### ISSUE TITLE
Instances with drain_timeout set , get stuck in "stopping(draining..)" state when they are added as targets to older Lb instances that dont support drain.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10013]
Rancher versions: upgraded to v1.6.11-rc1

Steps to reproduce the problem:
Fresh install of Rancher versions: v1.6.10. 
Have LB with few target services- S1 and S2.
Upgrade to  v1.6.11-rc1.

Scenario 1:
Upgrade service S1 and add drain_timeout parameter.
Older containers get stuck in "stopping(draining..)" state forever.
Why would the older containers be stuck in when they do not even have  drain_timeout parameter set yet?

Scenario 2:
Add new  service S3 with drain_timeout parameter.
Added this service as a target to one of the existing LB services.
Upgrade service S3.
Older containers get stuck in "stopping(draining..)" state forever.

**Comment by prachidamle** [comment]
- Why would the older containers be stuck in when they do not even have drain_timeout parameter set yet?

drain_timeout parameter is added at the service launch_config level, so during upgrade if it is added, it would apply to all containers of the service

- Now why Older containers get stuck in "stopping(draining..)" state forever?
I assume the LB image is not upgraded even if rancher/server is upgraded to latest code. 
So rancher/server will start sending out drain events and wait for a reply to the event from the LB to proceed with the stop. However since the LB is not upgraded, it is not listening to any events.

So the upgrade of the target service is stuck. @cjellick @sangeethah

**Comment by cjellick** [comment]
needs lb image v0.7.12-rc1 before testing

**Comment by deniseschannon** [comment]
New image will be v0.7.13.

**Comment by prachidamle** [comment]
The fix here is that, rancher/server will not send drain events to LB's with old images. That way the container stopping is not stuck forever due to events being not replied by LB.

Drain events will only be sent to LB's with the latest images that support draining.

**Comment by sangeethah** [comment]
Rancher versions: upgraded to v1.6.11-rc3

Steps to reproduce the problem:
Fresh install of Rancher versions: v1.6.10.
Have LB with few target services- S1 and S2.
Upgrade to v1.6.11-rc3.

Scenario 1:
Upgrade service S1 and add drain_timeout parameter.
Upgrading service S1 works as expected.

Scenario 2:
Add new service S3 with drain_timeout parameter.
Added this service as a target to one of the existing LB services.
Upgrade service S3.
Upgrading service S3 works as expected.
