### ISSUE TITLE
Remove per-host-network container, host routing information is not cleared.

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10075]
**Rancher versions:**
rancher/server: v1.6-development
rancher/net:v0.13.0

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Create a new environment with Use per-host-network.
2. Add host with label "io.rancher.network.per_host_subnet.subnet=xx.xx.xx.xx/xx".
3. Remove per-host-network container.
**Results:**
Host routing information is not cleared.

https://github.com/rancher/rancher/issues/9153

**Comment by niusmallnan** [comment]
Yes, this is a problem.
Now we should assume that the user is prohibited from modifying the `per-host-subnet` host label.

In the UI to prohibit users to edit `per-host-subnet` host label, I recommend doing so.
@yasker

**Comment by yasker** [comment]
@kingsd041 Are the reproduce steps right? @niusmallnan mentioned that label was changed/removed before removing per-host-network container.

**Comment by niusmallnan** [comment]
@yasker 
Oh, I think I may have missed some. 
This should have two cases about `Host routing information is not cleared`:
1. Host routing information is not cleared while removing `per-host-subnet` container.
2. Host routing information is not cleared while users change/remove the `per-host-subnet` label

For case#1:
Maybe I should trap the `stop/kill` signal, then do some cleanup logic.

For case#2:
As I said above, disable editing the `per-host-subnet` host label in the UI, is a simple way.

**Comment by yasker** [comment]
@niusmallnan 

Case 1: `per-host-subnet` container is an infrastructure service container, I don't think we expect the user to destroy it. And the recovery sounds good. Case #1 is fine.

Case 2: The user experience will be weird if we disable modifying on the UI. The user should have a way to update the host subnet after adding it. It's a configuration, the user should be able to change it, though it may mean we(or the user) have to restart certain services and make other operations to get it all wired up correctly again. But in general, it's a bad user experience. A user has to jump multiple hops to get the configuration updated, and it's all manual.

Do you have a sequence of operations user needs to do in order to update a `per-host-subnet`if it's possible?

**Comment by niusmallnan** [comment]
@yasker 

Case 2: We don't want users to update those labels. This has been documented.
https://github.com/rancher/rancher-catalog/tree/v1.6-development/infra-templates/per-host-subnet/0#requirements

If we still want to do that, we should record history routes what we added(need to know which routes are we add), and refresh all containers' IP for the new subnet.  Perhaps in this process, users also need to reboot the host.

**Comment by yasker** [comment]
@niusmallnan I see. Then it makes sense to disallow user to change it from UI.

@loganhz Can you check if it's doable from UI?

**Comment by yasker** [comment]
In fact, @kingsd041 please fill another issue to reflect the case 2 from @niusmallnan .

This one can be closed as `won't fix` then.

**Comment by loganhz** [comment]
@yasker we can hide `io.rancher.network.per_host_subnet.subnet` in edit host page.

**Comment by yasker** [comment]
Thanks @kingsd041 , close this one as won't fix.
