### ISSUE TITLE
With drain_timeout set on primary service , LB ip access results in 504 Gateway Time-out

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10090]
Rancher server version - v1.6.11-rc3

Steps to reproduce the problem:
Create a service with drain time out set to 25sec  and a sidekick.
Create LB service and add this service as a target.
Access LB IP . When LB ip is still is connecting , upgrade service.
LB ip access gets ```504 Gateway Time-out``` error after about 50 secs.
Drain timeout was hit in this case after 25 sec, after which service container was stopped.
Even after this, LB connection was not closed and only after about 50 secs LB ip access gets ```504 Gateway Time-out``` error .

```
Sangeethas-MBP:testwget sangeethahariharan1$ wget http://35.202.138.141:9001/connect
--2017-10-11 16:11:55--  http://35.202.138.141:9001/connect
Connecting to 35.202.138.141:9001... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
2017-10-11 16:12:46 ERROR 504: Gateway Time-out.
```

**Comment by prachidamle** [comment]
Seems same underlying issue as for https://github.com/rancher/rancher/issues/10006

**Comment by prachidamle** [comment]
Found that this reproduces when LB and the target service are running on different hosts.  
After a connection is established to the target service on other host, if the haproxy process reloads due to some metadata changes,  (this is a soft reload - a new haproxy process is spawned, but the old process still exists until existing connection completes), the established connection never completes and is ultimately killed by timeout on haproxy.


If LB and target service lie on the same hosts, the haproxy reload does not cause such an issue.

**Comment by prachidamle** [comment]
Root cause: The ipsec tunnel is removed for stopping containers.
And this happens once metadata change is received by ipsec where the container is seen "stopping".

Ticket https://github.com/rancher/rancher/issues/9561 is the ipsec issue

**Comment by sangeethah** [comment]
Closing this as the root cause foe both these issues are the same - https://github.com/rancher/rancher/issues/10006
