### ISSUE TITLE
How to find the local account or password when we forgot it.

### ISSUE THREAD

**Issue by soulswords** [rancher/rancher#10095]
*Describe your issue here*
I find that If we forgot the account or password of the Rancher when I open the Access Control, we have no idea to find back. 
There is only one way to resolve the issue which is in Rancher FAQ Troubleshooting-AUTHENTICATION 
clear the api.auth.provider.configured value
We must login the host of the Rancher Server or  Database Server.
I suggest that we need API or Guide to find the local account and password.
It will be more easily for user,
Because we can do nothing when we can not login the Rancher Server host or database.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.7` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`stacks.index`|

**Comment by vincent99** [comment]
The point of access control is that you can't access it without the credentials.  By what mechanism do you expect to be able to recover it reset the password?

The cleartext password is not stored and there is (intentionally) no way to recover it from the hash that is.  We're have no email address and no mechanism for sending emails because it's running on your arbitrary hardware. If you can run another container on the same machine as the server., then you already have access to the database.

**Comment by superseb** [comment]
Only option is to disable auth and reconfigure it back.

https://rancher.com/docs/rancher/latest/en/faqs/troubleshooting/#help-i-turned-on-access-controldocsrancherv16enconfigurationaccess-control-and-can-no-longer-access-rancher-how-do-i-reset-rancher-to-disable-access-control
