### ISSUE TITLE
Deleting a rancher secret should delete secret

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#10128]
**Rancher versions:**
rancher/server: 1.6.10

**Steps to Reproduce:**
Setup rancher secrets. Run a container service with a created secret.

**Results:**
Remove secret and observe that services still using the secret can access it.

Goal: deleting a secret should remove it everywhere for current and any subsequent usage.

**Comment by vincent99** [comment]
That is a non-goal, because it breaks existing running applications (either immediately if they re-read the secret into memory regularly, or on restart if they don't).  If that value is no longer valid you create a new secret and upgrade the services using it, which will then have the new value (and not have the old one).

If anything, a secret should refuse to delete while there are active references to it... But once the secret value has been pushed down to containers the cat is out of the bag, you can't push the cat back in by trying to clean it up later.

**Comment by cloudnautique** [comment]
Secrets are injected as part of the volume create process to ensure they are available before the container starts. The volume driver obtains the secret writes  it once and then stops monitoring it. It does look like there is a bug, when the container is stopped or deleted the volume driver steps in again to clear the contents. It looks like one of the references isn't getting cleaned up and the secret is still available. Need to take a look at that. This would cause the service to break though, as it would no longer have access to data that it needs to startup.

In 2.0 this behavior will change as we build on top of K8s. The K8s secrets update the files when they change. I don't think they do anything to the env vars though.

**Comment by flaccid** [comment]
Thanks guys. @cloudnautique I do believe that bug situation you mentioned exists. In some cases where you'd expect the secret to be gone (not on running/immutable services) it is still there.

**Comment by wargamez** [comment]
I really hope this gets fixed for 1.6

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
