### ISSUE TITLE
Test login failed for AD automation using API keys

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#10189]
**Rancher versions:**
rancher/server: v1.6.11-rc4

Noticed several failures in AD automation in rc4 that doesn't reproduce in the previous rc, according to @mrajashree there is a different way of sending data in the API and UI which caused the issue.

**Comment by mrajashree** [comment]
The UI flow and API flow differ, in that the UI sends token in cookies, API call would have to first do a login to get the token and then pass it. 
So the tests failed because they weren't passing token in cookies.
The UI will change to pass no username in testlogin call.
The auth-service will change so that, if the username is empty, then it will use token.originalLogin, if not then just use whatever username is passed
The current validation tests test the API flow, one test needs to be added for the UI flow, to create a token and pass it in the testlogin api call

**Comment by mrajashree** [comment]
//releases.rancher.com/ui/stable
UI tag^

**Comment by galal-hussein** [comment]
@mrajashree AD validation passed successfully on Rancher v1.6.11-rc6
