### ISSUE TITLE
rancher-auth-service only performs case sensitive attribute matches

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10205]
**Rancher versions:**
rancher/server: v1.6.10

**Steps to Reproduce:**
1. Configure Active Directory as Access Control in v1.6.7 and use `User` as `Object Class`.
1. Login works as expected matching `User` as `Object Class`
1. Upgrade to v1.6.10 (new auth service)

**Results:**
Access is denied. When we change the value from `User` to `user` before upgrading to v1.6.10, login works as expected.

Logging:
```
2017-10-20T19:08:09Z" level=debug msg="Failed to determine if object is type: User" 
2017-10-20T19:08:10Z" level=error msg="GetToken failed with error: User identity not found for Ldap" 
[.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500, message: User identity not found for Ldap
```

**Comment by sangeethah** [comment]
Tested with fresh install of rancher-server built from v1.6 branch.

Able to successfully enable AD auth when providing attribute names in "Customize Schema" in different case(upper/lower/mixes).

There are other issues seen when using "Name Field" for User and Group to "NAME" (instead of the the default value name) and "Login Field" to "SAMAccountName" - 
https://github.com/rancher/rancher/issues/10227#issuecomment-339826876
