### ISSUE TITLE
Validate that ECR Credentials Updater catalog entry works on Windows

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#10329]
Validate that ECR Credentials Updater catalog work on Windows.

Need ensure that ECR credentials do not expire after 12 hours and that images can be pulled.

**Comment by orangedeng** [comment]
I think it we can make ECR updater work out side of windows environment. ECR updater can just run in a linux environment and put the `CATTLE_URL `, `CATTLE_ACCESS_KEY ` and `CATTLE_SECRET_KEY ` of windows environment into it. Then RCR updater can runs and update credentials for windows environment. 
I think we can let @kingsd041 test for it.

**Comment by kingsd041** [comment]
@orangedeng I test according to your steps, it has been 16 hours, ECR credentials have not expired and that images can be pulled.

**Comment by deniseschannon** [comment]
We will need to officially document this setup as it's different than a normal setup. 

@superseb Could you help make a PR?

**Comment by superseb** [comment]
I can create docs on this, is everything required to make this work complete? Are we letting people manually update the catalog item to adjust the environment variables or are we going to make variables to the catalog item to override `CATTLE_*` variables which are normally automatically created because of the `agent.role` label?
