### ISSUE TITLE
Can't communicate between managed container and container with host networking across hosts using vxlan

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10344]
**Rancher versions:**
rancher/server: v1.6.11
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
vxlan: v0.3.0
network-services: v0.2.7

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 Ubuntu 16.04.3 LTS (with KVM) (4.4.0)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle (with vxlan)

**Steps to Reproduce:**
1. Create env with ipsec disabled and vxlan enabled
1. Add 2 or more hosts
1. Run global service with `nginx` as image
1. From a container with host networking, try `curl`ing the managed IP of the nginx container on another host

**Results:**
1. `curl` will timeout

This will affect k8s as well, as those components run host networking and have to connect to the kube-apiserver.

**Comment by niusmallnan** [comment]
@superseb 
The communication within the overlay network works perfectly fine. Just the communication between a host and a container on another host doesn't work because the host itself is not part of the overlay network.
Docker VXLAN also has this problem, see this: https://github.com/moby/moby/issues/18357

But we all know that our previous VXLAN version did not have this problem,  we ran the VXLAN service in a container(this container likes a router), and ran proxy arp that containers can get the right MAC.
We can not get a good network performance this way, so we build a new VXLAN.

@leodotcloud @yasker ^^^

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.12-rc1 using vxlan version -v0.3.1 which uses rancher/net:v0.13.1	for cni-driver and rancher/net:v0.11.9 for vxlan-router.

Steps to Reproduce:
Create env with ipsec disabled and vxlan enabled
Add 3 hosts
Run global service with nginx as image
From a container with host networking, able to reach managed ip of all the containers of the global service.

**Comment by leodotcloud** [comment]
*Steps to recover from a broken setup:*
1) Upgrade rancher/server from 1.6.11 to 1.6.12
2) Upgrade vxlan stack
3) `ip link delete vtep1042` on all the hosts
