### ISSUE TITLE
When new environment created, pipeline-server is constantly pinging and returning a 503

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10405]
**Rancher versions:** v1.6.10

**Steps to Reproduce:**
1.  Create a new environment
2.  Go to the new environment
3.  Open up Dev tools

**Results:** pipline-server:60050/v1 is constantly pinging.  Service should not try and start until at least 1 host is available.
![image](https://user-images.githubusercontent.com/11514927/33282536-33ce4b6c-d366-11e7-949c-4c168b2dd9ea.png)

> Get 'URL'/r/projets/1a23/pipline-server:60080/v1 503 (Service Unavailable)

**Comment by biblesyme** [comment]
Fixed it in (http://35.202.69.220:8080/)

## problem analysis
After long time investigation.
I found this problem is caused by two main reasons.
Firstly, the slow networking.
Secondly, some vulnerable codes caused competition for `store.baseURL` in async callback. 

These problem won't be emerge in good networking conditions. When networking is bad enough, these two factors caused this problem and other two issues( (https://github.com/rancher/rancher/issues/10408) (https://github.com/rancher/rancher/issues/10407)).

**Comment by tfiduccia** [comment]
Now if the host is not setup, I get 
![image](https://user-images.githubusercontent.com/11514927/33337271-b08ae16e-d42f-11e7-8dc2-9c19e9538183.png)

**Comment by biblesyme** [comment]
Do you mean a new environment with none hosts added? 
I switched between `Default` and `newEmpty` in http://35.202.69.220:8080/, I didn't encounter this problem.

If you tested in another environment deployed according to deploy guide. Then your version is outdated. I will update the files link in deploy guide to the latest today.

**Comment by tfiduccia** [comment]
Version - master 12/5
Verified fixed
