### ISSUE TITLE
Rancher 2.0 : cannot add host with google driver

### ISSUE THREAD

**Issue by olivierboudet** [rancher/rancher#10446]
Hello,

There is an javascript error when adding host with docker-machine and google driver : 
```
Subscribe ping (projectId=1a37, sockId=1)
ember.prod.js:16692 TypeError: Cannot read property 'get' of undefined
    at i.<anonymous> (host-driver.js:70)
    at c.h.get (ember.prod.js:16079)
    at Object.r [as get] (ember.prod.js:20968)
    at i.get (ember.prod.js:33591)
    at i.<anonymous> (host-driver.js:164)
    at c.h.get (ember.prod.js:16079)
    at Object.r [as get] (ember.prod.js:20968)
    at i.get (ember.prod.js:33591)
    at i.willSave (host-driver.js:178)
    at i.n [as willSave] (ember.prod.js:37638)
r @ ember.prod.js:16692
subscribe.js:185 Subscribe ping (projectId=1a37, sockId=1)
23subscribe.js:185 Subscribe ping (projectId=1a37, sockId=1)
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha9` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`authenticated.clusters.index`|

**Comment by deniseschannon** [comment]
As of the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!

Note: For google, there are some known limitations due to using docker-machine. You can use the GKE cluster to start up google instances!
