### ISSUE TITLE
unable to create a user in rancher server from access control in webui

### ISSUE THREAD

**Issue by sivajibhai** [rancher/rancher#10463]
While create an user account from access control i filled all the details when select enable local Auth tab showing error

<img width="853" alt="error_image" src="https://user-images.githubusercontent.com/20254517/33515610-a9bf642c-d78b-11e7-9fc5-bed9fe756cc0.PNG">

**Comment by superseb** [comment]
What version are you on, is this from scratch (only running `rancher/server` and not having enabled a different auth mechanism before), and what does the logging inside the `rancher/server` container look like when you submit the request?

I think, because the error is undefined, the `rancher/server` is not running/reachable at the point you submit to active access control.

**Comment by superseb** [comment]
Please report back so we can investigate.
