### ISSUE TITLE
There is no stable tag for rancher/agent to go along with rancher/server:stable. Please fix this.

### ISSUE THREAD

**Issue by dbsanfte** [rancher/rancher#10483]
There is a stable tag for rancher/server, but no stable tag for rancher/agent. There is a latest tag, but this isn't updated reliably and in any case I'd expect it to be out of sync with stable. 

Our deployments are fully automated, and we really need a stable tag on rancher/agent to go along with the stable tag on rancher/server. Manually updating these ad-hoc in our Azure templates just isn't sustainable. 

I suspect I'm not alone in this either.

**Comment by dbsanfte** [comment]
Speaking of which, there is a v1.2.6 for rancher/agent but rancher/agent:latest is still at v1.2.5...

**Comment by vincent99** [comment]
The correct image to use is provided in the registration command shown in the UI, or `registrationToken` in the API if you want to automate it.  Using `latest` is a bad idea*, may break at any time, and eventually definitely will.

As a simple example, if you spin up a new host on your 1.6.x the day after Rancher 2.0 becomes `server:latest`, it will pull the 2.0 agent and be totally incompatible with your server.

[*]: Both for this and for anything in general... mutable named tags are the single worst decision in the Docker UX and a landmine patiently waiting for you to blow your foot off on any environment with more than one host.

**Comment by dbsanfte** [comment]
> The correct image to use is provided in the registration command shown in the UI

This isn't good enough. If the entire environment is down, I can't get to rancher/server to tell what agent versions should be spun up.

If you provide a rancher/server:stable, you need to provide a rancher/agent:stable.

**Comment by vincent99** [comment]
No.  It doesn't matter what the label is called, any fixed word is guaranteed to be the wrong version for the version of rancher some of the time.

**Comment by dbsanfte** [comment]
Then why are you providing :stable at all? What's the point?

**Comment by vincent99** [comment]
You have one (or a few) long-lived server containers, and need a command to run the server in docs and such, so we provide `rancher/server:stable` and `:latest` to give you the current version at that time.  The only time it being a fixed word bites you is if you later decide to do HA and `stable` is no longer the same version as it was when you started the first server.

For the agent, users have many hosts coming in multiple environments over weeks or months.  When a new server is registered, it needs to use the right version of the agent for the server it will register to.  And it needs a token to authenticate itself to that environment.  So the `registrationToken` (and command shown in the UI by extension) provide both.

You could be running Rancher 1.0.0 from two years ago right now, but if you add a host it still needs to work.

**Comment by dbsanfte** [comment]
Fair enough, that's an argument for not using a keyword that I'll accept.

It's not an argument for not providing a matching :stable on both targets so I can look them up before I write their matching version tags in the deployment template. As it stands I have to spin up the server first before I can update the templates. That's silly.

**Comment by vincent99** [comment]
Every release announcement includes the appropriate image versions.  https://forums.rancher.com/t/rancher-release-v1-6-12/7948

**Comment by dbsanfte** [comment]
> Stable - v1.6.12 - rancher/server:stable

And you advertise the tags that we're not supposed to reference or use...

¯\_(ツ)_/¯

**Comment by superseb** [comment]
I've been back and forth on this one but..

Regarding `rancher/server`, Vincent already explained why we provide `stable` and `latest`.

Regarding `rancher/agent`, this is a component depending on the used `rancher/server`. The best way to launch `rancher/agent`, is to retrieve it through the API of the `rancher/server`. (and this can be automated easily). For the use-cases where this is not an option, we supply all the needed versions for your own automation (release announcement). In case you can't use the fully automated route, you can use your own scripting/automation with these images.

My first attempt was going `rancher/server:stable` + `rancher/agent:stable` as `rancher/server:latest` + `rancher/agent:latest`. But as we can't guarantee those tags in all environments, it will be hard to use (or support). Of course, we do support running an older version while upgrading, as it will be upgraded automatically. But we can't see what image `rancher/agent:stable` or `rancher/agent:latest` is in an environment, so it could be way old and incompatible. Seeing that we support a specific `rancher/agent` to a `rancher/server`, my suggestion would be to remove `rancher/agent:latest` and only keep versions. This way it should be clear, only proper image versions should be used as tag to `rancher/agent`.

**Comment by ItsReddi** [comment]
@superseb if you talk about receiving the correct version via api
you mean: v2-beta/settings -> bootstrap.required.image ?

anyway, the current way of updating / setting correct version of new agents could be enhanced.
whats about checking at startup (and periodically) of an agent if version is correct, otherwise update it?

"Of course, we do support running an older version while upgrading, as it will be upgraded automatically."
Well, yeah if the hosts are healthy at the moment of upgrade the agents are updated.
But if not, the hosts will staying at the old agent. (Because of that a periodical check would be good)

If this would be done, anyone could use the stable tag, to get the latest stable version for the active server version.

**Comment by vincent99** [comment]
The reality is the image containI just the dependencies needed for the agent.  The actual appropriate agent binary that is run is retrieved from the server (as-needed) every time the agent connects.

The agent container itself (i.e. it's docker id) never changes during an upgrade because creating a new container and deleting the current one, from itself, creates situations that are hard to recover from when something goes wrong.  So the agent is forward-compatible with any server newer than the current one at the time the agent image shipped.

But that does not work the other way, we're not going to guarantee that agent:latest is always going to be backwards compatible with every possible version of server in perpetuity and will work if registered to e.g. server:v1.0.0 as I said earlier.
