### ISSUE TITLE
rancher env/statck user Privilege

### ISSUE THREAD

**Issue by jinghuaz** [rancher/rancher#10508]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 0.6.5

Hi guys:
   Rancher user privileges are configured to the environment, but I want to ask if you can configure it to stack？ means User privileges are limited to stack.

**Comment by cjellick** [comment]
No, access control is only at the environment level in v1.6

**Comment by jinghuaz** [comment]
Is there a plan to limit permission control to stack?

**Comment by vincent99** [comment]
Not directly, it doesn't really work out very well usability-wise.

But in 2.0 a cluster (set of hosts) can be shared between multiple projects (environments) which then have their own namespaces (stacks).  So Roles are still assigned to users/groups on the project level, but you can create several and share hardware instead of having to have new hosts dedicated to each environment.
