### ISSUE TITLE
Soft affinity and affinity rules behave the same when used with global label set to "true".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1053]
Server version - Build for master - jun/04

Steps to reproduce the problem:

Have host1 - with label - a=b
Have host2 - with label - a=b
host3 and host4 have no labels.

Create a service with "Always run one instance of this container on every host" option and scheduling rule as  "host SHOULD have a host label - a=b" 

Activate service.
Containers get deployed in host1 and host2.
This is the same as having a affinity rule defined as "host MUST have a host label - a=b"

Do we expect soft affinity to do anything different than affinity rule in cases where global is true?

**Comment by will-chan** [comment]
There should be no difference between soft and strict for global.  Global means deploy 1 container for a given service matching the host tag.  Since there can never be more than 1 container per host as defined by the host tag, soft or strict should not come into play.

**Comment by vincent99** [comment]
So should I not offer the "should" options for services set to global?

**Comment by will-chan** [comment]
Ideally, if I select the "Global" option, you should just give them a text box to add host labels (optional of course) right next to it. The actual label can be must or should because it should not matter.

It's not clear that after selecting "Global", you are suppose to add a host affinity rule (or at least have the option to).  Also, when you select Global, technically all scheduler rules other than host affinity are no longer valid or won't be used.  Might be worth to disable schedule altogether if "Global" is chosen.

**Comment by vincent99** [comment]
You have the same problem with regular scale not knowing that you can set scheduler rules, so if it's not clear for global it's not clear for anything.  I don't want to have a 4th place to manipulate labels on the screen (and what happens when you turn global back off, those labels disappear and go to the scheduler tab?)

(Besides that it's simpler and how we programmed it,) why does global need to be a special case that ignores other kind of rules?  It seems like it should act as "automatic scale" where a container is run on every host that meets the rules regardless of what the rules are.

**Comment by will-chan** [comment]
The way it is implemented, if "Global' is set, only host affinity is applied.  It makes sense because Global means to deploy a single container into a host tagged as "X".  All other affinity rules don't make sense anymore, or at least would make understanding what you really want very complicated.  I see Global as a special scheduler rule that basically means "Deploy a container into a host with host tag "X"".  It only gets triggered when a host is added or a label applied.  That's it.  If I wanted to start mixing and matching rules, I should probably start using normal scheduling policies.

A scale means all scheduler rules would apply.

**Comment by will-chan** [comment]
Moving it to post-beta to discuss what we want for global.

**Comment by vincent99** [comment]
`_soft` ("should" and "should not") are removed now if global is set, as are all the conditions except "has a host label" for now.  We should still test that part for beta, then move this to 1.0 to discuss or open a separate issue.

**Comment by will-chan** [comment]
Ok, let's at least verify what Vince has said.

**Comment by sangeethah** [comment]
On latest master (Jun/08) builds, When "Always run one instance of this container on every host" is picked , we have only conditions - "must/must not" , field = "host label" with key and value.

**Comment by will-chan** [comment]
Closed as verified by sangeetha as only strict mode is allowed in UI.
