### ISSUE TITLE
a registered cattle host, is active before cattle template is aplied

### ISSUE THREAD

**Issue by BobVanB** [rancher/rancher#10577]
**Rancher versions:**
rancher/server:
Rancher | v1.6.12
Cattle | v0.183.30
User Interface | v1.6.30
Rancher CLI | v0.6.5
Rancher Compose | v0.12.5

rancher/agent:
"dockerVersion": "Docker version 17.06.1-ce, build 874a737",
"kernelVersion": "4.9.45",
"operatingSystem": "RancherOS v1.1.0"
agent_image": "rancher/agent:v1.2.7",

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version:
"dockerVersion": "Docker version 17.06.1-ce, build 874a737",

**Operating system and kernel:**
Rancher-Os 

**Type/provider of hosts:**
Bare-metal

**Setup details:**
Rancher HR, external postgres db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. add a virtual machine
2. add multiple infrastacks to the default cattle template
3. execute cattle command on virtual machine
4. wait until it pops up in rancher environment
5. wait for status is active
6. see that the containers are still starting

**Results:**
Step 5: Host status is `active`
```
{

    "id": "1h7862",
    "type": "host",
    "links": { … },
    "actions": { … },
    "baseType": "host",
    "name": null,
    "state": "active",
```
Step 6: System stack instances is `starting`
```
{

    "type": "collection",
    "resourceType": "instance",
    "links": {
        "self": "…/v2-beta/projects/1a1217603/hosts/1h7862/instances"
    },
    "createTypes": {
        "container": "…/v2-beta/projects/1a1217603/containers"
    },
    "actions": { },
    "data": [ 9 items
        {
            "id": "1i1400186",
            "type": "container",
            "links": { … },
            "actions": {
                "stop": "…/v2-beta/projects/1a1217603/containers/1i1400186/?action=stop"
            },
            "baseType": "instance",
            "name": "healthcheck-healthcheck-7",
            "state": "starting",
```

**Expected Result**
```
{

    "id": "1h7862",
    "type": "host",
    "links": { … },
    "actions": { … },
    "baseType": "host",
    "name": null,
    "state": "starting",
```
1. i would like to know that the cattle-template is not applied yes.
2. i would like to know that the system instances are still starting.
3. i would like that the states of the instances bubbles up to host state / stack state.
4. i would like to see a separate state for system instances
```
{

    "id": "1h7862",
    "type": "host",
    "links": { … },
    "actions": { … },
    "baseType": "host",
    "name": null,
    "state": "active",
    "system_state": "starting",
```

**Comment by vincent99** [comment]
This is not going to happen.  It _does_ work that way for healthState from containers->service->stack,  and for state from container->service, but there is a direct relationship where a service knows it is or isn't still being scheduled.

There is no inherent "doneness" or preallocation/direct relationship to know if more containers are going to be scheduled to a particular host than are currently on it.

So what you're asking is for the host state predict if _future_ scheduling decisions will, during an indefinite period of time in the near future, result in more containers starting on it.

And a healthState on host that is an aggregation of container healthStates doesn't really make any sense, the host is not necessarily bad because something scheduled to it is.

**Comment by BobVanB** [comment]
@vincent99 went through it again, indeed i agree :*(
