### ISSUE TITLE
 failed to activate image of java jar running on openjdk

### ISSUE THREAD

**Issue by jrdbls** [rancher/rancher#10611]
Rancher versions:**
```
rancher/agent:v1.2.6
rancher/server:stable 
```

**Infrastructure Stack versions:**
```
rancher/healthcheck:v0.3.3
rancher/net:v0.11.9
rancher/metadata:v0.9.4
rancher/network-manager:v0.7.8
rancher/scheduler:v0.8.2
```

**Docker version: (docker version,docker info preferred)**
```
Containers: 19
 Running: 16
 Paused: 0
 Stopped: 3
Images: 32
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-4-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.778GiB
Name: docker01
ID: JBEI:VXPV:P2I5:2R6J:HYCK:JT7P:OIC7:ESNB:Z5WU:UGAM:D7FV:PVMK
Docker Root Dir: /home/dockserver/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (cat /etc/os-release, uname -r preferred)**
```
uname -r : 4.9.0-4-amd64
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node ranche

**Steps to Reproduce:**

Basically I am trying to run a java JAR file, in this case Leshan server, that has been tested to run correctly out of the docker environment.

Dockerfile uploaded to github:

```
FROM 		openjdk:9
COPY /home/dockserver/stacks/leshan/compose/code /usr/src/leshan
WORKDIR /usr/src/leshan
RUN java -jar leshan-server.jar -slp 5684
```

docker-compose.yml:

```
version: '2'
services:
  leshanserver:
    build: <github raw url>
    ports:
     - "9200:8080"

```

Command to run:
`rancher-compose -p leshan up -d`

Results:
On the Rancher gui:

leshanserver (Expected state running but got error: ImageActivate: failed to activate image) 

ERROR	service.activate.wait.exception	Expected state running but got error: ImageActivate: failed to activate image

I don't know where I can get more detailed logs to see what the error is. 

If I run this commands service gets up correctly:
`docker build -t leshan .`
    (With the same local docker file)

**Comment by eesprit** [comment]
You are confusing some things there :
"docker build" is used to build images, not running them.
In your Dockerfile, you don't want to RUN, but you want to define a CMD.
That's why it is "working" when building the image.
It's totally normal that it doesn't work in Rancher (or any other Docker container management system).

**Comment by jrdbls** [comment]
I am sure I am confusing things but I am not sure which ones :).

I have adapted it to this, following to :
```
FROM            openjdk:9
COPY ./code /usr/src/leshan
WORKDIR /usr/src/leshan
CMD java -jar leshan-server.jar -slp 5684
```

It works as I understand is correct: after build and run commands. Previously it was running after build.

I am receving the same error on rancher. Container is failing to activate.

**Comment by superseb** [comment]
It's not totally clear where the problem lies as not all information is present. If you run a container using Rancher, it gets scheduled to an added host and that host will try to pull the image from a registry. First question is, are you building the image on the host running the container or not? If so, it should use the locally built image to start, if not, the host has no way to download the image needed to run the container.

The UI should show you a more precise error of image failing to activate, either in `rancher/agent` container logging of `rancher/server` container logging.

**Comment by superseb** [comment]
Please reply if you need help on this.
