### ISSUE TITLE
docker-machine always opens "0.0.0.0/0" on ports 22, 2376 when creating new AWS instance

### ISSUE THREAD

**Issue by cyphrsonic** [rancher/rancher#10619]
This seems to be an expression of this issue in docker-machine: https://github.com/docker/machine/issues/3810 - Is this something Rancher can patch in docker-machine, or at least reedit the image after docker-machine is invoked? This would go a long way to securing our infrastructure. 

**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.1.4
network-services: 0.2.6
scheduler: 0.6.3
kubernetes (if applicable): 1.8.5-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
17.0.3.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Rancher OS 1.10

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher w/ External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Custom Kubernetes

**Steps to Reproduce:**
1. Add new Machine to a Kubernetes cl;uster hosted on AWS with Clone Command or "Add New Host" Screen

**Results:**
1. docker-machine updates rancher-machine security group with a "0.0.0.0/0" for port 22 (ssh) and 2376 (docker port). This is an insecure setting in our environment and violates our security policy.

**Comment by vincent99** [comment]
The reason it's added is because docker-machine has to SSH to the host to install docker and you cannot necessarily determine what the right IP to whitelist is, or assume that it will be the same IP a day or a year later when you want to perform some other action on that machine.  So all the providers either have no firewall by default, or the machine driver opens them up to any IP.

All the same problems apply when running machine from inside Rancher.  So just unconditionally hacking out the code to add the ports is not a solution.  And removing them after the fact doesn't really work, depending on the the provider there is no way to tell the difference between 22 was just added by machine or it was already there intentionally and you're breaking it.

It would have to be an option like `--i-am-NOT-a-dummy` (à la MySQL) to skip creating firewall rules, for each driver individually, disabled by default, and if you enable it then you're responsible for ensuring that the box running machine can reach the new instance.  This is something we'd probably expose if it was an option, but not something we really want to maintain as a patch.

Or on a more practical note, you don't _have_ to use the machine driver.  If you're using Amazon anyway creating an autoscaling group and using userdata to run the registration command works well.

**Comment by cyphrsonic** [comment]
Thank you for the prompt response. That makes a lot of sense, and I understand why that's a difficult challenge. I'll look into using an AWS autoscale group for our scaling. 

I don't know about the other cloud providers, but at least in the case of AWS the CIDR block the machine will be created in is predictable since it will be in the range assigned to the VPC. I'll continue to work with the docker-machine team and see if they view the lack of a customizable CIDR block as something in scope.

**Comment by vincent99** [comment]
It's the other way, you need the new VM/firewall rule to know what the source IP of requests from the machine where `docker-machine` is being run from to the host _will be_ if a connection were made.  For us this would be the machine running the rancher/server container (or containers if HA).

You may have your server host in the same VPC as your worker hosts, but that does not have to be the case.  And the IP(s) does not necessarily stay the same over time, but we don't actually use `docker-machine ssh` or similar once the host is registered (since we have our own agent connected)... so that isn't necessarily a concern for Rancher.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
