### ISSUE TITLE
[Auth] 400 Bad Request: invalid header value error when trying to enable AD authentication

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#10690]
Try to enable AD authentication in access control. The account used for authentication test is in a OU which has two levels with Chinese characters, like this: CN=RancherAdmin,OU=各系统域控用户,OU=功能组,DC=mf,DC=com. The test and enable authentication failed with error "400 Bad Request: invalid header value"

Move the user account to upper level, like this: CN=RancherAdmin, OU=功能组,DC=mf,DC=com. Then the AD authentication can be enabled successfully. It seems there are some problems in this logic and Rancher can't handle OU with more than two level Chinese characters successfully. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.13` Cattle: `v0.183.35` UI: `v1.6.34` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`admin-tab.auth.activedirectory`|

**Comment by loganhz** [comment]
Reason:

1. Cattle gets a token form `rancher-auth-service` by sending `/v1-auth/token`. 
2. Cattle uses this token to call other API in rancher-auth-service by putting this token in `Authorization` header.
3. HTTP request can not ensure everything works well with Chinese characters in http header.

Solution:

1. encode the token in `rancher-auth-service` before returning it to cattle. 
2. decode the `Authorization` header first before using it in `rancher-auth-service`.

**Comment by lexapi** [comment]
have any plans?

**Comment by genuss** [comment]
I made a quick fix here https://github.com/rancher/rancher-auth-service/pull/57

**Comment by prachidamle** [comment]
@loganhz why does this issue happen only when the user's account has 2-level OU parts with chinese character and not when there is a single OU?
If its a problem of encoding, even a single OU should fail I assume. Or  Is it that one of the OU's in this example has some character that is not handled by http correctly?

Do you happen to have any logs when you reproduced this problem? How did you find that it happens because of the authorization header?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
