### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#10743]
I have rancher v1.6.12 installed, where the Rancher home page is accessible from the public internet via https.

My company IT Security department reported however the following issue and may eventually take action and prohibit access from the public internet. Any thoughts about this issue? And how to resolve it?

![report](https://user-images.githubusercontent.com/10650187/34583872-53b09d9c-f191-11e7-9bcb-d33aadc542ea.png)

File in question: ``https://<host>/.DS_Store``

**Comment by vincent99** [comment]
The build script is already changed to remove them for future versions (after 1.6.13) because someone else asked about it.

(As far as thoughts: it's a ridiculous non-issue, it contains almost nothing but 6k of null bytes.  And the entire history of every file that's ever existed is in git since the UI is open-source, so there's no secret deleted files to leak info about.)
