### ISSUE TITLE
No validation done for  Subnet start/end ip address in ipsec service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10766]
Rancher versions: v1.6.13
Catalog: https://github.com/leodotcloud/rancher-catalog.git
Branch: regions

Steps to reproduce the problem:
Create a template with ipsec having invalid  Subnet start/end ip address w.r.to the subnet.
There is no validation done to prevent for this template to get created with incorrect values.

Create environment using this template.
Ipsec fails to start successfully because of mismatch between the bridge IP and the actual IP allocation.

We will not be able to correct this situation by upgrading ipsec stack and setting the correct values for subnet start/end ip address since the subnet start/end ip address entered on the upgraded ipsec container does not take effect.

**Comment by leodotcloud** [comment]
The catalog starts with valid default values and since networking is a critical component, we expect the user to know what's being changed if default values are not being used.

Also configuration changes done to existing IPSec template not taking effect is already a known behavior. (Example: MTU) Networking configuration cannot be changed on the fly, so it's expected to create a new environment with the correct settings.
