### ISSUE TITLE
`rancher ps` shows ENDPOINTS is empty

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10878]
**Rancher versions:**
rancher/server: v1.6.14
rancher cli version: v0.6.7

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-105-generic

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Add service or Load Balancer and set port map
![image](https://user-images.githubusercontent.com/19684717/34969944-61aad682-faac-11e7-9d20-82cc0d7a641c.png)
2. Use `rancher ps` to show ENDPOINTS for the service.
**Results:**
ENDPOINTS is empty.
```
root@iZ2zeccvnq6egust6e9rihZ:~# rancher ps
ID        TYPE                  NAME           IMAGE                                STATE     SCALE     SYSTEM    ENDPOINTS   DETAIL
1s7       service               test1/nginx1   nginx                                healthy   1/1       false
1s8       loadBalancerService   test1/lb1      rancher/lb-service-haproxy:v0.7.15   healthy   1/1       false
```

**Comment by vincent99** [comment]
CNI drivers map ports by manipulating iptables rules, and the network is `--net=none` as far as Docker is concerned, so there are no endpoints that Docker knows about.

**Comment by hongxiaolu** [comment]
@vincent99  Hi, If because it is the CNI drivers reason, then if the bridge mode is used，Will the endpoints be shown here？

I created four services, which correspond to one of the four network models, but But no service can show endpoints.


<img width="1311" alt="test1" src="https://user-images.githubusercontent.com/20707603/35184932-cd2e9d02-fe36-11e7-8175-f3ac2965e887.png">

<img width="531" alt="test2" src="https://user-images.githubusercontent.com/20707603/35184950-053c8704-fe37-11e7-8438-4168895661d8.png">


<img width="1660" alt="test3" src="https://user-images.githubusercontent.com/20707603/35184940-dc85210e-fe36-11e7-8c86-c91eebf91bce.png">
