### ISSUE TITLE
Feature request: Multiple LDAP hosts for Access Control

### ISSUE THREAD

**Issue by rgruyters** [rancher/rancher#10939]
In Access Control for LDAP you can only use one LDAP host. For availability reasons we would like to add multiple hosts.

**Comment by superseb** [comment]
Thanks, we have an open issue for this here: https://github.com/rancher/rancher/issues/7858

**Comment by rbkaspr** [comment]
@superseb The issue referenced  above was closed due to support draw-down for Rancher 1.x, though the request was for any version of Rancher. Can we get this issue reopened so we can get Rancher 2.x configured with multiple LDAP hosts. Being limited to one limits the resilience of our infrastructure.
