### ISSUE TITLE
Creating RKE cluster using hosts from both AWS and Digital Ocean fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10981]
**Rancher versions:**
rancher/cattle:master build from Jan 18 night 

**Steps to Reproduce:**
1. Create a 3 node RKE cluster using one AWS host  and two digital ocean hosts
2. Cluster creation fails with the below error:
```
2018-01-19 18:45:32.017856 I | mvcc: store.index: compact 29703
2018-01-19 18:45:32.019463 I | mvcc: finished scheduled compaction at 29703 (took 1.006509ms)
E0119 18:49:41.260844       1 generic_controller.go:185] ClusterController cluster-kstjl [cluster-stats] failed with : Operation cannot be fulfilled on clusters.management.cattle.io "cluster-kstjl": the object has been modified; please apply your changes to the latest version and try again, [cluster-provisioner-controller] failed with : [netwok] Port check for ports: [x.y.z.a:2379, z.y.a.p:2380] failed on host: [a.b.c.d]
```
2379 and 2380 are opened for security group (rancher-nodes)in aws for aws nodes only

**Comment by deniseschannon** [comment]
This is combination of issues: 

1. The security group for `rancher-nodes` only opens up the necessary ports to allow communication between k8s between the nodes in AWS. 
2. We need TLS for etcd
3. we pass to RKE the AWS internal IP

**Comment by StrongMonkey** [comment]
We will add a field in machine called `useInternalIpAddress`
1. for aws: need to set `useInternalIpAddress` to true so that the internal ports between EC2 instances are open to each other. Only if we are using default security group.  (they are only open to internal Ipadress)
2. for DO. Doesn' t make a difference 
3. for Mixed. need to set `useInternalIpAddress` to false. The correct security group need to be configure to make sure ports are open between machines.

**Comment by deniseschannon** [comment]
Node pools in a cluster must be from the same cloud provider as there currently isn't a secure way to do cross cloud networking.
