### ISSUE TITLE
Owner of cluster/project can't delete/modify original creator of cluster/project

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11056]
**Rancher versions:** 2.0 master 1/21

**Steps to Reproduce:**
1.  As Admin, create a user testuser1 as admin
2. Create a cluster and make testuser1 and owner of the cluster
3. Log in as testuser1
4.  Edit cluster

**Results:**  Admin is dimmed and I can't delete or edit their permission for the cluster.  Two things here - As admin I should have all permissions and be able to do this.  Also as owner of cluster I should be able to edit/delete any users.  The same is true if you do this for projects.

**Comment by cjellick** [comment]
There is no API restricting this. It is imposed by UI. Co-assigning @westlywright but keeping myself assigned in case there is something I need to do on the backend to accommodate the front end.

**Comment by vincent99** [comment]
Removing yourself on edit is also problematic...  I'd say the behavior _should_ be you can delete whoever you want as long as there is at least one owner (this is what 1.x does), but because it's a mapping table resource that's not currently possible for the UI to implement.

It doesn't know which of the bindings are giving the current user the ability to delete the bindings, so it can't order the deletes in a way that guarantees that they can all succeed.

So to do this properly, there would have to be an atomic setMembers type action (as in 1.x) where we pass the whole set and the backend does the create/deletes of the mapping entries.

**Comment by westlywright** [comment]
In my next PR i'll have the  "simple" implementation that just checks to see if any owners were removed, if so do you have a new owner role? If not you'll get an error.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/2
Verified fixed
