### ISSUE TITLE
YML setup for rancher: User that has owner rights to the "local" cluster, has access to all clusters

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11099]
**Rancher versions:** 2.0 master 1/23

**Steps to Reproduce:**
1.  As admin, Create a testuser1 with standard permission
2.  Create a cluster and add testuser1 as owner
3.  Create a couple of more clusters and don't add testuser1
4.  Create another cluster and add testuser1 as owner
5.  Log out and log in as testuser1

**Results:**  testuser1 can see all clusters and add project and such to all projects

**Comment by tfiduccia** [comment]
This is because I create rancher using the yamls, which created a local cluster using my machines.  I added user to the local cluster as owner and now they have god level rights.

**Comment by deniseschannon** [comment]
After discussing with @ibuildthecloud and @cjellick, this is expected behavior as this cluster is essentially the DB for Rancher. 

We will not be recommending users to deploy production in this manner.

@ibuildthecloud needs to expose the field which allows differentiating between the local cluster and an external cluster. 

Afterwards, we'll include in the UI warnings for when you add users to the local cluster/projects.

**Comment by deniseschannon** [comment]
@ibuildthecloud has exposed an `internal` field on the `cluster` so UI can warn about makign changes to the local cluster.

**Comment by vincent99** [comment]
Added warning on cluster membership edit for local cluster

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/31
Verified fixed
