### ISSUE TITLE
DYNAMIC RBAC - User added to a project with "manage-project-members" is not able to modify users for project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11105]
Rancher versions: v2.0 built on jan23

Steps to reproduce the problem:
Create a cluster c1.
Create a project P1 and add "user1" with "manage-project-members" option.

Log in as user1.
Try to edit project P1 and add a new user to the project.

This fails with " projects.management.cattle.io "project-tm47n" is forbidden: User "user-2c74c" cannot update projects.management.cattle.io in the namespace "cluster-8v4m9"

The request made by UI is edit project for which the user does not have access to.

```
Request URL:https://****:8443/v3/projects/cluster-8v4m9:project-tm47n
Request Method:PUT
Status Code:403 Forbidden
Remote Address:****:8443
Referrer Policy:no-referrer-when-downgrade
```

We should be able to decouple the edit project action and add/edit member to project action.

**Comment by loganhz** [comment]
@vincent99 is there anything we can do for this issue? 
`update` action is in the `links` of the project.

**Comment by westlywright** [comment]
@deniseschannon i think we can move this to the API as well, requires changes to scope of a role in the API which is outside the UI imo .

**Comment by cjellick** [comment]
@vincent99 I'd like to explicitly outline the situation and get your explicit agreement on path forward.
1. This fails in the UI because updating the project (PUTing to project) is coupled with changing members (POST/PUT/DELETE PRTBs)
2. You are asking me to add the ability to update a project (PUT to project to change all the editable fields like name and description) to the role called "Manage project members"
3. When dynamic RBAC is implemented, theoretically the schema would tell you update is not available but that would be on per-project basis.

So my questions are:
- Do you really want the "manage-project-members" role to _also_ have the "edit project" permission
- Would relying on dynamic RBAC be a viable fix for this? Do you guys load schemas per project?

**Comment by vincent99** [comment]
The `update` link would need to go away on projects you can't PUT; `/v3/projects/x/schema` is only loaded when you are inside the project.

But given that, we could skip the put and disable the fields.

**Comment by cjellick** [comment]
ah right, ok.
So in summary, do not change the role; dynamic RBAC should address this

**Comment by deniseschannon** [comment]
If you update the members from the members tab of a project, you will be able to manage project membership. The reason why it doesn't work in "Edit Project" is because you are trying to also edit the project, which you don't have permissions.
