### ISSUE TITLE
Host continues to be shown in "Active" state when it was powered down/deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11189]
Rancher versions: v2.0.0-alpha12

Steps to reproduce the problem:
Provision a RKE cluster with 2 nodes:
node 1 - all roles
node2 - worker

Wait for cluster to get to "Active" state.

power down node2.
Host state in rancher UI continues to shown as "Active".

Node status is being reported as being "NotReady".
```
NAME         STATUS     ROLES                AGE       VERSION
sangee20t1   Ready      etcd,master,worker   1d        v1.8.5-rancher1
sangee20t2   NotReady   worker               1d        v1.8.5-rancher1
```

We should be active to sync this status to Rancher .

Even when host is deleted ( from DO in my case) , host continues to be shown as being in "Active" state.

**Comment by sjdevries** [comment]
Is this happening because of Kubernetes default values?  
By default, it seems kubernetes takes 5 minutes to evict a node.  

https://stackoverflow.com/questions/47317682/kubernetes-node-shutdown-crash-recovery

**Some items you can adjust to test:**
kubelet: node-status-update-frequency=4s (default 10s)
kube-controller-manager: node-monitor-period=2s (default 5s)
kube-controller-manager: node-monitor-grace-period=16s (default 40s)
kube-controller-manager: pod-eviction-timeout=30s **(default 5m)**

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/37334889-18e84c1e-26e8-11e8-8ab9-4e03a85ee504.png)

Now when the node is power down, its state becomes `unavailable` and a new node will be added to the cluster so that the desired state of the cluster is satisfied.  

@sangeethah do you think it is the expected result?

**Comment by deniseschannon** [comment]
@sangeethah With the changes with node pools introduced later in 2.0, the correct behavior is as @zionwu pointed out. If the host is powered down outside of Rancher, we will mark the node as unavailable and spin up a new node.

**Comment by vincent99** [comment]
It's "intended" for now but I don't think it's "correct" as far as what we ultimately want.  There needs to be mechanisms for controlling the various behaviors of the pool, e.g.how long a node is allowed to be unavailable before it's deleted/replaced, preventing loss of quorum, etc.  @ibuildthecloud was working on options for this stuff last week...

**Comment by soumyalj** [comment]
Tested with master from March 20 build. Created a 3 node cluster with ALL roles on each of them. 
When a node is Powered OFF it goes to `Unavailable` state and a new node gets provisioned. 
When a node is deleted a new node gets provisioned.
