### ISSUE TITLE
Member Permissions too relaxed

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#11263]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: v1.2.9 

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.13.7
network-services: 0.7.19
scheduler: 
kubernetes (if applicable): 1.8.5-rancher4

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.75-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single-node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Adding a user to the environment with "member"-permissions. The user can still see, modify infrastructure-stacks, remove complete hosts as opposed to the docs ( http://rancher.com/docs/rancher/v1.6/en/environments/#membership-roles ).

**Results:**

**Comment by deniseschannon** [comment]
Can you confirm that the user is not an admin?

Also, they will be able to see the actions but if you try to do one of the actions, the API will reject them. 

In 2.0, we are adding the ability for the UI to hide the actions that they don't have permissions for.

**Comment by deniseschannon** [comment]
A member is exactly like an owner except you can't change the membership roles of the environment.

A restricted user is equivalent to the permissions that you are looking for.

**Comment by strowi** [comment]
Argh, sorry, i made a mistake myself... i meant a member with the "read-only"-permissions, but that seems to be only a ui-issue. 
Read-only users still get the bullet-points to delete containers, but an error after clicking).
When using a read-only user, it seems i can't even access the kubernetes-api?

Testing the restriced-user, i wonder why they can delete the kube-dns pod, which is quite essential (shouldn't this be infra anyway?)..
Maybe it would be useful to have kube-system namespace excepted from the restricted-users access.

**Comment by FFock** [comment]
Either the documentation is wrong or the Rancher 1.6.11 (or later) code: As environment member I can see the infrastructure services which must not be the case according to the 1.6 documentation which reads as follows:
_A member of an environment can perform any actions in Rancher that do not affect the environment. They will not be able to add/remove members or change the membership roles of existing members or view any of the infrastructure services._
See http://rancher.com/docs/rancher/v1.6/en/environments/#membership-roles
I think this is a bug - a serious one because infrastructure services like the External-DNS expose DNS server secrects!

**Comment by superseb** [comment]
Thanks, this was corrected in the docs.
