### ISSUE TITLE
Cluster stuck in updating state when adding a new node with role worker and control to existing 1 node cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11331]
rancher-server - v2.0 from master
Steps to reproduce the problem:

Create a cluster with 1 node (all roles) using custom host (docker run command)
Wait for the cluster to be provisioned fully.
Add another custom node(using docker run command) with worker and control roles.
Host gets added to the cluster. But cluster gets stuck in "updating" state forever.
kubectl command shows that the host has been added with correct roles

I see many error states - one of them
```failed to get Kubernetes server version: Get https://<ip>:6443/version: x509: certificate is valid for <ip>, 127.0.0.1, 10.233.0.1, not <ip>```

**Comment by sangeethah** [comment]
Tested with v2.0 master build done at ~12:00 pm.

Able to add nodes with role worker and control to existing 1 node cluster successfully.

**Comment by sh0umik** [comment]
I am having the same problem in v2.0.4 . In my case of creating a custom cluster, I have added 3 single core 2 gb ram and all works fine , Then i added another custom hosts with 4 gb ram and 2 cores and got the same error and its been in the updated sate since yesterday .. 

This single 2 Core and 4 GB ram are assigned as etcd, worrder and controller 

However all nodes are active !
