### ISSUE TITLE
Support casbin as the authorization backend

### ISSUE THREAD

**Issue by veotax** [rancher/rancher#11386]
[Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I think it's more powerful than the [current RBAC way](https://github.com/rancher/rancher/blob/f3e80f69e94d7da64e75545caadda61870148753/pkg/rbac/access_control.go), what do you think? Thanks.

**Comment by veotax** [comment]
@cjellick

**Comment by cjellick** [comment]
We've made the architectural decision in 2.0 to rely on native K8S RBAC as the authorization mechanism. This is what our users/customers have asked for. I don't think we want to pull in an external authorization framework.

Note: the bit of code you linked to is still powered by k8s RBAC doesn't represent our entire RBAC solution. Its basically used to bridge a gap between how we wanted our API to function and how k8s RBAC works. We want users to be able to list resources and see _just_ the resources they have access to. K8S RBAC list is all or nothing, so that bit of code basically acts as a list filter, but under the covers, everything is still powered by K8S RBAC.
