### ISSUE TITLE
[err-msg] Need to restart service reconcile

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#11513]
**Rancher versions:**
1.6.5+

**Symptom:**
What this message means is unclear to us. It is seen sometimes when finising an upgrade, but possibly other times as well.

**Expected behavior:**
This message needs to indicate better it's meaning. We can't advise on what it should say because we don't understand what it means.

**Comment by leodotcloud** [comment]
https://github.com/rancher/cattle/blob/v0.183.45/code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/ServiceDeploymentPlanner.java#L168

There are multiple reasons which qualify for service reconcile. Instead of just returning True/False, may be we can associate a message for each condition and return which can then be shown in the error message in UI.

**Comment by leodotcloud** [comment]
After further investigation, the above messages are already displayed in the Service log. Will update the error message to : `reconciling service state`

**Comment by sangeethah** [comment]
Tested with latest build fro master:

Created a service with invalid entry point do that containers get to "stopped" state as soon as they get to "running" state , which results in constant attempt to restart containers that would keep failing.
Upgrading / rolling back this service , would now result in the following error message presented to the user:

<img width="1053" alt="screen shot 2018-04-12 at 9 44 06 am" src="https://user-images.githubusercontent.com/4266958/38691618-35328df2-3e36-11e8-8e32-12bac2211f7b.png">


<img width="1223" alt="screen shot 2018-04-11 at 3 38 04 pm" src="https://user-images.githubusercontent.com/4266958/38691625-39a5cf7a-3e36-11e8-94f2-8a1ab06d3e14.png">
