### ISSUE TITLE
CLI 2nd set of commands

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#11526]
`namespaces`
`nodes`
`ssh`
Available at [v1.0.0-alpha6](https://github.com/rancher/cli/releases/tag/v1.0.0-alpha6)
https://github.com/rancher/cli/pull/118
https://github.com/rancher/cli/pull/119
https://github.com/rancher/cli/pull/120

**Comment by sangeethah** [comment]
Tested with v1.0.0-alpha6:

Following commands are now available and works as expected:
namespaces
nodes
ssh

@dramich Had the following questions:

1. Why is ssh not provided as command for nodes instead of being made available as a standalone command ?
2. When using ```rancher namespaces create  <ns>```  it is created without being associated with any project. Ideally we would expect it to be associated with the default project that was set during login.

**Comment by dramich** [comment]
1: For expandability 
2: Addressed [here](https://github.com/rancher/cli/pull/124)

**Comment by deniseschannon** [comment]
Available with v1.0.0-alpha7

**Comment by sangeethah** [comment]
Tested with  v1.0.0-alpha7
rancher namespaces create <ns> creates namespace and associates it with the default project.
