### ISSUE TITLE
Email notifier stuck in testing and throwing error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11571]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Setup an email notifier
2.  Click on test

**Results:**  Testing button stuck in testing - 
Error in dev console - 
![image](https://user-images.githubusercontent.com/11514927/36578293-6d528c8e-1819-11e8-8326-4defbf13595e.png)

**Comment by zionwu** [comment]
@tfiduccia  I can not reproduce the issue. Could you provide me the env or the request data?

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/36625719-fdba3348-195f-11e8-85ec-971721207fbc.png)

@tfiduccia I tested with the latest rancher:master and could not reproduce the issue. Can you check with the lateset rancher:master?

**Comment by zionwu** [comment]
![image](https://user-images.githubusercontent.com/1213386/36625738-5db188b4-1960-11e8-975a-c368a1263339.png)

Screen shot if I input the valid data.

**Comment by zionwu** [comment]
This issue can be reproduced if user re-type the value for port. Then UI is passing a string instead of the int to backend which causes it.

**Comment by zionwu** [comment]
@vimniky please fix it. thanks.

**Comment by vincent99** [comment]
This is because the test flow doesn't go through the normal `validate()` call and save flow.  HTML `<input>` values are always a string, but if the schema says a field is an int/float it's converted during validation (in `ember-api-store/addon/models/resource.js` `validationErrors()`).

Checking for validation errors before doing the test will be both useful and fix this.

**Comment by vimniky** [comment]
@vincent99  Thanks!  Fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/27
Verified fixed
