### ISSUE TITLE
Ingress - "503 service temporarily unavailable" error when  trying to access default ingress rule.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11600]
**Rancher versions: 2.0 build from master

Steps to reproduce the problem:
Create Ingress - "ing1" with default rule pointing to workload - wl1
Accessing ingress url without passing any host header directs traffic to pods in wl1 as expected.
Create Ingress - "ing2" with default rule pointing to workload - wl2
Accessing ingress url without passing any host header continues to directs traffic to pods in wl1. Is this expected?
Delete "ing1".
Accessing ingress url without passing any host header results in "503 service temporarily unavailable" error .

Expected Behavior:
Accessing ingress url without passing any host header should directs traffic to pods in wl2 now.

**Comment by orangedeng** [comment]
@alena1108 
Problem to ask
1. After create two ingresses with the one path and each ingress is point to its own workload, what should we except when we access that path? 
2. And because we have two ingresses, we should have two services for each ingress rule. For now, we only have one service for that and I will fix it.
3. @sangeethah If you wait for about 30s, the ingress rules will recover and you will get response from wl2.

**Comment by alena1108** [comment]
@orangedeng for now, admin should ensure the rule uniqueness. We might add some validation on api layer later on - k8s doesn't have it by default
