### ISSUE TITLE
Fail to enter Add Pipeline page

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#11617]
Rancher versions: 2.0 master 2/24

**Steps to Reproduce:**

1. set Github config at cluster level to enable pipeline
2. go to the pipeline tab in default project page
3. click `Add Pipeline`

**Results:**
Stuck in loading and got error in console:
![image](https://user-images.githubusercontent.com/5697937/36627671-092ef2ec-1981-11e8-83f3-9aa43c2c54e0.png)

**Comment by biblesyme** [comment]
I have an `ember-drag-drop` package under my pipeline engine, but it missed in the build of `rancher/server:master`. 

@vincent99 I thought this is because the command `./scripts/update-dependencies` won't install the npm packages under engines, so the build process missed dependencies under engines, right?

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/26
Verified fixed
