### ISSUE TITLE
Upgrading service with mem_reservation

### ISSUE THREAD

**Issue by smakhtin** [rancher/rancher#11632]
I’m trying to upgrade service with mem_reservation: 10000000000 on a machine with 30GB Ram. Currently, we run 3 container instances per such machine. The problem is, when I upgrade this service, I see memory limit error. Looks like even stopped containers are counted in memory limit, which is counter-intuitive because for the upgrade I need a double amount of RAM per machine. Is there any workaround for this?

**Comment by blackholegalaxy** [comment]
Ran into the same issue a few days ago. I had to delete previous container before running an updated one, praying the updated one starts properly. It's not an acceptable workaround as we loose the benefit of the upgrade processus.

**Comment by vincent99** [comment]
Reservations apply to scheduling and do not take running state into consideration because reserved memory is not oversubscribed.

During an upgrade both containers ARE running for "start then stop".  For "stop then start" the old containers exist and might be run again on rollback.  Ignoring the reservation of one of them during upgrade allow creating situations where you are oversibscribed (e.g. upgrade A and change reservation downward, deploy B using the now free RAM, rollback A).

**Comment by loganhz** [comment]
Please check https://github.com/rancher/rancher/issues/11632#issuecomment-368563262

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
