### ISSUE TITLE
Adding custom cluster member fails with "Role Template required" error

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#11696]
**Rancher versions:**
rancher/server: Master from Feb 27

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

***Steps to Reproduce:**
1. Create a custom user "testuser" at the global level
2. Create a cluster
3. From the cluster level, add "testuser" as custom member to the cluster by choosing "View Volumes, view projects, view nodes, view custom members"

The add member fails with error "Role Template is required" 

<img width="355" alt="screen shot 2018-02-27 at 11 55 38 am" src="https://user-images.githubusercontent.com/18536626/36751500-31600324-1bb5-11e8-85f5-f8fb3c968dce.png">

**Comment by westlywright** [comment]
The root cause of this problem was that the UI was allowing creation of users with the `custom` radio checked but no actual roles selected. I've fixed the bug so users can not be added from this page without a role.

As such retesting this should be done with a fresh setup as the user `testuser` in the original reproduction should have never been created in the first place. The error message displayed and the ui functionality for the original steps are as intended.

**Comment by tfiduccia** [comment]
Version - 2.0 - master 3/4
Verified fixed
