### ISSUE TITLE
Support volume linking and migration across hosts

### ISSUE THREAD

**Issue by binduwavell** [rancher/rancher#117]
This is likely two feature requests, but I'm unclear what is possible currently. 

I have a bunch of nodes that need to be distributed across physical hosts and share storage.

A cool solution would be to have distributed volume containers.

**Comment by binduwavell** [comment]
Possibly something like flocker. I get there is a overlap between these projects. So not necessarily suggesting you use flocker but at least it's a place to start.

**Comment by binduwavell** [comment]
This article on syncthing is also interesting, although I'm unclear how transactional the shared disks are.

**Comment by binduwavell** [comment]
Also glusterfs looks interesting.. http://blog.gluster.org/2014/07/docker-glusterfs-dockit-an-easy-way-of-glusterfs-deployment-with-docker/

**Comment by os12** [comment]
Right, we have been thinking about storage in the Rancher context. What usecases do you have in mind? Creating a shared/distributed volume? Moving a container from one physical host to another? Growth? Redundancy? Sharing?

**Comment by binduwavell** [comment]
My immediate need is for a shared/distributed volume with guarantees that all clients always have a consistent view of the file system. 

Currently I could accept distribution where there is only a single stored copy of each file however it would be quite important that containers on different hosts have consistent and good read and write performance.

Having a way to configure redundancy so a file can't be lost if/when a single mode is lost would be a big win.

Ideally this would then support content migration. Say I need to allocate a new host with faster storage and decommission another host. If I could add the new host, add the distributed volume to the new host, increase redundancy from 2 to 3, wait actual redundancy to reach at least 3, decommission the older storage node and reduce redundancy back to 2... So I am sure that I always have at least two copies of each file. That would allow us to manage redundancy, and also to add and remove storage nodes as need be.

I don't need for the actual storage to be on each physical host but having some control over this to optimize performance would be helpful. 

It would be OK if each compute node had to have a live replica of the volume, but Ideallly I could setup one or more storage nodes per data center and have the compute

**Comment by binduwavell** [comment]
I should add that I wouldn't use this for databases as they have purpose built replication solutions. This is truly for files.

**Comment by os12** [comment]
Could you further clarify your first point please? Why would you share a volume across multiple containers? Are you thinking about NFS-style shared access to the data?

**Comment by corn13read** [comment]
Are you basically requesting cron'd rsyncs for files?

**Comment by binduwavell** [comment]
I have a clustered content management system. Each node needs to have a shared file system and a shared database. On bare metal ai'd cross-connect SAN to multiple machines or I'd use NFS to cross mount a common file system that would contain the files. 

No I'm not looking rsync in as much as that would create an eventually consistent view of the file system. 

I guess that as long as the directory entry for a file added on node one is visible on node two by the time my write completes on node 1 and as long as node 2 can read said file right away even if the underlying file system is fetching it over the network, that type of eventual consistency is fine... But from the content management systems perspective, the file system is consistent within the time frame of a write/read...

**Comment by stela5** [comment]
+1 for https://github.com/ClusterHQ/powerstrip-flocker

**Comment by ibuildthecloud** [comment]
@stela5 working on it :)  Hope to show some progress soon.

**Comment by corn13read** [comment]
@stela5 @ibuildthecloud I have the same (drupal) use-case. I'm interested in adding this or working on this.

**Comment by 5an1ty** [comment]
+1

the example on powerstrip-flocker is exactly what I want:
$ ssh node1 docker run -v /flocker/demo:/data busybox sh -c "echo fish > /data/file"
$ ssh node2 docker run -v /flocker/demo:/data busybox sh -c "cat /data/file"

Currently a volume container chains you to the host the container is running on, it would be nice to have a volume container run on multiple hosts and share state between them.

**Comment by vincent99** [comment]
@5an1ty Flocker does not actually provide (all of) what you're asking about.  It can *move* a volume between hosts but it is only writable on a single host and disappears if that host does.  So that example works by moving the volume to host2 before running the 2nd command.  This has it's uses, but two containers can't actually be running on different hosts at the same time and share the volume.

Simultaneously writing from multiple hosts and resilience against a host disappearing is a "clustered filesystem" and considerably more complicated.  As @ibuildthecloud said we're working on this and hope to have something to show soon.

For now, creating a NFS export on one machine and mounting it on all the hosts is a simple way to accomplish the sharing part.  If you need the resiliency too then there are projects like a Ceph and GlusterFS.

**Comment by 5an1ty** [comment]
@vincent99 Apologies, I was a bit over eager and misread the solution flocker offered. What you mentioned is what I'm actually looking for "A Clustered filesystem". Resilience against a host disappearing is indeed the biggest use-case. I'll try looking into GlusterFS, but something that would be built into rancher would give my preference.

Looking forward to what you guys come up with!

**Comment by mattapperson** [comment]
+1

**Comment by mattapperson** [comment]
To expand on that +1 :) ... 
While Ceph / GlusterFS solutions are... ok... the reality is that they have MAJOR performance hits. A solution like Flocker (if you use that or not) is about as good as one can expect from an out of the box solution IMHO. Trying to do more in this space will lead to instability and major performance hits that are, again IMHO, not worth it.

**Comment by Kelindar** [comment]
Same here. Flocker (-like) approach seems to be much better suited for Rancher. I would also like to have some volume backup capabilities with configurable snapshots to S3 (-compatible) object storage.

The use-case I have in mind is quite simple, having a periodic backup with the ability to migrate containers and their data or restore from a snapshot if say, the disk on a particular node crash or someone accidentally deletes the container or wipes all the data.

**Comment by tsgoff** [comment]
+1

**Comment by faddat** [comment]
+1, and I'll toss in what my use-case will look like, too.  

I'd like to be able to attach an NAS to the rancher Cluster itself, so that all of the hosts would simply use that for their storage as in:

NAS might look like:
Host1/
Host2/
Host3/
Host4/

this is in opposition to the idea of sharing globally across the hosts-- instead I'd like to create a situation where storage is entirely compute-independent, existing as network endpoints.  Now, since I will be in several clouds and several datacenters, it could be that I just want S3 / gstore support so that I could "mount" the storage that way.  

BTW:  I'm a tad green-- if I'm missing something by suggesting a setup like this, please let me know.  Cloud is/will be a collection of:

-Bare metal
-GCE
-Azure
-Hyperlocal Nodes (these are the trickier ones, they'd be ~200ms from the NAS, so I might just exclude them from using the NAS)

Additional, related challenge-- the hyperlocal nodes may be ARM.  They may not be, too.  My plan now is to store volumes in a standard way so that data goes from x86 to ARM without an issue and vice versa.

**Comment by cjellick** [comment]
This issue is partially covered by our current convoy-nfs and convoy-gluster integrations, but there are some advanced feature requests here that could/should be teased out before closing.
