### ISSUE TITLE
For project alerts, remove Workload type and show all workloads in drop-drop

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11768]
**Rancher versions:** 2.0 master 2/28

**Steps to Reproduce:**
1.  Create a notifier
2.  Go to project and go to Add alerts
3.  Select Workload radio button

**Results:**  Please remove the first drop-down that has the different type of workloads.  Just list all of them in the in second drop-down.

**Comment by vimniky** [comment]
@tfiduccia  I did the change, but I don't think it's better.  Because there's also `workload selector`  and for `workload selector ` we must select a `workload type`.  If we remove the `workload type` drop-down of workload, `workload` and `workload selector` are not consistent anymore. It would be better if we can remove both the workload drop-downs of `workload` and `workload selector`, but that's not the case from what I know.

<img width="1216" alt="screen shot 2018-03-01 at 10 54 11" src="https://user-images.githubusercontent.com/11426875/36825050-6b6e6a56-1d40-11e8-888c-d87ca0c9d6c6.png">

<img width="1154" alt="screen shot 2018-03-01 at 10 54 36" src="https://user-images.githubusercontent.com/11426875/36825058-73b48880-1d40-11e8-9d89-ebf906b66509.png">

**Comment by vincent99** [comment]
I'm not really sure what the value of filtering a workload selector to a particular type is either...

**Comment by zionwu** [comment]
Behind workload, it is deployment/statefulset/daemonset,  backend needs to know the exact type of the workload so that it can call api for that resource. When implement this feature, the workload feature is not usable and Darren told me just go with the deployment/statefulset/daemonset. 

I am not sure if I can watch workload resource for alering, I need to check with Alena.

**Comment by vincent99** [comment]
Watch them all?  And there's several other kinds (replication controller, replica set; job and cronjob but not clear what available means to them)

**Comment by zionwu** [comment]
As discussion with Will and Vince, we will remove the type field for workload. And I will watch the workload resource.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/1
Verified fixed
