### ISSUE TITLE
Not able to create a new Host

### ISSUE THREAD

**Issue by sredXNY** [rancher/rancher#11949]
**Rancher versions:**
rancher/server: stable 
rancher/agent:  v1.2.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.09.1-ce
Docker version 17.12.1-ce,

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Docker version 17.09.1-ce, build 19e2cf6
[root@centos-s-4vcpu-8gb-sfo2-01 ~]# ^C
[root@centos-s-4vcpu-8gb-sfo2-01 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Hello, I have a VM with CentOS7 and I am trying to register that VM as a host in my rancher server but I am facing some problems with that, I tried some versions of docker but in all of them I get a problem, next I will list the version and error message:

- Docker version 17.12.01-ce = failed to find state json
- Docker version 17.09.1-ce =  json: cannot unmarshal number into Go value of type string  

So, can someone tell which version of docker will work correctly? and, how can I update (if needed) my rancher server container?

**Comment by superseb** [comment]
`rancher/server:stable` does not say much on the actual versions, but seeing the agent version, you are running a pretty old version (over a year old). This won't work with much more recent Docker versions.

If you have to keep running this old version, you can check http://rancher.com/docs/rancher/v1.4/en/hosts/#supported-docker-versions, otherwise use v1.6 and check out http://rancher.com/docs/rancher/latest/en/hosts/#supported-docker-versions.
