### ISSUE TITLE
UI should not allow create two node with all roles

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#11985]
**Rancher versions:**
rancher:master 03/06

**Steps to Reproduce:**
1.  Create a cluster with one node using DO.
2. after the cluster is active, go to the node page for that cluster, click "+" to add node. This leads to 2 nodes for etcd, which should be forbidden.  The same behavior is forbidden if I do it on "Edit cluster" page.

**Results:**
Node page:
![image](https://user-images.githubusercontent.com/1213386/37016823-15b02d54-2149-11e8-9153-0085b2f685d8.png)

Edit cluster page:
![image](https://user-images.githubusercontent.com/1213386/37016830-20792e34-2149-11e8-9c40-211dff69a85d.png)

**Comment by vincent99** [comment]
There's nothing fundamentally wrong with 2 (or 4) etcd nodes, it is just a waste of hardware because it doesn't increase the quorum until you have an odd number.

The add flow gets you a valid cluster; after it's up you can't prevent the creation of situations we don't like because things like deleting it registering machines from the provider directly.

**Comment by zionwu** [comment]
The "Edit Cluster" button is on the "Node" page,  User can change the number of cluster clicking "edit cluster" or "+". I think the behavior should be consistent between the two places.


<img width="1226" alt="wx20180306-145629 2x" src="https://user-images.githubusercontent.com/1213386/37025784-91f2737c-2167-11e8-8a4f-00f6fdadf488.png">

**Comment by loganhz** [comment]
@vincent99 what should we do for this issue?

**Comment by vincent99** [comment]
Nothing, it's fine..
