### ISSUE TITLE
Namespaces don't show in workload/ingress/dns for imported cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11994]
**Rancher versions:** v2.0.0-alpha17

**Steps to Reproduce:**
1.  Create a imported cluster
2.  Go to workloads
3.  Add workload

**Results:**  Notice the namespace drop-down is empty.  Should have default in there.
![image](https://user-images.githubusercontent.com/11514927/37025803-e56e7240-20e9-11e8-88ea-18ebc400625c.png)

**Comment by alena1108** [comment]
@tfiduccia it might be happening because the cluster you import, used to be a part of rancher before. In this case Default namespace continues to be assigned to its original project/cluster. I've filed a separate ticket so we can come up with the proper cleanup steps to take before the cluster can be re-registered with rancher (https://github.com/rancher/rancher/issues/12126)

For this ticket, could you validate if the issue happens for a freshly created cluster import.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
This is reproducible on a cluster that I just created.  The default namespace is showing up on the namespace page, but doesn't show up on Deploy Workload.

**Comment by alena1108** [comment]
Can't reproduce, steps taken (was specifically trying to avoid UI refresh):

1) Go to Global view, Create cluster, Chose import, copy command, get back to Global page
2) Execute the command on the cluster side, wait for the cluster to appear and become active on the Global page
3) Go to project view under the cluster, hit workload create. Default namespace is presented in the namespaces dropdown.

May be a timing issue? And the workload.run is hit before underlying controller sets the projectId on the default namespace

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Timing issue between project and namespace creation (very small window)

**Comment by gitdemo-cn** [comment]
Is it fixed? Still have this issue in 2.0 master 3/28

**Comment by tfiduccia** [comment]
@gitdemo-cn - I've seen this off and on, can you answer a few questions to help us track down?
1.  What type of cluster are you using?  
2.  Do you have more than 1 cluster?
3.  Are you in the default project or did you create a new one?
