### ISSUE TITLE
Provider detail for cluster is empty for non-admins who didn't create the node template from the cluster

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12038]
Rancher server version  - v2.0.0-alpha19

Steps to reproduce the problem:
As admin , Create DO cluster c1 and assign "user1" as "owner" of this cluster.

Log in as user1.

Edit this cluster. There is no "Save" button in this edit page.

<img width="1317" alt="screen shot 2018-03-07 at 3 06 53 pm" src="https://user-images.githubusercontent.com/4266958/37123539-7b67794c-2219-11e8-8283-4976d36a68f1.png">

Also in the cluster list view , provider is empty.

<img width="1301" alt="screen shot 2018-03-07 at 3 11 07 pm" src="https://user-images.githubusercontent.com/4266958/37123657-e4b2f688-2219-11e8-9a2b-9c10e0fc2eb7.png">

**Comment by sangeethah** [comment]
@loganhz In my case I used clusters with DigitalOcean providers.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Still not fixed - the save/close buttons for first issue is fixed.  But the second issue is not.
![image](https://user-images.githubusercontent.com/11514927/37900750-f98ac08e-30a3-11e8-9517-80138b85cb9e.png)

**Comment by loganhz** [comment]
The nodeTemplate is created by `admin` user.  
UI shows the `provider` by looking for `node` -> `nodeTemplate` -> `driver`
However, `user1` doesn't have the permission to get the nodeTemplate which is created by `admin`.

@vincent99 any ideas?

**Comment by loganhz** [comment]
I think there is nothing we can do on UI side as `user1 ` can not get the template created by `admin`.

**Comment by deniseschannon** [comment]
Node Templates can only be seen by the user who created them.

Missing ability for admins to see node templates made by other users: https://github.com/rancher/rancher/issues/12186

Debatable if cluster owners should be able to view the node templates of other users if they aren't admins.

**Comment by janeczku** [comment]
v2.1.3: global admin is unable to edit a cluster created by a standard user (using a node template).

**Comment by jgnagy** [comment]
This seems like a pretty significant issue, given #19332 (which I'm experiencing too). Was having someone else (another admin in my group) configure etcd backups to S3 but they're not able to because of this bug in 2.2.1. I'm a bit concerned if all cluster maintenance at this level must be done by me... what happens if I'm hit by the metaphorical bus? Even the global admin can't edit the cluster.

**Comment by vincent99** [comment]
A missing feature you would like is not a bug.  They are intentionally not visible because they contain secret keys.  There is work progressing towards this, including separating the template from the credentials in 2.2.  If you were hit by a bus the admin could edit the CRD directly to change the owner, or add new pools.

**Comment by jgnagy** [comment]
@vincent99, whether you consider this a nice-to-have feature, fleeting curiosity, or bug, it still seems like a significant issue. I mentioned 2.2 because node templates there, during their creation _seem_ to only refer to credentials that are actually shared with other admins. It seems odd that cloud credentials are safe to share amongst administrators but the node templates that reference them aren't.

I'm glad you're making progress on this issue (though that wasn't otherwise obvious in the discussions in this issue). In the interim, can you refer me to some documentation on how "the admin could edit the CRD directly to change the owner, or add new pools" so I can add this to our operations documentation as a workaround? Without this, I'm stuck having to do all this work on any clusters I've created. I'll also work through our Enterprise support process to see if that helps at all with prioritizing this work.

**Comment by patrick0057** [comment]
As a workaround you can use this script to change the nodetemplate owner.
https://github.com/patrick0057/change-nodetemplate-owner

**Comment by jiaqiluo** [comment]
on Rancher: master 6/13, 

1. *no-creator* user will see a do/ec2 cluster marked as a **custom cluster**
2. when *no-creator* user  edits the cluster, it asks for choosing the provider

**Comment by davidnuzik** [comment]
@deniseschannon this is now a bigger issue.
Due to changes in the UI when we edit as non-admin user the cluster (I am cluster owner) I can't pick the provider. UI thinks my Linode cluster is a custom cluster and things are broken in the UI.

**Comment by deniseschannon** [comment]
@davidnuzik In your use case, it sounds as if we would expect the admin to create a cluster template, share the cluster template with the user and let the user create the cluster with their own creds for the node pool. That's how they would be able to edit the cluster.  

Today, if an admin created a cluster using node pools and shared it with a cluster owner, would they be able to edit the cluster?

**Comment by davidnuzik** [comment]
@deniseschannon as we discussed my issue is not quite the same problem and so I created a separate issue to track this here: https://github.com/rancher/rancher/issues/22080
