### ISSUE TITLE
How to get access to the Kubernetes Dashboard?

### ISSUE THREAD

**Issue by lucevers** [rancher/rancher#12146]
From the previous question, the answer was:
You can get access to Kubernetes Dashboard via the UI in containers tab then advanced.
 **So where is the container tab?**

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha21` UI: `v2.0.25` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by vincent99** [comment]
I don't know where "the previous question" is, but it sounds like it was referring to the first preview release (<= alpha12).

The containers tab is currently called Workloads, when inside of a Project.

The dashboard is not deployed by default, because it does not work very well with RBAC.  You can use kubectl to deploy the yaml for it if you want.

**Comment by lucevers** [comment]
oke, thanks!
