### ISSUE TITLE
Add resume to deployment

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12360]
As we have pause for deployment, we need to have resume as well:

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment

**Comment by vincent99** [comment]
@kinarashah 
  - The resourceAction entries are on `workload` instead of `deployment`, so you can't see that the action exists when looking at a deployment
  - Pausing should return the state as `paused`
  - Only one of the actions should be available at a given time.  Calling `pause` on an already paused deployment (or vice versa) should say return action not allowed.  Currently pausing a paused deployment _unpauses_ it.

**Comment by vincent99** [comment]
@loganhz You're currently calling pause() to unpause, and making a combined state that looks at the field that does exist.  You should be to remove that and call unpause after --^ is fixed.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/12431

**Comment by loganhz** [comment]
hi @kinarashah 

- The `state` field is still `active`, I guess it should be `paused` instead of using a `paused ` field.
- Both of `resume` and `pause` are in the actions at a given time. I think we should only show `resume` action for a `paused` workload.

![image](https://user-images.githubusercontent.com/21168270/38463210-d41e474c-3b27-11e8-8e0c-ec1b5a15240e.png)

**Comment by kinarashah** [comment]
@loganhz 
1) when the deployment is paused, it means that any update to it now will not be stored in revisions, but it is still active so we can't really change the state and need to work on the "paused" field. 
2) sounds like a good idea, I'll update to show only the valid action in this case

**Comment by vincent99** [comment]
It will work the way it is for now, but I do not agree, it should be a real state.  It could be a different word, but all we're going to do is make it a fake computed state in the UI.  And then that won't match the CLI/API appearance, which causes confusion.

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/11
Verified fixed
