### ISSUE TITLE
Can still see users and groups from AD after I disable access control

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12416]
**Rancher versions:** 2.0 master 4/2

**Steps to Reproduce:**
1.   Authenticate Active Directory
2.  Click on Allow members of Clusters, Projects and click on group drop-down
3.  Enter user name that exist in AD
4.  Disable Access Control
5.  Go to Add Cluster and go to Members
6.  Click on Group drop-down and type in AD user (that you didn't add) into members textbox

**Results:**  Groups and Users are showing up for AD.

**Comment by deniseschannon** [comment]
@cjellick The question is what should happen when you disable an auth provider? 

If we don't log the user out with that principal and re-log them in with their local user, this issue occurs.

**Comment by adingilloRancher** [comment]
just to chime in on this, when you disable AD auth and add the same AD back, preexisting members are still listed under site access. 
![screen shot 2018-04-06 at 9 35 49 am](https://user-images.githubusercontent.com/38012481/38432962-08c54762-397e-11e8-9e24-16b09f85814c.png)

If you switch to a different AD afterwards, the same number of users are listed, however they are blank
![screen shot 2018-04-06 at 9 38 41 am](https://user-images.githubusercontent.com/38012481/38433030-4f0bca48-397e-11e8-8f88-5d24b522284c.png)

**Comment by cjellick** [comment]
@adingilloRancher 's issue on the auth provider page will be covered by resetting the auth provider on disable

The originally reported issue is because we do not reset/unset the current user's token when they disable an auth provider, so, they still have a token for the disabled provider. We need to add a check to the framework that searches principals to not search if the provider is disabled
