### ISSUE TITLE
AD Auth - User with Local admin privileges can't add AD users to clusters/projects

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#12444]
**Rancher versions:** 2.0 master 2/4

**Steps to Reproduce:**
1.  Create a rancher server
2.  Add a local user with Administrative privileges 
3.  Authenticate using Active Directory
4.  Log out and log in as local admin user
5.  Go to Add/edit cluster, add/edit project, or add members (for cluster or project)
6.  Try to add a AD user

**Results:**  AD users do not show up in drop-down.  Only local user show up.

**Comment:**  This is currently happening with admin account as well.

**Comment by deniseschannon** [comment]
@tfiduccia Since we are unable to search for the external providers when logged in as local for some of our auth providers (github/saml), we currently aren't going to enable this ability for only AD. 

The reasons why we can't search other auth providers when logged in as a "local" admin is that they require session tokens to be able to talk to that specific auth provider. It would only work with AD as we have the service account user information that could be used to search. 

As of now, we would expect the admin who also has an AD account to use their AD account to login and add users.

Note: we are adding the ability to search for local users when logged in with the specific auth provider with this fix: https://github.com/rancher/rancher/issues/11868

**Comment by tfiduccia** [comment]
Version - v2.0.0-alpha26
Closing
