### ISSUE TITLE
Proxy env for Catalog

### ISSUE THREAD

**Issue by cuseinovic** [rancher/rancher#12547]
Hi,

I'm work on rancher with the last version of the preview. 
i'm work in a company and like all compagny we have a proxy. 
I need to use a http_proxy, https_proxy, no_proxy on localhost, 127.0.0.1 and NO_proxy env to have the catalog.
I have a problem with this part: 
`[INFO] cluster [cluster-42q4j] provisioning: [authz] Creating rke-job-deployer ServiceAccount`
`WARNING: 2018/04/06 09:58:38 grpc: addrConn.createTransport failed to connect to {0.0.0.0:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 403 Forbidden\\r\\nContent-Length: 1339\\r\\nCache-Control: no-cache\\r\\nConnection: Keep-Alive\\r\\nContent-Type: text/html; charset=utf-8\\r\\nPragma: no-cache\\r\\nProxy-Connection: Keep-Alive\\r\\n\\r\\n<HTML><HEAD>\\r\\n<TITLE>Access Denied<`

I don't want that 0.0.0.0:2379 use my proxy and i don't know how to configure that.

Can you help me ?

**Comment by Remigius2011** [comment]
Hi,

adding 0.0.0.0 to the no_proxy environment variable in the docker run (i.e. add the parameter `-e no_proxy=0.0.0.0`) command for rancher server got me a bit further - but I'm still stuck on "Creating rke-job-deployer ServiceAccount" (which is the reason I found this issue).

Here's my full docker run command (proxy IP and port given as x.x.x.x:ppp):

    docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e http_proxy=http://x.x.x.x:ppp/ -e https_proxy=http://x.x.x.x:ppp/ -e no_proxy=0.0.0.0 --name rsv rancher/server:v2.0.0-beta3

In addition, the host on which you run the rancher server must be able to ssh directly into the droplets.

Maybe the reason why it fails to create the service account here is because also a direct connection over hattps is needed to connect to the k8s api on the droplet - but I have no idea on what the exact communication is - I can only proceed by trial and error here.

However, after enabling direct connections from rancher hosts to the droplets (including direct https) I got the cluster running (labeit with some error messages).

So my current conclusion is that it is not (or not easily) possible to run rancher server over an (outgoing) proxy server. Incoming connections via a reverse proxy seem to be OK, though.

**Comment by Remigius2011** [comment]
addendum: much to my own surprise I was even able to provision an nginx pod on first attempt!

good luck!

**Comment by Remigius2011** [comment]
addendum 2: today I retried to create a custom cluster with 1 machine on premise, but this time with direct internet access (outgoing connections with nat), by running the docker agent registration command exactly as given by rancher server. it worked. again, this looks like ti is currentla difficult (no guidance available) or impossible to create clusters behind a http proxy.

**Comment by superseb** [comment]
Proxy config is documented here: https://rancher.com/docs/rancher/v2.x/en/installation/proxy-configuration/

Please file a new issue when you encounter problems.
