### ISSUE TITLE
Ability to use GitLab in Pipeline

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12608]
Being able to use GitLab in Pipeline, besides GitHub.

**Comment by lastboy1228** [comment]
2.0 GA do not contain this feature.

**Comment by alena1108** [comment]
Gitlab support is added as a part of pipeline refactoring pr

**Comment by dmastag** [comment]
Awesome, should we wait for the next release then ?

**Comment by bmdepesa** [comment]
rancher/rancher:master 8/30

User is able to use repositories from Gitlab, and the pipeline executes successfully.

**Comment by iwin4aids** [comment]
I just update to the 2.1.0 release to test the pipeline future with gitlab, but met some problems.
I use my own private gitlab，when I finish the form of application id and secret and then click the button "Authenticate", it prompt a browser modal window and then shows me an error: "You need to sign in or sign up before continuing"
how to reslove this issue？

**Comment by gitlawr** [comment]
@iwin4aids You need to expand `Use a private gitlab enterprise installation` and input your private host. Please open new issues if you encounter any relevant problem.

**Comment by josenobile** [comment]
I'm using Rancher 2.1.0 when I try to add gitlab.com pipeline I got:
 [ERROR] Unknown error: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}

This feature is supported for gitlab.com ?

Steps:
1. Go to Resource -> Pipeline
2. Create application in https://gitlab.com/profile/applications (I gave all permissions)
3.  Copy the application id / secret and click authorize.
4. In the oauth window from gitlab.com click in Authorize
Result: TestAndApply Error
oauth2: cannot fetch token: 401 Unauthorized Response: {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}

**Comment by gitlawr** [comment]
@josenobile Yes gitlab.com is supported.
You probably hit a bug that recent gitlab.com introduces.
![image](https://user-images.githubusercontent.com/5697937/46916977-6d72a580-cff4-11e8-9ccc-6ed48c77573b.png)
When you click the copy button of the application secret, you actually get the application ID.
Please check the id/secret value before you copy them to Rancher(because we don't show the secret directly in the UI so users might not notice the wrong value)
