### ISSUE TITLE
Pods with health check stuck on "Unavailable" status. Unable to expand health check banner.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12610]
Steps:
Create a new work load.
Add health check with option "TCP connection opens successfully"
Launch workload. 

Results:
Associated console errors when attempting to expand health check banner.
Does not list added health checks. 
![screen shot 2018-04-10 at 9 23 54 am](https://user-images.githubusercontent.com/38012481/38569744-f5c30214-3ca0-11e8-8dec-76c613f2e5fd.png)

**Comment by loganhz** [comment]
Fixed in UI side. But there is a backend issue as well.

UI sends `tcp: true` to backend for "TCP connection opens successfully"

![image](https://user-images.githubusercontent.com/21168270/38850524-66fb091a-4244-11e8-9e54-653ce2c161d8.png)

But backend didn't populate it.

![image](https://user-images.githubusercontent.com/21168270/38850562-9689e6a6-4244-11e8-9f5e-729467e455e2.png)

**Comment by adingilloRancher** [comment]
Master 4/20/18

Verified ability to add pod with health check. Reached available status. Checked TCP set to "true" for backend. UI able to edit health check.
