### ISSUE TITLE
UI - Endpoint links gets truncated when there are more than 1 ingress rule pointing to the workload.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12682]
Rancher server version - Build from master

Steps to reproduce the problem:
Create a workload.
Create an ingress having multiple rules pointing to this workload.
Endpoint links gets truncated .

<img width="1191" alt="screen shot 2018-04-12 at 2 40 49 pm" src="https://user-images.githubusercontent.com/4266958/38706331-9ff67b6e-3e61-11e8-9982-6bee070132b7.png">

**Comment by biblesyme** [comment]
@vincent99 How about we make it three or four per line?

**Comment by biblesyme** [comment]
Or, we can make the width of column draggable. User can adjust it to fit the right

**Comment by vincent99** [comment]
- It's intended to be cut off and is properly clipped  with ellipsis.  The table view is not intended to show unlimited information, click on the workload to see more.

- Adjustable tables are always clunky and terrible because resize callbcks are reflowing the whole page.  Getting an extra 2 inches on this screen doesn't solve the problem, they'll just make a bigger list or smaller window.

- But I don't know why `path` got added to the endpoints but it's weird, and it looks like a jumbled up URL.  I'm assuming these are ingress from an ingress, so it should _only_ show the `/path`.  The port and protocol are always going to be 80 or 443/http.

**Comment by sangeethah** [comment]
Tested with - v2.0.0-rc1

Now i see only "path" being presented for endpoint url text:

<img width="1300" alt="screen shot 2018-04-26 at 6 41 05 pm" src="https://user-images.githubusercontent.com/4266958/39340155-746f6250-4981-11e8-8ca0-f0798e3e7af5.png">


But we are not able to tell the difference between http and https now. Can this be addressed?

**Comment by vincent99** [comment]
A) Why do you care?
B) Hover
