### ISSUE TITLE
HPA can't get metrics

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#12711]
###  I use the following method to deploy
-  git clone https://github.com/kubernetes-incubator/metrics-server
- kubectl create -f deploy/1.8+/
Then find that the metric-server deployment fails
![](http://ohx02qrb8.bkt.clouddn.com/metric_4.png)

- View pod's log

![](http://ohx02qrb8.bkt.clouddn.com/metric_2.png)

- In addition ,Why is kubelet's 10255 port closed?
1.6.x version of rancher deployed kubernetes this port is open

Thanks!
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by marufbd** [comment]
I ran this on my cluster where api is a node deployment 
`kubectl autoscale deployment api --cpu-percent=50 --min=3 --max=8`

But after that whenever I run
`kubectl get hpa`

It always gives:

NAME| REFERENCE |TARGETS|MINPODS |MAXPODS |REPLICAS | AGE
-------|--------------|----------|------------|------------|-----------|------
api      |Deployment/api  |  \<unknown\> / 50% |  3   |      8   |      5    |      7m

It seems heapster is not configured with rancher that's why the unknown in the TARGET.
Does it mean horizontal pod autoscaler feature is not usable out of the box with rancher?
The question is rancher should already have something to collect all the cpu/memory metrics to show in the dashboard.

**Comment by DaytonG** [comment]
I just noticed this on rancher 1.6.17 with kube 1.9.5.

**Comment by moelsayed** [comment]
Following the steps [here](https://gist.github.com/superseb/90527bd079feac17f379964f50769e28), you can create a cluster that can run HPA.

Instead of creating a cluster using the API, the current rancher 2.0 master allows editing the cluster yaml configuration to add the needed kubeapi and kubelet extra_args. 

By default we close port 10255 for kubelet for security. To enable the metric server to use port 10250 over ssl you can use this [patch](https://github.com/superseb/metrics-server/commit/96c03399a3dcbbd2ed5feda4a0b8fa061f7a5c04)

**Comment by JasonvanBrackel** [comment]
If you have an existing cluster that needs to work with metric-server, I put together this document.  It's based on the instructions provided by @moelsayed and @superseb.

https://github.com/JasonvanBrackel/metrics-server-on-rancher-2.0.2

**Comment by deniseschannon** [comment]
By adding the ability to add in `extra_args` in the advanced options of RKE clusters, you should be able to deploy kubernetes with the necessary flags to be able to get HPA working. @moelsayed will provide the necessary yaml.

**Comment by adingilloRancher** [comment]
Master 6/8/2018

Tested above yaml and steps.

Verified ability to see metrics data.

**Comment by AntonW** [comment]
Hi @moelsayed, @adingilloRancher 
I have the same Issue. Can you tell me were are the advanced settings? I cannot find them.

Thanks in advance

**Comment by harshsharma22** [comment]
happens with  Kubernetes Version: v1.18.2+k3s1  provider k3 rancher version2.4.2
