### ISSUE TITLE
Support Rancher Templates

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#1272]
Rancher needs to support re-usable "templates" for the following use cases:

- A public template that can be re-used to launch managed micro-services within Rancher
  * Kubernetes
  * Mesos
  * ELK logging service
  * Swarm scheduler
  * Rancher storage and volume service
- Allow users to "save" existing compose/rancher templates so they can be re-used again.
- Initial support in terms of visibility will be:
  * Visible to everyone in rancher (public templates)
  * Visible to everyone within an environment

**Comment by will-chan** [comment]
- PoC of variable replacement.
- Adding support for runtime variables.

**Comment by faddat** [comment]
I'm so very in support of this.  110%.  While we are going blue-sky, let me
go ahead and mention how incredibly awesome an ARM port would be, and
additionally mention that if given some pointers, I think I can handle the
porting....

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by ibuildthecloud** [comment]
@faddat do you want all of rancher to run on ARM or just the hosts.  Specifically rancher/server.  Do you envision running that on ARM too?

**Comment by faddat** [comment]
Sorry, should have been more specific!

I'd like to run RancherOS on ARM, and on top of it run rancher/agent.  I
was going to start with rancherOS, because (I assumed) that I could
retrofit it into the ever-amazing build instructions for the bananaPI
platform distributed by Igor Pekovnik https://github.com/igorpecovnik/lib.

Rancher/server is more like a that'd be nice to run on ARM than a OMG it'd
change everything if I had that running on ARM!  Waaaaait.  You folks have
those build images.  Are you telling me.... *looks to board with docker on
it an ARM core...."  (YEah, I'll be trying that and I'll report back)

*What I'm trying:*
Just take the master-builder image and make sure that its source ("FROM")
is something ARM-based and then let er rip.  I'll fire off another message
afterwards.

I guess that with the templates, I'm by no means the only one who has been
thinking something along the lines of "let's put a menu to the left of
infrastructure that says 'Applications' and call it a day."  Of course, the
Rancher team would never do the second part, till every thought was
finished.    You guys are incredible.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by ibuildthecloud** [comment]
@faddat towards the end of they month we will be dedicating time to getting RancherOS running on RPi2.  With the exception of the kernel I believe this will make it such that we can easily run on most armv7 devices.

**Comment by faddat** [comment]
:)!

Playing with building the agent now

**Comment by faddat** [comment]
Also, I re-read the original comment and would very much like to add my two bits on this:

Rancher is great for open source web applications, and it could be useful to consider putting an "applications" menu into it because that would enable people who aren't terribly cloud-literate to build out entire clouds without much difficulty or cost.  I see Rancher as an empowerment technology, and the more people empowered by it, the greater its value.  

So-- 

My thought on this would be that it would be a great strategy to include a publicly generated set of deployment parameters-- "Ready to go applications/services" as it were, that run straight out of the box.  Additionally a social element could be added by allowing people to click a checkbox and share their particular deployment of publicly available images (ex: the docker-compose.yml and rancher-compose.yml) with the community at large.  A "5-star" ratings system could be used to keep quality floating to the top.  

:).  

Thanks!

**Comment by vincent99** [comment]
@faddat That is basically what we're talking about here (minus the global sharing/social bits for now).  Parametrized compose templates maintained by us with a description of the parameters so that the UI can show a list of applications, the user picks one, fills in a few options, and the compose project is spun up.  

Some of the templates will likely require custom startup scripts, e.g. to discover all the peers for Zookeeper, so we'll do that to make them "just work".

**Comment by faddat** [comment]
FYI,

DinD was my chokepoint for ARM.  :)

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by thaJeztah** [comment]
>  That is basically what we're talking about here (minus the global sharing/social bits for now). Parametrized compose templates maintained by us with a description of the parameters so that the UI can show a list of applications, the user picks one, fills in a few options, and the compose project is spun up.

That's really an ideal thing for our company. Ideally, being able to check-in the template into version-control, so that a developer can checkout a project and start it from that template?

Must admin, if "global sharing/social bits" are taken into account, it sounds a bit like http://panamax.io

**Comment by will-chan** [comment]
Breaking this feature into four phases:

Phase 1:
Add Rancher CLI to list and run Rancher Catalog templates hosted on Rancher public Github project.
* Templates must be "generalized" and support variables that can be replaced.
* Rancher CLI must be able to query for user input either as a parameter within Rancher or specified in a file.
* Decide whether to add this logic as a separate micro-service, done at Rancher CLI, or inside Cattle server.

Phase 2:
Rancher API/UI integration.  

Phase 3:
Integration with a meta data service hosted by Rancher.  This also included pre-determined Rancher run-time meta-data information.  See #1431

Phase 4:
Support private catalogs and be able to launch them via Rancher CLI/UI.

**Comment by faddat** [comment]
Rancher CLI = rancher-compose , or is this something new and exciting?

**Comment by deniseschannon** [comment]
@faddat Yes, Rancher CLI = rancher-compose. :)

**Comment by janeczku** [comment]
+1 for porting the Rancher agent ecosystem to Linux ARM platform. I'd love to be able to deploy Rancher nodes on Scaleway's bare-metal cloud.

**Comment by cusspvz** [comment]
> Add Rancher CLI to list and run Rancher Catalog templates hosted on Rancher public Github project.

+1

> Rancher CLI must be able to query for user input either as a parameter within Rancher or specified in a file.
> Rancher API/UI integration.

That would be awesome! Those features would enhance **Rancher** to be much more usable than **CoreOS** and **Panamax** together! :)

**Comment by cusspvz** [comment]
@vincent99
> the user picks one, fills in a few options, and the compose project is spun up.

Those options will be all environment variables available on template?
If not, is there some kind of structure for defining options and their attributes such as: `name`, `description`, `defaultValue` and `validation`?

**Comment by vincent99** [comment]
The docker/rancher-compose.yml files will have variables in them, e.g. 

```
database:
  image: mysql:${version}
  environment:
    MYSQL_ROOT_PASSWORD: ${root_password}
```

You will be able to use rancher-compose on a file like this and it will prompt for values for the variables, or take answers in as a separate file.

The template definition can (optionally, but will for anything we maintain) contain more info about each variable so that the UI can display friendlier questions.  Very similar to the [API schema](https://github.com/rancher/api-spec/blob/master/specification.md#schema-fields) defining fields on resources.

**Comment by cusspvz** [comment]
That solves my doubt. Going to pull some templates after dinner :)

**Comment by flaccid** [comment]
Really excited about getting this. Happy to test and provide feedback before release.

**Comment by ajagnanan** [comment]
@faddat , did you manage to get the rancher-agent running on raspberry pi?

**Comment by deitch** [comment]
Is there documentation as to how to use the "templates" or "catalog"? I couldn't find anything in docs.rancher.com, but would love to try this out.

**Comment by deniseschannon** [comment]
I forgot to push my doc change, so it was missed in the v0.43.1 doc release. 

http://docs.rancher.com/rancher/rancher-ui/applications/catalog/

**Comment by deitch** [comment]
Thanks @deniseschannon I see it now. Nice, really should make some of the enterprise growth easier.

Some questions:

1. Is there a way to do this from the API / rancher-compose?
2. I see it pointing to the official rancher catalog templates from https://github.com/rancher/rancher-catalog . Is there support for custom templates (i.e. templates I can add for my installation of Rancher)? 
3. I see that I use the catalog to create a stack. Can I use it to add applications to an existing stack?

**Comment by vincent99** [comment]
1. The templates are just compose files, you can clone the catalog deploy them with a suitably new `rancher-compose` (and `--env-file` to fill in variables).  The answer to "the UI does X, can I do that in the API too" is *always* yes.  It reads the template from the catalog API (`GET /v1-catalog/templates`), collects answers to the questions and passes the yml + answers to stack create (`POST /v1/{projects/1a5}/environments`).

2. You can change `/v1/settings/catalog.url` to point to your own repo today, which could be a fork of ours (or not).  Soonish will support configuring multiple repos.

3. No; the immediate reason is there's just not an API call for adding services via compose/yml to an existing stack, only creating a new one.  But there is detection to show that upgrades are available when new template versions are put into the repo and determining which N catalog items + user services + potential naming conflicts a stack is composed of would significantly complicate things.

**Comment by deitch** [comment]
Hey @vincent99 somehow I knew you would have the answers!

1. OK, got it. So I can use an existing catalog using the above steps. I know I have asked this before, but please add to the docs?
2. Nah, I don't want that kind of manual hack right now. I would rather wait for your support for multiple catalogs. Do you have some sense of "soonish"?
3. Is that true? I do it all the time. I use rancher-compose with a yml to add a service, reference an existing Stack name, and it just adds it to the existing Stack. It works like a charm and we use it pretty heavily. 

For 3 above, when we release a new version, we have a release manager who uses their own API to "authorize" a given release. This then creates the Service inside the existing Stacks (we have a Stack per QA environment, or per pod/cluster). The actual administrators just need to "start" the Stack which was made available.

Private Catalog would go a long way towards this. We would just add it to the catalog.

**Comment by vincent99** [comment]
1. We're getting there...

2. I think there's a PR for the API now, but it needs some work to disambiguate templates with the same name in different catalogs, and then UI support to group by them.  Probably 2 weeks, but there's a lot going on for DockerCon EU.

3.  The compose cli does the yml parsing and turns that into the various calls to manipulate services in the API.  The only API that takes actual yml is in create stack (environment).

**Comment by deitch** [comment]
I keep telling people that speed of reliable iteration is the most important factor. I like how this is new and yet, "probably 2 weeks." Love it.

Well, when you get the catalog moving further ahead, definitely keep the ability to add a service to an existing stack. It is very powerful.
