### ISSUE TITLE
RBAC in pipelines -- non-admin users are unable to view / create pipelines

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#12794]
**Rancher versions:**
rancher/server: Master 4/17

**Steps to Reproduce:**
As an admin user, create a cluster & enable pipeline integration w/ Github auth settings.
Add a standard user as a cluster owner or member.
Login as standard user, navigate to the existing cluster project & view pipelines. - All pipelines should be visible & new pipelines can be created. 

**Results:**
Standard user cannot see any existing pipelines.
When adding a new pipeline, message that pipeline is not enabled is displayed with link to enable. 
When clicking the link to enable, the user is logged out.

**Comment by gitlawr** [comment]
missing rbac rules for users as a project-owner. 
In my test results:
As a `Cluster-Owner`, can list & add pipelines
As a `Cluster-Member & Project-Member`, can list & add pipelines
As a `Cluster-Member & Project-Owner`, **cannot** list & add pipelines
Should be fixed by https://github.com/rancher/rancher/pull/12573

**Comment by bmdepesa** [comment]
Validated on master 4/18 - standard users can create/view pipelines if given access to cluster/project.
