### ISSUE TITLE
Download Machine Config - HTTP Error 413: (Request Entity Too Large)

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#1280]
I just started up two new hosts on Digital Ocean and when they came up, wanted to get the machine config out of them so i could ssh into them and add some swap space but when I do, i get `(Request Entity Too Large) 413` error in the console.

It would seem that the URL is to long.

**Comment by jwhitcraft** [comment]
But when i go directly to the API and hit the v1/machines/<uuid>/config it downloads just fine.

**Comment by vincent99** [comment]
The UI adds `?token=<jwt>&projectId=<id>` to the URL because it's going into a new window (frame) and won't be authorized.  This isn't actually necessary any more with switching to cookies for passing the token (rancherio/ui#214) that will be in the next release.

Still, Java appears to be limiting the query to 4kb, is your token really anywhere near that size @jwhitcraft?  It includes the GitHub teams/orgs you're a member of, but that would have to be quite a few.  

If you open up the developer tools in your browser you can use the network tab to see the request, or in Chrome there's the Resources tab and the token is under Session Storage (in the current release).

**Comment by jwhitcraft** [comment]
@vincent99, I think it would be since i'm a member of 5 orgs and multiples teams inside of each org.

**Comment by vincent99** [comment]
Ok; we'll likely reduce the size of the token by moving the team/org membership into a cache on the server side.  Even if it worked sending 4+lb on every request isn't very desirable.

**Comment by jwhitcraft** [comment]
:+1:

**Comment by ibuildthecloud** [comment]
@vincent99 I've put in a change to increase the query string size to about 16k.  I figured going much bigger means we will probably hit issues other places.  Sounds good?

**Comment by vincent99** [comment]
As a temporary solution yes.  Still think we should address it with a smaller and bounded-length token.

**Comment by vincent99** [comment]
This should be resolved for now with the 16k limit..

**Comment by deniseschannon** [comment]
@jwhitcraft I haven't been able to test this as I don't belong to that many groups in GitHub. Have you been seeing this issue in any of the recent releases?

**Comment by vincent99** [comment]
This should definitely work now in the next release with a fixed-length string sent back to the client and 16 megabyte limit on the server side.
