### ISSUE TITLE
Changing node Template of a deployed pool doesn't reconcile

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#12824]
**Rancher versions:**
rancher/server:v2.0.0-beta3

You have the option to change the node template of an already deployed pool, but saving it doesn't actually change anything so it no longer reflects the deployed pool.

We should either disable the changing of the node template once deployed, or we should reconcile by destroying existing nodes and redeploying using the new template

**Comment by deniseschannon** [comment]
@vincent99 can we disable changing node template of a deployed pool?

**Comment by vincent99** [comment]
No?  You can change it, and it applies to any new nodes created in that pool, just like editing the existing node template (which is a thing you can do now).

If you want to recycle all the old VMs you can do that yourself, but us doing that automatically is dangerous.

**Comment by chrisurwin** [comment]
I think that node templates should not be editable once machines are deployed via it. If people want to change a node pool they should create a new one, give people the ability to clone the template.

Not only does going to the cluster edit page kind of imply that all of the nodes are of this type, going to the node page also implies that all of the nodes are of the types are what is described in the pool description.

Alternative is that you remove the template from the node pool description on the node page and when they click + to add more nodes give them the option of which template to use.

At the moment I believe the way it displays the information can be misleading to the user.

**Comment by chrisurwin** [comment]
in beta 3 it appears as 
![image](https://user-images.githubusercontent.com/13744596/38987616-4d8f7512-43c8-11e8-811b-5e846dd0798c.png)

Which is incorrect, only one of these is a medium, the others are small

**Comment by vincent99** [comment]
I was thinking of the location/size column on the Node Template instead of what's on the Node page.  The CPU/RAM columns do reflect the size of the actual node.  

Anyway, you do not _have_ to use edit if you don't want to, you can make a new pool, put a new template on it, scale them up and down and all that if you want to do it that way.  You can even make an RBAC role that doesn't let people edit Node Templates at all.

But it is massively more convenient to just allow editing, and we think easily understandable.  So all we're going to change is adding a note:

![image](https://user-images.githubusercontent.com/753917/39016576-b2c13e68-43d5-11e8-98b5-6dd657c8d27f.png)

**Comment by chrisurwin** [comment]
So are we going to update the Cluster/Node page as well, as it would be better to remove the node information than to have it showing misleading information?

**Comment by tfiduccia** [comment]
Version - 2.0 master 4/23
Verified - text added to edit node template.  Also verified that the info on the nodes page and cluster page are being updated.
