### ISSUE TITLE
Encryption Of a Resource Field.

### ISSUE THREAD

**Issue by hibooboo2** [rancher/rancher#1285]
This comes from the need to secure private data.
 
Overall functionality goal being from an api point you see no differences. You create a resource, when it is stored to db it is encrypted. When you read the resource it is decrypted.

In this context encrypted and decrypted is a transformation of data in some way that has many implementations.

**Comment by hibooboo2** [comment]
* Encrypter
    * encrypt (value)
    * decrypt (value, metadata)

* EncrypterHandler
    * encrypt (value, encrypterName)
             * This will use the encrypterName to chose the correct encrypter and pass the value to the encrypt function.
     * decrypt (value)
            * This will take the value Split on : to seperate the METADATA and VALUE one the encrypted value.
                 * EX: ```NoOp$salt!someMoreMetaData!moreMetaData:VALUE``` will yield METADATA=```NoOp$salt!someMoreMetaData!moreMetaData``` and VALUE=```VALUE```
            * Then it will split on $ to get the Encrypter Name and the MetaData needed for Decrypt.
            * Call decrypt providing metadata and value on the correct Decrypter.

**Comment by vincent99** [comment]
I thought you were calling them transforms.. Not all handlers are encryption.

The decrypt/spltting logic seems like it's in the wrong place..  
  - TransformHandler.untransform(value) should split the value into 2 pieces at `firstIndexOf('$')`, look at the first part to get the transform name, and blindly pass the 2nd part to the correct `impl.decrypt()`. 
  - The impl can then encode any metadata it has however it wants, unaware that it will be prefixed with the impl name before being stored.
  - And it contain its own logic for handling that metadata if the format ever needs to be changed.
  - You can also probably use only 1 or 2 delimiting characters instead of 3 by reusing the outer delimiter inside the impl.

Some transforms like hashing will not have a decrypt/untransform.
  - You'll need something like a `handler.compare(storedValue, providedCleartextValue)`.
  - For a 1-way hash it would parse the storedValue to extract the salt, call a (private) method to `hash(salt,providedCleartextValue)`, and return if that is equal to the stored value (or maybe the hashing library just has a method for all that).
  - For 2-way transforms it could be no-op, or just return `decrypt(storedValue) === providedCleartextValue`.

Speaking of which, some transform implementations will probably need other inputs, like an encryption key. 

I don't know how shared-libraries work in Java and this probably isn't needed initially, but companies have their own crazy secret storage systems.  If a user could easily-ish plug in their own transformer without forking Cattle:

![image](https://cloud.githubusercontent.com/assets/753917/8244551/00706cfe-15d7-11e5-8516-27664a433041.png)

**Comment by vincent99** [comment]
You should also assume that un/transform could be long, slow, asynchronous operations that talk to a remote host, if that requires any changes to the interfaces.  (i.e. if this were JavaScript, add `, cb` to the signatures of everything. or return promises.  or generators. or...)

**Comment by hibooboo2** [comment]
As for the first one i designed it as suck the naming if things can change but the concepts are the same. as for the second comment in must be synchronous as the current design does this before any thing else on the request. We may want to move it to the resource manager level so that it happens before reading and writing to the db. Not sure requires a design discussion with @ibuildthecloud but where it happens is easy to change so this is none blocking.

**Comment by will-chan** [comment]
- Determine best place to encrypt the individual values.

**Comment by hibooboo2** [comment]
Added with rancher/cattle#725
