### ISSUE TITLE
Alerts triggered with no event.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12922]
**Rancher versions:**
Master 4/20/18

Steps:
Create a new cluster.
Create alert for Daemonset and Statefulset events (I set initial wait for 30 seconds).
Create a new Daemonset workload and Statefulset workload.

Results:
Initial alert is received. However, alerts are still triggered without new events being logged.
![screen shot 2018-04-20 at 9 06 30 am](https://user-images.githubusercontent.com/38012481/39061795-55b3c8ee-447a-11e8-9650-e363954302d5.png)

<img width="560" alt="screen shot 2018-04-20 at 9 09 29 am" src="https://user-images.githubusercontent.com/38012481/39061859-8eb47abc-447a-11e8-84fa-f00f90ccb34f.png">

<img width="1262" alt="screen shot 2018-04-20 at 9 06 42 am" src="https://user-images.githubusercontent.com/38012481/39061798-5b3e223c-447a-11e8-8dab-5c59eef15cf6.png">

**Comment by zionwu** [comment]
@adingilloRancher  I would like to know the setting for `Interval` parameter in advanced options.

Are you setting it to a short interval like  5 min?

**Comment by zionwu** [comment]
I can't reproduce the issue. I created an alert for normal event of StatefulSet, with 10s `Initial Wait` and 10min `Interval`. And only one alert message is received. 

However, if you are setting  `Interval` to a short interval like 1 min, you will receive 5 message. This is because the alert manager has the `resolve_timeout` parameter, of which the default value is 5 mins.  ResolveTimeout is the time after which an alert is declared resolved if it has not been updated. It means once an alert is triggered,  it will stay active for 5 mins. If `Interval` is 1 min then 5 message will be sent out.  However, the `Interval` is usually ~1h or more.

**Comment by adingilloRancher** [comment]
@zionwu It was set to the hour default.

**Comment by zionwu** [comment]
I can reproduce it.  event watcher watches the event ：
```
events.AddHandler("cluster-event-alerter", eventWatcher.Sync)
```
we should investigate why the `Sync` is invoked by the norman framework when no new event happens.

**Comment by zionwu** [comment]
@adingilloRancher  I tried again and can not reproduce this issue.
1. create an alert for daemonset event and an alert for statefulset event.
2. create an daemonset workload and statefulset workload.
3. only receive one notification for each alert:
![image](https://user-images.githubusercontent.com/1213386/39918529-54487fc0-5543-11e8-8a02-4f2ec845887e.png)

Can you retest in you env?

**Comment by adingilloRancher** [comment]
<img width="407" alt="screen shot 2018-05-25 at 9 03 30 am" src="https://user-images.githubusercontent.com/38012481/40554427-873a357e-5ffa-11e8-812a-255c073d11bc.png">

Verified alerts are coming in.
