### ISSUE TITLE
Add Labels to already created service

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#1292]
I have a set of services that I would like to add affinity labels to even after creating them.  Currently I can not find a way to do this via the UI or API.  It would be cool to have that ability.

**Comment by deniseschannon** [comment]
Currently, we don't allow updating labels after creating a service. One workaround is to clone the service and add the labels. Anything that the service is dependent on already linked, but anything that is dependent on the service will need to be redirected. If you have services dependent on your service, you could add in a service alias/dns service to help alleviate the dependencies. Read more about service alias here: http://rancherio.github.io/rancher/docs/services/projects/adding-service-alias/

**Comment by vincent99** [comment]
This isn't currently allowed because the new labels can't be applied to any existing containers of the service.  So we'd have to figure out what happens to existing containers.. do they get deleted/recreated, rescheduled to different hosts if the one they're on is longer eligible according to the new labels/rules, how many do you restart at a time, what if the scale is 1 and you'll take the service down, etc.

Some of that will be more practical after https://github.com/rancherio/rancher/issues/1079 .

**Comment by jwhitcraft** [comment]
Thanks for the info guys, I'll be on the lookout for this and #1079

**Comment by deniseschannon** [comment]
In-service upgrade should be able to solve what you were looking for. @jwhitcraft Please re-open if you don't think it helps.
