### ISSUE TITLE
Logs parameters in CLI do not get applied

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12924]
Version: rancher/cli v0.6.9

Specifying tail in the CLI does not get passed/used.

```
./rancher logs --tail=5 aaa-nginx-1 | wc -l
100
```

Docker daemon logging
```
dockerd[3958]: time="2018-04-20T16:13:32.636061657Z" level=debug msg="Calling GET /v1.22/containers/e46bda2fcb13d6535d9c5e6b7aa7277527e9750330ac8d1e8d92369cfe60c256/logs?stderr=1&stdout=1&tail=100&timestamps=1"
```

Also, `--timestamp`, `--since` seem not to work. Tail seems to be set at `100`.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by dramich** [comment]
This is a server side issue. The logs handler is not parsing the number so defaults to 100 for `--tail` and is ignoring the input for both `--timestamp` and `--since`.

https://github.com/rancher/host-api/blob/master/logs/logs.go#L47

**Comment by alena1108** [comment]
The fix should go to host-api

**Comment by dramich** [comment]
So, this is now a multi part fix. 

1. CLI - update so all fields are getting passed through to the API server. Fixing this and the host-api will fix the `--tail` issue.
2. host-api - Fix the conversion of the `tail` value and also add getting of the other required fields - `timestamps` and `since`. This will fix the number of lines showing up but will not fix the other two. 
3. Cattle server - The API does not support `timestamps` and `since` so these will need to be added. `timestamps` is a bool and `since` is a string. Based off Alena's finding the following three files would need to be updated : 
 - ContainerLogs.java
 - user-auth.json - permissions for the fields
 - [ContainerLogsActionHandler.java](https://github.com/rancher/cattle/blob/v1.6/code/implementation/docker/api/src/main/java/io/cattle/platform/docker/api/ContainerLogsActionHandler.java#L53)

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by sangeethah** [comment]
Tested with rancher/server:v1.6.26-rc1 and rancher cli version - rancher-v0.6.13-rc1
```
MacBook-Pro-3:rancher-v0.6.13-rc1 sangeethahariharan$ ./rancher --url http://35.188.179.245:8080 --access-key 7B7787F85BDEA4380326 --secret-key 
wnhP1dTeF416XxvB8RaCm3DavkuwJQVmjKBkdUiy logs --tail=2 mytest1/mytest
63.205.203.157 - - [08/Jan/2019:01:11:50 +0000] "GET / HTTP/1.1" 304 0 "http://35.188.179.245:8080/env/1a5/apps/stacks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"
63.205.203.157 - - [08/Jan/2019:01:11:58 +0000] "GET / HTTP/1.1" 304 0 "http://35.188.179.245:8080/env/1a5/apps/stacks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"

MacBook-Pro-3:rancher-v0.6.13-rc1 sangeethahariharan$ ./rancher --url http://35.188.179.245:8080 --access-key 7B7787F85BDEA4380326 --secret-key wnhP1dTeF416XxvB8RaCm3DavkuwJQVmjKBkdUiy logs --tail=4 mytest1/mytest
63.205.203.157 - - [08/Jan/2019:01:11:49 +0000] "GET / HTTP/1.1" 304 0 "http://35.188.179.245:8080/env/1a5/apps/stacks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"
63.205.203.157 - - [08/Jan/2019:01:11:49 +0000] "GET / HTTP/1.1" 304 0 "http://35.188.179.245:8080/env/1a5/apps/stacks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"
63.205.203.157 - - [08/Jan/2019:01:11:50 +0000] "GET / HTTP/1.1" 304 0 "http://35.188.179.245:8080/env/1a5/apps/stacks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"
63.205.203.157 - - [08/Jan/2019:01:11:58 +0000] "GET / HTTP/1.1" 304 0 "http://35.188.179.245:8080/env/1a5/apps/stacks" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"
MacBook-Pro-3:rancher-v0.6.13-rc1 sangeethahariharan$ 
```

**Comment by soumyalj** [comment]
Tested with rancher/server:v1.6.26-rc1 and rancher cli version - rancher-v0.6.13-rc1
In the API we do see option to specify lines, since and timestamp as below
<img width="745" alt="screen shot 2019-01-10 at 3 44 05 pm" src="https://user-images.githubusercontent.com/18536626/51004288-cb793100-14ee-11e9-8ace-fe6119f0c559.png">

The fields are functional. API calls were tested with python 
```
def test_logs_token(client):                                       
    url = "ws://abcde/v1/logs/"             
    token = "abc"
    conn = ws.create_connection(url + '?token='+token)                      
    count = 0                                                                                               
    while count <= 100:                                 
       count += 1                                      
       try:                                            
           result = conn.recv()                        
           print result                                
       except ws.WebSocketConnectionClosedException:   
           break                                       

```
