### ISSUE TITLE
Add Azure AD as an auth provider in 2.0

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#12942]
Make sure to be able to configure Azure AD and Azure AD China

**Comment by dramich** [comment]
This is in master.

**Comment by olljanat** [comment]
Here is some test results from rancher/rancher:master image:
- [Mandatory](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code#request-an-authorization-code) parameter **response_type=code** is missing from redirectUrl generated by /v3/azureADConfigs/azuread?action=configureTest
- You always get generic **Azure access was not authorized** error no matter why it fails so it is very hard to figure out working configuration.
- **Endpoint** parameter in UI is useless as it is always: https://login.microsoftonline.com/
- **Graph Endpoint** parameter in UI is useless as it is always: https://graph.microsoft.com/v1.0/
- **Token Endpoint** parameter in UI is useless as it is always: https://login.microsoftonline.com/{tenantId}/oauth2/token
- **Auth Endpoint** parameter in UI is useless as it is always: https://login.microsoftonline.com/{tenantId}/oauth2/authorize

**Comment by dramich** [comment]
Hey @olljanat, thanks for taking an interest in this. To address your concerns:

1. The parameter is added by the UI as it may need to add/remove them as needed for different types of logins required. 
2. This is most likely because you are blocking the popup where you sign in to MS. If you disable your popup blocker you should get the MS sign-on page then get a real error if something still isn't correct. The UI not telling you the popup is being blocked is a known issue and should be addressed soon. 
3. All the endpoints are needed as those are not the only endpoints. As an example China has it's own endpoints. We also do not want to maintain a list of MS endpoints in our code so we ask for them.

**Comment by olljanat** [comment]
1. OK. Then I would propose that you will fill working configs to these fields and let user to change them if needed.
2. True and looks that Chrome does always tell when it blocks popups.
3. Ok but used library/sdk anyway defines which API versions are supported. Example authentication endpoint https://login.microsoftonline.com/common/oauth2/v2.0/authorize and https://graph.microsoft.com cannot be used with current library.

Thanks anyway of your help with this. I got it working on my lab and updated working endpoint list to my earlier message.

**Comment by adingilloRancher** [comment]
Master 6/19/18
Completed test pass for AD testing with Azure AD.
Also validated China AZ Ad was working as expected.
Tested 2FA users.
