### ISSUE TITLE
Rancher 2.0 with cluster on AWS- cannot build control plane

### ISSUE THREAD

**Issue by NewBDAQ** [rancher/rancher#13003]
Creating a test cluster on AWS, I consistently get: [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [18.208.109.51]: Get https://localhost:6443/healthz: can not build dialer to cluster-fhtbj:m-np88w.

I keep changing the template, and have seen that others are having similar issues, but I have found no solutions.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by deniseschannon** [comment]
@NewBDAQ Can you try with v2.0.0-beta4 and did you make sure the ports are open? https://rancher.com/docs/rancher/v2.0/en/quick-start-guide/#port-requirements

**Comment by armsby** [comment]
I am having the same issue, I have a questions about the port requirements, the documentations says that the ports needs to be open on the master nodes and worker nodes, is that towards the management server or only between them self?

**Comment by armsby** [comment]
I have just tried with 2.0.0-rc3 this time towards hetzner cloud, I am running all 3 services on the same node so there should be no issue with ports, also from my rancher server I can telnet to all the ports on the list,

If I login to the node and curl the url https://localhost:6443/healthz I get a certificate failure, but if I use the -k on curl it returns "ok" so the check works the server just dont get it, what information can I provide?

**Comment by paulyhedral** [comment]
I have the same issue. Tried beta2 through beta4, and had to manually edit the security group to make sure the ports were open, but it still fails.

**Comment by 34code** [comment]
Same issue. Also trying on hetzner. Tried with all services on all 5 nodes and also with independent nodepools per service.

**Comment by armsby** [comment]
I have just look some more into this, and I cant get it to work on hetzner, the health check is ok if I hit the public IP from the rancher server, I still get a certificate error, but that is probably because im not loading any certificates, can anyone with some more experience direct me on where to look to locate the issue

**Comment by superseb** [comment]
Please run through these and create a new issue with your steps to reproduce:

Issue 1:
Nodes created/added cannot reach the configured server-url (usually the IP/name of the host running the rancher/rancher container or LB/proxy), this can be tested by running curl -k https://configured_server-url on the node and see it you get a response, if so, network connectivity is not an issue. This is not something Rancher can automatically configure as you created the node running rancher/rancher yourself, so you need to configure appropriate access inbound from the created node IP/subnet. (HTTPS, TCP/443) https://rancher.com/docs/rancher/v2.x/en/installation/references/

Issue 2:
Certificates are not configured correctly, usually this occurs when a recognized CA certificate needs intermediates added to the certificate to function. It can work well in the browser, but that won't work in the Go agent. Intermediates need to be added in order, your certificate first, followed by intermediates in the chain. This can be checked by the logging of rancher/rancher-agent where it will say x509: certificate signed by unknown authority

Issue 3:
Proxy/loadbalancer does not have the prerequisites listed in the docs, so not support websockets/not passing the correct headers/no HTTP2.

**Comment by CRuppert** [comment]
@superseb i don't know why you closed this? You didn't link to any other ticket. As the ticket describes, this happens to a lot of people.
 

This happens on azure as well. This happens with a default, out of the box install on Azure. 

If you want steps to repro, follow your quick start guide on azure. It's really that simple. 

I am on 2.0.5, running on the Ubuntu 16.04 LTS.
I have verified the ports are open as described. (80+443 incoming)
I have verified the machines and firewalls are being created appropriately in the Azure portal.
I am using the directions provided in the quickstart for rancher 2.0.
I am creating a single node cluster using the canal networking protocol, using the default self signed cert as is generated and managed by Rancher 2.0
I am using the default image in the default node template.

This also appears to be a very common issue.

**Comment by superseb** [comment]
It's about the connection between the host running the `rancher/rancher` container  and the nodes that are created. The steps above point out how you can diagnose the issue, and if it still happens, you can create a new issue with the steps needed to reproduce and what the outcome is of the above steps. Verifying configuration is fine, testing it if it applies is better. That's what the steps above describe. (i.e. port 80+443 incoming in firewall is fine, testing if the agent can reach it is better), also the logging from the `rancher/rancher-agent` container will tell why it can't connect.

**Comment by CRuppert** [comment]
@superseb with all due respect, did you read my entire entry?  I am not trying to be difficult here, but have you tried the out of the box experience using the quickstart guide on a clean cloud install?

I stated that the ports are open and allowed entry, and are WIDE open. no IP restrictions.
I also specifically stated that the steps to repro are following your quick start guide. 
I have told you the cert config used, and the image used in my template. I don't really know what other steps to repro that I could provide?  

If you want me to open a new ticket to provide the same information, I can do so? 

This might be one of those times though where you might want to take the 20 minutes to follow your own quick start guide with a vanilla experience, just so you can see where we are coming from, rather than shutting down the ticket with "provide moar repro"? It's literally the out of the box experience that is broken for me, and apparently several others.

I will attempt to access the logs, but really, this is the out of the box stuff, shouldn't it Just Work?
