### ISSUE TITLE
Cannot deploy sidecar

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13028]
rancher/server:master 04/23

Steps to reproduce:
1. Create  a deployment via UI
2. Click add sidecar of the deployment
3. Deploy sidecar

Results:

Server returns the following issue. I guess this is a backend issue?

```
Validation failed in API: Deployment.apps "rancher" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{}: `selector` does not match template `labels`
```

Expected:

Sidecar should be added successfully.

**Comment by kinarashah** [comment]
Hi @loganhz, 
The issue seems to be that labels is sent empty from the sidecar page. 

When we do a normal edit, workload has this label - 
![image](https://user-images.githubusercontent.com/16870565/39208843-e146c848-47b8-11e8-9d3c-e0643a1aabd3.png)

But from add sidecar page, 
![image](https://user-images.githubusercontent.com/16870565/39208891-027fa35e-47b9-11e8-94ca-d20d7f66f6ab.png)

could you make this change and see if it works?

**Comment by loganhz** [comment]
Thanks @kinarashah ! Fixed in UI side

**Comment by tfiduccia** [comment]
Version - v2.0.0-beta4-rc4
Verified fixed
