### ISSUE TITLE
Ability to set flags/extra_args & extra binds for kubernetes components in the UI

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13076]
All the components have configurable flags that might need to be adjusted for a particular need, or added to get extra functionality. As of today, this is only possible using RKE and import.

As this can break clusters, we can add an Advanced Options which allows users to add flags to kubernetes components with the warning this can break their cluster/use at your own risk etc.

**Comment by vincent99** [comment]
@loganhz This is going to need design and consideration so I wouldn't just go build something...

**Comment by loganhz** [comment]
@vincent99 can we do something like edit RKE config in yaml?

**Comment by agasbzj** [comment]
So how to use RKE to achieve that for now?

**Comment by vincent99** [comment]
@loganhz Can you do:

- Add an advanced options at the bottom of cluster config, which takes the YAML for the contents of the `rancherKubernetesEngineConfig` field.
- You'll probably need a blacklist of things to remove from the displayed YAML because they have custom UI options.
- On save, convert to JSON (`yamljs` is already loaded) and overlay/recursively merge the custom settings into the resource
- Drop etcd heartbeat/interval, and flannel/canal iface options from the UI, since they're not that common and can be set in YAML now.
- For bonus points, read the schema and construct YAML with all the fields that are possible shown but commented out so it's easy to find what you want and edit the YAML.

**Comment by tfiduccia** [comment]
Version - 2.0 master 6/4
Verified fixed

**Comment by kirankamineni** [comment]
@agasbzj until I can pull this change into my environment, I used the suggested workaround of creating an environment using **rke up** (**extra_args** in the config can be used to pass additional args to kubelet and others) and then importing that created env into the Rancher UI via the **import** option.

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/19

Cluster options are being displayed in YAML and editing works correctly.
