### ISSUE TITLE
Issue with static IP and Layer 4 LoadBalancer on GKE

### ISSUE THREAD

**Issue by Toflar** [rancher/rancher#13118]
**Rancher versions:**
rancher/server:preview

When I want to expose a workload, say `nginx`, to the world, I configure the port `80` to be exposed as port `80` as L4 LoadBalancer. For GKE, Rancher then automatically creates an IP in GKE causing an issue when you already have a static IP (quota exceeded). Either it should take the one that is already there or ask me which one I would like to link to (or at least give me the option to configure it).

**Comment by tfiduccia** [comment]
@Toflar - Rancher uses port 80 for ingress.  You will have to use a different port to expose nginx out to the world.  This is not a bug and we do not plan on changing it.

**Comment by Toflar** [comment]
Rancher is not installed on the the GKE cluster...

**Comment by vincent99** [comment]
Rancher creates a service with type=LoadBalancer, which goes into Pending state.  The cloud provider configured for the cluster is then responsible for watching for these and creating/assigning a balancer to satisfy them.  In this case the cloud provider is GKE's, and they create a new balancer with a new IP for each request.  There may be an annotation or something you can specify to request reusing one.

(But if so you'll need to create the workload and service separately, since there's nowhere to pass annotations for the service in the UI while creating a workload.  And creating standalone services has not made it into the UI yet, though you can do it with YAML).
