### ISSUE TITLE
Storage-class using ceph-rbd as backend error

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#13198]
When using ceph-rbd as the storage-class backend, the following error is reported when you configure rbd to create pvc in the UI：
```
Warning ProvisioningFailed 2s (x25 over 6m) persistentvolume-controller Failed to provision volume with StorageClass "rbd": invalid option "adminSecret" for volume plugin kubernetes.io/rbd
```
When I change adminSecret to adminSecretName can succeed
Ui generates incorrect configuration
```
apiVersion: storage.k8s.io/v1
Kind: StorageClass
Metadata:
  Annotations:
    field.cattle.io/creatorId: user-hzhxh
  creationTimestamp: 2018-04-30T03:59:04Z
  Name: rbd
  resourceVersion: "1915672"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/rbd
  Uid: d2ee45e8-4c2a-11e8-8dad-00163e04a673
Parameters:
  adminId: admin
  adminSecret: ceph-secret-admin
  adminSecretNamespace: default
  Monitors: 172.31.164.57:6789
  Pool: rbd
  userId: default
  userSecretName: ceph-secret-admin
Provisioner: kubernetes.io/rbd
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Normal configuration  
```
Kind: StorageClass
apiVersion: storage.k8s.io/v1
Metadata:
  Name: rbd
Provisioner: kubernetes.io/rbd
Parameters:
  Monitors: 172.31.164.57:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: default
  Pool: rbd
  userId: admin
  userSecretName: ceph-secret-admin
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta4` UI: `v2.0.38` |
|Access|`local` `admin`|
|Route|`volumes.index`|

**Comment by tfiduccia** [comment]
Need to change adminSecret to adminSecretName

**Comment by deniseschannon** [comment]
@loganhz is this UI?

**Comment by tfiduccia** [comment]
Version - 2.0 master 5/14
Verified fixed

**Comment by dimitribellini** [comment]
Hi Rancher Team,
As from previous messages point out on Rancher 2.0.0 we have found a small bug on adminSecret but after upgrade to 2.0.1 i still was not able to configure the RBD StorageClass. The only way to debug was check the PVC of the volume to see this error:
`Failed to provision volume with StorageClass "rbd-store": failed to get admin secret from ["default"/"ceph-secret-admin"]: failed to get secret from ["default"/"ceph-secret-admin"]`
After 4 hours of crawling the web and check every kind of kubernetes doc i saw that https://kubernetes.io/docs/concepts/storage/storage-classes/
`userSecretName: The name of Ceph Secret for userId to map RBD image. It must exist in the same namespace as PVCs. This parameter is required. The provided secret must have type “kubernetes.io/rbd”, e.g. created in this way: kubectl create secret generic ceph-secret --type="kubernetes.io/rbd" \ --from-literal=key='QVFEQ1pMdFhPUnQrSmhBQUFYaERWNHJsZ3BsMmNjcDR6RFZST0E9PQ==' \ --namespace=kube-system`
The documentation say use a secret "type kubernetes.io/rbd", what is?? After configure that kind of secret option from console i was able to create the volume!
Please Rancher Team add that "Type Option" to your "Secret" WebGUI page and please put some sort of references on "StorageClass" configuration page where we could understand how is possible to configure the storage.
I know kubernetes was a mess of code and revision but I like Rancher and i think is the only way to bring a sort of order on Kubernetes enviroment :-)
Thanks very much

PS: The command above used to create the secret is still not working... so i have to used this one:
`kubectl create secret generic ceph-secret-admin --type="kubernetes.io/rbd" --from-file=/tmp/secret --namespace=default`

**Comment by dimitribellini** [comment]
Hi Team,
After solved my "secret" problem (kubernetes is able to bind the volume from ceph) i still discovered a new problem during the deploy of a workload... 
On default Ubuntu 16.04 installation the "rbd" module is not loaded  at boot, below the Kubelet log:
`W0524 08:00:21.176084    8564 rbd_util.go:770] rbd: no watchers on kubernetes-dynamic-pvc-2f042d84-5f28-11e8-9043-da6fc8eb37dd
I0524 08:00:21.176184    8564 rbd_util.go:408] rbd: map mon 10.10.11.3:6789
W0524 08:00:21.177526    8564 rbd_util.go:412] rbd: failed to load rbd kernel module:exit status 1
I0524 08:00:21.192567    8564 rbd_util.go:417] rbd: map error exit status 2, rbd output: 2018-05-24 08:00:21.184045 7fbfe165c100 -1 did not load config file, using default settings.
2018-05-24 08:00:21.187147 7fbfe165c100 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
libkmod: ERROR ../libkmod/libkmod.c:586 kmod_search_moddep: could not open moddep file '/lib/modules/4.4.0-119-generic/modules.dep.bin'
modinfo: ERROR: Module alias rbd not found.
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-119-generic/modules.dep.bin'
modprobe: FATAL: Module rbd not found in directory /lib/modules/4.4.0-119-generic
rbd: failed to load rbd kernel module (1)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail" or so.
rbd: map failed: (2) No such file or directory`

and "/etc/ceph/admin.keyring" are not deployed automatically from the kubernetes cluster (I could understand :-) ) , below Kubel log after solved the RBD module load:
`E0524 08:03:23.594313    8564 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/rbd/kube:kubernetes-dynamic-pvc-2f042d84-5f28-11e8-9043-da6fc8eb37dd\"" failed. No retries permitted until 2018-05-24 08:05:25.594275351 +0000 UTC m=+87056.903462394 (durationBeforeRetry 2m2s). Error: "MountVolume.WaitForAttach failed for volume \"pvc-2efaf0d2-5f28-11e8-9cd8-da6fc8eb37dd\" (UniqueName: \"kubernetes.io/rbd/kube:kubernetes-dynamic-pvc-2f042d84-5f28-11e8-9043-da6fc8eb37dd\") pod \"ubutest-584d85d79c-4wdbb\" (UID: \"2f2c10f7-5f28-11e8-9cd8-da6fc8eb37dd\") : rbd: map failed exit status 110, rbd output: 2018-05-24 08:02:23.566886 7fc165c20100 -1 did not load config file, using default settings.\n2018-05-24 08:02:23.570175 7fc165c20100 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory\nrbd: sysfs write failed\n2018-05-24 08:03:23.569884 7fc165c20100 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory\nIn some cases useful info is found in syslog - try \"dmesg | tail\" or so.\nrbd: map failed: (110) Connection timed out\n"`

but Ubuntu 16.04 is not compatible with Ceph Luminous (v.12.2.x) and you could see something on worker machine log:
`libceph: mon0 172.16.0.104:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000` 
link: https://silvenga.com/ceph-feature-mismatch/

My suggestion is to report this kind of incompatibility because Rancher 2.0 have supported Ubuntu 16.04 and RHEL/Centos 7.5 but i think both distro is not able to use the RBD Storage Class with the native kernel.
On Ubuntu 16.04 you could fix it with a newer kernel:
`apt install --install-recommends linux-image-generic-hwe-16.04`

**Comment by danielfree** [comment]
@dimitribellini the issue of ceph mismatch feature is not a bug with Rancher, latest ceph releases make use of some features from quite new kernel versions that are not shipped by default in common server distros like ubuntu 16.04. You can either upgrade the server kernel or install prior ceph packages. For larger deployments upgrading kernel may not be a good idea, and if you feel not to downgrade ceph, you can always change the 'turnable' parameter after your ceph cluster is up and running with this command: 

`sudo ceph osd crush tunables hammer`

I'm pretty sure this works with ubuntu 16.04 default kernel and latest ceph releases.

**Comment by dimitribellini** [comment]
@danielfree I now know what you said :-) But if Rancher 2.0 say is compatible with Ubuntu 16.04, RHEL 7.5, i think is very important to publish this kind of information on the page related to CEPH Storage implemetation inside Rancher GUI or on the Rancher Documentation.
My 2 cents
Thanks very much

**Comment by deniseschannon** [comment]
@wanshaoyuan can you re-try tis issue? it looks like we made the relevant fix for the original issue.

**Comment by loganhz** [comment]
Original issue has been fixed. 

Created a new issue for the secret with type `kubernetes.io/rbd` https://github.com/rancher/rancher/issues/13923
