### ISSUE TITLE
catalog can't create app when creating namespace in app

### ISSUE THREAD

**Issue by jianzi123** [rancher/rancher#13239]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.19.2

**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-693.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by tfiduccia** [comment]
@jianzi123 - Can you please provide more details.  Which catalog are you trying to deploy?  Does the namespace already exist?

**Comment by jianzi123** [comment]
@tfiduccia We use our catalog in local and the helm chart written by  our team, we will create new namespace in the helm chart.
when deploy the chart in rancher, it does not work in in web UI. I try to use the chart in using helm install...it works.
Our solution is use the same namespace in rancher and helm chart.  
I'm sorry for late reply .

**Comment by guangbochen** [comment]
Hi @jianzi123,  by using the Rancher Catalog's UI, you don't need to create a new namespace for your helm chart, because the Rancher UI will did that for you. you can get the namespace by using `{{  .Release.Namespace }}` in your yaml files.

If you need to specify a fixed namepace, you can define it in the `questions.yml` or `catalog.yml` using `namespace: my-namespace`. an example can be [find in here](https://github.com/rancher/charts/blob/master/proposed/istio/v1.0.0/questions.yml), thanks.

**Comment by guangbochen** [comment]
Hi @jianzi123,  by using the Rancher Catalog's UI, you don't need to create a new namespace for your helm chart, because the Rancher UI will did that for you. you can get the namespace by using `{{  .Release.Namespace }}` in your yaml files.

If you need to specify a fixed namepace, you can define it in the `questions.yml` or `catalog.yml` using `namespace: my-namespace`. an example can be [find in here](https://github.com/rancher/charts/blob/master/proposed/istio/v1.0.0/questions.yml), thanks.

**Comment by guangbochen** [comment]
closed because there has been no response.
