### ISSUE TITLE
Ability to remove/hide built-in roles

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#13279]
Currently, there is no way to remove built-in roles that users can select when inviting new members to project or clusters.  There are several ways of solving this:

1. Given an ability to disable built-in roles from being selectable.
2. Ability to delete/remove any roles, including built-in.
3. Ability to hide roles from being selectable

**Comment by deniseschannon** [comment]
This was fixed with the concept of locked roles:
https://github.com/rancher/rancher/issues/13574
https://github.com/rancher/rancher/issues/13418

Docs on how it works: 
https://rancher.com/docs/rancher/v2.x/en/concepts/global-configuration/users-permissions-roles/#locked-roles
https://rancher.com/docs/rancher/v2.x/en/tasks/global-configuration/roles/#locking-unlocking-roles
