### ISSUE TITLE
ca-checksum validation fails if certificate does not have a trailing newline

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13308]
**Rancher versions:**
rancher/rancher: v2.0.0

When computing `--ca-checksum`, we add a `\n` (as required in a certificate). If the given certificate (mounted as `cacerts.pem` or edited in the API) does not have a newline, the function that calculatest the checksum adds a newline (https://github.com/rancher/rancher/blob/master/pkg/systemtemplate/import.go#L50) which makes the validation fail if the agent retrieves the certificate from settings and validates it with the given checksum.

**Comment by galal-hussein** [comment]
@superseb I can't reproduce this issue at all, the agent also adds a new line when it pulls the certificate from the settings using curl and jq.
I only reproduced the problem when rancher agent couldn't reach the settings and curl returns back an empty file, and its checksum doesn't match the server's

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/19

I have not been able to reproduce this.

**Comment by nlowe** [comment]
I ran into this yesterday. I generated the CA list on a windows machine so the file had `\r\n` instead of `\n` for line endings. Rancher calculated the checksum one way. However, when it served the CA file to the client, the line endings were normalized to `\n`, thus the different hash. I'm not certain if this warrants a new issue or if it's similar enough to this one to re-open.
