### ISSUE TITLE
containers being listed twice on the hosts view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1339]
Server version - v0.25.0-rc2

I see all the containers in one of my host being listed twice in the UI. This issue is seen only in 1 of the 3 hosts in my set up.

Database has only 1 entry:

mysql> select id,name,state from instance where name like "%test-141399%";
+------+-------------+---------+
| id   | name        | state   |
+------+-------------+---------+
| 2851 | test-141399 | running |
+------+-------------+---------+
1 row in set (0.01 sec)

mysql> 

![screen shot 2015-06-25 at 9 49 07 pm](https://cloud.githubusercontent.com/assets/4266958/8371014/93671c52-1b85-11e5-91f4-e597eaa06014.png)

**Comment by sangeethah** [comment]
Also I don't see Network agent being listed in the host , but Network agent container is running.

**Comment by vincent99** [comment]
This was due to having more than 100 of them and hitting pagination, which is depaginating wrong.  The UI now loads pages of 1000, which totally solves the problem once and for all. (Proper fix in https://github.com/rancher/rancher/issues/1606)

![image](https://cloud.githubusercontent.com/assets/753917/8821517/17733642-3013-11e5-800c-0e78f1cc1aa4.png)

**Comment by sangeethah** [comment]
Tested with sever version - v0.29.0-rc1.
Able to list > 100 containers in a 1 host in the hosts list view without any duplication.
