### ISSUE TITLE
Healthcheck changes

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#13398]
* Drop healthcheck events only when ipsec service is going through upgrading process (there are several service states qualifying for `upgrading`)
* Only drop down events; never drop UP/UP1/2 (check for all possible events in the `service_event` table
* Fix initializing/reinitializing instances cleanup thread to ignore instances of the services having healthcheck strategy Noop
* Always assign one of the healthcheckers to the host where application is getting deployed. Today we try to place them all on diff hosts. This change would be easy code wise, but would probably require changing some amount of integration/validation tests :)

**Comment by sangeethah** [comment]
Tested with v1.6.18-rc1 and rancher/healthcheck:v0.3.6

Always assign one of the healthcheckers to the host where application is getting deployed. Today we try to place them all on diff hosts:

1. Environment with 3 hosts (h1,h2,h3)
2. Deploy health check enabled instance. — All 3 hosts monitor health check for this instance
3. Add 3 more hosts (h4,h5,h6)
4. Deactivate hosts (h1,h2,h3)
5. Make instance unhealthy and  so that the instance gets moved to h4/h5/h6.
6. When instances get recreated in one of the new set of hosts , they have host h4,h5,h6 monitoting its health.
7. Activate all the deactivated hosts.
8. Deploy global health check enabled services.
9. All the service instances have their health monitored by the host that they are in and 2 other hosts in the setup as expected.

10. Power off one of the monitoring hosts. This results in a new host being picked up for health monitoring. Health check enabled instance continue to remain healthy and are not getting recreated.  
11. Power off both hosts that are monitoring hosts. This results in a 2 new hosts being picked up for health monitoring.Health check enabled instance continue to remain healthy and are not getting recreated.  
12. Power off  hosts where health check enabled instance is running. Once the host gets to "reconnecting" state , Health check enabled instances get recreated in different host successfully.
13. Power off  hosts where health check enabled instance is running and another host that is monitoring its health.Once the host on which the container is running gets to "reconnecting" state , Health check enabled instances get recreated in different host successfully.
14.Power off  hosts where health check enabled instance is running and 2 other hosts that montior health for this instance. Once the host on which the container is running gets to "reconnecting" state , Health check enabled instances get recreated in different host successfully.

**Comment by sangeethah** [comment]
Drop healthcheck events only when ipsec service is going through upgrading process (there are several service states qualifying for upgrading)
Only drop down events; never drop UP/UP1/2 (check for all possible events in the service_event table)

Tested with v1.6.18-rc1 and rancher/healthcheck:v0.3.6

1. When ipsec service was stopped , there were no "403 Conflict Errors" seen. We see "DOWN" events being reported for health check instances from the other hosts that monitor it(other than the one it is hosted in). But this does not result in health check instances to get recreated since we have "UP" from the host that it is deployed in.

2. Fresh install v1.6.17 and have some health check enabled  instances .
Upgrade to v1.6.18-rc1.
Upgrade ipsec stack.

When upgrade is in progress , user health check instances do not get recreated.  There are "403 Conflict Errors" seen for "DOWN" events in health check containers during this time.

3. On upgraded setup: 
1. Add few more hosts .
When new hosts were added , existing health check instances do not get recreated.

2. When ipsec service was stopped , there were no "403 Conflict Errors" seen. This results in all the health check instances to get recreated since there are "DOWN" events reported from all the hosts that are monitoring it. Since these are health check instances created from previous release , local host does not monitor health of the services in this case. Once health check instances are recreated with local host being one of the host monitoring their health.

3. Stop ipsec service again. This time health check instances do not  get recreated since we local host will always report them as being healthy even when ipsec is not functional.

**Comment by sangeethah** [comment]
Fix initializing/reinitializing instances cleanup thread to ignore instances of the services having healthcheck strategy Noop
Tested with v1.6.18-rc1 and rancher/healthcheck:v0.3.6:

Create a health check service with healthcheck strategy set to Noop by providing incorrect health check url . This results in the container being stuck in "Initializing" state forever. The container does not get recreated in this case.

When this same use case was tested in  v1.6.17 , the container keeps getting deleted and recreated.

**Comment by sangeethah** [comment]
@kinarashah  When I tested the use case of  adding few more hosts to an upgraded setup, I did not see any health check enabled instances getting recreated. ipsec containers in this case also did get reported  as being unhealthy.

**Comment by sangeethah** [comment]
There is 1 issue seen where existing  ipsec containers get marked as "unhealthy" even though i dont see them getting recreated when large number of hosts get added to an existing environment. This issue is tracked in - https://github.com/rancher/rancher/issues/13548.
