### ISSUE TITLE
Unable to start multiple Containers on one Host

### ISSUE THREAD

**Issue by screwgoth** [rancher/rancher#1341]
I have added only one Host, which is a AWS EC2 instance.
Am successfully able to start any one container on it (Jenkins and MySQL official repos work)
However, if I start one more container on it, the container seems to be stuck in "Starting" / "Networking" state

**Comment by deniseschannon** [comment]
Can you provide me the following information?

* Rancher Version
* Docker Version

Do you see the Network Agent on the host besides the container that you started? If so, could you get the logs of the network agent? This might be really big. If you launched the AWS EC2 instance using Rancher, here's the details on how to get into your machine.

http://rancher.docs.rancher.com/docs/infrastructure/hosts/#host-access-for-hosts-created-by-rancher

**Comment by screwgoth** [comment]
From the WebUI : 
Rancher : v0.24.0
Cattle : v0.56.0
User Interface : v0.28.0

Docker version : 1.6.2, build cec9cd8 (This is a RancherOS EC2 node)

Some more details : 
- I did not start my EC2 host by selecting Amazon in "Add Host" (because at that time I did not have the AWS secret key). Rather, I selected "Custom" for "Add Host" then ssh'd into my EC2 instance running RancherOS and then ran the docker command to register the host.
- The EC2 instance is a basic t2.micro 

- Yes, I see Network Agent on the host as soon as I start the first host.

- Yes, I think this is pretty huge and I'll give you another reason why : I'm not able to shutdown or delete (and definitely not purge) a Network Agent and MySQL containers. I tried to collect some logs using "docker logs" but I see nothing. 
Is there any way to forcefully shut these down ? 
- The way I see it , I can deactivate the host and then manually cleanup everything on my instance. OR
- Shutdown Rancher Server host and start from scratch

**Comment by deniseschannon** [comment]
Just clarifying based on your last comment, is Rancher server on the same EC2 instance as your host? If it's the same, can you confirm that the the IP of the host was picked up correctly? When adding hosts on the same machine as the server, you need to pass in `-e CATTLE_AGENT_IP=<server_IP>'. Otherwise, it might pick up the docker IP. http://rancher.docs.rancher.com/docs/infrastructure/hosts/custom/#samehost

What ports are open for your security group for your instance? Are you making any network changes to the container? 

What version of RancherOS are you using?

I haven't been able to reproduce. I am using Rancher v0.25.0-rc2 with RancherOS v0.3.1 AMI. I added the EC2 instance using the custom command (like you). The only difference could be that I have my host on a separate machine, but that shouldn't affect it.

I am able to successfully add 2 mysql containers and delete them.

**Comment by screwgoth** [comment]
I'm using RancherOS v0.3.1 and I started it by starting the AWS ami : ami-818668ea
And No, my Rancher server and Host are not the same.
Were you able to start a MySQL and another container like say, Wordpress successfully up and running at the same time.
I will try this once more from scratch, also try starting 2 MySQL containers.

**Comment by deniseschannon** [comment]
Could you also try upgrading Rancher server to v0.25.0? This is the new latest.

**Comment by deniseschannon** [comment]
@screwgoth Have you been able to reproduce this with the latest Rancher (v0.25.0) and latest RancherOS (v0.3.3)? Unfortunately, I was never able to reproduce, but if you were still having issues, I want to try and help.

**Comment by deniseschannon** [comment]
@screwgoth If this issues comes up again, please re-open.
