### ISSUE TITLE
Adding new node to cluster keeps getting stuck in Registering with "Waiting to register with Kubernetes" message

### ISSUE THREAD

**Issue by MihaiASSECO** [rancher/rancher#13433]
**Rancher versions:**
rancher/server or rancher/rancher: v1.10.1
rancher/agent or rancher/rancher-agent: v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 454
 Running: 24
 Paused: 0
 Stopped: 430
Images: 24
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639GiB
Name: puppet
ID: OM7W:2674:FV4L:JNCB:A6BP:BFNM:6MDM:4SFA:EQPX:NBNO:DLW7:WMXM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mihai97
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS7 3.10.0-693.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB

**Steps to Reproduce:**
Current Rancher cluster configuration:
1 VMWare VM that also has the rancher server installed on it.
Tried adding to the cluster a second VM that has the same OS and docker version installed on it. The jobs keeps getting stuck in Registering status with the following message: "Waiting to register with Kubernetes". Tried rebooting the second VM and I still get the same issue.
**Results:**
Cannot add VM to the cluster, keep getting the message "Waiting to register with Kubernetes"

**Comment by MihaiASSECO** [comment]
Tried allowing 500 & 4500 udp ports and it finally worked but not instantly, it waited about 1-2 minutes in the "Waiting to register with Kubernetes" state. This seems to be an issue with custom hosts.

**Comment by admiralspark** [comment]
Hello. 

I'm running into the same issue, I didn't bother with any of these fixes mentioned here. Custom nodes, one Node with all functions and adding a second Node with worker only gets stuck in Registering.

If you parse through the API, you'll find that the cluster information doesn't populate properly if you have a single etcd server and you add a second node with the "worker" role only. This is likely because the worker-only provisioning doesn't properly apply "some" setting, which I didn't bother to figure out because...

A reboot of the Node while it is stuck Registering brings up the services correctly and will properly register the Node at that time. 

I did notice that if you add etcd functionality to the second node, it immediately joins and modifies the cluster. The scenario of the first node running everything, and the second node being added as only a worker node is the only way I can reproduce this, but it is consistent. This is for future people landing here from google.
