### ISSUE TITLE
Is there a way to disable rancher2.0 network policy management 

### ISSUE THREAD

**Issue by luzhongming** [rancher/rancher#13462]
Rancher version：2.0
-----------------------------------
Is there a way to disable rancher2.0 network policy management ? 
We have a k8s cluster to be imported but we dont want rancher2.0 create network policy in our cluster,which would make exist policies not working because of the loose rules

**Comment by leodotcloud** [comment]
Since you already are using network policies, it means you have a controller for the policies. So the policies programmed by Rancher would be in effect. These rules are necessary to make sure Project isolation is enforced. I don't think there is a toggle available ATM.

Also can you please elaborate: `because of the loose rules`?

**Comment by cloudnautique** [comment]
@luzhongming in Rancher v2.0.7 this is now a configurable option.

**Comment by mvisonneau** [comment]
@cloudnautique thanks for the info. I'm struggling to find documentation around this configurable option. Do you know what it is or where to find it ?

**Comment by cloudnautique** [comment]
it is under cluster options on edit/create cluster in the Rancher 2 UI.
