### ISSUE TITLE
Workload was created on the non-worker node when scaling.

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/rancher#13524]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2 ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos7.2
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
virtual machine
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
rke - k8s 1.10.1

**Steps to Reproduce:**
1. Create a custome cluster with worker and etcd+control node seperated.
![image](https://user-images.githubusercontent.com/23303886/40101010-9c99c166-5918-11e8-9887-316e181c8b75.png)

2. Deploy a deploment such as this
![image](https://user-images.githubusercontent.com/23303886/40101090-e0f763c2-5918-11e8-8166-f7f51cdead03.png)

3. Scale the wordload. You can find that the new instances were created on the etcd+control node. 
![image](https://user-images.githubusercontent.com/23303886/40101259-796d5c06-5919-11e8-8512-1fcf9f07a6e3.png)

**Comment by tfiduccia** [comment]
Currently we allow pods to be placed on nodes that have the control plane on them.  But we should fix this.  And only deploy pods on worker nodes (according to Darren).  So marking this as a bug we should fix.

**Comment by sangeethah** [comment]
Tested with latest build from master.
User pods get created only on worker nodes. user pods will not be deployed on Control nodes anymore.

**Comment by Itiho** [comment]
I get error: 

[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.0.152.117]: Get https://localhost:6443/healthz: can not build dialer to c-4bjtg:m-6srg6, log: I0623 18:51:20.218200 1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.

![captura de tela de 2018-06-23 14-54-00](https://user-images.githubusercontent.com/7440821/41812685-4a7722ca-76f5-11e8-8228-c9ad6bb130be.png)

**Comment by Itiho** [comment]
nginx-ingress-controller no start in Unschedulable node

**Comment by Itiho** [comment]
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

[network] Port check for ports: [10.0.152.183:2379] failed on host: [10.0.152.117]; exit status 1, W0623 21:32:52.357410 13614 factory_object_mapping.go:423] Failed to download OpenAPI (an error on the server ("Error: 'x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")'\nTrying to reach: 'https://10.0.152.117:6443/swagger-2.0.0.pb-v1'") has prevented the request from succeeding), falling back to swagger Error from server (InternalError): an error on the server ("Error: 'x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")'\nTrying to reach: 'https://10.0.152.117:6443/api'") has prevented the request

**Comment by nlowe** [comment]
Does this get fixed for existing clusters? Or will this only apply to clusters created in 2.0.3+? I updated and still don't see the taints / tolerations applied to my nodes or services after about 5 minutes.

**Comment by nlowe** [comment]
Updating the cluster to `1.10.3-rancher2-1` seems to have triggerd the taint / tolerations update. Is there a way to kick this off without doing an upgrade?

**Comment by nlowe** [comment]
I'm pretty sure `cattle-agent` needs the toleration for these. My cluster got stuck in a crash backoff until I fixed the deployment to tolerate the new taints added to the masters after the upgrade.

**Comment by Itiho** [comment]
@nlowe how can you do fixed the cluster. In new cluster 1.10.3 works but in old cluster (Edit-->change to 1.10.3 kubernetes version)  crash
