### ISSUE TITLE
Support encryption on overlay networking

### ISSUE THREAD

**Issue by stephen-dahl** [rancher/rancher#13536]
Requesting encrypted networking support in 2.0.

Options:
optional ipsec backend for flannel
https://github.com/coreos/flannel/blob/master/Documentation/backends.md#ipsec
add support for weave-net
https://www.weave.works/oss/net/

**Comment by superseb** [comment]
ipsec backend for flannel is still experimental: https://github.com/coreos/flannel/issues/6

@leodotcloud will have an answer on the direction for this.

**Comment by leodotcloud** [comment]
It's on my TODO list.

**Comment by hiscal2015** [comment]
@superseb @leodotcloud 

Since there's already pull request for weave network encryption:
https://github.com/rancher/rke/pull/781
Can you just integrate weave network to Rancher 2.0 at earlier?
We're running Rancher1.x on production, and Rancher 1.x has builtin ipsec mode on network, the network encryption feature is now the only one reason to stop us moving to Rancher 2.x. Thanks.

https://github.com/rancher/rancher/issues/15194
https://github.com/rancher/rancher/issues/12909

**Comment by phlegx** [comment]
I'd still vote to have it very soon in flannel/calico ;-)

**Comment by deniseschannon** [comment]
The option we would use will be to add in the ability to use weave in Rancher 2.0, which is this issue: https://github.com/rancher/rancher/issues/12909
