### ISSUE TITLE
UI displays a different rule option while editing ingress

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13572]
**Rancher versions:**
rancher/rancher: v2.0.1-rc2

Case 1:

1. Create a workload wk1
2. Create an ingress with rule ```Automatically generate a .xip.io hostname``` pointing to workload "wk1"
3. Verify the ingress. 
4. Edit the ingress and point to a different workload
In the edit screen, UI points to the option ```Specify a hostname to use```.

Case 2:
1. Create a workload wk1
2. Create an ingress with rule ```Specify a hostname to use``` pointing to workload "wk1"
3. Verify the ingress. 
4. Edit the ingress and point to a different workload
In the edit screen, UI points to the option ```Automatically generate a .xip.io hostname```.

If the user does not pay attention that the UI is pointing to a different rule, the edited ingress may not function correctly[It will point to pods of the old and new and old workloads]

**Comment by loganhz** [comment]
For case 1, I guess we need to add some filed in backend to let frontend know if it is auto generated.

As a user, I might want to `specify a hostname to use` such as `lb.192.168.1.100.xip.io`.
It doesn't make sense if we reset it to `Automatically generate a .xip.io hostname` in edit view.

@vincent99 Can I set it to `Automatically generate a .xip.io hostname`, if the host ends with `.xip.io` ?

**Comment by vincent99** [comment]
The basic behavior here is correct; you asked for us to generate a name, we did, and on subsequent a subsequent that is now just what the name is.  We don't know or particularly care if we previously generated it.  So it is shown and selected as "specify a hostname to use".  You need to know what it is to use it, and it shouldn't automatically change just because you changed the target (case 2).

To make this a little more clear, on edit there could be a new first option of "Keep the existing hostname: <x.a.b.c.d.xip.io or whatever-they-typed.com>`.

And on edit, "Automatically generate a xip.io name" (which is going to set the value to `xip.io` and then the server will update it) is not normally very useful (because it will pick the same name), so it could be eliminated if the current value ends in xip.io.  (But that does make it impossible to update it for your case 2 without just typing the new name).

**Comment by soumyalj** [comment]
Tested with master. For both the cases mentioned in the issue above, UI points to the correct option in edit screen. 
Example below:
<img width="1443" alt="screen shot 2018-06-07 at 10 43 41 am" src="https://user-images.githubusercontent.com/18536626/41116611-b29b9c40-6a3f-11e8-8526-1fae3a56b82b.png">

<img width="1370" alt="screen shot 2018-06-07 at 10 45 48 am" src="https://user-images.githubusercontent.com/18536626/41116722-f3d43730-6a3f-11e8-98eb-9aee5b1a7271.png">
