### ISSUE TITLE
Editing port mapping on rancher container does nothing

### ISSUE THREAD

**Issue by moimael** [rancher/rancher#1358]
HI,

When I edit the port mapping on the container running rancher UI (rancher/server), the modification is accepted and displayed in the UI, but the container still has the old port mapping.

**Comment by deniseschannon** [comment]
We are unable to reproduce the issue. Can you provide the following information?
Rancher Version (click on the cow in the top left corner) 
Docker Version

When you launched the container, did you change the network settings? What is the IP of the container? If it's 10.42.x.x, then it's within the managed network.

**Comment by vincent99** [comment]
One thing to note is that the mapping is done in iptables on the host;  `docker ps` will not update to reflect the currently mapped port.

**Comment by moimael** [comment]
Ok maybe that is the issue, I will do some test today to confirm. But it's a bit confusing, there is no way to update what docker ps return ?

**Comment by deniseschannon** [comment]
@moimael Were you able to do some tests? Docker doesn't allow editing ports after creation, which is why the `docker ps` would not show the new ports. Since mapping is done on the iptables on the host, it allows Rancher to edit ports on a container in a running state.

If you are still having issues, please re-open.
