### ISSUE TITLE
SSL: add rancher generated CA cert and key as k8s secret.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#13619]
Rancher generating self signed certs is a boon to testing on local installs and in large organizations that require ssl, but have long process to request internal CA signed certificates. 

Adding the cert chain and key as a k8s secret in the namespace that rancher server is launched in would eliminate the need to enable ssl passthrough on the ingress. Reducing the special config and documentation needed to support it.

**Rancher versions:**
rancher/rancher: v2.0.0

**Comment by jgreat** [comment]
Please name the secret "tls-rancher".  This will match up with the helm chart I'm developing.

**Comment by alena1108** [comment]
The request of this bug was for the self signed server certificate to be put as a k8s secret. The original fix put self signed **CA** cert as a secret, which didn't address the issue as the CA is used for validating server cert, but it's not a server cert by itself. As Rancher generates self signed certificate on demand - on every user request - it is not feasible to put server cert to the secret. @jgreat is looking at other options to make setting up Rancher HA with self signed cert model, easier.

**Comment by will-chan** [comment]
@jgreat let Alena know what you'd need instead.

**Comment by jgreat** [comment]
Publishing the CA cert and key as a secret is just fine.  We can use cert-manager to generate certificates for the ingress with that cert and key.

So the changes in #13854 are fine.

**Comment by alena1108** [comment]
@jgreat are you working on the doc explaining how to use cert-manager to generate certificate, and how to integrate it to rancher ha setup scripts/configs?

**Comment by jgreat** [comment]
Tested issuing certs with cert-manager using the Rancher generated CA in the K8s secret. Also tested other SSL methods (LetEncrypt, BYO Cert).

Testing instructions here: https://gist.github.com/jgreat/70b15d82448a7e6e7540d4d37f286e23
