### ISSUE TITLE
[Questions] User who sets up Authentication behavior

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#13684]
Rancher/rancher:v2.0.2

After enabling AD/Github, the user used to sign in becomes an admin and becomes the logged in user?

This user does not show up in the global users list, is this the expected behavior?
It is the current observed behavior.

When using the "default admin" user after authentication is turned on, it only searches principles provider for local?
Observed this behavior, want to confirm. This user can not be used to add AD or GH users to the system any longer.

cc @lopf

**Comment by cjellick** [comment]
> After enabling AD/Github, the user used to sign in becomes an admin and becomes the logged in user?
We attach the github/ad id of the user who turned on auth to the existing Default Admin user. So, GitHub/AD credential that turned on auth _is_ the Default Admin user.  This is intentional, but we just yesterday realized it was too confusing. So, we are going to change it such that when a user turns on auth, it creates a new user for that AD/Github credential, makes them an admin, and switches the current UI session to that newly created suer.
 
> This user does not show up in the global users list, is this the expected behavior?
See above. You don't see a new user for them because their github identity has been attached to the Default Admin user. As above, this will change to having an explicit new user created.

> When using the "default admin" user after authentication is turned on, it only searches principles provider for local? Observed this behavior, want to confirm. This user can not be used to add AD or GH users to the system any longer.
The current implementation limits searching to the auth provider you logged in with + local. So, if you log in with github, you will see github and local users. If you login with local, you will only see local users. This is because, basically, a credential (in github's case an access token, in AD's case, a username and password) is needed to perform these searches. However, we discussed this yesterday as well and we are going to change this behavior to be a "best effort" to search all providers. So, when we make this change, if you've enabled github and later have logged in as local, as long as we still have a non-expired access token from github for you, we will search github. For AD, we will just use the service account credentials we already have for all providers.

It's a nice coincidence that you opened an issue that covered many of the enhancements we discussed yesterday. I'm going to use this issue as a placeholder/tracker for them until I need to split them out into more specific issues.

**Comment by vincent99** [comment]
> After enabling AD/Github, the user used to sign in becomes an admin and becomes the logged in user?

The Rancher user who is signed in was already an admin (because they can write auth config).  The external auth account they used to test the config (Github or AD principal ID) is then associated with their current Rancher user (which is often the "Default Admin", but not necessarily).  In accordance with the law of conservation of users, no new users are created or destroyed during access control configuration in <= 2.0.2.

We discussed a future release having an _option_ presented to the user for whether to:
  - Add the principal of the tested external account to the current Rancher User, or
  - Create a new Rancher user with admin rolebinding for the tested external account principal

I still think the former is what most people would want and should do, but the option at least makes it more clear what is happening and then you can have a choice.  The latter is going to have new and exciting edge cases to handle (e.g. what if there's already a Rancher user using that principal ID?)

**Comment by cjellick** [comment]
Thanks for the elaboration and clarification @vincent99

**Comment by deniseschannon** [comment]
We've added this information into documentation..

https://rancher.com/docs/rancher/v2.x/en/concepts/global-configuration/authentication/
