### ISSUE TITLE
Make clusters reachable without master

### ISSUE THREAD

**Issue by gwiersma** [rancher/rancher#13698]
When the rancher2.0 master goes down for some reason, is there a way to reach the kubernetes cluster directly with kubectl? I am currently running a project and one of the requirements is when the rancher master goes down , all the kubernetes clusters can be managed separately. If something happens to the Rancher master how can i manage my environments? 

I have tested this situation and i changed the ip from the master to one of the worker nodes in the kube configs. When i execute a command i get the message  Unable to connect to the server: x509: cannot validate certificate for <IP> because it doesn't contain any IP SANs

**Comment by cloudnautique** [comment]
The clusters will not be accessible via the Kubeconfigs generated by Rancher. The files generated by Rancher are proxied through the Rancher server. 

You can still use the kube configs that were generated by the provisioning process that talk directly to the Kubernetes API servers in the remote clusters. Rancher 2.0 UI doesn't export those yet, but they do exist and work without Rancher server being operational.

**Comment by gwiersma** [comment]
@cloudnautique Thank you. Can i retrieve these files somewhere for a provisioned cluster? If so, where can i find them?

**Comment by bmdepesa** [comment]
Exec into your rancher container and execute:

```kubectl get secret c-<YOUR_CLUSTER_ID> -n cattle-system -o yaml```

This will return a base64 encoded value for `cluster`. Decode this value and execute `jq .metadata.state` on the decoded output, for example:

```cat decoded_output.txt | jq .metadata.state```

This will return the kubeconfig, but it will need to hand edited to the correct format with whitespaces.

**Comment by will-chan** [comment]
As @cloudnautique pointed out, Rancher is the central auth point for all kube access.  We are looking to push a temporarily auth tokens down to each individual k8s cluster so that access will not be disrupted unless those tokens expire.  We expect this to be in post 2.0.3 as it is a larger enhancement.  However, once this has been completed, you will be able to access the k8s cluster even if Rancher server is down unless the token has expired and needs to be refreshed again through Rancher.

**Comment by etlweather** [comment]
@will-chan That sounds good to me!

**Comment by superseb** [comment]
This script is also used for the Gitlab Auto-Devops blog, to retrieve the kubeconfig: https://gist.github.com/superseb/f6cd637a7ad556124132ca39961789a4

**Comment by cjellick** [comment]
related: https://github.com/rancher/rancher/issues/13474

**Comment by bmdepesa** [comment]
rancher/rancher:master 

First pass of testing is completed.

**Comment by pwilken** [comment]
Now you just have to change the current-context at the end of your kubeconfig file for reaching the k8s API directly.

**Comment by ellerydb** [comment]
> Now you just have to change the current-context at the end of your kubeconfig file for reaching the k8s API directly.

How exactly is that?

**Comment by mjschmidt** [comment]
@pwilken is there a doc anywhere with an example? If not could you copy paste two example kubeconfigs so I could see what you are changing. This is great!

**Comment by mjschmidt** [comment]
All, scratch that. You must provision a new kubernetes cluster with rancher version 2.2.7+ to get a kubeconfig file with multiple contexts in it.

Hope this helps

**Comment by vitobotta** [comment]
Hi, I have deployed a cluster with 2.3.1 using the UI and the kubeconfig has only one context that connects through Rancher with a token. How can I connect directly to the cluster? I am trying something that doesn't seem to work properly and I think it's because everything is being proxied through Rancher. Thanks
