### ISSUE TITLE
gcr.io images in Catalog of Library 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13716]
rancher/rancher:v2.0.0

China users can not access `gcr.io` images. Can we move the images to docker hub and not use `gcr.io` images in catalog

**Comment by deniseschannon** [comment]
I don't think we should plan on moving all the images used in the library catalog to docker hub. But we should make it so that you can pull the images from dockerhub instead of gcr. 

@guangbochen is that possible to update charts so that there is a configurable field for the repo that pulls the images? 

Note: This would only occur for our helm charts that we maintain. We have no control over helm stable/helm incubator charts.

**Comment by guangbochen** [comment]
yes, the user can already modify the default image, and @loganhz for some `gcr.io` images user can find a replacement in the `dockehub.io` or `quay.io`, but they are not maintained by the official distributor, so I prefer to leave the default.
![image](https://user-images.githubusercontent.com/4569037/40570615-20dace4a-60bf-11e8-9bf0-c3ac010aadca.png)
