### ISSUE TITLE
NodePort are automatically added to worklaods if there is a ingress points to it

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13717]
rancher/rancher:v2.0.0

Steps to reproduce.

1. Create a RKE cluster.
2. Deploy a workload without any port mapping
3. Deploy a ingress points to this worklaod

Results:

A node port are added to the workloads public endpoints.

**Comment by alena1108** [comment]
@loganhz this is by design. For ingress with workload targets we automatically create the service as k8s object doesn't understand the workload. And this service has to be the NodePort to satisfy all cloud providers (GKE for example requires ports to be published on the node, for the service to be registered with built in GKE ingress).

**Comment by alena1108** [comment]
Closing as by design.

**Comment by truongdo** [comment]
Let’s say we have an application need to be protected using nginx ingress basic authentication, adding NortPort make it meaningless because people can scan open ports and access the service directly without authentication. Is there anyway to handle this case?

**Comment by Leen15** [comment]
This cannot be closed for a "by design" reason.
if we have load balancer, we should use them!
Generate a random port for every workload is a big security issue and also if you have a website to a specific domain it should be accessible ONLY with that domain and not with the IP or with another domain + random port. 
This also generate lots of issues with google indexing if it finds that the same site exists with a domain and with an IP.

**Comment by alena1108** [comment]
We can limit it to only GKE when opening node port on the service is a requirement for it to be placed behind the ingress (`It needs a service with a node port to use as the default backend. This is the backend that's used when an Ingress does not specify the default.` https://github.com/kubernetes/ingress-gce#l7-load-balancing-on-kubernetes). 

RKE clusters should get cluster ip service instead, where port is not exposed.

**Comment by alena1108** [comment]
@orangedeng we should also handle the upgrade use case in the code, and make sure that nodePort services on non GKE clusters get recreated as ClusterIP ones

**Comment by Leen15** [comment]
Absolutely yes, thanks Alena.

**Comment by alena1108** [comment]
@sangeethah besides testing the basic functionality, lets also hit the upgrade scenario. Services behind ingresses on RKE clusters, should have their services translated to ClusterIP. Please refer to @orangedeng for more info

**Comment by galal-hussein** [comment]
rancher/rancher:master july 23rd

i tested creating ingress in RKE cluster and the service backend was ClusterIP type

Also i tested creating ingress in gke cluster but the service didin't get created with NodePort type, here are my steps:

- create a GKE cluster
- create a workload
- create an ingress that points to this workload

i don't see external ip gets assigned for the ingress, and i can see service gets created with ClusterIP type:
```
kubectl get services
NAME                                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
ingress-e8b66cf4195d914109ecb7195ee7eadb   ClusterIP   10.3.243.176   <none>        80/TCP           36s

```

**Comment by galal-hussein** [comment]
any change to the ingress properties and saving it resulted in changing the service from nodePort to clusterip.
