### ISSUE TITLE
Issue  a BUG

### ISSUE THREAD

**Issue by lanhao-tik** [rancher/rancher#13737]
Missing PORT while confirm upgrade
<img width="810" alt="wx20180526-180455 2x" src="https://user-images.githubusercontent.com/38715690/40575012-9d16434a-610f-11e8-837b-362c8db7b66a.png">

**Comment by vincent99** [comment]
The API returns absolute URLs and the server needs to have enough information from the request it receives in order to produce the right URLs.  The UI just follows them.

If you have a proxy or SSL termination in front of it, this means passing along PROXY protocol or the appropriate X-Forwarded- headers.
