### ISSUE TITLE
Rancher network manager is killing TCP connections

### ISSUE THREAD

**Issue by papaiatis** [rancher/rancher#13794]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.16
cattle: v0.183.46
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.2.3
network-services: 0.2.9
scheduler: 0.8.3-1
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 56
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:6-134333255-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/cl/docker-data
 Metadata file: /dev/cl/docker-meta
 Data Space Used: 38.13GB
 Data Space Total: 161.1GB
 Data Space Available: 122.9GB
 Metadata Space Used: 62.94MB
 Metadata Space Total: 17.05GB
 Metadata Space Available: 16.98GB
 Thin Pool Minimum Free Space: 16.11GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 94.15GiB
Name: samu
ID: FT7P:GS2J:EOQG:7DE4:WB5Z:HSR3:AOUS:UD4Y:PCHJ:7RP2:WVWS:4KIO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: 
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-514.26.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
I have three production containers. They all have their static IP addresses (10.224.138.187/188/189).
After I registered this docker host on our Rancher system we faced a lot of network issues with our containers. After investigation we found that TCP connections between the clients and these containers were killed by rancher/network-manager.
See the logs below.

For example, I monitored TIME_WAIT connections for one of the containers like this:
`watch -n 1 'grep TIME_WAIT /proc/net/nf_conntrack | grep 10.224.138.189`
About every 3-5 seconds, all these connections got killed and the list above gets cleared

**Results:**
[rancher-network-manager.txt](https://github.com/rancher/rancher/files/2058407/rancher-network-manager.txt)

**Comment by papaiatis** [comment]
```
iptables -L

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
CATTLE_NETWORK_POLICY  all  --  10.42.0.0/16         10.42.0.0/16        
CATTLE_FORWARD  all  --  anywhere             anywhere            
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain CATTLE_FORWARD (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             mark match 0x1068
ACCEPT     all  --  anywhere             anywhere             mark match 0x4000
ACCEPT     all  --  anywhere             10.42.0.0/16        

Chain CATTLE_NETWORK_POLICY (1 references)
target     prot opt source               destination         

Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8008
ACCEPT     tcp  --  anywhere             172.17.0.3           tcp dpt:distinct32
ACCEPT     tcp  --  anywhere             172.17.0.4           tcp dpt:distinct32
ACCEPT     tcp  --  anywhere             172.18.0.2           tcp dpt:commplex-main
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:https
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:http

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere   
```

excerpt from `ip addr`

```
8: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 18:66:da:af:b7:83 brd ff:ff:ff:ff:ff:ff
    inet 10.224.138.32/24 brd 10.224.138.255 scope global dynamic bond0
       valid_lft 26110sec preferred_lft 26110sec
    inet 10.224.138.190/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet 10.224.138.189/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet 10.224.138.188/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet 10.224.138.187/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 fe80::1a66:daff:feaf:b783/64 scope link 
       valid_lft forever preferred_lft forever
9: docker0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:0e:c0:cd:9e brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet 10.42.0.1/16 brd 10.42.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:eff:fec0:cd9e/64 scope link 
       valid_lft forever preferred_lft foreve
```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by papaiatis** [comment]
@loganhz please leave this open as I'm still facing this issue and we're not in a position to upgrade to Rancher 2 yet.

**Comment by loganhz** [comment]
@papaiatis sure
Added to the to-do list. We will find someone to look at it.
Thanks!

**Comment by billinghamj** [comment]
This does seem like a pretty critical bug I think?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.x, development on v1.6 is limited.

**Comment by jevgenijs** [comment]
Guys are you actually serious? It's a very **critical issue,** this makes rancher 1.6.x **completely unusable** for any prod environment. Migrating to 2.x is both difficult and time consuming if you have a lot of services across multiple environments. And judging by how this thread was handled, there is no guarantee that a similar situation wouldn't happen with 2.x -> 3.x transition, as the devs seem to be fine with just sweeping the issue under the rug. Building a large infrastructure around rancher seems too risky in the long term with this dev team attitude. Why do you even still allow people to download and use 1.6 if it's fundamentally broken?   @loganhz @deniseschannon

**Comment by vincent99** [comment]
We have thousands of community users  and paying customers doing just fine with their 1.x production clusters.

Your hyperbole does not accomplish anything, especially when you are telling us nothing about what's actually broken ("a lot of network issues" tells me nothing).

"Connections" in TIME_WAIT are not _connections_ anymore.  It means the connection has already been closed (by "this side"), and they are kept track of so that no other connection can use the same {src IP, src port, dst IP, dst port} tuple for a while.  This prevents what is supposed to be a new connection from receiving a stray late retransmitted packet (which happens to also have an appropriate sequence number) from a previous connection.

In rancher, containers are behind an overlay network and if you put a service behind a load balancer then three out of those four parameters are fixed (or nearly so).  That leaves only the source port (and maybe a few target IPs) varying per connection.  At the defaults you could only handle ~30000 connections (size of the typical ephemeral port range) in ~5 minutes before you are out of available slots and rejecting new connections, which is not much.

Reducing that window is a very typical thing to tune to be able to handle more traffic, and I don't think it has anything to do with your problem.  I don't even know what your problem really is, but it's not something every user is seeing and the sky is falling.

**Comment by jevgenijs** [comment]
@vincent99 the sky may not be falling, but rancher 1.6.x is not working properly. We only started using rancher several weeks ago and our setup is very similar to the initial reporter - 3 hosts, 3 dedicated IP's. The only real difference is that we have newer versions of rancher server and agents, as well as ubuntu instead of CentOs. We noticed that every once in while the connections to all services (all behind load balancers in our case) are being reset, resulting in actual micro down-times. It may go unnoticed if you don't pay attention or don't care that every 50-100 requests you randomly get a 503.

The first google search leads to here, where the official answer to a guy who posted about exactly this already 1 year ago, **with steps to replicate and logs**, is "With the release of Rancher 2.x, development on v1.6 is limited.". 

Don't get me wrong, you are well within your rights to brush it off as an edge case if only some clients experience this, dev time is a precious commodity, we all get that, but for those affected with this the problem is critical with no obvious solutions except migration to 2.x.
