### ISSUE TITLE
Preview in catalog apps is slow and hanging up the app

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13839]
**Rancher versions:** 2.0 master 5/4

**Steps to Reproduce:**
1. In Catalog apps, click on Grafana
2. Click on Preview at bottom

**Results:**  Takes quite a bit of time for preview to open and I can't click on anything else while it's opening.  If I switch to another file (like answers) in the drop-down it also looks like it's hanging.

**Comment by tfiduccia** [comment]
@loganhz - Vincent says this is UI and to send to you to make it faster.

**Comment by sangeethah** [comment]
@loganhz Tested with latest build from master.

I see the UI load's preview option pretty quickly. But when i try to launch files from drop down for "Template Files" , I see some files takes quite a bit of time to load like grafana/dashboards/k8s/kubernetes-capacity-planning-dashboard.json  when switching between them. Is this because of their size?

**Comment by loganhz** [comment]
Yes. Created another PR to show user a loading spinner

**Comment by sangeethah** [comment]
Tested with latest build from master
UI load's preview option pretty quickly. When i try to launch files like grafana/dashboards/k8s/kubernetes-capacity-planning-dashboard.json  from drop down for "Template Files" , I see the loading spinner show up for a short time after which the contents load successfully.
