### ISSUE TITLE
[Multinode] [Zookeeper] Volume locks 

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#1383]
User reported this in issue #1379 where cattle tries to get a lock from zookeeper using a URI which happens to container the volume path in the form file:///var/lib/... Zookeeper sees the /// as two empty nodes when creating the path.

**Comment by cloudnautique** [comment]
ping @will-chan @ibuildthecloud 
/cc @alena1108

**Comment by alena1108** [comment]
Zookeeper reports following error:

/cattle/locks/59/206/DOCKER.STORAGE_POOL.VOLUME.CREATE.1.file:///var/lib/docker/volumes/6ff0e5a73f59c13956584d1d5e648fb674039c9702ad794559b353cf9193ca02 ""
Command failed: java.lang.IllegalArgumentException: Invalid path string "/cattle/locks/59/206/DOCKER.STORAGE_POOL.VOLUME.CREATE.1.file:///var/lib/docker/volumes/6ff0e5a73f59c13956584d1d5e648fb674039c9702ad794559b353cf9193ca02" caused by empty node name specified @63


Looking at their source code,  "///" in the lock name is the culprit:(https://github.com/devhong/Zookeeper.Net/blob/master/Zookeeper/Utils/PathUtils.cs, line 41),

"file///..." in the lock name is the cattle's volume URI. Looks like we read this field to form the lock name, and zookeeper doesn't like it.

**Comment by ibuildthecloud** [comment]
@alena1108 just change the code to use the hash code of the volume path string.  In general we keep lock names to [a-z0-9._] this one just slipped by I guess.

**Comment by ibuildthecloud** [comment]
The other thing is we can normalize the paths in the ZK lock code to replace non valid characters with _

**Comment by ibuildthecloud** [comment]
Oh wait, that's bad, don't do that.

**Comment by haswalt** [comment]
Any movement on this? Need any more help from me?

**Comment by haswalt** [comment]
This is kind of a major blocker. has anyone managed to look at this or need any more information?

**Comment by ibuildthecloud** [comment]
@haswalt Sorry for the sluggish response on this.  I'll get the fix in master today.

**Comment by haswalt** [comment]
Has this made it into the new latest image?

**Comment by cloudnautique** [comment]
Its in v0.31.0-rc2 we are in the process of testing...

**Comment by deniseschannon** [comment]
@haswalt Any image that has a RC in it's tag is still being tested. We will only tag it as latest when it's passed testing.

**Comment by haswalt** [comment]
I've tested this with RC3 and it looks to be working now. My containers boot correctly and no more errors are shown

**Comment by cloudnautique** [comment]
Verified as well.
