### ISSUE TITLE
Reduce ipsec connectivity check requirements during upgrades

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#13891]
**Rancher versions:**
rancher/server or rancher/rancher: v1.16.18

We should reduce the ipsec connectivity check requirements during ipsec upgrades only.  A slow network can cause the ipsec upgrade to take an extremely long time even if things are healthy.  This also doesn't scale well as the number of hosts grow in a given environment.

The proposal is this.  When ipsec is upgrading, the connectivity check should query metadata to understand the service is in an Upgrading state and only perform 1 random connectivity check to a host, if possible.  If that returns healthy.  When ipsec service goes back to Active, you can resume normal operation.

**Comment by sangeethah** [comment]
Upgrade from 1.6.18 with environment having 30 hosts  ->1.6.19-rc5 .
When upgrade was happening , did not see any of the ipsec containers being reported unhealthy.

Upgrade of ipsec service itself took ~8 minutes and had about ~50 DOWN events being reported which could be attributed to the ipsec-connectivity-check container being unavailable because of being recreated when healthcheck was attempted.

```select * from service_event where instance_id in (select id from instance where name like "ipsec-ipsec%") and reported_health like "DOWN%" and id >2810 order by created```


The same scenario when attempted when upgrading from v1.6.16 -> 1.6.18 had lot more DOWN events reported for ipsec containers when upgrade was in progress and upgrade itself took slightly longer time.

Upgrade from 1.6.16 with environment having 30 hosts  ->1.6.18 .
Upgrade of ipsec service itself took ~10 minutes and had about ~125 DOWN events being reported which was double the number of DOWN events from the 1.6.19 upgrade scenario.

**Comment by sangeethah** [comment]
Tested with 1.6.18:
Drop inter host communication between 2 hosts in a 3 host setup , so that ipsec reports unhealthy.
Upgrade ipsec service.
It gets stuck in upgrading state forever , since the new container gets stuck in "Initializing" state.

With 1.6.19-rc4:
Drop inter host communication between 2 hosts in a 3 host setup , so that ipsec reports unhealthy.
Upgrade ipsec service.
As soon as we start upgrading the service , the ipsec containers that were reported unhealthy , get reported as being healthy. When ipsec containers get created they also get to "healthy" state immediately (even when the inter host communication is bad since the health check is always returned as true when service is not in "active" state) and upgrade succeeds.
