### ISSUE TITLE
Make Rancher EKS Integration More Robust

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#13910]
Right now Rancher is relying on cloud formation stack templates hosted in s3 that AWS controls to spin up EKS clusters.  When EKS GA was released these templates were removed and Rancher-EKS integration broke. A quick fix was implemented that used the latest version of those templates. We need to update our code to be more robust by either vendoring the templates or putting the logic in the code.

This means the following needs to be updated
1. service role template
2. vpc template
3. worker nodes template

**Comment by nathan-jenan-rancher** [comment]
We should also refactor the posting of the EKS cluster to use the EKS Go SDK.

**Comment by superseb** [comment]
This also includes specifying existing VPC, existing role, instead of creating them all by default.

**Comment by nathan-jenan-rancher** [comment]
I've gone over the new EKS GA system and have some thoughts/questions on how we should be handling the new features that were added since beta:

1. Amazon suggests using a reusable service role for creating clusters.  Right now we are creating a new service role for each EKS cluster we spin up.  We could change Rancher to use an existing role that the user specifics, or have Rancher only create the service role if it doesn't exist (or both).
2. We are currently bypassing heptio authentication.  Do we want to investigate either integrating AWS's EKS authentication system into Rancher?
3. We create a new VPC/Subnet for each EKS cluster.  Can we allow the user to specify a VPC or Subnet? There are some specific requirements around what VPCs and Subnets should look like. Can we have Rancher automatically update a VPC or Subnet if it is not configured correctly?
4. Specifying security groups have the same problems as specifying VPCs and subnets (and may be required if specifying a VPC/subnet.
5. Right now all VPCs are exposed to the public internet by default, maybe add an option to not do this.
6. We don't support modifying existing clusters at all right now. Looks like EKS clusters can't be modified (which means we can't change VPC, subnet, security groups, or even k8s version), but VPCs/subnets and worker nodes can.
7. Amazon says to not use root credentials when creating an EKS cluster, might be a good idea to remind the user of this or check and fail if root credentials are supplied.
8. DNS propagation takes a few minutes when exposing a pod with a layer-4 LB.  We should see if there is a way to show this to the user (healthchecks?)
9. Our deletion process leaves a lot of resources dangling.  When we delete VPCs it is often blocked because of network interfaces and LBs.  Can we have rancher automatically find and delete these resources so that the VPC is deleted successfully?

**Comment by deniseschannon** [comment]
1. Amazon suggests using a reusable service role for creating clusters.  Right now we are creating a new service role for each EKS cluster we spin up.  We could change Rancher to use an existing role that the user specifics, or have Rancher only create the service role if it doesn't exist (or both).

> Yes, we should be able to use an existing cluster service role. 

2. We are currently bypassing heptio authentication.  Do we want to investigate either integrating AWS's EKS authentication system into Rancher?

> Not as of now

3. We create a new VPC/Subnet for each EKS cluster.  Can we allow the user to specify a VPC or Subnet? There are some specific requirements around what VPCs and Subnets should look like. Can we have Rancher automatically update a VPC or Subnet if it is not configured correctly?

> Yes, we should give flexibility to VPC/subnet. We should not automatically update a VPC/Subnet, but we should document what are the VPC/subnet requirements. 

4. Specifying security groups have the same problems as specifying VPCs and subnets (and may be required if specifying a VPC/subnet.

> We should give the ability to let them  select their own, but document on what needs to happen for security group.


5. Right now all VPCs are exposed to the public internet by default, maybe add an option to not do this.

> Yes, let's add this option when we create VPC, but not if they are using an existing one. 

6. We don't support modifying existing clusters at all right now. Looks like EKS clusters can't be modified (which means we can't change VPC, subnet, security groups, or even k8s version), but VPCs/subnets and worker nodes can.

> Hold off on this for now. 

7. Amazon says to not use root credentials when creating an EKS cluster, might be a good idea to remind the user of this or check and fail if root credentials are supplied.

> Add a note in the UI for this

8. DNS propagation takes a few minutes when exposing a pod with a layer-4 LB.  We should see if there is a way to show this to the user (healthchecks?)

> File a separate issue for this. We have this issue for all k8s managed providers. 

9. Our deletion process leaves a lot of resources dangling.  When we delete VPCs it is often blocked because of network interfaces and LBs.  Can we have rancher automatically find and delete these resources so that the VPC is deleted successfully?

> No, we should only delete the nodes themselves and put a note reminding the users that these network related resources are not deleted and need to be cleaned up themselves.

**Comment by deniseschannon** [comment]
As for hosting templates, I'd recommend that we host it on releases.rancher.com, but defer to @vincent99 if he has other ideas.

**Comment by nathan-jenan-rancher** [comment]
Created https://github.com/rancher/rancher/issues/14566 to track enhancements to EKS driver outside of making it more robust.

**Comment by nathan-jenan-rancher** [comment]
Consider taking a look at https://github.com/weaveworks/eksctl, it does a lot of things we do already in our integration

**Comment by nathan-jenan-rancher** [comment]
Added https://github.com/rancher/rancher/issues/16157 to track adding the root credentials note to the UI

**Comment by nathan-jenan-rancher** [comment]
Closing this issue out because it has been split out to, or addressed and tested in, other issues
