### ISSUE TITLE
Wrong rancher container started after os update

### ISSUE THREAD

**Issue by moimael** [rancher/rancher#1392]
Hi,

I updated Rancher from 0.24 to 0.25 using the method described in the documentation. I kept the 0.24 container under the name original rancher and started 0.25 under the name latest_rancher doing a volume_from original rancher; 
That worked perfectly fine. 
Now each time I do a RancherOS upgrade and have to reboot, the original_rancher container is launched but not the latest_rancher. Which mean I have to manually stop and start container to have the latest version running.

It's a bit of a pain, especially when updating regularly like now with the beta going on.

**Comment by ibuildthecloud** [comment]
@moimael This does suck...  The problem is that if you have `--restart=always` on the container, even if the container was stopped when the Docker daemon is restarted Docker will start it back up.  I don't think that is the correct behavior.  I'll take that up with the Docker team and see what they think.  For a fix for your issue I'd do the following:

```
docker create --volumes-from orignal_rancher --name rancher-data rancher/server
docker run --restart=always --volumes-from rancher-data -p 8080:8080 rancher/server
```

@deniseschannon Our instructions should probably tell people to create a rancher-data container from the original.

Then you can delete `original_rancher`.  Now going forward just keep the rancher-data container around and the current rancher server.

**Comment by moimael** [comment]
Thanks ! I'll try this ASAP. I agree on updating the doc, because it is very confusing when you begin updating rancher.

**Comment by deniseschannon** [comment]
@moimael We've updated the documentation to reflect creating a data container for upgrading.
