### ISSUE TITLE
Problem with volumes(longhorn) results in a never ending deployment

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#13944]
**Rancher versions:**
rancher/server or rancher/rancher:v2.0.2
rancher/agent or rancher/rancher-agent:v2.0.2

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom Cluster with rke

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher, 3 node cluster

**Steps to Reproduce:**

See https://github.com/rancher/longhorn/issues/85

**Results:**

The result is a never ending deployment, e.g.:

````
./kubectl -n wordpress get pod
NAME                                         READY     STATUS              RESTARTS   AGE
wordpress-mariadb-c8fd6b65d-mls8l      1/1       Running             0          1d
wordpress-wordpress-7568bbd7b4-cvnn2   1/1       Running             0          1d
wordpress-wordpress-867b64bdfd-nb4pc   0/1       ContainerCreating   0          4m
````

As you see, ther're 2 deployments, where only one is configured:
````
./kubectl get deployment -n wordpress
NAME                        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
wordpress-mariadb     1         1         1            1           3d
wordpress-wordpress   1         2         1            1           3d
````

**Comment by yasker** [comment]
@dnauck It's due to wordpress chart is a deployment rather than a statefulset.

Adding a sidecar will cause kubernetes to perform rolling upgrade for the deployment. But since Longhorn is RWO (read-write-once) storage system, the persistent volume cannot be mounted to another node. So the new wordpress pod failed to start, stopped the rolling upgrade process.

If we're using statefulset for wordpress, this can be avoided.

Also, if the pod launched with the sidecar, this can be avoided as well.

**Comment by loganhz** [comment]
Please try https://github.com/rancher/rancher/issues/13944#issuecomment-398543354
