### ISSUE TITLE
Rancher deploy and stateless services

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#13998]
Rancher versions : 2.02
Docker version: (docker version,docker info preferred) 17.03.2-ce
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
4.9.0-6-amd64
Virtualbox
Rancher in Rancher
**Steps to Reproduce:**
1.Create custom cluster with one node - node when rancher slave will be deployed
2.deploy to that node agent with all roles
3.wait until it will be registered
4.go to workloads, deploy rancher/rancher, and in advanced options -> commands add : "--k8s-mode embedded --add-local false"
5.wait until rancher slave will be working
6.in rancher slave create a custom cluster and attach 3 nodes (1 with etcd and control, 2 with worker)
7.in rancher master create next cluster with one node (itself)
8.deploy nexus docker repository on rancher master in newly created cluster that will be proxying to dockerhub
9.deploy nexus docker repository on rancher slave cluster that will be proxying to rancher master repository
**Results:**
All is working fine but when i restart machine where nexus or rancher slave then rancher or nexus is getting freshly new so all repos are gone and im prompted to set a new admin password , it's like reseting all to a state when i deploy.
Another problem is i want to be able to deploy apps through name of the service of nexus like this: nexus:/busybox in other cluster also located on rancher master and on rancher slave.
![chrome_2018-06-14_10-55-30](https://user-images.githubusercontent.com/32438378/41407403-9b0b4432-6fcf-11e8-917a-1791f75b72d8.png)
![chrome_2018-06-14_10-55-54](https://user-images.githubusercontent.com/32438378/41407405-9b26ba0a-6fcf-11e8-82f6-7c59a126e46c.png)
![chrome_2018-06-14_10-56-22](https://user-images.githubusercontent.com/32438378/41407406-9b439396-6fcf-11e8-821a-17fdb552f7e2.png)

**Comment by superseb** [comment]
Running Rancher in Rancher via Rancher is an advanced use-case (next to being unsupported). The launched Rancher has no persistence, it launches an embedded etcd which can be mounted to a host directory to keep persistence, if you don't, it will be cleared on container re-creation (not on restart).

Re-using etcd for this is not recommended as it should be for a single cluster (and it's the most important part of a cluster).

I would stay away from this setup if these concepts are unknown, you will end up in a world of hurt when trying advanced usecases when internal workings are unknown.

If you believe there is an actual bug here, let me know and I can re-open.

**Comment by RRadziejewski** [comment]
Could you please provide me info about how to mount this embeded etcd to host directory

**Comment by RRadziejewski** [comment]
Okey my colleague fixed this by mounting /var/lib/rancher

**Comment by superseb** [comment]
It is described here: https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install/#persistent-data
