### ISSUE TITLE
Question about DNS > How it works ?

### ISSUE THREAD

**Issue by ebuildy** [rancher/rancher#1401]
I cannot find documentation and use case examples about Rancher + DNS, I am sorry if it's not the right place to ask:

I have 2 EC2 hosts with Rancher agent running. I created a service called SNMP (that run SNMP) and scale it to each host. The scale is fine, now I can see:
- Admin_snmp_1
- Admin_snmp_2

I want to use observium (kind of Zabbix) to monitor the 2 hosts.

Where can I find their hostnames?

![Link schema]
(https://beemapp.s3-eu-west-1.amazonaws.com/59fb2e86-056a-4225-8e3c-9741733858df.jpg)

Thanks you,

**Comment by vincent99** [comment]
Service links are available in DNS from as whatever you put in as the "as name" when linking.  So in your screenshot 'mysql' and 'snmp-client' will resolve inside of 'observium-server-app' containers.  Try `dig snmp-client`, `ping snmp-client`, etc.

If a service has scale > 1, multiple A records will be returned for the name.  Most clients will pick a random one, but in the next release they will explicitly be sent back in random order every time they are requested.

**Comment by ebuildy** [comment]
Thanks you, so it's "too magic" for me ;-(

Where is the DNS server? any chance to "see it" so I could edit entries.

Thanks,

**Comment by vincent99** [comment]
I don't know if I'd call it magic :smile: ; it's generally the same way links work in native docker, extended to multiple hosts/containers.

The DNS server runs in the "Network Agent" container on each host.  Source is in [rancherio/rancher-dns](https://github.com/rancherio/rancher-dns), and the config is just a JSON file that is pushed down from rancher/server.  You can't really realistically edit it though because it will be overwritten whenever something changes and a new version is pushed.

The only "magic" is that the answers depend on the client that is asking, because you could have another container A with a link to container B "as mysql" and "mysql" in A would be different than "mysql" in "observium-server-app".  It's not really a general purpose server either, its only purpose in life is to return A (and CNAME in next release) records that depend on the source IP that asked for them.  For anything not found it recurses to the default DNS servers, so you can layer anything you want on top of them.

**Comment by ebuildy** [comment]
Oups, I call magic something I cannot understand ;-) yet... 

Where I can see the JSON file used ?

Thanks,

**Comment by vincent99** [comment]
Click "Execute Shell" on one of the Network Agent containers, `cat /var/lib/cattle/etc/cattle/dns/answers.json`

**Comment by vincent99** [comment]
(Note that the JSON structure is changing in the next version/later this week... https://github.com/rancherio/rancher-dns/tree/cname)

**Comment by ebuildy** [comment]
Ok thanks you, I start to understand the mechanism behind this.

How containers know the DNS to use?

**Comment by ebuildy** [comment]
I cant see anything:

![Rancher DNS?]
(http://b3.ms/YxpM1717AgK3)

I don't see any DNS server running, I am searching documentation about the Rancher agent, found a repository: https://github.com/rancher/agent-instance, but nothing more ;-(

Is there any real example online?

Many thanks,

**Comment by alena1108** [comment]
@ebuildy answers.json exists inside agent-instance container, not the rancher-agent. You can either look up the instance with the name "rancher/agent:v<version>" and ssh using docker, or you can also access it using Shell Access from Rancher UI for the Network agent instance.

Here is the link to Rancher-DNS project. The answers.json example there though is of the newer version that hasn't been released yet:

https://github.com/rancher/rancher-dns

**Comment by ebuildy** [comment]
Thanks, yep I can see a file with:

````
{
    "default": {
        "recurse": [
            "213.186.33.99"
        ]
    },
    "": {}
}
````

Whereas all my containers IP are 10.* ;-( How can I use it (I don't see port 53 bind)?

Is there a real example somewhere where someone using it in production?

Thanks you very much,

**Comment by vincent99** [comment]
Everyone using Rancher is using it "production" (whatever that means to them).  A Network Agent container runs on each host.  Every container on that host gets configured to use the Network Agent as it's DNS resolver (via link-local IP, `169.254.169.250`.. look at `/etc/resolv.conf` in any of your containers).  [rancher-dns](http://github.com/rancher/rancher-dns) runs in the container and responds with answers from `/var/lib/cattle/etc/cattle/dns/answers.json` based on the IP of the container who made the request.  Things that are not in the JSON file are sent up to the public DNS recurser.

There are entries in the DNS server JSON file only for things that need to be there.   It is not a general purpose DNS server, and it does not contain all the container's hostnames. It only has entries for the "as name" of containers that are linked together, so that you are explicitly defining the relationships needed between containers.

**Comment by ebuildy** [comment]
Thanks you very much for the detailed answer, I can see the DNS entries work only when using Rancher service :/

Also, how can I create a mysql (or mongodb, elasticsearch...) cluster if DNS is working in that way?

Thanks you,

**Comment by rcarmo** [comment]
> It only has entries for the "as name" of containers that are linked together, so that you are explicitly defining the relationships needed between containers.

Do you think it would be possible to add entries for individual containers that are not part of services/links? It would make it a lot easier to set up some services (even the GlusterFS/PXC examples you have on your site would benefit from that)

**Comment by cusspvz** [comment]
> Most clients will pick a random one, but in the next release they will explicitly be sent back in random order every time they are requested.

@vincent99 could you please point me where is that discussed? Because I need to gather all information related with service discovery to start creating cluster-targeted images and templates just for rancher.

**Comment by vincent99** [comment]
The specific bit you quoted was done months ago, `A` records for linked services return the IPs of the containers in a random order.

What is probably more useful to you is [metadata](http://docs.rancher.com/rancher/metadata-service/), which will let a container look up info about itself and the other containers in a service.

Also [this repo](https://github.com/rancher/compose-templates), though it is a work in progress.

**Comment by cusspvz** [comment]
Thanks @vincent99
