### ISSUE TITLE
Not able to import an existing GKE Cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14030]
**Rancher versions: Build from master - Jun 15
**Steps to Reproduce:**

Tried to import an existing GKE Cluster.
It fails to get imported with following errors when running the kubectl command:

```curl --insecure -sfL https://<ip>/v3/import/j7kc2knmwsr2lfvrsw2rvlvk5xrd54zm4hzcs85k7mh6vjmkgm228q.yaml | kubectl apply -f -```
```
namespace "cattle-system" created
serviceaccount "cattle" created
clusterrolebinding "cattle-admin-binding" created
secret "cattle-credentials-108fedd" created
deployment "cattle-cluster-agent" created
daemonset "cattle-node-agent" created
Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "cattle-admin" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]} PolicyRule{NonResourceURLs:["*"], Verbs:["*"]}] user=&{sangee2004@gmail.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```

**Comment by deniseschannon** [comment]
Due to changes required to get AKS imported clusters working, which don't have a `cluster-admin` by default. We had to add in ability to create our own role (`cattle-admin`), which is the same permissions as the built-in `cluster-admin` roles that other Kubernetes distros may have. 

To be able to create this `cattle-admin` role and your Kubernetes distro already had a `cluster-admin` role, you must have `cluster-admin` permissions to be able to import the cluster in and create the `cattle-admin` role. 

By default, GKE already has an existing `cluster-admin` role so the user importing the cluster would need to have been assigned the `cluster-admin` role, which can be done with: 

```
kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user useremail@gmail.com
```

@westlywright We should update our UI to include notes about needing to add cluster-admin permissions for any Kubernetes cluster. 

@StrongMonkey Can you make a docs change in these files to indicate what was written above for importing any Kubernetes clusters?

https://rancher.com/docs/rancher/v2.x/en/concepts/clusters/cluster-providers/
https://rancher.com/docs/rancher/v2.x/en/tasks/clusters/import-cluster/

@nathan-jenan-rancher we should determine the behavior for EKS as well for import.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/41642450-ef1261f8-749a-11e8-8161-e4cce658c523.png)

Added the notes in UI

**Comment by sangeethah** [comment]
Tested with latest build from master

Able to import GKE cluster successfully using the instructions provided in the UI for creating cluster bindings before importing the GKE cluster to rancher.

**Comment by PicoCreator** [comment]
Coming in from a fresh perspective : it wasn't clear to me what `[USER_ACCOUNT]` means. It would help if a few examples were provided. It also doesn't help that if I were to get it wrong there would be no error. Until the second command step. Which once executed cannot be undone without destroying the cluster (or the definitions done)

Possible confusing interprations 

+ rancher user?
+ gcp service account?
+ current login user?

This is coming from a GCP perspective, AWS might have other confusing terms, and may need their own example.

**Comment by muxalko** [comment]
+1 
Agreed with PicoCreator.
[USER_ACCOUNT] isn't very clear. 
Does that mean the rancher default "admin" user is going to be used,
or a new user should be created at kubernetes cluster for rancher ? Then,  where should it be provided ?

BR,
Michael

**Comment by mikepuglisi** [comment]
+1 Trying to figure out what USER_ACCOUNT is

**Comment by anthonyav** [comment]
Hello,

i'm trying to import a GKE cluster, and i have a similar error. my version of rancher is v2.1.4
I first run
`kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user [USER_ACCOUNT]`

then 
`kubectl apply -f https://....`

To have this error : 
Error from server (Forbidden): error when creating "https://mydomain.com/v3/import/j8fpjwhhxhnflhg27ht6h7txmbt4dhshsiisdsdsdnfdsf6bctv6fpj.yaml": clusterroles.rbac.authorization.k8s.io "cattle-admin" is forbidden: attempt to grant extra privileges: [{[*] [*] [*] [] []} {[*] [] [] [] [*]}] user=&{test@test.com  [....

Thanks

**Comment by paulliss** [comment]
> 
> 
> +1 Trying to figure out what USER_ACCOUNT is

It seems should be an user account that you use for k8s cluster administration.

Going through this steps helped me out:

1.Create
kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user myuser
2.Check existence
kubectl get clusterrole cluster-admin -o=yaml
3.Restart Rancher
docker container restart <rancher-container-name>
4.See Rancher logs
docker logs -f <rancher-container-name>

If it doesn't, try to stop and delete all rancher containers, delete rancher configs and start hole rancher steps again.
