### ISSUE TITLE
Settings cacerts keeps resetting when scaling rancher instances

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#14067]
**Rancher versions:**
2.0.2

Right now when I scale the Rancher instances up and down the cacert setting keeps resetting. I have a custom CA cert I provided but it gets reset back to the old initial one when instances are scaled.

Is this cacert setting global to all rancher instances or is it per instance? If a instance starts up should it not replace if one is already set?

**Comment by mlguthrie** [comment]
I'm using Rancher 2.0.8 and I am experiencing a similar issue. I don't even have to scale Rancher instances, just give it enough time and the cacert reverts back.

**Comment by bigbrozer** [comment]
Just did a new install of Rancher using v2.0.8 and the helm chart installation method: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/.

Versions:

* helm v2.11.0
* rancher v2.0.8

## Steps to reproduce

Install Rancher using 3 replicas (3x nodes), a private CA + certs and a HTTP proxy:

```shell
helm install rancher-stable/rancher \
    --name rancher \
    --namespace cattle-system \
    --set replicas=3 \
    --set hostname=<RANCHER_URL> \
    --set rancherImageTag=<RANCHER_VERSION> \
    --set ingress.tls.source=secret \
    --set privateCA=true \
    --set proxy="http://<PROXY_URL>:3128" \
    --set noProxy="127.0.0.1\,localhost\,10.0.0.0/8\,172.16.0.0/12\,192.168.80.0/20\,192.168.144.0/20"
```

Created the Ingress cert with:

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key
```

Created also the private CA with:

```shell
kubectl -n cattle-system create secret generic tls-ca --from-file=cacerts.pem
```

I'm able to connect on https://<RANCHER_URL> successfully but the **cacerts** setting option is empty. Tried to paste the CA in but it is empty after a couple of seconds.

When creating a cluster and adding nodes, the docker run command is missing the `--ca-checksum`.

Running the command output in the rancher-agent container is ending with:

```
...
Failed to connect to proxy" error="x509: certificate signed by unknown authority
...
```

## Workaround

Scale down the replicas:

```shell
kubectl scale -n cattle-system --replicas=1 deployment rancher
```

Edit **cacerts** again, now it stay over time.

Now able to register nodes in the cluster because the `--ca-checksum` is set in generated docker run command.

**Comment by loganhz** [comment]
In 2.1.0, you can set replicas to 3.
https://github.com/rancher/rancher/releases/tag/v2.1.0

Please let us know in a comment if you can still reproduce the issue in v2.1.0, and we'll reopen it
