### ISSUE TITLE
Authenticated users need to be added to global users list.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14072]
**Rancher versions:**
Master 6/18/19

**Steps to Reproduce:**
Enable azure AD authentication
Select users 

**Results:**
Authenticated AD user should be listed under users as admin.

**Comment by dramich** [comment]
The users tab shows local users only so when a new user logs in via a provider a local user is created and mapped to the external provider in order to get their `Token`. The first user to turn on an auth provider is mapped to the Default Admin. This mapping can be seen by viewing the users through the API under `principalIds`. If 100 users are added under the auth screen they will not show up under Users until that user logs in for the first time thus creating the token. 

This is currently working as expected.

**Comment by sangeethah** [comment]
@dramich Since we have multiple "principalIds"associated with the "Default Admin" user now, UI should be able to show all the users associated with this account ?

**Comment by deniseschannon** [comment]
I spoke with @adingilloRancher about this. This is as designed and confusing for most users. We've tried to update the docs with clearer information about how it works:

https://rancher.com/docs/rancher/v2.x/en/concepts/global-configuration/authentication/
