### ISSUE TITLE
Shibboleth / HTTP header auth

### ISSUE THREAD

**Issue by rcarmo** [rancher/rancher#1417]
Hello there,

It would be great if Rancher supported [Shibboleth](https://shibboleth.net/) for authentication, or at the very least be HTTP aware to the point where one could pass HTTP_REMOTE_USER and other information as HTTP headers like described [here](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAttributeAccess).

It would then be very straightforward to deploy Rancher behind an authenticating reverse proxy (which would set `X-Remote-User`, `X-Remote-Name`, `X-Remote-Mail`, etc.) for institutions who don't/can't use GitHub for auth but already have Shibboleth in place for single sign-on.

**Comment by rcarmo** [comment]
Here's an example from our own Shibboleth setup (these are the env vars exposed to a CGI app, mapped directly from HTTP headers - they're all available as `X-Shib-Foobar` on a raw HTTP request):

<pre>
HTTP_SHIB_SESSION_ID: _e132eb4673effa1ae9a23239882fd28d
HTTP_SHIB_IDENTITY_PROVIDER: https://login.intranet.local/shibboleth
HTTP_SHIB_APPLICATION_ID: intranet
HTTP_SSOMAIL: rui.carmo@<redacted>
HTTP_SSOUNIXNAME: rcarmo
HTTP_SHIB_AUTHENTICATION_INSTANT: 2015-07-08T07:49:04.143Z
HTTP_SSOCONTACTMAIL: rui.carmo@<redacted>
HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12
HTTP_SSOBID: ae8203fd-c2ce-4e07-82df-d142927f5495
SERVER_NAME: intranet
HTTP_SSOLOGOUTURL: https://login.intranet.local/Logout.do
HTTP_SHIB_AUTHNCONTEXT_CLASS: urn:oasis:names:tc:SAML:1.0:am:unspecified
HTTP_SSOAUTHTYPE: digest
HTTP_SSOAUTHGROUP: admin
HTTP_REMOTE_USER: rcarmo
HTTP_SHIB_ASSERTION_COUNT: 
HTTP_SHIB_SESSION_INDEX: 
HTTP_SHIB_AUTHENTICATION_METHOD: urn:oasis:names:tc:SAML:1.0:am:unspecified
HTTP_SSONAME: Rui Carmo
</pre>

**Comment by deniseschannon** [comment]
@rcarmo We are working to make it easier to set up SSL at this time. If there is enough interest in Shibboleth, we can definitely look into adding it into our roadmap.

**Comment by rcarmo** [comment]
Well, again, the header authentication method I described will work with _anything_ that can act as a reverse proxy (Apache with Kerberos, Apache with LDAP, etc., etc.), so I wouldn’t say Shibboleth is the single authentication service in question here — by supporting user IDs sent over HTTP headers, you’ll be making it possible for a lot of people to tie in Rancher with whatever auth method they need.

**Comment by vincent99** [comment]
Determining what user the request is for is only the authentication half the problem; The other half is authorization, what resources should that user have access to.

We do not really want to be yet-another place for your company to configure a list of who is a member of what team, so we pull in GitHub teams/orgs, LDAP groups, etc and encourage you to use those instead of adding individual people to Environments.

The API then needs to be able to lookup things like what groups a user is a member of to determine what Environments they should have access to.  That requires integration with each individual identity provider.  There is a bunch of work going on to generalize everything from assuming GitHub to being pluggable, and once that is done adding additional providers will be easier, with the first new one being LDAP as @deniseschannon said.

**Comment by rcarmo** [comment]
Hi Vincent,

That’s the whole point of Shibboleth (and mod_ldap, and Kerberos) filling the HTTP headers - you don’t get just authentication, you get a full-blown user profile.

You’ll notice that the set of HTTP headers I added as an example flags my user as an admin (HTTP_SSOAUTHGROUP). And there’s more I excised (tuples with specific attributes).

There’s no need to configure anything inside Rancher - you get all the required profile information from the upstream proxy, and whoever manages that proxy can easily tweak the auth group/perms headers to accommodate the values you might need (for instance, setting which LDAP attribute gets mapped to the right HTTP header - with nginx, you can even transform the headers using Lua). This setup is often used to centralize authentication (and first-pass authorization) for several services behind a single trusted proxy.

It also frees you from having to bind to LDAP/Kerberos/whatever yourself (which might not be possible due to connectivity restrictions) and have the site admins set a connection configuration for that on Rancher.

Plus this is easily mockable in testing, etc. So I think it’s a lot simpler for a first pass than having to do all the work of hooking up to various auth back-ends.

(Incidentally, the reason I suggested this is that we’re running this kind of trusted reverse proxy setup in front of hundreds of systems and web applications - the benefits of doing this at scale are tremendous, since only a few machines actually need to have connectivity to our AD or other IDPs…)

BTW, Denise’s original reply - which I got via e-mail - said you were working on SSL. I can use a direct LDAP binding, but it’s still less flexible (and more error-prone) than the approach I’m suggesting (which I still think would save you a lot of time).

**Comment by vincent99** [comment]
I understand that you like SAML.  It would indeed be easier for us if we could not write a bunch of GitHub and LDAP and GitLab and BitBucket-specific code and just make it an external service's problem.

But for anybody that doesn't already use it, it's a complete non-starter to ask them to go install & maintain a highly-available configuration of a new and complicated service so they can enable access control in our product.  Especially because we'd want you to install it outside of Rancher to avoid catch-22 situations (where you can't fix the problem because you can't get in because auth is broken because auth is broken).

So the practical option is adding it as one of the supported access control drivers among the others.  If everything we need is in the headers then it will be a very simple driver to write.  I see the list of groups you're a member of... what about the list of users and groups (that you're not a member of) that exist, for autocomplete/validation in the UI?

Yes, there was a misunderstanding about what this was so the post was edited... sorry for the confusion.

**Comment by rcarmo** [comment]
Erm. No, I don’t actually like SAML (in fact I hate it, and there are a few untold sagas regarding my wrestling with Shibboleth configs until I was actually being asked to do it for other folk…)

All the above is applicable if you just use Apache + LDAP as a reverse proxy, or htpasswd and a few tweaks to set group names :)

But yeah, the full group list can also be obtained from the IDP and added to an HTTP header. 

There’s a sea of XML/XSLT to do that “magically" in Shibboleth (we send out a list of back-offices a user is entitled to access, for instance, as well as a list of groups/projects they’re members of), and it should also be doable in an Apache + LDAP/Kerberos setup (although I don’t recall exactly how). We use HTTP_SSOPROJECTS for the latter, IIRC.

**Comment by sshipway** [comment]
I'd like to add a +1 for Shibboleth support.  Either native Shib support built into Rancher (preferable), or header integration from a shib-locked proxy, as @rcarmo was suggesting.  Shib is our standard auth method here, and it is the preferred way to authenticate.

Of course, an LDAP call would still be necessary to obtain group data, unless you can pull this from the Shib metadata.

**Comment by sshipway** [comment]
Another benefit of using Shibboleth (at least, for us) is that we could then use our Two-factor Authentication which is integrated into Shibboleth.

**Comment by jschilperoord** [comment]
+1 For SAML support. We are using both Shibboleth and OneLogin and it would be nice to integrate one of them

**Comment by deniseschannon** [comment]
With v1.2, Shibboleth can now be used for access control.
