### ISSUE TITLE
OpenLDAP - Display name is  not shown for some users in site access list

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14245]
**Rancher versions: Build from master
**Steps to Reproduce:**
Have a OpenLDAP auth enabled in the setup.
Added a user with following fields to site access:

```
testuser9 (password1) - Special characters in cn-tuser9,{} and sn-snuser9{:::)@
```

Once the user is added , display name for the user is not shown in the access list.

<img width="1256" alt="screen shot 2018-06-26 at 8 02 51 pm" src="https://user-images.githubusercontent.com/4266958/41950700-23d295ee-797c-11e8-9ce1-d252161e94e7.png">

**Comment by carolynhu** [comment]
@westlywright  This might be an UI bug, since I added a bunch of test users, but the name not showing within parentheses occurs randomly.
<img width="1080" alt="screen shot 2018-06-27 at 2 35 08 pm" src="https://user-images.githubusercontent.com/29208297/42002936-f62019e4-7a1d-11e8-841d-b4109e4f381e.png">

**Comment by westlywright** [comment]
I think something changed in the backend and the bug was fixed before I could check because on `master` as of 5:11pm I am not seeing the issue. 
<img width="1341" alt="screenshot 2018-06-27 17 11 20" src="https://user-images.githubusercontent.com/858614/42006182-3aacec72-7a2d-11e8-922f-0af5656402ef.png">


@carolynhu I've also include a quick pseudo-code logic flow for how we display those names in that component 
```
if principal.displayName
  displayname > computed from  `name OR ( id )`
else if principal.loginName
  principal.displayName (principal.loginName) > principal.loginName is computed from principal.username
else if unkownuser
  `unknown user` > set when we can not fetch user data from api (incase of cross provider search)
else
  non-breaking space > all else failed  
```

**Comment by sangeethah** [comment]
Tested with v2.0.5-rc2.

This issue is not reproducible anymore. Display name is shown for users in site access list
