### ISSUE TITLE
Add drain action for the node

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#14265]
Add then following actions into cluster nodes:
* drain - equivalent of cordon + rescheduling pods if applicable to other worker, nodes. Also give an optional parameter to delete host.

**Comment by kinarashah** [comment]
Not ready to test yet, seeing a few issues with `stopDrain`.

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/issues/15260

**Comment by sangeethah** [comment]
@kinarashah When a host is drained , host state gets to "Drained" state which also means that it is in "NodeNotSchedulable" state which is similar to "Cordoned" state.
Should we be putting the host in "Cordoned" state after draining , since we already have a state for this? Or should we also name the "Cordoned" state to be something like "NotSchedulable" and use it for both cordoned and drained host ?

**Comment by mitchellmaler** [comment]
I know right now when a node is deleted it is condoned. Now with the drain action will the be added to the delete process?

**Comment by sangeethah** [comment]
Tested with latest build from master.
"Drain" action is now available for the worker nodes.

It was decided that when a node gets drained , its state will transition from "Active"->"Draining"->"Drained". User will be given the "Uncordon" option on the nodes that are in "Drained" state.


There is no Alert when nodes is in "Draining"/"Drained" state.

Bugs found when testing this feature are tracked as different issues.
