### ISSUE TITLE
Validate Docker 18.06 for v1.6

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14297]
Validate latest Docker stable release for v1.6

**Comment by deniseschannon** [comment]
The stable release hasn't been released as of July 9. If it doesn't come out before end of the week, this will have to be done with the next 1.6 release.

**Comment by superseb** [comment]
Docker 18.06 has been released

**Comment by deniseschannon** [comment]
Ran automation using Docker 18.06 and no new issues seen.

**Comment by doreplado** [comment]
@deniseschannon I can open a new issue if you like, but I just wanted to report that the rancher-agent-bootstrap container uses hardcoded DNS of 8.8.8.8 / 8.8.4.4 instead of the host its provisioned to on Ubuntu 18.04 + Docker 18.06. 

The effect of this is that anyone using a private zone for their Rancher URL will fail to provision the rancher agent and get the: "Failed to find rancher-agent container"

**Comment by doreplado** [comment]
Opened https://github.com/rancher/rancher/issues/14849
