### ISSUE TITLE
Fix Clone on all types

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#14350]
**Rancher versions:** 2.0 master 7/1

**Results:**  Review clone on all types and add it back.  It is missing.  (Workloads, pipeline and notifier have clone but it's missing everywhere else).

**Comment by vincent99** [comment]
Especially NodeTemplates, but anything that can reasonably support it, should.  (Namespace, Cluster, and other deeply nested things aren't going to be reasonable)

**Comment by vincent99** [comment]
Storage Class: Seems potentially useful

PV: I think my concern was once you're looking at disks "clone" starts meaning give a copy of this disk and all of it's data and that's not what it's going to do.  

Project -> Volume (PVC): This is weird because after they're bound you're pointing at a specific volume and probably can't use it again.

Secret scope: sure

**Comment by deniseschannon** [comment]
@westlywright  let's add the ability to update the secret scope. 

i've made this issue to do clone for alerts: https://github.com/rancher/rancher/issues/14811

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/2
Verified fixed
