### ISSUE TITLE
AD/LDAP Login not working with 2.0.3+

### ISSUE THREAD

**Issue by hameno** [rancher/rancher#14369]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.3+ (also tested with 2.0.4)

**Steps to Reproduce:**
Our previously configured Active Directory is not working anymore. Logins fail and logs provide the following information:

> [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: server returned error for search DC=corp,DC=example,DC=com (member:1.2.840.113556.1.4.1941:=CN=Firstname Lastname,OU=EMEA,DC=corp,DC=example,DC=com): LDAP Result Code 1 "Operations Error": 00002020: Indexed and full searches both failed!

**Comment by tfiduccia** [comment]
@hameno - Can you log into Rancher using your local admin and see if it's still setup under Security/Authentication?

**Comment by hameno** [comment]
I had to downgrade for now. Will try later.

Sidenote: After downgrade one cluster stays in state error and shows:

> Exit status 1, W0703 19:26:18.756524 140 factory_object_mapping.go:423] Failed to download OpenAPI (an error on the server ("Error: 'waiting for cluster agent to connect'\nTrying to reach: 'https://10.233.0.1:443/swagger-2.0.0.pb-v1'") has prevented the request from succeeding), falling back to swagger error: error validating "management-state/tmp/yaml-820303657": error validating data: an error on the server ("Error: 'waiting for cluster agent to connect'\nTrying to reach: 'https://10.233.0.1:443/swaggerapi/api/v1'") has prevented the request from succeeding; if you choose to ignore these errors, turn validation off with --validate=false

It looks like the cluster is connected and usable despite showing this error

**Comment by alexandrem** [comment]
Maybe you hit the issue here  #14284

Perhaps you should try v2.0.5-rc2 and change the search field like I did.

**Comment by hameno** [comment]
I tried again with 2.0.5 with both a new local admin user and my previous admin user. It does not allow me to login, for the local user with no ldap user I'm getting:

    API error response 401 for POST /v3-public/localProviders/local?action=login. Cause: crypto/bcrypt: hashedPassword is not the hash of the given password

I'm pretty sure the password is correct. Really frustrating...how did this even pass QA?

**Comment by hameno** [comment]
I'd really like to use a newer version to have a fix for #12770

**Comment by cjellick** [comment]
@hameno I believe the reason AD fails for you in v2.0.3+ is because we introduced recursive nested group membership searching and your AD server doesn't like that.

In v2.0.5, we introduced a flag to turn it off. It is in the "Customize schema" section of the Active Direction configuration screen and has the title/heading "Nested Group Membership." You'll want to select the "Search only direct group memberships" option.

Now, you have a bit of a chicken and egg problem since the flag is only available in v2.0.5 and once you upgrade, you cannot log in. So, I suggest you first ensure you can log in with the local admin credentials before upgrading. If you need to, you can reset the default admin password by following the instructions in this FAQ: https://rancher.com/docs/rancher/v2.x/en/faq/technical/
Once you do that and ensure you can log with the default admin creds, you should be able to upgrade, log with the default local admin creds, and update the AD configuration.

Please let us know whether this resolves the problem for you.

**Comment by deniseschannon** [comment]
@hameno in v2.0.6, we will be turning the recursive group search (aka nested group search) off by default  for AD as it seems to be causing issues with people setups that are upgrading. if people specifically use nested groups, they can turn enable it.

if you would like, you are more than welcome to test that you can upgrade to v2.0.6-rc2 from your version to ensure that you're able to log in now.

**Comment by hameno** [comment]
Yes, 2.0.6-rc2 is working. Thank you very much 👍

**Comment by deniseschannon** [comment]
@hameno Great! Thanks for the update.

**Comment by deniseschannon** [comment]
We will be releasing v2.0.6 in the next day or two.
