### ISSUE TITLE
file volume mount hangs gui

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#14387]
deployments can't be edited when they have file mounts.

      volumes:
      - name: openldap
        persistentVolumeClaim:
          claimName: openldap
      - name: secret-volume
        secret:
          defaultMode: 438
          optional: false
          secretName: ldap-secret
      - name: vol1
        secret:
          defaultMode: 256
          items:
          - key: ca
            path: ca.crt
          - key: chain-crt
            path: chain.crt
          - key: key
            path: key.key
          optional: false
          secretName: cert

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.4` UI: `v2.0.53` |
|Access|`` `admin`|
|Route|`containers.index`|

**Comment by loganhz** [comment]
Hi @Toonix , I can not reproduce this issue.
Can you try it in v2.0.6, please?

Can you provide the reproduce steps or a whole yaml which I can use to re-create this issue?

Thanks

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by imwower** [comment]
use any existed file, such as : /etc/localtime, and volume type is Bind-Mount , will cause UI hanged, leave the pod status : ContainerCreating
![91595203](https://user-images.githubusercontent.com/1744486/45479584-79f7aa00-b779-11e8-8f5e-62b5809cf234.png)

you can see the full yaml file here: [nginx.yaml](https://gist.github.com/imwower/f7b3224f6075906448d222c9e8d540d2)

**Comment by loganhz** [comment]
@imikushin 

Reason:

Rancher starts kubelet as a container. It will check `/etc/localtime` in the kubelet container instead of the real host.

Solution One:

You can use `FileOrCreate` instead of `File` for `spec. volumes. hostPath.type`. It will pass the kubelet check. And your container can mount the real `/etc/localtime` on the host.

Solution Two:

Deploy k8s from binaries. And import it into Rancher.
