### ISSUE TITLE
Ingress doesn't work

### ISSUE THREAD

**Issue by develar** [rancher/rancher#14390]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

I want to do very basic and simple task. I have program that listen on 443 port using custom SSL cert (service intended for use by special clients, own certificate authority is used). And I want to expose it.

As I have encountered a lot of pitfall during attempts to configure Rancher, I have decided to not use ingress and simply use HostPort service. But... for some reasons I cannot since "all ports occupied". **why some ingress exists by default and why 80/443 ports are occupied by default** Ok, I didn't find way to disable default ingress and decided to add ingress.

1. Port 443 exposed as Cluster IP.
2. Add ingress. By default "select workload" Ok, workload. I have set it as "default backend". Result: service unavailable. 

Ok... after googling:

2. Add ingress again, but use "service" instead of "workload". Great, get some response, but with "Kubernetes Ingress Controller Fake Certificate", not with mine.

Ok... logically, if Rancher doesn't support TCP proxy (as stated in docs), I need to change my program service port to 80 and my program should listen 80 plain HTTP and SSL termination will be performed by Ingress. And I should add certificates.

Ok, I changed programm to listen plain HTTP on port 80 (still exposed as Cluster port, as ingress only should access it) and certificate was specified for Ingresss. But... as workload target doesn't work (and on forum I see unanswered question about service vs workload), I use "service targret" in ingress settings. But in this case I cannot specify port 443, only 80 (combobox). So, unclear how I can setup Ingress for my very simple and common use case. And wonder why, why such simple tasks cannot be done in several minutes but instead to a lot of googling and unclear internal errors (e.g. my EC key was not accepted, I have forced to use only RSA).

Maybe "Kubernetes Ingress Controller Fake Certificate" is used instead of my specified cert because request performed by IP (CN is set not to domain name, but to something like "node.foo-service") but it is also not expected behaviour (and again, not clear where to see logs about it).

Page https://rancher.com/docs/rancher/v2.x/en/concepts/load-balancing/ even doesn't specify which nginx ingres is used (https://github.com/nginxinc/kubernetes-ingress or https://github.com/kubernetes/ingress-nginx).

**Comment by develar** [comment]
Found docs about underlying RKE — https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/ingress-controllers/ I hope it helps me since rancher is so awesome and low level configuration is quite ok :)

**Comment by TehTotalPwnage** [comment]
For your setup, you shouldn't need to modify the underlying Ingress controller (the Ingress controller and the Ingress **resources** that you can create through the Rancher UI are two different things). If you want to read more about Ingress, you can do so [here](https://kubernetes.io/docs/concepts/services-networking/ingress/#types-of-ingress).

You're correct in that you want to set up the Ingress resource to handle SSL/TLS termination while the actual service only needs to listen on port 80 using HTTP (assuming you want to use Ingress). There's some other issues with your setup, but I'll go over the main one:

Services exposed via Ingress need to have a hostname attached to them, not an IP address. If you try to give an IP address to the Ingress configuration when it asks for a host name for the certificate you provide, it won't work (at least in my testing). You'll either need to work around the issue by finding a way to disable the Ingress controller or make it occupy a different port, make your service accessible through a hostname instead of just an IP address, or have your service exposed using `HostPorts` on other ports.

**Comment by develar** [comment]
To disable ingress, it seems you need to define node sector like `boo: foo` — https://github.com/rancher/rancher/issues/14074#issuecomment-402636690

**Comment by biels** [comment]
So we can conclude that in rancher 2.0 the ingress feature as set up by default does not work?

**Comment by quangnhut123** [comment]
For me its opposite that when i create an ingress with target is a workload. Its can work. But when i want to change to service target then its not work always automatic redirect to a self sign ssl page of ingress instance. dont know why !

**Comment by deniseschannon** [comment]
Ingress in Rancher is working as expected. If you have a specific use case that is not working, please open a new issue with exact steps.

please make sure you read about how k8s works with the nginx ingress controller. There are limitations that @develar has outlined in hsi followup comment.

**Comment by averri** [comment]
I'm having a similar issue, I did not create a bug because it's not clear to me if that is the case:
https://forums.rancher.com/t/ingress-running-on-localhost-not-working-properly/40475
