### ISSUE TITLE
Load Balancer is always Pending

### ISSUE THREAD

**Issue by totogo** [rancher/rancher#14424]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS China

**Steps to Reproduce:**
1. Setup a cluster in AWS EC2 in China region
2. Launch a Helm app in Catalog Apps
3. Find Moodle and Launch it

**Results:**
In AWS the Load Balancer is created automatically and the app is already accessible through the Load Balancer. But in Rancher Load Balancer, it is still showing Pending. Here are some information copied from the API result:
```
"projectId": "c-krcvz:project-n5l5k",
"publishNotReadyAddresses": false,
"selector": {
    "app": "moodle-moodle"
},
"sessionAffinity": "None",
"state": "pending",
"transitioning": "yes",
"transitioningMessage": "Load Balancer is being provisioned",
"type": "service",
"uuid": "392a686c-80bf-11e8-ab71-02ee297771fe",
"workloadId": null
```

**Comment by superseb** [comment]
Did you configure the Kubernetes Cloud Provider?
https://rancher.com/docs/rancher/v2.x/en/faq/technical/#why-is-my-layer-4-load-balancer-in-pending-state and https://rancher.com/docs/rancher/v2.x/en/concepts/clusters/cloud-providers/

**Comment by superseb** [comment]
Does the IAM role attached to the instances have the permissions as stated in the docs?

If you can provide a `kubectl describe svc -n yournamespace`, I can take a look.

**Comment by totogo** [comment]
Yes, I just copied the permission from the document. It's attached to the Rancher server and Cluster instance. But one thing I am not so sure. Since you have the last 2 statements, it provides full permissions on EC2  and ELB resources, why do you still need the first 3 statements? The last 2 already covers the first 3. 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ec2:Describe*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "ec2:AttachVolume",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "ec2:DetachVolume",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": ["ec2:*"],
            "Resource": ["*"]
        },
        {
            "Effect": "Allow",
            "Action": [ "elasticloadbalancing:*"],
            "Resource": ["*"]
        }
    ]
}
```

And here is the information you asked:
```
> kubectl describe svc -n moodle
Name:                     moodle-moodle
Namespace:                moodle
Labels:                   app=moodle-moodle
                          chart=moodle-2.0.0
                          heritage=Tiller
                          io.cattle.field/appId=moodle
                          release=moodle
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"moodle-moodle","chart":"moodle-2.0.0","heritage":"Tiller","release":"...
Selector:                 app=moodle-moodle
Type:                     LoadBalancer
IP:                       10.43.35.116
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  32391/TCP
Endpoints:                10.42.0.184:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  31359/TCP
Endpoints:                10.42.0.184:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**Comment by blackholegalaxy** [comment]
I had the same problem on GCE. 

To reproduce, you can simply run the openvpn helm chart. By default, the chart will try to expose a LoadBalancer L4. The openvpn pod takes a long time to start and become reachable, until RSA keys generation.

When the chart is deployed, here are the steps you can see:
 - Creation of the pod along with a LoadBalancer L4 service.
- The LB tries to be created but the pod takes a long time to become ready
- The LB is stuck on both google cloud console and Rancher
- The pod finally become reachable and fully started
- Even after the pod is reachable, the LB is kept stuck at pending.

Then, the only way to get the LB to start is then to kill the LB service and deploy another by hand. Since the pod is reachable, the LB is created without any problem.

**Comment by biels** [comment]
Same thing here

**Comment by jasonfhill** [comment]
I had the same problem in AWS EC2 us-east-1. I had to add permissions for CreateServiceLinkedRole.
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "arn:aws:iam::XXXXXX:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing"
        }
    ]
}`

**Comment by satomic** [comment]
@jasonfhill thx! your solution solved my problem, fantasitc!
btw,  hi, @superseb I think the docs should be updated by adding the `iam:CreateServiceLinkedRole` authority, so the policy json content should be
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ec2:Describe*",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "ec2:AttachVolume",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "ec2:DetachVolume",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": ["ec2:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["elasticloadbalancing:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["iam:CreateServiceLinkedRole"],
      "Resource": ["*"]
    }
  ]
}
```
in the rancher1.6 docs: https://rancher.com/docs/rancher/v1.6/en/kubernetes/providers/#adding-hosts 
and rancher2.0 docs: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/cloud-providers/

**Comment by deniseschannon** [comment]
If you are still facing issues with the correct IAM policy (corrected in docs) and added the AWS cloud provider, please reopen a new issue.

**Comment by Hantse** [comment]
Same issue for me.

**Comment by tegk** [comment]
Same here

**Comment by averri** [comment]
The same issue still occurs on Rancher 2.3.4. I have installed on custom servers (VMs). There is something fundamentally wrong with this feature, there are a big number of people reporting the same problem. The Rancher UI should inform the cluster operator about the problem, instead of showing the UI stuck in **Pending**.

![image](https://user-images.githubusercontent.com/1898447/73163549-21178000-40e8-11ea-98dc-e21478699172.png)

**Comment by cove9988** [comment]
Any update for the L4 Load balancing pending issue?

**Comment by gp187** [comment]
Same problem on EC2 cluster

**Comment by luchinskyvidal** [comment]
any solution for this isuue?, Same problem in my rancher on DigitalOcean

**Comment by Arjetakrasniqi** [comment]
Does anyone have a solution for that ?

**Comment by vincent99** [comment]
There is no general "problem" or "issue" here.  Vanilla kubernetes (and therefore Rancher/RKE clusters) do not come with any implementation to handle services with type=LoadBalancer by default. And there is no good way to tell for a given cluster if something will handle them if you request the creation of one.

Cloud Providers plug-ins can be installed (if not built in) and configured to add this support.  They work for the specific provider your nodes are in and create some their particular implementation of a balancer and update the status on the service to reflect what was created.

For bare-metal/on-premise  you probably want something like MetalLB instead.  K3s ships with a very minimal implementation that uses available ports on the nodes to satisfy LB requests for the simplest use cases.

If these are not configured, or not working correctly, then the service stays in pending state forever because that is their initial state.. waiting for someone to do something.

**Comment by Med-All** [comment]
Is there any documentation or tutorial how to set this up then?

**Comment by Terkea** [comment]
same here
```
﻿apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: traefik
    chart: traefik-1.0.0
    heritage: Tiller
    io.cattle.field/appId: traefik
    release: traefik
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:chart: {}
          f:heritage: {}
          f:io.cattle.field/appId: {}
          f:release: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:release: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-10-05T22:52:03Z"
  name: traefik
  selfLink: /api/v1/namespaces/kube-system/services/traefik
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31621
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 32238
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: traefik
    release: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by diegohsi** [comment]
`kubectl get svc -n traefik`
```
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
traefik   LoadBalancer   10.43.224.210   <pending>     80:31099/TCP,443:30553/TCP   11m
```
The same here.

I have an on-premise cluster and followed this blog https://traefik.io/blog/install-and-configure-traefik-with-helm/. I am showing you how my CloudFlare configuration is doing. I have a wildcard pointing at my worker nodes.

![image](https://user-images.githubusercontent.com/1406648/103144919-1ad2bf00-4710-11eb-8e7a-8145cb4a506c.png)

**Comment by VladimirTambovtsev** [comment]
Same with MetalLB on treafik. Could we improve debugging process somehow?
