### ISSUE TITLE
Make ipsec's healthcheck optional 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#14587]
* Introduce a global flag on cattle side enabling healthcheck on ipsec service (false by default). Propagate the flag to the metadata. Trigger update on flag change. 

* `connectivity-check` should report health state only if it's true and ipsec is active, else it'd be healthy.

**Comment by sangeethah** [comment]
Reopening this issue after testing with latest changes made to set peer-connection-timeout to 60000.

1. Added a new environment with 3 hosts.
2. Able to query for the above setting in metadata for ipsec -  rancher-metadata/latest/services/ipsec/metadata/ipsec.service.enable.healthcheck which gets returned as "false" as expected.
3. when cross host communication is broken between 2 hosts in the setup (by blocking traffic to other hosts using iptables (iptables -I FORWARD -d -j DROP) say between h1 and h2 ,we see the connectivity check report peers becoming unreachable. 
But I see ipsec report unhealthy for all 3 hosts in the setup .

Expected behavior in this case should be that all the hosts continue to be reported as "healthy" since ipsec.service.enable.healthcheck is false.

**Comment by sangeethah** [comment]
Tested with 1.6.19-rc7 build with  ipsec-connectivty-check having peer-connection-timeout set to 6000.

1. There is a new setting - v2-beta/settings/ipsec.service.enable.healthcheck set to "false".
2. Able to query for the above setting in metadata for ipsec/router/connectivity-check-metadata/latest/services/ipsec/metadata/ipsec.service.enable.healthcheck
3. With default settings , when cross host communication is broken (by blocking traffic to other hosts using iptables (iptables -I FORWARD -d -j DROP) , we see the connectivity check report peer becoming unreachable.But ipsec continues to report healthy is this case as expected.
4. With cross host communication still broken , change the ipsec.service.enable.healthcheck settings to "true". After few seconds of changing the settings , ipsec container reports state as "Unhealthy" as expected.
5. Restore cross host communication. Ipsec containers which were reported as being "unhealthy" now report "healthy" state as expected.
6. Break cross host communication between few hosts in the set up when ipsec.service.enable.healthcheck settings to "true" and wait for , ipsec container reports state as "Unhealthy" .
7. change the ipsec.service.enable.healthcheck settings to "false".
ipsec container that reports state as "Unhealthy" , will now report state as being "healthy", which is expected.
