### ISSUE TITLE
Add more complex GKE Options

### ISSUE THREAD

**Issue by nathan-jenan-rancher** [rancher/rancher#14634]
Allow the following options to be passed into GKE.

- basic authentication
- client certificate
- labels
- vpc-native
- Automatically create secondary ranges
- Master authorized networks
- maximum number of nodes per pool
- network policy config (GKE appears to ignore this value and always sets `disabled` to `true`)

**Comment by davidnuzik** [comment]
@nathan-jenan-rancher or @fyery-chen or @loganhz please explain what resourceFields were added to googleKubernetesEngineConfig. I should not have to look at code to try to figure out what we added for each bullet point listed in the issue description. For example I don't see vpc-native in googleKubernetesEngineConfig
Can we just update the original issue description here saying what each resourceFields is for each of these?

> Allow the following options to be passed into GKE.
> 
> * basic authentication
> * client certificate
> * labels
> * vpc-native
> * Automatically create secondary ranges
> * Master authorized networks
> * maximum number of nodes per pool
> * network policy config (GKE appears to ignore this value and always sets `disabled` to `true`)

**Comment by loganhz** [comment]
Thanks @davidnuzik 

@fyery-chen please list it

**Comment by davidnuzik** [comment]
Not sure if this is helpful. This is diff from older to new when I create GKE cluster (POST).
I know much is not for this issue as it is related to other issues.
This at least helped me spot what has changed when submit create GKE cluster form via UI.
```
  diskType: "pd-standard"
  displayName: ""
  driverName: "googlekubernetesengine"
  enableAutoRepair: false
  enableAutoUpgrade: false
  enableMasterAuthorizedNetwork: true
  enableNodepoolAutoscaling: false
  enablePrivateEndpoint: false
  enablePrivateNodes: true
  gkeCredentialPath: ""
  imageType: "UBUNTU"
  ipPolicyClusterIpv4CidrBlock: "10.128.0.1/11"
  ipPolicyClusterSecondaryRangeName: null
  ipPolicyCreateSubnetwork: true
  ipPolicyNodeIpv4CidrBlock: ""
  ipPolicyServicesIpv4CidrBlock: "10.128.0.1/18"
  ipPolicyServicesSecondaryRangeName: null
  ipPolicySubnetworkName: ""
  issueClientCertificate: true
  kubernetesDashboard: false
  labels: []
  legacyAuthorization: false
  localSsdCount: 0
  maintenanceWindow: ""
  masterAuthorizedNetworkCidrBlocks: ["10.0.0.0/8"]
    0: "10.0.0.0/8"
  masterIpv4CidrBlock: "10.128.0.0/17"
  maxNodeCount: null
  minNodeCount: null
  name: ""
  network: "default"
 nodePool: ""
  nodeVersion: ""
  oauthScopes: ["https://www.googleapis.com/auth/devstorage.read_only",…]
    0: "https://www.googleapis.com/auth/devstorage.read_only"
    1: "https://www.googleapis.com/auth/logging.write"
    2: "https://www.googleapis.com/auth/monitoring"
    3: "https://www.googleapis.com/auth/servicecontrol"
    4: "https://www.googleapis.com/auth/service.management.readonly"
    5: "https://www.googleapis.com/auth/trace.append"
  preemptible: false
  resourceLabels: ["clusterlabelkey=labelvalue"]
    0: "clusterlabelkey=labelvalue"
  serviceAccount: "redacted"
  subNetwork: null
  taints: []
  useIpAliases: true
  zone: "us-central1-f"
  id: "c-c5sz8"
  internal: false
```

**Comment by fyery-chen** [comment]
@davidnuzik 

* basic authentication -- doesn't support configure
* client certificate --- related to field issueClientCertificate
* labels 
   node labels --- related to field labels
   cluster labels --- related to field resourceLabels
* vpc-native --- related to field useIpAliases
* Automatically create secondary ranges  --- default support, do need to configure
* Master authorized networks --- related to field enableMasterAuthorizedNetwork and masterAuthorizedNetworkCidrBlocks
* maximum number of nodes per pool --- related to field enableNodepoolAutoscaling, maxNodeCount and minNodeCount
* network policy config (GKE appears to ignore this value and always sets `disabled` to `true`) --- doesn't support configure because it is invalid

**Comment by davidnuzik** [comment]
@fyery-chen Thanks! This helped a great deal.

**Comment by jiaqiluo** [comment]
The following areas are tested while testing GKE private cluster as this issue describes: https://github.com/rancher/rancher/issues/13980  
* vpc-native
* Automatically create secondary ranges
* Master authorized networks

The following areas are tested:
* labels
  - node labels
  - cluster labels 
* client certificate
* maximum number of nodes per pool

The followin areas are not tested becaue they do not supprt configure
* basic authentication -- doesn't support configure
* network policy config (GKE appears to ignore this value and always sets `disabled` to `true`) --- doesn't support configure because it is invalid
