### ISSUE TITLE
support fluentd aggregator target

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#14652]
1. support fluentd aggregator target so the user could aggregate log by them self.

**Comment by cloudnautique** [comment]
@aiwantaozi 
It looks like the backend stores the rendered Fluentd in config maps with potentially sensitive information. Can we move it to secrets?

In the UI:
In examples where a host:port combo are needed we should show something more like: `example.com:1234`  as suggestion text. (Changing it here means were should be consistent everywhere.

When is username / password required instead of server key, or are they used together. 
The shared key is a secret/Password type of data? Should probably make it a password field.

In the event that there is only 1 server why would weight be anything other then 100?

Standby -> `Use as Standby Only`

If a certificate is not added, can you still use TLS? I think we need the TLS transport option. (We should make sure we 
`trusted server certificate` -> `CA Certificate PEM`

**Comment by aiwantaozi** [comment]
@cloudnautique 
Re configmap to secret: I will change to secret

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.4

All test cases passed for fluentd logging target, with fluentd configured as an aggregator.
