### ISSUE TITLE
Add support for `apps/v1` workloads (Kind: Deployment)

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#14682]
kind/enhancement
area/api

**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent:

--------

>Kind: `Deployment`
APIVersion: `apps/v1`

are **not** shown as _Rancher workloads_, whereas

>Kind: `Deployment`
APIVersion: **`apps/v1beta2`**

**are**.

I'm writing an operator and want to be able to use stable apps api.
I need to work around with this to get the visibility, I need: https://gist.github.com/superseb/3a9c0d2e4a60afa3689badb1297e2a44

**Comment by blaggacao** [comment]
ping @deniseschannon

**Comment by alena1108** [comment]
@blaggacao `apps/v1` is supported for 1.9+ clusters. Given that we use the same client to talk to users clusters of diff versions, we will continue using `apps/v1beta2` till support for 1.8 clusters is "hard" dropped

**Comment by david-maumenee** [comment]
Since Rancher v2.1.3, it seems that K8s 1.8 is no more supported. 
![rancher-k8s-version](https://user-images.githubusercontent.com/4135760/49785372-a8593700-fd20-11e8-9cab-165b7246fe9b.png)
Rancher could support apps/v1 but it doesn't, this error message apear : 
/!\ the API version in the data (apps/v1) does not match the expected API version (apps/v1beta2)

**Comment by deniseschannon** [comment]
This is now supported.
