### ISSUE TITLE
Ping Federate - Local users not listed correctly under authorized user list

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14765]
**Rancher versions:**
Master 7/25

**Steps to Reproduce:**
Create a local standard user
Enable ping federate.
Set site access level to "Allow members of Clusters, Projects, plus Authorized Users and Organizations"
Add local user as authorized user.

**Results:**
Local user is not displayed correctly. Shows user ID instead of display name.

Ping Federate

![screen shot 2018-07-25 at 3 20 34 pm](https://user-images.githubusercontent.com/38012481/43231292-9db915f8-9020-11e8-8619-77d5e9ea05c1.png)

Vs.

AD

![screen shot 2018-07-25 at 3 35 29 pm](https://user-images.githubusercontent.com/38012481/43231279-91b916a4-9020-11e8-9f1e-aaba96989c39.png)

**Comment by westlywright** [comment]
@adingilloRancher similar to the other issue (rancher/rancher#14799), can you retest with latest? I believe this was fixed by a backend change.

<img width="1299" alt="screenshot 2018-07-31 12 28 13" src="https://user-images.githubusercontent.com/858614/43482358-5907cce6-94bd-11e8-8bbe-756362a02e7f.png">

**Comment by adingilloRancher** [comment]
Master 8/2

User is correctly listed.
