### ISSUE TITLE
ADFS - Removed member of cluster can still view but cannot access/use cluster

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14857]
**Rancher versions:**
Master 7/30

**Steps to Reproduce:**
Enable ADFS
Create a new cluster.
Assign a user to cluster as a member. 
In a new session, login as assigned user. Cluster will be listed.
Remove user from cluster. 
Logout of your second session.
Log back in as assigned user.

**Results:**
User still sees removed cluster.

**Comment by mrajashree** [comment]
I see the same happening for Active Directory too. I think it's because when you add a standard member to a cluster, it creates a user with login access. When you remove the member, user is still not removed and still has login access. But I don't know why user can still see the removed cluster. But this is not something ADFS specific.

**Comment by mrajashree** [comment]
The only way I could repro (not specific to ADFS) :
Added 2 clusters, added testgroup1 as a member of cluster 1. Added testuser2 (member of testgroup1) as a member of cluster 2.
Now even after I remove testuser2 from cluster 2's member list, testuser2 can still login since testuser2 is a member of testgroup1. Maybe that was the case with your setup too?
Although I don't know why testuser2 can still see the cluster. But the same happens in case of AD and I think would happen for other auth providers too, so it's not ADFS specific

**Comment by adingilloRancher** [comment]
Master 6/8

User no longer has visibility to unassigned cluster.
