### ISSUE TITLE
ADFS - User in 1k+ groups is unable to login.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14870]
**Rancher versions:**
Master 7/31

**Steps to Reproduce:**
Enable ADFS auth
Site site access to unrestricted.
Attempt to login as a user in 1k+ groups (multipleuser1 from our test ad)

**Results:**
User is unable to login. Tried even adding them as an authorized user, still unable to login. Any other user I attempt to log in with unrestricted access is able to login without any issues. 

![screen shot 2018-07-31 at 9 05 51 am](https://user-images.githubusercontent.com/38012481/43471882-f8310368-94a0-11e8-8b6a-f2326c2237ac.png)

**Comment by mrajashree** [comment]
When I try the same use case for PingFederate, the user is able to login and all 1000 groups get correctly listed as groupPrincipals. The backend is same for Ping and ADFS so this should have worked for ADFS too. But I could repro the bug for ADFS, and on turning on debug logs, the SAMLResponse status code is `urn:oasis:names:tc:SAML:2.0:status:Responder`, which according to SAML core spec means `The request could not be performed due to an error on the part of the SAML responder or SAML authority`
So something is wrong on our ADFS side, maybe a size limit

**Comment by deniseschannon** [comment]
Testing with 950 groups allows the user to log in.

It seems that ADFS does not allow being able to configure a user with more than 1000 groups. 

Since the same use case works with PingFederate, which uses the same backend implementation works, the conclusion is that this is a size limit for ADFS.
