### ISSUE TITLE
Rancher UI incomplete for Ingress Creation when using cert-manager for issuance

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14924]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

This is perhaps a perception problem combined with a technical problem. When looking at the official chart library for Rancher, the cert-manager (lets encrypt) shows up.  When you look at deploy it the readme suggests that all that is needed is to simply add the `kubernetes.io/tls-acme=true` annotation to the ingress rule to have Lets Encrypt certificates generated automatically. 

For the technical side of things the appropriate tls spec information is not added to the ingress rule.

For cert-manager to work properly, the following information has to be at minimum present on the ingress definition.  Without this being set on the ingress, cert-manager is unable to generate certificates for the ingress rule, even if the ingress rule has the appropriate annotations.

```yaml
spec:
  tls:
  - hosts:
    - some-host.some-domain.com
    secretName: cert-manager-some-host
```

**Note:** this can be added by editing the YAML. However I had to figure this out after much trial and error, neither the Rancher UI nor the Chart for cert-manager seems to indicate this is necessary.

## Expected Behavior

I would expect rancher either expose an option to indicate that the TLS spec information should be added based on the hostname that was configured on the ingress rule, or have rancher do it automatically.

**Comment by stieler-it** [comment]
I was struggling with this the whole day, as I saw that the Racher chart for cert-manager seems to automate all the manual steps that are explained everywhere else. This seems to be the missing part, thanks a lot!

Since I was trying to secure another chart application (Artifactory) I wanted to provide the configuration to the chart values, which worked out like that:

```
# Use Ingress instead of default nginx in the chart
nginx.enabled=false
ingress.enabled=true
ingress.hosts[0]=artifactory.hostname.tld
# For cert-manager
ingress.annotations.kubernetes\.io/tls-acme=true
ingress.tls[0].secretName=cert-manager-artifactory
ingress.tls[0].hosts[0]=artifactory.hostname.tld
```

Some more (off-topic) information:
As stated elsewhere, both the "Certificate" and the Ingress TLS configuration looks broken in Rancher UI, but it worked. Also, switching from letsencrypt "staging" to "production" did not lead to cert-manager fetching a new certificate ("the current one is still valid"). Finally, I'm not sure if the automatic fetching will work out for multiple hosts. AFAIK a TLS server usually serves only one certificate for all hosted domains, which are then selected using SNI. I'll try that next.

**Comment by splattner** [comment]
thanks a lot!!

**Comment by guangbochen** [comment]
added TLS spec notes to the app-readme for both latest and v0.3.2 cert-manager.
