### ISSUE TITLE
Pausing Orchestration Does Not Stop Scheduling

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14935]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

I was unable to find documentation around orchestration pausing, so forgive me if my understanding is incorrect.

After pausing a workload, if you delete the PODS under the workload, the PODS just reappear. 

**Expected Behavior:** Pausing Orchestration would prevent PODs from being re-scheduled in any capacity until orchestration is resumed.

**Comment by vincent99** [comment]
Pause allowed you to stack up multiple edits (e.g. adding 2 sidekicks and changing the existing container) so that they will all be applied at once on resume instead of repeatedly making new replicasets (Which makes new pods).

It does not affect the existing replicaset, if you delete a pod or a healthcheck fails the pots is replaced as normal.

There is no exact equivalent to 1.x.

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment

**Comment by ekristen** [comment]
Thanks @vincent99 I figured there was a reasonable explanation.
