### ISSUE TITLE
Cluster goes to "provisioning" state with error from server  

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#14996]
**Rancher versions:**
rancher/server or rancher/rancher: upgrade from v2.0.6 to master

**Steps to Reproduce:**
1. Create a DO cluster in v2.0.6 with k8sv1.8.10 or v1.8.11
2. Upgrade to master

Cluster goes to "provisioning" state for a brief time with the below error and eventually gets to active state
<img width="1448" alt="screen shot 2018-08-01 at 1 42 52 pm" src="https://user-images.githubusercontent.com/18536626/43603359-962d298c-9647-11e8-86ed-18cb17357f5d.png">

**Comment by cjellick** [comment]
Upon upgrading rancher/rancher, a new, upgraded version of the cluster agent needs deployed in the cluster. Deploying that agent is part of provisioning, so, the state of the cluster returns to provisioning while this is occurring. The error message occcurs because the connection from rancher to cluster is breifly unavailable.

So, this is all functioning as expected

**Comment by cjellick** [comment]
@soumyalj If you have any more questions or concerns, let me know. Otherwise, can you close this?
