### ISSUE TITLE
Namespace edit not possible

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#15038]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.6

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): 1.10.5

**Docker version: (`docker version`,`docker info` preferred)**
17.3.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

4.4.0-131-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMs on Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher (internal DB)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Chose project of k8s Cluster > Namespaces > View/Edit YAML > Make a change or "Read from File"

**Results:**
Changes will not take effect (neither when editing the file nor when uploading a new file)

**Comment by janeczku** [comment]
I have always found it weird that `View/edit YAML`  on a namespace does not return the YAML of the namespace resource but returns the equivalent of `kubectl get all --namespace X`. It's unexpected from user point of since for all other resources the `View/edit YAML` action will return the resource itself. It also prevents from editing the namespace resource itself, e.g. adding labels, etc...

**Comment by vincent99** [comment]
This was intentional and mirrors exporting a stack in 1.x, as there is no other way to bulk export.  And other than the occasional annotation, there is virtually nothing on the namespace itself to view or edit.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/23348
