### ISSUE TITLE
Make vSphere cloud provider configurable in the UI

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#15089]
**Rancher versions:**
v2.0.7

Currently the UI lacks integration with vSphere cloud provider.
When deploying a vSphere cluster, users have to select the `Custom` cloud provider option, then manually edit the cluster YAML to specify the configuration parameters.

Having to select a `Custom` instead of a `vSphere` provider while deploying a vSphere cluster feels counter-intuitive and results in users skipping that configuration step and expecting stuff to just to work.

Manually editing the YAML is not user friendly and - since the configuration consists of up to 5 subsections - prone to misconfiguration, which will result in the cluster to not provision successfully at all.

![vsphere-cloud-provider](https://user-images.githubusercontent.com/3813921/44209961-4f5c0680-a165-11e8-913a-72600079f1f9.png)

**Proposal:**
The UI should be augmented to allow users to select the `vSphere` cloud provider option and then provide the required configuration by filling out a configuration form that is being validated before  the cluster is created. Basically mirror how it's implemented for the Azure cloud provider.

**Comment by snowyfox** [comment]
Any reason why this was closed? I just found #14724 after searching for a few hours trying to figure out why I couldn't get persistent volumes to work with vSphere. That issue was closed, pointing over here to this one. Now this issue was closed a few months ago, along with no explanation as to why, and I couldn't find anything else related. Was this possibly closed by mistake?
