### ISSUE TITLE
Supported for cilium 

### ISSUE THREAD

**Issue by sunface** [rancher/rancher#15087]
Hi there, is there any plan for cilium supporting?

**Comment by curantes** [comment]
There are a lot of nice features in 1.6 release of cilium. It would be nice if cilium support would be integrated to rancher.

https://cilium.io/blog/2019/08/20/cilium-16/

**Comment by styk-tv** [comment]
Guys, what is the progress on this (would be great to have this as standard set AirGapped pull)

https://cilium.io/blog/2020/02/18/cilium-17/

(from article above)

Hubble: We've heard lots of positive feedback on Hubble since the announcement. To make cluster connectivity easier to visualize and debug, we've released a new Hubble UI as open source so you can tweak and extend it too! We've also been working on various improvements to the core Hubble implementation, including better correlation between network flow data and Kubernetes resources. (More details)

Cilium Cluster-wide Network Policies: The 1.7 release brings the much-anticipated Cluster-wide CNP feature. This allows users to apply baseline network policies which apply to pods across the cluster, regardless of the namespace that the pod resides in. (More details)

**Kube-proxy replacement with Direct Server Return**: As presented at Kubecon US 2019 and FOSDEM 2020, this release rounds out the full service feature set for replacing kube-proxy and additionally adds support for Direct Server Return (DSR). This further improves the latency and performance of the kube-proxy replacement in Cilium. Moreover, our kube-proxy replacement comes out of beta and is automatically enabled in environments with newer kernels. (More details)

**Extending L7 policies with TLS introspection**: We've added support to Cilium to configure Envoy TLS certificates via Kubernetes resources or local files. This allows Cilium to transparently observe HTTP calls and enforce API-aware policies on TLS-encrypted sessions. (More details)

**L7 visibility annotations for pods**: Previously, to gain L7 visibility into traffic in the cluster, users would need to write network policies that put pods into a default deny posture. Visibility annotations now allow users to gain L7 visibility into network traffic first, then subsequently craft full network policies using these insights. (More details)

**Pure Go eBPF library**: This is the first Cilium release to begin using the pure Go eBPF library co-written between the Cilium community and CloudFlare. This streamlined library already allowed Cilium to jettison CGo, improving performance and reducing binary sizes. (More details)

**Improvements to scalability** through Kubernetes EndpointSlice support and Cilium agent improvements, development on upstream Linux, running our testing environment on managed Kubernetes, distributing Cilium via Helm repositories... and much more! For more highlights, see the 1.7 Release Highlights.

**Comment by mmack** [comment]
Guys please consider adding cilium. My dream setup would be k8s 1.18 with dual stack and no kube-proxy. Cilium doing all the stuff... The cilium hubble visibility into the network is still unbeaten.

**Comment by bentastic27** [comment]
The install is pretty easy and is doable via `addon_includes`:

```
rancher_kubernetes_engine_config:
  addons_include:
    - https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml
```

The main rub I see is the [bpf mount](https://docs.cilium.io/en/v1.8/concepts/kubernetes/requirements/#mounted-bpf-filesystem) for production clusters, but perhaps that can be done via a "cni install" init container or similar.

**Comment by deniseschannon** [comment]
This will be coming as part of v2.6 with RKE2 provisioning and we will track support of this issue: https://github.com/rancher/rancher/issues/32381
