### ISSUE TITLE
Add UI support for cluster capabilities 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#15105]
https://github.com/rancher/rancher/issues/12422

**Comment by loganhz** [comment]
Backend is merged in master.

**Comment by davidnuzik** [comment]
Related issue - #16785

Related UI issues:
#16783
#16784

**Comment by davidnuzik** [comment]
Needs testing, #16785 will be resolved later and is only loose end remaining in this area.

**Comment by davidnuzik** [comment]
Note: All areas have been validated except for IngressCapabilities (previously IngressController); it's possible there may be a bug in this area and this area is being tested further.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (12/14/18)
Confirmed new UI features EXCEPT for the new row added to the add ingress page regarding ingressControllers in PR https://github.com/rancher/ui/pull/2364 (now called ingressCapabilities). This is not working and an API bug was entered around this: #17140 and EXCEPT for NodePortRange due to #16785
