### ISSUE TITLE
[FR] Add pipeline variables for workloads

### ISSUE THREAD

**Issue by stefanfritsch** [rancher/rancher#15131]
Hi,

currently a pipeline can detect a change in a repo and then run a build using a build-id for tagging the image. But as far as I see there is no way to then auto-update dependent workloads (i.e. pods running the image) to the new tag. 
This leaves only the use of `:latest` which is discouraged for kubernetes and makes updating annoying.

It would be great if you could make CD easier with one of these features:

1. Each pipeline could show a list of dependent workloads (which is problematic because pipelines are project-specific, I know) with the option to select all and update. 
2. Or allow access to some of the variables available in pipeline definition. That way you could use, e.g. `me/myimage:${CICD_EXECUTION_SEQUENCE}` to create a pod that references the latest pipeline build that you tag with the same variable.
3. The last option would profit from a quicker way to upgrade multiple deployments at once. E.g. to upgrade all instances of an auth-proxy that's used for 20 different services I have to open 20 different edit pages or hover my way through to the option to kill each pod.

Thanks,
Stefan

**Comment by gitlawr** [comment]
Since 2.1, this can be accomplished by `Deploy Yaml` Step. Please check the [docs](https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/#2-configuring-pipeline-stages-and-steps) for details.

**Comment by stefanfritsch** [comment]
I don't think that's a good solution.

Don't get me wrong, I'm grateful for your answer and it definitely helps with my problem.

But, it basically means that all your workloads have to be created and updated from image pipelines. This turns the rancher UI into a glorified editor for yaml that you then have to deploy to a repository. It also means that the same docker image will be created 10 times for different deployments.

OTOH if there was a pipeline field in the Deploy Workload dialog that would give you access to the current CICD-variables of that pipeline everything would fit into the current rancher workflow.

**Comment by cloudnautique** [comment]
@stefanfritsch, I get what you are saying. Sounds like you would like to be able to script something and have kubectl config files available to script deployments and updates? 

We had the web hook capability in Rancher 1.6, where web hooks from Docker up would upgrade services based on selector labels. It worked, but only for a single tag, which as noted above isn't spectacular. 

I'm not sure we are going to or need to do the same thing for 2.x, because of projects like this:
https://github.com/keel-hq/keel

Would be interested in hearing additional thoughts.
