### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by lly835** [rancher/rancher#15262]
<img width="1244" alt="qq20180827-210012 2x" src="https://user-images.githubusercontent.com/2225913/44695492-016cca00-aaa6-11e8-9962-7e4b9e11edd4.png">

**Comment by loganhz** [comment]
@lly835 the error code is 500. Please look at what the error is in chrome network tab and console log tab

**Comment by pjmazenot** [comment]
I'm getting this error too.

Here is what I get in the Network tab : 
`(Opcode -1)`

And in the console log:
`component.js:102 WebSocket connection to 'wss://[container_url]/exec?container=[container_name]&stdout=1&stdin=1&stderr=1&tty=1&command=%2Fbin%2Fsh&command=-c&command=TERM%3Dxterm-256color%3B%20export%20TERM%3B%20%5B%20-x%20%2Fbin%2Fbash%20%5D%20%26%26%20(%5B%20-x%20%2Fusr%2Fbin%2Fscript%20%5D%20%26%26%20%2Fusr%2Fbin%2Fscript%20-q%20-c%20%22%2Fbin%2Fbash%22%20%2Fdev%2Fnull%20%7C%7C%20exec%20%2Fbin%2Fbash)%20%7C%7C%20exec%20%2Fbin%2Fsh' failed: Error during WebSocket handshake: Unexpected response code: 500`

It seems to be node related (vs container related) because for the same workloads on different nodes if I request the shell it works for some nodes and some not.

**Installation info**

Rancher versions:
rancher/rancher: v2.0.8
rancher/rancher-agent: v2.0.8

Infrastructure Stack versions:
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.1

Docker version: (docker version,docker info preferred)
Client:
Version: 17.03.2-ce
API version: 1.27
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 03:35:14 2017
OS/Arch: linux/amd64

Server:
Version: 17.03.2-ce
API version: 1.27 (minimum version 1.12)
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 03:35:14 2017
OS/Arch: linux/amd64
Experimental: false

Operating system and kernel: (cat /etc/os-release, uname -r preferred)
4.4.127-mainline-rev1

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
Bare-metal

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
HA rancher, internal DB

Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

**Comment by bradjones1** [comment]
@leodotcloud I'm running into a similar issue. Imported GKE clusters, and requests to tail logs or exec into containers results in a 500 error. The cluster is otherwise operational and I don't see anything particularly telling in the Rancher logs.

**Comment by bradjones1** [comment]
Same as https://github.com/rancher/rancher/issues/13149

**Comment by bradjones1** [comment]
Both of the affected clusters previously had calico network policy support enabled, prior to it being disabled for non-RKE clusters.

**Comment by bradjones1** [comment]
Fixed in my case: The issue was with a missing firewall rule for the VPC on GCP to allow ssh connections from the master to nodes. It would be great to see some more helpful logging from Rancher on the failure's origin, but this is not a Rancher error, at least in my case. https://stackoverflow.com/a/36378625

**Comment by Allen-yan** [comment]
I have the same issue , when I ran pod on a special node .
The node had a vpn client . And I can see 2 IP address on the rancher dashboard

> 

bh-k8s-worker-test03
10.10.20.53  /  192.168.42.10
--

All the pods run on this node can not access to Shell or Log

**Comment by VickyKung** [comment]
> 

have you any way to solve it ?
