### ISSUE TITLE
Auth validation test should cover special character for all kinds of possible places for users and groups

### ISSUE THREAD

**Issue by carolynhu** [rancher/rancher#15279]
like username, user'DN, groupname, can all be special characters.
To test special character for groupname, we need to create a group with special character, and add this group to allowedPrincipals. Users in this group should have access to login to rancher.

**Comment by cjellick** [comment]
Looks like this should be moved out of the zenhub revie column

**Comment by sangeethah** [comment]
@carolynhu , Can we do the following changes to the existing tests in test_auth.py ?
1. Rename all tests to start with "test_auth", so all tests can be picked up by jenkins jobs by just including "-k test_auth" option.

2. Tests from  test_ad_custom_filter.py can be put into test_auth.py  and skip this test for openldap and freeipa.

3. Also since you already have a enable/disable method  , we should not be expecting setups to be enabled to  openldap/freeipa/AD before executing the tests . This can be done with in the tests. Make sure to disable auth once the tests are done.

**Comment by sangeethah** [comment]
@carolynhu I have provided reviewed the PR and have provided some comments.

**Comment by cjellick** [comment]
removing resolved and moving back to impletment since there is feedback that needs addressed

**Comment by deniseschannon** [comment]
@sangeethah this looks like the PR was merged so it could just be closed?
