### ISSUE TITLE
Add Feature to Allow User to Change Max Limit for Pagination in Rancher 1.6.x API

### ISSUE THREAD

**Issue by massimo-cannavo** [rancher/rancher#15278]
**Rancher versions:**
rancher/server: **v1.6.21**

**Steps to Reproduce:**

Generate **4000 volumes** using the API

```
#!/usr/bin/env bash

COUNTER=0
MAX_VOL=4000

while [ $COUNTER -lt $MAX_VOL ]; do
  curl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
    -X POST \
    -H 'Content-Type: application/json' \
    -d '{
          "name": "random-volume-'$COUNTER'",
          "driver": "local"
        }' 'http://massimo.do.rancher.space:8080/v2-beta/projects/1a5/volumes'

  let COUNTER=COUNTER+1
done
```
**Results:**

The pagination is not honoring the limit for anything greater than 3000. It seems that 3000
is the maximum value that the pagination supports.

```
root@massimo-server:~# curl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
  http://massimo.do.rancher.space:8080/v2-beta/volumes?limit=2000 \
  | jq '.data[].id' | wc -l

2000

root@massimo-server:~# curl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
  http://massimo.do.rancher.space:8080/v2-beta/volumes?limit=4000 \
  | jq '.data[].id' | wc -l

3000
```

When you look at the pagination collection, you can see that the limit is set to 3000
even though 4000 was specified. 3000 seems to be the maximum allowed.

```
root@massimo-server:~# curl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
  http://massimo.do.rancher.space:8080/v2-beta/volumes?limit=4000 | jq '.pagination'

{
  "first": null,
  "previous": null,
  "next": "http://massimo.do.rancher.space:8080/v2-beta/volumes?limit=4000&marker=m3000",
  "limit": 3000,
  "total": null,
  "partial": true
}
```

**Comment by vincent99** [comment]
This is [intentional](https://github.com/rancher/cattle/blob/4a6ea6970bbd831e4fd69acf355154de2d279e24/code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/ParseCollectionAttributes.java#L31).  You can't go arbitrarily high, the entire response is buffered in memory and has to be marshaled into JSON, written out, etc.

**Comment by massimo-cannavo** [comment]
@vincent99 okay thank you. That makes sense, will relay the information to the customer.

**Comment by massimo-cannavo** [comment]
The customer has requested a feature where you can override the [Max Limit](https://github.com/rancher/cattle/blob/4a6ea6970bbd831e4fd69acf355154de2d279e24/code/framework/java-server/src/main/java/io/github/ibuildthecloud/gdapi/request/handler/ParseCollectionAttributes.java#L31) for the pagination. A setting that the user could change in the API.

**Comment by vincent99** [comment]
The limit exists for a reason.  3001 isn't going to break, but if you start going much higher you're going to run out of memory for the JVM, hit timeouts because there's no response for seconds while marshaling a multi-megabyte JSON response, break clients that have to then parse that response, etc.

The customer should request a reasonable number per page and follow the `pagination`->`next` link to get more.  It is not practical to return an unbounded number of resources in one response and it is extremely common to set a maximum limit on the number of items per page in an API and force pagination.  Usually at far less than 3,000.  e.g. GitHub is 100.

**Comment by massimo-cannavo** [comment]
@vincent99 thanks for the explanation. That makes sense. Let me talk to the customer and share this with him. Basically you just have to cycle through the next collection of items. Okay cool.
