### ISSUE TITLE
Namespace quota should not be allowed to be above Project quota.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15318]
**Rancher versions:** 2.1 master 8/30

**Steps to Reproduce:**
1.  In Add/Edit project, set a project quota
2.  Set the namespace quota higher then the project quota

**Results:**  Allows you to create/save.  Same is true when I create Namespace.  We should have API validation that checks to make sure Namespace quota is not higher then project quota.

**Comment by soumyalj** [comment]
Tested with master. 
Verified in UI and API that there is validation to ensure namespaceresource quota is not higher than project quota. 
But the error message  should specify namespaceDefaultResourceQuota instead of resource quota.
Ex: Create a new project with namespaceDefaultResourceQuota higher than the project resource quota
UI error 

<img width="1321" alt="screen shot 2018-09-10 at 3 39 37 pm" src="https://user-images.githubusercontent.com/18536626/45328218-d35ca080-b50f-11e8-90d7-d155292931cd.png">

API error below:

<img width="751" alt="screen shot 2018-09-10 at 3 38 53 pm" src="https://user-images.githubusercontent.com/18536626/45328281-20d90d80-b510-11e8-86b1-38b65aa7f93b.png">

The filedname should be `namespaceDefaultResourceQuota`

**Comment by soumyalj** [comment]
Tested with master from master build Sep 13.
Verified in UI and API that there is validation to ensure namespaceresource quota is not higher than project quota.
The error message is fixed
<img width="827" alt="screen shot 2018-09-13 at 3 01 52 pm" src="https://user-images.githubusercontent.com/18536626/45518413-43fcfa80-b766-11e8-8c75-fe9df3a4751b.png">
