### ISSUE TITLE
Review default machine specifications/instance types used when creating nodes for cluster

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15328]
* Check the default instance types used when creating nodepools for clusters (if in line with recommendation from us/cloud provider)
* Check wether we want to advise when using an instance type not suitable for etcd/controlplane usage

**Comment by martcastaldo** [comment]
@superseb Can I ask why they are not recommended? Even for a minion? I was just wondering why :)

**Comment by loganhz** [comment]
@vincent99 Can we remove  `t2.nano`, `t2.micro` and `t2.small` ?

**Comment by vincent99** [comment]
There are at least 7 more instances types than that that are <= 2GB, so _if_ you're going to do it, it should be consistent.  It should also be done for all the node and container-engine drivers, not be arbitrarily applied only to AWS.  

I don't think _requiring_ 2 cores and > 2 GB is particularly reasonable though; Maybe a warning that it's not "recommended" if you pick < 2GB + control/etcd roles or something.  But GKE, DO, etc allow 1 GB (or smaller) worker nodes and that might be enough for some user's workload.

Also the default sizes are usually what we use ourselves, so requiring > 2GB will just cost us money.

**Comment by superseb** [comment]
This was created after reports of creating machines and then failing provisioning due to out of resources, especially because its not always easy to troubleshoot as out of resources can give any logging. But I agree on the generic approach, if we want to do this, we can decide if we want to add "recommended" or possibly document it. When researching requirements last month, the minimal requirement for worker would be 1CPU/1GB but if you look at EKS supported instance types:

```
    Default: t2.medium
    AllowedValues:
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.nano
    - t3.micro
    - t3.small
```

So I would rewrite this to generic node requirement which could either be fulfilled by doing it overall for all providers or just a check for defaults (we default to `t2.medium` already for AWS) and documentation.

**Comment by vincent99** [comment]
`t3.nano` is on that list and 512 MB so that sounds like justification for _not_ restricting values that can work to me...

GKE also has `f1-micro` (which is usually 600 MB but the GKE page says 1 GB).

DO has the small "flexible" available (1 GB / 3 vCPU, or 2/2, or 3/1 for $15/mo).

Azure only shows 2+ GB types.

For all the standard providers we know (or could know) how much RAM the template is for and act accordingly.

I'd suggest:
  - For kontainer-engine, leave as-is, the provider has decided what they want to offer.
  - Continue allowing choosing any size on a node-template.
  - Possibly append "(for worker only)" to the label in the dropdown for ones < 2gb.
  - On node-template create/edit, save annotations of CPU + memory onto the template (this is the only time we'll have easy access to the API to know it)
  - For add RKE/node-driver cluster, read the annotation and show a warning if you pick a node pool with role=etcd or controlplane and a template < 2GB each.
  - If you really want to, let them continue anyway.
