### ISSUE TITLE
helm set value and all the value is considered a string

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#15344]
**Rancher versions:**
rancher/master 08/31

helm install chart use --set-string, all the value will be considered a string. This won't be a problem for just rendering templates because they just render string, but the thing would break if you expect to compare a boolean or number.

**Comment by cjellick** [comment]
@guangbochen do you have a specific test case that you can add to this ticket so that QA can verify?

**Comment by guangbochen** [comment]
sure, please verify with the `wordpress` chart and using different input types like boolean and string, and make sure they all passed correctly, thanks.

**Comment by cjellick** [comment]
@maxkorp to validate

**Comment by maxkorp** [comment]
So, if I include all values within `--set-string` then they're all interpreted as strings, but that would be expected, since we're explicitly telling helm that they are string values. I am able to use both `--set-string` and `--set` in one command to avoid any issues

For example, this breaks:
```
helm install --name onlySetString --set-string allowEmptyPassword=false,wordpressUsername=1234567 
```
But we are explicitly telling helm that false is a string. 

I can run the following without issues. 
```
helm install --name bothSetAndSetString --set allowEmptyPassword=false --set-string wordpressUsername=1234567 
```

Since we're passing allowEmptyPassword through `--set`, it interprets normally

@guangbochen Is there somewhere I'm not aware of that we're calling everything with `--set-string`? Or were you talking about doing it from the command line?

**Comment by cjellick** [comment]
@maxkorp sync with me tomorrow before you close

**Comment by guangbochen** [comment]
@maxkorp sure, this should be done via UI, and the case you have mentioned above are both correct, the UI is expected to working as same as the second approach with `-set`, thanks.

**Comment by maxkorp** [comment]
Confirmed working as expected.

1. Open a project in rancher
2. Choose catalog apps
3. Click deploy
4. Choose wordpress app
5. set `Install MariaDB` to false
