### ISSUE TITLE
We need to cache the api ui files in rancher

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#15378]
For now, we are using the specific api-ui version in norman, But we should cache the api-ui files inside Rancher server in case we will do air gap rancher setup.

**Comment by JasonvanBrackel** [comment]
@loganhz @deniseschannon Will this be backported to 2.1.1?

**Comment by deniseschannon** [comment]
@JasonvanBrackel 2.1.1 is already at code freeze, but we can backport it to v2.1.2 (cc: @alena1108)

**Comment by michaelkoro** [comment]
Will it be available at v2.1.2 ? When is it due ?

**Comment by sangeethah** [comment]
@jiaqiluo Can you validate this issue using alpha-rc1 build when it is made available?

**Comment by jiaqiluo** [comment]
> @jiaqiluo Can you validate this issue using alpha-rc1 build when it is made available?
Sure!

[Space holder for future validation result]

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher: v2.2.0-rc1 HA airgap setup.

Steps:  
- For the cluster `local` click `view in API`
- in the API page, right-click to view page resource
- see `/api-ui/...` instead of `//releases.rancher.com/api-ui/...`

<img width="757" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53280462-b5f34b80-36d7-11e9-99e9-30b8cec5b3c4.png">
