### ISSUE TITLE
Feature Request - EKS - Allow for AssociatePublicIpAddress: 'false'

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#15419]
**Rancher versions:**
rancher/rancher: v2.0.8

**Details:**
Right now the EKS cloudformation stack defaults to:
AssociatePublicIpAddress: 'true'

This should be a parameter and allow for it to be set to false.

**Comment by nathan-jenan-rancher** [comment]
In order to fix this issue we will need to do the following:
1) vendor the worker nodes template into kontainer engine
2) add an additional field to kontainer-engine to allow a true/false boolean to be passed in for the `associate public IP address` field (default to true)
3) modify the vendored template to allow the `associate public IP address` field to be passed in (currently it is hardcoded to `true`)
4) update the ui

**Comment by nathan-jenan-rancher** [comment]
This issue is not as simple as originally thought.  After allowing the `AssociatePublicIpAddress` to be toggled true or false, and setting it to `false`, the nodes in the EKS cluster failed to connect.
We do not have a definitive cause at this time, but we strongly suspect that this is because the worker nodes no longer have a path to the internet, the EKS cluster is exposed via a public IP.
The fix for this would involve allowing the worker nodes to access the internet, possibly through a NAT, as well as modifying the existing cloud formation templates to create a mix of private and public subnets within the EKS VPC. Additional logic for cleaning up these resources would also be required when the cluster is deleted.

**Comment by nxf5025** [comment]
@nathan-jenan-rancher - I'm wondering if that occurred due to the setup of the AWS account you were testing in. After launching the initial stack (Through Rancher) with `AssociatePublicIpAddress`  set to 'true' I'm able to update that same stack and pass 'false'. The stack updated successfully and I'm able to launch my containers without issue. However, on creation I am passing a VPC id as well as subnets which is probably why I do not have an issue. Possible for first release of this item to force the user to also pass a properly configured VPC ID as well as subnets assuming that is indeed the issue?

**Comment by tfiduccia** [comment]
Version - 2.1.1 rc5
Verified fixed

**Comment by soumyalj** [comment]
Tested with master build from Nov 28 . Created cluster allowing private IPs for worker nodes.

Note: It was required to create a VPC with 2 private subnets and 1 public subnet.
The two private subnets should be in different AZs
Public subnet’s route table had the target as AWS’s internet gate way
Private subnet’s route table had the target as NAT which was deployed in the public subnet

Cluster API displayed the config as below:
```
amazonElasticContainerServiceConfig": {
"accessKey": "abc",
"associateWorkerNodePublicIp": false,
"instanceType": "m4.large",
"maximumNodes": 3,
"minimumNodes": 1,
"region": "us-west-2",
"securityGroups": [
"sg-defg"
],
"subnets": [ 2 items
"subnet-abcd",
"subnet-0d81d5f551e063316"
],
"type": "/v3/schemas/amazonElasticContainerServiceConfig",
"virtualNetwork": "vpc-abcd"
},



```
