### ISSUE TITLE
I create a "nginx" workload, and then scale two container, when i access http://wudl.pro.10.10.1.38.xip.io  (ingress), it only   balancer to one container

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#15439]
I create a "nginx" workload, and then scale two container, when i access http://wudl.pro.10.10.1.38.xip.io  (ingress), it only   balancer to one container

---
![image](https://user-images.githubusercontent.com/14210543/45155181-b1f86d80-b20c-11e8-8499-b4406ee3676e.png)
![image](https://user-images.githubusercontent.com/14210543/45155191-b9b81200-b20c-11e8-9abe-bd07610ed03a.png)

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.8` UI: `v2.0.67` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by orangedeng** [comment]
@wuchencm I can not reproduce your problem. I am using rancher master 1/23 with RKE cluster. The ingress-nginx version is 0.16.2-rancher1. Steps are following:
- Create nginx workload with 1 replica
- Create ingress for nginx workload with xip.io
- Scale nginx to 2 replicas
- Access to ingress dns address 5 times
- Check the logs from both 2 nginx pod and both of them get hits.

I think this issue is fixed and closing this issue
