### ISSUE TITLE
Support to kube-router CNI

### ISSUE THREAD

**Issue by selmison** [rancher/rancher#15470]
**Rancher versions:**
rancher/server or rancher/rancher: v2.x

Is it possible to add support to [kube-router CNI](https://github.com/cloudnativelabs/kube-router)?

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rke/issues/312

**Comment by BloodyIron** [comment]
Uhh this request was specifically for RANCHER to support kube-router, and for me, the distinction between that and RKE is that Rancher, the webGUI, supporting kube-router instead of calico/etc... (or in parallel to?) Closing this ticket in favour of the RKE thread does not address the webGUI functional need for kube-router support, which appears to be absent as of Rancher v2.6 as of this writing.

If @superseb I am just incorrect, there is a way to install, manage, and such for kube-router within Rancher v2.6/etc, then please point me in the correct direction. But thus-far, my search for it turns up nothing.

I am particularly interested in kube-router as it looks to be a possible solution for retaining "Source IP" since I'm using Metal LB Layer 2 loadbalaner . This is, naturally, all on-prem.

**Comment by superseb** [comment]
@BloodyIron Without support in RKE for this, there is no need to create changes in Rancher. 

The only way to do it in RKE today is to disable all conflicting components in RKE and deploy it manually through add-ons or outside RKE. There are examples how other users have done it in https://github.com/rancher/rke/issues/312.

**Comment by BloodyIron** [comment]
@superseb what is the roadmap for kube-router then? As that ticket looks roughly dead in the water from RKE/Rancher bringing kube-router in to be a main feature. My vote would be for it to be a selection in the rancher UI, naturally as an alternative to Calico/Cilium, the like, and all necessary steps taken by Rancher, as is the point.

I mean so much is already automated by Rancher, even if kube-router isn't in main for RKE, clearly the method for what needs to be automated is, as you say, in that thread.
