### ISSUE TITLE
Display used resource quota for namespaces in a project with associated resource quota

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15522]
For a project with resource quota, we need to display the resource quota usage for the namespaces in a user friendly manner.
Currently the only way to find the resource quota used for a namespace is by using the API.

**Comment by loganhz** [comment]
@vincent99 @westlywright 

As there is no project/namespace detail page, we can only view the resource quota for a project/namespace in edit project/namespace page now.

Where should we display the resource quota of namespace and project?

**Comment by loganhz** [comment]
How about adding a `View` action in action menu for project and namespace?

**Comment by cjellick** [comment]
ping @vincent99 @westlywright ^ answer?

**Comment by westlywright** [comment]
@loganhz @cjellick Vince and I have come up with a solution. We wont be adding a view action or a detail page (i think there are actual reasons we don't have these details pages). On the namespace creation page we we will show a progress bar with the `project limit total/used/remaining`. This is what we briefly discussed in our meeting earlier @cjellick

**Comment by vincent99** [comment]
![image](https://user-images.githubusercontent.com/753917/45709349-ad02ba80-bb38-11e8-99ac-c7465c554ace.png)

- "Reserved" color shouldn't stand out... `bg-info`
- "This namespace" number should be the same as the input on the right (=5), not (reserved+this=11)
- The math is wrong somehow, if you put in a 0 quota there's still a yellow bar, sometimes @tfiduccia gets NaNs for all the numbers, etc
- You shouldn't be able to type in a number higher than is available, or negative numbers in the first place.. set min/max on the input
- Use colons instead of hyphens, and newlines, and drop the field name ("Pods") from the tooltip
- Show units on the numbers when appropriate (500 MiB)
- Trying again on the labels with @tfiduccia (below)
- And +1 internet points if it could be an actual HTML table so they line up nicely (ignore the first row, GitHub markdown...):

<table>
<tr><td>Other Namespaces:</td><td align="right">1500 MiB</td></tr>
<tr><td>This Namespace:</td><td align="right">600 MiB</td></tr>
<tr><td>Available:</td><td align="right">400 MiB</td></tr>
<tr><td colspan="2" align="center" >-- border-top line --</td></tr>
<tr><td>Total:</td><td align="right">2000 MiB</td></tr>

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/21
Verified fixed
