### ISSUE TITLE
Readonly project members are allowed to create namespace the project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15560]
**Rancher versions:** Build from master
**Steps to Reproduce:**
Create a github enabled setup.
Create a cluster and add projects - project1 and project2.
Add "user1" as "Member" to project2.
Add "user1" as "Read-only" member to project1.
Log in as user1.
User1 is allowed to create a new namespace in project1.
Note - He is not able to create workloads as expected. 

Expected Behavior:
User1 should not be allowed to create a new namespace in project1.

**Comment by dramich** [comment]
This is expected because of how we/kubernetes handles namespace permissions. If a user has namespace create permission in any project they will have that permission everywhere. Other resources will still fail outside of the namespace for a user that is read-only in a project.

Opened an issue to address this in the docs: https://github.com/rancher/docs/issues/794

**Comment by dramich** [comment]
https://github.com/rancher/docs/pull/795

**Comment by cjellick** [comment]
https://github.com/rancher/docs/pull/837

**Comment by sangeethah** [comment]
Following text is now added under "project-roles" section in docs:

Caveat:

Users assigned the Owner or Member role for a project automatically inherit the namespace creation role. However, this role is a Kubernetes ClusterRole, meaning its scope extends to all projects in the cluster. Therefore, users explicitly assigned the owner or member role for a project can create namespaces in other projects they’re assigned to, even with only the Read Only role assigned.
