### ISSUE TITLE
Can't create Azure RKE machines in us east using defaults - error on resource

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15651]
**Rancher versions:** 2.1 master 9/17

**Steps to Reproduce:**
1.  Using the defaults, create a Azure RKE template but change location to East US
2.  Use template and create cluster

**Results:**   Error creating machine: Error in driver during machine creation: compute.AvailabilitySetsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="InvalidResourceLocation" Message="The resource 'docker-machine' already exists in location 'westus' in resource group 'docker-machine'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name."; Timeout waiting for ssh key

![image](https://user-images.githubusercontent.com/11514927/45649355-ea574180-ba7f-11e8-92e8-a755588d8db7.png)

**Comment by cjellick** [comment]
This is due to naming clashes in azure. The docker-machine azure driver defaults some new resources to be named "docker-machine" and there are some name uniqueness constraints.

Impact seems low since the work around is to rename the offending resource and a fix would be large and impactful. So, moving this out of the 2.1 release
