### ISSUE TITLE
B size instance for azure rke won't work with default availability set

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15653]
**Rancher versions:** 2.1 master 9/17

**Steps to Reproduce:**
1.  Create a azure template using defaults but change size to B1s
2.  Try to create an azure cluster using that template

**Results:**  The cluster won't create.  Say the b series isn't added to that particular availability set.
![image](https://user-images.githubusercontent.com/11514927/45457108-51e94780-b6a2-11e8-9e48-6d4389c128af.png)

**Comment by cjellick** [comment]
Some relevant documentation:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-availability-sets?toc=%2fazure%2fvirtual-machines%2fwindows%2ftoc.json
https://www.petri.com/understanding-azure-availability-sets

What is happening is that once you've launched VMs with an availability set, that AS gets tied to physical hardward. The physical hardware only supports certain VM sizes. So, when you try to add a VM to an AS that already has VMs, you might not be able to because the hardware doesnt support that size.

The workaround would be to name a new availability set for the new VM you are creating.

The ideal fix would be to make this an OPTIONAL field and if it is not specified, DONT use availability sets at all, but that requires a change in docker machine (or at least our patched version of it).
