### ISSUE TITLE
Support more alert group config

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#15663]
Alertmanager have the feature to group event, the ```init wait``` time for group the alerts before first notify, and the ```group interval``` is for group the subsequent event, but we not open the second config yet, in case user could not get some notify so we config a very short group interval as the default.

We need to support more alert group feature and make the configure more clear.

**Comment by aiwantaozi** [comment]
link old issue: https://github.com/rancher/rancher/issues/15562

**Comment by aiwantaozi** [comment]
@n313893254 Backend support groupWait, groupInterval, repeatInterval for alert rule and alert group now, UI just support config them in group, could you also support for rule level?

**Comment by davidnuzik** [comment]
Found bug: #17763 alerts are not working correctly.

**Comment by davidnuzik** [comment]
Re-opening this issue; I have noticed that when I create an alert group the advanced settings do not seem to be honored or at least the repeat interval time. I set a repeat interval time of 2 minutes, group wait of 30s and group interval of 1m and I only get a repeat notification after 1 hour (the default).
When I inspect http/api everything looks correct. The server acknowledged the times but this doesn't seem to work.

Please let me know if I can provide any additional information or assist in any way.
Version: master 2.2 (1/31/19)

**Comment by davidnuzik** [comment]
Looks like this issue cannot be tested until #17536 is fixed.

**Comment by aiwantaozi** [comment]
@davidnuzik Now we have an interval for alert group and alert rule now, now the alert rule is actual work for each alert rule, can you check the advance option for you alert rule? The alert rule may config the repeatInterval is 1h. Will improve by add alert rule could inherit from the alert group by default, then you could update the alert group advance option then affect the alert rule. Related issue: https://github.com/rancher/rancher/issues/17538

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/1/19)
Confirmed feature. The advanced alert alert group options work as expected. Alerting is not perfect but the times are close.

I tested by creating my own alert group, I had one rule for when there is a pod event so that it only fires occasionally such as when I add a pod, or multiple pods in a row for a while. My second rule is an expression that fires if the cpu is over 3% and I set an ubuntu workoad to run the stress program to eat 100% cpu constantly. This makes this rule always constantly alerting.

With this set up I was able to test the groupWaitSeconds, groupIntervalSeconds, and repeatIntervalSeconds (pictured below in clockwise)
![image](https://user-images.githubusercontent.com/45179589/53664247-3ad4ec80-3c25-11e9-836d-d04c59a9d5c2.png)

I got my initial notification in about 30 seconds (it takes longer first time setting this up because the workload for alerting needs to deploy but it's close) this was for cpu since it is constantly alerting. After about 5 minutes I got the repeat interval and just before this i kept creating pods and put a workload in a state so it's constantly creating pods/containers due to error state so now both kept firing. This sent the notifications in a group due to Group Interval Time being in this timeframe.

I smoke tested this area and reliably get repeat notifications every 5 minutes per my settings seen in the screenshot. I tried adding/removing more rules from the alert rule group and didn't identify any noticeable issues.

Again the times are not perfect but are close, around every 5 minutes I get repeat notifications for CPU since it is constantly alerting with my configuration / test setup.
