### ISSUE TITLE
Node labels set when adding a node can't be changed

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15709]
Version: master 9/19

**Steps to Reproduce:**
1. Add a node to a custom cluster, add Node label `dummy=yes` so it gets added as `--label dummy=test` to the generated `docker run` command. Execute command on a node to add it.
1. After the node was added, edit Node in UI, change Node Label `dummy=yes` to `dummy=no`.

**Results:**
Node label is changed, and changed back to original value few seconds later.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Scenarios  Tested:
1. Create a custom cluster. Add 1 node with etcd and controlplane role.
2 .Add worker node by passing labels (hello1=value1, hello2=value2).
3. Once the node gets registered , able to see the labels in the nodes in UI as expected.
4. Edit host and modify the existing label's value to a different value say "hello1=value11".
5. Node labels get updated as expected and is reflected in the UI (and in kubectl) as expected.
6. Reboot the worker node , so that the node gets to "Unavailable" state and then gets back to "Active" state.  
7. After host gets back to active state, correct labels(with modified values)  are present in the node.
8. Edit host and add new labels. New labels get added as expected to the nodes.
9. Edit host and delete the existing label (which was added using register command) -hello1=value11. Notice that label get set back on  the node with initial values set during the register command - hello1=value1.

Reopening this issue to fix the case where deleted labels get added back to the nodes.

**Comment by alena1108** [comment]
Marking the issue as resolved - the use case it was filed for, is addressed. The removal use case will be tracked in a separate issue.

**Comment by ikogan** [comment]
I'm not sure if this is related but on 2.2.4 I accidentally created a node with an empty label. That is, I did `--label role=` on one node. That label continues to get reset to empty every time I change it either with the Rancher UI or with `kubectl edit` on the node.
