### ISSUE TITLE
Show Kubernetes events in UI

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15710]
`kubectl get events --all-namespaces --watch` can often be used to quickly indicate something that is wrong with the cluster, it could be useful if we can show the events stream in the UI.

**Comment by yvespp** [comment]
It would also be nice to see the events per namespace, for example Quota errors are not directly attached to a Deployment/Pod and not visible in Rancher UI:
```
kubectl.exe -n appll-test get events
LAST SEEN   FIRST SEEN   COUNT     NAME                                                    KIND         SUBOBJECT   TYPE      REASON         SOURCE                  MESSAGE
51m         51m          1         app-service-558d78f8f.159681c0a4f38125   ReplicaSet               Warning   FailedCreate   replicaset-controller   Error creating: pods "app-service-558d78f8f-8dsql" is forbidden: exceeded quota: test-quota, requested: requests.memory=2Gi, used: requests.memory=2Gi, limited: requests.memory=3Gi
```

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/13/19)

Now there is an "Events" pane when viewing the cluster dashboard. This lists kubectl events. They are also listed by namespaces and you can sort like most tables in the UI.

I didn't spot any issues while testing, except I think it would be ideal if we could limit how many events per page i.e. if it honored our max count per page like in the user settings:
![image](https://user-images.githubusercontent.com/45179589/64889966-6056a000-d623-11e9-96fd-69694448f0be.png)

This is because the list can be rather long. I created a separate issue to request this here: https://github.com/rancher/rancher/issues/22858

Example screenshot of this new area on the cluster dashboard (note, text is shown smaller than usual as I zoomed out in my browser):
![image](https://user-images.githubusercontent.com/45179589/64890203-e672e680-d623-11e9-9cc1-377b6e9fc50b.png)

As events come in, this will update in the UI. The update happens about every 10 seconds.

**Comment by chiru6003** [comment]
Hi @davidnuzik I am not able to see Rancher Events on the UI. Can you please suggest to me how to enable those events?
