### ISSUE TITLE
Problem when adding host from openstack

### ISSUE THREAD

**Issue by j90332** [rancher/rancher#15796]
I'm using rancher v1.6.14
When I start a new environment, it asks me to add a host.
I want to add a host from the openstack. So I use the GUI to add the host.
But I get the error: 
![image](https://user-images.githubusercontent.com/30824663/45996466-dbe7d600-c0ce-11e8-89a3-1a9c2c01349b.png)
How can I fix the problem?
Here is the openstack config
![image](https://user-images.githubusercontent.com/30824663/45996504-05a0fd00-c0cf-11e8-9a64-e6a855e77c87.png)
Thank you.

**Comment by superseb** [comment]
Probably hitting this upstream issue: https://github.com/docker/machine/issues/3774

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by kayrus** [comment]
@loganhz can you reopen this issue, since it affects rancher 2.x as well? I developed a patch for docker-machine (see linked), but I suppose it won't be merged. When I tried to develop the plugin, which can be downloaded independently, for some reason it didn't allow me to override built-in openstack driver. I didn't dig much into details, but appreciate some help.

**Comment by DJAyth** [comment]
Running into this issue as well which seriously hampers my initial cluster creation. Replacing docker-machine with the copy from @kayrus works, but requires manual intervention.

**Comment by dbagg** [comment]
Also running into this which is a big hurdle to my team giving rancher a serious evaluation.

Is there somebody who can look at the open PR?

**Comment by kayrus** [comment]
@loganhz since you reopened this issue, could you please take a look on these PRs as well?
https://github.com/rancher/types/pull/986
https://github.com/rancher/types/pull/984
https://github.com/rancher/rke/pull/1661

**Comment by dbagg** [comment]
@loganhz:
Any idea when or if this will get worked on?
Before I go down the road of trying to make the proposed fix locally and running off of forks to evaluate rancher, want to make sure we won't be stuck on our own little fork forever.

Also, issue labels should probably be updated since this is present in latest.

**Comment by daxmc99** [comment]
@kayrus Could you make the PR to https://github.com/rancher/machine/? We use a fork of docker machine. If you need any help getting the PR merged you can reach out to me directly on the rancher slack's developer channel or here.

**Comment by kayrus** [comment]
@daxmc99 sure, will do.
