### ISSUE TITLE
Cluster wide views with filter options

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15833]
As an admin I would like to have an easy way to view all workloads in a cluster and view any that are having issues, etc with filtering without having to jump between all projects. 

Maybe ways to search workloads by project, image, name, namespace, labels, etc.

**Comment by superseb** [comment]
This needs some work in the backend to make this work, other use-case would be a Security Dept that wants a view on all clusters directly with the images that are currently running for instance.

**Comment by yasker** [comment]
As a first step, I think the overview of the cluster can be shown in the form of a pie chart instead of a huge list.

For example, one pie chart to show the status of `Projects`. There can be three colors, green, yellow and red, indicates a different level of the outage. If every workload/lb/service/volume in the project is running/active, show green in the pie chart; if all the workloads etc. are down in the project, show red in the pie chart; if neither of the conditions was met, show yellow. The admin can click the correlated color in the pie chart to show a list of projects, which can be clicked again for details.

The same can be applied for `Workloads`, `Load Balancing`, `Service Discovery`, `Volumes`.

One issue pointed by @vincent99 is, for a large cluster, there can be too many information on the list. So it cannot be UI who load all the information every time and try to make sense of it. The backend API should provide the summary, filter and pagination functions for UI to consume.

**Comment by sheng-liang** [comment]
We need backend API. This is not a UI only feature.

**Comment by ekristen** [comment]
Yes please! I find that on clusters where it makes sense to have even 3 projects for separation for others, as an admin having to flip constantly back and forth between projects to get what I need is rather frustrating.

**Comment by deniseschannon** [comment]
In the new Cluster Dashboard view (available as of v2.5+), you can view all workloads in a cluster either grouped by namespace or not. In this view, you can sort by State.
