### ISSUE TITLE
vSphere node template test option

### ISSUE THREAD

**Issue by tuxiem** [rancher/rancher#15837]
**Rancher Version:**
2.0
**Feature Request:**
When deploying new clusters on vSphere, it would be nice, if the template had a "test connection" button/option.
So you don't have to provision a new cluster, to find out there is an error in the configuration.
Also add helper lines, to give an indication where the problem is located in the template configuration.

**Comment by skyscooby** [comment]
Yes it's very difficult to figure out exactly what you need to type into the fields when you have a lot of organisational subgroups in the folders, resource pools, datastores etc.. having dropdowns generated based on the user account already supplied in the credentials would make success a higher probability... I have been trying quickly after each release to get a rancher cluster going on vsphere since version 2.0 released.. finally got one going by omitting the resource pool as I couldn't figure out how to specify the one I wanted. Seems like it's just created at the root of the cluster if it's left blank.

**Comment by lapawa** [comment]
+1 
It's always a trial and error procedure to the parameters right.
