### ISSUE TITLE
 In a cluster, should not give muti-permissions to the same user

### ISSUE THREAD

**Issue by dongjuanwinhong** [rancher/rancher#15876]
**Rancher versions:**
rancher/server or rancher/rancher:v2.1.0-rc4

**Results:**
![image](https://user-images.githubusercontent.com/39041059/46240474-b1519200-c3da-11e8-91c7-738a66a57cc5.png)

**Comment by loganhz** [comment]
This is by design. 
@vincent99 please correct me if I am wrong

**Comment by vincent99** [comment]
That particular example is not very useful since those roles contain mostly the same permissions, but yes a user can intentionally have multiple roles.  Even if that were restricted, a user can still have multiple roles because they can be a member of multiple groups which have a role (or multiple) in the cluster.

RBAC is strictly additive.  The user gets the union of all the permissions granted by all the role bindings applicable to them.
