### ISSUE TITLE
Cluster provisioning stuck in "provisioning" state for Azure with cloud provider enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15906]
Rancher server version - v2.1.0-rc8

Steps to reproduce the problem:
Create a cluster with Azure with cloud provider enabled with following configurations:
1 control node
1 etcd node
3 worker nodes

Cluster provisioning gets stuck in "provisioning" state with following error message:
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Failed to get kubernetes node [test-28884]: "test-28884" not found
```
test-28884 is the etcd node.

All nodes are stuck in "Registering" state with message -  "Waiting to register with Kubernetes"

**Comment by sangeethah** [comment]
@galal-hussein's findings:

i found the problem, the first run failed because kubeapi wasn't ready yet the second run of rke override the cloud config file, we should put check to make sure not to override the cloud config if its already deployed:
https://github.com/rancher/rke/blob/master/cluster/cloud-provider.go#L44
GitHub
rancher/rke
Rancher Kubernetes Engine, an extremely simple, lightning fast Kubernetes installer that works everywhere. - rancher/rke
that's why both kubelet on controlplane and etcd failed

```, kubelet says:
```I1002 06:12:53.809518   12440 kubelet_node_status.go:82] Successfully registered node test-71856```
but later it reports:
```E1002 06:13:04.124868   12440 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "test-71856": nodes "test-71856" not found```

**Comment by moelsayed** [comment]
Here is the problem:
- During provisioning, kubeapi entry script will use configuration from the cloud provide config to connect to azure cloud api and get further configuration items and update the cloud provider config. Azure api can be slow and the kubeapi health check can time out.
- When rancher retries, it will redeploy the cloud provider config with the essential configuration _only_, the new updates created added by kubeapi will be overwritten.
- Rancher will find kubeapi up and proceed to deploy the `kube-controller-manager`, which will find the cloud provider config the essential config only. This will cause it to fail to connect with the cloud provider and later cause kubelet to fail in registering itself with kubeapi. 

The fix is to generate the needed configuration in entry script for kube-controller-manager as well. 

To reproduce this:
- Deploy an azure cluster.
- Monitor rancher server logs during provisioning, once kube-apiserver is started, and before the healthcheck succeeds, stop the rancher server. 
- After a couple of minutes, start the rancher server back. Rancher will try to provision again and will trigger the same case described in the issue.

**Comment by bmdepesa** [comment]
rancher/rancher:master 10/4

* First reproduced issue in v2.1.0-rc5
* Provisioned Azure cluster w/ cloud provider, but stopped rancher server after kube-apiserver deployed, before healthcheck completed.
* Started rancher server
* Azure cluster failed to provision, with "node not found" error from above and stuck at "Waiting to register"

Fresh install from master:
* Provisioned Azure cluster w/ cloud provider and stopped rancher after kube-apiserver deployed
* Started rancher server
* Rancher retried provisioning and cluster came up successfully.
