### ISSUE TITLE
Pod creation fails in a cluster with flannel network provider 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15936]
**Rancher versions:**
rancher/server or rancher/rancher: v2.1.0-rc9
Kubernetes version: v1.11.3
**Steps to Reproduce:**
1. Create a cluster with network provider set as "Flannel"
2. Create workloads/pods

Pod creation fails with the below error:

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2dbfe2330719023ffdcc1c617b4fe755dc0ad8a49efebe76318f9db3ac609875" network for pod "wk1-7b4f89968f-5lvw6": NetworkPlugin cni failed to set up pod "wk1-7b4f89968f-5lvw6_default" network: open /run/flannel/subnet.env: no such file or directory

```

**Comment by moelsayed** [comment]
The problem is that Rancher server sets `flannel_backend_type` by default:
```
"network": {

    "options": {
        "flannel_backend_type": ""
    },
    "plugin": "flannel",
    "type": "/v3/schemas/networkConfig"

},
```
This seems to be introduced in this UI PR: https://github.com/rancher/ui/commit/64be404fbb. The problem with this is that it breaks defaults for Linux hosts. 

To fix this, UI should either set this option to `vxlan` for linux hosts, or not send this option at all and the backend with handle it and set the default.

**Comment by soumyalj** [comment]
Tested with master. Created a cluster with network provider set as "Flannel". Cluster creation and pod creation was successful.

**Comment by tfiduccia** [comment]
Version - 2.1 master 10-4
Verified fixed

**Comment by cjellick** [comment]
I've re-opened so that we can have someone validate windows still works with this change.
