### ISSUE TITLE
Rancher 1.6.17 getting dying with oom

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#15935]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.17

Kubernetes environment

we've increased the Xmx and Xms values to 12 and 16 gigs in order to get the server to start. There's only one rancher server behind an nginx service at the moment.

**Comment by pasikarkkainen** [comment]
@aemneina : Did you try with the latest version in 1.6 branch: v1.6.22 ?

**Comment by cjellick** [comment]
The OOMs are occuring in the places where we load all instances (about 1500 in this case) for an enviroment into memory after a DB call or where we build up a cache of instances. Generally, doing this would not be an issue in-and-of-itself. I'm sure plenty of users have environments with 1000+ containers, but it is a problem for this user  because the `data` field of many of the instances is quite large. This `data`field contains json data that we need, but dont want to dedicate a column or table to. It also includes the docker inspect.
For many of their instances, the size of this field is greater than 300 KB. 600 are even pushing a 500 KB (half a meg each).

The majority of that size is due to a many environment variables being set in the container. We are talking in the range 4000 environment variables. ...which get stored twice in the data field - once in our `environment` field and once in the raw docker inspect that we got back from the host :grimacing:

The heap dumps have allowed me to positively identify several places where this is causing a problem, but this may not be all of them:
- https://github.com/rancher/cattle/blob/4a6ea6970bbd831e4fd69acf355154de2d279e24/code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/process/SelectorServiceCreatePostListener.java#L110
  - based on this one, we need to find anywhere else we are using find() to get all non-removed instances. My quick grep found 3 or 4 more.
- https://github.com/rancher/cattle/blob/4a6ea6970bbd831e4fd69acf355154de2d279e24/code/iaas/model/src/main/java/io/cattle/platform/core/dao/impl/InstanceDaoImpl.java#L314
  - this cache is ultimately used to populate metadata.

**Comment by alena1108** [comment]
Can be tested with `rancher/server:v1.6.26-rc1`

**Comment by soumyalj** [comment]
Tried to reproduce with Rancher v1.6.17. Created several containers with each having 1000+ environment variables. As the env variables increased, the memory consumption increased, but rancher setup became unresponsive after. Did not hit the Out of memory exception.

**Comment by soumyalj** [comment]
Tested with v1.6.26-rc6. Created a Kubernetes setup with 4G memory nodes. 
Created several containers with each having 100000+ environment variables. As the env variables increased, the memory consumption was not drastic. The rancher setup slowed down during container creation for few minutes and stabilized eventually.
Sample of memory consumption on rancher server
```
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1250         347           5        2095        2142
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1248         349           5        2095        2144
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1255         341           5        2096        2136
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1240         356           5        2096        2151
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1235         356           5        2101        2156
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1233         357           5        2101        2158
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1217         374           5        2101        2175
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1217         374           5        2101        2175
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1220         371           5        2101        2172
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1221         370           5        2101        2170
Swap:             0           0           0
soumya_jlk@soumya1626rc6oom-10acre-master-0:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3693        1227         302           5        2162        2163
Swap:             0           0           0







```
