### ISSUE TITLE
AD - Inconsistencies seen in search results.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15961]
**Rancher versions: v2.1.0-rc10
**Steps to Reproduce:**
Have AD auth enabled setup.
In siteAccess list/Project Member/Cluster member page , try to search for any group(or user) by entering first few characters of the group to search.

I see the list return all groups (and users) starting with the characters entered.
When i scroll down the list , I also see entries that do not start with search string entered.

<img width="569" alt="screen shot 2018-10-05 at 10 26 25 am" src="https://user-images.githubusercontent.com/4266958/46550290-7db6b200-c889-11e8-8d39-120b1893ba4b.png">

**Comment by mrajashree** [comment]
<img width="1388" alt="screen shot 2018-10-05 at 10 12 02 am" src="https://user-images.githubusercontent.com/10672776/46550143-f9fcc580-c888-11e8-8530-c9fe1ae67607.png">
This happens because the TestUserGroup* accounts are actually user accounts mistakenly named as groups. These user account have first name starting with Ne*, and the search is for both, users and groups.

<img width="1397" alt="screen shot 2018-10-05 at 10 23 24 am" src="https://user-images.githubusercontent.com/10672776/46550220-3f20f780-c889-11e8-9c03-ff2272ee32f3.png">
This happened in 2.0.8 too, it could be something to do with UI cache but in both, 2.0.8 and latest master you can see the group you were looking for as well. So not a bug as per me and definitely not related to the fix

**Comment by cjellick** [comment]
@westlywright do you think is connected to how the UI caches search results, as @mrajashree suggests? If so, do you think we should change it or do you think the current behavior is intended and desired?

**Comment by westlywright** [comment]
@cjellick we don't cache the results, we do some debouncing with the input which sends a new request after no additional input for 250ms. If the user starts input again the current request will be dropped in favor of the new request with new input. 

I was unable to reproduce this but after some analysis of the code I think that in some cases we'd return the promise, start another search and before the new search completed the `then` statement from the previous would fire. Since we can't technically abort an ajax call I have a feeling this may be the problem. I tweaked the flow so that we only parse the results after the yield has finished.

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/8/19)
Confirmed search is still functioning correctly. I was not able to reproduce the issue.

I spent time trying to reproduce, change the speed of typing, faster than 250ms per char and less, etc. Enter partial searches and then add a letter that should refresh search. In every situation the search was working correctly for me. I monitored HTTP traffic and saw the UI appropriately query after an update every quarter of a second. I was unable to identify any issues.
