### ISSUE TITLE
backport UI html header fix to prevent incorrect caching

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16041]
Backport https://github.com/rancher/rancher/issues/15981

**Comment by loganhz** [comment]
As the HTML is already cached in browsers, you still need to clear the cache manually if you met this issue in Rancher v2.1.1.

**Comment by loganhz** [comment]
For testing this issue,

Steps:

1. Clean your browser cache. (as HTML already cached before 2.1.1-rc, so we can do noting but clear it)
2. Go  to Rancher UI
3. Look at the http response header in html files
4. Verify browser always loads the html file instead of using the cached one. (You can look at in the Firefox/Chrome dev tool. It will shows if it is in using cached file)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.1.1-rc4

First reproduced the issue:
* Deployed v2.0.8
* Loaded UI
* Upgraded to 2.1.0
* Saw incorrect version

Validated fix:
* Cleared cache
* Upgraded to v2.1.1-rc4
* Opened network tools
* Validated the `no-cache` header is applied to HTML requests and is not using a cached version.
