### ISSUE TITLE
API /v1/containers is missing ports for services containers

### ISSUE THREAD

**Issue by ebuildy** [rancher/rancher#1607]
I setup a service with MariaDB that expose port 3306:

**/v1/containers**

![/v1/](https://beemapp.s3-eu-west-1.amazonaws.com/2c8864b6-f275-45c0-8e82-542e8c660392.jpg)

Whereas I can the port in **/v1/containers/1i133/ports**

![/v1/](https://beemapp.s3-eu-west-1.amazonaws.com/2f10d8cb-e12d-43c4-b93b-2c92d8c711c1.jpg)

Why I don't see the port 3306?

**Comment by vincent99** [comment]
Sort of an oddity but ports as a string array is only for create.  When listing or editing you have to use the ports link.

**Comment by ebuildy** [comment]
I can see ports for containers created manually by **docker run ...** but not for those created via Rancher scheduler.

https://gist.github.com/ebuildy/27694710e8ca13f0234f

Worked before only with ports ;-( now I have to declare an explicit label. (not a big deal, just to let you know).

**Comment by deniseschannon** [comment]
It's strange, ports exposed in the image show up in the UI on the container with no public port, but not in the API.

Since it works for `docker run` and shows these ports exposed form the image in the API of the v1/container/contianerID, it should display ports for when we create a service/container from the UI.

**Comment by vincent99** [comment]
I don't think any of this is relevant to 1.6 or 2.0 anymore...
