### ISSUE TITLE
load balancer issues since acme

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#16106]
**Rancher versions:**
rancher/server or rancher/rancher: rancher/rancher v2.0.8
rancher/agent or rancher/rancher-agent: rancher/rancher-agent v2.0.8

**Operating system and kernel: Rancher OS 1.4.1

**Type/provider of hosts: VPS on contabo.com

**Setup details: single node rancher

**Environment Template: Kubernetes (no other choice sinde rancher 2 I gues)

**Steps to Reproduce:**
* I had a simple rancher setup with the same version running
* stopped the running instance
* setup rancher with the following command:
docker run --name rancher-server -d -v rancher:/var/lib/rancher -p 80:80 -p 443:443 rancher/rancher:stable --acme-domain rancher.<domain>.<tld>
* adding the cluster via "custom"
I am not sure if this is nececary but I habe a wildcard letsencrypt cert on my domain on which rancher runs.

**Results:**
Rancher spams the following line in the log:
http: TLS handshake error from 91.113.21.167:<several ports>: acme/autocert: host not configured
And most of my containers are not reacable via ip:port or domain. It seems that I have issues maybe with a rancher network? Docker container which I've created via docker run works well and are instantly available via ip or domain and port. But ports opened with rancher are not realy reacable. the browser tries to load the page, but nothing happesn until several minutes. It is realy confusing, a container on port 60 is reacable. If I set the contianer to an other port, it is not reacable. All containers / pods are configured with HostPort.

Edit: now I've found an other interesting thing: if I delete a pod and want to let create a new one. It sayes 0/1 nodes are available... WHY?? Nothing else is lisening on the same port. And with docker run I am able to acces it, but rancher can't. I am realy confused.

What is going wrong?

PLEASE HELP ...

**Comment by MSandro** [comment]
Solved by update to 2.1.0.

**Comment by MSandro** [comment]
It would be realy nice if someon could give me an answer how to solve those confusing situation on my server. I am able to use my services since v2.1.0 but only with the port. I am not able to use a load balancer. Since today, the rancher UI shows "initializing" on the balancer. Deleting and recreating them also doesn't solve the issue.

**Comment by MSandro** [comment]
Do I need a second IP adress for my server to bind rancher to a subdomain without need of a something like a nginx in front of it, or what the hell I am doing wrong? Could someon help me please? This would be realy nice. I like to work with Rancher. But I am not sure if I use it as I should.

**Comment by superseb** [comment]
It's a bit unclear, it usually helps to describe the steps to reproduce as this sounds like a setup where many things have changed since running it (starting with spinning up a new Rancher instance with ACME using the old data). Step 1 is to check if the settings (`server-url` and `cacerts`) are still valid, as you might hit https://github.com/rancher/rancher/issues/14731 when changing something in that area.

Probably because of the previously mentioned issue, the errors in the log appear as the Rancher container is being hit on the previous `server-url` (IP or hostname), which triggers the `host not configured` error.

Then for the nginx-ingress controller, probably you are adding the same machine running `rancher/rancher` to a cluster which will conflict on ports, which is explained in https://rancher.com/docs/rancher/v2.x/en/installation/single-node/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node. This can be checked by running `kubectl logs -l app=ingress-nginx -n ingress-nginx`.

**Comment by superseb** [comment]
Let me know if this needs additional help.
