### ISSUE TITLE
Get supported and default k8s versions from settings

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#16113]
Currently each cluster provider (RKE, AKS, EKS, GKE) has its own method of determining what K8s versions are available choices for deploying/upgrading a cluster and what the default one is.  There should be one set of settings for the release management team to set what the supported and default versions are, and all drivers should respect that.

Add settings for:
  - `k8s-supported-versions`: `>=1.9.0 <= 1.12.x`
  - `k8s-default-version`: `<=1.11.x`
  - As of this writing; for final 2.2.0 they will likely be different
  - They live in https://github.com/rancher/rancher/blob/master/pkg/settings/setting.go
  - But you can add your own in the API to test without waiting for a backend PR merge.

All cluster providers in the UI should take the list of possible versions they get from the provider and:
  - Sort them from highest to lowest (with the version-string-aware comparator, lib/shared/addon/utils/sort.js)
  - On edit, add the current version if it does not already appear in the version list
  - Disable (or keep enabled, but add something to the display label?  not remove) the versions which do not satisfy the `k8s-supported-versions` range (semver.satisfies)
  - On create: Select the highest version which satisfies `k8s-default-version` as the default value.
  - On create: If none of the available versions satisfy the default range, default to null/"Choose a version...".
  - On edit, enable the current version if it was disabled because it's outside the supported range.
  - On edit, disable versions older than the current version so that you can't downgrade (I think?  Do any providers support downgrade?  @deniseschannon)
  - On save, ensure a version is selected (not null).

Do all that in one common place and use that in all the drivers, so they all work the same way.  Something like `supportedVersions(allVersionsForThisDriver, currentVersionIfEditing)` -> `[{label: "v1.2.3", value: "v1.2.3-gke3"}, ...]` array suitable for giving to `{{new-select}}`, or a component that extends new-select and handles all that given a list of versions and the current version.

**Comment by davidnuzik** [comment]
Version: master 2.2 (1/4/19)
Validated the enhancements.
- I can confirm that we now always default to the latest available for any provider with the "Kubernetes Version" drop downs. The order appears correct for each (latest on top oldest at bottom).
- Versions that are not supported are grayed out and not clickable options in the drop-down (i.e AKS cluster cannot pick "1.8.14 (unsupported)") and sort order is still correct.
- Upon creation highest version is chosen by default.
- On edit you can see the current k8s version
- On edit older versions than current are disabled so that you can't downgrade you can only upgrade to newer.
- On save a version is always selected for every provider.

Confirm the above and for each validate HTTP and ensure is working correctly. Upgrades work, etc.
