### ISSUE TITLE
Add UI Support for SSL Passthrough

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#16149]
Is there a way to turn on SSL passthrouh ingress via the Rancher UI? Up to now it's only possible  to manually edit a yaml file for the passthrough to work (enable-ssl-passthrough) which is not persistent after k8s upgrade.

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/5/18)
Confirmed UI fix. If a param has empty value the UI no longer removes this. Also performed halo testing with this and made sure we can use the ingress annotation as well even though we didn't change this area in code.
Regarding the request: since this is an advanced option for nginx,etc and there are so many parameters we are not adding to the UI so we can keep it clean. It will be necessary to edit in the YAML. This issue fixed the UI so it's not removed when the value is empty.
