### ISSUE TITLE
Certificate of kube-apiserver is not renewed with all controlplane node entries when adding controlplane node causing 'x509: certificate is valid for' error when using kubectl

### ISSUE THREAD

**Issue by canhnt** [rancher/rancher#16151]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent: v2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.11.2

**Docker version: (`docker version`,`docker info` preferred)** 1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.16.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA RANCHER
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
When creating a worker cluster with multiple masters (say 3), some of masters have to old `kube-apiserver.pem` that only contains one domain in the `X509v3 Subject Alternative Name` rather than 3 domains.
**Results:**

Because of outdated `kube-apiserver` certificate in some kube masters, when users run `kubectl exec -it <pod-name> sh`, or `kubectl get pod`, etc. k8s requests from rancher server hit these masters, it returns 500 and error messages like:
```
unable to upgrade connection: error dialing backend: x509: certificate is valid for 10.x.y.z, 127.0.0.1, 10.43.0.1, not 10.x.y.t
```

Workaround fix: manually synchronize `kube-apiserver.pem` between master nodes and restart `kube-apiserver` container.

**Comment by dalsh** [comment]
I just encountered the exact same issue on one of my clusters : kube 1.11.2 deployed on custom nodes by rancher 2.0.8. 
Updated rancher to 2.1.0 and updated the cluster in the GUI to trigger provisionning, issue still present. 

@canhnt workaround works though 👍

**Comment by superseb** [comment]
Please provide steps to reproduce the issue, if not, all the details available in the setup you have encountered it that we can use to run tests/reproduce. How many nodes with what roles are in the cluster and did it start happening on creation of a new cluster or after adding nodes, and if the latter, what node with what role was added.

**Comment by dalsh** [comment]
@superseb Here's what I can recall : 

- Rancher 2.0.8, create new cluster with custom nodes, kube 1.11.2
- Add node "A" master,worker,etcd and specify internal IP "IP1"
- Add node "B" master,worker,etcd and specify internal IP "IP2"
- Add node "C" master,worker,etcd and specify internal IP "IP3"

Everything goes green, except `kubectl port-forward ...` on a pod running on C gives one of the following errors 2/3 of times : 
```
unable to upgrade connection: error dialing backend: x509: certificate is valid for IP1 ... not IP3
unable to upgrade connection: error dialing backend: x509: certificate is valid for IP1, IP2 ... not IP3
```

Inspection of `kube-apiserver.pem` on the 3 nodes shows the following : 
- Node A : 
```
X509v3 Subject Alternative Name:
  DNS:..., IP Address: *IP1*, ...
```
- Node B : 
```
X509v3 Subject Alternative Name:
  DNS:..., IP Address: *IP1*, IP Address: *IP2*, ...
```
- Node C : 
```
X509v3 Subject Alternative Name:
  DNS:..., IP Address: *IP1*, IP Address: *IP2*, IP Address: *IP3*, ...
```

After copying `kube-apiserver.pem` from node C to node A and B, the issue disapeared.

Versions : 
- OS: Ubuntu 16.04
- Kernel: 4.15.0-36
- Docker: 17.03.2-ce

The issue started happening a few days after the cluster was created. In the interval, we : 
- migrated to rancher 2.1.0. 
- restarted the nodes

A consequence of the restart could be that the Pod migrated from node A to node C, which I guess could have made the issue visible.

Hope that helps !

**Comment by kdanthony** [comment]
Same exact issue here and the work around fixed it for now. Our test cluster is 3 nodes so it was exactly as described in the previous comment where the earlier nodes did not have the newest nodes in the SAN of the cert.

**Comment by Symbianx** [comment]
We have the same issue with our newly created 2.1.1 cluster, with on-prem nodes.
As we add new control plane nodes, the old ones do not get updated certificates.

To add some more information:
We added 3 nodes, you can find the nodes below with the time they were added to the cluster and the `Subject Alternative Names` content of the local `/etc/kubernetes/ssl/kube-apiserver.pem` certificate.

```
cetxcosv005 10.172.80.21
    Added to cluster at 2018-11-06T11:52:49.178279948Z
    Subject Alternative Names: cetxcosv005, localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, IP Address:10.172.80.21, IP Address:127.0.0.1, IP Address:10.43.0.1

cetxcosv003 10.172.80.19
    Added to cluster at 2018-11-06T11:56:56.751949062Z
    Subject Alternative Names: cetxcosv003, cetxcosv005, localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, IP Address:10.172.80.19, IP Address:10.172.80.21, IP Address:127.0.0.1, IP Address:10.43.0.1

cetxcosv004 10.172.80.20
    Added to cluster at 2018-11-06T11:59:15.920508236Z
    Subject Alternative Names: cetxcosv004, cetxcosv003, cetxcosv005, localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, IP Address:10.172.80.20, IP Address:10.172.80.19, IP Address:10.172.80.21, IP Address:127.0.0.1, IP Address:10.43.0.1
```
We used the creation date of the share-mnt container to determine the time at they were added to the cluster.

**Comment by Seeefo** [comment]
Same here.  I am noticing the same issue, its particularly troublesome on helm commands as they tend to fail.  kubectl will notify you of failures if you use `--v=10`, but I think it retries the requests and they eventually work.  I can't tell if that's because Rancher is LB the kubectl commands across the nodes or what.

Since I am automating the API and deploying clusters on a pretty regular basis, I see this every 2-3 days.  Most of my deployments are 3 nodes and usually one or two of them have the wrong cert. 

In some cases, my cluster will have all 3 nodes, but Rancher will say one of the nodes is inactive.  Ironically, its the node with the most up-to-date certificate.

**Comment by bordeo** [comment]
We get the same issue. We spotted it because Jenkins kubernetes plugin return the error:

`hudson.remoting.ProxyException: io.fabric8.kubernetes.client.KubernetesClientException: error dialing backend: x509: certificate is valid for x.x.x.x ,.x.x.x.x, x.x.x.x not y.y.y.y`

This happened after we add a second master node and try to run a build using Jenkins master and slaves from that node.
I check the `/etc/kubernetes/ssl/kube-apiserver.pem` of `kube-apiserver` container on the first master node and I found that the certificate is not updated with the new node. So i copied the `kube-apiserver.pem` from new node to the old one like @dalsh and all works.

For who have the same problem in Jenkins a fast fix is to disable https check. This configuration could be check on Jenkins Kubernetes plugin config: **Disable https certificate check**

**Comment by superseb** [comment]
Possible root cause here is:

`apiEndpoint` in API for cluster is set to IP of a node with the `controlplane` role. This could be the one thats hit or is routed to another when its unavailable. The request made to the kube-apiserver is using the node IPs but the connection is made to the `apiEndpoint` IP, long story short, the IP of the `apiEndpoint` of the cluster has to be in the certificate, and due to the certificates not being refreshed, it might hit a certificate with that IP not being present.

I've seen this when standing up clusters and having nodes join randomly (based on boot time and Docker install time), and then break after stopping the `kube-apiserver` on one or more controlplane nodes while running `while true; do kubectl -v9 get nodes; sleep 1; done` and seeing:

```
"message": "Error: 'dial tcp IP_OF_NODE2:6443: connect: connection refused'\nTrying to reach: 'https://IP_OF_API_ENDPOINT:6443/api/v1/nodes?limit=500'"                                                                                                                                           
```

Indicating it tries to connect to `apiEndpoint` IP but actually connects to `IP_OF_NODE2`.

After some time, you will see:

```
"Error: 'x509: certificate is valid for x, x, 127.0.0.1, 10.43.0.1, not x'\nTrying to reach: 'https://x:6443/api/v1/namespaces/default/pods?limit=500'"                                                                                                   
      }
    ]
```

Because controlplane nodes are targeted randomly, and the `apiEndpoint` only changes when the node is deleted from the cluster, it is not immediately noticeable as it requires changes with nodes in the cluster. There might also be a trigger when multiple nodes are added simultaneously but I don't have a solid reproducer yet.

**Comment by superseb** [comment]
Steps to reproduce are in https://gist.github.com/superseb/36919dba64a18cb40951228254660f03

**Comment by alena1108** [comment]
Can be tested with `rancher/rancher:v2.2.3-rc2`

**Comment by jira-sync-svc** [comment]
➤ Sowmya commented:

Validated the issue on rancher:v2.2.2

  1. Deployed a cluster with 1 etcd, 1 ctrl, 1 worker nodes. (control plane#1)
  2. scaled up the number of control plane nodes to 2(add control plane#2)
  3. After the cluster becomes Active scale up the number of Control plane nodes to 3. (add control plane #3)

exec into the control plane nodes, and exec into kube-apiserver container*.*

Observations: 

On control Plane#1:

DNS:sowmya-test-ctrl-1, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:127.0.0.1, IP Address:10.43.0.1

On Control Plane#2: 

DNS:sowmya-test-ctrl-1, DNS:sowmya-test-ctrl-2, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:127.0.0.1, IP Address:10.43.0.1

On Control Plane#3:

DNS:sowmya-test-ctrl-1, DNS:sowmya-test-ctrl-3, DNS:sowmya-test-ctrl-2, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:x.x.x.x, IP Address:127.0.0.1, IP Address:10.43.0.1

**Comment by sowmyav27** [comment]
validated this issue. 
In `rancher:v2.2.2` - steps taken:

1. Created a custom cluster - 1etcd, 1 control plane (Control Node#1) , 1 worker node.
2. Scale the number of control planes to 10 nodes - automation provisioning.
3. Wait until the cluster comes to Active state
4. Executed the steps mentioned in - 
https://gist.github.com/superseb/36919dba64a18cb40951228254660f03#run-commands-to-retrieve-info
5. Output received - `$ip is GOOD on certificate`. 
6. Verified that Control Node#1 **did not have** certificate for kube-apiserver with all names and IPs of each controlplane node added in step 2. 
7. Executed steps - 1 to 6, 4 to 5 times.

In `rancher:v2.2.3-rc3` - steps taken:
1. Created a custom cluster - 1etcd, 1 control plane (Control Node#1) , 1 worker node.
2. Scale the number of control planes to 10 nodes - automation provisioning.
3. Wait until the cluster comes to Active state
4. Executed the steps mentioned in - 
https://gist.github.com/superseb/36919dba64a18cb40951228254660f03#run-commands-to-retrieve-info
5. Output received - `$ip is GOOD on certificate`. 
6. Verified that Control Node#1 **had** certificate for kube-apiserver with all names and IPs of each controlplane node added in step 2. Also verified the other control nodes had certificate for kube-apiserver with all names and IPs of each controlplane node. 
7. Executed steps - 1 to 6, 2 - 3 times.
