### ISSUE TITLE
Internal LB listeners are programmed in hosts to expose the ports.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1618]
Server version - V0.29.0-rc1

Steps to reproduce the problem:
Create a LB rule with listener set to "Internal".
Activate the LB service.

Listener ports get programmed in host.
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 6767 -j DNAT --to-destination 10.42.223.235:6767

| 14 | lb-internal  |          5 | loadBalancerService | 2475868e-42dc-4938-abbb-d5d5d537eed6 | lb-1         | active  | 2015-07-22 19:40:06 | NULL                | NULL                | {"fields":{"scale":1,"launchConfig":{"startOnCreate":true,"publishAllPorts":false,"privileged":false,"stdinOpen":true,"tty":true,"readOnly":false,"networkMode":"managed","environment":{},"labels":{},"ports":["7878:81"],"expose":["6767:80"],"count":null,"description":null,"hostname":null,"volumeDriver":null,"workingDir":null,"user":null,"domainName":null,"memorySwap":null,"memory":null,"cpuSet":null,"cpuShares":null,"pidMode":null},"loadBalancerConfig":{"healthCheck":null,"appCookieStickinessPolicy":null,"lbCookieStickinessPolicy":null,"name":"lb-internal config","description":"lb-1"}}}

**Comment by vincent99** [comment]
It seems like there is an actual issue here that @alena1108 is fixing, but a bit of clarification on the terminology:

`"ports"` is the field for listeners that are exposed on the public host IP.
`"expose"` is the field for listeners that are only exposed internally.

These names are somewhat unfortunate, but they're part of compose ([ports](https://docs.docker.com/compose/yml/#ports) and [expose](https://docs.docker.com/compose/yml/#expose)).

The values are both of the form `{listening port}:{default target port}`, and if the default target port is not given then it is implicitly the same as the listening port.

**Comment by sangeethah** [comment]
Tested with build from master:
For  internal Lb listeners , ports are not exposed on the hosts where the LB agents are running.
