### ISSUE TITLE
Pipeline doubts

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#16198]
I'm trying to use the integrated pipeline (v.2.1.0) with our repositories and I have some doubts:

1. I saw that at every build the base image is downloaded from scratch
2. due to point 1, the build doesn't support docker cache for every layer of the image, so the build is always done from scratch (and the build time increases from 1 minute to 16 minutes for us)
3. How to define the namespace to use in the deployment.yaml file ?
4. Is there a way to pass the deployment.yaml file without store it in the repo? different branches should have different deployment rules
5. How can I define the namespace where to put the deployed pipeline? I'm trying the example here (https://github.com/rancher/pipeline-example-maven/blob/master/deployment.yaml) but it deployes the workload inside the same namespace of jenkins
6. How can I check the deployment status in the pipeline? it seems that the pipeline is marked as "success" when it start the deploy without check if all is deployed fine (so I cannot execute post deploy scripts because I'm not sure the deploy is ended successfully)
7. Is there a way to put in pipeline github status updates and slack notifications ?

Thanks

**Comment by gitlawr** [comment]
Hi,
3. You can define namespace in kubernetes manifests. Example:
```
apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: mydeploy
    namespace: mynamespace
  spec: ...
```
4. The Deploy YAML step reads manifest files in the workspace. So you can either put it in the repo or generate one before doing the deploy step. You can also do deployment in some other ways instead of using the Deploy YAML step. An example is to use a kubectl image then operate and manage in kubectl way.
5. Same to <3>, the example deployment goes to the pipeline namespace by default because no namespace is declared for the deployment and it uses a serviceaccount under the namespace.
6. You can add arbitrary stages/steps for different tasks in the pipeline. For example, add a stage/step after the deployment to do some validation tests on your workloads, and do rollback when it doesn't look good. 

For 1/2/7, they are tracked as enhancement issues:
https://github.com/rancher/rancher/issues/16223
https://github.com/rancher/rancher/issues/15984
https://github.com/rancher/rancher/issues/15665

**Comment by Leen15** [comment]
Thanks @gitlawr for answered to my doubts. do you have some examples for point 6 ?

**Comment by luto** [comment]
> How can I define the namespace where to put the deployed pipeline?

That's something I'm also very interested in! Having everything in the same namespace as the pipeline containers and other pipelines is a reasonable default, but doesn't seem to great for production. When trying to create a pipeline like this ...

```yml
apiVersion: v1
kind: Namespace
metadata:
  name: rainloop
---
kind: Service
apiVersion: v1
metadata:
  name: rainloop-service
  namespace: rainloop
spec:
  selector:
    app: rainloop
(...)
```

... the deployment fails:

```
"./deployment.yml": namespaces "rainloop" is forbidden: User "system:serviceaccount:p-7cfgs-pipeline:jenkins" cannot get namespaces in the namespace "rainloop"
```

It is clear to me that jenkins shouldn't be able to modify arbitrary namespaces. But I can't figure out how to give that service account additional permissions so it can access the ones it's supposed to. I'd be very happy about any pointers to docs or relevant code sections to add this functionality, in case it's not there already.

**Comment by luto** [comment]
@gitlawr oh, of course! works just fine now. Thank you!

@Leen15 give it a try :) setting `metadata.namespace` on every resource in `deployment.yaml` does the job, provided the namespace already exists.

**Comment by deniseschannon** [comment]
If there are more questins. please open a new issue.
