### ISSUE TITLE
Rancher WSS Connections are "EOF"'ed when nginx-ingress reloads

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#16301]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
When running Rancher in HA mode in Kubernetes, when the nginx ingress controller on the local cluster reloads (i.e. endpoint change, etc), all WSS connections to rancher are killed with "EOF". This causes any `kubectl -f` commands to also fail.

Steps to reproduce are as follows:
1. Install Rancher HA on an RKE Kubernetes cluster
2. Gather the kubeconfig through the rancher auth proxy for your cluster and use it to open a watched connection, i.e. `kubectl --kubeconfig=rancher-auth-kc-local logs rancher-XXXX -n cattle-system -f`
2. Create a workload/deployment of anything inside of the local cluster in any namespace
3. Create an ingress pointing to the workload
4. Wait for nginx-ingress to reload to update the desired ingress

**Result:**
The `kubectl logs` will fail with the following error message:
```
Endeavor:stuff chriskim$ kubectl --kubeconfig=kc-rancher logs rancher-79977f9d95-4dln7 -n cattle-system -f
...
2018/10/25 21:37:27 [INFO] error in remotedialer server [400]: websocket: close 1006 unexpected EOF
2018/10/25 21:40:36 [INFO] Creating token for user user-qstdm
2018/10/25 21:42:11 [INFO] Handling backend connection request [local:machine-nkwwj]



error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```

Logs inside of the cattle-*-agents looks like:
```
time="2018-10-25T21:37:27Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"
time="2018-10-25T21:37:37Z" level=info msg="Connecting to wss://rancher.192.168.100.126.xip.io/v3/connect with token <redacted>"
time="2018-10-25T21:37:37Z" level=info msg="Connecting to proxy" url="wss://rancher.192.168.100.126.xip.io/v3/connect"
time="2018-10-25T21:42:00Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"
time="2018-10-25T21:42:10Z" level=info msg="Connecting to wss://rancher.192.168.100.126.xip.io/v3/connect with token <redacted>"
time="2018-10-25T21:42:10Z" level=info msg="Connecting to proxy" url="wss://rancher.192.168.100.126.xip.io/v3/connect"
time="2018-10-25T21:42:48Z" level=error msg="Failed to connect to proxy" error="websocket: close 1006 unexpected EOF"
time="2018-10-25T21:42:58Z" level=info msg="Connecting to wss://rancher.192.168.100.126.xip.io/v3/connect with token <redacted>"
time="2018-10-25T21:42:58Z" level=info msg="Connecting to proxy" url="wss://rancher.192.168.100.126.xip.io/v3/connect"
```
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Any
- Kubernetes version (use `kubectl version`):

```
Endeavor:stuff chriskim$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

/cc @alena1108 @aemneina

**Comment by alena1108** [comment]
Happens because nginx ingress controller acts as a global LB for all ingresses in the system - in this case Rancher ingress and user ingresses - and on any update, the nginx config gets reloaded and it results in connection drop for Rancher. There are a couple of ways to address it:

* avoid putting user ingresses on the rancher cluster to minimize the chances of reload
* explore alternative ingress controllers that do reload more seamlessly (haproxy, traefik)

**Comment by deniseschannon** [comment]
Added notes in the docs about how the ingress on k8s cluster should only point to the Rancher application and not other apps.

**Comment by gioppoluca** [comment]
Similar problem on rancher 2.5.8 on K3s
I have a 2 node K3s (latest version at the moment of writing) that seems installed properly with a nginx balancer in front on a separate machine configured as in the documentation.
Installed 2.5.8 using helm.
Trying to add a "custom cluster" and seems that it canno reach the rancher env since the rancher node signal the error of EOF.
Installed cert-manager 1.3.1 that also seems to be working correctly.
Rancher is on a subnet 10.102.184.x on a domain X, while the custom cluster is on a 10.102.185.x on a domain of Y.
We also have an enterprise proxy to cope with.
How can I better debug to understand the situation?
Thanks

**Comment by spatialy** [comment]
Hi @gioppoluca were you able to dig deep on this? We are in a similar situation.

Best
