### ISSUE TITLE
ActiveDirectory Authentication/Site Access Settings Broken

### ISSUE THREAD

**Issue by drewboswell** [rancher/rancher#16313]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add Activedirectory authentication
2. submit activedirectory authentication with test user

**Result:**
1. You cannot add any group the test user is not part of
2. You cannot add any user 
3. when logging in to rancher U.I. with another admin level user, you can only add the groups you are part of to the authentication section.

**Other details that may be helpful:**
It appears that when it calculates/compares principals, it only compares it to the currently logged in user.

I tested using another AD user in the test section and had the same trouble, I could only add groups he was in.

*logs of failed attempt*

```
2018/10/26 08:40:13 [DEBUG] Impersonating user user-5qw69, groups [activedirectory_group://.....redactedstuff system:authenticated]
2018/10/26 08:40:13 [DEBUG] REST GET apis/management.cattle.io/v3//authconfigs/activedirectory
2018/10/26 08:40:13 [DEBUG] Failed to determine if object is type: activedirectory_group
2018/10/26 08:40:13 [DEBUG] Failed to determine if object is type: user
2018/10/26 08:40:13 [DEBUG] Query for getPrincipal(): (objectClass=group)
2018/10/26 08:40:13 [DEBUG] Now creating Ldap connection
2018/10/26 08:40:13 [DEBUG] Failed to determine if object is type: user
2018/10/26 08:40:13 [DEBUG] Failed to determine if object is type: user
2018/10/26 08:40:13 [DEBUG] Failed to determine if object is type: group
2018/10/26 08:40:13 [ERROR] Unknown error: Failed to get attributes for 

```

**Environment information**
- Rancher version: 2.1.1
- Installation option (single install/HA): Single install

- Docker:

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859GiB
Name: ..
ID: ..
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by drewboswell** [comment]
Is this a known issue? Have you had clients / open source users that have reported similar problems and perhaps a workaround?

If confirmed (and it's not just me noobing out) essentially this makes the product unwieldy when using security groups, and I would image many people would be dissuaded from using the product because of it.

**Comment by mrajashree** [comment]
Hi @drewboswell, no this has not been reported by other users. Can you make sure your User Search Base and Group Search Base are broad enough to find the users/groups you are looking for?

**Comment by deniseschannon** [comment]
With AD, you can only list the groups that the user doing the search is part of. It sounds this is working  as designed.

**Comment by deniseschannon** [comment]
Sorry about that, in AD you should be able to search for groups even if you are in them. 

@drewboswell Can you make sure your User Search Base and Group Search Base are broad enough to find the users/groups you are looking for?

**Comment by drewboswell** [comment]
The weird thing is that it looks like it is performing searches on my own currently logged in user, rather than the user/pass given in the /g/security/authentication/activedirectory page.

What then happens is that if as an admin you don't have the same group as someone you are administering... you get "Unable to fetch user info"s all over the place.

**Comment by drewboswell** [comment]
Any news on this... It has been open for a while now and the misbehaviour is still there.

**Comment by zakufish** [comment]
We are experiencing this issue as well.
The Active Directory seems to be working (successfully located the group) first, but showing "unable to fetch user info" later on. I could still login through LDAP credentials, but adding cluster membership is problematic at the moment as Rancher isn't able to fetch the group based on my LDAP search.

**Comment by mrajashree** [comment]
@drewboswell @zakufish Can you make sure that the group you are searching for falls under Group Search Base you have set while setting up auth?

**Comment by zakufish** [comment]
Hi @mrajashree here're the steps we executed to set up auth.
1. Configure Rancher AD and test & apply the config.
2. Add restrictions, in which I could successfully locate the group in the dropdown list based on my LDAP search query.
3. Add member group to the cluster.

10-15 minutes later, we started to see the following messages on Rancher GUI:
<img width="1299" alt="Screen Shot 2019-06-07 at 2 19 05 pm" src="https://user-images.githubusercontent.com/15952327/59081016-512eca80-892f-11e9-9151-217dc75164db.png">

However, we are still able to login into Rancher using LDAP credentials, but everything else that requires LDAP permission is broken (including the cluster member access).

**Comment by drewboswell** [comment]
@mrajashree please read previous responses. Question already asked. Already answered. I'm amazed such a problem exists after such a long time. Does no one use rancher in production with AD?!

**Comment by mrajashree** [comment]
@zakufish Were you logged in as the local admin when you got the unable to fetch user info error? Also the cluster member access won't work with the option you have selected in the screenshot, you'll have to select the second option "Allow members of Clusters, Projects, plus Authorized Users and Organizations" for that.

**Comment by mrajashree** [comment]
@drewboswell Yes I have read your previous responses, they do not signify that the search bases are broad enough. It’s important to know that, because if they aren’t then search won’t work. AD is used widely in production by rancher users but they do not face the same issue. Now to debug this one you can check the following
1. You said that you “cannot add any group the test user is not part of” - For this we need to check the search query. In our debug logs, you should find following two logs:
`LDAPProvider searchGroup query:` and `LDAPProvider searchUser query:`
Can you run ldapsearch command against your AD setup using the following:
Filter from above `searchGroup` log, service account creds, search base narrowed down to the Group Search Base you provided.
Let us know if this gives you the groups you want to add.
You can test the same for the searchUser log with user search base
2. “Unable to fetch user info” - This will happen only after you have been able to search for and add a principal (group/user) to rancher. Is this happening for some user you added since you haven’t been able to add any groups?
3.
```
The weird thing is that it looks like it is performing searches on my own currently logged in user, rather than the user/pass given in the /g/security/authentication/activedirectory page.
```
Not sure what this means, is this while you’re adding a user/group using the search text box? we always use the service account creds you provided during auth setup for this. Not the test user creds

**Comment by mrajashree** [comment]
@drewboswell  Yes I have read your previous responses, they do not signify that the search bases are broad enough. It’s important to know that, because if they aren’t then search won’t work. AD is used widely in production by rancher users but they do not face the same issue. Now to debug this one you can check the following
1. You said that you “cannot add any group the test user is not part of” - For this you need to check the search query. In our debug logs, you should find following two logs:
`LDAPProvider searchGroup query:` and `LDAPProvider searchUser query:`
Can you run ldapsearch command against your AD setup using the following:
Filter from above `searchGroup` log, service account creds, search base narrowed down to the Group Search Base you provided.
Let us know if this gives you the groups you want to add in Rancher.
You can test the same for the searchUser log with user search base
2. “Unable to fetch user info” - This will happen only after you have been able to search for and add a principal (group/user) to rancher. Is this happening for some user you added since you haven’t been able to add any groups?
3.
```
The weird thing is that it looks like it is performing searches on my own currently logged in user, rather than the user/pass given in the /g/security/authentication/activedirectory page.
```
Not sure what this means, is this while you’re adding a user/group using the search text box? we always use the service account creds you provided during auth setup for this. Not the test user creds

**Comment by drewboswell** [comment]
DISCLAIMER: I have not tried the last 4 months of versions.

In the last couple of conferences I've been to (including barcelona kubecon 2019), many users have mentioned this annoying display bug which makes administring difficult/painful.

People have commented here as well : #14343

2. It happens for any user that is not part of a group it's trying to see. (which is what led me to believe that it is in fact not using the service account for display purposes)
3. I understand that it is the intended logic, but based on 2. it doesn't look like it's the case.

I am moving away from live-edit solutions like rancher, ion favor of cluster read-only solutions using gitops so I won't be of any help for this issue. Hopefully someone will be able to point the bug out or pull request it for you.

**Comment by rmalchow** [comment]
this is still open. and it is still an issue that it says "unable to fetch user info", apparently disallowing access to that info, and yet the id is the full dn of the LDAP object. 

i think this needs a big reworking on the UI side. specifically, it would make sense (and this is a HUGE issue for us) to severely limit the ability to search for users and groups. as it stands now, the second that you have any permissions at all, you can perform searches on the AD. we're currently solving this with adding rather complex LDAP search filters - however, i'd rather not have the search function at all, or limited to admin users. 

also, the fact that your AD permissions govern what you can see in the rancher UI is a bit ... unfortunate. this means that effectively, we have to do a lot of authorization config on the AD that has nothing to do with the AD as we use it otherwise. we would appreciate it if a.) adding users or groups would require a full DN and searches (if needed at all) would be limited to certain (admin) users and b.) users that can list members can also see their info. 

what definitely does not make sense to me is the fact that the ID is generated from the RDN and visible, but the CN (or whatever name attribute) is not.

**Comment by kalebharrison** [comment]
I'm facing the original issue as well.
My AD auth configuration is very broad with User and Group search bases and no search filters within the schema.

I can also add all of the groups that the initial AD user used to "test" the AD auth is currently a member of - So it appears the "test" logic is able to correctly get a response on the Query for getPrincipal.

When searching for a user or group in the Security->Authentication->Site Access location, the initial LDAP/AD query is able to find the groups and users and list them out. When you select one of those users or groups, it appears to fail to correctly take that CN information for that user/group you selected and add to the Query for getPrincipal and bombs out. This is indicated by the blank value in the query.
**[DEBUG] Query for getPrincipal(): (objectClass=group)**
Where you would expect it to look like
**[DEBUG] Query for getPrincipal(_CN=Group1,DC=CORP,DC=COMPANY,DC=com_): (objectClass=group)**

I have two installations where it works correctly in one, but not the other. The authentication configuration is identical between the two installations and have been compared via the API.

**Comment by kalebharrison** [comment]
My issue has been resolved -

The root cause for my issue is in relation to using a http load balancer in front of Rancher. In this use case, nginx was used and the proxy_pass had a trailing slash afterwards which caused the ldap query from the UI to be **ldap///:blah** instead of **ldap//:blah**.
From my understanding, this issue is possible from most other layer 7 load balancers but most clients will convert http:/// to http://. 
In this case the UI side of Rancher acts like a client for the ldap query and is not converting /// to // which causes the invalid query.

This location configuration did not work -

```
    location / {
        proxy_http_version 1.1;
        proxy_buffering off;

        proxy_set_header Host $host;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass https://rancher.backend/;

        proxy_read_timeout 900s;
    }
```

This location configuration did work -

```
    location / {
        proxy_http_version 1.1;
        proxy_buffering off;

        proxy_set_header Host $host;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass https://rancher.backend;

        proxy_read_timeout 900s;
    }
```
