### ISSUE TITLE
Helm template failed

### ISSUE THREAD

**Issue by fadeAce** [rancher/rancher#16337]
Helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: redis : exit status 1

this happened when I'm trying to install harbor in kubernetes cluster ,
![image](https://user-images.githubusercontent.com/20850645/47649219-8ca63100-dbb7-11e8-80e0-47776986d8d8.png)
I manually added harbor 
![image](https://user-images.githubusercontent.com/20850645/47649262-a9426900-dbb7-11e8-9ff2-abd7453f5846.png)
from here : _https://github.com/goharbor/harbor-helm_
I've no idea about it  🔢

**Comment by fadeAce** [comment]
this is from catalog , which I manually added it

**Comment by guangbochen** [comment]
The latest version should works now in https://github.com/goharbor/harbor-helm. 
And for rancher's catalog that uses git protocol, it is required to download the dependency charts using `helm dep update` and push the `/charts` directory together to the git repo.

**Comment by guonl** [comment]
I also had the same problem, the latest version is still unresolved. I used this version:  harbor:1.1.1

**Comment by chris-aeviator** [comment]
I'm experiencing this when forking https://github.com/helm/chart and using this as a catalogue. I've modified a single chart (airflow, changed the docker-airflow container to a private reg) & now cannot install it anymore due to `Wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql, redis : exit status 1` where `postgresql` & `redis` are both still inside my forked helm chart catalogue and in the original.
