### ISSUE TITLE
Add ability to customize footer section of UI login page

### ISSUE THREAD

**Issue by garyellis** [rancher/rancher#16474]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Other details that may be helpful:**
Currently, the Rancher Settings section of UI allows customizing UI private label at login screen only.
Often times, administrators/platform teams will want to add company specific fields such as: access requests, internal urls, support email addresses, notifications, or etcetera somewhere on the login screen. (i.e. footer section)

Add the ability to set user defined fields "key/value pairs" to the footer section of the Rancher UI login page. Additionally, add support to render html or markdown for url and email address hyperlinks.

**Comment by vincent99** [comment]
Add a `ui-footer-links`Setting that takes a Jason array of something like `[{class: 'bg-success', icon: 'icon-name', title: 'Blah', link: 'http://blah', targetBlank: false}]`

All are optional (default blank to true), though obviously if you leave enough out nothing gets displayed.

No raw HTML, a setting that does arbitrary HTML injection into all pages for all users is not a good idea.

And this needs https://github.com/rancher/rancher/issues/16468 first because another request to load a setting 99.9% of installs don't use is crazy.
