### ISSUE TITLE
GitHub auth provider member autocomplete disregards hierarchy.

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#16547]
In github we use teams and sub-teams for project level access. 
People with parent-team access have access to all the teams below.

In rancher the only groups that are displayed are those that you are directly set a member of (so in this example the parent group) making it impossible to see/add a team further down the chain (which you still have access to in github) to assign to a project.

**Comment by jfrederickson** [comment]
I've just started giving Rancher a try, and this feels like it'll be a usability issue for our use case. Along similar lines, the UX here is tricky when you have more than one team across different orgs with the same name:

<img width="602" alt="screen shot 2019-01-30 at 9 50 37 am" src="https://user-images.githubusercontent.com/1923178/51989866-e39cfa00-2475-11e9-93a1-88f3fc021858.png">

When you select one of these, the text field above is filled in with the name of the team. It turns out that it actually is keeping track of which one you selected (I think, based on looking at network activity), but it looks like just a plain old text field, so that's not super obvious.

**Comment by ChrisMcKee** [comment]
it would be nice to be able to say "only in this org". 
The search experience is only as bad as GITHubs in that sense though.
