### ISSUE TITLE
Etcd snapshot container is not deployed after upgrade

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#16556]
rancher/rancher:v2.1.2-rc9

Etcd snapshot container is not deployed after upgrading to v2.1.2-rc9. Rancher server logs do not show `rke up` being triggered for RKE clusters.

To reproduce: 
* Deploy Rancher server v2.1.1
* Provision an RKE cluster (in this case, used Azure)
* Upgrade to v2.1.2-rc9
* Etcd snapshots are enabled in cluster yaml / UI
* ssh to etcd node

`docker ps`  on etcd node shows no snapshot container
`/opt/rke/etcd-snapshots` does not exist

Expected:
* `etcd-rolling-snapshots` container to be running
* `/opt/rke/etcd-snapshots` exists

**Comment by bmdepesa** [comment]
Viewing in the API also shows that snapshots are enabled:

```
services": {
"etcd": {
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": true,
"type": "/v3/schemas/etcdService"
},
```
After editing & saving a cluster, the container is started and the directory is created. 

We will document that the clusters will not be automatically updated without saving.

**Comment by alena1108** [comment]
The fix can be to remove norman annotation defaulting value to true, and do the defaulting in the store (always not nil value, true or false based on user input). Leave the type as pointer though so standalone rke can default if the value is nil

**Comment by maxkorp** [comment]
Went over this with Craig and Darren, and decided to change things a bit.

For existing clusters with a nil value, we want this to be interpreted as false. Currently, snapshots wont start anyways until the cluster is updated, so this part is ok.

- To fix the value showing up in the UI as true, we are changing norman so that Non-nullable values who's key is not present are assigned the empty value during get/list, rather than the default value. 

- To ensure that existing clusters don't suddenly start snapshotting, when we update clusters in rancher, before we pass the update down to kontainer-engine, if the snapshot value is nil, we set it explicitly to false. 

This way the default is still true, so on create the UI gets true as the default, and in RKE the default is still true, so that when it is omitted creating clusters with RKE it is still enabled

**Comment by alena1108** [comment]
> To fix the value showing up in the UI as true, we are changing norman

fyi we have `release/v2.1` branch in norman - the last commit of this branch is vendored in to rancher's `release/v2.1`.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.1.1 to v2.1.1-rc13.
After upgrade, the etcd snapshot was still disabled as expected
<img width="1218" alt="screen shot 2018-11-21 at 11 56 17 am" src="https://user-images.githubusercontent.com/18536626/48865788-78ec8580-ed85-11e8-88f3-80590445bef2.png">
Edited another parameter(PSP) and after the update succeeded, the etcd snapshot field was still disabled as expected

**Comment by maxkorp** [comment]
We decided to change this such that on upgrade clusters are legitimately not snapshotting, so it should show as false.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.1.1 to v2.1.6
1. Created a 3 node DO cluster in v2.1.1
2. Created workloads. 
It was observed that ` "snapshot": false, ` was set in API 
```
"services": {
		"etcd": {
    		"extraArgs": {
         		"election-timeout": "5000",
         		"heartbeat-interval": "500"
     		},
     		"snapshot": false,
     		"type": "/v3/schemas/etcdService"
 		},
```
3. Upgrade rancher to v2.1.6. After upgrade the `etcd-rolling-snapshots` containers are still not deployed

```
"services": {
		"etcd": {
    		"extraArgs": {
         		"election-timeout": "5000",
         		"heartbeat-interval": "500"
     		},
     		"snapshot": false,
     		"type": "/v3/schemas/etcdService"
 		},
```
4. Edit the cluster and enable the etcd snapshot with creation time as 5m. After the cluster update completed, the `etcd-rolling-snapshots` containers were deployed and running. The snapshots were created at intervals of 5m as set. `"snapshot"= true` is set in the API as below:

```
services": {
"etcd": {
"creation": "5m",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "2h",
"snapshot": true,
"type": "/v3/schemas/etcdService"
}

```

Note: After rancher upgrade from v2.1.6 to master build from Feb 19, `Snapshot = true` is  set in the API. The `etcd-rolling-snapshots` continue to run and snapshots are taken at the set interval. 
After editing and saving the local etcd backup settings, cluster gets updated and “snapshot=false”  is set in the API since legacy backups are disabled
