### ISSUE TITLE
Upgraded Helm Catalog App not showing new deployments

### ISSUE THREAD

**Issue by fabiorauber** [rancher/rancher#16568]
**What kind of request is this:** Bug

**Steps to reproduce (least amount of steps as possible):** 
1. Install Helm catalog app containing one deployment and another one triggered by a variable
2. Upgrade Helm catalog item changing the variable that triggers another deployment install

**Result:**
New deployment is seen only on Workloads but not inside the Catalog App.
Catalog App view:
![captura de tela de 2018-11-13 15-24-56](https://user-images.githubusercontent.com/2218824/48431279-7d4aea00-e758-11e8-9090-d4a7029e1fe7.png)

Worloads view:

![captura de tela de 2018-11-13 15-25-10](https://user-images.githubusercontent.com/2218824/48431298-86d45200-e758-11e8-818f-54820f179583.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.1.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type: Self-Hosted via docker-machine
- Machine type (cloud/VM/metal): XenServer VMs
- Kubernetes version: v1.11.3

**Comment by strainovic** [comment]
I ran into same the same problem. Not only workloads do not show but also all of other new resources.

**Comment by rmweir** [comment]
this appears to be fixed in master:
validated behavior in v2.1.1, v2.1.11
validated behavior is gone in latest rancher image

**Comment by jiaqiluo** [comment]
Validated the bug is already fixed in 
- Rancher:v2.2.7
- Rancher:master-head 7277535d

Steps:
- add the catalog: https://github.com/interlegis/il-charts
- deploy the app `portalmodelo` without any answer variable
- see that there is one deployment showing in both the app page and the workload page 
- edit the app to add the following variable: `instance.zeoclient = true`
- see that a new deployment shows in both the app page and the workload page
