### ISSUE TITLE
Informational text should not be red

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#16562]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Create a new custom cluster, then click on the cluster. Informational text should not be red. Normally red indicates an error. 

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/468462/48395626-b2115f80-e6cc-11e8-948d-9a904b1b9725.png">

If possible, should fix all places in the UI that currently use red text that are not errors.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
v2.1.1

**Comment by tfiduccia** [comment]
Version - master 8/29
Message banner is now blue.

**Comment by vincent99** [comment]
I changed the background of the banner to match the color the cluster state would be instead of always being error colored.  Previously only the detail message (2nd line) reflected the cluster state color (so it's sometimes text-info/blue)

But the screenshot for @dnoland1 it's still going to look exactly the same in that situation, because the cluster is (apparently) in `transitioning=error` state and the 2nd line is already red.

So that is an unrelated issue for deciding if/when a cluster that's changing should return `transitioning=yes` vs `transitioning=error`.
