### ISSUE TITLE
Adding system namespace in project

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#16588]
As long as we need to deploy some system components per project like jenkins, registry in pipeline, we should put those components into a special namespace per project.

The namespace could be named as <project-id>-system and Rancher will have a controller to ensure the namespace will not be move to other project. Other than that, the system namespace should have no different from other namespace in the project. The users(admin or not) belong to the project can operate those resource in system namespace.

Also we will move those components into the project system namespace in the upgrade.

**Comment by cjellick** [comment]
Discussed with @ibuildthecloud and @cloudnautique. Conclusions:
1. You need to support N namespaces per project. Bill wants a namespace for prometheus and a different one for pipelines, per project
2. Project owners and members by default should have no access to the namespaces. The cluster owner owns and manages them.
3. Because of item 2, the most striaghtforward solution is to place these namespaces in the system project, instead of each individual project

**Comment by cjellick** [comment]
think that through and let me know if you find any flaws in that approach

**Comment by loganhz** [comment]
Close it as we don't need system namespace in project now
