### ISSUE TITLE
Backport Mitigate kubernetes API timeouts in rancher server

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#16599]
Backport for https://github.com/rancher/rancher/issues/16598

**Comment by cjellick** [comment]
Note that this is NOT the same as the cluster going to unavailable. That is tracked separately.

**Comment by soumyalj** [comment]
Reproduced the issue is v2.1.1 as below:
<img width="1399" alt="screen shot 2018-11-23 at 1 28 06 pm" src="https://user-images.githubusercontent.com/18536626/48960719-f2ba7580-ef23-11e8-98b0-6085b3d0cf7c.png">

Tested with v2.1.2-rc14 . Created AKS cluster . Created few projects and workloads and the setup was left around for 30 to 90 minutes. After the idle time, when I navigated to different projects, I see that the spin could be longer, but eventually it succeeds without the error message.
