### ISSUE TITLE
Running Rancher on hosted k8s (GKE/AKS/EKS)

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16627]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Investigate how/if to support running Rancher on hosted k8s (and which) besides RKE clusters.

**Comment by mvisonneau** [comment]
The only blocker I see for the moment is the backup/restore procedure. What I believe would be required is an alternative one that would allow us to perform them without having to access etcd directly.

**Comment by alena1108** [comment]
As a part of evaluation, have to test backup/restore. And document the procedure in case it's different from the rke install.

**Comment by mvisonneau** [comment]
I have tested it using https://github.com/heptio/velero it seems to work. Backup is easy but it is not that trivial to restore.

**Comment by bottkv488** [comment]
> I have tested it on EKS using https://github.com/heptio/velero it seems to work. Backup is easy but it is not that trivial to restore.

@mvisonneau, so etcd backups were succesful?
Could you share some details about your restore attempts/challenges, please?

**Comment by mvisonneau** [comment]
With Velero you backup Kubernetes resources. It has been a while now and we haven't followed up this direction given the restoration issues. On top of my mind there were 2 things:
- The main issue was the fact that you had to manually update the replica count for rancher deployment to `0` so that Velero has the time to restore all CRDs before rancher attempts to recreate and reinitialise them itself.
- The second was related to Velero itself, not sure if it has been fixed now, but you had to restore the backup twice as on the first attempt it would only recreate the CRDs API definitions and on the second, restore the actual data.

**Comment by joberdick** [comment]
I have just noticed the official statement in the install docs: https://rancher.com/docs/rancher/v2.x/en/installation/ha/

"IMPORTANT:
It is not supported, nor generally a good idea, to run Rancher on top of hosted Kubernetes solutions such as Amazon’s EKS, or Google’s GKE. These hosted Kubernetes solutions do not expose etcd to a degree that is manageable for Rancher, and their customizations can interfere with Rancher operations. It is strongly recommended to use hosted infrastructure such as EC2 or GCE instead"

I think is a pretty big limitation. Rancher could have a backup/import process for its own state. Making access to ectd irrelevant.

Being able to run Rancher on managed kubernetes is big win in my opinion.

**Comment by bradjones1** [comment]
I am, as well, a bit surprised to see such a strong statement in the docs, especially as Rancher engineers have not indicated such a strong position on related issues in the queue (in my experience.) However, since most of the work on the project is done by Rancher Inc., I would think this probably represents internal consensus rather than something that's been worked through publicly. (Which is totally fine, of course, but doesn't help for the rest of us to understand the context.)

> These hosted Kubernetes solutions do not expose etcd to a degree that is manageable for Rancher...

It's no surprise that the recommended method for installing Rancher is RKE, and I assume part of this is to reduce the edge cases that Rancher will have to support, since paid support is the business model.

For those of us who are running Rancher 2.x in managed environments, I would like to see more expansion on the quote above in particular. As I've become more familiar with Rancher, I summarize its value proposition in a hosted environment thusly:

* For multi-cluster environments, it provides a unified authn/authz interface where Kubernetes does not provide one natively, and
* Rancher provides some helpful resource finalization/controllers to help less-technical users navigate Kubernetes, such as automatically creating services for workloads and linking image pull secrets to deployments, for instance.

While it is certainly true that etcd is not directly accessible in most managed environments, the fact that Rancher stores its configuration in CRDs means it's rather simple to back up Rancher with tools like Velero.

> ...their customizations can interfere with Rancher operations.

On this point, similar to the point regarding etcd, begs for some clarification. I have not [yet] run into a situation in which Rancher's controllers interfere with GKE. However, it is certainly possible that functionality such as cluster logging or Istio provisioning may overlap/duplicate/interfere with similar functionality that is offered by a hosted cluster. In this case administrators can, depending on the feature, choose either Rancher's management or the cloud provider's, and perhaps the UI could warn when known conflicts are foreseen.

It's also true that in some cases Rancher will fail to recognize a cluster's node type, requiring some manual fixes to paths for logging (https://github.com/rancher/rancher/issues/14425#issuecomment-407602873) and automatic generation of network policy rules has been disabled for some time in non-RKE clusters (https://github.com/rancher/rancher/issues/14085) - the type of issue that I think they're referring to.

I don't think any of the above is an absolute contraindication to running Rancher in a managed cluster, however. I would be interested to know if this recommendation is more technical in nature or related to a desire to limit the range of supported environments for business reasons.

**Comment by Kampe** [comment]
This seems very strange to me given the alternatives to hosting a HA Rancher management plane. It seems that this is a missing link in the Rancher toolchain, an elegant solution for hosting a HA Rancher management plane. When I saw the docs that basically amount to "run it in docker on a linux host" I giggled a bit.

**Comment by egagala** [comment]
Are there any more insights on limitations running Rancher on managed Kubernetes (particularly on EKS)? Statement in Rancher  documentation doesn't provide enough details.

**Comment by vincent99** [comment]
You can do what you want, but we don't support it.

You do but have access to atomically backup etcd as a whole from the "outside"; backing up and restoring pieces from the "inside" (valero) is not the same thing, not necessarily successful, and we don't test it.

You also have no control of the configuration or scaling of etcd, and no recourse if something happens (e.g. the keyspace becomes maxed out).

**Comment by bradjones1** [comment]
For what it's worth I think there are many of us finding success with Rancher in a hosted environment, but as Vincent points out, no official support. Beyond that of course, you don't have any support SLA from Rancher without a _paid_ relationship, either, so there are two levels to this question - what are you willing to maintain and operate on your own, and what is your expectation internally that you can manage those edge cases?

**Comment by travis-sobeck** [comment]
FWIW I asked Azure about backup/restore of etcd in AKS and got this response.
"As etcd is part of the managed Control Plane, as of today, there's no possible procedure for the user to back up the etcd database"
"As etcd is part of the Managed Control Plane, by default etcd has been deployed in high availability with an automatic backup process and our Product Group will be able to recover in case of failure. Also, Uptime SLA can be an option that could be enabled on active and new clusters"
That being said I have not actually tried to have Azure do a restore to validate it would really work out well.
Even if it did, its still a problem because you can never pick-up your rancher server and move it anywhere so you are always tied to that "one specific" cluster.
Assumming this statement is true: "These hosted Kubernetes solutions do not expose etcd to a degree that is manageable for Rancher..." then I have to wonder, is relying so heavily on etcd for this application the best choice.  In world where there is more and more of push to the cloud, managing your own RKE cluster in cloud with so manage managed k8s options seems less than desirable IMHO.

**Comment by SayakMukhopadhyay** [comment]
I have tried out Gardener (https://gardener.cloud/) and it can be deployed on a managed k8s service like AKS. They do this by creating a "virtual" cluster which has its own etcd and stuff. Maybe something similar can be used here?

**Comment by joberdick** [comment]
In case anyone missed it. Rancher 2.5 resolves this issue. Thanks to everyone who contributed to that!

**Comment by bradjones1** [comment]
@joberdick Do you have a link to release notes or an issue/PR that backs up the "resolution"? This is more of a meta ticket to begin with so I'm curious what you're specifically referring to.

**Comment by joberdick** [comment]
@bradjones1  https://rancher.com/blog/2020/rancher-2-5-delivers-enhanced-full-lifecycle-management-eks-clusters

"Also, it is now possible to run the Rancher application on EKS clusters. Before Rancher 2.5, backups of the Rancher application required etcd snapshots of the management cluster. This caused problems for operators looking to run Rancher on hosted Kubernetes solutions like Amazon EKS because there are no etcd backups. In Rancher 2.5, a new backup restore operator can back up the Rancher management server data to S3 or a volume in the Kubernetes cluster. With this new backup utility, you can now safely run the Rancher management server on Amazon EKS clusters."

**Comment by bradjones1** [comment]
Interesting. We're on GKE, though I don't particularly see anything here that couldn't effectively `s/EKS/GKE`... but worth a look. Thanks for the pointer. Might be an opportunity for some documentation (rather than a blog post) to dive more into the actual mechanics as they apply more broadly to "imported" clusters where you do not have direct access to etcd.

**Comment by travis-sobeck** [comment]
> @bradjones1 https://rancher.com/blog/2020/rancher-2-5-delivers-enhanced-full-lifecycle-management-eks-clusters
> 
> "Also, it is now possible to run the Rancher application on EKS clusters. Before Rancher 2.5, backups of the Rancher application required etcd snapshots of the management cluster. This caused problems for operators looking to run Rancher on hosted Kubernetes solutions like Amazon EKS because there are no etcd backups. In Rancher 2.5, a new backup restore operator can back up the Rancher management server data to S3 or a volume in the Kubernetes cluster. With this new backup utility, you can now safely run the Rancher management server on Amazon EKS clusters."

That's good to know, I'll have to look into it.

**Comment by joberdick** [comment]
@bradjones1  Yea, the blog is specific to EKS for some reason but the backup solution could be used on any cloud provider. Its a new stand alone backup operator that you can send backups to S3 or PV's https://github.com/rancher/charts/tree/main/charts/rancher-backup

**Comment by SayakMukhopadhyay** [comment]
Specifically this point might be the most useful https://rancher.com/docs/rancher/v2.x/en/installation/#changes-to-installation-in-rancher-v2-5
The documentation uses the words 
>such as Amazon EKS clusters.

which makes me believe that this should work on other cloud providers too. We are on AKS and hopefully it works for us. It would be great if someone from the Rancher team confirms that Rancher 2.5+ can be installed on EKS/GKE/AKS. Such a confirmation should be enough to close the ticket too.

**Comment by vincent99** [comment]
Rancher has always "worked" on any cluster, but we only supported our own distros because there was no way to backup or restore the configuration reliably on things where you don't control the database.  The backup operator resolves that.

**Comment by dnoland1** [comment]
See https://rancher.com/support-maintenance-terms/ for the official list of what Rancher Labs supports. You can install Rancher v2.5.x on all three of the major cloud providers' hosted Kubernetes - AKS, EKS, and GKE.
