### ISSUE TITLE
DigitalOcean no longer supports Ubuntu 14.10

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1666]
We need to remove Ubuntu 14.10 from the UI as it's no longer supported by DigitalOcean.

**Comment by haswalt** [comment]
Instead of having a limited list of images in the UI, why not load the available image list when using DigitalOcean from their api? https://developers.digitalocean.com/documentation/v2/#list-all-distribution-images

That would make other images like the docker image with the memlimit kernel enabled available as well as more manual images.

**Comment by deniseschannon** [comment]
@haswalt It's a bit more complicated than just listing what's available through DigitalOcean. Since we provision using `docker-machine` and not directly through DO, some of the images that you can provision in DO is not supported using `docker-machine`. I don't believe that there is a way to get a list of what drivers are supported from `docker-machine`.

**Comment by haswalt** [comment]
I'd be happy to look into it



On 27 Jul 2015, at 22:59, Denise <notifications@github.com<mailto:notifications@github.com>> wrote:


@haswalt<https://github.com/haswalt> It's a bit more complicated than just listing what's available through DigitalOcean. Since we provision using docker-machine and not directly through DO, some of the images that you can provision in DO is not supported using docker-machine. I don't believe that there is a way to get a list of what drivers are supported from docker-machine.

-

**Comment by haswalt** [comment]
Also if using the docker images for DO for example docker-machine wouldn't be required in that instance either so under if something clever can be done there. At the moment I build all my DO hosts as custom machines since the options from the UI are too limiting

**Comment by will-chan** [comment]
Yeah, we can probably do as you suggest and make a direct query to DO to grab the images.  We had to integrate with AWS in a similar manner because just trying to figure out what subnet/vpc/zone/instance types/security groups all worked together was too error prone.

**Comment by deniseschannon** [comment]
Verified that Ubuntu 14.10 is no longer listed as option for DO. v0.31.0-rc4

Created an enhancement request for the other issues.
