### ISSUE TITLE
Service Discovery Integration with public DNS

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1675]
Today the only way to make service - regular or load balancer - available to the public is by binding its port the host. And even then it can be accessed by the host ip only, not by its DNS name. What users been doing so far is:

1) Scheduling services on a particular Rancher host, so host's ip is known beforehand. 
2) Registering Rancher host to the public DNS

Downsides of this approach is that the user has to keep track of services vs hosts; adding host to DNS once service is up on this host,  and when the service is removed from the host, host has to be removed from the DNS.

All the above concludes the need for Service Discovery Integration with Public DNS support. So Rancher will handle public DNS entries management as a part of Service Discovery solution.

**Comment by dxxxxxg** [comment]
When is this feature planned on being released?

**Comment by deniseschannon** [comment]
It should be out around 2-3 weeks.

**Comment by kaos** [comment]
What've done to solve this is to have a Load Balancer on run on each rancher host, routing the traffic to the right services. That way we can point a public DNS entry to any (all) hosts regardless of on which host the service actually runs, and have the load balancer route the traffic to its final destination. No need to meddle with the DNS record for moving services.. :)

**Comment by vincent99** [comment]
That works, but if a host disappears its IP will still be in the public DNS entry and one out of N request will be sent to a black hole.  That's why you'll need DNS integration :-) (or public IPs that can be moved, or anycast, or...)

**Comment by kaos** [comment]
Ah, yes. I don't expect too frequent changes to the number of hosts. On a related note, is there any hook or such that I could use that would be triggered when a new gets added/removed? (I could use that to update our dns.. :)

**Comment by flaccid** [comment]
From the DNS provider side, I would like Route 53 support please.

**Comment by Kelindar** [comment]
How this integration is going to work? This is necessary but looks to me quite complex to get right. 

Currently what I'm doing with Rancher is simply building-in this functionality in the services themselves which get registered to Route53. Going forward, I was thinking of building an additional service which can query Rancher DNS and do the public DNS service registration.

**Comment by lavvy** [comment]
@Roman that would be very awesome. What's your time line ? Is it going to
be integrated into rancher ?

**Comment by vincent99** [comment]
We haven't really specced out exactly how this would work/with who.  The obvious thing is just building route53 support, but I would like it to be pluggable for other providers (beyond the big few are infinite smaller ones and $your_company's custom thing) and not require us to write/package/maintain support for those providers and storing the keys to your registrar or DNS provider in our database.

So I'm thinking this is maybe a good place to start with bring a webhook provider, and we maintain images for a couple of the biggest providers as images you can run as a service and register to receive the hook calls.

**Comment by vincent99** [comment]
@ibuildthecloud @alena1108 --^

**Comment by kaos** [comment]
@vincent99 that sounds like a good idea. I'm hoping your idea of a webhook provider is to call a hook for basic events in rancher like a container is started, stopped, deleted etc.. then the hook can inspect the event subject to find out the data it needs depending on what function it is carrying out.

I'm thinking for the DNS stuff, in our case we want custom DNS entries added for certain services. We could then have labels attached to those services, and a another DNS updater service can then receive hooks for when containers are launched and update the DNS based on those labels.

These ideas actually shift slightly the implementation I'm currently working on for how we're going about to solve precisely this, so that in the future we could rely on such webhooks instead of what I'm working with now.. :)

**Comment by vincent99** [comment]
Something like that yes; we'd have to work out the right level of granularity for what the events are and what resources they apply to.

There is a websocket you could largely do this with today.  It it is lower level than a normal user would want and has no delivery guarantees, but the UI uses it to receive copies of resources as they change and keep the screen up to date.

Still I thought I'd mention it because if you're building something today it may be better than polling lots of resources  :-) `ws://rancher-host:8080/v1/subscribe?eventNames=resource.change`

**Comment by kaos** [comment]
@vincent99 thanks, that's good info there :)

**Comment by lavvy** [comment]
Yeah good, +1. Any support too for dynamic dns providers, noip, dyndns and
custom-provider

**Comment by Kelindar** [comment]
@vincent99 @kaos Simple webhooks would be nice indeed, along with the rancher-provided `presence` service (or however you want to call it), similar to the `load balancer`.

![1](https://cloud.githubusercontent.com/assets/583116/9637771/985a58e6-519a-11e5-8db1-7f92fb9911c0.png)

They would be used similarly to the current load balancer, registering services/hosts in the presence service along with a specific `provider` (eg: Route53, OpenStack stuff, etc). The `provider` could be a simple rest service which provides a defined API (eg: list, update, create of record sets) and could actually be implemented by anyone in any language. Moreover, this can be simply a docker image which is launched by an internal docker demon running inside `presence` service. Think of it as dependency-injection via docker where by simply setting a provider image we could have an extendable system which supports pretty much anything.

![2](https://cloud.githubusercontent.com/assets/583116/9637774/9c57721c-519a-11e5-9cb3-ea73c233bc61.png)

**Comment by lavvy** [comment]
Hey how about this feature ? Has it been added? I don't think I have this add presence button in my rancher

**Comment by vincent99** [comment]
@lavvy that screenshot is something @Kelindar made up.  DNS integration is coming soon, I think we're designing it out later today.

**Comment by jas99** [comment]
+1

**Comment by tj13** [comment]
＋1

**Comment by vincent99** [comment]
@tj13: this was added months ago... Applications -> Catalog -> Category: Rancher Services
