### ISSUE TITLE
Rancher UI - deploy workload requires limits when limitrange defaults are set

### ISSUE THREAD

**Issue by garyellis** [rancher/rancher#16753]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a project with one resource quota limit (CPU Limit)
2. Create a namespace in the project
3. Create a limit range on the namespace that sets default and defaultRequest cpu limits.
4. Deploy a workload in the namespace.

**Result:**
Deploy workload "Launch" fails and returns error: `"CPU Limit" is required as resource quota is enforced on the project`.
The Rancher UI should allow deploy workload when limitrange defaults are set.

**Other details that may be helpful:**
Will relate to #16677, #15648

**Environment information**
Rancher 2.1.1

**Comment by cjellick** [comment]
@westlywright can you take a look and let me know if this is truly a UI issue or if it is an api issue

**Comment by cjellick** [comment]
or a combination of both

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/15648

@cjellick combination of both. Once 15648 is resolved, the UI part can be implemented. I will follow up with @westlywright once api part is in.

**Comment by alena1108** [comment]
@westlywright the backend is in

```
we have 2 new fields:
project.containerDefaultResourceLimit
namespace.containerDefaultResourceLimit

on the namespace create/update, derive containerDefaultResourceLimit from project.containerDefaultResourceLimit by default, if not set by the user. 

On workload creation, don't force specifying resource limit if namespace.containerDefaultResourceLimit != nil
```

**Comment by davidnuzik** [comment]
@loganhz I see CPU Limit "Limit to" text field filled in with 1000 (more than our default) and I still get the message. Is this expected? Do I have to manually pick "Limit to" ?
Here is what I see when I just try to deploy a workload with defaults (change nothing): 
![image](https://user-images.githubusercontent.com/45179589/52589720-bef13c80-2dfc-11e9-9048-0275cd2970c8.png)
![image](https://user-images.githubusercontent.com/45179589/52589733-c31d5a00-2dfc-11e9-9940-d1aeecc7591c.png)

**Comment by loganhz** [comment]
Hi @davidnuzik 

You can verify it by the following steps

1. Create a project with cpu limit quota and config the default limit in create project page
2. Create a namespace and check if the default limit is auto filled in create ns page
3. Deploy a workload into the newly created ns

Expected:

it should not show the error message and you can deploy the workload without specifying the limit

**Comment by davidnuzik** [comment]
@loganhz when I do this I do see that our default limit is entered already for the namespace. However when I create the workload I observe the issue I mentioned yesterday. As you can see in the screenshot when I try to create the workload, I encounter this error -- presumably this is because the UI did not pick for me "Limit to 1000 milli CPUs" which also would likely cause a problem since we are actually limited to 500 by default.

I am re-opening this issue.

**Comment by loganhz** [comment]
@davidnuzik 

Could you look at the `containerDefaultResourceLimit` field of the namespace which you would like to deploy the workload, please?

I guess the `limitsCpu` under `containerDefaultResourceLimit` is missing. If so, may I know how did you create this namespace?

![image](https://user-images.githubusercontent.com/21168270/52705080-06bec200-2fbd-11e9-9854-0e18baafddc6.png)

**Comment by davidnuzik** [comment]
@loganhz I just use the steps you outlined. I have a video link below so this might help to make it more clear what I see.

> You can verify it by the following steps
> 
> 1. Create a project with cpu limit quota and config the default limit in create project page
> 2. Create a namespace and check if the default limit is auto filled in create ns page
> 3. Deploy a workload into the newly created ns
> 
> Expected:
> 
> it should not show the error message and you can deploy the workload without specifying the limit

Actual:
![image](https://user-images.githubusercontent.com/45179589/52589720-bef13c80-2dfc-11e9-9048-0275cd2970c8.png)
![image](https://user-images.githubusercontent.com/45179589/52589733-c31d5a00-2dfc-11e9-9940-d1aeecc7591c.png)

Video link showing the issue per steps:
https://vimeo.com/317336401
As you can see in video I get stopped when I try to create workload. I can't just click launch. I presume this is because on workload page UI does not automatically pick "Limit to <value> milli CPUs" for us. I must manually enter this in order to be able to continue. So this was my original question. Is this expected? Is this a separate issue or expected of user to fill in each time. All I needed to validate was step 2 for this issue that the namespace default is filled in? Or did I also need to validate that workload can be launched right away without any manual intervention of config? (i.e. issue I saw in video).

**Comment by loganhz** [comment]
@davidnuzik Thanks!

We need to config the default value in `Container Default Limit` section when create Project.

![image](https://user-images.githubusercontent.com/21168270/52824317-01fc2a00-30f3-11e9-93af-b77ed45d9b6f.png)

**Comment by davidnuzik** [comment]
Thanks @loganhz

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/14/19)
Confirmed issue.

1. Create project with the following settings:
![image](https://user-images.githubusercontent.com/45179589/52826477-3d104600-307e-11e9-80be-99179541047b.png)
2. Create a namespace under this project the defaults are filled out here.
![image](https://user-images.githubusercontent.com/45179589/52826495-56b18d80-307e-11e9-8c9f-fde28d6d1bc3.png)
3. Create a workload under this namespace.
![image](https://user-images.githubusercontent.com/45179589/52826512-68933080-307e-11e9-8a5c-7a8a3115540b.png)
4. Notice you can launch the workload without any issues. 

Smoke tested this area with various container limits, etc. I did not identify any issues and this appears to be working as expected.

When I inspect the container details I can see our limits set.
![image](https://user-images.githubusercontent.com/45179589/52826562-a42dfa80-307e-11e9-9e42-4c61c845c94a.png)

**Comment by cianiandreadev** [comment]
Why is not possible to leave the containers to freely use the resources within the quotas of the namespaces? 
I have a namespace with a limit of 1GB RAM and I don't want to set the limits for each pods. I just want that all together do not exceed the namespace/project limits. Why is not possible?
