### ISSUE TITLE
Is Rancher vulnerable of CVE-2018-1002105? 

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#16835]
Rancher release 2.1.2 
Images:  rancher/hyperkube:v1.11.3-rancher1 and  rancher/hyperkube:v1.12.1-rancher1 mean Kubernete version 1.11.3 and 1.12.1 ?

https://github.com/kubernetes/kubernetes/issues/71411

CVE-2018-1002105 is *fixed* in the following Kubernetes releases:

• v1.10.11
• v1.11.5
• v1.12.3
• v1.13.0-rc.1

**Comment by BalaBalaYi** [comment]
Same. Waiting an answer...

**Comment by guangbochen** [comment]
We already have a hack in place that protects Rancher clusters as this issue is reported by @ibuildthecloud , but should add the proper one in the coming releases.

**Comment by NaffanDroo** [comment]
@guangbochen Which version of Rancher is the hack present in? Nice work by @ibuildthecloud then :)

**Comment by canhnt** [comment]
I see `rancher/hyperkube:v1.11.5-rancher1` image is published. How can we upgrade masters of worker clusters with this image?

**Comment by guangbochen** [comment]
`CVE-2018-1002105` is fixed in the following Kubernetes releases and rancher users can update to the following rancher upstream if the cluster is provisioned by the `rke`:
- rancher/hyperkube:v1.11.5-rancher1
- rancher/hyperkube:v1.10.11-rancher1
- rancher/hyperkube:v1.12.3-rancher1

For existing `rke` cluster you can click update cluster, then in the cluster options click edit `Edit as  YAML` to update or add the kubernetes system images according to your current k8s version, e.g:
```
system_images:
    kubernetes: rancher/hyperkube:v1.12.3-rancher1
```

for cloud host k8s cluster, please bear with us for the coming updates, and if you find the upgrade options from the cloud provider, you can doing the upgrade without any hesitation.

**Comment by deniseschannon** [comment]
As @ibuildthecloud was the one to report the vulnerability to Kubernetes, Rancher has already put a fix in place to mitigate the vulnerability when accessing Kubernetes clusters through Rancher. This is available in Rancher v2.1.2. 

Since Kubernetes has fixed the vulnerability in official releases, the team is working on getting these updated kubernetes versions into a patch release. We are working on release patches for 2.1.x, 2.0.x and 1.6.x and will be making these available ASAP. 

The following Rancher launched Kubernetes clusters will be fixed:

In Rancher 2.1.3, we will update to Kubernetes v1.10.11, v1.11.5, and v1.12.3.
In Rancher 2.0.9, we will update to Kubernetes v1.10.11 and v1.11.5. 
In Rancher 1.6.25, we will update to Kubernetes v1.11.5. 

To find out when these releases are available, either follow the releases on Github or follow our announcements category at the [Rancher Forums](https://forums.rancher.com/).

**Comment by micronax** [comment]
[v2.1.3-rc1](https://github.com/rancher/rancher/releases/tag/v2.1.3-rc1) has been released.

**Comment by superseb** [comment]
RC releases are used for internal testing and are not meant to be used for anything else, the official release will be announced in the forums and GitHub releases (not `Pre-release`)

**Comment by bmdepesa** [comment]
* Validated upgrade from 2.1.1 -> 2.1.3 with RancherOS k8s v1.10.5 -> v1.10.11, and RancherOS k8s v1.12.0 -> v1.12.3

* Validated HA fresh install 2.0.9 with upgrade to 2.1.3
