### ISSUE TITLE
Catalog App Wordpress does not work on Rancher 2.0.8

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16857]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. started the rancher server v2.0.8
2. added a cluster (I tested for both DO and custom cluster)
3. launched the catalog app  Wordpress with all default settings

**Result:**
Wordpress runs up, but the container `Containers` never run up. 

error message: ```Containers with unready status: [mariadb-test]```

<img width="1544" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49485488-70219800-f7f8-11e8-9e9a-61e838957728.png">
<img width="1442" alt="screenshot 1" src="https://user-images.githubusercontent.com/6218999/49485492-77e13c80-f7f8-11e8-94b1-c1514405f88f.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.0.8
- Installation option (single install/HA): Single Install

**Comment by guangbochen** [comment]
The `wordpress-mariadb-test` is only a test container and it will not get deployed if the user is using rancher v2.1 or above, this is because we only bring the tiller back since Rancher v2.1. 

So user can either delete this test container or using the old version of WordPress.

Relevant feature request of catalog version filtering: https://github.com/rancher/rancher/issues/15014

**Comment by jiaqiluo** [comment]
The "bug" happens because the memory in the cluster is not sufficient to run up the mariadb.
Close the issues since it is not a bug.
