### ISSUE TITLE
Options "Node Operating system" is missing when update windows cluster yaml.

### ISSUE THREAD

**Issue by laoshancun** [rancher/rancher#16863]
**What kind of request is this (question/bug/enhancement/feature request):**

BUG
**Steps to reproduce (least amount of steps as possible):**
1. create custom cluster with windows support.
2. edit cluster yaml(like ignore_docker_version ) and save it.

**Result:**
Options "Node Operating system" is missing

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):v1.11.3-rancher1-1

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```

**Comment by virtrixke** [comment]
I noticed the same behaviour. We don't want the default CIDR ranges and cannot change them this way

**Comment by davidnuzik** [comment]
Version: Master 2.2 (12/10/18)
Confirmed fixed. Followed steps to reproduce and was unable using latest master. I see the "Node Operating System" option after saving the modified YAML and can choose between the two (Linux/Windows). Validated HTTP form submission we are using flannelBackendType now instead of flannel_backend_type.
