### ISSUE TITLE
CLI: Add Groups to Projects

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#16885]
CLI can currently add users to projects, but not groups.

**Comment by Venture200** [comment]
Same request : 
Hello, currently I have a Jenkins pipeline which can add Users to Rancher projects but not groups. It would be super helpful from automation point of you adding this feature to CLI because without groups, I have to add groups manually in UI which is time consuming.
Please take this into consideration. looking forward to hear further updates.
