### ISSUE TITLE
graceful removal of hosts

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1696]
When I want to remove a host, I first select "deactivate" and then "remove". However, rancher does not begin to re-schedule containers on the deactivated host until you select remove. At this point, it might take time for the new containers to start on any new or remaining hosts. It would be nice if the re-scheduling started to happen after "deactivating" a host and when a host was fully "deactivated" it is safe to remove it.

One downside to this approach is that the "scaling" size for services has to be relaxed during this deactivation period (since a service container will continue to run on the deactivated host until it starts on a new host). There would also need to be some sort of "timeout" if services cannot start on new hosts and you still want to deactivate/remove the old host.

This would provide a nice way to remove hosts without service disruption and something I thing the "deactivate" state is well positioned to offer.

**Comment by will-chan** [comment]
The "deactivated" state was always meant to allow you to set the host in a state where you would leave the host alone, stop scheduling new containers on the host, but do not stop the existing containers.  You would commonly use this when the host is in max capacity and you don't want Rancher to schedule anymore unto the host or perhaps do some maintenance on it and do not want any new activity to be placed on the host.

For your specific problem, I assume the issue is that you only have 1 container per service and since you removed the host, it will still take some time before the health check kicks in and the container rescheduled unto a new host?  I also assume that it could be annoying to manually scale up a service before removing a host and you would also have to guarantee that the new container lands on a different host via some anti-affinity rule.  I'm trying to understand your use case a bit more.

**Comment by defunctzombie** [comment]
I run an LB instance in front of my services and I think in my case I had a single LB instance and it was on the host I wanted to bring down. I have since changed my deployment structure to not co-locate LBs on the same hosts I run service containers on to avoid other issues with network and memory.

Now that you have explained what deactivated means, I don't think this it as big a deal since I know the process now for bringing down a host per what you described if I do end up with a single container.

Some users might want a state where the host is running as is but no longer part of the LB network (aka receiving inbound data, etc). I don't have that immediate need tho I do find the word "deactivated" possibly overloaded for these use-cases.
