### ISSUE TITLE
Cannot read property `set` of null

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#1700]
Seeing this error in the UI when trying to clone a load balancer. Happy to dig into the db or identify any other information since I am able to reproduce this every time I try to clone this particular LB.

<img width="745" alt="screen shot 2015-07-30 at 11 01 51 pm" src="https://cloud.githubusercontent.com/assets/84792/9001663/061e45b4-370f-11e5-9cc3-4dfe671377e3.png">

**Comment by deniseschannon** [comment]
What version of Rancher and UI? These can be found in by clicking on Rancher in the upper left corner.

Can you let me know what is in the LB that you are cloning? I haven't reproduced with just cloning.

**Comment by defunctzombie** [comment]
<img width="270" alt="screen shot 2015-07-31 at 11 22 59 am" src="https://cloud.githubusercontent.com/assets/84792/9014312/88f4ede6-3776-11e5-923b-8fcc7b4b4ec8.png">

The LB was super basic. Internal LB to a single endpoint (a service). No stickiness rules or even any host/path rules.

**Comment by deniseschannon** [comment]
Still unable to reproduce.

Is the cloned Load Balancer in an active state or inactive state? What is the scale? Does the error occur when you click on Clone or when you click on Create in the cloned screen? Can you share a screenshot of the cloned Load Balancer before you try creating? 

Was the Load Balancer from a previously upgraded setup? Since we made so many changes from 0.25.0->0.28.0->0.30.0 with Load Balancers, I wonder if that has some relevance.

**Comment by defunctzombie** [comment]
This was a new load balancer created on this fresh setup. I did not keep the DB from a previous setup.

It happens when I click on `Clone`

Screenshots:

<img width="272" alt="screen shot 2015-07-31 at 11 45 03 am" src="https://cloud.githubusercontent.com/assets/84792/9014837/c3e1a3a6-3779-11e5-9323-dc129af676bd.png">
<img width="787" alt="screen shot 2015-07-31 at 11 45 19 am" src="https://cloud.githubusercontent.com/assets/84792/9014838/c3e87aaa-3779-11e5-80a3-2f1964dd05a4.png">

**Comment by defunctzombie** [comment]
The only thing I see in the rancher-server logs is the following:

```
2015-07-31 18:43:49,748 ERROR [c3f79b25-2c56-4261-9cf8-df1d706c0dcf:9960] [instance:258] [instance.start] [] [cutorService-19] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: 8621bfd0-1577-45c3-abdf-fdf35f695299 : 404 Client Error: Not Found ("Cannot start container 8aca1239b4d45d6ee098ddbd50414a3cf81f2a38fbe18e247b54ffadaa99d96c: adding interface veth4bc007e to bridge docker0 failed: could not find bridge docker0: no such network interface")
```

Which may or may not be related.

**Comment by deniseschannon** [comment]
Can you share the docker-compose configuration that was generated for this LB? If you go into the stack, you should find it here. 

![screen shot 2015-08-03 at 10 16 35 am](https://cloud.githubusercontent.com/assets/11410997/9043223/ced92dbe-39c8-11e5-876b-76f05629b134.png)

**Comment by defunctzombie** [comment]
```yaml
lb-api-3:
  expose:
  - 80:3000
  labels:
    io.rancher.loadbalancer.target.api-9977039-2: '3000'
    io.rancher.loadbalancer.target.api-9977039-3: '3000'
    io.rancher.scheduler.affinity:host_label: type=lb
  tty: true
  image: rancher/load-balancer-service
  links:
  - api-9977039-3:api-9977039-3
  stdin_open: true
```

**Comment by deniseschannon** [comment]
It looks like the one you copied was for the `lb-api-3` instead of the `lb-soc-3`. Could you send me the other one?

A couple of quick notes from the lb that you've shared.
1. When you have a listener port of 80 -> 3000, you don't also need to set the target port for the services in the advanced routing options. All services will go to 3000. 
2. At some point, it looks like you had deleted service called `api-9977039-2` and added the deleted service to the LB when it was in a removed state. This is where `io.rancher.loadbalancer.target.api-9977039-2: '3000'` is added as a label but not set as a link. Basically, it was deleted from Rancher, but hasn't been purged from Rancher. There is already an issue filed to make it more apparent so that we don't add targets that are no longer available. https://github.com/rancher/rancher/issues/1623

Note: There is an issue where when you attempt to clone a LB that has been edited, it won't have saved the changes and will try to clone whatever the original LB was. There might be something in the original LB that is making it impossible to clone from a UI perspective. https://github.com/rancher/rancher/issues/1662

**Comment by deniseschannon** [comment]
@defunctzombie Are you still having this issue? I haven't seen anyone else encounter it. 

I'll close the issue in a couple of days if there is no response.

**Comment by defunctzombie** [comment]
Haven't checked recently. I believe I re-did the configs that had these issues and removed the old ones. Will revisit if I see it again.
