### ISSUE TITLE
Show the current cpu/memory usage in cluster dashboard

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17040]
Show the current cpu/memory usage for cluster in cluster dashboard when monitoring is enabled.

**Comment by davidnuzik** [comment]
@n313893254 / @loganhz 
I do not see the changes such as those suggested in the screenshot in https://github.com/rancher/ui/pull/2534
I still see the old cluster page. I tested with latest master 2.2 (2/22/19 ImageID: 6fbc596be2db) with DigitalOcean RKE cluster via incognito browser (so I have clear cache, etc).

![image](https://user-images.githubusercontent.com/45179589/53269145-57ad7500-36a5-11e9-9cc1-d8d4d5e01fc1.png)

![image](https://user-images.githubusercontent.com/45179589/53269150-5da35600-36a5-11e9-8b64-250aae67b6fd.png)

**Comment by vincent99** [comment]
You need to have prometheus deployed to get live stats.  Without it you should be getting the same as before.

**Comment by davidnuzik** [comment]
Thanks. Updated issue description to mention that monitoring needs to be enabled.

**Comment by davidnuzik** [comment]
I like the new wheels for CPU/Memory but we still show the percentage used but this has changed from reserved to used and I don't like how it's ambiguous what the percentage is for.

![screen shot 2019-02-22 at 2 10 01 pm](https://user-images.githubusercontent.com/45179589/53271432-ae1db200-36ab-11e9-81b6-5b6a50a63a45.png)

Could we update it a bit so it's more clear to the user what the % is for? Especially since it changed from reserved to used.

Would it look decent to reduce the font size of it a bit and show % Used and % Reserved underneath?

This is just a very rough idea I'm throwing out there. I know it looks like garbage I don't have Photoshop to make something proper and Gimp gives me a headache.
![screen shot 2019-02-22 at 2 04 13 pm](https://user-images.githubusercontent.com/45179589/53271307-4bc4b180-36ab-11e9-825a-9bc6a37875bb.png)

I was thinking something closer to this, but make it look nicer with proper fonts and stuff. :P

@n313893254 @loganhz 
Assigning back and re-opening just to get some input from you. Thanks!

**Comment by davidnuzik** [comment]
^^ Better yet, 100% above the "2 of 2 Used" and 67% above the "1.3 of 2 Reserved" as pictured. Used percentage can be blue and % reserved can be green perhaps.

**Comment by loganhz** [comment]
@vincent99 Do you like the design https://github.com/rancher/rancher/issues/17040#issuecomment-466549395 ?

**Comment by vincent99** [comment]
I'd do

75% (big, matching ring color)
1.5 of 2 Used (small, same color)

90% (medium, matching the other ring color)
1.8 of 2 Reserved (small, same color)

So they are grouped together and reserved/used isn't repeated.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/25/19)
Confirmed issue. When monitoring is enabled there is a new wheel showing the amount used versus reserved.
I smoke tested this area, set 100% load on a workload to validate the wheels work as expected using "stress" application via aptitude. During my testing I could not identify any issues.

Screenshot of new CPU wheel:
![image](https://user-images.githubusercontent.com/45179589/53359645-b7e42700-38f0-11e9-90a7-1f59a1b840b4.png)

Screenshot of new memory wheel:
![image](https://user-images.githubusercontent.com/45179589/53359657-c4687f80-38f0-11e9-9e0a-e637fd0f10bc.png)

_I did open a separate issue around requests to tweak the look of this a little bit to make it slightly easier to read_: #18377
