### ISSUE TITLE
When starting server/agent/networkingcontainer, a lot of things are downloaded dynamically

### ISSUE THREAD

**Issue by feliksik** [rancher/rancher#171]
This has a number of disadvantages: 
- slow
- harder to cache (e.g. in docker registry mirror)
- more error prone

To me, ideally, it would be all packaged in docker containers at build time (so no on-the-fly github downloading). Optionally, some extra docker containers may be downloaded additionaly, but if a list of these dependencies is published than they can be pulled beforehand. 

What's you take on this? Is this a long term strategy, or just because it allows faster patching of deps?

**Comment by ibuildthecloud** [comment]
The current approach was done because it was easier to package and maintain, but obviously (I see now) at the cost of the user.  We've already had issues filled that one can't run Rancher with no internet connection.

I think we will change our approach and try to have everything packaged in a documented set of images.  We have not spent anytime optimizing the size of our images either, so they are known to be quite large.

The downloads from github are cached into the rancher-agent-state volumes.

**Comment by feliksik** [comment]
@ibuildthecloud perfect. Large images is not a problem to me at all, provided they are... well, images. Large dynamic dependencies look nice on the surface, but are actually less user friendly indeed. 

Ah, that clarifies what this rancher-agent-state guy is doing :-D and the name suddenly makes sense

**Comment by feliksik** [comment]
Now that I think of it, I may decide to remove the rancher-agent but not the rancher-agent-state, and this would cache stuff -- right? That's actually a workaround for now. It does make it slightly less transparent what software version you're running, though.

**Comment by ibuildthecloud** [comment]
Yes, you shouldn't delete the rancher-agent-state.  The version of the agent and all software dynamically downloaded is managed by the server.  If the server requires a new agent it will deploy a new one based off of a different image.  We enforce a strong consistency between server and the required agent version.

This is part of the magic and why it downloads stuff on startup because the agent is a generic image.  The server decides what software needs to be installed.  For example we have different agents, host agent, network agent, load balancer agent, and swarm agent.  Each requires slightly different software but is all based off of generic docker images.

As development stabilizes a bit more we will look at caching this software in the image.  Right now there are so many moving parts evolving so rapidly that it helped to do all this dynamic magic

**Comment by feliksik** [comment]
> Yes, you shouldn't delete the rancher-agent-state. (...)

This is great :-) I recommend putting this in the Github Readme.md as it is actually a very good property, but not totally clear. 

> As development stabilizes a bit more we will look at caching this software in the image. Right now there are so many moving parts evolving so rapidly that it helped to do all this dynamic magic 

I can totally imagine.

**Comment by vincent99** [comment]
Can we call this good now that you can do offline-install and provide your own private registry copies of the images?  http://docs.rancher.com/rancher/installing-rancher/installing-server/no-internet-access/
