### ISSUE TITLE
[UI] Visit ip:port/projects instead of hostname/projects on web ui init

### ISSUE THREAD

**Issue by bxy09** [rancher/rancher#1712]
![image](https://cloud.githubusercontent.com/assets/3319944/9021115/5f5adb28-3864-11e5-949a-f6812ca0ee1e.png)

Using nginx vhost to redirect ip:8080 to a hostname.

**Comment by cjellick** [comment]
Can you explain your setup in a little more detail so that we can try to reproduce?
In the browser, are you going to the hostname or to ip:port?
And if you could post your nginx configuration here, that would be most helpful. Of course, feel free to omit any sensitive information in it.

**Comment by vincent99** [comment]
There's a button in the network console that will make it show double height lines that have the host & port in them instead of just the path.

The rancher API returns absolute URLs for everything, so it needs to know the original protocol, host, and port.  Make sure nginx is configured to send x-forwarded-{host,proto,for} headers.

**Comment by deniseschannon** [comment]
@bxy09 If you could supply your nginx configuration so that we could help you troubleshoot, we'd like to help you get set up. As mentioned, please feel free to omit the sensitive information. 

If not, I will be closing this issue in the next couple of days.
