### ISSUE TITLE
Pending state for cluster is red and should be yellow (Pending should not be error state)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17281]
Version - master 1/2

**Steps to reproduce (least amount of steps as possible):**
1.  Create a DO cluster

**Result:**  First state is pending.  And it's red.  Pending should not be a "error" state.  It should be a transitioning type of state and be yellow.
![image](https://user-images.githubusercontent.com/11514927/50609554-48702f00-0e8d-11e9-9ddd-96c631ead289.png)

**Comment by cjellick** [comment]
related https://github.com/rancher/rancher/issues/15907 https://github.com/rancher/rancher/issues/17201

**Comment by davidnuzik** [comment]
When Provisioning is in the wrong color, is green instead of yellow.
When you get an Updating state this too is in red and we should only see red for an Error state or any state where something is critically wrong and the cluster is essentially in a permanent unusable state until human interaction is taken to fix it.

**Comment by davidnuzik** [comment]
We will keep provisioning green so this is okay. I will open another bug regarding Updating state should be yellow instead of red.
Version: Master 2.2 (2/13/19)
Pending state no longer occurs clusters go straight into the provisioning state which is a teal color. We had a discussion in slack and this is okay.
