### ISSUE TITLE
EKS cluster goes to active with no nodes for a few seconds before provisioning

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#17282]
Version - 2.2 master 1/2

**Steps to reproduce (least amount of steps as possible):**
1.  Create a EKS cluster

**Result:**  Notice when you first create, the cluster goes directly to "Active" with no nodes created.  This is confusing and it shouldn't go into active state until it's actually done provisioning.  This is new behavior and didn't exist before.

**Comment by davidnuzik** [comment]
@nathan-jenan-rancher This seems to be improved, however I seem not notice with most clusters they go to an Active state then after about 5 seconds back to Provisioning/Updating and then quickly (after 3 seconds?) back to Active again. This seems to be new; is this related? I don't see anything unusual in the rancher logs.

**Comment by davidnuzik** [comment]
Haven't heard back. Created #18127 to track this.

The main issue identified in this issue is resolved.
Version: Master 2.2 (2/14/19)
Now when you create ANY cluster it will go immediately straight into the Pending state and stay there until ready and fully provisioned. Then it goes to Active state.
