### ISSUE TITLE
Rancher Monitoring with Prometheus Should Be a Blackbox / Use Non-Defaults to Not Conflict

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#17331]
**Version: 2.2.0-alpha3**

Deploying Prometheus monitoring for Rancher 2 causes conflicts when wanting to deploy Prometheus from a catalog.

Specifically the node exporter exposes itself on the Host Port of 9100, this should be a cluster only port I think or a non-default port.

**Comment by ekristen** [comment]
@thxCode appreciate the comments. 

> Rancher monitoring uses node-exporter as a required component to show the metrics from each host(with host IP)

Actually it doesn't need host IP, it just needs an IP, a cluster IP would work as well, but additional work would be required to attribute the cluster IP back to the correct node.

> if you want another Prometheus from the catalog, I think you can disable the node-exporter in it and configure the scrape_config to scrape monitoring node-exporter when deploying alpha version.

From the Prometheus Library entry you cannot disable node-exporter or changes it's port from the questions alone, but you can do so by manually modifying and providing the correct overriding values.

The default Helm and consequently Library versions are setup with Kubernetes SD Configs out of the box, which means it looks for the io.prometheus.scrape labels to deteremine which targets to scrape so that manual configuration of the scrape_configs is not required.

**Note:** At least for me there is not configuration options available when enabling monitoring in 2.2.0-alpha.

## Argument

I believe the position that I can change my configs, and change ports and disable node-exporter is the wrong for Rancher to take on this and here is why.

As Rancher using Prometheus as what I would consider semi-critical if not critical monitoring of the cluster I would not want any user touching its deployment configuration. There's a reason why it gets deployed into the System Project under the `cattle-prometheus` namespace, and not under the Default Project. 

This Prometheus instance for monitoring should be treated as a black box setup specifically and only for Rancher to use otherwise you run the risk of it breaking and thus breaking Rancher's monitoring capabilities.

## Conclusion

I believe that the prometheus instance deployed by Rancher for monitoring should be a black box, using non-defaults and configured to not conflict with any other prometheus monitor that might need to be or want to be deployed the the cluster for other purposes.

This includes but is not limited to:
  * using non-default ports
  * not using io.prometheus.scrape labels (I didn't see any but putting here for good measure)

**Comment by ekristen** [comment]
@loganhz any chance of a follow up here? Thanks for all you guys are doing!

**Comment by loganhz** [comment]
@orangedeng @thxcode maybe it’s a good idea to use another port instead of 9100? Also are we using io.prometheus.scrape label?

**Comment by thxCode** [comment]
@ekristen, 

> using non-default ports

from the suggestion of [node_exporter](https://github.com/prometheus/node_exporter#using-docker), for now, we cannot deploy `node_exporter` without `hostNetwork` mode if we need to see the actual network stats for the container network. There are still namespacing issues with running the node_exporter in a container, mostly around filesystem mount spaces. _So there is still create a port on host whatever 9100 or something else._

In order to avoid forcibly occupying certain ports, we will provide parameter configuration to allow the user to disable `hostNetwork`: ["exporter-node.enabledHostNetwork"](https://github.com/rancher/rancher/issues/17340) . The result is that you may count incorrect network status.

But if you certainly know the exposed ports on your host, you can use: "exporter-node.ports.metrics.port" to choose an unoccupied one.

---

> not using io.prometheus.scrape labels (I didn't see any but putting here for good measure)

We should support `prometheus.io.scrape`, actually, we use it to discover some metrics which don't point out with the [scrap_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) or [ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#servicemonitor) explicitly on `cluster-level`, for example: [what we do for the nginx-ingress-controller](https://github.com/rancher/system-charts/blob/master/charts/rancher-monitoring/v0.0.2/charts/prometheus/additionals/c-scrape_prometheus_io.yaml)

For now, we don't support this on `project-level`. We hope the users can use the Custom Metrics which we provide in UI to config the metrics source explicitly. This part, I think, it's as you expected.

cc @loganhz

**Comment by ekristen** [comment]
I understand keeping network mode as host.

Are you going to change the default port @thxCode on the system chart?

**Comment by thxCode** [comment]
@ekristen , we will change its default on UI (maybe 9101 or something else) and allow users to replace it. 

Replacing a port is secondary. It is important that node_exporter currently uses`hostNetwork` to collect real network status. Therefore, no matter what port you change, if you want to play the real function of node_exporter, you need to solve the port conflict problem yourself.

The solution we provide is to adjust the configuration parameters when enabling/editing Monitoring:
- If you don't want node_exporter, you can `disable` it.
- If you want metrics but not network from node_exporter, you can `disable hostNetwork` for it.
- If you want everything from node_exporter, you must know what port your host is exposed to.
- If you want to enabling Rancher Monitoring on the public cloud, you can use the network security group to protect the node_exporter.
- Protecting the node_exporter only can be scraped by cluster-level Prometheus, we will fix on https://github.com/rancher/rancher/issues/17957

**Comment by ekristen** [comment]
@deniseschannon @loganhz I think at this point this issue can be closed for the most part. Outside of node exporter everything else deploys blackbox pretty well.
