### ISSUE TITLE
Update etcd binaries in rke-tools to 3.3.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#17362]
**What kind of request is this (question/bug/enhancement/feature request):**
Currently we use `v3.0.17` in `rke-tools` which is the etcd version for k8s 1.8. We should update it to `v3.1.12` which is the version for k8s 1.10

ARM was added in the meantime and `3.3.10` of etcd was added there, so I updated this to match the ARM package.

**Comment by alena1108** [comment]
@superseb can you provide the steps for qa to verify?

**Comment by superseb** [comment]
- Create custom cluster and add node
- Run the following command on the node to verify etcdctl version:

```
docker run -e ETCDCTL_API=3 --rm $(docker inspect $(docker images -q --filter=reference='*/rke-tools:*') --format='{{index .RepoTags 0}}') etcdctl version
etcdctl version: 3.3.10
API version: 3.0
```

Next to this, any etcd interaction (etcd snapshot and restore) should be verified on every k8s version.

**Comment by davidnuzik** [comment]
Yes, something doesn't seem quite right with etcd snapshot/restore.
I ran into an issue today when testing this area:

version: master-head (7/19/19)

I created ec2 RKE cluster, this was with default v1.15.0 k8s version the UI picks.
Perform snapshot, wait until it is done (It seems to take a while, possibly longer than normal).
Attempt restore, this will fail to work.

Snapshot appears to work completely fine based on rancher logs.
Restore seems to fail with this message:

`Failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2019-07-19T22:57:51Z" level=fatal msg="stat /backup/c-ctt5t-ml-dqqp9_2019-07-19T22:38:55Z: no such file or directory" ]`

I ssh'd into my node and exec'd into the etcd container and ran `etcdctl version` and got expected result:
```
etcdctl version: 3.3.10
API version: 3.3
```

**Comment by davidnuzik** [comment]
I was asked to check again. My master-head was 2 hours old. It's now latest (~10 mins old as of writing). (`6efc134f`)

Snapshot now saved quickly.
Restore now worked successfully.
Restore now worked without any issues.

**Comment by sowmyav27** [comment]
on rancher:master-head(latest)
running the command for clusters with k8s versions- v1.15.0, 1.13.8 and 1.14.4
```
docker run -e ETCDCTL_API=3 --rm $(docker inspect $(docker images -q --filter=reference='*/rke-tools:*') --format='{{index .RepoTags 0}}') etcdctl version
etcdctl version: 3.3.10
API version: 3.0
```
Able to take manual/recurring snapshots
Able to restore from these snapshots successfully.

**Comment by zbialik** [comment]
> running the command on the nodes of clusters with k8s versions- v1.15.0, 1.13.8 and 1.14.4

@sowmyav27 how are you able to run k8s version 1.14.4 when the available kubernetes version for rancher v2.2.6 release is 1.14.3? I am running rancher v2.2.6 in air gap and cannot get get rke to perform an etcd-snapshot.

Specifically, rancher/rke-tools:v0.1.34 does not have the updated etcdctl cli. Can this really be considered fixed in rancher v2.2.6 if rke-tools:v0.1.34 does not have the upgraded etcdctl cli?

Thanks for the help!

**Comment by sowmyav27** [comment]
@zbialik This was tested and verified in the latest master build. The latest master - `rancher:master-head` has the said k8s versions and the fix.

**Comment by zbialik** [comment]
@sowmyav27 Ahh okay.

I am not concerned about the validity of this fix, rather I believe the [Release Notes for Rancher v2.2.6](https://github.com/rancher/rancher/releases/tag/v2.2.6) are inaccurate since this fix is not implemented in the v2.2.6 release.

Based on the [commit](https://github.com/rancher/rke-tools/commit/19a86600e388a69dbf2e56b5be9ba9b542541e9d) for this fix, the earliest rke-tools that has this fix is `rancher/rke-tools:v0.1.35`

Rancher v2.2.6 specifically identifies the rke-tools version to be v0.1.34 (See the rancher-images.txt file). This means that Rancher v2.2.6 does not have this fix and the Release Notes should either be updated or the rancher-images.txt file should identify rke-tools:v0.1.35 as the needed image version for rke-tools.

**Comment by bmdepesa** [comment]
@zbialik what are you referring to in the Release Notes for v2.2.6? 

This fix was not tested in 2.2.6 as it was not available, this is slated to go into the upcoming v2.3.0 release.

**Comment by zbialik** [comment]
@bmdepesa 

- This release fixes a bug introduced in v2.2.5 when Etcd Snapshots fail to create in airgap setup with private registry set [[21628](https://github.com/rancher/rancher/issues/21628)]

**Comment by bmdepesa** [comment]
@zbialik Those notes refer to a separate issue relating to private registries in an airgap setup: #21627

**Comment by zbialik** [comment]
@bmdepesa I think I am confused. That issue #21627 has a milestone set for v2.3 and is also still open. How can the Rancher v2.2.6 Release Notes say it offers a fix for performing etcd snapshots in Air Gap environments when that is only true for whatever release has `v0.1.35` listed as the required version for the rke-tools docker image?

**Comment by zbialik** [comment]
@bmdepesa I actually think the issue I am experiencing is related to Issue [#1472](https://github.com/rancher/rke/issues/1472)

Perhaps I just need to upgrade my rke cli. I am using v0.2.5.

**Comment by bmdepesa** [comment]
@zbialik Issue #21627 was backported to v2.2.6 (#21628), where we tested that etcd backups could be performed with private registry in airgap environment. 

The fix for this issue relates _specifically_ to an issue that occurred when using private registries. This issue is unrelated to the specifics of issues #21627, #21628

Are you able to provide any logs from Rancher or the etcd snapshot containers? If updating RKE does not resolve your issue, please open a new issue with your specifics.

**Comment by zbialik** [comment]
@bmdepesa Ok thanks so much for the quick support. I believe I was mistaken and my real issue is the version of my rke cli, not the Rancher release. 

@sowmyav27 Appreciate the support from you as well.

Thank you !! Upgrading rke cli to v0.2.6 fixed it for me !
