### ISSUE TITLE
Support external prometheus in rancher monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17370]
As a Rancher user, I have a running prometheus in 2.1 already.

When I upgrade to 2.2, it will be good if I can still use my own Prometheus instead of deploy a new one.

**Comment by DarthSlider** [comment]
Any news?

**Comment by Tejeev** [comment]
Perhaps our best solution is remoteWrite in the Rancher Monitoring chart.  It is by far the most requested method of resolution and I think it should work better than "Prometheus Federation"

**Comment by Tejeev** [comment]
https://github.com/rancher/rancher/issues/20624

**Comment by DarthSlider** [comment]
Looks like I completely don`t understand how internal Rancher monitoring works.
It looks like grafana-style graphs that get metrics from Prometheus and draws it inside rancher UI. Why it can't just have a setting where it could find Prometheus and why it even care if it's an internal Prometheus at all?

**Comment by strowi** [comment]
@Tejeev i was looking for a way to configure a remoteWrite endpoint (to victoriametrics), but it seems i can't figure out the correct syntax to specify in the cluster-monitoring app.
Could you (or anyone else) help me out pls?
I tried:
- prometheus.remoteWrite = url: https://status.xyz.de/victoria/api/v1/write
- prometheus.remoteWrite[0] = url: https://status.xyz.de/victoria/api/v1/write
- prometheus.remoteWrite = ['url: https://status.xyz.de/victoria/api/v1/write']

**Comment by Tejeev** [comment]
Hi @strowi, at the moment it's not actually supported in the app.  We are looking at adding it but the feature is listed as experimental by Prometheus so I believe our devs are taking the time to do some due diligence before tossing in the new feature.  One fear is that if we go with remote write and Prometheus deprecates it anyone using it will be left SOL.

**Comment by strowi** [comment]
@Tejeev thx for the info! Completely understandable. ;)
I was under the impression it was a sightly modified copy of the public helm-chart. Can i add it via some other variable like additionalConfig?

Right now we are using the remoteWrite for our production workloads in conjunction with victoriametrics. Haven't had a problem since introduction in June.
We have to check 2 different grafana/prometheus/alert-instances, which we would like to solve.

**Comment by dawidmalina** [comment]
@Tejeev where did you found information that remote write is experimental? I think rather that this is where community is trying to go. Take a look at projects like cortex or thanos (receiver).

**Comment by Tejeev** [comment]
Oh from what I see I think it is the method of choice (why I mentioned it), but I'm not a dev so I leave that to you smarter folks.

As for where I arrived at it being experimental, I found it listed as experimental in the coreos prometheus-operator PrometheusSpec:

Field | Description | Scheme | Required
-- | -- | -- | --
remoteWrite | If specified, the remote_write spec. This is an experimental feature, it may change in any upcoming release in a breaking way. | []RemoteWriteSpec | false
remoteRead | If specified, the remote_read spec. This is an experimental feature, it may change in any upcoming release in a breaking way. | []RemoteReadSpec | false

https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md

Rancher Monitoring installs the prometheus-operator (https://github.com/rancher/system-charts/tree/dev/charts/rancher-monitoring/v0.0.6)

**Comment by rjshrjndrn** [comment]
Any of you folks figured this out?
@rancher is there any plan to integrate this?
This would be an awesome help for devs, to see metrics in rancher itself.

**Comment by Tejeev** [comment]
https://github.com/rancher/rancher/issues/20624 is closed so looks like we may have a remoteWrite solution in v2.4

**Comment by pbrissaud** [comment]
Just upgrade to Rancher 2.5.1 and I don't see the fields to add remoteWrite configuration : 

![image](https://user-images.githubusercontent.com/27202456/98677263-12d7df00-235d-11eb-8cb6-17dea90b135f.png)

How can I do to "forward" data to a central Prometheus Server ?

**Comment by igormaksimoff** [comment]
> Just upgrade to Rancher 2.5.1 and I don't see the fields to add remoteWrite configuration :
> 
> ![image](https://user-images.githubusercontent.com/27202456/98677263-12d7df00-235d-11eb-8cb6-17dea90b135f.png)
> 
> How can I do to "forward" data to a central Prometheus Server ?

Hi! Did you find a way to configure remoteWrite with Rancher 2.5.x? Thanks.

**Comment by pbrissaud** [comment]
@igormaksimoff unfortunately no, I change some networks settings in order that Grafana can access to all my prom instances

**Comment by igormaksimoff** [comment]
Looks like there is no option in UI, at least in 2.5.5, so updated the Chart YAML directly and got it to work.

```
    remoteWrite:
      - bearerToken: >-
          [token_value]
        url: >-
          http://[something]/api/prom/push
```

**Comment by Tejeev** [comment]
updating the chart yaml is the recommended method for remotewrite

**Comment by willemm** [comment]
I don't see what remoteWrite has to do with this issue.
If there is already a monitoring stack in place (in our case, victoriametrics) which already has all teh monitoring data needed, then all that needs to happen is for rancher to use the query endpoint (or even the existing grafana installation) to produce the graphs in its own UI.

Basically, whatever internal setting there is that now points to the grafana it deploys itself, should point to the existing one (or the internal grafana it deploys should be pointed to the existing query endpoint).

**Comment by lawso017** [comment]
Agree with @willemm comment above. We have had to move to VictoriaMetrics in our environment because Prometheus is extremely resource-hungry by comparison. It would be ideal if there was a looser coupling available between Rancher and the environment's chosen "Prometheus-compatible" monitoring stack.

**Comment by Tejeev** [comment]
@willemm In 2019 through early 2021 the ecosystem was much less developed and remoteWrite was the best way to move data between Prometheus instances for several reasons.  
This issue was opened specifically about interfacing between Prometheus instances by one of our devs based off of the common needs of our customers and I suggested remoteWrite as a way to do so in a time where Thanos was a pain to configure.
Now days we have the Federator and other solutions for those needs but remoteWrite still works well, last I checked.   

More importantly, now days tools like VictoriaMetrics are mature enough to start seeing production use.
As such, I completely agree that in the modern context, it makes sense to open Rancher out to allow for coupling with  Prometheus compatible tools deployed by the user.

I would suggest we close this request because it is too specific and it was actually resolved by a PR 3 years ago, and that you open a new one to address moving towards a looser coupling to the monitoring solution. This will give our product managers something with more visibility and a better laid out plan to work with.
