### ISSUE TITLE
Add external VIP provider support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1740]
1) Add VIP (Virtual Private IP) to every service by default. Default vip cidr is 169.254.0.0/16
2) Cattle delegates VIP implementation to external service provider. To register as external VIP provider in cattle, service has to be deployed with a label:

'io.rancher.network.services': "vipService"

3) When service container is deployed on the host having VIP provider running, Rancher DNS gets programmed with service VIP for this service DNS A record. And the VIP provider will provide an implementation for that.

**Comment by sangeethah** [comment]
Tested with build from master from Aug 14.

Following scenarios were tested:

1. When any service is created and activated , dy default they get an ipaddress from cidr 169.254.0.0/16. This is avaialable  as "vip" in service object.

2. Deployed a service with label - 'io.rancher.network.services': "vipService" . /var/lib/cattle/etc/cattle/dns/answers.json file in the network agent instance of the host where this service is deployed now has references to vip in the "a" records instead of the managed network . Example of one such entry:
"test191042.": {"answer": ["169.254.85.84"]},
        "test191042.rancher.internal.": {"answer": ["169.254.85.84"]},
where 169.254.85.84 is the "vip" of service - test191042

3. Create a new service in this host. The new service gets programmed in the answers.json file with "a" records referencing vip.

4. Remove vip service. This results answers.json file being programmed with managed ipaddress instead of the vip.
