### ISSUE TITLE
Provide option to set Administrative flag for cluster scoped roles

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#17443]
RoleTemplate has a new field called Administrative. This is for now only to be set on cluster roles. The UI for cluster scoped roles should also provide an option for this field, along with Built-in, created and other such options
<img width="1362" alt="screen shot 2019-01-15 at 8 46 59 pm" src="https://user-images.githubusercontent.com/10672776/51189808-cf4dee80-1906-11e9-9880-a357e4ce4e50.png">

**Comment by mrajashree** [comment]
This flag is needed to distinguish between the cluster-owner and other cluster roles, while granting them access to certain project-scoped resources

**Comment by loganhz** [comment]
What’s the label for the field in the UI? And what’s the help text should be?

**Comment by mrajashree** [comment]
@loganhz I'm not sure I know what the label field is? The name of the flag should be Administrative. 
The reason behind adding this is, managing access to resources that are both, cluster scoped and project scoped, for example the `catalogtemplates` and `catalogtemplateversions`. If any cluster role has Administrative set to `true`, then that cluster role will get access to all catalogtemplates/versions from all projects that are a part of that cluster. Which is why cluster-owner has by default Administrative bit set to true; but cluster-member doesn't since cluster-members should not have access to catalogtemplates/versions from projects that they don't belong to, even if that project is in the cluster they are a part of. So in short this flag if set will grant cluster-scoped roles access to all resources across all projects in the clusters they are added to, and should be set only if the role being added is expected to be equivalent to a cluster-owner role

**Comment by cjellick** [comment]
I explained this field to @vincent99 and we talked through the usecases and we decided that we dont want to expose this field in the UI. it should be set for our existing cluster admin roles, but we will just hide it. If people complain about custom roles, they can in the short term flip the bit in the API and then we can figure out the right way to explain what it does.

The problem is that it is fairly confusing and requires understanding how rancher does authz to fully grok
