### ISSUE TITLE
UI for enhancements to rancher settings

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17487]
UI for https://github.com/rancher/rancher/issues/17488

I am adding this on behalf of @orangedeng because I am not sure if the changes introduced in https://github.com/rancher/rancher/pull/17208 going to require UI changes to be fully utilized.
In short, if a setting is set via an environment variable a rancher start-up time, the setting is NOT EDITABLE. This was implemented by removing the update link upon returning the setting in the API and erroring out if an update is required.

So, if the UI automatically respects the absence of the update link for settings, then no UI change should be needed

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/51794699-899cfa00-2213-11e9-8c7f-4d8870bb9022.png)
![image](https://user-images.githubusercontent.com/21168270/51794700-8efa4480-2213-11e9-8f80-c057c82a0c93.png)

`/v3/settings` returns `ui-index` with `update` link. But `/v3/settings/ui-index` doesn't.

`docker run -d -e CATTLE_UI_INDEX=local  -p 80:80 -p 443:443 rancher/rancher:master`

**Comment by loganhz** [comment]
Validate steps

Case 1:

1. docker run -d -e CATTLE_UI_INDEX=local -p 80:80 -p 443:443 rancher/rancher:master
2. Make sure there is no `Edit` button for ui-index in global setting page

Case 2:

1. docker run -d -p 80:80 -p 443:443 rancher/rancher:master
2. Make sure there is `Edit` button for ui-index in global setting page
3. Make sure you can change it to something else such as `local`

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/4/19)
Confirmed fix.

Case1: run with env var CATTLE_UI_INDEX=local and ensured UI Index is NOT editable in the UI. API looks correct.
Case2: run without env var and ensure UI Index IS editable and can change to local and smoke test UI. API looks correct.

Local UI is v2.0.77 and so we are missing mc app functionality, etc. @loganhz is this expected when we run with local UI index? Or should I open a separate bug for this? I expected LATEST UI with master branch. Also I noticed that I can attempt to "Revert to default" which results in 405 error (as expected due to api) but the UI should either have a nicer error to explain what went wrong or we should remove revert to default. I think we have this option because in API "customized": false, so I presume I should open another separate bug for this as well?
