### ISSUE TITLE
UI for Support vSphere network protocol profiles #2308

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17490]
see https://github.com/rancher/rancher/issues/15817
PR https://github.com/rancher/ui/pull/2308

**Comment by cjellick** [comment]
we're adding a handful of new inputs for the vSphere machine driver. The PR and root issue have good details on the fields being added
cc @kinolaev

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
Validated UI. Further testing will be done in the referenced issue #15817 
Created vSphere node template and tested around the new vApp section. Ensured that form worked appropriately and inspected http POST req payload / server resp. Validated API.
Per the PR this added four areas to the template you can see this below in my req payload:
```
vappIpallocationpolicy: "fixedAllocated"
vappIpprotocol: "IPv4"
vappProperty: ["guestinfo.dns.servers=${dns:asd}", "guestinfo.dns.domains=${searchPath:asd}",…]
0: "guestinfo.dns.servers=${dns:asd}"
1: "guestinfo.dns.domains=${searchPath:asd}"
2: "guestinfo.interface.0.ip.0.address=ip:asd"
vappTransport: "com.vmware.guestinfo"
```
I smoke tested this area and played around with various options to ensure it is functioning correctly. The API looks good.

Screenshot of this new section:
![image](https://user-images.githubusercontent.com/45179589/52005385-cf152d80-2486-11e9-9d61-59570eadf27f.png)

Discovered a bug while testing:
Appears to be #15879
You cannot edit the vSphere node template due to this or clone it.
