### ISSUE TITLE
UI for support force-upgrade in the rancher catalog

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#17510]
**Problem:**
UI for support force-upgrade in the rancher catalog.

**Solution:**
add `force-upgrade` option for both upgrade and rollback.

**Related Issues:**
https://github.com/rancher/rancher/issues/16769

**Related PRs:**
https://github.com/rancher/rancher/pull/17193

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/30/19)
Confirmed fix. In the UI when you upgrade a catalog app there is now an option near the bottom with a checkbox to "Delete and recreate resources if needed during the upgrade" when you do this in the POST req payload we see forceUpgrade: true and this works. If you fail to do this when following the steps to reproduce in #16769 it will result in an error as expected. This error no longer happens when you force upgrade using this option.
Rollbacks are also working as well. I smoke tested this area and validated all HTTP / API.
