### ISSUE TITLE
[UI] Login doesn't prompt "Save Password" on chrome

### ISSUE THREAD

**Issue by lucasdeassis** [rancher/rancher#17591]
When logging in on Chrome, due the lack of `input name` and/or `password name` on `login-user-pass` component template, the `save password` popup is not prompted. This can be boring for users that use `password generating solutions` or just store passwords in the browser.

**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**

1 - Open Login on Chrome
2 - Insert User 

**Result:**
Logs in without the browser prompting 

**Other details that may be helpful:**
stackoverflow.com/questions/2382329/how-can-i-get-browser-to-prompt-to-save-password

**Environment information**
- Rancher version (`rancher/ui`): 2.1.19

**Comment by davidnuzik** [comment]
@westlywright I can see that we have set a name=username and name=password for each username/password field respectively but Chrome is not offering to save password even though I have this enabled in chrome settings. I also created a whole new blank profile with these settings to ensure an extension or some setting I had under my profile was not affecting this and this still does not work.
Perhaps this is because I am using a self-signed certificate and Chrome doesn't like that?
Screenshot of my new blank chrome profile and settings:
![image](https://user-images.githubusercontent.com/45179589/51930068-f1d81100-23b6-11e9-8964-63dd83127d56.png)

**Comment by davidnuzik** [comment]
QA testing note: requires either a rancher server that does not use a self signed cert or running chrome with a special argument see: 
https://superuser.com/questions/1241132/chrome-password-saving-with-self-signed-or-broken-ssl/1241237

**Comment by davidnuzik** [comment]
Version: Master 2.2 (1/29/19)
I was not able to get this to work with Chrome when using a self-signed certificate. This is by design (Chrome) so it is necessary to use a proper SSL certificate configuration with Rancher. I did get this to work on Firefox however and I confirmed that we indeed added the proper names to each field per the PR/commit.
