### ISSUE TITLE
UI support of custom values.yaml in the catalog apps

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#17605]
**What kind of request is this (question/bug/enhancement/feature request):**
UI feature request

**Steps to reproduce (least amount of steps as possible):**
1. go to the catalog apps page and click one of the app e.g, DockerRegistry
2. add an option to use custom user-supplied `values.yaml` file, e.g,
![image](https://user-images.githubusercontent.com/4569037/51728130-0f049b00-20aa-11e9-8e2e-71b30c8f8578.png)

3. click launch and ensure the user-supplied `values.yaml` values will override the default one.

**Result:**
Ensure the user-supplied `values.yaml`'s values will override the default one.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): single & HA

**Related PR **
https://github.com/rancher/rancher/pull/17576

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/19)
Confirmed enhancement.
This now treats "Edit as YAML" as actual YAML rather than key pairs as we were doing before. I inspected the POST (creation) and POST (upgrading/editing) of the docker-registry app and the http/API looks good. This adds "valuesYaml" and it will send proper YAML with all the whitespaces/carriage returns.

I tested by Editing as YAML and putting in custom YAML such as replicaCount: 2 and then validate in UI that we have two pods created for example.

Screenshot below. You can see my added YAML below. I tested a few other things as well.
![image](https://user-images.githubusercontent.com/45179589/53055250-47f31e00-3464-11e9-8722-a4aabf8b004f.png)
