### ISSUE TITLE
Regular user does not see the "Global" catalogs listed in "Catalogs" page or in the catalog dropdown in the "Catalog App" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17638]
Rancher server version - Build from master

Setup - AD auth enabled setup.

Steps to reproduce the problem:
As admin user , Create a "Global" catalog - "test1"
Log in as a regular user.

Go to Global -> Catalogs does not list the Global catalog -"test1".

When trying to deploy an app from this global catalog , they do not appear in the  catalog dropdown in the "Catalog App" page but the apps from this global catalog is made available for users to deploy the app.

Information about the catalog from which this app is presented is not there

<img width="627" alt="screen shot 2019-01-25 at 5 32 10 pm" src="https://user-images.githubusercontent.com/4266958/51780974-0e7afd00-20c8-11e9-8af2-79d95e5e1c1b.png">

**Comment by mrajashree** [comment]
Non-admin users weren't allowed to list global catalogs even earlier.

**Comment by sangeethah** [comment]
Related to - https://github.com/rancher/rancher/issues/17625

**Comment by jiaqiluo** [comment]
Here is a little more info about issue 1:
1. `cluster owner` cannot see `global` level catalog in the catalog management panel and the drop-down list when launching apps
2.  `project owner` cannot see both `global` and `cluster` level catalog in the catalog management panel and the drop-down list when launching apps

tested on Rancher:master 1/30 
![screenshot](https://user-images.githubusercontent.com/6218999/52020280-faf7d980-24ad-11e9-8975-36e471ff826a.png)
![screenshot](https://user-images.githubusercontent.com/6218999/52020292-06e39b80-24ae-11e9-93dd-3b0a70e2ece1.png)



cc/ @mrajashree @sangeethah

**Comment by jiaqiluo** [comment]
The bug fix is validated on master 2/11.
The setup and steps are the same as the original post describes.
The fix for issue 1 is validated for all cases in the following table: 
 
See   Catalog in management panel
--
Roles | Global | Cluster | Projects
-- | -- | -- | --
Admin | yes | yes | yes
Cluster owner | yes | yes | yes
Cluster member | yes | yes | no
Project    owner | yes | yes | yes
Project member | yes | yes | yes
Project Readonly | yes | yes | yes

Issue 2 is tracked by this ticket: https://github.com/rancher/rancher/issues/17625
