### ISSUE TITLE
Master node - moving to a different server

### ISSUE THREAD

**Issue by iamdevnull** [rancher/rancher#17646]
hey guys,

1.) how does the recommended way look like for moving a master node (etcd, controlplane) to a different server. i am uncertain because of this issue https://github.com/rancher/rancher/issues/14102 2 the new master node would have a new ip address.

2.) what is technically the difference between --address and --internal-address with regard to the " Rancher Agent Options" https://rancher.com/docs/rancher/v2.x/en/admin-settings/agent-options/
is it possible to build a 3 node cluster (1 master - 2 worker) inside a private vlan/subnet and to control the external access to the cluster through a firewall (inbound - dnat / outbound - snat) ?
if this would be possible then i dont understand the meaning of the options “–address and --internal-address”.

i would welcome your response.

best regards

https://forums.rancher.com/t/master-node-moving-to-a-different-server/13115

Regards

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by m-osmani** [comment]
i would really appreciate an answer.

**Comment by m-osmani** [comment]
Are my questions so dificult ? My first question is a very general question concerning migration of master nodes.

The second one wants only a clarification of —address and —internal-address.

An answer of Rancher Supporter would be nice.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by superseb** [comment]
The way to "move" a node would be adding a new node  and removing the old node. I can't find any explanation why it has to be moved explicitly, so adding a new node and removing the old one (keeping in mind quorum for etcd) should be fine.

Documentation on the agent options is already linked, RKE documentation has some additional info on most options (https://rancher.com/docs/rke/v0.1.x/en/config-options/nodes/). Nodes will be registered using 1 or 2 IPs and those will be used to get the info from API to show in the UI. If you want to do translations in the network to get the traffic there, it will probably work but as there is no description of what you are doing exactly, it's hard to tell. (Workload in cluster -> outside only, in and outside, both ways translated?)

**Comment by m-osmani** [comment]
@superseb thx a lot for your answer.

my network looks like this at the moment:

master (etcd+controlplane) - eth0 - public - created with „docker run xyz —address [public-ip]“ by rancher ui (2.1.5)

node1/2 (worker) - eth0 - public - created with „docker run xyz —address [public-ip]“ by rancher ui (2.1.5)

http/s access over traefik ingress controller with custom external-ip

—-

From my security point of view it is not optimal that all nodes are directly open towards the internet.

Therefore i want to change the running setup without buying and deploying new nodes:

INTERNET <- Central Firewall (fixed external-ip - open ports 80/443 - inbound dnat - outbound snat to ingress controller ) <- Cluster ( eth0 - private ip - all nodes )

i am uncertain because of this issue https://github.com/rancher/rancher/issues/14 if i can change the public ips against private ips and that the cluster would work after the change.

If it is possible how can i change the ip of the the running rancher/k8s service container which are normaly started/triggert initially by the main rancher container ?

Best regards

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
