### ISSUE TITLE
There is no indication on when external DNS entries are made available.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17688]
Rancher server version - Build from master - jan 28

Steps to reproduce the problem:
1. Create a globalDns entry with fqdn - "test1.test.com" with projectIds set to Cluster1 and project p1.
2. Create globalDnsProvider with root domain - "test.com"
3. In user cluster - Cluster1 and project p1, Create Ingress - ingress1 using annotation - rancher.io/globalDNS.hostname=test1.test.com which points to a workload with host name rule pointing to "test1.test.com"
4. Wait for the ingress to get to "Active" state . Try to access the ingress url - test1.test.com. This is still not accessible at this point since the Route53 entry may not have been created at this point.
 
After some delay (up to 1 minute) , we see an FQDN entry getting created with ingress1's ip in Route53 after which the ingress url becomes accessible.

It would be good to give some indication on when the external DNS entries are made available and  ingress url becomes accessible.

**Comment by prachidamle** [comment]
I don't think we will be able to facilitate this. Since we do not poll the external-dns providers ourselves we do not have a track of what FQDN's are present in the hosted zone. We just provision dummy ingresses with the necessary FQDN and endpoints and offload the rest to kubernetes/external-dns deployment.

**Comment by alena1108** [comment]
Moving out off 2.2 given the comment above
