### ISSUE TITLE
[rancher-mesos-executor] 

### ISSUE THREAD

**Issue by neuhausler** [rancher/rancher#1775]
executor.go is importing "github.com/rancherio/rancher-mesos-executor/orchestrator", which can't be resolved. I guess it should be rancher instead of rancherio?

**Comment by deniseschannon** [comment]
Github is redirecting any rancherio to rancher. But if I try to find the page under rancher ,it's a 404.

@wlan0 Can you take a look?

**Comment by vincent99** [comment]
All the code should be updated to use `rancher` instead of `rancherio`.  This particular repo was created after we switched the org name so there is no redirect, and the redirect shouldn't be relied on anyway.

It's a golang import, so the /orchestrator part is not a literal URL but the directory once the code is pulled down. https://github.com/rancher/rancher-mesos-executor/tree/master/orchestrator

**Comment by wlan0** [comment]
Fixed in https://github.com/rancher/rancher-mesos-executor/pull/1
