### ISSUE TITLE
UI - Multicluster app chart options always display default values

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#17820]
rancher/rancher:master 2/1
UI - latest2

After changing the default options when deploying a multicluster app, the actual values are not reflected in the UI upon upgrading. The answers are correct in the API.

To reproduce:
* Deploy multicluster app, changing some settings
* Click upgrade

Expected:
* The actual values are reflected

Actual:
* Default values are shown (See services.nodePort below)

![screen shot 2019-02-01 at 3 43 42 pm](https://user-images.githubusercontent.com/21316915/52153689-39b99b00-2638-11e9-9667-085cb7fbcea2.png)
![screen shot 2019-02-01 at 3 43 57 pm](https://user-images.githubusercontent.com/21316915/52153691-3cb48b80-2638-11e9-8756-1e9bc7f0ae97.png)

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/1/19)
Confirmed fix. I tested using the same app and steps and could not reproduce. I deployed a MC app, changing some settings such as setting docker-registry app to use ClusterIP instead of default NodePort. Once the app provisioned, I upgraded and I can see all my changed settings are still there.
I briefly smoke tested a couple of other apps to ensure this was the case with others as well including with an app that did not fully provision (still deploying). I encountered no issues in this area. The API/http appears correct.
