### ISSUE TITLE
UI - Add ability to access SSH keys to EKS driver

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#17875]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
keyPairName is the new resourceField to be used

**Result:**
Able to specify a previously created EC2 ssh key pair.

**Other details that may be helpful:**
https://github.com/rancher/rancher/pull/17868
https://github.com/rancher/kontainer-engine/pull/125
https://github.com/rancher/rancher/issues/14598

**Comment by davidnuzik** [comment]
The ssh key is for the nodes in the cluster and so I think it should go under the Nodes section not Cluster Options. Could we change this?

**Comment by westlywright** [comment]
@davidnuzik that makes sense I'll make the change.

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: Master (4/29/19)

Confirmed the “SSH Key” drop down was added and then moved down to the Nodes section (I requested that change). The list enumerated correctly and I saw my key and was able to choose this. HTTP/API looks good.

HTTP/API for the cluster:

keyPairName: "David.nuzik-us-west-2"Screenshot of this:

!image-20190429-155702.png|width=614,height=180!

FYI in the API this is of type String, as expected. Also, you can start typing in the drop-down to filter through all the results which makes life a lot easier.

!image-20190429-160518.png|width=302.5,height=71!

You must pick an item from the drop-down however (which is good as this should prevent mistakes due to mistype). For example as pictured above I cannot submit with “David.nu” if I click off the field it will blank out again since I did not pick an item from the drop-down menu.

I made sure I could connect to the nodes via SSH without any issues.

NOTE: Your security group must be configured to allow inbound port 22 (SSH) – I had to manually change the default SG to allow this before I could connect as user ec2-user.
