### ISSUE TITLE
Helm Libaray Multi Cluster Apps Fail Silently When Launching

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17888]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enable Helm Library and wait for sync to finish
Launch a multi cluster app from the Helm Library, I used MySQL or Mongo
Without inputing any extra data

**Result:**
Nothing happens

**Other details that may be helpful:**
Adding answers via the key/value input or answer overrides causes JS error

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2-alpha 
- Installation option (single install/HA):

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/7/19)
Confirmed fix. Activate HELM stable charts. Wait for it to finish syncing. Deploy mysql using helm stable catalog. Quickly deploys (deploys but is not functional since we are missing required information). Try again by overriding answers by filling in key:value pairs and with overrides. Still works without any JS errors reported in browser console with either of these.
