### ISSUE TITLE
Increase command-timeout value

### ISSUE THREAD

**Issue by fsunaval** [rancher/rancher#1790]
I've seen the threads saying that the "command-timeout" value for the curl scripts in the ranch client is too low.  Has the fix been committed to allow adjustable command-timeout for the scripts ?

**Comment by ibuildthecloud** [comment]
We increased the timeout to 20 seconds in https://github.com/rancher/cattle/commit/5e3fd20380243b51c0a3c36ae9f80c31a91573a5.  We didn't make it configurable though.  The problem with configuration is that if 20 seconds isn't working for you and you need to increase to 60 seconds then the latency is just too high and it will cause downstream issues.  It was previously low because we need connection to not take a very long time.  What we didn't realize at the time was that apparently DNS resolution is included in the connect time, not just the TCP connection.  So we can increase it to 20, but beyond that we believe we will start hitting issues.

**Comment by deniseschannon** [comment]
I am closing this issue in favor of #1366 to configure the default timeout value. This issue is to track that we increased the default value to 20 seconds.
