### ISSUE TITLE
UI support for multiclusterapp rbac changes and actions

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#17975]
This ticket is to track the changes to multiclusterapp UI made for rbac
1. Multiclusterapp spec will have a new field for Roles which references v3.RoleTemplate
2. There will be 2 new actions on multiclusterapp called addProjects and removeProjects for modifying the projects. Both will take as input a list of v3.Project, and for addProjects you can also provide project-scoped answer overrides for the new projects by passing a list of v3.Answer
3. Targets field is now non updatable in the API, since we have actions described above for updating them.
4. Rest of the fields can be updated via Edit/PUT

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/19)

Confirmed UI support for MCapp RBAC and some additional per issue description:

1. Multiclusterapp spec will have a new field for Roles which references v3.RoleTemplate
![image](https://user-images.githubusercontent.com/45179589/53046485-5eda4600-344d-11e9-92c5-d5f6d5b342f4.png)
Confirmed this is working as expected; I also cannot add a user that does not have the roles provided and get a proper error in the UI explaining the issue.
I found a minor translation issue (missing translation) #18237

2. There will be 2 new actions on multiclusterapp called addProjects and removeProjects for modifying the projects. Both will take as input a list of v3.Project, and for addProjects you can also provide project-scoped answer overrides for the new projects by passing a list of v3.Answer
This was tested in detail in #17853 please refer to that issue. This is working as expected.

3. Targets field is now non updatable in the API, since we have actions described above for updating them.
See #17853 Working as expected.

4. Rest of the fields can be updated via Edit/PUT
This was also tested in #17853 and is also working as expected. I did some additional testing to test some other fields I did not cover in that issue.

I also saw the Members field and tested this as well.
![image](https://user-images.githubusercontent.com/45179589/53046753-035c8800-344e-11e9-8f92-9abdac5249f9.png)

HTTP/API looks correct. Tested POSTs and PUTs (create/edit) and Deletes.
Further testing in this area will continue as we fix various RBAC and other issues.
