### ISSUE TITLE
Enhance monitoring actions with pre-emptive RBAC short circuit

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17987]
We currently defer all auth checks down to prometheus auth. We dont do any checking in rancher. But, when we did the prom refactor, we now have an exlicit permission that we could check to see if the user has before showing the actions for accessing grafana or showing chart links.
This does not need done for v2.2. We are enforcing rbac properly, i just would like to see this change so that we can dynamically hide monitoring for folks that should not see it.

**Comment by cjellick** [comment]
TBD == We currently defer all auth checks down to prometheus auth. We dont do any checking in rancher. But, when we did the prom refactor, we now have an exlicit permission that we could check to see if the user has before showing the actions for accessing grafana or showing chart links.
This does not need done for v2.2. We are enforcing rbac properly, i just would like to see this change so that we can dynamically hide monitoring for folks that should not see it.
