### ISSUE TITLE
UI: GKE Cluster Options that require api endpoints

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#17992]
UI for https://github.com/rancher/rancher/issues/14298

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/13/19)
Per the linked backend issue this adds new areas to the UI for GKE:

* additional zones
* network
* project access
* maximum number of nodes per pool

![screen shot 2019-02-13 at 12 08 56 pm](https://user-images.githubusercontent.com/45179589/52737043-9d24c080-2f88-11e9-9269-2668ee15183b.png)
Additional zones can be added on to your primary (drop down) by checking boxes as seen in the screenshot above. You can pick your network as well from a drop-down list of available networks.

![screen shot 2019-02-13 at 12 10 00 pm](https://user-images.githubusercontent.com/45179589/52737047-9f871a80-2f88-11e9-987f-998e0c76123f.png)
You can limit project access by setting Security options to set oauth scope. You can enable min/max nodes per pool by enabling node pool autoscaling.

I validated for each the various options and ensured http/api looks correct.
Additional zones just adds more entries to locations:
```
locations: ["us-central1-b", "us-central1-c", "us-central1-a"]
0: "us-central1-b"
1: "us-central1-c"
2: "us-central1-a"
```

network:
`network: "hgalal"`

Project access is oauth settings:
```
oauthScopes: ["https://www.googleapis.com/auth/devstorage.read_only",…]
0: "https://www.googleapis.com/auth/devstorage.read_only"
1: "https://www.googleapis.com/auth/logging.write"
2: "https://www.googleapis.com/auth/monitoring"
3: "https://www.googleapis.com/auth/servicecontrol"
4: "https://www.googleapis.com/auth/service.management.readonly"
5: "https://www.googleapis.com/auth/trace.append"
```

node pool size:

```
maxNodeCount: 3
minNodeCount: 1
```

Validated UI checking the various options. Validated HTTP/API as well for each area. Ensured can edit and update these settings for an existing cluster. Note if the cluster is in a bad state because wrong network was picked you cannot recover from this.
While testing this a few issues were found and entered around GKE.

@loganhz may I ask for a quick review of my testing above? Did I understand the new areas correctly and relating API? I tried to look in PRs/Commits but it's difficult for me to pinpoint exactly what is what.

**Comment by fyery-chen** [comment]
@davidnuzik yes, your testing step is right, as you said
Locations ---> additional zones
Network ---> network
Security ---> project access
Node Pool Autoscaling ---> maximum number of nodes per pool

**Comment by n313893254** [comment]
Here is GKE UI:
- Node Pool Autoscaling:
![image](https://user-images.githubusercontent.com/18737885/52758015-b0e02d80-3041-11e9-8d9e-e4a1d402a954.png)
- Security:
![image](https://user-images.githubusercontent.com/18737885/52758026-c48b9400-3041-11e9-8896-0ab65bdab538.png)
- Locations and Network:
![image](https://user-images.githubusercontent.com/18737885/52758059-e2f18f80-3041-11e9-837a-38132f8a0f5d.png)

**Comment by davidnuzik** [comment]
Thank you both :) Yes looks like I got this correct based on what I see you have both sent.
I am closing the issue based on my testing done above see the comment here: https://github.com/rancher/rancher/issues/17992#issuecomment-463350596
