### ISSUE TITLE
The eth0 10.x.x.x ip address is not available immediately when rancher starts

### ISSUE THREAD

**Issue by feliksik** [rancher/rancher#180]
If you run without rancher

docker run -d -p 7077:7077 -p 8080:8080 --name spark_master mraad/spark /usr/local/spark/sbin/sm.sh

all is fine. Alternatively, you can run with rancher the equivalent of

docker run -d -p 7077:7077 -p 8080:8080 --name spark_master mraad/spark /usr/local/spark/sbin/sm10.sh

This scripts tries to detect the 10.x.x.x ip address from Rancher  with

export SPARK_LOCAL_IP=$(ip -o -4 addr list eth0 | awk '$4~"^10"{split($4,A,"/");print A[1]}')

This works fine if you start with /bin/bash and then run the script manually in the terminal. Problem is that this address only comes available after the container is started (there is a delay). So the script assumes that the eth0 address is available, but this is not yet the case just after starting. 

Ideally, you would have a mechanism to know the IP from within a container -- such as the one above. The question is whether rancher should guarantee the availability of the 10.x.x.x address, or whether the script should be more robust. At least this one was tricky to debug, especially since the ip-hack is not used when you run with the docker command. So I had to fall back to debug prints in the shell script.

**Comment by cjellick** [comment]
The delay is due to the fact that we do indeed inject the IP after the container has started. We do this by accessing the container's network namespace and unfortunately, that isn't available until the container is up and running.

So, I think your safest bet for the near term might be to add some resilience to the script so that it tries/sleeps for a few seconds.

That said, in an upcoming release (likely next week's), the rancher ip will actually be available inside the container as the environment variable `RANCHER_IP`. So, once that is released, you could potentially key off of that. But this solution isn't perfect either: we are setting it as an environment variable as a work-around until docker implements container labels. We didn't intend the environment variable to be a user facing feature, so once docker labels is released, we'd like to switch over to using that mechanism. Also, the data in that environment variable won't by a simple IP, it'll look like `10.1.2.3/16` or `10.1.2.3/16|eth0`. But it looks like your parse/discovery script would already handle that.

Finally, much further down the road, when and if docker implements a plugin framework that allows for real hooks into the container provisioning life cycle, we should be able to guarantee the IP is available by the time the container starts. But again, that is further down the line.

@ibuildthecloud have anything to add to this?

**Comment by ibuildthecloud** [comment]
The correct solution here is that we have one and only one IP assigned and it's the IP managed by rancher.  Good progress is being made on this front such that Docker will provide a proper hook for this.  We're looking at Docker 1.7 for this (June).

In the mean time there is not a lot we can do to get the IP immediately assigned short of shipping a custom version of Docker.  We can do it really fast, but can't guarentee that always.  I'll keep looking for a solution.

**Comment by feliksik** [comment]
I understand the situation, and I think building resilicience in the scripts is perfectly fine for now. Maybe my assumption that the IP would be immediately available was silly. At least, be warned that people may suffer a bit while finding this out (documentation on "determine your ip" would solve this entirely)

**Comment by santagada** [comment]
We apparently were bitten by this, isn't there a way to wait a second or two after image start?

we have a wget as first command on a bunch of images so I will change it to wget  --retry-connrefused --waitretry=1 --tries=5 to see if it fixes it. Hopefully 5 seconds is enough

**Comment by santagada** [comment]
just one more question, would this manifest in kubernetes clusters as well or is this just how cattle works?

**Comment by vincent99** [comment]
@santagada What version are you on?  This should have been fixed somewhere in 1.0.x

**Comment by santagada** [comment]
Component	Version
Rancher	v1.1.3
Cattle	v0.165.8.1
User Interface	v1.1.12
Rancher Compose	v0.8.6

os: Amazon Linux AMI 2016.03

**Comment by leodotcloud** [comment]
With the new CNI plugins, the IP address is assigned to the container before it starts. Please file a new issue if you are still having problems.
