### ISSUE TITLE
get/create/update/delete CRDs in the Rancher UI

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#18013]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
It would be nice to have an ability to get/create/update/delete CRDs in the Rancher UI. At least to make them visible.

**Result:**
Maybe there can be an configuration field, where the CRD can be configured, which shows up somewhere in the project UI part as an dynamic item.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA): N/A

gz#3400

**Comment by AlexisDucastel** [comment]
Even a raw yaml Editor would be great, because `kubectl edit` does not work well in "kubectl" shell on cluster tab.

For example, I'm currently updating my rook-ceph cluster to image v14.2.4-20190917, I would have a yaml editor to make this change rather than download kubeconfig and start kubectl from my workstation.

**Comment by deniseschannon** [comment]
In the new Cluster Explorer view with 2.5, all CRDs are visible and you can manage those CRs directly in the Rancher UI.
