### ISSUE TITLE
[rancher-mesos-scheduler] 

### ISSUE THREAD

**Issue by jazzman809** [rancher/rancher#1804]
This is great progress, I have some queries though about setting this up on a production environment.

Where should each package be installed? I know the executor is installed on the slave(s). Am I correct to assume Libvirt is also installed on the slave(s)? Should I install the scheduler on the Mesos master(s), a separate VM, etc.?

Just a bit confused on what goes where? Thanks for the help.

**Comment by wlan0** [comment]
@jazzman809 libvirt and the executor should be installed on the slave. The slave uses the executor, which then uses libvirt to launch VMs. 

The scheduler can be run on any host/VM that can reach both rancher-server and Mesos master through the network. The scheduler obtains task requests from rancher server and obtains resource requests from Mesos master. In my development setup, I generally run the scheduler on the same host as rancher server. 

That said, we do not recommend that you run Rancher Mesos framework in production as it is right now. It can be run in production once we integrate all of Mesos' error handling and robustness features into the Rancher Mesos framework.

In order to understand the architecture of the Rancher Mesos framework better, please refer to this blogpost - http://rancher.com/rancher-and-apache-mesos-docker-in-production/

**Comment by deniseschannon** [comment]
@jazzman809 If you have further questions, please re-open and ask away. :)
