### ISSUE TITLE
When creating Azure/vSphere RKE for first time should not see cluster options until after set up cloudCredential

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18093]
Version: Master 2.2 (2/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- On a fresh install add an Azure or vSphere RKE cluster
- Notice that you can immediately see cluster options before entering cloud credentials or picking one from drop-down.
- Compare to other providers. You don't see cluster options until you have completed picking/entering cloud credential on the node template modal.

**Result:**
Azure/vSphere RKE is not in alignment with other providers. We should only see our azure cluster options after entering cloud credential.

**Comment by westlywright** [comment]
This won't change right now, the reason you see the provider options for Azure and vsphere is because these UI never talked to the provider api's. The infra providers functioned this way before cloud keys were introduced. Perhaps we can move this out of the 2.2 milestone and attach it to rancher/rancher#18037. When we add key validation for the other providers it would make sense to update the node templates. 

@cjellick thoughts?

**Comment by davidnuzik** [comment]
Yes Sangeetha explained this to me earlier yesterday. I think it's fine to move out of 2.2 scope.

**Comment by cjellick** [comment]
Sounds good moving out

**Comment by tfiduccia** [comment]
@davidnuzik - Redesigning Add Cluster, so closing this in favor of that. #23313
