### ISSUE TITLE
UI for TTL field in Global DNS entry

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18101]
This ticket is track the support UI for  TTL field in Global DNS entry.
Server ticket - https://github.com/rancher/rancher/issues/17871

**Comment by davidnuzik** [comment]
When you create a GDNS entry the default TTL shown in the UI is zero. When you submit the form to create it it sends zero in request payload and server responds confirming a setting of zero. When you inspect R53 it's the default per linked issue #17871 with a setting of 300. When you inspect the GDNS entry in the API it's also 0. Backend issue @westlywright ? Or my guess is 0 == DEFAULT (300) still confusing in UI though.

![image](https://user-images.githubusercontent.com/45179589/53041639-b5418780-3441-11e9-8544-223c32fc5587.png)

**Comment by westlywright** [comment]
@davidnuzik the default in the schema ( `v3/schemas/globalDns` is 0. If that needs to change then yes it needs a backend ticket. if 0 === 300 in this case that is very confusing.

**Comment by davidnuzik** [comment]
My bad @westlywright I should have looked at the schema. I agree this issue is working I will open a backend ticket.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/22/19)
Confirmed issue. There is a field now to enter the TTL (Time to live).
I confirmed that the number entered in the UI is what ends up in Route 53.
HTTP/API looks good.

For some reason the default is zero in the API so I opened a separate ticket to track this. When you enter 0 it's actually 300 in Route 53 so this is confusing. The API should default to 300 rather than zero.
Issue for backend issue with api: #18349
