### ISSUE TITLE
Bug - UI for Docker version in the node templates dropdown

### ISSUE THREAD

**Issue by Coopyrightdmin** [rancher/rancher#18117]
*Describe your issue here*
In order to solve the last CVE and comply with Rancher Recommendations, I would like to upgrade my cluster to Docker 18.09-2.

Unfortunately, this version is not part of the node template dropdown yet.

Could you please make correction #17547 available for Rancher 2.1.x?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.6` UI: `v2.1.19` |
|Route|`global-admin.clusters.index`|

**Comment by vincent99** [comment]
It's a text field, you can put in whatever URL you want.  The "Latest" option fills in `https://get.docker.com` which goes straight to docker and is always their latest release.

The versions we host are mainly because Docker does not provide a way to get anything _other than_ the latest release.  They are listed in https://github.com/rancher/install-docker and available at `https://releases.rancher.com/install-docker/xx.yy.sh`
