### ISSUE TITLE
MultiCluster App - Not able to present project details correctly for a user who is the owner of the MCAPP but does not have access to the project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18153]
Rancher server version - Build from master.

Steps to reproduce the problem:
Create a standard user - `test1`.
As admin user, Create a Multi cluster app with targets as projects from 2 different cluster and add "test1" as owner.

Log in as `test1` and go to  Multi-cluster app tab .

Notice that the target links are empty for the Multi-cluster app.

<img width="734" alt="screen shot 2019-02-14 at 8 17 56 pm" src="https://user-images.githubusercontent.com/4266958/52834237-b10a1880-3095-11e9-8715-e52ffed9c402.png">

When clicking the link user is taken to the log in page.

Use "upgrade" option for the Multi-cluster app .

Project details in this page is empty.

<img width="1199" alt="screen shot 2019-02-14 at 8 17 46 pm" src="https://user-images.githubusercontent.com/4266958/52834287-f595b400-3095-11e9-8acf-47ea67a2e7c2.png">

**Comment by sangeethah** [comment]
@westlywright @mrajashree I was not sure if there needs to be server side fixes for UI to be showing the right set of things here. So assigned the issue to both of you.

**Comment by cjellick** [comment]
I _think_ this should be a UI issue where we just need to display something explicit that describes that the current user doesnt have access to particular project links

**Comment by cjellick** [comment]
we arent filtering out the project/clusters on the MCA in the api are we @mrajashree ?

**Comment by mrajashree** [comment]
@cjellick nope, we don't filter out project/clusters on the MCA in the api based on whether user has access or not

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/19/19)
Confirmed fix. I followed the steps to reproduce and now I see an appropriate message in the UI indicating I do not have access to the projects. 
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/53056890-36147980-346a-11e9-8f15-3f29716231d5.png)

Similarly, when I upgrade the mcapp I see a message here as well indicating I do not have access to the projects.
Screenshot:
![image](https://user-images.githubusercontent.com/45179589/53056930-59d7bf80-346a-11e9-8160-b9fb322a8657.png)

I confirmed I could still otherwise manage the project i.e. upgrade. I changed one of the answers without any issues and confirmed this took effect.
