### ISSUE TITLE
[rancher-compose] upgrade action cleanup

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#1817]
Just testing the upgrade action of the rancher-compose app and stumbled across a possible bug/possible design decision. 

Currently the compose action 'upgrade' removes all containers and purges them from the old service but it leaves the service definition in-place. This results in lots of 'old version' services dotted around the GUI you have to manually clean up.

If it's a bug then i might have a crack at a branch to resolve this, thought i'd check first though.

Rancher V32, compose v.0.2.5

**Comment by sangeethah** [comment]
@Rucknar , we have a similar issue that tracks this behavior - #1602 .

**Comment by Rucknar** [comment]
Apologies - missed that.
Just had a read, that's been closed as 'wont fix' but it's suggested this could be fixed by using a flag.

That would be useful for us as we wish to automate our release process and this is currently a blocker. 
I'll see if we can get a branch put together for you to review.

**Comment by sangeethah** [comment]
@Rucknar , it would be good to have the option to clean up the service after upgrading which is controlled by a flag . Thanks.

**Comment by Rucknar** [comment]
^ Had a stab at this, ready for review when your ready.
Thanks.

**Comment by sangeethah** [comment]
Tested with rancher compose version - v.0.2.6

When passing cleanup option to upgrade , the old version of service gets removed after upgrade is completed:

In the following example , if web6 is associated with other LB / Alias services as target , after upgrade to web7 , web6 gets removed and which also results in web6 links to  LB / Alias services being removed and replaces with with web7 links.

./rancher-compose -p testrancher -f dc1.yml upgrade web6 web7 --cleanup

In cases were we cancel upgrades when it is in progress ,  should "--cleanup" flag  be ignored since upgrade has not been completed successfully and the old service should continue to be in "active" state?

Current behavior seen is , when --cleanup flag is used and the upgrade process is cancelled , the old service is removed. This may not be the desired behavior.

Reopening this issue to address this behavior.

**Comment by ibuildthecloud** [comment]
@sangeethah I think it would make sense to add a check to the cleanup logic to only do the cleanup if the source service scale reached zero.  Otherwise print a warning that cleanup didn't happen as scale 0 wasn't reached.

**Comment by Rucknar** [comment]
Totally agree with the recommendation. @ibuildthecloud I've had a poke about the code to see how this could be done but it might be slightly more complex than my knowledge of Go allows. If you could give me some pointers on how i can obtain the scale factor of an existing service then i could do a branch with that in as a fix.

**Comment by sangeethah** [comment]
Tested with rancher compose version - v0.3.0-rc1

In cases were we cancel upgrades when it is in progress  with "--cleanup" flag enabled , the original service is not removed which is as expected.  If there are LB services that have targets to this service , it continues to have links to both the original service and the upgraded service.

User is provided with a message stating that service is not deleted.

```
root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.3.0-rc1# ./rancher-compose -p Default  -f dc-upg1.yml upgrade test1 test2 --cleanup
INFO[0001] Creating service test2                       
INFO[0003] Upgrading test1 to test2, scale=10           
WARN[0013] Not deleting service test1, scale is not 0 but 8 
root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.3.0-rc1# 
```
