### ISSUE TITLE
UI: Monitoring - Refactor project level

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18204]
UI for https://github.com/rancher/rancher/issues/18115

**Comment by loganhz** [comment]
Now we can enable project level monitoring without enabling cluster level moniotring

**Comment by davidnuzik** [comment]
1. Enable project-level monitoring. See grafana-project-monitoring and prometheus-project-monitoring workloads deploy successfully.

2. Inspect workload/pod/container details and no charts are shown for any of these.

@cjellick @loganhz FYI.

**Comment by cjellick** [comment]
You're kicking it back to dev right @davidnuzik ? I think the reopened label should have been added

**Comment by davidnuzik** [comment]
My bad @cjellick added that to my notes as reminder going forward.

**Comment by loganhz** [comment]
@davidnuzik  As the pods/containers cpu/memory metrics are from cluster level monitoring. So we cannot show the icon for pods/containers and Graph in Rancher UI if only project level monitoring is enabled. So it is expected. 

The purpose of enabling project level monitoring only is that users will be able to collect custom metrics. Then users can jump to the grafana page (you can find it in catalog app page) to see the metrics.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/20/19)
Confirmed issue.

- Deploy project level monitoring. Ensure can access grafana web ui (index.html via catalog app) and that it works as expected. (Can see appropriate namespaces, pods, containers in this project).
![image](https://user-images.githubusercontent.com/45179589/53183866-5272fc00-35b9-11e9-8e32-4bf9b4fca9e5.png)
- Go to Cluster level monitoring. Ensure this page does not read as "Enable" since we have not enabled it.
- Enable Cluster level monitoring. Once it is complete briefly test; now disable it.
- Ensure that our project level monitoring is still enabled (disabling cluster level did not turn it off).

While testing watched for issues in browser console, smoke tested grafana/rancher, did not identify any issues.
