### ISSUE TITLE
Availability Zones shown in TKE cluster options is incomplete

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18219]
**Rancher Version**
master 02/19

**Steps to reproduce (least amount of steps as possible):**
1. Activate TKE cluster driver
2. Create a TKE cluster
3. Configurations are shown as followings:

**Result:**
![image](https://user-images.githubusercontent.com/5697937/52989435-575f7080-343e-11e9-8f85-8d8de3412ea3.png)

Only two of the four AZ are shown in the dropdown, therefore I cannot choose subnet from AZ-1/2.
But from the console I can see that API is returning 4 AZs.

**Comment by n313893254** [comment]
@gitlawr 
![image](https://user-images.githubusercontent.com/18737885/53218787-7c4f2000-3698-11e9-95dc-47f08fc5365f.png)

It only shows AZ-3/4 in TKE UI. Because AZ-1/2 `zoneState` is unavailable.
![image](https://user-images.githubusercontent.com/18737885/53218846-b4eef980-3698-11e9-9ae6-f7b59e27c1fb.png)

**Comment by gitlawr** [comment]
It is an expected result then.
