### ISSUE TITLE
Filtered Environment Variables in API

### ISSUE THREAD

**Issue by gerred** [rancher/rancher#1822]
Currently, environment variables are not filtered when getting a container through the API. A filter list would be handy, to help prevent exposure of secrets set as env vars.

**Comment by vincent99** [comment]
While we don't have a better secrets management system to offer as an alternative yet, I would highly suggest not using environment variables like this; they aren't secret.

All the environment variables on a container are available to any other container that links to it or anyone with access to the host's docker daemon as standard Docker behavior.  We actually used to specifically *not* copy linked env vars in Rancher because (it's a terrible idea and) we have some additional control over the linking process vs standard Docker, but too many people's applications depend on this behavior.

So hiding them from the API would just be obfuscation.

**Comment by gerred** [comment]
@vincent99 - that makes sense. Right now, the using an external MySQL requires the use of environment variables, leading to me opening this issue. Is this something that will be remedied with secrets management and, if so, is there a working issue/PR for this?

**Comment by vincent99** [comment]
It's on our roadmap, there's an issue you can track (https://github.com/rancher/rancher/issues/1269) but no concrete work yet.  There are a few possible ways go to about it, involving such things as [rancher-metadata](https://github.com/rancher/rancher-metadata) service that will be available soon, a special volume or volume-driver that provides the secrets as files (but can't be `--volumes-from`ed), and asymmetric encryption.

Providing a bridge from the secrets management to environment variables seems like a reasonable request.  If that didn't exist, it would still be trivial to run `export MYSQL_PASSWORD=$(whatever_you_do_to_get_secrets "the_name_of_the_mysql_password_secret")` before invoking the main $your_application process.

**Comment by gerred** [comment]
Ok. Great. I'll track and hopefully be able to contribute on that side! Closing this issue.
