### ISSUE TITLE
When creating cluster Node Template is no longer auto-selected for you when have more than 1 template

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18247]
Version: v2.1.8
Version: Master 2.2 (2/19/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster and node template.
- Create another node template.

**Result:**
The Node Template is no longer picked for us when have 2 or more. This was working earlier today (2/19) (but perhaps the browser cached this as last picked somehow?).
![image](https://user-images.githubusercontent.com/45179589/53053611-20e61d80-345f-11e9-9c38-5104e4ef8ac3.png)

**Other details that may be helpful:**
For my testing I was using EC2. I also tried clearing my browser cache and still observe the issue.

**Comment by deniseschannon** [comment]
@tfiduccia can you let me know if this works in 2.1.8 and it regressed in v2.2.1?

**Comment by davidnuzik** [comment]
@deniseschannon Tani checked and exists in v2.1.8; updated issue to mention this version as well

**Comment by westlywright** [comment]
@deniseschannon @davidnuzik I don't think this change makes sense. I'm not sure why it was auto picked for David the first time but I speculate that as mentioned it could have been a caching issue or perhaps the new node template was created in a different tab or window.

Regardless, when the user has two node templates to choose from it would be incorrect to select one for them. Logically, when only a single node template exists for a given cloud provider it would be safe to assume the user wants this node template selected because they have no other templates available and they know the cost of that template on the cloud provider and the options.  Conversely, when more than one is available the same assumption can not be made. For example, the cost for standard droplets doubles every step up. If the user has one 2gb template named `smallish-do` and a 32gb template named `largish-do` the cost difference is massive and the name gives no indication of the actual size. Making the user choose is an explicit action and implies the user knows the options of that template. If anything we should change it so the node template selection _never_ auto selects. The first assumption could still cost an organization extra money if the user wasn't paying attention and they thought they'd already added a small node template but only had a single large template available. 

I think those arguments are extreme but in cases where we select options for hosted k8s providers we choose the smallest resource that will work for Rancher in an effort to avoid issues like this so, IMO, it follows we'd apply the same logic here.

**Comment by cjellick** [comment]
Agree with Wes's analysis. I dont think we need to auto-select here. We are very likely to make the wrong choice on behalf of the user. Feel free to reopen and comment if you still feel strongly @davidnuzik

**Comment by davidnuzik** [comment]
Thanks, yes it's a valid point and I agree with Wes as well.
