### ISSUE TITLE
Unable to create RKE Cloud Key when using uppercase name, UI should not allow uppercase

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18272]
Version: Master 2.2 (2/20/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Try to create a any RKE Cluster. You will be prompted to create a Cloud key. Enter uppercase in the name for the cloudkey.

**Result:**
You cannot create a cloudkey unless it's name is lowercase because of the dnsLabel type used by the API.
If the name of the cloudkey has capital letters you will get this message in the UI:
![image](https://user-images.githubusercontent.com/45179589/53115955-aec81400-3504-11e9-8dba-d82df2d1b370.png)
If you then try right after with lowercase you will get a different message because the UI also isn't sending the whole object now
![image](https://user-images.githubusercontent.com/45179589/53115972-bbe50300-3504-11e9-9821-fa94b943dde7.png)

**Other details that may be helpful:**

**Comment by kinarashah** [comment]
@davidnuzik @sangeethah 
1) When using all caps, this is not allowed as the error message suggested 

2) I am assuming you changed the name to lowercase in the same page, this error happens because, UI isn't sending the whole object this time - 

<img width="469" alt="screen shot 2019-02-20 at 11 03 04 am" src="https://user-images.githubusercontent.com/16870565/53117163-24c97c80-34ff-11e9-9ce9-5a9d2aaa8872.png">

If you go and do this whole thing again and now give lowercase, it will work. 

Also, not sure why it's working for you for EC2, I see the same behavior there too? 
For Vsphere and Azure, UI makes it lowercase even if entered in caps, hence it goes through.

**Comment by davidnuzik** [comment]
@kinarashah 
1. Could have sworn I could do uppercase before without any issues. This seems new.

2. Lowercase does not work. 

Not sure why ec2/others work for me but not you. Perhaps for ec2, etc I used lowercase. When I use lowercase with DO I get the error in the screenshot snippet in your comment above.

**Comment by davidnuzik** [comment]
Update: If you do uppercase FIRST then lowercase second time UI doesn't send whole object to API. So we will just need to fix UI so it never allows upper case in first place.

**Comment by westlywright** [comment]
@davidnuzik and I walked through this at my desk and couldn't reproduce this bug.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/4/19)
Tested again and am not able to reproduce the problem.
Followed the steps and when I create a cloud key with capital letters it's quickly changed to lowercase letters and I have no issues creating the key and any clusters.
