### ISSUE TITLE
When LDAP user is part of many groups (~30) ,it takes a very long time (~20 secs) to get authenticated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1829]
Server version - V0.33.0-rc3

When LDAP user is part of many groups (~30) ,it takes a very long time (~20 secs) to get authenticated.

**Comment by will-chan** [comment]
We should first figure out whether it's the LDAP server taking this long making the query or our code after it returns.

**Comment by hibooboo2** [comment]
@will-chan Looked into it. With ~30 groups it takes about 8 ish seconds to create and return the token from the api. Then the ui starts to load as that user. The total time is about 20 seconds as a result. Right now in order to authenticate to ldap we make a request to ldap for each group the user has. This makes the request time to make a token unknown until completion.

**Comment by vincent99** [comment]
Are the groups loaded in parallel or one at a time serially?

**Comment by hibooboo2** [comment]
Serially right now. Are you suggesting making them load in parallel?

**Comment by sshipway** [comment]
This is affecting us badly as well.  We're using AD LDAP which is generally very fast to respond, but we're getting 30s logins (people can be in 50+ groups here).  After logging in, everything works, but it is annoying when logging in.

Related to this is the amount of time taken to populate the group selector dropdown when configuring Environment permissions.  This is apparently timing out and just showing what it obtained, since we have a vast number of groups and not all of them end up in the dropdown.

It would be helpful to be able to specify an LDAP filter for both users and groups to restrict what needs to be queried.

**Comment by hibooboo2** [comment]
rancher/rancher#1024 should make this much better. Got what was previously 86 seconds down to 2.5 using our test setup.

**Comment by deniseschannon** [comment]
Verified with v0.47.0-rc1. Our test user with many groups is logged in a couple of secs instead of 30 secs.
