### ISSUE TITLE
UI performance optimizations

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#18295]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement request
rancher:v2.1.3

**Steps to reproduce (least amount of steps as possible):**
1. have a large number resources under management (pods, namespaces, clusters, deployments, pods, etc...)

**Result:**
1. Switching between projects is slow.

**Other details that may be helpful:**
Speaking with @cjellick he mentions a couple optimizations to be had:
1. Rearrange the order of the filtering so that we only "get the parent" after we've filtered down to the current project.

2. We already cache the parent result, but its 1 hour. This data is static, so we could increase cache time to, say, 12 hours

**Comment by dbason** [comment]
Hi Ahmad
Number of nodes is 13 compute nodes, 1 control plane node, 3 etcd nodes
Namespaces: 29
Projects: 11
Deployments: 709
Pods: 873

**Comment by ahmadalli** [comment]
One of the reasons is that when you switch to project X it downloads every resources which might take some time. e.g. loading System project took a lot of time because it was downloading 51 Mb of configmaps

![image](https://user-images.githubusercontent.com/2167301/55434407-d05cf680-55ac-11e9-8718-b53e113ec8fd.png)

this behavior could be optimized by downloading the resources when we open them or at least when we open the proper page (e.g. configmaps page)

**Comment by rmweir** [comment]
Hello @ahmadalli, thank you for the details! There is currently a fix pending for that: https://github.com/rancher/rancher/pull/19228

**Comment by sangeethah** [comment]
Following tests have been done using master builds - https://github.com/rancher/rancher/issues/18870#issuecomment-484278427

**Comment by ahmadalli** [comment]
@sangeethah great! is it published on `latest` channel?

**Comment by vincent99** [comment]
@ahmadalli `latest` is the latest release (2.2.2), not what's actually in master.  But most of the various improvements did ship in 2.2.2 AFAIK.

**Comment by ahmadalli** [comment]
I've tested 2.2.2 and I'm still experiencing the issue I've described:
![image](https://user-images.githubusercontent.com/2167301/56860510-9d8bff80-69ac-11e9-84c2-3f3dd42ac419.png)

**Comment by vincent99** [comment]
Configmaps for old app revisions don't get automatically/retroactively cleaned up.  Upgrading the app(s) will trigger it, or the configmaps can be manually deleted from the UI/API/kubectl.

**Comment by deniseschannon** [comment]
There is a fix for cleaning up configmaps that will be in 2.2.3.

**Comment by ahmadalli** [comment]
@vincent99 thanks. I've improved performance by removing older releases of helm packages. But my question is why is rancher loading all the resources without paginating while the ui for configmaps or secrets has pagination?

**Comment by vincent99** [comment]
Kubernetes has a lot of resources and relationships between them, and a database/API with no...features...like joins, searching, sorting, or actual backend support for paging*.  So instead of loading pages of data all the time from the API and doing `n+1` calls to find e.g. what services refer to what workloads, all the major types are loaded once on pageload and all the rest is done in the browser.  And then that is kept up to date with a websocket whenever a resource changes/is created/removed, which also makes everything live update.

This works fine as far as the UI is concerned, and is OK in the backend for the order of a few thousand of a resource (though not great, and we're continuing to work on it).  But not great for tens of thousands, which are beyond the design scale of k8s to begin with (and in this case only exist because of a bug).

*: It exists, but is not really any faster than requesting the whole dataset because the way it's implemented behind the scenes is getting the whole dataset and then throwing the data outside the window you asked for away.
