### ISSUE TITLE
Provide relevant help message regarding etcd snapshot changes when editing cluster after rancher upgrade 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18316]
Rancher version: v2.1.6
Upgraded version: master

Steps:

1. Create a 3 node cluster with all 3 roles in v2.1.6
2. Create few workloads
3. Upgrade rancher from v2.1.6 to master
4. After upgrade, edit the cluster and change any setting(Pod security policy etc) other than the etcd backup snapshots and hit "Save"

The legacy etcd snapshots also get changed to the new local backup.
The user is not informed that changing any of the fields will change the legacy etcd snapshots  to the new local backup

Add proper help that will inform the user of this change . Also, add information that  user can change other fields without changing the snapshot related settings through API or API UI

**Comment by davidnuzik** [comment]
I see this in latest master.
![216do-modified-after1-looksgood](https://user-images.githubusercontent.com/45179589/53534636-fa5a5f00-3abc-11e9-89c8-2bc224c65fcc.png)

It will show appropriate numbers depending on what your last settings were.

**Comment by westlywright** [comment]
@davidnuzik I've moved the warning to a more prominent location as apart of the referenced PR.

**Comment by davidnuzik** [comment]
Version: v2.1.6 -> Master 2.2 (3/5/19) Upgrade
Confirmed issue.
The message is shown and clearly states what changes will happen and your options. The message also shows correct retention duration (mine is custom 71h instead of 72h as pictured below). The message placement makes it hard to miss as it is shown 1) without expanding any sections and 2) on the first page without any scrolling needed unless at very low resolution / browser dimensions.

![image](https://user-images.githubusercontent.com/45179589/53825269-2188b480-3f33-11e9-9989-27b2ed9dcb30.png)

When I view advanced cluster options my Snapshot Creation Period is still correct as well (my previous setting before upgrade). I can successfully save after making a small change to the cluster such as slightly changing node port range. I encounter no issues.
