### ISSUE TITLE
Multiclusterapp UI : Show app states along with id 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#18337]
With the latest changes in rancher/master, each target of multi cluster app now has app state along with appID. It'd be great if UI can display the state as well. 

https://github.com/rancher/rancher/issues/17899

**Comment by westlywright** [comment]
@kinarashah @alena1108 why would we want to include the appId here? It doesn't seem useful like the quick visualization of the state does. If a user needs the appId, it would add up they are doing something more than wanting to see a quick glance and in that case I'm not sure additional info is warranted at this level (it may actually be more confusing) and they would be better served clicking through to the app in the project. Most UI interaction with resources works with the resource name (or display name) only showing the ID when all else fails (as is the case when showing the apps when the user doesn't have access to the project where the app is installed). 

<img width="1333" alt="screenshot 2019-02-25 16 14 13" src="https://user-images.githubusercontent.com/858614/53375431-7a938f80-3918-11e9-96e0-e8fa9e3ef82c.png">

**Comment by kinarashah** [comment]
@westlywright I agree, it makes sense to omit appID since user can always navigate to the app with the projectID and the visualization above is nice enough to see all the required information, thank you!

**Comment by westlywright** [comment]
@kinarashah thanks for the quick feedback! I'll have the feature in soon.

**Comment by davidnuzik** [comment]
App states are now shown. When we are updating (deploying) we see "Deploying" In UI in mouseover.
![image](https://user-images.githubusercontent.com/45179589/53435679-96e60980-39b6-11e9-84cd-7df186e3b9c0.png)

It's not easy to see that anything is there though it's the same color as the background and the text is too dark as pictured above.
@westlywright can we fix this ^^

Further testing on hold due to #18409 blocker (app won't come up)

**Comment by davidnuzik** [comment]
@westlywright I created a separate bug to track this issue. #18447

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/27/19)
Confirmed issue. I can see app states as they are deployed. These appear to be in sync with watching the individual apps in separate windows while the app goes from "installing" state to "deploying" state to "active" state.

Installing/deploying looks like this below. Issue #18447 was entered because we cannot see the circles and text is dark but it works fine:
![image](https://user-images.githubusercontent.com/45179589/53435679-96e60980-39b6-11e9-84cd-7df186e3b9c0.png)

Once active it looks like this:
![image](https://user-images.githubusercontent.com/45179589/53506330-01f51600-3a73-11e9-9c53-f663e43602dc.png)

I smoke tested this area and could not identify any issues.
