### ISSUE TITLE
Change button text from "Test" to "Dry Run" for advance mode logging target 

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#18364]
Version: v2.2.0-rc2
For advance mode logging, after user use ```edit as file``` then user could input the raw fluentd config, then click the "Test" to validate the config file, in advance mode, we will use fluentd command dry-run to validate the generated config file, for ```edit as form``` will send a log to the target, the action is different, so we better change the ```Test``` to ```Dry Run``` to make sure not confuse user

**Comment by davidnuzik** [comment]
Version: Master 2.2 (2/25/19)
Confirmed issue. When using advanced "Edit as File" option for logging the button is now "Dry Run" rather than Test. When switching back to "Edit as Form" it goes back to "Test". 
![image](https://user-images.githubusercontent.com/45179589/53365804-5aa3a200-38ff-11e9-9dd3-916e55627ddc.png)

While running you will see "RUNNING" with html spinner to let you know it is in progress.
![image](https://user-images.githubusercontent.com/45179589/53365818-6000ec80-38ff-11e9-8cfb-417eea5f69cc.png)

When it fails you will get a message in the UI describing what went wrong:
![image](https://user-images.githubusercontent.com/45179589/53365835-6becae80-38ff-11e9-8f39-8db9b1574902.png)

**Comment by davidnuzik** [comment]
I did notice if I use a config that does not use fluentd it still says Dry Run. Is this expected @n313893254 / @aiwantaozi ? Or do I just misunderstand and fluentd is used anyway in this case?

![image](https://user-images.githubusercontent.com/45179589/53365944-ae15f000-38ff-11e9-8ded-2960073573ac.png)
![image](https://user-images.githubusercontent.com/45179589/53365963-b66e2b00-38ff-11e9-82d9-507eaebcb97d.png)

**Comment by davidnuzik** [comment]
Re-open to get input.

**Comment by n313893254** [comment]
@davidnuzik It is an expected result. For customTargrt, using `dryRun` action to validate settings. For other target, using `test` action to validate settings. 

The type (e.g. elasticsearch) belongs to customTarget. It will use Fluentd command dry-run to validate the generated config file.

**Comment by davidnuzik** [comment]
Thanks @n313893254 I just wanted to be certain. I appreciate the information.

**Comment by davidnuzik** [comment]
Closing per my comment above https://github.com/rancher/rancher/issues/18364#issuecomment-467166358
This is working as expected.

**Comment by davidnuzik** [comment]
FYI entered related issue, #18405 regarding issue I saw while testing. If not having some logging properly configured such as elasticsearch the fluentd-tester will never timeout and Dry Run button stays in "Running" state forever.
