### ISSUE TITLE
Enabling ADFS (SAML auth) in HA setup occasionally results in “404 Not Found” error .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18380]
Rancher server version - Build from master

Set up - HA setup
Steps to reproduce the problem:
Enable  ADFS (SAML auth).
Enter valid credentials when prompted.

After this user is directed to ```https://<rancher server>/v1-saml/adfs/saml/acs``` which results in "404 Page not found" .

Note - This issue does not happen all the time. When  this issue is encountered , if we try to enable ADFS again it would succeed.

**Comment by alena1108** [comment]
Moving out as the issue is intermittent and happens only when enabling/disabling providers.

**Comment by davidnuzik** [comment]
reproduced in v2.1.8

**Comment by davidnuzik** [comment]
reproduced in v2.2.1

**Comment by janeczku** [comment]
Reproduced with Ping authentication provider on v2.1.8. The 404 is intermittent and works upon retrying.

**Comment by janeczku** [comment]
Reported to occur in v2.2.2 also.

**Comment by eest** [comment]
Hello,

I have experienced what might be a related issue. I am setting up rancher 2.5.3 on top of a single-node k3s v1.19.4+k3s1 cluster and trying to enable Shibboleth auth. After entering the required shibboleth fields (ignoring LDAP settings) and clicking the `Authenticate with Shibboleth` button I see a shibboleth authconfig object appearing in the system:
`kubectl get authconfigs shibboleth -o yaml`
```
accessMode: unrestricted
allowedPrincipalIds: []
apiVersion: management.cattle.io/v3
enabled: false
[...]
kind: AuthConfig
metadata:
  creationTimestamp: "2020-12-14T12:39:06Z"
  generation: 11
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: management.cattle.io/v3
[...]
```

The reason `enabled` is set to false is probably because I have not yet gone through with the remaining IDP-setup dance yet. At this point I expect to be able to fetch the generated SP metadata so I can add it to the IDP:
```
curl -s https://rancher-url.example.com:<port>/v1-saml/shibboleth/saml/metadata
```

Here I notice that 1/3 requests I get a metadata response, the other 2/3 times I get a `404 page not found` result. This seems to coincide nicely with me having 3 rancher pods running in the cattle-system namespace:
```
# kubectl get pods -n cattle-system
NAME                               READY   STATUS    RESTARTS   AGE
rancher-webhook-698dd9dc76-jbczx   1/1     Running   1          160m
rancher-6585c886b-jvnpg            1/1     Running   1          151m
rancher-6585c886b-jb9rs            1/1     Running   1          150m
rancher-6585c886b-nnb9w            1/1     Running   1          152m
```

After digging around some in the code I might have figured out why this is. From what I can tell, the function responsible for configuring/enabling the SAML endpoints is `InitializeSamlServiceProvider()` from here: https://github.com/rancher/rancher/blob/master/pkg/auth/providers/saml/saml_client.go#L46

This function is called in two places, here as part of a controller loop sync() function: https://github.com/rancher/rancher/blob/master/pkg/controllers/managementapi/samlconfig/samlconfig.go#L81

... and also in the testAndEnable() function here:
https://github.com/rancher/rancher/blob/master/pkg/auth/providers/saml/saml_actions.go#L50

What I think is happening is this: when you click the "Authenticate with Shibboleth" button you will end up calling the 
`testAndEnable()` function in the pod that happens to handle the request, which makes it temporarily serve the SAML endpoints. This does not affect the pods that did not handle the request, and this would be the reason I see a 1/3 success rate on the requests. This would also be the reason for the issues in the earlier posts which see `404` responses for some requests.

Since the AuthConfig object is actually added to the database I was expecting the controller loop in the other pods to react to this, but I think the reason they do not is because the `sync()` function checks for the object to have the `enabled` field set to true, otherwise it does nothing:
https://github.com/rancher/rancher/blob/master/pkg/controllers/managementapi/samlconfig/samlconfig.go#L47
```
if !config.Enabled {
	return nil, nil
}
```

... and as is visible above, the data sent from the UI sets this field to false.

I guess it is written this way so a disabled provider will not have its endpoints available for requests, but it becomes a bit tricky when you expect the endpoints to be available during a setup phase of the provider.

I am not sure how to properly solve this is so it works correctly when multiple replicas are running. Maby instead of enabling the endpoints in the pod that happaned to handle the UI request, the AuthConfig data sent by the UI should include some "setup" or "test" field which is set to true, and when this is added to the database the controller loop in all replicas will be able to pick it up.

The main problem with this is how to handle the field if the setup is aborted before it is completed. If someone decides to cancel the setup it would require clearing the new field so the pods does not expose the endpoints forever.
