### ISSUE TITLE
imagePullSecrets gone after upgrading image version

### ISSUE THREAD

**Issue by JerryCurl** [rancher/rancher#18408]
Seems like this was previously reported and closed, but its happening in 2.2.0-rc2.  I have imagePullSecrets set on a deployment.  If i use the form in the GUI to update the image to a newer version/tag, imagePullSecrets is removed from the deployment, and the upgrade fails (can't pull).

I can edit YAML, add imagePullSecrets back in, and all is well again until the next update. Update version again and problem repeats.

If I edit the deployment YAML (through the web gui) and change the image tag there, all is well. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc2` UI: `v2.2.3` |
|Route|`workload`|

**Comment by loganhz** [comment]
Thanks for the report. I can not reproduce this issue. Can you try again in `v2.2.0-rc3`, please?

**Comment by JerryCurl** [comment]
i went back to 2.1.7, same issue.  Also happens when cloning a deployment.

**Comment by pengjiang80** [comment]
@loganhz what we saw in an environment today is:
1. Create two image secrets for two different registries.
2. Use image from registry 01 to create a deployment.
3. Upgrade the deployment and change the image to registry 02.
4. The imagepullsecret setting was lost and not switched to secret02, which caused upgrade failure.

The version is v2.1.7. Not sure if there is the same issue in v2.2.4. We will try and feedback.

@satomic

**Comment by satomic** [comment]
@loganhz I had done some test with `v2.3.0-alpha5` version in `demo.cnrancher.com` env. here is some test description & results.

## Harbor Configuration
- privision a Harbor registry, root URL is `118.190.53.189`
- create 2 users in Harbor with name `test1` & `test2`
- create 2 projects for the 2 users seperately, all are **private projects**
- push `nginx` to the 2 Harbor projects, tagged with `118.190.53.189/test1/nginx` &  `118.190.53.189/test2/nginx`

##  Test in Rancher

### testcase1: deploy workload before add Registry Credentials
- deploy an workload `nginx` with image `118.190.53.189/test1/nginx` before add the `test1` credential, so there will always be a `ImagePullBackOff` error
- then add the `test1` credential to current rancher project with all namespaces scrope
- **then I tried (1) delete pod, recreate pod again (2) edit workload than save (3) redeploy the workload, but all way is a bad way, always `ImagePullBackOff` , and I checked the yaml of the workload, the `imagePullSecret` was not updated to it, so I am wandering if this is a bug or not.**
- at the last, I add the `imagePullSecrets` segment to the yaml file by hand, image was pulled success fianlly.
```
      imagePullSecrets:
      - name: test1
```

### testcase2: based on testcase1, change the image URL
- add  `test2` credential to current Rancher project (so ideally, we can pull the image from `test2` Harbor private project in the Rancher from now on)
- edit the workload docker image from `118.190.53.189/test1/nginx` to `118.190.53.189/test2/nginx`, save it
- and the new image had been pulled successfully
- check the yaml file , we cans see the `imagePullSecrets` segment contains all registry credentials.
```
      imagePullSecrets:
      - name: test1
      - name: test2
```

### testcase3: change image with different root URL
- deploy workload `nginx` with image `nginx`, check yaml there is no `imagePullSecrets` configured
- edit workload `nginx`, change image to `118.190.53.189/test2/nginx`, updated success, check yaml `imagePullSecrets` segment is
```
      imagePullSecrets:
      - name: test1
      - name: test2
```

## summary
based on the testcase2 & 3, maybe this main issue had been fixed I think. so my question is
- if the testcase1 situation is a bug or not? maybe the version `2.2.4` will have the same problem

**Comment by satomic** [comment]
and I tried the version `v2.2.4` too, with the 3 testcases, the test results are just same as the version `v2.3.0-alpha5`. @pengjiang80 @loganhz

**Comment by thecodeassassin** [comment]
Got the same issue on v2.2.3. Deployed via kubectl apply -f deployment.yaml.
```
imagePullSecrets:
- name: artifactory
```

Maybe good to note that I have one imagePullSecret

**Comment by thecodeassassin** [comment]
This also seems to happen when you clone a deployment.

**Comment by vincent99** [comment]
The UI does not do anything at all with imagePullSecrets.  If they are present in the object, they are preserved and sent back on edit/clone.

On **creation** of a workload, the API finds a suitable pull secret for the given image and adds it to the workload.  I do not know that it continuously updates this if the image or pull secrets are changed after the fact, but I think your problems are with this and have nothing to do with the UI specifically.

**Comment by JerryCurl** [comment]
Not in my experience. If they are present, they are dropped on edit/clone. No longer exist in the yaml

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by thecodeassassin** [comment]
> The UI does not do anything at all with imagePullSecrets. If they are present in the object, they are preserved and sent back on edit/clone.
> 
> On **creation** of a workload, the API finds a suitable pull secret for the given image and adds it to the workload. I do not know that it continuously updates this if the image or pull secrets are changed after the fact, but I think your problems are with this and have nothing to do with the UI specifically.

Not sure if it's the UI or the API but something sure removes the imagePullSecrets from the yaml. It happens constantly. Of all the bugs, this is the most annoying one since I have to keep adding the ImagePullSecrets.

**Comment by loganhz** [comment]
Still cannot reproduce it with repro steps in the comments in 2.2.4

**Comment by D3473R** [comment]
The issue is still occurring for me in `v2.2.5` when i'm changing the docker image tag of a deployed workload.

**Comment by leodotcloud** [comment]
I am not able to reproduce this issue either using v2.1.7 or v2.2.4. 
@pengjiang80 I tried your scenario too, doesn't repro.

@JerryCurl, @D3473R, @thecodeassassin if you can provide steps to reproduce, we would be more than happy to dig into this further. At this point, based on all the info available in the issue, the problem is not reproducible at our end. 

<img width="1677" alt="Screen Shot 2019-08-20 at 1 08 37 PM" src="https://user-images.githubusercontent.com/19392926/63381720-1cd38380-c34e-11e9-812d-dcbbdb51e05a.png">
<img width="1678" alt="Screen Shot 2019-08-20 at 1 08 48 PM" src="https://user-images.githubusercontent.com/19392926/63381721-1cd38380-c34e-11e9-92bf-2a9ebb5eb1ce.png">
<img width="1680" alt="Screen Shot 2019-08-20 at 1 08 59 PM" src="https://user-images.githubusercontent.com/19392926/63381722-1cd38380-c34e-11e9-9061-9d05e9d931e8.png">
<img width="1677" alt="Screen Shot 2019-08-20 at 1 25 33 PM" src="https://user-images.githubusercontent.com/19392926/63381724-1d6c1a00-c34e-11e9-9423-460e89cf984c.png">

**Comment by leodotcloud** [comment]
@sangeethah can you please look into this as well?

**Comment by JerryCurl** [comment]
I am on 2.2.7 now, still happens.  Here are exact steps:

1) deployment running as normal - see ImagePullSecrests in the yaml (pic
#1.png)
2) use the GUI to change the image tag (pic 2.png and 3.png)
3) upgrade fails with errors that registry is hosed (image 4.png)
4) imagePullSecrets no longer exists in YAML (image 5.png)

**Comment by leodotcloud** [comment]
@JerryCurl I do not see any of your screenshots. Can you please check?

**Comment by thecodeassassin** [comment]
I can provide a video reproducing the issue. I'll make it asap and post it here.

**Comment by thecodeassassin** [comment]
@leodotcloud Please check this video I made: 
https://www.youtube.com/watch?v=_0CqqNScmiU

Steps:

Method 1
1) Clone existing deployment that has imagepullsecrets
2) new deployment lacks imagePullSecrets

Method 2
1) Change the image version of an existing deployment
2) the deployment's imagePullSecrets are gone

**Comment by leodotcloud** [comment]
@thecodeassassin Please ping me on https://slack.rancher.io, I would like to do a screen share and debug further as it's not reproducible on our end.

**Comment by thecodeassassin** [comment]
Conclusion after testing with @leodotcloud 

When your image pull secrets aren't created via the rancher ui / API directory. But for example via import yaml or direct kubectl apply commands (which was how we did it). The result is that the imported secret works fine, but when you clone the deployment or change the version it removes the imagePullSecrets. I assume it's because there are essential tags missing.

The missing tags are:

```
"labels": {
"cattle.io/creator": "norman"
},

"creatorId": "u-a666jbgqgb",

```

Not entirely sure if this is directly what is causing it but that was the only noticeable difference between the secret that was created via the UI and one that was created via Import Yaml.

**Comment by leodotcloud** [comment]
Registry credentials created using the UI have the type: dockerCredential, whereas the ones created using `kubectl` have the type: namespacedDockerCredential. The registry domain/host is stored without the prefix "http" or "https" when created using the UI. The logic in the code missed to capture this, hence the problem, will be fixing the source code.

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher:v2.2.8

Step:
- add a docker registry secret from kubectl, it is a private registry in docker hub 
- deploy a workload with an image from the private registry using the secret    
- see the workload is active in Rancher UI
- clone the workload in Rancher UI

Results:
- the clone is failed to be active 
- the clone cannot pull the image from the private registry 
- view its yaml file to see that the deployment's imagePullSecrets are gone

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:master-head a98b70f17

Following the same testing steps, now the cloned workload works as expected.

**Comment by Serrvosky** [comment]
Hello @jiaqiluo, @leodotcloud .
I'm using Rancher v2.3.4, and I'm facing the same problem that is describe in this issue.

I used kubectl to apply my private registry secret, then deployed my workload with Terraform tool and everything works perfect, but when I change image version, imagePullSecrets tag is removed from the YAML. Then I have to edit the file, to add that entry manually, then workload updates successfully.
 
Can you please check if this error is happening again?

Thanks :)

**Comment by theAkito** [comment]
Struggling with this issue since a couple of Rancher versions.
Current versions:
<html><body>


Component | Version
-- | --
Rancher | v2.5.7
User Interface | v2.5.6
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher52


</body>
</html>

This only happens 90% of the time with deployments on independent k3s clusters imported into Rancher. RKE clusters do not have this issue.
