### ISSUE TITLE
Project edit view has missing name of AzureAD group added to it

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#18425]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
add a azure ad group to rancher via edit project. save changes. might require a refresh of the pane but the group name is no longer visible.

**Other details that may be helpful:**
hit this with rancher/rancher:v2.1.6 HA

credit to @bluemalkin for finding the issue

**Comment by bluemalkin** [comment]
I'm still seeing this issue in v2.2.0

**Comment by westlywright** [comment]
@bluemalkin @aemneina could you provide a bit more info? I am unable to repro in 2.2. Where is the name missing from? Is it on the members page after edit project? or are you selecting edit again? Is it only after the page refresh that the name is no longer present? Are there any js console or network errors? 

When editing a project we fetch the members user model based on the existing PRTB's because the PRTB only contains the principal id of the user (or group) and we need the readable info off the user model. Perhaps the call is failing? We should fallback to displaying the principal id in that case, but I can't repro and I don't see any glaring issues when grok'ing the code.

**Comment by bluemalkin** [comment]
@westlywright the issue happens only when I edit a Project (e.g. /c/c-fq6k6/projects-namespaces/project/c-fq6k6:p-zg2z6)

If I'm already inside a Project and go to Members via the top bar menu, there is no issue (e.g. /p/c-fq6k6:p-zg2z6/security/members). So really something which works here isn't replicated to edit Project members.

**Comment by westlywright** [comment]
Available in master and ui tag `2.2.31`

**Comment by davidnuzik** [comment]
Note, this was already validated in #19307 against v2.2.2-rc1 and confirmed working. We may want to test again for v2.3 in this issue.

**Comment by davidnuzik** [comment]
Version: Master (4/11/19) ImageID: 0d755e769e77

This was tested in master again to validate for  v2.3 and is confirmed working. The group name now shows up upon the second edit.

**Comment by bluemalkin** [comment]
Confirming fixed in v2.2.2 👍

**Comment by davidnuzik** [comment]
👍Thanks. FYI #19307 is for v2.2.2
