### ISSUE TITLE
pipeline - Failed to load pipeline history execution logs after upgrade

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#18475]
**environment:** single install and HA
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Start rancher v2.1.7-rc4
2. Enable GitHub or Gitlab
3. Enable some repositories
3. Edit pipeline configuration and run pipeline
4. Upgrade rancher to v2.2.0-rc2
5. View pipeline history execution logs

**Result:**
Execution logs fail to load.  display:  `Log is unavailable. `
Upgrade and downgrade all have this problem.
<img width="1305" alt="upgrade logs" src="https://user-images.githubusercontent.com/42061003/53558329-c8133500-3b82-11e9-86b8-fd2434776968.png">

**Other details that may be helpful:**
Re-run the pipeline, the execution logs is loaded normally.

**Comment by gitlawr** [comment]
The minio deployment's spec is updated to have resources configs. On rancher upgrade, the pipeline components will be automatically updated to the new specs.
Because the minio uses ephemeral storage to keep execution logs by default, the data is gone during the upgrade.
If users want the build logs to be persistent, they need to configure pv for minio as described in pipeline docs: https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/#4-configuring-persistent-data-for-pipeline-components

**Comment by gitlawr** [comment]
@rootwuj Can you confirm if the logs show as expected if PV for minio is configured before the upgrade

**Comment by rootwuj** [comment]
@gitlawr 
 I followed the [docs](https://rancher.com/docs/rancher/v2.x/en/tools/pipelines/configurations/#4-configuring-persistent-data-for-pipeline-components) to mount the `docker-registry` and `minio ` storage (longhorn I used).
Run the pipeline to generate some execution logs.
Upgrade to 2.2.
View the execution logs of the pipeline, still no log.

Because the pipeline detached the PVC after the upgrade. If you remount the PVC, you can see the log.

The `nginx` workload I deployed in the default namespace also mount PVC. After updating the rancher, the PVC is not detached. I think this may be a problem with the pipeline. Please help me confirm.

**Comment by gitlawr** [comment]
Component upgrade overrides persistency configurations as well. We should avoid that

**Comment by rootwuj** [comment]
Version: master 2.2 (3/5/19) Image ID: 62b73e8b4ba8
Confirmed fixed.
