### ISSUE TITLE
Public port is not being configured for networkMode=bridge

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1847]
When networkMode=bridge is specified for the container, its public port is not being configured on the host.

**Comment by sangeethah** [comment]
Tested with server version - v0.34.0-rc3
Created a container with port 80->7771 and 81->8881 with container in bridge mode:

"ports": [ 2 items
"80:7771/tcp",
"81:8881/tcp",
],

Container has ports 7771  and 8881 exposed , but they are mapped to 80 and 81.
f1222e8e2802 - was deployed from rancher server

de470958ab46 - was deployed using docker run command using following command:
 docker run -d -p 80:6666 sangeetha/testnewhostrouting

```
de470958ab46        sangeetha/testnewhostrouting          "/scripts/run.sh ngin"   7 minutes ago       Up 7 minutes        80-81/tcp, 443/tcp, 0.0.0.0:80->6666/tcp       hopeful_pare
f1222e8e2802        sangeetha/testnewhostrouting:latest   "/scripts/run.sh ngin"   13 minutes ago      Up 13 minutes       80-81/tcp, 443/tcp, 7771/tcp, 8881/tcp         92f47de2-e769-426d-93ed-ceb16590deff
```

Reopening this issue , since we expect the ports to be mapped.

**Comment by alena1108** [comment]
python-agent with this change hasn't been released yet; the change exists in python-agent master branch only. I'll update this bug once its released and ready to test. Want to keep status "to-test" to indicate that the fix has been checked in.

**Comment by alena1108** [comment]
Ok, python-agent 0.47 has been released, and you can test it on the latest now.

**Comment by sangeethah** [comment]
Tested with server version - v0.34.0-rc4
Created a container with port 80->1234 and 81->1235 with container in bridge mode:

The public ports are mapped as expected

```
e7016cb04b4a        sangeetha/testnewhostrouting:latest   "/scripts/run.sh ngin"   30 seconds ago      Up 29 seconds       443/tcp, 0.0.0.0:1234->80/tcp, 0.0.0.0:1235->81/tcp   a20e2293-31f4-4ddc-9bc9-d78a3323079f
```
