### ISSUE TITLE
SAML authentication fails when IdP Metadata contains multiple signing certificates

### ISSUE THREAD

**Issue by fsanys** [rancher/rancher#18471]
**What kind of request is this (question/bug/enhancement/feature request):** question

**Steps to reproduce (least amount of steps as possible):** 
-- ADFS connectivity --

**Result:**
Version of ADFS:  10.0.14393.2515
Rancher version: v2.1.6

While connecting to AD FS we have this error message from Rancher: Forbidden Access.

In the debug logs of rancher, we can see these logs in the debug logs of rancher:
samlp:Response ID="_bfbff4bd-759b ... 
ERROR: cannot validate signature on Response: Could not verify certificate against trusted certs

We have followed the documentation to setup AD FS with Rancher and tried few things related to the certificate like self-signed certificate as mentionned in the documentation or our wildcard certificate but we always have this error message.

There are no relevant logs in ADFS server after enabling DEBUG logs.

Any ideas/tips about this?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
- Installation option (single install/HA): single install

gz#13003

**Comment by niroz89** [comment]
Facing the same issue. 
Rancher version : v2.3.5

**Comment by ArronD** [comment]
We have the same problem. @fsanys Have you solved it?

**Comment by fsanys** [comment]
Sorry @ArronD, we couldn't figured it out.

**Comment by nickngch** [comment]
Does the ADFS server have more than one signing certificate? Remove additional/old certificate in the metadata.xml if the ADFS has more than one certificate.

**Comment by xeiss** [comment]
I had the same problem and @nickngch solution fixed it for me. But I think this is just an workaround, because with that problem no smooth migration to the new ADFS signing certificate (happens every year) is possible.

**Comment by janeczku** [comment]
This also breaks authentication with Shibboleth IdPs that have been configured with multiple signing certificates (typical use cases include federation or certificate rollover).

**Steps to reproduce:**
1. Setup a Shibboleth IDP with multiple signing certificates in the metadata XML. See [here](https://devidp3.srv.lrz.de/idp/shibboleth) for an example.
2. Setup authentication in Rancher
3. Test authentication

**Result:**

> ERROR: cannot validate signature on Response: Could not verify certificate against trusted certs

Removing the certificates from the Metadata is not an option,  since they are required for the SAML client to verify the signature of the federated assertions.

**Comment by janeczku** [comment]
It looks like this was already fixed upstream and so we only need to update the vendored SAML library in order to resolve the issue in Rancher: https://github.com/crewjam/saml/pull/193

**Comment by asemen2608** [comment]
On a customer site, ADFS Stopped working with SAML authentication after the automatic time change from summertime MESZ (UTC+2) to MEZ (UTC+1) on Sunday 25th, October 2020.

**Comment by deniseschannon** [comment]
Completing this task https://github.com/rancher/rancher/issues/30291 should automatically fix this issue

**Comment by paynejacob** [comment]
This pr https://github.com/rancher/rancher/pull/30858 switches us to the library we forked from originally.  This pr https://github.com/crewjam/saml/pull/193 adds support for multiple certificates in the upstream library.  @fsanys @niroz89 @ArronD  Would you be able to test with https://github.com/rancher/rancher/releases/tag/v2.5.6-rc4 to see if the issues is resolved?  We do not currently have a saml provider setup with this scenario and it may take some time before we can test for this case.

**Comment by sowmyav27** [comment]
@Jono-SUSE-Rancher is there an update on this issue after https://github.com/rancher/rancher/issues/18471#issuecomment-772037676 ?

**Comment by Jono-SUSE-Rancher** [comment]
Hi @sowmyav27 - I have not heard anything at this time, so without feedback we may need to investigate the effort needed to set up a saml provider to test this with.

**Comment by deniseschannon** [comment]
The updates in the SAML library will be available for this issue in v2.5.6, but we don't have a valid setup to verify that the SAML changes corrects this. We will keep this until v2.5.7 to see if anyone from the community can help validate it.

**Comment by nikkelma** [comment]
Rancher server v2.5.7 is experiencing the same issues - happy to implement any workarounds or test with RCs as appropriate.

**Comment by sowmyav27** [comment]
Reopening based on this - https://github.com/rancher/rancher/issues/18471#issuecomment-807800549

**Comment by eest** [comment]
I have run into this error when trying to set up Shibboleth auth, in our case I think it might be a result of our IDP metadata not containing "use" attributes which makes crewjam/saml stop at the first available cert instead of returning the full list (which in our case started with a now deprecated cert from a rollover), see my ticket there for the full details: https://github.com/crewjam/saml/issues/352

Relevant for people still having problems might be to verify if their rancher-uploaded IDP metadata has a similar problem.

**Comment by samjustus** [comment]
@sowmyav27 what info does QA need?
