### ISSUE TITLE
Allow ability to allow users/groups for access control in LDAP (at the site level, not environment level)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1850]
With GitHub authentication, you are able to allow access control to specific users/organizations.

In LDAP, there is no ability to allow to certain LDAP users/groups as there is no API field for it.

**Comment by kaos** [comment]
This would be a remaining issue from what was described in #688 but not yet implemented (added this comment for the side effect of getting a cross ref I was expecting but didn't find).

**Comment by cjellick** [comment]
@kaos We're looking for user feedback on this feature. Exactly how would expect/want it to behave?  This feature is to lock Rancher access down to a specific subset of LDAP users. Would your organization do that based on groups, specific users, OUs, or some other LDAP construct?

**Comment by kaos** [comment]
We use groups for that. OUs are fine too. I'm no LDAP expert, my experience only goes as far as locking down sites for ldap auth using apache, looking that a authenticated user is a member of a certain group. And in apache, I'm used to specifying a LDAP path with OUs and DCs to identify the desired group.

But we'd certainly want the possibility to specify at least one group per environment. It would make life easier if we could use arbitrary number of groups per environment.

**Comment by vincent99** [comment]
@kaos You can add multiple groups (and users) to environments today to control who can work with each environment.

This issue is to address that currently *any* user in LDAP can login, but you may want to allow only the "Developers" or "Ops" groups in your tree in.  This would prevent say "customer support" or "pointy haired bosses" from logging in and creating their own environments.

**Comment by kaos** [comment]
@vincent99 Ah, cool. Will have to look closer at that tomorrow. I just got the 0.34.0 version installed on Friday afternoon, and the LDAP auth configured like 15 minutes before leaving for the weekend.. ;)

**Comment by kaos** [comment]
@vincent99 ok, so the groups/users per environment looks good. My only remaining question now is: who's the overall admin for the rancher server instance? With access to setup/disable ldap auth etc. Stuff that isn't directly tied to a specific environment.

**Comment by kaos** [comment]
@cjellick ok, so we've done some poking around, and find that the current implementation for users/groups on the environment level is good enough for us (not missing any features there).

We also don't require the upcoming feature to lock down the ability to login and access the rancher server on a per user/group level. We don't mind any user to login, as they don't get any further access that hasn't been explicitly assigned.

What I do miss in its current form though, is to manage the admins of rancher server instance itself, i.e. at the "top level" (same as my previous comment for vincent). Right now, I'm guessing that this is hardwired to the account used when enabling LDAP auth. This would need to be addressed, so that we can assign admin roles to users/groups.

**Comment by vincent99** [comment]
Yes, the user who turns on access control becomes the admin user (ID 1a1).  That part won't change, but there is internal support for multiple admins so it is not hard wired per-se.  There no way to manage/promote/demote them in the UI today though.

There will need to be a screen to CRUD users for the upcoming local authentication, so that will likely include managing the admin bit too (and support GitHub/LDAP).

**Comment by kaos** [comment]
Ah, I see, that makes sense. Looking forward to that. Not a show stopper, so we keep working with what we have thus far :)

**Comment by hibooboo2** [comment]
@kaos It is possible with the current ui to make a user an admin for rancher, on the accounts screen on the admin page. 
![image](https://cloud.githubusercontent.com/assets/1197823/10404146/a18964ea-6e85-11e5-99ec-f09aac57ba62.png)

**Comment by deniseschannon** [comment]
Closing as this has been already been enabled in v1.1.0
