### ISSUE TITLE
Admin sees extra types at /v1 that don't work

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1852]
The user who happens to be admin, or everybody if auth is off, sees all sorts of extra types at the root of the API (e.g. `registrationTokens`, `containers`) that appear to do things but don't really work because they are resources that can only belong to a environment (`/v1/project`).

The root `/v1` level of API should contain only types that are relevant for a user, even if the user is admin.

If we want to add the behavior that admin has a way to see a collection of e.g. all containers across projects, I propose that goes into a separate namespace like `/v1/admin/containers` vs a bunch of resources at the top level for admin.

**Comment by sangeethah** [comment]
I was allowed to add a container using /v1/containers using user api keys which really did not succeed because of placement error since it was trying to add container with its own ID and not the account Id of the project it belonged to. Should API throw an error in this case , rather than allowing the container to be deployed ?

**Comment by vincent99** [comment]
Yes, that is one example.. a user cannot own hosts so there is nowhere to run it.
