### ISSUE TITLE
Can't edit environment name and description

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#1856]
When I try to modify the name of an existent environment it will not save.
Component	Version
Rancher	v0.32.0
Cattle	v0.75.0
User Interface	v0.40.0
Rancher Compose	beta/latest

**Comment by deniseschannon** [comment]
@silviupanaite This is most likely a duplicate of https://github.com/rancher/rancher/issues/1590. 

Can you try clicking on the Environment name and Edit from the detailed environment name? There is a UI bug that will be fixed in the next release where editing from the "Manage Environments" page is broken.

**Comment by silviupanaite** [comment]
Yes it is. Thank you

**Comment by deniseschannon** [comment]
@silviupanaite This was fixed in v0.34.0. Please let me know when you test out that version if it's still an issue.

**Comment by silviupanaite** [comment]
It is fixed.
