### ISSUE TITLE
extend rancher ui (new tab)

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1860]
Hi there,
is there way (or is in consideration) to add a new tab (like an add on/service) to rancher ui?
~ without hacking, extending rancher ui source itself.

Would be nice to keep administration of services/clusters in one place.

**Comment by ibuildthecloud** [comment]
This sounds like a great idea.  I'm know nothing about the front end so I'll defer to @vincent99 for the technical details.  Couple questions though.  Do you really just want a link to pop up somehow?  Imagine if a tab appear because you deployed a stack that had some metadata that say it provides some admin page.  When you click on the tab what would you expect to happen?  Would the navigation at the top of the page stay the same or would the whole page change.  Do you expect our authentication to front the web page or not?

**Comment by fentas** [comment]
What I imagine is that rancher ui stays the same. Authentication etc. should work as usual. If you in your workspace/enviroment there should be some kind of "+" tab besides of "Infrastructure". If click on it a kind of modal dialog should appear in which you can select some sort of source. (In future there could be a repository of addons/service to fast install). Now the question of integration. I am not that fluent in ember but i could imagine that there is a possibility to containing the source of an addon/service within a single package. Meaning that components have the same style applied as the ui itself. The use of services gives the necessary control to stuff.

**Comment by kaos** [comment]
+1 :)
Having the ability to extend the UI by deploying a container would be super :)

**Comment by faddat** [comment]
This is one of the directions that I considered taking with the klouds.io UI (only one single challenge left to hurdle till release)

<3 +1

**Comment by vincent99** [comment]
I don't think dynamically loading extra modules is terribly practical but hers an example of making an addi-in that adds UI for a custom docker-machine driver.  PRs accepted for adding any hooks you need to integrate other areas, like adding arbitrary new routes or top-nav tabs,

https://github.com/rancher/ui-example-addon-machine
