### ISSUE TITLE
Rancher 2.2.x cannot remove notify if there is only one

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#18616]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
create 1 notify
add notify to one of alert rule group

**Result:**
Cannot delete notify if there is only one

One notify, delete option disabled
![image](https://user-images.githubusercontent.com/15118220/53860148-2719f380-4034-11e9-85b9-0f23f9e0aaaf.png)

Add 2nd empty notify and delete first one cannot save
![image](https://user-images.githubusercontent.com/15118220/53860181-4284fe80-4034-11e9-9564-a4875e9ddfb0.png)

![image](https://user-images.githubusercontent.com/15118220/53860200-516bb100-4034-11e9-8af9-c4d99a7b272c.png)

**Comment by davidnuzik** [comment]
You can also see this if you just try to edit one of the default alert groups we include. 1) Notifiers should never be required/mandatory. If a user wants they can just see alerts firing in the Alerts view if they so wish (no notifications). 2) We should be able to remove all notifiers and if none exist have a button to add one.

Here's an example. I just edited one of the default alert groups we have at the cluster level after install, "A set of alerts for etcd" when I edit I cannot remove the one (blank) entry for notifiers but why? And if you follow the steps to reproduce you can also run into a case where you must supply one even though this is not required.

Pictured shows that the "minus" button remove the notifier is grayed out.
![image](https://user-images.githubusercontent.com/45179589/54939428-cfa9cd80-4ee5-11e9-8f6d-faef6d268e7f.png)

**Comment by aiwantaozi** [comment]
In order to make it simple and easy to use, alert don't have a switch like enable/disable, when user configure an alert which has a validate notifier the alertmanager get deployed, the status mute/firing is from the alertmanager.  We will update to allow empty notifier, need to notice when none of alerts has notifiers, the alertmanager won't get deployed, and the status wouldn't change.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/6/19)

I can now delete the single notifier in my alert group without any issues.
When I do this I no longer get notifications as expected but the rule keeps firing in the UI, again as expected. In the logs I see removal of monitoring-operator since I only had one group with notifications. I can add the notifier again and will successfully get alerts (notifications) again (it deploys again).

I also tested another scenario, I set up two groups one with a notifier and the second also with a notifier. I set them up so they are both always firing on a quick interval (30 seconds). I deleted my only notifier on one of the two groups and confirmed in logs we do _not_ remove monitoring-operating in this case (since we still need it for my second group that is getting notifications). This is good.

I made sure that I still do not get notifications for that group I removed the notifier from (sometimes 1 more alert can be cached but after that no more alerts). Last, I enabled the notifier on that group and now get notifications from that group again.

**Comment by davidnuzik** [comment]
FYI these issues have been tested and closed:

https://github.com/rancher/rancher/issues/19967
https://github.com/rancher/rancher/issues/18616

#18616 might be a duplicate. In any case I _think_ it's safe to close this issue as well based on the testing done unless I am missing anything.
