### ISSUE TITLE
Versioning Services

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#1864]
We've been using the upgrade feature of rancher-compose quite heavily in the last week, this works well when specifying the version number as part of the service name. To better match docker containers it would be nice if rancher would support a version attribute/tag in the service definition.

**Pro's**
- Match container versioning approach
- Look better in GUI
- Make docker/rancher compose files easier to manage when dealing with large environments. 

**Con's**
- Would require update to compose/rancher and GUI.

**Comment by ebuildy** [comment]
Since rancher-compose relies on docker-compose, this is not possible.

+1 for the GUI

I am adding some wish as well ;-) :

- A better link between registry and Rancher, like a Continous Integration workflow, if you push a new version of a container to a registry, Rancher should be able to pull and run it automatically (by removing the old container).

- A rollback process, so if you upgrade a service, you should be able to rollback easily.

- Registry browser, so you can see your images, with versions, and in 1 click, you could run it.

**Comment by Rucknar** [comment]
Forgive my basic understanding but where functionality is lacking in docker-compose it seems to be handled by the rancher-compose file. Couldn't rancher be programmed to read such a value from there?

Agree with those points you raised though.

**Comment by ebuildy** [comment]
I don't see **version** attribute here:

https://docs.docker.com/compose/yml/

**Comment by Rucknar** [comment]
I'm going to close this one down, we primarily worry about the image version, that's now easily seen at the service level. Feel free to re-open if it's something you wish to progress.
