### ISSUE TITLE
Create project system token on demand

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18660]
**Rancher version:**
master 3/6

**Steps to reproduce (least amount of steps as possible):**
1. Set up Rancher and add a GKE cluster
2. Go to API & Keys as the default admin

**Result:**
I can see two `pipeline token for project xxx`, though I don't have pipelines configured. I think we should generate them when needed.
![image](https://user-images.githubusercontent.com/5697937/53928669-e9fe4180-40c5-11e9-8579-75b78dad6df0.png)

**Other details that may be helpful:**
1. The project system token is introduced for app deployment in pipeline, but it is also used in helm controller now: https://github.com/rancher/rancher/blob/master/pkg/controllers/user/helm/controller.go#L355.

**Comment by gitlawr** [comment]
Talked with @loganhz and move this to 2.2

**Comment by bmdepesa** [comment]
rancher/rancher:master-38fd13a8 3/7

* Create cluster
* Created 2 projects
* Created pipeline in both projects
* ServiceAccounts (default, jenkins) created for each project's pipeline instead of project system token

* Deployed catalog app to project
* Project system token created for helm
* Login as different user
* Deploy catalog app to project
* Project system token created

* As admin view API keys
* Both project system tokens are present
