### ISSUE TITLE
Delete button and menu item do not become disabled unless manually refresh UI when cluster driver in use

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18762]
Version: Master 2.2 (3/9/19) 365fde6ba442
Closely related to issue rancher/rancher#18761

Related to rancher/rancher#18460

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Add a cluster driver via the UI (you can use the instructions [here](https://github.com/rancher/ui-cluster-driver-skel/tree/google-gke-example) to add the google gke example)
- Launch a cluster with the `example` cluster driver
- When the cluster is ready and Active and the API does not allow deletion of the kontainer-driver you can still see the Delete button on the Cluster Drivers page and the Delete action in the function menu.

**Result:**
You must manually refresh in order to see the Delete button gray out and delete item be removed from function menu on Cluster Driver page for the driver.

**Other details that may be helpful:**
It is worth noting that as long as the cluster is active you still cannot delete the kontainer-driver from the UI even if delete action is still shown. You will get an appropriate error message from the API so this is not a deal-breaker for v2.2 in my opinion. _If this cannot make it in v2.2 it should be okay in my opinion._

**Comment by westlywright** [comment]
@davidnuzik after some investigation and a few questions I've found this is not a UI issue. The API needs to issue some kind of change event on the cluster driver in question otherwise the UI doesn't know that the actions have changed to recalculate the values of the actions dropdown. Currently after launching a cluster attached to the driver there is no change event fired. The conditions array on the resource confirms this.

**Comment by cjellick** [comment]
moving out. not a blocker
