### ISSUE TITLE
Dealing with Host failures

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#1877]
I'm currently exploring non functional testing on a POC environment we have stood up using rancher.
I've done a simple test to force power off one of the hosts rancher is managing, this however has highlighted a few issues. I've had a search on the issues list but couldn't find much covering them.

**Expected Outcome:**
I expected the host to be marked offline and i expected the services to maintain their scale by spinning up containers on other available hosts.

**Actual Outcome:**
Rancher detected the failure very quickly and marked the host in red with a message of 'reconnecting'.
However:
- Services didn't attempt to maintain scale across other hosts, no new containers were spun up.
- Applications view and infrastructure view still view the containers with a hollow green circle suggesting they are running fine.

**Summary**
From a user experience, I'd expect a host failure to be somewhat more highlighted within the GUI and i'd expect the containers which no longer exist to be highlighted in some fashion so i can quickly understand the impact of the failure. As a sidepoint and perhaps other ticket it would be nice to have a simple status traffic lights for services running through the load balancers. 

From a service recovery point of view, i'd like to be able to configure the behaviour of rancher-server here in how it manages failure scenarios. A fairly safe non aggressive default should be fine and then allow the user to customise it to their requirements.  It's an area of functionality that needs careful considerations of the logic, that said it's also something that's critical as we are assessing rancher against tools such as vSphere / MS VMM.

**Comment by Rucknar** [comment]
<img width="972" alt="screen shot 2015-08-26 at 11 41 04" src="https://cloud.githubusercontent.com/assets/5539660/9491735/26917188-4be9-11e5-9536-d2d2cd5b0f97.png">

**Comment by Rucknar** [comment]
I've been told that we should actually be seeing containers restart on other hosts, i'm wondering if there is something wrong with our configuration. All of our containers have health checks on the container and at the loadbalancer level. Example below, some config 

```
Audit:
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
  tty: true
  image: registry:5000/aud:65
  stdin_open: true
  volumes:
    - /home/rancher/env_config/rt/tomcat/catalina.sh:/usr/share/secure_tomcat/bin/catalina.sh
    - /home/rancher/gluster:/mnt/gluster
    - /home/rancher/env_config/rt:/home/***_user/***
  links:
    - IAM-Database:***
    - LB-***:LB-***
    - LB-***:LB-***
```

**Comment by ibuildthecloud** [comment]
@Rucknar Let me explain in detail how we manage host and service failures.  In short, you want to add service health checks to get the behavior you want.

### Host Failures

When a host goes down we lose the connection to the agent.  Since the agent is not accessible we mark that agent as "reconnecting".  At this time all we know is that we can't talk to the host.  The host could be running, but experiencing a network partition or such.  You can reproduce this situation by just running `docker stop rancher-agent`.   The host is really fine, but Rancher can't talk to it.

Determining if a host is really in fact down is a sufficiently hard problem to solve in a generic fashion.  The approach we take at the moment is that we don't actually try to determine the host state.  We rely instead on service state to for determining if we should act on a failture.

### Service Health Check

For each service you can add a TCP or HTTP based health check.  It's in the `Advanced` section on the create dialog.  We rely on these health check to determine if a service is bad.  How this works is when you enable health checks we run the health check monitor on up to 3 remote servers.  So if service A in running on Host 1, we set up health monitors from H2, H3, and H4.

When Host 1 goes down we loose connection to the agent, so you see "reconnecting".  We don't move the services to a bad state at this time.  That is why you still see green circles.  Once all three health monitors can no longer hit the service, we then decide the service is bad and will start reconciliation.

**Comment by Rucknar** [comment]
Thanks @ibuildthecloud I've updated my last response with the rancher-compose config for the same service (forgot before sorry). I presume that's the same level of service check? I created a dummy service just now and it looks to be correct.

**Comment by ebuildy** [comment]
Even after set the host as "inactive", API tell the container is still in state "running".

**Comment by kaos** [comment]
I would suggest a "yellow" state for services running on hosts that are in state "reconnecting", to flag a potential issue. I argue that it's equally bad to assume the services on a lost host are up and running just as much as they're gone.

The service checks are a good remedy to get out of this, and also the only way for rancher to base any decisions on scheduling wise, but for the UI, to get a feeling for the current state, it would be nice to highlight this condition.

**Comment by fentas** [comment]
@kaos but I guess it is that way right now. If a host is reconnecting the color changes of that host (kind of red). But regarding of the running containers, their state should not change, because reconnecting host does not mean that containers are affected. Only that maybe something is interrupting communication between agent and server. If something is wrong with the container their health checks will tell (as mentioned from ibuildthecloud).

That said I figure changing the color of all running container could be misinterpreted if there is actually nothing wrong happening. And also I rather keep the color yellow for something like response time is going critical (or equally).

**Comment by Rucknar** [comment]
Regarding the host, it clearly shows that it's not connected. It could perhaps be slightly clearer but it's enough for a user of the system to be alerted to the fact there is a potential failure at some level. Personally i'd rather it was more descriptive but that's a minor gripe. 

Regarding the containers, if were unable to contact the host, we can assume their is an issue at some level, we just don't know what level. Perhaps the use of an exclamation mark that when you hover over states 'The host this container is running on is currently not contactable' would help here.

Currently it's assumed that it's running and doesn't highlight this in the interface, assumptions either way  will always lead to confusion, we just need to alert the user there is an issue that warrants further investigation. 

I'm going to deploy a simple web app and re-test the above scenario. We don't currently have the services scale being maintained, aka containers aren't spinning up when a host fails. I need to understand if this is a configuration issue or a bug.

**Comment by kaos** [comment]
@fentas well, in my case, something caused all running containers on a host to go extinct, including the rancher agent instance. Being a lab environment, we haven't setup any health checks, so they all looked fine, until you browse the infrastructure side of things, you see that, aaahh, the agent isn't connected.. Now, each and every container doesn't really have to be marked any special way, but some sort of indication that the system is not 100% ok would be nice, regardless of which page you're at.

I like the idea from @Rucknar that there could be an additional hint, like an exclamation mark, or something, that indicates there may be some issue with the host the container is running on..

Also consider the possibility that not all services may have a TCP socket where you can check its health..

**Comment by deitch** [comment]
Yeah, the last is important. At some level, a service may exist as outbound only, not inbound, but it is critical. What if I have a batch reporting service that generates reports every 60 minutes and then dumps them somewhere else? It expects no input, has no TCP port, but it has to be managed to be up as much as anything else. 

If this were old-school process management, I would rely on a monitor that checks the process, and then a monitor checking the host. If either fails, fail it over.

How would I replicate that here?

**Comment by kaos** [comment]
This is an interesting issue to solve. I don't see any way to generally solve this right, from ranchers perspective. As there may be any number of underlying issues, the most likely being: network down, agent down or host down. Which action to take would be application/deployment specific, so I'm inclined to suggest that the health checks available is extended to take into account these extra conditions, along with the desired action to take on each one. There is of course a problem to determine the difference between if the host or network is down. But given a few extra facts, like reference hosts to determine network status, should be able to help. Then it would be flexible at least, for how your rancher setup would handle these various scenarios on a per service level.

**Comment by deitch** [comment]
Actually, Rancher already has taken a stance on it. Rancher has an algorithm for determining if a service is down. It is treated as down if it is unreachable via tcp/http (whatever you defined in the health check) from 3 independent rancher agents.

Why can the same algorithm not be used for the host? Have each rancher agent, in addition to user-defined health checks, check the health of another agent. If it is unreachable, it is down.

If that algorithm is good enough for health checks on the service, why not for health check on the host?

**Comment by deitch** [comment]
To add (I just posted on the forum), we had health checks set up with Rancher-managed IP, it still didn't fail over.

Can we get a more detailed explanation of how health checks work, how to investigate and debug them? I want to see the health checks running, see their output, see why/how they determine that a service is up or down. Obviously in this case the health check is not successfully running and/or detecting failure.

**Comment by Rucknar** [comment]
Some useful discussion but to bring this slightly back on-track as i believe i'm seeing a bug.

I've done a re-test with a simple web app & loadbalancer running across two physical hosts. I've terminated one physical host (hard power off) and the application hasn't responded to restore scale. 


docker-config.yml
```
WebsiteLB:
  restart: always
  ports:
  - 80:80
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - WebServiceV1:WebServiceV1
  stdin_open: true
WebServiceV1:
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
  tty: true
  image: tutum/hello-world
  stdin_open: true
```
rancher-config.yaml
```
WebsiteLB:
  scale: 1
  load_balancer_config:
    description: Loadbalancer for website testing.
    name: WebsiteLB config
WebServiceV1:
  scale: 12
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
```

Here is the host showing as offline.
<img width="327" alt="screen shot 2015-09-24 at 09 25 22" src="https://cloud.githubusercontent.com/assets/5539660/10068804/78c6e18c-629f-11e5-81ea-3bafb452b6b3.png">

Here is the app, impossible to tell anything is wrong and it hasn't restored the services elsewhere.
<img width="844" alt="screen shot 2015-09-24 at 09 25 15" src="https://cloud.githubusercontent.com/assets/5539660/10068810/7f9c36ec-629f-11e5-8fa8-6b7d67c2ded4.png">

What process health checks these containers? Is it on the host they run on? If so, i fail to see how they would spot a host being forced off?

**Comment by ibuildthecloud** [comment]
@Rucknar There is one caveat you have to be careful of, don't know if this applies, but I'll just give you a heads up.  When we schedule the health check clients we never put in the same host as the container.  The health check client is the component that does the port/http ping check.  If we put it on the same host, we can never know the health check failed.  We schedule up to 3 clients if we can (this requires at least 4 hosts).

There is one exception though, if you only have one host, then we put it on the same machine.  So I just wanted to confirm that when you started this test did you have one host?  Then deploy some containers, add another host, deploy more.  In that scenario health checks will not work properly.

Besides that, it does sound like there could be a bug.  We'd have to try to reproduce on our side.

Right now I would say Rancher is pretty conservative when it comes to recovering from failure.  Other container system are more aggressive in spinning up new container based on "fuzzy" failure information.  Meaning that there is good indication that the service is gone, but they don't really know.  I think our conservative nature comes from our background in running persistent workloads.

I'm wondering if Rancher should have different policies for how to recover applications.  One can be aggressive where we don't wait for an absolute indication of failure, the other could be something more tailored to persistent work loads that require strong guarantees before taking action.

**Comment by deitch** [comment]
@ibuildthecloud what does that mean, "schedule the health checks on the same host as the container"? The health checks are a Rancher-wide thing, aren't they? How do you "schedule" them?

**Comment by ibuildthecloud** [comment]
@deitch When you create a health check on a container/service that is running on host A, we then try to find 3 hosts that are not host A to run the healthcheck from.  So hosts B, C, D will be configured to ping your container/service on host A.  The health check scheduling refers to which host we decide to checks on.

**Comment by Rucknar** [comment]
@ibuildthecloud this is when using two hosts and failing one of those two, I've tested with 3 and got the same result.

**Comment by ibuildthecloud** [comment]
@Rucknar thanks.  We will definitely look into this, sounds like a bug.  

ping @alena1108 @sangeethah

**Comment by deitch** [comment]
@ibuildthecloud ok so you mean internally.

How do I look at logs of what the health check is trying to do? In our case, we had 3 agent hosts + server, set up a service with scale=1, the container is running sshd, set up a health check to port 22, and killed docker on the one host. The health check kept showing `running`. 

I am not sure how to recreate it, but I can cause it to happen in our environment. Tell me what to look for to get debug output and I am more than happy to walk it through.

**Comment by ibuildthecloud** [comment]
@deitch We don't expose this information well in the API/UI, we should.  @alena1108 @sangeethah Can you share SQL statements to run to check the state of the health checks that are running and where they are running from.

**Comment by sangeethah** [comment]
There is similar issue whet we are not able to mark instance unhealthy since the host in which the instance was running was also included as one of the host to monitor its health - 
https://github.com/rancher/rancher/issues/1917

**Comment by deitch** [comment]
I wish I could give you access to our environment, but behind firewalls, etc. Consider me your smart-hands. Tell me how to see the checks, last checks, and where they log output.

**Comment by sangeethah** [comment]
@deitch , This sql command should list health state reported by each of the hosts that is assigned to monitor instance's health:

```
select * from healthcheck_instance_host_map where healthcheck_instance_id=(select id from healthcheck_instance where instance_id=<instance id>);
```

**Comment by deitch** [comment]
Is there some sort of log where I can see in real time as the health checks are performed, and what they see?

**Comment by deitch** [comment]
What is `<instance_id>` in this case? Is it the instance as shown by `docker ps`? How do I find it?

**Comment by sangeethah** [comment]
You can do a "View In API" and you will be see id. It would be in the format , 1i<nnnn> , <nnn> would be the instance id.

**Comment by vincent99** [comment]
`<instance_id>` would be the numeric ID rancher assigns to each container.. Go to the container in the UI, and it's the end of the URL, not including the `1i`.  e.g. `/infra/containers/1i42` -> 42.

**Comment by deitch** [comment]
OK, got it. It looks like right now in our environment the host is down, the health check is defined, and I have the ID. So I am going to check the sql now.

**Comment by deitch** [comment]
Hmm...

````sql
mysql> select * from healthcheck_instance_host_map where healthcheck_instance_id=(select id from healthcheck_instance where instance_id='122');
+----+------+------------+----------------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+-------------------------+---------+--------------------+--------------+
| id | name | account_id | kind                       | uuid                                 | description | state  | created             | removed | remove_time | data | healthcheck_instance_id | host_id | external_timestamp | health_state |
+----+------+------------+----------------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+-------------------------+---------+--------------------+--------------+
| 19 | NULL |         10 | healthcheckInstanceHostMap | c69c1f28-de56-483f-8b54-57e2dca7f464 | NULL        | active | 2015-09-24 07:01:22 | NULL    | NULL        | {}   |                       9 |       5 |               NULL | healthy      |
| 20 | NULL |         10 | healthcheckInstanceHostMap | c9dc003c-6a57-426e-ac3c-4009b0b704bf | NULL        | active | 2015-09-24 07:01:22 | NULL    | NULL        | {}   |                       9 |       2 |         1443121029 | unhealthy    |
+----+------+------------+----------------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+-------------------------+---------+--------------------+--------------+
2 rows in set (0.01 sec)
````

**Comment by deitch** [comment]
So running `select * from hosts;` shows that `5` and `2` are 2 of the 3 known hosts (the third is where the service container was running), both are fine and have state `active`.

What next?

**Comment by sangeethah** [comment]
In your case , 2 hosts - 5 and 2 where assigned to monitor this instance health and host id -5 was not able to detect the state of the instance as being unhealthy.  We expect all the hosts to report the state of instance as being "unhealthy"  to mark the state of the instance as "unhealthy".

**Comment by deitch** [comment]
Right, so you know what my next question is. Why did host 5 not succeed in marking it as unhealthy?

BTW, I concur with what the commenter said earlier: there needs to be a way to choose how aggressive an algorithm you want.

**Comment by deitch** [comment]
FWIW, `docker ps | grep rancher` on host 2:

````bash
# docker ps | grep rancher
019931dad304        rancher/agent-instance:v0.4.1                                "/etc/init.d/agent-in"   13 hours ago        Up 13 hours         0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   b0999a69-98bb-4fb1-b935-55e8712cfe83
018a7f7fa8d7        rancher/agent:v0.8.2                                         "/run.sh run"            7 days ago          Up 13 hours                                                        rancher-agent
````

and on host 5:

````bash
# docker ps | grep rancher
b200a4f9e813        rancher/agent:v0.8.2                                         "/run.sh run"            3 days ago          Up 3 days                               rancher-agent
````

**Comment by sangeethah** [comment]
host 5 is not able to mark the host healthy because there is no Network Agent running. 
Workaround can be to start a network agent in this host , by deploying an instance in this host.
After this , host should be able to mark the state as "unhealthy".

This bug that we do not have a network agent running on a host ,that should be monitoring health for instances needs to be addressed.

**Comment by deitch** [comment]
So you are saying:

1. the rancher-agent should have started the network agent
2. the network agent would have monitored the health
3. because the rancher-agent failed, it didn't know my health check failed
4. the rancher server/agent should have known no network agent is running

In other words, rancher agent failed its own health check, but didn't alert or fix itself (failed silently) and so my health check also failed silently? Shouldn't rancher know and handle these issues?

Or are you saying that is the bug, and it is known and will be fixed?

**Comment by vincent99** [comment]
1/2/4: Yes.  3: Sort of, it didn't exactly "fail".. The bug is that nothing currently schedules the creation of a Network Agent if there isn't already one on the host chosen for the health check.

@alena1108 it also seems wrong that the `health_state` is defaulted to `healthy` here instead of `initializing` when the state was obviously never set by an actual check.  If it wasn't marked `healthy` the state would have shown degraded and it would have been more obvious that *something* was wrong.

**Comment by deitch** [comment]
@vincent99 I don't agree. Look at it from a user's perspective:

* I scheduled a health check
* The health check isn't running but the system says it is

That is all that matters. The fact that part of the components are running (server and agent) and part not (network-agent) is not of much interest except in debugging.

The proximate bug may be that "nothing currently schedules the creation of a Network Agent if there isn't already one on the host chosen for the health check." But the fundamental problem is that a crucial component of the system - one which can lead to a cascade of errors, like in this case - can fail (or not start) without the system being any the wiser.

I would've assumed it works like this:

* server knows all of its hosts, speaks to and checks on those *agents*
* if any *agent* is unreachable, the entire host on which that agent runs and all of its dependencies are treated as unreachable (or "in error" or whatever you want to call it). 
* each agent should be checking regularly all of its own dependencies, e.g. network agent (although personally, I would have rolled it into a single agent container). 
* each agent should restart its dependencies if needed, and report on their state to the server
* if the server does not have a positive assessment of a dependency, it should treat it as missing and reschedule dependencies on those. So if I do not have a positive assessment of a network agent, create the health check elsewhere or, at the very least, remove this node's status from the algorithm

**Comment by deitch** [comment]
In the meantime, though:

1. When is this scheduled to be fixed?
2. What can I do to work around this?

I don't relish the idea of building my own container monitoring system and then using the API to force it to move elsewhere.

**Comment by vincent99** [comment]
This is GitHub, we're talking about the code.  All I meant is the issue is not in `rancher/agent` because it was never told to create the Network Agent and the health check state didn't "fail" because nothing existed to update it.  The root issue is that cattle never told the host to create a Network Agent (it would download it's config containing the check definition on startup), and additionally some other factors made this situation undetectable.

> server knows all of its hosts, speaks to and checks on those agents
> if any agent is unreachable, the entire host on which that agent runs and all of its dependencies are treated as unreachable (or "in error" or whatever you want to call it).

`rancher/agent` (which communicates with the `rancher/server`, creates/destroys containers, etc) on each host connects to the server.  If the agent is not connected the host will show "reconnecting" state.  
This does not provide any information as to whether the host is *actually* still ok or not, as the agent can be disconnected for a variety of reasons while the host and containers on it are still fine.  For example, while upgrading the agent itself, or there is a network partition separating the server from host(s).

> each agent should be checking regularly all of its own dependencies, e.g. network agent (although personally, I would have rolled it into a single agent container).

They are not "dependencies" per se.  The `rancher/agent` tells docker to run containers.  One of those can be the Network Agent (the image is `rancher/agent-instance`) which provides the IPSec point-to-point network and healthchecks for containers on those networks.  Though not exposed today, there could be multiple separate networks and therefore multiple Network Agents per host.

> each agent should restart its dependencies if needed, and report on their state to the server

This is "turtles all the way down".  Now you need something to check that the checker that checks that the agent is up is still checking, ad infinitum.

> if the server does not have a positive assessment of a dependency, it should treat it as missing and reschedule dependencies on those. So if I do not have a positive assessment of a network agent, create the health check elsewhere or, at the very least, remove this node's status from the algorithm

The health checks report their state to the server in the table you were looking at.  The `external_timestamp` is the last time it was reported.  The checker should be considered down if the time is "too old".  Like having a check for the checker, sans turtles.

> When is this scheduled to be fixed?

Likely next week's release, but since this thread just worked out the root cause this afternoon we (@alena1108, @ibuildthecloud and I) haven't yet gotten together to evaluate what changes need to be made, their scope, or the priority of each.  Particularly given the workaround is fairly straightforward (below).

There are several things to look into:
- [ ] Scheduling a health check doesn't ensure that a Network Agent is scheduled on the host to run it
- [ ] The default health state is apparently `healthy` instead of `initializing`
- [ ] The `external_timestamp` is null but that check state was apparently still considered valid.  Is the timestamp actually used in the evaluation?
- [ ] Is there logic to reschedule a health check to another host when an agent is disconnected? A host is deleted?  A network agent is deleted?  The timestamp isn't updated in "a while"?
- [ ] Is the state `unhealthy` in the API when 1, 2, or 3 checks fail?  (I think it's 3).  Maybe there should be an intermediate healthState in the API for `mixed` or something if there is disagreement between the check states.
- [ ] Should the number of checks scheduled and the threshold for unhealthy be options?  (global settings, or part of the healthcheck definition?)  Maybe people like flapping and want rescheduling on a single failure, or want to be *really* sure and want to run checks from *every* host and wait until they *all* fail.

> What can I do to work around this?

Deploy a container on every host so that a Network Agent will be created.  An easy way would be to create a service with global scale ("Always run one instance of this container on every host") using a small image like `busybox` that does nothing.

**Comment by deitch** [comment]
That's a pretty detailed answer, thanks.

> This is "turtles all the way down". Now you need something to check that the checker that checks that the agent is up is still checking, ad infinitum.

It is, but at a certain point you just say, "that's it." So rancher needs agents? It checks on them. Rancher needs health checks, which use network agents? It checks that they are up. 

The trap we fell into here isn't that scheduling a health check doesn't necessarily start a network agent; that is a bug, nice debugging on it. The core issue is depending on something and not checking its existence from the one service we know has to be up: rancher server, which needs to **know** proactively that an agent and necessary components are up.

> The health checks report their state to the server in the table you were looking at. The external_timestamp is the last time it was reported. The checker should be considered down if the time is "too old". Like having a check for the checker, sans turtles.

Like that approach. You are saying, the server knows what a normal operation would look like. Let it check (e.g. timestamps) with enough frequency to be satisfied, and if it sees a problem, try to resolve it or, at the very least, flag it.

In your terms: the server is the bottom turtle.

> Deploy a container on every host so that a Network Agent will be created.

Do you mean a container "with rancher-managed networking", right? I have a container running on every host, but it has host networking, so it didn't trigger it. 

If it will come out patched next week, that works for us. Flag here if you have a beta you want me to try. More than happy to help.

**Comment by vincent99** [comment]
Yes a container with managed network.

Hmm, there's another one.  We probably can't offer health checks for every network mode, 3 other random hosts don't necessarily have a way to reach the container.

**Comment by deitch** [comment]
You mean if a container isn't using rancher-managed networking? Yes, I raised that earlier. And if you have a container that has not open ports, e.g. a batch processor that goes to a data source every 10 mins, gathers data, and sends out a report (I can think of lots of examples).

In this case, the classic way to monitor *is* by process. We really need a health check that involves monitoring the process via rancher-agent (or process-agent spinoff, or similar).

**Comment by Rucknar** [comment]
@vincent99 Submitted a pull request for the docs, just added in a little more detail about health checking based on this conversation, easier to read for others than this thread!

**Comment by deniseschannon** [comment]
Thanks @Rucknar for the docs about details on health checks. We've incorporated them into the docs site at http://docs.rancher.com/rancher/concepts/health-checks/

**Comment by deitch** [comment]
@deniseschannon I saw you closed it. There still was an open discussion about using the "health check algorithm" (up to 3 independent hosts monitoring the *agent*), and if all 3 fail, then to treat the entire host **and all its containers** as down, and thus maintain scale by moving the containers to other hosts.

This is necessary so that services that cannot have tcp-based health checks (no IP, no inbound services, etc.) can be managed by Rancher as well.

**Comment by deniseschannon** [comment]
@deitch The issue you are discussing is a duplicate of this: https://github.com/rancher/rancher/issues/1917

**Comment by deitch** [comment]
@deniseschannon I don't think it is. I am not discussing the issue with currently defined tcp-based health checks failing. I am talking about being able to manage the state of a Service's containers even *without* tcp-based health checks at all. Since the agent already exists, and can monitor the containers locally and thus know their state(s), they should be able to act as their own local health-checkers, and their state, in turn, can be determined by other agents.

**Comment by kaos** [comment]
+1 for that last description @deitch , very clear (and something I'd like to see :)

**Comment by vincent99** [comment]
The state and health of the `rancher/agent` is not a good proxy for the condition of a host of the user containers on it.

The agent already does keep track of the state of the containers on the host.  If a container stops it will be reported up, the UI will show it stopped, it will be restarted according to the restart policy (which defaults to always for services), etc.  That is all part of the native docker integration so that we know about `docker run`s or `docker stop`s performed on the host.

What it sounds like you want but is missing is a way to use the container state as a "health check" and cause it to be rescheduled to another host instead of just restarted.  To be useful this would have to have some different options like consider it unhealthy if it stopped X times in Y seconds.l, we can't go shuffling containers every time they restart.

Or you can add a small http daemon inside the container of a process thar otherwise would not have one, to do some checking and reports a health state out.  Monitoring that a process is still running is pretty coarse and not really all that helpful.  It doesn't tell you that the process is successfully still doing anything other than existing; it could be hung, deadlocked, unable to connect to a dependency, out of disk space, etc.  An actual check to e.g. watch a logfile for a line showing that your report was sent out in the last 10 minutes is much more valuable.

**Comment by Rucknar** [comment]
Also we still have an open bug where no failover of any type works. I'm happy to raise another ticket for this and leave this to the discussion but that was the tickets original purpose.

**Comment by deitch** [comment]
> or you can add a small http daemon inside the container of a process

@vincent99 that isn't very realistic. Almost no one is going to add an http daemon, with all its attendant overhead, management, security risks, performance tests, *everything*, just to do a `200` check! Who is going to want to rebuild and reconfigure their container for that? They will say, "if a tool cannot monitor process liveness, it is missing something basic."

I used to run enterprise management at a very large firm. I brought in the modern host and process monitoring (pre-container days). I brought in tcp monitoring tools too, for E2E. But that was later. First, I needed to fundamentally know and manage processes: is it running? How well is it running is something I worried about after I had covered the basic "blocking and tackling" of processes.

Don't get me wrong; I love Rancher. I put a lot of effort into it, recommended it, so I have some reputation on the line. And I think one of its strongest assets is the sheer speed of iteration of the team. But I am ask if we get what customers do: the fundamental unit of deployment, and therefore of health, is the container. If the container is up, all is good; if it is not, all is not. If you do not know the state of the container, have an algorithm that resolves the uncertainty.

Just about every customer on this discussion and the one on the Rancher forum said:

1. I created a service (without health checks)
2. I set `scale=1`
3. I killed the host, Rancher didn't move it over. What is broken?

People expect the container monitor and manager built into the orchestrator to watch the container because it just makes sense. Heck, that is what every cluster management system always has done. I used to do it with Veritas 20+ years ago. Not working that way violates the principle of least surprise. 

Allow me to put it in product management terms. Do you want to say, "Rancher is awesome for managing all your services across a multi-host cluster"? Or do you want to say "Rancher is awesome for managing all your services across a multi-host cluster, except for services that do not have a listening http or tcp port open, which, by the way, is a major portion of enterprise services (and hence containers), so go find some other orchestrator to manage it"?

When you ask potential customers to either change their software to fit your monitoring, or do some additional engineering to create monitors, they will look elsewhere.

> Monitoring that a process is still running is pretty coarse and not really all that helpful. 

I disagree and agree completely. Monitoring that a process is still running *is* pretty coarse... but it *is* extraordinarily helpful. This is the very basic level of monitoring. Everything else - TCP checks, logfile checks, etc. - are all at the **next** level. It is fabulous that Rancher gives us customers the opportunity to use a more intelligent level of monitoring, but start with the basics.

I love a good steak, it is great it is on the menu, but if I am eating here three times a day, make sure you offer a salad, sandwiches and soup *before* you offer steak.

Ok, I think I have made my point (probably too many times). Let me summarize:

* Rancher's TCP health checks are great, but they miss the very basic level of monitoring and management
* Customers expected failover to work the way I described, not the way it actually functions. 
* Rancher is damn cool but has a gaping hole at the basic level for one of its fundamental tasks, while most of the logic for filling that hole already exists. Why drive customer to something else?

**Comment by deniseschannon** [comment]
@Rucknar I think your issue has become intertwined with lots of discussion. Could you please create a new ticket for your issue that you are still seeing? 

@deitch Similarly, I wonder if it'd be better to create a new ticket for what you are looking for regarding. "I am talking about being able to manage the state of a Service's containers even without tcp-based health checks at all. Since the agent already exists, and can monitor the containers locally and thus know their state(s), they should be able to act as their own local health-checkers, and their state, in turn, can be determined by other agents."

**Comment by Rucknar** [comment]
Thanks @deniseschannon I've done that now.

**Comment by deitch** [comment]
Good idea @deniseschannon; done. See https://github.com/rancher/rancher/issues/2195

**Comment by deitch** [comment]
@deniseschannon @vincent99 going back to what we agree was a bug, quote from @vincent99 :+1: 

> Scheduling a health check doesn't ensure that a Network Agent is scheduled on the host to run it

Do we have a targeted release for fixing it?

**Comment by deniseschannon** [comment]
@deitch I've just created an issue for the 

"Scheduling a health check doesn't ensure that a Network Agent is scheduled on the host to run it"

It's #2287 

I'm going to close this issue as it's hard to track exactly what we're trying to fix. I believe we've created separate issues for everyone who has chimed in. For any other issues, please open a new issue.

**Comment by deitch** [comment]
Thanks, @deniseschannon

**Comment by deitch** [comment]
I am still having an issue, even with the workaround. I am opening a new issue.

**Comment by jmcarbo** [comment]
What I've found so far is that starting a rancher-compose deployment with s3 based builds places a heavy network demand on the rancher server machine and causes random node disconnections. The same deployment with images placed in a local registry runs smoothly without any issues because rancher server machine has spare bandwitdh to talk to other nodes. I am using rancher server 0.56. Hope this might help some of the issues pointed out here.

**Comment by deniseschannon** [comment]
@jmcarbo What you're seeing/describing is related to this issue: https://github.com/rancher/rancher/issues/2137

**Comment by tombusby** [comment]
I feel like Rancher's current behaviour handles this really badly. The entire point of rancher/docker/scaling is that if I have a problem with part of the system, it shouldn't bring the entire site down. It's entirely self defeating. Plus the fact that after a huge amount of digging, it doesn't actually seem to be possible to add a healthcheck to an existing service. You have to clone/recreate the service.

**Comment by deitch** [comment]
I am wondering if there is a saner way, e.g. to use the autopilot pattern with Rancher.
