### ISSUE TITLE
rancher kubectl cannot be used with plugins

### ISSUE THREAD

**Issue by guilhem** [rancher/rancher#18788]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

install a kubectl plugin (like [node-admin](https://github.com/danisla/kubefunc/tree/master/node-admin)

**Result:**

```
$ rancher kubectl node-admin
Error: unknown command "node-admin" for "kubectl"
Run 'kubectl --help' for usage.
unknown command "node-admin" for "kubectl"
FATA[0000] exit status 1

$ kubectl node-admin
1)  aks-....  v1.12.6
2)  aks-....  v1.12.6
3)  aks-....  v1.12.6
Select a node:
```

**Comment by xanalogica** [comment]
The cause is one position-dependent argument in kubectl v1.14.6:

   WORKS:  kubectl newplugincmd --kubeconfig=/home/jeff/.kube/config1
   FAILS: kubectl --kubeconfig=/home/jeff/.kube/config1 newplugincmd

The Rancher CLI is inserting the --kubeconfig= argument before the custom plugin command.
Reversing it however requires the plugin to accept/ignore the --kubeconfig argument.
A third option is passing setting the env var KUBECONFIG= instead of using an argument, but the behavior is -slightly- different as KUBECONFIG is a list of config files that are merged, whereas on the command-line it overrides any other config files present in a env var.  All very messy.
