### ISSUE TITLE
Gauge ticks incorrect if there is unschedulable nodes in the cluster

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18857]
rancher/rancher:master 

Steps:

1. Create a cluster with 3 nodes (1 node with etcd role, 1 node with worker role, 1 node with control panel and worker role)
2. Enable monitoring

Result:

The ticks are wrong

![image](https://user-images.githubusercontent.com/21168270/54255455-2254c280-4593-11e9-81c2-0945a6a4ab46.png)

Reason:

The unschedulable nodes are filtered out before finding the min and max values

**Comment by davidnuzik** [comment]
Note when testing you need at least 2 worker nodes (scheduleable nodes)

Version: Master 2.2 (3/13/19) e090397b4c72
Confirmed issue. Follow the steps to reproduce. You will need at least 2 worker nodes now because unschedulable nodes are filtered out (Control Plane and etcd).

While testing watched page as additional worker node provisions. When fully up the gauge ticks appear correct.
