### ISSUE TITLE
Feature Request: Suspend/Disable and Enable a Cronjob

### ISSUE THREAD

**Issue by ducas** [rancher/rancher#18945]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a cronjob to kubernetes
2. Open cronjob workload in rancher UI

**Result:**
* Can not disable/suspend a cronjob that is enabled
* Can not enable a cronjob that is suspended

**Other details that may be helpful:**
As an operator
I want to be able to suspend an enabled cronjob
So that I can stop the job from running temporarily

As an operator
I want to be able to enable an suspended cronjob
So that the job can run on its next cron after being stopped from running temporarily

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6
- Installation option (single install/HA): HA using helm chart

**Comment by TechCanuck** [comment]
This is a great add.  After a recent dockerhub compromised password issue, our cron jobs caused many unsuccessful login attempts and thus continued to lock the dockerhub account.  The only option to stop it authenticating was to remove the cron job while the issue was repaired.

**Comment by ducas** [comment]
@loganhz any idea when this might get prioritised?

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/60228500-732fc300-98c5-11e9-8571-8e9fcd041b78.png)

@ducas there is a suspend field in rancher UI. Does it work?

https://stackoverflow.com/questions/52776690/disabling-cronjob-in-kubernetes

**Comment by ducas** [comment]
@loganhz hey! that does seem to work! has that been there for a while...? sorry, i must have missed that before. is there any way we can make the feature a little more prominent?

**Comment by loganhz** [comment]
Yes, we can make it as an action for cronjob.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (7/2/19)

This change is essentially _just_ adding "Suspend" and "Resume" to the function menu for the workload. There are no API changes.

I tested by importing the example cronJob k8s docs supply. This is a simple job that runs every minute:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

I then "Suspended" (the new addition to the function menu)
![image](https://user-images.githubusercontent.com/45179589/60546337-ed02ea80-9cd1-11e9-82af-d60aa0ad409d.png)

The UI shows the workload is suspended:
![image](https://user-images.githubusercontent.com/45179589/60546355-f68c5280-9cd1-11e9-8f20-43119f617d31.png)

And we indeed stop running each minute immediately.

I made sure that if we edit the workload while it is suspended that the Edit page is correct showing "Suspend" is "Yes" and it is:
![image](https://user-images.githubusercontent.com/45179589/60546452-2d626880-9cd2-11e9-9975-6bb8ecef9449.png)

I made sure I can set to "No" via the same edit page and save and it will indeed Resume.

I tested this via the function menu and via the edit workload page several times in various ways.
When you want to Resume the menu updates to state "Resume"
![image](https://user-images.githubusercontent.com/45179589/60546501-4f5beb00-9cd2-11e9-8a8c-f58380569a2e.png)

Confirmed nothing has changed in the API. Suspend has been a feature of "cronJobConfig" in the cronjob when viewing in API. We just exposed this in the extra area in the UI -- the function menu.

I tested with a few other jobs, tested by creating a brand new job via UI as well (instead of YAML import) and this is also working. I was not able to identify any issues. I made sure when we suspend/resume this is reflected in kubectl as well and is functionally working correctly.
