### ISSUE TITLE
rancher issues

### ISSUE THREAD

**Issue by zhengyongtao** [rancher/rancher#18983]
1. 不给命名空间分配项目就无法查看该命名空间下的pods，有的项目是不由rancher构建的，默认没有项目，这样每次都要进rancher重新分配项目，十分麻烦
2. 用EC2构建的K8S集群可以查看公网IP，但是EKS构建的就只能查看到子网IP了，希望能改进一下
3. 用EC2构建的K8S集群使用rancher管理，会经常发生页面响应超时的情况，但是使用EKS构建的就不会发生这种情况， 希望优化一下

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.7` UI: `v2.1.21` |
|Route|`authenticated.project.ns.index`|

**Comment by deniseschannon** [comment]
@zhengyongtao It's best if you translate your issues into English and create separate issues for each one. 

Per google translation

1. You can't view the pods under the namespace without assigning items to the namespace. Some projects are not built by rancher. There is no project by default, so you have to re-allocate the project every time.

This is correct. In order to navigate through pods/namespaces in Rancher, they must be associated with a project. 
 
2.The K8S cluster built with EC2 can view the public IP, but the EKS can only view the subnet IP, I hope to improve it.

EC2 with Rancher launching k8s and and EKS are not directly comparable. 

3. The K8S cluster built with EC2 uses rancher management, and the page response timeout often occurs. However, this situation does not happen with EKS. I hope to optimize it.

I'm not sure what you mean by the page time outs? Can you give more clarity? Are there are lot of deployments or what exactly times out? Can you create a new issue with more details (and in english).
