### ISSUE TITLE
Need to be more consistent in etcd "snapshot"/"backups" namings

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18999]
For rke clusters, you can configure periodic snapshots with a possibility to back up the snapshot to an external S3 data store. Based on that, we need to make small changes to the UI:

* On a cluster configuration page, instead of a drop down target where you chose between local and S3, we need a radio button. Default would be "local". The second choice would be Remote/s3 (@westlywright to decide on an exact naming).
* Action "Take a backup" should be "take a snapshot". Same applies to "Restore..." action.
* On the Snapshots page we already distinguish between local snapshots and the ones backed up to S3, so we are good there.

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/18/19)
Each issue was addressed correctly:

- On a cluster configuration page, instead of a drop down target where you chose between local and S3, we need a radio button. Default would be "local". The second choice would be Remote/s3 (westlywright to decide on an exact naming).
> This change has been made. Local:
![image](https://user-images.githubusercontent.com/45179589/54574652-5888ac80-49ae-11e9-9ee3-1a5790900af9.png)

> s3:
![image](https://user-images.githubusercontent.com/45179589/54574659-62aaab00-49ae-11e9-8d61-0c5ea8667681.png)

- Action "Take a backup" should be "take a snapshot". Same applies to "Restore..." action.
> This has been fixed so it's more clear (since these are snapshots in both cases and we only backup to s3 AFTER a snapshot has been taken)
![image](https://user-images.githubusercontent.com/45179589/54574872-3e030300-49af-11e9-8996-4c69a457504a.png)

- On the Snapshots page we already distinguish between local snapshots and the ones backed up to S3, so we are good there.
> Yes the Target column already covers this so this is good.
![image](https://user-images.githubusercontent.com/45179589/54574956-920de780-49af-11e9-9112-6ce7f2a2123b.png)


Smoke tested this area, ensure UI looks good. Ensure local/s3 backup/restore still working as expected. HTTP/API look good.
