### ISSUE TITLE
Support Kubernetes API Server Endpoint Access Control for EKS

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#19051]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Add support for Kubernetes API Server Endpoint Access Control

https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-eks-introduces-kubernetes-api-server-endpoint-access-cont/

gzrancher/rancher#4690

gzrancher/rancher#7307

**Comment by janeczku** [comment]
**Use case**

When provisioning an EKS cluster in Rancher a public (internet-facing) Kubernetes API server endpoint is created and used for communication between Rancher, worker nodes and the Kubernetes Control Plane.

Users should be able to enable private access to the Kubernetes API server so that all communication between worker nodes and the API server stays within the VPC.
If Rancher shares a common VPC with the worker nodes, users should also be able to completely disable public access to the API server so that it's not accessible from the internet.

**Comment by janeczku** [comment]
Pinned: https://github.com/aws/containers-roadmap/issues/221

**Comment by sowmyav27** [comment]
Reopening this because of this issue - https://github.com/rancher/rancher/issues/28533

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `3ca11da8297`**

- User is able to deploy a hosted EKS cluster with only private access enabled. (VPC, subnet and security group same as that of rancher server's)
