### ISSUE TITLE
Catalog App answers and values out of sync

### ISSUE THREAD

**Issue by mikenorgate** [rancher/rancher#19060]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a catalog app by completing the form
- Upgrade the app 
  - Edit the "answers" as yaml and make a change

**Result:**
When returning to the upgrade page again the page shows the yaml editor, when clicking the "Edit as form" button the values differ from the yaml

**Other details that may be helpful:**
The impact is that it can be quite easy to accidentally upgrade a service with old values 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0-rc2
- Installation option (single install/HA): Single

**Comment by davidnuzik** [comment]
Tested in v2.1.7 and cannot reproduce in that version.
Tested in v2.2.0-rc12 and reproduced the issue.

**Comment by loganhz** [comment]
@westlywright @davidnuzik 

in 2.1.x, `Edit YAML`  converts the key/value pairs to YAML and `Edit as Form` converts the YAML to key/value pairs. The converting stuff is not stable if your YAML is complex. 

in 2.2.x, Rancher supports the `valuesYaml` field. Now UI will send the real YAML to backend directly instead of converting to key/value pairs first. Now if you click save in `Edit as YAML` mode, it will send `valuesYaml` field only to backend. If you click save in `Edit as Form` mode, it will send the `answers` field only.

So now UI doesn't support converting between YAML and  key/values pairs when you switch `Edit YAML` and `Edit Form` as the converting is not stable.

Maybe we can document the behavior change or maybe we can add some  warning like your change is not saved when users switch the edit mode?

**Comment by cjellick** [comment]
That is incredibly confusing

**Comment by loganhz** [comment]
Here is one of the converting issue if we want to support the convert.

https://github.com/rancher/rancher/issues/16680

**Comment by westlywright** [comment]
So I'm understanding this like so: 

2.1.x - switching back and forth between `Edit as Yaml` or `Edit as Form` was fine because the answers were sent as k/v pairs regardless. 

2.2.x - we added `valuesYaml` to the api, so if the user `edits as yaml` we send the yaml directly to the api in `valuesYaml` param and do not populate the answers fields and vice versa, `edit as form` sends the answers in k/v pairs and we don't populate `valuesYaml` so we don't support switching between them if one was used because the conversion was not always correct? 

Is this correct @loganhz?

**Comment by loganhz** [comment]
The thing is I can not make sure the converting stuff between YAML and key/value pairs is 100% correct.

**Comment by loganhz** [comment]
@westlywright Yes, it is correct.

**Comment by cjellick** [comment]
we need to talk about how we will addresss this for 2.2.1

**Comment by vincent99** [comment]
The intent was for the UI to always use produce a `valuesYaml` and never use `answers` anymore.

**Comment by proligde** [comment]
same here - we've just upgraded to 2.2.1 and this is pretty bad for us

**Comment by materemias** [comment]
Maybe we should have a button to convert answers to yaml. Having nothing is the worst scenario.

**Comment by loganhz** [comment]
@materemias  Still trying to find a solid way to do the converting.
 
If we can't find a solid solution, how about adding a popup warning when switching between the 2 modes?

**Comment by materemias** [comment]
It makes sense, at the same time yaml should be the default imho. answers just has no comparative benefits.

**Comment by mholasek** [comment]
The current situation is very bad for us because we often need to copy app deployments via the yaml answer file from one project to another with minor changes (done by search/replace). But at the same time colleagues will make changes in the form. We lost the possibility to copy answers from one project to the other or the simple edit functionality in the form in 2.2.x. Would be great if you can bring back switch between yaml and form without loosing values.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/20/19)

This change significantly improves support for switching from YAML back to form. Refer to https://github.com/rancher/ui/pull/2897 for the details.

Now, when you make changes in YAML and try to go back to the form view you will be warned if there is data in the YAML that may be lost if you switch back to the form. Below is an example with some of the preliminary tests I did with chartmuseum.

In the chartmuseum app config, I switched to YAML and added this secret as pictured below.
![image](https://user-images.githubusercontent.com/45179589/57721188-6cf8c680-7638-11e9-829a-581d4c748b49.png)

Upon clicking the "Edit as a Form" button to go back to the form view, you will now get a warning when data you have in the YAML may get lost due to us switching back to the form view:
![image](https://user-images.githubusercontent.com/45179589/57721258-987bb100-7638-11e9-8354-59c02823c941.png)

The modal allows you to confirm or Cancel to return back to the YAML view and avoids data loss. Other wise you may opt-in to the data loss by choosing "Confirm" which will switch us back to the form view. When switching back to the YAML view I can indeed see my data is lost.

We know that this is not a perfect solution, but this will at least make it very clear to the user the risks of what data may be lost if switching back to the form view.

I also tested this via app upgrades (scenario reported in the original issue, #19060 and again, I will get an appropriate warning if there is potential for data loss when switching back to the form view.

In the case where we input data for questions the form already contains there is no data loss. For example back to the chartmuseum example, I can input under "persistence" size of "17Gi" when I go back to the form view, my value is reflected in the form and I do not get any warnings in this case since I have no custom data (content that is not already existing questions).

![image](https://user-images.githubusercontent.com/45179589/57721617-83535200-7639-11e9-8549-a6150d593c34.png)

I followed these steps to test various apps. I ensured that I can bi-directionally change values. I can change values of items in the form view and it will be reflected in the YAML view and vice versa (must be a question seen on the form to support fully bi-directionally changing in YAML and form).
My testing included but was not limited to the following apps: chartmuseum, grafana, artifactory, wordpress, etc. 

For each app I configured them via YAML and switched back to form. I entered various custom content into the YAML to ensure I would always get a warning when switching back to the form view. I upgraded them via Form and YAML each. Testing as also done where I launch an app just via the form and later upgrade via YAML view.

I did not observe any issues during my testing and launching / upgrading the apps worked without any issues. I tried to test every different way I could think of.

The UI test plan will be updated around this area and improved as well.
Note: While testing I did spot an unrelated issue when add a newline to YAML. This is tracked here: #20249
