### ISSUE TITLE
the canal not work when i upgrade rancher to v2.1.7

### ISSUE THREAD

**Issue by wuchencm** [rancher/rancher#19091]
*Describe your issue here*

![image](https://user-images.githubusercontent.com/14210543/54821052-188e3600-4cdc-11e9-8f93-3b1360cc87a0.png)
![image](https://user-images.githubusercontent.com/14210543/54821078-2ba10600-4cdc-11e9-9c07-f3792cbc0a75.png)
![image](https://user-images.githubusercontent.com/14210543/54821152-53906980-4cdc-11e9-941b-7389c0300a8a.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.7` UI: `v2.1.21` |
|Route|`containers.index`|

**Comment by deniseschannon** [comment]
We need a lot more information in order to assist you. 

Can you please fill out the template that exists when you file an issue from the Rancher repo?



**What kind of request is this (question/bug/enhancement/feature request):**


**Steps to reproduce (least amount of steps as possible):**


**Result:**


**Other details that may be helpful:**


**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):



**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```
