### ISSUE TITLE
rancher 2.x catalog cache

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#19118]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement / feature request

**Steps to reproduce (least amount of steps as possible):**
Rancher catalog seems to cache chart by version number
Update question.yaml without chart version and publishing chart again.
Rancher catalog refresh not  picking up latest change. You must change chart version number.

**Result:**
In early phase of chart development, it is may not get everything right. It ends up of many version of same chart.

It would be great if Rancher catalog cache refresh and reload chart by looking at individual chart created timestamp and reload.

**Comment by erikwilson** [comment]
We cache and lazy load catalog stuff as much as possible to keep things fast. 

The best route for development would be using helm command-line, or use a custom git catalog, or delete the disk cache on the server as a last resort.

**Comment by erikwilson** [comment]
Sorry, disk cache thing is only for v2.2, catalogs have been refactored. 

Best development route here is really helm command-line and git catalogs.

**Comment by erikwilson** [comment]
And... you probably are using git catalogs since you are using questions.yaml. Not sure if you have had a chance to try out the 2.2 RCs but they may have better behavior for development & refreshing git.

**Comment by erikwilson** [comment]
Also, for testing Rancher UI questions.yaml helm command line isn't very helpful, really need git catalog refreshes to work. Please let me know if you have any problems with this in 2.2 @panho66

**Comment by zbialik** [comment]
So is there no way to forcefully clear the catalog cache?

**Comment by jaczie** [comment]
We are experiencing the same issue on 2.3.5. Why this issue was closed?

Our scenario:
Build and push package with version X.Y.Z e.g 0.0.1 to project catalog
Reindex repo in the repo
Refresh catalog in rancher
Delete pushed package from the repo
reindex repo
refresh catalog
change Helm manifests e.g. dependencies list in requirements.yaml
build and push packages after changes again with the same version as before X.Y.Z e.g 0.0.1
reindex repo
refresh catalog
try to deploy app again in rancher:

- expected result: new package definition will be visible in rancher

- current result: old package version will be displayed/deployed

**Comment by throrin19** [comment]
@erikwilson  How to use git catalog ? I found nothing in the documentation. 

To test charts we have to use charts without cache. If I understand, the solution is to use git catalog. How to do this ?

**Comment by erikwilson** [comment]
It might be best to open a new issue.
If you are using html indexes then increment the version of the chart.
To use a git catalog set the git url for the location.

**Comment by dorsany** [comment]
@erikwilson any chance to add new button to forcefully clear the catalog cache?

**Comment by erikwilson** [comment]
It shouldn't be needed?
I am not in charge of these decisions tho, please open a new issue as a feature request if you think it is a necessity.

**Comment by dorsany** [comment]
@erikwilson why to open a new git issue if we have this one?
We need a way to forcefully clear the cache of the catalog. at least you can  expose a rest api route to perform this by using http post request

**Comment by erikwilson** [comment]
Why hijack someone else's different issue when your own more specific issue can be created?

The issue is old and closed (for over a year!), so no exposure to anyone other than me or the people on this thread.
The person who originally filed the issue has not responded and presumably the git repo problem has been resolved.
Requests or problems are being brought up that are outside the scope of the original issue.

**Comment by dorsany** [comment]
> Why hijack someone else's different issue when your own more specific issue can be created?
> 
> The issue is old and closed (for over a year!), so no exposure to anyone other than me or the people on this thread.
> The person who originally filed the issue has not responded and presumably the git repo problem has been resolved.
> Requests or problems are being brought up that are outside the scope of the original issue.

here: https://github.com/rancher/rancher/issues/27717
