### ISSUE TITLE
Monitoring - user can delete apps for monitoring from the App list 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19170]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
- enable cluster/project monitoring (in my case it is proejct monitoring)
- notice that the app is launched
- delete the app from the list
<img width="1431" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/54961571-7e6a0000-4f1e-11e9-9c0b-85449012650c.png">

**Result:**
Notice that the app is deleted successfully, but the monitoring is still on the `enabled` state. 

**Expected Result:**  
Should we consider either 
- forbid user from deleting the apps from the list directly   
or 
- turn the montoring off when the app is deleted by user 
or
- add some visual enhancements to notify user not to delete the app

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.0-rc14
- Installation option (single install/HA): single install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cjellick** [comment]
as part of 2.3 system chart refactoring, we improve this with validation and indication

**Comment by cjellick** [comment]
can this be worked around by enable/disable?

**Comment by cjellick** [comment]
@jiaqiluo cann you validate teh work around?

**Comment by materemias** [comment]
beware though it may have side-effects like #19209

**Comment by cjellick** [comment]
Thinking about this some more, I do not think we should just completely disable the ability to delete apps if they are from the system-charts catalog. We don't know the user's intention here. I think at most we should warn or disable at the UI level only.

**Comment by davidnuzik** [comment]
@n313893254 could you please make a small change to en-us.yaml? `systemChartNote`

Please change translation key string to:
`'You are removing a system app. It may cause issues with the cluster if it is removed.'`

**Comment by n313893254** [comment]
Sure

**Comment by davidnuzik** [comment]
Version: master-head (7/30/19)

This change notifies the user, which follows one of the recommendations of what is expected in the issue description "add some visual enhancements to notify user not to delete the app"

This was if necessary, the user is still able to delete the app, but now there will be a clear warning when attempting to delete a system chart app.

To validate, I enabled monitoring and istio. I attempted to delete the three apps:
![image](https://user-images.githubusercontent.com/45179589/62156328-a815a800-b2bf-11e9-8e03-da8a3d52c347.png)

For each I get a warning message for the modal popup prompting for confirmation:
![image](https://user-images.githubusercontent.com/45179589/62156359-b794f100-b2bf-11e9-9cab-f23c3c99ee93.png)

I confirmed I can still Delete if I so wish or cancel out of the modal.

Last, I created my own app from the library to ensure that I do NOT get the message for it (since it's not a system chart app this works as expected).
![image](https://user-images.githubusercontent.com/45179589/62156444-e0b58180-b2bf-11e9-99db-d365cf20452d.png)
