### ISSUE TITLE
GDNS Entry-Broken links when user has access to GDNS entry that points to a MCAPP which has targets he does not have access to.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#19174]
Rancher server version - v2.2.0-rc15

Setup:
Seup has 3 clusters.
Cluster1 
Cluster2  
Cluster3 - testuser2 is cluster owner and project member for "default" project.  

Steps to reproduce the problem:
As admin user , Create a MCAPP1 with targets from Cluster1/Default , Cluster2/Default .
Add `testuser2` as owner of MCAPP1.

Create a GDNS entry pointing to MCAPP1 and add `testuser2`  as owner.

Log in as `testuser2`.
Add Cluster3/Default as another target to MCAPP1.

View GDNS entry.

<img width="1309" alt="Screen Shot 2019-03-25 at 7 01 12 PM" src="https://user-images.githubusercontent.com/4266958/54966182-b4b07b00-4f30-11e9-816d-396868a2f890.png">

When accessing the broken links , there is an attempt made  to launch the project view that fails as expected and user is taken to the log in page.

**Comment by davidnuzik** [comment]
Note: This was tested and is now working in v2.2.2-rc1 per https://github.com/rancher/rancher/issues/19369#issuecomment-479718901 I will do a check again in latest master later to validate again for v2.3

**Comment by davidnuzik** [comment]
(Cannot validate at this time, blocked by #19676 )

**Comment by davidnuzik** [comment]
I validated this again in Master (4/17/19) in order to validate again for v2.3.

_Setup:_
Seup has 3 clusters.
Cluster1
Cluster2
Cluster3 - testuser2 is cluster owner and project member for "default" project.

Steps to reproduce the problem:
- As admin user, Create a MCAPP1 with targets from Cluster1/Default , Cluster2/Default .
- Add testuser2 as owner of MCAPP1.

- Create a GDNS entry pointing to MCAPP1 and add testuser2 as owner.

- Log in as testuser2.
- Add Cluster3/Default as another target to MCAPP1 (Upgrade the app)

- View GDNS entry

Now, we can see the projects we do not have access to in the UI. When you hover over these projects you just see the projectid and a message indicating you do not have permission.
