### ISSUE TITLE
UI: Windows 1809 Support Alpha

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19176]
UI for https://github.com/rancher/rancher/issues/19173

* Windows Options should be disabled unless users are using k8s 1.14 or above version and selected Flannel as network provider.

* Users should be able to choose `Host Gateway` or `VXLAN` mode as  `Flannel Backend`

* `VXLAN` should be the default backend mode

* Users should be able to configure `Node Name` and labels.

![image](https://user-images.githubusercontent.com/21168270/57172076-bf263480-6e4d-11e9-9900-9bc08cd44625.png)

* When deploy new workload (no support for edit), users should be able to choose if deploy to linux or windows nodes only.

**Comment by sangeethah** [comment]
@loganhz Could you list all the UI changes that have been done for Windows 1809 Alpha Support ?

**Comment by loganhz** [comment]
@sangeethah added in the issue detail

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/6/19)

- Windows Options should be disabled unless users are using k8s 1.14 or above version and selected Flannel as network provider.

Confirmed that you must have BOTH Flannel Network Provider picked and v1.14.x Kubernetes Version in order to be able to Enable Windows Support. If you don't have both of these picked, there is a helpful message in the UI "Available for Kubernetes 1.14 with Flannel network provider."
![image](https://user-images.githubusercontent.com/45179589/57252218-7fec1500-7000-11e9-8c21-6b715226b13d.png)

- Users should be able to choose Host Gateway or VXLAN mode as Flannel Backend

Confirmed that if you have picked the "Enabled" radio button for Windows Support, then and only then does a new option come up "Flannel Backend" allowing you to pick with radio buttons either "Host Gateway (L2bridge)" or "VXLAN (Overlay)"
![image](https://user-images.githubusercontent.com/45179589/57252416-dd806180-7000-11e9-8e02-15e76b0de49d.png)

- VXLAN should be the default backend mode

Confirmed, VXLAN (Overlay) is the default.

- Users should be able to configure Node Name and labels.

Confirmed I could set my node name and various labels. The name worked and I can see my labels under node details.

- When deploy new workload (no support for edit), users should be able to choose if deploy to linux or windows nodes only.

I successfully brought up a couple of clusters with windows worker nodes via Custom cluster option. On this cluster I was able to create workloads for linux only (nginx, etc) and workloads for windows only (orstar/webserver:iis-1809) using the UI option for each respectively as pictured below. You can also see that there is a warning for when you have 1 or more windows workers regarding the Host Port.

![image](https://user-images.githubusercontent.com/45179589/57253928-c479af80-7004-11e9-8725-dd7304e7adf1.png)

![image](https://user-images.githubusercontent.com/45179589/57253968-e5420500-7004-11e9-9583-83c1fabbcbe0.png)

Further testing in this area (Experimental Windows) will be continuing as we test v2.3. This issue validated these UI additions and the proper use of labels. I also validated HTTP/API for each new option
