### ISSUE TITLE
UI: Firefox Issues

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19184]
Version: v2.2.0

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
> There are a few minor styling / placement issues when using FireFox.
- Create a project. Expand the "Container Default Resource Limit" pane. Notice that CPU Reservation is in the wrong area:
![image](https://user-images.githubusercontent.com/45179589/55014549-6474ff80-4fa8-11e9-809b-504072de0ae8.png)

>In some but not all required fields, Firefox seems to add a red border around required fields. This would seem to indicate that in html not all fields are actually required. I am having a hard time finding a tag or anything though to prove this.
- Create a secret or config map or certificate. The boxes are red. If firefox highlights required boxes as red, why are they not red everywhere in the product? For example required fields when creating clusters do not show up with red borders.
![image](https://user-images.githubusercontent.com/45179589/55014838-ec5b0980-4fa8-11e9-8999-39cf4a6369b6.png)
![image](https://user-images.githubusercontent.com/45179589/55014855-f3821780-4fa8-11e9-8579-fd09a6dd00f8.png)

**Result:**
These minor issues make the UI look different in FireFox.

**Related:**
#19101

**Comment by westlywright** [comment]
I have a fix for item 1.

The root cause of item 2 is pretty simple, the text-area inputs have the required attribute on the HTML element. I am not sure why this was added but has been present for some time. The required attribute is used when doing form validation with via HTML forms only. It has accessibility features as well. I believe in most evergreen browsers it causes the accessibility screen reader to announce the field is required. Firefox implements the spec differently than chrome and automatically changes the presentation of the field. I believe the reason we don't use the required HTML attribute everywhere is that we do form validation via the JS and not HTML forms so having the required field accomplishes nothing in that regard. There is another attribute, aria-required, which brings the accessibility features without the field presentation modification. If a user is using a screen reader the required fields will be still be announced. 

I think we should break this portion out into a separate ticket, the scope of addressing this is going to be pretty large. We should implement the aria-required tag on all required fields in the UI and remove any of the HTML required attributes because we're not utilizing the validation features of the attribute. We have a standard indicator of required fields denoted by the red `*` that looks the same across all browsers.

@vincent99 do you have any thoughts on item 2?

**Comment by vincent99** [comment]
You can probably just style `:required` [CSS selector](https://html.spec.whatwg.org/multipage/semantics-other.html#selector-required) to not be red in firefox for now.

If anything, longer term we should probably be going through and applying `required` in the element consistently.  Possibly instead of using `{{field-required}}`, there's nothing tying that to whether it's _actually_ required and no easy way to do that.

**Comment by westlywright** [comment]
Oh that's not a bad idea! Thanks. I'll do that for the firefox fix but I agree, longer term we need to add some indicator to the actual inputs that are required on the element. I was wondering if there would be anyway to integrate this into the store somehow? If the field has a required attribute on its models schema then we automatically add it to the input. Not sure if that is worth investigating though. Seems like the extra JS overhead might not be worth it.

**Comment by vincent99** [comment]
Yes, you'd have to annotate the input to know what field it is or what shcema it's for.  Or have a generic `{{schema-input type="pod" field="name"}}` type thing and have that lookup the schema and output the appropriate `{{input-...}}` component.  This is probably only slightly net-negative vs the typical label/field-required/input- setup and could cleanup some other things (like there's already mapping of model field names to display strings for error messages, but they're only sometimes used, because there's a different version of those strings for the form already.  Most forms could just use the standard model field name mapping)

**Comment by davidnuzik** [comment]
Version: Master (4/11/19) ImageID: 0d755e769e77

Confirmed this is fixed in firefox.

Item1 is fixed and I can change the browser window size and it works regardless of dimensions.
![image](https://user-images.githubusercontent.com/45179589/55989063-45d66000-5c5a-11e9-9541-d500176a741d.png)

Item2 is fixed. I do not see the red border (browser doesn't think is required fields now) when creating secrets/config maps.
Longer term we may want to change this across the product? And what is the intended behavior -- these should indeed be `:required` I would think. For now, this is working correctly.
