### ISSUE TITLE
cron jobs cannot use private registries

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#19234]
After having added a private registry, I am able to pull and run images from this registry, when deploying a standard pod using option `Scalable deployment of x pod`. 

If I try to deploy a cron job using the same image from the same registry, in the same namespace, it appears rancher doesn't use registries credentials for this registry and doesn't start container, displaying error:

```

Warning | Failed | Failed to pull image "MYREGISTRY/MYIMAGE:2.9.0": rpc error: code = Unknown desc = Error response from daemon: Get https://MYREGISTRY/v2/MYIMAGE/manifests/2.9.0: denied: access forbidden

Warning | Failed | Error: ErrImagePull
```

Here is a capture from a "classical" deployment:

![image](https://user-images.githubusercontent.com/11064123/55110862-670e4c80-50af-11e9-987f-3a64c6d5128a.png)

And capture from "cron" deployment of the same image a few seconds later:

![image](https://user-images.githubusercontent.com/11064123/55111019-c9ffe380-50af-11e9-83b0-2ff60e88f32a.png)

Cluster info:

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0` UI: `v2.2.19` |
|Cluster info|GKE - 1.13.4 |

**Comment by blackholegalaxy** [comment]
Tried to reproduce today on our company cluster and it does the same thing under 2.1.7

**Comment by leodotcloud** [comment]
@blackholegalaxy I am not able to reproduce the issue.

Tried with version v2.2.0 and v2.2.4 and it works as expected.

Steps followed:
  - Add Registry for private image access (Selected: Available to a single namespace)
  - Create a cron job (every minute) using private image: leodotcloud/swiss-army-knife-private
  - I see the cron job pods being created successfully every minute.
  - Repeat the above steps in a different namespace and the pods fail to start as expected since I had used the Registry for a single namespace.

Can you please capture the network traffic and see if the "imagePullSecrets" field is being set?

<img width="1678" alt="Screen Shot 2019-08-20 at 12 01 50 PM" src="https://user-images.githubusercontent.com/19392926/63376629-20add880-c343-11e9-878f-9b2cd85e80d3.png">
<img width="1583" alt="Screen Shot 2019-08-20 at 12 03 50 PM" src="https://user-images.githubusercontent.com/19392926/63376631-20add880-c343-11e9-825d-e331d6bcdfb9.png">

**Comment by blackholegalaxy** [comment]
I will provide you some more debug information today. In summary, we managed to get it working with private dockerhub registry. But with custom registry (like gitlab one): it works on deployments but not on cron jobs.

**Comment by leodotcloud** [comment]
@blackholegalaxy Please ping me on https://slack.rancher.io, I would like to do a screen share and debug further as it's not reproducible on our end.

**Comment by leodotcloud** [comment]
Related: https://github.com/rancher/rancher/issues/18408. 

@blackholegalaxy can you please check how the registry secrets are created in your Rancher setup? Are they created using the UI or `kubectl`? If you click on "View in API" and inspect the content, you would be able to find the difference. The ones created using `kubectl` would show `"type": "namespacedDockerCredential",`.

**Comment by blackholegalaxy** [comment]
I stil didn't have time to involve in a slack discussion. I use the UI to create the registry secret. I don't do anything by kubectl.

**Comment by leodotcloud** [comment]
@blackholegalaxy Let me know when you are able to reproduce the issue, would be happy to debug.

**Comment by leodotcloud** [comment]
@blackholegalaxy were you able to reproduce the problem? If not, can we close this issue?

**Comment by blackholegalaxy** [comment]
We updated on 2.3.0 version and it seems the problems is not there anymore so we can close this :)

**Comment by borgez** [comment]
i have same problem on 2.4.8 when image pull from deployment all ok when from cron auth pull fail
