### ISSUE TITLE
Internal mysqld error

### ISSUE THREAD

**Issue by pyle** [rancher/rancher#1925]
Issue is after running the rancher master for roughly 2 weeks the master container has produced this error, this causes the container to be in a constant state of restarting.
```
150829  7:35:46 [ERROR] Incorrect integer value: '1000000000000000000000000000000000000000000000000000'
150829  7:35:46 [Warning] option 'max_connections': unsigned value 0 adjusted to 1
150829  7:35:46 [ERROR] /usr/sbin/mysqld: Error while setting value '1000000000000000000000000000000000000000000000000000' to 'max_connections'
150829  7:35:46 [ERROR] Aborting
```
Upon restarting the container it will continue to add zeros to the connections integer value.

The error before this happens says 
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ee315000, 109740032, 0) failed; error='Cannot allocate memory' (errno=12)
```

The host this is ubuntu14.04 on Hyper-V with a static 1GB of RAM
The master manages 2 environments 
Env1: 1x Ubuntu docker host; 1x rancherOS host (both local network)
Env2: 1x Ubuntu docker host (digital ocean)

**Comment by vincent99** [comment]
@cloudnautique the sed matches every time and adds another zero:

https://github.com/rancher/rancher/blob/2579ab99e195cf734d5a99c37abfa41bd86281e9/server/artifacts/mysql.sh#L58

**Comment by ibuildthecloud** [comment]
Most definitely a bug.  @pyle The easiest way to fix this is to upgrade `rancher/server` because it will reset the `/etc/mysql/my.cnf` file which is malformed now.  If you are running the latest, you can even just do an upgrade to the same version.  Docs are here: http://docs.rancher.com/rancher/upgrading/

The memory issue is still something we are working on.  Should be much better in the latest release (currently RC), but there are still some bad situations we are working through.

**Comment by pyle** [comment]
Thanks @ibuildthecloud , all up and running again.
