### ISSUE TITLE
UI: validate cloud credential is present for node template

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#19275]
Issue:
This validation was done before at api level for known node drivers (azure, ec2, do, vsphere), but now needs to be done from UI side to avoid breaking api changes. 

https://github.com/rancher/rancher/issues/19219

PR to remove this check from api: https://github.com/rancher/rancher/pull/19270

**Comment by westlywright** [comment]
The validation for the cloud credential id is now done in the UI for DO, EC2, Azure, and VMWare

**Comment by davidnuzik** [comment]
Version: Master (4/4/19) ImageID: 10a1ef90fcbd
Confirmed the UI now blocks creation of node templates unless you fill out and provide a cloud credential. This affects Azure and vSphere mostly (they show node template before getting cloud key, which is by design).

The UI now shows `A cloud credential is required` when you attempt to create an Azure or vSphere node template without providing a cloud credential. This is not possible with ec2/do by design those ask for your cloud key before you may fill out node template.

This was also validated in v2.2.2-rc1 in issue #19335
