### ISSUE TITLE
Backport: Project edit view has missing name of AzureAD group added to it

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19307]
backport  https://github.com/rancher/rancher/issues/18425

**Comment by loganhz** [comment]
Available in master and ui tag 2.2.31

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1

- Create any cluster. Enable Azure AD Auth.
- Edit a project (such as Default, does not matter) Add an Azure AD group to members list such as Project member. Save.
- Edit that project again. Now you'll see the issue -- the group name is blank as pictured below.
![image](https://user-images.githubusercontent.com/45179589/55516644-ad6d2980-5622-11e9-81d6-14ac114f3462.png)


**Verification Steps:**
v2.2.2-rc1

- Create any cluster. Enable Azure AD Auth.
- Edit a project (such as Default, does not matter) Add an Azure AD group to members list such as Project member. Save.
- Edit that project again. Now you'll see the issue IS FIXED as pictured below we see the group name:
![image](https://user-images.githubusercontent.com/45179589/55516684-cece1580-5622-11e9-837c-808ce00ed803.png)


Ignore that you see a different project owner in the first screenshot. That was a unique project that I had tested with before for another issue. I remove that user,  created a new project and still replicated in v2.2.1
