### ISSUE TITLE
Backport: Monitoring: Should not allow 1 node cluster with only 1vCPU to enable monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19311]
backport https://github.com/rancher/rancher/issues/19078

**Comment by loganhz** [comment]
@davidnuzik Added as resolved as it is merged. But please verify it when we cut a RC release. We will add a `to-test` label when it is ready

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication steps:**
v2.2.1
- Create a 1-node 1 vcpu cluster such as with DO RKE
- Try to enable monitoring with the default settings
- Monitoring does NOT work -- insufficient vCPU for all the necessary pods/containers. (#19078 issue description explains in more detail, 1050milliCPU is minimum required with defaults as of v2.2.1) prometheus-cluster-monitoring will have insufficient cpu

**Validation steps:**
v2.2.1-rc1

_Scenario A:_
- Create a 1-node 1 vcpu cluster such as with DO RKE
- Try to enable monitoring with the default settings
- UI will not allow you to enable monitoring now and has a warning message explaining why. Cannot click Save button. (This is perfect!)
![image](https://user-images.githubusercontent.com/45179589/55501605-a41e9580-55ff-11e9-84a3-1851df8bb2f5.png)

_Scenario B:_
- Create a 1-node 2 vcpu cluster such as with DO RKE
- Add workloads that make CPU reservation so we are just barely shy of having 1200 milliCPU available.
- Try to enable monitoring with the default settings
- Again, just like in Scenario A, UI will not allow you to enable monitoring and has the same warning message explaining why. Cannot click Save button. (This proves that we are checking how many milliCPU we have upon attempt to enable monitoring and disallow if only have 1199 milliCPU or less).
![image](https://user-images.githubusercontent.com/45179589/55501605-a41e9580-55ff-11e9-84a3-1851df8bb2f5.png)
- Now, remove workloads so we have just barely more than 1200 milliCPU available
- Enable monitoring - UI lets us and monitoring works.

_Scenario C:_
- Create a 1-node 2 vcpu cluster such as with DO RKE
- Try to enable monitoring with the default settings
- We are allowed to enable monitoring (I used default settings) because we have at least 1200 milliCPU available out of the box. Monitoring works.

**Comment by davidnuzik** [comment]
Test plan updated to include this 1200milliCPU check.
