### ISSUE TITLE
Backport: Monitoring is crippling the cluster (very high load avg), scraping at 3200 metrics/second

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19316]
backport: https://github.com/rancher/rancher/issues/19248

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher v2.2.1
Setup: 
- Rancher is installed on 3 nodes; each node is an AWS EC2 t2.xlarge instance(4 vCPU, 16 GB Memory)
- Besides of the `local` cluster, I also add an EC2 cluster(3 nodes, t2.medium) an imported RKE cluster (3 nodes, t2.medium)

Steps for each cluster:
- use the `top` command to track the CPU usage of the process running `kube-apiserver` on each node before enabling cluster-level monitoring
- enable cluster-level monitoring
- keep tracking how the CPU usage changes

Result:
- in the `local` cluster, it observes that the `kube-apiserver` uses a significant amount of CPU after enabling cluster-level monitoring. the change is roughly from 4% ~ 5% to   20% ~ 60% 

The CPU usage of the process running `kube-apiserver` before and after enabling cluster-level monitoring 

Cluster Type | before | after
------------ | ------------- | -------------
EC2 cluster | 2 - 3% | 3 - 6% 
Imported RKE cluster | 2 - 3% | 5 - 8%
Local cluster | 4% ~ 5% | 20 - 60%
--------------

The bug fix is validated in Rancher v2.2.2-rc1 by using the same configuration and repeating the same steps to test in Rancher v2.2.2-rc1. 

Result:
- All three kinds of clusters are using a reasonable amount of CPU resource before and after enabling cluster-level monitoring.  
- For the `local` cluster, the CPU usage changes from 4% - 5% to 5% - 8%

The CPU usage of the process running `kube-apiserver` before and after enabling cluster-level monitoring 

Cluster Type | before | after
------------ | ------------- | -------------
EC2 cluster | 6 - 8% | 4 - 8%
Imported RKE cluster | 1 - 2% |  1 - 4%
Local cluster |4% - 21% |   4 - 28%

The CPU usage of the `local` cluster after enabling the cluster-level monitoring
<img width="1333" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55513805-7ba49480-561b-11e9-9840-7aa6ca651611.png">
