### ISSUE TITLE
Backport: UI: validate cloud credential is present for node template

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19335]
Backport https://github.com/rancher/rancher/issues/19275

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
Related: #18731

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1
- Try to create do/ec2/azure/vsphere node templates without any cloud credentials. (azure and vsphere are the ones that had the issue before due to how they are designed)
- Not possible with any, UI blocks this `Validation failed in API: Cloud Credential must be set is required`

**Validation Steps:**
v2.2.2-rc1
- Try to create do/ec2/azure/vsphere node templates without any cloud credentials. (azure and vsphere are the ones that had the issue before due to how they are designed)
- Not possible with any, UI blocks this with a different message now `A cloud credential is required`
