### ISSUE TITLE
Backport: Custom node driver says active but template fields don't immediately show up

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19330]
Backport https://github.com/rancher/rancher/issues/19066

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1

- Add a custom node driver such as https://mxschmitt.github.io/ui-driver-hetzner/
- The driver will download and activate
- Try to add a node template for it -- notice it does not appear to actually be ready - icon is missing and if you click on it you will see the following (no UI)
![image](https://user-images.githubusercontent.com/45179589/55510038-2e6ff500-5612-11e9-9b7e-338680fc7578.png)

**Validation Steps:**
v2.2.2-rc1

- Perform the exact same steps as above but with v2.2.2-rc1
Issue still occurs.

**Comment by alena1108** [comment]
Can be tested with rancher/rancher:v2.2.2-rc2

**Comment by davidnuzik** [comment]
Version: v2.2.2-rc2

The issue is now resolved.
- Add a custom node driver such as https://mxschmitt.github.io/ui-driver-hetzner/
- The driver will download and activate
- Try to add a node template for it -- notice it NOW appears ready right away. The UI for it loads right away without any issues. The icon shows up.

Add node template screenshot:
![image](https://user-images.githubusercontent.com/45179589/55573973-1ce52680-56c0-11e9-8cda-8c21cb3cd804.png)
