### ISSUE TITLE
Backport: Monitoring crashes on 2.2.0RC-13

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19343]
backport https://github.com/rancher/rancher/issues/19145

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by davidnuzik** [comment]
**Replication Steps:**
v2.2.1

NOTE: It's not easy to reproduce what was reported in the #19145 issue because we need rather large clusters (possibly larger than we can reasonably test with). So I am basically confirming that there is no way to customize node exporter memory in this version. This should be sufficient. Refer to my comment here for details - we had a hard time reproducing but agree that this is an important issue and can be reproduced such as in a large production environment: https://github.com/rancher/rancher/issues/19145#issuecomment-479670302

- Created a cluster
- Enabled monitoring
Note, there is no option to set the memory limit for the node exporter. Thus in this version you can run into the issue of running out of memory for the node exporter.
The default was 50MB max memory limit and 30mb memory reservation. Could not be configured without manually editing the workload in this version.

**Validation Steps:**
v2.2.2-rc1

- Created a cluster
- Enabled monitoring
Note, we now have options to set the node exporter memory limit upon enabling monitoring:
(Default options pictured)
![image](https://user-images.githubusercontent.com/45179589/55515807-58c8af00-5620-11e9-81cb-fafd66e78b7b.png)
I changed these settings (both the cpu limit and memory limit) and ensured they will restart the appropriate pods in the workload to update changes. In my case I had two nodes and so both pods in the exporter-node-cluster-monitoring workload were updated to reflect my new memory limit and cpu limit settings for the node exporter. inspect HTTP looks correct as well.
Note, look in the containers themselves to see the updated memory limit and cpu limit.
