### ISSUE TITLE
Backport AzureAD and Local Auth broken after 2.2 Upgrade

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19346]
Backport https://github.com/rancher/rancher/issues/19202

**Comment by alena1108** [comment]
Can be tested on rancher/rancher:v2.2.2-rc1

**Comment by sangeethah** [comment]
Able to reproduce the issue  in the following case:

1. When testing with Fresh install of v2.2.1
Try to enable AD auth (Service account password has ":" in it).
Not able to enable auth and user is presented with error message that secret was not found.

2. Fresh install of v2.1.8 . 
Enable AD auth (Service account password has ":" in it).
Create few clusters and give access to some user - say "user1" to one of the clusters.
Upgrade to v2.2.1

After upgrade , no AD users( including the admin user is able to log in ) and following errors are seen:
```2019/04/04 00:04:11 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: can't find authprovider```

This issue is not reproducible with v2.2.2-rc1 in following 2 cases:

1. With Fresh install of v2.2.2-rc1:
Try to enable AD auth (Service account password has ":" in it).
Able to enable AD auth successfully and also able to log in to rancher server as other valid AD users.

2.1. When testing with Fresh install of v2.2.1
Try to enable AD auth (Service account password has ":" in it).
Not able to enable auth and user is presented with error message that secret was not found.

2. Fresh install of v2.1.8 . 
Enable AD auth (Service account password has ":" in it).
Create few clusters and give access to some user - say "user1" to one of the clusters.
Upgrade to v2.2.1

After upgrade , no AD users( including the admin user is able to log in ) and following errors are seen:
```2019/04/04 00:04:11 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: can't find authprovider```

Upgrade to v2.2.2-rc1
After upgrade , all AD users are able to log in successfully.
