### ISSUE TITLE
How do I run Rancher on GKE/AKS/EKS type services?

### ISSUE THREAD

**Issue by raazcrzy** [rancher/rancher#19385]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
need documentation help

**Result:**

**Other details that may be helpful:**
I want to deploy rancher in GKE as a statefulset. I could not find any documentation related to it. The motive behind statefulset, is to make the data persistent. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:2.2.1
- Installation option (single install/HA): single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.11.2

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by alena1108** [comment]
@raazcrzy just curious - when you say "to make the data persistent" for Rancher, do you have any special data in mind?

**Comment by jgreat** [comment]
Kubernetes StatefulSets are used in situations where pod startup order and consistent naming are important, they don't really do anything to make a service "stateful".

Since the Rancher management server pods are actually stateless (state is stored in the hosting kubernetes cluster) using a StatefulSet instead of a Deployment has no benefit.

### The real question here is "How do I run Rancher on GKE/AKS/EKS type services?"

Rancher embeds deeply into the K8s cluster that its running on and manages workload clusters as k8s objects.  You can technically run the Rancher chart and install onto these service, but due to operational limitations **we don't currently support running Rancher on hosted K8s solutions**.  We are working on options to make this possible.

#### Some of the operational concerns:

These services tend to be a black box when it comes to etcd operations. Rancher relies on the ability to do etcd snapshots for backup, restores and rolling back the database state on failed upgrades. Etcd endpoints are not available for monitoring and the limitations of the etcd services are not published so its pretty much impossible to know the health of the Rancher database when installed on these services.

**Comment by superseb** [comment]
Running on hosted k8s is tracked in https://github.com/rancher/rancher/issues/16627

**Comment by flaccid** [comment]
Not intending to necrobump, but thought it was worth mentioning that v2.5 now allows you to run on any k8s cluster with backup/restore, see https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/.
