### ISSUE TITLE
Backport: Prometheus error when installing Monitoring

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19380]
Backport https://github.com/rancher/rancher/issues/19278

**Comment by thxCode** [comment]
@jiaqiluo  https://github.com/rancher/rancher/issues/19326#issuecomment-479814459

**Comment by alena1108** [comment]
Can be tested with rancher/rancher:v2.2.2-rc2.

@sangeethah this issue is not easy to reproduce. Lets just run a regression test for monitoring, and also test the case when monitoring is enabled on 2.2.1, and then once upgraded to 2.2.2, things still work.

**Comment by jiaqiluo** [comment]
followed the suggested steps outlined by @thxCode https://github.com/rancher/rancher/issues/19326#issuecomment-479814459
1. Enable Cluster Monitoring -> the monitoring dashboards should be on
2. Disable Cluster Monitoring -> the monitoring dashboards should be off
3. Enable Cluster Monitoring and then drop cattle-prometheus/prometheus-cluster-monitoring Pod -> the monitoring dashboards should be off until Prometheus Pod redeploy

The bug is reproduced in Rancher v2.2.1
For step 3:
When the pod is deleted the cluster page misses some values (see the CPU wheel) and cannot show metrcis in tabs.
<img width="1642" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55582497-853e0300-56d4-11e9-8c38-64ddb4a3b1d7.png">
After the pod is recreated, I need to refresh the page manually to get it recovered. 


The bug fix is validated in Rancher v2.2.2-rc2
For step 3:
When the pod is deleted the cluster page switches back to the classic view without showing any error messages which we saw in v2.2.1
<img width="1399" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55582110-815db100-56d3-11e9-9a7f-ec38d1487563.png">

As soon as the pod is recreated, the cluster page looks like this:
<img width="1388" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55581782-9d148780-56d2-11e9-9098-0cf826d55ae6.png">

Then the wheel metrics go back to classic view after 3 - 5 seconds:
 
<img width="1434" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55581791-a271d200-56d2-11e9-8015-d4e71393d53b.png">

Now if I refresh the page manually, it recovers to the desired view:
<img width="1392" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55581855-c3d2be00-56d2-11e9-83d6-02fb217de9ef.png">

**Comment by jiaqiluo** [comment]
Tests on monitoring are finished in Rancher v2.2.2-rc2 throughout.
Wait for a new RC to test upgrading.

**Comment by jiaqiluo** [comment]
Instead of waiting for a new RC, the upgrading testing is done in the path v2.2.1 to v2.2.2-rc2

Steps:

- add one EC2 cluster, one EKS cluster, one AKS cluster, and one GKE cluster in the Rancher v2.1.1
- enable both the cluster moinitoing and proejct monitoring in each cluster
- check monitoring working as expected
- upgrade Rancher to v2.2.2-rc2
- check monitoring still works in all clusters
- turn on amd off monitoring to make sure it works 

This issue is closed. New issue will be made if necessary.
