### ISSUE TITLE
Backport: A previous error message not cleared on the UI when another error message is displayed

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19401]
Backport: rancher/rancher#19377

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: v2.2.3-rc1

I carefully followed the steps to reproduce and now only one error is shown at a time. The previous error is very quickly blanked out before showing the next error (the 401 AuthFailure) error due to invalid credentials replaces the previous error. This is now working as expected.
