### ISSUE TITLE
UI: Expose some additional Rancher GlobalDNSProvider parameters

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#19425]
We will expose some new parameters for "route53" and "cloudflare" GlobalDNSProvider objects, in the API.

The corresponding backend issue is https://github.com/rancher/rancher/issues/19251

Need UI changes to add these parameters on the UI.

**Comment by alena1108** [comment]
Backend is ready in `rancher/rancher:v2.2.3-rc1`

**Comment by jira-sync-svc** [comment]
➤ wes commented:

PR Contains new params to validate 

https://github.com/rancher/ui/pull/2934 ( https://github.com/rancher/ui/pull/2934 )

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Version: Master (4/26/19)

I can see the new options and validated them all (HTTP). QA does not have accounts to test cloudflare/ali.

The HTTP looks correct as does the API. I can see that cloudflare proxy option is now of type bool rather than string. The HTTP req payload and server response appear correct. Tested create/edit/delete.

**Comment by davidnuzik** [comment]
This was originally not tested correctly; I have checked again after reviewing the PR and commit.

Version: master (4/29/19)

All fields are working correctly except for zone. The UI appears to be sending in the request payload the following when I put in a custom zone string in the Zone field for Route53 config:

```
zone: "myzone"
zoneType: "public"
```

I think the problem is that UI sends just "zone" instead of "zoneType" when I inspect server response it does not mention "zone". Further, this is not in the schema.

Last, we need to determine what are the possible options for "zoneType" I may be wrong but I think these are only "public" and "private" so then should this not instead be radio buttons? We may want to ask Alena about this.

Otherwise, the other fields all seem to work as expected.

Cloudflare is also working except for the Proxy option which has a separate issue already entered to track that https://github.com/rancher/rancher/issues/19251

**Comment by davidnuzik** [comment]
One additional thing. value for zone is helper text not as a value - my guess is that this is just because of the mixup (zone versus zoneType)

**Comment by westlywright** [comment]
Comments pertaining to this issue for <2.3 are here https://github.com/rancher/rancher/issues/19833#issuecomment-488466409

**Comment by davidnuzik** [comment]
Version: Master (5/3/19)

I can now confirm zoneType is working as expected in the UI. As Wes mentioned in v2.2.3 issue this also fixes the issue where the default value was not being filled in in the field.

This completes testing of the added params in route53ProviderConfig (and cloudflare). See comment https://github.com/rancher/rancher/issues/19425#issuecomment-488043649 above for my prior notes. I also fuzzed data in these fields to validate types, etc. Defaults look good.
