### ISSUE TITLE
Monitoring - Enabling monitoring and switch to other page will cause an UI error

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#19423]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- enable the cluster level monitoring of any cluster
- switch to any other page, for example, going to another cluster, while the monitoring is deploying 

**Result:**
It will show the error as the screenshot shows:
<img width="1498" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55658593-0370d700-57b3-11e9-9866-4f5b750c1a41.png">

**Other details that may be helpful:**
The issue does not happen every time, so I am not sure the exact steps to reproduce it, but it is related to the action of enabling cluster monitoring 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.2-rc2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jiaqiluo** [comment]
I met the bug when I switch from the Cluster/ Project config page to the Global page in v2.2.2-rc5

**Comment by alena1108** [comment]
Can be tested in `rancher/rancher:v2.2.2-rc7`

**Comment by davidnuzik** [comment]
v2.2.2-rc7
Validated this issue. I tested with a few clusters (as the issue did not always happen). I tried to follow steps to reproduce and tried switching to other clusters, etc as cluster monitoring is still provisioning. I did not encounter the issue. I also tried navigating from the cluster monitoring config page to the main global page (/g/clusters).

I am going to continue testing in this area and if I happen to run into the issue will immediately re-open this issue. However, based on my testing done thus far I think it's pretty safe to say the issue is indeed resolved.
