### ISSUE TITLE
Support User Data / Cloud Init for AWS Node Templates

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#19449]
**What kind of request is this (question/bug/enhancement/feature request):** feature request

The title says it all.

However, specifically since Rancher has Rancher OS and the primary way of configuring it is to use UserData/Cloud-Init, I believe this should be a first class supported item.

**Comment by gillarda** [comment]
I don't know if you noticed but you can send some userdata to AWS iinstances, however :
- It is not supported in the UI so you need to use the API
- For AWS, the userdata has to be in a file on the Rancher instance. (We use a configmap to do so)

I think the later is because Rancher uses Docker Machine behind the scene to provision the AWS instances, and Docker Machine only supports the use of files for userdata.

This is not the easiest nor the cleanest way, but it works.
