### ISSUE TITLE
ui-pl was reset during upgrade to 2.2.1

### ISSUE THREAD

**Issue by roycec** [rancher/rancher#19446]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Install e.g. Rancher-HA 2.1.6
- Configure ui-pl in settings to custom value
- Upgrade Rancher to version 2.2.1

**Result:**
Value in ui-pl again contains 'Rancher'

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.1
- Installation option (single install/HA):
HA

**Comment by roycec** [comment]
In the same context I found another thing: When I open the catalog page in Global -> Tools -> Catalog the text below displays 

**Official repository of curated application templates maintained by ecp.**

I changed ui-pl in the settings to 'ecp'. I think this should display 'Rancher'.

**Comment by tfiduccia** [comment]
@roycec - 
1.  I was not able to reproduce the ui-pl issue when upgrading to 2.2.2.  If you see this issue again, please reopen.
2.  Removing the text Rancher is by design.  We will not display the text Rancher anywhere once ui-pl has been modified so user can work to 'customize' the product for their purposes.  As an admin you can disable the Library catalog and prevent users from enabling it.
