### ISSUE TITLE
Upgrading from 2.1.8, eks cluster api is getting wrong k8s version

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#19458]
Version - v2.1.8 upgraded to v2.2.2-rc4

**Steps to reproduce (least amount of steps as possible):**
1.  Install rancher v2.1.8 (I did just a single node install)
2. Add a EKS cluster (go to amazon and verify k8s version, should be 1.12)
3. Upgrade to version v2.2.2-<latest rc>
4. View k8s in UI and API for upgraded eks cluster 

**Result:**  1.10 (unsupported) is selected.  If you go to amazon, you will see the version is still 1.12.

**Comment by sangeethah** [comment]
This seems to be very similar to the issue - https://github.com/rancher/rancher/issues/18390

**Comment by jiaqiluo** [comment]
Following the same steps as the issue provides but upgrading from 2.1.8 to 2.2.2-rc5, seeing that 
- in the upgraded setup Rancher UI shows the correct k8s version
<img width="1425" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55764924-4684b180-5a22-11e9-9df7-772c1ecf4bb6.png">
<img width="1477" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55764949-61572600-5a22-11e9-84a8-4f5c50ca4d9f.png">

- viewing in API, there is a new filed added called `kubernetesVersion`, but its value is not correct: it shows 1.10 but expected to be 1.12
<img width="1590" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55764999-8ba8e380-5a22-11e9-9bcb-bf99a118e57f.png">

- go to edit the cluster, the default value of the `Kubernetes Version` option shows 1.10(unsupported) which is bad
<img width="1436" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/55765063-d6c2f680-5a22-11e9-87ef-fbc3caa0966a.png">

**Comment by jiaqiluo** [comment]
The fix for those two issues I mentioned in my previous comment https://github.com/rancher/rancher/issues/19458#issuecomment-481055002  is validated on Rancher v2.2.2-rc6 upgraded from v2.1.8

**Comment by davidnuzik** [comment]
Version: v2.1.8 -> Master (4/15/19)

I also validated with v2.1.8 to latest master update and can confirm this is now working as expected.
When I look in the UI 1.10 (unsupported) is no longer selected when I attempt to edit the EKS cluster post-upgrade. I can save without making any changes to the EKS cluster and it will not do anything (as expected). I checked this because this was an issue previously and wanted to make sure we don't have regression of that issue (cluster updating even if no need to). This is working correctly.

![image](https://user-images.githubusercontent.com/45179589/56154610-cd2f1680-5f6d-11e9-90c2-9071a2452396.png)
