### ISSUE TITLE
Kubelet not starting in Custom Rancher cluster -> Amazon provider

### ISSUE THREAD

**Issue by rborsaru** [rancher/rancher#19462]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Rancher 2.x on AWS. 
We are now trying to set up a Custom rancher cluster, by selecting Amazon as the cloud provider. 

**Result:**
When we try to execute the command we get from Rancher UI to start Rancher agent  in our AWS – E2 server, we are noticing that kubelet container is failing to startup. The error its displaying is as below

F0408 00:58:45.614181   15011 server.go:261] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0b8d20a2b09480f42: "error listing AWS instances: \"RequestError: send request failed\\ncaused by: Post https://ec2.ap-southeast-2.amazonaws.com/: dial tcp 52.119.211.206:443: i/o timeout\""

**Other details that may be helpful:**
If we setup the cluster ignoring the cloud provider type - Amazon, the setup is successful and we can use it. But in that case if we want to setup a Load Balancer we get "LoadBalancer stuck in Pending" error. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.1.7
- Installation option (single install/HA):
single install
AWS with three EC2 nodes. Selecting custom type cluster and cloud provider as Amazon.
We have followed the pre-reqs required for this kind of setup - AWS role and labels.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
The hosts need to be able to reach EC2 to look up required information, are you in a proxied environment or any other network restrictions outside or on the host (firewall)?

**Comment by rborsaru** [comment]
Thanks for the reply. We are in a private cloud, firewalled from Internet. But the three hosts -master and two workers are all in the same subnet.
Is there any way to check the network restriction?

**Comment by rborsaru** [comment]
I have tried something different. This might give some more information about this problem.
I selected new cluster and instead of custom selected 'From nodes in an infrastructure provider' option and Amazon EC2 from there. 
Then selected the add node template button, added region and aws key pair and clicked next. After a long wait got a 502 null error message.
Any idea?

**Comment by superseb** [comment]
Is it only firewalled or also proxied? Connectivity check is basically something like

```
curl -s https://ec2.$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document|grep region|awk -F\" '{print $4}').$(curl -s 169.254.169.254/latest/meta-data/services/domain) -v
```

You need to open connectivity to AWS as it needs to query resources in AWS as being the cloud provider.

**Comment by vidyanair** [comment]
Hello,
I am facing the the same problem.
Creating a custom cluster from Rancher UI ->Chose Amazon as cloud provider -> Rancher UI would provide the command to run in existing instances.
Copied that command and executed in ec2 instance where docker is installed.
Kubelet container failed to start, it keeps restarting.
error listing AWS instances: "RequestError: send request failed\ncaused by: Post https://ec2.ap-southeast-2.amazonaws.com/: dial tcp 


I am in private subnet and access to internet is through proxy.
I am able to reach AWS(https://ec2.ap-southeast-2.amazonaws.com/) from EC2 instance using my proxy.

But somehow kubelet which is started in rancher agent is not using the proxy setting.
I have HTTP_PROXY and HTTPS_PROXY in /etc/systemd/system/docker.service.d/http-proxy.conf.
Also I tried to pass proxy variables as env variables to command copied from rancher UI.

Would you please advise where should I include proxy settings so that kubelet can use it?

**Comment by superseb** [comment]
To provide the proxy configuration environment variables, you can follow https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-add-additional-arguments-binds-environment-variables-to-kubernetes-components-in-a-rancher-launched-kubernetes-cluster

**Comment by superseb** [comment]
Let me know if this still needs help

**Comment by vidyanair** [comment]
Hi @superseb ,

Thanks a lot, you are a saviour.
As you said, I have added the proxy details as env variables to each service.
I spent may hours in googling where to include the proxy, the document above is hidden somewhere from googlers.

Cheers,
