### ISSUE TITLE
Using a FQDN in CATTLE_AGENT_IP results in Network Agent restart/errors

### ISSUE THREAD

**Issue by bymodude** [rancher/rancher#1946]
when I register a Host with CATTLE_AGENT_IP=rancher1.example.com it seems to work mostly ok however the Network Agent instance container starts to constantly restart due to the erro shown below

my rancher hosts are cloud servers and their IPs change when they are recreated etc., hence I am trying to use DNS to register these hosts instead of hardcoding IPs, is this even supported? 

```
[scripts.sh:164] /usr/sbin/setkey -f content-home/etc/cattle/setkey
libipsec: invalid IP address while parsing "rancher1.example.com"
line 7: Name or service not known at [ out ipsec esp/tunnel/172.17.0.20-rancher1.example.com/require]
parse failed, line 7.
[scripts.sh:165] '[' -e /var/lib/cattle/etc/cattle/setkey ']'
[scripts.sh:168] return 1
[config.sh:1] cleanup
[config.sh:9] EXIT=1
[config.sh:11] '[' -e /var/lib/cattle/download.iXW1W1h ']'
[config.sh:12] rm -rf /var/lib/cattle/download.iXW1W1h
[config.sh:15] return 1
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot

```

**Comment by fentas** [comment]
Maybe the same issue as rancher/rancher/issues/1940?

**Comment by fentas** [comment]
After short thinking, i figured, what you are trying to do is that `rancher/server` recognizes the restarting host as the same before?  Hm. Could be potentially nice. That `rancher/server` recognize that the new host is actually an old one and could be used for dealing with host failures (#1877).

This could also be solved with an unique token. @ibuildthecloud What about the possibility to set an unique token on host registration and if this token is used for a new registration `rancher/server` can replace the reconnecting host?

**Comment by vincent99** [comment]
Re-registering a host does recognize it as the same host as before because there is a UUID in /var/lib/rancher/state (`ls -al`, it's a dot-file).

Your error message above indicates it failed setting up the IPSec tunnels for the Rancher overlay network.  It requires an IP Address, not a hostname, because what the hostname resolves to can change at any time and would have to be constantly re-checked (and then what happens with existing tunnels to the old IP, etc).

**Comment by bymodude** [comment]
@vincent99 
I don't think anyone would expect an existing IPSec tunnel connection between two IPs to change when the IP of a hostname is changed, DNS lookups of the hostname are usually only used during initial connection time. 
My usecase are rancher hosts on Azure, when I change the VM Size (e.g. from 3.5GB RAM VM to 7GB VM) Azure assigns a new IP, the VM hostname however stays the same and is updated with the new IP by Azure automatically. The VM Size change requires a VM reboot, at that point the IPSec tunnels are lost anyway. Instead of Rancher trying to re-establish the tunnels between the IPs it would be nice if it would merely do a DNS lookup to get the IP when trying to establish the connection again.  

Re-registering ("docker rm" all rancher agent containers, then run the "docker run.." from add host command again) never worked for me, always some error which solution was to delete /var/lib/rancher/state.

**Comment by ibuildthecloud** [comment]
I could imagine that we could support a FQDN for CATTLE_AGENT_IP.  How that would work is that we essentially resolve the hostname to an IP and then report that to the server.  Then on an interval check the DNS to see if it changed.  The only problem we have right now is that changing the host IP is not completely dynamic.  When you change the host IP, after Rancher detects the changed IP, you have to manually restart the network agent.  If we got that process to be dynamic, we could support a hostname.

**Comment by ibuildthecloud** [comment]
@bymodude As a work around for your use case what you can do is add a script on start (maybe cloud-init) that runs the host registration command.  You just need to determine your IP on start using either `ip addr` or Azure's API if the IP is not locally bound, or just resolving the hostname to an IP.

The host registration script can be ran over and over again with different IPs.  If there is an existing `rancher-agent` container it will just delete the existing agent and create a new one.  If the IP the host is reporting changes it will be reflected in Rancher.  The "identity" of the server is kept in `/var/lib/rancher/state` as @vincent99 mentioned, so as long as you keep that directory the VM will always register as the same host.

The only catch, as I mentioned before, is that when the IP changes you must restart the network agent.  In your case, since you are rebooting the VM, it might just work.  If it doesn't we can probably fix it pretty easily.

**Comment by bymodude** [comment]
thanks for the suggestion, I will try the workaround, although if I could eventually specify a hostname as CATTLE_AGENT_IP it would also be great

**Comment by ibuildthecloud** [comment]
@bymodude In the next release setting `CATTLE_AGENT_IP` to a hostname will be supported.  On each agent ping we do `gethostbyname(${CATTLE_AGENT_IP})`.  I believe this will satisfy your use case.

**Comment by sangeethah** [comment]
Tested with server version - v0.37.0-rc4.

I am able to use fqdn as the CATTLE_AGENT_IP , when registering the host.
Host get added successfully and is in "Active" state.

Able to launch containers and the Network Agent container stays up. 

@ibuildthecloud , The one issue I see is that the ip address of the agent get registered as local ip address - 127.0.1.1 , in case of a Digital Ocean machine. So there is no cross host communication possible.

I am not able to override the ip address using /etc/host entry in the host machine , for the public ipaddress to be picked up by the rancher-agent

```
root@test345:~# docker exec -it rancher-agent ping test345
PING test345 (127.0.1.1) 56(84) bytes of data.
64 bytes from test345 (127.0.1.1): icmp_seq=1 ttl=64 time=0.126 ms
64 bytes from test345 (127.0.1.1): icmp_seq=2 ttl=64 time=0.094 ms
64 bytes from test345 (127.0.1.1): icmp_seq=3 ttl=64 time=0.102 ms
^C
--- test345 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.094/0.107/0.126/0.016 ms
root@test345:~# ping test345
PING test345 (45.55.140.8) 56(84) bytes of data.
64 bytes from test345 (45.55.140.8): icmp_seq=1 ttl=64 time=0.102 ms
64 bytes from test345 (45.55.140.8): icmp_seq=2 ttl=64 time=0.061 ms
64 bytes from test345 (45.55.140.8): icmp_seq=3 ttl=64 time=0.060 ms
^C
--- test345 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.060/0.074/0.102/0.020 ms
root@test345:~# 
```

**Comment by deniseschannon** [comment]
With the introduction of CNI and network drivers in v1.2.0, there is no network agent running on hosts anymore. This is no longer applicable. If there are new errors related to the original use case, please re-open.
