### ISSUE TITLE
Set content type if empty for gzipped responses

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#19507]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Open rancher using firefox browser
2. Enable monitoring for a cluster
3. Navigate to that cluster

**Result:**
Error messages caused by failure to parse JSON.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2-rc8

**Comment by rmweir** [comment]
https://github.com/rancher/rancher/pull/19497 issue first acknowledged

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.2.2-rc8. 
Following the same steps as the issue describe, notice that 
- two error messages show in the UI
- the `GET https://your-url/c/c-xxxx/monitoring` response header does not set the content types. 
<img width="459" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/56169116-fd88ac00-5f91-11e9-8ffe-7470407d39ef.png">


The bug fix is validated with Rancher: master 4fd2548
Following the same steps as the issue describe, notice that 
- no error message
- the `GET https://your-url/c/c-xxxx/monitoring` response header contains the content types: `Content-Type: text/html; charset=utf-8`
