### ISSUE TITLE
Disable Project Monitoring in 2.2.2

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19514]
Due to stability issues, we are going to temporarily disable project monitoring in 2.2.2. We are going to fix them in the next scheduled maintenance release, and re-enable the feature back.

@sangeethah as a part of testing, we have to:

* Make sure it's disabled in the UI
* All project monitoring related actions (enablemonitoring, disablemonitoring) are disabled for project object in the API
* Previously enabled monitoring (on 2.2.0, 2.2.1) should be disabled on the projects after upgrading to 2.2.2

**Comment by alena1108** [comment]
Can be tested on `v2.2.2-rc9`

**Comment by jiaqiluo** [comment]
The issue is validated on v2.2.2-rc9 upgraded from v2.2.1 with the following scenarios

Case 1
Before upgrading    
 - cluster1 -> cluster monitoring enabled,     
|-project1 -> project monitoring enabled, deploy a workload which exposes a custom metrics
|-project2 -> project monitoring NOT enabled         

 - cluster2 -> cluster monitoring NOT enabled    
|-project1 -> project monitoring enabled     
|-project2 -> deploy some workloads    

After upgrade:     
- cluster1 -> cluster monitoring still work
 - cluster1 project1 -> project monitoring option is gone from the UI, related app and workload are deleted, existing workload still work     

 - cluster2 -> can enable cluster level monitoring
 - cluster2 project1 -> project monitoring option is gone from the UI, related app and workload are deleted,
- cluster2 project2 -> workloads still work
 
----

Case 2
Before upgrading
- create cluster3, project1, project2, project3
- assign user1, user2, user3 as the following roles  
- check RBAC related cases in the test plan work as expected 

 ... | cluster3 | project1 | project2 | roject3
------- | -------- | ---------- |--------- |--  
User1 | member | owner | member |  none
User2  | none | owner | member | none
User3 |  owner   | none   | none    | none

After upgrading 
- check RBAC related cases in the test plan still work as expected 

-------

Case 3
Before upgrading    
 - cluster1 -> cluster monitoring NOT enabled
|-project1 -> project monitoring enabled

After upgrade:  
- project monitoring option is gone from the UI,
-  related app and workload in the project are deleted, 
- the app `monitoring operator` in system project is deleted

**Comment by jiaqiluo** [comment]
Update 1: 

The issue is also validated in a freshly installed setup v2.2.2-rc9
All RBAC tests and complex scenarios are tested

Also tested the monitoring API in the upgraded setup. The issue is tracked here: https://github.com/rancher/rancher/issues/19528

**Comment by jiaqiluo** [comment]
Update 2: https://github.com/rancher/rancher/issues/19516
