### ISSUE TITLE
Backport:UI: When go to Cluster Monitoring Configuration, enable but don't save UI shows is Enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19601]
https://github.com/rancher/rancher/issues/19402

**Comment by davidnuzik** [comment]
I followed the steps and tested again like I did with Master in issue #19402 

Version: 2.2.3-rc4

The UI has been tweaked a bit on the Cluster Monitoring Configuration page so that it is now more in alignment with how the UI looks in similar areas. The Disable/Enabled buttons at the top-right have been removed. Now when you set up monitoring for the first time you will see this button to enable it at the bottom of the page:
![image](https://user-images.githubusercontent.com/45179589/56158021-cad0ba80-5f75-11e9-89b3-669c6a0e1e01.png)

And once it is enabled it changes to a normal "Save" button.

When cluster is enabled you will now see a red "Disable Monitoring" button at the top-right of the page.
![image](https://user-images.githubusercontent.com/45179589/56158089-fa7fc280-5f75-11e9-8e26-b61a1c4c7015.png)

Click it once to get a prompt to click it again. When you click it again it will disable monitoring.
![image](https://user-images.githubusercontent.com/45179589/56158134-15523700-5f76-11e9-8052-0b2c402c025a.png)
