### ISSUE TITLE
Backport:New Monitoring Prometheus PVC doesn't work with OpenEBS

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19609]
https://github.com/rancher/rancher/issues/19410

**Comment by loganhz** [comment]
can be tested after https://github.com/rancher/rancher/issues/19610 is ready for test

**Comment by loganhz** [comment]
in rc7

**Comment by davidnuzik** [comment]
I am closing this issue, it has effectively already been tested here: https://github.com/rancher/rancher/issues/19610#issuecomment-490294425
This is because when I validate the UI I ensure the API appears to be working correctly as well.

Using the release name makes the names stay under 63 chars and as such should resolve the OpenEBS issue originally reported.
