### ISSUE TITLE
Creating settings on startup not working

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19705]
See https://github.com/rancher/telemetry/pull/19#issuecomment-484263244

Looks like we somehow broke a use case for settings.

possibly related to changes made in this pr
https://github.com/rancher/rancher/pull/17960/files

**Comment by jira-sync-svc** [comment]
➤ Craig Jellick commented:

fixes the telemtry issue referenced in er-173

**Comment by jira-sync-svc** [comment]
➤ Jack Luo commented:

The bug is reproduced in Rancher v2.2.2
Steps:

  * run rancher container
  * when setting the password, do not check the for collecting anonymous data
  * check the page url/v3/settings to confirm that the variable telemetry-uid does not exist
  * run the following command

curl -k -u your-token -X POST -H 'Content-Type: application/json' -d '{"name":"telemetry-uid", "value": "foo"}' <https://url/v3/settings/>Result:

  * the command returns failure

The bug fix is validated in Rancher: master and v2.2.3-rc1
Following the same steps as before, and see the variable is created and its value is set to foo as expected.
