### ISSUE TITLE
Long-term data storage and querying from Prometheus data

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#19726]
What kind of request is this (question/bug/enhancement/feature request):
Feature Enhancement

Steps to reproduce (least amount of steps as possible):
We're using the Prometheus services built into Rancher 2.2, but in Prometheus' docs, there are several mentions of Prometheus' storage not being durable or recommended for more than an 'ephemeral sliding window'. Phrases like "If your local storage becomes corrupted for whatever reason, your best bet is to shut down Prometheus and remove the entire storage directory." and "Prometheus's local storage is not meant as durable long-term storage." make me nervous to store long term data there. We would like a way to store and report on metrics from Prometheus over longer terms (as in years)

Environment information

Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI):
2.2.1

Installation option (single install/HA):
HA

gz#4071

**Comment by deniseschannon** [comment]
When enabling monitoring there is a specific section for enabling persistent storage: 

<img width="336" alt="Screen Shot 2019-04-25 at 2 55 23 PM" src="https://user-images.githubusercontent.com/11410997/56770987-3c74e980-676a-11e9-8111-b586e8a43599.png">

There are also docs on this. 

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/prometheus/#persistent-storage

**Comment by ankur111** [comment]
Talked to the customer and the issue isn't about just enabling persistent volume.  
It is about corruption of prometheus when the volume if full.

**Comment by stenwt** [comment]
Sorry, the original issue wasn't clear - Prometheus' documentation itself says: "Prometheus's local storage is limited by single nodes in its scalability and durability. Instead of trying to solve clustered storage in Prometheus itself, Prometheus has a set of interfaces that allow integrating with remote storage systems." 

Prometheus recommends several options for external backends: 
https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations

There are also a few projects that intentionally provide roll-up archiving and more durable storage for Prometheus, while still maintaining the same interfaces for e.g. Grafana, Alertmanager: 

https://github.com/cortexproject/cortex

https://github.com/improbable-eng/thanos

We'd like to see something like this integrated to the product.

**Comment by isaacsanders** [comment]
It would be awesome to see something like Cortex or Thanos implemented.
