### ISSUE TITLE
Catalogs cannot handle commas in your passowrd

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#19737]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install a Catalog App with an automatically generated helm chart

**Result:**
Sometimes, a password may be generated with invalid characters in it, like `,`

When this happens, you will get the error message:
```
Helm template failed. Error: failed parsing --set data: key "gA92nmfSK" has no value (cannot end with ,) : exit status 1
```

where the password generated was `lhmn,gA92nmfSK`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2
- Installation option (single install/HA): doesn't matter

**Comment by loganhz** [comment]
Which catalog app? I guess we can fix it in the chart as `valid_chars ` works for password.

Related PR https://github.com/rancher/ui/pull/2505

**Comment by Oats87** [comment]
@loganhz this is a custom catalog app

**Comment by vincent99** [comment]
That's a perfectly valid random password, being not escaped properly somewhere along the line.  Answers should be able to have a comma in them.

**Comment by fgeorgatos** [comment]
i also think character `#` gets mishandled. 

Could someone from the rancher team (@cjellick ?) state if such passwords are meant to be supported?

**Comment by cjellick** [comment]
Yep, meant to be supported. We can address as part of this bug.

**Comment by dramich** [comment]
https://github.com/helm/helm/issues/1556

**Comment by dramich** [comment]
The issue comes from the helm parser splitting on commas when using the --set command as we do. So our command looks something like `--set "a=b,c=d` which is fine but if you include a comma in the value the parser breaks. Well, you can quote the pairs and escape all the commas but now something that _should_ work in helm, won't. For example the lists `a={a,b,c}` they allow for [set](https://github.com/helm/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set). So this fix needs to take all of this into account - quoting the pairs and escaping commas but only when they should be escaped and won't break set.

**Comment by cjellick** [comment]
Let's limit to escaping commas (and other prolematic characters) when WE generate passwords.
Lets add a general UI note that reference the fact that users must escape commas in their own answers. https://rancher.com/docs/rancher/v2.x/en/catalog/apps/?origin_team=T02RW4JDH#configuration-options

**Comment by bmdepesa** [comment]
rancher/rancher:master-head bc3700f8

* Reproduced in v2.2.7
  * Deploy wordpress app with a comma in the password
  * Wordpress fails to deploy
* Deploy Rancher master
* Create cluster
* Deploy wordpress app with a comma in the password
* The app deploys successfully
