### ISSUE TITLE
Backend is pulling system images from private registry even though cluster registry is not set to default registry

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#19734]
Version: Master (4/19/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- In the UI, create any RKE cluster and add a private registry
- Use a fake URL, username, and password, leave "System Default Registry" unchecked
- UI will POST to create the cluster with the private registry not set to default (so shouldn't pull system images)

**Result:**
The cluster will fail to provision because ClusterController appears to be attempting to pull system images even though this is not the default registry.

Error in rancher server logs:
```
2019/04/19 22:27:12 [ERROR] ClusterController c-h7m8t [cluster-provisioner-controller] failed with : [Error checking if image [https://test1.test.com/rancher/rke-tools:v0.1.28] exists on host [IP-ADDRESS-REDACTED]: Error response from daemon: no such image: https:/test1.test.com/rancher/rke-tools:v0.1.28: invalid reference format]
```

Snippet of HTTP POST to create cluster:
```
privateRegistries: [{isDefault: false, type: "privateRegistry", url: "https://test1.test.com", user: "testuser",…}]
0: {isDefault: false, type: "privateRegistry", url: "https://test1.test.com", user: "testuser",…}
isDefault: false
password: "testpassword"
type: "privateRegistry"
url: "https://test1.test.com"
user: "testuser"
```

API confirms is not default registry:
```
privateRegistries": [
{
"isDefault": false,
"type": "/v3/schemas/privateRegistry",
"url": "https://test1.test.com",
"user": "testuser"
}
],
```

**Other details that may be helpful:**
Required fix in order to validate (test) #19325

**Comment by davidnuzik** [comment]
Added triaged label; we need this in JIRA to connect with ER-92

**Comment by jira-sync-svc** [comment]
➤ David Nuzik commented:

Closing this issue and I will remove the blocking links in JIRA. This issue was created due to a misunderstanding. When a private registry is provided when creating a cluster this is for system images. It should always pull system images and we were providing an invalid URL (fake one) so this is completely expected.

The confusion was around another issue that states a non-default registry should not pull system images which is not true. Again, registries provided when creating a cluster are for system images. For non-system images – you should create a registry under the project in Rancher. In a situation where a registry is not default it still gets used if is only entry.
