### ISSUE TITLE
Cadvisor doesn't work properly if you are using a different docker root dir

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#1974]
You get an issue like this:

```
I0904 09:13:50.550699 26630 container.go:242] Failed to update stats for container "/docker/57226857cf0bdbc9c40523ac3668248948e16d001b050f003adca1e55fd383cf": 
stat failed on /var/lib/docker/aufs/diff/57226857cf0bdbc9c40523ac3668248948e16d001b050f003adca1e55fd383cf with error: no such file or directory, continuing to push stats
```

Cadvisor supports specifying a different docker root via: `--docker_root` [heres the PR where they added that](https://github.com/google/cadvisor/pull/204/files) but rancher doesn't pass that option.

This doesn't appear to affect functionality because cadvisor just logs a warning and moves on. Even stats continue to work, but it does spam the rancher-agent logs.

**Comment by joshuakarjala** [comment]
I have the same problem - in Kibana 90% of my logs are rancher-agent complaining about this :(

**Comment by ebr** [comment]
just curious if there's any expected progress on this. We started seeing these messages sometime in the last 2 weeks (with no apparent changes in our stack, but perhaps the rancher agent updated itself as it does automatically). Now this additional logging volume is causing overages in our the hosted log aggregation solution... I'll find a workaround in the meantime, but it would be great to get this fixed.
(at least I *think* the log spam is caused by this issue, since the sample message above matches what we're seeing).
Thank you!

**Comment by deniseschannon** [comment]
No longer using cadvisor as of v1.2.0.
