### ISSUE TITLE
rollback functionality for apps does not work

### ISSUE THREAD

**Issue by drpebcak** [rancher/rancher#19819]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy an App from the catalog
2. Upgrade and change the app's values.yaml in some way that causes it to get stuck trying to deploy (like using a bogus image name).
3. Select Rollback from the Apps UI and try to rollback to the previous revision.

**Result:**
Rollback never happens. It does not create a new revision either.

**Other details that may be helpful:**
Using kubectl to roll back the broken deployment works as expected.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS, Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, m5d.large instances
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by tfiduccia** [comment]
Version - 2.2.2
@deniseschannon - I cannot reproduce this. My steps:
1.  Helm chart has 2 version.  1st version is fine.  2nd version has bad image reference in values.yaml
2.  Deploy 1st version of app (deploys fine)
3.  Upgrade app to version 2 (deploy does not complete because bad image)
4.  Go to app page and select rollback and choose version which used version 1

This all worked for me.

**Comment by tfiduccia** [comment]
@deniseschannon - Sat down with Taylor and got reproducible steps:
1.  Go to launch apps and open redis app
2.  Edit as yaml and change
  master/persistence/enable = true
  password = "abc"
3.  Launch redis app
4.  After it's become active select upgrade from app's menu
5.  change image/repository to "bitnami/redis222"
6.  Upgrade app and wait a couple of seconds, (it won't activate cause image is bad image)
7.  Select rollback from app menu and select the previous revision and Rollback

Results:  A post is send but nothing is actually being posted.  It's empty.  So nothing is actually happening.  

This is only reproducible by modifying the values.yaml directly through the app UI (either using edit as a form or edit as yaml) and not through versioning.

**Comment by daxmc99** [comment]
Maybe we need to clarify how app revisions work? 
I followed the steps here. However, the most recent revision was the *same* as the currently deployed version. While the chart was "bad" since the image repo did not exist helm technically did not fail. There is no way for helm to infer that the image repo does not exist or is unreachable. 
### Testing done:
1. Create redis as above observe deployment as
```
    image: bitnami/redis:4.0.9
```
2. Upgrade with an non-existent repo
```
      image: bitnami/redis222:4.0.9
```
3. Chose the revision *before* the current one. Rancher creates revisions everytime helm is ran so it needs to be the 1st revision. You should see a diff in the UI.  Rollback the app with the revision with the correct bitnami repo 
```
    image: bitnami/redis:4.0.9
```

**Comment by daxmc99** [comment]
Based on a further conversation with the @drpebcak it should be noted that the Redis app will actually fail to deploy even after the chart has been redeployed with a good image repository. This is because the main Redis pod is deployed as part of a stateful set. Stateful sets attempt to minimize disruption and can require manual intervention. 
Per the stateful set  [docs](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations)
- When using Rolling Updates with the default Pod Management Policy (OrderedReady), it’s possible to get into a broken state that requires manual intervention to repair.

Testing should ensure the stateful set has its image repository set correctly on rollback verified via `kubectl describe statefulset redis`

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 4c7e3263a

* Performed steps above and was able to get Redis app in a stuck state
* Rolled back to the previous revision and saw the redis statesful set had the correct image, though not functional
* Deployed some other apps and updated to create revisions, and rolled back successfully. 
* All requests from UI correctly contained a payload
