### ISSUE TITLE
In rancher's private Catalogs Template files are not shown

### ISSUE THREAD

**Issue by S93rastogi** [rancher/rancher#19829]
**BUG**

In case of Rancher the Private Catalogs get added and the private catalogs are also displayed but the helm charts associated to a private catalog can't be accessed. If I select a catalog I don't find the templates files listed.
![image](https://user-images.githubusercontent.com/7479903/56784223-16ecec00-680d-11e9-9566-769f4e6581f6.png)

Incase if we put the same helm chart on a public catalog the templates file get listed. The issue so clearly is with Rancher and not with the helm charts.
I tried to put the helm charts on different private repository like ACR and git private repo and the issue still persists so also the issue with the registry is ruled out. 

**Steps to reproduce:**

- Create a Private App Catalog ( any, but I used ACR )
- Add the app catalog to Rancher by providing the correct Credentials.
- Go and Launch the app
- The helm chart(pushed in prev steps) gets listed.
- Try to go and Launch the App. 

**Result:**
- You find that there is no template files listed (Values.yml,Deployemnt.yml etc are not listed )

**Logs of Rancher Server** 

![image](https://user-images.githubusercontent.com/7479903/56784650-39800480-680f-11e9-848b-229e9061e75d.png)

I get a unsupported Protocol schema error when the chart tries to read the index.yml and then ries to get the *.tar.gz file

The issue seems to be linked to other issues like :  [https://github.com/rancher/rancher/issues/15671](url)

**Comment by xinghui-hou** [comment]
I have a same promblem.
Suddenly one day
![image](https://user-images.githubusercontent.com/10824788/70962812-64320c80-20c1-11ea-9b8d-2bc5b15452c5.png)

![image](https://user-images.githubusercontent.com/10824788/70962835-7b70fa00-20c1-11ea-9985-dff5872dff24.png)

**Comment by onkar-dhuri** [comment]
I am also running into same issue. So, I have an app deployed through custom catalog which was working just fine. The app version was v0.0.1
Today I wanted to have another version so I updated the current version as dev_v1 and prod_v1 in the catalog and pushed it to git.
But this didn't go well with Rancher and it started failing to refresh the catalog giving -
"Error in chart(s): failed <my-template> template version name <catalog>-<template>prod_v1: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')];"
I have updated the master branch to use names like d0.0.1 (for dev) and p0.0.1 (for prod) but it's not able to refresh the repo. Whenever I use master branch it shows the same error as above.
I created a separate branch and the error was gone, however when I go to launch screen, I don't see my app listed there.
Additionally I noticed it requires index.yaml in root directory of helm charts repo which it didn't require before. I tried with both empty and some formatted index.yaml but still no luck.

I am suspecting that after upgrading to rancher (2.4.5) and upgrading to downstream cluster (1.18.3) this issue might have popped again because I see some fixes related to helm repo update after 2.4.4 - #27282  &  #27252
