### ISSUE TITLE
Backport Expose some additional Rancher GlobalDNSProvider parameters

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19833]
Backport rancher/rancher#19425

**Comment by jira-sync-svc** [comment]
➤ wes commented:

Available in v2.2.3-rc3

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc3

All fields are working correctly except for zone. The UI appears to be sending in the request payload the following when I put in a custom zone string in the Zone field for Route53 config:

```
zone: "myzone"
zoneType: "public"
```

I think the problem is that UI sends just "zone" instead of "zoneType" when I inspect server response it does not mention "zone". Further, this is not in the schema.

Last, we need to determine what are the possible options for "zoneType" I may be wrong but I think these are only "public" and "private" so then should this not instead be radio buttons? We may want to ask Alena about this.

Otherwise, the other fields all seem to work as expected.

Cloudflare is also working except for the Proxy option which has a separate issue already entered to track that https://github.com/rancher/rancher/issues/19251

**Comment by davidnuzik** [comment]
@westlywright one additional thing. value for zone is helper text not as a value - my guess is that this is just because of the mixup (zone versus zoneType)

**Comment by westlywright** [comment]
`zone` was a typo on my part it should be `zoneType`. This will fix the default value for zone as well.

If there are only two values for `zoneType` we can implement this in the UI but really the type in the backend should change. If there are only two values the field should be changed to `publicZone` of type `bool`. If there are more than two possible values the type should be an enum with all the possible values as options. @alena1108 @prachidamle Input?

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc5

I can now confirm zoneType is working as expected in the UI. As Wes mentioned this also fixes the issue where the default value was not being filled in in the field.

This completes testing of the added params in route53ProviderConfig (and cloudflare). See comment https://github.com/rancher/rancher/issues/19833#issuecomment-488043283 above for my prior notes. I also fuzzed data in these fields to validate types, etc. Defaults look good.
