### ISSUE TITLE
Backport: Remove redundant "Azure Unmanaged Disk" option from Storage Class dialog

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#19863]
Backport rancher/rancher#19744

**Comment by westlywright** [comment]
Available in `v2.2.3-rc4`

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc7

I can confirm removal of this radio button option. Now instead we have a drop down that let's you select the Kind you would like to specify (as pictured below).

![image](https://user-images.githubusercontent.com/45179589/57409473-384ec000-719d-11e9-8990-99ccdc06f9e5.png)

I validated that the UI is working correctly and successfully provisioned a managed disk. Please note that due to a bug I was not able to validate unmanaged at this time, but this appears to be working correctly from the UI-perspective (UI, API, HTTP). As such I will be closing this issue.

For details around the issue where we cannot create a PVC for a storage class with Azure Disk provisioner, see #19216
