### ISSUE TITLE
[Feature] Support for NGINX-Ingress with static-ip for airgap networks.

### ISSUE THREAD

**Issue by gabrielcalderon** [rancher/rancher#19883]
While testing Rancher in my team's dev network I tried to deploy an ingress with a static-ip and the UI doesn't allow to use IP's. What's the reasoning for this, it's currently supported by nginx-ingress.

NGINX-Ingress tutorial on the topic: https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/static-ip/README.md

Is this supported in Rancher/Via Rancher?

**Comment by vincent99** [comment]
The default nginx-ingress controller is deployed as a daemonset because that's the only reasonable thing that can be done automatically. You then point at any of the worker nodes.

You can create a service of type=LoadBalancer and target the pods of the ingress controller; that's all this example is doing.

But you have to first have a cluster in a provider that supports LoadBalancers.

**Comment by gabrielcalderon** [comment]
@viclncent99 Thanks for the explanation. I will look more into it.
