### ISSUE TITLE
Add Filesystem Type to Storage Class Amazon EBS Disk

### ISSUE THREAD

**Issue by ersutton** [rancher/rancher#19933]
**What kind of request is this:** enhancement/bug

**Steps to reproduce (least amount of steps as possible):**
* Create a storage class on the cluster like so:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/creatorId: user-2ngpd
  creationTimestamp: '2019-05-02T05:53:15Z'
  labels:
    cattle.io/creator: norman
  name: mongo-xfs
  resourceVersion: '552369'
  selfLink: /apis/storage.k8s.io/v1/storageclasses/mongo-xfs
  uid: 6f97ce45-58f9-11e9-816e-1235ca56e877
parameters:
  encrypted: 'false'
  type: gp2
  fsType: xfs
  zone: us-east-1a
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
Provision a volume using this storage class, I used the mongo helm chart.

**Result:**
created volume is still has the default ext4 filesystem.

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.2.2
- Installation option (single install/HA): HA, 2 nodes

**Cluster information**
- Cluster type: Custom (On Amazon us-east-1)
- Machine type: cloud, RancherOS 1.5.1
- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

I am trying to self host a mongo database, and would like to use a storage class that has the `fsType` of xfs.

The kubernetes documents suggests that this is possible:
https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs

The UI does not seem to support either `allowVolumeExpansion` or the parameter `fsType`.

I tried to create my own storage class

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/creatorId: user-2ngpd
  creationTimestamp: '2019-05-02T05:53:15Z'
  labels:
    cattle.io/creator: norman
  name: mongo-xfs
  resourceVersion: '552369'
  selfLink: /apis/storage.k8s.io/v1/storageclasses/mongo-xfs
  uid: 6f97ce45-58f9-11e9-816e-1235ca56e877
parameters:
  encrypted: 'false'
  type: gp2
  fsType: xfs
  zone: us-east-1a
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
However, when trying to use this storage class, the created volumes are still `ext4`.

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.2.2`
Steps:
Provision a storage class with fsType: xfs.

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 3fc6715ca`
There is now a field for fstype:
![Screen Shot 2020-02-07 at 2 12 07 PM](https://user-images.githubusercontent.com/57409052/74195361-493ecd00-4c18-11ea-9490-c876d6785959.png)
Setting fstype to xfs:
![Screen Shot 2020-02-10 at 10 23 44 AM](https://user-images.githubusercontent.com/57409052/74195706-121ceb80-4c19-11ea-9b5f-ff2081508ace.png)
Volume is created successfully using volume class:
![Screen Shot 2020-02-10 at 3 07 34 PM](https://user-images.githubusercontent.com/57409052/74195388-58257f80-4c18-11ea-97cb-98ac3652206f.png)
Workloads can be deployed using the volume:
![Screen Shot 2020-02-10 at 3 20 38 PM](https://user-images.githubusercontent.com/57409052/74195677-00d3df00-4c19-11ea-9b60-9bef8c18799c.png)
