### ISSUE TITLE
Backport Catalog App Upgrade Action Does Not Nullify a Null valuesYaml Field

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19937]
Backport https://github.com/rancher/rancher/issues/19634

**Comment by alena1108** [comment]
can be tested on rc5

**Comment by jiaqiluo** [comment]
The bug is reproduced on Rancher:v2.2.2 following the steps in the issue, and notice that both the valuesYaml or answers properties exist when viewing the app in API.

The bug fix is validated on Rancher: v2.2.3-rc5, notice that only one of those two will exist depending on the choice of `edit as yaml` or `edit as form` when upgrading the app.
