### ISSUE TITLE
AWS private ip impossible to provision elb

### ISSUE THREAD

**Issue by massontom** [rancher/rancher#19948]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** use rancher in a public subnet to deploy kubernetes cluster using EC2s in a private subnet with only **private ips**

**Result:** L4 load balancers are stuck in "pending" status, nothing is created on aws

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): ```> kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}``` 

- Docker version (use `docker version`): 

```
> docker version
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by rsilvasu** [comment]
Hi,
We have the same problem and we have fixed it adding the following annotation to the ELB provision:

service.beta.kubernetes.io/aws-load-balancer-internal: "true" 

The issue is from Kubernetes AWS Cloud Provider, not Rancher.

You can see this on the K8S source code:
https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/cloudprovider/providers/aws/aws.go#L2140
// Determine if this is tagged as an Internal ELB
internalELB := false
internalAnnotation := annotations[ServiceAnnotationLoadBalancerInternal]

**Comment by superseb** [comment]
This was made available in the UI in https://github.com/rancher/rancher/issues/15070
