### ISSUE TITLE
Backport: Rancher 2.2.x cannot remove notify if there is only one

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19967]
Backport https://github.com/rancher/rancher/issues/18616

**Comment by alena1108** [comment]
will be available in rc6

**Comment by davidnuzik** [comment]
Version: v2.2.3-rc6

I can now delete the single notifier in my alert group without any issues.
When I do this I no longer get notifications as expected but the rule keeps firing in the UI, again as expected. In the logs I see removal of monitoring-operator since I only had one group with notifications. I can add the notifier again and will successfully get alerts (notifications) again (it deploys again).

I also tested another scenario, I set up two groups one with a notifier and the second also with a notifier. I set them up so they are both always firing on a quick interval (30 seconds). I deleted my only notifier on one of the two groups and confirmed in logs we do _not_ remove monitoring-operating in this case (since we still need it for my second group that is getting notifications). This is good.

I made sure that I still do not get notifications for that group I removed the notifier from (sometimes 1 more alert can be cached but after that no more alerts). Last, I enabled the notifier on that group and now get notifications from that group again.
