### ISSUE TITLE
Cannot set public ip when use Windows 2019 with host-gateway mode 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19964]
rancher/rancher:master 05/01

Steps to reproduce:

Create a windows cluster with public ip and private ip configured (Input `Public Address` in the node options)

![image](https://user-images.githubusercontent.com/21168270/57127501-32369900-6dc3-11e9-9235-72ceef502a14.png)

Result:

Cannot add the windows node successfuly

![image](https://user-images.githubusercontent.com/21168270/57127580-6ad67280-6dc3-11e9-819b-2fc8229d598c.png)

**Comment by kingsd041** [comment]
Test with rancher/rancher:master(05/10 commit id: 5d74988c) with kubernetes 1.14.1
Fixed in this version
![image](https://user-images.githubusercontent.com/19684717/57498642-3c025400-730f-11e9-838a-9e7261658ce2.png)

![image](https://user-images.githubusercontent.com/19684717/57498649-46245280-730f-11e9-99a0-eb8678a89214.png)
