### ISSUE TITLE
Backport: cloud_provider credentials exposed to lowest privilege users

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19986]
Backport https://github.com/rancher/rancher/issues/19653

**Comment by alena1108** [comment]
can be tested on rc6

**Comment by sangeethah** [comment]
Able to reproduce the issue when testing with v2.2.2

1. Create a Azure cluster with cloud provider.
2. Once the cluster gets to "active" state , edit cluster and use "Edit as YAML" option to see the cluster yml. "aad_client_secret: " under "azureCloudProvider" section is available in clear text.
3. Use "View in Api" option . "aad_client_secret: " (part of "azureCloudProvider") is available in clear text.

This issue is fixed when testing with v2.2.3-rc7.

1. Create a Azure cluster with cloud provider.
2. Once the cluster gets to "active" state , edit cluster and use "Edit as YAML" option to see the cluster yml. "aad_client_secret: " is not present anymore in "azureCloudProvider".
Use "View in Api" option . "aad_client_secret:" is not available as part of "azureCloudProvider" anymore.
3. on edit page, user is not presented with the "aadClientSecret" parameter anymore.
4. Edit cluster ( In my case I disabled recurring snapshots) and "Save". Following error message is presented to the user

<img width="1361" alt="Screen Shot 2019-05-07 at 7 31 28 PM" src="https://user-images.githubusercontent.com/4266958/57345312-39311480-70ff-11e9-8101-0cab983f126f.png">

**Comment by sangeethah** [comment]
Tested with 2.2.4-rc1.
1. Create a Azure cluster with cloud provider.
2. Once the cluster gets to "active" state , edit cluster and use "Edit as YAML" option to see the cluster yml. "aad_client_secret: " present with empty value in "azureCloudProvider".
Use "View in Api" option . "aad_client_secret:" is not available as part of "azureCloudProvider" anymore.
4. on edit page, user is presented with the "aadClientSecret" parameter with no value set.

On cluster edit , user has to re-enter "aadClientSecret".
