### ISSUE TITLE
Registry credentials are not available to alreay provisioned nodes

### ISSUE THREAD

**Issue by cedricziel** [rancher/rancher#2000]
Steps:

1. Provision node
2. Add registry credentials
3. Add image from private registry
4. Image cant be pulled

How to fix:

Remove node and add another one. The new node can pull the image.

**Comment by ibuildthecloud** [comment]
This behaviour is quite odd.  Registry credentials are not related to hosts in any fashion.  For example we don't copy the credentials to the hosts, they are dynamically sent at the time that rancher does an image pull.  The side effect of this is also that if you log into the machine and manually do a `docker pull` it will fail because we do not store the credentials on the host.

Are you sure this wasn't a transient issue?  Is this easily reproducible?  I say this because the way in which we tests credentials is almost exclusively in the situation where the host exists before we add the credential.

**Comment by cedricziel** [comment]
Seems like a heisenbug. It happened in 3 of 10 cases.

**Comment by jmreicha** [comment]
Seeing something similar, maybe the same thing?  On a fresh Rancher install I added two nodes, then added credentials to dockerhub after the servers were provisioned and the rancher-server container logs indicate it can't connect to dockerhub.

I haven't tried killing the nodes and re-adding after adding creds, I will test this tomorrow.

I can post the logs if it helps, or open a new issue of this behavior is something separate.

**Comment by deniseschannon** [comment]
I have been unable to reproduce this. 

Steps I did:
1. Add a node
2. Add credentials on DockerHub
3. Launch a private image
4. Image pulls as expected

Can you provide how you place the image name? Just want to make sure it's following the expected image name. 
http://docs.rancher.com/rancher/configuration/registries/#using-registries

For DockerHub, it expects.

`[namespace]/[imagename]:[version]`

**Comment by deniseschannon** [comment]
Also, are you using an insecure registry or self-signed certificate, if so, there needs to be configuration independently done on the hosts.  This is covered in http://docs.rancher.com/rancher/configuration/registries

@cedricziel If you are still seeing this issue and it's reproducible consistently, please re-open.
