### ISSUE TITLE
2 Prometheus operator get deployed when enable cluster monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20042]
Image: 2.2.3-rc7 / system-chart dev branch

Steps:

1. Create a cluster
2. Enable cluster level monitoring

Results:

2 prometheus operator get deployed in cattle-prometheus ns

Expected:

It should be one operator get deployed

**Comment by jiaqiluo** [comment]
This is what I see on Rancher: master
<img width="1431" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57413593-9386af80-71a9-11e9-84ba-5f305b85bb8b.png">

**Comment by loganhz** [comment]
@jiaqiluo yes, now it's ready for test

**Comment by jiaqiluo** [comment]
the bug fix is validated on Rancher:v2.2.3-rc7 since it is a fix on the chart which is used by both v2.2.3-rc7 and mater

Confirm that when the version of `cluster-monitoring` and `monitoring-operator`  are v0.0.3, there is only one workload named `prometheus-operator-monitoring-operator` under the namespace `cattle-prometheus`

<img width="1396" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/57417639-eae04c00-71b8-11e9-8d07-5d1a84e99efa.png">
