### ISSUE TITLE
Make Restore Snapshot possible across clusters

### ISSUE THREAD

**Issue by DavidBajon** [rancher/rancher#20051]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

The "Restore Snapshot" Feature introduced with Rancher 2.2 can only be used to restore the current cluster with it's registered snapshots. It's not possible to use snapshots saved in a S3 bucket from an other cluster, because they won't be listed.

It would be nice if you could use the "Restore Snapshot" feature across clusters, so that if for some reason it's deleted it can be restored this way. Or an other option would be to create a new cluster from an Snapshop via Rancher 2 UI.

**Comment by JannikZed** [comment]
we have an urgent need for that right now!! we crashed our cluster somehow and need to re-create it. Would be very convenient to just copy and restore the backup through the rancher GUI

**Comment by Jlaird** [comment]
I see a few great use cases for this.

1. Copy prod to test running updates or changes.
2. Easy way to make a stage or testing environment. 
3. Lastly and probably the best, when everything breaks, you can start over.

**Comment by eduDorus** [comment]
I have to agree to the use cases @Jlaird wrote down. We are currently experiencing the same needs

**Comment by rdu** [comment]
The current implementation is pretty useless when really nasty things happen.

I cannot believe I have backup but all my data is lost. My only choice is to recreate the cluster from scratch.

I tried to overwrite a local snapshot with my backup. It seemed to be restored but sadly the cluster won't startup. (I believe because the cluster id is different) Is it possible to change this id?

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/23645
