### ISSUE TITLE
UI-language dropdown position is below the page

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#20053]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Click language dropdown

**Result:**

![image](https://user-images.githubusercontent.com/18737885/57372442-449c4280-71c8-11e9-8f93-909d90bde03c.png)

5/8/2019 master

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/8/19)
I also checked v2.2.3-rc7 to make sure it is not affected and it is not.

I confirmed this is fixed in the latest master. The UI-Language dropdown position is now upwards like it used to be and working normally.

![image](https://user-images.githubusercontent.com/45179589/57393119-4853a900-7177-11e9-8359-cb8d63d4100e.png)
