### ISSUE TITLE
cluster unavailable for no reason

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#20102]
BUG/REPORT
v2.2.2 Ubuntu 16.04 Docker 17.04
------------
One of our production cluster ( Provider: Custom
Version: v1.11.6
Nodes: 52
CPU: 660 Cores
Memory: 2.9 TiB
Created: 01/13/2019 )

went unavailable for no reason after running for months. I couldn't find any errors even after going through pretty much every log I could find.
The only hint was that there hasn't been any logs in etcd node 2 since days.

Rebooting the VM that carries master2 /etcd 2 solved the problem (albeit still no logs in etcd2)

Obviously this is unacceptable. What's the point of having a HA setup when everything goes unavailable just because apparently 1 node has an issue (I still don't know why though, docker and system logs gave me nothing). 
Given other posted similar issues before "cluster unavailable after node reboot" I'd urge the rancher team to do better testing (in general).

Also for this issue: If you got ideas where to look, I will. Rancher Master didn't have anything in the logs either that seemed relevant.

**Comment by superseb** [comment]
Please provide the information requested in the issue template (see https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions why that is important).

Providing logging always helps at least in confirming something was working at that time vs finding anything that root causes the issue directly so posting logging is always helpful. If it narrows down to that single node, system logging also helps to see since when it stopped logging and if that could be related to anything on the system.

**Comment by superseb** [comment]
Let me know if you can supply the requested info so we can investigate.
