### ISSUE TITLE
Add in logic to upgrade system-charts branch

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#20115]
Logic needs to be added as we cannot add to the `master` branch for the system-charts repo as this will impact users running on v2.2.0-v2.2.3. 

v2.2.4 will ship with a new system-charts branch as to avoid that impact. 

Upgrade Scenarios to Test:
```
1. Launch v2.2.3
2. Upgrade to  v2.2.4 - Confirm that the branch for the system-charts repo is updated to new branch. 
3. Roll back to v2.2.3 - Confirm that the branch for the system-charts repo is updated to `master`
```

```
1. v2.2.3 and enable cluster monitoring 
2. Upgrade to v2.2.4 -  Confirm that the new cluster monitoring chart is available.
3. Upgrade cluster monitoring
4. Roll back to v2.2.3 - Confirm that the cluster is running the old cluster monitoring chart. 
```

```
1. v2.2.3 and enable cluster monitoring and change the defaults to new values.
2. Upgrade to v2.2.4 -  Confirm that the new cluster monitoring chart is available.
3. Upgrade cluster monitoring
4. Roll back to v2.2.3 - Confirm that the cluster is running the old cluster monitoring chart and the updated values from default.
```

```
1. v2.2.3
2. set the system-chart branch and url to custom values.
3. Upgrade to v2.2.4 - Confirm system-chart branch and url DO NOT change
```

```
1. Fresh v2.2.4 setup
2. Set the system-chart branch and url to custom values.
3. Restart rancher -confirm the system-chart branch and url values do not change
```

**Comment by cjellick** [comment]
## Background information:
Reason we need this change: we can potentially introduce new system-chart versions that are incompatible with older versions of rancher. In the long term, we are going to address this by adding support for `min_rancher_version` and `max_rancher_version` to charts. But that will not hit until v2.2.4 and v2.3.0. Once we do that, we can just have one generic branch called `release`.

So, for v2.2.3, we need a solution that will effectively lock rancher v2.2.3 to a specific branch of the system-chart catalog.

FYI, "rolling back" means reverting to a pre-upgrade snapshot of etcd, not just downgrade rancher. See https://rancher.com/docs/rancher/v2.x/en/upgrades/

This is where we add the system-chart catalog: https://github.com/rancher/rancher/blob/master/app/catalog_data.go#L27-L30 Note that the branch and url are hardcoded, but they are just populated an entry of the catalog CRD. So, you can change what the catalog points to after rancher starts by updating the catalog entry. You should be able to update it in the UI for v2.2.3. Prior to v2.2.3, you had to update it via the api (see https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/config-rancher-system-charts/#b-configure-system-charts)

### Implementation details:
We need to move the system-chart url and branch from hard-coded constants to environment variables set in the [server's dockerfile](https://github.com/rancher/rancher/blob/master/package/Dockerfile). These values should then just be read in the catalog_data.go file mentioned above.

We need to add upgrade logic to catalog_data.go that will update the system-chart catalog if its url or branch value is different from the values read from the environment variable. HOWEVER, we cannot change those values if the user has _manually_ changed them. So, we need to be careful about the update logic. We should only update under the following circumstances:
1. The url and branch on the catalog CRD are the current defaults from v2.2.2 (`https://git.rancher.io/system-charts` and `master`) and the `manage.cattle.io/default-system-chart-version` annotation is not present. This will let us upgrade from v2.2.2 to v2.2.3 without breaking airgap installs.
OR
2. The url and branch from the catalog CRD do not match the values retrieved from the environment variables AND they match the values from the `manage.cattle.io/default-system-chart-version` annotation. This will let use upgrade from v2.2.3 to v2.2.4 where the new catalog branch should simply be `release`.

When you update the catalog to have new url or branch values, you need to record those values in the previously mentioned `manage.cattle.io/default-system-chart-version` annotation. This annotation does not exist yet. It needs added as part of  the update logic. The value should be json that you can parse that looks like `{"url": "xyz", "branch": "abc"}`.

Finally, our build scripts should be updated so that the branch is properly set when we publish an image. It needs to do the following:
- when we build `rancher/rancher:master` (a special image built on every commit to master of rancher/rancher), the value of the branch is `dev`. Currently QA has to manually change to `dev` when they want to test catalog changes.
- when we build a real official release like `rancher/rancher:v2.2.3`, the value is set appropriate (`release-v2.2.3`).

We can do this by introducing a SYSTEM_CHART_DEFAULT_BRANCH build argument to the server dockerfile with a default value of `release-v2.2.3` on the release/v2.2 branch of rancher and with a default value of just `release` on the master branch of rancher/rancher. You can then seed the environment variable that you'll introduce in the dockerfile with this value. The .drone.yaml file in rancher/rancher (which controls all our image publishing) should then be tweaked to add the build_arg `SYSTEM_CHART_DEFAUL_BRANCH=dev` when build master, which is here-ish i think: https://github.com/rancher/rancher/blob/master/.drone.yml#L41

When we are ready to cut the final RC of rancher for v2.2.3, we will need to make the official `release-v2.2.3` and `release` branches of system-charts so that all this madness works.

@alena1108 we will need to release note the branch change for airgap setups

**Comment by alena1108** [comment]
@cjellick 
> we will need to release note the branch change for airgap setups 

added to RN todo list

**Comment by cjellick** [comment]
Lgtm

**Comment by cjellick** [comment]
needs another change to incorporate into drone

**Comment by sangeethah** [comment]
Closing this issue with findings from https://github.com/rancher/rancher/issues/20270

If we find issues when validating upgrade scenarios involving system charts like monitoring , alerting , logging as part of testing upgrade from 2.2.5 -> 2.2.3-rcx releases we will track them as separate issues.
