### ISSUE TITLE
Backport: Catalog App answers and values out of sync

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20165]
Backport https://github.com/rancher/rancher/issues/19060

**Comment by westlywright** [comment]
Was merged with https://github.com/rancher/ui/pull/2973

**Comment by davidnuzik** [comment]
Version: v2.2.4-rc1

This change significantly improves support for switching from YAML back to form. Refer to https://github.com/rancher/ui/pull/2897 for the details.

Now, when you make changes in YAML and try to go back to the form view you will be warned if there is data in the YAML that may be lost if you switch back to the form. Below is an example with some of the preliminary tests I did with chartmuseum.

In the chartmuseum app config, I switched to YAML and added this secret as pictured below.
![image](https://user-images.githubusercontent.com/45179589/57721188-6cf8c680-7638-11e9-829a-581d4c748b49.png)

Upon clicking the "Edit as a Form" button to go back to the form view, you will now get a warning when data you have in the YAML may get lost due to us switching back to the form view:
![image](https://user-images.githubusercontent.com/45179589/57721258-987bb100-7638-11e9-8354-59c02823c941.png)

The modal allows you to confirm or Cancel to return back to the YAML view and avoids data loss. Other wise you may opt-in to the data loss by choosing "Confirm" which will switch us back to the form view. When switching back to the YAML view I can indeed see my data is lost.

We know that this is not a perfect solution, but this will at least make it very clear to the user the risks of what data may be lost if switching back to the form view.

I also tested this via app upgrades (scenario reported in the original issue, #19060 and again, I will get an appropriate warning if there is potential for data loss when switching back to the form view.

In the case where we input data for questions the form already contains there is no data loss. For example back to the chartmuseum example, I can input under "persistence" size of "17Gi" when I go back to the form view, my value is reflected in the form and I do not get any warnings in this case since I have no custom data (content that is not already existing questions).

![image](https://user-images.githubusercontent.com/45179589/57721617-83535200-7639-11e9-8549-a6150d593c34.png)

I followed these steps to test various apps. I ensured that I can bi-directionally change values. I can change values of items in the form view and it will be reflected in the YAML view and vice versa (must be a question seen on the form to support fully bi-directionally changing in YAML and form).
My testing included but was not limited to the following apps: chartmuseum, grafana, artifactory, wordpress, etc. 

For each app I configured them via YAML and switched back to form. I entered various custom content into the YAML to ensure I would always get a warning when switching back to the form view. I upgraded them via Form and YAML each. Testing as also done where I launch an app just via the form and later upgrade via YAML view.

I did not observe any issues during my testing and launching / upgrading the apps worked without any issues. I tried to test every different way I could think of.

The UI test plan will be updated around this area and improved as well.
Note: While testing I did spot an unrelated issue when add a newline to YAML. This is tracked here: #20249
