### ISSUE TITLE
[rancher-catalog] Catalog should be able to configure cluster resources

### ISSUE THREAD

**Issue by tibers** [rancher/rancher#20167]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature request.

**Steps to reproduce (least amount of steps as possible):**

1) Become disappointed with batchy workloads which are supposed to be pulled kicking and screaming into an autoscaled future - when they don't autoscale.

**Result:**

An existential crisis.

**Other details that may be helpful:**

I want to be able to scale my cluster when deploying a workload, and also select a nodetemplate. Basically I want to add a nodepool temporarily and have it properly sequestered if I so choose when deploying a catalog app.

I suspect there's a bunch of people who could use this when doing batch workloads. I have a [compute load](https://hpccsystems.com/) which is extremely resource hungry, but once the computing resources are defined, _they cannot change_ or the application's cluster has to be reconfigured. 

I thought that this was something the catalog could do, being an overlay to the helm chart, but I talked with Vincent in the slack and he indicated it couldn't happen.  So, feature time! Catalogues should be able to reconfigure cluster resources. In my case, I have a cluster defined by a cloud provider, and my interest is in scaling the cluster. I envision that someone might be interested in deploying this catalogue chart and part of that chart would be scaling the cluster to the correct size to handle this workload.

Also consider being relevant to a machine learning use case. I probably don't want to bunch of GPU instances laying around in AWS when most of my work could be performed by something like a vanilla m5.xlarge. I would also like the ability to spawn a set of nodes in a nodepool based off a node template so I could deploy this workload, keep it organized by a nodelabel or something, do my work, and then the nodes go away when the work is done.

This could also be useful for a QA scenario: I want to test out an application (or a version of an application) which requires a specific version of a group of resources (EG: ElasticSearch 6, Java 8, etc), I want to scale my cluster as part of that deployment, do my thing, and then scale it back down when I am done my thing. 

**EDIT**:
I figured I would mock up a workflow since someone told me this was opaque. We will assume that I have the nodeTemplate defined for instances I want to spin up and a working cluster, and that I am selecting a catalog app which accepts an S3 bucket as its argument.

If I did not have this as a catalog app, but it was a vanilla K8s cluster, the helm chart would assume I already had all my compute in place. The catalog would extend that helm charts functionality to enable me to use the nodeTemplate.

My input arguments will be:
1. the name of the nodeTemplate
2. how many nodes to spawn
3. misc options for the helm chart (EG: s3 bucket, configuration, etc)
4. The cleanup condition ("all pods are in CrashLoopBackoff" or "Load is under 1" or similar) 

The workflow would then look like:
1. Select the app from the catalogue
2. Specify the nodeTemplate which this app will be sequestered to
3. Tell the catalog how many nodes I want to spawn 
4. Fill out misc configuration options for that helm chart
5. click Go
6. The nodeTemplate is applied to the cluster and it waits for all the workers to join successfully
7. Work is performed
8. Exit condition is met
9. Nodes are despawned

**Comment by vincent99** [comment]
I'm sorry I apparently wasn't clear enough in Slack, but there's just no way this is ever going to get picked up by us as a community feature.  And frankly I'd argue against it as a customer request too (I don't know if your company is a customer it not, but it's a public issue now).

This is a _very_ specific workflow with limited appeal to other users.  It crosses the streams of several very separate concerns and will be full of pointy edge cases.  We don't build big complicated features for one use case because the product ends up looking like [The Homer](https://simpsons.fandom.com/wiki/The_Homer)

A few of the top of my head:
  - Helm ("catalogs") operate within the context of a cluster, and the definition of that cluster is but containers in itself.  
  - Owners who can manipulate the cluster and users that can deploy apps into it are often different roles
  - NodeTemplates and CloudCredentials belong to users and are not shared (though this is being worked on) to be picked from when deploying the app
  - You need Taints on the nodes to limit them to only running this app's workload, but these are not part of the NodePool definition at the moment.
  - Those aren't necessarily unique, so an app might request nodes that already exist and you may or may not want to create a new set it use the existing set.  If you make a new one the Taints don't restrict it to the right set (so you probably need dynamically defined Taints), and if you don't you have no idea when to cleanup mixed-use nodes.
  - The cleanup condition as described is basically Turing compete, you could want it to be anything.  And that may impose requirements on the cluster or all being deployed, like you need monitoring enabled for one you describe.

So as I was trying to say in Slack, this is the kind of thing where we provide primitives/building blocks that allow you to do the steps of the workflow you want, and then you build that in your own scripting language outside of Rancher instead of trying to build exactly the workflow one person wants.

Some of those building blocks are missing features today that would help this, and those are a much more reasonable ask to add a series of small things that are individually useful functionality to a broader set of users.
