### ISSUE TITLE
Feature Request: Support for any SAML-enabled IdP

### ISSUE THREAD

**Issue by danielmittelman** [rancher/rancher#20175]
**Feature Request**
Although not officially supported, I was able to integrate my team's SAML-enabled IdP (JumpCloud) with Rancher through the AD FS connector, only to find out that it's just plain SAML and has no special properties related to Active Directory. This is a great security feature for us.

However, when my users login today through SSO, they see a button saying "_Log In with AD FS_". This is, obviously, confusing.

I'd like to request that the "AD FS" connector's name is changed to "SAML 2.0", and an input box is added to describe the Identity Provider's name. Or, just add another button next to it named that way so that existing ADFS users are not impacted. Maybe something like this?

<img width="950" alt="Screen Shot 2019-05-11 at 7 45 25" src="https://user-images.githubusercontent.com/6874922/57565149-d5d60980-73c0-11e9-989a-6e6c6ef7ec59.png">

**Comment by vincent99** [comment]
We test only the providers we support, and support only the providers we test, because they may have variations or may eventually have provider-specific additional features. 

"Hijacking" a supported provider config to talk to something else may or may not work now, and may or may not continue to work in future versions.  But it's not something we're going to encourage.

(And if we were going to, it would be a separate something like UnsupportrdGenericSamlConfig provider)

**Comment by danielmittelman** [comment]
But SAML 2.0 is a generic protocol and is not (and should not be) vendor-specific. Limiting this protocol to a handful of vendors seems peculiar at best.

By looking in the source code, it seems that all SAML-enabled providers are eventually based on the [crewjam/saml](https://github.com/crewjam/saml) library which does exactly that. Why not just create a "vanilla" connector which does not impose any preset values?

**Comment by vincent99** [comment]
That's all lovely in theory but being a protocol doesn't mean they all support the same parts of it or in the same way.  We had "generic LDAP" in 1.x and a constant stream of people not able to configure it properly because different options are needed for different implementations and server preferences.  We have enterprise customers who we need to provide actionable support for, so like I said we support only specific things and test those things.

Standards doesn't help with any integration outside of the actual protocol.  For example GitHub is "just OAuth" but what makes it actually useful is using the token acquired from the OAuth flow to talk to their API, which there are no standards for, to do things like search users/groups.  Right now none of the SAML providers have that kind of integration, but that doesn't mean they will never have it.

Yes, obviously all the SAML clients are using a SAML library.  A "vanilla connector would be what I said before:

> (And if we were going to, it would be a separate something like UnsupportrdGenericSamlConfig provider)

**Comment by zonywhoop** [comment]
What's the chance of getting a JumpCloud auth provider created and supported?  I'm working with both companies (Rancher and JumpCloud) and per JumpCloud I'm the 3rd person this moth that's talked with them about integrating with Rancher.

**Comment by alexey-pelykh** [comment]
According to https://github.com/rancher/rancher/commit/d9f1432cdad6d9abdee93a0d1ad4f04334631d15 adding extra SAML2-compatible provider is more of marketing move, no more no less. So Adding "UnsupportrdGenericSamlConfig" as mentioned above would solve the issue, meanwhile it seems that configuring any-SAML2-provider-as-Okta-or-any-other would do

**Comment by alexey-pelykh** [comment]
Also, it would be great to support LDAP+SAML2 at the same time, to sync directory from LDAP while allow to login using SSO

**Comment by MetalJacx** [comment]
I too would like to request either jumpcloud or generic.

**Comment by qdrop17** [comment]
Yeah, I support a generic SAML provider too. It gets quite difficult to setup SSO (remember: the first "S" stands for "Single") with these dependencies all over the place.

Please consider tackling this issue. Additionally you could add a disclaimer that you don't offer any support to these unsupported backends. That's fine.

**Comment by dverbeek84** [comment]
I have worked ad a IAM vendor and mostly with SAML. I don't see a clear reason why only supporting specific SAML providers besides commercial reasons. `provider-specific additional features` is not a SAML standard and should not be used offcourse.
This is also why SAML is here in the first place. Even if you implement the bare minimal of the SAML spec(excluding 'artifact binding' for example ) you support most of the use cases.

**Comment by dirien** [comment]
hi Everyone,

have the same problem at the momen. Would like to implement SAML in Rancher but found out there is no "generic" saml support. 

Our software supply chain consist from different products, like for example Artifactory, who  support SAML out of the box without a fuzz. 

So i would really see in Rancher the support for SAML.

**Comment by zonywhoop** [comment]
Just as a note for this issue - it would be great if signed responses or the private was not required.  The reason is that integration with providers such as Google SSO or AWS SSO do not allow you download or set the private key that is used so it's impossible to integrate these with Rancher. A generic provider that allowed us to set these settings would be great a fix.
