### ISSUE TITLE
[Windows] Could not start kube-proxy without setting node name when using AWS cloud provider 

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#20185]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Prepare 1 Linux Ubuntu 18.04 and 1 Windows 2019
1. Follow https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/ to set up a cluster with AWS cloud provider
1. Add a Linux control plane + etcd + worker node
1. Add a Windows node by default

**Result:**
Fail to bootstrap kube-proxy on Windows

**Other details that may be helpful:**
- Bootstrap kube-proxy successfully if setting `Node Name` to [`AWS private DNS name`](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#node-name) when adding a new Windows node
- It seems kube-proxy cannot find the node info without setting node name when using AWS cloud provider
![image](https://user-images.githubusercontent.com/3394724/57598352-78d78080-7585-11e9-8468-eaa6bbb5e4e7.png)
 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): 1.14.1

**Comment by sowmyav27** [comment]
verified on `rancher:master` (06/10/2019)
1. Bring up a custom cluster with 1 linux node - 18.04 (all roles) and 1 Windows 2019 node (worker node)
2. Cloud provider should be set.
3. cluster comes up successfully


Issues:
1. Do an Edit cluster.
2. `Node Operating System` option is not displayed.
3. OS labels on Cluster--> Nodes page as `Windows` or `Linux` is not displayed. 
4. **Node names** displayed - **Node name: ip-x-x-x-x** - Linux and **Node name: ip-x-x-x-x** - Windows
5. While deploying a workload, labels (Target OS) - `Linux` or `Windows` are not displayed.


For another cluster - no AWS cloud provider enabled, things work fine - `Node Operating System` option is displayed on an edit cluster, while deploying Workloads Target OS labels are shown and windows nodes - have **Node Name : ec2amaz-a0juj5r** and linux nodes have **Node name: ip-x-x-x-x**

Reopening this issue because of the issue.

**Comment by loganhz** [comment]
cannot reproduce it. It looks like it's an UI issue. The flannel RKE setting is missing in the setup.

**Comment by loganhz** [comment]
Still cannot reproduce this issue. Need more input from QA for the reproduce steps.

**Comment by sowmyav27** [comment]
verified `rancher:master` (06/13/2019)

Not able to reproduce the issue reported in [https://github.com/rancher/rancher/issues/20185#issuecomment-500588582](url)

Able to configure an AWS cloud provider cluster with 1 Linux - 18.04 node - all roles and 1 windows 2019 node - worker.

Workload deployed on windows node -- works fine.
