### ISSUE TITLE
Use gitlab to configure cicd authentication, prompting net/ HTTP: request canceled (client.timeout while reading body)

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#20191]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Gitlab version  is 11.3.6，the repository has six pages, totaling nearly 600 repositories. 
2. The new gitlab account can be authorized normally.
3. When using root account for authorization, prompting net/ HTTP: request canceled (client.timeout while reading body)

**Result:**

Use gitlab to configure cicd authentication, prompting net/ HTTP: request canceled (client.timeout while reading body)

<img width="396" alt="image" src="https://user-images.githubusercontent.com/20707603/57605109-7599c000-7598-11e9-9f76-15959429dfec.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version:
`rancher/rancher:v2.2.2`

- Installation option :
HA

**Cluster information**
- Cluster type:
Custom

- Machine type:
VM

- Kubernetes version (use `kubectl version`):
v1.13.5
```

**Comment by xiaoluhong** [comment]
@gitlawr

**Comment by gitlawr** [comment]
Reproducible by following steps:
1. Set up a 4c16g Gitlab instance
2. Import 400+ repositories from Github using my access token.
3. Integrate with the Gitlab instance in tools-pipeline and get the error.

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher:v2.2.7

Steps:
- run Rancher:v2.2.7 single install
- add a cluster
- under the default project, go to tools -> pipeline
- add a Gitlab account
- wait for authentication to be finished 

Results:

<img width="1443" alt="Screen Shot 2019-08-20 at 7 46 27 PM" src="https://user-images.githubusercontent.com/6218999/63398957-021c0180-c384-11e9-91de-0c4934caf52d.png">
<img width="1321" alt="Screen Shot 2019-08-20 at 7 51 12 PM" src="https://user-images.githubusercontent.com/6218999/63398958-021c0180-c384-11e9-8514-b304670297ff.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher: master-head 

Following the same steps as the previous comment, this time Rancehr loads all 300 repos from Gitlab successfully 

<img width="1261" alt="Screen Shot 2019-08-20 at 8 01 39 PM" src="https://user-images.githubusercontent.com/6218999/63399484-86bb4f80-c385-11e9-8cdd-d32709c0f66e.png">
