### ISSUE TITLE
Backport MCAPP continues to be stuck in "installing" state even after attempting to upgrade the Mcapp and fix with correct roles.

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20239]
Backport https://github.com/rancher/rancher/issues/19982

**Comment by alena1108** [comment]
Can be tested with v2.2.4-rc1

**Comment by sangeethah** [comment]
Tested with 2.2.4-rc1

Steps to reproduce the problem:

As a cluster owner , deploy a MCAPP for "grafana" app by choosing "project" role.
MCAPP will be stuck in "Installing" state since the app will fails to deploy.
This is expected since "grafana" app requires cluster role to be deployed successfully.

Upgrade MCAPP and change the role to "cluster".

After this , able to see the MCAPP deploy successfully.
