### ISSUE TITLE
[Windows] Unable to create LB in Azure cluster with cloud provider set

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20240]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Set up an azure custom cluster with the following setup: 1 linux node - All Roles, 1 Windows worker node. Have the Azure cloud provider set.
2. Deploy a workload with Load Balancer set. (windows workload)

**Expected Result:**
Workload is deployed successfully and load balancer is deployed successfully, and comes up to `Active` state.

**Actual Result:**
Workload is deployed successfully, comes to `Active` state, but the load balancer is stuck in `Pending` state.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.3.0-alpha2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.14.1
```

**Comment by thxCode** [comment]
There are two kinds [Load Balancer](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview) on Azure, `basic` and `standard`. When using the Azure cloud provider, the default LoadBalancer type is `basic`. We can override it via `loadBalancerSku`: https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#cluster-config.

Normally, creating a VM from Azure portal with **Public IP**, Azure portal will bind a `standard` Public IP for this VM. 

However the Azure doesn't allow to retain both `standard` (bound to VMs) and `basic` (bound to the `kubernetes` [Load Balancer](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview)). Look at the kube-controller-manager log, I can find: `Different basic sku and standard sku load balancer or public Ip resources in availability set is not allowed`. _This is the root cause of this issue._

For now, we don't support to override Azure Load Balancer type via `loadBalancerSku`: https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#cluster-config from Rancher UI, as we need to add this configuration item in https://github.com/rancher/types/blob/83a44f57428533fd8efe956bcc44e714e35a6115/apis/management.cattle.io/v3/rke_types.go#L529. As a workaround, this will be a bit complicated:

1. Set _None_ Public IP when creating VM
    ![image](https://user-images.githubusercontent.com/3394724/57759679-01dcec00-772d-11e9-8eae-40e79df89c74.png)
1. Create a _Basic_ Public IP
    ![image](https://user-images.githubusercontent.com/3394724/57760049-8465ab80-772d-11e9-9b06-bb42594e0588.png)
1. Associate the `#2` created Public IP to `#1` created VM.

**Comment by sowmyav27** [comment]
@thxCode @loganhz After the fix, is there any manual configuration that has to be done while setting up Azure nodes? Or are the steps mentioned in this comment - [https://github.com/rancher/rancher/issues/20240#issue-444018244](url) will be sufficient to validate this issue?

**Comment by loganhz** [comment]
Yes, it's still sufficient.

Please make sure you specify the cloud provider param `loadBalancerSku` to `standard`

**Comment by sowmyav27** [comment]
@loganhz Where can I find this parameter `loadBalancerSku` be set to standard ?

**Comment by sowmyav27** [comment]
verified on latest master build.
**Steps taken:**

1. Set up an azure custom cluster with the following setup: 1 linux node - All Roles, 1 Windows worker node. Have the Azure cloud provider set and set `loadBalancerSku` to `standard`
2. Deploy a workload with Load Balancer set. (windows workload)
3. The Load balancer is stuck in `Pending` state.

**Comment by thxCode** [comment]
@sowmyav27 ,the Public IP of the VM created from Azure Portal changes from `Standard` to `Basic`. On this case, you could configure the `loadBalancerSku` to `basic` or leave it blank.

The checkpoint is that after the Azure VM is established, look at the public IP type of it. thereby determining the type of `loadBalancerSku`.

**Comment by sowmyav27** [comment]
Verified on `rancher:master` (06/13/2019)

Able to deploy Load balancer - workloads - Linux and on Windows nodes with `loadBalancerSku` set to `Basic` and `Standard`. Load Balancer comes up to `Active` state.

Cluster config - 1 linux node Ubuntu 18.04 LTS - all roles, 1 windows 2019- worker node.

**Comment by shapetheLOLa** [comment]
> @loganhz Where can I find this parameter `loadBalancerSku` be set to standard ?

Can you tell me where to set the parameter when not in the Rancher UI?

**Comment by loganhz** [comment]
`loadBalancerSku` is in UI now if you are using v2.3.0-alpha5. 

![image](https://user-images.githubusercontent.com/21168270/60348013-4a0c5100-99f1-11e9-8553-be1908c72f1d.png)

**Comment by shapetheLOLa** [comment]
Unfortunately no, we are on the latest RC. Is there any other way to change it to standard?

**Comment by loganhz** [comment]
It requires a backend change. The value is `Basic`, so I guess you can only create basic LB for now.

**Comment by loganhz** [comment]
@thxCode is there a workaround ?

**Comment by shapetheLOLa** [comment]
Thats alright. Ill wait for this to make it to the next RC and will update then.

Thanks! :)

**Comment by shapetheLOLa** [comment]
Ok. I was told to use the alpha, but its a production env. So I would rather not do it, as its my responsibility. Is there a workaround for this besides using the alpha version?

**Comment by loganhz** [comment]
There is no workaround in 2.2.x. Even you update the cloud provider config file on the VM, RKE will change it back after a while..

I think you can only use Basic LB in Azure if you are using 2.2.x.

2.3.x will be out in Sep.
