### ISSUE TITLE
UI for Cluster templates

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20268]
This ticket is to keep track of the UI component development of Cluster Templates feature

https://github.com/rancher/rancher/issues/14337

**Comment by westlywright** [comment]
UI MVP is in master.

**Comment by davidnuzik** [comment]
Re-opening issue. There is still something we should fix before I can properly test. For now I'll keep testing cluster templates creation/cloning/etc, but can't test creating clusters from templates due to this issue.

Version: master-head (7/8/19)

- Able to create cluster templates by navigating to user-menu and clicking on Cluster Templates.
- NOT able to create clusters after having 1 or more cluster templates. The Browser dev console complains about:
```
Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.ie [as get] (metal.js:1603)
    at controller.js:42
    at Array.forEach (<anonymous>)
    at n.<anonymous> (controller.js:39)
    at n.a.get (metal.js:2984)
    at ie (metal.js:1592)
    at t.r.compute (glimmer.js:535)
    at t.value (glimmer.js:384)
    at e.r.value (runtime.js:5087)
    at _t (glimmer.js:4084)
```

And in the UI I see cluster template revisions are not listed:
![image](https://user-images.githubusercontent.com/45179589/60848645-508e8b80-a19c-11e9-9662-6ca57b8fac01.png)

So far I have not identified any issues with cluster templates and revisions themselves. I can create cluster templates, clone revisions, create from default, etc all fine. Just this issue is preventing me from creating clusters after I have made 1 or more cluster templates.

**Comment by davidnuzik** [comment]
Version: master-head (7/9/19) (`3f16f9f0`)

# Summary and What Changed:
This adds Cluster Templates to the UI. This comment covers the basic functionality and there are still a few things that are subject to change. An in-depth test plan was created and I don't go into depth discussing each and every test performed. This is just an overview.

The view of the "Add Cluster" page was changed as pictured below (default drivers enabled):
![image](https://user-images.githubusercontent.com/45179589/60912429-27243d00-a23a-11e9-89af-a55679090979.png)

To create a cluster template, go to the user menu like below:
![image](https://user-images.githubusercontent.com/45179589/60912261-d7457600-a239-11e9-820a-daea556bd9d3.png)

You will initially see a page like this, where you can click on "Add Template" to create one:
![image](https://user-images.githubusercontent.com/45179589/60912505-55098180-a23a-11e9-929d-6df677eacf74.png)

You will then see a form like this asking for details for each area for the template. This is just for Rancher-Created clusters. (Picture does not show whole form):
![image](https://user-images.githubusercontent.com/45179589/60912646-b4679180-a23a-11e9-8f21-3c5fc37013ba.png)

There are options we may set (or use defaults):
- Template Name
- Template Revision Name
- Set As Default Revision (checkbox which is enabled by default)
- Share Template Section
 This section lets you share the template with other users or to all publicly (makes it read-only to all users). This is not currently working and is a known issue. A fix is currently in progress. My test plan covers testing this thoroughly so testing this area will not be forgotten.
- Cluster Options Section
 This section is just like the Cluster options section when you create a cluster without using a template. You can set the K8s version, CLI (Network Provider), Windows Support (if k8s 1.14 or newer and Flannel are chosen), Project Network Isolation, and Cloud Provider. You can Enable toggle buttons for each and every configurable area if you would like to allow the members with access to the template to be able to override any of your settings. For example, as pictured below I have opted in to enable the allowance of a member to override the k8s version of my template:
![image](https://user-images.githubusercontent.com/45179589/60913073-79b22900-a23b-11e9-85be-9e3d85913bd3.png)
You can also see I have hovered over the button and see the tooltip that explains the button.
- Private Registry Section
 This has again the same settings as if you created a cluster without a template. We can opt in to Enable this and define our URL, User, and Password, and optionally allow members with access to the template to override any of these.
- Authorized Cluster Endpoint Section
 Again, we can set any options we want in this section and allow any overrides.
- Advanced Cluster Options Section
 Again, we can set any options we want in this section and allow any overrides.

When you have one or more templates on this page, they are grouped by the template name. Items under these groups are our revisions (basically revisions = our templates, whereas template names are just a container for them).
![image](https://user-images.githubusercontent.com/45179589/60914154-c5fe6880-a23d-11e9-8b56-da0aedec4926.png)

There are new actions as well. For a cluster template (name/container) we can create a new revision based on the default.
![image](https://user-images.githubusercontent.com/45179589/60914212-ed553580-a23d-11e9-9ff2-92ed6c982288.png)

And for individual cluster template revisions, we can clone from these as well:
![image](https://user-images.githubusercontent.com/45179589/60914253-ffcf6f00-a23d-11e9-91b2-a28fcb6b6047.png)

# Validation:

### Endpoints/HTTP:

**Template creation:**

- When you create a cluster template, a POST is requested at /clustertemplate which sends the following in req payload:
```
enforced: false
name: "clustertemplatename_goes_here"
type: "clustertemplate"
```
Note, enforcement is still being worked on and is not tested here. It is in the test plan though so this gets coverage. I validated that any valid name looks correct in this HTTP call.
The server response payload basically appears to be an affirmative with cattle-global-data.

- A POST is requested at /clustertempalterevision which sends the following in req payload (formatting isn't perfect, is example):
```
clusterConfig: {dockerRootDir: "/var/lib/docker", enableClusterAlerting: false, enableClusterMonitoring: false,…}
dockerRootDir: "/var/lib/docker"
enableClusterAlerting: false
enableClusterMonitoring: false
enableNetworkPolicy: false
localClusterAuthEndpoint: {enabled: true, type: "localClusterAuthEndpoint"}
enabled: true
type: "localClusterAuthEndpoint"
rancherKubernetesEngineConfig: {addonJobTimeout: 30, ignoreDockerVersion: true, sshAgentAuth: false,…}
addonJobTimeout: 30
authentication: {strategy: "x509", type: "authnConfig"}
strategy: "x509"
type: "authnConfig"
ignoreDockerVersion: true
ingress: {provider: "nginx", type: "ingressConfig"}
provider: "nginx"
type: "ingressConfig"
kubernetesVersion: "v1.14.3-rancher1-1"
monitoring: {provider: "metrics-server", type: "monitoringConfig"}
provider: "metrics-server"
type: "monitoringConfig"
network: {plugin: "canal", type: "networkConfig", options: {flannel_backend_type: "vxlan"}}
options: {flannel_backend_type: "vxlan"}
flannel_backend_type: "vxlan"
plugin: "canal"
type: "networkConfig"
privateRegistries: [{isDefault: true, type: "privateRegistry", url: ""}]
0: {isDefault: true, type: "privateRegistry", url: ""}
isDefault: true
type: "privateRegistry"
url: ""
services: {type: "rkeConfigServices",…}
etcd: {creation: "12h", extraArgs: {heartbeat-interval: 500, election-timeout: 5000}, retention: "72h",…}
backupConfig: {enabled: true, intervalHours: 12, retention: 6, type: "backupConfig"}
enabled: true
intervalHours: 12
retention: 6
type: "backupConfig"
creation: "12h"
extraArgs: {heartbeat-interval: 500, election-timeout: 5000}
election-timeout: 5000
heartbeat-interval: 500
retention: "72h"
snapshot: false
type: "etcdService"
kubeApi: {alwaysPullImages: false, podSecurityPolicy: false, serviceNodePortRange: "30000-32767",…}
alwaysPullImages: false
podSecurityPolicy: false
serviceNodePortRange: "30000-32767"
type: "kubeAPIService"
type: "rkeConfigServices"
sshAgentAuth: false
type: "rancherKubernetesEngineConfig"
type: "clusterSpecBase"
clusterTemplateId: "cattle-global-data:ct-jr94m"
enabled: true
name: "revision-lqnbnmzx"
questions: [{variable: "rancherKubernetesEngineConfig.kubernetesVersion", type: "string", isBuiltIn: true}]
0: {variable: "rancherKubernetesEngineConfig.kubernetesVersion", type: "string", isBuiltIn: true}
isBuiltIn: true
type: "string"
variable: "rancherKubernetesEngineConfig.kubernetesVersion"
questionsSchemas: {questions: [{variable: "rancherKubernetesEngineConfig.sshCertPath", type: "string"},…]}
questions: [{variable: "rancherKubernetesEngineConfig.sshCertPath", type: "string"},…]
[THIS SECTION TRUNCATED]
type: "clusterTemplateRevision"
```
This basically contains the meat of the template, containing the contents of the template revision which has all our settings for the cluster. You can see rancherKubernetsEngineConfig is within it, and  you'll, see this mentioned below in the validation section. I validated as best I could by changing various settings, allowing overrides, etc in most areas.
The server response payload is an affirmative that basically echos the cluster config, etc.

- Last, a PUT is requested at /cattle-global-data:ct-jr94m (last 5 chars are random). This contains the following in the request body (example):
```
annotations: {}
baseType: "clusterTemplate"
created: "2019-07-09T18:24:55Z"
createdTS: 1562696695000
creatorId: "user-zcfl9"
defaultRevisionId: "cattle-global-data:revision-lqnbnmzx"
enforced: false
id: "cattle-global-data:ct-jr94m"
labels: {cattle.io/creator: "norman"}
cattle.io/creator: "norman"
name: "test"
type: "clusterTemplate"
uuid: "d99cba0f-a276-11e9-aee6-0242ac110002"
```
There isn't much to be tested in this area. I tried various valid names and they all worked. API prevents naming invalid things (not of same type).
The server response is basically an affirmative with cattle-global-data.

**Template cloning:**

When you clone either from default revision or from an individual template revision, a PUT is requested to cattle-global-data again and a POST to create the new clustertemplaterevision. The content is basically the same. I made sure this works without any issues.
Server response is similar to creation (see above prior section on creation).

**Template deletion:**

You cannot delete the default revision. Instead you must delete the whole template if you wish to do this. Or, alternatively, change the default to another revision, then you can delete that revision which is now no longer default.

When you delete a revision, a simple DELETE is requested at v3/clusterTemplateRevisions/cattle-global-data:revision-vbqqyywy (example shown, your revision name will vary).

When you delete a template, a simple DELETE is requested at v3/clusterTemplates/cattle-global-data:ct-jr94m (example shown, your ct name will vary (is random last 5 chars)).

I made sure deletion works without any issues. Server response is basically an HTTP 204, as expected.

### API Schema:

Part of testing the UI involves testing the API schema and ensuring that types are honored, defaults show, if something is required the UI indeed requires it, and etc.

- v3/schemas/clusterTemplateRevision
- v3/schemas/clusterTemplate

I ensured that for each area I could possibly test with the UI, the types are honored. I.e. for a type of "dnsLabel" only valid DNS string is accepted, etc.

I ensured that any default elements are indeed set to a default value. Any that are nullable are indeed nullable, and any that are required are indeed required. Some areas cannot be null but looks like UI prevents this anyway. This is okay.

### Functional checks/issues:

- [ ] Create simple cluster template (using defaults) and bring up cluster with it.
- [ ] Clone cluster template revision, ensure clones correctly, ensure can bring up cluster with it.
- [ ] Clone cluster template from default, ensure clones correctly and is indeed from default, ensure can bring up cluster with it.
- [ ] Delete cluster template and cluster template revision. Ensure UI modal prompts for each. Deletion works correctly. No long see listed on Cluster Templates page.
- [ ] Create various cluster templates all with different settings, ensure that for each area we can override everything. Create a cluster and ensure that user can indeed override these settings.
ISSUE: #21410 "Cannot make some cluster template fields overridable with disabled elements" section

### Miscellaneous checks/issues:

- Create cluster template using defaults, get rancherKubernetesEngineConfig json.
- Create cluster without template using defaults, get rancherKubernetesEngineConfig json.
- Compare the two, ensure they are the same (template indeed uses same defaults).

Note, there are other known issues that already exist:
- Can't edit a cluster that has k8s version as a question in template: #21406
- Members/enforcement not yet working/ready: #21401 and #21378 
(There are more as well but these are mostly due to API-specific issues / API areas of testing).

Note, this validation basically covers basic workflows with cluster templates in the UI. Further testing is to be done per internal test plans (including RBAC testing which is not yet available due to #21401 and #21378 . This validates that the basic core features are working as expected except for issues described above.

**Comment by davidnuzik** [comment]
To do's
- Test Sharing (this should actually be working, only had 1 unrelated backend issue)
- Test Windows Support, create template that defines cluster support and leverage it, ensure is working.
- Editing either needs to be tested here or needs to be tested in another issue and this should be called out.

**Comment by davidnuzik** [comment]
To do:
RBAC.
Cluster owner seems to have issues, test all types of membership.

**Comment by davidnuzik** [comment]
Closing this issue. All the existing functionality has been validated. See the comment above with all the details and links to issues created.
