### ISSUE TITLE
Support one click upgrade option for cluster/project monitoring.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20304]
Rancher server version - v2.2.4-rc5

Currently we expect users to upgrade cluster/project monitoring related apps individually.

Following are some of the the workflows that are not obvious to the user when "upgrade available" options are made available on the cluster/project monitoring related apps.

1. Cluster monitoring relies on both `cluster-monitoring` app  and  `monitoring-operator` app , we expect users to upgrade BOTH these app  so that  are  up to date for a given rancher server version .
2. Project Monitoring relies on  `monitoring-operator` (deployed in system project)  and `project-monitoring` (deployed in users project ) . Ideally when `project-monitoring`is upgraded , we would expect  `monitoring-operator` (deployed in system project) to also be upgraded .

I almost feel like there should be 1 click to upgrade cluster monitoring/project monitoring which should do the upgrade of all the necessary apps  .Otherwise there is going to be lot of confusion. Just like enabling/disabling monitoring in a single click , Upgrade should also be 1 click which should not require users to be doing multiple app upgrades.

At this time , a project owner will not have the ability to  upgrade `monitoring-operator`which is in the “System” project ? We will not have the need to be doing a project monitoring upgrade for this release. But this something that needs to be addressed as well.

**Comment by alena1108** [comment]
Based on offline discussion with @sangeethah @loganhz and @cjellick, we are going to add a better UX around monitoring upgrade. There will be a UI option to upgrade cluster monitoring, that would trigger app upgrade. So user doesn't have to go and manually update 2 monitoring apps.

**Comment by davidnuzik** [comment]
**Replication:**
v2.2.4-rc5

I enabled cluster monitoring on one cluster and project monitoring on another cluster.
- Downgraded the cluster monitoring and operator to v0.0.2 (need to do this because latest is v0.0.3 so I wouldn't have anything to upgrade to and in v2.2.3 we didn't have an option for project monitoring).
- Downgraded to v0.0.1 for project monitoring because downgrading to v0.0.2 does not work due to errors.

I agree there is no easy way to do upgrades. You have to manually go to each app in the System project and upgrade each app individually for both project and cluster monitoring.

**Validation:**
v2.2.4-rc5 -> master upgrade (Master (v2.3) (5/30/19))

I upgraded to the latest master build available to me at the time and tested the one-click upgrade feature for cluster and project monitoring.

I observed the new "Upgrade Available" notice at the top of monitoring config.
![image](https://user-images.githubusercontent.com/45179589/58671540-db57ad00-82f7-11e9-8f6a-fda6b23e2b38.png)

From the drop down I can choose to keep current v0.0.2 or upgrade to now v0.0.3 available. I upgraded to v0.0.3. All I had to do was pick this and then click "Save"
I quickly switched to System > Apps and watched both the `cluster-monitoring` and `monitoring-operator` update to v0.0.3. This worked without any issues.

If I go back to the cluster monitoring config page now I no longer see the alert that an update is available. You also cannot downgrade which I think is fair. If for some unique reason a user must downgrade they should probably do this manually for each app.
![image](https://user-images.githubusercontent.com/45179589/58671639-2a054700-82f8-11e9-9f1f-0090747d02bc.png)

I did the same test but for the cluster that had project monitoring enabled. It was basically the same process.
![image](https://user-images.githubusercontent.com/45179589/58671659-40ab9e00-82f8-11e9-85ce-e91dc8a91c62.png)

This upgraded `project-monitoring` to the latest v0.0.3 and upon checking the project monitoring config page again I no longer see the alert that it is out of date.

--

I smoke tested both cluster monitoring and project monitoring post-upgrade (project monitoring ensure endpoints functional). I didn't observe any issues.
