### ISSUE TITLE
Cluster goes to unavailable state after performing a `docker stop` on etcd node that is the first in `etcd-servers` api server argument

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#20311]
Rancher server: v2.2.2

Steps:
1. Create a DO  cluster with 3 nodes having all roles each
```
node1 - etcd, control, worker
node2 - etcd, control, worker
node3 - etcd, control, worker
```
2.  Create few pods
3.  Find the etcd leader using the command :
```
ETCDCTL_API=3 etcdctl -w table --endpoints=etcd1:2379,etcd2:2379,etcd3:2379 endpo
int status
```
This node also happened to the active control node 

4. Perform a docker stop on the master node 

The cluster goes to unavailable state and does not recover

**Comment by alena1108** [comment]
It doesn't have to be the etcd leader host necessarily. The situation where I've observed the issue, is:

1) Start 3 hosts, all having role=all
2) Find the host which ip = cluster.status.ApiEndpoint.
3) Login to the host and shutdown docker. 

API never recovers, and cluster in the UI stays in unavailable state.

Based on @ibuildthecloud input, `translateClusterAddress` in https://github.com/rancher/rancher/blob/master/pkg/dialer/factory.go#L144 should be able to handle this situation, and redirect the traffic to the working host.

In other case, when you shutdown the host instead of shutting down docker, the recovery happens, but it's not immediate, and might take 10-30 seconds.

**Comment by alena1108** [comment]
Update: the issue is not caused by the cluster agent; the root cause is https://github.com/kubernetes/kubernetes/issues/72102. 

Rancher is designed to ensure that all of the etcd certificates will have the SANs of all the etcd nodes. This should have mitigated the upstream kubernetes issue. However after more investigation, we observed that SANs could go missing in some situations. And if the SAN(s) are missing from the first etcd node of `etcd-servers` api server argument (the node doesn't have to be a real etcd leader), the setup can become unavailable once this first node goes down.

**Comment by sangeethah** [comment]
Steps to reproduce the issue:

Rancher server version - v2.2.2
Create a custom cluster.
Register node1 (all roles). Wait for cluster to become active.
Register node2 (all roles). Wait for cluster to become active.
Register node3 (all roles). Wait for cluster to become active.

Stop docker  or power down the node that appears as the first entry in `etcd-servers` list in the kube-apiserver.

```
root@ip-172-31-10-43:/etc/kubernetes/ssl# docker inspect kube-apiserver | grep etcd-server
            "--etcd-servers=https://172.31.2.37:2379,https://172.31.10.43:2379,https://172.31.10.92:2379"
                "--etcd-servers=https://172.31.2.37:2379,https://172.31.10.43:2379,https://172.31.10.92:2379"
root@ip-172-31-10-43:/etc/kubernetes/ssl#``` 
```
Check that there are missing Ip and DNS  entries in the etcd certs.

```
root@ip-172-31-10-43:/etc/kubernetes/ssl# for f in kube-etc*.pem; do echo $f;  openssl x509 -text -noout -in $f | grep -i ip-172; done
kube-etcd-172-31-10-43-key.pem
unable to load certificate
139805791819416:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE
kube-etcd-172-31-10-43.pem
                DNS:ip-172-31-10-43, DNS:ip-172-31-10-92, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:18.220.11.139, IP Address:172.31.10.43, IP Address:3.14.128.73, IP Address:172.31.10.92, IP Address:127.0.0.1, IP Address:10.43.0.1
kube-etcd-172-31-10-92-key.pem
unable to load certificate
140659085407896:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE
kube-etcd-172-31-10-92.pem
                DNS:ip-172-31-10-92, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:3.14.128.73, IP Address:172.31.10.92, IP Address:127.0.0.1, IP Address:10.43.0.1
kube-etcd-172-31-2-37-key.pem
unable to load certificate
139722298246808:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE
kube-etcd-172-31-2-37.pem
                DNS:ip-172
, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:18.219.27.67, IP Address:172.31.2.37, IP Address:18.220.11.139, IP Address:172.31.10.43, IP Address:3.14.128.73, IP Address:172.31.10.92, IP Address:127.0.0.1, IP Address:10.43.0.1
```

**Comment by soumyalj** [comment]
Tested with master

Created custom cluster with 3 etcd nodes and one control/worker node
Deleted each of the etcd nodes and added new node. After new node is created, verified that the command openssl x509 -text -noout -in kube-etcd-a-b-c-d.pem returns IP and DNS entries of all the 3 etcd nodes as expected.
Cluster was operational and new workloads got created successfully.
