### ISSUE TITLE
Etcd graph on cluster dashboard off by 100x

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#20345]
Rancher 2.2.4-rc5

When comparing the etcd graph in the Rancher UI to the grafana etcd graph for raft proposals there is a 100x  discrepancy.

Rancher UI
![Screen Shot 2019-05-20 at 2 53 31 PM](https://user-images.githubusercontent.com/1989084/58057434-b3a75e80-7b19-11e9-9162-753c5152779e.png)

Grafana:
![Screen Shot 2019-05-20 at 2 54 12 PM](https://user-images.githubusercontent.com/1989084/58057445-bdc95d00-7b19-11e9-89eb-9d974d590586.png)

**Comment by loganhz** [comment]
Please test it with rc8

**Comment by davidnuzik** [comment]
Version: v2.2.4-rc8

I can confirm the issue is resolved. In my case I tested with several etcd nodes because I wanted to make sure that scenario would work fine as well. The sum of the values for each etcd node is equal to what is displayed in the grafana dashboard. Screenshots below.

![Screen Shot 2019-05-23 at 9 28 36 AM](https://user-images.githubusercontent.com/45179589/58271044-02ced880-7d40-11e9-98f6-4e22af0a70f1.png)

![Screen Shot 2019-05-23 at 9 28 49 AM](https://user-images.githubusercontent.com/45179589/58271052-05313280-7d40-11e9-9ffa-071c27cebab5.png)

`2.7 * 3 = 8.1`

Using a cluster with one etcd node works fine as well.
