### ISSUE TITLE
Add support for AWS ec2 t3a instance types (2.2)

### ISSUE THREAD

**Issue by ryanrca** [rancher/rancher#20372]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature Request:
Please add support for AWS t3a instance types (same performance as T3 but with 10% cost savings):

id | vCPU | ECU | Memory (GiB) | Instance Storage (GB) | Linux/UNIX Usage
-- | -- | -- | -- | -- | --
t3a.nano | 2 | Variable | 0.5 GiB | EBS Only | $0.0047 per Hour
t3a.micro | 2 | Variable | 1 GiB | EBS Only | $0.0094 per Hour
t3a.small | 2 | Variable | 2 GiB | EBS Only | $0.0188 per Hour
t3a.medium | 2 | Variable | 4 GiB | EBS Only | $0.0376 per Hour
t3a.large | 2 | Variable | 8 GiB | EBS Only | $0.0752 per Hour
t3a.xlarge | 4 | Variable | 16 GiB | EBS Only | $0.1504 per Hour
t3a.2xlarge | 8 | Variable | 32 GiB | EBS Only | $0.3008 per Hour

**Other details that may be helpful:**

This is the same request[ as this](https://github.com/rancher/rancher/issues/19826), but for Rancher 2.x:
https://github.com/rancher/rancher/issues/19826

**Comment by mohag** [comment]
The m5a series would be useful as well... (Somewhat cheaper AMD-based m5 alternatives)

(Dynamically detecting the available instance types might be the only way to keep up with them...) (Or a "custom" option allowing manual entry)

**Comment by ryanrca** [comment]
I especially like the custom option idea, to fill the gap between new EC2 instances and rancher releases.

**Comment by davidnuzik** [comment]
Version: master-head (7/11/19)

I can confirm the addition of these ec2 instance types (t3a and m5a) in the UI.

screenshot showing new t3a (burstable) additions to the Instance Type dropdown:
![image](https://user-images.githubusercontent.com/45179589/61091961-1b32a980-a3f9-11e9-9171-a2108aa930e1.png)

and m5a:
![image](https://user-images.githubusercontent.com/45179589/61092035-5fbe4500-a3f9-11e9-9fb6-b14be799b1ae.png)

Note m5 and m5d are now grouped together as well and we added a couple in (See the PR for details).
![image](https://user-images.githubusercontent.com/45179589/61092041-677de980-a3f9-11e9-8ad8-99a0a9f6a74e.png)

I could not test each and every single one of these, but did spot check several among the different groups. I reviewed the PR in order to make sure they all look correct. From what I can tell everything looks correct.

UI, HTTP ( id in nodepool call), API (nodetemplates, instanceType) all look good.
Confirmed for the instance types that I spot checked, they were all created correctly (AWS web console, ensure instance type matches).
