### ISSUE TITLE
Backport: Catalog APP - 404 error when cloning an app if the catalog is deleted

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20433]
Backport rancher/rancher#19593

**Comment by alena1108** [comment]
Can be tested with `v2.2.4-rc12`

**Comment by jiaqiluo** [comment]
Reopen the issue because deploying apps fails in v2.2.4-rc12.
 
<img width="701" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58360045-5bcf6700-7e3b-11e9-9868-37ac53910582.png">

**Comment by alena1108** [comment]
@jiaqiluo the fix for the last issue is in rancher/rancher:v2.2.4-rc15

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher v2.2.4-rc15

Steps are the same as the original issue

Result:
- instead of 404 error, Rancher shows the following errors
<img width="318" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58521707-38c1f180-8172-11e9-8d80-b235eeb812db.png">
 
<img width="487" alt="Screen Shot 2019-05-28 at 5 43 08 PM" src="https://user-images.githubusercontent.com/6218999/58521755-60b15500-8172-11e9-9001-823d37d22717.png">

**Comment by davidnuzik** [comment]
Rollback does not work. If you rollback and pick "Delete and recreate resources if needed during the rollback" you will get errors in the logs like `catalogtemplateversions.management.cattle.io "(CATALOG_HERE)" not found`

**Comment by westlywright** [comment]
A fix is available in `2.2.71` ui tag but this may not make it into 2.2.4.

**Comment by alena1108** [comment]
Will be available in v2.2.5-rc2

**Comment by davidnuzik** [comment]
Version: v2.2.5-rc2

I can confirm the issue is resolved. Upon deleting the catalog we see that the "Catalog Template not found" message appears (instead of rev upgrade status for the app). We also have no menu options except to view in API and delete, as expected.

![image](https://user-images.githubusercontent.com/45179589/59473999-de739280-8df9-11e9-93c1-f3d0ca5e9d72.png)

Both View in API and Delete function work correctly.
