### ISSUE TITLE
Zero (or little) downtime for Kubernetes upgrades

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20465]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Upgrade a Rancher provisioned Kubernetes cluster.

**Result:**
During the upgrade process, there is service interruption and downtime.

**Other details that may be helpful:**
According to the docs at https://rancher.com/docs/rancher/v2.x/en/cluster-admin/editing-clusters/ 
> "During the upgrade, your cluster is unavailable."

**Ideas/Solution:**
For Kubernetes deployments with two or more control planes, two or more workers, and three or more etcd servers, customers have the expectation that the cluster is fault tolerant and highly available. This includes the ability to perform Kubernetes upgrades with zero or minimal downtime. Stating "During the upgrade, your cluster is unavailable." is just not acceptable.

To make upgrades more fault tolerant and HA, the following can be considered:
- Make sure the control plane components are updated in a rolling fashion. If you have 3 control plane nodes running 3 kube-apiservers, only bring down and upgrade one kube-apiserver at a time. Once it's confirmed to be up, move on to the next one. Do the same for kube-scheduler and kube-controller.
- For etcd nodes, upgrade one at a time.
- For worker nodes, have the option to drain all workloads and cordon the node during the kubelet and kube-proxy upgrades.
- Consider allowing the end user to specify the batch size for worker node upgrades. Could be worker number or percentage (example, 5 workers at a time, or 20% of workers at a time).
- Make sure the upgrade order/process used by Rancher is documented so users know how the upgrade is happening.

Note, appears to have overlap with this issue - https://github.com/rancher/rancher/issues/17057

See also: https://kubernetes.io/docs/setup/release/version-skew-policy/

**Comment by FrederikNS** [comment]
Yes, I was just testing upgrades out on a 3 master, 3 worker cluster, and first the api server became unavailable, however only for a very short time. Then all the ingresses became unavalable, also only for a rather short time. I can however see that my normal workloads kept running through the upgrade, but were just unreachable due to the ingress controllers being unavailable.

I have been running kops clusters previously, where the process of upgrading nodes, start with masters and then worker. And only one node is first cordoned and drained, and then terminated. Due to AWS autoscaling groups new nodes are provisioned, and finally kops validates that all nodes are ready, and that all kube-system workloads are ready. Then it moves on to the next node.

This method has the added benefit of respecting Pod Disruption Budgets, due to draining the nodes before the upgrade.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/23038
