### ISSUE TITLE
[Windows] Cannot use Google LB on GCP

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20512]
rancher/rancher:v2.3.0-alpha3

Try to use Google LB with cloud provider configured in RKE.

But it doesn't work

**Comment by thxCode** [comment]
GCP cloud provider supported should be configured:
- The GCP cloud provider configuration sample: https://github.com/rancher/rke/issues/1329#issuecomment-490775878
- Rancher custom cluster with GCP cloud provider configuration example: https://github.com/rancher/rancher/issues/18207#issuecomment-491263788
- An example for Windows cluster:
```
...
cloud_provider:
  name: gce
  customCloudProvider: |-
    [Global]
    project-id=<your projcet ID, optional>
    network-name=<your network, optional if using default network>
    subnetwork-name=<your subnetwork of the above network, optional if using default network>
    node-instance-prefix=<your instance group name/your instance name specific prefix>
    node-tags=<your network tags, optional if not patching any tags>
services:
  kube-controller:
    extra_args:
      configure-cloud-routes: true # we need to allow the cloud provider configure the routes for the hosts
...
```
- The identity and API access on GCE hosts need `Computer Admin` permission, otherwise, the kube-controller-manager logs:
```
Reason: forbidden, Message: Required 'compute.routes.create' permission
Reason: forbidden, Message: Required 'compute.networks.updatePolicy' permission
```
- GCP cloud provider needs to specify the `Node Name`: https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#gce, https://github.com/rancher/rancher/pull/20174 could configure this automatically.

**Comment by sowmyav27** [comment]
verified with `2.3.0-alpha4`
able to create LB on a GCE cluster with cloud config
