### ISSUE TITLE
RFE: View CRDs

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20529]
Rancher version:
2.2.2

Description:
Currently if I have a custom resource definition, and resources that are based on that definition there is no way for me to view them. I would like to be able to view these resources in the ui (even if its not pretty or editable). 

Also, related to:
https://github.com/rancher/rancher/issues/18013

gz#4460

**Comment by laxmanpradhan** [comment]
I would like to vote for this as well. Since more apps are now using CRDs (like traefik), the Rancher GUI is mostly useless when managing these. Under the ressources drop down there should be an option to see and edit all CRDs that are in the cluster. 

It will be hard to design GUI elements around custom resources because there can be infinitely many of them. I would recommend the ability to 'pin' a specific type of resource to the resources tab. 

My suggestion would be something like this: Under the 'Resources' drop down there is another entry for 'Custom Resources'. If you click on the text itself, it goes to a page that lists all the CRDs that are currently defined. There should also be an option to star specific resources types so that they type appear as a sub-menu under Resources -> Custom Resources -> 'list of all Starred CRDs'.

**Example:** 
Resources -> Custom Resources -> IngressRoute
Resources -> Custom Resources -> MiddleWare
etc...

**Bottom Line:** Ability to create CRD and resources of that custom type. Ability to quickly navigate and browse through existing CRDs and custom resources. 

**Example Workflow:**
Lets say I want to setup Traefik as my reverse proxy / load balancer. Traefik requires several CRDs such as 'IngressRoute', 'Middleware', 'TLSOptions', etc. The main benefit to Traefik is that I can easily modify the IngressRoute or middleware to route traffic different without restarting anything. As such it's useful to be able to modify these resources as easily as possible. 

The first step in setting up Traefik is to apply a bunch of new CRD. So I would go to Resources -> Custom Resources (there is no sub-menu yet). The page show any CRDs that have already been defined. At the top there is a 'Create' button which opens a form. The form allows me to define a CRD either by form or by yaml. I use that to define CRDs for IngressRoute and Middleware.

Now the CRDs page shows these two new entries, but there should be some indicator that I don't yet have any resources that use these definitions. There should be an edit button next to each one but the 'star' button should be grey'ed out because I don't have any actual resources of this type yet. Next to each CRD there should be a 'Create' button that opens a form (with option for yaml editing) that will allow me to create a resources of that type. For example, next to the IngressRoute CRD I press the 'Create' button which opens a form that allows me to define a resource of type IngressRoute. I hit save and now on the Custom Resources page, there is an indicator showing that there exists 1 IngressRoute. The 'star' button for that CRD is now available as well. If I hit the star button, it will appear in the top navigation bar under Resources -> Custom Resources -> IngressRoute.

Now I can easily navigate to my IngressRoutes, edit them, create new ones, delete existing ones, etc. 

This will make rancher very useful for managing anything that uses a lot of CRDs like Traefik but also any future app that uses it's own CRDs. This brings together the strengths of the Rancher GUI with the flexibility of CRDs and still allows users to only add frequently used resources to the GUI without adding too much clutter. 

I believe some implementation similar to this will be essential for the viability of rancher given the rise in CRD usage. Without this, users will have to regularly use kubectl to manage things.

**Comment by gioppoluca** [comment]
This is really important to manage components like traefik for example

**Comment by mamiu** [comment]
@deniseschannon This issue can be closed due to [that comment from you](https://github.com/rancher/rancher/issues/18013#issuecomment-693495750).

Thanks a lot for all the great tools and your hard work @rancher team!
