### ISSUE TITLE
RFE: Pod health list

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20526]
Rancher version:
2.2.2

A view that shows pods that have many restarts and the ability to view why, i.e are they getting OOM Killed, etc. Should also be able to see every pod for which you have access rights regardless of namespace or project 
There should be a Global level, cluster level, project level set of views. 

gz#4458

**Comment by vincent99** [comment]
I'm not sure there's any concrete place to look that says "hey it's because it ran out of memory" other than maybe reading strings in events.  But for whatever info exists, for project level this is "just" more columns.

For cluster, it's probably impractical but at least conceivable.  The (Rancher) API does not currently getting or subscribing to "all namespaces".  I think this would end up requiring N+1 gets and watches, and be very bad at "design scale" (namespaces, nodes, pods/node, pods/namespace).

For global, it's "impossible" because it would require:
  - Constantly copying pod info from clusters into management (which has limited capacity, and users concerned about bandwidth usage as it already is)
  - Or simultaneously connecting to an unbounded number of clusters to get and watch an unbounded number of pods.

Rather than trying to create views of everything everywhere so that you can find bad things I think you'd probably be better off reporting up of "pods in bad states" from a controller in the cluster to the management plane.  Then those can be shown at any level, because they're centrally stored and limited in quantity.
