### ISSUE TITLE
RFE: Cluster Read Only Admin

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#20534]
Rancher version:
2.2.2

Description:
We would like to give some users the ability to see everything in the cluster, but not edit everything. They should still be able to edit their own projects. Right now we have to just give these people Admin and hope they don't do anything they shouldn't

gz#4463

**Comment by vincent99** [comment]
This is a role you can create yourself; inherit from `Kubernetes view`.

**Comment by dsargent3220** [comment]
That does not seem to do what we are looking for.
Here's how I tested it.

1. Added a new Cluster Role called  "Cluster Admin Viewer", had that role inherit from "Kubernetes view" role.
2.  Added a new user as a standard user
3   Granted the new user access to our test cluster using the "Cluster Admin Viewer"  role
4.  Logged into the new test account

Doing so allows me to see that the test cluster exists but no information about the cluster, the nodes or any of the projects

What we are looking for is the exact same thing a cluster admin  or better yet a Rancher admin can see but in a read only state.  I.e all data about Rancher, all its clusters and all of the nodes, projects, deployments and other resources.

**Comment by vincent99** [comment]
Ok yes; to see all clusters it would have to be a global role.

**Comment by ankur111** [comment]
This is how I was able to solve this. Does it work? The only thing is that I have to add the user to each cluster manually. 

<img width="1330" alt="Screen Shot 2019-06-07 at 12 04 18 PM" src="https://user-images.githubusercontent.com/16214682/59127415-70702c80-891c-11e9-8afe-802766359db3.png">

**Comment by dsargent3220** [comment]
@ankur111 This does appear to solve most of what we were wanting.  It's not a true Readonly Rancher admin,  but close enough.
It would be cool if you shipped a pre-built read only admin roll using settings like these.
FYI, I added a bunch more resource types in mine to flesh it out, things like: StatefulSets, Jobs, Events, etc  I have 20 resources total.  Still not sure I missed anything critical and this won't allow this user to see CRDs (I don't think)

**Comment by ankur111** [comment]
Thanks @dsargent3220. I think read-only admin could be a useful role. We will keep this in mind the next time we update our roles (no ETA yet)

**Comment by straffalli** [comment]
Hello,
Now with Rancher 2.4.x it is possible to create custom Global role, any idea on how to do some kind of Global Admin Read-only role?

**Comment by NielsH** [comment]
@straffalli did you ever figure this out?
I'm also trying to do this; I tried cloning `restricted-admin` and changing permissions to be only get+list+watch, however this does not appear to work. I cannot see the resources.

It's weird because even when not changing the cloned role, it appears the "real" `restricted-admin` role gives me permissions that the cloned `restricted-admin` role does not, when I assign the cloned role instead of the built-in role...

**Comment by NielsH** [comment]
I would still like to know this so would rather not close fwiw.

**Comment by ritheshgm** [comment]
+1, 

We wanted to add the groups with read-only permission, So they can view all the cluster and resources deployed in it and not able to edit/delete it. 

![image](https://user-images.githubusercontent.com/50571179/127834857-b36b173a-f2f8-4671-8635-2c70f149e7ba.png)


with above privilege we can able to see the clusters but not able to view deployments in project as shown below 

![image](https://user-images.githubusercontent.com/50571179/127834983-f7848b19-1145-4b82-b42f-74d8ce72bb39.png)

**Comment by NielsH** [comment]
I would still like to know this so would rather not close fwiw.

**Comment by larrycai** [comment]
I vote for this feature as well!

**Comment by NielsH** [comment]
I would still like to know this so would rather not close fwiw.

**Comment by NielsH** [comment]
I would still like to know this so would rather not close fwiw.

**Comment by Turb0Fly** [comment]
Same, highly interested in that. We have a need to create a role that will list all clusters, except the local one.  Users with that role shouldn't be able to change anything, just read only.

**Comment by Shaked** [comment]
> restricted-admin

I think this is related to the fact that the restricted-admin is hardcoded in Rancher: https://github.com/rancher/rancher/search?q=GlobalRestrictedAdmin 

I am trying to achieve the same - a power user with view only access, but it seems like it's impossible.

**Comment by pgdagenais** [comment]
We talked to Rancher about getting that feature added in a future version. It might help with the progress of the issue.

**Comment by DeMaBo** [comment]
Hey, there are still not very much updates on this topics. I'm also trying to create some custom roles, but as discussed before. There is an issue to see some resources on the cluster, if not restricted admin is used.
Even if I try to create the resources like the others. 

Something else, which I find confusing is that I can't only use a custom role and don't use the pre-created roles.
I provided also a Screenshot, maybe you can see what I meant to mean. 
![image](https://github.com/rancher/rancher/assets/27978252/2fd05704-afca-44eb-a1a0-24b7e6848f12)
 
Why its not possible to use my custom roles only? The problem is I don't get really the information from the docs to create some custom roles.

**Comment by pozimkiewicz** [comment]
+1 for this feature

**Comment by samjustus** [comment]
https://www.suse.com/c/rancher_blog/building-a-custom-read-only-global-role-with-the-rancher-kubernetes-api/
