### ISSUE TITLE
[RFE] Support cluster nodes using podman

### ISSUE THREAD

**Issue by lonewulf** [rancher/rancher#20544]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

Would it be possible to have support for cluster nodes that aren't running a docker daemon and are using podman instead ? (For example RHEL 8 servers).

Regards.

**Comment by pasikarkkainen** [comment]
Kubernetes has Container Runtime Interface (CRI) support, which allows using different container runtimes. Docker is the most used and mature runtime for kubernetes, but support for other container runtimes is available aswell in kubernetes.

Afaik Podman is a replacement/alternative for "standalone docker" in RHEL8 (and now in RHEL7 aswell), but podman is not actually required for kubernetes, as like said kubernetes has direct support for linux containers (without podman) via CRI, using other kubernetes container runtimes such as cri-o or containerd.

docker/podman/cri-o already use shared internal components/libraries, and (afaik) the plan is to share more components between podman and cri-o (for example libpod).

So maybe this request really should be about supporting other kubernetes CRI's directly, rather than trying to use the docker-CRI without docker? I know podman is mostly cli-compatible with docker, but I wouldn't be surprised to get many problems if trying to use kubernetes docker-CRI with podman.. it's probably better to use native alternative kubernetes CRI directly?

Just some random thoughts :)

**Comment by raul-gherman** [comment]
On Rancher master node(s), Rancher could be launched using:

$ podman run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher

instead of:

$ sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher

priviledged access (sudo) would not be required anymore, so less security concerns, less exposed surface

**Comment by joshuaganger** [comment]
Podman doesn't support '--restart'.  Instead it's necessary to use systemd services as described here: https://www.redhat.com/sysadmin/podman-shareable-systemd-services

Running Rancher with podman does seem successful although so far my attempts to bring up a new cluster using podman have not successfully finished provisioning.  I haven't looked deeper into the failure yet.

**Comment by azrdev** [comment]
Setting up a cluster (the `rancher/rancher-agent` image) apparently starts an etcd, but then the other components fail to connect to it.
I guess the missing docker socket /var/run/docker.sock is the first culprit.

**Comment by publicocean0** [comment]
interested in this feature

**Comment by Syntax3rror404** [comment]
interested in this feature +1

**Comment by markusg80** [comment]
interested in this feature +1

**Comment by heylix** [comment]
You can run podman with sockets, too. You "just" have to run `podman system service -t 0`

More information: https://www.mankier.com/1/podman-system-service, https://github.com/containers/podman/issues/6015

**Comment by volvicoasis** [comment]
Hello all, on a redhat8 node's, rancher ui start perfectly with podman. 
But, since you want to build a kube cluster, your etcd will fail to load.
Rancher agent use rename docker API method in order to manage etcd pod, podman doesn't support 
it at all, redhat say its better to rm and create it again...
Still thinking its a good idea to rancher support podman... even if.

Error coming from rancher ui :
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
[etcd] Failed to bring up Etcd Plane: Error response from daemon: Path /v1.24/containers/etcd/rename is not supported 

` podman info
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.22-3.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: a40e3092dbe499ea1d85ab339caea023b74829b9'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file`

Bien à vous,
J

**Comment by ifelsefi** [comment]
Please add podman support. It's not sustainable to require docker when it has been dropped by Redhat and various forks.

**Comment by rajha-korithrien** [comment]
Mr. Stale Bot, please don't close this ticket.
It is still quote relevant especially given that RKE2 supports not needing Docker. It would make sense that this feature should be placed into Rancher itself.

**Comment by Clocen** [comment]
Given the latest Docker [announcement](https://www.docker.com/blog/updating-product-subscriptions/) podman support of podman became whole a lot more important.

**Comment by xanderificnl** [comment]
Still interested.

**Comment by cragr** [comment]
## To run Rancher in Podman on a CentOS 10 Stream hosts I needed to do the following:


### Load Required Kernel Modules

CentOS 10 Stream requires additional kernel modules for container networking:

```bash
# Load the required modules
sudo modprobe iptable_nat
sudo modprobe iptable_filter
sudo modprobe iptable_mangle
sudo modprobe br_netfilter
sudo modprobe overlay
sudo modprobe ip_tables

# Verify they loaded
lsmod | grep -E "iptable_nat|br_netfilter|overlay"
```

### Persist Kernel Modules Across Reboots

```bash
sudo tee /etc/modules-load.d/k3s-rancher.conf <<EOF
iptable_nat
iptable_filter
iptable_mangle
br_netfilter
overlay
ip_tables
EOF
```

### Set Required Sysctl Parameters

```bash
sudo tee /etc/sysctl.d/90-k3s-rancher.conf <<EOF
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF

sudo sysctl --system
```

### Podman one-liner

```
sudo podman run -d \
  --name rancher \
  --restart=always \
  --privileged \
  --cgroupns=host \
  --network=host \
  --mount type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,bind-propagation=rshared \
  --tmpfs /run \
  --tmpfs /var/run \
  -v rancher-data:/var/lib/rancher:Z \
  rancher/rancher:latest \
  --http-listen-port=8080 \
  --https-listen-port=8181
```


## To run Rancher as a service in Quadlet I ran the commands above except the "Podman One-liner" and then the following:


### Create Data Directory

```bash
sudo mkdir -p /opt/containers/rancher
sudo chown $USER:$USER /opt/containers/rancher
```

### Create the Quadlet File

Create the container definition at `~/.config/containers/systemd/rancher.container`:

```ini
[Unit]
Description=Rancher container
After=network-online.target
Wants=network-online.target

[Container]
ContainerName=rancher
Image=docker.io/rancher/rancher:stable

# --- Security ---
# Required: Rancher runs K3s inside the container (containers-in-containers)
SecurityLabelDisable=true
PodmanArgs=--privileged
PodmanArgs=--cgroupns=host

# --- Networking ---
# Host networking avoids Podman bridge IP churn that corrupts K3s etcd endpoints
Network=host

# --- Mounts ---
# cgroup v2 filesystem — K3s needs read-write access with shared propagation
Mount=type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,bind-propagation=rshared

# K3s runtime directories
Tmpfs=/run
Tmpfs=/var/run

# Persist Rancher data (includes embedded k3s/etcd)
Volume=/opt/containers/rancher:/var/lib/rancher:Z

# --- Custom Ports ---
# Passed as arguments to the Rancher entrypoint
Exec=--http-listen-port=8080 --https-listen-port=8181

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=default.target
```

### Start the Container

```bash
# Reload systemd to pick up the new quadlet
systemctl --user daemon-reload

# Start Rancher
systemctl --user start rancher

# Enable on boot
systemctl --user enable rancher

# Check status
systemctl --user status rancher
```

### View Logs

```bash
podman logs -f rancher
```


## To run Rancher behind a reverse proxy like NginxProxyManger terminating TLS I needed to do the following:

### Append --no-cacerts to the Exec= line

```
Exec=--http-listen-port=8080 --https-listen-port=8181 --no-cacerts
```

##  Remove the strict CA verification env var from the agent on the downstream cluster
```
kubectl -n cattle-system set env deployment/cattle-cluster-agent \
  STRICT_VERIFY- \
  CATTLE_CA_CHECKSUM-
```

### Note: Claude helped troublehsoot and created most of this code.  
## Hope this helps someone else.

**Comment by adrianharabula** [comment]
As of today, using Podman Desktop on Mac, **with rootful podman machine**, Rancher UI works with this command:
```bash
podman run -d --name=rancher-ui --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:v2.13.3 \
  --no-cacerts
```

I arrived here because I was in rootless mode and Rancher UI was not provisioning.
