### ISSUE TITLE
Refresh issues with container stats in service details page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2057]
Server version - v0.38.0-rc1

Launch service details page.

In the following use cases , i dont see the container stats for the containers refresh.

1. Stop and Start service.
2. Edit service and scale up. The new container that shows up in the container list does not show the stats.
3. Stop one of the containers.
4. Delete one of the containers
5. Restart one of the containers.

When the page gets refreshed , i see the stats show up again.

**Comment by vincent99** [comment]
All of these are because the list of containers to watch is embedded in the token that the API sends to the UI which passes it on to the host-api.  Detecting that one of these conditions might have occurred, dropping the conncetion, requesting the stats token again, and reconnecting doesn't seem very practical, can we make the API smarter about sending newer containers?

There's a sort of tangentially related problem that the tokens get big quickly, and will eventually hit the 16k query param limit (already increased from 4k).

**Comment by vincent99** [comment]
Tokens are now in the database instead of entirely in the browser, but the underlying issue here is the same.. The token doesn't authorize access to the new containers though,
