### ISSUE TITLE
unable to recognize "management-statefile_path_redacted": Unauthorized

### ISSUE THREAD

**Issue by JannikZed** [rancher/rancher#20612]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
We had a major outage of our rancher HA setup and couldn't get it running again. We had to re-install and recover from an older backup. Our kubernetes cluster was in an older version during that time. Now we have a rancher server expecting our custom cluster to be version 1.11 but we are actually 1.13 with rotated certificates. We can't get it running now again. 
I don't know if this is an option, but adding the cluster somehow again should fix the issue, but I have no idea how to do this.

**Result:**
<img width="1056" alt="Screenshot 2019-06-02 at 18 06 23" src="https://user-images.githubusercontent.com/7526174/58763885-288a8780-8561-11e9-9edc-aed6bf282e16.png">

```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Failed to get Kubernetes server version: the server has asked for the client to provide credentials; exit status 1, unable to recognize "management-statefile_path_redacted": Unauthorized
``` 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher v2.2.2
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom

**Comment by Dayanand-Chinchure** [comment]
Any solution for this issue ?

**Comment by Dremor** [comment]
Got the same error on a fresh install (Rancher 2.3.5, Kubernetes 1.17.2-rancher1-2)

Kube-ApiServer show the following errors : 

`E0203 13:56:19.556372       1 webhook.go:109] Failed to make webhook authenticator request: the server rejected our request for an unknown reason
E0203 13:56:19.556411       1 authentication.go:104] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive, the server rejected our request for an unknown reason]`

**Comment by liorkesos** [comment]
happens to mem on 2.4.2
