### ISSUE TITLE
Could not link a service with Load Balancer

### ISSUE THREAD

**Issue by canthefason** [rancher/rancher#2063]
I am currently doing some PoCs with Rancher, and thinking about how we can utilize its functions with our new infrastructure. 

Actually I am able to link two services together. Since load balancers are also created as standalone services, I thought that we would be able to link a service with a load balancer, but I could not. 

Let me try to explain my case with an example. This is a regular link that I have created between two services:

![Image](https://cldup.com/jiZ8mjGJ96-3000x3000.png)

And after creating an auth service LB, I tried to link that with my email service. Unfortunately it did not work, and when I debug the email service, I realized auth service LB related environment variables are not created at all. 

![Image](https://cldup.com/mLYT3wcLp6-3000x3000.png)

Not sure if this is a bug, or if I am trying to push for some extra functionality, or if I totally misunderstood the concept.

**Comment by andrefreitas** [comment]
Can you post the configuration used for the balancer? I am linking services with balancers and they work.

**Comment by ccirello** [comment]
I just experienced this same issue. It worked once LB and containers were within the same host.

**Comment by deniseschannon** [comment]
@canthefason If you are trying to do authentication with your LB, it's additional configuration that is currently not supported. See the request: https://github.com/rancher/rancher/issues/1768, which actually will re-direct you to the request to be able to configure some custom defaults in your LB, which is just HAproxy. https://github.com/rancher/rancher/issues/1871

@ccirello 
In order to help us troubleshoot your problem, it would help if you provided some information on your set up.

* **Rancher Version:** Click on the cow icon in the upper left corner to provide us the info.
* **Rancher Setup:** What is your setup of Rancher? 
 * Single Node? HA? SSL Configuration? Anything special
 * Internal Rancher server DB, external DB? bind mount MySQL volume?
 * Authentication? GitHub, LDAP (With or without TLS), Local
* **Rancher Hosts:**
 * Is Rancher server on the same host as Rancher agent? If so, please make sure that the IP of the shared host has the server IP displayed in the UI. If not, please read more [about how to correct](http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#samehost).
 * If you’ve used Rancher’s managed network, can containers in host A ping containers in host B? You can check by exec into a container on Host A and ping the IP of a container on the Host B. 
 * If you see a host on the UI with IP (`172.17.42.1`) or starting with `172.17.x.x`, then please double check to see if the IP is the actual IP of the host. These IPs tend to be the docker internal IP and will not work. You will need to re-register your host with the [correct IP](http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#samehost).
* **Service/Load Balancer Issues:**
 * Provide your `docker-compose.yml` file for your stack by clicking on the paper icon in the detailed Stack View.

**Comment by ccirello** [comment]
@deniseschannon I am going to open a new issue to avoid clutter and link here.

**Comment by ccirello** [comment]
@deniseschannon please refer to https://github.com/rancher/rancher/issues/2164

**Comment by cusspvz** [comment]
> I just experienced this same issue. It worked once LB and containers were within the same host.

@ccirello could it be a Network Agent issue? I'm running tests since yesterday and I've notice today (scaled to multiple hosts) that services cannot communicate.

cc @vincent99 @deniseschannon

**Comment by ccirello** [comment]
@cusspvz I guess Network Agent is creating an internal network in the node, but not accross nodes.

**Comment by cusspvz** [comment]
I got it working, but I think this issue could be intermittent. At a certain point, i was unable to ping other containers and agents were always going down. In two cases I've been trough, agent/container was unable to make requests to `rancher-server`, and thats awkward because on host they worked correctly.

Minions restarts solved the agent/container issue but didn't solved the network issue.

Had to bootstrap entire cluster, now its working, but I'm not too confident to start using it on production.

**Comment by cusspvz** [comment]
Just to leave here some info, my tests had 3 environments and 15 hosts.

**Comment by deniseschannon** [comment]
@canthefason I'm going to close this issue as I believe you are looking for #1768

@cusspvz Typically if services/load balancers aren't able to communicate with each other, it's an issue with the hosts being able to communicate with each other. If you have a specific scenario where you don't see hosts communicating (easy test is to exec into the network agent container and ping the network agent container on a different host), then you'd have to fix that issue before containers would be able to communicate with each other.

**Comment by cusspvz** [comment]
@deniseschannon I realized and did just that after commenting here. :smile:

**Comment by gordontyler** [comment]
As described in #2164, I am experiencing an issue where the load balancer is not distributing traffic to multiple hosts. I have SSH'd into both Docker hosts and verified that they can ping each other. However, if I exec in the the network agent container on one host and try to ping the container IP of the network agent on the other host, I get no reply.

The Docker hosts are Centos 7 VMs running in vSphere with Docker v1.7.1 that I added to the Rancher environment by running the command from the Custom tab of the Add Host page.

**Comment by gordontyler** [comment]
I have this working now.

After I had posted the above, I noticed that the IP address in the Rancher UI for the host on which the Rancher server was also running had a bogus IP (172.x.x.x, but it should have been 10.4.x.x). I then read the FAQ entry regarding this problem, and recreated my entire Rancher setup from scratch and used the CATTLE_AGENT_IP env var when connecting my two hosts to the Rancher server. The hosts now show up with the correct IP address in the Rancher UI and setting up the same stack now has traffic load balanced across all the instances across both hosts.

**Comment by Rucknar** [comment]
We just hit a similar issue, thanks to the comment above from @deniseschannon we realised the agent's couldn't ping each other. After further investigation we found we had 4x agent-instance containers running per host. No idea how or why but stopping all 4 and letting the agent re-create just one fixed the issue.
