### ISSUE TITLE
Feature: granular features to selectively choose what to forward

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#20643]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Information**

When enabling cluster level logging the customer would like for the configuration form to be more configurable in what gets forwarded. They would like to be able to say disable kubelet logs, but enable kube-apiserver logs for example.

> We are working with splunk and are testing cluster level logging.  When we enabled it, it was a firehose of data – most of it unnecessary.  Has Rancher reduced overall cluster level logging or provided granular features to selectively choose what to forward?

gzrancher/rancher#5657

gzrancher/rancher#11732

gzrancher/rancher#10713

gzrancher/rancher#4556

**Comment by dnoland1** [comment]
As part of this request, would it also be possible for cluster level logging to be able to ignore logs from a namespace or project?

**Comment by Tejeev** [comment]
Recently I've had the following request and I think it related as these are all related to expanding the configurability of logging. Should be noted that this might expose the node logs to project users so might be better as a separate request anyway?  Would it be viable to have a admin level configurable logging solution to aggregate logs with more configuration options?

> At the moment the UI allows configuration to use certain fluentd outputs but no configuration for input/parsing/filtering (also flexibility to exclude some logs). Not sure it would be feasible to have a UI for this, but some way to add these configuration stanzas into the existing default configuration in a way that it would persist updates etc. – perhaps similar to the existing ”Edit as File” option for the output?
> 
> In our case, for certain applications we need to consider how to take the fluentd input from different log file paths and also some applications need to send the logs via tcp directly to fluentd. So perhaps using env variables or env config maps we could add config stanzas to the existing default configuration…

**Comment by granttr** [comment]
Having the option to disable logging for certain namespaces at project or cluster level would be very useful - is that what is planned as part of this feature?

At the moment, I think the fluentd configuration delivered by the rancher-logging app is very basic in what it can do. For example, using elasticsearch, enabing project level logging will route all /var/log/containers/* within that project to one index (even worse for cluster level logging). We would like to have ability to filter and send certain pod/container logs to individual indexes directly.

If it were possible to edit the default rancher-logging-fluentd secret values, without the configReloader reverting the changes, we could customize this fluentd configuration?

This issue is open a year now, so perhaps there is not much appetite for this out there... how are others handling fluentd configuration within Rancher I wonder - thanks!

**Comment by cbron** [comment]
Bumping to 2.5.x as this is not part of initial first-class support for v2.

**Comment by paynejacob** [comment]
This is supported as of 2.5.0 in logging V2 with the use of Flows and ClusterFlows.  See the example section here https://rancher.com/docs/rancher/v2.x/en/logging/ for how to restrict logs to a single namespace. For more complex use cases see https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/flow_types/.
