### ISSUE TITLE
Istio - When editing sidecar auto-injection, workloads should be redeployed

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20712]
rancher/rancher:master 1c18dda3 6/6

When editing a namespace to enable/disable sidecar auto-injection, the workloads in the namespace should be redeployed to add/remove sidecars as expected. 

Current:

* Without auto-injection enabled, create a workload
* Enable auto-injection
* Workload does not redeploy with sidecar

Expected:
* All workloads in the namespace should be redeployed.

**Comment by loganhz** [comment]
This is an Istio feature. Istio has a controller for auto-injection. 

We don't want to change Istio's behaviour due to the following reason.

1. We should bring the original istio user experience
2. Istio is doing this by design
3  We would like to have Rancher and Istio code decoupled. So we don't want to add other controller for it.

Injection occurs at pod creation time. Kill the running pod and verify a new pod is created with the injected sidecar. The original pod has 1/1 READY containers and the pod with injected sidecar has 2/2 READY containers.

https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#automatic-sidecar-injection


Can we provide a warning message for it?
Once users editing it, we should show the warning says you need to re-create the pod manually for it.

**Comment by deniseschannon** [comment]
Per @ibuildthecloud, this behavior is expected and we will add in warnings that workloads will need to be redeployed.

**Comment by bmdepesa** [comment]
#20836 for the related warning
