### ISSUE TITLE
[v2.2.4] Openstack cluster creating failed: ssh private key is filled with the path

### ISSUE THREAD

**Issue by antoine-rehm** [rancher/rancher#20721]
Version: v2.2.4

What kind of request is this (question/bug/enhancement/feature request):
Bug

Steps to reproduce (least amount of steps as possible):

Create a new cluster with openstack cloudprovider.
Waiting for instance creation.
The cluster creation failed due to waiting too long for ssh avability.

To understand what is going wrong, I try to download instance keys through rancher. It appears that the id_rsa is filled with the file path instead of the content of the file.

rollback to 2.2.3 corrected the issue.

**Comment by sangeethah** [comment]
@antoine-rehm When creating openstack cluster, are you providing a privateKeyFile in the node template which points to a file location ?

**Comment by antoine-rehm** [comment]
@sangeethah Yes, I provided an absolute path in the privateKeyFile it's work in rancher 2.2.3 but not in 2.2.4.
If i filled the privateKeyFile input with some random text, the instance keys zip have a id_rsa file with this random text.

**Comment by sangeethah** [comment]
@antoine-rehm In rancher server version - v2.2.4 , we have changed all  file path related fields to content based fields in node template drivers. As part of this fix , privateKeyFile field was modified to start accepting actual contents of the private keys instead of an absolute file path containing the key content. We will have this change documented . The description field had been changed to reflect this change but we will have better documentation around the changes being made.
![image (1)](https://user-images.githubusercontent.com/4266958/59124993-f3da4f80-8915-11e9-8253-e7bf79a7b2e6.png)

If you have the actual key contents entered in privateKeyFile, you should be able to get the nodes to provision successfully.

**Comment by antoine-rehm** [comment]
@sangeethah Ok, thanks you for the explanation about the new input form.
But to make it work I tried to simply paste the content of the privatekey but it didn't work. 
Next, I tried to make it one line it didn't work.
By now, the only solution that work is to edit the value through the api and replace new line with \n (if you paste \n in the form the value become \\n ).

**Comment by cjellick** [comment]
We're working on a fix that will make this multi-line

**Comment by cjellick** [comment]
@antoine-rehm what version of openstack are you using? I'm trying to test Rancher's openstack integration and need this as a data point.

**Comment by cjellick** [comment]
@sangeethah this should have been moved over to test awhile ago

**Comment by sangeethah** [comment]
UI support for Multiline fields has been validated as part of - https://github.com/rancher/rancher/issues/20789

**Comment by antoine-rehm** [comment]
@cjellick @sangeethah Thanks for your work, sorry to not response about openstack version. I was in vacation. I will test the new field when 2.2.5 is out.
