### ISSUE TITLE
[monitoring] operator & grafana not honoring node selector rules

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#20730]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Enable Cluster Monitoring with a selector to drive workloads to be scheduled. For example you could use `node-role.kubernetes.io/controlplane=true`

**Result:**

Grafana & Prometheus Operator get scheduled on random nodes and do not have the node scheduling rule put in place.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
Could you try if it works if you don't use `true`, `false` or `number` as the value of the selector, please?

**Comment by ekristen** [comment]
Neither work.

It's not a problem of the label and it's value, the selector rules you add when enable monitoring are simply not being added to Grafana & Prometheus Operator.

**Comment by ekristen** [comment]
* `prometheus-cluster-monitoring` - OK (gets the label)
* `grafana-cluster-monitoring` - NOT OK (does not get the scheduling label)
* `exporter-node-cluster-monitoring` - DaemonSet, so it's not needed.
* `exporter-kube-state-cluster-monitoring` - NOT OK (does not get the scheduling label)

**Comment by jiaqiluo** [comment]
The bug is reproduced on Rancher: mater 6/12

the result is the same as @erikwilson 's comment:

only the workload `prometheus-cluster-monitoring` gets the node selector

**Comment by jiaqiluo** [comment]
The bug is reproduced in rancher:v2.2.7 and the bug fix is validated in rancher: master-head bc3700f8

Steps:
- run rancher container single install
- add a DO cluster wither 1 etcd, 2 control plane, 2 worker
- enable the cluster monitoring with the selector `node-role.kubernetes.io/worker=true`
- enable the project monitoring with the selector `node-role.kubernetes.io/worker=true`


Result:
 - For cluster monitoring, the selector is applied to workloads 
	- `exporter-kube-state-cluster-monitoring`
	-  `grafana-cluster-monitoring`
	- `prometheus-cluster-monitoring`
	- `prometheus-operator-monitoring-operator`
- For project monitoring, the selector is applied to workloads 
	- `grafana-project-monitoring`
	- `prometheus-project-monitoring` 
	- `prometheus-operator-monitoring-operator`
