### ISSUE TITLE
[Bug] Liveness probe host configuration lost after UI modification

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#20749]
Rancher Version: 2.2.4

Step to reproduce:
1. Create a 1.13.5 k8s cluster with calico network. The calico node daemon set will have liveness probe configuration as below when viewing yaml. The host: localhost configuration is not supported by UI so not displayed in UI view.

        livenessProbe:
          failureThreshold: 6
          httpGet:
            host: localhost
            path: /liveness
            port: 9099
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

2. Click update or redeploy to redeploy the daemon set through UI without changing any configuration. 
3. View yaml again after step 2. The host:localhost configuration is missing.
4. The liveness probe will connect to pod IP by default without the host: localhost configuration. As calico node only listens on 127.0.0.1, the daemon set will fail in liveness check and be recreated again and again.

**Comment by pengjiang80** [comment]
https://github.com/rancher/rancher/issues/19992

**Comment by pengjiang80** [comment]
[https://github.com/rancher/rancher/issues/19992](url)

**Comment by wanshaoyuan** [comment]
We found that the canal network plugin also has this problem.

**Comment by loganhz** [comment]
View API doesn't show the host field. So we need a backend fix as well

**Comment by jiaqiluo** [comment]
Following the steps in the issue, the bug is reproduced in Rancher:v2.2.6 in those two clusters:
- K8s v1.14.3(default version), network Provider: Canal
- K8s v1.14.3(default version), network Provider: Calico

The bug fix is validated in Rancher:master-head 895f8dd1 in those two clusters:
- K8s v1.15.0(default version), network Provider: Canal
- K8s v1.15.0(default version), network Provider: Calico

Result:
- after updating or redeploying the daemon from the UI, it becomes active again and the `host: localhost` line is preserved in the YAML file.

**Comment by fjoesne** [comment]
I'm experiencing this behavior on 2.2.8, could it be something else, or am I missing something?
