### ISSUE TITLE
Backport: Update UI for nodedriver fields

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#20789]
Backport rancher/rancher#20787

**Comment by alena1108** [comment]
Will be available in `v2.2.5-rc2`

**Comment by davidnuzik** [comment]
Version: v2.2.5-rc2

I carefully tested again like as was done in the source issue in v2.3 milestone but with v2.2.5-rc2:

I can confirm that we now see multi-line fields for fields that have UI hints.
For example, with openstack, privateKeyFile and is a multi-line field.
Also, userDataFile has been added in the API and this too is multiline. They don't initially appear as multiline (not apparent) but they are indeed multiline and in my browser I can use the handle at the bottom-right to expand these:

![image](https://user-images.githubusercontent.com/45179589/59386289-2374c780-8d1b-11e9-810b-046eb0bc6ccd.png)

![image](https://user-images.githubusercontent.com/45179589/59386298-27a0e500-8d1b-11e9-8363-ac235912e1b5.png)


![image](https://user-images.githubusercontent.com/45179589/59386309-35ef0100-8d1b-11e9-8572-39484860053d.png)

![image](https://user-images.githubusercontent.com/45179589/59386324-3e473c00-8d1b-11e9-8cbf-c087d7888bb8.png)

We do not have test accounts for other providers that might utilize ui hints, but the expected behavior is exactly the same. This is for situations where a UI is not provided by 3rd party drivers only so testing openstack should be sufficient.
