### ISSUE TITLE
Error viewing some graphs in Kiali

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20835]
rancher/rancher:master 7a23ff88

* Create cluster
* Enable istio
* Create a service and generate some traffic
* Click Graph
* Select Service Graph
* User is presented with an error
![Screen Shot 2019-06-11 at 2.02.01 PM.png](https://zube.io/files/rancher/d115588b809d69bb3229b11a041c33db-screen-shot-2019-06-11-at-2-02-01-pm.png)

* Click Applications
* Select a service
* Click the Traffic tab
* User is presented with an error:
![Screen Shot 2019-06-12 at 11.37.35 AM.png](https://zube.io/files/rancher/7ebc6288dff68dca79be926434521e45-screen-shot-2019-06-12-at-11-37-35-am.png)

**Comment by loganhz** [comment]
It should be a Kiali issue. It's an error from Kiali server.

**Comment by rancher-max** [comment]
Should be fixed in v2.3.4:

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/55997940/72273737-1d640380-35e8-11ea-8d80-b6fc486cbd4d.png">

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/55997940/72273800-3cfb2c00-35e8-11ea-875d-8a23ae5e9fa2.png">
