### ISSUE TITLE
Rancher UI Project’s Tab  Click Event Bug

### ISSUE THREAD

**Issue by echo-layker** [rancher/rancher#20845]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

install rancher v2.2.4 by HA

create cluster， choose cluster，click tab tools， can not select  a subtag,  when you move down point, the tab disapear and show again!

![image](https://user-images.githubusercontent.com/10571512/59413142-918bbe00-8df1-11e9-8997-b3477f5f072a.png)

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
V2.2.4
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Custom
VM
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by davidnuzik** [comment]
Possibly related to https://github.com/rancher/rancher/issues/20627

**Comment by watersoona** [comment]
maybe cause by rancher monitor 
because my rancher enabled  cluster monitor， prometheus-cluster-monitoring can't start up.
this is log :

  |   |   |  
-- | -- | -- | --
Normal | SuccessfulCreate | create Pod prometheus-cluster-monitoring-0 in StatefulSet prometheus-cluster-monitoring successful | 15 minutes ago
Warning | FailedCreate | create Pod prometheus-cluster-monitoring-0 in StatefulSet prometheus-cluster-monitoring failed error: The POST operation against Pod could not be completed at this time, please try again. | 15 minutes ago

and restart again and again ! 

and I disable monitor , this ui bug disappear !
