### ISSUE TITLE
AWS Security Group List Has Invalid Groups in Add Host Workflow

### ISSUE THREAD

**Issue by alexderz** [rancher/rancher#2084]
When adding a new AWS host, the security group list shows the Group name. It is not unlikely that those are uninformative (eg, I had 5 'default' groups, of which only 1 really applied to the VDC I had selected).

I recommend that either:
1. The group ID is printed as well to exactly identify the group
2. And/or only the groups assigned to the selected VDC are shown

Thanks!

**Comment by vincent99** [comment]
This was changed to limit the groups shown to the VPC that is selected a long time ago.  Added the ID display, though you still can't tell docker-machine to select a group by ID.  Also filtered out the `launch-config-`ones you get automatically when creating instances in the AWS UI, since they're plentiful and usually useless.

https://github.com/rancher/ui/commit/88a99f0f509c9a8f9ef450515357d24f3b94af25#diff-2479348455bdf3f7aa13c2bcecf550b8L159

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
