### ISSUE TITLE
CPU/Storage/Network stats graphs for host  are empty when reported stats are 0.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2086]
Server version - Build from master - sep 21

CPU/Storage/Network stats graphs for host are empty when reported stats are 0.

<img width="1602" alt="screen shot 2015-09-21 at 9 58 23 am" src="https://cloud.githubusercontent.com/assets/4266958/9998722/78f079ac-6047-11e5-89cc-783048f9baa8.png">

**Comment by vincent99** [comment]
This is because the stats socket is sending duplicate frames with the same timestamp in some situations.  @wlan0 is looking into why and if we can fix that, but I suspect that is just what cAdvisor does when the container has not run at all so the stats haven't changed.

The UI compares the current and previous frame to calculate the CPU % and Network and Storage kbps... but the time difference is 0, so (current - previous)/(time difference) => divide by 0.  I changed this to consider that point a 0 (%/kbps) if this happens.

**Comment by deniseschannon** [comment]
CPU/Network seems to be working in v0.38.1

![screen shot 2015-09-22 at 2 47 27 pm](https://cloud.githubusercontent.com/assets/11410997/10032599/e275e712-6138-11e5-88b5-875d7f0bfb09.png)
 but not for Storage.

**Comment by vincent99** [comment]
d'oh.. storage will be fixed next release for this duplicate timestamp case.

**Comment by deniseschannon** [comment]
Verified with v0.39.0-rc1
