### ISSUE TITLE
HPA changes

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20866]
* [x] Add warning in order to use Prometheus with HPA, you'll need to deploy prometheus adapter - link this to the current issue for deploying prometheus adapter and make a note in the prometheus adapter PR that the warning should be removed when we automatically deploy it.

**Comment by loganhz** [comment]
There is no way to detect the current HPA api version until we fix https://github.com/rancher/rancher/issues/20693

So I will use https://github.com/rancher/rancher/issues/20693 to track it.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/14/19)
I can confirm that we now get the following messages if we do not have CPU/Memory reservation set on our workloads we want to use for HPA. Or pick Metric types other than Resrouce.
(From the PR)
```
      warning:
        custom: "In order to use custom metrics with HPA, you need to deploy the custom metrics server such as prometheus adapter."
        external: "In order to use external metrics with HPA, you need to deploy the external metrics server such as prometheus adapter."
        cpu: "CPU reservation is not set in the selected deployment. HPA will not be able to compute the replica count based on CPU utilization."
        memory: "Memory reservation is not set in the selected deployment. HPA will not be able to compute the replica count based on memory utilization."
```
Reservation type (CPU and Memory)
![image](https://user-images.githubusercontent.com/45179589/59533918-b5a6d800-8ea1-11e9-87bc-353406ff23f9.png)
![image](https://user-images.githubusercontent.com/45179589/59533932-bc354f80-8ea1-11e9-9431-3d7051814be7.png)

Pods/Object types:
![image](https://user-images.githubusercontent.com/45179589/59533965-d4a56a00-8ea1-11e9-8379-5ced790295ae.png)

External type:
![image](https://user-images.githubusercontent.com/45179589/59533975-dbcc7800-8ea1-11e9-8567-0e342a915622.png)


I made sure that if I have other workloads which DO have reservations and pick those the messages go away.
I only lightly smoke tested HPA to ensure it is still working as expected because the changes are just light changes on the UI (reviewed PR).
