### ISSUE TITLE
Expose DeleteNotReadyAfterSecs in the UI for nodepools

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#20862]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature
Nodepools now have an additional field on the `Spec` field, `DeleteNotReadyAfterSecs` which defaults to the int64 value of `0`. This new field indicates whether Rancher should, after _x_ number of seconds, recreate nodes that have been marked as unreachable by Kubernetes. 

**Steps to reproduce (least amount of steps as possible):**
Spin up a node pool, set a value greater than zero on the field, and then turn off the node/ delete it. Rancher should delete the node and spin up another one with the same name. 

**Result:**
- [x] Strong indication if `DeleteNotReadyAfterSecs` is > 0 since this can results in additional customer costs if it is enabled. 
- [x] `DeleteNotReadyAfterSecs` should be settable via the UI and should not requre viewing the nodepool in the API

**Other details that may be helpful:**
The user should pick a value like 120 seconds since there are multiple controllers that have to run. Very low values, ie < 10 likely would require tuning the node controller to run more often.
Furthermore, this field will also need to accommodate fairly large values since the time is in seconds, ie 86400 seconds is 24 hours.

**Comment by cjellick** [comment]
@daxmc99 please update this for the new field name (and the dropping of selfHeal)

**Comment by davidnuzik** [comment]
Version: master-head (7/16/19)

The UI now exposes this, but in minutes, the UI will convert the minutes (which makes sense to me based on comments in this issue's description) entered by the user into seconds for the `deleteNotReadyAfterSecs` field. 1 min = 60 and etc. I tested with several values and they all appear to work correctly including a value of 0 (0 secs) and 1 (60 secs).

This appears to essentially delete the node after the time is up (new logic), and then a new node automatically gets created based on existing logic we have.

A value of 0 means we don't do anything (traditional way of handling). This is to say, that rancher won't delete the node that stopped posting status.
![Screen Shot 2019-07-16 at 4 31 16 PM](https://user-images.githubusercontent.com/45179589/61336710-2f0a5100-a7e7-11e9-98ea-d7a3a24257a4.png)

A value of 1 or greater (in the UI) means we will delete the node after 60 (or more) seconds. Again, as mentioned earlier UI does this in minutes, then sends to backend the value in seconds.

Screenshot of node down:
![Screen Shot 2019-07-16 at 4 34 02 PM](https://user-images.githubusercontent.com/45179589/61336795-92947e80-a7e7-11e9-9531-bb85b80742ce.png)

About one min later (1 entered in UI) node is deleted and starts provisioning new:
![image](https://user-images.githubusercontent.com/45179589/61336816-a8a23f00-a7e7-11e9-8009-14772e4175f4.png)

---------

Here is what you see in the UI when creating nodePools now:
![image](https://user-images.githubusercontent.com/45179589/61336854-d38c9300-a7e7-11e9-91e0-e47fdb1f59e7.png)

Notice the red text (for indicating count of etcd, cp, worker roles) is now offset created a separate issue to track this styling issue: https://github.com/rancher/rancher/issues/21576

When you hover over the new field you'll see a useful tooltip (as described in UI PR)
![image](https://user-images.githubusercontent.com/45179589/61337087-be643400-a7e8-11e9-9b83-4842677e9c36.png)
This is helpful, but too has an issue. It doesn't really explain that a value of 0 means we basically do nothing (I think it should ideally). I created a separate issue for that here: https://github.com/rancher/rancher/issues/21578

**Conclusion:**

The core functionality appears to be working as expected based on numerous tests I have performed.

I also did my regular UI/API/HTTP checks. i.e. attempt to input invalid values, etc. The UI blocks this and only allows positive integers. Numbers with zeros in front are ignored ("01" == "1"). I couldn't really break it. I tried extremely long ints (even greater than int64) -- this created extremely larger values like "deleteNotReadyAfterSecs: 6e+71" but it didn't appear to actually hurt anything even when reviewing backend logs (rancher logs).

Since the UI currently doesn't do any limitations on fields (limit length of strings/ints) we can enter today, I am not going to worry about this currently, this is how things work elsewhere.

Editing the cluster and changing the value is also working correctly as well. I can also change back to 0 at any time (edit) and this will never delete my node.

My testing was done primarily with worker nodes as well as nodes with CP+Worker roles. I tried with nodes that also have etcd role but keep in mind you can only expect so much out of etcd -- this would not always work well based on the limitations of etcd.

**Comment by davidnuzik** [comment]
Todo list (will delete this comment later):

I want to do a couple more tests with nodes with different roles, count of nodes in pool, etc. I did some with worker+CP but would like to do more as well as with etcd role (etcd will be limited testing though I can only expect so much out of that based on etcd limitations).

**Comment by davidnuzik** [comment]
Added an additional test, in API set to a value not divisible by 60, such as "45" seconds. If do this then edit cluster in UI, UI will show value correctly:

![image](https://user-images.githubusercontent.com/45179589/61477238-a3f29d80-a943-11e9-971a-c2a9402597a9.png)
