### ISSUE TITLE
Istio changes

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20865]
* [x] Change "service mesh" links to "Istio", Change "Cluster Service Mesh" to "Istio"
* [x] Note/Warning in the UI that sidecar injection needs to be enabled for each namespace. For any existing namespaces, you will need to enable the feature and re-deploy. "In order to leverage Istio, you will need to enable Istio sidecar auto injection for each namespace. If you enable it on an existing namespace, any existing workloads will need to be re-deployed to leverage the sidecar auto injection."
* [x] Add Istio icon next to namespace names for any namespace that has sidecar injection turned on. 
* [x] In traffic graph view, add in kiali logo with a note that says "Powered by Kiali" in the bottom right corner
* [x] Add in version dropdown for istio as we did for monitoring.
* [x] Enabled Mixer Policy -> Enable Mixer Policy

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (6/14/19)
This covered lots of little changes. I took the summary from the PR and addressed how I tested each area below. Each bullet is each change done.

- **Change "service mesh" links to "Istio", Change "Cluster Service Mesh" to "Istio"**
https://github.com/rancher/ui/pull/3058/commits/09c43455875aff8f5213c1d04e194509dfdf8792

Confirmed that the link on the nav bar now reads "Istio" and that Tools > menu now shows "Istio" and that config page header now shows "Istio"
![image](https://user-images.githubusercontent.com/45179589/59534973-8e9dd580-8ea4-11e9-8316-5caa3803c3a3.png)
![image](https://user-images.githubusercontent.com/45179589/59534989-96f61080-8ea4-11e9-8186-0a8adea80ade.png)
![image](https://user-images.githubusercontent.com/45179589/59534997-9eb5b500-8ea4-11e9-8e1d-85cef01cd5a7.png)

- **Note/Warning in the UI that sidecar injection needs to be enabled for each namespace. For any existing namespaces, you will need to enable the feature and re-deploy. "In order to leverage Istio, you will need to enable Istio sidecar auto injection for each namespace. If you enable it on an existing namespace, any existing workloads will need to be re-deployed to leverage the sidecar auto injection."**
https://github.com/rancher/ui/pull/3058/commits/09c43455875aff8f5213c1d04e194509dfdf8792

notEnabled:
![image](https://user-images.githubusercontent.com/45179589/59535166-0f5cd180-8ea5-11e9-8eda-8e20bcd79802.png)

enabled:
![image](https://user-images.githubusercontent.com/45179589/59535492-fbfe3600-8ea5-11e9-89fe-d8dc31f478cd.png)

- **Add Istio icon next to namespace names for any namespace that has sidecar injection turned on.
In traffic graph view, add in kiali logo with a note that says "Powered by Kiali" in the bottom right corner**
https://github.com/rancher/ui/pull/3058/commits/d5636f2578d3e72c9b3b2ecf6fc5ecb14192dc44

![image](https://user-images.githubusercontent.com/45179589/59536408-8051b880-8ea8-11e9-8517-64d9b009fd0c.png)
This is to the bottom-right of the Kiali chart (Traffic Graph) and scales well and properly with various window sizes (no glitches in placement, etc). Clicking on it bring us to https://www.kiali.io/

- **Add in version dropdown for istio as we did for monitoring.**
https://github.com/rancher/ui/pull/3058/commits/e371628a03819e5ca0a7fa4c4791d25f71797f5d
![image](https://user-images.githubusercontent.com/45179589/59535293-711d3b80-8ea5-11e9-82b1-e9bc708a1508.png)

Currently, as of preview2 release, hard-coded version in the UI. This will be used later in https://github.com/rancher/rancher/issues/20617

- **Enabled Mixer Policy -> Enable Mixer Policy**
https://github.com/rancher/ui/pull/3051
![image](https://user-images.githubusercontent.com/45179589/59535190-213e7480-8ea5-11e9-89f2-f757493587ba.png)
(This was already fully validated with https://github.com/rancher/rancher/issues/20840 )

- **Istio - Warn user that workloads will need to be re-deployed when editing sidecar auto-injection on namespace**
https://github.com/rancher/ui/pull/3058/commits/4dded84ef5acd18866bb7afeefc80ab67e7978ee

Only when we edit our namespace and pick "Enabled" do we see the message.
When you create a _new_ namespace and click "Enabled" you do NOT see the message (as expected because we could not possibly have any workloads in this ns yet).
You will see this message when you edit a namespace and Enable the auto-injection regardless if there are any workloads or not. I think this is okay.
![image](https://user-images.githubusercontent.com/45179589/59536329-42549480-8ea8-11e9-91b9-f104d6715160.png)


Last, smoke tested Istio config (ensure UI and app answers match, http good, actual memory/cpu requests/limits correct, etc)
