### ISSUE TITLE
[2.2 Backport] Make k8s 1.14 an officially supported

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20873]
Backport https://github.com/rancher/rancher/issues/19522

**Comment by davidnuzik** [comment]
Also needs quick UI check that kube-node-lease is now in System project.

**Comment by alena1108** [comment]
Can be tested with rancher v2.2.5-rc3

**Comment by jiaqiluo** [comment]
Automation tests are done and passed on the following imported clusters,
K8s version:  v1.14.3-rancher1-1
- Ubuntu 16.04   - docker version 18.09
- Ubuntu 18.04   - docker 18.09
- RHEL 7.6         - docker 1.13 (native)
- ROS 1.5.1        - docker 18.06 (native)
- SLES - 12 SP2 - docker 18.06

**Comment by sowmyav27** [comment]
Verified the below scenarios on `v2.2.5-rc6`

HA cases relating to Control and Etcd planes: (k8s v1.14.3)
**Etcd plane HA:** Verified -  Logged - https://github.com/rancher/rancher/issues/20956 - cluster fails to come up when the etcd node is powered down but NOT deleted

1. Create AWS custom cluster with 3 etcd nodes (`etcd1` , `etcd2` , `etcd3`) and 1 control and 2 worker nodes.Make sure cluster is functional.
2. Power down one of the etcd nodes , say `etcd1`. Make sure cluster is functional by adding new workloads successfully. (The node will go into Unavailable state. On adding an etcd node in this state will give you the issue mentioned above)
3. Delete the powered down node  - `etcd1` . Make sure cluster is functional by adding new workloads successfully.
4. Add a new etcd node , say `etcd11` .Make sure cluster is functional by adding new workloads successfully. (The cluster comes up successfully)
5. Repeat steps 2-4 for the remaining 2 nodes - `etcd2` , `etcd3`, so that we end up with a cluster with all 3 new etcd nodes (from the initial creation).
6. Make sure cluster continues to be functional.

**Control plane HA: Verified**

1. Create AWS custom cluster with 3 etcd nodes (`etcd1` , `etcd2` , `etcd3`) and 1 control nodes `ctl1`  and 2 worker nodes.Make sure cluster is functional.
2. Add a new control node say `ctl2`
3. Power down the first control node , say `ctl1`. Make sure cluster is functional by adding new workloads successfully. (The node will go into Unavailable state)
4. Delete the powered down node  - `ctl1` . Make sure cluster is functional by adding new workloads successfully.

**Comment by sowmyav27** [comment]
`kube-node-lease` is seen under System project 
<img width="630" alt="Screen Shot 2019-06-19 at 9 50 47 AM" src="https://user-images.githubusercontent.com/26032343/59784672-ddb68280-9277-11e9-9401-bc6338136c77.png">

**kubectl version**
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
