### ISSUE TITLE
Support Istio Virtual Service and Destination Rule as first class resources

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20894]
Support Istio Virtual Service and Destination Rule as first class resources in Rancher UI just like Workloads.

We should use https://github.com/rancher/pkg/tree/rancher/apis/istio/v1alpha3 for types

**Comment by loganhz** [comment]
UI is not merged. So we can only test it via API in master build now

**Comment by bmdepesa** [comment]
rancher/rancher:master-head (8/9)

* Creating virtual service and destination rules work well through UI
* Functional checks:
  * Created a service using samples from istio test plan
  * Created canary deployment using virtual service and destination rules
  * Crated basic round robin deployment using virtual service and destination rules
* Checked CRDs after editing each field in the UI and validated that updates made from the UI are immediately reflected (since we are not able to easily test all Istio functionality)
