### ISSUE TITLE
UI: Access control for Kiali, Jaeger, Grafana and Prometheus UI

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20899]
UI for https://github.com/rancher/rancher/issues/20895

**Comment by davidnuzik** [comment]
@loganhz @n313893254 the commits mention access control for all four external UI. Yet, in Istio config I only see that it affects Kiali and Jaeger UI.
How do I configure access control for Grafana and Prometheus UI? Or are these not configurable? (And thus I only need to test access control for Kiali and Jaeger ?)

**Comment by loganhz** [comment]
We can only config it for kiali and jaeger. Project member can see grafana and prom links if project level monitoring enabled

**Comment by davidnuzik** [comment]
Version: master-head (8/6/19)

This adds ability to set access control for Kiali and Jaeger UI.
![image](https://user-images.githubusercontent.com/45179589/62581230-65bf0e80-b85d-11e9-8b48-0907fbe13aac.png)

Grafana and Prometheus are not affected (And the UI clearly states that only Kiali and Jaeger are effected). Any project member can see the Grafana and Prometheus links as Logan mentioned.

I first tested without ANY change to the default access control by adding  a user as read-only to the system project. They should not have access to the Jaeger and Kiali UIs.
Confirmed the user does not have access. They get a 403 error when attempt to view the UIs. The same is true for other UIs too since this user only has read-only access.

I then added this Project Read-only user to the member list.
![image](https://user-images.githubusercontent.com/45179589/62581426-07def680-b85e-11e9-9e36-a0ae8092290f.png)
Confirmed this project read-only user now can see the Kiali and Jaeger UI. They still cannot see Grafana/Prometheus (as expected).

I confirmed that when they are given access we can now see the UI links when access Istio at project level:
![image](https://user-images.githubusercontent.com/45179589/62581497-48d70b00-b85e-11e9-9051-ae804c052ce9.png)

These links work as well. When we had no access those links were not shown.


Last I tested as a project member. I did not add them to access control. I confirmed they can access all four UIs without any issues.
