### ISSUE TITLE
Backport: Rancher enforces arbitrary limit on autoscaling nodes in GKE clusters

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#20936]
https://github.com/rancher/rancher/issues/20355

**Comment by westlywright** [comment]
https://github.com/rancher/rancher/pull/21030

**Comment by davidnuzik** [comment]
**Replication:**
Version: v2.2.4

As pictured I cannot make GKE node pool autoscaling max greater than 5 for each min and max (template prevents this). (Below in picture I tried to plug in a number greater than 5 in each field)
![image](https://user-images.githubusercontent.com/45179589/59947642-9ae4de00-9422-11e9-9b62-fdb8108b076e.png)

**Validation:**
Version: release-v2.2 (essentially v2.2.5 rc) (6/21/19)

Failed.

I still cannot set min to greater than 5 and max to greater than 5.
I think this just isn't in release-v2.2 yet? I just pulled it 6/21/19 12:50PM pacific.

**Comment by davidnuzik** [comment]
Waiting on new build.

**Comment by davidnuzik** [comment]
Use https://releases.rancher.com/ui/2.2.78/index.html for testing and re-test this.

**Comment by davidnuzik** [comment]
Version: v2.2-head with ui-index of https://releases.rancher.com/ui/2.2.78/index.html 

This is now working correctly. See my comment above for reproduction notes https://github.com/rancher/rancher/issues/20936#issuecomment-504553068
![image](https://user-images.githubusercontent.com/45179589/59954619-7f85cd00-943a-11e9-987b-e032a13cfdb9.png)

The ui allows the min to be greater than 5 and the max to be greater than 5.

I brought up a cluster with this configuration and confirmed settings in GCP web UI.
![image](https://user-images.githubusercontent.com/45179589/59954675-c70c5900-943a-11e9-908f-842abed3fd46.png)

Further, I ensured I can have a min setting of 1 and a max setting of 1 as well. This works without any issues as well.
![image](https://user-images.githubusercontent.com/45179589/59954721-15215c80-943b-11e9-8156-85bd79d796fa.png)

I also did various checks with weird settings like a min of 3 and a max of 1. The UI does not allow this, as expected (it will forcibly set max to at least equal the min at minimum). Additionally, if you do not set the initial node pool amount to be the minimum value or greater then the UI will mention this and prevent creating the cluster, as expected. The UI also does not allow entering any zeros or other chars, as expected. Last, there appears to be no limit set. I can have autoscaling set to min 1 and max 1048576 without any issues.

HTTP/API appear correct. I could not identify any issues except for one small issue (for which I will open a separate bug). When you first try to change the numbers the UI seems to enforce the old 5/5 for min/max fields. But then try again and then it works. You basically just have to plug in your number you want twice (if greater than 5). It's a strange behavior but doesn't seem to hurt anything. This issue is tracked here:
