### ISSUE TITLE
How do I use calico with global BGP peer in rancher?

### ISSUE THREAD

**Issue by fantietou** [rancher/rancher#20970]

**Comment by scoof** [comment]
This worked for me:
`
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: gw
spec:
  peerIP: 192.168.122.1
  asNumber: 64567
`
It probably doesn't make much sense to do this without disabling natOutgoing in your IPPool CRD

**Comment by behnm** [comment]
Hi . 
By Rancher UI, when choose "Network provider :calico", after launching the cluster, we faced calico in IPIP (because of interface tun0). By the way, I need to launch my cluster with calico in bgp mode. 
What should I do?
Does it need to add any config in  yaml  file, at the time of cluster creation ?
