### ISSUE TITLE
questions.yml in catalog only supported using git repos

### ISSUE THREAD

**Issue by fredleger** [rancher/rancher#20977]
So far, according to our testing only catalogs downloaded from a git repo are taking questions.yml into account.

**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
adds 2 catalog sources:
webofmars-demo-git : https://github.com/webofmars/demo-rancher2-catalog.git
webofmars.demo-helm: https://webofmars.github.io/demo-rancher2-catalog/

same repos with same content in demo chart !

**Result:**
when launching apps in the the cluster from the UI, the git source will show the questions parts.

**Other details that may be helpful:**
tested with a bare new cluster on digital ocean provisionned through rancher-ui

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): single

**Comment by samail** [comment]
+1 
Would love a solution for this one ;)

**Comment by fredleger** [comment]
This is mainly restrict the use of custom catalogs to scenarios using a chartmuseum or self hosted helm repos

**Comment by erikwilson** [comment]
I think that `questions.yml` has only ever been officially supported using git repos (although the documentation and enforcement of this may not be great). One of the reasons for this limitation currently is that we are aggregating keywords and labels for all versions, but we should not pull all versions of all charts when traversing a helm index repo.

https://github.com/rancher/rancher/blob/0aa5d3ca067ebefe2ee02449aa95bd67e2318ed3/pkg/catalog/manager/traverse.go#L99

We may be injecting that data and caching it in such a way where subsequent updates to the catalog would pick up those cached values (not sure if such a bug exists but looks possible).

https://github.com/rancher/rancher/blob/0aa5d3ca067ebefe2ee02449aa95bd67e2318ed3/pkg/api/customization/catalog/templateversion.go#L79

I think the preferred method should be to use git repos, where we should document this more explicitly, ensure we are enforcing the behavior correctly in the code, and provide an example of deploying a git server in cluster for custom catalogs. Otherwise we might be able to support a subset of the behavior (minus labels and keywords, but supporting RancherVersion and Namespace, with some rework of the code.

**Comment by ekristen** [comment]
I'm on 2.2.4 and questions.yml most definitely get's parsed and rendered when using a helm repo (NOT git).

I'm doing a self-hosted, static helm repo and packaging a `questions.yml` at the root at the same level as the Chart.yaml and values.yaml.

I most definitely think that the questions.yml should be present via git or helm repo.

**Comment by ekristen** [comment]
I think this is an actual UI bug.

If questions.yml is present in the tbz that gets uploaded to the helm chart, it does indeed get pulled in, but it seems to only get rendered by the UI if you first limit the app launch catalog to your custom one, then click refresh, then click view details on the app that has the questions.yml.

If you load up a fresh UI and simply navigate to the view details of the helm app from your custom catalog, the questions.yml does NOT get rendered, but if you back out click refresh and re-enter view details it'll be rendered.

I can open a separate bug for this. @cjellick @vincent99

**Comment by vincent99** [comment]
The UI is just listing template & templateVersions.  Whether the questions are there or not depends on whether the server has downloaded and parsed them or not.

For git the answer is "yes" because they all come together with the repo.  For http the answer is currently "randomly maybe", because it was never explicitly intended to be but if some of the N tarballs are downloaded they go through the same code to process them.

**Comment by ekristen** [comment]
In my case it's definitely downloaded and I only have 1 tarball and 1 version. The UI only renders the questions right after I click the refresh button, if I do a full refresh of the browser, and go back in, it's not there. 

It's definitely a bug in the API. I'm looking at the version entry right now and sometimes the questions array is populated, and sometimes it is not. 

@vincent99 would you prefer I open a separate issue for this?

**Comment by SimonHeimberg** [comment]
Deploying own charts is unhandy currently. For serving a chart with subcharts:
* Serve a repo for questions.yml to work (because of this issue).
* And for subcharts, serve a helm repo.

Being able to serve the questions with the helm repo, or to provide the questions somehow else (maybe solved by #20603) would help.
