### ISSUE TITLE
Backport: Node driver Error creating machine: Error running provisioning: something went wrong running an SSH command

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#20985]
https://github.com/rancher/rancher/issues/20753

**Comment by davidnuzik** [comment]
I essentially followed the same steps to test as outlined here: https://github.com/rancher/rancher/issues/20753#issuecomment-504140691
In that comment I also already replicated in v2.2.4 so please reference that issue to also see replication steps and additional information.

**Validation:**
Version: Master (v2.3) (6/21/19)

- Create Digital Ocean RKE cluster. For the nodes, instead of Ubuntu 18.04 use CentOS 7.6 instead.

The node comes up without any issues.

**Additional notes:**
You can see the jail script was indeed fixed. For example, notice we see nsswitch.conf now in the jail in the etc folder.
