### ISSUE TITLE
Backportv2.0: Node driver Error creating machine: Error running provisioning: something went wrong running an SSH command

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#21012]
https://github.com/rancher/rancher/issues/20753

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.0.15

- Create a Digital Ocean RKE cluster. For the nodes, instead of Ubuntu 18.04 use CentOS 7.6 instead.

The cluster fails to come up. The jail script does not copy necessary nsswitch.conf and passwd files.
`Error creating machine: Error running provisioning: something went wrong running an SSH command`
![image](https://user-images.githubusercontent.com/45179589/60540090-2da73780-9cc3-11e9-9ee7-f738e943bbe3.png)


**Validation:**
v2.0-head (7/2/19)

- Create a Digital Ocean RKE cluster. For the nodes, instead of Ubuntu 18.04 use CentOS 7.6 instead.

The nodes now come up without any issues. Cluster is operational; all nodes active.
The jail now has the nsswitch.conf file and passwd file (it did not before the fix).
![image](https://user-images.githubusercontent.com/45179589/60539256-16674a80-9cc1-11e9-89d5-66582218154f.png)

Next up: Pingan driver test

**Comment by davidnuzik** [comment]
@loganhz may we request test but with Pingan driver?

**Comment by rootwuj** [comment]
Tested with v2.0-head (7/4/19)

Create a PinganyunECS cluster using Ubuntu 18.04 image, the nodes have no ssh error.
