### ISSUE TITLE
Not able to add Amazon EC2 host

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2104]
Server version - V0.38.0-1

Not able to add Amazon EC2 host

After entering valid credentials and clicking on "Next:Authenticate & select a network" , we get the following:

<img width="1004" alt="screen shot 2015-09-22 at 6 14 37 pm" src="https://cloud.githubusercontent.com/assets/4266958/10036026/f3442d02-6155-11e5-993d-e44ab666e04b.png">

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /proxy/ec2.us-west-2.amazonaws.com/. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

**Comment by sangeethah** [comment]
Tested with server version - v0.39.0-rc1

We are able to add EC2 machine successfully from UI.

**Comment by joao-fidalgo** [comment]
I'm having this issue on v0.51.0

**Comment by ixis-andrew** [comment]
We're having this issue too.

Thinking it could be because of:

"NetworkError: 403 Forbidden - http://rancher.ixishosting.co.uk:8080/v1/proxy/ec2.ap-northeast-2.amazonaws.com/"

Something to do with Amazon's new DC? 

Tried restricting the IAM user's region to exclude it but then Rancher just complains about not having access to the other regions.



Thanks,

Andrew

**Comment by joao-fidalgo** [comment]
https://github.com/rancher/rancher/issues/3185
