### ISSUE TITLE
[Monitoring] Can not turn on dns exporter in cluster monitoring

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21066]
rancher/rancher:v2.2.5

`exporter-kube-dns.enabled` is set to `false` and not able to be overridden. If users have interested in exporting those metrics, users can not use it in rancher cluster monitoring.

We should allow users to enable exporters for core dns and kube dns

**Comment by thxCode** [comment]
- if interested in kube-dns metrics (e.g: using v1.12)
    + configuring `exporter-kube-dns.enabled` item as `true` when
    enabling cluster-level monitoring
    + guaranteeing the DNS service of `kube-system` namespace has:
        - `k8s-app=kube-dns` label
        - `dnsmasq-metrics` port with `TCP:10054`
        - `skydns-metrics` port with `TCP:10055`
- if interested in coredns metrics (e.g: using v1.14)
    + configuring `exporter-coredns.enabled` item as `true` when enabling
    cluster-level monitoring
    + guaranteeing the DNS service of `kube-system` namespace has:
        - `k8s-app=kube-dns` label
        - `metrics` port with `TCP:9153`

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher:v2.2.6

Steps:
- run Rancher:v2.2.6 container single installed
- add a cluster
- go to enable the cluster monitoring
- in the `advanced options` section, add `exporter-kube-dns.enabled` = `true`
<img width="1438" alt="Screen Shot 2019-07-31 at 3 53 55 PM" src="https://user-images.githubusercontent.com/6218999/62253831-0750e680-b3ac-11e9-9dbf-41479ca3d83f.png">

- click `enable monitoring`

Result:
- go to `System` project -> `Apps` -> `App: cluster-monitoring` -> `Answers`
- see the `exporter-kube-dns.enabled` is set to `false`
<img width="900" alt="Screen Shot 2019-07-31 at 3 55 16 PM" src="https://user-images.githubusercontent.com/6218999/62253904-39fadf00-b3ac-11e9-9698-662a13a5d6c1.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher: master-head 

following the same steps, see  the `exporter-kube-dns.enabled` is set to `true` successfully 

<img width="875" alt="Screen Shot 2019-07-31 at 4 26 03 PM" src="https://user-images.githubusercontent.com/6218999/62254971-22255a00-b3b0-11e9-8e16-31d117a1b690.png">
