### ISSUE TITLE
Backport: UI will load js files even for inactive cluster drivers

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21109]
https://github.com/rancher/rancher/issues/21108

**Comment by westlywright** [comment]
Will be available in UI Tag: `2.2.79`

**Comment by westlywright** [comment]
Release PR: https://github.com/rancher/rancher/pull/21119

**Comment by westlywright** [comment]
There was a minor issue with cluster edit, please use `2.2.80` to validate. The new Baiducloudcontainerengine was causing problems so I've added the active filter. Its not the best fix as we shouldn't even try to load this on edit but its the smallest scope fix. The same fix has been added to master but will probably end up being removed with the changes coming to launching clusters in 2.3 that will decouple some of this functionality a bit more so I'm not super concerned about a temporary fix in master.

**Comment by sowmyav27** [comment]
Found issue on `rancher:v2.2-head`
**Steps:**
1. Launch rancher server with custom 2.2.4 image(30 mins cert expiry)
2. Create a do cluster (3 nodes)
3. Upgrade to rancher:v2.2-head. Let the certs expire. Do a Rotate Certificates on the cluster.
4. The cluster comes up `active`.
5. Do an edit cluster. The UI load fails with error `Cannot read property 't' of undefined`
<img width="1779" alt="Screen Shot 2019-06-25 at 2 48 01 PM" src="https://user-images.githubusercontent.com/26032343/60140499-ef5fc480-9766-11e9-90a2-96383c4446db.png">


On setting the `ui-index` = `https://releases.rancher.com/ui/2.2.80/index.html` I was able to edit the cluster, no errors seen after changing the UI tag.

**Comment by davidnuzik** [comment]
**Reproduction:**
Version: v2.2-head (with ui-index https://releases.rancher.com/ui/2.2.77/index.html, an older but rather recent build which has the issue)

- Activate Baidu cluster driver. Click on add cluster.
- Disable it.
- Watch http traffic
- Click the "Add Cluster" button -- notice for some reason Biadu is listed even though it is now disabled.
- Observe we load unnecessary Biadu js/css. We load each component file twice
![image](https://user-images.githubusercontent.com/45179589/60140824-dacffc00-9767-11e9-9969-1f3360e49c70.png)
Note: This was an issue only for specific timeframe -- i.e. it was fairly quickly fixed in ui so newer UI builds don't have the issue. This is why we had to override ui-index to reproduce.

**Validation:**
Version: v2.2-head (with ui-index https://releases.rancher.com/ui/2.2.80/index.html, newer ui build slated for qa testing 6/25/19)

(pre-requisite had done reproduction already i.e. enabled then disabled Baidu driver)
- Watch http traffic
- Click the "Add Cluster" button
- Observe we NO LONGER load the unnecessary Biadu js/css and driver is not enabled in the UI.
- Enable 
Note: v2.2-head does not have a solution for getting proper ui-index yet so we manually override with latest v2.2 ui build.
