### ISSUE TITLE
Listing Cluster template through API after delete operation results in "Forbidden" error

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21107]
Version: rancher/rancher:master-head

Steps:

1. Login to the setup as an admin and create a standard user "user1"
2. Login as "user1"
3. Create a cluster template "T1" and it succeeds
4. Delete the cluster template T1
5. Cluster template T1 gets deleted, but the following forbidden error is displayed when reloading the page to list the template T1 after delete operation. 
```
    "baseType": "error",
    "code": "Forbidden",
    "message": "clustertemplates.management.cattle.io \"ct-g6c7n\" is forbidden: User \"u-shvpw\" cannot get resource \"clustertemplates\" in API group \"management.cattle.io\" in the namespace \"cattle-global-data\"",
    "status": 403,
    "type": "error"

}


```

**Comment by mrajashree** [comment]
@soumyalj This isn't a bug, since the resource is deleted and standard user does not have access to resources in that namespace, reloading the page using that template's id will throw 403. This is the behavior for other resources like projects created by users too
<img width="1195" alt="Screen Shot 2019-06-24 at 9 16 08 PM" src="https://user-images.githubusercontent.com/10672776/60068849-50cf5700-96c5-11e9-8988-ba66ecf4d6ba.png">

This won't be thrown in UI since UI won't reload the same link, and in API-UI you can click on `Go Up` instead of `Reload`

**Comment by sangeethah** [comment]
@mrajashree  In this case , we expect the error message to indicate that invalid template Id is passed ?
