### ISSUE TITLE
Server panic during startup when k8s v1.14 is not available.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#21129]
**Steps to reproduce (least amount of steps as possible):**
- Provision a v1.14 cluster. 
- stop all etcd nodes in the cluster
- wait for a minute and try to restart rancher

**Result:**
rancher will panic:
```
panic: creating CRD store Get https://x.x.x.x:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

goroutine 11794 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc007bcbf00, 0xc007bcbf20, 0x2, 0x2, 0xc00b99c8c0, 0x74d01c0, 0x4892180, 0xc00c083c40, 0x3e787fc, 0x4)
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2c2
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
        /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce
```
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 25/6
- Installation option (single install/HA): single install

related call https://github.com/rancher/rancher/blob/master/pkg/controllers/user/controllers.go#L76

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher:master-head, but not in Rancher:v2.2.4

Steps:
- run Rancher container
- add a cluster with k8s v1.14 using EC2, 1 etcd, 1 control plane, 1 worker
- stop the etcd node on AWS
- `docker stop`  to stop Rancher container
-  wait to see the UI is gone and it shows no connection
- `docker start` to start the Rancher container
- check the logs to see errors

Results:

in Rancher:master-head
- failed to restart the Rancher container, it will crash and restart with the following error in its log
```
panic: creating CRD store Get https://13.57.255.96:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

goroutine 11553 [running]:
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs.func1(0xc0170f5620, 0xc0170f5640, 0x2, 0x2, 0xc0115abd60, 0x6cfd800, 0x4371920, 0xc01408f680, 0x3bd5ec4, 0x4)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x2d9
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/crd/init.go:50 +0xce
```


in Rancher:v2.2.4
- Rancher server is not panic, and Rancher's log shows 
```
2019/06/26 21:50:25 [ERROR] ClusterController c-lwsms [user-controllers-controller] failed with : failed to start user controllers for cluster c-lwsms: failed to contact server: Get https://13.57.19.104:6443/version?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
<img width="1447" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60217897-a8cfa000-9822-11e9-9760-648a606559b9.png">

![Screen Shot 2019-06-26 at 2 56 17 PM](https://user-images.githubusercontent.com/6218999/60217887-9fdece80-9822-11e9-8d47-a03af2991d16.png)

**Comment by jiaqiluo** [comment]
The bugfix is validated on Rancher:master-head af5771ff

Steps:
- run Rancher:master-head container
- add a cluster with k8s v1.14 using EC2, 1 etcd, 1 control plane, 1 worker
- stop the etcd node on AWS
- `docker stop`  to stop the Rancher container
-  wait to see the UI is gone and it shows no connection
- `docker start` to start the Rancher container

Results:
- Rancher server is restarted successfully
- in Rancher's UI, the cluster is still in the unavailable state
- restart the etcd node, then the cluster goes back to active and is functional
