### ISSUE TITLE
Backport: Using cloud config in Azure with a Service Principal that has multiple subscriptions fails to operate

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21124]
Backport https://github.com/rancher/rancher/issues/20632

**Comment by davidnuzik** [comment]
**Reproduction:**
Version: v2.2.4

We were able to see that when we supply azure cloud information the subscription id is essentially ignored.

- Create an RKE Azure nodeTemplate with correct credentials (Subscription ID, Client/app ID, secret); just make it a simple cluster, say 1 node with all 3 roles
- Fill out Azure cloud fields, but put in a fake subscription ID
- SSH into cluster node. Review kubelet logs and kube-controller-manager logs. grep for our fake subscription ID that we entered
- The fake subscription id is not found, instead we find another subscription id that we did not specify.

We expected provisioning the cluster to fail since we provided a false/fake subscription id in the azure cloud subscriptionid field. Instead, the cluster worked and came up for us (because in this case it used a subscriptionid that was set up and able to create the azure resources). In our case we had difficulty setting up a subscriptionid such that it would fail to provision -- but the point is that we have effectively reproduced because we saw when we inspect kubelet and kube-controller-manager logs that our fake subscription id was not used.

Here is an example:
```
docker-user@david-224invalid1:~$ cat kube-cntrl-mgr_logs | grep "8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6"
+ local az_subscription_id=8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6
+ '[' -z 8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6 ']'
+ jq '.subscriptionId="8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6"'
docker-user@david-224invalid1:~$ cat kube-cntrl-mgr_logs | grep "7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6"
```

First command greps for incorrect subscription id (we did not supply this) Second command greps for what we actually entered in the UI when we plugged in subscriptionid for azure cloud field.

**Comment by davidnuzik** [comment]
This change causes failures bringing up a cluster even with correct cloud info provided (all four required fields).
Something's not quite right with the original PR I think. https://github.com/rancher/rke-tools/pull/38

[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [13.91.88.208]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused, log: ++ cut -d / -f 9]; waiting on cluster-scoped-gc
--

**Comment by davidnuzik** [comment]
I confirmed in v2.2.4 I can bring up azure RKE cluster with azure cloud without any issues (and thus our config supplied is good)

**Comment by davidnuzik** [comment]
Is there a link to PR @alena1108 I don't see any new commits to fix the issue.

**Comment by kinarashah** [comment]
@davidnuzik this is the original PR which is in rke-tools, https://github.com/rancher/rke-tools/pull/53 

And new rke-tools got added in these backport PR,
https://github.com/rancher/rancher/pull/21180

**Comment by davidnuzik** [comment]
Version: v2.2-head (6/27/19)

The PR fixed our previous issue. We can now bring up an azure cluster with azure cloud option without any issues (when proper credentials are supplied).
I also checked with my own test app in separate subscription. As long as correct credentials are supplied the cluster now comes up (this was broken with previous PR and preventing creating any azure nodes with cloud option before).
Also ensured we can leverage Azure cloud features like Azure disk storage class and bind a volume.

------------------

**Reproduction:**
Refer to previous comment https://github.com/rancher/rancher/issues/21124#issuecomment-506026017

**Validation:**
Version: v2.2-head (6/27/19) Ver from logs: 5521557f

- Create an RKE Azure nodeTemplate with correct credentials (Subscription ID, Client/app ID, secret); just make it a simple cluster, say 1 node with all 3 roles
- Fill out Azure cloud fields, but put in a fake subscription ID
- SSH into cluster node. Review kube-controller-manager logs. grep for our fake subscription ID that we entered
- The fake subscription id IS NOW found (it was not before).

First is correct subscription id (we did not supply this)
Second is our fake subscription id (which we supplied)
```
docker-user@david-testappbad1:~$ cat kubelogs.txt | grep 8070bfdf-3a92-47fe-bec5-2f3ae43d2bf6
docker-user@david-testappbad1:~$ cat kubelogs.txt | grep 7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6
+ local az_subscription_id=7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6
+ '[' -z 7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6 ']'
+ jq '.subscriptionId="7070bfdf-3a92-47fe-bec5-2f3ae43d2bf6"'
```

Previous behavior was that logs showed the subscription id that we did NOT supply in our cloud config. 

Confirmed that since I supplied bad subscriptionID I cannot make use of cloud features like provision storage with azure disk. The volume cannot be bound because we get an error stating credentials issue like:
![image](https://user-images.githubusercontent.com/45179589/60302168-0548c300-98e8-11e9-99dc-1f55370294c4.png)

I also made sure that when we DO supply correct credentials we can make sure of such features (I can make an azure disk storage class and provision a volume).

Note as node provisioned saw we are indeed pulling latest rke-tools (build 34).

**Comment by davidnuzik** [comment]
Version: v2.2-head (6/27/19)

The PR fixed our previous issue. We can now bring up an azure cluster with azure cloud option without any issues (when proper credentials are supplied).
I also checked with my own test app in separate subscription. As long as correct credentials are supplied the cluster now comes up (this was broken with previous PR and preventing creating any azure nodes with cloud option before).
Also ensured we can leverage Azure cloud features like Azure disk storage class and bind a volume.

------------------

**Reproduction:**
Refer to previous comment https://github.com/rancher/rancher/issues/21124#issuecomment-506026017

**Validation:**
Version: v2.2-head (6/27/19) Ver from logs: 5521557f

- Create an RKE Azure nodeTemplate with correct credentials (Subscription ID, Client/app ID, secret); just make it a simple cluster, say 1 node with all 3 roles
- Fill out Azure cloud fields, but put in a fake subscription ID
- SSH into cluster node. Review kube-controller-manager logs. grep for our fake subscription ID that we entered
- The fake subscription id IS NOW found (it was not before).

First is correct subscription id (we did not supply this)
Second is our fake subscription id (which we supplied)
```
docker-user@david-testappbad1:~$ cat kubelogs.txt | grep 8redacted
docker-user@david-testappbad1:~$ cat kubelogs.txt | grep 7redacted
+ local az_subscription_id=7redacted
+ '[' -z 7redacted ']'
+ jq '.subscriptionId="7redacted"'
```

Previous behavior was that logs showed the subscription id that we did NOT supply in our cloud config. 

Confirmed that since I supplied bad subscriptionID I cannot make use of cloud features like provision storage with azure disk. The volume cannot be bound because we get an error stating credentials issue like:
![Screen Shot 2019-06-27 at 3 02 04 PM](https://user-images.githubusercontent.com/45179589/60303948-b5b8c600-98ec-11e9-8a73-ea3bc62ff87a.png)

I also made sure that when we DO supply correct credentials we can make sure of such features (I can make an azure disk storage class and provision a volume).

Note as node provisioned saw we are indeed pulling latest rke-tools (build 34).
