### ISSUE TITLE
Cannot create alerts due to "serviceaccounts "project-monitoring" not found"

### ISSUE THREAD

**Issue by hameno** [rancher/rancher#21150]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Install rancher < 2.2.4
* Enable cluster monitoring
* Upgrade to rancher 2.2.4
* Enable project monitoring
* In project go to Alerts
* Try to create new alert group

**Result:**
Red popup opens with error:

    get service account cattle-prometheus-p-rfjdc:project-monitoring for monitor failed, serviceaccounts "project-monitoring" not found

**Other details that may be helpful:**
On a clean install of rancher it seems to work

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.4
- Installation option (single install/HA):
single install, docker compose

Using RKE created cluster, 1.13.5

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs
- Kubernetes version (use `kubectl version`): 1.13.5

- Docker version (use `docker version`):

n/a

**Comment by orangedeng** [comment]
I tried to reproduce with following steps:
1. Create rancher setup with v2.2.3 and create a test cluster.
2. Enable cluster monitoring
3. Upgrade rancher to v2.2.4
4. Enable project monitoring
5. Add notifier
6. Create alert policy group

result:
1. Create success and can't see your errors.

I think the reason why you get that errors is because the project monitoring wasn't deployed complete. I think you won't see the same error after project monitoring is up and active.

**Comment by hameno** [comment]
The problem ist that it never completes deploying

**Comment by hameno** [comment]
The namespace for the project monitoring stays empty - what can I provide to help debug this bug?

**Comment by hameno** [comment]
Can someone please advise how we can help debug this problem?

**Comment by hameno** [comment]
Could it be related to https://github.com/rancher/rancher/issues/21546?
