### ISSUE TITLE
[UI] Ceph RBD userSecretNamespace missing

### ISSUE THREAD

**Issue by Raboo** [rancher/rancher#21188]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
Add Ceph RBD Storage Class

**Result:**
userSecretNamespace is missing.
All Apps that are deployed with different namespaces that needs to create persistent storage fail because it's looking for the secret in current namespace.

**Other details that may be helpful:**
Add parameter box for `userSecretNamespace` to the configuration UI when creating Ceph RBD Storage Class.

https://kubernetes.io/docs/concepts/storage/storage-classes/#ceph-rbd

Current workaround is to use kubectl or rancher api to add storage class.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): HA

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (7/15/19)

"User Secret Namespace" was added as a Parameter under Ceph RBD Storage Class config.
![image](https://user-images.githubusercontent.com/45179589/61255573-036f6400-a71e-11e9-8b2d-500d3c99be2d.png)

I validated the UI field as well as the API (`userSecretNamespace": "secretNS"` is an example). 

There was no changes needed in backend (API) as this is just an extra string to add on to parameters mapping in /v3/cluster/CLUSTERID_HERE/schemas/stroageClass

Schema:
```
"parameters": {
"create": true,
"nullable": true,
"type": "map[string]",
"update": true
}
```

I ensured that the UI/HTTP/API all look good. This field is a string so any values can be entered. We currently do not validate any fields. I fuzzed the field and can enter anything I wish that is a string of text including Unicode. This is currently expected behavior.
![image](https://user-images.githubusercontent.com/45179589/61255754-c788ce80-a71e-11e9-99a6-49a989ab04b5.png)

**Comment by davidnuzik** [comment]
@Raboo we do not have a means to fully test this currently, but the added field should work. I made sure everything looks good from the UI perspective and it does. If you would like you are welcome to test from the latest `master-head` image or we can just close this issue.

**Comment by Raboo** [comment]
@davidnuzik so I just run?

```
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head
```

And then add a Ceph RBD using the UI?

**Comment by Raboo** [comment]
BTW a half-off-topic.
Have a look at https://rook.io/. You could easily add Ceph RBD and CephFS to your test pipeline with that I assume.

**Comment by davidnuzik** [comment]
@Raboo if you wish to test (you do not have to). Yes you can just run the latest via the "master-head" image and then add Ceph RBD using the UI. The new field should be there and it should work fine now.

**Comment by Raboo** [comment]
I'll close it then.
Thanks!
