### ISSUE TITLE
ControlPlane is not reachable in v2.2.5-rc7 

### ISSUE THREAD

**Issue by sybnex** [rancher/rancher#21216]
After Updating to v2.2.5-rc7, Rancher is complaing an Cluster as offline because he cannot not reach e.g. the scheduler and the controllermanager

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an e.g. AKS Cluster not from Rancher and Import it later in Rancher.

**Result:**
As Rancher is not able to see the scheduler and the controllermanager (because on AKS and how its behave) it complains the cluster is not ready and you cannot connect. 

**Other details that may be helpful:**
This is working in v2.2.5-rc6

**Environment information**
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): BareMetall
- Kubernetes version (use `kubectl version`): 1.13.x

**Comment by superseb** [comment]
Thanks for the report, sounds like a regression from https://github.com/rancher/rancher/pull/21121

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher: v2.2.5-rc7, fresh install

Steps:
- run  Rancher: v2.2.5-rc7 container
- provision an AKS cluster through Rancher UI
- import an existing AKS cluster from Azure

Result:
- both AKS clusters are stuck in `Waiting for API to be available` state 

<img width="1267" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60363539-b018ba00-9998-11e9-9f8f-1c2a97acc50d.png">

Rancher logs
```
2019/06/28 18:33:55 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10049
2019/06/28 18:33:55 [INFO] kontainerdriver azurekubernetesservice stopped
2019/06/28 18:33:58 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:10587
2019/06/28 18:33:58 [INFO] kontainerdriver azurekubernetesservice stopped
2019/06/28 18:34:05 [ERROR] Failed to update cluster [c-ttzmh]: Operation cannot be fulfilled on clusters.management.cattle.io "c-ttzmh": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by jiaqiluo** [comment]
The bug is reproduced with Rancher: v2.2.4 upgrading to v2.2.5-rc7

Steps:

- run Rancher: v2.2.4 container
- provision an AKS cluster through Rancher UI
- import an existing AKS cluster from Azure
- upgrade Rancher to v2.2.5-rc7

Result:
- failed to start the clusters 
<img width="1458" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60369806-acd9fa00-99a9-11e9-9104-99da24284c1b.png">

```
{
"lastUpdateTime": "2019-06-28T20:36:24Z",
"message": "component check failed for [scheduler]: Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused",
"reason": "ComponentHealthCheckFailure",
"status": "False",
"type": "Ready"
},
```

**Comment by jiaqiluo** [comment]
The bugfix is validated on v2.2-head b240bd20 

Fresh Install:
- add an AKS cluster through Rancher UI - PASS

Upgrade Path:
- run Rancher: v2.2.4 container
- provision an AKS cluster through Rancher UI
- import an existing AKS cluster from Azure
- upgrade Rancher to v2.2.5-rc7

Result:
- both clusters are up and functional 
<img width="1430" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/60455264-ccac3080-9bea-11e9-841d-a1c06c090c29.png">
