### ISSUE TITLE
Support for Raspberry PI in 64-bit and 32-bit mode

### ISSUE THREAD

**Issue by trunkyredstone** [rancher/rancher#21243]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement/Feature Request

**Steps to reproduce (least amount of steps as possible):**
1. Use a raspberry pi
2. run the rancher-agent:v2.2.4-arm64 image.

**Result:**
standard_init_linux.go:207: exec user process caused "exec format error"

**Environment information**
- Rancher version: 2.2.4
- Docker version: 18.09.0

Hi, i'm currently setting up a multi-arch cluster, and after a bit of searching i have come to the conclusion that rancher + raspberry pi = error. Could someone provide me with the steps to build/acquire an arm32 rancher-agent image?

Thanks

**Comment by kopwei** [comment]
I hit into the same issue since my RPi4 doesn't have proper ARM64 OS yet. Official Raspbian won't migrate to 64 bit within a few years. Thus my K3s cluster cannot be managed by rancher with rancher-agent. I am working on it. I think at least you need to have prebuilt binaries from following Rancher repositories based on ARM arch:

rancher/loglevel
rancher/shared-mnt
rancher/machine-package
rancher/helm
rancher/helm-unittest
etcd-io/etcd

**Comment by jonfairbanks** [comment]
+1 for this request. When trying to add a Pi based container, you get an error that the **rancher/rancher-agent** image is not compatible with the ARM platform. 

```
$ kubectl get events --all-namespaces

Failed to pull image "rancher/rancher-agent:v2.2.5": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.2.5": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:6db9d81c10716ca1da8f4ece7c19e5762ce0bfd586024e4b8546beb4e71f5781: not found
cattle-system   10m         Warning   Failed              pod/cattle-node-agent-xvvz4                  Error: ErrImagePull
cattle-system   100s        Normal    BackOff             pod/cattle-node-agent-xvvz4                  Back-off pulling image "rancher/rancher-agent:v2.2.5"
```

**Comment by unixorn** [comment]
Another +1.

I'm running k3s on my Arm cluster (It's a mix of Odroid HC2s and Raspberry Pi 4s) and would really like experiment with Rancher on top of the cluster.

**Comment by bsord** [comment]
Another +1.

Would really appreciate being able to use Rancher to manage my Pi cluster as it's already running k3s.

**Comment by mzac** [comment]
+1 Same here!  I just got my k3s cluster up and running with 3 Pi boards and having the hardest time managing it.  If it could be managed through Rancher which I am already quite familiar with it would be so much easier even if I've started learning about writing manifests, it is a pain especially that so many images out there don't support ARM.  Troubleshooting with the CLI is really annoying!!

**Comment by WhiteBahamut** [comment]
Just want to pop this up as well. K3s server is running on my Pi **4** in **64bit** mode and now I want to scale and manage a whole cluster with rancher.

```
$ docker run --rm rancher/rancher
standard_init_linux.go:211: exec user process caused "exec format error"
```
After running the cluster import command rancher server generated (running on a different machine for now)
```
 $ kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY   STATUS             RESTARTS   AGE
kube-system     helm-install-traefik-b5cxx                0/1     Completed          0          81m
kube-system     svclb-traefik-4tz2s                       3/3     Running            3          79m
kube-system     coredns-d798c9dd-xcl9l                    1/1     Running            1          81m
kube-system     traefik-65bccdc4bd-lgqvf                  1/1     Running            1          79m
kube-system     local-path-provisioner-58fb86bdfd-mg4fh   1/1     Running            1          81m
kube-system     metrics-server-6d684c7b5-cdzpz            1/1     Running            1          81m
cattle-system   cattle-cluster-agent-6d97c65cd-zwjbv      0/1     ImagePullBackOff   0          19m
cattle-system   cattle-node-agent-8rsq9                   0/1     ImagePullBackOff   0          19m
cattle-system   cattle-cluster-agent-5db4bb48-tqh6w       0/1     ImagePullBackOff   0          27m
```

```
$ docker info
...
Kernel Version: 4.19.75-v8+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
...
```

IMHO title should be changed to "Support for Raspberry PI in 32bit and 64bit mode"

**Comment by trunkyredstone** [comment]
Agreed

**Comment by wintamute** [comment]
Just some info because I also played with rancher on Rasperrypi 4: arm64 is supported, you just have to take care to select the right image since 'latest' is only for amd64 platform.
You can check which architectures are supported by looking at the tags [here](https://hub.docker.com/r/rancher/rancher/tags).
I used 
```
docker run rancher/rancher:v2.3.5
```
on my RaspberryPi 4 with ubuntu 64bit OS successfully.
I didn't see any armv7 images though.

**Comment by leflambeur** [comment]
I've been testing RPi and Rancher in my spare time as well

Originally I had 3B+'s but these really didn't have the capacity to run Rancher and k3s and would fail a lot

A default helm install with 3x Raspberry Pi 4 4GB in 64 bit running with k3s on them worked like a charm though  - didn't need to image tag or anything just used the default rancher-stable helm repo

Only change I needed was the arm_64bit set in my /boot/config.txt but a lot of you have gotten past that already

Deploying additional apps on top has been difficult with go exec errors (indicating architecture mismatch) but I'm using the Rancher helm Charts and not confident those have arm64 images for every thing I've wanted to do which is my thought on it failing - a test build of a tiddlywiki server i built in armv8 worked I just need to make the deployment more formal

I really honestly just used all the standard helm installs - for those who don't know local is the auto genned name for the imported k8s cluster that runs Rancher

My specs are in the screenshots

My rough abstracted process was:

Req: wildcard dns CNAME record for my k3s master server (I'm adding the proxy/lb later)

You need this at first because Traefik which is on 80/443 of your Cluster master will auto-route requests to containers by hostname so you want the wildcard CNAME serving anything it auto detects (if you go to something it doesn't recognise you get a 404)

1. Install k3s Server on A
2. Attach 2 Worker nodes (B&C)
3. Create cert-manager namespace using kubectl 
4. Deploy Cert manager using helm
5. Create cattle-system namespace using kubectl
6. Helm deploy Rancher
7. Watch the rollout and then connect to https://your-rancher-instance.your-domain

I've since repeated the install once I got it working to add my own CA and SSL Certs successfully as well to Rancher 

I've also been using it to provision Cloud clusters for troubleshooting customer envs which works as an fyi

<img width="1506" alt="Screenshot 2020-02-27 at 12 17 55" src="https://user-images.githubusercontent.com/57944539/75444502-78b14180-595b-11ea-97bc-2e47f54b9223.png">
<img width="1388" alt="Screenshot 2020-02-27 at 12 18 17" src="https://user-images.githubusercontent.com/57944539/75444517-7f3fb900-595b-11ea-918f-9d7b82bf4e8a.png">

**Comment by wintamute** [comment]
@leflambeur Nice writeup, thanks.
I'm running a similar setup, only difference is Rancher running outside the cluster on its own RPi. But importing it was straightforward, only took seconds.

But yes, all the helm charts (also the cluster monitoring part) uses images which are currently amd64 only.
I checked various GitHub projects and it seems that it's being worked on, with some difficulties due to not all image registries supporting multi-arch images (quay.io for example).
Not sure how to workaround in the meantime, thinking of using self-built images, at least for easy to build images like everything Golang based.

Also lots of the monitoring images used by Rancher are based on the original images which already support arm64, so just switching them out works most of the time.

**Comment by leflambeur** [comment]
@wintamute Not a problem, mine is a personal project in my spare time as I potentially move and can't host so much of the larger equipment that I run at home now

For now to get around the lack of arm64 support in the wider apps I'm going to be looking to set up my own registry and helm repos internally and then rebuild things manually as I can't expect the images used in the rancher helm apps to fully supplement my own wild env ideas when they have external to Rancher dependencies - this is the most obviously supported way forward to me at the moment

I wanted to share my experience though if it helps anyone struggling with managing single clusters as I can manage my cluster using Rancher with this method at least - next is getting more Rpi 4s and importing (I'm not expecting too much trouble with that but will report back if I get the chance) so I can run a separate HA Rancher cluster and 'production' hosting cluster to run all my silly nice-to-have apps at home like tiddlywiki or local CI/CD more cleanly

**Comment by lebeier** [comment]
wrote a guide on how to setup k8s on Raspberry Pi using Rancher and Ubuntu 20.04 LTS.
[https://codestrian.com/index.php/2020/05/23/ubuntu-20-04-rancher-and-raspberry-pi/](https://codestrian.com/index.php/2020/05/23/ubuntu-20-04-rancher-and-raspberry-pi/)

**Comment by lcotonea** [comment]
I have built a multi arch nodes cluster (one amd64 node and one armhf node):

![Capture d’écran_2020-09-16_13-03-46](https://user-images.githubusercontent.com/222894/93329290-4266e100-f81d-11ea-9b20-0b3cfe464540.png)

The good news is that works :) 

However:
- Rancher fluentd deployment (log settings)  doesn't take account the node architecture to deploy the official fluentd armhf docker image
- Prometheus seems not provide an official image for amrhf architecture

A support of multi arch nodes for Rancher fluentd deployment across the cluster could be an interesting additional feature.
