### ISSUE TITLE
ETCD is not restarted on certificate rotation from Rancher UI

### ISSUE THREAD

**Issue by jannylund** [rancher/rancher#21278]
**bug**

**Steps to reproduce (least amount of steps as possible):**
Deploy cluster via rancher. Rotate certificates through Rancher UI before they expires.

**Result:**
`etcd` fails with errors on expired certificate.

**Other details that may be helpful:**
Restarting etcd on each master fixes the problem.

**Environment information**
- Rancher version 2.2.3
- Installation option: single install

**Cluster information**
- Cluster type: created from within rancher 2.0.x, using rancher os.
- Machine type: ec2
- Kubernetes version: v1.11.3
- Docker version: 17.3.2

**Comment by davidnuzik** [comment]
I attempted reproduction:

- v2.0.15 single rancher install
- Deploy ec2 cluster via Rancher UI with current RancherOS image, k8s v1.11.9
 Cluster has 3 etcd+cp nodes and 2 workers
- Upgrade to v2.2.3
- Rotate certificates (before they expire) (all services)
- Certificates  successfully deploy and cluster is operational

Note: Just because I was not able to reproduce, does NOT invalidate what was reported. There  could be many things that differ between our environments. For example, I do not know the exact v2.0.x version the upgrade was from. I had to guess and my k8s version (RKE) is slightly different. There could be other things as well that make our environments greatly differ.

**Comment by jannylund** [comment]
- Cluster was provisioned on 1st of July 2018 from Rancher 2.0.4.
- Cluster has been upgraded once from within Rancher
- Rancher was upgraded from 2.0.4 -> 2.1.1 -> 2.1.4 -> 2.2.3
- Certificates where rotated in `2.2.3` 3 days before expire.
- ETCD died on expiry. `docker ps` showed etcd containers had been running for 4 weeks (since 2.2.3 upgrade) while other containers where running since certificate rotation. See attached screenshot from this failure.

<img width="1252" alt="Screenshot 2019-07-02 09 49 20" src="https://user-images.githubusercontent.com/121457/60570112-7f11fe00-9d79-11e9-839e-b37b9e7abf3b.png">
<img width="1273" alt="Screenshot 2019-07-02 10 12 27" src="https://user-images.githubusercontent.com/121457/60570124-8afdc000-9d79-11e9-9d66-025745f08262.png">

**Comment by 99b2b** [comment]
I'm having the same problem.

Since I rotated the certificates, my nodes are unhealthy.

**Comment by wkjun** [comment]
I'm having the same problem,when i reference the article https://rancher.com/blog/2019/kubernetes-certificate-expiry-and-rotation-in-rancher-kubernetes-clusters/, upgrade to v2.1.10 version and certificate rotation support via the API, like other compontents have been restarted ,except 3 etcd compontents ,may be it need a manual restart
