### ISSUE TITLE
CLI: Store cluster information in Rancher as a cache

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#21289]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature

**Desired Result:**
A customer is having issues with cluster listings with Rancher cli taking a long time. This is due to them managing a large number of clusters all around the world. Some of these clusters have very high latency and take 2 seconds on their own to return data.

In cases like this it may be beneficial to store a cached version of this data on the local Rancher cluster to pull from for basic queries to reduce command completion time.  Perhaps something like a `--live` flag could be used not use the cache.

**Comment by dnoland1** [comment]
Are calls being made to a cluster one at a time? If so, maybe making parallel calls would speed up the overall process. Caching may introduce consistency issues.

**Comment by bentastic27** [comment]
@dnoland1 I believe that they are being made one at a time, in which case they would benefit greatly from them being done concurrently. In this case that should decrease the run time of their script from 30ish seconds down to less than 3.

**Comment by alena1108** [comment]
@bentastic27 do we know how many a) clusters b) nodes c) average nodes per cluster the user has? Per @gitlawr we don't fetch clusters one by one, but we do fetch nodes on per cluster basis to figure out the node count for each cluster. Ideally we should reproduce the problem with the exact number of clusters/nodes the user has. We can set the `RANCHER_CLIENT_DEBUG=true` env var to get more logging as well.

**Comment by mrajashree** [comment]
The per cluster call to get node count can be avoided for all clusters except `Imported` cluster. Since rke, gke, eks and aks all have the current node count somewhere in the cluster spec and we get the spec of each cluster from the first and only call done to fetch clusters.
For rkeConfig the field `Nodes` is an array, we can use its length as node count.
And for gke, eks and aks, there are fields under the `genericEngineConfig` which reflect node count.
Unless we expect these fields to keep changing? Also from the earlier comments, making the calls to list each cluster in parallel will help
