### ISSUE TITLE
after adding a description in workload, upgrade service, the description disappear

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#21357]
*Describe your issue here*

after adding a description in workload, upgrade service, the description disappear

We should disabled the option to add description in workload as API doesn't support it. Description field is not in the workload schema

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`containers.run`|

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.3`
`Add a Description` option is available and does not work:
![Screen Shot 2020-01-06 at 2 41 35 PM](https://user-images.githubusercontent.com/57409052/71851099-ff038280-3092-11ea-9727-a3b2f86dd9b0.png)
![Screen Shot 2020-01-06 at 2 42 43 PM](https://user-images.githubusercontent.com/57409052/71851103-0165dc80-3093-11ea-81e0-872c56453a75.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 552eb2896`
`Add a Description` option has been removed:
![Screen Shot 2020-01-06 at 2 42 27 PM](https://user-images.githubusercontent.com/57409052/71851112-088cea80-3093-11ea-8f8a-98fec9822386.png)
