### ISSUE TITLE
[UI] Enable Global Enforcement for Cluster Templates

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#21378]
Cluster Templates MVP in the UI did not expose the new `cluster-template-enforcement` flag. UI needs to expose the setting via the global settings page but only to admins
UI needs to wire up launching clusters when global enforcement flag is setting.
When global admin turns Enforcement ON, Global Admin should choose from the list of public templates, the templates that should be enforced. UI should guide this.
During cluster creation, only the public templates that are marked as enforced by the global admin can be used.
Cluster Admins have to choose from only enforced templates and they cannot edit the template settings. Also Cluster Admins *must* select a template during cluster creation.
With Enforcement ON, rest all functionalities - create/update/share templates will still be available to all users as before. Only cluster creation will be template enforced.
Global Admin will be excluded from this enforcement and create templates and create clusters with/without templates.

**Comment by davidnuzik** [comment]
Note the issue description is stale. Reference https://github.com/rancher/rancher/issues/20420#issuecomment-512510906

Version: master-head (7/23/19)

For all tests, enabled Auth (I used Azure AD) unless otherwise noted. I also did some smoke tests without auth enabled.

_Case 0 - Enable/Disable enforcement HTTP/API and MISC check_:
v3/settings/cluster-template-enforcement
- When enable/disable HTTP/API appear correct. UI sends correct request payload and server response looks good. API looks correct.
- Enable enforcement, use "Revert to Default" action under Settings. This works correctly as well whether is currently set to default or not.
- UI modal for changing cluster-template-enforcement setting allows for Save/Cancel without any issues. No JS errors.

_Case 1 - Ensure when enforcement is enabled admin can still create without templates:_
- Note: Initially do NOT have auth enabled.
- Enable enforcement from the Settings page
- Ensure the admin is still allowed to create clusters without utilizing a template
Pictured below, admin can optionally create cluster with or without a template when enforcement on:
![image](https://user-images.githubusercontent.com/45179589/61814377-d3e6e880-adfc-11e9-82f9-295c2e24f0b0.png)
- Enable Auth (I used Azure AD). Ensure that as our Azure AD admin user we can still create clusters without utilizing a template. This works.

_Case 2 - Ensure that when enforcement is enabled, standard users can only create clusters when using a cluster template (such as any shared with them) and can't make clusters when have no templates shared with them:_
- Enable enforcement from the Settings page (as admin)
- Note: DON'T have any cluster templates shared with any users yet! (Case 3 tests with templates shared)
- As standard user, ensure only allowed to create clusters when utilizing a cluster template.
This is working, see below screenshot. As you can see we don't have any templates shared with this user, so user is prevented from creating any rancher clusters with a message. Also notice when hover over any disabled buttons we get a "No" cursor.
![image](https://user-images.githubusercontent.com/45179589/61815399-05f94a00-adff-11e9-9ec6-f139dd499a11.png)
- Confirm that the standard user cannot create a cluster template (Because they do not have the Create Cluster Templates role by default). User gets appropriate error when attempt to create their own cluster template:
![image](https://user-images.githubusercontent.com/45179589/61815514-40fb7d80-adff-11e9-9e57-99743c542073.png)

_Case 3 - Ensure that when we share cluster templates with users (public and shared with individual users) they have proper permissions and can create clusters:_
- Log in as admin, make 1 cluster template public, make 1 cluster template shared to certain users (1 with Owner access, 1 with Member, 1 with read-only). ENSURE the proper permissions are applied by inspecting HTTP and API. These worked correctly (public, owner, member, read-only).
- Give these users "Create Cluster Templates" role so they may create revisions.
Owner: Can clone revisions, edit cluster template (change sharing, etc), disable/enable, set defaults, and delete.
Member: Can clone revisions, disable/enable, and set default.
Read-Only: Can only use the template, cannot clone, enable/disable, set default, delete, etc.
Public: each user has read-only access to the template.
- For the cluster template that was shared with public, ensure all users can leverage the template to create clusters.
- For each, ensure that when we edit clusters we still must pick one of our templates and can't change any fields that are not questions in the template. Could not test edit with our "Member" and "Read-only" user due to bug https://github.com/rancher/rancher/issues/21747 so testing this was skipped for now.
