### ISSUE TITLE
Backport: UI - Add ability to access SSH keys to EKS driver

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#21433]
Backport rancher/rancher#17875

**Comment by westlywright** [comment]
Available in UI index 2.2.87

**Comment by davidnuzik** [comment]
Version: v2.2-head with ui-index of https://releases.rancher.com/ui/2.2.87/index.html

I'm not sure why, but it looks like call to aws isn't happening so we aren't getting list of ssh keys. I also see translation key.

![image](https://user-images.githubusercontent.com/45179589/61007395-92950a00-a321-11e9-8cf1-3145eb994c62.png)
![Screen Shot 2019-07-10 at 2 47 10 PM](https://user-images.githubusercontent.com/45179589/61007421-a7719d80-a321-11e9-850d-5f37cec719f7.png)

I then cleared cache again and tried again and confirmed the issue. I see call to ListRoles action and to get VPCs (DescribeVpcs) and that's all. I don't spot anything with our ssh keys.

**Comment by westlywright** [comment]
Bug fixed in UI Index 2.2.88

**Comment by davidnuzik** [comment]
Version: v2.2-head with ui-index of https://releases.rancher.com/ui/2.2.88/index.html (`8268cd5f`)

Keypairs show up now, but are in the old Cluster Options area (is in Nodes section in master).
Is this going to be okay?

![image](https://user-images.githubusercontent.com/45179589/61014554-e6f9b300-a33c-11e9-9204-43b1e1896b7d.png)

That said. I can confirm this is working correctly now. I see the call made to get ssh keys (Action=DescribeKeyPairs) and we indeed list all the ssh keys for the region I chose. The only minor issue is the placement is the old location before we fixed and moved to Nodes section.

I was successfully able to pick my ssh key and connect to the nodes when the cluster was up and ready without any issues.

@westlywright per our discussion I'm just going to re-open so we can fix placement of the drop-down since is easy and quick to fix. Should be in the Nodes section like we had it in master.

**Comment by davidnuzik** [comment]
Version: v2.2-head with ui-index of https://releases.rancher.com/ui/2.2.89/index.html (`8268cd5f`)

New frontend change to the UI simply moved the location of the drop-down box from Cluster Options pane down to the Nodes pane (which makes more sense) this is what we did in master as well.

I again, confirmed that we are making the call now to aws api (Action=DescribeKeyPairs) and indeed get our list of ssh keys. I picked my key, changed EKS security group to allow inbound ssh port 22, and then I could log in to each node without any issues utilizing my amazon ssh key.

Screenshot of this new placement of the dropdown (just like in master now):
![image](https://user-images.githubusercontent.com/45179589/61074974-d6dde400-a3cd-11e9-9fa4-b10ac4da59b8.png)
