### ISSUE TITLE
Default values are not getting populated in the override section when creating template revision in UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21447]
Version: master-head

Steps:
1. Create a cluster template T1 and revision R1 with overrides for few fields as below:
Allow overrides for field "Recurring etcd Snapshot Creation Period" with default value 3 and "Recurring etcd Snapshot Retention Count" with default value 2. 

In the override section, the "Default value" and "Required" fields are not populated 
![Screen Shot 2019-07-10 at 3.11.08 PM.png](https://zube.io/files/rancher/4042df44cf92315f2a3974803db78881-screen-shot-2019-07-10-at-3-11-08-pm.png)

The "Default value" field should be a editable text box . 
The checkbox for "Required" field should also be editable

Note: This issue exists when we are adding new revisions and new questions are added

**Comment by davidnuzik** [comment]
Additionally when there are required fields in the UI cluster config, such as Azure keys, these do not appear to be required when creating cluster template. They should be required if and only if we have the fields as questions (overridable) since user will be expected to provide them.
But, if we do NOT override then Azure keys (credentials) should all be required when creating cluster template. The same is true for any other required fields.

**Comment by davidnuzik** [comment]
**Validation: FAILED**
master-head (7/19/19)

Steps:
1. Create a cluster template T1 and revision R1 with overrides for few fields as below:
Allow overrides for field "Recurring etcd Snapshot Creation Period" with default value 3 and "Recurring etcd Snapshot Retention Count" with default value 2. 

In the override section, the "Default value" and "Required" fields are now shown in the UI:
![image](https://user-images.githubusercontent.com/45179589/61566469-1f7e4880-aa31-11e9-9c2c-7eb79ae4ebd8.png)

Furthermore, if you change any values in the form, these are immediately updated in the "Cluster Option Overrides" section. I.e. pictured below I changed "Recurring etcd Snapshot Creation Period" field from "4" in the previous screenshot to "5" below, UI updates Default Value here:
![image](https://user-images.githubusercontent.com/45179589/61566773-180b6f00-aa32-11e9-92d8-e9c86619251c.png)

This is true for other types as well such as booleans, etc.

"The "Default value" field should be a editable text box"
This is not the case with fields that are already editable in the form. For any custom overrides added in, then yes there is supposed to be an option to edit the Default Value.
This is not currently working -- when you click on "Add Override" this results in a JS error in the browser dev console. You also cannot remove any overrides you added either with the switch or the "-" minus/delete button. Also, if you toggled the switch to disable override and toggle back on, if you edit value the "Cluster Options Overrides" section doesn't update. None of these work correctly. As such, I created a separate issue to track this here: https://github.com/rancher/rancher/issues/21658

When you attempt to save the cluster template you will also get an error like reported in the issue above, as such I am going to re-open this issue. This may be because we are in a "bad state" because we toggled overrides off and back on, but this should work before we approve this fix in my opinion.

**Comment by westlywright** [comment]
This is by design. You as the cluster template creator are providing the default value to the template. You are providing the initial config in the way of the inputs in the form. This config is the default cluster spec that will be used to launch the cluster. When adding an override for a question in the form why would you want the default value to the override to be different than what you are providing in the initial cluster spec you've configured? That defeats the purpose of the cluster template and spec you've built.  Really the only reason we show the overrides from the form in the overrides section is because we need a way to attach `required`. 

I think you tested before the CI build was done. I've just tested master on my live server and am not seeing the JS errors.

**Comment by soumyalj** [comment]
Tested with master-build from July 22nd. 
Create a cluster template T1 and revision R1 with overrides for few fields 
Default values are populated and the "Required" field is editable as shown below:

<img width="1243" alt="Screen Shot 2019-07-22 at 9 54 01 PM" src="https://user-images.githubusercontent.com/18536626/61683697-5e2f2f80-accb-11e9-9e2f-a1c28a9a68d1.png">

**Comment by davidnuzik** [comment]
Version: master-head (7/23/19)

- Created a cluster template T1 and Revision "rev1" with overrides for a few fields.
- The default values now show up and we can change the Required field (enable or disable with checkbox).
- Clone and create another revision and the required fields are still editable.

HTTP/API look correct. When leverage the templates the clusters will be created correctly.
