### ISSUE TITLE
Google Auth - Special characters in name/email are not considered while searching for a user or a group

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21456]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Special characters in name/email are not considered while searching for a user or a group

**Expected Result:**
Special characters should be taken into consideration while searching.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Comment by mrajashree** [comment]
@sowmyav27 The special characters are being ignored which leads to search not being restrictive, but users with those characters still do show up in search results and can be added to Rancher. As we saw the google server returns the same result on doing the query rancher does, and since backend relays the same search output, it can't fix anything in this.
