### ISSUE TITLE
Google Auth - User and group search gives inconsistent results

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21452]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Login to Rancher UI
2. Go to Global --> Authentication --> Google
3. Enter all required input fields, and Authenticate with Google.
4. Enter username and password of a google user. and click on Allow
5. Google Auth gets enabled successfully.
6. In the search text field under `Site Access` section, search for users/groups

**Observations:**
on entering `thetestgsuite` lists out all users, but on entering `suite` lists no users 
on entering `test$t` lists incorrect groups 
on entering `test` lists a group - group_test (email of the group nor the name of the group begins with `test`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master-head
- Installation option (single install/HA): single

**Comment by mrajashree** [comment]
All of these results that are returned through SearchPrincipals in rancher, match the ones that are returned by directly searching using gsuite apis without rancher.

For searching users, we do a query with no field (name/email) specified and use just the search key.
As per the [docs](https://developers.google.com/admin-sdk/directory/v1/guides/search-users), such a query searches against the givenName, familyName, or email. It seems gsuite performs begins-with search on these fields and does not have an option to do contains match.
So `thetestgsuite` returns results but `suite` doesn't.

> on entering test$t lists incorrect groups
For `test$t`, gsuite api returns the same result, maybe it doesn't consider special characters, but it doesn't restrict entries with those characters from being displayed, only adds more entries
to the search results.

> on entering test lists a group - group_test (email of the group nor the name of the group begins with test
Could be because of the `_`, and how gsuite isn't considering special characters in search api. 

For all these cases results returned by gsuite and by rancher are consistent. So we can't change anything.

**Comment by alena1108** [comment]
Thank you @mrajashree. @sangeethah closing the issue as Rancher apis' results are consistent with gsuite (direct google apis).
