### ISSUE TITLE
Service hooks

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2146]
Is there a feature that allows to configure hooks?

We used hooks on `CoreOS` to prepare storage environments for some services.
It would be great if we could at least have those:
- `BeforeStart`
- `AfterStart`
- `OnFailure`
- `BeforeStop`
- `AfterStop`

**Comment by mstate** [comment]
Any word on these very useful hooks?  Looks like it's been planned for quite some time.

I need to de-provision an allocated resource per-container on stop/fail of the container.  Importantly, before it's restarted so that the resource is available for the new container.  Is there a another (or maybe better) way to do this?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
