### ISSUE TITLE
vSphere Driver Supports Cloning

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#21483]
First, try and get node initialization working with docker-machine vmwarevsphere driver with a stock ubuntu iso + cloudinit. That will involve getting an ssh-key in place for rancher to connect and install docker and rancher-agent.
 
Second, we will try and get this same approach to work using a url to a VMDK or OVA file instead of an ISO.

**Comment by cjellick** [comment]
Going to restate the above from a requirements perspective:

**Requirements**
1. The user must be able easily to use non-RancherOS OSs when provisioning VMWare VMs. The requirement can no longer be that the OS supports the "boot2docker hacks". Instead, the requirement for the image is that it supports cloud-init (so that we can use that to bootstrap the ssh key into the vm)
2. The user must be able to specify an existing VM template by name or ID
3. The user must be able to continue to use the cloud-init field that already exists on the vsphere driver.
4. We must not break any existing vsphere node templates. In other words, the change must be fully backwards compatible (or if that's not possible we have to introduce a new driver).
...
5. (Stretch goal): In addition to launching from a template, the user should be able clone from another VM. We should not attempt this until all other requirements are met and sent to QA.

**Implementation details**

Regarding #3, this could get very tricky in that the content of a cloud config script can take on many different forms. We have to experiment with all of those forms and ensure our solution won't break any existing vsphere node templates. If we cannot resolve all the scenarios, then we may need to create a new "vspehre2" driver that has different requirements/expectations for the cloud-init field so that we can more precisely control/predict the behavior without breaking existing rancher installations.

**Comment by cjellick** [comment]
@luthermonson you will need to open a UI ticket for this an make sure it gets into the v2.3 milestone. Someone on the team can explain the process for that and the labels/assignments/milestones that need to be put on it.

**Comment by cjellick** [comment]
Updated requirements:
- boot2docker hacks are acceptable bc they are just standard vm-tools workflow. requires vm-tools must be install in the base image
- support deploy from template:
  - required:
    - cloning from template inside of vsphere cluster
    - cloning from template from vsphere content library
  - nice to have:
    -  OVA. This is the most complicated because docker-machine would have to push an OVA. Would have to upload the OVA similar to how we upload the ISO now.
- clone from VM is out of scope 

UI
- Dropdown for:
  - ISO
  - deploy from template
  - clone from VM
- multi-network mapping
- multi-storage mapping

**Comment by luthermonson** [comment]
WIP PR, still testing: https://github.com/rancher/machine/pull/29

**Comment by luthermonson** [comment]
machine: https://github.com/rancher/machine/pull/37
rancher: https://github.com/rancher/rancher/pull/22999

**Comment by luthermonson** [comment]
UI: https://github.com/rancher/rancher/issues/21580

**Comment by deniseschannon** [comment]
@luthermonson Is the backend ready for this?

**Comment by luthermonson** [comment]
PR: https://github.com/rancher/rancher/pull/23242

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 6611960c9
UI: `latest-2.3`

* vSphere node template UI is updated
* Can create nodes from:
  * Datacenter Template
  * Content Library
  * Clone existing machine

RancherOS ISO install has regressed: #23797
