### ISSUE TITLE
Should not be able to assign pod security policy in project

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#21548]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug - It seems the GUI does indeed have support for disabling the PSP setting in project settings (see `local` cluster). 

**Steps to reproduce (least amount of steps as possible):**
1. Create RKE based cluster
2. Make sure `Pod Security Policy Support` is `disabled` in cluster option
3. Navigate to Project/Namespaces, click Add Project

**Result:**
User can select a pod security policy for the project. But this configuration will not take effect because the cluster was not configured with PSP support.

**Expected Result:**
When cluster is not configured to support PSP, use can not assign a PSP to a project.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by rmweir** [comment]
@jiaqiluo you will want to attempt to apply a template to a project by using the api.

**Comment by jiaqiluo** [comment]
the bug is reproduced in v2.3.1 
Steps:
- run Rancher v2.3.1  single install
- add an ec2 cluster with NO psp enabled
- add a new project, notice that psp can be setted
<img width="1383" alt="Screen Shot 2019-11-04 at 10 07 43 AM" src="https://user-images.githubusercontent.com/6218999/68141549-f9e75300-feea-11e9-90fc-6fe841960897.png">
- set the psp to be restricted 
- deploy a workload in the project with setting privileged to be `Yes: container has full access to the host`
- the worload is deployed successfully, which indicates the psp is not applied actually. 
<img width="1388" alt="Screen Shot 2019-11-04 at 10 11 06 AM" src="https://user-images.githubusercontent.com/6218999/68141810-74b06e00-feeb-11e9-97c3-ba2d2998e3b2.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:v2.3-head da8cbdb71 with the default UI-index `latest-2.3`

1. When the cluster's psp is disabled, the project create/edit page does not show the option for psp anymore
<img width="1271" alt="Screen Shot 2019-11-04 at 11 35 47 AM" src="https://user-images.githubusercontent.com/6218999/68147712-e5f61e00-fef7-11e9-99dd-3229635f619b.png">

2. if sending the action request from API, a 422 error will be returned.
<img width="527" alt="Screen Shot 2019-11-04 at 11 36 22 AM" src="https://user-images.githubusercontent.com/6218999/68147761-0920cd80-fef8-11e9-82fc-cf329366256f.png">
