### ISSUE TITLE
[2.2.5] UI: Click "Enable monitoring" link in cluster dashboard cannot go to cluster monitoring page

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#21541]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a cluster.
2. Click "Enable Monitoring to see live metrics"

**Result:**
Can not go to cluster monitoring page.

![image](https://user-images.githubusercontent.com/18737885/61263020-fef88900-a7b9-11e9-80e5-4460d0e71d43.png)

**Environment information**
v2.2.5

It was introduced in this commit https://github.com/rancher/ui/commit/cd663c8d183004aa4a43f3ad24cc05b0a1eff291

**Comment by davidnuzik** [comment]
Version: v2.2.5
**Reproduction:**

I was able to reproduce the issue exactly as described in the issue description. There are no browser dev console errors. Nothing happens when you click the link.

**Comment by saintanger** [comment]
Version: v2.2.5

Same here, you cannot get to the view for the monitoring. You cannot click on updating an existing one either

**Comment by davidnuzik** [comment]
Workaround:

In UI, go to the cluster, on navbar, pick Tools menu and from there click on Monitoring. This brings you to the same config page for monitoring.
![image](https://user-images.githubusercontent.com/45179589/61483270-541ad300-a951-11e9-8a41-a22eb7098191.png)

**Comment by alena1108** [comment]
Can be tested with `v2.2.6-rc2`

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.5
Already reproduced earlier in this issue see comment above https://github.com/rancher/rancher/issues/21541#issuecomment-511885231

**Validation:**
v2.2.6-rc2

1. Add a cluster.
2. Click "Enable Monitoring to see live metrics"

**Result:** Now we are properly taken to the monitoring config (we are correctly routed to /c/CLUSTERID/monitoring/cluster-setting).
I could successfully set up config and enable monitoring; it works as expected based on a smoke test. This issue was just a spelling mistake that broke the link action, this is now fixed (reviewed PR).
No browser web console errors observed.
