### ISSUE TITLE
Cloud credentials support for Linode node driver

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#21554]

**Comment by alena1108** [comment]
https://github.com/rancher/ui/pull/2834
https://github.com/rancher/rancher/pull/20281

**Comment by davidnuzik** [comment]
Note, there is a known issue that we see other cloud creds when try to add Linode node template. This is a known issue and is addressed here: https://github.com/rancher/rancher/issues/21601

**Comment by davidnuzik** [comment]
master-head (7/19/19) (`4aa4e1ab`)

This adds the ability to leverage Cloud Credentials with Linode.

Shown below is add Linode cloud credential via add node template method:
![image](https://user-images.githubusercontent.com/45179589/61555037-46c61d00-aa13-11e9-85c2-7b4ad84c083d.png)

Shown is add Linode cloud credential via Cloud Credentials page:
![image](https://user-images.githubusercontent.com/45179589/61555081-5e9da100-aa13-11e9-8e83-5af5d7bfb2c9.png)

Both these modals work as expected. I was successfully able to create Linode Cloud Credentials with my API key. I fuzzed data (plug in garbage data) and tried to break this. I could not identify any issues.

This cloud credential also features validation like with ec2 and digitalocean. If your API key does not validate you will get a message explaining the issue:

![image](https://user-images.githubusercontent.com/45179589/61555187-9c9ac500-aa13-11e9-947c-913ad424b0c8.png)
We basically make a call to https://api.linode.com/v4/profile to try to validate the API. If this fails the error of the issue is shown in the UI similar to how we handle validation with DO/EC2 api keys.

Supplying NO key results in UI taking no action. The field is not required (Access Token). As such I opened a separate issue for this here: https://github.com/rancher/rancher/issues/21651

The core functionality however is working without any issues.
UI/HTTP/API look good. UI conforms to API schema.

**Comment by davidnuzik** [comment]
master-head (7/19/19) (4aa4e1ab)

Additional checks were performed per the internal node template test plan (it includes cloud credential checks). Also ensured can edit cloud credential and delete without any issues both as admin and regular users (also only creator can see their own cloud credentials). The internal test plan was updated to include Linode.

All of these passed except for existing known issues. I found one issue when edit a Linode node template, cloud credential is missing: https://github.com/rancher/rancher/issues/21652

Below are some other known issues.
https://github.com/rancher/rancher/issues/19759
https://github.com/rancher/rancher/issues/21601
https://github.com/rancher/rancher/issues/21651
https://github.com/rancher/rancher/issues/21503
https://github.com/rancher/rancher/issues/21215
https://github.com/rancher/rancher/issues/20577
https://github.com/rancher/rancher/issues/19756
