### ISSUE TITLE
UI Updates for vSphere Templates

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#21580]
The docker-machine vsphere driver will be getting some updates to take more parameters which will need to be passed in through the front end. We are planning for some of the following but ultimately the support is tbd right now until we get into code.

Backend work being done against this issue rancher/rancher#21483

Some things we'd like to try are the following
* Clone from "type" concept, will be 3 options: ofv, template, content library
* Each of those three types take one thing and should hopefully just be a single text field, needs investigation.
* Multiple Networks, will probably be key/value map like parameters are today
* Mutliple disks, will probably be a key/value map like parameters are today

**Comment by deniseschannon** [comment]
@luthermonson Is the backend ready for this?

**Comment by codyrancher** [comment]
Feedback captures from demo.

1. Clone vs manual:
  a. Condense the dropdowns for manual vs clone and the secondary clone dropdown (that has vm, template, etc) into a single dropdown that reflects the verbage in the vsphere UI
  b. in that dropdown, change manual to something more meaningful like “Deploy from rancheros iso (legacy)“. I might even say use the word deprecated instead of legacy so that it is more strongly discouraged
  c. in that dropdown, default to one of the clone options
2. move networks out of scheduling and into instance options
3. clean up the rest of the labels and wording to match vsphere verbage
4. custom attributes and tags get their own accordian sections
5. cloud-init needs to be its own line. dont wrap with the previous inputs
6. at least the vm and template dropdowns should be searchable lists instead of just normal  dropdowns

7. the cloud-config text box can/should be a yaml editor

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3` 

* Fields are populated by data from vCenter:
  * Datacenter
  * Resource Pool
  * Data store
  * Folder
  * Host
  * Networks
  * Tags
  * Custom Attributes
* User is able to select creation method
  * Fields are updated and populated based on creation method
* Deploy from RancherOS ISO is marked as deprecated
