### ISSUE TITLE
How to build rancher from source code?

### ISSUE THREAD

**Issue by zbialik** [rancher/rancher#21592]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**

1. download rancher/rancher source code from github repository (v2.2.5)
2. execute `make build` while inside source code main directory
3. copy out the `rancher `and `agent `executable from inside the bin directory and paste into the package folder in the working directory
4. change to package folder and execute `docker build .`
5. attempt to run the built rancher image in an Air-gap environment

**Result:**
**rancher logs shows:**
`[ERROR] failed to serve UI: Get https://releases.rancher.com/ui/latest2/index.html: dial tcp [2606:4700:20::6818:1133]:443: socket: address family not supported by protocol `

Why is the compiled rancher server looking for this html on the internet? Shouldn’t it be stored locally?

**UPDATE**: I just noticed that the last commit to the scripts/build-server file has the message:

**["Fix UI can not open in dev version"](https://github.com/rancher/rancher/commit/083e73e7b25b2b623c7dfaa94dc94007a003b7dc)**

This looks relevant to my issue. Is there anyway I can get around this? Also, is there a way to not have to tag my rancher-agent with :dev to get this custom built rancher server and agent working together? The version of the rancher-agent that is used when I run the custom rancher-server is always defaulted to :dev but I would rather have it tagged with the same version I tag the rancher-server.

**Other details that may be helpful:**
I am trying to update the aws-sdk-go that rancher uses, which is why I need to rebuild the image from source.
I am deploying rancher in HA configuration in an air-gapped environment.

I haven't found any documentation on building rancher from source code. I believe I made some mistake when building rancher and need to know the correct way to do so. I have also posted in https://forums.rancher.com/t/how-to-build-rancher-from-source/14810

Thanks for the help!

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.5 (also tried v2.2.4)
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud (AWS)
- Kubernetes version (use `kubectl version`): 

```
v1.14.3
```

- Docker version (use `docker version`):

```
1.13.1
```

**Comment by dramich** [comment]
Hey @zbialik, the issue stems from not tagging rancher with a version when running the build. The build being created under `dev` tells rancher to fetch the UI from the internet, if you don't want that to happen there are a couple of options.

1. Set the build with a version that starts with `v`. If you take a look [here](https://github.com/rancher/rancher/blob/master/scripts/build-server#L11) we set that settings based off the tag coming in. 
2. After you have built rancher and have it running you can change the setting since the UI is still built in. Going to `<server-url>/v3/settings/ui-index` and changing the value to `local` should work with a reboot. 
3. Set a version [here](https://github.com/rancher/rancher/blob/master/main.go#L27) but I wouldn't recommend that. 

The easiest way is to tag the build with a `v.xxx` though.

**Comment by zbialik** [comment]
@dramich Thank you for the reply. We actually discovered the `version `file in the `scripts `folder and performed your 2nd workaround option prior to you commenting. We've since went with your first option and are able to successfully hit the rancher UI.

I would like to add that we also had to update the `Dockerfile`'s such that the version would read to something other than 'dev'. 

Thanks for the help!
