### ISSUE TITLE
Error on pipeline setup page

### ISSUE THREAD

**Issue by jungju** [rancher/rancher#21608]
rancher version : 2.2.5

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enter https://<rancher-domain>/p/<project-id>/pipeline page
Memory Reservation : empty
CPU Reservation : empty
Memory Limit : empty
CPU Limit : empty
Update Limit and Reservation

Enter https://<rancher-domain>/p/<project-id>/pipeline page
error

**Result:**

![image](https://user-images.githubusercontent.com/809189/61438799-40846200-a97b-11e9-9227-25b2a1f6edb3.png)

**Comment by gitlawr** [comment]
I'm able to reproduce this:
1. set up pipeline using Github in the Default project
2. go to the setting page via `project - tools - pipeline`
3. Remove the resource configurations and click update.
Result: fails to load the setting page after that.

**Comment by gitlawr** [comment]
Workaround in v2.2.5 to recover:
Go to
1. `https://<rancher-url>/v3/project/<cluster-id>/pipelineSettings/<projext-id>:executor-memory-limit`
2. Click `Edit` button.
3. Remove the value field(which is set to `Mi`)
4. Click `Show Request` 
5. Click `Send Request`

Repeat the above process to clean the invalid value set for `executor-memory-request`, `executor-cpu-request` and `executor-cpu-limit`

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.2.5`
Steps:
set up pipeline using Github in the Default project
go to the setting page via `project - tools - pipeline`
Remove the resource configurations and click update.
![Screen Shot 2020-02-04 at 1 54 31 PM](https://user-images.githubusercontent.com/57409052/73787186-fa94bd00-4757-11ea-8202-bbdfd16461c9.png)
Result: fails to load the setting page afterwards.
![Screen Shot 2020-02-04 at 1 54 52 PM](https://user-images.githubusercontent.com/57409052/73787131-dfc24880-4757-11ea-96eb-d97e09e52d10.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version bc8175f6f`
Fields can no longer be blank. Deleting fields sets minimum to:
Memory Reservation: 4
Memory Limit: 4
CPU Reservation: 0
CPU limit: 0
![Screen Shot 2020-02-04 at 2 05 31 PM](https://user-images.githubusercontent.com/57409052/73787194-ff597100-4757-11ea-9beb-9e3f61f7f435.png)
Settings page can be accessed afterwards.
