### ISSUE TITLE
Namespace UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#21629]
**Version:** master-head

**Steps to reproduce (least amount of steps as possible):**
1.  Create a new project
2.  Go to Add Namespace page

**Result:**  
- [x] Add a namespace, "In this Project" is redundant cause you won't see any other projects on this page.  It's always "In this Project"
![image](https://user-images.githubusercontent.com/11514927/61499998-14b6ab80-a97e-11e9-91fd-42c3e4d08882.png)

**Comment by izaac** [comment]
@tfiduccia 

In version 2.2.8 If I have a project with description it makes a bit more sense as you can have an extra indication on where you are at in the UI as a user.

![Screen Shot 2019-09-03 at 3 25 03 PM](https://user-images.githubusercontent.com/27659/64212750-3b15a500-ce5f-11e9-8eb9-c31e28f43b49.png)

Otherwise the only indication that you're in the project level (p1 in this case) is the little project name in the cluster dropdown.

![Screen Shot 2019-09-03 at 3 26 59 PM](https://user-images.githubusercontent.com/27659/64212823-72845180-ce5f-11e9-9025-c9fe36d41910.png)

I think keeping that table element removed but also appending the project name to the `h1` in that project page could give a better user experience, unless there's some limitation like a very large namespace name that would probably not fit by resizing the browser.

Like `Namespaces of project p1`, but I'm open for better wording if you think this is a better approach.

@davidnuzik @vincent99

**Comment by tfiduccia** [comment]
After discussion going to leave as is.

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (09/03/2019)

This is looking good, the table header is no longer displayed in the project page with the namespaces table specific for that project.
