### ISSUE TITLE
[Alerting] replicate number from state isn't the desired replicate number

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#21639]
Rancher version: 2.2.4

Step to reproduce:
1. Add notifier
2. Add project workload replicate persent alert with label selector
3. Add workload with 2 pod and ```Rolling: stop old pods, then start new``` stage
4. Upgrade the workload with couldn't match resource request
5. Then there should be 1 active pod and 1 error pod, should send out alert
6. The alert does not send out

Root cause:
The workload state watcher uses the replicate number in crd state as the desired replicate number, which is the current pod number(included unavailable pod). Also, convert float into int32 lose accurate in calculation, for example ```availableThreshold := int32(percentage) * (wl.Status.Replicas) / 100``` -> ```availableThreshold := int32(70) * (2) / 100```, availableThreshold is 1 after calculating, in above case, there left 1 active pod, so will not trigger the alert

**Comment by loganhz** [comment]
@patrick0057 ^^

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher: v2.2.4

Steps:
- run Rancher container
- add an RKE cluster
- at the cluster level, add Slack as the Notifier
- go to the default project
- deploy a workload `w1` with 2 replicas
- add a project level alert that alerts if `w1` has less than 70% available
- edit `w1` upgrade policy be to `Rolling: stop old pods, then start new`, and add node selector `name = Rancher` which does not exist in any node

Result:
- the workload `w1` is stuck in the upgrading state with 1 pod active 1 pod failed
- but the alert is not triggered 
<img width="1429" alt="Screen Shot 2019-08-12 at 4 41 56 PM" src="https://user-images.githubusercontent.com/6218999/62906166-702c4d00-bd22-11e9-8b35-74918a923382.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher: master-head 734bd953

Following the same steps as the previous comment, now the alter is triggered and sent out to Slack

![Screen Shot 2019-08-12 at 5 01 07 PM](https://user-images.githubusercontent.com/6218999/62906238-cd280300-bd22-11e9-8c37-a7c80402c196.png)
