### ISSUE TITLE
[UI] Service - critical bug: edit service, and then save, selector miss, 100% reproduce!

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#21670]
*Describe your issue here*
critical bug: edit service, and then save, selector miss, 100% reproduce!
![1](https://user-images.githubusercontent.com/4767546/61605787-af163800-ac79-11e9-90b7-e6fac92641a3.png)
![2](https://user-images.githubusercontent.com/4767546/61605790-b2a9bf00-ac79-11e9-96ed-ecdf0c054a86.png)
![3](https://user-images.githubusercontent.com/4767546/61605798-b5a4af80-ac79-11e9-9b90-664646bdf9ed.png)
![4](https://user-images.githubusercontent.com/4767546/61605799-b89fa000-ac79-11e9-9345-82a053f145d8.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3-v2.2.5` UI: `v2.2.41` |
|Route|`containers.index`|

**Comment by davidnuzik** [comment]
Note: Repro in older v2.2.5, create service in UI. Edit as YAML and change selector. Save. Edit again - check selector.

**Comment by davidnuzik** [comment]
@loganhz I'm having a hard time reproducing. I've reviewed your PR and see your steps mentioned but am not seeing the issue in v2.2.5. Any idea what I'm missing?

- Tried to create nginx workload, it creates service for me automatically, attempt to View/Edit YAML and change selector and it works, remove selector it works.
- Try to delete the nginx service and import YAML and paste in with the selector and it works
- Try to create nginx service with import YAML and don't include the selector first time (create) then edit YAML and add it in and it works.

I wasn't successful in finding a situation where the selector did not work when edit as YAML or import YAML, etc.

**Comment by loganhz** [comment]
@davidnuzik 

1. Create a workload
2. Go to the `Edit` page for the auto created svc in Service Discovery page by clicking `Edit` instead of `Edit as YAML`.
3. Just click `Save` without changing anything
4. Click `View YAML` to check if the selector field is missing in the yaml.

**Comment by davidnuzik** [comment]
Thanks Logan.

**Reproduction:**
v2.2.5

- Create an nginx workoad with port mapping.
- Rancher automatically creates service. View/Edit in YAML this service, notice our selector is correct currently:
![image](https://user-images.githubusercontent.com/45179589/62899357-76afca00-bd0c-11e9-916c-7f3cb859529c.png)
- Cancel out of the view/edit YAML. Edit the service. Save (make no changes).
- View/Edit in YAML again. The selector is missing now!
![image](https://user-images.githubusercontent.com/45179589/62899432-97781f80-bd0c-11e9-9c26-a95785c65efc.png)

**Validation:**
master-head (v2.3) (8/12/19)

- Perform the steps per the above reproduction section again.
- Upon the last step we can see the selector is still there now. (The issue is resolved).
![image](https://user-images.githubusercontent.com/45179589/62900567-52a1b800-bd0f-11e9-94b4-8a8b0427f1eb.png)
