### ISSUE TITLE
[UI] Cluster Templates - Able to revoke access on template even if in use by other users

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21686]
Version: master-head (7/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create cluster template, share with public.
- As standard user, leverage this public template to create a cluster.
- Log back in as the admin, revoke the public access. The UI lets us do this even though it's actively in use by a cluster.

**Result:**
Is this expected behavior? If so I can test further and close the issue. My expectation was that if the template is in use we should not be able to revoke access or this will break things for users currently using the templates on their clusters.

**Comment by prachidamle** [comment]
This is an expected behavior, sharing access is done via editing templates 'members' field - editing a clusterTemplate even if it is in use by some clusters is allowed - the running clusters are not affected. 

Note that editing a **clusterTemplateRevision** if it is in use by some clusters is not allowed.

**Comment by davidnuzik** [comment]
Closing the issue. This is expected behavior.
