### ISSUE TITLE
UI - Cluster creation from template revision fails when attempted again after a failure.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21723]
Rancher Server version - Build from master

Steps to reproduce the problem:
Create a cluster with cluster template and do not provide a cluster name.
User is presented with error message `Validation failed in API: Cluster name is required`
Provide a cluster name and create again.
Stuck in "Saving" state forever.

<img width="1410" alt="Screen Shot 2019-07-23 at 2 50 46 PM" src="https://user-images.githubusercontent.com/4266958/61751282-a9455300-ad5c-11e9-9f66-e3374aac29a4.png">

**Comment by davidnuzik** [comment]
Version: master-head (7/29/19)

I tested this again and am no longer able to reproduce the issue. This appears to be fixed with the caching fixes put in recently.
I followed the steps to reproduce (outlined below) in four different scenarios (four different templates). Note, before testing I have already created clusters both with and without templates. Thus, if we were still caching incorrectly I should have seen the issue (I did not).

- Create a cluster with cluster template and do not provide a cluster name.
- User is presented with error message `Validation failed in API: Cluster name is required`
- Provide a cluster name and create again.
Now we are no longer stuck in the "Saving" state forever. The cluster provisions without any issues in all four cases (templates). The clusters are created with the correct k8s version chosen. No JS/TypeErrors. UI/API appear correct; ensured answers values appear correct.

Templates/cases tested:
_Template 1:_ k8s v1.15.0-rancher1-2 chosen WITH override.
_Template 2:_ k8s v1.15.0-rancher1-2 chosen WITHOUT override.
_Template 3:_ k8s v1.15.x chosen WITH override.
_Template 4:_ k8s v1.15.x chosen WITHOUT override.

Other tests:
Test again, but change k8s version for templates that allow override. No issues found here as well.
