### ISSUE TITLE
UI - cluster creation fails with "cannot set rancherKubernetesEngineConfig and clusterTemplateRevision both"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21726]
Rancher server version - Build from master

Steps to reproduce the problem:
1. Create a cluster with a cluster template.
2. Create another cluster . At this point , the cluster template used in step 1 will be pre selected.
3. Choose to create without a template by unselecting this "Use an existing cluster template" option.
4. Create this cluster without providing cluster name, so it fails to get created.
5. Add cluster name and create.

Cluster creation fails with "cannot set rancherKubernetesEngineConfig and clusterTemplateRevision both"

Even though, "Use an existing cluster template"  is not selected , UI sends the cluster template Id in the create cluster call and fails.

<img width="1409" alt="Screen Shot 2019-07-23 at 2 57 16 PM" src="https://user-images.githubusercontent.com/4266958/61752473-a8aebb80-ad60-11e9-9454-17ecdb9bba2c.png">

**Comment by davidnuzik** [comment]
Version: master-head (7/29/19)

I am no longer able to reproduce the issue. Caching fixes are in, but most notably you must opt-in to picking a cluster template each time you create a cluster now. (This assumes enforcement is off so we test with it off and on, these are our two testing scenarios).

_Scenario 1 - Enforcement is off:_
- Create a cluster with a cluster template, you must pick "Use an existing cluster template" in order to get the CT list and leverage one to create a cluster.
- Create another cluster, notice that this is no longer picked. You must manually pick it again to create via a cluster template again.

I encountered no issues creating both clusters. I also ensured that while we are still setting up to create our second cluster I can check, then uncheck the "Use an existing cluster template" option and that the UI updates accordingly and that I can create a cluster successfully too after doing this (i.e. it didn't use a template).

_Scenario 2 - Enforcement is on:_

Blocked by https://github.com/rancher/rancher/issues/21747 (can't pick anything under "Cluster Options" so can't create a cluster as non-admin.
