### ISSUE TITLE
[api-spec] - insufficient documentation, or too general

### ISSUE THREAD

**Issue by wolfch** [rancher/rancher#2175]
This document only describes generic resource types and their CRUD operations - I would like to be able to programatically perform "rancher-compose up" via the rancher REST API, however, so far, I have not found any documentation for this.  I used tcpdump to try to reverse-engineer the protocol, but the process of converting docker-compose.yml/rancher-compose-yml into the appropriate POST messages seems to be too involved to reproduce reliably.  

Is there a reason why this is not documented, or have I just failed to find the documentation?

**Comment by vincent99** [comment]
The API spec is generic, and this is documentation on how to build a compliant server and how clients should behave.  The Rancher API is one implementation of this, but any other APIs we have will also follow it and share the same clients/tooling.

The UI, rancher-compose, and internal communication uses it, but Rancher API is not documented basically because we initially focused on supporting the "native experience" (`docker run`) over giving people a proprietary API.  It will definitely eventually be properly documented and supported, but until then releases may (and some definitely will, #384 and #1052) contain breaking changes.

Since the spec provides schema with every resource type and info about every field, the API UI (click the endpoint in Rancher in a browser) acts somewhat like auto-generated documentation.  You can click create in collections and fill in the fields, see the equivalent curl request, etc.  it doesn't tell you what anything *means*, but does tell you almost everything you can do.

There is no simple equivalent of `rancher-compose up` though, the real logic to determine what has to be deleted/creates/started/linked is currently all in the CLI.  So as you saw it makes many list/create/stop/start requests to the API for individual services.
