### ISSUE TITLE
[UI]Support exist condition for metric alert

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#21790]
UI issue for https://github.com/rancher/rancher/issues/21302

**Comment by davidnuzik** [comment]
_QA Testing notes (will delete this later)_
Reference Jack's test in the backend issue https://github.com/rancher/rancher/issues/21302#issuecomment-521792791 I can execute the same tests but utilizing the UI (and perform all standard UI checks along the way).

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/22/19)

**Summary:**
This change adds a "Not Null" condition for metric alerts (exists condition). It also allows us to have an expression with multiple parts now such as something like this (taken from the backend issue #21302 )
`predict_linear(node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"}[6h], 4*60*60) <0
and
node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} < 0.2 and node_filesystem_readonly_bytes{app="node-exporter",fstype=~"ext.|xfs"} == 0`
Last, we can supply our own expressions now rather than having to pick something form the Expression drop-down menu.

**Validation:**
I performed some checks similar to tests done in the backend issue #21302 
During these checks I did not encounter any issues and the expressions I tested with and new "Not Null" condition appeared to work correctly. Note, Jack has already tested this area in the backend issue so I did not go into too much detail. I just did various simple checks. One check included setting an expression with a value that is 0 (but not null) and I ensured that the alert is triggered in this case too.

From a UI perspective I ensured that the UI, HTTP, and API all look good. I did some additional checks / smoke tests and I was not able to identify any issues. I ensured notifications work as expected as well (set condition to cause trigger of notification and confirm I get the notification sent to me, not just triggered in the UI on the Alerts page).

**Additional Notes:**
During my tests I noticed the drop-down search for "Expression" is rather slow. I entered an issue to see if we can somehow improve performance in the future. Issue: https://github.com/rancher/rancher/issues/22361

**Screenshots/Examples:**
![image](https://user-images.githubusercontent.com/45179589/63543275-4bc93100-c4d7-11e9-98b7-877732669233.png)
![image](https://user-images.githubusercontent.com/45179589/63543293-5388d580-c4d7-11e9-9f42-996da78271a2.png)
![image](https://user-images.githubusercontent.com/45179589/63543306-5a174d00-c4d7-11e9-83c5-b0535a616538.png)
