### ISSUE TITLE
[UI] Cluster Templates - Azure cloud provider cluster creation from a cluster template in UI does not display the selections as per the cluster template

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21815]
Version: Master-head

Steps
1. Create a cluster template/revision T1/R1 in UI with cloud provider set and provide all the credentials

<img width="1243" alt="Screen Shot 2019-07-28 at 6 50 38 AM" src="https://user-images.githubusercontent.com/18536626/62001175-f8e2a080-b107-11e9-92ee-aaba0e57b366.png">
<img width="800" alt="Screen Shot 2019-07-28 at 6 52 42 AM" src="https://user-images.githubusercontent.com/18536626/62001984-1c621700-b119-11e9-9e1a-63b3fd831192.png">

2. Create Cluster and choose the template revision R1. Once the cluster template is selected, the screen shows the cloud provider disabled. The azure cloud provider selection in the template is not honored in UI.

<img width="1178" alt="Screen Shot 2019-07-28 at 8 16 03 AM" src="https://user-images.githubusercontent.com/18536626/62001518-fbe18f00-b10f-11e9-969d-2ef60ae79d50.png">

Cluster template API below:

```
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509",
"type": "/v3/schemas/authnConfig"
},
"cloudProvider": {
"azureCloudProvider": {
"aadClientCertPath": null,
"aadClientId": "REDACTED",
"cloud": null,
"cloudProviderBackoff": false,
"cloudProviderBackoffDuration": 0,
"cloudProviderBackoffExponent": 0,
"cloudProviderBackoffJitter": 0,
"cloudProviderBackoffRetries": 0,
"cloudProviderRateLimit": false,
"cloudProviderRateLimitBucket": 0,
"cloudProviderRateLimitQPS": 0,
"loadBalancerSku": null,
"location": null,
"maximumLoadBalancerRuleCount": 0,
"primaryAvailabilitySetName": null,
"primaryScaleSetName": null,
"resourceGroup": null,
"routeTableName": null,
"securityGroupName": null,
"subnetName": null,
"subscriptionId": "REDACTED",
"tenantId": "REDACTED",
"type": "/v3/schemas/azureCloudProvider",
"useInstanceMetadata": false,
"useManagedIdentityExtension": false,
"vmType": null,
"vnetName": null,
"vnetResourceGroup": null
},
"name": "azure",
"type": "/v3/schemas/cloudProvider"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "1.13.x",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},


```

**Comment by davidnuzik** [comment]
Version: master-head (8/7/19)

I followed the steps and created my CT with "Azure" cloud provider and filled out the four required fields. (No overrides provided)

I then leveraged my template to create a cluster. While doing so I confirmed that now "Azure" cloud provider is picked (UI honors CT now).

![image](https://user-images.githubusercontent.com/45179589/62648237-3d8bea00-b907-11e9-968f-fa50dfe4d8b3.png)

And my info from the CT is shown in the UI (less the secret which is supposed to be hidden)
![Screen Shot 2019-08-07 at 11 34 26 AM](https://user-images.githubusercontent.com/45179589/62648295-5dbba900-b907-11e9-9da5-30e8ba6f61c0.png)
![Screen Shot 2019-08-07 at 11 35 05 AM](https://user-images.githubusercontent.com/45179589/62648344-74620000-b907-11e9-8d70-c15278eb7e21.png)

I tried again, this time applying overrides for the Azure four required fields and this works too. Azure cloud option is still picked.

This is now working correctly, except for an issue with my aadClientSecret. It was supplied in the CT but the UI claims it's not being supplied. This is not true so I created a SEPARATE issue to track this because the core functionality of this issue is confirmed (UI now honors our "Azure" cloud option). The aadClientSecret issue is tracked here: https://github.com/rancher/rancher/issues/22038

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/19/19)

I am reopening this issue. We appear to have regression of the issue.
I essentially just created a CT again with the same steps. My CT looks like this:
![image](https://user-images.githubusercontent.com/45179589/63299483-bd606f80-c28a-11e9-901c-ea502225b663.png)


When I attempt to create a custom cluster and leverage the template "Cloud Provider" is "Disabled" again even though my CT defines Azure as the cloud provider.
![image](https://user-images.githubusercontent.com/45179589/63299439-9e61dd80-c28a-11e9-8473-604f145f0d71.png)

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/3/19)

I tested again and now have the same result as we had before the regression. This is worked as expected now because the UI now shows "Cloud Provider" as "Enabled" when we leverage the CT.
Reference https://github.com/rancher/rancher/issues/21815#issuecomment-519221818
