### ISSUE TITLE
[UI] Cluster Templates - UI turns blurry and non-editable when adding a new version to a template created from API

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#21816]
Version: Master-head from July 28

Steps:
1. Create a template and revision T1/R1  in API
2. In the rancher UI, add another revision to the template. 
The screen turns blurry and non-editable as below:
![Screen Shot 2019-07-28 at 9.28.12 AM.png](https://zube.io/files/rancher/20d3b379da2969a8c01d693f2ba52ca9-screen-shot-2019-07-28-at-9-28-12-am.png)

A 304 status code is displayed as below:
![Screen Shot 2019-07-28 at 9.34.13 AM.png](https://zube.io/files/rancher/b2878758c01a87182afa2b347d58a65a-screen-shot-2019-07-28-at-9-34-13-am.png)

**Comment by soumyalj** [comment]
Tested with master-head build from July 31. The issue still persists
1. Using the API, create a template and revision T1/R1 
2. In the rancher UI, add another revision to the template.
UI turns blurry and is not editable

<img width="1353" alt="Screen Shot 2019-07-31 at 8 16 46 AM" src="https://user-images.githubusercontent.com/18536626/62180003-11eb8b80-b36c-11e9-86d5-fb0b267ed684.png">

<img width="682" alt="bug_request_header" src="https://user-images.githubusercontent.com/18536626/62180265-077dc180-b36d-11e9-9987-632d33e38266.png">


<img width="669" alt="Screen Shot_bug" src="https://user-images.githubusercontent.com/18536626/62180368-65aaa480-b36d-11e9-8909-49d685f93739.png">

**Comment by davidnuzik** [comment]
Note: use the clusterConfig provided and attempt to create CTR in API and link to CT. See if UI works with this now.

**Comment by davidnuzik** [comment]
Version: master-head (8/7/19)

1. Create CT in API. Create CTR with clusterConfig of:
`{"dockerRootDir":"/var/lib/docker","enableClusterAlerting":false,"enableClusterMonitoring":false,"enableNetworkPolicy":false,"type":"clusterSpecBase","name":"wwww","rancherKubernetesEngineConfig":{"addonJobTimeout":30,"ignoreDockerVersion":true,"sshAgentAuth":false,"type":"rancherKubernetesEngineConfig","kubernetesVersion":"v1.13.5-rancher1-3","authentication":{"strategy":"x509","type":"authnConfig"},"network":{"plugin":"canal","type":"networkConfig","options":{"flannel_backend_type":"vxlan"}},"ingress":{"provider":"nginx","type":"ingressConfig"},"monitoring":{"provider":"metrics-server","type":"monitoringConfig"},"services":{"type":"rkeConfigServices","kubeApi":{"alwaysPullImages":false,"podSecurityPolicy":false,"serviceNodePortRange":"30000-32767","type":"kubeAPIService"},"etcd":{"creation":"12h","extraArgs":{"heartbeat-interval":500,"election-timeout":5000},"retention":"72h","snapshot":false,"type":"etcdService","backupConfig":{"enabled":true,"intervalHours":12,"retention":6,"type":"backupConfig"}}}},"localClusterAuthEndpoint":{"enabled":true,"type":"localClusterAuthEndpoint"}}`
- Ensure is enabled, etc.

2. In the UI ensure CT and CTR shows up:
![image](https://user-images.githubusercontent.com/45179589/62641797-470e5580-b8f9-11e9-82a1-1ea82f7e53bc.png)
- Create a revision (via Clone Revision and Revision from Default)

Both work without any issues. UI is not "Blurry" and is usable. Cluster Template looks correct (except for k8s version which is expected because the clusterConfig defines k8s version that is not supported). I tried again with proper k8s version and it works correctly.
