### ISSUE TITLE
Design of istio UI & flow

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#21887]
Wireframes:
https://xd.adobe.com/view/3a10455b-f004-4bc1-636d-0415a0fed4b0-4c21

**Comment by davidnuzik** [comment]
Wireframe page 1 looks good and has been validated. Wireframe page 2 menu looks different. Wireframe page 3 -- I cannot tell any difference.
@tfiduccia let's review in person so I can ensure I understand all the changes.

**Comment by davidnuzik** [comment]
Based on Slack discussion, changes are expected. Page 2 will be addressed further via https://github.com/rancher/rancher/issues/21985 which asks to create a "Secrets" page to encapsulate some other pages.
Page 3 is for the "istio" button which needs to be tested.

**Comment by davidnuzik** [comment]
Version: master-head (8/5/19)

I tested each wireframe page:

Page 1:
Ensured "Enable Monitoring" checkbox is disabled and checked. Confirmed I can bring up Istio without any issues.

From a usability perspective I'm not a huge fan, but this is an okay solution for now. I created this separate issue to track the fact that we can't tweak monitoring resources before bringing it up (enable it). The tooltip seems to claim otherwise. 
I created https://github.com/rancher/rancher/issues/21994 for review.

Otherwise, from a functionality standpoint this works fine.

Page 2:
The new "Resources" menu was validated. This makes sense to me from a usability perspective and I approve of this. I created #21985 to track another enhancement in this area we would like to get in.

Page 3:
This adds an Istio button. It's actually called "Enable Istio Auto Injection" now and this works without any issues for me.

![image](https://user-images.githubusercontent.com/45179589/62503030-42398c80-b7a7-11e9-94c4-9e144a61ccdf.png)

Note there is a typo here and this is tracked here: https://github.com/rancher/rancher/issues/21995

I wasn't able to find any other issues and approve of the changes except otherwise noted above.
