### ISSUE TITLE
[UI] Suppress autoComplete for our custom dropdowns

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21895]
Version: master-head (7/31/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have AutoComplete on in your browser. Have some data in it for various fields.
- Click in the text box for our custom drop downs we have such as those we use for listing users/groups, picking MCapp projects, picking hosts for Istio Virtual Service / Destination Rules.

**Result:**
The browser's autocomplete will offer suggestions, blocking the options shown in our drop down.
Is there any way to suppress the autoComplete functionality somehow? Is this even possible? If so could we implement this in all areas we utilize this drop down?

**Comment by vincent99** [comment]
Once upon a time there was autocomplete, and it was good.

Then websites thought they didn't want to users to autofill forms because they want you to type your password confirmation without pasting or whatever, so they all started adding `autocomplete=off`.

Then browsers started ignoring `autocomplete=off`, because browser users still wanted autocomplete even when websites said no.

So the current arms race is that if you set it to something, but not "off", then it doesn't show up.

**Comment by davidnuzik** [comment]
@tfiduccia could you test to ensure autoComplete no longer shows up for you in searchable-select dropdown? I don't use autoComplete or have anything in my autoComplete cache...

I can then test a little further to ensure basic functionality of searchable-select works as expected.

**Comment by tfiduccia** [comment]
Version - master 8/7
Verified fixed
