### ISSUE TITLE
Show inactive nodes and unhealthy components in cluster list

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#21933]
Now there is no way to notice something is wrong inside a cluster.

We should show inactive nodes and unhealthy components in cluster list

![image](https://user-images.githubusercontent.com/21168270/62359440-6009b600-b549-11e9-8f07-34e8350ae3ad.png)
![image](https://user-images.githubusercontent.com/21168270/62359495-7f084800-b549-11e9-840d-94ad17579913.png)

cc @pengjiang80

**Comment by davidnuzik** [comment]
Version: master-head (8/5/19)

I tested this via three scenarios. Each covers each case "inactive nodes" and "unhealthy components" and the last ensures that when we have Auto Replace enabled, the messages in the UI will eventually go away when the nodes get replaced.

Setup:
Cluster with: 5 etcd nodes, 3 control plane nodes, 3 workers.
Auto Replace was NOT enabled (set to 0 minutes value) for the first two scenarios.

**Scenario 1 - Inactive Nodes:**

- Power down an etcd node.
UI shows etcd is unhealthy and a node inactive on list clusters page.
![image](https://user-images.githubusercontent.com/45179589/62485609-01735080-b772-11e9-8dca-6aa6400d77ba.png)

- Power down a control plane node.
UI shows control plane is not active
![image](https://user-images.githubusercontent.com/45179589/62485703-4e572700-b772-11e9-9391-a1d046e7765d.png)

- Power down a worker node.
UI shows worker node is not active
![image](https://user-images.githubusercontent.com/45179589/62485785-89595a80-b772-11e9-843b-b34a69f4e2b0.png)

- Bring nodes back up. UI updates and no longer shows UI warning triangle next to cluster name.
![image](https://user-images.githubusercontent.com/45179589/62485886-c45b8e00-b772-11e9-9723-fec61eb2024b.png)

**Scenario 2 - Make nodes unhealthy:**

- SSH into etcd node, and stop kubelet container.
UI shows etcd node is not active
![image](https://user-images.githubusercontent.com/45179589/62486183-6aa79380-b773-11e9-812d-a03e4a8759ee.png)

- SSH into control plane node, and stop kubelet container.
UI shows control plane node is not active
![image](https://user-images.githubusercontent.com/45179589/62486263-ab071180-b773-11e9-9654-c4e5002fcf55.png)

- SSH into worker node, and stop kubelet container.
UI shows worker node is not active
![image](https://user-images.githubusercontent.com/45179589/62486383-f9b4ab80-b773-11e9-8473-2f7dc61bd3ff.png)

**Scenario 3 - Make nodes inactive and unhealthy, but with Auto Replace enabled:**
The purpose of this test scenario is to basically test Scenario 1 and 2 again, but this time with Auto Replace of nodes enabled on the cluster. The UI should remove the warning message when nodes come back up to replace the old nodes.

- I tested again the first two scenarios. This time, the Auto Replace functionality eventually brings the nodes back up.
The UI warning message will go away when the new nodes come up without any issues.

**Sanity check:**
I did one last check as well. I ensured that if I delete nodes within rancher we still get our cluster states to update accordingly. This still works:
![image](https://user-images.githubusercontent.com/45179589/62486553-734c9980-b774-11e9-9d3d-6a7e916e1c03.png)
Otherwise, the cluster is still "Active" if it is healthy enough, as expected.
