### ISSUE TITLE
Update EKS AMI's for k8s 1.13, 1.12, 1.11

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#21992]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Need:**
We need to update EKS AMI's for k8s 1.13. These are found in eks_driver.go.

**Comment by davidnuzik** [comment]
Related: https://github.com/rancher/rancher/issues/21980

I can confirm the AMIs are updated now for k8s 1.13. I tested all three US regions; we cannot test all the available regions, but the PR looks good to me. The UI only lets us pick the latest k8s version, 1.13 so I could not validate other k8s versions as well.
_screenshot shows UI only allows 1.13_
![image](https://user-images.githubusercontent.com/45179589/62960751-30ac4200-bdb0-11e9-8181-b498045f65ef.png)

We see that the EKS worker nodes are the updated k8s version now (rather than old 1.10.x as seen previously)
![image](https://user-images.githubusercontent.com/45179589/62962016-d660b080-bdb2-11e9-9597-3c8393e0b47e.png)

I saw an issue specific to the us-east-2 region and this appears to probably be unrelated. As such I created a separate issue to track this: https://github.com/rancher/rancher/issues/22150
