### ISSUE TITLE
Allow DELETE of a registry in "active" state

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#220]
Version - V0.11.1

Option to delete a private registry that is in "Active" state is available on the API UI.
When deleting this registry , user is provided with "500 Internal Server Error"

Expected Behavior:
API UI should not expose "Delete" option for a private registry that is in "Active" state .

If user still attempts this action , we should be able to present a more meaningful error message.

HTTP Request:
HTTP/1.1 DELETE /v1/registries/1sp12
Host: 104.154.94.20:8080
Accept: application/json

HTTP Response:
HTTP/1.1 500
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-API-Schemas: http://104.154.94.20:8080/v1/schemas
Server: Jetty(8.1.11.v20130520)
X-API-Client-IP: 50.255.37.17
Content-Length: 176
Content-Type: application/json; charset=utf-8

{
"id": "0db8f021-ab33-4b52-8382-cec697e12530",
"type": "error",
"links": { },
"actions": { },
"status": 500,
"code": "Internal Server Error",
"message": "Internal Server Error",
"detail": null,
}

**Comment by vincent99** [comment]
The API UI does not know anything about Rancher specifically, it's a totally generic client implementing the [API Spec](http://github.com/rancherio/api-spec).

The spec has a way to specify which `actions` are available at the moment for a specific resource, and which `[resource]methods` are available for a resource type in general, but not which methods (`PUT` for editing and `DELETE` to remove) are availbale for a specific resource at this moment.

The Rancher UI currently takes advantage of a side-effect in the API server that causes `update` and `remove` to be exposed as `actions` to decide when to show Edit and Delete buttons, but the API UI can't do that (and be generic).

Separately, we should change the API so that the DELETE just always works.  Having to deactivate things before deleting is a pointless extra step for the user to click through.

**Comment by vincent99** [comment]
Also if it is not allowed, it should return 405 Method Not Allowed, not a 500.  @hibooboo2 ?

**Comment by hibooboo2** [comment]
Current behavior says method not allowed. 405.

**Comment by sangeethah** [comment]
Tested with build from master - Nov 19
Option to delete a private registry that is in "Active" state is available on the API UI.
But now when deleting this registry , user is presented with error message -  "Method not allowed"

```
{
"id": "95e03ab9-9723-4720-bb93-d0c53c9b776b",
"type": "error",
"links": { },
"actions": { },
"status": 405,
"code": "Method not allowed",
"message": "Method not allowed",
"detail": null,
}
```
