### ISSUE TITLE
Undeletable containers

### ISSUE THREAD

**Issue by moimael** [rancher/rancher#2203]
Sometimes containers cannot be deleted via UI (for whatever reasons), so in those case I often remove the container by hand directly with a docker rm.
The problem is that the UI do not seems to pick up the change and I must remove every trace of the instance in the rancher mysql (which takes like 10 sql requests...).

How about checking if the container is still present and removing rancher metadata from db if not ?

**Comment by cusspvz** [comment]
I'm facing it atm. Version: `v0.40.0-rc1`

**Comment by deniseschannon** [comment]
Can you provide more details on why it can't be deleted in the UI? What happens when you select "Delete" from the drop down? 

What kind of container is it? Is it part of a service? Sometimes a service could be in "Active" state in Rancher even though it should be in "removed" because the UI no longer shows it. So Rancher might be spinning up another container to replace that one.

**Comment by cusspvz** [comment]
Before asking your questions, this happened to me on a single host. Every container Scheduled into that host, become into "Networking" state. After trying to upgrade related Stack, it broken on deleting state ("In process"). Tried to restart host. I had to remove it since i wasn't able to access it. (downloaded docker-machine configs didn't worked aswell).

Now relevant QA:

> What kind of container is it?

All of them, with exception of Network Agent.

> Is it part of a service?

Yup

> Sometimes a service could be in "Active" state in Rancher even though it should be in "removed" because the UI no longer shows it.

They weren't active, couldn't ping them from other hosts but i was able to ping Network Agent.

> So Rancher might be spinning up another container to replace that one.

Didn't happened.

**Comment by deniseschannon** [comment]
@cusspvz It sounds like you were having issues connecting to your hosts, which might be why Rancher was unable to connect to your host. When you tried to ssh in using your docker-machine configs, did you use this command? @aruneli was able to access his machine using this command using v0.40.0-rc2

```
ssh -i id_rsa ubuntu@ip_of_machine
```

**Comment by cusspvz** [comment]
@deniseschannon actually i wasn't able to connect to my host because configs provided by rancher didn't provided some of the assets needed. I also had to change paths on host config file.

**Comment by deniseschannon** [comment]
@cusspvz What additional assets did you need? We have always been able to access any machine created through the UI using the id_rsa key in the machine configs. 

Was this also the host that had issues with deleting containers or the one that you had issues with purging from your environment? I know you're swapping out hosts all the time, but if it's all the same host it sounds like somewhere along the way, the way Rancher was able to communicate with the host was changed. Maybe something on the Azure side?

**Comment by cusspvz** [comment]
Could you please specify the procedure you use? I was able to communicate over docker protocol already (by changing paths from the downloaded config and using `docker-machine env`) but not over `docker-machine ssh`.

**Comment by deniseschannon** [comment]
Here's the docs that illustrate what I've done. http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/#accessing-hosts-from-the-cloud-providers

I don't use the `docker-machine ssh` to get entry into the host.

**Comment by cusspvz** [comment]
cc @fernandoneto

**Comment by deniseschannon** [comment]
@cusspvz I'm thinking this is related to your reconnecting issues with the agent. 

https://github.com/rancher/rancher/issues/2196

I'm going to close this in favor of the other issue. 

If you are still having this issue, please re-open.
