### ISSUE TITLE
[ui] Support GKE regional or zonal clusters

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#22045]
**What kind of request is this (question/bug/enhancement/feature request):**
Rancher should be able to create zonal and regional GKE clusters. 

**Steps to reproduce (least amount of steps as possible):**
1. Create a GKE cluster
2. Choose region or zone (exclusive or) 

**Result:**
<img width="149" alt="Screen Shot 2019-08-07 at 3 43 59 PM" src="https://user-images.githubusercontent.com/31839142/62662948-a0db4380-b92a-11e9-94ee-35cb059eb562.png">

**Other details that may be helpful:**
From GKE: 
 A regional cluster provides a single static endpoint for the entire cluster, enabling you to access the cluster's control plane regardless of any outage or downtime in an individual zone. https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters?hl=en_US
Location type is permanent 

GKE regions: https://cloud.google.com/compute/docs/regions-zones/
Address issue: https://github.com/rancher/rancher/issues/17099

**Comment by daxmc99** [comment]
This may require another authed handler to GET gke regions https://github.com/rancher/rancher/blob/4f3943c624f01b96106095c8a19d8ebcc1bb771a/server/server.go#L118

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/16/19)

**Summary:**
This change adds a new option when launching a GKE cluster in the Rancher UI.
It allows us to pick if we want to configure our GKE cluster in a zonal manner or regional manner.

Previously, we could only configure via zones. If we wanted to cover a whole region, you would basically pick your zone, and ALL additional zones.

**NOTE:** for all my tests I only chose 1 small worker node. This is because the more zones you pick the more worker nodes are created and makes it easier to count. That is to say, your specification of the count of worker nodes is per zone. When you pick a region you get your one worker in each zone for the region.

The change adds a "Location Type" option where the user can choose either Zonal or Regional. The dropdown (and additional zones when using zonal type) were moved to the right in the form.
![image](https://user-images.githubusercontent.com/45179589/63199438-b50df780-c032-11e9-8d84-ba3f8ef34741.png)
The screenshot above shows the default values.

**Test zones scenario:**
I ensured that when I chose the default zonal type, and switch zones in the zone dropdown, the Additional Zones section still behaves as expected (it only shows the remaining zones for the region). This is still working correctly just as it was before the change. I tested with various zones, and added additional zones to ensure this works correctly both in the rancher HTTP/API and in the Google Platform web console. I spot checked various zones and additional zones. I ensured that I had my one worker in each zone chosen.

**Test regions scenario:**
Last, I tried the new option to pick regions ("Regional"). When you pick this the form changes to just show a dropdown now of the various regions.
![image](https://user-images.githubusercontent.com/45179589/63199536-fb635680-c032-11e9-8ffd-1b35a8bbc174.png)
The screenshot above shows the default value when switching to "Regional"

I again ensured that the rancher HTTP/API appear correct as well as the Google Platform web console. All the various options worked as expected. I spot checked various regions. I ensured that for each region I get the expected count of workers (1 worker per zone in my case). So for example, when I pick the us-west-2 region, I get 3 worker nodes (since I chose 1 worker node, you get 1 per zone).

**API/HTTP:**

When you send a request to use a region, "region" is sent in the googleKubernetesEngineConfig.
`region: "us-west2"` (default when chose Regional in UI)
location: is not sent at all (this is expected).
zone: is null (this is expected)

When you send a request to use a zone or zones (pick additional zones in the UI), "zone" is sent as well as "locations" when additional zones are chosen. (This is expected).
region: is null (this is expected)
(here is an example where I picked us-east-4-a and in the UI chose us-east-4-c as my additional zone)
```
locations: ["us-east4-c", "us-east4-a"]
  0: "us-east4-c"
  1: "us-east4-a"
```
```
zone: "us-east4-a"
```

**Conclusion:**
During my various spot checks with different regions and zones, I wasn't able to identify any issues. HTTP/API/UI all look good, and my GKE cluster config was confirmed by checking the Google Cloud Platform web UI (i.e. ensure in proper zone(s)/region). In each scenario I got the expected count of worker nodes per my spec for zone(s)/region.
