### ISSUE TITLE
[UI] Inconsistency with "Edit as YAML" view

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22103]
Version: master-head (v2.3) (8/9/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

Today, we have the "Edit as YAML" view in some places in the UI such as for catalogs and logging (just a couple of examples).

It would be nice if this was more consistent. Just about everywhere we have a "View/Edit YAML" action we should probably have an "Edit as YAML" button available as well when editing an object in the UI. There may be a few exceptions where this would not make sense.

The point is that we should expand this into other areas in the UI in order to be more consistent. The possible trade off is risk of converting from YAML back to form and back and forth without any issues.

**Comment by vincent99** [comment]
The `View/Edit YAML` action on native cluster/project k8s resources is a very generic thing outside of the normal edit flow that goes straight to the k8s API to get YAML for some resource and PUTs it back for k8s to deal with applying on save.

The "Edit as YAML" in cluster create/edit is a very custom thing to take the cluster you're looking at and manipulate a portion of its (JSON) definition in the API with a YAML editor, so that changes made there are reflected when you go back to the form view or post to the Rancher API.  This is not really generalizable and would require dev and (ongoing) testing for every type it's added to.

**Comment by tfiduccia** [comment]
@bmdepesa - unless there is a specific place you would like to see it changed, can you please close?
