### ISSUE TITLE
[UI] EKS - Kubernets Version is set to "v1.10 (unsupported)" by default after you create your first eks cluster

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22149]
Version: master-head (8/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create an EKS cluster, use the latest k8s version
- Create a second EKS cluster

**Result:**
For some reason the second or any other future EKS clusters we create -- the k8s version is set to v1.10 now by default:
![image](https://user-images.githubusercontent.com/45179589/62958132-f1c7bd80-bdaa-11e9-926b-c9bf05f7caa3.png)

You must manually change this to a supported k8s version.

**Other details that may be helpful:**
No JS errors, etc. Just appears to be a glitch in the UI.

**Comment by loganhz** [comment]
cannot reproduce this issue.

**Comment by davidnuzik** [comment]
It looks like some recent change fixed this. Now I just see odd drop down. What do templates have to do with hosted providers?

![image](https://user-images.githubusercontent.com/45179589/63039915-2f931780-be79-11e9-9ae5-5c3bd3092028.png)

**Comment by loganhz** [comment]
CT only works for rke clusters.

**Comment by vincent99** [comment]
The `{{form-versions}}` component is used for both clusters and templates, and the `unsupported` message was apparently overloaded to have 2 meanings so when I changed it for templates it affected regular clusters.

If adding/editing a regular cluster it should say `(unsupported)` when the version is outside of the supported range (as defined in the setting).

If editing a cluster created from a template(with kubernetesVersion="1.14.x" for example), and kubernetesVersion is not overridable, then it should say "(not allowed by template)" on versions that are not 1.14.x since you're not allowed to pick them.

**Comment by davidnuzik** [comment]
I wasn't able to determine the reasoning why I see this in the drop down (I suppose what Vincent mentioned helps?) I still see this even when I have zero cluster templates.

![image](https://user-images.githubusercontent.com/45179589/63133401-f098bb00-bf79-11e9-92dc-3120baf10f48.png)

However, since the root issue is not longer happening (I can't reproduce anymore) I am closing the issue an opening a new one to continue the discussion. New issue: https://github.com/rancher/rancher/issues/22216
