### ISSUE TITLE
Disable automatic creation of monitoring CRDs on new clusters.

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#22171]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

A customer would like to use their own/our library prometheus charts, but the following CRDs are conflicting with the charts, making them not work.

alertmanagers.monitoring.coreos.com 
podmonitors.monitoring.coreos.com 
prometheuses.monitoring.coreos.com 
prometheusrules.monitoring.coreos.com 
servicemonitors.monitoring.coreos.com

It would be beneficial to create these CRDs only as needed when features are enabled by the user instead of when the cluster is created.

**Comment by doug-ba** [comment]
This feels much more like a bug than an enhancement.  If a cluster creator does not enable the built-in monitoring, it feels like it's wrong to install these CRDs. 

This causes custom Prometheus-operator installs to require removing the existing CRDs we didn't ask for in order to replace them with the appropriate versions for our release.

Why this is a problem for me:

I'm currently working on a workflow for kube cluster provisioning and bootstrapping using terraform and terragrunt to eventually be triggered by some pretty CI gui.  These CRDs existing are the only thing stopping this workflow from being 100% automated without something gross like a local-exec or a one-off "go kubectl delete these things" step.

**Comment by doug-ba** [comment]
For anybody who finds this in a search, for the specific use case of using terraform and the helm provider, I came up with this workaround which seems to do what I'm looking for.  I'd prefer not needing to use a local-exec, but am ok with it as a short term workaround.  The local.host and local.token variables are extracted from the kubeconfig generated by the rancher2_cluster resource (I put that in vault in that module).  I make no warranties about this working for your things:
```resource "null_resource" "clean_up_crds" {
  triggers = {
    cluster_id = data.rancher2_cluster.custom_cluster.id
  }
  provisioner "local-exec" {
    command = "kubectl -s=$HOST --token=$TOKEN --insecure-skip-tls-verify delete crds alertmanagers.monitoring.coreos.com podmonitors.monitoring.coreos.com prometheuses.monitoring.coreos.com prometheusrules.monitoring.coreos.com servicemonitors.monitoring.coreos.com || true"
    environment = {
      HOST  = local.host
      TOKEN = local.token
    }
  }
}```

**Comment by aiyengar2** [comment]
@doug-ba while I hear your concerns that it would be ideal if Rancher `create[d] these CRDs only as needed when features are enabled by the user instead of when the cluster is created`, a workaround for this constraint that is currently being used by Monitoring V2 (which installs a different set of CRDs than are currently installed by the Rancher cluster) is to use our rancher-monitoring-crd Helm chart.

You can find the logic for how we configured something very similar to your script in https://github.com/rancher/charts/tree/release-v2.5/charts/rancher-monitoring/rancher-monitoring-crd/14.5.100, and I think you should be able to fork this chart and replace the contents of the `crd-manifest` directory with the versions of the CRDs you actually want installed on the cluster.

This would provide a Helm-based workaround for your current issue that will "assume ownership" of CRDs within the cluster; therefore, if you replace the contents of crd-manifest and redeploy, the new CRDs will be used. If you delete the CRD chart, the CRDs in the cluster should also be deleted.

**Comment by athulg93** [comment]
Does anyone know how to handle this issue or is it resolved?
