### ISSUE TITLE
[UI] Change styling of Provider column on /g/clusters page so that it's always same size text

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22180]
Version: v2.2.7 (pre-existing issue)
Version: master-head (v2.3) (8/14/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster of any type
- Watch it from the global /g/clusters page as it provisions then becomes active, watch the Provider column

**Result:**
The text will change size from large to smaller text once the cluster is up and we have info for the k8s version.
We would like to have the text always stay the smaller size whether or not we have k8s version info yet so that things don't look odd in the UI when some clusters are not active yet.

Example screenshot shows the selected clusters are still coming up and so we don't have k8s version... Notice how big the font is. I think we just need to tweak styling to force certain font size.
![image](https://user-images.githubusercontent.com/45179589/63054343-852aec80-be98-11e9-940d-86b89045dad8.png)

**Comment by tfiduccia** [comment]
@deniseschannon - I'm going to go ahead and push this until our overall redesign.  I think what we will be fine until then.

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by aaronRancher** [comment]
This bug is reproduced with Rancher server `rancher\rancher:v2.3-head`
Steps:
Create a cluster
Watch it from the global /g/clusters page as it provisions then becomes active, watch the Provider column
![Screen Shot 2019-11-21 at 10 28 26 AM](https://user-images.githubusercontent.com/57409052/69362891-9d0acd00-0c4c-11ea-921b-25e9dc7fccee.png)

The bug fix is validated in Rancher server `rancher\rancher:master-head` `version 276702446`
![Screen Shot 2019-11-21 at 9 06 28 AM](https://user-images.githubusercontent.com/57409052/69362933-b3b12400-0c4c-11ea-9498-ea4e1679d5c9.png)
