### ISSUE TITLE
[UI] Cluster Templates - Show an information tip while sharing a clustertemplate with "Owner" Access Type

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#22201]
While sharing a clustertemplate with a specific user/group, the clustertemplate creator can assign "Owner" accessType to the user/group being shared with.

"Owner" accessType implies that the user should be able to manage the clustertemplate that includes ability to create new revisions, edit and delete existing revisions and the  clustertemplate.
But if the user does not have the global role "Create Cluster Templates", they cannot create new revisions even if they have been granted the "Owner" accessType. Thus the global role is a pre-requisite.

We should show the below information tip on the "Share Template" screen - when someone is sharing the template with a user with "Owner" accessType:

"When assigning an *Owner*, the user must have the `Create Cluster Templates` global role in order to create new revisions. These permissions can be granted by an administrator."

<img width="1377" alt="Screen Shot 2019-08-15 at 12 07 23 PM" src="https://user-images.githubusercontent.com/1470602/63119561-4870fb00-bf55-11e9-90a7-f20d52da2b7c.png">

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/16/19) (`196033ccf`)

I'm not seeing any change when I create a cluster template and add an owner member in the UI. There is no pop-up, or helper text, or tooltip, etc.

If I log in as the "owner" user too without any Create Cluster Template access and try to clone a CTR I don't see anything either. I just get the option to try this and click "Create" button and nothing happens in the UI.

**Comment by loganhz** [comment]
@vincent99  it looks like the last commit in UI is not in `https://releases.rancher.com/ui/latest2/index.html`
The build looks good. Not sure why

`https://github.com/rancher/ui/commit/2636b77d279f5d5200169a6ef20a132c7dad74bb`

**Comment by vincent99** [comment]
I guess I need to wait longer between merging PRs, with multiple drone nodes writing to one CDN location the last uploaded in isn't necessarily the newest merge.  Re-pushed it, try again now.

**Comment by loganhz** [comment]
@vincent99 thanks! fixed!

**Comment by davidnuzik** [comment]
Thanks guys.

Version: master-head (v2.3) (8/19/2019)

I can now confirm, that when you are creating a cluster template and add an entry with Access Type of Owner a blue info ribbon immediately pops up explaining that the owner user must have the "Create Cluster Templates" global role (in order to create new revisions).

Screenshot:
![image](https://user-images.githubusercontent.com/45179589/63281763-4616e580-c262-11e9-99cb-1ebe6e0dbcfe.png)

This seems to work without any issues. I tried this as non-admin too (but has create cluster templates permission) and a non-admin user will also see this ribbon as well.
