### ISSUE TITLE
Backport: User role selection not taking effect 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#22260]
https://github.com/rancher/rancher/issues/19640

**Comment by deniseschannon** [comment]
Available in UI: 2.2.94

**Comment by davidnuzik** [comment]
**Reproduction:**
v2.2.7

1. Log into Rancher v2.2.7 as admin
2. Click on Add User. Enter Username, Password. Select global Permissions - Custom.
3. Select individual permissions by clicking on the text (example: Click on text `Create Clusters` to select the permission. (Do not click on the checkbox to select)
4. Clicking on the text, selects the checkbox.
5. Click on Create.

**Expected Result:**
Permissions should be set for the user.

**Actual Result:**
Permissions are not set for the user. Can be tested when you select the user created, and click on `Edit User`. Permissions which you selected in Step 3, will not be selected for the user.
You can also see there is no POST to /v3/globalrolebinding for the "clusters-create" globalRoleId

**Note:**
Try creating another user, and this time actually pick the checkbox. The user has the proper "Create Clusters" permission now (the second POST to globalrolebinding included the "clusters-create" globalRoleId
This proves that the issue was a UI issue.

**Validation:**
v2.2.-head (8/18/19) (`a6c23c95`) (with ui-index 2.2.94 set)

Execute the same steps as outlined above in the Reproduction section.

**Result:**
Now permissions are properly set for the user.
We see BOTH of the POSTs to /v3/globalrolebinding go through. The standard one for "user-base" globalRoleId and the second one for "clusters-create" globalRoleId.
When I edit the user I see that "Create Clusters" is checked now.
When I check the API for the user I can confirm it has the "clusters-create" and "user-base" roles. (i.e. query globalRoleBindings with my userId like /v3/globalRoleBindings?userId=u-smqvv)

**Comment by davidnuzik** [comment]
_Additional checks for cluster and project membership and another quick check at global level as well_

Version: v2.2.8-rc3

- Ensure works at cluster level permission (click on text, not checkbox, create user and then edit to ensure the setting took, check API)
![image](https://user-images.githubusercontent.com/45179589/63302292-98232f80-c291-11e9-80f8-8b21eb7be7fe.png)

- Ensure works at project level permission (same steps as cluster level)
![image](https://user-images.githubusercontent.com/45179589/63302355-bdb03900-c291-11e9-8171-5873f6e58032.png)

Confirmed these both worked without any issues.

- Re-test global-level permission (sanity check in RC).

This too works without any issues.

For each area I ensured that this worked correctly in the UI and the API.
