### ISSUE TITLE
Catalog apps should not re-use existing image and tag if the version is upgraded

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#22265]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Catalog apps should not re-use the existing image and tag if the app version is upgraded.
1. select the Drone app with app version 1.4.0 and the existing image tag would be `0.8.5`
2. upgrade to v1.7.4 and the default image tag would be `0.8.6`, but because there are a default image and image.tag value so the app will still using `0.8.5` image.

**Result:**
need to upgrade to a newer version of the image and image.tag even if there is a default value in the answers.

**Comment by izaac** [comment]
Rancher version: master-head (v2.3) (08/22/2019)

Some Catalog apps doesn't update the image tag between App versions. Drone uses a new tag between App versions and is now working fine.

Another example is **dask**, Installing App 2.0.0 it uses image tag 1.0.0. And upgrading the App to 3.0.0 also upgrades the tag to 1.1.5.

The docker-registry App however if you install 1.4.3 and then make the upgrade to 1.6.1 both has the same image tag 2.6.2.

I don't think we don't have control for the image tag unless the App version explicitly use a new image tag.

But right now when the App version upgrades the the new version has a new image tag is used instead of reusing an existing while I was doing this validation.
