### ISSUE TITLE
[UI] Azure nodeTemplate displaying wrong value for managed/unmanaged disk

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#22276]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create azure nodetemplate with disk type set to "Managed Disk"
2. view the create nodetemplate

**Result:**
Disk type is displayed as unmanaged disk in UI
Disk type is displayed correctly as being managed when viewed via kubectl

**Other details that may be helpful:**
value should reflect the vlaue for the nodetemplate

**Comment by davidnuzik** [comment]
Note: I'm not able to reproduce because we just recently added the option to pick managed/unmanaged in the nodeTemplate UI modal (Disk Type field)

Version: master-head (v2.3) (8/20/19)

- Create an Azure node template and under the Instance pane, pick "Managed Disk" for Disk Type.
![image](https://user-images.githubusercontent.com/45179589/63378370-f78f4700-c346-11e9-9a9c-1525a9901f3c.png)
- View the Template, notice our setting took now; it's indeed "Managed"
- View in the API and doubly confirm this.

We see `managedDisks: true` when check browser client http or the API.

Confirmed that in the Azure web console the disk is indeed the Managed type.
![image](https://user-images.githubusercontent.com/45179589/63378810-dbd87080-c347-11e9-9645-1156efae2407.png)
