### ISSUE TITLE
UI - Bump Azure default Ubuntu image - fix placeholder text

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#22272]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Description**
We've updated the default ubuntu image for azure, the UI already reflects that, but we still need to change placeholder text: https://github.com/rancher/ui/blob/041b384986384cd291d41b90eebcf4fe203f6ea9/translations/en-us.yaml#L7031

**Related tickets**
Backend Issue: https://github.com/rancher/rancher/issues/21207

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/20/19)

The fix is only covering Azure AKS (we actually don't even use ...clusterNew.azureaks.image.placeholder ) We need this in for the key pictured below too for Azure RKE nodeTemplate modal.

![image](https://user-images.githubusercontent.com/45179589/63365379-64e1ae80-c32c-11e9-959e-1d0d83be3887.png)

This is the key that needs to be fixed:
![image](https://user-images.githubusercontent.com/45179589/63365405-6f03ad00-c32c-11e9-8aac-29ca6327ab8f.png)

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (8/21/19)

I can now confirm the correct placeholder text was updated accordingly:

![image](https://user-images.githubusercontent.com/45179589/63475479-dce5cc80-c431-11e9-8ff4-c9012260316e.png)
