### ISSUE TITLE
Scheduling based on resource requirements. 

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2228]
I know the Rancher documentation clearly states that scheduling based on host resources is not supported.

Here's the feature as described in the Rancher docs: 
Swarm’s filter tries to provide an available host that fulfills various resource requirements for the container. For example: $ docker run -ti -m 300M ubuntu:14.04 /bin/bash specifies to run on a host that has a minimum of 300MB.

If you don't have some kind of resource-based constraint, I'll have to add tooling to check my hosts to be sure the are not bogged down. I'd rather have Rancher just fail to deploy a container or stack if their are no hosts with sufficient resources.

Is this feature on your road map?

**Comment by ibuildthecloud** [comment]
Resource based scheduling is for sure on our roadmap but I just want to point out the oddities of it.  Most people don't put memory limits on every container.  The immediate problem you run into is that if you want to put a memory limit on something and have it scheduled, then you must also do that for every single container.  If you don't have a memory limit on a container you have to assume it is 0 and then it is able to fit on every host.  

This user experience is non-intuitive for us.  We haven't figured out yet what is the best way to present this to users.

**Comment by kaos** [comment]
How about having "virtual" dynamic memory limits for containers that doesn't have a fixed limit set. What I mean by that is for rancher to pretend that a fixed limit was set to the highest memory usage seen (on average over some time, perhaps, to avoid short spikes to drive it up too high) - ought to give reasonable behavior.

**Comment by vincent99** [comment]
That seems somewhat workable, given https://github.com/rancher/rancher/issues/48...

**Comment by eebjr** [comment]
I posted this on the rancher forum, so I'll share here also. I think giving Rancher hints for resource scheduling could be relatively simple. 

For example, if I could assign  a number of tokens to a host, then I could assign my containers a number of tokens.  Rancher could easily calculate whether a given host had enough available tokens for a given container or stack. So if I assigned a host 10 tokens, I could run two containers that consume 5 tokens each, or one stack that consumes 10 tokens. This example is just to illustrate how simple the scheduling hints could be, in my opinion. Trying to use actual system metrics could become very complex for users and for the Rancher code.

**Comment by ibuildthecloud** [comment]
@eebjr interesting enough this is exactly how the default scheduling works in rancher.  We just don't allow users to tweak it.  When a host is added it gets X compute.  When a container is scheduled we subtract the compute of the container from the host.  Since we don't let the user select the compute values they default to 10000 for the host and 1 for each container.  Effectively this is how we spread containers based off of the number of containers.  We find the host with the most compute available.

But if this seems like a useful model we can expose changing the compute values.  Then you effectively get your token model.

**Comment by eebjr** [comment]
@ibuildthecloud, I would also need to set expected compute consumption of my containers in the rancher-compose.yml. The expected consumption of a stack would just be the total of the compute consumption of it's containers.

**Comment by demarant** [comment]
+1
I like the idea of assigning tokens to containers and to the hosts. It seems simple and powerful enough for most use cases....
However, I see two issues to think on this: 

- what to do when containers change their footprint over time ... the token does not change automatically and it may not reflect the actual resource needs. But I guess this is a responsibility of the people deploying the stacks to update the tokens (will this mean an upgrade and re-scheduling?)
- tokens give by different Stacks may not be comparable ... will one token given in Stack A be the same as one token in Stack B? How do we know what a token actually represent .. it can be easily missused.

So I still think, in order to be transparent to docker, the best is to use the actual cpu/memory limits set in docker-compose file. When users do not use it, than the Stack is not deployable in the environment that has such advanced resource-based scheduling enabled. Maybe we could have some sane defaults to enforce it via the generated docker-compose,yml from the Stack page.

**Comment by eebjr** [comment]
putting the token values in the docker-compose.yml does seem like a good idea. Then one could easily tweak the values based on the deployment scenario or environment.

**Comment by demarant** [comment]
I like only put mem/cpu, that is the correct approach. Those are absolute resource values. I don't like to go around and change virtual tokens...

**Comment by taketnoi** [comment]
+1

**Comment by CBR09** [comment]
+1 for this

**Comment by RXminuS** [comment]
Just an idea, why not make host-labels variable based on aggregate container labels?

For instance I have 1 host with mem=$(4) and if that host has two containers with mem=$(1) and mem=$(2) then (leaving host mem at 1) then it can't host another container with mem>1.

That way we don't hardcode what a resource is defined as (cup/mem) and allows users to easily define their own resource allocation strategy. all that rancher has to do is compute the sum of container labels and check that host label stays above 0.

**Comment by bdentino** [comment]
Is there currently any workaround for this? I'm less concerned about scheduling based on resources requested by an individual container as much as simply adjusting the available compute per host. For example, if I have a non-homogeneous environment where half of my servers have 2 CPU and the other half have 4 CPU, is there any way (official or hacked) to tell rancher to put 2 containers on the 4-cpu instances for every 1 on the 2-cpu instances?

**Comment by deniseschannon** [comment]
No, the level of the scheduling that you're requesting does not exist today.

**Comment by pschrammel** [comment]
I think the tokens represent resource dimensions (cpu, memory, gpu ....). rancher has "only" to do a multidimensional optimization.  https://jeromeloisel.com/2016/01/22/scheduling-docker-container-cluster/ (binpack problem).

**Comment by ibrokethecloud** [comment]
I seem to be reaching a point where I may have a use case for this as well.

**Comment by cjellick** [comment]
Implementation details in https://github.com/rancher/rancher/issues/2228

**Comment by kaos** [comment]
@cjellick You referenced this issue, in this issue.. typo?

**Comment by sangeethah** [comment]
@koas, yes , Implementation details can be found here - https://github.com/rancher/rancher/issues/5264.

@eebjr , this feature will available in 1.2 release . Implementation details and testing done so far is tracked in https://github.com/rancher/rancher/issues/5264.

**Comment by kaos** [comment]
@sangeethah thanks :)
