### ISSUE TITLE
Global Rolebindings can become stuck on cluster removal

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#22281]
What kind of request is this (question/bug/enhancement/feature request):
bug

Steps to reproduce (least amount of steps as possible):

1. Create a global admin
2. Create a cluster
3. Wait for cluster to be active / steady-state
4. Delete cluster
5. Try remove privileges from them
6. Privileges reset to admin every time

Result:
Stuck global admins

**Comment by daxmc99** [comment]
PR here https://github.com/rancher/rancher/pull/22241

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher:v2.2.7

Steps:
- as the default admin, enable Github Auth
- open another browser to log in as Github user `rancherdev`
- as the default admin, go to the `Users` page to change rancherdev's role to `Administrator`
- change rancherdev's role back to `Standard User`  -> the change takes effect
- change rancherdev's role to `Administrator` again
- as rancherdev, create a cluster
- wait for the cluster to be active
- as the default admin, delete the cluster
- as the default admin, go to the `Users` page to change rancherdev's role to `custom` like the below screenshot shows

<img width="937" alt="Screen Shot 2019-08-16 at 10 07 53 AM" src="https://user-images.githubusercontent.com/6218999/63185943-0bb60a00-c010-11e9-9571-ae702cb393a1.png">

- save and refresh the page 

Result:
- rancherdev's role is reset to `Administrator`
- log in as rancherdev, confirm that rancherdev still have the admin permission

<img width="723" alt="Screen Shot 2019-08-16 at 10 25 45 AM" src="https://user-images.githubusercontent.com/6218999/63186020-399b4e80-c010-11e9-9fbd-9a88836a3dd3.png">

**Comment by jiaqiluo** [comment]
The bug is partially fixed in v2.2-head.  a6c23c95

Following the same steps as my previous comment says, and this time the role is changed successfully.
