### ISSUE TITLE
I want to do remote builds, but I don't have s3

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2229]
Any plans to support an open source data store for doing Docker image builds with Rancher?

**Comment by vincent99** [comment]
You can specify a http/git URL instead of `build: .`, which might help you.  When using `build: .` the build context has to be uploaded somewhere so the host can get it.

There exist many S3-compatible object stores, both commercial alternatives to AWS and free install yourself open-source (Eucalyptus, OpenStack Swift, Riak CS, ...).

It appears we lack an option to change the base URL for the S3 client besides the region though, @ibuildthecloud.

**Comment by justsml** [comment]
Has this been added? 

Is everyone an AWS/S3 customer? 
Did I miss a memo along the way? 

I might be able to add it, I'd like to score some Go OSS contribs ;)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
