### ISSUE TITLE
[UI] Add ap-east-1 to eks regions

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#22339]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
go to create an eks cluster

**Result:**
ap-east-1 is not provided as an option but is now supported by api.

Backend PR:
https://github.com/rancher/kontainer-engine/pull/182

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/3/19)

I can confirm ap-east-1 region has been added as an option for the Region for an EKS cluster in the UI now.
![image](https://user-images.githubusercontent.com/45179589/64207579-c1c38580-ce51-11e9-8b09-f76e6c85f5c8.png)

API calls are sent to the correct ap-east-1 region. Although I am only able to test the api call to check credentials due to regions we are constrained to.
