### ISSUE TITLE
Add Custom CA to agent when SSL'ing Server?

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher#2237]
Is there a way to add a custom CA to the agent when connect to a server? 
The error we are seeing is 
"Unable to create EventRouter" Err= "Get https://redacted/v1:x509: certificate signed by unknown authority"

We would like to be able to pass in a custom CA for the agent to use?

**Comment by clemenko** [comment]
Is this possible?

**Comment by deniseschannon** [comment]
Currently this is not possible.

**Comment by clemenko** [comment]
Feature request! It makes using SSL on an air gapped network impossible.

**Comment by ibuildthecloud** [comment]
@clemenko The short of it is that you need your custom CA in `/etc/ssl/certs/ca-certificates.crt` in the rancher/agent image which we don't make easy to customize.  If you are already doing air gap then you are already going through the hassle of configuring a custom image name for rancher/agent, I assume.  For work around you can create your own rancher/agent image like below (not tested, just spit balling here)

```
FROM rancher/agent:v0.8.2
COPY my-ca.pem /tmp
RUN cat /tmp/my-ca.pem >> /etc/ssl/certs/ca-certificates.crt
```

**Comment by clemenko** [comment]
Good idea thanks!

**Comment by smaccona** [comment]
We had to do some additional stuff to get this to work properly, and we ended up with our own builds of both `rancher/server` and `rancher/agent`. Here's our "recipe" in case anyone else is having issues.

For the agent, it was not enough to append our certificate to `/etc/ssl/certs/ca-certificates.crt` - we additionally had to run `update-ca-certificates` for it to be recognized by `curl`. On top of that, the Python `requests` and `websocket` packages have their own `cacert` files and don't use the OS-installed one, so we need to update those files too.

Our custom agent `Dockerfile` looks like this (where `ca.crt` is your custom CA root certificate):
```
FROM docker.io/rancher/agent:v0.8.2
COPY ca.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates && \
    cat /usr/local/share/ca-certificates/ca.crt >>/usr/local/lib/python2.7/dist-packages/requests/cacert.pem; && \
    cat /usr/local/share/ca-certificates/ca.crt >>/usr/local/lib/python2.7/dist-packages/websocket/cacert.pem
```

Then when we build it, we have to make sure the image has the same name as the current `rancher/agent` image, otherwise when you run the agent on your host it will "update" to the stock one and you will lose your certificate changes:

```bash
$ sudo docker build -t rancher/agent:v0.8.2 .
Sending build context to Docker daemon 970.2 kB
Sending build context to Docker daemon 
Step 0 : FROM docker.io/rancher/agent:v0.8.2
 ---> 11539df40565
Step 1 : COPY ca.crt /usr/local/share/ca-certificates/
 ---> dba8944dc5b3
Removing intermediate container 5da927884408
Step 2 : RUN update-ca-certificates &&     cat /usr/local/share/ca-certificates/ca.crt >>/usr/local/lib/python2.7/dist-packages/requests/cacert.pem &&     cat /usr/local/share/ca-certificates/ca.crt >>/usr/local/lib/python2.7/dist-packages/websocket/cacert.pem
 ---> Running in 4020d265062b
Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
 ---> 9db13c8e3b70
Removing intermediate container 4020d265062b
Successfully built 9db13c8e3b70
```

We also made our own build of `rancher/server`. There are two issues here - first, the server also needs a copy of our CA certificate, otherwise it can't talk to itself via SSL properly. This has been addressed in https://github.com/ibuildthecloud/rancher/commit/c92da0ea5c4c21ea8e5e5902f8464e8d7ca210ad, which looks for `ca.crt` in the root of the docker container and adds it to the `ca-certificates` database in a similar fashion to what we used above. So we copy our CA cert to `/ca.crt` in our `Dockerfile`.

The second issue is that the agent downloads Python agent code from the Rancher server on the fly. Although this no longer comes from the CDN and is hosted locally on the Rancher server, it still has the same `cacert.pem` issues we had with the Python `requests` and `websocket` packages above. To get around this issue, we made a small shell script that does the following:
- Navigates to the directory on the server container which hosts the downloadable files
- untars the `python-agent.tar.gz` file in situ
- adds our CA cert into all `cacert.pem` files it finds in the archive's tree
- updates the SHA1 checksums in the root of the archive
- re-tars the whole thing, replacing the original `python-agent.tar.gz`

This is a pretty ugly hack and currently needs to be manually run after the server starts and before you try to register any hosts (we use `docker exec` for this - see below for details).

Here's our `rancher/server` `Dockerfile`:

```
FROM docker.io/rancher/server
COPY ca.crt update-python-cacert.sh /
```
And here's `update-python-cacert.sh`:
```bash
#!/bin/bash
cd /usr/share/cattle/artifacts
tar zxf python-agent.tar.gz
ARC_DIR=`find . -name cacert.pem -exec sh -c "echo {} | cut -d '/' -f2" \; | uniq`
find . -name cacert.pem -exec sh -c 'cat /ca.crt >> "{}"' \;
find $ARC_DIR -type f ! -name 'SHA1SUM*' -exec sh -c 'sha1sum {} | sed "s/  / */g"' \; > $ARC_DIR/SHA1SUMS
sha1sum $ARC_DIR/SHA1SUMS > $ARC_DIR/SHA1SUMSSUM
tar czf python-agent.tar.gz $ARC_DIR
rm -rf $ARC_DIR
```

Here's what the whole thing looks like when run. The `rancher-nginx` image is our own build with a configuration file that expects to find the certificates & keys in `/certs`. 

```bash
$ sudo docker run -d --restart=always --name=rancher-server rancher/server
$ sudo docker run -p <your-exposed-SSL-IP>:443:443 --link=rancher-server -v /certs:/certs --name=rancher-nginx -d rancher-nginx
$ sudo docker exec -i rancher-server /update-python-cacert.sh
# After this, go to the newly-running Rancher server site and configure your
# choice of auth and also make sure your registration URL is set properly
$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 https://<rest-of-url-from-rancher-server-here>
```

**Comment by largesoft** [comment]
seconded

**Comment by largesoft** [comment]
there is no way I'm gonna go through all this to fix:

   time="2016-02-24T15:49:32Z" level=fatal msg="Unable to create event router" error="Get https://os.cccccc.org/v1: x509: certificate signed by unknown authority" 
[rancher@ip-172-31-16-207 rancher]$ ll

**Comment by largesoft** [comment]
I'll just buy the cert and hope it works lol

**Comment by deniseschannon** [comment]
In the latest version (v0.59.1), we added the ability to use self signed certs. 

http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta

**Comment by smaccona** [comment]
@deniseschannon excellent news! We already have self-signed certs working in prod using the workaround I posted above at https://github.com/rancher/rancher/issues/2237#issuecomment-149386553, but on our next rollout I will try this in our staging environment.

**Comment by averri** [comment]
This solution does not work for rancher/agent-1.0.2. Please, see: [#5381](https://github.com/rancher/rancher/issues/5381).

**Comment by will-chan** [comment]
Tracking this bug with #5381
