### ISSUE TITLE
Ability to add custom hosts instantiated from VM template

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2238]
I'm trying to automate my Rancher/Docker environment. I have a VM template (vSphere, Centos 7, Docker) from which I would like to create new instances that will automatically join my Rancher environment. I tried running the Add Custom Host command in the VM that was used to subsequently create the template, but upon instantiation of a new instance from that template, the agent fails with an Unauthorized response from the server.

I realize that this is probably intended, most likely for security reasons, but it makes VM automation difficult and I was wondering if there was any alternatives or plans for alternatives that would work in a situation like this?

**Comment by vincent99** [comment]
The custom host `docker run...` command is `rancher/server` install and environment (the dropdown in the top-right) specific, but reusable.

If you registered the VM to a `rancher/server`, you need to wipe out `/var/lib/rancher/state` before imaging.  It contains (among other things) a UUID for that host, so that if it registers again it's recognized as the same one.  So all your instances from the template probably have the same UUID.

**Comment by gordontyler** [comment]
So the process to setup the template would be something like:

1. Clone from base Centos 7 image.
2. Install Docker.
3. Run custom host add command.
4. Wait ???
5. Stop rancher-agent container.
6. rm -rf /var/lib/rancher /var/log/rancher
7. Freeze VM for template.

And the process to instantiate a new VM from the template:

1. Clone new VM from template.
2. Start rancher-agent container.

What about the /var/lib/cattle mount?

**Comment by vincent99** [comment]
The registration command needs to run on first boot of the image.. So stop at "2" and run it on instantiation, or add an init script to to the image to call it if no agent container exists, but don't run it before creating the image.

**Comment by gordontyler** [comment]
Gotcha. I'll give that a shot.

**Comment by gordontyler** [comment]
Vincent's suggestion worked, so this can be closed.
