### ISSUE TITLE
Cannot launch app from catalog for existing namespace when CPU and memory resource quotas are set

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#22401]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a new project with the following Resource Quotas:
CPU limit: Project limit: 4000 millis, Namespace default: 4000 millis
Memory Limit: Project limit: 16000 MiB, Namespace default 16000 MiB
2. Go to new project and App Catalog.
3. Select MySQL, Deploy

**Result:**
App is not created, get error `Validation failed in API: resourceQuota exceeds projectLimit on fields: limitsCpu=8,limitsMemory=23300Mi"`

**Other details that may be helpful:**
This only happens one a specific cluster. Cannot reproduce on a new cluster. Get same error if you create namespace and select that namespace when launching the App.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.7
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
NA
- Kubernetes version (use `kubectl version`):
v1.13.5

- Docker version (use `docker version`):
NA

**Comment by prachidamle** [comment]
I deployed Rancher v2.2.7 with Kubernetes 1.13.9, but I could not reproduce this issue with the steps mentioned:
- Create a new project with the following Resource Quotas:
CPU limit: Project limit: 4000 millis, Namespace default: 4000 millis
Memory Limit: Project limit: 16000 MiB, Namespace default 16000 MiB
- Go to new project and App Catalog.
- Select MySQL, Deploy

The app got deployed without error. For deploying new app I got the error "Validation failed in API: resourceQuota exceeds projectLimit on limitsCpu=8,limitsMemory=32000Mi" as expected.

The values of the limits mentioned are also correct.

I tried creating new namespaces with the above project limits, namespace gets created but you cannot deploy any new workload to the, since the quota is exhausted by the mysql app.
