### ISSUE TITLE
Host registration page is not displayed prior to registering the first host

### ISSUE THREAD

**Issue by sjwoodr** [rancher/rancher#2249]
In versions before 0.40, when you spun up a new rancher/server and went to add your first host, the host registration page was displayed so that you could specify the base URL for the rancher/server.  In 0.40 this page is not displayed and is only accessible via ADMIN -> Host Registration ... this led to some hard to debug issues since I was registering agents with a private address (http://10.x.x.x:8080) and while it would work, it left the stack in 'Activating' state while the services all came up as 'Active'.  

Please display the host registration prior to adding the first host, like you used to.  :)

**Comment by deniseschannon** [comment]
The behavior hasn't changed. Once you set the host registration URL, the UI will not display the host registration page when you click on "Add Host" . 

When upgrading from one version to another, since you've already set the host registration URL in the previous version, we don't show it again. 

In a fresh setup, the only time this gets bypassed is when GitHub Auth is turned on. It uses the URL used in the GitHub authentication.

**Comment by vincent99** [comment]
The logic is basically to show the prompt if the setting isn't set (and hasn't changed that I'm aware of).  Did you upgrade from a previous install/use an existing database?  Or turn on GitHub access control?  Setting up Github sets the registration URL to the page you're on once it's enabled.

**Comment by vincent99** [comment]
Gah, @deniseschannon wins this round.

**Comment by sjwoodr** [comment]
Ah hah!  That's the difference.... I enabled GitHub access control first.  I did not realize that setting that up would squash the display of that host registration page.   My bad.   so yeah... not a bug.  :)
