### ISSUE TITLE
Kubernetes taints are not seen on the nodes in the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22565]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a cluster - 1 etcd, 1 control plane and 1 worker node.
2. Verify the etcd and control plane have kubernetes taints.

**Expected Result:**
kubernetes taints should be seen on the nodes in the UI.

**Actual Result:**
kubernetes taints are not seen on the UI on the nodes even though on an Edit node --> Taints section has them
<img width="889" alt="Screen Shot 2019-08-30 at 1 54 20 PM" src="https://user-images.githubusercontent.com/26032343/64050740-d0e2c480-cb2d-11e9-8323-4b1a73e38f2e.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest UI
- Installation option (single install/HA): Single

**Comment by loganhz** [comment]
Not Kubernetes taints, they are Kubernetes role taints. So you still can see kubernetes node not-ready taints in UI.

I would like to hide Kubernetes role taints in UI. 

The reason is following:

- To keep the UX the same with 2.2.x for users who don't use taints, users cannot see the very long  Kubernetes role taints in UI
- We already have a `Unschedule` label and `Roles` column to indicate that if they are etcd/control plane and they are not unschedule.

**Comment by loganhz** [comment]
Talked to Vince, we will remove the yellow `Unschedule` tag and just show the taints.

**Comment by sowmyav27** [comment]
verified on master-head latest UI tag.

The Kubernetes role taints are seen on the UI and the yellow `Unschedule` tag is not seen anymore.
<img width="1462" alt="Screen Shot 2019-09-03 at 11 55 16 AM" src="https://user-images.githubusercontent.com/26032343/64200796-16f79b00-ce42-11e9-8952-6ca926686e85.png">
