### ISSUE TITLE
Non-exist docker image in rancher-images.txt file

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22651]
Bug in v2.3.0-rc1

The rancher-images.txt file from the Github release page (https://github.com/rancher/rancher/releases/tag/v2.3.0-rc1) contains the image `rancher/coredns-coredns:1.1.2` which does not exist. 

```
>  docker pull rancher/coredns-coredns:1.1.2
Error response from daemon: manifest for rancher/coredns-coredns:1.1.2 not found: manifest unknown: manifest unknown
```

It breaks the bash scripts for loading and saving images.

**Comment by kinarashah** [comment]
@guangbochen @loganhz would you happen to know why is this not available? I see that this image is present in `2.3-dev` branch for system-charts, and that's why it's getting added to rancher-images.txt 

https://github.com/rancher/system-charts/blob/dev/charts/rancher-istio/0.0.1/values.yaml#L131
https://github.com/rancher/system-charts/blob/dev/charts/rancher-istio/0.0.2/values.yaml#L134

**Comment by guangbochen** [comment]
Seems the coredns:1.1.2 image was missing in the previous image mirror syncs.
Link to https://github.com/rancher/rancher/pull/22678, the rancher/coredns-coredns:1.1.2 will be pushed once this PR is merged.

**Comment by sangeethah** [comment]
Will wait for rc2 to validate this issue.

**Comment by jiaqiluo** [comment]
The bug fix is validated during install rc2.

the image `rancher/coredns-coredns:1.1.2` is available now

```
>  docker images | grep coredns

rancher/coredns-coredns                     1.1.2                     8558f8c47fd7        16 months ago       46.4MB
```
