### ISSUE TITLE
Fail to ssh VM which was deployed by OpenStack

### ISSUE THREAD

**Issue by fengzixu** [rancher/rancher#22701]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. start a rancher container in vm
2. activate openstack nodedriver
3. fill the nodetemplate of OpenStack
4. create the cluster

**Result:**

1. VM has been created successfully.
2. Can Login with private_key in rancher docker manually
3. "Wait for SSH available" error msg always exists

![image](https://user-images.githubusercontent.com/9636615/64469907-5e00cb80-d175-11e9-9ff2-e190d4a7b5d5.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.3
- Installation option (single install/HA):sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): OpenStack NodeTemplate
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM, sufficient CPU and MEM
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
```

**Comment by fengzixu** [comment]
Hope someone can help me.

**Comment by empinator** [comment]
I have the same problem

**Comment by empinator** [comment]
I think I've at least found a reason for the ssh symptom ...
I am launching an Ubuntu image, which is immediately running the unattended-upgrades job
rancher, more precise docker-machine, is logging into the machine and trying to install curl
this is failing because apt can't get a lock, since the unattended-upgrades are still running
then the docker-machine is timing out after 60 retries

I managed to debug this issue so far by logging into the rancher container
```
[rancher@rke-server-3 ~]$ docker ps | grep "rancher/rancher"
edc9a8fec13f        rancher/rancher  ...

[rancher@rke-server-3 ~]$ docker exec -it edc9a8fec13f bash

root@rancher-6f9f545598-6kzrw:/var/lib/rancher# ps xau | grep "docker-machine" | more
root     31837  1.6  0.3 934904 24960 ?        Sl   15:05   0:01 docker-machine create -d openstack --engine-install-url http:// ...
```

Execute same command with --debug from within the container
```
root@rancher-6f9f545598-6kzrw:/var/lib/rancher# docker-machine --debug create -d openstack ...
```

It will print all commands executed towards your node in detail. In my case I can see that the "apt-get install -y curl" command is unable to get a lock.

I still don't have it solved yet (with the ubuntu image) but I wanted to share my research

**Comment by empinator** [comment]
So, I finally figured out what the real problem was (my research above is still valid though)

There was a change in the node-template regarding the certificate field. Before one was supposed to supply a file path pointing to the pem file to log into the provisioned VMs. This field has been changed to a textarea (I guess in Version 2.2.4) and now you have to copy/paste the content if the pem file into the field. No more copying of the pem file to the server necessary.

![node-template-privatekey](https://user-images.githubusercontent.com/3467461/66549228-1e961800-eb43-11e9-8474-64a87ca13bea.png)
