### ISSUE TITLE
[UI] Alerting - Better message for expressions that do not return graph data

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22742]
Version: master-head (v2.3) (9/9/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable alerting
- Edit the "A set of alerts for node" alert rule group.
- Look at the node disk rules

**Result:**
There is no data returned in Prometheus so the UI shows a message "No metric graph data."

**Expected Result:**
We expected the UI to either show this in a more friendly manner (no red text making it look like there is an error) or to show something on the chart (e.g. we could render the chart but show a message on the chart itself like "No metric graph data."

**Additional Comments:**
This isn't really a big deal -- the UI is doing what it should. But to a new user it may look like their expression is not set up correctly because of the red text. It threw me off at first -- I had thought the expressions were wrong but they are not - there is just simply no data to show.

I propose that at a minimum we make the text no longer red.

**Comment by aaronRancher** [comment]
This bug is reproduced in `rancher\rancher:v2.3-head` `version b7e6f7b52`.

Create a cluster.
Enable monitoring.
From Global > Tools > Alerts
Edit the "A set of alerts for node" alert rule group.

![Screen Shot 2019-11-27 at 9 26 52 AM](https://user-images.githubusercontent.com/57409052/69741618-9cfd4800-10f8-11ea-8245-99fe9b431583.png)


The bug fix is validated in `rancher\rancher:master-head` `version`.

Message does not show up.
![Screen Shot 2019-11-27 at 9 41 02 AM](https://user-images.githubusercontent.com/57409052/69742511-2b25fe00-10fa-11ea-9bc0-fc6f589a980f.png)
