### ISSUE TITLE
Rancher should support AWS access/secret key rotation

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#22812]
**What kind of request is this (question/bug/enhancement/feature request):**
feature - enhancement

**Steps to reproduce (least amount of steps as possible):**
Rancher uses access/secret in cloud credentialand node template to provision EKS or EC2 and so on. AWS security guideline is to rotation access/secret key pair minimum every 30 days

If we could assign IAM role for Rancher master to have permission to rotate access/secret key pair in a define interval e.g. 30 day that could improve security of product.

**Comment by panho66** [comment]
- use case 1
    single AWS account where Rancher master and managed cluster deployed
    Rancher instance has IAM profile to grant permission to rotate access/secret key
- use case 2
    multiple AWS accounts where Rancher master in account #1 and managed cluster in account #2
    Rancher instance has IAM profile to grant permission to resume role to rotate access/secret key in another AWS account
- use case 3
   Option to disable key rotation

**Comment by stacylacy6** [comment]
Any chance of this progressing?  Manually changing keys is a huge pain with dozens of clusters?

**Comment by stacylacy6** [comment]
This is still a valid issue.  Rancher needs to support other methods of AWS credentials or provide an easier method of rotating keys.  For most situations we would rely on role based authentication rather than access key's and secrets.  But if access keys and secrets are used, there must be a way other than manually to update them.  Best practices for AWS would be not to have permanent access keys and secrets.
