### ISSUE TITLE
The monitoring data of load in rancher ui is inconsistent with the data of grafana

### ISSUE THREAD

**Issue by MrYuanZhen** [rancher/rancher#22820]
* What kind of request is this 
    bug

* Environment information
    Rancher Version: v2.2.8

* Problem Description
    Open monitoring in RancherUI, the load information monitoring icon data of the node is inconsistent with grafana.

![image](https://user-images.githubusercontent.com/37647017/64753445-d7bdfe00-d555-11e9-97d8-3c406f07f969.png)
![image](https://user-images.githubusercontent.com/37647017/64753450-dab8ee80-d555-11e9-935b-e48e75617935.png)
![image](https://user-images.githubusercontent.com/37647017/64753451-dc82b200-d555-11e9-9815-dfbaa2ee59b8.png)

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.2.8

Steps:
- run rancher v2.2.8
- add a single node cluster, the node has 4 virtual CPU core
- enable cluster monitoring 

In Rancher UI, the value of `Load1` is 0.07

<img width="514" alt="Screen Shot 2019-09-13 at 10 53 19 AM" src="https://user-images.githubusercontent.com/6218999/64884135-c9cfb200-d615-11e9-98ec-1f55f733dc99.png">

In Prometheus, the value of `Load1` is 0.29

<img width="444" alt="Screen Shot 2019-09-13 at 10 54 07 AM" src="https://user-images.githubusercontent.com/6218999/64884159-da802800-d615-11e9-8347-fa299c70add4.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in master-head ee3fb04a7

Steps:
- run rancher v2.2.8
- add a single node cluster, the node has 4 virtual CPU core
- enable cluster monitoring 


Result:
- the values for `load1` `load5` and `load15` are the same in both Rancher UI and Prometheus 

<img width="407" alt="Screen Shot 2019-09-13 at 11 16 52 AM" src="https://user-images.githubusercontent.com/6218999/64885141-321f9300-d618-11e9-8874-0ca20a67e0b5.png">
<img width="437" alt="Screen Shot 2019-09-13 at 11 17 26 AM" src="https://user-images.githubusercontent.com/6218999/64885142-321f9300-d618-11e9-8ae2-7fef467063b4.png">
<img width="365" alt="Screen Shot 2019-09-13 at 11 17 52 AM" src="https://user-images.githubusercontent.com/6218999/64885143-321f9300-d618-11e9-84a9-dd672ee8b110.png">
<img width="316" alt="Screen Shot 2019-09-13 at 11 18 07 AM" src="https://user-images.githubusercontent.com/6218999/64885144-321f9300-d618-11e9-982f-f17fa1b97070.png">
