### ISSUE TITLE
Inconsistent units in the project quota page

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#22827]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Result:**
In the project quota page, the memory-related configuration uses MiB, and the storage-related configuration uses GB.

Storage does not use GiB, is there any special reason?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8

**Comment by vincent99** [comment]
Physical memory comes in and is measured in powers of 2 (MiB = 2^20).  Physical storage does not because hard drive manufactures don't want to.  A 1GB hard disk has 1000^3 bytes.  (SSDs are made in powers of two, but have reserved capacity and are marketed in 1000's anyway)

macOS and Windows both show files in 1000's to match.

(networking is also similar, but usually measured in 1000^x bits)
