### ISSUE TITLE
rancher_max_version set for older versions of monitoring and istio is not being applied

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22835]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a cluster in a new Rancher setup of `v2.3.0-rc3`

**Expected Result:**
Monitoring and Istio should show only the valid chart versions.

**Actual Result:**
When you navigate to cluster --> Tools --> Monitoring or Istio, all the 4 (Monitoring) / 2 (Istio) chart versions are seen.

**Note:**

This does not happen always.

Leave the setup around for sometime. DO NOT do a hard refresh of the page. Then again navigate to cluster --> Tools --> Monitoring or Istio. All the charts versions will be displayed..

ON doing a hard refresh of the page, only 1 chart version is displayed for both monitoring and Istio.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.3.0-rc3`
- Installation option (single install/HA): single

**Comment by dramich** [comment]
After discussing this with @vincent99 this should be a change in the UI to filter out the versions not compatible with that version of rancher.

**Comment by vincent99** [comment]
The problem is there's no connection between asking for templates within this range in the initial list call and what comes down the socket.  So rather than having the server do that filtering (half the time) I suggested the UI just get them all and decide which to show on its own.

But that doesn't actually work, each templateVersion has a different valid range and the reason the server filters it is so that we can load just /v3/templates and get back the set of valid versionLinks for that range without having to load the entire (huge) set of /v3/templateVersions (or making n+1 calls to verify individual versions)

Soo... I think we need to go back to (stay on) server filtering:

- `/v3/templates` should only return `versionLinks` for `versions` which are satisfied by the current Rancher version.  You can add a secret `?all` flag if you want but I don't think there's any use case _requiring_ it.

- Drop/ignore the query param that the UI uses to pass in the server version.  You already know what version you are. (this is historical baggage from catalog being an independent microservice in 1.x)

- Suppress change events for any templateVersion that does not satisfy the current server version.

- /v3/templateVersions and /v3/templateVersions/:id should still return ALL the versions (so that if you have an App that already exists the UI can get info about the version and its upgrade links, even if it's now incompatible with the running Rancher version)

**Comment by sowmyav27** [comment]
verified on `rancher:v2.3.0-rc4`.

- Bring up an rke cluster.
- After the cluster is `Active` state, go to Cluster --> Tools --> Monitoring/Istio.
- Verified that only one version is seen, which is applicable for the rancher version.
- Leave the setup around for sometime. (no hard refresh)
- Navigate to Cluster --> Tools --> Monitoring/Istio.
- Verified that only one version is seen, which is applicable for the rancher version.
