### ISSUE TITLE
Health monitoring should create a network agent on all hosts that are picked up for monitoring

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2287]
In https://github.com/rancher/rancher/issues/1877, there is a known bug that if health monitoring picks up a host that doesn't have a network agent on it, the health monitoring will not work.

We need to deploy network agents on any hosts that are used in health monitoring so that health monitoring will work correctly. 

Current workaround is to ensure that there is a container on every host so that network agent will always be present on all hosts.

**Comment by alena1108** [comment]
Schedule health check on host only when Healthcheck network service provider is present there. Also:

reconcile health check scheduling for all instances with health check enabled, when Healthcheck network service provider (network-agent) gets deployed
remove health check host maps on network-agent remove

**Comment by sangeethah** [comment]
Tested with latest build from master -  Jan/05

Health check does not get scheduled on host where there is no network agent running.
Tested in a set up with 3 hosts (h1,h2,h3) , where 1 host (h1) had 1 LB instance running and the other 2 hosts had no instance/ network agent running.

Only the host on which LB was running was scheduled for health monitoring.
 Started an instance in h2 . This resulted in the h2 being added to monitor LB's health.
 Started another instance in h3. This resulted in the h3 being added to monitor LB's health.
 
Deactivate and deleted host h2. This resulted in the h3 being removed  from monitoring LB's health.

**Comment by deitch** [comment]
Perhaps I misunderstood, but isn't that a bit backwards? If I have h1,h2,h3 and a service running on h1. Based on reading this, it sounds like the behaviour is "don't schedule health checks from h2 and h3 because there is no network-agent running." But we want 3 health check sources! Isn't the correct behaviour, "start network-agents on h2 and h3 so that health checks can run"?

**Comment by deniseschannon** [comment]
You are correct that it's a bit backwards, but this is the best that we could do with our current design. You can read the discussion we had about design in the PR: https://github.com/rancher/cattle/pull/1116

**Comment by deitch** [comment]
That discussion was very interesting. Based on this, it sounds like you couldn't get to "automatically deploy network agent when scheduling health check" in time, so instead you went for "stop health check from being scheduled on host of network agent isn't present." It isn't ideal, but it does solve the immediate inconsistent state problem. 

Is this in 1.0 or one of the earlier pre releases?

And what is the ETA for breaking out network agent into a system stack scheduled for "global", so that this problem really is fixed correctly?

**Comment by deniseschannon** [comment]
This fix should be v0.56.1. 

It's not on the roadmap to have the network agent to be scheduled as global service.
