### ISSUE TITLE
Hide 'unsupported' storage providers and provisioners

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#22895]
**What kind of request is this (question/bug/enhancement/feature request):**
Hide 'unsupported' storage providers and provisioners

Pages affected:
Persistent Volume
Storage Class
Add Workload -> Volume -> Ephemeral

**Comment by vincent99** [comment]
New feature flag to look at:  https://github.com/rancher/rancher/pull/22899

If false, then hide unsupported options for those types, unless you're editing an existing resource that is already using it.

**Supported:**

Persistent Volume volume plugin: `aws-ebs`, `azure-disk`, `azure-file`, `flex-volume-longhorn`,
`gce-pd`,`host-path`,`local`,`nfs`,`vsphere-volume`

StorageClass: `aws-ebs`, `azure-disk`, `azure-file`, `gce-pd`, `longhorn`, `local`, `vsphere-volume`

**Unsupported:** Everything else

**Comment by izaac** [comment]
@vincent99 do we still prefer to wait for QA until this other PR is finished https://github.com/rancher/rancher/pull/22899

Or this is ready for validation after @codyrancher 's changes ?

**Comment by sangeethah** [comment]
Reopening this issue for  #22899 to be merged.

**Comment by rmweir** [comment]
appear to work fine if the page is refreshed, if the page is not refreshed then the user can still use one of these types. If we want to stop the creation then we should do it in validators for PV/SC:
feature off: 
![image](https://user-images.githubusercontent.com/19376037/65285602-d3fc1f80-daf1-11e9-96d5-ce0389003cb0.png)

feature on:
![image](https://user-images.githubusercontent.com/19376037/65285667-0279fa80-daf2-11e9-8ee5-082942210e19.png)

**Comment by rmweir** [comment]
This appear to work when the value is changed via kubectl, but since using the flag or environment variable changes the default, it does not work

**Comment by rmweir** [comment]
Arguments and environment variables appear to work now.

**form:** featurename1=bool,featurename2=bool....

**How to use arguments:**
`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher --features=unsupported-storage-drivers=bool`

**How to use environment variable:**
`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_FEATURES='unsupported-storage-drivers=bool' rancher/rancher`

**Comment by rmweir** [comment]
Also, if the feature is disabled while a user is still on a page, they will still be able to use the unsupported storage providers. We could add a validator to stop this

**Comment by codyrancher** [comment]
My understanding is that we don't necessarily want to disable functionality we just want to discourage the use. So my vote would be to leave it out of the validator.

**Comment by sowmyav27** [comment]
**Verified on latest `master-head`.**

- Started a rancher server with no args/env variables -- `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head`

### Scenario#1
- Verified under `/v3/features`, `unsupported-storage-drivers` is set to **false**.

```
name": "unsupported-storage-drivers",
"type": "feature",
"value": false
```

- Bring up a cluster (AWS, cloud provider set). Go to Storage --> Storage Classes --> Add Class --> Provisioner
- UI shows the supported versions:

<img width="1463" alt="Screen Shot 2019-09-20 at 11 22 30 AM" src="https://user-images.githubusercontent.com/26032343/65349987-8affa600-db99-11e9-9ba8-edcd8f940976.png">

- Go to Storage --> Persistent Volumes --> Add Volume --> Volume Plugins
- UI shows the supported versions:

<img width="1459" alt="Screen Shot 2019-09-20 at 11 28 31 AM" src="https://user-images.githubusercontent.com/26032343/65350161-f184c400-db99-11e9-8f41-c769e4dcf89b.png">

- Go to Project --> Deploy a workload --> Volume --> Ephemeral Volume
- UI shows the supported versions:
<img width="973" alt="Screen Shot 2019-09-20 at 11 34 55 AM" src="https://user-images.githubusercontent.com/26032343/65350759-496ffa80-db9b-11e9-85ff-91c9683eae6b.png">


@vincent99 Have a couple of questions based on the comment here - https://github.com/rancher/rancher/issues/22895#issuecomment-531999169:
- In a Cluster --> Storage --> Storage Classes --> Add Class --> Provisioner, are `local` and `(Custom)` (as displayed in the UI) the same?
- In Storage --> Persistent Volumes --> Add Volume --> Volume Plugins, are `host-path` and `local` , the same as `Local Node Disk` and `Local Node Path` as seen on the UI ?
- The list of supported volume source, for Ephemeral Volume, is it expected?

### Scenario#2

- Go to `v3/features/unsupported-storage-drivers`
- Set value: `true`. And send the request.
- The Value for `unsupported-storage-drivers` feature is set to `true` now.
- Go to Storage --> Storage Classes --> Add Class --> Provisioner. Everything is listed including unsupported ones.
- Go to Storage --> Persistent Volumes --> Add Volume --> Volume Plugins. Everything is listed including unsupported ones.
- Go to Project --> Deploy a workload --> Volume --> Ephemeral Volume. Everything is listed including unsupported ones.

### Scenario#3
The Value for `unsupported-storage-drivers` feature is set to `true` now.

- Create a Storage Class, Persistent Volume from the Unsupported List.
- User is able to create Class and volumes successfully

**Issue -** 
- Deploy a workload
- Add an ephemeral Volume.
- Choose one form the unsupported list say - `StorageOS`.
- The UI throws an error and does not allow you to proceed.
<img width="1007" alt="Screen Shot 2019-09-20 at 12 43 30 PM" src="https://user-images.githubusercontent.com/26032343/65355524-f9973080-dba6-11e9-9c59-4e7bf8b71bd6.png">
- Whereas when you select anything from the `Supported List` of Volume source, user is able to create an ephemeral volume. 

Reopening this issue because of this ^^^.

**Comment by sowmyav27** [comment]
**Verified on latest `master-head`.**

**Steps:**

- The Value for `unsupported-storage-drivers` feature is set to **`true`** now.
- Create a Storage Class, Persistent Volume from the Unsupported List.
- User is able to create Class and volumes successfully
- Deploy a workload
- Add an ephemeral Volume.
- Choose one form the unsupported list say - StorageOS.
- Enter all other details and click on `Define`.
- There is no error seen on the UI.
- User will be able to deploy the workload.
- 

Verified  with volume `Empty dir volume`, no error seen on UI, workload deployed successfully.

**Comment by sowmyav27** [comment]
@codyrancher Have a couple of questions based on the comment here - #22895 (comment):

- In a Cluster --> Storage --> Storage Classes --> Add Class --> Provisioner, are local and (Custom) (as displayed in the UI) the same?
- In Storage --> Persistent Volumes --> Add Volume --> Volume Plugins, are host-path and local , the same as Local Node Disk and Local Node Path as seen on the UI ?
- The list of supported volume source, for Ephemeral Volume, is it expected?
<img width="973" alt="Screen Shot 2019-09-20 at 11 34 55 AM" src="https://user-images.githubusercontent.com/26032343/65350759-496ffa80-db9b-11e9-85ff-91c9683eae6b.png">

**Comment by codyrancher** [comment]
> @codyrancher Have a couple of questions based on the comment here - #22895 (comment):
> 
> * In a Cluster --> Storage --> Storage Classes --> Add Class --> Provisioner, are local and (Custom) (as displayed in the UI) the same?

There isn't a local storage class currently registered. I suspect that Custom could be used to do local. @vincent99 when you were referring to local storage class which did you mean?
Here's the list https://github.com/rancher/ui/blob/master/app/models/storageclass.js#L11
> * In Storage --> Persistent Volumes --> Add Volume --> Volume Plugins, are host-path and local , the same as Local Node Disk and Local Node Path as seen on the UI ?

They are.
local -> Local Node Disk
host-path -> Local Node Path

> * The list of supported volume source, for Ephemeral Volume, is it expected?
> 
Ephemeral uses the same supported providers as persistent it's just a matter of whether or not the provider is labeled as ephemeral.
Here's the full list https://github.com/rancher/ui/blob/master/app/models/volume.js#L7
> <img alt="Screen Shot 2019-09-20 at 11 34 55 AM" width="973" src="https://user-images.githubusercontent.com/26032343/65350759-496ffa80-db9b-11e9-85ff-91c9683eae6b.png">

**Comment by vincent99** [comment]
The provisioner for a storage class is an arbitrary string that the user can provide (besides the standard ones that are listed.  If you type in something then it's supposed to show up as `<thing you said> (custom)`.  If you haven't typed in something or the current value is an option already in the dropdown, you shouldn't see "(custom").

But all that's changing for this issue is that some drivers are or aren't shown by default.

If you're getting into testing what individual drivers do or don't do or how they work that's fine, you can put in separate issues, but that is a separate concern that hasn't changed here.

**Comment by sowmyav27** [comment]
@vincent99 @codyrancher - a couple of questions
1. In master-head, currently irrespective of this flag - `unsupported-storage-drivers` being set to true or false, user is able to see the `custom` option in the dropdown. User is able to add a custom storage class when the `unsupported-storage-drivers` is set to false, which should not be the case.
2. As per comment here -- https://github.com/rancher/rancher/issues/22895#issuecomment-531999169, `local` is NOT available as a dropdown value at all for Storage class provisioners irrespective of this flag - `unsupported-storage-drivers`- set to true/false.

**Comment by deniseschannon** [comment]
1. Showing `custom` is fine for supported storage drivers
2. There is no `local` in 2.2.8 for storage classes so we don't need to add anything additional.

**Comment by sowmyav27** [comment]
Closing this issue based on @deniseschannon 's comments.

**Comment by drbothen** [comment]
I knwo this is closed, but after updating I lost my ability to create iscsi volumes from the UI. I am assuming thats because of this, correct?

**Comment by codyrancher** [comment]
@drbothen 

That's correct. If you still need to use iscsi you can enable it using feature flags. 
to list feature flags: `kubectl get features`
to edit feature flags: `kubectl edit feature <feature-name>`

We will have a UI added to edit these feature flags in soon.

**Comment by tfiduccia** [comment]
@drbothen - You can also go to the API https://'your url'/v3/features/unsupported-storage-drivers, edit and set the value to true, you will see your drivers as well.
