### ISSUE TITLE
"CSRF header and cookie do not match"

### ISSUE THREAD

**Issue by JulianKingman** [rancher/rancher#2292]
I just set up rancher, and I'm getting this error when I try to log in. I logged in yesterday just fine, I'm not sure what changed, nor am I sure what this message means.

I tried restarting the container and clearing my cache, neither worked. After deleting the cookies, it told me my username and password were incorrect (more helpful error). I tried a couple different ones, and finally got back in. So what was the CSRF header thing all about?

I'm rather new to server config, hopefully I can help resolve this.

**Comment by vincent99** [comment]
I'm not sure how you would have triggered it justing using the browser, but CSRF is short for Cross-Site Request Forgery.  Without protection any third party site can make a request to `http://your-rancher/...` to say create a container, and it would succeed if you happened to be logged in to your rancher at the time.

So we prevent this by having a cookie called CSRF (which other domains can't read) and requiring that the same value be passed in the request headers (since only we can know the value of the cookie).

**Comment by JulianKingman** [comment]
That's a clever solution. Would you expect it to give me that error if I had the wrong login info?

**Comment by deniseschannon** [comment]
@JulianKingman Are you still facing this issue? If so, please re-open. 

If you had the wrong login error, it would provide an error that the login is incorrect.
