### ISSUE TITLE
Catalog app does not show correct template version on Edit app

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23051]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy a cluster - rke with 1 node.
2. In a project --> Apps --> Select an app i.e. mysql
3. Select template version `0.3.7`
4. Click on Launch
5. After the app is in `Active` status, click on `Upgrade` 

**Expected Result:**
Template Version shown should be 0.3.7

**Actual Result:**
Template version shown is the latest one - 0.3.8
But it does show `0.3.7` as **`current`**

**Note:**
This happens on 2.2.8 also

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.0-rc8
- Installation option (single install/HA): single

**Comment by codyrancher** [comment]
I'm not sure that this is actually a bug. If we changes this behavior we'll actually force the user to make another interaction in order to upgrade an app.

We can change this but I think this would be a feature request.
@tfiduccia or @vincent99 is this something that we want to change?

For some additional context when loading the page we see:
![Screen Shot 2019-09-24 at 2 01 23 PM](https://user-images.githubusercontent.com/55104481/65550203-ef8d6e80-ded3-11e9-835e-609560018df9.png)

But this request wants us to switch it to the 0.3.7 (current) version which is listed in the dropdown:
![Screen Shot 2019-09-24 at 2 01 30 PM](https://user-images.githubusercontent.com/55104481/65550238-05029880-ded4-11e9-8ac4-810da0bd589d.png)

**Comment by vincent99** [comment]
Yes this is correct.  "Upgrade" can be changing the actual version, or just changing the answers provided. It shouldn't automatically select a newer/the newest version.

**Comment by codyrancher** [comment]
Alright. I'll work on it.

**Comment by sowmyav27** [comment]
**Verified on master-head -- latest** 

**Steps:**

- Deploy a cluster - rke with 1 node.
- In a project --> Apps --> Select an app i.e. mysql
- Select template version 0.3.7
- Click on Launch
- After the app is in Active status, click on Upgrade
- Template Version shown is 0.3.7
- Upgrade app to version 0.3.8. Click on Upgrade.
- After the app comes up Active, click on edit app - Upgrade
- Version shown is 0.3.8
