### ISSUE TITLE
Processes Page won't load on process ID

### ISSUE THREAD

**Issue by bscott** [rancher/rancher#2309]
![image](https://cloud.githubusercontent.com/assets/191290/10414500/c852e990-6f8c-11e5-93b1-fcd00aaae558.png)

**Comment by deniseschannon** [comment]
What version of Rancher are you running? I haven't been able to reproduce this.

**Comment by deniseschannon** [comment]
@bscott If you can re-produce on the latest vrsions, please let me know. It seems to work for me, but just takes a little bit to actually load.
 
Maybe yours will take longer to load because of how long the process has been running. Looks like about 3 months. 

@westlywright  Is there anything that could be done to make the page load a bit faster?
