### ISSUE TITLE
Cluster template and cluster template revision names should be made unique

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23104]
Version: Master-head

Currently cluster template and cluster template revision names do not need to be unique.
We are allowed to create multiple cluster templates and multiple template revisions with the same names. 
Though it gives the user flexibility to choose what he wants, but using the same names does not help while working with the templates and using them. The user will have to use the ids to differentiate between them . 

<img width="1263" alt="Screen Shot 2019-09-26 at 12 20 18 PM" src="https://user-images.githubusercontent.com/18536626/65718250-08269180-e058-11e9-8b3b-0c1fbcb8b4e5.png">

**Comment by prachidamle** [comment]
For clustertemplates and revisions, we decided not to have uniqueness imposed for names because:

1) There can be different users creating and naming their templates with same names. So imaging user1 creating a template say CT1 and a revision V1 - we need to allow user2 also be able to create a template CT1 and revision v1. So uniqueness cannot be imposed on them as we need to let users create them with same names.

2) Now if we want to impose the uniqueness per user account, the following scenario would also break: 
suppose user1 creates a template named CT1 and user2 also creates a template CT1. Now later user1 shares their template with user2. In this case for user2 we will have to be able to list two templates with name CT1.
Thus per account restriction will not work either due to sharing feature.

I dont think we should fix this issue.
