### ISSUE TITLE
For a cluster member, rke template id/revision id is displayed instead of the name 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23125]
Version: master-head

Steps:
1. Create a RKE template/revision T1/R1
2. Create users, user1, user2
3. Create a cluster using T1/R1 and add user1 as a member to the cluster
4. Login as user1 who is a member
In the cluster dashboard page, the rke template/revision ids ( RKE Template: ct-cmj5g/ctr-4ttzn ) are displayed instead of T1/R1

![Screen Shot 2019-09-27 at 10 51 15 AM](https://user-images.githubusercontent.com/18536626/65790564-c0b20b00-e114-11e9-827b-50c825dff10c.png)

**Comment by codyrancher** [comment]
This is expected behavior. I had a conversation with @westlywright about what we do when the user doesn't have access to the cluster template and he told me that we typically display the id.

@westlywright would you mind confirming/denying my understanding of the conversation?

**Comment by westlywright** [comment]
Based on the way the issue is worded I agree with what @codyrancher said. Currently just because the user is a member of the cluster doesn't give them access to the cluster template afaik.

**Comment by soumyalj** [comment]
I agree that for a cluster member does not have access to the template. 
Displaying the ID can have security concerns. We can possible not show a template for this case or just say RKE template in use.

**Comment by westlywright** [comment]
@soumyalj I don't understand why this would be a security concern? If simply having access to the id's is cause for concern we have a bigger issue. Obfuscating it from the UI doesn't solve that problem, the data is still sent over the wire and someone who wants the id can get it fairly easily. This is also a pattern we use when you repeat this exact scenario but remove rke templates and replace them with a node template. A member of the cluster can not see the node templates they do not have access to; If a cluster member edits the cluster they would see the node template id in the selector drop down because they don't have access to view that template.
