### ISSUE TITLE
[go] [rancher/types] NewManagementClient does not work with Cluster Scoped Token

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#23142]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

```
        managementClientOptions := &clientbase.ClientOpts{
		URL: "https://rancher2/v3/cluster/cluster-id"
		AccessKey: "accessKey",
		SecretKey: "secretKey",
	}

	managementClient, err := rancherManagementClient.NewClient(managementClientOptions)
	if err != nil {
                 panic(err)
	}

	nodes, err := managementClient.Node.List(&types.ListOpts{})
        if err != nil {
                 panic(err)
        }
```

**Result:**

This will result in schema type node unknown error.

**Other details that may be helpful:**

Basically it seems like the golang client can't handle scoped tokens properly. It's unable to determine the correct schemas when scoped.

**Comment by vincent99** [comment]
The management client is for global-level resources (clusters themselves, and other things in the global level of the UI).  Cluster scored tokens are only for (things inside) an individual cluster.

There is a “nodes” at the global level because they all call in to report status to the management server, but you cannot interact with them using a cluster-scoped token.

**Comment by ekristen** [comment]
Ah. Good to know. Thanks.
