### ISSUE TITLE
links not working as expected 

### ISSUE THREAD

**Issue by fernandoneto** [rancher/rancher#2315]
im performing some tests and every time i creat a stack based on same `docker-compose.yml` the links relation are different. 

this is how it should be
![captura de ecra de 2015-10-12 11 19 53](https://cloud.githubusercontent.com/assets/6515784/10426151/963c1c5c-70d5-11e5-9df0-89c1b980845d.png)

but im getting something like this 

![captura de ecra de 2015-10-12 11 19 24](https://cloud.githubusercontent.com/assets/6515784/10426166/a8c2eae0-70d5-11e5-9cf1-db1908f81aa6.png)
![captura de ecra de 2015-10-12 11 21 36](https://cloud.githubusercontent.com/assets/6515784/10426175/b1181594-70d5-11e5-94b0-1f0ca0069b1b.png)

![captura de ecra de 2015-10-12 11 33 29](https://cloud.githubusercontent.com/assets/6515784/10426207/d44e0a78-70d5-11e5-845d-d6ed498e363e.png)

the compose file is allways the same without any change.

**Comment by ebuildy** [comment]
I am getting also some trouble since version 0.40, but it's just UI bugs isnit?

**Comment by deniseschannon** [comment]
Yes, these should be just UI bugs related to https://github.com/rancher/rancher/issues/1389

**Comment by deniseschannon** [comment]
@fernandoneto Since you guys have multiple environments, I believe you are just hitting #1389. If you refresh, the links should show up. 

If they don't show up after refreshing, please re-open the issue and we can debug further. 

Also, with the DNS improvements this may not be necessary for you unless you need explicit environment variables to be passed from one service to another that occurs when linking 2 services.
