### ISSUE TITLE
When creating a service with no image and selector.container , scale gets saved as 1.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2317]
Rancher server version - v0.41.0-rc1
Rancher compose version - rancher-compose-v0.4.1-rc2

Used the following docker-compose.yml from rancher-compose to create a service with no image.
noscale:
  labels:
    io.rancher.service.selector.container: foo=bar

When this service gets created on the rancher-server , its scale gets set to 1:
When i try to export config for the service , the scale for this service is set to 1.

```
| 113 | noscale |          5 | service | 2ca407bf-0221-4964-a3d8-ed1970af67d8 | NULL        | active  | 2015-10-10 00:22:36 | NULL                | NULL                | {"fields":{"scale":1,"launchConfig":{"labels":{"io.rancher.service.selector.container":"foo=bar"},"logConfig":{},"networkMode":"managed","privileged":false,"publishAllPorts":false,"readOnly":false,"startOnCreate":true,"stdinOpen":false,"tty":false,"version":"0"}}} |             50 | 169.254.86.202 |         NULL | NULL          | foo=bar        
```

We should not set the scale when adding a service with no image and  selector.container.

**Comment by alena1108** [comment]
Have to tweak the defaults for "scale" parameter - today its 1, should be null.

**Comment by alena1108** [comment]
Thought more of it - changing the default from 1 to 0 can break the backwards compatibility. Users would have to go and update their *yml templates in case the scale was missing there.

This issue is not a blocker. When user wants to create his service with scale=0, he can pass scale=0 parameter to the API call. Although its not supported in the UI today, it should be supported via API/rancher-compose

As for putting a scale on selector only container - keeping scale causes no harm either. Selector only service is identified by imageUUID=rancher/image-none presence; and as long as this image is set, scale is going to be ignored.

Punting this bug till later.

**Comment by alena1108** [comment]
Closing this bug for now as it doesn't impact functionality, only a compose representation which is harmless.
