### ISSUE TITLE
Unable to upgrade Istio from 0.0.1 -> 0.0.2 due to insufficient CPU

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23197]
rancher/rancher:master-head bc57ac2d1

Upgrading Istio from 0.0.1 -> 0.0.2 fails due to a lack of sufficient resources

* Deploy a cluster
* Enable Istio 0.0.1(1.2.0)
* After Istio is enabled, upgrade to 0.0.2 (1.3.1)
* The upgrade fails with components `istio-pilot, istio-policy, istio-telemetry` failing with error: `ReplicaSet <name> has timed out progressing.; Deployment does not have minimum availability.`

This was tested with 2 different clusters

* Cluster 1 - 4 `t2.medium` worker nodes
* Cluster 2 - 1 `t3.2xlarge` worker node

In the case of cluster 2, cpu reservation went from `4.9/8` to `7.7/8` during the upgrade. Scaling the nodepool up to 2 workers allowed the deployment to progress for a short time until it failed again when cpu reservation hit `15.1/16`.

What is causing the upgrade to reserve so much CPU? At times the replica count goes up to 4 (desired is 1) for some of the components, which seems to be contributing.

This behavior did not occur when upgrading from `1.2.0` to `1.2.5` when this was last tested.

**Comment by loganhz** [comment]
Istio 1.3.2 is just released. Maybe we can introduce 1.3.2 and test upgrade from 1.3.1 to 1.3.2

**Comment by deniseschannon** [comment]
Can you make a new helm chart that uses istio 1.3.2?

**Comment by guangbochen** [comment]
The high CPU reservation is raised by both the `RollingUpdate` strategy and HPA policy `(scale up/down upon 80% average utilization of CPU)` of the `istio-pilot, istio-policy, istio-telemetry` components, so during the upgrade:
1. `RollingUpdate` strategy for those components will request `2*(CPU & Memory)` in total.
2. since the CPU average usage of each pod is above 80% during the upgrade (could be the app itself bootstrap consumption), so the HPA policy will scale the pod number up to maximum 5, normally it goes up to 2 or 3 of different components, so this will request 2~3*(CPU & Memory) in total.
3. the pod replicas will scale down to the default `1` if no peak traffic is generated by the user's istio sidecars after a few minutes.

As a result, if the customer's k8s cluster has enough resources it will be sufficient to handle the istio upgrade, or optionally we can set the default requested CPU and memory of the `istio-pilot, istio-policy, istio-telemetry` components to smaller values.

**Comment by loganhz** [comment]
Can be test with https://github.com/rancher/system-charts `dev` branch. Istio 1.3.2 is available.

**Comment by deniseschannon** [comment]
Istio 1.3.3 is now available as app version 0.1.1

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 10/17
system-charts:dev branch

* Create cluster, 5 t2.medium worker nodes
* Enable Istio 0.1.0
* CPU has 6.5/10 reserved
* Upgrade Istio to 0.1.1
* Upgrade completed without needing to add any nodes
* CPU has 7.3/10 reserved
