### ISSUE TITLE
Canal use nodes internal-ip for overlay network?

### ISSUE THREAD

**Issue by GameScripting** [rancher/rancher#23281]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher 2.2.8 on VM/bare metall
- Create custom cluster with Canal as network provider

Canal now uses [the nodes default route interface](https://github.com/projectcalico/canal/blob/master/k8s-install/canal.yaml#L8-L11) to create the overlay network.

**Question:**
Within a heterogeneous cluster where different machines with different interfaces are used:
- old naming schema eg. `eth0`
- new schema eg. `ens6`
- nodes connected via openvpn eg. `tun1`

the default [cluster wide config](https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/#canal-network-plug-in-options) of the interface name [will not really work](https://github.com/rancher/rancher/issues/14721#issuecomment-418193403).

Within kubernetes every workernodes gets an external (1) and internal ip (2):
![grafik](https://user-images.githubusercontent.com/1827070/66411808-a3bee700-e9f4-11e9-9df1-355ba1ae9aa3.png)

Is there any way to tell Canal to just always use the interface/ip specified in the "internal ip" (2) address? Because this way it would not matter what the name if the nodes interface is.

the reason I am asking is, because I don't want my inter-cluster communication to happen on a public interface, because it may has [security implications](23278).

**Comment by andersla** [comment]
I have hit the same problem, I am trying to add  a node from another network that is talking on a different network. The pods can not communicate on the overlay network because flannel is bound to the external interface.

**Comment by martin-kieliszek** [comment]
> Note: in the below examples I have redacted the actual IP addresses

When I run rancher agent, I specify the desired `--address 10.0.0.164` and `--internal-address 10.0.0.164` options on the cli, AND for extra insurance I add the same values for `-e CATTLE_ADDRESS=10.0.0.164` and `-e CATTLE_INTERNAL_ADDRESS=10.0.0.164` as I *need to use this local interface* to communicate to other nodes via this secondary interface address (not default interface)

I then check the first agent container that gets launched and can confirm that all of the values get assigned as expected:

```
CATTLE_ADDRESS=10.0.0.164 CATTLE_INTERNAL_ADDRESS=10.0.0.164 
.
customConfig=map[address:10.0.0.164 internalAddress:10.0.0.164 roles:[etcd worker controlplane] label:map[]]
.
```

However, because rancher spins up an additional two agent images (total of 3 now) the third agent image it spins up doesn't honor the provided variables 

Third agent container during set-up
```
CATTLE_ADDRESS=10.0.10.180 CATTLE_INTERNAL_ADDRESS=
.
Option customConfig=map[roles:[] label:map[] address:10.0.10.180 internalAddress:]"
.
```
The address seen in the above example is the default network/gateway interface on the node. (But not the interface I wish to use for the rancher network - as the default interface is set for other purposes)

When the agent successfully registers and finishes setting up, the rancher node GUI shows two IP addresses - just like the auther of the post.

I did some digging. When issuing the below kubectl command 
```
 $ kubectl --kubeconfig ~/.kube/config describe node nodeNameX
```

... the Internal IP seems to be set to what rancher auto inspects from the server, as opposed to the provided and desired value

```
$ kubectl --kubeconfig ~/.kube/config describe node nodeNameX | grep -i internal
                    
rke.cattle.io/internal-ip: 10.0.0.164
  InternalIP:  10.0.10.180
```

It is my understanding that the `Internal IP` is set during registering the node to kubernetes. Despite the cattle tags clearly making into the annotations of the node configuration, is it possible to hard set the `Internal IP` to the provided and desired environment variables of the first agent container?

Is the fix to ensure that the environment variables propagate towards subsequent rancher agent spin ups?

**Comment by GameScripting** [comment]
@martin-kieliszek thank you for sharing you insights about how the internal IP is not correctly communicated to K8s. How, however is this related to my original post?

I *think* your findings are worth a seperate issue, but do not really releate to my issue.

**Comment by martin-kieliszek** [comment]
@GameScripting thanks for your swift response

Perhaps it is worth me filing a separate issue, agreed.

RE: my initial thought process of how my comment could have been relevant to your issue:
We have a desire to control inter-cluster communication over Canal on a desired `Internal IP` address. 

However, in hindsight, I agree, my comment focused on another topic. The topic of failing to overwrite the `Internal IP` AWAY from automatically being set to the node's default public interface IP.

**Comment by GameScripting** [comment]
Unfortunately this issue creates a showstopper for that we are trying. I am preparing to create a patch + pull request.

I would like to implement a solution where the name of the interface used by canal can be specified/overriden as an annotation for the node.

I guess that the code I need to modify is this one: https://github.com/rancher/rke/blob/747f63945c64fa38121cd67da90bb978cedef199/cluster/network.go#L167

I am not a Golang developer, but I think I might manage to do it.
Are there any hints for me from any contributer how to go about the feature?

**Comment by GameScripting** [comment]
Update: We did not end up creating the patch. Instead we are now using k3s to deploy small clusters at the edge, connecting them to our central rancher server for managment.

**Comment by boris-savic** [comment]
This would've been a really cool feature thought. As it would simplify certain deployments and firewall management
