### ISSUE TITLE
Translation for banners are broken on Apps page when autorefresh fires

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#23322]
Version - v2.3.0

**What kind of request is this (question/bug/enhancement/feature request):**
Bug 

**Steps to reproduce (least amount of steps as possible):**
1.  Go to Global Apps page
2.  Wait until backend refresh for catalog fires

**Result:**  Banners lose translation
![image](https://user-images.githubusercontent.com/11514927/66520954-04a2f980-ea9f-11e9-9da7-9a6eaebf9da4.png)

**Comment by westlywright** [comment]
I was never able to reproduce this locally but was able to see it on Tani's machine. There was another bug in the same code that I think was the cause of this though. Since it seemed dependent on the catalog refresh firing and the automatic refresh only happens once an hour I had to work around this by using my own catalog and triggering the refresh from the API ui or another window. 

1. Clone https://github.com/rancher/integration-test-charts
2. Add this catalog (from your clone) as a catalog in Rancher
3. Make a change to this local catalog and push the change to the github repo and branch you added to Rancher. _we have to do this because the backend compares commit hashes on refresh and if the commits haven't changed it doesn't trigger the refresh._
4. In another window or from the API UI, trigger the refresh via the refresh button

Alternately you could wait for the the automatic refresh to happen on the back end (which I did 
 but still didn't cause the error to happen)

I have also fixed another error where the refresh button in the UI would show the warning icon after clicking. It should revert back to the correct icon on success now.

**Comment by westlywright** [comment]
Available in UI tag `latest-2.3`

**Comment by soumyalj** [comment]
This issue was not reproducible in v2.3.0.

**Comment by tfiduccia** [comment]
I haven't been able to reproduce on newest verisons so I'm going to close.
