### ISSUE TITLE
Certain AWS instance types do not work with managed network

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2332]
Discovered that IPsec tunneling doesn't work with certain AWS instance types, which will cause managed containers to not be able to communicate with each other. 

Known to work:
m3.medium

Known issues:
r3.large
m4.large
m3.large
t2.medium

Note: There may be others that have issues.

**Comment by deniseschannon** [comment]
Confirmed by user using v0.42.0-rc3

**Comment by synaptics** [comment]
Hi, sorry but I'm using the following Rancher in AWS on an m3.large Ubuntu instance:

Component	Version
Rancher	v0.43.1
Cattle	v0.106.0
User Interface	v0.63.0
Rancher Compose	v0.5.0

and I still have the issue where health checks are failing and causing the container to restart, can you look at this behaviour please (I got here because this issue was linked to from another thread discussing the problem I was experiencing)?  

Happy to provide further information if needed.

Thanks,
John

**Comment by synaptics** [comment]
Hi, additionally I've discovered the random restarting behaviour seems to occur more reliably when the container is scheduled globally (I'm running in a single host environment).

Thanks,
John

**Comment by deniseschannon** [comment]
Healthchecks don't cause containers to be restarted. In fact, new containers are created when healthcheck reports a failure. 

If it's creating a new container, can you look at the `healthState` of the previous container (the one that was stopped) to confirm that it's the healthcheck causing the issue.

**Comment by synaptics** [comment]
How do I check the healthState of the previous container?

**Comment by deniseschannon** [comment]
When you see the stopped container in the UI, you can "View in API" to find the "healthState". It's in the API.
