### ISSUE TITLE
Glusterfs failedmount error

### ISSUE THREAD

**Issue by barankaynak** [rancher/rancher#23374]
My cluster is working with glusterfs 5.5 but the same cluster cant mount volumes on glusterfs 6.5. https://github.com/gluster/glusterfs/issues/658 says that k8s version on rancher dowsnt support glusterfs 6.x. 

Rancher version: v2.3.0
Kubernetes Version: v1.14.3

> MountVolume.SetUp failed for volume "pvc-0b27a11c-ec05-11e9-ab38-005056b7e9c3" : mount failed: mount failed: exit status 1 Mounting command: mount Mounting arguments: -t glusterfs -o backup-volfile-servers=192.168.10.191,log-file=/opt/rke/var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-0b27a11c-ec05-11e9-ab38-005056b7e9c3/test-7d8bf8f966-dxtjt-glusterfs.log,log-level=ERROR 192.168.10.191:vol_33fa96d3ed5199d0970c5dbfce454e12 /opt/rke/var/lib/kubelet/pods/0b34ef70-ec05-11e9-ab38-005056b7e9c3/volumes/kubernetes.io~glusterfs/pvc-0b27a11c-ec05-11e9-ab38-005056b7e9c3 Output: Mount failed. Please check the log file for more details. the following error information was pulled from the glusterfs log to help diagnose this issue: [2019-10-11 08:57:00.845388] E [glusterfsd-mgmt.c:1590:mgmt_getspec_cbk] 0-glusterfs: failed to get the 'volume file' from server [2019-10-11 08:57:00.845455] E [glusterfsd-mgmt.c:1690:mgmt_getspec_cbk] 0-mgmt: failed to fetch volume file (key:vol_33fa96d3ed5199d0970c5dbfce454e12)
> --

**Comment by mamsy** [comment]
Rancher version: v2.3.5
Kubernetes Version: v1.17.2

same shit:
MountVolume.SetUp failed for volume "glusterfs-cluster" : mount failed: mount failed: exit status 1 Mounting command: mount Mounting arguments: -t glusterfs -o auto_unmount,backup-volfile-servers=192.168.110.56:192.168.110.57,log-file=/opt/rke/var/lib/kubelet/plugins/kubernetes.io/glusterfs/glusterfs-cluster/mapi-deployment-5495b78bc6-ktr6w-glusterfs.log,log-level=ERROR 192.168.110.57:mamsy /opt/rke/var/lib/kubelet/pods/6a9eccb8-9153-4454-b3f2-33c5ebf3fddf/volumes/kubernetes.io~glusterfs/glusterfs-cluster Output: [2020-02-13 06:59:57.826073] E [glusterfsd.c:795:gf_remember_backup_volfile_server] 0-glusterfs: failed to set volfile server: File exists Mount failed. Please check the log file for more details. , the following error information was pulled from the glusterfs log to help diagnose this issue: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f576cd52d0f] ---------

**Comment by JulyIghor** [comment]
/opt/rke/var/lib/kubelet/plugins dir is empty right?

**Comment by mamsy** [comment]
> /opt/rke/var/lib/kubelet/plugins dir is empty right?

yes, everything empty its most simple installation)

**Comment by Giancarlo1974** [comment]
The problem is related to the version of Gluster installed on the Rancher kubelet:
it is too old

Log in via SSH on a node in the cluster
Type:

`sudo su -`
`docker ps | grep kubelet`
--> CONTAINER ID = 740541b0bd7c

Now enter in the container

docker exec -it 740541b0bd7c /bin/bash

Now you can verify that an older version is installed in Rancher

glusterfs --version
--> glusterfs 4.1.5


I encountered a similar problem when I tested OpenEBS
The workaround is to bind
[(Step2: Add extra_binds under kubelet service in cluster YAML)](https://blog.openebs.io/running-openebs-on-custom-rancher-cluster-98ecd52b5961)

However, I was unable to use the trick on Gluster

I hope this information can help someone find the solution, which I would like to know

**Comment by slash1387** [comment]
see https://github.com/rancher/rancher/issues/27472 and support please :)
