### ISSUE TITLE
[UI] Associate a group (from AD/SAML/Github/etc) with rancher role

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23452]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**What:**
when creating AD group a user should be able to select from a dropdown of rancher roles to associate with that group

**Backend Issue:**
https://github.com/rancher/rancher/issues/22707

**Comment by tfiduccia** [comment]
Changes only to user screen:
1.  Add a button on the User list page that says Add Group.  It should only show if you are logged into an Auth provider that supports groups.

2.  Add group page:
     Drop-down with list of groups pulled from auth provider
     Global Permissions section
     Create/Cancel buttons

![image](https://user-images.githubusercontent.com/11514927/66876705-a2973800-ef67-11e9-8c9a-5549b6dea22e.png)

**Comment by westlywright** [comment]
Due to some limitations of the external auth provider api's we've had to change the requirements of this page a bit.

1. Move `Users` route under top level `Security` nav item
2. Add `Groups` route under users
3. Groups page should list out group rows containing the following info
  a) Group Name
  b) Comma separated list of roles associated with this group
  c) List of roles link to there global role page
  d) Row actions allowing edit and delete 
4. Add Group Page
  a) Principal Search dropdown which loads in your groups and lets you search additional groups (only group principals)
  b) Global Permissions section
  c) Create/Cancel buttons
5. No changes to user and user detail pages because we can't not gather this info
6. No group detail page because the users api doesn't return a group that is has to lookup.

**Comment by jiaqiluo** [comment]
The feature is tested in Rancher:master-head 5845c2d

The UI works exactly as the above comment describes. https://github.com/rancher/rancher/issues/23452#issuecomment-558740533

More tests are done and tracked in the test plan, and new issues will be made for bugs found during the validation.
