### ISSUE TITLE
Changing service port updates ingress in UI but not in nginx.conf

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#23461]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create workload that listens on 80 (like a webserver) but expose port 8080 as an error
2. Create ingress pointing to service on 8080. This will fail.
3. Edit workload and change port to 80

**Result:**

1. Ingress shows in the UI that it updated to port 80, but nginx.conf still shows that it's sending traffic to 8080.
2. Connections to ingress return a 503.

**Other details that may be helpful:**

The destination app is running on Windows.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.0
- Installation option (single install/HA): standalone

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Azure
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by loganhz** [comment]
Ingress UI shows 80. But it is still 8080 if you check via yaml. the workaround is re-selecting the port in edit ingress page

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.0` 
Steps:
Create workload that listens on 80 (like a webserver) but expose port 8080 as an error
Create ingress pointing to service on 8080. This will fail.
Edit workload and change port to 80
UI shows that port has changed:
![Screen Shot 2020-01-16 at 12 00 44 PM](https://user-images.githubusercontent.com/57409052/72554552-2bb85680-3858-11ea-9314-eca2304ac0b5.png)
View/Edit YAML shows that port has not changed:
![Screen Shot 2020-01-16 at 12 00 52 PM](https://user-images.githubusercontent.com/57409052/72554585-396ddc00-3858-11ea-8fd7-a44e20831532.png)
Results in a 503:
![Screen Shot 2020-01-16 at 11 59 49 AM](https://user-images.githubusercontent.com/57409052/72554602-42f74400-3858-11ea-936b-5d4e41f74601.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 8e320d045`
Upon port change, ingress shows no port:
![Screen Shot 2020-01-16 at 12 06 12 PM](https://user-images.githubusercontent.com/57409052/72554851-c1ec7c80-3858-11ea-8ecb-c680ad79f339.png)
New, correct port is shown in dropdown:
![Screen Shot 2020-01-16 at 12 06 21 PM](https://user-images.githubusercontent.com/57409052/72554858-c749c700-3858-11ea-888b-db5460ce2a78.png)
