### ISSUE TITLE
Docker network freezing during rancher agent registration (occasionally)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2347]
User reported that sometimes during rancher agent registration, the entire docker network freezes and is unusable.

**Comment by edurdias** [comment]
Hi @deniseschannon, @will-chan, do you have any update on this? We're facing this problem during a reboot of the host. 
Currently using:

Rancher: v0.49.1
Cattle: v0.121.0
User Interface: v0.71.0
Rancher Compose: v0.6.1
Rancher Agent: v0.8.2

**Comment by ibuildthecloud** [comment]
@edurdias This issue is typically caused by an external process manipulating iptables during provisioning of the server.  For example puppet often hits this issue.  People deploy Docker + rancher/agent using puppet.  What will happen is that Docker boots, rancher agent starts then some external puppet module either changes the iptables or flips the value of `/proc/sys/net/ipv4/ip_forward` to 0.

I would recommend looking at `/proc/sys/net/ipv4/ip_forward` and iptables when this happens.

**Comment by deniseschannon** [comment]
@edurdias If you are still facing this issue after @ibuildthecloud's comment, please re-open.
