### ISSUE TITLE
Showing Amazon EKS message for Azure AKS

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#23601]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1.  Go to Add Clusters
2.  Select Azure AKS

**Result:**
![image](https://user-images.githubusercontent.com/11514927/67315148-d1a72f80-f4ba-11e9-8fac-faf9d5b49acd.png)

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by soumyalj** [comment]
Reproduced the issue with v2.3.2
![Screen Shot 2019-11-08 at 4 54 39 PM](https://user-images.githubusercontent.com/18536626/68519948-2384df00-0249-11ea-954f-b79c5d856fbc.png)

Tested with master-head. The issue is fixed
![Screen Shot 2019-11-08 at 4 58 04 PM](https://user-images.githubusercontent.com/18536626/68519956-297ac000-0249-11ea-82f9-c8eb0e1d5ab8.png)
