### ISSUE TITLE
Error when upgrading k8s from 1.13.12-rancher1-1 to 1.16.2-rancher1-1

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23653]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.3.1
- add a cluster with k8s `1.13.2-rancehr1-1`
- upgrade Rancher to 2.3.2-rc1
- upgrade the cluster to k8s `1.16.2-rancher1-1`

**Result:**
- the upgrade is finished and the cluster is up
```
> k version 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
> 
```
- the Workload: `rke-kube-dns-addon-delete-job` ( image `rancher/hyperkube:v1.16.2-rancher1`)  is stuck with the error in pods' logs
```
unable to recognize "/etc/config/rke-kube-dns-addon.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "/etc/config/rke-kube-dns-addon.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
'-f rsrc.yaml'
'--filename=rsrc.json'
'<resource> <name>'
'<resource>'
```
 
<img width="1471" alt="Screen Shot 2019-10-23 at 5 13 09 PM" src="https://user-images.githubusercontent.com/6218999/67443117-68a5e180-f5b8-11e9-974d-9b32bfae1d45.png">

**Comment by sowmyav27** [comment]
On an upgrade from 2.2.9 to 2.3.2-rc2, Upgrade from `v1.15.5-rancher1-1` --> `v1.16.2-rancher1-1` works fine.

**Comment by mrajashree** [comment]
K8s 1.13 rke-kube-dns-addon configmap has "apps/v1beta1" as the apiversion. When we upgrade to 1.16, rke gets this configmap, and since 1.16 no longer supports any older/deprecated versions we get the "no matches for kind" error.

K8s 1.15 configmap has "apps/v1" as the apiversion hence upgrading to 1.16 works

**Comment by mrajashree** [comment]
Workaround 1: 
1. Before upgrading to 1.16, check the kube-dns configmap by running
```
kubectl get configmap rke-kube-dns-addon -n kube-system -o yaml
```
The configmap data field contains all resources for kube-dns. 
2. Edit the apiversion of 2 deployment resources: `kube-dns-autoscaler` and `kube-dns` to `apps/v1`
3. Upgrade to 1.16
4. Core-dns will be deployed post upgrade

Workaround 2:
1. If the above steps aren't performed prior to upgrade from 1.13 to 1.16, upon upgrade delete the workload `rke-kube-dns-addon-delete-job` (pod with error in the above screenshot) and the `rke-kube-dns-addon-deploy-job` job.
2. The 1.16 cluster will continue to use kube-dns now.
3. If instead you want to switch to core-dns, another cluster upgrade is needed, because the logic to remove kube-dns and start core-dns for 1.16 doesn't retry on the first error. So you can upgrade cluster, which will lead to core-dns being deployed and then you can delete kube-dns

**Comment by sowmyav27** [comment]
Verified on an upgrade from `2.2.9` to `2.3.2-rc2`

- Have an rke cluster - k8s 1.13.2 deployed in 2.2.9 rancher. (3 etcd, 1 control plane, 3 worker nodes)
- Run Pre upgrade automation checks. 
- Upgrade to 2.3.2-rc2.

**Workaround 1:**

- Check the kube-dns configmap by running - `kubectl get configmap rke-kube-dns-addon -n kube-system -o yaml`
- Change the apiVersions of these 2 deployments - kube-dns-autoscaler and kube-dns to "apps/v1"
- Upgrade to 1.16.2 k8s version
- Core-dns is deployed post upgrade
- Post upgrade automation checked passed.

**Additional Checks**
- Have an rke cluster - k8s 1.13.2 deployed in 2.2.9 rancher. (3 etcd, 1 control plane, 3 worker nodes)
- Run Pre upgrade automation checks. 
- Upgrade to 2.3.2-rc2.
- Run post upgrade checks. All Passed.
- Upgrade cluster to 1.15.5 k8s version.
- Run post upgrade automation checks. All passed. Core-dns is deployed
