### ISSUE TITLE
Test, certify, and harden vSphere cloud provider

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#23677]
The not-fully-quantified feedback we've gotten is that it is somewhat buggy and quirky. We should identify what specifically works and doesnt work and see what we can fix.

vSphere clusters should also get added to our validation matrix so that automation runs against such a cluster on tagged builds.

cc @sangeethah @cloudnautique @deniseschannon

**Comment by cloudnautique** [comment]
Specifically, our attention should be spent on the out of tree provider.

**Comment by janeczku** [comment]
Note that out of tree cloud providers no longer provide native storage support.
Since the main purpose of deploying the vSphere cloud provider is to consume storage for persistent volumes, we should certify both [vSphere CPI driver](https://github.com/kubernetes/cloud-provider-vsphere) and  [vSphere CSI driver](https://github.com/kubernetes-sigs/vsphere-csi-driver).

**Comment by cjellick** [comment]
Thanks for clarifying @janeczku
