### ISSUE TITLE
Setting `CATTLE_UI_PL` Does not replace `Rancher` on the First Login server url page.

### ISSUE THREAD

**Issue by Luberry** [rancher/rancher#23681]
**What kind of request is this (question/bug/enhancement/feature request): bug

**Steps to reproduce (least amount of steps as possible):
1. Run rancher UI with `CATTLE_UI_PL` set to something other than default.
```bash
docker run --rm -it -p 80:80 -p 443:443 -e CATTLE_UI_PL=TEST_UI_PL rancher/rancher:v2.3.0
```
2. Navigate to your rancher server in the browser and set your password.
3. You will now be redirected to the page asking you to change the server url.

**Result:**
This results in a page that says `Rancher Server URL` when it should be `TEST_UI_PL Server URL` per the settings of the `CATTLE_UI_PL` variable.

<img width="1678" alt="Screen Shot 2019-10-25 at 12 02 43 PM" src="https://user-images.githubusercontent.com/438520/67587074-0fa58d00-f721-11e9-8ca1-e4059ac6c5d0.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): I have tested this with rancher/rancher:v2.2.8, rancher/rancher:v2.3.0

- Installation option (single install/HA): Affects single install and HA

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.0`:
Steps:
Run rancher UI with CATTLE_UI_PL set to something other than default.
```
docker run --rm -it -p 80:80 -p 443:443 -e CATTLE_UI_PL=TEST_UI_PL rancher/rancher:v2.3.0
```
`CATTLE_UI_PL` variable is not reflected on URL page:
![Screen Shot 2020-01-24 at 2 26 02 PM](https://user-images.githubusercontent.com/57409052/73107713-c7327280-3ebb-11ea-9de0-0886e3a29d98.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version d92bd8b`:
![Screen Shot 2020-01-24 at 3 09 31 PM](https://user-images.githubusercontent.com/57409052/73107701-c0a3fb00-3ebb-11ea-9b03-fd0af6326aa8.png)
