### ISSUE TITLE
weave password changes on cluster updates causing network outages

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#23702]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. deploy cluster
2. modify any aspect of the cluster (say addon_job_timeout) via edit as yaml
3. the `weaveNetworkProvider: {}` gets emptied out which erases the password redeploying the weave network

**Result:**
this causes weave to get redeployed causing a network outage

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher v2.3.1

**Comment by superseb** [comment]
The reason why this happens:

In types, we mark the password field in the weaveNetworkProvider as `norman:"type=password"`, which hides it in the API. If you edit the YAML, it retrieves the config from the API (where it is hidden), and then making any change in that YAML applies the YAML as it is submitted (without the hidden parameter), triggering an update to the cluster because the spec is different and applying the "new" network deployment without the parameter. What I can think of to fix this:

- Remove the `"type=password"` to hide it from the API so it ends up in the YAML when retrieving the config from the API. This makes it possible for any user in the cluster to see the password in the API and defeats the intention to hide it from the API in the first place. The reason to name this is because it keeps the API flow of retrieving and modifying data. Other reason to do this is because when the YAML has everything, you don't have to guess if the data was changed or not. In case the user wants to remove the password, you can't distinguish that request from someone who changed something else in the YAML.
- Don't remove the key/value from the API, but show the key and obfuscate the value to indicate that the password is unchanged and shouldn't be touched/handled as changed.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 5ccf85b5a`

Deploy a cluster with Network set to "Weave".
Once the cluster gets created successfully , notice that the weave-net workload under kube-system using "Edit/View Yaml" option shows weave password being set -"name":"WEAVE_PASSWORD","value":""}
![Screen Shot 2019-11-19 at 12 58 15 PM](https://user-images.githubusercontent.com/57409052/69182328-00babc00-0ace-11ea-9525-aed1526804c8.png)

Edit cluster and modify any aspect of the cluster (say addon_job_timeout) via edit as yaml.
As part cluster update , notice that weave-net workload does NOT get redeployed anymore.WEAVE_PASSWORD continues to be set in the weave-net workload as expected.
