### ISSUE TITLE
sidekick instances get registered as targets to the LB

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2371]
Steps to reproduce:

1) Create and activate service with sidekicks.
2) Add Load Balancer. Register service created on step 1) to the LB.
3) Activate the LB service. Its important that the LB service gets activated as the last step as thats what caused buggy behavior. 

Bug: only instances of primary service should have been registered to the LB, but I'm seeing instances of the sidekicks registered as well.

**Comment by sangeethah** [comment]
This issue is reproduced when the LB service is activated after the targets gets added.
Following steps will results in the bug:
Create a service - s1 with sidekick and activate it.
Create LB service.
Add service s1 as target to LB service.
Activate LB service.

Instances of primary service as well as sidekick instances gets added as targets to the LB service.

In the following set of steps where targets are added after the LB service is activated , only instances of the primary services get added as targets to LB service.

Create a service - s1 with sidekick and activate it.
Create LB service.
Activate LB service.
Add service s1 as target to LB service.

**Comment by sangeethah** [comment]
Tested with build from v0.43.0-rc1

Tested the following flow when adding LB services:

Create a service - s1 with sidekick and activate it.
Create LB service.
Add service s1 as target to LB service.
Activate LB service.

Only Instances of primary service gets added as targets to the LB service.
