### ISSUE TITLE
Error on UI on catalog refresh

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23725]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Add a global level/project level catalog app.
- Refresh the catalog app say the library catalog: `https://git.rancher.io/charts`.
- Error is seen on the UI: `Update failed: fatal: unable to access 'https://git.rancher.io/charts/': The requested URL returned error: 502 : exit status 128`

The refresh action's response: `{"baseType":"catalogRefresh","catalogs":["library"],"type":"catalogRefresh"}` gives a 200 response.

Catalog is seen stuck in Refreshed Status

<img width="1282" alt="Screen Shot 2019-10-29 at 1 50 29 AM" src="https://user-images.githubusercontent.com/26032343/67714756-8cb95680-f9ee-11e9-8d9c-9b9f3eb25375.png">

But the UI continues to show the error message.

After the user, logs out of Rancher and logs back in, the error on UI is not seen anymore.

**Note:** not always reproducible 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head/2.3.2-rc3
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
I have been unable to reproduce this and allegedly there were some issues the day this ticket was filed with catalogs that may have caused this to occur. In my opinion, since I don't have logs to prove this, is that the UI acted in the correct manner here. The refresh action succeeded, as indicated by the 200 response posed above. The error occurred and was sent almost immediately and the status was sent over the websocket which is why we see the error below. When the user logs out and in and no longer sees the error is purely coincidence. When the user logged back in the status of the resource may have been in a good state again. The error message for these and other resources is retrieved from the `conditions` param on the resource which is live updating via events pushed over websockets. The fact that is changes from green to error indicates the messages are coming over the wire correctly and if the error message is stuck, then the backend probably didn't send a change event via websocket. 

Again this is my opinion as I have not been able to reproduce this and was told it was an intermittent issue that appeared that day.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/68754784-a7ebaf00-0607-11ea-85f2-2aa68088a4e9.png)
Rancher 3.3.2

**Comment by vincent99** [comment]
@MSandro that looks like a totally unrelated issue.  Clearly 3 completely separate domains (aliyun, google, and our git mirror) are not all receiving HTTPS and giving back HTTP responses, so it is likely that you have a misconfigured HTTP proxy or TLS interception device in your path to the internet.

**Comment by MSandro** [comment]
@vincent99 thanks, I will create a separate issue for this, because since a few days I am trying to solve this and figure out why this happens, but without success.

**Comment by dramich** [comment]
Confirmed looking at slack that `https://git.rancher.io/charts/` was down the day this was submitted (@sowmyav27 is the one who posted about it initially). 

The catalog refresh will return a 200 indicating that the server accepts your refresh request and succeeded in marking the catalog as requiring a refresh. This does not mean the act of doing the refresh succeeded. A controller will pick up the catalog and go do the refresh updating the status as it goes. During this refresh the above error was encountered which is normal/expected behavior if the URL is returning errors.

**Comment by MSandro** [comment]
https://git.rancher.io/charts/ gives me a 404 if I access it from my home network, there is definitly no proxy or TLS interception device.

**Comment by vincent99** [comment]
It's a git repository, not a website.  

```
Mercury:tmp vincent$ curl -I https://git.rancher.io/charts/
HTTP/2 404
server: openresty/1.15.8.1
date: Fri, 15 Nov 2019 17:07:52 GMT
expires: Fri, 01 Jan 1980 00:00:00 GMT
pragma: no-cache
cache-control: no-cache, max-age=0, must-revalidate
strict-transport-security: max-age=15724800; includeSubDomains

Mercury:tmp vincent$ git clone https://git.rancher.io/charts/
Cloning into 'charts'...
remote: Counting objects: 4933, done.
remote: Compressing objects: 100% (2107/2107), done.
remote: Total 4933 (delta 2628), reused 4904 (delta 2614)
Receiving objects: 100% (4933/4933), 2.61 MiB | 5.86 MiB/s, done.
Resolving deltas: 100% (2628/2628), done.
Mercury:tmp vincent$
```
