### ISSUE TITLE
Monitoring - some graphs are missing in k8s 1.16 cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23731]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.3.2-rc3
- add a cluster with k8s 1.16
- enable the cluster monitoring 

**Result:**
The following graph is missing in the Kubernetes component metrics section
- controllermanager-queue-depth

The following graphs are missing in the workload metrics section
- workload-network-packet
- workload-network-io
- workload-disk-io

**Comment by thxCode** [comment]
1. Against controllermanager-queue-depth graph:
    - since `v1.14`, the Workqueue metrics have been modified to follow the Prometheus best practices and naming conventions (ref: https://github.com/kubernetes/kubernetes/pull/71300) and changed the `xxx_depth` format metrics (search `Controller Manager Queue Depth` from [Rancher Docs](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/expression/)) have been deprecated 
   - When going into `v1.16`, those deprecated metrics has been dropped via https://github.com/kubernetes/kubernetes/pull/77553. 
   - The root cause is the `xxx_depth` metrics has bee dropped, I could patch some Recording Rules back to fix it. **With a compatible PR https://github.com/rancher/system-charts/pull/120, it would not affect `<=v1.13` cluster and should work well in `>=v1.16`**

2. Against workload-network-packet, workload-network-io, workload-disk-io graph:
    - since `v1.13`, https://github.com/kubernetes/kubernetes/pull/69099 has introduced two new labels `pod` and `container` to try to replace `pod_name` and `container_name` labels of `container_*` metrics.
    - When going into `v1.16`, those two deprecated labels has been dropped via https://github.com/kubernetes/kubernetes/pull/80376. 
        + However, with [KEP: kubelet-resource-metrics-endpoint](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/kubelet-resource-metrics-endpoint.md) and our [monitoring metricRelabelings logic](https://github.com/rancher/system-charts/blob/d7db400173e29d00e1b857ab5c5a285f86bfff04/charts/rancher-monitoring/v0.0.5/charts/exporter-kubelets/templates/servicemonitor.yaml#L134-L146) , the following metrics still keep both `(pod|container)` and `(pod_name|container_name)` labels: *container_cpu_usage_seconds_total*, *container_memory_working_set_bytes*, *node_cpu_usage_seconds_total* and *node_memory_working_set_bytes*.
    - The root cause is losting `pod_name` and `container_name` lables in lots of `container_*` metrics. **With a compatible PR https://github.com/rancher/system-charts/pull/120, it would not affect `<v1.13` cluster and should work well in `>=v1.16`**

Test plan:
- [ ] In any rancher version that could access to the `dev` branch of `rancher/system-charts`, set up a `v1.12` cluster with enabling cluster-level Monitoring
    - [ ] [Verify] those four graphs still work
- [ ] In any rancher version that could access to the `dev` branch of `rancher/system-charts`, set up `v1.16` cluster with enabling cluster-level Monitoring.
    - [ ] [Verify] those four graphs still work

**Comment by deniseschannon** [comment]
Available in `dev` branch of system-charts with Monitoring v0.0.6

**Comment by jiaqiluo** [comment]
The bugfix is validated in v2.3-head 5187fce31 with monitoring v0.0.6

Steps:

- run Rancher v2.3-head
- add a cluster with k8s 1.16
- enable the cluster monitoring (v0.0.6)

Results:
The mentioned missing metrics show up now.

**Comment by jiaqiluo** [comment]
@thxCode 
If the new monitoring chart 0.0.6 is not compatible for k8s 1.14 and 1.15, will cluster with k8s v1.14 or v1.15 in Rancher v2.3.3 uses monitoring v0.0.5? 
Currently, the chart does not support min/max k8s version, right?

**Comment by jiaqiluo** [comment]
confirmed with @thxCode that monitoring template v0.0.6 works with k8s v1.13, v1.14, v1.15, and v1.16

**Comment by jiaqiluo** [comment]
Rancher `v2.3-head` 5187fce

The cluster monitoring `v0.0.6` is tested in the following clusters:  k8s `v1.13`, `v1.14`, `v1.15`, and `v1.16`
