### ISSUE TITLE
Hide description field in configmap

### ISSUE THREAD

**Issue by freeloop914** [rancher/rancher#23736]
**What kind of request is this (question/bug/enhancement/feature request):**
bug v2.3.1

**Steps to reproduce (least amount of steps as possible):**
1. Add new ConfigMap from UI
2. Fill description field.
3. Save

**Result:**
The list or detail of configmap cannot find any description 

**Other details that may be helpful:**
No description filed in API too. 

We need to hide it as it's not supported in api

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version fc9a84779`

The bug is reproduced with Rancher server `rancher\rancher:v2.3.1`
Steps:
Create a config map.
Edit map and add a description.
![Screen Shot 2020-01-13 at 10 29 10 AM](https://user-images.githubusercontent.com/57409052/72279799-23f87800-35f4-11ea-82f2-ae2da9b367dd.png)
![Screen Shot 2020-01-13 at 10 29 24 AM](https://user-images.githubusercontent.com/57409052/72279807-265ad200-35f4-11ea-95ea-ddb49ade8610.png)
Upon refresh, description is not shown.
![Screen Shot 2020-01-13 at 11 00 51 AM](https://user-images.githubusercontent.com/57409052/72279824-2c50b300-35f4-11ea-8611-8b30381e042d.png)

Using Rancher server `rancher\rancher:master-head` `version fc9a84779`:
The option to add a description has been removed.
![Screen Shot 2020-01-13 at 10 15 00 AM](https://user-images.githubusercontent.com/57409052/72276687-c19c7900-35ed-11ea-92ee-c3c857e2c60a.png)
