### ISSUE TITLE
Incorrect node memory usage gauge when cluster monitoring is enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23786]
Steps:

1. Create a cluster. (Worker Node A with memory 20GB) (Worker Node B with 2GB).
2. Enable cluster monitoring
3. Deploy all workloads to Node B to consume all memory on Node B

Results:

The gauge says `2 GB of 22GB used`. But the percent value is `50%`

Expected:

The percent value in the gauge should be `9%`

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.3.1

- add a cluster with 2 workers, worker-1 has 4GB memory and worker-2 has 16GB 
- enable the cluster monitoring with the selector `kubernetes.io/hostname = worker-1` 

Results:
- 2.1 of 19.5 GiB memory is used, which should be about 11%, but the gauge shows 17%


<img width="1435" alt="Screen Shot 2019-11-01 at 10 01 35 AM" src="https://user-images.githubusercontent.com/6218999/68042055-3159c380-fc8f-11e9-90aa-fd8d1775e838.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in v2.3-head with UI index `latest-2.3`

The steps are the same. Now the gauge shows the correct percentile 

<img width="1446" alt="Screen Shot 2019-11-01 at 10 48 22 AM" src="https://user-images.githubusercontent.com/6218999/68044814-52bdae00-fc95-11e9-8afa-22b0dfd84b0a.png">
