### ISSUE TITLE
Scaling up instances

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2379]
1) Don't see scale up button
2) Have a stack with 4 services, when running `rancher-compose scale event-sink=2` all 4 services will restart after scaling targeted service as you can see at the image below... same effect with `racnher compose upgrade event-sink event-sink --scale 2`
<img width="1252" alt="screenshot 2015-10-20 14 33 37" src="https://cloud.githubusercontent.com/assets/3070298/10605903/ac492554-7737-11e5-8107-1ca1134fcf22.png">
3) When execute `rancher-compose --url=http://rancher/v1/projects/1a8 --access-key= --secret-key= -p mail -f "./run.mail.compose.yml" -r "./stacks/mail/rancher-compose.yml" up -d` it doesn't use my rancher-compose file and create stack with default scale=1. If i provide nonexistent file to `-r` option command will not fail.
4) Why not to add --pull option to `up` command? I just pushed new version of same image with same name and would like to recreate stack without using `io.rancher.container.pull_image: always`

rancher-composer 0.4.3
rancher-server v0.42.0-rc4

**Comment by deniseschannon** [comment]
1. In the most recent release, the scale up button disappeared. https://github.com/rancher/rancher/issues/2349
2. When I do `rancher-compose -p stackname scale testservice=3`, I only see my `testservice` scaling up. None of my other ones. Could you share your docker-compose.yml and rancher-compose.yml? 
3. The `-r` option is just trying to find your file, since rancher-compose.yml is optional, if it can't find it, it'll just use a scale of 5. I have no issues putting in my file at a different location. It sounds like your location is incorrect. Can you try a `cat stacks/mail/rancher-compose.yml` from the command line that you ran your `rancher-compose` commands to ensure it's actually there?
4. We have a `rancher-compose pull` command that will pull new images to all hosts. Since people will typically need the `--pull` during an upgrade, it exists as an option for `rancher-compose upgrade --pull`. I have added an enhancement request for `rancher-compose up --pull`. https://github.com/rancher/rancher/issues/2382

**Comment by vincent99** [comment]
For 3, if you explicitly specify a file and it doesn't exist it should probably bail...

**Comment by deniseschannon** [comment]
For 3, I created https://github.com/rancher/rancher/issues/2402

**Comment by ndelitski** [comment]
@deniseschannon For 3 i tried `cat ./stacks/mail/rancher-compose.yml` and all ok, maybe the command does not expect a file path as a parameter but only filename?

**Comment by deniseschannon** [comment]
@ndelitski Yes, I believe it's looking for an alternative filename, not a file path that contains a `rancher-compose.yml` file. So trying `./stacks/mail/rancher-compose.yml` would probably work in your situation. 

Based on the `rancher-compose --help`

```
--rancher-file, -r 			Specify an alternate Rancher compose file (default: rancher-compose.yml)
```

It seems to indicate file name vs. path.

**Comment by deniseschannon** [comment]
Reviewing what you have remaining open (#2), are you still having issues with scaling up services using rancher-compose?

**Comment by ndelitski** [comment]
@deniseschannon nope, maybe the issue was due to quotes around the path, thx! currently absolute and relative paths are working
