### ISSUE TITLE
Updating custom cluster created with RKE template disables cluster monitoring

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#23795]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an RKE template using default options, but allow override for Kubernetes version.
2. Create a new custom cluster using the RKE template created in step 1. Use default options.
3. Add a worker/cp/etcd node to the cluster.
4. In the UI, go to Tools -> Monitoring and enable cluster monitoring.
5. Wait a few minutes and confirm cluster monitoring is enabled and showing graphs/metrics.
6. Edit the cluster in the UI and change the Kubernetes version from v1.15.5-rancher1-2 to v1.16.2-rancher1-1. Click the Save button.

**Result:**
The monitoring graphs and metrics are gone. Cluster monitoring is disabled and turned off.

Expectation is that upgrading Kubernetes will not turn off cluster monitoring. This is likely happening because the RKE template's YAML has enableClusterMonitoring: false. However, the end user would never be aware of this and the fact that user is allowed to enable it, then it gets disabled is not a good user experience.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
aws vm t3a.medium
- Kubernetes version (use `kubectl version`):
after update:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:38:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd87f
  Built:            Wed Jul 17 17:48:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by dmlabs** [comment]
+1
We experience the same behavior in our environment.

**Comment by pirminjanka** [comment]
+1

**Comment by deniseschannon** [comment]
@prachidamle When looking at this, we should also review the other use cases that might fall into this scenario. Is cluster monitoring the only option that could be enabled?

**Comment by prachidamle** [comment]
@deniseschannon I think this problem is applicable to the following flags that can be set in the RKE template as they are part of the clusterSpec:
```
enable_cluster_alerting: false
enable_cluster_monitoring: false
```

This is how these flags work **even for a cluster which is NOT created via a template**:

- cluster.yml: enable_cluster_monitoring: false. 
--  When the cluster is provisioned with this flag as false, no monitoring pods are deployed.
--  But User can go and enable monitoring for that cluster at a later point in time. Once they enable monitoring, this flag is then set to true in the clusterSpec.

- cluster.yml: enable_cluster_monitoring: true. 
--  When the cluster is provisioned with this flag as true, monitoring pods are deployed by Rancher when the cluster is provisioned.

- cluster.yml: enable_cluster_alerting: false. 
--  When the cluster is provisioned with this flag as false, it indicates no alerts are configured yet for the cluster.
--  But User can go and add alerts/notifier for that cluster at a later point in time. Once they do so monitoring, this flag is then set to true in the clusterSpec.

- cluster.yml: enable_cluster_alerting: true. 
--  When the cluster is provisioned with this flag as true, it actually does not mean that Rancher adds any alerts. 


Thus it looks like these flags are more for indicating if a given cluster does have monitoring or alerts enabled. Setting them false does not actually control the user's ability to enable monitoring/alerts on a cluster later.
However re-setting the flag enable_cluster_monitoring to false for a cluster  results in monitoring disabled. So the design of these flags is confusing.

So @cloudnautique @deniseschannon 
 a) Fix so that these flags control whether user can turn on monitoring/alerts on a cluster. It means if they are set as false, user will not be able to enable monitoring or add alerts on a cluster. 

This way we wont have a cluster with a template that says enable_cluster_monitoring:false, but a cluster with monitoring enabled later.

This approach however does not solve the problem for clusters already in this state.

OR

b) We deny updating a cluster to a templateRevision that would set these flags off by checking the cluster's Spec.

**Comment by deniseschannon** [comment]
@prachidamle spoke with @cloudnautique 

Let's go with option b, where a template can turn on monitoring, but it will not disable it from the template. 

We will document that enabling monitoring in the RKE template will give you the ability to turn on monitoring as part of the RKE template but does not enforce whether or not monitoring can be turned on/off in the cluster. 

We will consider adding in functionality to give users an option to also enforce whether or not monitoring can be turned on/off by a RKE template.

**Comment by prachidamle** [comment]
This is the fix for now:
Usecase 1) 
- Create an RKE template revision R1 with `enable_cluster_monitoring:true` 
- When a cluster is launched using this template revision, Rancher will deploy the monitoring components.

- Now if another revision R2 is made available for this RKE template, with `enable_cluster_monitoring:false`
- The user will not be able to upgrade the cluster to this revision R2 since it will disable the cluster monitoring.

Usecase 2)
- Create an RKE template revision R1 with `enable_cluster_monitoring:false` 
- When a cluster is launched using this template revision, Rancher will NOT deploy the monitoring components.
- Suppose User enables monitoring on the cluster after it is provisioned and is `active`.

- Now if another revision R2 is made available for this RKE template, with `enable_cluster_monitoring:false`
- The user will not be able to upgrade the cluster to this revision R2 since it will disable the cluster monitoring.

Same cases also apply to the `enable_cluster_alerting` flag.

**Comment by soumyalj** [comment]
Editing and updating K8s version use case mentioned in the issue needs to be handled.

**Comment by prachidamle** [comment]
This is the fix redone:
Usecase 1) 
- Create an RKE template revision R1 with `enable_cluster_monitoring:true` 
- When a cluster is launched using this template revision, Rancher will deploy the monitoring components.

- Now if another revision R2 is made available for this RKE template, with `enable_cluster_monitoring:false`
- The user  will be able to upgrade the cluster to this revision R2  but `enable_cluster_monitoring` flag from the template will be ignored and not applied to the cluster since it will disable the cluster monitoring. Rest all updates will go through.

Usecase 2)
- Create an RKE template revision R1 with `enable_cluster_monitoring:false` 
- When a cluster is launched using this template revision, Rancher will NOT deploy the monitoring components.
- Suppose User enables monitoring on the cluster after it is provisioned and is `active`.

- Now if another revision R2 is made available for this RKE template, with `enable_cluster_monitoring:false`
- The user will be able to upgrade the cluster to this revision R2  but `enable_cluster_monitoring` flag from the template will be ignored and not applied to the cluster since it will disable the cluster monitoring. Rest all updates will go through.

Same cases also apply to the `enable_cluster_alerting` flag.

Usecase 3)
- If the cluster is created from an RKE template having overrides set. 
- Enable monitoring on the cluster
- Upon editing the cluster to change the template overrides should not disable monitoring. Update should go through

cc @soumyalj @sangeethah

**Comment by soumyalj** [comment]
Tested with updated revision v2.3-head 
1. Use case 1 works as expected. Monitoring is retained after cluster update. 
<img width="426" alt="Screen Shot 2019-11-21 at 7 21 16 PM" src="https://user-images.githubusercontent.com/18536626/69395540-2db8cb80-0c94-11ea-8586-a888c75de8fd.png">

**Comment by soumyalj** [comment]
Tested with v2.3-head for alerts

Usecase 1)

1. Create an RKE template revision R1 with enable_cluster_alerting:true
2. When a cluster is launched using this template revision, in the API, enableClusterAlerting is set to true in the Applied spec and enableClusterAlerting is set to false at the cluster level initially
Once notifier is created and alerts are set, enableClusterAlerting is set to false at the cluster level in API
3. Create another revision R2 with enable_cluster_monitoring:false
The user will be able to upgrade the cluster to this revision R2 but enable_cluster_monitoring flag from the template will be ignored and not applied to the cluster since it will disable the cluster monitoring. Rest all updates will go through.

Usecase 2)

1. Create an RKE template revision R1 with enable_cluster_alerting: false
2. Create a cluster using R1.
3.Enable cluster level alerts by creating notifier and enabling the alerts. After this, enable_cluster_monitoring is set to true at the cluster level in the API
4. Create revision R2 with enable_cluster_alerting:false
The user will be able to upgrade the cluster to this revision R2 but enable_cluster_monitoring flag from the template will be ignored and not applied to the cluster since it will disable the cluster monitoring. Rest all updates will go through. enableClusterAlerting is set to true at the cluster level in API

Usecase 3)

1. Create rke template R1 having overrides set with enable_cluster_alerting:false
Enable alerts on the cluster. After enabling alerts, enableClusterAlerting is set to true at the cluster level in API
2. Edit the cluster and change the template overrides 
The enable_cluster_alerting is still set to true. Updates go through as expected

Usecase4)

Create rke template R1 having overrides set with enable_cluster_alerting:false
Add another revision R2 with enable_cluster_alerting:true
Upon editing the cluster to change to R2, alerting is turned on . enableClusterAlerting is set to true at the cluster level in API [Note in this case, setting the alerts was not necessary, but the alerting got set in the API at the cluster level]

**Comment by disaster37** [comment]
Hi,

I use rancher v2.4.5 with fresh install. I am on usecase 2 that you describe and it doesn't work as expected.
I deploy cluster with rke template and enable_cluster_monitoring:false. The after cluster desployed, I enable monitoring from tools -> monitoring. Then If I update the cluster and upgrade rke template revision or stay on same revision but change user / role. Monitoring is dissabled.
