### ISSUE TITLE
Allow copy/paste env vars in Firefox

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#238]
When creating containers with a lot of env variables... would be nice to be able to paste them in.

The workflow here being creating multiple containers with identical configuration on separate hosts.

**Comment by vincent99** [comment]
In rancherio/ui#154 you can paste one or more lines of `name=value` pairs into any of the environment variable name fields.
  - All keys and values are trimmed on both sides.  Empty lines are ignored.
  - If there is an existing value for a `name` in the paste, the old value is overwritten
  - Any empty name+value pairs that happened to be in the list before are removed (because...reasons...)
  - A line with just a key (no "=") is allowed.  If the entire paste has no "=" then it is not a special paste and the string just replaces the `name` you pasted into.

**Comment by tfiduccia** [comment]
v0.20.2
Failed - does not work in Firefox.  Works in Chrome and Safari

**Comment by vincent99** [comment]
Fixed for firefox..

**Comment by tfiduccia** [comment]
Version - master 3/9
Verified fixed
