### ISSUE TITLE
Detect Edge browser and suggest a different browser

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23909]

**Comment by codyrancher** [comment]
@tfiduccia when you have some time would you mind letting me know what you'd like to see for UX? After a quick discussion with Wes I was thinking something along the lines of a full width dismissible banner at the top of the page that we keep hidden for subsequent page loads if the user ever dismisses it.

**Comment by tfiduccia** [comment]
@codyrancher - This should really just show up on login and not in the application itself.  It should be something that we force people who are in IE to see & purposely close.  So once login happens if someone is on IE we should bring up a window or something. There can be a checkbox on the modal to not show again for that user.

**Comment by codyrancher** [comment]
@tfiduccia 
How about something like 
![Screen Shot 2019-11-06 at 12 21 28 PM](https://user-images.githubusercontent.com/55104481/68330162-fccf7880-008f-11ea-87df-9aa55dcd02ad.png)

**Comment by tfiduccia** [comment]
@codyrancher - Yep that looks great to me.

**Comment by codyrancher** [comment]
@deniseschannon what actually sparked this issue? I was just finishing up the implementation with the IE detection and while testing a came across this:
![Screen Shot 2019-11-06 at 3 36 42 PM](https://user-images.githubusercontent.com/55104481/68344075-6d37c300-00ab-11ea-8291-f3faf12241a5.png)

The above makes me think that we need to address this issue differently.

**Comment by codyrancher** [comment]
It turns out we just wanted to detect Edge browsers as we were already detecting Internet Explorer browsers. I've updated the title to reflect that.

This will only detect EdgeHTML based browsers as the mobile and chromium based versions should be supported.

**Comment by codyrancher** [comment]
![ie](https://user-images.githubusercontent.com/55104481/68427141-ce709c80-0166-11ea-9ee7-fd221b51f7db.gif)

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by davidnuzik** [comment]
Version: v2.3-head (11/11/19 `5187fce31`) (single-node)

I launched Edge on my Windows 10 Pro machine and successfully got redirected to the /ie page:
![image](https://user-images.githubusercontent.com/45179589/68612749-798c9900-047a-11ea-841b-10e3db16c4da.png)

I then launched IE11 on the same machine and also go the same result.
However, the site actually failed to load in this case:
![image](https://user-images.githubusercontent.com/45179589/68612918-d8eaa900-047a-11ea-8cad-e397f62a5635.png)

**Since we don't support IE11 I think this is okay. I didn't create a bug. If I should please notify me.**

I then tested on my Laptop on Debian Buster with Chromium using dev tools (much like Cody did here https://github.com/rancher/rancher/issues/23909#issuecomment-551264383 )

I got the same result. I get redirected to the /ie page each time.

I made sure when I set the user-agent to the (Chromium) versions of Edge that I DON'T get redirected to the /ie page.

I spot checked various other user-agents and ensured I do not get redirected to /ie

I didn't identify any other issues exept for IE11 not loading.
