### ISSUE TITLE
[forwardport] Detect Edge browser and suggest a different browser

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23971]
Forwardport of rancher/rancher#23909

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by izaac** [comment]
rancher version: `master-head` (11/20/2019) `ebe495938` (Single node)
I've tested in Windows 10 with Microsoft Edge browser versions 18 and 15.

Both got me redirected to `/ie` and shown me the `Sorry, IE and Edge are not supported.` message.

IE11 On Windows 8.1 rendered errors in the Web Console. It seems this is a known issue: #24028

Microsoft Edge Beta for Mac OS X is able to open Rancher UI because it is based on Chromium.

Closing as fixed.
