### ISSUE TITLE
Vsphere Template - Creation method defaults to "RancherOS ISO(Deprecated)" 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#24060]
Rancher server version - `v2.3.3-rc1`

Steps to reproduce the problem:
Create node Template page for Vsphere.

Notice that the  Creation method defaults to "RancherOS ISO(Deprecated)" .

Question - Do we need "RancherOS ISO" to be marked Deprecated ? If we do want this to be deprecated , then we should not be defaulting to an option that is deprecated.

**Comment by cjellick** [comment]
my 2 cents: yes mark deprecated and it should not be the default

**Comment by cloudnautique** [comment]
Should not be the default, mark as deprecated.

**Comment by deniseschannon** [comment]
@cloudnautique Which option should be the default? 

<img width="993" alt="Screen Shot 2019-11-13 at 10 22 53 AM" src="https://user-images.githubusercontent.com/11410997/68792135-9dc5b280-05ff-11ea-8411-590369ff84e1.png">

For RancherOS, it sounds like we want to move  the text from `RancherOS ISO (Deprecated)` to  `Install from boot2docker ISO (Legacy)`

<img width="990" alt="Screen Shot 2019-11-13 at 10 23 02 AM" src="https://user-images.githubusercontent.com/11410997/68792129-9bfbef00-05ff-11ea-80d1-f07dba278723.png">

**Comment by cloudnautique** [comment]
@deniseschannon the default shoud be be `Deploy from template: Content Library`.

**Comment by codyrancher** [comment]
Switched this back to me even though the default was actually being set by the backend. After speaking with @luthermonson it looks like there's going to be less unknowns if we make this change on the front end.

**Comment by cloudnautique** [comment]
@codyrancher, Sorry, Luther pointed out Data Center... not what I originally set. 

@luthermonson why isnt the backend doing this? what would the Terraform provider get for instance?

**Comment by luthermonson** [comment]
the flag on the cli was added to let you toggle which creation method you would choose. the default is "legacy" as you could also omit the flag and still run it so that creation path is still the b2d iso (we had called it default at one point too). if i change the creation method default from "legacy" to "template" then a node template that does not have this creationType set pre this fix will stop working. the upgrade process will set the default too meaning that upgrading from pre 2.3.2 to 2.3.3 would autoset the creationType to "template" breaking an old node template that used the iso.

**Comment by sangeethah** [comment]
Tested with latest `v2.3-head`

<img width="773" alt="Screen Shot 2019-11-14 at 11 01 32 AM" src="https://user-images.githubusercontent.com/4266958/68897096-a8587880-06e1-11ea-84f3-db8816c18f61.png">
