### ISSUE TITLE
ssh command for `rancher-compose`

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2413]
Would be awesome to have an `ssh/exec` command in `rancher-compose` to connect to any container from command line. Something like `rancher-compose ssh <container-name_index | container_ip >` or `rancher-compose exec <container> <command>`. To have this feature in UI is really cool but when you have to constantly debugging multiple containers with browser is quite painfull

**Comment by deniseschannon** [comment]
Honestly, I'm not sure if this is even feasible, but I've added it as a feature request. :)

**Comment by pierreozoux** [comment]
@deniseschannon everything is possible! That's why being a hacker is like being a magician :)

Indeed it would be awesome. The WebUI is quiet poor to execute commands on a container.
I would say `exec` is better than `ssh`, because no ssh daemon will be running, and this will use `docker exec` api behind the scene.

For me this is a major pain point.

To convince you, here is a great talk, from one of the smartest engineer on earth!
https://www.youtube.com/watch?v=sYQ8j02wbCY

**Comment by deniseschannon** [comment]
Instead of adding this into Rancher Compose, we recommend using the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which supports `rancher exec`.
