### ISSUE TITLE
Values stuck in loading state when creating Node Template using vSphere provider with standalone ESXi server

### ISSUE THREAD

**Issue by kevinvermeersch** [rancher/rancher#24201]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Add Node Template using vSphere provider

**Result:**

Select fields stay in a "loading" state for unsupported values on a standalone ESXi server

<img width="1408" alt="Screenshot 2019-11-22 at 10 33 34" src="https://user-images.githubusercontent.com/2557662/69416445-ecb5cb00-0d16-11ea-9525-86014dfd7760.png">

**Other details that may be helpful:**

Api request error on /meta/vsphere/custom-attributes?cloudCredentialId=xxx
```
{"type":"error","status":"422","message":"InvalidBodyContent: product/version specific feature not supported by target"}
```

**Environment information**
- Standalone ESXi server
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.3-head
- Installation option (single install/HA): single install

**Comment by axi92** [comment]
We have the exact same issue!

**Comment by dwimberger** [comment]
> We have the exact same issue!

**Environment information**
VSphere with vCenter server and Cluster v6.7

**Rancher version** 
rancher/rancher:v2.3.3 (stable and latest)

**Installation option**
HA on RKE Cluster

**Other details that may be helpful**

Requests like `https://xxx.xxx.xxx/meta/vsphere/tag-categories?cloudCredentialId=cattle-global-data:cc-nphnv` may return `null` values, which in turn causes the `content.filter` methods in the UI handlers to generate exceptions.

Code References:
[component.js](https://github.com/rancher/ui/blob/4768ca91557b6762aface80b065bc2c140849020/lib/nodes/addon/components/driver-vmwarevsphere/component.js)

Exceptions:
`component.js:153 Uncaught (in promise) TypeError: e.filter is not a function
    at n.tagContentFilter (component.js:153)`

Returned data:
`{"data":null}`


The cause for the `null` value seems to be an incomplete login (although the credentials are correct and values are read for other fields).

`{type: "error", status: "422",…}
message: "InvalidBodyContent: ServerFaultCode: Cannot complete login due to an incorrect user name or password."
status: "422"
type: "error"`


**Thoughts**
It's hard to reproduce with all the same errors, as it seems that there is a timing dependent behavior (sometimes one field loads, another one doesn't or a random set of fields works and other's don't. 
=> Maybe there is a concurrency issue somewhere with the credential and the number of requests fired at different moments?

There are no Tags in our Installation:
=> Maybe these edge cases were not considered?

The UI behavior after these exceptions is erratic at best.
=> Maybe it would be good to safeguard these edge cases or error cases in the UI by checking the parameter validity `(!=null)`  of the functions before using accesors and functions.
