### ISSUE TITLE
Registry credential scoped to a single namespace cannot be cloned

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#24231]
rancher/rancher:v2.3-head
rancher/rancher:v2.3.2

Cloning a registry credential secret which is scoped to a single namespace fails with error `No namespace specified`

Actual:
* Create a cluster
* In a project, create a Registry Credential secret scoped to a single namespace
* Clone the created registry credential
* On saving, an error is presented: `No namespace specified`

Expected:
* Registry credential is cloned

--

* No API calls are made by UI when attempting to save.
* Original object contains the namespaceId
* Registry credentials available to all namespaces can be cloned successfully
* Attempted with global admin user and standard user/project owner

![Screen Shot 2019-11-25 at 9.59.57 AM.png](https://zube.io/files/rancher/7507d80484ce6604882ff1985c3c4c87-screen-shot-2019-11-25-at-9-59-57-am.png)

**Comment by westlywright** [comment]
Available in `latest2` and `latest-2.3`

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.2`
Steps
Create a cluster.
In a project, create a Registry Credential secret scoped to a single namespace.
Clone the created registry credential.
On saving an error is presented: `No namespace specified`
![Screen Shot 2019-12-13 at 8 27 26 AM](https://user-images.githubusercontent.com/57409052/70812701-59a40a00-1d85-11ea-9834-7f2ae1427bfc.png)

The bug fix is verified with Rancher server `rancher\rancher:v2.3-head` `version 96f961bc5`
Clone is created successfully.
![Screen Shot 2019-12-13 at 8 46 44 AM](https://user-images.githubusercontent.com/57409052/70812712-5f99eb00-1d85-11ea-98f9-7e1d3710bade.png)
![Screen Shot 2019-12-13 at 8 46 51 AM](https://user-images.githubusercontent.com/57409052/70812747-704a6100-1d85-11ea-91ed-26850710cd56.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 624460445`
Clone is created successfully
![Screen Shot 2019-12-13 at 8 38 05 AM](https://user-images.githubusercontent.com/57409052/70812752-73455180-1d85-11ea-9034-fc10376d9bb7.png)
