### ISSUE TITLE
Bug: nodes will not delete if aws key has been deleted/disabled even after updating nodetemplate.

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#24234]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create an ec2 cluster with some nodes
2) Deactivate/disable/delete AWS keys on AWS
3) Create new AWS keys on AWS
4) Update node template with new AWS keys
5) Attempt to delete node created before AWS keys were updated

**Result:**
Node will appear to be deleted but is actually still running in AWS

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8
- Installation option (single install/HA): HA

**Comment by askldjd** [comment]
Just to provide a bit more information. Our Rancher node template were created before the existence of Cloud Credential. So the AWS access_key were directly embedded in the template. Here's the full sequence.

1. Deactivate existing AWS key
1. Create a new Cloud Credential with a new AWS key
1. Update each template to use the new Cloud Credential from step 2.
1. Delete a node that was created using the deactivated key. Notice that the node is never deleted in AWS. There is no error and the failure is silent. However, the node pool will immediately recreate the a new node using the new Cloud Credential.
1. Delete the newly created node, confirm that the node is actually deleted in AWS.

It seems that the AWS key that was used to create the node stays in the lifecycle of the node. Even if the node template is updated, it will not take into effect until the next lifecycle. This is very problematic for production because we rotate AWS keys often. As keys rotate, we are affecting stability of production because traffics are routed through these orphaned nodes.

**Comment by askldjd** [comment]
Another update:

It turns out that it doesn't matter if you are using Access Keys in Node Template or Cloud Credential. The key that Rancher uses to create the node will always be the same key it uses to destroy the node. So whenever any AWS credentials gets deactivated, Rancher will lose the ability to delete all the nodes created by the deactivated key.

**Comment by aaronRancher** [comment]
Able to reproduce bug using steps above in `v2.2.8` and `v2.3.3`.

**Comment by dramich** [comment]
Master pr: https://github.com/rancher/rancher/pull/24435
2.3 pr: https://github.com/rancher/rancher/pull/24490

**Comment by sangeethah** [comment]
@dramich Reopening this issue to get a fix in `2.3-release` branch.

**Comment by aaronRancher** [comment]
Unable to validate bug fix in `rancher\rancher:master-head` `version f3fbe1449`

Tested using worker node:
```
2019/12/10 20:15:10 [WARNING] [node-controller-rancher-machine] Error removing host "aaron-w1": unable to terminate instance: AuthFailure: AWS was not able to validate the provided access credentials
2019/12/10 20:15:10 [WARNING] [node-controller-rancher-machine] 	status code: 401, request id: 1900916e-fd92-47b3-a9fb-bc584993f60d
2019/12/10 20:15:10 [WARNING] [node-controller-rancher-machine] AuthFailure: AWS was not able to validate the provided access credentials
2019/12/10 20:15:10 [WARNING] [node-controller-rancher-machine] 	status code: 401, request id: 559dd990-3170-4213-a912-3d2cfb4b59a3
```

**Comment by aaronRancher** [comment]
Steps:
Create an EC2 template and provision a cluster with multiple nodes.
Disable the AWS key used to create the template.
Create a new AWS key.
Update the EC2 template with the new active key in Rancher.
Attempt to delete a node created before AWS keys were updated.

**Comment by aaronRancher** [comment]
There are 2 ways to test this.
- Change the existing cloud credential to point to the new AWS key.
The node pool has become unreachable
- Create a new cloud credential with new keys and then point the existing template to use the new cloud credential.

In both situations, an error is seen signifying that the nodepool is missing.
```
[ERROR] NodeController c-db2fr/m-bgh8d [user-node-remove] failed with : nodes.management.cattle.io "m-bgh8d" not found
```

We do provide a message in node template edit to warn of such occurrences.
![screen_shot_2019-12-10_at_2 07 26_pm](https://user-images.githubusercontent.com/57409052/70575228-474a8600-1b63-11ea-9237-65c160a71aba.png)

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/24559

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 624460445`

Both scenario 1 and scenario 2 were tested.
![Screen Shot 2019-12-12 at 1 06 43 PM](https://user-images.githubusercontent.com/57409052/70745465-11cba700-1ce1-11ea-80ce-ec08e0cc6113.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.3-head` `version 5175de351`

Both scenario 1 and scenario 2 were tested.
![Screen Shot 2019-12-12 at 3 28 53 PM](https://user-images.githubusercontent.com/57409052/70754658-02eeef80-1cf5-11ea-8e67-06f6c617e14e.png)
