### ISSUE TITLE
[UI] UI API adds spaces to principal ID when generating CURL request

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#24261]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. setup auth
2. go to create a globalrolebinding in API UI
3. reference a group principal id
4. select "Show Request"

**Result:**
Generated curl request contains groupPrincipalId with added spaces after commas. This binding now references an improper id.

__Example:__
`curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \ -X POST \ -H 'Accept: application/json' \ -H 'Content-Type: application/json' \ -d '{"globalRoleId":"admin", "groupPrincipalId":"activedirectory_group://CN=testgroup1, CN=Users, DC=testad, DC=rancher, DC=io", "name":""}' \ 'rancherurl'`

**Comment by deniseschannon** [comment]
@westlywright not sure how easy this fix is but could you take a look?

**Comment by vincent99** [comment]
https://github.com/rancher/api-ui/commit/e99b91c09bcf2c5158e1076ad90951fd38a796b9#diff-97615e2c7681c9f83ca38ef214144a16L1030

Need to update server to point to API-UI 1.1.9

**Comment by aaronRancher** [comment]
The bug is reproduced in `rancher\rancher:v2.3.3`

Steps:
Setup auth
Navigate to `/v3/globalrolebindings`
Go to create a globalrolebinding in API UI  
Reference a group principal id
Select "Show Request"

Result:
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"labels":{"groupPrincipalId":"activedirectory_group://CN=testgroup1, CN=Users, DC=testad, DC=rancher, DC=io"}, "name":""}' \
'https://157.245.116.98/v3/globalrolebindings'
```

The bug fix is validated with Rancher server `rancher\rancher:master-head` `version 6717e73d1`

groupPrincipalId can now be referenced within the UI.
![Screen Shot 2019-12-11 at 10 18 54 AM](https://user-images.githubusercontent.com/57409052/70644281-f3da4580-1bff-11ea-8ccd-b7d59e44c928.png)

The curl request no longer contains groupPrincipalId.
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
'https://167.172.27.172/v3/globalrolebindings'
```
