### ISSUE TITLE
Rancher agents behind NAT?

### ISSUE THREAD

**Issue by miko** [rancher/rancher#2427]
Hello,
I have following setup:
public server A.A.A.A with rancher server and rancher agent, then two home computers on 192.168.1.1 and 192.168.1.2 (home LAN), both behind a NAT (with my local home network having public address B.B.B.B) and both with rancher agents.
I have succesfully registered all 3 hosts to the rancher server, but both my home computers are visible with their public address B.B.B.B. I guess this is the reason why there are no communications between containers on my computers, as A.A.A.A cannot ping B.B.B.B (its my router). I guess if I had only one computer, I could have port forwarding of port 500 and 4500 on my router and that could work. How can I run more than one computers (rancher agents) on my LAN behind a NAT? Is it possible? I am using rancher agent v0.8.2, rancher server v0.41.0, cattle v0.100.0

I do notice outgoing UDP packets from my laptop in LAN to A.A.A.A port 500, but no return packets.
Is it a problem with my router configuration?

**Comment by vincent99** [comment]
Hosts communicate with each other using the IP that is shown on each host.  That is detected when they register, which would both be your public WAN IP in this case, so they can't talk to each other.  You can override the registered IP with [the CATTLE_AGENT_IP variable](http://docs.rancher.com/rancher/faqs/hosts/#how-does-the-host-determine-ip-address-and-how-can-i-change-it), and if you set them all to 192.168.1.x the hosts will be able to communicate with each other.  But you will have different problems that may or may not affect you, like the external-dns providers will create DNS records for 192.168 addresses instead of the public IP.  And if you have other hosts outside the NAT they will not be able to communicate with the ones in it.

**Comment by lgleim** [comment]
Is this still not possible in 2017? I think it is a pretty common usage scenario to have e.g. build slaves behind a NAT and it does not appear conceptually hard to place all Rancher Hosts in a VPN so they share addressable private IP addresses with each other - independent of the container network...

**Comment by leodotcloud** [comment]
@lgleim If the hosts are already part of VPN and have reachable private IP addresses, you can use those IP addresses to register the hosts in the rancher/server. The IP addresses need not be "public"(some of our customers use private data centers, VPCs in AWS, etc), but the different hosts need to be reachable via unique IP addresses.

**Comment by lgleim** [comment]
@leodotcloud Thanks for the feedback! I am aware that it is possible to set up such a configuration, however any host that is not part of the VPN cannot connect to any of the host's services within the VPN. I simply cannot believe that this has still not been resolved as part of Rancher since I do not see any kind of downside that would explain not having this type of configuration by default.

**Comment by tuwid** [comment]
I have all my nodes connected through a VPN and still make it work, there is something wrong in the swarm joing part as I've specified the VPN's internal IP but the join command still points to the public IP.. any ideas?

**Comment by ElPsyCongro** [comment]
Hi I have a rancher-server on a local server and what I'm trying to do is add my AWS host with his public IP but they can reach my local server only by VPN connection. (When I execute the command generated by the UI of Rancher to add a host the detected cattle agent IP is his IP of the VPN even when use the public IP of the host for cattle agent IP).
Every host has a OpenVPN client that is running on background providing a tun0 interface, I have a VPN server on AWS that allows connection between clients and redirect all the traffic through the VPN. Also my local server is connected to that VPN.
The AWS hosts get added but when the second host is added the health check stays on initializing and there is no connection between hosts. Any idea of what is happening? What I'm doing is wrong?

**Comment by leodotcloud** [comment]
@ElPsyCongro Did you try using CATTLE_AGENT_IP to override?

**Comment by ElPsyCongro** [comment]
@leodotcloud Yes I use the Custom method in where you need to specify the CATTLE_AGENT_IP I think, I opened an issue for more details. If you can check it I would appreciate it.
https://github.com/rancher/rancher/issues/10148
