### ISSUE TITLE
Translation not found

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#24300]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`global-admin.clusters.index`|

<img width="1680" alt="Знімок екрана 2019-11-27 о 22 29 25" src="https://user-images.githubusercontent.com/5846351/69757364-804b2980-1165-11ea-931e-e84c1d5340ba.png">

<img width="1329" alt="Знімок екрана 2019-11-27 о 22 30 55" src="https://user-images.githubusercontent.com/5846351/69757461-bd172080-1165-11ea-8967-617b0a0065b1.png">

**Comment by loganhz** [comment]
It's easy to reproduce by switching to `uk-ua` language. Not sure why it will not fallback to English. cc @westlywright

**Comment by westlywright** [comment]
@loganhz its because there were new translations path's added for this key, a new `label` child key was added which causes this bug. Basically if the key path does not terminate at that level is used to it doesn't know how to fallback. I've fixed that and also have a PR open for syncing the translations from crowdin.

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.3`

Change language to `ru-ru` language.
![Screen Shot 2019-12-10 at 2 55 05 PM](https://user-images.githubusercontent.com/57409052/70573224-bec9e680-1b5e-11ea-95e2-db946bc44d47.png)

In Rancher server `rancher\rancher:master-head` `version f3fbe1449`
The fix does not work for `zh-hant`
![Screen Shot 2019-12-10 at 3 04 51 PM](https://user-images.githubusercontent.com/57409052/70573230-c5585e00-1b5e-11ea-9dda-ee0dfedb85fd.png)

**Comment by westlywright** [comment]
@aaronRancher This was my bad, we typically no not maintain translations outside of the `en-us` & `zh-hans`, other translations are maintained by the community in crowdin. I made this fix as it was fast and easy but this is exactly why we don't take care of core maintained languages, it opens a large can of worms which we lack the time to wrangle. In the future we should only open and validate issues for translations in the maintained languages. Regardless I've made a fix to the zh-hant file as well since it was pretty easy and it should be available in `latest2` shortly.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 88fcc20ad`

The fix works with `zh-hant`:
![Screen Shot 2020-01-14 at 11 40 23 AM](https://user-images.githubusercontent.com/57409052/72372298-4f966380-36c3-11ea-92c1-565be4f1b6e0.png)
The fix works with `uk-ua`:
![Screen Shot 2020-01-14 at 11 41 19 AM](https://user-images.githubusercontent.com/57409052/72372317-57560800-36c3-11ea-86c0-c68fe15d2f07.png)
