### ISSUE TITLE
Rancher 2.3.3 update can't create new node template to use existing vsphere template

### ISSUE THREAD

**Issue by bevank** [rancher/rancher#24315]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG  

**Steps to reproduce (least amount of steps as possible):**

- upgraded from Rancher 2.3.2 to 2.3.3 
- old templates still work 
- new templates cant find resource pool, same resource pool from old template
      **_Please select a new value. The following is no longer valid: "/SAC3/host/DES/Resources/bktest"_**
- created node template pointing at "deploy from template: data center" gets the following error 
      _**[node-controller] failed with : Error creating machine: Error in driver during machine creation: vm 'SAC3/vm/DES//SAC3/vm/DES/Templates/rhel77_k8_d1934_overlay2_nov28' not found**_

**Result:**
looks like the vsphere targeting is not working for resource pools and it looks like its duplicating the folder location for locating the template

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`): 

```
the cluster does not create because of the node templates not working correctly 
```

- Docker version (use `docker version`):

```
N/A
```

**Comment by soostdijck** [comment]
Just want to say I'm having the same issue. If more info is needed I'm happy to help troubleshoot.

**Comment by fredbeltrao** [comment]
Same issue when cloning from an existing virtual machine. Rancher appears to duplicate the path when looking for the artifact on vSphere:

`2019/11/29 20:32:34 [INFO] [node-controller-docker-machine] (master-1) Cloning VM from VM or Template: /DC-TRE/vm/rancher/RancherOS...
2019/11/29 20:32:34 [INFO] [node-controller-docker-machine] (master-1) Finding datastore /DC-TRE/datastore/VV_VMWARE_EVABACKUP_FC_RD5
2019/11/29 20:32:34 [INFO] Generating and uploading node config worker-1
2019/11/29 20:32:34 [ERROR] NodeController c-srqrn/m-flgbj [node-controller] failed with : Error creating machine: Error in driver during machine creation: vm 'DC-TRE/vm/rancher//DC-TRE/vm/rancher/RancherOS' not found
`

**Comment by bmdepesa** [comment]
@bevank 

```
new templates cant find resource pool, same resource pool from old template
Please select a new value. The following is no longer valid: "/SAC3/host/DES/Resources/bktest"
```

Does your resource pool show up in the dropdown menu when creating the new node template? 
<img width="724" alt="Screen Shot 2019-12-02 at 9 58 34 AM" src="https://user-images.githubusercontent.com/21316915/69978847-5c337380-14ea-11ea-896b-677755d4b22a.png">

**Comment by bevank** [comment]
@bmdepesa 

The list is populated with all the resource pools available to the account and no matter which one I select I get the same error "The following is no longer valid: ...", we are in a multi-cluster configuration on Vsphere 6.5 and the service account we are using has admin access to the target cluster

**Comment by soostdijck** [comment]
@bmdepesa would it be better to split this issue into two, because I (and perhaps @fredbeltrao) only have the "second" error `[ERROR] NodeController c-pv2gm/m-lghlx [node-controller] failed with : Error creating machine: Error in driver during machine creation: vm 'cluster/vm/rancher//cluster/vm/rancher/rancher-k3os-template' not found`

**Comment by ldibello** [comment]
Ive got same issue, duplicated path, installation not foun my template. Im using VsPhere 6.7 u3a baremetal. I even tried with fulla access user to test it.

**Comment by fredbeltrao** [comment]
> @bmdepesa would it be better to split this issue into two, because I (and perhaps @fredbeltrao) only have the "second" error `[ERROR] NodeController c-pv2gm/m-lghlx [node-controller] failed with : Error creating machine: Error in driver during machine creation: vm 'cluster/vm/rancher//cluster/vm/rancher/rancher-k3os-template' not found`

In my case, I'm not using any Resource Pool in VSphere. I've tried to create a node from cloning a VM and from template. Both cases didn't work because Rancher can't found them.

**Comment by espigle** [comment]
I am experiencing the exact same problems as the original poster. After upgrade to 2.3.3, templates are broke if I update them. Old ones that I don't update still work. I see the same problems as documented up top. I can provide any details as needed. Thankfully I discovered this on a test cluster, but I have definitely found that as soon as a Rancher node template is updated, it no longer works.

**Comment by hsartoris-bard** [comment]
Experiencing path duplication as well; also happy to help debug.

`[node-controller] failed with : Error creating machine: Error in driver during machine creation: vm 'Datacenter/vm/k8s-vms//Datacenter/vm/Templates/photon-hw11-3.0-9355405' not found`

**Comment by hsartoris-bard** [comment]
Some info:
https://github.com/rancher/machine/blob/cdf20ea56b6395f97a1665da65afa1729615461f/drivers/vmwarevsphere/vsphere.go#L342
Probably content library creation doesn't work because it's matching on "libary", not "library". This would explain why, after switching my node template to Content Library and back, but without unsetting the ContentLibrary element, it suddenly attempted to clone from a content library, although it hadn't done so when I actually had the template set to content library.

In any case, it gets past that, which means the error is scoped to createFromVmName; we know it would pass the precreate check in vsphere.go because the line that should check it (https://github.com/rancher/machine/blob/cdf20ea56b6395f97a1665da65afa1729615461f/drivers/vmwarevsphere/vsphere.go#L274) is checking for "clone" rather than "vm" source types.

Thus, when fetchVM is called [here](https://github.com/rancher/machine/blob/cdf20ea56b6395f97a1665da65afa1729615461f/drivers/vmwarevsphere/create.go#L298), it's the first time, and we finally get to [this line](https://github.com/rancher/machine/blob/cdf20ea56b6395f97a1665da65afa1729615461f/drivers/vmwarevsphere/vm.go#L85), where the driver, seeing that Folder is set, erroneously concatenates d.Folder with the template/vm location, not accounting for the location now being a full path.

Even were we to get past that, we'd run smack into the same issue [later](https://github.com/rancher/machine/blob/cdf20ea56b6395f97a1665da65afa1729615461f/drivers/vmwarevsphere/create.go#L309), where the full-path folder is concatenated with a prefix from govmomi.

Happy to submit a PR for this later; let me know if I'm totally off-base, though.

**Comment by Oats87** [comment]
Path duplication is being caused due to a bug in the vSphere node driver where it is pre-pending the folder to the full path of the source template/VM. In order to get around this, please try setting the "Folder" field to the blank option (that's another issue that we should correct)

<img width="1043" alt="Screen Shot 2019-12-09 at 10 49 24 AM" src="https://user-images.githubusercontent.com/30601846/70463363-a16b1e80-1a71-11ea-925c-c6abee93a011.png">

cc @luthermonson

**Comment by espigle** [comment]
@Oats87 It appears leaving the folder blank allows this all to work. The only downside being that it is put into the top level folder structure under the datacenter inside of vSphere, but I can turn around and move it after the fact. At least new nodes are deploying, but it does require manual intervention after the fact to house it in the appropriate datacenter VM folder.

**Comment by Tejeev** [comment]
We worked around the issue by doing the following:
1. Go to your node templates
![image](https://user-images.githubusercontent.com/8906089/70557313-6c96be80-1b7a-11ea-91d6-881f3ee03aa0.png)
2. Choose ​View in API in the ellipsis menu for your chosen node template
![image](https://user-images.githubusercontent.com/8906089/70557337-76202680-1b7a-11ea-815b-69f4e074199a.png)
3. Select Edit​ in the Operations menu on the right
![image](https://user-images.githubusercontent.com/8906089/70557345-7cae9e00-1b7a-11ea-9ec9-b8c4de6d8585.png)
4. Check for and correct full paths in the vmwarevsphereConfig​ section to be vsphere syntax simple paths.  I believe you will need to remove `/TaxSlayer - ITC/vm` and `/TaxSlayer - ITC/host` anywhere you see it.  Also replace `null` with `""` everywhere you see it in this field to avoid https://github.com/rancher/rancher/issues/2451.
![image](https://user-images.githubusercontent.com/8906089/70557357-83d5ac00-1b7a-11ea-8780-69a4161c2761.png)
5. Select Show Request​
![image](https://user-images.githubusercontent.com/8906089/70557372-8932f680-1b7a-11ea-98b2-f5e3e90b3454.png)
6. And if all looks good, you can choose to Send Request​
![image](https://user-images.githubusercontent.com/8906089/70557381-8fc16e00-1b7a-11ea-857a-631086f31cd3.png)

Here is an example of a working vmwarevsphereConfig as seen in Show Request (though you should have replaced `null` with `""` throughout the field to avoid https://github.com/rancher/rancher/issues/24510):
![image](https://user-images.githubusercontent.com/8906089/70558095-1fb3e780-1b7c-11ea-9697-8a03a8d9a4be.png)


​

**Comment by luthermonson** [comment]
@hsartoris-bard totally spot on https://github.com/rancher/machine/pull/58

**Comment by hsartoris-bard** [comment]
@luthermonson thanks, looks like you have a more useful solution to the content library issue as well, so I'll close my PR

**Comment by Hubok** [comment]
@Tejeev An even better way to save your sanity: Change folder to "/foldername" instead of "", will actually work as you expected it to in the first place.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 565ef1a

* Fresh install `v2.3.2`
* Created node template and created cluster
* Upgrade to `v2.3.3`
  * Reproduced issue, path duplication causes an error in cloned template
* Upgrade to `v2.3-head`
* Create cluster from v2.3.2 template
* Created node templates:
  * Cloned original v2.3.2 template
  * Cloned template from v2.3.3 (clone of v2.3.2 template)
  * Created a new template
  * Edited and saved v2.3.3 template
* All clusters from the 4 templates above created successfully
  * Edited and saved original v2.3.2 template

**To-do**
* Needs to be tested in `master-head`

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 17045525a

* Fresh install `v2.3.2`
* Created node template and created cluster
* Upgrade to `v2.3.3`
  * Reproduced issue
    * Clone v2.3.2 template and select folder/resource pool from dropdowns
    * path duplication causes an error in cloned template
* Upgrade to `master-head`
* Create cluster from v2.3.2 template
* Created node templates:
  * Cloned original v2.3.2 template
  * Cloned template from v2.3.3 (clone of v2.3.2 template)
  * Created a new template
  * Edited and saved v2.3.3 template
* All clusters from the 4 templates above created successfully
  * Edited and saved original v2.3.2 template
