### ISSUE TITLE
creating vsphere cluster errors on all nodes with Error in driver during machine creation: yaml: unmarshal errors

### ISSUE THREAD

**Issue by dan-evolvere** [rancher/rancher#24314]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create fresh rancher HA installation across 3 nodes, deploy 2.3.3
- Add vsphere credential
- Add vsphere node templates, selecting options, add cloud-config
- Create cluster using node templates using rancheros from boot2docker

**Result:**
- All nodes fail to create with unmarshal error
2019/11/28 17:22:33 [INFO] Creating jail for c-xp2gr
2019/11/28 17:22:33 [INFO] Generating and uploading node config
2019/11/28 17:22:34 [INFO] [node-controller-docker-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2019/11/28 17:22:34 [INFO] [node-controller-docker-machine]
2019/11/28 17:22:34 [INFO] Generating and uploading node config evovsphere-wrkr-a-1
2019/11/28 17:22:34 [ERROR] NodeController c-xp2gr/m-wnjxh [node-controller] failed with : Error creating machine: Error in driver during machine creation: yaml: unmarshal errors:
2019/11/28 17:24:20 [INFO] Removing node evovsphere-wrkr-b-1

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted vsphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vsphere
- Kubernetes version (use `kubectl version`): 1.15.4-rancher1-2

- Docker version (use `docker version`):
19.03

**Comment by dan-evolvere** [comment]
upon doing some testing, it appears this is to do with the cloud-config.yaml URL.
We set this to an internal url http://IP:PORT/cloud-config.yaml

Has something changed in the way the cloud config URL is parsed? ie is it not longer auto wrapped in quotes or something?

Removing that URL fixes the issue. This was working just fine on 2.3.2

**Comment by dan-evolvere** [comment]
fwiw, i just tried this using a DNS based URL and got the same thing. The yaml file contents are;

#cloud-config
rancher:
  docker:
    insecure_registry:
    - registry1.domain
  system_docker:
    insecure_registry:
    - registry1.domain


Still seeing the same issues.

**Comment by espigle** [comment]
I am running into the same problem. I'm unable to spin up a node using my cloud-config.yml that I serve up from a server on premise. Previously it read the could-config.yml file fine and read any of my customization's, but it now no longer works and I get the same error.

**Comment by AntonSmolkov** [comment]
+1

**Comment by AntonSmolkov** [comment]
As a temporary workaround you can pass your cloud-init through node-templates's guestinfo parameter -  guestinfo.cloud-init.config.data 
![image](https://user-images.githubusercontent.com/5318028/70861781-dc72c380-1f43-11ea-831a-4c98c8d25a81.png)

**Comment by espigle** [comment]
This work-around seems to work for right now. Thank you.

**Comment by bevank** [comment]
+1 and the workaround is not working for me, cloud-config from the iso attached to the node(rhel vm template) only has the docker user and ssh key (which get created by cloud-init) and none of my additional config specified in the "guestinfo.cloud-init.config.data" param

**Comment by luthermonson** [comment]
no one actually says if they're doing Legacy RancherOS or cloning of templates. I'm going to assume you're all cloning because guestinfo still works in the Legacy deploy method. If anyone is seeing otherwise please provide more information.

For cloning, cloudinit is what we're trying to support going forward instead of the guestinfo method which requires you to install an additional [vmware script](https://github.com/vmware/cloud-init-vmware-guestinfo) to get working properly and we didn't want to have to force all cloned templates to have that preinstalled when cloud-init is already pretty ubiquitous and preinstalled on many OVAs. The off the shelf OVA from Ubuntu for instance comes preloaded with cloud-init and the mounted ISO is the [officially supported](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html#nocloud) method to inject your yaml into a vsphere vm. @bevank @espigle @AntonSmolkov @daehyeok try instead of using the guestinfo params use the cloud-config box like this: https://www.youtube.com/watch?v=dPIwg6x1AlU&feature=youtu.be&t=1357

I believe ultimately this requires some UI changes and documentation as if you read the text around the field it does feel like you can continue with the same guestinfo method. I'd also potentially like to see the YAML editor for that field which would make it more obvious that you should just copy/paste your YAML into that field.

**Comment by AntonSmolkov** [comment]
@bevank Yeah,  i don’t do cloning and use “legacy” method so I'm fine with guestinfo parameter for now😊. 

Btw, why RancherOS deploy has been claimed ad “legacy”? One minor release ago it was the only method and looked pretty useful and solid.

**Comment by dan-evolvere** [comment]
I actually said in my original bug report that I’m using rancheros with boot2docker which is the legacy config is it not?

**Comment by AntonSmolkov** [comment]
@luthermonson  Just to clarify - bug is reproducible only if cloud-config **URL** specified in node template settings.

**Comment by luthermonson** [comment]
@dan-evolvere sorry my mistake, i grepped with my mind for "legacy" and "clone" and i sorta glossed over that part. The method for cloudinit in the guestinfo did't change, just got moved around and might not be hit with some UI bug. i pinged you in rancher-users slack to ask for api details for your nodetemplate, if you could respond there i can look further at your setup.

**Comment by luthermonson** [comment]
@AntonSmolkov it did become legacy overnight, the original driver had a lot of bad practices like for instance it left ISOs all over the rancher/rancher container and redownloaded a new ISO every cluster create. it really added time to the cluster deploy process you really never noticed but once you switch to a clone you can get vms up MUCh quicker. it's legacy in lieu of fixing it and we'd like to promote vsphere being the source of truth for templates instead of random ISOs downloaded off the internet.

**Comment by AntonSmolkov** [comment]
@luthermonson thanks for explanation.

I hope it doesn’t mean that RancherOS itself are gonna become obsolete too.

**Comment by luthermonson** [comment]
@dan-evolvere i recreated it, thanks for the update. no need to ping me back on the rancher-slack. if you want to fix it via the API the problem is the URL needs to be in the cloudinit field (legacy) but it's getting stuck in the cloudConfig field (clone) which sends it down the path of trying to make an ISO hence the yaml unmarshall error. it's just UI not switching the fields when you toggle between legacy/clone. take a look at the screenshot from my local

this is broke:
![Screen Shot 2019-12-19 at 11 29 30 AM](https://user-images.githubusercontent.com/1616909/71199283-d84fea00-2252-11ea-8553-dc4b140ff260.png)

this works:
![Screen Shot 2019-12-19 at 12 01 25 PM](https://user-images.githubusercontent.com/1616909/71201461-4e565000-2257-11ea-82d1-263314d70b3a.png)

**Comment by Fabianm75** [comment]
Thanks all for your work on this issue. I tried the above workarounds and the "unmarshal error" is gone, but the Node deployment keep stuck in "Waiting for SSH to be available". I'm using RKE v2.3.3 in my on prem lab with vSphere 6.7, trying to deploying a Node from a RHEL 7.3 template. Thanks!

**Comment by luthermonson** [comment]
@Fabianm75 there's another bug if you have groups in your cloud-config, any chance this issue represents your problem: https://github.com/rancher/rancher/issues/24619

**Comment by Fabianm75** [comment]
@luthermonson, #24619 looks similar. It's not clear whether cloud-init should be part of the VM Template or not, can you clarify that? From my side, I'm using as template a plane RHEL, do I need to install any tool on that VM for enabling the customization or that should be just managed by the cloud-config yaml file? Thanks!

**Comment by luthermonson** [comment]
@AntonSmolkov it will continue to be supported, the method of deploying in vsphere is being deprecated in favor of official OVAs and template cloning which is more in line with the vSphere UI.

**Comment by luthermonson** [comment]
@Fabianm75 i do not know the install process on RHEL but if your image does not have cloud-init then nothing will work with this process. The only defined requirement moving forward will be a vm/template with cloud-init. read the [docs](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/#dynamically-populated-options-for-instances-and-scheduling) here for more information. I would boot your RHEL image and just type `cloud-init` and see if its available. if not find an install guide and make sure it's properly in place and then save a new template. i can't stress enough that the ubuntu OVAs come pre-loaded with cloud-init and work right out of the box, if you want something simple and working just grab one of those from their [releases page](https://cloud-images.ubuntu.com/releases/disco/release/) and give it a try, should be able to deploy a vm from the OVA and target it for cloning and have a K8s cluster up in a couple minutes.

**Comment by bmdepesa** [comment]
@westlywright can we have this backported to v2.3 as well?

**Comment by westlywright** [comment]
@bmdepesa The changes are backported and available in `latest-2.3`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 565ef1a85

* Create a node template for RancherOS Legacy w/ cloud-init field containting a URL w/ cloud config for docker insecure registry
  * No yaml unmarshalling error
  * `sudo ros config get rancher.docker.insecure_registry` correctly shows the configured insecure registry
* Base64 encoded cloud-init does not get configured correctly
  * `sudo ros config get rancher.docker.insecure_registry` shows an empty value
* Multiline file cannot be pasted, ends up formatted to one line
  * Even when including linebreak characters, the config is not correctly set

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 17045525a

* Validated above scenario on `master-head`
* cloud-init via URL
* plaintext cloud-init via guestinfo params
* base64 encoded cloud init via guestinfo params
