### ISSUE TITLE
Global roles with identical names cannot be differentiated

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24409]
**EDIT**
The desired behavior here is probably to include the actual id of the global role. Having global roles with duplicate names is not wrong and is something we allow for most objects.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- as admin, go to Global → Security → Roles → Global
- add one global role named `a1`
- add another global role also named  `a1`

**Result:**
- we got two group roles with the same name, 
- it could be confusing for users and 
- users may select and assign the wrong global role 

<img width="1444" alt="Screen Shot 2019-12-04 at 3 21 09 PM" src="https://user-images.githubusercontent.com/6218999/70186861-145b4a80-16aa-11ea-9150-86a2fe80e47e.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head 
- Installation option (single install/HA): single install

**Comment by westlywright** [comment]
@jiaqiluo if this is a requirement the back-end should be doing the check. Doing arbitrary checks through the UI is only stopgap as they can still use the API UI or CLI.

**Comment by rmweir** [comment]
a lot of things in rancher work like this- its just a display name. They also have uniquee ids backing them that the UI is aware of. I would say the issue is may be "cannot distinguish between two global roles with same display name". Node templates we show author to help out with this same issue. Node drivers and kontainer drivers show url.

![image](https://user-images.githubusercontent.com/19376037/73976017-acf98b00-48e4-11ea-8c55-ec39bba18525.png)

![image](https://user-images.githubusercontent.com/19376037/73976002-a66b1380-48e4-11ea-8d0a-834254582b82.png)

**Comment by rmweir** [comment]
edited original issue to clarify desired outcome

**Comment by jiaqiluo** [comment]
The enhancement is validated in Rancher master-head 17a40f502 with the default ui-index `https://releases.rancher.com/ui/latest2/index.html`

Steps:
- as admin, go to Global → Security → Roles → Global
- add one global role named a1
- add another global role also named a1

Results:
- the UI shows the ID of the role as a separate column, which makes it possible to distinguish roles with the same name.

<img width="1461" alt="Screen Shot 2020-03-04 at 12 13 07 PM" src="https://user-images.githubusercontent.com/6218999/75914464-0c7a8600-5e12-11ea-97dd-a8a5503db08a.png">

The same check is done for cluster roles and project roles.
