### ISSUE TITLE
Rancher Security issue : Cookie are not set with the HttpOnly and Secure attribute.

### ISSUE THREAD

**Issue by athipathy-gunasekaran** [rancher/rancher#24427]
Hello,
We are using rancher/server:v1.6.29 for managing our docker containers and as per our company policy we ran the security scan for all our applications and found that rancher server gui has the following vulnerabilities and it was advised to get it fixed. so could you please let me know is there an recommended way to fix this issue.
 
Issue 1: 
Cookies in rancher gui are not flagged with the HttpOnly attribute which protects cookies from being read or written to by client side scripts e.g. JavaScript.  Protecting the cookies in this manner where possible can prevent attacks such as cross site scripting (XSS) from successfully stealing cookie information leading to hijacked sessions.

![image](https://user-images.githubusercontent.com/49866264/70241861-ccb1ed00-1795-11ea-80a5-e94ccb376d8b.png)

Recommendation from our Security team:
It is recommended that the HttpOnly attribute be used during the set-cookie directive for all cookies. It should be noted that some applications by design use client-side scripts to read/write cookie information which goes against best practices in the security industry because of the introduction of client-side tampering and is not an acceptable form of managing a session through the cookie attributes and values

Issue 2:
Cookies in rancher gui, when set, are not flagged with the “Secure” attribute which prevents the browser from transmitting the cookie over an unencrypted channel.  Protecting the cookies in this manner where possible can prevent cookies from being observed by unauthorized parties due to the transmission of the cookie in clear text.  

![image](https://user-images.githubusercontent.com/49866264/70242344-afc9e980-1796-11ea-8a83-37a1e5c41983.png)

Recommendation from our Security team:
It is recommended that the secure attribute be used during the set-cookie directive for all cookies. The secure flag should be set on all cookies that are used for transmitting sensitive data and when accessing content over HTTPS. This makes the cookie less likely to be exposed to cookie theft via eavesdropping on the victim’s computer or in transit.

**Comment by athipathy-gunasekaran** [comment]
Gentle reminder is there an update on this issue ? this delays our security approval for proceeding on deployment on customer premise.

**Comment by vincent99** [comment]
1.x is no longer being maintained except for critical security issues (which this isn't).  So you should really probably not be deploying any new 1.x installs anywhere at this point...

These "recommendations" are standard boilerplate output of an automated testing suite.  The `PL` cookie is there for the server to tell the client (browser) what company name to show on the screen and can't be HttpOnly since its purpose is explicitly to be read by the client.  It could be marked secure in theory, but its value is not a secret so this is irrelevant.

The one cookie that does contain sensitive info (the session token) is `secure` if the page is loaded with https, but cannot be `httponly` without significant changes that are not going to happen in 1.x (and were already done in 2.x).

This is not a bug and will not be patched (even if there were any upcoming releases planned for 1.x).

**Comment by athipathy-gunasekaran** [comment]
Thanks Vincent for your reply.

Regards,
Athipathy.
