### ISSUE TITLE
minus-icon to remove members from project missing from Edit Project page

### ISSUE THREAD

**Issue by flrichar** [rancher/rancher#24428]
**Rancher version:** 2.3.3

**docker version:**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**kubectl version:**
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**Operating system and kernel:**
cat /etc/os-release
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
uname -r
```4.4.0-1099-aws```

**Type/Provider of hosts:** AWS (lab)

**Steps to Reproduce:**

 * log into UI as cluster owner user
 * select Cluster, then Projects/Namespaces
 * for named Project, select right-side 3 dots menu, "Edit"

**result:**
Icon missing for removing members from this project (see screenshots)

v2.3.3:
![project-members-233](https://user-images.githubusercontent.com/3878418/70244528-926b3000-1742-11ea-8c9f-1fb449a993b9.png)

(member-remove minus icons were present in v2.2.8)
screenshot of v2.2.8 with remove icons:

![project-members-228](https://user-images.githubusercontent.com/3878418/70244526-926b3000-1742-11ea-9dad-c18542f551ca.png)

**Comment by sowmyav27** [comment]
**Reproduced the issue on `2.3.4`**

**Steps:**

- Deploy a cluster
- Add User1 as a member of the cluster
- Go to Edit cluster --> Member Roles section
- minus-icon to remove members from project missing from Edit Project page

<img width="1480" alt="Screen Shot 2020-01-23 at 11 26 24 AM" src="https://user-images.githubusercontent.com/26032343/73016693-34b6a400-3dd3-11ea-97d6-e049a0797eb8.png">

**Verified on latest-master - head**

The issue is seen fixed
<img width="1439" alt="Screen Shot 2020-01-23 at 12 02 25 PM" src="https://user-images.githubusercontent.com/26032343/73022720-fb843100-3dde-11ea-9f06-7a46f6d01462.png">
