### ISSUE TITLE
Unable to listen for both HTTP and HTTPS with Rancher load balancer

### ISSUE THREAD

**Issue by bilal** [rancher/rancher#2442]
I tested two scenarios and both seem to fail:

1.  Listen on HTTP and HTTPS on the same port
2. Listen on HTTP and HTTPS on different ports for the same target service

My Rancher setup:

Rancher	v0.42.0 (I upgraded from an earlier version)
Cattle	v0.102.0
User Interface	v0.57.0
Rancher Compose	v0.4.3

More details:

1) Listen on HTTP and HTTPS on the same port

When I configure HTTP and HTTPS on the same port for a target service (shown below) HTTP stops working
![image](https://cloud.githubusercontent.com/assets/60473/10714193/4e2ea596-7ab8-11e5-8b2c-5954bb190cee.png)

2) Listen on HTTP and HTTPS on different ports for the same target service

I configured HTTP on port 9000 and HTTPS on port 9001 with the same target port and target service. HTTPS (on 9001) doesn't work (connection refused) but HTTP (on 9000) works. 
 
![image](https://cloud.githubusercontent.com/assets/60473/10714212/5afc1078-7ab9-11e5-8631-92f4a30a2dd0.png)

I then configured HTTPS on port 9000 and HTTP on port 9001 with the same target port and target service. HTTP (on port 9001) doesn't work but HTTPS (on 9000) works. 
![image](https://cloud.githubusercontent.com/assets/60473/10714230/663bf4a2-7aba-11e5-910c-a8febecd5354.png)

And then when I go and view/edit the load balancer it only shows one of the listening ports configured:
![image](https://cloud.githubusercontent.com/assets/60473/10714237/ef7c2232-7aba-11e5-94a1-0bbcbee46493.png)

**Comment by vincent99** [comment]
1. Generally makes no sense and should be prevented by UI validation. The input to the API is a list of port numbers to listen on and a list of those which should be SSL.  So this is just saying to listen on 9000 twice and that 9000 should be SSL.  It is technically possible to detect http vs ssl protocols on the same port, but it is certainly not a common configuration and most software doesn't support that (I don't know if haproxy does or not).

2. sounds like a bug, either in what was sent to the API to create it in the UI or creating the actual containers with it later.

**Comment by bilal** [comment]
re: 1: Why not? It's not uncommon to have HTTP and HTTPS on the same port specifically for setups where SSL termination happens at the load balancer/proxy. It's typically useful for test/integration environments where HTTPS mimics production behaviour and HTTP is mostly there for debugging etc.  Also from a UI perspective, this is exactly what is allowed by some of the AWS services, e.g., Elastic Beanstalk.

**Comment by vincent99** [comment]
It is *very* uncommon; few to 0 of the major web or application servers support this and most people don't even know it's possible (or they think "http://host" and "https://host" are the "same port").  The most prominent common use I can think of is in the CUPS printer daemon.

It is impossible for TCP ports because they are speaking an arbitrary protocol.  For HTTP specifically you can implement what amounts to a hack to look at the first few bytes of the request and see if they "look like" a TLS handshake or a HTTP method.  They look different in the real world, but the handshake varies between versions and the HTTP spec allows arbitrary methods that can overlap with things that look like handshakes of some TLS versions. It's a hack, and it appears beanstalk supports it because they don't allow more than one listening port for some other reason so they had to do something.

I dont think this covers every handshake but it does appear to be possible in haproxy,  http://serverfault.com/a/628183. You can inject that into the Rancher balancer config eventually with https://github.com/rancher/rancher/issues/2171.

Separate listener ports to the same target is the normal way to do this and should of course not be broken.

**Comment by cusspvz** [comment]
I have Load-Balancers listening for 80 and 443 ports and redirecting to the same port.
Here's how you should config it:
<img width="984" alt="captura de ecra 2015-10-26 as 13 48 31" src="https://cloud.githubusercontent.com/assets/3604053/10730508/45273d74-7be8-11e5-8cb9-ef0c2cd7376a.png">

**Comment by cusspvz** [comment]
I've figured this out, and reported more technical details on #2450. You can workaround this by reading the second comment.

**Comment by cusspvz** [comment]
Hope it helps! :)

**Comment by etlweather** [comment]
Just a two cents - cups works that way... both http/https occurs on port 631.

**Comment by bilal** [comment]
@cusspvz , your example works for both http and https. thanks.

**Comment by deniseschannon** [comment]
Closing as there is a solution provided by @cusspvz.
