### ISSUE TITLE
AKS/GKE/EKS multiple node-pool support

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24492]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature request

We would like to have multiple node-pool support so that we can have workloads of different types deployed to the same k8s cluster. For example, some pods should run on large instances with GPU support; others could fit into a default pool with no specific requirements.

We have already begun work towards a PR for EKS support and plan to follow-up with GKE & Azure support.

**Comment by dstockton** [comment]
FYI @cjellick

**Comment by dstockton** [comment]
Relates to https://github.com/rancher/rancher/issues/24126

**Comment by xabierlaiseca** [comment]
Here's my proposal for this issue.

# Scope
The goal is to implement support for multiple node pools for AWS, GKE and Azure. For a given Kubernetes cluster, at least one node pool will be set up. For each
node pool, the user will be able to provide the same kind of attributes that can
be now provided for the only supported node pool (vm image, capacity, etc.) plus
node taints and labels.

This proposal will only include the description of the feature from a high level
point fo view. How the integration with cloud providers will be implemented will
be explained in following proposals.  

# Proposed feature
During a Kubernetes cluster creation and update, adding and deleting node pools will be supported. For each node pool, during node pool creation both taints and labels could be provided.

## Taints
In order to setup taints in a given node pool, 2 approaches will be available:

1. Flag to add default taint: a `NoSchedule` effect taint with operator set to `Equal`, key set to `nodepool` and value set to the name of the node pool. This is meant to have a simple way of setting up a taint.

1. Provide an optional list of additional taints that will allow setting up taints as desired. Each element of the list will have the effect, the operator, the key and the value.

## Labels
In order to setup labels in a given node pool, 2 approaches will be available:

1. Flag to add default node pool label: this will add `node-restriction.kubernetes.io/nodepool` set to node pool name. The proposed label is based on the recommendation described in [here](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-isolation-restriction).

1. Provide an optional list of additional custom labels.

Additionally, some cloud providers add a custom label to nodes that references the node pool the node belongs to. Those labels could as well be used in order to deploy pods to specific node pools by using affinities. Azure adds `agentpool`, GKE adds `cloud.google.com/gke-nodepool` but AWS (using the autoscaling group approach) does not add any node pool specific label. For AWS, the `node-restriction.kubernetes.io/nodepool` label will be set if no other custom label is been set up.

# Limitations

1. _Azure does not support setting up labels in node pools_: By the time this proposal was written, Azure does no support adding labels but there's ongoing work to add support for it: https://github.com/Azure/AKS/issues/1088

2. _AWS's newly released node pools functionality does not support tainting_: Because of that, this new feature will not be considered.

**Comment by g0atcheez** [comment]
Has there been any additional discussion around supporting multiple node pools for AKS? It looks like according to https://github.com/Azure/AKS/issues/1088#issuecomment-587730732 the required functionality is now in place in the Azure API.

**Comment by fgielow** [comment]
> Has there been any additional discussion around supporting multiple node pools for AKS? It looks like according to [Azure/AKS#1088 (comment)](https://github.com/Azure/AKS/issues/1088#issuecomment-587730732) the required functionality is now in place in the Azure API.

Considering this, is there plans on the roadmap to include node pools on AKS?
