### ISSUE TITLE
Incorrect progress bar status in app

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#24500]
Version: 2.3.3

Steps:

1. Deploy a catalog such as registry in default project and wait.
2. Go to workloads page and remove the pod of the catalog manually
3. Go back to the apps page

Result:

Sometimes the progress bar will always be red until refresh the page

![image](https://user-images.githubusercontent.com/21168270/70500341-47905480-1b56-11ea-8325-5b04c618de31.png)

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.3`

Deploy a catalog such as registry in default project and wait.
Go to workloads page and remove the pod of the catalog manually
Go back to the apps page
Progress bar is stuck until refresh
![Screen Shot 2019-12-10 at 2 31 39 PM](https://user-images.githubusercontent.com/57409052/70571978-19157800-1b5c-11ea-8d7a-b264925d345f.png)

Tested with Rancher server `rancher\rancher:master-head` `version f3fbe1449`

Progress bar is no longer stuck.
![Screen Shot 2019-12-10 at 2 46 43 PM](https://user-images.githubusercontent.com/57409052/70571999-23d00d00-1b5c-11ea-850e-4944b0410019.png)
![Screen Shot 2019-12-10 at 2 46 52 PM](https://user-images.githubusercontent.com/57409052/70572005-26326700-1b5c-11ea-8640-c4231c951ec8.png)
