### ISSUE TITLE
etcd node changes can cause unhealthy cluster (especially in case of leader re-election, slow etcd or large etcd size)

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [rancher/rancher#24547]
**What kind of request is this (question/bug/enhancement/feature request):Bug

**Steps to reproduce (least amount of steps as possible):**
**Rancher Version**: v2.3.2
**Kubernetes Version:** v1.13.5
**Docker Version:** 17.3.2
AWS Worker Node Version: CentOS Linux release 7.6.1810 , m5.2xlarge , kernel:4.4.184-1.el7.elrepo.x86_64
The cluster is Amazon EC2 Launched Cluster via Rancher GUI.
The cluster has 3 separate nodes which handle etcd & controlpanel.. Worker nodes are seperate and don't have etcd & controlpanel
```
1) Try to add a AWS worker node. The node is stuck during provisioning. I see following commands run in /var/log/secure on the node
============================================
grep COMMAND /var/log/secure  | grep <provisioninguser>
Dec 11 11:34:22 ip-x-x-x-x sudo: <provisioninguser> : TTY=pts/0 ; PWD=/home/<provisioninguser> ; USER=root ; COMMAND=/bin/hostname blah-blah
Dec 11 11:34:22 ip-x-x-x-x sudo:  <provisioninguser> : TTY=pts/0 ; PWD=/home/<provisioninguser> ; USER=root ; COMMAND=/bin/tee /etc/hostname
Dec 11 11:34:25 ip-x-x-x-x sudo:  <provisioninguser> : TTY=pts/0 ; PWD=/home/<provisioninguser> ; USER=root ; COMMAND=/bin/tee -a /etc/hosts
Dec 11 11:34:29 ip-x-x-x-x sudo:  <provisioninguser> : TTY=pts/0 ; PWD=/home/<provisioninguser> ; USER=root ; COMMAND=/bin/yum install -y curl
Dec 11 11:34:58 ip-x-x-x-x sudo:  <provisioninguser> : TTY=pts/0 ; PWD=/home/<provisioninguser> ; USER=root ; COMMAND=/bin/yum -y update -x docker-*

Then the provisioning user logs out after couple of minutes without doing anything
Dec 11 11:37:27 <hostname> sshd[pid]: pam_unix(sshd:session): session closed for user <provisioninguser>
```

**Result:**
AWS Worker node stuck in provisioning and then when tried to remove it , its stuck in "Removing " State with message 
`Provisioning with <provisioninguser>...; waiting on node-controller`
--

**Other details that may be helpful:**

**Environment information**
**Rancher Version**: v2.3.2
**Kubernetes Version:** v1.13.5
**Docker Version:** 17.3.2
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
rancher/rancher-agent:v2.3.2
rancher/hyperkube:v1.13.5-rancher1
rancher/rancher:v2.3.2 ( This is run in a separate "local" k8s cluster
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider Amazon EC2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS m5.2xlarge
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
![image](https://user-images.githubusercontent.com/39374310/70682271-55fc7e80-1cc4-11ea-949d-1e02f5242c8b.png)

gzrancher/rancher#9105

**Comment by Hitesh-Agrawal** [comment]
Anyone from rancher team looking into this. Its a blocker for us right now

**Comment by Hitesh-Agrawal** [comment]
@Oats87 Chris - can you look into this?

**Comment by Hitesh-Agrawal** [comment]
Any update on this ?

**Comment by Hitesh-Agrawal** [comment]
At this point, I am planning to delete the node from the backend etcd keystore and see what happens `ETCDCTL_API=3 etcdctl delete /registry/management.cattle.io/nodes/<cluster-id>/<error-node-id>`

**Comment by thiagosantosleite** [comment]
I had the same issue in "Rancher 2.3.3" after I upgrade kubernetes custom cluster (Running on EC2) to 1.16.3 Instances, but the interesting point was that it self solved after 3 hours (the node disappear).

Now I'm afraid it'll happen again.

**Comment by Hitesh-Agrawal** [comment]
Ok this was fixed after I killed the `docker-machine` cmd which was spawned from the rancher workload running under `cattle-system` namespace.  Also the etcdctl delete solution works. Once I ran it , it deleted the node from the ui, but docker-machine cmd was still running inside the rancher deployment. 
`ETCDCTL_API=3 etcdctl del /registry/management.cattle.io/nodes/<cluster-id>/<error-node-id>`

**Comment by Oats87** [comment]
@Hitesh-Agrawal so you're saying you had a hung `docker-machine` process running within a jail in Rancher? Did you ever try just killing all of the Rancher pods (to force a restart) and seeing if things cleared up?

**Comment by Hitesh-Agrawal** [comment]
> @Hitesh-Agrawal so you're saying you had a hung `docker-machine` process running within a jail in Rancher? Did you ever try just killing all of the Rancher pods (to force a restart) and seeing if things cleared up?

@Oats87 Yep I believe even doing that would have cleared things up. 

Also regarding the node stuck in provisioning at COMMAND=/bin/yum -y update -x docker-* was due to awscli installed via pip in my custom image which was causing issue with above yum command
Replaced below in my image from
```
curl -O https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install awscli --upgrade 
```
to
`yum -y install awscli`

You probably need to introduce a timeout for the hung docker-machine process.

**Comment by Tejeev** [comment]
I see this or a similar issue when creating a cluster in 2.3.6 with nodes of 2 Cores and 4GiB of RAM. I've seen these sorts of issues may be caused by resource issues, but I also see them in clusters where this is not the case

Steps:
1. Deploy cluster with 1 cp/etcd node
2. Scale up to 3 nodes using `+` in the UI
3. Scale down to 1 node
![image](https://user-images.githubusercontent.com/8906089/84809286-c1bbfd00-b001-11ea-9d18-26c8e644cc5a.png)

Alternatively, I also see failures when scaling down one node at a time.  After a cp/etcd node was removed in the v2.3.6 cluster (leaving 2 behind) I saw one of the two get stuck with waiting on the node to respond (unfortunately I lost the screenshot and error).  Deleting the node forced a recreation and resolved the issue.

It took roughly 8 attempts to recreate before I was able to get nodes stuck again after the first attempt (which similarly failed). The failure doesn't appear to be predictable but it is common enough that I've seen this behavior on many test clusters for several versions. I've not yet been able to recreate in 2.4.3, and i notice that the nodes take longer to deploy and remove, so this may have been fixed?
![image](https://user-images.githubusercontent.com/8906089/84827099-de652e80-b01b-11ea-8328-1047b5191b3f.png)

**Comment by fel835** [comment]
2.4.3，similar issue

**Comment by superseb** [comment]
Based on https://github.com/rancher/rancher/issues/24547#issuecomment-645008685, the following was investigated:

As it wasn't consistently reproduced, I started with testing removing one and two nodes at a time. Sometimes this would succeed, sometimes this would fail. Based on this outcome I tried checking the etcd leader and make sure that when deleting a node, it was the etcd leader. This caused more delay in recovering the cluster because re-election is triggered. Because there is no wait/healthcheck on member delete, there is not enough time to re-elect a leader and either the next member delete (in case of deleting multiple nodes) or the cluster health check that we do on reconcile only is coming too soon and doesnt have enough time to let the cluster settle.

The fix is to add a health check the cluster on member delete.

To reproduce (either RKE CLI or Rancher node driver):

- Create a 2 node and a 3 node cluster
- Check the etcd leader using the command on https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/#check-endpoint-status
- Make sure to delete the node that is the leader (in the 2 node cluster) and that node and another random node in the 3 node cluster
- Observe the cluster failing because etcd is not recovering

To make it easier to reproduce, raise the election-timeout on etcd so it takes longer to elect a new leader:

```
services:
  etcd:
    extra_args:
      election-timeout: "50000"
```

**Comment by Tejeev** [comment]
Looks like this has already been fixed but just in case, we've seen this recreated as follows:
In a new test cluster running on rke 1.17.11-rancher1-1, rancher 2.4.4, host OS all Ubuntu 18.04, docker 19.3.11 all on vSphere on-prem using canal:

1.     Created 2 pools, 1 for etcd/cp and1 for workers
2.     Created 1 node for combined etcd/cp and 1 node for workers
3.     Im now going to upgrade the cluster to 3 etcd/cp by immediately increasing the amount of nodes in the pool by hitting the + icon twice.

Result:
    This ends up with the 2 new etcd/cp nodes ending in error:  Error creating machine: Error running provisioning: Failed to obtain lock: Maximum number of retries (60) exceeded

**Comment by FWest98** [comment]
> Ok this was fixed after I killed the `docker-machine` cmd which was spawned from the rancher workload running under `cattle-system` namespace. Also the etcdctl delete solution works. Once I ran it , it deleted the node from the ui, but docker-machine cmd was still running inside the rancher deployment.
> `ETCDCTL_API=3 etcdctl del /registry/management.cattle.io/nodes/<cluster-id>/<error-node-id>`

This is what worked for me as well. In my case, I was using the OpenStack provisioner with incorrect settings. To be specific, I had an error in my network configuration causing the instance to be unreachable. Rancher was permanently `waiting for SSH` without any timeout.

**Comment by kinarashah** [comment]
Available to test with `v2.4.9-rc1`

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.4.8 single install setup 

Steps:
- add a cluster 4 nodes: 3 etcd+controlplane, 1 worker 
- ssh into one of the etcd+controlplane node to find the etcd leader
- delete the leader node and another one etcd+controlplane node at the same time from Rancher UI

Results:
- the cluster is stuck in the updating state and never recover 

<img width="1424" alt="Screen Shot 2020-10-19 at 3 55 07 PM" src="https://user-images.githubusercontent.com/6218999/96522409-2db8a700-1228-11eb-8c11-1a2a6be4a4d9.png">

**Comment by jiaqiluo** [comment]
The fix is validated in the following RKE CLI 

- v1.1.11-rc1
- v1.2.2-rc2


Steps:
- use RKE CLI to provision a 4 node cluster: 3 etcd+controlplane, 1 worker
- ssh into one of the etcd+controlplane node to find the etcd leader
- remove the leader node and another one etcd+controlplane node in the `rancher-cluster.yml`
- run `rke up` again to update the cluster


Results:
- the cluster is upgraded successfully
