### ISSUE TITLE
vSphere 6.7 Support

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#24568]
Validate vSphere 6.7 as an OS as well as supported in node provisioning.

**Comment by wsaca** [comment]
Now I don't have any problem with vsphere 6.7 but I had these problems:
- I couldn't use a vsphere credential in a node template because the datacenter information couldn't be retrieved, it was throwing JS errors due to a malformed entity.
- When the boot of a provisioned vm (with rancheros) failed (because vt-x/etp for nested vm was disabled) then rancher tried to create it again. I ended up with many vm with a suffix, ie: master-1, master-1_1, master-1_2, etc.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head

Tested the following against our vSphere 6.7:
* Legacy RancherOS
* Deploy from Template: Datacenter
* Clone from existing
* Deployed w/ cloud provider and tested storage provisioning

Tested the following with a failure:
* Deploy from Template: Content Library - #24480
