### ISSUE TITLE
[UI] 'View in API' button on services link broken

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2457]
When clicking the 'View in API' link of a service, instead of going to your rancher server address + API Url it's sending you to `http://latest.rancher.io/`

This doesn't resolve.

Version 0.43.0, cleared browser caches.
Tested in Chrome on a mac.

**Comment by ibuildthecloud** [comment]
@Rucknar yep, v0.43.0 is broken in this regard.  Expect v0.43.1 shortly.

**Comment by vincent99** [comment]
The last UI build was compiled with the wrong settings because an [environment variable](https://github.com/rancher/ui/commit/74a143907e1518defb3984d01b21f91e19085095#diff-695693c5dabaffb064bde5b060195ff7R96) was renamed, I thought I'd be nice and leave the old one backwards compatible, but that happened to be set on the build host and not cleared when doing the regular build. :frowning:

It does resolve (on the public internet), but wouldn't matter anyway since it's one of our installations.

**Comment by Rucknar** [comment]
Cool, figured you had spotted it but thought i'd raise it just in-case. I'll deploy 43.1 and close this once it's out.

**Comment by deniseschannon** [comment]
@Rucknar v0.43.1 is out, so please feel free to test it. :)

**Comment by Rucknar** [comment]
Works a treat, thanks all.
