### ISSUE TITLE
Labels and annotation aren't read-only in pod security policy detail page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#24621]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1.  Create a Pod security policy
2.  Click on the name to get to details page
3.  Open the Labels & Annotations accordion

**Result:**  The Add buttons are still available, an extra row for both are added and the remove is active.  The buttons should not be there and it should be read-only.
![image](https://user-images.githubusercontent.com/11514927/70950863-0947d900-201f-11ea-94f1-fe0d6689cea8.png)

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.3`
Steps:
Create a Pod security policy
Click on the name to get to details page
Open the Labels & Annotations accordion
Result:
![Screen Shot 2020-01-06 at 11 55 15 AM](https://user-images.githubusercontent.com/57409052/71841037-c0160280-307b-11ea-9e64-bbf81b2fcc62.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 552eb2896`
![Screen Shot 2020-01-06 at 11 55 20 AM](https://user-images.githubusercontent.com/57409052/71841053-c5734d00-307b-11ea-8362-8d551548b5c7.png)
