### ISSUE TITLE
[UI] The custom address surrounded by '*%'  in registry credentials page

### ISSUE THREAD

**Issue by ly5156** [rancher/rancher#24659]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Click Add Registry button in registry credentials page
2. Choose custom options and input a address(eg. myluckystar.xyz) in address section when add registry
3. Click Save button
**Result:**
Go to registry credentials page, the address  was surrounded by '*%' 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:latest
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM(2core/2g)
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:50:02 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df9ba
  Built:            Wed Sep  4 16:55:50 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.3`
Steps:
Add a registry.
Choose custom options and input a address(eg. myluckystar.xyz) in address section.
Save.
![Screen Shot 2020-01-06 at 10 28 08 AM](https://user-images.githubusercontent.com/57409052/71835818-bf776f00-306f-11ea-81cb-4e51b5c5d25b.png)
Result:
![Screen Shot 2020-01-06 at 10 28 14 AM](https://user-images.githubusercontent.com/57409052/71835823-c43c2300-306f-11ea-9076-069bc753690f.png)

The bug fix is validated in Rancher server `rancher\rancher:master-head` `version 552eb2896`
![Screen Shot 2020-01-06 at 10 06 38 AM](https://user-images.githubusercontent.com/57409052/71838506-357ed480-3076-11ea-9c01-8dfc6936fbb8.png)
