### ISSUE TITLE
Unable to create config for node x-xxxx: lstat fail no such file or directory

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#24695]
This have been happening intermittently to me in latest `2.4 master-head` and `2.3-head` d73dff8df

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a new Rancher server, I've used a Linode host to deploy the single Install Rancher docker.
2. Create a Digital Ocean, Linode or vSphere node template.
3. Create a cluster with this node template use 3 Node Pools. 1 etcd, 1 control plane, 3 workers.
4. Save the cluster
5. Click the  cluster nodes to see them.
6. An error will be displayed.

**Result:**

`Unable to create config for node m-sxngn: lstat /opt/jail/c-kd46b/management-state/node/nodes/test-23head-wrkr-3: no such file or directory`

**Other details that may be helpful:**

A workaround I've seen is by removing the node in the UI and letting Rancher recreate it in the node pool. This new instance usually gets created properly.

**Environment information**
- Rancher version: `2.3-head` d73dff8df
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud

**Comment by izaac** [comment]
```
root@localhost:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           395M  7.0M  388M   2% /run
/dev/sda         79G  4.0G   71G   6% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           395M     0  395M   0% /run/user/0
overlay          79G  4.0G   71G   6% /var/lib/docker/overlay2/23f48d928894f9250e65a490482c8443e3b554547b5d6aa2e10c9f6044018619/merged
```

```
root@localhost:~#  badblocks -sv /dev/sda
Checking blocks 0 to 83361791
Checking for bad blocks (read-only test): done
Pass completed, 0 bad blocks found. (0/0/0 errors)```

**Comment by dramich** [comment]
This is most likely caused by https://github.com/rancher/rancher/pull/24564

**Comment by superseb** [comment]
@dramich It seems that having the refreshNodeConfig in https://github.com/rancher/rancher/pull/24564/files#diff-08561860aec1e2ae34abab4f4102f50eL156 triggers a race condition where the jail directory is removed while its not fully setup yet. I can't find any reference to cleanup besides cleaning up the jail directory when there is no `done` file present and it being removed causing this issue.

Some possible solutions:

- Wait for the jail timeout for the done file to be created (to make sure it doesn't trigger jail removal when its in progress, at least the timeout that is set for it to be created)
- Not remove jail directory (but I guess this is needed when creating a jail fails and remains incomplete)
- Do not trigger this behavior on node creation (not sure if we can limit this properly)

As you have worked on a fix for a different scenario, can you share your insight on the logic and the expected behavior?

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (01/06/2020)` 552eb2896
- DigitalOcean Cluster with k8s v1.17.0
- Linode Cluster with k8s v1.16.4

Rancher version: `2.3.4-rc8`
- DigitalOcean Cluster with k8s v1.16.4
- Linode Cluster with k8s v1.15.7


Those are some of the sample clusters I've made trying to reproduce the issue I've originally faced.
So far I wasn't able to reproduce, I tried checking the rancher server logs too and there weren't any logs about no such file or directory.

Closing issue.
