### ISSUE TITLE
CIS Scan - UI - Scan results seen on a page refresh

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24756]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Run CIS Scans on a cluster.
2. The Scan report becomes Active.
3. But the Passed/Failed/Skip details are not seen on the UI.
4. Refresh on the page, gives the details.

<img width="1273" alt="Screen Shot 2019-12-23 at 9 45 00 PM" src="https://user-images.githubusercontent.com/26032343/71396141-c7de9d00-25cd-11ea-8d8f-64ef20d391a4.png">

**Expected Result:**

User should be able to see Passed/Failed/Skip details for a scan run, on the UI without a refresh

**Note:** 
This does NOT happen always

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.0-alpha1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom/rke
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by codyrancher** [comment]
@sowmyav27 is there anything special I need to do in order to reproduce this issue?

I've attempted to repro this quite a few times and haven't been able to.

![Kapture 2020-01-20 at 14 44 27](https://user-images.githubusercontent.com/55104481/72759687-a1dbf680-3b93-11ea-854f-5387306dc8af.gif)

**Comment by sowmyav27** [comment]
@codyrancher I am not sure of the exact steps to reproduce this.
This does not happen always.

**Comment by sowmyav27** [comment]
@codyrancher @leodotcloud I think this would happen, on a new cluster, when you run the Scan for the first time, while not navigating to any page, until the scan report is Seen Active.
I am able to reproduce this on master-head latest today with these steps.
<img width="1285" alt="Screen Shot 2020-02-07 at 11 29 28 AM" src="https://user-images.githubusercontent.com/26032343/74059667-5308cc00-499d-11ea-8e1b-6abaa32fc6b8.png">

**Comment by codyrancher** [comment]
Cool, thanks for the repro @sowmyav27 I'll see if I can repro myself.

**Comment by codyrancher** [comment]
I'm actually able to reproduce this all the time now but what I'm seeing this should only be a problem if the url to rancher has a port. @soumyalj what's the url to the test environment you use?

@leodotcloud Locally I'm failing to get the report because the links that are being passed by the websocket are incorrect, they're not including the port. When I attempt to fetch the report the request fails. This is actually also breaking the View Api actions as well.

Here's my browser url:
<img width="358" alt="Screen Shot 2020-02-20 at 12 35 31 PM" src="https://user-images.githubusercontent.com/55104481/74971715-c5d26800-53dd-11ea-8e8b-dd26b431f17c.png">

Here are the malformed links:
<img width="598" alt="Screen Shot 2020-02-20 at 12 35 25 PM" src="https://user-images.githubusercontent.com/55104481/74971699-bfdc8700-53dd-11ea-9e87-6a1d99d0b783.png">

And this is the report request failing.
<img width="785" alt="Screen Shot 2020-02-20 at 12 35 44 PM" src="https://user-images.githubusercontent.com/55104481/74971722-c9fe8580-53dd-11ea-8ce2-b12112f61bf4.png">

**Comment by sowmyav27** [comment]
@codyrancher URL usually is https://<rancher-server(ip-address)>/

**Comment by codyrancher** [comment]
@sowmyav27 so no port like mine? The 8000 in https://localhost:8000?

**Comment by codyrancher** [comment]
Once @leodotcloud resolves the port issue I'll attempt to reproduce again since @sowmyav27 doesn't use a port.

**Comment by leodotcloud** [comment]
I was able to reproduce this issue with a new cluster on first scan. I don't think this is related to port issue at all. Please see below screenshots, everything looks fine. There is some UI issue here.

<img width="1138" alt="Screen Shot 2020-03-05 at 2 24 53 AM" src="https://user-images.githubusercontent.com/19392926/75922379-e217df80-5e88-11ea-85df-bc187cd10fef.png">
<img width="1144" alt="Screen Shot 2020-03-05 at 2 25 23 AM" src="https://user-images.githubusercontent.com/19392926/75922386-e643fd00-5e88-11ea-83c2-4830b0d86037.png">
<img width="1144" alt="Screen Shot 2020-03-05 at 2 25 41 AM" src="https://user-images.githubusercontent.com/19392926/75922388-e6dc9380-5e88-11ea-93c6-c84ce67cefdb.png">
<img width="1141" alt="Screen Shot 2020-03-05 at 2 25 55 AM" src="https://user-images.githubusercontent.com/19392926/75922391-e7752a00-5e88-11ea-8fb1-3e63f6a71a2f.png">
<img width="1141" alt="Screen Shot 2020-03-05 at 2 26 07 AM" src="https://user-images.githubusercontent.com/19392926/75922395-e80dc080-5e88-11ea-9869-ea98061bceb0.png">

**Comment by leodotcloud** [comment]
@codyrancher as you can see from the screenshots above, the links are correct and the report links is returned too after the scan is finished. I don't think this is a backend issue. Assigning it back to you.

**Comment by codyrancher** [comment]
Once more I'm no longer able to reproduce this issue. Would you mind testing again?

**Comment by sowmyav27** [comment]
Currently on latest master, not able to reproduce this issue.
Closing it for now
will reopen when we see the issue
