### ISSUE TITLE
Document an example of adding options for enabling Thanos

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24793]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
We need to update the `Cluster Monitoring Configuration` and `Project Monitoring Configuration` pages to make it easy to enable Thanos. Currently, we need to pass all options in the answers section. 

```
prometheus.thanos.enabled=true
prometheus.thanos.objectConfig.type=S3
prometheus.thanos.objectConfig.config.bucket=jiaqi-thanos
prometheus.thanos.objectConfig.config.region=us-west-1
prometheus.thanos.objectConfig.config.endpoint=s3.amazonaws.com
prometheus.thanos.objectConfig.config.signature_version2=false
prometheus.thanos.objectConfig.config.insecure=true
prometheus.thanos.objectConfig.config.access_key=*****
prometheus.thanos.objectConfig.config.secret_key=*****
```

See this issue for more info: https://github.com/rancher/rancher/issues/24214

**Comment by deniseschannon** [comment]
This is not needed for 2.3.4, so I moved it out to 2.4. We can enable the chart in 2.3.4 but add the UI enhancement in for 2.4.

**Comment by westlywright** [comment]
@deniseschannon I don't think implementing this is as simple as exposing this exact set of parameters outlined above. Based on the [chart pull request](https://github.com/rancher/system-charts/pull/95) which links to the docs about the [storage config](https://github.com/thanos-io/thanos/blob/master/docs/storage.md) the requirements outlined define the S3 config. There are currently 6 other potential `type` configs with unique parameters. This is not impossible to do, but the requirements need to be defined better. The maintenance and upkeep of those configs, adding/removing config types, etc. make this enhancement a hard sell personally. Since we're already providing a method for users to input custom entries via `answers`, in this case I would argue that answers, while more tedious, would satisfy the needs of a customer using Thanos.

**Comment by deniseschannon** [comment]
Closing in favor of the docs issue https://github.com/rancher/docs/issues/2229
