### ISSUE TITLE
Text in UI to specify logging only works in host gateway mode in windows cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24795]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

A text can be available on the UI for the users, to specify logging only works in host gateway mode in windows cluster.

This is because when logging is now enabled in VXLAN mode, the workload - rancher-logging-fluentd-windows crashes. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher-master
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Is this a known change? Do you have a backend PR to reference this change?

**Comment by loganhz** [comment]
We already have a similar warning in UI in 2.3.0
`Logging doesn't work with VxLan mode currently due to <a href="https://github.com/kubernetes/kubernetes/issues/79359" target="_blank">kubernetes/kubernetes#79359</a>. We are working with Microsoft to fix it in Kubernetes side.`
https://github.com/rancher/ui/blob/master/translations/en-us.yaml#L9718

**Comment by sowmyav27** [comment]
**On master - head - UI tag latest2**

Logging is seen disabled on the UI for a VXLAN windows cluster and a warning is displayed
<img width="1377" alt="Screen Shot 2020-01-28 at 8 55 13 AM" src="https://user-images.githubusercontent.com/26032343/73286137-ee36c000-41ab-11ea-8099-3f2bda4e96a9.png">


Closing the issue
