### ISSUE TITLE
Bug: Image name in workload view does not wrap

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#24828]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Deploy workload with image name that is very long.

**Result:**
Text does not wrap as shown in this screenshot.
![image](https://user-images.githubusercontent.com/44879867/71694707-f868c880-2d7d-11ea-85a0-d12905f1e396.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): HA

**Comment by westlywright** [comment]
The bug here is that the image name is not being clipped. The image name is wrapped in a tooltip for this exact reason but the clipping was not working. The reason we clip here instead of wrapping is the table view starts to look really wonky when wrapping. Placing the name in a tooltip made more sense design wise and while still allowing users to access the entire name if so desired.

**Comment by khushboo-rancher** [comment]
Tested in master-2399-head - 926997017

1. Created a workload with image having long name.
2. Cluster -> project -> workload, image name appears with clipping.
3. Cluster -> System -> workload, image name appears with clipping.
4. Created ingress with long value in path, it gets wrapped.

Text appeared in v2.3.3
<img width="1404" alt="Screen Shot 2020-03-09 at 2 58 47 PM" src="https://user-images.githubusercontent.com/60111667/76261985-7cc14700-6218-11ea-9000-7b694a3a5073.png">

Text appeared in master-2399-926997017
<img width="1346" alt="Screen Shot 2020-03-09 at 2 42 51 PM" src="https://user-images.githubusercontent.com/60111667/76262004-85b21880-6218-11ea-996a-3052057f59c6.png">
