### ISSUE TITLE
Dynamic host labels 

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2483]
Hi,

it would be nice to have the ability to put down host labels via some configuration management process.

In our environment, we use Puppet extensively and we do have a number of facts that drive the whole configuration of the machine. These facts could also be used as rancher host labels to make decisions on where a container should be eventually scheduled.

I believe there's a lot of value in adding support for this.

Cheers,
Matteo

**Comment by cloudnautique** [comment]
If Puppet is handling the rancher registration process, you can set host labels by adding the following env var: `-e CATTLE_HOST_LABELS='key=value&key2=value` to the docker run command for the agent registration.

 We could do something else if that doesn't work, but curious if that meets your use case.

**Comment by m4ce** [comment]
@cloudnautique,

I missed to find CATTLE_HOST_LABELS in the official Rancher docs :)

That would do it. However, it opens an other question https://github.com/rancher/rancher/issues/2473 which is how I should manage rancher-agent via Puppet, since the first container is only a bootstrap process and then shuts. My intention would be to manage rancher-agent as a systemd unit.

Will close this, thank you!

Matteo

**Comment by cloudnautique** [comment]
@m4ce, its been a while since I wrote puppet, but you'll need something that checks if "rancher-agent" container is running. If not, then run the registration script. The rancher-agent is started up with restart always if I recall, and will be brought up with Docker. Docker ultimately ends up managing the process handling for the agent. As far as making it a systemd unit, we will have to look into that some.
