### ISSUE TITLE
Ability to post data to Rancher Metadata Service

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2484]
Hi,

currently, it seems that the Rancher Metadata Service can only be queried, please correct me if I am wrong :)

It would nice if one could also post data, effectively using it as a key value store.

This is especially useful for sharing some configuration data (e.g. node id NOT based on current create_index) across multiple instances of the same service.

One could make a specific endpoint like /self/container/custom/key = value available for posting data, so that other instances can then retrieve it via /containers/container/custom/key.

Thanks,
Matteo

**Comment by deniseschannon** [comment]
There is the ability to add user metadata (currently only supported by using rancher-compose to start a service). 

http://docs.rancher.com/rancher/metadata-service/#adding-user-metadata-to-a-service

Would that satisfy your use case?

**Comment by m4ce** [comment]
Hi @deniseschannon,

Thank you for your reply.

I am already aware of the metadata feature through rancher-compose, which I am using to store static configuration of the service.

What I am after is a key value store where I could post data  when the container comes up, specifically in between upgrades.

My scenario involves sharing between containers of the same service some piece of information that can only be produced during the application runtime.

Now, I know I could achieve that by deploying my key-value store in rancher, but just wonder if one could piggyback on to the Metadata service since it's already there.

Thank you for your help.
Matteo

**Comment by ibuildthecloud** [comment]
I'd definitely like to here more from the community if a lot of people would find this useful.  We've definitely considered it but then we contrast it with consul/etcd.

One could just run one of these keystores to accomplish this.  If we did support writing to metadata the consistency guarentees would probably be very basic and different from consul/etcd.

What I'm thinking is that writes would be eventually consistent and last write wins.  Basically you wouldn't depend on this as database because the guarentees would be poor and the replication would be relatively slow.  In this situation I would expect writers to leverage the create_index in the metadata to do leader election so one container could write important information and the others could read.

As I think about this I like it very much :smile:   Please let me know what you think about these ideas.

**Comment by m4ce** [comment]
@ibuildthecloud,

```
What I'm thinking is that writes would be eventually consistent and last write wins. Basically you wouldn't depend on this as database because the guarentees would be poor and the replication would be relatively slow. In this situation I would expect writers to leverage the create_index in the metadata to do leader election so one container could write important information and the others could read.
```

That would actually be one of the use cases I have. In the meantime, I can definitely deploy my own key-value store.

However, long term I would dislike this option. The reason is the number of dependencies I need to operate the availability of a service. I already have a dependency on metadata service, why having another that will also have again the metadata service as a dependency? I would deploy etcd or consul on top of Rancher.

From an operational point of view, If I could look at the metadata service as the only component I need to ensure that a cluster of services can be brought up and down, that would be great. It also simplifies things quite a bit.

Thanks,
Matteo

**Comment by AnalogJ** [comment]
+1
This would be really useful for me, especially to pull dynamically generated API keys from application and share them with another.

**Comment by raphink** [comment]
Rancher is easier than setting up swarm+consul+consul-based-haproxy because it doesn't make it necessary to manage all these components. If there is a need to add consul on top of rancher in order to share information between services, then there's no reason not to use this consul for the LBs and swarm, too, and get rid of rancher altogether. So I'd +1 a way to use the rancher metadata as a mean for containers to communicate information.

**Comment by vincent99** [comment]
This is not going to happen for 1.x, and 2.0 doesn't have metadata.
