### ISSUE TITLE
Kiali Traffic Graph not displaying

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#24852]
v2.3-head (default ui-index, 2.3-latest https://releases.rancher.com/ui/latest-2.3/index.html) 1/3/20 `a21dd0bab`

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster with k8s 1.16 or 1.17. You need plenty of resources for istio.
- As either the admin or cluster owner user, enable Istio including the Ingress Gateway.
- Deploy some test YAML (attached)
- Hit the necessary endpoint to generate traffic either manually refreshing a few times or using a tool such as `hey` example endpoint: http://ip_address:31380/productpage/
- Go to the project and on the nav bar, Resources > Istio and go to the Traffic Graph tab

- Try again with rc6 -- notice it's working here, but it brings us to the wrong page. It brings us to the default Kiali home page instead of to the /console/graph page (e.g. like /console/graph/namespaces/?edges=noEdgeLabels&graphType=versionedApp&namespaces=&unusedNodes=false&injectServiceNodes=true&pi=15000&duration=60)

**Result:**
Nothing comes up for the Traffic Graph. We just see "Not enough data for chart" we don't even have the namespace selector drop-down.
![image](https://user-images.githubusercontent.com/45179589/71746880-5d2e2c80-2e2b-11ea-9562-3ae6aff76cd5.png)

**Other details that may be helpful:**
See attached for test YAML to deploy test app. You can then hit the /productpage/ endpoint to generate traffic.
[v1.16-v1.17-test-yaml.txt](https://github.com/rancher/rancher/files/4020769/v1.16-v1.17-test-yaml.txt)

**Comment by davidnuzik** [comment]
This is probably related. Can't get some graphs and can't access some endpoints

![image](https://user-images.githubusercontent.com/45179589/71748682-8bfad180-2e30-11ea-9854-23e70c57d360.png)

When fix is in QA should review the UI and ensure we can access everything as expected. In this case I was the admin user.

**Comment by davidnuzik** [comment]
Based on in-person discussion we determined the issue does not happen in ui-index https://releases.rancher.com/ui/2.3.29/index.html

**Comment by westlywright** [comment]
Available in `latest2` and `latest-2.3`

**Comment by rancher-max** [comment]
This is what's showing up now:
![image](https://user-images.githubusercontent.com/55997940/71754771-f0c02700-2e44-11ea-9654-b419a17f2bb8.png)

I believe this is what is expected:
![image](https://user-images.githubusercontent.com/55997940/71754836-3a107680-2e45-11ea-9bb9-40c16ad09651.png)

@loganhz @davidnuzik Might understand how this should work better... The value in the iframe src is: `/k8s/clusters/c-47bjb/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/console/graph/namespaces/?edges=noEdgeLabels&amp;graphType=versionedApp&amp;namespaces=default&amp;unusedNodes=true&amp;injectServiceNodes=true&amp;layout=dagre`

**Comment by rancher-max** [comment]
Going directly to the kiali graph link works in `2.3.3` but does not in `2.3-head`:

https://1.2.3.4/k8s/clusters/c-12abc/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/console/graph/namespaces/?edges=noEdgeLabels&amp;graphType=versionedApp&amp;namespaces=default&amp;unusedNodes=true&amp;injectServiceNodes=true&amp;layout=dagre

**Comment by rancher-max** [comment]
Everything else on this issue is fixed with `latest-2.3` and `latest2` ui-index other than:
> [Traffic Graph] brings us to the wrong page. It brings us to the default Kiali home page instead of to the /console/graph

**Comment by westlywright** [comment]
I do not believe this is a UI issue, @strongmonkey @logan may need to chime in here. From what I know, we used to have some hacks in place on the back end so that link would correctly load the namespace graph through the iframe. This doesn't seem to be working which is why you have to click to get to the correct namespace. The UI should not be solving this problem, if there is custom routing work to be done the UI doesn't have control over this.

**Comment by rancher-max** [comment]
### Traffic Graph fixed in https://github.com/rancher/system-charts/pull/145

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/55997940/72275637-8731dc80-35eb-11ea-823d-e03978f2b0a2.png">

Validated both in upgrade testing and fresh install. Scenarios for both:
**Upgrade:**
1. Create cluster on rancher v2.3.3
2. Enable latest Istio (v0.1.1) with gateway enabled and all user access to Kiali.
3. Deploy workloads, gateway, virtualservice and validate everything is working as expected
4. Upgrade rancher to v2.3-head
5. Change global system-chart to use the PR above
6. Navigate to cluster tools --> Istio page and validate an upgrade is available. Dropdown shows current version and latest version (v1.4.3).
7. Navigate to cluster System Apps --> cluster-istio should have Upgrade available.
8. Validate deployments are working correctly before upgrading istio
9. Upgrade istio to v1.4.3
10. Validate deployments are still working through gateway and nodeport
11. Redeploy workloads and validate they have the new version of istio sidecars, and that they are still accessible.
12. Traffic Graph should show traffic correctly.
13. Istio functionality should generally work properly with full p1 workflow.

**Fresh Install**
1. Same steps as 1-3 above, using Istio v1.4.3
2. For this issue, also validated that multiple namespaces in the same project with istio sidecar enjection enabled showed up on the Traffic Graph page and that I was able to switch between them and see the traffic graph:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/55997940/72276484-3b803280-35ed-11ea-8519-e6cf9d786d18.png">

**Comment by rancher-max** [comment]
Confirming Rancher versions this is fixed:

`v2.3-head commit a21dd0bab`
`master commit 6c488064c`

Both using system-charts `dev` branch.

**Comment by aledr** [comment]
I'm using v2.4.5.
Saw no graphs on *Traffic Metrics* page and following error on the request:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kiali-http\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kiali-http",
    "kind": "services"
  },
  "code": 404
}
```

Can it be related to this issue?

**Comment by cbron** [comment]
@aledr what version of Istio and how was it installed ? Rancher replaced the `kiali-http` service with one named `kiali` after 0.1.1, and the UI in 2.4.5 would be looking for that. Check to see what services exist in the istio-system namespace.

**Comment by aledr** [comment]
Rancher v2.4.5
Istio 1.4.10

Istio was installed and being upgraded inside Rancher itself.

A kiali service exists in istio-system namespace.

Full list of Services in istio-system are:
istio-citadel
istio-galley
istio-ingressgateway
istio-pilot
istio-policy
istio-sidecar-injector
istio-telemetry
jaeger-agent
jaeger-collector
jaeger-query
kiali
tracing
zipkin
kube-dns

**Comment by cbron** [comment]
Followed up separately, but that error message is unrelated as it is for graphs page. Most likely the “Not enough data” message is due to averages being too low, so try adjusting search time and ensure you have traffic.
