### ISSUE TITLE
Clarify the option to override CNI MTU in the UI

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#24929]
This is how the option is presented in `v2.3-head`:

<img width="1140" alt="Screenshot 2020-01-13 at 15 33 25" src="https://user-images.githubusercontent.com/2620179/72263971-32f22100-361a-11ea-8dae-eef042f44edf.png">

This should be clarified as the terminology is ambiguous.

- Need to clarify this is overriding the default calculated CNI MTU
- Need to clarify this needs to be calculated by the user (host MTU minus overhead needed for CNI plugin)
- Option needs to be presented better, e.g. disabled when 0 and made active when it gets focus or similar to what we already use

**Comment by westlywright** [comment]
@superseb I am making updates for the first two bullets but the third bullet doesn't make sense. This is exactly how this input is supposed to be used. The type of that value in the schema is an int, the schema has a default value of `0` which is what is displayed. I believe what you're referring to is when an input for a value doesn't have a default in the schema, in which case we revert to a placeholder value and may make the input look disabled because there is no data in the input. Is this what you're referring to? Unless there is a compelling reason to write custom logic to remove the default value for this I see no need to change the UI in regards to the third bullet. Even if there was I would argue we need a different default value or we should remove the default from the schema if one shouldn't be present as writing one off custom logic for that stuff is not best practice.

**Comment by superseb** [comment]
That's fine, if we dont use it we can just refer to 0 being auto-detect as that is the behavior as of today (without configurable CNI MTU).

**Comment by westlywright** [comment]
Available on `latest2` and `latest-2.3`

**Comment by jiaqiluo** [comment]
The bug fix is validated in 
- Rancher v2.3-head 9243de496 with the default UI index `https://releases.rancher.com/ui/latest-2.3/index.html`
- Rancher master-head 88fcc20ad with the default UI index `https://releases.rancher.com/ui/latest2/index.html` 

Steps:
- run Rancher single install
- add a new RKE based cluster

Result:
- see the filed for MTU and an explanation under it
<img width="493" alt="Screen Shot 2020-01-13 at 7 20 27 PM" src="https://user-images.githubusercontent.com/6218999/72308944-cb989900-363a-11ea-9eb5-073803ac9da5.png">
