### ISSUE TITLE
rancher logs show kube-kubelet-* certificate and key generated for the CIS compliant cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24942]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.3-head latest - deploy a CIS compliant cluster(manual steps performed on nodes and cluster.yml is CIS compliant)
- Cluster spec - 8 nodes, 3 etcd, 2 control plane and 3 worker nodes.
- after the cluster has been provisioned, logs keep showing

```
2020/01/13 22:23:32 [INFO] [certificates] Generating Kubernetes Kubelet certificates
2020/01/13 22:23:32 [INFO] [certificates] Generating kube-kubelet-ip1 certificate and key
2020/01/13 22:23:59 [INFO] [certificates] Generating Kubernetes Kubelet certificates
2020/01/13 22:23:59 [INFO] [certificates] Generating kube-kubelet-ip2 certificate and key
2020/01/13 22:24:06 [INFO] [certificates] Generating Kubernetes Kubelet certificates
2020/01/13 22:24:06 [INFO] [certificates] Generating kube-kubelet-ip3 certificate and key
```
ip1, ip2, ip3 -- worker nodes in the cluster.

**Expected Result:**
certificate and key should NOT keep generating

**Note:**
This happens on a non CIS cluster when kubelet serving certificate is enabled
`generate_serving_certificate: true`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3-head latest - commit id: `2ac7bb59b`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by sowmyav27** [comment]
This issue is seen on `rancher:2.3.3` also.

**Comment by prachidamle** [comment]
The regeneration of the kubelet certs happens when `generate_serving_certificate: true` is set on the cluster and this is by design that everytime rancher server communicates the node plan to the workers, new certs get regenerated.
The worker agents will only apply them if the certs have expired or the ip/dns name has changed and a log will be seen when the cert is applied.

I checked the rancher-agent logs and I dont see any logs saying new certs have been applied. So even if new certs are generated, worker agent will ignore them.

This is not an issue, but by design you are seeing the log after every few minutes.

**Comment by sowmyav27** [comment]
**Verified on latest-master -head commit id: `e11d47814`**

- deploy a CIS compliant cluster(manual steps performed on nodes and cluster.yml is CIS compliant)
- Cluster spec - 8 nodes, 3 etcd, 2 control plane and 3 worker nodes.
- after the cluster has been provisioned, logs keep showing now in DEBUG mode

```
2020/02/19 23:47:45 [DEBUG] [certificates] Generating Kubernetes Kubelet certificates
2020/02/19 23:47:45 [DEBUG] [certificates] Generating kube-kubelet-172-31-14-244 certificate and key
```
