### ISSUE TITLE
[UI] Cluster Name being ignored during Add Cluster when switched to "Edit as YAML"

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#24971]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. Add Cluster from Rancher UI (Custom)
2. Click "Edit as YAML"
3. Enter Cluster Name in the UI(Above "Member Roles")
4. Click "Next"
5. An error message appeared on the UI "Validation failed in API: Cluster name is required"

**Result:**
An error message appeared on the UI "Validation failed in API: Cluster name is required"

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): HA

**Comment by aaronRancher** [comment]
The bug is still seen with Rancher server `rancher\rancher:master-head` `version ca01ddff2`
Steps:
`Add Cluster`
Click "Edit as YAML"
Enter Cluster Name in the UI
![Screen Shot 2020-02-04 at 2 42 29 PM](https://user-images.githubusercontent.com/57409052/73790028-09ca3980-475d-11ea-96ee-aa3c24cf8e20.png)
Set nodes and click `Next`
UI error shows `Validation failed in API: Cluster name is required`
![Screen Shot 2020-02-04 at 2 43 09 PM](https://user-images.githubusercontent.com/57409052/73790092-24041780-475d-11ea-94fe-d4b1dd337d6c.png)

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.3`
Steps:
`Add Cluster` (DO cluster was used in this example)
Click `Edit as YAML`
Enter Cluster Name in the UI
Set nodes and click `Next`
UI error shows `Validation failed in API: Cluster name is required`

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 1a03ecea3`
