### ISSUE TITLE
Migration path away from Istio helm install

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#24976]
Istio is deprecating their helm chart: https://preliminary.istio.io/blog/2019/introducing-istio-operator/#migration-from-helm

While [26786](https://github.com/rancher/rancher/issues/26786) will handle the implementation details of the 1.6 install, this ticket will specifically handle moving from 1.4 to 1.6 and the wider infra/UI changes.

- [ ] 1) Update rancher controllers to handle multiple versions of istio being installed.
- [ ] 2) Allow an uninstall of 1.4 to not disrupt 1.6. Some of this work will be in UI.
- [ ] 3) Update the UI to handle the templating of the new helm chart and multiple installs at the same time.
- [ ] 4) Allow users to pass in custom IstioOperator CR in UI that gets layered on top
- [ ] 5) [Egress gateway](https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/) should be a first class citizen in UI
- [ ] 6) Enable moving between different canary versions to be done easily in the UI via switching the injection label on a namespace.

**Comment by cbron** [comment]
Will also need to address CNI plugin install for PSP enabled clusters, as it is also installed via helm: `{docs}/cluster-admin/tools/istio/setup/enable-istio-in-cluster/enable-istio-with-psp/`

**Comment by LinAnt** [comment]
Istio will eventually move to having its lifecycle handeled through the operator. Upgrading from 1.4.4 -> 1.5.0 already assumes you are using `IstioOperator` objects for configuring your control plane.

https://istio.io/docs/setup/upgrade/istioctl-upgrade/

**Comment by cbron** [comment]
https://github.com/istio/istio/issues/22148#issuecomment-606794875

**Comment by howardjohn** [comment]
What are your requirements? Do you just need to install istio with some settings? Expose those settings to users? Specifically use helm?

**Comment by cbron** [comment]
@howardjohn thanks for asking. We have a lot of infrastructure built up around helm, and for istio specifically we also use it to:
* Modify settings and expose settings to users
* Specify private registry _and_  use custom images
* Add install/upgrade/delete hooks for things like CRDs and rbac
* Add extra resources (configmaps, deployments) and modify Istio deployments to tie the two together.

**Comment by howardjohn** [comment]
@cbron thanks. For some additional context, as part of the new install using istioctl/operator (they are both the same code base for the most part), we have a new set of helm charts that are used internally.

In 1.5, we offer the istioctl installation and the legacy helm charts.

In 1.6, we will drop the legacy helm charts, but its possible, due to users like yourself and others that depend on helm, we will support users directly using the helm charts that istioctl is using internally. See the `manifests/` folder of the istio/istio repo for these. Its not yet decided if we will "officially" support these as a first class installation method, or if it will be more community driven
