### ISSUE TITLE
Pushing multiple Docker images in parallel in Rancher pipeline

### ISSUE THREAD

**Issue by alinturbut** [rancher/rancher#24988]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** Create a step for pushing all images in parallel.

```- name: Publish images
  steps:
    - publishImageConfig:
        dockerfilePath: ./frontend/deployment/Dockerfile
        buildContext: ./frontend
        tag: registry.remote.com/remote/frontend-${CICD_EXECUTION_ID}
        pushRemote: true
        registry: registry.remote.com
    - publishImageConfig:
        dockerfilePath: ./gateway/backend/src/Dockerfile
        buildContext: ./gateway/backend
        tag: registry.remote.com/remote/backend-${CICD_EXECUTION_ID}
        pushRemote: true
        registry: registry.remote.com
    [...]
```

**Result:** One image is pushed, but all the rest fail with `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Other details that may be helpful:**

I've also tried increasing the --max-concurrent-uploads from /etc/docker/daemon.json without any success.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): - 
- Kubernetes version (use `kubectl version`): v1.14.3

**Comment by jean-leonco** [comment]
Has someone managed to solve it? I'm struggling with a similar same setup

**Comment by alinturbut** [comment]
@jean-leonco they have 4000 open tickets, 160 open PRs, I doubt there is any project / task / repository management going on. I wouldn't hold my breath...

**Comment by vincent99** [comment]
Pipelines are deprecated in 2.5 and will not be getting any future updates.

@alinturbut I'm sorry you didn't get a response a year ago.  But managing a large open source project & community is not as magically easy as you think it is.

This repo aggregates issues for over 300 other repos (that have issues disabled) because watching them individually is impossible.  We don't use "stale bots" to keep the list artificially low like many other projects, because this is (I assume) still a real issue.  If enough people found it and cared about it and commented on it, it would get attention. ..if the feature weren't also now deprecated.
