### ISSUE TITLE
Backup/Restore Rancher Catalog Apps with Velero

### ISSUE THREAD

**Issue by clayrisser** [rancher/rancher#24986]
How do I use Velero to backup and restore rancher catalog apps? I backed up a namespace and restored it fine, but the app did not show up on the apps page.

https://forums.rancher.com/t/backup-restore-rancher-catelog-apps-with-velero/16354

**Comment by Oats87** [comment]
This is likely due to the fact that the Rancher representation of an app is stored as a CRD within Rancher's local cluster.

**Comment by mharrend** [comment]
I found a possible solution which could maybe be helpful:
Besides using Velero in the production cluster, I deployed Velero in the local cluster.
Afterwards I configured Velero that the following ressources get backuped:

- app
- apprevisions
- project (not absolutely necessary, but still good to backup)

If you checkout these ressources, you will find that all the information about the corresponding app is stored as part of them.

So the recovery process can go look this:

1. The project and namespace should still be available. Otherwise, one can use the backuped project ressources to restore the project.
2. One restores the deployments by using the velero backup from the production cluster. As a result one should get back all the deployments etc. But these deployments are no longer part of an app.
3. One restores the app and apprevisions in the local cluster of Rancher. Afterwards, the deployments should be part of the original app again.

**Comment by gonarys** [comment]
> I found a possible solution which could maybe be helpful: Besides using Velero in the production cluster, I deployed Velero in the local cluster. Afterwards I configured Velero that the following ressources get backuped:
> 
> * app
> * apprevisions
> * project (not absolutely necessary, but still good to backup)
> 
> If you checkout these ressources, you will find that all the information about the corresponding app is stored as part of them.
> 
> So the recovery process can go look this:
> 
> 1. The project and namespace should still be available. Otherwise, one can use the backuped project ressources to restore the project.
> 2. One restores the deployments by using the velero backup from the production cluster. As a result one should get back all the deployments etc. But these deployments are no longer part of an app.
> 3. One restores the app and apprevisions in the local cluster of Rancher. Afterwards, the deployments should be part of the original app again.

Hi @mharrend how you configured velero to backup project (projectid) and when you restored the cluster, have you the same project id ?
