### ISSUE TITLE
Is it possible to run rancher agent without privileged access?

### ISSUE THREAD

**Issue by funkytaco** [rancher/rancher#2498]
Is it possible to run rancher agent without privileged access? Rackspace uses AppArmor with their new Carina product (docker swarm, essentially).

https://community.getcarina.com/t/whats-the-path-to-docker-sock-i-need-it-for-rancher-agent/45

**Comment by cloudnautique** [comment]
Hmm, we add --privileged because we bind mount in the docker socket of the host. Which essentially gives the container privileged access. We are making it explicit. Looking at the reference documents posted in the forum, it doesn't look like you could bind mount in the docker socket either. We will have to look into Carina a bit more to see what it would take.

**Comment by disaster37** [comment]
I think SYS_ADMIN capabilities is sufficient to mount on docker container ?

**Comment by cloudnautique** [comment]
On the RedHat variants you need privileged. Also, it appears carina disables cap_add and cap_drop as well.

**Comment by funkytaco** [comment]
So I take it no way to use it with Rackspace Carina? Shipyard 3's  agent somehow runs without privileged, but I'm not sure that's an apt comparison.

**Comment by cloudnautique** [comment]
@funkytaco no, not at this time. I'm not to familiar with Shipyard, but it looks like they communicate remotely with the Docker socket over TLS. Which means you have to expose the Docker socket to the Shipyard API server, and do not need privileged container access to the socket. If that is the case, then shipyard / Rancher are not exactly an apples to apples comparison.

**Comment by funkytaco** [comment]
Bummer. Okay, thanks.
