### ISSUE TITLE
[Enhancement] Upgrade prometheus-operator version

### ISSUE THREAD

**Issue by spencergilbert** [rancher/rancher#24995]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Run cluster-monitoring (or any prometheus created via current prometheus-operator) configured with a Thanos sidecar (available in rancher-monitoring 0.0.7) inside of a istio service mesh

**Result:**
thanos-sidecar will be inaccessible

**Other details that may be helpful:**
https://github.com/coreos/prometheus-operator/commit/67bccfd45bbf6c8db46b608d46a38ee4cc207f42 <- newer operator versions allow additional configuration needed to run a thanos-sidecar inside of an istio service mesh

I made a quick attempt at upgrading the existing manifests in the system-charts repo: https://github.com/rancher/system-charts/pull/136

**Environment information**
- Rancher version: 2.3.3
- Installation option (single install/HA): HA

**Comment by cbron** [comment]
This may be working with v2 monitoring.

**Comment by aiyengar2** [comment]
Based on the commit referenced in the issue description and the drafted PR, this issue required an upgrade of the Rancher Monitoring V1 chart to a minimum of Prometheus Operator `v0.34.0` for the Thanos sidecar to be accessible. The current Monitoring V1 chart (`v0.1.3`) is using Prometheus Operator [`v0.38.1`](https://github.com/rancher/system-charts/blob/21ee063cc7c8dfbbe4ff4198371e066663f5f026/charts/rancher-monitoring/v0.1.3/values.yaml#L7), so this issue should be resolved. No need to upgrade to Monitoring V2.

Since the prometheus-operator version has been updated, I'm closing out this ticket as it should be resolved.

@spencergilbert please open up a new issue and tie it to this ticket if you are still encountering this.
