### ISSUE TITLE
Possibility to save own stack as template in a Catalog ( official or private)

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#2500]
The addition of a Catalog of docker-compose+rancher-compose is a great enhancement to Rancher.

We have a couple of feature requests related to this:

1. Possibility to save private stack as templare in official catalog/add private catalog
2. Enable versioning of stack templates

1.
As a Rancher owner/admin I would like to be able to save Stacks I created within my development team as Templates in the Catalog. Alternatively the possibility to at least add own private Catalogs (project catalogs) on the side of Rancher official Catalog. This way different teams would be able to experiment and create their own stacks and save them in the project Catalog.

This also useful for Rancher so that more stacks becomes available for reuse in the official catalog.

I do know that the current Catalog is connected to a rancher github repo. It would be fairly simple to allow rancher admin to add private catalogs, just by indicating the github repo to add. Partially related to #2481

2.
Having them in github, makes it also possibile to provvide another important missing feature: versioning of stacks. So user can see if a stack templare gas bene updated and which version is in sue.(this is probably another distinct feature)

Thanks!

**Comment by vincent99** [comment]
Templates are revision controlled (git) and versioned (the user can choose between different releases of the catalog application).  When a new version is available the UI shows an upgrade button and will do an in-place upgrade.  Since the catalog is new there just aren't any versions, except the [ElasticSearch](https://github.com/rancher/rancher-catalog/tree/master/templates/elasticsearch) template has two so QA could test upgrade.  You'll need to specifically choose the older one when initially deploying it since it defaults to the newer one.

You can do private catalog today with a little bit of work; change /v1/settings/catalog.url to a different url `git clone ...` can pull (possibly but not necessarily a fork of our [rancher-catalog](https://github.com/rancher/rancher-catalog)) and then restart the rancher/server container.  We will support multiple catalog URLs soon so you can add your own additional things without having to fork ours.

**Comment by demarant** [comment]
@vincent99 
thanks, this is great news.
so basically stack versioning (point 2) is already in place, I just did not see it, because I expected it to be displayed a ver.# directly on the template card, than I realised that only when you click "Launch" you get the option of versions...

regarding the "private catalogs", where do I find the /v1/setttings/catalog.url property?

**Comment by vincent99** [comment]
Click on the user menu in the top-right -> API & Keys -> click on the endpoint URL to bring up the API;  Then change the path in the browser to `http://your-rancher-server:8080/v1/settings/catalog.url` (if you have access control off or are already logged in you can actually go straight there).

**Comment by demarant** [comment]
@vincent99 thank you! I [forked the rancher-catalog](https://github.com/eea/rancher-catalog) and followed your steps. It was easy and it works fine. I look forward for the multiple catalogs or a way to submit community-supported catalog entries to the official rancher catalog.

**Comment by demarant** [comment]
I close this issue as since v0.50.0 it is possible to add own catalogs.
