### ISSUE TITLE
cannot convert int64 to float64

### ISSUE THREAD

**Issue by dorsany** [rancher/rancher#25036]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1) install rancher higher than `v2.3.1`
2) try to install kong or strimzi using helm

**Result:**
```
 Error: unable to convert to CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: cannot convert int64 to float64
```

**Other details that may be helpful:**
because you updated the helm verison inside rancher from `v2.10.0-rancher10` to `v2.14.3-rancher1` we experienced the bug above.
please downgrade the helm version to `2.13.1` or to helm version without this bug.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

related: 
https://github.com/helm/helm/issues/5806
and
https://github.com/helm/helm/issues/5750

**Comment by dorsany** [comment]
FYI - @dramich @alena1108

**Comment by dramich** [comment]
@dorsany I am not sure how much effort we will put into changing anything around helm 2, we run our own fork and requires applying changes to new versions along with QA time to do a version change. Helm 3 is out now which is where we are focusing our efforts in order to get that integrated into Rancher.

**Comment by dorsany** [comment]
Thank you for the information
