### ISSUE TITLE
Rancher-prometheus cannot co-exist with another instance of prometheus

### ISSUE THREAD

**Issue by tomerleib** [rancher/rancher#25044]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable monitoring to install rancher-prometheus on `cattle-monitoring` and wait for everything to work.
Install the helm chart for `prometheus-operator` on another namespace.

**Result:**
Prometheus instance on the monitoring namespace will fail to start with the error:
`Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a9ae5bd99d417ecbecd2033e253b1178a5c36a167aac7db85ebbbee88db5cde0" network for pod "prometheus-prometheus-operator-prometheus-0": networkPlugin cni failed to set up pod "prometheus-prometheus-operator-prometheus-0_monitoring" network: failed to Statfs "/proc/20810/ns/net": no such file or directory`

At the same time, the prometheus on `cattle-monitoring` is killed:

```bash
kubectl get events -n cattle-monitoring
LAST SEEN   TYPE     REASON    OBJECT                                MESSAGE
35m         Normal   Killing   pod/prometheus-cluster-monitoring-0   Stopping container prometheus-config-reloader
35m         Normal   Killing   pod/prometheus-cluster-monitoring-0   Stopping container prometheus-agent
35m         Normal   Killing   pod/prometheus-cluster-monitoring-0   Stopping container prometheus-proxy
35m         Normal   Killing   pod/prometheus-cluster-monitoring-0   Stopping container prometheus
35m         Normal   Killing   pod/prometheus-cluster-monitoring-0   Stopping container rules-configmap-reloader
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): 

```
Client Version: v1.16.3
Server Version: v1.16.3
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

gz#10295
gz#14382

**Comment by Kampe** [comment]
I have the same issue, as soon as I enable monitoring all hell breaks loose.

I install prometheus with the coreos operator myself, so when Rancher tries to lay that down as well, everything fails, causing my prometheus to spin out of control and terminate itself in a loop.

**Comment by robertgates55** [comment]
Also having this issue.

**Comment by Tejeev** [comment]
We see the same in two downstream clusters in a Rancher v2.4.4 deployment. 
It would appear that if monitoring is enabled at the cluster level, users can not deploy prometheus-operator with kubectl.
 We are able to deploy Project-level Monitoring and Prometheus Apps to private namespaces successfully.

**Comment by Tejeev** [comment]
@maggieliu Do we have a workaround for this?

**Comment by aiyengar2** [comment]
@Tejeev is there a specific use case you have for running multiple Prometheus Operators on the same cluster? The root cause of this issue is that Rancher and Prometheus Operator are both deploying prometheus-operator pods, which (unless otherwise configured) will both try to manage the same CRDs within the cluster. 

This is not recommended by Prometheus Operator, as noted in the following excerpt from the [`README.md`](https://github.com/helm/charts/blob/master/stable/prometheus-operator/README.md#prometheus-operator-1):
Parameter | Description
-- | --
`prometheusOperator.enabled` | Deploy Prometheus Operator. Only one of these should be deployed into the cluster

Rancher Project-level monitoring does not encounter this issue as we do not redeploy the actual operator itself:
https://github.com/rancher/rancher/blob/9b4685f29518f6dd7c763c516d856570ff04ca5d/pkg/controllers/managementagent/monitoring/projectHandler.go#L166

Can you try disabling the `prometheusOperator.enabled` flag while deploying the chart onto a different namespace when Rancher Monitoring is enabled?

**Comment by Tejeev** [comment]
Hi @aiyengar2,
This comes up often as users of the clusters often have their own internal reasons for deploying their own monitoring.  The last use case was because they had their own deployment because Rancher Monitoring had experienced OOMs (I believe this was a result of bad defaults and a lack of a clear way to determine good ones in the UI) and had customized it to their liking over time without the risk of their configs being lost on upgrades, but then they required Istio which failed due to the multiple Prometheus Operators.

**Comment by aiyengar2** [comment]
@Tejeev that makes sense. In [Monitoring V2](https://github.com/rancher/rancher/issues/26549), these types of use cases will be more easily supported since the user should be able to configure / override any settings that can be configured in the Prometheus Operator upstream chart without relying on the Rancher UI to expose those options.

There still won't be support for multiple Prometheus Operators within the same cluster (although it should be possible to carefully achieve that if required by making sure the Prometheus Operators are not managing the same CRDs).

**Comment by Tejeev** [comment]
@aiyengar2 how would we configure the Prometheus Operators to manage different CRDs?

**Comment by Tejeev** [comment]
Another use case is deploying sumologic https://github.com/rancher/rancher/issues/26111

**Comment by aiyengar2** [comment]
@Tejeev in regard to having multiple `prometheus-operator` Pods in the same cluster:

For Monitoring V1, I don't believe there is any currently available way to configure the Rancher-managed `prometheus-operator` Pod to manage different CRDs since those options are not exposed on Rancher.

For [Monitoring V2](https://github.com/rancher/rancher/issues/26549), you should be able to limit the scope of Rancher-deployed `prometheus-operator` pod based on the fields for `prometheusOperator.namespaces` / `prometheusOperator.denyNamespaces` to particular namespaces that the CRDs should be pulled from; this would need to be similarly provided on the SumoLogic [`values.yaml`](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/668136c72cb896117de46fb3451e440655717535/deploy/helm/sumologic/values.yaml#L780-L810) to prevent the two `prometheus-operator` Pods from managing CRs in the same namespaces.

If you do not need to have multiple `prometheus-operator` pods, however, another solution would be to just disable all other components except the [Prometheus CR fields](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/668136c72cb896117de46fb3451e440655717535/deploy/helm/sumologic/values.yaml#L811-L1181) in the `prometheus-operator` Helm subchart of the SumoLogic chart so that just the Prometheus CR is deployed. I believe this should work for both Monitoring V1 and Monitoring V2, although I haven't personally tested deploying a Prometheus CR that is not managed by Rancher in Monitoring V1.

**Comment by aiyengar2** [comment]
https://github.com/prometheus-operator/prometheus-operator/commit/b9571bdee8d7636bad1d434d781dbf09e8aca53f#diff-bb97947e3dc86ea3008b99ce3372c6ac75936c5d86f7bf2bb4a7aa10d625fe21 might help mitigate this problem with Monitoring V1, since it allows us to say that we limit the scope of Prometheus Operator to CRs within the `cattle-prometheus` namespace (which is where all the CRs used by Monitoring V1 are created) while still allowing the Operator to manage Prometheus CRs only that are deployed in namespaces where Project Monitoring V1 is enabled.

You would still need to configure Monitoring V2 to set denyNamespaces to those projects with Monitoring V1 enabled.

It will only be available in a later version of Prometheus Operator though that is strictly deployable in Kubernetes 1.16+ clusters.
