### ISSUE TITLE
globalRoles - Issue while cloning Admin Global role

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25085]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Go to Global --> Security --> Roles
- Click on Admin user role
- Admin has the following roles

<img width="1304" alt="Screen Shot 2020-01-23 at 4 34 48 PM" src="https://user-images.githubusercontent.com/26032343/73035806-5b3e0480-3dfe-11ea-83f2-d98b3ea6d9f0.png">

- On the Admin role, click on Clone
- Recource - `Non-Resource URL:` is not copied on the new Role.
<img width="1312" alt="Screen Shot 2020-01-23 at 4 34 37 PM" src="https://user-images.githubusercontent.com/26032343/73035846-7741a600-3dfe-11ea-9adf-0bb7b6563f1e.png">

- Enter -`Non-Resource URL:` and click on Save
- Error seen in console - `Uncaught TypeError: Cannot read property 'slice' of undefined`
<img width="1670" alt="Screen Shot 2020-01-23 at 4 36 35 PM" src="https://user-images.githubusercontent.com/26032343/73035887-94767480-3dfe-11ea-94ee-ad3ade084041.png">

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest commit id: `47bf996c2`
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
@deniseschannon The reason for this error is outlined in the PR. Basically we never exposed `nonResourceURLs` as a separate parameter. I am not confident that I remember why this decision was made but I believe its a left over remnant of logic from before we allowed cloning or even viewing global roles from the UI. Because we do allow both of those things now I have exposed this new parameter in the UI. 

The UI doesn't do any additional validation as the API accepts any array of string in this parameter. But the [Kubernetes docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#policyrule-v1-rbac-authorization-k8s-io) to state the following:

> NonResourceURLs is a set of partial urls that a user should have access to. *s are allowed, but only as the full, final step in the path Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding. Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"), but not both.

If validation is required I believe this should happen on the backend as any user could easily bypass front end validation by using the api.

**Comment by sowmyav27** [comment]
**Verified on latest master- commit id: `7912bfdfa` ui tag: latest2**

- Go to Global --> Security --> Roles --> Global Roles
- Clone the admin role
- `Non-Resource URLs (path only)` is seen added as a separate parameter

<img width="1302" alt="Screen Shot 2020-02-04 at 1 27 48 PM" src="https://user-images.githubusercontent.com/26032343/73788639-3f1d5a00-4752-11ea-98d7-181c7dc7e716.png">

- When user adds a new global role, the nonResourceURLs and resources parameters mutually exclusive from the UI :

<img width="1341" alt="Screen Shot 2020-02-04 at 1 34 39 PM" src="https://user-images.githubusercontent.com/26032343/73789209-337e6300-4753-11ea-88dd-aa5f3aa16f3c.png">

- Through the API, user is abled to create a role where he can specify both nonResourceURLs and resources parameters.
- Role created has the rule:

```
rules:
- apiGroups:
  - '*'
  nonResourceURLs:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```
