### ISSUE TITLE
Container stats show up on host page but not detailed container page (for RancherOS hosts)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2510]
RancherOS v0.4.0
Rancher v0.431

On the host page, it appears that the container stats are being read. 

![screen shot 2015-11-02 at 10 40 50 am](https://cloud.githubusercontent.com/assets/11410997/10890680/3d3eb8f6-814e-11e5-8df0-245ecd649632.png)

But on the detailed container page, the stats are stuck in "Connecting" .

**Comment by robbertkl** [comment]
Same issue here. Host stats working, container starts not. RancherOS v0.4.1, Rancher v0.47.0.

**Comment by akafrmn** [comment]
Also have same issue:
RancherOS v0.4.1
RancherServer v0.47.0
rancher/agent-instance:v0.6.0
rancher/agent:v0.8.2

Next errors from console:
[Report Only] Refused to load the script 'http://ip.ip.ip.ip:49152/livereload.js?snipver=1' because it violates the following Content Security Policy directive:
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive:

**Comment by deniseschannon** [comment]
Verified with v0.49.0-rc1

**Comment by demarant** [comment]
@deniseschannon 
this issue just appeared to us after we upgraded from rancher v1.0.2 to v1.1.0.
we are on CentOS7 hosts (3.10.0-327.13.1.el7.x86_64) with docker engine 1.10.3 (not RancherOS).
