### ISSUE TITLE
CIS scan is not working for a newly created RKE cluster on Civo Cloud

### ISSUE THREAD

**Issue by saiyam1814** [rancher/rancher#25129]
Kind - BUG
Steps - 
- Cloud used - Civo cloud medium Virtual machine
- spin up rancher server
- create RKE cluster on cloud provider (using the rancher UI)
- run CIS scan
- scan completes successfully but when you open it , keeps on loading
CIS scan successful
![image](https://user-images.githubusercontent.com/8190114/73227680-48c72080-419a-11ea-9d1e-22fd98bdb3d5.png)
Cannot open the scan to see results and shows a UI error as well 
![image](https://user-images.githubusercontent.com/8190114/73227725-6f855700-419a-11ea-8756-8d25d9faba0e.png)

**Comment by leodotcloud** [comment]
Root cause: `pgrep` for etcd returned multiple results, causing a failure in the shell script.

**Comment by leodotcloud** [comment]
@codyrancher I think we should catch the exception in the UI and show the error rather than keep the spinner going. It would be nice if we don't have our users pull up the developer tools/console to figure out the error message. What say?

**Comment by sowmyav27** [comment]
**Hit this issue on master-head - commit id: `527a48207`**

- Cluster spec - 5 node - 3 worker node, 1 etcd, 1 control plane
- This happens when the CIS scan is run on a cluster and `etcd-rolling-snapshots` process is still running on the etcd node.

<img width="1878" alt="Screen Shot 2020-02-07 at 10 32 25 AM" src="https://user-images.githubusercontent.com/26032343/74071839-db956580-49b9-11ea-8e39-989366fadd0b.png">

**Comment by sowmyav27** [comment]
**Verified on master-commit id: `0f1c4b17d`**

- CIS scan was run on a cluster several times, Did not encounter this issue.
- Closing the issue now. Will reopen if this happens again.

**Comment by saiyam1814** [comment]
Hi Sowmyav27, whihc docker image I can use to verify this?

**Comment by sowmyav27** [comment]
@saiyam1814 currently the fix is on rancher `master-head`.
