### ISSUE TITLE
RFE - Add imagePullSecrets to rancher system charts

### ISSUE THREAD

**Issue by ebauman** [rancher/rancher#25217]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Currently you cannot specify `imagePullSecrets` for Rancher features such as Monitoring or Istio. This results in only being able to pull from a non-credentialed `system-default-registry` in Rancher, or use the default image repository.  

**Result:**
If you want to use a private repo that requires credentials, you cannot. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): Both

**Comment by KittyKatt** [comment]
Still experiencing this issue in v2.6.4 during Rancher deployment to a cluster. Specifying a system-default-registry fixes the path that the system charts request images at, but still doesn't allow them to pull them through our proxy because we cannot specify authentication. Is there any recommended fix to this?
