### ISSUE TITLE
Notifier: smtp_config tls boolean not respecting 'false' when creating through api/terraform

### ISSUE THREAD

**Issue by chrisreed87** [rancher/rancher#25321]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a basic email notifier, with tls boolean set to false:
```
 resource "rancher2_notifier" "email" {
   name = "email"
   cluster_id = "c-cmwc8"
   description = "test snmp notifier"
   smtp_config {
     default_recipient = "test@example.com"
     host = "127.0.0.1"
     port = 587
     sender = "test"
     password = "test"
     tls = false
   }
 }
```

**Result:**
Notifier TLS is still set to its default 'true', in UI and api
```
"smtpConfig": {

    "defaultRecipient": "test@example.com",
    "host": "127.0.0.1",
    "password": "test",
    "port": 587,
    "sender": "test",
    "tls": true,
    "type": "/v3/schemas/smtpConfig"

},
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.3.5
- Installation option (single install/HA): both

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
```

**Comment by rawmind0** [comment]
This issue is affecting rancher/types client. It's related with golang `Marshal` function from `encoding/json` that omits false bool if `omitempty` is set in the field definition, https://github.com/golang/go/issues/13284#issuecomment-157288425

Submitted PR https://github.com/rancher/types/pull/1083 to fix it.

**Comment by izaac** [comment]
I reproduced the issue in Rancher `master-head (06/04/2020)` 7e5b59b4e. I will check in a more recent build and then work in the `v2.4-head` build.

**Comment by izaac** [comment]
This is still setting `tls = true` in Rancher `v2.4.5-rc2` shown in API and UI.

```json
"smtpConfig": {
"defaultRecipient": "test@example.com",
"host": "127.0.0.1",
"port": 587,
"sender": "test",
"tls": true,
"type": "/v3/schemas/smtpConfig"
},
```
Basically I used the same terraform `rancher2_notifier` resource as described in this issue:

```terraform
 resource "rancher2_notifier" "email" {
   name = "email"
   cluster_id = rancher2_cluster.foo-do2.id
   description = "test snmp notifier"
   smtp_config {
     default_recipient = "test@example.com"
     host = "127.0.0.1"
     port = 587
     sender = "test"
     password = "test"
     tls = false
   }
 }
```

**Comment by rawmind0** [comment]
@izaac , you can't test this issue using terraform provider, due it's not patched yet. You should use rancher API to test it

**Comment by rawmind0** [comment]
Patched rancher2 terraform provider on PR https://github.com/terraform-providers/terraform-provider-rancher2/pull/362

**Comment by izaac** [comment]
@rawmind0 I didn't notice this was a two part fix for the terraform provider. 
This is working building the provider from the PR you mentioned in Rancher `v2.4.5-rc2` I will check Rancher `master` next.

**Comment by rawmind0** [comment]
Yes, building tf provider from PR should work fine for every Rancher version

**Comment by izaac** [comment]
Working also in Rancher `master-head (06/05/2020)` commit 9f6da9ed1

**Comment by izaac** [comment]
I will validate the other three fields that where fixed in the PRs

https://github.com/rancher/types/pull/1083
https://github.com/rancher/types/pull/1149

- `IgnoreDockerVersion` on `rke_types`
- `UseInternalIPAddress` on `NodeCommonParams` and `IgnoreDaemonSets` on `NodeDrainInput` on `machine_types`
- `Compress` on `FluentForwarderConfig` on `logging_types`

**Comment by izaac** [comment]
I was able to validate the three other fields fixed in the Rancher types PRs.

Terraform Provider build locally from: https://github.com/rancher/rancher/issues/25321#issuecomment-639582364

Rancher versions used:

- `v2.4.5-rc2`
- `master-head (06/05/2020)` commit 9f6da9ed1

Fields validated using Terraform Provider:

- `IgnoreDockerVersion` on `rke_types`
- `UseInternalIPAddress` on `NodeCommonParams` 
- `Compress` on `FluentForwarderConfig` on `logging_types`

Fields validated using API directly (I couldn't find a way to do so with the TF provider).

-`IgnoreDaemonSets` on `NodeDrainInput` on `machine_types` 

This field is in the cluster object:

```json
"upgradeStrategy": {
    "drain": false,
    "maxUnavailableControlplane": "1",
    "maxUnavailableWorker": "10%",
    "nodeDrainInput": {
        "deleteLocalData": false,
        "force": false,
        "gracePeriod": -1,
        "ignoreDaemonSets": false,
        "timeout": 120,
       "type": "/v3/schemas/nodeDrainInput"
    },
},
```

I was able to switch the boolean values.
