### ISSUE TITLE
[RFE] [vSphere] Have option to use guestinfo interface insead of mounting a config iso for clout-init

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#25336]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature

We currently install the [cloud-init-vmware-guestinfo](https://github.com/vmware/cloud-init-vmware-guestinfo) which adds the vmware guestinfo datasource for cloud-init. This allows us to provide the cloud config as a metadata string instead of needing to mount a config drive. We would like the option to use this feature on vsphere vm provisioning instead of it creating and mounting an iso as the config drive to reduce that extra disk dependency. 

For UX you could have a flag to change how the cloud config is injected.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): Latest Stable 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): N/A

**Comment by mitchellmaler** [comment]
We have started investigating Fedora CoreOS which by default wants you to use ignition and vmware guestinfo. Would be great if we can op-out on mounting the config iso since we do not need it.

**Comment by jameswu2** [comment]
Sounds like this request is asking for something similar to #35099. This is still a very important feature for us so we hope to see it re-opened.

**Comment by Martin-Weiss** [comment]
Can we get this re-opened? I see the same request for the customers I am dealing with..

**Comment by Martin-Weiss** [comment]
> Sounds like this request is asking for something similar to #35099. This is still a very important feature for us so we hope to see it re-opened.

@jameswu2 - could you give some details on why this feature is such important and what problem you see with the ISO method? In case you can - it would also be great if you could create a Support Case for this topic..

**Comment by jameswu2** [comment]
@Martin-Weiss Hi Martin, we've opened tickets with Rancher Federal on this topic before. They've provided a Rancher Engineering ticket number '00321714' to reference. 

[This comment](https://github.com/rancher/rancher/issues/25073#issuecomment-1007298845) on #25073 accurately describes our biggest challenges with the current NoCloud .iso behavior - primarily because the mounted .iso blocks VM migrations across ESXi hosts during upgrade cycles and because of the .iso file persisting on the datastore when node removal is not handled by Rancher (something that may need to happen if node provisioning is interrupted, for example).

Much of our infrastructure is vSphere so we consider this an appropriate solution to those problems by eliminating the need for  the .iso entirely while aligning with our environment. That being said, we would also be satisfied if Rancher always unmounts the .iso after a node has been provisioned and removes the file from the datastore.

This applies to both RKE1 and RKE2 clusters.
