### ISSUE TITLE
K3s integration to Rancher

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25371]
What kind of request is this:
Feature request/Backend development

Description:
Backend requirements for k3s integration to Rancher.

Additional Information:
rancher/rancher#25141

**Comment by daxmc99** [comment]
results of k3s sync-up @cjellick, @dweomer , @galal-hussein @rmweir:

**How will k3s version be determined**:
- client-go K8sClient.Discovery().ServerVersion 
https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L120
- @daxmc99 to determine if timeout concerns on this method are valid 

**How will Plans be used to upgrade the cluster** 
- 2 plans will be used: Master/ Non-master
- "Ordering" will be preserved by using the *Prepare* spec within the worker plan
- - ie: Master plans proceeds and worker plan has a *Prepare* spec to wait until master plan completes 
- - Goal of _not_ having Rancher run the upgrade, controller + plans should be self-sufficient. 
- - @galal-hussein to work with @dweomer to add *Prepare* logic to k3s-upgrade image

**Users who have previously used plans + system-upgrade-controller**
-  Rancher will create plans that disable all other plans
-  for example `plane.upgrade.cattle.io/<plan name>: <digest>` exists
- - rancher plan will have 
```
spec { 
         nodeSelector {
                            plane.upgrade.cattle.io/disable : true
```
- - rancher applies label `plane.upgrade.cattle.io/disable : true` to all nodes it sees

- If a user removes cluster from rancher they simply need to (preferably)  delete the label  or 
use a plan that specifically selects the disable label

**Comment by dweomer** [comment]
@daxmc99 @cjellick I thought that we decided that `upgrade.cattle.io/disable=true` on nodes was not necessary given plans `p0` and `p1` with `p0` being legacy aka pre-import and provided that we are able to leverage the assumption that `plan.upgrade.cattle.io/p1!=disabled` is the enabling label for `p1` which means that we put the equivalent of `!plan.upgrade.cattle.io/p1` aka `- {key: plan.upgrade.cattle.io/p1, op: DoesNotExist}` in the `spec.nodeSelector` of `p0`

**Comment by cjellick** [comment]
@dweomer, no - I came away with (almost) the same takeaway as @daxmc99.
When Rancher creates a plan, it first adds `upgrade.cattle.io/disable: true` to all non-rancher manager plans. I like this approach because the documentation explaining what we did is very simple and straightforward, something like:
> When Rancher assumes management of a K3s cluster after importing, it will ensure the k3s-upgrader is deployed. ...If Plans already exist in the cluster, Rancher will disable these plans by adding the `upgrade.cattle.io/disable: true` label to the node selector, causing the plan to not select any nodes...

The point being that that label name is easily identified and understood. Grokking "we added doesNotExist ../<some arbitrary name> p1 to your old plans is a bit harder.

**Comment by cjellick** [comment]
note: i said *almost* because:
1. The name i had for the label was `upgrade.cattle.io/disable: true`. But I'm not super attached to the name. If you two agree on plan.upgradel.cattle.io/disable, then that is fine.

2. This is wrong:
> rancher applies label plane.upgrade.cattle.io/disable : true to all nodes it sees
it adds this as a nodeSelector rule to the plan, it doesnt touch nodes. The point is to not have to update all the nodes in the cluster

3. This is slightly wrong:
> Rancher will create plans that disable all other plans

The plan will not disable all other plans. A rancher controller running in the Rancher control plane will do that before creating the rancher managed plans.

**Comment by dweomer** [comment]
@cjellick so `upgrade.cattle.io/disable=true` is to be applied to the Plan correct? I am fine with this change but it does mean I will need to alter the controller logic to handle such.

**Comment by dweomer** [comment]
@cjellick lets flip it around and add `upgrade.cattle.io/enabled=true` to the `nodeSelector` of existing plans.

**Comment by daxmc99** [comment]
I vote for a neutral label of `upgrade.cattle.io/rancher-managed=true` so that there is no confusion about the label enabling or disabling upgrades. It should be an opaque label for users. 

I think the exclusionary label idea is what will be best if we want to avoid adding a label to every node.

**Comment by daxmc99** [comment]
Partial controller work here: https://github.com/rancher/rancher/issues/25543

**Comment by sangeethah** [comment]
With latest builds from master , ability to upgrade imported k3s is available in rancher.

Issues found when testing this feature is tracked in https://github.com/rancher/rancher/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fimport-k3s
