### ISSUE TITLE
[vSphere] Rancher doesn't delete VM when it fails to startup due to vsphere error

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#25425]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Deploy a rancher cluster pool to a vsphere cluster that is not HA compliant such as one host in maintenance mode or just remove a host in a 2 node cluster.

**Result:**
VM is cloned and configured but will not start up due to "Insufficient resources to satisfy vSphere HA failover level on cluster" which was expected. The issue is Rancher doesn't delete the VM, it will now just wait then try to re-provision the node again which results in a "the name already exists" loop. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): N/A

**Comment by MattF-NSIDC** [comment]
I am experiencing this issue with 2.3.5 as well, but downgrading to 2.3.3 resolved it. This release has other issues, for example there's a bug with the "Folder" selection for vsphere node templates (I have to leave it blank to get past an error where an invalid folder path is constructed).

**Comment by Dids** [comment]
I'm also experiencing this, but on a single single vSphere server setup (no HA), so there's no errors, except for the `The name 'X' already exists.".

Using Rancher v2.4.3, and it doesn't even attempt to delete the existing VM, just tries to recreate it with the same name and location, which will obviously fail.

**Comment by dbsanfte** [comment]
Can we get the option to tell Rancher it's okay to delete any existing VMs when there is a name collision? vSphere driver isn't walk-away safe. It does not always clean up after itself. If I try to delete and recreate a cluster I often have to go into vsphere and manually delete VMs because Rancher didn't clean them up. This wouldn't be a problem if we could say 'hey, deleting them if they already exist is ok, just do it'.

**Comment by rex** [comment]
@dbsanfte Your comment was a roller coaster of emotions for me. 

1. 🎊  Wow, this guy is having _exactly_ the same issue I am having, and has the same idea for how to resolve it! Jackpot! 
2. 😭  There aren't any more comments, no solution posted
3. 🤞 Maybe it's because he solved it, which gives me hope!!!
4. _looks at comment timestamp..._ Noooooooooooooo

**Comment by jwestrom** [comment]
We are also experiencing this issue.
