### ISSUE TITLE
kontainer-engine and docker-machine zombie processes

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#25443]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
You need to access UI and activate a cluster or node driver, which should be a non-built-in driver.

**Result:**
You need to exec to the rancher-server container, then, you will see the zombie processes like:
```
# ps aux |grep Z
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        53  0.0  0.0      0     0 ?        Z    08:33   0:00 [kontainer-engin] <defunct>
```

**Other details that may be helpful:**
These "zombie" processes are created when a process has finished, but the parent has not read their exit status via the wait system call.

For the node drivers, when determining whether the driver is executable, `cmd.Wait` is not called after `Start`:
https://github.com/rancher/rancher/blob/7892e90064328cf3128dfcb8da75d389037ec82a/pkg/controllers/management/drivers/dynamic_driver.go#L68-L88

For the cluster drivers, we can look at the [kontainer-engine](https://github.com/rancher/kontainer-engine). We can get the same problem in the `service/service.go` file:
https://github.com/rancher/kontainer-engine/blob/247063a5f1e89bdbd3934075fe9b7b6b846b431e/service/service.go#L444-L475

The simple fix is to use defer:
```
...
err := cmd.Start()
...
defer cmd.Wait()
…
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
 rancher/rancher:v2.3.5
- Installation option (single install/HA):  
 both

I did not submit a PR, as I did not have much time for self-test for the time being, and it may affect communication efficiency due to time zone issues.
It will be very cool if any others can fix it. ping @cjellick ?

**Comment by gasxia** [comment]
Can it be blocked here?

**Comment by thedadams** [comment]
### Root cause
The root cause of this issue is not "waiting" for processes after starting them in Rancher.

### What was fixed, or what changes have occurred
Now, Rancher will wait for the process so that it will not go into zombie status.

### Reproduction steps
Note: It is easiest to do this in Docker, but these steps could also be run in HA on the leader Rancher pod.
1. Deploy Docker install Rancher.
2. Once Rancher starts, activate one of the non-built-in node drivers (like OCI).
3. Exec into the Rancher container and run `ps aux | grep Z`. You will see a `docker-machine` process with `(defunct)` next to it.
4. The same test with the kontainer-engine drivers. Activate one of the non-built-in kontainer-engine drivers (like OCI).
5. Exec into the Rancher container and run `ps aux | grep Z`. You will see a `kontainer-engine` process with `(defunct)` next to it.

With the fix, following the steps above, you should not see and `(defunct)` processes.

### What areas could experience regressions?
It should also be tested that one can deploy clusters with the non-built-in node drivers (just one of them).

### Are the repro steps accurate/minimal?
Yes

**Comment by snasovich** [comment]
@annablender  to handle dev validating this one.

**Comment by annablender** [comment]
Dev-validated on rancher `v2.6-head.`

Steps
- Run Rancher v2.6-head on a standalone DO node
- Access the Rancher UI at https://<DO node IP>
- Activate the OCI node driver
- `docker exec` into the Rancher container and run `ps aux | grep Z` and note that there are no defunct processes

![image](https://user-images.githubusercontent.com/12955547/158618373-a9f7e8d7-0937-4bf6-97eb-466b27a77f9b.png)

![image](https://user-images.githubusercontent.com/12955547/158618419-6ed5bc2a-c96a-43fe-a19c-a3c343873c28.png)

**Comment by annablender** [comment]
Going to repro this issue on 2.6.3 today, to verify that the fix was needed.

**Comment by annablender** [comment]
@sowmyav27 Reproduced issue on 2.6.3.

I did the exact same steps as above, and when I ran `ps aux | grep Z` saw that the container-engine process was <defunct> in the Rancher container.

![image](https://user-images.githubusercontent.com/12955547/159081094-9e33f806-2efb-44d3-b8d7-ac1c907f401e.png)

![image](https://user-images.githubusercontent.com/12955547/159081128-f6fdc88e-6048-4831-9b5e-0c6bb608bcba.png)

![image](https://user-images.githubusercontent.com/12955547/159081139-15fe3139-42c6-44d0-a7ea-51ff5ce959f9.png)
