### ISSUE TITLE
Global + Soft host label acts as a must rule

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2544]
When deploying a service with the following labels:

io.rancher.scheduler.global: true
io.rancher.scheduler.affinity:host_label_soft: ci=worker

Into an environment without the ci=worker label applied to any host, no containers are created. I would expect this to look like a global service in the absence of the host labels.

**Comment by sshipway** [comment]
In my opinion it is working the way I'd expect, if the host affinity were hard.  A *soft* affinity is a bit weird combined with a 'global', and I don't think you can define this via the web interface?

We're using this method (global + hard host affinity rule) on Rancher load balancers so that we can have a wildcarded hardware F5 load balancer rule over the top without having to worry about updating the backing pool or having an excessive number of LB containers.

**Comment by cloudnautique** [comment]
closing #1053 already exists
