### ISSUE TITLE
Listing many large resources can be slow on the ember UI

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#25487]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/ possibly enhancement 

**Steps to reproduce (least amount of steps as possible):**
Deploy 30-50 helm releases to one project. 
And a few revisions for each. With every release or iteration , rancher becomes slower and slower and at some point I am no longer able to access cluster via web UI at all, it just shows loading icon and kicks you back out to cluster list page 

**Result:**

**Other details that may be helpful:**
Helm 3 stores state in kubernetes secret. Looks like very large secrets, looks like rancher is trying to pull on all kubernetes secrets when I try to access UI. 

It should be better to exclude helm release secret types, or at least not to include soft of secret and type of helm3 secrets in cluster pollings. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): HA
Rancher is deployed on bare metal k8s cluster and another deployment is ingke

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#11894

gz#11629

**Comment by cruikshj** [comment]
We are experiencing the same issue...  we have mitigated it somewhat by setting the `--history-max` parameter on our `helm upgrade` command to 1 (default is 10).

This is not a fix... just delays the inevitable.

**Comment by Isakgicu** [comment]
For me this happen only when adding public repositories to catalogs with support of helm 3(helm 2 works fine). If add a private repository with helm 3, everything is just fine. Hope this info will help you fix this issue ASAP.

**Comment by yshch** [comment]
This issue makes UI almost unusable in any cluster with large amount of secrets. It doesn't have to be helm releases, any significant amount of large secrets makes the UI unresponsive, because Rancher tries to get **all** secrets every time you select a Project. Worse, if there are enough pending requests(just 3-4 people clicking is enough in my case), the pod starts to fail the probes, dies and starts a long re-election during which the Rancher is basically completely unavailable.


![secrets](https://user-images.githubusercontent.com/8925723/109018352-db0d6100-76d9-11eb-87f5-4090fac9edf0.png)

**Comment by Ji993** [comment]
Rancher 2.5.5. We are experiencing the same issue on our production cluster. The "secrets?limit=-1&sort=name" call takes >25s to finish.
Our cluster is not large - just several projects with low amount of kubernetes objects inside.
Our users are forced to use the Cluster Explorer instead of the Rancher UI, since it is very slow.
Any ideas ?

**Comment by mkindalov** [comment]
We had the same issue. This is what happened:
- Installed Rancher 2.5.5  which tried to install rancher-operator and fleet
- rancher-operator and fleet were not starting because of issues described in https://github.com/rancher/rancher/issues/23077
- Rancher was constantly trying to redeploy them and was creating secrets with names like sh.helm.release.v1.fleet.vXYZ in the rancher cluster.
- Rancher /secrets request is probably connected with the secrets in the local cluster even if the request is for downstream cluster
- We deleted all the sh.helm.release.v1.fleet.* and  sh.helm.release.v1.rancher-operator.* secrets 

-> calls to /secrets went from ~20sec to <1sec

- don't forget to either uninstall rancher-operator and fleet or fix them :)

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 - Can you have this tested on v2.5.8 and see if it's still an issue? The LOE from the red team indicates that this is something that shouldn't be a problem in later versions but we are seeing reports that it's still an issue as recently as 2.5.5, so we want to confirm.

**Comment by aiyengar2** [comment]
`RANCHER_VERSION=v2.6.0`

### Steps to Reproduce
- Provision a single node and install Docker on it: `curl https://releases.rancher.com/install-docker/20.10.sh | sh`
- Install Rancher on the node: `docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   --privileged -e CATTLE_BOOTSTRAP_PASSWORD=test  --name rancher rancher/rancher:${RANCHER_VERSION}`
- Exec into the container: `docker exec -it rancher /bin/bash`
- Run the following script to generate 50 Secrets using a 1MB dummy file
```
for i in {0..50..0}; do
    < /dev/urandom tr -dc "[:alnum:]" | head -c1048576 > dummy.txt
    kubectl create secret generic "dummy${i}" --from-file=dummy.txt
    sleep 0.5
done
rm dummy.txt
```

#### Results

In both the Dashboard UI and the Manager UI, this same issue is observed where on visiting `VISIT_LINK`, a call is made to `GET_ALL_SECRETS_LINK` which loads every single secret and the value contained within it in one shot:
- Dashboard
  - `VISIT_LINK`:  `RANCHER_URL/dashboard/c/local/explorer/secret`
  - `GET_ALL_SECRETS_LINK`: `RANCHER_URL/v1/secrets`
- Manager
  - `VISIT_LINK`: any link that matches `RANCHER_URL/p/local:PROJECT/*`
  - `GET_ALL_SECRETS_LINK`: `RANCHER_URL/v3/project/local:PROJECT/secrets?limit=-1&sort=name`

For the Dashboard UI, this is terrible since it loads all secrets across all namespaces, regardless of project assignment, on trying to list secrets.

For the Manager UI, although it only loads secrets from your given project, it does so the moment you hit the Project page, which means it loads secrets even if you are just trying to configure Istio, Monitoring, Ingresses, Workloads, etc.

#### Proposed Solution

The Rancher UI should lazily load secrets when the value of the secret is requested rather than requesting for all secrets and their values in one shot.

**Comment by bashofmann** [comment]
The proposed solution would be also useful for ConfigMaps.

**Comment by snasovich** [comment]
Related to: https://github.com/rancher/rancher/issues/30718, a possible solution is being researched as part of it.

**Comment by aiyengar2** [comment]
> The proposed solution would be also useful for ConfigMaps.

Good call out. My current PR also adds this feature into ConfigMaps. See https://github.com/rancher/rancher/pull/34708

**Comment by paynejacob** [comment]
Testing this will require ensuring any page in the ember UI that requires listing resources is functioning properly.  Additionally we should generate ~200 secrets and  200 configmaps with ~125KB of data each to reproduce the excessive response times.  Before these fixes are applied listing these resources should respond in ~30 - 40s.  After these fixes are applied I would expect to see response times closes to 8 - 10 seconds.  

cc: @sgapanovich

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-b6d9284175fc2e8e6682e90beb7ac78130ef26cd-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: ec2 8 nodes (3 etcd, 2 cp, 3 worker)
Downstream K8s version: v1.21.6

----------

### Test Steps: ###

t3.medium and t3.xlarge setups were used for testing. 
Ember does work faster when 250(t3.medium) or 500(t3.xlarge) configmaps and secrets deployed
- To see difference 2.6.1 was used vs 2.6-head
  - after random refreshes (including hard refreshes) + navigating to the cluster I could see the following improvements:
      - Config maps: on average ~2x faster response time
      - Secrets: on average ~25% faster response time

![diff ember.jpg](https://zube.io/files/rancher/6549fe85eb74abb41ea49afe2023633e-diff-ember.jpg)

- deployed 1500 pods, 500 services, 500 ingresses, 200 users, 200 namespaces 
  - api response times are reasonable (no noticeable difference between 2.6.1 vs 2.6-head)
  - all pages load as expected

Verified that all other pages where any resources listed are loading as expected

**Comment by pulberg** [comment]
"api response times are reasonable" - i'm not sure that's a true statement from a customer/user point of view.  I see the improvement that has been made, but I don't understand how anything taking 7 seconds is considered "reasonable".  It seems like there needs to be a fundamental logic change in how those resources are delivered.

**Comment by sgapanovich** [comment]
@paulofrazao I understand what you mean but I used the word "reasonable" for "deployed 1500 pods, 500 services, 500 ingresses, 200 users, 200 namespaces" and those times are less than a 500ms (except the pods -> those were somewhere between 500ms - 1 sec)
the screenshot above is for secrets and configmaps improvements
