### ISSUE TITLE
Unable to add Hosts to the same machine as Rancher Server

### ISSUE THREAD

**Issue by mfilotto** [rancher/rancher#2553]
Hi,
I try to add as rancher host the VM hosting rancher.
I followed this doc : http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#adding-hosts-to-the-same-machine-as-rancher-server
But can't have it work, still stuck on message ERROR: http://192.168.90.111:8080/v1 is not accessible.
Here is my command line : 
````
sudo docker run -d  -e CATTLE_AGENT_IP=192.168.90.111 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 http://192.168.90.111:8080/v1/scripts/ACEEE1A6FBF4BCEA3ECA:1446685200000:QFeZOL88T9Lo9XFIffsijiZI
````
Thanks for your help

**Comment by deniseschannon** [comment]
This is strange because typically that error would be if you couldn't reach your rancher/server, but if you're on the same VM I would assume it wouldn't be an issue. 

Is there any issues reporting on rancher/server.

Have you looked at the troubleshooting docs?  http://docs.rancher.com/rancher/faqs/troubleshooting/

**Comment by deniseschannon** [comment]
@mfilotto If you are still having issues, please re-open and provide more information on the full rancher/agent logs.

http://docs.rancher.com/rancher/faqs/troubleshooting/#where-can-i-find-detailed-logs-of-the-rancher-agent-container
