### ISSUE TITLE
Monitoring: Pod Usage (CPU/Memory) is doubled

### ISSUE THREAD

**Issue by stremlau** [rancher/rancher#25539]
In the Metrics in Rancher and Grafana, the "CPU Usage/Utilization" is doubled.

**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster using hetzner driver
- Enable monitoring on cluster level
- Create a deployment with the use of the image `progrium/stress`, set Command to `--cpu 1` and set the CPU limit to 150

**Result:**
`htop` on the node:
![Bildschirmfoto von 2020-02-24 17-12-49](https://user-images.githubusercontent.com/1077867/75170152-f857ca00-5729-11ea-9146-3251e1356d1e.png)

The view in Rancher (CPU usage is not correct):
![Bildschirmfoto von 2020-02-24 17-12-37](https://user-images.githubusercontent.com/1077867/75170124-eb3adb00-5729-11ea-85aa-66c076df1fe5.png)

The pod dashboard / CPU Usage panel in Grafana (Current is not correct):
![Bildschirmfoto von 2020-02-24 17-13-27](https://user-images.githubusercontent.com/1077867/75170158-fbeb5100-5729-11ea-8169-02628b6737b5.png)

**Other details that may be helpful:**
- The pod was running on a node with 8 vCPUs
- The behavior is the same on a node with 2 vCPUs
- It does not make a difference to set the `--cpu X` to 2 or 8

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hetzer using hetzner driver
- Machine type (cloud/VM/metal) and specifications (CPU/memory): hetzner cloud cx51, 8 vCPU, 32GB RAM
- Monitoring version: 0.0.7
- Kubernetes version
```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by stremlau** [comment]
On an Amazon EKS Cluster connected to Rancher it works correctly. Does anyone have an idea?

**Comment by jiaqiluo** [comment]
the bug is reproduced in Rancher v2.3.5 with monitoring version 0.0.7

Steps:
- run Rancher v2.3.5 single install
- add an ec2 cluster
- enable the cluster monitoring
- deploy a workload with the image `progrium/stress`, set Command to `--cpu 1` and set the CPU limit to 150
- check the pod metrics in Grafana (from the pod page)

Results:
- the value of the current is twice the limit 
![image](https://user-images.githubusercontent.com/6218999/75379243-4e478180-5892-11ea-8813-09093b9d9cb2.png)


The bug fix is validated in Rancher master-head with monitoring version 0.0.8

Te steps are the same. 

Results:
- the values in the metrics are correct, and the current does not exceed the limit. 
<img width="998" alt="Screen Shot 2020-02-26 at 12 22 30 PM" src="https://user-images.githubusercontent.com/6218999/75379479-b1391880-5892-11ea-8942-9af7489f896c.png">

**Comment by rkapoz-tech** [comment]
Hi,
I'm running RANCHER 2.8.1 and I have the same issue; the memory usage for PODS seem dubled.

Can anyone found a solution?
Roberto
