### ISSUE TITLE
Network graph incorrect Y-axis label 

### ISSUE THREAD

**Issue by lkm** [rancher/rancher#2555]
The axis on the network graph in rancher UI is said to report traffic rate in bits per second (K/M/G**b**ps) whereas it's actually reporting bytes (K/M/G**B**ps). Would be great with correct label or even better that it actually reporting bits more commonly used to measure data transfer rates. Either way it should be a small change.

**Comment by vincent99** [comment]
I'm willing to be convinced otherwise, but would argue disk and network interfaces commonly are measured in bits.  Gigabit & 10-gig ethernet, SATA is 3 or 6gbps, etc.

Anyway you are correct that the graphed value was in bytes, and was additionally wrong/doubled on some OSes because cAdvisor reports both a total and a per-interface number.  So it should be correct (in bits) next release.

**Comment by tfiduccia** [comment]
Version - Master with latest reskin UI
Verified fixed
