### ISSUE TITLE
High browser memory usage on apps page during service changes

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2559]
When viewing an application stack with a larger number of services (~90) and applying changes to those services using rancher-compose from the command-line, the memory usage in the browser increases quite rapidly. It's currently at arond 850MB and ... it's just crashed. This happens quite reliably.

I'm going to try record a timeline dump in Chrome in case that's helpful.

**Comment by gordontyler** [comment]
Sorry, I can't collect a heap timeline without the browser tab crashing.

**Comment by vincent99** [comment]
rancher-compose is quite good at creating a torrent of calls which can easily result in the UI receiving dozens+ of `resource.change` events a second.  We will be working on bucketing them so that the same object doesn't get too many changes nearly simultaneously and adding whitelist/blacklisting so the UI can not receive events it doesn't care about soon.
