### ISSUE TITLE
delay happens after auto refreshing kontainer-driver-metadata 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25632]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
- run master-head 7640e89b0 or v2.4.0-rc1
- Copy the builtin data.json file and host it at a server so Rancher can download from an URL
- go to Settings -> rke-metadata-config to change the URL to point to the copy and the refreshing interval to 1
- edit the data.json file to add a new k8s version `v1.18.1-rancher1-1`, and change the default to v1.18.x
- track both Rancher logs and Rancher UI

**Result:**
There is a 3-5 minutes delay between the first auto-refreshing after changing the data.json file and the new values show up in Rancher UI and API

**Comment by StrongMonkey** [comment]
The data may require 3-5 minutes to read and save into etcd database. Let me if that is the case.

**Comment by StrongMonkey** [comment]
Actually I didn't reproduce this issue. I think this is due to the cache issue in github raw content API.
@jiaqiluo  You can try something like this:
1. Deploy rancher master head.
2. Change data.json to point to https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/bae03d4c8c2563471c7aea040cec624986a88a7b/data/data.json. This only has kubernetes 1.17.2-rancher1 as default version. 
3. Check cluster page to see if default k8s version is changed to 1.17.2-rancher1.
4. Revert it back to default setting for kdm. 
5. Check if cluster page to see if default k8s version is changed to 1.17.3-rancher1.

I tested with steps above and it took effect immediately.

**Comment by jiaqiluo** [comment]
Thanks for the feedback @StrongMonkey. 
In rancher:master-head 2e6041d75, I did not see the delay happening anymore following the steps in your comment. 

However, there is another issue happening occasionally:

after changing the URL from url-1 to url-2, there is a refreshing trigged as expected, but Rancher log shows it still uses the url-1, and this can also be confirmed from the UI/API that new values are not applied.

**Comment by jiaqiluo** [comment]
A new issue is made to track the auto-refreshing issue https://github.com/rancher/rancher/issues/25735

this one is closed.
