### ISSUE TITLE
Build-in helm says "function "concat" not defined"

### ISSUE THREAD

**Issue by lonelyleaf** [rancher/rancher#25659]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
I'm adding and testing this helm  chart in https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single but get these message:

```
Wait helm template failed. Error: parse error in "timescaledb-single/templates/statefulset-timescaledb.yaml": template: timescaledb-single/templates/statefulset-timescaledb.yaml:225: function "concat" not defined : exit status 1
```

I can depoly it in helm3,so maybe your helm version is too low.

**Environment information**
- rancher2.3.5
- Installation option (HA):

**Comment by deniseschannon** [comment]
@lonelyleaf We are adding in support for deplying apps using helm3 in 2.4 GA.

**Comment by jiaqiluo** [comment]
This is tested in rancher:master-head 63306835a 

Steps:
- add the catalog https://github.com/timescale/timescaledb-kubernetes.git as a helm 3 catalog

![image](https://user-images.githubusercontent.com/6218999/76131494-e8fb3b00-5fcb-11ea-9160-9140a139ee3b.png)

![image](https://user-images.githubusercontent.com/6218999/76131250-f4019b80-5fca-11ea-928a-e1c0bf146b84.png)


- deploy the app `Timescaledb-Single` from the catalog

Results:
- the error mentioned in the issue is not showing anymore, the chart is parsed and deployed successfully

- the app is not active because there is no storage class configured in my cluster, which is not part of the issue. 

<img width="1319" alt="Screen Shot 2020-03-06 at 4 56 15 PM" src="https://user-images.githubusercontent.com/6218999/76131440-b3565200-5fcb-11ea-9fc7-30bf5c39bbf4.png">
<img width="694" alt="Screen Shot 2020-03-06 at 4 56 07 PM" src="https://user-images.githubusercontent.com/6218999/76131444-b5b8ac00-5fcb-11ea-8212-4b163b1e8fa3.png">

**Comment by schahal** [comment]
As an aside/FYI: my management cluster uses helm2 for its deployments (and can't upgrade seamlessly due to state reasons), so we actually ended up using helm chart v0.5.3 for timescaledb (as v0.5.4 seemed not to support it)

**Comment by feikesteenbergen** [comment]
This was added here:

https://github.com/Masterminds/sprig/pull/169

Which was part of the v2.21.0 sprig release,
Since Helm 2.16.0, this is included in Helm.
