### ISSUE TITLE
When upgrading k8s in mixed clusters, windows nodes are left unavailable after upgrade finishes due to kubelet issues

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#25671]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Upgrade K8s version via Rancher UI on a GCP mixed cluster:
v1.15.9-rancher1-1 upgrade to  v1.16.6-rancher1-2 (not specific to any starting k8s version)

linux cp/etcd master 1m25s
linux worker 4m15s
windows worker kubelet error ~6m 
`error: Kubelet stopped posting node status.` 

except the node reports a successful upgrade at the same time it shows an error in the UI:
```
time="2020-02-01T05:46:19Z" level=info msg="{\"status\":\"Status: Downloaded newer image for rancher/hyperkube:v1.16.6-rancher1\"}"
time="2020-02-01T05:46:24Z" level=info msg="For process kubelet, Image has changed from rancher/hyperkube:v1.15.9-rancher1 to rancher/hyperkube:v1.16.6-rancher1"
```

**Result:**
specific to GCP and mixed clusters, kubelet on windows nodes fail after a k8s upgrade and the nodes become unreachable / unscheduable 
 
kube-proxy error
```
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
Cannot index into a null array.
At C:\opt\rke-tools\entrypoint.ps1:202 char:13
+             $subnet = $hnsNetworkObj.Subnets[0].AddressCIDR
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : NullArray
```

kubelet errors
`I0201 05:53:59.782009 6624 metadata.go:219] Failed to Get service accounts from gce metadata server: Get http://metadata.google.internal./computeMetadata/v1/instance/service-accounts/: dial tcp: lookup metadata.google.internal.: getaddrinfow: The requested name is valid, but no data of the requested type was found.`
and
```
E0205 19:17:24.653032    6512 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Other details that may be helpful:**

this is not specific to any k8s version. 
windows versions used on GCP: 

windows-server-1909-dc-core-for-containers-v20200114
windows-server-1909-dc-core-v20200114 (installed Docker myself, same result)

same upgrade process in AWS succeeds with no kubelet errors:

AWS mixed cluster:
v1.15.9-rancher1-1 upgrade to v1.16.6-rancher1-2

cp/etcd master node  ~1minute
linux worker rancherOS  ~3 minutes
linux worker ubuntu ~4 minutes
windows worker node ~5 minutes

# same windows node upgrade message
`time="2020-02-01T04:57:52Z" level=info msg="For process kubelet, Image has changed from rancher/hyperkube:v1.15.9-rancher1 to rancher/hyperkube:v1.16.6-rancher1"`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud - gce large and xlarge
- Kubernetes version (use `kubectl version`):v1.15.9
- Docker version (use `docker version`): 19.03.5

**Comment by thxCode** [comment]
@rosskirkpat , the cause is that the querying metadata route might be dropped after flannel started. We can divide into two scenarios to discuss:
1. Without GCE cloud provider:
  After starting, we can repair the losing metadata manually in the following ways:
    - login into Windows nodes
    - open `powershell`
    - cd `c:\etc\rancher\wins`
    - exec `.\wins.exe cli route add --addresses "169.254.169.254"`
2. With GCE cloud provider:
  Rke-tool will repair the losing route before starting kubelet/kube-proxy with https://github.com/rancher/rke-tools/blob/64c1facb4b6e5685f9ec70d0bf8074035d8acc3e/windows/sidecar.ps1#L77-L78

I personally think there are two problems here:
1. Without the cloud provider setting, kubelet should treat all running hosts equally, but how could it know the platform is GCE and why it needs to query metadata server? 
2. The Windows host on GCE is very strange, it will not rebuild the querying metadata route after the network interface is refreshed, but `AWS` and `Azure` will do that.

FYI:
- Flannel only builds the HNSNetwork and manages those HNSEndpoints/HNSPolicies below the built HNSNetwork.
- GCE cloud provider setting could follow https://gist.github.com/thxCode/3d6805a904fdb34a03010c0908e25bed

**Comment by maggieliu** [comment]
Confirmed with Support no further action is required from engineering side.
