### ISSUE TITLE
When creating AmazonEC2 host, get error saying security group and subnet "belong to different networks".

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2570]
Version - Master with reskin UI

Steps:
1.  Create Amazon EC2 host/machine with:
      Zone - us-west-2a
      VPC/Subnet - vpc-16885b73
      Security Group - Standard
2.   Fill out rest of setup and click create

Results:  Host/Machine doesn't setup and I get an error:
![image](https://cloud.githubusercontent.com/assets/11514927/10981688/7298c8f0-83c6-11e5-906d-fc459d730791.png)

Expected:  Host to setup

**Comment by tfiduccia** [comment]
Looks like this is because of the Security Group.  If I change zones and VPC/subnets, it is still broken.  But if I switch to something other then the "Standard: Use the existing rancher-machine group", the host/machine creates fine.

**Comment by deniseschannon** [comment]
This is a docker-machine issue. I haven't figured out a way to specify exactly which security group to go with a VPC/Subnet. It's not only an issue with rancher-machine, but if you have multiple Defaults. 

https://github.com/rancher/rancher/issues/2084 kind of tracks potential UI enhancement, but the real issue is that docker-machine only takes `security-group` name so I don't know how it decides which security group to pick.

**Comment by hibooboo2** [comment]
@deniseschannon Since this is a docker machine issue and not ours can we close this?

**Comment by deniseschannon** [comment]
@vincent99 Is there a way for us to return only security groups that belong to a specific subnet?  This would mean closing this in favor of #2084.

**Comment by vincent99** [comment]
I'm sure we can filter for the vpc/ subnet; the bigger problem was there was no option to choose a group by id, but that is in docker-machine now.
