### ISSUE TITLE
Show CIS scan error message in UI

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#25792]
https://github.com/rancher/rancher/issues/24626#issuecomment-583784157

Now that the error message is returned from backend, we need to show this in UI when a cluster scan has errored out.

**Comment by maggieliu** [comment]
@codyrancher backend is ready per https://github.com/rancher/rancher/issues/24626#issuecomment-583784157

**Comment by codyrancher** [comment]
Here's a screenshot of what it will look like 
![Screen Shot 2020-03-16 at 1.43.49 PM.png](https://zube.io/files/rancher/8447e8b8182fb74594bc7d7175871372-screen-shot-2020-03-16-at-1-43-49-pm.png)

**Comment by sowmyav27** [comment]
verified on latest master-commid id:`e651c7a81` ui tag: `latest2`

config.json value is `@`
Run scan.
Error seen on UI:
<img width="1332" alt="Screen Shot 2020-03-16 at 4 10 50 PM" src="https://user-images.githubusercontent.com/26032343/76808324-99bfc200-67a4-11ea-9a88-2e3730be3fe1.png">

From the error message, user does not know the issue is with the config map 
Logging issue to track this -- https://github.com/rancher/rancher/issues/26072
