### ISSUE TITLE
Istio 1.4.6 airgap testing

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#25801]
Airgap testing for: https://github.com/rancher/rancher/issues/25695
On 2.4 and 2.3.6

**Comment by deniseschannon** [comment]
@rancher-max This could be tested with v2.3.6-rc5.

**Comment by rancher-max** [comment]
#### Validated on Rancher v2.3.6-rc5 in both fresh install and upgrade from v2.3.5

All below bullets were done for both fresh install and upgrade scenarios. Only showing one screenshot in most cases as the data is the same on both.
- 1.4.600 is the only available version (in upgrade scenario it is the only available version to upgrade to)
![image](https://user-images.githubusercontent.com/55997940/76356463-3aa90b80-62d3-11ea-843f-46aa3bbaa79f.png)

![image](https://user-images.githubusercontent.com/55997940/76363409-30413e80-62e0-11ea-9f87-47bb890e619f.png)

- All images are correct and deployed successfully when all relevant options are enabled
![image](https://user-images.githubusercontent.com/55997940/76357510-13ebd480-62d5-11ea-94fb-ce75ca53c490.png)
- sidecars deploy properly when auto-injection is enabled in namespace
- Traffic Metrics and Traffic Graph pages show correct data
![image](https://user-images.githubusercontent.com/55997940/76357774-88267800-62d5-11ea-922f-1bba956025ba.png)
- Links all work and display correct data
- Saving changes via tools page and apps page are both successful and changes are deployed successfully
- Previous bug regarding unable to add custom sidecar image is fixed here (note the ImagePullBackOff error is because I did not actually have the image available in my Airgap setup, but this scenario passes if the image is being used as specified, which it is):
![image](https://user-images.githubusercontent.com/55997940/76358978-9ffefb80-62d7-11ea-87c1-3990e92f4cad.png)
