### ISSUE TITLE
Change the feature flag name for Steve and add descriptions

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25817]
Need to change the feature flag name to "Dashboard" for Steve and update the description.

**Comment by deniseschannon** [comment]
@rmweir We also need to change it so that the description of feature flags come from the API instead of the UI.

**Comment by rancher-max** [comment]
#### Validated in master-2408-head `Rancher version e78e43fea`
![image](https://user-images.githubusercontent.com/55997940/76337759-0f172880-62b5-11ea-9331-eab6f7894c5f.png)
- `dashboard` is now shown instead of `steve`
- Related to #25909 where more detail was added to validations for descriptions.
