### ISSUE TITLE
Cannot upgrade or rollback apps using --force option with helm v3

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25847]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a catalog using helm v3. I used https://argoproj.github.io/argo-helm
2. Deploy an app using that catalog. I chose argo-cd, version 1.8.5
3. Upgrade that app and choose the `force` option. I upgraded version to 1.8.6

**Result:**
Fails with:
```
Failed to install app argo-cd. manifest_sorter.go:192: info: skipping unknown hook: "crd-install" manifest_sorter.go:192: info: skipping unknown hook: "crd-install" Error: UPGRADE FAILED: failed to replace object: Service "argo-cd-argocd-application-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "argo-cd-argocd-dex-server" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "argo-cd-argocd-redis" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "argo-cd-argocd-repo-server" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "argo-cd-argocd-server" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**Other details that may be helpful:**
This workflow works if NOT selecting the `force` option.
This workflow also works using the same helm repo but choosing helm v2 instead.

**Environment information**
single node install `master-2377-head` `Rancher version 75d3dc825`

**Comment by rancher-max** [comment]
Note this also applies for rollback as well

**Comment by brendarearden** [comment]
I am able to use the --force option with helm 3 with different helm charts (I used just argo from that same catalog, instead of the argo-cd one), so it seems the failure is chart specific. 

This failure is due to how Helm 3 handles merge patches now, it sees `spec.clusterIP` empty from the initial deploy and tries to set it that way for the next deploy which fails. Since this is the expected helm 3 behavior, it would need to be a change the chart as explained in the helm issue linked below. 

https://github.com/helm/helm/issues/6378#issuecomment-557746499

**Comment by maggieliu** [comment]
Confirmed with @rancher-max it's no longer an issue.
