### ISSUE TITLE
UI - CIS Scan Alerts issues

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25852]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**

Currently on master-head - ui tag: `latest2`

**Issue#1**
- Go to Cluster --> Tools --> CISscans --> "Set Alert"
<img width="1312" alt="Screen Shot 2020-03-06 at 3 11 28 PM" src="https://user-images.githubusercontent.com/26032343/76129755-168cb800-5fbd-11ea-9eed-b70bf8d33b31.png">

**Expected:**
"Set Alert" can be renamed to something like "Alert"

**Issue#2**
- When user clicks on "Set Alert", currently user is redirected to "Add Alert Group" page

**Expected:**
When user clicks on "Alert", he could be redirected to the page, where existing alert group is available
<img width="1278" alt="Screen Shot 2020-03-06 at 3 11 41 PM" src="https://user-images.githubusercontent.com/26032343/76129758-1987a880-5fbd-11ea-877b-815393c05835.png">

**Comment by codyrancher** [comment]
@tfiduccia 

For issues #1 I believe you had suggested "Set Alert" would you like to change it to"Alert"? If so, would you also like to change "Set Schedule" to "Schedule"?

For issue #2, the backend now creates a default group for CIS alerts. Prior to the backend creating the default I made it so that the "Set Alert" button would take us to the "Add Alert Group" page with Security Scan already selected. Would you like to change this behavior to taking the user to the Alert page or perhaps to the "Add Alert" page for the CIS alerts default group?

**Comment by tfiduccia** [comment]
@codyrancher 

- [ ]  Can we just change them to say Add Alert & add Schedule?  that would be more consistent with rest of app
- [ ] Can you put a little white space between the two buttons
![image](https://user-images.githubusercontent.com/11514927/76253880-b722e800-6208-11ea-92b9-a687ab2342cb.png)

- [ ] In cluster, instead of recurring can we actually say CIS?  When I went to Set Schedule, I had no idea what I was supposed to set cause it didn’t referent CIS?
![image](https://user-images.githubusercontent.com/11514927/76253922-cc981200-6208-11ea-9547-cdc4147d0ce8.png)

**Comment by codyrancher** [comment]
I went ahead and did Tani's 3 asks. I actually replaced all references of Security Scan with CIS Scan for consistency. 

Tani and I also discussed the action of Add Alert and we are going to keep the current behavior.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/10/2020)` commit id: e78e43fea

Validated the UI improvements mentioned here. Also the `Add Alert` redirects the user to Add a new alert group (and rule) with the CIS condition selected by default. So the behavior was unchanged as mentioned.
