### ISSUE TITLE
Cluster provider is not updated to k3s after successful import

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#25930]
I noticed that on the clusters overview page, we aren't updating the provider to k3s on an imported cluster dynamically. You have to refresh to see the new provider.
I watched the websocket frames and we do send a frame that has cluster.driver set to k3s and the cluster.k3sConfig field set, which you can see below
![Screen Shot 2020-03-10 at 8 34 00 AM](https://user-images.githubusercontent.com/2473240/76329989-7e3b4f80-62aa-11ea-9042-db0a80cc372c.png)

**Comment by westlywright** [comment]
Steps to repro:
1. Create `imported` cluster
2. Copy command to run on imported cluster but do not use command on imported cluster yet
3. Click `Done`
4. Paste the command and start the import process.

Order of operations is the critical part to reproducing this. If you run the command on your cluster before or you never click done and let the UI transition you back to the clusters over page the provider field would update correctly.

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.4.0-rc2`
Steps:
Create `imported` cluster
Copy command to run on imported cluster but do not use command on imported cluster yet
Click `Done`
Paste the command and start the import process.

Result:
![Screen Shot 2020-03-10 at 1 30 40 PM](https://user-images.githubusercontent.com/57409052/76356707-9c697580-62d3-11ea-8a89-931fb7da8cdf.png)


The bug fix is verified with Rancher server `rancher\rancher:master-2409-head` `version 8ede17d10`

Cluster before import command is run:
![image](https://user-images.githubusercontent.com/57409052/76348547-9a001f00-62c5-11ea-8a0a-d02fbbe6f557.png)

After import command is run, cluster updates 
![image](https://user-images.githubusercontent.com/57409052/76348273-24944e80-62c5-11ea-8245-0e58f2fd026f.png)

![image](https://user-images.githubusercontent.com/57409052/76348248-1a725000-62c5-11ea-8953-7b61d6dec183.png)
