### ISSUE TITLE
Can't create resources with . in their names

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#25955]
**What kind of request is this (question/bug/enhancement/feature request):**
bug possibly

**Steps to reproduce (least amount of steps as possible):**
in the 2.2 line users were able to create resources with a `.` in the name. In 2.3 this is no longer the case which throws errors when managing existing resources that have the dot. In 2.3 one cant manage or create resources with a dot in the name. Since `.` is explicitly accepted, along with `-` in the k8s naming convention, I feel this is a regression.

gzrancher/rancher#8937

**Comment by vincent99** [comment]
@aemneina What type of resource are you referring to here?  It's definitely wrong in some places but I don't think there's anything new about this?

There are several different rules for what's allowed as a name depending on the resource.  Most are a DNS hostname (`[a-z.-]`, <= 253 chars) but some are a single DNS label where a dot is correctly not allowed (& <= 63 chars) or have other restrictions.

Those are supposed to be reflected in the Rancher schema, which has types for `dnsLabel`, `hostname`, and `dnsLabelRestricted`, but these are not all applied correctly to each type, or at all (lots are just `string`).

So someone should go through and fix them to match the rule k8s actually has for each type (among the other validation info that's missing and could be getting used).

There's additional complication for some types like Workloads, because we create multiple things from the one name:
  - A deployment (which should be a `hostname`)
  - A service (`dnsLabel`)
  - A container in the deployment (`dnsLabel`)

Current mapping in master (for a project):
```
 "alertmanager": "dnsLabel"
  "alertmanagerEndpoints": "string"
  "app": "dnsLabel"
  "appRevision": "dnsLabel"
  "applyAppConfig": "string"
  "basicAuth": "dnsLabel"
  "bitbucketCloudPipelineConfig": "dnsLabel"
  "bitbucketCloudProvider": "dnsLabel"
  "bitbucketServerPipelineConfig": "dnsLabel"
  "bitbucketServerProvider": "dnsLabel"
  "certificate": "dnsLabel"
  "configMap": "dnsLabel"
  "configMapEnvSource": "string"
  "configMapKeySelector": "string"
  "configMapProjection": "string"
  "configMapVolumeSource": "string"
  "container": "string"
  "containerPort": "string"
  "containerStatus": "string"
  "cronJob": "dnsLabelRestricted"
  "crossVersionObjectReference": "string"
  "daemonSet": "dnsLabelRestricted"
  "deployment": "dnsLabelRestricted"
  "destinationRule": "dnsLabel"
  "dnsRecord": "dnsLabelRestricted"
  "dockerCredential": "dnsLabel"
  "envVar": "string"
  "ephemeralContainer": "string"
  "gateway": "dnsLabel"
  "githubPipelineConfig": "dnsLabel"
  "githubProvider": "dnsLabel"
  "gitlabPipelineConfig": "dnsLabel"
  "gitlabProvider": "dnsLabel"
  "horizontalPodAutoscaler": "string"
  "httpCookie": "string"
  "httpHeader": "string"
  "ingress": "hostname"
  "job": "dnsLabelRestricted"
  "localObjectReference": "string"
  "metric": "string"
  "namespacedBasicAuth": "dnsLabel"
  "namespacedCertificate": "dnsLabel"
  "namespacedDockerCredential": "dnsLabel"
  "namespacedSecret": "dnsLabel"
  "namespacedServiceAccountToken": "dnsLabel"
  "namespacedSshAuth": "dnsLabel"
  "objectMeta": "dnsLabel"
  "objectReference": "string"
  "ownerReference": "string"
  "persistentVolumeClaim": "dnsLabel"
  "pipeline": "string"
  "pipelineExecution": "dnsLabel"
  "pipelineSetting": "dnsLabel"
  "pod": "dnsLabel"
  "podDNSConfigOption": "string"
  "port": "string"
  "portSelector": "string"
  "prometheus": "dnsLabelRestricted"
  "prometheusRule": "dnsLabel"
  "replicaSet": "dnsLabelRestricted"
  "replicationController": "dnsLabelRestricted"
  "ruleGroup": "string"
  "secret": "dnsLabel"
  "secretEnvSource": "string"
  "secretKeySelector": "string"
  "secretProjection": "string"
  "service": "dnsLabel"
  "serviceAccountToken": "dnsLabel"
  "serviceMonitor": "string"
  "servicePort": "string"
  "sourceCodeCredential": "dnsLabel"
  "sourceCodeProvider": "dnsLabel"
  "sourceCodeProviderConfig": "dnsLabel"
  "sourceCodeRepository": "dnsLabel"
  "sshAuth": "dnsLabel"
  "stage": "string"
  "statefulSet": "dnsLabelRestricted"
  "subset": "string"
  "sysctl": "string"
  "typedLocalObjectReference": "string"
  "virtualService": "dnsLabel"
  "volume": "string"
  "volumeDevice": "string"
  "volumeMount": "string"
  "workload": "dnsLabelRestricted"
```

**Comment by ruckuz99** [comment]
3 we have run into so far(although I am sure there are others based on the list you sent):

**configMap**

**Cronjob**

**secrets**

Looks like these are being being restricted by using the **dnsLabel**, which is incorrect.
There should be a restriction called dnsSubdomain, or something similar.

#### From the Kubernetes Docs:

Name of a ConfigMap object must be a valid ***DNS subdomain name***.

The name of a Secret object must be a valid ***DNS subdomain name***.

CronJob resource, make sure the name you provide is a valid ***DNS subdomain name***. 

### Definition:

#### DNS Subdomain Names

Most resource types require a name that can be used as a DNS subdomain name as defined in RFC 1123. This means the name must:

contain no more than 253 characters
contain only lowercase alphanumeric characters, ‘-’ or ‘.’
start with an alphanumeric character
end with an alphanumeric character


#### DNS Label Names
Some resource types require their names to follow the DNS label standard as defined in RFC 1123. This means the name must:

contain at most 63 characters
contain only lowercase alphanumeric characters or ‘-’
start with an alphanumeric character
end with an alphanumeric character

**Comment by ryansann** [comment]
As far as I can tell from my testing in the 2.2 line, this functionality is not a regression. I ran `rancher/rancher:v2.2.4` and was unable to create Secrets, ConfigMaps, and Workloads with a DNS Subdomain `name`. Instead, the `name` for those resources is required to be DNS Label. If there is a specific example / use case where you saw a regression, I'd be happy to take another look.

As was mentioned, our validation criteria is more strict than the native Kubernetes validation for some resources. For the case of ConfigMaps and Secrets, fixing this is fairly straightforward and I have been able to validate some code changes that do fix the `name` for these types, allowing them to be a DNS Subdomain as opposed to a DNS Label. 

For Workloads the fix would be a bit more involved. A Workload can be backed by a Deployment, StatefulSet, ReplicaSet, DaemonSet, CronJob, or a Job. The `name` for each of these backing types is validated as a DNS Subdomain in Kubernetes, but because the name of the Workload is being used for the name of the backing type (and a Workload is validated as a DNS Label), only a DNS Label is permitted by Rancher. Further, if we do relax Workload `name` to a DNS Subdomain, there are issues when creating the corresponding Pod(s). Specifically, the `name` used for the Workload is passed down in the Pod Spec and is used for the name of the Container associated to the Pod. This presents an issue because Container names must a DNS Label, per the Kubernetes validation ([validation logic](https://github.com/kubernetes/kubernetes/blob/v1.18.3/pkg/apis/core/validation/validation.go#L2719)). So, if we want to relax the validation constraints on the Workload, we will need to do something like figure out a DNS Label compliant naming strategy for the corresponding Container name(s). 

Changes to accomplish this would cause Containers to be named differently than the Workload they were created from (assuming the Workload `name` was a valid DNS Subdomain and not a valid DNS Label). I am not positive on the implications of this, but will discuss further with the team.

**Comment by soumyalj** [comment]
This issue was not reproduced in 2.2 line. Tried v2.2.0 and v2.2.13. 
Tested with master-head(865d70cd1) as a standard user.  Verified that Secrets, Configmaps, PVs and PVCs can have "." "-" in the names . 

1. Create a config map with name "c1.name-1" . Configmap name creation was successful
```
{type: "configMap", data: {k1: "v1"}, labels: {}, name: "c1.name-1", namespaceId: "default"}
data: {k1: "v1"}
labels: {}
name: "c1.name-1"
namespaceId: "default"
type: "configMap"

```
2. Create a secret with name "s1.name-1" 
```
{type: "secret", data: {k2: "djE="}, labels: {}, name: "s1.name-1"}
data: {k2: "djE="}
labels: {}
name: "s1.name-1"
type: "secret"

```
Create a PV with name "pv-test.name1" 

```
{type: "persistentVolume", accessModes: ["ReadWriteOnce"], name: "pv-test.name1",…}
accessModes: ["ReadWriteOnce"]
capacity: {storage: "10Gi"}
csi: {readOnly: false, type: "csipersistentvolumesource", driver: "driver.longhorn.io",…}
name: "pv-test.name1"
type: "persistentVolume"



```


Create a pvc with name "pvc.test-name.1". PVC creation is successful
```
{type: "persistentVolumeClaim", accessModes: ["ReadWriteOnce"], name: "pvc.test-name.1",…}
accessModes: ["ReadWriteOnce"]
name: "pvc.test-name.1"
namespaceId: "longhorn-system"
resources: {requests: {storage: "10Gi"}}
type: "persistentVolumeClaim"
volumeId: null

```

**Comment by soumyalj** [comment]
Tested with v2.4.6-rc2/v2.4-head. We cannot create secrets/configmaps/pvs/pvcs with "." and "-" in the names. 

![Screen Shot 2020-07-01 at 12 06 58 PM](https://user-images.githubusercontent.com/18536626/86282078-65291800-bb93-11ea-9eeb-c3a210bacfc8.png)

**Comment by sangeethah** [comment]
Latest `2.4-head` build now has the fix `2d85dd78f`.

**Comment by soumyalj** [comment]
Validated with Rancher v2.4-head(2d85dd78f)

- Verified that Secrets, Configmaps, PVs and PVCs can have "." "-" in the names . 

1. Create a config map with name "new.1-configmap" . Configmap name creation was successful
```
{type: "configMap", data: {k3: "v4"}, labels: {}, name: "new.1-configmap",…}
data: {k3: "v4"}
labels: {}
name: "new.1-configmap"
namespaceId: "longhorn-system"
type: "configMap"
```

2. Create a secret with name "s1.name-1" 
```
{type: "secret", data: {k2: "djE="}, labels: {}, name: "s1.name-1"}
data: {k2: "djE="}
labels: {}
name: "s1.name-1"
type: "secret"

```
3. Create a PV with name "lh.new-h.1" 

```
{type: "persistentVolume", accessModes: ["ReadWriteOnce"], name: "lh.new-h.1",…}
accessModes: ["ReadWriteOnce"]
capacity: {storage: "10Gi"}
csi: {readOnly: false, type: "csipersistentvolumesource", driver: "driver.longhorn.io",…}
name: "lh.new-h.1"
type: "persistentVolume"


```

4. Create a pvc with name "pvc-name.1.5"

```
{type: "persistentVolumeClaim", accessModes: ["ReadWriteOnce"], name: "pvc-name.1.5",…}
accessModes: ["ReadWriteOnce"]
name: "pvc-name.1.5"
namespaceId: "longhorn-system"
resources: {requests: {storage: "10Gi"}}
storageClassId: null
type: "persistentVolumeClaim"
volumeId: "lh-lv.name"

```

- Verified that the schema for the objects secrets, configmaps, persistentvolumes and persistentvolumeclaims is as below:

The updated schema for secret is below:
```
"name": {
"create": true,
"required": true,
"type": "hostname",
"update": false
}

```
- Verified that the max character length is 253 characters.

**Comment by justinyuan** [comment]
after upgrade to 2.4.7 this bug is still there
![image](https://user-images.githubusercontent.com/1291619/91934612-6525cf80-ed1e-11ea-92de-07f5769f917f.png)
