### ISSUE TITLE
Add virtual machine support in Rancher

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#2597]
Enable RancherVM in Rancher.

1. Adapt RancherVM scripts into Rancher. Embed VM root volume in Docker images. Bridge VM's NIC to Rancher network and setup a DHCP server to assign IP.
2. Make VM work with Convoy volumes. Convoy should pass block device directly to the VM if possible. In some cases like Gluster we should utilize native Gluster/QEMU integration.
3. Make sure there's a way to configure the VM using cloud config.
4. Integrate NoVNC into UI so VM console can be visited.

**Comment by lavvy** [comment]
+1. Can't wait for this feature,  please is the release in sight?

**Comment by yasker** [comment]
@lavvy Yes, we're actively working on this currently and should have a release in the near future.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v0.63.0-rc2

Able to start Virtual Machine successfully using convoy-gluster driver for ROOT/DATA disk in a host with  KVM.
Able to pass  cloud config to VM as userdata when deploying VM.
Also able to view VM console using "Open Console" option for the VM from UI.

**Comment by pwFoo** [comment]
Tried to use ranchervm to start vm-rancheros, but 

- ranchervm console doesn't work because of https://github.com/rancher/vm/issues/70
- login to RancherOS needs a pubkey, no ssh password login (started with  -nographic)

Is the integration under development or stalled? Would be nice to run rancheros vm with rancher ;)
