### ISSUE TITLE
K3S - First time save from upgrade, the status blue box should show immediately

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26024]
K3s Backend change:
* First time save from upgrade, the status blue box should show immediately

**Comment by sangeethah** [comment]
Tested with `v2.4.0-rc5`
Import a k3s Cluster.
Upgrade k3 version.
Able to see the upgrade status message immediately which is as expected:

<img width="1263" alt="Screen Shot 2020-03-16 at 6 07 41 PM" src="https://user-images.githubusercontent.com/4266958/76812520-62f0a880-67b2-11ea-9ff8-e001517728d8.png">

But when the node are getting cordoned now we see the message relating to that node show up for a very short time and then it gets back to the standard message of your "cluster is upgrading" instead of sticking to show the node specific upgrade message.

<img width="1237" alt="Screen Shot 2020-03-16 at 6 08 06 PM" src="https://user-images.githubusercontent.com/4266958/76812592-95020a80-67b2-11ea-90dc-fed0078f2ff0.png">

Reopening this issue to fix this.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-2474-head` `version 888029fb0`

Update box shows up immediately upon cluster update. Box message changes with sequential nodes being updated.
