### ISSUE TITLE
Using View Graph icon when no services in stack

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2604]
Version - Master with reskin UI

Steps:
1.  Create a new stack with no services and stay on main stack screen

Results:
Notice the icon next the menu icon is the View Graph icon.
![image](https://cloud.githubusercontent.com/assets/11514927/11021961/f0ac2b48-860e-11e5-81ce-76c20aad1223.png)

Expected:
Since there are no service it seems silly to take us to the Graph view.  Normally if you have a Service it's on Stop or Stop.  Maybe if it's empty it should be the Delete Stack icon and functionality.

**Comment by vincent99** [comment]
The current logic looks at the things in the actions dropdown before the first dividing line and picks the first one that has an icon and is not 'delete'.  So delete is intentionally not allowed, though I could be convinced otherwise.

Rearranged the actions for stacks, this will have the effect that on a stack with no containers there will be no primary action (it will show just the one down arrow button), and also for ones that are in 'upgrade' state that the primary action will be 'Finish upgrade'.

**Comment by tfiduccia** [comment]
Verified fixed - Master with newest reskin
