### ISSUE TITLE
Upgrade ceph-common package in Hyperkube

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#26083]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Latest Hyperkube shows ceph-common 10.2.11-2 amd64 (default with Debian 9) which is incompatible with Luminous Ceph clusters or beyond when provisioning Ceph Storage classes in the kube-controller

For reference Luminous version of Ceph came out in 2017

Upstream image issue seems to have gone stale:

https://github.com/kubernetes/kubernetes/issues/73620

**Result:**
You have difficulties provisioning newer Ceph Storage providers

**Environment information**
- Rancher version: 2.2.8/2.3.5

**Comment by patrickstump** [comment]
Would like to see this happen soon as well. We are using ProxMox with Ceph as our CEPH server and using Rancher to create a Storage Class or PV.  This is currently not working due to version / protocol mismatch.
Using:
- Rancher 2.3.5 using hyperkube v1.17.3-rancher1-1
- Proxmox  Version pve-manager/5.4-13

To recreate:
On the CEPH Proxmox Server:
```
$ceph --version
ceph version 12.2.13 (98af9a6b9a46b2d562a0de4b09263d70aeb1c9dd) luminous (stable)
```
On a kubernetes node :
```
# docker exec -it `docker ps | grep hyper | grep kubelet | awk '{print $1}'` ceph --version
ceph version 10.2.11 (e4b061b47f07f583c92a050d9e84b1813a35671e)
```
The following error occurs when the client tries to access the server.
```
2020-03-22 16:43:37.809862 7f164bd74700  0 -- 172.25.10.160:0/4170956644 >> 172.25.10.133:6789/0 pipe(0x7f1644000be0 sd=3 :47924 s=1 pgs=0 cs=0 l=1 c=0x7f1644001f20).connect protocol feature mismatch, my 27ffffffefdfbfff < peer 27fddff8eeacbffb missing 200000
```

To test the issue on the Kubernetes node under rancher management 
with existing version:
```
docker exec -it `docker ps | grep hyper | grep kubelet | awk '{print $1}'` /bin/sh
 sh-4.4# rbd --version
ceph version 10.2.11 (e4b061b47f07f583c92a050d9e84b1813a35671e)

sh-4.4# rbd ls testpool
```
results in 
```
2020-03-22 16:25:04.993026 7f546c6a7700  0 -- 172.25.10.160:0/222603765 >> 172.25.10.133:6789/0 pipe(0x7f5468000be0 sd=4 :39302 s=1 pgs=0 cs=0 l=1 c=0x7f5468001f20).connect protocol feature mismatch, my 27ffffffefdfbfff < peer 27fddff8eeacbffb missing 200000
```
Then to test the fix:

```
echo "deb https://download.ceph.com/debian-luminous/ stretch main" > /etc/apt/sources.list.d/ceph.list
aptitude update
aptitude upgrade
```
And run the same command again
```
sh-4.4# rbd --version
ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)
sh-4.4# rbd ls testpool
base-129-disk-0
base-131-disk-0
base-132-disk-0
base-138-disk-0
#
```

**Comment by zaventh** [comment]
For reference, the package is referenced in [kubernetes-package](https://github.com/rancher/kubernetes-package/blob/33e6ac75098e5728b3b43fc1fea35c559d085529/package/Dockerfile#L26)
