### ISSUE TITLE
When Rancher GUI session times out, you are prompted for an API key

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2611]
When the GUI session times out,  and no links are clicked, the browser is given a popup HTTP-AUTH prompt to "Enter API access key and password", instead of being redirected to the login page.  It would be preferable if the UI recognised a session timeout, and instead prompted the user to login again.

Cancelling the login popup and then clicking on any link will correctly redirect to the user login form.

**Comment by vincent99** [comment]
There is a header specifically sent to have the API not include the `www-authenticate` header in 401 responses to the UI, so this should never happen..  What screen was it on?  What auth mode?  SSL termination or anything else special involved?

**Comment by sshipway** [comment]
I have rancher-server installed on a separate docker host, behind an nginx proxy that does SSL offloading.  I was connected via https to nginx and then on to rnahcer-server.

I left the desktop logged in overnight viewing the Infrastructure screen (Hosts) and when coming in in the morning saw the http-auth prompt.

The rancher-server is configured with LDAP authentication to AD.  rancher-server v0.43.1

**Comment by sshipway** [comment]
The nginx configuration was pulled from the Rancher website instructions:

    upstream rancher {
      server rancher-server:8080;
    }

    server {
      listen 443 ssl;
      server_name rancher.container.auckland.ac.nz;
      ssl_certificate     certs/rancher.container.auckland.ac.nz.crt;
      ssl_certificate_key certs/rancher.container.auckland.ac.nz.key;

      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
      }
    }

**Comment by vincent99** [comment]
Ok I think this is from the subscribe websocket;  The no-challenge header is missing on that request, because there is no way to set custom headers on websocket requests.  

That normally wouldn't normally matter because it's the last thing opened on the page and something earlier would have gotten unauthorized first.. But the socket reconnects automatically, so if your connection dropped briefly overnight it would reconnect and trigger the prompt.  This will require a change on the API side.

Note to future me / @westlywright: catalog and a couple add-host drivers also have some requests that are doing raw AJAX and should be fixed.  Everything should use `store.{request,rawRequest}`, not `ajaxPromise` or `[Ember.]$.ajax`.

**Comment by vincent99** [comment]
@ibuildthecloud added a fix for the server-side for next release

**Comment by tfiduccia** [comment]
Version - Master
Verified Fixed
