### ISSUE TITLE
Valid charts in a helm catalog are not updated when catalog contains an invalid chart

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#26162]
rancher/rancher:master-head cf6d0c979

* Add a catalog containing both a valid and invalid chart
`github.com/bmdepesa/helm-test-repo:goodbad`
* The catalog shows an error during syncing
* Launch a multicluster app
* The good chart from the catalog is shown, the invalid is not
* Update the good chart with some changes
* Sync the catalog
* No charts are updated, and the changes to the good chart are not reflected in the UI

Initial sync:
```
2020/03/19 23:25:07 [INFO] Catalog sync done. 1 templates created, 0 templates updated, 0 templates deleted, 1 templates failed
```

After refreshing the catalog:
```
2020/03/20 07:11:52 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
```

This is after the fixes for: https://github.com/rancher/rancher/issues/24914

**Comment by brendarearden** [comment]
I was able to recreate this, but this appears to be existing behavior. 
If a change to a chart occurs in a hosted repo that has an index.yaml, the index.yaml is regenerated, which results in a change to the digest for that chart. In this situation, the manual changes are not recreating how the index.yaml gets regenerated so the change isn't being picked up because its not passing this following check because we aren't seeing the digest change: https://github.com/rancher/rancher/blob/371ec137fb7a6d4925603d475d5012f33d97c4f4/pkg/catalog/manager/traverse.go#L71 

I followed these steps:
Add a catalog containing both a valid and invalid versions of the same chart
`https://github.com/brendarearden/integration-test-charts:testing`
The catalog shows an error during syncing
Launch a multicluster app
The good chart versions from the catalog are shown, the invalid version is not
Update the good chart version with some changes
Sync the catalog
1 chart is updated, and the changes are reflected in the ui

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 371ec137f

* Updated the digest when updating the chart, in the catalog also containing an invalid chart, and the changes are reflected in the UI after sync
* Also tested the same scenario with a github repo (no index.yaml) and saw the same funcitonal behavior.
