### ISSUE TITLE
documentation (airgapped) displays wrong rke output file names

### ISSUE THREAD

**Issue by styk-tv** [rancher/rancher#26198]
as per

RKE_VERSION=v1.0.4

output file names for post installation have different names than in the documentation page
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/launch-kubernetes/

<img width="395" alt="Screenshot 2020-03-23 at 15 00 03" src="https://user-images.githubusercontent.com/838921/77330270-0132c000-6d17-11ea-87d8-3ee638d60c49.png">

kube_config_rancher-cluster.yml > shouldbe > **kube_config_clusterfile.rendered**
rancher-cluster.rkestate> shouldbe > **clusterfile.rkestate**

please update abovementioned page, if wrong place to post sorry in advance but at least its documented.

**Comment by deniseschannon** [comment]
@styk-tv  It seems that you have named your `rancher-cluster.yml` as `clusterfile.yml` which is why your file names are different so you hadn't followed the directions as stated. 

In general docs issues should be made in our docs repo. https://github.com/rancher/docs

@catherineluse we should make a note that the `rancher-cluster` parts of the 2 latter files are dependent on how you name the RKE cluster configuration file.

**Comment by catherineluse** [comment]
I have fixed it in this commit https://github.com/rancher/docs/commit/055bd2da562185381659696101346109d7f59902
