### ISSUE TITLE
Service type makes impossible to deploy with Helm on GKE

### ISSUE THREAD

**Issue by vitorfhc** [rancher/rancher#26295]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Follow all steps presented in the [Install Rancher on the Kubernetes Cluster](https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/helm-rancher/) using LetsEncrypt
2. Rancher will be deployed but the Ingress resource will show an error on GKE UI
> error while evaluating the ingress spec: service "cattle-system/rancher" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

**Result:**
Rancher will not be deployed properly because Ingress is never created

**Other details that may be helpful:**
As far as I know, GKE sets ClusterIP as the default type for a service
#13035 shows the same problem and the solution presented doesn't make sense when you want to create a LetsEncrypt certificate using the cert-manager.

**Screenshot:**
![image](https://user-images.githubusercontent.com/19597793/77697559-7277aa80-6f85-11ea-8796-4ff0db304571.png)

**Possible solution:**
Setting a variable in values.yml which is reflected as the chosen type to the service.

**Comment by mrickert-bouncex** [comment]
Just ran into this issue as well, same error. An ugly workaround is to edit the service in gke services and change it from clusterip to loadbalancer.

**Comment by vincent99** [comment]
We support running the Rancher control plane only on a RKE or K3s cluster, because your ability to backup, restore, scale and configure the underlying etcd is limited or non-existent in hosted providers.

Yes you can make it work in places we don't support, but adding extra options to make an unsupported configuration convenient is not really going to be a priority for us.

**Comment by daavelar** [comment]
Same issue here

**Comment by amoon78** [comment]
Is it fixed on Rancher 2.5 version? Regarding this doc https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/ , it says `As of Rancher v2.5, Rancher can be installed on any Kubernetes cluster`. 
I tired to install rancher 2.5.5 on GKE but, have exactly same issue. 
Is there any available option or variables to have node port or loadbalancer type instead of clusterip?

**Comment by soudaburger** [comment]
Use case: GKE + IAP to protect rancher resources:

Kubernetes cluster is deployed, but service is not configurable to be of type `NodePort` or `LoadBalancer` in order for ingress to be visible as a Google Cloud Global Load Balancer.

This is broken or otherwise poorly documented.

**Comment by guhcampos** [comment]
wow, this issue just made me discard Rancher and find out about kubesphere. Thanks.
