### ISSUE TITLE
How to add and configure user groups with saml?

### ISSUE THREAD

**Issue by nathankodilla** [rancher/rancher#26309]
I have authentication setup via Okta saml and have the groups field being sent. However, attempting both with the local admin and saml user, I see no place in the UI to manage the groups and what permissions they have. Every user that logs in currently, is an admin by default.

On version 2.3.5.

**Comment by vincent99** [comment]
Tying global roles to groups is coming in 2.4.  

You can currently choose the default rules a new user gets, and have apparently added Admin as one of them is every new user is an admin.

**Comment by nathankodilla** [comment]
We have not added admin as a new role by default.
![image](https://user-images.githubusercontent.com/22841858/77810205-b7750d00-7069-11ea-902d-de9d2ada51b6.png)
The user role:
![image](https://user-images.githubusercontent.com/22841858/77810223-d2e01800-7069-11ea-95de-15a38c3e2112.png)

**Comment by UrosSimovic** [comment]
Yup, same here. All users logging in with Okta get not just admin rights but are logged in as admin user. Also assigning roles to Okta gorups doesn't help. 

![2020-04-16_11-02](https://user-images.githubusercontent.com/11682124/79437086-fe538400-7fd1-11ea-860c-79f06decbde4.png)

**Comment by nathan-mellis** [comment]
I'm also seeing this on a fresh install of 2.5.2 connected to Okta.

**Comment by mrajashree** [comment]
@nathankodilla  @UrosSimovic @nathan-mellis Whichever user first sets up authentication gets the admin account. 
Do you see any user accounts created for the other users? Do you only have one user account when you go to the Global level Security -> Users tab?
Also can you please confirm if the fields for login name and Unique ID are set properly when configuring auth, so that the Identity Provider (Okta) sends unique information for these fields per user?

**Comment by nathan-mellis** [comment]
@mrajashree I do see users. See attached screenshot:
<img width="1250" alt="Screen Shot 2021-01-26 at 11 38 18 AM" src="https://user-images.githubusercontent.com/56159457/105895976-14638b80-5fcb-11eb-9396-9f5dbee9d2fb.png">

As far as configuring for login name and unique ID, we're setting display name to the user's full name, username and UID field to their email address, and groups to a list of their (relevant) Okta groups. We followed these instructions: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/okta/.

Even though the screenshot shows "Unable to fetch user info" in that screenshot, if I look at each SSO user's individual details, the display name is being set correctly but the groups never come through in a way that has them show up in the group dropdown box. So we're not able to set any permissions based on group membership since you can _only_ do that via selection via the group dropdown box.

**Comment by ccckblaze** [comment]
any updates?

**Comment by michaelandrepearce** [comment]
Any update
