### ISSUE TITLE
Feature Request: Mixed type clusters

### ISSUE THREAD

**Issue by pbecotte** [rancher/rancher#26330]
Being a man of culture, a couple days ago I managed to delete both the state and the backup of that state from a rancher cluster. This is not a production workload, and the whole reason I run it is to find new and original ways to break things, so not a big deal. I was able to reconnect the new rancher server to the existing k8s cluster by using the "import" functionality. 

This is where I hit what I consider a weird limitation. the node type is tied to the cluster. Since my cluster is "imported" the vast majority of control options no longer apply. For example, terraform was able to recreate the node pools from the old setup- but those nodes, when launched, don't actually join the cluster since they expect that to happen without it. Its interesting that even though the cluster was created using RKE, there is no way to convince RKE to start managing it again.

So, the feature request (and, honestly, the way I had assumed things already worked): tie the node type to the node pools instead of the cluster. Let me explain- I would like to be able to launch nodes for a single cluster using several different methods- having Rancher launch nodes using two separate cloud providers and allowing me to launch/join custom RKE nodes in my data center, for example. A good way of doing that seems like having node pools of different types- a cloud provider pool would work like a current cloud provider cluster (launch nodes, manage them), while I could also have an "unmanaged" pool where Rancher doesn't do anything except report that they exist (like the current behavior on imported clusters).

I do understand the reasons why heterogeneous k8s clusters are a bad idea- and that doing this may make things easier to the point where people who don't realize that do it, and then blame Rancher for their own mistakes- but there are times when it may be useful.

**Comment by jonathon2nd** [comment]
I have run into the same issue.

I was looking forward to a setting up a hybrid cluster with master pool being 'on prem' and my worker pool being in the cloud using Open stack driver. But after making the cluster, you are tied to one type of node driver or the other. I find this frustrating because I am not understanding what the limitation here is. I am assuming there is one, and I just do not know enough yet. 

Is there any possibility of this being a feature later one? This would also tie in nicely with https://github.com/rancher/rancher/issues/15738 which I have a work around working using https://github.com/rancher/rancher/issues/15145#issuecomment-724242780. But it would be nice if this would work natively as well.

**Comment by jonathon2nd** [comment]
I was able to create a hybrid cluster though Rancher API, and [terraform](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_pool). I have had no issues with any testing, and it's been in preprod for over a month now. While I have not had the need to do this yet, I bet you could mix node driver types like this. 
Just an FYI for anyone who comes across this later in their search for hybrid ck8s clusters.

**Comment by vincent99** [comment]
You "can" do whatever you want from the API or with registering "Custom" nodes, but it's not recommended (by us or upstream k8s), supported, or physically allowed through our UI because it's basically a field of landmines.  Here are a few that come immediately to mind:

- Cloud provider integrations: These deal with setting the right addresses for the nodes, noticing when one is deleted by the provider, loadbalancer services, etc.  You can set one configuration for the cluster, so it can't work for multiple providers simultaneously.

- Load balancers: Assuming you get one from the one configured cloud provider, there are nodes in the cluster that the balancer probably can't reach and will have no idea what to do with.  e.g. you can't tell an ELB to send traffic to a random internal IP for a DigitalOcean VM.

- Network boundaries: Depending on the CNI picked, different implementations of networking have different assumptions about addressing and reachability of the nodes.

- Storage providers: Different providers have different storage systems which need different configuration.  You can't specify a pod to use one of N different kinds of volumes depending on where the node it's going to land on is.  Even within one provider volumes can't necessarily be moved between regions, but the scheduler doesn't take this into account when trying to start a pod and attaching an existing volume.

- Latency: Services by default take no consideration to try and reach an endpoint that is "close" to the pod that's trying to reach it.  Unless you go way down the rabbit hole into alpha-only features for service topology and carefully label and select everything, internal communication between pods will hop randomly across provider/network/region boundaries and be much slower.

And there's an extra level of pain with spreading etcd:
- Latency: Performance of the cluster and API is _heavily_ sensitive to, and limited, by the latency between the "farthest" members.
- HA: The cluster needs a strict majority of nodes up.  So splitting into 2 locations/providers does not help (just like how having 2 replicas is bad), now you need at least a 3rd one, which is going to compound the latency problem.

**Comment by jonathon2nd** [comment]
The reason I went forward with this was because we have one workload whose resource usage various thought the day as end-user usage goes up and down. So we have a public worker node pool with a taint where only this workload can run on. We also have some on-prem hosts to cover the baseline. This workload does not have persistent volumes, all networking is done on vrack which is hosted by the same vender. Also we have this system which contains this workload as a separate k8s cluster _just in case_ something does go wrong in the future, with all masters on prem.

So it works out good for our use case. But other admins mileage may very, and should be tested out for a long period of time first. I don't mean to proscribe/sign off on any architecture that others should use, and I am sorry that it came across that way.

**Comment by vincent99** [comment]
Sure it's fine to do whatever works for you; just explaining some of the reasons why we probably wouldn't make this a real feature...
