### ISSUE TITLE
Cluster Private Registry setting not adhered to when pulling rancher-agent image during Node Driver cluster provisioning

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#26366]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

_Edited to clarify reproduction steps, and call-out this appears to be Node Driver provisioning related, not Azure specific._

> The following steps assume you have an internet-accessible private Docker registry populated with the Rancher [v2.4.8 rancher-images.txt](https://github.com/rancher/rancher/releases/v2.4.8) images and a Rancher v2.4.8 instance (I used https://github.com/superseb/tf-do-rancher2/ for the latter). In the tests below I have replaced the actual private registry URL with registry.example.com:

The issue is that the initial rancher-agent container, started by Rancher, on a node during a Node Driver cluster provisioning does not adhere to the Private Registry configured on the cluster. Instead it will attempt to pull the image from Docker Hub (by default) or the `system-default-registry` (if configured). As a result cluster provisioning for Node Driver clusters will fail if Docker Hub, or the `system-default-registry` (if configured), is un-reachable from the node. Below are the three tests I performed for this:

#### Working as expected: Custom cluster with Private Registry configured

1. Create a custom cluster with Kubernetes v1.18.6-rancher1-2, specifying a Private Registry in the cluster configuration with the URL, user and password for your private registry.
2. Observe the agent command, generated by Rancher, for the cluster correctly references the private registry:
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run registry.example.com/rancher/rancher-agent:v2.4.8 --server https://161.35.32.125 --token <token> --ca-checksum 25710285359810f586aefef46cd3673efdb97be0131d4942dc0e94489b933032 --worker --etcd --controlplane
```
3. On a host with Docker installed, login to the private registry `docker login registry.example.com` and execute the agent command. Observe the node is successfully provisioned with all Kubernetes component and System Project workload images pulled from the private registry.

#### Not working as expected: Digital Ocean Node Driver cluster with Private Registry configured

1. Create a single node Digital Ocean Node Driver cluster with Kubernetes v1.18.6-rancher1-2, specifying a Private Registry in the cluster configuration with the URL, user and password for your private registry.
2. Once the VM itself is provisioned SSH to the node, and observe that the initial rancher-agent container is started with the `rancher/rancher-agent` image pulled from Docker Hub, but all Kubernetes component and System Project workload images are pulled from the private registry as expected.

#### Not working as expected: Digital Ocean Node Driver cluster with Private Registry configured, and un-reachable/non-existent system-default-registry configured:

1. Define a non-existent `system-default-registry` in the Rancher settings, e.g. `foo.example.com`.
2. Create a single node Digital Ocean Node Driver cluster with Kubernetes v1.18.6-rancher1-2, specifying a Private Registry in the cluster configuration with the URL, user and password for your private registry.
3. Observe that once the VM has been provisioned and Docker installed, provisioning fails with the following error, indicating the Private Registry is not being observed for the initial rancher-agent pull, but the system-default-registry is being used instead:
```
Unable to find image 'foo.example.com/rancher/rancher-agent:v2.4.8' locally docker: Error response from daemon: Get https://foo.example.com/v2/: dial tcp: lookup foo.example.com: no such host. See 'docker run --help'. Process exited with status 125 : exit status 1
```

**Environment information**
- Rancher v2.4.8

gz#9153

gz#11072

gz#11072

**Comment by izaac** [comment]
Reproduced in Rancher `v2.4.8`

**Comment by ryansann** [comment]
Providing an update on this issue, as I have been working on it for some time.

I've evaluated/implemented 3 different approaches to have the agent image be pulled from a private registry:

#### Approach 1
Add a command in the node provisioning process to authenticate against the registry, i.e.
```
rancher-machine --native-ssh ssh my-machine sudo docker login --username xxx --password xxx registry.example.com
```
This approach works. I tried some stuff with env vars to hide the password, but setting them on the remote would require configuring the ssh agent. and `os/exec.Command` doesn't support inline env var expansion.

#### Approach 2 
Next I tried a different command, that one looked like this:
```
/bin/bash -c docker $(rancher-machine config my-machine) login -u $DOCKER_PASSWORD -p $DOCKER_USER registry.example.com
```
This worked with CATTLE_DEV_MODE=1 and leverages a local docker binary to connect to the remote daemon and run the login command. In reviewing with @luthermonson, we saw that docker is not present in the rancher container and, further, there could be future version mismatches between the docker binaries that could break node provisioning w/ a private registry.

#### Approach 3 
The last approach I tried was adding registry options to `rancher-machine create` in order to pre-authenticate a user to the registry, if the options are provided. Then Rancher sets up the jailed env to have registry credentials if a private registry is defined on the he cluster. This works, but only establishes a docker config for the ssh user, which may not work in some cases.

After some discussion with @Oats87, I've tend to think the login logic makes the most sense if it's kept in rancher and carried out by `rancher-machine`, which means going with approach 1. 

The PR for approach 1 is here:
- https://github.com/rancher/rancher/pull/29769

cc: @superseb @deniseschannon

**Comment by ryansann** [comment]
@superseb and I discussed some possible error scenarios that the user should be able to recover from. I've run through these and validated they are recoverable. 

#### Scenario 1
While creating a node driver cluster, the incorrect username and/or password are specified in the private registry configuration.

Result:
When navigating to Cluster > Nodes, the user will see an authentication error for each node

Solution:
Navigate to Cluster > Nodes, choose Edit Cluster and reenter the private registry credentials correctly and save changes. When the node provisioning is retried with valid credentials, it will succeed.

#### Scenario 2
While creating a node driver cluster, an incorrect registry url is provided

Result:
When navigating to Cluster > Nodes, the user will see an error like `dial tcp: lookup bad.host: no such host`

Solution:
Navigate to Cluster > nodes, choose Edit Cluster and reenter the correct registry url and credentials, then save changes. When the node provisioning is retried with a valid registry url and credentials, it will succeed.

NOTE: In both of these scenarios, the cluster will remain in the Provisioning state. The errors are visible when looking in the Cluster's Nodes view, since these errors are encountered during node provisioning.

**Comment by slickwarren** [comment]
I was able to successfully add a DO cluster through an insecure private registry on v2.4.13-rc1

```
740a6eb38313        insecureprivateregistry/rancher/rancher-agent:v2.4.13-rc1                 "run.sh --server htt…"   29 minutes ago      Up 29 minutes                           wonderful_ardinghelli

```
all images were pulled through the private registry, including `rancher-agent` as pictured above.  
Repro steps: 
* create rancher server on version 2.4.13-rc1
* create private registry
* configure private registry for insecure access, download load/save images for release 2.4.14-rc1
* create DO template in rancher, pointing to your insecure private registry
* add  Digital Ocean Node Driver cluster with Private Registry configured
* wait for new cluster to provision, login to cluster and `docker ps` to verify source of images all match your private registry

(note: insecure private registry not required for repro)
I was able to validate the following on 2.4.13-c1:
```
Scenario 1
While creating a node driver cluster, the incorrect username and/or password are specified in the private registry configuration.

Result:
When navigating to Cluster > Nodes, the user will see an authentication error for each node

Solution:
Navigate to Cluster > Nodes, choose Edit Cluster and reenter the private registry credentials correctly and save changes. When the node provisioning is retried with valid credentials, it will succeed.

Scenario 2
While creating a node driver cluster, an incorrect registry url is provided

Result:
When navigating to Cluster > Nodes, the user will see an error like dial tcp: lookup bad.host: no such host

Solution:
Navigate to Cluster > nodes, choose Edit Cluster and reenter the correct registry url and credentials, then save changes. When the node provisioning is retried with a valid registry url and credentials, it will succeed.
```
