### ISSUE TITLE
Healthy instances get marked as "unhealthy" and recreated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2637]
Server version - Build from master

Steps to reproduce the problem:

Set up has 2 hosts.
Had a service with scale 15.
There were few instances in host1 and few in host2.

Stopped host1.

This resulted in existing instances in host1 being marked for "deletion" and new instances being created in host2 , so that all instances of the service are in host2.

Started host1.

When host1 got to "Active" state , I see the instances that are stuck in "removing" state getting removed. 
But this also triggered few existing instances in host2 to be marked "unhealthy" , which triggered new instances to be created in host2.

```
After host1 went to "reconnecting" state and healthcheck triggered new instances to be created.

mysql> select id,name,state,health_state from instance where name like "%myhealth%";
+-----+------------------------+---------+--------------+
| id  | name                   | state   | health_state |
+-----+------------------------+---------+--------------+
| 224 | test494388_myhealth_1  | purged  | unhealthy    |
| 225 | test494388_myhealth_2  | purged  | unhealthy    |
| 226 | test494388_myhealth_3  | purged  | unhealthy    |
| 227 | test494388_myhealth_4  | purged  | unhealthy    |
| 228 | test494388_myhealth_5  | purging | unhealthy    |
| 229 | test494388_myhealth_6  | purged  | healthy      |
| 230 | test494388_myhealth_7  | purging | unhealthy    |
| 231 | test494388_myhealth_1  | purging | unhealthy    |
| 232 | test494388_myhealth_2  | purging | unhealthy    |
| 237 | test494388_myhealth_3  | running | healthy      |
| 238 | test494388_myhealth_4  | running | healthy      |
| 239 | test494388_myhealth_6  | running | healthy      |
| 240 | test494388_myhealth_8  | running | healthy      |
| 241 | test494388_myhealth_9  | purging | unhealthy    |
| 242 | test494388_myhealth_10 | running | healthy      |
| 243 | test494388_myhealth_11 | running | healthy      |
| 244 | test494388_myhealth_12 | purging | unhealthy    |
| 245 | test494388_myhealth_13 | purging | unhealthy    |
| 246 | test494388_myhealth_14 | running | healthy      |
| 247 | test494388_myhealth_15 | purging | unhealthy    |
| 248 | test494388_myhealth_16 | running | initializing |
| 249 | test494388_myhealth_17 | purging | initializing |
| 250 | test494388_myhealth_17 | running | healthy      |
| 251 | test494388_myhealth_18 | running | healthy      |
| 252 | test494388_myhealth_19 | running | healthy      |
| 253 | test494388_myhealth_20 | running | healthy      |
| 254 | test494388_myhealth_21 | running | healthy      |
| 255 | test494388_myhealth_22 | running | healthy      |
| 256 | test494388_myhealth_23 | running | healthy      |
+-----+------------------------+---------+--------------+
29 rows in set (0.00 sec)

After host1 went to "Active" state. I see 7 instances being recreated in host1.

mysql> select id,name,state,health_state from instance where name like "%myhealth%";

+-----+------------------------+---------+--------------+

| id  | name                   | state   | health_state |

+-----+------------------------+---------+--------------+

| 224 | test494388_myhealth_1  | purged  | unhealthy    |

| 225 | test494388_myhealth_2  | purged  | unhealthy    |

| 226 | test494388_myhealth_3  | purged  | unhealthy    |

| 227 | test494388_myhealth_4  | purged  | unhealthy    |

| 228 | test494388_myhealth_5  | purged  | unhealthy    |

| 229 | test494388_myhealth_6  | purged  | healthy      |

| 230 | test494388_myhealth_7  | purged  | unhealthy    |

| 231 | test494388_myhealth_1  | purged  | unhealthy    |

| 232 | test494388_myhealth_2  | purged  | unhealthy    |

| 237 | test494388_myhealth_3  | removed | unhealthy    |

| 238 | test494388_myhealth_4  | removed | unhealthy    |

| 239 | test494388_myhealth_6  | removed | unhealthy    |

| 240 | test494388_myhealth_8  | removed | unhealthy    |

| 241 | test494388_myhealth_9  | purged  | unhealthy    |

| 242 | test494388_myhealth_10 | removed | unhealthy    |

| 243 | test494388_myhealth_11 | removed | unhealthy    |

| 244 | test494388_myhealth_12 | purged  | unhealthy    |

| 245 | test494388_myhealth_13 | purged  | unhealthy    |

| 246 | test494388_myhealth_14 | removed | unhealthy    |

| 247 | test494388_myhealth_15 | purged  | unhealthy    |

| 248 | test494388_myhealth_16 | running | healthy      |

| 249 | test494388_myhealth_17 | purged  | initializing |

| 250 | test494388_myhealth_17 | running | healthy      |

| 251 | test494388_myhealth_18 | running | healthy      |

| 252 | test494388_myhealth_19 | running | healthy      |

| 253 | test494388_myhealth_20 | running | healthy      |

| 254 | test494388_myhealth_21 | running | healthy      |

| 255 | test494388_myhealth_22 | running | healthy      |

| 256 | test494388_myhealth_23 | running | healthy      |

| 265 | test494388_myhealth_1  | running | healthy      |

| 266 | test494388_myhealth_2  | running | healthy      |

| 267 | test494388_myhealth_3  | running | healthy      |

| 268 | test494388_myhealth_4  | running | healthy      |

| 269 | test494388_myhealth_5  | running | healthy      |

| 270 | test494388_myhealth_7  | running | healthy      |

| 271 | test494388_myhealth_9  | running | healthy      |

+-----+------------------------+---------+--------------+
```

**Comment by alena1108** [comment]
>> But this also triggered few existing instances in host2 to be marked "unhealthy" , which triggered new instances to be created in host2.

Where was the heatlchecker for those instances, on host1 or host2?

**Comment by alena1108** [comment]
Looked at the DB, instances were reported unhealthy by host id=2 (checked for instance 237 and 238)

mysql> select instance_id, host_id, reported_health from service_event where instance_id in (237,238) order by id;
+-------------+---------+-----------------+
| instance_id | host_id | reported_health |
+-------------+---------+-----------------+
|         237 |       2 | DOWN            |
|         237 |       2 | DOWN 1/2        |
|         237 |       2 | INIT            |
|         237 |       2 | UP              |
|         238 |       2 | INIT            |
|         238 |       2 | UP              |
|         237 |       2 | DOWN            |
|         238 |       2 | DOWN            |
+-------------+---------+-----------------+

host id=2 (I assume its host1? instances were running on host id=3, lets assume its host2) by some reason reported those instances as down. So the bug here would be - host1 went to disconnecting state, yet healthchecks running on it, weren't moved to host2. Should be fixed with https://github.com/rancher/cattle/pull/1043. 

Please reopen if you see this bug again.

**Comment by sangeethah** [comment]
Tested with recent build:

I noticed the same behavior of healthy instances being recreated in the following scenario:

Set up with 2 hosts:

Started a service with scale 5 - "testhealthnow" . All instances reported "healthy" state.

Started another service with scale 10 - "yello1" .When instances for this instance is getting deployed , I saw that couple of instances of the service - "testhealthnow" being recreated.

Instance Id - 3 and 5 get marked "unhealthy" and gets recreated.

```
mysql> select id,health_state,state,name from instance;
+----+--------------+---------+-------------------------+
| id | health_state | state   | name                    |
+----+--------------+---------+-------------------------+
|  1 | healthy      | running | Default_testhealthnow_1 |
|  2 | healthy      | running | Default_testhealthnow_2 |
|  3 | healthy      | purged  | Default_testhealthnow_3 |
|  4 | healthy      | running | Default_testhealthnow_4 |
|  5 | healthy      | purged  | Default_testhealthnow_5 |
|  6 | NULL         | running | Network Agent           |
|  7 | NULL         | running | Network Agent           |
|  8 | healthy      | running | Default_yello1_1        |
|  9 | healthy      | running | Default_yello1_2        |
| 10 | healthy      | running | Default_yello1_3        |
| 11 | healthy      | running | Default_yello1_4        |
| 12 | healthy      | running | Default_yello1_5        |
| 13 | healthy      | running | Default_yello1_6        |
| 14 | healthy      | running | Default_yello1_7        |
| 15 | healthy      | running | Default_yello1_8        |
| 16 | healthy      | running | Default_yello1_9        |
| 17 | healthy      | running | Default_yello1_10       |
| 18 | healthy      | running | Default_testhealthnow_6 |
| 19 | healthy      | running | Default_testhealthnow_7 |
| 20 | healthy      | running | Default_yello2_1        |
| 21 | healthy      | running | Default_yello2_2        |
| 22 | healthy      | running | Default_yello2_3        |
| 23 | healthy      | running | Default_yello2_4        |
| 24 | healthy      | running | Default_yello2_5        |
| 25 | healthy      | running | Default_yello2_6        |
| 26 | healthy      | running | Default_yello2_7        |
| 27 | healthy      | running | Default_yello2_8        |
| 28 | healthy      | running | Default_yello2_9        |
| 29 | healthy      | running | Default_yello2_10       |
+----+--------------+---------+-------------------------+
29 rows in set (0.00 sec)

```

**Comment by alena1108** [comment]
Figured out the reason why it happens. By some reason, haproxy reports INIT state for the same instance twice over time:

mysql> select id, reported_health, host_id, created from service_event where instance_id=3 order by id;
+----+-----------------+---------+---------------------+
| id | reported_health | host_id | created             |
+----+-----------------+---------+---------------------+
|  2 | DOWN            |       2 | 2015-11-12 03:17:04 |
| 13 | DOWN 1/2        |       2 | 2015-11-12 03:20:07 |
| 15 | INIT            |       2 | 2015-11-12 03:20:09 |
| 16 | UP              |       2 | 2015-11-12 03:20:11 |
| 18 | INIT            |       2 | 2015-11-12 03:20:43 |
| 21 | UP              |       2 | 2015-11-12 03:20:45 |
+----+-----------------+---------+---------------------+
6 rows in set (0.00 sec)

INIT reported state at 03:20:43 is considered as unhealthy, and that triggers instance removal by the service reconcile. 

mysql> select process_name, start_time from process_instance where resource_id=3 and resource_type='instance';
+--------------------------+---------------------+
| process_name             | start_time          |
+--------------------------+---------------------+
| instance.create          | 2015-11-12 03:16:05 |
| instance.updatehealthy   | 2015-11-12 03:20:11 |
| instance.updateunhealthy | 2015-11-12 03:20:43 |
| instance.updatehealthy   | 2015-11-12 03:20:45 |
| instance.remove          | 2015-11-12 03:20:57 |
| instance.stop            | 2015-11-12 03:20:57 |
| instance.remove          | 2015-11-12 03:20:59 |
| instance.purge           | 2015-11-12 03:22:47 |
+--------------------------+---------------------+
8 rows in set (0.00 sec)

mysql> select id, process_name, start_time from process_instance where resource_id=2 and resource_type='service';
+-----+------------------+---------------------+
| id  | process_name     | start_time          |
+-----+------------------+---------------------+
|  76 | service.create   | 2015-11-12 03:16:02 |
|  77 | service.activate | 2015-11-12 03:16:05 |
| 196 | service.update   | 2015-11-12 03:20:43 |
| 428 | service.update   | 2015-11-12 04:17:13 |
| 571 | service.update   | 2015-11-12 04:19:37 |
+-----+------------------+---------------------+


INIT health state reported twice can be caused by many reasons - healtcheck go process restart, agent instance restart. Just reproduced this issue very easily:

1) Have just one host in the setup.
2) Start service with one instance, healtcheck enabled.
3) Wait for the healthcheck to become green.
4) Restart the network agent that does the healtcheck. Your container created on step 2) will get restarted. 

Very good bug, very worth fixing

**Comment by alena1108** [comment]
Sangeetha, fix is in master. Could you please run 2 tests - one that I've provided (network agent restart), and another yours. See if any of it results in the same kind of failure.

**Comment by sangeethah** [comment]
Tested with build from master:

All the scenarios mentioned in the bug work as expected and does not result in  marking healthy instances as "unhealthy".
