### ISSUE TITLE
Upgrading cluster with a downed control plane node breaks secret encryption

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#26421]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Start with a cluster with at least two control plane nodes
2. Stop docker on one of them
3. Enable secret encryption per [the docs](https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/#enable-encryption)
4. Wait for Rancher to complain about not being able to connect to the downed node
5. Start docker back up and wait for the upgrade to "finish"

**Result:**

Should result in the following error:

```
Internal error occurred: unable to transform key "/registry/secrets/kube-system/rke-job-deployer-token-pxc8p": no matching key was found for the provided AES transformer
```

**Other details that may be helpful:**

At this point disabling and re-enabling encryption does not resolve this. The secrets are never re-written to be encrypted.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.6

- Installation option (single install/HA):
both

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
custom

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
any

- Kubernetes version (use `kubectl version`):
v1.17.4-rancher1-2

- Docker version (use `docker version`): 

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

gz#9286

SURE-1893

**Comment by HarrisonWAffel** [comment]
This issue could not be reproduced on Rancher 2.7.0. 

After stopping the docker service on a control-plane node and attempting to enable secrets encryption, the UI throws an unmentioned error stating: `cannot proceed with upgrade of controlplane since 1 host(s) cannot be reached prior to upgrade`. Shortly after that message, another message regarding a failing health check will be displayed since one node is no longer responsive. 

After restarting docker on the control plane node the upgrade does not automatically continue, but I can still manage the downstream node. Additionally the health check error will no longer be present, though the error referencing an unreachable host will be present. After modifying the cluster to force a reconciliation both error messages go away, and you are able to, for example, remove a node pool or scale existing node pools. After that reconciliation is finished the cluster will become available again, and no error messages will be seen.
