### ISSUE TITLE
Can no longer remove Users from a Project

### ISSUE THREAD

**Issue by gregsidelinger** [rancher/rancher#26428]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Setups local users
Create a project
Add users as a project member to the project and save.

**Result:**
Edit the project and you will notice the minus sign does not appear next any of the new users

![image](https://user-images.githubusercontent.com/1437031/78180894-7302bc00-7431-11ea-8e54-6b6e99e95c57.png)

**Other details that may be helpful:**
I've seen this on a rancher setup that uses LDAP for user when logged in via LDAP users too. This also appears to happen with rancher setup for 100% local users.

I've used chrome and firefox reproduce.

**Environment information**
- Rancher version: 2.4.1
- Installation option (single install/HA): HA via helm

**Comment by rancher-max** [comment]
Similar to #24934. UI Workaround right now is to navigate to the Project and select "Members"

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/55997940/78280470-012c8000-74ce-11ea-9378-acee20617cc5.png">

**Comment by izaac** [comment]
@rancher-max that's only for local users, but if we use other Auth we can't do that. Just checked this with OpenLDAP.

**Comment by rancher-max** [comment]
#### Validated in master-2720-head (`3c6eb2b74`) and v2.4-2718-head (`64cf5ecd0`) using ui-index `latest2` and `latest-2.4`, respectively

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/55997940/78734312-cb87fc80-78fc-11ea-96ce-89f8be82500a.png">

- Minus button is present again when editing the project
- Using the minus button works to remove those users from the project now as well


**Reopening because there is no minus button when adding users on initial project creation and there should be.**

**Comment by rancher-max** [comment]
#### Validated using ui-index `latest2` and `latest-2.4`

This is working now for both edit projects and new projects. Validated the same as in the previous comment.
