### ISSUE TITLE
ingress: extra_args: not visible in 'Edit as YAML' view of RKE Template

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#26469]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.4.2 instance
2. Create a new RKE Template, click 'Edit as YAML' and set the ingress definition as follows:

```
  ingress:
    provider: nginx
    extra_args:
      enable-ssl-passthrough: ""
```
3. Save the RKE Template, then view the revision and click 'Edit as YAML', observe the 'extra_args' section is not visible.
4. Click 'View in API' for the revision and observe the enable-ssl-passthrough is set as expected:
```
"ingress": {
    "extraArgs": {
        "enable-ssl-passthrough": ""
    },
    "provider": "nginx",
    "type": "/v3/schemas/ingressConfig"
},
```

**Environment information**
- User reported in Rancher v2.3.3, I reproduced in Rancher v2.4.2

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.4.2`
Steps:
* Create a new RKE Template, click 'Edit as YAML' and set the ingress definition as follows:
```
  ingress:
    provider: nginx
    extra_args:
      enable-ssl-passthrough: ""
```
* Save the RKE Template, then view the revision and click 'View as YAML', observe the 'extra_args' section is not visible.
![Screen Shot 2020-06-24 at 3 04 18 PM](https://user-images.githubusercontent.com/57409052/85633712-a28b2400-b62e-11ea-947b-eb4f11fc4e85.png)
* Click 'View in API' for the revision and observe the enable-ssl-passthrough is set as expected:
![Screen Shot 2020-06-24 at 3 00 17 PM](https://user-images.githubusercontent.com/57409052/85633729-ab7bf580-b62e-11ea-9908-111ad7bcc97e.png)


The bug fix is verified with Rancher server `rancher\rancher:v2.4-head` `version 46f7940dd`
`extra_args` is visible in `View as YAML`: 
![Screen Shot 2020-06-24 at 3 27 21 PM](https://user-images.githubusercontent.com/57409052/85633970-41178500-b62f-11ea-9a7a-2ca4f5e256d6.png)
And in `View in API`:
![Screen Shot 2020-06-24 at 3 27 38 PM](https://user-images.githubusercontent.com/57409052/85633974-42e14880-b62f-11ea-941e-c23d3c5f8dec.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version c4efe069d`
`extra_args` is visible in `View as YAML`:
![Screen Shot 2020-06-24 at 3 33 56 PM](https://user-images.githubusercontent.com/57409052/85634393-22fe5480-b630-11ea-96f9-d93de489146c.png)

And in `View in API`:
![Screen Shot 2020-06-24 at 3 33 44 PM](https://user-images.githubusercontent.com/57409052/85634397-2560ae80-b630-11ea-8b1e-d7ac3dbb9df7.png)
