### ISSUE TITLE
Clusters go into Updating state for some time after an upgrade to 2.4.2  from 2.3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26471]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster - 1.16/1.15 in 2.3.5 - 1 node all roles
- Upgrade rancher server to 2.4.2
- The clusters go into "Updating" state (for about few seconds) and come back "Active".

**Expected Result:**
The clusters should not go into "Updating" state

**Other details that may be helpful:**
This does not happen on an upgrade from 2.3.5 to 2.3.6

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5 to 2.4.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.15/1.16
```

**Comment by mrajashree** [comment]
Tried to reproduce this multiple times but couldn't. Since the "updating" state lasts for a few seconds, and the logs from the test setup don't contain any messages corresponding to an actual cluster upgrade, this isn't an rke up for sure. So at least the cluster isn't getting upgraded without any trigger. Not sure why the state change was seen in UI

**Comment by soumyalj** [comment]
The same issue was observed when rancher was upgraded from v2.3.6 to v2.4.3-rc2. 
**Pre upgrade in v2.3.6**
K8s version: v1.15/v1.16
RKE and Hosted K8s clusters(GKE, AKS, EKS) clusters were deployed in v2.3.6

**Post upgrade to v2.4.3-rc2**
All clusters went to "Updating" state for a brief time(2 to 5s)
No upgrade was triggered on the clusters.

**Comment by mrajashree** [comment]
@sangeethah @soumyalj @sowmyav27 can we have debug logs enabled during upgrade testing next time? Since the state change is for such short time, checking UI is not useful and INFO logs don't tell much either

**Comment by soumyalj** [comment]
@mrajashree : Reproduced the issue again with debug logs enabled and provided you the setup.

**Comment by mrajashree** [comment]
UI shows "Updating" state when ClusterConditionUpdated is Unknown. 
On rancher-server upgrade, cluster sync happens, during which the [provisioner controller](https://github.com/rancher/rancher/blob/master/pkg/controllers/management/clusterprovisioner/provisioner.go#L125) calls ClusterConditionUpdated.Do(), to check whether the cluster needs an upgrade. This method in norman sets the Updated condition to [Unknown](https://github.com/rancher/norman/blob/master/condition/condition.go#L208) first, while checking if the cluster spec has changed. Since the cluster spec doesn't change on Rancher upgrade, the provisioner controller doesn't trigger a cluster upgrade, but because the condition "Updated" was set to "Unknown", for that duration the state is "Updating" in UI. I still think this would have happened for earlier rancher versions too

**Comment by mrajashree** [comment]
The above comment explains the "Updating" state, and from discussion with @dramich this would have been the behavior for older versions too, but since 2.4 uses one management controller, it's more visible in 2.3 -> 2.4 upgrade. So @maggieliu @deniseschannon this is not a bug
