### ISSUE TITLE
[Backport 2.3] Cannot add label to node in imported cluster

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#26497]
2.3.6

Backport https://github.com/rancher/rancher/issues/26496

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.0.4`
**Steps:**
Import a k3s cluster or other any cluster
go to node page
Try to add a label to a node
**Result:** 
Node label is not saved

The bug fix is verified with Rancher server `rancher\rancher:v2.3-head` `version 538a1a478`
Node labels can be added and saved.
<img width="489" alt="Screen Shot 2020-04-07 at 4 33 07 PM" src="https://user-images.githubusercontent.com/57409052/78729299-91aff980-78ee-11ea-8f11-f17bf786ca67.png">
<img width="389" alt="Screen Shot 2020-04-07 at 4 32 58 PM" src="https://user-images.githubusercontent.com/57409052/78729306-9379bd00-78ee-11ea-921b-9f7b30296766.png">
