### ISSUE TITLE
[Help/LDAP] Changing LDAP backend 

### ISSUE THREAD

**Issue by Kanshiroron** [rancher/rancher#26503]
Rancher 2.2.7

Hello,
We need to migrate or current authentication backend (now FreeIPA) to a new one (OpenLDAP), and we are looking forward knowing what is is the correct reciepe.
Almost everything has changed, from the URL, to the base DN, group filters and so on.

- Is-it possible to directly change CustomResources? If so which ones?

- If re-creating the Rancher cluster is our solely option then fine, but I guess we need to delete all CustomResource from all clusters?

Please advise,
Thanks a lot!

**Comment by vincent99** [comment]
I don't know what custom resources you're referring to... "Database diving" to manipulate the rancher config in the local cluster is possible but not supported, or needed here.  The only thing stored in the "downstream" clusters it is managing are standard Roles and RoleBindings.

- Create a local admin account if you don't have one sheet
- Login as it
- Disable old auth provider
- Configure and enable new one
- Clean up old users and memberships.  If there is some relation you could potentially automate this by editing users in the API, otherwise probably delete all and start over.

**Comment by Kanshiroron** [comment]
Thank you @vincent99 for your quick answer. I will try that and let you know

**Comment by Kanshiroron** [comment]
Hey @vincent99 
That pretty much worked correctly. I had to re-create group member ships but that was pretty much expected.
Thanks again for your help,
Best regards,
