### ISSUE TITLE
[UI] UI hangs when attempting to clone a cluster role as Standard User

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26547]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. make a new Standard User
2. login as Standard User
3. go to `Security > Roles > Cluster`
4. go to menu for a role and select `Clone`

**Result:**
UI hangs. Console shows this error:
![image](https://user-images.githubusercontent.com/19376037/78726494-febf9100-78e6-11ea-8f18-60b28e64d78f.png)

**Other details that may be helpful:**
Doesn't happen in Rancher v2.3.6
Doesn't appear to happen to Admin users

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.4.2`
Steps:
make a new Standard User
login as Standard User
go to `Security > Roles > Cluster`
go to menu for a role and select `Clone`
Result:
UI hangs with:
![Screen Shot 2020-04-09 at 3 49 36 PM](https://user-images.githubusercontent.com/57409052/78950316-3ebb7b00-7a83-11ea-9b76-70bd574a7283.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 03947c351` and `rancher\rancher:v2.4-head` `version 03947c351`
Result:
Add Cluster Role page can be accessed:
![Screen Shot 2020-04-09 at 3 56 19 PM](https://user-images.githubusercontent.com/57409052/78950344-5692ff00-7a83-11ea-99cb-3e34b2ede00a.png)
