### ISSUE TITLE
Node Template Unavailable to Creator - Forbidden by API

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#26575]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Unsure

1. Create a Node Template with a User
2. Clone that Node Template with the same User

**Result:**

Cloned Template might be unavailable?

**Other details that may be helpful:**

I wanted to clone an existing node template and make some changes to it, so I did that and everything appears to be ok, it's even in the API (for other users to see) but the user that created it gets 

```
{
"baseType": "error",
"code": "Forbidden",
"message": "nodetemplates.management.cattle.io \"nt-hkcl4\" is forbidden: User \"u-sm7rb\" cannot get resource \"nodetemplates\" in API group \"management.cattle.io\" in the namespace \"cattle-global-nt\"",
"status": 403,
"type": "error"
}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Comment by sergiomacedo** [comment]
This problem is still present on Rancher 2.4.2. 

I was able to reproduce the problem with a newly created standard user and newly created templates, without any extra annotations or rancher upgrade between node template creation and cloning. 

It does not to seem related to https://github.com/rancher/rancher/issues/26946

Component | Version
Rancher | v2.4.2
User Interface | v2.4.14
Helm | v2.16.3-rancher1
Machine | v0.15.0-rancher35

**Comment by izaac** [comment]
This is reproducible in `v2.4.2`

- Rancher single install with rancher generated certs
- login as local `admin`
- create `user1` (**Standard User** only checked during creation).
- logout `admin`
- login as `user1`
- go to node templates and create a new template (DO for example). `og-template`
- Once the `og-template` template is created clone it as `cloned-template1`

There are a few things here we can do to check the error. Click `View in API` from `cloned-template1`

```json
{
"baseType": "error",
"code": "Forbidden",
"message": "nodetemplates.management.cattle.io \"nt-xxxxx\" is forbidden: User \"u-xxxxx\" cannot get resource \"nodetemplates\" in API group \"management.cattle.io\" in the namespace \"cattle-global-nt\"",
"status": 403,
"type": "error"
}
```

Try creating a cluster with `cloned-template1`
Creating node pools will fail `unable to find node template [cattle-global-nt:nt-xxxxx]: undefined`
```
{"baseType":"error","code":"NotFound","message":"unable to find node template [cattle-global-nt:nt-xxxxx]","status":404,"type":"error"}
```

Refresh the browser in the Node Templates page, the cloned templates will disapear from the UI (because they won't get listed).

I don't see these cloned node templates listed in `/v3/nodeTemplates/`

**Comment by izaac** [comment]
This is not reproducible in `v2.4-head`

**Comment by sergiomacedo** [comment]
How about 2.4.3?

**Comment by izaac** [comment]
@sergiomacedo that version also has the issue, `v2.4.4` will include the fix once it's released.
