### ISSUE TITLE
Rancher Server triggered alerts doesn't work when using customized cluster domain.

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#26597]
All rancher 2.x

Steps:

1. Create a cluster with customized cluster domain instead of `cluster.local`
2. Enable a project level alert with `Workload` alert type

Results:

Alert never sent out. And following error shows in Rancher Server pod.

```
2020/04/10 14:09:44 [ERROR] Failed to send alert: Post http://alertmanager-operated.cattle-prometheus.svc.cluster.local:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus.svc.cluster.local on 10.43.0.10:53: no such host
```

Solution:

We should not hard code `cluster.local` in alert controller as  it can be customized

**Comment by DoNotSayYes** [comment]
**Reproduced in** `rancher/rancher:v2.4.4`
**Steps:**
1. Create a cluster with customized cluster domain instead of cluster.local, e.g.,  wilson.local
2. Add a project level alert
3. Check rancher server logs
```
cd /var/lib/docker/containers/rancher_server_container_id
less container_id-json.log | grep cluster.local
```

**Result:**
Alerts sent failed, got error logs in rancher server
```
{"log":"2020/06/09 02:22:03 [ERROR] Failed to send alert: Post http://alertmanager-operated.cattle-prometheus.svc.cluster.local:9093/api/v1/alerts: dial tcp: lookup alertmanager-operated.cattle-prometheus.svc.cluster.local on 10.43.0.10:53: no such\n","stream":"stdout","time":"2020-06-09T02:22:03.435137342Z"}
```

Tested in `rancher/rancher:master-head` off 9th June
**Steps:**
1. Create a cluster with customized cluster domain instead of cluster.local, e.g.,  wilson.local
2. Add a project level alert

**Result:**
Alerts sent successfully
![image](https://user-images.githubusercontent.com/57614736/84134729-983c2800-aa7b-11ea-8627-f13161dfa6f2.png)
![image](https://user-images.githubusercontent.com/57614736/84134609-69be4d00-aa7b-11ea-8c1e-36b2f7af0947.png)
![image](https://user-images.githubusercontent.com/57614736/84134653-79d62c80-aa7b-11ea-8634-59d3e30f4aa4.png)
