### ISSUE TITLE
[Backport 2.3] app update/edit via api should not expect projectID

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#26632]
Backport fix for this bug to 2.3 https://github.com/rancher/rancher/issues/24371

**Comment by jiaqiluo** [comment]
The bug is validated on rancher:v2.3-head a0c372a82 

Now we can deploy/edit an app using either project or cluster catalog via command line without passing the `projectId` key 

`via command line` means first getting the curl command by tracking the network in Rancher UI then running the command with modified value in a terminal

`without passing the projectId key` means removing the `projectId` item from the request's data section
