### ISSUE TITLE
Node hostname issues when Amazon/AWS cloud provider is configured

### ISSUE THREAD

**Issue by anouarchattouna** [rancher/rancher#26637]
When cloud provider is configured to `AWS`, the node resource name is set to the internal DNS name of the AWS instance.

This should be fixed by https://github.com/rancher/rancher/issues/22849 but reproduced with the following version

* Rancher **v2.3.2**
* Cloud Provider **AWS**

![Screenshot 2020-04-15 at 5 24 18 PM](https://user-images.githubusercontent.com/9251649/79356419-3c539800-7f3f-11ea-9760-c0f53fac1aee.png)

**Comment by ahmedfourti** [comment]
I have same issue with Rancher version 2.3.6

**Comment by superseb** [comment]
The behavior is not a bug, its how the cloud provider works. The issue referenced when was restarting nodes, they wouldn't get the certificates back because the nodename was not recognized as it differs from initial registration. The fix for that went in v2.3.3.

If you encounter any issues, please describe the steps to reproduce and the error situation you are seeing. The screenshot does not show an error situation, the names set by cloud provider is how the AWS cloud provider works. See https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#aws
