### ISSUE TITLE
Istio Integration: Allow activating Automatic mutual TLS in interface

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#26797]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
Automatic mutual TLS is a very nice feature of istio to automatically encrypt traffic between istio proxies.
It can be optionally activated by setting the `global.mtls.auto`  flag to `true` when installing/configuring istio.
Of course this setting can be provided as a "Custom answer" but it would be nice to have this as a checkbox in the Istio installation/configuration interface to make it easier to use.

**Result:**
There is a checkbox in the istio installation/configuration interface to toggle Automatic mutual TLS.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): HA

 gz#10377

**Comment by Tejeev** [comment]
Having Rancher smoothly enable MTLS for Istio with some documentation on how to work with it would be very helpful to some of our customers.

**Comment by Tejeev** [comment]
gz#10377

**Comment by doflamingo721** [comment]
We now don't need to activate auto mTLS manually, all traffic between workloads with proxies uses mutual TLS by default. This was enabled in istio 1.5 and has been default since then. Refer [this](https://istio.io/v1.15/docs/tasks/security/authentication/authn-policy/#auto-mutual-tls) document for more information. 
Closing this issue based on the above findings.
