### ISSUE TITLE
Upgrade from v2.4.2 to v2.4.3-rc2 the K8s version dropdown in edit cluster is empty sometimes

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26791]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Upgrade from Rancher v2.4.2 to v2.4.3-rc2 HA
  - Local imported cluster k8s: `v1.17.4`
  - Build your own certificate with Recognized CA
  - RKE clusters used 
    - Azure `v1.15.11-rancher1-3`
    - EC2 `1.16.8-rancher1-3`
    - Custom `Windows 1.16.8-rancher1-3`
  - EKS `v1.14.9-eks-f459c0`

- Install command:
   - `helm_v3 install rancher rancher-latest/rancher --version v2.4.2 --namespace cattle-system --set hostname=<hostname> --set ingress.tls.source=secret --set rancherImageTag=v2.4.2`

- Upgrade command:
  - `helm_v3 upgrade rancher rancher-latest/rancher --version v2.4.3-rc2 --namespace cattle-system --set hostname=<hostname> --set ingress.tls.source=secret --set rancherImageTag=v2.4.3-rc2`

**Result:**

Going to Edit cluster in each of the above clusters shown the `Kubernetes version` dropdown empty.

**Other details that may be helpful:**

I had to navigate and click: `Global -> Tools -> Drivers -> Refresh Kubernetes Metadata` and after that the Dropdown was populated again with k8s versions.

**Environment information**
- Rancher version: `v2.4.3-rc2`
- Installation option: HA with local k8s `v1.17.4` cluster

**Comment by StrongMonkey** [comment]
Related https://github.com/rancher/rancher/issues/24091

**Comment by StrongMonkey** [comment]
#24091 is not addressed, This issue is not easy to reproduce during the normal setup. 
@izaac You should try to following setup and should be able to reproduce this bug:
1. Create a HA cluster with 3 nodes, wait for kubernetes dropdown to be popuated.
2. Edit rancher deployment to increase one replica, and then check kubernetes dropdown. You should see empty value.

I put an fix and will need to verify with @kinarashah about the potential regression. Once fix is put in, try the steps above and verify the bug.

Also I would like verify that no regression is introduced. You might also need to verify the following setting is populated correctly. You can go to https://server-url/v3/settings and check each value.
1. k8s-version
2. k8s-version-to-service-options
3. k8s-version-to-images
4. k8s-versions-current
5. k8s-versions-deprecated
6. ui-k8s-supported-versions-range
7. ui-k8s-default-version-range

You can compare the value with the value in v2.4.2 or v2.4.3-rcx. The default value for each setting should be empty. Also check the dashboard of cluster template to make sure everything is correct.

**Comment by izaac** [comment]
Increasing the replicas in Rancher version `v2.4.3-rc3` I increased it three times and went ahead to validate the k8s version dropdown each time. It was populated and available for selection the three times in Custom/RKE/Cloud provisioners.

I also checked these settings values as suggested after increasing the replicas. They looked good

1. k8s-version
2. k8s-version-to-service-options
3. k8s-version-to-images
4. k8s-versions-current
5. k8s-versions-deprecated
6. ui-k8s-supported-versions-range
7. ui-k8s-default-version-range

My setup was the upgrading path from Rancher `v2.3.6` to `v2.4.3-rc3`

**Comment by izaac** [comment]
Validated in Rancher version: `master-2839-head (05/01/2020)` commit id: 8e9f88bed HA k8s setup. `v2.4.3-rc4`  and image override `master-head`

I increased it three times and went ahead to validate the k8s version dropdown each time. It was populated and available for selection the three times in Custom/RKE/Cloud provisioners.


I also checked these settings values as suggested after increasing the replicas. They looked good

1. k8s-version
2. k8s-version-to-service-options
3. k8s-version-to-images
4. k8s-versions-current
5. k8s-versions-deprecated
6. ui-k8s-supported-versions-range
7. ui-k8s-default-version-range
