### ISSUE TITLE
EKS, GKE and AKS going into Updating state for a few seconds after a rancher upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26793]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy AKS/GKE/EKS clusters in 2.3.6
- Upgrade rancher to 2.4.3-rc2
- The clusters go into "Updating" state for a few seconds ~ < 5 seconds
- EKS cluster shows error while updating: 

<img width="1092" alt="Screen Shot 2020-04-23 at 2 15 42 PM" src="https://user-images.githubusercontent.com/26032343/80164166-16f10a80-858d-11ea-80d0-ef341c266032.png">

**Expected Result:**
The cluster should not go into Updating state

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.6 to 2.4.3-rc2
- Installation option (single install/HA): HA/Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted

**Comment by sangeethah** [comment]
This is similar to the behavior seen for RKE clusters getting into "updating" state for a short time which is tracked in https://github.com/rancher/rancher/issues/26471

**Comment by mrajashree** [comment]
@sangeethah @soumyalj @sowmyav27 can we have debug logs enabled during upgrade testing next time? Since the state change is for such short time, checking UI is not useful and INFO logs don't tell much either

**Comment by soumyalj** [comment]
@mrajashree : Reproduced the issue again with debug logs enabled and provided you the setup.

**Comment by mrajashree** [comment]
UI shows "Updating" state when ClusterConditionUpdated is Unknown.
On rancher-server upgrade, cluster sync happens, during which the provisioner controller calls ClusterConditionUpdated.Do(), to check whether the cluster needs an upgrade. This method in norman sets the Updated condition to Unknown first, while checking if the cluster spec has changed. Since the cluster spec doesn't change on Rancher upgrade, the provisioner controller doesn't trigger a cluster upgrade, but because the condition "Updated" was set to "Unknown", for that duration the state is "Updating" in UI. I still think this would have happened for earlier rancher versions too

**Comment by mrajashree** [comment]
The above comment explains the "Updating" state, and from discussion with @dramich this would have been the behavior for older versions too, but since 2.4 uses one management controller, it's more visible in 2.3 -> 2.4 upgrade. So @maggieliu @deniseschannon this is not a bug
