### ISSUE TITLE
Custom image support in Azure requires managed disks and managed availability sets

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26804]
Version: v2.4.3-head/master-head

Steps:
1. Create Azure node template by specifying custom image. 

- During template creation, it is required to specify `managed disk` for disk type option

![Screen Shot 2020-04-24 at 9 57 01 AM](https://user-images.githubusercontent.com/18536626/80237713-0afb5c00-8612-11ea-8442-5093854ea689.png)

Using "Unmanaged" disks  in the node template will result in the below error during cluster creation:
```

Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="VM created from Image cannot have blob based disks. 
All disks have to be managed disks."

```

- It is also required use a managed `Availability Set` . The default "docker-machine" is not a managed "availability set"

![Screen Shot 2020-04-24 at 10 00 55 AM](https://user-images.githubusercontent.com/18536626/80238136-c15f4100-8612-11ea-8ee9-f5dd322370b3.png)

UI should provide information for these requirements in the node template page. This would help the users to provide the right input when Azure custom images are used

**Comment by aiyengar2** [comment]
This requirement seems to be documented as a service constraint imposed by Azure in https://github.com/Azure/azure-sdk-for-java/issues/1815 and is documented under [common VM error codes](https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/error-messages).

**Comment by westlywright** [comment]
Availability Set label now includes managed or unmanaged depending on the disk type selected.

Image includes the following help block below the input Providing an ARM resource identifier requires using managed disk

Disk type includes the follow help block below the input, "Creates a unmanaged availability set " or "Creates a managed availability set", depending on what disk is selected.

**Comment by aiyengar2** [comment]
Some clarifications:

Unmanaged disks can still be used for Marketplace images that are provided in the `provider:sku:offer:version` format.

However, custom images (provided in an ARM resource identifier format) must use managed disks; since managed disks must use managed availability sets and unmanaged disks must use unmanaged availability sets, custom images also require the use of managed availability sets.


Therefore, it should be documented that a user who wants to use / migrate to using custom images must set `managedDisks: true`. In addition, if their node template references an availability set that currently exists in the resource group provided, they should ensure that the availability set is a managed availability set. 

Alternatively, simply changing the availability set name to one that does not currently exist in the resource group should trigger the creation of a new availability set, in which case it will be created as managed / unmanaged based on `managedDisks`.

**Comment by soumyalj** [comment]
Validated with v2.4-head (8a5b2eb39). 
Disk type field provides more info as below:
![Screen Shot 2020-04-24 at 3 54 45 PM](https://user-images.githubusercontent.com/18536626/80263125-6f371380-8644-11ea-87f6-7c7725246aca.png)
Availability set field also has a label which displays "Managed or Unmanaged " based on the disk type chosen
![Screen Shot 2020-04-24 at 4 00 07 PM](https://user-images.githubusercontent.com/18536626/80263212-c2a96180-8644-11ea-85b7-d61eced70dbc.png)
