### ISSUE TITLE
Worker node cordoned after adding new worker in custom rke cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#26807]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Deploy a custom cluster in Rancher `v2.4.3-rc2` k8s version `1.17.5-rancher1-1` (1 node, all roles)
Wait for cluster to become available.
Add a worker node.
Continue adding worker nodes until previous nodes become cordoned.

**Result:**
![Screen Shot 2020-04-24 at 12 05 15 PM](https://user-images.githubusercontent.com/57409052/80249860-700d7c80-8627-11ea-8f3e-c263d6197072.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.4.3-rc2`
- Installation option (single install/HA): Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom

Related issue:
https://github.com/rancher/rancher/issues/26790

**Comment by StrongMonkey** [comment]
@aaronRancher I assume this is the same issue that was happening on https://github.com/rancher/rancher/issues/26791?

**Comment by aaronRancher** [comment]
@StrongMonkey This is part of the same issue, but created to specifically note the "cordoned" behavior. We've seen nodes become temporarily "cordoned" when a worker node is successfully provisioned. Can close issue if deemed too redundant.

**Comment by StrongMonkey** [comment]
I am not aware of node being cordoned automatically though. @kinarashah ^^ maybe you have some idea?

**Comment by sowmyav27** [comment]
Verified on a custom image from 2.4-release and master branch 

**Steps:**

- Create a custom cluster - 1 node all roles
- Add a worker node - The worker node will be stuck in registering state because of this issue - https://github.com/rancher/rancher/issues/26790
- Add more worker nodes 
- No panic is seen
- The cluster goes into `Updating` state for about 3-5 seconds and comes back to `Active`.
- Existing "Active" worker nodes do NOT go into "Cordoned" state.
