### ISSUE TITLE
Failed to open Rancher Dashboard on v2.4.2

### ISSUE THREAD

**Issue by babytut** [rancher/rancher#26848]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug on open Rancher new Dashboard v2.4.2

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher on company network with firewall block access to  https://releases.rancher.com/dashboard/release-2.4/index.html
- After installed, click Try Dashboard button, it return 500 error and not show anything.
- Check log rancher container, it shows log
Get https://releases.rancher.com/dashboard/release-2.4/index.html: dial tcp 104.26.4.146:443: connect: connection refused
**Result:**
it return 500 error and not show anything

**Other details that may be helpful:**
I think it should still open Dashboard 

**Environment information**
- Rancher version v2.4.2 (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Single install and HA install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vincent99** [comment]
The dashboard UI is experimental and intentionally hosted on our CDN for now so that we can update it outside of the Rancher release cycle.

If you do not have access to our CDN you cannot currently use it.  You can disable the feature flag to prevent it from showing up.

When it becomes a stable feature it will be packaged with the release as usual.
