### ISSUE TITLE
RFE - RBAC - Allow project "-promoted" role exclusions

### ISSUE THREAD

**Issue by chrisreed87** [rancher/rancher#26856]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Currently, if the role of a user in the project contains: storageClass, persistentVolumes and apiServices, Rancher creates a `-promoted` clusterrolebinding to allow access to those resources.

For customers who would like to create custom Project Roles that granted certain Project members to cluster-level resources, perhaps an annotation to a `ProjectRoleBinding` to prevent the `-promoted` CRB from being created would be helpful, that way it would give those customers more control over what Cluster resource they'd like their users/accounts to have

**Comment by skaven81** [comment]
Actually the RFE here is not to _prevent_ the `-promoted` CRB from being created.  It's to allow the `-promoted` CRB to include resources other than the static list currently supported.  So for example, if I create a Project `roleTemplate` that includes permission to get/list/watch ValidatingWebhookConfigurations or CustomResourceDefinitions -- I would want those additonal permissions to appear in the `-promoted` CRB so that these cluster-level rights can be assigned at the Project level.  This is also important if we add 3rd party software to the cluster, that leverages CRDs and the Operator model.  There may be cases where we need to grant our users access to non-namespaced instances of these CRDs.

The Project abstraction is at its best when Rancher is tightly managing access to cluster-level resources.  For example, the way that Rancher handles Namespaces is very clever: each project gets a ClusterRole that is dynamically updated with the list of namespaces that are "in" each Project, and Project-member-based ClusterRoleBindings ensure that members of those projects can manipulate those namespaces.

I understand and accept that this won't be the behavior we get, should any cluster-level resources be included in the `-promoted` ClusterRole -- instead, any Project members would simply have unfettered access to all members of those resources; as those resources won't have any project assignment metadata for Rancher to do any magic with.  But this would still be very useful for us despite this limitation.

Managing access to Kubernetes via the Project model is a very close match to our business logic.  Development teams ask for Kubernetes access, and we create a Project for them in one or more clusters.  Everything about that development team is encoded in the Project via the ProjectRoleTemplateBindings.  We know who has access.  We know how much access they have.  We have a human-readable description and name of the development team.  All of their work is neatly organized with a project ID.

But in some cases we have "power-users" that need some (limited) access to cluster-level resources (other than StorageClass, persistentVolumes, and apiServices).  Currently, this can only be implemented by adding these power-users as *cluster* members via a Rancher ClusterRoleTemplateBinding. But now we have a disjoint management paradigm -- most of the access is being handled in the Project, and yet some aspects of the Project (namely, cluster-level rights) are handled at the Cluster level, where we don't have any way to link the membership to an application team.

By allowing any cluster-level rights to propagate out of a ProjectRoleTemplateBinding into a `-promoted` ClusterRole and corresponding ClusterRoleBinding, we would be able to continue to use the Project model for managing *all* kinds of cluster access, not just namespaced stuff.  We get to maintain that nice tidy boundary around each development team, where we can easily enumerate the members of each dev team, and enumerate all the rights they have (both inside and outside their namespaces).
