### ISSUE TITLE
Docke 1.9 named volumes removed with last container

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2686]
In Docker 1.9 volumes are a top level entity, and can be created and named. A named volume is a replacement for data containers, and to some extent lines up with host bind mounts for explicitly knowing where data is being stored. 

Current Rancher behavior cleans up volumes attached to containers. Now that named volumes are an option, we should likely not delete the named volume when the container is removed. It is possible a user would want to use it again.

**Comment by cjellick** [comment]
Working on it. I need to implement proper deletion the 1.9 way, but also need to support the old way. Here's my stop gap:
https://github.com/rancher/python-agent/pull/185

**Comment by alejom99** [comment]
Any updates on this? Thanks

**Comment by cjellick** [comment]
Done. (Rough) steps to test:
1. create a container that uses a named volume.
2. on the host, docker volume ls to verify the volume exists
3. delete and purge the container in rancher
4. wait a little while because the volume purge is scheduled a minute or two later
5. docker volume ls on the host again to verify it is gone.

**Comment by sangeethah** [comment]
Tested with rancher server version - v0.63.0-rc1
Docker version on the hosts - 1.10.2, build c3959b1
1. create a container that uses a named volume.
2. on the host, docker volume ls to verify the volume exists

```
root@sangee63-10acre-1:/home/sangeethahariharan1# docker volume ls 
DRIVER              VOLUME NAME
local               389a7e1fb515b46e2b6f2913de38b139edbb3e97002abf69fe7f5ccd1463c950
local               test1
```
3. delete and purge the container in rancher
4. wait a little while because the volume purge is scheduled a minute or two later
I waited for 5 minutes or so .. 
docker volume ls on the host  still lists the volume.

In rancher db , I see the volume is not marked as "removed" .It is in "inactive" state.

```
mysql> select * from volume where name like "test1";
+----+-------+------------+--------+--------------------------------------+-------------+----------+---------------------+---------+-------------+--------------------------------------------------+------------------+-----------------+---------------+--------+------------------+----------------+-------------+----------+-------------+---------+--------------------------------------------+-------------+
| id | name  | account_id | kind   | uuid                                 | description | state    | created             | removed | remove_time | data                                             | physical_size_mb | virtual_size_mb | device_number | format | allocation_state | attached_state | instance_id | image_id | offering_id | zone_id | uri                                        | external_id |
+----+-------+------------+--------+--------------------------------------+-------------+----------+---------------------+---------+-------------+--------------------------------------------------+------------------+-----------------+---------------+--------+------------------+----------------+-------------+----------+-------------+---------+--------------------------------------------+-------------+
|  4 | test1 |          5 | volume | 3153b9fe-0858-4d3e-97bf-5e6c4ef6ebd5 | NULL        | inactive | 2016-03-10 00:22:09 | NULL    | NULL        | {"fields":{"isHostPath":false,"driver":"local"}} |             NULL |            NULL |            -1 | docker | active           | inactive       |        NULL |     NULL |        NULL |       1 | file:///var/lib/docker/volumes/test1/_data | test1       |
+----+-------+------------+--------+--------------------------------------+-------------+----------+---------------------+---------+-------------+--------------------------------------------------+------------------+-----------------+---------------+--------+------------------+----------------+-------------+----------+-------------+---------+--------------------------------------------+-------------+
```

@cjellick : Do we expect the volume to get deleted state in DB , before the volume gets removed from the host ?

**Comment by cjellick** [comment]
I misread the initial bug and my steps to test were wrong, but its still fixed.

@cloudnautique is stating that we *should not* delete named volumes when a container using them is deleted. We made this change and actually your testing shows that we in fact do not delete the named volume.

Now, the only way to delete them is via the API because we don't expose local storage pools in the UI, but I guess that is something for @vincent99 to consider.

**Comment by cjellick** [comment]
But @sangeethah, the reason it isnt deleted on the host is that it wasnt deleted in rancher. So to more directly answer your question: the volume should be purged in rancher before it is actually gone from `docker volume ls`

**Comment by sangeethah** [comment]
@cjellick , Is there a way to delete the volumes ? I don't see local volumes being listed any where in the UI ? should I be using api to test deletion of volume?

**Comment by sangeethah** [comment]
Deleted local Volumes using API and waited for the volume to get to "purged" state.
After this confirmed , that local volume is deleted in the host (volume not listed in docker volume ls )
