### ISSUE TITLE
API metrics break with k8s v1.17.5 - Rancher 2.4.3

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#26985]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Deploy a cluster using Rancher using k8s v1.17.5

**Result:**
API metric seen in pictures stops working
![image](https://user-images.githubusercontent.com/56899019/81383200-fc08c380-9152-11ea-8d7e-82f71665e157.png)

After upgrading 1.16.9 Cluster to 1.17.5
![image](https://user-images.githubusercontent.com/56899019/81384065-7c7bf400-9154-11ea-9e09-d49e1e17043a.png)

After 10 minutes, graphs start disappearing
![image](https://user-images.githubusercontent.com/56899019/81384198-a46b5780-9154-11ea-9ca8-9d75aeac60a1.png)

After 15 minutes they are both gone,
Not sure what else is broken.
![image](https://user-images.githubusercontent.com/56899019/81384477-12178380-9155-11ea-81b1-477f68281e7b.png)

**Other details that may be helpful:**
This does not break for v1.16.9

No Data points available in Grafana aslo
![image](https://user-images.githubusercontent.com/56899019/81384324-d977aa00-9154-11ea-9e7d-db5e263987d7.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA):
HA + Rancher Launched Cluster

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Rancher Launched
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.17.5

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by kengibous** [comment]
I believe this is likely due to - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#v1170

Several metrics have been deprecated and renamed in k8s 1.17+

For example the current rancher grafana expression for api server request latency is 

avg(apiserver_request_latencies_sum / apiserver_request_latencies_count) by (instance)

but for k8s .17+ should be

avg(apiserver_request_duration_seconds_sum / apiserver_request_duration_seconds_count) by (instance)

**Comment by sangeethah** [comment]
Related issues https://github.com/rancher/rancher/issues/25201 and https://github.com/rancher/rancher/issues/26724

**Comment by maggieliu** [comment]
Brought into Monitoring v0.1.1.

**Comment by jiaqiluo** [comment]
The issue is repoed because the metric `API Server Request Rate`, which shows on a newly provisioned 1.17 cluster, does NOT show on the upgraded 1.16 -> 1.17 cluster

The same behavior is seen on both 
- `v2.4-3036-head` and
- `master-3034-head`

with both monitoring chart version 
- `0.1.0` and 
- `0.1.1`

here are the steps:
- run rancher server, single installed
- provision a cluster with k8s `1.16.10-rancher1-1`
- enable the cluster monitoring 
- wait and see the `Kubernetes Components` Metrics section in Rancher UI

![Screenshot_2020-05-26 Rancher(2)](https://user-images.githubusercontent.com/6218999/82956436-a2cbcd00-9f65-11ea-90b0-0249d6178709.png)

- upgrade the k8s cluster to `1.17.6-rancher1-1`
- wait and see the `Kubernetes Components Metrics` section in Rancher UI, notice that the metric `API Server Request Rate` is gone along with some others 

![Screenshot_2020-05-26 Rancher(3)](https://user-images.githubusercontent.com/6218999/82956516-cc84f400-9f65-11ea-82f7-bb4bbf53d2a4.png)


- provision another cluster with `1.17.6-rancher1-1`, enable cluster monitoring, wait and see the Kubernetes Components Metrics section in Rancher UI.  the metric `API Server Request Rate` shows in the UI 

![Screenshot_2020-05-26 Rancher(4)](https://user-images.githubusercontent.com/6218999/82956596-fb9b6580-9f65-11ea-8365-537065041b2e.png)

**Comment by jiaqiluo** [comment]
here is the reason for the above behavior:

We added a new logic in the monitoring chart `0.1.1` to use different sets of APIs for different k8s versions, which is calculated and applied at the time of enabling the cluster monitoring.

Upgrading the k8s version of a cluster does NOT cause apps to be re-deployed.

So, if we enable monitoring in the k8s 1.16 cluster and then upgrade the k8s to 1.17/1.18, the monitoring apps will still try fetching data from deprecated APIs, which of course will NOT work.


Since we support multiple k8s version in one release, for example, 1.16, 1,17, and 1.18, there should be no need to re-install the monitoring if we just upgrade the k8s version of a cluster.
