### ISSUE TITLE
MTU cannot be set to 0 after mtu input focused

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#27016]
The default value of MTU is 0, however if user touched the input. Users cannot change it back to 0

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.4.3

on the cluster provisioning page, we see the default value for MTU is 0:
<img width="524" alt="Screen Shot 2020-05-11 at 5 00 09 PM" src="https://user-images.githubusercontent.com/6218999/81623668-06bc9600-93a9-11ea-9120-c0d9c75d193f.png">

but as soon as you click on the input box, the value is set to 1 and cannot be set back to 0:
<img width="497" alt="Screen Shot 2020-05-11 at 5 00 26 PM" src="https://user-images.githubusercontent.com/6218999/81623707-1dfb8380-93a9-11ea-8bf7-ce398db06b4e.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher:v2.4-head 65b520517 and master-head e9957eadc

clicking on the input box will not set the value to be 1 anymore,
and we can set the MTU back to 0.
