### ISSUE TITLE
Upgrade fails with: Error: UPGRADE FAILED: cannot patch "rancher" with kind Ingress

### ISSUE THREAD

**Issue by chuegel** [rancher/rancher#27013]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
upgrading rancher from 2.3.6 to 2.4.3 via helm3 fails:
```
 helm upgrade rancher rancher-stable/rancher \
>   --namespace cattle-system \
>   --set ingress.tls.source=secret \
>   --set hostname=k8smgmt.example.com \
>   --set proxy="http://10.2.3.124:3128" \
>   --set noproxy="127.0.0.0\/8\,10.2.0.0\/16\,172.17.0.0\/16"
```
**Result:**
```
Error: UPGRADE FAILED: cannot patch "rancher" with kind Ingress: an error on the server
 ("<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center>
<h1>502 Bad Gateway</h1></center>\r\n<hr><center>openresty/1.15.8.1</center>\r\n</body>\r\n</html>") 
has prevented the request from succeeding (patch ingresses.extensions rancher)
```
```
helm list -A
NAME        	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
cert-manager	cert-manager 	1       	2019-12-14 08:19:03.076793783 +0000 UTC	deployed	cert-manager-v0.12.0	v0.12.0    
rancher     	cattle-system	5       	2020-05-10 17:54:55.133962287 +0000 UTC	failed  	rancher-2.4.3       	v2.4.3   
```

**Other details that may be helpful:**
However, version 2.4.3 is deployed on the cluster but the helm chart remains in status `failed`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure/Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by jiaqiluo** [comment]
I cannot reproduce the bug 

Steps:
- use Squid to set up a proxy https://github.com/wernight/docker-squid
- use RKE to provision a cluster (configure the Docker Daemon to use the proxy)
- install Rancher into the rke cluster following Rancher's documentation for using proxy and bring-you-own-valid-certificates. the command looks like this 
`
helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=my_hostname --set proxy="http://proxy-ip:port/" --set noProxy="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16" --set ingress.tls.source=secret --version 2.3.6
`
- it turns out the Rancher is installed properly, I can add both custom clusters and Rnacher-provisioned cluster, the squid's access logs show the traffic is going through the proxy
- upgrade Rancher to v2.4.3
`
helm upgrade rancher rancher-stable/rancher --namespace cattle-system --set hostname=my_hostname --set proxy="http://proxy-ip:port/" --set noProxy="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16" --set ingress.tls.source=secret --version 2.4.3
`
- no error during the upgrading, Rancher is upgraded successfully, clusters are functional, adding new nodes/ provisioning new clusters also work

**Comment by chuegel** [comment]
closing issue. I've re-started the upgrade process and the 2nd time all went well

**Comment by ChrisMcKee** [comment]
I had this same error, but don't use nginx (use AWS LB controller)
I ran `kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission` and reran the upgrade to fix.
