### ISSUE TITLE
Cluster provisioning fails when using private registry with authentication

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#27029]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Setup a private registry for pulling the RKE system images ([docs](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#private-registries))
2. Enable authentication on the private registry
3. Create a user with image pull privileges
4. Choose a `user:password` combination (auth string) that when encoded with Base64URL yields a string that is not valid Base64.
    *Example:*
    Username: `user1`
    Password: `passw~rd`
    Base64 encoded auth string: `dXNlcjE6cGFzc3d+cmQ=`
    Base64URL encoded auth string: `dXNlcjE6cGFzc3d-cmQ`
5. Create a custom cluster in Rancher, configuring the private registry and credentials in the cluster settings.

**Result:**
Cluster fails to be successful provisioned. Pods in the kube-system and cattle namespaces fail to start with the following error:
```
Failed pulling image "private.registry.com/rancher/pause:3.1": Error response from daemon: Get https://private.registry.com/v2/rancher/pause/manifests/3.1: no basic auth credentials
```

Kubelet logs contain the following:

```
E0511 13:20:35.373548   18685 config.go:236] while trying to parse blob "{\"auths\":{\"private.registry.com\":{\"auth\":\"dXNlcjE6cGFzc3d-cmQ=\"}}}": illegal base64 data at input byte 14
E0511 13:20:35.417430   18685 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "private.registry.com/rancher/pause:3.1": Error response from daemon: Get https://private.registry.com/v2/rancher/pause/manifests/3.1: no basic auth credentials
```

**Root Cause:**

Rancher/RKE provisions a Docker config.json containing the registry credentials to `/var/lib/kubelet`. The `auth` field in that file is incorrectly encoded using Base64URL instead of the [expected Base64 encoding](https://success.docker.com/article/generate-new-auth-in-config-json-file).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  2.3.6, 2.4.3
- Installation option (single install/HA): HA
- Kubernetes version (use `kubectl version`): 1.17.4

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.4.3

Steps:
- setup a private registry with basic auth enabled 
```
Username: jiaqi
Password: passw~rd
```

- add a new cluster with the above private registry info

<img width="1386" alt="Screen Shot 2020-05-27 at 3 20 37 PM" src="https://user-images.githubusercontent.com/6218999/83080450-1091fa80-a033-11ea-86b4-79f5b0549b73.png">


Results:
- the cluster failed to be active
- ssh into the node and get the logs of the `kubelet` container
`
E0527 22:48:53.516695   13393 kuberuntime_manager.go:729] createPodSandbox for pod "rke-network-plugin-deploy-job-lk8w2_kube-system(45c08c73-6c62-4d03-a53f-1cdecc9244d4)" failed: rpc error: code = Unknown desc = failed pulling image "jiaqi-registry.qa.rancher.space/rancher/pause:3.1": Error response from daemon: Get https://jiaqi-registry.qa.rancher.space/v2/rancher/pause/manifests/3.1: no basic auth credentials
`

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher
- `v2.4-3036-head` and
-  `master-3034-head` 

the steps are the same as the previous comment. 
Now the cluster is provisioned successfully and active.
