### ISSUE TITLE
Cluster owners can't scale nodepool if the node template has been created by a different user

### ISSUE THREAD

**Issue by spiette** [rancher/rancher#27031]
**Bug**

**Steps to reproduce (least amount of steps as possible):**
- As user *A*, create nodetemplates, and create a cluster with nodepool using this nodetemplates
- As user *A*, add user *B* as cluster owner
- As user *B*, try to scale up the node pool 

**Result:**

Error updating node pool scale: unable to find node template [cattle-global-nt:nt-u-t2k5pklxw3-nt-f9sw5]: undefined

**Other details that may be helpful:**

**Environment information**
- Rancher version (2.3.6 and 2.4.2)
- Installation option (single install/HA): HA
- Kubernetes 1.17

gzrancher/rancher#10033

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.6`

Steps:
* As user A, create node template. Create a cluster with node pool using new node template.
* As user A, add user B as cluster owner
* As user B, try to scale up the node pool

Result:
User B is unable to scale up node pool
```
unable to find node template [cattle-global-nt:nt-7s2qq]: undefined
```
![Screen Shot 2020-06-24 at 4 25 09 PM](https://user-images.githubusercontent.com/57409052/85637164-51336280-b637-11ea-836a-3a4880be0d26.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.4-head` `version fb2c5fb2d`

Reopening for a fix in master-head

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/27959

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 16616de9c`
