### ISSUE TITLE
Need af-south-1 as UI option for AWS deployment via Rancher

### ISSUE THREAD

**Issue by jlozada77** [rancher/rancher#27042]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
Customer would like to deploy to AWS South Africa region via the Rancher UI, however, they are unable to as the region values are not in the dropdown list (af-south-1).

Request is to add `af-south-1` as an available region in the dropdown via the UI.

gzrancher/rancher#10023

**Comment by rancher-max** [comment]
#### Validated in both master-head and v2.4-head UI index `latest2` and `latest-2.4`

- Region is available to select in the UI
<img width="693" alt="image" src="https://user-images.githubusercontent.com/55997940/82270025-4e529d00-9928-11ea-8759-4a74e39ca299.png">

- Selecting the region and finishing steps correctly creates a cluster in af-south region:
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/55997940/82271036-827b8d00-992b-11ea-840c-d0d74e2017a1.png">


NOTE: Had to select t3.medium for instance type instead of the default option of t2.medium presented in Rancher because AWS does not provide any "t2" instances in this region.
