### ISSUE TITLE
Etcd/ControlPlane node periodically reads itself to death.

### ISSUE THREAD

**Issue by dwene** [rancher/rancher#27061]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug.

I'm running Rancher using RKE with a single etcd/controlplane node on AWS. Periodically the etcd/controlplane node starts reading an insane amount of disk, and completely locks up (see chart below). During these events, I've attempted to SSH into the node to diagnose, but it's so locked up reading, I can't get any shell commands to run. Even a simple `ls` never completes. The only solution I've found is restarting the node.

Chart below shows EBSReadBytes statistic provided by AWS cloudwatch metrics.

<img width="1211" alt="Screen Shot 2020-05-13 at 9 52 36 AM" src="https://user-images.githubusercontent.com/12628251/81830983-67abb180-9502-11ea-872a-fdc8df3b681a.png">

Even after the EBSRead spike ends, the node is still extremely slow, which leads me to believe AWS might be rate limiting EBS, and some docker process is still trying to read a copious amount.

I've seen this happen approximately once a week for the past 2 months.

**Steps to reproduce (least amount of steps as possible):**
Create an RKE cluster using using single-node rancher with AWS as cloud provider.
Configure a single etcd/controlplane node and any number of worker nodes.
Wait a week or two.

**Result:**
As seen above.

**Other details that may be helpful:**
- etcd/controlplane node has 32GB of disk.

<img width="1251" alt="Screen Shot 2020-05-13 at 10 30 29 AM" src="https://user-images.githubusercontent.com/12628251/81833333-31236600-9505-11ea-9944-cd14e182fe10.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS cloud provider, RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): EC2 T3 Medium (2vcpu, 4GB memory)

- Kubernetes version (use `kubectl version`): v1.17.5-rancher1-1 (but it appears to happen on previous versions also)

- Docker version (use `docker version`):  19.3.8

**Comment by codejamninja** [comment]
I have seen similar behavior with a single node etcd. I have my etcd node tainted so workloads won't run on it, and after a few days the CPU burns at 100% until the server crashes. I cannot get reliable behavior from the etcd node without at least 4 CPU's, which seems a bit excessive.

**Comment by brandond** [comment]
Heavy disk IO kinda sounds like the node has swapped itself to death. How much memory do these nodes have? Have you disabled swap?

**Comment by dwene** [comment]
The node is running with 4 gigs of memory. That's a good idea though, I'll check to see if swap is on. Thanks @brandond!

**Comment by brandond** [comment]
If you're using systemd, I've found that setting a memory limit (`MemoryLimit=2G` or the like) in the unit helps a lot - otherwise the go garbage collector doesn't kick in until it's already taken up a ton of RAM, quite probably enough to throw it into swap if it's still enabled.

**Comment by dwene** [comment]
Hey @brandond that sounds like a good thing to do... but I have no idea how I would do that haha. Is that a setting I can put somewhere in my RKE config?

**Comment by immanuelfodor** [comment]
2 days ago I was woken up by thermal alerts around 2AM, and it was not fun :S Since then I was restarting the cluster several times a day to fix the problem, and also removing suspected workloads that might have caused it one by one. Rancher was the last to uninstall, and it finally solved the problem. My server almost fried itself several times under its 3 node RKE k8s cluster. 

Yesterday's last event before removing the whole Rancher deployment:

CPU usage climbs:

![Screenshot_20200610_180925](https://user-images.githubusercontent.com/21174107/84355449-ec9def80-abc2-11ea-989d-a88f863fb533.png)

CPU temperature rise:

![Screenshot_20200610_181019](https://user-images.githubusercontent.com/21174107/84355593-2838b980-abc3-11ea-86f0-2704f27f7440.png)

CPU throttling kicked in:

![Screenshot_20200610_181231](https://user-images.githubusercontent.com/21174107/84355639-3ab2f300-abc3-11ea-949f-315cf9c41ca8.png)

Meanwhile NVMe temperature rises to insane levels:

![Screenshot_20200610_181319](https://user-images.githubusercontent.com/21174107/84355687-50281d00-abc3-11ea-91c9-ec11c9df2ec8.png)

The reading to death effect in progress:

![Screenshot_20200610_183344](https://user-images.githubusercontent.com/21174107/84355741-6a61fb00-abc3-11ea-9362-353c8063f15e.png)

kubectl operations and any HTTP access are unavailable, even SSH couldn't connect. Restarted the VMs, then immediately hem uninstall-ed Rancher. Since then the cluster is finally stable, I could move back some of the workloads just for testing purposes. I really hope the update will fix it for good. 

The sad thing is that in cluster monitoring was unusable completely meanwhile the incidents (also after it only showed empty graph data, maybe it couldn't write to disk with the high IO), and no comms with the VM in-out made the debug harder depending only on external monitoring. I'm happy that I could at least restart the VMs to remediate it for some time, restarting the hardware could cause more pain.

**Comment by brandond** [comment]
@immanuelfodor interesting data. What kind of server is this that a workload running near 100% utilization can cause thermal shutdown? Better hope you don't ever have a real workload max out your system!

**Comment by immanuelfodor** [comment]
Hmm, there was no shutdown to the hardware, just thermal throttling, I shut the 3 VMs down periodically to remediate the heavy CPU/NVMe IO load until I found what causes it. This is a Supermicro X11SCH-LN4F board with a Xeon E-2278G unit, so no harm was done besides a headache after the wake up call, and the time wasted on the workload migration until the problematic deployment was found. This was the first real-life stress test of the hardware since purchase I must say, and as you mentioned cooling, it is weird that the mobo turned DOWN both CPU fan's speed during all the incidents, e.g., yesterday:

![image](https://user-images.githubusercontent.com/21174107/84363839-92eff200-abcf-11ea-987b-285f4fb66282.png)

I put them to constant high speed and also ordered an NVMe heat sink this morning.

**Comment by dwene** [comment]
Updating to 2.4.4 seemed to fixed the problem for me.

**Comment by immanuelfodor** [comment]
Also updated to 2.4.4 a few minutes ago, we'll see what will happen.

**Comment by immanuelfodor** [comment]
Running fine since the update, no sign of the read to death effect 🎉

**Comment by dwene** [comment]
@immanuelfodor Glad to hear it! I'm going to close this ticket then, seems like the issue is resolved.
