### ISSUE TITLE
Allow admins to upgrade Rancher version using UI

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#27076]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Description**
Allow global administrators the option to upgrade the Rancher version using the user interface, similar to the current mechanism of running a helm upgrade from the CLI. Ok if this option is only available to HA/helm based installations and not single node docker installs.

gz#10097

**Comment by vincent99** [comment]
This will work in the explorer UI if you add the repo and had previously installed it with Helm 3.  (Because it is very literally running Helm CLI for you)

But I'm not super convinced it's a good idea to tell people about it.   It's going to drop all the connections for the UI they're looking at for a while in the best case.  And if anything goes wrong there will be no obvious indication or clear path to resolution.
