### ISSUE TITLE
[Backport 2.2] Add 'cert-manager.io/issuer-kind: Issuer' to ingress.yaml in Rancher chart to mitigate https://github.com/jetstack/cert-manager/issues/2533 

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27086]
related to: https://github.com/rancher/rancher/issues/26505

**Comment by rancher-max** [comment]
#### Validated in v2.2.12-rc1

Following the same steps as noted here: https://github.com/rancher/rancher/issues/26505#issuecomment-629467217

**Result:**
Certificate is valid, signed by Let's Encrypt:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/55997940/82093954-fc541200-96b0-11ea-87bb-8ba49b18a547.png">

**However, the local cluster comes up showing 0 nodes, and cattle-agent and node-agent are not deployed. Reopening due to this.**

I see this error in logs: `Referenced "ClusterIssuer" not found: clusterissuer.cert-manager.io "rancher" not found`

**Comment by rawmind0** [comment]
@rancher-max , what is the k8s version where you did the test?? The error you mention sounds like you are using newer k8s version than supported by rancher 2.2.x , 1.15.x

**Comment by rancher-max** [comment]
That's correct! I was using a newer rke version which defaults to kubernetes version 1.17. When switching back to rke version v0.2.10 (which defaults to k8s 1.15) this worked correctly. My mistake.
