### ISSUE TITLE
Container Linking and Networking Issues

### ISSUE THREAD

**Issue by Prodian0013** [rancher/rancher#2708]
I have 2 containers which are linked.  Container A uses a configuration which requires the hostname  of container B (ie: tcp://containerB:8888).  Using native docker this workings by using the hostname attribute.

Ive used the same docker images and docker compose that work in native docker but Container A is unable to reach container B when using the stacks feature in rancher.  I have noticed the hosts file does not show the hostname of the linked container.

Furthermore, container B is unable to reach external services returning an UnknownHost exception.

**Comment by deniseschannon** [comment]
Did you use the `io.rancher.container.hostname_override: container_name` label if you need to the hostname of containerB to be the container name? Rancher will use the UUID as the hostname. 

http://docs.rancher.com/rancher/labels/

For external services, you need to make sure they are activated before pinging. 

Also, in the next release, you won't need the services linked (unless they are in a different stack) in order to be able to ping using the alias. #2628

**Comment by Prodian0013** [comment]
I added the label but this didnt fix the issue.

I changed the network to bridge for both containers and this resolved the issue.

**Comment by Prodian0013** [comment]
Yeah it was managed befire trying bridged.  Swichted it back to managed and I was able to ping using the container name.  Still getting a connection refused error to the tcp endpoint.

**Comment by Prodian0013** [comment]
Success!  It was a configuration issue with one of the containers.  Setting it to tcp://0.0.0.0:8888 fixed it now the data is routed properly using the containers hostname.
