### ISSUE TITLE
RKE Template private registry url, user and password overrides do not work

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#27166]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create an RKE Template with Private Registry enabled and a default url, user and password, all set to user over-rideable.
2. Create a custom cluster using the RKE template and specify overrides for the url, user and password.
3. Perform `kubectl get clusters <cluster-id> -o yaml` against the Rancher server and observe that spec.answer.values.rancherKubernetesEngineConfig.privateRegistries[0].password, spec.answer.values.rancherKubernetesEngineConfig.privateRegistries[0].url and spec.answer.values.rancherKubernetesEngineConfig.privateRegistries[0].user are all set to the RKE template default, not the user overrides.

**Environment information**
- Reproduced in Rancher v2.4.3, user reported in Rancher v2.3.7

gz#10101

gz#12537

SURE-2029
SURE-2463
SURE-3259

**Comment by oxr463** [comment]
Also occuring in 2.4.5 and 2.4.9 as well.

**Comment by andreivnst** [comment]
Hello,

Also occuring in 2.5.3.

**Comment by codyrancher** [comment]
After diving into this issue I actually think it's a two part problem but related to the same thing.

The front-end wasn't sending answers to the backend because it wasn't handling the bracket notation properly `array[0]`. And I've put together a PR to address this issue.

Unfortunately the cluster instance is showing the answer properly set but still shows `spec.answer.values.rancherKubernetesEngineConfig.privateRegistries[0].url` being the default value that's set in the question. This makes me think that the backend is also having problems with handling the bracket notation. I'm asking around to try and find out if I'm correct about this portion.

**Comment by Jono-SUSE-Rancher** [comment]
This is currently scheduled for 2.6.2 but I just wanted to highlight Cody's comments for @superseb or whoever is going to grab this from the backend. It looks like we'll need both FE/BE on it.

**Comment by slickwarren** [comment]
This is reproducible on 2.6-head (931a0f0):
* Create an RKE Template with Private Registry enabled and a default url, user and password, all set to user over-rideable.
* Create a custom cluster using the RKE template and specify overrides for the url, user and password.
* the run command still has the default URL for the registry
* Perform kubectl get clusters <cluster-id> -o yaml against the Rancher server and observe that 
   * spec.answer.values.rancherKubernetesEngineConfig.privateRegistries[0].password, 
   *  spec.answer.values.rancherKubernetesEngineConfig.privateRegistries[0].url and 
   *  spec.answer.values.rancherKubernetesEngineConfig.privateRegistries[0].user are all set to the RKE template default, not the user overrides.

**Comment by jiaqiluo** [comment]
### Root cause
The key for registry-related questions contains an index, such as [0], because the data type of the field is a list of PrivateRegistry, but the backend does not handle the bracket notation properly when processing those new values.

### What was fixed, or what changes have occurred
 When a registry-related question is detected, generate a list of PrivateRegistry based on the index value and set it to the correct position in the Cluster object.

### Areas or cases that should be tested

- provision a cluster using a cluster template that enables the options for private registry
	- the cluster template has default values 
	- the cluster template does not have default values 
	- when creating the cluster, overwrite the default values 
	- when creating the cluster, do not overwrite the default values 
- provision a cluster using a cluster template that does not enable the options for private registry


### What areas could experience regressions?
provisioning clusters by using cluster templates that enable the options for private registry

### Are the repro steps accurate/minimal?
yes

### Note
need [the UI fix](https://github.com/rancher/dashboard/issues/3940) to allow QA to validate the backend fix in UI

**Comment by slickwarren** [comment]
tested using rancher v2.6.4-rc2 as a standard user:
* use a template with overrides enabled for private registry, and default values for password, user, and registry values -- pass
* use a template with overrides enabled for private registry, and override values for password, user, and registry values -- pass
* disabling override in future versions of a template -- pass
* use a template with overrides enabled for private registry, but no default values -- pass
* use a template with overrides disabled for private registry -- pass
