### ISSUE TITLE
Node did't add in cluster: " Waiting to register with Kubernetes"

### ISSUE THREAD

**Issue by SlastikhinNikita** [rancher/rancher#27234]
**What kind of request is this (question/bug/enhancement/feature request):**

Just install rancher 2.4.3 on clean OS (Alpine 3.11). 

And when I try to add node in new cluster with command (Node with same OS):

```
docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.3 --server https://r.ioi.pp.ua --token 5rs****d --ca-checksum 0***3 --node-name node1 --etcd --controlplane --worker
```

**Result:**

So I got an error in Rancher:
```
[controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node node1: "node1" not found]]
```

In Nodes page got status: ```Waiting to register with Kubernetes```
If open node monitor page "Kubelet" is red. 

more info:
```
kuber:~# docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
79d630a7f55e        rancher/hyperkube:v1.17.5-rancher1    "/opt/rke-tools/entr…"   2 minutes ago       Up 2 minutes                            kube-scheduler
2c1f24b4ed9a        rancher/hyperkube:v1.17.5-rancher1    "/opt/rke-tools/entr…"   2 minutes ago       Up 2 minutes                            kube-controller-manager
1e415625b4c3        rancher/hyperkube:v1.17.5-rancher1    "/opt/rke-tools/entr…"   2 minutes ago       Up 2 minutes                            kube-apiserver
0681263dcc75        rancher/coreos-etcd:v3.4.3-rancher1   "/usr/local/bin/etcd…"   3 minutes ago       Up 3 minutes                            etcd
f0a43eb3826e        rancher/rancher-agent:v2.4.3          "run.sh --server htt…"   3 minutes ago       Up 3 minutes                            inspiring_liskov
```

In Alpine setup only docker. Maybe need some another package?

**Comment by pauljolsen** [comment]
I saw this too using Kubernetes version v1.15.4-rancher1-2.
It disappeared with version v1.15.11-rancher1-2.
Docker version 18.09.4, build d14af54266 in both cases.
Rancher 2.4.3

**Comment by BalajiTechs** [comment]
I am facing same problem. Here is what i did.
* Created 4 new VMs(One for server and 3 worker nodes)
* Followed below steps to setup rancher server on one of the VM. 
https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/
* Created cluster using same setup instructions. Ran command on all of the three nodes as per instructions
* After some time cluster provisioning is stuck and i see mutliple errors in the rancher UI and one of them is below
`Failed to upgrade Control Plane: [[[controlplane] Error getting node rancher-n2: "rancher-n2" not found]]`

![image](https://user-images.githubusercontent.com/10494133/83351706-f8d4b200-a363-11ea-8b0a-86eac2fdd9b3.png)


Can somebody guide how to fix this? I am struggling since three day on this.

**Comment by tamasgal** [comment]
I have the same issue. @BalajiTechs how did you fix that?

Or is there any update on this?

**Comment by SlastikhinNikita** [comment]
unfortunately no, didn't fix it
So, I was uninstall Rancher and delete Alpine
As I see... Rancher was work fine on ubuntu only

Now I am using Docker Swarm and Portainer.

**Comment by dbsanfte** [comment]
I encountered this error today while spinning up an Azure cluster (raw VMs) with the Azure cloud provider enabled.

In my case, I had mismatched my resource group names in my node templates and my cluster's cloud-provider config. 

Fixing the resource group names to match resolved the issue.

**Comment by behnm** [comment]
I have this issue too. 
How can I solve the problem ???

**Comment by gitwittidbit** [comment]
Is there a fix for this yet?

I am having the same issue.
