### ISSUE TITLE
Monitoring - Upgrading k8s version causes the metrics API Server Request Rate missing

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27267]
This is found during validating this issue: https://github.com/rancher/rancher/issues/26985#issuecomment-634315808

how to reproduce:
- run rancher `v2.4-head` or `master-head`
- edit the system chart to point to branch `dev-v2.5`
- provision a cluster with k8s `1.16`
- enable the cluster monitoring `0.1.1`
- upgrade the k8s version to `1.17` or `1.18`

results:
- we expected to see the metric `API Server Request Rate` under the `Kubernetes Components Metrics` section but it is gone along with some others 

here is the reason for the above behavior:

We added a new logic in the monitoring chart `0.1.1` to use different sets of APIs for different k8s versions, which is calculated and applied at the time of enabling the cluster monitoring.

Upgrading the k8s version of a cluster does NOT cause apps to be re-deployed.

So, if we enable monitoring in the k8s `1.16` cluster and then upgrade the k8s to `1.17` or `1.18`, the monitoring apps will still try fetching data from deprecated APIs, which of course will NOT work.

The workaround is to disable and re-enable the cluster monitoring.

Since we support multiple k8s version in one release, for example, 1.16, 1,17, and 1.18, there should be no need to re-install the monitoring if we just upgrade the k8s version of a cluster.

**Comment by StrongMonkey** [comment]
@maggieliu @deniseschannon 

This issue is due to the fact that we don't automatically redeploy system charts when user upgrades k8s cluster. This behaviour is normal and doesn't need to be changed. But in our monitoring chart we detect k8s version to decide if it should apply specific manifests, which is broken in upgrade case. Th e workaround will be redeploying monitoring charts(doesn't have to disabled and re-enable). I would suggest that as a manual workaround to fix rather than putting the fix into rancher since it is too hacky to deal with that.

**Comment by jiaqiluo** [comment]
This issue is closed since we have a workaround.
