### ISSUE TITLE
Project Resource Quotas are not Propagated when edited

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#27308]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

To recreate this I tested it by creating a Project and Default Namespace Limit of 8000 and 1000 respectively by editing the Project and saving

I then changed the Default Namespace Limit to be 500 and tried to save to no avail

**Result:**

The only solution seems to be to remove the quotas, save and then reapply the updated ones

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): k3s/hosted for me - not for customer - behaviour seems cluster/provider independent

gz#10358

**Comment by ryansann** [comment]
I have investigated this issue and found that in order to allow updates to existing project level quotas to propagate to namespaces, the resource quota controllers will need enhancement. In order to distinguish between an update to a project level default value and an override of a namespace value, the controller needs more information about the state of the quotas.

Let's look at an example to see why this is a problem for accomplishing propagation to namespaces on update. 

Inside the controller, we know the current default value and the current namespace value. So, say an update was made and the controller is reconciling the new value. Inside the controller we have this information:
```
existing = {
    limits.cpu: "500m"
}

default = {
    limits.cpu: "650m"
}
```
Then the controller needs to decide which of these values to apply for the new namespace value. Well, there are two possible situations that could have led to this state. 
1. There was an existing default value for CPU Limit set to `500m` and the default was updated to `650m`
2. The namespace value was overridden to `500m` and the default was not changed

In case 1, we would want to apply the new default with a result of:
```
result = {
    limits.cpu: "650m"
}
```

In case 2, we would want to apply the overridden value with a result of:
```
result = {
    limits.cpu: "500m"
}
```

Since the same internal state of the controller can be reached through two different actions, there is not enough information to decide how to correctly reconcile the new namespace value. This ambiguity implies that the controller does not have enough information to make this decision correctly, and that enhancements are needed to achieve the desired functionality. A viable enhancement would be to track which quotas are overridden at the namespace level.

In the meantime, I have updated documentation around resource quotas to more accurately capture some of the nuances with behavior.

Also as mentioned in the initial report, you can delete and recreate quotas in order to workaround this issue.

**Comment by SheilaghM** [comment]
https://jira.suse.com/browse/SURE-2095
Feature request

**Comment by MKlimuszka** [comment]
this behavior is intentional
