### ISSUE TITLE
Errors seen during azure cluster creation when using ubuntu custom images in the node template

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#27316]
Version: v2.4-head, v2.4.3, master-head

Steps:
1. Create a azure node template using custom image with Ubuntu OS, managed disk option specified. 
2. Create a cluster using this node template
Cluster creation fails with the error below:
```
Error creating machine: Error running provisioning: Failed to obtain lock: Maximum number of retries (60) exceeded

```

<img width="1303" alt="Screen Shot 2020-05-27 at 3 31 13 PM" src="https://user-images.githubusercontent.com/18536626/83193097-57432b80-a0eb-11ea-97fc-5d38342169b2.png">

When there is a retry to create the VM again, we run into the issue that the OS disk already exists in the resource group. 

```
Error with pre-create check: "OS Disk with name soumyafinimagetest1 already exists in resource group "
```

<img width="1263" alt="Screen Shot 2020-05-27 at 3 42 51 PM" src="https://user-images.githubusercontent.com/18536626/83193167-6fb34600-a0eb-11ea-8c73-f1982c095bef.png">

The OS disk is not cleaned up before we begin retrying again.

**Comment by aiyengar2** [comment]
Re: `OS Disk with name soumyafinimagetest1 already exists in resource group`

I drafted [a commit](https://github.com/aiyengar2/machine/commit/351a42ad0f052ed72ccace697f961fedecabf817) to revert a change made as part of https://github.com/rancher/machine/pull/72 to fail on PreCreateCheck if the OS disk already exists. This was initially added to ensure that we fail early-on if a disk with the same name already exists.

However, it appears this also unintentionally prevents a VM from attaching itself to a previously created OS Disk that is configured correctly (i.e. one that was left over from a previously failed provisioning process if it is a managed disk).

By removing this, provisioning will still fail on create if a machine tries to attach itself to a managed disk whose settings differ from those listed in [`getOSDisk`](https://github.com/rancher/machine/blob/2fbd7ec65dea41983a8222141df4ce58df7eaeac/drivers/azure/azureutil/azureutil.go#L633-L656) with the appropriate Azure error.

Alternatively, this issue could also be solved by adding in the ability to delete managed disks automatically (unchanged since [this commit](https://github.com/rancher/machine/commit/875f6c344774021b8c93d9443231b36fb2141a6c)). This is probably a feature that should be incorporated at some point (as we require manual cleanup of managed disks at the moment), but currently requires parsing through all managed disks owned by a user to find the one that is managed by their VM according to the [Azure docs](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/find-unattached-disks).




Based on the [Azure docs](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/find-unattached-disks), deleting managed disks would require iterating through the managed disks in a user's account and deleting the one which is managed by the virtual machine.

**Comment by aiyengar2** [comment]
Re: `Error creating machine: Error running provisioning: Failed to obtain lock: Maximum number of retries (60) exceeded`

This error is unrelated to the Managed Disks error and seems to have to do with provisioning for Ubuntu images. The error specifically happens when running [`sudo apt-get update`](https://github.com/rancher/machine/blob/2fbd7ec65dea41983a8222141df4ce58df7eaeac/libmachine/provision/utils.go#L299) on the machine to try to [get a lock on apt-get](https://github.com/rancher/machine/blob/2fbd7ec65dea41983a8222141df4ce58df7eaeac/libmachine/provision/ubuntu_systemd.go#L74) while trying to [install packages](https://github.com/rancher/machine/blob/2fbd7ec65dea41983a8222141df4ce58df7eaeac/libmachine/provision/ubuntu_systemd.go#L118) required before installing docker (i.e. `curl` for systemd provisioning) during the [provisioning process](https://github.com/rancher/machine/blob/2fbd7ec65dea41983a8222141df4ce58df7eaeac/libmachine/libmachine.go#L171-L173) for an Ubuntu systemd host.

I SSHed into one of the machines that was stalling during the Provisioning process and found the following:
```
docker-user@arvind-test2:~$ ps aux | grep "lock"
root         34  0.0  0.0      0     0 ?        I<   20:56   0:00 [kblockd]
root       3582  0.0  0.0   4624  1796 ?        S    20:57   0:00 /bin/sh /usr/lib/apt/apt.systemd.daily lock_is_held install
docker-+   9922  0.0  0.0  14852  1136 pts/0    S+   20:59   0:00 grep --color=auto lock
```

According to https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image, `/bin/sh /usr/lib/apt/apt.systemd.daily lock_is_held install` is related to an apt-daily.service run on Ubuntu Cloud images, which “performs various APT-related tasks like refreshing the list of available packages, performing unattended upgrades if needed, etc.” This service that is running on the background locks up the ability to perform an `apt-get update`, which results in the provisioning error we see where we `Failed to obtain lock`.

Although the probability that we run into this issue is seemingly random (i.e. provisioning sometimes succeeds and sometimes fails for the custom image), it seems like this error might be more likely with older Ubuntu images which haven't updated their packages recently, which is likely why we did not see this while testing https://github.com/rancher/rancher/issues/23010 (since the image was brand new at the time).

To mitigate this on provisioning, we could introduce a waiting mechanism such as `systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true` (which only works on Ubuntu 18.04 and up; not sure how to accomplish a similar result in older versions of Ubuntu) to ensure that we wait for that process to complete before trying to obtain a lock in the provisioning process.

**Comment by aiyengar2** [comment]
Re: https://github.com/rancher/rancher/issues/27316#issuecomment-635635229

It seems like just reverting a change in https://github.com/rancher/machine/pull/72 is not sufficient as I got the following error while trying to re-provision:
```
2020/05/28 16:31:10 [ERROR] NodeController c-lmsh8/m-4fnw5 [node-controller] failed with : Error creating machine: Error in driver during machine creation: Code="ConflictingUserInput" Message="Disk arvind-test-image-custom1-os-disk already exists in resource group ARVIND-TEST. Only CreateOption.Attach is supported.  Target: '/subscriptions/14a619f7-a887-4635-8647-d8f46f92eaac/resourceGroups/ARVIND-TEST/providers/Microsoft.Compute/disks/arvind-test-image-custom1-os-disk'."
```

Currently we use [`CreateOption.DiskCreateOptionTypesFromImage`](https://github.com/rancher/machine/blob/2fbd7ec65dea41983a8222141df4ce58df7eaeac/drivers/azure/azureutil/azureutil.go#L638) instead, which creates the OS Disk from the imageReference provided. Switching to `CreateOption.Attach` would not be preferable as we could be attaching our node to a disk which was made off of a previous imageReference not reflected in the latest node template.

To resolve this, I updated https://github.com/rancher/machine/pull/85 to support deleting the unused managed disks automatically (via checking if they are managed by any VM, similar to how this is done in the [Azure docs](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/find-unattached-disks)). Tested this out locally and it seems to work as expected.

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/27316#issuecomment-635644153 will be addressed separately in https://github.com/rancher/rancher/issues/27353

**Comment by soumyalj** [comment]
Tested with v2.4-head(afdea9956)
Steps:
1. Create a azure node template using custom image with Ubuntu OS, managed disk option specified.
2. Create a azure cluster using this node template. 

We see the "Error creating machine: Error running provisioning: Failed to obtain lock: Maximum number of retries (60) exceeded; waiting on node-controller" which will be addressed separately in https://github.com/rancher/rancher/issues/27353

With the fix, when there is a retry to create the VM again, we do not see the issue  "the OS disk already exists in the resource group".  The OS disk is cleaned up before a provisioning retry is initiated. 

It was observed that cluster provisioning succeeds after around a hour if it succeeds to obtain the lock.
