### ISSUE TITLE
Update Grafana to 6.7.4

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27418]
Update grafana for security issue [here](https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/)

**Comment by StrongMonkey** [comment]
The only change made was to update grafana image to 6.7.4. We should verify that there is no regression and monitoring continues to work. Should be available to test in v2.4.5-rc1.

**Comment by jiaqiluo** [comment]
The new image is validated on `v2.4.5-rc1`, freshly installed, with/without enabling the persistent storage for Grafana

Steps:
- run `v2.4.5-rc1` single install 
- add a cluster with k8s `v1.18.3`
- deploy the app `Longhorn`
- enable the cluster monitoring (`v0.1.1`) with/without Enable Persistent Storage for Grafana using Longhorn as the storage class
- run monitoring tests on the cluster

**Comment by jiaqiluo** [comment]
reopen this issue since the upgrade path from the previous version (0.1.0) to this version (v0.1.1) is still broken when persistent storage is enabled. 

It is tracked in this issue https://github.com/rancher/rancher/issues/27450 but is moved out the milestone `v2.4.5`

we cannot release this new version if we don't have a good solution for the upgrade scenario.

**Comment by StrongMonkey** [comment]
Just want to make clear that the only change between 0.1.0 and 0.1.1 regarding to grafana is the image update. The persistent storage issue is caused by the chart itself that we don't enable statefulset in our monitoring chart which does poor support on upgrade scenario. We need to enable statefulset feature in grafana chart to better support this. This issue is not caused by the chart version bump(v0.1.1) and likely exists on previous version.

**Comment by jiaqiluo** [comment]
@StrongMonkey 
We have more changes than just the Grafa image in the v0.1.1 chart, 

this fix for issue https://github.com/rancher/rancher/issues/26969 is also the v0.1.1 chart.

**Comment by jiaqiluo** [comment]
can we have the upgrade strategy fix to the chart `v0.1.1`, so that we can avoid this problem in future upgrades.

**Comment by StrongMonkey** [comment]
@jiaqiluo Upgrade strategy is not the ideal fix. It is better to get statefulset support on grafana chart. https://github.com/helm/charts/commit/b4b137e70fe56b86a45daef2bc2ad06e6e22391a#diff-9f60775633bb510fb9e3b3c20679ac09. I will talk to @maggieliu about it.

**Comment by jiaqiluo** [comment]
@StrongMonkey 
It turns out this is a better workaround:
- scale down the workload `grafana-cluster-monitoring` to 0
- wait for pods to be removed
- scale up back to 1

This way will guarantee that the new pod is using the new images.
If we delete the old pod, then there is a race between creating a pod in the old replicaSet and in the new replicaSet, and my tests show most of the time the old replicaSet wins so a new pod using the old image is running eventually

**Comment by jiaqiluo** [comment]
The new chart is validated on both fresh install and upgrade case. 

We need to mention the workaround for the upgrade scenario in the release note.

**Comment by rancher-max** [comment]
#### Validated in airgap setup using v2.4.5-rc6

- Monitoring v0.1.1 is available to upgrade to and upgrade is successful
- Upgrading monitoring version uses Grafana v6.7.4
- Fresh install has only v0.1.1 available for monitoring and enabling it is successful
- Fresh install of monitoring v0.1.1 uses Grafana v6.7.4
