### ISSUE TITLE
Rancher-logging is not deployed correctly on new cluster creation

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#27659]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Provision a new cluster with the Rancher2 Terraform provider, with logging enabled. It appears that if there is any significant delay to the cluster API becoming available the rancher-logging app fails to install (my testing in a lab with a simple Digital Ocean cluster works, but user environment where the cluster takes longer to spin-up does not).

**Result:**

rancher-logging App fails with an error such as the following, indicating the API server was not available to process the request:

```
AppController p-hvpjn/rancher-logging [helm-controller] failed with : failed to install app rancher-logging. Error: release rancher-logging failed: the server is currently unable to handle the request (post secrets)
```

**Other details that may be helpful:**

As a workaround the customer must take action to upgrade/force redeployment of the app after cluster provisioning.

A similar issue raised in https://github.com/rancher/rancher/issues/27250 and https://github.com/rancher/rancher/issues/26440 appears to have resolved this issue for the cluster-monitoring app, but my reading of the code suggests no such force redeploy occurs automatically for the rancher-logging apps.

**Environment information**
- Rancher v2.4.4

gz#10597

**Comment by izaac** [comment]
Reproduced in Rancher `v2.4.4`

The issue here is when provisioning a new cluster and also enabling cluster logging at the same time, we get into this state from the Rancher server:

Cluster is in provisioning state.
Logging was enabled but there's no cluster to deploy the App to.

![Screen Shot 2020-06-26 at 9 17 23 AM](https://user-images.githubusercontent.com/27659/85883148-61615400-b795-11ea-9e1c-bd65a4eb534c.png)


Eventually failing
`
2020/06/26 16:26:09 [ERROR] AppController p-fwd4k/rancher-logging [helm-controller] failed with : failed to install app rancher-logging. Error: release rancher-logging failed: the server is currently unable to handle the request (post secrets)
`

**Comment by izaac** [comment]
This is also reproducible in Rancher `v2.3.8`
