### ISSUE TITLE
Add rotateEncryption to Rancher API

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#27735]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
- rke currently supports the command `rke encrypt rotate-key` but the Rancher API doesn't have an option to rotate the rke encryption key. The current process is to disable encryption, waiting for the task to be completed. Then re-enable encryption with a new key.

**Result:**
- We need to add https://RancherURL/v3/clusters/c-abcde?action=rotateEncryption or something like that to the API to make the process easier and safer.
- During testing we saw that sometimes the same key would be get re-used when re-enabling encryption.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

gz#10865

**Comment by superseb** [comment]
To make this work we need to:

* Add the necessary fields to the cluster object, so that Rancher can use that to rotate the encryption key (similar to RotateCertificates), but without input fields. (rotating using custom config is not supported). This is based on that we need to modify the cluster object with a field before calling `Update`.
* Add an action here https://github.com/rancher/rancher/tree/master/pkg/api/norman/customization/cluster which can be used to rotate the encryption key, which will configure the cluster object with the field for rotate-encryption-key and set it to true, and call `Update`.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b0` and master-head - commit id: `4297ee10`**

- Enable secret encryption on the cluster
- Secrets are encrypted with a key
- API has rotateEncryptionKey option. And UI has the option to rotate.
- The keys are rotated
- Secrets are encrypted with the new key.
