### ISSUE TITLE
Longhorn - the namespace is stuck in removing state if delete the project directly 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27758]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.4.5 single install
- provision a cluster
- in the cluster, create a project `p1`
- in the project, create a namespace `longhorn-system` 
- deploy the Longhorn app from the built-in library `v1.0.0`
- wait for the app to be deployed
- delete the project 

**Result:**
- the namespace `longhorn-system` is stuck in `removing` state forever 

![image](https://user-images.githubusercontent.com/6218999/85907071-270fab00-b7c5-11ea-9cd5-32c6aa0d343b.png)

**Other details that may be helpful:**
- this does not happen to other apps in the catalog

**Comment by yasker** [comment]
You need to use app->uninstall instead of deleting the project/namespace directly. Longhorn has used finalizers to clean up the resources.

Because the resources cannot be cleaned up properly due to finalizers wasn't removed. See https://longhorn.io/docs/1.0.0/deploy/uninstall/

See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers as well.

**Comment by jiaqiluo** [comment]
closed since this is not a real issue.
