### ISSUE TITLE
Rancher v2.4.5 UI display name for nodes incorrect when nodes in a single cluster have FQDN hostnames under multiple different subdomains

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#27873]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug (unable to reproduce)

**Steps to reproduce (least amount of steps as possible):**

The user's hostname configuration which is encountering the issue is in the customer-facing ticket, leaving out here for data privacy reasons.

In the issue seen in their environment, the display name of nodes in the Rancher UI for two clusters, which have mixed subdomains for their nodes hostnames, e.g. kube01.prep.qdsp.axe.al and kube02.train.qdsp.axe.al, are displaying incorrectly. The etcd/controlplane nodes in the same subdomain show the expected display name (e.g. kube02). The worker nodes show the TLD suffix only for all nodes (e.g. .al). The issue occurred after upgrade from Rancher v2.4.3. The UI display name for nodes is the only place this is shown incorrectly. Clusters where all nodes are under the same subdomain display correctly.

I attempted to reproduce with a v2.4.5 provisioned custom cluster, with nodes with the following `--node-name` overrides, but could not successfully reproduce:

kmaster01.int.qdsp.axe.al controlplane/etcd
kmaster02.int.qdsp.axe.al controlplane/etcd
kube01.prep.qdsp.axe.al worker
kube02.train.qdsp.axe.al worker

**Environment information**
- Rancher v2.4.5

gz#11056

gz#11664

**Comment by splattner** [comment]
I think the example here is not fully correct and I  it might help to reproduce it with the following list of nodes:

kmaster01.prep.qdsp.axe.al controlplane/etcd
kmaster02.prep.qdsp.axe.al controlplane/etcd
kube01.prep.qdsp.axe.al worker
kube02.prep.qdsp.axe.al worker
kube03.prep.qdsp.axe.al worker
kube01.int.qdsp.axe.al worker
kube02.int.qdsp.axe.al worker
kube01.dev.qdsp.axe.al worker
kube02.dev.qdsp.axe.al worker


so there are multiple host with the same hostname (`kube01`) but with different domain part `prep.qdsp.axe.al` or `int.qdsp.axe.al` )

on our cluster only `kmaster01.prep.qdsp.axe.al` / `kmaster02.prep.qdsp.axe.al`  has the correct hostname in the WebGui. The other ones only show `ch` part. But then again `kube03.prep.qdsp.axe.al` shows the correct name again, I guess because there is no other kube03 on the other environments.


related changes between 2.4.3 and 2.4.5 are probably here:
* https://github.com/rancher/ui/commit/5a8ea608bb22d5d8549ae84bd043fe300086573d
* https://github.com/rancher/ui/commit/89ff5242c038172f0a8d993766c7a92fd62c9311

**Comment by axeal** [comment]
@splattner Thanks for the hint, with your suggested hostnames I was able to reproduce the issue.

**Comment by slickwarren** [comment]
I was able to reproduce this on rancher v2.5.5 by doing the following: 
* bring up a 4 node custom cluster, using rancher's `advanced options` to give node names for the following:
  * etcd -> kmaster01.prep.qdsp.axe.al 
  * controlplane -> kmaster02.prep.qdsp.axe.al 
  * worker -> kube01.prep.qdsp.axe.al worker
  * kube01.int.qdsp.axe.al worker
* worker with `int` in name came up with the correct shortened name `kube01`, while `prep` node came up with the end DNS line `al`

**Comment by slickwarren** [comment]
tested on 2.5-head (dba332111aacdba283baabdc6501d5c42079a3e4) and master-head (98fe72a40efb771428cd3eac0096db4ac0b5cdae) and appears to be fixed

* bring up a 4 node custom cluster, using rancher's advanced options to give node names for the following:
  * etcd -> kmaster01.prep.qdsp.axe.al
  * controlplane -> kmaster02.prep.qdsp.axe.al
  * worker -> kube01.prep.qdsp.axe.al 
  * worker -> kube01.int.qdsp.axe.al 
<img width="415" alt="Screen Shot 2021-02-12 at 11 58 13 AM" src="https://user-images.githubusercontent.com/16691014/107819009-50b61c00-6d2d-11eb-8600-e382f994ffea.png">
