### ISSUE TITLE
Issues with Deletion of Convoy stacks.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2788]
Server version - V0.47.0-rc1

Server version - v0.47.0-rc1

Deployed "Gluster FS" and "Convoy Gluster” stacks with 2 hosts in my setup as part of convoy storage pool.

Deployed few services using convoy storage pool.

Deleted "Convoy Gluster” stacks.

Deletion of stack succeeded.

Since we have services that are using this storage pool , should we restrict the deletion of stack? Or provide some warning to user ,when deletion is attempted.

Should deletetion of "Convoy Gluster” stacks also result in associated Storage pool deletion ? Currently there is no way to delete a storage pool.

**Comment by cjellick** [comment]
Chatted with @vincent99 about this. Since this stack is "just a normal stack" as far as cattle is concerned, we don't think it makes sense to have special one-off validation logic to prevent deletion.

But maybe we could implement the protect/unprotect featrue and utilize it for the convoy-nfs service. See: https://github.com/rancher/rancher/issues/2383

@will-chan @ibuildthecloud opinions?

**Comment by cjellick** [comment]
Could potentially be addressed as part of #2918

**Comment by cjellick** [comment]
I _think_ @ibuildthecloud is addressing this as part of volume refactor. Assigning over.

**Comment by Chris7** [comment]
Is there any work around to this issue atm?

**Comment by will-chan** [comment]
Obsolete
