### ISSUE TITLE
Rancher EC2 support custom KMS encryption key

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27965]
UI field needed for this issue: https://github.com/rancher/rancher/issues/27015

**Comment by sowmyav27** [comment]
Blocked on 2.4-head by this issue -- https://github.com/rancher/rancher/issues/28112
On `master-head` 
- Create an AWS node template --> Instance config page --> Enable Encryption
- Dropdown for the KMS keys are displayed. But it is missing the heading `KMS Key` (which is available in an EKS cluster creation) reopening the issue
<img width="1016" alt="Screen Shot 2020-07-28 at 11 30 52 AM" src="https://user-images.githubusercontent.com/26032343/88707228-d1316a00-d0c6-11ea-95a5-b1bcd6fd9b4f.png">

**Comment by sowmyav27** [comment]
Blocked on 2.4-head commit id: `6708cf9f1` because of issue -- https://github.com/rancher/rancher/issues/28141

- On 2.4-head dropdown is empty. User is able to enter a value and save
- Deploy a cluster using this node template.
- Cluster is created successfully. The volume associated with the node has `Encrypted` set. and the KMS key.

**On master-head - commit id: `6d6199121`**
- Create a node template . select `Encrypt EBS Volume` as True. Select a KMS key from the dropdown. Save the node template
- Create a cluster using this node template
- CLuster is created successfully. The volume associated with the node has `Encrypted` set. and the KMS key.
- Create a node template . select `Encrypt EBS Volume` as False. Save the node template
- Create a cluster using this node template. The volumes on the nodes have Encryption - disabled.

**Comment by sowmyav27** [comment]
**Verified on 2.4-head commit id: `0a219c19e` ui tag: `latest-2.4`**

- Create a node template . select Encrypt EBS Volume as True. Select a KMS key from the dropdown. Save the node template
- Create a cluster using this node template
- Cluster is created successfully. The volume associated with the node has Encrypted set. and the KMS key.
- Create a node template . select Encrypt EBS Volume as False. Save the node template
- Create a cluster using this node template. The volumes on the nodes have Encryption - disabled.
