### ISSUE TITLE
Cluster is stuck in Provisioning state on an upgrade from 2.4.5 and CIS scan fails to run on an upgraded setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28014]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create two clusters on 2.4.5 - custom clusters - 1 node - all roles.
- enable scheduled CIS scan on both the clusters.
- Upgrade to 2.4-head - commit id: `b7ab53e95`
- On of the clusters is stuck in `Provisioning` state with error `Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (Forbidden): {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-287v4\" is forbidden: User \"u-gkaezv3cht\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""}`
- On the other cluster, which is `Active` run cis scan manually.
- Error seen in rancher logs

```
[tiller] 2020/07/21 19:51:15 failed to prepare update: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-fgxrs\" is forbidden: User \"u-b62nmwgw5n\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get configmaps)
UPGRADE FAILED
```

**Note:**
- This is just one upgrade setup where this issue is seen, did 3 or 4 more upgrades from 2.4.5 to 2.4-head -- this issue is NOT seen and CIS scan continues to work in those setups.
- This is not always reproducible

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5 to 2.4-head commit id: `b7ab53e95`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom clusters
- Kubernetes version (use `kubectl version`):

```
1.18.6
```

**Comment by sowmyav27** [comment]
**Faced this issue again on an upgrade from 2.4.5 to 2.4-head - commit id: `a01d0e5f5`**

- Deploy a cluster - custom cluster - 3 nodes all roles.
- Create few users and assign roles (user1 with cloned project owner role, user2 cloned cluster owner role for the custom cluster)
- Upgrade to 2.4-head.
- cluster is seen in provisioning with error : 
```
Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (Forbidden): {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-ftdqt\" is forbidden: User \"u-iilfcyjlak\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""}
```

**Comment by prachidamle** [comment]
Looking at the error message and the steps above that say:
1. Create few users and assign roles (user1 with cloned project owner role, user2 cloned cluster owner role for the custom cluster)

This error seems related to cluster or project owner rbac, does not seem to be CIS related. When a CIS scan is invoked, the user needs to have "cluster-admin" rights to run the scan, possibly this rbac check is having some problem.

**Comment by mrajashree** [comment]
1. We create a system account user for each cluster. And this user gets the role of "cluster-owner" through a clusterrolebinding
2. An upgrade from 2.4.5 to 2.4-head now includes the changes made to roletemplates of "cluster-owner" and "project-owner" to add "own" verb.
3. RoleTemplate controller should reconcile first to include the new verb. However the clusterroletemplatebinding controller reconciled first to check whether the system account's role is a cluster-owner or not. Since it didn't have the updated "own" verb at the time, it assumes this role isn't an owner and deletes the clusterrolebinding for system account. And roletemplates reconcile later
4. This happens for each cluster but not all get stuck in Provisioning.

A sure of way of testing the fix is
1. Create clusters in 2.4.5
2. Find the system account users for each cluster
3. Find the clusterrolebinding for this user binding it to role `c-xxxx-clusterowner`. Note the name of this crb
4. Upgrade to 2.4-head. All crbs for cluster-owners should be intact

**Comment by sowmyav27** [comment]
**Validated using 2.4-head commit id- `54a466511` and master-head - commit id: ``**

- Create 3 clusters on 2.4.5 - custom clusters - 1 node - all roles and 3 nodes all roles
- Note the clusterrolebindings for the 3 clusters

```
To find userID of system account of your cluster:
- kubectl get users -o yaml | grep -A20 "System account for Cluster c-xxxx"
To find crbs for that userID
- kubectl get clusterrolebindings -n c-xxxx -o yaml | grep -B15 u-xxxxxxxx
select name of crb, that has role c-xxxx-clusterowner
```

- Upgrade to 2.4-head/master-head
- Cluster are seen in `Active` state.
- Verified all the clusterrolebindings were available
- Verified CIS scan works fine
- Verified Project monitoring was enabled by a user having role cloned from project owner. (on master-head verb "own" is not seen existing issue)
