### ISSUE TITLE
[RFE] - Feature Request : Add support for Linkerd

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#28105]
[Linkerd](https://linkerd.io/) is an amazing alternative to [Istio](https://istio.io/). It would be good to have native integration in Rancher just like what we have for Istio.

**Comment by akin-ozer** [comment]
As end user for both projects for some time, my thoughts on some integration points would be:

- Multi-cluster: This was added to linkerd with 2.8, rancher is also multi-cluster management platform so I think configure, install or enable east-west traffic between clusters on rancher UI and API would be interesting, especially enabling when creating new clusters. [Linkerd multi-cluster capabilities](https://linkerd.io/2/features/multicluster/)

- Adding apps to mesh: Since rancher has projects which contains namespaces and distributes secrets between them, I think we could activate mesh on specific projects. So when we create new namespaces in the project, we automatically inject all apps inside it. Also deploying a single app in UI could have "add to mesh" tick so if we don't want to enable mesh for whole cluster, we can still do that without dealing with CLI or complicated ways. [Linkerd service injection](https://linkerd.io/2/tasks/adding-your-service/)

- Rotation of certs: We can automatically rotate certs easily with both rancher and linkerd. It's not much but doing both in same place would be meaningful. [Linkerd cerrs rotation](https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/)

- Network metrics for apps in Rancher UI: Linkerd creates network metrics for meshed apps and also can catch error rates, latency etc. Linkerd already have metrics exporter so when we enable monitoring for cluster in Rancher we can also see our network metrics in grafana aswell. [Linkerd metrics export](https://linkerd.io/2/tasks/exporting-metrics/)

- Service mesh debug: In Rancher UI we can see application logs for debug purposes. In linkerd there is a way that you can also tap into network traffic and see what is going on. Maybe we could see this also in Rancher UI so we have more areas to cover while debugging for errors. [Linkerd tap](https://linkerd.io/2/tasks/securing-your-service/#validating-mtls-with-linkerd-tap)

- Finally API first design: With rancher, you can do nearly all the things(or all the things?) with API calls and this creates automation opportunities like terraform or http requests for simple things in our platform pipelines. Linkerd also have API first design and integration points could be standardized for future stability. [Linkerd architecture](https://linkerd.io/2/reference/architecture/)


Disclaimer: I'm not associated with both Rancher or linkerd(buoyant) by any means. I'm just big fan of these 2 projects and see real value with this integration. It would also speed up service mesh adoption which Rancher already doing for kubernetes adoption.

**Comment by vikas027** [comment]
@akin-ozer very well written 👍🏻

**Comment by wmorgan** [comment]
From the Linkerd side, would love to see this and we'd be happy to help.

**Comment by Saim-Safdar** [comment]
Linkerd easy to Install, fastest to spun up, give us security, reliability and observability who doesn't need that. Love to see rancher take this direction and Would love to do help in any way.

**Comment by vikas027** [comment]
Ah, Rancher! No love for Linkerd :(

**Comment by wmorgan** [comment]
Just a note for anyone else who comes across this issue: there is nothing special needed to run Linkerd on Rancher (you can just use the [basic installation](https://linkerd.io/2/getting-started)), and there are many happy Linkerd + Rancher users running the two together today. Hop into [the Linkerd Slack](slack.linkerd.io) if you get stuck on anything.
