### ISSUE TITLE
Enabling/Disable ECM feature flag

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28132]
Need the ability to enable/disable ECM chart and uninstall should cleanly delete all CRDS.
Corresponding dashboard issue: https://github.com/rancher/dashboard/issues/844

**Comment by deniseschannon** [comment]
There will be no ECM chart, but I am updating this issue as ability to enable/disable the ECM feature flag.

**Comment by bmdepesa** [comment]
@deniseschannon Currently ECM is enabled by default in the latest build - do we expect to see this feature flag in the UI for ECM and Dashboard so that it can be toggled outside of enabling the feature flag through `docker run` or `helm install`

![Screen Shot 2020-08-10 at 3 43 33 PM](https://user-images.githubusercontent.com/21316915/89838703-ca701180-db20-11ea-89af-779bf9b02aeb.png)
![Screen Shot 2020-08-10 at 3 43 42 PM](https://user-images.githubusercontent.com/21316915/89838705-cba13e80-db20-11ea-9ae2-45ae9c526e90.png)

**Comment by maggieliu** [comment]
Feature flag should be removed now.
