### ISSUE TITLE
When editing a deployment with 0 pods it automatically changes to 1

### ISSUE THREAD

**Issue by saparicio** [rancher/rancher#28168]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Scale down to 0 a deployement.
Edit the deployment.
Move out the focus from the number of pods fields

**Result:**
The number of pods is automatically changed to 1

**Other details that may be helpful:**
This happens since the last update. We moved directly from 2.2.8 (it worked fine) to 2.4.5

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): single Install

**Comment by saparicio** [comment]
I think this was broken fixing this https://github.com/rancher/rancher/issues/25974

**Comment by bashofmann** [comment]
@westlywright was there a specific reason to change the min value for the replica count to "1"? "0" is a valid value for this and there are definitely use-cases where you want to keep a deployment or statefulset scaled down to 0.

**Comment by westlywright** [comment]
@bashofmann I think it was a misunderstanding between myself and QA.

**Comment by SebManGK** [comment]
@bashofmann @westlywright So, in case that this was not intended, could there be the chance to be adapted to the origin possibility again (minimum of pods=0) in the next patch?

**Comment by westlywright** [comment]
@SebManGK I will get a fix into the 2.4.6 path release

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.4.5`
Steps:
Deploy a scaleable deployment.
Scale down to 0 a deployment.
Edit the deployment.
Move out the focus from the number of pods fields.
Pods count will be set to 1 instead of 0 
![Screen Shot 2020-08-11 at 4 16 44 PM](https://user-images.githubusercontent.com/57409052/89958159-1046db80-dbee-11ea-8d02-04fd4f5b13bb.png)

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 44caa5889`
Pod count remains at 0.
