### ISSUE TITLE
Make services discoverable to each other cross stacks

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2817]
Today services within the same stack are discoverable to each other. We should make even services cross stack to be discoverable by calling serviceName.stackName. The bug below should be fixed along:

https://github.com/rancher/rancher/issues/1758

@ibuildthecloud @will-chan

**Comment by lavvy** [comment]
+1.  Yeah i had actually been thinking of this feature.  I was thinking it could be Stackname.Servicename

**Comment by alena1108** [comment]
Here is the way we are planning to implement it. 

1) "default" section will contain ALL services (from all the stacks) information. There will be a change in FQDN format to support duplicated services names cross stack. 

Instead of 
```
serviceName.ranhcer.internal
```

it would be:
```
serviceName.stack.ranhcer.internal
```

2) /etc/resolve/conf on every service container will get programmed with

```
domain stack.ranhcer.internal
```

so containers of the stack "foo" would be able to resolve all services within foo w/o putting "stack.ranhcer.internal" suffix to every dns request explicitly 

to resolve service in another stack. stackName.ranhcer.internal has to be appended to dns request

3) we are still going to support custom link names. If you want service "foo" to be resolvable as "foo1" to instances of service "bar", you would have to create service link from service bar to service foo with a link name "foo1"

@vincent99 @ibuildthecloud comment if anything is missing

**Comment by Rucknar** [comment]
Sounds good, would it be possible to make this behaviour configurable? For any users that prefer the explicit linking as opposed to everything to everything? I suspect most use cases would use the above, i can imagine use cases though where there is a wish to restrict resolution to defined links.

**Comment by alena1108** [comment]
@Rucknar we will most likely start with default cross stack resolution as a default strategy, and can add an option to turn it off later if there is a users demand for this behavior.

**Comment by vincent99** [comment]
We should probably start telling people to use the FQDN in their code, or else there's going to be confusion when someone creates a stack that matches a TLD ("com", "dev", "ninja", there's hundreds now).  A DNS request for "google.com" could end up searching `google.com.rancher.internal.` and matching a service.

That is also not great because you now have to know the name of the current stack to create an unambiguous fully-qualified DNS request.  Maybe we should add alternate entries to allow explicitly asking for a service in the current stack, i.e. `<service>.rancher-current-stack.internal.`  And put that as the first search domain, and use namespace that for explicit "as name" links too.

I would be +42 on an option to disable all the implicit linking behavior.  Not that I personally need it right now, but if I were at $big_company developing an application with microservices it seems like madness to control all the flow between them with duct-taped config files with hardcoded service names in them that might point to entirely different stacks managed by different teams.  I'd much rather require explicit links with a contract of "this service requires input services linked as: `db`, `queue`, `mailer`, etc".  Plus the graph view is useless if you're just using implied links.  And you have no hope of ever locking down communication paths if you don't know what the relationships are.

**Comment by alena1108** [comment]
>> I would be +42 on an option to disable all the implicit linking behavior. 

do you think we should disable it for cross stacks only, or even within the service? because today its implicit for the latter

**Comment by vincent99** [comment]
I was thinking all, but that makes sense too... "none", "stack", or "environment"

**Comment by mishak87** [comment]
I would like "none" option also. Graphs in UI are useful feature especially when communicating architecture with rest of the team.

**Comment by alena1108** [comment]
So cross stacks dns support is in! Things to test

* old functionality should still work (including host level networking). Services are discoverable within the same stack as before by service_name; instances - instance_name
* cross stacks services are discoverable by fqdn in format of service_name.stack_name.rancher.internal; instances - instance_name.service_name.stack_name.rancher.internal
* named links are still supported, both within the stack, and cross stacks.
* cross stack discovery is limited by environment. Cross environment discovery is not supported. 
* support for 2 namespaces - rancher.internal and kubernetes (latter can be tested separately, as a part of k8s testing)
* upgrade should be tested as well

there were also changes to the VIP generation. VIP will be assigned to the service only when "assignServiceIpAddress" (new param) is set to true on the service.

**Comment by fbrbovic** [comment]
Do new changes include restricting access between containers and services which are not linked together or not part of the same app?  

Firewalling access between containers and services which are not link together is very much needed for any serious environment so it can be kept secure.

**Comment by vincent99** [comment]
@fbrbovic:  no, this is just changing the list of DNS answers available..  We can create a separate issue for actually restricting communication.

**Comment by fbrbovic** [comment]
Yes I think having the restriction would be very much needed, so if you can create a separate issue that would be great. Thanks

**Comment by sangeethah** [comment]
Tested with latest build from master:

- cross stacks services are discoverable by fqdn in format of service_name.stack_name.rancher.internal; instances - instance_name.service_name.stack_name.rancher.internal - Bug - https://github.com/rancher/rancher/issues/3811
- named links are still functional both within the stack, and cross stacks - Bug - https://github.com/rancher/rancher/issues/3785

Closing this issue since the feature is in. Bugs found when testing this feature will be tracked as different bugs.

**Comment by deniseschannon** [comment]
@fbrbovic Would you be able to create an issue for the use case that you'd like to address for restricting communication?

**Comment by fbrbovic** [comment]
@deniseschannon I've opened a separate ticket:  https://github.com/rancher/rancher/issues/3895
