### ISSUE TITLE
Support for UAE in AKS

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#28341]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
https://azure.microsoft.com/en-us/global-infrastructure/services/?regions=uae-central,uae-north&products=all
UAE North is available and UAE Central will be available in q3 2020

gz#13507

**Comment by jiaqiluo** [comment]
the region `UAE North` is validated on rancher:`v2.4.11-rc2` single install setup 

Steps:
- run rancher single install
- provision an AKS cluster in the region `UAE North`. Note: set "Monitoring" to "Disabled" because log analytics is not supported in this region 

results:
- the cluster is provisioned successfully 
- basic functional checks are passed 

![image](https://user-images.githubusercontent.com/6218999/100648689-8470d080-32fe-11eb-9ef7-7a992a19d1ad.png)


Here is the list of k8s versions showing in the dropdown list when creating the cluster
<img width="700" alt="Screen Shot 2020-11-30 at 10 56 50 AM" src="https://user-images.githubusercontent.com/6218999/100648744-9bafbe00-32fe-11eb-855e-e77b1692802a.png">

**Comment by maggieliu** [comment]
UAE central for 2.4 is tracked here: https://github.com/rancher/rancher/issues/30278

**Comment by jiaqiluo** [comment]
the region `UAE North` is validated on rancher:`v2.4.11-rc6` single install setup 

Steps:
- run rancher single install
- provision an AKS cluster in the region `UAE North`. Note: set "Monitoring" to "Disabled" because log analytics is not supported in this region 

results:
- the cluster is provisioned successfully 
- basic functional checks are passed 

 
![image](https://user-images.githubusercontent.com/6218999/100682183-bc920680-3332-11eb-953c-1daedfda46a5.png)


Note: `UAE North`  is the only new region added to this release
<img width="715" alt="Screen Shot 2020-11-30 at 5 24 04 PM" src="https://user-images.githubusercontent.com/6218999/100682231-dcc1c580-3332-11eb-811b-e68f08d4202d.png">

**Comment by jiaqiluo** [comment]
The following are verified on rancher:`v2.4.11` single-install setup:


- confirmed that we can launch the `kubectl` from the cluster page 

<img width="975" alt="Screen Shot 2020-12-01 at 11 53 39 AM" src="https://user-images.githubusercontent.com/6218999/100793144-f0c00280-33d8-11eb-851e-bdef990ae0b5.png">


Note: 
- the `kubectl` might be not accessible right after the cluster shows active in the UI but will recovery by itself in one minute or two. 
<img width="1846" alt="Screen Shot 2020-12-01 at 11 52 43 AM" src="https://user-images.githubusercontent.com/6218999/100793361-38df2500-33d9-11eb-96c9-3ec677067490.png">
