### ISSUE TITLE
istio sidecar memory request vs limit producing OOMs

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#28359]
**What kind of request is this (bug):**
On bare-metal we are usually bound by more or less fixed RAM.
When deploying rancher + istio on bare-metal this might become a problem regarding the memory request/limit.
Imagine cluster-node having 128GB RAM, 126GB being used.
Now istio-sidecar starts using more memory e.g. 4 sidecars using 1GB instead of 128MB -> (random) processes getting OOM-killed.

**Steps to reproduce (least amount of steps as possible):**
Make cluster-nodes use 99% of ram, and then make istio-sidecars (or other pods having memory request < memory limit) use more ram.

**Result:**
Kernel will (randomly) kill processes with lower priority.

**Other details that may be helpful:**
It's a general problem with request/limit, but for our workloads we usually only set a limit so we get max=min and this doesn't become a problem.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal 
- Kubernetes version (use `kubectl version`): 1.17.9/1.18.6

regards,
strowi

**Comment by ItsReddi** [comment]
I am unsure if we hitted that, thought it would be some new rancher 2.6 bug.
In our case it was even worse. The node, went down completely. (I think because swap is disabled on our cluster nodes and somehow we got a kernel panic? can only expect, since its not reproduced easily)

BUT:
The node was not out of memory it only used ~20% of the memory. But system logs were showing, kernel was killing processes for OOM Reasons.
The only change on our side was that we added a request value, before that we only had a limit value set.
