### ISSUE TITLE
[UI] EKSv2: display import command on create if cluster only has private access enabled

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#28356]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
If an EKS cluster is created with only private access enabled, display the import commands shown for other clusters. This is because it will not be possible for rancher to communicate with the cluster and deploy the agent when public access is not enabled unless rancher is privately networked to the cluster somehow.

This import command should also be displayed when a user registers a cluster with only private access enabled.

**Comment by westlywright** [comment]
The UI will do the following: 
On cluster create when the user saves, if the eks cluster has `privateAccess` enabled, the user will be shown the cluster import command. This is the same command we show for the regular import clusters. 
A new action has been exposed for EKS clusters with private access enabled, `Import Host`. Selecting this option will show the cluster registration modal with the import command. The same action exists at the cluster dashboard level. 
On EKS cluster import, the user will be redirected as normal. We can't redirect the user to the import command because we don't know yet if the cluster has private access enabled. We don't know this until the configs have been synced on the backend. The user will have to use the `Import Host` action after the cluster specs sync between EKS and Steve. There is no way around this unless the configs can be synced as soon as the cluster is "created/imported". 
Edit actions occur as normal, I dont think we should show the import command on every edit since we have the `Import Host` action available now.

**Comment by aaronRancher** [comment]
This feature is verified with Rancher server `rancher\rancher:master-head` `version a31eecf` and `rancher\rancher:v2.5-head` `version e2e530c`

Steps:
Create an EKS cluster in rancher
Deselect public network access
Select private network access
![Screen Shot 2020-12-03 at 5 12 30 PM](https://user-images.githubusercontent.com/57409052/101105518-07a65680-358b-11eb-9d75-104b731aecfd.png)
Create cluster

Result:
Import command is displayed:
![Screen Shot 2020-12-03 at 5 13 30 PM](https://user-images.githubusercontent.com/57409052/101105497-f52c1d00-358a-11eb-8eb1-1a699870cf42.png)
User is given the option to view the same command in cluster view during provisioning:
![Screen Shot 2020-12-03 at 4 59 24 PM](https://user-images.githubusercontent.com/57409052/101105570-27d61580-358b-11eb-8b45-7b7d7e037c79.png)
