### ISSUE TITLE
FR: GlobalDNS/externaldns Allow setting of '--aws-batch-change-size' via Rancher UI

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#28391]
**What kind of request is this (question/bug/enhancement/feature request):**
feature-request

**Steps to reproduce (least amount of steps as possible):**
No need to reproduce the default aws-batch-setting is 1000
![image](https://user-images.githubusercontent.com/56899019/90220300-48972580-de4b-11ea-854b-a644cf9aaf12.png)
![image](https://user-images.githubusercontent.com/56899019/90220318-5056ca00-de4b-11ea-875c-9cf2954bc9c3.png)

**Result:**
However, with large deploys this can cause issues when an UPSERT operation is triggered (this doubles the transactions to surpass 1000)

**Other details that may be helpful:**
Currently, the workaround is to lower this batch size to 500 which will allow for a 500 batch upsert operation.

![image](https://user-images.githubusercontent.com/56899019/90220361-6795b780-de4b-11ea-8c71-1b371e5ebe18.png)

However when any updates to the underlying GlobalDNS app are made the change is reverted.

Having this setting configurable, or even defaulting lower due to the UPSERT situation would be ideal. Definitely prefer allowing us to configure as needed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GlobalDNS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gzrancher/rancher#10967

gz#13293

**Comment by prachidamle** [comment]
@maggieliu  @cbron  The PR above will expose the parameter as a chart value and ensure it is always set to a lower value when GlobalDNS is deployed.

 But looks like in this ticket, we want to expose the parameter via Rancher GlobalDNS U and be able to change it while deploying it via Rancher UI? If that is what is desired, we will need to change Rancher API to expose this parameter. 

https://github.com/rancher/system-charts/pull/370#issuecomment-729860601

**Comment by maggieliu** [comment]
@Rancheroo @dkeightley Is the intention to make the parameter a fixed value or something user should be able to configure when deploying the chart?

**Comment by dkeightley** [comment]
@maggieliu from the context we have, the preference is to allow configuration in the UI, but at a minimum provide a safe default (already in the PR) to avoid rate limiting.

**Comment by cbron** [comment]
Ready to test in 2.5/master.

**Comment by cbron** [comment]
The fix adds ability to add any custom value, for this specific setting the key is: `aws.batchChangeSize`

**Comment by anupama2501** [comment]
Following are the steps that were verified:
on 2.5-head, create a DNS provider with the additional options, added the key aws.batchChangeSize with a value of 2000 and the value is reflecting in the local DNS app with 3 worker nodes, 1 etcd and 1 control plane
<img width="1264" alt="Screen Shot 2020-12-11 at 4 06 34 PM" src="https://user-images.githubusercontent.com/38144301/101965882-08fb0300-3bcb-11eb-9670-5aece101ac2e.png">
<img width="579" alt="Screen Shot 2020-12-11 at 4 07 13 PM" src="https://user-images.githubusercontent.com/38144301/101965953-3f388280-3bcb-11eb-8803-4955aa204395.png">

From the local edit yaml option, tried editing the value from view/edit yaml and the edit option is reflecting correct values
<img width="746" alt="Screen Shot 2020-12-11 at 4 05 49 PM" src="https://user-images.githubusercontent.com/38144301/101966014-71e27b00-3bcb-11eb-80c8-ec37cccc12f3.png">

Upgrade from 2.5.3- latest:
On 2.5.3 created a global DNS provider and from the local- edit yaml, added the key value : --aws-batch-change-size=2000 in the container part. 
Now upgraded to 2.5.4, and verified by adding the aws.batchchangesize value to 1200. and verify the API view, the value is not changed [as expected because the charts aren't upgraded]. now upgrade the chart to latest:
<img width="1266" alt="Screen Shot 2020-12-11 at 4 28 30 PM" src="https://user-images.githubusercontent.com/38144301/101968814-0ce05280-3bd6-11eb-8c58-84bcab3fe8ff.png">

Added the additional option with the key aws.batchChangeSize and verified the values reflected in the API. 
<img width="568" alt="Screen Shot 2020-12-11 at 5 27 48 PM" src="https://user-images.githubusercontent.com/38144301/101968867-54ff7500-3bd6-11eb-9c5f-ac932f973ac3.png">
Changed the values from the additional option to a different value and it reflected the changed value. 
Verified changing the values from the edit yaml/API and saved. The values are reflected as expected.

**Comment by sowmyav27** [comment]
Reopening to validate on master-head..

**Comment by anupama2501** [comment]
Verified on master-head[commit id: 46b0df4].Added UI additional button key for batchsize - aws.batchChangeSize=2500
<img width="1082" alt="Screen Shot 2020-12-11 at 7 19 32 PM" src="https://user-images.githubusercontent.com/38144301/101971395-d7436580-3be5-11eb-85ff-cda056ff3ad5.png">
<img width="638" alt="Screen Shot 2020-12-11 at 7 18 20 PM" src="https://user-images.githubusercontent.com/38144301/101971397-de6a7380-3be5-11eb-8892-be02a45eb059.png">

Edited the button with different value and see that API is reflecting the provided values.
