### ISSUE TITLE
Install the Rancher cluster independently on the server of the existing Kubernetes cluster

### ISSUE THREAD

**Issue by lipangeng** [rancher/rancher#28451]
# question
Install the Rancher cluster independently on the server of the existing Kubernetes cluster.
1. I have a Kubernetes cluster,but I don’t have enough servers to provide it to Rancher independently.
2. I want to ensure that rancher is independent, and I don't want to install rancher in an existing Kubernetes cluster.

I want to use the following architecture, but I don't have enough servers.

<img width="343" alt="WX20200819-100551@2x" src="https://user-images.githubusercontent.com/7782635/90583882-d7b58c00-e203-11ea-8b83-93f30ab46cc0.png">

**Comment by superseb** [comment]
I don't understand what the question is, for K3S based Rancher HA, you will need 2 servers + a database, for RKE based Rancher HA, you will need 3 servers (because of etcd). From there on, you can create clusters following the node requirements listed here (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/node-requirements/).

The only part that is shown is what you would like, but nowhere is specified what you actually have. How many (bare metal/virtual) servers do you have with what specifications? Do you want to use bare metal only or VMs? If you don't have enough resources to run the required setup, you will need to make sacrifices in other areas.

**Comment by lipangeng** [comment]
Looks like this:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/7782635/91426460-22cc4080-e88f-11ea-8ce0-e32c8bd9ae8c.png">
or
<img width="680" alt="image" src="https://user-images.githubusercontent.com/7782635/91430248-79d31500-e891-11ea-9924-1096f3332456.png">

**Comment by superseb** [comment]
We recommend dedicated nodes for Rancher, to make sure Rancher is not influenced by other workloads in the cluster (possibly hammering etcd/ingress or other). If you can't reserve nodes for a dedicated cluster, technically you can mix but it is not advised because of the reasons mentioned earlier.
