### ISSUE TITLE
external_links are not created with rancher-compose 0.5.3 but work with 0.5.2

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2848]
rancher-compose 0.5.3
rancher-server 0.46.0

**Comment by deniseschannon** [comment]
rancher-server v0.46.0 is to used with rancher-compose v0.5.2, so that may be the issue? I haven't had a chance to spin up a v0.46.0 to test the combo of v0.46.0 and v0.5.3. 

I tested rancher-compose v0.5.3 with external links in v0.47.0 and my links were created. When I look at the docker-compose.yml in the view config of the stack, I see that the external link is created.

You might be running into this issue if you have multiple environments:
https://github.com/rancher/rancher/issues/1389

**Comment by deniseschannon** [comment]
@ndelitski We are expecting users to use the rancher-compose version paired with the associated Rancher version as this is the tested combination. Please re-open if you are still seeing issues with external-links as of v0.51.0 and Rancher-compose v0.7.0
