### ISSUE TITLE
GKE Service Account is not updated

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#28527]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Set up a cluster with one SA then attempt to change the SA and revoke the older one

**Result:**
You can auth to edit the cluster with the new SA but no values are ever saved as the old service account is cached in the cluster state and that now fails auth as it is revoked

**Other details that may be helpful:**
This is the same as the EKS bug fixed here - https://github.com/rancher/rancher/pull/26412

It just needs to be applied to GKE

@rmweir @maggieliu could this fix make it into an upcoming release?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5

**Cluster information**
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud - GKE

gzrancher/rancher#11643

gz#13289

**Comment by asemen2608** [comment]
gz#12151

**Comment by asemen2608** [comment]
See also customer case 12151.
oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}

**Comment by asemen2608** [comment]
Could it be added to one of the earlier v2.5.x release?

**Comment by sadiapoddar** [comment]
Reproduced this issue on 2.3.5 rancher
steps.
1. created a gke cluster with a service account (SA)
2. Edit cluster to load a different SA and saved
3. Disable the SA account which was used in step 1.
<img width="1313" alt="Screen Shot 2020-11-10 at 12 45 14 PM" src="https://user-images.githubusercontent.com/72409237/98733143-f0da5e80-2354-11eb-8313-71c54ae3071b.png">

4. Issue an operation from the cluster which needs authentication from the identity manager. (auto scaling was invoked)
5. Since the new SA was not updated and the previous SA was used from the cache, users hit the error

**Comment by asemen2608** [comment]
Is it planed for Rancher v2.5.3, v2.6 ?

**Comment by gaktive** [comment]
This should be able to be tested once https://github.com/rancher/rancher/issues/31042 is completed.

**Comment by asemen2608** [comment]
The error message shown in the UI has changed after the latest upgrade to Rancher v2.5.6

The new error is now:
Get "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_grant","error_description":"Invalid JWT Signature."}

![Screenshot_](https://user-images.githubusercontent.com/61939253/110631109-760c3d80-81a6-11eb-9c7c-3b1d064d6970.png)

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.3.5` and `rancher\rancher:v2.5.6`

Steps:
1. In Google Cloud Platform, ready 2 service accounts.
2. In Rancher, provision a GKE cluster with service account alpha.
3. After cluster is made available, edit the cluster by loading service account beta. Save the cluster.
4. In Google Cloud Platform, disable service account alpha. 
5. In Rancher, scale the node count of the cluster using service account beta.

Result:
Error from Rancher `v2.3.5`
![Screen Shot 2021-03-15 at 12 43 55 PM](https://user-images.githubusercontent.com/57409052/111234976-f7037480-85ac-11eb-9a69-d8955db14e39.png)
Error from Rancher `v2.5.6`
![Screen Shot 2021-03-15 at 1 17 14 PM](https://user-images.githubusercontent.com/57409052/111235729-7fcee000-85ae-11eb-97fe-620db27dad4f.png)

After waiting, the cluster health check will fail:
![Screen Shot 2021-03-15 at 2 58 11 PM](https://user-images.githubusercontent.com/57409052/111235756-8eb59280-85ae-11eb-95d6-07b381f49d3c.png)

**Comment by prabalsharma** [comment]
@aaronRancher I guess you have tested this as a part of test plan.

**Comment by aaronRancher** [comment]
With the addition of GKEv2 cloud credentials, this issue has been tested and validated as part of the GKE test plan: https://github.com/rancher/rancher/issues/31678#issuecomment-825042470

On Rancher `v2.5.8-rc8`, the user is able to update Google cloud credentials on cluster edit. And use the valid credential to edit the cluster.
