### ISSUE TITLE
Istio v2 cannot deploy in a hardened cluster

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#28622]
rancher/rancher:v2.5.0-alpha1
cis-1.4
cis-1.5

* Create a hardened cluster
* Deploy `rancher-istio`
* `rancher-istio-kiali` deployment fails with error, and the install does not complete:
```
"rancher-istio-kiali-5c565f856c-" is forbidden: unable to validate against any pod security policy: []:replicas: 0/1
```

**Comment by brendarearden** [comment]
will also need to consider hardened cluster with jaeger and/or cni enabled

**Comment by cbron** [comment]
See also: https://github.com/rancher/rancher/issues/29076

**Comment by doflamingo721** [comment]
This issue is not active on rancher 2.6.3.
Steps followed:
1. Rancher Server version: 2.6.3
2. Create a downstream hardened cluster following rancher's [hardening guide](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/).
3. Install istio from Apps and marketplace.


Result:
istio and kiali installation is successful.

**Comment by rishabhmsra** [comment]
**Validated on 2.6-head**

**Rancher Server:**
- Version: v2.6-head (7efbeab)
- docker install

**Steps followed:**
- Created a downstream hardened cluster (4 nodes, 1-cp, 1-etcd, 2-worker)
- Installed monitoring chart.
- Installed istio `(100.1.0+up1.11.4)`

**Result:**
- Istio chart got installed successfully all istio components came up active. Hence closing the issue.
