### ISSUE TITLE
Update Add Cluster page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#28625]
Highlights in red and keep the spacing normal. I told @lvuch to not bother making a perfect mock with the spacing

<img width="604" alt="Screen Shot 2020-08-28 at 3 36 32 PM" src="https://user-images.githubusercontent.com/11410997/91620282-5d43e500-e944-11ea-9a34-05c4c875be75.png">

**Comment by westlywright** [comment]
I changed `Other Kubernetes Cluster` to `Other Cluster`. It was causing a line break to occur since the boxes are now much smaller and was throwing the heights off. Even when the heights were even between the two boxes, youd get a larger gap below the content of the first box which was weird. Since the title of the section is `Register an existing Kubernetes Cluster` dropping Kubernetes from the button label also seemed appropriate because its sort of implied that you are registering a Kubernetes cluster.

**Comment by soumyalj** [comment]
Verified with master-head(master-731b33e1a7763b)

The updated "Add Cluster page" has the changes mentioned above. The `Other Kubernetes Cluster` is renamed to `Other Cluster` and the boxes are of uniform dimensions.

![Screen Shot 2020-09-03 at 10 29 16 AM](https://user-images.githubusercontent.com/18536626/92147721-5c8dd180-edd0-11ea-86cb-c86ef441b854.png)
