### ISSUE TITLE
Charts Integration testing framework

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28630]
* Investigate helm test module for unit testing
* Investigate adding integration testing into the CI in charts repo

official docs: https://helm.sh/docs/topics/chart_tests/
base example: https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/tests/test-mariadb-connection.yaml

**Comment by cbron** [comment]
Likely bumping this to 2.5.7 timeframe.

**Comment by aiyengar2** [comment]
Need to ensure the testing stuff makes its way into charts-build-scripts and resolves https://github.com/rancher/charts-build-scripts/issues/30.

**Comment by aiyengar2** [comment]
@bmdepesa fyi during hack week we built a solution in https://github.com/aiyengar2/charts-testing that integrates with our existing scripts in rancher/charts (at the time we built it; we'll need to make slight modifications now due to a new repository structure) to set up a Go "unit" testing framework for Helm charts. There is more information on what this framework is in https://github.com/aiyengar2/charts-testing/blob/dev-v2.5-source/tests/template/tests/README.md and example tests that could be written in this way in https://github.com/aiyengar2/charts-testing/tree/dev-v2.5-source/tests/template/tests and https://github.com/aiyengar2/charts-testing/tree/dev-v2.5-source/tests/common.

At the time, the way we defined "unit" testing on a Helm chart was `a test you could run on the manifest outputted by a helm template command on one or more values.yamls associated with the chart`, which differs from integration testing that was defined to be `a test you could run on a chart that has been deployed onto a Kubernetes cluster`.

So while that might not completely satisfy the goals of this issue (e.g. the solution built would not be able to test something like ensuring an operator is creating resources that are Windows compliant, which is something that only integration testing could test), there's definitely some overlap with the type of automated testing we could do with this framework that might fit in nicely with what QA is working on for this issue.

Issue tracking integrating this with rancher/charts: https://github.com/rancher/charts-build-scripts/issues/30
