### ISSUE TITLE
[UI] Recognize rancherd clusters as "rancherd"

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#28651]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Component

**Summary:**
RancherD will need to be recognized separately from rke2 clusters. Today, with no changes made, RancherD would be recognized as an RKE2 cluster. This will need to be changed so it is recognized as a "rancherd" cluster. Could be done via annotations?

**Related:**
RKE2 clusters will need to be shown as "RKE Federal". A separate issue here tracks this: https://github.com/rancher/rancher/issues/28650

**Comment by MonzElmasry** [comment]
a specific driver was set for rancherd pr : https://github.com/rancher/rancher/pull/29075
It's correctly showed in dashboard :  
![Screenshot from 2020-09-22 07-42-47](https://user-images.githubusercontent.com/65324011/93848643-7c673580-fcaa-11ea-9cea-8c713d88f692.png)

and in ecm api cluster driver is set to 'rancherd' but the ember ui shows `imported`  
![Screenshot from 2020-09-22 07-43-18](https://user-images.githubusercontent.com/65324011/93848709-a3be0280-fcaa-11ea-84e0-d090543cc01f.png)

probably because there's no config assigned https://github.com/rancher/ui/blob/master/app/models/cluster.js#L165

**Comment by deniseschannon** [comment]
We should move the cluster page to start using the Rancher provider to show the Provider. Seeing as this is a bigger change, I've moved it to 2.5.1.

**Comment by ShylajaDevadiga** [comment]
In Rancher version v2.5.0-rc6, on the rancher dashboard provider is seen as RKE Government.
```
rancherd -v
rancherd version v2.5.0-rc6 (HEAD)
```
Snippet from cluster API
```
driver": "rancherd",
provider": "rke2",
gitVersion": "v1.18.9-rc1+rke2",
```

![image](https://user-images.githubusercontent.com/56045581/95000951-364b8500-057a-11eb-8540-cf58f207ea58.png)

**Comment by izaac** [comment]
We need a `v2.5.3` RC to test this fix

**Comment by izaac** [comment]
Rancher version `v2.5.4-rc1 (12/04/2020)`

RancherD cluster is now properly recognized as RancherD in the EmberUI and RKE Government in the Dashboard.

![Screen Shot 2020-12-04 at 3 45 26 PM](https://user-images.githubusercontent.com/27659/101222858-efe0d800-3647-11eb-8086-20aad76c049c.png)

![Screen Shot 2020-12-04 at 3 45 35 PM](https://user-images.githubusercontent.com/27659/101222877-f53e2280-3647-11eb-8f01-7ceaac8b24a1.png)
