### ISSUE TITLE
Rancher 2.4.6 - Api Key max duration

### ISSUE THREAD

**Issue by quadrinho** [rancher/rancher#28668]
**What kind of request is this (question/bug/enhancement/feature request): question

**Steps to reproduce (least amount of steps as possible): Create a Api Key in Rancher UI

**Result:You can create a Api Key with Max 1 Day expiration

**Other details that may be helpful:**

**Is there a Rancher API that can be used to refresh the Bearer Token so that it doesn't expire every day?**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher 2.4.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by martin-kieliszek** [comment]
+1 

Curious to get advice on what the recommended flow is, now that those who have migrated away from previous long lived API keys can only get maximum 1 day keys. Definitely would like to automate it (where previous automation wasn't needed as it was just a longer expiry than 1 day)

**Comment by toolbar23** [comment]
+1 

I use api keys to let another system do stuff on my behalf. 

And most of the time I want that system to do it's job not just for 24 hours but for eternity (though I am ok with renewing these api keys every now and then).

**Comment by vincent99** [comment]
This is something that was intended to be optional, and not on by default.  You can edit `/v3/settings/auth-token-max-ttl-minutes` for the moment.

**Comment by quadrinho** [comment]
> This is something that was intended to be optional, and not on by default. You can edit `/v3/settings/auth-token-max-ttl-minutes` for the moment.

Thanks @vincent99 . On my side is usefully change that parameter.

**Comment by maggieliu** [comment]
Need to update the AuthTokenMaxTTLMinutes to default to 0

**Comment by jiaqiluo** [comment]
the following tests are done on v2.4.7-rc2: 


### 2.4.5 -> 2.4.6 -> 2.4.7
- run v2.4.5
- create tokens t1(never), t2(a day), t3(a month), and t4(a year) -> confirm that all tokens get the expected expiration date  
- upgrade to v2.4.6
- confirm that all tokens keep the existing expiration date  
- by default, auth-token-max-ttl-minutes = 1440
- create token t5(a day) -> confirm the expiration date is after 1 day 
- change auth-token-max-ttl-minutes to 2880
- upgrade to 2.4.7
- confirm that auth-token-max-ttl-minutes is 2880 
- confirm that existing tokens keeps the same 
- create token t6(expire in 12 hours) -> check the expiration date is after 12 hours 
- create token t7(expire in 36 hours) -> check the expiration date is after 36 hours 


### 2.4.5 -> 2.4.7
- run v2.4.5
- create tokens t1(never), t2(a day), t3(a month), and t4(a year) -> confirm that all tokens get the expected expiration date 
- upgrade to v2.4.7
- all tokens keep the existing expiration date
- confirm that auth-token-max-ttl-minutes = 0 
- create tokens t5(never), t6(a day), t7(a month), t8(a year), and t9(36 hours) -> confirm that all tokens get the expected expiration date 
- change auth-token-max-ttl-minutes to 1440
- create tokens t10(a day) and t11(23 hours) -> confirm that all tokens get the expected expiration date 
- create a token with 0 minute -> it turns out the token expires in 1 day (the max value)


### 2.4.6 -> 2.4.7
- run v2.4.6
- by default, auth-token-max-ttl-minutes = 1440 (1 day)
- create tokens t1(1 day), t2(23 hours) -> confirm that all tokens get the expected expiration date
- create a token t3 with 0 minute -> it turns out the token expires in 1 day (the max value)
- upgrade to v2.4.7
- existing token keeps the same expiration date
- confirm that auth-token-max-ttl-minutes become 0
- create tokens t4(never), t5(a day), t6(a month), and t7(a year) -> confirm that all tokens get the expected expiration date  
- create a token t8 with 0 minute -> it turns out the token expires never 
- change auth-token-max-ttl-minutes to 600(10 hours)
- create tokens t9(max), t10(9 hours) -> confirm that all tokens get the expected expiration date 
- create a token with 0 minute -> it turns out the token expires in 10 hours (the max)
