### ISSUE TITLE
Prometheus-proxy not able to start - Permission Denied

### ISSUE THREAD

**Issue by frankthetank** [rancher/rancher#28676]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
From the Rancher web UI, navigate to a cluster > Tools > Monitoring.  Enable Monitoring.  (we have tried with Prometheus and Grafana persistent storage marked as True as well as False with no difference)

**Result:**
Cattle-prometheus namespace is created within the System project however the prometheus-proxy container within the prometheus-cluster-monitoring pod / stateful set fails to launch.  The error reported is "/bin/sh: /var/cache/nginx/nginx-start.sh: Permission Denied"

**Other details that may be helpful:**
I have reviewed ticket #23573 which links to a merge request that suggested a change of storage to EmptyDir and user ID to 101 would solve the problem.  I verified the loaded configuration matches these storage and user semantics.  The container in question is pulling image rancher/nginx:1.17.4-alpine.

This cluster is primarily offline / disconnected from the internet.  System images are manually pulled and imported into the private system registry.  Cluster images are pulled through an Artifactory instance from external sources.

We are enabling monitoring so that we can then enable Istio to make use of some of the additional features that tool provides.

**Environment information**
Rancher version 2.4.5, deployed in HA configuration.  The clusters on which we are enabling monitoring have at least three hosts each.
Host OS: CentOS 7

**Cluster information**
Cluster type: Local Custom
Machine Type: VM (in vSphere-managed environment)
Kubernetes version: 1.17.2 (server), 1.17.6 (client)

- Docker version (use `docker version`): 1.13.1, api version 1.26 (as provided by CentOS via RPM)

**Comment by bgulla** [comment]
I am going to try to reproduce this bug this week. We haven't had any other customers reporting this. Can you confirm that you are installing Istio without first enabling the monitoring stack from Tools -> Monitoring?

**Comment by frankthetank** [comment]
The Istio component (under Tools -> Istio) will not enable / install without first enabling Monitoring.  We have enabled Monitoring at the cluster level.  We can then enable Istio and the istio-system namespace shows up in the System project and all of its (Istio) pods appear to start successfully.

While the Prometheus monitoring does report as "Enabled" allowing the Istio tool to then be enabled, the Rancher UI now shows a "Monitoring API is not ready" on the cluster dashboard.

And now, because these things report as "Enabled" we are able to begin looking at Istio panels on the project levels, too.  The additional tools (Kiali, Grafana, Jaeger, etc) do come up and attempt to display data but there is no data to display because Prometheus is still down.  In fact, Kiali reports that many other pods are up but that Prometheus is down.

Hope that helps.

**Comment by kurbar** [comment]
I ran into the same issue when trying to enable monitoring on our cluster. `prometheus-proxy` container under `prometheus-cluster-monitoring` fails to come up because it fails to start Nginx due to a permission issue.
```
/bin/sh: /var/cache/nginx/nginx-start.sh: Permission denied
```

**Environment information**
- Rancher version: v2.4.8
- Installation option (single install/HA): single install
- Host OS: CentOS 7



**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (kubeadm)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 5x VM - CentOS 7 2vCPU 8GB ram (1 master, 4 worker)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 19.03.6, API version 1.40

**Comment by NadEFurY** [comment]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Importing a custom cluster. 7 hosts, 2 workers, 2cps, 3etcds. Running in vSphere. Air-gapped installation with a private registry.

**Result:**
All's good except for the prometheus-proxy. The container doesn't start because of a permission problem.
/bin/sh: /var/cache/nginx/nginx-start.sh: Permission denied

**Other details that may be helpful:**
/bin/sh: /var/cache/nginx/nginx-start.sh: Permission denied

**Environment information**
- Rancher version: v2.4.8
- Installation option: HA, with a supplemental cluster. The cluster that has the prometheus pod is in a seperate cluster from rancher itself.


**Cluster information**
- Cluster type: Custom. Pre-created OEL7 VMs.
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs in vSphere, 5 ESXis, E5-2690 v2 x2 per ESXi host, ~384GB RAM per host
- Kubernetes version (use `kubectl version`): v.1.18.6

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.11-ol
 API version:       1.40
 Go version:        go1.14.7
 Git commit:        78418d7
 Built:             Tue Aug 18 22:46:21 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11-ol
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.7
  Git commit:       78418d7
  Built:            Tue Aug 18 22:44:38 2020
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
 containerd:
  Version:          1.2.4
  GitCommit:        
 runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by NadEFurY** [comment]
Okay, a classic case of reporting and then immediately solving the problem.

In my case, the host has the /var mountpoint mounted with the noexec flag.

Removing that, solves the problem. Now why the container executes something in /var, is beyond me.

**Comment by frankthetank** [comment]
Unfortunately, the environments we work in will not allow disabling the "noexec" flag on a mount to /var for our hosts.  It kind of goes to your question about why the container is trying to execute something from /var.  Security means a lot to my organization.

Anyone have alternative ideas?

**Comment by frankthetank** [comment]
~solved for us
An alternate solution that my lead sys admin found is to create separate mount points under /var/lib{docker,kubectl} where those mount points may be mounted with the exec flag while the base system maintains the noexec flag.

It still does not absolve the issue of executing from the /var/* mount but is a workable solution for us to enable Istio in our Rancher environments.
