### ISSUE TITLE
Rancher DNS sometimes not resolving

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2873]
Hi,

I am having a hard time with Rancher DNS sometimes not resolving DNS records depending on where I resolve from.

Should any container in Rancher be able to look up any other container DNS records as long as the io.rancher.container.dns is set to true?

Cheers,
Matteo

**Comment by bacheson** [comment]
I experienced this problem when launching many fast moving containers. I had a race condition where the network wasn't initialized when I attempted to resolve a service.

My solution was to wait for the network before proceeding. Just a thought.

**Comment by m4ce** [comment]
@bacheson,

thanks for the info, but in this case I am only testing with a handful of containers, so there should not be any bottleneck on the network level.

What I noticed is the following:

1) All containers running in a given stack can look up DNS records for services running within the stack. So, if stackA has serviceA and serviceB, all containers in the stack can look up serviceA.rancher.internal and serviceB.rancher.internal;

2) If stackA/serviceA containers wants to resolve stackB/serviceB as serviceB.rancher.internal, external_links need to be used between the two services;

3) given one container from stackA/serviceA runs on the same host as one container from stackB/serviceB, if serviceB runs in host-networking with io.rancher.container.dns set to true, serviceA can resolve serviceB.rancher.internal without any external linking! The other way around doesn't work unless serviceA also runs with host-networking and io.rancher.container.dns set to true

There might be other cases but I have not been able to identify them properly.

M

**Comment by m4ce** [comment]
I've re-tested 3) extensively and things look even more confusing:

Given the following scenario:

stackA: serviceA1, serviceA2
stackB: serviceB1 -> (external link to stack/serviceA)

in theory any container under serviceB1 can resolve serviceA1.rancher.internal but not serviceA2.rancher.internal.

The above behaves like that if all the services involved run under the managed network. However, if one service runs under host-networking with io.rancher.container.dns set to true, it starts behaving a bit weird.

In fact, if one or more containers from stackA/serviceA1 or stackA/serviceA2 run on the same host and one or more containers from stackB/serviceB1, then serviceB1 containers will be able to resolve serviceA2.rancher.internal even without external linking.

I've tried to describe the issue as best as I could, let me know if there's anything unclear.

M

**Comment by alena1108** [comment]
@m4ce 

>> serviceA can resolve serviceB.rancher.internal without any external linking! 

>>All containers running in a given stack can look up DNS records for services running within the stack. So, if stackA has serviceA and serviceB, all containers in the stack can look up serviceA.rancher.internal and serviceB.rancher.internal;


Thats a change we've added recently. All services within the same stack are resolvable to each other w/o explicit links between them. Only when you need a custom dns name for your service (!=service.name) you would have to create a link. Example: service A would need to resolve service B by "foo" name. For that, you would have to create a link from service A to service B with custom name "foo".

>>2) If stackA/serviceA containers wants to resolve stackB/serviceB as serviceB.rancher.internal, external_links need to be used between the two services;

To make services resolvable cross stacks, you do have to link them explicitly. 

>>given one container from stackA/serviceA runs on the same host as one container from stackB/serviceB, if serviceB runs in host-networking with io.rancher.container.dns set to true, serviceA can resolve serviceB.rancher.internal without any external linking! The other way around doesn't work unless serviceA also runs with host-networking and io.rancher.container.dns set to true. Bug?

No, its not a bug. "io.rancher.container.dns=true" defines that the container can use Rancher internal-dns. So all services with host-networking should have this label set to true in order to resolve others.


@deniseschannon we should document all the above...

**Comment by alena1108** [comment]
@m4ce now to the bug you've described in the video (thank you for the detailed explanation). It is a real bug. So here what happens. Lets assume you have just one host in your system, and there are 2 services deployed on this host: serviceA (managed network) and serviceB (managed network). In this case DNS config file would look like this:

```
default {
8.8.8.8
}

serviceA_ip1{
everything service A can resolve
}

serviceA_ip(n){
everything service A can resolve
}

serviceB_ip1{
everything service B can resolve
}

```

So when request comes from service's A container having ip1, the lookup is done in "serviceA_ip1" section first, then - if the fqdn not found there - the lookup is done against "defaults" section.

Now lets assume the use case when serviceA is on managed network, and service B is on host networking, and has a label allowing it to use rancher internal dns. In this case dns config looks a big different:

```
default {
8.8.8.8

and everything service B is allowed to see
}

serviceA_ip1{
everything service A can resolve
}

serviceA_ip(n){
everything service A can resolve
}
```

As you see, everything that service B is allowed to see, is placed under "default" section. Why is it done this way? Because we don't know client  ip address of the requests coming from host level container. Therefore when implementing "dns for host container" we used this workaround - place host-container-resolve-info to "defaults".

@ibuildthecloud @vincent99 we have to think of a better workaround. As now all containers on the host where at least one host container is present, would be able to discover all services of the stack where the host container belongs to. Suggestions?

**Comment by spicykaiju** [comment]
Why not make things simple and expose DNS Rancher-wide? This is how DNS works in regular environments, and IMHO what you are proposing above is very confusing for engineers who expect this behavior. You can still continue to block unlinked services from one another via managed networking.

**Comment by alena1108** [comment]
@spicykaiju I didn't propose anything, I've just explained how things work currently in Rancher and why the buggy behavior occurred. And we do plan to make services discoverable to each other by default even cross stacks, here is the ticket: https://github.com/rancher/rancher/issues/2817

**Comment by liubaishui** [comment]
Please see the #3100 issues, I have the save error.

**Comment by alena1108** [comment]
Services are discoverable cross stacks now by default in format:

service_name.stack_name.rancher.internal


 We are suggesting to use fqdn format for service resolution even within the same stack.

**Comment by sangeethah** [comment]
Tested with latest build from master:
Services can be discovered cross stack using the format - service_name.stack_name.rancher.internal

**Comment by m4ce** [comment]
@sangeethah,

thank you guys for the great work!
