### ISSUE TITLE
[feedback] [ui] Suggest stop button change

### ISSUE THREAD

**Issue by hrwebasst** [rancher/rancher#2882]
Stop button uses a symbol more commonly associated with delete whereas start uses universal start symbol.
![stop](https://cloud.githubusercontent.com/assets/9060082/11543465/b3e9b04a-98f1-11e5-9f29-d7e9ae0f6e1e.png)

Suggest a Square stop button

**Comment by vincent99** [comment]
It's an octagon because stop sign, but in that size it's not very clear that it's not just a circle so the x adds another element to identify it.  Square only works when next to pause/play/rewind, on it's own it just looked like generic box.  Maybe square in octagon @lvuch?

We're hardly the first people using an x though:  https://www.google.com/search?q=stop+icon&source=lnms&tbm=isch&sa=X&biw=960&bih=1018

**Comment by hrwebasst** [comment]
Square in octagon sounds good, It just gives me pause as it is and I wait for the alt text which makes me feel others would do the same.

**Comment by deniseschannon** [comment]
In v0.49.1, the stop has changed to a square in the octagon.
