### ISSUE TITLE
Monitoring v2 - namespce `cattle-monitoring-system` is left after uninstalling

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28864]
**What kind of request is this (question/bug/enhancement/feature request):**
bug? 
Not sure if it is a bug or the design, so open this issue for tracking it. 

When uninstalling the monitoring v2, the ns `grafana-dashboards` and `grafana-datasources` are removed, but the ns `cattle-monitoring-system` is preserved.

**Comment by aiyengar2** [comment]
This is expected for `rancher-monitoring` since the default behavior of the chart is to leave the Alertmanager Secret behind `cattle-monitoring-system` namespace (re: https://github.com/rancher/charts/pull/637) in order to avoid destroying a user's alerting configuration on uninstall.

However, the `grafana-dashboards` and `grafana-datasources` are chart resources so they are expected to be removed.

Closing out this issue.
