### ISSUE TITLE
Graph view needs scrollbar when bringing up Summary View

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2889]
Version - Master 12/2

Steps:
1.  Create a Stack with a few services that are linked together
2.  Go to Graph view
3.  Click on a service name

Results:
The Summary view comes up, but some of the services are hidden by it and there is no scrollbar that comes up so I can get to them
![image](https://cloud.githubusercontent.com/assets/11514927/11568444/4795e7ac-99a9-11e5-8437-7bf81d0e0205.png)

Expected:
Scrollbar so I can access other services.

**Comment by westlywright** [comment]
@tfiduccia a scroll bar does not really make sense here because the graph view allows you to zoom in and out using the scroll wheel on your mouse along with being able to drag and drop. If we added a overflow to the graph view you still would not be able to scroll with out grabbing the scroll bar with your mouse. What im looking at doing is adjusting the zoom of the graph so your graph items are all viewable but on small screens if we go much below a scale factor of 1 the graph items are so small they are illegible.
