### ISSUE TITLE
Don't include unhealthy containers only to A records on DNS; but propagate even unhealthy records to the top level "client" section

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2890]
Unhealthy container shouldn't be discoverable to other containers in the stack, but it itself should be able to discover others.

**Comment by sangeethah** [comment]
Tested with latest build from master - Dec 3:

Had a service - S1 which has containers stuck in "Initializing" state (because of incorrect health check).
Had another service - S2 in the same stack.

From containers of service -S2 , S1 does not resolve.
From containers of service -S1 , S2 resolves to containers in the stack.

Upgraded S1 and correct healthcheck parameters. After this I , From containers of service -S2 , S1 resolves.

**Comment by sangeethah** [comment]
Had a service - S1 which has containers stuck in "Initializing" state (because of incorrect health check).
Had another service - S2 in different stack which has a link to S1.

From containers of service -S2 , S1 does not resolve by link name.

Upgraded S1 and correct healthcheck parameters. After this I , From containers of service -S2 , S1 resolves.

**Comment by deniseschannon** [comment]
@tobowers FYI, the DNS issue that you reported will be fixed in the next release.

**Comment by tobowers** [comment]
Thank you!

**Comment by m4ce** [comment]
Hi,

I would like to know what will be the final logic behind the DNS resolution when it comes to health checks.

Right now, it seems that container-level DNS records (e.g. stack_service_id.rancher.internal) are not available for instances that are in initializing/unhealthy states.

I believe the logic should be a bit different. If a service has health checks configured, then only the healthy onces are made available in the stack_service.rancher.internal round-robin DNS A record. 

However, each container should still get its own A record independently from the health check failing or not. There are applications that require the DNS to be resolvable upon starting up, and that happens before the health check can transition to healthy.

Cheers,
Matteo

**Comment by deniseschannon** [comment]
>"If a service has health checks configured, then only the healthy instances are made available in the stack_service.rancher.internal round-robin DNS A record."

This is how it works today.

If service foo has foo_1 healthy and foo_2 unhealthy, service foo is resolvable and the resolution would be the foo_1 container. 

> However, each container should still get its own A record independently from the health check failing or not. There are applications that require the DNS to be resolvable upon starting up, and that happens before the health check can transition to healthy.

When service foo is still in initializing state, it can still resolve other services in Rancher, but not itself. This should get fixed. I've opened up this issue for it. https://github.com/rancher/rancher/issues/3576
