### ISSUE TITLE
Update RIO Chart annotations

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28948]
Need to make sure RIO can deploy, if not need to remove the chart from Dashboard.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/charts/pull/660

**Comment by izaac** [comment]
Rancher version: `master-head (09/18/2020)` _8fd81a9b46847317a95ab654ae58053787d57687_
`rio-0.8.000` <== from Dashboard Apps.

Rio controller is in Error state:

`InvalidImageName: Failed to apply default image tag ":": couldn't parse image reference ":": invalid reference format`


![Screen Shot 2020-09-18 at 10 58 18 AM](https://user-images.githubusercontent.com/27659/93629885-e1b2e200-f99d-11ea-8eb2-543297058a76.png)

**Comment by cbron** [comment]
We also need to ensure everything from helm chart requirements doc is added to Rio chart.

The ones needed I see are: 

* default-system-registry: https://github.com/rancher/charts/blob/dev-v2.5/packages/rio/charts/templates/deployment.yaml#L36 
* use repository and tag for image
* User RBAC for kube aggregation roles. This one actually perhaps we don't need because there are no CRDs.

**Comment by StrongMonkey** [comment]
@izaac Not sure why there is no tag. When you deploy rio, do you see the values.yaml in the UI? This happens when you deploy Rio with an empty values.yaml. I didn't see this in recent master.

**Comment by StrongMonkey** [comment]
@izaac Can you re-test it? I tested on the latest master it is working for me

**Comment by izaac** [comment]
Rancher version `master-head (09/21/2020)` _f1a410a_

I was able to deploy rio after deploying `rancher-monitoring` and `rancher-istio`

Local HA k8s and downstream DO RKE clusters.
