### ISSUE TITLE
Monitoring v2 - Grafana cannot connect to Prometheus in GKE cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28941]
**What kind of request is this (question/bug/enhancement/feature request):**
bug 

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`master-01c13f69cb277e037f6d58323cb0859300e8af5d-head` HA mode 
- provision a GKE cluster 
![image](https://user-images.githubusercontent.com/6218999/93397060-9f6a9300-f82d-11ea-8d4a-e11e899d2cdb.png)
- go to dashboard -> apps -> install monitoring v2 

**Result:**
- the monitoring app is installed successfully 
- but Grafana cannot show any graphs, and it turns out it cannot connect to the Prometheus service, the connection test fails

![screencapture-34-122-41-224-31342-datasources-edit-1-2020-09-16-14_49_06](https://user-images.githubusercontent.com/6218999/93397141-d6d93f80-f82d-11ea-9ccf-6f6658e09513.png)
 

**More info:**
This does NOT happen for AKS or EKS.

**Comment by aiyengar2** [comment]
I've been doing some investigation into this issue using the cluster specified by this ticket; it seems like the root cause of this is that the Grafana pod is unable to use `kube-dns` in order to resolve the `http://rancher-monitoring-prometheus:9090` address.

Following the guide to [Debug Services](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#is-the-kube-proxy-working) on the Kubernetes doc, I exec-ed into the Grafana pod and tried to execute the following:
```shell
/usr/share/grafana $ nslookup kubernetes.default
;; connection timed out; no servers could be reached
```

This seems to potentially imply that the Kubernetes master service is not working within the cluster.

**Comment by aiyengar2** [comment]
I created a new GKE cluster using version `v1.17.9-gke.1504` and I was unable to reproduce this issue; the connection test is successful.

![Screen Shot 2020-09-17 at 3 05 42 PM](https://user-images.githubusercontent.com/13127443/93533200-42d3aa80-f8f7-11ea-9f60-8fe75b0ed6ed.png)

**Comment by jiaqiluo** [comment]
Tried the following 2 GKE clusters in the latest rancher:`master-bcc8261487ecdd37761fc7a010950e4cffd40874-head` and the connection test is successful 

- v1.16.13-gke.401
- v1.17.9-gke.1504


@aiyengar2 It looks like there might be something wrong on the GKE side at that time, and I think we don't need to do anything.
