### ISSUE TITLE
[Monitoring V1 UI] Prevent deploy when Prometheus Operator already exists

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29006]
This is the equivalent of https://github.com/rancher/dashboard/issues/1167 that needs to be backported to Monitoring V1's UI experience as well. Users should be warned or prevented when deploying Monitoring V1 onto a cluster where a Prometheus Operator is deployed.

For more context, see the original ticket.

**Comment by jiaqiluo** [comment]
The enhancement is validated on mater-head ec04f78 with the latest UI 

Instead of preventing users from installing monitoring v1 when v2 is installed, Rancher shows a warning message on the cluster monitoring page 

when the namespace `cattle-monitoring-system` does not exist in the cluster
<img width="1428" alt="Screen Shot 2020-09-29 at 5 49 07 PM" src="https://user-images.githubusercontent.com/6218999/94631067-4d3d5f00-027c-11eb-9107-249275d3c1b8.png">

when the namespace `cattle-monitoring-system` is created  in the cluster
<img width="1413" alt="Screen Shot 2020-09-29 at 5 49 22 PM" src="https://user-images.githubusercontent.com/6218999/94631083-59c1b780-027c-11eb-8cb9-83811464fd6f.png">

**Comment by jiaqiluo** [comment]
This issue is reopened because of the following 2 reasons:
1. the link of the `deprecated` word is broken (404 error): https://rancher.com/docs/rancher/v2.x/en/reference/deprecation

2. The warning in the project monitoring does not change when the namespace `cattle-monitoring-system` exists in the cluster. Can we make it behave the same as the cluster monitoring page? 

<img width="1416" alt="Screen Shot 2020-09-29 at 5 56 03 PM" src="https://user-images.githubusercontent.com/6218999/94631361-187dd780-027d-11eb-8e8d-5320d6e79deb.png">

**Comment by westlywright** [comment]
@jiaqiluo Im adding the warning to the project page now. The link tot he docs is not published yet and will not go live until 2.5 drops so it is going to 404 until then. I dont think that should block the ticket.

**Comment by jiaqiluo** [comment]
the bug fix is validated in rancher:master-head 2ae933e 

Now the warning in the project monitoring page changes depends if the namespace `cattle-monitoring-system` exists or not 

![image](https://user-images.githubusercontent.com/6218999/94737167-3e10ec80-0322-11eb-9b19-e582b1a5ddc3.png)


![image](https://user-images.githubusercontent.com/6218999/94736943-e5d9ea80-0321-11eb-9f2c-0378906e693e.png)
