### ISSUE TITLE
Monitoring v1 - field spec.baseImage is deprecated

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29052]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
- on rancher:`master-f1a410a97e2abf8c81c62195a7b40f10007398f0-head` single install
- provision a DO cluster 
- enable both cluster monitoring and project monitoring  `0.1.3`
- check the logs of the workload `prometheus-operator-monitoring-operator`

**Result:**
one warning for cluster monitoring 
```
level=warn ts=2020-09-21T17:37:56.361593244Z caller=operator.go:1199 component=prometheusoperator msg="prometheus key=cattle-prometheus/cluster-monitoring, field spec.baseImage is deprecated, 'spec.image' field should be used instead"
```
one for project monitoring 
```
level=warn ts=2020-09-21T17:55:36.333089962Z caller=operator.go:1199 component=prometheusoperator msg="prometheus key=cattle-prometheus-p-src8w/project-monitoring, field spec.baseImage is deprecated, 'spec.image' field should be used instead"
```
 

similar issue https://github.com/rancher/rancher/issues/27289

**Comment by aiyengar2** [comment]
Already addressed in https://github.com/rancher/system-charts/pull/330. 

This might be a duplicate of https://github.com/rancher/rancher/issues/27289 since that ticket already has us update `spec.baseImage` as part of fixing the first log statement in the `Result` section.

Project monitoring should also be fixed since both cluster and project monitoring use the same underlying chart with different `values.yaml`.

**Comment by jiaqiluo** [comment]
This does not happen after refrshing the repo and reintall the monitoring app. 
The issue can be closed.
