### ISSUE TITLE
[UI] Update default Oracle Linux Version (OL 7.7 is purged) in OCI driver (2.4 branch)

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#29096]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**

For OCI Driver:
1. Open your Node Templates in Rancher UI
2. Add a new Template and Select Oracle Cloud Infrastructure
3. In the Image drop-down list, notice that "Oracle Linux 7.8" is not listed.

**Result:**
Provisioning an OCI cluster with "Oracle Linux 7.7" fails due to error "Oracle Linux 7.7" image is not found.

**Other details that may be helpful:**

We shouldn't need to make these types up manual updates if the [PR](https://github.com/rancher/ui/pull/3952) to fetch values like these was back-ported to the 2.4 branch. 

**Environment information**
- Rancher version: v2.4.8 (using rancher/rancher:latest)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:2.4.8`

Steps:
Create a node template for Oracle Cloud Infrastructure
See Oracle-Linux-7.7 as the only default option
![Screen Shot 2020-10-07 at 2 43 11 PM](https://user-images.githubusercontent.com/57409052/95391878-ae80b600-08ac-11eb-959c-688615fa010c.png)
Create a cluster using the node template

Result:
Cluster creation fails with: 
`Error with pre-create check: "could not retrieve image id for an image named Oracle-Linux-7.7"; Timeout waiting for ssh key`
![Screen Shot 2020-10-07 at 2 50 45 PM](https://user-images.githubusercontent.com/57409052/95391872-ac1e5c00-08ac-11eb-9169-5034e89ea1c0.png)

**Comment by aaronRancher** [comment]
The bug is seen with Rancher server `rancher\rancher:2.4-head` `version eb990af`

Steps:
Create a node template for Oracle Cloud Infrastructure
See Oracle-Linux-7.8 as the only default option
![image](https://user-images.githubusercontent.com/57409052/95399606-64540080-08bd-11eb-923b-9d089ac5addd.png)
Create cluster using the node template

Result:
Cluster creation fails with:
`Error with pre-create check: "could not retrieve image id for an image named Oracle-Linux-7.7"; Timeout waiting for ssh key`
![Screen Shot 2020-10-07 at 4 38 56 PM](https://user-images.githubusercontent.com/57409052/95399538-3e2e6080-08bd-11eb-9653-a2029681c66e.png)

**Comment by aaronRancher** [comment]
Reopening for a fix as well as one in `2.5-head` and `master-head`.

**Comment by deniseschannon** [comment]
@aaronRancher Can you make a separate issue for 2.5/master? 

There should be 1 issue for 2.5/master and 1 for 2.4.

**Comment by jlamillan** [comment]
Anything I can do to help? 

`HEAD` on the [2.4-fixes](https://github.com/rancher/ui/blob/2.4-fixes/lib/nodes/addon/components/driver-oci/component.js#L56) branch already has the fix. 

[master](https://github.com/rancher/ui/blob/master/lib/nodes/addon/components/driver-oci/component.js) and [2.5-fixes](https://github.com/rancher/ui/blob/2.5-fixes/lib/nodes/addon/components/driver-oci/component.js) no longer maintains a static map for these types of values and instead pulls them in _dynamically_.

**Comment by deniseschannon** [comment]
@jlamillan Did this work on your test environment? It's not working in our QA environment and still pulling the wrong ID.

**Comment by jlamillan** [comment]
Out of the box, the `v2.4.8` node template wizard only offers `Oracle Linux 7.7`.

I have to update the the `ui-index` setting (from local) to `https://releases.rancher.com/ui/latest-2.4/index.html` to pick up the UI fix from the [2.4-fixes](https://github.com/rancher/ui/blob/2.4-fixes/lib/nodes/addon/components/driver-oci/component.js#L56).

**Comment by aaronRancher** [comment]
The dynamic fetch from OCI API fix for `2.5-head` and `master-head` was done in this issue: https://github.com/rancher/rancher/issues/27051

From the dropdown value perspective, this has been fixed. Unfortunately we are still seeing the same error when trying to provision a cluster with `Oracle-Linux-7.8`. We will track the error specifically in this issue: https://github.com/rancher/rancher/issues/29503

Will close this issue once we are able to provision a healthy cluster with OL 7.8.

**Comment by jlamillan** [comment]
Yeah, it's a little confusing. 

Even when the UI offers `Oracle-Linux-7.8`, version `1.0.0` of the [Docker machine driver for OCI](https://github.com/rancher-plugins/rancher-machine-driver-oci) does _an explicit look up_ of the `Oracle-Linux-7.7` image ID in its  `PreCreateCheck()`, which is the root cause of the `Error with pre-create check` above.

[Updating the driver](https://github.com/rancher/rancher/pull/29505) to `v1.0.1` _in combination_ with the UI populating `Oracle-Linux-7.8` will resolve the issue.

**Comment by aaronRancher** [comment]
Closing issue, as cluster can be provisioned with the correct version. Tracked in this issue: https://github.com/rancher/rancher/issues/29503#issuecomment-708765091
