### ISSUE TITLE
Unable to integrate Keycloak SAML SSO when Client ID field is reserved

### ISSUE THREAD

**Issue by joshrwolf** [rancher/rancher#29212]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement

**Steps to reproduce (least amount of steps as possible):**

Configure Keycloak (SAML) within Rancher, but do not set the `Client ID` filed as the required `https://yourRancherHostURL/v1-saml/keycloak/saml/metadata`.

**Result:**

Rancher fails to test authentication with keycloak, returning "Access was not authorized".  

**Other details that may be helpful:**

Users with reserved format/entries for Keycloak `Client ID`s are unable to set up Keycloak SAML because the saml metadata endpoint is parsed from the client ID.  Adding the metadata endpoint as a separate field, or reconstructing it from the existing `Rancher API Host` field would allow for generic `Client ID`s.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

**Comment by mrajashree** [comment]
As per Keycloak docs,
```
Client ID: This value must match the issuer value sent with AuthNRequests. Keycloak will pull the issuer from the Authn SAML request and match it to a client by this value.
```
When setting up Keycloak with Rancher, the rancher metadata URL will be the issuer for AuthNRequests. So I don't think it can be changed.

**Comment by joshrwolf** [comment]
I think it would have to be a change with how rancher is constructing the issuer from the `Rancher API Host` (`https://${rancherAPIHost}/v1-saml/keycloak/saml/metadata`).  Instead, providing a user defined field for `issuer` (or the expected sp entity id) would allow for non standard `clientIDs`.  This seems to be a common option amongst other tools supporting SAML.

**Comment by mrajashree** [comment]
Will move this to test once [this](https://github.com/rancher/rancher/issues/29553#issuecomment-710682731) is fixed

**Comment by izaac** [comment]
I validated this configuration and included some P1s checks after enabling Keycloak auth.

- Rancher version: `master-head (10/19/2020)` _e4dc25135_
- Rancher version: `v2.5-head (10/19/2020)` _52583ea7a_


First I enabled Keycloak in Rancher by using the same configuration settings as documented in the docs, and leaving the Entity ID Field blank so that Rancher will generate one automatically. Then checked users auth and site access.


Then I proceeded to build a setup with a custom `Client ID`. Client ID is how Keycloak names this field in the Clients settings. Rancher UI shows it as Entity ID Field.

![Screen Shot 2020-10-19 at 5 22 40 PM](https://user-images.githubusercontent.com/27659/96525472-e2a29200-122f-11eb-821a-911e5be5abd5.png)

![Screen Shot 2020-10-19 at 5 24 24 PM](https://user-images.githubusercontent.com/27659/96525508-f817bc00-122f-11eb-8b6f-6be2c06b447b.png)


If I set this to an unknown Client ID I get an error as expected in the Login page:

![Screen Shot 2020-10-19 at 4 57 23 PM](https://user-images.githubusercontent.com/27659/96525528-0b2a8c00-1230-11eb-91f7-8850d659ee6f.png)




After that I executed the same checks for users and site access. Both `v2.5-head` and `master-head` worked.
