### ISSUE TITLE
Cluster monitoring link takes the user to a 503 ClusterUnavailable page when the cluster is still provisioning.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29234]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Provision a cluster
- While it's still in provisioning state click in Cluster -> Tools -> Monitoring

![Screen Shot 2020-09-29 at 9 09 13 AM](https://user-images.githubusercontent.com/27659/94585573-0c6e2780-0235-11eb-947c-38700fa9b446.png)

**Result:**

![Screen Shot 2020-09-29 at 9 09 03 AM](https://user-images.githubusercontent.com/27659/94585466-e6e11e00-0234-11eb-985f-bd383161f4c1.png)

**Environment information**
- Rancher version: `master-head (09/29/2020)` _ec04f78_ 
- Installation option: HA k8s with GKE downstream cluster

**Comment by izaac** [comment]
In v2.4.5 i don't see this error.
![Screen Shot 2020-09-29 at 9 54 49 AM](https://user-images.githubusercontent.com/27659/94589271-ee56f600-0239-11eb-9e56-339e74892277.png)

**Comment by westlywright** [comment]
@izaac At somepoint the api started returning a 503 for `clusters/<cluster-id>/namespaces` which is the root of the problem I believe. I think there may be some regression on the backend because I feel like even though the cluster is not ready we could return an empty response with out 503'ing. But there may be some technical reason the backend is now doing this that I am unaware of. I think this or another ticket should be kicked over to backend to figure out why its 503'ing and if that error is the expected behavior? Regardless I have a PR in review for this and it will utilize a check we have built into the header nav, `monitoring` will only show when the cluster is active. Additionally I've change some logic for the Istio link as well. It will follow the same pattern and not display until the cluster is active. Prior to this change the istio link would redirect you back to the cluster index page, it was actually kind of confusing at first. Because both the pages are custom pages with no list of resources similar to say alerts I think this makes sense. Monitoring and Istio are pretty useless when the cluster is not Active so why even show the links in my opinion.

**Comment by izaac** [comment]
@westlywright thanks for the thorough explanation, I will check the fix.

**Comment by izaac** [comment]
Rancher version `v2.5-head (03/16/2021)` _868c715_
Rancher version `master-head (03/18/2021)` _b0d3575_

Used Administrator and Standard user accounts.

Cluster types checked:

- RKE
- Custom
- GKE

During provisioning:

![Screen Shot 2021-03-18 at 4 27 53 PM](https://user-images.githubusercontent.com/27659/111712898-c9683680-880b-11eb-9118-52f6777c3d85.png)

After Provisioning: 
![Screen Shot 2021-03-18 at 4 39 35 PM](https://user-images.githubusercontent.com/27659/111712891-c8370980-880b-11eb-9be3-20066b2e9d7d.png)
