### ISSUE TITLE
Nginx-ingress does not uses default configmap (nginx-configuration)

### ISSUE THREAD

**Issue by albertocrj** [rancher/rancher#29233]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug (I think)

**Steps to reproduce (least amount of steps as possible):**

Check if there's any arg in contairners spec mapping to the configmap

kubectl get daemonset.apps/nginx-ingress-controller -n ingress-nginx -o=json | jq '.spec.template.spec.containers[0].args'

**Result:**
Returns me nothing

**Other details that may be helpful:**
nginx image: nginx-ingress-controller:nginx-0.25.1-rancher1

Found out because I needed to set enable-underscores-in-headers to true in nginx config. After modify the nginx configmap "nginx-configuration" nothing happens.

I had to modify my daemonset and add args mapping to this config map:
kubectl patch daemonset.apps/nginx-ingress-controller -n ingress-nginx --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args", "value": ["/nginx-ingress-controller", "--configmap=$(POD_NAMESPACE)/nginx-configuration"]}]'

After that, I was able to enable this config and the it's applied to my nginx pods:
kubectl patch configmap nginx-configuration -n ingress-nginx --type merge -p '{"data":{"enable-underscores-in-headers":"true"}}'

Is that an expected behavior? Is there another way to modify this kind of config?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
If it returns nothing, something else is going on as even if it is missing that arg, there are a few others that are configured. The templates used to deploy nginx-ingress all have the configmap arg so we need a bit more info on this. Was this a newly created cluster in 2.4.3 or upgraded, if upgraded, from what version? And do you have logs from the creation/provisioning/upgrading of this cluster so we can try to root cause why this happened? Does it occur as well if you create a new cluster in this Rancher setup?

**Comment by superseb** [comment]
Let me know if we still need to investigate this.
