### ISSUE TITLE
Migrating alerts/dashboards from monitoring v1 to v2

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29235]
https://github.com/bashofmann/rancher-monitoring-v1-to-v2

The dashboards script will take all dashboards from a v1 Grafana, either from the cluster monitoring or from a project monitoring and create ConfigMaps that you can create in a cluster with v2 monitoring.
The alerts will take all user generated metrics based rules from the cluster alerting or from a project alerting and create PrometheusRules that you can create in a cluster with v2 monitoring.
Non metrics based rules are not migrated since all these cases are already covered already by the default rules shipping with v2.

Need to validate the scripts, migrate over to rancher and add it in docs and support KB.

**Comment by aiyengar2** [comment]
Thank you @bashofmann for the awesome contribution! I tried using these scripts on an existing cluster and they work great. However, I had a couple of thoughts on the scripts.

## Dashboards

### Concerns

#### Cluster Dashboards

*Question: Does it make sense to import dashboards that already have equivalents in V2 feature charts (e.g. default dashboards) or should we introduce a flag that requires a user to specifically turn it on to import those dashboards?*

- [x] Yes, because the user is introducing two sets of dashboards that encode the same information. The purpose of the script should only be to migrate user-added dashboards since we want users to switch to using Monitoring V2 / Feature V2 default dashboards. A user should be able to choose to import those dashboards via a flag, but the default should encourage them to use the new dashboards and, if any specific dashboards are missing, they should be encouraged to ask us to open an issue to introduce those dashboards to Monitoring V2 / Feature V2 instead.
- [ ] No, because there is slightly different information / a slightly different layout encoded in Monitoring V1 dashboards that a user who is migrating would be more familiar with. We should let them keep those by default.

####  Project Dashboards

*Question: Does it make sense to import the default dashboards that are also found on a cluster level?*
- [x] No, because all the default dashboards deployed for Projects are already found on a cluster level (see table below). The reason why this encoded different information in the past was because the Project Grafana pointed to a completely different Project Prometheus, which was collecting different data than the Cluster Prometheus (metrics only specific to the project it was in). However, in Monitoring V2, we only have one (Cluster) Prometheus, so these dashboards no longer serve any purpose on a project level.

*Question: Does it make sense to [pre-pend the project name](https://github.com/bashofmann/rancher-monitoring-v1-to-v2/blob/c1e8b9f7536fd1646cdd69d0490f80035717f50c/migrate_dashboards.py#L70) in the title of the dashboard?*
- [x] No, because ConfigMap-based dashboards are supposed to be cluster-agnostic. We shouldn't introduce dashboards that rely on a specific project name since those won't be exportable to other cluster and don't fit into the Monitoring V2 expectation that there is just one (Cluster) Prometheus.

### PR with proposed fixes

https://github.com/bashofmann/rancher-monitoring-v1-to-v2/pull/1

### Context

The current script migrates the following default Dashboards for Monitoring:

Dashboard Name | Cluster or Project | Dashboard Exists in Monitoring V2?
---|---|---|
StatefulSet | Cluster / Project | Yes, slightly modified with modified panels
Etcd | Cluster | Yes, slightly modified with different panels
Pods | Cluster / Project | Yes, slightly modified with different panels
Cluster | Cluster | Yes, but missing several panels
Kubernetes Components | Cluster | Yes, but missing panels like `Nginx Ingress Request Rate`
Nodes | Cluster | Yes but missing panels like `Used Root FS`
istio | Cluster | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Citadel Dashboard | Cluster | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Galley Dashboard | Cluster | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Mesh Dashboard | Cluster | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Mixer Dashboard | Cluster | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Performance Dashboard | Cluster | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Pilot Dashboard | Cluster | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Service Dashboard | Cluster / Project | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Istio Workload Dashboard | Cluster / Project | Yes, but this is [introduced by Istio](https://github.com/rancher/istio-installer/pull/13)
Rancher Components (FluentD) | Cluster | No, but should be introduced by Logging
DaemonSet | Cluster / Project | No
Deployment | Cluster / Project | No
Kubernetes Resource Requests | Cluster | No

These dashboards have rough equivalents in Monitoring V2, such as for StatefulSets as show in the screenshots below:

![Screen Shot 2020-11-03 at 12 06 13 PM](https://user-images.githubusercontent.com/13127443/98035203-f96aec00-1dcc-11eb-8764-43fbd987a9d3.png)

![Screen Shot 2020-11-03 at 12 06 22 PM](https://user-images.githubusercontent.com/13127443/98035230-0091fa00-1dcd-11eb-8a2c-df749b4ffa47.png)

But there are certain panels that exist in V1 that don't exist in V2 such as:

![Screen Shot 2020-11-03 at 12 02 40 PM](https://user-images.githubusercontent.com/13127443/98034849-7ba6e080-1dcc-11eb-871f-db2348cd1aaa.png)

## Rules

### Concerns

The current set of scripts only migrates the PrometheusRules, but ideally we should migrate the Alertmanager Config Secret stuff as well so that the user's entire Alerting configuration can be migrated over to Monitoring V2. This secret exists in the `cattle-prometheus` namespace in the system project and requires modifications.

Also, I think the script needs to be modified to just get all the PrometheusRules from your cluster (from all projects) rather than just the ones that you supply via command-line arguments since it should be one command that you run that generates the Alertmanager Config Secret for your entire cluster as well.

### PR with proposed fixes

https://github.com/bashofmann/rancher-monitoring-v1-to-v2/pull/2

**Comment by jiaqiluo** [comment]
The validation for the `migrating alerts` part is done.
- the namespace `cattle-monitoring-system` is included
- the secret `alertmanager-cluster-alerting` is included
- the receiver is included when 
	- it is NOT webhook-config based 
	- it is used by at least one PrometheusRule 
- the PrometheusRule is included when 
	- it is created by the user
	- it has a receiver assigned 
	- at least 1 of its rule uses metrics 
- the Rule is included when 
	- it uses metris

**Comment by jiaqiluo** [comment]
The validation for the `migrating dashboards` part is done.
The following dashboards can be exported by the script:
- the default dashboards on the cluster Grafana 
- the istio dashboards on the cluster Grafana
- the user-created dashboards and folders on both the cluster Grafana and the project Grafana 

The output yaml file can be applied into the cluster with Monitoring v2 enabled, and dashboards show up on the Grafana.

**Comment by jiaqiluo** [comment]
reopen the issue to wait for this PR to be merged: https://github.com/bashofmann/rancher-monitoring-v1-to-v2/pull/4

**Comment by jiaqiluo** [comment]
Validation is done.
