### ISSUE TITLE
Istio custom answers don't stay visible in UI and don't persist subsequent saves

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#29247]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. enable istio and save
2. edit istio and add `istio_cni.enabled: true` as a custom answer, hit save
3. refresh, notice the custom answer doesn't exist

**Result:**

The answer will be applied to the current running cluster-istio app. However, if I were to go back and hit save again, the answer will be gone in the app as well.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): either

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, but doesn't matter
- Kubernetes version (use `kubectl version`): v1.18.8-rancher1-1

gz#12505

**Comment by sadiapoddar** [comment]
Reproduced the issue with 2.4.8 
steps.

1. Created a cluster
2. Enabled istio and saved
3. Edited "Custom Answer" and 
4. enter the following key: value pair

 istio_cni.enabled: true 
5. Saved

<img width="1281" alt="Screen Shot 2020-11-19 at 4 00 32 PM" src="https://user-images.githubusercontent.com/72409237/99739375-7bbc0700-2a81-11eb-8887-c38e3ff1e292.png">

Refreshed the page and the custom answer is not  there anymore

<img width="1271" alt="Screen Shot 2020-11-19 at 4 01 15 PM" src="https://user-images.githubusercontent.com/72409237/99739399-8b3b5000-2a81-11eb-9eba-6af25308ff79.png">

Additional information which could be helpful
I added a number of custom answers,  seeing only the "istio_cni.enabled: true" value disappears after the refresh, all other answers remain as saved. 
<img width="1310" alt="Screen Shot 2020-11-19 at 4 21 51 PM" src="https://user-images.githubusercontent.com/72409237/99740435-de160700-2a83-11eb-87a4-b6e805c3573b.png">
 
After refresh
<img width="1233" alt="Screen Shot 2020-11-19 at 4 22 10 PM" src="https://user-images.githubusercontent.com/72409237/99740451-e8d09c00-2a83-11eb-8a05-5419e7ae85e9.png">

**Comment by westlywright** [comment]
`istio_cni` is not saved because it belongs to an object in the code that is specifically set to hidden. If you were to look at the api object for this app you can see the param is still saved. I do see the bug where the custom answer is overwritten on the second save.  I am not quite sure why this value is hidden though? @loganhz I know its been ages since this was written but do you have any thoughts on why these values are hidden?

**Comment by maggieliu** [comment]
@guangbochen can you please take a look at @wes's question?

**Comment by guangbochen** [comment]
after checked with @n313893254 he has confirmed those values are added by design to ensure the `istio` can be enabled successfully, for example, there are some [pre-requestites](https://istio.io/latest/docs/setup/additional-setup/cni/#prerequisites) which are needed for success enable the `istio-cni` and only set `istio_cni.enabled: true` will not work if those prerequisites are not configured correctly, therefore they have enforced those configurations from the UI side.

However, this is arguable and I think we should allow the user to do more advanced configuration and resolve them manually if needed.

**Comment by anupama2501** [comment]
<h4>Reproduced the issue on v2.5.6</h4>
Istio version: 1.5.901 

- Create a cluster with 3 worker,1etcd and 1 control plane
- Enabled monitoring[0.21] and enabled istio[1.5.901]
- Custom answers are hidden. After editing istio and adding cni_enabled=true, it was hidden on UI

<h4>Verified the issue on v2.5-51253e556b6cc3d9b285b559c4ff043e2301d687-head</h4>

Upgraded the cluster to v2.5-51253e556b6cc3d9b285b559c4ff043e2301d687-head
Custom answers are visible on the UI cluster --> istio --> custom answers

- From the custom answers, added istio_cni=enabled and saved.
- Refreshed the key and the value is shown 
- Changed the value to false and the value is shown as set.
- Deleted the key istio_cni.enabled=true, the value is removed from the custom_answers
