### ISSUE TITLE
[Logging v2] - Can't access the Logging Overview as Cluster Member

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29250]
I am able to access the Logging Overview as Cluster Owner, Project Owner and Project Member.

But he Logging App link is not shown for Cluster Member

![Screen Shot 2020-09-28 at 6 53 51 PM](https://user-images.githubusercontent.com/27659/94504060-bfe70580-01bc-11eb-9653-7a8d07e6aa81.png)

Rancher version: `master-head (09/28/2020)` _ec04f78_ HA k8s with Downstream DO RKE cluster

**Comment by deniseschannon** [comment]
@paynejacob This is a backend issue as the schema doesn't exist for the cluster member which is driven by the API.

**Comment by vincent99** [comment]
The dashboard decides what products to show based on what schemas are available.  So specifically in this case, the user doesn't have access to any schemas matching `[*.]logging.banzaicloud.io`.  i.e. they don't have any rolebindings to any roles which give them read access to anything in that api group.

**Comment by cbron** [comment]
This is just a casualty of our aggregated CR system. The cluster-member doesn't have any RoleBindings to access the logging operator NS, or any other NS. They can't list or create a workload in any NS, and don't aggregate to any default ClusterRole. This will happen for all of our features. Possible solutions include: 
* We could give it to them in ECM manually, because cluster-member is an ECM construct. But it sucks to implement and couple things in ECM to charts.
* We could use solution from #29168 and give `*` access on ClusterOutput to _everyone_ in cluster with a view-only CRB, but there are potential security concerns there, and only solves issue for logging.

**Comment by cbron** [comment]
> The direction for RBAC in dashboard is that we will add the ability to create project and user will need to create a project before having the ability to deploy apps. 

Close this ticket as it will be fixed as part of that work.
