### ISSUE TITLE
Admission webhook error when restricted admin attempts to create an Administrator user

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#29315]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher 2.5.0-rc4 (or master-1b0778b1ddde4f9786008d864dffd4d8c090cf82-head) with helm chart restrictedAdmin=true
2. Log in as admin.
3. Go to Security -> Users
4. Create a new user with "Administrator" checked in Global Permissions

**Result:**
Receive the error:
admission webhook "rancherauth.cattle.io" denied the request: user "user-ctqxw" (groups=["system:authenticated" "system:cattle:authenticated"]) is attempting to grant RBAC permissions not currently held: {APIGroups:["*"], Resources:["*"], Verbs:["*"]} {NonResourceURLs:["*"], Verbs:["*"]}

**Other details that may be helpful:**
This attempts to create a full admin which is not allowed from a restricted admin user. There is a new "Restricted Admin" role under Built-in, but it isn't obvious to a user that this needs to be used instead of Administrator.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
1b0778b

gzrancher/rancher#12793

**Comment by maggieliu** [comment]
There is a new role called "Restricted Admin" currently listed under "Built-in" and can we move that up to the "Global Permissions" section.

**Comment by dnoland1** [comment]
Not sure I'd say this is fixed. As a restricted admin, I see both Administrator and Restricted Administrator under Global Permissions. If I choose Restricted Administrator, the user is added, I can log in as that user, and user seems to have the permissions I would expect. However, if I choose Administrator, I get the same admission webhook error. The user still gets created, but I cannot log in with that user's login and password. That's not a great user experience.

**Comment by sangeethah** [comment]
Reopening this issue as per https://github.com/rancher/rancher/issues/29315#issuecomment-703006354

**Comment by vincent99** [comment]
Creating the user and the rolebinding are two separate API calls.
  - The user-id is random and server-generated so the user has to be created first.
  - You may or not haver permission to create the rolebinding(s) you ask for for that user.
  - We don't know (and aren't going to) in advance if you have the ability to assign "Administrator" (or any other role) is going to succeed or not in advance.
  - Currently if it fails there's no good way out, you can't edit the checkboxes and then hit save again because it tries to recreate the user.

We can fix the last part, you should see the error, be able to pick a different set of roles, and hit save again.  But there is no practical way to prevent the error from being seen or to only create the user if the rolebinding is also going to succeed.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head db350a6
rancher/rancher:master-head 6f96683

* Create a restricted admin as the global admin
* Login as the restricted admin
* Create a new user
  * The Restricted Admin role is listed in the Global Permissions section
* Select Administrator and create the user
* The webhook error should be shown
* Edit the user type to `Restricted Admin` and save
* UI shows the correct permissions when viewing the user
* Login as the new restricted admin
* User has the correct permissions

Cancelling the operation after getting the webhook error still creates the user but without any rolebindings (as expected due to separate API calls).
