### ISSUE TITLE
Add in support to limit k8s versions for system-charts

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29346]
Need to be able to restrict different chart versions based on k8s version. Example where this is needed is for Monitoring v1 chart. If we update the prometheus operator image to v0.39, the API is only supported in k8s 1.16. Given that 2.3 and 2.4 both still support k8s 1.15, this will cause problem.

**Comment by jiaqiluo** [comment]
Failed to validate the enhancement in rancher:`v2.5-7eb1792946639251f51bd109b630f9c1cf8940c2-head` single-install 
Steps:
- clone the rancher's system-chart https://github.com/rancher/system-charts
- create new Monitoring charts version `0.1.5` `0.1.6`
- add the following kubeVersion requirements to the charts
```
chart 0.1.5 - kubeVersion: >= 1.16.0 < 1.18.10
chart 0.1.6 - kubeVersion: >1.18.0
```
https://github.com/jiaqiluo/system-charts/commit/50831a799a2523b54ec7f2b521ad9b8e2d60021a
- in Rancher change the system-library to point to my repo and branch. 
![image](https://user-images.githubusercontent.com/6218999/97369781-cf647780-186a-11eb-9c86-6c825d49d2a7.png)
- Rancher's logs show the chart is updated
```
2020/10/27 22:34:59 [INFO] Updating global catalog system-library
2020/10/27 22:35:00 [INFO] Catalog sync done. 0 templates created, 1 templates updated, 0 templates deleted, 0 templates failed
```
- provision a cluster with k8s `v1.19.3`
![image](https://user-images.githubusercontent.com/6218999/97369868-ff137f80-186a-11eb-82ec-ab113c67eb46.png)

- go to the cluster monitoring page

results:
- It is expected to see the chart version `0.1.6` in the list but it does not show up 
![image](https://user-images.githubusercontent.com/6218999/97369977-3aae4980-186b-11eb-9a2e-8dd04ca67946.png)

**Comment by rmweir** [comment]
Constraints that includes spaces such as `>= 1.16.0 < 1.18.10` must be wrapped in quotes or they will not be properly parsed. Moving back to test.

**Comment by izaac** [comment]
Rancher version: `master-head (10/29/2020)` _d61a1a4_
Rancher version: `v2.5-head (10/29/2020)` _0465f04_

I created new charts for monitoring 0.1.5 and 0.1.6
Updated the system-chart repo url en branch to point to my fork https://github.com/rancher/system-charts and branch `k8stest` https://github.com/rancher/system-charts/compare/dev-v2.5...izaac:k8stest?expand=1

for 0.1.5 I set: `kubeVersion: ">=1.16.0 <1.18.10"` in `Chart.yaml`
for 0.1.6  I set : `kubeVersion: ">1.18.0"` in Chart.yaml
My downstream k8s cluster is v1.19.3
Make sure the `kubeVersion` is following the `semver` `ParseRange` expected format https://godoc.org/github.com/blang/semver

I still see the version listed in the Ember UI dropdown. This is expected and is being tracked in a separate issue here: https://github.com/rancher/rancher/issues/29774
![Screen Shot 2020-10-29 at 6 43 35 PM](https://user-images.githubusercontent.com/27659/97651115-789ca080-1a18-11eb-952e-8dc983f00137.png)

The expectation here was as the `0.1.5` chart version is not including clusters with k8s versions greater than 1.18.10 to not be able to install which is the observed behavior:

![Screen Shot 2020-10-29 at 6 50 07 PM](https://user-images.githubusercontent.com/27659/97651206-aaae0280-1a18-11eb-81ef-7eacb9ca0845.png)

I also checked my test version `0.1.6` was able to continue installation because `kubeVersion: ">1.18.0"` includes k8s 1.19.x
