### ISSUE TITLE
Monitoring v2 - failed to install in k8s 1.16 cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29395]
**What kind of request is this (question/bug/enhancement/feature request):**
bug 

**Steps to reproduce (least amount of steps as possible):**

Enable monitoring v2 in a 1.16.15 cluster in Rancher:v2.5.0-rc9  

**Result:**
`rancher-monitoring-crd` is installed, but the `rancher-monitoring` is failed to install 

here is the error message
```
Error: Prometheus.monitoring.coreos.com "rancher-monitoring-prometheus" is invalid: type: Required value
```

monitoring should create a CRD of the type Prometheus.monitoring.coreos.com but it does not

```
>  k get prometheuses.monitoring.coreos.com -A
No resources found
```

<img width="1322" alt="Screen Shot 2020-10-05 at 9 07 27 PM" src="https://user-images.githubusercontent.com/6218999/95158385-52088400-0750-11eb-983e-1d2395d831b0.png">

**Comment by aiyengar2** [comment]
Based on an initial investigation, it seems like this only impact `rancher-monitoring` and not `kube-prometheus-stack`. Also, based on the error statement, this could be related to an error in the open API validation of the CR that is generated by the `rancher-monitoring` chart.

It seems like this could be related to either [`ignoreNamespaceSelectors`](https://github.com/rancher/charts/blob/708b31e09020859c80bab923275217fbbf56eaa0/packages/rancher-monitoring/rancher-monitoring.patch#L1471-L1473) or, more likely, the way that we use `tpl` instead of `toYaml` in the [`containers`](https://github.com/rancher/charts/blob/708b31e09020859c80bab923275217fbbf56eaa0/packages/rancher-monitoring/rancher-monitoring.patch#L1480-L1483) field of the Prometheus spec.

**Comment by jiaqiluo** [comment]
The bug fix is validated in rancher:master-head 0dee1de with the latest monitoring chart `v9.4.201`

The monitoring chart `v9.4.201` is installed into a 1.16 cluster successfully. All components are working as expected. 

Also notice that the following change in the YAML file: the configmap is not a list anymore
 
<img width="514" alt="Screen Shot 2020-10-13 at 4 51 56 PM" src="https://user-images.githubusercontent.com/6218999/95927834-c35dbd80-0d74-11eb-9818-b3975c0681c2.png">

**Comment by zhcsyncer** [comment]
May directly in v2.5.1 update rancher-monitoring chart version As mentioned in #29420 ?

**Comment by aiyengar2** [comment]
> May directly in v2.5.1 update rancher-monitoring chart version As mentioned in #29420 ?

yes
