### ISSUE TITLE
[UI][EKSv2]: cannot add SSH key to new nodegroups

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#29431]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create cluster with nodegroup, nodegroup may or may not have ssh key
2. edit cluster and add a nodegroup

**Result:**
SSH key dropdown cannot be selected and shows N/A.
![image](https://user-images.githubusercontent.com/19376037/95371849-9b132200-088f-11eb-8853-ea01e75b646d.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master-e98728fdcdb57e30aeb36cd3ef58a565d5a03195-head

- UI version: 
vmaster-dev

**Comment by aaronRancher** [comment]
The bug is reproduced  Rancher server `rancher\rancher:master-head` `version 5ebc964` and `rancher\rancher:v2.5-head` `version db350a6`

Steps:
Create an EKS cluster
Leave SSH Key field blank when setting node group
![Screen Shot 2020-12-01 at 3 55 45 PM](https://user-images.githubusercontent.com/57409052/100814288-9a65ba80-33fe-11eb-9e28-42f19971891a.png)
Create cluster
Once cluster is provisioned, edit cluster

Result:
SSH key cannot be edited
![Screen Shot 2020-12-01 at 4 18 41 PM](https://user-images.githubusercontent.com/57409052/100814271-920d7f80-33fe-11eb-9936-95cf089622b1.png)
