### ISSUE TITLE
Unable to install rancher-monitoring using RancherOS

### ISSUE THREAD

**Issue by NaPs** [rancher/rancher#29447]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- In cluster explorer -> Apps & Marketplace
- Deploy rancher-monitoring chart

**Result:**

Chart deployment ends in failed state.

First time I noticed that the pod `pushprox-kube-etcd-client-xxx` was failing because /etc/kubernetes/ssl was empty. Using RancherOS the actual directory is `/opt/rke/etc/kubernetes/ssl`.

I fixed the chart values to use the right directory:

```
    rkeEtcd:
      clients:
        https:
          certDir: /opt/rke/etc/kubernetes/ssl
```

After that, the same pod is failing because of this error:

```
MountVolume.SetUp failed for volume "metrics-cert-dir-source" : hostPath type check failed: /opt/rke/etc/kubernetes/ssl is not a directory
```
(Note that I checked and this directory is actually existing on my nodes and contains various certificates)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): Single
- OS: rancheros 1.5.5

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by kidhasmoxy** [comment]
Hey just as an update I found a workaround for this issue. You'll run into it if you're running a host node on ROS (Rancher OS). You were on the right track with using the "/opt/rke" prefix, but there's this weird issue that I hit with the Rancher, ROS, RKE combination where you directory checks on volumes don't work if the directory is chmod to "600" and owned by root. 

I've run into this with other host volumes, it's like RKE kubelet doesn't have perms to access the folder but the pod will. 

The fix is to turn off the directory exist check. Here's an example from "Cluster Manager", but you can also change the daemonset definition directly in the yaml. 

![image](https://user-images.githubusercontent.com/37122/96581585-06a1ba00-12a8-11eb-9e6c-220122d43fa3.png)

**Comment by aiyengar2** [comment]
Closing this issue out in favor of https://github.com/rancher/rancher/issues/29447, which is the same underlying issue.
