### ISSUE TITLE
cluster monitoring failure on 2.4.7: The CustomResourceDefinition "podmonitors.monitoring.coreos.com" is invalid

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#29594]
V 2.4.7
k8s 1.18.8

operator-init-crds pod failed

The CustomResourceDefinition "podmonitors.monitoring.coreos.com" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[podMetricsEndpoints].items.properties[targetPort].anyOf[0].type: Forbidden: must be empty to be structural

Delete and redoing yields in the same

**Comment by benzman81** [comment]
same in v2.5.1 with k8s v1.19.3

**Comment by aiyengar2** [comment]
@superxor I'm closing this issue out in favor of https://github.com/rancher/rancher/issues/29348 since it seems to be the same underlying issue. As noted in https://github.com/rancher/rancher/issues/29348#issuecomment-708963326, this seems to be an issue with the Custom Resource Definition that is deployed itself.

**Comment by superxor** [comment]
This did not resolve the issue

**Comment by aiyengar2** [comment]
@superxor the linked issue is still open / unresolved, but it tracks the same bug.
