### ISSUE TITLE
[2.4] Add in support to limit k8s versions for system-charts

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#29647]
Backport of https://github.com/rancher/rancher/issues/29346

**Comment by cbron** [comment]
PR: https://github.com/rancher/rancher/pull/29866

**Comment by jiaqiluo** [comment]
this is validated on rancher:v2.5-head 23eee56

**Steps:**
- run rancher with passing the parameter `CATTLE_SERVER_VERSION`
```
docker run -d \
  --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -e CATTLE_SERVER_VERSION=2.4.11\
  rancher/rancher:v2.4-head
```
- add clusters with different k8s versions 

![image](https://user-images.githubusercontent.com/6218999/102943001-17230c00-4474-11eb-9d93-932ea6954c3a.png)

- edit the `system-library` to point to the following catalog
![image](https://user-images.githubusercontent.com/6218999/102946503-1becbd80-447e-11eb-8cb0-d8011bdf76d5.png)

```
repo:   https://github.com/jiaqiluo/system-charts
branch: k8s-limit
---

add two new versions for the rancher-monitoring chart:

for 0.1.4, no kubeVersion is set
for 0.1.5 I set: kubeVersion: ">=1.16.0 <1.18.10" in Chart.yaml
for 0.1.6 I set : kubeVersion: ">1.18.0" in Chart.yaml
```

- go to the cluster/project monitoring page, and here are the versions showing on each cluster 

k8s version | template version
------------| ---------------
v1.18.13| 0.1.4, 0.1.6
v1.17.14| 0.1.4, 0.1.5 
v1.16.15| 0.1.4, 0.1.5 
v1.15.12| 0.1.4

![image](https://user-images.githubusercontent.com/6218999/102946577-4f2f4c80-447e-11eb-9691-6d6e84b3e277.png)
![image](https://user-images.githubusercontent.com/6218999/102946591-5a827800-447e-11eb-9988-6fba12bf1f51.png)
![image](https://user-images.githubusercontent.com/6218999/102946609-6a9a5780-447e-11eb-98c4-f587cba35bd0.png)
![image](https://user-images.githubusercontent.com/6218999/102946623-784fdd00-447e-11eb-91bd-26ad1577f13c.png)

Note `0.1.4` shows in the list because the `kubeVersion` filed is not set in its chart.
