### ISSUE TITLE
Process started in UI container shell stays even after closing the UI

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#29667]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an app (Eg:leodotcloud/swiss-army-knife)
- Select the pod and connect to the shell from UI (Execute Shell )
- Execute "sleep 1000"
- Press the "Close button" of the UI shell
- Connect to the shell again 
- Do a "ps -ef |grep sleep" to see the process started earlier 

**Result:**

The process started in UI shell stays even after closing the UI shell causing unwanted/ untracked resource usage.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.1
- Installation option (single install/HA): HA

gz#12861

**Comment by maggieliu** [comment]
duplicated: https://github.com/rancher/rancher/issues/16192#issuecomment-526276609

**Comment by westlywright** [comment]
UI will send the exit command before the socket closes so the user doesn't need to end it themselves.

**Comment by sadiapoddar** [comment]
Verified the fix with 2.5-head, v2.5-71da1569f8e41947302d0a2708e707c249585b0b-head
Looks like the fix is sending exit when the shell is closed using UI's "close",
So, users don't need to explicitly send "exit" now, the fix does it for the users.
Verification Steps.
1. Invoked the workload shell 
2. Executed "ps -ef" command per invocation of the shell
3. Closed the shell
 Note that exit has sent on the shell for each close
<img width="805" alt="Screen Shot 2020-11-13 at 4 58 49 PM" src="https://user-images.githubusercontent.com/72409237/99134237-baf5de00-25d1-11eb-8d8b-2bbf46a93af7.png">

**Comment by ansilh** [comment]
hi @sadiapoddar , The issue is still present. 

It's reproducible with the below steps.

```
Select the pod and connect to the shell from UI (Execute Shell )
Execute "sleep 1000"
Press the "Close button" of the UI shell
Connect to the shell again
Do a "ps -ef |grep sleep" to see the process started earlier (the sleep command should get killed while closing the UI)

```

**Comment by vincent99** [comment]
There is nothing that can be done on our side for that case.  Docker does not kill them when the exec is ended, and it is the only thing that can cleanly solve this.

The Ui is just a tty that has no good way to cause the arbitrary process tree that's running to exit.  Sending ^D/exit is just a "hack" to exit the process if it happens to recognize that input, as sitting on a shell prompt would.
