### ISSUE TITLE
Rancher can't perform App upgrade from helm2 to helm3

### ISSUE THREAD

**Issue by hatharom** [rancher/rancher#29758]
**Use case:**
I have a helm2 chart(apiversion: 1) named 'myChart' imported as HELM2 Catalog  and an App ('myApp') is deployed from it.
I want to increase the apiversion of the chart to 2. 
According to do documentation this will require the remove/readd of the catalog as helm3
https://rancher.com/docs/rancher/v2.x/en/helm-charts/legacy-catalogs/#catalog-helm-deployment-versions
`When you create a custom catalog, you will have to configure the catalog to use either Helm 2 or Helm 3. This version cannot be changed later. If the catalog is added with the wrong Helm version, it will need to be deleted and re-added.`

Unfortunately it doesn't work,Rancher shows the catalog as a Helm3 one, but the App upgrade fails : 
` Error: apiVersion 'v2' is not valid. The value must be "v1" : exit status 1`

The deployed App's view in API section shows : `  "helmVersion": "rancher-helm"`.

**So as I tried the other way around :**
Starting with a clean install:
Using the same helm2 chart but importing the Catalog as Helm3, the App is deployed.
Then I remove the catalog and readd it as Helm2.  Now the upgrade goes well, but
The deployed App's view in API section shows : `  "helmVersion": "helm_v3"`.

So as turned out even if I change the catalog's helm version it will not change the way how it manages already deployed releases.

The documentation doesn't say anything about it. It only states that the catalog should be removed/readd.

**_So my question is : How to upgrade an already deployed APP from helm2 to helm3?_**

note: The only change in the chart is the Chart.yaml's apiversion field.

Rancher version: 2.4.8

**Comment by cyboman32** [comment]
Seems this related https://github.com/rancher/rancher/issues/26407
In my case helm3 v1 -> helm3 v2 fails but with the same error and seems because rancher uses helm2 binary instead of helm3

**Comment by flauschi** [comment]
I have the same problem. I added the Helm catalog long time ago. At this time Helm 3 wasn't out.
Now a chart has transitioned from Helm 2 to Helm 3 (Rook Operator). I deleted the v2 Helm catalog and readded it as v3 Helm catalog. The upgrade of the app still fails with the error message @hatharom has mentioned.

Is there a way to manually upgrade an app from v2 to v3 **without** deleting and recreating it? (in my case: Deleting the Rook Operator Helm chart would delete the distributed Ceph storage. Rebuilding everything from backup would be a really huge effort.)

**Comment by jonathon2nd** [comment]
Our setup is relatively new so I was able to backup various things/dbs and redeploy helm 3 chart apps. 

I looked into migrating the apps from helm v2 to v3, but I eventually gave up and did everything manually. 
There was this issues opened https://github.com/rancher/rancher/issues/28198, but nothing happened.

Rancher docs now contain https://rancher.com/docs/rancher/v2.x/en/installation/upgrades-rollbacks/upgrades/ha/helm2/, but this really only talks about if you installed the Rancher management cluster with helm 2. Same for this doc https://rancher.com/docs/rancher/v2.x/en/installation/resources/helm-version/

Both link to this https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/, this does not look like it is useful for this. No matter where I setup the plugin, it could never see the apps installed to migrate them. I did this on the hosts as well as different rancher system workload pods. 

Hope this helps a little and that you can find something I could not.

**Comment by konvergence** [comment]
Hi all,

I get the same issue with rook operator create in v1.4.6.

I have recreated the catalog rook with helm_v3, 
But get  error during upgrade of the rook operator in v1.5.5: `Error: apiVersion 'v2' is not valid. The value must be "v1" : exit status`, 

I don't want to recreate the app, because it means to loose all the ceph cluster.
Is there a way to force with rancher API the `"helmVersion": "helm_v3"` on the existing rook operator app ?

**Comment by flauschi** [comment]
Offtopic, because it has nothing to do with the "bug":
@konvergence I have tried everything and found no way to manually upgrade the deployment without recreating the app. I ended up to do a disaster recovery of the Rook Ceph Cluster. I used the guide provided at https://github.com/rook/rook/blob/master/Documentation/ceph-disaster-recovery.md#adopt-an-existing-rook-ceph-cluster-into-a-new-kubernetes-cluster . Have a working (!!!) backup of everything (each Kubernetes node and the Rancher instance), delete the app, add the helm catalog as v3, and then follow the guide step by step. Last step is to increase the monitor count to your previous setting (this step is missing in the guide).
