### ISSUE TITLE
Alerts-Does Rancher have a plan to provide GUI-based configuration in 2.5.x

### ISSUE THREAD

**Issue by sadhugit** [rancher/rancher#29776]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Does Rancher have a plan to provide a GUI-based configuration?
Cluster Explorer only provides Prometheus/AlertManager UI.

Actual result:
Version v1 (cluster manager) - we have provided GUI-based configuration for cluster alerts (for etcd, k8s components, node, cluster scan, etc.). Right now, in v2 (Cluster explorer), end users are unable to find the same GUI-based configuration to configure the alerts and only provide Prometheus/alert manager UI. Is there any plan to provide the same GUI based format (v1) in upcoming releases (v2.5.x)?

**Comment by Tejeev** [comment]
Alerting GUI is being fleshed out further at each release.  Rancher v2.5.6 and https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/configuration/alertmanager/ have been much improved from the early versions available late last year (when this issue was filed).  Please let us know if this concern has been addressed to your satisfaction (still more improvements on the way :) )
