### ISSUE TITLE
Add filter option for template GET request

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#29773]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
When making a request to get a template, links are added to the response for version that are compatible with server version. This request is for being able to accept a query param for cluster kubernetes version so that only version links compatible with that cluster, on top of being compatible with rancher version, will be included. To achieve this, the new ValidateChartCompatibility can be used in the extractVersionLinks method of the template store.

**Comment by jiaqiluo** [comment]
This is enhancement is validated on 
- rancher:master-head `203033a` 
- rancher:v2.5-head `f671292`


Steps:
- add the following repo which charts contains the `kebeVersion` filed
```
URL: https://github.com/izaac/system-charts.git
branch: k8stest
```
- open the url  `https://server-url/v3/templateversions` in the browser 

Resutls:
- `kubeVersion` is an option for filtering 
<img width="345" alt="Screen Shot 2020-11-20 at 2 27 07 PM" src="https://user-images.githubusercontent.com/6218999/99852184-b4211b00-2b3d-11eb-8891-53c997382aec.png">

- We can use the filter to find all `templateversions` which `kubeVersion` is '>1.18.0'
 
![screencapture-178-128-8-172-v3-templateversions-2020-11-20-14_38_25](https://user-images.githubusercontent.com/6218999/99852362-17ab4880-2b3e-11eb-993d-2333fa4dfd09.png)

**Comment by jiaqiluo** [comment]
Reopen this issue because all charts with the field `kubeVersion` in `Chart.yaml` are now not returned from the backend. Also, we are not passing the ClusterName when getting the version links of a template.

The following is done on rancher:master-head 6f96683ba

**Steps:**
- run rancher with passing the parameter `CATTLE_SERVER_VERSION`
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_SERVER_VERSION=2.5.3 --privileged rancher/rancher:master-head
```
- add clusters with different k8s versions 

![image](https://user-images.githubusercontent.com/6218999/101083128-c18ccb00-3569-11eb-9c8f-07b7fc5986e1.png)

- add the following repo as a global repo 
```
repo:     https://github.com/jiaqiluo/system-charts
branch: k8s-limit
---
for 0.1.5 I set: kubeVersion: ">=1.16.0 <1.18.10" in Chart.yaml
for 0.1.6 I set : kubeVersion: ">1.18.0" in Chart.yaml
```

- Now I pretend to install the monitoring app as a regular app on the cluster with k8s `v1.17.14`, but only chart 0.1.4 shows in the version list on all clusters.

<img width="1033" alt="Screen Shot 2020-12-03 at 12 37 26 PM" src="https://user-images.githubusercontent.com/6218999/101083664-1d575400-356a-11eb-98b6-37714f17a80c.png">

- the GET request passes the new parameter `ClusterName`, but only link to the chart 0.1.4 returns, but  I expect to see the chart vesion `0.1.5`
<img width="627" alt="Screen Shot 2020-12-03 at 12 37 55 PM" src="https://user-images.githubusercontent.com/6218999/101083703-2ba57000-356a-11eb-914b-87eb02d6e023.png">
<img width="358" alt="Screen Shot 2020-12-03 at 12 38 36 PM" src="https://user-images.githubusercontent.com/6218999/101083706-2c3e0680-356a-11eb-8349-859054f6afab.png">


**Notes:**
I also tried with a modified WordPress chart cloned from the rancher/charts GH repo, and I also did not see the new charts. 

link to the chart: https://github.com/jiaqiluo/charts/tree/test-k8s-limit/charts/wordpress

**Comment by thedadams** [comment]
This appears to be a UI issue. In the query string, it passes the display name of the cluster: `clusterName=1-17`. The query string should pass the cluster name instead, something like `clusterName=c-ctdzb`.

I tested this locally with a cluster on version 1.17.14 and it returned 0.1.4 and 0.1.5, but not 0.1.6.

**Comment by jiaqiluo** [comment]
Wait for the UI to be fixed https://github.com/rancher/rancher/issues/29774
then I will close this issue

**Comment by jiaqiluo** [comment]
The validation is done on 
- rancher:master-head  a31eecf55
- rancher:v2.5-head ef237669e

**Steps:**
- run rancher with passing the parameter `CATTLE_SERVER_VERSION`
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_SERVER_VERSION=2.5.3 --privileged rancher/rancher:master-head
```
- add clusters with different k8s versions 

![image](https://user-images.githubusercontent.com/6218999/101083128-c18ccb00-3569-11eb-9c8f-07b7fc5986e1.png)

- add the following repo as a global repo 
```
repo:     https://github.com/jiaqiluo/system-charts
branch: k8s-limit
---

add two new versions for the rancher-monitoring chart:

for 0.1.5 I set: kubeVersion: ">=1.16.0 <1.18.10" in Chart.yaml
for 0.1.6 I set : kubeVersion: ">1.18.0" in Chart.yaml
```

 
Here are the versions showing on each cluster 
k8s version | template version
------------| ---------------
v1.19.4 | 0.1.6 
v1.18.12| 0.1.6 
v1.17.14| 0.1.5 
v1.16.15| 0.1.5 

Note `0.1.4` shows in the list because the `kubeVersion` filed is not set in its chart.  

![image](https://user-images.githubusercontent.com/6218999/101220996-fd945e80-3643-11eb-9ca1-8a4d98b1c8e0.png)


I also tried with a [modified WordPress chart](https://github.com/jiaqiluo/charts/tree/test-k8s-limit/charts/wordpress) cloned from the rancher/charts GH repo, and it also works as expected.
