### ISSUE TITLE
Monitoring v2 - failed to create pv for prometheus when using longhorn as the storage class 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29839]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run rancher:v2.5-head single-install
- provision a cluster
- install Longhorn `1.0.201` 
- install Monitoring v2 `9.4.201` with persistent storage enabled for Prometheus 
![image](https://user-images.githubusercontent.com/6218999/97618929-dd3a0a00-19dc-11eb-998f-1ee26a7174c3.png)

**Result:**
A PVC is stuck in the pending state and waiting for Longhorn to provide a PV
![image](https://user-images.githubusercontent.com/6218999/97619067-00fd5000-19dd-11eb-96e1-19a43c8b15eb.png)

Maybe this is the reason: 
```
failed to provision volume with StorageClass "longhorn": claim Selector is not supported
```
![image](https://user-images.githubusercontent.com/6218999/97619092-06f33100-19dd-11eb-977b-d754a28d520f.png)

**Comment by joshimoo** [comment]
I think this issue applies to all provisioners.
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1

See the Note in the kubernetes documentation: 
`Currently, a PVC with a non-empty selector can't have a PV dynamically provisioned for it.`

**Comment by aiyengar2** [comment]
@joshimoo thanks for the insight! You are correct.

Here is a summary of the issue and the resolution for any users who encounter this issue when installing Monitoring before 2.5.2:

#### Issue
This issue occurs because the Dashboard UI automatically sets `prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.selector: { matchExpressions: [], matchLabels: {} }` when persistent volumes are configured when it should be omitting the field entirely by default unless a rule is added by the user. The fix for the UI defaults will be tracked in https://github.com/rancher/dashboard/issues/1757.

#### Workaround

After configuring your options under `Chart Options` as normal:
1. Click on `Edit as YAML` on the bottom of the page
1. Find the YAML field for `prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.selector`
1. Remove that field entirely

For example, the yaml shown under `prometheus.prometheusSpec.storageSpec` in a valid configuration might look something like:

```yaml
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: longhorn
          volumeMode: Filesystem
```

#### Other Possible Issues

If you see the Prometheus pod pending creation due to a failure to attach the volume like:

![Screen Shot 2020-10-30 at 2 30 34 PM](https://user-images.githubusercontent.com/13127443/97759933-472ae000-1abf-11eb-986b-9dfe358843c9.png)

Based on https://github.com/longhorn/longhorn/issues/1661#issuecomment-668225787, you need at least 3 nodes or need to modify your Longhorn configuration.

If you see the Prometheus pod showing an event where it fails to mount the volume like:

![Screen Shot 2020-10-30 at 2 38 36 PM](https://user-images.githubusercontent.com/13127443/97760084-9a049780-1abf-11eb-9c2c-60f9bbbbb8c7.png)

Based on https://github.com/longhorn/longhorn/issues/1712#issuecomment-678878069, this is a transient error that should disappear and the Prometheus pod deployment should still be successful.

**Comment by aiyengar2** [comment]
@jiaqiluo can you test the workaround on a 3+ node cluster? If the workaround works, I think we should close this issue out in favor of https://github.com/rancher/dashboard/issues/1757 for the actual fix to the defaults.

**Comment by jiaqiluo** [comment]
Confirmed on rancher:`v2.5-cc777ebfabe4dba48216525bb1cd56c01231dd40-head` that the workaround is valid. 

Steps:
- run rancher in the single-install mode 
- provision a cluster with 1 etcd, 1 control plan, and 4 dedicated worker nodes 
- install Longhorn `1.0.201`
- install Monitoring v2 `9.4.201` with persistent storage enabled for Prometheus and Grafana 
- apply the workaround by editing the app in YAML. Specifically, removing the following highlighted line for the YAML
<img width="564" alt="Screen Shot 2020-10-30 at 3 18 32 PM" src="https://user-images.githubusercontent.com/6218999/97762160-e8686500-1ac4-11eb-8c1b-bc8f3cc61e63.png">


Results:
- monitoring is installed successfully and functional
- the PV and PVC for Grafana and Prometheus are created and bounded successfully

![image](https://user-images.githubusercontent.com/6218999/97762219-1352b900-1ac5-11eb-90b2-da0fe679df7d.png)
