### ISSUE TITLE
Cluster-scoped API keys shall work against the Rancher API (e.g. terraform provider, rancher cli)

### ISSUE THREAD

**Issue by miraculixx** [rancher/rancher#29943]
Currently scoped Rancher APIs don't work with the terraform provider nor the rancher cli. This means that anyone requiring access to the cluster via API has to be provided full access across the entire rancher scope (all clusters, projects).

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement/Bug

**Steps to reproduce (least amount of steps as possible):**
See #18639

**Result:**
Better security model for use cases where terraform and the cli are used to work with rancher by multiple people / across organizations. 

**Other details that may be helpful:**
The current way of full-cluster access for API tokens breaks rancher's otherwise well structured security model.
I'm choosing to open a new issue because several people have voted for a change in #18639, which is a bug report marked closed with a documentation update, in effect preventing the report's intended change. 

**Environment information**
- Rancher version 2.4.5
- Installation option HA

**Comment by ivanvmoreno** [comment]
I completely agree with @miraculixx - for our use case, we have a 1:1 binding of Rancher cluster to Rancher user (added as a member to said cluster). This is because the cluster is delivered to the team / customer, scoped to that particular cluster.

However, we have automated a feature for which users can fetch their Kubeconfig for that cluster without needing to access to Rancher - and that's when we found out that cluster-scoped tokens can't be used for authentication for the Rancher API (e.g. `clusters/<cluster-id>?action=generateKubeconfig`) - thus, forcing us to rely on global-scoped tokens for this purpose.

**Comment by vincent99** [comment]
> This means that anyone requiring access to the cluster via API has to be provided full access across the entire rancher scope (all clusters, projects).

It does not mean this at all.  The alternative to cluster-scoped tokens is USER-scoped, and they receive only the access to the global resources/clusters/projects/etc for which that particular user has been granted.  

That will only be "everything" if you're giving out a token for an admin user to everyone.

**Comment by vincent99** [comment]
> for our use case, we have a 1:1 binding of Rancher cluster to Rancher user (added as a member to said cluster). This is because the cluster is delivered to the team / customer, scoped to that particular cluster.

If you're already creating a user and binding them to exactly one cluster and generating a token for that one user+cluster, giving them a user-scoped token is almost exactly the same thing as making a cluster-scoped one for that user+cluster.  They'll get the same access to that cluster.  Plus some additional global types, but you can lock down their global role for down to "user base", which includes very little.
