### ISSUE TITLE
local cluster upgrade does not work

### ISSUE THREAD

**Issue by felipecrs** [rancher/rancher#29966]
I edited my `local` cluster and selected a newer version of Kubernetes in order to upgrade it. However, the upgrade did not happen and it's now flashing in the cluster view as upgrading all the time. GIF:

![J0F2bGAho2](https://user-images.githubusercontent.com/29582865/98388747-0162a000-2008-11eb-853b-727ecd8cf988.gif)

Already tried to restart the Rancher server and the node hosting the Rancher itself but nothing helps. Also, since it's "upgrading", I can't revert to an older version.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.0` UI: `v2.5.0` |
|Route|`undefined`|

**Comment by maggieliu** [comment]
@felipecrs Can you provide more information on how you installed it? Was it a docker install? We have disabled upgrading k3s   on docker install in 2.5.2, please refer to this: https://github.com/rancher/rancher/issues/29412

**Comment by felipecrs** [comment]
Yes, it's installed in a VM through Docker, not in a cluster. 

Thank you so much for letting me know. I'll try to upgrade Rancher and see if it stops "upgrading".

**Comment by felipecrs** [comment]
The same behavior persists with v2.5.1, but as said, it was changed in v2.5.2. So I'll wait for its release before testing.

**Comment by felipecrs** [comment]
I upgraded to v2.5.2 but the problem still persists:

![OGfQGG6grN](https://user-images.githubusercontent.com/29582865/98865874-ce2a7180-244a-11eb-99c3-9377d8c98366.gif)

**Comment by hp-caoy** [comment]
I meet the same problem, Is there anybody know how to solve it ?

**Comment by moschlar** [comment]
Same here

**Comment by Vashiru** [comment]
@maggieliu It appears that the fix for that isn't fool proof. I run a single node docker install as well, currently running v2.5.5 and the option to upgrade was available for me.. The local cluster was running K3s v1.18.8+k3s1, tried upgrading it to 1.19.5+k3s2 as the option was there and now it's just blinking on and off. The API shows it as:

```
state": "upgrading",
"transitioning": "yes",
"transitioningMessage": "cluster is being upgraded",
"type": "cluster",
"uuid": "f42d4b29-9116-4552-8449-909xxxxxxx",
```

I tried editing the k3sConfig field in the API to see if I can revert it back but it won't let me (error 422, unprocessable entity)

**Comment by Vashiru** [comment]
Ok I managed to sort of fix / work around it. **Note: This might have unforeseen consequences down the line (maybe somebody else can judge this)...**

**Steps:**
1. Go to your local cluster
2. Go to edit cluster
3. Set control plane concurrency and Worker concurrency to 1
4. Press save
5. Now you  should be back at your local cluster
6. Go to view/edit in API
7. In the top right corner click on Edit
8. Edit the value of k3sConfig and set it to `{"k3supgradeStrategy":{"drainServerNodes":false,"drainWorkerNodes":false,"serverConcurrency":1,"type":"/v3/schemas/clusterUpgradeStrategy","workerConcurrency":1},"kubernetesVersion":"v1.18.8+k3s1","type":"/v3/schemas/k3sConfig"}`.
9. Click Show Request
10. Click on Send Request
11. You should get a HTTP response 200

After that the upgrade message will stop flashing. However where there used to be Edit cluster / View edit in Api etc. I now see "No actions available". I am not sure if I broke something by doing these steps, or if this was the intended behavior since 2.5.2.

Other things I noticed: If you press save on editing the cluster at step 3 without setting them to 1, it'll refuse because it can't be empty or 0. Which is likely why simply editing the field in the API before didn't work, because it refused the value for my k3sConfig. So it might be you only need steps 6 through 11, but I wrote down exactly what I did to be sure.

**Comment by Vashiru** [comment]
I eventually reverting a back-up. But yeah I can confirm @maggieliu, in Rancher v2.5.3 the option for a local upgrade is not there, however in v.2.5.5 the option is available for the local cluster.

Perhaps the title should be updated to reflect the real issue: Local cluster k3s upgrades are available for single node docker installs in v2.5.5 where they shouldn't be.

**Comment by felipecrs** [comment]
I would rather change it to "Can't stop upgrading local cluster".

**Comment by chris922** [comment]
I've got the same issue.. does anybody found a working solution to get rid of this "Cluster is being upgraded" messages blinking in the cluster overview?

**Comment by bennysp** [comment]
I have the same problem too. Anyway to get rid of it?

**Comment by TiTidom-RC** [comment]
Had the same issue this morning in rancher 2.5.6 : i wanted to upgrade k3s local cluster as it was proposed in the cluster "edit" properties... and after that, the message "cluster is being upgraded" was blinking every about 10sec :(

I restored from a backup (i'm using the backup/restore feature of rancher scheduled to run every 6h), and after that the message (cluster upgrade) disappeared and i was able to use rancher again normally.

**Comment by bennysp** [comment]
Thanks @TiTidom-RC . I just restored using the same feature and it appears to have removed the error too.

**Comment by smirnov-mi** [comment]
Got the same, trying to update my "local" from v1.18.8+k3s1 .  Also running it in a single docker.

**Comment by JumpMaster** [comment]
I ran into the same issue and reverted my /var/lib/rancher directory to a pre-upgrade backup.  I use a cronjob to stop the rancher container nightly and backup the /var/lib/rancher volume with restic over s3 via minio.

My question is.  How do we upgrade k8s on a docker container?  I assume there will eventually be a need to?

**Comment by Vashiru** [comment]
> 
> 
> > **EDIT: Err I did the following (see below) and currently I can no longer access my main Rancher Cluster Overview. I can access other parts of Rancher through various URLs though. So yeah, it might be a bad idea. I see 2 problems in my logs. Fleet-system gitjob can't be updated because another change has been in between and `[ERROR] could not convert gke config to map` - so proceed with caution.**
> > Ok I managed to sort of fix / work around it. **Note: This might have unforeseen consequences down the line (maybe somebody else can judge this)...**
> > **Steps:**
> > ```
> > 1. Go to your local cluster
> > 
> > 2. Go to Edit cluster
> > 
> > 3. Set control plane concurrency and Worker concurrency to 1
> > 
> > 4. Press save
> > 
> > 5. Now you  should be back at your local cluster
> > 
> > 6. Go to View in API
> > 
> > 7. In the top right corner of the API click on Edit
> > 
> > 8. Edit the value of k3sConfig and set it to `{"k3supgradeStrategy":{"drainServerNodes":false,"drainWorkerNodes":false,"serverConcurrency":1,"type":"/v3/schemas/clusterUpgradeStrategy","workerConcurrency":1},"kubernetesVersion":"v1.18.8+k3s1","type":"/v3/schemas/k3sConfig"}`. (Or the version your k3s version used to be, you can still see the old version on the Dashboard).
> > 
> > 9. Click Show Request
> > 
> > 10. Click on Send Request
> > 
> > 11. You should get a HTTP response 200
> > ```
> > 
> > 
> > After that the upgrade message will stop flashing. However where there used to be Edit cluster / View in API etc. I now see "No actions available". I am not sure if I broke something by doing these steps, or if this was the intended behavior since 2.5.2.
> > Other things I noticed: If you press save on editing the cluster at step 3 without setting them to 1, it'll refuse because it can't be empty or 0. Which is likely why simply editing the field in the API before didn't work, because it refused the value for my k3sConfig. So it might be you only need steps 6 through 11, but I wrote down exactly what I did to be sure.
> 
> Fixed it for me. I do see the buttons though in latest rancher version `v2.5.7`.

Glad to hear my tinkering fixed it for you. I tested this recently in 2.5.8 and the upgrade button is no longer available.

> 
> 
> I ran into the same issue and reverted my /var/lib/rancher directory to a pre-upgrade backup. I use a cronjob to stop the rancher container nightly and backup the /var/lib/rancher volume with restic over s3 via minio.
> 
> My question is. How do we upgrade k8s on a docker container? I assume there will eventually be a need to?

Nope. Rancher in a single node docker install uses K3s internally to set up a cluster. K3S is basically K8S in a binary. Upgrading that (when used as an actual cluster, NOT INSIDE THIS CONTAINER*) is nothing but stopping K3s, replacing the binary and restarting K3s. In this case you don't have to worry about that as new versions of the Rancher Docker image will automatically be bundled with newer versions of K3s and thus upgrade the kubernetes version.

* For real, don't go replacing the binary in this container. I've tried doing this on an older version of Rancher, it didn't go over well. (Mind you that was a really old version of K3s and the reason I was attempting it is because that old version didn't have automatic certificate renewal yet and I was dealing with expired certificates and running out of options).
