### ISSUE TITLE
nginx.ingress.kubernetes.io/rewrite-target not working

### ISSUE THREAD

**Issue by piyush94** [rancher/rancher#30033]
controller image: rancher/nginx-ingress-controller:nginx-0.35.0-rancher2
K8s version: 1.16.15
rancher version: 2.4.8

After controller version 0.21.0-rancher3, the rewrite-target annotation hasn't worked for us.
Even after adding the annotation, the rewrite doesn't happen.

Let me know if I can provide any logs that would help.

Thanks.

**Comment by superseb** [comment]
Sounds like https://github.com/rancher/rancher/issues/25272, please let me know if this is not the case.

**Comment by piyush94** [comment]
Thanks, this worked.

**Comment by natekwilson** [comment]
This method works BUT after editing the path to include a regex the web-cluster manager's Endpoint links are broken and is entirely enumerated as a URL instead of just the path portion

/test(/|$)(.*) - Path in YAML
https://test-domain/test-path(/%7C$)(.*) - Broken URL in Cluster manager
https://test-domain/test-path - Desired URL in Cluster manager

**Comment by vincent99** [comment]
The UI doesn't know that the path you entered happens to also be a regex (without looking for implementation-specific annotations).  Assuming we did, there's still no general way to turn an arbitrary regex into into a particular "desired" link that matches it.
