### ISSUE TITLE
Cluster stuck "currently Upgrading, updating worker node" on Cordoned workers

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#30049]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

How to recreate:
1. Create a cluster with 3 master and a
In that state different issues happen:t least 2 workers.
2. Once the cluster is ready, cordon at least 2 workers.
3. Delete master #1, wait for it to be replaced.
4. Repeat step 3 with master rancher/rancher#2 and #3.
5. Cluster state is still "This cluster is currently Upgrading – Updating worker nodes", some other side effects might also be seen. 

**Result:**
The current bug is that if more than 2 worker nodes are cordoned, the cluster will be stuck in a "This cluster is currently Upgrading – Updating worker nodes" state forever until we uncordon the nodes.

**Other details that may be helpful:**

When a Controlplane node get replaced, the worker nodes need to be updated with the new IP address of the master nodes.

* Sometimes it will take quite a while (more than 30 minutes) to recreate the deleted master node.
* Kubelet is down on multiple nodes (cordoned or not)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): HA

```
kubectl 1.17.2 
```

![screenshot2_](https://user-images.githubusercontent.com/61939253/98946602-603a8480-24f4-11eb-9bd5-5bad2c2c90e1.png)

![screenshot1_](https://user-images.githubusercontent.com/61939253/98946506-413bf280-24f4-11eb-8e96-5805c77f1da3.png)

gz#13331

**Comment by asemen2608** [comment]
A side effect with a cordoned worker node and the replacement of a master node is that the worker node gets automatically uncordoned.

How to recreate:
1. Create a cluster with 3 masters and at least 1 worker.
2. Once the cluster is ready, cordon 1 worker.
3. Delete any master node.
4. The worker that was cordoned is now uncordoned.

**Comment by asemen2608** [comment]
Will there be also a fix for v2.4.x?

**Comment by kinarashah** [comment]
@asemen2608 Thanks for opening the issue, I'll backport the fix so it's available in `v2.4.x` as well.

**Comment by kinarashah** [comment]
This issue is not always reproducible. Isn't related to k8s or rancher versions, though certain behaviors might exacerbate it and make it more probable on certain setups. It requires messing with stopping and starting kubelet or nginx-proxy on worker nodes multiple times before the actual issue is hit. It's possible, but not guaranteed. 

Instead, following steps could be used to reproduce the bug: 
- Rancher server v2.4.x or v2.5.x 
- Create a RKE cluster with ~5 worker nodes and set maxUnavailable to 100% (optional, just to speed up the process).
- ssh into one of the worker nodes and retag older agent image as the current image on the node. 
 `docker pull rancher/rancher-agent:v2.3.9; docker tag rancher/rancher-agent:v2.3.9 rancher/rancher-agent:v2.4.x`
 - Trigger an upgrade. Could be adding/removing control plane node, changing k8s version or changing kube extra args. 
 - Cluster will be stuck with "Upgrading worker nodes" with this one node stuck in Upgrading. 
 - Update the node crd in local cluster, 
 ```
 kubectl edit nodes.management.cattle.io -n c-xxx
 set the `appliedNodeVersion` to `cluster.Status.NodeVersion`
 update condition Upgraded to "True"
 ```
 - Node will be stuck in cordoned state. No edits on node or cluster fixes the issue.

**Comment by slickwarren** [comment]
following the above directions, I was able to reproduce this on v2.5-head (05fbcbb75ba84a80c5aaa243985e892c52b9ac32) and 2.5.5: 
* create 1 node with all roles, and 3 more with only `worker` role
* ssh into the 3rd worker node with the downloaded keys, download an old image, and tag it as the version of rancher you're using `docker pull rancher/rancher-agent:v2.3.9; docker tag rancher/rancher-agent:v2.3.9 rancher/rancher-agent:v2.5-05fbcbb75ba84a80c5aaa243985e892c52b9ac32-head`
* go to `system` -> `cattle-node-agent` and select the pod running on worker 3. Delete the pod (it will restart with the image tagged previously)
* go to the cluster -> nodes, `edit cluster`, and add control plane to worker 1 , then save changes
* the cluster will update all nodes, and worker 3 will remain in `cordoned` state indefinitely.

**Comment by slickwarren** [comment]
reopening for master-head forwardport

**Comment by slickwarren** [comment]
tested on master-head (007e2985af1f24749d704020929a1c635f97e7ef), able to get the node out of `cordoned` state and back to active
