### ISSUE TITLE
Node template values not changing while switching cloud credentials for vSphere

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30074]
Tracking issue mentioned here: https://github.com/rancher/rancher/issues/26997#issuecomment-726217804

gz#9795

gz#13362
gz#14290

**Comment by maggieliu** [comment]
@aaronRancher can you test out what @ansilh mentioned [here](https://github.com/rancher/rancher/issues/26997#issuecomment-726217804) and see if you can reproduce?

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.4-4306-head`

An error is seen when switching between valid credentials under the data center field.
![Screen Shot 2020-11-19 at 1 31 56 PM](https://user-images.githubusercontent.com/57409052/99720948-b5821300-2a6b-11eb-9795-a68821d75246.png)

Reopening for fix.

**Comment by ansilh** [comment]
Thanks, @aaronRancher.
I've also noticed that, while saving the template which is created with the second vCenter credential, the POST call still takes values from the first vCenter. Could you please test it and make sure that also covered in this issue?

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version fa6ab9d` and `rancher\rancher:v2.5-head` `version fc09f27`
Steps:
Create vSphere credentials by following the steps detailed here https://github.com/rancher/rancher/issues/26997#issuecomment-726217804
In Rancher, create a new vSphere node template.
Switch between the credentials and see fields update.

Result:
![15ac0668f1b57d8105c67539bc29c749](https://user-images.githubusercontent.com/57409052/103712303-ad782700-4f76-11eb-8d5c-1f2dd5597750.gif)


On `rancher\rancher:v2.4-4544-head`, an error is seen when switching between credentials:
![a95f1b09f89aecb2df543c86bda1ac89](https://user-images.githubusercontent.com/57409052/103712298-a94c0980-4f76-11eb-9f0a-25ae712aa7d3.gif)

Reopening for fix in `v2.4-head`

**Comment by codyrancher** [comment]
@aaronRancher I suspect the change wasn't in when you verified because it seems to be working as intended for me. It resets all the fields and waits for the new data center to load (I still only have access to one datacenter though).

![Kapture 2021-01-12 at 13 09 40](https://user-images.githubusercontent.com/55104481/104367182-ace01300-54d7-11eb-871c-c54c930f9a78.gif)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.4-4683-head`

Fields are updated without error when switching between cloud credentials:
![34fc32996db34558a6a4a71109d07967](https://user-images.githubusercontent.com/57409052/104506276-65728900-55a2-11eb-9dc4-fd05fe9fb96c.gif)
