### ISSUE TITLE
[UI] Add "Rotate Encryption Key" to Cluster Actions Dropdown

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#30077]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Description:**
This is a request for enhancement. As part of the backend issue, I'm implementing a cluster action that performs etcd encryption key rotation for secrets. Similar to other actions, we will need an option in the cluster dropdown for "Rotate Encryption Key".

![Screen Shot 2020-11-13 at 2 06 05 PM](https://user-images.githubusercontent.com/8824599/99121207-6ba3b380-25b9-11eb-86ad-b7a6b33de8a7.png)

There is an additional requirement that the user should create an etcd backup before proceeding with the key rotation, so that they may restore in the case of a failure. We'd like to have the "Rotate Encryption Key" button bring up a modal/warning that makes the user confirm they have created a backup. The modal should say something like: "Ensure you've take a successful etcd backup before proceeding" Confirm / Cancel. Confirming will trigger the api request that initiates the key rotation action.

The API request to perform the key rotation looks like:
```
HTTP/1.1 POST /v3/clusters/<cluster-id>?action=rotateEncryptionKey
Host: <rancher-server-url>
Accept: application/json
Content-Type: application/json
Content-Length: 2

{ }
```

**Backend Issue:**
https://github.com/rancher/rancher/issues/27735

**Comment by westlywright** [comment]
UI has been merged to both 2.5-fixes and master. But I do not believe the backend is in yet on master so this should be qa'd on the 2.5 branch. 

Additionally there are a couple things that have changed:
Exposed the `Encrypt Secrets` param for RKE clusters in the advanced section on create. This flag must be set for the rotate action to work. Otherwise you'll get an error from the backend. 
IF the cluster is transitioning, doesn't have the previously mentioned flag set, doesn't have any etcd backups, or is in the middle of a rotate action (indicated by the `rotateEncryptionKey` on `rancherKubernetesEngineConfig` being set true) the Rotate Action will not be available in the actions dropdown. 
The UI also imposes a 360 minute limit as the `last safe backup` timeframe, so if you dont have a backup within the last 6 hours you wont see the rotate action in the dropdown.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:v2.5-head` `version bb69b03`

Steps:
In Rancher launch an RKE cluster
Edit cluster
Enable `Secrets Encryption`
![Screen Shot 2020-12-18 at 12 00 55 PM](https://user-images.githubusercontent.com/57409052/102650821-b79dc700-4128-11eb-9d12-366856dabc8a.png)
Return to cluster view. Wait for cluster to update. Click on dropdown.
`Rotate Encryption Key` is available:
![Screen Shot 2020-12-18 at 11 09 40 AM](https://user-images.githubusercontent.com/57409052/102665005-3868bd00-4141-11eb-8908-fbd87b5bfa91.png)

**Comment by aaronRancher** [comment]
For full coverage, I tested and validated a few test cases to verify the above comments. Tested on Rancher `v2.5.4`

Scenario 1:
Create a downstream cluster with `Secrets Encryption` enabled.
After cluster is available, check cluster dropdown and verify `Rotate Encryption Key` is available.
Edit the cluster, add a node.
While cluster is updating, check cluster dropdown and verify `Rotate Encryption Key` is NOT available.

Scenario 2:
Create a downstream cluster with `Secrets Encryption` enabled.
After cluster is available, check cluster dropdown and verify `Rotate Encryption Key` is available.
Wait 6 hours.
Check cluster dropdown and verify `Rotate Encryption Key` is NOT available.
