### ISSUE TITLE
Panic in KEv1 caused by etcd backup

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#30078]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
user used the terraform rancher2 module to create etcd backups

**Result:**
rancher deployment entered a crash loop

**Other details that may be helpful:**
It appears that the grpcServer in the GrpcServer struct is nil which is causing a panic when method the Stop() is called. May just need a nil check but should investigate further.
original report: https://rancher-users.slack.com/archives/C3ASABBD1/p1604954479116400

**Comment by rawmind0** [comment]
@rmweir , what tf provider version was used to reproduce this issue?? What Rancher version?? I can't access slack link to get more context about this. Could you please provide more context?

This issue was happening on old tf provider, but it was already addressed, so not sure if it'd be a regression on new tfp versions or talking about "old" issue.
