### ISSUE TITLE
[2.4] Backport Bug: ec2 cluster with Amazon Linux images fail to start

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30070]
related: https://github.com/rancher/rancher/issues/21648

**Comment by sadiapoddar** [comment]
Verified the fix on v2.4-4531-head
Used the amazon ami-0b898040803850657.
When users will use this ami from to create node-template, the user has to be
"ec2-user". The fix is working on both branches.

Steps

created a node template using the amazon linux ami, mi-0b898040803850657
created a cluster using the node-template
the cluster is up and running
