### ISSUE TITLE
[EKSv2] eks-operator: 1.0.5

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30142]
#### Rancher Release

2.5.3

#### Repo

`rancher/system-charts`

#### Changes

Check for existing clusters in EKS with the same display name
Issue:
https://github.com/rancher/rancher/issues/29103
PR:
https://github.com/rancher/eks-operator/pull/18, https://github.com/rancher/eks-operator/pull/26

Remove creation of extraneous security group
Issue:
https://github.com/rancher/rancher/issues/29826
PR:
https://github.com/rancher/eks-operator/pull/21

**Comment by cbron** [comment]
This is ready to go, but we are waiting on all related issues to get validated/closed by QA before tagging final image.

**Comment by aaronRancher** [comment]
This issue is verified with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version b2953cb`

eks-operator has been updated to 1.0.5
![Screen Shot 2020-12-08 at 12 26 11 PM](https://user-images.githubusercontent.com/57409052/101532556-f629c980-3951-11eb-9243-1e54bea2eff4.png)
Validated the issues mentioned. Clusters pass regular testing.
