### ISSUE TITLE
[OPA Gatekeeper] rancher-gatekeeper: v3.2.1

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#30179]
Location: https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-gatekeeper
Repo: rancher/charts
Branch: dev-v2.5

Changes include rebasing to latest upstream version v3.2.1, and adding the ui-component annotation

**Comment by prachidamle** [comment]
@PennyScissors We also need the following change included and tested in the new version:
https://github.com/rancher/charts/pull/803

**Comment by aaronRancher** [comment]
This issue is verified with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version b2953cb`

Rancher-gatekeeper `v3.2.1`is available:
![Screen Shot 2020-12-08 at 2 07 17 PM](https://user-images.githubusercontent.com/57409052/101546574-38f59c80-3966-11eb-810f-d318c8e9d802.png)
![Screen Shot 2020-12-08 at 2 07 03 PM](https://user-images.githubusercontent.com/57409052/101546572-37c46f80-3966-11eb-8d80-91bd42d9e085.png)
OPA P1 use cases are verified. Upgrade path from Rancher v2.4.8 to v2.5 is verified.
