### ISSUE TITLE
Enabling monitoring on new cluster gives intermittent 500 errors and object has been modified error

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#30188]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create Rancher HA setup
2. Create API keys and plug into script below
3. Run the following script (delete cluster and re-run until you hit the problem.
```
export CATTLE_ACCESS_KEY=token-xxxxx
export CATTLE_SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxx
export HOST=myrancherserver.something.com

JSON="{\"name\":\"test-cluster\",
       \"description\":\"My Test Cluster\",
       \"rancherKubernetesEngineConfig\":{
         \"type\":\"rancherKubernetesEngineConfig\",
         \"version\":\"v1.19.4-rancher1-2\"
       },
       \"type\":\"cluster\"
      }"

echo json is $JSON

RESPONSE=`curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-H 'content-type: application/json' \
-H 'Accept: application/json'  \
-X POST \
-d "${JSON}" \
https://${HOST}/v3/clusters`

echo response is $RESPONSE
echo ""

CLUSTER_ID=`echo $RESPONSE | jq -r .id`

echo cluster id is $CLUSTER_ID
echo ""

curl -vu "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-H 'content-type: application/json' \
-H 'Accept: application/json'  \
-X POST \
-d "{\"version\": null}" \
https://${HOST}/v3/clusters/${CLUSTER_ID}?action=enableMonitoring
```

**Result:**
Sometimes this works, get 204 return code. But sometimes get:
```
{"baseType":"error","code":"ServerError","message":"failed to enable monitoring","status":500,"type":"error"}
```
And error in Rancher logs is:
```
2020/11/21 18:36:46 [ERROR] API error response 500 for POST /v3/clusters/c-lw2f9?action=enableMonitoring. Cause: Operation cannot be fulfilled on clusters.management.cattle.io "c-lw2f9": the object has been modified; please apply your changes to the latest version and try again
```

**Other details that may be helpful:**
Should be able to reproduce if you run it 3-4 times. Suspect you need a Rancher HA setup, did not test on single server setup.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.2
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AWS EC2 m5a.large
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12+k3s1", GitCommit:"56cd36302dc3188f21f9877d1309df7d80cd8b7d", GitTreeState:"clean", BuildDate:"2020-11-13T06:12:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
using k3s w/ containerd

**Comment by aiyengar2** [comment]
@dnoland1 Is there a particular reason why you enable cluster monitoring as a separate action rather than enabling it as part of the cluster spec itself? 

Instead of trying to trigger an action immediately on a cluster that just got created (I suspect that's why the errors are intermittent), the best practice would be to pass in [the relevant field(s)](https://github.com/rancher/rancher/blob/198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f/pkg/client/generated/management/v3/zz_generated_cluster_spec.go#L52-L53) directly while creating the cluster.

e.g.

```
export CATTLE_ACCESS_KEY=token-xxxxx
export CATTLE_SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxx
export HOST=myrancherserver.something.com

JSON="{\"name\":\"test-cluster\",
       \"description\":\"My Test Cluster\",
       \"rancherKubernetesEngineConfig\":{
         \"type\":\"rancherKubernetesEngineConfig\",
         \"version\":\"v1.19.4-rancher1-2\"
       },
       \"enableClusterMonitoring\":\"true\",
       \"type\":\"cluster\"
      }"

echo json is $JSON

RESPONSE=`curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-H 'content-type: application/json' \
-H 'Accept: application/json'  \
-X POST \
-d "${JSON}" \
https://${HOST}/v3/clusters`

echo response is $RESPONSE
echo ""
```

**Comment by ebauman** [comment]
This may be a terraform bug, but the user is using our Terraform tools as documented. they do the following:

```
resource "rancher2_cluster" "my-cluster" {
  name = "whatever"
  ...
  enable_cluster_monitoring = true
}
```

And by executing `tf apply`, this behavior is sometimes encountered.

**Comment by dnoland1** [comment]
@aiyengar2 I'm simulating the behavior of the rancher2 terraform provider. @rawmind0 is it by design for the tf rancher2 provider to make two APIs to create cluster and enable monitoring even when the `enable_cluster_monitoring` is defined in the rancher2_cluster resource?

**Comment by aiyengar2** [comment]
I see, you're referring to:

https://github.com/rancher/terraform-provider-rancher2/blob/34a9e52634ed75ed1769c07d8bceda550f076148/rancher2/resource_rancher2_cluster.go#L124-L173

If this is by design, maybe [the delay](https://github.com/rancher/terraform-provider-rancher2/blob/34a9e52634ed75ed1769c07d8bceda550f076148/rancher2/resource_rancher2_cluster.go#L147) needs to be increased? 

Maybe this was required to support earlier versions of Rancher before v2.2.0 when Monitoring was introduced?

**Comment by dnoland1** [comment]
I just tried on the Rancher UI and get an error. Created new cluster, then immediately went to Tools -> Monitoring and got:
![image](https://user-images.githubusercontent.com/468462/100017854-62bc9a00-2d90-11eb-86af-90f2dff15234.png)

**Comment by rawmind0** [comment]
> This may be a bug in our terraform provider, but the user is using our Terraform tools as documented. they do the following:

@ebauman is any user/customer having this issues??  Is there any issue opened at tfp?? Could you please provide an error log??

> @aiyengar2 I'm simulating the behavior of the rancher2 terraform provider. @rawmind0 is it by design for the tf rancher2 provider to make two APIs to create cluster and enable monitoring even when the enable_cluster_monitoring is defined in the rancher2_cluster resource?

@dnoland1 , what is the reason to simulate the behaviour of the tfp?? Is the issue happening just with tfp or is it a rancher API issue??

The reason to make 2 API calls instead of one is the chance to use custom monitoring config, you can't just using `"enableClusterMonitoring":"true"`. Anyway, it should work fine.

> If this is by design, maybe [the delay](https://github.com/rancher/terraform-provider-rancher2/blob/34a9e52634ed75ed1769c07d8bceda550f076148/rancher2/resource_rancher2_cluster.go#L147) needs to be increased?

@aiyengar2 this delay is just for start refreshing state. Anyway, if [enableMonitoring function is not available on cluster](https://github.com/rancher/terraform-provider-rancher2/blob/34a9e52634ed75ed1769c07d8bceda550f076148/rancher2/resource_rancher2_cluster.go#L157) the provider is re-reading the cluster before enable monitoring. 

> I just tried on the Rancher UI and get an error. Created new cluster, then immediately went to Tools -> Monitoring and got:

Seems that issue is on API

**Comment by aiyengar2** [comment]
So w.r.t. the API issue, the [current ActionHandler for Clusters](https://github.com/rancher/rancher/blob/b45ddae99be66fa45cd960735eae443be4064bae/pkg/api/norman/customization/cluster/actionhandler.go#L82) does not do any retry logic if it receives an object conflict error, so the object conflict error is returned directly to the user and the user is expected to retry. 

We can mitigate this by introducing [`retry.RetryOnConflict`](https://github.com/rancher/rancher/blob/master/pkg/controllers/management/auth/crtb_handler.go#L225) directly within the ActionHandler. This would should fix both the current terraform provider logic and the error outputted by the Bash script above. 


But IMO the terraform provider itself should be modified to pass in `enableClusterMonitoring=true` on creating the cluster since it's already part of the cluster spec rather [first creating a cluster with Monitoring disabled](https://github.com/rancher/terraform-provider-rancher2/blob/34a9e52634ed75ed1769c07d8bceda550f076148/rancher2/resource_rancher2_cluster.go#L124-L137) and then [trying to update the state with an action](https://github.com/rancher/terraform-provider-rancher2/blob/34a9e52634ed75ed1769c07d8bceda550f076148/rancher2/resource_rancher2_cluster.go#L169).

> The reason to make 2 API calls instead of one is the chance to use custom monitoring config, you can't just using `"enableClusterMonitoring":"true"`. Anyway, it should work fine.

@rawmind0 can you elaborate? Maybe I'm missing the point as to why we need to first create the cluster and then enable monitoring.

**Comment by rawmind0** [comment]
@aiyengar2 , the main reason for doing in that way is the chance to use custom monitoring config values, like enable persistence, adjust resources limits or requests, etc.. [ActionEnableMonitoring](https://github.com/rancher/rancher/blob/master/pkg/client/generated/management/v3/zz_generated_cluster.go#L164) function is used providing [MonitoringInput](https://github.com/rancher/rancher/blob/master/pkg/client/generated/management/v3/zz_generated_monitoring_input.go#L9) with answers and version. Also, tfp is checking that function is available at cluster before call it.

```
resource "rancher2_cluster" "foo-custom" {
  name = "foo-custom"
  description = "Foo rancher2 custom cluster"
  rke_config {
    network {
      plugin = "canal"
    }
  }
  enable_cluster_monitoring = true
  cluster_monitoring_input {
    answers = {
      "exporter-kubelets.https" = true
      "exporter-node.enabled" = true
      "exporter-node.ports.metrics.port" = 9796
      "exporter-node.resources.limits.cpu" = "200m"
      "exporter-node.resources.limits.memory" = "200Mi"
      "grafana.persistence.enabled" = false
      "grafana.persistence.size" = "10Gi"
      "grafana.persistence.storageClass" = "default"
      "operator.resources.limits.memory" = "500Mi"
      "prometheus.persistence.enabled" = "false"
      "prometheus.persistence.size" = "50Gi"
      "prometheus.persistence.storageClass" = "default"
      "prometheus.persistent.useReleaseName" = "true"
      "prometheus.resources.core.limits.cpu" = "1000m",
      "prometheus.resources.core.limits.memory" = "1500Mi"
      "prometheus.resources.core.requests.cpu" = "750m"
      "prometheus.resources.core.requests.memory" = "750Mi"
      "prometheus.retention" = "12h"
    }
    version = "0.1.0"
  }
}
```

As you mention, RetryOnConflict should mitigate the issue. Retry option can also be added on tfp, but IMO should fit better at api

**Comment by aiyengar2** [comment]
I'll draft a PR to add it to the API level and attach it to this issue. But w.r.t. the terraform provider, older versions of Rancher on/before 2.5.3 or 2.4.11 will still face this problem right?

Might make sense to also implement retry logic with the terraform provider as well to support those older versions.

**Comment by rawmind0** [comment]
> Might make sense to also implement retry logic with the terraform provider as well to support those older versions.

Agreed, i'll work on that tfp PR.

**Comment by jiaqiluo** [comment]
The bug is reproduced on `v2.5.3` single install setup 

The following modified script is used (the change is to get a random cluster name each time the script runs)

```
export CATTLE_ACCESS_KEY=token-xxxxx
export CATTLE_SECRET_KEY=xxxxxxxxxxxxxxxxxxxxx
export HOST=xxx.xx.xxx.xxx


JSON="{\"name\":\"test-$RANDOM\",
       \"description\":\"My Test Cluster\",
       \"rancherKubernetesEngineConfig\":{
         \"type\":\"rancherKubernetesEngineConfig\",
         \"version\":\"v1.19.4-rancher1-2\"
       },
       \"type\":\"cluster\"
      }"

echo json is $JSON

RESPONSE=`curl -k -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-H 'content-type: application/json' \
-H 'Accept: application/json'  \
-X POST \
-d "${JSON}" \
https://${HOST}/v3/clusters`

echo response is $RESPONSE
echo ""

CLUSTER_ID=`echo $RESPONSE | jq -r .id`

echo cluster id is $CLUSTER_ID
echo ""

curl -k -vu "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-H 'content-type: application/json' \
-H 'Accept: application/json'  \
-X POST \
-d "{\"version\": null}" \
https://${HOST}/v3/clusters/${CLUSTER_ID}?action=enableMonitoring
```


and after running the script about 5 times in a row 
```
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Expires: Wed 24 Feb 1982 18:42:00 GMT
< X-Api-Schemas: https://xxx.xx.xxxx.xxx/v3/cluster/c-lhjm7/schemas
< X-Content-Type-Options: nosniff
< Date: Thu, 03 Dec 2020 00:09:32 GMT
< Content-Length: 110
<
{"baseType":"error","code":"ServerError","message":"failed to enable monitoring","status":500,"type":"error"}
* Connection #0 to host xxx.xxx.xxx.xx left intact
* Closing connection 0
```

and in Rancher's logs
` 
2020/12/03 00:09:32 [ERROR] API error response 500 for POST /v3/clusters/c-lhjm7?action=enableMonitoring. Cause: Operation cannot be fulfilled on clusters.management.cattle.io "c-lhjm7": the object has been modified; please apply your changes to the latest version and try again
`

**Comment by jiaqiluo** [comment]
the bug fix is validated on the following Rancher version 
- v2.4-4378-head 8e306b57b
- master-head 6f96683ba16d711fb65df198c3cda17eef7bae37
- v2.5-head db350a63bc974b9a7173949ae056d55344b5601a

Run the same script 10 times in a row and do not see the error happen.
