### ISSUE TITLE
DNS issues when using host based networking

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#3018]
Hello,

Due to an unrelated failure, a number of our containers restarted earlier today.

We have two containers that use `host` networking mode and have the label `io.rancher.container.dns: true` applied. These hosts came online and couldn't resolve an external service we have linked in. 
They can resolve everything else we have linked but they could not resolve the external service. 

Interestingly, the service was present in each of the IP address sections in the `answers.json` on both hosts but crucially not listed in the `default` section of the same file.

```
Component	Version
Rancher	v0.47.0
Cattle	v0.115.0
User Interface	v0.68.0
Rancher Compose	v0.5.3
```

External service is defined with two ip's as per below:
```
Portal:
  external_ips:
    - $PORTAL1_IP
    - $PORTAL2_IP
```
Other hosts in the stack can see the Portal linking but not this one, could this be a bug? I've got the system in this state now so can diagnose.

**Comment by alena1108** [comment]
@Rucknar its a bug in all versions prior to v49: external services are not resolvable to host level containers, whether its linked or otherwise. Got fixed with the refactoring we've done around forming dns data. Good catch, thanks for reporting it. Hold on upgrading to v49 though, there was some performance bug we've addressed that is gonna be available in v50 (which is gonna be released early this week)

@sangeethah we have to add more tests for containers on host networking :) We should make sure all kinds of rancher services - external/alias/regular service can be resolved from host container.

**Comment by Rucknar** [comment]
Thanks @alena1108 I'll hold on until 50 is out the door. Happy for you to close this if you wish?

**Comment by alena1108** [comment]
@Rucknar I can't be completely happy till it's validated by our QA :) So lets @sangeethah close it.

**Comment by sangeethah** [comment]
Tested with server version - v0.50.0-rc4

From containers that belong to services with networking set to "host"  and "io.rancher.container.dns" set to "true" , able to resolve external servives /alias services /regular services,
