### ISSUE TITLE
Kubectl error "You must be logged in to the server"

### ISSUE THREAD

**Issue by Nicolas-TS** [rancher/rancher#30230]
SURE-3029
SURE-3609
SURE-3394

Hi everyone !

**What kind of request is this (question/bug/enhancement/feature request):**

Question or bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a LDAP user (FreeIPA) on a project (owner, member ...)
2. Launch the kubectl command (through Rancher UI or using the kubeconfig file) : It must works
3. After 24 hours, when the user execute a kubectl command, the following error is displayed : 
```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

**Result:**
 error: You must be logged in to the server (the server has asked for the client to provide credentials)

**Other details that may be helpful:**
- LDAP Authentication : FreeIPA
- Certificates signed by an intern PKI (CA Cert is imported during IPA connector configuration)
- Rancher upgraded from 2.1.8 to 2.4.5
- Problem still exists with a Rancher 2.4.5 fresh install
- Identified workaround : User has to delete his tokens to regenerate them when he gets his new kubeconfig file
- No problem with local users 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher 2.4.5
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Vsphere Cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Virtual Machines
- Kubernetes version (use `kubectl version`): v1.18.3
- Docker version (use `docker version`): 19.3.11

Thank you for your help !

Nicolas

**Comment by Nicolas-TS** [comment]
Hello,

Additional information :

Just see that through the API v3/token that tokens are not expired but enabled is set to false :

```
"authProvider": "local",
"baseType": "token",
"clusterId": null,
"created": "2020-11-24T14:59:46Z",
"createdTS": 1606229986000,
"creatorId": null,
"current": false,
"description": "Kubeconfig token",
"enabled": false,
"expired": false,
"expiresAt": "",
"groupPrincipals": null,
"id": "kubeconfig-u-5oz67ae73y",
```

The "enabled" field goes from "true" to "false" after ~24 hours. I didn't have this behavior in Rancher 2.1.8.

**Comment by papanito** [comment]
> Identified workaround : User has to delete his tokens to regenerate them when he gets his new kubeconfig file

definitively helped me ;-)

**Comment by nikhilno1** [comment]
I am facing same problem. I did AD configuration yesterday and today I am facing this issue.
How do I delete the tokens for the user as mentioned in the workaround?

> Identified workaround : User has to delete his tokens to regenerate them when he gets his new kubeconfig file

**Comment by nikhilno1** [comment]
Found it. You have to click on the Avatar and select "API & Keys". Thanks for the workaround.

**Comment by nikhilno1** [comment]
Hello, in my setup I have to keep doing this workaround every hour or so (delete the key, fetch and update the new kubeconfig file). This is quite annoying. Any idea why this is happening and how I can fix it?

**Comment by Nicolas-TS** [comment]
Hi,

I don't have a technical solution for the version 2.4.5.

We have done an upgrade of Rancher (to 2.5.3) and we use another LDAP directory (openldap) for the authentication.

And now, we have no more this issue (token are still available after 24 hours).

**Comment by nikhilno1** [comment]
I am on latest version (v2.5.5) and even removed the Active Directory configuration. Still facing the problem.
After a few minutes of doing the workaround (deleting the keys and generating new kube-config), the problem is seen again.
When I see the v3/tokens/ API, I can see the enabled flag has been changed to false.
`"enabled": false,`

If I try to change it back to true, I get 404 error. 
```
{
"baseType": "error",
"code": "NotFound",
"message": "no store found",
"status": 404,
"type": "error"
}
```

I have tried many options, using tokens, CLI authentication but the same problem is seen.

**Comment by michalgar** [comment]
Hi, we are experiencing the same problem.
The workaround of deleting the API token works, but only temporarily.
Did anyone manage to solve it? Any insights on this, please?

**Comment by nikhilno1** [comment]
Re-install with wiping out the DB.

**Comment by StrongMonkey** [comment]
reopen for investigation

**Comment by StrongMonkey** [comment]
@SheilaghM This needs more investigation as we need to reproduce in our setup. As mentioned before, this is caused by our refreshing logic not being able to recongize users so token that belongs to these user are disabled.

**Comment by gauravbodar** [comment]
We are facing exact same issue. However we have removed and reinstall rke for rancher host and now we are trying to import existing cluster. but all existing kubernetes clusters are locked and throws the above error. so not sure how to import them again in rancher

**Comment by CNOITServices** [comment]
> We are facing exact same issue. However we have removed and reinstall rke for rancher host and now we are trying to import existing cluster. but all existing kubernetes clusters are locked and throws the above error. so not sure how to import them again in rancher

Currently facing the same issue, were you able to solve this?

**Comment by MbolotSuse** [comment]
Has anyone experienced this issue with 2.6.3?

I'm thinking that this is caused by an integer overflow in [v2.5 of the go-ldap package](https://github.com/go-ldap/ldap/blob/v2.5.1/error.go#L119). We use that version in rancher up until 2.6.3, where we used [v3.4](https://github.com/go-ldap/ldap/blob/v3.4.1/error.go#L209). V3.4 has a larger destination int (there's still potential for overflow, but the result code would have to be substantially higher), so the overflows shouldn't happen (according to the [IANA](https://www.iana.org/assignments/ldap-parameters/ldap-parameters.xhtml#ldap-parameters-6) 4096 is the current highest error code, so uint16 should be sufficient). 

The reasoning here is that rancher is because of this overflow, rancher isn't seeing the errors, so it's disabling the kubeconfig tokens (since it thinks that the errored searches indicate that the user lost access). It would help to know if people are still experiencing the issue on 2.6.3, as that would indicate the issue is elsewhere.

**Comment by samjustus** [comment]
this was solved in 2.5.12 and we will reopen if we see again

**Comment by Nox-404** [comment]
Hello,
I'm facing the same issue with `v2.4.5`, is there a way to backport this fix ?

**Comment by lukibahr** [comment]
I'm facing the same issue un 2.6.3.

**Comment by hoerup** [comment]
Hmm forgot to write back here - but even after upgrading to 2.5.12 we kept running into the issue 
But then I got the idea of giving privs directly to individual users instead of via LDAP groups - and the issues disappeared !

**Comment by Nox-404** [comment]
@hoerup I'll try it out tomorrow then.

Thx for the tips
