### ISSUE TITLE
grsecurity

### ISSUE THREAD

**Issue by WnP** [rancher/rancher#3025]
Hi,

I'm trying to run `rancher/server` using the docker image on a grsecurity kernel, but it crash with:
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000654241000000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
```
and nothing in `dmesg`
any idea?

**Comment by WnP** [comment]
you can find the complete logs [here](http://sprunge.us/SAQK)

**Comment by ibuildthecloud** [comment]
Looks like grsec disables something Java needs by default (rwx memory pages for JIT).  I don't know much about grsec but you need to disable mprotect for the Java process.  Now the tricky thing is how do you do that with a container.... I don't know.

**Comment by propyless** [comment]
Hello,

I've been hitting this issue as well,but since you seem willing to solve it but unsure of how..
I found this dockerfile `https://hub.docker.com/r/pindar/kibana/~/dockerfile/` and it seems to install paxctl and run the following command:

`paxctl -c -m out/Release/mksnapshot`
What you'll need to add for rancher is:
` paxctl -c -m /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java`

I'm basing this off my logs in dmesg:
`grsec: denied resource overstep by requesting 4096 for RLIMIT_CORE against limit 0 for /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java[java:5192] uid/euid:0/0 gid/egid:0/0, parent /usr/bin/s6-supervise[s6-supervise:5136] uid/euid:0/0 gid/egid:0/0`

What the flags do:
```
-c: convert PT_GNU_STACK into PT_PAX_FLAGS (see manpage!)
-m: disable MPROTECT
```

Now.. I'm quite new to docker so I'm wondering if theres a way to change dockerfiles that i've pulled from dockerhub before running them?
So I can test and see if the above solution works.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/116
