### ISSUE TITLE
PVC seen Active when status shows "Resizing"

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30319]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cloud provider enabled cluster (AWS)
- Create a storage class with allowVolumeExpansion:true
- Create a PVC using this Storage say with storage - 10G
- Edit the PVC and resize - 20G
- The PVC/volume gets resized. (when this PVC is attached to a workload/pod)
- Edit the pvc again and resize it to 30G now
- It does not resize the volume anymore
- View in API of the PVC shows:

```
conditions": [
{
"lastProbeTime": null,
"lastTransitionTime": "2020-12-03T01:29:57Z",
"lastTransitionTimeTS": 1606958997000,
"status": "True",
"type": "Resizing"
}
],
```
- But the PVC is still Active state
- Kubectl describe pvc pvc-1 gives
```
Type     Reason              Age   From           Message
  ----     ------              ----  ----           -------
  Warning  VolumeResizeFailed  56m   volume_expand  error expanding volume "default/new" of plugin "kubernetes.io/aws-ebs": AWS modifyVolume failed for vol-0fa443c9da1d992 with VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
           status code: 400, request id: 111153f7-0476-464a-a0a9-69bec48410ac
  Warning  VolumeResizeFailed  40m  volume_expand  error expanding volume "default/new" of plugin "kubernetes.io/aws-ebs": AWS modifyVolume failed for vol-0fa443c9da1d992 with VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
           status code: 400, request id: 9ca07c4c-704c-4d42-afdc-ea7bf47822fa
```

**Expected Result:**
Is there a way this message/ "Resizing" status appear on the PVC ? 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `db350`
- Installation option (single install/HA): single
 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Cloud provider aws nnode driver
- Kubernetes version (use `kubectl version`):

```
1.19.4 (any)
```

**Comment by westlywright** [comment]
@sowmyav27 This is technically not a bug. In the UI the column you are referring to is `State`. If you look at the state on the PVC in the API you'll see it's still bound. The state badge is a pattern we use for all resources in tables. Since conditions is an array of condition resources it does not makes sense to show these in the table. Instead what Ive done is added the conditions on the detail page of the PVC. This is the pattern we follow for Pods, Containers, and other resources that have conditions. One thing to note here is that the Conditions will be titled as Status, I understand this could be confusing but again this is the pattern that is followed for other resources and conditions through the UI. I wont be changing this title/description for 2.5.4, since it touches so many places I believe it to be too risky this late in the cycle.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cbc` and master-head - commit id: `278c1f988`**

- Deploy a cloud provider enabled cluster (AWS)
- Create a storage class with allowVolumeExpansion:true
- Create a PVC using this Storage say with storage - 10G
- Edit the PVC and resize - 20G
- The PVC/volume gets resized. (when this PVC is attached to a workload/pod)
- Edit the pvc again and resize it to 30G now
- PVC details page shows Status -- Resizing

<img width="1285" alt="Screen Shot 2020-12-08 at 9 51 59 PM" src="https://user-images.githubusercontent.com/26032343/101590671-bab5ec00-399f-11eb-88f3-5b3be57386cc.png">
