### ISSUE TITLE
Update import command display for EKS clusters

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30337]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Create/import an EKS cluster with private only API endpoint

**Result:**
The import command pops up correctly, but it is too generic. The recommendations are:
 1. the references to GKE should be removed
 2. the display should have an explanation telling the customer something like:
	"You are (creating/importing) an EKS cluster that has private API access only. In order to complete the setup, you must run one of the following commands manually."

**Comment by aaronRancher** [comment]
This issue is verified with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version b2953cb`

Import command display has been updated:
![Screen Shot 2020-12-08 at 4 57 15 PM](https://user-images.githubusercontent.com/57409052/101555785-91cd3100-3976-11eb-9d9e-3b809f854611.png)
