### ISSUE TITLE
Disable default backend by default for ingress-nginx

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#30356]
This should only be done _**after**_ 1.20+ is the default Kubernetes version for Rancher.
Currently, we expose the option to disable the default backend (#25590). However, it is still enabled by default.

This will most likely require a change to [RKE](https://github.com/rancher/rke) and [KDM](https://github.com/rancher/kontainer-driver-metadata).

**Comment by deniseschannon** [comment]
@nickgerace Are we saying that we want this disabled starting 1.20 or after 1.20?

**Comment by nickgerace** [comment]
Starting once 1.20 becomes the default version. Regardless, I'll double check again with upstream

**Comment by cbron** [comment]
Moving to release candidate since 1.20 will be default in 2.5.7 or 2.6.

**Comment by sirredbeard** [comment]
If this can't be done until after 1.20 and 1.20 is default in 2.6, this may need to come out of 2.6.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/31567

**Comment by bmdepesa** [comment]
See https://github.com/rancher/rancher/issues/30272

**Comment by anupama2501** [comment]
Reopening this ticket as from offline discussion with @kinarashah and @nickgerace it is yet to be decided if we continue with the current implementation of UI & rke having disabled & enabled by default for default ingress backend for k8s versions <= 1.20 and disabled & disabled by default for k8s > 1.20 respectively.

**Comment by kinarashah** [comment]
@sowmyav27 @cbron @deniseschannon  In Rancher v2.5.4, we introduced a new flag to turn on/off default-backend for nginx ingress. The idea was to disable it only for k8s >=1.21. But UI passed default false for all k8s versions and RKE didn't. This causes some difference in behavior between clusters created via UI and API (API is same as using RKE standalone to create clusters). 

I think we don't need to fix this to make the behavior same across UI and API because 
- It'll eventually become same with k8s 1.21 in Rancher 2.6 which is our default k8s version.  
- Users haven't complained about this difference or there's no issues resulting because of it. 
- Users always have a way to enable/disable it, this only concerns the default behavior. 

----------------------------------------------------------------------------------------------------------------------
Rancher v2.5.4 only supports <=1.20 clusters, so the behavior would be:
| Clusters | Flag value | k8s version | 
| ---- | ---- | --- | 
| Rancher provisioned RKE clusters via UI | false | all | 
| Rancher provisioned RKE clusters via API | true |  < 1.21 | 
| RKE standalone clusters | true | < 1.21 | 

Rancher v2.6 now supports >=1.21 clusters, so the behavior would be: 
| Clusters | Flag value | k8s version | 
| ---- | ---- | --- | 
| Rancher provisioned RKE clusters via UI | false |  all | 
| Rancher provisioned RKE clusters via API | false |  >=1.21 | 
| RKE standalone clusters | false | >=1.21 | 
| Rancher provisioned RKE clusters via API | true |  < 1.21 | 
| RKE standalone clusters | true | < 1.21 |

**Comment by cbron** [comment]
So to summarize: the UI started disabling this by default ahead of time, even though the API didn't. But now once 1.21 comes out in Rancher it will be disabled by default everywhere. 

@nickgerace / @kinarashah one thing that isn't clear to me is what happened in k8s 1.20 / 1.21 that made us wait for this change ?

**Comment by nickgerace** [comment]
@cbron if I remember correctly, the reason was based on this: https://github.com/kubernetes/ingress-nginx/pull/3196#issuecomment-452273871

However, I believe this was likely a miscommunication since the `v0.20.0` version for ingress-nginix does not correspond to Kubernetes, but to the controller itself.

Fortunately, despite the probable miscommunication, I think our current defaults are satisfactory given its behavior.

**Comment by anupama2501** [comment]
Verified on master-head be7cdb8

**Fresh install** 

- Node driver downstream clusters on k8s v1.19.12-rancher1-1, v1.20.8-rancher1-1, v1.21.1-rancher2-1 have `nginx Default Backend` disabled by default on UI
- Node driver downstream cluster on k8s v1.19.12-rancher1-1 has `Nginx Default Backend` enabled by default via API v3

**Upgrade: v2.5.3 to master-head be7cdb8**

- Downstream node driver clusters on v1.16.15, v1.17.17, v1.18.20, v1.19.12 have ` Nginx Default Backend` enabled by default
- Created a few workloads and load balancers in each cluster.
- Upgraded the cluster to master-head
- Verified all the clusters after upgrade have `Nginx Default Backend` set to enabled.


Waiting on https://github.com/rancher/rancher/issues/33749 for an upgrade validation

**Comment by anupama2501** [comment]
- Created 4 clusters on rancher server v2.5.3 with k8s `v1.16.15, v1.17.17, v1.18.20, v1.19.13`
- Upgraded to the master-head 3499046 
- Created a few workloads on the clusters with k8s `v1.16.15, v1.17.17, v1.18.20`
- Upgraded the k8s to versions v1.19.3 and v1.20.9 and verified the clusters have gone to `updating`, `upgrading` and `active`.
- Scaled the workloads created in above step and created new workloads and verified have come up active.
- Created a cluster on k8s `v1.21.1` with `Nginx default Backend` is disabled by default
