### ISSUE TITLE
[Question] A Kubernetes cluster at two locations?

### ISSUE THREAD

**Issue by bor8** [rancher/rancher#30352]
**What kind of request is this (question/bug/enhancement/feature request):**
Question:
Is it practical to install one Kubernetes cluster at two locations? etcd causes problems when the "bigger" location goes offline. Will the RAFT algorithm ever be improved in this respect?

**Steps to reproduce (least amount of steps as possible):**
Create cluster with 3 etcd/masters at location A and 2 etcd/masters at location B.
Install Rancher HA inside cluster.
Bring location A offline.

**Result:**
If A goes offline B will only throw etcd timeouts. :(

![grafik](https://user-images.githubusercontent.com/5301068/100779755-1fee6800-3409-11eb-9708-b19f6fab6883.png)

**Other details that may be helpful:**

![grafik](https://user-images.githubusercontent.com/5301068/100779249-67c0bf80-3408-11eb-9b70-bdc0ac94f979.png)

A bit more failure tolerance would be nice!?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): HA

**Comment by maxisam** [comment]
I thought about this issue too.  https://kubernetes.io/docs/setup/best-practices/multiple-zones/ 

I think the best solution is having 3 regions.

**Comment by bor8** [comment]
I understand that I need three locations instead of two. What do all those companies do that "only" have two locations? I want to host everything myself.

**Comment by vincent99** [comment]
If you have 2 locations you want to be independent then they need to be separate independent clusters, not members of one combined cluster.

Having a strict majority (and therefore an odd number) of nodes is a very fundamental constraint of how a distributed system decides what the truth is.

If the connection between the locations is cut, which one is in charge and should keep accepting writes?  Neither one knows if the other is dead forever or still running but unreachable to it.  If they accept writes then you have now 2 diverging states ("split brain") which can't necessarily be reconciled once the link is back up.  So what it does is they don't accept writes, and neither can be changed until a majority can agree on them.

Significant latency between members also severely impacts the write performance of the database, because they have to be acknowledged by a majority before they can be accepted.  So if they are physically far apart you'd want separate clusters even if you had 3 locations.

**Comment by bor8** [comment]
Apart from the fact that I use an odd number (five), this is what I do now - separate clusters. Now comes the next problem: I don't want to use S3 backup in Longhorn, but NFS. How do I get it mirrored safely now? I think I will use a little script or cronjobs after all.

**Comment by bor8** [comment]
So, I hold on: With one location it works of course (as long as the location remains online). With two locations you have a problem when the "larger" location goes offline. With three locations it works again (at least if two or all three locations do not fail at the same time).

I have started reading many Kubernetes books. Most of them say that you're fine with 5 etcd instances. Not true if you have two sites.

**Comment by vincent99** [comment]
You are "fine" for the failure of up to any 2 nodes out of those 5.  Etcd doesn't know or care where they are physically located, other than latency controlling performance.

The problem is you are adding an external point of failure by connecting 3 of them within the same rack/building/internet connection/power provider/etc, separate from the other 2.

This introduces many ways for those 3 to all fail to be able to reach the other 2 simultaneously.  Which you don't have to worry about if all 5 were independent, or if all were together.

**Comment by bor8** [comment]
Yes.
