### ISSUE TITLE
[Logging v2] Handle log rotating kubelet logs in cloud providers GKE/AKS/EKS

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#30383]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Setup a GKE/AKS/EKS cluster and log rotate the logs (or wait and wait until it's triggered)
- The log file would be now empty and a gz file is created.

**Result:**

Rancher is collecting the kubelet logs from the **AKS nodes** from this path: `/var/log/azure/kubelet-status.log`
Rancher is collecting the kubelet logs from the **GKE nodes** from this path: `/var/log/kube-proxy.log`
Rancher is collecting the kubelet logs from the **EKS nodes** from this path: `/var/log/messages`

We should collect the logs even if they were rotated.

Logging Chart version: `3.8.201`

**Environment information**
- Rancher version: 
  - `v2.5-head (12/08/2020)` _8d759be_
   - `master-head (12/07/2020)` _a5e40aa_
- Installation option (single install/HA): HA

**Comment by nickgerace** [comment]
We are closing this issue since log rotation is handled by fluentbit.

## Investigation Results for EKS

- EKS is logging to `/var/log/messages`
- Logging is installed and we set EKS logs collect to enabled
- Logs collected from `/var/log/messages` are sent to the Output
- `/var/log/messages` is rotated to `/var/log/messages-INSERTDATE.gz`
- `/var/log/messages` is recreated as an empty file by logrotate
- Logging keeps monitoring `/var/log/messages` (although empty), and it will collect once the file is populated by a service/system proc

*Note: this investigation was only in EKS, but applies to AKS and GKE as well due to how logrotate works (universal on nix systems with a given `logrotate.conf` and` logrotate.d/*`)*

## Findings
Fluentbit handles log rotation by default, including the lag time between rotation and new file creation.

> From the [docs](https://docs.fluentbit.io/manual/pipeline/inputs/tail): "Note that the Path patterns cannot match the rotated files.
> Otherwise, the rotated file would be read again and lead to duplicate records."

Logging rotated files or archives would be an anti-pattern.
Fluentbit includes default protections/settings for handling rotated files, including `Rotate_Wait` with a default setting of 5 seconds (specifies the number of extra time in seconds to monitor a file once is rotated in case some pending data is flushed).

## Future Considerations
We may want to add customizable settings for dealing with rotated files based on the following issues.

- https://github.com/fluent/fluent-bit/issues/2847
- https://github.com/fluent/fluent-bit/issues/2110

The settings would potentially include the following:

- `Rotate_Wait`
- `Refresh_Interval`
- `Mem_Buf_Limit`

We would essentially add these to `values.yaml `as optional fields, but that is a **future** consideration once we need it.
