### ISSUE TITLE
[UI] In k8s v1.20 "delete local data" for drain has been renamed to "delete empty dir data."

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30386]
Need to investigate what's the impact on UI from this change [here](https://github.com/kubernetes/kubernetes/pull/95076)

**Comment by westlywright** [comment]
I am not sure there is a ton that should happen here from the UI. `drain` is an action on the cluster object, drain takes several inputs, one being `deleteLocalData`. I do not think the param name should be changed on the front end since this is an action, the backend should be able to easily parse the cluster version and flip the correct flag for the respective k8s version. Then there is no breaking api change on our end between k8s versions and we dont need to introduce a bunch of weird logic into the UI. If the change is a must, I would think the api action for drain would need two params names, one for the old param and one for the new, the UI will have to parse the k8s version of the cluster and flip the correct flag for the drain modal action. I dont like this though cause then API users now have to understand why the two fields exist. I suppose the action could return different param names depending on the k8s version but going that route doesn't make sense because you're now got to make changes to the backend to do and the front end to deal with dynamic action params, that seems like the worst option.

 @deniseschannon or @vincent99  What are your thoughts?

**Comment by vincent99** [comment]
Yeah I could see updating the checkbox label in the UI but don't see any reason to change/break the API field name.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `8201e080` and master-head commit id: `fbe2c30`**

- `Delete Empty Dir Data` field is seen on the UI while creating a cluster.
- In the API request `deleteLocalData: true` is sent when this field is enabled.
