### ISSUE TITLE
Cluster Explorer Apps/Marketplace is completely broken in Firefox

### ISSUE THREAD

**Issue by MG2R** [rancher/rancher#30423]
I use Firefox as my main browser. The old UI works splendidly, but ever since Cluster Explorer and especially the App Marketplace has been forced down upon me, I've had to start using Chrome. Can you please make Cluster Explorer work in Firefox?

**Comment by vincent99** [comment]
Everything we do is free, open source, and nobody is "forcing" anything on you.

The cluster manager UI still exists, and works the same as it always has.  It will continue to through at least including 2.6.

Explorer works fine in Firefox.  We test it.  And Safari.  I use them all periodically.  Various other employees including our chief architect use Firefox exclusively.

It's somewhat slower with a lot of data because [js proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) are used to maintain all the state from the server and the implementation of them in Firefox is about 100x slower than Chrome, but is still perfectly usable normal uses.

If you have specific, actionable, reproducible problems, report them.

**Comment by MG2R** [comment]
You're absolutely right. I'm sorry. This issue was created in frustration. That was wrong of me. I'll try to do better next time. Thanks for your work!
