### ISSUE TITLE
[Backport] 2.4: Add filter option for template GET request

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#30497]
**Original Issue:**
https://github.com/rancher/rancher/issues/29773

**Comment by jiaqiluo** [comment]
this is validated on rancher:v2.5-head 23eee56

**Steps:**
- run rancher with passing the parameter `CATTLE_SERVER_VERSION`
```
docker run -d \
  --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -e CATTLE_SERVER_VERSION=2.4.11\
  rancher/rancher:v2.4-head
```
- add clusters with different k8s versions 

![image](https://user-images.githubusercontent.com/6218999/102943001-17230c00-4474-11eb-9d93-932ea6954c3a.png)

- add the following repo as a global repo 
```
repo:     https://github.com/jiaqiluo/system-charts
branch: k8s-limit
---

add two new versions for the rancher-monitoring chart:

for 0.1.4, no kubeVersion is set
for 0.1.5 I set: kubeVersion: ">=1.16.0 <1.18.10" in Chart.yaml
for 0.1.6 I set : kubeVersion: ">1.18.0" in Chart.yaml
```

 
Here are the versions showing on each cluster 
k8s version | template version
------------| ---------------
v1.18.13| 0.1.4, 0.1.6
v1.17.14| 0.1.4, 0.1.5 
v1.16.15| 0.1.4, 0.1.5 
v1.15.12| 0.1.4

Note `0.1.4` shows in the list because the `kubeVersion` filed is not set in its chart.  

![image](https://user-images.githubusercontent.com/6218999/102943310-e0012a80-4474-11eb-9d06-7e85df0434f1.png)


I also tried with a [modified WordPress chart](https://github.com/jiaqiluo/charts/tree/test-k8s-limit/charts/wordpress) cloned from the rancher/charts GH repo, and it also works as expected.
