### ISSUE TITLE
[Fleet] Ensure Windows clusters run agents

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30516]
Ensure that when a Windows clusters is added to Fleet, the agent runs on the cluster and the manifests can be applied. 

gz#13922

**Comment by brianharwell** [comment]
The fix is to add the following to the deployment...
```
tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```

**Comment by nickgerace** [comment]
Thanks @brianharwell. We are actually evaluating running at least one component with a Windows container rather than just scheduling them all to run only on Linux nodes. Keep an eye on this ticket :)

**Comment by brianharwell** [comment]
Thanks @nickgerace but I don't think think having the Fleet agent run in Windows is required. In a Linux+Windows cluster a Linux worker is required and Fleet can run on that worker or any other Linux worker. Fleet responds to git events and deploys a manifest or Helm chart to the cluster. Fleet does not need to run in Windows or have ANY knowledge of Windows.

**Comment by nickgerace** [comment]
That is correct @brianharwell; it is not required. However, evaluating when to have a native Windows container manifest is motivated by distributing the load, so to speak. Taking that route over scheduling may give users more leeway in how thin/thick they want to provision their Linux or Windows nodes.

**Comment by brianharwell** [comment]
Right on, so giving the option to host on Windows workers will help with redundancy. But, seeing that ingress will only work on Linux nodes, wouldn't a production environment need multiple Linux workers anyway?

**Comment by nickgerace** [comment]
There are use cases where an ingress controller would provide little benefit, even in production. If you require an ingress controller though, that is correct. We would like to enable the option, if possible.

**Comment by brianharwell** [comment]
Agreed but correct me if I am wrong, in ANY Kubernetes cluster you need AT LEAST 1 linux worker because Kubernetes requires some non control plane or etcd workloads in order to function.

**Comment by nikkelma** [comment]
You would only need a Linux worker if some deployed component can't tolerate being on the control plane. As far as I understand, this is currently unlikely in Windows cluster, as many tools in the ecosystem don't have a model that allows "run control components on Linux nodes, run per-node components on Windows nodes" similar to flannel.

Do you have any specific use cases in mind (in addition to Ingress controllers) that would fully guarantee some Linux worker nodes in a Windows cluster?

**Comment by brianharwell** [comment]
The 2 that come to mind are CoreDns and Metric Server. I guess my question is if I were to create a new cluster in Rancher and add only nodes that have the control plane and etcd role will I have a functioning cluster? I would say no because I would need at least one linux worker. Even in a linux+windows cluster I need at least one linux node because CoreDns will not run on Windows nodes.

I do like the idea of having the option to run Fleet on Windows but we would choose to run Fleet on linux nodes due to the resource requirements of Windows containers. Better to use those resources for our app workloads and use linux for Kubernetes workloads.

**Comment by nickgerace** [comment]
When creating a cluster with existing nodes in Rancher, you can use a single Linux node for a Windows cluster. In my test clusters, my sole Linux node not only has the the `controlplane` and `etcd` roles, it has the `worker` role as well.

Now, what about without the `worker` role on the sole Linux node? I have never tested this configuration. I do not see why it would not work (barring issues with applications not having Windows manifests), but I could be wrong there.

**Comment by brianharwell** [comment]
I remember reading somewhere (can't find it) that a linux worker was required in a Windows cluster because there are some kube system workloads that will not run on Windows. Either way, I think supporting the option of running Fleet on Windows is ultimately a good thing.

**Comment by nikkelma** [comment]
I know of a few internal conversations happening where coredns and the metrics server are being considered to tolerate the `CriticalAddonsOnly` taint, since these workloads are nearly as important as control-plane / etcd components. In RKE2 the control-plane and etcd both run as static pods, so it would even make sense to run coredns and the metrics server as more pods on that control plane, and then allow this consistent pattern in k3s as well (running coredns + metrics server pods on `server` nodes tainted with `CriticalAddonsOnly`.

Appreciate your perspective and discussion around whether this is a useful feature / improvement, always great to hear of concrete use cases and concerns.

**Comment by nickgerace** [comment]
It appears in at least one place on our docs site. Here's a location that @izaac pointed out: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/

> there must be at least one worker node that is run on Linux in order to run the Rancher cluster agent, DNS, metrics server, and Ingress related containers

Continuing the discussion though: if we give all the "Linux worker" essentials a toleration for the `CriticalAddonsOnly` taint, then I do not see why this wouldn't be poissble.

**Comment by nickgerace** [comment]
The fleet-example is up for PR (https://github.com/rancher/fleet-examples/pull/5), but can currently be used from the developer fork.

```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-local
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - windows-helm
```

**Comment by izaac** [comment]
Rancher version: `v2.5-head (02/10/2021)` _761c805_
Fleet chart version `v0.3.4-rc4`
Rancher RKE HA Setup. k8s v1.19.7

## Downstream Windows clusters

### Cluster 1

- Network Flannel VXLAN
- Windows 1909
- k8s v1.20.2

Error found:
```
Error: failed to start container "fleet-agent": Error response from daemon: container fleet-agent encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"C:\u000cleet\u000cleetagent-windows.exe","WorkingDirectory":"C:\\","Environment":{"CHECKIN_INTERVAL":"0s","GENERATION":"10908c39-0f7d-4b90-97d1-ea81e5eba7f5-2","KUBERNETES_PORT":"tcp://10.43.0.1:443","KUBERNETES_PORT_443_TCP":"tcp://10.43.0.1:443","KUBERNETES_PORT_443_TCP_ADDR":"10.43.0.1","KUBERNETES_PORT_443_TCP_PORT":"443","KUBERNETES_PORT_443_TCP_PROTO":"tcp","KUBERNETES_SERVICE_HOST":"10.43.0.1","KUBERNETES_SERVICE_PORT":"443","KUBERNETES_SERVICE_PORT_HTTPS":"443","NAMESPACE":"fleet-system","RELEASES":"releases.rancher.com","VERSION":"v0.3.4-rc4"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```

### Cluster 2

- Network Flannel Host GW
- Windows 1809
- k8s v1.20.2

Error found:

```
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "632b8d6022580dbdbfaa5a75e3255b6803c2759a2af339e1dab757333f88ed7f" network for pod "fleet-agent-7cdfd4d775-k4tnn": networkPlugin cni failed to set up pod "fleet-agent-7cdfd4d775-k4tnn_fleet-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.
```

**Comment by izaac** [comment]
Cluster 2 in above comment I had to deploy it again as Windows 1809 should be installed with Kubernetes 1.17

After doing this I see the same error as Cluster 1, File not Found

`(0x2) extra info: {"CommandLine":"C:\u000cleet\u000cleetagent-windows.exe`

**Comment by sowmyav27** [comment]
Same issue seen on 2.5-head - commit id: `761c805d` on a windows 2004 cluster using k8s 1.19.7-rancher2-1
```
Error: failed to start container "fleet-agent": Error response from daemon: container fleet-agent encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"C:\u000cleet\u000cleetagent-windows.exe"
```

**Comment by nickgerace** [comment]
@izaac that's good that we were able to narrow it down. Thanks as well @sowmyav27.
Testing a fix locally.

**Comment by izaac** [comment]
Rancher version `v2.5-head (02/17/2021)` _03b8153_
Fleet version `v0.3.4-rc5`

## All Windows Cluster installs VXLAN (with 1909 also doing GW Host)

### Clusters states in Fleet

![Screen Shot 2021-02-17 at 5 21 49 PM](https://user-images.githubusercontent.com/27659/108285589-a717c600-7144-11eb-82d8-e20aa7c331f6.png)



### Windows 1809

`v1.17.17-rancher2-1`

I am getting the following error as well as Zero nodes ready in Fleet:

`
time="2021-02-17T23:23:39Z" level=error msg="Failed to register agent: Get \"https://10.43.0.1:443/api/v1/namespaces/fleet-system/secrets/fleet-agent\": dial tcp 10.43.0.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
`



### Windows 1903

`v1.18.9-rancher1-1` <- Works
`v1.18.15-rancher2-1` (?) - <- Fails (EOL?)

Both have the same Windows 1903 version on workers, Docker 19.03, etc
Fleet fails to deploy in v1.18.15 is that due to the 1903 EOL?  Rancher v2.5.6 has 1.18.15 as default 1.18 k8s

### Windows 1909

`v1.19.2-rancher1-1`
Zero nodes ready in Fleet

Cluster GW Host shows 0 nodes ready in Dashboard but Active.

Error from Fleet pod logs (VXLAN):

`Warning | FailedCreatePodSandBox | (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "d69a228fda34d79769498f6dafd96bf9deb0d0e564b17a728e1a437c20478769" network for pod "fleet-agent-6fb968ddb5-4c74r": networkPlugin cni failed to set up pod "fleet-agent-6fb968ddb5-4c74r_fleet-system" network: open /run/flannel/subnet.env: The system cannot find the path specified., failed to stop sandbox container "d69a228fda34d79769498f6dafd96bf9deb0d0e564b17a728e1a437c20478769" for pod "fleet-agent-6fb968ddb5-4c74r": operation timeout: context deadline exceeded]`


### Windows  2004

`v1.19.7-rancher2-1`
Active in Fleet but Example Bundle won't deploy. See below.


## Installing a Bundle in an Active cluster

Using the helm windows app above I get the following error from the GitRepo, I tried Windows 2004 and Windows 1903


`unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template): unknown field "nodeSelector" in io.k8s.api.core.v1.PodTemplateSpec, ValidationError(Deployment.spec.template): unknown field "tolerations" in io.k8s.api.core.v1.PodTemplateSpec]`

**Comment by nickgerace** [comment]
Hmmm, the bundle PR was missing a change from the dev branch. Fixing.
As far as the other issues go, I am going to work from 2004 and move backwards.

**Comment by izaac** [comment]
Rancher version `v2.5.6-rc5`

VXLAN

Windows 1809
v1.18.16-rancher1-1
https://github.com/rancher/rancher/issues/31405

Windows 1903
v1.18.16-rancher1-1

Windows 1909
v1.20.4-rancher1-1

Windows 2004
v1.20.4-rancher1-1

HOSTGW 

There's a known issue that prevents the cluster agent to deploy and charts like fleet to fail too.
https://github.com/rancher/rancher/issues/31316

**Comment by izaac** [comment]
Rancher version `v2.5.5` upgrade to `v2.5.6-rc5`
Downstream clusters Windows versions: `1903` and `2019 ltsc`

### Pre upgrade on `v2.5.5`

- Make sure the fleet agent is active by:

Cordon all Windows Workers except the Linux Worker.

Add the following toleration to the fleet-agent workload and redeploy.
```yaml
tolerations:
- effect: NoSchedule
  key: cattle.io/os
  operator: Equal
  value: linux
```

### Once the fleet agent is active upgrade to `v2.5.6-rc5`

On 2.5.6 Add the fleet-examples repo to use and point it to the windows multi-cluster helm path. Make sure to label the Windows OS version properly
`kubectl get nodes --show-labels`  and look for the `windows-release-id=`

- Windows 2019 = `windows.version: win1809`
- Windows 1903 = `windows.version: win1903`

```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-local
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster/windows-helm
```
Deploy to all clusters.

Check the workloads came up active in the namespace `fleet-helm-windows-example`

**Comment by izaac** [comment]
Covered these windows versions with the following k8s versions from the support matrix:

```
Windows Server 2019 LTSC -  v1.19 (from 2.5.5 Upgrade)
Windows Server 2019 LTSC -  v1.20 (Fresh Install)
Windows 1809 - v1.18 (Fresh Install)
Windows 1903 - v1.18 (Fresh install and Upgrade)
Windows 1909 - v1.20 (Fresh Install)
Windows 2004 - v1.20 (Fresh Install
```
