### ISSUE TITLE
Priviledge escalation for ServiceAccount and RoleBinding in kubernetes v1.19.4 / rancher v2.5.3

### ISSUE THREAD

**Issue by matsonkepson** [rancher/rancher#30548]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
While creating ServiceAccount and assigning privileges with RoleBinding only to one namespace I can list/access/modify all resources / all namespaces
gist here > https://gist.github.com/matsonkepson/ea64d35c9260d81d93994ab197d5d3d4

**Result:**

Works fine with microk8s v1.18.13
NOT working for Kubernetes v1.19.4 (rancher 2.5.3 edition)
gist here > https://gist.github.com/matsonkepson/6d4a076ec5a97beb50f9e724fa332ff3

**Other details that may be helpful:**

copy of https://github.com/kubernetes/kubernetes/issues/97369

**Comment by vincent99** [comment]
in the future if you think you have a security issue please email security@rancher.com instead of paying it to the public internet.

But RBAC is not enabled by default in microk8s, so you can do anything and managing roles/bindings/service accounts has no real effect.

**Comment by matsonkepson** [comment]
@vincent99 
yes i know its not enabled, and i have enabled in on purpose to do a crosscheck and it succeed. 
If you don't want to pursue it fine... 
p.s. are you also answer this to your paid customers ?

**Comment by vincent99** [comment]
- Yes, if a customer posts security issues publicly I absolutely tell them to stop it, and they appreciate possible vulnerabilities not being broadcast to the world before they can be fixed.  If I thought there was really an issue here I would have deleted the content of the issue to limit the disclosure.
- Your gist is clearly geared for microk8s, you didn't say anything about enabling rbac, and that's the obvious explanation for anything with roles working when not expected.
- Your use of terms like "working" and "not working" to mean "doing what you expect, which is failing in some cases" is not helping make things clear.  I read the whole thing backwards and thought you were saying you CAN do things you shouldn't be able to in microk8s (which again, has no RBAC by default so this is expected) and can't in RKE (which would be expected).
- Your 2nd gist shows the output of a script that isn't what's in the gist, with both the user and role already existing.  So this is clearly not a clean run of your test; we have no idea what other bindings that service account might have, or what's in `~/work/testing-sa-admin-per-namespace.sh`.
- On a clean 1.19.4 cluster, provisioned by RKE with Rancher 2.5.3, your gist produces exactly what you (correctly) expect for things that should and should not be allowed: https://gist.github.com/vincent99/afe5baa30244f4c12b301dadbefd944b (I ran it a line at a time instead of as a script, and changed only `KUBE_MASTER` and `rancht` as appropriate)
- RBAC is enforced by native k8s code that we don't do anything to change.
- So I still see no evidence that k8s is doing anything wrong here, or that Rancher has added extra roles/bindings to cause it to appear to.

**Comment by matsonkepson** [comment]
Okay I am guilty of lazynes and you are right, my ticket is messy and bit of misleading.  But forgive me because this is my first posting to community . Let me rephrase it bit more clear. 

I am trying to create a ServiceAccount in kubernetes which has admin access to all inside ONLY ONE namespace. 
I was following this > https://dvops.cloud/2019/07/30/kubernetes-rbac-restrict-user-access-to-one-namespace/
this >https://jeremievallee.com/2018/05/28/kubernetes-rbac-namespace-user.html
this > https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole
and this > https://gist.github.com/steimntz/abb9d705d495c95029a47b5388674be5

as its written in kubernetes documentation " A RoleBinding grants permissions within a specific namespace whereas a ClusterRoleBinding grants that access cluster-wide"  And am using this RoleBinding...

And my problem is that it fails successfully , namely i can do all within namespace and also whole cluster! (kubernetes v. 1.19.4)

I have run same script (like here https://gist.github.com/matsonkepson/ea64d35c9260d81d93994ab197d5d3d4 but with kube_master modification and namespace)  against v1.19.4 and microk8s ( with rbac enabled) and i got different results!
Namely 
**microk8s with kubernetes v1.18.13 was correct** (here https://gist.github.com/matsonkepson/68f874db443b60c485304b103e594337) i could not see anywhere outside namespace

**rancher v2.5.3 with kubernetes v1.19.4 was also working but gave me to much privileges** ( results here https://gist.github.com/matsonkepson/6d4a076ec5a97beb50f9e724fa332ff3) and i was seeing things which i should not like kluster nodes, another namespaces with write permissions on top of it

And this is all about , it gave me to much privileges. 

Because i am not fluent with Open Source Community standards and i don't know who should i write to but this is real deal and should not be omitted (in my opinion).

Do you want me to provision other Rancher2 versions or same rancher2 cluster but another kubernetes versions?
or should i just stop right now

**Comment by matsonkepson** [comment]
> On a clean 1.19.4 cluster, provisioned by RKE with Rancher 2.5.3, your gist produces exactly what you (correctly) expect for things that should and should not be allowed: https://gist.github.com/vincent99/afe5baa30244f4c12b301dadbefd944b (I ran it a line at a time instead of as a script, and changed only KUBE_MASTER and rancht as appropriate)

I will try to run my stuff with a new RKE 2.5.3 (kube 1.19.4) and get back to give my results.

**Comment by matsonkepson** [comment]
there was clusterrolebinding  which i have overlooked, bounding all serviceaccounts to the cluster-admin role.

I was sure that this was an empty(never used) cluster.

Sorry for that
