### ISSUE TITLE
Rancher 2.5.3 doesnt show node group options in old (rancher 2.4.8) createtd EKS clusters

### ISSUE THREAD

**Issue by flostru** [rancher/rancher#30564]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. Create a EKS Cluster in Rancher 2.4.x
2. Upgrade to Rancher 2.5.3
3. create cloud credentials
4. edit EKS Cluster

**Result:**
No Cloud Credentials for "old" cluster available to choose
No Node Group Settings available

**Other details that may be helpful:**

Until now we have manually upgraded the nodes for EKS Cluster.
Node Groups give a much more convenient way of rolling out updates on EKS Worker nodes.

**Environment information**
- Rancher version: 2.5.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): c5.xlarge 
- Kubernetes version (use `kubectl version`): Master: v1.18.9, Workers: v1.17.9

We would like to switch to Node Groups for easyer upgrading of Worker Nodes.
Since the Options for Nodegroups are not available for old (pre 2.5) rancher created EKS Clusters my question is if there is a workaround for that?
Maybe manually creating the Node Groups in AWS Console or Terraform and then tagging/editing the cluster so the new settings would be reflected and available in Rancher.

Has someone successfully managed to get that done?

**Comment by Roberdvs** [comment]
I would also like to know if there's a way to upgrade a pre-2.5 Rancher created EKS cluster to the V2 config format to take advantage of the new features.

I though about removing the cluster from Rancher and then register it back ([since according to the docs there's no difference now for EKS clusters](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/imported-clusters/#changes-in-rancher-v2-5)) but apparently there's [no way of dettaching the cluster from Rancher](https://rancher.com/docs/rancher/v2.x/en/faq/removing-rancher/#what-if-i-don-t-want-my-rke-cluster-or-hosted-kubernetes-cluster-managed-by-rancher) apart from deleting it (which also deletes the cluster).

**Comment by hoppla20** [comment]
I can confirm that importing the cluster again works because I tested it. We had a EKS cluster that we created with pre-2.5 Rancher. After updating to 2.5.3 I imported the cluster again and now I can take advantages of the new features. But after the first minutes of joy I realized that I can't detach either one of the clusters (I now have two clusters in Rancher that point to the same EKS cluster). The workloads are only shown in one cluster but I can move Namespaces between the two Rancher clusters (same EKS cluster). My Problem now is that I don't want to delete either one of them because I'm scared that it will delete the EKS cluster. I will setup a pre-2.5 rancher and will try to replicate this and try to delete either one of them. I will give an update afterwards.

I know that in the [documentation](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/imported-clusters/#changes-in-rancher-v2-5) it says the following:
_When you delete an EKS cluster that was created in Rancher, the cluster is destroyed. When you delete an EKS cluster that was registered in Rancher, it is disconnected from the Rancher server, but it still exists and you can still access it in the same way you did before it was registered in Rancher._

But it's our production cluster and I'm not sure whether I should trust that at the moment because I don't think that our current situation with the cluster is normal.

But I'm a little disappointed that there is no documentation of how to upgrade the cluster to post-2.5. It didn't even mention it once in the documentation. So yeah, I would also really appreciate it if there are any updates on this issue.

**Comment by hoppla20** [comment]
I've done the following:
* Create a rancher instance with version 2.4.12
* Create a eks cluster with name "test"
* Upgrade rancher to 2.5.3
* Rename the cluster in rancher to "test-old"
* Import the eks cluster again
  * Now I have two clusters in rancher: "test" and "test-old"
* Then I deleted "test-old" (the cluster I created with the old version)
I have now waited for about an hour and the cluster is still there (in rancher and in the amazon console). I still haven't tried it on our production cluster but this seems promising. If we try it on our production cluster I will give you an update how it went

**Comment by hoppla20** [comment]
I'm just a bit confused because I deleted a eks cluster that I created in Rancher. But it didn't delete the eks cluster (maybe because I had another cluster in rancher referencing the eks cluster?)

**Comment by flostru** [comment]
Same thing here, we have done the same procedure in our lab environment.
renaming old one, importing duplicate and deleting old one.
Cluster still alive, project association of namespaces was gone thou. But moving stuff into correct projects worked fine.
Kubectl configs need to be updated.

still i dont dare to do it in prod environment

**Comment by stremlau** [comment]
We are in the exact same situation. We imported a pre 2.5 eks cluster and now we have both of them in Rancher.

We also did some testing: Deleting the "old" cluster does not delete the eks cluster when it was imported beforehand. The question is: Is this a feature or a bug? When it is a bug it could be fixed in future rancher released and our production cluster would siently disappear.

**Comment by stremlau** [comment]
colud be related to https://github.com/rancher/rancher/issues/30817

**Comment by flostru** [comment]
Any news on this?
We really need to import/migrate existing eks clusters to v2.

Looks like all will be fine by importing as new cluster and later removing the old one, but i must be really sure that this is intended .
Alternatively it would be really usefull to have the abillity to just "deregister" a eks cluster without removing it from aws.

**Comment by stremlau** [comment]
No news from our side :-(

**Comment by mshivanna** [comment]
hit with the same issue. Our eks clusters we created prior to 2.5 and now the node section is uneditable and there is no option of nodegroup.  :( Cannot scale the clusters now.

**Comment by mshivanna** [comment]
@sowmyav27  any workaround on how we can go about this? thank you
