### ISSUE TITLE
rancher-machine should have a no-op provisioner that doesn't install Docker

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30597]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Steps to reproduce (least amount of steps as possible):**
Create a new machine with `rancher-machine` using any driver

**Result:**
Docker is installed and certificates uploaded to the machine.

**Other details that may be helpful:**
A flag should be added to the `create` command that allows the user to specify a URL for a custom install script. When this flag is given, then docker will not be install and the related certificates/config is not generated or saved.

**Comment by cbron** [comment]
This can actually go into test right ? Just nothing realistic for QA team to test yet.

**Comment by thedadams** [comment]
Yes, this is ready to move but there isn't anything to test directly until provisioning is finished.

**Comment by thehejik** [comment]
**Test report:**
Tested on `rancher/rancher:master-head e546ffe`

The binary `rancher-machine` is used for both RKE1 and RKE2 provisioning and it is widely used and tested within cluster provisioning.

* For **RKE1 provisioning** the `rancher-machine` bin is executed directly in `rancher` pod and following arguments are used for RKE1 EC2 nodes provisioning:
```shell 
> kubectl exec -it rancher-74877fc5c6-dnbcc -n cattle-system -- sh
sh-4.4# ps auxf | grep machine-rancher
root       720  0.2  0.5 773136 43428 ?        Sl   09:55   0:00  \_ rancher-machine create -d amazonec2 --engine-install-url https://releases.rancher.com/install-docker/20.10.sh --amazonec2-volume-type gp2 --amazonec2-block-duration-minutes 0 --amazonec2-spot-price 0.50 --amazonec2-zone a --amazonec2-vpc-id vpc-REDACTED --amazonec2-http-tokens optional --amazonec2-root-size 16 --amazonec2-tags kubernetes.io/cluster/c-d5vt8,owned --amazonec2-access-key REDACTED --amazonec2-ami ami-0dbcb516c6c091feb --amazonec2-instance-type t2.medium --amazonec2-security-group open-all --amazonec2-ssh-user ubuntu --amazonec2-region us-east-2 --amazonec2-retries 5 --amazonec2-http-endpoint enabled --amazonec2-secret-key REDACTED thehejik-allroles1
```
Result: There is no trace of `--custom-install-script` flag for `create` action of `rancher-machine` for RKE1 provisioning and docker is installed by passing `--engine-install-url https://releases.rancher.com/install-docker/20.10.sh`. The node was based on `minimal-ubuntu-18-2021.04.08` `ami-0dbcb516c6c091feb` which is shipped without docker preinstalled - the cluster was provisioned successfully so the docker installation script was used.

* For **RKE2 provisioning** the `machine-rancher` binary is called not from `rancher` pod but from extra container living in `fleet-default` namespace in Pod `<cluster-name>-<pool-name>-machine-provisioning*` which is using image `rancher/machine:v0.15.0-rancher60` and has following args (taken from `kubectl describe pod thehejik-rke2-do-thehejik-allroles-9d4jl-machine-provision7mzhd -n fleet-default`):
```yaml
    Args:
      --driver-download-url=
      --driver-hash=
      --secret-namespace=fleet-default
      --secret-name=thehejik-rke2-do-thehejik-allroles-9d4jl-machine-state
      create
      --driver=digitalocean
      --custom-install-script=/run/secrets/machine/value
      --digitalocean-image=ubuntu-18-04-x64
      --digitalocean-region=sfo3
      --digitalocean-size=s-2vcpu-4gb
      --digitalocean-ssh-port=22
      --digitalocean-ssh-user=root
      thehejik-rke2-do-thehejik-allroles-9d4jl
```
Result: I was using RKE2 DO driver because EC2 driver is currently broken. The cluster has been provisioned successfully and you can see in output above that `--custom-install-script=/run/secrets/machine/value` flag was used in this case. The DO node was based on `ubuntu 18.04` DO image - I also verified that docker is not installed on the node.

Works as expected. Closing
