### ISSUE TITLE
Exoscale machine/host not creating

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3060]
Version 0.50.1

Steps;
1.  Add host
2.  Try to add an exoscale host

Results:  Host doesn't setup.  Instance on exoscale side is not created either.
![image](https://cloud.githubusercontent.com/assets/11514927/11879253/7e70947a-a4b7-11e5-8e55-7839a7a5d023.png)

Expected:
Exoscale should setup

**Comment by tfiduccia** [comment]
Retested this and I still can't get exoscale hosts to setup.  Error = Unsupported type: []interface {}

**Comment by vincentbernat** [comment]
Hello,

I can reproduce that. I am looking at the issue.

**Comment by vincentbernat** [comment]
So, after a bit of investigation, the problem is with security groups. @wlan0 did add support for string slices in rancher/go-machine-service#69 but it seems that it was broken later by @hibooboo2 in rancher/go-machine-service#74. Now, instead of being `[]string`, `securityGroup` is `[]interface{}`.

I have a hard time finding where this could be fixed. Any hint would be appreciated.

**Comment by wlan0** [comment]
@vincentbernat I've added a fix for this issue here - https://github.com/rancher/go-machine-service/issues/95 

Thanks for your investigation, it helped a lot!

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc3
Verified fixed - Exoscale setup

**Comment by vincentbernat** [comment]
Thanks! @tfiduccia If you can mention me in the future issues related with exoscale, I would be happy to investigate them (and hopefully I will be able to fix something myself one day ;-) )
