### ISSUE TITLE
forwardport: Removing in-tree vSphere vCenter server entries does not propagate

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#30606]
forwardport: https://github.com/rancher/rancher/issues/27306

**Comment by rawmind0** [comment]
Submitted PR #30694  to fix the issue

**Comment by sadiapoddar** [comment]
Verified the fix on 2.5-head, commit id, 23a29c30

1. Created a cluster on vSphere cloud provider by choosing the "custom" provider option and added the clouder provider information in YMAL file

2. Once the cluster is up checked all the config info and verified info. 
root@sadia-control1:# docker inspect kube-apiserver |grep cloud

3. Edited the cluster configuration and added a second non-existing vCenter information in the cluster config and saved it
<img width="843" alt="102672878-f17dc600-4146-11eb-9f71-61acb5f28a66" src="https://user-images.githubusercontent.com/72409237/105412308-69795900-5be9-11eb-8efc-e79b56e75e47.png">

4. Noticed a health error during updating the cluster with the newly added Center. 

5. Re-edited the cluster config to remove the newly added vCenter info 
6. Checked after saving it 
The cloud configuration doesn't have the second vCenter information in the config
<img width="669" alt="Screen Shot 2021-01-21 at 1 04 47 PM" src="https://user-images.githubusercontent.com/72409237/105412371-7d24bf80-5be9-11eb-8667-89190ce6a74f.png">

7. Cluster became healthy. 
<img width="1349" alt="Screen Shot 2021-01-21 at 1 01 54 PM" src="https://user-images.githubusercontent.com/72409237/105412005-fff94a80-5be8-11eb-8ae0-35bfdb39b85f.png">

Closing the bug as vCenter's in-tree server entries are propagating as expected

**Comment by sowmyav27** [comment]
Reopening this for a PR for master-head

**Comment by sadiapoddar** [comment]
The fix is not merged in the master branch.

**Comment by rawmind0** [comment]
Submitted PR to master, https://github.com/rancher/rancher/pull/30948

**Comment by sadiapoddar** [comment]
Verified the fix on master-head, 41045a8

- Created a cluster on vSphere cloud provider by choosing the "custom" provider option and added the clouder provider information in YMAL file

- Once the cluster is up checked all the config info and verified info.

- Edited the cluster configuration and added a second non-existing vCenter information in the cluster config and saved it
- Noticed a health error during updating the cluster with the newly added Center.

- Re-edited the cluster config to remove the newly added vCenter info
- Checked after saving it that the cloud configuration doesn't have the second vCenter information in the config
- Cluster became healthy.

The fix is working on the master branch.
