### ISSUE TITLE
forwardport: registry for workload cluster - let RancherUI freeze

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#30602]
forward port:  https://github.com/rancher/rancher/issues/25147

**Comment by deniseschannon** [comment]
Based on the original issue which was conflating 2 issues, this use case should have been fixed already and just needs to be validated: 

The original issue for which this GitHub issue was filed, related to a UI bug noted in Rancher v2.3.4, when attempting to view the System project registry credentials in the Rancher UI for a cluster with a private registry configured in the cluster settings. This was originally reported when enabling a private registry configuration for a cluster without one initially configured, and I also reproduced this scenario #25147 (comment) In further testing I was also able to reproduce this in v2.3.4 when configuring a Private Registry on a cluster at initial provisioning.

Tests in Rancher v2.4.0, v2.4.8 and v2.5.3 show that this bug is no longer present in Rancher v2.4+, and I think this GitHub issue can be closed.

For the record an error observed in the browser Javascript console when the issue occurred in v2.3.4 was as below:

Uncaught (in promise) Error: <ui@helper:t::ember355> helper requires value attribute.
    at n.compute (-format-base.js:42)
    at t.compute (glimmer.js:791)
    at t.value (glimmer.js:384)
    at e.value (runtime.js:552)
    at e.t.initialize (reference.js:454)
    at e.t.peek (reference.js:429)
    at Function.n.initialize (runtime.js:901)
    at Object.evaluate (runtime.js:873)
    at e.t.evaluate (runtime.js:72)
    at e.t.evaluateSyscall (runtime.js:3471)

**Comment by aaronRancher** [comment]
This bug is not reproduced on `Rancher v2.5-head` `version 2b061d7`

Steps:
Provision a single node custom cluster via Rancher v2.3.4
Edit the custom cluster to add a private registry URL: registry.example.com, username: username, password: password
Observe the System project -> secrets -> registry credentials view freezes
Observe following contents of the secret:
```
kubectl -n cattle-system get secret cattle-private-registry -o jsonpath="{.data.\.dockerconfigjson}" | base64 -d
{"username":"username","password":"password"}
```

Result:
System Secrets and Registry Credentials page is accessible.
![Screen Shot 2021-01-08 at 3 09 07 PM](https://user-images.githubusercontent.com/57409052/104070204-9417ea80-51c3-11eb-8af4-7d4d41b155cf.png)
