### ISSUE TITLE
Make etcd snapshot job timeout tunable

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#30663]
**What kind of request is this:**
Feature

**Description**
Followup item from issue https://github.com/rancher/rancher/issues/30662

Make backup job timeout tunable to handle slow backup destination. 
As of now, the value is hardcoded as 5 minutes.
https://github.com/rancher/rke/blob/v1.1.6/docker/docker.go#L495

Slow backup destination or bigger etcd snapshot causing rescheduling of snapshot causing unwanted repeating etcd snapshot, compression, and backup transfer to S3. These unsuccessful operations have etcd/CPU/Disk/Network cost.

gz#13924

**Comment by rawmind0** [comment]
Submitted PRs to add this feature to: 
* rke v1.1 ( https://github.com/rancher/types/pull/1196 and https://github.com/rancher/rke/pull/2418) 
* rke v1.2 (https://github.com/rancher/rke/pull/2419) 
* rancher v2.4 (https://github.com/rancher/rancher/pull/30885) 
* rancher v2.5 (https://github.com/rancher/rancher/pull/30886)

**Comment by rawmind0** [comment]
Feature PR's has been merged, adding it to:
- types
- rke v1.1, v1.2 and master
- rancher v2.5 and master. rancher v2.4 support has been set as out of the scope so PR not merged, just closed

**Comment by sowmyav27** [comment]
@rawmind0 [This](https://github.com/rancher/types/pull/1196) PR which is merged for 2.4 has to be reverted? As said in [here](https://github.com/rancher/rancher/issues/30663#issuecomment-768460771) that this issue is out of scope for 2.4 ?

**Comment by rawmind0** [comment]
@sowmyav27 , the PR can't be reverted as it's used by rke v1.1.4, https://github.com/rancher/types/pull/1196

**Comment by sadiapoddar** [comment]
Verified the fix on 
   2.5-head, commit v2.5-5f3fcb84 and master-head, b4b232
 
Steps
1. Created  4 cluster with 1 etcd, 1, cnt and 3 worker nodes
3. Created a few projects, lots of workload, installed monitoring, cis, logging and lstio charts
4. Took a few snapshots on each cluster
5. Introduced network delay 100 ms on the etcd host 
6. Issue restore on the cluster from the snapshot taken before, restore was successful
7. Edited the etcd time out which is default 300 sec to 1 sec
8. Issue restore on the clusters from the snaphsot take nbefore, all the snapshot failed due to timeout 1 sec
<img width="1325" alt="Screen Shot 2021-02-04 at 7 29 49 PM" src="https://user-images.githubusercontent.com/72409237/106986423-2b6b5180-6720-11eb-8bc3-a8434ca942f1.png">

9. Re-edited the etcd time out back to default 300 sec and issue restore and restore was successful


Also verified 1.2.6-rc4 and 1.3.0-rc rke version by
1. Created cluster config with etcd timeout value set to 1 sec
etcd:
    backup_config:
      enabled: true
      interval_hours: 12
      retention: 6
      safe_timestamp: false
      timeout: 1
2. Created a cluster by ./rke up
3. once the cluster is up, issued a backup by taking snapshot, but snapshot didn't finish since timeout was 1 sec

FATA[0012] Container [etcd-snapshot-once] did not exit in time on host [x.x.x.x]: stderr: [time="2021-02-05T02:45:29Z" level=info msg="Created local backup" name=snapshot1 runtime=110.484999ms
], stdout: [] 

The fix was adding a configurable timeout parameter to use in etcd. This timeout value users can configure to take back/restore based on their infrastructure. 
The fix is working as expected.
