### ISSUE TITLE
[Monitoring v2] Show metrics from nodes where etcd runs on the Nodes dashboard in Grafana

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#30680]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

In Monitoring v2, we'd like to see the metrics of etcd nodes in the `Nodes` dashboard in Grafana. 

Currently, the dashboard shows all other nodes except the etcd node. 

<img width="538" alt="Screen Shot 2021-01-05 at 10 06 11 AM" src="https://user-images.githubusercontent.com/6218999/103685383-5e1c0180-4f4a-11eb-9f4b-eecd564480fa.png">

**Comment by aiyengar2** [comment]
@jiaqiluo thanks for catching this! This bug was caused by a No-Execute taint added to etcd-only nodes on Rancher.

While the `prometheus-node-exporter` does have a [default toleration for NoSchedule](https://github.com/helm/charts/blob/7e45e678e39b88590fe877f159516f85f3fd3f38/stable/prometheus-node-exporter/values.yaml#L98-L100), we need to update the Monitoring V2 chart to have an additional toleration for NoExecute by default as well.

### Workaround

If you are encountering this issue, just add the following to the [values.yaml](https://github.com/rancher/charts/blob/e41bb716466a834bb29e24a1c139996b8f4ce182/charts/rancher-monitoring/values.yaml#L1550-L1568) on deploying the chart:

```yaml
prometheus-node-exporter:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
```

**Comment by jiaqiluo** [comment]
The bugfix is validated on Monitoring v2 chart `v9.4.203-rc01` rancher:`master-head` 55384b8

Steps:
- run Rancher in the single-install mode
- provision a downstream cluster with EC2 node-drvier ( 1 control plane, 3 etcd, 3 worker) 
- enable monitoring v2 9.4.203-rc01 on the cluster 
- After the monitoring is installed and active, go to Grafana -> Node dashboard 

Results:
- on the Node dashboard, we can see metrics from etcd nodes
<img width="584" alt="Screen Shot 2021-02-02 at 1 55 52 PM" src="https://user-images.githubusercontent.com/6218999/106661462-76d60200-655e-11eb-955c-4619bd753c39.png">

- the daemonSet `rancher-monitoring-prometheus-node-exporter` has pods running on the etcd nodes
