### ISSUE TITLE
[1.6] Env. vars from service created in the lb-service-haproxy container and it fails to start

### ISSUE THREAD

**Issue by beatcracker** [rancher/rancher#30734]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create Stack and Service
2. Create Loadbalancer
3. Add Service Rule for service in stack.

**Result:**

Environment variables from the linked service are set as environment variables in the `rancher/lb-service-haproxy` container.

Example

```
docker inspect r-load-balancer-lb-http-3-7793dc36
        "Config": {
            "Hostname": "95beee6910de",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SERVICENAME_PORT_443_TCP_PROTO=tcp"
                "STACKNAME_SIDEKICKNAME_SERVICENAME_8_PORT_80_TCP_PROTO=tcp"
                "STACKNAME_SIDEKICKNAME_SERVICENAME_1_PORT_443_TCP_PROTO=tcp"
                "STACKNAME_SERVICENAME_2_PORT_80_TCP_PROTO=tcp"
                "STACKNAME_SERVICENAME_9_PORT_443_TCP_PROTO=tcp"
                "STACKNAME_SIDEKICKNAME_SERVICENAME_4_PORT_443_TCP_PROTO=tcp"
                "STACKNAME_SERVICENAME_3_PORT_80_TCP_PROTO=tcp"
                "STACKNAME_SERVICENAME_8_PORT_80_TCP_PROTO=tcp"
                "STACKNAME_SIDEKICKNAME_SERVICENAME_2_PORT_443_TCP_PROTO=tcp"
                "STACKNAME_SIDEKICKNAME_SERVICENAME_9_PORT_80_TCP_PROTO=tcp"
                "STACKNAME_SIDEKICKNAME_SERVICENAME_8_PORT_443_TCP_PROTO=tcp"
                "STACKNAME_SIDEKICKNAME_SERVICENAME_3_PORT_80_TCP_PROTO=tcp"
                "STACKNAME_SERVICENAME_1_ENV_CUSTOM_VARA=some value a"
                "STACKNAME_SERVICENAME_1_ENV_CUSTOM_VAR_B=some value b"
                "STACKNAME_SERVICENAME_4_ENV_CUSTOM_VAR_C=some value c"
                ...
```

This hast two consequences:

1. Private vars from services are exposed to haproxy loadbalancer container
2. If you have lot of services with lot of vars added to LB, haproxy container wouldn't start because of env. var size limit
    ```
    standard_init_linux.go:190: exec user process caused "argument list too long"
    ```

**Other details that may be helpful:**

I've found code that could generate something like this, but I'm not sure if it's applicable:

* https://github.com/rancher/python-agent/blob/master/cattle/plugins/docker/network.py#L210-L213
* https://github.com/rancher/python-agent/blob/master/cattle/plugins/docker/network.py#L262-L265
* https://github.com/rancher/python-agent/blob/master/cattle/plugins/docker/network.py#L232

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **1.6.25**
- Installation option (single install/HA): **single**
- Docker version (use `docker version`): **18.06.3-ce**

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        d7080c1
 Built:             Tue Feb 19 23:07:53 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d7080c1
  Built:            Tue Feb 19 23:07:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

----

P.S. I'm pretty much aware that 1.6 is EOL, but I would appreciate at least some pointers on how I can fix it. I don't mind patching code and rebuilding Rancher container images if needed.

**Comment by vincent99** [comment]
This is a behavior Docker implements that is just being emulated to work properly within the context or Rancher. So it is effectively working as intended, but has limitations.

 Those are the place it is done (called by `setup_links ()`).  It's unclear what you actually want to happen here, any change you make is going to be breaking the expected behavior of linking.

If this were years ago and we were addressing this, it would have probably been by adding an option to opt-out of the variable injection, and applying that option to the balancer services we create...

Looking at the image name and hardcoding that special case in would be a much simpler alternative/hack.

As you've noted we no longer support or maintain 1.x, so talking about the security of environment variables being copied is really the least of your problems. Nobody should be running this anymore.  Running unmaintained software that controls root on all your nodes is playing with fire.

The entire stack is based on tiers of things from the JVM to the base OS images and everything in between that are not supported by anybody anymore, and not easily updatable.  I don't know what they are, but there are surely serious and possibly remotely-exploitable vulnerabilities to be found.

**Comment by beatcracker** [comment]
@vincent99 Thank you for the detailed response. I generally agree and this stuff is scheduled for migration, but for some time I'm stuck with it. This means that I need a short-tem fix for a case when load-balancer fails to start.

Would you mind pointing how `python-agent` is integrated with the rest of the stack so I can update it? I've found the links below, but looking at the `rancher/agent:v1.2.11` image I can't see where the actual python code is used. And I can't find anything related to the env. var setup in go agent code.

* https://forums.rancher.com/t/requesting-access-to-rancher-agent-repository/176/4
  * https://github.com/rancher/rancher/blob/v1.6.30/agent/run.sh#L68-L96%2015
  * https://github.com/rancher/cattle/blob/v1.6/resources/content/cattle-global.properties#L11-L17%205

* https://forums.rancher.com/t/docs-on-how-to-build-a-debug-rancher-rancher-agent/6351/2

**Comment by vincent99** [comment]
With the time that's passed there's just a very limited set of current employees who have ever even touched 1.x.  Most of development moved over 3+ years ago, and there weren't that many people then. There's was a long deprecation period with very limited changes, time has passed, people have moved on to management jobs or forgotten details or retired, the company was bought, etc.

I forgot the part where the agent was rewritten from python to go around v1.2..  for newer versions the equivalent looks like here: https://github.com/rancher/agent/blob/v1.6/core/compute/compute_unix.go#L282-283 .  You are provably looking at the 2.x agent since it uses the same repo but unrelated code.

I have always done the Ui and overall architecture so i don't know the specifics of how the image is built or how you're going to get your version of the agent on the nodes.  But it probably involves `dapper`, and I think there's a /v2-beta/setting for what image to use, but probably nothing built in to cause existing ones to be redeployed when it's changed.

**Comment by beatcracker** [comment]
@vincent99 This is more than enough to get me started. Thank you for spending your time on such minor edge case in deprecated piece of software, I really appreciate it. Please accept my sincere gratitude for your support ❤️.

**Comment by beatcracker** [comment]
TWIMC: I've built a custom agent version with disabled [links](https://rancher.com/docs/rancher/v1.6/en/cattle/adding-services/#linking-services) support to workaround this issue:

* Repo: https://github.com/housewares/agent  
See [dist/README.md](dist/README.md) for details on building and deploying this custom agent version.
* Pre-built agent binaries: [Releases/v0.3.11-no-links](https://github.com/housewares/agent/releases/tag/v0.3.11-no-links)
* Pre-built Rancher server container with updated agent: [housewares/server:v1.6.30-no-links](https://hub.docker.com/r/housewares/server)
