### ISSUE TITLE
Audit Logs- Environment status icon shows "in-progess"  when launching the "Application" page after accessing "audit logs" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3074]
Server version - Build from master

Steps to reproduce the problem:
Create couple of services . 
Make sure the environment show up "Active" in "Applications" page.
Go to  "audit logs" page.
Go to "Application" page.

Notice that the environment status icon shows "in-progess" icon for all the  services.
The problem corrects itself when the page is refreshed.

<img width="1394" alt="screen shot 2015-12-18 at 11 20 14 am" src="https://cloud.githubusercontent.com/assets/4266958/11905282/67bee650-a57a-11e5-9a0b-f648338fefbd.png">

**Comment by sangeethah** [comment]
@westlywright , I see similar issues when testing in a setup that has multiple environments.

After launching "audit logs" , launching "Application" /"Infrastructure" page shows entries from other environment and the status of these entries are shown as being in progress.

![Uploading Screen Shot 2015-12-18 at 3.35.41 PM.png…]()

**Comment by vincent99** [comment]
Ugh, this is bad.. the responseObjects are getting parsed and put into the store and overwriting newer copies of the resource.  The change to serialize the request/responseObject to plain objects is after this has already happened.

**Comment by vincent99** [comment]
Fixing this with the fields as actual objects will require major changes to how API responses are parsed in the UI.  It currently goes depth-first/bottom-up, so it sees the responseObject is say `{type: container, id: 42}` and then updates the copy in the store memory with the "new" info for that container.  In this case though it's a days old copy of that resource and that info shouldn't be used to update the store.  But because the parsing is bottom-up instead of top-down there's no good way to know it's a container that happens to be in an auditLog resource.

So @hibooboo2 I'm going to have to backpedal on the API and make `requestObject`/`responseObject` strings again (sorry).  And @westlywright you can remove the `serialize()` stuff from the model now and use `JSON.stringify(JSON.parse(str),null,2)` to pretty-ify it before passing to the highlighter.

**Comment by will-chan** [comment]
let's fix this before the RC then.

**Comment by sangeethah** [comment]
Tested with latest build from master

Issue mentioned in the bug is not reproducible. No discrepancies seen when loading Application/Infrastructure page after loading "Audit Log" page.
