### ISSUE TITLE
Introduce error state for container

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3080]
Container that fails to deploy, gets destroyed immediately today if its a part of the service. It doesn't give user a chance to figure out the reason for its failure. To fix it, we need to introduce one extra state for the container - Error. Container should stay in this state for 1 hour (configurable) and be assigned to the service while in this state. So the user can see all the containers that failed to deploy, and the reason for the failure. 

@vincent99 in the UI, we should probably group containers in Error state, and don't expand this group by default, only on demand, to avoid flooding service's view with dead containers.

**Comment by alena1108** [comment]
@sangeethah we might need a UI fix as now error instances can clutter the UI as they are not gonna be purged for 1 hour (configurable)

**Comment by sangeethah** [comment]
Tested with v0.63.0-rc1 .

Create a service with scale 4 having port map when there is only 3 hosts in the setup.
Service is stuck in activating state since the 4th instance cannot be created because of not being able to find a suitable host because of port conflict.
Error message are seen in UI at the service level as well as instance level.

<img width="1126" alt="screen shot 2016-03-09 at 2 01 43 pm" src="https://cloud.githubusercontent.com/assets/4266958/13652312/51259d32-e600-11e5-8c46-8467776b1847.png">
<img width="1125" alt="screen shot 2016-03-09 at 2 01 36 pm" src="https://cloud.githubusercontent.com/assets/4266958/13652311/5124efe0-e600-11e5-9e51-be613d8b5721.png">

Container that fails to get created , appears in "Error" state for a while and then it gets removed after ~ 1 minute.
