### ISSUE TITLE
Audit Logs - Filter "Auth Type"/"Account"/"Identity" not working.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3086]
Server version - Build from master

Steps to reproduce the problem:
Go to Admin->Audit logs.

I see entries for "Auth Type"/"Account"/"Identity".

 click on "show filter" option.
Type in value in "Auth Type"/"Account"/"Identity" field that has a matched entry.

No entries show up in the audit list.

**Comment by westlywright** [comment]
@sangeethah after talking with @vincent99 we're going to remove Account and Identity filters. These two filters we have to remap to make the data useful to display so the filter input would look drastically different then the display. Since your can sort them we feel that removing the ability to filter by those fields is acceptable. I will be changing the Auth Type filter to a dropdown.

**Comment by sangeethah** [comment]
Tested with latest build from master:
Account and Identity filters are not present any more.
"Auth Type" filter drop down works as expected.
