### ISSUE TITLE
Apps disappear from ClusterManager when cluster is reimported

### ISSUE THREAD

**Issue by mogoman** [rancher/rancher#30877]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a new vanilla cluster (in my case k3s v1.19.5+k3s2)
2. Import the new cluster (in ClusterManager Add cluster -> Other cluster)
3. In the default project on the new cluster launch any catalog app, example Redis (Apps -> Launch)
4. Delete the cluster from Rancher
5. Import the cluster again (repeat step 2)
6. Add the namespace (redis) back to the default project

**Result:**

Click on the apps tab in clustermanager and the deployed app is no longer visible. The app is still visible on the "installed apps" section in the new cluster explorer and can still be viewed using the helm CLI - it can even be deleted via helm or cluster explorer.

**Environment information**
- Rancher 2.5.5, k3s v1.19.5+k3s2
- Installed via Docker as a single node
- Docker version 19.03.11

**Additional Info**

Docker writes error logs:

2021/01/18 15:16:01 [ERROR] error getting app redis apps.project.cattle.io "p-zq6m8/redis" not found
2021/01/18 15:16:20 [ERROR] error getting app redis apps.project.cattle.io "p-zq6m8/redis" not found

**Comment by vincent99** [comment]
Apps in Manager are a Rancher type stored in the management ("local") cluster.  They get deleted when you delete that cluster and are gone now.

These exist because Helm 2 with Tiller lacked adequate controls to limit who can do what in a multi-tenant system.  It ultimately still calls Helm to do the actual install though, which stores its own state inside the target cluster.

Then Helm 3 was released, which stores it in a different, incompatible places.  In Manager we added support for 3 but otherwise left the apps type in place.

But Helm 3 also addressed their multi-tenant problems, so the newer "Apps & Marketplace" in Explorer just uses Helm 3 and its state in the cluster directly. Our own "Apps" type is not needed in between anymore.  This also means if you install something with Helm 3 in the old Apps or the CLI, it becomes also visible in the new one.

**Comment by mogoman** [comment]
Thanks for that - makes things a lot clearer. So would the way forward then be to use Helm 3 and the Explorer "Apps & Marketplace?"

**Comment by vincent99** [comment]
Yes; the older apps will eventually be deprecated.

**Comment by mogoman** [comment]
Tried the Explorer way:

1. added a private repository using Explorer
2. deployed a new chart
3. Removed cluster
4. Added cluster back

In Explorer the repository as well as the deployed charts survive cluster delete / add. In the charts view it complained about 2 configmaps missing:

```
configmaps "rancher-partner-charts-dlj9f" not found
configmaps "rancher-charts-5bngr" not found
```

However using the Explorer charts definitely appears to be more robust. I'll deploy all new charts this way.

One other point about the UI; we are using private repositories - I was able to add ours using the format `https://user:pass@url` ; cluster manager style support for private repositories would be good (fields for credential input)
