### ISSUE TITLE
Validate v1 and v2 charts for Oracle linux 8.2

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#30899]
Validate v1 and v2 charts for Oracle linux 8.2

**Comment by slickwarren** [comment]
currently blocked by #30935

**Comment by slickwarren** [comment]
no longer blocked by above.  on current 2.5-head (23a29c3), I was unable to test the following due to previously filed bugs:
* CIS Benchmark: https://github.com/rancher/dashboard/issues/2235
* Fleet: #30978

**Comment by slickwarren** [comment]
The following tests were completed:
**Downstream cluster tests**
* [p0 v1 charts](https://confluence.suse.com/display/EN/P0+Workflows+for+v1+charts)
  * SELinux = permissive
  * SELinux = enabled 
* [p0 v2 charts](https://confluence.suse.com/display/EN/P0+workflows+for+v2+charts)
  * SELinux = permissive
  * SELinux = enabled
  * errors found were already filed as issues on 2.5-head (see comment above)

**Oracle Linux 8.2 as OS that rancher is installed on:**
* deployed HA cluster to test backups
* tested general deployments (provider and custom clusters). ran into [this issue](https://github.com/rancher/rancher/issues/28768) but otherwise was able to operate normally

waiting on status of above 2 tickets to be resolved, then will retest CIS and Fleet with this OS

**Comment by slickwarren** [comment]
CIS Benchmark is now passing on on 2.5-head (3e96d7f)
However;
 I am getting a failure for fleet agent `time="2021-02-16T16:33:37Z" level=error msg="error syncing 'cluster-fleet-default-c-4d7qf-83b6a2c3f753/fleet-agent': handler bundle-deploy: cannot patch \"fleet-agent\" with kind Deployment: Deployment.apps \"fleet-agent\" is invalid: spec.template.spec.containers[0].env[3].name: Required value, requeuing"` 
<img width="785" alt="Screen Shot 2021-02-16 at 8 38 55 AM" src="https://user-images.githubusercontent.com/16691014/108094108-506e9700-7033-11eb-87b6-bc159fb56463.png">

**Comment by slickwarren** [comment]
the issue above was unrelated. Confirmed tests for fleet v2 are working as expected on 2.5-head (05fbcbb)
