### ISSUE TITLE
[Logging v2] Add logging upstream 3.9.0 chart

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#30917]
Releases: https://github.com/banzaicloud/logging-operator/releases

**Comment by izaac** [comment]
Rancher version `v2.5-head (02/01/2021)` _b152ce8_
Rancher version `master-head (02/01/2021)` __
Logging Chart `3.9.000-rc02`

P1 test cases for Flows/Outputs - Cluster{Flow,Output}

- AKS
- k3s
- RKE
- GKE

RKE PSP validation was done in a separate issue: https://github.com/rancher/rancher/issues/30771

EKS testing is blocked due to https://github.com/rancher/rancher/issues/31087

**Comment by izaac** [comment]
Rancher version: `v2.5-head (02/02/2021)` _4f20a4529_
Rancher version: `master-head (02/02/2021)` _55384b86a_
Logging Chart: `3.9.000-rc02`

P1 test cases for Flows/Outputs - Cluster{Flow,Output}

- EKS k8s 1.18
