### ISSUE TITLE
Rancher Cluster Explorer - YAMLException: expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by DiaaEddin** [rancher/rancher#30954]
**Bug**

**try to create any resource using yaml file with multi documents separated by ---**

**YAMLException: expected a single document in the stream, but found more**

**It was working in the previous version**

**Environment information**
- Rancher version 2.5.5
- Installation option : single

**Comment by vincent99** [comment]
The current buttons are for creating a single particular resource; This allows us to show the example and all the fields as comments, but you can only put in a single instance of that resource because it's sent to that particular API endpoint to create (not actually as YAML at all).

A future release will have an arbitrary import that's basically the equivalent of `kubectl apply` and will take multiple documents.  https://github.com/rancher/dashboard/issues/1745
