### ISSUE TITLE
Rancher UI typing exit in terminal does not close window

### ISSUE THREAD

**Issue by oxr463** [rancher/rancher#30960]
**What kind of request is this (question/bug/enhancement/feature request):** Feature Request

**Steps to reproduce (least amount of steps as possible):**

1. Open a shell from the Rancher UI in the browser.
2. Type 'exit' and press enter.

**Result:**

![Screenshot_2021-01-22 Rancher](https://user-images.githubusercontent.com/43783393/105552742-5db59180-5cd2-11eb-9137-b8c883244f81.png)

**Other details that may be helpful:** N/A

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v2.5.5
- Installation option (single install/HA): N/A

gz#14174

**Comment by vincent99** [comment]
This is intentional (and why the connection state is shown at the top).  The screen stays up even after the websocket is closed because you may be trying to figure out what's going on when a container dies, or is deleted, or similar.  This is very difficult if the modal just closes as soon as the connection drops.

The UI doesn't (and can't, really) know that you typed "exit" or ^D and thus triggered a "good" reason for the socket to be closed vs a "bad" one.
