### ISSUE TITLE
[Forwardport] Istio sidecar injection - workload deployment failed with error in sidecar injector

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30964]
Forwardport fix for https://github.com/rancher/rancher/issues/30921

**Comment by anupama2501** [comment]
Verified on 2.5-head[v2.5-2ae4cf117ac988ce409ca0617d246008f74c7aaa-head]

Rancher | v2.5-2ae4cf117ac988ce409ca0617d246008f74c7aaa-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher50

Followed same steps as of https://github.com/rancher/rancher/issues/30921
The fix is working as expected
<img width="652" alt="Screen Shot 2021-01-29 at 11 39 47 AM" src="https://user-images.githubusercontent.com/38144301/106336240-572f9880-6243-11eb-94b7-8ee159b253bf.png">
.
<img width="1351" alt="Screen Shot 2021-01-29 at 11 39 19 AM" src="https://user-images.githubusercontent.com/38144301/106336311-7c240b80-6243-11eb-9023-8031e1a301ed.png">
