### ISSUE TITLE
[UI] show agent env vars on cluster page 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31023]
Fix for https://github.com/rancher/rancher/issues/25412 and https://github.com/rancher/rancher/issues/24876 to add a new field `AgentEnvVar` on cluster object to keep track of env vars passed to the agent. It is of type `[]v1.EnvVar` which includes both EnvVar and EnvVarSource. 

UI needs to add this option for clusters create and update. 

Note: Currently when I create an Imported cluster and add agentEnvVar, API shows it correctly but UI doesn't load. Note: this is only for imported clusters, works fine for RKE clusters.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/31024

**Comment by kinarashah** [comment]
Backend changes are available in `v2.5-head`

**Comment by codyrancher** [comment]
We didn't add agentEnvVars as a part of RKE Templates because nested objects don't behave well with the current question framework. If we want this to be a part of templates let's open another issue and track it separately as it will be a fairly large change.

**Comment by slickwarren** [comment]
<img width="1350" alt="Screen Shot 2021-02-23 at 3 35 58 PM" src="https://user-images.githubusercontent.com/16691014/108926410-39abdf80-75f3-11eb-9e70-1ca659dc59a9.png">
Import cluster page does not have an option for environment variables

**Comment by slickwarren** [comment]
also, there are 2 places to add environment variables. One when adding the node template
<img width="1377" alt="Screen Shot 2021-02-23 at 4 36 37 PM" src="https://user-images.githubusercontent.com/16691014/108927623-7d074d80-75f5-11eb-9d2b-f11119aef709.png">
and the other is on the node provision page (this is the same one that is on the custom cluster page)
<img width="1346" alt="Screen Shot 2021-02-23 at 4 37 33 PM" src="https://user-images.githubusercontent.com/16691014/108927645-8c869680-75f5-11eb-9cde-842c36d03e25.png">
was this intended? 

Adding a variable to either location appears to work

**Comment by slickwarren** [comment]
**Config Map on Edit Cluster is Broken**
config map appears when editing a cluster and has an uncaught exception `cannot read property 'displayname' of undefined` when selected (when changing type from default, key/value -> configmap, key/value inputs remain).  This happens when editing an existing cluster. I was trying to add config map. Could not reproduce when creating a cluster, but did repro on edit
<img width="323" alt="Screen Shot 2021-02-23 at 6 33 14 PM" src="https://user-images.githubusercontent.com/16691014/108938938-c65f9900-7605-11eb-9c50-1c0a28000a3e.png">

<img width="1302" alt="Screen Shot 2021-02-23 at 6 04 53 PM" src="https://user-images.githubusercontent.com/16691014/108934649-db3a2d80-7601-11eb-9c43-c408d4527757.png">
<img width="1306" alt="Screen Shot 2021-02-23 at 6 04 36 PM" src="https://user-images.githubusercontent.com/16691014/108934665-dc6b5a80-7601-11eb-9de8-10c7c9e4b0a3.png">
<img width="1341" alt="Screen Shot 2021-02-23 at 6 04 28 PM" src="https://user-images.githubusercontent.com/16691014/108934676-dd03f100-7601-11eb-9f38-093e82f2503c.png">

**Able to add empty fields (causes warnings/breaks cluster)** : 
*  whe configmap entry is left blank, upon revisiting the edit page, user is unable to remove the config map/fix the error in the cluster. They can still delete the cluster and add a new one
<img width="1625" alt="Screen Shot 2021-02-23 at 6 29 46 PM" src="https://user-images.githubusercontent.com/16691014/108939309-5bfb2880-7606-11eb-8df1-0c6152924a34.png">

* leaving a `resource` or `key/value` or `pod field` empty results in no error or warning when revisiting the edit page.  Upon editing the cluster, the use can see that the empty environment var reverted to a key/value type. 
* after creating a cluster successfully, the config map and `secret key` are available when editing/creating new clusters.  However, when selecting `secret key` and saving the page, the user can see the UI revert the type to `key/value`.  When going back to edit the cluster, `secret key` is not available.   

![Screen Recording 2021-02-23 at 7 06 09 PM](https://user-images.githubusercontent.com/16691014/108941871-b1d1cf80-760a-11eb-8bc3-45a83d908949.gif)

<img width="400" alt="Screen Shot 2021-02-23 at 7 04 45 PM" src="https://user-images.githubusercontent.com/16691014/108941461-03c62580-760a-11eb-9e0d-ae614c957bc3.png">

**One last note:** I think it would be useful to give the user a dropdown to select from existing, valid `resource`, `configmap key` and `secret key`, given that the wrong selection will leave the cluster in a bad state.

**Comment by codyrancher** [comment]
> <img alt="Screen Shot 2021-02-23 at 3 35 58 PM" width="1350" src="https://user-images.githubusercontent.com/16691014/108926410-39abdf80-75f3-11eb-9e70-1ca659dc59a9.png">
> 
> Import cluster page does not have an option for environment variables

Kinara told me that she will open a separate ticket for this if she decides it's something we need.

> config map appears when editing a cluster and has an uncaught exception cannot read property 'displayname' of undefined when selected (when changing type from default, key/value -> configmap, key/value inputs remain). This happens when editing an existing cluster. I was trying to add config map. Could not reproduce when creating a cluster, but did repro on edit

This was only occurring when editing an `Existing nodes` cluster that had config maps or secrets. This should be resolved.

> Able to add empty fields (causes warnings/breaks cluster) :

Fixed this so that empty fields won't cause things to fail. When editing some of the envVars will revert back to keyValue because that's the best that can be inferred without the values set. Maybe we want to filter out fields that are empty or just add validation. But I think this should be opened in a separate ticket for 2.5.7 if you think that's what we should do.

> One last note: I think it would be useful to give the user a dropdown to select from existing, valid resource, configmap key and secret key, given that the wrong selection will leave the cluster in a bad state.

I don't want to change the UX here. This closely reflects the UX that's already been reviewed in dashboard.

**Comment by slickwarren** [comment]
on 2.5-head (67228a3cdba34161e1e03a4639b9c5b445e7b81b) the following were checked when creating/editing custom, imported, and node-driver clusters:
* [no error occurs when adding empty fields](https://github.com/rancher/rancher/issues/31023#issuecomment-786276371)
* the following were opened to address new issues: https://github.com/rancher/rancher/issues/31528 https://github.com/rancher/rancher/issues/31529

**Comment by slickwarren** [comment]
on 2.5.6-rc6, the following have been tested with downstream nodes behind proxy (testing with environment variables through the UI):
* import k3s cluster -- pass
* import rke cluster -- pass
* create custom cluster -- pass

* edit imported k3s cluster -- [failed through UI](https://github.com/rancher/rancher/issues/31545)
* edit import rke cluster  -- [failed through UI](https://github.com/rancher/rancher/issues/31545)
* edit custom cluster -- pass

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039` and master-head commit id: `f1e3e76d`**

After changes - https://github.com/rancher/ui/pull/4481
- Secrets are not available. Only key/value pair is available for entering agent Env variables - during create and edit of custom rke/rke node driver/ import rke/k3s clusters.
<img width="1437" alt="Screen Shot 2021-03-01 at 5 31 53 PM" src="https://user-images.githubusercontent.com/26032343/109583465-cd2e5600-7ab4-11eb-8d30-72675f95f7b1.png">

- Able to add env avriables on edit/create clusters.
