### ISSUE TITLE
Should be allowed to add "Listening ports" with no  source port for public ports when adding/editing LB services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3103]
Server version - Build from master

With #2097 in , UI should allow to add "Listening ports" with no source port for public ports when adding/editing LB services.

**Comment by vincent99** [comment]
This is going to be weird for balancers because we currently require a host port and container is optional.. The API is already changed though, so I'll change the UI to send 80:80 if you just put in source port=80.

Act now and we'll also throw in defaulting container port to 80 if the source port is 443+ssl, because people mess that up all the time.

**Comment by sangeethah** [comment]
Tested with latest build from master:

We still do not allow for source port to be empty from UI .
But we do allow for target port to empty in which case it gets defaulted to source port.

**Comment by sangeethah** [comment]
@vincent99 , Can you confirm that the behavior noted in the previous comment is what we allow from UI?
