### ISSUE TITLE
[Fleet] Disable Fleet doesn't uninstall it

### ISSUE THREAD

**Issue by mecseid** [rancher/rancher#31044]
**What kind of request is this (question/bug/enhancement/feature request):**
bug (or maybe enhancement)

**Steps to reproduce (least amount of steps as possible):**
Go to Feature Flags in Settings
Deactivate Fleet

**Result:**
Rancher restarts
Fleet still installed on local and downstream cluster

**Other details that may be helpful:**
I think if I disable the fleet feature in Rancher, then it will uninstall it after restart.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): single install (Docker)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.17.14

https://jira.suse.com/browse/SURE-2950

**Comment by nickgerace** [comment]
Since Fleet will be _required_ in Rancher 2.6.x for provisioning, this issue will be closed. If you are reading this comment and have substantive data for undesirable downstream Fleet agent performance, please reach out here, in [our users Slack](https://slack.rancher.io/), or via official support channels with details.

**Comment by mecseid** [comment]
Thank you @nickgerace the explanation.

I have some question about Fleet and CD feature.

1. If I stay on 2.5.x, then how can I delete Fleet? There is a feature flag where I can disable the Fleet installation, but as I see, it doesn't do anything at the moment. (not delete Fleet nor disable the Continuous Delivery option on the new UI)
![image](https://user-images.githubusercontent.com/6381828/117370331-87cc4180-aec6-11eb-9ddb-10f20df56cbf.png)
![image](https://user-images.githubusercontent.com/6381828/117370383-9a467b00-aec6-11eb-8c35-cee67995bc99.png)
2. What is the purpose of the previously mentioned disable option?
3. You said that Fleet will be required for provisioning in Rancher 2.6.x.
Could you explain me or give me some more details about it?
(for example, it will be required for provision new clusters, or multi-cluster applications, or single- and multi-cluster applications too, etc.)
I'm asking, because the other components in Rancher is optional, and if I don't want to use it, I could be able to disable it (such as logging or monitoring)
4. Will I be able to disable the Continuous Delivery feature in Rancher?
If I want to use another GitOps solution - ArgoCD/Flux - then I don't want to run Fleet to consume resources, give me unused CRDs, features, attack vector, etc..

**Comment by nickgerace** [comment]
Hi @mecseid. I'll answer your questions below:

> If I stay on 2.5.x, then how can I delete Fleet? There is a feature flag where I can disable the Fleet installation, but as I see, it doesn't do anything at the moment. (not delete Fleet nor disable the Continuous Delivery option on the new UI)

In each downstream cluster...

1. Uninstall the fleet-agent chart (or just delete the fleet-agent deployment)
2. Delete namespace(s) with `fleet` in the name

In the local cluster...

1. Uninstall the fleet-agent chart
2. Uninstall the fleet
3. Uninstall the fleet-crd
4. Delete the `fleet-system` namespace

There may be small artifacts left behind, but this will eliminate all persistent resources.

> What is the purpose of the previously mentioned disable option?

We have [feature flags](https://github.com/rancher/rancher/blob/909237a97ef01872a64006b90bf7cd4cb05d3120/pkg/features/feature.go) for new and optional features. These flags are intended for beta-level features primarily, but can be used for optional features handled by Rancher itself. For Fleet, it is *supposed* uninstall Fleet (at least in the local cluster), similarly to the steps above. This issue is valid (good find!), but we marked it as "won't fix" since Fleet is required for 2.6.x provisioning.

*(Side note: if you see/have Fleet performance issues and can provide substantive detail for them, please file an issue in [rancher/fleet](https://github.com/rancher/fleet). We'd like to investigate them!)*

> You said that Fleet will be required for provisioning in Rancher 2.6.x. Could you explain me or give me some more details about it?

Sure thing. Forewarning: we are always evaluating, and iterating on, the best path forward for Rancher, so everything is subject to change until you see an official release.

Rancher 2.6.0 is slated to be our next minor release. Our minor releases tend to have significant changes to the underlying Rancher architecture whereas our patch releases typically do not (which is the case for many semver-compliant projects, as you may be familiar with). Since the early days of Rancher 2.x, RKE has been our primarily provisioner for creating downstream clusters. Our [next generation provisioner](https://docs.rke2.io/) is slated to be used for Rancher 2.6.x provisioning (in addition to our existing provisioning framework).

The reason why Fleet needs to be installed is because of its "[bundle](https://fleet.rancher.io/concepts/)" orchestration. This does not necessarily mean that Rancher 2.6.x will use all the "GitOps" features that Fleet provides, but it is slated to use (at least) the "bundle" delivery part in conjunction with downstream cluster provisioning. Whether or not this affects single cluster use cases remains to be seen. We are carefully evaluating these things as 2.6.0 comes together.

> Will I be able to disable the Continuous Delivery feature in Rancher?

Like all your questions, this is a good question. Since the Rancher 2.6.x provisioning implementation is still in flux (see "Forewarning" above), I am ultimately unsure. This has been floated before, and if it's something you'd like us to dive into further, please feel free to file an issue. Like I mentioned prior though, I do not know how much of Fleet will be used for provisioning... or even _other_ parts of Rancher for that matter. I entirely understand where you are coming from though, and can see a use case to disable `X` percentage of Fleet functionality with the purpose of slimming it down to solely assist Rancher.

**Comment by mecseid** [comment]
Thank you for your comprehensive answer.
It helped me a lot to understand the actual and future behaviour/role of Fleet.

**Comment by nickgerace** [comment]
Not a problem @mecseid! Please feel free to reach out via the aforementioned channels if you have more questions :)

**Comment by songtianlun** [comment]
oh, i try to remove fleet/fleet-agent chart and namespace, Then my cluster disappeared.
