### ISSUE TITLE
Monitoring V2 can't access exporters when using private LAN

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#31056]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Launch a rancher managed cluster using nodes configured to have a second network interface providing only private LAN routing. Enable firewall for all incoming traffic on eth0 and allow all communicatio between nodes on eth1.

Configure RKE template to use eth1 as the canal interface:

```
  network:
    canal_network_provider:
      iface: eth1
    mtu: 0
    plugin: canal
    options:
      canal_iface: eth1
      canal_flannel_backend_type: vxlan
```

Launch monitoring v2 and navigate to Prometheus targets.

**Result:**

Nodes come up and cluster is created, monitoring v2 can be launched but prometheus can't reach node exporters (or other exported e.g. mongodb) due to 2 reasons:

1. The node exporter is being access by prometheus on the public ip of eth0. This fails because the certificate is valid for the ip address of eth1
2. Nodes cannot access each other over the public interface.

Essentially there should be a way to tell all internal services and endpoints to be configured to use only the private LAN. Due to autoscaling I don't know all the IP addresses of nodes when they are launched so can't simply open firewall traffic to the public IPs of the cluster nodes as a workaround.

**Other details that may be helpful:**

eth0 has public WAN IP and accepts only incoming traffic to the KubeAPI server
eth1 has private LAN IP and accepts internode traffic and WAN traffic via a hardware load balancer.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, 4 vCPUs / 8GB
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
N/A
```

**Comment by haswalt** [comment]
Nodes can't connect ot each other over the public WAN
![failed-node-exporter](https://user-images.githubusercontent.com/338588/106302688-2d7d6e00-6251-11eb-80ff-69479d5e0441.png)

The certificate was setup automatically for the internal LAN IP so when scraping etc metrics the cert fails to validate for the public WAN IP

![failed-etc-scrape](https://user-images.githubusercontent.com/338588/106302784-4dad2d00-6251-11eb-9a14-91a62f32906c.png)

**Comment by haswalt** [comment]
Maybe related to https://github.com/rancher/rancher/issues/31167. Allowing more customization of the addresses and ports in the charts?

**Comment by aiyengar2** [comment]
@haswalt [rancher-pushprox](https://github.com/rancher/charts/tree/release-v2.5/charts/rancher-pushprox/rancher-pushprox/0.1.2) can help you here. It's a chart specifically built for the purpose of scraping metrics across a network boundary (powered by a Rancher fork of a Prometheus community project called PushProx, which sets up a proxy that clients on nodes reach out to to send metrics through). This is also what powers all of our [cluster-type specific exporters](https://github.com/rancher/charts/blob/999fd4788a7cee740732231c3777d0b052638fa3/charts/rancher-monitoring/rancher-monitoring/9.4.202/values.yaml#L24-L233).

Normally, the Helm chart is hidden but if you add `?hidden` to the URL on the Apps & Marketplace page of the Cluster Explorer UI (where you install Monitoring), you can access the install page for the Helm chart. Under the values.yaml, try overriding the following:

```
clients:
  port: 10015
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
  useLocalhost: false
component: node-exporter
metricsPort: 9796
enabled: true
```

Before deploying this, you also want to make sure that [`node-exporter.enabled`](https://github.com/rancher/charts/blob/999fd4788a7cee740732231c3777d0b052638fa3/charts/rancher-monitoring/rancher-monitoring/9.4.202/values.yaml#L1514) is set to false on the Monitoring V2 chart's values.yaml on an install (this omits the service / ServiceMonitor created by the Rancher Monitoring chart in favor of the one created by PushProx). Leave `prometheus-node-exporter.enabled` on since you still need the node-exporter deployments.

rancher-monitoring-crd will also need to be installed since this chart needs the CRDs to be installed to avoid a failure on helm install.
