### ISSUE TITLE
[Backport] v2.4: Includes k3s upgrade images when uses image export script in dev, master, or non semver tag that is equal to kd.RancherVersionDev

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#31122]
**Original Issue:**
https://github.com/rancher/rancher/issues/31061

**Comment by jiaqiluo** [comment]
Reopen this issue because of missing images tags in the `rancher-images.txt` file on rancher:`v2.4.14-rc1`


Steps:
- get the compatible k3s versions from the [here](https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.4/data/data.json)
- get the `rancher-images.txt` from rancher:`2.4.14-rc1`'s [release page](https://github.com/rancher/rancher/releases/tag/v2.4.14-rc1)

Results:
- there are three compatible k3s versions for rancher:v2.4.14-rc1
```
v1.17.17+k3s1
v1.18.15+k3s1
v1.19.7+k3s1
```
- the `klipper-helm` images are in the `rancher-images.txt` file
```
rancher/klipper-helm:v0.2.3
rancher/klipper-helm:v0.2.7
```
**missing `docker.io/rancher/klipper-helm:v0.3.0` for supporting k3s `v1.19.7+k3s1`**
- the `k3s-upgrade` images are in the `rancher-images.txt` file  
```
rancher/k3s-upgrade:v1.17.17-k3s1
rancher/k3s-upgrade:v1.18.15-k3s1
```
**missing `rancher/k3s-upgrade:v1.19.7-k3s1` for supporting k3s `v1.19.7+k3s1`**


@rmweir  Do we expect to see all images in the `rke-images.txt` of a supported k3s release, such as [v1.19.7+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.19.7%2Bk3s1), are included in the `rancher-images.txt`?

**Comment by rmweir** [comment]
@jiaqiluo I don't think 1.19.7+k3s1 is compatible as it's constraints are as follows:
```
{
    "maxChannelServerVersion": "v2.5.99",
    "minChannelServerVersion": "v2.5.0-rc1",
    "version": "v1.19.7+k3s1"
}
```
We would expect to see all the images in k3s-images.txt if that were not the case though.

**Comment by jiaqiluo** [comment]
Thank you @rmweir for the confirmation!

This issue can be closed based on the following additional validation:
- only `v1.17.17+k3s1` and `v1.18.15+k3s1` are supported on rancher v2.4.14
- all images in `k3s-images.txt` are in `rancher-images.txt`
