### ISSUE TITLE
rancher-operator should not overwrite v3 cluster objects

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31120]
The rancher operator currently needs the entire cluster schema in order to modify it to add some fleet stuff. A problem now occurs when changes happen to the schema outside of the operator and aren't added to it, the operator drops those fields because it doesn't know about them, causing problems. 
We should remove the cluster schema (and importing of various pieces) and instead use dynamic-client, then it will just grab existing cluster as-is.

**Comment by cbron** [comment]
This is a bit of an edge case that is hard to QA. @cmurphy can you confirm on your side, then we can close. Donnie will have any needed details. Leaving in review for that process.

**Comment by cmurphy** [comment]
@cbron I can confirm that the immediate fix https://github.com/rancher/rancher-operator/pull/43 fixes the issue for me and doesn't override my `GKEConfig` field, and the effect of that fix should be verified when the fix for https://github.com/rancher/rancher/issues/31986 is confirmed. But my understanding of this problem is that there should ideally be a more generic fix where rancher-operator patches the cluster object properly and doesn't require synchronizing the Rancher version in go.mod.

**Comment by thedadams** [comment]
@cmurphy Yes, I made a change in rancher-operator that should be a more general fix. We just wanted to make sure it worked for you before calling it good.

**Comment by cmurphy** [comment]
Ah, sorry I missed that https://github.com/rancher/rancher-operator/pull/44 was added.

**Comment by cmurphy** [comment]
I built a version of rancher-operator containing this change and omitting the go.mod change and verified I could create a cluster without the gkeConfig field disappearing, so in my opinion this is working.
