### ISSUE TITLE
Change  "Audit Log" page to not be the default page for "Admin" tab.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3118]
Server version - Latest Build from master

Currently we have "Audit Log" as the default page to be loaded when accessing "Admin" tab . 
In set ups that are around for a long time we expect lot of entries to be present in "Audit Log" page whic would result in a delay in loading this page whenever "Admin" tab is accessed .

Can we not have "Audit Log" as the default page for "Admin" tab ?

**Comment by will-chan** [comment]
Settings or perhaps a "Admin dashboard" should be the default page for admin tab.

**Comment by vincent99** [comment]
No?  It's and processes are the only pages you're likely to go to more than occasionally.  If it's too slow it just needs to be faster.

**Comment by westlywright** [comment]
I lean towards leaving it as well. I am using a few different machines locally and not seeing speed issues. One of them is Darren's which i think is probably a good test case for this. If you look on latest audit logs can be slow but i feel like this is a poor test since latest is kind of a cesspool of activity that is not really echoed in real environments. I also fixed various issues in the last round that would have affected speed. Are we still getting speed issues?

**Comment by westlywright** [comment]
@vincent99 @will-chan is this still under discussion? Audit Logs perf seems pretty good with the recent changes to the call. Additionally with the new menu hover functionality you can select exactly what tab in admin you want to go to thereby bypassing the default of Audit Logs.

**Comment by will-chan** [comment]
Yep, I think we are done here.
