### ISSUE TITLE
external TLS on ALB doesn't work

### ISSUE THREAD

**Issue by dkim-dev** [rancher/rancher#31198]
Hi!

I'm spinning up a new Rancher Cluster in AWS using ALB with cert.

OS is Ubuntu 18, Docker 19, RKE 1.2.5, Rancher 2.4.8

After installation I wasn't able to add Cloud Credentials. was getting: 502 502: There was a problem validating your keys. Enter valid credentials and try again.

Creds are fine, I've used the ones that are already in use on another cluster, in addition I've created another Creds.

However, I've tested spinning the same combination on RancherOS 1.5.X. Everything worked just fine!!!

I've checked Firewall on Ubuntu - it is disabled by default.

I've found that I need to change DNSPolicy from "ClusterFirst" to Default for 'cattle-cluster-agent' and for 'rancher' pods. After that I was able to add creds and spin up downstream clusters. BUT, after spinning up Flux, I was getting messages in logs: 

ts=2021-02-08T22:47:26.515570919Z caller=warming.go:154 component=warmer canonical_name=index.docker.io/rancher/istio-sidecar_injector auth={map[]} err="Get \"https://index.docker.io/v2/\": x509: certificate is valid for *.<company_name>.farm, not index.docker.io"

So the patch wasn't fixing the problem, it was postponing it...

Is there a chance you know, how to fix the issue?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.8` and/or 'v2.4.13' UI: `v2.4.34` |
|Route|`undefined`|

**Comment by slessardjr** [comment]
I'm not quite sure where you problem is. The error you pasted clearly states you're using the wrong cert.  What are you doing that is causing it to pull the image from *.<company_name>.farm instead of index.docker.io?  I'm using an ALB for the rancher management plane without any issues. 

Is your issue with using ingress on a cluster where the ALB terminates?

Either way, I don't think GH issues will help you, you are probably better off checking their slack.  People are more likely to help you there.
https://slack.rancher.io/
