### ISSUE TITLE
The default docker engine script 20.10.sh is not available in the drop down to select from

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/rancher#31216]
on 2.5-head, 3c4c625
Currently, the docker engine has 20.10sh as the default script, 
if the user deselects this default and selects v19.0.3x or any other version from the drop-down
then the default 20.10.sh is not available in the drop-down to reselect it

<img width="1299" alt="Screen Shot 2021-02-09 at 12 28 29 PM" src="https://user-images.githubusercontent.com/72409237/107424990-3a148880-6ad3-11eb-8f14-a8a82aaaa893.png">

**Comment by westlywright** [comment]
The URL is available, its the `Recommended` url. This is pulled from the setting `engine-install-url` at `/v3/settings/engine-install-url`. 

@gaktive I think this should be pushed out of the release as the functionality has been present for quite sometime. If there is enough desire perhaps we can revisit it after the next release?

**Comment by gaktive** [comment]
So that I understand it, choosing Recommended from the dropdown means picking 20.10sh, so it is there as evidenced by the URL, just not in a clear fashion.

As noted, it's not regression and by the sounds of it, this would need backend changes. I'm curious about what happens when the Recommended docker version does get bumped in future versions and what work that would require. 

@sadiapoddar, based on other 2.5.6 UI work, is it OK if we push this to 2.5.7?

**Comment by westlywright** [comment]
@gaktive I think we can find a resolution that would clarify this without requiring a backend changes. But yes if we can push this out, Id like to so we're not introducing the risk of new bugs at the last minute.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `31f00c1` and master-head commit id: `1c3629`**
- docker 20.10 is available as default and as _Recommended_ in the dropdown in nodetemplates creation
- `Docker Version: 20.10.5` gets installed on the nodes - tested using node driver DO and AWS clusters
<img width="1402" alt="Screen Shot 2021-04-20 at 12 41 28 PM" src="https://user-images.githubusercontent.com/26032343/115454656-e1015900-a1d5-11eb-9a50-2dd17ba51a32.png">
