### ISSUE TITLE
cattle-cluster-agent fails to become ready without a worker role/node present due to coredns dependency

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#31244]
For Rancher 2.5.5 and potentially previous versions as well

When building a new custom cluster, if the only nodes added are etcd/cp and there are no worker roles attached to those nodes or a worker node added, cattle-cluster-agent will fail to become ready due to a dependency on coredns. The agent will flap every second or two until it ends up in a crashloopbackoff state. This is due to the cattle-cluster-agent deployment not using host-networking or `ClusterFirstWithHostNet` DNSPolicy.

This is only an issue when the CATTLE_SERVER env variable is a URL that requires dns resolution. If a public/private IP is used instead when building rancher, this issue will not be present and the cattle-cluster-agent will successfully register

note: cattle-node-agent and the rancher agent uses host networking so it does not exhibit this issue

**Comment by sowmyav27** [comment]
On 2.5-head- commit id: `dba33211` 

- On HA setup(Rancher URL having a route53 entry)
- Deploy a 1 node custom cluster - Linux cluster and also validated using windows cluster - FLannel/VXLAN
- Add one linux node - etcd+control plane roles.
-  The cluster comes up Active. 
- Cattle cluster agent is up and active 
- Metrics server, coredns and coredns autoscaler pods are in error state --> expected as there is no worker nodes in the cluster yet. 
- Add a linux worker node, all these ^^^ pods come up Active.

**Comment by stefanlasiewski** [comment]
Sounds related to https://github.com/rancher/rancher/issues/24078

**Comment by sowmyav27** [comment]
Reopening to revert the fixes

**Comment by sowmyav27** [comment]
2.5 UI PR: https://github.com/rancher/ui/commit/d197f4d5cc1f1a628843c72ee0a5c0420766526b

**Comment by sowmyav27** [comment]
**On master-head commit id: `5bf4b5de7` and 2.5-head commit id: `87006de`**

- Deploy a custom cluster with no nodes
<img width="461" alt="Screen Shot 2021-02-23 at 5 10 02 PM" src="https://user-images.githubusercontent.com/26032343/108930080-18022680-75fa-11eb-87be-da47a6306652.png">

- Registration command page for custom cluster:
<img width="1249" alt="Screen Shot 2021-02-23 at 5 11 58 PM" src="https://user-images.githubusercontent.com/26032343/108930174-4aac1f00-75fa-11eb-8f20-c63801087f1b.png">

**Comment by deniseschannon** [comment]
For node driver RKE clusters, we have always forced users to create one node for each role in the UI, but for Custom RKE Clusters, users could create a cluster without worker role nodes due to how you add nodes into a cluster. On a cluster without worker roles, cluster shows up as not Ready complaining about agent not ready in UI: `"Msg: Cluster health check failed: cluster agent is not ready"`. In API, Cluster Condition Ready is set to False with the same reason.

On startup, cattle-cluster-agent connects to CATTLE_SERVER (Rancher Server URL) and if this is set such that it requires DNS resolution, agent requires coredns to be running to start successfully. coredns can only be scheduled on worker nodes, so coredns pods fail to be scheduled when there are no worker nodes. Sample error:
```
INFO: Environment: CATTLE_ADDRESS=10.42.0.2 CATTLE_CA_CHECKSUM=486dc89d34e6ca0a7b76ddddcb9648f21758b1d9b94a31ba7127cd229008e749 CATTLE_CLUSTER=true CATTLE_FEATURES=dashboard=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-6b8bc8c67-lj6gp CATTLE_SERVER=https://ec2-54-148-108-134.us-west-2.compute.amazonaws.com
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal options ndots:5
ERROR: https://ec2-54-148-108-134.us-west-2.compute.amazonaws.com/ping is not accessible (Could not resolve host: ec2-54-148-108-134.us-west-2.compute.amazonaws.com)
```

cluster-agent failing is exactly the same between v2.4.x and v2.5.x. The only difference is that 2.4.x will show the cluster as "healthy" and `Active` where as 2.5.x will be stuck in `Provisioning.

We cannot change the dns policy of cluster-agent because controllers rely on cluster agent's dns resolution to communicate with the cluster, causing issues like https://github.com/rancher/rancher/issues/31365. And we will not update the logic to allow coredns pods to be scheduled on non-worker nodes. 

Therefore, we will not be supporting this use case and you are required to add one of each role into the cluster.
