### ISSUE TITLE
rancher-monitoring-crd install not passing through ArgoCD

### ISSUE THREAD

**Issue by rajivml** [rancher/rancher#31619]
HI,

**Chart Name:** rancher-monitoring-crd
**Rancher Charts Version:** https://github.com/rancher/charts/tree/release-v2.5/charts/rancher-monitoring/rancher-monitoring-crd/9.4.203

Am trying to deploy rancher-monitoring-crd through argoCD but am hitting this roadblock where argoCD uses "helm template" followed by "kubectl apply -f " to apply the template and since the size of the configMap is exceeding 256KB the install via argoCD is getting failed

![image](https://user-images.githubusercontent.com/46923567/110266204-52e56080-7fe3-11eb-967d-70603fe1029c.png)

https://github.com/argoproj/argo-cd/issues/2730
https://github.com/argoproj/argo-cd/issues/5704
https://github.com/kubernetes/kubectl/issues/712

To overcome this limitation, instead of packing all these CRD's into a single configmap, can you create different configmaps depending on purpose and also there might be other charts like grafana which might have this problem, so can we have an permanent fix here ?

![image](https://user-images.githubusercontent.com/46923567/110266450-d1da9900-7fe3-11eb-8c45-09d10ec0a422.png)
![image](https://user-images.githubusercontent.com/46923567/110266474-de5ef180-7fe3-11eb-89d6-c5c143ead88c.png)

**Comment by rajivml** [comment]
I have modified this chart such that , one configMap get created for each manifest, but even after doing so it failed again with the same error, looks like thanosrulers itself is quite big 

![image](https://user-images.githubusercontent.com/46923567/110277511-68668480-7ffb-11eb-9c9e-ee39f8d94c5f.png)




```
{{- $crds := (.Files.Glob  "crd-manifest/**.yaml") -}}
{{- range $path, $_ :=  $crds -}}
{{- $name := (split "." (base $path))._0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-manifest
  namespace: {{ $.Release.Namespace }}
data:
  crd-manifest.yaml: |
    {{ $.Files.Get $path | nindent 4 }}
{{- end }}
```

**Comment by rajivml** [comment]
same problem with prometheus and alertmanager CRD's as well , now I almost lost the hope that the same can be deployed via argoCD :)  cc @nikkelma 

![image](https://user-images.githubusercontent.com/46923567/110286370-d1092d80-800a-11eb-9c9e-914b77559dd0.png)

**Comment by aiyengar2** [comment]
cc: @StrongMonkey w.r.t. how we deploy these Helm charts, but I'm pretty sure we do a `helm upgrade --install`.

This reminds me of an issue we faced earlier in https://github.com/rancher/rancher/issues/29973. We never ended up resolving it, probably because we switching to using `helm upgrade --install` instead of `helm template` to `kubectl apply -f`.

FYI I also don't think doing `helm template` and `kubectl apply -f` is a good idea for the Monitoring Helm chart in general since we use Helm Hooks to do actions like installing the Alertmanager Secret or patching the default service account. I don't think that approach respects the ordering / execution of Helm hooks based on the provided annotations on the resources.

**Comment by StrongMonkey** [comment]
Yeah this is a common problem in kubectl apply, which they track the previous applies object into annotations so they can figure out what needs to be patched on the next apply. I wonder if these can be solved using server side apply. We had the same problem in wrangler too.

**Comment by StrongMonkey** [comment]
Another option would be [fleet](http://fleet.rancher.io/), which use helm to install all the things(no kubectl apply). If argo-cd support server side apply you could also try that.
