### ISSUE TITLE
[api-spec] [Rancher API v3] REPLACE operation on Rancher Helm App not working

### ISSUE THREAD

**Issue by theAkito** [rancher/rancher#31705]
https://github.com/rancher/api-spec/blob/master/specification.md#replace-operation

As explained in this part of the API spec, I issued a `REPLACE` request.

The request went through and I received a `200 OK` HTTP status code.

> * Either ALL the changes succeed and a 2xx response code is returned,
> * or NONE of the changes are committed and a 4xx or 5xx code is returned.

According to above quote taken from the specification, my request was valid and was ultimately completely executed.

However, this is not the case. The Rancher Helm App in question remains absolutely untouched. Nothing happens.

Even if something is "wrong" with the request, it should not output a `200 OK` HTTP status code.

The Rancher Helm App that is supposed to be replaced, is retrieved, 2 values in the `answers` object are modified (the modified Rancher Helm App is confirmed to be sent to the server correctly, all this has been already debugged) and then it is sent to the server through a `REPLACE` request, as defined in the API specification.

Rancher API v3 is used to submit the operation and everything seems to "work", except it does not, after all.

I cannot use a Rancher API client, because all available clients are outdated, except one, but the one not outdated cannot handle Rancher Helm Apps. It barely can handle anything.

I cannot post the request content here.

How can I make the `REPLACE` operation work?

**Comment by vincent99** [comment]
The api-spec is an entirely generic document that knows nothing about Rancher-specific APIs (and predates the company entirely).  No current Rancher-product APIs implement `REPLACE` and should return 405/Method Not Allowed, which is what I see attempting to send e.g. `REPLACE /v3/project/<project id>/apps/<app id>`.

And this would be an odd use for it; you want to tear down the whole app and then reinstall it again with slightly different answers instead of doing a helm upgrade?

The normal way to do an upgrade is POSTing to the app's `upgrade` link (which will be `/v3/project/<project id>/apps/<app id>?action=upgrade`) with new `externalId`, `answers`, and/or `valuesYaml`s in the body.

What clients are you referring to?  The [golang](https://github.com/rancher/rancher/tree/master/pkg/client) client is part of the source tree and used by Rancher itself.  And the [python](https://github.com/rancher/client-python) one is an entirely generic implementation of the spec which also knows nothing about Rancher products and dynamically exposes whatever the schema of the API you point it at has; so it can't be "outdated".

**Comment by theAkito** [comment]
> you want to tear down the whole app and then reinstall it again with slightly different answers instead of doing a helm upgrade?

Precisely. Rancher's reliability is in some aspects **extremely low**. For example, upgrading a Rancher Helm App does not always produce the expected results and there is nothing a user can do about it. Sometimes Rancher just happily breaks things.
Such issues usually can be avoided by deleting a resource and creating it completely from scratch. This usually mitigates most stability issues.


> The normal way to do an upgrade is POSTing to the app's `upgrade` action link (which will be `/v3/project/<project id>/apps/<app id>?action=upgrade`) with new `externalId`, `answers`, and/or `valuesYaml`s in the body.

Yes, the "normal" way is the worst way, as described above. For example, issuing a Helm upgrade action usually does not work, except one ticks on the `Delete and recreate resources if needed during the upgrade (uses helm --force)` checkbox. And even then I have seen no way of "ticking" this "checkbox" through the Rancher API. Perhaps you can explain to me how to do that with an `Action` request.



> What clients are you referring to? The [golang](https://github.com/rancher/rancher/tree/master/pkg/client) client is part of the source tree and used by Rancher itself. And the [python](https://github.com/rancher/client-python) one is an entirely generic implementation of the spec which also knows nothing about Rancher products and dynamically exposes whatever the schema of the API you point it at has; so it can't be "outdated".

Well, Go is a no-go, so that is already out of the question.
As for the Python client, of course Python is **not** used for critical operations.

I am implementing Rancher API functionalities in a Kotlin app. There are only outdated Java libraries, except the one I mentioned in the OP. And of course there are exactly 0 Kotlin libraries, which would be the most preferred type.

So the point is basically, that I do not want to and cannot use a simple and generic "Upgrade" Action, because it is inherently unreliable, unsafe, unpredictable and most of the time does _not_ do what it _should_ do.

The app implementing the Rancher API functionality uses the API to do absolutely critical Rancher Helm App related operations. None of these operations may fail. Therefore, I can't just use the "normal way" to upgrade a Chart, praying that Rancher won't screw things up again and again. The functionality I am building into the application needs to be absolutely safe and reliable.

That said, I do not follow your remarks regarding the generic nature of the API spec.

>  This is also the same documentation our internal teams use to build their APIs.

If that quote from the README.md in the [api-spec repository](https://github.com/rancher/api-spec) is true, then I expect this spec to be worth their 2 cents.

**Comment by vincent99** [comment]
> Precisely. Rancher's reliability is in some aspects extremely low.

All Apps are ultimately doing is calling helm, which has its own problems, so it's unclear what you're actually running into or who is actually calling it with no details.  "Rancher Apps" (in /v3) adds a layer that was needed at the time because Helm 2 had no multi-tenancy support.  In 2.5+ the "Cluster Explorer" has a more direct integration with Helm 3 where this is no longer needed and that is a separate API and probably what you'd want to be using now.

>  And even then I have seen no way of "ticking" this "checkbox" through the Rancher API. Perhaps you can explain to me how to do that with an Action request.

The UI is just static HTML/JS talking to the API.  There is no magic, anything it does you can do too.  The `upgrade` action takes a body of type `appUpgradeConfig`, which has a `forceUpgrade` field.  You can see all this just looking around the API in a browser.

![image](https://user-images.githubusercontent.com/753917/111222251-d03b4300-8598-11eb-9ef6-b0f76b9973c6.png)

> If that quote from the README.md in the api-spec repository is true, then I expect this spec to be worth their 2 cents.

I wrote it.  And the APIs you're using follow that spec (for the most part), and for REPLACE it says `Services MAY implement replace for any collections where they see fit.`, and none of the Rancher-product services "DO" implement it.

> Are you using a client or how do you get this result?

It's a HTTP server; the client doesn't really matter, but I used curl.

> Is your target Rancher instance on a 301 Redirect? If yes, you need to permit redirects for this arbitrary non-standard HTTP method. Then you will get a 200 OK, as in my case. (Which proves, the server part is broken in this specific regard.)

Redirects are a 301/2 status code and a Location header.  The server does not decide how the client interprets that.  The standard behavior of most HTTP clients is to follow that by sending a GET to the Location header, not to preserve the method or re-submit the body.  This is a problem with your client, not the server.  It sounds like you're effectively sending a GET for the app, which of course has no mutating effect.

**Comment by theAkito** [comment]
> All Apps are ultimately doing is calling helm, which has its own problems, so it's unclear what you're actually running into or who is actually calling it with no details.

Yes, I assumed it is mainly a problem with Helm, but from a user perspective, it does not matter. If it does not work, it does not work, no matter why. The upgrades were almost always issued through the Rancher UI.



> "Rancher Apps" (in /v3) adds a layer that was needed at the time because Helm 2 had no multi-tenancy support. In 2.5+ the "Cluster Explorer" has a more direct integration with Helm 3 where this is no longer needed and that is a separate API and probably what you'd want to be using now.

Thank you for the explanation, that clears up some of the fog.
Do you mean "separate API" as in the Cluster Explorer part having a completely separate API or did you refer to Helm 3?



> The UI is just static HTML/JS talking to the API. There is no magic, anything it does you can do too. The `upgrade` action takes a body of type `appUpgradeConfig`, which has a `forceUpgrade` field. You can see all this just looking around the API in a browser.

Well, seems like I did not browse the visual API long enough. Thanks for this hint.



> I wrote it. And the APIs you're using follow that spec (for the most part), and for REPLACE it says `Services MAY implement replace for any collections where they see fit.`, and none of the Rancher-product services "DO" implement it.

I understand, but that way I could never be sure, what is actually implemented, when reading the specification, as there were only very few "MUST" keywords and way too many "SHOULD" and "MAY" keywords. Therefore, I hoped that most things would be implemented.



> Redirects are a 301/2 status code and a Location header. The server does not decide how the client interprets that. The standard behavior of most HTTP clients is to follow that by sending a GET to the URL in the Location header... not to preserve the method or re-submit the body. This is a problem with your client, not the server. It sounds like you're effectively sending a GET for the app, which of course has no mutating effect.

I actually had to implement a custom `RedirectStrategy` for the `REPLACE` method I initially tried to use, as this method is an arbitrary one. I then used the custom `RedirectStrategy` for all further HTTP methods, as well.

Turns out, I wrongly assumed that the `getRedirect()` method was good enough, as I saw that it forwards all request bodies on HTTP redirects. After you mentioned this issue, I checked this method a bit closer and noticed, that the body only gets forwarded for 302 (temporary redirect) status, not for 301 (permanent redirect) status.
So, in the end, the `GET`ing was indeed the problem the whole time.

Well, what a journey.

Thank you very much for the explanations, I appreciate it!
In the end, this issue was my fault for not configuring the HttpClient correctly, as needed.

**Comment by vincent99** [comment]
> Do you mean "separate API" as in the Cluster Explorer part having a completely separate API or did you refer to Helm 3?

Yes there is a separate API endpoint for explorer.  `/v3` (which is elsewhere called "Norman") was to varying degrees an attempt to make the native Kubernetes APIs better/more consumable for the UI/more like the Rancher 1.x API.  Structures are flattened down to be less deep, things are renamed to be more consistent, only the types that are needed are exposed, everything goes through Projects, etc, basically lots of hand-decided and written mappings.

Explorer and it's API (which is under `/v1` but inside of individual clusters, so `/k8s/clusters/<cluster id>/v1`) goes the opposite direction in changing as little as possible to make the native k8s APIs show up and work with our clients.  All types are mechanically translated and available by default, and only a few special things are hand-maintained to do special behaviors.
 e.g. aggregating watches into one websocket.  Or getting the counts of how many of what resources there are in the whole cluster is impractical with the k8s API, so there's a special `.../v1/counts` resource that does that efficiently.  A few things are still actions (helm upgrade being one).

This generally all goes along with getting towards being able to do "gitops" for all the resources going forward, which hasn't always been the case before.. Various existing Rancher resources live in the management/local cluster and can only be correctly manipulated through the logic in Norman, not directly through k8s API.
