### ISSUE TITLE
[Forwardport]Private Registry authentication with no credentials fails 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31733]
Forwardport of https://github.com/rancher/rancher/issues/31600

**Comment by slickwarren** [comment]
This needs an RC in order to fully test. 
on 2.5-head:
I was able to download the rancher-images.txt through the UI and use it for newer image tags in order to deploy a cluster using the private registry. However, that image list does not include updated images for all charts/apps (i.e. fleet or monitoring). The rancher-images.txt downloaded from the releases page does include this information.

**Comment by slickwarren** [comment]
tested the following on v2.5.8-rc2:
Cluster level Private Registry
* Node driver cluster with Priv reg with no Auth
  * deploy CIS Benchmark app
* Custom cluster with Priv reg with no Auth

Global Level Private Registry
* Node driver cluster with Priva reg with no Auth
* Custom cluster with Priva reg with no Auth
  * deploy CIS Benchmark app
