### ISSUE TITLE
Grafana graphs are not seen for Windows nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31742]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5-head, commit id: ff68b3a
- Deploy a windows cluster - 1909
- Deploy monitoring v2 on the cluster
- Noticed that Grafana graphs are missing for windows nodes

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `ff68b3adc`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): windows custom
- Kubernetes version (use `kubectl version`):

```
Any
```

**Comment by thehejik** [comment]
Just found out the same, there are 3 nodes related dashboards in Grafana:
* `USE Method / Node` - refers only to linux nodes in Instances dropdows
* `Nodes` - dtto
* `Kubernetes / Compute Resources / Node (Pods)` - there are listed also windows nodes in the dropdown but it is reporting "No data" in all graphs.

All these dashboards are showing graphs for Linux nodes normally.

I've also tried to deploy a windows workload in default namespace but it is still showing "no data".

**Comment by aiyengar2** [comment]
Thanks for calling this out / looking into this @sowmyav27 and @thehejik. I'm looking into how to tackle this issue right now.

**Comment by aiyengar2** [comment]
I've reached a slight blocker with this issue. Will schedule offline design discussion to move forward. 

### Context

Based on the approach outlined in https://github.com/rancher/rancher/issues/31742#issuecomment-801870488, I started looking into using the Monitoring V1 approach of embedding Windows host metrics into the Linux host dashboards to enhance the existing Dashboards with Windows metrics. 

This involved:
1. Creating recording rules in PrometheusRules that map `windows_exporter` metrics to `node_exporter` metrics, so that Prometheus itself would add those Windows metrics to the series exposed by `node-exporter` itself
2. Modifying the Dashboard queries to be scoped to `{job=~"node-exporter|windows-exporter"}` instead of `job="node-exporter"`, since the series they point to now support both types of jobs

However, this approach is problematic since **windows_exporter and node_exporter do not necessarily have parity w.r.t. the metrics that they export.** 

Specifically, it seems like:
- At least one panel from each Node dashboard (`USE Method / Node`, `Nodes`, and `Kubernetes / Compute Resources / Node (Pods)`) uses a series that does not have a clear counterpart in `windows_exporter`. 
- Even if they have a counterpart, it is not safe to assume that the values of the series themselves have the same semantics: e.g. In Monitoring V1, we currently map `wmi_os_physical_memory_free_bytes` to `node_memory_MemAvailable_bytes` but the prior is [`Bytes of physical memory currently unused and available`](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.os.md) while the latter is strictly the bytes that are "available".
- `windows_exporter` exposes additional Windows specific metrics that would enhance the experience of users using Windows hosts, but these would not make sense to be added into existing Node dashboards

Furthermore, since Monitoring V2 forks upstream [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack), which in turn forks from upstream [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) for Dashboards, this will be an issue we'll have to continually address every time we rebase to an upstream, such as in https://github.com/rancher/rancher/issues/29871.

### Proposal

We split Windows metrics to their own set of Dashboards / Prometheus Rules that will be maintained entirely independently of existing Linux host dashboards / rules. 

#### Existing Linux Node Dashboards

These will need to be relabeled:
- `USE Method / Node` => `USE Method / Linux Nodes`
- `Nodes` => `Linux Nodes`
- `Kubernetes / Compute Resources / Node (Pods)` => `Kubernetes / Compute Resources / Linux Node (Pods)`

#### Windows Dashboard(s)

While there is no official source for these dashboards, we could attempt to base the dashboards on [community-provided dashboards](https://github.com/prometheus-community/windows_exporter/issues/721#issuecomment-777282709) currently offered on Grafana's website. 

#### Windows PrometheusRules (alerts)

None required right now since they were not supported in Monitoring V1. Users can request for specific alerts to be added post-release.

@cloudnautique from a product perspective, does this UX for Windows users make sense to you or do you feel strongly about a unified dashboard solution? Also, are there any additional product requirements for Windows node metrics that you would expect aside from eventual Monitoring V1 parity?

**Comment by thehejik** [comment]
@aiyengar2 thanks for the valuable info. Just tried two grafana dashboard which work out-of-the-box with windows_exporter:
* https://grafana.com/grafana/dashboards/13466 really nice one
* https://grafana.com/grafana/dashboards/13868 additional translation needed

**Comment by aiyengar2** [comment]
Conclusions from design meeting:

Proposal has been accepted. We will use community provided Windows-only dashboards for now and prioritize a unified Windows + Linux host dashboard at a later date (re: https://github.com/rancher/rancher/issues/31878).

These dashboards will also have to be displayed as part of https://github.com/rancher/dashboard/issues/812 to provide a unified experience on the Rancher UI, even though they will be exposed as separate panels on Grafana.

**Comment by aiyengar2** [comment]
For 2.5.8, we are addressing this issue in https://github.com/rancher/rancher/issues/31921.

For additional dashboards beyond what will be supported in the Cluster Overview dashboard, we will track it in https://github.com/rancher/rancher/issues/32104.

Closing this issue in favor of those two issues.
