### ISSUE TITLE
[monitoring] issue with rancher-monitoring in a k3s cluster

### ISSUE THREAD

**Issue by iioragg** [rancher/rancher#31825]
Hi everyone,
I am unable to install monitoring on my k3s cluster via rancher 2.5.5, every pods is running, but the solution not work.
In particular, I notice that pushprox-clients are unable to contact the pushprox-server.
By installing the various components separately **without rancher**, they work (there is not the pushprox)

Is there the possibility to remove the pushprox from the deployment or is it essential for rancher? 
Has anyone with a k3s cluster had similar issues?
Thanks.

**Comment by aiyengar2** [comment]
@iioragg What version of Monitoring V2 do you have deployed? 

Also if you click on the Edit as YAML view when deploying the Monitoring V2 chart, is the correct PushProx (k3sServer, found [here](https://github.com/rancher/charts/blob/aae93d0125fad561024b25ac1a15580ea612e158/charts/rancher-monitoring/rancher-monitoring/9.4.203/values.yaml#L94) in the values.yaml) deployed?

### Context

The purpose behind k3sServer is in order to allow you to scrape metrics from the k3s server nodes (e.g. those that correspond to kube-controller-manager, kube-scheduler, and kube-proxy for k3s), even in a hardened cluster setup (that blocks all **inbound** communication to nodes only). Without PushProx, you will be unable to collect these metrics.

The way this is accomplished is via having the pushprox-clients reach out to a pushprox-server to establish a connection which will be used by Prometheus to scrape metrics by proxying requests to the pushprox-clients through pushprox-server. 

One explanation for why you might be encountering these issues is that the pushprox-clients are unable to make outbound requests to the pushprox-server to establish the connection due to firewall rules on your nodes or pods.
