### ISSUE TITLE
Global Admin unable to create/edit cluster if cluster-template-enforcement is true and user has additional global role

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#31822]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher instance (tested with v2.5.5 and v2.5.7)
2. Set `cluster-template-enforcement` setting to `true`
3. Create a custom cluster and observe creation is successful
4. Edit the Default Admin user and add `User-Base` or `Standard User` to the `Global Permissions` alongside existing `Administrator`
5. Attempt to create a custom cluster

**Result:**

Observe cluster creation fails with `Validation failed in API: A clusterTemplateRevision to create a cluster is required`

**Environment information**
- Rancher v2.5.5/v2.5.7

**Comment by superseb** [comment]
Summary of refinement:

- We need to check why the `isAdmin` check is failing for the user after adding the additional global role, this could be because the function is not addressing having multiple roles or the additional role is actually overwriting/stripping the admin from the role/rules that are needed to be an admin.
- Based on the investigation above, we need to figure out what the intention is of adding roles or fix the `isAdmin` function if the admin role/rules are still intact.
