### ISSUE TITLE
Validate vSphere Out Of Tree on an RKE Local cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31839]
Validate RKE Local cluster deployment using vSphere Out of Tree config

gz#15314

**Comment by bmdepesa** [comment]
Updating current status: 

Currently I have working steps for installing the OOT cloud provider on an RKE cluster via Helm outside of Rancher, then installing Rancher via Helm

Two additional scenarios I want to test: 
* Creating an RKE cluster setting `cloud_provider=external`, then installing Rancher, then installing the charts (I'm not sure if this will work due to the taints applied when `cloud_provider=external`
* Creating an RKE cluster without cloud provider, installing Rancher, and then configuring the OOT cloud provider through Rancher (either rke up with `cloud_provider=external` then install charts through Dashboard, or edit cluster in Rancher UI then install charts through Dashboard)

**Comment by bmdepesa** [comment]
We should also test migration of an RKE cluster using the in-tree provider to using the out-of-tree provider

**Comment by bmdepesa** [comment]
Steps added to docs issue here - https://github.com/rancher/docs/issues/3151
