### ISSUE TITLE
Disabling last active environment borks rancher

### ISSUE THREAD

**Issue by simpsonjon** [rancher/rancher#3183]
So I was having an issue and found a weird bug. If you only have one environment, in my case default, and you disable it using the dropdown menu rancher no longer works and you can't load any pages or create a new environment.

edit: 
So I used a different browser and the page refreshed correctly and simply showed the default environment as inactive. I added another environment and the original browser was able to continue using the rancher app. 

I am able to recreate this issue by disabling all environments. Which ever browser I execute the last disable in shows a white page that will flash a 'loading' message but never load. An alternative computer or browser can change state of the environments. The original browser will work when at least one environment is active.

**Comment by deniseschannon** [comment]
This used to work fine as I've done it before, but just tested with v0.51.0 and confirmed that this is broken now.

I can never access it again though even if I go to a new browser.

**Comment by deniseschannon** [comment]
Verified with v0.56.0-rc1 that it doesn't bork Rancher anymore.

**Comment by deniseschannon** [comment]
But there are other underlying issues. 

1. The main menu disappears instead of just the active environments side bar.

<img width="1163" alt="screen shot 2016-01-20 at 8 07 50 pm" src="https://cloud.githubusercontent.com/assets/11410997/12471332/83d831b0-bfb1-11e5-9f5b-2249a00997f8.png">

2. After re-activating the last environment that was deactivated, it doesn't refresh the UI to indicate it's active. 

<img width="1156" alt="screen shot 2016-01-20 at 8 08 37 pm" src="https://cloud.githubusercontent.com/assets/11410997/12471364/c398b7de-bfb1-11e5-9ea7-eef86461dae8.png">

**Comment by vincent99** [comment]
1) Is intentional, there are no environments so there's no things to go manage.  I suppose Admin and Help don't *need* to be hidden, but this isn't new.

2) Asploding trying to refresh, fixed next build

**Comment by tfiduccia** [comment]
version - 0.56.0-rc2
Verified fixed
