### ISSUE TITLE
GKE: private endpoints

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31895]

**Comment by cmurphy** [comment]
How to test:

## Scenario 1: Public endpoint, private nodes, no outgoing access to the internet from nodes

On GKEClusterConfigSpec, set 

```
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
```

Nodes will not have access to the internet, so if created from Rancher, so the [air-gapped installation instructions](https://rancher.com/docs/rancher/v2.x/en/installation/resources/local-system-charts/) need to be followed to ensure the nodes have access to the necessary charts and images. Rancher itself does not necessarily need to be installed in the same VPC since it can access the cluster's public endpoint.

## Scenario 2: Public endpoint, private nodes, [Cloud Nat](https://cloud.google.com/nat/docs/using-nat)

On GKEClusterConfigSpec, set 

```
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
```

No other steps are needed.

## Scenario 3: Public endpoint, private nodes, authorized networks

On GKEClusterConfigSpec, set 

```
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
  masterAuthorizedNetworks:
    enabled: true
    cidrBlocks:
    - displayName: example
      cidrBlock: <rancher server IP range>
```

Add Rancher's public IP to authorized networks. This blocks requests from other networks outside of GCP. Testing should ensure that Rancher still has access to the cluster.

## Scenario 4: Private endpoint, private nodes,no outgoing access to the internet from nodes

On GKEClusterConfigSpec, set

```
  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
```

Nodes will not have access to the internet, so if created from Rancher, so the [air-gapped installation instructions](https://rancher.com/docs/rancher/v2.x/en/installation/resources/local-system-charts/) need to be followed to ensure the nodes have access to the necessary charts and images. Rancher needs to either run in the same VPC or be connected with [Cloud VPN]https://cloud.google.com/network-connectivity/docs/vpn/concepts/overview() or [Cloud Interconnect VLAN](https://cloud.google.com/network-connectivity/docs/interconnect).

## Scenario 5: Private endpoint, private nodes, [Cloud Nat](https://cloud.google.com/nat/docs/using-nat)

On GKEClusterConfigSpec, set

```
  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
```

1. In the GKE console, create a VPC network and subnet https://console.cloud.google.com/networking/networks/list

2. In the GKE console, create a Cloud NAT gateway for your network https://cloud.google.com/nat/docs/using-nat#creating_nat

3. Create your cluster in Rancher, with Spec.Network and Spec.Subnetwork referring to the network you created, and Spec.PrivateClusterConfig.EnablePrivateEndpoint and Spec.PrivateClusterConfig.EnablePrivateNodes set to true and Spec.PrivateClusterConfig.MasterIpv4CidrBlock set to a /28 range. Keep track of the cluster name, region or zone, and node pool name for later.

4. Wait for the cluster to be ready in GKE.

5. Once the cluster is created, the cluster agent needs to be manually installed in order to allow Rancher to access the cluster. You will need to download a kubeconfig and be able to connect to the private control plane endpoint in some way. This could by creating a compute instance with your kubeconfig credentials on the same VPC, or connecting to the VPC via a VPN. If you don't want to create an additional node and you don't have a VPN, you can create an SSH tunnel through one of the cluster nodes.

6. The Rancher UI should prompt you run a `kubectl` command on the cluster to register it with Rancher.

**Comment by prabalsharma** [comment]
Bugs:
https://github.com/rancher/rancher/issues/32251
https://github.com/rancher/rancher/issues/32241

**Comment by prabalsharma** [comment]
Supported Scenarios (https://confluence.suse.com/display/EN/GKE+Private+Cluster+Scenarios): 
2, 3 only with NAT and 5. Only these three will be tested, as decided in todays meeting with Caleb, Ricky and Colleen.
