### ISSUE TITLE
When incorrect information is entered in monitoring v2 grafana persistent volume, a reinstall using correct information still does not install correctly

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31900]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* install longhorn (for PV)
* Install monitoring 
  * in grafana options, enable persistent volumes with statefulset template 
  * enter incorrect information or leave one of the options blank for persistent volumes (i.e. size is left blank)
* installation of grafana will fail, while other monitoring resources should install correctly
* reinstall monitoring with correct PV information

**Result:**
* grafana statefulset and other resources are not cleaned up(?), so monitoring will now fail with any configuration of grafana with PV enabled
* The only way to enable grafana is to disable PV.  Disabling then re-enabling does not work either

**Other details that may be helpful:**
* entering the correct configuration for PV on the first try will allow grafana to correctly install with PV
* manually deleting the statefulset will allow for an attempt at reinstall of grafana with PV, however still fails due to other resources conflicting with the install
* reinstall with correct info does not configure volume on longhorn, and has the same error as if the info was still incorrect/missing `Error: UPGRADE FAILED: timed out waiting for the condition` from the install logs and `0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.` in the `rancher-monitoring-grafana-0` pod

<img width="787" alt="Screen Shot 2021-04-02 at 12 53 20 PM" src="https://user-images.githubusercontent.com/16691014/113449347-80d77e00-93b2-11eb-894b-1daa9df922ab.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): V2.5-head (b2a34d7)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): linode (hosted)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 2 nodes, each 8 vCPU (1 all, 1 worker only)
- Kubernetes version (use `kubectl version`): v1.20

**Comment by aiyengar2** [comment]
@slickwarren thanks for filing this issue. However, I'm moving this off 2.5.8 to our backlog for the following reasons:
1) This is not a regression in the current chart.
2) A valid workaround exists, as mentioned in the issue description.
3) Rancher does not modify the logic for deploying PVs for Grafana (aside from allowing you to specify the options on the UI), so any fix that validates PV information on deployment should be added to the upstream Grafana Helm chart as well. 

If a fix is required, users are encouraged to submit a PR to upstream Grafana at https://github.com/grafana/helm-charts/tree/main/charts/grafana, at which point we can rebase on the latest upstream chart.

cc: @Jono-SUSE-Rancher @gaktive @SheilaghM

**Comment by aiyengar2** [comment]
cc: @sowmyav27 , I removed this from QA/S as well

**Comment by aiyengar2** [comment]
@slickwarren the fix for this will be done in two ways:
1. From the backend perspective, the Helm chart will be modified to prevent you from `leav[ing] one of the options blank for persistent volumes (i.e. size is left blank)`. The fields that should fail a helm install now are if size is left blank or if access modes are null or if access modes are empty list. However, even if you provide an invalid value, this validation will **not** be done by the backend.
2. I've followed this up with opening up a UI ticket in https://github.com/rancher/dashboard/issues/2994 that does the validation before allowing you to install. This should validate that you do not `enter incorrect information` and will also fix the Grafana PVC / StatefulSet options to set intelligent defaults for deploying that came from the original Helm chart.

What we need to validate at minimum when this fix is in is that:
1. Leaving the size empty (or default, without UI fixes) causes an error
2. Leaving the accessMode empty (or default, without UI fixes) causes an error
3. Editing the YAML directly for accessMode and leaving an empty list causes an error
4. Putting the defaults described in the UI ticket successfully deploy Grafana in the cluster.

It might also make sense to validate Prometheus's PV options as well (similar to what you did when you opened up this ticket) if UI values are disregarded. 

However, I don't think we need any further backend validation for Prometheus since the CRD already validates this on trying to do an install / upgrade (e.g. it will fail since the fields are required and don't match the regex in the Prometheus CRD spec).

**Comment by slickwarren** [comment]
blocked by https://github.com/rancher/rancher/issues/32657 (need to see logs when installing monitoring to verify this ticket)

**Comment by aiyengar2** [comment]
@slickwarren I created a backport issue to track testing this fix in 2.5 here: https://github.com/rancher/rancher/issues/33013

**Comment by slickwarren** [comment]
tested on master-head e756276:
for the following, I set the value to "", which does cause an error. Leaving the UI blank has a separate request below:
* Leaving the size empty (or default, without UI fixes) causes an error -- https://github.com/rancher/dashboard/issues/3333
* Leaving the accessMode empty (or default, without UI fixes) causes an error -- https://github.com/rancher/dashboard/issues/3333
* Editing the YAML directly for accessMode and leaving an empty list causes an error -- pass -- error is displayed to user on chart install for each of the following:
  * accessMode
  * Size
* Putting the defaults described in the UI ticket successfully deploy Grafana in the cluster. -- pass
* using incorrect/empty values can be upgraded to use correct values, where monitoring installs correctly -- pass
