### ISSUE TITLE
[CIS Benchmark] CRD chart for 1.0.400 is missing

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31920]
![Screen Shot 2021-04-05 at 12 01 03 PM](https://user-images.githubusercontent.com/13127443/113613828-99d86d00-9606-11eb-8835-97e046aecfdf.png)

We never updated the CRD chart version in https://github.com/rancher/charts/pull/1041.

Need to ensure that the CIS Benchmark chart is successfully deployable once this issue is resolved.

**Comment by kravciak** [comment]
The fix works fine. Tested with:
rancher: 2.5.7
chart: https://git.rancher.io/charts (dev-v2.5)
cluster: Google GKE (v1.18.16-gke.2100)

![Screenshot from 2021-04-06 10-09-51](https://user-images.githubusercontent.com/538604/113679923-9a353e80-96c0-11eb-8e73-c1ba5b4dd14a.png)

I also scheduled scan with gke-profile and cis-1.6-profile which executed successfully (with mixed results since cluster is not hardened)

**Comment by sowmyav27** [comment]
Reopening for a check on master-head in `dev-v2.6` feature charts branch

**Comment by kravciak** [comment]
Blocked on https://github.com/rancher/rancher/issues/31964

**Comment by sowmyav27** [comment]
Closing this, tracking master-head validation on another bug
