### ISSUE TITLE
[monitoring v2] instance reported to prometheus is using pod IP, should use node IP

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31953]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy monitoring v2 on a downstream cluster
* navigate to monitoring -> prometheus -> graph
* run a query i.e. `kube_daemonset_labels`

**Result:**
`instance` reports the pod IP, but the node IP is expected
<img width="563" alt="Screen Shot 2021-04-06 at 2 21 43 PM" src="https://user-images.githubusercontent.com/16691014/113781429-8a7c2100-96e5-11eb-8bf4-8d51a3e29271.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-head (93d921f)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Linode / Windows
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 12vCPU (3 nodes, 4vCPU each)

**Comment by aiyengar2** [comment]
For metrics that come from kube-state-metrics (e.g. `kube_daemonset_labels`), alertmanager, grafana, prometheus-operator, prometheus, ingress-nginx (note: pod IP == node IP for this since it's hostNetwork) and coredns, we expect the instance scraped from Prometheus to be the Pod's IP since that is the source from where the metrics are being scraped from. These should not change.

The ones that should have the instance be the node IP should be:
- kube-controller-manager (pushprox)
- kube-etcd (pushprox)
- kube-proxy (pushprox)
- kube-scheduler (pushprox)
- node-exporter
- apiserver
- kubelet
- windows-exporter

From my testing, the only one of these that did not have the correct IP is windows-exporter.

**Comment by slickwarren** [comment]
on monitoring v14.5.100-rc7 using v2.5.8-rc4 on a windows cluster, windows-exporter is now using the correct IP
example query: 
<img width="981" alt="Screen Shot 2021-04-15 at 9 03 52 AM" src="https://user-images.githubusercontent.com/16691014/114901331-8af17780-9dc9-11eb-904b-96120e7f77ad.png">
