### ISSUE TITLE
Private networking breaks down after a container is created

### ISSUE THREAD

**Issue by nlhkh** [rancher/rancher#3202]
I have been experiencing this issue in all machines I tried (Mac, Linux, Windows). When I provision some machines with Vagrant in Virtualbox, each machine can ping each other. I then install Rancher, and form a cluster. At this point, the machines can still ping each other. Then I created a service, and at soon as that service is started, it is deleted, and all the hosts are stuck in "Reconnecting" state. The machine can no longer pings each other. This does not happen when I work on DigitalOcean though.
Even though this is not a production use case, I think it is worthwhile to address this issue so that I can test my setup before bringing the setup to production.

**Comment by nlhkh** [comment]
I setup my VMs again with Ubuntu instead of RancherOS, and I don't have the same issue, so I think it is an issue with RancherOS itself. I am using version 0.41 from Vagrant.

**Comment by deniseschannon** [comment]
@nlhkh I'm going to close this issue as it's a RancherOS networking issue and this is the Rancher repo. If you have more specific steps that could be outlined about how RancherOS isn't working, then please open in rancher/os. Otherwise, I'm hoping by switching to Ubuntu, you are able to get Rancher up and running.
