### ISSUE TITLE
Disable Catalog V2 chart repository

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#32048]
Acceptance Criteria 

- Ability to disable/enable the Helm Repository in the UI.
- If disabled, the charts from the Helm repository should not be shown in the Apps&Marketplace UI.
- Installation/Upgradation/Deletion of the Chart should work as expected of already installed charts. 
- The only thing that is required is that the charts from that helm repository should not be displayed.

**BUG**

**Steps to reproduce (least amount of steps as possible):**
Go to Helm chart repo on Rancher 2.5.x in Cluster Explorer.
We cannot disable a chart, the only close option available is to delete it.

It was something doable in the previous Catalog version in the Cluster Manager

**Result:**
We need to delete a chart if we want to make it unavailable.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Rancher 2.5.x

**Comment by nicholasSUSE** [comment]
This is not a BUG

1st: Test, Document Old Feature of Enable/Disable Helm Repos:
https://jira.suse.com/browse/SURE-2884

Disable feature deletes catalog from kubernetes

Disables on UI and:

Keeps pods running
Does not show charts from the catalog (helm repo) anymore.
Deletes only the catalog (there was no clusterRepo at this version)
It seems it is already implemented, screenshot of filter in rancher Mapps UI
2nd:

Debug DELETE button, see what k8s resources it is affecting besides catalogs.
Verify if it is possible to completely delete the helm repos by the UI because it seems it is only possible to disable it.
3rd:
If going to implement:

Create official documentation on Confluence.
Test Deleting and recreating an entire ClusterRepo.?
Design Enabled/Disabled functionality?
ClusterRepo.Spec + ClusterRepo.Status?
ClusterRepo.Annotations?
Lock somehow the configmap?
Reset Rancher cache for ClusterRepo and ConfigMap at content?

**Comment by nicholasSUSE** [comment]
Not Possible to completely remove the helm repos by the UI, it will always be available for making enabled withing the global scope:

image.png
image.png
image.png

Labels
team/mapps
Sprint
No Sprint
Epic
No Epic
Assignees
nicholasSUSE Nicholas openSUSE Software Engineer
Add card to a source
  
Create a duplicate Card
 Subscribe

**Comment by nicholasSUSE** [comment]
We have discovered how to reproduce the same old functionality with RBAC.
I have documented this process at:
https://confluence.suse.com/pages/viewpage.action?pageId=1333068416
