### ISSUE TITLE
Access control cache sees issue when adding namespaces

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32045]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Spin a rancher on version 2.4.15
2. Create users u1 and u2 as standard users
3. Create a cluster with 3worker, 1etcd and 1 cp
4. Add a project as admin and add u2 as Project Owner and Project member
5. Upgrade the cluster to the latest v2.5.8-rc2
6. Once the server is active, create a namespace logged in as u2
7. Namespace is stuck in activating
8. Create another namespace and the ns is stuck in activating too. 
9. If we refresh the page, the namespace in step7 appears but namespace in step 8 disappears.

**Result:**
All the created namespaces should appear in the project

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
Before upgrade: v2.4.15
After upgrade: v2.5.8-rc2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure provider digital ocean

**Other details that may be helpful:**
Screen recording for the same:

https://user-images.githubusercontent.com/38144301/114331821-bc342400-9af9-11eb-8039-f5bf9c6ced3b.mov

This is not seen on a fresh install of 2.5-head,2.5.7 and not happening always.. 
Also, if we upgrade from 2.4.15 to 2.5-head -- issue is not seen

**Comment by anupama2501** [comment]
@ryansann This is also seen on v2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head

1. Create two users u1 as Admin/restricted admin and u2 as standard user
2. Create a cluster logged in as u2 and add a project to u1 to this project with custom roles -- only enable create namespaces
3. Now login as u1 and verify, he has access to all the projects
4. Change the user u1 from admin to standard user logged in as local cluster admin
5. Log in as u1 and create a namespace. We can see the same issue happening 
6. If I verify the namespaces created from kubectl, I see all the created namespaces:

```
ns1               Active   8m55s
ns2               Active   8m45s
ns3               Active   8m31s
ns4               Active   6m13s
ns5               Active   6m2s
ns6               Active   35s
```

If we log out and log in as u1, we can then see all the namespaces

**Comment by anupama2501** [comment]
@ryansann I'm not seeing it on v2.5.7. 
When I upgrade from 2.4.15 --> 2.5-head and 2.5.7 --> 2.5-head, I see this happen. Logged in as a ProjectMember --> create a namespace [See this happen]

**Comment by ryansann** [comment]
I've done the following:
1. Upgrade from v2.5.7 to 2.5-head to reproduce issue, gather RBAC resources in management cluster
2. Run v2.5.7, don't see the issue, gather RBAC resources in management cluster

The resources are identical in both scenarios, except, when gathering the resources from the upgraded cluster, there is no duplicate cluster-membership binding seen. This does happen in the v2.5.7 cluster because we are adding user as project-owner and project-member at the same time.  Seeing no duplicate in the upgraded cluster is expected based on the changes made to RoleBinding and ClusterRoleBinding naming. 

I will take a look at downstream cluster to see if there are any issues that stick out to me there.

**Comment by ryansann** [comment]
Having investigated downstream clusters, I also don't see any significant differences in the RBAC resources between the two scenarios. There are duplicates in the v2.5.7 cluster that don't appear in the upgraded cluster.

**Comment by ryansann** [comment]
Minimum reproduction steps:

- Fresh install of Rancher v2.5.7
- Add user `u1` as Standard User
- Create project `p1` in **local cluster** with `u1` as Member
- Upgrade to 2.5-head
- Login as u1
- Add namespace to `p1`, observe issue

**Comment by ryansann** [comment]
Actually, you need not upgrade from v2.5.7, this is seen if, instead of upgrading, you restart Rancher.

**Comment by ChrisHaPunkt** [comment]
related to https://github.com/rancher/rancher/issues/20549 ?

**Comment by justcloudnative** [comment]
We, have the same problem

**Comment by ChrisHaPunkt** [comment]
I hope we do not have to wait till 2.6 to have this issue resolved. Our Users are not reliably able to create their self-managed Namespaces any more.

**Comment by ryansann** [comment]
This issue is being caused by some API access control caching issues. Disabling caching for access control here: https://github.com/rancher/rancher/blob/master/pkg/rbac/access_control.go#L12 (true -> false), causes the issue not to happen. I am investigating what's going wrong with the cache and should have a fix for this soon

**Comment by ryansann** [comment]
More details on the caching issue. When we see a namespace stuck in `Activating` the user has the following cache key in the access control cache: `8c5033791bed7d14b2a2684d4bce33f97cb5d457ebaf3bc900a1adb368422b4e`. This value associated to this cache key is the user's access set. I've implemented some deterministic hashing of the access set to get a better idea of equality. That logic can be found [here](https://github.com/ryansann/steve/blob/fd9770cf3322ab910cf651eea4f83df3501ba681/pkg/accesscontrol/access_store.go#L89). 

The hash of the user's access set when they are experiencing the issue is: `4461fff991484cc861854ba4bd2073c2b3701dee8b9805e5719d039f22312db3`. 

After a restart, namespaces return to normal and the user's access set has a different hash, namely: `5b1405440809e96dfb48d0d71f217a64b259854766380e55f2434ffbe2ec5d3a`. 

Assuming correctness of the deterministic hashing logic, this implies that the user has a different access set after restart, but the same cache key. I have not found the root cause of this issue yet.

**Comment by ryansann** [comment]
#35172 Looks to have fixed this issue, I will move it to test so QA can also validate

**Comment by anupama2501** [comment]
Verified on v2.5-head `f5cf749`

Docker install upgrade from 2.5.10 --> 2.5-head f5cf749
1. Created two standard users from global --> users
2. Added a user - user1 to the local cluster as PM 
3. restarted the rancher server and verified the issue was reproduced
4. Upgraded rancher to v2.5-head 
5. Created a downstream cluster and added the user user1 as the PM 
6. Restarted the rancher server
7. Logged in as user1 and verified the user was able to create namespaces and all the namespaces were seen active
8. Restarted the rancher server and verified user1 was able to create namespaces and deploy workload in all the namespaces.

verified the same steps on an HA fresh install 2.5-head `f5cf749`  and the user can create namespaces and deploy workloads in all of the created namespaces
