### ISSUE TITLE
GKEv2 UI, shows old k8s version on Edit Cluster page when registering an existing GKE v2 cluster

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32059]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a GKE cluster on GCP with k8s version = 1.17.7
2. Resister an existing the GKE cluster on  Rancher
3. Upgrade GKE cluster version on GCP to 1.18.15-gke.1501
4. Check cluster api for the update to 1.18.15-gke.1501 in `upstreamSpec`
5.  Go to edit cluster, you will still see a `check mark` on `1.17.7`, instead of `1.18.15-gke.1501`

<img width="1380" alt="Screen Shot 2021-04-12 at 11 54 21 AM" src="https://user-images.githubusercontent.com/3749546/114446212-d582b200-9b85-11eb-9090-4ed75d3be877.png">

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-6f71d4c7346c63a60c671d59185e1595fe826ac7-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cmurphy** [comment]
I don't think this has to do with upgrading the version, I think the default in the UI is just statically set to `1.17.17-gke.2800` since that's the default when creating new clusters. @westlywright is the edit screen supposed to pull values from the current cluster state?

There will be a slight delay of up to 5 minutes between when the cluster finishes updating in GKE and when it appears on the `upstreamSpec` object in Rancher, but that's an unavoidable part of the design. I double checked that it does update `upstreamSpec` after a minute or two.

**Comment by prabalsharma** [comment]
yes, it has nothing to do with upgrading the cluster. I will update the steps to repro...

**Comment by westlywright** [comment]
We should be respecting that but editing was flaky last week for me so I didn't get to test edit it a ton. Its probably a UI bug.

**Comment by sowmyav27** [comment]
On a hosted GKEv2 cluster, I do not see this issue.

**Comment by prabalsharma** [comment]
Passed: v2.5-4e70ed29ccc5de7c61516ba0367c7c4904989b56-head
