### ISSUE TITLE
GKEv2 UI should allow to select Node Pool's k8s version

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32102]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Rancher v2.5-6f71d4c7346c63a60c671d59185e1595fe826ac7-head
2. Create a GKE cluster
3. Cannot select NP's version
<img width="604" alt="Screen Shot 2021-04-13 at 12 04 17 PM" src="https://user-images.githubusercontent.com/3749546/114606654-61f9a700-9c50-11eb-9f54-febb7ee30f10.png">

**Result:**

**Other details that may be helpful:**
GKE allows user to select "NP's version" equal to or less than "CP's k8s version", if the user has selected `Static version` for CP.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
I can see the argument to match the GKE UI here but I don't think we should. Our EKS provisioner does not allow the user to select a node Kubernetes version because there are not many use cases for it and it general it causes more problems then it solves. I think we should follow our EKS UX here and only allow users to change the version on the node pool when the cluster version is different, and then it only changes it to the same version as the cluster. If there is a dire need to use a different version on the node pool the API UI could be used to edit the node pool.

**Comment by prabalsharma** [comment]
Caleb, please close this, if you agree as well ^^. IMO, this is ok ^^.

**Comment by cbron** [comment]
Agree with Wes, it should ideally all be the same so we should drive users towards that pattern.
