### ISSUE TITLE
[Monitoring V2] Remove pre-install job in favor of Helm annotations

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#32113]
Need to use the approach provided in https://github.com/rancher/charts/pull/1085#discussion_r612018643 to avoid having a job that creates the Alertmanager Secret.

~This issue should also address https://github.com/rancher/rancher/issues/31849 since the approach provided above would make it trivial to make the Prometheus Adapter secret an install-only secret.~ Leaving as a separate issue.

**Comment by sowmyav27** [comment]
To validate:
- a job should no longer be required to install the initial secret for Alertmanager. If it exists before install , nothing should fail. If it does not exist before install, it should be created with the default on the values.yaml. On an upgrade, it should not be modified
- We should also no longer see the image rancher/agent in use by monitoring v2

**Comment by cbron** [comment]
Assigning to @jiaqiluo for dev-validate

**Comment by jiaqiluo** [comment]
the fix is validated in rancher v2.6-head e3316c9 with Monitoring v2 chart `100.0.0+up16.6.0`

The following 2 cases are tested:
- fresh install of monitoring v2 `100.0.0+up16.6.0` into a downstream RKE cluster 
- upgrade monitoring v2 from `14.5.100` to `100.0.0+up16.6.0`

Results:
- both fresh install and upgrade succeeds
- no job for creating the initial secret
- the `rancher/agent` image is not used anymore

**Comment by jiaqiluo** [comment]
@sowmyav27  Please review and close the issue
