### ISSUE TITLE
Global/restricted admin unable to create an EKS cluster in hosted Rancher tenant

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#32149]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher and use helm option "restrictedAdmin" = "true"
2. Create a new EKS cluster - enter AWS creds with permissions to create EKS cluster, can mostly use default options. Click Create.

**Result:**
Cluster fails to provision with error: "Failed to deploy eks-operator: can't find system project "
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/468462/114798450-3824ab00-9d4a-11eb-971a-88b4814ef9b6.png">

**Other details that may be helpful:**
This appears to be a regression. EKS provisioning was failing in a v2.5.0 alpha, but was fixed in the final v2.5.0 release. See https://github.com/rancher/rancher/issues/28764 . Seems to have broke sometime between v2.5.0 and v2.5.7

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.7
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
K3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
2 AWS m5a.large VMs (2vpu 8gb ram)
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+k3s1", GitCommit:"355fff3017b06cde44dbd879408a3a6826fa7125", GitTreeState:"clean", BuildDate:"2021-03-31T06:21:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
NA, contained

gz#16465

gz#17477

**Comment by thedadams** [comment]
@dnoland1 Are you getting a bunch of "cannot find system project" errors on these clusters in other situations?

**Comment by dnoland1** [comment]
@thedadams Not that I'm aware of.

**Comment by aaronRancher** [comment]
This issue is reproduced on Rancher `v2.5.7` with the following steps:
- Bring up a hosted Rancher setup with helm option "restrictedAdmin" = "true" on tenant cluster.
- Log into tenant cluster Rancher.
- Create a new EKS cluster - enter AWS creds with permissions to create EKS cluster, can mostly use default options. Click Create.

Result:
Cluster fails to provision with error: `Failed to deploy eks-operator: can't find system project`

The fix is validated on Rancher `master-head` `version 500de20` with the above steps.
The EKSv2 cluster is available in Rancher UI and EKS console.
EKS operator version: `v1.0.10-rc1`
![Screen Shot 2021-07-28 at 6 06 21 PM](https://user-images.githubusercontent.com/57409052/127416494-7594e283-e79e-45cc-b083-27fee9f211c1.png)
