### ISSUE TITLE
Switching from self-signed certificates to Let's Encrypt

### ISSUE THREAD

**Issue by sr258** [rancher/rancher#32206]
I installed Rancher 2.5 with Option A from https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/ onto a single node.

I now want to move from self-signed certificates to Let's Encrypt certificates without re-installing Rancher. I can't find any instructions how to do that. Can someone help out?

**Comment by shimondoodkin** [comment]
me too

**Comment by MiningPickaxe** [comment]
me too :)

**Comment by shimondoodkin** [comment]
below are hints 
not directions.
i have been able to solve it with some struggle by deleting secrets and trying to reinstall. but then some things did not work. maybe purge is better.

https://docs.ranchermanager.rancher.io/v2.5/getting-started/installation-and-upgrade/resources/update-rancher-certificate
https://benyoung.blog/deploying-rancher-to-manage-a-kubernetes-cluster/
https://support.tools/post/how-to-change-rancher-2.x-server-cert/

i think it is boils down to uninstall rancher helm
and install with letsEncrypt 

my command was 

(i installed it from folder)
cd ~/rancher
helm upgrade rancher .  --namespace cattle-system  --create-namespace  --set hostname=s4.asdfasdf.com  --set replicas=1  --set bootstrapPassword=asdfasdf--set ingress.tls.source=letsEncrypt --set letsEncrypt.email=asdfasdf@gmail.com

i think i used uninstall first then, install again instead of upgrade

maybe use
helm delete <deployment name> --purge

**Comment by Mr-MooMoo** [comment]
What worked for me (Rancher 2.7.3),

`helm _upgrade_ rancher [same options you had on first install] --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=your@email.com`

then run

`- kubectl cert-manager renew -A --all             #to renew ALL certificates`
