### ISSUE TITLE
ISTIO kiali graph for egress gateway are not displayed when workloads are created from dashboard

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32286]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug
ISTIO: 1.8.300-rc01, 1.8.500-rc01
Monitoring: 14.5.100-rc07

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster with 3 worker,1 etcd, 1 cp
2. Install v2 monitoring and v2 istio with egress-gateway enabled from the components 
3. From cluster explorer --> namespaces --> Create a namespace with istio-injection enabled and select project default
4. Apply the egress testyaml in the namespace created above. Deploy a workload in the same namespace and generate traffic by executing in the pod.
5. From kiali --> graph --> select the namespace created in step4 and no traffic is seen on kiali
6. If we create a namespace in the ember UI by enabling istio-injection in the default project. Apply egress testyaml in this namespace and deploy a workload in this namespace  and generate traffic by executing into the pod,  kiali displays generated traffic in this namespace.

**Result:**
Traffic is not updated on kiali if the workload is created from dashboard and should've been displayed.

**Other details that may be helpful:**

If the workload is deployed from ember UI in the namespace created in dashboard, the issue is not seen

**Dashboard workload:**
<img width="200" alt="Screen Shot 2021-04-21 at 10 37 32 PM" src="https://user-images.githubusercontent.com/38144301/115661546-70039380-a2f2-11eb-9df0-5fd399e28970.png">
**ember UI workload:**
<img width="200" alt="Screen Shot 2021-04-21 at 1 22 11 PM" src="https://user-images.githubusercontent.com/38144301/115661769-d7214800-a2f2-11eb-831a-2c58fe680df1.png">
d:

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc6
- Installation option (single install/HA): Single

**Comment by brendarearden** [comment]
@anupama2501 After doing some additional trouble shooting, I believe this is just a difference in what Kiali chooses to display now, along with the what the work load you deployed looks like 

Here is what I did to see the same information: 

1. create a namespace (I put it in the default project) and enabled istio auto injection
2. create the sample deployment from the istio engress steps by copy-pasting the following `sleep.yaml` into the yaml upload and select the namespace you created. https://raw.githubusercontent.com/istio/istio/release-1.9/samples/sleep/sleep.yaml  
3. Use the egress.yaml deployment that contains the service entry, gateway, destination rule, and virtual service and upload through the yaml import into the cluster you created. If you are not sure which resources, https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-http-traffic follow these steps. 
4. use `kubectl exec sleep-557747455f-4zdw6 -c sleep -n <your namespace> -- curl -sSL -o /dev/null -D - http://edition.cnn.com/politics` (update with your pod name) to check that the services are working from the ui kube shell or you can call `curl -sL -o /dev/null -D - http://edition.cnn.com/politics` from the pods exec shell. 
5. At this point if you have hit the service a few times, you should see the following graph in kiali with the namespace you created along with the istio-system namespace selected (you may need to change your timeframe if its been a while or curl the service a few more times)
![Screen Shot 2021-04-23 at 9 36 35 PM](https://user-images.githubusercontent.com/19455540/115947407-45454680-a47c-11eb-8501-2cdff970b428.png)
6. This looks like the graph you are seeing in the ember ui. 
7. Creating another deployment workload from the ui using the `ranchertest/mytestcontainer` image, add  label and pod labels for `app: mytest` 
Note: One difference between this deployment and the deployment from step 2 is there is no service associated with it
8. use `kubectl exec <newly created pod> -n <your namespace> -- curl -sSL -o /dev/null -D - http://edition.cnn.com/politics` (update with your pod name) to check that the services are working from the ui kube shell or you can call `curl -sL -o /dev/null -D - http://edition.cnn.com/politics` from the pods exec shell. 
9. And then go to kiali and you should see the traffic from the egress to cnn. This make sense because there is only the pod and you are making a call directly from that pod to cnn - there are not additional services to be listed in the graph. 
![Screen Shot 2021-04-23 at 9 46 41 PM](https://user-images.githubusercontent.com/19455540/115947578-796d3700-a47d-11eb-82ee-106605602341.png)

**Comment by anupama2501** [comment]
@brendarearden 
I followed these steps to reproduce the issue:


1. spinup rancher server `v2.5.8-rc9` and enable istio `1.9.300` with egress-gateway enabled
2. Create a namespace `testns-egress` from cluster explorer --> namespaces with istio-injection enabled in the labels
3. Run kubectl in the namespace created above  ` kubectl apply -n testns-egress -f egressgateway.yaml `
4. From cluster explorer --> workload overview --> create -> deployment --> select namespace `testns-egress ` and container image 
5. once the pod is active, execute shell and run the command multiple times `curl -sL -o /dev/null -D - http://edition.cnn.com/politics`
6. If we go to kiali and select this namespace, we see the graph as follows:

<img width="400" alt="Screen Shot 2021-04-26 at 4 58 12 PM" src="https://user-images.githubusercontent.com/38144301/116168735-f97ee100-a6b7-11eb-9034-279983f4cdc7.png">

7.  Now create a workload from ember UI --> cluster --> default project where namespace is present --> workloads --> create a workload with the the image used from the above step and namespace as egressgateway.yaml . Once the pod is active, execute shell and run the same command `curl -sL -o /dev/null -D - http://edition.cnn.com/politics`
8. Verify the graph on kiali and it is as seen as follows:


<img width="400" alt="Screen Shot 2021-04-26 at 4 59 23 PM" src="https://user-images.githubusercontent.com/38144301/116168784-174c4600-a6b8-11eb-8780-2fad9bc3b17e.png">

**Comment by brendarearden** [comment]
I went ahead and changed the kiali image version from v1.32.0 to v1.29.0 from the deployment just to confirm its not the kiali version and the graph did stay the same so we can rule that out.  What I see happening is when you create the workload in the dashboard ui, a service does not get created but when you create the workload through the ember ui, a service does get created. Without that service, Istio is not able to generate the expected telemetry to for kiali to pick up to display in the graph. I am not sure if there are particular steps we are missing in the dashboard when it comes to deploying workloads but that missing service is our culprit for this issue.

**Comment by anupama2501** [comment]
Verified on 2.5.8-rc10

1. On cluster with 3etcd, 1 cp, 3 worker - install monitoring and istio with egress gateway enabled. 
2. Create a namespace from explorer --> namespaces with istio auto injection enabled
3. run the kubectl in the namespace created above kubectl apply -n testns-egress -f egressgateway.yaml and deploy a workload from explorer --> workload overview --> deployment and select service type cluster IP --> create
4. Once the workload is active run the curl command and verify graphs from kiali

<img width="300" alt="Screen Shot 2021-04-27 at 3 40 53 PM" src="https://user-images.githubusercontent.com/38144301/116321466-f85cbb00-a76e-11eb-9e62-da9b685042a5.png">
