### ISSUE TITLE
Enable "Auto upgrade" and "Auto repair" for imported GKE by default and add documentation

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32282]
From this comment, https://github.com/rancher/rancher/issues/32196#issuecomment-821539838, the user can easily encounter an error (`Googleapi: Error 400: Auto_upgrade and auto_repair cannot be false when release_channel REGULAR is set., badRequest`) if "Auto upgrade" and "Auto repair" are not enabled when creating a new node pool or when editing an existing node pool.
"Auto upgrade" and "Auto repair" should be selected by default when creating a new node pool for an imported GKE cluster. 
We also should have some form of documentation to tell the user why this is needed.

**Comment by westlywright** [comment]
I think there is some confusion here. We can't set Auto Upgrade and Auto Repair true for an imported cluster because at the time of creation all the UI passes to the API is the cluster name and cloud creds, nothing really to do with the actual GKE config or node pool configs. What I think we are aiming for here is updating the default node pool config in the UI to have these two fields enabled regardless of type, which I already updated [here](https://github.com/rancher/ui/pull/4560/commits/137d901ef63a240833f31cd5498456734a948e88).

Regarding auto editing these two fields for an imported cluster when the user edits, we should not do this. Going forward new nodes added during edit will have the two fields true by default. In the GKE console those fields are also enabled by default and if you choose `Release Channel` you can not disable them at all. I think changing the defaults in the UI and adding documentation is a good path forward and will cover most common cases.

@cmurphy @cbron Thoughts? 


Additionally, I am starting to think that post 2.5.8, the UI should be updated to work with the Release vs Static version channels. Not sure how much work that will be though or if we should make that a requirement of the Vue UX when we build the provisioning UI's in that project. I lean towards that option.

**Comment by cbron** [comment]
Sounds like the right path to take. That being said, its not entirely clear to me if that UI fix will have fixed the UX problem Aaron was running into when importing clusters on regular channel.

**Comment by westlywright** [comment]
@cbron On edit I can check to see if the cluster is imported and if the existing node pools don't have these options checked I can display a warning that these fields should be set true or face the consequences.

**Comment by westlywright** [comment]
Ive added the logic to display a warning in the case that we have an imported cluster (gkeConfig.imported = true) and the node pool does not have Auto Upgrade or Auto Repair enabled. This warning will also show if you add a new pool and disable those fields. New clusters created from Rancher UI will not show this as they are technically in the static release channel and disabling the fields is acceptable in that case.

**Comment by aaronRancher** [comment]
This issue is validated on Rancher `v2.5-head` `version 124e7af`:

A warning is displayed on an imported cluster when `Auto upgrade` and/or `Auto repair` are not selected in a node pool:
![Screen Shot 2021-04-26 at 4 26 41 PM](https://user-images.githubusercontent.com/57409052/116163336-6be9c400-a6ac-11eb-9485-08806e6c834a.png)
