### ISSUE TITLE
[GKE] Cannot get out of error when cluster is provisioned with the same name

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32292]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher `v2.5.8-rc8` provision a GKE cluster with the name "cluster1".
After the cluster becomes active, provision another GKE cluster with the name "cluster1" in Rancher.
The cluster provisioning will fail with: `Cannot create cluster [cluster1] because a cluster in GKE exists with the same name`. This is expected.
Try to get out of the error by editing the second cluster and changing the name ("cluster2").
Save cluster.

**Result:**
The cluster will remain unprovisioned with an error: `Cannot create cluster [cluster1] because a cluster in GKE exists with the same name`

**Other details that may be helpful:**
On cluster save, the UI sends a request with the edited cluster name ("cluster2")

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.8-rc8`
- Installation option (single install/HA): single install

**Comment by cmurphy** [comment]
@westlywright is validating that the cluster name is unique something that could be handled in the UI? It could use the /meta/gkeClusters proxy that we already have.

**Comment by westlywright** [comment]
@cmurphy This is definitely possible via the UI but will leave out API users which I feel would leave us in the same boat.

**Comment by cmurphy** [comment]
@aaronRancher after discussion with other devs I think this is working as expected, and it works the same way in EKS. You have to delete and recreate the cluster. I double-checked on my end that deleting the cluster from Rancher doesn't delete the same-named cluster in GKE, can you verify as well? I will also change the error message to explain that the cluster needs to be deleted and recreated. Would this work for now?

@westlywright there's not really a good way to handle it in the backend so I think it would be okay to just address it in the UI and let API users handle it the hard way. But since this is working the same way for EKS, maybe we can push it off past 2.5.8?

**Comment by westlywright** [comment]
@cmurphy If it works this way for EKS then I would agree if it is acceptable, lets push it to >2.5.8 so we dont risk intro'ing new bugs and sliding.

**Comment by aaronRancher** [comment]
@cmurphy Yes. Deleting the same-named cluster in error state does not delete the original cluster. An error message explaining the cluster needs to be recreated will work.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 124e7af`
GKE operator version: `gke-operator:v1.0.1-rc10`

The error message explains the cluster has to be deleted and recreated:
![Screen Shot 2021-04-26 at 4 35 23 PM](https://user-images.githubusercontent.com/57409052/116274474-8f0d8580-a737-11eb-91e9-21964e5122f4.png)
