### ISSUE TITLE
RKE2 Provisioning - Node Options

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32361]
Ability to add taints and labels to nodes through Node Provisioned clusters and Custom clusters

Available to test through yaml creation

**Comment by deniseschannon** [comment]
Node Pools:

```
nodePools:
#      - cloudCredentialSecretName: string
#        controlPlaneRole: boolean
#        displayName: string
#        etcdRole: boolean
#        hostnamePrefix: string
#        labels:
#          key: string
#        name: string
#        nodeConfig:
#          apiVersion: string
#          fieldPath: string
#          kind: string
#          name: string
#          namespace: string
#          resourceVersion: string
#          uid: string
#        paused: boolean
#        quantity: int
#        rollingUpdate:
#          maxSurge: string
#          maxUnavailable: string
#        taints:
#          - effect: string
#            key: string
#            timeAdded: string
#            value: string
#        workerRole: boolean
```

**Comment by ShylajaDevadiga** [comment]
Taints flag is not available issue https://github.com/rancher/rancher/issues/32695

**Comment by ShylajaDevadiga** [comment]
**Applying taints:**

**Custom Cluster:**
AWS and DO
Taints have invalid format in config file https://github.com/rancher/rancher/issues/33419

**Node Driver:**
AWS
Blocked on node creation issue https://github.com/rancher/rancher/issues/32785
DO
Pass

**Comment by ShylajaDevadiga** [comment]
Update on applying taints using master-head commit id: 3e44415

AWS Custom Cluster: Taints have invalid format in config file #33419 
DO Node Driver: Taints have invalid format in config file #33419 

AWS Node Driver: Blocked on node creation  #32785
DO Custom Cluster: Blocked on node creation

**Comment by ShylajaDevadiga** [comment]
Confirming DO Custom Cluster works as expected. It failed in my previous test due to limited resources.

**Comment by davidnuzik** [comment]
**Reproduction:**
Not required.

**Validation Successful:**
Rancher version: v2.6-head `7b9a232ac` 8/6/21 2:12pm Pacific
Rancher cluster type: single-node rancher in docker container
Docker version: 19.03

Downstream cluster type: rke2 (test both rke2 cluster provisioned by rancher [node driver] and rke2 custom cluster)
Downstream K8s version: v1.21.3-rc4+rke2r2

Validation steps:
_Use Case 1 - RKE2 Provisioned by rancher (node driver):_
1. Create an RKE2 cluster in Rancher, I used the DigitalOcean provider. Observed the ability to add node lables and taints in the UI:
![image](https://user-images.githubusercontent.com/45179589/128577001-1cc3cb23-3c62-4674-8382-0f9ea03a4776.png)

2. Test by creating a couple of labels and and taints. I created a pool with just some labels and a worker pool with all types of taints (because this may cause issues with provisioning etcd/cp nodes)
![image](https://user-images.githubusercontent.com/45179589/128577234-777cdfbc-cc7d-4231-8b36-34004f7c6fa9.png)

3. Ensured that the json body in the POST request payload to create the cluster was as expected:

```
{
	"machinePools": [
		{
			"controlPlaneRole": true,
			"etcdRole": true,
			"hostnamePrefix": "dave-rke2-taints-1-pool1-",
			"labels": {
				"apples": "drool",
				"tacos": "rule"
			},
			"machineConfigRef": {
				"kind": "DigitaloceanConfig",
				"name": "nc-dave-rke2-taints-1-pool1-hb6g4"
			},
			"name": "pool1",
			"quantity": 1,
			"taints": [],
			"workerRole": true
		},
		{
			"controlPlaneRole": false,
			"etcdRole": false,
			"hostnamePrefix": "dave-rke2-taints-1-taintedworker-",
			"labels": {
				"brocolli": "drools",
				"tacos": "rule"
			},
			"machineConfigRef": {
				"kind": "DigitaloceanConfig",
				"name": "nc-dave-rke2-taints-1-taintedworker-cgdmp"
			},
			"name": "taintedworker",
			"quantity": 1,
			"taints": [
				{
					"effect": "NoSchedule",
					"key": "tainted",
					"value": "love"
				},
				{
					"effect": "PreferNoSchedule",
					"key": "taint2",
					"value": "hi"
				},
				{
					"effect": "NoExecute",
					"key": "taint3",
					"value": "yo"
				}
			],
			"workerRole": true
		}
	]
}
```

4. Ensured the cluster came up and in the UI I can see the labels/taints when viewing the nodes.
![image](https://user-images.githubusercontent.com/45179589/128577641-aad9135a-24d2-45ec-9bb1-4a1c3eb9a099.png)
![image](https://user-images.githubusercontent.com/45179589/128577653-0590e71f-861e-4d15-b5bb-95ea5d83c490.png)
![image](https://user-images.githubusercontent.com/45179589/128577667-91cadf32-4983-409d-8021-60ef638cf72d.png)

5. Queried the nodes in kubectl shell and ensured the labels and taints show there as well.
![image](https://user-images.githubusercontent.com/45179589/128577735-145397ca-b3ec-4d2c-8077-49e18e09c441.png)
![image](https://user-images.githubusercontent.com/45179589/128577745-62daca13-4fa8-49ec-9205-ad564544e272.png)

_Use Case 2 - RKE2 custom cluster:_
_Performed the same steps as above in Use Case 1, but with a custom RKE2 cluster instead. Same result (all checks pass)._

NOTE: The process / UI flow for rke2 custom clusters is slightly different. You set node labels and taints on the 2nd screen. Under "Step 1" in the UI on this 2nd page, click the "Show Advanced" link there to see the node taints/labels option :)
