### ISSUE TITLE
Conditional support in Catalogue templates

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3239]
It would be useful if Catalogue templates were able to have condition if/then/else constructs to test user responses and enable/disable sections of the template.  

Currently, templates can only substitute for ${varname}, but there is so much more that should be possible.

This would allow Catalogue items to generate more complex stacks, even enabling and disabling whole services as required.  This would allow a boolean "Use SSL?" option that caused the underlying template to add or remove the whole SSL-offload section in the Load Balancer.

Conditional tests should allow testing of booleans, numerical >/</=, and text comparisons =/!= on or between variables.  A regexp text comparison ~ might also be beneficial.

A more simple example:

```
Minecraft:
  environment:
    EULA: ${EULA}
#IF ${MODE} ~ /survival|creative|adventure/
    MODE: ${MODE}
#ELSE
    MODE: survival
#END
    WHITELIST: ${WHITELIST}
    OPS: ${OPS}
#IF ${SEED} != ""
    SEED: ${SEED}
#ELSE
    WORLD: ${WORLD}
#END
  tty: true
  image: itzg/minecraft-server:latest
  stdin_open: true
```

You could even go as far as to use something like TT2 format, with calculations and variable definition allowed, though that might be a bit complex.

**Comment by vincent99** [comment]
-(∞+1) inventing new template language

+1 adding optional support for an existing one (likely https://golang.org/pkg/text/template/ since rancher-compose and libcompose are Go).  In a way that is backwards compatible, like a comment on the first line to indicate the template type.

@cloudnautique This would conveniently solve your issue with `net:managed` vs `net:ugly string`...

**Comment by sshipway** [comment]
@vincent99 - the important things to me would be (a) ability to do conditionals, and (b) backwards compatibility with the current `${varname}` format.  How it is achieved (Go templates, TT2, or `\#if`) I don't really care, though there are obvious benefits to going with an established templating system in the application language.  However, would this mean losing backwards compatibilty with `${varname}` since Go templates appear to use `{{.varname}}``?

**Comment by vincent99** [comment]
It would have to be conditional to be backwards compatible, e.g. to use Go template the file has to start with say `#text/template`, otherwise it's treated as existing.

Presumably we would only document the new `{{.style}}` and eventually deprecate/remove the `${existing}` style, since it would have no benefit and the transition is minimal.

**Comment by sshipway** [comment]
I'm all in favour of this way of achieving the result, then.

The reason this came up is that I'm working on a number of Catalogue items for use here, including a managed registry.  I've hit a snag in that there is (currently) no way to have a 'with SSL' switch as the differences in the require YAML are too great to do with ${varname}.  

In our situation (university, many researchers) we are likely to be creating many, many new stacks of small size on a regular basis (as opposed to e.g. a business where they have very few stacks but they have a very big scale).  So, it is in our interest to ensure that researchers stick to a standard way of creating (e.g.) a MariaDB stack when they need one.  For this, a local Catalogue is perfect, but it needs to be able to support a lot of flexibility.   As a result, I'm posting this feature request.  

On a related note, it would be useful to have an online document somewhere with instructions, best practice and examples on creating Catalogue items, particularly on the best practice way to use sidekicks, mount shared filesystems, use labels, and so on.  This is probably not high priority at the moment though as 1.0 draws nearer :)

**Comment by c0deaddict** [comment]
+1

**Comment by joshwget** [comment]
Templating is present in v1.5.0-rc1, but only via executor (launching catalog items and stacks via the UI). Docs available at https://github.com/rancher/rancher.github.io/pull/683.

**Comment by sangeethah** [comment]
Tested with build from master:

K8s compose file uses conditional logic in docker-compose.yml  ( https://github.com/rancher/rancher-catalog/blob/v1.5.0-dev/infra-templates/k8s/19/docker-compose.yml ) to decide on using soft vs hard affinity for host label requirements (for deploying etcd/orchestration/user pods containers )depending on the  the value of ``CONSTRAINT_TYPE`` which is a question presented to the user when deploying K8s environment.

```
    labels:
        io.rancher.scheduler.affinity:host_label{{ if eq .Values.CONSTRAINT_TYPE "best-effort" }}_soft{{ end }}: etcd=true
```

When "Plane Isolation" is set to "best-effort" , we get the ``io.rancher.scheduler.affinity:host_label_soft`` (soft affinity) for etcd and orchestration planes.

When "Plane Isolation" is set to "best-effort" , we get the ``io.rancher.scheduler.affinity:host_label`` (hard affinity) for etcd and orchestration planes.

**Comment by sangeethah** [comment]
@joshwget , reopening this issue to provide support for conditional logic from rancher cli .

**Comment by joshwget** [comment]
@sangeethah Templating is available in v0.4.1.

**Comment by joshwget** [comment]
@sangeethah CLI v0.5.0-rc1 contains templating.

**Comment by sangeethah** [comment]
@josh , with v1.5.0-rc2 version , K8s stacks that uses conditional logic in docker-compose.yml is not able to start successfully.

**Comment by sangeethah** [comment]
Tested with v1.5.0-rc3 version and rancher cli version - v0.5.0-rc1

Able to use docker-compose file with conditional supports for variables.

When creating a service with this docker-compose yml , with PORT value being set to "standard" service gets created with port as 8000:80.
When creating a service with this docker-compose yml , with PORT value being set to "nonstandard" service gets created with port as 8000:81.

```
version: '2'
services:
  web:
    image: sangeetha/testnewhostrouting
    {{- if eq .Values.PORT "standard" }}
    ports:
    - 8000:80
    {{- else }}
    ports:
    - 8000:81
    {{- end }}
```

Related issue with variables used in templating not being defined - https://github.com/rancher/rancher/issues/8026

@sshipway , this feature will be available with rancher-server version 1.5.0.

**Comment by EugenMayer** [comment]
Pretty cool feature in 1.5.0

If now, also the catalogs could be conditional, things could really take of

**Comment by vincent99** [comment]
@EugwnMayer not sure exactly what you mean but catalog templates can use templating (in 1.5+)

**Comment by EugenMayer** [comment]
@vincent99 i did remove myself from using catalogs and rancher a while ago in the masses because catalogs are just not good enough.

Not going into the first 10 details, because the templates in here will solve a lot of those systematically, that is great.

But one other thing really makes catalogs suffer in either complexity or ease of installation are conditional fields.

As usual, you have, per catalog, several choices to take
 - which persistence layer ( assuming you select DB type and, if you want to have the catalog start one for you or you provide the link / creds yourself )
 - which auth backend ( like ldap/AD/file whatever )
 - SMTP settings yes/know
 
And things like that are needed by nearly all services which do make sense to be packaged into a catalog at all. But those settings are conditional, depending on if you select "provide persistance layer" you have to set other fields then "provide one for me". Same for if you "activate LDAP' you have to put into this 5 mandatory fields ( host, port, basedn.., id/ mail mapping ) but if you do not select ldap, you dont.

The latter one is the biggest issue - since LDAP should be optional, all fields of ldap must be optional, even though they are mandatory if LDAP is selected. this leads to complex / broken setups, inconvenience and actually at a point, removes the last useful point of a catalog - simple starting point (since upgradeability is none )

**Comment by HenryTheSir** [comment]
Is this anywhere documented? Or is this the only docu for conditions?
Waited very long for this nice feature - Thanksfor the resolution!

**Comment by joshwget** [comment]
The only documentation we currently have is [here](https://docs.rancher.com/rancher/v1.5/en/cli/variable-interpolation/#templating). Past that documentation would really just be general templating docs (https://golang.org/pkg/text/template/). For anything Rancher-specific going forward we will add to out documentation.

**Comment by joshwget** [comment]
@EugenMayer I agree that conditional fields (fields that hide/show depending on the value of another field) would be a really powerful addition to catalog. Between this feature and templating I think it should be possible to create nearly any general template.

**Comment by vincent99** [comment]
While I agree it would be cool, it's also complete madness.

"I just want to show/hide a field based on a boolean" you say.  But the next request will be for evaluating conditionals based on multiple values.  Or the day of the week.  Or I need to compare this field that's a string but contains a number to this other number, can you implicitly cast that for me.  Or "I want the options in an enumeration to depend on the value of another field"...

The eventual endgame is you end up implementing a turing-complete DSL to describe everything.  Which the client has to parse, evaluate, re-evaluate on every keypress, and not accidentally allow arbitrary code injection/otherwise break the app just to ask questions.  And every feature of that DSL needs to be implemented in at least 2 languages (for the browser and CLI).

You can have things like a cyclic graph of dependencies of those variables, so now you need an ncurses interface or something for the CLI to let you edit all the currently-applicable variables, because there isn't necessarily an unambiguously "right" order to ask the questions.  And cycles need to not be able to cause infinite loops somehow.  I could keep going...  And the catalog developer needs to be able to understand somehow, wrapped in a YAML file that contains Golang templates (which use variables, which could affect questions, for yet another level of fun).

For basic use-cases I think what people already do isn't bad; 2 templates with different questions that deploy the same docker image.  If you have more than one or two independent variables that affect thins this doesn't really scale.  But answers that change the questions don't really work very well on upgrade either, it's unlikely your template is going to support clicking upgrade and switching from LDAP+MySQL to GitHub+Postgres.  So now we need another feature to allow you to give us logic to set if an answer should be changeable on upgrade...  Down this path leads madness.

**Comment by gregkeys** [comment]
It would be nice if the conditional templates worked in rancher-compose.yml , the conditions in the docker-compose.yml work great, however if there is a healthcheck associated with a conditional service the stack deploy will fail

**Comment by gregkeys** [comment]
Actually this has been solved with 1.6.0 in that healthchecks can now be placed in the docker-compose.yml

**Comment by ElGranLoky** [comment]
But what happend with scale or start_on_create? It's not support in docker-compose.yml

**Comment by lasley** [comment]
Just ran into this and can confirm there are no warnings or errors when using `scale` or `start_on_create` for instances that are not defined in the `docker-compose` file, so this strategy totally works 🚀
