### ISSUE TITLE
[GKE] Rancher cannot connect to GKE cluster created using Terraform

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32409]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Download and use the following Terraform binary: https://github.com/rancher/terraform-provider-rancher2/pull/621#issuecomment-824813685
On Rancher `v2.5.8-rc9`, create a GKE cluster using the following Terraform script (Networks, API url, and token must be replaced. File can be renamed to `terra.tf`):
[gke_example.txt](https://github.com/rancher/rancher/files/6387336/gke_example.txt)

**Result:**
Cluster is stuck in error state with: `Failed to communicate with cluster: error generating service account token: Post "https://.../api/v1/namespaces": dial tcp ...:443: i/o timeout`

**Other details that may be helpful:**
Related issue:
https://github.com/rancher/rancher/issues/31295

From GKE console, cluster is not private. Rancher GKE upstream spec is populated.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.8-rc9`
- Installation option (single install/HA): single install

**Comment by cmurphy** [comment]
I see the terraform script is using [master authorized networks](https://cloud.google.com/kubernetes-engine/docs/how-to/authorized-networks):

```
    master_authorized_networks_config {
      enabled = "true" 
      cidr_blocks {
        cidr_block = "10.0.0.0/16"
      }
    }
```

That causes access to the control plane endpoint to be disallowed from any IP that is not within the defined CIDR range. Since the CIDR block in the list is a 10-net address, it is not able to access the public control plane endpoint. Can you try either setting master_authorized_networks_config enabled to "false" or choosing a CIDR block that has the Rancher server's public IP address?

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5.8-rc9`. 
gke operator version: `gke-operator:v1.0.1-rc7`

Was able to launch a GKEv2 cluster from Terraform using the following config:
[gke_example2.txt](https://github.com/rancher/rancher/files/6394537/gke_example2.txt)

@cmurphy is correct, the cidr_block needed to be changed. The cluster worked with the following range which includes the rancher setup's public IP.
```
    master_authorized_networks_config {
      enabled = "true" 
      cidr_blocks {
        cidr_block = "23.92.0.0/16"
      }
    }
```
