### ISSUE TITLE
Include RKE2 charts and images in air-gap setup

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#32403]
There are new images (like `rancher-machine`) and new charts (like RKE CNI charts) that need to be included for air-gapped environments. It is likely that the images and charts should be included in KDM and pulled during the build process.

**Comment by cbron** [comment]
This is dependent on RKE2 team creating an "all-in-one" images.txt. Then Rancher team can grab it based on given version of RKE2.

**Comment by cbron** [comment]
This exists now. We need to add a setting for which version of rke2 to use, and given that setting we can download the rke2 images.txt and append it to ours: https://github.com/rancher/rke2/releases/download/v1.21.0-alpha3%2Brke2r1/rke2-images-all.linux-amd64.txt
This should also ensure the rancher-images-sources.txt list has the source set as rke2.

**Comment by ron1** [comment]
Consider adding milestone 2.5.9 to this issue.

**Comment by cbron** [comment]
@ron1 the solution going into 2.6 will likely be quite different than solution going into 2.5. If thats true its less likely for us to formulate a path for 2.5, since it will essentially be a deprecated path.

**Comment by nickgerace** [comment]
Dependent on https://github.com/rancher/rke2/issues/1077 being resolved. Once this issue is resolved, the following images will be mirrored.
```
docker.io/calico/cni
docker.io/calico/kube-controllers
docker.io/calico/node
docker.io/calico/pod2daemon-flexvol
docker.io/calico/typha
```

**Comment by superseb** [comment]
The difference in CI log output regarding k3s-upgrade images being in the list of generating images was because we only install `golangci-lint` for `amd64` (because the checks are not arch dependent so it only has to run on one arch), and in our `scripts/validate` we have the following snippet:

```
if ! command -v golangci-lint; then
	echo Running: go fmt
        echo Skipping validation: no golangci-lint available	test -z "$(go fmt ./... | tee /dev/stderr)" 
        exit
fi	
```

Where we run `go fmt` for the entire repository, but we just exit after which ends with exit 0 (regardless if `go fmt` returns errors). Because of the dirty repo, `scripts/version` marks the `TAG` as `commit_hash-dirty` which makes the version comparison pass for when KDM data is parsed and compared to the min/max versions specified in KDM data and the images get added to the list. On `amd64`, we end up with just the commit_hash as the `TAG` and then the version comparison failed and the images did not get added. The version parsing was not specifically tested/validated but based on the test it seems that that was the reason.

The fix will be to make sure `go fmt` runs and actually fails when something is found. In the process of doing that we also will upgrade `golangci-lint` to latest version and update to `go-skel` latest standards.

**Comment by cbron** [comment]
Nice writeup! One piece I am still confused about though is why its running on both amd64 and arm64, and which one actually gets attached as the asset (or if its whichever finishes last). Can't we just run it on amd64 since it is OS agnostic.

**Comment by nickgerace** [comment]
RE: https://github.com/rancher/rancher/issues/32403#issuecomment-853443837 from @cbron 

Spoke to @StrongMonkey and an `ARCH` check has been added for image generation since it only needs to run on `amd64`.

**Comment by nickgerace** [comment]
## QA Validation

Pre-requisite changes have been merged, but this will require two things:

- [ ] Rancher v2.6 RC (cannot be tested with dev branch unless generated manually)
- [x] RKE2 1.21+ Tag that includes the `rke2-images-all.linux-amd64.txt` file _and_ has all images prefixed with `rancher/`

For the merged solutions to be valid, the `rancher-images.txt` file must include all images in `rke2-images-all.linux-amd64.txt` for the Rancher RC.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by slickwarren** [comment]
blocked by https://github.com/rancher/rancher/issues/34106

**Comment by slickwarren** [comment]
blocked by this issue https://github.com/rancher/rancher/issues/34265 on 2.6.0-rc3

**Comment by nickgerace** [comment]
For more context on https://github.com/rancher/rancher/issues/32403#issuecomment-900417364: Fleet `v0.3.6-rc11` was a dead-on-arrival RC due to Windows automation issues. The manifest for `rc11` DockerHub images was not published as a result. It has been fixed with `rc12`, which requires another Rancher RC.

**Comment by brendarearden** [comment]
Available for testing in 2.6.0-rc4

**Comment by slickwarren** [comment]
blocked by: https://github.com/rancher/rancher/issues/32600#issuecomment-901341667 (unable to provision rke2 cluster in airgap setup)

**Comment by slickwarren** [comment]
this image `rancher/system-agent-installer-rke2:v1.21.3-rc6-rke2r2` is in rancher-images.txt and is tagged in the registry like all the other images, `<registry>/rancher/system-agent-installer-rke2:v1.21.3-rc6-rke2r2`.  But when creating an RKE2 cluster in an airgap setu (2.6.0-rc5) the pull fails in `rancher-system-agent` , as it is expecting `<registry>/docker.io/rancher/system-agent-installer-rke2:v1.21.3-rc6-rke2r2`

**Comment by slickwarren** [comment]
on v2.6.0-rc6, I am able to:
* bring up rke2 cluster v1.21.3-rc7+rke2r2 successfully -- pass
* briing up rke1 cluster v1.21.4 successfully -- pass
