### ISSUE TITLE
No error displayed when no nodepool name is entered during an Edit of a GKEv2 cluster 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32467]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted/imported GKE cluster.
- When the cluster is up and Active, Edit cluster --> Add a nodepool and without entering a name, click on Save
- Error seen

<img width="734" alt="Screen Shot 2021-04-29 at 2 05 13 PM" src="https://user-images.githubusercontent.com/26032343/116619246-0d635680-a8f5-11eb-9c31-9e6752ad46a2.png">

**Expected Result:**
Error similar to `node pool name cannot be an empty string` should be displayed

**Other details that may be helpful:**
Through API, when no nodepool name is given on an Edit cluster error seen
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "node pool name cannot be an empty string",
"status": 422,
"type": "error"
}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): on 2.5-head commit id: `42f722b`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted or imported GKEv2
- Kubernetes version (use `kubectl version`):

```
Any
```

**Comment by westlywright** [comment]
This seems to be a back end issue. It occurs because the second node pool's name is null and not `''` empty string. When the api errors with the 500 I edited my request and changed the null node pool name to `''` and I saw the 422 error happen.

**Comment by aaronRancher** [comment]
This issue is reproduced on Rancher `v2.5.8-rc12`

Steps:
Deploy a hosted/imported GKE cluster.
When the cluster is up and Active, Edit cluster --> Add a nodepool and without entering a name, click on Save
Result:
No error is seen from the UI

This issue is validated on Rancher `v2.5-head` `version a7ebbe6`
An error is shown from UI:
![Screen Shot 2021-04-30 at 9 48 45 AM](https://user-images.githubusercontent.com/57409052/116727780-dbf09680-a999-11eb-99d2-c522039549e6.png)

Will track fix for master-head here: https://github.com/rancher/rancher/issues/32486
