### ISSUE TITLE
Containers fail to start due to "(409 Client Error: Conflict ("Conflict. The name "<name>" is already in use by container . You have to remove (or rename) that container to be able to reuse that name."))"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3247]
Server version - Build from master

Lot of container deployment failures are seen when trying to upgrade/rollback a service , reconcile a service. 
This  causes the service to be stuck in "Upgrading" /"Rolling-Back"/"Degraded" state for a very long time. Sometimes they are stuck forever.

Following error is seen when container deployment fails:

(409 Client Error: Conflict ("Conflict. The name "r-hello_hello123_1" is already in use by container b5e406b5dffb. You have to remove (or rename) that container to be able to reuse that name."))

<img width="1340" alt="screen shot 2016-01-12 at 3 40 50 pm" src="https://cloud.githubusercontent.com/assets/4266958/12280458/e32e4674-b942-11e5-9ccf-8e27359d46f0.png">

<img width="958" alt="screen shot 2016-01-12 at 3 35 49 pm" src="https://cloud.githubusercontent.com/assets/4266958/12280364/2ee06616-b942-11e5-9b0a-5b28bc9bb9fc.png">

**Comment by sangeethah** [comment]
Tested with v0.55.0-rc3:

This issue is not seen anymore where services are stuck in "Upgrading" /"Rolling-Back"/"Degraded" when upgrading/rollbacking/reconciling services.

**Comment by manei** [comment]
Rancher Release - v0.59.1
This issue appeared again. Even if the service and its containers are deleted, unless you restart the agent on that specific host when the container is starting it gives you:

Containers fail to start due to "(409 Client Error: Conflict ("Conflict. The name "<name>" is already in use by container . You have to remove (or rename) that container to be able to reuse that name."))".
I can confirm that the container shown in the error did not exist on the host.

Unfortunately I cannot give you more information on how to reproduce this bug.

**Comment by deniseschannon** [comment]
@manei I am unable to reproduce. 

If you are launching services, it doesn't matter what host the containers are on. It's a matter of whether the same service with the same name exists in a particular stack.  That's the only check that Rancher performs when adding services.

If you are adding containers to a specific host, there is no name restriction for standalone containers in Rancher. 

<img width="276" alt="screen shot 2016-03-11 at 10 33 23 am" src="https://cloud.githubusercontent.com/assets/11410997/13711826/70c563b8-e775-11e5-9529-1736b315839b.png">

I ended up looking in Docker and it looks like you might be hitting one of their open issues. 
https://github.com/docker/docker/issues/15311

What version of Docker are you using?

**Comment by manei** [comment]
@deniseschannon thanks for the quick response
I'm using docker version 1.10.0 and it seems is actually a docker issue. It was really weird that rancher complained about not being able to deploy a container because the name it wanted to assign to it was already used by another container with an id which did not exist in docker engine.

**Comment by VAdamec** [comment]
I'm getting same error, for Prometheus stack, config container didn't start after healthcheck fail:

```
2017-02-01 06:13:31,228 ERROR [:] [] [] [] [cutorService-28] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got stopped: Error response from daemon: Conflict. The container name "/r-Prometheus-prometheus-prom-conf-1-f3b4308f" is already in use by container c62ca816958c4705c4c8e0a2470c0ebc6406fbc5fba044b9715cd4cf2a4c4b46. You have to remove (or rename) that container to be able to reuse that name.
```

agent restart didn't help, only deleting.


Docker version 1.13.0, build 49bf474
Rancher version v1.3.3

**Comment by tuwid** [comment]
Still having this issue randomly on rancher 1.6.10 and docker 17.04.0-ce

**Comment by thehackercat** [comment]
Still having this issue randomly docker 18.03.1-ce

**Comment by superseb** [comment]
This issue is almost 2.5 years old and can't be used to indicate issues with current releases. Please file a new issue with versions used and steps to reproduce so we can investigate.

**Comment by surendrababukandhikattu** [comment]
facing the same issue in Rancher V1.6

**Comment by surendrababukandhikattu** [comment]
Any resolution , please provide me..

**Comment by MouniraTlili** [comment]
Docker -> preferences -> bug icon (top right) -> clean / purge data
