### ISSUE TITLE
[monitoring v2] Windows-exporter deploys on linux clusters when installing monitoring

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32530]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a downstream cluster (linux)
* install monitoring v14.5.100
* wait for it to install

**Result:**
* windows-exporter daemonset is deployed with no pods (expected not to deploy)

<img width="1219" alt="Screen Shot 2021-05-04 at 11 23 09 AM" src="https://user-images.githubusercontent.com/16691014/117051198-1f654080-accb-11eb-9f37-45cd324c0f18.png">

**Other details that may be helpful:**
* commit ID of repo: 20b70c0c253c515bade19f3d6d15fd50c425c330

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc18
- Installation option (single install/HA): single

**Comment by aiyengar2** [comment]
@slickwarren The fix from the backend side was the uncomment `global.cattle.windows.enabled=false` (which means that, from the Rancher Dashboard UI, a user cannot change this value back to false as indicated in https://github.com/rancher/rancher/issues/32274#issue-864267284), so we need to make sure we can retest https://github.com/rancher/rancher/issues/32274.

The new way to disable windows components specifically would be to set `windowsExporter.clients.enabled=false` instead of trying to modify the `global.cattle.windows.enabled` value.

**Comment by slickwarren** [comment]
using the latest chart (commit 766d0ea8d73bb6a727a72c4a89fa4ce730479239) I did not see windows-exporter daemonset deploying on linux clusters. Tested the following:
* updated existing linux DS cluster with monitoring already installed (and had windows-exporter daemonset) -- pass -- removed daemonset, monitoring operates normally
* deployed new downstream linux cluster -- pass -- windows-exporter doesn't deploy and monitoring works as expected
