### ISSUE TITLE
[monitoring v2] Add unit label to grafana embedded graphs that are for a rate or count

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32559]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
* deploy monitoring v2 on a downstream cluster
* go to the `Kubernetes Components Metrics` tab of the cluster dashboard

**Result:**
* graphs here (and in the grafana link) don't have units
<img width="1625" alt="Screen Shot 2021-05-05 at 12 32 26 PM" src="https://user-images.githubusercontent.com/16691014/117208841-73932200-adaa-11eb-8ba0-a5b5b1dcc0dc.png">

**Other details that may be helpful:**
* I would suggest a unit of something like `<count> per <refresh_rate>` where applicable

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc19 -- monitoring v14.5.100
- Installation option (single install/HA):single

**Comment by MKlimuszka** [comment]
Unfortunately, we have chosen not to do this.  The convention for metrics is to encode the information requested in metric names, and since metric names are subject to change it requires embedded metric extraction in grafana dashboards, and kube-prometheus-stack and prometheus ecosystem projects typically take a stance that that's not something they want to do or maintain. So adding labels in our dashboards will not match what upstream does and could possibly cause bugs and inaccurate reporting over time.
