### ISSUE TITLE
Occasional 404s on fonts

### ISSUE THREAD

**Issue by rlex** [rancher/rancher#3256]
Sometimes when opening rancher web ui i see squares instead of icons with following errors in console:
https://rnc.e.tld/assets/fonts/rancher-icons-5ddce9a2c2585ade492286685e2d59ca.ttf?jbgtcg Failed to load resource: the server responded with a status of 404 (OK)
https://rnc.e.tld/assets/fonts/rancher-icons-04098764ef91e5fe4d5caf7ffcd93c05.woff?jbgtcg Failed to load resource: the server responded with a status of 404 (OK)
After reload it starts working correctly.

**Comment by deniseschannon** [comment]
I have never seen this, so will let the UI team take a look at it.

**Comment by vincent99** [comment]
@rlex It really says 404 OK?  Was this after recently upgrading `rancher/server` by any chance?  If you reload is it the same URL that succeeds? (you can open up the browser dev tools -> network tab, then reload to see the request)

**Comment by rlex** [comment]
URL lines copied directly from chrome dev tools. Yes, i upgraded to recent release and after this i started to see those errors. It also seems i can't reproduce it right now.

**Comment by vincent99** [comment]
ok, the underlying issue is probably https://github.com/rancher/rancher/issues/2977 then.. You're getting served a stale copy of index.html becuase of that issue.  The HTML refers to the font with a hash that on longer exists, if the font happens to have changed in the release you upgraded to (which it does fairly infrequently), so you get 404.  Then you do a manual refresh and get new HTML that refers to new hash that does exist, and can't reproduce it anymore.
