### ISSUE TITLE
RKE2 Provisioning - Add support for Airgap

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#32600]
For RKE2 provisioned clusters, we need to ensure that Air Gap will work correctly, which means the following:

- It needs to support setting up a private registry. Please test using the **global** private registry. Cluster level private registry should be validated with https://github.com/rancher/rancher/issues/32389.
- It needs to be able to use bundled charts / KDM.
- It needs to have specialized instructions on how to deploy private registry and configure bundled charts.

**Note:**
- Only system-charts and feature charts (charts on dev/release branches) are bundled into a Rancher instance and can be installed onto Rancher without access to the internet.

**Comment by deniseschannon** [comment]
@kinarashah to add support to extend this to set the system-default-registry

**Comment by slickwarren** [comment]
did a first pass using the following:
**Rancher Server Setup**
- Rancher version: v2.6.0-rc1
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, v1.3.0-rc11, k8s v1.21.3
- Proxy/Cert Details: airgapped cluster, valid letsencrypt certs

**Information about the Cluster**
- Kubernetes version: v1.21.3-rc3+rke2r2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom


**Describe the bug**

Downstream custers are not registering in an airgapped setup.  

**To Reproduce**
* deploy an airgapped setup on v2.6.0-rc1
* deploy a custom node and run the registration cmd

**Result**
Downstream node(s) are stuck in state `waiting for agent to check in and apply initial plan`.  Looking at the logs on the node after running the registration command, this is the last log from `rancher-system-agent`
```
 level=debug msg="reconciling file permissions for /var/lib/rancher/rke2/etc/config-files/private-registry to 0:0 384"
```
with no logs in `rke2-server`

**Expected Result**

Nodes should be able to register using RKE2

**Screenshots**


**Additional context**
<!--Add any other context about the problem here.—>
RKE1 custom nodes registered and went to an `active` state in the cluster

**Comment by deniseschannon** [comment]
Mostly likely will blocked by: https://github.com/rancher/rancher/issues/34071

**Comment by deniseschannon** [comment]
Blocked also by: https://github.com/rancher/rancher/issues/34217

**Comment by deniseschannon** [comment]
@slickwarren The main issue where the cluster wasn't getting the registry should be resolved for the global registry, so we will need to do another test to see what the next issue is.

**Comment by deniseschannon** [comment]
Available to test with v2.6.0-rc3

**Comment by slickwarren** [comment]
blocked by this issue https://github.com/rancher/rancher/issues/34265 on 2.6.0-rc3

**Comment by slickwarren** [comment]
on 2.6.0-rc4:
* local cluster (HA setup, valid certs) comes up with all pods active -- pass
* rke1 custom cluster provisions and comes to `active` state -- pass
* rke2 imported cluster (from a public setup) comes to `active` state -- pass
  * able to install monitoring v2, uses registry images for v100.0.0+up16.6.0 -- pass

**reopening for the following issue:**
* unable to provision rke2 custom cluster
  * stuck in waiting for agent to check in and apply initial plan .  The last log I see from rancher-system-agent.service is
`level=debug msg="reconciling file permissions for /var/lib/rancher/rke2/etc/config-files/private-registry to 0:0 384"`
  * there are no logs for the `rke2-server`

**Comment by deniseschannon** [comment]
Latest issue is that a required image is missing in `rancher-images.txt`:

https://github.com/rancherlabs/rancher-security/blob/master/package/Dockerfile#L43

**Comment by deniseschannon** [comment]
There are other images that was introduced by @ibuildthecloud which was never added to the `rancher-images.txt` file creation. 
These images are harder to identify, as they aren't actually defined anywhere, but derived from KDM versions of RKE2 and k3s. We will need to find them from the data.json file. It needs to based on the version in KDM that also has the serverArgs as part of the entry. There are other entries that don't have this serverArgs that should not be added. 

`rancher/system-agent-installer-rke2` 
- Derived from here: https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels-rke2.yaml#L11

and

`rancher/system-agent-installer-k3s`
- Derived from here: https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels.yaml#L8

**Comment by kinarashah** [comment]
@deniseschannon Does RKE2/k3s store these versions somewhere for UI to display on create cluster?

**Comment by deniseschannon** [comment]
`/v1-rke2-release/releases` is where the options and chart versions

**Comment by slickwarren** [comment]
A smoke test of 2.6.0-rc5 [does have a blocker,](https://github.com/rancher/rancher/issues/32403) but there is a workaround for it. Continuing p0 tests using a global, noauth registry:
* all workloads in local cluster are active -- pass
* able to deploy downstream cluster -- pass
  * single node -- pass
  * multi node, dedicated node per role -- pass
* able to deploy apps/workloads -- pass
  * workload added to registry + deployed to downstream cluster -- pass
  * monitoring v2 able to deploy and p0 tests pass -- pass


A small issue with [chart images/logos not loading was filed here](https://github.com/rancher/rancher/issues/34377)

I will continue with testing on Monday.

**Comment by slickwarren** [comment]
on 2.6.0-rc5:
* provision rke1 cluster (1.21.4-rancher1.1) -- pass
  * install apps (monitoring v100.0.0+up16.6.0, longhorn v100.0.0+up1.1.2) -- pass
* provision rke2 cluster (v1.21.3-rc7+rke2r2) -- pass
  * install apps (monitoring v100.0.0+up16.6.0, longhorn v100.0.0+up1.1.2) -- pass
* upgrade k8s for rke1 cluster (1.20.10 -> 1.21.4) -- pass
