### ISSUE TITLE
Feature Flags: New and Expected Behaviors

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#32631]
**Fleet is expected to always be on for 2.6**
- Test for upgrade scenarios where in v2.5.x Fleet is disabled.
- Test for fresh installs while setting Fleet feature flag explicitly to OFF.
- Test using the API to set the feature flag to OFF.

**Cluster Provisioning is a New Feature Flag in 2.6**
- What does the UI look like if Cluster Provisioning is turned off? Take note of the Cluster Management/Provisioning section look like?

**RKE2 Provisioning has a Feature Flag in 2.6**
- Test with this flag in conjunction with cluster provisioning both toggled OFF and ON.

**Comment by slickwarren** [comment]
**RKE2 provisioning feature flag**
on master-head (5c06f35) I tested the following:
* Feature flag explicitly off on fresh install
  * toggle button no longer shown
  * rke1 only options available (provision through dashboard has embedded ember view for all options)
  * dashboard and ember provisioning works as expected
<img width="1865" alt="Screen Shot 2021-05-13 at 9 02 42 AM" src="https://user-images.githubusercontent.com/16691014/118152998-3e01c080-b3ca-11eb-814b-1c5ce6aa0798.png">

* Feature flag left to default on install (set to true)
  * RKE2 disables clicks on provision options that don't have RKE2 enabled yet
  * RKE1 has all options enabled, similar view to screenshot above

* toggle feature flag through UI
  * both enabling and disabling gives the expected behavior above
  * warning given when enabling/disabling the flag
<img width="351" alt="Screen Shot 2021-05-13 at 9 07 40 AM" src="https://user-images.githubusercontent.com/16691014/118153779-1eb76300-b3cb-11eb-8027-56bc016f7631.png">

**Comment by slickwarren** [comment]
disabling `multi-cluster-management` on the same version as above gives the following errors:
<img width="1726" alt="Screen Shot 2021-05-13 at 11 28 42 AM" src="https://user-images.githubusercontent.com/16691014/118170083-8e831900-b3de-11eb-93ba-dc68849336c9.png">
<img width="698" alt="Screen Shot 2021-05-13 at 11 29 03 AM" src="https://user-images.githubusercontent.com/16691014/118170096-917e0980-b3de-11eb-8eeb-660e93d9100b.png">

**Comment by izaac** [comment]
Most of the continuous delivery (fleet related flags) were covered in: https://github.com/rancher/rancher/issues/32808

**Comment by slickwarren** [comment]
on master-head (ad099ee), for RKE2 feature flag tested the following:
* adding an RKE2 cluster, disabling the feature flag -> after rancher fully restarts, the cluster is fully functional  == PASS
* adding rke1 cluster, re-enabling the feature flag -> after rancher fully restarts, the cluster is fully functional == PASS
