### ISSUE TITLE
Pushprox-kube-etcd-client pods fail to start

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#32652]
CrashLoopBackOff: back-off 5m0s restarting failed container=copy-certs pod=pushprox-kube-etcd-client-gk9vr_cattle-monitoring-system(3dc96f9a-25eb-4b82-9b24-d4140462e43b)

copy-certs container logs:
```
Searching for files to copy within the source volume
cert: kube-etcd-*.pem
key: kube-etcd-*-key.pem
cacert: kube-ca.pem
Failed to find cert file
```

To reproduce:
 - deploy 3 node DO custom cluster in EmberUI
 - Dashboard -> Cluster tools -> Monitoring -> Install (system project)
 - rancher-monitoring:14.5.100

Tested on:
master-head (6030ab5) - chart dev-v2.6 (f52800537f606e9ac9744081f6e3b2748d53685f)
2.5-head (3816d8b) - chart dev-v2.5 (3cd4b8063ed136e7fbd0de269bec75c1514ad5cc)

**Comment by aiyengar2** [comment]
@kravciak is the cluster provisioned via RKE1? If so, based on [the configuration of `rkeEtcd`](https://github.com/rancher/charts/blob/afe207aa7ea93b3baa28c107640ed22a4b6d3e0c/charts/rancher-monitoring/rancher-monitoring/14.5.100/values.yaml#L66-L83), we should be able to expect:
1. That your etcd nodes have the label `node-role.kubernetes.io/etcd: "true"` on them
2. That each etcd node has certs in `/etc/kubernetes/ssl` following the format `kube-etcd-*.pem`, `kube-etcd-*-key.pem`, and `kube-ca.pem`.

Can you check whether these hold true within your cluster? If not, the workaround for this issue might be overwriting one of those fields.

**Comment by kravciak** [comment]
I retried on master-head (29674d9) and problem is still there

1. labels are there
```
ε kubectl get nodes -o wide --show-labels | grep 'node-role.kubernetes.io/etcd=true' | awk '{print $1,$12}'
mkravec1 beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cattle.io/creator=norman,kubernetes.io/arch=amd64,kubernetes.io/hostname=mkravec1,kubernetes.io/os=linux,node-role.kubernetes.io/controlplane=true,node-role.kubernetes.io/etcd=true,node-role.kubernetes.io/worker=true
mkravec2 beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cattle.io/creator=norman,kubernetes.io/arch=amd64,kubernetes.io/hostname=mkravec2,kubernetes.io/os=linux,node-role.kubernetes.io/controlplane=true,node-role.kubernetes.io/etcd=true,node-role.kubernetes.io/worker=true
mkravec3 beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cattle.io/creator=norman,kubernetes.io/arch=amd64,kubernetes.io/hostname=mkravec3,kubernetes.io/os=linux,node-role.kubernetes.io/controlplane=true,node-role.kubernetes.io/etcd=true,node-role.kubernetes.io/worker=true
```

2. there are no certs on this path. I see this option in Monitoring setup, default is
`etcd Node Certificate Directory = /etc/kubernetes/ssl`
```
~ ssh rancher@<node> 'hostname; sudo ls -lR /etc/kubernetes/ssl/'
mkravec1
/etc/kubernetes/ssl/:
total 4
drwx------    2 root     root          4096 Jun  3 08:17 certs

/etc/kubernetes/ssl/certs:
total 4
-rw-------    1 root     root           635 Jun  3 08:17 serverca
```

**Comment by aiyengar2** [comment]
Given that there are no certs on this path and an offline conversation with @kravciak that this may have been a cluster composed on RancherOS nodes (which [are documented](https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/) to require specifying a non-traditional etcd certificate directory `/opt/rke/etc/kubernetes/ssl` to deploy under the `Enable Monitoring` section), I'm moving this issue back to test since I've not been able to reproduce this.

@kravciak if we find out the nodes were not RancherOS, then feel free to re-open this issue with details of what hosts you used as part of testing so we can reproduce the cluster and see where the certs are located. Perhaps we need to add more to our docs to resolve this issue.

If the nodes were RancherOS hosts, can you double check whether the steps indicated in our docs were sufficient?

**Comment by kravciak** [comment]
Hi, on rancherOS nodes setting `/opt/rke/etc/kubernetes/ssl` during chart deployment helped.
I checked also using ubuntu with default setting, everything works fine as well.

Thanks again for pointing to doc, I assumed defaults would work - my bad :)
Tested on master-head (51d074b)
