### ISSUE TITLE
Apps deployed in downstream clusters stuck in "Deploying"

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#32692]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Provision a downstream custer.
2. Launch redis app in default project.

**Result:**
App is stuck in `Deploying` when it should be active. May have to refresh to see updates to app progress in UI which may be a separate bug.

**Other details that may be helpful:**
Logs show:
`[ERROR] error syncing 'redis/redis-master': handler workloadServiceGenerationController: cannot find app namespace in labels of redis, requeuing
`
When the namespace are created it appear that the `field.cattle.io/projectId` is not being added unless it is in the local cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master-head

- Installation option (single install/HA):
docker install

**Comment by Jono-SUSE-Rancher** [comment]
Can you guys validate one of the apps from the library catalog in ember on a downstream cluster?

**Comment by aaronRancher** [comment]
This issue is reproduced on Rancher `master-head` `version d7ef41e`
Steps:
Provision a downstream cluster.
Launch redis app in default project.

Result:
App is stuck in `deploying` state.
![Screen Shot 2021-05-14 at 12 06 58 PM](https://user-images.githubusercontent.com/57409052/118317439-e9834180-b4ac-11eb-8a50-ed65776d37cb.png)
`field.cattle.io/projectId` is not set:
![Screen Shot 2021-05-14 at 12 03 27 PM](https://user-images.githubusercontent.com/57409052/118317459-f011b900-b4ac-11eb-93c9-8e42718913b1.png)
Expected:
![Screen Shot 2021-05-14 at 12 03 17 PM](https://user-images.githubusercontent.com/57409052/118317476-f30ca980-b4ac-11eb-82e1-c10950ccdaec.png)

**Comment by deniseschannon** [comment]
I'm unable to reproduce this with master-head.

When I try and deploy redis in a downstream RKE1 or RKE2 cluster, the app is active with 3 containers.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version b395238` with the following steps:
Deploy a downstream cluster.
Install Redis in default project.

Result:
App becomes active and workloads are healthy:
![Screen Shot 2021-08-02 at 5 25 03 PM](https://user-images.githubusercontent.com/57409052/127939392-1351bb92-6720-44f6-8c47-7925117425af.png)
![Screen Shot 2021-08-02 at 5 25 13 PM](https://user-images.githubusercontent.com/57409052/127939393-39585d5a-dcf4-4a64-915a-18d31174c7c3.png)
`field.cattle.io/projectId` is set on Redis namespace.
![Screen Shot 2021-08-02 at 5 38 16 PM](https://user-images.githubusercontent.com/57409052/127940115-5d858ac9-9089-479d-a337-b0303d314b4a.png)
Tested on an RKEv1 and RKEv2 cluster.
