### ISSUE TITLE
Cluster is seen in Provisioning state when one of the two nodepools is Active

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32690]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- New cluster explorer UI --> Left Panel --> Cluster Management --> Clusters page --> Create
- Deploy a 2 nodepool DO RKE2 cluster; 1 nodepool - np1 - all roles enabled, 2nd nodepool - np2 - worker node role enabled.
- np1 comes up Active. np2 doesnt
- But the cluster is still stuck in Provisioning state.

**Expected Result:**

- Can we expect the clusters with 1 nodepool all roles Active and 1 nodepool inActive(stuck in provisioning) to be available as Active to the users
- It is seen Active on Ember UI though.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `1e1ed67`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE2 DO
- Kubernetes version (use `kubectl version`):

```
ANy
```

**Comment by deniseschannon** [comment]
The state of the cluster will roll up the state of all nodes in the new cluster provisioning v2 framework. Therefore any nodes in the cluster that is any provisioning state will show up as provisioning for the cluster.

There is a new type of cluster (provisioning.cattle.io) that was introduced with the new cluster provisioning framework which is used in Vue. 

When creating the new RKE2 cluster (provisioning.cattle.io), we also create the old cluster type (management.cattle.io), but in this old cluster type, the cluster is treated as an imported cluster since it was created outside of the old provisioning framework. Therefore, the state of the cluster will be `Active` as soon as the cluster agent is deployed and is not reliant on the state of the nodes.

**Comment by deniseschannon** [comment]
The behavior seen in this issue is as expected based on the explanation.

**Comment by sowmyav27** [comment]
Closing this based on https://github.com/rancher/rancher/issues/32690#issuecomment-854168819 .
