### ISSUE TITLE
Add container start time to Metadata/Rancher API

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#3270]
Hi,

would it be possible to add when a container started in the metadata and/or Rancher API? It would be the equivalent of 'StartedAt' in docker inspect.

I am building some monitoring around Rancher and I'd like to use this field together with start_count.

Thank you!

Matteo

**Comment by deniseschannon** [comment]
There is a `created` in the API for containers. This is when the container is created in Rancher. 

It's not listed in the API docs for the container resource (http://docs.rancher.com/ranchaer/api/api-resources/container/) because it's a common field on all of our resources (http://docs.rancher.com/rancher/api/common/).

**Comment by deniseschannon** [comment]
@m4ce Would `created` be sufficient with what you are trying to do?

**Comment by deniseschannon** [comment]
@m4ce If you are looking for something else, please re-open. :)

**Comment by m4ce** [comment]
@deniseschannon,

sorry for not coming back to you earlier. The created field would not be enough, but I'd say we can leave this for now as it's not super important :)

Thank you for looking into it!
