### ISSUE TITLE
404 Error when installing monitoring v2 chart 

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32738]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* go to apps and marketplace
* select monitoring to install

**Result:**
readme displays, but there is a 404 error in the logs `Request URL: https://<ip>/k8s/clusters/<cluster>/v1/catalog.cattle.io.apps/cattle-monitoring-system/rancher-monitoring`

**Other details that may be helpful:**
user is still able to continue through the workflow, and install monitoring

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (d7ef41e8)
- Installation option (single install/HA): single
- chart version: dev-v2.6 branch (ccad1334fa39669b5e7f4a3130494f28b201e67f)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 node, 2vCPU each
- Kubernetes version (use `kubectl version`): v1.21.1-alpha4+rke2r1

**Comment by sowmyav27** [comment]
Maybe caused by this PR - https://github.com/rancher/dashboard/pull/2876 ?

**Comment by richard-cox** [comment]
Some charts have targeted namespaces (like I think all in Cluster Tools) and are singular. So in the Chart Details page we check if an app for that chart exists to advise the user they will be editing the existing app rather than creating a new one. The 404 request here is that check and is to be expected if the app has not been installed.
