### ISSUE TITLE
Upgrade Plan for RKE2 downstream cluster does not honor system-default-registry / does not work in airgapped scenarios

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#32803]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Rancher 2.5.8 or earlier
Imported RKE2 downstream cluster 1.20.5
Air-Gapped deployments

Change the version of the downstream cluster via edit to 1.20.6

The plans created have the prepare and the upgrade image `rancher/rke2-upgade:v.1.20.6-rke2r1` and NOT `<system-default-registry>/rancher/rke2-upgade:v.1.20.6-rke2r1`. This is also not configurable.
Even changing the deployed plan via "patch" does not help as Rancher is overwriting the plans automatically with the wrong settings.

**Result:**

Upgrade Pods fail in pulling the image as they can not reach docker.io

**Other details that may be helpful:**

Registry mirror feature in rke2 can not be used in 1.20.5 or earlier or in 1.19.. as there is only a single on-premise registry where images are in namespaces and the namspace mapping feature in registries.yaml only comes with 1.20.6.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.20.5

**Comment by Martin-Weiss** [comment]
Some further comments:

There are several changes required in the rke2-server or agent configuration during upgrades.. i.e. from 1.20.5 to 1.20.6 changes for the system-default-registry setting in config.yaml and registries.yaml are required due to changes in the behavior. Also for changes like vsphere in tree to out of tree migration or dependencies on the OS side of things we must have a way to modify / customize the PLANs that are created and used by Rancher for the given downstream cluster.

Is there / What is the way to customize the upgrade plans?

**Comment by Martin-Weiss** [comment]
One more comment:

In airgapped setup we also might have to delete the "old" /var/lib/rancher/rke2/agent/images/rke2-images.linux-amd64.tar.zst during the upgrade - replacing the binary i.e. 1.20.5 -> 1.20.6 and still importing the images from 1.20.5 might not be the best thing...

**Comment by thedadams** [comment]
If the `k3s-based-upgrader` is successfully being deployed and only the plans have the wrong image, then Rancher should check the `SystemDefaultRegistry` setting when setting the `upgradeImage` [here](https://github.com/rancher/rancher/blob/978d81ce2127e20a963a9d3e5bb181bdb8d61495/pkg/controllers/management/k3sbasedupgrade/deployPlans.go#L32).

The `k3s-based-upgrader` is being deployed as an App, so it seems reasonable that the correct image with the system default registry is being used there.

**Comment by jiaqiluo** [comment]
The bug is reproduced on Rancher 2.5.8 with an imported single-node RKE2 v1.20.5+rke2r1 cluster. 
The RKE2 cluster is configured to mirror `docker.io` to a private registry following [the docs](https://docs.rke2.io/install/containerd_registry_configuration/#containerd-registry-configuration).
In Rancher, the global `system-default-registry` is set to the same private registry.

After triggering the upgrade of the RKE2 version in Rancher UI (from v1.20.5+rke2r1 to v1.20.13+rke2r1), an app named `rancher-rke2-upgrader` is deployed into the system project in the RKE2 cluster. The app uses the chart `rancher-k3s-upgrader`  0.2.1, and pulls the image from the private registry. 
Problems comes from the job `apply-rke2-master-plan-on-jiaqi-test-node-2-with-26cc28ad-4b1c7` which pulls the following 2 images: 
- `ec2-52-53-233-140.us-west-1.compute.amazonaws.com/rancher/kubectl:v1.18.0` for the init container, 
- `rancher/rke2-upgrade:v1.20.13-rke2r1` for the main container 

It fails to pull the second one with the following error message:
```
Failed to pull image "rancher/rke2-upgrade:v1.20.13-rke2r1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/rke2-upgrade:v1.20.13-rke2r1": failed to resolve reference "docker.io/rancher/rke2-upgrade:v1.20.13-rke2r1": failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
```

**Comment by jiaqiluo** [comment]
After future debugging and discussion with @thedadams, we concluded that we need to fix the following 2 issues:
- Rancher should add the system-global-registry to the values it passes to the chart when installing the `rancher-rke2-upgrade` app 
- Rancher should also append the system-global-registry to the image when setting the `rke2upgradeImage`. 

The above-mentioned app and job run and finish successfully in my test on both rancher 2.5.8 and v2.6-head simply because I have the registry mapping configured on the node: all pulls for images from docker.io is mapped to the private registry under the hook, so even the UI/Kubectl shows the image name without the private registry address as the prefix, they are actually from the private registry.  However, we still need to fix those two issues because the registry used for provisioning the RKE2 cluster could be different from the one in Rancher.

**Comment by Martin-Weiss** [comment]
FYI - with newer versions of RKE2 we use registries.yaml and remove the system-default-registry to get around this issue.
While this does not help for „older“ versions - maybe we should start to deprecate system-default-registry in favor of registries.yaml mappings to be used in the future..

**Comment by thedadams** [comment]
Since the `registry.yaml` must be configured by the user for imported RKE2 clusters, then a user can also add a mirror for the system-default-registry if necessary. The only way for Rancher has to indicate a different registry can/should be used in for this issue is the system-default-registry.

**Comment by jiaqiluo** [comment]
### Root cause
When upgrading the k8s version of RKE2 clusters via Rancher UI, Rancher creates a Plan (which will create a Job later) and installs an app named `rancher-rke2-upgrade` in the RKE2 cluster (which can be found in System project -> Apps in the old UI), but Rancher does not append the global-system-registry to the images. As a result, the Job and the app try to pull images from DockerHub which fails in the air-gapped environment. 

### What was fixed, or what changes have occurred
There are two parts in the fix:
- the system-global-registry is added to the values that are passed to the chart when installing the rancher-rke2-upgrade app
- the system-global-registry is appended to the image when setting the rke2upgradeImage in the Plan 

### Areas or cases that should be tested
Upgrading the downstream RKE2 cluster should succeed in the air-gapped environment. Images should be pulled from the global-system-registry
 
### What areas could experience regressions?
It should not affect anything except upgrading the downstream RKE2 cluster. 

### Are the repro steps accurate/minimal?
yes.

**Comment by slickwarren** [comment]
tested using rancher v2.6.4-rc2:
* deploy rke2 cluster v1.21.9+rke2r1 -> upgrade to v1.22.6+rke2r1 -- pass
  * ensure that all pods have <system-default-registry> images -- pass
  * ensure cluster gets back to active state on latest version used -- pass
* deploy k3s cluster v1.21.9+k3s1 -> upgrade to v1.22.6+k3s1 -- pass
  * ensure that all pods have <system-default-registry> images -- pass
  * ensure cluster gets back to active state on latest version used -- pass
* deploy rke1 cluster v1.21.9 -> upgrade to v1.22.6-- pass
  * ensure that all pods have <system-default-registry> images -- pass
  * ensure cluster gets back to active state on latest version used -- pass
