### ISSUE TITLE
Service discovery records / services are not created when workload is deployed

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#32801]
rancher/rancher:master-head 9c9491b

From the Ember UI:
* Create an RKE cluster (in this case used an ec2 nodedriver cluster)
* Create a workload
* Check services `kubectl get svc -n <namespace>` and no service is created for the workload. 
* No dns/service-discovery record is created for the workload

Expected:
As in v2.5.8
* A service and dns record should be created for the workload
```
> kubectl get service -n default
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   131m
test         ClusterIP   None         <none>        42/TCP    109m
test6        ClusterIP   None         <none>        42/TCP    18m
```

This might be related to the root cause of https://github.com/rancher/rancher/issues/32659

**Comment by anupama2501** [comment]
On the master-head version f6c1d82:

1. Create an rke1 cluster on ember UI
2. Once the cluster is active, create worklaods and ingress and the test fails with the following error:

`
rancher.ApiError: (ApiError(...), 'InternalError : Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": dial tcp***:443: connect: connection refused\n\t{\'baseType\': \'error\', \'code\': \'InternalError\', \'message\': \'Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": dial tcp ***:443: connect: connection refused\', \'status\': 500, \'type\': \'error\'}')
`

**Comment by sowmyav27** [comment]
**On master-head commit id: `979d2ba`**

Ports - Nodeport, hostpost and ingresses also do not work, as this involves creating service discovery entries for the workload.

**Comment by ryansann** [comment]
This does look to be related to https://github.com/rancher/rancher/issues/32659

What we're seeing with that issue is the handler in the `pkg/controllers/managementagent/nslabels` controller isn't firing when namespaces change, which is causing the projectId label to not be added to namespaces, which in turn causes the networkpolicy controllers to not work properly.

**Comment by kinarashah** [comment]
Note: Hold off on testing this issue, we've added support for management agent feature flag. But need to turn it on. Will be putting in a separate PR for that.

**Comment by sowmyav27** [comment]
Reopening for this https://github.com/rancher/rancher/issues/32801#issuecomment-850594065

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/32951/commits/1952830252abddea062a13ab23a66cbc8335e757

**Comment by slickwarren** [comment]
After running our automation on master-head (29674d9) using an RKE1 cluster, this issue appears to be fixed. All service tests passed (excluding xio, kubectl, and cluster IP failed. xio and kubectl were expected to fail, and a manual run of cluster IP passed).

**Comment by thehejik** [comment]
Reopening because the services are not created when workload is deployed on custom clusters deployed from rancher or imported RKE1 clusters provisioned by `rke-1.3.0-rc6` bin, both with k8s `v1.21.1-rancher2-1` on `rancher/rancher:master-head 62a8e6a`.

Interesting is that services are created on local RKE1 cluster with the same kubernetes version - it doesn't work on custom or imported RKE1 with k8s versions 1.20 and 1.21.

**Comment by thehejik** [comment]
Closed in favor of https://github.com/rancher/rancher/issues/33125 (new)
