### ISSUE TITLE
[Monitoring v1] deploys, but prometheus is missing most targets and grafana has no metrics

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32837]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy monitoring v1 (tested with 0.2.1, 0.2.2, 0.2.3) on a downstream cluster

**Result:**
* monitoring deploys, but doesn't finish provisioning
* prometheus only has 2 targets
* all other UI seems to be fine 
* since prometheus isn't up correctly, grafana doesn't have any data

**Other details that may be helpful:**
* all monitoring related pods and workloads are active 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head(cb94b9c)
- Installation option (single install/HA):tested on single, HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): tested on Linode, ec2 nodes
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):v1.20.6

**Comment by slickwarren** [comment]
likely culprit: https://github.com/rancher/rancher/issues/32801

**Comment by aiyengar2** [comment]
The root cause for this issue is unrelated to Monitoring V1; the issue is that the `cattle-prometheus` namespace that was added to the System Project in `master` (`629146a`) does not contain the expected label `field.cattle.io/projectId: SYSTEM_PROJECT_ID` on it, as seen in the screenshot below:

![screen_shot_2021-05-27_at_12 20 21_pm](https://user-images.githubusercontent.com/13127443/120027752-9e872500-bfa8-11eb-9832-39486531988e.png)

This breaks Monitoring V1 (both Project and Cluster) since the Prometheus CR selects ServiceMonitors from a namespace based on the label on that namespace, as seen here: https://github.com/rancher/rancher/blob/692a9507ebeec70118aa8496999e89d0dfa1cc18/pkg/controllers/managementuserlegacy/monitoring/clusterHandler.go#L339-L341

Spoke to @slickwarren offline and he was unable to reproduce this issue in `2.5.8` and `2.5-head` today.

**Comment by aiyengar2** [comment]
Reproduced in `master-head` (`d8acb21`): issue seems to only impact downstream clusters, not the local cluster.

```
arvindiyengar: DOWNSTREAM
$ kubectl get namespaces -o=json | jq -r '.items[].metadata | "\(.name) \(.labels)"' - | grep cattle-prometheus
cattle-prometheus {"cattle.io/creator":"norman"}
```

```
arvindiyengar: LOCAL
$ kubectl get namespaces -o=json | jq -r '.items[].metadata | "\(.name) \(.labels)"' - | grep cattle-prometheus
cattle-prometheus {"cattle.io/creator":"norman","field.cattle.io/projectId":"p-75jzs"}
```

**Comment by aiyengar2** [comment]
Works in the latest master-head `d7528a2`.

The root cause for this issue is that the namespaces in downstream clusters in master-head only weren’t getting updated with projectIDs.

The [nslabels namespaceHandler wasn’t registered](https://github.com/rancher/rancher/blob/692a9507ebeec70118aa8496999e89d0dfa1cc18/pkg/controllers/managementagent/nslabels/labels.go#L28-L35), which happens when the [managementagent is registered](https://github.com/rancher/rancher/blob/692a9507ebeec70118aa8496999e89d0dfa1cc18/pkg/controllers/managementagent/controllers.go#L34), which happens when [mcmagent is registered](https://github.com/rancher/rancher/blob/880e476a2ca2b82524c8e92994efeeceeec29587/pkg/controllers/dashboard/mcmagent/mcmagent.go#L16), which happens when [dashboard is registered](https://github.com/rancher/rancher/blob/880e476a2ca2b82524c8e92994efeeceeec29587/pkg/controllers/dashboard/controller.go#L50) if and only if [`(features.MCMAgent.Enabled() || features.MCM.Enabled())`](https://github.com/rancher/rancher/blob/880e476a2ca2b82524c8e92994efeeceeec29587/pkg/controllers/dashboard/controller.go#L49).

And MCMAgent was never enabled in downstream clusters till https://github.com/rancher/rancher/commit/aec8ead0f4269d0eb4e2bf60ee83f66e594d3f02 was merged in.

**Comment by slickwarren** [comment]
on master-head (5d49b92f479a00773607fb41fe851f98271148c0) I'm getting a `422 Unprocessable entry` error. Rancher also shows this error, as if it can't check that prometheus-operator isn't already installed: 
```
Failed to ensure prometheus operator app: stale "monitoring-operator" App in p-r58z5 Project is still on terminating
```

<img width="1510" alt="Screen Shot 2021-06-01 at 9 06 28 AM" src="https://user-images.githubusercontent.com/16691014/120355979-af8daa00-c2b8-11eb-9ad8-b50513277fe0.png">

Could this be a result of https://github.com/rancher/rancher/issues/32943 or is this a new issue @aiyengar2 ?

**Comment by aiyengar2** [comment]
@slickwarren this seems like a new issue.

**Comment by slickwarren** [comment]
filed [the blocking ticket](https://github.com/rancher/rancher/issues/32969) for this issue.

**Comment by slickwarren** [comment]
The above ticket appears to only be an issue for RKE2 clusters, so I will test this ticket with other cluster types.  
on master-head (5d49b92): 
* all targets in prometheus appear to be active and a complete list 
* grafana now has stats for all applicable metrics

tested on RKE1, k3s, and hosted EKS Cluster types.
