### ISSUE TITLE
[Monitoring V2] Add pushprox for kubelet and node-exporter

### ISSUE THREAD

**Issue by dbason** [rancher/rancher#32841]
Raising RFE for this as per the discussion in https://github.com/rancher/docs/issues/2493#issuecomment-790963731.

Node-exporter runs on the hostNetwork by default so we will need a pushprox to avoid opening ports to all nodes.  Kubelet is also monitored so we need a pushprox for that one.

gz#15946

**Comment by aiyengar2** [comment]
Needs a UI issue attached to it to expose these options on the UI.

**Comment by sowmyav27** [comment]
@aiyengar2 @gaktive @nwmac Do we need [this](https://github.com/rancher/dashboard/issues/3095) UI issue to be fixed for this issue ? I see the UI issue is in 2.6.x milestone.

**Comment by dbason** [comment]
> @aiyengar2 @gaktive @nwmac Do we need [this](https://github.com/rancher/dashboard/issues/3095) UI issue to be fixed for this issue ? I see the UI issue is in 2.6.x milestone.

Nope, the way the push-prox exporters are structured they are optional extras for a hardened environment.  I don't think we need any additional UI elements.  I'll close out the issue

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head e83ac8c` with `rancher-monitoring-100.0.0+up16.6.0` deployed on custom RKE2 cluster with k8s `v1.21.2+rke2r1` and on RKE1 with k8s `v1.20.7-rancher1-1`

chart repo commit: `375fdb1a74e2bb1418e8d03d7831c76c679883a7`

**prometheus-node-exporter**
* pushproxy is used by default
* I see that for scraping following metrics a pushprox-client is used - the output was taken from one of the `rancher-monitoring-prometheus-node-exporter*` pod processes:
```
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-scheduler-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10012 --allow-port=10251 --use-localhost
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-proxy-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10013 --allow-port=10249 --use-localhost
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10011 --allow-port=10252 --use-localhost
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-etcd-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10014 --allow-port=2381 --use-localhost
```
* corresponding `pushprox-kube-*-proxy*` pods are running
* all the metrics above are healthy (and listening on public ip of the node over endpoint) in Prometheus Targets view

**kubelet**
* pushproxy must be enabled first for kubelet eg. by setting `hardenedKubelet.enabled: true` in values (otherwise it scrapes the metrics directly from kubelet container over hostNetwork which has similar result - both are on public ip)
* then the pods `pushproxy-kubelet-client*` (DS)  and `pushprox-kubelet-proxy-*` (1 RS) are deployed
* this is pushprox-client process taken from one of the pushprox-kubelet-client*` pod:
```
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kubelet-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10015 --allow-port=10250 --use-localhost --insecure-skip-verify --token-path=/var/run/se
crets/kubernetes.io/serviceaccount/token
```
* The metrics from kubelet are healthy in Prometheus Targets view

This is example of the metrics targets (kubelet and kube-scheduler form node-exporter) with pushprox labels:
![pushprox](https://user-images.githubusercontent.com/12828077/125806147-0460bcaa-cf47-4d5e-844d-c05eb54bd0ec.png)

I'd say it works as expected. Close.
