### ISSUE TITLE
Public port displayed in UI points to Docker IP, not Host

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#3285]
![image](https://cloud.githubusercontent.com/assets/13985506/12340518/536e06fc-bae9-11e5-9272-99b3ed1e7277.png)

In the last version of the UI, the public service port (within a stack) linked to directly to my Host IP (in my case, the IP of the VM e.g. 192.168...).  Now it is pointing to the Docker IP (172.17...), effectively making the link useless.

**Comment by vincent99** [comment]
The links are to the public IP the host is registered with.

**Comment by deniseschannon** [comment]
If you go to your host page, is the host that the container on showing the DockerIP instead of the hostIP? Your host has registered and picked up the Docker IP instead of the actual IP of the agent. 

You'll need to re-register your agent and add the environment variable `-e CATTLE_AGENT_IP=<ip>` to the rancher/agent command.

**Comment by dsvmacdonald** [comment]
You are correct.  I had some automation scripts that were recently updated and broke setting the cattle_agent_ip properly.

Thanks for your help!
