### ISSUE TITLE
[monitoring v2] Prometheus/Grafana is missing metrics for some workload types

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#32896]
While working through https://github.com/rancher/dashboard/issues/2678 I noticed that grafana only had metrics for several workload types.

I checked Prometheus and it looks like it's also missing some of the workload types.
![image](https://user-images.githubusercontent.com/55104481/119721941-9dc38700-be20-11eb-87d0-c89ed2d71925.png)

We should also see metrics for:

- DEPLOYMENT:             'apps.deployment',
- CRON_JOB:               'batch.cronjob',
- REPLICATION_CONTROLLER: 'replicationcontroller'

@slickwarren also noticed that even though the jobs are in prometheus but not in grafana.

**Comment by aiyengar2** [comment]
@slickwarren @codyrancher I don't think this is an issue.

As seen below in Rancher 2.5.8, when I deploy a ReplicationController, the metrics are collected as expected.

![Screen Shot 2021-06-02 at 5 54 50 PM](https://user-images.githubusercontent.com/13127443/120569855-a3464180-c3cb-11eb-8231-c2f67daee582.png)

w.r.t. CronJobs and Deployments, both of those manage Jobs and ReplicaSets under the hood (respectively). That's why they don't show up in kube_pod_info under `created_by_kind`, since the resource that actually created the Pod was the underlying Job / ReplicaSet.

Moving this issue back to test so we can confirm that:
1. ReplicationController metrics are collected, as show in the screenshot above, in master-head, 2.5.8
2. CronJob metrics are collected via Job metrics (you can test this by constructing a PromQL query based on `created_by_name`) in master-head, 2.5.8
3. Deployment metrics are collected via ReplicaSet metrics (you can test this by constructing a PromQL query based on `created_by_name`) in master-head, 2.5.8

**Comment by aiyengar2** [comment]
@codyrancher correct me if I'm wrong, but this does seem like a separate bug for UI since you wouldn't be able to embed any dashboards for Deployments or CronJobs due to the fact that Grafana dashboards won't be populated for them right?

Would it be possible for UI to embed the individual dashboards for each ReplicaSet / Job managed by the Deployment / CronJob, or do we need dashboards specifically for Deployments / CronJobs that collect summary metrics across all related resources?

**Comment by kravciak** [comment]
1. Works fine, I verified by:
- deploy DO infra provider cluster (1 pool, 3 nodes, all roles selected)
- deploy ReplicationControlled in default namespace
(https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#running-an-example-replicationcontroller)
- deploy monitoring v2 (100.0.0+up16.6.0)
- open monitoring -> Prometheus Graph
- enter expression `count(kube_pod_info) by (created_by_kind)`
- check that list contains `{created_by_kind="ReplicationController"}`

2. create CronJob in default namespace
(https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#creating-a-cron-job)
- `count(kube_job_created) by (job_name)` returns names of jobs created by CronJob

3. create Deployment indefault namespace (nginx:alpine image)
- `count(kube_replicaset_created) by (replicaset)` shows created deployment
