### ISSUE TITLE
ipsec network qps limited to 2000?

### ISSUE THREAD

**Issue by coregear** [rancher/rancher#3290]
I have runed times of below tests if different environment, but single instance's qps seems to limited to 2000. It's that a issue? and Can I turn up the limit?

host A webbench > host B rancher lb > host C app(static page). and host B and C in a rancher managed network.

./webbench -t 10 -c 150 http://xxx.com:8100/
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://xxx.com:8100/
150 clients, running 10 sec.

Speed=122718 pages/min, 4763271 bytes/sec.
Requests: 20453 susceed, 0 failed.

122718/60s = 2045 pages/sec

**Comment by deniseschannon** [comment]
@coregear We just updated our managed network to use charon instead of racoon. If you aren't using CoreOS, please consider looking into upgrading and seeing if you have the same issue. 

Also, please read the full release notes on the notes for this refactoring.
https://github.com/rancher/rancher/releases/tag/v0.56.0

If you still have this issue, please re-open.
