### ISSUE TITLE
[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy - after one year of running rancher in docker

### ISSUE THREAD

**Issue by klauskobald** [rancher/rancher#32901]
**What kind of request is this (question/bug/enhancement/feature request):** 
bug ?
Allthough I see similar issues here on github I was told on Slack to post this as a new Issue.

**Steps to reproduce (least amount of steps as possible):**
I installed a 3 node cluster with rke one year ago. (1 master, etcd, worker and 2 worker)
On one extra Server I installed the docker version 2.4.x of rancher
```
sudo docker run -d --restart=unless-stopped  -p 80:80 -p 443:443  -v /root/rancher-data:/var/lib/rancher rancher/rancher:v2.4...
I then added the nodes with the given rancher-agent:v2.4 register command 
```
After turning off Prometheus I could get it to run smoothly. (It´s only a tiny server with 4GB and 1cpu)

**Result:**
Short: 
Rancher cannot manage working cluster anymore (but Cluster is working fine!)

Long:
Everything worked till a month ago. From then on Rancher was not responding anymore (white page). I remember x509 certificate errors all over the place when looking int to some logs.
I do not have these logfiles anymore, but it was the same errors I am still getting now after updating everything.
This is a line from the etcd pod of the master node:
```
 I | embed: rejected connection from "95.****:60644" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")", ServerName "")
```

**Other details that may be helpful:**
I updated rke to the latest (a few days ago).
I installed rancher 2.5.8 with docker and get the app running again. (webpage showing up).
The Cluster entry is still there with state "unavailable"
So I thought to  add a new empty cluster is a good idea and used registration commands provided by rancher.
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.5.8 --server https://rancher.MYSERVER.com --token kvzv7mzfz6chbfbm7wfkkgt4vnvrvllxpt6nj6gdkgkrqwlfwfc5xd --ca-checksum 69f5b43080eee456cf91878e2f023266edf28283c21375b1c3a90f35282e8129 --etcd --controlplane --worker
6d87e3079bd112ae1c5aa35db30a38287212d52661404c40e3a1ec9c7899b39c
```
But after a while it shows
[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [95.*****] failed to report healthy. Check etcd container logs on each host for more information.
The logs show them same x509 error as above.

I tried rke cert rotate on CLI and also via the web interface.
I also tried copying the files from /etc/kubernetes/ssl to /etc/kubernetes/.tmp
But nothing changes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
```
Rancher | v2.5.8
User Interface | v2.5.8
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher55
```
- Installation option (single install/HA):
docker

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Hetzner VMs
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by superseb** [comment]
We need some clarifications as there are too many gaps in the information:

* `I installed a 3 node cluster with rke one year ago. (1 master, etcd, worker and 2 worker)`, this means 1 controlplane, 1 etcd, 1 worker or 3 worker? Also exact version used helps here.
* `On one extra Server I installed the docker version 2.4.x of rancher`, so this was a node solely used for running Rancher using Docker?
* `I then added the nodes with the given rancher-agent:v2.4 register command`, on what nodes did you run this? Because the nodes mentioned so far are already in a cluster (the cluster created with RKE)
* `After turning off Prometheus I could get it to run smoothly. (It´s only a tiny server with 4GB and 1cpu)`, what requirements stated that his was enough to run this? We document requirements at https://rancher.com/docs/rancher/v2.x/en/installation/requirements/
* `I installed rancher 2.5.8 with docker and get the app running again. (webpage showing up).`, did you use the same volume as the old install (so its an upgrade and you would keep all your config/clusters etc) or did you create a whole new install?
* `So I thought to add a new empty cluster is a good idea and used registration commands provided by rancher.`, this makes sense but again the question would be, what nodes are you using for this? Nodes that are being reused need to be cleaned before re-adding as files on the nodes conflict with each other. You can't just have an old cluster node with files from a previous cluster and add it to a newly created cluster.

In general I think most of your issues would be solved if you would use the HA Install where you have a dedicated cluster with Rancher and where you can manage etcd snapshots containing a state of everything at a certain point, so if something blows up, you can easily restore this snapshot and get back into a good state (this is like max 5 minutes to restore), or use the backup-operator in 2.5. If you really want to stick with the Docker install, most likely you would have been good by restoring a backup made before the issue appeared. You can find more info on https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/ (for both 2.5 and pre-2.5, and single and HA installs)

**Comment by klauskobald** [comment]
Answers:
it´s 3 servers: 1 has all roles, 2 have worker roles
yes, it is one server dedicated to rancher only
Rancher says: I have to run the registration command on all existing nodes of the cluster - that´s what I did
I do not see the requirements or lack of memory as an issue here. (it never was!)
To make things clean:  right now I created a blank new rancher server with Ubuntu 20, installed docker and ran the rancher container script. So, new server is up and running. Web Interface is working.

But I get the same errors as before when adding the existing cluster. Log of etcd of master node:
```
2021-05-30 18:16:06.680002 I | embed: rejected connection from "95.216.*.*:36782" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")", ServerName "")
(repeating endlessly)
(ip address 95.216.*.* is the ip from the master node)

```
You are stating:
_Nodes that are being reused need to be cleaned before re-adding as files on the nodes conflict with each other. You can't just have an old cluster node with files from a previous cluster and add it to a newly created cluster._

That makes sense! I was trying to use this script to remove rancher components from the cluster
(https://github.com/rancher/rancher/blob/master/cleanup/user-cluster.sh)
```
./user-cluster.sh -dry-run rancher/rancher-agent:v2.5.8
```
but that ended up in a 
```Error from server (BadRequest): container "cleanup-agent" in pod "cattle-cleanup-job-sx9j7" is waiting to start: InvalidImageName
```

So, if you could tell me how to put a "ranchered" cluster into a state without rancher, maybe that would be a good start?
