### ISSUE TITLE
Replace go-version with a library that handles prereleases correctly in catalog rancher check

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#32930]
ValidateRancherVersion needs to be updated to use Masterminds/semver (or another alternative library) as go-version does not follow proper semver when comparing pre-releases

**Comment by jakefhyde** [comment]
### Root cause
 
The `go-version` library does not perform proper handling of prereleases. The ordering as per the semver spec is as follows:
```
1.0.0-0 < 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0
```
`go-version` appears to order `-0` before `-alpha`, i.e. numeric prerelease identifiers are given precedence over alphabetical.

### What was fixed, or what changes have occurred

The version range checking library to determine if catalogs are valid was replaced with [`blang/semver`](https://github.com/blang/semver).
 
### Areas or cases that should be tested

Installing and upgrading charts should list the exact same values as before.
 
### What areas could experience regressions?

Improperly formatted version ranges may cause specific charts to no longer show up. For example, a chart with the following values:
```
rancher_min_version: 2.6.4-alpha1
rancher_max_version: 2.6.5-0
```
for `server-version == v2.6.4` would validate with `go-version`, and fail with `blang`. 

Prerelease rancher versions should now actually work correctly, as before a chart with the following values:
```
rancher_min_version: 2.6.4-0
rancher_max_version: 2.6.4
```
for `server-version == v2.6.4-rc1` would have also failed, although we have not utilized a chart with such constraints.

To the best of my knowledge, we have no charts installable with `v2.6-head` that would be subject to either of these possible regressions, but it would be entirely possible for someone to misinterpret the semver spec and assume that `v2.6.5-0 >= v2.6.0`, especially since some libraries like `go-version` seem to reinforce this incorrect behavior.

### Are the repro steps accurate/minimal?

When launching `rancher/rancher:v2.6-head`, the environment variable `CATTLE_SERVER_VERSION=v2.6.3` will allow verification that the exact chart versions for `v2.6.3` are available, as otherwise they would all show up. Additionally, this environment variable can be used to set an `rc` version, or a custom tag. The list of available charts to install and upgrade should be the same.

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 
Rancher cluster type: single-node docker install 
Docker version: 20.10

Semantic versioning info (semver): https://semver.org/

Chart for testing: https://github.com/sgapanovich/test
-the personal chart was used so it's easier to test different `catalog.cattle.io/rancher-version` values

Command to pull latest image BUT use a specific rancher server version:
-`docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_SERVER_VERSION=v2.6.3-rc2 rancher/rancher:v2.6-head`

----------

### Testing: ###

During testing `2.6.3-rc2` rancher server I noticed that if a chart's `catalog.cattle.io/rancher-version` equals or includes `2.6.3` the chart will appear in Rancher

![hmmm](https://user-images.githubusercontent.com/40282141/153314044-cea4fc97-4247-4698-9c4a-bd01741544fa.jpg)




Based on semver spec: 2.6.3 comes after 2.6.3-rc2 so it should not be shown 

Is it expected? If yes, I will need a list of exception because from my point of view if we try to comply with semver I should not see a chart in the case above


@jakefhyde @aiyengar2 


testing notes (testing in progress)

![present](https://user-images.githubusercontent.com/40282141/153313622-579e1351-4276-468b-8d67-2939a89e2ff8.jpg)

**Comment by sgapanovich** [comment]
testing continued. 2.6-head 11a7451

behavior above is expected since `2.6.3-xx` server is treated as `2.6.3` (see issue https://github.com/rancher/rancher/issues/36120)

the rest of test cases 
![notes](https://user-images.githubusercontent.com/40282141/153971592-0c7b2532-1072-4efb-a206-fbca87c6032a.jpg)
