### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by qdrop17** [rancher/rancher#32965]
**What kind of request is this (question/bug/enhancement/feature request):**
There is an inherent conflict between the official latest documentation and Rancher itself:

https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/production/recommended-architecture/ states:

_**In either case, the worker role should not be used or added to nodes with the etcd or controlplane role.**_

while Rancher itself states:

_**The cluster needs to have at least one node with each role in order for Rancher to finish provisioning.**_ 

![grafik](https://user-images.githubusercontent.com/42340241/120332130-b9ca9b00-c2ee-11eb-9d7a-c89dfae4a81e.png)

... when trying to provision a node with just certain roles activated.

That circumstance raises some questions:

- I interpret, that it's not possible to get any cluster alive, without having at least one specific node with all roles activated - correct?
- What's the actual best-practice for now to deploy a Rancher cluster? Isolating roles / nodes or running all roles on couple of nodes?

We highly appreciate any clarification on that matter.

Best

Thomas

**Comment by vincent99** [comment]
Each role has to be running _somewhere_. If you don't have a database, you can't have a cluster because there's nowhere to store data.  With no control plane there's no API to talk to.  With no workers there's no nodes to run regular workloads on (such as the agent that runs to connect the cluster up in to Rancher).

So just to have anything work at all, you can have roles in any combination.  You can have one node and have it perform all three roles;  This is relatively common for tiny clusters of one. You can have 10 nodes as 5 etcd, 3 control, 92 worker.  That's the 2nd quote.

The first quote is about what's _recommended_ for non-toy installations.  There are various reasons why having an individual node perform multiple roles is not the best idea, so it is not _recommended_; but it is still _possible_.

**Comment by qdrop17** [comment]
Yeah, I understand this. But this leaves us with the following issue: We were not able to provision a Rancher cluster with 1 etcd / controlplane (only) node and 3 worker (only) nodes. Rancher never finished provisioning and failed bringing this cluster up. In the moment we had one node with all (each?) role(s) activated, Rancher finished provisioning the cluster.

This brought us to this interpretation.
