### ISSUE TITLE
AKS KEv1 should use region call from KEv2

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32967]
AKSv2 has added metadata around the region calls, we should backport this to kev1. This will require us moving code out of internal dir. 
This will need to be QA'd for KEv1. 

PR:
- [x] https://github.com/rancher/aks-operator/pull/9/files

Bacport to AKSv1:
- [x] https://github.com/rancher/rancher/pull/32985

**Comment by mjura** [comment]
With backporting `CheckLogAnalyticsWorkspaceForMonitoring` from AKSv2 to AKSv1 it will be more problems because there are some custom changes for example in function header
`func CheckLogAnalyticsWorkspaceForMonitoring(ctx context.Context, cred *Credentials, client *operationalinsights.WorkspacesClient, spec *aksv1.AKSClusterConfigSpec)`
and AKSv1
`func (d *Driver) ensureLogAnalyticsWorkspaceForMonitoring(ctx context.Context, client *operationalinsights.WorkspacesClient, state state) (workspaceID string, err error)`

**Comment by cbron** [comment]
Need to test AKSv1 calls here.

**Comment by prabalsharma** [comment]
@cbron whats the test case here? 
Check if location list on AKSv2 is same as on AKSv1 (2.5-head)?
Also should the milestone be 2.5.10?

**Comment by prabalsharma** [comment]
I could see list of locations for AKS v1 on 2.6
<img width="972" alt="Screen Shot 2021-07-16 at 12 35 30 PM" src="https://user-images.githubusercontent.com/3749546/125999915-ac0fc38e-02ed-47c2-9787-ad0b76de47cc.png">
