### ISSUE TITLE
aksv2 - UI should show AZs only for supported regions

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33019]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
UI should show AZs for only supported regions. Eg:
UI shows AZs 1, 2 and 3 for westus, which is not correct. 

**Result:**
`Error failed to create cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="AvailabilityZoneNotSupported" Message="Availability zone is not supported in this region." Target="agentPoolProfile.availabilityZone"`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
@prabalsharma I'm not sure how we want to support this functionality. Currently the UI keeps a list of locations that support availability zones but I could not find a list of what AZ are available in each location. It looks like there may be a small bug with this logic because if a location is selected without zone support the radio buttons should be disabled and un-selectable. 

That being said I still think we're still going to run into issues because some locations don't support ALL zones from what I understand. We currently do not have an API to fetch the availability zones nor am I sure that one actually exists. I dug around a bit looking for an API that would do this and it seems there may be some way to do this from the CLI but I could not find any other info actual rest APIs. 

@mjura is there any way for you to fetch the availability zones for a location? Even better would be adding the availability zone to the locations call but I'm not sure that's possible?

**Comment by prabalsharma** [comment]
>  It looks like there may be a small bug with this logic because if a location is selected without zone support the radio buttons should be disabled and un-selectable.
> 

My bug is for this ^ : AZ buttons not getting disabled for Regions which do not support AZs

> That being said I still think we're still going to run into issues because some locations don't support ALL zones from what I understand. We currently do not have an API to fetch the availability zones nor am I sure that one actually exists. I dug around a bit looking for an API that would do this and it seems there may be some way to do this from the CLI but I could not find any other info actual rest APIs.
> 

I was not able to find a region which supports partial AZs (either a Region supports all 3 AZs or none). Do you have an example of a Region which supports a subset of AZs 1, 2 and 3?

> @mjura is there any way for you to fetch the availability zones for a location? Even better would be adding the availability zone to the locations call but I'm not sure that's possible?

**Comment by westlywright** [comment]
I was not able to find a region which supports partial AZs (either a Region supports all 3 AZs or none). Do you have an example of a Region which supports a subset of AZs 1, 2 and 3?
@prabalsharma I think I may have misread or seen something early on in dev because I couldn't find one either. If this ticket is solely for the radios not being disabled then I will move this. The change for that went in with rancher/ui#4648

**Comment by prabalsharma** [comment]
tested on master-b2f8824
