### ISSUE TITLE
Backport 2.5: Rancher-monitoring installation fails on fresh cluster with crd error

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33014]
Backport fix for https://github.com/rancher/rancher/issues/32827

**Comment by snasovich** [comment]
@brendarearden or @jiaqiluo , same as https://github.com/rancher/rancher/issues/32827

**Comment by jiaqiluo** [comment]
the fix is validated in rancher v2.5-head 0713103 with Monitoring v2 chart `16.6.0`

Steps:
- run rancher in single-install mode 
- provision multiple RKE clusters with various k8s versions and number of nodes 
- install monitoring v2 into the cluster via the cluster explorer UI

Results:
- monitoring is installed successfully without hitting the error mentioned in the issue
