### ISSUE TITLE
aksv2 - should be able to select AZs for User Mode NPs, if available for selected region

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33021]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
Right now, NPs gets AZs from whatever is selected by user in "Cluster Location", which is fine for System Mode NPs. However for User Mode NPs, it will be nice if user is given an option to choose from list of AZs selected in Cluster Location step.

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
This required some tweaks to the UI. I removed the AZ's from the section next to the region selection. Since it really ties to the node pool I think its less confusing to select the AZ's per node pool instead of trying to keep the on selection next to the region and also add it to node pools when adding a new one.

**Comment by prabalsharma** [comment]
tested on master-b2f8824
