### ISSUE TITLE
aksv2 UI - is not showing added cloud credential when creating a cluster

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33148]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. deploy master-3d465ee7cc5afbea762e328affbb76e88ebd3229-head
2. delete existing Azure CCs
2. Add Azure cloud credential
3. Add cluster
4. You will not see the added cloud credential.

**Result:**

**Other details that may be helpful:**
I can see added cloud credentials in drop down while creating AKS cluster, only if number credential is more than 1.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
This should be automatically handled by the UI store via change events on the web socket. Since we load all the cloud credentials when we first hit the create cloud cred page we don't refetch them (unless the dev specifically forces a refetch) because the UI store will automatically update the resource (and its availability) in response to the WS change event. Since this isn't happening and I don't force a refetch of the cloud creds when you hit the cluster launch page, we don't see it in the drop down. Seems to be related to [this web sockets](https://github.com/rancher/rancher/issues/32972) issue. The global web socket is not pushing the updates to resources. I believe that once the WS issue is fixed this will all work correctly again. 

Tested on `v2.5-head`:
Create Azure Cloud credential while viewing the the messages from the `v3/subscribe?sockId=1` web socket via dev tools.
You'll be able to observe the change event to the newly created cloud credential. 


Tested on `master-6b430f31afb9cfc5493f686279a97dd79c54ad88-head`:
Create Azure Cloud credential while viewing the the messages from the `v3/subscribe?sockId=1` web socket via dev tools.
No change events are received for the newly created CC.

cc: @gak

**Comment by prabalsharma** [comment]
I am closing this, as the underlying issue is being tracked separately as mentioned by Wes.
Also, this issue is only for old UI which is not longer relevant.
