### ISSUE TITLE
Change usage of github.com k3s location from "rancher/k3s" to "k3s-io/k3s"

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33223]
This issue applies to modules, docs, etc. in this repository.

CC: @davidnuzik

**Comment by davidnuzik** [comment]
+1 to this. Not a high priority in my opinion, but I think we should try to fix this because it should be a simple matter of find and replace all and test. Right now we are relying on GitHub redirects and it's possible this could break later or expire? Not sure on that, but I would just feel better fixing this properly.

**Comment by brandond** [comment]
Docs and such should definitely change, but for modules we have put off changing go.mod within k3s, so it'll need to be handled with replace entries for the time being - which isn't great.

https://github.com/k3s-io/k3s/blob/master/go.mod#L1

**Comment by nickgerace** [comment]
I hear you loud and clear, stalebot, let's keep the conversation going.

**Comment by brandond** [comment]
That should keep stalebot off our back...

**Comment by maknop** [comment]
Could I snatch this issue? I'd like to give it a try.

**Comment by brandond** [comment]
https://github.com/k3s-io/k3s/pull/4846
