### ISSUE TITLE
Ability to allow load balancers to target a sidekick service 

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3322]
When defining a link to another container -- such as when defining a Load Balancer -- you are unable to select a sidekick container.  Since sidekicks have different IP addresses to the main container, this means that ports opened by a sidekick cannot be routed to by a load balancer (though they can expose ports to their host).

Particular usecase:

App container has nginx proxy container as a sidekick that performs authnz (different sidekicks available depending on how you want to auth).  It must be a sidekick as it uses volumes_from to mount a config directory exported by the appcontainer.  Nginx proxy adds authentication and listens on port 80.  Load balancer should be able to listen on known IP and forward to nginx container (which then proxies to app container) but in Load Balancer config you cannot select the sidekick container.

**Comment by RVN-BR** [comment]
I'm a little bit unsure about the best way of doing this...  The notion of "sidekicks as lesser services" may not work out well for a bunch of use-cases...  

In your case @sshipway maybe the best is to invert and make the app container the sidekick to your nginx proxy? If I'm not mistaken it should work as you expect that way...but I'm not 100% sure, so you'd have to give it a try...

**Comment by sshipway** [comment]
The problem with inverting the order (making the main container the sidekick) is that it conceals the status of the main container, and sets the wrong precendence.

I would rather that the sidekicks appear in the service selector the same way as any other service; alternatively, I'm not really clear why 'volumes_from' is denied apart from between sidekicks.  Possibly because sidekicks are 1-to-1 and otherwise it might be unclear as to which container (of a larger scale one) to mount from?  If this is the case, then maybe add a 'one instance max' option to Rancher services, and allow volumes_from to mount only from sidekicks or services with this flag.

Sidekicks could be very useful for things like ephemeral shared config filesystems, or for adding features to existing standard containers (such as, in this case, adding authnz over the top of a web service); however their invisibility to Load Balancers is a problem.

**Comment by RVN-BR** [comment]
I see @sshipway .... Yeah the status becomes hidden if you move the service to sidekick.  From what I could gather sidekicks are indeed 1-to-1, and even if you scale a service on the same host it will create other copies of the sidekick...  In the current setup it wouldnt make much sense as ephemeral storage, since each container gets its own copy, and its not being shared...

Also, unless these settings are host-specific, you could perhaps use a convoy shared FS for these?  Just an idea... but still, if its for readonly data, the only option is to keep duplicating the sidekick for each service...not really ideal in some situations...

I'm starting to think abt just bundling the Server & Files into a single image to get away from the sidekicks all together... if they arent shared across the same host, and cant be "upgraded" in place, I dont see much gain.... It takes longer to spinup with sidekicks, and there isnt really a tangible benefit for me anymore...  It'll just be adding folders to the containers and thats that...

If you need de facto shared data between two containers (and not just 1 container reading from 1 data container), then something else needs to be used or changed in rancher

**Comment by sshipway** [comment]
Unfortunately, I have yet to manage to make Convoy work at all - neither Glusterfs not NFS - despite having upgraded to the latest Rancher, latest CoreOS and Docker 1.9.1 everywhere.  So Convoy is out.

I'm trying to use off-the-shelf containers for the main thing, with their configs being supplied by a microcontainer, or with additional authnz being provided by a sidekick, agains configured by a microcontainer.  These would ideally use the volumes_from to mount the config filesystem, since there may be multiple stacks that need separate configs and so I can't use the same mount.  However with the way Rancher works, volumes_from is almost useless.

**Comment by beatcracker** [comment]
+1 on this. It seemed so natural, so I was very surprised when I found that this can't be done.

**Comment by tmiklas** [comment]
+1 here as well... Even if you don't need to scale the service (and clone sidekicks alongside main container) then it becomes a pain. 

Example - mongo and mongo-express as sidekick, I want only one, but don't want to have sidekick running  if mongo itself is down, so having mongo-express as sidekick works great... however - as things stand I'm forced to expose mongo-express port on the host to access it directly on the host.
You can't even map the host exposed port on the LB, nor the one exposed by the container internally, so this is completely inaccessible.

**Comment by EugenMayer** [comment]
Also missing this for my usecase. I sidekick a FPM container, main container is an nginx - but i also need a SSH connection to the FPM container, and thats where this all fails using a sidekick.

I am using a sidekick because of "volumes_from"

**Comment by vincent99** [comment]
You can so this by having the Sidekick share the network namespace with the main container instead of having its own.  (A pod is always a single network namespace in k8s, so it will always work this way in 2.0)

`network_mode: container:nginx`

Where nginx is the name of the primary container/the service.  I don't remember if the UI lets you set this up or not so you may have to use compose.

**Comment by Rakhmanov** [comment]
@vincent99 
It does not have this option in UI, not on edit stack not on create.

**Comment by Anonymous-Coward** [comment]
Just encountered this, as I was looking for more details about sidekicks, investigating the possibility to use the sidekick mechanism to run a sidecar along each service.

Seems to me most people commenting above need support for a sidecar, not a sidekick. The difference, as I see it: sidekicks are meant to provide help to the service they are attached to, whereas sidecars are meant to sort of wrap/mediate access to the service they are attached to.

Would be nice to get some feedback from rancher devs about the difference from rancher's point of view/intention to support each mechanism differently.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
