### ISSUE TITLE
Upgrading an S3 build fails. Subsequentely canceling the upgrade brings the service/stack down...

### ISSUE THREAD

**Issue by RVN-BR** [rancher/rancher#3325]
Hi,

When trying our Rancher with S3 builds I have an issue whenever I try to upgrade a service.  After issuing an "up --upgrade" command on an existing stack, Rancher marks the service(s) as Upgrading and tries to launch new containers, however the new containers are erroring out with this message: Removed ( : xxxxxxx-xxxxxxx-4909-8c7e-cdd034990741 : 500 Server Error: Internal Server Error ("Error detecting content type for remote https://xxxxxx-xxxxxxxxxx.s3.amazonaws.com/nginx-static-files-xxxxx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxxx%2F20160119%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160119T171001Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxxx: unsupported Content-Type "binary/octet-stream""))

If I click on "Cancel upgrade" it seems to keep the current service up, *but then* when I click on "finish upgrade" it deletes the original service and takes the stack offline (in this case, as the container in question is the entrypoint to the LB)...

There appears to be two isolated issues, one in regards to the pull from S3, and another one that when an upgrade is canceled, it should mark the *existing* service as the service to keep, and not delete it when clicking on 'finish' (its debatable whether a canceled upgrade should even be "finished", since its technically not gone to another service yet?)...

EDIT: fyi the service stays "Finishing Upgrade" forever, or at least for an extremely long time... At this point it has failed deploying the new containers, and deleted the old containers, therefore effectively "breaking" the stack.  In order to restore things I need to delete the stack and recreate... 

Thanks

**Comment by deniseschannon** [comment]
The first part of your issue is a duplicate: https://github.com/rancher/rancher/issues/2666

When you say "click on cancel upgrade", it sounds like you are trying to cancel the upgrade through the UI. We haven't expected users to go between rancher-compose and UI during upgrading. If you are to use `rancher-compose up --upgrade`, then we have only tested to be able to use the commands to finish the upgrade or rollback. I think a Ctrl+C would cancel the upgrade in rancher-compose.

**Comment by RVN-BR** [comment]
You are correct, it is indeed a duplicate... my bad...  Ctrl-C didnt cancel the upgrade in this case... it continued trying to launch containers and erroring out on them as per the other issue... which is why I clicked on the options in the UI...  

I just made a little test deploying a simple container from an image.  I then noted the container IP (X), and triggered an Upgrade from the UI, then cancelled the upgrade.  I see that rancher stopped the container with IP X, and is starting a new one with IP Y.  As I canceled the upgrade, I'd expect it to stop the new (IP Y) container and remain on the original one...  It doesnt.  The UI shows Canceled-Upgrade
![image](https://cloud.githubusercontent.com/assets/1218902/12427931/07346266-bec9-11e5-8760-da103f4f0b47.png)
At this point it started the new container and stopped the original one: 
![image](https://cloud.githubusercontent.com/assets/1218902/12427958/27385efa-bec9-11e5-8807-d0e27f5310de.png)

If I click Finish upgrade it maintains the container it launched... If I click "Rollback", it launches a new container with the old image...I'm unsure if Rancher is caching the 2 versions of the image if the image doesn have a specific version or is using a tag like :latest or something...

I tried using the same image, always with the "always pull image" option selected, and also tried with two different versions of the image, the difference I observed was in the rollback command... effectively it seems "Cancel upgrade" isnt really cancelling it, its going through with it...

I also tested it with the "start before stop" option and even if I cancel the upgrade before the new container comes up, it still brings up a container with the new image (if different) and stops the running container, again not canceling the upgrade but going through with it?...

Perhaps this is the desired behavior, and after a Canceled upgrade I should be "rolling back" instead of "finishing"? It seems to me that a canceled upgrade shouldnt be upgraded as is happening right now tho...

**Comment by deniseschannon** [comment]
"Finish upgrade" implies that you are doing exactly that. You are finishing the upgrade that you had already started (regardless if you are in a cancelled state or upgraded). 

"Rolling back" means you are going back to whatever you had originally selected.

As for the images, if you use `latest`, there's no way to officially "rollback" to the old image as there is no place to pull it back down from. We don't have a cache of the images anywhere, it's whatever gets stored on the host. This is why we tend to recommend not to use latest and use specific versions. :)

I'm closing as the origin of this issue is a duplicate.
