### ISSUE TITLE
Keycloak OIDC - Cluster owner can't search for users to add as cluster members 

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33356]
**What kind of request is this:**
bug

Related to: 
- https://github.com/rancher/rancher/issues/33352
- https://github.com/rancher/rancher/issues/30280

**Steps to reproduce:**

- Enable Keycloak OIDC
- Allow all valid users to login
- In a downstream cluster navigate to the Cluster -> RBAC -> Cluster Members
- Add a Keycloak user as Cluster Owner
- Login as the User added as cluster member, the user should be able to login and see the Downstream cluster after login
- In a downstream cluster navigate to the Cluster -> RBAC -> Cluster Members
- Click Add in the Members area and start searching for users

**Result:**

`500` is returned from the backend:

`https://<host>/v3/principals?action=search`
`{"baseType":"error","code":"ServerError","message":"unexpected end of JSON input","status":500,"type":"error"}`

**Expected Result:**

The Cluster Owner should be able to search for users and add them as Members/Owners of a cluster.

**Other details that may be helpful:**
And I confirm this is working using the admin principal.

**Environment information**
- Rancher version: `2.6 master-head (06/23/2021)` _d44698d_ 
- Installation option: HA RKE1

**Comment by brendarearden** [comment]
@izaac I have added a PR to address the error that is being returned because the error is not returning correctly. We can keep 1 of the issues open to track the error message change but we can close https://github.com/rancher/rancher/issues/33356. The behavior of the cluster owner and cluster member not being able to search is expected if they do not view/list level permissions for those resources in keycloak. Since we are getting the access token from keycloak and using that for the api calls there is nothing else we add or should be adding for user search to work as desired for this provider. While other providers might have different ways of setting this permission, for this provider, if they do not have that permission in keycloak, they will not have that permission in rancher. 

Admin level privileges can be added to a user by going to the user in keycloak >> edit / create user  >> go to the role mappings tab >> in the client-roles drop down select realm-management >> add `view` permissions >> save permissions and that should be enough for the search call to return values.

**Comment by brendarearden** [comment]
After talking with @dramich  and @prachidamle, it appears that there are two approaches to how we have handled search functionality with our other providers:

1.  Use the credentials from the user that is currently logged in to perform the search. (this is what keycloak oidc is doing currently. Github is another provider that is doing this)
2. Create a ServiceAccount with the admin level credentials and utilize that for all searches. 

Currently I am planning on sticking with option 1 and documenting that Keycloak administrators will need to add `view & get` permissions for all users that they want to be able to utilize the search functionality. Option 2 does provide an easier End User experience because the additional changes to users is not needed in Keycloak.

A third option could also be possible - where we do a hybrid approach of oauth and saml search results:  if the user does not have permission to search, we return a similar principal result to what SAML is doing so that at least something is returned. Thoughts on this? 

I have reached out to the original support team member to get their perspective on this design decision to ensure that they are prepared to support it. Once we hear back, we can make final adjustments as needed and either move this back to working to add the ServiceAccount or close after testing the error message change.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/01/2021)` _c1151f6_

I was able to search for users and add them as cluster members after adding the proper roles to the user accounts in keycloak as described previously [here](https://github.com/rancher/rancher/issues/33356#issuecomment-870953154).

keycloak >> edit / create user >> go to the `role mappings` tab >> in the `client-roles` drop down select `realm-management` >> add `view-users` permissions >> save permissions 

If I remove this role The user no longer has permissions to view users and thus gets a `500` as expected.

**Comment by thanhtai9606** [comment]
> Rancher version: `2.6 master-head (07/01/2021)` _[c1151f6](https://github.com/rancher/rancher/commit/c1151f6e61b3e05a8499aaff9d946e35083df326)_
> 
> I was able to search for users and add them as cluster members after adding the proper roles to the user accounts in keycloak as described previously [here](https://github.com/rancher/rancher/issues/33356#issuecomment-870953154).
> 
> keycloak >> edit / create user >> go to the `role mappings` tab >> in the `client-roles` drop down select `realm-management` >> add `view-users` permissions >> save permissions
> 
> If I remove this role The user no longer has permissions to view users and thus gets a `500` as expected.

Why I already added user with role-mapping is **realm-management** _view-users_. It still not working ?? I cannot search user??

**Comment by maradwan** [comment]
Still not working, I cannot search user?
