### ISSUE TITLE
cloud init from rancher specifically is not running on vsphere

### ISSUE THREAD

**Issue by rlewkowicz-rcd** [rancher/rancher#33374]
I've tried ubuntu 20 and ubuntu 18. I'm getting stuck waiting for ssh. I've done:

```
   23  rm -fr /var/lib/cloud/instances/
   24  rm -fr /var/lib/cloud/instance
   25  rm -f /etc/machine-id /var/lib/dbus/machine-id
   26  truncate -s 0 /etc/machine-id
   27  ln -s /etc/machine-id /var/lib/dbus/machine-id
   28  ls
   30  rm -f /var/log/cloud-init*
```

and 

```
cloud-init clean
```

Cloud init version:
```
/usr/bin/cloud-init 21.2-3-g899bfaa9-0ubuntu2~18.04.1
```

My very very simple addition in the node template:
```
#cloud-config
runcmd:
 - [ sh, -xc, "touch /iran.test" ]
```

This never runs, nor does anything else from rancher it seems. cloud init DOES run through, with no errors. Rancher is not mounting the iso or whatever it's supposed to be doing.

**Comment by rlewkowicz-rcd** [comment]
Ok, so I'm spamming this a bit, but this was such a pain and I see multiple other questions out there and lots of people with no resolution. I feel like rancher should maintain an publish a golden image, or even like advertise it as best effort. With rancher OS going away, something thats going to work best with the platform should be advertised. 

On ubuntu 18 at least, you need to modify your data source list. 

/etc/cloud/cloud.cfg.d/99-installer.cfg
needs:
```
datasource_list: [ "NoCloud", "VMwareGuestInfo" ]
```

**Comment by David-VTUK** [comment]
`datasource_list: [ "VMwareGuestInfo" ]` is only needed if you're actually pulling cloud-init data directly from guestinfo, with Rancher we just use cloud-init YAML via a mounted ISO. When cloud-init has run as part of the Rancher provisioning process, you should see the following in the logs, which we see the `NoCloud` source used.

```
2021-06-26 19:35:26,028 - DataSourceNoCloud.py[DEBUG]: Attempting to use data from /dev/sr1
2021-06-26 19:35:26,030 - subp.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'auto', '/dev/sr1', '/run/cloud-init/tmp/tmpyxvxckt4'] with allowed return codes [0] (shell=False, capture=True)
2021-06-26 19:35:26,073 - DataSourceNoCloud.py[DEBUG]: Using data from /dev/sr1
2021-06-26 19:35:26,076 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=/dev/sr1][dsmode=net]
```

I don't see `VMwareGuestInfo` as a cloud-init datasource for my nodes. However, I have used it when I've used it in conjunction with Terraform to directly configure VM networking (Example: https://github.com/David-VTUK/Rancher-K3s-vSphere)

I help maintain the following repo for Packer templates : https://github.com/David-VTUK/Rancher-Packer. I've just tested the Ubuntu 18.04 and 20.04 templates which both work without issues. The "secret sauce" in getting cloud-init in a compliant state is via the following config scripts:

https://github.com/David-VTUK/Rancher-Packer/blob/master/vSphere/ubuntu_1804/script.sh
https://github.com/David-VTUK/Rancher-Packer/blob/master/vSphere/ubuntu_2004/script.sh

I found some extra cleaning up had to be done with 20.04 due to the Subiquity installer. I recommend you try these Packer templates, or running the associated scripts on your templates.

I also presented at a Rancher Masterclass on vSphere provisioning, including some troubleshooting steps which may be of interest : https://www.youtube.com/watch?v=ozLPpyrqwf8
