### ISSUE TITLE
Back-off pulling image rancher/mirrored-prometheus-alertmanager

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#33400]
In emberUI enable monitoring, set up slack notifier and add alert.
Test alert can be sent when setting up notifier.
After adding alert rule (tested pod not running) and removing pod alert rule disapears but notification is not sent.

```
ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: manifest for rancher/mirrored-prometheus-alertmanager:latest not found: manifest unknown: manifest unknown
```

![Screenshot from 2021-06-29 16-58-51](https://user-images.githubusercontent.com/538604/123821522-c3e6b600-d8fb-11eb-9953-0deff85f7ee6.png)

Chart: dev-v2.6 (commit: 2452663cae8dbd9083e1374782ef445440491ae6)
Cluster1: Custom v1.20.7 (Oracle 8.4)
Cluster2: Infra provider DO (Ubuntu 20.04)
Rancher: single node master-head (c7f3cce)

**Comment by jiaqiluo** [comment]
Hi @kravciak  I assume you are using the monitoring v1 chart version `v0.2.3`, right? 

It is weird to see it tries to pull the `latest` tag because we always avoid the `latest` tag in all our charts.  

The abovementioned image is used is at https://github.com/rancher/system-charts/blob/cd9dbb6b031a58b7b7d2b1f1edc2ccd99ea6a0d8/charts/rancher-monitoring/v0.2.3/values.yaml#L210-L211
```
    repository: rancher/mirrored-prometheus-alertmanager
    tag: v0.22.0
```

Can you try it one more time to see if it works now?

**Comment by kravciak** [comment]
Yes, monitoring v1 is `v0.2.3`. I was not able to reproduce again, everything seem ok in master-head (ac7cef3)

**Comment by c4m4** [comment]
is there any different between the rancher prometheus docker image and the upstream one?
