### ISSUE TITLE
[Backport 2.5, Monitoring V2] Add pushprox for kubelet and node-exporter

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33420]
Backports https://github.com/rancher/rancher/issues/32841.

**Comment by thehejik** [comment]
Tested on `rancher/rancher:2.5.8` with `rancher-monitoring:16.6.0` deployed on custom RKE1 cluster.

User chart repo `dev-v2.5` commit: `fae0bf3eabad5fb902e4bda7b87fd1b14034456c`

**prometheus-node-exporter**
* pushproxy is used by default
* I see that for scraping following metrics a pushprox-client is used - the output was taken from one of the `rancher-monitoring-prometheus-node-exporter*` pod processes:
```
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-scheduler-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10012 --allow-port=10251 --use-localhost
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-proxy-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10013 --allow-port=10249 --use-localhost
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10011 --allow-port=10252 --use-localhost
pushprox-client --fqdn=redacted_ip --proxy-url=http://pushprox-kube-etcd-proxy.cattle-monitoring-system.svc:8080 --metrics-addr=:10014 --allow-port=2379 --tls.cert=/etc/ssl/push-proxy/push-proxy.pem --tls.key=/etc/ssl/push-proxy/push-proxy-key.pem --tls.cacert=/etc/ssl/push-proxy/push-proxy-ca-cert.pem
```
* corresponding `pushprox-kube-*-proxy*` pods are running
* all the metrics above are healthy (and listening on public ip of the node over endpoint) in Prometheus Targets view

**kubelet**
* pushproxy must be enabled first for kubelet eg. by setting `hardenedKubelet.enabled: true` in values (otherwise it scrapes the metrics directly from kubelet container over hostNetwork which has similar result - both are on public ip)
* then the pods `pushproxy-kubelet-client*` (DS)  and `pushprox-kubelet-proxy-*` (1 RS) are deployed
* The metrics from kubelet are healthy in Prometheus Targets view

Works as expected. Close.
