### ISSUE TITLE
[Backport 2.5, Monitoring V2] Remove pre-install job in favor of Helm annotations

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33442]
Backport https://github.com/rancher/rancher/issues/32113

**Comment by jiaqiluo** [comment]
the fix is validated in rancher v2.5-head 0713103 with Monitoring v2 chart `16.6.0`

The following 2 cases are tested:
- fresh install of monitoring v2 `16.6.0` into a downstream RKE cluster 
- upgrade monitoring v2 from `14.5.100` to `16.6.0`

Results:
- both fresh install and upgrade succeeds
- no job for creating the initial secret
- the `rancher/agent` image is not used anymore
