### ISSUE TITLE
Show load metrics on UI infrastructure > hosts page overview

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3344]
As Rancher environment administrator I would like to see which hosts have the highest load in terms of cpu/mem or network.
Right now I have to go to each host to find out, with many hosts this is really a lot of clicks.

Since we already show some live metrics (cAdvisor) on the single Host page, it should be fairly easy to show a small miniature of that on the Hosts page. 

Rancher already show the host static values for # CPUs, RAM and disk space,  we could make those numbers a bit more alive with color indication if the consumption is too high. Similar approach is used I think in mesosphere, kubernetes UI and other CaaS. 

If this is in place it would also make sense to add "sort by <metric>" in the upper right corner of the hosts page.

The overview of the hosts page would than be much more useful and help in a single glance identify "full / problematic hosts" and Rancher will help us manage containers in production.

**Comment by cusspvz** [comment]
I have submitted a feature request regarding a dashboard with the most important metrics. I think it could perhaps be more appealing to you. Unfortunately I am on my phone and cant relate the issue over email. :/ 

Enviado do meu telefone com Cyanogen

Em 20/01/2016 16:55, Antonio De Marinis <notifications@github.com> escreveu:

As Rancher environment administrator I would like to see which hosts have the highest load in terms of cpu/mem or network.
Right now I have to go to each host to find out, with many hosts this is really a lot of clicks.

Since we already show some live metrics (cAdvisor) on the single Host page, it should be fairly easy to show a small miniature of that on the Hosts page. 

Rancher already show the host static values for # CPUs, RAM and disk space, we could make those numbers a bit more alive with color indication if the consumption is too high. Similar aproach is used I think in mesosphere and other CaaS. 

The overview of the hosts page would than be much more useful and help in a single glance identify "full / problematic hosts" and Rancher will help us manage containers in production.

**Comment by deniseschannon** [comment]
Closed in favor of #2718
