### ISSUE TITLE
Can't uninstall V1 Monitoring use V1 API

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#33454]
Please see this UI ticket from QA: https://github.com/rancher/dashboard/issues/3223

**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Install V1 Monitoring using the Rancher UI via Cluster Tools.

Go to Apps & Marketplace -> Installed Apps.

Try and delete the 'cluster-monitoring' app - this fails with the following message in the UI:

```
Thu, Jul 1 2021 2:01:28 pm | helm uninstall --namespace=cattle-prometheus cluster-monitoring
Thu, Jul 1 2021 2:01:28 pm | Error: uninstall: Release not loaded: cluster-monitoring: release: not found
```

The Backend API indicates that the uninstall action is available for this app, but invoking this action fails, see:

/v1/catalog.cattle.io.apps/cattle-prometheus/cluster-monitoring

** Expected **

~Uninstall API should work for a V1 app OR the uninstall action should not be available.~
Based on discussions below V1 Monitoring should not be available under Apps & Marketplace -> Installed Apps.

**Comment by aiyengar2** [comment]
I have some concerns about whether we can install Monitoring V1 via the Apps & Marketplace UI. 

Namely, enabling Monitoring V1 at the moment is not as simple as just doing a Helm install of the rancher-monitoring chart in system-charts, unlike Monitoring V2. It involves multiple Helm installs that are managed by Rancher controllers that also need to be enabled for full functionality and is conditionally uninstalled as well depending on whether Alerting V1 is enabled as well (which is based on a set of conditions based on Alerting CRs).

The right way to enable Monitoring would be to hit the v3 cluster endpoint to `enableMonitoring`, which would trigger all of these things, and the right way to disable it would be to hit the v3 cluster endpoint to `disableMonitoring`. But that type of action seems to be out of scope for Apps & Marketplace, which is focused on triggering Helm installs.

cc: @Jono-SUSE-Rancher @deniseschannon @dramich

**Comment by deniseschannon** [comment]
@nwmac I've re-read the issue above and think that the implementation of the v1 monitoring needs to change in the Cluster Tools page. 

v1 Monitoring isn't a simple helm chart so it can't be deployed using a single API call to deploy the charts. Can you review how  we enable/disable the v1 Monitoring in Cluster Manager and leverage those same API calls? The downside is then we don't have an easy way to view/manage these as individual apps since they will be v3 apps. 

Does v1 Logging have this issue or is it okay cause it is a standard helm chart? The only concern of the v1 logging is that the Helm chart was never certified/verified as a Helm 3 install, so using the v1 API to deploy assumes it's a Helm 3 chart. 

Remind me, what other v1 tools are available in cluster tools?

**Comment by vincent99** [comment]
I agree there's a problem, but don't think this is really related to monitoring or any other particular tool.

"Apps" from Helm3 catalogs in the old API/UI also show up as entries in the Installed Apps of the new API/UI (because those are just looking at native helm release data and the old system still calls helm and generates that).  But you can't actually manage those apps that show up with the new API/UI.

So either managing them should work, or they should be filtered out of the display.

**Comment by snasovich** [comment]
@vincent99 , I think what is suggested here is to have UI handle actions on certain apps listed under "Installed Apps" in a special way so for example Delete action on Monitoring V1 app uses matching v3 object to do deletion instead of v1 one.
Filtering out may be an option as well. My understanding is that these legacy apps can be disabled from Cluster Tools when legacy feature flag is enabled and this uses v3 API as needed.

**Comment by deniseschannon** [comment]
We discussed offline and old apps that were deployed using Helm 2 were accidentally being seen as Helm 3 apps, so @ibuildthecloud will make a fix to change this and it shouldn't list the app under the list of apps & marketplace.

**Comment by snasovich** [comment]
PR: https://github.com/rancher/rancher/pull/33661

**Comment by snasovich** [comment]
@sowmyav27 , this is now ready to test on `master-head`. Legacy Monitoring apps (`cluster-monitoring` and `monitoring-operator`) should no longer be shown under Installed Apps in new UI.

**Comment by sowmyav27** [comment]
**On master-head commit id: `cfbd0d3`**

- Deploy monitoring v1 on a cluster from Ember UI.
- Enable Legacy feature flag on the rancher server setup.
- Go to cluster context in Dashboard --> Apps and Market Place --> Installed apps. 
- Monitoring v1 app is not see.
- Cluster tools --> Monitoring v1 --> install button is seen
- Click on Install, Disable option is seen, as Monitoring v1 is enabled already
- User is able to disable monitoring v1 and enable monitoring v1 from the cluster tools.
