### ISSUE TITLE
Rancher crashes and restarts when multiple cluster and node drivers are enabled.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33461]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- On the new UI, enable all cluster and node drivers

**Result:**
Rancher server crashes and restarts

**Expected Result:**
Rancher should not crash.

**Other details that may be helpful:**
Reach out to me for rancher logs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `e546ffe`
- Installation option (single install/HA): single

**Comment by rmweir** [comment]
Was unable to reproduce. However, I have witnessed restarts without restarting driver that I think are caused by having limited compute resources. This is the error shown in that case: `leaderelection lost for cattle-controllers `. Something similar is mentioned here: https://github.com/rancher/rancher/issues/32080#issuecomment-822731609. I think this may have been what was encountered since activating all the cluster/node drivers will increase cpu usage as shown here:
![image](https://user-images.githubusercontent.com/19376037/124839579-e2713080-df3d-11eb-8107-3347ad66dcc2.png)

The first spike is rancher starting up, the second, circled spike is while activating all deactivated drivers. If this is the case I would agree with the linked comment that this is just a resources issue.

**Comment by sowmyav27** [comment]
**On a HA setup on rancher master-head commit id: `4d41301`**

- t3.large AWS nodes, enable multiple cluster and node drivers. 
- No Rancher restart is seen.
