### ISSUE TITLE
What is the best way to run on a particular host?

### ISSUE THREAD

**Issue by deitch** [rancher/rancher#3347]
In https://github.com/rancher/rancher/issues/3323 I had raised the issue of how I get a service/container to run on a particular host only using compose yml.

That raises the larger issue though.

I feel as though scheduling a service on one individual host in an "Environment" is just, well, *wrong*, un-Rancher-ish. Is there a better way to do this?

The circumstances are that we have multiple hosts in our Rancher "Environment". Some of the time we want container `x` to run only on host `A`, at least for now. We do it for testing reasons, either how service `x` and service `y` interact with each other when run together, or the performance of how service `x` performs by itself, then `x` and `y` together, then 3, etc. 

In all cases, we are trying to control the server tightly with 2 rules:

A. Those 2 (or 3 or whatever) **only** run together; AND
B. **Nothing but** those 2 (or 3 or whatever) are on the host.

I see a few options:

1. Define all hosts in a single "Environment", but those that should be on a particular host have the right label in the yml. That solves (A) above, but not (B)
2. Define hosts in different "Environments". This only works if each Environment is exactly one host, else I have the same problem as (B) above. 
3. Define hosts in different "Environments", have one of the environments called "isolation", and whenever we start a pre-defined service, we start it on a given host (can I even do that from the UI?).

There has to be a better way to get the behavior I am after. What can I do better?

**Comment by sshipway** [comment]
Can you do this via host labels?
You can set a host label on the host you want it on ( FOO=1 )
You can set a container label on the service A  ( A=1 )

Now you can set the scheduling rule for service A to be (Host label MUST be FOO=1 )
And the scheduling rule for service B to be (Host MUST have container with label A=1)

The second rule ensures your requirement A.  To ensure nothing else runs on the host, you would need to have all other services have the scheduling rule (Host MUST NOT have FOO=1)

The benefit is that you can, of course, add more FOO=1 hosts if you want.  This would be a way to identify which hosts are local and which are in AWS, for example, while still keeping a single environment.  The difficulty is that you need to ensure all other services have scheduling rules to exclude your FOO=1 label.

Or am I missing something?  The scheduling rules are pretty powerful and flexible as you can test for not just labels, but service and container names.

**Comment by deitch** [comment]
Thanks @sshipway . Yes, labels do appear to be the way to go. I was just wondering if my whole mindset around "tie to this host" is the right methodology, or if there are other abstractions (or combinations), like using Environments somehow, that make this process more manageable than my "tie it to a host".

I also am worried about both sides. If someone forgets to put in `Host MUST NOT have FOO=1` on a different service, then stuff gets messed up.

I guess I could do something like add a unique label to each service, e.g. service `y` has `supports=x`, service `y` has `supports=y`, and then apply/remove labels to hosts as I want things to run. But that too seems kludgy.

Is there any way to configure services without hosts, and select which hosts to start them on at run time, rather than creation time? Maybe in these situations I really am looking to have an Environment in which I start a service and say, "run here".

**Comment by demarant** [comment]
In my mind, scheduling the services to specific hosts, is not a good idea, it reduces a lot what actually the Rancher HA service does. In the case of host failure, Rancher will not be able to find alternative hosts on where to re-schedule the containers and achieved the desired scale of the service. This of course, as per today, only works well for ephemeral containers. For stateful containers, those having e.g. dependencies with certain hosts, like bind-mounts or other db-dependencies, the situation or re-scheduling by Rancher is not possible. They are waiting for this funntionality  from docker itself as far as I understood from the discussions I had with Rancher folks. 

There is also no way at the moment for Rancher to understand when a Host is full, they will add capacity scheduling as well, I hope. So the built in scheduling may lead your containers to undesired hosts. For this reasons, I think people are trying to schedule to specific hosts, because they are kind of unhappy on how the current scheduling picks up hosts, and want more control over it.
 
@deitch So my short answer to your question in this issue is. Do not schedule to specific hosts, rather always schedule to a set of hosts with specific characteristics and concentrate on HA setups, meaning at least two containers on two different hosts.

In the meantime, I can share with you some ideas I wrote down for my organisation on *MyStack example for HA in Rancher* https://docs.google.com/document/d/1FIUGNZQ_08kw4hz3qaRXI6JPO8ptGdcqh0Tz-_So16Y/edit?usp=sharing

*HA Experiments with Rancher (WIP)*
https://docs.google.com/document/d/1tQEkuvK5_6Mgg8LQSzBe4euwrN0XZXLFmdyY0xKuJLY/edit?usp=sharing

We should probably discuss in the rancher forums more and share good examples on how people are scheduling in Rancher.

**Comment by deitch** [comment]
@demarant thanks for the detailed feedback. I am looking forward to reading the examples you shared.

In a production environment, I absolutely am scheduling based on labels or anywhere in an environment, with any constraints provided by sidekicks or co-scheduling rules.

My issue really is test labs, where strict control of what runs where is important for testing one item polluting another, or a pristine environment (clean host) for performance testing so I can do apples-to-apples.

So, perhaps the question should be rephrased: how do I manage controlled deployments when testing? Truth be told, if I had the ability to click not just "start service" but "start service on host X" from the UI, much of this problem would go away.

**Comment by demarant** [comment]
@deitch I have similar concerns for the dev/test/staging environments. My goal is to live up to the [Dev/Prod parity principles](http://12factor.net/dev-prod-parity) within Rancher. 

So my main question is not "isolate this test Stack here", because docker already provides enough isolation at the host level, rather how do I make sure Test environment is exactly the same as the Prod environment? Actually I don't want that a stack in a test environment works in isolation and than in production works together with somethings else that may interfere and gives you surprises when you deploy same stack to production. The test lab must be a reproduction of your final environment, which is actually the production environment, therefore test-lab must be a copy of it.

Although, docker-compose+rancher-compose/ the catalog and scheduling rules will give you a recipe for achieving this, the kitchen (the environment and its host) may be different and therefore the recipe is not a 100% guarantee that you get same layout on other environments.

One way to solve this would be to Clone an entire Environment. This idea sounds crazy I know, because it involves the recreation of new hosts, lot of automation... but it would actually give us what we want. Right now one has to manually make sure those environments are kept in sync, so that scheduling behaves the same. So the only way I see to solve your and my requirements is to keep control over the environments and make sure they stay in sync (number of hosts and labels).

**Comment by demarant** [comment]
@deitch: and I fully understand your need for the "pristine environment (clean host) for performance testing so I can do apples-to-apples". In that case a single dedicated environment where only the Test lab Team has access to should help. That they can assign the labels to the new fresh hosts > deploy the Stack > Deactivate the hosts (so no more stacks get accidentally deployed there), Run the performance tests > Delete/Stop the stack

**Comment by deitch** [comment]
@demarant that makes sense. Is that better than just assigning it to a host? I guess it might be, else I am stuck worrying that some service or stack got deployed to a host, and it no longer is pristine?

**Comment by demarant** [comment]
@deitch yes, I think it is better, because it is more generic, and you can use exact same compose file (with same labels) for both test and prod. The labels can be applied to specific hosts in a controlled manner by the Test Team to their Test Environment. This gives you exactly what you asked in the UI without "by-passing/overaking" Rancher scheduler.

**Comment by deitch** [comment]
@demarant that makes a lot of sense. Thank you. I will try to go down that path.

**Comment by deitch** [comment]
@demarant just to follow up. So I set up 2 environments: "QA" and "Performance". QA looks like production, no labels per se, just a nice pool of hosts and services.

Performance has just a few hosts, possibly even 2 or 3. Services look the same from a compose file perspective, but I deploy services for performance testing to "Performance" environment.

How do I control at the granular level which services run on which hosts in "Performance"? I thought of 2 ways, not sure which you meant:

1. Shut down all services, disable all hosts except the one(s) performing the current test, start just the service(s) involved in those tests. Don't love it, but doable on a small scale.
2. Add arbitrary labels to each service, e.g. "host_label_se: service=svc1". Then I can attach labels to the hosts in the Performance environment to say, "I am the host for running svc1". Again, not fabulous, but most flexible.

Is that what you mean?

**Comment by demarant** [comment]
@deitch:
Yes, i was thinking more of option 2 combined with stopping/deactivating all other stacks. Again, If we want to automate more we could also create the hosts via API run the performance tests, save results outside of rancher.finally unregister and delete all the hosts. So at each the environment is clean.

**Comment by deitch** [comment]
Thanks @demarant , now on to changing people's cultural mindset! :-)

**Comment by demarant** [comment]
@deitch:
Btw i would never run performance tests on the Cloud....unless it is exactly what you want to test "how does your application runs on the cloud". 
I say this because, if your hosts are VM on amazon/digital ocean or other IaaS, the VMs are running on very bUsy and shared hardware...therefore results will vary from time of the day....so i gueaa better to run performance tests on isolated baremetal hosts.

**Comment by deitch** [comment]
Oh quite agreed. The only exception is packet.net. Bare metal on demand. I very much have done performance tests on them and love them.
