### ISSUE TITLE
[rancher-logging] Kubelet logs for RKE2 are not picked up by logging chart

### ISSUE THREAD

**Issue by dbason** [rancher/rancher#33472]
Logs for the kubelet are logged to `/var/lib/rancher/rke2/agent/logs/kubelet.log` not journald, and they are not picked up by rancher-logging

**Comment by snasovich** [comment]
@SheilaghM , assigning it to @nickgerace since he's the other Logging SME and we cannot have it validated by who implemented it (Jacob).

**Comment by brendarearden** [comment]
Validation: FAILED

Steps to recreate:

1. install rancher-logging:3.9.400 on rke2
2. Validate that I can only see control plane logs for `"component"=>"kube-apiserver"` and `"component"=>"etcd"`

Steps to validate:

1. install rancher-logging:100.0.0+up3.12.0 on rke2
2. Still only seeing control plane logs for `"component":"kube-apiserver"` and `"component"=>"etcd"`

**Comment by brendarearden** [comment]
Validation: PASSED

Steps to Validate:

1. From an HA rancher setup ( rancher version: v2.6.0-rc3)
2. Deploy a downstream RKE2 cluster with multiple nodes - Digital Ocean, k8s version v1.21.3-rc4+rke2r2.  1 node set to all roles, and the 2nd node is set to worker role. 
3. Install rancher-logging v100.0.0+up3.12.0. 
4. Install example logging application and flows from https://github.com/paynejacob/rancher-logging-examples
5. Edit the cluster flow to forward to my local ngrok endpoint `ngrok tcp 24224` that is setup to display the forwarded logs on the stdout of `docker run -p 24224:24224 fluent/fluent-bit /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'`
6. Per dev instructions, I restarted the work node by ssh into node and running `sudo reboot`. This will help generate logs since logs are not showing up as frequently as they did in previous versions
7. After ssh into node with all roles, I tailed `tail -n 500 /var/lib/rancher/rke2/agent/logs/kubelet.log` to get a kubelet log out. I grabbed the a recent entry
```
I0819 06:57:57.731864    3340 scope.go:111] "RemoveContainer" containerID="5f9d142faed3e00771db5e30608a1266afca5dc1df5c9194fb4b842c939d14ad"
```
8. I validated that I was able to see it being forwarded correctly
```
{"date":1629356278.297592,"log":"I0819 06:57:57.731864    3340 scope.go:111] \"RemoveContainer\" containerID=\"5f9d142faed3e00771db5e30608a1266afca5dc1df5c9194fb4b842c939d14ad\""}
```

@paynejacob I see that some of the logs in kubelet.log are not coming through to the stdout still, since I am getting some I was curious if this has to do with the `stdout` setup vs being an actual issue. Is it possible the stdout is dropping the data, or is it still not getting forwarded?
