### ISSUE TITLE
Deployment: API returns related resource that does not exist - Only occurs for RKE2 clusters

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#33657]
See dashboard issue: https://github.com/rancher/dashboard/issues/3436

This is reproducable on a single-node cluster provsionned in Digital Ocean:

See the ticket above for steps to reproduce - but essentially create a deployment  in the UI - just specify a name and the image as 'nginx:alpha".

The pod for the deployment will have a related resource (secret) 'kube-root-ca-crt' - this resource does not exist (or at least, not visible to the user).

I've checked the backend and the API is returning this resource in the response.

**Comment by anupama2501** [comment]
This issue is not seen on an rke1 cluster. 

- Created an rke1 cluster with 1 node all roles
- Created a deployment from explore cluster --> workloads
- From the deployment pods  --> Related resources --> secrets 
- The secret is default-token in the deployment pods for rke1 clusters
- If we add the environment variables and select config map --> `kube-root-ca.crt` and click on `kube-root-ca.crt` works fine and no errors are seen.
- Secrets referred in rke1 cluster pods

<img width="300" alt="Screen Shot 2021-07-19 at 1 32 23 PM" src="https://user-images.githubusercontent.com/38144301/126238447-ba450324-3883-4a3d-b2b7-25c0b4c77380.png">


- On rke2 clusters, if we click on the secret `kube-root-ca.crt`  in the workload, the page results in error. 
- `kube-root-ca.crt` is present in the config-map and not secrets, therefore the API errors out with the `not found` message
- Secrets referred in rke2 cluster deployment pods:
<img width="300" alt="Screen Shot 2021-07-19 at 1 31 58 PM" src="https://user-images.githubusercontent.com/38144301/126238492-77433a7b-c625-4aaa-9eec-8621aa6b329f.png">




```
Request Method: GET
Status Code: 404 Not Found
```

**Comment by deniseschannon** [comment]
There was a bug that it was referring it to as a secret, when it actually is a configmap.

**Comment by anupama2501** [comment]
Verified on master-head 3499046

- On a downstream rke2 node driver cluster, created a worklaod deployment from explorer
- Deployment pods display `Service account` and `config map` with `deafult` and `kube-root-ca.crt` certificates in the relate resources tab.
- Verified all are clickable and do not error out.
- Verified the same by creating a daemon set and a workload deployment from ember UI.
