### ISSUE TITLE
Cannot create backup in Cluster Explorer after switching to Simplified Chinese

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#33654]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Describe the bug**

Cannot create backup in Cluster Explorer after switching to Simplified Chinese

**To Reproduce**
 
1. Go to "Cluster Explorer"
2. Switch to Simplified Chinese
3. Create a backup
**Result**
Unable to create backup, the page stays at "正在加载中...(Loading...)"

![image](https://user-images.githubusercontent.com/19684717/125898213-d1b754b3-ff07-4539-8efb-a3a592509481.png)

**Expected Result**

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by kingsd041** [comment]
v2.5.10 also has the same problem

**Comment by niusmallnan** [comment]
v2.6.3 has no this problem, as it's translated by the right word.
https://github.com/rancher/dashboard/blob/v2.6.3/assets/translations/zh-hans.yaml#L503

I think that we only need to fix this in v2.5.x(probably v2.5.12).

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: 2.5-head
Rancher cluster type: single-node docker install
Docker version: 20.10

----------

### Testing: ###

Reproduced the issue in 2.5.11 (didn't use 2.5.12 because the fix went to 2.5.12 and the issue can't be reproduced there)
![reproduced](https://user-images.githubusercontent.com/40282141/154091175-76999109-4164-4e76-a4a1-a6861ca5311a.jpg)

---------

2.5-head does not have issues with creating a backup
Switched to Simplified Chinese and tested 
- create a backup with a preconfigured s3 bucket (when the backup chart is installed) 
- create a backup with passing s3 info while creating a backup

![back up](https://user-images.githubusercontent.com/40282141/154091996-f11fca39-5e9d-4d76-be2b-aa1c36890bdc.jpg)
