### ISSUE TITLE
[Forwardport] Global/restricted admin unable to create an EKS cluster in hosted Rancher tenant 

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33741]
https://github.com/rancher/rancher/issues/32149
Unclear at this time if this is required or not, as similar issues were already fixed in 2.6.

**Comment by thedadams** [comment]
@cbron I don't think this is necessary. Darren's changes should make it possible to create an EKS cluster in hosted Rancher.

There was also a change made to not re-assign the `cattle-system` namespace to the tenant system project, but that shouldn't be a problem in 2.6 because Daishan's changes to move the operators to rancher/charts.

**Comment by cbron** [comment]
Moving to test to ensure it was fixed.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 21ab02c` with the following steps:
- Bring up a hosted Rancher setup with helm option "restrictedAdmin" = "true" on tenant cluster.
- Log into tenant cluster Rancher.
- Create a new EKS cluster - enter AWS creds with permissions to create EKS cluster, can mostly use default options. Click Create.

Result:
The EKSv2 cluster is available in Rancher UI and EKS console.
EKS operator version: `v1.1.1-rc8`
![Screen Shot 2021-07-28 at 6 05 50 PM](https://user-images.githubusercontent.com/57409052/127416980-2af84f05-daf8-4fcc-91c2-7a2dc7df690d.png)
