### ISSUE TITLE
ingress controller workload fails to deploy in a windows 1.21 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33756]
**Rancher Server Setup**
- Rancher version: master-head commit id: `cd623b5d`
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: 1.21.1, RKE1 Windows custom cluster

**Describe the bug**
ingress controller workload fails to deploy in a windows cluster

**To Reproduce**

- Deploy a windows 2004 k8s 1.21 cluster
- In Dashboard --> Deployments page --> ingress controller workload is Not Active

**Result**
- Errors seen on the ingress controller deployment:
```
FailedMount (22) | 1.2 mins ago | Unable to attach or mount volumes: unmounted volumes=[webhook-cert], unattached volumes=[webhook-cert kube-api-access-dxcks]: timed out waiting for the condition
-- | -- | --
FailedMount (35) | 6 mins ago | MountVolume.SetUp failed for volume "webhook-cert" : secret "ingress-nginx-admission" not found
FailedMount (2) | 26 mins ago | Unable to attach or mount volumes: unmounted volumes=[webhook-cert], unattached volumes=[kube-api-access-dxcks webhook-cert]: timed out waiting for the condition
```
- Error on ingress jobs:
<img width="1413" alt="Screen Shot 2021-07-30 at 6 39 29 PM" src="https://user-images.githubusercontent.com/26032343/127724831-29152694-5e0e-460e-82a0-4df3950720a9.png">

- Windows nodes dont register - issue logged - https://github.com/rancher/rancher/issues/32910

**Expected Result**
ingress-controller should be deployed successfully on the linux nodes

**Comment by deniseschannon** [comment]
As this has to do with the linux cluster, this is most likely a generic linux issue.

@sowmyav27 Do you see this issue on pure linux clusters?

**Comment by sowmyav27** [comment]
@deniseschannon No this issue isnt seen on a linux only cluster - tried it with 1 etcd, 1 control plane and 1 worker nodes.

**Comment by rosskirkpat** [comment]
I suspect that the underlying RC (as the the previous version 0.46.0 of nginx controller doesn't have the tolerations/nodeSelectors set either) is due to the nginx-ingress changes on 1.21. 

This would not have popped up during previous QA on Windows clusters as 1.21 is not supported on rancher 2.5.x and would not have been tested on rke1 windows clusters previously.

Validation:
I manually redeployed the jobs and forced them to use the linux worker via setting nodeName and then redeployed the nginx ingress controller and confirmed it is running/active

jobs that are stuck in ContainerCreating (they are being scheduled on windows nodes):
```
ingress-nginx-admission-create
ingress-nginx-admission-patch
```

How to fix:
- add tolerations for NoSchedule on linux nodes as currently kube-scheduler reports only 3 feasible nodes, which are all of the Windows nodes
- add a nodeSelector to have this run on Linux only

ref for fixes: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=template&template=admission-webhooks/job-patch/job-createSecret.yaml

This will be fixed in KDM and then possibly need vendored into RKE (this needs verified)
https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/templates/nginx-v0.48.1.go#L576-L665

**Comment by kinarashah** [comment]
Available to test on v2.6-head after https://drone-publish.rancher.io/rancher/rancher/6186 is green. PRs for master-head pending.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4b6af95d`**

- Ingress controller deploys on a windows 1.21 cluster. Deploys on the Linux worker node.
<img width="1068" alt="Screen Shot 2021-08-08 at 4 01 18 PM" src="https://user-images.githubusercontent.com/26032343/128648382-6b90fecf-eb79-4ab6-9c0b-d85c722e6e7c.png">

**Comment by sowmyav27** [comment]
Closing. Forwardport tracked here - https://github.com/rancher/rancher/issues/34065
