### ISSUE TITLE
Verify Rancher server helm chart will be stopped on a k8s 1.22+ cluster

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33777]
We need to verify if we can run Rancher on a k8s 1.22 cluster and if not, we need to update our Rancher server helm chart to limit deploying on a k8s 1.22 chart until it's supported.

**Comment by snasovich** [comment]
I'm 99% sure it won't be able to run on 1.22 as changes to move CRDs to v1 API from v1beta1 APIs are not in.
@cmurphy , could you please verify this and update Rancher Helm charts?

**Comment by cmurphy** [comment]
Rancher will not run on kubernetes 1.22 because of https://github.com/rancher/rancher/issues/33222. Added https://github.com/rancher/rancher/pull/33781 to pin the version.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by snasovich** [comment]
@thedadams , please validate this one. k8s 1.22 is out so it should be possible to test.

**Comment by thedadams** [comment]
This issue is verified: installing Rancher from the new helm chart produces an error and Rancher is not installed.
![Screen Shot 2021-08-06 at 11 29 57 AM](https://user-images.githubusercontent.com/3682717/128556048-666ac40f-ca43-4b7d-bda3-b9f8244f504f.png)
![Screen Shot 2021-08-06 at 11 31 01 AM](https://user-images.githubusercontent.com/3682717/128556138-9faa71e3-d1bd-420d-9e37-ad8466246169.png)

**Comment by deniseschannon** [comment]
Rancher will extend support to k8s 1.22 with this issue. Due to the dropped APIs, it will take signifcant work to get this supported. 

https://github.com/rancher/rancher/issues/34060
