### ISSUE TITLE
Unable to take etcd snapshots to S3 after upgrading to Rancher 2.4.16

### ISSUE THREAD

**Issue by dhawton** [rancher/rancher#33835]
**Rancher Server Setup**
- Rancher version: 2.4.16
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 - 1.18.20
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version: 1.18.20
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider: AWS, reproduced on DO

**Describe the bug**
After upgrading to Rancher 2.4.16, attempts to take a snapshot of etcd to S3 fail with:

[etcd] Failed to take one-time snapshot on host [10.4.140.13], exit code [1]: time="2021-07-26T10:40:49Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:REDACTED err:Head \"https://REDACTED.us-east-2.amazonaws.com/\": net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=\\x00\\xa2\\x00U\\x04\\xc9\\x10\\xc4\\xc7\\x1f\\x84D`\\xd3J/20210726/us-east-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=3a63bd57c782f4e1e4545bec949d7d612de3b8bec621ff9404fbd3c84b4f67ca\" for key Authorization"

**To Reproduce**
1. Install Rancher 2.4.15
2. Create downstream cluster, configuring etcd backups to S3 through the Cluster Manager Cluster Config
3. Take test etcd snapshots
4. Upgrade Rancher to 2.4.16
5. Attempt to take etcd snapshot again

**Result**
Failure with error, no snapshot in the S3 bucket.

[etcd] Failed to take one-time snapshot on host [10.4.140.13], exit code [1]: time="2021-07-26T10:40:49Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:REDACTED, err:Head \"https://REDACTED.us-east-2.amazonaws.com/\": net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=\\x00\\xa2\\x00U\\x04\\xc9\\x10\\xc4\\xc7\\x1f\\x84D`\\xd3J/20210726/us-east-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=3a63bd57c782f4e1e4545bec949d7d612de3b8bec621ff9404fbd3c84b4f67ca\" for key Authorization"

**Expected Result**
The backup to be taken and in the S3 bucket

**Screenshots**
NA

**Additional context**
NA

**Comment by slickwarren** [comment]
I was able to reproduce this in:
* a clean install of 2.4.16 with etcd snapshots enabled on a downstream (Digital Ocean) cluster via S3 -> no snapshots were taken
* a 2.4.15 cluster with etcd snapshots enabled on a downstream cluster -> snapshot taken (also set recurring snapshot time to 1 hour)
  * updated cluster to 2.4.16, after 1 hour no snapshot was taken of the downstream cluster
  * also setup another downstream cluster after the upgrade, which also did not take a snapshot

**Comment by aiyengar2** [comment]
The root cause of this issue has to do with a missing backport of https://github.com/rancher/rke/commit/313f3635a64b73e7b807a956ed1fd92176fb8d42.

In rke-tools v0.1.73, a change was introduced to try to base64-decode the S3 credentials passed into the container (see [this](https://github.com/rancher/rke-tools/compare/v0.1.72...v0.1.73)). This was paired with a corresponding change in rancher/rke's 1.2.x release line (linked above) which passed in base64-encoded S3 credentials.

However, this change was not backported to the rancher/rke 1.1.x release line, which the release line used by Rancher 2.4.x.

As a result, in Rancher 2.4.16, Rancher uses rke 1.1.x to trigger the S3 snapshot (which passes non-base64-encoded values into rke-tools) and rke-tools tries to decode it. It incorrectly succeeds (since it so happens that Amazon S3 keys happen follow the regex rules for base64 encoded strings) and the wrong credentials are used.

Note: For 2.4.16, there is no mitigation / workaround to be able to fix the issue since, as noted in https://github.com/rancher/rke/issues/1937#issuecomment-894386256, the version of rke-tools used for backup images is directly vendored into the Rancher code.

**Comment by slickwarren** [comment]
tested the following:
* fresh install of 2.4-head (6169)
  * deploy digital ocean cluster with S3 etcd backups enabled -- pass

* Fresh install of 2.4.16 -> deploy digital ocean cluster with S3 etcd snapshots enabled -- fail (expected)
  * Upgrade from 2.4.16 to 2..4.head -> existing cluster with s3 etcd snapshots enabled -- pass
