### ISSUE TITLE
Use embedded etcd from k3s for single node usage

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33850]
This is an exploratory issue to track dropping the etcd binary in favor of embedded etcd from k3s for single node usage.

**Comment by annablender** [comment]
Merged in a PR https://github.com/rancher/rancher/pull/35323. Single node K3s with embedded etcd will be available in 2.6.4. Docs on how to look at the data inside embedded etcd and debug issues with the new database are here How to Use Etcdctl with K3s Embedded Etcd.

**Comment by cbron** [comment]
@annablender can you fill out the QA template here, then @MbolotSuse this might be a good dev-validate for you.

**Comment by MbolotSuse** [comment]
Validated image using manifest sha of `7d3c66bd40f8a0f45add026453ed1e7cec0902e1f31170db7e22977feff7dbed` and config sha of `a50b5a93275dd32e949778b0b20743cdb830e0bfd6d69be481a53a3344543d6a`. This was built in DroneCI from commit `77392a65`, which was merged several days after the target commit `944a4654` (i.e. - testing was completed using `rancher/rancher:v2.6-head` as of ~8:30 am CT, which was also `rancher/rancher:v2.6-77392a65423df8507c27d07d0c0a3e85c4d97a5a-linux-amd64`).

Other images used:
| Image | Image Manifest sha |
|-------|--------------------|
| rancher/rancher:v2.6.2 | e9ea04573c21d9126d76d41c2c1311d52fa6835095410a3487d286776ca424fc |


| Test Case Id | Test Case Overview | Test Case Steps | Test Case Status |
|--------------|--------------------|-----------------|------------------|
| 1 | Ensure ETCD can be interacted with in the container using etcdctl with the [provided instructions](https://github.com/rancher/rancher/wiki/How-to-Use-Etcdctl-with-K3s-Embedded-Etcd) | 1. Run rancher/rancher:v2.6-head. <br/> 2. Exec into the container. <br/> 3. Wait for the k3s cluster to fully come up. <br/> 4. Using the earlier etcdctl instructions, issue a `member list` command and ensure that the output is valid. <br/> 5. Issue a http request `curl -i http://localhost:2379`. Ensure a blank reply. | Pass  |
| 2 | Ensure that a deployment can be created in a managed cluster | 1. Run rancher/rancher:v2.6-head <br/> 2. Log into the rancher ui. <br/> 3. Create a deployment using nginx:latest in the local cluster. Use a nodeport service so that the deployment functionality can be verified without running a command inside of the pods. <br/> 4. Issue a http request to the nodeport using `curl -X GET http://$NODE_IP:$SERVICE_NODE_PORT`. <br/> 5. Ensure that the reply is a nginx welcome page. | Pass |
| 3 | Ensure that, using the [established backup/upgrade process](https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/), a cluster running rancher/rancher:v2.6.2 can be upgraded to rancher/rancher:v2.6-head | 1. Run rancher/rancher:v2.6.2. <br/> 2. Ensure that the embedded k3s/rancher UI are up. Do not log into the rancher UI. <br/> 3. Use the backup process to create a backup. <br/> 4. Run the rancher/rancher:v2.6-head image using the backup. <br/> 5. Ensure that the rancher UI came up and review the logs for any unexpected errors. | Pass |
| 4 | Ensure that, using the [established backup/upgrade process](https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/), a cluster running rancher/rancher:v2.6.2 can be upgraded to rancher/rancher:v2.6-head and retain data created using rancher:v2.6.2 | 1. Run rancher/rancher:v2.6.2. <br/> 2. Ensure that the embedded k3s/rancher UI are up. <br/> 3. Log into the rancher UI. <br/> 4. Create a deployment on the local cluster using the nginx:latest image with a nodeport service <br/>  5. Create a remote DO RKE cluster (using a temporary api key) <br/> 6. On the remote DO RKE cluster (through the rancher UI), create a deployment using the nginx:latest image with a nodeport service. <br/> 7. Ensure that both deployments are runnning and return the nginx welcome page when a curl command (as outlined in thest case 3) is used to access the services. <br/> 8. Use the backup process to create a backup. <br/> 9. Run the rancher/rancher:v2.6-head image using the backup. <br/> 10. Ensure that the rancher UI came up and review the logs for any unexpected errors. <br/> 11. Ensure that the deployments still exist on the local/remote clusters, and that their respective services can still be accessed through the previously mentioned curl commands | Pass |
