### ISSUE TITLE
Cluster is not accessible from new UI when the agents are in a bad state; Cluster is accessible in Ember UI in this case

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33882]
**Rancher Server Setup**
- Rancher version: master-head latest `3499046`

**Describe the bug**

**To Reproduce**

- Currently when the cluster is Unavailable, is when in Ember UI, the projects/workloads are not accessible. 
- For instance When the cluster(RKE1) has come up, but the worker nodes are in provisioning state and agents and other system workloads are deploying, from Ember this cluster is still accessible. 
- But from Dashboard now, the cluster has to come up Active completely for us to access the pods.

**Result**

- The cluster should be accessible from the new UI also. 
- Important usecase, is sometimes when things are bad on the cluster, the cluster is still accessible in Ember UI, user can go to System project and look at the pods/workloads.
- But now, from new UI this wont be possible. Only option would be to use kubectl commands.

**Comment by deniseschannon** [comment]
In RKE1, when the cluster is in error state, I am unable to access the system project. 

The new UI requires to have the kube-apiserver up and running in order to select the cluster and see al the k8s resources running on it. 

In the old UI, you would be able to see the state of the "Nodes", but with v2.6, we've differentiated between machines and kube nodes. The kube nodes are the nodes that you can find with "kubectl get nodes" and that is found if you click on the cluster from the main drop down. The machines which are not dependent on the downstream cluster API to be up can be found through the cluster management -> cluster view.
