### ISSUE TITLE
Evaluate Traefik for Load Balancing

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#3391]
http://traefik.github.io/ claims having watchers for docker as a back end and manage dynamic hot reloading of configuration based on those watchers.

Maybe it is worth to have a look at it as a candidate to replace haproxy, more suitable for microservices.

**Comment by vincent99** [comment]
As much as we (really) like replacing things with slightly different versions of the same thing written in Go, I don't think replacing something widely battle-tested with a very young project for no particular benefit is really a great idea.

The docker backend appears to be based on talking to a single docker socket so that wouldn't really work for us managing multiple balancer containers on different hosts balancing to containers on also different hosts.

If we had some reason to need to customize the balancer source, this would be much more compelling than hacking on haproxy in C.

**Comment by blaggacao** [comment]
Very fair. I'm gonna close this, so be it in the archives for reference one day.

**Comment by Toflar** [comment]
Just out of curiosity: Is this being reconsidered for 2.0? Traefik gained a lot of traction the last two years and is widely used. Of course it is not as battle tested as a 17 year old other project but I think one could still say it's become a very stable, reliable and awesome reverse proxy. Also it feels like it just follows the recent trends more closely [announcing](https://github.com/containous/traefik/releases/tag/v1.6.0-rc1) nice features out-of-the-box such as Let's Encrypt wildcard certs and support for native k8s secrets. Given the fact that Rancher 2.0 builds on top of k8s reconsidering the load balancer might at least worth the time.

**Comment by vincent99** [comment]
The de-facto standard ingress controller for k8s is nginx and that's what RKE deploys.  You can still create a cluster with whatever you want in it and use it.
