### ISSUE TITLE
UX: do containers belong to applications or infrastructure? I would say the former. Proposal to move containers page under applications

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3398]
In the Rancher UI, right now running containers are treated as part of the concept infrastructure, they are found under Infrastructure > Containers. I found this association some how confusing for me.

From a UX point of view, I believe containers belong more to the overall concept of "Applications". Containers are per se single applications in my mind, rancher could automatically treat the single standalone container as a Stack with one service and one container, with a scale on 1. 

Therefore I find much user friendly to have the list of all running "Containers" under Applications > Containers instead. Even though some containers are not part of a Stack (standalone containers), in the mind of devops these are just running applications and belongs to the Applications concept and not infrastructure. If a container belong or not belong to a Stack is not a division criteria for being infrastructure or not. 

So, from a UX point of view, I propose to move the Containers page under Applications area and on the containers page make it possible to distinguish which container is part of a Stack and which one is a standalone.

**Comment by vincent99** [comment]
Standalone containers can't just be treated as services with scale=1.  They may be containers imported from the CLI, using images that only exist on that host, etc, and we'd have no idea whether they can be scaled up/down or not, if 2 containers with the same name on different hosts should be the same service or are unrelated, etc.  This would also create a ton of useless services and stacks to cleanup if you ever use the CLI to run anything one-off.  

Containers are what is physically running on the hosts, so moving the containers into applications makes no sense to me.  But the container view header could/should link back to the service instead of host if that's the path you came from..

**Comment by demarant** [comment]
@vincent99

Sorry, but i disagree :)

I understand about the issue with too many tiny stacks that can create too much noise...it was just an example to explain that a single container is a tiny application, the main point of this raised issue.

I think I know why it is like this...in the early Rancher versions, the "Applications" used to be called Projects....if i remember right and were meant for only docker-compose/rancher-compose, what it is called today Stacks. Than u changed the concept to "Applications" ....but ypu forgot that any container is an application x se...

So the applications is a very large concept and it consists of any container running on the hosts. 
Docker calls anything specified in a docker-compose file a service. 

In any of the case above, imo infrastructure should be restricted to what we run containers on, the IaaS part: the hosts, the volumes, the networking and so on.

I don't get the logic of showing runnning containers from stacks (applications) under infrastructure (you cannot even distinguish them from the standalone there). 

Containers are not infrastructure, that is really confusing to me, containers belongs to applications concept. Probably a little poll would help understand what majority users thinks.
