### ISSUE TITLE
Update Rancher server helm chart to allow deploying on k8s 1.22 clusters

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34058]

**Comment by jiaqiluo** [comment]
The rancher server chart in the `release/v2.6` branch does not use any [deprecated API versions in 1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22)

**Comment by jiaqiluo** [comment]
### Root cause
Rancher 2.6.2 and lower does not support k8s 1.22: 
- Rancher cannot be installed in a k8s 1.22 cluster
- Rancher cannot manage 1.22 clusters

Because of that, the `Chart.yaml` in the Rancher Helm chart contains `kubeVersion: < 1.22.0-0` to prevent the chart from installing into a 1.22 and above cluster 

### What was fixed, or what changes have occurred
`kubeVersion: < 1.22.0-0` ==> ``kubeVersion: < 1.23.0-0``

### Areas or cases that should be tested
The HA installation of Rancher into a 1.22 cluster

### What areas could experience regressions?
- HA installation of Rancher
- the upgrade of the local cluster from 1.21 to 1.22

### Are the repro steps accurate/minimal?
n/a

**Comment by brendarearden** [comment]
Available to test on v2.6.3-rc1

**Comment by sowmyav27** [comment]
**Veriffied using 2.6.3-rc1**

Able to deploy Rancher charts on k8s 1.22.3-rancher 1-1 k8s RKE1 cluster.
