### ISSUE TITLE
Validate the specific legacy features on k8s 1.22

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34059]
Only a specific set of legacy features need to be supported on a k8s 1.22 cluster:

[ ] Catalogs/Deploying Apps through ember

The following legacy features do not need to be support: 
-  Alerts v1 (see comment below) 
-  Notifiers v1 (see comment below) 
- Monitoring v1 (comment below) 
- Logging v1
- CIS Scans v1
- Istio 1.5
- Pipelines

**Comment by kinarashah** [comment]
- [x] **Monitoring v1** - Not supported on v1.22 because feature flag `BoundServiceAccountTokenVolume` was unconditionally turned on starting 1.22 and that'll require a v1 redesign to handle prometheus-auth. https://github.com/rancher/rancher/issues/35574

**Comment by sowmyav27** [comment]
On 2.6.3, ember apps are hidden. Related issues:
- https://github.com/rancher/rancher/issues/35347
- https://github.com/rancher/rancher/issues/35351
- https://github.com/rancher/rancher/issues/35352
- https://github.com/rancher/rancher/issues/35353

**Comment by sowmyav27** [comment]
@slickwarren Can you validated alerts v1 and notifiers v1 on 1.22.3 cluster on 2.6.3-rc4 ?

**Comment by slickwarren** [comment]
I've tested this on 2.6.3-rc4 on both local and downstream 1.22.3 clusters:
* add a notifier (under 'legacy' options) for slack
* add an alert and configure it to send to the notifier setup in the previous setup

-> alert does not send to the notifier. Also, watching the 'legacy' -> 'alerts' page, nothing ever goes into a 'firing' state. So that is likely the root of the issue.
