### ISSUE TITLE
Can you add a contributing.md (https://github.com/blog/1184-contributing-guidelines)

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3407]
I ask this because I don't know if this repo is the right one to report UI problems or feature requests.
Also, not quite sure if I'm just being noisy or usefull at all :)

**Comment by vincent99** [comment]
This is the right place; We have too many sub-projects to effectively keep track of issues in each one so in general everything goes here and individual repos have issues disabled.  A couple things that are very separate worlds (like rancher/os) have their own.  Each(ish...) repo's readme has [a section](https://github.com/rancher/ui/#bugs--issues) about this.

**Comment by rvion** [comment]
@vincent99 adding a contributing.md has the advantage of displaying a nice tooltip to users while they fill new issues:

![image](https://cloud.githubusercontent.com/assets/2150990/12649896/df04730c-c5e0-11e5-884e-1d063efa3ee3.png)

**Comment by deniseschannon** [comment]
Notes from rancher/cattle#145

We currently have and implied and assumed process for contributing. We should create an md for all the repos / projects so that it is clear and consistent . Here are some base starting notes i went over with @cjellick 

* Fork the rancherio/cattle repo to your account.
* Clone your fork.
* Run tests locally off of your fork, make sure they pass.
* Branch to start a feature.
* Write Feature and Tests.
* Run tests and make sure they all pass.
* Push branch to your repo.
* Fetch latest changes from rancherio/cattle master and solve conflicts with your changes(if there are any).
* Run tests again
* Submit PR (Label it as WIP if that applies.)
* After Review before changes are merged Squash commits into meaningful commits. If only one that is fine.
* PR is merged.

So that basically describes the standard basic github fork/pull request workflow.  Which is fine, but a CONTRIBUTING.md file is usually about a lot more than that.. So if we're going to create one it should be reasonable complete, with things like:
  - How to report bugs, request features, update documentation (not every contribution is code)
  - Reporting security issues out-of-band
  - Code formatting guidelines
  - Testing rules (is there a test for your change?)
  - How PR get approved and by whom
  - Contributor license agreement/Signed-Off-By
  - IRC channels to join
  - Code of conduct(probably not relevant for now)

**Comment by will-chan** [comment]
Closed due to inactivity.

**Comment by bradjones1** [comment]
Raised the question of a contributor code of conduct at https://github.com/rancher/rancher/issues/14324
