### ISSUE TITLE
Create a cloud credential to support S3 type to be used for etcd snapshots with RKE2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34088]

**Comment by davidnuzik** [comment]
**_Issue description is blank - asked in slack - basically need to check if s3 is working now with rke2. (It was prior but changes made so check again -- and should be able to fully validate now in Rancher)._**

**Comment by davidnuzik** [comment]
**My checks Failed**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6-head `f81199694` 8/16/21 9:08 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc6+rke2r2
 
Validation steps:

1. Due to [this bug](https://github.com/rancher/dashboard/issues/3847), create an s3-compatible cloud credential first as this will not work during cluster creation. Supply the required key and secret (fake values pictured but not used). Supply the optional bucket and region.
![image](https://user-images.githubusercontent.com/45179589/129608219-e0b56147-38db-48b6-a92e-cecf3c302f7e.png)

Note, the UI appears to send the correct request body for `cloudcredentials` POST:
![image](https://user-images.githubusercontent.com/45179589/129608743-190892c6-29b2-4822-a34a-f1415dce9bb8.png)

The response as well appears correct. The secret is not mentioned probably for security reasons.
![image](https://user-images.githubusercontent.com/45179589/129608867-5a457192-6741-41af-9652-0bde66139997.png)


2. Create and rke2 cluster. In my case I used the DigitalOcean node driver. I created a 1-node cluster. Under the cluster configuration section, pick etcd, then pick the s3-compatible cloud credential we created earlier. Enter a folder. Click Create.
The UI appears to send the correct request body for `provisioning.cattle.io.clusters` POST:
![image](https://user-images.githubusercontent.com/45179589/129609135-acec1706-efc2-4dc4-a49d-454918053b1e.png)
This appears as expected to me because I just specified the folder, otherwise the necessary key, region, secret, and bucket are supplied in the cloud config.

The response as well appears correct.
![image](https://user-images.githubusercontent.com/45179589/129609279-9da548de-923b-45d6-b5a2-93a91fc2614f.png)


3. The cluster will instantly have an error and not provision. I could be mistaken but it appears as though this is likely a backend issue. I immediately see the following in the UI and rancher server logs:
![image](https://user-images.githubusercontent.com/45179589/129609512-fed15261-86ed-4c9a-8271-8b8b6f8a5749.png)

```
2021/08/16 18:02:49 [ERROR] error syncing 'fleet-default/dave-test2-s3simple': handler provisioning-cluster-remove: Cluster.provisioning.cattle.io "dave-test2-s3simple" is invalid: spec.rkeConfig.etcd.s3.bucket: Required value, handler rke-cluster: failed to create fleet-default/dave-test2-s3simple rke.cattle.io/v1, Kind=RKEControlPlane for rke-cluster fleet-default/dave-test2-s3simple: RKEControlPlane.rke.cattle.io "dave-test2-s3simple" is invalid: spec.etcd.s3.bucket: Required value, requeuing
```
 
Additional Info:
I'm not quite sure what precisely is wrong. Maybe the backend expected to get the bucket inetcd>s3>bucket in the `provisioning.cattle.io.clusters` POST? This is null as expected though because this is specified in the s3-compatible cloud credential...

**Comment by davidnuzik** [comment]
**_Please note, there are other s3 bugs at present - I just checked that the cloud credential works - not that snapshot/restore works perfectly here, that will be covered in separate issues._**
 
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6-head `0935a90` 8/24/21
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3+rke2r2
 
Validation steps:

1. Create an RKE2 cluster. We will create our cloud credential on the cluster creation form. This works as expected the UI passes correct request body and server responds correctly.
![image](https://user-images.githubusercontent.com/45179589/130685294-b9acbc19-bb89-42d5-9e80-cac0db4befbe.png)

2. Also try creating a cloud credential on the cloud credentials page. This works correctly as well. I can provide a cluster with this cloud credential as well and take s3 snapshots.

I no longer identified any issues with the s3-compatible cloud credential. Further testing of s3 snapshot/restore will be handled separately in other issues.
