### ISSUE TITLE
Rancher Storage Pool with gluster-convoy does not seem to work on v0.56.0-rc3

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3408]
I did 2 attempts on existing and clean rancher setup, following http://docs.rancher.com/rancher/rancher-services/storage-service/, but it's not working. Also, documentation about host labels could have a small example because it's not completely clear.

![image](https://cloud.githubusercontent.com/assets/2150990/12557173/cd6a3b4e-c389-11e5-8568-e3b73fbcbf5f.png)

![image](https://cloud.githubusercontent.com/assets/2150990/12557190/da2376e8-c389-11e5-96d4-21a3d9f5e9b2.png)

![image](https://cloud.githubusercontent.com/assets/2150990/12557108/9183e94a-c389-11e5-81a6-856c9a141915.png)

![image](https://cloud.githubusercontent.com/assets/2150990/12557118/9d7dc2b6-c389-11e5-8bf2-c9be8fbfa136.png)

#### List of containers 

![image](https://cloud.githubusercontent.com/assets/2150990/12557065/5dc4f5c2-c389-11e5-938c-e4a2b3e348ba.png)

**Comment by sangeethah** [comment]
This issue is similar to the issue tracked in https://github.com/rancher/rancher/issues/3265 and should be resolved with v-0.2 version of convoy-nfs template which will be made available along with the next rancher-server release . Also with this version , there will be no dependency on the host labels and convoy-gluster will get deployed in all the hosts in the setup.

**Comment by rvion** [comment]
yay, perfect, thanks !
