### ISSUE TITLE
RKE2 Installed version does not necessarily match the `kubectl get nodes` reported version on Linux

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#34095]
**Describe the bug**

When installing Rancher RKE2 `v1.21.3-rc4+rke2r2`, the version reported by `kubectl get nodes` on a Linux box is reported as `v1.21.3+rke2r1`. This obviously does not match and is caused by https://github.com/rancher/rke2/issues/1576

**Comment by brandond** [comment]
This issue affects RCs only, and will be addressed via developer documentation, but not fixed. See.https://github.com/rancher/rke2/issues/1576#issuecomment-895527963

**Comment by cjellick** [comment]
Yes, @deniseschannon and I discussed this and we agreed to allow for this mismatch, but to keep an eye on it to see if it causes major confusion. If it does, we may need to revisit.

Note that we initially thought the only impact of this mismatch would be confusion, but it actually also causes a legitimate bug: https://github.com/rancher/rancher/issues/34067. We've addressed that bug independently by bumping the k8s version.

RKE2 team will have to put some guardrails in place to make sure we keep things aligned.

**Comment by cjellick** [comment]
These two mismatched because we broke our kubernetes build out into a separate step. It does not need to be incremented every time we cut an rke2 rc, because generally k8s itself is not changing, only the rke2 specific bits are. 

We will bump the hardened-kubernetes image tag prior to tagging the first RC, so that the tag will match on the GA release, without having to commit another change after the final RC to adjust the image tag.

Here's examples of what you can expect to see:
```
rke2 v1.19.12+rke2r1     => kubernetes v1.19.12+rke2r1
rke2 v1.19.13+rc1-rke2r1 => kubernetes v1.19.13+rke2r1
rke2 v1.19.13+rc2-rke2r1 => kubernetes v1.19.13+rke2r1
rke2 v1.19.13+rke2r1     => kubernetes v1.19.13+rke2r1
```

I'm going to close this as won't fix, but we'll keep an eye on it and if this causes persistent confusion, we will revisit and devise a new strategy.
