### ISSUE TITLE
Review Helm Feature Charts in Rancher for k8s 1.22 support

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34125]
We need to review all the helm charts within Rancher to put kubeversion limits

- system-charts
- charts (dev-v2.6/release-v2.6 branches)

**Comment by cbron** [comment]
We'll add two annotations to feature charts: 
* `catalog.cattle.io/kubeVersion` - This will be a semver range, just like helm's. The difference being that ours will only hide the chart inside the UI, and still allow users to edit (helm upgrade) the chart. The helm kubeVersion disables edit's of installed charts, otherwise we could just use that. 
* `catalog.cattle.io/upstreamVersion` - This will be used to specify what the underlying upstream version of a chart is to avoid accidental downgrades with our 100 versioning system. 100.1.0+up3.2.0 -> 101.0.0+up3.1.0 would be disallowed. We are only doing the annotation here, to avoid updating all old charts yet again. The functional work will be done in: https://github.com/rancher/rancher/issues/35469

@kinarashah can you make a UI issue, so that the `kubeVersion` is used to filter out properly there.

**Comment by brendarearden** [comment]
UI Issue: https://github.com/rancher/dashboard/issues/4563

**Comment by cbron** [comment]
Above issue is in test. Seems only thing left here is to update prior released charts to have these annotations.

**Comment by brendarearden** [comment]
https://github.com/rancher/charts/pull/1642

**Comment by cbron** [comment]
Planning on still doing this one, though its not critical, but it needs to be done anyway and doesn't need real QA.

**Comment by brendarearden** [comment]
I am splitting this into two seperate issues. 

This issue will be used to track the feature charts OOB release for adding the `kube-version` annotation to limit charts from showing in the UI. This portion of the 1.22 support was bumped from v2.6.3 to OOB before v2.6.4

https://github.com/rancher/rancher/issues/35897 will be used to track the system-charts support for kubeVersion in v2.6.3

**Comment by sowmyav27** [comment]
@MKlimuszka Is this needed for 2.6.5?

**Comment by Jono-SUSE-Rancher** [comment]
@PennyScissors & @MKlimuszka - What happened with this ticket? It was in review for many days and then bumped back to working and then bumped out to v2.6.6. I understand the bumping based on timelines for v2.6.5 but it seems like something that is coming a bit late to get bumped, considering we're defaulting 1.23 in 2.6.5 right?

**Comment by PennyScissors** [comment]
@Jono-SUSE-Rancher I need Arvind's review for this, but he was swamped with other work. This got bumped because it can happen at any time, doesn't need to wait until the 2.6.6 charts release (sort of like OOB).

**Comment by brandonsuse** [comment]
**SCOPE:** For this ticket, we will run P0 test cases for 1.22 k8s version of a cluster against all charts.

**Comment by ronhorton** [comment]
verified feature charts in v1.22.11-rancher1-1
