### ISSUE TITLE
Restarting Rancher loses changes to Host names

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3414]
Rancher 0.56
Our docker hosts are cloned in VMware and consequently have the same hostname internally (though different IP addresses via DHCP).
When they register with Rancher, the Hosts are given the same hostname; however we can edit this to identify the VM number.
However, when Rancher is restarted (such as to upgrade) then these changes are lost, and the Host names revert to the actual VM hostnames.

**Comment by sshipway** [comment]
In fact, it seems that any changes to hostnames are reverted after a few minutes to whatever the host in question thinks its hostname is

**Comment by ibuildthecloud** [comment]
@sshipway Yep we broke this.  Basically we wanted if the hostname of the server changed for that to be reflected in the UI.  Kind of forgot about users renaming the host.  We will fix this so both situations work.

**Comment by sshipway** [comment]
Thatnks; I can see the benefit for some of hostname changes trickling through, however many people (including us) who use VMWare or equivalent will have a chain of identical clones docker hosts with the same name using DHCP, and you then end up with everything called 'host' ....
Hard to support both cases, though I suppose you could have a flag for if the hostname was overridden

**Comment by RVN-BR** [comment]
+1 to follow. noticed the same

**Comment by RVN-BR** [comment]
On a related note, where does the agent get the hostname from?

```
vagrant@ubuntu-03:~$ hostname
ubuntu-03
vagrant@ubuntu-03:~$ cat /etc/hostname
ubuntu-03
```

![image](https://cloud.githubusercontent.com/assets/1218902/12656743/e6b8dc54-c5e6-11e5-85f0-8c7122d74f13.png)

**Comment by vincent99** [comment]
@sshipway The new behavior we [were thinking](https://github.com/rancher/python-agent/pull/218) would be that the `name` field is empty/null by default and the host agent continuously updates the `hostname` field.

Then the UI would show the `name` if set, and the `hostname` otherwise, so you could override the display if you want to without fighting the agent.

But now that I'm typing this out... @ibuildthecloud This will break metadata unless we do the same `name || hostname` logic when producing the answers file, because [only `name` is magic there](https://github.com/rancher/rancher-metadata/blob/master/main.go#L31-L34).

**Comment by vincent99** [comment]
This is (will be) in 0.57

**Comment by tfiduccia** [comment]
Version - master UI 2/4 (you will see it in next build, which will be 0.58)
Verified fixed

Comment: After the hostname is changed, the API is not sending a change request to UI, so to see it you have to refresh the page.  There is a separate issue entered for getting change request for Host info changes - #3523
