### ISSUE TITLE
Add tolerations cusomization in values for Rancher helm chart

### ISSUE THREAD

**Issue by gartemiev** [rancher/rancher#34159]
Hi, We've noticed that there is no way to specify custom tolerations via rancher chart values. As a result with using taints on one of our EKS clusters We can not deploy rancher there. It would be great if you allow to customize tolerations on chart level via values.

**Comment by MbolotSuse** [comment]
## Validation for Rancher-Webhook

### Background
In order to have rancher fully support tolerations, the components that rancher deploys as part of its functionality (fleet, webhook) need to support tolerations before rancher can be changed to pass on tolerations to these applications. The webhook was changed to support specification of tolerations in line with this change.

The webhook-specific changes will ship with 2.6.4.

### Test Case

#### Setup
Setup Type: HA, RKE v1.20.12-rancher1-1 (Digital Ocean)
Rancher Helm Chart Version: `2.6.4-rc8`
Webhook helm Chart Version: `1.0.4+up0.2.5-rc2`

#### Test Case
1. Create an RKE cluster using the above setup.
2. Install rancher `v2.6.4-rc8` following the [rancher docs](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/).
3. Log into rancher. In the UI - ensure that the webhook deployment has been created with version `0.2.5-rc2`. Ensure that the chart version is set to the above version, and that the tolerations are set to an empty value.
4. Ensure that the webhook is working by creating a request that will be rejected by the webhook, and ensuring that the request was rejected.
5. Update the chart (through the UI) with a toleration and ensure that it is applied to the deployment.
6. Uninstall the chart (through the UI) and ensure that the pre-delete pod does not enter a failed state.
7. Wait for rancher to re-deploy the chart. Ensure that it is deployed successfully.
8. Uninstall the chart (through the UI). Ensure that the pre-delete pod does not enter a failed state.

### Status
Validation Passed.

### Notes
- Chart did upgrade itself to `0.2.5-rc3`. This is not an issue with the test case but should be noted.

**Comment by samjustus** [comment]
SURE-4362

**Comment by manno** [comment]
The SURE issue is resolved, is this still necessary? The existing Fleet PR https://github.com/rancher/fleet/pull/703 has many conflicts.
