### ISSUE TITLE
Rancher 2.6 - updating/upgrading  aks cluster

### ISSUE THREAD

**Issue by claudioser** [rancher/rancher#34161]
**Rancher Server Setup**
- Rancher version: Rancher 2.6 rc2
- Installation option (Docker install/Helm Chart): Helm on RKE1
   
**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Downstream 
   - AKS

**Describe the bug**
when trying to upgrade from 1 version ok aks to another, I am getting this error, even though all Im actually modifying on the ui is the actual version desired ,
![image](https://user-images.githubusercontent.com/53047113/128998277-ce0378a1-8c69-4224-8158-6f1de6485962.png)

Furthermore the upgrade never starts or finishes. If I try to edit the cluster again, It thinks its already 1.19.11, even though nothing happens . Error message stays on UI, but cluster functionality is working.

![image](https://user-images.githubusercontent.com/53047113/128998596-5a6c1faa-ccc6-4bf3-b7a7-7f9b795e2e97.png)

**To Reproduce**
 happens on both aks clusters provisioned from rancher or existing aks clusters imported to rancher

**Additional context**
 on a probable similar context, when upgrading get  options for upgrading up to 1.21.2 from UI , but on Azure - AKS, only have up to 1.20.7

![image](https://user-images.githubusercontent.com/53047113/128999094-188a9b54-f645-437e-a7e9-9f4627a0329e.png)

![image](https://user-images.githubusercontent.com/53047113/128999120-9db09277-7753-4836-bfc0-556ba0843ce3.png)

**Comment by prabalsharma** [comment]
**Issue1:** 
I could not repro the issue. I tried it on 2.6-rc4. RKE_VERSION=v1.3.0-rc15
I was able to upgrade clusters k8s version from 1.19.9 to 1.19.11

**Issue2:**
Its a UI issue. Not sure how extra versions are coming up. AFAIK version is is being pulled from Azure. @codyrancher any idea?

**Comment by codyrancher** [comment]
@prabalsharma this looks to be a backend issue. All of the versions in the screenshot are being returned by aksVersions.

![image](https://user-images.githubusercontent.com/55104481/130155066-60433e40-410d-41fe-8d0e-cd4e7d3f8768.png)

**Comment by prabalsharma** [comment]
Thanks Cody.

**Comment by paynejacob** [comment]
waiting on https://github.com/rancher/charts/pull/1421

**Comment by prabalsharma** [comment]
**part 2 of issue (list of k8s version):** 

I am **reopening** this issue as I can still see the extra k8s versions in the list, when I click on `Edit Config`. 

I did some digging and found out that AKS has 2 different k8s version list: **One is which you get while creating a cluster**

<img width="883" alt="Screen Shot 2021-08-23 at 2 53 49 PM" src="https://user-images.githubusercontent.com/3749546/130524444-679f14f6-39e4-41c7-8269-64fe9638fff5.png">

and **the other is when you try to upgrade k8s version**

<img width="495" alt="Screen Shot 2021-08-23 at 2 55 19 PM" src="https://user-images.githubusercontent.com/3749546/130524618-0c7c771e-0deb-4e17-b17d-cd7c999e01d5.png">

it looks like we are fetching the one for cluster creation, for both "Creation and Edit".


Regarding part 1 ( error on k8s version upgrade): @claudioser I could not repro the error. If you have some more info about the issue I will be happy to look at it again. Otherwise, can you please re-try it with 2.6-head or latest RC and let me know how it goes.

**Comment by claudioser** [comment]
@prabalsharma - part1 of the issue is now fixed. tested on rc_6

**Comment by sowmyav27** [comment]
**On 2.6.0**

- Create a cluster AKS with k8s 1.19
- Edit config on the cluster
- All the k8s versions are displayed.

<img width="897" alt="Screen Shot 2021-09-18 at 1 16 57 PM" src="https://user-images.githubusercontent.com/26032343/133907464-a895adb6-542d-4447-b801-33fde393aa68.png">
