### ISSUE TITLE
Unable to Execute Shell on pod running on windows node from Cluster Explorer

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#34197]
**Rancher Server Setup**
- Rancher version: rancher:2.5.9
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 
- Proxy/Cert Details: selfsigned

**Information about the Cluster**
- Kubernetes version: v1.20.9-rancher1-1 (local & downstream)
- Cluster Type (Local/Downstream): downstream Windows cluster (vxlan) based on `Windows 2019` updated 07.14.21 `ami-05a418fd6eb36fd5b`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**
After deploying a pod with eg. `ranchertest/testcontainer:windows` or `ranchertest/testnginx:windows` image from Cluster Explorer user is not getting a shell when clicked on `Execute Shell` but only a message in a shell window:

`container 1c8746c569636c094dac395af7e23a19d3a4dba2d9a711c270c6e991a1e63693 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)`

:exclamation: **Other useful info:**
* It works correctly from Ember UI where cmd.com in running normally.
* Also it got fixed in Explorer once I upgraded to `rancher:2.6.0-rc1`

**To Reproduce**
* In Cluster Explorer create a ns and Deployment with one Replica of `ranchertest/testcontainer:windows` container.
* Select Workload/Pods pane and look for the new pod, then select `Execute Shell` for the pod.

**Result**
No shell will appear

**Expected Result**
Shell like cmd/pwsh will appear

**Screenshots**
![win_shell](https://user-images.githubusercontent.com/12828077/129209896-ec2bd973-db85-4e7b-b9ee-45554b86563f.png)

**Comment by sirredbeard** [comment]
@rosskirkpat Is this related to https://github.com/rancher/windows/issues/102 and https://github.com/rancherlabs/rancher-security/issues/947?

**Comment by rosskirkpat** [comment]
@thehejik Would you be able to share additional information on the user trying to execute shell? Were you using the built-in `admin` user or another user? If it was a different user, would you be able to provide the user's role, any custom permissions, and what (if any) role the user inherited?

**Comment by thehejik** [comment]
@rosskirkpat I don't have access to aws nor windows anymore. I'd say it was failing with any account.

**Comment by slickwarren** [comment]
tested the following on v2.6.3 and v2.5.11:
* deploy windows workload:
  * as admin -- pass
  * as standard user, cluster owner -- pass
  * as standard user, project owner -- pass
* exec shell on windows workload:
  * as admin -- pass
  * as standard user, cluster owner -- pass
  * **as standard user, project owner -- fail**
    * this seems to align with the findings from the [linked security](https://github.com/rancherlabs/rancher-security/issues/947) issue
* deploy linux workload:
  * as admin -- pass
  * as standard user, cluster owner -- pass
  * as standard user, project owner -- n/a (unable to schedule on a node due to rbac restriction)
* exec shell on windows workload:
  * as admin -- pass
  * as standard user, cluster owner -- pass
  * as standard user, project owner -- pass

**Comment by slickwarren** [comment]
This appears to have regressed as of v2.6.4-rc2:
as an admin/standard user, I can no longer use the `execute shell` functionality. I get a disconnect shortly after clicking the button to open a shell.

**Comment by phillipsj** [comment]
This is fixed here: https://github.com/rancher/rancher/pull/37214

**Comment by phillipsj** [comment]
### Root cause

The project owner role did not have permissions to read the node correctly. This caused the node OS check to fail. The default was set to Linux and bash and that is why even with the failure it continued to work for Linux pods. With Windows pods, it would fail because bash isn't available for Windows.
 
### What was fixed, or what changes have occurred
 
The RBAC for project owner was updated to include the ability to read nodes.

### Areas or cases that should be tested

The use cases listed above should be tested:  https://github.com/rancher/rancher/issues/34197#issuecomment-1005281229

### What areas could experience regressions?
 
RBAC for Project Owner could potentially see regressions, that is unlikely since it added permissions.

### Are the repro steps accurate/minimal?

Yes

**Comment by slickwarren** [comment]
tested on v2.6-head (228a585):
* deploy windows cluster (v1.22.8+rke2r1) using windows 2022
* deploy a windows workload
* as admin, shell into the workload -- pass
* as admin, execute commands in the shell (cmd, powershell) -- pass
*  as standard user, cluster owner shell into the workload -- pass
* as standard user, cluster owner execute commands in the shell (cmd, powershell) -- pass
* as base user, project owner shell into the workload -- pass
* as base user, project owner execute commands in the shell (cmd, powershell) -- pass
* as base user, project member, user is able to view resources but not use shell -- pass
