### ISSUE TITLE
Can't add Disks in VIRTUAL MACHINES 

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#3419]
![qq20160126-0](https://cloud.githubusercontent.com/assets/11401602/12576219/14fd0bf8-c44d-11e5-9389-35823e4f5631.png)
![qq20160126-1](https://cloud.githubusercontent.com/assets/11401602/12576224/1ee9f7de-c44d-11e5-940d-a71e2c5e7ec1.png)

I use the VIRUAL MACHINES in rancher v 0.56.0 ,
I have a StoragePool,
but when I add new vm, i can't add any disk, because the Driver show nothings, what should i do?

**Comment by vincent99** [comment]
The stack where convoy-gluster is deployed currently has to be called `convoy-gluster`, because that becomes the driverName on the pool and the UI only shows drivers it knows are supported.  This will be fixed with a separate field to explicitly identify which pools can be used.

**Comment by cjellick** [comment]
@vincent99 @ibuildthecloud this could be revisited once @ibuildthecloud's volume driver changes are merged.

**Comment by cjellick** [comment]
But beyond my last comment, this is convoy-gluster specific. Can we move out of 1.2.0?

**Comment by deniseschannon** [comment]
@xrain0610 Please note that we have removed GlusterFS and Convoy Gluster from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  However, due to lack of active maintenance, we cannot recommend this solution going forward.

Instead, we recommend and certify Convoy NFS, which is actively maintained by Rancher. As a user, you can get GlusterFS support directly from Red Hat and use it in Rancher using Rancher's NFS plugin. 

Due to these changes regarding glusterfs and convoy gluster, we will not be addressing this bug for 1.2.0

**Comment by deniseschannon** [comment]
We have removed away from convoy gluster and I believe the VM driver has also switched to being a text box. Closing for now.
