### ISSUE TITLE
When user created with user-base `global permission` and added in the cluster with `Manage nodes` custom membership, nodes are not visible in the cluster management, machines tab

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34288]
**Rancher Server Setup**
- Rancher version: v2.6-head 72986b2
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: `v1.21.4 and v1.21.3-rc6+rke2r2`
- Cluster Type (Local/Downstream): `RKE1 and RKE2` Infrastructure provider
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
Users with `Manage nodes` custom membership in the cluster, should be able to see the nodes and download the keys with global permissions as `user-base`.

**To Reproduce**
1. From users and auth, create a user - user1 , with global permissions set to `user-base`
2. Create an rke1 and rke2 node driver all roles cluster.
3. As an admin, add user1 to both rke1 and rke2 in cluster with the following permissions --> RBAC --> custom `Manage nodes`.
4. Login as user1

**Result**
rke1:
**Cluster management:** Users cannot see any nodes and an error is displayed `{ "message": "Unknown schema for type: management.cattle.io.nodetemplate", "statusCode": 500 }

**Expected Result**
`Download ssh keys` should be available for rke1 clusters with the node listed in the `cluster management` page.

**Screenshots**

<img width="500" alt="Screen Shot 2021-08-17 at 2 36 29 PM" src="https://user-images.githubusercontent.com/38144301/129804235-b0d87ef0-20a8-4039-a14f-acb7e6c4e791.png">

**Additional context**
for rke2 clusters, users can list the nodes in the cluster management page and can download the ssh keys with the global permissions set to `user-base`  and custom `Manage nodes` membership in the cluster.

Can link the setup.

Ref: https://github.com/rancher/rancher/issues/33573

**Comment by vincent99** [comment]
Works for me... 

![image](https://user-images.githubusercontent.com/753917/130522675-aaa2a445-19c5-46d8-a2e5-a50a77bf86da.png)

**Comment by deniseschannon** [comment]
v2.6-head b8a44fa

Added a userbase user to a cluster with manage nodes shows the following behavior:

RKE1: I am able to view machine pools as well as scale up/down buttons and Download SSH keys button. 

But I am unable to delete nodes due to a permission issue, Filed a new issue: https://github.com/rancher/rancher/issues/34411
```
{ "type": "error", "links": {}, "code": "PermissionDenied", "message": "Method DELETE not supported", "status": 403 }
```
![Screen Shot 2021-08-23 at 9.27.06 PM.png](https://zube.io/files/rancher/50c18d08499dca9c94e14ff560cfd324-screen-shot-2021-08-23-at-9-27-06-pm.png)

RKE2: Machines are not recognized as being in a node pool, so I cannot scale up or down the node pool. I have access to the SSH shell and Download SSH key. Used the same issue that limits standard users as cluster members from being able to view machines in machine pools. https://github.com/rancher/rancher/issues/34404

![Screen Shot 2021-08-23 at 9.26.24 PM.png](https://zube.io/files/rancher/98120087c7d3ff64a59d7c65a665404e-screen-shot-2021-08-23-at-9-26-24-pm.png)

**Comment by deniseschannon** [comment]
@anupama2501 Your original use case has been fixed, but 2 different issues were created. I'd like to have you validate your use case before I close the issue.

**Comment by anupama2501** [comment]
Verified on rancher v2.6-head b43e4d9
 

- Created a user - u1 with global permissions set to `userbase`.
- Verified rke1 clusters, all machine pools are visible for the user u1.
- can scaleup/down the nodes - verified in the backend as well.
- downloaded ssh keys for the nodes and able to login with the ssh key downloaded.


As pointed by @deniseschannon not able to delete the nodes for rke1 clusters fails with the error `{ "type": "error", "links": {}, "code": "PermissionDenied", "message": "Method DELETE not supported", "status": 403 }
` 
but the same nodes[rke1 cluster nodes] can be deleted from explore cluster --> nodes page.


Since the original issue is resolved and the other issues are being tracked separately, closing this ticket.
