### ISSUE TITLE
Node Taints aren't being applied to etcd/control plane nodes for nodes (machine pools and custom)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34295]
**Rancher Server Setup**
- Rancher version: v2.6-head

**Describe the bug**

Currently, Rancher is expected to add taints to the etcd/control plane nodes to prevent workloads from being scheduled on them.

These taints are not being added to custom nodes. 

**To Reproduce**
 
1. Create a custom cluster  or Create a node provisioned cluster with 1 etcd, 1 control plane, 1 worker as individual nodes
2. Review the taints on the node.

**Result**
No taint on the node. 

In the annotation of the node of what is passed to RKE2, it looks like the node taint is blank for a node provisioned cluster. 

```
rke2.io/node-args: '["server","--agent-token","********","--cni","calico","--disable-apiserver","true","--disable-controller-manager","true","--disable-kube-proxy","false","--disable-scheduler","true","--etcd-expose-metrics","false","--etcd-snapshot-retention","5","--etcd-snapshot-schedule-cron","0
      */5 * * *","--node-label","rke.cattle.io/machine=65310b60-bbd3-4eb5-8fba-7dcfc71f2e43","--node-taint","","--private-registry","/var/lib/rancher/rke2/etc/config-files/private-registry","--protect-kernel-defaults","false","--token","********"]'
```

**Expected Result**

Expect taints on these nodes

**Screenshots**

**Additional context**

One or both of these PRs failed to actually apply taints on nodes for node provisioned clusters and custom clusters. 

Merged PR to add taints:https://github.com/rancher/rancher/pull/33768
Merged PR to correctly parse taints for custom nodes: https://github.com/rancher/rancher/pull/33797/files

**Comment by deniseschannon** [comment]
Please test through custom AND machine pools

**Comment by sowmyav27** [comment]
To validate:
- Deploy customer clusters
- Deploy machine pools
- Verify taints are available on the node (via kubectl) and are seen on the UI in Kube Nodes page.
- Verify on both the clusters:
- - RKE2 components (CNI/coredns) can still be scheduled onto control plane nodes
- - Other workloads shouldn’t be scheduled on the etcd/control plane  nodes

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Environment:**

Rancher version: v2.6-head (e3d4b6d19) pulled at 8/18/21 3:28 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc6+rke2r2
 
**Validation steps:**


NOTE: For each use case, used canal CNI instead of Calico as Calico currently has a bug that can affect multi-node clusters: https://github.com/rancher/rancher/issues/34300

_**Use Case 1 - Rancher-provisioned rke2 cluster:**_

1. Create an RKE2 cluster with Rancher - in my case I used the digitalocean node driver:
- 1st node pool is etcd-only role with 3 machines
- 2nd node pool is control-plane-only role with 2 machines
- 3rd node pool is worker-only role with 3 machines
3. Observed cluster came up successfully. Observed that CNI and CoreDNS look good and are scheduled onto cp/etcd nodes, as expected (they are tolerated). Observed the non-worker nodes are tainted, as expected.
rke2-canal DaemonSet is still scheduled to all nodes (does tolerate):
![image](https://user-images.githubusercontent.com/45179589/129981822-a946d335-c3f7-4f27-8498-bf0ba0a8c43b.png)

rke2-coredns has availability and is scheduled to a non-worker node as we can see here (does tolerate):
![image](https://user-images.githubusercontent.com/45179589/129982076-25539e37-2141-4ca6-9fb1-6c99e3503eaa.png)


Control plane taint:
![image](https://user-images.githubusercontent.com/45179589/129981418-4b23cba8-f744-414f-979b-d9d654501830.png)
Etcd taint:
![image](https://user-images.githubusercontent.com/45179589/129981467-6941557c-c391-434a-9c36-c7869db7d4f7.png)
Worker (not tainted):
![image](https://user-images.githubusercontent.com/45179589/129981538-5ce72aaa-486a-4708-8cc9-f1ea95afc4fd.png)

4. Create a DaemonSet workload. Image doesn't matter but I picked `nginx:latest`
5. Observed that the workload is ONLY deployed to the 3 worker nodes (count is 3, not 8, as expected)
![image](https://user-images.githubusercontent.com/45179589/129981608-d7761a15-b510-4a4a-ba64-bc83191feb36.png)

Note, prior to the fix, I saw that when I created such a deployment it was scheduled to 8 nodes (all of them) in the same node pools configuration. I can confirm the issue is indeed fixed.

_**Use Case 2 - User-provisioned rke2 cluster (Custom cluster):**_

1. Create a 3-node custom RKE2 cluster:
- 1st node is etcd-only role
- 2nd node is control-plane-only role
- 3rd node is worker-only role

2. Otherwise, perform the steps above in Use Case 1 precisely the same, except that we will see a max count of 1 for my DaemonSet nginx workload test.

No issues observed in Use Case 2 checks as well.
 
**Additional Info:**
