### ISSUE TITLE
Rancher 2.6 RKE2 w/ Calico scaling issues

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#34300]
**Rancher Server Setup**
- Rancher version: v2.6-head (c10ef4b078b8fdbbaef089da103ab012a53eed44)
- Installation option (Docker install/Helm Chart): docker
- Proxy/Cert Details: ngrok tls forward

**Information about the Cluster**
- Kubernetes version: v1.21.3-rc6+rke2r2
- Cluster Type (Local/Downstream): EC2

**Describe the bug**

When scaling an RKE2 node through the Rancher UI a calico pod may enter a bad state and cause the cluster-agent to fail, and cause the cluster to enter an error state like:
```
Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded
```

**To Reproduce**
 
Scale an RKE2 cluster down - failure is random

**Result**

Cluster error state

**Expected Result**

No error state

**Screenshots**
<img width="1431" alt="Screen Shot 2021-08-17 at 3 53 35 PM" src="https://user-images.githubusercontent.com/1999874/129912465-fc52eea3-f2a0-4afa-a35f-908a95ccebc5.png">

**Additional context**

Calico pod logs contain fatal errors like:
```
[FATAL][1632] tunnel-ip-allocator/startsyncerclient.go 73: Failed to connect to Typha error=dial tcp 192.168.124.167:5473: i/o timeout
```
Typha pods are all up and running without error

When the calico pod is experiencing failure on the node which runs coredns then the cluster-agent will fail with errors like the following:
```
ERROR: https://xxxxxx.ngrok.io/ping is not accessible (Could not resolve host: xxxxxx.ngrok.io)
```

**Comment by manuelbuil** [comment]
It seems the problem is that the calico.vxlan interface is gone. As a result, no traffic across nodes is working and calico-node pods cannot connect to typha pod. Only the calico-node pods that have the typha pod locally are working:
```
NAME                                      READY   STATUS    RESTARTS   AGE    IP                NODE                 NOMINATED NODE   READINESS GATES
calico-kube-controllers-748bcb7bb-qw6xd   1/1     Running   7          125m   10.42.221.1       ip-192-168-120-28    <none>           <none>
calico-node-4qdbp                         1/1     Running   0          138m   192.168.111.134   ip-192-168-111-134   <none>           <none>
calico-node-6x8qp                         0/1     Running   0          132m   192.168.120.28    ip-192-168-120-28    <none>           <none>
calico-node-r724w                         1/1     Running   0          134m   192.168.114.163   ip-192-168-114-163   <none>           <none>
calico-node-rhq5m                         0/1     Running   0          131m   192.168.105.139   ip-192-168-105-139   <none>           <none>
calico-node-tfk58                         1/1     Running   0          133m   192.168.79.196    ip-192-168-79-196    <none>           <none>
calico-typha-59465cbbf7-7xhvd             1/1     Running   1          133m   192.168.79.196    ip-192-168-79-196    <none>           <none>
calico-typha-59465cbbf7-fqsrn             1/1     Running   0          134m   192.168.114.163   ip-192-168-114-163   <none>           <none>
calico-typha-59465cbbf7-vhq29             1/1     Running   0          138m   192.168.111.134   ip-192-168-111-134   <none>           <none>
```
The vxlan tunnel should be created by felix which is running inside the calico-node. When checking its logs, I can see this repeating all the time:
```
2021-08-18 15:31:58.224 [INFO][15654] felix/route_table.go 249: Calculated interface name regexp regex="^vxlan.calico$"
2021-08-18 15:31:58.224 [INFO][15654] felix/vxlan_mgr.go 348: VXLAN tunnel device thread started. mtu=8951 wait=10s xsumBroken=true
2021-08-18 15:32:41.469 [INFO][15756] felix/route_table.go 249: Calculated interface name regexp regex="^vxlan.calico$"
2021-08-18 15:32:41.469 [INFO][15756] felix/vxlan_mgr.go 348: VXLAN tunnel device thread started. mtu=8951 wait=10s xsumBroken=true
```
My hypothesis is that the code that should create the vxlan tunnel is getting stuck somewhere. I'll increase the verbosity of the logs and check the code to see if we understand where this is getting stuck

**Comment by manuelbuil** [comment]
After increasing the logs verbosity we see:
`2021-08-18 16:25:17.113 [DEBUG][500] felix/vxlan_mgr.go 353: Missing local VTEP information, retrying...`

We realized that the connectivity of a faulty node to a runs typha is not working on port 5473 but it works in other port (e.g. 22). Maybe the issue is not in Calico but in the network policy between nodes in AWS:
```
root@ip-192-168-105-139:~# nc -zv 192.168.114.163 5473
^C
root@ip-192-168-105-139:~# nc -zv 192.168.79.196 5473
^C
root@ip-192-168-105-139:~# nc -zv 192.168.111.134 5473
^C
root@ip-192-168-105-139:~# nc -zv 192.168.111.134 22
Connection to 192.168.111.134 22 port [tcp/ssh] succeeded!
root@ip-192-168-105-139:~# nc -zv 192.168.79.196 22
Connection to 192.168.79.196 22 port [tcp/ssh] succeeded!
root@ip-192-168-105-139:~# nc -zv 192.168.114.163 22
Connection to 192.168.114.163 22 port [tcp/ssh] succeeded!
```

**Comment by manuelbuil** [comment]
We have just realized that the port `5473` is not enabled by default in aws when deploying through Rancher. We must add that port to the security group when deploying with Calico, otherwise things will fail when deploying more than 3 nodes (typha deploys 3 pods, if there are more nodes, there will be a calico-node pod that can't connect to a typha pod). This possibly happens too in other public clouds

**Comment by deniseschannon** [comment]
Summary: A new port needs to be added as part of the `rancher-machine` security group that gets automatically created.

Also need a new docs ticket to add this to the list of port requirements for RKE2 nodes.

**Comment by thedadams** [comment]
Created docs issue: https://github.com/rancher/docs/issues/3463

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `8898bf8`**


- Deployed an EC2 EC2 cluster
- Inbound rule added in the SG - `| Custom TCP | TCP | 5473` 
- This is seen for any CNI RKE2 cluster
