### ISSUE TITLE
All CIS v2.0.0 scans fail on v1.21.3+k3s1

### ISSUE THREAD

**Issue by peteingithub** [rancher/rancher#34492]
v2.6.0-rc7

Is this related to CIS itself?

![image](https://user-images.githubusercontent.com/86831399/130920214-4c4ac7fa-37a9-414b-8bbf-c30952481242.png)

**Comment by peteingithub** [comment]
Same problem with RC9.

![image](https://user-images.githubusercontent.com/86831399/131232844-bddb83ae-93e9-4473-bfa2-268fd971ff86.png)

**Comment by peteingithub** [comment]
Scan results are slightly different with Rancher 2.6.3-rc1.
Downstream K3s cluster v1.21.5.
CIS Benchmark v2.0.2

![image](https://user-images.githubusercontent.com/86831399/142617733-44213f8e-ba65-4bbb-8498-ef0bcb3551cb.png)

Reports are empty:
![image](https://user-images.githubusercontent.com/86831399/142617787-9c6d505d-9d22-484f-ae31-1b87b786ac73.png)

**Comment by bennysp** [comment]
I am seeing something similar and I manually run the scan commands on RKE2 with good results (passing results) since RKE2 is hardened by default.

**Rancher**: v2.6.4
**RKE2**: v1.22.8+rke2r1
**CIS Benchmark**: v2.0.3

![image](https://user-images.githubusercontent.com/4121872/161452024-6af28401-2e6e-4a36-a10c-9340c2afcbf4.png)

![image](https://user-images.githubusercontent.com/4121872/161452045-6b7dcc3d-4364-4fbb-b717-57af5d08dbd8.png)

It almost seems like it is not able to scan the "master" nodes because worker only scans seem to pass and report just fine:

![image](https://user-images.githubusercontent.com/4121872/161452111-1fa4661f-33ee-4373-8315-db8825f302db.png)
