### ISSUE TITLE
[Agent] Being able to access server through public IP, but have agents behind firewall.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#345]
Refer to https://github.com/rancherio/rancher/issues/55

In this issue, @feliksik has comments on overriding the CATTLE_AGENT_IP. 

He is comment: 
"Be aware of the following: The url that is generated by the server UI and should be executed on agent host, in order to start agent, seems te be based on the host/ip used by the browser. The agents will then try to contact the server on same socket.

This is not necessarily the way people want to use rancher. I envision accessing the server through a public IP, and having the agents behind a firewall, contacting the server on an internal network."

**Comment by feliksik** [comment]
It looks like this is fixed for the docker orchestration functionality (although not for the networking) -- so this should be closed? I leave it to a developer that can actually judge it properly.

**Comment by hwinkel** [comment]
Is this really closed? From the answer it's not clear the initial intention is covered. Can rancher sit in a private network and tHe ui is exposed on a public one. may via a reverse proxy or load balancer?

**Comment by cloudnautique** [comment]
Rancher is pretty flexible in its network configuration.

Breaking it down...
The UI needs to be able to hit the Rancher API in order to function, so the host needs to be exposed to your users. That can be over the internet, intranet, etc... 
The nodes need to be able to register, which can be a separate IP address from the UI and `websocket-proxy`. The registration IP would need to be on the Rancher server still. So the server would need to be multi-homed or nat'd typical of cloud providers. 

In order for the UI to fully work with logs, stats, and console access to the containers, all hosts will need access to the `websocket-proxy` AND all of your users will need to be able to access the websocket-proxy as well. 

With this model, you can lock down the hosts running your applications. They only need UDP ports 500,4500 between them and outbound access to the websocket-proxy and Rancher registration endpoint. The ports on the control plane are well known, and can be ACL'd as you would any other network port. 

Hopefully, that helps? :)
