### ISSUE TITLE
Restoring rancher from a backup on a migrated rancher server fails with the error unable to create new content in namespace cluster-fleet-default-anupamapostbkp because it is being terminated error restoring

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34518]
**Rancher Server Setup**
- Rancher version: v2.6.0-rc8
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Info: `RKE1`
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 3 nodes all roles
         Version:  `v1.21.4`
- Proxy/Cert Details: Self-signed

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Downstream node driver rke1 and rke2 clusters
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
Restoring rancher server from the backup that is created on a rancher server that is migrated to a new rke cluster.

**To Reproduce**

- On rancher server created an rke1 and rke2 node driver clusters [3 worker, 1 etcd, 1 cp ] in each cluster
- Installed backup charts in the local cluster. version `2.0.0+up2.0.0-rc11`
- from continuous delivery, created a git repo - fleet1, url `https://github.com/rancher/fleet-examples` , path: `multi-cluster/helm`
- Took a backup of the rancher server - bkp1
- Created another git repo - fleet2 [url: `https://github.com/rancher/fleet-examples` , path: `single-cluster/helm`
- Created another backup - bkp2 [will reuse after migration]
- Created a new rke1 cluster and installed the rancher backup charts version 2.0.0+up2.0.0-rc11.
- Restored the backup on the new rke cluster and migrated rancher to the new rke cluster. ref:https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/
- All clusters come up fine. verify no errors in fleet logs in the downstream clusters and the clusters in continuous delivery are all up and active.
- Create a new rke2 cluster on this new rancher server.
- Take a backup bkp3 once the cluster is up.
- Perform restore from the backup - bkp2 [from the steps above]
- All clusters come up fine. verify no errors in fleet logs in the downstream clusters and the clusters in continuous delivery are all up and active.
- Perform another restore with bkp3.

**Result**
- restore fails with the errors seen in the logs continuously in the backup resource `rancher-backup-xxx`.

<img width="500" alt="Screen Shot 2021-08-27 at 2 13 10 PM" src="https://user-images.githubusercontent.com/38144301/131189182-bd497181-993d-43b4-a6f9-cdf3e94600ae.png">
- rancher server retries multiple times, after sometime the rancher server comes up and the cluster created after migration in the new rke cluster is stuck in `Wait Check-In` state on the cluster.
<img width="600" alt="Screen Shot 2021-08-27 at 2 11 49 PM" src="https://user-images.githubusercontent.com/38144301/131189657-2030e81e-8e3b-4f1d-9113-da4087366c5d.png">

**Expected Result**
Restore should be successful and no errors should be seen. Downstream clusters should come up active.

**Additional Info:**

Issue is seen for both rke1 and rke2 downstream clusters:

<img width="600" alt="Screen Shot 2021-08-27 at 4 07 15 PM" src="https://user-images.githubusercontent.com/38144301/131196835-6fece1af-c6df-4b38-bbe5-0191353bd1a0.png">

Related: https://github.com/rancher/rancher/issues/33954

SURE-5358

**Comment by anupama2501** [comment]
Seen on v2.5.9 as well:

- On rancher server created 2 rke1 node driver clusters [3 worker, 1 etcd, 1 cp ] in each cluster
- Installed backup charts in the local cluster. version `1.0.400`
- from continuous delivery, created a git repo - fleet1, url https://github.com/rancher/fleet-examples , path: multi-cluster/helm
- Took a backup of the rancher server - bkp1
- Created another git repo - fleet2 [url: https://github.com/rancher/fleet-examples , path: single-cluster/helm
- Created another backup - bkp2 [will reuse after migration]
- Created a new rke1 cluster and installed the rancher backup charts version `1.0.400`.
- Restored the backup on the new rke cluster and migrated rancher to the new rke cluster. ref:https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/
- All clusters come up fine. verify no errors in fleet logs in the downstream clusters and the clusters in continuous delivery are all up and active.
- Create a new rke1 cluster on this new rancher server.
- Restore from backup b2 from above and see the restoring fails and won't recover from it.

**Comment by raphaelzoellner** [comment]
Hello,
we are experiencing the same symptoms during a migration of Rancher to a new cluster, but the restore process keeps retrying after the errors of the same type are logged. The restore does not finish and keeps retrying for at least 30min.

Is there any way to identify the reason for the namespaces of the form `cluster-fleet-default-{clusterid}-{id}` being terminated or a workaround to successfully restore the rancher to the new cluster?

Rancher version: 2.6.4
Rancher local cluster: k3s
New Rancher local cluster: RKE1
Downstream clusters: RKE1

**Comment by MKlimuszka** [comment]
@eliyamlevy , you should try to reproduce this in newer Rancher versions.

**Comment by sowmyav27** [comment]
@prachidamle @MKlimuszka It's not ready to test yet since we need a backup restore RC and an update into Rancher charts. Moving it back into `Review` column

**Comment by prachidamle** [comment]
@eliyamlevy Can we create a backup-restore rc and the move this to-test?

**Comment by eliyamlevy** [comment]
@prachidamle New RC is cut https://github.com/rancher/charts/pull/2764

**Comment by nickwsuse** [comment]
'Verified on v2.7-head Commit ID: 160bee8'

1. Basic Backup/Restore p0 test cases - PASS
2. Basic B/R HA migration - PASS
3. Upgrade (2.7.5 -> 2.7-head) - PASS
4. backup without fleet → add fleet → restore to before fleet - PASS

I also tested the changes made for allowing a more graceful error state when doing a restore that includes clusters that have been deleted, and that passed as well.

**Comment by sowmyav27** [comment]
@nickwsuse sees an issue during backup and restore. Nick will be adding details soon

**Comment by nickwsuse** [comment]
Seeing issues with the restore process on `v2.7.7-rc4` and Rancher Backups `v102.0.2+up3.1.2-rc1`. 

Specifically, when trying to restore on a fresh cluster I see the following errors in the logs:
```
Error getting object for controllerRef apps/v1/deployments/rancher: deployments.apps "rancher" not found

Error restoring resource mcc-<redacted>-managed-system-upgrade-controller of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource namespaces "cluster-fleet-default-<redacted>" not found

Error restoring resource fleet-agent-local of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource namespaces "cluster-fleet-local-local-<redacted>" not found

Error restoring resource fleet-agent-<redacted> of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err creating resource namespaces "cluster-fleet-default-<redacted>" not found

Error restoring resource <redacted> of type cluster.x-k8s.io/v1alpha4, Resource=clusters: restoreResource: err creating resource conversion webhook for cluster.x-k8s.io/v1alpha4, Kind=Cluster failed: Post "[https://capi-webhook-service.cattle-provisioning-capi-system.svc:443/convert?timeout=30s](https://capi-webhook-service.cattle-provisioning-capi-system.svc/convert?timeout=30s)": service "capi-webhook-service" not found
```

It sounds like the issue is that some resources are being excluded when they shouldn't, while some are not that should be.

It's also strange that this is just appearing as I found this issue when doing release testing for v2.7.7 while performing the same test as case #2 in my previous comment signing off on this fix.

**Comment by eliyamlevy** [comment]
It seems that the above test case failing is from two issues:

- a [capi-webhook error in the restore process ](https://github.com/rancher/rancher/issues/42631) that was created by a commit (~v2.7.7-rc1) and merged into rancher/rancher after the original testing was done. This is why the issue only appeared in v2.7.7-rc4 testing of backup restore.
- A resource which was missed when excluding `cluster-fleet-*` namespaced resources.
  - `bundledeployments` is the specific resource missed and the error message has been fixed

The second issue was fixed in a[ followup pr](https://github.com/rancher/backup-restore-operator/pull/381) to this issue. In my testing with rancher v2.7.6 with this resourceSet I found that there may be a case where one of the nodes in a downstream RKE2 cluster may become "misaligned" with the local agents and be stuck in a `waiting for plan to be applied state`, this can be fixed by letting the agent try to resolve the issue itself and if it doesn't simply scaling up the  node pool until all the nodes refresh and then scaling back down will remove the "Updating" state from the cluster and realign the nodes (thanks @matttrach for [that one](https://github.com/rancher/rancher/issues/37174#issuecomment-1349810284))

The capi-webhook error is a breaking error and results in important resources triggering a conversion webhook call to a service which is not ready at the time. Please look at the linked issue for more info on that.

**Comment by eliyamlevy** [comment]
Update to the above comment:

I've done two migrations with the updated changes and the below versions. Everything was successful and no errors present. It does take some time to resolve the agent errors, so please let them work. It can take up to 15 minutes.

Rancher: v2.7.7-rc4
Backup Restore Operator: v3.1.2-rc1 with bundledeployments and cluster.x-k8s.io/v1alpha4 removed from resourceSet
Kubernetes: v1.26.7

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: 60c50f0 && BRO v102.0.2+up3.1.2-rc2`

I retested all of the previous scenarios in this ticket plus a few extra since the capi-webhook change was included as well. There are no errors in the restore logs with these changes and restores are completed as expected. I did run into an issue of the resourceSet not being updated accordingly went upgrading Rancher and the BRO chart, logged [here](https://github.com/rancher/rancher/issues/42756). I also ran into one of the migrations taking a while for the downstream clusters to come back up, but they did eventually come back up.

Test Cases:
1. Basic Migration
2. In-Place Restore
3. Rollback on same Rancher cluster
4. Upgrade Rancher and migrate
5. Rollback via migration
6. Backup without fleet → add fleet → restore to before fleet
7. The "more graceful" error state that was previously fixed in this issue

**Comment by eliyamlevy** [comment]
### Release Note
Due to some changes made to the default resourceSet, downstream clusters may take longer to reconnect with the local after a migration is done. If you see a downstream cluster in updating state or error state immediately after a migration please let it attempt to resolve itself. This could take from 5 to 45 minutes to complete. The quicker you re-install Rancher after completing a migration the quicker it will take for clusters to come up.

**Comment by anupama2501** [comment]
cc @btat @martyav Release note for this ticket needs to be updated as well.

**Comment by martyav** [comment]
@anupama2501 This is currently listed under Known Longstanding Issues. Should this be moved up to the main section for 2.7.7-related topics?

**Comment by anupama2501** [comment]
If https://github.com/rancher/rancher/issues/34518 is under Known Longstanding Issues, it can be removed from that section and the note from this comment, https://github.com/rancher/rancher/issues/34518#issuecomment-1734168244 should be updated for the issue: https://github.com/rancher/rancher/issues/42834

**Comment by martyav** [comment]
@anupama2501 just pushed https://github.com/rancherlabs/release-notes/pull/328/commits/c94295f8dbcac8bc79bd637452110ce61aa4328d to address your comment

**Comment by martyav** [comment]
My mistake -- another issue that begins with the digits 345 was already listed and mistaken for 34518. I'll go correct the draft. Unfortunately, this issue has been around for a while and received other milestone tags, so it seemed plausible that it might already have an RN.
