### ISSUE TITLE
RKE2 upgrade takes a long time to finish upgrading and sometimes get stuck after upgrading one master node

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34560]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `a97612b`
- Installation option (Docker install/Helm Chart): HELM
   - If Helm Chart, Kubernetes Info: RKE1
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: 3 nodes all roles
         Version: 1.20.9
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20.10rke2 to 1.21.4 rke2 version
- Cluster Type (Local/Downstream): Downstream imported RKE2 cluster

**Describe the bug**

- This happened on an upgraded rancher from 2.5.9 to 2.6head setup, but that shouldnt matter.
- Deploy an imported RKE2 cluster - 3 etcd+cp and 2 worker nodes on 1.20.10 rke2 version
- Upgrade rancher
- Upgrade the rke2 version of the downstream cluster to 1.21.4
- One of the master nodes get upgraded, and the cluster is stuck in Provisioning 
- It waits for 30 mins, and another master plan pod is deployed, and then master nodes get upgraded, and worker also get upgraded.

**Comment by rancher-max** [comment]
I believe this is due to system-upgrade-controller itself and maybe we should move this to that repo. I have seen this same thing happen in the past on standalone SUC upgrades. Basically, the upgrade gets stuck on a node and there is some internal timeout of 30 minutes until it will retry on its own. Usually this retry resolves the issue. 

When it gets stuck, there isn't anything useful that I can tell by looking at the plans and jobs, other than that it tried to apply on a master node (for example, based on the plan) and then there is no pod showing that it ran anything.

**Comment by rancher-max** [comment]
This could very well be an upstream bug that SUC exposes, and we probably want to bump it out of 2.6.1. For the use cases here, we are not using drain, which can itself sometimes be the problem.

What I'm seeing is that a job on the node in question (in this case a server node) is created but not running:
```
NAME                                                                  READY   STATUS     RESTARTS   AGE
pod/apply-rke2-agent-on-ip-172-31-13-106.us-east-2.compute.in-lprnz   0/1     Init:0/2   0          9m3s
pod/apply-rke2-agent-on-ip-172-31-6-22.us-east-2.compute.inte-pjdfd   0/1     Init:0/2   0          9m3s
pod/system-upgrade-controller-7cbf7ff8d5-6t6lv                        1/1     Running    0          79m

NAME                                                                        COMPLETIONS   DURATION   AGE
job.batch/apply-rke2-agent-on-ip-172-31-13-106.us-east-2.compute.in-35da0   0/1           9m         9m
job.batch/apply-rke2-agent-on-ip-172-31-6-22.us-east-2.compute.inte-7f711   0/1           9m         9m
job.batch/apply-rke2-server-on-ip-172-31-2-47.us-east-2.compute.int-59967   0/1                      9m1s
```

When checking the kubelet logs on the node, it appears this could be a problem with it not finding mount points, even though they exist:
```
E0902 20:00:42.335782    3767 kubelet_pods.go:153] Mount cannot be satisfied for container "cordon", because the volume is missing (ok=false) or the volume mounter (vol.Mounter) is nil (vol={Mounter:<nil> BlockVolumeMapper:<nil> SELinuxLabeled:false ReadOnly:false InnerVolumeSpecName:}): {Name:host-root ReadOnly:false MountPath:/host SubPath: MountPropagation:<nil> SubPathExpr:}
E0902 20:00:42.335900    3767 kuberuntime_manager.go:829] init container &Container{Name:cordon,Image:rancher/kubectl:v1.18.3,Command:[],Args:[cordon ip-172-31-2-47.us-east-2.compute.internal],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{EnvVar{Name:SYSTEM_UPGRADE_NODE_NAME,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:spec.nodeName,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:SYSTEM_UPGRADE_POD_NAME,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.name,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:SYSTEM_UPGRADE_POD_UID,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.uid,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:SYSTEM_UPGRADE_PLAN_NAME,Value:rke2-server,ValueFrom:nil,},EnvVar{Name:SYSTEM_UPGRADE_PLAN_LATEST_HASH,Value:8edf2a220da7edb9e0979f15c1f4f9eeb539dfc0c1845203376af791,ValueFrom:nil,},EnvVar{Name:SYSTEM_UPGRADE_PLAN_LATEST_VERSION,Value:v1.21.4-rc1-rke2r3,ValueFrom:nil,},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:host-root,ReadOnly:false,MountPath:/host,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:pod-info,ReadOnly:true,MountPath:/run/system-upgrade/pod,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:system-upgrade-token-lwn4z,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod apply-rke2-server-on-ip-172-31-2-47.us-east-2.compute.int-97cwk_system-upgrade(e985599a-93ed-498c-a279-5fb0ad4fed8c): CreateContainerConfigError: cannot find volume "host-root" to mount into container "cordon"
E0902 20:00:42.335926    3767 pod_workers.go:191] Error syncing pod e985599a-93ed-498c-a279-5fb0ad4fed8c ("apply-rke2-server-on-ip-172-31-2-47.us-east-2.compute.int-97cwk_system-upgrade(e985599a-93ed-498c-a279-5fb0ad4fed8c)"), skipping: failed to "StartContainer" for "cordon" with CreateContainerConfigError: "cannot find volume \"host-root\" to mount into container \"cordon\""
```

This fixed itself within 20 minutes, but for future reference, on the system where we see these errors, we need to attempt correlation with the containerd logs (because while the kubelet is responsible for setting up mounts these are funneled through containerd which is likely applying its own sanity checks).

**Comment by slickwarren** [comment]
I was not able to reproduce this on v2.6-head (1d2b746) by following the original instructions:
* import 1.20.10 rke2 cluster
* upgrade to 1.21.x
the cluster upgrades in a timely manner and returns to an `active` state
