### ISSUE TITLE
New Charts in 2.6.1

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34589]
System charts (v1) `rancher/system-charts:dev-v2.6`:

Name                 | Version  | Backend Dev(s)
---------------------| -------- | -----------
monitoring v1 |  0.3.1 | @jiaqiluo 

Feature charts (v2) `rancher/charts:dev-v2.6`:

Name                       | Version           | Note                 | Backend Dev(s) | rancher-max of prev chart set
---------------------------| ----------------- |----------------------|----------- | -----------
Fleet | v0.3.7  | | @nickgerace @StrongMonkey |
opa gatekeeper                      | 100.0.1+up3.6.0   |  |  @rayandas  | 
CIS-benchmark                      | 2.0.1  |  |  @jakefhyde @paynejacob   |  
Longhorn                      | 100.0.0+up1.1.2  |  |  @innobead  |
Longhorn                      | 100.1.0+up1.2.0 |  |  @innobead  | 
aks-operator | 100.0.1+up1.0.2 | | @cmurphy |
rancher-webhook              | 1.0.1+up0.2.1 |  | @jiaqiluo / @ryansann  |
rancher-backup               | 2.0.1         |  | @jiaqiluo | 
rancher-istio | 100.0.1+up1.10.4| |@brendarearden |

**Comment by deniseschannon** [comment]
OPA Gatekeeper - 3.6.0

**Comment by innobead** [comment]
For the longhorn release, we need to support multiple release lines like 1.1 and 1.2 in 2.6 and also will continue releasing on 2.5 as well, so we should have the following compromised solution to keep the latest versions of each line instead of only one latest version to avoid cross-line chart false upgrade after users upgrade from 2.5 to 2.6. But some cases can not be avoided (ref: https://github.com/rancher/charts/pull/1428#discussion_r709186675), and we will document them in the Longhorn documentation. 

Note: the false upgrade caused by ` different version scheming between 2.5 n 2.6`

The solution discussed with @cbron 
https://github.com/rancher/charts/pull/1428#discussion_r709186675

The example for chart updates when we have new longhorn releases.
https://github.com/rancher/charts/pull/1428#discussion_r709209875
https://github.com/rancher/charts/pull/1428#discussion_r709440786

**Comment by thedadams** [comment]
Added `k3s-upgrader` to system-charts table and `system-upgrade-controller` to rancher/charts table.

**Comment by aiyengar2** [comment]
vsphere-csi has been removed due to the revert in https://github.com/rancher/charts/pull/1510. We are no longer releasing a vsphere chart in this release.

**Comment by sowmyav27** [comment]
`On 2.6.1-rc7`

Name                 | Expected Version  | Actual version 
---------------------| -------- | -----------
monitoring v1 |  0.3.1 | 0.3.1

Feature charts (v2) `rancher/charts:dev-v2.6`:

Name                       | Expected Version           | Actual version on 2.6.1-rc7                 
---------------------------| ----------------- |----------------------
Fleet | v0.3.7  | rancher/fleet-agent:v0.3.7-rc3; rancher/fleet:v0.3.7-rc3 (will check on an RC once this is tagged)
opa gatekeeper                      | 100.0.1+up3.6.0   |  100.0.1+up3.6.0
CIS-benchmark                      | 2.0.1  |  2.0.0 (FAIL)
Longhorn                      | 100.0.0+up1.1.2  |  100.1.0+up1.1.2
Longhorn                      | 100.1.0+up1.2.0 |  100.1.0+up1.2.0
aks-operator | 100.0.1+up1.0.2 | rancher/aks-operator:v1.0.2
rancher-webhook              | 1.0.1+up0.2.1 | rancher/rancher-webhook:v0.2.1
rancher-backup               | 2.0.1         |  2.0.1 - rancher/backup-restore-operator:v2.0.1
rancher-istio | 100.0.1+up1.10.4|  rancher-istio:100.0.1+up1.10.4
system-upgrade-controller | 100.0.1 | rancher/system-upgrade-controller:v0.8.0-rc.1

Monitoring v2 - `100.0.0+up16.6.0`

**Comment by cbron** [comment]
System-upgrade-controller has been removed from both. This ^ comment caught it halfway.

**Comment by cbron** [comment]
Longhorn will switch to 100.1.0+up1.2.2 (go from up1.2.0 to up 1.2.2, keep package version).
