### ISSUE TITLE
GET /v1/projects not returning all projects for LDAP user on v0.56.1

### ISSUE THREAD

**Issue by bhinkle-work** [rancher/rancher#3463]
After upgrading to v0.56.1 (from v0.51.0), we've noticed a user logging in via LDAP (even if they're set as "admin" as user type) sees a restricted subset of projects in a GET /v1/projects call. Specifically, they only see projects where hosts have been joined to the environment. We can GET the specific project ID without hosts if we know the ID, but it doesn't show up in the list of all projects.

Because we have authentication enabled, we can't create API keys anymore for the built-in admin user (account id 1a1, user "admin") and so this is affecting our ability to automate environment creation. We can't join hosts automatically to a newly created environment if there's no way to find the project ID for that environment (which allows us to find the registration token for the Rancher agent).

The API key associated with 1a1 existed prior to enabling authentication which is the only reason any part of this process works.

**Comment by vincent99** [comment]
Does `/v1/projects?all=true` return what you want?

The `/v1/projects` list is just the ones the account is a member of (so that you don't *have* to see every project on earth because you happen to be an admin), and the UI uses `/v1/projects?all=true` to load the full list for the environment management screen.

None of this is new though so it's not clear why you've seen a change in behavior;  @hibooboo2 is looking into the 51->56 diff.

**Comment by bhinkle-ezesoft** [comment]
Yes it does! Is there any reason why this filter isn't declared in the filters section for the project API? Or is that a global filter?

**Comment by vincent99** [comment]
It's not a "real" filter because there isn't an actual field with a "am I a member of this" value to filter based on.. Added to https://github.com/rancher/rancher/issues/1052

**Comment by deniseschannon** [comment]
Closing in favor of #1052
