### ISSUE TITLE
No way to determine if v1 istio is installed in a cluster

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#34663]
Required for: https://github.com/rancher/dashboard/issues/4072

We need to hide the Istio resources in the UI if v2 Istio is installed.

The best way is if the backend can annotate the cluster metadata to indicate the presence of v1 istio - the backend can ensure that there are no permissions issues in doing so and that this is done efficiently (which would most likely be the case if the UI tried to do this).

**Comment by brendarearden** [comment]
Use the `kubectl get --ignore-not-found=true deploy istio-pilot -n istio-system -o=jsonpath='{$.spec.template.spec.containers[*].image}'` to get the istio version from the istio-pilot deploment, and then see if it is less than 1.6. If you don't want to do a less than, you can specifically check if it is 1.3, 1.4 or 1.5 to confirm if it is v1. This is the same code we are using in our installer image to see if v1 is installed so it would make sense to use it in the UI as well.

**Comment by nwmac** [comment]
@brendarearden what if a user does not have access to the istio namespace?

It's also awkward for us to have to make that request each time a user explorers a cluster - couldn't the backend do this and return in the cluster metadata? That's less calls from the front end and it sounds like you have the code to do this already.

**Comment by brendarearden** [comment]
@nwmac 
That is a good call out - the users that would be able to see the Istio Dashboard in the right nav will have access to run `kubectl get --ignore-not-found=true deploy istio-pilot -n istio-system -o=jsonpath='{$.spec.template.spec.containers[*].image}'` so permissions shouldn't be an issue. 

Because Istio is a helm chart and not a controller in rancher, I am unable to add something to return that for istio specifically. Do you know how we resolved this issue for rancher-monitoring? From there I can see if there is a generic approach we can take in the helm controller.

**Comment by nwmac** [comment]
@brendarearden 

For monitoring, the backend provides status.monitoringStatus on the management cluster if v1 monitoring is installed.

**Comment by brendarearden** [comment]
@nwmac 

Gotcha - Looking at the v3 cluster type, I do see that there is a value for 'istioEnabled' and that seems to be exactly what you are looking for

**Comment by nwmac** [comment]
@brendarearden Perfect - I will close this issue.
