### ISSUE TITLE
Rancher 2.6: Fetching the secret from Azure AD occasionally fails

### ISSUE THREAD

**Issue by k8s42** [rancher/rancher#34756]
I enabled Azure AD authentication using the same SPN I use in other Prod clusters (2.5.4). I installed 2.6 today in my test cluster and enabled Azure AD using the same SPN. I then added the users successfully. However, a few minutes later, I see "Unable to fetch principal info" under Authorized Users & Group in Azure AD settings. Users also complain that they cannot log in. The issue then goes away after a few minutes. It appears to be sporadic.

**Comment by prachidamle** [comment]
@codyrancher  `Unable to fetch principal info` is an expected error when you login using local user - with the local providers login token, there is no way the backend can fetch the principal info of the external provider - hence this error message.

I will check about the secret.

**Comment by prachidamle** [comment]
@codyrancher I see what the problem is. 
- UI is calling the `/v1/management.cattle.io.authconfigs` API when it is listing the authconfigs instead of the `/v3/authconfigs ` API.
- To fix this UI should call the /v3 API to list the authconfigs 


When /v1 API is called, the formatters/mappers logic does not get applied and just the data stored in the management cluster is returned. When /v3 API will be called, backend will hide the applicationSecret field and not cause this issue.

Here is the screenshot of the difference of outputs:
/v1/management.cattle.io.authconfigs returns the applicationSecret field:

<img width="1069" alt="Screen Shot 2021-09-16 at 9 44 23 PM" src="https://user-images.githubusercontent.com/1470602/133726873-2b0097bb-0a3d-4e8c-b5be-dfc475017db4.png">



/v3/authconfigs does not return the applicationSecret field:

<img width="1200" alt="Screen Shot 2021-09-16 at 9 43 50 PM" src="https://user-images.githubusercontent.com/1470602/133726710-931819c4-1452-4ccd-a2b0-71013c0ec65f.png">

**Comment by sowmyav27** [comment]
On 2.6.1-rc1, reproduced what Prachi has mentioned [here](https://github.com/rancher/rancher/issues/34756#issuecomment-918809622)

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.0
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a (turns out this is NOT needed to reproduce or validate this issue)
Downstream K8s version: n/a
 
**Reproduction steps:**

1. I Set up Azure AD auth provider and after saving, as the same user used to set this up (my admin user) switched from the default "Allow any valid user" setting to "Restrict access to only the authorized users & groups"
2. I added a few authorized users to the list in the directory.
3. I loged out, logged in as a standard user "testuser3" in my case
4. I was able to encounter the issue - web response `{"baseType":"error","code":"ServerError","message":"Server error while authenticating","status":500,"type":"error"}` to the 500 error to azuread?action=login and rancher server error like:
```
2021/09/30 04:19:20 [ERROR] API error response 500 for POST /v3-public/azureADProviders/azuread?action=login. Cause: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: REDACTED\r\nCorrelation ID: REDACTED\r\nTimestamp: 2021-09-30 04:19:20Z","error_codes":[7000215],"timestamp":"2021-09-30 04:19:20Z","trace_id":"REDACTED","correlation_id":"REDACTED","error_uri":"https://login.microsoftonline.com/error?code=7000215"} Endpoint https://login.microsoftonline.com/REDACTED/oauth2/token?api-version=1.0
```

 
-----
 
**Validation Environment:**

Rancher version: v2.6.1-rc7
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a (not needed)
Downstream K8s version: n/a
 
**Validation steps:**

1. Execute the same steps as in the reproduction steps above.
I was unable to reproduce (the issue appears fixed) when I log out as the restricted user, I can still log back in again without encountering the errors in my browser and the rancher server logs. Logs look normal now.
