### ISSUE TITLE
Metadata - Not able to container list when using /self/service/containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3476]
Server version - V0.57.0-rc3

steps to reproduce the problem:
Create a service.
From within the container , we are not able to get the list of containers by executing the following command:

<img width="651" alt="screen shot 2016-01-29 at 7 25 25 pm" src="https://cloud.githubusercontent.com/assets/4266958/12693413/13b09648-c6be-11e5-8cfa-698eda21e1d8.png">

The same problem is encountered when access rancher-metadata version - 2015_07_25  and 2015_12_19

**Comment by alena1108** [comment]
@prachidamle this bug is a regression caused by https://github.com/rancher/cattle/pull/1312/files. We don't set containers list for the service as a result of it. Containers are being populated a special way based on the version requested: 2 classes - ServiceMetaDataVersion1 and ServiceMetaDataVersion2. I guess we should think of better way of hiding token from non-self section than creating that overriding constructor.

**Comment by sangeethah** [comment]
Tested with Server version - V0.57.0-rc4

steps to reproduce the problem:
Create a service.
From within the container , we are able to get the list of containers by executing the following command:
1. wget http://rancher-metadata/latest/self/service/containers
2. wget http://rancher-metadata/2015-07-25/self/service/containers
3. wget http://rancher-metadata/2015-12-19/self/service/containers
