### ISSUE TITLE
vSphere provider CSI should allow setting volume expansion

### ISSUE THREAD

**Issue by braunsonm** [rancher/rancher#34797]
The helm chart for the vSphere provider CSI allows you to set some settings on the storage class it creates but it does not let you enable volume expansion which is required to use that feature.

A property should be added to the values file and storage class here: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.0/values.yaml#L66

**Comment by slickwarren** [comment]
**Test Environment**
- Rancher Version:2.5.10-rc3
- Installation option (Docker install/Helm Chart):docker

**Information about the Cluster**
- Kubernetes version:1.20.11
- Cluster Type(s) tested on (Local/Downstream):Downstream

**Overview of Validation**

* enable `allow Volume Expansion` (default option) -> `AllowVolumeExpansion` is set to `True` in the Yaml -- pass
<img width="203" alt="Screen Shot 2021-10-08 at 3 21 05 PM" src="https://user-images.githubusercontent.com/16691014/136633877-93ae104f-e106-4504-bea0-2b53287167f6.png">

* disable `allow Volume Expansion` (default option) -> `AllowVolumeExpansion` is set to `False` in the Yaml -- pass

Since there were no further changes to this feature other than the additional UI, the above checks are all that need to be done.
