### ISSUE TITLE
Allow rancher-logging chart to configure [cluster]flow and [cluster]output

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#34796]
I can see that rancher/charts#587 removed default outputs and flows, but it seems that allowing users to configure the chart's values with [cluster]flow and/or [cluster]outputs would be very convenient and avoid having a second configuration pass when deploying charts with automation.

**Comment by paynejacob** [comment]
@jmatsushita It was decided to not include the outputs and flows in the chart because there are so many configuration options that we could not add any value by configuring part of the inputs or outputs. It is better for this configuration to be managed outside of rancher logging given how variable it could be..  If you feel there is a use case we are missing please feel free to re-open the issue.
