### ISSUE TITLE
[rke2 templates] unable to create cluster from an rke2 template as non-admin user

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34844]
**Rancher Server Setup**
- Rancher version: v2.6-head (45dfeb4)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:1.21.4+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): digital ocean, from rke2 template

**Describe the bug**

non-admin users are not able to create a cluster from rke2 cluster templates. Initial chart install fails

**To Reproduce**
 
* log in as non-admin user (restricted admin)
* add an rke2 cluster template repo 
* using a template, create a cluster using valid parameters

**Result**
  * currently, restricted admin gets this error when provisioning a cluster that the restricted admin has added:
  * <img width="1789" alt="Screen Shot 2021-09-20 at 10 01 02 AM" src="https://user-images.githubusercontent.com/16691014/134054190-03e78e37-7884-4a9c-8b5d-050c90fcf664.png">
  * the regular admin can use the same parameters to create a cluster from the template.  **Reopening for this issue,** thought this might be a separate issue. 

**Expected Result**

any user should be able to install from an rke2 cluster template

**Screenshots**

**Additional context**
found when testing https://github.com/rancher/dashboard/issues/3995

**Comment by janeczku** [comment]
Related: https://github.com/rancher/rancher/issues/35177

**Comment by jakefhyde** [comment]
### Root cause

The `create-clusters` role did not have access to get/list/watch cluster repos, so non-admin users were not able to provision clusters with them.

### What was fixed, or what changes have occurred

The `create-clusters` role was updated to allow the user to view these resources.
 
### Areas or cases that should be tested

Creating a cluster using an rke2 template.

### What areas could experience regressions?

N/A
 
### Are the repro steps accurate/minimal?

As an admin user, add the [cluster template examples repo](https://github.com/rancher/cluster-template-examples). Create a user with the `create-clusters` role, and try to provision an rke2 cluster using the template.

**Comment by slickwarren** [comment]
tested as part of: https://github.com/rancher/rancher/issues/35177


tested on v2.6-head (c682e30):
* provision cluster from rke2 template as admin user  -- pass
* provision cluster from rke2 template as standard user  -- pass
*  provision cluster from rke2 template as base user with `create cluster` role -- pass
  * verify user only has access to their cloud credentials in rke2 template -- pass
  * verify user can access rke2 template(s) added by admin -- pass
