### ISSUE TITLE
Convert sync handler to env variables

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34876]
Continuation of this issue: https://github.com/rancher/rancher/issues/34875

1. Add all settings from sync handler (currently 4) as env vars. 
2. Remove the settings sync handler: https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/managementuser/settings/controller.go
3. Audit which settings should trigger agent redeployment

**Comment by jakefhyde** [comment]
Are there any concerns regarding updating of a downstream agent when one of these environment variables is changed? For example if I spin up a local and a downstream cluster, and `helm upgrade ... --set env.CATTLE_SERVER_VERSION=v2.5.9`, will the cluster agent be redeployed because it's deployment depends on the variable?

**Comment by StrongMonkey** [comment]
You can check this method. https://github.com/rancher/rancher/blob/5c2933173bc07a1cd260d6e07fd9459243afc45d/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L184

I don't think it will reploy agent if you just change the env variable. We only redeploy acccording certain conditions above. ^^ If you upgrade rancher it will redeploy agent since agent image changes and that will trigger cluster-agent upgrade.

**Comment by cbron** [comment]
Setting up something to discuss.

**Comment by jakefhyde** [comment]
### Root cause

### What was fixed, or what changes have occurred

Settings are no longer synced downstream, and instead passed from the local cluster to the cluster-agent deployment template as environment variables. 
The following settings are used to trigger a redeployment:
- server-version
- install-uuid
- ingress-ip-domain

### Areas or cases that should be tested

Changing server-version, install-uuid, or ingress-ip-domain in the local cluster triggers a redeployment of the downstream agent. Likewise, changing any other setting should **not** trigger a redeployment of the downstream agent.

### What areas could experience regressions?

N/A

### Are the repro steps accurate/minimal?

Deploy a downstream cluster, and then edit one of the settings, either through API or externally (i.e. kubectl, lens, etc.). The cluster agent should be redeployed.

**Comment by slickwarren** [comment]
on 2.6-head (78b25c3) I've tested the following:
`example of how to change one of these vars: go to <your_server_ip>/v3/settings/<your_variable> -> edit -> send request`

* update install-uuid (random name) -> cattle-cluster-agent pod is redeployed -- pass
* update ingres-ip-domain (to nip.io) -> cattle-cluster-agent pod is redeployed -- pass
  * validate that new domain propagates to downstream resources by deploying a new ingress using the auto-generated name -- pass
* update a setting that is not one of the 3 mentioned in the comment above -> no redeployment of any agent pod(s) -- pass
  * some variables are protected, and give a 405 with message `is readOnly because its value is from environment variable`, other variables allow an edit through the API and the cluster agent is not restarted

note: from what I could find, there isn't a way to update the server-version through the UI, so instead I did an update of the local cluster and used a newer version from there, which also resulted in an update to the downstream cluster agent -- pass
