### ISSUE TITLE
Convert ServerVersion to downstream env var

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34875]
Don't sync with settings sync handler, instead pass as env var to downstream cluster agent. If that cluster-agent contains the Rancher controllers then it should pick up this env var, if it doesn't (local rancher install downstream) then it should not.

**Comment by cbron** [comment]
Adding @rmweir for dev-validate. @jakefhyde let us know when its ready for validation.

**Comment by cbron** [comment]
removing dev-validate because this is now a more complex test

**Comment by jakefhyde** [comment]
### Root cause
 
The `server-version` setting does not propagate to downstream clusters, which causes issues when a downstream requests a chart that is only available for a specific version (range) of rancher.

### What was fixed, or what changes have occurred
 
 The `server-version` setting is now being passed in the cluster-agent template as the `CATTLE_SERVER_VERSION` environment variable.
 
### Areas or cases that should be tested
 
 Chart install, edit, upgrade, uninstall, as well as install, upgrade rancher, and then edit.
 
Testing should be done with rancher installations using a valid semver server version (v2.6.1, rc, etc)., versions which have special meanings (dev, master, master-head), as well as default developer versions which default to git short hashes (e.g. 3eaa377d3).

### What areas could experience regressions ?

Downstream clusters have defaulted to using dev as the server-version at least are early as 2.6. Catalogs and KDM query server version, and non production setups may be affected.
 
### Are the repro steps accurate/minimal ?
Todo

**Comment by cbron** [comment]
Assigning @brendarearden for dev-validate here.

**Comment by brendarearden** [comment]
Validation: PASSED

Steps to Test:
1. Installed HA Rancher v2.6.0
2. Created downstream DO cluster, rke, k8s v1.21.5  
3. In downstream cluster add new chart repository - `url: https://github.com/jakefhyde/charts`  `branch: add-min-rancher-version`
4. Navigated to charts and validated that I was able to see all of the chart version that met the `rancher-version` annotation requirement
Example list from rancher-istio chart:
![Screen Shot 2021-09-28 at 5 05 29 PM](https://user-images.githubusercontent.com/19455540/135184771-3ea1c6ae-df4d-4841-ba64-aa52c4df0f6a.png)
5. Then I upgraded the rancher instance to Rancer v2.6.1-rc5
6. Naviated to charts and validated that on the charts the met the `rancher-version` annotation requirement were listed and available in index response. 
Example list from rancher-istio chart after upgrade:
![Screen Shot 2021-09-28 at 5 22 22 PM](https://user-images.githubusercontent.com/19455540/135184936-e89a6e2a-1bb7-425c-909f-2e5efbc415b4.png)
