### ISSUE TITLE
Restrict UI access by source ip address

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#3490]
How could I restrict the RancherUI access based on source ip address without modify / hack the automated docker iptables rule?

I won't use a rev proxy for that.

**Comment by vincent99** [comment]
Those are the two obvious ways, iptables on the host(s) restricting what can get in on port 8080 or proxying (which you already need if you want to use SSL).  If you're on a cloud provider with security groups you could filter there.

Otherwise you're taking about a whitelist/blacklist to the API server (there is no UI server, it's all static content), which is not a feature that exists, nor that I foresee great demand for.

**Comment by pwFoo** [comment]
Hi @vincent99 
restrict by iptables all traffic to 8080 is simple and should work for me. 
If there is a way to restrict 8080 to Rancher Server container explicit I would prefer it. 

I'll use a rev proxy for my containers, but it is deployed as rancher stack service. 

I thinking about a second (private) ip address reachable via openvpn tunnel as primary access to the RancherUI. Rev proxy could be used for ip based restriction / auth and SSL from outside, but I don't know if it would work fine for adding hosts.

**Comment by RXminuS** [comment]
Feel like this is something that needs to be taken care of on a different level than Rancher. For instance on AWS you can have SecurityGroup rules or otherwise you run Rancher behind a proxy that does the IP filtering for you. A rancher implementation would be needless clutter, and extra security concerns

**Comment by pwFoo** [comment]
I can't just reject all connections to Rancher Server (8080/tcp), because it's also the API port, right? So a iptables "ACCEPT <my_ip>" followed by "DROP any" would break host communication too?

With my new setup rancher server listening at a private / internal ip address. All hosts connected by openvpn tunnel. The WebGui is reached by a reverse proxy with additional basic auth. 
So host to host communication is just internal.
