### ISSUE TITLE
RKE2 Provisioning - Nodepool doesn't self heal after correcting it's configuration. Custom Driver.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#34914]
**Rancher Server Setup**
- Rancher version: `v2.6.1-rc3`
- Installation option: Helm HA
   - If Helm Chart, Kubernetes Cluster and version: RKE1 k8s `v1.21.5`
- Proxy/Cert Details: `Bring your own valid`

**Information about the Cluster**
- Kubernetes version: `v1.21.4+rke2r2`
- Cluster Type: `Downstream
   - RKE 2 Cluster Oracle OCI Driver
   - `VM.Standard2.8` Nodes Shape

**Describe the bug**

An RKE2 Node Pool doesn't auto delete a failed node and provision a new node after editing the node pool with correct configuration parameters.

**To Reproduce**

- Create an RKE2 Oracle OCI cluster 
- Configure one node pool with all roles (etcd, control plane, worker) and right parameters.
- Configure a second node pool with worker role and one invalid parameter to make it fail provisioning.
- Wait until it's Provisioning with an error and colored red in the UI
- Edit the cluster Node Pool again and set the correct configuration parameters

**Result**

- The node with the error will stay in the pool and won't be deleted and no node with correct parameters will be provisioned.

I had to manually delete the node

**Expected Result**

- Node pool should auto-heal or time out somehow after some time (or if a new configuration is detected?) deleting the failed node and provisioned a new node with the updated parameters.

**Screenshots**

This is how the node pool looks in the UI after editing the Node Pool parameters with right values. It just hangs there.

![Screen Shot 2021-09-24 at 11 22 24 AM](https://user-images.githubusercontent.com/27659/134722650-53d49a78-3138-458c-a12d-3b46365d6d2c.png)

**Additional context**

If I delete the node manually from the UI then a new node with the Updated/Corrected parameters is provisioned and get active.

https://github.com/rancher/rancher/issues/34713

**Comment by thedadams** [comment]
### Root cause
The root cause was the infrastructure objects were not getting re-enqueued to the controllers.

### What was fixed, or what changes have occurred
The infrastructure objects should be re-enqueued now when edits are made (not just when they are created/deleted).

### Areas or cases that should be tested
Creating clusters with nodes that are misconfigured should be tested:
1. Creating nodes in a cluster that are misconfigured (like in the description).
2. Creating a cluster that is misconfigured from the beginning. For example with the OCI steps in the description, don't create the cluster with valid configuration. Instead, create it with something misconfigured so the cluster will go into an error state. Once the cluster is errored, then an edit to valid configuration should allow the cluster to reconcile successfully.

### What areas could experience regressions?
Replacing control plane nodes of a successfully provisioned cluster.

### Are the repro steps accurate/minimal?
Using OCI is probably the easiest way to reproduce. There is a way to reproduce using Digital Ocean, but it is much more complicated. The steps are included for completeness:
1. Create a cloud credential for Digital Ocean
2. Create a cluster using the Digital Ocean cloud credential, but BEFORE YOU ARE READY TO CLICK CREATE.
3. Using `kubectl`, edit the cloud credential secret and remove everything in the `data` section. Probably better to save the data section somewhere so you can add it back when ready.
4. Click "Create" in the UI.
5. Wait for the error to occur in the UI.
6. Put the `data` section back in the cloud credential secret.
7. In the UI, edit the cluster. You can do something simple like changing the OS image.
8. Click "Save"
9. The cluster should create successfully after several minutes.

**Comment by Auston-Ivison-Suse** [comment]
**Moving Back to Re-opend**

When trying to validate the fix I was running into the issue Izaac describes. 

**My Setup**

- Rancher Version: 2.6-head commit (931a0f0)
- Installation option: Helm HA
    -Kubernetes Cluster and version: RKE1 k8s v1.21.5
-Proxy/Cert Details: rancher-self-signed

**Downstream Cluster**

- Kubernetes version: v1.21.4+rke2r2
- Cluster Type: `Downstream
    - RKE 2 Cluster Oracle OCI Driver
    - VM.Standard2.8 Nodes Shape


![Screen Shot 2021-11-03 at 10.05.51 AM.png](https://zube.io/files/rancher/8eb50b7adfb7178b4ca0e8cd35c6ef50-screen-shot-2021-11-03-at-10-05-51-am.png)

**Comment by Auston-Ivison-Suse** [comment]
**Setup for Reproduction**

Rancher version: v2.6.2
    Installation method: Docker install using the following command in ec2 instance
```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:latest
```

**setup for validation**
Rancher version: v2.6-head (638b29a) 
    Installation method: Docker install using the following command in ec2 instance
```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:v2.6-head
```

**Steps for reproduction & Validation:**
1. Activate Oracle Cloud Infrastructure(OCI) node driver within Cluster Management ---> Drivers ---> Node Drivers ---> Select the OCI node driver and click activate
2. Go to create cluster selecting RKE2 slider and selecting OCI as the provider. 
3. Land on the create credential's page, enter the following fields from previous made account with Oracle. Create account here: https://cloud.oracle.com/identity/users/ocid1.user.oc1..aaaaaaaakc2x64wi5axhmcv52wjfiinmsuo5a6gsa7yizhihc7b37qylmvsq/groups?region=us-sanjose-1

  - Fingerprint
  - privateKeyContents (contents of pem file)
  - tenancyId
  - userID
4. Land on the Create cluster page and fill out the following fields for your Pool 1, you will have obtained these previously with from your oracle account. 
  - nodeAvailabilityDomain
  - nodeCompartmentId
  - nodeImage
  - nodeShape
  - region
  - subnetId
  - vcnCompartmentId
  - vcnId
  All other fields are left empty.
5. Be sure that all three roles are selected for pool 1 node. 
6. Create pool 2 node following the previous steps with only two differences. 
  a. Only give this node the worker role
  b. leave region empty. 
7. Uncheck  "metrics server" this will give the node more resources to use. 
8. Press create. 

Following the press create:

  - You should see the cluster provision except with a single node not provisioning with this following error: 
![Screen Shot 2021-11-11 at 4.19.48 PM.png](https://zube.io/files/rancher/07b73b90052464a1a4855d2f80beda02-screen-shot-2021-11-11-at-4-19-48-pm.png)

Now to test/reproduce the self healing feature:
1. From cluster management click the 3 dot menu(kebab) and edit config.
2. Go to pool 2 and enter the correct region and press save. 
3. Observe that the cluster doesn't delete the previous node like it should. 

**Results**
When reproducing the issue I am able to edit the config with the appropriate data and press save. 
Which then leads to the issue where the node doesn't self heal.

When attempting to validate the fix I'm not able to save the updated config. I get the following result: 
![Screen Shot 2021-11-11 at 4.22.09 PM.png](https://zube.io/files/rancher/20d1766e5fc65de5533edb0008ef6394-screen-shot-2021-11-11-at-4-22-09-pm.png)

**Comment by thedadams** [comment]
@Auston-Ivison-Suse That comes from the UI. Refreshing the page fixes that.

**Comment by sowmyav27** [comment]
Reopening to test a few more usecases

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Further Validation**
- Rancher Version: v2.6-head (44b8030)
- Cluster info: RKE2 3 nodes of each role, using ec2

**Steps For Validation of Control Plane Usecase**
1. Provision a cluster with a specific instance type ex. t3.medium
2. Let the cluster provision, then select the cluster from cluster explorer
3. go to "edit config" from the kebab menu. 
4. Change the instance type of the control plane machines to something else and press save.

**Results**
A new machine starts to provision while another starts to delete. This continues until all three old machines are replaced with the newly configured nodes. 

**Sanity Testing**
- Replace the nodes several times, 4-5. _Passed_
- Add the worker role to the control plane in the edit config and save. _Passed_
- Remove the worker role from the control plane and save. _Passed_
