### ISSUE TITLE
Add Docker 20.10.8 & 20.10.9

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#35031]
https://github.com/moby/moby/releases/tag/v20.10.9

**Comment by rayandas** [comment]
Tracking the issue here: https://github.com/rancher/rancher/issues/34615

**Comment by rayandas** [comment]
Validation steps:

Create AWS infrastructure provider with 3 nodes, 1 role each.
- Change Docker Install URL to `https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.8.sh` in node template (as current changes are not synced yet with CDN release.rancher.com).
- Launch cluster and wait for cluster to become available.
- Do the same for Docker version `20.10.9`

Create DO infrastructure provider with 3 nodes, 1 role each.
- Change Docker Install URL to `https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.8.sh` in node template.
- Launch cluster and wait for cluster to become available.
- Do the same for Docker version `20.10.9`

Create a custom cluster, 1 node all roles.
- Install Docker using `https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.8.sh`
- Launch cluster and wait for cluster to become available.
- Do the same for Docker version `20.10.9`

**Comment by vivek-infracloud** [comment]
### Validated on rancher v2.6-head

Steps followed.

- On rancher v2.6-head (7efbeab) created an AWS node template with docker install URL set to `https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.8.sh`
- Created a cluster.
- Made sure the installed docker version is v20.10.8
- Did the same with docker install URL for v20.10.9

Closing the issue, since docker install scripts working as expected.
