### ISSUE TITLE
RKE2 version does not get refreshed upon a refresh of rke-metadata-config 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35073]
on v2.6-head (7bc7959):
- Update setting `rke-metadata-config` url to `https://raw.githubusercontent.com/kinarashah/kontainer-driver-metadata/21812d7e35cdc5a8fcca3b470751500633dbdcd1/data/data.json`. 
- Refresh Kontainer-driver-metadata from cluster management -> Drivers page. 
- Confirm both RKE2 and k3s have new versions `v1.21.6` -- pass
- Switch the `rke-metadata-config` back to default, k8s versions should now show only `v1.21.5` -- fail
  - also tried hard refershes, but only the k3s version is changing. RKE2 is not updating back to v1.21.5
<img width="640" alt="Screen Shot 2021-10-07 at 10 12 52 AM" src="https://user-images.githubusercontent.com/16691014/136432371-4cb2c3ef-8518-4379-a6fc-c5d209e9fd74.png">

upon further investigation, there still seems to be an issue with the refresh feature. currently, we seem to be in a `partial` refresh state.  The above behavior is observed in the following case:
* update rke-metadata-config
* refresh kontainer-driver-metadata (`cluster management` -> `drivers` -> button) by clicking 1 time

However, if the user clicks the refresh button a second time without leaving the page, both k3s and rke2 are updated to the versions matching what is in rke-metadata-config

Related issue: https://github.com/rancher/rancher/issues/34473

**Comment by jiaqiluo** [comment]
### Root cause

1. RKE2 metadata update is not invoked when editing the rke-metadata-config setting.
2. RKE2 metadata is not updated all the time when refreshing the Kubernetes Metadata manually via UI. This is a little complicated. Basically, we have two goroutines listening to the same channel, which causes a race condition. Each time a value is sent to the channel, only one of those two goroutines will get the value. (Note: this could happen for either k3s or RKE2 although it is reported for RKE2)

### What was fixed, or what changes have occurred

1. Add the missing call for the RKE2-refreshing function in the handler for KDM metadata.
2. Eliminating the race conditional by changing both the channel and how the goroutines handle the value from the channel.

### Areas or cases that should be tested

1. - Edit the rke-metadata-config setting, conform a refreshing of rke2 and k3s metadata happens.
2. - Refreshing the Kubernetes Metadata manually via UI, conform a refreshing of rke2 and k3s metadata happens.
  
### What areas could experience regressions?
 none
### Are the repro steps accurate/minimal?
the steps in the issue cover case 2, QA also need to validate case 1.

**Comment by slickwarren** [comment]
tested using rancher v2.6-head (e55a04c):

* Edit the rke-metadata-config setting, conform a refreshing of rke2 and k3s metadata happen -- pass
* Refreshing the Kubernetes Metadata manually via UI, conform a refreshing of rke2 and k3s metadata happens -- pass
* revert to default is working and metadata is refreshed -- pass

**Comment by nickderoo-hv** [comment]
Can anyone suggest a workaround for this issue? 
I'm unable to get the rancher metadata pod to correctly sync through the proxy or take the updated version when I update the rke-metadata-config global setting.

` Starting webserver...                                                                                                                                                                                                                                               │
│ AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.42.2.30. Set the 'ServerName' directive globally to suppress this message                                                                                           │
│ Detected proxy settings.                                                                                                                                                                                                                                            │
│ Starting downloader...                                                                                                                                                                                                                                              │
│ Downloading kontainer-driver-metadata for v2.4                                                                                                                                                                                                                      │
│ --2024-08-27 14:47:25--  https://releases.rancher.com/kontainer-driver-metadata/release-v2.4/data.json                                                                                                                                                              │
│ Resolving releases.rancher.com (releases.rancher.com)... 18.161.21.4, 18.161.21.33, 18.161.21.78, ... `
