### ISSUE TITLE
Use managed network without agent-instance

### ISSUE THREAD

**Issue by DennyLoko** [rancher/rancher#3508]
Hello,

We have several servers which we have installed rancher on them and they works fine, but we also have some others which runs in our private infrastructure and we need to have more precise control of which containers run on them, so we can't install rancher to manage their containers, so we have installed an OpenVPN client on them and we were able to connect to the containers on the managed network.

The problem is the reverse. We want that our containers which are on the rancher's managed network be able to connect on the containers outside the rancher's structure.

To try accomplish that, I've created a new docker network and configured it to assign the IPs on the managed network using the following command `docker network create --driver=bridge --subnet=10.42.0.0/16 --ip-range=10.42.0.0/16 --gateway=10.42.0.1 testnw`. So every new container in this specific hosts are created using the IP of the managed network, but only this approach was not sufficient to work.

What I'm trying to do is possible? I've made any mistake?

Thanks.

**Comment by cloudnautique** [comment]
It might be simpler then that, If the underlying hosts have routes setup that can communicate with your private cloud infrastructure, you could use `external services` which are really just DNS entries. You can link to them etc. They are what we had in mind for handling the Rancher outbound discovery. The docs can be found [here](http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-external-services/) Would this help?

**Comment by DennyLoko** [comment]
Hi @cloudnautique,

First of all thanks to reply.

Unfortunately this doesn't help, since we are trying to not expose any port to outside world, that's why we want use the VPN with the rancher's managed network.

**Comment by vincent99** [comment]
Maybe we can solve "precise control of which containers run on them" instead?  You can label the hosts and then use scheduling rules to decide what services are/aren't allowed on them.

Or this is a little hacky but you could add the agent and then Deactivate the host in Rancher/the UI.  That will make it so that we never schedule containers to those hosts, but it will still keep track of what is running on the host and you could run containers manually/however you're starting them now with the `io.rancher.container.network=true` label to have them get a 10.42.x.y Rancher IP.

**Comment by deniseschannon** [comment]
@DennyLoko Would @vincent99's suggestions work?

**Comment by deniseschannon** [comment]
@DennyLoko Please re-open with more questions if you are unable to use @vincent99's workaround.
