### ISSUE TITLE
Rancher keeps redirecting to port 443 despite "tls=external"

### ISSUE THREAD

**Issue by stewie83** [rancher/rancher#35088]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart):
   - Helm Chart on RKE2 cluster. RKE2 v1.21.5+rke2r1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21.5
- Cluster Type (Local/Downstream):
   - Local

**Describe the bug**
Rancher keeps doing HTTPS redirect despite _tls=external_ flag set in Helm chart and _use-forwarded-headers=True_ in Nginx ingress controller configuration

**To Reproduce**

1. Deploy rancher on Kubernetes per instructions [here](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/).
2. Follow "tls=external" instructions [here ](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/chart-options/#external-tls-termination) to terminate SSL on an upstream proxy (HAProxy, in this case) whose backends are cluster nodes on 80/tcp.
3. Enable "use-forwarded-headers=true" on the Nginx ingress as explained [here](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/chart-options/#external-tls-termination)
4. Test that you can reach rancher directly on the cluster on 80/tcp using the "required" headers mentioned [here](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/chart-options/#external-tls-termination).
```
 curl -H "Host:rancher.hostname.com" \
        -H "X-Forwarded-Proto:https" \
        -H "X-Forwarded-Port:443" \
        -H "X-Forwarded-For:<ip of client>" \
        -i <ip of worker node>
```

**Result**
The ingress redirects (302) to port 443. This causes loops when coming through the upstream proxy.

**Expected Result**
The ingress should not redirect to port 443.

**Screenshots**

**Additional context**

Helm command used to deploy rancher:

```
helm install rancher rancher-latest/rancher \
        --namespace cattle-system \
        --set hostname=rancher.hostname.com \
        --set tls=external`
```

Ingress describe command:

```
Name:             rancher
Namespace:        cattle-system
Address:          10.X.Y.15,10.X.Y.25,10.X.Y.27
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                            Path  Backends
  ----                            ----  --------
  infra-rke2-brno.kmglobalrd.com  
                                     rancher:80 (10.42.0.10:80,10.42.1.2:80,10.42.2.2:80)
Annotations:                      field.cattle.io/publicEndpoints:
                                    [{"addresses":["10.X.Y.15","10.X.Y.25","10.X.Y.27"],"port":80,"protocol":"HTTP","serviceName":"cattle-system:rancher","ingress...
                                  meta.helm.sh/release-name: rancher
                                  meta.helm.sh/release-namespace: cattle-system
                                  nginx.ingress.kubernetes.io/proxy-connect-timeout: 30
                                  nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
                                  nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
                                  nginx.ingress.kubernetes.io/ssl-redirect: false
                                  nginx.ingress.kubernetes.io/use-forwarded-headers: true
```

**Comment by davemuench** [comment]
I am running into this same issue with a fresh install of Rancher 2.6.2 with k3s v1.21.5+k3s2. I am new to k3s, but it appears to be using traefik instead of nginx, and it is having the same issue. I see the same behavior above testing with curl as well.

**Comment by ninedongsu** [comment]
Hi @davemuench , I installed same yours(k3s + traefik ingress controller + rancher helm stable version) and success to access 80 port with no redirect to 443 port.

plz check below my steps

0. configure your LB
 - you should config the `X-Forwarded-Proto` header for LB.

1. install k3s
```
$ curl -sfL https://get.k3s.io | sh -s - server --docker \
 --datastore-endpoint="mysql://username:password@tcp(hostname:3306)/database-name"
```

2. install helm
```
$ curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
$ chmod 700 get_helm.sh
$ ./get_helm.sh
```

3. install rancher-stable using helm(with TLS Termination options)
```
$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
$ kubectl create namespace cattle-system
$ helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=your-lb-domain \
  --set replicas=3 \
  --set tls=external
```

4. edit k3s traefik manifest file
add  `valuesContent.additionalArguments` into `/var/lib/rancher/k3s/server/manifests/traefik.yaml` file.
```
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.insecure"
      - "--entryPoints.web.forwardedHeaders.insecure"
````
when  you save the file, the traefik pod will redeploy.

5. test with curl
```
$ curl https://your-lb-domain -H "X-Forwarded-Proto: https" -v

SKIP...

> Host: your-lb-domain
> User-Agent: curl/7.58.0
> Accept: */*
> X-Forwarded-Proto: https
>
< HTTP/1.1 200 OK
< Content-Type: application/json

... SKIP
```

**Comment by moubctez** [comment]
>  4. edit k3s traefik manifest file
>    add  `valuesContent.additionalArguments` into `/var/lib/rancher/k3s/server/manifests/traefik.yaml` file.
> 
> ```
>   valuesContent: |-
>     additionalArguments:
>       - "--entryPoints.web.proxyProtocol.insecure"
>       - "--entryPoints.web.forwardedHeaders.insecure"
> ```

This fixes the problem for me, but occasionally the change gets erased. Is Rancher auto-updating Traefik or its chart values?

**Comment by maradwan** [comment]
* ingress-nginx 
helm upgrade --install \
  ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --set controller.service.type=LoadBalancer \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-cert"=arn:aws:acm:xxx \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol"=http \
  --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports"=https \
  --set controller.service.targetPorts.https=http \
  --set-string controller.config.use-forwarded-headers="true" \
  --version 3.12.0 \
  --create-namespace  
  
  * rancher
  helm install rancher rancher-stable/rancher   --namespace cattle-system   --set hostname=XXX.com   --set replicas=3 --set tls=external

**Comment by gpow81** [comment]
Here is my solution. 
As most people already found, missing use-forwarded-headers="true"  for the nginx-ingress is the culprit. My main problem was how to set it. It probably depends  on which kube you run - k3s, rke or rke2. Documentation tells about adding this setting to cluster.yml.  What, how, huh?  I couldn't find anything about cluster.yaml for the rke2 so finally I realized that it must be for k3s or something else. Anyway in RKE2 documentation (https://docs.rke2.io/networking/) I found that for RKE2 all we need to do is: 
create /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml :
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        use-forwarded-headers: "true"

If you do this before installing rke2 then of course you need to create that directory first, dump in the file and proceed with installation of rke2 and rancher
But you can do this at any moment, even after installing rke2 and rancher.   (don't forget about --set tls=external when you do helm install rancher) 

I was able to confirm that the “use-forwarded-headers” has been added (or not) by running: 
kubectl get configmap rke2-ingress-nginx-controller -n kube-system -o yaml
…
data:
  allow-snippet-annotations: "false"
  use-forwarded-headers: "true"

The second line will literally pop up in there few seconds after dropping that /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml  in. There is a process which monitors that directory and when there is a new manifest it automatically does apply on it.
This made my proxy setup for rancher (with ssl termination) work right away. 

It also works if you just edit the config map instead of adding the file:
kubectl edit configmap rke2-ingress-nginx-controller -n kube-system   and adding that line manually but I am not sure if it would stick during cluster upgrades. 

The nginx.conf for the proxy which terminates SSL was fine the way it was suggested in the documentation. 

One more problem I had was “An error occurred logging in. Please try again.”   right after providing initial password for the rancher. 
This again has something to do with proxy and ports. I was trying to set my proxy on port 4444 (outside port) but apparently it didn’t like it. Changing my outside port to 443 solved the issue.
I didn’t have any enough will power left in my to find out why I can’t use other port :( 

Hope this helps

**Comment by cdstg** [comment]
> This fixes the problem for me, but occasionally the change gets erased. Is Rancher auto-updating Traefik or its chart values?

I added a file 
 /var/lib/rancher/k3s/server/manifests/traefik-config.yaml


with this inside problem solved and the pods were redeployed  automatically 


apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.insecure"
      - "--entryPoints.web.forwardedHeaders.insecure"

**Comment by vallimangai** [comment]
Still Facing the same issue
http call is redirecting to https
even after adding the annotations in ingress
nginx.ingress.kubernetes.io/ssl-redirect: false
nginx.ingress.kubernetes.io/use-forwarded-headers: true
