### ISSUE TITLE
Rancher max version for logging V1

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#35111]
we should restrict the logging v1 chart to a maximum rancher version

only the latest version of logging v1 should be installable all older versions should be restricted.  We should also restrict all versions to less than 1.21

**Comment by sowmyav27** [comment]
@paynejacob Couple of questions,

Can you confirm if the requirements in the original issue's description are fixed, since from the PR, i see only one of the three reqs is fixed.
- restrict the logging v1 chart to a maximum rancher version
- On 2.6-head/2.6.3, only the latest version of logging should be available to deploy
- restrict all versions to less than 1.21 --> Is fixed in the linked PR.

**Comment by sowmyav27** [comment]
Closing this as per [this](https://github.com/rancher/rancher/issues/35111#issuecomment-967760281) and an offline discussion
