### ISSUE TITLE
2.6.1 replica increase/decrease button for workloads

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#35149]
**Is your feature request related to a problem? Please describe.**
The old UI had a +/- button to quickly increase/decrease replica counts for workloads, however in the new UI this seems to be completely removed. It appears that the only way to change replica count is to edit the config of a workload.

**Describe the solution you'd like**
Please put the feature back

**Describe alternatives you've considered**

**Additional context**

**Comment by a-nldisr** [comment]
In a previous environment we used DC/OS. There was a stop button per directory, which translates to a namespace in Kubernetes. With this you could set all the instances/replica's to 0. 
**Use case:**
We have groups of Developers starting POC's and environments in our test/acceptance environments. On some moments you just need the capacity for something that needs to be expedited. Instead of going through each deployment setting replica's to 0, I would love the ability to just press a scale down button to bring everything in a namespace to a halt.

**Comment by richard-cox** [comment]
Scaling workloads is possible via editing the workload itself. The scale up/down buttons will be returning soon and is covered by https://github.com/rancher/dashboard/issues/4328
