### ISSUE TITLE
Documentation: improvement suggestions

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3517]
### Adding a search form:

![image](https://cloud.githubusercontent.com/assets/2150990/12813121/4e665648-cb36-11e5-967a-c35f7795b343.png)
(image from another random project)

### Adding a read progression indicator:

Like here ( http://getbootstrap.com/css/#grid-example-fluid)

Rancher:

 ![image](https://cloud.githubusercontent.com/assets/2150990/12813312/8aaade8e-cb37-11e5-8c67-a1e8b969b521.png)

Bootstrap (for comparaison):
![image](https://cloud.githubusercontent.com/assets/2150990/12813343/b191c4fe-cb37-11e5-98b4-7cf4c3371249.png)

in the same topic, it would be better if the side menu were kept visible on the screen. 
For now, scrolling makes the menu disappear completely:

![image](https://cloud.githubusercontent.com/assets/2150990/12845606/5ee51abe-cc07-11e5-86b5-958d425b95a3.png)
 
### Updating the Copyright 

Current one is sooo 2015 :)

![image](https://cloud.githubusercontent.com/assets/2150990/12813407/1826502c-cb38-11e5-887a-3a94bd6faccc.png)

### HA = High availability

Minor suggestion, but it would be to use full concept names at least ones along abbreviations

on http://docs.rancher.com/rancher/concepts/, searching `high availability` yields only one result in the first line of the [#distributed-dns-service](http://docs.rancher.com/rancher/concepts/#distributed-dns-service) section, despite the fact there is a [#service-ha](http://docs.rancher.com/rancher/concepts/#service-ha) section in the same page

mention

didn't see those mentioned before [is:open is:issue label:area/documentation](https://github.com/rancher/rancher/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fdocumentation)

**Comment by faddat** [comment]
Some usage guidelines would be good, too.  I'm about to make a rancher forum post, trying to get feedback from the community on this:  I'm curious how people have ended up using Rancher in terms of number of containers that are able to be hosted in these scenarios:

a) per deployment (for convenience's sake let's say that means 1 master, 8-core & 64gb or smaller, with as many nodes as that might able to support of equal or lesser power)
b) per host (of course I know this varies wildly, so I guess I am looking mostly at bare metal and high-power cloud deployments of Rancher)

Over the past year or so I've heard from a few developers that the API documentation is sparse.  I am not sure that this is still the case.  I think that both Rancher and Rancher OS could use a very visible (github repo "readme"?) graphical roadmap.  Because of the nature of these products (I'm sure you're aware) users are planning their systems right alongside your plans, so keeping those users well informed as to the direction of the product overall and what that means for their deployment will be critical in upcoming years.  

All of that said, I'd like to thank the Rancher team very sincerely:  If I had never run into your software, I would not be doing what I now do professionally.  I mean this entirely literally, and lucky for me, this is without a doubt the most interesting, satisfying work I've ever had.

**Comment by deniseschannon** [comment]
@rvion I did the easy ones (copyright, HA), but I will need to see when I get some more free time to work on the search bar and read progression indicator. :)

@faddat Thanks for the feedback, our roadmap is constantly changing as priorities shift and we're stll in beta. So as of now, having a graphical roadmap will probably get out of date quickly. After GA, we can look into adding a more high level roadmap.

**Comment by faddat** [comment]
@deniseschannon 
Operating in the "linux container business space" myself, wow do I ever connect to what you're saying about shifting priorities.  Good luck shifting them well!  :+1:

**Comment by deniseschannon** [comment]
Thanks to @lvuch and @vincent99, we've added in a search bar and the navigation changes.  I'm going to close this issue for now.

**Comment by rvion** [comment]
thanks !
