### ISSUE TITLE
[BUG] Users with Create Cluster permissions can not see available RKE2 cluster templates

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#35177]
Rancher 2.6.1

1. Add RKE2 cluster templates to Rancher installation (see[ docs](https://rancher.com/docs/rancher/v2.6/en/admin-settings/cluster-templates/#rke2-cluster-template))
2. Create a standard user with following global permissions:
- User-Base
- Create new Clusters
3. Login as the standard user and navigate to Cluster Management -> Create, Toggle RKE2

**Expected:**
The configured cluster templates are shown

**Actual:**
The cluster templates are not shown

**Comment by slickwarren** [comment]
on v2.6.1 I tested the following:
* standard global role -- user is able to see rke2 templates added by admin
* base-user global role + `create new clusters` -- user is not able to see rke2 templates added by admin
* base-user global role + all roles configurable in the UI -- user is not able to see rke2 templates added by admin

**Comment by jakefhyde** [comment]
### Root cause

The `create-clusters` role did not have access to get/list/watch cluster repos, so non-admin users were not able to provision clusters with them.

### What was fixed, or what changes have occurred

The `create-clusters` role was updated to allow the user to view these resources.
 
### Areas or cases that should be tested

Creating a cluster using an rke2 template.

### What areas could experience regressions?

N/A
 
### Are the repro steps accurate/minimal?

As an admin user, add the [cluster template examples repo](https://github.com/rancher/cluster-template-examples). Create a user with the `create-clusters` role, and try to provision an rke2 cluster using the template.

**Comment by slickwarren** [comment]
tested on v2.6-head (c682e30):
* provision cluster from rke2 template as standard user  -- pass
*  provision cluster from rke2 template as base user with `create cluster` role -- pass
  * verify user only has access to their cloud credentials in rke2 template -- pass
  * verify user can access rke2 template(s) added by admin -- pass
