### ISSUE TITLE
Authorized Cluster Endpoint unavailable after upgrading to Rancher 2.6.x and RKE 1.21.5-rancher1-1

### ISSUE THREAD

**Issue by Blackclaws** [rancher/rancher#35187]
**Rancher Server Setup**
- Rancher version: 2.6.1
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm Chart

**Information about the Cluster**
- Kubernetes version: RKE 1.21.5-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE Rancher Launched using Docker

**Describe the bug**

Authorized cluster endpoint isn't working, even after enabling and reenabling it the following issue presents itself:

Kubectl output:
```
error: You must be logged in to the server (Unauthorized)
```

Output of the kube-api-auth pod:
```
time="2021-10-19T17:23:39Z"  level=error msg="clusterAuthToken.cluster.cattle.io  \"cattle-system/kubeconfig-u-m2ac4e3amu.c-hjvg2\" not found"
--
```

And indeed the result of the check whether there is any token results in:
```
$ kubectl get clusterAuthToken.cluster.cattle.io --all-namespaces
No resources found
```

The endpoint is enabling/disabling correctly as the resource types are created. However it seems no auth token is being created when the kubeconfig is being downloaded.

**To Reproduce**
This is where it gets tricky. I've upgraded these clusters from rancher 2.5.10 and the then current RKE version. I haven't done anything else to them and the endpoint has always been enabled. I've tried disabling and reenabling it.

**Result**
Access denied

**Expected Result**

Authorized Endpoint works

**Screenshots**

**Additional context**
Power cycling the cluster does not solve the problem.
Installing a new cluster with rke 1.21.5-rancher1-1 shows the same issue.

Logs from the rancher pod itself:
```

2021/10/19 17:48:03 [ERROR] error syncing 'kubeconfig-u-m2ac4e3amu.c-hjvg2': handler cat-token-controller: clusterAuthToken for token [kubeconfig-u-m2ac4e3amu.c-hjvg2] has not been created yet, requeuing
2021/10/19 17:48:12 [ERROR] error syncing 'c-9qr2x': handler restrictedAdminsRBACCluster: 1 error occurred:
	* RoleBinding.rbac.authorization.k8s.io "crt-c-9qr2x-cluster-owner-" is invalid: subjects[0].name: Required value

, requeuing
2021/10/19 17:48:16 [ERROR] error syncing 'c-pr5ds': handler restrictedAdminsRBACCluster: 1 error occurred:
	* RoleBinding.rbac.authorization.k8s.io "crt-c-pr5ds-cluster-owner-" is invalid: subjects[0].name: Required value


```

Feature flags:
```
> kubectl get features.management.cattle.io
NAME                          CUSTOM VALUE   DEFAULT   DESCRIPTION
continuous-delivery           <no value>     true      Gitops components in fleet
fleet                         <no value>     false     Install Fleet when starting Rancher
harvester                     <no value>     true      Enable Harvester integration, with ability to import and manage Harvester clusters
istio-virtual-service-ui      <no value>     true      Exposes a UI that enables users to create, read, update and delete virtual services and destination rules, which are traffic management features of Istio.
legacy                        true           false     Enable legacy features
multi-cluster-management      <no value>     false     Multi-cluster provisioning and management of Kubernetes clusters.
rke2                          <no value>     false     Enable provisioning of RKE2
token-hashing                 <no value>     false     Enable one way hashing of tokens. Once enabled token hashing can not be disabled
unsupported-storage-drivers   <no value>     false     Allows the use of types for storage providers and provisioners that are not enabled by default.
```

Since this might be relevant to the bug. Users are SSO users via Keycloak SAML.

**Comment by davidnuzik** [comment]
**I failed to  reproduce**
Note: While I failed to reproduce this doesn't necessarily mean this issue does not exist. It's possible that the steps to reproduce could have been misinterpreted or that my environment was different in some way that could cause me to not reproduce the issue.
 
**Reproduction Environment:**

Rancher version: v2.5.10 to v2.6.1
Rancher cluster type: HA
 
Downstream cluster type: RKE1
Downstream K8s version: v1.20.11-rancher1-1 via AWS EC2 Node driver, upgraded post rancher upgrade to v1.21.6-rancher1-1 (the latest available in the UI).
 
**Reproduction steps:**

0. Throughout all testing watch the rancher pod logs for any errors.
1. Install Rancher 2.5.10. Setup Keycloak SAML as the auth provider. Create a downstream RKE1 cluster - I used the AWS EC2 node driver to create this downstream cluster. RKE k8s version 1.20.11-rancher1-1. ACE should be enabled when creating the cluster (it is by default).
2. Wait for the downstream cluster to provision, when it is ready get the kubeconfig from the Rancher UI. Set it as the config for `kubectl` on another machine. Ensure the primary context works (it does). Now, use the secondary context (This is the ACE context) -- `kubectl config use-context 2ND-CONTEXT-NAME` ensure this works (it does).
3. Now, upgrade rancher to v2.6.1. During this process I didn't notice anything concerning in the rancher pod logs. When the upgrade is done reset the kubectl queries (I actually used kubetail) so they monitor the new rancher pods (the upgraded ones).
4. Now, upgrade the downstream RKE1 cluster to the latest available version. Due to a KDM release this is v1.21.6-rancher1-1 (issue reports v1.21.5-rancher1-1 as that was probably the latest at the time).
5. Ensure that the secondary context still works with the same kubeconfig for the downstream cluster. This works for me -- I didn't encounter any issues.
 
**Additional Info:**

I have some thoughts about my attempt to reproduce. Maybe I could not reproduce due to any of the following?
- Misinterpretation of the issue (maybe an imported rke cluster was used as the downstream cluster? This is not clear)
- My environment could be slightly different or Keycloak SAML server slightly different in some way
- The newer RKE version I upgraded to for the downstream cluster could be a factor
- Something else

cc: @sowmyav27 for awareness.

**Comment by Blackclaws** [comment]
Ok the fact that you can not reproduce it gives me hope that this is an issue with our environment rather than with rancher itself. I'll try to setup a new separate rancher server and try to reproduce the issue myself on a different cluster.

Some additional info myself:

- Its not an imported RKE Cluster, it was launched in 2.5 and just ported over automatically
- The downstream RKE version doesn't seem to matter as I've upgraded it to the latest available version as well (even the one shipped with 2.6-head and marked as experimental)
- Rancher itself is running on a k3s cluster, the same cluster that keycloak itself is running on
- The nodes themselves are baremetal and not cloud hosted, might make a difference as our environment isn't the same there. 

If I can reproduce it in an additional cluster I'll let you know, if I can't reproduce it myself that will make it probably impossible to diagnose as reproduction is the first step in such a process as always.

**Comment by Blackclaws** [comment]
> **I failed to reproduce** Note: While I failed to reproduce this doesn't necessarily mean this issue does not exist. It's possible that the steps to reproduce could have been misinterpreted or that my environment was different in some way that could cause me to not reproduce the issue.
> 
> **Reproduction Environment:**
> 
> Rancher version: v2.5.10 to v2.6.1 Rancher cluster type: HA
> 
> Downstream cluster type: RKE1 Downstream K8s version: v1.20.11-rancher1-1 via AWS EC2 Node driver, upgraded post rancher upgrade to v1.21.6-rancher1-1 (the latest available in the UI).
> 
> **Reproduction steps:**
> 
>     0. Throughout all testing watch the rancher pod logs for any errors.
> 
>     1. Install Rancher 2.5.10. Setup Keycloak SAML as the auth provider. Create a downstream RKE1 cluster - I used the AWS EC2 node driver to create this downstream cluster. RKE k8s version 1.20.11-rancher1-1. ACE should be enabled when creating the cluster (it is by default).
> 
>     2. Wait for the downstream cluster to provision, when it is ready get the kubeconfig from the Rancher UI. Set it as the config for `kubectl` on another machine. Ensure the primary context works (it does). Now, use the secondary context (This is the ACE context) -- `kubectl config use-context 2ND-CONTEXT-NAME` ensure this works (it does).
> 
>     3. Now, upgrade rancher to v2.6.1. During this process I didn't notice anything concerning in the rancher pod logs. When the upgrade is done reset the kubectl queries (I actually used kubetail) so they monitor the new rancher pods (the upgraded ones).
> 
>     4. Now, upgrade the downstream RKE1 cluster to the latest available version. Due to a KDM release this is v1.21.6-rancher1-1 (issue reports v1.21.5-rancher1-1 as that was probably the latest at the time).
> 
>     5. Ensure that the secondary context still works with the same kubeconfig for the downstream cluster. This works for me -- I didn't encounter any issues.
> 
> 
> **Additional Info:**
> 
> I have some thoughts about my attempt to reproduce. Maybe I could not reproduce due to any of the following?
> 
>     * Misinterpretation of the issue (maybe an imported rke cluster was used as the downstream cluster? This is not clear)
> 
>     * My environment could be slightly different or Keycloak SAML server slightly different in some way
> 
>     * The newer RKE version I upgraded to for the downstream cluster could be a factor
> 
>     * Something else
> 
> 
> cc: @sowmyav27 for awareness.

It seems I forgot to add one vital piece of information. 

Everything works fine in the default install. When you apply the steps from [Setting TTL on Kubeconfig Tokens](https://rancher.com/docs/rancher/v2.5/en/api/api-tokens/#setting-ttl-on-kubeconfig-tokens) is when it stops to work.

The first two steps are enough. As soon as you switch from having a token embedded in the kubeconfig to having the rancher command in the kubeconfig it breaks.

**Comment by davidnuzik** [comment]
Do you set TTL on the kubeconfig tokens in v2.5.10 or after the upgrade?
It may not matter but just want to make sure I get the timing of this correct when I try to reproduce again.

**Comment by Blackclaws** [comment]
Either produces the issue. In the original issue that happened I set the TTL on the 2.5 instance and it just persisted through the upgrade. In my repro I've set it after seeing that it still worked in 2.6 and found out that setting that breaks it.

**Comment by davidnuzik** [comment]
I cannot encounter the issue with v2.5.10. I will try upgrading and see if the issue happens to me post-upgrade but this will take some time as I am juggling other priorities currently.
