### ISSUE TITLE
Implement cache-control headers on responses from Rancher API response for agent nodeplan

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35199]
SURE-2953

**Rancher Server Setup**
CentOs 7.9, Docker 19.03.14
K8s 1.17.17-rancher1-1 , Rancher 2.5.7

... Singular RMC on 2.5.7, 3x Downstream Custom Clusters (Prod/Dev/Test)

**Describe the bug**
... Singular RMC on 2.5.7, 3x Downstream Custom Clusters (Prod/Dev/Test).. All clusters are unhealthy, etcd is down.. We are seeing agents fire up in one cluster and deploy workloads for another cluster, multiple agents running on downstream CP nodes with versions 2.4.12, 2.5.5, and 2.5.7.  We are getting SSL errors across the board, its like they are getting the wrong certs. 

The short version is the customer had clusters where the nodes' were registering to the wrong clusters/environments due to enabling a caching feature option on their F5 load balancer.  A workaround was introduced - see SURE ticket.

Business impact:

Affects all but one of their downstream clusters.  Only their prod cluster is showing as operating in Rancher.

Troubleshooting steps:

Tried rolling back VM snapshots from downstream control-plane node, restarting agents on downstream control-plane node.  Still seeing many cert errors.

**To Reproduce**
troubleshooting uncovered a proxy that had been caching the api calls, they disabled that and their issues went away.. it was determined that setting cache control headers would had been adequate to prevent such a failure in any other environment.

**Comment by cmurphy** [comment]
Some notes on design/implementation based on @superseb 's comment in jira:

> * Design should cover implementing this for all API responses
> * If not, this customer issue should be specifically mentioned to see if we want to implement it for the nodeplan endpoint only or not at all
> * Possible regression/risks of implementing it

### Implementing for all API responses

This initially sounded high risk to me but I actually think it's not. In my testing with Firefox, browsers already don't cache any resources served by the Rancher server, either because we set the `Expires` header to 0 on encoded responses[[1]](https://github.com/rancher/norman/blob/82478fb169cbfbc255c94c14a7bd3620fd08599b/api/writer/headers.go#L29)[[2]](https://github.com/rancher/apiserver/blob/c4e289f92e46c8556ba2b62a907d7c2aaca4c00f/pkg/writer/headers.go#L23) or because we don't set any Cache-Control or Expires headers at all, for example in the case of the `/meta/*` endpoints, in which case ["we do not expect it to be cached"](https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.4), though this is not a guarantee.

So setting `Cache-Control: no-store` ([ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-store)) should be a noop for browsers.

So for the most part this should only affect the case where some intermediate cache (F5, squid, varnish) has some explicit settings that cause it to cache responses in the absence of cache directives from the server, which is the case with the customer.

Example implementation: https://gist.github.com/cmurphy/4a0356b592c2aefeb354f02e10852b43

### Implementing only for nodeplan endpoint

If we don't want to rely on not-fully-defined caching behavior in browsers, we can implement this only for the endpoint the agent uses to get its configuration.

There is no literal `/nodeplan` endpoint, so what I presume this means is the `/v3/connect/config` endpoint, which is what the RKE1 agent uses to generate a node plan after a node is registered, which is what contains the rancher cert that the bug says were wrongly cached. This wouldn't apply to RKE2 nodes or imported clusters. If we go with this route, do we want to do the same for non-RKE "node plan" endpoints?

Example implementation: https://gist.github.com/cmurphy/31e6211e1a7eb78bcd5b95fe39032c81

### Possible regression/risks

If there are some browsers that are caching API responses, this would slow down response times for those users.

If there are users with intermediate caches that are finely tuned and working well, this could add latency to either browser requests or cluster-agent communication.

### Recommended directives

From [the Cache-Control header reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#preventing_storing) `no-store` supersedes other directives, so there is no need to also add `no-cache` or `no-transform` if we add `no-store`.

**Comment by cmurphy** [comment]
Issue: https://github.com/rancher/rancher/issues/35199

# Problem

In certain production environments there may be intermediate caches between the Rancher server and clients, including cluster agents. Caches configured to cache responses for the purpose of scalability and improved response time may inadvertently cache stale data which can disrupt deployment of downstream clusters.

# Solution

Most API responses, especially responses for the endpoint /v3/connect/*, now set response headers to include `Cache-Control: no-store` which directs intermediate caches not to cache the response.

# Testing

## Engineering Testing

### Manual Testing

Manually tested fetching data from various endpoints and checking that the Cache-Control headers were present in the responses.

### Automated Testing

None

## QA Testing Considerations

This wasn't implemented to fix a particular problem, so there are no reproduction steps. This was implemented just to mitigate a potential problem. Basic smoke testing and checking for the presence of the headers should be fine. More advanced testing might include setting up an intermediate cache like a squid proxy and checking that the cache correctly does not cache the responses from the Rancher server.

### Regressions Considerations

This is not likely to cause regressions.

**Comment by anupama2501** [comment]
Verified on v2.6-head 4199cac

- Created a rancher server with two custom clusters
- Ran pre-upgrade checks 
- Verified the following headers in the post calls:
<img width="300" alt="nocache" src="https://user-images.githubusercontent.com/38144301/172198548-ecfa4dee-257e-41a7-9e80-068832331ef4.png">

**Comment by samjustus** [comment]
@cmurphy this issue will need a release note, please
