### ISSUE TITLE
Rancher keeps resetting secrets created in 2.5.X after upgrade to 2.6.X

### ISSUE THREAD

**Issue by SGudbrandsson** [rancher/rancher#35207]
**Rancher Server Setup**
- Rancher version: 2.6.1
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: Let's encrypt

**Information about the Cluster**
- Kubernetes version: v1.17.17-eks-087e67
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS EKS

**Describe the bug**
After upgrading Rancher from 2.5.something to 2.6.0, some changes to secrets keep getting reset.

We change a password or a connection string inside a secret, then a few hours later the secret value is back to being the same it was before.

**To Reproduce**
1. Create a secret in 2.5.X user interface (the old one)
2. Upgrade the cluster to 2.6.X
3. Change the secret you made in 2.5.X
4. Wait a few hours
5. Look at the secret being reset

**Result**
The secret is the old value that you set before

**Expected Result**
The secret doesn't change

**Screenshots**
Constant secret reset after upgrade  
![image](https://user-images.githubusercontent.com/1608474/138070090-a6fbed6f-a306-4f3c-b458-b265e3dd8a01.png)

Secret that is OK and not being reset constantly
![image](https://user-images.githubusercontent.com/1608474/138070012-c0a49163-940e-4493-9d26-653314f7ddb6.png)

Secret that is being reset
![image](https://user-images.githubusercontent.com/1608474/138071984-b8f7030f-06c2-4916-aed1-2a4cfd7268bb.png)

**Additional context**
Looking at the logs, I can see that Rancher is constantly creating and updating the secrets again and again.
I believe it's storing the secrets somewhere else, then resetting them on a cron schedule or some other trigger

**Comment by rstoye** [comment]
We're currently facing the same issues and would love some official feedback on the matter. This is clearly unintended behavior and very risky in a production environment.

**Comment by wjbabicz** [comment]
Running into this myself .. Added a few keys to enable APM on a pod and they just disappear after an unknown amount of time on 2.6.0.

**Comment by junkiebev** [comment]
Have this problem on `2.5.9` - it is still present on `2.5.11`

**Comment by wjbabicz** [comment]
Worth noting: Removing the annotations does not prevent the secret from getting updated on 2.6.0. They get added back automatically.

**Comment by junkiebev** [comment]
Still happening on `2.5.12`

**Comment by junkiebev** [comment]
Adding Comment.

**Comment by ralfdonald** [comment]
Adding comment. Rancher still behaves that way.

**Comment by piyush94** [comment]
Upgraded from 2.5.12 to 2.6.6 and facing the same issue.

**Comment by cfahrni** [comment]
We're seeing the same behaviour in our 2.6.6 installation (Upgrade-Path: 2.5.11 => 2.6.4 => 2.6.6).

Workaround: Delete the secret in the local cluster to get it removed in the downstream cluster. Recreate the secret in the downstream-cluster and edit/delete it as usual.

**Comment by nymo** [comment]
+1 can confirm the same issue. Now currently on 2.6.5. Workaround with delete and recreate secret worked so far.

**Comment by junkiebev** [comment]
Believe this behavior is still exhibited on latest head

**Comment by nymo** [comment]
bump

**Comment by nymo** [comment]
Solution from @niranjan94 solved my issues.

**Comment by tengl** [comment]
We faced this issue as well, for the first time a couple of days ago. We are on 2.7.1 and updated a few weeks ago. The secret was probably created on 2.4 or 2.5, and probably hasn't been changed since. So far only one specific secret is affected, we've changed other (newer) secrets without issues.

**Comment by daniel-nov** [comment]
Still happening, v2.6.5. I'm starting to assume it's a feature and not a bug.

**Comment by serverbaboon** [comment]
For anyone coming across this while googling, its a legacy feature thing.

https://www.suse.com/support/kb/doc/?id=000020999

Deleting the All type secret in a project will delete all the copies of the secret in each namespace so copy it out 1st if you wish switch away from this legacy feature to the typical namespaced secrets. Then recreate the secret in each namespace.

I am guessing this is stored in the Local cluster which is why it also works.

**Comment by bratao** [comment]
Bump, this happening in v2.8.2!! 
Please @moio  help us!!!

**Comment by moio** [comment]
> Bump, this happening in v2.8.2!!
> Please @moio help us!!!

Hey @bratao, I appreciate your faith, unfortunately I know nothing about this condition - it's the first time I read about it I think.

If any of the affected users are SUSE customers I can suggest them to open a case with my Support colleagues, who might be more informed.

In the meantime I will try to contact people to see if anyone from the current engineering groups know anything about this issue, but unfortunately I cannot promise more than that.

Thanks for reporting

**Comment by moio** [comment]
JFYI: some colleague reported this could be due to a project secret that is getting replicated into the target cluster and namespace, overwriting secrets you might already have there.

https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-resources-setup/secrets#creating-secrets-in-projects

**Comment by Vashiru** [comment]
@moio Can confirm it's related to project based secrets.

Specifically I've created a "Registry" secret as project secret back in probably the 2.2 days of Rancher. Well that Gitlab token recently expired due to changes at Gitlab adding expiration dates to the Access tokens. I have repeatedly changed the Gitlab token affected in my Downstream cluster, only to have it reset a few hours later. Turns out that's because the actual secret I created was living in the upstream Local cluster.

For now I've manually edited my secret upstream and patched the downstream ones as I don't feel like properly fixing the pull secrets across all namespaces now.

But hopefully this information helps somebody.
