### ISSUE TITLE
Rancher 2.6.2 uses flannel:v0.13.0 which causes iptables segfault in RHEL 8.4

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#35245]
Need KDM release for flannel to address segfault.

Original 2.5 issue tracked in https://github.com/rancher/rancher/issues/34604.

SURE-3096

**Comment by Auston-Ivison-Suse** [comment]
**Reproduced this issue.** 

**My setup.** 
- Rancher version: v2.6.2
- Docker install


**Cluster Info**

- k8s version: v1.21.6-rancher1-1 and PNI enabled
- Cluster Type: Downstream, Custom
- Nodes:  3 ec2 instances with  AMI: rhel-8.4-docker-20.10.7-selinux-on-rpm
- Roles for nodes: 1 etcd, 1 worker, 1 control plane 

**Steps to reproduce**
1. Within the custom cluster deploy a workload in the default.
2. From explorer --> pods --> View the logs of pod with canal deployed on it in the namespace `kube-system`
3. You will see the following: 
` Failed to ensure iptables rules: Error checking rule existence: failed to check rule existence: running [/sbin/iptables -t filter -C FORWARD`
4. You will witness a segfault by running the command `dmesg` within the shell of the worker node.
For example ` segfault at 80 ip xxxxxx sp xxxxxxx  error 4 in libnftnl.so.11.2.0[7xxxxxxx]`
5. You can also check within the docker container by running `docker logs k8s_kube-flannel_canal-XXXX`
the output will contain the following : ` Failed to ensure iptables rules: Error checking rule existence: failed to check rule existence: running [/sbin/iptables -t filter -C FORWARD -s xxxxx/xx -j ACCEPT --wait]: exit status -1: `

**Validation Steps**
- Rancher version: v2.6-head(46eb9d4)
- Docker install

Cluster info
- custom cluster
- 3 nodes: 1 worker, 1 etcd, 1 control plane
- ec2 instances: rhel-8.4-docker-20.10.7-selinux-on-rpm
- k8s: v1.21.6-rancher1-2 (This is achieved, in part, by following the steps in the _Prerequisites_ section below. In the meantime use the latest version available to you)

**Prerequisites Before Testing**
1. Run the following command within all 3 of the nodes with the RHEL amis, _before_ attempting to provision the custom cluster.

`sudo systemctl disable nm-cloud-setup.service nm-cloud-setup.timer`

2. In your rancher setup: go to Global Settings --> scroll to rke-metadata-config and insert:

`"url": "https://releases.rancher.com/kontainer-driver-metadata/dev-v2.6-flannel-v0.15/data.json"`

3. Now edit the config of the cluster to upgrade it to k8s: v1.21.6-rancher1-2. 

**Validation Steps** 
1. Within the custom cluster deploy a workload in the default namespace.

2. From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.

3 . Change the container to kube-flannel, and run the `dmesg` command. 

**Result**
Within the output you will see something similar to:
`[18023.894669] ip6tables[187203]: segfault at 80 ip 00007f596bd35964 sp 00007ffe257c6fe8 error 4 in libnftnl.so.11.2.0[7f596bd30000+19000]
[18023.904630] Code: 83 c4 08 5b 5d 41 5c 41 5d c3 0f 1f 40 00 48 83 c4 08 31 c0 5b 5d 41 5c 41 5d c3 66 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <48> 8b 87 80 00 00 00 48 83 ef 80 48 39 f8 74 1b 85 f6 75 0c eb 18`

For the purpose of this ticket, flannel is absolved of being the root cause. The above segfault seems to be tied to libnftnl.so.11.2.0/iptables version. 

@aiyengar2 has very kindly outlined more information in his comment in the other issue. We have created another issue to remove any segfault entirely: https://github.com/rancher/rancher/issues/35709.
