### ISSUE TITLE
[Monitoring v2] Duplicate 'rules' key in rancher-monitoring 100.0.0+up16.6.0

### ISSUE THREAD

**Issue by christiangonre** [rancher/rancher#35264]
Hi all, there is a duplicate 'rules' key in the [clusterrole.yaml ](https://github.com/rancher/charts/blob/0e060071274ef7991559a0ef1bbe35ea27471da3/charts/rancher-monitoring/rancher-monitoring/100.0.0%2Bup16.6.0/templates/rancher-monitoring/clusterrole.yaml#L45)file. 
I checked and there is a PR with the fix, could you check it? If you need this PR in another branch I can do it again.

The PR is the following: https://github.com/rancher/charts/pull/1556

Thanks in advance for all!

**Comment by jiaqiluo** [comment]
Can be tested in the rancher-monitoring  `100.1.0+up19.0.3`
---
### Root cause
there is a duplicated 'rules' key in the clusterrole.yaml file.

### What was fixed, or what changes have occurred
remove the duplicated key 

### Areas or cases that should be tested? What areas could experience regressions? Are the repro steps accurate/minimal?
 
Please check [this commit](https://github.com/rancher/rancher/issues/34577#issuecomment-962151533) for the scope of tests.

**Comment by slickwarren** [comment]
tested with rancher v2.6-head (03ed782):
* no duplicate found for `rules` in [clusterrole.yaml](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/rancher-monitoring/100.1.0%2Bup19.0.3/templates/rancher-monitoring/clusterrole.yaml#L45) nor via deployment
