### ISSUE TITLE
About the bug of Monitoring unit

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#35331]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): Docker install/
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  v1.21.5
- Cluster Type (Local/Downstream): Custom
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

Units set through YAML cannot be displayed on the UI

**To Reproduce**
 
1. Enable monitoring
2. Create Prometheus Rule
3. Add Alerting Rules
4. Click Edit as YAML
5. Set `spec.groups.rules.for` to `10m`, like this:
![image](https://user-images.githubusercontent.com/19684717/139640420-f21ca1ba-d725-468a-b410-dac152c3a354.png)

6. Click Create
**Result**

After successfully creating the `Prometheus Rules`, check the config. The unit displayed by `Wait to fire for` is still `Seconds`.  Does not meet expectations.

![image](https://user-images.githubusercontent.com/19684717/139641584-7ef53cb0-a42e-4c86-a002-720414d3c194.png)

**Expected Result**

The unit of `Wait to fire for` should be displayed as `m`, or automatically converted to time in seconds. 

**Screenshots**

**Additional context**

**Comment by ronhorton** [comment]
**PASS** Verified fixed in `2.6-head Commit ID e7f03fd`

1. Provisioned downstream cluster
2. Installed monitoring
3. Created prometheus rule
4. Added Alert - Wait to fire for `10 Seconds`
5. Edited yaml for prometheus rule
6. Changed Wait to fire from 10 seconds to 10m
7. Saved
8. Checked Config in UI
9. `Minutes were correctly converted to seconds - ie, 10m = 600s`
<img width="614" alt="Screen Shot 2022-01-27 at 4 14 48 PM" src="https://user-images.githubusercontent.com/89212856/151446478-9ddf8dea-77f3-42cb-aa37-d78453eeeb4d.png">
<img width="910" alt="Screen Shot 2022-01-27 at 4 15 04 PM" src="https://user-images.githubusercontent.com/89212856/151446504-36c8d01c-d234-4e7f-847f-7bb75117a3d1.png">
