### ISSUE TITLE
cattle-node-cleanup jobs stick around forever

### ISSUE THREAD

**Issue by herrbpl** [rancher/rancher#35334]
**Rancher Server Setup**
- Rancher version: v2.6.1
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubernetes v1.17.4, RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.17.4
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom
**Describe the bug**
When cluster-autoscaler manages AWS SG-s and removes nodes, jobs prefixed with cattle-node-cleanup remain forever in cluster unless deleted manually, cluster is unable those jobs because underlying node is already terminated. Problem started with upgrade to Rancher 2.6.x from 2.5.5

**To Reproduce**
1. Add custom node (EC2 instance) to custom RKE1 cluster using registration information. 
2. Wait until node is fully operational
3. remove node by terminating in AWS console

**Result**
Node is gone but cleanup job sticks around. 
**Expected Result**
After a while, cluster should notice that node is gone and remove it. There should not be cleanup job sticking around because node is not ever coming back

**Screenshots**
![image](https://user-images.githubusercontent.com/2135514/139689239-c3f87dad-e98d-48a0-93ff-6d58d74af3ff.png)

**Additional context**
This probably also prevents cleanup of machine records, resources for machines stick around for days.
![image](https://user-images.githubusercontent.com/2135514/139689479-3113b64b-63b3-410e-98e5-932c980fb761.png)

**Comment by ebenezar-mccoy** [comment]
In my case, I was performing a series of tests

in one of them:
- I deleted the VM first - I needed to simulate recovery in a situation when VM was unrecoverable
- then I attempted to delete the node via cli and web - I did it several times
- most likely my attempts of deleting an unavailable node created several cattle-node-cleanup jobs, in my case they started one after another 
- after few manual deletions of cattle-node-cleanup* , the node got deleted from my cluster

**Comment by herrbpl** [comment]
On additional node, I think this might be issue related to clusters where windows nodes are in existance. 
Failing job and pod example
JOB:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2021-11-19T08:24:12Z"
  generateName: cattle-node-cleanup-
  labels:
    cattle.io/creator: norman
    cattle.io/node: m-03e513cd2ed2
  name: cattle-node-cleanup-xgs7c
  namespace: default
  resourceVersion: "332899406"
  selfLink: /apis/batch/v1/namespaces/default/jobs/cattle-node-cleanup-xgs7c
  uid: d7ca6aef-e7f8-4e75-a776-40c4f317e406
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: d7ca6aef-e7f8-4e75-a776-40c4f317e406
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: d7ca6aef-e7f8-4e75-a776-40c4f317e406
        job-name: cattle-node-cleanup-xgs7c
    spec:
      containers:
      - args:
        - --
        - agent
        - clean
        - job
        env:
        - name: AGENT_IMAGE
          value: rancher/rancher-agent:v2.6.1
        - name: PREFIX_PATH
        - name: WINDOWS_PREFIX_PATH
        image: rancher/rancher-agent:v2.6.1
        imagePullPolicy: IfNotPresent
        name: cattle-node-cleanup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-184-135.eu-central-1.compute.internal
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/unschedulable
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/unreachable
        operator: Exists
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: Socket
        name: docker
status:
  active: 1
  startTime: "2021-11-19T08:24:12Z"

```

POD:
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-19T08:30:08Z"
  generateName: cattle-node-cleanup-xgs7c-
  labels:
    controller-uid: d7ca6aef-e7f8-4e75-a776-40c4f317e406
    job-name: cattle-node-cleanup-xgs7c
  name: cattle-node-cleanup-xgs7c-fd2sj
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: cattle-node-cleanup-xgs7c
    uid: d7ca6aef-e7f8-4e75-a776-40c4f317e406
  resourceVersion: "332902781"
  selfLink: /api/v1/namespaces/default/pods/cattle-node-cleanup-xgs7c-fd2sj
  uid: c786999c-c42a-490f-86f0-f9441a296793
spec:
  containers:
  - args:
    - --
    - agent
    - clean
    - job
    env:
    - name: AGENT_IMAGE
      value: rancher/rancher-agent:v2.6.1
    - name: PREFIX_PATH
    - name: WINDOWS_PREFIX_PATH
    image: rancher/rancher-agent:v2.6.1
    imagePullPolicy: IfNotPresent
    name: cattle-node-cleanup
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wxv6r
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    kubernetes.io/hostname: ip-172-31-184-135.eu-central-1.compute.internal
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: Socket
    name: docker
  - name: default-token-wxv6r
    secret:
      defaultMode: 420
      secretName: default-token-wxv6r
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-11-19T08:30:08Z"
    message: '0/20 nodes are available: 20 node(s) didn''t match node selector.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
`

**Comment by Earsil** [comment]
Hi, 
I have a similar issue. I don't really remove vm/system that is running RKE cluster. It happens when I click delete button on a node in UI or by running kubectl delete. This triggers job cattle-node-cleanup creation, which cannot be finished, because it wants to be run on a node that is already out of Kube cluster. There is a node selector set on this jobs pod:
```Node-Selectors:  kubernetes.io/hostname=k8s-worker-syrwar``` and like I said it is already out of the cluster.

My Rancher version is 2.6.2.

**Comment by FredNass** [comment]
I had a similar situation with a node still referenced in Rancher's Cluster Management despite already being deleted from the kubernetes cluster (kubectl delete node/cluster-agent-76b5f799b5-vw6x6). To get rid of the deleting task, I edited the Machine resource and removed the "finalizers:" named "machine.cluster.x-k8s.io" (kubectl edit ma -n fleet-default cluster-agent-76b5f799b5-vw6x6). :-)

**Comment by pwurbs** [comment]
Hi,
I have a similar issue:
In my case, the creation of a pod for the cattle-node-cleanup job failed using Rancher 2.6.3.
`Error creating: pods "cattle-node-cleanup-8nx54-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]`
I use a more restrictive standard PSP in the cluster which prohibits the usage of a hostPath volume.
The job should use a specific service account to which the unrestricted PSP is bound.

**Comment by thedadams** [comment]
### Root cause
The issue was that if the cleanup job timed out, then Rancher was leaving the job on the downstream cluster and it would never get removed.

### What was fixed, or what changes have occurred
Now, when the cleanup job times out (after 30 seconds), Rancher will delete the job so that it doesn't stick around.

### Areas or cases that should be tested
1. Provision a custom RKE1 cluster.
2. Add node with all roles.
3. Add a worker-only node.
4. After the worker-only node is added to the cluster and is ready, delete the underlying VM (do not delete the node from Rancher).
5. Once the error "Kubelet stopped posting statuses" appears on the node in Rancher, then delete the node from Rancher.
6. On the downstream cluster, a job will be created with prefix `cattle-node-cleanup-`. With this fix, the job should be removed shortly after the node is removed from Rancher.

### What areas could experience regressions?
Deleting nodes from custom RKE1 clusters.

### Are the repro steps accurate/minimal?
Yes.

**Comment by bentastic27** [comment]
@thedadams I found that the job gets deleted, but the pod stayed in scheduling for me. I added an extra bit in this PR to delete the pods as well:

https://github.com/rancher/rancher/pull/36398

**Comment by thedadams** [comment]
@bentastic27 It does take an extra few minutes for the pod to be cleaned up after the job goes away. I think the limit is 5 minutes, and then the job will get cleaned up. I hope this is consistent with what you saw.

**Comment by bentastic27** [comment]
@thedadams Admittedly I didn't wait that long. I actually wrote that before I stumbled onto this thread due to a customer issue. In any case, I just tried it and I have an orphaned pod at 10 minutes. It looks to lost its owner reference, so I think the controller may treat it as a normal pod at this point. May be some oddity due to it being Pending and not Running/Completed/Whatever.

**Comment by bentastic27** [comment]
As an addition to that this comment indicates that if there is no ownerRef the pod won't get removed:

https://github.com/kubernetes/kubernetes/issues/71975#issuecomment-455180079

**Comment by thedadams** [comment]
Moving back to review to add Ben's changes.

**Comment by elixxx** [comment]
Does anybody have a workaround for Version 2.6.3-patch1?
I can not find the machines ressource.

**Comment by elixxx** [comment]
Okay, i already deleted all jobs one time but then I was thinking that rancher recreated them.
Now everything is clean.

One issue that wasn't mentioned.
We are naming nodes with their ip-address so it happened that after a new node comes up, it gets directly get cleaned.
If there was already a node with the same address, which happened in an address range of 256 addresses quit often.

What is happing there in detail? We explored some networking issues after the cleanup jobs run on new scaled-in servers.

**Comment by thedadams** [comment]
It's difficult to know exactly what is happening, but node names must be unique. So, if there is a node in Rancher (even if the node was already deleted) with the same name as the one being added, then the results are unpredictable.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 1d2b746
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: Custom Cluster

----------

### Testing: ###

Tested this issue with the following steps:

1. Provision a custom RKE1 cluster.
2. Add node with all roles.
3. Add a worker-only node.
4. After the worker-only node is added to the cluster and is ready, delete the underlying VM (do not delete the node from Rancher).
5. Once the error "Kubelet stopped posting statuses" appears on the node in Rancher, then delete the node from the RKE1 cluster. The best way to do this is kubectl delete node <NODE_NAME>. We really want to do this outside of Rancher because that is what causes the problem.
6. On the downstream cluster, a job will be created with prefix cattle-node-cleanup-. With this fix, the job should be removed shortly after the node is removed from Rancher.

**Result** - Pass

Upon removal of node, the job is removed as expected
