### ISSUE TITLE
Support for RKE2 provisioned cluster certificate rotation

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#35343]
Implement support to rotate certificates on RKE2 provisioned cluster, including an option to rotate certificates for individual service(s) (or all services).

Requires https://github.com/k3s-io/k3s/issues/2636 (and the same for RKE2 - https://github.com/rancher/rke2/issues/570)

**Comment by snasovich** [comment]
Unblocked as the changes are in December 2021 RKE2/k3s release.

**Comment by paynejacob** [comment]
### Root cause
new feature
  
### What was fixed, or what changes have occurred
provisioning v2 clusters now support certificate rotation.
  
### Areas or cases that should be tested
- rotating certs with all permutations of node configurations
- rotating certs on upgrade
- rotating specific service certs
  
### What areas could experience regressions?
- upgrades
  
### Are the repro steps accurate/minimal?
kubectl patch -n fleet-default --patch '{"spec":{"rkeConfig":{"rotateCertificates":{"caCertificates":true,"generation":1}}}}' --type=merge cluster/<cluster name>

kubectl patch -n fleet-default --patch '{"spec":{"rkeConfig":{"rotateCertificates":{"caCertificates":true,"generation":1, "services": [<service name here>]}}}}' --type=merge cluster/<cluster name>

**Comment by rancher-max** [comment]
This appears to just constantly rotate in a loop. My setup is just 3 nodes all roles:
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/55997940/156247274-8689f9f8-c4a5-4e9d-9418-20a72b0b2535.png">

v2.6-head `cf4364d`

Reopening for now and will gather more logs and post them when I have them. In this setup I was using DigitalOcean and it appears the server logs here are unavailable using `journalctl` for some reason:
```
root@maxrp1-maxrp1-49700a55-llzdg:~# journalctl -u rke2-server -f
No journal files were found.
```

**Comment by rancher-max** [comment]
I might've reopened this prematurely. After some time, this seems to have resolved itself and completed. Although there's something strange going on since according to the logs shown below it rotated on one node 5 times, another node once, and another node not at all.
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/55997940/156257814-5d61760a-ac51-4295-b669-287e9d96b3fd.png">

However, when I check how many times it actually rotated, it appears to have done the node from those logs 5 times and both other nodes once:
```
# mk6ff
root@maxrp1-maxrp1-49700a55-llzdg:~# ls /var/lib/rancher/rke2/server/ | grep tls | wc -l
6

# qmqd7
root@maxrp1-maxrp1-49700a55-b724x:~# ls /var/lib/rancher/rke2/server/ | grep tls | wc -l
2

# vg8dg
root@maxrp1-maxrp1-49700a55-296zw:~# ls /var/lib/rancher/rke2/server/ | grep tls | wc -l
2
```

FWIW, the timestamp on vg8dg associated with that in the logs matches:
```
# Timestamp shown at end of the tls-* record
root@maxrp1-maxrp1-49700a55-296zw:~# ls /var/lib/rancher/rke2/server/ | grep tls
tls
tls-1646168074

# Retrieving timestamp value using python, which gives the exact same time as in the logs
print(datetime.fromtimestamp(timestamp).strftime("%m/%d/%Y, %H:%M:%S"))
03/01/2022, 13:54:34
```

Doing the same as the above calculation, there should've been a provisioning log at approx. 1:53:03 pm for `qmqd7`, but there wasn't. Instead at 1:53:04 there was the 5th one for `mk6ff`.

Before I debug further into the actual nuts and bolts of this feature (functionality itself actually working) I think we need at least two things here:
1. Provisioning Log to match what is happening on the correct node
2. Rotation to only happen once per node

**Comment by paynejacob** [comment]
@rancher-max how were your node pools configured? Specifically how many nodes per pool and what roles?

**Comment by rancher-max** [comment]
just one node pool with 3 nodes all roles

**Comment by rancher-max** [comment]
It also seems that the rotation itself isn't functioning properly. I used a new setup with 3 nodes all roles again:
```
$ sudo diff -sr /var/lib/rancher/rke2/server/tls/ /var/lib/rancher/rke2/server/tls-1646249776/ | grep -i identical | awk '{print $2}' | xargs basename -a | awk 'BEGIN{print "Identical Files:  "}; {print $1}'
Identical Files:  
client-admin.crt
client-admin.key
client-auth-proxy.crt
client-auth-proxy.key
client-ca.crt
client-ca.key
client-controller.crt
client-controller.key
client-kube-apiserver.crt
client-kube-apiserver.key
client-kube-proxy.crt
client-kube-proxy.key
client-kubelet.key
client-rke2-cloud-controller.crt
client-rke2-cloud-controller.key
client-rke2-controller.crt
client-rke2-controller.key
client-scheduler.crt
client-scheduler.key
dynamic-cert.json
peer-ca.crt
peer-ca.key
server-ca.crt
server-ca.key
kube-controller-manager.crt
kube-controller-manager.key
kube-scheduler.crt
kube-scheduler.key
request-header-ca.crt
request-header-ca.key
server-ca.crt
server-ca.key
service.key
serving-kube-apiserver.crt
serving-kube-apiserver.key
serving-kubelet.key
```

I would expect the output to show:
```
Identical Files:  
client-ca.crt
client-ca.key
dynamic-cert.json
peer-ca.crt
peer-ca.key
server-ca.crt
server-ca.key
request-header-ca.crt
request-header-ca.key
server-ca.crt
server-ca.key
service.key
```

And similarly when doing the rotation on just one service, I would expect the output to have identical files for everything except that service.

**Comment by rancher-max** [comment]
The original reopening issues have been resolved of:
```
1. Provisioning Log should match what is happening on the correct node
2. Rotation should only happen once per node
```

Reopening again because it appears the rotation itself isn't happening. Issue noted in the above comment: https://github.com/rancher/rancher/issues/35343#issuecomment-1057354804. This is the case on all 3 nodes (still using 3 nodes all roles for the setup). Validated using v2.6-head commit `572ab58`

**Comment by rancher-max** [comment]
Moved this back to the working column as it was determined the above is a UI issue and it appears certs are rotating correctly. Just need to finish validating all possible options.

**Comment by rancher-max** [comment]
Validated can rotate all services individually as well as all together. Rotating all together requires passing an empty array, whereas rotating an individual service requires selecting that service. List of services: `admin, api-server, controller-manager, scheduler, rke2-controller, rke2-server, cloud-controller, etcd, auth-proxy, kubelet, kube-proxy`.

Also confirmed that multiple services can be passed in the array when doing it via Edit Yaml or directly through the API, although the UI will force only a single service selection (which I believe is acceptable).

Did this all on the same configuration as above and the same v2.6-head commit.

Still need to validate using split roles on nodes, but this is something that wasn't validated in rke2 standalone so I need to do that first to get expectations and potential current limitations of the feature from rke2's side.

**Comment by rancher-max** [comment]
Confirmed this is successful even on split roles using rancher v2.6-head commitid `3b2677f`. 

Rotating on worker-only nodes isn't really supported (see https://github.com/rancher/rke2/issues/2623) but rotating on a control-plane node does correctly rotate the worker certs that are being used.

The general way this works for other split-role nodes is:
- etcd nodes rotate etcd cert
- CP nodes rotate certs associated with CP (apiserver, scheduler, etc.)
