### ISSUE TITLE
v2.6.3 - Tracking issue for K3s k8s November Patches

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35370]
This is the tracking issue for the K3s November k8s Patches. We should be checking/validating the following versions:

- v1.22.4
- 1.21.7
- v1.20.13

**Comment by rancher-max** [comment]
There are net-new server args that will need to be addressed by the rancher UI at some point in these releases for 1.21 and 1.22 (provisioning cases). See https://github.com/rancher/kontainer-driver-metadata/pull/732 for what has been added.

**Comment by rancher-max** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/738

**Comment by rancher-max** [comment]
Using rancher v2.6.3-rc2, I've validated upgrading an imported cluster to all of the listed versions is successful. Those versions show in the UI along with the additional 1.21 versions (which has been called out previously in https://github.com/rancher/kontainer-driver-metadata/pull/707#pullrequestreview-793418577).

Provisioning correctly only shows v1.21.7+k3s1 and v1.22.4+k3s1:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/55997940/144150578-e86ae251-2ec6-4755-9a94-6a15916ef5db.png">
and provisioning v1.21.7+k3s1 is successful. v1.22.4+k3s1 fails due to https://github.com/rancher/rancher/issues/35683. I am going to close this as validated as the other issue will be sufficient to cover the rest of the provisioning case for 1.22 and KDM seems to be successful.
