### ISSUE TITLE
[Monitoring v2] Wrong permissions in the PSP for Grafana

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#35390]
**Rancher Server Setup**
- Rancher version: 2.6.x
- Installation option (Docker install/Helm Chart): Helm Chart 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:
 
**Describe the bug**

rancher-monitoring 100.0.0+up16.6.0 fails to install when passing the value `grafana.persistence.enabled=true` since its PSP set `runAsUser=MustRunAsNonRoot` but the grafana deployment wants to run the init pod as `root`.

**To Reproduce**
 
install rancher-monitoring 100.0.0+up16.6.0 with the value `grafana.persistence.enabled=true` 

**Result**
grafana pod will fail to run up with the error 
```
pods "rancher-monitoring-grafana-7f54b7d8bc-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot: Invalid value: false: must be true]:Deployment does not have minimum availability.
```

**Expected Result**

the installation should succeed 

**Screenshots**

<img width="1853" alt="Screen Shot 2021-11-05 at 12 40 55 PM" src="https://user-images.githubusercontent.com/6218999/140570187-85b47f32-d5ea-4fc3-b7c4-d81a34a509fa.png">

**Comment by Martin-Weiss** [comment]
With initChownData: false this should not be a problem I believe… so maybe the helm chart needs to create the PSP different based on this setting?

**Comment by Tejeev** [comment]
Could this be a result of https://github.com/grafana/helm-charts/issues/752?

**Comment by jiaqiluo** [comment]
@Tejeev Yep, it is the same bug. The fix is in the next release of rancher monitoring.

**Comment by jiaqiluo** [comment]
Can be tested in the rancher-monitoring  `100.1.0+up19.0.3`
---
### Root cause
rancher-monitoring `100.0.0+up16.6.0 `fails to install when passing the value `grafana.persistence.enabled=true` since its PSP set `runAsUser=MustRunAsNonRoot` but the grafana deployment wants to run the init pod as `root`.

### What was fixed, or what changes have occurred
correct the permission in the PSP file 

### Areas or cases that should be tested? What areas could experience regressions? Are the repro steps accurate/minimal?
 
Please check [this commit](https://github.com/rancher/rancher/issues/34577#issuecomment-962151533) for the scope of tests.

**Comment by MbolotSuse** [comment]
| Image Name | Image Tag | Image Digest |
|------------|-----------|--------------|
| rancher/rancher | v2.6.2 | 51658639bf2b28f4796e7daa04b0434e29fcf69ce062bf649462be77ae76cd2c |
| rancher/rancher | v2.6-head | 49e9e6f39477971969399ea925951536986d7d09699d70d9a127db16eec33712 |

Issue was verfied to exist in `2.6.2` (rancher version) / `v100.0.0+up16.6.0` (chart version) through the following steps:

- Deploy hardened cluster
- Run rancher:v2.6.2 through docker (on separate host)
- Import hardened cluster into rancher
- Deploy CIS benchmark on the hardened-cluster through `Cluster Tools`
- Validate the cluster is hardened (i.e no fails) using CIS benchmark scan profile `rke-profile-hardened-1.6` (warnings should not fail the scan)
- Deploy Monitoring `v100.0.0+up16.6.0` through `Cluster Tools`. Grafana storage should be enabled through `Edit Options` -> `Grafana` -> `Grafana Storage` -> `Enable with PVC template`
- Validate that the `rancher-monitoring-grafana` deployment failed (in `cattle-monitoring-system` namespace) due to the PodSecurityPolicy

Issue was verfied to be fixed (i.e. test passed) in `2.6-head` (rancher version) / `v100.1.0+up19.0.3` through the following steps:

- Deploy hardened cluster
- Run rancher:v2.6-head through docker (on separate host)
- Import hardened cluster into rancher
- Deploy CIS benchmark on the hardened-cluster through `Cluster Tools`
- Validate the cluster is hardened (i.e. no fails) using CIS benchmark scan profile `rke-profile-hardened-1.6` (warnings should not fail the scan)
- Enable the local storage class for the cluster
- Deploy a PV of size 20Gi to the cluster
- Deploy Monitoring `v100.1.0+up19.0.3` through `Cluster Tools`. Grafana storage should be enabled through `Edit Options` -> `Grafana` -> `Grafana Storage` -> `Enable with PVC template`. PVC size should be 15Gi and use the storage class created a few steps earlier. In addition, `grafana.initChownData.enabled` should be set to false
- Validate that the `rancher-monitoring-grafana` deployment succeeded (in the `cattle-monitoring-system` namespace)
- Validate that the Grafana UI can be access through `hardened-cluster` -> `monitoring`.


Some notes:

- I had to disable the init container for Grafana to get this to work on the upgraded version `grafana.initChownData.enabled=false`
- No PV was provisioned when validating that the issue occured on `2.6.2`/`v100.0.0+up16.6.0`
- The end deployment (which worked) was a bit unstable, and had to be deployed a couple of times before it took hold (I don't believe this to be related to the changes - moreso to how the PV was created/used).

**Comment by MbolotSuse** [comment]
Post fix Dev-Validate

| Image Name | Image Tag | Image Digest |
|--------------|-----------|--------------|
| rancher/rancher | v2.6.3-rc5 | a8ebbe326619f99644d3784311b431b74feefbd0a769e61bdff9c889b29988e0 |

Validation Steps:

- Deploy hardened cluster
- Run rancher/rancher:v2.6.3-rc5 (on a separate machine)
- Import hardened cluster into ranchar
- Install CIS benchmark v2.0.2 from Cluster Tools (in the downstream cluster)
- Install longhorn v100.1.0+up1.2.2 from Cluster Tools (in the downstream cluster)
- Run a scan (in the downstream cluster) using the profile `rke-profile-hardened-1.6`. Warnings should not cause a failure. Validate that the scan passed.
- Install Monitoring v100.1.0+up19.0.3 from Cluster Tools (in the downstream cluster). Enable Grafana Persistence using Edit Options -> Grafana -> Grafana Storage -> Enabled with PVC Template. Set size to 15Gi, Storage Class Name to longhorn, and Access Mode to ReadWriteOnce.
- Using kubectl, validate that the pod prefixed by `rancher-monitoring-grafana` is running using `kubectl get pods --all-namespaces | grep "rancher-monitoring-grafana"`
- Validate that the grafana UI can be reached and is functioning by going to Monitoring -> Grafana in the rancher UI.
- Validate that the newest version of the chart was published by running `kubectl describe psp rancher-monitoring-grafana -n cattle-monitoring-system` and reviewing the output to ensure that it includes specifically enumerated Required Drop Capabilities (including DAC_OVERRIDE).

Validation Status: Pass
@sowmyav27 This now passes after the fix (without `grafana.initChownData.enabled=false`)
