### ISSUE TITLE
[KEv2] Cluster owners should be able to change cloud credential

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#35413]
**Describe the bug**

Currently, a cluster owner of a KEv2 cluster can only change the cloud credential if they have access to the one currently on the cluster AND have access to the one they are trying to change it to.

**To Reproduce**
 
1. As an admin, create an EKS/GKE/AKS cluster
2. Create a standard user
3. Assign the standard user as a cluster owner of the EKS/GKE/AKS cluster
4. Logout as admin and login as the standard user.
5. Edit the cluster and try to change the cloud credential (you may have to create a cloud credential for the standard user).

**Result**
The standard user is not allowed to change the cloud credential.

**Expected Result**

The standard user should be able to do this.

**Comment by thedadams** [comment]
Related UI issue: https://github.com/rancher/dashboard/issues/4529

**Comment by brudnak** [comment]
## Reproduction Environment


| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.2                                  |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | AWS EKS                                 |
| Downstream K8s version  | 1.21                                    |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)  |
| Cloud Credentials       | AWS Access Token Setup Prior to Steps   |

![01-repro-env](https://user-images.githubusercontent.com/40877149/143289935-8a860524-741d-4199-9753-1a0e0e4f0432.png)

## Reproduction steps

1. Starting from the **default** Rancher homepage `/dashboard/home` & logged in as the default `Admin` user

>Create an EKS cluster

2. Click `hamburger menu` -> click `Create`
3. Click `Amazon EKS`
4. Fill out the form for `Amazon EKS` cluster creation
    1. Cluster Name: `abrudna-qa-eks`
    2. Click `Next: Configure Cluster`
    3. Click `Next: Configure Network`
    4. Select `Custom: Choose from your existing VPC and Subnets`
    5. Click `Next: Select Security Group`
    6. Select desired security group
    7. Node Group Name: `abrudna-qa-node-g`
    8. Click `Create` -> you are then redirected back to the `Clusters` page
    9. Wait for the newly created AWS EKS cluster to have an `Active` state

>Create a standard user

5. Click `hamburger menu` -> click `Users & Authentication` -> click `Create`
6. Fill out the user creation form
    - Username: `user1`
    - Password: create a password
    - Leave default values
    - `Global Permissions` should be `Standard User`
    - Click `Create`

>Assign the standard user as a cluster owner of the EKS/GKE/AKS cluster

7. Click `hamburger menu` -> under `EXPLORE CLUSTER` click the EKS cluster `abrudna-qa-eks`
8. From the left side menu click `RBAC`
9. Click `Add`
10. Search for `user1` -> add that user as an `Owner`
11. Click `Create`

>Logout as admin and login as the standard user.

12. Click the user icon at the top right -> click `Logo Out`
13. Now login as `user1`

>Edit the cluster and try to change the cloud credential (you may have to create a cloud credential for the standard user).

15. Starting from the default Rancher homepage `/dashboard/home` as standard `user1` 
16. Click `hamburger menu` -> click `Cluster Management` -> click `ellipsis (three dots)` next to the EKS cluster
17. Click `Edit Config`

**RESULT**

Unable to proceed with editing the cluster because the cloud credential is not populated

**WORKAROUND**

Create a new cloud credential as this standard user `user1`

## Additional Info

 This backend issue [https://github.com/rancher/rancher/issues/35413](https://github.com/rancher/rancher/issues/35413) was set `To Test` for 2.6.3

 However, the UI portion has been moved to 2.6.4 it looks like [https://github.com/rancher/dashboard/issues/4529](https://github.com/rancher/dashboard/issues/4529)

 CC: @gaktive  @sowmyav27

**Comment by thedadams** [comment]
This can be tested before the UI is in. I have simple work-around steps. If this gets tested before the UI is in, please reach out to me and I can share the work-around steps.

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-b7d78a8c65261076bb7ebfbe8d38fc07ebdd7897-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | Amazon EKS                                         |
| Downstream K8s version  | 1.21                                               |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)             |

## Validation steps

1. Starting from the Rancher **default** homepage `/dashboard/home`
2. Create an Amazon EKS downstream cluster as the default admin user
    - click `hamburger menu` -> click `Cluster Management` -> click `Create` -> click `Amazon EKS` -> fill out the form to create an `Amazon EKS` cluster
    - NOTE: cloud credential setup prior to these steps
    - Cluster Name: `provide a cluster name`
    - Region: `us-east-2`
    - Cloud Credentials: `aws-creds` (setup before steps)
    - Click `Next: Configure Cluster` -> leave defaults
    - Click `Next: Configure Network` -> make network selections
    - Click `Next: Select Security Group` -> make security group selections
    - Node Group Name: `enter some name here`
    - Click `Create` -> to create the EKS cluster and be redirected back to the `Clusters` page -> wait for the cluster to become active
3. Create a standard user
    - click `hamburger menu` -> click `Users & Authentication` -> click `Create` -> fill out the form to create a standard user
    - Username: `user1`
    - Password: `enter a password here`
    - Global Permissions: `Standard User`
    - Click `Create`
4. Add the standard user: `user1` as an owner of the EKS cluster
    - click `hamburger menu` -> click the EKS cluster -> click `RBAC` -> under `Cluster Members` -> click `Add`
    - Search for `user1` -> select `user1`
    - Select the radio button for `Owner` under `Cluster Permissions`
    - Click `Create`
5. Log out as admin, and then log back in as `user1`
6. Click `hamburger menu` -> click `Cluster Management` -> click the `ellipsis (three dots)` next to the EKS cluster -> click `Edit Config`
7. Right click on the disabled `Next: Configure Cluster` button, select `inspect` -> delete the `disabled` from the html button tag -> hit enter -> close the dev tools window
8. Click `Next: Configure Cluster` -> update the instance type from `t3.xlarge` to `t3.large` -> click `Save`
9. Cluster successfully updates
