### ISSUE TITLE
Rancher server logs error syncing machine-worker-label on imported harvester 0.3.0 cluster

### ISSUE THREAD

**Issue by SweBarre** [rancher/rancher#35440]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): docker install
- Proxy/Cert Details: self signed

**Information about the Cluster**
- Kubernetes version: v1.21.5+rke2r1
- Cluster Type (Local/Downstream): Downstream, harvester v0.3.0
 
**Describe the bug**
The rancher server repeatedly logs the following when importing a newly imported harvester v0.3.0 cluster
```
2021/11/10 08:40:57 [ERROR] error syncing 'node2': handler machine-worker-label: machines.cluster.x-k8s.io "custom-9cebcaf1ae85" not found, requeuing
2021/11/10 08:41:08 [ERROR] error syncing 'node1': handler machine-worker-label: machines.cluster.x-k8s.io "custom-e0a3c84cc108" not found, requeuing
2021/11/10 08:41:17 [ERROR] error syncing 'node3': handler machine-worker-label: machines.cluster.x-k8s.io "custom-752a28e09de7" not found, requeuing
```

**To Reproduce**
Import a harvester v0.3.0 cluster into rancher server

**Additional context**
Rancher server stopped logging the error when labeling the harvester nodes as worker nodes with:
`kubectl label node <nodename> node-role.kubernetes.io/worker=true`

**Comment by snasovich** [comment]
The issue is in https://github.com/rancher/rancher/blame/6ae91f6ea7dee6f54e49291313ac8bb3c7937900/pkg/controllers/managementuser/machinerole/machinerole.go controller. Need to add some checks to run/not run this controller depending on cluster type (possibly not start the controller for Harvester clusters?). Need to see how Harvester clusters are showing up in UI to ensure https://github.com/rancher/rancher/issues/33385 is not applicable here.
@slickwarren has a setup to test.

**Comment by erSitzt** [comment]
Same errors here with Rancher 2.6.3 and Harvester 1.0.0
```
 [ERROR] error syncing 'harvester-test-1': handler machine-worker-label: machines.cluster.x-k8s.io "custom-5345e8d0fea8" not found, requeuing
```

**Comment by thedadams** [comment]
### Root cause
The `machine-worker-label` controller was not checking for a CAPI machine for these custom nodes.

### What was fixed, or what changes have occurred
This area was refactored and now Rancher does not look for a machine, but a secret. If Rancher does not find this secret then no error is produced.

### Areas or cases that should be tested
1. The scenario that produced this issue should be tested.
2. In addition, provisioning an RKE2/K3S cluster with a worker-only node should be tested to ensure the label `node-role.kubernetes.io/worker=true` is put on the downstream node.

### What areas could experience regressions?
Number 2 above could experience a regression.

### Are the repro steps accurate/minimal?
Yes.

**Comment by sowmyav27** [comment]
@slickwarren Please validate this usecase
- In addition, provisioning an RKE2/K3S cluster with a worker-only node should be tested to ensure the label node-role.kubernetes.io/worker=true is put on the downstream node.

@noahgildersleeve Please validate
- The scenario that produced this issue should be tested.

**Comment by slickwarren** [comment]
using rancher v2.6.4-rc1:
* worker-only node(s) have the label `node-role.kubernetes.io/worker=true` (harvester node driver, k8s 1.21.9+rke2r1)
* add a new harvester setup by importing it through `virtualization management`  -- no error for `syncing machine-worker-label` found in rancher server logs
#35440
upgrade case: 
* rancher 2.6.3 with 1 registered harvester setup -- still has the `error syncing...` in logs
* upgrade rancher to 2.6.4-rc1
* error does not persist
