### ISSUE TITLE
Create Namespace button is missing for cluster members and project owners/members when they are added to a newly created project

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35453]
**Setup**

Rancher version: 2.6-head  ea7823e 
Browser type & version: Chrome

**Describe the bug**
Created a new project and added local/auth users as project Owners/members. When logged in as the respective project owners/members, the `Create namespace` button is missing. 
It appears if we create a namespace as an admin in the newly created project

**To Reproduce**
1. Create a downstream cluster rke1/rke2 1 etcd,1 cp ,1 worker
2. Create a local user with standard permissions - user1
3. As an admin, create a project P1 in the downstream cluster - P1
4. Add user1 to P1 as a project owner
5. Login as user1

**Result**
Create namespace button is missing on the project. 

**Expected Result**
Expected the `create namespace` button to be present for the project for a Project owner/Project member.

**Screenshots**
When logged in as a project Owner - user1:
<img width="600" alt="Screen Shot 2021-11-04 at 1 30 54 PM" src="https://user-images.githubusercontent.com/38144301/140415466-3194e28a-a6d0-4f5b-b8f7-ce9bbcd7a8fa.png">

When same user - user1 is added as as Project owner in default project

<img width="600" alt="Screen Shot 2021-11-04 at 12 53 22 PM" src="https://user-images.githubusercontent.com/38144301/140415572-5ac73a17-fa56-4acb-ab93-d35f2bf91da1.png">

**Additional context**
Happens for Cluster members as well.
If we add a user as cluster member in any of the clusters dowsntream/local, members can create project but the `Create namespace` button is missin.

**Two workarounds:**

1. In a browser, as an admin add user1 to default project as project member/owner. refresh the URL logged in as user1 in a different browser, we see the namespace button appear along with a duplicate project P1.
2. As an admin, add a namespace in the project P1. If we login as user1, we see the create namespace button appear and thereby the workloads tab.

Possibly related:
https://github.com/rancher/dashboard/issues/4455

**Comment by MbolotSuse** [comment]
@gaktive I took a look into this on the UI side. Relevant code (that I think you were referring to) is here: https://github.com/rancher/dashboard/blob/db6bca553e54d7dac2b8cc593e79e176581dbfc5/pages/c/_cluster/_product/projectsnamespaces.vue#L50

I think I understand the original intention of the UI side of this code. That being said, I think there is a large flaw to this approach, namely that the button's presence is tied (in best case) to the user's ability to create namespaces generically. This leads to the button being present on every project that the user sees, or on no projects. I'm not sure that this is the desired behavior. It seems to me that it would be better to evaluate if the button should be present on a project-by-project basis. That being said, the way that you are determining permissions right now (through the schema) doesn't really seem to support this. I'm going to look more into the backend side and see if there's something that makes more sense there.

**Comment by gaktive** [comment]
cc @nwmac, we may have to look at the design around this button pending what is found here.

**Comment by samjustus** [comment]
SURE-4040

**Comment by MbolotSuse** [comment]
@gaktive 

I think I've got this one finally figured out, sorry that it took so long. When Steve checks for access permissions to create today, it looks for the "POST" ability contained in the "CollectionMethods" field of the schema. You can see that here: https://github.com/rancher/apiserver/blob/master/pkg/server/access.go#L17-L22 . The UI, on the other hand, is currently checking if the user has "PUT" access to "ResourceMethods". This checks if the user has update access to a namespace, rather than create permissions to namespaces. Because the project in this issue is initially empty, the backend does not report that the user has "PUT" access to "ResourceMethods" (because there exists no namespaces that the user has access to modify). Once a namespace has been created, however, the user now has update/edit access to a namespace, which causes the button to appear on the UI.

The solution here is pretty simple. https://github.com/rancher/dashboard/blob/db6bca553e54d7dac2b8cc593e79e176581dbfc5/pages/c/_cluster/_product/projectsnamespaces.vue#L51 should be changed from:

```
return (this.schema?.resourceMethods || []).includes('PUT');
```

to 

```
return (this.schema?.collectionMethods || []).includes('POST');
```

I ran a quick test on my local using this as the override, and was able to get the button to show up as expected (doesn't show up when the user is read-only, does when the user is project member).

As far as my earlier comment goes, the backend logic doesn't support the structure that I was referring to there. That may be a topic that we revisit in the future, but for now I would recommend going wiht the above fix.

**Comment by samjustus** [comment]
@gaktive based on Mikes comment, I am going to assign the 3 or 4 related jira issues to your team as they should all be resolved by the solution he outlined above.

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/5322 should address the UI side of things.

**Comment by gaktive** [comment]
@samjustus UI does have a fix for this with https://github.com/rancher/dashboard/issues/5322, which QA verified and @nwmac confirmed. This will be in 2.6.5 so this can go back to QA for additional validation as needed. The Jira items are updated.

**Comment by anupama2501** [comment]
Verified efa312e 2.6-head

- Create a downstream cluster rke1/rke2 1 etcd,1 cp ,1 worker
- Create a local user with standard permissions - user1
- As an admin, create a project P1 in the downstream cluster - P1,P2
- Add user1 to P1 as a project owner and P2 and project member
- Login as user1
- Verified user1 can create namespaces as a project member/owner in the respective projects
