### ISSUE TITLE
Scale Node Pool Up or Down for RKE2 provisioned clusters is not working for long cluster/node pool names

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#35452]
**Setup**
- Rancher version: v2.6-head (052336574a21bf5675af9dc80632c69215a9715d)
- Browser type & version: Chrome (94.0.4606.81)

**Describe the bug**
"+" and "-" buttons do nothing on node pools of RKE2-provisioned clusters.

**To Reproduce**
1. Navigate to RKE2-provisioned cluster in Cluster Manager with long name used for cluster and node pool (see examples on screenshots below and in the comments).
2. For any node pool, click "+" or "-" buttons to attempt to scale up/down the number of nodes in the pool.

**Result**
Nothing happens, no new nodes are provisioned or existing ones removed. Looking at "Network" tab confirms there is no request going to backend.

**Expected Result**
Node pool is scaled up/down accordingly.

**Screenshots**
![image](https://user-images.githubusercontent.com/85187633/138778268-b266bcb4-e7bd-4f57-909e-b6dd073b762c.png)

**Comment by thedadams** [comment]
This is going to have to be solved with a team effort. The backend cannot change the naming. Kubernetes [has a strict length maximum](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md#identifiers-and-names-in-kubernetes) for names. Therefore, we have to do what we are doing (truncating the name and adding 5 random characters at the end).

Instead of looking at just the name of the MachineDeployment and matching it to the machinePool, the UI will have to do the following:
- The MachineDeployment will have an `infrastructureRef` that points to a MachineTemplate
- That MachineTemplate will be cloned from a Config (*)
- The Config will be referenced by a machineConfigRef from the cluster object's `spec.rkeConfig.machinePools`

So the identification of MachineDeployment to machinePool will be more complicated, but I don't really see a way around that at this point.

(*) This is currently not possible because the backend does not identify which Config a MachineTemplate is cloned form. This is the part that will need to be adjusted by the backend.

**Comment by snasovich** [comment]
@thedadams , thank you for detailed explanation and plan of action. Moving it to 2.6.4 as it only happens if longer names are used and we're close to 2.6.3 dev code freeze time.

**Comment by snasovich** [comment]
There may need to be UI change for this, to be confirmed as part of the implementation.

**Comment by sgapanovich** [comment]
Backend changes seems to be working as expected. There is an issue with UI not working with some node drivers. Will keep the issue in the "QA Working" column until the UI issue is fixed. See comments https://github.com/rancher/dashboard/issues/4990#issuecomment-1043656690

**Comment by sgapanovich** [comment]
The UI issue is still in the reopened status but I see now that the backend issue can be passed since I was able to provision and scale up/down node pools for different RKE2 node driver clusters. (the UI issue got more comments  https://github.com/rancher/dashboard/issues/4990#issuecomment-1049035700)

--------------

### Test Environment: ###
Rancher version: rancher_version
Rancher cluster type: single-node docker install / HA
Docker version: 20.10

Downstream cluster type: rke2 node driver clusters

----------

### Testing: ###

1. provision different node driver RKE2 clusters 
2. get machine templates for those clusters (apiversion: rke-machine.cattle.io/v1)
3. each template will have new annotations added: 
  ```
    rke.cattle.io/cloned-from-group-version: 
    rke.cattle.io/cloned-from-kind: 
    rke.cattle.io/cloned-from-name: 
  ```

`rke.cattle.io/cloned-from-kind` is machineConfigRef type from the cluster yaml file 
`rke.cattle.io/cloned-from-name:` is machineConfigRef name from the cluster yaml file 

![amazonec2](https://user-images.githubusercontent.com/40282141/155389755-28e2d45b-52e0-4fe6-bcb6-bfe2fbfaa58e.jpg)

UI will be looking for that `rke.cattle.io/cloned-from-name` value in the template and then working with the pool which `machineConfigRef.name` is the same as the value in template

whole picture/logic 
![154591766-e402b2eb-a7c9-4fbb-bf17-30f578c8f2ed](https://user-images.githubusercontent.com/40282141/155389885-df7725ee-b246-45a7-964e-d82bf5cee700.jpeg)



linode and do examples 
![154591807-a155f4eb-4dc2-4282-88ef-fd8efb89f2cb](https://user-images.githubusercontent.com/40282141/155389913-c1c9605f-ed3e-4bf7-b5f9-360715c5a066.jpeg)


I can deploy different rke2 node driver clusters
I can scale pool up/down
I can delete the cluster

**Comment by sgapanovich** [comment]
Upgrade testing 
2.6.3 -> 2.6-head 8c785a1

1. Create Rancher server (HA) 2.6.3
2. Deploy DO RKE2 node driver cluster 
3. Copy `digitaloceanmachinetemplates.rke-machine.cattle.io` resource for one of the node pools 
4. Upgrade Rancher to 2.6-head
5. Notice that `digitaloceanmachinetemplates.rke-machine.cattle.io` got updated with 3 new annotations (see above)

2.6.3 template            vs             2.6-head template 
![machines diff](https://user-images.githubusercontent.com/40282141/155431859-20d7e415-0c1e-4a64-b3d8-c7e486ac4fee.jpg)
- scale node pools up/down and verify that nodes are created/deleted

the following issue created while testing the upgrade path https://github.com/rancher/rancher/issues/36627
