### ISSUE TITLE
Chart loading takes 1 minute in the airgap setup

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#35553]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.6+rke2r1
- Cluster Type (Local/Downstream):  Custom
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

Enter any chart page, it takes at least 1 minute to load successfully

**To Reproduce**
 
1. Navigate to EXPLORE CLUSTER -> Apps&Marketplace -> Charts
2. Click any chart

**Result**
It takes about a minute to load out the detailed information of the chart

**Expected Result**

**Screenshots**

![image](https://user-images.githubusercontent.com/19684717/142129239-e3d3a338-417d-4c05-956e-eb4be7fc3df7.png)

**Additional context**

**Comment by niusmallnan** [comment]
@kingsd041 v2.6.3 works fine for me. Could you please check this again?

**Comment by niusmallnan** [comment]
Wow, got a way to reproduce. This issue can be only seen in the airgap setup.

Since Icon files are loaded in batches on the chart list page, many of them need to be downloaded remotely. Rancher will forward these http requests to the Icon URl defined in the chart, and the request timeout is 30s. Before these requests are completed, the browser can no longer process new tasks.

![image](https://user-images.githubusercontent.com/998984/147646590-6916d512-88c6-47dc-9f2f-524bc8a891f6.png)
