### ISSUE TITLE
[2.6.3] Add support for new chart annotation: kube-version 

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#35613]
To ensure that all charts are supported for the k8s 1.22 upgrade, we need the ability to filter out charts from the UI that are not compatible with the cluster's k8s version. 

To do this, all chart.yamls will have an annotation added: `catalog.cattle.io/kube-version`. This annotation will be a semver range that needs to be used to hide the chart in the UI.

**Comment by jiaqiluo** [comment]
### Root cause
A new annotation `catalog.cattle.io/kube-version` is added to the feature chart. It will be used to determine if a chart should show in UI in a cluster based on if the cluster's k8s version is in the range of the `kube-version`
Examples: 
- `catalog.cattle.io/kube-version: < 1.22`
- `catalog.cattle.io/kube-version: > 1.17.0`
- `catalog.cattle.io/kube-version: >= 1.17.0-0 <= 1.20.0-0`

### What was fixed, or what changes have occurred
The changes are in the backend. 
For a specific chart, if the annotation exists, Rancher will return the chart only when the target cluster's k8s version is in the range of the  `kube-version`

### Areas or cases that should be tested
- the version list of feature charts in k8s 1.22 clusters 
- adding/changing the annotation in a new/released chart, the changes should reflect in the UI 

### What areas could experience regressions?
- A chart doesn't support k8s 1.22 but shows in the version list 

### Are the repro steps accurate/minimal?
n/a

**Comment by anupama2501** [comment]
The annotations currently only are present for istio and external-ip-webhook, vsphere cpi/csi on v2.6.3-rc4 
istio: ` catalog.cattle.io/kube-version: 1.19 - 1.22`
externali-webhook ` catalog.cattle.io/kube-version: < 1.22.0`


re-opening as the following are to be addressed:
fleet,fleet-crd, fleet-agent, rancher-logging, rancher-monitoring, cis-benchmark, rancher-alerting

**Comment by brendarearden** [comment]
This issue was re-opened to adress the following: 
fleet,fleet-crd, fleet-agent, rancher-logging, rancher-monitoring, cis-benchmark, rancher-alerting

This is ready to test again, but fleet,fleet-crd, fleet-agent should be ignored because they are hidden from the UI and will not have the kube-version

**Comment by anupama2501** [comment]
Verified the following on rancher v2.6.3-rc6:

Monitoring version 100.1.0+up19.0.3
```
catalog.cattle.io/upstream-version: 19.0.3
catalog.cattle.io/kube-version: '>=1.16.0-0'
catalog.cattle.io/rancher-version: '>= 2.6.0-0 <=2.6.99-0'
```
CIS benchmark: 2.0.2 
```
catalog.cattle.io/kube-version: '>=1.16.0-0'
catalog.cattle.io/rancher-version: '>= 2.6.0-0'
```

Alerting drivers 100.0.1:
```
catalog.cattle.io/kube-version: '>= 1.16.0-0'
catalog.cattle.io/rancher-version: '>= 2.6.0-0 <=2.6.99-0'
catalog.cattle.io/upstream-version: 100.0.1
```

Logging 100.0.1+up3.15.0:
```
catalog.cattle.io/kube-version: >=1.16.0-0
```

**Comment by anupama2501** [comment]
Re-opening this for missing annotation `catalog.cattle.io/rancher-version` and `catalog.cattle.io/upstream-version` for logging.

**Comment by anupama2501** [comment]
The following annotations are missing: 
aks,eks,gke --> `catalog.cattle.io/kube-version: >= 1.18.0-0`

**Comment by anupama2501** [comment]
`kube-version` annotations are not required for aks,eks,gke as they are hidden from the UI

Checks fo other charts look good:
longhorn 100.1.1+up1.2.3
```
catalog.cattle.io/rancher-version: >= 2.6.0-0
catalog.cattle.io/kube-version: >=1.18.0-0
catalog.cattle.io/upstream-version: 1.2.3
```

longhorn 100.0.1+up1.1.3 
```
catalog.cattle.io/rancher-version: >= 2.6.0-0
catalog.cattle.io/kube-version: >= v1.16.0-0, < v1.22.0-0
catalog.cattle.io/upstream-version: 1.1.3
```


rancher-backup 2.1.0 
```
catalog.cattle.io/rancher-version: '>=2.6.0-0'
catalog.cattle.io/kube-version: '>= 1.16.0-0'
catalog.cattle.io/upstream-version: 2.1.0
```

system-upgrade-controller 100.0.1+up0.3.1
```
catalog.cattle.io/rancher-version: '>= 2.6.3-alpha'
catalog.cattle.io/kube-version: >= v1.18.0-0
```

rancher-logging 100.0.1+up3.15.0 
```
catalog.cattle.io/rancher-version: > 2.6.0-0
catalog.cattle.io/kube-version: >=1.16.0-0
catalog.cattle.io/upstream-version: 3.15.0
```
