### ISSUE TITLE
Unavailable node is seen Active in Cluster Management --> Machine Pools page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35646]
**On 2.6-head commit id: `e322f8f`**

- Deploy an RKE1 cluster (I had an 8 node cluster - 3etcd, 2 control and 3 worker nodes and powered one etcd down)
- Power down one of the nodes in the cluster
- the Node in Cluster explorer --> nodes page shows Unavailable
- Machine pool is seen Active.
- Click on the node --> Node is seen Unavailable

**Expected**
Machine pool should not be in Active state

**Comment by kinarashah** [comment]
The issue is stemming from the difference between how norman and steve transform fields for `v3/node (management.cattle.io.nodes)` at api level. 

**Norman**
When we look at v3/node in norman api, conditions from internalNodeStatus get combined with node's status conditions so we can see the `Ready` condition shows up correctly with `Unknown` status for the node - 

<img width="467" alt="Screen Shot 2021-12-01 at 10 34 41 AM" src="https://user-images.githubusercontent.com/16870565/144293299-f83435c2-9039-4ac0-9375-680f9a532534.png">

**Steve**
We don't have transformation logic similar to norman, so there are two different conditions on the v3 node object - 
1. Node status conditions

<img width="423" alt="Screen Shot 2021-12-01 at 10 36 27 AM" src="https://user-images.githubusercontent.com/16870565/144293860-f6d4d973-f7a5-4bc6-b4b3-9a1432e379bd.png">

2. Internal node status conditions which has the Ready condition update 

<img width="565" alt="Screen Shot 2021-12-01 at 10 36 35 AM" src="https://user-images.githubusercontent.com/16870565/144293940-15c03b2a-3ee5-4a12-87b6-e0ac4f4ebcb8.png">

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `e4db3ee`**

- verified on a custom cluster and an RKE1 DO cluster
- Powered down the node in the backend cloud provider console
- The node showed up as Unavailable in machine Pools page

<img width="845" alt="Screen Shot 2021-12-07 at 5 30 40 PM" src="https://user-images.githubusercontent.com/26032343/145132451-28d127b2-d4c6-40d5-bdf5-412139c5de90.png">
<img width="816" alt="Screen Shot 2021-12-07 at 5 32 47 PM" src="https://user-images.githubusercontent.com/26032343/145132478-b5ae4f72-bb74-4d3d-90ef-28bc331d0d47.png">
