### ISSUE TITLE
Cluster owner unable to use shareable harvester cloud credential to edit harvester rke2 cluster

### ISSUE THREAD

**Issue by TachunLin** [rancher/rancher#35651]
**Rancher Server Setup**
- Rancher version: v2.6-head (744f32f)
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Describe the bug**

Harvester cloud credentials aren't shareable between cluster owners. 
so if you create a rke2 harvester cluster with user A, make user B a cluster owner (or other roles), and then come to the edit screen as user B, you will not find the credential here.  

**To Reproduce**
 
1. Environment preparation as above steps
2. Create standard user with name: `userB`
3. Create a 3 nodes Harvester RKE2 cluster 
4. Edit cluster config, assign userB with cluster owner role
5. Login with userB
6. Edit the RKE2 cluster config 
7. Check can load harvester cloud credential correctly

**Result**
Which will cause the error messge
`secrets "cc-t5s8c" is forbidden: User "u-vql4s" cannot get resource "secrets" in API group "" in the namespace "cattle-global-data""`

**Expected Result**

userB could have the ability to edit the assigned cluster as a cluster owner.

**Screenshots**

![image](https://user-images.githubusercontent.com/29251855/143176266-4c24a636-5621-4e09-a1e9-21ea8bbfb7c9.png)

**Additional context**

as discussed  in the [rancher/rancher/#34800](https://github.com/rancher/rancher/issues/34800)

**Comment by yasker** [comment]
Set milestone to `v2.6.3` according to the thread at https://github.com/rancher/rancher/issues/34800#issuecomment-977319514

**Comment by thedadams** [comment]
The Harvester integration works differently from all the other providers I have used. In the other providers (like Digital Ocean), the user is able to use the cloud credential through the meta proxy without having direct read-access to the cloud credential. In the case of Harvester, the UI is making a GET request to directly get the cloud credential.

Giving read-access to the cloud credential is a slippery slope. The user would be able to use the Harvester credential outside of Rancher to do anything they wanted with it. For example, they would be able to copy the credential and use the kubeconfig to do anything in Harvester that is allowed by the kubeconfig (create VMs, etc). I'm not sure if this is the desired result. All other implementations do not give general read-access to the cloud credential.

**Comment by snasovich** [comment]
Moving to "Need Info" based on the https://github.com/rancher/rancher/issues/35651#issuecomment-981955860.
@yasker @guangbochen , need your input here, thank you.

**Comment by guangbochen** [comment]
Hey @thedadams, I believe the case we are discussing here is to allow the admin users to manage the Harvester cluster without access to the `cloud credentials` directly, and that's why the backend development with `meta proxy` support is needed. cc @gitlawr can u please help to add more context here, thanks.

**Comment by gitlawr** [comment]
We need to provide APIs to query Harvester resources without the access to the cloud credential. Similar implementation as https://github.com/rancher/rancher/blob/ec31e6456d4068899460bb83640b63c83eaa72c6/pkg/multiclustermanager/routes.go#L99 for Harvester

**Comment by thedadams** [comment]
OK. This is a much bigger ask compared to "not able to share cloud credential." This would involve backend and frontend changes. Unfortunately, it seems to be too late in the v2.6.3 cycle to get both backend and frontend changes in and QA'd before release.

In addition, in order to implement the backend changes, we need to know which requests will come from the UI, how they will come (which URL, for example) and how they should be made to the Harvester cluster. Once we have this mapping then the UI can do something very similar to how it handles the VSphere proxy with the Harvester proxy. These types of requests should be very specific because we don't want users to use the Harvester proxy to make all kinds of different requests that are not needed for provisioning.

**Comment by snasovich** [comment]
@gitlawr @yasker , please let us know if this is something that should be prioritized? We have not heard back on the https://github.com/rancher/rancher/issues/35651#issuecomment-983009226 and we need this information to proceed.
Meanwhile, I'm moving this issue to unscheduled.

**Comment by yasker** [comment]
@snasovich sorry I missed this message. I don't think we require it for v2.6.4 but need @guangbochen's confirmation. CC @rebeccazzzz

**Comment by guangbochen** [comment]
Yes, move the dependency issue https://github.com/harvester/harvester/issues/1348 to the future milestone from the Harvester side, and in regards to the above API/UI mapping design issue, will need to do a proper investigation and will be updated in this thread later once we have it, thanks.

**Comment by kinarashah** [comment]
@guangbochen @yasker Hi, any updates on the above? Do we need this for v2.6.6 or a future release?

**Comment by guangbochen** [comment]
remove `\stale`, and keep this issue for future release planning, thanks.

**Comment by rebeccazzzz** [comment]
This issue is still relevant. Leaving a comment to remove the stale status.
