### ISSUE TITLE
Not able to import rke1 clusters into the rancher server

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35650]
**Rancher Server Setup**
- Rancher version: `v2.6-head 44b8030 `
- Installation option (Docker install/Helm Chart): Docker install & HA
   - If Helm Chart, Kubernetes Info: k3s & RKE1 
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1` & `v1.22.3-rancher1-1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version:  `v1.21.6` , `v1.22.3` and `v1.18.20`
- Cluster Type (Local/Downstream): `Imported RKE1 cluster 3 nodes all roles`

**Describe the bug**
After importing an rke1 cluster into the rancher server, the cluster is stuck in `Unavailable` state and won't come up active

**To Reproduce**
1. Create an rke1 cluster with any k8s, I tried with k8s 1.22.3, 1.21.6 and 1.18.20
2. Run the curl command against the kubeconfig file of this cluster.

**Result**
Cluster is stuck in `unavailable` state for HA installation and on docker install, it is flapping between `Active` and `Unavailable` state.
Following error was seen on the cluster 
```
Cluster agent is not connected
```
From the cluster agent pod logs, we see the following:
```
time="2021-11-23T22:18:02Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp<redacted>:443: i/o timeout"
time="2021-11-23T22:18:02Z" level=error msg="Remotedialer proxy error" error="dial tcp <redacted>:443: i/o timeout"
time="2021-11-23T22:18:12Z" level=info msg="Connecting to wss://<redacted>/v3/connect with token starting with<redacted>"
time="2021-11-23T22:18:12Z" level=info msg="Connecting to proxy" **url="wss://<redacted>/v3/connect"**
```

**Expected Result**
Expected the cluster to come up active 

**Additional context**
Issue is not seen for imported RKE2 clusters

**Comment by deniseschannon** [comment]
Most likely related to https://github.com/rancher/rancher/issues/35546

**Comment by cbron** [comment]
We understand reason its breaking now, just need to find a new fix.

**Comment by kinarashah** [comment]
For the first cluster agent deployed through template generated by cluster import handler, [CATTLE_FEATURES is empty ](https://github.com/rancher/rancher/blob/release/v2.6/pkg/api/norman/customization/clusterregistrationtokens/import.go#L49) so rancher isn't running. Without secret and aggregation controllers running, session with clientKey `"stv-cluster-{clusterName}"` never gets added for clusters.

hasSession will always remain false until cluster agent is redeployed (during redeploy, CATTLE_FEATURES is set) and then connected becomes true. But [we blocked redeploy if connected is false](https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L96 ), so that's why imported cluster is stuck in the disconnected state.

Can fix this by either: 
1. run rancher in the first agent by passing CATTLE_FEATURES 
2. deploy cluster agent even if connected is false - so basically remove this line https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L96

**Comment by anupama2501** [comment]
2.6-head 9295d4f

- Verified importing rke1 clusters on versions v1.21.4-ranher1-1, 1.21.7-rancher1-1, v1.18.20-rancher1-3 on HA rancher with local on k8s v1.21.7-rancher1-1
- Ran validation checks and the checks look good.
