### ISSUE TITLE
kiali crd is not installed when installing istio version 100.1.0+up1.11.4

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35686]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.20.11, 1.2.13
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.21.6
- Cluster Type (Local/Downstream): Downstream node driver 1 worker, 1 etcd, 1 cp

**Describe the bug**
kiali crd is not installed when istio version 100.1.0+up1.11.4 is installed 

**To Reproduce**
1. Create a downstream rke1 node driver cluster with 3 worker, 1 etcd, 1 worker DO cluster 
2. Install istio version `100.1.0+up1.11.4`

**Result**
If we navigate to apps & Market --> istio --> we see the kiali CRD is not installed.

**Expected Result**
Expected the istio kiali CRD be installed

**Additional context**
Doesn't happen with istio version `100.0.2+up1.10.4` and below.
rancher/mirrored-kiali-kiali:v1.35.0 deployment is seen installed in the istio-system namespace.

**Comment by brendarearden** [comment]
Starting in Kiali version 1.36, they consolidated the dashboard CRDs which removed the CRDs from the helm-chart. https://github.com/kiali/kiali/issues/4057 & https://kiali.io/news/release-notes/#1360.  

A release note needs to be added for this issue: The rancher-istio 100.1.0+up1.11.4 no longer installs the rancher-kiali-server-crd. This is because it was removed from the upstream helm chart starting in Kiali version 1.36. If you have upgraded from a previous version of rancher-istio installed to 100.1.0+up1.11.4, you will need to manually delete the rancher-kiali-server-crd found on the installed apps page since it is no longer in use after the upgrade completes.

**Comment by brendarearden** [comment]
It is expected that the CRD is not showing as installed with 100.1.0+up1.11.4.

**Comment by brendarearden** [comment]
Re-opening as this needs to be removed:  https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-istio/rancher-istio/100.1.0%2Bup1.11.4/charts/kiali/Chart.yaml#L4

**Comment by brendarearden** [comment]
### Root cause 
Kiali removed the CRDs from its chart starting with version 1.36 (see: https://kiali.io/news/release-notes/#1360) 
### What was fixed, or what changes have occurred 
As part of the upgrade to Istio 1.11.4, Kiali was upgraded to 1.41 which removed the CRD installation. Because the CRD chart no longer exists, the chart.yaml annotation `catalog.cattle.io/provides-gvr: monitoringdashboards.monitoring.kiali.io/v1alpha1` was removed. 
### Areas or cases that should be tested
This only changed the chart.yaml, so a basic install and upgrade should be tested. 
### What areas could experience regressions?
None
### Are the repro steps accurate/minimal?
Install/Upgrade to rancher-istio 100.1.0+up1.11.4, view the rancher-kiali installation and validate the chart.yaml does not contain `catalog.cattle.io/provides-gvr: monitoringdashboards.monitoring.kiali.io/v1alpha1`.

**Comment by samkulkarni20** [comment]
**Rancher Server Setup**

- Rancher version:v2.6.3-rc4
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details:Selfsigned

**Information about the Cluster**

- Kubernetes version: v1.21.6
- Cluster Type (Local/Downstream): Downstream node driver 1 worker, 1 etcd, 1 cp

**To Reproduce**

- Create a downstream rke1 node driver cluster with 3 worker, 1 etcd, 1 worker DO cluster
- Install istio version 100.1.0+up1.11.4 & observe if the installation is successful
- Install istio version 100.0.2+up1.10.4 & upgrade it to 100.1.0+up1.11.4. Observe if the installation is successful

**Result**

- Installation & upgrade of Istio chart works as expected.
- If we navigate to apps & Market --> istio --> we see the kiali CRD is not installed.
- Couldn't validate the chart annotation using Rancher, as chart.yaml is not available in UI.

**Comment by anupama2501** [comment]
Closing the issue as the fix is working as expected
