### ISSUE TITLE
Windows node's k8s version is different than cluster's kubernetes version

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35740]
**Rancher Server Setup**
- Rancher version: 2.6head commit `5b56b17`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.7+rke2r1`
- Cluster Type (Local/Downstream): RKE2 custom windows cluster

**Describe the bug**
Windows node's k8s version is different than cluster's kubernetes version

**To Reproduce**

- on a windows 2022 cluster using v1.21.7+rke2r1 version, the linux node is seen to be on version v1.21.7+rke2r1 and the windows node is seen on v1.22.3 k8s.
- Cluster config - 1 linux all roles, 1 windows 2022 worker node.

**Expected Result**
All node' k8s versions should be same as the cluster k8s version

**Comment by phillipsj** [comment]
I wanted to post an update about the last issue listed. We discovered a bug in the system agent installer rke2 script which then uncovered an untested scenario in the RKE2 installer for Windows. The untested scenario is doing an "air gapped" install of the binary without doing an "air gapped" install of the images. That is how the system agent installs RKE2 on Linux. Both items have been fixed and linked to the ticket that was opened for it. I need to do full dev-validation which I will do first thing Monday morning. This fix is going to require an RKE2 release.

**Comment by phillipsj** [comment]
@sirredbeard @Jono-SUSE-Rancher I have a solution and I am working on doing all of the dev validate before merging items since it will require an RKE2 release.

**Comment by phillipsj** [comment]
### Root cause

There were two root causes to this issue. The first is that the RKE2 installer script had some tweaks merged in that changed the environment variables. Since the system agent installer run.ps1 wasn't setting the variables directly it was not picking up those changes and was defaulting to the latest stable release. Upon fixing the system-agent-installer-rke2 run.ps1 script it was uncovered that the airgap install for the binary only tarball, was broken. This wasn't discovered because we only tested a full airgap installation so that path wasn't executed.
 
### What was fixed, or what changes have occurred

We fixed the run.ps1 script in the system-agent-installer-rke2 to pass the needed information by parameters.

* https://github.com/rancher/system-agent-installer-rke2/pull/29

We also fixed the local airgap binary tarball installation only in RKE2.

* https://github.com/rancher/rke2/pull/2214
 
### Areas or cases that should be tested

Provisioning of RKE2 version 1.21.7+rke2r2 and 1.22.4+rke2r2 should occur without errors.

Here is the dev validation for RKE2 standalone installation.

![image](https://user-images.githubusercontent.com/1568133/144896930-0b761084-3360-4828-a899-b53cb29e6a44.png)

Here is the dev validation for the Rancher installation.

![35740-windows-node-joining-cluster](https://user-images.githubusercontent.com/1568133/144896963-8c07836c-8565-448e-b908-42318cabbd40.png)
 
![35740-kubernetes-version-match](https://user-images.githubusercontent.com/1568133/144896978-d0781f80-1679-49bb-8d27-b4c5b645892f.png)

![35470-suc-and-coredns-up](https://user-images.githubusercontent.com/1568133/144896991-c84c4bd2-f219-469d-9236-97fe3beb6c2a.png)

### What areas could experience regressions?

No areas should be impacted for Rancher from this change. A standalone RKE2 installation was performed to verify that the installation script wasn't impacted for that scenarios
 
### Are the repro steps accurate/minimal?

To repreoduce a custom cluster with a minimum of a all roles linux node, a worker linux node, and a worker windows node need to be created using both RKE2 version 1.21.7+rke2r2 and 1.22.4+rke2r2. The Windows version shouldn't impact this issue.

**Comment by phillipsj** [comment]
@slickwarren @sowmyav27 @sirredbeard @Jono-SUSE-Rancher they released a few hours ago.

**Comment by rancher-max** [comment]
This is going to be blocked for full QA at the moment by a couple of things:
- [Unable to provision v1.22](https://github.com/rancher/rancher/issues/35683)
- [1.21 provisioning fails for calico, which is required for windows](https://github.com/rancher/dashboard/issues/4714)

The correct updated KDM is https://github.com/rancher/kontainer-driver-metadata/pull/757, which hasn't been merged yet. But you will hit both of these issues when it is merged. In the meantime, https://raw.githubusercontent.com/rancher-max/kontainer-driver-metadata/test12/data/data.json can be used if desired (which only includes the new rke2 1.21 version and correct chart values), but ideally this should wait until these issues are fixed and the correct KDM pr is merged.

**Comment by sowmyav27** [comment]
Thanks @rancher-max Moving this back to review for now

**Comment by sirredbeard** [comment]
This is not currently a Windows-specific issue.

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `03ed782`**

This issue is fixed
<img width="935" alt="Screen Shot 2021-12-10 at 8 50 50 PM" src="https://user-images.githubusercontent.com/26032343/145664260-efde3ee5-017a-47c8-8bf2-e1eaac4d526c.png">
