### ISSUE TITLE
Not able to install istio 1.11.4 on an air-gapped setup

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35742]
**Rancher Server Setup**
- Rancher version: `v2.6.3-rc2`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.22.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: v1.21.6
- Cluster Type (Local/Downstream): `Downstream RKE1 custom cluster  3 worker, 1 etcd, 1 cp`

**Describe the bug**
When I try to install istio version, rancher-istio:100.1.0+up1.11.4 in the downstream cluster in an air-gapped setup, installation fails with the error `EnvoyFilter/istio-system/metadata-exchange-1.10: Internal error occurred: failed calling webhook "validation.istio.io"` 
This issue is reproduced when we install 1.10.4, uninstall this version and re-install istio rancher-istio:100.1.0+up1.11.4
Can be also seen if the istio version is upgraded from 1.10.4 to 1.11.4.

**To Reproduce**

- Install rancher in a docker in an air-gapped setup
- Pull all the required images for istio installation in the private registry.
- Create a downstream custom RKE1 cluster with 3 worker, 1 etcd, 1 cp with the private registry enabled.
- Install istio version 1.10.4
- Uninstall the istio version to 1.10.4
- Re-install istio version rancher-istio:100.1.0+up1.11.4

**Result**
Installation fails with the error :
```
✔ Istio core installed
--
Fri, Dec 3 2021 11:30:43 am | - Processing resources for Istiod.2021-12-03T19:30:43.478090Z error installer failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:43 am | 2021-12-03T19:30:43.528369Z error installer failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:43 am | 2021-12-03T19:30:43.593018Z error installer failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:43 am | 2021-12-03T19:30:43.678713Z error installer failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:43 am | 2021-12-03T19:30:43.863051Z error installer failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found




✘ Istiod encountered an error: failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
--
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-metadata-exchange-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-metadata-exchange-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-metadata-exchange-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-stats-filter-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-stats-filter-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
Fri, Dec 3 2021 11:30:46 am | failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-stats-filter-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found


```

**Expected Result**
Expected the installation to go through without any error. 

**Additional context**
Found while verifying https://github.com/rancher/rancher/issues/34858
Even after installing 1.10.2, if we uninstall this version and try to re-install it, the error is seen.

**Comment by brendarearden** [comment]
Release note:  A `failed calling webhook "validation.istio.io"` error will occur in AirGapped environments if the `istiod-istio-system` `ValidatingWebhookConfiguration` exists and you attempt a fresh install of Istio >= 1.11.x. Run`kubectl delete validatingwebhookconfiguration istiod-istio-system` and attempt your install again.

### Problem 
Starting in Istio 1.11, an additional `ValidatingWebhookConfiguration` for istiod was created: `istio-validator-istio-system`. This is installed when `global.configValidation` is set true. This is set true by default in >= 1.11.x.  This results in the `istiod-istio-system``ValidatingWebhookConfiguration` not getting cleaned up on an upgrade from <1.11.x to >= 1.11.x. This causes problems if you attempt an uninstall and reinstall at the newest version >=1.11.x in Airgapped environments because the Istio Operator attempts to reconcile the resources that are installed and is unable to apply the necessary patches it needs to without internet access and errors. 

### Potential solutions
Because this only occurs after completing an upgrade from < 1.11.x to >= 1.11.x, uninstalling and reinstalling in an airgapped environment a long term solution is to run `kubectl delete validatingwebhookconfiguration istiod-istio-system` when attempting a reinstall. 

We could change the default behavior in the rancher-istio chart to pass in `global.configValidation: false` to ensure that it continues using and upgrading the `istiod-istio-system` `ValidatingWebhookConfiguration`

Template out the `global.configValidation` option so that it can be set depending on the situation. 

Switch to using the experimental `istioctl x uninstall` in our `istio-installer` image to ensure that ALL resources are removed

**Comment by brendarearden** [comment]
Moved to v2.6.4 - release note with work around will be in v2.6.3 release

**Comment by brendarearden** [comment]
https://github.com/istio/istio/issues/36526 opened an upstream issue for them to include `validatingwebhookconfiguration` as part of upgrade cleanup.

**Comment by samkulkarni20** [comment]
> Moved to v2.6.4 - release note with work around will be in v2.6.3 release

@Jono-SUSE-Rancher The upstream issue is still open & hasn't moved since it was created. Going by above comment, a release note with work around was already part of v2.6.3 release. Do we need anything additional for v2.6.4?

**Comment by Jono-SUSE-Rancher** [comment]
The reason that this ticket is still open (despite the release note) is because Brenda proposed several solutions in her response: 

- We could change the default behavior in the rancher-istio chart to pass in global.configValidation: false to ensure that it continues using and upgrading the istiod-istio-system ValidatingWebhookConfiguration

- Template out the global.configValidation option so that it can be set depending on the situation.

- Switch to using the experimental istioctl x uninstall in our istio-installer image to ensure that ALL resources are removed

Can you investigate some of the solutions and see which one seems the most reasonable?

**Comment by rayandas** [comment]
Tried installing `Istio 1.11.4` on Rancher `v2.6.3` and `Istio 1.11.7` on Rancher `v2.6.4-rc9` air-gapped setup, both are getting installed successfully, also tried uninstalling istio and installing again, it was successful.
cc: @anupama2501

**Comment by anupama2501** [comment]
@rayandas could you try installing istio 1.10.x and then upgrade it to 1.11.x?

**Comment by SheilaghM** [comment]
This issue needs additional investigation so we are moving to v2.6.6

**Comment by rayandas** [comment]
As the PR https://github.com/rancher/istio-installer/pull/56 got merged and the changes are introduced in Istio `100.1.3+up1.11.8` if anyone tries to install Istio 1.10.4, uninstall it and try to install 1.11.8, Istio will get successfully installed. 
Moving this issue to QA to validate it once. 

**Validation steps:**
- Install rancher in a docker in an air-gapped setup
- Pull all the required images for istio installation in the private registry.
- Create a downstream custom RKE1 cluster with 3 worker, 1 etcd, 1 cp with the private registry enabled.
- Install istio version 1.10.4
- Uninstall the istio version to 1.10.4
- Re-install istio version rancher-istio: `100.1.3+up1.11.8`

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6.6-rc1, docker airgap setup

Steps followed:
- Pulled all the required images for istio installation in the private registry.
- Created a downstream custom cluster with 3 worker, 1 etcd, 1 cp with the private registry enabled.
- Installed istio `100.0.2+up1.10.4` 
- Uninstalled the istio version `100.0.2+up1.10.4`
- Re-installed istio `100.1.3+up1.11.8`

Result:
- istio installation was successfull, hence closing the issue.
