### ISSUE TITLE
Monitoring v1 is unavailable after an upgrade of rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35760]
**Rancher Server Setup**
- Rancher version: 2.5.11 to 2.6.3-rc4 upgrade
- Installation option (Docker install/Helm Chart): RKE1 elm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 - `v1.20.10` k8s version
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: v1.20.12 custom rke1 clsuter

**Describe the bug**
Monitoring v1 is unavailable after an upgrade of rancher server

**To Reproduce**

- On 2.5.11.
- Deploy a custom cluster - 1 etcd, 1 cp and 3 worker nodes
- On the local RKE1 cluster and the downstream cluster, deploy monitoring version 0.2.2 from ember UI
- it is deployed successfully, and the graphs are seen on the cluster dashboard
- Helm upgrade rancher server to 2.6.3-rc4
- Monitoring v1 is not available on both the clusters (Check this cluster after about a couple of hours)
- Error seen when trying to access from clustter dashboard
- Api call: `https://rancher-server/v3/clustermonitorgraphs?action=query`
- Error: `{“baseType":"error","code":"ServerError","message":"Failed to obtain metrics. The metrics service may not be available.","status":500,"type":"error”}`
- Error`Failed to obtain metrics. The metrics service may not be available. undefined` on the UI
- No obvious logs from Rancher server.

**Comment by cbron** [comment]
Likely related or same as: https://github.com/rancher/rancher/issues/35559

**Comment by aiyengar2** [comment]
Observed error on QA setup; attempting to reproduce the issue locally to see where the error is coming from.

For now, since the error was noted *both* in the local cluster and the downstream cluster, I'm attempting to reproduce the issue on *only* the local cluster, since I can iterate quicker on the checks.

RKE version of local cluster: `v1.20.12-rancher1-1`

Checked a fresh install of Rancher `2.6.3-rc4` with Monitoring v0.3.1 installed on the local cluster -> `/v3/clustermonitorgraphs?action=query` seems to be operating fine.

Checked a fresh install of Rancher `2.6.3-rc4` with Monitoring v0.2.2 installed on the local cluster -> `/v3/clustermonitorgraphs?action=query` seems to be operating fine.
-> Question: @sowmyav27 did you ever update Monitoring to v0.3.1 after upgrading the Rancher server, or was this observed when the local cluster was still using v0.2.2?

Checked an upgrade of Rancher `2.5.11` with Monitoring v0.2.2 installed on the local cluster to `2.6.2`, without updating to Monitoring v0.3.1 -> `/v3/clustermonitorgraphs?action=query` seems to be operating fine.

Upgraded the prior mentioned setup to `2.6.3-rc4` without updating to Monitoring v0.3.1 ->`/v3/clustermonitorgraphs?action=query` seems to be operating fine.

Tried to redeploy the stateful set to see if prometheus restarting (due to OOMKilled, from what I observed in the original setup) could be triggering this issue -> saw `{"baseType":"error","code":"ServerError","message":"failed to pick endpoint address","status":500,"type":"error"}` on trying to hit the endpoint while Prometheus was re-provisioning and *temporarily* observed the `Failed to obtain metrics. The metrics service may not be available. undefined` error on the UI, as shown in the screenshot below. But future calls to `/v3/clustermonitorgraphs?action=query` seem to be successful...

<img width="1569" alt="Screen Shot 2021-12-08 at 1 46 45 PM" src="https://user-images.githubusercontent.com/13127443/145289809-aeb94f1a-8438-4e87-adc4-2468cc1db3fb.png">

---

### Conclusion

As I'm unable to reproduce the issue precisely on trying various different setups and based on my research on the initially broken cluster, I suspect the issue observed was caused by the following sequence:

A large amount of churn generated in the cluster due to testing issues in a Rancher RC version
-> Leading to a large amount of metrics collected by Prometheus
-> Leading to repeated OOMKills on Prometheus, which took down the Prometheus several times; as I noticed on the QA setup, by the time I got there Prometheus had restarted 50 times and prometheus-agent had restarted 15 times (for unknown reasons)
-> Leading to multiple logs of `{“baseType":"error","code":"ServerError","message":"Failed to obtain metrics. The metrics service may not be available.","status":500,"type":"error”}` that were probably happening when UI tried to execute a Prometheus query before Prometheus was ready to receive query requests, which would repeatedly spawn as Prometheus went through a cycle of restarts

What I noticed on the QA setup was that, once I bumped Prometheus's memory limit to an extremely high value (3000MiB, which is not recommended but used as a way to cast out OOMKilled as being the root cause of the issue), I still noticed that the 500 errors were appearing... but there wasn't a noticeable pattern of why the error was occurring.

@sowmyav27 @Jono-SUSE-Rancher while I can't necessarily confirm that this issue is resolved, unless we can reproduce this again faithfully, I think we should leave this issue open and toss it in our backlog for now, since it could have just been an issue with this particular setup. What are your thoughts?

**Comment by sowmyav27** [comment]
**On 2.5.11 to 2.6-head coommit id: `9295d4f`**

This issue is seen. As described in the original issue on the local and downstream cluster. (right after rancher. server upgrade)

**Comment by aiyengar2** [comment]
I took a look at the setup @sowmyav27 and added additional logging to Rancher to provide context around why we are seeing these errors specifically coming from the following code block:

https://github.com/rancher/rancher/blob/943388d2f764ab2b87f378f9b453de43193c1a81/pkg/api/norman/customization/monitor/cluster_graph_action.go#L130-L134

For context, this code block essentially does a little bit of parallel processing (namely, creating an error group and spinning off the "get query" requests in parallel), which in turn actually makes the query via the Prometheus API client:

https://github.com/rancher/rancher/blob/943388d2f764ab2b87f378f9b453de43193c1a81/pkg/api/norman/customization/monitor/prometheus_manager.go#L94-L98

https://github.com/rancher/rancher/blob/943388d2f764ab2b87f378f9b453de43193c1a81/pkg/api/norman/customization/monitor/prometheus_manager.go#L71-L74

On printing out the log (since it seems like `logrus.WithError(err)` is not working as expected), I see the following repeatedly outputted:

```
query range failed, Post "http://10.42.0.10:9090/api/v1/query_range": read tcp 10.42.1.18:40376->10.42.0.10:9090: read: connection reset by peer, expression: sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~"$namespace",pod_name=~"$podName", container_name=~"$containerName"}[5m]))
...
query range failed, Post "http://10.42.0.10:9090/api/v1/query_range": read tcp 10.42.1.18:56038->10.42.0.10:9090: read: connection reset by peer, expression: sum(rate(container_network_transmit_packets_dropped_total{namespace=~"$namespace",pod_name=~"$podName", container_name!=""}[5m]))
```

where the IP addresses listed above are `RANCHER:56038->PROMETHEUS:9090`, as indicated below:

```
$ kubectl get pods -o wide -A | grep 10.42.1.18
cattle-system               rancher-68749df874-mffw2                                   1/1     Running     0          10m   10.42.1.18      3.145.155.123    <none>           <none>
$ kubectl get pods -o wide -A | grep 10.42.0.10
cattle-prometheus           prometheus-cluster-monitoring-0                            5/5     Running     1          80m   10.42.0.10      3.17.179.219     <none>           <none>
```

**Comment by aiyengar2** [comment]
After numerous rounds of testing, it seems like the root cause of this issue is https://github.com/rancher/rancher/pull/34847; on executing a revert of that PR's contents in https://github.com/rancher/rancher/pull/35871, we see that a previously broken Monitoring V1 setup recovers fully, with no more 500s.


Also, based on my testing, it seems like the symptoms of the 500s appearing also correlate with a different set of symptoms; namely, the dashboards shown below seem to be 1) wildly incorrect and 2) the exact same graph overlaid multiple times under multiple contexts.

![arvind-rancher-server-0 cp-dev rancher space_c_local_monitoring (1)](https://user-images.githubusercontent.com/13127443/146119121-39644407-e482-48d4-ae89-0fa6db90090f.png)

![arvind-rancher-server-0 cp-dev rancher space_c_c-g2jf5_monitoring (2)](https://user-images.githubusercontent.com/13127443/146119128-94b115ce-b851-4fb8-8961-5364f1c1bf0d.png)

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.11 to 2.6-head commit id: `39cecf0`**

- The monitoring 0.2.2 graphs are available after rancher server upgrade and the graphs are different and look good.
- The monitoring metrics look good for both local and downstream cluster

<img width="1426" alt="Screen Shot 2021-12-15 at 8 38 42 PM" src="https://user-images.githubusercontent.com/26032343/146309303-1cd83018-0edc-4ff1-b441-45210e003e68.png">


<img width="1455" alt="Screen Shot 2021-12-15 at 8 38 35 PM" src="https://user-images.githubusercontent.com/26032343/146309307-cad8dc84-fb7a-4765-b5c4-22e5464678a8.png">
