### ISSUE TITLE
v1 alerts are not working on 2.6.3 -> alerts are not `firing` when there is activity

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35776]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc4
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.20.13, 1.22.3
- Cluster Type (Local/Downstream): both were tested (local 1.22, downstream 1.20 and 1.22)
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): node driver, digital ocean

**Describe the bug**

* alerts are not firing when there is clear activity for that alert

**To Reproduce**
 
* enable legacy flag
* add a notifier (legacy -> notifiers). I used slack
* add a simple alert (legacy -> alerts) i.e. normal pod activity should send an alert
* deploy a workload or deploy some charts

**Result**
alerts are not firing and the notifiers are not being triggered

**Additional context**
found when testing https://github.com/rancher/rancher/issues/34059#issuecomment-986420709
edit: after installing monitoring v0.3.1, this is working on the 1.20 downstream cluster since alerting is dependent on the operator that monitoring installs.

**Comment by jiaqiluo** [comment]
The bug is reproduced in rancher 2.6.3-rc4 single install setup.

Alerting v1 is broken in Rancher v2.6.3-rc4 (local cluster runs k3s 1.22 ), in downstream clusters running either RKE1 1.20 or 1.22

Normally, there should be two apps installed in the system project when cluster alerting is enabled: cluster-alerting and monitoring-operator. 
![image](https://user-images.githubusercontent.com/6218999/145120826-aa54c2bb-821d-49c3-beef-77167ed1834b.png)


In the downstream 1.20 cluster, the cluster-alerting app is installed with some resources missing, the monitoring-operator app is not installed.  We see the following error in rancher logs 
```
2021/12/07 19:43:00 [ERROR] error syncing 'c-vqvng/car-zhkcj': handler cluster-alert-rule-deployer: failed to get Alertmanager Deployment information, statefulsets.apps "alertmanager-cluster-alerting" not found, handler cluster-alert-rule-controller: Failed to get service for alertmanager, services "cattle-prometheus/alertmanager-operated" not found, requeuing
```

In the downstream 1.22 cluster,  none of those two apps are installed, and we see the following error in rancher logs 
```
[tiller] 2021/12/07 23:03:31 warning: Release cluster-alerting crd-install rancher-monitoring/templates/crds.yaml failed: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
[tiller] 2021/12/07 23:03:31 failed install perform step: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
Finished installing CRD: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"2021/12/07 23:03:31 [DEBUG] Stopping Tiller
```
and the following in the app in  Rancher UI 

![image](https://user-images.githubusercontent.com/6218999/145120661-cf9832d0-ef66-4f59-a5f2-c20849e1b392.png)

The error makes sense because `apiextensions.k8s.io/v1beta1` does not exist in 1.22 cluster.

**Comment by cbron** [comment]
Going to test this with 1.21 before bumping to 2.6.4.

**Comment by jiaqiluo** [comment]
### Root cause
The prometheus-operator-handler is used for both monitoring and alerting, but in rancher v2.6 it will be started only if monitoring is enabled. 
As the result, enabling alerting alone does not trigger prometheus-operator-handler to run, so alerting is broken. 

### What was fixed, or what changes have occurred
enable the prometheus-operator-handler when either monitoring or alerting is enabled. 

### Areas or cases that should be tested
alerting v1 

### What areas could experience regressions?
- both the cluster-alerting and monitoring-operator app should be installed properly 
- alerts can be sent out to receives such as lack 

### Are the repro steps accurate/minimal?
yes, the steps in the original issue is accurate.

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**
- Rancher version: v2.6.3-rc4
- Installation option (Docker install/Helm Chart): docker

**Cluster Information**
- Cluster type: RKE1
- K8s Version: 120.13

**Steps For Reproduction**
1. enable legacy flag

2. add a notifier (legacy -> notifiers). I used slack

3. add a simple alert (legacy -> alerts) i.e. normal pod activity should send an alert

4. deploy a workload or deploy some charts

**Result**
There were no slack notifications sent when I installed and app or a workload. 

**Setup For Validation**
- Rancher version: v2.6.3-head(fd930f7)
- Cluster type: RKE1
- K8s Version: : v1.21.7

**Steps for validation**
1. enable legacy flag

2. add a notifier (legacy -> notifiers). I used slack

3. add a simple alert (legacy -> alerts) i.e. normal pod activity should send an alert

4. deploy a workload or deploy some charts

**Result**
The alerts are being sent once the appropriate parameters are met that got set within the notifier.
