### ISSUE TITLE
Questions about Rancher Service Discovery + Labels

### ISSUE THREAD

**Issue by DanielDent** [rancher/rancher#3579]
Hello,

I just prepared an initial release of [Cowhand](https://github.com/DanielDent/cowhand), a Rancher Catalog integration of Prometheus, InfluxDB, Grafana, and Alertmanager. It comes with cadvisor & node-exporter to provide monitoring of nodes.

For that, I created [prom-rancher-sd](https://github.com/DanielDent/prom-rancher-sd), a service discovery bridge to allow Prometheus to autodiscover Rancher services which should be monitored.

I've got some questions about the Rancher metadata service:

1. Is this the best interface for me to use to get this data? One reason I am thinking something better might be available is that I am polling the interface. Is there a Consul-like 'long lived request' notion so changes can be pushed? Right now between my polling interval (30s) and Prometheus' polling interval (30s) it could be up to a minute from the time a service shows up in the interface to the time the service is monitored.

2. How expensive are rancher metadata requests, and how distributed is the load of those requests? Would polling more frequently be (in)advisable?

3. What are the consistency semantics and how will this interface behave under various failure conditions? For instance, during a network split, will I continue to see services on the other side of the split? The thing with combining Monitoring + automatic service discovery is that it's important to understand when a service might automatically stop being monitored.

4. Currently a service registers to be monitored by providing a `com.danieldent.cowhand.prom.port` label on the service. The service is automatically labelled with the instance set to the 'hostname' parameter, and the stack, service, and instance name are assigned labels as well. 

Things I'm currently thinking about:
   * Providing an additional label where people can specify key-value pairs for labels they want added to the monitoring.
   * Automatically adding the host labels from the host a service is running on.
   * Making use of other container/service/stack labels.

I'd appreciate your feedback on what would might make sense to implement, as well as any other suggestions you could offer.

**Comment by vincent99** [comment]
1. We will probably add a push method but polling metadata is fine.  There is a value at `GET /2015-12-19/version` which changes when the metadata does, so you can poll that and only look at other stuff when you see it change (rather than watching many different keys).  There is also the regular API and a WebSocket socket that sends a frame every time a resource changes if you want to subscribe to the firehose instead of polling.

2. You're talking to a process in the Network Agent on the same host as the requesting container and it has all the metadata in memory.  Our [external-dns](github.com/rancher/external-dns) service polls the version every second.

3. Metadata changes are pushed from the rancher/server to the host agents.  So agents that are no longer connected to the server won't see any changes.  Service health checks are run on 3 hosts (different ones than the target container is on, if $num_hosts >= 4) and pushed to the server, which would then update metadata when the health state changes.

I don't think there's a great answer for how to tell if you're on the wrong side of a split, because metadata won't be getting updated anymore and there's not a key for anything like the last time it was known to be current.  You might be better off talking to the API directly here and watching host/service/container `state` and `healthState`.

**Comment by DanielDent** [comment]
Thanks for the detailed answer, this is extremely helpful!

**Comment by deniseschannon** [comment]
@DanielDent If you have more questions, please open a new issue!
