### ISSUE TITLE
[2.5] Kubectl error "You must be logged in to the server"

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#35791]
backport: https://github.com/rancher/rancher/issues/30230

**Comment by MbolotSuse** [comment]
Validation template:

Root cause
Older versions of the Go-ldap library have an integer overflow in the error handling (https://github.com/go-ldap/ldap/blob/v2.5.1/error.go#L119) which causes certain error codes (namely 4096) to be treated as 0 (success). This causes Rancher to errantly invalidate user tokens.

What was fixed, or what changes have occurred
Updated the go-ldap library from v2 to v3.

Areas or cases that should be tested
Using openldap and AD as external auth providers.

What areas could experience regressions ?
Authentication and authorization (RBAC) when using openldap or AD as external auth providers.

Are the repro steps accurate/minimal ?
No. Reproduction of the original issue is as follows:

1. In openldap, create 3 users: A service account, a rancher admin, and a rancher user.
2. In openldap, create a rancherGroup. Assign rancher user to the rancher group.
3. In rancher, add the openldap server as the authentication method (using rancher admin). Change the configuration options so that only authorized users/groups have access to rancher and add Rancher Group to the authorized list.
4. Change the auth-user-info-max-age-seconds value so that a refresh will be forced when the user uses the config token (recommended value: 30).
5. Add a new project (testProject) and grant Rancher Group member level access to it.
6. Create a new namespace (test) in test project.
7. Log in as rancher user. Download the kubeconfig file for the cluster that testProject is in. 
8. Confirm that you can use the kubeconfig file by running a simple command such as `k get secrets -n test`.
9. In openldap, enable the retcode overlay with a large power of 2. 4096 represents a valid openldap error code.
10. Wait at least the amount of seconds specified in 4.
11. Attempt to use the same basic command as was used in step 8. 
12. Without the patch, this command will fail. With the patch, the command will succeed (note: even with the patch, powers of 2 greater than or equal to 131072 will still cause a failure).

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.5.10                                 |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | N/A                                     |
| Downstream K8s version  | N/A                                     |
| Browser type            | Google Chrome                           |
| Browser version         | 97.0.4692.71 (Official Build) (x86_64)  |

## Reproduction steps

1. Create an OpenLDAP server with the following users and groups
    - Service Account
    - Admin Account
    - User Account
    - User Group
2. Add the User Account to the User Group
3. In Rancher add the OpenLDAP server as the authentication method (using rancher admin)
4. Select the setting `Restrict access to only Authorized Users and Organizations` and add the User Group created on the OpenLDAP server
5. Change the `auth-user-info-max-age-seconds` value so that a refresh will be forced when the user uses the config token (recommended value: 30).
    - To find this value start at `/g/clusters` -> click `Settings` -> scroll down until you see `auth-user-info-max-age-seconds` -> change the value to `30`
6. Create a new project: `mytest-project` -> assign the Rancher Group member level access to it
7. Create a new namespace in the newly created project: `mytest-namespace`
8. Log in as rancher user. Download the kubeconfig file for the cluster that `mytest-project` is in
9. Run a simple command like the following, and you will receive a valid response

```shell
kubectl get secrets -n mytest-namespace
```

10. In OpenLDAP force a 4096 error code using the retcode overlay
11. Wait the amount of time specified in `step #5`
12. Attempt the same command again from `step #9`

### RESULTS

You will get the error message `error: You must be logged in to the server (Unauthorized)`

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.5-89ccfcf10f7985a6e5eb0a4ed6cb5f6d8f22a559-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | N/A                                                |
| Downstream K8s version  | N/A                                                |
| Browser type            | Google Chrome                                      |
| Browser version         | 97.0.4692.71 (Official Build) (x86_64)             |

## Validation steps


1. Create an OpenLDAP server with the following users and groups
    - Service Account
    - Admin Account
    - User Account
    - User Group
2. Add the User Account to the User Group
3. In Rancher add the OpenLDAP server as the authentication method (using rancher admin)
4. Select the setting `Restrict access to only Authorized Users and Organizations` and add the User Group created on the OpenLDAP server
5. Change the `auth-user-info-max-age-seconds` value so that a refresh will be forced when the user uses the config token (recommended value: 30).
    - To find this value start at `/g/clusters` -> click `Settings` -> scroll down until you see `auth-user-info-max-age-seconds` -> change the value to `30`
6. Create a new project: `mytest-project` -> assign the Rancher Group member level access to it
7. Create a new namespace in the newly created project: `mytest-namespace`
8. Log in as rancher user. Download the kubeconfig file for the cluster that `mytest-project` is in
9. Run a simple command like the following, and you will receive a valid response

```shell
kubectl get secrets -n mytest-namespace
```

10. In OpenLDAP force a 4096 error code using the retcode overlay
11. Wait the amount of time specified in `step #5`
12. Attempt the same command again from `step #9`

### RESULTS

The command successfully works! There is no error

**Comment by MbolotSuse** [comment]
Release Note: 

Fixed an issue where LDAP servers which returned specific high-value error codes (such as 4096) would cause rancher to invalidate user's kubeconfig tokens during the nightly auth refresh or when the user attempted to use their kubeconfig token. See [#30230](https://github.com/rancher/rancher/issues/30230).
