### ISSUE TITLE
EKS Node Group deletion piloted by Rancher

### ISSUE THREAD

**Issue by jonathanribas** [rancher/rancher#35804]
**Rancher Server Setup**
- Rancher version: 2.5.6

**Information about the Cluster**
- Kubernetes version: 1.18
- Cluster Type (Local/Downstream): 
* Hosted = EKS

**Describe the bug**

Yesterday AWS had a serious service outage in North Virginia, so our EKS Node Groups were certainly unhealthy at a time.

Rancher has asked EKS to delete all our node groups. Our services went completely down, we had to run manual commands to make our website back in business.

It's still unstable at that time as Rancher UI inform us the following message even if we have re-created manually Node Groups on AWS side. It

> This cluster is currently Waiting.
> 
> Cluster must have at least one managed nodegroup.

**To Reproduce**

We are not sure how to reproduce but it may be related with unhealthy EKS Node Group.

**Result**

Node Groups are deleted automatically by Rancher. 

Our services are completely down. In order to have them back we need to create a new cluster as the existing one is not editable anymore. It seems to have lost connectivity with cluster on Rancher UI edit cluster.

> This cluster is currently Waiting.
> 
> Cluster must have at least one managed nodegroup.

Some logs at Rancher level:

2021/12/08 09:35:01 [INFO] updating cluster [c-lnl9z], upstream change detected 
2021/12/08 09:35:01 [ERROR] error refreshing EKS cluster [c-lnl9z] upstream state 
2021/12/08 09:35:21 [INFO] update kontainerdriver amazonelasticcontainerservice 
2021/12/08 09:35:21 [INFO] update kontainerdriver azurekubernetesservice 
2021/12/08 09:35:21 [INFO] update kontainerdriver baiducloudcontainerengine 
2021/12/08 09:35:21 [INFO] update kontainerdriver huaweicontainercloudengine 
2021/12/08 09:35:21 [INFO] update kontainerdriver opentelekomcloudcontainerengine 
2021/12/08 09:35:21 [INFO] update kontainerdriver oraclecontainerengine 
2021/12/08 09:35:21 [INFO] update kontainerdriver aliyunkubernetescontainerservice 
2021/12/08 09:35:21 [INFO] update kontainerdriver linodekubernetesengine 
2021/12/08 09:35:21 [INFO] update kontainerdriver tencentkubernetesengine 
2021/12/08 09:35:21 [INFO] update kontainerdriver googlekubernetesengine 
2021/12/08 09:35:21 [INFO] update kontainerdriver rancherkubernetesengine 
2021/12/08 09:35:26 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:34427 
2021/12/08 09:35:26 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:43351 
2021/12/08 09:35:26 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:35749 
2021/12/08 09:35:26 [INFO] kontainerdriver azurekubernetesservice stopped 
2021/12/08 09:35:26 [INFO] kontainerdriver amazonelasticcontainerservice stopped 
2021/12/08 09:35:26 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating 
2021/12/08 09:35:26 [INFO] kontainerdriver googlekubernetesengine stopped 
2021/12/08 09:35:26 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating 
2021/12/08 09:35:26 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating 
2021/12/08 09:35:30 [INFO] waiting for cluster EKS [c-lnl9z] to update 
2021/12/08 09:35:30 [INFO] waiting for cluster EKS [c-lnl9z] to update 

**Expected Result**

In my opinion it's way too hard to delete Node Groups automatically. 

Maybe Rancher wants to delete them but it has to try to create them again, otherwise our services stay down forever. 

We are using Kubernetes to do less maintenance or recovery operations.

**Comment by JonathanParrilla** [comment]
This has happened to us twice in the last month. On 12/7 and before that on 11/24.

**Comment by thedadams** [comment]
### Root cause
The root of the issue was a missing `nil` check. The EKS, GKE, and AKS implementations were combined to reduce code duplication. A type was added to hold the configs for each of these types of hosted clusters. Rancher was checking for `nil` on this new type, but was not checking on the appropriate configs contained in that type. For example, for EKS clusters, the `eksConfig` field of this new type should be checked.

### What was fixed, or what changes have occurred
A `nil` check was added to the configs.

### Areas or cases that should be tested
Syncing should be checked:
1. Deploy an AKS/EKS/GKE cluster from Rancher.
2. After the cluster becomes active, make a change to the cluster (like add a new node group) from the hosted provider (not in Rancher)
3. After 5 minutes, the change should show up in Rancher. The easiest way check this is to edit the cluster from the Rancher UI and verify the change is in the config there.

### What areas could experience regressions?
Syncing for EKS, AKS, and GKE.

### Are the repro steps accurate/minimal?
The problem with reproduction is that it requires errors from AWS. This change was checked by manually changing the code locally to always error and ensure that the syncing was disabled after the change. It may be possible for QA to test error scenarios involving the AWS API, but that would require significant effort.

**Comment by brudnak** [comment]
# My checks PASSED
 
<hr>
  
## Validation Environment

| Component               | Version / Type                                              |
| ----------------------- | ----------------------------------------------------------- |
| Rancher version         | v2.6-03ed782ae89950ae664b9cfef899723cf5e60b4a-head          |
| Rancher cluster type    | Docker                                                      |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2                     |
| Helm version            | v2.16.8-rancher1                                            |
| Downstream cluster type | EKS, AKS, GKE                                               |
| Downstream K8s version  | (EKS k8s=1.21), (AKS k8s=1.21.2), (GKE k8s=1.21.5-gke.1302) |
| Browser type            | Google Chrome                                               |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)                      |

## Validation steps

1. Create EKS, AKS, and GKE downstream clusters
2. Login directly to EKS, AKS, GKE (outside of rancher)
3. Make change to the cluster (adding a node pool)
4. Wait 5 minutes to confirm the changes are reflected in rancher
    - Edit the config of each cluster and make sure the newly added node pool is present
  
#### RESULTS

1. EKS - PASS
2. AKS - PASS 
3. GKE - PASS
