### ISSUE TITLE
the default value in the questions.yml didn't take effect

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#35825]
**Rancher Server Setup**
- Rancher version: `v2.6-head`

**Describe the bug**
- When the default value is specified in the `questions.yml` but it does not take effect.
the default value of [hostPath](https://github.com/rancher/charts/blob/dev-v2.6/charts/harvester-csi-driver/harvester-csi-driver/100.0.0%2Bup0.1.6/questions.yml#L11) in the csi-chart is `/etc/kubernetes/cloud-config` but it was using the original value fro the `values.yaml` file.
![image](https://user-images.githubusercontent.com/4569037/145365504-49766b38-a00a-4a2a-9e5c-fbb851d9ef49.png)

**Result**
the chart is installed with the default values from `values.yml`

**Expected Result**
the `questions.yml` values should take effect

**Comment by StrongMonkey** [comment]
Looks like it is using `catalog:cattle.io/namespace` which has a typo.

**Comment by vincent99** [comment]
For the first one, set the default in values.yaml and not (also) questions.yaml's default.  They are contradictory and the intended behavior is that values.yaml wins, so that you get the same result from `helm install <chart>` and just clicking through the UI install without changing anything.

For the 2nd, the annotation is incorrect as @StrongMonkey, said so it has no effect.

**Comment by guangbochen** [comment]
thanks for the detailed explanation and close in favor of https://github.com/rancher/charts/pull/1649 as have set the desired value in the `values.yaml` instead of using the `questions.yml`.
