### ISSUE TITLE
Actions that cannot be performed by a Cluster member are available on an RKE1 cluster in a rancher setup when RKE2 flag is disabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35828]
**On 2.6-head commit id: `b43e4d9`**

Actions that cannot be performed by a Cluster member are available on an RKE1 cluster in a rancher setup when RKE2 flag is disabled
<img width="1126" alt="Screen Shot 2021-08-24 at 11 04 08 PM" src="https://user-images.githubusercontent.com/26032343/130735223-25c71212-db96-459a-ad96-26cf74862442.png">

**Comment by snasovich** [comment]
It's possible that controller(s) that should be tied to V2 provisioning flag are controlled by RKE2 flag instead. We may need to switch which flag enables these controllers.

**Comment by annablender** [comment]
I reproduced this on a local single node DO RKE1 cluster, with the RKE2 flag both enabled and disabled. Both times I saw the `Take Snapshot` and `Rotate Certificates` options for the standard cluster member, so it's safe to assume the RKE2 flag status is unrelated to this bug.

PR in with fix https://github.com/rancher/rancher/pull/35963.

**Comment by annablender** [comment]
## Testing template

#### Root cause

A standard cluster member on an RKE1 cluster was seeing options reserved for a cluster admin because the logic in the Norman API on what actions to make permissible to a user was incorrect.
 
#### What was fixed, or what changes have occurred

- Updated https://github.com/rancher/rancher/blob/release/v2.6/pkg/api/norman/customization/cluster/actionhandler.go
- Updated logic in https://github.com/rancher/rancher/blob/1a361b790d3099e004732ad2f51936456a53cd3c/pkg/api/norman/customization/cluster/formatter.go#L38

#### Areas or cases that should be tested

1. Create a new `user`
2. Create an RKE1 downstream cluster with `user` as a standard cluster member
3. Logout and login as `user`
4. You should only have access to the downstream cluster. View your cluster and make sure your actions drop down for the cluster looks like this
 
![image](https://user-images.githubusercontent.com/12955547/151041790-08dadeb4-90f7-4cf8-b4e8-ecd71cf186ae.png)

#### What areas could experience regressions ?

Rancher UI actions list for an RKE1 cluster if logic is overwritten.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by Auston-Ivison-Suse** [comment]
**Reproduction Setup**
- rancher version: v2.6.3
- Downstream cluster: rke1, ec2, k8s: v1.21.9-ranche1-1

**Reproduction Steps**
1. Create user with standard permissions
2. Login as said user and create downstream cluster
3. Logout and log back in. Check the actions within the kebab menu. 

**Result**

The actions available in the dropdown are not the permissible actions of a standard user. 

**Setup For Validation **
- rancher version: v2.6-head(
- Downstream cluster: rke1, ec2, k8s: v1.21.9-ranche1-1

1. Create user with standard permissions
2. Login as said user and create downstream cluster
3. Logout and log back in. Check the actions within the kebab menu. 

**Results**

The correct actions are available. 

**Screenshot**

Reproduction Screenshot: 

![StandardPermissionsRepro.png](https://zube.io/files/rancher/ce01d7cd2d774cba728db3488906a4a2-standardpermissionsrepro.png)

Validation Screenshot:
![PermissionsStandardValid.png](https://zube.io/files/rancher/9f4b744526c52374edbde98b59d175e4-permissionsstandardvalid.png)
