### ISSUE TITLE
`v1.21.6+rke2r1` RKE2 cluster goes into provisioning state on a rancher server upgrade 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35821]
**Rancher Server Setup**
- Rancher version: 2.6.2 to 2.6-head commit id: `77392a6`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.6+rke2r1` RKE2 cluster EC2 node driver
- Cluster Type (Local/Downstream): Downstream

**Describe the bug**
`v1.21.6+rke2r1` RKE2 cluster goes into provisioning state on a rancher server upgrade 

**To Reproduce**
Deploy a 2 node RKE2 cluster - 1 all roles, 2 worker nodes
Upgrade rancher from 2.6.2 to 2.6-head
Cluster goes into provisioning state
<img width="992" alt="Screen Shot 2021-12-08 at 9 37 21 PM" src="https://user-images.githubusercontent.com/26032343/145341076-6b2ceb0c-57a8-40c7-bbfc-d8eca471f1fe.png">

Worker nodes upgrade
<img width="661" alt="Screen Shot 2021-12-08 at 9 37 44 PM" src="https://user-images.githubusercontent.com/26032343/145341094-c4825047-f10e-4158-badc-9d96f6624b6d.png">

**Expected Result**
Cluster should not upgrade on a rancher server upgrade

**Comment by thedadams** [comment]
When upgrading from v2.6.2 to v2.6.3, provisioning clusters will have to go into a provisioning state. That is because there was an update to the provisioning cluster CRD that will cause the cluster to reconcile.

In addition, as RKE2 provisioning reaches GA, machine plans will be updated and existing clusters will need to be reconciled on Rancher upgrade. Soon, this will not need to be the case, but for now it is.

However, [this](https://github.com/rancher/rancher/issues/35822) is a valid concern: even if the cluster needs to reconcile, it should become active.

**Comment by sowmyav27** [comment]
Change to provisioning CRD was done here - https://github.com/rancher/rancher/issues/35161, so the clusters going into provisioning state to reconcile is expected behavior here. This should not happen once RKE2 goes GA. Closing this issue for now.
