### ISSUE TITLE
`v1.21.6+rke2r1` RKE2 cluster is stuck in provisioning state on a Rancher server upgrade when a worker node is stuck in `Nodeconditionsfailed` state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35822]
**Rancher Server Setup**
- Rancher version: 2.6.2 to 2.6-head commit id: `77392a6`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.6+rke2r1` RKE2 cluster EC2 node driver
- Cluster Type (Local/Downstream): Downstream

**Describe the bug**
`v1.21.6+rke2r1` RKE2 cluster is stuck in provisioning state on a Rancher server upgrade

**To Reproduce**

- Deploy a 2 node RKE2 cluster - 1 all roles, 2 worker nodes
- Upgrade rancher from 2.6.2 to 2.6-head
- Cluster goes into provisioning state  - logged bug - https://github.com/rancher/rancher/issues/35821
- Worker node is stuck in `Nodeconditionsfailed` state
- And the cluster is stuck in provisioning state
<img width="1452" alt="Screen Shot 2021-12-08 at 9 42 37 PM" src="https://user-images.githubusercontent.com/26032343/145341398-7b16fb33-1609-4c5e-bcce-17fcdf2035f3.png">

**Expected Result:**
On an Upgrade, worker node should not get stuck in `Nodeconditionsfailed` state

Maybe related to: https://github.com/rancher/rancher/issues/35714

**Note:**
Cluster seems to have recovered in ~30 mins

**Comment by thedadams** [comment]
### Root cause
The root cause of this issue was a race condition in the controllers for Rancher and for CAPI.

### What was fixed, or what changes have occurred
The caches used in CAPI for the Rancher objects were started if the weren't already started.

### Areas or cases that should be tested
RKE2/K3S provisioning:
1. Single node all roles.
2. 3 nodes, one role each
3. 1 control plane, 1 etcd and multiple worker nodes

### What areas could experience regressions?
Provisioning and editing

### Are the repro steps accurate/minimal?
Yes.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

RKE2 provisioning and edit usecases for the following have been tested
- Single node all roles.
- 3 nodes, one role each
- 1 control plane, 1 etcd and multiple worker nodes

**Comment by thedadams** [comment]
Issue was reopened by zube bot.
