### ISSUE TITLE
[monitoring v2] RKE2 Windows (2022) nodes are not reporting to `serviceMonitor/kube-system/rancher-monitoring-kubelet` in prometheus

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35851]
**Rancher Server Setup**
- Rancher version:v2.6-head (03ed782)
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1 1.22.x local cluster
- Proxy/Cert Details: letsencrypt certs (valid)

**Information about the Cluster**
- Kubernetes version: 1.21.7+rke2r2
- monitoring version: 100.1.0+up19.0.3
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, windows workers running version 2022

**Describe the bug**

monitoring is showing windows nodes as `down` for metrics in prometheus `serviceMonitor/kube-system/rancher-monitoring-kubelet`

**To Reproduce**
 
* deploy a custom downstream cluster (1 etcd/cp linux, 2 worker linux, 2 worker windows 2022)
* install monitoring

**Result**
Monitoring is able to install, however prometheus shows `serviceMonitor/kube-system/rancher-monitoring-kubelet` targets down for windows nodes. Linux nodes are healthy

**Expected Result**

expecting windows nodes to not be down for any endpoints through prometheus

**Comment by slickwarren** [comment]
my apologies, Yes this was indeed using rke2r2, not r1. I've updated the main comment as well.

**Comment by phillipsj** [comment]
We have found one of the issues here: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-windows-exporter/rancher-windows-exporter/0.1.100/scripts/check-wins-version.ps1#L3

That is causing the wins check to fail and not allowing it deploy the additional pods. /cc @luthermonson @sirredbeard @rosskirkpat.

**Comment by sirredbeard** [comment]
Fix has been merged. Will dev validate and then move into QA to test.

**Comment by phillipsj** [comment]
A potentially related issue. @sirredbeard @sowmyav27 https://github.com/rancher/rancher/issues/35751

**Comment by phillipsj** [comment]
### Root cause

The monitoring chart has a script that is determining the version of Wins that is installed by executing Wins that is located in C:\Windows\Wins.exe. Wins is copied to that location by the Rancher Agent in the bootstrap.ps1 script. RKE2 doesn't work the same and therefore Wins wasn't being copied into that location. 
 
### What was fixed, or what changes have occurred

The Rancher Windows installer was updated to include this additional step of copying the Wins.exe to C:\Windows directory. Windows Firewall will also need to be checked to ensure that the probes can communicate correctly.

### Areas or cases that should be tested
 
Deployment of an RKE2 Windows worker node should be tested to make sure that the installation script changes had no negative impact. In addition, the Monitoring chart should be installed to ensure that everything is deployed in a healthy state.

### What areas could experience regressions?

Installation of RKE2 through the Rancher Windows installation script.
 
### Are the repro steps accurate/minimal?

The repo steps are the same as the ones defined in the ticket and the same steps were taken to do validation. This will need to be on a new 2.6-head build to pick up these changes, but no other depedencies are required.
![35851-cluster-management](https://user-images.githubusercontent.com/1568133/146066792-dd24efc2-311f-4419-a88a-5456d225554b.png)
![35851-nodes](https://user-images.githubusercontent.com/1568133/146066803-347f3e1d-759b-447e-b3f5-bfa0d20d5773.png)
![35851-coredns](https://user-images.githubusercontent.com/1568133/146066816-dd0de946-e7c6-4ae7-afe1-50c9a36baa23.png)
![35851-windows-exporter-deployed](https://user-images.githubusercontent.com/1568133/146066827-3e34b8ab-09b9-4fcc-b1bd-b21886906b66.png)
![35851-metrics-reporting-as-up](https://user-images.githubusercontent.com/1568133/146066843-a6ab4be1-79f5-4729-bb6a-d0628364d612.png)

**Comment by slickwarren** [comment]
tested on v2.6-head (6de683b):
setup -> custom rke2 cluster, k8s v1.21.7+rke2r2, dedicated linux nodes, 3 worker windows nodes. 

Monitoring targets are now all up. Part of the issue was [allowing traffic on the ports for monitoring](https://github.com/rancher/windows/issues/128)
