### ISSUE TITLE
[2.6.3] - Update AKS / EKS / GKE operators to the latest wrangler

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#35875]
Need to ensure that AKS / EKS / GKE operators are updated to the latest wrangler release and vendor those changes into rancher/rancher

https://github.com/rancher/gke-operator/blob/548d87a06a553abc5429341d85e39652abf4f823/go.mod#L9
https://github.com/rancher/eks-operator/blob/2752114461247c4ee7a116220fc4bb0df5c9ff66/go.mod#L11
https://github.com/rancher/aks-operator/blob/9f74df71fab3e021de190208de835e41435e179a/go.mod#L15

https://github.com/rancher/wrangler/releases/tag/v0.8.10

**Comment by thedadams** [comment]
### Root cause
The wrangler dependency needed to be bumped in each of the 3 operators because it was causing compilation errors in Rancher.

### What was fixed, or what changes have occurred
The Wrangler dependency was bumped.

### Areas or cases that should be tested
Provisioning a cluster in each hosted provider is enough. As long as the operator is deployed successfully and is able to deploy a cluster, then everything is OK.

### What areas could experience regressions?
Only running the operator.

### Are the repro steps accurate/minimal?
N/A

**Comment by snasovich** [comment]
@cmurphy , please validate this one as you're most familiar with all of GKE/EKS/AKS and probably have access to all. Thank you in advance.

**Comment by cmurphy** [comment]
Validated on v2.6-head (`CATTLE_SERVER_VERSION=v2.6-39cecf0e10194bcb57190cd3ffc72ef38b728aa7-head`):

1. Created hosted clusters in EKS, GKE, AKS.
2. Clusters become active :heavy_check_mark: 
3. Created clusters external from provider consoles
4. Registered clusters from EKS, GKE, AKS
5. Clusters become active :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/1220710/146428235-cdc5b17a-1a74-411e-abad-4d802a305708.png)

Checked operator versions are correct:

```
955abbe57247:/var/lib/rancher # kubectl -n cattle-system get deploy aks-config-operator -o yaml | grep image:
        image: rancher/aks-operator:v1.0.3-rc2
955abbe57247:/var/lib/rancher # kubectl -n cattle-system get deploy eks-config-operator -o yaml | grep image:
        image: rancher/eks-operator:v1.1.2-rc3
955abbe57247:/var/lib/rancher # kubectl -n cattle-system get deploy gke-config-operator -o yaml | grep image:
        image: rancher/gke-operator:v1.1.2-rc3
```
