### ISSUE TITLE
Rancher 2.6.2 upgrade 2.6.3 cluster down.

### ISSUE THREAD

**Issue by oguzhansrky** [rancher/rancher#35955]
Rancher
RKE 1 v1.21.7-rancher1-1
Docker Version 20.10.12
[486e95fbfe82099b72326d1d70660bb18d9873aa325ce81adbd29e3a0808cca6-json.log](https://github.com/rancher/rancher/files/7765094/486e95fbfe82099b72326d1d70660bb18d9873aa325ce81adbd29e3a0808cca6-json.log)

As I did in previous versions, the existing container and image are removed and the rancher command is run.

I've used this update style at least 100 times and it hasn't been a problem so far.

Use command: 

docker run -d --restart=unless-stopped \
  --name=rancher \
  -v /opt/rancher/var/lib/rancher:/var/lib/rancher \
  -v /opt/rancher/var/log:/var/log \
  -v /opt/rancher/var/lib/cni:/var/lib/cni \
  -v /opt/rancher/var/lib/kubelet:/var/lib/kubelet \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:stable

**Comment by ajacques** [comment]
I also encountered an issue from v2.6.2 -> v2.6.3 where all (5) of my clusters were missing from Rancher UI, but the clusters continued running in the background and I had to restore a backup to go back to v2.6.2 to recover them.

**Comment by oguzhansrky** [comment]
Hi,

If I didn't have a spare, I would already sit and cry. :)

I tried it with a clean install in my test environment, it doesn't work on it either.

For your information

**Comment by pangliang** [comment]
same issue !!

**Comment by mecseid** [comment]
Looks the same as https://github.com/rancher/rancher/issues/35956

**Comment by pangliang** [comment]
Delete ${rancher_dir}/k3s/server/db/etcd  and ${rancher_dir}/k3s/server/db/snapshots, Rollback to 2.6.2, Can be solved temporarily

**Comment by niusmallnan** [comment]
It seems that this issue happens in the single node installation.

My setup local-host-data-dir is `/opt/rancher`, which is a rancher volume mountpoint for `/var/lib/rancher`.
```
cd /opt/rancher
mkdir -p k3s/server/db/etcd
cp -rf management-state/etcd/member k3s/server/db/etcd/
```
Then, upgrade your rancher to 2.6.3. This works well for me.

**Comment by l3system** [comment]
For already updated cluster I had to do the following:
stop rancher container
    cd /opt/rancher
    rm -rf k3s/server/db/etcd
    cp -rf management-state/etcd/member k3s/server/db/etcd/
start rancher container

I need to reset the admin password since the 2.6.3 update made me change, and now I dont have the original/restored one:
    docker exec -ti rancher-container-id reset-password

**Comment by snasovich** [comment]
Likely caused by https://github.com/rancher/rancher/issues/33850

**Comment by snasovich** [comment]
Update: This is indeed caused by https://github.com/rancher/rancher/issues/33850 and is **only reproducible when `/var/lib/rancher` volume is bound to host**.

The issue stems from the fact that when this is done there is no `/var/lib/rancher/etcd` folder in the running container so the etcd data is only in `/var/lib/rancher/management-state/etcd` and not in `/var/lib/rancher/etcd` (when the referenced folder exists the following code creates symlink: https://github.com/rancher/rancher/blob/d3f98065499849a81f14704d7550b24126b8cd5b/main.go#L205-L213).

The folder exists in the container (see https://github.com/rancher/rancher/blob/d3f98065499849a81f14704d7550b24126b8cd5b/package/Dockerfile#L6) but is replaced when the volume is bound.

Because of this the commands to handle migration do not execute: https://github.com/rancher/rancher/blob/d3f98065499849a81f14704d7550b24126b8cd5b/package/entrypoint.sh#L9-L13).

Most likely just using `/var/lib/rancher/management-state/etcd` instead of `/var/lib/rancher/etcd` in this script would suffice. Note that when volume is NOT bound, `/var/lib/rancher/management-state/etcd` is symlink to `/var/lib/rancher/etcd`; but when it's not bound `/var/lib/rancher/management-state/etcd` ends up being a directory.

We should also fix the code that creates `etcd` symlink as etcd data is no longer under `/var/lib/rancher/management-state/etcd` but instead under `/var/lib/rancher/k3s/server/db/etcd`.

At this time the recommendation is to use the workarounds provided above until the issue is resolved in the next release.

**Comment by pacholoamit** [comment]
Thank God, I thought I was going insane... I had a heart attack

**Comment by pacholoamit** [comment]
I tried this solution but when I ran Rancher v2.6.3 I still only see the local cluster.

> For already updated cluster I had to do the following:
> 
> * stop rancher container
> 
> ```
> cd /opt/rancher
> rm -rf k3s/server/db/etcd
> cp -rf management-state/etcd/member k3s/server/db/etcd/
> ```
> 
> * start rancher container
> 
> I need to reset the admin password since the 2.6.3 update made me change, and now I dont have the original/restored one:
> 
> ```
> docker exec -ti rancher-container-id reset-password
> ```

**Comment by snasovich** [comment]
@pacholoamit , could you provide the full `docker run` command you're using to run Rancher?

**Comment by snasovich** [comment]
As a fix, we likely want script in entrypoint.sh changed to use `management-state/etcd` instead of `etcd` and remove `migrateETCDlocal` func as it doesn't do anything now since change to Dockerfile in 2.6.3 as we no longer create `/var/lib/rancher/etcd`.

**Comment by gaby** [comment]
I have the same issue as @pacholoamit . Was able to get Rancher 2.6.3 running, but we can't access any of our k8s clusters. 

How is it possible that Rancher broke something like this in a Patch release? 

I was able to downgrade with:

```
Stop Rancher Service
rm -rf ${rancher_dir}/k3s/server/db/etcd
rm -rf ${rancher_dir}/k3s/server/db/snapshots
Start Rancher
```

**Comment by gaby** [comment]
@nickgerace @MbolotSuse @annablender  The changes from https://github.com/rancher/rancher/issues/33850 and https://github.com/rancher/rancher/pull/35323  were not properly tested and broke upgrade path from 2.6.2 to 2.6.3

**Comment by nickgerace** [comment]
Hi @gaby, while I no longer work at SUSE (Rancher Labs), did the test case ID no.4 steps align with your upgrade process?
https://github.com/rancher/rancher/issues/33850#issuecomment-990244584

**Comment by annablender** [comment]
https://github.com/rancher/rancher/issues/33850#issuecomment-990244584 step no. 4 is closest to their upgrade process, but did not check upgrade of single node Rancher with bind mounted volumes. The bind mounted volumes overwrote `/var/lib/rancher/etcd,` breaking the etcd data migration.
 
PR with a fix has been opened.

With this fix, the following retains downstream clusters, and cluster data
1) Single node Rancher upgrade 2.6.2 -> 2.6.3
2) Single node Rancher upgrade 2.6.2 -> 2.6.3 (with bind mounted volumes)

Test plan
1. Build local Rancher image and push to Docker
2. Run Rancher 2.6.3
    - Create RKE1 DO 2 node downstream cluster
    - Create a deployment
    - Create a secret
3. K3s single node upgrade 2.6.2 -> local Rancher image PASS
4. Repeat steps 2-3 for 2.6.2 with bind mounted volumes PASS

<img width="1544" alt="Screen Shot 2022-01-06 at 4 02 47 PM" src="https://user-images.githubusercontent.com/12955547/148454437-33b8b803-a862-47a4-b6c6-5f92f1bad4e6.png">

<img width="725" alt="Screen Shot 2022-01-06 at 4 02 19 PM" src="https://user-images.githubusercontent.com/12955547/148454453-aea8c44e-9178-4840-9b94-9b48c3b5ce19.png">

**Comment by gaby** [comment]
@annablender Thank you for the extensive explanation. Yes the use case you mention is the one that caused my problem. 

I'm able to get Rancher to start, but Cluster are missing even with fix by: @l3system @pangliang @niusmallnan

**Comment by snasovich** [comment]
@gaby , are you binding `/var/lib/rancher` to the host's folder? If so, what are the contents of this folder (folder names and enough) after applying the workaround suggested and running Rancher 2.6.3 on top of it?

**Comment by gaby** [comment]
I'm running rancher with:

`
-v /opt/rancher:/var/lib/rancher
`

After running the upgrade I have two both:

`
/opt/rancher/k3s/server/db/etcd
/opt/rancher/management-state/etcd/member
`

**Comment by benzman81** [comment]
@snasovich same here, workaround does not work. Cluster still not visible.

Rancher is started with:
`docker run -d --privileged --name rancher-server --restart=unless-stopped -p 8080:80 -p 8443:443 -e CATTLE_BOOTSTRAP_PASSWORD=xxx -v /opt/rancher:/var/lib/rancher rancher/rancher:v2.6.3`

Folders in /opt/rancher are `k3s` and `management-state`.

We use a single node docker install (server and node in the same VM) and rancher was previously started using the same command but wirh `v2.6.3`.

**Comment by benzman81** [comment]
Just to add, the workaround for after an update by @l3system does not work. The workaround by @niusmallnan to do additional stuff before an upgrade works in my test environment.

**Comment by benzman81** [comment]
Last note: I upgraded to 2.6.3 and the cluster was gone. Then I uses the rollback described by @pangliang to get back 2.6.2 which also worked. Then I applied the upgrade path by @niusmallnan and 2.6.3 successfully showed the cluster. Dont know what side effects are there, but for now its working.

**Comment by snasovich** [comment]
@benzman81 , thank you for additional information.

@gaby , could you please try the steps suggested by @benzman81 in the previous comment?

The gist is that for 2.6.3 `member` folder containing etcd data is expected in `/var/lib/rancher/k3s/server/db/etcd` instead of `/var/lib/rancher/management-state/etcd`. If that's the case (you have `member` folder in `/var/lib/rancher/k3s/server/db/etcd` with the content that is/was in `/var/lib/rancher/management-state/etcd`), please try creating `name` file with `default` content in `/var/lib/rancher/k3s/server/db/etcd` as that's what the migration script does: https://github.com/rancher/rancher/blob/d3f98065499849a81f14704d7550b24126b8cd5b/package/entrypoint.sh#L12

**Comment by gaby** [comment]
Should I at this point wait for the next patch release? I tried several of the workarounds here and none work. My Rancher instance has been running since 2019, we always apply updates on release day.

**Comment by snasovich** [comment]
@gaby , I'm sorry to hear none of the workarounds worked for you. Upgrading to the upcoming 2.6.4 from 2.6.2 should not have the same issue. However, please note:
* At this time we're not ready to share 2.6.4 release date
* If as part of applying workarounds you've modified files/folders under the host's folder that is bound to `/var/lib/rancher`, you want to make sure these changes are reverted. At minimum we want to ensure there is no `/var/lib/rancher/k3s/server/db/etcd` folder for this script to properly run the migration:
https://github.com/rancher/rancher/blob/3fc44ba6ca156581930e1d836334ac48e6b80707/package/entrypoint.sh#L9

**Comment by annablender** [comment]
QA test template

### Root cause

The `/var/lib/rancher/etcd` folder was being overwritten on upgrade from Rancher 2.6.2 to 2.6.3 for clusters running with bind mounted volumes.
 
### What was fixed, or what changes have occurred

Code changes
- etcd migration code now migrates data from `management-state/etcd` dir instead of `etcd` https://github.com/rancher/rancher/blob/3fc44ba6ca156581930e1d836334ac48e6b80707/package/entrypoint.sh#L9
- EtcdMigrateLocal was removed
 
### Areas or cases that should be tested

- Single node Rancher upgrade 2.6.2 -> latest
- Single node Rancher upgrade 2.6.2 -> latest (with bind mounted volumes)

See https://github.com/rancher/rancher/issues/35955#issuecomment-1006947403
 
### What areas could experience regressions?
 
### Are the repro steps accurate/minimal?

**Comment by valterm** [comment]
After trying @niusmallnan 's workaround, rancher won't launch at all. 
The container keeps restarting every 10> seconds, with no output whatsoever. If ran in foreground, it hangs for a couple of seconds, then exits without any output. 

Would there be a way to check for any logs? Is it worth trying to dig down into this, or should we wait for the next release?

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**

Rancher version: v2.6.2 upgrade to --> 2.6.3
Downstream cluster: node driver: ec2 k8s: v1.21.8
Rancher installation: Docker single node

**Steps for Reproduction**
1. After provisioning a cluster in 2.6.2 return to the terminal and within the shell we have rancher installed on proceed with the docker upgrade. 
2. Use version v2.6.3 for the upgrade
3. Return to your rancher server's url and notice that the downstream cluster no longer "exists" in your rancher setup. 

**Setup for Validation**
Rancher version: v2.6.2 upgrade to --> 2.6-head(4763f8d)
Downstream cluster: node driver: ec2 k8s: v1.21.8
Rancher installation: Docker single node

**Steps for Validation**
1. After provisioning a cluster in 2.6.2 return to the terminal and within the shell we have rancher installed on proceed with the docker upgrade. 
2. Use version v2.6-head(4763f8d) for the upgrade
3. Return to your rancher server and the downstream cluster is now listed as it should be. 

**Sanity Checks**

- upgrade with bind mounted volumes: PASS
- upgrade with created secrets: PASS

**Comment by roderickgreen** [comment]
Can I point out that the :latest tag *still* points to a version that destroys data? I lost a cluster to this just a few days ago.
