### ISSUE TITLE
Issue in Monitoring v1 graphs - All metrics show the same graph and CPU/Memory usage is incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35995]
**Rancher Server Setup**
- Rancher version: 2.5.12-rc2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s `v1.20.13+k3s1`

**Information about the Cluster**
- Kubernetes version: `v1.20.13+k3s1` imported cluster - Downstream

**Describe the bug**

**To Reproduce**

- Deploy k3s HA cluster - 3 server, 3 worker nodes using v1.20.13+k3s1 version
- Deploy Rancher on this setup - 2.5.12-rc1
- Import a k3s HA cluster in rancher with v1.20.13+k3s1 version
- Deploy Rancher 2.5.12-rc1 on this
- Enable monitoring v1 on this cluster.
- On the cluster dashboard verify the graphs

<img width="1274" alt="Screen Shot 2021-12-30 at 9 44 41 AM" src="https://user-images.githubusercontent.com/26032343/147777270-39790195-39a0-4c84-9bfb-7cf3aa8526f6.png">

<img width="1276" alt="Screen Shot 2021-12-30 at 10 21 44 AM" src="https://user-images.githubusercontent.com/26032343/147778360-c3d11f4d-8d94-4600-a28f-b2a87380a884.png">

**Result**
- The graphs are all same for the cluster as ^^^
- CPU and memory used also seems incorrect
- Similar to what Arvind found [here](https://github.com/rancher/rancher/issues/35760#issuecomment-994263833)

**Expected Result:**
The metrics graphs should not be the same. 

**Note:**
- Happens on an AWS node driver downstream cluster on 2.5.12-rc12 also.
- This issue is not seen on 2.5.11 rancher server (custom downstream cluster; RKE1 HA local cluster; monitoring v1 enabled)

**Comment by slickwarren** [comment]
reproduced on 2.5.12-rc1
confirmed that this issue is fixed on 2.5-head (edf83d5f6d2041217f9e543743d69246fe18afa7) by doing the following:
* Deploy k3s HA cluster - 3 server, 3 worker nodes using v1.20.13+k3s1 version
* Deploy Rancher on this setup - 2.5-head
* Import a k3s HA cluster in rancher with v1.20.13+k3s1 version
* Enable monitoring v1 on this cluster.
* On the cluster dashboard verify the graphs -- pass

<img width="921" alt="Screen Shot 2022-01-03 at 2 43 20 PM" src="https://user-images.githubusercontent.com/16691014/147988338-12ee9b95-131d-405f-b757-84bf4b0e226a.png">
