### ISSUE TITLE
RKE(1) unnecessarily causes DOS when generate_serving_certificate is set to true for the kubelet

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36025]
When a Rancher installation with a large number of downstream provisioned RKE1 nodes comes back online, it is possible to accidentally/inadvertently DOS the installation.

The overview of this issue is that when a large number of node agents all connect to Rancher at once, it can cause a CPU DOS as Rancher will unnecessarily generate a large number of kubelet serving certificates. This can be seen in the logs if the Rancher log level is set to `debug`.

The code snippet that causes this issue can be seen here: https://github.com/rancher/rancher/blob/v2.6.3/pkg/rkenodeconfigserver/nodeserver.go#L207-L213 

The general gist of the situation is that "expected behavior" is to automatically generate a new kubelet certificate/key for a node agent connection, and have the downstream node agent determine whether or not it needs to apply the new kubelet certificate to the local node. Evidence of this expected behavior can be found here: https://github.com/rancher/rancher/issues/24942#issuecomment-574784471

This behavior should be changed as it is not scalable at large loads.

I would say an easy reproducer for this is to create 30 clusters, each with 10 nodes per cluster. Every cluster will need to be configured with the `kubelet` option `generate_serving_certificate: true` i.e. like: https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet . When Rancher is completely shut down (scaled to 0) then scaled back up, it will be possible 

Depending on the mitigation/change of behavior, this may need to be backported to prior minor release lines of Rancher.

SURE-3089

**Comment by snasovich** [comment]
This needs design and discussion within the team before we can proceed. _Planning_ to do that next week.

**Comment by snasovich** [comment]
@HarrisonWAffel to work on the initial design proposal for this.

**Comment by slickwarren** [comment]
waiting on design/more info to assign QA

**Comment by HarrisonWAffel** [comment]
### Root cause
Rancher was generating new kubelet serving certificates for each node agent reconnection. Additionally it was needlessly generating many certificates at a time, one for each host, whereas only one was needed.

### What was fixed, or what changes have occurred
 The node agent now determines if the current certificate needs to be rotated and will indicate to the Rancher server if so. A new certificate will be generated if `generate_serving_certificate` is set to `true` and any of the following conditions apply 

1. The certificate does not exist on the host 
2. The current certificate does not match the hosts IP address or hostname 
3. The current certificate will expire in less than 3 days 

### Areas or cases that should be tested
This issue requires that you have the ability to stop/scale down rancher to 0 pods. We are interested in the reconnection process once an existing Rancher server is brought back online. Any setup in which you can restart Rancher will work, but an HA setup will likely be the easiest configuration. While this fix addresses a scaling issue, it can be tested on a smaller scale using a single cluster with 3 nodes. Some of the above conditions are difficult to test (e.g. expiry time, as certs are valid for 10 years) but the below test cases address the most common behavior contributing to this issue.

#### Test Environment / Setup
+ Create an RKE1 cluster with three nodes 
  + one of the nodes will have the etcd control plane roles 
  + two of the nodes will only have the worker role 
+ Before creating the cluster, edit the YAML and find the `services` section. Add the `generate_serving_certificate` [as described in this documentation ](https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet)
+ Create the cluster and wait for all nodes to come online. Once they've come online, double check the config YAML and ensure that `generate_serving_certificate` is set to `true`. 

#### 1) Certificate should not regenerate on each reconnection

+ SSH into one of the worker only nodes and navigate to `/etc/kubernetes/ssl`. You should see several `.pem` files with the following naming convention `kube-kubelet-<IP_ADDRESS>.pem` and `kube-kubelet-<IP_ADDRESS>-key.pem`. Mark the time at which these files were created using `ls -l`. Make sure you mark the file which belongs to current node you are SSH'd into 
+ Scale down / restart the rancher server and wait for all nodes to reconnect
+ Ensure that no certificates have been updated by checking the file creation time

#### 2) Certificate should be recreated when deleted
+ SSH into one of the worker only nodes and navigate to `/etc/kubernetes/ssl`. Delete the `kube-kubelet` certificate and key which belongs to the node you are SSH'd into (the file name will include the nodes IP address)
+ scale down / restart the rancher server and wait for all nodes to reconnect 
+ ensure that the deleted files have been recreated and are present on the node
+ Also ensure that no other certificate files have been updated or modified

### What areas could experience regressions?
We should make sure that general cluster functionality is working as expected, such as the ability to deploy workloads, charts, metrics, etc. In my testing I did not see any issues but a more thorough check would be useful. 
  
### Are the repro steps accurate/minimal?
Yes

**Comment by slickwarren** [comment]
tested on v2.7-head (5df9701):
Local Cluster (running rancher) setup:
* rke2 cluster (1.24.8+rke2r1), 3 server nodes, 0 worker nodes
* valid certificates installed for accessing rancher

Downstream cluster:
* rke1 linode node driver (1.24.8-rancher1-1) 
  * 1 cp/etcd node, 2 worker nodes
  * `services: kubelet: generate_serving_certificate: true` set
  * verified that both public and private IPs are set through rancher
Case 1: **FAIL**
when scaling down, then back up, the rancher pods on the local cluster, the `kube-kubelet-<ip_of_node>.pem` files are being recreated. I do see `nodeConfig: node agent has requested new kubelet certificate and VerifyKubeletCAEnabled is true, generating kubelet certificate for [public_node_ip]` in the rancher server debug logs
here is a docker inspect of a node that had its certs refreshed: 
```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-12-19T19:31:03.477521388Z",
            "FinishedAt": "2022-12-19T19:31:05.3451889Z"
        },
        "Image": "sha256:43c927a4170ae75f60c3a9002e6e68e358b68e638761e6fc3e1668689989cc67",
        "ResolvConfPath": "/var/lib/docker/containers/3fcf57244a66a77bf5b32f0f5d90099b1a9425d70890bcf43ae7415e5fe8c5c7/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/3fcf57244a66a77bf5b32f0f5d90099b1a9425d70890bcf43ae7415e5fe8c5c7/hostname",
        "HostsPath": "/var/lib/docker/containers/3fcf57244a66a77bf5b32f0f5d90099b1a9425d70890bcf43ae7415e5fe8c5c7/hosts",
        "LogPath": "/var/lib/docker/containers/3fcf57244a66a77bf5b32f0f5d90099b1a9425d70890bcf43ae7415e5fe8c5c7/3fcf57244a66a77bf5b32f0f5d90099b1a9425d70890bcf43ae7415e5fe8c5c7-json.log",
        "Name": "/share-mnt",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/run:/var/run",
                "/etc/kubernetes:/etc/kubernetes"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/d171fac0efbb5b0a94153d9eaf3b71beb5ce17e28569dfe5355bbeace4a94acf-init/diff:/var/lib/docker/overlay2/3394e3ac25106476209ead4d644b86c9d75db06ff741b8e11e41ec79bed68f88/diff:/var/lib/docker/overlay2/78c893fc8f5533f306e750e6d4079d6ec3edbdebcd6c6e38f3b3a50d8da2dbb4/diff:/var/lib/docker/overlay2/09529b11809b00623cd07623dbc92a3bc4cbdb3059abe00746c13fa529559ec3/diff:/var/lib/docker/overlay2/a3c32e60aacc16d592c862cd6e9e874bf8b6e0d78186fad4859342db6058b5cc/diff:/var/lib/docker/overlay2/fba5cd33b5f9001696aed92a57a09d02d77efc7963220a072b09f2bd0e438e01/diff:/var/lib/docker/overlay2/a68d4dfc9d3469e7ab85884c2df28fa635650d647dfceb56bab7917b0d92e4cf/diff:/var/lib/docker/overlay2/a144bacdb74016338afb6cae6e68770365b0393d0ca5477c92eacca20f4e0973/diff",
                "MergedDir": "/var/lib/docker/overlay2/d171fac0efbb5b0a94153d9eaf3b71beb5ce17e28569dfe5355bbeace4a94acf/merged",
                "UpperDir": "/var/lib/docker/overlay2/d171fac0efbb5b0a94153d9eaf3b71beb5ce17e28569dfe5355bbeace4a94acf/diff",
                "WorkDir": "/var/lib/docker/overlay2/d171fac0efbb5b0a94153d9eaf3b71beb5ce17e28569dfe5355bbeace4a94acf/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/run",
                "Destination": "/var/run",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/kubernetes",
                "Destination": "/etc/kubernetes",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "ctw-hw2",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "KUBECTL_VERSION=v1.23.6",
                "LOGLEVEL_VERSION=v0.1.5",
                "AGENT_IMAGE=rancher/rancher-agent:v2.7-5df9701e63e148e64c949f49fe768d56ccdfa9b5-head",
                "SSL_CERT_DIR=/etc/kubernetes/ssl/certs"
            ],
            "Cmd": [
                "--no-register",
                "--only-write-certs",
                "--node-name",
                "ctw-hw2",
                "--server",
                "https://<rancher_server>/",
                "--token",
                "<token>"
            ],
            "Image": "rancher/rancher-agent:v2.7-5df9701e63e148e64c949f49fe768d56ccdfa9b5-head",
            "Volumes": null,
            "WorkingDir": "/var/lib/rancher",
            "Entrypoint": [
                "run.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.suse.bci.base.created": "2022-12-13T12:53:04.141614726Z",
                "com.suse.bci.base.description": "Image for containers based on SUSE Linux Enterprise Server 15 SP4.",
                "com.suse.bci.base.disturl": "obs://build.suse.de/SUSE:SLE-15-SP4:Update:CR/images/1477b070ae019f95b0f2c3c0dce13daf-sles15-image",
                "com.suse.bci.base.eula": "sle-bci",
                "com.suse.bci.base.image-type": "sle-bci",
                "com.suse.bci.base.lifecycle-url": "https://www.suse.com/lifecycle",
                "com.suse.bci.base.reference": "registry.suse.com/suse/sle15:15.4.27.14.23",
                "com.suse.bci.base.release-stage": "released",
                "com.suse.bci.base.source": "https://sources.suse.com/SUSE:SLE-15-SP4:Update:CR/sles15-image/1477b070ae019f95b0f2c3c0dce13daf/",
                "com.suse.bci.base.supportlevel": "l3",
                "com.suse.bci.base.title": "SLE BCI 15 SP4 Base Container Image",
                "com.suse.bci.base.url": "https://www.suse.com/products/server/",
                "com.suse.bci.base.vendor": "SUSE LLC",
                "com.suse.bci.base.version": "15.4.27.14.23",
                "com.suse.eula": "sle-bci",
                "com.suse.image-type": "sle-bci",
                "com.suse.lifecycle-url": "https://www.suse.com/lifecycle",
                "com.suse.release-stage": "released",
                "com.suse.sle.base.created": "2022-12-13T12:53:04.141614726Z",
                "com.suse.sle.base.description": "Image for containers based on SUSE Linux Enterprise Server 15 SP4.",
                "com.suse.sle.base.disturl": "obs://build.suse.de/SUSE:SLE-15-SP4:Update:CR/images/1477b070ae019f95b0f2c3c0dce13daf-sles15-image",
                "com.suse.sle.base.eula": "sle-bci",
                "com.suse.sle.base.image-type": "sle-bci",
                "com.suse.sle.base.lifecycle-url": "https://www.suse.com/lifecycle",
                "com.suse.sle.base.reference": "registry.suse.com/suse/sle15:15.4.27.14.23",
                "com.suse.sle.base.release-stage": "released",
                "com.suse.sle.base.source": "https://sources.suse.com/SUSE:SLE-15-SP4:Update:CR/sles15-image/1477b070ae019f95b0f2c3c0dce13daf/",
                "com.suse.sle.base.supportlevel": "l3",
                "com.suse.sle.base.title": "SLE BCI 15 SP4 Base Container Image",
                "com.suse.sle.base.url": "https://www.suse.com/products/server/",
                "com.suse.sle.base.vendor": "SUSE LLC",
                "com.suse.sle.base.version": "15.4.27.14.23",
                "com.suse.supportlevel": "l3",
                "io.cattle.agent": "true",
                "io.rancher.rke.container.name": "share-mnt",
                "org.openbuildservice.disturl": "obs://build.suse.de/SUSE:SLE-15-SP4:Update:CR/images/1477b070ae019f95b0f2c3c0dce13daf-sles15-image",
                "org.opencontainers.image.created": "2022-12-19T17:38:27Z",
                "org.opencontainers.image.description": "Image for containers based on SUSE Linux Enterprise Server 15 SP4.",
                "org.opencontainers.image.revision": "5df9701e63e148e64c949f49fe768d56ccdfa9b5",
                "org.opencontainers.image.source": "https://github.com/rancherlabs/embargoed-security.git",
                "org.opencontainers.image.title": "SLE BCI 15 SP4 Base Container Image",
                "org.opencontainers.image.url": "https://github.com/rancherlabs/embargoed-security",
                "org.opencontainers.image.vendor": "SUSE LLC",
                "org.opencontainers.image.version": "15.4.27.14.23",
                "org.opensuse.reference": "registry.suse.com/suse/sle15:15.4.27.14.23"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b78d99e9c6f44c6fe59704dcbb5bb138ed70c4689c3dd33120a3f1d4ff65d1c6",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "f37f89cc2cba688276906a63c794b582bfdde06f4ffa1dc81d003c1b4d078c5c",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
```

**Comment by HarrisonWAffel** [comment]
I was able to reproduce this issue while using Azure as a cloud provider, but not when using AWS or DO. It seems the node agent is being given the private IP address of the node, but all of the certificate files are named using the public IP address. 

Because of this the agent will not be able to perform the cert validity checks and will always request a new certificate. I'm looking into why this is, but this behavior is likely not introduced due to the PR merged for this issue.

**Comment by HarrisonWAffel** [comment]
In the case of Azure, it seems that the NIC resource created for each VM is the root cause of this issue. By putting the NIC into its own resource we are unable to see the external IP address when running `route` on the Azure VM. This is unfortunate, as the node agent installation process relies on the output of `ip -o route get 8.8.8.8` get the nodes external IP address. In the case of Azure, that command will actually output the _private IP_ of the node, not the public IP advertised by the NIC and recorded by Rancher. 

I do not have access to a Linode account to test with, however I would guess a similar situation is occurring there too. Ultimately, the node agent is dependent upon the output of `ip -o route get 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'` to get the external IP address. So, situations where this command does not actually return the external IP address recorded by Rancher will result in the behavior seen during testing.

**Comment by HarrisonWAffel** [comment]
A PR has been merged which should address the remaining issues found in this ticket. I've been able to confirm that the additional logic resolves the IP mismatch issue on Azure, but do not have a Linode account to test with. 

It would be great if this could be retested on both Linode _and_ another provider supported by Rancher (AWS/DO/Azure). If this issue still persists on Linode then I'll need access to a Linode environment I can test with, though I'm fairly sure the additional logic will resolve the issue on Linode as well. 

Moving this ticket back into to-test, everything should be good to test on 2.7-head

**Comment by slickwarren** [comment]
still seeing the same issue from [the last comment](https://github.com/rancher/rancher/issues/36025#issuecomment-1358322515) on v2.7.2-rc1. Sync'd with Harrison and are closer to discovering the root cause.

**Comment by jameson-mcghee** [comment]
During testing on `v2.6.9`, I was able to reproduce a "scaled down" version of this issue when following the Steps to Reproduce. However, during testing on `v2.7-head` (Commit ID: da810a7) I was unable to reproduce this issue. Therefore I am closing this ticket as Done.

**Steps to Reproduce:**
1. Spin up a Rancher server on `v2.7-head` (Commit ID: da810a7)
2. Provision a downstream AWS (or other) Node Driver RKE1 cluster with anode pool with 1 etcd & cp node and a different node pool with 2 workers
  - During provisioning, Edit as YAML, and under `services:` add:
    `kubelet:`
     [indent]`generate_serving_certificate: true`
3. Navigate to the Explorer --> Pods page for the RKE1 cluster
4. Select _All Namespaces_
5. Click the 3-dot button for the `cattle-node-agent-[tagname]` pod for one of the workers, and select _Execute Shell_
6. In the shell navigate, to `etc\kubernetes\ssl`, and run the `ls -l` command
  - Note the Timestamp for the certs
7. Download and export the correct kubeconfig for the local cluster
8. Scale down Rancher by using the `kubectl scale deployment rancher -n cattle-system --replicas=0` command
9. Scale Rancher back up to its previous `replica` value, and refresh the Rancher UI
10.  Click the 3-dot button for the `cattle-node-agent-[tagname]` pod for one of the workers, and select _Execute Shell_
11. In the shell navigate, to `etc\kubernetes\ssl`, and run the `ls -l` command
  - Note the Timestamp for the certs
If the issue is reproducing, you will see the timestamp for some of the cert have be updated, indicating that the certs were recreated. If the issue is resolved, the values will all remain the same after the scale down/up.

**`v2.6.9`:**
![image](https://user-images.githubusercontent.com/13294321/211938572-b1f9e316-d2a6-4002-9d77-99e13b76868b.png)
![image](https://user-images.githubusercontent.com/13294321/211938584-e5ec1756-4d70-4074-85a9-881979a8df51.png)

**`v2.7-head` (Commit ID: da810a7):**
![image](https://user-images.githubusercontent.com/13294321/211938680-3494b298-8be1-4483-b9e0-682c89378016.png)
![image](https://user-images.githubusercontent.com/13294321/211938689-adfc34e7-9746-4bfb-87c4-5e7a8fceb28b.png)
