### ISSUE TITLE
instances get stuck in purge and volume stuck in deactivate sometimes

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3604]
Sometimes during validation and/or upgrade testing its possible to get instances stuck in purging and a corresponding volume stuck in deactivating (with volumeStoragePoolMap failing to remove).

This needs fixed.

To test, you basically just need to run validation tests and verify that no containers are stuck in purging and no volumes are stuck in removing.

**Comment by DanielDent** [comment]
I'm glad you see this issue in testing, because I see it in production :)

I have volume.purge and instance.remove processes which have been stuck anywhere between 2 and 6 days. The volume.purge processes have "UNKNOWN_EXCEPTION" exit reason, and I suspect the underlying cause is that sometimes docker aufs volumes don't remove when you ask them to.

**Comment by sangeethah** [comment]
Tested with latest build from master. 
After executing Validation test runs , there were no containers are stuck in "purging" state , all the deleted containers were in "purged" state.

Volumes relating to deleted containers are all in "purged" state.
