### ISSUE TITLE
[RKE2 Cluster Provisioning] Removing RKE2 Addon Config does not remove resource in cluster

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#36068]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3s  v1.21.8+k3s1 
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: v1.21.7+rke2r2 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 Custom or with infrastructure provider

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
   
**Describe the bug**
Removing a resource from the RKE2 addon config does not remove the resource in the cluster.

**To Reproduce**
* Create a cluster with an addon configuration manifest like
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: Deployment
```
* Wait until the cluster is create and check that the manifest has been added to the cluster
* Edit the cluster configuration and remove the addon configuration
* Wait until the cluster configuration change has been applied

**Result**
The resource from the deleted addon configuration is still present in the cluster.

**Expected Result**
The resource from the deleted addon configuration should be deleted.

**Screenshots**

**Additional context**
Editing the addon configuration works correctly, the resources are updated. Just the deletion does not work.
When you remove the addon configuration, the `/var/lib/rancher/rke2/server/manifests/addons.yaml` is correctly cleared, but the resource remains in the cluster.

**Comment by ron1** [comment]
@bashofmann The HelmChartConfig resource is only responsible for customizing the configuration of the addon. It is the presence of the HelmChart resource in the kube-system namespace of the cluster that results in creation of the corresponding workload. So, it makes sense that the removal of the HelmChartConfig resource would only undo the customizations defined in its spec.valuesContent. If/when the HelmChart resource itself is deleted should the workload be removed. Do you agree?

**Comment by bashofmann** [comment]
Yes certainly. But the bug is that if you delete the file from `/var/lib/rancher/rke2/server/manifests`, the resource is not removed from the cluster. Instead of a helmchartconfig you could also put a deployment in there. Adding a deployment.yaml file will create the deployment in it, but removing the file will not remove the deployment.

**Comment by ron1** [comment]
Thanks for the clarification. I did not get that from the issue description.

Are you proposing a change to Rancher RKE2 Cluster Provisioning or are you proposing a change to how RKE2 itself responds to file removals from directory `/var/lib/rancher/rke2/server/manifests`? I suspect RKE2 takes a conservative approach here when it comes to files removals from this directory. The fact that RKE2 requires an explicit removal of a HelmChart resource from the cluster seems reasonable to me. Of course, the manifests would need to be deleted from the manifests directory on all control plane nodes so that a subsequent restart of any of the nodes does not try to re-add the resource. 

Since Rancher RKE2 Cluster Provisioning is declaratively describing the RKE2 cluster, it seems reasonable that it would take care of removing the obsolete HelmChart from the cluster and updating the manifests directory. Is this what you are proposing?

**Comment by bashofmann** [comment]
Yes, at lest for Rancher provisioned clusters the current behaviour is not what I'd expect.

I think Fleet for example wraps all Kubernetes manifests that it deploys from a git repo to clusters internally into a helm chart, so that it can also remove the resources again when a file is removed from git.

**Comment by Martin-Weiss** [comment]
I see two challenges with "file delete = CRD object delete":

1. what if we have multiple masters where the same files exist? (having them on a single master only might be single point of failure)

2. how to prevent / block uninstall of some applications i.e. of longhorn?

**Comment by PeterSR** [comment]
Sorry for reviving this again, but even if there is no automatic "file delete = CRD object delete", how can I delete all manifests from an addon manually?
