### ISSUE TITLE
Add node metrics permissions to cluster members

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#36116]
**Rancher Server Setup**
- Rancher version: v2.6.3

**Information about the Cluster**
- Kubernetes version: v1.21.7+rke2r2
   
**Description**
When log in as a cluster member and go to the cluster dashboard, I cannot see CPU/memory usage.
![image](https://user-images.githubusercontent.com/5697937/149049760-d7613ec6-dd41-408e-b8c4-5627408c9a80.png)

Cluster members can view nodes. I think they should be able to view node metrics by default, so that they can see the usage:
![image](https://user-images.githubusercontent.com/5697937/149050082-62c62b4f-b497-46aa-99ff-ea798bbd5036.png)

**Addditional Context**
It would be nice if cluster members can view nodes.longhorn.io resource by default so that they can see disk usage. This is useful for the Harvester use case.

**Comment by MbolotSuse** [comment]
Validation template:

Root cause

Cluster members were not given permissions to read `node/nodemetrics` resources in the `metrics.k8s.io` api group.


What was fixed, or what changes have occurred

The role template for the `Cluster Member` role was changed to grant read permissions `get, list, watch` to the `node, nodemetrics` resources in the `metrics.k8s.io` api group.


Areas or cases that should be tested

Cluster member permissions. It should be validated that users can now see node metrics through the UI for clusters that they have the `Cluster Member` role on (and only those clusters).

What areas could experience regressions ?

The `Cluster Member` cluster role (as well as any automation which uses this role).


Are the repro steps accurate/minimal ?
Yes. They are included here for convenience.

1. Run rancher v2.6.3 in local/HA setup.
2. Create/Import a cluster.
3. Create a new user with the `user base` global role.
4. Add the new user to the imported cluster as a `Cluster Member`
5. Observe that the user cannot view resource metrics in the UI (as demonstrated in the screenshot).

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-bfd6a8a9-head` and Rancher `948355c`. Only showing blank reserved Memory and CPU, not used as it does in admin.
## Verification steps
1. Deploy Harvester from ISO in 1 node setup
2. Deploy Rancher in Docker
3. Import Harvester into Rancher
4. Deploy RKE2 cluster on Harvester from Rancher
5. Create base-user user in Rancher
6. Add base-user to cluster members for RKE2 cluster
7. Log out
8. Log in as base-user
9. Check dashboard of RKE2 cluster
![Screenshot from 2022-02-23 17-52-29](https://user-images.githubusercontent.com/83787952/155442483-a30360cb-a67b-45b6-882e-3780650ff96a.png)

The dashboard for that same cluster looks like this with the admin user
![Screenshot from 2022-02-23 17-52-45](https://user-images.githubusercontent.com/83787952/155442504-7cd83b5f-28d2-4908-b17f-8a3c076c53a2.png)

**Comment by noahgildersleeve** [comment]
My previous test was with a stale `v2.6-head` build. Retesting.

Tested in Rancher `v2.6-58e374f9eaa0e96a76298259734348a377b1a186-head` and Harvester `master-bfd6a8a9-head`. Tested with above test steps

> ## Verification steps
> 1. Deploy Harvester from ISO in 1 node setup
> 2. Deploy Rancher in Docker
> 3. Import Harvester into Rancher
> 4. Deploy RKE2 cluster on Harvester from Rancher
> 5. Create base-user user in Rancher
> 6. Add base-user to cluster members for RKE2 cluster
> 7. Log out
> 8. Log in as base-user
> 9. Check dashboard of RKE2 cluster

You can see the CPU and memory now with the base user
![Screenshot from 2022-03-01 10-27-45](https://user-images.githubusercontent.com/83787952/156227629-a84575d6-cd8e-4ecb-8b90-5f0e93ada40a.png)
