### ISSUE TITLE
[2.5.12] Adding https://git.rancher.io/helm3-charts does not result in any charts being returned

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#36120]
See UI issues: https://github.com/rancher/dashboard/issues/4902 and https://github.com/rancher/dashboard/issues/4812

When you add the chart repo `https://git.rancher.io/helm3-charts` with the name` helm3-library` to Rancher using the dashboard UI, the API call to /v1/management.cattle.io.catalogs/helm3-library returns no charts.

In 2.6 this returns the charts from that repository.

In order to resolve the reported UI issue, the backend needs to provide the same behaviour as 2.6.

**Comment by aiyengar2** [comment]
@sowmyav27 we should also check whether this impacts 2.6 and test use cases around that. From what I can tell, we should be able to reproduce this in any 2.6.3-rcX version.

Filed another PR to resolve this issue in 2.6.4

**Comment by aiyengar2** [comment]
For those who encounter this issue, the root cause of this is that the semver library that Rancher uses to compare the constraint string provided in the `catalog.cattle.io/rancher-version` annotation assumes that a constraint string that has no prerelease version (e.g. `<2.6.3`) always returns false for pre-release versions (e.g. `2.5.12-rc2` would return false for that constraint, although semantically it should return true).

Therefore, this should only impact RC / pre-release versions of Rancher and should not impact any version of Rancher that has been officially released.

**Comment by brendarearden** [comment]
Available to test in rancher/rancher v2.5.12-rc4

**Comment by anupama2501** [comment]
Verified 2.5.12-rc4

1. Created aws-event-sources in the ember UI 0.1.1
2. Migrate the app to the dashboard UI by adding the required annotations and the helm3-library repo from apps & marketplace.
3. Verified the app versions reflected are from the catalog that was added 
4. Upgrade went through fine

**Comment by tomasnorre** [comment]
I'm still getting this error with following command. 

```
helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.example.com
```

I'm still a little rusty in helm so might be something that I'm missing, but a pointer would be really helpful.
