### ISSUE TITLE
RKE2 not pulling all images from private registry

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#36137]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2

**Information about the Cluster**
- Kubernetes version:  1.21.7
- Cluster Type (Local/Downstream): Local

   
**Describe the bug**
When configuring an RKE2 cluster with a private registry, most images are pulled using this registry, but fleet-agent, rancher-agent, system-agent, and system-upgrade-controller are not.

**To Reproduce**
- Create a private registry and load all images defined at https://github.com/rancher/rancher/releases/download/v2.6.3/rancher-images.txt
- In Rancher, create an RKE2 custom cluster. Enter the endpoint for the registry created. All other default options are fine.
- Get the registration command (all 3 roles) and run the command on the node.
Wait about 10 minutes for the cluster to get created. 
- Check the images downloaded by running: export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
/var/lib/rancher/rke2/bin/crictl images

**Result**

```
> crictl images
IMAGE                                                                                                    
docker.io/rancher/fleet-agent
docker.io/rancher/rancher-agent
docker.io/rancher/system-agent
docker.io/rancher/system-upgrade-controller
<PRIVATE_REGISTRY_FQDN>/rancher/hardened-cluster-autoscaler
...   
```

**Expected Result**

```
> crictl images
IMAGE                                                                                                    TAG
<PRIVATE_REGISTRY_FQDN>/rancher/fleet-agent
<PRIVATE_REGISTRY_FQDN>/rancher/rancher-agent
<PRIVATE_REGISTRY_FQDN>/rancher/system-agent
<PRIVATE_REGISTRY_FQDN>/rancher/system-upgrade-controller
<PRIVATE_REGISTRY_FQDN>/rancher/hardened-cluster-autoscaler
...   
```

**Screenshots**

**Additional context**

SURE-3856

**Comment by thedadams** [comment]
For the fleet-agent image, this is blocked by https://github.com/rancher/fleet/issues/711

**Comment by thedadams** [comment]
### Root cause
The RKE2 controllers in Rancher were ignoring the cluster's private registry.

### What was fixed, or what changes have occurred
The controllers will now take into account the private registries configured for the RKE2 cluster, if it exists.

### Areas or cases that should be tested
1. From Rancher, provision an RKE2 cluster with a private registry for the Rancher images. Can be a single node cluster.
2. After the cluster is active, SSH to the node.
3. Run the following command: `CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml /var/lib/rancher/rke2/bin/crictl images`
4. The only image that should not be pulled from the private registry is `fleet-agent` (see issue https://github.com/rancher/fleet/issues/711 for the issue there). This includes rancher-agent, system-agent, and system-upgrade-controller images.

### What areas could experience regressions?
Provisioning RKE2/K3S clusters from Rancher.

### Are the repro steps accurate/minimal?
Yes.

**Comment by Josh-Diamond** [comment]
Blocked by https://github.com/rancher/rancher/issues/36939; Unable to provision RKE2 Custom cluster w/ private registry
This ticket is also related to blocker - https://github.com/rancher/rancher/issues/37364

**Comment by Josh-Diamond** [comment]
Ticket #36137 - Test Results

With Helm via HA Jenkins job:

Verified on rancher `v2.6.5-rc1`:
1. Fresh install of rancher `v2.6.5-rc1`
2. Create a standard user
3. As standard user, provision RKE2 Custom cluster with a private registry
4. Verified - With the exception of `fleet-agent`, all other images successfully pulled from private registry

Screenshot:
<img width="1023" alt="Screen Shot 2022-04-18 at 4 47 30 PM" src="https://user-images.githubusercontent.com/46494969/163894092-c11f6176-8f85-40ba-a841-dba42e27284e.png">

**Comment by dnoland1** [comment]
@Josh-Diamond Why was the issue closed if you can still reproduce the issue? If fleet-agent is not using the private registry, it's going to fail in an air-gapped environment.

**Comment by Josh-Diamond** [comment]
@dnoland1 `Areas or cases that should be tested - #4'
https://github.com/rancher/rancher/issues/36137#issuecomment-1089567007

**Comment by thedadams** [comment]
@dnoland1 The fleet-agent being pulled from a private registry is not in Rancher's control. That is handled by fleet-controller and there is nothing Rancher can do to change this at this point.

The issue I linked above from the fleet repository is the one being used to track the fleet-agent changes.
