### ISSUE TITLE
Update k8s versions 1.19.x, 1.20.x, and 1.21.x, to use NGINX v1.1.x

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#36136]
[This](https://github.com/kubernetes/ingress-nginx/tree/controller-v1.1.1#support-versions-table) table states k8s versions 1.19, 1.20, and 1.21 are supported by NGINX v1.1.x, but only 1.22 is using a v1.1.x version. Critical CVEs were addressed in v1.1.x so the other k8s versions need to be updated as well.

Somewhat of a continuation of https://github.com/rancher/kontainer-driver-metadata/pull/712 as we now should be able to  v1.1.0 as https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/templates/nginx-v1.1.0.go template should handle k8s versions prior to 1.22 properly.

SURE-3776

**Comment by rayandas** [comment]
I raised a PR https://github.com/rancher/kontainer-driver-metadata/pull/790 But I have a few queries. 
1. K8s stopped support for `v1.19` so we didn't add a new template in a while. If we want to add `nginx 1.1.0` then we have to add a new template from the latest patch and bump `nginx to 1.1.0`. Is that correct? (or we should avoid updating 1.19?)
2. Do we have to update all the patches of 1.19, 1.20 and 1.20 or only the latest patches (which are not released yet)?
/cc: @PennyScissors @snasovich

**Comment by snasovich** [comment]
@rayandas , thank you for working on this.
On 1, we do want to release a new version of 1.19 line with updated add-on versions. From what I see we have `v1.19.16-rancher1-2` so we want to add `v1.19.16-rancher1-3`.
On 2, since these changes won't make it into the upcoming KDM release that will go out with Rancher 2.5.12 in a few days, they would probably apply to the January 2022 k8s patches - may as well bundle it in the same PR with January patches. That would apply for 1.20 and 1.21 only as for 1.19 we would introduce new `v1.19.16-rancher1-3` without bump to hyperkube/k8s version and for 1.22 we already use nginx 1.1.0.

**Comment by snasovich** [comment]
@kinarashah @PennyScissors , let us know if I misspoke on anything in the comment above. Or like this/previous comment if it looks good.

**Comment by rayandas** [comment]
thanks for the insights @snasovich

**Comment by kinarashah** [comment]
@snasovich Thanks, this sounds good.

**Comment by snasovich** [comment]
@rayandas , I don't believe we close issues until they are tested by the QA. Also, for 2.5 KDM changes do we handle it within the same issue or do you generally expect backport issue to be created to handle it?

**Comment by rayandas** [comment]
Ah! my bad.
For backporting I think there were new issues every time.

**Comment by rayandas** [comment]
@snasovich I raised 2.5 NGINX bump and attached this issue number on it.

**Comment by samkulkarni20** [comment]
@PennyScissors @snasovich Pls confirm if we can follow the same validation steps as used in [this issue](https://github.com/rancher/rancher/issues/35128#issuecomment-955151808). 
CC: @vivek-infracloud

**Comment by snasovich** [comment]
@samkulkarni20 , we want to ensure we no longer default `allow-snippet-annotations` to `false` following the changes.

**Comment by vivek-infracloud** [comment]
**Reopening the issue.**

Verified on v2.6-head KDM pointing to dev-2.6

nginx-ingress-controller - v1.1.0

Created downstream clusters on canal network providers with the k8s versions:

- v1.19
- v1.20
- 1.21

nginx controller logs shows following error.

```E0124 13:19:16.853686 9 leaderelection.go:367] Failed to update lock: configmaps "ingress-controller-leader" is forbidden: User "system:serviceaccount:ingress-nginx:ingress-nginx" cannot update resource "configmaps" in API group "" in the namespace "ingress-nginx"```

Ingress creation failed with following error.
```Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding```

Following error is seen in the ingress-controller logs while trying to create the ingress.
`E0124 13:30:24.967139 7 server.go:82] "failed to process webhook request" err="rejecting admission review because the request does not contain an Ingress resource but networking.k8s.io/v1beta1, Kind=Ingress with name ingresstest in namespace default"`

**Comment by ohauer** [comment]
Maybe this blog post on kubernetes.io gives more advice https://kubernetes.io/blog/2021/07/26/update-with-ingress-nginx/

**Comment by vivek-infracloud** [comment]
**Reopening the issue.**

**Verified on v2.6-head KDM pointing to dev-2.6**

nginx-ingress-controller - v1.1.0

Created downstream clusters on all network providers with the k8s versions:

- v1.19
- v1.20
- v1.21
- v1.22

NGINX ingress is working as expected on k8s versions v1.22. However issue is still active on other k8s versions.

nginx controller logs shows following error.
`E0201 15:48:17.680280 9 leaderelection.go:367] Failed to update lock: configmaps "ingress-controller-leader" is forbidden: User "system:serviceaccount:ingress-nginx:ingress-nginx" cannot update resource "configmaps" in API group "" in the namespace "ingress-nginx"
`

Ingress creation failed with following error.
`Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding
`

**Comment by kinarashah** [comment]
@vivek-infracloud This issue will be present in 2.6-head because of https://github.com/rancher/rancher/issues/36346, please test this on 2.6.3.

**Comment by vivek-infracloud** [comment]
**Verified on v2.6.3 pointing KDM to dev-v2.6**

nginx-ingress-controller - v1.1.0-rancher1

1. Created downstream custom RKE1 clusters on all network providers with the following k8s versions:

- v1.22.6-rancher1-1
- v1.21.9-rancher1-1
- v1.20.15-rancher1-1
- v1.19.16-rancher1-3

2. Created a ingresses, all the ingresses came up active.
3. Verified the `allow-snippet-annotations` is **not set** by default.
4. Ingresses working as expected on all the clusters.
