### ISSUE TITLE
istio-installer with overlay file causes exit 123 error

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#36157]
SURE-3899

Rancher version: 2.5.9
Number of nodes: 3
Node OS version: Ubuntu

Downstream Cluster:
Number of Downstream clusters: 10
Node OS: AmazonLinux AMI (EKS)
RKE/RKE2/K3S version: 1.3.2
Kubernetes version: 1.20.7
CNI: Canal

Longhorn: NA
Longhorn version:
CPU per node:
Memory per node:
Disk type: HDD/SSD/NVMe
Network bandwidth between the nodes:

Other:
Underlying Infrastructure: EKS downstream
Any 3rd party software installed on the nodes:

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Description
Issue description:
Customer is trying to install Istio 1.9.8 on Rancher 2.5.9 with a custom overlay.  Her goal is to choose the tcp nodeport 31370 for the "status-port" section of the ingressGateway under the IstioOperator spec. 

Business impact:
It stops them from automating Istio upgrades, as the custom change would get reverted.  A feature of the chart (overlays) seems like there may be something wrong.

Troubleshooting steps:
I have reproduced with Rancher 2.6.3 (hosted rancher) and a single k3s 1.19 node, installing Istio helm chart 1.11.4 (latest).  We reviewed the spec for the overlay to ensure it is correct.

Repro steps:

Navigate to Apps & Marketplace
Install Istio chart (1.9.8 under Rancher 2.5 or 1.11.4 under Rancher 2.6) & choose overlay file info (see below)
helm operation fails with exit code 123
Workaround:
Is workaround available and implemented? yes
What is the workaround: customer modifies the service after helm install manually

Actual behavior:
Logs show "MODIFIED" for istio-installer but it fails ... error message says Exit Code 123.

Expected behavior:
Helm chart is upgraded/installed with proper overlay values

Files, logs, traces:  See SURE ticket

**Comment by doflamingo721** [comment]
@SheilaghM The overlay file mentioned in the SURE ticket has a typo. The field `targetport` should be `targetPort`  as mentioned in the[ IstioOperatorSpec](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#ServicePort) documentation. Did anyone try using the overlay file with `targetPort` (with capital "P")?

**Comment by rishabhmsra** [comment]
**Validated this on rancher v2.6.3 by following below steps:**
- Created a single node (all role) downstream cluster using k8s `v1.21.8`
- Deployed istio `100.1.0+up1.11.4` with the custom overlay file mentioned in SURE ticket, after correcting the typo in `targetPort` field as mentioned [here](https://github.com/rancher/rancher/issues/36157#issuecomment-1023102896). The istio chart deployed successfully. 


**Note:** 
- On installing istio with the exact overlay file provided in SURE ticket the helm chart installation errors out and this is found in the istioctl job logs :
`Error: failed to generate Istio configs from file [/app/istio-base.yaml /app/overlay-config.yaml], error: unknown field "targetport" in v1alpha1.ServicePort:`

- **Also getting exit code 123 in helm operation:**

![istio-exit-123](https://user-images.githubusercontent.com/36376154/152345922-e5058f60-e368-43fa-bca9-1a2858c3d52d.png)



**Result:**
- This errors seems to occur because of the typo as mentioned [here](https://github.com/rancher/rancher/issues/36157#issuecomment-1023102896).
- After correcting the overlay file, istio deployed successfully, hence closing the issue.

cc: @sowmyav27 @MKlimuszka @SheilaghM

**Comment by johnwc** [comment]
> On installing istio with the exact overlay file provided in SURE ticket the helm chart installation errors out and this is found in the istioctl job logs :
Error: failed to generate Istio configs from file [/app/istio-base.yaml /app/overlay-config.yaml], error: unknown field "targetport" in v1alpha1.ServicePort:

@rishabhmsra I am having a similar issue with a different chart, where do I find this job log that may have a better error message in it?
