### ISSUE TITLE
Fleet: Add Age and last modified metadata for resources

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#36173]
See UI ticket: https://github.com/rancher/dashboard/issues/4683

There is a request to show the age and last modified date of resources in the Dashboard UI for fleet. Currently this data is not available from fleet.

Can we add to the response ofthe `/v1/fleet.cattle.io.gitrepos/WORKSPACE/REPO` API this metadata for each of resources in the resources list.

SURE-4651

**Comment by Jono-SUSE-Rancher** [comment]
@MKlimuszka - Can you have a discussion with @geethub97 or @aiyengar2 to see if this is going to make it into v2.6.6? It's for an associated JIRA and there is a front end ticket that is dependent on this one.

This may also be one that Matt F's team is going to pick up - but if that happens let's make sure it's assigned out properly.

**Comment by kkaempf** [comment]
I'm adding it to Q3 for Fleet, pending coordination with @gaktive. Maybe it can be moved to Q2 🤔

**Comment by gaktive** [comment]
@kkaempf I'll put the corresponding UI ticket in for Q3 for now since UI's feature complete for Q2 is this week and we're dealing with various capacity issues on existing feature work for that release. If you can indicate how testing around this is to be done, that could help sway towards Q2.

**Comment by manno** [comment]
The resources tab exists for 
- gitrepo: shows the .status.resources key
- bundle: shows the .status.resourceKey key

The gitrepo's `resources` key is calculated from the aggregated `resourceKey`s of its bundles. This happens after the bundles are created. The resources that are listed are not the actual resources which were deployed to clusters. It's an early estimation, that doesn't take targeting (bundledeployments) into account.
The actual list of resources can differ, for example because a helm chart uses capabilities to deploy different resources, depending on the k8s version. Also target customizations and overlays may affect the outcome for some clusters.

To provide timestamps and an accurate list (bundle, cluster), we would need to send the helm release information from the downstream cluster and store it on the bundledeployment.

**Comment by kkaempf** [comment]
closing as fixed
