### ISSUE TITLE
[forwardport] etcd backups 'thrash' when multiple backups occur at once (i.e. user starts manual backup, and recurring backup starts before manual backup finishes)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36210]
forward port of rancher/rancher#36209 please see this ticket for more information.

**Comment by jakefhyde** [comment]
### Root cause
Multiple etcd backups could be running at once (including recurring backups), which causes issue when rke tries to create resources with the same name to handle snapshot creation and deletion.
### What was fixed, or what changes have occurred
All backup requests are added to a queue, and will be run in order from oldest to newest. There is also a minor change to ensure that at least the number of `retention` 
 (recurring) backups specified in the spec are actually retained before deleting older backups.
### Areas or cases that should be tested
- Adding multiple backups at the same time sees them finish in order from oldest to newest, running one at a time
- Recurring backups are not created until the previous recurring backup is finished
- Deleting a backup before it has been started
- Deleting a backup after it has been started, but before it has finished
- Deleting a recurring backup when an older backup exists should not delete the older backup until at least `retention` backups exist. (These backups are not required to necessarily be successful, this is a known issue, has always existed, and is not targeted for this release).
### What areas could experience regressions?
N/A
### Are the repro steps accurate/minimal?
Concurrent backups can be tested with a rate-limited nginx proxy to a minio installation. The upload limit does not need to be configured such that the upload takes long (e.g. ~5 min), just sufficiently long enough to be able to queue up multiple backups and observe their behavior. It is also worth noting that the first recurring backup usually is created within the first 5 minutes after a cluster is available, so immediately creating manual backups is a good way to ensure the recurring backup gets queued.

**Comment by slickwarren** [comment]
closing as duplicate of https://github.com/rancher/rancher/issues/36209
