### ISSUE TITLE
Support mounted service account tokens for rancher service monitor

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#36234]
**Is your feature request related to a problem? Please describe.**
It should be possible to use a ranch ServiceMonitor without making a rancher token. This is a step toward adding rancher service metrics to the monitoring chart. It's not absolutely mandatory but it improves the user experience and is arguably more secure since sa tokens expire, in 1.22+ they rotate every hour, while rancher tokens are valid until deleted by default.

**Describe the solution you'd like**
Make it so service account tokens are supported for /metrics requests and bind role for viewing metrics to `rancher-monitoring-prometheus` service account.

**Describe alternatives you've considered**
Having the use created and enter a token themselves.

**Additional context**
For testing, the following steps using the second manifest in step 5 (do not use the first one) should be confirmed to not work prior to fix and should work after the fix: https://github.com/rancher/rancher/wiki/How-to-setup-prometheus-dashboard-for-controllers.

**Comment by rmweir** [comment]
Blocked on second part of this by https://github.com/rancher/dashboard/issues/4988.

**Comment by brudnak** [comment]
# QA Blocked / Reopened 

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-1d2b7468851553f4b89f8af99d74305af9d1b594-head |
| Rancher cluster type    | high availability                                  |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | not applicable                                     |
| Downstream K8s version  | not applicable                                     |
| Browser type            | google chrome                                      |
| Browser version         | 98.0.4758.109 (Official Build) (x86_64)            |

## Validation steps

1. Enable metrics on the Rancher server
    1. Starting from the `default` Rancher homepage `/dashboard/home`
    2. Click `hamburger menu` -> click `local` (under explore cluster) -> click `Workload` -> click `Deployments` -> clear `Only User Namespace` to `All Namespaces` -> right click `rancher` under `cattle-system` Namespace -> click `Edit Config`
    3. Scroll down to `Environment Variables` -> click `Add Variable`
        - Type: `Key/Value Pair`
        - Variable Name: `CATTLE_PROMETHEUS_METRICS`
        - Value: `true`
    4. Click `Save`
    5. Wait for all rancher pods to update
2. Locate the bearer token
    1. Right click one of the updated rancher pods from above -> click `Execute Shell`

```shell
cd ..
cd ..
cd run/secrets/kubernetes.io/serviceaccount/
cat token
```
3. Copy the token
4. Open Postman create a `POST` request to this endpoint `/v1/namespaces` with the following body & and token set as a bearer token under authorization

```json
{
    "type": "namespace",
    "metadata": {
        "annotations": {
            "field.cattle.io/containerDefaultResourceLimit": "{}",
            "field.cattle.io/projectId": "local:p-npw7s"
        },
        "labels": {
            "field.cattle.io/projectId": "p-npw7s"
        },
        "name": "mytest-ns42"
    },
    "disableOpenApiValidation": false
}
```

#### RESULT / ACTUAL

Get a status code of `401` Unauthorized, type `error`. Please see the screen shots labeled `A1` and `A2` below.
  
#### Expected
 I would expect to get a `403`. The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it.


![a1](https://user-images.githubusercontent.com/40877149/156301193-672957dd-c49d-441b-8d2d-f94e3693abf7.png)



![a2](https://user-images.githubusercontent.com/40877149/156301180-d8c98b76-ca3e-4dcf-b185-1bc70e2c648b.png)


<hr>

 ### Additional Testing 1

1. Trying to use kubectl to access the cluster with the token located at `run/secrets/kubernetes.io/serviceaccount/`
2. Run the following commands against the local cluster

```shell
kubectl get nodes --token=$ADD_TOKEN_HERE -v=7
```

#### RESULT / ACTUAL
The nodes are returned and we get an http status code of `200` OK.See the screenshot labeled `A3`


![a3](https://user-images.githubusercontent.com/40877149/156301163-8ab646c1-f72c-4609-81ae-99c40f49fd21.png)

<hr>

#### Expected
For the service account token not to work here.

### Additional Testing 2

1.  Running the additional test above but instead of using kubectl using Postman.
2.  Send a `GET` request to the following API endpoint: `/k8s/clusters/local/api/v1/nodes?limit=500`
3.  Receive back data and a `200` OK status. See screenshot labeled `A4`


![a4](https://user-images.githubusercontent.com/40877149/156301134-e70bd0dd-3dc8-4fb3-8a83-3cdabd3b9a60.png)

#### RESULT / ACTUAL
Getting data back from Postman with the service account token.

#### Expected
I would expect the service account not to work for this endpoint.

**Comment by rmweir** [comment]
@brudnak is this a kubeconfig generated when creating the local cluster or created through rancher?

**Comment by brudnak** [comment]
@rmweir Using the default local kubeconfig located at the screenshot below.

Also though I was able to use Postman with the bearer token located at `run/secrets/kubernetes.io/serviceaccount/` to make a successful GET request to `/k8s/clusters/local/api/v1/nodes?limit=500`. Is that expected? 

![Screen Shot 2022-03-02 at 11 10 21 AM](https://user-images.githubusercontent.com/40877149/156422750-3364bfd0-7658-4f32-9bcf-f9c924050951.png)

**Comment by rmweir** [comment]
@brudnak Those requests use a different authentication path than what I have changed. This behavior was the same prior to the change and therefore is expected and fine. What I changed pertains to requests going through the rancher paths not k8s or the k8s proxy. It would be helpful if you can validate that you also observe that this behavior was the same before.

**Comment by brudnak** [comment]
# My checks PASSED

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-1d2b7468851553f4b89f8af99d74305af9d1b594-head |
| Rancher cluster type    | high availability                                  |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | not applicable                                     |
| Downstream K8s version  | not applicable                                     |
| Browser type            | google chrome                                      |
| Browser version         | 98.0.4758.109 (Official Build) (x86_64)            |

## Validation steps

1. Enable metrics on the Rancher server
    1. Starting from the `default` Rancher homepage `/dashboard/home`
    2. Click `hamburger menu` -> click `local` (under explore cluster) -> click `Workload` -> click `Deployments` -> clear `Only User Namespace` to `All Namespaces` -> right click `rancher` under `cattle-system` Namespace -> click `Edit Config`
    3. Scroll down to `Environment Variables` -> click `Add Variable`
        - Type: `Key/Value Pair`
        - Variable Name: `CATTLE_PROMETHEUS_METRICS`
        - Value: `true`
    4. Click `Save`
    5. Wait for all rancher pods to update
2. Locate the bearer token.

#### Test Cases
1. Unable to use the service account token where it would not be expected. For example the token will not work for creating namespaces, etc. Pass.
2. Enable service monitor Prometheus metrics with the token path was successful `/var/run/secrets/kubernetes.io/serviceaccount/token`

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rancher
    release: rancher
  name: rancher
  namespace: cattle-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
      serverName: rancher
  jobLabel: rancher
  namespaceSelector:
    matchNames:
    - cattle-system
  selector:
    matchLabels:
      app: rancher
      chart: <this should match the rancher service's chart label's value>
      release: rancher
```
  
### Results

 Service token working as expected. Checks passed.
