### ISSUE TITLE
Tenant Cluster in Unavailable state where the Super Rancher setup is on 2.6.3 and Tenant Rancher is 2.5.12

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#36316]
**Rancher Server Setup**
- Rancher version: Managed Rancher (Super is 2.5.3 and Tenant 2.5.12)
- Installation option: Helm
   - If Helm Chart: k3s both Super and Tenant with k8s `v1.20.12+k3s1`
- Proxy/Cert Details: External TLS termination (Layer 7 Load balancer nginx)

**Information about the Cluster**
- Kubernetes version: `v1.20.12+k3s1`
- Cluster Type:  k3s on local and downstream
   - Imported k3s (Tenant cluster) 

**User Information**
- What is the role of the user logged in? `Admin`

   
**Describe the bug**

The Tenant cluster is in Unavailable state after Rancher 2.5.12 is installed in the cluster
The Tenant Rancher UI is accessible through the Server URL and no evident errors are observed.
The Tenant cluster is marked as Unavailable in the Rancher UI with this error: `Cluster agent is not connected`

**To Reproduce**

- Configure k3s cluster with Rancher 2.6.3 HA (three master nodes)
  - Options used: External TLS termination, Valid certificates, External Datastore (Postgres)
- Create a new k3s cluster with the same options as the super and import it (wait for the Active state in the UI)
- Install Rancher 2.5.12 in the Tenant

**Result**

The Tenant cluster is in Unavailable state after Rancher 2.5.12 is installed in the cluster
The Tenant Rancher UI is accessible through the Server URL and no evident errors are observed.
The Tenant cluster is marked as Unavailable in the Rancher UI with this error: `Cluster agent is not connected`

**Expected Result**

Rancher Tenant cluster 2.5.12 is in Active state after installing Rancher and is browsable in the Super Rancher 2.6.3 UI 

**Screenshots**

![Screen Shot 2022-01-28 at 9 12 33 AM](https://user-images.githubusercontent.com/27659/151581998-c4bc9964-0f97-4204-963b-fd21aeb6d8f2.png)

**Additional context**

Error log in Rancher Super 2.6.3

```
[DEBUG] Skip updating cluster condition ready - cluster agent for [c-m-vvhswcxp] isn't connected yet
```

Cattle cluster agent logs in the Tenant Rancher 2.5.12:

```
INFO: https://<REDACTED>/ping is accessible
INFO: <REDACTED> resolves to <REDACTED>
time="2022-01-27T22:33:50Z" level=info msg="Listening on /tmp/log.sock"
time="2022-01-27T22:33:50Z" level=info msg="Rancher agent version v2.6.3 is starting"
time="2022-01-27T22:33:51Z" level=info msg="Connecting to wss://<REDACTED>/v3/connect/register with token starting with 9c572jrngrckpmkrb2wp5xhn6kh"
time="2022-01-27T22:33:51Z" level=info msg="Connecting to proxy" url="wss://<REDACTED>/v3/connect/register"
time="2022-01-27T22:33:51Z" level=info msg="Starting /v1, Kind=Service controller"
E0127 22:37:09.698824      40 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Service: the server is currently unable to handle the request (get services.meta.k8s.io)
E0127 22:37:13.048197      40 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:cattle-system:cattle" cannot list resource "services" in API group "" at the cluster scope
time="2022-01-27T23:18:27Z" level=error msg="Remotedialer proxy error" error="websocket: close 1006 (abnormal closure): unexpected EOF"
time="2022-01-27T23:18:37Z" level=info msg="Connecting to wss://<REDACTED>/v3/connect with token starting with 9c572jrngrckpmkrb2wp5xhn6kh"
time="2022-01-27T23:18:37Z" level=info msg="Connecting to proxy" url="wss://<REDACTED>/v3/connect"
time="2022-01-27T23:18:45Z" level=error msg="Remotedialer proxy error" error="websocket: close 1006 (abnormal closure): unexpected EOF"
time="2022-01-27T23:18:55Z" level=info msg="Connecting to wss://<REDACTED>/v3/connect with token starting with 9c572jrngrckpmkrb2wp5xhn6kh"
time="2022-01-27T23:18:55Z" level=info msg="Connecting to proxy" url="wss://<REDACTED>/v3/connect"
time="2022-01-27T23:18:55Z" level=error msg="Failed to connect to proxy. Response status: 503 - 503 Service Unavailable. Response body: Service Unavailable" error="websocket: bad handshake"
time="2022-01-27T23:18:55Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2022-01-27T23:19:05Z" level=info msg="Connecting to wss://<REDACTED>/v3/connect with token starting with 9c572jrngrckpmkrb2wp5xhn6kh"
time="2022-01-27T23:19:05Z" level=info msg="Connecting to proxy" url="wss://<REDACTED>/v3/connect"
```

**Comment by thedadams** [comment]
@izaac I would be interested to see the `cattle-cluster-agent` deployment on the downstream cluster here. In other situations I have seen the cluster agent not connect, the cause was the `CATTLE_FEATURES` environment variable was not set.

**Comment by thedadams** [comment]
This is expected when Rancher v2.6.x is managing a cluster with Rancher < v2.6.x.

Here is the detailed explanation:
When the `cattle-cluster-agent` runs without Rancher running on the downstream cluster, then the `cattle-cluster-agent` will run an embedded Rancher instance which runs some controllers and makes another websocket connection ([`stv-cluster-CLUSTER_ID`]) which the UI uses to display information.

If Rancher is already running on the downstream cluster, then Rancher is already running these controllers. So, the existing instance of Rancher only needs to make the websocket connection. The `cattle-cluster-agent` will look for the `rancher` service in the `cattle-system` namespace and not run these controllers because they would be running twice on the downstream cluster.

The issue is that in Rancher v2.5.12, Rancher will not make this websocket connection to the management cluster. So the `cattle-cluster-agent` won't run the controllers (which means it will not make the websocket connection) and Rancher will not make the websocket connection. This appears in the dashboard as the cluster agent is disconnected.

This is not the case if the downstream cluster is running Rancher v2.6.x. Also, in the case of the downstream cluster running v2.5.x, the cluster can be managed from the host Rancher via the old (Ember) UI.

**Comment by izaac** [comment]
Closing as wontfix.

This is working fine with Rancher installations on Tenant (downstream) clusters of version 2.6 and Rancher 2.6 as the Rancher manager (super Rancher).
