### ISSUE TITLE
[feature] add configurable src access list to Load Balancer

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3633]
I have had several requests from users to be able to add a firewall to their container, so that they can restrict access to certain subnets.

The easiest way to do this would seem to be to add an optional item to Load Balancer configuration so that you can configure a list of subnets from which connection is allowed.

It may be possible to do this using the defaults section of the custom haproxy.cfg (if so, documentation would be nice), but having the feature built-in on a per-proxy basis would make it much easier to use.

**Comment by vincent99** [comment]
This would fall under https://github.com/rancher/rancher/issues/2179 .. there are a hundred options everybody that needs customization needs a different 2.  So we want 1st class API/yaml fields for the most common things and options to put in your own haproxy config for everything else, rather than being in the business of supporting all hundred.

**Comment by deniseschannon** [comment]
Closing in favor of #2179
