### ISSUE TITLE
Generate Kubeconfig doesn't respect TTL settings

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/rancher#36382]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.21.4+rke2r2

**Information about the Cluster**
- Kubernetes version: v1.21.4+rke2r2
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
When calling generateKubeconfig the Kubeconfig tokens never expire even with the setting `kubeconfig-token-ttl-minutes` set.

**To Reproduce**
1. Set kubeconfig-token-ttl-minutes
2. Generate a kubeconfig either via the api or UI

**Result**

**Expected Result**
The kubeconfig token should expire in set TTL time.

**Additional context**
When looking through the code that backs this API call it simply passes `nil` for the TTL which the functions it calls respects. This same function pulls in the configuration for this and it would be nice if it just used the config value.

It would also be nice if you could specify a TTL at the API endpoint as well to dynamically expire kubeconfigs and could be done in the same change.

**Comment by ADustyOldMuffin** [comment]
Suspected code in question https://github.com/rancher/rancher/blob/75285c91dfcf6883b7a9cb36c61fc70a9cc9eca2/pkg/api/steve/clusters/kubeconfig.go#L76-L95

**Comment by ADustyOldMuffin** [comment]
And another one https://github.com/rancher/rancher/blob/fc01fff137321c3016f7e6c583bf3cb26df03768/pkg/api/norman/customization/cluster/actionhandler.go#L135-L175

**Comment by mateuszdrab** [comment]
I think I just observed the same issue, generated token via UI has no expiration despite settings being set as follows:
`kubeconfig-generate-token: true`
`kubeconfig-token-ttl-minutes: 960`

**Comment by slickwarren** [comment]
I've just tested the following on v2.6.4-rc4:
* as an admin user, download a kubeconfig of the local cluster through the UI
  * verify that <ip>/v1/management.cattle.io.settings/kubeconfig-token-ttl-minutes is set (default value is 960)
    * also checked v3/.../ setting (matches v1) 
  * verify that new token generated from the UI interaction is set to expire -- fail

note- this is also the case for the default value on v2.5.12. No token timeout is set

**Comment by mateuszdrab** [comment]
Hmm, that's quite disappointing. 
Is there a reason why the generated kubeconfig can't respect the configured TTL?
I think generation of never expiring tokens by default is not a good practice and using the CLI to obtain the token is cumbersome - I tried it and it prompted me to login via commandline when I'm using Oauth2. This probably means I need to provide the tool parameters/token to login to AAD and at this point I gave up - not what I expected from a copy to clipboard button.

**Comment by ADustyOldMuffin** [comment]
@slickwarren That doesn't correct the issue and it no reason to close the issue.

You provide a setting to set TTL on kubeconfigs but then ignore it on UI calls, this could simply be fixed by passing the config value when generating the kubeconfigs. Also of note that even if generated via the CLI or API it will ignore this value. If you close an issue please provide a reason as to why this can't be fixed instead of just linking the documentation to the work around.

If I don't hear anything I'll make another issue as this isn't a fix or work around, our users don't use the CLI they use the UI which offers an option for this.

**Comment by ADustyOldMuffin** [comment]
So after reading through [this](https://rancher.com/docs/rancher/v2.6/en/api/api-tokens/) documentation more I'm also on the side of @mateuszdrab why couldn't this be extended to use a generated token with a TTL? Seems odd to ignore configuration values by default when they're security settings.

**Comment by slickwarren** [comment]
there are a few reasons why we designed it this way:
* k8s allows support to call on external logic to handle tokens, but doesn't handle expiry itself. So, we use rancher CLI to handle this
* the new kubeconfig you generate after disabling the setting `kubeconfig-generate-tokens` will have a call to rancher-cli. On a kubectl call with this kubeconfig, it'll ask for user credentials, authenticate with rancher and then cache that token for future kubectl calls till it expires. Once it expires, it'll automatically ask user to re-login.
kubeconfig TTL is set for all kubeconfig tokens at global level by admin, so it's not cluster level and it cannot be set with the API request to generate kubeconfig.

So this is not a workaround, but it is working by design with k8s implementation. no settings are ignored. 

rancher CLI supports login through all of the normal avenues (local users, SAML, Active Directory, etc.). i.e. if you try and login with active directory with kubeconfig-generate-token disabled, you will be given a link to login with your provider when trying to use the kubeconfig from rancher.

**Comment by mateuszdrab** [comment]
Okay, so I understand it a bit more now, but correct me if I'm wrong.

So, with the rancher cli call, what happens is that every time you call kubectl, rancher cli takes a token that it obtained during logon, ensures it's valid and that token is used to speak to the API server which in turn uses a webhook/external logic to validate the tokens's validity.

However, since you mention that kubernetes doesn't handle validity, does that mean that if I capture the bearer token from the API call and use it for example with curl, the token will expire from rancher's perspective but kubernetes API server will still permit it?

I'd expect that the webhook/external logic would error out on an expired token.

I'll try the rancher CLI approach and report back.
