### ISSUE TITLE
For Rancher 2 Managed Clusters Set Service Account Issuer and JWK URL Options

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#36443]
**Is your feature request related to a problem? Please describe.**

There are ways to do federated access to cloud resources and external resources if those resources can validate the tokens signed by the kubernetes cluster. Since 1.20 with the feature flag turned on you can override the service account issuer and jwks uri. 

**Describe the solution you'd like**

For Rancher managed clusters using RKE/RKE2, it should pass `--service-account-issuer` and `--service-account-jwks-uri` to the kube-apiserver that is based on the rancher2 accessible URL like `https://rancher2/k8s/cluster/<id>/` for the issuer, and for the jwks uri, `https://rancher2/k8s/cluster/<id>/openid/v1/jwks`

These urls should be made to be publicly accessible.

**Describe alternatives you've considered**

Manually setting the values in the configurations.

Part of: SURE-6815

**Comment by ekristen** [comment]
@deniseschannon I believe this should be a feature and pretty straight forward for the team. 

With aws and azure and GCP moving to federated auth, this would be immensely helpful.

**Comment by drpebcak** [comment]
I agree on this, would be super helpful.

**Comment by ekristen** [comment]
This is still relevant

**Comment by ekristen** [comment]
Still valid

**Comment by burgerjeffrey** [comment]
Looking for this, very valid.

**Comment by kishori-sharan** [comment]
Any updates on this?

**Comment by drpebcak** [comment]
still valid

**Comment by drpebcak** [comment]
Still valid

**Comment by drpebcak** [comment]
Still valid

**Comment by drpebcak** [comment]
still valid

**Comment by tepley** [comment]
we would also like this

**Comment by cbron** [comment]
I'm not familiar with this area, so may be dumb questions: 
1. Why do you want to do this via the "rancher2 accessible URL" instead of going directly to downstream cluster ? And does going directly to downstream work ? 
2. Is this only a problem on RKE1/RKE2 clusters ? I assume no, and that Rancher is blocker here, not distros.

**Comment by drpebcak** [comment]
1. Because it allows you to have a cluster with no direct public endpoints, which means you don't have to jump through all the hoops of setting up the cluster endpoint stuff. Going directly to downstream might work, I'm not sure. Part of the other problem there is that you need to know the endpoint when configuring the cluster, so if its generated too late in the process, you won't be able to use it.
2. This issue exists for any cluster rancher provisions.
