### ISSUE TITLE
Can't promote a agent node to server node

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#36480]
**Rancher Server Setup**
- Rancher version: `v2.6-11a7451ffee557897197fc624af03ac6fd34a9f0-head`
- Installation option (Docker install/Helm Chart):  Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `v1.21.7+rke2r1`

**Information about the Cluster**
- Kubernetes version: `v1.21.7+rke2r1`
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**

When bumping rancher to `v2.6-11a7451ffee557897197fc624af03ac6fd34a9f0-head` in Harvester, we found node promotion doesn't work as expected.

**To Reproduce**
 

- Setup a two-node cluster, the first node is the server node and the second one is the agent node.
- Add labels `rke.cattle.io/control-plane-role=true rke.cattle.io/etcd-role=true` to the second node's corresponding machine resource: e.g.,
  ```
  kubectl label -n fleet-local machines.cluster.x-k8s.io custom-13fac6f87899 rke.cattle.io/control-plane-role=true rke.cattle.io/etcd-role=true
  ```

**Result**

node2's roles don't change:
  ```
  $ kubectl get nodes
  NAME    STATUS   ROLES                       AGE     VERSION
  node1   Ready    control-plane,etcd,master   13m     v1.21.7+rke2r1
  node2   Ready    <none>                      4m37s   v1.21.7+rke2r1
  ```

**Expected Result**
node2's roles should become `control-plane,etcd,master` as well. 

**Screenshots**

**Additional context**

The promotion works well with image tag `v2.6.3`, it might be a regression.

```
$ k get machines -A
NAMESPACE     NAME                  CLUSTER   NODENAME   PROVIDERID     PHASE     AGE     VERSION
fleet-local   custom-13fac6f87899   local     node2      rke2://node2   Running   4m36s
fleet-local   custom-1c2d0bf1c41b   local     node1      rke2://node1   Running   9m25s
```

Rancher pod logs:
- [rancher-58c78b84db-24lhg.log](https://github.com/rancher/rancher/files/8049678/rancher-58c78b84db-24lhg.log)
- [rancher-58c78b84db-znb8n.log](https://github.com/rancher/rancher/files/8049679/rancher-58c78b84db-znb8n.log)

I have a Vagrantfile to bring up a cluster with rancherd, please check https://github.com/bk201/try-rancherd/tree/issue-36480

**Comment by thedadams** [comment]
@bk201 This is correct behavior; adding the labels to the CAPI machines is no longer supported. What is the use case here?

**Comment by bk201** [comment]
@thedadams Thanks for the reply. Harvester promotes agent nodes to server nodes if the total node counter is more than 3. Because the underlying RKE2 runtime is deployed and managed by Rancher, we want an "upgrade-proof" way to promote agent nodes. If we promote agent nodes via RKE2's way, we can't assure Rancher won't start the RKE2 agents again when upgrading the RKE2 runtime in the future.

If this is no longer supported, is there a preferred way?

**Comment by thedadams** [comment]
@bk201 Thank you for your response. I would also like to apologize that this was changed without communicating it to the Harvester team. I was unaware that this was something that was being done.

To be honest, there are two correct answers here.

The simplest way: put the same label on the machine plan secret. On the machine spec, there is a bootstrap config reference. The machine plan secret name will be the name of the bootstrap config with `-machine-plan` appended to it. That should the minimal amount of steps.

The safest way: the label should be put on the machine, the bootstrap object, and the plan secret. This is to ensure that all the controllers will do the right thing no matter how they change in the future.

Explanation of why this change happened:
We found that putting Rancher labels on the CAPI machine objects was causing the cluster-api controllers to run unnecessarily. We were afraid that continuing to do this would cause performance issues in the future for some of the users. In addition, it also seemed that this cause the CAPI controllers to not enqueue at the times we wanted because the objects were already going through the controllers. Again, we were afraid that this was causing some racing issues that we wanted to clean up before this support goes GA.

If you have any other questions or concerns, please ask.

**Comment by bk201** [comment]
@thedadams Thanks. I can confirm labeling the machine plans works. When you say "the bootstrap object", does this refer to CR `rkebootstraps.rke.cattle.io`?

For example:
```
╰─$ kubectl get rkebootstraps.rke.cattle.io -n fleet-local
NAME                  AGE
custom-13fac6f87899   3d16h
custom-1c2d0bf1c41b   3d16h
```

**Comment by thedadams** [comment]
Yes, you have the correct object(s).

**Comment by bk201** [comment]
@thedadams, Thanks. I'll close this one and use the new way to promote nodes.
