### ISSUE TITLE
No theme is selected when I log into new account in same browser

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3651]
Version: master 2/18

Steps: 
1.  Set your theme to Dark
2.  Go to Admin/Access Control
3.  Authenticate using Local Auth
4.  Go to Admin/Account
5.  Add an account
6.  Log out of current account and go into new account you just created (using same browser tab)

Results: Theme is dark and if you click on user icon in top right corner you see that no theme is actually selected.  This is true if you start in light theme or auto as well.
![image](https://cloud.githubusercontent.com/assets/11514927/13160734/86a46218-d656-11e5-93f1-cd294b516803.png)
![image](https://cloud.githubusercontent.com/assets/11514927/13160751/9e3fa8ba-d656-11e5-8a0f-29f78bc67af1.png)

Expected:  Should probably start and have light theme selected?

**Comment by westlywright** [comment]
After digging into this I believe this to be an acceptable use case. 

Logic Flow:
* Does the user have a theme stored in rancher preferences?
  * Yes - set as user theme -> set local storage theme to match
  * No  - Does the user have a theme preference stored in local storage?
    * Yes - set as user theme -> set local storage theme to match
    * No  - set light theme as user theme -> set local storage theme to match

Whats happening is we're falling into the second no then yes because the admin creating accounts set a user theme for his/her self that persisted to local storage. So when you log in as a new user there is no theme in pref but there is one locally from the previous user. 

I don't believe the logic is incorrect here. Is this a common bug that's happening? In a real world scenario wouldn't the Admin creating accounts be creating accounts for people not using the same computer? In that case this the bug would not present itself. The only way this seems like it would be an issue is if the admin and new user were using the same computer. This strikes me as an uncommon use case.

@vincent99 @tfiduccia thoughts?

**Comment by vincent99** [comment]
I think this will be fixed by not creating a new admin account when turning auth on...

**Comment by westlywright** [comment]
@vincent99 I believe we had a discussion about you doing the new admin account thing at some point? What was the status on this? the problem still exists as described originally, but like I stated above I do not believe this to be a bug.

**Comment by vincent99** [comment]
The API was changed ~1.0 to convert implicit admin account being used while access control was off into the person who turned auth on.  So this should now work, because the "current account" and "new account" in step 6 are the same account with the same preference.

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
