### ISSUE TITLE
Hostports are not working properly through rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36560]
**Rancher Server Setup**
- Rancher version: v2.6-head 3e482df
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: any

**Information about the Cluster**
- Kubernetes version: observed on 1.21, 1.22 for both rke1 and rke2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): any

   
**Describe the bug**

Hostport will deploy and get to an active state, however it fails to route to the service correctly using the link in rancher

**To Reproduce**
 
* in a downstream cluster, deploy a workload  using hostport
* wait for the workload and associated service to get to an active state

**Result**
rancher service/workload come to an active state, but when the user clicks the link to the hostport, the service is not deployed there. 

**Expected Result**

hostports should work when deployed through rancher

**Additional context**
* same behavior both through ember and dashboard
* was intermittently seen as of v2.6.4-rc2, but is now consistently observed. 
* observed in this ticket, but probably unrelated https://github.com/rancher/rancher/issues/36473

**Comment by jiaqiluo** [comment]
It turns out not a bug but a network-security-configuration thing Rancher applied to the nodes it provisions on the cloud provider:
- When using the AWS EC2 node driver to provision cluster nodes in Rancher, Rancher creates a security group called `rancher-nodes` if no security group is specified.  In this SG, the port range 30000-32767 is open for inbound TCP/UDP traffic. see [Rancher docs ](https://rancher.com/docs/rancher/v2.6/en/installation/requirements/ports/#rancher-aws-ec2-security-group)
- When using the Digital Ocean node driver, Rancher does not create or attach any Firewall to the droplet. 

As the result, we see the following behavior:
- in an EC2-node cluster, the workload does not work properly when setting the hostPort 9998 but work when setting it in the range 30000-32767
- in a DO-node cluster, the workload works when setting the hostPort 9998

**Comment by slickwarren** [comment]
this issue is validated on rancher v2.6.4-rc3 using an ec2 node driver cluster with default settings:
* in an EC2-node cluster, the workload does not work properly when setting the hostPort 9998 but work when setting it in the range 30000-32767
