### ISSUE TITLE
Rancher uses independent vSphere chart

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36579]
A new vSphere chart was created in this ticket: https://github.com/rancher/rancher/issues/35702

Now Rancher needs to actually use it instead of the older chart.

**Comment by deniseschannon** [comment]
@PennyScissors Could you please fill out the QA template to indicate what needs to be validated?

**Comment by deniseschannon** [comment]
@samkulkarni20 With this change, can the team test an upgrade path? Someone deployed with the older versions in v2.5.0 and that the cluster that have the old vsphere charts deployed on it can be upgraded to the new version of the vsphere chart?

**Comment by samkulkarni20** [comment]
Yes @deniseschannon . I'll have QAs validate the upgrade scenario.

**Comment by PennyScissors** [comment]
@samkulkarni20 Could you please fill out the QA template @deniseschannon mentioned above?

**Comment by samkulkarni20** [comment]
**Issue:** The vSphere CPI, CSI were configured as local charts in [rancher/charts](https://github.com/rancher/charts) repo. This issue updates it to use the newly created [vsphere-charts](https://github.com/rancher/vsphere-charts) as upstream repo for the same, instead of building them as local charts. This helps in having central vSphere CPI CSI charts for both RKE1 & RKE2.

This issue & the corresponding PR only updates the upstream location for building the vSphere charts & keeps the underlying CPI, CSI versions same as before. Hence the QA tests should cover the following scenarios for this issue:

Verify that vSphere CPI & CSI charts install & work properly on cluster created using Rancher v2.6-head in below scenarios:
1. Fresh install of CPI chart version `100.1.1+up1.0.1`, CSI chart version `100.1.1+up2.3.0-rancher1`
2. Upgrade CPI chart from `100.1.0+up1.0.100` to `100.1.1+up1.0.1` version & CSI chart from `100.1.0+up2.3.0` to `100.1.1+up2.3.0-rancher1` version

Use rancher/charts repo `dev-v2.6` branch for testing.

**Comment by PennyScissors** [comment]
@samkulkarni20 FYI, once PRs https://github.com/rancher/charts/pull/1764, and https://github.com/rancher/charts/pull/1763 are merged, the charts in your comment would be replaced by the new upgraded charts.

**Comment by deniseschannon** [comment]
To Validate:

Fresh Install: 
Deploy RKE1 with k8s 1.22 with vsphere cloud provider

Upgrade Use Case:
Deploy Rancher 2.6.3, deploy RKE1 with k8s 1.21 with external cloud provider. Deploy vsphere charts through apps & marketplace, add a deployment that uses volumes.

Upgrade to 2.6.4-rcX, upgrade to k8s 1.22. Upgrade vsphere charts through apps & marketplace. Confirm that deployments are still working with volumes.

**Comment by sirredbeard** [comment]
This would be captured during the validation that helm yes would be completing per @rosskirkpat

**Comment by bmdepesa** [comment]
Tested on a vSphere 7.0.3 environment

Fresh install on v2.6.5-rc8
* Created a cluster w/ cloud provider set to external
* Installed out of tree cloud provider with
  * rancher-vsphere-cpi 100.3.0+up1.2.1
  * rancher-vsphere-csi 100.3.0+up2.5.1
* Created a pvc and workload using the PVC
* Everything working as expected


Upgrade from Rancher v2.6.3 -> v2.6.5-rc8
* Created a cluster w/ cloud provider set to external
* Installed out of tree cloud provider with 
  * rancher-vsphere-cpi 100.1.0+up1.0.100
  * rancher-vsphere-csi 100.1.0+up2.3.0
* Created a pvc and a workload using the PVC
* Upgraded Rancher
* Upgrade cpi -> 100.3.0+up1.2.1
* Upgrade csi -> 100.3.0+up2.5.1
* Existing workloads with volumes function
* Provisioned a new workload with a new PVC and that functions as well
