### ISSUE TITLE
Add CIS Hardening Guide for 2.6x for RKE2 provisioned clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36629]
We currently need to have an up-to-date hardening guide for the v2.6x line. Our Rancher 2.6 documentation (https://rancher.com/docs/rancher/v2.6/en/cis-scans/) will need updated for RKE2 clusters.

**Comment by macedogm** [comment]
@anupama2501 FYI I'm still working in updating RKE2's hardening guide. As soon as the PR is done, I'll ping you.

**Comment by macedogm** [comment]
Draft PR https://github.com/rancher/rke2/pull/2507 to update RKE2 hardening guide.

**Comment by macedogm** [comment]
### Root cause
As we are updating RKE hardening guide in https://github.com/rancher/rancher/issues/35735, we also did a review of the current [hardening guide](https://docs.rke2.io/security/hardening_guide/) provided for RKE2.

### What was fixed?
The CIS hardening guide for RKE2 was reviewed and small improvements were added to make sure that it passes CIS profile v1.6 - [rke2-cis-1.6-hardened](https://github.com/rancher/security-scan/tree/master/package/cfg/rke2-cis-1.6-hardened).

### What should be tested?

1. Install a local Rancher 2.6.3 cluster through Helm.
1. Create a cluster with RKE2 (using its [default install instructions](https://github.com/rancher/rke2#quick-start) and version `v1.21.9+rke2r1`).
    ```
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="v1.21.9+rke2r1" sh - && \
    systemctl enable rke2-server.service && \
    systemctl start rke2-server.service && \
    export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin
    ```
1. Import the cluster in Rancher.
1. Install `CIS Benchmark (2.0.2)` chart in the imported RKE2 cluster.
1. Execute a CIS scan with the `rke2-cis-1.6-hardened` profile.
1. Verify the failed tests.
1. Create a new cluster with RKE2 (with version `v1.21.9+rke2r1`), apply the hardening steps. Follow the hardening steps as described in:
    1. Section [Set kernel parameters](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#set-kernel-parameters).
    1. Section [Create the etcd user](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#create-the-etcd-user).
    1. Section [RKE2 configuration](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#rke2-configuration).
    1. Restart RKE2 server in order to apply the new configuration - `systemctl restart rke2-server.service`.
1. Import the cluster in Rancher.
1. Apply the hardening step in section [Configure default service account](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#configure-default-service-account). This needs to be executed after the RKE2 cluster is imported in Rancher.
1. Install `CIS Benchmark (2.0.2)` chart in the new imported hardened RKE2 cluster.
1. Execute a CIS scan with the `rke2-cis-1.6-hardened` profile.
1. Verify that no tests failed in the hardened RKE2 cluster.

### What areas could experience regressions?
No regression is expected.

**Comment by macedogm** [comment]
PR https://github.com/rancher/rke2/pull/2507 is ready for review.

**Comment by samjustus** [comment]
SURE-4358

**Comment by anupama2501** [comment]
blocked by https://github.com/rancher/rancher/issues/37364

**Comment by anupama2501** [comment]
Re opening rancher v2.6-head efa312e
- Created a custom rke2 cluster with the parameters set in the yaml file:

```
spec:
  rkeConfig:
    machineSelectorConfig:
      - config:
          profile: cis-1.6
          protect-kernel-defaults: true
```

- Created 3 VMs and on the vms following sysctl `/etc/sysctl.d/90-kubelet.conf` configured:
```
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
```

- Ran `sudo sysctl -p /etc/sysctl.d/90-kubelet.conf` to enable the settings
- Set `sudo useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U`
- Registered the nodes in the custom cluster
- Once the cluster is active, created account_update.yml with 

```
yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
automountServiceAccountToken: false
```

- Ran the following bash file

```
#!/bin/bash -e

for namespace in $(kubectl get namespaces -A -o=jsonpath="{.items[*]['metadata.name']}"); do
  echo -n "Patching namespace $namespace - "
  kubectl patch serviceaccount default -n ${namespace} -p "$(cat account_update.yaml)"
done
```

- Installed cis-benchmark 2.0.3
- Ran cis-1.6 hardened scan and see 92 failures:

<img width="500" alt="cisrke2" src="https://user-images.githubusercontent.com/38144301/163635320-4bfb2fad-53be-40ab-b2e7-2a04de2520d0.png">

**Comment by anupama2501** [comment]
Blocked on: https://github.com/rancher/rancher/issues/37397

**Comment by anupama2501** [comment]
Verified test cases on Rancher version `2.6.5-rc6`, CIS chart: `2.0.4-rc1`

Cluster Type | Hardened? | CIS_profile | Cluster Spec | CNI | cis-1.5-profile-permissive | cis-1.6-profile-permissive | cis-1.6-profile-hardened | cis-1.5-profile-hardened |
 | - | - | - | - | - | - | - | - | - 
RKE2 custom cluster | Yes | cis_profile: 1.6 | 3 nodes all roles | Canal | PASS | PASS | PASS | PASS |
RKE2 custom cluster | Yes | cis_profile: 1.6 | 3 worker, 1 cp, 1 etcd | Canal |  PASS | PASS | PASS | PASS |
RKE2 custom cluster | Yes | cis_profile: 1.5 | 3 nodes all roles | Canal | PASS | PASS | PASS | PASS |
RKE2 custom cluster | Yes | cis_profile: 1.5 | 3 worker, 1 cp, 1 etcd | Canal |  PASS | PASS | PASS | PASS |
RKE2 custom cluster | No | N/A | 3 nodes all roles | Canal | PASS | PASS | N/A | N/A |
RKE2 custom cluster | No | N/A | 3 worker, 1 cp, 1 etcd | Canal | PASS | PASS | N/A | N/A |
RKE2 custom cluster | No | N/A | 3 nodes all roles | Calico | PASS | PASS | N/A | N/A |
RKE2 custom cluster | No | N/A | 3 worker, 1 cp, 1 etcd | Calico | PASS | PASS | N/A | N/A |
