### ISSUE TITLE
Update the CIS Hardening Guide for 2.6x for k3s cluster type

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36630]
We currently need to have an up-to-date hardening guide for the v2.6x line. Our Rancher 2.6 documentation (https://rancher.com/docs/rancher/v2.6/en/cis-scans/) will need updated for clusters of type k3s

**Comment by macedogm** [comment]
@anupama2501 I opened PR https://github.com/rancher/docs/pull/3897 to update K3s' hardening guide. I used CIS profile [k3s-cis-1.6-hardened](https://github.com/rancher/security-scan/tree/master/package/cfg/k3s-cis-1.6-hardened) that is provided by Rancher.

You spotted correctly that we need to update https://rancher.com/docs/rancher/v2.6/en/cis-scans/ to mention both `k3s-cis-1.6-hardened` and `k3s-cis-1.6-permissive` profiles available in https://github.com/rancher/security-scan/tree/master/package/cfg.

**Comment by macedogm** [comment]
### Root cause
As we are updating RKE hardening guide in https://github.com/rancher/rancher/issues/35735, we also did a review of the current [hardening guide](https://rancher.com/docs/k3s/latest/en/security/hardening_guide/) provided for K3s.

### What was fixed?
The CIS hardening guide for K3s was reviewed and small improvements were added to make sure that it passes CIS profile v1.6 - [k3s-cis-1.6-hardened](https://github.com/rancher/security-scan/tree/master/package/cfg/k3s-cis-1.6-hardened).

### What should be tested?

1. Install a local Rancher 2.6.3 cluster through Helm.
1. Create a cluster with K3s (using its default install instructions and version `v1.21.9+k3s1`) and import it in Rancher.
    1. `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.21.9+k3s1" sh -s -`
1. Install `CIS Benchmark (2.0.2)` chart in the imported K3s cluster.
1. Execute a CIS scan with the `k3s-cis-1.6-hardened` profile.
1. Verify the failed tests.
1. Create a new cluster with K3s (with version `v1.21.9+k3s1`), apply the hardening steps and import it in Rancher. Follow the hardening steps as described in:
    1. Section [Ensure protect-kernel-defaults is set](https://github.com/rancher/docs/blob/f3efeb3924a7cacf02aaa8c0864563925a31a69c/content/k3s/latest/en/security/hardening_guide/_index.md#ensure-protect-kernel-defaults-is-set).
    1. Section [Pod Security Policies](https://github.com/rancher/docs/blob/f3efeb3924a7cacf02aaa8c0864563925a31a69c/content/k3s/latest/en/security/hardening_guide/_index.md#pod-security-policies).
    1. The network policy was not added, as it might block network traffic when Rancher agent is installed in the cluster. The network policy is provided as an example that must be improved by the user, as it varies from user to user environment.
    1. Install K3s using the example command-line provided in [`The command below is an example of how the outlined remediations can be applied to harden K3s`](https://github.com/rancher/docs/blob/f3efeb3924a7cacf02aaa8c0864563925a31a69c/content/k3s/latest/en/security/hardening_guide/_index.md#pod-security-policies). Install K3s version `v1.21.9+k3s1`.
1. Install `CIS Benchmark (2.0.2)` chart in the new imported hardened K3s cluster.
1. Execute a CIS scan with the `k3s-cis-1.6-hardened` profile.
1. Verify that no tests failed in the hardened K3s cluster.

### What areas could experience regressions?
No regression is expected.

**Comment by macedogm** [comment]
PR is ready for review https://github.com/rancher/docs/pull/3897.

**Comment by samjustus** [comment]
https://jira.suse.com/browse/SURE-4357

**Comment by samjustus** [comment]
SURE-4357

**Comment by anupama2501** [comment]
Verified on v2.6.5-rc3

Created a k3s cluster by following the hardening guide mentioned above.
Installed rancher and ran cis hardening guide 1.6 profile. 
Verified scans went through without any error
Created a k3s cluster and imported into rancher server. Verified the scans go through without any error.

```
> k get clusterscans
NAME         CLUSTERSCANPROFILE               TOTAL   PASS   FAIL   SKIP   WARN   NOT APPLICABLE   LASTRUNTIMESTAMP       CRONSCHEDULE
scan-qp2kb   k3s-cis-1.6-profile-hardened     122     72     0      0      29     21               2022-04-28T04:59:13Z   
scan-v4fxk   k3s-cis-1.6-profile-permissive   122     63     0      0      36     23               2022-04-28T05:00:03Z   
> 
```
