### ISSUE TITLE
Kiali fails to load a graph

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#36668]
**Setup Configuration:**

**Rancher server v2.6-head:**

**Installation option :** Docker
**Provider:** ec2 single node.

**Information about the Cluster:**
Kubernetes version: v1.21.9-rancher-1-1
Cluster Type : Custom Cluster with 1 etcd, 1cp, 3 worker nodes. 
OS: RHEL-8.4 SElinux on, dockerversion: 20.10.7

Steps to reproduce:

- Create rancher server
- Create a single node custom cluster with all the roles running RHEL-8.4 with PSP enabled and set to restricted by default
- Run following commands on the instance before adding it to the cluster

`systemctl disable nm-cloud-setup.service nm-cloud-setup.timer
`
`mkdir -p /var/run/istio-cni && semanage fcontext -a -t container_file_t /var/run/istio-cni && restorecon -v /var/run/istio-cni
`

- Install Monitoring version 100.1.1+up19.0.3.
- Install istio version 100.1.1+up1.11.4
- Create a namespace in default project and enable istio auto injection.
- Deploy demo book app
- Open Kiali in Istio.
- Click on the graph. Graph window shows **`Error loading Graph`**.
![Screenshot from 2022-02-28 13-04-31](https://user-images.githubusercontent.com/83208989/155946353-1692ce07-6cfb-4ddb-bd27-21f1f3c2e665.png)

- Further, click on the Services ---> productpage. **`Could not fetch Service Details`** error shows up in the notification.
![Screenshot from 2022-02-28 13-34-45](https://user-images.githubusercontent.com/83208989/155947154-55568cd9-fa62-4bbd-beb4-5df39d0bbb79.png)

Result:

Kiali fails to load graph and fetch Service Details.

**Comment by izaac** [comment]
Was PSP enabled on the chart options values.yaml too ?

**Comment by doflamingo721** [comment]
#### This issue is not active on Rancher v2.6-head (dafffc2)
**Rancher server**: v2.6-head (dafffc2)
**Installation option** : Docker
**Provider**: AWS ec2 instance (ami: ami-0035d7e2be370e0f1)

#### Cluster information:
Kubernetes version: v1.21.10-rancher1-1
Cluster type: Custom cluster with 1cp 1etcd 3worker nodes
OS: RHEL-8.4 SElinux on, dockerversion: 20.10.7

#### Steps followed:
1. Create rancher server
2. Create a custom cluster with 1cp 1etcd 3worker nodes all running SElinux eanbled RHEL-8.4 with PSP enabled and set to restricted by default.
3. Run `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer`  and  `mkdir -p /var/run/istio-cni && semanage fcontext -a -t container_file_t /var/run/istio-cni && restorecon -v /var/run/istio-cni` on all nodes before adding it to the cluster. 
4. Install Monitoring version 100.1.2+up19.0.3.
5. Install istio version 100.1.2+up1.11.7,
6. Create a namespace in default project and enable istio auto injection.
7. Deploy demo book app and generate some traffic on the app.
8. Access Kiali-UI and Click on graph and select the appropriate namespace. 

#### Result:
The graph is getting generated and traces can be seen in services. 
![Screenshot from 2022-03-31 15-24-15](https://user-images.githubusercontent.com/34883075/161036560-fa8fa195-7d37-4099-bf3e-a42142c50ad6.png)

**Comment by vivek-infracloud** [comment]
### Validated the issue on v2.6-head (5c01252)

**Rancher server**: v2.6-head (5c01252)
**Installation option** : Docker
**Provider**: AWS ec2 instance (ami: ami-0035d7e2be370e0f1)

#### Cluster information:
Kubernetes version: v1.21.10-rancher1-1
Cluster type: Custom cluster with 1cp 1etcd 3worker nodes
OS: RHEL-8.4 SElinux on, dockerversion: 20.10.7

#### Steps followed to validate:
1. Created rancher server
2. Created a custom cluster with 1cp 1etcd 3worker nodes all running SElinux eanbled RHEL-8.4 with PSP enabled and set to restricted by default.
3. Ran `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer`  and  `mkdir -p /var/run/istio-cni && semanage fcontext -a -t container_file_t /var/run/istio-cni && restorecon -v /var/run/istio-cni` on all nodes before adding it to the cluster. 
4. Installed Monitoring version 100.1.2+up19.0.3.
5. Installed istio version 100.1.2+up1.11.7,
6. Created a namespace in default project and enable istio auto injection.
7. Deployed a demo book app and generate some traffic on the app.
8. Accessed Kiali-UI and Click on graph and select the appropriate namespace. 

#### Result:
The graph is getting generated and traces can be seen in services.

**Comment by vivek-infracloud** [comment]
Based on above validations, issue is not active anymore. 
Hence closing the issue.
