### ISSUE TITLE
Steve API should allow specific fields in responses to be excluded

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#36683]
When the UI requests a list of resources, currently all data for each resource is returned.

In some cases - e.g. fleet bundle resource - these can be large and for most cases in the UI, there are fields that are not needed or at least not needed on list pages.

Steve should support additional query parameters when fetching resources that specify fields to be excluded from the data sent back to the UI - e.g.

`/v1/management.cattle.io.fleetworkspaces/fleet-default?exclude=metadata.managedFields`

This mechanism should support excluding multiple fields, e.g.

`/v1/management.cattle.io.fleetworkspaces/fleet-default?exclude=metadata.managedFields,metadata.generation`

In addition to exclusion, being able to indicate which fields to only return would be useful too, e.g.

`/v1/management.cattle.io.fleetworkspaces/fleet-default?include=metadata.managedFields`

For some resources, e.g. configmaps, if we're just listing them, we don't want to retrieve all of the data in all of the keys (since this may be large), but we do want to know what keys exists in the data field. This would be a little more complex, but perhaps support something like:

`/v1/management.cattle.io.fleetworkspaces/fleet-default?excludeValues=data`

This would effectively wipe the values under the `data` key, so we just got back the keys with empty values - so for a configmap with large values, we'd still be able to show which keys exist, but we wouldn't need to retrieve all data.

**Comment by samjustus** [comment]
https://jira.suse.com/browse/SURE-4365

**Comment by cmurphy** [comment]
### Root cause
 
n/a

### What was fixed, or what changes have occurred

Added support for query parameters to include or exclude entire fields or exclude large data values for certain keys.

### Areas or cases that should be tested
 
Use curl to test the new query parameters. This is only supported for steve (`/v1/`) endpoints. The new parameters are `include`, `exclude`, and `excludeValues`. Subfields can be specified with a `.`. Subfields within arrays are not supported. Multiple fields can be specified by repeating the query parameter. Example:

```
$ curl http://<rancher>/v1/configmaps?exclude=data&exclude=metadata.managedFields
```

The `ConfigMap` fields `metadata.managedFields` and `data` are excluded. The top-level `data` field in the configmap Collection is still included because the filtering is done on the individual resources, not the collection.

More examples and explanations are shown on https://github.com/rancher/steve/pull/46

### What areas could experience regressions?

Steve API responses
 
### Are the repro steps accurate/minimal?

n/a

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | v2.6-6bb6e45fba97f58443e547e2f57d2807a424467f-head  |
| Installation option       | Helm high availability (in AWS)                     |
| RKE binary version used   | v1.3.8                                              |
| If Helm Chart k8s cluster | v1.22.7                                             |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | not applicable                                      |
| Downstream K8s version    | not applicable                                      |
| Logged in user role       | Administrator                                       |
| Browser type              | Google Chrome                                       |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)            |

## Validation steps

1. Using Postman to validate steve endpoints with query parameters
2. Also checking endpoints manually with various query parameters
   
## Additional Info
Created a Postman collection test query parameters with steve endpoints. Located at this repository: [https://gitlab.com/brudnak/rancher-steve-api-query-params-postman/-/tree/main](https://gitlab.com/brudnak/rancher-steve-api-query-params-postman/-/tree/main)

## RESULTS


![2022-04-20_20-19-09](https://user-images.githubusercontent.com/40877149/164366985-349796c4-ee6d-4148-a532-cedb598e6402.png)

#### :white_check_mark: Expected
Query parameters are working as expected with steve endpoints

#### :white_check_mark:Actual
Query parameters are working as expected with steve endpoints
