### ISSUE TITLE
Unable to edit imported AKS clusters

### ISSUE THREAD

**Issue by David-VTUK** [rancher/rancher#36690]
**Setup**
- Rancher version:  v2.6.3 
- Browser type & version: Firefox 97.0.1 (64-bit)

**Describe the bug**
Unable to edit the options of an imported AKS cluster 

**To Reproduce**

1. Create an AKS cluster from the Azure console.
2. Add credentials to Rancher
3. Navigate to `Cluster Management -> Import Existing -> Azure AKS -> Import cluster`
4. Once the cluster has been imported, Navigate to `Cluster Management -> Edit Config -> Select credentials and Configure Cluster`. 

**Result**

An empty warning bar is displayed but no cluster details are shown:

![image](https://user-images.githubusercontent.com/5892615/156033555-da9ab417-5770-44a7-86e8-3286832ed657.png)

Browser tools indicate this API call returned a `502 Bad Gateway` message:

GET https://RANCHERURL/meta/aksUpgrades?cloudCredentialId=cattle-global-data:cc-REF&region=REGION&clusterId=CLUSTERID

**Expected Result**
To edit existing, imported AKS clusters

**Additional context**
* AKS Clusters *created* by Rancher using the same credentials can have their details edited
* AKS version  `v1.21.9`

**Comment by FerencoVonMatterhorn** [comment]
Our Team is also experiencing this issue on Version 2.6.3 😶

**Comment by annablender** [comment]
## Testing template

#### Root cause

Rancher does not manage fields for imported clusters that the user does not set in the cluster config or launch template. So, when the user imported an AKS cluster Rancher didn't care about the kubernetes version set on the upstream AKS config. That caused a panic when `kubernetesVersion` was accessed.
 
#### What was fixed, or what changes have occurred

I added checks to make sure if `kubernetesVersion` isn't set, use the current version set in `aksStatus` https://github.com/rancher/rancher/blob/428ec692b0336a3bc54b5c68e29c4acd6ee9857b/pkg/api/norman/customization/aks/listers.go#L161.

#### Areas or cases that should be tested

* Create an AKS cluster in Azure portal
* Import the AKS cluster using the Rancher UI
* Go to Cluster Management -> Edit Config for your imported cluster and check that you can edit the configuration and then save it, and the cluster updates
 
#### What areas could experience regressions ?
 
N/A

#### Are the repro steps accurate/minimal ?

Yes.

**Comment by thedadams** [comment]
Reproduced the issue on Rancher v2.6.3:
- Create a cluster in AKS
- Create cloud credential in Rancher for Azure
- Import cluster into Rancher
- Wait for the cluster to be Active
- Edit cluster
- Click "Next: Configure Cluster
I am unable to continue with the edit and I see the screenshot below:
<img width="1497" alt="Screen Shot 2022-03-15 at 11 54 21" src="https://user-images.githubusercontent.com/3682717/158450912-2a4c7afc-96cb-4811-a2ba-d564d10242d4.png">

Verified the fix on v2.6-head (99974f0):
- Create a cluster in AKS
- Create cloud credential in Rancher for Azure
- Import cluster into Rancher
- Wait for the cluster to be Active
- Edit cluster
- Click "Next: Configure Cluster
I am ABLE to continue with the edit and I see the screenshot below (with more configuration below):
<img width="1497" alt="Screen Shot 2022-03-15 at 12 02 46" src="https://user-images.githubusercontent.com/3682717/158452236-2238c343-045b-4379-9636-0d6fca5ab210.png">
