### ISSUE TITLE
RKE2 | Custom cluster | Deleting a machine in Cluster Manager doesn't delete the node 

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36727]
**Rancher Server Setup**
- Rancher version: 2.6-head 54b740f
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed 

**Information about the Cluster**
- Kubernetes version: v1.21.10+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 **custom** cluster 
   
**Describe the bug**

When a machine is deleted in the cluster manager the node is not deleted in the cluster. 

**To Reproduce**
 
1. Provision a **custom** RKE2 cluster with a worker nodes 
2. Navigate to the Cluster Manager 
3. Click on the cluster 
4. Delete the worker machine 

**Result**
Machine is deleted (confirmed in Advanced -> Machines) but the node is still present when navigating to the cluster explorer -> nodes or running `kubectl get nodes`

**Expected Result**

Node is deleted when the machine is deleted

In case of a RKE2 **node driver** cluster (checked with DO) when a machine is deleted in the cluster manager -> the node is deleted in the cluster explorer -> new machine (new node) is provisioned.

**Comment by snasovich** [comment]
@sgapanovich , could you check if the same issue is happening in 2.6.3 as well? If that's the case we should be OK with bumping it to 2.6.5.

**Comment by sgapanovich** [comment]
@snasovich
the issue exists in 2.6.3
after deleting a machine I can see that machine count went from 8 to 7, but we still have 8 nodes

![machines vs nodes](https://user-images.githubusercontent.com/40282141/157569153-e608b5cc-e5d8-4b78-80f2-01fa83b2d56d.jpg)

**Comment by jiaqiluo** [comment]
The bug is reproduced in rancher:v2.6-head 93757af
The steps are the same as the issue provides. 

Results:
- the object `Machine.cluster.x-k8s.io/v1beta1` is removed, but not the object `Node.v1` 
- the following line in Rancher's logs is suspicious: 
```
2022/03/17 23:33:42 [DEBUG] Deleting Kubernetes Node associated with Machine is not allowed
```
- Also see the following in Rancher's logs:
```
2022/03/17 23:33:42 [DEBUG] [UnmanagedMachine] Removing machine fleet-default/custom-ee8770cbc795 in cluster rke2-custom
2022/03/17 23:33:42 [DEBUG] [UnmanagedMachine] Safe removal for machine fleet-default/custom-ee8770cbc795 in cluster rke2-custom not necessary as it is not an etcd node
...
2022/03/17 23:34:30 [DEBUG] Updating machine for node [jiaqi-rke1-1]
2022/03/17 23:34:30 [DEBUG] Updated machine for node [jiaqi-rke1-1]
2022/03/17 23:34:30 [DEBUG] clusterDeploy: getControlPlaneTaints: Length of nodes for cluster [c-m-dw955k9k] is: 2
```

**Comment by jiaqiluo** [comment]
### Root cause
1. because of the missing CAPI label "cluster.x-k8s.io/control-plane" in the control plane node, the controller thinks the cluster does not have any control plan node, so it does not allow the deletion of v1.node when deleting a worker node
2. another issue is found during the investigation: deleting the cluster does not trigger the deletion of the control plan Machine, which is caused by the absence of logic for deleting Machines. 


### What was fixed, or what changes have occurred
1. Add the missing CAPI label "cluster.x-k8s.io/control-plane" to the control plane node. Otherwise, we cannot remove a node because of the errNoControlPlaneNodes error.
4.  Delete the CAPI Machines which have the control plane role and are managed by an RKEControlPlane object. 
  

### Areas or cases that should be tested

- provision an RKE2 custom cluster with 1 (control plane + etcd +worker) and 1 worker. First, delete the worker node, then delete the cluster
- provision an RKE2 custom cluster with 1 (control plane + etcd +worker) and 1 worker. Delete the cluster directly
- provision an RKE2 custom cluster with 1 control plane, 1 etcd, and 2 workers. First, delete one worker node, then delete the cluster

### What areas could experience regressions?
RKE2 custom cluster: 
- delete node with different roles 
- delete the cluster 

### Are the repro steps accurate/minimal?
yes

**Comment by Josh-Diamond** [comment]
Ticket #36727 - Test Results

With Docker on single-node instance:

Reproduced on rancher `v2.6.3`:
1. Fresh install of rancher `v2.6.3`
2. As admin, provision an RKE2 Custom cluster (with multiple nodes - 3 etcd, 2 cp, 3 wkr)
3. Once provisioned, navigate to `Cluster Manager` and select the RKE2 Custom cluster
4. Delete a machine
5. Reproduced - Machine successfully deleted from `Cluster Manager`, but node is NOT deleted from cluster

Screenshots:

`7 machines`

<img width="263" alt="current-reprod#1" src="https://user-images.githubusercontent.com/46494969/160203070-4dc7dd86-dd61-4ca6-b3ab-ff0a608027db.png">

<img width="469" alt="current-reprod#3" src="https://user-images.githubusercontent.com/46494969/160203090-d755caec-8e6b-41d8-a01d-903449ed3a79.png">

`8 nodes`

![current-reprod#2@](https://user-images.githubusercontent.com/46494969/160213673-a7488c1c-0ad4-46e2-9f18-1c8911dfad9f.png)


Verified on rancher `v2.6-6f9c19dc3e1daa4880c11dee036899f4ad2b5340-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, provision an RKE2 Custom cluster (with multiple nodes - 3 etcd, 2 cp, 3 wkr)
3. Once provisioned, navigate to `Cluster Manager` and select the RKE2 Custom cluster
4. Delete a machine
5. Verified - Both machine and node were successfully deleted

Screenshots:

`Post-delete`

<img width="480" alt="Screen Shot 2022-03-25 at 2 21 32 PM" src="https://user-images.githubusercontent.com/46494969/160213971-80c0994d-1b0a-4e8e-9397-970477e96338.png">

![verifiedfinal](https://user-images.githubusercontent.com/46494969/160213974-2b2f8ea7-af3b-4889-98e1-b8dce444aade.png)
