### ISSUE TITLE
Deleting a cluster in error state doesn't remove management cluster object

### ISSUE THREAD

**Issue by David-VTUK** [rancher/rancher#36798]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3s  v1.21.7+k3s1 
- Proxy/Cert Details: Cert-manager issued from LetsEncerypt

**Information about the Cluster**
- Kubernetes version: v1.21.7+k3s1 
- Cluster Type (Local/Downstream): Downstream Imported K3s Cluster

**User Information**
- What is the role of the user logged in?: Admin
   
**Describe the bug**
Imported clusters that are deleted in an error state result in stale CR's, This is visible in the UI.

**To Reproduce**
1. Create a K3s cluster (**not** via Rancher and v2 provisioning)
2. Import the cluster into Rancher
3. Simulate a failure - ie disconnect the k3s node NIC so that Rancher reports it as `Cluster Agent is not connected`
4. Delete the cluster from the Rancher UI

**Result**
1. Previously delete cluster is visible in some parts of the UI

**Expected Result**
1. Cluster to be fully deleted

**Screenshots**
Pre Removal:
![image](https://user-images.githubusercontent.com/5892615/157262599-c51dd773-87a2-4880-bdb3-4bc726d5c2b3.png)
Simulate Error:
![image](https://user-images.githubusercontent.com/5892615/157263038-b23fc50a-8882-4402-9cae-a7e2f4a47008.png)
Post Removal:
![image](https://user-images.githubusercontent.com/5892615/157263147-29c3eaef-74c6-4f71-af37-177cefbbdbcb.png)
Which is different from the homepage:
![image](https://user-images.githubusercontent.com/5892615/157263305-c8bdb378-dc18-4b4e-a817-21bbb50985a1.png)

**Additional context**
The corresponding CR:
```
> kubectl get clusters.management.cattle.io
NAME           AGE
c-m-2564zkdj   21d
c-m-26z755wl   4d23h
c-m-729pglgf   2d5h
c-m-hcrv7x62   22m
c-m-wp9c22sx   42d
local          42d
```

`c-m-hcrv7x62` is the cluster object in question

Related #[35018](https://github.com/rancher/rancher/issues/35018)
[SURE-3507]

**Comment by thedadams** [comment]
### Root cause
If there was an error that wasn't an `agent disconnected error` when the imported cluster is removed from Rancher, then the deletion will hang and won't move forward.

### What was fixed, or what changes have occurred
Now, on any error, Rancher will retry three times to cleanup the downstream cluster. If it fails after the third time, then Rancher will move on with cluster removal.

### Areas or cases that should be tested
1. Deleting imported cluster that is unavailable. The cluster will be removed very quickly from the Cluster Management page, but will stick around in the Home page. After a few minutes (it takes a while to retry), the cluster should be removed from the Home page.
2. Deleting imported cluster that is available. A few minutes after the cluster is removed from Rancher, ensure that the `cattle-system` namespace and `cattle-cluster-agent` deployment are removed from the downstream cluster. This should be tested to ensure the desired functionality hasn't changed.

### What areas could experience regressions?
Deleting imported clusters.

### Are the repro steps accurate/minimal?
Yes.

**Comment by Josh-Diamond** [comment]
Ticket #36798 - Test Results

With Docker on single-node install:

Reproduced on rancher `v2.6.3`:
1. Fresh install of rancher `v2.6.3`
2. Provision a k3s cluster, `v1.21.7+k3s1`, outside of rancher, then import it into rancher
3. Disconnect CP node to simulate error state
4. Delete cluster from Rancher UI
5. Cluster is removed from `Cluster Management`; Cluster is in an error "hang" state on `Home`

Screenshot:

`Home - Post-deletion`
<img width="1445" alt="Screen Shot 2022-04-19 at 2 20 57 PM" src="https://user-images.githubusercontent.com/46494969/164104606-cea34280-87a9-41a7-8d4b-5d4a66c6ed21.png">


Verified on rancher `v2.6-c8114a946563c4ca902881de703c6e4b55b72cb5-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a k3s cluster, `v1.21.7+k3s1`, outside of rancher, then import it into rancher
3. Disconnect CP node to simulate error state
4. Delete cluster from Rancher UI
5. Verified - Cluster is removed from `Cluster Management`; Cluster is removed from `Home`
6. Provision another k3s cluster, `v1.21.7+k3s1`, outside of rancher, then import it into rancher
7. Once `Active`, delete the cluster from Rancher UI
8. Verified - Cluster is removed from `Cluster Management`; Cluster is removed from `Home`; Confirmed `cattle-system` namespace and `cattle-cluster-agent` deployment are removed from downstream cluster

Screenshots:

`Home - Post-deletion - Step 5`
<img width="1447" alt="Screen Shot 2022-04-19 at 2 56 37 PM" src="https://user-images.githubusercontent.com/46494969/164108572-90638bf3-964b-46e3-87a0-83cb24128b42.png">

`Kubectl pods + namespace - Step 8`
<img width="566" alt="Screen Shot 2022-04-19 at 3 55 57 PM" src="https://user-images.githubusercontent.com/46494969/164115309-f923bc8c-549e-4ffa-a743-57eff8cda5e8.png">

<img width="244" alt="Screen Shot 2022-04-19 at 4 03 25 PM" src="https://user-images.githubusercontent.com/46494969/164115317-05b7f45f-fcff-4650-ad70-afc370f106e3.png">
