### ISSUE TITLE
v2prov etcd snapshot restore is incorrectly prepending cluster name to snapshot

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36842]
The etcd snapshot restore functionality is incorrectly prepending the cluster name to the snapshot.

This is a regression caused due to the change in behavior where etcd snapshot CRs were added.

**Comment by thedadams** [comment]
According the the code changes, it looks like restoring Kubernetes version or cluster object would fail because the get request would fail. The get request was incorrectly pre-pending the cluster name when trying to get the restore object. A previous change added etcd snapshot backup/restore objects for RKE2 (like they are used in RKE1). Therefore, pre-pending the cluster name to these objects is no longer needed. This one spot in the code was still pre-pending.

So, in order to dev-validate this issue, I provisioned a single-node RKE2 cluster with v1.22.7+rke2r2, took a snapshot of the cluster, upgraded the cluster to v1.23.4+rke2r2, then restored the cluster using the snapshot. The cluster and Kubernetes version were successfully restored, which indicates that Rancher was able to get the etcd snapshot object and read the old Kubernetes version from it.

This indicates that the fix is working as expected.
