### ISSUE TITLE
[rancher-compose] rm doesn't remove orphaned services (those not in docker-compose.yaml)

### ISSUE THREAD

**Issue by romandvoskin** [rancher/rancher#3693]
Rancher Version:  v0.7.1

Docker Version: 1.9.0

OS: Ubuntu 14.04.3 LTS

Steps to Reproduce: 

1. Create docker-compose.yaml with two services
2. Run rancher-compose -p <projectName> up --upgrade --confirm-upgrade -d
3. Notice both services are present
4. Create docker-compose.yaml with one service (leaving one service from step 1, and delete one from step 1.
5. Two parts:
  - Run `rancher-compose -p <projectName> rm --force`
  - Run `rancher-compose -p <projectName> up --upgrade --confirm-upgrade -d`

Results: 

The orphaned service is never removed.

Expected:

In general I think there should be a way to ensure the state of stack (project) matches docker-compose.yaml file. 

Possible suggestions:
Create an extra option that ensures the stack matches the docker-compose.yaml file for
1. rm (possibly with an extra option)
or
2. up --upgrade (with an extra option)

**Comment by cjellick** [comment]
@romandvoskin that rancher version you provided: "Rancher Version: v0.7.1" is the rancher-compose cli version. The rancher version we are looking for is the version of the rancher server. I believe it can be found by clicking on the cow icon in the UI.

**Comment by cjellick** [comment]
@romandvoskin: my bad: version is in footer

**Comment by deniseschannon** [comment]
Personally, I don't like the idea of deleting services just because they are not in a docker-compose.yml. I re-use stack names for different docker-compose.yml files. I like that you need to explicitly decide which service you want to delete as it ensures that the user knows exactly what they are deleting. 

If there is enough community feedback, I could see adding an option for for `up --upgrade` that allows you to specify needing to match the stack to the docker-compose.yml.

**Comment by romandvoskin** [comment]
In general I tend to think of docker-compose.yaml as THE definition of my stack. Anything outside of it, should not exist. In other words, I think of docker-compose.yaml as a desired state not an incremental change.

**Comment by deniseschannon** [comment]
Since docker-compose/libcompose supports multiple `-f` in a command line, it's hard to justify that one docker-compose.yml would be the definition of a stack and we have a couple of users looking for the fix to be merged into rancher-compose. https://github.com/rancher/rancher/issues/2626

There is this request https://github.com/rancher/rancher/issues/1723, but maybe we could change it to delete the stack regardless if there were services in it. 

Could we agree to close this issue in favor of #1723?

**Comment by romandvoskin** [comment]
Yes. 1723 sounds like a great solution.
