### ISSUE TITLE
Tags defined in Node Template for AWS Node Driver propagated to EC2 instance, but not EBS volume backing that EC2 instance

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#36958]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

   
**Describe the bug**

When custom tags are defined in a Node Template for the AWS Node Driver, these are only propogated to the EC2 instances created during cluster provisioning, not other AWS resources created by the Node Template, including most critically the EBS volumes that back those EC2 instances. The customer relies on the use of AWS tags for internal cost allocation, so these missing tags have critical internal impact. (Please note that EBS volume here refers to the EBS volumes that back the EC2 instances (i.e. attached and available as /dev/sda1), not EBS volumes used as PVs in a cluster, I originally mixed these two up based on issue description from the customer).

**To Reproduce**
 

- Provision a Rancher v2.6.3 instance, I used github.com/superseb/tf-do-rancher2
- Define an AWS Cloud Credential
- Define an AWS Node Template, adding an AWS tag (I set "my-custom-tag": "bar")
- Create a single all role node AWS Node Driver cluster using the Node Template
- Observe that the "my-custom-tag": "bar" is present on the EC2 instance, but not the EBS volume attached to that EC2 instance as /dev/sda1

**Result**

Custom AWS tags defined in Node Template only propagated to EC2 instances

**Expected Result**

Custom AWS tags defined in a Node Template are propagated to all cluster resources created by Rancher during cluster provisioning, including the EBS volumes that back the EC2 instances, not just the EC2 instances themselves.

SURE-4089

**Comment by annablender** [comment]
In response to, _what resources should have tags?_

```
Here is the customer's answer:
"It should be any AWS resource that Rancher manages and creates which supports AWS Tags.
e.g

- AWS EC2 Instance
- AWS EBS Volume
- AWS Security Group (if using the default rancher SG) – we are currently provisioning this outside of rancher.
- AWS EKS ( and any resources that rancher creates as part of this) – we care currently creating EKS outside of rancher and just importing it into rancher."

```

**Comment by snasovich** [comment]
@HarrisonWAffel , we don't have final confirmation on what other resources we need to apply tags to, but whenever you have a chance you can start looking into adding it for EBS volumes and testing the changes.

**Comment by sowmyav27** [comment]
Usecases to validate:

- Fresh install on 2.6.5-rc or 2.6-head
- upgrade rancher usecase from 2.6.4 to 2.6-head

**Comment by Josh-Diamond** [comment]
Ticket #36858 - Test Results

With Docker on single-node instance:

Reproduced on rancher `v2.6.3`:
1. Create an EC-2 instance; create an EBS volume; attach the created EBS volume to the EC-2 instance
2. Fresh install of rancher `v2.6.3`
2. As admin, create a standard user
3. As standard user, provision an AWS Node driver downstream cluster, with an AWS tag defined in the AWS Node Template - [`from: 2-6-3-rke1`]
4. Reproduced - AWS tag is present in EC-2 instance; not present EBS volume

Screenshots:

`EC-2`:

<img width="1378" alt="Screen Shot 2022-04-13 at 11 33 25 AM" src="https://user-images.githubusercontent.com/46494969/163247153-db968b9b-2313-4000-a647-8279b5f67095.png">

`EBS Volume`:

<img width="1376" alt="Screen Shot 2022-04-13 at 11 34 16 AM" src="https://user-images.githubusercontent.com/46494969/163247255-16484a8a-7802-4cef-bc48-7ebbc260f0f9.png">

---

Verified on rancher `v2.6-d63d95a6d75603146e5b15b948ee54a2d452b767-head`:
1. Create an EC-2 instance; create an EBS volume; attach the created EBS volume to the EC-2 instance
2. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As standard user, provision an AWS Node driver downstream cluster, with an AWS tag defined in the AWS Node Template - [`jkeslar: rke1`]
4. Verified - AWS tag is present on both EC-2 instance and EBS volume

Screenshots:

`EC-2`:

<img width="1374" alt="Screen Shot 2022-04-13 at 11 01 47 AM" src="https://user-images.githubusercontent.com/46494969/163242776-922e83a6-79b1-4f5c-b352-2b0f88cce167.png">


`EBS Volume`:

<img width="1377" alt="Screen Shot 2022-04-13 at 11 01 15 AM" src="https://user-images.githubusercontent.com/46494969/163242731-65abf751-0955-4125-a75f-6367d9536d2c.png">

---

Upgrade verified on rancher `v2.6.3` => `v2.6-d63d95a6d75603146e5b15b948ee54a2d452b767-head`:
1. Create an EC-2 instance; create an EBS volume; attach the created EBS volume to the EC-2 instance
2. Fresh install of rancher `v2.6.3`
2. As admin, create a standard user
3. As standard user, provision an AWS Node driver downstream cluster, with an AWS tag defined in the AWS Node Template - [`from: 2-6-3-rke1`]
4. Reproduced - AWS tag is present in EC-2 instance; not present EBS volume
5. Upgrade rancher from `v2.6.3` => `v2.6-head`
6. `Edit Config` of cluster and upgrade k8s version
7. After re-provisioning cluster with k8s upgrade, confirmed - AWS tag still not in EBS Volume
8. Create a new AWS Node driver cluster with an AWS tag, defined in node template - [ RKE2 this time with AWS tag `jkeslar: rke2`]
9. Upgrade verified - Post rancher upgrade, newly provisioned AWS Node driver clusters WILL display AWS tags across all AWS resources (Instances, EBS Volumes, etc)

Screenshots:

`EC-2`:

<img width="1375" alt="Screen Shot 2022-04-13 at 12 05 45 PM" src="https://user-images.githubusercontent.com/46494969/163252490-dd7a78c3-d3d1-4558-8ebd-0483815496d8.png">

`EBS Volume`:

<img width="1377" alt="Screen Shot 2022-04-13 at 12 07 20 PM" src="https://user-images.githubusercontent.com/46494969/163252691-36f71543-cb1e-46fa-bf30-6d4632121fe1.png">

**Comment by deniseschannon** [comment]
Since there wasn't a testing template, we missed testing if the network interfaces also received the tags as described in the PR. 

cc: @HarrisonWAffel @sowmyav27 @Josh-Diamond

**Comment by HarrisonWAffel** [comment]
### Root cause
When creating downstream clusters using EC2's the tags specified for the cluster were only being applied to the EC2 instance itself, and not any of the backing resources such as the EBS volume and primary network interface. This made it difficult for customers to monitor their EBS spending as they used tags to do so. 
### What was fixed, or what changes have occurred
Downstream EC2 clusters now have the tags specified for an instance applied to all resources supporting the EC2 instance. This includes the EBS volume and primary network interface. 
### Areas or cases that should be tested
+ Open the create cluster menu within rancher and select an EC2 cluster 
+ Add a new node template 
+ Select required credentials and VPC 
+ Once you reach `instance settings` (step 4) look in the lower left hand corner and find the `AWS Tags` button
+ Add several instance tags, content of the tags is not important 
+ Save node template and create downstream EC2 cluster (1 node, all roles) 
+ Create the cluster & once it becomes active, navigate to the AWS console, find the EC2 instances page, and find the newly created instance
+ Check the following for tags 
  + The instance itself (under the tags tab)
![Screen Shot 2022-04-20 at 9 45 24 AM](https://user-images.githubusercontent.com/25062254/164244804-de000652-18a5-4f12-b63e-3dbb4ab13825.png)
  + The EBS Volume (open the storage tab and click on the EBS volume listed
![Screen Shot 2022-04-20 at 9 45 36 AM](https://user-images.githubusercontent.com/25062254/164244879-ffdb518c-bf00-4848-9138-887f09063037.png)
  + The network interface (open the storage tab and click on the interface listed) 
![Screen Shot 2022-04-20 at 9 45 45 AM](https://user-images.githubusercontent.com/25062254/164244997-ca5868fc-8a2b-4fff-b5a7-664371cfdda8.png)

### What areas could experience regressions?
+ A possible regression would be that no tags are applied
### Are the repro steps accurate/minimal?
+ yes

**Comment by Josh-Diamond** [comment]
Ticket #36958 - Test Results [pt. 2]

Verified on rancher `v2.6-228a585bb25b99ee191f2911ea3c6fb0ce9e41f3-head`:

1. Create an EC-2 instance; create an EBS volume; attach the created EBS volume to the EC-2 instance
2. Fresh install of rancher v2.6-head
3. As admin, create a standard user
4. As standard user, provision an AWS Node driver downstream cluster, with an AWS tag defined in the AWS Node Template - [`jkeslar: tag`]
5. Verified - AWS tag is present on EC-2 instance, EBS volume, and Network Interface

Screenshots:

`Rancher UI`
<img width="972" alt="Screen Shot 2022-04-20 at 12 56 24 PM" src="https://user-images.githubusercontent.com/46494969/164312414-d0125d05-2a71-4b83-b173-032b2dca73fc.png">

`EC-2 Instance`
![instance_final](https://user-images.githubusercontent.com/46494969/164311868-878e31df-ac60-45ec-b0da-859a6dd9c0a9.png)

`EBS Volume`
![ebs-tag_final](https://user-images.githubusercontent.com/46494969/164312075-291dcec0-1276-4bc7-ab04-6c3a26401aa2.png)

`Network Interface`
![networkTag_final](https://user-images.githubusercontent.com/46494969/164312275-a7b60dd3-5c64-4180-9f10-deb76197acee.png)
