### ISSUE TITLE
RKE2 Cluster does not show an `Error` state when cluster upgrade has failed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36969]
**On 2.6-head commit id: `024e6fa`**

- Deployed an RKE2 cluster - 3 etcd, 2 cp and 3 worker nodes
- Upgrade strategy is set on the cluster
- Edit cluster --> Upgrade k8s version from 1.22 to 1.23
- Error seen on the cluster -
- `Draining etcd node(s) sowmya-do3-pool1-6c6f5f7f4f-x66td: error draining machine sowmya-do3-pool1-6c6f5f7f4f-x66td: error when evicting pods/"calico-typha-6546b78f-qpg5l" -n "calico-system": global timeout reached: 30s`
- But the state of the cluster is `Provisionining`
- And in another scenari, on the control plane error `Draining control plane node(s) sowmya-test-pool2-56d9c84585-xx5hz: error draining machine sowmya-test-pool2-56d9c84585-xx5hz: cannot delete Pods with local storage (use --delete-emptydir-data to override): cattle-system/system-upgrade-controller-5b6457d644-n8qhx`
<img width="1427" alt="Screen Shot 2022-03-21 at 12 16 58 AM" src="https://user-images.githubusercontent.com/26032343/159177709-a4a4017f-5943-4cae-b9ac-a1e9022987d0.png">

**Expected:**
Cluster state must show Error

**Comment by paynejacob** [comment]
The error message show occurs when a cluster is waiting to finish draining.  The upgrade has not technically failed because it is just waiting for the drain to complete.  @thedadams did some work to make it clearer when a cluster is waiting to drain.  Hopefully this will make it clearer to the user why their upgrade has seemed to stall.

**Comment by slickwarren** [comment]
the option `--delete-emptydir-data` is disabled by default when enabling an upgrade strategy. And it seems the user will hit this error without enabling it. Would it be a backend or dashboard request to enable this by default? or is there a case against enabling this by default? 
<img width="1033" alt="Screen Shot 2022-04-08 at 3 49 41 PM" src="https://user-images.githubusercontent.com/16691014/162543821-c5e64e14-6466-48c8-889f-a96d5b440b24.png">

**Comment by Oats87** [comment]
Personally I don't have any issues with moving to a model where `--delete-emptydir-data` is enabled by default; however, I think we should very clearly state this with as many disclaimers as possible b/c it can cause data loss for those that are not expecting it. Even though `emptyDir` is expected to be "ephemeral", there are users out there that rely on `emptyDir` persisting over the life of a pod and if a pod's lifecycle is prematurely interrupted due to an "upgrade" this may cause issues. 

With a disclaimer, we can fall back on the "it said it would do that" argument around it.

Additionally, I'm not sure exactly what RKE1 does, but we should probably just mimic that (I'm pretty sure RKE1 drains forcefully by default)

**Comment by slickwarren** [comment]
as a result of the above comment and offline discussion, the above UI ticket was opened and we will close this one.
