### ISSUE TITLE
cattle-node-cleanup doesn't pull from private registry

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#36981]
**Rancher Server Setup**
- Rancher version: 2.6.2 & 2.6.3
- Installation option (Docker install/Helm Chart): any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: any 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:  

   
**Describe the bug**

When deleting a node from a custom cluster,  a `cattle-node-cleanup` job is created and it pulls images from DockerHub and not the configured private registry for the cluster.
As the result, the job gets stuck in an airgap environment and holds a finalizer on the machine object, which can cause issues if the hardware is re-used.

**To Reproduce**
 
- Create a custom cluster of 3+ nodes and specify a private registry
- Delete one of the nodes and monitor the job that gets created to clean up the node

**Result**
A `cattle-node-cleanup` job is created and it pulls images from DockerHub and not the configured private registry for the cluster.

**Expected Result**

The job should pull images from the configured private registry for the cluster.
 
SURE-3888
SURE-4289

**Comment by thedadams** [comment]
### Root cause
The node-cleanup job completely ignored the private registry information for a cluster.

### What was fixed, or what changes have occurred
The cattle-cleanup-node job now created with private registry information similar to the cattle-cluster-agent.

### Areas or cases that should be tested
1. Create a custom RKE1 cluster with Kubernetes version v1.21.10 (I don't know if the Kubernetes version is important, but I was able to reproduce this issue with that version).
2. Provision three custom nodes: one with all roles and two with a worker-only role.
3. Once all nodes are active, turn the VM off one of the worker nodes.
4. Once this worker node is unavailable in the Rancher UI, delete the node from the Rancher UI. It should be deleted.
5. Without turning the VM off, delete the second worker-only node. It should be deleted.

### What areas could experience regressions?
Deleting nodes from custom RKE1 clusters.

### Are the repro steps accurate/minimal?
Yes

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6.5-rc1 
Rancher cluster type: Airgap
Docker version: 20.10

Downstream cluster type: RKE1 Custom

----------

### Testing: ###

Tested this issue with the following steps:

1. Create a custom RKE1 cluster with Kubernetes version v1.21.10 (I don't know if the Kubernetes version is important, but I was able to reproduce this issue with that version) and a private registry.
2. Provision two custom nodes: one with all roles and one with a worker-only role.
3. Once all nodes are active, delete the worker-only node.
4. A job with name cattle-cleanup-node gets created in the default namespace. This job should use an image from the private registry, similar to cattle-cluster-agent.

**Result** - Pass
The cattle-cleanup-node job is now created with private registry information similar to the cattle-cluster-agent.

![image.png](https://zube.io/files/rancher/2e6d79ed6bc59d6a9dec13c25b6a88b8-image.png)
