### ISSUE TITLE
[vsphere node driver] windows is unable to register with the cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36986]
**Rancher Server Setup**
- Rancher version: v2.6-head(024e6fa)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: self signed certs

**Information about the Cluster**
- Kubernetes version: any (tested with 1.22.7+rke2r2)
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vsphere rke2 node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

   
**Describe the bug**
windows node (using the node driver) is unable to register with the cluster. it appears to be looking for CA certs

**To Reproduce**
* deploy a vsphere node driver cluster with 1 node each role
  * include a windows worker pool
* wait for the windows node to come to an active state

**Result**
* windows node never joins the cluster

**Expected Result**
* windows node should join the cluster

**Screenshots**
<img width="1479" alt="Screen Shot 2022-03-21 at 2 20 58 PM" src="https://user-images.githubusercontent.com/16691014/159365877-a9c9fa19-3f4e-493c-9c72-8319976ac3dd.png">

**Additional context**
@rosskirkpat  is aware of the issue and looking into it

**Comment by sirredbeard** [comment]
This can be retested. It worked in the Rancher 2 weekly demo based on 2.6.6 release.

**Comment by jameson-mcghee** [comment]
@sirredbeard 
cc @snasovich @Sahota1225 
This issue is still reproducing for me on v2.6-head (see below).
![image.png](https://zube.io/files/rancher/08642059923789639c950556def7e2b2-image.png)

I was using the following settings for the Windows Worker:
![image.png](https://zube.io/files/rancher/c0b6fcdbf3e17672352fa87a36921253-image.png)
![image.png](https://zube.io/files/rancher/d6c08ce931aeb9973340c22e627d323f-image.png)

YAML for the Win Worker:
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  annotations:
    machine.cluster.x-k8s.io/exclude-node-draining: "true"
  creationTimestamp: "2022-07-08T15:50:09Z"
  finalizers:
  - machine.cluster.x-k8s.io
  generateName: thistimeforsure-winworker-66d4d97cbd-
  generation: 2
  labels:
    cattle.io/os: windows
    cluster.x-k8s.io/cluster-name: thistimeforsure
    cluster.x-k8s.io/deployment-name: thistimeforsure-winworker
    machine-template-hash: "2280853768"
    rke.cattle.io/cluster-name: thistimeforsure
    rke.cattle.io/rke-machine-pool-name: winworker
    rke.cattle.io/worker-role: "true"
  managedFields:
  - apiVersion: cluster.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:machine.cluster.x-k8s.io/exclude-node-draining: {}
        f:finalizers:
          .: {}
          v:"machine.cluster.x-k8s.io": {}
        f:generateName: {}
        f:labels:
          .: {}
          f:cattle.io/os: {}
          f:cluster.x-k8s.io/cluster-name: {}
          f:cluster.x-k8s.io/deployment-name: {}
          f:machine-template-hash: {}
          f:rke.cattle.io/cluster-name: {}
          f:rke.cattle.io/rke-machine-pool-name: {}
          f:rke.cattle.io/worker-role: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"63cb7909-7516-46a0-aa6d-68120992820d"}: {}
      f:spec:
        .: {}
        f:bootstrap:
          .: {}
          f:configRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:uid: {}
          f:dataSecretName: {}
        f:clusterName: {}
        f:infrastructureRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:uid: {}
    manager: rancher
    operation: Update
    time: "2022-07-08T15:50:25Z"
  - apiVersion: cluster.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:bootstrapReady: {}
        f:conditions: {}
        f:infrastructureReady: {}
        f:lastUpdated: {}
        f:observedGeneration: {}
        f:phase: {}
    manager: rancher
    operation: Update
    subresource: status
    time: "2022-07-08T16:01:06Z"
  name: thistimeforsure-winworker-66d4d97cbd-79skt
  namespace: fleet-default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachineSet
    name: thistimeforsure-winworker-66d4d97cbd
    uid: 63cb7909-7516-46a0-aa6d-68120992820d
  resourceVersion: "370879"
  uid: 087d8ff9-ffbe-42a4-8f89-fc1a797d7dc4
spec:
  bootstrap:
    configRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEBootstrap
      name: thistimeforsure-bootstrap-template-wj98j
      namespace: fleet-default
      uid: 2e36a14d-4af3-401c-87b6-89c7519d8a73
    dataSecretName: thistimeforsure-bootstrap-template-wj98j-machine-bootstrap
  clusterName: thistimeforsure
  infrastructureRef:
    apiVersion: rke-machine.cattle.io/v1
    kind: VmwarevsphereMachine
    name: thistimeforsure-winworker-6ca2f116-rhl6k
    namespace: fleet-default
    uid: 7b197ab7-2640-441e-9102-e16570efa835
status:
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2022-07-08T15:50:28Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-07-08T15:50:24Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2022-07-08T15:52:56Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2022-07-08T15:50:15Z"
    reason: WaitingForNodeRef
    severity: Info
    status: "False"
    type: NodeHealthy
  - lastTransitionTime: "2022-07-08T16:01:06Z"
    status: "True"
    type: PlanApplied
  - lastTransitionTime: "2022-07-08T16:01:08Z"
    message: waiting for agent to check in and apply initial plan
    reason: Waiting
    status: Unknown
    type: Reconciled
  infrastructureReady: false
  lastUpdated: "2022-07-08T15:50:28Z"
  observedGeneration: 2
  phase: Provisioning

**Comment by snasovich** [comment]
@jameson-mcghee , could you please re-test it? `v2.6-head` was broken around the time you were testing this.

**Comment by jameson-mcghee** [comment]
@snasovich, will do!

**Comment by jameson-mcghee** [comment]
@snasovich, it still appears to be broken for me on 2.6-head (2c21373)

![image](https://user-images.githubusercontent.com/13294321/178997042-d5ad394d-2e5d-4839-8479-36e4708af459.png)

**Comment by phillipsj** [comment]
I am unable to reproduce with the latest v2.6-head (2c21373).
![image](https://user-images.githubusercontent.com/1568133/179227306-ee6054b3-df4d-4639-afb5-35ab4c34df9a.png)

**Comment by phillipsj** [comment]
I tried splitting out all the roles and everything came up fine again.

![image](https://user-images.githubusercontent.com/1568133/179232083-05702bff-2dfc-4290-aa6a-560ce8e2119b.png)

**Comment by phillipsj** [comment]
@jameson-mcghee @snasovich this is caused by an issue with the Windows Server 2022 template. I will generate a new template today that should have all the required files. Somehow the image was built and didn't have cloudbase-init installed.

**Comment by phillipsj** [comment]
## Issue: 

NA
 
## Problem

The issue is that a bad Windows Server 2022 image template was being used that didn't have cloudbase-init properly configured.
 
## Solution

Built a new template for Windows Server 2022 on the QA vSphere 7.0 environment called **windows-server-2022-datacenter-dexp-v22.07**.
 
## Testing

I created a cluster using the latest Rancher and then created a cluster for RKE2 using the vSphere node driver.

![image](https://user-images.githubusercontent.com/1568133/179875236-28ae0492-495d-49f0-b4b8-fb06e377219a.png)

![image](https://user-images.githubusercontent.com/1568133/179875621-4329327a-e5e4-4100-9002-c5bf3b025ec6.png)

**Comment by jameson-mcghee** [comment]
This issue is no longer reproducing on v2.6-head. Therefore I am setting this to ticket to Done.

![image.png](https://zube.io/files/rancher/4c126ce18cff6ca23e96ffcdcf349bb2-image.png)
