### ISSUE TITLE
[monitoring, windows rke2] can't deploy windows-exporter on RKE2 cluster

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#37022]
**Rancher Server Setup**
- Rancher version: v2.6-head (b7c9b89)
- Installation option (Docker install/Helm Chart):docker 

**Information about the Cluster**
- Kubernetes version: v1.22.7+rke2r2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom (windows, rke2)

**Describe the bug**
windows-upgrader fails at `check-wins-version` since the wins binary it points at is wrong

**To Reproduce**
* deploy windows rke2 cluster
* deploy rancher-monitoring chart with global.cattle.windows.enabled set to true

**Result**
* daemonset fails to successfully deploy pods for the chart due to `check-wins-version` failing

**Expected Result**
windows-exporter should deploy and all pods from deployment should get to an active state.

**Additional context**

As discussed with @luthermonson offline, the issue has to do with https://github.com/rancher/charts/blob/78e6519897eb0af266dfdf2c84ff6359e3e7f96a/charts/rancher-monitoring/100.1.1%2Bup19.0.3/charts/windowsExporter/scripts/check-wins-version.ps1#L3

**Comment by aiyengar2** [comment]
Related comment: https://github.com/rancher/rancher/issues/37020#issuecomment-1076935510

**Comment by luthermonson** [comment]
This ended up actually being a problem with our wins builds. After getting the wins-upgrader story sort of working I ended up finding the following while trying to deploy monitoring.

```
InvalidArgument: C:\scripts\check-wins-version.ps1:9
Line |
9 | return [System.Version]($winsAppInfo.Server.Version.substring(1))
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot convert value "9cae19-dirty" to type "System.Version".
| Error: "Version string portion was too short or too long.
| (Parameter 'input')"
```

Which turns out we have a non-porcelain repo while building wins which puts this -dirty in silently and the wins version checker couldn't parse the semver.

With this PR: https://github.com/rancher/wins/pull/107

We now get...

![8b054bc40dbab82bff1c741668eb92ec](https://user-images.githubusercontent.com/1616909/165399046-8ee72e9d-d856-4e52-bac2-5e768abf6a0a.png)

And

```
PS C:\Users\Administrator> get-process -name rancher-wins-windows-exporter

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    277      16    22632      21492       0.31    964   0 rancher-wins-windows-exporter
```

**Comment by slickwarren** [comment]
on v2.6-head (5f04f3a) I am still seeing an issue with windows exporter with the following setup:
* custom cluster, v1.22.9-rc4+rke2r1
* 1 dedicated node-per-role (linux, ubuntu 20)
*  1 windows 2022 node (containerlatest AMI from 4-13-22)

the `windows-monitoring-windows-exporter` target is down in prometheus. Upon looking at the pod logs, I see the following:
* `check-wins-version` is confirmed using 0.2.3 `Detected wins version on host is v0.2.3, which is >v0.1.0. Continuing with installation...`
* logs of `exporter-node-proxy` are where errors are seen:
```
INFO[2022-04-27T21:40:49Z] Connecting to proxy url="ws://rancher_wins_proxy"
--
Wed, Apr 27 2022 2:42:34 pm | ERRO[2022-04-27T21:42:34Z] Error writing ping error="i/o timeout"
Wed, Apr 27 2022 2:42:34 pm | ERRO[2022-04-27T21:42:34Z] Error writing ping error="i/o timeout"
Wed, Apr 27 2022 2:42:34 pm | FATA[2022-04-27T21:42:34Z] i/o timeout
```

**Comment by markusewalker** [comment]
The initial issue I verified on `v2.6-head`  https://github.com/rancher/rancher/commit/2a954f41fda669a7aaec13c6740142ca54b6dcf7, but there are additional issues discussed below.

**ENVIRONMENT DETAILS**
	• Ubuntu 20.04: Docker Install
	• Windows 2022: Worker Node
	• Rancher version: v2.6-head  https://github.com/rancher/rancher/commit/2a954f41fda669a7aaec13c6740142ca54b6dcf7

**TEST RESULT**
PASS/FAIL

VERIFICATION STEPS
1. Setup Rancher, create a Standard user, logout and login as that standard user.
2. Created a custom downstream RKE2 cluster that includes the following: 1 Linux cp, 1 Linux etcd, 1 Linux worker, 1 Windows worker.
3. Installed rancher-monitoring chart with global.cattle.windows.enabled set to true.
4. Verified that windows-exporter deployed successfully on my cluster:
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/52591819/166343141-e6a7e93c-f827-4fa5-bc62-f5f8322a739d.png">

Although the above appears successful, there are some issues that are worth further looking into. To start, looking at the logs for the `windows-exproter`, they are blank as shown below for each container:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/52591819/166343148-7e44127a-04ef-4191-ac58-eaec4262f720.png">

Additionally, looking into the monitoring targets, it appears that there are several targets not started.  See them all below:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/52591819/166343165-1a142837-c4f6-4b4c-b677-560ffcf89988.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/52591819/166343168-5677bfd0-5e82-49d6-b6ef-45e85c9748b3.png">
<img width="474" alt="image" src="https://user-images.githubusercontent.com/52591819/166343174-5cb0bd28-9ff2-4f1e-b5c4-3188f12dbd11.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/52591819/166343184-88e9230c-0050-40de-a8ce-b5d9e1d2062c.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/52591819/166343189-0d5f872c-88e2-427f-aeb9-7c3de36ab93b.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/52591819/166343195-6f06178d-64c6-411c-8649-6310f9995e63.png">

**Comment by markusewalker** [comment]
Spoke with @luthermonson regarding this. I will retest on my end as there are suspected configuration issues that are causing the errors I reported before.

**Comment by markusewalker** [comment]
Verified on `v2.6.5-rc6` that this is working as expected. My earlier testing showed issues due to configuration issues unrelated to this issue.

ENVIRONMENT DETAILS
- Ubuntu 18.04: Rancher HA
- Ubuntu 20.04: 1 cp, 1 etcd, 1 worker 
- Windows 2022: Worker Node
- Rancher version: `v2.6.5-rc6`

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher, create a Standard user, logout and login as that standard user.
2. Created a custom downstream RKE2 cluster that includes the following: 1 Linux cp, 1 Linux etcd, 1 Linux worker, 1 Windows worker.
3. Installed rancher-monitoring chart with global.cattle.windows.enabled set to true.
4. Verified that windows-exporter deployed successfully on my cluster:
![image](https://user-images.githubusercontent.com/52591819/166824137-e8fba500-e8fd-4f7e-8e6e-6ccdf05a4a3e.png)
5. Verified that the Prometheus targets are all passing and up and running as expecting. Some samples below:
![image](https://user-images.githubusercontent.com/52591819/166824314-219aad34-d45f-4109-9e48-31433fdc3285.png)
![image](https://user-images.githubusercontent.com/52591819/166824341-af2a91e8-5515-4efc-aa7a-26ebda89985e.png)
![image](https://user-images.githubusercontent.com/52591819/166824362-877a9334-0fca-4841-bf6b-e40dab2de23d.png)
