### ISSUE TITLE
vsphere rke1 node driver: some nodes stuck in `Waiting for VMware Tools to come online...`, unable to delete node through rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37058]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc13
- Installation option (Docker install/Helm Chart): docker
- 
**Information about the Cluster**
- Kubernetes version: v1.22.7-rancher1-1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vsphere cloud provider

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard

   
**Describe the bug**
sometimes when provisioning a cluster, node(s) in the cluster get stuck in `Waiting for VMware Tools to come online...`. These nodes do not come up with an IP address, and appear to be running but don't ever get an IP address.  These nodes in rancher are visible, but are not able to be removed.  Deleting the cluster, deleting nodes in this state, and scaling down the pool(s) all fail to resolve this issue. 

**To Reproduce**
* provision a downstream cluster using vsphere node driver
  * k8s v1.22.7
  * 1 node per role
* wait for the cluster to get to an active state

**Result**
cluster doesn't get to an active state. Nodes in this state are not removable. 

**Expected Result**
user should be able to remove downstream nodes provisioned by rancher. 

**Screenshots**
In the screenshot, I am able to delete the controlplane node, but not worker or etcd node(s)
<img width="441" alt="Screen Shot 2022-03-25 at 5 12 09 PM" src="https://user-images.githubusercontent.com/16691014/160216483-955f320c-cd09-45ae-bc8b-52bcb67aa434.png">

**Additional Notes:**
* this was tested using a vsphere 7.0 environment. 
* Eventually, the cluster deletion occurred through rancher, but the backend nodes that displayed this message in rancher were not removed

**Comment by snasovich** [comment]
@sirredbeard , could this be given priority as it blocks testing for https://github.com/rancher/rancher/issues/35474 and we want it tested soon to ensure there are no big issues with vSphere CPI/CSI charts upgrades when RKE2 version is upgraded on the downstream clusters?

**Comment by sirredbeard** [comment]
We suspect this is a bad template.

**Comment by phillipsj** [comment]
I just tested in a different environment and wasn't able to recreate the issue.  Is this environment available to investigate?

**Comment by phillipsj** [comment]
@slickwarren and I met today to discuss this issue. I will be doing some testing with the same template that he is using to debug what is occuring. As part of this process I will be finishing up the Packer template generation for vSphere so we can have a standard set of known good templates for several Linux distributions and versions of Windows Server.

**Comment by phillipsj** [comment]
@slickwarren I created a new image for Ubuntu 20.04 called linux-ubuntu-20.04lts-v22.04 in the packer-templates content library. There were multiple issues with the first being using lvm, which in 20.04 defaults to a specific size for root and needs resized. The other issue was related to how the partitions were configured by default causing an issue in the cloud-init not auto growing the volume. Both issues have been fixed by not using lvm and then defining the partitions in the auto-install.

https://bugs.launchpad.net/subiquity/+bug/1907128

**Comment by phillipsj** [comment]
### Root cause

There were multiple issues with the template, first being using lvm, which in 20.04 defaults to a specific size for root and needs resized. The other issue was related to how the partitions were configured by default causing an issue in the cloud-init not auto growing the volume.

https://bugs.launchpad.net/subiquity/+bug/1907128
 
### What was fixed, or what changes have occurred
 
Both issues have been fixed by not using lvm and then defining the partitions in the auto-install.

### Areas or cases that should be tested
 
Deploying both RKE1 and RKE2 nodes using the template in the vSphere node driver.

### What areas could experience regressions?

No regressions should be experienced since this is a VM template issue.

### Are the repro steps accurate/minimal?

Yes

**Comment by slickwarren** [comment]
Tested using rancher 2.6-head (6c12bee)
I'm no longer seeing this issue when provisioning rke1 or rke2 nodes on 1.21.x or 1.22.x when using the new packer templates
