### ISSUE TITLE
After upgrade to Monitoring v2 cluster name is no longer included in alerts

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#37128]
**Issue description:**

When an alert fires it does not mention from which cluster it comes.

**Business impact:**

Much time is lost going through each cluster looking for failures when an alert comes in. Some customers have hundreds of clusters and this renders the alert largely useless as an early response tool

**Troubleshooting steps:**

Enable Monitoring v2 and set an alert threshold low so the alert will fire.

**Repro steps:**

    Enable Monitoring v2 (possibly have to upgrade from v1?)
    Set an alert threshold low so the alert will fire.

**Actual behavior:**

Alert comes in without a cluster name.

**Expected behavior:**

Alert should include the cluster name

**Additional notes:**

Since this was working in v1 it is expected behavior this is a regression.

SURE-2912

**Comment by MKlimuszka** [comment]
QA, please confirm this is still an issue in 2.6.x

**Comment by ronhorton** [comment]
@MKlimuszka monitoring v2 doesn't include the cluster name in alerts. it is, however, configurable on the alert itself to include whatever information relevant to the alert that the user finds useful. 

eg, in the alert name, I include the cluster name
<img width="274" alt="Screen Shot 2022-03-31 at 10 11 13 AM" src="https://user-images.githubusercontent.com/89212856/161075696-901c7223-014e-4583-90ae-81c91ca3b2f1.png">

**Comment by aiyengar2** [comment]
As @ronhorton mentioned, you can always add the label to the alert. The field to configure to get this is https://github.com/rancher/charts/blob/949710afc89c78a07aa3f0082046526738ba547d/charts/rancher-monitoring/100.1.2%2Bup19.0.3/values.yaml#L566

But auto-inferring the cluster name on install and inserting it into this list is a feature request

**Comment by Tejeev** [comment]
I would argue that adding cluster name to the alerts is not a Feature Request as it was standard in Monitoring v1, and so this is a regression and bug.  

Though we have a workaround, I believe it is not reasonable for a customer with tens or hundreds of clusters to go and edit each and ever alert for each of those clusters so that it includes the cluster name.  Since this is such an old regression (as v2 has been out for more than a year now), and since we are now removing the ability to easily deploy v1 or continue using it, I believe it's reasonable to argue that v2 should have reached feature parity with v1.  I would argue that this should be of a higher priority.
 
From speaking to Arvind, we have a couple approaches for resolution.  Can we get it slotted for an upcoming release?  I believe it warrants fixing the regression over more changes to UI that users will have to adapt to.

**Comment by ronhorton** [comment]
Still an issue - Alerts do not contain cluster name in 2.6.9-rc1

**Comment by geethub97** [comment]
I have added a new cluster-id label to all existing Prometheus Recording rules within the monitoring chart. However, for any new rules created from the UI, we will need to make that change on the UI itself, and add another default label.  

Related Ticket: https://github.com/rancher/dashboard/issues/7513

**Comment by ronhorton** [comment]
**No cluster name reported in alerts by default**

The default includes the cluster id, but does not include the cluster name. this is true in 2.6.12 and 2.7.2

**Comment by ronhorton** [comment]
testing blocked by https://github.com/rancher/dashboard/issues/8902

**Comment by ronhorton** [comment]
**Pass** verified in `2.7-head commit ID 707d173`
clustername now included by default in alert labels. 
![2023-05-22_21-01-21.png](https://zube.io/files/rancher/8b18a8800ad879e6ebdb2fa62d34d0dc-2023-05-22_21-01-21.png)
![2023-05-22_21-02-03.png](https://zube.io/files/rancher/0fb8442ac530ca440b774958e700b273-2023-05-22_21-02-03.png)
