### ISSUE TITLE
Unable to install/upgrade some helm charts - got status code 413

### ISSUE THREAD

**Issue by jorotg** [rancher/rancher#37138]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option Docker install/Helm Chart): Docker install on 3 node cluster
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Let's Encrypt certificate

**Information about the Cluster**
- Kubernetes version: v1.21.4
- Cluster Type (Local/Downstream): Imported self-hosted Vanilla k8s cluster in vCenter 7.0
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Owner

   
**Describe the bug**
When I try to install or upgrade some "bigger" helm charts (kube-prometheus-stack, Thanos) I get the following error:
UPGRADE FAILED: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets). If I kubeconfig file /etc/kubernetes/admin.conf retrieved from the master node the installation completes fine.

**To Reproduce**
- Install vanilla k8s cluster in vCenter
- Import that cluster into Rancher
- Attempt to install kube-prom-stack (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

**Result**
INSTALLATION FAILED: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)

**Expected Result**
Installation/upgrade succeeds.

**Screenshots**
Unnecessary.

**Additional context**
We don't have load balancer in front of the Rancher cluster. Just using DNS round-robin.

**Comment by ehsank777** [comment]
Have the same issue with deploying `kube-prom-stack` . Apparently it has some thing to do with using secretes as the helm backend storage driver. If you do `export HELM_DRIVER=configmap` it works fine. I am wondering if it has something to do with #37060 or no.

**Comment by Alan-R** [comment]
Having the same issue as well.

**Comment by mikejoh** [comment]
> Having the same issue as well.

@Alan-R We had this issue as well. The 413 status code came from the Pods handling the `Ingress` logic within the Rancher MGMT cluster not the Kubernetes API itself.

See [this](https://github.com/prometheus-community/helm-charts/issues/2518) issue over at the repository hosting the `kube-prometheus-stack` chart.

Stack Overflow [thread](https://stackoverflow.com/questions/49918313/413-error-with-kubernetes-and-nginx-ingress-controller) about this, a good read with comments that summarizes the issue and how to fix it.

To fix this it's possible to reconfigure the Rancher MGMT cluster `Ingress` using [this annotation](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size).

That `kube-prometheus-stack` helm release `Secret` is a bit over 1MB, which is the default setting for `client_max_body_size` hence the 413 Entity too large error response from Nginx Pods.

> Have the same issue with deploying `kube-prom-stack` . Apparently it has some thing to do with using secretes as the helm backend storage driver. If you do `export HELM_DRIVER=configmap` it works fine. I am wondering if it has something to do with #37060 or no.

@ehsank777 We did try this also, but since the default helm driver is `Secret` it became confusing to list all installed charts.

**Comment by charles-horel-rogers** [comment]
If you are running into this issue when deploying using helm from gitlab, using kas, as well as the gitlab provided ingress, this can be mitigated by modifying your gitlab deployment to add this annotation to the ingress:

gitlab:
  kas:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 8m

**Comment by snps-sagarrao** [comment]
Using **_export HELM_DRIVER=configmap_** fixed the error message below for me. Thank you.

> Error: INSTALLATION FAILED: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)


```
helm repo add seldonio https://storage.googleapis.com/seldon-charts
helm repo update
kubectl create namespace seldon-system
helm install seldon-core-operator seldonio/seldon-core-operator --namespace seldon-system

```
https://github.com/SeldonIO/seldon-core/tree/v1.17.1/helm-charts/seldon-core-operator

**Comment by nookseal** [comment]
> Using **_export HELM_DRIVER=configmap_** fixed the error message below for me. Thank you.
> 
> > Error: INSTALLATION FAILED: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)
> 
> ```
> helm repo add seldonio https://storage.googleapis.com/seldon-charts
> helm repo update
> kubectl create namespace seldon-system
> helm install seldon-core-operator seldonio/seldon-core-operator --namespace seldon-system
> ```
> 
> https://github.com/SeldonIO/seldon-core/tree/v1.17.1/helm-charts/seldon-core-operator

Where did you run export HELM_DRIVER=configmap?
on Master node or somewhere
