### ISSUE TITLE
Self added Route53 CNAME being removed

### ISSUE THREAD

**Issue by dax0** [rancher/rancher#3716]
I have the Route53 DNS container running.  It seems to be populating my Zone file with the correct records for my exposed services but when I try to add another record CNAME-ing to one of them Rancher deletes it promptly.

Example: oregon.mydomain.com -> haproxy.default.oregon.mydomain.com

This gets removed within a minute.  Any ideas what's going on?

**Comment by deniseschannon** [comment]
Rancher manages the record sets ending with "environment_name.root_domain". If you add something extra to it on Route53 side, and the record is not present on Rancher side, its going to be removed by Rancher to ensure the records are in sync.

**Comment by dax0** [comment]
I'm not modifying the rancher created record, I'm adding a new one.  It doesn't seem correct logic to assume rancher owns everything *.environment_name.root_domain and can therefore delete it

**Comment by alena1108** [comment]
@dax0 unfortunately there is no other way for us to determine "our" records today rather than make this assumption. AWS doesn't let you set metadata that could possibly identify rancher specific records. And we did have to implement cleanup part to handle the case when:

a) service has AWS Route53 record programmed 
b) service is removed
c) route53 rancher service does Rancher-AWS sync up, can no longer find the AWS service's record on rancher metadata server, so it removes it from AWS.

**Comment by cllunsford** [comment]
Is it possible for the route53-rancher service to store its state somewhere?  Maybe #2484 or in a volume?

Possible workarounds short of making the service stateful:

- During syncup, limit the purge to records that match the enforced syntax `service.stack.environment.domain` instead of blindly deleting `*.environment.domain`.  This would still incorrectly wipe user CNAMEs that happen to match the syntax but would leave `cname.environment.domain` alone, which (for me) is a more common use case.
- During syncup, limit the purge to records that match both `environment.domain` and `ttl`.  I could then configure rancher-route53 to use a unique ttl like `299` instead of `300` to ensure there was no overlap with my own records.  Downside here is that records would get orphaned if the user changes the configured TTL of the rancher service.

Either of these could be options that are off by default to preserve the present behavior.

**Comment by dax0** [comment]
My primary use case is for a CNAME `*.environment.mydomain.com` so @cllunsford first suggestion would work for me

**Comment by alena1108** [comment]
@cllunsford @dax0 

>> During syncup, limit the purge to records that match the enforced syntax service.stack.environment.domain instead of blindly deleting *.environment.domain. This would still incorrectly wipe user CNAMEs that happen to match the syntax but would leave

Thats possible, although it would solve cover some of the use cases

>> During syncup, limit the purge to records that match both environment.domain and ttl. I could then configure rancher-route53 to use a unique ttl like 299 instead of 300 to ensure there was no overlap with my own records. Downside here is that records would get orphaned if the user changes the configured TTL of the rancher service.

I like this :)

**Comment by alena1108** [comment]
We are going to apply following fix for now - remove only records that:

* end with *.envName.domain.com - with . prepended
* only having TTL = TTL defined on the template

And TTL on the template will be changed to non-trivial 299. That fix should cover the majority of the user cases.

In the future, we might rework it by saving all A records generated by Rancher, in a single rancher-config TXT record on Route53; so the removal will be done only when A record's fqdn is present in the record.

**Comment by alena1108** [comment]
@prachidamle , it would require 2 fixes - one for external-dns component, another in template

**Comment by prachidamle** [comment]
@alena1108 this will need a new template for route53

**Comment by prachidamle** [comment]
Assigning to @alena1108, to release external-dns with new template.

**Comment by alena1108** [comment]
External dns v0.3.0 is released, please follow up on template creation

**Comment by prachidamle** [comment]
Submitted new route53 template PR https://github.com/rancher/rancher-catalog/pull/116

**Comment by sangeethah** [comment]
Tested with latest build from master and "Route53 DNS" version- v0.3.0-rancher1.

Route53 CNAME entries with format *.<env-name> .<domain-name> / *<env-name> .<domain-name> that get added manually , do not get deleted by rancher-server when route53 entries are being programmed.


Also Route53 A entries with format *<env-name> .<domain-name>  dose not get removed.

There is 1 more additional check that can be done before deleting "A" records tracked in
https://github.com/rancher/rancher/issues/4066

**Comment by sangeethah** [comment]
@dax0 fix for this issue will be available in the next release.
