### ISSUE TITLE
rancher token command generates new token and the old one becomes invalid

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37245]
SURE-4163

**Rancher Server Setup**
Rancher Cluster:
Rancher version: 2.6.3
Number of nodes: 5
Node OS version: RHEL7.9

Downstream Cluster:
Number of Downstream clusters: 5
Node OS: RHEL 7.9
RKE/RKE2/K3S version: 1.20.8
Kubernetes version: 1.20.8
CNI: calico

   
**Describe the bug**
After upgrading rancher to version 2.6.3, we are seeing the "rancher token" command can cause the old token on the server to get overwritten.

With rancher 2.5.9 I see this (good) behavior:

Run the token command using one config directory:
$ rancher --config=$HOME/tmp/rancher1 token --auth-provider=openLdapProvider --server=our-2.5.9-server --user=my-kubecontext-user
INFO[0000] Saving config to [....]/tmp/rancher1/cli2.json
Enter credentials for openLdapProvider
Enter username: myuserid
Enter password:
INFO[0007] Saving config to [....]/tmp/rancher1/cli2.json
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{},"status":{"expirationTimestamp":"2022-02-11T04:16:39Z","token":"kubeconfig-user-XXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"}}

Run the token using a different config directory (since using new config directory will be prompted for userid and password again):
$ rancher --config=$HOME/tmp/rancher1 token --auth-provider=openLdapProvider --server=our-2.5.9-server --user=my-kubecontext-user
INFO[0000] Saving config to [....]/tmp/rancher2/cli2.json
Enter credentials for openLdapProvider
Enter username: myuserid
Enter password:
INFO[0027] Saving config to [....]tmp/rancher2/cli2.json
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{},"status":{"expirationTimestamp":"2022-02-11T04:16:39Z","token":"kubeconfig-user-XXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"}}

In the above the exact same token is returned in both calls (even though there were two separate logins). Additional calls to "rancher token" using either of the above two config directories will continue returning this token with no username and password prompt (since the expirationTimestamp is not passed).

We are using this "rancher token" command in our kubeconfig files as a kubectl exec plugin and it works great. Until the token expires, kubectl commands run without any username/password prompt. After they expire, then we are prompted again and the token is refreshed.

The exec plugin functionality is still working for us in 2.6.3, except when we have a separate config directory (i.e. simulating a login from two different hosts). With 2.6.3 a new token is issued on each login and the old token is no longer valid. When I look at the /apikeys url I only see the most recent of the two tokens are present. From that it makes sense that the old token is invalid now.

Here are the full details of the rancher 2.6.3 (bad) behavior:

Run the token command using one config directory:
$ rancher --config=$HOME/tmp/rancher1 token --auth-provider=openLdapProvider --server=our-2.6.3-server --user=my-kubecontext-user
INFO[0000] Saving config to [....]/tmp/rancher1/cli2.json
Enter credentials for openLdapProvider
Enter username: myuserid
Enter password:
INFO[0007] Saving config to [....]/tmp/rancher1/cli2.json
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{},"status":{"expirationTimestamp":"2022-02-11T04:16:39Z","token":"kubeconfig-user-XXXX:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"}}

Run the token using a different config directory (since using new config directory will be prompted for userid and password again):
$ rancher --config=$HOME/tmp/rancher1 token --auth-provider=openLdapProvider --server=our-2.6.3-server --user=my-kubecontext-user
INFO[0000] Saving config to [....]/tmp/rancher2/cli2.json
Enter credentials for openLdapProvider
Enter username: myuserid
Enter password:
INFO[0027] Saving config to [....]tmp/rancher2/cli2.json
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{},"status":{"expirationTimestamp":"2022-02-11T04:16:39Z","token":"kubeconfig-user-XXXX:ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"}}

The second login returns a different token and the first one is no longer valid

$ rancher --version
rancher version v2.4.11
(same happens with latest 2.6.0 version as well).

**To Reproduce**
unable to repro

**Result**
CLI operation seems to have changed between API versions when it comes to renewing tokens

**Expected Result**
CLI should operate similarly between versions.

**Comment by KevinJoiner** [comment]
I was able to reproduce and viewed that rancher server 2.5 does behave differently than 2.6.
This change in behavior was made with [this PR](https://github.com/rancher/rancher/pull/33189).

**Comment by KevinJoiner** [comment]
## Root Cause
The Rancher server creates a new token value every time a kubeconfig is requested via the CLI which invalidates the previously created tokens.

## What was fixed, or what change has occurred?
Rancher server now generates a new token every time a kubeconfig is requested via the CLI. This token is then cached by the CLI on the local system.

## Areas or cases that should be tested
We need to test the TTL gets set correctly on tokens requested through the following paths: 

1. Install the latest rancher CLI so that it is accessible in your PATH
2. Create a new rancher server.
3. Update `kubeconfig-generate-token` to 'false' `https://<rancher-server>/v3/settings/kubeconfig-generate-token`
4. Download kubeconfig for the local cluster
5. Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
6. Repeat steps 4-5 on a different machine, but with the same user.
7. Verify kubectl can be used for cluster communication on both machines with their downloaded KUBECONFIGs. `kubectl get pods -A`



## What areas could experience regressions
  Using kubeconfigs with `kubeconfig-generate-token` set to false.
## Are the repro steps accurate/minimal?
Steps to reproduce the issue.
1. Install the latest rancher CLI so that it is accessible in your PATH
2. Create a new rancher server.
3. Update `kubeconfig-generate-token` to 'false' `https://<rancher-server>/v3/settings/kubeconfig-generate-token`
4. Download kubeconfig for the local cluster
5. Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
6. Repeat steps 4-5 on a different machine, but with the same user.
7. Check cluster communication on both machines with their downloaded KUBECONFIGs. `kubectl get pods -A`

**Result**
Only the second machine's token is valid.

**Expected** 
Both machines contain valid tokens.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type   |
| ------------------------- | ---------------- |
| Rancher version           | 2.6.5            |
| Installation option       | helm             |
| RKE binary version used   | v1.3.11          |
| If Helm Chart k8s cluster | rke1 	v1.23.6    |
| Cert Details              | let's encrypt    |
| Helm version              | v2.16.8-rancher1 |
| Downstream cluster type   | not applicable   |
| Downstream K8s version    | not applicable   |
| Logged in user role       | administrator    |
| Browser type              | google chrome    |
| Browser version           | 102.0.5005.115   |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$REDACTED \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$REDACTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5
```

## Reproduction steps

1. Install the latest rancher CLI so that it is accessible in your PATH
2. Create a new rancher server.
3. Update kubeconfig-generate-token to 'false' `https://<rancher-server>/v3/settings/kubeconfig-generate-token`
4. Download kubeconfig for the local cluster
5. Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
6. Repeat steps 4-5 on a different machine, but with the same user.
   1. Create a Linode Ubuntu instance
   2. Run these commands / similar depending on your situation and setup

```shell
# download latest release of kubectl
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

# download the kubectl checksum file
curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"

# validate the kubectl binary against the checksum file
echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

# If valid, the output is:
# kubectl: OK

# install kubectl 
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

kubectl version --client

# start install of rancher cli

 wget https://github.com/rancher/cli/releases/download/v2.6.5/rancher-linux-amd64-v2.6.5.tar.xz
 
 tar xf rancher-linux-amd64-v2.6.5.tar.xz 

 chmod +x rancher 

 PATH="$(pwd):$PATH"

 rancher login $RANCHER_URL_WITH_HTTPS --token $RANCHER_BEARER_TOKEN

```
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Expected Both machine's to have valid tokens

#### :x: Actual
Only the second machine's token is valid

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.6-9bcffaa9cb7259a223280de1c50050a443267362-head                                 |
| Rancher commit link       | https://github.com/rancher/rancher/commit/9bcffaa9cb7259a223280de1c50050a443267362 |
| RKE binary version used   | v1.3.11                                                                            |
| If Helm Chart k8s cluster | rke1 	v1.23.6                                                                      |
| Cert Details              | let's encrypt                                                                      |
| Helm version              | v2.16.8-rancher1                                                                   |
| Downstream cluster type   | not applicable                                                                     |
| Downstream K8s version    | not applicable                                                                     |
| Logged in user role       | administrator                                                                      |
| Browser type              | google chrome                                                                      |
| Browser version           | 102.0.5005.115                                                                     |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$REDACTED \
  --set letsEncrypt.email=$REDACTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5 \
  --set rancherImageTag=v2.6-head
```

## Validation steps

1. Install the latest rancher CLI so that it is accessible in your PATH
2. Create a new rancher server.
3. Update kubeconfig-generate-token to 'false' `https://<rancher-server>/v3/settings/kubeconfig-generate-token`
4. Download kubeconfig for the local cluster
5. Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
6. Repeat steps 4-5 on a different machine, but with the same user.
   1. Create a Linode Ubuntu instance
   2. Run these commands / similar depending on your situation and setup

```shell
# download latest release of kubectl
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

# download the kubectl checksum file
curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"

# validate the kubectl binary against the checksum file
echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

# If valid, the output is:
# kubectl: OK

# install kubectl 
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

kubectl version --client

# start install of rancher cli

 wget https://github.com/rancher/cli/releases/download/v2.6.5/rancher-linux-amd64-v2.6.5.tar.xz
 
 tar xf rancher-linux-amd64-v2.6.5.tar.xz 

 chmod +x rancher 

 PATH="$(pwd):$PATH"

 rancher login $RANCHER_URL_WITH_HTTPS --token $RANCHER_BEARER_TOKEN

```
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Both machines have valid tokens

#### :white_check_mark: Actual
Both machines have valid tokens

**Comment by samjustus** [comment]
@brudnak could you check if this also resolves https://github.com/rancher/rancher/issues/37992 ?

**Comment by Waleedghuman** [comment]
how can i get rancher's bearer token with rancher cli...??
