### ISSUE TITLE
rke2 cluster in "hang" state following deletion by standard user

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#37240]
**Setup**
- Rancher version: `2.6.4-rc8`
- Browser type & version: `Chrome - Version 99.0.4844.51 (Official Build) (arm64)`

**Describe the bug**
When a standard user deletes an rke2 custom cluster (as `cluster-owner`), UI "hangs" on `Waiting for machine [machine_id] to delete`. 

**To Reproduce**
1. Fresh install of rancher `v2.6.4-rc8`
2. As admin, create a standard user
3. As standard user, create a cluster (`rke2 custom`)
4. As standard user, delete the cluster
5. Reproduced 

**Result**
cluster is deleted and cluster role binding is removed; UI stuck in "hang" state

**Expected Result**
cluster is deleted, cluster is removed from UI

**Screenshots**
<img width="1484" alt="157498573-611091cd-6ab9-418f-ac4a-25658b54d6b7" src="https://user-images.githubusercontent.com/46494969/158278245-384d8573-65b3-4106-aa95-ff4d06d2edd7.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by aalves08** [comment]
I have been investigating the issue and I am quite certain that the issue is backend related.

Looking into the Websocket messages for the deletion of a RKE1 cluster as **_admin_**, here are the most relevant messages received:
`provisioning.cattle.io`
<img width="1811" alt="Screenshot 2022-04-07 at 16 01 25" src="https://user-images.githubusercontent.com/97888974/162407346-7edfafea-b51a-495b-aa57-a3ec0b4b68da.png">


`management.cattle.io`
<img width="1811" alt="Screenshot 2022-04-07 at 16 01 20" src="https://user-images.githubusercontent.com/97888974/162407354-538b4510-283e-4acb-9893-c0baf6627bbb.png">


For a **_standard user_**:
only `management.cattle.io`
<img width="1811" alt="Screenshot 2022-04-07 at 16 29 11" src="https://user-images.githubusercontent.com/97888974/162407412-ed441b62-2d55-4897-ae29-2345287dee5f.png">


What we are missing on the FE side is the `provisioning.cattle.io` message about removal of the cluster while as a **_standard user_**, which is responsible for the removal on the FE (which we never receive), hence why the FE is not "live updated" (item removed from the list) but does in fact disappear once we refresh it.

**Comment by aalves08** [comment]
@gaktive issue transferred

**Comment by snasovich** [comment]
This issue seems to be exactly the same as https://github.com/rancher/rancher/issues/36072.
@Josh-Diamond , could you please review and close this one if you agree with this and we'll track the work on this in https://github.com/rancher/rancher/issues/36072?

**Comment by Josh-Diamond** [comment]
CONFIRMED - This issue is a duplicate of #36072 ; Issue will be tracked, resolved, and closed there.
