### ISSUE TITLE
Imported AKS Cluster Cannot Be Deleted in the Rancher UI

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#37256]
**Rancher Server Setup**
- Rancher version: `2.6-head` (2.6.4)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21.7
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Downstream imported AKS cluster 3-5 node, imported via Rancher UI

**Describe the bug**

The AKS cluster was created in AKS and imported via the Rancher UI successfully. I delete the cluster in the Rancher UI and then deleted the cluster in Azure. The cluster in Azure was not fully terminated (not sure why), and the Rancher UI threw this error on deletion.

![image](https://user-images.githubusercontent.com/12955547/162773919-9dcbfa0f-b37e-4573-bb19-a9ab0edd6390.png)

These finalizers are leftover on the cluster

```
finalizers:
  - controller.cattle.io/cluster-agent-controller-cleanup
  - controller.cattle.io/mgmt-cluster-rbac-remove
```

The error is

```
Post "[https://ablender-aks-podcount-test-dns-ef17b65d.hcp.eastus.azmk8s.io:443/apis/rbac.authorization.k8s.io/v1/clusterroles?timeout=45s](https://ablender-aks-podcount-test-dns-ef17b65d.hcp.eastus.azmk8s.io/apis/rbac.authorization.k8s.io/v1/clusterroles?timeout=45s)": dial tcp: 
lookup ablender-aks-podcount-test-dns-ef17b65d.hcp.eastus.azmk8s.io on 10.43.0.10:53: no such host
```

on the `cluster-agent-controller-cleanup`.

**To Reproduce**
 

- Create an AKS 3 node downstream cluster in Azure
- Import it via the Rancher UI
- Delete the cluster via the Rancher UI and in Azure

**Result**

The cluster hangs with the above error in the Rancher UI.

**Expected Result**

The cluster should be successfully deleted in the Rancher UI.

**Comment by thedadams** [comment]
### Root cause
If there was an error that wasn't an `agent disconnected error` when the imported cluster is removed from Rancher, then the deletion will hang and won't move forward.

### What was fixed, or what changes have occurred
Now, on any error, Rancher will retry three times to cleanup the downstream cluster. If it fails after the third time, then Rancher will move on with cluster removal.

### Areas or cases that should be tested
1. Deleting imported KEv2 cluster that is unavailable. The cluster will be removed very quickly from the Cluster Management page, but will stick around in the Home page. After a few minutes (it takes a while to retry), the cluster should be removed from the Home page. All KEv2 clusters are handled the same way in this part of Rancher, so I don't think each one should be tested. However, if there is time for this thoroughness, then it may be a good idea to test all three KEv2 providers.
2. Deleting imported cluster that is available. A few minutes after the cluster is removed from Rancher, ensure that the `cattle-system` namespace and `cattle-cluster-agent` deployment are removed from the downstream cluster. This should be tested to ensure the desired functionality hasn't changed.

### What areas could experience regressions?
Deleting imported clusters.

### Are the repro steps accurate/minimal?
Yes.

**Comment by Josh-Diamond** [comment]
Ticket #37256 - Test Results

With Docker on single-node instance:

Reproduced on rancher `v2.6-7b6d1a222a2f60e77e94f28bfa0f2f8b52c3aa9c-head`:
1. Fresh install of rancher `v2.6-head`
2. In Azure, create an AKS 3-node downstream cluster
3. Import AKS cluster via Rancher UI
4. Delete AKS cluster via Rancher UI, then in Azure
5. Reproduced - Imported AKS cluster fails to delete; hangs in `Removing` state with errors

Screenshots:

`Cluster Management`
<img width="1254" alt="Screen Shot 2022-04-18 at 1 43 08 PM" src="https://user-images.githubusercontent.com/46494969/163874953-232580ec-357a-4b74-a494-5aa10404598f.png">

`Docker logs`
<img width="1252" alt="Screen Shot 2022-04-18 at 1 42 47 PM" src="https://user-images.githubusercontent.com/46494969/163875030-90efea40-7f0b-458b-8581-95017151f0cb.png">


Verified on rancher `v2.6-6c12bee2d0bee16a2854df5471aaa0cdee5b9bf1-head`:
1. Fresh install of rancher `v2.6-head`
2. In Azure, create an AKS 3-node downstream cluster
3. Import AKS cluster via Rancher UI
4. Delete AKS cluster via Rancher UI, then in Azure
5. Verified - Imported AKS cluster successfully deleted w/ clean logs
