### ISSUE TITLE
[rke2 windows] node information is not correct for k8s version, metrics, or external IP

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37288]
**Rancher Server Setup**
- Rancher version: v2.6-head (cd0555b)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 1.22.7, 1.3.9
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: v1.23.5+rke2r1 (also observed on 1.22.x, 1.21.x)
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom (windows)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

   
**Describe the bug**
* windows node(s) don't display proper info for metrics, k8s version or the external IP address
* the windows node doesn’t show anything after the k8s patch number? (other nodes show *+rke2r1)
* external IP display for the windows node
* metrics don't show for the windows node (cpu, memory, pods)

**To Reproduce**
* deploy a windows custom cluster using rke2
* once the cluster is ready, deploy monitoring v2

**Result**
other nodes display correct info, but windows node does not. 

**Expected Result**
windows node should display the same information as linux clusters

**Screenshots**
<img width="1481" alt="Screen Shot 2022-04-12 at 1 23 24 PM" src="https://user-images.githubusercontent.com/16691014/163049829-e4435fab-ce67-4dcc-ac47-98f89d7e04d4.png">

**Comment by phillipsj** [comment]
@slickwarren which version of windows? 

The Kubernetes versions aren't expected to match. We use upstream K8s for Windows currently so it will not display the information after the patch number.

Metrics appear to be working fine in the cluster with both Windows 2019 and 2022.  I just created using Rancher 2.6-head and RKE2 1.23.5+rke2r1. I think possible firewall/NSG settings could be causing some issues since this is in AWS. There is also the possibility that the source destination check could also be impacting it.

![image](https://user-images.githubusercontent.com/1568133/163190219-89777a5a-fbb9-4505-9bab-9f649ec1d273.png)

As far as the external IP issue, for custom clusters you need to pass the flags. The info can be found in this GH Issue: https://github.com/rancher/windows/issues/91

**Comment by slickwarren** [comment]
@phillipsj  have this firewall setting on the windows node. I went and applied the source destination check, and now pods are showing metrics but get n/a for cpu/memory(which is the opposite of your screenshot in the ticket). does the firewall look right?

this is a windows 2022 node
```
New-NetFirewallRule -DisplayName "Allow TCP Node Port traffic" -Direction Inbound -Action Allow -EdgeTraversalPolicy Allow -Protocol TCP -LocalPort 30000-32767
```
<img width="1342" alt="Screen Shot 2022-04-13 at 12 24 28 PM" src="https://user-images.githubusercontent.com/16691014/163255903-e9a0f180-1ad3-4ac4-8f08-4f8ba7d09499.png">

**Comment by phillipsj** [comment]
@slickwarren have you tried turning it off and see what happens. I think we may be missing a rule that needs to be added.

**Comment by jameson-mcghee** [comment]
Caleb and I followed the steps to reproduce while also checking the "Stop" check box for **Source/destination checking** in EC2, and after rebooting the instance with that change, the **Pods** information was listed (see screenshot). Therefore this ticket was closed.

![image](https://user-images.githubusercontent.com/13294321/174877866-40f58495-c22c-4ba7-9b3e-3e00a11adfad.png)
