### ISSUE TITLE
v2.6.5 Release Task - Prepare Draft PRs for releasing charts.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37326]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/37315) for the rancher engineering team 3 & the Release captain to:

- [] System-Charts: Make a PR from the dev branch into the release-branch. Review to make sure the system charts seem aligned with what’s expected. The title of the PR should be the release vehicle that all the system charts are being added for.
- [] Charts: See the checklist for specific information.

**Comment by PennyScissors** [comment]
Charts v2 PR: https://github.com/rancher/charts/pull/1885

There is no draft PR for system charts, or rancher/charts dev->master because we don't have any new charts in those repos/branches to release. This will be a charts v2 only release (unless stuff gets merged last minute, which shouldn't be the case, but I'll watch out for that).

diff system-charts: https://github.com/rancher/system-charts/compare/release-v2.6...dev-v2.6

diff rancher/charts dev->master: https://github.com/rancher/charts/compare/master..dev

**Comment by PennyScissors** [comment]
Charts for v2.6.5 are released
