### ISSUE TITLE
Ability to edit catalogue entries that expose ports to different ports (due to many catalog entries using port 80)

### ISSUE THREAD

**Issue by opichon** [rancher/rancher#3732]
A number of catalogues are configure to expose port 80 on the host (e.g. ghost, owncloud). How can I add 2 such catalogues without create a port conflict? On the other hand,m catalogues are not editable.

Am I missing something obvious here? 

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
| Access | `github` `admin` |
| Route | `null` |

**Comment by deniseschannon** [comment]
I've made this into a more general catalog enhancement request for ports, but it's similar to this request. https://github.com/rancher/rancher/issues/2974 In that issue, you can see how you can copy the docker-compose.yml/rancher-compose.yml so that you could add your own stack and change the port. 

This request requires changes to all [Rancher catalog entries](https://github.com/rancher/rancher-catalog) or [community catalog entries](https://github.com/rancher/community-catalog)  from a static port to an option to declare a port with a default port of 80. Feel free to make some PRs to specific catalog entries that you want to be able to edit the port. :) Please note that we won't be maintaining the community-catalog entries. 

http://docs.rancher.com/rancher/catalog/#questions-in-the-rancher-compose-yml

**Comment by piotron** [comment]
There's also option to create stack without starting, and do upgrade services where you can remove used bindings. It requires additional work but it's better than downloading and pushing yml files.

**Comment by deniseschannon** [comment]
@piotron We are actually adding the ability to change scale, ports and labels for catalog templates, which should be available in the UI for v1.2.0.

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.2.0-pre4-rc1.

While creating stack , we now provide the ability to override "labels" and ""ports" that are specified in docker-compose/rancher-compose.yml files by passing bindings parameter.

Need UI support for exposing the bindings parameters.

**Comment by vincent99** [comment]
#2852
