### ISSUE TITLE
CIS scans fail on a hardened rke2 cluster with multiple roles

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37397]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head 6c12bee
- Installation option (Docker install/Helm Chart): Helm Chart and Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.8, v1.3.10-rc3
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.22.8+rke2r1
- Cluster Type (Local/Downstream): `Downstream custom 1 worker, 1 etcd, 1 cp RKE2`

**Describe the bug**
When I run CIS scans - 1.6 hardened, 1.5 hardened, 1.6 permissive and 1.5 permissive, I see 92 failures reported in all of the scans. This is seen happening when a custom rke2 cluster is provisioned with different roles on different nodes. If we run the scans against a cluster with all roles enabled on all of the nodes, we get a pass result.

**To Reproduce**
1. Create a custom rke2 cluster by following steps from this comment https://github.com/rancher/rancher/issues/36629#issuecomment-1100426864
2. Install CIS benchmark 2.0.3 version
3. Run CIS scans - 1.6 hardened, 1.6 permissive, 1.5 hardened, 1.5 permissive 

**Result**
All the 4 scans have 92 failures as shown in the screenshot below. Logs in the rancher pods seen:
```
2022/04/19 04:28:36 [ERROR] defaultSvcAccountHandler: Sync: error handling default ServiceAccount of namespace key=cattle-fleet-system, err=Operation cannot be fulfilled on namespaces "cattle-fleet-system": the object has been modified; please apply your changes to the latest version and try again
```

**Expected Result**
Expected the scans to go thorugh

**Screenshots**
<img width="500" alt="cisrke2" src="https://user-images.githubusercontent.com/38144301/164048487-40b4261c-471b-43bc-8421-eb41e0102386.png">

**Additional context**
Found while validating https://github.com/rancher/rancher/issues/36629

**Comment by thedadams** [comment]
This is a known issue with the cis-operator: https://github.com/rancher/cis-operator/issues/107

Moving this issue to team3 since the above issue is assigned to them as well.

**Comment by snasovich** [comment]
@thedadams , thank you for your investigation.
@SheilaghM & @MKlimuszka , FYI

**Comment by SheilaghM** [comment]
@samkulkarni20 please take a look at this on Monday and advise in standup.

**Comment by dhruvmewada15** [comment]
Of all ~92 failures in all 4 test scan profiles 1.6 hardened, 1.5 hardened, 1.6 permissive and 1.5 permissive - the majority are of master node. Because there is a mismatch in taint and the toleration, master node related tests are failing for which the fix is already there in [rancher/cis-operator](https://github.com/rancher/cis-operator/pull/150). Please use [rancher/cis-operator:v1.0.8-rc2](https://github.com/rancher/cis-operator/releases/tag/v1.0.8-rc2) to use the fix and failed scan will come down to 3 to 7. (Refer to the screenshot below)

![image](https://user-images.githubusercontent.com/26231966/165115782-d5d2c247-1867-46d6-9d11-b0351bcb57fd.png)


However there are some additional 3 to 7 etcd and RBAC related tests failing in different 4 profiles. I am currently debugging those tests. Will update here if I find anything.

**Comment by anupama2501** [comment]
@dhruvmewada15 as you mentioned I Installed cis 2.0.3 with cis-operator updated to v1.0.8-rc2 and yes the failures were significantly reduced:
```
> kubectl get clusterscans
NAME         CLUSTERSCANPROFILE                TOTAL   PASS   FAIL   SKIP   WARN   NOT APPLICABLE   LASTRUNTIMESTAMP       CRONSCHEDULE
scan-nl6w2   rke2-cis-1.5-profile-hardened     122     80     7      0      25     10               2022-04-26T20:35:13Z   
scan-qk58x   rke2-cis-1.5-profile-permissive   122     72     6      0      25     19               2022-04-26T20:35:37Z   
scan-rs7qm   rke2-cis-1.6-profile-hardened     122     87     4      0      25     6                2022-04-26T20:34:30Z   
scan-rvtxc   rke2-cis-1.6-profile-permissive   122     67     3      0      40     12               2022-04-26T20:35:27Z   
```

**Comment by dhruvmewada15** [comment]
This issue needs to be tested on both single node and multi node for both hardened and non hardened cluster as there were also additional failures found in single node non hardened cluster which were fixed in the [PR](https://github.com/rancher/security-scan/pull/73)

**Steps to Validate for multi node hardened cluster:**
**_Note : Refer to this [comment](https://github.com/rancher/rancher/issues/36629#issuecomment-1100426864) for instruction for RKE2 hardening guide_**
- Deploy Rancher Server: `v2.6-head`
- Deploy downstream multi node (1 worker, 1 etcd, 1 cp) hardened RKE2 cluster : k8s version: `v1.22.8+rke2r1`
- Install `rancher-cis-benchmark:v2.0.4-rc1`
- Run CIS Scan with `rke2-cis-1.6-hardened, rke2-cis-1.6-permissive, rke2-cis-1.5-hardened, rke2-cis-1.5-permissive`.

**Expected Result:**
All the scan should **PASS** successfully.

**Steps to Validate for single node non hardened cluster:**

- Deploy Rancher Server: `v2.6-head`
- Deploy downstream single node permissive RKE2 cluster : k8s version: `v1.22.8+rke2r1`
- Install `rancher-cis-benchmark:v2.0.4-rc1`
- Run CIS Scan with `rke2-cis-1.6-permissive and rke2-cis-1.5-permissive`.

Both the scan should **PASS** successfully.

**Comment by anupama2501** [comment]
https://github.com/rancher/charts/pull/1884 -- waiting on charts PR

**Comment by dhruvmewada15** [comment]
@anupama2501 Did you run below step for network policies? Can you please try below step and try once again.

- Create `default-allow-all.yaml`
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-all
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress

```

- Create a bash script file called apply_networkPolicy_to_all_ns.sh. Be sure to chmod +x apply_networkPolicy_to_all_ns.sh so the script has execute permissions.
#!/bin/bash -e
```

for namespace in $(kubectl get namespaces -A -o json | jq -r '.items[].metadata.name'); do
  kubectl apply -f default-allow-all.yaml -n ${namespace}
done
```
