### ISSUE TITLE
ADFS Users cannot be used with Project Permissions

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37403]
**Rancher Server Setup**
Rancher version: 2.6.2

**Describe the bug**
Rancher is able to login successfully with ADFS but it is showing both ADFS user and corresponding local user( Type= standard, with user ID) while adding the user as a project member, also it is allowing to add both ADFS user as well as local user to the project for the same user ID.

**To Reproduce**
 

**Result**
The added ADFS / SAML User can never be used for adding permissions - so we would expect, that it should ether work to create permissions with the ADFS user or the ADFS user should not be shown

**Expected Result**
It should allow only one user per user id, either ADFS user or the corresponding local user.

SURE-4079

**Comment by samjustus** [comment]
@asemen2608 it was not, but we are planning to work on the above linked issue and we will try to also look at this one at the same time

**Comment by samjustus** [comment]
SURE-4152 as well

**Comment by nflynt** [comment]
Confirmed, this behavior is still happening as recently as `v2.7-c2423288d53210b4f1526e22c9e9ff18de1b24a8-head`. This is actually a SAML behavior, and affects any SAML-based auth provider that does not have a search backend configured.

The basic issue is that the SAML protocol does not provide a user lookup function, so Rancher is only able to search users that it already knows about. To facilitate assigning permissions for users that have not yet logged in, it also generates a dummied entry matching exactly what was typed. Several things are happening in the provided screenshot:

1. The first result is a dummied ADFS user matching exactly what was typed. On its own this is expected behavior
2. Rancher matches the typed string against an existing ADFS user, so it tries surfaces that result. For an **exact** match, we ideally want to avoid a duplicate. Rancher `v2.7-head` currently prefers the dummied result, which happens to work correctly as it is generated with a valid principalID. (This behavior **differs** from the reported version, which surfaced both results)
3. When Rancher matches an existing user that it knows about, it incorrectly returns the **Local** identifier for that user. When AFDS is enabled, this local identifier is routed through a lookup function to find the corresponding ADFS principal, and this fails due to a type mismatch. **This** behavior is still occurring in `v2.7-head` and results in broken permission assignments.

This is already a tricky situation because for pure SAML (incl. ADFS), we can't do the expected thing and include remote users in the list. The current solution is a compromise, but it is admittedly a bit fragile.

Proposed alternative behavior:

1. When Rancher matches an existing user, if that user belongs to an enabled Auth Provider, return this version of their principalID. Ensure these work properly for assigning permissions. (This should visually result in match results being of the "ADFS User" type)
2. For convenience, when sorting the list of matches, place known existing users first in the list, and dummied alternatives last. This shortens keyboard navigation for selecting the matched result.

**Comment by nflynt** [comment]
A quick update as my own understanding has expanded since my recent comments. When Rancher creates an ADFS user, under the hood it _also_ creates a "Local" principalID for that user. More generally, every user is always a Local user, and their ability to log in using another principal type depends on whether an auth provider has been linked to them.

For ADFS, since SAML doesn't provide a search function, Rancher pulls results from its local set of users instead. These use the Local principalID type and set the binding accordingly. Either binding is **supposed** to work for a given user. The UI looks a bit strange, but it reflects how Rancher is handling the search internally.

So long as the Local bindings _are working_ for assigning permissions, the general consensus is that searches are working as designed. If the local bindings aren't allowing permissions to be set for some reason, that may still be a bug. So far I've been unable to reproduce this second scenario: when I assign "Local" users from search results, they get the expected permissions. 

My current theory: if the auth provider changes how it generates principalIDs, either through Rancher auth configuration or something on the ADFS side, then new AFDS sessions are treated like new unique users. They would show up as a duplicate in the "Users" tab, and the new user would be unable to access permissions assigned to their old session. This may occur if the "uid" SAML field is set to something that may change, like the user's name or email address, or their position within the org hierarchy.

**Comment by AndrewHoffmanQA** [comment]
@nflynt does this sound like an accurate summary for this ticket so far? the user may have an issue with applying permissions to local users with an associated same user, however we can't reproduce it so far. and outside of that everything in this ticket is the system functioning as expected?

**Comment by nflynt** [comment]
@AndrewHoffmanQA Yes, that's basically the current understanding. There are ongoing discussions to perhaps greatly improve the auth+local users situation in terms of how users are represented internally within Rancher. As currently implemented however, as long as local bindings are resolving to the right user object, the behavior is working as designed.

Currently I'm working through the reconciliation code to see if we can't detect purely non-Local users (those with a local ID merely because the underlying system requires it) and, in those cases, prefer to use the Auth Provider principal ID instead. If that lands, it would change the default for project creation and require testing. Not sure if we'll get that change in ahead of the rework though; the ideal end goal is to not have one user end up with two principal IDs in the first place.

**Comment by nflynt** [comment]
Quick update: the high level plan is to separate Local and ADFS (really _any_ auth) users within Rancher. This issue, and several other counter-intuitive UX behaviors, fall out of there being two principal IDs that can both refer to the same user. Once those are separated, these "duplicate" IDs will no longer exist, and search results should exhibit fewer surprising behaviors.

That's a longer term project, and we'll want to make sure it's _thoroughly_ tested. We're currently working through a design proposal and I'll try to keep this ticket updated as that moves along.

**Comment by prachidamle** [comment]
https://jira.suse.com/browse/SURE-6693 feature ticket has been logged.

**Comment by samjustus** [comment]
this is being tracked in a feature request SURE_6693
