### ISSUE TITLE
Env Rename is not reflected in external DNS

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3742]
Rancher Version: 0.59.1

Docker Version: 1.10.2

OS: ubuntu

Steps to Reproduce: I just renamed my Environment from Default. I'm using the DNSsimple Service. 

Results: The rename of the ENV is not reflected in the DNS

Expected: a change of ENV name should be reflected in the external DNS

**Comment by vincent99** [comment]
@alena1108 Is there a reason we even have environment in there?  The container only manages the environment it's in.

**Comment by alena1108** [comment]
@vincent99 for unique identification on AWS route53 side as the same AWS route53 account can be used by multiple Rancher environments. We've discussed some time ago with you that environment.uuid should be used instead.

But the real bug here - environment name change doesn't trigger metadata update, while it should. We store environment_name under Stack metadata.

**Comment by sangeethah** [comment]
Tested with rancher-server version-v.0.63.0-rc2

Create an environment with name say - "abc".
Create a stack/service in this environment.

From within any container in this environment,  try to get environment_name from metadata using http://rancher-metadata/latest/self/stack/environment_name.

Make sure it reflects the correct value.

Change the name of the environment.

From within any container in this environment,  try to get environment_name from metadata using http://rancher-metadata/latest/self/stack/environment_name.

Updated environment name is returned.

@hwinkel , this fix will be available in the next release.
