### ISSUE TITLE
add `calico-apiserver` to list of rancher namespaces so that it doesn't show up in user namespace filters in 1.23 clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37433]
**Rancher Server Setup**
- Rancher version: v2.6-head (6c12bee)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, v1.3.10-rc3
- Proxy/Cert Details: valid letsencrypt certs

**Information about the Cluster**
- Kubernetes version: 1.23.5
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any (tested with vsphere node driver)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): any (tested with standard user, cluster owner)

   
**Describe the bug**
on a fresh install, the `calico-apiserver` workload/namespace are listed under user namespaces when rancher installed it during the provisioning process. 

**To Reproduce**
* deploy a 1.23 cluster using a node driver
* wait for the cluster to get to active state, and view workloads of the cluster with `only user namespaces` filter enabled (this is the default view)

**Result**
workloads are listed for calico-apiserver

**Expected Result**
user namespaces should be empty on a fresh install downstream cluster
**Screenshots**

<img width="826" alt="Screen Shot 2022-04-21 at 10 18 33 AM" src="https://user-images.githubusercontent.com/16691014/164561757-e5f0ddf4-7237-4e5f-a3de-33c5c44e7f38.png">

**Additional context**
this is net-new on 1.23

**Comment by jakefhyde** [comment]
Reassigned to team 3 because the UI decides how to classify things based on fields in the chart.

**Comment by bmdepesa** [comment]
@jakefhyde which chart are you referring to? This workload would be deployed when calico is selected as the CNI during cluster provisioning.

**Comment by jakefhyde** [comment]
### Root cause

`calico-apiserver` was not present in the list of `CATTLE_SYSTEM_NAMESPACES`
 
### What was fixed, or what changes have occurred

Added `calico-apiserver` to the list of `CATTLE_SYSTEM_NAMESPACES`. This should be automatically added on upgrade, based on the work done for this issue: https://github.com/rancher/rancher/issues/32898
 
### Areas or cases that should be tested

- Create the `calico-apiserver` namespace on a rancher setup before this commit. Verify that it is moved on upgrade.
- Create the `calico-apiserver` namespace on a rancher setup after this commit. Verify that it is present in the list of system namespaces.
 
### What areas could experience regressions?

N/A
 
### Are the repro steps accurate/minimal?

:heavy_check_mark:

**Comment by slickwarren** [comment]
tested on v2.6.7-rc3:
* new and upgraded clusters to 1.23+ do not have any namespaces/workloads in `user only namespaces` -- pass
