### ISSUE TITLE
Project level PSP is not respected while creating deployment.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#37443]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc2
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.22.8+rke2r1
- Cluster Type (Local/Downstream): Downstream, Node Driver, AWS.

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
**Admin**
   
**Describe the bug**

PSP set to the project is not respected while creation of pod.
If you set restricted PSP as default to cluster and create a new namespace with unrestricted PSP, the Pod/Deployment creation in the new project fails with following error.

`Pods "nginx-7fbb89c5fd-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed]:Deployment does not have minimum availability.
`

**To Reproduce**
 

- Create a rancher server v2.6.5-rcX
- Deploy a AWS node driver RKE2 cluster with default PSP set to restricted.
- Create a new Project in cluster with PSP set to unrestricted.
- Create a new namespace in the newly created Project.
- Try to create a deployment with Privileged flag on in the newly created namespace.

The above mentioned scenario is one. There is another scenario where cluster default PSP is set to unrestricted and the Project level PSP is set to restricted. In this scenario the Deployment creation should fail, however, the deployment creation succeeds. 

**Result**

- Deployment creation fails in first scenario.
- Deployment creation succeeds in the second scenario. 

**Expected Result**

- Deployment creation should succeed in first scenario
- Deployment creation should fail in second scenario.

**Comment by MbolotSuse** [comment]
@snasovich - please feel free to correct any of the RKE2 related information below if it is inaccurate.

# Release Note

## Synopsis
RKE2 clusters which are provisioned by rancher are assumed to always have the Pod Security Policy admission controller enabled. If you manually disable this admission controller through kube-api-server args, rancher may still allow you to set Pod Security Policies for projects. However, these Pod Security Policies will have no effect.

## Resolved
No (the original issue that this is attached to was resolved - this release note item is for the side-effect which is not resolved).

Status: Side-effect may be resolved in a future release.
Workaround: Users may experience inaccurate UI information at times.

## Versions
2.6.5 has the side effect.

**Comment by cbron** [comment]
Moved to test.

**Comment by KevinJoiner** [comment]
## Root Cause
When creating a project with a selected PSP on RKE2 provisioned clusters the endpoint for setting PSP for that project returns an error. This is because the rancher server was not properly determining if the cluster has PSP enabled.

## What was fixed, or what change has occurred
To fix this issue when checking if the cluster has PSP enabled, we also check if the cluster is a provisioned RKE2 cluster since PSP should always be enabled for provisioned RKE2 clusters. 

## Areas or cases that should be tested
Test that a project has the ability to set PSP on an RKE2 cluster provisioned by the rancher server.

1. Create an RKE2 with a restricted PSP and verify you can override it for a project.
   - Provision a new cluster using RKE2 
   - Set the default PSP to restricted
   - Create a new project and set the PSP to unrestricted.
   -  Note that the new PSP for the project is set to unrestricted.

2. Create a RKE2 cluster with an unrestricted  PSP and verify you can override it for a project.
   - Provision a new cluster using RKE2.
   - Set the default PSP to unrestricted.
   - Create a new project and set the PSP to restricted.
   - Note that the new PSP of the project is set to restricted.
   
3. Create an RKE2 cluster with default PSP set to 'Default RKE2' verify that the backend endpoint does not respond with an error.
   - Provision a new cluster using RKE2.
   - Set the default PSP to 'Default RKE2'.
   - Create a new project
     - Note that the UI will not give the User an option to set the PSP
   - Manually change the PSP of the project with the endpoint {endpoint link}
   - verify that the request succeeds 
  
5. Create an RKE2 cluster and manually disable the PSP 
 e.g. `--kube-apiserver-arg=enable-admission-plugins=YourListWithoutPodSecurityHere`
 - verify that setting the PSP for a project has no effect.

6.  Import an RKE2 cluster not provisioned via the rancher server and verify that you are unable to change the PSP for newly created projects.

## What areas could experience regressions
The use of PSP on projects specifically on RKE2 clusters that rancher has provisioned or imported

## Are the repro steps accurate/minimal?
Yes
Steps To Reproduce
- Create a rancher server v2.6.5-rcX
- Deploy RKE2 provisioned cluster with default PSP set to restricted.
- Create a new Project in cluster with PSP set to unrestricted.
- Create a new namespace in the newly created Project.
- Try to create a deployment with Privileged flag on in the newly created namespace.

**Comment by samkulkarni20** [comment]
@KevinJoiner can you pls share the endpoint link here?

> Create an RKE2 cluster with default PSP set to 'Default RKE2' verify that the backend endpoint does not respond with an error.
> Provision a new cluster using RKE2.
> Set the default PSP to 'Default RKE2'.
> Create a new project
> Note that the UI will not give the User an option to set the PSP
> Manually change the PSP of the project with the endpoint {endpoint link}

**Comment by KevinJoiner** [comment]
@samkulkarni20 Apologies the endpoint to test would be `<server_url>/v3/projects/<cluster_id>:<project_id>?action=setpodsecuritypolicytemplate`

**Comment by vivek-infracloud** [comment]
**Tested the following cases successfully.**

1. Create an RKE2 with a restricted PSP and verify you can override it for a project. - **PASS**
   - Provisioned a new cluster using RKE2 
   - Set the default PSP to restricted
   - Created a new project and set the PSP to unrestricted.
   -  Note that the new PSP for the project is set to unrestricted.
   -  Pod creation with Privileged Flag is successful in the newly created project.

2. Create a RKE2 cluster with an unrestricted  PSP and verify you can override it for a project. - **PASS**
   - Provisioned a new cluster using RKE2.
   - Set the default PSP to unrestricted.
   - Created a new project and set the PSP to restricted.
   - Note that the new PSP of the project is set to restricted.
   -  Pod creation with Privileged Flag fails in the newly created project.

   
3. Create an RKE2 cluster with default PSP set to 'Default RKE2' verify that the backend endpoint does not respond with an error. - **PASS**
   - Provisioned a new cluster using RKE2.
   - Set the default PSP to 'Default RKE2'.
   - Created a new project
   - Note that the UI will not give the User an option to set the PSP
   - Manually change the PSP of the project with the endpoint {endpoint link}
   - verified that the request succeeds 
  
4.  Import an RKE2 cluster not provisioned via the rancher server and verify that you are unable to change the PSP for newly created projects. - **PASS**

5. Created an RKE2 cluster and manually disable the PSP - **PASS**
e.g. --kube-apiserver-arg=enable-admission-plugins=ListWithoutPodSecurityHere
**verified that setting the PSP for a project has no effect.**

**Comment by vivek-infracloud** [comment]
Based on above validation, the issue is not active anymore, hence closing the issue.
