### ISSUE TITLE
Feature Request: Automatic Cleanup of Disconnected Hosts

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#3745]
Source : https://forums.rancher.com/t/local-ip-for-rancher-agent-with-scale-sets/1836/2 

In scenario's where you use a kind of "autoscale" mechanism, it would be nice if the disconnected hosts (caused due to downscaling) would be cleaned up after a given grace period.

**Comment by tbossert** [comment]
Is there an expected release for this? 

According to my original forum post
https://forums.rancher.com/t/automatically-remove-disconnected-hosts/956/15

The functionality exists but doesn't seem to be supported or documented.   This would be really useful as manually cleaning up dead spot instances is very time consuming

Thanks
- Trevor

**Comment by Dmitry1987** [comment]
Hi  @kvaes , did you find a way to purge disconnected hosts?
i'm about to write my own script and searching through issues to see if anyone already has it. i think it can be a sidecar container that runs on master, and cleans up all disconnected hosts after some time threshold.

**Comment by kvaes** [comment]
Haven't built anything for it. I would expect to check out what's possible with rancher-cli if you needed it.

**Comment by Dmitry1987** [comment]
good idea ... i forgot to check what features rancher-cli has..
thanks :)

**Comment by Dmitry1987** [comment]
well i found it easiest to run a script which cleans all "disconnected" and "inactive" hosts (in my case I want to get rid on any disconnected no matter what, because they're on spotinst always rotating, but others can base their own solution on this):
```
#!/bin/bash

RANCHER_URL=your.rancher.url.com
RANCHER_ACCESS_KEY=<env access key>
RANCHER_SECRET_KEY=<env secret key>

PROJECT_ID=<chosen project id to clean from>

# get all disconnected hosts
curl -s "https://${RANCHER_URL}/v2-beta/projects/${PROJECT_ID}/hosts" \
         | jq '.data[] |  select(.state | contains("disconnected"))'  | jq -r .id > disconnected_list

# deactivate, before they can be deleted
while read ID ; do
curl  -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
-X POST -d '{}'  "https://${RANCHER_URL}/v2-beta/projects/${PROJECT_ID}/hosts/${ID}/?action=deactivate"
done < disconnected_list

# allow some time to transition state
sleep 10

# get all inactive
curl -s "https://${RANCHER_URL}/v2-beta/projects/${PROJECT_ID}/hosts" \
         | jq '.data[] |  select(.state | contains("inactive"))'  | jq -r .id > inactive_list

# delete all inactive hosts
while read ID ; do
curl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
-X DELETE "https://${RANCHER_URL}/v2-beta/projects/${PROJECT_ID}/hosts/${ID}"
done < inactive_list
```

hope it helps someone who searches for solution, to save time writing its own :) 
this can be written in clean maintainable way with javascript or go, but since I'm in POC stage, don't want to waste any more time with this.

**Comment by wmbutler** [comment]
It would be great if this could be added to rancher. Something like:

- [ ] Remove inactive hosts after _____ seconds.

**Comment by vincent99** [comment]
It exists today but is not very safe to use until 1.6 because it lacks a delay on startup to allow hosts to reconnect.  So if you take the server down for longer than the setting, on startup a bunch of hosts will be deleted before they can connect in.  This will be fixed in 1.6 and there's a control in advanced settings for it.

**Comment by wmbutler** [comment]
I wrote this for my use. Others can use it as well if you like:

https://hub.docker.com/r/wmbutler/rancher-purge/

**Comment by ellerbrock** [comment]
You can find this in the Rancher Settings => Advanced Settings => host.remove.delay.seconds

host.remove.delay.seconds=3600 would every hour clean up disconnected hosts.
