### ISSUE TITLE
CoreDNS pod is not getting scheduled after the cluster upgrade

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#37461]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc1
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.19.16-rancher1-4 (1-cp, 1-etcd, 1-w)
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

- The coredns pod fails to schedule after the cluster is upgraded from `v1.19.16-rancher1-4` to `v1.21.11-rancher1-1` with below error:
![image](https://user-images.githubusercontent.com/36376154/165072256-133a37a3-d31e-4a8e-be4a-cf53234533a7.png)

- This was found while validating the [#36985](https://github.com/rancher/rancher/issues/36985).
- On comparing the codedns pod yaml for versions v1.7.0 and 1.8.4, found that there are differences in the podAntiAffinity rules.

**To Reproduce**
 
- Create a rancher v2.6.5-rc1 setup.
- Provision a `v1.19.16-rancher1-4` custom cluster (1-cp, 1-etcd, 1-w).
- Once cluster is active, change CoreDNS forward plugin policy using KB https://www.suse.com/support/kb/doc/?id=000020186.
- Upgrade the cluster to `v1.21.11-rancher1-1`
- CoreDNS pod with image `rancher/mirrored-coredns-coredns:1.8.4` will get stuck into Pending state.

**Result**
- CoreDNS pod will not get scheduled after the cluster upgrade.

**Expected Result**
- New CoreDNS pod should be up and running.

**Additional context**

- [#36985](https://github.com/rancher/rancher/issues/36985)

**Comment by rayandas** [comment]
On another note, I tried provisioning a cluster (1 cp, 1 etcd, 1 worker) using RKE and imported that cluster on Rancher then tried to add coreDNS addon and then update the cluster from 1.19 to 1.21. The new coreDNS pod was getting scheduled successfully and old one was successfully terminated.

**Comment by kinarashah** [comment]
Still looking into the issue, but a couple of observations: 
- Issue is NOT reproducible with RKE `v1.3.10-rc6` 
- Issue is reproducible with Rancher `v2.6.5-rc3` 
- Issue is only reproducible when using the steps in the issue with extra configurations under `addons` section, it works normally without the config map changes 
- Issue is only reproducible going from `v1.19.16-x` to `v1.21.x`, otherwise coredns is the same and doesn't need to be rescheduled 

Need to look into what's the diff between RKE standalone and Rancher, because the issue doesn't reproduce with RKE using the same config and k8s versions.

**Comment by rayandas** [comment]
I validated this on v2.6-head but the issue is still occurring.

**Comment by rayandas** [comment]
Hi @kinarashah I started working on this issue. Is there any pointers you would like to give which I could use to fix this? I know this issue is not occurring while using RKE standalone and only occurring while upgrading the cluster through Rancher dashboard.

**Comment by rayandas** [comment]
The possible problem of this issue:
While creating a cluster using RKE standalone, the coreDNS deployment has the below strategy:
```
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
While creating a cluster using Rancher, the coreDNS deployment has the below strategy:
```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```
This is the reason why after updating to K8s 1.21 from 1.19 the old coredns pod is not getting deleted and the new one is not getting scheduled. Though if we manually delete the old coredns pod then the new one is getting scheduled automatically.

This issue happened for RKE back in 2020. See the [issue](https://github.com/rancher/rke/issues/1944). So someone fixed it. See the [PR](https://github.com/rancher/rke/pull/1947). So it's working for RKE standalone.
As RKE is being vendored in Rancher, I am not sure why Rancher's coreDNS deployment has 25% as maxSurge and maxUnavailable.

**Comment by snasovich** [comment]
@vardhaman22 , thank you for addressing this. With the [RKE PR](https://github.com/rancher/rke/pull/3087) merged, we should be ready to bump RKE version in Rancher as well so the fix can be tested per @kinarashah .
I've also opened [backport PR](https://github.com/rancher/rancher/issues/39729) for you to address in RKE v1.3.x / Rancher v2.6.x. Thank you!

**Comment by snasovich** [comment]
@vardhaman22 , it doesn't look like RKE version is bumped in Rancher yet to include this fix: https://github.com/rancher/rancher/blob/f7692f30cf47d00073cc41b879e0ff90fb0a68b0/go.mod#L119
I don't believe we're ready to move it to test until this is done per https://github.com/rancher/rke/pull/3087#issuecomment-1319008267.

**Comment by vivek-infracloud** [comment]
Validated the issue on rancher v2.7.0

Validation steps
1. Created a rancher server v2.7.0
2. Deploy downstream cluster with k8s version v1.23.14-rancher1-1
4. Change CoreDNS forward plugin policy using below KB https://www.suse.com/support/kb/doc/?id=000020186
5. Verify the modification in configmap - kubectl get cm -n kube-system coredns -o yaml
6. Upgraded the cluster to v1.24.8-rancher1-1
7. Coredns pod doesn't stuck in updating state. pod is up and running state.

**Hence, the issue is not active anymore. Closing the issue.**
