### ISSUE TITLE
Add CIS hardening guide for rancher provisioned k3s clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37493]
We currently need to have an up-to-date hardening guide for the v2.6x line. Our Rancher 2.6 documentation (https://rancher.com/docs/rancher/v2.6/en/cis-scans/) will need updated for k3s clusters.

https://github.com/rancher/rancher/issues/36630

**Comment by macedogm** [comment]
@samjustus from our chat, this is not going to be GA in 2.6.7, so I'm keeping this issue open and changing the milestone.

**Comment by samjustus** [comment]
@macedogm now can we move to test?

**Comment by macedogm** [comment]
@samjustus no, not yet, please. We agreed on chat with QA that I can start working on this next week, because it was only now communicated that this will be GA soon.

**Comment by macedogm** [comment]
CC @anupama2501 @markusewalker @sowmyav27 @samjustus

**Comment by macedogm** [comment]
Added QA test template https://github.com/rancher/rancher-docs/pull/244#issuecomment-1268190422.

**Comment by markusewalker** [comment]
**QA TEST PLAN**
1. Setup Rancher, create a standard user and login as that user.
2. Provision a K3s custom cluster with K8s version 1.24.
3. Validate that the cluster and nodes comes up as `Active` in Cluster Management and Cluster Explorer.
4. Navigate to Cluster Explorer > k3s cluster > Apps.
5. Install the CIS Benchmark chart app into the K3s cluster.
6. Run a CIS scan with profile `k3s-cis-1.23-profile-hardened`.
7. Validate that the scans fail.
8. Navigate to the Rancher client and execute the following as defined in the test template in the associated PR:
     - Kernel parameters
     - PSP file
     - Audit file and log directory
9. Follow the hardened template defined in the associated PR to modify the cluster's configuration.
10. Re-execute a CIS scan with profile `k3s-cis-1.23-profile-hardened`.
11. Validate that the scans now pass.
12. Repeat steps 2-11, but use a K3s custom cluster with K8s version 1.21.
     - Additionally, when running the CIS scan, use `k3s-cis-1.20-profile-hardened` instead.

**Comment by markusewalker** [comment]
Unable to validate this in `v2.7-head` https://github.com/rancher/rancher/commit/426f89a991a2f1241d2ae9c14e6bdc06402effc6.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/426f89a991a2f1241d2ae9c14e6bdc06402effc6
- Browser: Chrome

**TEST RESULT - FAIL**

REPRODUCTION STEPS
1. Setup Rancher, created a standard user and logged in as that user.
2. Provisioned a K3s custom cluster with K8s version 1.24.
     - 1 etcd, 1 cp, 1 worker
3. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Navigated to Cluster Explorer > k3s cluster > Apps.
5. Installed the CIS Benchmark chart app into the K3s cluster.
     - Validated the operation was successful and `rancher-cis-benchmark` and `rancher-cis-benchmark-crd` are in a sate of `Deployed`.
6. Still in Cluster Explorer, navigated to CIS Benchmark > Create.
7. Ran a CIS scan with profile `k3s-cis-1.23-profile-hardened`.
8. Validated that the scan fails as expected:
![image](https://user-images.githubusercontent.com/52591819/194127019-8e8866b9-fa1a-4e8c-a3d7-32c41559a9ec.png) 
9. Navigated to the Rancher client machine and included the following in the instance as defined in the issue's associated PR:
     - Kernel parameters
     - PSP file
     - Audit file and log directory
10. Navigated to Cluster Management and edited the cluster configuration to include the hardened template as defined in the issue's associated PR.
11. Upon performing this, I consistently am producing the following:
![image](https://user-images.githubusercontent.com/52591819/194127062-740b5e7c-944a-4f52-8fc5-a442539895f2.png) 
12. Repeated steps 2-11, but used a K3s custom cluster with K8s 1.21 and with profile `k3s-cis-1.20-profile-hardened` instead; results were all the same as mentioned above.
     - Here is the original failed scan prior to the cluster modifications:
![image](https://user-images.githubusercontent.com/52591819/194127117-29524fba-20e3-4530-ae9d-714662ac9945.png)

**Comment by macedogm** [comment]
@markusewalker thanks for checking this. I'll review the setup.

**Comment by markusewalker** [comment]
Re-tested this on `v2.7-head` https://github.com/rancher/rancher/commit/4092002b7b921d2862b75d0111f2805200832ee0.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/4092002b7b921d2862b75d0111f2805200832ee0
- Browser: Chrome

**TEST RESULT
Scenario 1: Fresh install, K8s version 1.24 :white_check_mark:
Scenario 2: Fresh install, K8s version 1.21 :white_check_mark:
Scenario 3: Upgrade K8s version 1.21 to 1.24 :white_check_mark:
Scenario 4: Upgrade Rancher from `v2.6.8` to `v2.7-head` :white_check_mark:**

**VALIDATION STEPS**

**Scenario 1: Fresh install, K8s version 1.24**
1. Setup Rancher, created a standard user and logged in as that user.
2. Provisioned a K3s custom cluster with K8s version 1.24.
     - 1 etcd, 1 cp, 1 worker
3. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Navigated to Cluster Explorer > k3s cluster > Apps.
5. Installed the CIS Benchmark chart app into the K3s cluster.
     - Validated the operation was successful and `rancher-cis-benchmark` and `rancher-cis-benchmark-crd` are in a sate of `Deployed`.
6. Still in Cluster Explorer, navigated to CIS Benchmark > Create.
7. Ran a CIS scan with profile `k3s-cis-1.23-profile-hardened`.
8. Validated that the scan fails as expected:
![image](https://user-images.githubusercontent.com/52591819/194381901-20681cea-b284-48af-a5c7-1ed09bb0fc95.png) 
9. Navigated to the Rancher client machine and included the following in the instance as defined in the issue's associated PR:
     - Kernel parameters
     - PSP file
     - Audit file and log directory
10. Navigated to Cluster Management and edited the cluster configuration to include the hardened template as defined in the issue's associated PR.
     - Validated that the cluster remains as `Active` upon hardening the cluster.
11. Navigated back to Cluster Explorer > CIS Benchmark > Create.
12. The new scan shows 3 failures instead of 12:
![image](https://user-images.githubusercontent.com/52591819/194381790-b054c5e7-33fe-4b20-b4a3-087fec5e96e0.png) 
     - Validated that this is an issue with the CIS scan itself as opposed to the hardening guide, that will be logged in a separate issue.
____________
**Scenario 2: Fresh install, K8s version 1.21**
1. Repeated scenario 1, but used profile `k3s-cis-1.20-profile-hardened` for the CIS scan.
2. Here is the result prior to hardening the cluster:
![image](https://user-images.githubusercontent.com/52591819/194381737-db7005da-597b-4d93-ac00-bdec66563553.png) 
3. Here is the result after hardening the cluster:
![image](https://user-images.githubusercontent.com/52591819/194381713-cfb0d469-684f-4efd-9a3d-72f6d7d5e01a.png)
___________
**Scenario 3: Upgrade K8s version to 1.21 to 1.24**
1. Repeated scenario 2.
2. Here is the result prior to hardening the cluster:
![image](https://user-images.githubusercontent.com/52591819/194381681-06cc759c-84df-4a93-b12a-18c30e6f5788.png) 
3. Here is the result after hardening the cluster:
![image](https://user-images.githubusercontent.com/52591819/194381650-6aa3963d-5c5d-48e6-8aa2-f3d55bc1f41a.png) 
4. Navigated back to Cluster Management and edited the cluster to update the K8s version to 1.24.
5. Validated the version is updated in Cluster Management and Cluster Explorer.
     - The nodes and cluster remained as `Active` as well.
6. Ran a new CIS scan, but this time using profile `k3s-cis-1.23-profile-hardened`:
![image](https://user-images.githubusercontent.com/52591819/194381592-e7dca9c7-a572-4625-a057-62d0e972ba6a.png) 
_____________
**Scenario 4: Upgrade Rancher from `v2.6.8` to `v2.7-head`**
1. Repeated scenario 2.
2. Here is the result prior to hardening the cluster:
![image](https://user-images.githubusercontent.com/52591819/194381531-f333d736-af83-407a-8e9f-b68ff2302260.png) 
3. Here is the result after hardening the cluster:
![image](https://user-images.githubusercontent.com/52591819/194381499-daf44d39-dc43-4585-930e-ab1fa3c19824.png) 
4. Upgraded Rancher server to `v2.7-head`; validated that this was successful and that the cluster did not auto-upgrade.
5. Edited the cluster's configuration to upgrade the K8s version to 1.24.
6. Validated that the upgrade was successful and that the cluster and nodes appear as `Active` in Cluster Management and Cluster Explorer.
7. Edited the cluster's configuration and validated that the modifications made were preserved.
8. Ran a new CIS scan, but this time using profile `k3s-cis-1.23-profile-hardened`:
![image](https://user-images.githubusercontent.com/52591819/194381460-a3f88444-9052-4569-85a3-0695f1236c81.png)

**Comment by sowmyav27** [comment]
Scan has passed now - https://github.com/rancher/cis-operator/issues/169#issuecomment-1280760214
