### ISSUE TITLE
Add 1.22 for EKS v1 clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#37534]
**Detailed Description**

- Add 1.22 for EKS v1 clusters

**Comment by Josh-Diamond** [comment]
Dashboard related issue: `https://github.com/rancher/dashboard/issues/5716`

**Comment by thedadams** [comment]
A script that can be used to get the default AMIs with the `aws` CLI.
```
#!/bin/bash

_aws_regions="us-east-2 us-east-1 us-west-2 us-west-1 af-south-1 ap-east-1 ap-south-1 ap-northeast-1 ap-northeast-2 ap-northeast-3 ap-southeast-1 ap-southeast-2 ca-central-1 cn-north-1 cn-northwest-1 eu-central-1 eu-west-1 eu-west-2 eu-south-1 eu-west-3 eu-north-1 me-south-1 sa-east-1"

_ami_list=ami.txt

> $_ami_list

for _version in $@
  do
    echo "\"$_version\": {" >> $_ami_list
    for _region in $_aws_regions
      do 
        _eks_ami=`aws ssm get-parameter --no-cli-pager --name /aws/service/eks/optimized-ami/$_version/amazon-linux-2/recommended/image_id --region $_region --query "Parameter.Value" --output text`
        echo "        \"$_region\": \"$_eks_ami\"," >> $_ami_list
        sleep 1
      done
    echo "}," >> $_ami_list
  done
```

**Comment by snasovich** [comment]
AMIs from the script need to be updated in https://github.com/rancher/rancher/blob/release/v2.6/pkg/kontainer-engine/drivers/eks/eks_driver.go (not just for 1.22, but for previous versions - if there is a newer version of EKS-optimized AMI).

**Comment by snasovich** [comment]
### Root cause
EKS-optimized AMIs are not present in EKS v1 configuration for k8s 1.22. Also, AMIs are outdated for other versions 1.18-1.21 (though this is not critical).
  
### What was fixed, or what changes have occurred
AMIs were updated by querying AWS with the script posted above.
  
### Areas or cases that should be tested
Creation of EKS v1 clusters of k8s 1.22 (primarily) as well as previous versions.
  
### What areas could experience regressions?
Potentially provisioning of any EKS v1 cluster based on region / k8s version combination, but chances of this are low since values were retrieved by script directly from AWS CLI.
  
### Are the repro steps accurate/minimal?
No repro steps are specified on the issue, however UI to provision EKS v1 cluster can be invoked by navigating to `/g/clusters/add/launch/amazoneks` URL.

**Comment by Josh-Diamond** [comment]
Ticket #37534 - Test Results

Verified on rancher `v2.6-98da58b9c8fe544ed3068ad9fa8176ccdb947862-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream EKS cluster with k8s version `v1.22`
3. Provision a downstream EKS cluster with k8s version `v1.21`
4. Provision a downstream EKS cluster with k8s version `v1.20`
5. Provision a downstream EKS cluster with k8s version `v1.19`
6. Verified - All EKS clusters successfully provision;
7. Deploy a workload on EKS cluster with k8s version `v1.22`
8. Deploy a workload on EKS cluster with k8s version `v1.21`
9. Deploy a workload on EKS cluster with k8s version `v1.20`
10. Deploy a workload on EKS cluster with k8s version `v1.19`
11. Verified - All EKS clusters successfully deploy workload
12. Delete EKS cluster with k8s `v1.22`
13. Delete EKS cluster with k8s `v1.21`
14. Delete EKS cluster with k8s `v1.20`
15. Delete EKS cluster with k8s `v1.19`
16. Verified - All EKS clusters successfully deleted

Screenshot:
<img width="1626" alt="Screen Shot 2022-05-03 at 9 38 47 AM" src="https://user-images.githubusercontent.com/46494969/166499532-85b0b178-8ac3-47d3-8f1c-9d07b25f80b3.png">
