### ISSUE TITLE
rke2/k3s encryption key rotation integration tests

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#37549]
Create integration tests for rke2/k3s encryption key rotation which tests the following cases:

- Single controlplane node clusters
- HA clusters
- Single controlplane node clusters where the controlplane node is not the init node (i.e. no nodes with both controlplane and etcd role)
- HA clusters where no controlplane node is the init node (i.e. no nodes with both controlplane and etcd role)
- Clusters "at rest" versus clusters actively creating and manipulating secrets
- Different version of rke2/k3s (unsupported versions should fail)
- Clusters that are not in `start` or `reencrypt_finished` when encryption key rotation is requested should fail

**Comment by jakefhyde** [comment]
Blocked until https://github.com/rancher/rancher/pull/38281 is merged

**Comment by jakefhyde** [comment]
Blocked by https://github.com/rancher/rancher/issues/38283

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster (3 etcd, 2 cp, 3 workers), attach a created secret to a workload, take etcd snapshot, rotate encryption keys|
|2|As a standard user, provision a downstream K3S node driver cluster (2 etcd+cp, 3 workers), attach a created secret to a workload, take etcd snapshot, rotate encryption keys|
|3|As a standard user, provision a downstream RKE2 node driver cluster (1 node, all roles), attach a created secret to a workload, take etcd snapshot, rotate encryption keys|
|4|As a standard user, provision a downstream RKE2 custom cluster (3 etcd, 2 cp, 2 Linux workers+1 Windows worker), attach a created secret to a workload, take etcd snapshot, rotate encryption keys|
|5|As a standard user, provision a downstream K3S node driver cluster (1 etcd, 1 cp, 1 worker), create 10,000 secrets, take etcd snapshot, rotate encryption keys|
|6|Setup Rancher v2.6.13, provision a downstream RKE2 node driver cluster (1 etcd, 1 cp, 1 worker), attach 10 created secrets to 10 unique workloads, upgrade Rancher to v2.7-head, take etcd snapshot, rotate encryption keys

**Comment by markusewalker** [comment]
Validated this against `v2.7-head` https://github.com/rancher/rancher/commit/2e50d9f2f8725dccb40f28c8be2d8c2bb99fa59a. See details below:

ENVIRONMENT DETAILS
	- Rancher install: Docker
	- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/2e50d9f2f8725dccb40f28c8be2d8c2bb99fa59a

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster (3 etcd, 2 cp, 3 workers),  create secret, take etcd snapshot, rotate encryption keys|:white_check_mark:|
|2|As a standard user, provision a downstream K3S node driver cluster (2 etcd+cp, 3 workers), create secret, take etcd snapshot, rotate encryption keys|:white_check_mark:|
|3|As a standard user, provision a downstream RKE2 custom driver cluster (1 node, all roles), create secret, take etcd snapshot, rotate encryption keys|:white_check_mark:|
|4|As a standard user, provision a downstream RKE2 custom cluster (3 etcd, 2 cp, 2 Linux workers+1 Windows worker), create secret, take etcd snapshot, rotate encryption keys|:white_check_mark:|
|5|As a standard user, provision a downstream RKE2 node driver cluster (1 etcd, 1 cp, 1 worker), create 10,000 secrets, take etcd snapshot, rotate encryption keys|:white_check_mark:|
|6|As a standard user, provision a downstream K3S node driver cluster (1 etcd, 1 cp, 1 worker), create secret, take etcd snapshot,, upgrade K8s version, rotate encryption keys|:white_check_mark:|
|7|Setup Rancher v2.6.13, provision a downstream RKE2 node driver cluster (1 etcd, 1 cp, 1 worker), create 10 secrets, upgrade Rancher to v2.7-head, take etcd snapshot, rotate encryption keys|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 node driver `v1.26.7+rke2r1` cluster (3 etcd, 2 cp, 3 workers).
2. Created a secret in the `default` namespace; took note of the resourceVersion.
3. Took an etcd snapshot.
4. Rotated the encryption keys; validated that this was successful.
5. Viewed the secret in the cluster and validated that the resourceVersion was updated.
6. Rotated encryption keys again; validated again that this was successful.

________

**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream RKE2 node driver `v1.26.7+rke2r1` cluster (2 etcd+cp, 3 workers).

_______

**Scenario 3**
1. Repeated scenario 1, but provisioned a downstream RKE2 custom driver `v1.25.12+rke2r1` cluster (1 etcd+cp+worker).
2. In the etcd node, installed `etcdctl` and ran the following command:
```
sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt get /registry/secrets/default/<secret name>| hexdump -C
```
3. Repeated the above command before and after the keys were encrypted; validated that they keys were rotated as the timestamp is different, along with the actual hexcode being different.

________

**Scenario 4**
1. Repeated scenario 1, but provisioned a downstream RKE2 custom cluster `v1.24.16+rke2r1` cluster (3 etcd, 2 cp, 2 Linux workers, 1 Windows worker).
2. In the etcd node, installed `etcdctl` and ran the following command:
```
sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt get /registry/secrets/default/<secret name>| hexdump -C
```
3. Repeated the above command before and after the keys were encrypted; validated that they keys were rotated as the timestamp is different, along with the actual hexcode being different.

_____

**Scenario 5**
1. Repeated scenario 1, but provisioned a downstream RKE2 node driver `v1.25.12+rke2r1` cluster (1 etcd, 1 cp, 1 worker) and created 10,000 secrets instead of 1.
     - Each secret was put in it's own respective, unique. Namespace.
2. This cluster is in state `Waiting for encryption key rotation stage to be finished` for ~35 minutes. After discussing with Jake, he mentioned he has seen transient issues like this before and should be non issue. Therefore, marking as successful.

______

**Scenario 6**
1. As a standard user, provisioned a downstream RKE2 node driver `v1.24.16+rke2r1` cluster (1 etcd, 1 cp, 1 worker).
2. Created a secret in the `default` namespace; took note of the resourceVersion.
3. Took an etcd snapshot.
4. Upgraded cluster version to `v1.26.7+rke2r1`; validated the cluster and nodes were upgraded successfully.
5. Rotated encyrption keys; validated this was successful.
6. Viewed the secret in the cluster and validated that the resourceVersion was updated.
7. Rotated encryption keys again; validated again that this was successful.

______

**Scenario 7**
1. Setup Rancher `v2.6.13` and logged in as a standard user.
2. Provisioned a downstream RKE2 node driver `v1.24.16+rke2r1` cluster (1 etcd, 1 cp, 1 worker).
3. Created ten secrets in unique namespaces.
4. Upgraded Rancher to `v2.7-head`; validated that the cluster did not auto-upgrade.
5. Took an etcd snapshot.
6. Upgraded cluster version to `v1.26.7+rke2r1`; validated that the cluster and nodes were upgraded successfully.
7. Rotated encryption keys twice; validated this was successful both times.
