### ISSUE TITLE
Unable to create Ingress on RKE2 clusters

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#37561]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc6
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: v1.23.6+rke2r1
- Cluster Type (Local/Downstream): Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin/Standard User
   
**Describe the bug**
Ingress creation fails on RKE2 cluster

**To Reproduce**
 

- Create a rancher server v2.6.5-rc6.
- Provision a RKE2 downstream cluster.
- Try to create a simple, raw ingress.

**Result**
Ingress creation fails with following error.

`Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.43.58.190:443: i/o timeout`

**Expected Result**
Ingress gets created successfully.

**Comment by thedadams** [comment]
### Root cause
The problem was that port 8443 needs to be open for the `rke2-ingress-nginx-controller` webhook.

### What was fixed, or what changes have occurred
`rancher-machine` will now open the port when provisioning nodes.

### Areas or cases that should be tested
1. Provision an RKE2 cluster in EC2 with 3 etcd-only, 2 cp, and 2 worker nodes
2. After the cluster is active, create an ingress from the Rancher UI in the downstream cluster.

### What areas could experience regressions?
None

### Are the repro steps accurate/minimal?
Yes.

**Comment by vivek-infracloud** [comment]
**Validated the above test on rancher v2.6-head.**

Validation steps followed

1. Created a rancher server v2.6-head
2. Provisioned a RKE2 cluster.
3. Successfully created an ingress.
4. Ran test_ingress checks with v3_needs_cluster job on RKE2 cluster.

**Ingress creation and tests were successful.**

**Comment by vivek-infracloud** [comment]
Based on comment above, the ingress creation issue is not active on RKE2 cluster. Hence, closing the issue.
