### ISSUE TITLE
[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [10.10.34.20] failed to report healthy. Check etcd container logs on each host for more information

### ISSUE THREAD

**Issue by LuksJobs** [rancher/rancher#37591]
I’ve been attempting to run Rancher in a single-node Docker deployment. Everything seems fine until creating the first cluster, at that point, the UI remains in the “provisioning” state with the following error: [etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [10.10.34.20] failed to report healthy…".

FULL LOG: 

5:33:22 pm | [INFO ] Initiating Kubernetes cluster
-- | --
5:33:22 pm | [INFO ] Successfully Deployed state file at [management-state/rke/rke-1475743140/cluster.rkestate]
5:33:22 pm | [INFO ] Building Kubernetes cluster
5:33:22 pm | [INFO ] [dialer] Setup tunnel for host [10.10.34.20]
5:33:22 pm | [INFO ] [network] Deploying port listener containers
5:33:25 pm | [INFO ] [network] Port listener containers deployed successfully
5:33:25 pm | [INFO ] [network] Running control plane -> etcd port checks
5:33:26 pm | [INFO ] [network] Successfully started [rke-port-checker] container on host [10.10.34.20]
5:33:26 pm | [INFO ] [network] Running control plane -> worker port checks
5:33:28 pm | [INFO ] [network] Successfully started [rke-port-checker] container on host [10.10.34.20]
5:33:28 pm | [INFO ] [network] Running workers -> control plane port checks
5:33:29 pm | [INFO ] [network] Successfully started [rke-port-checker] container on host [10.10.34.20]
5:33:29 pm | [INFO ] [network] Skipping kubeapi port check
5:33:29 pm | [INFO ] [network] Removing port listener containers
5:33:29 pm | [INFO ] [remove/rke-etcd-port-listener] Successfully removed container on host [10.10.34.20]
5:33:29 pm | [INFO ] [remove/rke-cp-port-listener] Successfully removed container on host [10.10.34.20]
5:33:29 pm | [INFO ] [remove/rke-worker-port-listener] Successfully removed container on host [10.10.34.20]
5:33:29 pm | [INFO ] [network] Port listener containers removed successfully
5:33:29 pm | [INFO ] [certificates] Deploying kubernetes certificates to Cluster nodes
5:33:36 pm | [INFO ] [reconcile] Rebuilding and updating local kube config
5:33:36 pm | [INFO ] Successfully Deployed local admin kubeconfig at [management-state/rke/rke-1475743140/kube_config_cluster.yml]
5:33:36 pm | [ERROR] [reconcile] host [10.10.34.20] is a control plane node without reachable Kubernetes API endpoint in the cluster
5:33:36 pm | [ERROR] [reconcile] no control plane node with reachable Kubernetes API endpoint in the cluster found
5:33:36 pm | [INFO ] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
5:33:36 pm | [INFO ] [file-deploy] Deploying file [/etc/kubernetes/audit-policy.yaml] to node [10.10.34.20]
5:33:37 pm | [INFO ] Successfully started [file-deployer] container on host [10.10.34.20]
5:33:37 pm | [INFO ] Waiting for [file-deployer] container to exit on host [10.10.34.20]
5:33:37 pm | [INFO ] Waiting for [file-deployer] container to exit on host [10.10.34.20]
5:33:37 pm | [INFO ] Container [file-deployer] is still running on host [10.10.34.20]: stderr: [], stdout: []
5:33:38 pm | [INFO ] Waiting for [file-deployer] container to exit on host [10.10.34.20]
5:33:38 pm | [INFO ] [remove/file-deployer] Successfully removed container on host [10.10.34.20]
5:33:38 pm | [INFO ] [/etc/kubernetes/audit-policy.yaml] Successfully deployed audit policy file to Cluster control nodes
5:33:38 pm | [INFO ] [reconcile] Reconciling cluster state
5:33:38 pm | [INFO ] [reconcile] This is newly generated cluster
5:33:38 pm | [INFO ] Pre-pulling kubernetes images
5:33:38 pm | [INFO ] Kubernetes images pulled successfully
5:33:38 pm | [INFO ] [etcd] Building up etcd plane..
5:33:39 pm | [INFO ] Successfully started [etcd-fix-perm] container on host [10.10.34.20]
5:33:39 pm | [INFO ] Waiting for [etcd-fix-perm] container to exit on host [10.10.34.20]
5:33:39 pm | [INFO ] Waiting for [etcd-fix-perm] container to exit on host [10.10.34.20]
5:33:39 pm | [INFO ] Container [etcd-fix-perm] is still running on host [10.10.34.20]: stderr: [], stdout: []
5:33:40 pm | [INFO ] Waiting for [etcd-fix-perm] container to exit on host [10.10.34.20]
5:33:40 pm | [INFO ] [remove/etcd-fix-perm] Successfully removed container on host [10.10.34.20]
5:33:42 pm | [INFO ] [etcd] Successfully started [rke-log-linker] container on host [10.10.34.20]
5:33:42 pm | [INFO ] [remove/rke-log-linker] Successfully removed container on host [10.10.34.20]
5:33:42 pm | [INFO ] [etcd] Successfully started etcd plane.. Checking etcd cluster health

**Comment by fabiobsantos92** [comment]
I have the same problem.
Rancher Server v2.4.15 docker 
Docker version 20.10.14, build a224086
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
![Screenshot from 2022-05-05 17-24-59](https://user-images.githubusercontent.com/17848542/166969127-eb201dd9-ceef-4a7e-8b26-3326445f2662.png)
2022-05-05 16:21:23.456000 I | embed: rejected connection from "192.168.100.62:47648" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")", ServerName "")

**Comment by fabiobsantos92** [comment]
@superseb any answer?

**Comment by superseb** [comment]
This node is not properly being reported in the UI so there must be something going on on that node. What does `docker ps` output? Was it restarted or did something else happen? What is the state of the `/etc/kubernetes` directory where a part of the state gets stored on this node? How does it compare to the other nodes? How many nodes in total are there in this cluster with what roles? What happened before this started to happen (restart/add node/change cluster config/upgrade cluster)?

And v2.4.15 is over a year old and no longer supported, to keep receiving latest security upgrades and bug fixes, please upgrade.

**Comment by fabiobsantos92** [comment]
Hi,

Let's answer your questions:

1. What does docker ps output?
rancher/rancher-agent:v2.4.15
rancher/coreos-etcd:v3.4.15-rancher1
2. Was it restarted or did something else happen? No, I also tried to nuke_rancher_kube_node.sh and create the new cluster and the output was the same.
3. What is the state of the /etc/kubernetes directory where a part of the state gets stored on this node?
-rw------- audit-policy.yaml
-rw-------  kube-api-authn-webhook.yaml
drwxr-xr-x ssl
On the ssl folder:
kube-apiserver-key.pem                    kubecfg-kube-apiserver-requestheader-ca.yaml  kube-node-key.pem
kube-apiserver.pem                        kubecfg-kube-controller-manager.yaml          kube-node.pem
kube-apiserver-proxy-client-key.pem       kubecfg-kube-node.yaml                        kube-proxy-key.pem
kube-apiserver-proxy-client.pem           kubecfg-kube-proxy.yaml                       kube-proxy.pem
kube-apiserver-requestheader-ca-key.pem   kubecfg-kube-scheduler.yaml                   kube-scheduler-key.pem
kube-apiserver-requestheader-ca.pem       kube-controller-manager-key.pem               kube-scheduler.pem
kube-ca-key.pem                           kube-controller-manager.pem                   kube-service-account-token-key.pem
kube-ca.pem                               kube-etcd-192-168-100-62-key.pem              kube-service-account-token.pem
kubecfg-kube-apiserver-proxy-client.yaml  kube-etcd-192-168-100-62.pem
4. How many nodes in total are there in this cluster with what roles? One node with the 3 roles
5. What happened before this started to happen (restart/add node/change cluster config/upgrade cluster)? This is the new cluster.

I know its and old version of rancher but it works other cluster with the same conditions and must work on the new node/cluster.
At the end i see this error on rancher/coreos-etcd:v3.4.15-rancher:

2022-05-17 14:39:06.692619 I | embed: rejected connection from "192.168.100.62:46816" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")", ServerName "")

**Comment by heavenkiller2018** [comment]
I have the same problem as you, what's the wrong with it and how to fix it?

**Comment by obyerere** [comment]
Any fix ??

**Comment by LuksJobs** [comment]
> Any fix ??

First of all, you need to make sure the machine is re-used or not (install Rancher before ?). All related information is in the https://github.com/rancher/rancher/issues/24189#issuecomment-759288688. Removing old data in some directories may fix the issue.

In my case, I clean all the old data for Rancher and re-install it but still get the same issue. Here is what I did. I disabled the swap and firewall, and the cluster works just fine. However, I think that the log of etcd is not quite friendly to check the root cause.

```
systemctl stop firewalld && systemctl disable firewalld
swapoff -a
```

**Comment by claudioivp** [comment]
Increasing the hardware from 2vcpu to 4vcpu and 6gb ram, these problem has been resolved here. Maybe help you.
