### ISSUE TITLE
CIS Benchmark 1.0.700 Missing from helm repo

### ISSUE THREAD

**Issue by Sheldons92** [rancher/rancher#37601]
**Rancher Server Setup**
- Rancher version: 2.5.13
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 1.18.20

   
**Describe the bug**

Rancher 2.5.13 ships with the default version of CIS Benchmarks 1.0.700, this version of the chart has not been published to charts.rancher.io 

When using Terraforms Helm provider to install CIS Benchmarking to a cluster it requires an official helm repository hosting the correct version.

**To Reproduce**
 

helm search repo rancher/rancher-cis-benchmark --versions

**Result**

CIS Benchmark and CRD versions of 1.0.600 and older.

**Expected Result**

CIS Benchmark and CRD versions of 1.0.700 showing.

**Screenshots**

**Additional context**

The correct version is visible in git.rancher.io/charts however as the official Helm provider for terraform requires the use of an official Helm repository and not a git based repo, git.rancher.io/charts is not suitable.

**Comment by samkulkarni20** [comment]
@MKlimuszka @SheilaghM can you pls assign the appropriate milestone to this issue?

**Comment by SheilaghM** [comment]
This was seen in 2.5.x, but isn't tied to any specific release. Based on workloads and timelines, I'd say let's get this ready for 2.6.6.  If we update the CIS chart it should fix the problem across all versions.

**Comment by brandonsuse** [comment]
@nickwsuse please work this back-end ticket when you can. Thanks!

**Comment by samkulkarni20** [comment]
The PR to port forward v2.5 charts into dev-v2.6 is merged. Although the actual issue testing can happen after the 2.6 charts are released.
The customer wants to access the CIS Benchmark chart version 1.0.700 using helm repo https://charts.rancher.io/. Since this is based off of `release-v2.6` branch, we can test the fix after the 2.6 charts are released.

**Comment by nickwsuse** [comment]
@samkulkarni20 So this issue isn't testable until after the release of the 2.6 charts then? I ask because when I do the helm search I don't see the chart version 1.0.700, but I do see that version in the UI when on v2.6-head
![image](https://user-images.githubusercontent.com/107147272/179615003-98e8323a-47bc-4f9b-a6d1-2936ef870b41.png)

**Comment by samkulkarni20** [comment]
@nickwsuse Yes. What you see is expected, till 2.6.7 is out.

**Comment by Sheldons92** [comment]
Apologies, but this makes no sense. It's not unusual for someone to be running the helm installs via the Helm CLI or Terraform provider as opposed to Ranchers API/GUI, why would someone running 2.5.13 need to wait until the release of 2.6.7 to use a chart that's shipped with 2.5.13? Surely 1.0.700 in this case shouldn't have been included in 2.5.13 at all to avoid this confusion.

**Comment by bmdepesa** [comment]
Moving this to 2.6.8 for QA, as we can't test until the charts are actually published. Once tested, we will close and change the milestone back to 2.6.7 to signify where it was actually fixed.

**Comment by vivek-infracloud** [comment]
Validated if the CIS Benchmark and CRD version is 1.0.700.

Correct version is visible in rancher charts. Hence, closing the issue.
