### ISSUE TITLE
EKS operator's logs flooded with error message when cluster is in error state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37650]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `628b1b9`
- Installation option (Docker install/Helm Chart): HA install - RKE1 local cluster

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): EKS v2 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

   
**Describe the bug**
EKS operator's logs flooded with error message when cluster is in error state

**To Reproduce**

- Deploy an EKS v2 cluster
- In the node group section, specific an AMI.
- The cluster is deployed, but fails to come up Active in Rancher

**Result**
- Error on Rancher UI : `Waiting for API to be available:ResourceInUseException: Nodegroup cannot be updated as it is currently not in Active State { RespMetadata: { StatusCode: 409, RequestID: "x-x-x-x" }, ClusterName: "israeleksubuntucluster", Message_: "Nodegroup cannot be updated as it is currently not in Active State", NodegroupName: "israelubuntunodegroup" }`
- EKS operator logs are spammed every second with logs:
```
time="2022-05-09T20:59:37Z" level=error msg="error syncing 'cattle-global-data/c-sgdtw': handler eks-controller: ResourceInUseException: Nodegroup cannot be updated as it is currently not in Active State\n{\n RespMetadata: {\n StatusCode: 409,\n RequestID: \"0bad6cf5-9ed5-471f-97af-47a44fe08257\"\n },\n ClusterName: \"israeleksubuntucluster\",\n Message_: \"Nodegroup cannot be updated as it is currently not in Active State\",\n NodegroupName: \"israelubuntunodegroup\"\n}, requeuing"
Mon, May 9 2022 1:59:38 pm | time="2022-05-09T20:59:38Z" level=error msg="error syncing 'cattle-global-data/c-sgdtw': handler eks-controller: ResourceInUseException: Nodegroup cannot be updated as it is currently not in Active State\n{\n RespMetadata: {\n StatusCode: 409,\n RequestID: \"f38d5f2f-111a-4687-942e-86d125390beb\"\n },\n ClusterName: \"israeleksubuntucluster\",\n Message_: \"Nodegroup cannot be updated as it is currently not in Active State\",\n NodegroupName: \"israelubuntunodegroup\"\n}, requeuing"
Mon, May 9 2022 1:59:38 pm | time="2022-05-09T20:59:38Z" level=error msg="error syncing 'cattle-global-data/c-sgdtw': handler eks-controller: ResourceInUseException: Nodegroup cannot be updated as it is currently not in Active State\n{\n RespMetadata: {\n StatusCode: 409,\n RequestID: \"93989b6f-40a5-4133-aefb-75c14dda479f\"\n },\n ClusterName: \"israeleksubuntucluster\",\n Message_: \"Nodegroup cannot be updated as it is currently not in Active State\",\n NodegroupName: \"israelubuntunodegroup\"\n}, requeuing"
Mon, May 9 2022 1:59:39 pm | time="2022-05-09T20:59:39Z" level=error msg="error syncing 'cattle-global-data/c-sgdtw': handler eks-controller: ResourceInUseException: Nodegroup cannot be updated as it is currently not in Active State\n{\n RespMetadata: {\n StatusCode: 409,\n RequestID: \"f87d89c3-0ad6-4fd8-9c81-cffd269f3076\"\n },\n ClusterName: \"israeleksubuntucluster\",\n Message_: \"Nodegroup cannot be updated as it is currently not in Active State\",\n NodegroupName: \"israelubuntunodegroup\"\n}, requeuing"
Mon, May 9 2022 1:59:40 pm
```

**Expected Result**
EKS operator should not retry every second. There should be a backoff interval

**Comment by jakefhyde** [comment]
EKS operator utilizes wrangler, which has a default backoff builtin. If this backoff is not being utilized, then there may be something causing the object to get updated, which skirts the backoff.

**Comment by annablender** [comment]
Both @sowmyav27 and I reproduced this on rancher 2.6.5.

When provisioning an EKS cluster via the rancher UI using a custom ubuntu AMI ID and a node volume size of < 30GB, this err appears because rancher expects a node disk size of >= 30GB for snapshots.

![image](https://user-images.githubusercontent.com/12955547/171693027-4fbd3f34-7d3b-4277-9b42-2d84eb716edc.png)

I updated the disk size to 30GB. Then the expected err appeared.

![image](https://user-images.githubusercontent.com/12955547/171693314-d608e565-ffbe-4e2b-b220-50ea648ebbcd.png)

EKS operator logs were spammed with that error.

![image](https://user-images.githubusercontent.com/12955547/171693573-087f5a9d-e698-492b-8c95-06ba532f748c.png)

**Comment by annablender** [comment]
So wrangler has a [controller timeout](https://github.com/rancher/wrangler/blob/8eeded9bae2a1641b16de66da962fe88991e67b8/pkg/clients/clients.go#L186) of 15 mins but since the `eks-config-handler` in the `eks-operator` is spamming the logs every second, that backoff interval is definitely not being used. When the operator spams the logs with that err, [this line](https://github.com/rancher/eks-operator/blob/1b8dfe2ea04eee43fd362c6da0e1cef2a09cb600/controller/eks-cluster-config-handler.go#L118) is hit, and via the comments.. what I think is happening is: the EKS operator assumes that a failure to update a node group is a currently pending update, so it logs the error message, then immediately sends the object back into the controller where the controller waits for the update 'to finish'.

**Comment by annablender** [comment]
Turns out, the behavior seen in this case results from the fact that the error message that is returned from EKS has metadata with a unique `requestID` in the body. Since the error message is different every time, the Status continues to get updated every second. Will modify PR.

**Comment by annablender** [comment]
## Testing template

#### Root cause

When a call to `UpdateNodeGroupVersion` fails due to a custom AMI version causing node provisioning to fail in EKS, the failure is expected but lasso spams the EKS logs every second. This happens because the error message that is returned from EKS has metadata with a unique `requestID` in the body. Since the error message is different every time, [this code](https://github.com/rancher/eks-operator/blob/1b8dfe2ea04eee43fd362c6da0e1cef2a09cb600/controller/eks-cluster-config-handler.go#L122) is skipped and the [Status gets updated](https://github.com/rancher/eks-operator/blob/1b8dfe2ea04eee43fd362c6da0e1cef2a09cb600/controller/eks-cluster-config-handler.go#L133) every time which reenqueues the handler immediately instead of doing a backoff reenqueue and is spamming the logs.
 
#### What was fixed, or what changes have occurred

My solution is to remove the metadata from the EKS logs

What happens now when an EKS error is logged?
- Raw err message is logged
- Remove metadata from the error. If removing metadata fails because the EKS error is not in the expected format, continue with the original logic to prevent a regression.  The new error string will contain the cluster name, error message, and node group.
- If the Status doesn't already contain the error (without metadata), add the error to the Status.

#### Areas or cases that should be tested

* Go to rainbow cluster
* Scale eks-operator deployment replicas to 0
* Run an instance of https://github.com/rancher/eks-operator in golang with the`KUBECONFIG` env var to the kubeconfig for the rainbow cluster. This runs a local version of eks-operator on rainbow
* Provision an EKS cluster via the rancher UI with a custom AMI and node gb of 30 instead of the default 20. You should see the following formatted error appear

![image](https://user-images.githubusercontent.com/12955547/176740608-e4b79dfa-bdf0-49e2-bcb1-cab462c42550.png)
 
#### What areas could experience regressions ?


 
#### Are the repro steps accurate/minimal ?

**Comment by markusewalker** [comment]
Verified in `v2.6-head` https://github.com/rancher/rancher/commit/069433410f08903ae5967e5178867c2622bce419.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/069433410f08903ae5967e5178867c2622bce419
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and logged into Rancher as that user.
3. Provisioned a hosted Amazon EKS cluster. Ensured that the cluster met the following criteria:
     - Custom Ubuntu AMI
     - Node volume size = 20GB
4. Monitored the `Provisioning Log` in the cluster and ensured no unwarranted messages appear.
5. Noted the following error message:
![image](https://user-images.githubusercontent.com/52591819/177398834-b47a7cdd-17cc-4f4b-844f-1ca81816df9c.png) 
     - This is expected as per the repro steps highlighted earlier in this issue. What's important is that there was NOT a flood of EKS operator messages present in the logging.
6. Repeat steps 3-5, but ensured that the Node volume size > 30GB:
![image](https://user-images.githubusercontent.com/52591819/177398868-c241f302-98ba-4445-9df1-0350692e90be.png) 
     - The above is from colleague's testing effort to this issue as for some reason, my AMIs were not yielding successful result.
     - Verified that no flooding of EKS operator messages.

**Comment by mikeh89** [comment]
> If the error returned from EKS is not in that format, the metadata removal will fail and get logged [here](https://github.com/rancher/eks-operator/blob/48c509cd0fe2ff5981048d35c239530607be952c/controller/eks-cluster-config-handler.go#L123) so this bug may appear for future error formats we are unaware of.

Are there any workarounds to this? I'm seeing similar behaviour on Rancher 2.7.6 for a missing LaunchInstanceTemplateVersion on EKS: 

> time="2024-04-16T14:26:51Z" level=error msg="error syncing 'cattle-global-data/c-94tkb': handler eks-controller: error creating nodegroup: InvalidParameterException: Launch template could not be found : Could not find the specified version 3 for the launch template with ID lt-xxxxxxxx.\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"cfed5af4-343f-4c2d-80bb-60d273af2125\"\n  },\n  Message_: \"Launch template could not be found : Could not find the specified version 3 for the launch template with ID lt-xxxxxxxxx.\"\n}, requeuing"
