### ISSUE TITLE
rotate encryption keys phase is automatically failed

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#37673]
The rotate encryption keys phase is automatically being set to Failed.

This is due to the fact that it is not supported by release data.

**Comment by snasovich** [comment]
@jakefhyde to dev-validate.

**Comment by jakefhyde** [comment]
Validated on `v2.6-head`

## Steps

- Deploy rke2/k3s cluster
- View `RKEControlPlane` status: ensure that the `status.rotateEncryptionKeysPhase` is not `"Failed"`
- Edit YAML to add `spec.rkeConfig.rotateEncryptionKeys.generation: 1`
- Observer message containing `"refreshing encryption key rotation state"` in the rancher logs
- Observe that the `status.rotateEncryptionKeysPhase` is now `"Failed"` due to an unsupported version.
