### ISSUE TITLE
Rancher generates prefixed kubeconfig token for every download

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37705]
SURE-4262

**Rancher Server Setup**
- Rancher version: 2.6.3
   
**Describe the bug**
Between v2.5/v2.6 a new prefix-style token is created each time a kubeconfig is requested.

**To Reproduce**
Get a current list of tokens on the Rancher local cluster - kubectl get tokens
Retrieve a kubeconfig from the Rancher UI
List the tokens again and compare
Repeat the steps to confirm tokens are generated each time

**Comment by KevinJoiner** [comment]
Expected outcome: Rancher cleans up old tokens.

**Comment by cbron** [comment]
The most important part of this will be communication. If we do indeed go with a TTL by default, that will need to be made very clear in release notes, and docs will need to be updated. This is just one place: https://rancher.com/docs/rancher/v2.5/en/api/api-tokens/#setting-ttl-on-kubeconfig-tokens

Worried about use case where people expect TTL to live on forever in automation, they upgrade to Rancher 2.6.6, and suddenly after 18 hours all their automation breaks.

**Comment by KevinJoiner** [comment]
## Root Cause
The Rancher server creates a new token for every kubeconfig that is downloaded. These tokens live forever, and admins have no way to manage their cleanup other than manually removing the resources.

## What was fixed, or what change has occurred?
Updates to Rancher token related setting with the addition of `kubeconfig-default-ttl-minutes` and the deprecation of 
`kubeconfig-token-ttl-minutes`. Below are full descriptions of each relevant token setting.
### auth-user-session-ttl-minutes _(no change)_
Time to live (TTL) duration in minutes used to determine when a user auth session token expires. When expired, the user will be required to log in and obtain a new token. This setting is not affected by [`auth-token-max-ttl-minutes`](#auth-token-max-ttl-minutes).

### kubeconfig-default-token-TTL-minutes _(new)_
Time to live (TTL) duration in minutes used to determine when a kubeconfig token expires. When the token is expired, the API will reject the token. This setting can not be larger than [`auth-token-max-ttl-minutes`](#auth-token-max-ttl-minutes).

### kubeconfig-token-ttl-minutes _(deprecated, no change)_
**Deprecated: This setting will be replaced with the value of [`kubeconfig-default-token-TTL-minutes`](#kubeconfig-default-token-ttl-minutes).**
Time to live (TTL) duration in minutes used to determine when a kubeconfig token that was generated by the CLI expires. Tokens are generated by the CLI when [`kubeconfig-generate-token`](#kubeconfig-generate-token) is false. When the token is expired, the API will reject the token. This setting can not be larger than [`auth-token-max-ttl-minutes`](#auth-token-max-ttl-minutes).

### auth-token-max-ttl-minutes _(increased scope to all non session tokens)_
Maximum Time to Live (TTL) in minutes allowed for auth tokens. If a user attempts to create a token with a TTL greater than `auth-token-max-ttl-minutes`, Rancher will set the token TTL to the value of `auth-token-max-ttl-minutes`.



## Areas or cases that should be tested
We need to test the TTL gets set correctly on tokens requested through the following paths: 
1. Downloaded Kubeconfig `https://<rancher-server>/v3/clusters/local?action=generateKubeconfig`
    1. Test `kubeconfig-default-token-TTL-minutes`
       - Create a downstream cluster 
       - Update  `kubeconfig-default-token-TTL-minutes` to '3' `https://<rancher-server>/v3/settings/kubeconfig-default-token-TTL-minutes`
       - Download Kubeconfig for the downstream cluster.
       - Verify kubectl can be used for cluster communication. `kubectl get pods -A`
       - Wait 3 minutes.
       - Verify kubectl returns an unauthorized response. `kubectl get pods -A`
   2. Test `auth-token-max-ttl-minutes` enforcement 
      - Use the same cluster from step 1
      - Update `auth-token-max-ttl-minutes` to '1' `https://<rancher-server>/v3/settings/auth-token-max-ttl-minutes`
      - Download kubeconfig token
      - Verify kubectl can be used for cluster communication. `kubectl get pods -A`
      - Wait 1 minute.
      - Verify kubectl returns an unauthorized response. `kubectl get pods -A`
  
2. Downloaded Kubeconfig with MCM disabled `https://<rancher-server>/v3/clusters/local?action=generateKubeconfig`
   1. Test `kubeconfig-default-token-TTL-minutes` with MCM disabled
      - Create Rancher server with mcm disabled `--features=multi-cluster-management=false`
      - Update  `kubeconfig-default-token-TTL-minutes` to 3 minutes. `https://<rancher-server>/v3/settings/kubeconfig-default-token-TTL-minutes`
      - Download Kubeconfig for the local cluster.
      - Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
      - Wait 3 minutes.
      - Verify kubectl returns an unauthorized response. `kubectl get pods -A`
   2. Test `auth-token-max-ttl-minutes` enforcement wit mcm disabled
      - Use the same cluster from step 1
      - Update `auth-token-max-ttl-minutes` to '1' `https://<rancher-server>/v3/settings/auth-token-max-ttl-minutes`
      - Download kubeconfig for the local cluster
      - Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
      - Wait 1 minute.
      - Verify kubectl returns an unauthorized response. `kubectl get pods -A`
      - 
4. User API Keys `dashboard/account/create-key`
   1. Test `auth-token-max-ttl-minutes` enforcement 
       - Create downstream cluster 
       - Update `auth-token-max-ttl-minutes` to 1 `https://<rancher-server>/v3/settings/auth-token-max-ttl-minutes`
       - Create a new api token that never expires via the endpoint `https://<rancher-server>/dashboard/account/create-key`
       - Verify token is valid 
         ```
         curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
         -H 'Accept: application/json' \
         -H 'Content-Type: application/json' \
         'https://<RANCHER_SERVER>/v3
         ```
       - Wait 1 minute.
       - Verify the token expired.
         ```
         curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
         -H 'Accept: application/json' \
         -H 'Content-Type: application/json' \
         'https://<RANCHER_SERVER>/v3
         ```
5. CLI token command (Local) 
   1. Test `kubeconfig-token-ttl-minutes` 
       - Install latest rancher CLI so that it is accessible in your PATH
       - Create a new rancher server.
       - Update `kubeconfig-token-ttl-minutes` to '3' `https://<rancher-server>/v3/settings/kubeconfig-token-ttl-minutes`
       - Update `kubeconfig-generate-token` to 'false' `https://<rancher-server>/v3/settings/kubeconfig-generate-token`
       - Download kubeconfig for the local cluster
       - Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
       - Wait 1 minute.
       - Verify kubectl returns an unauthorized response. `kubectl get pods -A`
    2. Test `auth-token-max-ttl-minutes` enforcement 
       - Use the same cluster from step 1
       - Update `auth-token-max-ttl-minutes` to 1 `https://<rancher-server>/v3/settings/auth-token-max-ttl-minutes`
       - Download kubeconfig for the local cluster
       - Verify kubectl can be used for cluster communication. `kubectl get pods -A`
       - wait 1 minute.
       - Verify kubectl returns an unauthorized response. `kubectl get pods -A`
  
6. CLI token command (SAML)
   - Install latest rancher CLI so that it is accessible in your PATH
   - Create a new rancher server.
   - Provision a downstream cluster.
   - Add a test-user from a SAML provider as a cluster-owner to the downstream cluster.
   - Update `kubeconfig-token-ttl-minutes` to '3' `https://<rancher-server>/v3/settings/kubeconfig-token-ttl-minutes`
   - Update `kubeconfig-generate-token` to 'false' `https://<rancher-server>/v3/settings/kubeconfig-generate-token`
   - Log in as test-user
   - Download kubeconfig for the downstream cluster.
   - Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
   - Wait 3 minutes.
   - Verify kubectl returns an unauthorized response. `kubectl get pods -A`
   
7. CLI token command (LDAP) 
   - Install latest rancher CLI so that it is accessible in your PATH
   - Create a new rancher server.
   - Provision a downstream cluster.
   - Add a test-user from a SAML provider as a cluster-owner to the downstream cluster.
   - Update `kubeconfig-token-ttl-minutes` to '3' `https://<rancher-server>/v3/settings/kubeconfig-token-ttl-minutes`
   - Update `kubeconfig-generate-token` to 'false' `https://<rancher-server>/v3/settings/kubeconfig-generate-token`
   - Log in as test-user
   - Download kubeconfig for the downstream cluster.
   - Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
   - Wait 3 minutes.
   - Verify kubectl returns an unauthorized response. `kubectl get pods -A`



## What areas could experience regressions
  UI Auth sessions login. 
## Are the repro steps accurate/minimal?
Steps to reproduce the issue.
  1. Create a rancher server
  2. Update `auth-token-max-ttl-minutes` to '1' `https://<rancher-server>/v3/settings/auth-token-max-ttl-minutes`
  3. Download 3 separate kubeconfig tokens.
  4. Navigate to `https://<RANCHER_SERVER>/dashboard/account`
  5. Verify that 3 tokens with the description `Kubeconfig token` are created that never expire

**Comment by cbron** [comment]
Made inline updates, overall lgtm.

**Comment by anupama2501** [comment]
UI ticket: https://github.com/rancher/dashboard/issues/6120

**Comment by anupama2501** [comment]
Verified cases: v2.6-head `0694334` 
Fresh checks:
Test case1 Downloaded Kubeconfig https://<rancher-server>/v3/clusters/local?action=generateKubeconfig
PASS
- Test kubeconfig-default-token-TTL-minutes

1. Test kubeconfig-default-token-TTL-minutes
2. Create a downstream cluster
3. Update kubeconfig-default-token-TTL-minutes to '1' https://<rancher-server>/v3/settings/kubeconfig-default-ttl-minutes
4. Download Kubeconfig for the downstream cluster.
5. Verify kubectl can be used for cluster communication. kubectl get pods -A
6. Wait 3 minutes.
7. Verify kubectl returns an unauthorized response. kubectl get pods -A

- Test auth-token-max-ttl-minutes enforcement

1. Use the same cluster from step 1
2. Update auth-token-max-ttl-minutes to '1' https://<rancher-server>/v3/settings/auth-token-max-ttl-minutes
3. Download kubeconfig token
4. Verify kubectl can be used for cluster communication. kubectl get pods -A
5. Wait 1 minute.
6. Verify kubectl returns an unauthorized response. kubectl get pods -A
```
error: You must be logged in to the server (the server has asked for the client to provide credentials (get pods))
```

Test case2 User API Keys dashboard/account/create-key
PASS
Test auth-token-max-ttl-minutes enforcement
Test auth-token-max-ttl-minutes enforcement

Upgrade test cases:
1. Install rancher on v2.6.5
2. Create a downstream cluster
3. Create a few tokens as an admin in Accounts & API Keys by downloading kubeconfig file from the downstream cluster
4. Upgrade rancher server to v2.6.7-rc1
5. Create a few more tokens
6. From  https://<rancher-server>/v3/settings/kubeconfig-default-ttl-minutes, set the value to `1`
7. Download kubeconfig file and verify the token expires in 1 min
8. Previously created tokens in v2.6.5 were not expired.

**Comment by anupama2501** [comment]
Re opening the issue:
Downloaded Kubeconfig with MCM disabled https://<rancher-server>/v3/clusters/local?action=generateKubeconfig
- Installing rancher with MCM disabled and navigating to https://<rancher-server>/v3/ returns a 403

**Comment by KevinJoiner** [comment]
@anupama2501 Did you attempt to download the kubeconfig through the UI? I believe the UI should be using a /v1 endpoint to download the kubeconfig since /v3 does not exist.

**Comment by anupama2501** [comment]
Verified on v2.6-head `0694334` 

Created a standard user added as a cluster owner and 

**Test case3 Downloaded Kubeconfig with MCM disabled**
`kubeconfig-default-token-TTL-minutes`
1. Create Rancher server with mcm disabled --features=multi-cluster-management=false
```
helm_v3 install rancher rancher-latest/rancher --version 2.6.7-rc1 --namespace cattle-system --set hostname=<redacted> --set rancherImageTag=v2.6-head --set bootstrapPassword=admin --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=multi-cluster-management=false'
```
2. Update kubeconfig-default-token-TTL-minutes to 3 minutes via the UI. <rancherURL>/v1/management.cattle.io.settings/kubeconfig-default-ttl-minutes
3. Download Kubeconfig for the local cluster through the UI from cluster explorer
4. Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. `kubectl get pods -A`
5. Verify kubectl returns an unauthorized response. kubectl get pods -A after 3 minutes

`auth-token-max-ttl-minutes` 

1. Update auth-token-max-ttl-minutes to '1' via the UI <URL>/v1/management.cattle.io.settings/auth-token-max-ttl-minutes
2. Download kubeconfig for the local cluster via the UI
3. Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. kubectl get pods -A
4. Wait 1 minute.
5. Verify kubectl returns an unauthorized response. kubectl get pods -A

**Test case4 CLI token command (Local)**
 kubeconfig-token-ttl-minutes

1. Install latest rancher CLI so that it is accessible in your PATH
2. Create a new rancher server and a downstream cluster
3. Update kubeconfig-generate-token to 'false' https://<rancher-server>/v3/settings/kubeconfig-generate-token
4. Update kubeconfig-token-ttl-minutes to '3' https://<rancher-server>/v3/settings/kubeconfig-token-ttl-minutes
5. Download kubeconfig for the local cluster
6. 5. Provide the credentials for local user
7. Verify kubectl can be used for cluster communication with downloaded KUBECONFIG. kubectl get pods -A
8. Wait 3 minutes.
9. Verify after 3 minutes, users are prompted to re login.

`auth-token-max-ttl-minutes`

1. Use the same cluster from the above test
2. Update auth-token-max-ttl-minutes to 1 https://<rancher-server>/v3/settings/auth-token-max-ttl-minutes
3. Download kubeconfig for the cluster
4. Verify kubectl can be used for cluster communication. kubectl get pods -A
5. Provide the credentials for local user
6. Once the login is successful, verify the kubeconfig token is created under Account & API Keys in the following format `kubeconfig-user-7s6kz.c-mctg7gft24` 
7. wait 1 minute.
8. Verify upon running the command `kubectl get pods` user is prompted to re login.


**Test case5 CLI token command (SAML)**
Verified with oauth auth provider. Same steps as the above test case4
In step 5, select oauth provider option and provided required credentials.

**Test case6 CLI token command (LDAP)**
Verified with openLDAP auth provider. Same steps as the test case4
In step 5, select openldap provider option and provided required credentials.

**Comment by OA72280** [comment]
In Rancher 2.7.0, there does not appear to be a registration token option. In previous versions, I was able to obtain a join token to apply to new worker nodes, or control-plane nodes, etc. Any ideas?

**Comment by jbilliau-rcd** [comment]
hey folks, I'm reading a lot about these settings and how they deprecate tokens as in, they aren't able to be used anymore, but do they also *clean them up*? We have 1,465 users in our Rancher environment and currently, over 155,000 tokens, which seems insane to me. Is there any recommended guidance on cleaning these up? @KevinJoiner

**Comment by KevinJoiner** [comment]
@jbilliau-rcd Rancher will automatically delete Tokens when they expire. You would benefit from setting the default TTL value of tokens to a non-zero value so they do not live forever and get manually cleaned up by Rancher. Checkout our [token docs](https://ranchermanager.docs.rancher.com/reference-guides/about-the-api/api-tokens#token-settings) for more info on what setting to use. I think  [kubeconfig-default-token-TTL-minutes](https://ranchermanager.docs.rancher.com/reference-guides/about-the-api/api-tokens#kubeconfig-default-token-ttl-minutes) would help for your particular use case. As for your current Tokens, Rancher is unable to determine which one's are in use, so you would need to delete Tokens manually. I would suggest a script that looks at the creationTimestamp and deletes Tokens older than X days.
