### ISSUE TITLE
ERROR - cattle-global-data kubernetes version 

### ISSUE THREAD

**Issue by maurodouglas** [rancher/rancher#37784]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE 2 

**Information about the Cluster**
- Kubernetes version: v1.23.6+rke2r1
- Cluster Type (Local/Downstream): Local

I'm getting error on the creation of a Global DNS Provider ( CloudFlare ), it's a brand new install, running rancher 2.6.5 through Helm Install of Stable repository, the global-data pod wasn't createad; 

Docker version: 20.10.16
RKE2: v1.23.6+rke2r1

 2022/05/20 18:39:05 [ERROR] error syncing 'cattle-global-data/cloudflare': handler mgmt-global-dns-provider-catalog-launcher: template system-library-rancher-external-dns incompatible with rancher version or cluster's [local] kubernetes version, requeuing

What's the "maximum" version needed?

**Comment by albertocrj** [comment]
We're facing the exactly same error after an upgrade from rancher 2.5.15 to 2.6.8 :
kubernetes version v1.24.4
rke version v1.3.15

2022/10/03 13:42:42 [ERROR] error syncing 'cattle-global-data/migration1': handler mgmt-global-dns-provider-catalog-launcher: template system-library-rancher-external-dns incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2022/10/03 13:42:42 [ERROR] error syncing 'cattle-global-data/migration2': handler mgmt-global-dns-provider-catalog-launcher: template system-library-rancher-external-dns incompatible with rancher version or cluster's [local] kubernetes version, requeuing

@maurodouglas 
In our case, according to rancher compatibility matrix rancher 2.6.8 supports kubernetes version 1.24 -> https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-8/

We're now going to test with a lower version of kubernetes, because we need to going on with the migration.

Any news about that?


Thanks,

Alberto Viana
