### ISSUE TITLE
[v2.5] vsphere node driver clusters not respecting cpu count, all nodes have 1 cpu each regardless of user input

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37808]
**Setup**
- Rancher version: v2.5-head (62437fcdef179ef502d34fea5acd0f0ca1631112)
- Browser type & version: chrome

**Describe the bug**
when creating a node driver cluster with vsphere, the CPU count is not being respected.

**To Reproduce**
* create a vsphere node driver cluster
  * when creating the node template, specify a node count more than 1 (tested with 4vCPUs)
  * create the cluster

**Result**
nodes have only 1 cpu in rancher and in backend.

**Expected Result**
rancher should respect user input for cpu count. 

**Additional context**
* Using a content library template from vsphere, which has configurable cpus through rancher on v2.6-head
* memory field seems to not be affected
* verified that in the response for the `node template` request, the correct numbers are saved. However, upon updating a cluster, I see there is a field that is sent with the data that might be the culprit:

```
allocatable: {cpu: "1", memory: "8045952Ki", pods: "110"}
cpu: "1"
memory: "8045952Ki"
pods: "110"
```

**Comment by a-blender** [comment]
I was not able to reproduce this on rancher `2.7-head` or `2.6-head.`

Steps
- [ ] Provision a vSphere node driver RKE cluster with a node template using a packer linux os from the `Content Library` and cpu = 4
- [ ] Check allocatable cpu: 4 is set in node template on the backend
- [ ] Check that allocatable cpu: 4 is et on v1 node and synced to mgmt cluster

CPU 4 is set in node template POST request
![image](https://github.com/rancher/rancher/assets/12955547/403e2a12-dfd4-4f62-8299-6e1e4cab647d)

CPU 4 is set on v1 node and synced back
![image](https://github.com/rancher/rancher/assets/12955547/8702888d-d482-40bb-95fc-accf284c3354)

...to the mgmt cluster
![image](https://github.com/rancher/rancher/assets/12955547/d48cdafb-572e-4ccf-b15c-34147c481841)

Saw the same behavior with a vSphere node driver cluster on rancher v2.6-head with CPU = 5.

The [content library was broken](https://github.com/rancher/dashboard/issues/5978) on 2.5.13 and appears to have been fixed on the latest 2.6 and 2.7. Either the content library was directly fixed or this issue is not recurring due to updates to the NodeSync or StatsAggregator controllers. Both of these work together to grab node stats from the v1 node and sync them back to rancher. This can be closed.

**Comment by slickwarren** [comment]
blocked until we have a new vsphere environment up to test with

**Comment by a-blender** [comment]
@slickwarren Unblocking this, as the new vsphere env is available! DM me if you need any help testing this :)

**Comment by slickwarren** [comment]
tested on v2.7.6: this is no longer an issue for vm templates through rancher nor content-library through rancher. Closing this issue.
