### ISSUE TITLE
SystemDefaultRegistry overrides registry Configuration at Downstreamcluster

### ISSUE THREAD

**Issue by grischdian** [rancher/rancher#37867]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.22.9+rke2r2
- Proxy/Cert Details: lets encrypt

**Information about the Cluster**
- Kubernetes version: v1.22.9+rke2r2
- Cluster Type (Local/Downstream): local and downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Priovided Azure RKE2

**User Information**
- What is the role of the user logged in? Admin with max privileges

**Describe the bug**
It worked until 2.6.4 ;)

If a SystemDefaultRegistry is set on Rancher and a different Registry-Mirror config is used for the downstream Cluster the configuration made in the cluster-create-wizard will be not used an is overwritten by SystemDefaultRegistry.

**To Reproduce**
Install Rancher with a SystemDefaultRegistry (e.g. myregistry.company.com) 
Add Cloud Credentials for Azure
Create a new RKE2 Azure Cluster (not aks) and set "configured advanced containers mirroring and registry authentication options" with e.g. mynewregistry.company.com 
Wait for the VM to start
ssh to vm (get public IP from azure Portal and key from rancher)
have a look at /etc/rancher/rke2/config.yaml.d/50-rancher.yaml

**Result**
You will find the SystemDefaultRegistry _NOT_ the one you set in "configured advanced containers mirroring and registry authentication options" in the config file

**Expected Result**
I find the registry I've configured in "configured advanced containers mirroring and registry authentication options" 

**Additional context**
In our environment we mirror all images to harbor into project which means the URL of the rancher Repo is not myharbor.company.com but myharbor.company.com/rancher.

I'm able to add the systemDefaultRegistry so Rancher and AKS can fetch all needed images but for the downstream cluster Rancher complains that myharbor.company.com/rancher is not in the correct URI format. That's the reason why we've created the mirror configuration for all downstream cluster (for containerd) but since 2.6.5 this is overwritten.

**Comment by HarrisonWAffel** [comment]
Sorry for the delay when looking into this issue, there have been many shifts in priorities recently due to the release of 2.7.2 since I have picked up this task. 

I've looked into this issue for some time, but have unfortunately been unable to reproduce the expected behavior on 2.6.4 or 2.6.3. The following steps were performed in an attempt to reproduce 

+ Create a docker registry and load all images into a `testrepo` repository so that images are tagged in the following format`registry.com/testrepo/rancher/<IMAGE>`, this matches the format described in the 'Additional Context' of this ticket
+ Create a Rancher 2.6.4 server 
+ Set the global default registry to the above registry, `registry.com/testrepo`
+ Begin to create an RKE2 cluster on Azure
   + navigate to the 'Configure advanced container mirroring and registry authenticaiton options'
   + Select 'Advanced options' and create a new mirror 
       + In the leftmost box, place the URL for the global system default registry, `registry.com/testrepo`
       + in the rightmost box, place the URL you expect images to be tagged as, `registry.com`
+ Create the cluster 
+ SSH into the cluster and look at the `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` file 

In both scenarios I was not able to observe the system-default-registry field change in accordance with the mirror options I had configured. 

@grischdian I know this ticket has existed for some time now, so apologies for the delayed response, but do you have additional details that would help in reproducing the initial behavior? If this behavior did change between 2.6.4 and 2.6.5 we would treat this as a bug for a future release, but I need to confirm the initial behavior so I can begin to look for a root cause.
