### ISSUE TITLE
Support of Outscale providers

### ISSUE THREAD

**Issue by outscale-mdr** [rancher/rancher#37886]
Hello Rancher team,

At [Outscale](https://outscale.com/), we have implemented a node driver in order to create clusters from Rancher.
- [Docker plugin](https://github.com/outscale-dev/docker-machine-driver-outscale)
- [Ui plugin](https://github.com/outscale-dev/rancher-ui-driver-outscale)

We now would like to go one step further and make that driver available rancher natively.

Could you explain to us the process to make this possible ?

Thank you,
Best regards,
Maxime

**Comment by outscale-mdr** [comment]
Up

**Comment by snasovich** [comment]
The main PR to `rancher/rancher` got merged to release/v2.6 before we branched `release/v2.7` off it, so the changes are in branches for both the next 2.6.x and 2.7.0 release.

@outscale-mdr , merged your PR and moved this issue to test. Since your team is handling testing, could you or anyone from your team please test it on v2.6-head Docker image and confirm it's working as expected (you have the driver available to be enabled and once enabled it works)?

**Comment by outscale-mdr** [comment]
Hello @snasovich,

I just get back to work today. Sorry for the delay.

Thank you for the update, I will test it and will confirm you that it is working.

**Comment by outscale-mdr** [comment]
Hello,

Do I need to do something for the dashboard ? Like pushing our logo [here](https://github.com/rancher/dashboard/tree/master/shell/assets/images/providers) ?

Best regards,
Maxime

**Comment by outscale-mdr** [comment]
I confirm that the plugin works in the v2.6.9-rc2

**Comment by sowmyav27** [comment]
Hi Maxime @outscale-mdr , thanks for confirmation. Does this mean this issue can be closed ^? 
thanks.

**Comment by annablender** [comment]
@sowmyav27 The changes are in both rancher 2.6-head and 2.7. @outscale-mdr confirmed it works in v2.6.9-rc2. I think that's good enough to close. If they have any issues on 2.7, they can reach out

**Comment by outscale-mdr** [comment]
Thanks to all the team ! I'm closing this issue.
