### ISSUE TITLE
Broken times/dates when not using default format

### ISSUE THREAD

**Issue by abrondijk** [rancher/rancher#37929]
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option:
   - Helm: 2.6.5
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.6+k3s1
- Cluster Type (Local/Downstream):
   Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  Admin

   
**Describe the bug**
Changing the date or time format causes them to not display properly anymore, at least when viewing events (see screenshot from the cluster page). The entry that is shown on the preferences page is also messed up when it is changed.

**To Reproduce**
Change the default date and time format to anything.

**Result**
Messed up times and dates, see the screenshots below.

**Expected Result**
The format of the date or time to be what is set.

**Screenshots**
![image](https://user-images.githubusercontent.com/73667900/172380456-cae0018d-933c-4dad-8753-921de9e6f32e.png)
![image](https://user-images.githubusercontent.com/73667900/172380513-30871363-ae07-4fc0-9d5c-69974b81e36e.png)

**Comment by rak-phillip** [comment]
@abrondijk Thanks for raising this issue and helping to make rancher better. 

This issue was addressed in rancher/dashboard#5979 and will be fixed in v2.6.6. Feel free to follow up there if you have any questions or comments. 

I'm going to close this issue in interest of keeping information in one place. Please comment if you feel this issue needs to be reopened.

**Comment by abrondijk** [comment]
Ah I did not realize that there was a different repo for the dashboard itself. Thanks!
