### ISSUE TITLE
Azure AD - changing the admin user of azureAD auth results in an error  

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37948]
**Rancher Server Setup**
- Rancher version: `v2.5.14` upgraded to `v2.6-head f4d09c7`
- Installation option (Docker install/Helm Chart): `Docker install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.6`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin
   
**Describe the bug**
On v2.5.14, when we enable AzureAD we provide an admin. Post rancher upgrade, and post azureAD endpoint migration, if we try ti change the admin user to a different user, fails in an error.

**To Reproduce**
1. On rancher server v2.5.14, enable Azure AD auth from apps & market >> Auth Providers >> Azure AD
2. Upgrade the rancher server from v2.5.14 >> v2.6-head 
3. Upgrade the graph endpoint via kubectl as follows:
```
k edit authconfigs azuread
Update the following endpoints:
graphEndpoint: https://graph.microsoft.com
authEndpoint: https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/authorize
tokenEndpoint: https://login.microsoftonline.com/<tenanantID>/oauth2/v2.0/token
```
4. From Azure portal, add the additional permissions in the test app
5. From apps & Market >> Azure AD >> edit config >> provide the Application Secret >> Login as different user than admin from the microsoft login portal.

**Result**
Fails with the error:
```
refusing to set principal on user that is already bound to another user
```
022/06/08 22:31:28 [ERROR] Error refreshing token principals, skipping: UsersClient.BaseClient.Get(): unexpected status 400 with OData error: Request_BadRequest: Bad request. Please fix the request before retrying.
2022/06/08 22:32:40 [ERROR] refusing to set principal [azuread_user:/<redacted>] on user [Default Admin], principal already in use on user [testuser9]
2022/06/08 22:32:40 [ERROR] Unknown error: refusing to set principal on user that is already bound to another user

**Expected Result**
Expected the admin user to be changed to the new user.

**Additional context**
If we do not upgrade the end points, the change works fine.

**Comment by anupama2501** [comment]
Noticed the error `refusing to set principal on user that is already bound to another user
` pops when we change the admin to a user that has either a cluster/project membership in that rancher server already.

**Comment by maxsokolovsky** [comment]
Discussed offline, capturing this here:
### This behavior is normal in Rancher v2.6.x.

The reason is that Rancher does not allow an external user to be associated with more than one local user.

Say, you set up Azure AD and login as user1, so it's an external user associated with a local user (default admin).
Then you add user2 to the project, which creates a local user associated with it. Then you re-set your auth config thereby attempting to login as admin as user2, so Rancher tries to create an association between user2 and local admin. But your user2 is already associated with its local user created earlier, when it was added to the project.

And Rancher does not allow an external user to be associated with more than one local user.
To switch admins, you need to indeed delete your user1 before resetting authconfig and logging in as user2, who will become the new admin. This is not pretty, and there is no special button to switch the association of a local admin with another external user.

But this is how this works with all auth providers, not just Azure AD.

**Comment by maxsokolovsky** [comment]
I think we can close this, now that there is also a note in the docs (2.6 and 2.7) about it.

**Comment by anupama2501** [comment]
Closing based on the above comments

**Comment by jansobczak** [comment]
If anyone struggle to change settings because you lost the ability to login via provider you can change this on k8s level example
```
kubectl edit authconfig azuread
```

**Comment by papanito** [comment]
> Say, you set up Azure AD and login as user1, so it's an external user associated with a local user (default admin).

Where does this happen. 

> delete your user1 before resetting authconfig
 
I don't see `user1` under "Users & Authentication > Users"
