### ISSUE TITLE
fix gouroutine leak when sharedcontroller has been started

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37965]

**Comment by samjustus** [comment]
[lasso PR](https://github.com/rancher/lasso/pull/30)

**Comment by JacieChao** [comment]
# Problem 

If there's something wrong with downstream clusters and usercluster controller has to restart frequency, will cause goroutine leaks with management controller factory. 
When the usercluster controller starts to handle a downstream cluster, we also start management controllers [here](https://github.com/rancher/rancher/blob/release/v2.5/pkg/types/config/context.go#L490)  where the goroutine leaks problem happens.  

# Solution 

1. Rancher will start a usercluster controller for each downstream cluster and will start management controller factory [here](https://github.com/rancher/rancher/blob/release/v2.5/pkg/types/config/context.go#L490). The management controller factory will start only once because it checked `started` state [here](https://github.com/rancher/lasso/blob/release/v2.5/pkg/controller/controller.go#L153). If there's something wrong with the downstream cluster and usercluster controller has to stop, it canceled the context and skip goroutine [here](https://github.com/rancher/lasso/blob/release/v2.5/pkg/controller/sharedcontroller.go#L97). The management controller factory context is never canceled if Rancher is still running so that each time we start a usercluster controller, the goroutine leaks [here](https://github.com/rancher/lasso/blob/release/v2.5/pkg/controller/sharedcontroller.go#L92). So we also need to check `started` state to avoid creating more goroutine leaks if the controller has started. 

2. It set `started` state in Start() function but never set `unstarted` state for shutting down works when channel done. The controller may fail to start when we restart it. 

# Testing 

## Engineering Testing 

### Manual Testing 

1. Deploy HA Rancher and set up Prometheus dashboard for controllers. Refer to: https://github.com/rancher/rancher/wiki/How-to-setup-prometheus-dashboard-for-controllers 
2. Add an import cluster to Rancher and run the following scripts to test usercluster controller restart. 
``` 
#!/bin/bash

# =============== Usage ===============
# ./test.sh <cluster-id> <limit-times> <interval>
# ./test.sh c-xxxx 100 3
# Need to running on the node which can access to Rancher local cluster(Need to running on the node which can access to Rancher local cluster).
# =======================================

clusterid=$1
limit=$2
interval=$3

n=1
while [ $n -le $limit ]
do
    cluster=$(kubectl get clusters.management.cattle.io $clusterid -o json)
    for k in $(jq '.status.conditions | keys | .[]' <<< $cluster); do
        value=$(jq ".status.conditions[$k]" <<< $cluster);
        type=$(jq -r '.type' <<< "$value");
        if [ $type == 'Provisioned' ]; then
            kubectl patch clusters.management.cattle.io $clusterid --type='json' -p='[{"op": "replace", "path": "'/status/conditions/$k/status'", "value":"False"}]'
            break
        fi
    done
    sleep $interval
    let n++
done
``` 

3. Get go_goroutines{job="rancher-metrics"} in Prometheus Graph page. Before fixing this issue(**tested with v2.5.14**), we can see the goroutine continued growth when we finish running the script. 
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/23305062/174243217-5d7e99ee-55ea-467b-b01e-92e722cfebda.png">

4. Tested with fixed dev version, we can compare with the goroutine metrics that prove the goroutine leaks problem fixed.
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/23305062/174243296-23c91eaa-351c-4782-a92e-4ea3ac50f996.png">

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type   |
| ------------------------- | ---------------- |
| Rancher version           | 2.5.15           |
| Installation option       | helm             |
| RKE binary version used   | 1.2.20           |
| If Helm Chart k8s cluster | 1.20.15          |
| Cert Details              | let's encrypt    |
| Helm version              | v2.16.8-rancher1 |
| Downstream cluster type   | rke1 amazon ec2  |
| Downstream K8s version    | v1.20.15         |
| Logged in user role       | administrator    |
| Browser type              | google chrome    |
| Browser version           | 103.0.5060.134   |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set replicas=3 \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.5.15
```

## Reproduction steps

1. Starting from the **default** homepage `/g/clusters`
   1. Hover over `Global` ==> `local` ==> click `System`
   2. Hover over `Resources` ==> click `Workloads`
   3. Click the `ellipsis (three dots)` next to the `rancher` deployment under `cattle-system` ==> click `Edit`
   4. Click `Environment Variables` ==> `Add Variable`
   5. Key ==> `CATTLE_PROMETHEUS_METRICS`
   6. Value ==> `true` (no quotes around true)
   7. Click `Save` ==> wait for deployment to finish redeploying
2. Create a downstream rke1 amazon ec2 cluster
3. Run the following script in a shell that has exported the local cluster's kubeconfig file

```bash
#!/bin/bash

# =============== Usage ===============
# ./test.sh <cluster-id> <limit-times> <interval>
# ./test.sh c-xxxx 100 3
# Need to running on the node which can access to Rancher local cluster(Need to running on the node which can access to Rancher local cluster).
# =======================================

clusterid=$1
limit=$2
interval=$3

n=1
while [ $n -le $limit ]
do
    cluster=$(kubectl get clusters.management.cattle.io $clusterid -o json)
    for k in $(jq '.status.conditions | keys | .[]' <<< $cluster); do
        value=$(jq ".status.conditions[$k]" <<< $cluster);
        type=$(jq -r '.type' <<< "$value");
        if [ $type == 'Provisioned' ]; then
            kubectl patch clusters.management.cattle.io $clusterid --type='json' -p='[{"op": "replace", "path": "'/status/conditions/$k/status'", "value":"False"}]'
            break
        fi
    done
    sleep $interval
    let n++
done
```

4. Go to the `/metrics` endpoint once the script has started, check it throughout as well
5. Once the script ends check the amount of go routines compared to the start 
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Expected the go routines not to drastically increase

#### :x: Actual
The go routine amount increased substantially 

#### Screenshots
![2022-07-26_16-27-43](https://user-images.githubusercontent.com/40877149/181161398-2a8131c5-ebd3-466a-a330-6da05bb402aa.png)


<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.5-6f124d5b970d22ac815996021d0b1aba75da476d-head                                 |
| Rancher commit link       | https://github.com/rancher/rancher/commit/6f124d5b970d22ac815996021d0b1aba75da476d |
| Installation option       | helm                                                                               |
| RKE binary version used   | 1.2.20                                                                             |
| If Helm Chart k8s cluster | v1.20.15                                                                           |
| Cert Details              | let's encrypt                                                                      |
| Helm version              | v2.16.8-rancher1                                                                   |
| Downstream cluster type   | rke1 amazon ec2                                                                    |
| Downstream K8s version    | v1.20.15                                                                           |
| Logged in user role       | administrator                                                                      |
| Browser type              | google chrome                                                                      |
| Browser version           | 103.0.5060.134                                                                     |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set replicas=3 \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.5-head
```

## Validation steps


1. Starting from the **default** homepage `/g/clusters`
   1. Hover over `Global` ==> `local` ==> click `System`
   2. Hover over `Resources` ==> click `Workloads`
   3. Click the `ellipsis (three dots)` next to the `rancher` deployment under `cattle-system` ==> click `Edit`
   4. Click `Environment Variables` ==> `Add Variable`
   5. Key ==> `CATTLE_PROMETHEUS_METRICS`
   6. Value ==> `true` (no quotes around true)
   7. Click `Save` ==> wait for deployment to finish redeploying
2. Create a downstream rke1 amazon ec2 cluster
3. Run the following script in a shell that has exported the local cluster's kubeconfig file

```bash
#!/bin/bash

# =============== Usage ===============
# ./test.sh <cluster-id> <limit-times> <interval>
# ./test.sh c-xxxx 100 3
# Need to running on the node which can access to Rancher local cluster(Need to running on the node which can access to Rancher local cluster).
# =======================================

clusterid=$1
limit=$2
interval=$3

n=1
while [ $n -le $limit ]
do
    cluster=$(kubectl get clusters.management.cattle.io $clusterid -o json)
    for k in $(jq '.status.conditions | keys | .[]' <<< $cluster); do
        value=$(jq ".status.conditions[$k]" <<< $cluster);
        type=$(jq -r '.type' <<< "$value");
        if [ $type == 'Provisioned' ]; then
            kubectl patch clusters.management.cattle.io $clusterid --type='json' -p='[{"op": "replace", "path": "'/status/conditions/$k/status'", "value":"False"}]'
            break
        fi
    done
    sleep $interval
    let n++
done
```

4. Go to the `/metrics` endpoint once the script has started, check it throughout as well
5. Once the script ends check the amount of go routines compared to the start 
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
No go routine increase

#### :white_check_mark:Actual
No go routine increase

#### Screenshots
![2022-07-26_16-27-43](https://user-images.githubusercontent.com/40877149/181161117-b45005e9-0327-4ec4-8e09-fbae422de085.png)
