### ISSUE TITLE
Chart for ingress-nginx ingress resource is missing ingressClassName

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#37971]
A networking.k8s.io/v1/Ingress resource always needs the `ingressClassName` specified if the controller is nginx, otherwise, a new ingress is ignored or the ingress controller pod fails to start. This is relevant for K8s v1.22+.
`"Ignoring ingress because of error while validating ingress class" ingress="cattle-system/rancher" error="ingress does not contain a valid IngressClass"`

**Comment by brudnak** [comment]
Temporary Rancher QA workaround if you come across this issue:

Run `kubectl edit ingress rancher  -n cattle-system` and add a line under spec for `ingressClassName: nginx`

```yaml
spec:
  ingressClassName: nginx
```

**Comment by maxsokolovsky** [comment]
## QA Testing

### Root cause
Rancher may be unavailable to external requesters if the ingress controller
does not validate Rancher's ingress resource when it does not define `ingressClassName` in its definition.
This has been detected with the nginx ingress controller of a version greater than 4.x.

Users whose Rancher instances are backed by RKE clusters do not face this issue because
RKE, when setting up the local cluster, takes care to instruct the nginx ingress controller
to automatically insert the `ingressClassName` with a value of `nginx` if it's missing.

This does not happen with EKS or GKE clusters, so Rancher instances backed by those providers, and taking
advantage of the nginx ingress controller, may face this issue.

### What was fixed, or what changes have occurred
We expose the `ingress.ingressClassName` chart value. By default, its value is an empty string because
we do not make assumptions about the type of an ingress controller that runs in Rancher (nginx, traefik, etc.).

### Areas or cases that should be tested
1. Rancher instance backed by an RKE K8s cluster.
1. Rancher instance backed by a non-RKE K8s cluster, like EKS or GKE, for example.
Both cases need upgrade tests.

### What areas could experience regressions?

### Are the repro steps accurate/minimal?
#### RKE-based Rancher
1. Deploy an HA Rancher instance backed by RKE. Use Helm and choose a non-latest version of Rancher's image.
1. Inspect the Rancher ingress and ensure it does include the `ingressClassName` in its spec definition.
`kubectl get ingress -o yaml -n cattle-system rancher | grep ingressClassName`
1. Ensure that you can access the cluster on its hostname URL.
1. Use Helm to upgrade the Rancher release. Do not specify the `ingressClassName` value to Helm.
1. Ensure the ingress resource still has the class name, and Rancher is still accessible.

#### EKS-based Rancher
1. Provision an EKS Kubernetes cluster.
1. Deploy an ingress-nginx release.
```
helm upgrade --install \
  ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --set controller.service.type=LoadBalancer \
  --version 4.0.18 \
  --create-namespace
```
1. Deploy Rancher. Use Helm and choose a non-latest version of Rancher's image.
1. Inspect the Rancher ingress and ensure it does NOT include the `ingressClassName` in its spec definition.
1. Ensure that you cannot access the cluster on its hostname URL.
1. Inspect the logs of the ingress-nginx controller pod. Search for errors and find the one that says the controller
refused to allow the ingress resource defined by Rancher, because it does not have the `ingressClassName` defined.
1. Upgrade the Rancher release, make sure the chart is of the version that includes this issue's change. Specify
the `ingress.ingressClassName` as `nginx` on the command line to Helm.
1. Ensure the ingress resource still now the class name, and Rancher is accessible.

**Comment by samjustus** [comment]
SURE-4960

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component               | Version / Type       |
| ----------------------- | -------------------- |
| Rancher version         | v2.6.6               |
| Installation option     | `eksctl` eks local   |
| local k8s cluster       | v1.22.10-eks-84b4fe6 |
| Cert Details            | let's encrypt        |
| Helm version            | v2.16.8-rancher2     |
| Downstream cluster type | not applicable       |
| Downstream K8s version  | not applicable       |
| Logged in user role     | administrator        |
| Browser type            | google chrome        |
| Browser version         | 102.0.5005.115       |

**ADDITIONAL SETUP**

## Reproduction steps

1. Create an EKS cluster with `eksctl`

```shell
eksctl create cluster \
  --name $NAME_VAR \
  --version 1.22 \
  --region $REGION_VAR \
  --nodegroup-name $NG_NAME_VAR \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

2. Install an nginx ingress

```shell
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm upgrade --install \
  ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --set controller.service.type=LoadBalancer \
  --version 4.0.18 \
  --create-namespace
```

3. Install rancher 
   
4. Try to access the rancher UI

  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Being able to access the rancher UI

#### :x: Actual
Unable to access the rancher UI

**WORK AROUND**

1. Run this command:

```shell
kubectl edit ingress rancher -n cattle-system
```

2. Add this line under `spec`

```yaml
spec:
  ingressClassName: nginx 
```

<hr>
  
## Validation Environment

| Component               | Version / Type       |
| ----------------------- | -------------------- |
| Rancher version         | v2.6.7-rc2           |
| Installation option     | `eksctl` eks local   |
| local k8s cluster       | v1.22.10-eks-84b4fe6 |
| Cert Details            | let's encrypt        |
| Helm version            | v2.16.8-rancher2     |
| Downstream cluster type | not applicable       |
| Downstream K8s version  | not applicable       |
| Logged in user role     | administrator        |
| Browser type            | google chrome        |
| Browser version         | 102.0.5005.115       |

## Validation steps

1. Create an EKS cluster with `eksctl`

```shell
eksctl create cluster \
  --name $NAME_VAR \
  --version 1.22 \
  --region $REGION_VAR \
  --nodegroup-name $NG_NAME_VAR \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

2. Install an nginx ingress

```shell
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm upgrade --install \
  ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --set controller.service.type=LoadBalancer \
  --version 4.0.18 \
  --create-namespace
```

3. Install rancher with ` --set ingress.ingressClassName=nginx`

```shell
helm install rancher rancher-latest/rancher \
  --version 2.6.7-rc2 \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \ 
  --set ingress.ingressClassName=nginx
```

4. Try to access the rancher UI
5. Able to successfully access the rancher UI
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
To be able to access the rancher UI without a work around

#### :white_check_mark:Actual
Was able to access the rancher UI without a work around

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>RKE-based Rancher</td>
            <td>
                <ol>
                    <li>Deploy an HA Rancher instance backed by RKE. Use Helm and choose a non-latest version of Rancher's image</li>
                    <li>Inspect the Rancher ingress and ensure it does include the ingressClassName in its spec definition.</li>
                    <li>Ensure that you can access the cluster on its hostname URL</li>
                    <li>Use Helm to upgrade the Rancher release. Do not specify the ingressClassName value to Helm</li>
                    <li>Ensure the ingress resource still has the class name, and Rancher is still accessible</li>
                </ol>
            </td>
            <td>Not to lose access while upgrading rke based cluster</td>
            <td>Did not lose access wile upgrading an rke based cluster</td>
            <td>:white_check_mark: PASS</td>
        </tr>
        <tr>
            <td>EKS-based Rancher</td>
            <td>
                <ol>
                <li>Provision an EKS Kubernetes cluster</li>
                <li>Deploy an ingress-nginx release</li>
                <li>Deploy Rancher. Use Helm and choose a non-latest version of Rancher's imag</li>
                <li>Inspect the Rancher ingress and ensure it does NOT include the ingressClassName in its spec definition</li>
                <li>Ensure that you cannot access the cluster on its hostname URL</li>
                <li>Inspect the logs of the ingress-nginx controller pod. Search for errors and find the one that says the controller
refused to allow the ingress resource defined by Rancher, because it does not have the ingressClassName defined</li>
                <li>Upgrade the Rancher release, make sure the chart is of the version that includes this issue's change. Specify
the ingress.ingressClassName as nginx on the command line to Helm</li>
                <li>Ensure the ingress resource now has the class name, and Rancher is accessible</li>
                </ol>
            </td>
            <td>When upgrading with additional helm value ingress begins to work</td>
            <td>Ingress works when upgrading and passing helm value</td>
            <td>:white_check_mark: PASS</td>
        </tr>
    </tbody>
</table>

**Comment by chokosabe** [comment]
This fix really isn't ideal. All the docs out there - even the dedicated rancher books don't mention having to set the ingress class. Its a messy fix at best.
