### ISSUE TITLE
User-supplied bootstrap password not observed in air-gapped Rancher v2.6.5 installation

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37993]
SURE-4736

**Rancher Server Setup**
- Rancher version: 2.6.5

**Describe the bug**
The Rancher air-gapped installation docs (https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/install-rancher/#3-render-the-rancher-helm-template) document templating the Rancher chart with the --no-hooks argument provided to the `helm template` command. This prevents rendering of the post-delete hook Job. However, as a result of the helm.sh/hook annotation added to the bootstrap-secret in Rancher v2.6.5 this also prevents rendering of the bootstrap-secret (https://github.com/rancher/rancher/blob/v2.6.5/chart/templates/secret.yaml versus https://github.com/rancher/rancher/blob/v2.6.4/chart/templates/secret.yaml) 

**To Reproduce**

1. Install Rancher v2.6.5 per air-gapped installation docs (https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/install-rancher/#3-render-the-rancher-helm-template) supplying the bootstrap password
2. Observe user-supplied bootstrap password is not set

**Result**
Bootstrap password secret not created in air-gapped installation

**Expected Result**
Bootstrap password secret created in air-gapped installation

**Comment by samjustus** [comment]
We should attempt to automate a regression test for this helm template air-gap command.

**Comment by MbolotSuse** [comment]
I'm going to treat this as a docs issue. 

The core problem here is that our install instructions for proxy scenarios contain a `--no-hooks` directive. Since our bootstrap password is now a hook, it isn't created/installed in the airgap scenarios. Our strategy to install charts in an airgap scenario is to use `helm template` to produce the resources that are to be installed, and then use `kubectl apply` to install the resources. If we included the hooks in this process, this would likely run the hooks at install time, which is not a desired solution and could lead to unexpected behavior. We appear to have been forced into this solution to support installing from a rancher chart retrieved though `helm fetch rancher-latest/rancher`, which produces a `.tgz` file (containing the chart definitions). Since `helm install` could not be used with this file, we had to ignore the hooks.

However, helm supports the use of a `.tgz` defined chart with `helm install` (thanks to @jiaqiluo for pointing this out). Because of this, we can change our install instructions to have users use `helm install` as opposed to `helm template` & `kubectl apply`. This approach worked on a basic test, and should simplify our install instructions for proxy scenarios.

Other options (such as a code level fix or custom user docs showing how to create the bootstrap secret through kubectl) were considered and rejected due to issues with regressions and overall user experience. QA will need to do a full validation of the new install method to ensure that it fits the needs for customers in the long term.

**Comment by markusewalker** [comment]
@MbolotSuse for validation on my end since I am unaware of offline slack conversation, is QA specifically meant to validate the instructions in the linked documentation causes the mentioned failure?

If this incorrect, can you please further clarify?

**Comment by MbolotSuse** [comment]
@markusewalker To clarify, it's the opposite. QA is intended to validate that the updated docs allow you to get around the failure. See this PR for the updated docs: https://github.com/rancher/rancher-docs/pull/213. They need QA validation before they can go in.

**Comment by markusewalker** [comment]
Awaiting for new RKE RC to be cut before further looking into this issue. There were complications seen in initial testing that may be related to current airgapped failures due to lack of RKE RC.

I will test again once new RKE RC is available.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
1. Setup air-gapped Rancher: Follow the updated document highlighted in the PR to create an air-gapped Rancher environment with a user-supplied boostrap password

**Comment by markusewalker** [comment]
Tested this against `v2.7.0-rc3`.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7.0-rc3`
- Browser: Chrome
- Registry: Docker w/self-signed certificate

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|Setup air-gapped Rancher: Follow the updated document highlighted in the PR to create an air-gapped Rancher environment with a user-supplied bootstrap password|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. On a client machine, ensured that Helm is installed properly.
2. Added rancher repo with command `helm repo add rancher-latest https://releases.rancher.com/server-charts/latest`.
3. Fetched latest Rancher chart with command `helm fetch rancher-latest/rancher --version=v2.7.0-rc3`.
4. Added the cert-manager repo with command `helm repo add jetstack https://charts.jetstack.io; helm repo update`.
5. Fetched the cert-manager chart with command `helm fetch jetstack/cert-manager --version v1.7.1`.
6. Retrieved the cert-manager CRDs with command `curl -L -o cert-manager/cert-manager-crd.yaml https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml`.
7. Created a namespace for cert-manager with command `kubectl create ns cert-manager`.
8. Created the CRDs with command `kubectl apply -f cert-manager/cert-manager-crd.yaml`.
9. Installed cert-manager with command:
 ```
helm installed cert-manager ./cert-manager-v1.7.1.tgz  \
    --ns cert-manager \
    --set image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-controller \
    --set webhook.image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-webhook \
    --set cainjector.image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-cainjector \
    --set startupapicheck.image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-ctl`.
```
10. Created namespace for Rancher with command `kubectl create ns cattle-system`.
11. Installed Rancher with command:
```
   helm installed rancher ./rancher-<VERSION>.tgz \
    --namespace cattle-system \
    --set hostname=<RANCHER.YOURDOMAIN.COM> \
    --set certmanager.version=<CERTMANAGER_VERSION> \
    --set rancherImage=<REGISTRY.YOURDOMAIN.COM:PORT>/rancher/rancher \
    --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ 
    --set useBundledSystemChart=true # Use the packaged Rancher system charts`.
```
12. Noted that I am seeing the following behavior:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "rancher" namespace: "" from "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"

@MbolotSuse following the associated guide, I am seeing the error as noted in step 12. Is there additional steps that I need to take that's causing this issue, or does the doc need further updating?
ensure CRDs are installed first
```

**Comment by MbolotSuse** [comment]
@markusewalker This looks like the rancher chart attempted to use a lower version for the cert-manager issuer record than we would expect for cert manager 1.7.1. 

I'm guessing that this happened because in step 11 you used the cert manager version of `v1.7.1`. From what I can see this messes up our chat's version checks. If you use `1.7.1` (without the v in front of it), this should work as expected. When running a test on my local using `v1.7.1` gave the issue an api version of `certmanager.k8s.io/v1alpha1`, but using `1.7.1` gave an api version of `cert-manager.io/v1`. Installing using `v1.7.1` on my setup failed with the error message you showed above, but using `1.7.1` I was able to install successfully.

I'm going to move this back to test. Please test with the correct value for the `certmanager.version` in step 11. If I'm wrong, please provide the values that you used in step 11 so that I can more fully reproduce the issue.

**Comment by markusewalker** [comment]
Tested this again against `v2.7.0-rc3`.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7.0-rc3`
- Browser: Chrome
- Registry: Docker w/self-signed certificate

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|Setup air-gapped Rancher|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. On a client machine, ensured that Helm is installed properly.
2. Added rancher repo with command `helm repo add rancher-latest https://releases.rancher.com/server-charts/latest`.
3. Fetched latest Rancher chart with command `helm fetch rancher-latest/rancher --version=v2.7.0-rc3`.
4. Added the cert-manager repo with command `helm repo add jetstack https://charts.jetstack.io; helm repo update`.
5. Fetched the cert-manager chart with command `helm fetch jetstack/cert-manager --version v1.7.1`.
6. Retrieved the cert-manager CRDs with command `curl -L -o cert-manager/cert-manager-crd.yaml https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml`.
7. Created a namespace for cert-manager with command `kubectl create ns cert-manager`.
8. Created the CRDs with command `kubectl apply -f cert-manager/cert-manager-crd.yaml`.
9. Installed cert-manager with command:
 ```
helm installed cert-manager ./cert-manager-v1.7.1.tgz  \
    --ns cert-manager \
    --set image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-controller \
    --set webhook.image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-webhook \
    --set cainjector.image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-cainjector \
    --set startupapicheck.image.repository=<REGISTRY.YOURDOMAIN.COM:PORT>/quay.io/jetstack/cert-manager-ctl`.
```
10. Created namespace for Rancher with command `kubectl create ns cattle-system`.
11. Installed Rancher with command:
```
   helm install rancher ./rancher-2.7.0-rc3.tgz \
    --namespace cattle-system \
    --set hostname=<RANCHER.YOURDOMAIN.COM> \
    --set certmanager.version=1.7.1 \
    --set rancherImage=<REGISTRY.YOURDOMAIN.COM:PORT>/rancher/rancher \
    --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ 
    --set useBundledSystemChart=true \
    --set bootstrapPassword=<password>
```
12. Rancher is able to be installed as expected.
