### ISSUE TITLE
Unable to login to rancher server after a rancher server roll back via docker when azure AD is enabled

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38025]
**Rancher Server Setup**
- Rancher version: `v2.6.5` upgraded to `v2.6-head 0042faa rolled back to v2.6.5`
- Installation option (Docker install/Helm Chart): `Docker install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.6`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin
   
**Describe the bug**
Login fails when a rancher server is rolled back from v2.6.6-rc1 or v2.6-head when azure AD is enabled if we upgrade the azure AD end point in 2.6.6-rc1. This is because the azure AD end points will not be rolled back if the roll back is not performed via backup/restore charts.

**Solution here will be docs/release-note:**

If you want to rollback Rancher to use the old Azure AD Graph API without using the backup-restore operator, edit the azuread authconfig resource stored in the local cluster's database (you must have permission to edit this resource). Old azure AD auth graph endpoints will not be rolled back on a rancher roll back.

**Comment by maxsokolovsky** [comment]
Discussed offline, to summarize here: this is not an issue, but a consequence of rolling back a single-node instance of Rancher in Docker.

We can't make any guarantees about Rancher working correctly - because one might rollback to the old Rancher image but still have the newer version's database. This is how one can get to this inconsistent state with Azure AD, where there is a rollback to v2.6.5, but with the new data, which has the new endpoint, since the database state is like it was in the new Rancher v2.6-head.
With a backup-restore operator, you would rollback both the backend code and the database.

This issue exists to track release notes or any other documentation where we specify how to manually revert all endpoints to have the old version of auth config, one that would work with the deprecated Azure AD Graph.

**Comment by anupama2501** [comment]
Endpoint mappings:

```
Global
Graph Endpoint
old - https://graph.windows.net/
new - https://graph.microsoft.com/

Auth Endpoint
old - https://login.microsoftonline.com/{tenantID}/oauth2/authorize
new - https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/authorize

Token Endpoint
old - https://login.microsoftonline.com/{tenantID}/oauth2/token
new - https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/token

China
Graph Endpoint
old - https://graph.chinacloudapi.cn/
new - https://microsoftgraph.chinacloudapi.cn/

Auth Endpoint
old - https://login.partner.microsoftonline.cn/{tenantID}/oauth2/authorize
new - https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/authorize

Token Endpoint
old - https://login.partner.microsoftonline.cn/{tenantID}/oauth2/token
new - https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/token

Endpoint (login endpoint)
old - https://login.chinacloudapi.cn/
new - https://login.partner.microsoftonline.cn/
```

**Comment by starbuckscoffee** [comment]
I tried Rancher v.2.6.7-rc9 today, and I could not enable Azure AD.
Error Message on Rancher UI
"server error while authenticating: missing required permissions from Microsoft Graph: need Group.Read.All, User.Read.All"
---FYI---
  I checked these permission(Group.Read.All, User.Read.All) from Azure Portal(app registration), then I confirmed they ware Granted.

**Comment by maxsokolovsky** [comment]
@starbuckscoffee, did you upgrade or start with that Rancher version? Are the permissions of type Application or Delegated in the Azure portal?

**Comment by starbuckscoffee** [comment]
@maxsokolovsky 

>did you upgrade or start with that Rancher version?

Yes, I upgraded Rancher from 2.6.6 to 2.6.7 because it seems like Rancher ver 2.6.6 does not support OAuth Authrization Endpoint(V2) yet. 
FYI: With 2.6.6, I tried both OAuth(V1) and OAuth(V2), but Rancher caused error for both versions.
I upgrade Rancher by following your document, it seems like Rancher(ver 2.6.7-rc9) supports OAuth(V2), but it could not confirm these permissions(Microsoft Graph: need Group.Read.All, User.Read.All).

>"Are the permissions of type Application or Delegated in the Azure portal?

YES, type=Application, and I delegated these 7  permission names
** Directory.AccessAsUser.All
**Directory.Read.All
**Directory.Write.Restricted
**Group.Read.All
**User.Read
**User.Read.All
**User.ReadBasic.All

**Comment by maxsokolovsky** [comment]
@starbuckscoffee, did you use a custom endpoint or did you use Standard?

**Comment by starbuckscoffee** [comment]
@maxsokolovsky 
I used CUSTOM.
According to the link below:
https://www.rancher.co.jp/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/#6-configure-azure-ad-in-rancher
I suppose Rancher expects CUSTOM instead of STANDARD because STANDARD allows me to fill in 3 fields, tenantID, ApplicationID, ApplicationSecret.

Should I try STANDARD?

**Comment by starbuckscoffee** [comment]
@maxsokolovsky 

I tried STANDARD by filling following 3 fields.
* tenant ID
* Application ID
* Application Secret

>ERROR Message 
>server error while authenticating: missing required permissions from Microsoft Graph: need Group.Read.All, User.Read.All

**Comment by maxsokolovsky** [comment]
@starbuckscoffee, custom endpoints are not fully supported at the moment, just FYI.
But it's odd that Standard does not work. Standard is for the Global cloud, one accessible via portal.azure.com.
Could you share a screenshot of the permissions view for your app registration?

**Comment by starbuckscoffee** [comment]
Here it is...

![image](https://user-images.githubusercontent.com/5625960/184996981-2c3eb7a6-98f8-408b-8739-db90a5b731ce.png)

**Comment by starbuckscoffee** [comment]
By the way,  when I tried to enable Azure AD, I have to type my Sing-In ID(my e-mail address used for AAD login).
Is it correct? 

![image](https://user-images.githubusercontent.com/5625960/185000206-fdb2cd7d-b4d0-44e5-98da-d2637487b276.png)

**Comment by anupama2501** [comment]
Hi @starbuckscoffee was the azure account in China cloud? If so, can you try with China end points?

**Comment by starbuckscoffee** [comment]
@anupama2501 
>was the azure account in China cloud?
No, my account is Standard Public Cloud (Japan)

**Comment by anupama2501** [comment]
OK. thanks for the info @starbuckscoffee . The permissions you have in your app are of the type`Delegated`, they have to be `Application` pemissions.

**Comment by starbuckscoffee** [comment]
@anupama2501 
Many Thanks!!   I could enable Azure AD login from Rancher now!!
![image](https://user-images.githubusercontent.com/5625960/185242682-93c83b97-cd17-40f9-a34a-fbaf99fa02c0.png)

**Comment by anupama2501** [comment]
Closing the issue as the related release notes have been updated.
