### ISSUE TITLE
RKE2 cluster creation on Azure

### ISSUE THREAD

**Issue by gusraggio** [rancher/rancher#38159]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc1
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: RKE2 1.23.7
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Azure RKE2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin User.

   
**Describe the bug**

After the creation, a default 1 node RKE2 on azure, the following message appears bellow the cluster on the cluster management screen:
Waiting for viable init node

<br class="Apple-interchange-newline">

**To Reproduce**
 
Create a RKE2 on azure with the default values.

**Result**
Message: Waiting for viable init node
Nothing on Azure.
**Expected Result**

A new cluster
**Screenshots**

![image](https://user-images.githubusercontent.com/172923/176879966-065e094a-106a-4146-b4b9-01653e35e86c.png)

**Additional context**

**Comment by gusraggio** [comment]
[docker.log](https://github.com/rancher/rancher/files/9027757/docker.log)

**Comment by bashofmann** [comment]
I think the problem is, that there is a misconfiguration, like referencing a resource in the wrong region. But the actual error message is nearly impossible to see:

Rancher creates a Machine. Then it tries to create the Azure VM. The creation fails with an error message. Rancher directly deletes the Machine and creates a new one. The actual error is not visible in the UI, or only visible for a split second.

You can see this in this recording, at the end (00:50) you see the actual error message shortly:

https://user-images.githubusercontent.com/243056/176967549-7770c212-9880-4f30-891d-9f59545face2.mov
