### ISSUE TITLE
Nutanix Node Driver clashing with existing Nutanix Node Driver after Rancher Upgrade to 2.6.4+

### ISSUE THREAD

**Issue by hornet83** [rancher/rancher#38185]
Hi,

we were preparing to upgrade our Clusters to Rancher 2.6.4+ but are having the following issue.
We currently use Nutanix AHV with a modified Nutanix Node Driver that was implemented over 2 years ago. Now with the official support from Nutanix the node driver gets added automatically in a "deactivated" state, both drivers are using the same name though as shown in the screenshot.

This means that we can still scale our clusters, but we can't update the node templates anymore as they won't load (also shown in one of the screenshots). There is a workaround to delete the new node driver, then deactivate our node driver and re-activate it, after that we can modify and clone the node templates again.

The next issue is that during a Rancher pod restart or any upgrade etc, the new driver gets loaded again.. so we end up with broken node templates.

Is it possible to add a check to make sure drivers dont get added if a driver with the same name already exists?
Or a flag for the rancher options not to load specific drivers?

<img width="1423" alt="Screenshot 2022-07-01 at 2 59 05 PM" src="https://user-images.githubusercontent.com/31092498/177170375-21cdda94-3743-40f3-a3c2-deb648bb3dd5.png">

<img width="1417" alt="Screenshot 2022-07-01 at 7 32 25 AM" src="https://user-images.githubusercontent.com/31092498/177183630-0d936575-5b66-428b-8bbc-509f8438ab68.png">

Thanks,
Stefan

**Comment by ctrox** [comment]
We experienced pretty much the exact same issue. We also had our own node driver `nutanix` installed already and noticed that Rancher would simply update it (since in our case the NodeDriver object had the exact same name `nutanix`). Looking at the driver install code, it looks like Rancher will simply call [`Update` on the `NodeDriver` object](https://github.com/rancher/rancher/blob/release/v2.6/pkg/data/management/machinedriver_data.go#L193) if it finds an existing object with different fields. This meant rancher downloaded the driver from [this URL](https://github.com/rancher/rancher/blob/release/v2.6/pkg/data/management/machinedriver_data.go#L135) instead of our own version, which in turn broke lots of things as the new node driver had different fields, so our existing Cloud Credentials etc. did not match up anymore.

Sadly the inclusion of the new nutanix node driver was mentioned nowhere in the [release notes of v2.6.4](https://github.com/rancher/rancher/releases/tag/v2.6.4), so we we're not able to anticipate this. We were able to work around the issue temporarily by simply building rancher with the `addMachineDriver(NutanixDriver...` call commented out.

But as @hornet83 already mentioned, a preferred solution would be that we could configure which drivers get installed or that rancher would not blindly update existing drivers.
