### ISSUE TITLE
[Cattle] Enhancement : API for authentication configuration

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3832]
Create a API  `POST /v1/githubconfig` that a client can use to configure authentication.

The POST body will contain the following information
```json
{ 
    "type": "githubConfig",
    "enabled": true,
    "clientId": "1234556",
    "clientSecret": "123456",
    "allowUsers": ["username1","username2"],
    "allowOrganizations": ["org1","org2"]
}
```

This is a subtask of #62

**Comment by lesaux** [comment]
This sort of works, but I can't seem to be able to configure allowedIdentities. My github user doesn't seem to get access to the default stack. Not sure what I am doing wrong.

**Comment by vincent99** [comment]
@lesaux I'm not sure why this issues was created because the API was there then.. Everything the UI does is 100% driven by the API.  http://docs.rancher.com/rancher/latest/en/api/access-control/

`allowedIdentities` (and `accessMode`) controls what accounts have access to *login* to Rancher.  Once you can login, each Environment has a list of identities that are members with access to it.  That controls what Environments you see (I think you meant Environment, not Stack).  If you are an admin (and you are if you're the one that turned on access control) then you can also manage Environments that you're not a member of in the Environments -> Manage Environments menu.

Also to further confuse thing, "Environment" in the UI is `project` in the API, and "Stack" in the UI is `environment` in the API.

**Comment by lesaux** [comment]
I am posting the following to `v1/githubconfig` with curl.

{ 
    "type": "githubConfig",
    "enabled": true,
    "clientId": "1234556",
    "clientSecret": "123456",
    "allowUsers": ["username1","username2"],
    "allowOrganizations": ["org1"]
}

`clientId` and `clientSecret` are from github Oauth for `org1`, of which `username1` and `username2` are members. I am doing this on a fresh install, and no api keys have been created yet.

Once posted to the API, github auth is enabled and working fine, however I am limited to a new environment called `username1_env`. In "Manage environments", I don't see the "Default" and "System HA" environments - I only see the `username1_env` environment.

I tried specifying the different `accessModes` too, but even setting it to `unrestricted` didn't help.

Done through the GUI, everything works just fine. In that case I see the `allowedIdentities` field in the API which I though I might be missing.

**Comment by deniseschannon** [comment]
http://docs.rancher.com/rancher/v1.2/en/api/access-control/
