### ISSUE TITLE
Validate logging-operator 3.17.7

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#38322]
New version 3.17.7, updated from 3.17.4

**Comment by gboriso** [comment]
FYI customer Absa has requested this and we would expect to have it in v2.6.7 if possible as they have other crucial fixes also which aim that release. There is an internal reference open - SURE-4973.

**Comment by ronhorton** [comment]
testing 3.17.17 in `v2.6.7-rc3` opensuse leap 15.4
logging app is stuck in pending upgrade due to image pull back for the logging 3.17.17 pod
<img width="1392" alt="2022-07-26_18-17-56" src="https://user-images.githubusercontent.com/89212856/181122129-f02ad5d6-884d-4d2b-ba96-bf5db19f6eb3.png">
<img width="1362" alt="2022-07-26_18-18-17" src="https://user-images.githubusercontent.com/89212856/181122140-2dd1fe31-5243-4a23-9321-76278407a831.png">

**Comment by superseb** [comment]
@ronhorton this can be retested, the image was added in https://github.com/rancher/image-mirror/pull/267. (Dont have access to Zube to move the card)

**Comment by ronhorton** [comment]
**Pass** Logging `100.1.3+3.17.7` in Rancher `v2.6.7-rc5`
1. Fresh install
2. install and upgrade
3. end to end testing
