### ISSUE TITLE
CIS Benchmark app is trying to use image rancher/cis-operator:v1.0.8 but v1.0.9 is listed in rancher-images.txt v2.6.7-rc3

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#38357]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc3
- Installation option: Helm chart Airgap HA
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: No proxy, valid certificates

**Information about the Cluster**
- Kubernetes version: `v1.20.15-rancher2-1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?: Custom RKE1

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When installing the CIS Benchmark app v2.0.4 the chart has the cis-operator v1.0.8 but rancher-images.txt lists `rancher/cis-operator:v1.0.9`

This prevents the chart to install correctly with the default values.

**To Reproduce**
- Airgap Rancher install
- Downstream cluster RKE1
- Navigate to Cluster -> Apps -> Charts
- Click over CIS Benchmark and install with the default values.

**Result**

App is installed but the deployment is showing ImagePullBackOff errors in the `cis-operator` deployment in the `cis-operator-system` namespace

**Expected Result**
App and its deployments are active and functional in the downstream cluster. No ImagePullBackOff errors.

**Comment by PennyScissors** [comment]
What you are seeing here is the intended behavior. Rancher v2.6.7-rcX will generate a rancher-images.txt with the v1.0.9 operator version because that's the latest version we have in dev-v2.6 currently for that Rancher version and the image exporter only checks the latest version of this chart for images. To get the v1.0.8 operator version you need to start with a Rancher v2.6.6 setup which should have the previously released CIS benchmark version with that operator version in its rancher-images.txt. In an airgap setup the user needs to upgrade Rancher to get the new charts/images that were bundled with the new Rancher version, so realistically they would have an older Rancher version and the old operator version in their registry before the upgrade.

**Comment by izaac** [comment]
@PennyScissors if there's a new chart version in dev-2.6 wouldn't that version be available too as an install option in Rancher v2.6.7-rcX ? 

I will do another round of testing as the non-Airgap lists a CIS chart that use the v1.0.9, not sure why that version wasn't listed on the Airgap.

**Comment by PennyScissors** [comment]
@izaac Yes, but only the images of the latest version of the chart will be in the rancher-images.txt file of the latest Rancher RC since that's what is in dev-v2.6 at the time the Rancher RC is built and the rancher-images.txt file is generated.

**Comment by izaac** [comment]
Rancher version: `v2.6.7-rc5` 
rancher-cis-benchmark:2.0.5-rc6

I was able to install this chart version of CIS in the latest RC this version makes use of the `cis-operator:v1.0.9` image. No need to load any images from previous Rancher versions.
