### ISSUE TITLE
[BUG] Backup/Restore - Service account of a csp-adapter should not be restored on a migrated cluster 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38365]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.6.7-rc3`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `EKS`, `v1.22`
- Proxy/Cert Details: `Self-signed`

**Describe the bug**
While creating a backup the deployment for csp-adapter is not backed up. as a result the csp-adapter deployment is not restored when we migrate rancher to a new cluster on a restore.

**To Reproduce**
1. Create an eks cluster and install rancher on the eks cluster by following the docs https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/amazon-eks/
2. Create the required OIDC role and install csp-adapter on the eks cluster:
```
helm install rancher-csp-adapter rancher-dev/rancher-csp-adapter --namespace cattle-csp-adapter-system --set aws.enabled=true --set-string aws.accountNumber=$MY_ACC_NUM --set aws.roleName=$MY_ROLE_NAME --create-namespace
```
3. From the local cluster, navigate to apps & market place >> install rancher-backup charts 
4. From Rancher backups >> create a rancher backup and verify its saved in the s3 bucket
5. Create a new eks cluster and deleted the node groups and nodes of the eks cluster created in step1.
6. Follow the steps outlined in the docs https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/
7. After installing rancher, navigate to the local cluster >> deployments 

**Result**
service account for csp-adapter is restored

**Expected Result**
expected the csp-adapter service account not to be restored.

**Comment by MbolotSuse** [comment]
Part one of the validation template:

The following is a comprehensive list of csp-adapter resources that should be restored by the operator:
| Resource Kind | Resource Version/API Group | Resource Name |  Namespace | Source | 
|---------------------|-----------------------------------------|-----------------------|------------------|------------|
| ServiceAccount | v1 | rancher-csp-adapter | cattle-csp-adapter-system | helm chart |
| ClusterRole | rbac.authorization.k8s.io/v1 | rancher-csp-adapter-cluster-role | None (cluster scoped) | helm chart |
| ClusterRoleBinding | rbac.authorization.k8s.io/v1 | rancher-csp-adapter-crb | None (cluster scoped) | helm chart |
| Role | rbac.authorization.k8s.io/v1 | rancher-csp-adapter-role | cattle-csp-adapter-system | helm chart |
| RoleBinding | rbac.authorization.k8s.io/v1 | rancher-csp-adapter-binding | cattle-csp-adapter-system | helm chart |
| Deployment | apps/v1 | rancher-csp-adapter | cattle-csp-adapter-system | helm chart |
| Secret | v1 | csp-adapter-cache | cattle-csp-adapter-system | created by the deployment |

In addition, the csp adapter also creates a configmap (in the cattle-csp-adapter-system namespace) and a RancherUserNotification. These resources do not need to be restored on backup - the adapter is configured to handle their absence and generate new resources as it runs each 30 seconds.

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

The csp adapter is installed in the cattle-csp-adapter-system namespace. Since this namespace is prefixed with `cattle-` this lead to several of the adapter's resources being included in the backup-restore process.

This can interfere with operation of the adapter on a restored cluster, particularly since all of the resources are not restored.

## What was fixed, or what change have occurred

The default rancher resource set provided by the backup-restore operator has been modified to exclude csp-adapter resources, specifically the ones enumerated in the above comment https://github.com/rancher/rancher/issues/38365#issuecomment-1191965849 .

## Areas or cases that should be tested
- Backups of the rancher-resource-set, to ensure that none of the resources enumerated above are present in a restored setup.
- Fresh installation of the csp adapter after a restore- this should occur normally (excepting the 1 hour wait period) even if there is an active out-of-compliance banner (this should not be transferred but should be recreated by the adapter after re-install). This should be tested without an active banner and with an active banner - in either case the adapter should install successfully and be able to manage the state of compliance (this can be tested by adding/removing nodes, checking the supportconfig, etc.).

## What areas could experience regressions
- Rancher backup operations. Since modifications were made to the current rancher restore set, care should be taken to ensure that resources which were being backed up before are still being backed up now.

## Are the repro steps accurate/minimal?
Yes - they are included here for convenience.

1. Deploy rancher and the csp adapter according to the [docs](https://staging.rancher.com/docs/rancher/v2.6/en/installation/cloud-marketplace/aws/) .
2. Install the rancher backup operator through the UI. Use a local storage volume for the default type (on aws -gp2).
3. Take a backup of rancher. Record the name of the backup tar.gz.
4. Identify the name of the backup-restore operator pod (e.x through `k get pods -n cattle-resources-system`).
5. Using the following command, copy to the backup from the backup/restore pod to your local:
```bash
k exec $BACKUP_POD -n cattle-resources-system -- cat /var/lib/backups/$BACKUP_NAME  >> test.tar.gz
```
6. Extract the backup, using the below command (recommended to do this in an empty directory):
```bash
tar -xf test.tar.gz
```
7. Confirm that the resources are (or are not) included in the backup.

**Comment by anupama2501** [comment]
Rancher backup/restore chart version v2.1.3-rc6 to be used for qa validation.

**Comment by anupama2501** [comment]
Verified on v2.6.7-rc5 and backup/restore operator - `2.1.3-rc6`

1. Created 2 rancher servers as follows:
2. Create an eks cluster and install rancher on the eks cluster by following the docs https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/amazon-eks/
3. Create the required OIDC role and install csp-adapter on the eks cluster:
4. helm install rancher-csp-adapter rancher-dev/rancher-csp-adapter --namespace cattle-csp-adapter-system --set aws.enabled=true --set-string aws.accountNumber=$MY_ACC_NUM --set aws.roleName=$MY_ROLE_NAME --create-namespace
5. From the local cluster, navigate to apps & market place >> install rancher-backup charts
6. From Rancher backups >> create a rancher backup and verify its saved in the s3 bucket
7. Create a new eks cluster and deleted the node groups and nodes of the eks cluster created in step1.
8. Follow the steps outlined in the docs https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/
9. Verified the migration was successful and the values outlined [here](https://github.com/rancher/rancher/issues/38365#issuecomment-1191965849) were not backed up:

Initial rancher server has all clusters in compliance - Pass
Second rancher server has clusters out of compliance - Pass
