### ISSUE TITLE
[Cattle] Support Read Only Containers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3837]
docker/docker#10093

**Comment by ecliptik** [comment]
Can we re-open this as an option when deploying stacks in Cattle since docker/docker#10093 was closed and is now supported in Docker via the `--read-only` flag?

Having the option of making the rootfs of a running container with this feature would be a great addition to Rancher and additional benefits of immutable infrastructure.

See https://diogomonica.com/2016/11/19/increasing-attacker-cost-using-immutable-infrastructure/ as an example.

**Comment by robertofpaf** [comment]
+1 for reopening this.
