### ISSUE TITLE
Make resource lifecycles consistent

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#384]
At present our different kinds of resources have subtly different lifecycles for no good reason.  We should go through all the types and make everything consistent, or have a good reason for exceptions.  Proposed guidelines:
- Resources should not have an `active` vs `inactive` state unless there is a good reason.
  - For `host`, the scheduler uses this to decide which ones are eligible
  - For `apiKey`, keys can be deactivated as a test/safety net to see if you will break your clients by deleting that key.
  - Many other types have an `inactive` with no clear need (#361, #363).
  - Or have an `inactive` but no `activate` or `deactivate` action (#394).
- Resources that are asynchronously `201 created`/`202 accepted` should go into `state=error` if they fail to successfully create.
  - `state=error`, `transitioning=error`, `transitioningMessage=The reason why it failed`
  - `machine` now does this.
  - But deploying a bad `container` does not (#282).
  - Resouces in `state=error` should not be able to be restored, because they were never really created.  (#1050)
- Users should be able to delete a resource at any time.
  - A `DELETE` request should be accepted from any state (except `removing`, `purging` and `purged`) for any resource and move the resource to `state=removed`.
  - Currently some types allow this and some don't (#349, #275, #220)
- No data should be irrevocably lost at `state=removed`.
  - All resources should have a `restore` action to move from `state=removed` back to a relevant state (e.g. `inactive` or `stopped`).
  - All resources should have a `purge` action to move from `state=removed` to `state=purged`.
  - `machine`s are currently deleting VMs at `state=removed` (#337).  
    - This might be an exception because it's an external resource costing actual money to a third party, but should probably be an exception to the auto purge policy, not the lifecycle.
- Once a resource is in `state=purged`, all sensitive (e.g. `credential.secretValue`, SSL keys) and/or significant disk space consuming things (volumes, containers, etc) should be actually deleted.
  - Small, non-sensitive database entries may continue to exist ("the database only scales up™")
  - No transitions are possible out of `state=purged`.
  - `state=removed` resources get automatically `purge`d after a configurable amount of time.
  - Relevant child resources should be purged as well, like hosts & machines when purging a project (#340).
- Resources in `state=purged` should never be returned in the API.
  - This is broken for `?include=` (#297, #218).
- Resources in `state=removed` should not normally be returned in the API.
  - There should be a configurable option, disabled by default, to show resources that are in `state=removed` to only admin users or to all users.
  - This allows providers to use the `deleted` vs `purged` states to enforce a data-retention policy.

**Comment by alena1108** [comment]
>>No data should be irrevocably lost at
What if object O2 was removed as a part of O1 removal? Should restore for O1 handle restore for O2?

**Comment by vincent99** [comment]
> What if object O2 was removed as a part of O1 removal? Should restore for O1 handle restore for O2?

Since removed resources would become invisible to normal users, I think it's fine if the restore action only changes the given resource and does not cascade to children.

**Comment by vincent99** [comment]
Currently you can get a resource by id (`/v1/things/:id`) even after the resource is purged.  (This is a feature because it allows a user to save and poll the `links.self` link even if it no longer exists, and provides removed date and other info that a 404 would not).

For requests from a user who cannot see `state=purged` resources, this will leak information about whether the actual state is `removed` vs `purged`.  This should be addressed somehow, e.g. by having the response "lie" and say `state=removed` for purged resources for such users.  The `updated` date may leak info too, if so it should be === removed date.

**Comment by ibuildthecloud** [comment]
I agree to all of the above.  After we did the auth changes awhile back the number of types in the core API shrunk quite a bit.  I think it is reasonable to go through and review the lifecycle of each resource.

Regarding delete from any state.  It's harder to implement than just adding a transition.  There needs to be a framework change.  The problem is that most resource logically have an up and down action.  For example start and stop.  when you delete from and up state you really want to bring down and then remove.  You don't just want to remove.  Remove usually does nothin except set a timestamp.  In order to not have to duplicated logic I think a framework change could be made such that if you delete in an up state it knows how to bring it down first.

**Comment by vincent99** [comment]
Excellent, @will-chan and I will hunt you down on Wednesday to go through types as a first-step.

I could be convinced to not have delete from any state, but it would be nice to select several resources, click delete, see one "are you sure" confirm, and then have them be gone.  (Also the api-spec has no way to say it delete isn't availble per-individual-resource)

**Comment by alena1108** [comment]
@ibuildthecloud @vincent99 @will-chan  Darren, have a question about removal process. You said "Remove usually does nothing except set a timestamp", but I can think of the cases when mapped objects have to be updated with removed flag as well (service.remove triggers service's instances destroy; lb.remove - targets maps destroy). Otherwise unremoved mapped objects will result referencing removed entries, and displayed to an end user. But I also see downsides of this approach - restore logic becomes more complicated. What would be your suggestion on how we should handle it?

**Comment by cjellick** [comment]
We met on 4/20 to discuss this issue. Here are the notes from that meeting:

##### Resources should not have an active vs inactive state unless there is a good reason.
* get rid of states that dont make sense
* Follow up meeting to discuss concrete states and resources
  
##### Resources that are asynchronously 201 created/202 accepted should go into state=error if they fail to successfully create.
* some operation and the operations fails, just use transitioning message
* for instance, change the startOnCreate + error == remove logic
* Services are very weird. Some or all containers can fail.
  * exponential back off
  * cleanup failed containers at beginning of loop, not end. to keep 1 interval of failed around
  * If x out 5 fail to start, stay in activating for ever
* Generally, we should do exponential process.
  * Make configurable per process type?
  * exponential backoff based off of processType (“service.activate”)
  * next_run field in process_instance table

##### Users should be able to delete a resource at any time.
* Agreed. Implementation will move through the necessary processes to get to removed.

##### Why do resources have active and inactive?
* Because create is just putting in the database.

##### No data should be irrevocably lost at state=removed.
* For container, commit the image so that it can be restored from there. We really delete  the container at the time of remove. When purge container happens, we delete the archive. or do we rename it? We’ll decide on implementation later
  * docker container gets remove on remove
* Aside from containers, most everything is metadata, so do we need purge?
  * Basic flow is when you delete, it goes straight to removed.
  * Where needed, we stop at “archived” before going to removed.
  * Only resources with the archive process have a restore process.

##### Once a resource is in state=purged, all sensitive (e.g. credential.secretValue, SSL keys) and/or significant disk space consuming things (volumes, containers, etc) should be actually deleted.
* Yes.
* Credentials, machines, certs, etc
* “removed” not “purged"
* May eventually need a pluggable HSM solution.
  *  Should look at Cloud HSM.

##### Resources in state=purged should never be returned in the API. & Resources in state=removed should not normally be returned in the API.
* Dont have purged anymore, so:
  * include shouldnt cause purged/removed to show up in list
  * get by id needs to still work
  * Showing removed for certain time:
    * On by default header to turn off
  * Document in the spec

And we'll have a follow up meeting to review all states of current resources and determine what needs removed/added/standardized

**Comment by vincent99** [comment]
One more... Once all the above stuff is done, remove the `create`, `update` and `remove` actions from the schema.  They should always be available via POST, PUT, and DELETE.

This will require coordination with the UI as I currently use their presence to show/hide actions since they are not always available.

**Comment by vincent99** [comment]
Most of this that's ever going to get done is in 2.0...
