### ISSUE TITLE
[RFE] Steve should support pagination with sorting and filtering

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher#38427]
This issue is part of a set of Steve performance enhancements for v2.7.x. https://github.com/rancher/dashboard/issues/5243

# Pagination
Instead of fetching all resources in the cluster or in a namespace, the UI should be able to fetch and watch a single page of resources. The Steve API already supports a limit parameter for results, so the enhancement is to provide paginated results that are also sorted and filtered on the back end.

# Sorting

Currently the UI does all sorting client-side, usually after loading all resources of a certain type. To reduce memory consumption in the browser, the UI should only load the first page of resources for each list view up front. But to load only the first page without losing the ability to sort resources, Steve will need to be enhanced to support sorting.

This issue will be updated to list exactly which types of sorting will be needed for which resources.

# Filtering

Currently the UI does all filtering client-side, usually after loading all resources of a certain type. To reduce memory consumption in the browser, the UI should only load the first page of resources for each list view up front. But to load only the first page without losing the ability to sort resources, Steve will need to be enhanced to support filtering.

Currently, the UI supports search and filtering by resource name.

The following filters aren't needed purely to enhance performance in the UI, but we have also had requests to also support filtering by resource labels, annotations, API groups and API versions. SURE-4780

**Comment by cmurphy** [comment]
Some initial research notes:

* pagination and sorting

Kubernetes technically supports [pagination](https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks), and steve passed through pagination parameters directly to kubernetes, so steve also supports pagination. But it [does not implement sorting](https://github.com/kubernetes/kubernetes/issues/80602), so I guess this is basically useless for a dashboard.

* filtering

Kubernetes supports a limited kind of filtering. You can [filter by labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) and by a small set of k8s-defined [field selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/), which varies by resource but always includes names. There is [no support for filtering by generic fields](https://github.com/kubernetes/kubernetes/issues/1362). Filtering by annotation is specifically an anti-pattern, because that is what labels are for. So to fulfill

> Currently, the UI supports search and filtering by resource name.

This can be accomplished in steve with, for example,

```
curl -u $TOKEN https://<rancher>/v1/pods/default?fieldSelector=metadata.name=test
```

For 

> we have also had requests to also support filtering by resource labels

this can be done with

```
curl -u $TOKEN https://<rancher>/v1/pods/default?labelSelector=run=test
```

For

> annotations

this isn't supported in kubernetes currently.

For

>  API groups and API versions

I am curious about the use case for this. Most tabs in the UI are grouped by resource (Deployments, Configmaps, etc), and API groups and versions are part of the resource as a whole. E.g., all Deployments have the API group and version `apps/v1`. Why do these need to be sorted?

**Comment by Sean-McQ** [comment]
> This issue will be updated to list exactly which types of sorting will be needed for which resources.

What we'd really like to see for sorting in order to be useful on the frontend would be need to be at least basic asc/desc sorting on arbitrary fields for a resource. Ideally we'd like to the ability for a primary and secondary sort field in order to add grouping to paginated results (namespace and project grouping are two examples that immediately come to mind).

**Comment by gaktive** [comment]
@samjustus Internal reference: https://jira.suse.com/browse/SURE-5387. Let me know if that's the formatting you want before porting over other tickets.

**Comment by samjustus** [comment]
@gaktive  perfect... formatting isnt so important to me to be honest its just for Product to have a trackable unit.

**Comment by samjustus** [comment]
LOE: L

**Comment by richard-cox** [comment]
Referencing SURE-5698 (contains features still required before adoption)

**Comment by cmurphy** [comment]
Steve changes are merged in rancher with integration tests, assigning @Sean-McQ to dev-validate at your convenience, please reassign if needed

**Comment by richard-cox** [comment]
I'm not quite sure we can treat this issue as done. As in, the UI doesn't quite have everything required to implement server side pagination (remaining items described in SURE-5698).

The work done for 2.7 Q1 is great and the UI team (well volunteered @Sean-McQ) can double check the gaps between it and items described in SURE-5698 + child issues.

**Comment by cmurphy** [comment]
@richard-cox you're right, the feature is not complete. I started making separate issues https://github.com/rancher/rancher/issues/40141 and https://github.com/rancher/rancher/issues/40140 to cover the remaining asks in SURE-5698. For the other issues, I'm hoping we can flesh them out a little bit before committing to them.

**Comment by cmurphy** [comment]
I should also mention that we added some general usage docs in steve https://github.com/rancher/steve#readme and some auto-generated API examples in rancher https://github.com/rancher/rancher/tree/release/v2.7/tests/v2/integration/steveapi#readme

**Comment by richard-cox** [comment]
For whoever makes it down this far, in `2.7.2` the UI does not have enough functionality to cover the feature as described in the description. For delta please see https://github.com/rancher/dashboard/issues/8527#issuecomment-1484891769

**Comment by richard-cox** [comment]
After discussing with Neil, for clarity on feature (see https://github.com/rancher/rancher/issues/38427#issuecomment-1495598967) am re-opening this issue. There's been work completed in the 2.7.2 timeline, but the feature isn't complete.

**Comment by samjustus** [comment]
@richard-cox @nwmac it was discussed multiple times that we would close for now because the work in this ticket has been committed to the branch. We can reopen it if the **specific** work in these commit isn't validated by your team after the [Q2 work](https://github.com/rancher/rancher/issues/38427#issuecomment-1397416108) is completed.

**Comment by cmurphy** [comment]
Not adding a release note since this isn't user-facing and isn't in use yet, we can release note it when the feature is fully implemented.
