### ISSUE TITLE
[RFE] Steve: Improve the performance of resource fetch requests

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#38468]
Ahead of implementing server-side pagination in Steve, it would be good to improve the performance of get requests to Steve for k8s resources, particularly when the number of resources is large. Perhaps some cacheing can be added.

On a system with 3700 deployments, the get request to /v1/apps.deployments takes a minimum of 16 seconds. 13.5 seconds is spent waiting before any content is sent - which only takes 2.5 seconds.

Ideally a request like this should complete in under 5 seconds.

**Comment by cbron** [comment]
The only way I can think of this working is to add a cache in between steve and etcd, and that sounds like a nightmare to me. Caching bugs would be a serious problem. Also there already is a cache on top of listers in k8s. We can look into if etcd and steve have any sort of performance differences but I would guess not. The real way to solve this is to scale etcd, or use a different database.

**Comment by richard-cox** [comment]
@cbron, @aalves08 can share some initial findings on the old ui and how it performs with similar amounts of deployments (3.7k all in the same project).  There's some regressions when comparing steve to norman response times. I know norman did a number of 'magic' things that we don't want to reproduce in the more native steve, but it would be good to understand why there's a big difference.

**Comment by aalves08** [comment]
@cbron 
_2.6.7_
doing all the requests for workloads, about 3700 items, (uses K8s api) takes on average 21s.

_Old UI_
doing all the requests for workloads, about 3700 items, (uses norman V3 api) takes on average 7s.

FYI @richard-cox 

That has a big impact on FCP and LCP times for the interface.

**Comment by cbron** [comment]
Can you add details on which items you are requesting and how ? My guess it that Norman is scoping/filtering more by default (ie like a project level) and so you are actually just requesting fewer objects.

**Comment by richard-cox** [comment]
The resources are all in a single project, so the numbers Alex mentioned are the one's in the http responses. 

@aalves08 Can you update with the url's for the requests? From memory they're deployments

**Comment by aalves08** [comment]
**2.6.7**
_resources loaded for the table on workload list view_
https://localhost:8005/k8s/clusters/c-wpfct/v1/batch.jobs - 4 items
https://localhost:8005/k8s/clusters/c-wpfct/v1/apps.deployments - 3700 items
https://localhost:8005/k8s/clusters/c-wpfct/v1/batch.cronjobs - empty list
https://localhost:8005/k8s/clusters/c-wpfct/v1/apps.daemonsets - 4 items
https://localhost:8005/k8s/clusters/c-wpfct/v1/apps.statefulsets - empty list
https://localhost:8005/k8s/clusters/c-wpfct/v1/apps.replicasets - 3700 items
https://localhost:8005/k8s/clusters/c-wpfct/v1/replicationcontrollers - empty list

_secondary resources needed for that view_
https://localhost:8005/k8s/clusters/c-wpfct/v1/nodes - 40 items
https://localhost:8005/k8s/clusters/c-wpfct/v1/pods - 2600 items

**Old UI**
_resources loaded for the workload list view (probably some of these are secondary, in order to provide extra detail)_
https://10.86.2.89/v3/projects/c-wpfct:p-sf6sx/schema - 292 items
https://10.86.2.89/v3/cluster/c-wpfct/namespaces?limit=-1&sort=name - 1014 items
https://10.86.2.89/v3/cluster/c-wpfct/storageclasses?limit=-1&sort=name - 1 item
https://10.86.2.89/v3/cluster/c-wpfct/persistentvolumes?limit=-1&sort=name - empty list
https://10.86.2.89/v3/project/c-wpfct:p-sf6sx/pods?limit=-1&sort=name - 2600 items
https://10.86.2.89/v3/project/c-wpfct:p-sf6sx/workloads?limit=-1&sort=name - 3700 items
https://10.86.2.89/v3/project/c-wpfct:p-sf6sx/secrets?limit=-1&sort=name - empty list
https://10.86.2.89/v3/project/c-wpfct:p-sf6sx/services?limit=-1&sort=name - empty list
https://10.86.2.89/v3/project/c-wpfct:p-sf6sx/configmaps?limit=-1&sort=name - 1 item
https://10.86.2.89/v3/project/c-wpfct:p-sf6sx/namespacedsecrets?limit=-1&sort=name - 1 item
https://10.86.2.89/v3/project/c-wpfct:p-sf6sx/persistentvolumeclaims?limit=-1&sort=name - empty list

FYI @cbron @richard-cox

**Comment by richard-cox** [comment]
So we're talking
Ember UI -  `v3/project/c-wpfct:p-sf6sx/workloads?limit=-1&sort=name` - 3700 items in response - 7 seconds
Dashboard UI - `k8s/clusters/c-wpfct/v1/apps.deployments` - 3700 items in response - 21 seconds

**Comment by cbron** [comment]
Thanks, that gives us something to go off of. Are all your deployments then in just 1 project ? Cause the second call isn't filtering by project.
Under the API both are still hitting the same etcd server and k8s listers, so I'm still guessing there is filtering going on with the Norman call that doesn't exist on Steve. Or something else entirely is going on. If that cluster is still up I'd be curious about timing a list of cluster level objects like namespaces or ClusterRoleBindings.

**Comment by catherineluse** [comment]
It looks like the above time difference was from a setup where all the workloads were in the same project. In that case it seems like a pretty direct comparison since Ember and Dashboard are getting the same number of resources for the Deployment list.

For contrast, I have a setup where there's 1,000 workloads distributed across 500 projects. In this case it confirms that Ember's ability to only show one project at a time also makes a big difference:

- Steve: Getting all deployments in the cluster (1,000 workloads, distributed equally across 500 projects)
	- endpoint: `/k8s/clusters/c-m-gnvvtdhl/v1/apps.deployments`
	- time: 30 seconds
- Norman: Getting all deployments in a single project (Only 2 workloads)
	- endpoint: `/v3/project/c-m-gnvvtdhl:test0/workloads?limit=-1&sort=name`
	- time: 1 second

For cluster-level resources, the comparisons are:

## Namespaces

- Norman:
  - Endpoint: `/v3/clusters/c-m-gnvvtdhl/namespaces`
  - Time: 5.1 seconds
- Steve:
  - Endpoint: `/k8s/clusters/c-m-gnvvtdhl/v1/namespaces`
  - Time: 11.4 seconds

## ClusterRoleBindings

- Steve:
  - Endpoint: `/k8s/clusters/c-m-gnvvtdhl/v1/rbac.authorization.k8s.io.clusterrolebindings`
  - Time: 18.5 seconds
- Norman:
  - Not applicable? Couldn't find an endpoint for ClusterRoleBindings for the Norman API.

**Comment by gaktive** [comment]
Internal reference: SURE-5399

**Comment by catherineluse** [comment]
> Slow retrieval of schemas.

I think when we fetch schemas, we get more info back than what we need. Of course the number of schemas varies based on how many schemas are installed, but it's often more than 1,000 schemas, many of which don't even represent Kubernetes resources.

For example, we get `monitoring.coreos.com.v1.podmonitor.spec.podMetricsEndpoints.basicAuth` as a schema. But the UI doesn't need that - we only need `monitoring.coreos.com.v1.podmonitor` to check if the user has permissions to see PodMonitors.

So I'm thinking if the backend returned only whole K8s resources instead of returning a separate schema for each subsection of a resource, that could make it a little faster.

**Comment by catherineluse** [comment]
For field omission, it's relatively easy for the UI to exclude fields due to this feature https://github.com/rancher/rancher/issues/36683 - so we'd just need to come up with a list of what to exclude.

**Comment by MbolotSuse** [comment]
> I think when we fetch schemas, we get more info back than what we need. Of course the number of schemas varies based on how many Helm chart apps are installed, but it's often more than 1,000 schemas, many of which don't even represent Kubernetes resources.

I think I've got an answer to what is going on here, but I'm not super confident on the solution yet. Basically, it seems that a lot of these schemas represent sub resources. For example, suppose I've got the following resource:

```
apiVersion: v1
kind: Namespace
metadata:
    name: test
```

Suppose for sake of discussion that there isn't any other fields that you can apply to the namespace. This will end up with two schemas - one for the `Namespace` type, and one for the `ObjbectMeta` type - which used in the namespace schema as the type for the `metadata` field. 

I think the original intention was that the schema would represent all complex types, just like an openapi schema. That way, clients could hit this endpoint to get a full mapping of the various api types offered by rancher. This idea is flawed in several ways (our management types don't seem to have any field definitions in the sources that steve looks at to assemble type information, verbs are attached here but the UI only needs them for a small minority of "schema" resources), but I think this was the idea.

I can change this to only report top level resources. This appears to significantly reduce the size of the schemas (on a fresh 2.7 install, it had ~1200 values in the current state and ~200 with my experimental changes). However, this endpoint will no longer be usable to read in all field definitions, meaning that there will be top level resources with fields that refer to structures not in the schema (in the above example, there would be no `ObjectMeta` schema, but the schema for namespace would still refer to an `ObjectMeta` object). As long as this is ok I should be able to make this change.

The perhaps safer alternative is to leave the schema as it currently is and add a new `v1/resourceSchemas` endpoint which does this, but I'd prefer not to add additional complexity to steve if I can avoid it. 

As far as testing with this change does, I did some "basic tests", outline below and didn't see unexpected behavior (there was an RKE2 prov issue, but I've seen that before):
- Provision an RKE2 cluster on digital ocean
- Provision an RKE cluster on digital ocean
- Add an auth provider (openldap)
- Add a group from the auth provider as a restricted admin. 
- Add a user from the auth provider as a cluster member to both clusters.
- Confirm that the user can use the shell functionality in both clusters. 

I'll try to get this in a PR ready state and we will see if it meets with our goals for the backend/schema functionality.

**Comment by catherineluse** [comment]
> This idea is flawed in several ways (our management types don't seem to have any field definitions in the sources that steve looks at to assemble type information, verbs are attached here but the UI only needs them for a small minority of "schema" resources)

Yes, that's basically what I found out a while ago when I attempted to use the schemas to generate API documentation. There's not quite enough information for it to be a useful reference, and to my knowledge the UI doesn't use the schemas for form validation or typing or anything like that. I'm 99 percent sure the UI only uses the top-level schemas for permissions checks and that's it. But I could be wrong, so will confirm with the team.

**Comment by catherineluse** [comment]
Per discussion with Neil on Nov. 3, it sounds like we should proceed with the reduction in schemas. The body of each schema can be minimal as well, since the UI only needs to check for its existence.

**Comment by samjustus** [comment]
#39567 
#39568

**Comment by samjustus** [comment]
invalid

**Comment by richard-cox** [comment]
Have the issues in the description and initial comments been resolved or spun out? If not we'll need to re-open this and the JIRA issue
