### ISSUE TITLE
[BUG] Taking multiple s3 etcd snapshots at once take more time to get activated

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38460]
**Rancher Server Setup**
- Rancher version: `v2.6-head 78017e6 `
- Installation option (Docker install/Helm Chart): `Docker install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: `v1.24.2+k3s1`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider 3 worker, 1 etcd , 1 cp

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) 
  - If custom, define the set of permissions: Admin
   
**Describe the bug**
When we take continuous s3 etcd snapshots, first snapshot gets to activating state quickly but the next etcd snapshot that are added to the queue stay in `creating` state close to 8 minutes even after the first snapshot goes into active state. This was not the case on v2.5.16

**To Reproduce**
1. Create a downstream cluster and set in advanced options >> snapshot to be saved as s3.
2. Once the cluster is running >> cluster management >> etcd snapshots >> Take 3 to 4 snapshots

**Result**
First snapshot transitions into activating state quickly but the consecutive snapshots in queue take more than 7 minutes after the initial snapshot goes into active state.

**Expected Result**
Not expected for snapshots to take 8 min

**Comment by jakefhyde** [comment]
This is actually by design, due to fixes related to the followings etcd snapshot issues 
- https://github.com/rancher/rancher/issues/34890
- https://github.com/rancher/rancher/issues/36209
- https://github.com/rancher/rancher/issues/36492
- https://github.com/rancher/rancher/issues/37639

AFAIK only one issue, https://github.com/rancher/rancher/issues/36038 was backported and in fact if you actually create the issues fast enough by rapidly clicking the `Snapshot Now` button, this happens:

![image](https://user-images.githubusercontent.com/33796120/181807039-ad58175b-a3ba-4a8b-ad78-9a456f538d8b.png)

The other benefits are that

1. There is currently no use case where a user would actually want multiple snapshots to be running at the same time, or right after each other. The only way would be if a user created a manual snapshot while another manual or recurring is running, in which case waiting is desired in order to not flood the downstream.
2. In the event that the upload to s3 takes on the order of minutes, this gives a chance for network traffic not to be as congested. 

The actual issue is a simple fix, but I wanted to clarify that it is functioning as intended and not a regression because it simply doesn't scale in `v2.5.16`.

**Comment by anupama2501** [comment]
closing based on the above comments.
