### ISSUE TITLE
Create new packaged helm repos to support terraform installations for multiple release versions

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#38509]
Terraform helm provider installations need packaged helm repos to download and install charts and since we have only one such repo https://charts.rancher.io/ it is not possible to support multiple released versions at the same time.
This is leading to charts missing in the packaged repo.
Ex issue: https://github.com/rancher/rancher/issues/37601 

To fix this, we need to create additional repos for each version.

SURE-5346

**Comment by stormqueen1990** [comment]
I did some testing in Rancher 2.5, 2.6, and 2.7. I noticed that for Rancher 2.5, the package repository points to the `master` branch of the rancher/charts repository and we cannot change it due to some incompatibility. However, for Rancher 2.6 and 2.7, it is possible to point to specific branches of rancher/charts, therefore allowing installation of specific charts releases.

For Rancher 2.6, I did the following test:
* Install Rancher.
* In the app repositories, create a new repository named `new-charts` pointing to rancher/charts branch `release-v2.7`.
* Create a Terraform template that installs a package version that exists _only_ in `release-v2.7`.
* Try to install from the `rancher-charts` repository (v2.6).
* Check that it fails as expected.
* Change the template to point to the `new-charts` repository.
* Try applying the template again and check that it succeeds as expected.

@mitulshah-suse since the Rancher documentation currently states that Rancher 2.5 is at end of maintenance, and this requirement works for more recent versions, do you think it would be alright to close this issue?

**Comment by MKlimuszka** [comment]
Closing due to the original reason for filing is no longer relevant. See the previous comment for more details.
