### ISSUE TITLE
Remove Deprecated setting kubeconfig-token-ttl-minutes

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#38535]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samjustus** [comment]
@Jono-SUSE-Rancher can you make a 2.8 milestone please?

**Comment by Jono-SUSE-Rancher** [comment]
> @Jono-SUSE-Rancher can you make a 2.8 milestone please?

I don't _understand_ your request, but by golly I'm in.

**Comment by KevinJoiner** [comment]
@Jono-SUSE-Rancher We are deprecating `kubeconfig-token-ttl-minutes` in this next release. This issue is to officially remove the setting in 2.8.0

**Comment by KevinJoiner** [comment]
This will also need a docs page update for 2.8

**Comment by JonCrowther** [comment]
# Validation

## Root Cause

The setting `kubeconfig-token-ttl-minutes` was set to be deprecated for 2.8.

## What was fixed, or what change has occurred

The `kubeconfig-token-ttl-minutes` setting has been removed. It can no longer be found in the Global Settings, and can't be set via command line option when building rancher. It has been replaced by the setting `kubeconfig-default-token-ttl-minutes`.

## Areas or cases that should be tested

Create a rancher instance and see that the `kubeconfig-token-ttl-minutes` option is not present in the global settings. 

## What areas could experience regressions

Possibly any tests revolving around kubeconfig tokens may break if they're checking a different value.

## Are the repro steps accurate/minimal?
Yes

**Comment by anupama2501** [comment]
Verified on v2.8-head `436f4de`, the setting `kubeconfig-token-ttl-minutes` is removed from global settings.


Re opening: 
On an upgrade from v2.7.6 >> v2.8-head `436f4de`, the setting `kubeconfig-token-ttl-minutes` is still listed from v3/settings page:


<img width="400" alt="2023-10-02_11-15-25" src="https://github.com/rancher/rancher/assets/38144301/f605b1ae-4337-49ea-8fdb-40a78c05b73d">

**Comment by gaktive** [comment]
As @JonCrowther indicated, there is UI impact here which is hitting late for 2.8.0. We'll assess how quickly this can be done but earlier warning about dashboard changes would be helpful going forward so we're not scrambling at the end.

**Comment by anupama2501** [comment]
Re opening for a few more validations once the UI is unblocked.

**Comment by JonCrowther** [comment]
# Release note

## Synopsis of issue
The setting `kubeconfig-token-ttl-minutes` has been deprecated.

## Resolution
The setting has been removed. For more info visit: https://ranchermanager.docs.rancher.com/v2.5/reference-guides/about-the-api/api-tokens#setting-ttl-on-kubeconfig-tokens

**Comment by anupama2501** [comment]
Verified on an upgrade from v2.7.8 >> v2.8-head `01127d8`

@JonCrowther This is not listed in the UI anymore but I still see this listed at <rancherURL>/v3/settings/kubeconfig-token-ttl-minutes and <rancherURL>/v1/management.cattle.io.settings

**Comment by anupama2501** [comment]
from offline conversation:
```
For 38535, I opened a dashboard ticket, but even if that gets fixed, the setting will be visible in v3/settings, but doesn't do anything. There isn't any method of cleaning up settings on an upgrade. If that's something we want to pursue it would be feature work for a future milestone
```

Created the linked ticket
