### ISSUE TITLE
[BUG]Cannot unassign (delete) a global role assignment to an Azure AD SSO group

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#38561]
SURE-3845

**Rancher Server Setup**
Rancher Cluster:
Rancher version: v2.6.2
Number of nodes: 2
Node OS version: Ubuntu 20.04

Other:
Underlying Infrastructure: AWS
Any 3rd party software installed on the nodes: no

**Describe the bug**
When customer attempt to unassign a global role assignment in the UI, the UI returns a message that the group assignment was deleted, but it still shows in the UI.

**To Reproduce**
I was able to reproduce this on rancher 2.6.2 using RKE2 deployed on digital ocean and the following steps:
1. Deploy Rancher.
2. Deploy an RKE2 cluster in digital ocean.
3. Integrate an auth provider (openldap).
4. Assign a group to restricted admin.
5. Wait for the RKE2 cluster to deploy.
6. Delete the RKE2 Node(s) manually in the digital ocean console.
7. Delete the global role binding. Observe the errors in the logs.

**Result**
Deletion of global role assignments not removing global role assignment.

**Expected Result**
A deletion in the UI should delete the global role assignment without having to manually remove the finalizer.

**Comment by MbolotSuse** [comment]
From a functionality perspective, this behavior is desired. For Global Roles that give permissions on downstream clusters (such as restricted admin), when default deletion is used the binding should not be removed until the permissions have been removed from the downstream cluster. In cases such as a disconnected cluster, this will mean that the overall binding is not removed until all clusters have "checked-in" so that the per-cluster permission can be removed.

However, we definitely want to give users more information on why the binding hasn't been removed yet (including which cluster(s) need permissions removed). This should be accomplished in the initial implementation of a status field for GRBs. We also need to reproduce/confirm this behavior for Global Roles which use the new `inheritedClusterRoles` field.

**Comment by samjustus** [comment]
blocked by https://github.com/rancher/rancher/issues/44668
