### ISSUE TITLE
[cli] Newest Rancher CLI version 2.6.7 contains no binaries

### ISSUE THREAD

**Issue by Tonur** [rancher/rancher#38624]
Hi Rancher team

I've been looking forward to a new release of the Rancher CLI tool, as I am hoping for a solution to this issue: #37574 

However when I went to retrieve the new version, it contained no binaries, as earlier versions had. 
This can be seen in this link: https://github.com/rancher/cli/releases/tag/v2.6.7
Where only the source code is available.
Is this because I have to build it myself?

I can see that it was @jakefhyde that created the release, so the question is perhaps directed towards Jake.

As a side note, is it possible for the developers of the CLI tool to set up an automatic Chocolatey release of the binaries? 
The current release seems to be community supported, and on version 2.4.7: https://community.chocolatey.org/packages/rancher-cli
I have tried to contact the maintainer of the current Chocolaty release to no avail, but I hope to push a new version of it, when I go through the Triage process.

**Comment by snasovich** [comment]
@Tonur , thank you for reporting this issue. We've had an issue with CI during that time. It has since been corrected and 2.6.7 release of the CLI was recreated with binaries now - https://github.com/rancher/cli/releases/tag/v2.6.7.

At this time we don't maintain Chocolatey repo for any of Rancher tools.
