### ISSUE TITLE
Incorrect rke-tools image version for windows during cluster provision.

### ISSUE THREAD

**Issue by dzup4uk** [rancher/rancher#38657]
Created new Windows cluster k8s v1.21.14 using Rancher 2.6.6 and facing an issue with provisioning windows nodes.
It’s unable to pull an image rancher/rke-tools:v0.1.87
Looking at dockerhub the latest windows compatible image is v0.1.83.
Any suggestions?

**Comment by rosskirkpat** [comment]
@dzup4uk This is due to RKE Windows being deprecated. v0.1.83 was the last published version with windows builds.

I recommend transitioning to RKE2 Windows clusters, which went GA in Rancher v2.6.5.

Please refer to:
https://github.com/rancher/rke-tools/commit/2c5dc16b75a8f6b1e2cdd2a3bc4f4970ff9aeaeb
https://www.suse.com/support/kb/doc?id=000020684
https://github.com/rancher/windows/issues/182
