### ISSUE TITLE
[BUG] create & edit ingress  cannot select service with project member

### ISSUE THREAD

**Issue by stardemo** [rancher/rancher#38695]
**Rancher Server Setup**
- Rancher version: v2.6.7
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.20.11 ha with rancher server
- Proxy/Cert Details: with https cert 

**Information about the Cluster**
- Kubernetes version:  v1.20.11
- Cluster Type (Local/Downstream): Imported
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Project Member

**Describe the bug**

with the cluster owner ,user can edit /create ingress and normally select service with current namespace,but with the user who has  
project member permission, can edit/create ingress but cannot see any service with the same namespace,and shows `Sorry, no matching options`

**To Reproduce**

same as describe , use two different role user,create ingress in the same cluster and namespace.

**Result**

user with project member
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/20634646/186055774-a741192d-8366-47c3-80f0-1dd59f40e572.png">

**Expected Result**

user with cluster owner
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/20634646/186056108-9fc5375c-0840-41c3-bd82-527adf9eeb07.png">

**Screenshots**

**Additional context**

i also found user with `project member` role, the service resource has been received via chrome DevTools,
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/20634646/186057042-4bfb2991-65f8-441b-a705-45cd8547bcd5.png">

**Comment by niusmallnan** [comment]
### The Workaround

I create a new cluster role named`View IngressClass`. It has access to `ingressclass`.

<img width="1428" alt="截屏2022-08-26 上午10 48 14" src="https://user-images.githubusercontent.com/998984/186805887-43c9cced-7902-4295-bfd3-83201024d365.png">

Then bind the user with this role in the cluster.
<img width="818" alt="截屏2022-08-26 上午10 49 58" src="https://user-images.githubusercontent.com/998984/186806071-fef70ae7-b188-4218-b87a-861d0dfd3f9b.png">

In this way, the user can read ingressclasss in the Project, and the UI can also list services.

### The Rootcause

In 2.6.7, IngressClass is supported when creating Ingress
The default Project Member lacks access to the IngressClass, causing the UI to not display the service correctly.

In addition to adding the IngressClass to the Project Member, evaluate the role's settings such as View Ingress.

For non-namespace-level permissions to join Project Member, the whitelist mechanism of globalResourcesNeededInProjects also needs to be considered. 

This is also the reason why the Project Member is not directly updated in the workaround because it is not in the whitelist and will not take effect in the end.

**Comment by stardemo** [comment]
> Project
 so the solution to avoid this problem is create a role which can access ingressclass？ I use the code 
https://github.com/rancher/dashboard/pull/6718 also can work .

**Comment by mantis-toboggan-md** [comment]
@stardemo yes, that looks like the proper fix for this problem. It's fixed in v2.6.9. Since this is purely a UI issue I'm going to close it in favor of the dashboard issue here https://github.com/rancher/dashboard/issues/7194
