### ISSUE TITLE
[Backport v2.6.9][Azure AD] Always check access token from Microsoft Graph

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#38754]
backport of: https://github.com/rancher/rancher/issues/38880

It would be good to add this guardrail to prevent users from losing access to Rancher via Azure AD or getting their Azure AD setup in an invalid state. This can happen if they don't follow the documentation in setting the necessary permissions for their App registrations in Azure for Rancher v2.6.7+.

On initial Azure AD setup or subsequent login or search attempts, always check the access token to Microsoft Graph if it does not have the necessary permissions.

**Comment by anupama2501** [comment]
Reproduced the issue on v2.6.7
From azure app, removed the permission Microsoft graph permission`Group.Read.All` 
Enable Azure AD from the rancher server, and verify the `azuread-access-token` is created even with missing permissions in the local cluster >> ns: cattle-global-data.

**Comment by anupama2501** [comment]
QA to validate:
Fresh install:
1. Remove the Microsoft graph permissions and enable Azure AD from 2.6-head, verify the local cluster >> cattle-global-data do not cache the secret `azuread-access-token`
2. Enable azure AD with all the required permissions, then remove the configs, edit the azure AD and add in the secret, verify the azure ad config errors out. 
3. Enable azure ad with all the required permissions, verify the secret token is cached
4. Disable azure AD after step3, remove the permissions and verify the secret token is not cached
5. Try enabling azure AD via terraform without the required perms and verify it errors out and no secret is cached. 

Upgrade:
1. From 2.6.7, try to enable azure ad without the permissions, ensure the secret is cached, upgrade rancher and verify the token is deleted. Re try enabling the azure AD config and verify the secret is not cached.

**Comment by anupama2501** [comment]
On v2.6-head 79a5328 after enabling Azure AD with right permissions and then disable it the azuread-access-token is not removed.

Steps:
1. Install rancher on v2.6-head
2. Enable azure AD with all the required microsoft application permissions.
3. Disable the Azure AD auth and notice the secret is not deleted from local cluster >> ns: cattle-global-data >> `azuread-access-token`

re opening the issue as we expect the token to be deleted.

**Comment by anupama2501** [comment]
Verified test cases:

**Migration:**

On v2.6.6 rancher server
1. Enabled azure AD auth by removing the permissions required for migration - auth is enabled 
2. Created 2 downstream clusters - rke1 and rke2 node driver and ran pre upgrade checks
3. Upgraded rancher server
4. Update end points banner is displayed on the UI
 <img width="200" alt="perms" src="https://user-images.githubusercontent.com/38144301/190124907-3761c34b-1c5e-4d5b-82b0-a14a13ed1d02.png">
5. Tried to update the banner and an error pops up
6. Add required permissions and waited for a few minutes and retried updating - works as expected.
7. Logout and relogin - works as expected 
8. Login as a standard user and verified the API token previously created works fine to create workloads, ingress etc

**Fresh install:**

1. In the Azure portal, removed consent for one of the required permissions in the app Group.Read.All
2.Installed Rancher ion v2.6-head
3. Try to enable Azure AD in the UI.
4. See the error in the UI saying the app does not have all the necessary permissions.
```
server error while authenticating: missing required Application type permissions from Microsoft Graph: need Group.Read.All, User.Read.All
```
5. Check that a secret called azuread-access-token in the cattle-global-data namespace does not exist.
6. Go back to the Azure portal and add consent to the necessary permissions. Wait a minute for them to be propagated.
7. Try enabling Azure AD again, which must succeed.
8. Check that a secret called azuread-access-token in the cattle-global-data namespace has been created.


**Cache:**

1. Install rancher on v2.6-head 
2. Enable Azure AD auth provider with all the required permissions
3. In the Azure portal, removed consent for one of the required permissions in the app User.Read.All
4. Log out and try logging in.
5. Logged in successully because of the cached secret. 
6. Deleted the secret.
7. Log out and try logging in. Verified unable to login
8. Check that a secret called azuread-access-token in the cattle-global-data namespace does not exist.
9. Go back to the Azure portal and add consent to the necessary permissions. Wait a minute for them to be propagated.
10. Try logging in as an Azure AD user again.
11. Check that a secret called azuread-access-token in the cattle-global-data namespace has been created.


**Upgrade** 
Case1:
1. On v2.6.8 rancher server enable azure AD by removing one of the required permissions, azure AD is not enabled but a cache secret `azuread-access-token` in the namespace cattle-global-data is created.
2. Upgrade rancher server to v2.6-head and verify the secret is still available
3. try to enable azure AD --> Fails with the error that all permissions are required.
4. Verify the secret removed from cattle-global-data namespace is deleted.
5. Re enable azure AD by adding all the required permissions and verified that the secret is created in the local cluster 
6. Logout of the rancher server and then re login - succeeds 

Case2:
1. On v2.6.8 rancher server enable azure AD with all the required permissions
2. Upgrade rancher server to v2.6-head and verify the secret is still available
3. Remove the consent for one of the required permissions in the app User.Read.All
4. try to edit azure AD by adding in the secret - Config is saved because of the access token
5. Remove the secret from cattle-global-data namespace.
6. Try to re edit azure AD and when we save the config it fails
7. If we try to logout and re login we see an error `An error occurred logging in. Please try again.`
8. Re enable azure AD by adding all the required permissions and verified that the secret is created in the local cluster 
9. Logout of the rancher server and then re login - succeeds

**Comment by anupama2501** [comment]
Verified on v2.6-head a3b5237

1. On v2.6-head rancher server enable azure AD with all the required permissions
2. Disable azure AD auth
3. Remove the consent for one of the required permissions in a different app `User.Read.All`
4. Re enable azure AD with the new app
5. Azure AD is enabled as we have the token from the previous application [Tokens will be cleaned up as part of a future fix]
6. Remove the token from cattle-global-data ns in the local cluster.
7. Log out --> Fails with the error `An error occurred logging in. Please try again.`
8. Re login --> Fails with the error `An error occurred logging in. Please try again.`
9. Add the removed permissions with the admin consent.
10. Login works and the token is created in cattle-global-data ns of the local cluster.

**Comment by maxsokolovsky** [comment]
# Release note
For Azure AD, Rancher now doesn't create or update the cached secret with the Azure AD access token, if a new token does not have the necessary permissions. Rancher also prevents admins from updating the endpoints for Microsoft Graph, if a new token lacks permissions.
*Note: this will be removed in v2.6.10 in favor of a different approach of handling token permissions.*
