### ISSUE TITLE
Regression testing for Bundle Pruning

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38752]
2.6.8 fixed a few related issues with this PR: https://github.com/rancher/fleet/pull/933
This ticket tracks the regression testing for that area of code.

**Comment by ronhorton** [comment]
**Pass** verified fixed in `2.6.8-rc1` and `rancher/fleet-agent:v0.3.11-rc1`

- verified https://github.com/rancher/rancher/issues/38672 fixed by upgrading to 2.6.8-rc1
- verified fresh installs for fleet and monitoring, logging and longhorn on downstream cluster
- verified chart tolerations (rancher max version) are set - all feature charts appear in apps & marketplace
