### ISSUE TITLE
[2.5] [BUG] Unable to interact with downstream clusters after upgrading from 2.5.15 to 2.5.16

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#38815]
Backport rancher/rancher#38699

**Comment by brudnak** [comment]
Closing issue based on internal convo with dev team about not being able to test due to hosted k8s versioning

- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

- https://cloud.google.com/kubernetes-engine/docs/release-schedule

- https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
