### ISSUE TITLE
Customizable records naming for external-dns

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3882]
Today fqdn for external dns records is defined the following static way:

serviceName.stackName.environmentName.rootDomain

We should allow to define a custom format. Suggestion by @vincent99:

```
${service}.${stack}.${hostedzone}` (with a documented list of variables, or anything available in metadata?) and people can do whatever they want to it instead of us enforcing a certain scheme
```

@ibuildthecloud

**Comment by hwinkel** [comment]
Great  please include SRV records as well

-- 
Holger Winkelmann 
Managing Director 
Travelping GmbH 

email: hw@travelping.com 
mobil: +49-171-5594745 
http://www.travelping.com 
http://www.linkedin.com/in/hwinkel 

## Sent from a mobile device. Sorry for brevity and typos ##

On 9 Mar 2016 05:27, Alena Prokharchyk <notifications@github.com> wrote:

Today fqdn for external dns records is defined the following static way:

serviceName.stackName.environmentName.rootDomain

We should allow to define a custom format. Suggestion by @vincent99:

${service}.${stack}.${hostedzone}` (with a documented list of variables, or anything available in metadata?) and people can do whatever they want to it instead of us enforcing a certain scheme 

@ibuildthecloud

**Comment by nunofgs** [comment]
Yes, please! Having an uncustomizable `fqdn` forces me to create CNAMEs to the actual domains I want.

**Comment by superseb** [comment]
Realized in https://github.com/rancher/external-dns/commit/07b84160bbbcf878f6d0348c1f837082f5be2e6b
