### ISSUE TITLE
[BUG] Timeout received when waiting for rancher connection info

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#38916]
**Rancher Server Setup**
- Rancher version: v2.6-head (a3b5237)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Docker
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.x
- Cluster Type (Local/Downstream): Custom
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

Received an `operation timed out` from `curl` when registering a node against my new RKE2 cluster.

```
[INFO]  Generating Cattle ID
curl: (28) Operation timed out after 60001 milliseconds with 0 out of -1 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[INFO]  Successfully downloaded Rancher connection information
```

**To Reproduce**
Run registration command.

**Result**
It takes a while.

**Expected Result**
It should not take a while.

**Screenshots**

**Additional context**

**Comment by Oats87** [comment]
RCA:

In Kubernetes 1.24, a change was made where service account token secrets are no longer created by the `token-controller` run by the `kube-controller-manager`. As such, the service account objects that are created are no longer mutated with a `secrets` field, which we used to rely on to find the token for the service account for the downstream system agent.

With the change in my PR, we will now open a specific watch for the secret by name, as this will be created by Rancher.

**Comment by Josh-Diamond** [comment]
Ticket #38916 - Test Results
---

With Docker on a single node instance:

Verified on rancher `v2.6-fb0b18c157ce719bcc6050b11d8cd0c396772051-head`:

- Scenario 1 - ❌ 
   - Test: `Provision RKE2 Custom w/ k8s v1.24.4+rke2r1`
   - Result: Timeout encountered when registering node(s)
- Scenario 2 - ✅ 
   - Test: `Provision K3s Custom w/ k8s v1.24.4+k3s1` 
   - Result: Timeout not encountered; expected behavior

---

Reproduced - ✅ - Wednesday September 21, 2022

On rancher `v2.6-a3b5237ce1da4228c97df7552d57464c64947b3b-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 Custom cluster w/ k8s `v1.24.4+rke2r1`
3. Reproduced - Timeout encountered when registering node(s)
4. Provision a downstream K3s Custom cluster w/ k8s `v1.24.4+k3s1`
5. Reproduced - Timeout encountered when registering node(s)

Screenshot:

<img width="809" alt="Screen Shot 2022-09-21 at 3 42 41 PM" src="https://user-images.githubusercontent.com/46494969/191624548-9e30d1dd-fe37-4dc7-a1e7-91b4720dc621.png">

---

Scenario 1:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 Custom cluster w/ k8s `v1.24.4+rke2r1`
3. Veri-Failed - Timeout encountered when registering node(s)

Screenshot:

<img width="803" alt="Screen Shot 2022-09-21 at 4 30 12 PM" src="https://user-images.githubusercontent.com/46494969/191627683-7ad4be49-0455-4dc2-9d3c-7ee7c415d6aa.png">

---

Scenario 2:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream K3s Custom cluster w/ k8s `v1.24.4+k3s1`
3. **Verified** - Timeout not encountered; expected behavior

Screenshot:

<img width="466" alt="Screen Shot 2022-09-21 at 4 35 42 PM" src="https://user-images.githubusercontent.com/46494969/191628091-3ae8eed7-0f77-4794-a78a-4c3e90a7a9ca.png">

**Comment by sowmyav27** [comment]
@Oats87 Could you please add QA Template/more info in the PR for the latest fix ?

**Comment by jameson-mcghee** [comment]
During testing on v2.6-head (Commit ID: 2e00266) while following the Steps to Reproduce, I did not observe the timeout error (See Logs: [38916TestLogs.txt](https://zube.io/files/rancher/87123df2a61d746426fc1a41260b55cd-38916testlogs.txt)). Based on this, as well as the previous testing performed by @Josh-Diamond, I am closing this ticket as Done.
