### ISSUE TITLE
Prepare prometheus-federator chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38979]
prometheus-federator chart needs to be updated for 2.7 by 

1) File a PR removing the `doNotRelease` flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag
2) To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8
3) Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by aiyengar2** [comment]
FYI: 

As discussed with @prachidamle offline, the rancher/prometheus-federator repo will not be maintaining one release line **in upstream rancher/prometheus-federator** per Rancher minor version release; instead, https://github.com/rancher/prometheus-federator/pull/21 details how we plan to make releases in rancher/prometheus-federator available to different Rancher minor versions.

The reason why we are not maintaining multiple release lines in upstream is that Prometheus Federator **as a binary** has practically no inter-dependency with Rancher outside of the canonical use of the namespace `cattle-monitoring-system`; all Rancher integration are provided via values supplied in the `values.yaml` of the chart, which can be overridden per Rancher version as part of charts-build-scripts pulling in and maintaining the charts in rancher/charts.

If a Rancher minor version does need rancher/helm-project-operator changes in order to have Prometheus Federator functioning as expected, that would be identical to any feature request made to the rancher/prometheus-federator or rancher/helm-project-operator repo to support a new environment; therefore, upstream versioning can remain entirely independent of Rancher versioning.

This differs from charts like EKS Operator, GKE Operator, CSP Adapter, Rancher Backups, etc. which are much more intrinsically built for specific Rancher minor versions, and therefore need to cut new releases on Rancher minor releases.

**Comment by ronhorton** [comment]
verified in 2.7.0 release testing
