### ISSUE TITLE
[BUG]Cluster Disappears from Cluster Management when applying new Cluster Config Payload via API

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#39042]
SURE-5275

**Rancher Server Setup**
Rancher version: 2.6.6
Rancher Cluster:
Rancher version: 2.6.6
Number of nodes: 3
Node OS version: 18.04

Downstream Cluster:
Number of Downstream clusters: 4
Node OS: Ubuntu 18.04
Kubernetes version: 1.22.9
CNI: Canal

**Describe the bug**
Fidelity hits the end point /v3/clusters/${CLUSTERID} via their automation to update their cluster config to keep it clean. They are currently testing removing PSPs. It was found that podSecurityPolicy could not be changed via this method. Changing the endpoint to  /v3/clusters/${CLUSTERID}?_replace=true allowed the change to take place. However, while the change is propagated to the cluster it is not visible in the Cluster Management Page. It is still viewable when you do kubectl get clsuters.managment.cattle.io, and it will come back after the change it done. 

**To Reproduce**
curl -X PUT 'https://${RANCHERSERVER}/v3/clusters/${CLUSTERID}?_replace=true' -H 'Accept: application/json' -H "content-type:application/json" -H "Authorization:Bearer ${TOKEN}" -d "${JSONPAYLOAD}" --insecure

**Result**
cluster disappears from the UI

**Expected Result**
Cluster Stays in the UI. This should be identical to editing the config in the UI as it is the same exact call that is sent via the manual method.

**Additional context**
Also wondering why ?_replace=true is required to make the change to podSecurityPolicy when everything else seems to be changeable without that argument. Want to also make sure there is no other impact besides it being removed from the UI

**Comment by crobby** [comment]
I've done some digging on this and I'm so far unable to duplicate the problem.  Just in case I'm doing something that isn't on the right path here, let me describe what I've done.
1) Created an RKE cluster in Digital Ocean
2) Saved off that cluster config
3) Edited that cluster config json to include....
`
podSecurityPolicy: true
defaultPodSecurityPolicy: "restricted"
`
4) curl -X PUT ..../v3/clusters/$clusterid?_replace=true with my updated payload
5) Observed that my cluster was updated and was still visible in the dashboards cluster management page
6) Repeat toggling podSecurityPolicy by PUTting the original config back and trying the updated config again.

Each time, the cluster remained on the cluster management page.

If my testing method was invalid or otherwise misguided, can I get some more context and possibly a sample payload for the PUT request that caused the problem?
