### ISSUE TITLE
Confirm that all images in rancher-images.txt come from the Rancher repo.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#39159]
- The "registry:2" image will be removed as part of the pipeline feature in Rancher Manager is being removed from the product. (Pipelines) https://github.com/rancher/rancher/issues/37324
- The "busybox" image will be updated as needed. (Busybox) https://github.com/rancher/rancher/issues/35587

**Comment by deniseschannon** [comment]
Since both issues are ready to test, this is ready to test i the next Rancher C

**Comment by deniseschannon** [comment]
This is available in v2.7.0-rc4

**Comment by brudnak** [comment]
Reopening - As noted in https://github.com/rancher/rancher/issues/35587

The rancher-images.txt still contains references to busybox

**Comment by deniseschannon** [comment]
@brudnak Based on the fact that hte other referenced issue is now closed, could this be closed?

**Comment by samjustus** [comment]
@deniseschannon Caleb was going back and forth with @cwayne18, PM, and legal, but the last update I got was that we 'should be fine'. Something like that. I would say the answer is not in Andrew's hands at this point.

**Comment by deniseschannon** [comment]
Since this issue is to track that all issues come from the "rancher" repo in Dockerhub, I think this is fine to close if there are no stray images in the rancher-images.txt that do not start with a prefix of `rancher`. There is another thread specifically around the use of `busybox` image, but that is not the purpose of this ticket.
