### ISSUE TITLE
If I refresh browser while in a specific catalog I get a error page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3916]
Version - master 3/10

Steps to Reproduce: 
1. Go to catalog page
2. From Catalog drop-down select community
3. Refresh your browser

Results: Error page i is not a function, Reload to try again or log out
![image](https://cloud.githubusercontent.com/assets/11514927/13683378/991abc62-e6c3-11e5-818d-4bde86a7f17f.png)

Expected: No error page

**Comment by vincent99** [comment]
This isn't really exactly related, but as a side effect would be fixed by making the category a part of the route instead of a query param.. which would go well with making the catalogs the subnav:

![image](https://cloud.githubusercontent.com/assets/753917/13800079/a195c198-eae2-11e5-8621-e8bf6b0fb87a.png)

**Comment by tfiduccia** [comment]
Version - master 3/23
Verified fixed
