### ISSUE TITLE
[RFE] Rancher Helm Chart ingress hardcoded to port 80

### ISSUE THREAD

**Issue by anders-swanson** [rancher/rancher#39213]
Rancher Ingress is hardcoded to port 80. Port should be configurable to use the HTTPS port if desired - TLS termination at the load balancer may not be acceptable in all environments.

Fix is straightforward: Parameterize the ingress port in the helm chart. I am happy to make this change.

**Comment by jiaqiluo** [comment]
This is an enhancement to the Helm chart. 

### Root cause
(copied from the linked PR)
After installing Rancher using the official helm chart behind a reverse proxy (such as ingress-nginx or some other ingress controller/load balancer solution), `kubectl exec` and related commands (attach, port-forward) fail when using the Rancher-generated kubeconfig.

This is because the ingress created by the Rancher helm chart defaults to use TLS termination (ingress service port is hardcoded to `80`), and the SPDY protocol used in `kubectl exec` requires TLS. 

### What was fixed, or what changes have occurred
(copied from the linked PR)
Modify the Helm chart to parameterize the ingress service port. The default value remains the same (80), but now users may specify the HTTPS port (443) if they do not want TLS termination to happen at the load balancer.
  
### Areas or cases that should be tested

Using the helm chart to install rancher, the value of `servicePort` ( in the value.yaml file) should be applied to the Ingress object which is defined in the chart. 

  
### What areas could experience regressions?
 
the default value (80) should still be applied. 

### Are the repro steps accurate/minimal?

yes

**Comment by deniseschannon** [comment]
This is available to test in v2.7.0-rc4

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 9f1e043
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE

----------

### Testing: ###

Tested this issue with the following steps:
1. Create cluster to deploy rancher on using rke
2. Install Rancher using helm chart and add the flag `--set ingress.servicePort=<number>`
3. Wait for Rancher to be deployed
a. `kubectl -n cattle-system rollout status deploy/rancher`
4. Verify that servicePort has been successfully updated to the ingress
a. `kubectl get ingress rancher -n cattle-system -o yaml`

**Result** - Pass
`servicePort` has been successfully updated to the rancher ingress using the helm chart
![image.png](https://zube.io/files/rancher/eba862eda74de69519c89460b81d8bec-image.png)
