### ISSUE TITLE
[RFE] Ship bundles that adhere to semver

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#39303]
Copied from https://github.com/rancher/rke2/issues/2272 but ensuring it can be tracked by @Sahota1225 

Related UI ticket regarding upgrades not working within RKE2 versions (with extra comments): https://github.com/rancher/dashboard/issues/4776

As noted, the UI is dependent on semver logic to know the steps to upgrade. So when UI sees the RKE2 flow to upgrade from `v1.21.7+rke2r2` to `v1.21.7-rc2+rke2r3`, the hyphen `-` actually is a separator for versions, meaning that per helm, this is actually a downgrade as `v1.21.7` (without the `-rc2+rke2r3`) is lower than `v1.21.7+rke2r2`.

UI can consider a hack to make this upgrade logic work but our preference is to have the plus `+` data before the `-` (e.g, `1.21.7+rke2r3-rc2`). It has been noted that the current versioning is tied to Kubernetes pre-releases but enough people would like to see this changed so that we can make upgrades clearer using semver.

**Comment by snasovich** [comment]
@gaktive , I'm not sure why we want to track it in rancher/rancher since we use versions as they come from RKE2 so I think tracking it in https://github.com/rancher/rke2/issues/2272 only is perfectly fine.

Closing the issue. Please reopen if I've missed something.

Also, to add to what was posted in https://github.com/rancher/rke2/issues/2272#issuecomment-995212700 by @brandond :
* Going with `+` before `-` (e.g. `1.21.7+rke2r3-rc2`) won't be correct as that makes this a full release, not prerelease - the whole part after `+` is considered metadata. See https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions and https://regex101.com/r/ujL9Jq/1.
* Also, per the spec (https://semver.org/#spec-item-10) metadata should not be used to determine precedence, so technically `1.21.7+rke2r3` is not newer than `1.21.7+rke2r2`.

**Comment by gaktive** [comment]
@snasovich this ticket was filed here at the request of @Sahota1225 :) since it was tied to tracking towards the 2.7.x release and that other repo ticket was always going stale. As long as work does happen with the ticket, I'm OK with wherever.

**Comment by snasovich** [comment]
@gaktive , understood. Added `kind/enhancement` to that RKE2 issue so it's not picked up by stalebot.
