### ISSUE TITLE
[BUG] -  Airgap - Rancher Monitoring v2 install job rancher-monitoring-crd-create has image pull error of rancher/shell:v0.1.18

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#39364]
**Rancher Server Setup**
- Rancher version: `v2.7.0-rc4`
- Installation option: Helm Airgap
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: byo-valid

**Information about the Cluster**
- Kubernetes version: 1.24
- Cluster Type: Downstream
   - If downstream, what type of cluster?: Custom RKE2
  

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions: none

**Describe the bug**

On Rancher Airgap if the user tries to install Monitoring, the CRD install job fails because it's attempting to pull the image `rancher/shell:v0.1.18` but the image is in the private registry `<private registry URL>/rancher/shell:v0.1.18`

**To Reproduce**

- Rancher installed 2.7.0-rc4
- Navigate to Apps -> Monitoring -> Do the setup and click install 
- In the jobs of the rancher-monitoring-system  namespace `rancher-monitoring-crd-create` is stuck

**Result**

- The pods of job `rancher-monitoring-crd-create` are attempting to pull the image from external repository. Causing the error.

**Expected Result**

- Images should be pulled from the private registry

**Screenshots**

The `Container Registry` is correctly set during the App install.

<img width="793" alt="Screen Shot 2022-10-19 at 3 44 11 PM" src="https://user-images.githubusercontent.com/27659/196818713-6c446916-58c8-453e-b4bb-c1f7c1762bb7.png">

**Additional context**

The job's pod pulling from `rancher/shell:v0.1.18`

<img width="583" alt="Screen Shot 2022-10-19 at 3 58 25 PM" src="https://user-images.githubusercontent.com/27659/196820065-d5630b54-59eb-4c10-bff3-bff395b2affd.png">

**Comment by richard-cox** [comment]
The fix for related issue #6910 came in rc5 (and a bugfix for rk1 is an open PR ready to merge). The screenshots look a little odd, as there should be no container input field in rc4, was any of the `ui-offline-preferred` related settings changed?

From testing on my local v2.7-head the install chart process shows the correct registry `docker.io` to use, it then recognises this to be the system default and supplies an empty string in values 
  ```
  global.cattle.systemDefaultRegistry = ""
  global.systemDefaultRegistry = ""
  ``` 
This still results in similar scenario from screenshots above.

We need to confirm with the BE that an empty string does still mean the system registry is used, and that it should be working.

**Comment by izaac** [comment]
No `ui-offline-preferred` setting was changed during testing.

**Comment by izaac** [comment]
Rancher version: `v2.7.0-rc5`

This is now working after the fix in the FE https://github.com/rancher/dashboard/issues/7246

Monitoring and other charts have their pods pulling images from the configured global registry
