### ISSUE TITLE
[BUG] After v2.6.8 upgrade, high CPU/load on nodes and database, nodes flapping between ready/unready, excessive "refresh processing" logs

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#39401]
Rancher Cluster:
Rancher version: 2.6.8 (after upgrade from 2.6.6)
Number of nodes: 2
Node OS version: SLES 15 SP4

**Describe the bug**
After upgrade (around 10AM PDT) from v2.6.6 to v2.6.8, CPU/load on nodes and RDS MySQL database has been high. Nodes flapping between Ready/Not Ready

Business impact:
Rancher is availablility is flapping. Unable to meet uptime SLA

Troubleshooting steps:
Looked at Rancher logs. When running in DEBUG, seeing this continuously:

**To Reproduce**
Unknown, happened after v2.6.6 to v2.6.8 upgrade

**Result**
High CPU/load (~ 100%), Rancher unavailable.

**Expected Result**
Rancher running at 10-20% CPU and up.

**Additional context**
logs in jira issue

SURE-5323

**Comment by rmweir** [comment]
Possibly related to https://github.com/rancher/rancher/pull/38193.

**Comment by MbolotSuse** [comment]
Got some additional notes for a test case that we should include for this fix when ready.

This issue can also cause etcd to run out of memory in certain circumstances. Repro steps below:

1. Create a k8s cluster for rancher HA. Ensure that there are 3 nodes, RKE, each node all roles, 16 core CPU 64GB memory (digital ocean slug `g-16vcpu-64gb`) was used in testing.
2. Install rancher 2.6.6. Complete basic setup (provide bootstrap, set new password).
3. Create 6,000 tokens (script available). Tokens are used to slow down the refresh process slightly since the local provider is being used (which can complete refresh quicker than other providers). 
4. Create 700 users and user attributes (script available). Ensure that the user attributes are sufficiently large (I used large annotations to achieve this).
5. Upgrade rancher to 2.6.9 (I used terraform and just changed the version from 2.6.6 -> 2.6.9).
6. Wait and observe etcd memory usage, you will run out of memory soon (you can also increase log verbosity to observe the constant user refresh messages in the logs).

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment


| Component                        | Version / Type                           |
| -------------------------------- | ---------------------------------------- |
| Rancher version                  | 2.6.6                                    |
| Installation option              | Helm (high availability)                 |
| RKE binary version used          | v1.3.11                                  |
| If Helm Chart k8s cluster        | v1.23.6                                  |
| Cert Details                     | Let's Encrypt / `nginx`                  |
| Docker version                   | 20.10.7, build f0df350                   |
| Helm version                     | v2.16.8-rancher2                         |
| Downstream cluster type          | n/a                                      |
| Downstream K8s version           | n/a                                      |
| Authentication providers enabled | local                                    |
| Logged in user role              | Admin, Standard User                     |
| Browser type                     | Google Chrome                            |
| Browser version                  | 108.0.5359.124 (Official Build) (x86_64) |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

```shell
#!/bin/sh

helm repo update

kubectl create namespace cattle-system

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml

helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1


helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR  \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```


</details>


## Reproduction steps

1. Create a k8s cluster for rancher HA. Ensure that there are 3 nodes, RKE, each node all roles, (`m5.4xlarge` in `AWS ec2`) was used in testing
2. Install rancher 2.6.6. Complete basic setup (provide bootstrap, set new password).
3. Create 6,000 tokens (script available). Tokens are used to slow down the refresh process slightly since the local provider is being used (which can complete refresh quicker than other providers)
4. Create 700 users and user attributes (script available). Ensure that the user attributes are sufficiently large (I used large annotations to achieve this)
5. Upgrade rancher to 2.6.9 (I used a helm upgrade command, see below)
6. Wait and observe etcd memory usage, you will run out of memory soon (you can also increase log verbosity to observe the constant user refresh messages in the logs)


```shell
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR  \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```

## Additional Info

## RESULTS

#### ✅ Expected

To be able to upgrade without the etcd memory usage erroring out

#### ❌ Actual

etcd memory usage ran out shortly after upgrade ~5 minutes. Getting the warning `alarm:NOSPACE`. And memory went from `249 MB` to ==> `2.2 GB`
 
<hr>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.6-6f2b125ff169d2c80757cd753bb2a2b52c7de718-head                                 |  |
| Rancher commit link              | https://github.com/rancher/rancher/commit/6f2b125ff169d2c80757cd753bb2a2b52c7de718 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.3.11                                                                            |
| If Helm Chart k8s cluster        | v1.23.6                                                                            |
| Cert Details                     | Let's Encrypt / `nginx`                                                            |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | n/a                                                                                |
| Downstream K8s version           | n/a                                                                                |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | Admin, Standard User                                                               |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 108.0.5359.124 (Official Build) (x86_64)                                           |


<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

```shell
#!/bin/sh

helm repo update

kubectl create namespace cattle-system

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml

helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1


helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```

</details>

## Validation steps

1. Create a k8s cluster for rancher HA. Ensure that there are 3 nodes, RKE, each node all roles, (`m5.4xlarge` in `AWS ec2`) was used in testing
2. Install rancher 2.6.6. Complete basic setup (provide bootstrap, set new password).
3. Create 6,000 tokens (script available). Tokens are used to slow down the refresh process slightly since the local provider is being used (which can complete refresh quicker than other providers)
4. Create 700 users and user attributes (script available). Ensure that the user attributes are sufficiently large (I used large annotations to achieve this)
5. Upgrade rancher to 🚨 `v2.6-head` (I used a helm upgrade command, see below)
6. Wait and observe etcd memory usage


```shell
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```

## Additional Info

## RESULTS

#### ✅ Expected

To be able to upgrade without the etcd memory usage erroring out

#### ✅ Actual

Was able to upgrade without any errors from etcd memory, usage stayed at `~249 MB` before and after upgrade

**Comment by rmweir** [comment]
Release note: Fixed issue where handlers involving handlers would infinitely loop if a user had no tokens or only had tokens that did not the ExtraByProvider field.
