### ISSUE TITLE
rancher-monitoring deployment stuck when disabling rbac/psp

### ISSUE THREAD

**Issue by bhagtrajaram** [rancher/rancher#39426]
Hi,

I'm in the process of replacing the 'rancher-monitoring' psp's to gatekeeper policies in Rancher. One of my first steps is to disable the creation of psp's by the 'rancher-monitoring' chart. My gatekeeper policies are in place and functional. 

Please note the following (templating) configuration which i use (deployment goes via Terraforms):

***configuration
global:
  cattle:
    systemDefaultRegistry: ""
  imagePullSecrets: null
  kubectl:
    pullPolicy: IfNotPresent
    repository: rancher/kubectl
    tag: v1.18.6
  rbac:
    create: true
    pspAnnotations: {}
    pspEnabled: false
    userRoles:
      aggregateToDefaultRoles: true
      create: true
  systemDefaultRegistry: ""
  
  *** setting
  rbac:
    create: true -> false

As soon as i set the flag to 'false' the deployments gets stuck. Setting it to 'true' the deployment is succesful.

templating:

location in this repo: charts/charts/rancher-monitoring/templates/prometheus/psp.yaml

{{- if and .Values.prometheus.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{- if .Values.global.rbac.pspAnnotations }}
...
...

Is this the right place to disable the creation of psp's of the 'rancher-monitoring' chart?

Regards,

**Comment by aiyengar2** [comment]
@MKlimuszka this is something we should look into as part of supporting Monitoring in k8s 1.25, when PSPs will no longer be available.

**Comment by aiyengar2** [comment]
@bhagtrajaram there should be a couple of values.yaml fields you can use to disable all PSPs deployed with the chart, but it's not well-documented at the moment so I don't have an answer for this question off-hand. However, once we address this for 1.25 there should hopefully be a way to disable these PSPs from being created globally as well (probably by leveraging the `global.rbac.pspEnabled` field across all subcharts instead of the current behavior)
