### ISSUE TITLE
"Not enough data for graph" shown in v1 monitoring after upgrading

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39533]
Issue description:
After upgrading from Rancher v2.6.6 to v2.6.7, v1 monitoring on local and downstream clusters is displaying "Not enough data for graph"

Business impact:
Will block upgrading customers on Hosted Rancher to v2.6.7.

Troubleshooting steps:
Checked Rancher pod logs, nothing indicating any problems. Made sure all cattle-prometheus pods were running. Checked prometheus-cluster-monitoring-0 pod logs, no errors noticed.

Repro steps:

    Install Rancher v2.6.6.
    Create a RKE1 1.20.15 downstream clusters. Enable v1 monitoring. Can observe metrics on the cluster explorer UI
    Upgrade Rancher to v2.6.7
    Go back to downstream cluster cluster explorer dashboard.

Workaround:
Is workararound available and implemented? unknown

Actual behavior:
After upgrade, seeing message "Not enough data for graph" instead of metrics.

Expected behavior:
Expect to see the graphs.

SURE-5143

**Comment by MKlimuszka** [comment]
Ty to reproduce this bug upgrading from 2.6.6 to 2.6.7, and then try to reproduce it upgrading from 2.6.6 to 2.6.9. It might be fixed there. 
 Make sure you use k8s 1.18, and then try 1.20 as well.

**Comment by steffeneichler** [comment]
Hi,

we have the same problem on 2.6.9 and k8s 1.20.15.

We cannot update our production clusters until this is fixed.

**Comment by aiyengar2** [comment]
I just looked into this issue. This was a tricky one! However, I have diagnosed a root cause and a workaround.

### Root Cause

Due to a seemingly innocuous fix put in 2.6.7 to a helper function in https://github.com/rancher/rancher/commit/f8ac7256d6298c347bbaa33fe2bad9086067c218 that was intended to resolve an issue where 1.24 clusters no longer create service account tokens automatically, the logic for getting the auth token used by the Prometheus client in Rancher to execute queries on Prometheus and deliver the output at the `/v3/clustermonitorgraphs?action=query` endpoint for UI to display was modified to the following:

https://github.com/rancher/rancher/blob/c35f1126216ce66c54aadcccb547a1938d4e0bcc/pkg/api/norman/customization/monitor/handler_utils.go#L184-L196

As a result, Rancher in 2.6.7 is using a Golang Prometheus client leveraging the Service Account Token within a Rancher-created Secret called `cluster-monitoring-token` whereas Prometheus is loaded with the default Service Account Token tied to the Secret contained within the actual ServiceAccount (within the `cluster-monitoring` ServiceAccount under `.secrets[0]`), which is titled `cluster-monitoring-token-XXXXX`.

In theory, both tokens are pointing to the exact same underlying key; you can literally inspect this by running the following command to decode the contents of both secrets into a human readable format (since ServiceAccountTokens are just JWT tokens, which is two base64 JSON blobs separated by a dot):

```bash
NAMESPACE=${NAMESPACE:-cattle-prometheus}
NAME=${NAME:-cluster-monitoring-token}


kubectl get secrets -n "${NAMESPACE}" "${NAME}" -o=jsonpath='{.data.token}' | base64 -d | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
```

On running that, you'll see something like this:

```
{
  "alg": "RS256",
  "kid": "<REDACTED, BUT SAME KEY ID>"
}
{
  "iss": "kubernetes/serviceaccount",
  "kubernetes.io/serviceaccount/namespace": "cattle-prometheus",
  "kubernetes.io/serviceaccount/secret.name": "cluster-monitoring-token-XXXXX",
  "kubernetes.io/serviceaccount/service-account.name": "cluster-monitoring",
  "kubernetes.io/serviceaccount/service-account.uid": "<REDACTED, BUT SAME UID>",
  "sub": "system:serviceaccount:cattle-prometheus:cluster-monitoring"
}
```

However, the keys aren't identical and this is where the issue comes into play. **The only difference you will see is in the value of "kubernetes.io/serviceaccount/secret.name" within the second JSON blob, since the secret has a different name, which is directly encoded in the token.**


Since the tokens are different (although they point to the same key), prometheus-auth (the authorization proxy sitting in front of Prometheus in Monitoring V1) fails the direct proxy check, which is unexpected behavior that causes all queries to be rejected by Rancher's Prometheus client, resulting in an empty collection (and therefore no data) being returned to the Rancher UI.


https://github.com/rancher/prometheus-auth/blob/40787223b1c4aee600b9650a2b5412a0e841716c/pkg/agent/http.go#L68-L71


Since Grafana is still configured with the original token, it is not impacted as its token matches Prometheus's (as they both are attached to the same ServiceAccount).


### Workaround

You can simply upgrade Grafana and Prometheus to use the new Secret instead of the old one. To do this, take the following steps:
1. Patch the `cluster-monitoring` ServiceAccount in the `cattle-prometheus` namespace. Change `.secrets[0]` from `cluster-monitoring-token-XXXXX` to `cluster-monitoring-token`
2. Redeploy the Prometheus workload (ensures the new Pod uses the token from `cluster-monitoring-token` instead of `cluster-monitoring-token-XXXXX`)
3. Redeploy the Grafana workload (ensures the new Pod uses the token from `cluster-monitoring-token` instead of `cluster-monitoring-token-XXXXX`)

Data should now be showing.

**Comment by dnoland1** [comment]
Here are the kubectl commands for the workaround:
```
kubectl patch serviceaccount -n cattle-prometheus cluster-monitoring --type='json' -p='[{"op": "replace", "path": "/secrets/0/name", "value":"cluster-monitoring-token"}]'
kubectl scale --replicas=0 -n cattle-prometheus statefulset/prometheus-cluster-monitoring
kubectl scale --replicas=1 -n cattle-prometheus statefulset/prometheus-cluster-monitoring
kubectl scale --replicas=0 -n cattle-prometheus deployment/grafana-cluster-monitoring
kubectl scale --replicas=1 -n cattle-prometheus deployment/grafana-cluster-monitoring
```

**Comment by aiyengar2** [comment]
FYI for users who are looking for a better workaround:

The primary fix that will be shipped in the latest Monitoring chart will be https://github.com/rancher/system-charts/pull/579/commits/395247129bc5761aae66d1c441c50efb3b0d7ed4.

i.e.

You should be able to fix this in an existing Monitoring installation by providing overrides to set:

`grafana.image.tool.tag=v0.3.0`
`prometheus.image.auth.tag=v0.3.0`

and modifying the `cluster-monitoring` service account in the `cattle-prometheus` namespace to have the following additional rule:

```
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - "create"
```

Once you do this, redeploy the workloads for both Grafana and Prometheus.

**Important Note: The prometheus-auth image has not been fully tested by Rancher QA yet, so use this workaround at your own discretion. For production environments, it's recommended to wait till the chart officially releases in the next 2.6 release (identified by the milestone on this issue).**

**Comment by aiyengar2** [comment]
The primary fix shipped was in https://github.com/rancher/prometheus-auth/pull/13; prometheus-auth (the authentication proxy that is placed on top of Prometheus) will now do deeper token checks via creating a TokenReview resource (which is answered by the kube-api-server) and compare the token's user against prometheus-auth's token's user.

**Comment by ronhorton** [comment]
**Verified fixed** 
1. created `2.6.6 rancher HA`
2. created 1.20 cluster
3. enabled `legacy` flag
4. enabled `v1 Monitoring (Legacy) v0.3.2`
5.`upgraded` rancher to `2.6.7`
6. `verified monitoring v1 still functioning after upgrade`
<img width="1780" alt="2023-01-18_11-52-35" src="https://user-images.githubusercontent.com/89212856/213244867-1b121d43-c67e-40ef-89ce-daf6f53a3d4a.png">
