### ISSUE TITLE
[BUG] Rancher server not picking up the updated bootstrapPassword

### ISSUE THREAD

**Issue by pramodsetlur** [rancher/rancher#39576]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  GKE  v1.23.8
- Proxy/Cert Details: tls.external (TLS handled by existing nginx controller)

**Information about the Cluster**
- Kubernetes version:  GKE  v1.23.8-gke.1900
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
The updated $.Values.bootstrapPassword from the helm chart's valuefile is not being picked up by the Rancher server. After installing Rancher for the first time, the bootstrapPassword was updated and then redeployed using helm-upgrade. Deleting the rancher pods allowed the kubernetes secret to get recreated. However, the login to Rancher does not work with the new updated bootstrapPassword, and instead I am able to login only with the password that was created during the initial deployment. 

**To Reproduce**
1. Install Rancher (using Helm) for the first time in a new cluster using the follow values:
```
  tls: external
  hostname: rancher.company.com
  ingress:
    extraAnnotations:
      kubernetes.io/ingress.class: "nginx-internal"
      external-dns.alpha.kubernetes.io/hostname: rancher.company.com
  bootstrapPassword: value1
```
2. Visit rancher.company.com and login using admin/value1.
3. Update the values; bootstrapPassword: value2 and perform a helm upgrade. 
4. Visit rancher.company.com and login using admin/value2. Rancher errors with 401 indicating wrong username/password.
5. However login using admin/value1 to confirm that the login works.

**Result**
Unable to login into Rancher using the updated bootstrapPassword. Instead, logging in using the initial bootstrapPassword works correctly.

**Expected Result**
Rancher should be able to login using the updated bootstrapPassword. 
Logging in using the updated password (fetched from kubectl) should be allowed to log in.
`$ kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{"\n"}}'`

**Screenshots**

**Additional context**
It feels like there is come kind of secret persistency in place which is not allowing the login using the helm's updated bootstrapPassword.

**Comment by cbron** [comment]
@jakefhyde @pramodsetlur I believe this isn't a bug but is rather working as intended. Or if anything its a feature enhancement. Our docs state that this feature is meant for when "Rancher starts for the first time": https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/bootstrap-password

Turning this into a password reset mechanism has downsides, as the password would be sitting on a secret or env var and could be re-used later which would be a security flaw. Also during step 3 above (`perform a helm upgrade`) how would Rancher know the difference between when you want to change the password and when you don't ? Why would it not reset the password on every helm upgrade ? You can't check the current password because it's been changed by the user already when they login to the UI.
