### ISSUE TITLE
[RFE] Improve details available for Azure credentials issues troubleshooting

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39611]
**Is your feature request related to a problem? Please describe.**
When creating new Cloud Credentials for Azure it's impossible to get more information on what exactly is wrong with specified credentials as UI shows a generic "Authentication test failed, please check your credentials" message, response from `aksCheckCredentials` simply has `{"error":"invalid credentials"}` and Rancher server log doesn't have any relevant messages logged.
![image](https://user-images.githubusercontent.com/85187633/202046370-c3fd605b-bf55-436f-8eb8-675e731e081f.png)

In my case, it came down to created Azure app (Client ID) having no access to Azure subscription and that wasn't trivial to figure out.

**Describe the solution you'd like**
Some indication on UI / back-end call response / log that helps understand what exactly is wrong with the specified credentials.

**Describe alternatives you've considered**
Calling Azure APIs outside of Rancher to check what's wrong with the credentials (not ideal).

**Additional context**
None

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Create azure credential with incorrect subscription ID
2. Create azure credential with incorrect Client ID
3. Create azure credential with incorrect Client Secret

**Results**
1. Azure credential with incorrect Subscription ID
- credential creation failed with the following api error
```
{"error":"could not find tenant ID: Unexpected response from Get Subscription: subscriptions.Client#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription '<subscription_ID_redacted>' could not be found.\""}
```

2. Azure credential with incorrect Client ID
- credential creation failed with the following api error
```
{"error":"invalid credentials: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscription_id_redacted>?api-version=2016-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS700016: Application with identifier '<incorrect_client_ID>' was not found in the directory 'SUSE Linux s.r.o.'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\\r\\nTrace ID: <trace_ID_they_provide>\\r\\nCorrelation ID: <correlation_ID_they_provide\\r\\nTimestamp: <timestamp>\",\"error_codes\":[700016],\"timestamp\":\"<timestamp>\",\"trace_id\":\"<trace_ID>\",\"correlation_id\":\"<correlation_ID>\",\"error_uri\":\"https://login.microsoftonline.com/error?code=700016\"} Endpoint https://login.microsoftonline.com/<tenant_ID>/oauth2/token?api-version=1.0"}
```
3. Azure credential with incorrect Client Secret
- credential creation failed with the following api error
```
{"error":"invalid credentials: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscription_id_redacted>?api-version=2016-06-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {\"error\":\"invalid_client\",\"error_description\":\"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '<client_ID>'.\\r\\nTrace ID: <trace_ID>\\r\\nCorrelation ID: <correlation_ID>\\r\\nTimestamp: <timestamp>\",\"error_codes\":[7000215],\"timestamp\":\"<timestamp>\",\"trace_id\":\"<trace_ID>\",\"correlation_id\":\"<correlation_ID>\",\"error_uri\":\"https://login.microsoftonline.com/error?code=7000215\"} Endpoint https://login.microsoftonline.com/<tenant_ID>/oauth2/token?api-version=1.0"}
```
4. When attempting to input multiple incorrect values, it seems to be the order of the checks is
- subscription ID first
- client ID second
- client secret third
The api call will show the error of one of the parameters in that order, which makes sense since these IDs and secret and are sequential
