### ISSUE TITLE
Allow customize cattle-cluster-agent

### ISSUE THREAD

**Issue by edgrz** [rancher/rancher#39711]
**Is your feature request related to a problem? Please describe.**
My cluster agent is being evicted and I would like to ensure it's the last pod being evicted due to it's severity.

**Describe the solution you'd like**
`config.yaml` allows to customize the agent itself.

**Describe alternatives you've considered**
Run a manual patch as a workaround as an after hook of bootstrapping a new cluster.

**Additional context**
Hello,

Recently I have been suffering from cattle-cluster-agent eviction due to some `diskPressure` (not related with the topic). I wanted to set the `priorityClass` field to `cattle-cluster-agent` deployment in a way that is persisted. I have been reviewing the documentation and issues and haven't come up with a way to customize the agent itself during the bootstraping on `config.yaml` file. 

I think additional manifest sections won't work here as I don't want to create new objects, but patch the existing ones.

I have seen that you can customize/add `tolerations`, `priorityClass`, etc. to  the CNI itself. Would be great to be able to customize the cluster-agent itself as that would also enable users to set more requirements.

**Comment by sadhugit** [comment]
[SURE-4264]

**Comment by defreng** [comment]
Hi @brandond

Makes sense... Then I guess the question would be how this could be configured in Rancher.

Best,
Alex

**Comment by zbialik** [comment]
This is much needed. We just started enforcing custom `taints` on ALL our `Nodes`. This breaks our `cattle-cluster-agent` initialization because there's no way for us to configure it with `tolerations` at cluster-init.

We use the rancher terraform provider so running a patch after the `cattle-cluster-agent` is deployed isn't really viable since we want the `terraform apply` to succeed to abide by our current Iac workflow.

**Comment by dkeightley** [comment]
Just a heads up, this should be resolved with new functionality added in Rancher v2.7.5
  * https://github.com/rancher/rancher/issues/41035
