### ISSUE TITLE
[Feature] Gracefully handle PSPs in 1.25

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#39733]
Epic: https://github.com/rancher/rancher/issues/38701
SURE-5627

Step 1: Disabling and cleaning up features

Rancher's feature set around PSPs should be disabled starting in 1.25. Ideally everything would just silently not exist or operate. Controllers may be trying to create PSP objects or re-act to things, and those should act gracefully.

**Comment by maxsokolovsky** [comment]
### How I approach disabling any controllers related to PSP's for downstream clusters >=1.25.

Get a list of files and directories that have `psp` or `podsecurity` in their names.
I assume that the main thing that needs to be changed is the set of controllers that work with different resources as part of PSP management. The relevant directory is in bold. We need to check if the downstream cluster's version is 1.25 or greater, and, if yes, do not run code in the `Register` function.

Directories:
- rancher/pkg/api/norman/customization/podsecuritypolicytemplate
- rancher/pkg/api/norman/customization/podsecuritypolicybinding
- **rancher/pkg/controllers/managementuser/rbac/podsecuritypolicy**
- rancher/pkg/controllers/management/podsecuritypolicy

Files:
- rancher/pkg/generated/controllers/management.cattle.io/v3/podsecuritypolicytemplateprojectbinding.go
- rancher/pkg/generated/controllers/management.cattle.io/v3/podsecuritypolicytemplate.go
- rancher/pkg/data/management/podsecuritypolicytemplate_data.go
- rancher/pkg/controllers/managementuser/pspdelete/pspdelete.go

We must keep all the logic around Pod Security Policy Template and its Bindings (both local-cluster non-namespaced resources), because Rancher can still support downstream K8s clusters v1.24 and lower.

**Comment by maxsokolovsky** [comment]
### How controllers are registered
The controllers in the `rancher/pkg/controllers/managementuser/rbac/podsecuritypolicy` package.
The following are observations of events that occur when I provision a downstream cluster.

- When I provision K8s 1.23 with PSP's enabled, Rancher registers the controllers.

- When I upgrade the K8s version to 1.24, the controller registration does not run.

- When I disable PSP and update the cluster, Rancher does not run de-registration, which might be bad, as there will be code that runs and even potentially modifying the state of the cluster unnecessarily.

- When I enable PSP in 1.25 (tentatively allowed in the UI), my updated code does not run the controller registration.
But there is a provisioning error still. `error syncing 'c-b7dfx': handler cluster-provisioner-controller: Failed to validate cluster: PodSecurityPolicy has been removed and can not be enabled since k8s v1.25, requeuing.` This makes sense.

**Comment by anupama2501** [comment]
Validated following test cases:

**Comment by anupama2501** [comment]
To validate the issue on local k8s 1.25, we would need a rancher chart. Moving the issue to waiting for rc

**Comment by jiaqiluo** [comment]
Can be validated in Rancher [v2.7.2-rc1](https://github.com/rancher/rancher/releases/tag/v2.7.2-rc1)

**Comment by maxsokolovsky** [comment]
This needs additional work with the chart where the PSP is removed entirely for the chart used in v2.7.2.

**Comment by maxsokolovsky** [comment]
## QA Testing

Testing mostly consists of inspecting Rancher logs in the local cluster.

### Scenario 1
1. Provision a new downstream cluster with K8s v1.25.
2. When the cluster is up, search Rancher logs in the local cluster for messages that pertain to starting PSP-related controllers in the local cluster. Specifically, `Checking cluster [%s] compatibility before registering podsecuritypolicy controllers.`, insert cluster name or search for a substring of this message. Then ensure there is a message similar to `will not register podsecuritypolicy controllers for cluster`. This means Rancher correctly refused to register these controllers, since they are not needed to be run for downstream clusters with a K8s version >=1.25.
3. Ensure there are no PSP-related errors in the logs.

### Scenario 2
1. Provision a new downstream cluster with K8s v1.24.
2. When the cluster is up, search Rancher logs in the local cluster for messages that pertain to starting PSP-related controllers in the local cluster. Specifically, `Checking cluster [%s] compatibility before registering podsecuritypolicy controllers.`, insert cluster name or search for a substring of this message. Then search for a message that confirms Rancher has successfully registered those controllers: `cluster [%s] compatibility for podsecuritypolicy controllers check succeeded.`
3. Ensure there are no PSP-related errors in the logs.

### Scenario 3 (continues from Scenario 2)
1. Now upgrade the downstream cluster to K8s v1.25.
2. Ensure there are no PSP-related errors in the logs.

**Comment by anupama2501** [comment]
Verified on v2.7-head `ec67e31`
1. Install rancher on v2.7-head
2. Create a downstream rke1 node driver 1.25 cluster 
3. Verified no errors related to psp
4. Create a downstream rke2 custom hardened 1.24 cluster 
5. Verified the following errors were seen in the rancher pod logs:
```
Checking cluster `c-id` compatibility before registering podsecuritypolicy controllers.
```
6. Disabled psp from rke2 custom cluster from yaml and setting the profile to None and `protect-kernel-defaults: false`
7. Upgraded the cluster from 1.24 to 1.25 and verified no psp related errors were seen in the rancher logs.

Verified upgrade from v2.7.0 to v2.7-head `ec67e31`
1. Install rancher on v2.7.0
2. Created a downstream rke1 node driver 1.24 non-hardened cluster and 1.24 rke2 hardened cluster
3. Upgraded rancher server to v2.7-head
4. Repeated steps 3 through 5 and verified no psp related errors were seen in the rancher pod logs.
