### ISSUE TITLE
[Forwardport] v2.7: After -- upgrade, high CPU/load on nodes and database, nodes flapping between ready/unready, excessive "refresh processing" logs

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#39888]
**Original Issue:**
https://github.com/rancher/rancher/issues/39401

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment


| Component                        | Version / Type                           |
| -------------------------------- | ---------------------------------------- |
| Rancher version                  | 2.6.9                                    |
| Installation option              | Helm (high availability)                 |
| RKE binary version used          | v1.3.15                                  |
| If Helm Chart k8s cluster        | v1.24.4                                  |
| Cert Details                     | Let's Encrypt / `nginx`                  |
| Docker version                   | 20.10.7, build f0df350                   |
| Helm version                     | v2.16.8-rancher2                         |
| Downstream cluster type          | n/a                                      |
| Downstream K8s version           | n/a                                      |
| Authentication providers enabled | local                                    |
| Logged in user role              | Admin, Standard User                     |
| Browser type                     | Google Chrome                            |
| Browser version                  | 108.0.5359.124 (Official Build) (x86_64) |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

```shell
#!/bin/sh

helm repo update

kubectl create namespace cattle-system

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml

helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1


helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR  \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```


</details>


## Reproduction steps

1. Create a k8s cluster for rancher HA. Ensure that there are 3 nodes, RKE, each node all roles, (`m5.4xlarge` in `AWS ec2`) was used in testing
2. Install rancher 2.6.9. Complete basic setup (provide bootstrap, set new password).
3. Create 6,000 tokens (script available). Tokens are used to slow down the refresh process slightly since the local provider is being used (which can complete refresh quicker than other providers)
4. Create 700 users and user attributes (script available). Ensure that the user attributes are sufficiently large (I used large annotations to achieve this)
5. Upgrade rancher to 2.7.0 (I used a helm upgrade command, see below)
6. Wait and observe etcd memory usage, you will run out of memory soon (you can also increase log verbosity to observe the constant user refresh messages in the logs)


```shell
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR  \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```

## Additional Info

## RESULTS

#### ✅ Expected

To be able to upgrade without the etcd memory usage erroring out

#### ❌ Actual

etcd memory usage ran out shortly after upgrade ~5 minutes. Getting the warning `alarm:NOSPACE`. And memory went from `249 MB` to ==> `2.2 GB`
 
<hr>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-65089ee0b7369e0d189d9f0c8da7f501b9e672ca-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/65089ee0b7369e0d189d9f0c8da7f501b9e672ca |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.3.15                                                                            |
| If Helm Chart k8s cluster        | v1.24.4                                                                            |
| Cert Details                     | Let's Encrypt / `nginx`                                                            |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | n/a                                                                                |
| Downstream K8s version           | n/a                                                                                |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | Admin, Standard User                                                               |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 108.0.5359.124 (Official Build) (x86_64)                                           |


<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

```shell
#!/bin/sh

helm repo update

kubectl create namespace cattle-system

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml

helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1


helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```

</details>

## Validation steps

1. Create a k8s cluster for rancher HA. Ensure that there are 3 nodes, RKE, each node all roles, (`m5.4xlarge` in `AWS ec2`) was used in testing
2. Install rancher 2.6.9. Complete basic setup (provide bootstrap, set new password).
3. Create 6,000 tokens (script available). Tokens are used to slow down the refresh process slightly since the local provider is being used (which can complete refresh quicker than other providers)
4. Create 700 users and user attributes (script available). Ensure that the user attributes are sufficiently large (I used large annotations to achieve this)
5. Upgrade rancher to 🚨 `v2.7-head` (I used a helm upgrade command, see below)
6. Wait and observe etcd memory usage


```shell
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=$IMAGE_TAG \
  --version $VERSION
```

## Additional Info

## RESULTS

#### ✅ Expected

To be able to upgrade without the etcd memory usage erroring out

#### ✅ Actual

Was able to upgrade without any errors from etcd memory, usage stayed at `~249 MB` before and after upgrade

**Comment by rmweir** [comment]
Release note: Fixed issue where handlers involving handlers would infinitely loop if a user had no tokens or only had tokens that did not the ExtraByProvider field.
