### ISSUE TITLE
Validate CSP Adapter support for EKS 1.24

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#39882]
The CSP Adapter needs to be validated for support on EKS version 1.24, which [released last month](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-24/). The Adapter uses a service account to communicate with kubernetes, and these underwent some changes in version 1.24 (the current state can be seen in the [kubernetes docs](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token)). I do not believe that we will need any changes to support 1.24 based on these docs, but we do need to run some basic tests to make sure. This should be done before the next 2.7 release so we can make corrections as needed.

**Comment by maxsokolovsky** [comment]
## Overview
This is a research ticket whose aim is to instill confidence in that we don't need to adjust anything in light of upstream Kubernetes behavior changes around service account tokens in v1.24.

I've read a few docs pages and blog posts. I believe we don't need to do anything. There is no need to manually create a long-lived token via a secret associated with the css-adapter's service account. This is because new Kubernetes v1.24 setups will automatically create a short-lived token (without creating a secret associated with a given service account), mount it into the container and take care to refresh it as needed. Specifically, this article mentions this twice: https://medium.com/geekculture/k8s-serviceaccount-token-313d62aee119.

If people upgrade a v1.23 cluster running Rancher and csp-adapter to v1.24, then existing long-lived secrets will remain in the cluster and mounted in running containers, so the cluster upgrade should not break anything. Only new deployments of the csp-adapter will be accompanied by the new default behavior described above where Kubernetes will automatically generate a short-lived token and keep it refreshed periodically without outside action.

### Sources
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#serviceaccount-admission-controller-migration - this seems to be for the developers of Kubernetes where they discuss what needs to be done to enable this automatic refresh of short-lived tokens generated by Kubernetes when a pod starts.

https://medium.com/@th3b3ginn3r/understanding-service-accounts-in-kubernetes-e9d2abe19df8

@MbolotSuse also had dev-validated this by running Rancher with the csp-adapter on EKS v1.24 without problems.

**Comment by maxsokolovsky** [comment]
Looked at EKS docs here: https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html.
Service account tokens have an expiration of one hour.
It appears EKS has been using short-lived tokens before v1.24. Regardless, it automatically refreshes tokens within the required timeframe for client-go versions above `0.15.7`. The adapter uses a much later version.

Ran another test using EKS v1.24, Rancher v2.6.9 and csp-adapter 2.0.0.
The adapter has been running for over two hours. There have been no pod restarts, no messages in the logs beyond initial startup.
The adapter reacted to my adding and removing downstream clusters - the supportconfig had the correct number of required licenses.

We can close this card, since I haven't seen any behavior that suggests we need to adjust anything in the adapter (for example, explicitly create a secret with a long-living token associated with the service account) for EKS v1.24+ with regard to secret account tokens.
