### ISSUE TITLE
[RFE] Is there a way to learn steve?

### ISSUE THREAD

**Issue by gewei2000** [rancher/rancher#39933]
Is there a way to learn steve?

**Comment by cmurphy** [comment]
Hi @gewei2000, we're working on adding some developer documentation for steve, we're tracking that initiative in https://github.com/rancher/rancher/issues/38593. We're hoping to have those ready soon.

What are your intending to use steve for? Please be aware that we're not able to make any stability guarantees on it yet, so it could change at any moment to suit Rancher's needs, but we're interested to know how people want to use it so that we're aware of how changes may affect others and so we can potentially work toward a stable, shareable framework.

**Comment by gewei2000** [comment]
> Hi @gewei2000, we're working on adding some developer documentation for steve, we're tracking that initiative in #38593. We're hoping to have those ready soon.
> 
> What are your intending to use steve for? Please be aware that we're not able to make any stability guarantees on it yet, so it could change at any moment to suit Rancher's needs, but we're interested to know how people want to use it so that we're aware of how changes may affect others and so we can potentially work toward a stable, shareable framework.

rancher code is too large. I want to study how steve works and how to write k8s controller

**Comment by cmurphy** [comment]
We implement controllers using [wrangler](https://github.com/rancher/wrangler) and [lasso](https://github.com/rancher/lasso). Steve might have some examples of how we use them but they're not very well explained. Keep an eye on https://github.com/rancher/rancher/issues/38593 for news on new documentation for these frameworks. You could also check out [kubebuilder](https://book.kubebuilder.io/) for a great tutorial on controller-runtime-based k8s controllers.
