### ISSUE TITLE
[CSP]  Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#39940]
Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

Capabilities check for Helm

{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating:

CSP Adapter (has PSPs in the upstream )
If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by samjustus** [comment]
Parent epic
https://github.com/rancher/rancher/issues/39366

**Comment by cmurphy** [comment]
The csp-adapter chart does not deploy any PSPs so no changes are needed.

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type           |
| -------------------------------- | ------------------------ |
| Rancher version                  | 2.7.2-rc1                |
| Installation option              | Helm (high availability) |
| RKE binary version used          | v1.4.3-rc2               |
| If Helm Chart k8s cluster        | v1.25.5                  |
| Cert Details                     | Let's Encrypt / `nginx`  |
| Docker version                   | 20.10.7, build f0df350   |
| Helm version                     | v2.16.8-rancher2         |
| Downstream cluster type          | not applicable           |
| Downstream K8s version           | not applicable           |
| Authentication providers enabled | local                    |
| Logged in user role              | admin                    |
| Browser type                     | google chrome            |
| Browser version                  | 109.0.5414.87 (x86_64)   |


## Validation steps

>Test case: Deploy the adapter chart into any type of 1.25 cluster. Adapter installation only checked no EKS functionality.

1. Create a Rancher server with RKE1 k8s 1.25 
2. Install the CSP Adapter into Rancher with a helm install command like the following:

```shell
helm install rancher-csp-adapter rancher-charts/rancher-csp-adapter --namespace cattle-csp-adapter-system --set aws.enabled=true --set aws.roleName=$MY_ROLE_NAME --set-string aws.accountNumber=$MY_ACC_NUM --version $CSP_ADAPTER_VERSION --set global.cattle.systemDefaultRegistry=docker.io
```

3. Verify that the csp adapter installs into Rancher with 1.25
4. Getting expected CSP adapter errors since this is a non-EKS cluster
5. `(see internal communications for additional details)`

## Additional Info

Checking that the CSP Adapter will install into a Rancher server with 1.25. Couldn't do this with EKS since 1.25 is not currently available with EKS as of 01-20-2023. 

## RESULTS

#### ✅ Expected

For the CSP Adapter to install into Rancher with errors since it's a non-EKS cluster

#### ✅ Actual

The CSP Adapter installed and is giving expected errors for being in a non-EKS cluster
