### ISSUE TITLE
vSphere CPI chart updates to upstream v1.24.3 / v1.23.3 / v1.22.7

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39968]
**Is your feature request related to a problem? Please describe.**

Upstream has released the following new vSphere CPI versions on 12/8/22:
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.24.3
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.23.3
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.22.7

**Describe the solution you'd like**

Update the chart to include these new versions

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Verify Slack hook notified about chart "release" in relevant channels
- [x] Update chart in rancher/charts
- [ ] Update chart in rancher/rke2-charts (RKE2 team)
- [ ] Updated RKE2 to consume new chart (RKE2 team)

**Comment by annablender** [comment]
## Testing template

#### Root cause

CPI upstream released new versions.

#### What was fixed, or what changes have occurred

CPI now installs version v1.24.3 https://github.com/rancher/vsphere-charts/blob/96687762c6642efc3650626a0738c8caa45ae7c3/charts/rancher-vsphere-cpi/values.yaml#L39 (or v1.23.3, 1.22.7 based on k8s version of the cluster). These releases contain secret config updates and CVE fixes.

#### Areas or cases that should be tested

* Spin up a Rancher v2.x-head instance
* Add cloud credentials, node template, spin up a vsphere 3 node downstream cluster
* Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to nodes
* Install CPI on the downstream cluster via helm
* Verify CPI deployed successfully and the kubelet removed that taint from the nodes, providerID is set
* Install CSI on the downstream cluster via helm
* Verify CSI deployed successfully
 
#### What areas could experience regressions ?
 
 vSphere CSI/CPI
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by vivek-infracloud** [comment]
- Spun up a Rancher v2.7-head and v2.6-head servers.
- Added cloud credentials, node template, spin up a vsphere 3 node downstream cluster
- Made sure the nodes have taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule`.
- Installed CPI on the downstream cluster via UI
- Verified CPI deployed successfully and the kubelet removed that taint from the nodes, providerID is set
- Installed CSI on the downstream cluster via UI
- Verified CSI deployed successfully.

On rancher v2.7-head `vsphere-cpi-cloud-controller` image version is 1.25.0
![Screenshot from 2023-01-02 14-33-17](https://user-images.githubusercontent.com/83208989/210229897-2572e32c-953a-4ced-ba3e-a0aed1f57ec2.png)

On rancher v2.6-head `vsphere-cpi-cloud-controller` image version is 1.23.0
![Screenshot from 2023-01-02 17-48-10](https://user-images.githubusercontent.com/83208989/210230238-94768b32-a04b-4f5e-a58c-6e8c90184aac.png)

**Comment by slickwarren** [comment]
@vivek-infracloud can you also do a deployment of a workload using a persistent volume as a final check for these chart updates? 

Can you also confirm that both rke1 and rke2 are working as expected?

**Comment by vivek-infracloud** [comment]
@slickwarren There is already an issue logged for RKE2 type clusters.
https://github.com/rancher/rancher/issues/39462

**Comment by vivek-infracloud** [comment]
Tested the charts again and are working as expected for the RKE1 cluster. Also deployed a workload using persistent volume and made sure working as expected.
