### ISSUE TITLE
Support the use of PSACT and explicit PSA configuration passing for RKE2/K3S 1.23 - 1.25 cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39994]
Main issue: https://github.com/rancher/rancher/issues/38701

We want to support using PSACT (Pod Security Admission Configuration Template) and explicit PSA configuration via `machineGlobalConfig.kube-apiserver-arg` in the RKE2/K3S 1.23 - 1.25 cluster downstream cluster.

**Comment by jiaqiluo** [comment]
can be validated in the lastest v2.7-head

**Comment by markusewalker** [comment]
This will be tested alongside the overall K8s 1.25 internal test plan. Once those test cases have been addressed, I'll close this issue out.

**Comment by snasovich** [comment]
This requires adding support for placing files onto nodes as part of v2prov framework. This will be worked on in parallel by @Oats87 .

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7-head

**Comment by ron1** [comment]
The Rancher v2 provisioner for RKE2 is currently creating machine provisioner jobs in the fleet-default namespace whose SecurityContext violates the Restricted PSA [here:]( https://github.com/rancher/rancher/blob/e215285980fff335697c940e7d6584564a16721d/pkg/controllers/provisioningv2/rke2/machineprovision/template.go#L215).

Since I don't see namespace fleet-default listed [here:](https://github.com/rancher/rancher/blob/e215285980fff335697c940e7d6584564a16721d/pkg/data/management/podadmissionconfigurationtemplate_data.go#L12), should I create a bug for this or should I expect namespace fleet-default to be added as another PSA exempt namespace before Rancher 2.7.2 is released?

**Comment by markusewalker** [comment]
There are some upgrade test cases in the internal test cases that @Josh-Diamond and I are looking into. Once validated, I'll share the results here and close the issue.

**Comment by markusewalker** [comment]
Validated that the basic use-cases are addressed. Sharing the applicable test cases from the internal K8s v1.25 test plan below:

*ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, provision a downstream RKE2 v1.25 node driver cluster with PSA set to `rancher-privileged`|:white_check_mark:|
|2|As a restricted user, provision a downstream RKE2 v1.25 node driver cluster with PSA set to `rancher-privileged`|:white_check_mark:|
|3|As a standard user, provision a downstream K3s v1.25 node driver cluster with PSA set to `rancher-privileged`|:white_check_mark:|
|4|As a standard user, provision a downstream RKE2 v1.24 node driver cluster with PSA set to `rancher-restricted`, upgrade cluster to v1.25|:white_check_mark:|
|5|As a standard user, provision a downstream K3s v1.24 node driver cluster with PSA set to `rancher-restricted`, upgrade cluster to v1.25|:white_check_mark:|
|6|As a standard user, provision a custom RKE2 v1.25 custom cluster with PSA set to `Default - RKE2 Embedded` with Windows worker nodes|:white_check_mark:|
|7|As a standard user, provision a custom RKE2 v1.24 custom cluster with PSA set to `rancher-restricted` with Windows worker nodes, upgrade cluster to v1.25|:white_check_mark:|
|8|As a standard user, provision a downstream K3s v1.25 node driver cluster with PSA set to custom made value `baseline`|:white_check_mark:|

**Scenario 1**
1. Navigated to Cluster Management > Create.
2. In the Security section, updated the PSA dropdown to have value `rancher-privileged`.
3. Edited as YAML and validate that `spec.defaultPodSecurityAdmissionConfigurationTemplateName` is set to `rancher-privileged`.
4. Provisioned the cluster and validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Viewed the cluster's YAML and validate that `spec.defaultPodSecurityAdmissionConfigurationTemplateName` is set to `rancher-privileged`.
6. Verified the workloads/pods in System project page are up and `Active`.
7. Created a pod with the container image `nginx:latest` and default settings in the default namespace; validated that the pod came up as `Active`.
_______
**Scenario 2**
1. Repeated scenario 1, but with a restricted user.
_____
**Scenario 3**
1. Repeated scenario 1, but used a downstream K3s v1.25 node driver cluster instead of RKE2.
________
**Scenario 4**
1. Repeated scenario 1 steps 1-6, but used the following cluster configuration instead:
     - RKE2 v1.24 node driver cluster, PSA set to `rancher-restricted`
2. Edited the cluster's configuration and upgraded the K8s version to v1.25 and keep PSA at `rancher-restricted`.
3. Validated that the upgrade was successful and that the cluster and nodes K8s version was upgraded to v1.25.
4. Viewed the cluster YAML and validate that `spec.defaultPodSecurityAdmissionTemplateName` is set to `rancher-restricted`.
5. Verified the workloads/pods in System project page are up and `Active`.
6. Created a new test namespace and ensure that it has the following PSA configurations:
```
audit → restricted
enforce → restricted
warn → restricted
```
7. Created a new pod with the container image `nginx:latest` and default settings in the test namespace; validate that the pod DOES NOT create.
______
**Scenario 5**
1. Repeated scenario 4, but using a downstream K3s v1.24 node driver instead of RKE2.
_____
**Scenario 6**
1. Navigated to Cluster Management > Create > Toggle RKE2/K3s > Custom.
2. Ensured that Pod Security Admission is selected with `Default - RKE2 Embedded`.
3. Provisioned the cluster, applied the registration command to the following cluster setup: 3 etcd, 2 cp, 3 Linux workers.
4. Validated that the cluster and nodes came up as `Active`.
5. Verified the workloads/pods in System project page are up and `Active`.
6. Created a pod with the container image `nginx:latest` and default settings in the default namespace of the cluster; validated that the pod comes up as `Active`.
7. Registered two new Windows worker nodes to the existing RKE2 custom cluster.
8. Validated that the cluster returns to Active and that the Windows worker nodes are added are `Active`.
9. Created a pod with the container image `ranchertest/mytestcontainer` and default settings in the default namespace of the cluster; validate that the pod came up as `Active`.
______
**Scenario 7**
1. Repeated scenario 7 steps 1-5, but used the following cluster configuration instead:
     - RKE2 v1.24 custom cluster, PSA set to `rancher-restricted
     - Additionally, validated that `spec.defaultPodSecurityTemplateName` was set to `rancher-restricted` in the cluster's YAML.
2. Upgraded the cluster to v1.25; validated that the cluster and nodes remain in a state of `Active` in Cluster Management and Cluster Explorer.
3. Viewed the cluster's YAML and validated the parameter `spec.defaultPodSecurityAdmissionConfigurationTemplateName` has a value of `rancher-restricted`.
4. Verified the workloads/pods in System project page are up and `Active`.
5. Created a new test namespace and ensure that it has the following PSA configurations:
```
audit → restricted
enforce → restricted
warn → restricted
```
6. Created a new pod with the container image `nginx:latest` and default settings in the test namespace; validated that the pod DOES NOT create.
_______
**Scenario 8**
1. As an admin user, created a new PSACT value named `baseline` with audit, warning and enforce levels all set to baseline.
2. Logged out and logged back in as a standard user.
3. Navigated to Cluster Management > Create > Toggle RKE2/K3s.
4. Ensured that Pod Security Admission is selected with `baseline`.
5. Provisioned the cluster and validated that the cluster and nodes come up as `Active`.
6. Viewed the cluster's YAML and validate the parameter `spec.defaultPodSecurityAdmissionConfigurationTemplateName` has a value of `baseline`.
7. Verified the workloads/pods in System project page are up and `Active`.
8. Created a new test namespace and ensure that it has the following PSA configurations:
```
audit → baseline
enforce → baseline
warn → baseline
```
9. Created a new pod with the container image nginx:latest and default settings in the test namespace; validated that the pod creates.
