### ISSUE TITLE
How to get the IP of the proxy machine to follow the host?

### ISSUE THREAD

**Issue by ranmufei** [rancher/rancher#3999]
Rancher Version:  latest

Docker Version:  latest

OS: centos7

Steps to Reproduce: 

Results: 

Expected:

I need help!
How to get the IP of the proxy machine to follow the host?
Because the host IP may not be fixed.

**Comment by sshipway** [comment]
I suggest that you use a Global load balancer that forwards to the service; then you can access it from any host.

The way we do it is to have two of our Hosts with a LB=1 label, and then set the load balancer to be global with a requirement of label LB=1.  This means that every Host with LB=1 will have an instance of the load balancer.  We then put the two LB=1 Hosts behind our F5 Hardware load balancer with a 'wildcard' rule, so that Port X on the F5 will map to port X on one of the two Hosts (with failover if one host is down).  Thus, services can be scheduled anywhere in the Environment, and the Load balancer ensures that you reach it; the F5 in our case ensures that you reach a load balancer even if a host is down.  Of course, you could use a multi-valued DNA A record instead of the F5, though you would not get failover then.

Alternatively, use a service like Router53DNS or similar (the Templates are in the Rancher catalogue) and this will update the DNS to point to whatever Host the Service instance(s) are on.

Lots of different ways to achieve the same thing - one of the reasons I like Rancher - but it should go without saying that you should pick the one of them that works best for you, rather than trying to do all of them at once...

**Comment by deniseschannon** [comment]
@ranmufei As @sshipway mentioned, there are many ways to achieve this, what I would have suggested would hav ebeen to use a service like Route53 DNS (or any of the other DNS templates) in the rancher catalog. 

Please re-open if you have a specific question for a specific method of what you are trying to achieve.

**Comment by ranmufei** [comment]
yes  it's  dns    is  OK!!!
