### ISSUE TITLE
MongoDB with Replica Set not working due to DNS issue

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#4004]
Rancher Version: v0.63.1

Docker Version: 1.10.3

OS: Ubuntu 14.04.4 LTS

Steps to Reproduce: 

1) Set up a docker compose file with some client service and mongo service (use community or library catalog image for MongoDB).  Client Service put on host A; each mongo container is put on it's own host (different from Client Service)
2) Start up stack with name **test**

Results: 

1) Client Service continuously degrades and restarts to with error
2) Logs with show an error like this (FYI - my client is a Java app using Spring Data for MongoDB):

Caused by: com.mongodb.MongoTimeoutException: Timed out after 120000 ms while waiting for a server that matches {serverSelectors=[ReadPreferenceServerSelector{readPreference=primary}, LatencyMinimizingServerSelector{acceptableLatencyDifference=15 ms}]}. Client view of cluster state is {type=ReplicaSet, servers=[{address=10.43.122.110:27017, type=ReplicaSetSecondary, averageLatency=1.8 ms, state=Connected}, {address=10.43.122.44:27017, type=ReplicaSetSecondary, averageLatency=1.6 ms, state=Connected}, **{address=test_mongo_1:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: minerva_mongo_1: unknown error}}]**

The key part is shown in bold.  The MongoDB service sets the master using the hostname and not IP (couldn't quickly figure out a way to change this with the mongo service).  The Client Service is unable to resolve **test_mongo_1**.

During execution, I brought up a shell within the Client Service and tried to ping test_mongo_1.  It responded with unknown host.  I tried other names such as test_mongo_1.rancher.internal, test_mongo_1.mongo.rancher.internal and test_mongo_1.test.mongo.rancher.internal with the same results.  

I also tried to ping b/w Mongo Containers (e.g. ping test_mongo_2 from test_mongo_1) with result of unknown host.

Pinging by IP works fine.

Answers.txt for the network agent contains correct addresses for the hosts

**Works fine (as expected) in Rancher v0.59.0**

Expected:

1) Client Service comes up and is able to communicate with Mongo

Note: 

- Tested by running the compose files using rancher-compose and from a private catalog...error exists in both deployment methods
- In attached docker-compose file, I am using a custom MongoDB image.  It works the exact same as the one in the catalog library.  I also confirmed the issue with the one in the catalog libary.
- [docker-compose-example.yml.txt](https://github.com/rancher/rancher/files/177738/docker-compose-example.yml.txt)
- [rancher-compose-example.yml.txt](https://github.com/rancher/rancher/files/177739/rancher-compose-example.yml.txt)

**Comment by alena1108** [comment]
@dsvmacdonald sorry for the trouble, we are going to deploy app from the compose files given, and see whats going on.

**Comment by alena1108** [comment]
follow up based on info provided by @dsvmacdonald:

1) mongo db containers not being able to ping each other, seem to be intermittent issue, and most likely caused by resolution happening before rancher internal-dns is configured. We are going to address it for GA.
2) client not being able to resolve mongo db containers. Happen only when mongo db is deployed in diff stack. That is due to the changes we've made to represent the container in rancher-dns config:

* in 59, it was just the container name "foo"
* in 63, it's containerName.serviceName.stackName.rancher-internal

So on 63 in order to resolve container from another stack, .serviceName should be appended to the dns request.

We've decided it would make sense for the container being globally available by its name.rancher-internal as service's container name is going to be unique anyway.

**Comment by sangeethah** [comment]
Tested with latest build from master:

We are able to resolve by container-name and <container-name>.rancher.internal  globally (with the same stack and cross stack)

**Comment by dsvmacdonald** [comment]
Sangeethah,

Does this work with just the <container-name>?  In the initial description, MongoDB is returning the Replica Set picture with master set to the host name...or <stack-name>_<container-name>_<scale_increment> .  Clients need to resolve this without "rancher.internal".

Thanks,

Dan

**Comment by vincent99** [comment]
It should in master/next release.

**Comment by sangeethah** [comment]
@dsvmacdonald , this fix is now available in rancher-server version - v1.0.0-rc1

We will be able to resolve any container by its container-name ( just by container name without rancher.internal).

**Comment by nik131186** [comment]
I am still having the same error:
2017-12-29 01:06:56.724  INFO 1 --- [nfoReplicator-0] org.mongodb.driver.cluster               : No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]}. Waiting for 30000 ms before timing out

**Comment by DeividSilva** [comment]
I am having the same related problem using rancher v1.6.12
Using rancher DNS on host <service_name>.<stack_name> it doesn't work.
Connecting using machine name or direct IP it works perfectly.
