### ISSUE TITLE
Container Scheduling rules dont always work after upgrades

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#4012]
Rancher Version:
v.59.1

Docker Version:
1.10.3

OS: 
Ubuntu

I have a set of containers with the following rules:
Container A: The host must have a container with label of service=b
Container B: The host should not have container with label of service=b

The rule for B helps prevent two of the same container on one host. 
When I do a rolling upgrade using the CLI (not an in-place upgrade), sometimes both versions of B end up on the same host, so I have one host with nothing, and another host with two B's. While this is not ideal, the real issue is that that occasionally, the host with container A, no longer has a container B, thus breaking the scheduling rule of "host MUST have a container B" It seems like the schedule rule is only applied when A goes through changes, but if B moves off the host, container A stays on the host, and doesn't move to where container B is now located.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml of your original service and new one? It would make it faster to reproduce?

It sounds like you are expecting Container A to be moved after it's been scheduled onto a host (that originally had container B) because Container B was upgraded and moved to another host. In this use case, it would not move as it was correctly scheduled onto the host (when it originally had container B). If you want the pair of containers to always be scheduled together, you should look into sidekicks. Sidekicks force services to be scheduled on hosts together. 

http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-services/#sidekick-services
http://docs.rancher.com/rancher/rancher-compose/#sidekicks

**Comment by deniseschannon** [comment]
In your example, it sounds like you have 2 hosts and service B has a scale of 2 containers. The scheduling rules indicate that you want your containers launched on a host that shouldn't have a service B container already on it. For the rolling upgrade, if both of your hosts already have a service B container, then it is technically following the scheduling rule. Since both hosts already have a service B on it, it will choose whatever host has the least amount of containers (count of all containers, not just service B). In this case, this is how you could end up with a host with both containers on it.

**Comment by nhumrich** [comment]
This all makes sense, but for A and B, a sidekick doesn't solve the use case, because I only want one A, and two of B. Is that possible with sidekicks?

**Comment by alena1108** [comment]
@nhumrich 
> For A and B, a sidekick doesn't solve the use case, because I only want one A, and two of B. Is that possible with sidekicks?

Unfortunately not. Sidekicks and a primary service share the same scale

> so I have one host with nothing, and another host with two B's.

Changing "should not" to "must not" in "The host should not have container with label of service=b" scheduling rule should fix it

> While this is not ideal, the real issue is that that occasionally, the host with container A, no longer has a container B, thus breaking the scheduling rule of "host MUST have a container B" It seems like the schedule rule is only applied when A goes through changes, but if B moves off the host, container A stays on the host, and doesn't move to where container B is now located.

To, following could solve the problem: 

* upgrade for service A should follow up service's B upgrade
* label the hosts where containers A and B are supposed to get deployed, and put the same scheduling label on both A and B, and limit the number to the B's scale. That along with Service B "The host should not have container with label of service=b" would ensure that container A would always have B deployed eventually. 

Let me know if the above helps.

**Comment by nhumrich** [comment]
Currently
> Changing "should not" to "must not" in "The host should not have container with label of service=b" scheduling rule should fix it
Doesn't work because I do the rolling upgrade, and the upgrade hangs forever because there are no hosts to put the new service on before it pulls down the old ones. 

I think I will just have to change to using the upgrade in place. Then I can use "must" and things should work ok. 
Upgrading A along with B is a possible solution. I will consider that. 
Thanks for the thoughts.
