### ISSUE TITLE
Unable to provisioning RKE2/K3s Downstream Node Driver cluster with 63 characters in the name

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#40143]
**Rancher Server Setup**
- Rancher version: `v2.7-head` (Commit ID: e54432e)
- Installation option (Docker install/Helm Chart): Helm and Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: `v1.25.5+rke2r1`, `v1.24.8+rke2r1`, `v1.23.14+rke2r1`, `v1.25.5+k3s2`, `v1.24.8+k3s1`, and `v1.23.14+k3s1`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin and Cluster Owner
  - If custom, define the set of permissions: N/A

**Describe the bug**
When attempting to provision a downstream RKE2 or K3s Node Driver Cluster with 63 characters in the name, the cluster will remain in Reconciling state without ever provisioning, and the UI gives no indication of any issue. However, the Rancher logs states `failed to sync MachineSet replicas: failed to clone bootstrap configuration for MachineSet "loremipsumdolorsitametconsectetueradipiscingelitaeneancom-c71cd-6d898ccfc8" in namespace "fleet-default": RKEBootstrap.rke.cattle.io "loremipsumdolorsitametconsectetueradipiscingelitaeneancom-4g8vg" is invalid: metadata.labels: Invalid value: "loremipsumdolorsitametconsectetueradipiscingelitaeneancom-c71cd-6d898ccfc8": must be no more than 63 characters`
 
**To Reproduce**
1. Spin up Rancher on `v2.7-head` (Commit ID: e54432e)
2. Attempt to provision an RKE2 Node Driver cluster with the Cluster name "_loremipsumdolorsitametconsectetueradipiscingelitaeneancommodo12_" 
  - (Note: This is 63 characters in length)

**Result**
The cluster will remain in Reconciling state without ever provisioning, and the UI gives no indication of any issue.

**Expected Result**
The cluster provisions successfully without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/211948925-97e8194c-1b9d-413a-9912-3b43bf4a4e8d.png)

**Rancher Logs:**
[Rancher 27head Logs.txt](https://github.com/rancher/rancher/files/10397096/Rancher.27head.Logs.txt)

**Additional context**
When following the steps to reproduce, this issue **DOES NOT REPRODUCE** on `v2.6.9` or `v2.7.0`

**Comment by HarrisonWAffel** [comment]
This issue is related to the [CAPI version bump done in preparation for 1.25 support](https://github.com/rancher/rancher/pull/39782#discussion_r1041680436). Previously Rancher was using CAPI v1.2.0, but has recently been upgraded to v1.2.7. The issue we are seeing here is actually [a bug within CAPI that was introduced in 1.2.7](https://github.com/HarrisonWAffel/cluster-api/commit/4f536d8517d8288be8cfe65dec1082b62f538196#diff-340d8c7320ace7a81632cf023a171b8d22ab2424c2dc0fd84bbd7447a15e6ee2R549-R566), and subsequently [resolved in 1.2.8](https://github.com/HarrisonWAffel/cluster-api/commit/fca87beb1b65f0724bacddfdb625faa4aeb0ebbe#diff-340d8c7320ace7a81632cf023a171b8d22ab2424c2dc0fd84bbd7447a15e6ee2R562-R567), wherein the name of a machine deployment was sync'd into the labels of the associated MachineSet. K8s object names are limited to 253 characters, but labels are limited to 63 characters, which lead to the reconciliation failures seen in this ticket. 

Bumping to CAPI v1.2.8 seems to have partially resolved this issue, but also introduces an unwanted side effect. Now, if a cluster name is 63 characters (or long enough to cause the machine deployment name to exceed 63 characters), then the cluster will provision, but an additional empty node pool will be displayed in the UI. One node pool name will equal the name shown in the Rancher UI, and the other node pool name will have a name equal to [the formatting process done within CAPI](https://github.com/HarrisonWAffel/cluster-api/commit/fca87beb1b65f0724bacddfdb625faa4aeb0ebbe#diff-b5c550be14d88018108915e97c495d5b8714be5a058efa8a8151fd5ff407dc9aR29-R45). In cases where the cluster name is short enough not to exceed 63 characters, this additional node pool will not be displayed. 

e.g. 
![Screen Shot 2023-01-25 at 2 22 37 PM](https://user-images.githubusercontent.com/25062254/214665895-a47f2802-d6fc-404d-a6b8-3f83fdcbfa8b.png)

Only the formatted node pool will contain nodes, leaving the node pool which has a name equal to what is set in the UI empty. 

I'm trying to see if using an older version of CAPI will help resolve this issue in the short term without any of the observed side effects

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: 0504ce6), I was able to successfully provision a downstream cluster using 63 characters (_z7m4p8f9j0v5g6c3w2n1k8l0x7h1y9q3u7t0r3i8o2e3a4s0d2_) without issue. Therefore I am closing this ticket as completed.

**Steps to Reproduce:**
1. Spin up a Rancher server that has CAPI `v1.2.8` embedded in it
  - (i.e. `v2.7-head` (Commit ID: 0504ce6))
2. Create a downstream RKE2 cluster that contains 63 characters in the name 
  - (e.g. _z7m4p8f9j0v5g6c3w2n1k8l0x7h1y9q3u7t0r3i8o2e3a4s0d2_)
3. Wait for the node to provision successfully

**`v2.7-head` (Commit ID: 0504ce6):**
![image](https://user-images.githubusercontent.com/13294321/217648779-cced203a-59d1-4c91-b3dd-942baad66e2b.png)
