### ISSUE TITLE
[BUG] Monitoring v2 chart fails to upgrade on a hardened K3s or RKE2 cluster

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#40299]
**Rancher Server Setup**
- Rancher version: v2.7-head
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: RKE2 v1.23(hardened) or  k3s v1.24(hardened)
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- Monitoring chart upgrade from version `101.0.0+up19.0.3` to `101.1.0+up40.1.2` fails with below error on a hardened k3s and rke2 clusters:
```
...
jobs.batch "rancher-monitoring-upgrade" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-upgrade with timeout of 10m0s
Add/Modify event for rancher-monitoring-upgrade: ADDED
rancher-monitoring-upgrade: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-upgrade: MODIFIED
rancher-monitoring-upgrade: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Starting delete for "rancher-monitoring-upgrade" Job
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
```
- Note: Found this issue while validating : https://github.com/rancher/rancher/issues/37778#issuecomment-1401825636

**To Reproduce**

- Create a rancher v2.7-head server
- Provision a k3s v1.24 hardened cluster(1-cp, 1-e, 3-w) or create a RKE2 v1.23 hardened cluster(1-cp, 1-e, 3-w)
- Install monitoring v2 chart `101.0.0+up19.0.3`. It installs successfully.
- Upgrade the chart to version `101.1.0+up40.1.2` and observe that it fails with the error mentioned below.

**Result**
- Charts upgrade fails with error:
```
...
jobs.batch "rancher-monitoring-upgrade" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-upgrade with timeout of 10m0s
Add/Modify event for rancher-monitoring-upgrade: ADDED
rancher-monitoring-upgrade: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-upgrade: MODIFIED
rancher-monitoring-upgrade: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Starting delete for "rancher-monitoring-upgrade" Job
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
```

**Expected Result**

- Chart should upgrade successfully.

**Additional context**

https://github.com/rancher/rancher/issues/37778

**Comment by aiyengar2** [comment]
@rishabhmsra do we have any information on what logs the rancher-monitoring-upgrade Job was showing when the failure happened? Also, we should test this on the latest Monitoring chart (102.0.0) since 101.1.0 will never be released.

It's possible this could be because of buggy code w.r.t. choosing to deploy PSPs that has since been modified, but it's hard to tell with only the information that the Helm operation timed out. We'd need information about the state of the Pod that Helm was waiting on (such as if there was an ImagePullBackoff, an error in the logs, etc.) to fully debug.

**Comment by aiyengar2** [comment]
I checked this out with the latest Monitoring chart (`102.0.0+up40.1.2`). 

This specific bug does not seem to exist in the latest chart as long as you make sure you set `global.cattle.psp.enabled=true` (which is required for hardened cluster upgrades as of https://github.com/rancher/rancher/issues/40331, since our default behavior across all new charts now is to remove PSPs).

**Comment by aiyengar2** [comment]
I do, however, see other issues outside of upgrades in an RKE 1.23.16 cluster. Namely:
- Targets are down (the non-PushProx deployments
<img width="1792" alt="Screenshot 2023-02-09 at 1 07 12 PM" src="https://user-images.githubusercontent.com/13127443/217939255-a81dabea-b5dc-4484-b48c-09814d848576.png">
- The Grafana home dashboard is missing data (seems like it could be because node-exporter isn't around?)
<img width="1723" alt="Screenshot 2023-02-09 at 1 07 45 PM" src="https://user-images.githubusercontent.com/13127443/217939383-6b9dbca1-96d3-4639-b018-59b4b45a8d53.png">
<img width="1559" alt="Screenshot 2023-02-09 at 1 13 36 PM" src="https://user-images.githubusercontent.com/13127443/217940585-fa5c8960-788e-4a4a-8c01-c35c64ee97c5.png">

But I'm not sure if that's related to my dev setup or a general issue.

Moving this specific issue back to test.

cc: @ronhorton

**Comment by rishabhmsra** [comment]
Re-opening the issue

Validated on rancher v2.7-head(96097e8):
- Created hardened RKE2 `v1.23.16+rke2r1` and hardened k3s `v1.24.10+k3s1` clusters (1-cp, 1-etcd, 3-w)
- Installed Monitoring chart version `101.0.0+up19.0.3` on both the clusters.
- Upgraded the chart to version `102.0.0+up40.1.2` by setting `global.cattle.psp.enabled=true`. Chart upgraded succesfully.
- Also validated the Targets as mentioned [here](https://github.com/rancher/rancher/issues/40299#issuecomment-1424850006).  There were no Unhealthy targets on both the clusters:

![up](https://user-images.githubusercontent.com/36376154/218084902-06f4e62b-abc5-495b-9a29-e17d0c1db14b.png)

- However as mentioned [here](https://github.com/rancher/rancher/issues/40299#issuecomment-1424850006), Grafana dashboard is not showing data. `rancher-monitoring-prometheus-node-exporter` is erring out:

![ds](https://user-images.githubusercontent.com/36376154/218085746-ae3afa12-ef88-4193-974b-5ed3bbdf6ef9.png)

**Comment by aiyengar2** [comment]
Fixed the issue in the latest PR. Thanks for catching this @rishabhmsra!

**Comment by vivek-infracloud** [comment]
Validated the issue on rancher `v2.7-head` with `rancher-monitoring-prometheus-node-exporter` pod as mentioned [here](https://github.com/rancher/rancher/issues/40299#issuecomment-1425709485).

The `rancher-monitoring-prometheus-node-exporter` pod is working as expected and also the monitoring chart upgrade was successful.

Hence, closing the issue.
