### ISSUE TITLE
Update Rancher's default restricted PSACT to support RKE2 profile cis-1.23

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#40306]
**Background**
Rancher allows users to set the `profile` when creating an RKE2 custom cluster. 
When the REK2 cluster version is 1.25, and the profile is set as `cis-1.23`, the RKE2 engine will configure the cluster to use RKE2-builtin [restricted PSA config file](https://github.com/rancher/rke2/blob/0ab4614b13daa5a49e484249a49012918d46ed22/pkg/rke2/psa.go#L40-L60).  

**Problem**
The problem is that the config file does not include rancher's namespaces in its exception list, so Rancher's components can not be deployed into the cluster. Therefore, cluster provision will fail. 

**Solution**
To make the cluster work, we need to do the following:
1. add RKE2's namespaces to the exception list in Rancher's default `restricted` PSACT 
2. When the REK2 cluster version is 1.25, and the profile is set as `cis-1.23`, set the option `pod-security-admission-config-file` with the PSA config file generated from the Rancher's default `restricted` PSACT.  

Note:
We have two ways to overwrite the PSA config file: setting the`pod-security-admission-config-file` option, or the `kube-apiserver-arg` option.  The final implementation will be one of those.

**Comment by jiaqiluo** [comment]
can be validated in the latest 2.7-head

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 v1.25 custom cluster with CIS 1.23, validate cluster and nodes are `Active`|
|2|As a standard user, provision a downstream RKE2 v1.24 custom cluster with CIS 1.6, validate cluster and nodes are `Active`, upgrade cluster to v1.25 and CIS to 1.23, validate cluster and nodes upgrade

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.7-head` https://github.com/rancher/rancher/commit/ab561bf837ca6051176bf169784edb01d9dee134.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/ab561bf837ca6051176bf169784edb01d9dee134
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 v1.25 custom cluster with CIS 1.23, validate cluster and nodes are `Active`|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 v1.24 custom cluster with CIS 1.6, validate cluster and nodes are `Active`, upgrade cluster to v1.25 and CIS to 1.23, validate cluster and nodes upgrade|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 v1.25 custom cluster with CIS 1.23.
     - Validated that `rancher-restricted` is set by default when selecting `cis-1.23`:
![image](https://user-images.githubusercontent.com/52591819/220488355-653a64a3-5837-4aac-8819-5e6bbf20bc08.png) 
2. Validated that the cluster and nodes came up as `Active`.
3. Viewed the cluster's YAML and validated that `spec.defaultPodSecurityAdmissionConfigurationTemplateName` is set to `rancher-restricted`.
4. Verified the workloads/pods in System project page are up and `Active`.
5. Created a deployment with the container image nginx:latest and default settings in the default namespace; validated that the pod errors out due to `rancher-restricted` being set.
_______
**Scenario 2**
1. As a standard user, provisioned a downstream RKE2 v1.24 custom cluster with CIS 1.6.
     - Did not set PSA and kept PSP set to `Default - RKE2 Embedded`.
2. Validated that the cluster and nodes came up as `Active`.
3. Verified the workloads/pods in System project page are up and `Active`.
4. Edited the cluster configuration to upgrade the K8s cluster to v1.25.
     - When upgrading, verified that `rancher-restricted` PSA level is set automatically when selecting `cis-1.23`:
![image](https://user-images.githubusercontent.com/52591819/220488425-cb6a55d1-538d-418f-abb7-a07f50c7c256.png) 
5. Validated that the cluster and nodes upgraded to v1.25 in Cluster Management and Cluster Explorer and are `Active`.
6. Created a pod with the container image nginx:latest and default settings in the default namespace; validated that the pod comes up as `Active`.
7. The default namespace has PSA levels set to rancher-privileged, so pods should come up Active.
