### ISSUE TITLE
[BUG] statefulset/scale is not default granted permission

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40303]
**Rancher Server Setup**
Rancher version: 2.5.8
Number of nodes: 3

Downstream Cluster:
Number of Downstream clusters: 3
Node OS: RHEL
RKE/RKE2/K3S version: RKE2 1.20.6
Kubernetes version:1.20.6

**Describe the bug**
Users granted "Manage Workload" permissions on a project cannot scale statefulsets via kubectl

Users couldn't scale statefulsets without logging into Rancher

**To Reproduce**
Grant user "Manage Workloads" on project
Attempt to scale statefulset as that user via kubectl

**Result**
Scaling fails with following error:

[koolotha@g7top ~]$ kubectl scale statefulset.apps/rhel7-deployment -n test-csm --replicas=1
Error from server (Forbidden): statefulsets.apps "rhel7-deployment" is forbidden: User "u-xl7lf" cannot patch resource "statefulsets/scale" in API group "apps" in the namespace "test-csm": RBAC: clusterrole.rbac.authorization.k8s.io "monitoring-ui-view" not found

**Expected Result**
Scaling works via kubectl with "Manage Workloads" permissions

**Additional context**
What is the workaround: Create a new RBAC role with statefulset/scale permissions
see if it's intentional to not scale statefulsets outside of the UI

**Comment by samjustus** [comment]
SURE_5161

**Comment by MbolotSuse** [comment]
The built-in role "Manage workloads" is designed to allow users to manage the various aspects of the workloads. Because of this, we should add `statefulsets/scale` permissions to the users to scale statuful sets [here](https://github.com/rancher/rancher/blob/5b42ca50475398112661c80ac2b9070d5bacfb24/pkg/data/management/role_data.go#L351). A short security review should also be done to ensure that this does not give any non-workload permissions.

**Comment by crobby** [comment]
@joesims22 

To test this:
Start up a Rancher instance (issue is 2.5, but you can certainly use something more modern, 2.7.x or 2.8.x).
Create standard user
Create a downstream cluster, project, and namespace.
Assign the user from above "manage workloads" permission in that project.
Create a statefulset inside that project/namespace.
Login as the standard user for which you have granted the manage workload permissions.
Navigate to the statefulset you created inside the project/namespace.
In the UI, there will not be any buttons to scale the statefulset.
If you try via kubectl (get a kubeconfig for the standard user):  kubectl scale statefulset.apps/<your statefulset> -n <your namespace> --replicas=1   it will fail because no RBAC exists that grants those permissions.

Upgrade to a Rancher version that includes this fix.
The upgrade will patch-up the RBAC to include permission for scaling statefulsets for the "manage workloads" role.
After upgrade, the UI should have scale buttons that will work.
Also, the kubectl command from above will also work since the RBAC now allows that operation.

Let me know if you need anything else.  Happy to walk through this with you.

**Comment by joesims22** [comment]
Validated on v2.9 id `3bea7f5b`.

Test cases that were checked:
Test case | Status
-- | --
Verify the "Manage Workloads" permission allows a user to scale a stateful set via kubectl | PASS
Verify the "Manage Workloads" permission allows a user to scale down a stateful set via kubectl | PASS
Verify the "Manage Workloads"  permission allows a user to delete a statefulset via kubectl and all pods are terminated | PASS
Verify the "Manage Workloads" permission allows a user to scale a stateful set via kubectl after upgrade | PASS
