### ISSUE TITLE
[BUG] Cannot remove etcd nodes from K3s/RKE2 clusters if the cluster is architected with split controlplane/etcd roles

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#40301]
**Rancher Server Setup**
- Rancher version: v2.6 - v2.7

**Information about the Cluster**
- Kubernetes version: K3s v1.23.6 and newer

**Describe the bug**
When working with v2prov provisioned K3s/RKE2 clusters, if nodes have dedicated (controlplane and etcd) roles, etcd nodes are unable to be removed from the cluster.

This is due to internal logic in Rancher that is designed to safely remove etcd members from the cluster before deleting their Rancher references. This logic relies on a downstream K3s/RKE2 controller to perform the actual safe removal, but in newer versions of K3s/RKE2, this controller is only supposed to run on etcd nodes, but K3s/RKE2 treat "controlplane" nodes as the only ones that can run the leader elected controllers.

**To Reproduce**
1. Create a K3s or RKE2 cluster with dedicated controlplane and etcd nodes.
2. Attempt to delete an etcd node from the cluster

**Result**
The etcd node will remain in removing state indefinitely

**Expected Result**
The etcd node should be safely removed from the etcd member list, and then be removed

**Additional context**
This was broken with K3s pull: https://github.com/k3s-io/k3s/commit/f37e7565b87d64c3bc3260e0ee11d826798eb63c#diff-a156c5f501169aed57a4f23e7c0843a25cbf9211bd6424ed8b1c80e08a3aeb6eR15-R17 where the etcd safe removal controller is no longer run on nodes that have etcd disabled. This is a catch-22, because in the case of disabled controlplane (an etcd only node), the controllers have no chance of starting (see: https://github.com/k3s-io/k3s/blob/f10af367c3c96863c081ada4018e94e085c9404d/pkg/server/server.go#L80-L88).

**Workaround**
There are two known workarounds for this issue.

Option A: Don't create controlplane-only nodes in your cluster. Every control plane node should also be an etcd node. Note that it's fully understood that this is not an ideal architecture for most large scale deployments.

Option B: Manually remove the etcd member from the etcd cluster and edit node annotations
  
1. Identify the Kubernetes node object that is stuck in deleting, and check for the existence of the following annotations:
    * For K3s:
    ```
    etcd.k3s.cattle.io/remove=true
    etcd.k3s.cattle.io/node-name=<SOME-NODE-NAME>
    ```

    * For RKE2:
    ```
    etcd.rke2.cattle.io/remove=true
    etcd.rke2.cattle.io/node-name=<SOME-NODE-NAME>
    ```
2. Add the removed node name annotation:
    * For K3s:
    ```
    etcd.k3s.io/removed-node-name=<SOME-NODE-NAME>
    ```

    * For RKE2:
    ```
    etcd.rke2.io/removed-node-name=<SOME-NODE-NAME>
    ```
3. Remove the etcd member from the etcd cluster
    * For K3s:
    1. SSH into one of the K3s etcd nodes
    2. Download etcdctl, something like:
    ```
    sudo wget https://github.com/etcd-io/etcd/releases/download/v3.5.4/etcd-v3.5.4-linux-amd64.tar.gz -O - | sudo tar -zxv -C /usr/local/bin --strip-components=1 --wildcards etcd*/etcdctl
    ```
    3. Run an etcdctl member list to identify the member you are trying to remove
    ```
    sudo etcdctl --cert /var/lib/rancher/k3s/server/tls/etcd/client.crt --key /var/lib/rancher/k3s/server/tls/etcd/client.key --cacert /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt member list
    ```
    You'll get an output similar to:
    ```
    $ sudo etcdctl --cert /var/lib/rancher/k3s/server/tls/etcd/client.crt --key /var/lib/rancher/k3s/server/tls/etcd/client.key --cacert /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt member list
    214ecca738a03133, started, ck-test-broken-etcd-9029b8c0-b7vcv-b9f525f5, https://172.16.133.179:2380, https://172.16.133.179:2379, false
    4de04219572fca90, started, ck-test-broken-etcd-9029b8c0-9llvl-8c1dbc04, https://172.16.135.133:2380, https://172.16.135.133:2379, false
    ffcffb68881b6a31, started, ck-test-broken-etcd-9029b8c0-87pkg-35e38484, https://172.16.132.16:2380, https://172.16.132.16:2379, false
    ```
    4. Remove the etcd member by ID that you are looking to remove from the cluster:
    ```
    sudo etcdctl --cert /var/lib/rancher/k3s/server/tls/etcd/client.crt --key /var/lib/rancher/k3s/server/tls/etcd/client.key --cacert /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt member remove <MEMBER-ID>
    ```
    Example would be:
    ```
    $ sudo etcdctl --cert /var/lib/rancher/k3s/server/tls/etcd/client.crt --key /var/lib/rancher/k3s/server/tls/etcd/client.key --cacert /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt member remove 214ecca738a03133
    Member 214ecca738a03133 removed from cluster e42e54eef1a052e7
    ```

    * For RKE2: 
    1. Exec a shell into an etcd static pod (preferably not the one you are trying to delete)
    2. Run an etcdctl member list to identify the member you are trying to remove
    ```
    ETCDCTL_ENDPOINTS='https://127.0.0.1:2379/' ETCDCTL_CACERT='/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt' ETCDCTL_CERT='/var/lib/rancher/rke2/server/tls/etcd/server-client.crt' ETCDCTL_KEY='/var/lib/rancher/rke2/server/tls/etcd/server-client.key' ETCDCTL_API=3 etcdctl member list
    ```
    You'll get an output similar to:
    ```
    $ ETCDCTL_ENDPOINTS='https://127.0.0.1:2379/' ETCDCTL_CACERT='/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt' ETCDCTL_CERT='/var/lib/rancher/rke2/server/tls/etcd/server-client.crt' ETCDCTL_KEY='/var/lib/rancher/rke2/server/tls/etcd/server-client.key' ETCDCTL_API=3 etcdctl member list
    17f94b9c85d35ab7, started, jhyde-rke2-test-etcd-ea19f3b6-rnjrf-bbfbaaca, https://104.131.163.170:2380/, https://104.131.163.170:2379/, false
    27758bcfda10088f, started, jhyde-rke2-test-etcd-ea19f3b6-tpjl6-f4baf34c, https://159.203.104.148:2380/, https://159.203.104.148:2379/, false
    c0d407ff2de4cbeb, started, jhyde-rke2-test-etcd-ea19f3b6-w6f95-d178dafe, https://167.71.101.43:2380/, https://167.71.101.43:2379/, false
    ```
    3. Remove the etcd member that you are looking to remove from the cluster:
    ```
    ETCDCTL_ENDPOINTS='https://127.0.0.1:2379/' ETCDCTL_CACERT='/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt' ETCDCTL_CERT='/var/lib/rancher/rke2/server/tls/etcd/server-client.crt' ETCDCTL_KEY='/var/lib/rancher/rke2/server/tls/etcd/server-client.key' ETCDCTL_API=3 etcdctl member remove <MEMBER-ID>
    ```
    Example would be:
    ```
    ETCDCTL_ENDPOINTS='https://127.0.0.1:2379/' ETCDCTL_CACERT='/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt' ETCDCTL_CERT='/var/lib/rancher/rke2/server/tls/etcd/server-client.crt' ETCDCTL_KEY='/var/lib/rancher/rke2/server/tls/etcd/server-client.key' ETCDCTL_API=3 etcdctl member remove 17f94b9c85d35ab7
    Member 17f94b9c85d35ab7 removed from cluster asf0jk2masdfokjn5
    ```

**Comment by snasovich** [comment]
This will need to be release noted for the upcoming release(s).

**Comment by Oats87** [comment]
Probably related: https://github.com/rancher/rancher/issues/38926

**Comment by snasovich** [comment]
Moving to "Blocked" as we're waiting for RKE2 release with these fixes in.

**Comment by Oats87** [comment]
From my understanding of the planner code, a user that is encountering  this specific bug should be able to work around this by simply updating their cluster to a version of K3s/RKE2 that has this change.

We first process the `bootstrap` node -- in a split controlplane/etcd node, the bootstrap node will be one of the etcd nodes. If the current bootstrap node is the node that is being deleted, we will re-elect the bootstrap node to one of the other etcd nodes, and proceed to upgrade it to the new version of K3s/RKE2. When this node is updated, it should start and become the "leader" to run the safe remove controller, as there was no existing leader before.

**Comment by Oats87** [comment]
As there is no PR on our end (other than the KDM bump, and we didn't open that KDM bump) that deals with this, I will add the test template for this here:

# Problem
Please see the original issue. The tl;dr: is that if running an older version of K3s/RKE2 on a cluster that has designated roles (separate controlplane/etcd) nodes, it is not possible to use Rancher to remove an etcd node from the cluster.

# Solution
The solution is on the K3s/RKE2 side, where they are now running the correct etcd safe removal controller to ensure that the etcd node is properly removed from the etcd cluster.

# Testing
## Engineering Testing
### Manual Testing
1. Provision a K3s/RKE2 cluster using an affected version of K3s/RKE2, with dedicated controlplane and etcd nodes. I would recommend one of the following:
```
v1.26.1+rke2r1
v1.25.6+rke2r1
v1.24.10+rke2r1
v1.23.16+rke2r1

v1.23.16+k3s1
v1.24.10+k3s1
v1.25.6+k3s1
v1.26.1+k3s1
```

2. Wait for the cluster to provision fully and become active
3. Delete one of the dedicated etcd nodes, and observe it gets stuck being deleted
4. Upgrade the cluster to one of the working versions of K3s/RKE2 that has the fix in it, I would recommend one of the following:
``` 
v1.26.2+rke2r1
v1.25.7+rke2r1
v1.24.11+rke2r1
v1.23.17+rke2r1

v1.23.17+k3s1
v1.24.11+k3s1
v1.25.7+k3s1
v1.26.2+k3s1
```
5. Observe that after the upgrade starts to occur, the node is deleted as expected

### Automated Testing
We do not have any automated testing to test this specific case, but could add it if requested. The only issue I see with adding the test case is that our provisioning tests are quite resource/time intensive and this would add to the resource requirements of the testing.
## QA Testing Considerations

### Regressions Considerations

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision an affected v1.23 downstream K3s cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.24 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|2|As a standard user, provision an affected v1.23 downstream RKE2 cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.24 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|3|As a standard user, provision an affected v1.24 downstream K3s cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.25 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|4|As a standard user, provision an affected v1.24 downstream RKE2 cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.25 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|5|As a standard user, provision an affected v1.25 downstream K3s cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.25 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|6|As a standard user, provision an affected v1.25 downstream RKE2 cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.25 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|7|Setup Rancher 2.7.1, as a standard user, provision an affected v1.23 downstream K3s cluster (3 etcd, 2 cp, 3 workers), upgrade Rancher to v2.7-head, validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.24 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|8|Setup Rancher 2.7.1, as a standard user, provision an affected v1.23 downstream RKE2 cluster (3 etcd, 2 cp, 3 workers), upgrade Rancher to v2.7-head, validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.24 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|9|Setup Rancher 2.7.1, as a standard user, provision an affected v1.24 downstream K3s cluster (3 etcd, 2 cp, 3 workers), upgrade Rancher to v2.7-head, validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.25 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|
|10|Setup Rancher 2.7.1, as a standard user, provision an affected v1.24 downstream RKE2 cluster (3 etcd, 2 cp, 3 workers), upgrade Rancher to v2.7-head, validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.25 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|

**Comment by markusewalker** [comment]
Tested this against `v2.7-head` https://github.com/rancher/rancher/commit/aa7bea9baa40eb8eb1d7166cf37e0b15aaa81ed5. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/aa7bea9baa40eb8eb1d7166cf37e0b15aaa81ed5
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision an affected v1.23 downstream custom K3s cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.24 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|:x:|
|2|As a standard user, provision an affected v1.23 downstream node driver RKE2 cluster (3 etcd, 2 cp, 3 workers),  validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.24 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|:white_check_mark:|
|3|As a standard user, provision an affected v1.23 downstream node driver RKE2 cluster (3 etcd+cp, 2 workers), validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.24 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|:white_check_mark:|
|4|As a standard, provision an affected v1.24 downstream custom RKE2 driver (3 nodes, all roles on each node), validate deleting an etcd node causes it to hang, upgrade cluster to unaffected v1.25 cluster, validate deleting an etcd node is successful, scale down an etcd node and delete an etcd node, scale up an etcd node and delete an etcd node|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, navigated to Cluster Management > Create.
2. Provisioned a downstream custom K3s v1.23.16 cluster (3 etcd, 2 cp, 3 worker).
3. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
4. Validated that all pods in the system project page are up and `Active`.
5. Navigated to Cluster Management > cluster > Machines.
6. Deleted one of the etcd nodes and took note that the node is stuck in `Deleting` state after several minutes.
7. Edited the config of the cluster and upgraded the K8s cluster to v1.24.11.
8. Validated that the cluster and nodes upgraded in Cluster Management and Cluster Explorer and went from `Updating` to `Active`.
9. Took note that the etcd node that was stuck in a `Deleting` status is officially removed once the upgrade was successful.
10. Attempted to delete one of the etcd nodes and noted that it is stuck in `Deleting` with the second etcd node stuck in `Reconciling` with message `Waiting for plan to be applied`.
11. Upgraded the cluster to v1.25.7, but still see the same behavior occurring.
_______
**Scenario 2**
1. Repeated scenario 1 stpes 1-8, but used a downstream node driver RKE2 v1.23.16 cluster instead of K3s.
     - When repeating scenario 1, step 7, I upgraded to v1.24.11+rke2r1.
2. Attempted to delete one of the etcd nodes and took note that after updating the K8s version, the etcd node was successfully deleted.
     - Waiting several minutes, a new etcd node took it's place as expected.
     - In the node provider's infrastructure page, validated that the old etcd node was cleaned up and a new node took its place.
3. In the `Machines` tab in Cluster Management, clicked the `-` icon to scale down the etcd node pool from 3 to 2; validated this was successful and only 2 etcd nodes remained.
     - Validated in the node provider's infrastructure page that there are only 2 etcd nodes present.
4. Clicked the `+` icon to scale the etcd node pool from 2 to 3; validated this was successful and 3 etcd nodes appeared.
     - Validated in the node provider's infrastructure page that there are 3 etcd nodes present.
______
**Scenario 3**
1. Repeated scenario 1 steps 1-6, but used a downstream custom v1.23.16 RKE2 cluster (3 etcd+cp, 2 worker).
2. When deleting an etcd/cp node, I noted the following:
![image](https://user-images.githubusercontent.com/52591819/228312243-71d3bbe8-abc2-4469-bce5-5be9623baf4a.png) 
     - This is stuck here and does not change state at all.
3. Edited the config of the cluster and upgraded the K8s cluster to v1.24.11.
4. After upgrading the cluster's K8s version, noted that the etcd/cp node is deleted and is replaced with a new node.
5. Attempted to delete one of the etcd nodes and validated that it was removed from Rancher.
     - Reviewing the infrastructure backend, the node was NOT removed as this is a custom cluster.
     - Compared to some of the other test cases, it took several minutes for a new etcd/cp node to be replaced.
6. In the `Machines` tab in Cluster Management, clicked the `-` icon to scale down the etcd+cp node pool from 3 to 2; validated this was successful and only 2 etcd+cp nodes remained.
     - Validated in the node provider's infrastructure page that there are only 2 etcd+cp nodes present.
7. Clicked the `+` icon to scale the etcd+cp node pool from 2 to 3; validated this was successful and 3 etcd+cp nodes appeared.
     - Validated in the node provider's infrastructure page that there are 3 etcd+cp nodes present.
________
**Scenario 4**
1. Repeated scenario 1 steps 1-6, but used a downstream custom RKE2 v1.24.10 RKE2 cluster (3 nodes, all roles)
2. Deleting one of the nodes successfully removed one of the custom cluster nodes.
     - Re-registering the custom node that was removed was able to be added back to the cluster.
3. Edited the config of the cluster and upgraded the K8s cluster to v1.24.11.
4. Validated that the cluster and nodes upgraded in Cluster Management and Cluster Explorer and went from `Updating` to `Active`.
5. Deleting one of the nodes successfully removed one of the custom cluster nodes.
6. Re-registering the custom node that was removed was able to be added back to the cluster.

**NOTES**
- Scenario 3 passes, but the behavior noted was not exactly expected. Ultimately, the workaround to upgrade to an unaffected K8s version worked, so marked as passed for that reason.
- Scenario 1 is a bit concerning. It was the only test scenario where I noted this type of behavior happening, so unsure if this is environmental or not. This needs more testing to see if that's the case, but marking as failed for now due to uncertainty.

**Comment by markusewalker** [comment]
Updated the test results after retesting scenario 1 and scenario 3 based on offline discussions. However, in retesting scenario 3 with custom clusters instead of node providers, @Oats87 noted a potential side issue with webhook. This is currently under investigation, but if needed, a separate issue will be logged as this original issue has been validated.
