### ISSUE TITLE
[BUG] ADFS user" new created Projects shown always as Project Owner "local user" not owned by ADFS user

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40304]
**Rancher Server Setup**
Rancher version: 2.6.8

**Describe the bug**
On new created Project, by the admin AD user, the Project Ownership gets always to a local user instead to OF the admin AD user.

**To Reproduce**
UI Rancher Login with AD Login "Active Directory" (1.png)
Create a new project (2.png)
Check Members of the newly created Project (3.png)
see screenshots

**Result**
The project owner is a locale user, not an AD admin user.

**Expected Result**
The project owner should be the AD admin user that created the Project

SURE_4152

**Comment by cbron** [comment]
On reviewing, it's unclear if this is team 1 or team 3. If team 3 can start researching it we can review together after.

**Comment by crobby** [comment]
I think I looked at this one back in February.  It looks like the ptrb_handler.go is choosing the local:// principal instead of the AD principal.  I had a PR that I thought might work (just tossed it up while doing triage), but I think Michael mentioned that there may be a better way to accomplish this. https://github.com/rancher/rancher/pull/39827

**Comment by nflynt** [comment]
A quick explanation of what's going on here. When an ADFS user logs into Rancher, under the hood they are assigned a principal ID from the ADFS system, but they are **also** assigned a Local ID within Rancher. That is, every user entity internally has a _list_ of principal IDs, one from each auth provider that they could potentially use to log in. For most ADFS users, the Local ID isn't active (it has no password assigned) but it is still present in the system. The admin who set up ADFS is an exception, and can somewhat uniquely log in using either method.

When a project is created, Rancher needs to defer creating the initial owner binding, so it stores the username as part of the object. Later that "reconciled" to find the appropriate user. Currently, Rancher always prefers the _Local ID_ when reconciling a user in this way, and this is what we see when re-opening the project. Strictly, this behavior is working as designed, since the Local ID points to the same user, and should grant permissions in the same way. But it does create a confusing user experience.

There are a few ways we could go about solving this. The team is currently leaning towards a somewhat larger change: we'd like to separate Local IDs and ADFS IDs entirely, so that each user has _just one_ ID within Rancher. If we do this, the reconciliation process will have no other ID to pick, and it should then consistently select the expected AFDS principal for the project owner binding.

This is a long term project, as changing the underlying auth structure has security ramifications and we'll want to be sure they are _well tested._ Once we have that in place, this and several other counter-intuitive UX behaviors will fall away. We're running through a design proposal, and I'll try to keep this ticket updated as we make progress on the issue.

**Comment by samjustus** [comment]
this is being tracked in a new feature request` PrincipalID always has local user and ADFS userId, leading to confusing UX around project permissions`
