### ISSUE TITLE
[rancher-monitoring] Cannot enable persistent storage for Prometheus and Grafana using local-path-provisioner on RKE

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40312]
### Rancher Cluster:
**Rancher version**: 2.6.4
**Number of nodes**: 3
**Node OS version**: RHEL 7.9 (Maipo)

### Downstream Cluster:
**Number of Downstream clusters**: 5
**Node OS**: RHEL 7.9 (Maipo)
**RKE/RKE2/K3S version**: rke_linux-amd64-v1.3.10
**Kubernetes version**: v1.21.12
**CNI**: default

### Issue description:
Can not provision PVC to use with monitoring of Grafana and Prometheus as options when installing from the Rancher UI (App). They are trying to 'use' local-path provisioner.
They are using Monitoring (100.1.2+up19.0.3)
They receive the following 'errors'

```
file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
```

### Business impact:
<text>

### Troubleshooting steps:
Reproduced the same 'error' in my lab.
Tried the following in
https://github.com/prometheus/prometheus/issues/5976#issuecomment-532942295
https://github.com/aws/eks-charts/issues/21

1. Deleted the current version of 'monitoring'.
1. Deleted the older versions of volume claims.
1. Confirmed using 'default' 'values'
1. Reinstalled 'monitoring'.
1. Installed 'monitoring' without volume claims and it works

### Repro steps:

1. Followed the standard DOCs at https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/guides/enable-monitoring/
1. Choose 'extra' options and use 'Persistent Storage for Prometheus' and 'Grafana' and use
1. 'Storage Class Name' = 'local-path'

### Workaround:
**Is workararound available and implemented?** YES
**What is the workaround:**
1. Do not USE 'Persistent Storage

### Actual behavior:
Setup with 'Persistent Storage' fails with 'error and monitoring is not installed and hangs.

### Expected behavior:
Setup with Persistent Storage and its monitoring is installed.

### Additional notes:
SURE-5145

**Comment by stormqueen1990** [comment]
This issue is reproducible on Rancher v2.7.0 with the local path storage provisioner with the following combinations:
- Downstream RKE cluster with CentOS nodes.
- Downstream RKE cluster with Ubuntu nodes.

It is not reproducible on Rancher v2.7.0 with the local path storage provisioner in the following combinations:
- Downstream RKE2 cluster with Ubuntu nodes.
- Downstream RKE2 cluster with CentOS nodes.
- Downstream K3S cluster with Ubuntu nodes.
- Downstream K3S cluster with CentOS nodes.

**Comment by stormqueen1990** [comment]
### Investigation outcome

**Rancher tested versions**: v2.6.10 and v2.7-head
**`rancher-monitoring` tested versions**: v101.0.0+up19.0.3 and v102.0.0+up40.1.2
**Reproducibility**: reproducible only on RKE with local-path-provisioner

After further testing and investigation, I found out this issue has been brought up before via rancher/rancher#29149 and is not tied to the chart versions or Rancher versions, but to a limitation on the use of subpath in volume mounts using host path when the kubelet is running as a container. This limitation causes the subpath mount to not have the correct permissions propagated. RKE runs the kubelet as a container, and therefore subpath with host path does not work.

On top of the containerized kubelet subpath on host path volumes issue, it also seems like the local-path-provisioner requires a name for the volume claim template when the `disableMountSubPath` option is set to `true`. When a name is not specified, provisioning will fail with either a perpetual pending state or a message saying that using selectors in the volume claim template is not supported.

I was able to make the RKE + local-path-provisioner setup work by tweaking the configuration with the addition of the following options to the `storageSpec` values:
* `volumeClaimTemplate.metadata.name`, so that a named persistent claim is created.
* `disableMountSubPath: true`, so that prometheus-operator does not create a volume mount with a subpath for the persistent volume claim.

I was able to verify that this configuration works for versions v101.0.0+up19.0.3 and v102.0.0+up40.1.2 of rancher-monitoring in Rancher v2.6.10 and v2.7-head. While this currently makes for poor user experience as no GUI options to add a name to the volume claim template or to disable subpath mounts are available, the [documentation for prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/blob/1758cd6256cd4c328ee8f74ea8866443ead6b0d8/Documentation/api.md#storagespec) does state that subpath usage will be removed in the future.

### Related issues
* rancher/rancher#29149
* rancher/local-path-provisioner#4
* rancher/rancher#14836
* kubernetes/kubernetes#61456

**Comment by MKlimuszka** [comment]
Closing this ticket because a workaround was provided above. Also, Longhorn provides a solution to this issue.
