### ISSUE TITLE
Update versions of Oracle OCI node driver and OKE cluster driver

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40324]
This issue is to track bump of OCI node driver and OKE cluster driver. Please refer to the linked PRs for the fixes/enhancements these new versions bring.

Also, be advised of the following known issue affecting OKE cluster driver update on upgrading existing Rancher installations: https://github.com/rancher/rancher/issues/38165

**Comment by slickwarren** [comment]
Test Cases:
using rancher v2.7-head
* enable OCI and OKE drivers
* deploy rke1 node driver cluster using OCI v1.24.x or above
  * ensure the cluster is able to provision, and all workloads / resources are healthy
* deploy rke2 node driver cluster using OCI v1.24.x or above
  * ensure the cluster is able to provision, and all workloads / resources are healthy
* deploy OKE cluster with 1.24.x or above
  * ensure the cluster is able to provision, and all workloads / resources are healthy

**Comment by jlamillan** [comment]
@jlamillan

**Comment by jlamillan** [comment]
FYI @deniseschannon, @slickwarren. I'm currently testing the OKE cluster driver and OCI node driver on Rancher 2.7.1 HEAD (cd8eea1fdf0dd0071bfdcae4f1eb7de2c5b3722f). Here is a developing list of issues. I will file separate issues w/ more detail later:

OKE Cluster driver:
- UI issue: OKE cluster not visible in UI during provisioning process. Strangely, it visible in old UI e.g. https://rancher/g/clusters) during that same time. OKE cluster eventually shows up in both old and new UI once it is full provisioned and active status.
- Provisioned 1.24.1 cluster otherwise healthy.


OCI node driver:
- RKE1: failed to start driver `rancher-6cc7cd7d56-drhsr rancher 2023/02/11 00:50:08 [INFO] Creating jail for c-7nxkf
rancher-6cc7cd7d56-drhsr rancher 2023/02/11 00:50:08 [INFO] [node-controller] Provisioning node allineone2
rancher-6cc7cd7d56-drhsr rancher 2023/02/11 00:50:08 [INFO] [node-controller] [cluster-id: c-7nxkf] Error starting plugin binary: open /dev/null: permission denied`
- RKE2: TBD.

**Comment by snasovich** [comment]
@jlamillan , I've just tried this on the latest v2.7-head (828fe615a30ed0302d39df1a78366ce4f4a8b381) and definitely see "Oracle OKE" option in default UI after enabling Cluster Driver:
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/85187633/218365115-15316d29-f9a6-4ca9-9a2a-0b81e8dbc051.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/85187633/218365163-f4a79715-cf4d-4cf0-89fc-bc65d624b2c1.png">

No immediate ideas on the node driver issue.

**Comment by jlamillan** [comment]
The cluster driver is visible (as you show), what's not visible is the cluster provisioned with the OKE driver. 

I.e. when you create a cluster using the driver, it doesn't show up until it reaches is fully active status, which can take five minutes or so.

**Comment by deniseschannon** [comment]
@jlamillan Can you file a ticket about the UI issue for OKE in https://github.com/rancher/dashboard? I understand what you're saying but no idea how the clusters are shown. 

cc: @pgonin for visibility as well. Cluster drivers fall under KEV2 umbrella, so this may end up being a backend issue.

**Comment by snasovich** [comment]
@jlamillan , thank you for the clarifications, my bad for misunderstanding the issue.

**Comment by jlamillan** [comment]
Issue tracking the issue where downstream OKE clusters being provisioned are not displayed in UI:
https://github.com/rancher/rancher/issues/40529

**Comment by jlamillan** [comment]
Issue tracking the failure to start OCI node driver w/ the /dev/null error: https://github.com/rancher/rancher/issues/40530

**Comment by jlamillan** [comment]
Issue tracking OCI node driver failure to provision RKE2 cluster: https://github.com/rancher/rancher/issues/40535

**Comment by jlamillan** [comment]
Issue tracking missing fields for Oracle cloud credentials: https://github.com/rancher/rancher/issues/40537

**Comment by jlamillan** [comment]
Issue tracking broken "Read from File" button in Oracle cloud credentials: https://github.com/rancher/rancher/issues/40538

**Comment by snasovich** [comment]
@jlamillan , thank you for filing these issues. Now, are these new issues due to driver version updates or are they reproducible on driver versions prior to updates applied as part of this issue?

**Comment by jlamillan** [comment]
The issues reported above all seem to be reproducible using prior versions of the drivers (I checked at least one version back). 

I'm sure the UI issues having to do with the cloud credentials pre-date 2.7. 

I could try and pinpoint the rancher server version which the node driver first started failing for RKE1 & RKE2 (/dev/null issue) if that would be helpful.
