### ISSUE TITLE
If there is url in github enterprise but checkbox is off, it will still look at enterprise site

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4045]
Version - master 3/18

Steps to Reproduce: 
1.  Go to Access Control
2.  Select GITHUB
3.  Check the Use a private GitHub Enterprise installation
4.  Enter a website into Enterprise Host field
5.  Uncheck the checkbox
6.  Enter your github credentials and click Authenticate with GitHub

Results: Won't work because even thou you unchecked "Use a Private GitHub", it's still taking the Enterprise Host into consideration.

Expected: If unchecked should ignore Enterprise Host field and the use a non-secure('http') connection checkbox

**Comment by vincent99** [comment]
- Cleaned up the display of the enterprise options
- Snazzy animation when you check the enterprise option
- Changed option to positive ("use secure") instead of not selected not not negative by default ("use insecure")
- If you paste in a URL with http:// or https://, set the secure flag appropriately
- If you turn off enterprise, clear the host and set scheme=https:// so it will go back to github

**Comment by tfiduccia** [comment]
Version - master 3/22
Verified fixed
