### ISSUE TITLE
[BUG] RoleTemplate Sync can not handle semantic differences.

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#40484]
**Rancher Server Setup**
- Rancher version: 2.7-head
- Installation option (Docker install/Helm Chart): All

**Information about the Cluster**
- Kubernetes version: All

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

If a RoleTemplate is created with an empty list rancher will create a corresponding ClusterRole with a nil list. When Rancher goes to sync RoleTemplates and ClusterRoles. It will detect that emptyList != nil list and attempt to update the clusterRole.

**To Reproduce**
1. Start Rancher Server
2. Provision a downstream cluster
3. Create a new test-user
5. Apply the following roleTemplate 
      ```yaml
      apiVersion: management.cattle.io/v3
      builtin: false
      context: project
      description: ""
      displayName: "Custom Test Role"
      external: false
      hidden: false
      kind: RoleTemplate
      metadata:
        annotations:
          cleanup.cattle.io/rtUpgradeCluster: "true"
          field.cattle.io/creatorId: user-rsld9
          lifecycle.cattle.io/create.mgmt-auth-roletemplate-lifecycle: "true"
        creationTimestamp: "2023-02-09T21:18:59Z"
        finalizers:
        - controller.cattle.io/mgmt-auth-roletemplate-lifecycle
        generateName: rt-
        generation: 2
        labels:
          cattle.io/creator: norman
        name: rt-77txz
        resourceVersion: "132861"
        uid: b3ed79fc-0468-4d26-82c2-20e5bad411a9
      rules:
      - apiGroups:
        - ""
        resourceNames: []
        resources:
        - namespaces
        verbs:
        - get
        ```
 6. Create a new project in your downstream cluster
 7. Add the test user to the project with the above `Custom Test Role`
 8. View the rancher logs
 
**Result**
Logs will print out update message
`Updating clusterRole rt-77txz because of rules difference with roleTemplate Custom Test Role (rt-77txz).` 

**Expected Result**
No log updating messages are printed out.

**Screenshots**

**Additional context**

This applies to roles as well.
SURE-5528

**Comment by jbilliau-rcd** [comment]
So initially I thought this was related to just the local Rancher cluster having `resourceNames: []` while the downstream cluster doesn't, resulting in an infinite loop of Rancher updating the downstream due to the diff. So, I `kubectl edit roletemplate` my roletemplate on my local Rancher cluster, and just removed those lines, making the yaml the exact same as the downstream.....see below for a diff in VSCode (they the exact same)

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/69006307/218282931-542e294b-ceaf-4f91-8dff-fcf1ae63a568.png">

And yet, in my Rancher logs, I keep seeing this incessantly spammed nonstop:

rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role projects-view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role rt-hc9mf
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] Creating clusterRoleBinding User u-xjwzu5uxh4 Role clusterroletemplatebindings-view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] Creating clusterRoleBinding User u-xjwzu5uxh4 Role projects-view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:33 [INFO] Creating clusterRoleBinding User u-z2ebddzx6b Role projects-view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-arboeltwsa Role view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-z2ebddzx6b Role view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-xjwzu5uxh4 Role view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-arboeltwsa Role rt-hc9mf
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role clusterroletemplatebindings-view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-z2ebddzx6b Role rt-hc9mf
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role rt-hc9mf
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-xjwzu5uxh4 Role rt-hc9mf
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-z2ebddzx6b Role clusterroletemplatebindings-view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role clusterroletemplatebindings-view
rancher-86d9d47489-vjkxd rancher 2023/02/11 21:55:34 [INFO] Creating clusterRoleBinding User u-m7wikqwffb Role projects-view

So for some reason, Rancher is never in "sync", or at least thinks it is, with the downstream. This happens on multiple roles, multiple clusters, so its not specific to any cluster or role. Running Rancher 2.6.9 on AWS EKS 1.22.

**Comment by KevinJoiner** [comment]
@jbilliau-rcd Both the generated clusterRole and role must have matching rules to the RoleTemplate.

**Comment by jbilliau-rcd** [comment]
@KevinJoiner  that's my point, they do...note the screenshot, there are no diffs at all between the local Rancher `RoleTemplate` and the child `ClusterRole` it's linked to. And yet Rancher wants to incessantly sync them nonstop anyway.

**Comment by KevinJoiner** [comment]
@jbilliau-rcd Sorry, the screenshot was only a diff between two sets of rules when there are 3 sets of rules that need to be in sync RoleTemplate, Role, and ClusterRole. I want to verify that you updated the Role rt-4wcnr as well as the ClusterRole rt-4wcnr.

**Comment by jbilliau-rcd** [comment]
Hmmmm interesting. Ok I did a `kubectl get role rt-4wcnr -n c-9s8fv -o yaml > role.yaml` and compared the *rules* to the output of `kubectl get roletemplates.management.cattle.io rt-4wcnr -o yaml > template.yaml`, both ran against the local Rancher cluster. Quite a few differences.....what doesn't make any sense to me is I don't have ANY of those *role* permissions on my custom, cluster role in Rancher....no idea where it's getting those from.

![image](https://user-images.githubusercontent.com/69006307/218516286-51297bdc-418a-4bf6-8140-c269f5c29aba.png)


I was under the impression that custom **cluster** roles in Rancher became `RoleTemplates`, and those then propagated to downstream clusters via `ClusterRoles`.....where do `Roles` fit into this equation?

Logs currently:


9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Creating clusterRoleBinding User u-xjwzu5uxh4 Role clusterroletemplatebindings-view
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Creating clusterRoleBinding User u-z2ebddzx6b Role projects-view
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Creating clusterRoleBinding User u-z2ebddzx6b Role view
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv
rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-9s8fv

**Comment by KevinJoiner** [comment]
`roles` are used for namespaced resources and `clusterRoles` are used for non namespaced resources
The code for `role` and `clusterRole` creation based on roleTemplates is here if you want to dive into what is happening behind the scenes. https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/managementuser/rbac/handler_base.go#L155

**Comment by jbilliau-rcd** [comment]
By a Rancher "cluster role", by definition, shouldn't be namespaced....it's a cluster role, right? And besides that point, why does the `Role` have completely different permissions than that are on my `RoleTemplate`? It's in sync with the `ClusterRole`, so that part is working.

It just occurred to me that in addition to my explicit role perms on my custom role, I am also having it inherit "Manage Project Members", so that cluster admins can manage RBAC for all projects on the cluster. Is that causing the "Role" to get created, on a per-namespace basis within each project? If so, that makes sense....but the perms still don't. Only permission on "Manage Project Members" is `projectroletemplatebindings`, none of this rke.cattle.io stuff.....no idea where that's coming from.

**Comment by willamg** [comment]
@jbilliau-rcd A cluster role in Rancher is meant to have a broad scope and apply across all namespaces in your cluster. The "rke.cattle.io" permissions that you're seeing may be related to the way rke uses RBAC internally. 

I would have a glance over this documentation for more information: 

https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/custom-roles

**Comment by jbilliau-rcd** [comment]
Well, I don't know what to tell you then....I can only validate:

1.) downstream `ClusterRole` and Rancher local `RoleTemplate` match

2.) Rancher local `RoleTemplate` and Rancher local `Role` (in the namespace of the cluster) do NOT match, in fact, don't look related at all. Yet they are trying to sync? See this exact log:

rancher-86d9d47489-vjkxd rancher 2023/02/13 16:23:36 [INFO] Updating role rt-4wcnr in c-9s8fv because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).

3.) Rancher is incessantly spamming syncing of roles nonstop, which, when you have a few custom roles plus 90 clusters and hundreds of projects, results in a lot of log spam, possibly even a performance hit due to all of the unnecessary kubectl commands being run non-stop.

Due to the aforementioned log, it seems like Rancher DOES expect the cluster namespace `Role` to match the `RoleTemplate`....in which case, _"The "rke.cattle.io" permissions that you're seeing may be related to the way rke uses RBAC internally."_ doesn't make any sense.....if that was the case, why is it trying to sync an "internal" role to a customer made custom role?

**Comment by raulcabello** [comment]
## Validation Template

## Root Cause
If a `RoleTemplate` is created with an empty list in any `Rule`, then rancher creates a corresponding `ClusterRole` with a nil list. When Rancher goes to sync `RoleTemplates` and `ClusterRoles` it will detect that emptyList != nil list and attempt to update the `ClusterRole`.

## What was fixed, or what change have occurred
Use apimachinery [semantic.DeepEqual()](https://github.com/kubernetes/apimachinery/blob/v0.29.2/third_party/forked/golang/reflect/deep_equal.go#L263) instead of `reflect.Equal()` to compare `Rules`. This function considers a nil list to be equal to an empty list.

## Areas or cases that should be tested
Create a `RoleTemplate` that contains a empty `resourceNames` array in any rule. Rancher should not try to reconcile, which means the following error should not appear:
```
Updating clusterRole rt-xxxx because of rules difference with roleTemplate Custom Test Role (rt-xxx).
```
See repro steps in the issue for more info.

Any other change in a `RoleTemplate` should reconcile the generated `ClusterRoles` as it was working before. For example, modifying the verbs or resources in any rule should update the generated `ClusterRole`.

## What areas could experience regressions
I would not expect any regressions since `apimachinery.DeepEqual` is like `reflect.DeepEqual`, but focused on semantic equality. This means that an empty slice is equal to a nil slice and other comparisons remains the same

**Comment by samjustus** [comment]
sure-7514
sure-5528

**Comment by joesims22** [comment]
Reproduced error on v2.7-head commit id ```bd0bb77``` and an RKE2 cluster with K8s ```v1.26.15+rke2r1```.

Observed expected error spammed in Rancher logs:
```
2024/05/13 19:22:33 [INFO] Updating clusterRole rt-56bro because of rules difference with roleTemplate Custom Test Role (rt-56bro).
``` 

Currently working on completing automation of test cases for this issue.
