### ISSUE TITLE
[BUG] ConfigMap for provisioning logs are not getting backed up by backup restore operator

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#40580]
**Rancher Server Setup**
- Rancher version: v2.7-head 1dd2af2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): aws node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

Provisioning log configmaps are created in the same namespaces as the cluster. The ~namespace~ configMap does not get backed up by backup restore operator. When the cluster is deleted, the configmap is also deleted, removing all provisioning logs. During a backup and restore migration scenario, these logs will most likely be lost as they will be deleted.

**To Reproduce**

1. Provision rke2 downstream cluster
2. Verify provisioning log configmap exists in the namespace of the provisioned cluster. This can be found in the local cluster
3. Verify the ~namespace~ configMap is not found in the backup restore operator
4. After deleting the cluster, verify that the configmap also gets deleted

**Result**
The ~namespace~ configMap is not backed up and all provisioning log is deleted

**Expected Result**

There should be a backup of the ~namespace~ configMap so when a customer wants to backup and restore, the data is preserved in the backup

**Comment by jiaqiluo** [comment]
Assuming the Mgmt cluster's name is `c-m-csvzz8gj`, the provisioning logs are saved in a `ConfigMap` named `provisioning-log` in the namespace `c-m-csvzz8gj` in the local cluster. See [code](https://github.com/rancher/rancher/blob/179c01be149f1da85d31d46049ced41a253f556c/pkg/controllers/provisioningv2/rke2/provisioninglog/provisioninglog.go#L130-L135)

The rancher-backup app's [resourceSet](https://github.com/rancher/backup-restore-operator/tree/release/v3.0/charts/rancher-backup/files/default-resourceset-contents) defines the rules for resources to be included in the backup file. 

The namespace should be in the backup file because [this rule](https://github.com/rancher/backup-restore-operator/blob/ff860d6308d5d330f401f42a80413c936bf31909/charts/rancher-backup/files/default-resourceset-contents/rancher.yaml#L1-L5) matches its name. 

The fix to this issue is to add a rule that matches the above configMap object to the rancher-backup app's [resourceSet](https://github.com/rancher/backup-restore-operator/tree/release/v3.0/charts/rancher-backup/files/default-resourceset-contents)

**Comment by jiaqiluo** [comment]
can be validated on rancher-backup chart `102.0.1+up3.1.1-rc2`

**Comment by snasovich** [comment]
@sowmyav27 @brandond , just highlighting that `team/area3` was added to the issue for the purpose of Team 3's QA to validate it since it's for backup-restore operator.

**Comment by snasovich** [comment]
Oops, wrong person tag. Tagged @brandond instead of @bmdepesa .

**Comment by nickwsuse** [comment]
`Verified on v2.7-head Commit ID: 1f014b7 && Rancher Backups v102.0.1+up3.1.1-rc6`

I followed the repro steps in the ticket and I do now see the configmap in the backup where you'd expect it to be --`configmaps.#v1/<namespace>/provisioning-log.json`

In this case, the namespace is `c-m-w8n68m6v`

![image](https://user-images.githubusercontent.com/107147272/236964153-e7776cc8-5f78-4dab-9bdf-4904c7088d55.png)

I deleted the rke2 cluster and the configmap was also deleted. I did a restore with the backup taken **_before_** I deleted the rke2 cluster and it took a very long time to complete, ~45min, but did successfully restore. 

The configmap was also restored, though naturally the cluster itself did not come back up since the cluster machines were terminated when the cluster was deleted.
