### ISSUE TITLE
[v2.7] Azure node driver rke2/k3s nodes get recreated post rancher server upgrade

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#40609]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.6.10` upgraded to `v2.6.11-rc7` and `v2.7.0` upgraded to `v2.7-head`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.24.4 `, `1.3.15`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.24.9+rke2r2`
- Cluster Type (Local/Downstream): `RKE2 node driver -  1 worker, 1 etcd, 1 cp`

**Describe the bug**
On a rancher server upgrade, azure rke2 and k3s node driver cluster nodes are re created. 

**To Reproduce**
1. Create a rancher server on v2.6.10
2. Create an azure rke2/k3s node driver cluster as a standard user with the spec mentioned in information about the cluster
3. Upgrade rancher server to v2.6.11-rc7
4. Notice the cluster goes into updating state. 

**Result**
If we check the azure portal and also from rancher cluster management page >> cluster >> machine pools, all the nodes are recreated.

**Expected Result**
Expected the nodes were not re created.

**Screenshots**
<img width="400" alt="2023-02-17_15-59-57" src="https://user-images.githubusercontent.com/38144301/219818918-ee94a29b-a5ab-4f35-92b4-5fa0ee2a3928.png">

**Additional context**
Ran a few tests as follows:
1. On an upgrade from 2.6.10 >> 2.7.0, the issue doesn't seen happening
2. On an upgrade from 2.7.0 >> 2.7-head, the issue happens on both k3s/rke2 cluster
3. The issue doesn't happen on:
    - aws node driver rke2 cluster 
    - aws node driver rke1 cluster 
    - azure node driver rke1 cluster

A related issue seen while the nodes are re created is the etcd node is stuck in reconciling/deleting state as mentioned here:
https://github.com/rancher/rancher/issues/40588

**Comment by jakefhyde** [comment]
Needs rc

**Comment by thaneunsoo** [comment]
Sending back for QA test template

**Comment by jakefhyde** [comment]
### Root cause
 
When rancher is upgraded and the embedded version of rancher machine upgrades (as well as all third party node drivers), the dynamic schema objects are regenerated (if and only if the list of available flags for that particular driver has changed). When the schema objects are regenerated, the v2 provisioning config, infrastructure machine, and infrastructure machine template CRDs are redefined which previously included defaults for these values. Once the default values were added, CAPI would recognize that the machine-template-hash for the machine templates has changed, causing the entire cluster to reprovision.

### What was fixed, or what changes have occurred

Store the machine driver's spec as a field on the machine pool.

YOU WILL NO LONGER BE ABLE TO EDIT A CLUSTER TO ENABLE NEW FEATURES AND HAVE THIS APPLY TO EXISTING MACHINE POOLS. YOU WILL NEED TO PROVISION A NEW NODE POOL, OR REMOVE THE dynamicSchemaSpec FROM THE MACHINE POOL

### Areas or cases that should be tested

Test all supported node drivers

- Updating rancher does not reprovision node pools
- Updating cluster does not reprovision node pools
Adding node pools works
- Removing dynamic schema field will cause all machines in pool to be reprovisioned if the node config has changed (i.e., if you upgraded from 2.7.1 -> this version with azure node driver).

### What areas could experience regressions?

RKE2/K3S etcd restore (should still work but I abstracted out the base64+gzip compression and decompression which is used by restore)

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 2b2ed44
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2

----------

### Testing: ###
Tested this issue with the following steps:
1. Create a rancher server on v2.7.0
2. Create an azure rke2/k3s node driver cluster as a standard user with the spec mentioned in information about the cluster
3. Upgrade rancher server to v2.7-head
4. Verify the machine pool is preserved

**Result**
After upgrading, the nodes in the machine pools were preserved
![image.png](https://zube.io/files/rancher/499e7a3ead720f00cea3bce59167d9ee-image.png)

Full test plan regarding relevant issue can be found here [40628](https://github.com/rancher/rancher/issues/40628)

**Comment by snasovich** [comment]
RELEASE NOTE PLACEHOLDER
