### ISSUE TITLE
[Task] Update Prime registry with images from 2.7 OOTB KDM release from v2.6.11 release

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40632]
We want to ensure that any images needed by 2.7 out-of-the-band (OOTB) KDM release are available in Rancher Prime registry as images are currently only published there on full Rancher release.

Now, this OOTB KDM release is corresponding to v2.6.11 full release so there is a high chance all KDM-related images will be covered by it. However, we want to ensure that.

The proposed approach is to retag the same commit used to produce the latest v2.7.x release (https://github.com/rancher/rancher/tree/v2.7.1) with a new prerelease tag `v2.7.1-kdm-2.6.11` _after_ KDM changes are merged to https://github.com/rancher/kontainer-driver-metadata/tree/release-v2.7 KDM branch. Note the prerelease tag (`kdm-2.6.11`) is chosen so that it starts with a letter and technically passes some possible semver checks like `> v2.7.1-alpha0` etc.).

This will produce a new set of `rancher-images-digests-*.txt` artifacts listing all images.
We want to then compare them with corresponding files from actual v2.7.1 release (ignoring `rancher/rancher-agent`, `rancher/rancher-runtime`, `rancher/rancher` as they will get `v2.7.1-kdm-2.6.11` tag that we don't need). 

Working with EIO, we need to update their synchronization config to ignore the `v2.7.1-kdm-2.6.11` tag, and then provide the `rancher-images-disgests-*.txt` files to them for synchronization. After doing so we need to run the standard post-synchronization checks and coordinate with QA.

Comparing the newly generated image-digest files against the 2.6.11 file is useful to ensuring the correct Kubernetes versions are shared across both tags, however due to chart changes specific to each release line we cannot reuse the 2.6.11 digest files, so 2.6.11 artifacts should be used as a reference only.

~~Then we want to ensure any new images are covered by `rancher-images-digests-*.txt` from the actual `v2.6.11` release (it's also fine to check against ones from the final v2.6.11 RC).~~

~~If any are not covered, we want to review them and likely manually push to Rancher Prime registry with help of EIO team.~~

**Comment by HarrisonWAffel** [comment]
During this process we learned a few lessons on how to do these OOB KDM registry sync operations 

1. We should only use artifacts generated for the 2.7 release line to update the registry. Each release line pulls in a different set of charts and thus has a different set of images within its image artifacts. It is temping to use already created artifacts as opposed to creating a 'fake' tag, however this will likely result in many unneeded images being synchronized and potentially some images being missed altogether.

2. When creating a 'fake' tag of Rancher in order to produce image-digest artifacts, keep in mind any additional images added to KDM/Charts since the last release (in our case, since 2.7.1). Rancher CI will fail if images are found which are not tracked in the `pkg/image/origins.go` file. In our case, we needed to create a new branch off of 2.7.1 and add an additional commit to placate the CI. This scenario only applies to OOB KDM releases for the 2.7 line, and may not always be encountered. 

3. When creating the tag for the OOB KDM update, you should notify EIO of the tag name. They will need to exclude all images containing that tag from the synchronization process as they will never be used. 

4. Images from the 2.6 release line should not be sync'd to the prime registry, however we will likely need to sync images from future release lines (such as the not-yet-created 2.8 release line). Currently, we only need to worry about 2.7.

**Comment by slickwarren** [comment]
tested on v2.7.1 prime image:
* deploy the prime image using rke version from the latest KDM -- pass
* deploy rke2 and rke1 1.24.10 clusters -- pass
* deploy rke1 and rke2 1.23.16 clusters -- pass
* double check all pods have the correct (prime) image pulled -- pass
