### ISSUE TITLE
First time going to Add Host shows blank page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4063]
Version - master 3/20

Steps to Reproduce: 
1.  Install fresh version of Rancher
2.  Create a new environment and switch to it
3.  Click on Add host from welcome page
4.  Click Ok Host URL registration page

Results: Goes to infra/hosts/add/custom, but the screen is blank

Expected: Add host should show up

**Comment by vincent99** [comment]
Will check this after the first RC

**Comment by sangeethah** [comment]
In my case , after adding the first host (Digital Ocean in my case) , I am taken to the settings page.

Steps that I did:

Auth is not enabled in the set up.
Adding host to default environment.
When I click in "Add Host"  - > i am taken to  Host URL registration page -> OK -> presented with Add Host- page , choose Digital Ocean , fill all details and click "create".
I am taken to "settings" page.

Expected Behavior:
Should be taken to Infrastructure/Host View.

**Comment by tfiduccia** [comment]
Version - master 3/23
Not fixed
I'm taken to the Settings page still.

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc4
Verified fixed
