### ISSUE TITLE
Helm Project Operator isn't aware on existing project member

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#40647]
As described in [RBAC section](https://github.com/rancher/helm-project-operator/blob/main/charts/helm-project-operator/README.md#rbac) the operator watches for changes on project member to apply RoleBindings on release namespace.
This works pretty good, but what are with existing project members if the Operator is installed afterwards? 
Workaround would be to remove member from the project list and re-add them to get permissions. 
Another workaround would be a change of the ProjectRoleTemplateBinding object for a specific user, which triggers also the Operator to do things. 
The question are:  how to handle existing user? Is there already a way in the Operator? A better workaround would be fine to handle, let's say, 2000 users in 500 projects.

thx!

**Comment by aiyengar2** [comment]
Therefore, when you create the `ProjectHelmChart` in the registration namespace, existing subjects should be handled by the logic [here](https://github.com/rancher/helm-project-operator/blob/c573121b61184b92f040a850d8e7321602ead02a/pkg/controllers/project/controller.go#L283-L291), which should pick up the subjects that need to be tracked by this ProjectHelmChart based on what is currently in the cache of the controller as described [here](https://github.com/rancher/helm-project-operator/blob/c573121b61184b92f040a850d8e7321602ead02a/pkg/controllers/project/registrationdata.go#L13-L15).

If new members are added, the resolvers [here](https://github.com/rancher/helm-project-operator/blob/c573121b61184b92f040a850d8e7321602ead02a/pkg/controllers/project/resolvers.go#L97-L166) should take care of re-enqueueing the ProjectHelmChart, which will ensures that it re-syncs the Roles / RoleBindings due to the `OnChange` operation on the ProjectHelmChart attempting to re-apply.

### Considering Race Conditions

What happens if a Role or RoleBinding is created while the ProjectHelmChart is being processed?

Since we use client-go's workqueue implementation under the hood in our controllers, we can see that this behavior is documented in the [Go docs](https://pkg.go.dev/k8s.io/client-go/util/workqueue), namely:

> Multiple consumers and producers. In particular, it is allowed for an item to be reenqueued while it is being processed.

Therefore, if we are processing the ProjectHelmChart and we re-enqueue in between, it would still result in the ProjectHelmChart's OnChange operation happening again.

However, because of:

> Stingy: a single item will not be processed multiple times concurrently, and if an item is added multiple times before it can be processed, it will only be processed once.

Even if a 100 Roles / RoleBindings are added while we are processing the ProjectHelmChart's OnChange operation, it will only trigger the OnChange operation again **once**.

**Comment by aiyengar2** [comment]
So to summarize:
- Existing project members are handled by the ProjectHelmChart `OnChange` operation since we always refer to the cached RBAC resources to figure out what the desired RBAC resources should be for the ProjectHelmChart and then apply that
- Future additions should be handled by the `OnChange` operation on the RBAC resources causing the ProjectHelmChart to get re-enqueued

Does that answer your question?
