### ISSUE TITLE
RKE2/K3s v1.24 Kubernetes versions incorrectly appear as experimental verions

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#40694]
**Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/240554b59c83b2dca36684098abc5a8e63893dde
- Browser type & version: Chrome

**Describe the bug**

On the latest `v2.6-head`, when you navigate to Cluster Management > Create for RKE2/K3s clusters, you see the following when viewing the Kubernetes versions:

![image](https://user-images.githubusercontent.com/52591819/221255335-8c91bdb7-abad-454a-ad88-a2b1b9a39ffe.png)

This is an issue as 1.24 is not supposed to be in experimental; this behavior is not see in 2.6.10, so this appears to be a regression.

**To Reproduce**

1. Navigate to Cluster Management > Create.
     - Make sure you toggle RKE2/K3s, if not already.
2. In the `Cluster Configuration` > `Basic` section, click the Kubernetes version dropdown and view that v1.24 for RKE2 and K3s appear as experimental.

**Result**
v1.24 appears as experimental for RKE2/K3s.

**Expected Result**

v1.24 should not appear as experimental for RKE2/K3s.

**Comment by snasovich** [comment]
@nwmac , thank you for looking into it.

These settings are calculated in runtime based on versions coming from KDM and unfortunately there seems to be a bug in the code where versions are sorted lexicographically as strings vs. being sorted as proper semvers so `v1.24.9+rke2r2` is seen as a higher version than `v1.24.10+rke2r1`.
Ref: https://github.com/rancher/rancher/blob/a1abea50e0f47a5e38a77c72bbab77556805c870/pkg/channelserver/channelserver.go#L188

This needs to be fixed for both `release/v2.6` and `release/v2.7` even though the immediate issue is not currently reproducible on `v2.7-head` because the default there is `v1.25.x` and the latest `x` is <9.

It's also worth noting that the ideal fix should by a hybrid of semver and lexicographic comparison in sense that for k3s / RKE2 releases metadata is used for `r2`, `r3`, ... releases that should be considered higher versions than `r1`, i.e. `v1.24.9+rke2r2` > `v1.24.9+rke2r1` and `v1.24.9+k3s2` > `v1.24.9+k3s1` (per strict semver comparisons there is no precedence in each of these pairs).
The fix to the immediate problem can be simple semver comparison though.

**Comment by jiaqiluo** [comment]
Can be validated in the lastest v2.7-head

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.6-head` https://github.com/rancher/rancher/commit/6f7aebc479d83f0b458ce5dfe59ddde8fe933155. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/6f7aebc479d83f0b458ce5dfe59ddde8fe933155
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|Validate that RKE2/K3s do not list v1.24 as an experimental Kubernetes version|:white_check_mark:|

**Scenario 1**
1. Navigated to Rancher > Cluster Management > Create.
2. Validated that v1.24 no longer shows as experimental:
![image](https://user-images.githubusercontent.com/52591819/222016365-b4bbe817-8d63-4142-a240-34fa2b939608.png)

**Comment by slickwarren** [comment]
note; this is effecting v2.7.1 but as noted above and in the last linked PR, will be fixed in the next 2.7 release of rancher
