### ISSUE TITLE
Is it possible to use GPUs?

### ISSUE THREAD

**Issue by venomone** [rancher/rancher#40692]
Hello Folks,

just a very quick questions, what might be a good point to start if I want to use Nvidia or AMD GPUs inside my containers? I'm, doing a lot of video conversion using ffmpeg together nvenc in the background to accelerate my encoding workflows.
But I never had any contact with Kubernetes + GPUs, is this working properly with rancher? Is there something I have to know?

Thanks in advance

**Comment by nobbs** [comment]
If you want to use Nvidia GPUs, take a look at the gpu-operator maintained by Nvidia, cf. [these docs](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html). It works without issues in our setup based on RHEL 8.6 and RKE1 (currently on k8s v1.21.x). 

It does not support all GPUs, I'm especially not sure if customer grade GPUs are supported, but at least most of the recent server grade Nvidia GPUs are supported. 

Not sure if there's something comparable for AMD GPUs.

**Comment by venomone** [comment]
First, thanks for your fast comment.
I'm planing to run 40xx's for ffmpeg+nvenc conversion acceleration using Rancher 2.7.x.

Are you Folks also using GPUs for the same propose?

**Comment by nobbs** [comment]
Hey, no, we do use the GPUs for AI/ML workloads and number crunching, but as long as the tool uses the CUDA toolkit there shouldn't be much of a difference in the usage. 

P.S.: I'm not affiliated with Rancher in any way, just noticed your issue while looking for something unrelated ;)

**Comment by David-VTUK** [comment]
I wrote [this](https://www.virtualthoughts.co.uk/2022/11/21/installing-using-the-nvidia-gpu-operator-in-k3s-with-rancher/) blog article which might help, it's an extensions on @nobbs comment about the GPU operator.

I had the same idea as you - I wanted to experiment with ffmpeg hardware encoding using `nvenc`, which worked well.

You can even use the monitoring stack to capture GPU metrics exposed by the GPU operator:

![image](https://user-images.githubusercontent.com/5892615/221528580-2cfd0fa4-5630-4aab-ae02-003d4ebd77d8.png)

My quick Test:

```
h264 to h265 encoding results (356MB 2K source video):

Software encoder (libx265): Elapsed Time: 544 seconds
Hardware encoder (hevc_nvenc): Elapsed Time: 22 seconds.
```

Our distributions (RKE 1/2, k3s) are CNCF  conformant distros, therefore any documentation about functionality (GPU or otherwise) that works with upstream k8s will work for Rancher deployed clusters, therefore it's not a specific functionality in Rancher, but of the k8s cluster.

Hope this helps - I'm also in the Users slack channel if you want to discuss it in more detail.

**Comment by David-VTUK** [comment]
I got a Nvidia T400 as it was the cheapest GPU I could find that was on the [official supported list](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#supported-nvidia-gpus-and-systems). However, I've seen a lot of people use desktop GPU's with success. 

I'll need to rerun my test to get the VRAM stats, iirc it wasn't much, but I was testing on a small file.

**Comment by venomone** [comment]
So with a 4090 or so I'm also able to accelerate multiple workloads at once? Im asking as im running video encoding in batches across multiple servers using celery for coordination of my jobs 👍

**Comment by David-VTUK** [comment]
If you effectively want to partition a GPU so multiple Pods can use it simultaneously, then MIG (Multi Instance GPU) is what you need to look at [Source ](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-operator-mig.html)
