### ISSUE TITLE
PSPs endpoint returns 500 if nothing is found

### ISSUE THREAD

**Issue by cnotv** [rancher/rancher#40732]
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: ?

**Information about the Cluster**
- Kubernetes version: Any
- Cluster Type (Local/Downstream): Any

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When I try to fetch the endpoint `v1/policy.podsecuritypolicies` it returns 500 if no value is found.

**To Reproduce**
- Create a cluster without PSP, e.g. K8S 1.25.x has none by default
- Make a curl request to `https://<URL>/k8s/clusters/<MGMT-Cluster-name>/v1/policy.podsecuritypolicies <-- Note that's the Management Cluster Name`

**Result**
An error 500 is returned

**Expected Result**
~An empty list is returned or at least 404, although that's not accurate and still would cause issues.~
Return resource with count 0.

**Screenshots**

**Additional context**
This has been causing issues in case of cluster editing in the UI: https://github.com/rancher/dashboard/issues/8300 .

**Comment by snasovich** [comment]
@cnotv , this endpoint simply proxies request to the downstream cluster's k8s API. If it returns 500 (which is likely while the cluster is in the early stages of provisioning), we're returning 500 as well and it is the expected behavior.
cc: @Oats87 

For the original issue, suggesting to update the behavior along the lines of suggested in https://github.com/rancher/dashboard/issues/8300#issuecomment-1453714550.
