### ISSUE TITLE
Validate and document Hardened Imported RKE2 Cluster upgrade from 1.24 to 1.25

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40738]
As part of validating support for k8s 1.25 support we want to ensure hardened imported RKE2 clusters can be upgraded from k8s <=1.24 to 1.25.

The purpose of this "task" issue is to verify/refine/document the steps outlined below. The "document" part can be done as a comment on this issue and will likely be turned into a separate documentation issue.

1. Create standalone RKE2 hardened cluster on k8s 1.24 per the existing hardening recommendations
1. Import this cluster into Rancher
1. Prepare the cluster for the upgrade. _This step definitely needs refinement!_ See the documentation for the standalone RKE2 upgrade procedure prepared per https://github.com/rancher/rke2-docs/issues/51 as a starting point. However, we need to add a configuration of cluster-level PSA similar to `rancher-restricted` PSACT to these steps as updating the namespace where SUC runs as well as other Rancher-specific namespaces may not be a feasible option (this is to be evaluated).
1. After preparing the cluster per the above, edit the cluster in Rancher UI, change k8s version to 1.25 and save the changes.
1. Ensure the cluster is upgraded successfully and is otherwise healthy

Reference "k8s 1.25 support" umbrella issue: https://github.com/rancher/rancher/issues/38701

**Comment by jiaqiluo** [comment]
Following the steps mentioned in the issue, an imported hardened rke2 cluster is upgraded from 1.24 to 1.25 and passes the cis scan. 


The rke2 cluster runs Kubernetes v1.24.10+rke2r1 with three server nodes and is configured following the instruction from [RKE2 Docs - HA](https://docs.rke2.io/install/ha); it is hardened by following [RKE2 Hardening Guide](https://docs.rke2.io/security/hardening_guide). 

The cluster is imported into rancher and upgraded to v1.25.6+rke2r1 via Rancher UI. 

 The `rancher-cis-benchmark` app version 4.0.0-rc3 is used to run the CIS scan with the profile `rke2-cis-1.23-profile-hardened`. There is no failure when the cluster version is 1.24; when the cluster version is 1.25, there are only known expected failures. 



To prepare the cluster for the upgrade, instead of following the steps in [the RKE2 docs](https://docs.rke2.io/known_issues#ingress-in-cis-mode:~:text=Upgrading%20Hardened%20Clusters%20from%20v1.24.x%20to%20v1.25.x) we need to do the following:

First, on each node, create the file `rancher-psact.yaml` at the directory `/etc/rancher/rke2`  with the following content from Rancher's builtin `rancher-restricted` PSACT.   Both the filename and the directory can be customized. 

<details>
<summary> /etc/rancher/rke2/rancher-psact.yaml </summary>

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
      - cattle-system
      - cattle-epinio-system
      - cattle-fleet-system
      - longhorn-system
      - cattle-neuvector-system
      - cattle-monitoring-system
      - rancher-alerting-drivers
      - cis-operator-system
      - cattle-csp-adapter-system
      - cattle-externalip-system
      - cattle-gatekeeper-system
      - istio-system
      - cattle-istio-system
      - cattle-logging-system
      - cattle-windows-gmsa-system
      - cattle-sriov-system
      - cattle-ui-plugin-system
      - tigera-operator
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```
</details>


Then, on each node, edit the RKE2 config file with the following two changes:
1.  switch the `profile` from `cis-1.6` to `cis-1.23` 
2. set the path for the pod security admission config file to the above file 

for example 

```
profile: "cis-1.23"
pod-security-admission-config-file: /etc/rancher/rke2/rancher-psact.yaml
```


After finishing those two steps, we can edit the cluster to upgrade the Kubernetes version in Rancher UI.

**Comment by jiaqiluo** [comment]
This is moved to to-test for QA to validate if they can upgrade the cluster with the provided steps.

Once we get the confirmation from QA, we will add those steps to rancher's documentation. 

A separate issue in the rancher-docs repo will be linked to this one.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, validated that the instructions in the RKE2 hardening guide successfully upgrades an v1.24 -> v1.25 imported RKE2 cluster|

**Comment by markusewalker** [comment]
Reopening issue as I am seeing some unexpected behavior. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/211409c9a689d8ee4d801ed1bce1d887b0fb4b00
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validated that the instructions in the RKE2 hardening guide successfully upgrades an v1.24 -> v1.25 imported RKE2 cluster|:x:

**VALIDATION STEPS**

**Scenario 1**
1. In a terminal, setup an RKE2 cluster with 3 servers, 1 worker and K8s version set at v1.24.
2. Followed the RKE2 hardening guide to ensure the cluster is hardened before importing into Rancher.
3. Navigated to Rancher > Cluster Management > Import Existing.
4. Imported my RKE2 cluster into Rancher; validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Validated that the pods in the system project page are up and `Active`.
6. Installed the CIS benchmark chart into the cluster.
7. Ran a CIS scan with the `rke2-profile-1.23-hardened` profile and validated that it passed:
![image](https://user-images.githubusercontent.com/52591819/225126003-b74520dc-1432-4e89-95bc-7f577009e723.png) 
8. Navigated back to my terminal where I created my RKE2 cluster.
9. In each node, created file `rancher-psact.yaml` at the `/etc/ranhcer/rke2` directory. The file contains the following:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
      - cattle-system
      - cattle-epinio-system
      - cattle-fleet-system
      - longhorn-system
      - cattle-neuvector-system
      - cattle-monitoring-system
      - rancher-alerting-drivers
      - cis-operator-system
      - cattle-csp-adapter-system
      - cattle-externalip-system
      - cattle-gatekeeper-system
      - istio-system
      - cattle-istio-system
      - cattle-logging-system
      - cattle-windows-gmsa-system
      - cattle-sriov-system
      - cattle-ui-plugin-system
      - tigera-operator
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```
10. In each node, ran the following commands in the `/etc/rancher/rke2` directory:
```
sed -i 's+1.6+1.23+g' config.yaml
echo 'pod-security-admission-config-file: /etc/rancher/rke2/rancher-psact.yaml' >> config.yaml
```
11. Navigated back to Rancher and upgraded the cluster from v1.24 to v1.25.
12. Noted that I am seeing the following:
![Screen Shot 2023-03-14 at 1 08 12 PM](https://user-images.githubusercontent.com/52591819/225126218-07874f8a-3837-4636-a098-8b0b49f511a1.png)
     - The upgrade never finishes and I am stuck in this state.

**Comment by markusewalker** [comment]
Spoke with @jiaqiluo offline and we narrowed down the issue I reported to be a configuration issue. I am no longer blocked and will move this back to test.

**Comment by markusewalker** [comment]
Retested and validated that this is addressed. See below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/211409c9a689d8ee4d801ed1bce1d887b0fb4b00
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validated that the instructions in the RKE2 hardening guide successfully upgrades an v1.24 -> v1.25 imported RKE2 cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. In a terminal, setup an RKE2 cluster with 3 servers, 1 worker and K8s version set at v1.24.
2. Followed the RKE2 hardening guide to ensure the cluster is hardened before importing into Rancher.
3. Navigated to Rancher > Cluster Management > Import Existing.
4. Imported my RKE2 cluster into Rancher; validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Validated that the pods in the system project page are up and `Active`.
6. Installed the CIS benchmark chart into the cluster.
7. Ran a CIS scan with the `rke2-profile-1.23-hardened` profile and validated that it passed:
![image](https://user-images.githubusercontent.com/52591819/225167962-86d60c31-d125-4c9b-bd41-022201d2a319.png) 
8. Navigated back to my terminal where I created my RKE2 cluster.
9. In each node, created file `rancher-psact.yaml` at the `/etc/ranhcer/rke2` directory. The file contains the following:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
      - cattle-system
      - cattle-epinio-system
      - cattle-fleet-system
      - longhorn-system
      - cattle-neuvector-system
      - cattle-monitoring-system
      - rancher-alerting-drivers
      - cis-operator-system
      - cattle-csp-adapter-system
      - cattle-externalip-system
      - cattle-gatekeeper-system
      - istio-system
      - cattle-istio-system
      - cattle-logging-system
      - cattle-windows-gmsa-system
      - cattle-sriov-system
      - cattle-ui-plugin-system
      - tigera-operator
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```
10. In each node, ran the following commands in the `/etc/rancher/rke2` directory:
```
sed -i 's+1.6+1.23+g' config.yaml
echo 'pod-security-admission-config-file: /etc/rancher/rke2/rancher-psact.yaml' >> config.yaml
```
11. Navigated back to Rancher and upgraded the cluster from v1.24 to v1.25.
12. Validated that the cluster and nodes upgraded to v1.25 and is in an `Active` state.
13. Validated that the pods in the system project page are up and `Active`.
14. Ran a new CIS scan and noted that it failed as expected.
15. Created a test deployment with `nginx:latest` as the container image; validated that it failed due to `rancher-restricted` being the PSACT:
![image](https://user-images.githubusercontent.com/52591819/225167930-f3b78af2-49bf-443e-9133-aeb141690573.png)
