### ISSUE TITLE
[BUG] RKE2 clusters stay in updating state post rancher backup/restore and a roll back 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#40819]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.0` upgraded to v2.7-head `e2410e` rolled back to `2.7.0`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.24.6`, `1.4.0` Hardened 
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.24.10` non-hardened RKE1 cluster and a hardened RKE2 cluster `v1.24.10+rke2r1`
- Cluster Type (Local/Downstream): `Custom  3 worker, 1 etcd, 1 cp RKE1` and `custom 1 worker, 1 cp and 1 etcd RKE2`

**Describe the bug**
On a rancher server upgrade and roll back to `2.7.0` downstream rke2 custom hardened cluster stays in updating state and never comes back to active state. Local cluster is migrated from rke1 hardened cluster to non-hardened rke1 cluster.

**To Reproduce**
1. Install rancher on version 2.7.0
2. Create a custom RKE1 and a custom hardened RKE2 cluster with the specs mentioned above.
3. Install rancher backup/restore chart version `3.0.0` in the local cluster with config set to S3
4. Take a backup from the rancher backup/restore page and the backupfile gets saved in the s3.
5. Upgrade rancher server to v2.7-head
6. Create a new rke1 standalone cluster 
7. Bring down the nodes of current rancher local cluster
8. Migrate rancher to v2.7.0 by following instructions here https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster

**Result**
RKE2 cluster stays in updating state and following error logs are seen scroll through continuously in the local cluster's rancher pods 
```

2023/03/08 17:14:14 [ERROR] error syncing 'fleet-default/custom-f9b79a917c4c': handler unmanaged-machine: the server has asked for the client to provide credentials (get nodes ip-), requeuing

Wed, Mar 8 2023 9:14:14 am | 2023/03/08 17:14:14 [ERROR] error syncing 'fleet-default/custom-313ffce15c0d': handler unmanaged-machine: the server has asked for the client to provide credentials (get nodes ip-<redacted>), requeuing
Wed, Mar 8 2023 9:14:29 am | 2023/03/08 17:14:29 [ERROR] error syncing 'fleet-default/custom-8105746b6114': handler unmanaged-machine: the server has asked for the client to provide credentials (get nodes ip-<redacted>), requeuing
Wed, Mar 8 2023 9:14:29 am | 2023/03/08 17:14:29 [ERROR] error syncing 'fleet-default/custom-f9b79a917c4c': handler unmanaged-machine: the server has asked for the client to provide credentials (get nodes ip-<redacted>, requeuing
Wed, Mar 8 2023 9:14:29 am | 2023/03/08 17:14:29 [ERROR] error syncing 'fleet-default/custom-313ffce15c0d': handler unmanaged-machine: the server has asked for the client to provide credentials (get nodes ip-<redacted>), requeuing



2023/03/08 17:50:53 [ERROR] [CAPI] error watching nodes on target cluster: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster "fleet-default/anurke2harden": the server has asked for the client to provide credentials
--
Wed, Mar 8 2023 9:50:53 am | 2023/03/08 17:50:53 [ERROR] [CAPI] Reconciler error: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster "fleet-default/anurke2harden": the server has asked for the client to provide credentials
Wed, Mar 8 2023 9:50:54 am | 2023/03/08 17:50:54 [ERROR] [CAPI] error watching nodes on target cluster: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster "fleet-default/anurke2harden": the server has asked for the client to provide credentials
Wed, Mar 8 2023 9:50:54 am | 2023/03/08 17:50:54 [ERROR] [CAPI] Reconciler error: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster "fleet-default/anurke2harden": the server has asked for the client to provide credentials



2023/03/08 17:13:18 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster c-m-s4jftrrn from cache via index: Index with name by-cluster does not exist, requeuing


Wed, Mar 8 2023 9:15:18 am | 2023/03/08 17:15:18 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster c-m-s4jftrrn from cache via index: Index with name by-cluster does not exist, requeuing
```

**Expected Result**
Expected rke2 cluster to be back active

**Additional context**
1. This issue does not happen when we backup/restore rollback on the same cluster.
2. RKE1 downstream custom cluster comes back up fine.
3. This issue is not seen happening from 2.6.10 >> 2.6.11 >> 2.6.10

**Comment by Oats87** [comment]
I took a look into the cluster in question, and see an overview of what's going on. 

Just for a recap, the way we handle a backup-restore operation in rke2/k3s requires a couple of processes to happen. Keep in mind that the `rancher-system-agent` needs to run on every node in the cluster, and it uses a service account token from the rancher local cluster to watch a secret (the plan secret) for changes. In a backup-restore operation, because we are restoring to a new K8s cluster with a (likely) different service account token signing key, we do NOT transfer the service account tokens to the new cluster. Because of this, Rancher has to regenerate a new service account/service account token for every node in the cluster, and a new service account token (by way of the Fleet manager) for the `fleet-agent`.

This leaves us in a little bit of a conundrum. We need a way to update the credentials on every node for the `rancher-system-agent` and (the downstream cluster wide) `fleet-agent`. This is done with a few components, namely Fleet and the `system-upgrade-controller`.

We rely on the Rancher `cattle-cluster-agent` to connect to the new (restored) Rancher, allowing us to update the `fleet-agent` with new credentials on the downstream cluster (via manager initiated registration). Once the cluster is available to connect to from Rancher (via the reverse proxy), Rancher and Fleet can make a connection through the manager initiated registration workflow (via a kubeconfig file that is generated by v2prov for CAPI-use). 

Once fleet is updated and able to connect to Rancher, it sees the updated Fleet bundle that deploys the rancher `system-upgrade-controller`, and a second bundle that creates a SUC `plan`. This SUC plan runs the `system-agent` install script on every node, which is where the `rancher-system-agent` token gets re-generated.



In this specific case, there was only one worker node in the cluster. This worker node went unavailable, and the `fleet-agent` was left in a `pending` state. Because of this, fleet never updated the bundle for the `system-agent` install script, which left the `rancher-system-agent` with the old (invalid) credentials, unable to apply the new plans.

**Comment by Oats87** [comment]
I'm currently waiting on a reproduction of this, as I am unable to reproduce this on my own.

**Comment by Oats87** [comment]
Looking into this issue, it appears that the `fleet-controller` managed to deliver invalid credentials to the downstream `fleet-agent`, and the `fleet-agent` was unable to register with the upstream (local) cluster. Because of this, the system-agent install plans (bundles) were never delivered.

We had a similar issue with Rancher v2prov and the kubeconfig generation mechanism, I am wondering if a similar "race condition" exists in Fleet. More investigation will need to be done.

**Comment by Oats87** [comment]
This appears to be a bug with the current `backup-restore` resourceset that is used.

The `backup-restore` operator is backing up a secret that has a name like `import-token-anurke2hard2`, where the last part is the cluster name. This secret is of type `fleet.cattle.io/cluster-registration-values`. Ordinarily, it is created through a process that comes from the `clusterregistrationtoken`, where a `clusterregistrationtoken` CR is created, and a corresponding `serviceaccount` and `secret` for the token for that service account is created. Once the service account token secret is populated, the `clusterregistrationtoken` controller creates the `import-token-<CLUSTER-NAME>` secret.

In parallel, the `import-cluster` handler that is run in the `cluster` controller sees the agent deploy generation is incremented and deploys a new iteration of the `fleet-agent`. If the `clusterregistrationtoken` controller is too slow and does not create an updated version of the `import-token-<CLUSTER-NAME>` secret, or if the `import-token-<CLUSTER-NAME>` secret is updated to the (wrong data) AFTER the `clusterregistrationtoken` controller runs, the `import-cluster` handler will deliver invalid bootstrap credentials to the downstream clusters fleet-agent and the cluster will fail to recover.

I think the best way to solve this in the long term is to exclude secrets of type `fleet.cattle.io/cluster-registration-values` from the resourceset for fleet, but this does not solve the problem for folks who have taken a backup with the resource set that is too eager.

## Workaround
Delete the corresponding `clusterregistrationtoken` CR for the cluster, and then edit the `clusters.fleet.cattle.io` for the cluster and increment the `redeployAgentGeneration` field for the cluster.

**Comment by Oats87** [comment]
@snasovich @Sahota1225 I am not sure how I should proceed on this -- should I create a PR for the `backup-restore-operator`?

Is a workaround acceptable? Or do we need to implement some type of active fix in the `backup-restore-operator`?

**Comment by raulcabello** [comment]
we also think that we should exclude the secret of type `fleet.cattle.io/cluster-registration-values` from the backup resourceset for fleet

**Comment by snasovich** [comment]
This is now much more of a backup-restore-operator issue to exclude secrets of `fleet.cattle.io/cluster-registration-values` type on backup/restore and this is being discussed with @prachidamle and @MKlimuszka .

**Comment by WeAreHadock** [comment]
Hey, I'm trying to apply the workaround as I have to restore Rancher from a backup (version `2.7.0`, backup `3.0.0`) on a new cluster. 
My RKE2 downstream clusters are stuck in Updating (same logs as above in Rancher pods on local cluster) but I don't see any `clusterregistrationtokens.fleet.cattle.io` and editing `clusters.fleet.cattle.io` doesn't solve it.

I don't see any `cluster-registration-values` secret in the tar.gz from my initial backup, neither on my other Rancher Servers (`2.7.0` with rke2 downstream too), I am missing something ?

**Comment by sowmyav27** [comment]
@nickwsuse sees an issue during backup and restore. Nick will be adding details soon
