### ISSUE TITLE
[BUG] Webhook is installed in the downstream cluster post rancher backup/restore roll back on a migrated cluster 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#40816]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.0` upgraded to v2.7-head `e2410e` rolled back to `2.7.0`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.24.6`, `1.4.0` Hardened 
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.24.10` non-hardened RKE1 cluster and a hardened RKE2 cluster `v1.24.10+rke2r1`
- Cluster Type (Local/Downstream): `Custom  3 worker, 1 etcd, 1 cp RKE1` and `custom 1 worker, 1 cp and 1 etcd RKE2`

**Describe the bug**
On a rancher server upgrade and roll back to `2.7.0` webhook version `v0.3.2-rc19` is installed in the downstream clusters. Local cluster is migrated from a hardened RKE1 to non hardened RKE1 cluster.

**To Reproduce**
1. Install rancher on version 2.7.0
2. Create a custom RKE1 and a custom hardened RKE2 cluster with the specs mentioned above.
3. Install rancher backup/restore chart version `3.0.0` in the local cluster with config set to S3
4. Take a backup from the rancher backup/restore page and the backupfile gets saved in the s3.
5. Upgrade rancher server to v2.7-head
6. Create a new rke1 standalone cluster 
7. Bring down the nodes of current rancher local cluster
8. Migrate rancher to v2.7.0 by following instructions here https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster

**Result**
Once the migration is successful, and rancher is installed if we navigate to downstream clusters, we see the webhook is installed downstream.

**Expected Result**
Webhook is not installed on downstream clusters.

**Screenshots**
<img width="500" alt="2023-03-07_22-01-02" src="https://user-images.githubusercontent.com/38144301/223757022-14412d47-9358-49a0-8bca-42b8ce35985f.png">

**Comment by MbolotSuse** [comment]
## Release Note

To enforce new security boundaries, rancher's webhook will now be installed in all downstream clusters. Users who rollback from a version of rancher >= v2.7.2 to a version < 2.7.2 will experience an issue where these webhooks will remain in downstream clusters. Since the webhook is designed to be 1-1 compatible with specific versions of rancher, this can cause unexpected behaviors to occur in downstream clusters. The rancher team has developed a [script](https://github.com/MbolotSuse/rancher-scripts/tree/main/remove-webhook) which should be used after rollback is complete (meaning after rancher version < 2.7.2 is running) to remove the webhook from the affected downstream clusters.

**Comment by anupama2501** [comment]
Verified on a migration from v2.7.0 to v2.7-head `cf555aa` back to v2.7.0 with byo-valid certs and self-signed certs helm rancher installation and docker rancher installation:
1. Install rancher on version 2.7.0
2. Create a custom RKE1 and a custom hardened RKE2 cluster with the specs mentioned above.
3. Install rancher backup/restore chart version `3.0.0` in the local cluster with config set to S3
4. Take a backup from the rancher backup/restore page and the backupfile gets saved in the s3.
5. Upgrade rancher server to v2.7-head
6. Create a new rke1 standalone cluster 
7. Bring down the nodes of current rancher local cluster
8. Migrate rancher to v2.7.0 by following instructions here https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster
9. Run the script as mentioned [here](https://github.com/rancher/rancher/issues/40816#issuecomment-1462645576).
10. Verified from downstream - imported rke1, rke2 and rke1 node driver clusters the webhook has been removed.
11. Created a 3 users and added them as cluster owner and cluster member in the downstream clusters. 
12. Verified the  user creation was successful
13. Login as the user1 - CO and verified edit on the cluster and delete cluster works as expected
14. Login as user2- CM and verified edit/delete of cluster fails as expected.

**Comment by zpavlinovic** [comment]
Sorry for a potentially silly question, but does this issue address [CVE-2023-22651](https://github.com/advisories/GHSA-6m9f-pj6w-w87g) as mentioned in the [release notes](https://github.com/rancher/rancher/releases/tag/v2.7.3)? Or perhaps some other issue is addressing that CVE?

For context, I am just looking where exactly in the rancher code the fix is located.

**Comment by macedogm** [comment]
Hi @zpavlinovic 👋🏻 We just updated the advisory [CVE-2023-22651](https://github.com/rancher/rancher/security/advisories/GHSA-6m9f-pj6w-w87g) and added a reference section with the link to the commit that fixed the CVE.

**Comment by zpavlinovic** [comment]
Thank you!
