### ISSUE TITLE
[forwardport 2.7] RKE2/K3s v1.24 Kubernetes versions incorrectly appear as experimental verions

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40828]
forward port of: https://github.com/rancher/rancher/issues/40694

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.7-head` https://github.com/rancher/rancher/commit/23074b5a970e0c982a1d6bc556eaf02982cab4cd. This issue was specifically happening in 2.6, but because there was a 2.7 corresponding PR, QA wanted to ensure we validated we still do not see the issue in 2.7. See test result details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/23074b5a970e0c982a1d6bc556eaf02982cab4cd
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|Validate that RKE2/K3s do not list v1.24 as an experimental Kubernetes version|:white_check_mark:|

**Scenario 1**
1. Navigated to Rancher > Cluster Management > Create.
2. Validated that v1.24 does not show as experimental:
![image](https://user-images.githubusercontent.com/52591819/223880570-db01cdd1-9bb2-4177-8310-fd979b447646.png)

**Comment by slickwarren** [comment]
as a follow up - also verified that when the default version is on a patch version 10+, the `experimental` label doesn't show by default: 
<img width="809" alt="Screen Shot 2023-03-08 at 4 04 10 PM" src="https://user-images.githubusercontent.com/16691014/223881066-620cbfc8-64d6-4b85-a4db-adb7b5685e58.png">
