### ISSUE TITLE
[BUG] cis chart version v4.0.0-rc3 but getting an error in one of the pods container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#40820]
**Rancher Server Setup**
- Rancher version: `2.7-head`
- Installation option (Docker install/Helm Chart): `helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rke1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.10`
- Cluster Type (Local/Downstream): `local cluster`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
on an rke1 hardened cluster, using cis chart version v4.0.0-rc3 has error in pod: 
`CreateContainerConfigError (container has runAsNonRoot and image will run as root (pod: "patch-sa-7zg6l_cis-operator-system(d3baad3b-7e74-4d78-bea2-632ac5491e05)", container: sa))`

**To Reproduce**
create hardened downstream rke1, use cis v4.0.0-rc3

**Result**
error in pod

**Expected Result**
scan runs / no errors in pod

**Screenshots**

**Additional context**
cis v3.0.0 installed fine on cluster

**Comment by doflamingo721** [comment]
@ronhorton RKE hardened cluster has restricted PSP applied as part of hardening and the cis-benchmark chart 4.0.0 has PSPs [disabled](https://github.com/rancher/charts/blob/8c110be844b640a5d7f823e4c12f2ba05167d9a2/charts/rancher-cis-benchmark/4.0.0-rc3/values.yaml#L47) by default. The error we're looking at here is occurring because of this mismatch.
Is this a valid test scenario? To have PSPs enabled on the cluster, but disabled for the chart installation?
If the same chart is installed with `global.psp.enabled=true`, on a hardened cluster it works fine, since the required cis-psp is created to support the installation.
Also the same chart installed with `global.psp.enabled=false` works fine on a non-hardened cluster, where there are no PSPs.
The only scenario which fails is when cluster has PSP enabled due to hardening and chart installation has `global.psp.enabled=false`, which is the default value in the chart.

As a workaround if we need the above scenario to work we can do either of the below: (Preferably the first option)
1. Update the rancher/kubectl image to have USER set to 65535 like we have for cis-operator image
2. Add runAsUser: 65535 to securityContext in the [sa-patch post-install job](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-cis-benchmark/4.0.0-rc3/templates/patch_default_serviceaccount.yaml) in the cis chart.
Also the reason cis-benchmark 3.0.0 is getting installed without any errors is because these chart PSP are getting applied by default.

cc: @prachidamle @MKlimuszka @mitulshah-suse

**Comment by doflamingo721** [comment]
As discussed offline, the correct way to install cis-benchmark chart on a hardened rke cluster is to install the chart by setting `global.psp.enabled` to `true`. I have raised a [ticket](https://github.com/rancher/rancher-docs/issues/495) to document this.

**Comment by MKlimuszka** [comment]
The tickets mentioned above updated the required documents. Closing.
