### ISSUE TITLE
[BUG] cis chart version v3.0.0 upgrade path is broken when user tries to upgrade to 4.00-rc3 with existing PSPs in the cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40842]
**Rancher Server Setup**
- Rancher version: v2.7-head ()
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, rke v1.4.4-rc3, hardened (local) cluster
- Proxy/Cert Details: rancher certs

**Information about the Cluster**
- Kubernetes version: v1.25.6-rancher4-1
- Cluster Type (Local/Downstream): local, hardened on 1.24, then upgraded
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: administrator (local cluster)

**Describe the bug**

when upgrading the chart (since 3.0.0 doesn't work on k8s 1.25), an error is shown to the user. Upon trying to delete the existing failed install, the user is then hit with a different error. 

**To Reproduce**

* deploy 1.24 local cluster with PSPs enabled
* depoy cis chart v3.0.0 on the local cluster
* upgrade the k8s version of the local cluster
  * do not explicitly remove PSPs from the cluster
  * add a PSA (rancher-restricted) to the cluster when upgrading
* upgrade cis chart version to be compatible with 1.25 (currently v4.0.0-rc3)

**Result**
chart fails to upgrade

**Expected Result**

chart should be upgradable to be compatible with the k8s version being tested. (see screenshot for more details)

**Screenshots**

<img width="2047" alt="Screen Shot 2023-03-09 at 10 20 57 AM" src="https://user-images.githubusercontent.com/16691014/224171386-11d94047-36cf-4d9e-adf4-50695e619b95.png">

**Additional context**

I tried manually removing the old/broken install. of cis, however then was hit with a different error. 
when removing the in
<img width="870" alt="Screen Shot 2023-03-09 at 2 10 50 PM" src="https://user-images.githubusercontent.com/16691014/224171833-b0626838-6cb4-44f2-a9fa-75a1df333259.png">
stalled apps:

and when trying to upgrade after trying to remove the apps:
<img width="2008" alt="Screen Shot 2023-03-09 at 2 09 47 PM" src="https://user-images.githubusercontent.com/16691014/224171735-33a48a6d-b4e7-406a-adfc-32d29dfeb849.png">

which I am currently unable to resolve 

* possibly related to https://github.com/rancher/rancher/issues/40820

**Comment by Josh-Diamond** [comment]
Also experienced on `v2.7-70455b151e0d90cb9e6725a27008cf92a6b4eeac-head`

With downstream hardened RKE2 k8s 1.25 cluster, CIS Benchmark 3.0.0 fails into install w/ the following error:
```logs
Error: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "cis-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"; ensure CRDs are installed first
```

Installing CIS Benchmark 2.1.0 is successful, however, the issue is seen again, when attempting to upgrade 2.1.0 => 3.0.0

**Comment by mitulshah-suse** [comment]
@slickwarren @Josh-Diamond These are not valid scenarios. This is expected behaviour. The end user is expected to remove PSPs from the chart before upgrading to 1.25. 
There is a flag provided in the values.yaml of the chart `global.psp.enabled=false` to remove the PSP before upgrading cluster to 1.25. 
All the charts will have this issue if above process is not followed, its not just the CIS chart.

cc: @stormqueen1990 @prachidamle @MKlimuszka @ronhorton

**Comment by stormqueen1990** [comment]
> @slickwarren @Josh-Diamond These are not valid scenarios. This is expected behaviour. The end user is expected to remove PSPs from the chart before upgrading to 1.25. There is a flag provided in the values.yaml of the chart `global.psp.enabled=false` to remove the PSP before upgrading cluster to 1.25. All the charts will have this issue if above process is not followed, its not just the CIS chart.
> 
> cc: @stormqueen1990 @prachidamle @MKlimuszka @ronhorton

Indeed. The issue is not directly related to Kubernetes itself, but to the fact that Helm retains the PSP information inside of the release object, then tries to reapply it on upgrade/deletion. Therefore, a user must remove the PSP objects prior to upgrading to Kubernetes v1.25.

However, this scenario is useful for testing the effectiveness of using [helm/helm-mapkubeapis](https://github.com/helm/helm-mapkubeapis) for cleaning up a Helm release when the recommended upgrade path is not followed.

**Comment by Josh-Diamond** [comment]
@mitulshah-suse @stormqueen1990 before this gets dismissed as an invalid use case, I'd just like to clarify my scenario, as it differs from Calebs.

To reproduce:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream hardened RKE2 Custom cluster w/ k8s `v1.25.6+rke2r1` configured w/ PSA to `rancher-restricted`
3. Once `active`, navigate to `Cluster Explorer > Apps > Charts > CIS Benchmark` and install `v3.0.0`
4. Reproduced

Result:
<img width="1464" alt="Screenshot 2023-03-10 at 11 33 33 AM" src="https://user-images.githubusercontent.com/46494969/224396601-2ba6b6df-bb91-4a8e-9dad-9e5052684e1d.png">

Expected Result:

CIS Benchmark 3.0.0 is successfully installed


Additional context:

There are no PSP resources in my cluster
<img width="453" alt="Screenshot 2023-03-10 at 11 34 23 AM" src="https://user-images.githubusercontent.com/46494969/224396862-bbe7c68e-4048-4b76-a1f3-de0c427a1a44.png">

---

CIS Benchmark 2.1.0 is able to be successfully installed, however when attempting to upgrade the chart to 3.0.0, the same error Caleb reported above is seen:
<img width="1458" alt="Screenshot 2023-03-10 at 11 38 26 AM" src="https://user-images.githubusercontent.com/46494969/224398132-3a20e923-4a40-441a-a37f-e986d840b77f.png">

---

Is this still an invalid use case? Am i missing something here? mixing up compatible versioning or something?? or is this problematic?

**Comment by mitulshah-suse** [comment]
@Josh-Diamond 4.0.0 is the only chart that should be installed on 1.25.x k8s version and it should be installed with `global.psp.enabled=false` 
3.0.0 installation will fail because the chart has PSPs which will not work on 1.25 cluster.
2.1.0 got installed since that chart did not have any PSPs in it, they were introduced in a later version. So upgrading to 3.0.0 will fail, since 3.0.0 chart does have PSPs which are not supported.

**Comment by Josh-Diamond** [comment]
@mitulshah-suse Thank you for that clarification

**Comment by mitulshah-suse** [comment]
@slickwarren @Josh-Diamond Please confirm if this issue can be closed.

**Comment by Josh-Diamond** [comment]
From my perspective and scenario, this was an invalid use case, highlighted by @mitulshah-suse .

This issue may be closed, unless you have any additional concerns, @slickwarren ?
