### ISSUE TITLE
[BUG] In-Place k8s Upgrade of Local Cluster results in RKE2 Cluster staying stuck in `Updating` state

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#40859]
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc5`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `Helm`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.24.10-rancher4-1` -> `v1.25.6-rancher4-1`
- Cluster Type (Local/Downstream): `Downstream RKE2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `EC2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`

**Describe the bug**
Seems an in-place k8s upgrade deletes the service account tokens for the system-agent

**To Reproduce**
1. Deploy an HA cluster on `v1.24.10-rancher4-1`
2. Create a downstream RKE1 and RKE2 cluster (both at 1.25 k8s versions)
3. Migrate from the HA cluster using the rancher backup-restore operator to another HA setup running `v1.24.10-rancher4-1`
4. Perform an in-place upgrade on the local cluster to k8s v1.25.6-rancher4-1

Note, I do not expect the RKE2 cluster to come back up after step 3.

**Result**
Upgrade completes and the RKE2 cluster is in an Updating status, waiting for plan to be applied

**Expected Result**
Upgrade completes and all clusters are in an Active status

**Screenshots**
![image](https://user-images.githubusercontent.com/107147272/224802093-0cb78717-c852-4507-bc16-3797781ded82.png)

**Comment by Oats87** [comment]
Doing some investigation into this, the service account tokens were deleted because the Rancher setup was migrated from one Rancher installation to another. During this procedure, the service account tokens are deleted, and expected to be recreated through the process detailed here: https://github.com/rancher/rancher/issues/40819#issuecomment-1463015660

There is an issue where the `system-upgrade-controller` is not deployed to a 1.25.x cluster due to the inclusion of pod security policies, and Fleet errors out with:
```
fleet-default   nick-124-rke2   1/3             8/8           nick-124-rke2-c-66234465-8kcws   2023-03-13T19:58:15Z   ErrApplied(2) [Bundle mcc-nick-124-rke2-managed-system-upgrade-controller: unable to build kubernetes objects from release manifest: resource mapping not found for name: "system-upgrade-controller" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first]
```

This is occurring due to the fact that the latest RC (`v2.7.2-rc5`) does not have the newest version of the `system-upgrade-controller` chart that allows disabling PSPs. This should be when the following is fixed: https://github.com/rancher/rancher/issues/40565

@nickwsuse I will leave closing the issue up to you -- we can independently verify this specific path if you would like, once the chart is updated and a new RC is cut.

**Comment by jiaqiluo** [comment]
can be validated in v2.7.2-rc6

**Comment by nickwsuse** [comment]
I'm blocked on testing this until https://github.com/rancher/rancher/issues/40819 is resolved, as my RKE2 clusters are stuck `Updating` even before getting to the in-place upgrade. Once that's fixed I can do the migration -> upgrade tests.

**Comment by nickwsuse** [comment]
`Validated on v2.7.2-rc7`

I did an in-place upgrade with _several_ RKE2 clusters after a migration and all the clusters came back up as expected. 

Flow: HA1 v1.24.10 -> HA2 v1.24.10 -> HA3 v1.25.6 (I accidentally used the same backup file for HA1 -> HA2 so the clusters didn't come back up until I manually edited the `redeploySystemAgentGeneration` value to `2`) -> HA4 1.25.6 (All clusters came up as expected)
```
Custom RKE1 k8s v1.24.10
DS EC2 RKE1 k8s v1.25.6
DS EC2 RKE1 k8s v1.24.10

Custom RKE2 k8s v1.24.11+rke2r1
Custom Hardened RKE2 k8s v1.24.10+rke2r1
DS EC2 RKE2 k8s v1.24.10+rke2r1
DS EC2 RKE2 k8s v1.24.11+rke2r1
DS EC2 RKE2 k8s v1.25.7+rke2r1
```
