### ISSUE TITLE
Can not log into Grafana when deployed to a local cluster

### ISSUE THREAD

**Issue by tgeek77** [rancher/rancher#40873]
Issue: After deploying Grafana a local cluster, it is not possible to reach the login screen.  
Cluster: 1-node k3s cluster ("v1.24.10+k3s1") with 8GB ram and 4 vCPUs
Rancher: 2.7.2rc5

Steps to reproduce:

Install k3s and Rancher as specified above
Go to the local cluster dashboard -> Clusters Tools
Deploy Monitoring (v102.0.0+up40.1.2)
From the dashboard, go to Monitoring -> Grafana. You will see a Page not found error
Click on the Sign In page, you will either get the Page not found again or the JSON error: `message: "Unauthorized"`
![json-error](https://user-images.githubusercontent.com/10347457/225037752-4ed171bc-96f3-4f1a-a3ba-ea487cb25102.png)
![page-not-found](https://user-images.githubusercontent.com/10347457/225037758-625a8845-c38c-4dc4-b785-c3386da12504.png)

**Comment by sebracs** [comment]
This seems to be because Grafana thinks it should be deployed under 
`myrancher/k8s/clusters/local/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy`
but rancher wants it to run under
`myrancher/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy`
for some reason.

I managed to fix it by adjusting the following values in configmap cattle-monitoring-system/grafana-nginx-proxy-config under key `nginx.conf` :
```ini
sub_filter '"appSubUrl":""' '"appSubUrl":"/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy"';
# ...
rewrite ^/api/v1/namespaces/cattle-monitoring-system/.*/proxy(.*) /$1 break;
```

**Comment by bashofmann** [comment]
This should be fixed with https://github.com/rancher/charts/pull/2515

**Comment by kOstovic** [comment]
This was not fixed in
https://github.com/rancher/charts/pull/2515
I still had to apply this line in nginx conf instead of original rewrite
rewrite ^/api/v1/namespaces/cattle-monitoring-system/.*/proxy(.*) /$1 break;


So there is workaround that you manually add this rewrite every time you deploy grafana, but it is not fixed by default

**Comment by igbenic** [comment]
Fresh install, didn't work for me as well. I was getting 404 for images and reloading Grafana would return something like
```json
{"message": "Not found"}
``` 
This finally worked with Traefik:

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-replacements
  namespace: kube-system
spec:
  replacePathRegex:
    regex: "^/api/v1/namespaces/cattle-monitoring-system/.*/proxy(.*)"
    replacement: "$1"
```

**Comment by ddaka** [comment]
issue is still present in v107.2.1+up69.8.2-rancher.23, I fixed by manually editing nginx proxy rewrite rule.
