### ISSUE TITLE
[BUG] Rocky87 2.7.2-RC6- error thrown blocking users from installing charts without choosing a namespace

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#40920]
**Rancher Server Setup**
local: 2.7.2rc6

**Information about the Cluster**
downstream cluster
- Rocky87 ami-05ab2eb74c93eb441
- K8- v1.25.6
- RKE1
- 1 etcd, 1 cp, 3 workers.

**Describe the bug**
as a user, when i install a chart without choosing a namespace an error is thrown and blocks the user from installing the chart. the error says  a namespace is not found.
example: 
- CIS scan version 4.0.0-rc4  throws this error - namespaces "cis-operator-system" not found
- Longhorn chart version 102.2.0+up1.4.0 throws this error - namespaces "cis-operator-system" not found

tested charts:
- CIS
- Longhorn
- Monitoring
- Istio 

**To Reproduce**
1. stand up 2.7.2rc6 cluster
2.  stand up downstream rocky87 cluster with ami-05ab2eb74c93eb441
3. open downstream cluster apps > charts
4. install a chart while choosing the option to install the chart into 'project' 'none'

**Result**
namespace not found

**Expected Result**
the chart is installed successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/89030218/225966994-b15717b4-09c9-4d2b-a513-94ae8c86145f.png)

**Additional context**

**Comment by PennyScissors** [comment]
This issue seems to be specific to Rocky87 cluster types, and not the helm operation logic in charge of creating the namespace and installing the chart. I tried installing the ui-plugin-operator to test this and found the following:
1. Installing the chart works in all other cluster types with any of the project options including none
2. Installing the chart in a Rocky87 cluster with project: none results in this issue
3. Installing the chart in a Rocky87 cluster with project: default results in a "failed to wait for roles to be populated" error coming from the helm operation code [here](https://github.com/rancher/rancher/blob/a841a9e101ae601a033fa8b39342ad4800c91d85/pkg/catalogv2/helmop/operation.go#L901). Notice that the namespace should've been created before getting to this point, but it wasn't created (verified with kubectl). Something specific to Rocky87 setups may be preventing the helm operation from creating the namespace.

**Comment by superseb** [comment]
@AndrewHoffmanQA Here are my findings (this was tested on @ronhorton 's setup):

- Tried to install ui-plugin-operator, got the error message `namespaces not found`
- Looked at the current namespaces, saw one namespace stuck in `Terminating`
- Tried to remove that namespace, but got denied by gatekeeper admission webhook
- Uninstalled gatekeeper
- Was able to successfully installed ui-plugin-operator after removing gatekeeper

I also ran tests on my own cluster with a single node (all roles) with Rocky 8.7 and could install the charts without an issue.

Could you create a setup with the provisioned cluster without any installed apps and share it to me / @PennyScissors so we can test on the setup as you have created it/how you experienced it?

Any background info on your testing would also help, like:

- When was Rocky 8.7 successfully validated for the last time? (so since what version/RC did it break)
- Does it happen on one node with all roles too? Or only with split roles?
- Does it work on Rocky 8.6?

**Comment by AndrewHoffmanQA** [comment]
@superseb i can confirm the cluster i was originally using had OPA installed, thank you for looking into this and we will change process to ensure this doesn't happen again. 

I am able to successfully install charts on newly created Rocky87 clusters and see the same behavior you did. per talking with Steven, his comments are about the cluster I was using. i'm pretty confident in closing this bug as a personal knowledge gap around the implications of opa being installed on a downstream cluster. 

- I confirmed Infracloud tested 8.7 in  2.6.11 and 2.7.2 successfully
- it performed fine in a one node all roles cluster
- it does work on Rocky86.

I'm confident this is not a bug and will be closing this ticket. @superseb.
