### ISSUE TITLE
[BUG] k3s-master/worker-plan

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#40974]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  k3s 1.24.10

**Information about the Cluster**
- Kubernetes version: 1.24.10
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported, HCloud

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**

I've setup a k3s-cluster on Hetzner Cloud. Its working fine for some hours. Also deployed the system-update-controller and 2 plans for master/worker.
After importing the k3s-cluster into rancher, i get 2 additional plans "k3s-master/worker-plan" (to version: 1.24.11) in namespace "cattle-system" that re-appear even after deleting and mess with my custom plans.

**To Reproduce**

- create k3s cluster
- deploy system-upgrade-controller
- import into rancher (0 plans)
- deploy 2 custom plans 

**Result**
- seeing 2 addtional plans created

**Expected Result**

no additional plans; or at least possibility to disable this.

**Screenshots**

**Additional context**

**Comment by Oats87** [comment]
This occurs because any `k3s`/`rke2` cluster that is imported to Rancher triggers a few controllers (namely, https://github.com/rancher/rancher/blob/7913e283ff90eebd1f8cc48860a6b410d72cd4dd/pkg/controllers/management/clusterprovisioner/provisioner.go#L1064-L1118 and https://github.com/rancher/rancher/blob/7913e283ff90eebd1f8cc48860a6b410d72cd4dd/pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go)

You may be able to short circuit this logic by creating your imported cluster, then editing the `status` field on the `clusters.management.cattle.io` object and manually set your driver to `k3s`, i.e in the local cluster
```
kubectl patch clusters.management.cattle.io <CLUSTER> --type=json -p='[{"op": "replace", "path": "/status/driver", "value":"k3s"}]'
```

Note you will need to copy your import command before you perform the patch, because the UI will no longer show the registration command after you set the driver.

If your cluster already exists, I would recommend setting the `cluster.Spec.k3sConfig` to `nil`, which should make it stop trying to deploy those two plans. See: https://github.com/rancher/rancher/blob/7913e283ff90eebd1f8cc48860a6b410d72cd4dd/pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go#L41-L43 for the code that surrounds this.

**Comment by Oats87** [comment]
If this does not resolve your issue, please comment and I can re-open the issue and we'll take it from there.

**Comment by strowi** [comment]
Thanks! That might also explain why it didn't happen on previously imported clusters (via terraform).
I think i recently added the `driver = "k3s"` to that. 
Will try changing that to "imported" and see. I'm guessing this will only work on a newly imported cluster and not update.
Since we want to deploy a fleet of edge k3s' we obviously don't want them to update "at will", but on our timetable. ;)
