### ISSUE TITLE
edit or upgrade imported k3s cluster is not working

### ISSUE THREAD

**Issue by fragpit** [rancher/rancher#41007]
Just trying to figure out. Documentation tells that when I import k3s cluster, Rancher should recognize it and provide an options for editing and upgrading (Registration tab in cluster options). But I'm not seeing this in my installation.

k3s: v1.26.3+k3s1 (also  v1.24.12+k3s1)
rancher: 2.7.1

Rancher was deployed on local k3s cluster v1.24.12+k3s1, using helm chart. 

When I create cluster with Rancher (k3s) I have all the options available, but not when I import existing k3s cluster.
No Registration tab and Kubernetes version in cluster options is greyed out, and Config UI looks different btw.

Maybe I misunderstand the docs, please correct me.

**Comment by Oats87** [comment]
As of `v2.7.1` we do not currently support `v1.26.x` (or even `v1.25.x` of K8s/K3s). `v2.7.2` will bring `v1.25.x` support to the table, but will not support `v1.26`.

I see you also tested with `v1.24.12+k3s1`, which is the latest version of K3s. Because of this, there will not be a drop down (as there is no newer version to upgrade to), as Rancher only supports up to `v1.24.10+k3s1` right now. 

When installing K3s, you can specify environment variables to specify the version you are installing i.e. `INSTALL_K3S_VERSION=v1.24.9+k3s2`

You should be able to edit the cluster in the UI and see a dropdown like in the following screenshots.
<img width="3005" alt="Screenshot 2023-03-29 at 12 40 41 PM" src="https://user-images.githubusercontent.com/30601846/228649819-25a49b86-c49d-41b7-97ba-47eafd44c013.png">
<img width="3001" alt="Screenshot 2023-03-29 at 12 40 50 PM" src="https://user-images.githubusercontent.com/30601846/228649828-84caff22-7c59-4980-b0e4-2968dd6c5d02.png">

The latest version can be seen here: https://github.com/rancher/kontainer-driver-metadata/blob/22b2ac6d554714f76c2ad705889198cc259a4136/channels.yaml#L336 -- when v2.7.2 is released, that will be updated with the newer versions, and provided your Rancher is internet-connected, it should update the available versions.

**Comment by brandond** [comment]
You can also reference the Rancher support matrix, when deciding what versions of Kubernetes you want to use: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-1/

**Comment by fragpit** [comment]
Ok, thank you! Mainly I tested on  v1.24.12+k3s1. I assumed that the version change is greyed out because there is no new supported version. Now I know. 
Tell also please, what about Resitration tab. Shoud it be available?

**Comment by Oats87** [comment]
> Ok, thank you! Mainly I tested on v1.24.12+k3s1. I assumed that the version change is greyed out because there is no new supported version. Now I know.
> Tell also please, what about Resitration tab. Shoud it be available?

Once the cluster is imported to Rancher, the UI will no longer show the registration tab.
