### ISSUE TITLE
[BUG] 2.7.2-rc7 airgapped cluster throws error when attempting to install monitoring 

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#41016]
**Rancher Server Setup**
- Rancher version:
charts installed on local rancher
airgapped local (1 etcd, 1cp, 1 worker)
rancher - v2.7.2-rc7
k8- v1.25.6

**Describe the bug**
Monitoring- 102.0.0+up40.1.2

attempting to install monitoring fails, it appears that the image is not copying correctly from the registry. 

**To Reproduce**
1. stand up local airgapped cluster
2. navigate to charts > monitoring
3. install with standard values

**Result**
image is never successfully pulled from private registry.  see error logs screenshot

**Expected Result**
successful install

**Screenshots**

![image](https://user-images.githubusercontent.com/89030218/228903396-bb8459e8-2e83-4ad6-a8fe-31c4e26866d1.png)

**Additional context**
note: once this is retested, retest https://zube.io/rancher/rancher/c/49944 
during investigation Brandon Depesa found that the root issue may be due to the quote wrap in around the registry image location, 
examples - 
Monitoring pulls 
failing - `image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}`

logging pulls 
working - image: `"{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"`

**Comment by prachidamle** [comment]
The issue seems to be same as https://github.com/rancher/rancher/issues/41015, should be same rootcause

**Comment by aiyengar2** [comment]
If you're using an air-gapped setup with a private registry, it's weird that the `{{ template "system_default_registry" . }}` is not prepending the registry URL, which is expected to come from `global.cattle.systemDefaultRegistry`. That's why the error seems to be suggesting that `rancher/shell:v0.1.18` cannot be pulled, rather than `PRIVATE_REGISTRY_URL/rancher/shell:v0.1.18` cannot be pulled.

**Are you sure that you set `global.cattle.systemDefaultRegistry` to your expected registry when deploying the chart?** `Install with Standard Values` implies that this step may not have been taken.

---

If that's not the issue...

Given the fact that the [`rancher-images.txt` for `2.7.2-rc7`](https://github.com/rancher/rancher/releases/download/v2.7.2-rc7/rancher-images.txt) contains `rancher/shell:v0.1.18`, we should first check that the image has been improperly mirrored to the private registry / failed to be mirrored.

**Can you check to see if you can run `docker pull <PRIVATE_REGISTRY_URL>/rancher/shell:v0.1.18` successfully from a node in the cluster?**

If that works, we should then look at the manifest that gets created and ensure the image is indeed `<PRIVATE_REGISTRY_URL>/rancher/shell:v0.1.18`.

**Comment by nflynt** [comment]
I was able to reproduce this in a local setup by setting a private registry, and blocking access to the `docker.io` upstream registry. This is close enough to the airgapped environment to reproduce the broken behavior.

Even with the systemDefaultRegistry setting populating in the user interface:
![container_registry_setup](https://user-images.githubusercontent.com/122321752/229214827-ab72491d-118f-43a4-99fd-dc4c58c9d942.png)

When we go to actually install the chart, we can see in the Cluster logs that it's instead trying to pull from `registery-1.docker.io`, the default upstream source:
![broken_gatekeeper](https://user-images.githubusercontent.com/122321752/229214900-d7b49151-8ed2-42e2-8206-0663e973c260.png)

If we check the YAML for the `rancher-gateway-crd` chart, we can see that the value for `systemDefaultRegistry` was not saved correctly, which explains the reversion to default behavior:
![gatekeeper-missing-systemDefaultRegistry](https://user-images.githubusercontent.com/122321752/229215268-02306c61-9791-467f-a0b4-fe12b4aab76e.png)

![wrong_location](https://user-images.githubusercontent.com/122321752/229216247-bb1fa0cc-4f4b-4e6e-8756-d2043b94fb90.png)

Note: these examples are for the **gatekeeper** chart, noted in issue https://github.com/rancher/rancher/issues/41015 but they apply to the monitoring chart as well. The issue seems scoped to charts which are annotated as `auto-install` _and_ which require image pulls.

**Comment by nflynt** [comment]
Observation: this appears to be a recent dashboard regression. If I modify my global settings to use the released dashboard instead:
`ui-offline-preferred` set to `Remote`
`ui-dashboard-index` set to `https://releases.rancher.com/dashboard/release-2.7.2/index.html`

Then both charts install correctly, pulling from the custom registery as expected.

**Comment by mantis-toboggan-md** [comment]
> Observation: this appears to be a recent dashboard regression. If I modify my global settings to use the released dashboard instead:
> ui-offline-preferred set to Remote
> ui-dashboard-index set to https://releases.rancher.com/dashboard/release-2.7.2/index.html
> 
> Then both charts install correctly, pulling from the custom registery as expected.

Yeah this checks out. Very similar behavior to https://github.com/rancher/dashboard/issues/8566. We identified and fixed a regression that crept into rc7 in which charts were being installed with only the default global values, PR here:
https://github.com/rancher/dashboard/pull/8573

**Comment by prachidamle** [comment]
Thanks @nflynt for the analysis and @mantis-toboggan-md for confirming this is a dashboard issue thats fixed. I am moving this one to-test for QA to test with the next rc

**Comment by jiaqiluo** [comment]
can be validated in rancher v2.7.2-rc8

**Comment by AndrewHoffmanQA** [comment]
retest passed. 

testing information
- Airgapped 
- v2.7.2-rc8
- v1.25.6

installed monitoring on local cluster and confirmed successful install and smoked tested the basic monitoring functionality.

closing ticket
