### ISSUE TITLE
[BUG] cluster goes into error state on a k8s upgrade on rke2 node driver cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#41012]
**Rancher Server Setup**
- Rancher version: v2.7-head `3a42367` 
- Installation option (Docker install/Helm Chart): `Docker install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.25.5+k3s1`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Infrastructure Provider` 2 nodes - 1 etcd + cp and 1 worker

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Standard user and Admin
   
**Describe the bug**
When we upgrade the k8s version of na rke2 node driver cluster, the cluster goes into `error` state from `updating` state for a few seconds and then go back to `updating` state

**To Reproduce**
1. Create a rancher server v2.7-head 
2. Log in as a standard user or an admin
3. Create an rke2 node driver cluster from `1.24.11+rke2r1`
4. Upgrade the k8s version on the cluster from `1.24.11+rke2r1` to `1.25.7+rke2r1`

**Result**
Notice the cluster goes into error state for a few seconds and come back to updating state with the following error statement 
```
 Cluster health check failed: Failed to communicate with API server during namespace check: Get
      "https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=45s": dial tp 10.43.0.1:443: connect:
          connection refused
```

**Expected Result**
Expected the state to go from updating to active without the error state.

**Additional context**
<img width="500" alt="2023-03-29_13-59-56" src="https://user-images.githubusercontent.com/38144301/228667760-fafa59f6-1f11-4a11-89ab-bd8ab7663365.png">

**Comment by aiyengar2** [comment]
Tried to reproduce this on a slightly different setup but did not get the same results, used the following:
- Rancher Helm install on RKE2 management cluster
- 1 etcd+controlplane+worker RKE2 provisioned DO downstream cluster

**Comment by Oats87** [comment]
@anupama2501 Do you see an extended outage of the cluster?

I believe that this is being caused due to the fact that there is only one controlplane node in this cluster -- we run a controller within Rancher that is responsible for checking the health of the cluster and sets the `Ready` condition on the `clusters.management.cattle.io/v3` object. It does this through the use of the `cattle-cluster-agent` reverse proxy, and dials the downstream API server to ensure that the component health status is OK.

GIven the fact that this is occurring during the time of upgrade, I believe this to be a transient error. During upgrade, RKE2 will restart the `kube-apiserver` static pod (and actually, replace it with the newer version running the newer version of Kubernetes). When it does this, I would expect to get a connection refused to the API server as there are no other api servers available within the cluster. This specific error message is getting rendered into the condition here: https://github.com/rancher/rancher/blob/7913e283ff90eebd1f8cc48860a6b410d72cd4dd/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L90

**Comment by snasovich** [comment]
Added `release-note` to this one to list in "Known Issues" as it's a pre-existing transient error that is likely possible for RKE1 clusters with a single control plane node. Also worth noting that most real-life configurations should have more than 1 control plane node.

**Comment by Oats87** [comment]
The release note should look like this:

```
When using custom clusters in Rancher v2.7.2 with RKE2 and K3s, deletion of nodes without cleaning up underlying infrastructure can lead to unexpected behavior if the underlying infrastructure is not cleaned up thoroughly. If deleting a custom node from your cluster, if possible, ensure you delete the underlying infrastructure for it, or alternatively, run the corresponding uninstall script for the Kubernetes distribution installed on the node. For RKE2, documentation can be found here: https://docs.rke2.io/install/uninstall?_highlight=uninstall#tarball-method and for K3s, documentation can be found here: https://docs.k3s.io/installation/uninstall
```

**Comment by Oats87** [comment]
The release note should look like this:
```
When upgrading your Kubernetes cluster, it is possible to see a transient error stating that the "Cluster health check failed". During an upgrade, this is a benign error and will self-resolve. It is caused because the Kubernetes API server is temporarily unavailable as it is being upgraded within your cluster.
```

**Comment by snasovich** [comment]
Changed to milestone back to v2.7.2 for visibility for inclusion in release notes for now.
