### ISSUE TITLE
[BUG] Unable to install/upgrade v102 charts on hardened rke2 cluster

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#41018]
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc7`
- Installation option (Docker install/Helm Chart): `helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rke2`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `1.24`
- Cluster Type (Local/Downstream): `downstream hardened ec2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
Cannot install or upgrade to rancher-monitoring 102.0.0+up40.1.2 on hardened rke2 cluster

**To Reproduce**
1. create rke2 hardened cluster
2. attempt to install monitoring 102.0.0+up40.1.2

**Result**
installation fails

**Expected Result**
installation / upgrade succeeds

**Screenshots**

**Additional context**
was able to install monitoring using helm install by enabling psps

**Comment by ronhorton** [comment]
On a hardened rke2 cluster k8s 1.24, i was able to install rancher-monitoring-102.0.0-up40.1.2 by enabling psps
Before upgrading the cluster, I attempted to update the enable psps value to 'false' for monitoring. 
the rancher-monitoring-upgrade job fails so that i'm `unable to remove chart's psps`
<img width="1457" alt="2023-03-31_15-46-57" src="https://user-images.githubusercontent.com/89212856/229216777-0c6a3442-adad-471d-95b4-edca67407a13.png">

**Comment by Martin-Weiss** [comment]
I guess you must not remove the "monitoring PSPs" before you allow unrestricted PSP to be used by all service accounts / the default service account in cattle-monitoring-system namespace..

**Comment by prachidamle** [comment]
@ronhorton Did we test [this](https://github.com/rancher/rancher/issues/41018#issuecomment-1492519425) with latest rc?

**Comment by prachidamle** [comment]
@macedogm @cbron how should we proceed about documenting this case where when a user wants to upgarde a 1.24 hardened cluster to 1.25:
- On a hardened 1.24 cluster, monitoring chart has psp flag = true
- Before upgrading the cluster 1.25, all charts should be upgraded to drop psp's 
- But since the cluster is hardened, this chart upgrade to drop psp does not go through.
- Thus the user is then blocked on upgrading to 1.25 if the cluster is hardened.

Can the users be directed to "unharden" the cluster to unblock this situation and after charts are updated to drop psp's and the cluster is upgraded to 1.25 then they can apply any hardening back?

**Comment by macedogm** [comment]
> Can the users be directed to "unharden" the cluster to unblock this situation and after charts are updated to drop psp's and the cluster is upgraded to 1.25 then they can apply any hardening back?

No, I wouldn't recommend this, because it can lead to an insecure cluster (on an expected hardened environment). Plus it opens a window to attacks. We already wrote some info about how to transition and there is also the PR https://github.com/rancher/rancher-docs/pull/508 from @stormqueen1990 which instructions about how to migrate from PSP to PSS/PSA before the upgrade.

**Comment by stormqueen1990** [comment]
> No, I wouldn't recommend this, because it can lead to an insecure cluster (on an expected hardened environment). Plus it opens a window to attacks. We already wrote some info about how to transition and there is also the PR [rancher/rancher-docs#508](https://github.com/rancher/rancher-docs/pull/508) from @stormqueen1990 with instructions about how to migrate from PSP to PSS/PSA before the upgrade.

The instructions I've provided on rancher/rancher-docs#508 will unfortunately fail if the cluster is hardened as some workloads require specific PSPs to be deployed for privileged pods. Since we're trying to remove said PSPs, the upgrades fail.

In this case, what would be the recommended course of action?

**Comment by macedogm** [comment]
But on a hardened cluster before moving to 1.25 isn't the plan to 1) migrate the PSPs to PSS/PSA, 2) disable the PSPs and then 3) upgrade to 1.25?

Note: I haven't yet reviewed your PR.

**Comment by stormqueen1990** [comment]
> But on a hardened cluster before moving to 1.25 isn't the plan to 1) migrate the PSPs to PSS/PSA, 2) disable the PSPs and then 3) upgrade to 1.25?
> 
> Note: I haven't yet reviewed your PR.

When you say disable the PSPs, do you mean disabling the PSPs on a chart level or on the cluster level?

On the chart level we have observed that this path would not be possible unless the PSP policy in the cluster is changed to a more permissive one. Otherwise, the workloads still require their specific PSPs deployed in an upgrade, which ends up preventing the removal of PSPs during this process.

**Comment by macedogm** [comment]
When doing the step 1 the cluster will be on a hardened state with PSS/PSA, so step 2 would be to disable PSP at the cluster level.

**Comment by cbron** [comment]
So the summary here is to tweak the above _"Before upgrading the cluster 1.25, all charts should be upgraded to drop psp's
"_ to  _"Before upgrading the cluster 1.25, all charts should be upgraded to **enable PSS's first** and then drop psp's"_

**Comment by stormqueen1990** [comment]
> I'll review your PR later today and propose some updates there if applicable.

Sounds good! Thank you!

**Comment by ronhorton** [comment]
**Pass** Verified in `2.7.2-rc8`
1. provisioned hardened rke2 cluster k8s 1.24
2. installed rancher monitoring 101.0.0+up19.0.3 with psp enabled
3. upgraded monitoring to 102.0.0+up40.1.2 with psp enabled
4. upgraded cluster to k8s 1.25
5. update monitoring fails due to psps
6. run mapkubeapis commands
`helm mapkubeapis rancher-monitoring-crd --namespace cattle-monitoring-system
helm mapkubeapis rancher-monitoring --namespace cattle-monitoring-system`
7. update monitoring `manually change the psp.enabled to 'false' in install yaml`
8. monitoring upgrade successful

The manual change to the yaml value should be release noted for this scenario; the enable/disable psp checkbox is not shown on the chart install since the cluster is a k8s 1.25. 

mapkubeapis commands and scenario https://github.com/rancher/rancher/issues/40981#:~:text=in%20scenario%201.-,Scenario,-5

**Comment by ronhorton** [comment]
this has been release noted; closing as complete
