### ISSUE TITLE
Add Hull testing to OPA Gatekeeper charts

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#41026]

**Comment by doflamingo721** [comment]
The hull testing coverage 100% coverage for the gatekeeper chart is not possible at the moment because of multiple issues in the upstream and rancher's gatekeeper template. Some of the issues are already logged (https://github.com/rancher/rancher/issues/41688 and https://github.com/rancher/rancher/issues/41689) but similar indentation and tolerations from `values.yaml` not getting applied to the templates issues still persist in other templates as well. Some fixes are already raised in the upstream chart for this (https://github.com/open-policy-agent/gatekeeper/pull/2817 and https://github.com/open-policy-agent/gatekeeper/pull/2862) but these fixes would be released with the new gatekeeper chart. As of now the chart coverage is at 97 percent.
I'd suggest merging the PR at 97 percent coverage and with coverage disabled so that it won't affect the ci builds.
cc: @eliyamlevy @gunamata

**Comment by Jono-SUSE-Rancher** [comment]
@MKlimuszka - We cant keep this in v2.7.7. If we're blocked by upstream (or blocked by the CI build failures. Can we determine what the course of action here is and remove it from v2.7.7?
cc @doflamingo721

**Comment by mitulshah-suse** [comment]
@gunamata @diogoasouza Can you please advise about the below. As we had discussed earlier, this cannot be pushed in yet, due to upstream fixes pending and the handover for these have already been given to your team. So i believe your team will need to take this further.
cc: @Jono-SUSE-Rancher

**Comment by gunamata** [comment]
@mitulshah-suse , the indentation issue (https://github.com/rancher/rancher/issues/41689) has been resolved but we did not yet get a chance to work on https://github.com/rancher/rancher/issues/41688 . We will add this to our list of Q1 items. Removing the milestone 2.7.7 and put it under [2024-v2.8x-Backlog](https://github.com/rancher/rancher/milestone/319)

**Comment by mitulshah-suse** [comment]
@gunamata Ok, we are unassigning ourselves from this issue as well, since your team will be working on it once upstream issues are fixed.
