### ISSUE TITLE
Permission issues on RKE, RKE2 and K3s Clusters When Running CIS 1.24 Scans

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#41131]
I am working on introducing CIS 1.24 profiles for RKE1, RKE2 and K3s as part of the issue: https://github.com/rancher/rancher/issues/41886 and https://github.com/rancher/cis-operator/issues/191

**Server Setup:**

- Rancher: `v2.7.2-rc8`
- K8s: `v1.25` (rke, rke2 and k3s)

**security-scan and cis-operator with below versions**

- kube-bench: `v0.6.12`
- sonobuoy: `0.56.15`
- kubectl: `1.26.1`
- go `1.19`

In CIS 1.24, kube-bench has updated couple of tests where the permission of certain files like kube-ca.pem etc should be 600 or more restrictive. Earlier it was 644 or more restrictive. Because of this below tests for RKE, RKE2 and K3s are failing. 

The actual permission on the scanned cluster is set to 644, but because of the new tests (set to 600 or more restrictive) the tests are failing. 

I am raising this issue to check what can be done on this case. There are two possible solution I can see which are:
1. Check with RKE1, RKE2 and K3s teams and see if we can set the permission to 600 instead of 644 while spinning up the clusters.
2. Mark these tests as Manual so that users can update the permissions and set it to 600.

Below are the snapshots of the test failures:

- RKE1 multi-node hardened cluster: 
As per the json results below are the permissions of all the three nodes:
```
          "rayan-rke1-mn-h1": "permissions=600",
          "rayan-rke1-mn-h2": "permissions=644",
          "rayan-rke1-mn-h3": "permissions=600"
```
![rke1-mn-h-2](https://user-images.githubusercontent.com/32811240/231234268-431f4ab6-8f10-4c7e-875c-7321c9493d8f.png)

- Similarly we have failures in RKE2 clusters (multi node and single node):

![rke2-mn-p-2](https://user-images.githubusercontent.com/32811240/231235120-50c31f1d-11bc-4f88-8ede-40f8aacfc4fb.png)

- K3s multi-node cluster (multi node and single node):

![k3s-mn-p-2](https://user-images.githubusercontent.com/32811240/231235621-75e156cd-cb1b-4e76-8d5c-1190e5200d6b.png)

**Comment by rayandas** [comment]
@prachidamle @macedogm Please advice on the above issue.

**Comment by andypitcher** [comment]
Here are the CIS checks that had their permissions changed from 644 to 600, since CIS-124.

| Target | Check ID      | CIS-1.23 | CIS-1.24 and beyond    |
| :---  | :----:        |    :----:   |          ---: |
| ETCD | 1.1.20      | 644       | 600  |
| MASTER | 1.1.1   | 644        | 600      |
| MASTER | 1.1.3  | 644        | 600      |
| MASTER | 1.1.5   | 644        | 600      |
| MASTER | 1.1.7   | 644        | 600      |
| MASTER | 1.1.9   | 644        | 600      |
| MASTER | 1.1.15   | 644        | 600      |
| MASTER | 1.1.17  | 644        | 600      |
| NODE | 4.1.1   | 644        | 600      |
| NODE | 4.1.3   | 644        | 600      |
| NODE | 4.1.5   | 644        | 600      |
| NODE | 4.1.7   | 644        | 600      |
| NODE | 4.1.9   | 644        | 600      |

**Comment by rayandas** [comment]
Please find the checks (which are failing) below for all the profiles where the permissions are set to 600 instead of 644 and are failing while scanning. 

> NOTE: There are a couple of the checks which has 600 permission, but still they're passing as the permission of the files are getting set correctly (600) on the node.

```
RKE1 permissive:
	NONE
RKE2 permissive:
	1.1.3
	1.1.5
	1.1.13
	1.1.15
	1.1.17
	4.1.5
K3s permissive:
	1.1.15
	1.1.17
	4.1.5
	4.1.7
RKE1 hardened:
	4.1.7
RKE2 hardened:
	1.1.3
	1.1.5
	1.1.13
	1.1.15
	1.1.17
	1.2.19
	4.1.5
K3s hardened:
	1.1.15
	1.1.17
	1.2.14
	4.1.5

**Comment by rayandas** [comment]
Closing this issue as there are separate issues created for RKE RKE2 and K3s repos. All the communication will happen on the respective issues.
