### ISSUE TITLE
[v2.6] Update Pause version for K8s v1.24.13 in KDM

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#41208]
As per https://github.com/kubernetes/kubernetes/blob/v1.24.13/build/dependencies.yaml

**Comment by vivek-infracloud** [comment]
Tested the cluster creation on rancher v2.6.11

**- v1.24.13-rancher2-1**
  - KDM pointing to `dev-v2.6-2023-04-patches`
  - k8s v1.24.13-rancher2-1 provisioned successfully. Also checked the `rancher/mirrored-pause` version is `3.7`.
  - Upgrade from k8s v1.23.16-rancher2-1 to v1.24.13 is successful. 

Since v1.24.13-rancher2-1 is working as expected on rancher v2.6.11. Closing this issue.
