### ISSUE TITLE
[BUG] Machine pool names over 63 characters break CAPI machine deployments

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41394]
**Rancher Server Setup**
- Rancher version: v2.7-head

**Describe the bug**

When provisioning a cluster, specifying a machine pool name > 63 characters will cause the generated machine deployment not to create any machinesets. This is because the machine pool name is set as the value of the `rke.cattle.io/machine-pool-name` label of the machine set spec, and labels must be <= 63 characters.

**To Reproduce**

Create a cluster with a machine pool name > 63 characters

**Result**

The machine pool does not provision.

**Expected Result**

The machine pool provisions.

**Screenshots**

![image](https://user-images.githubusercontent.com/33796120/236027371-801df9ee-6174-41f6-a6a1-310b49ec2718.png)

**Additional context**

This should be validated at the webhook level. There are no concerns for regressions due to machine pools with names > 63 characters no being able to provision today, and the name is truncated anyway.

**Comment by thatmidwesterncoder** [comment]
### Root cause
There was no validation on the rke machine pool resource. This would cause a _very_ long label to be created which kubernetes would deny since they are limited to 63 characters. 

### What was fixed, or what changes have occurred
A validating webhook was added for the v1 cluster create operation which validates that the rke machinepool name is no longer than 63 characters. If it is it denies the request. 
 
### Areas or cases that should be tested
Create a cluster with machine pools less than and greater than 63 characters, as long as the machine pool name is less than 63 characters the cluster resource validation will pass.

### What areas could experience regressions?
Not that I know of unless there is a bug which would prevent clusters from being created. But the value is hardcoded so that is very improbable.
  
### Are the repro steps accurate/minimal?
Yes.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head dc105f0
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision RKE2 cluster
2. For the machine pool vm name, set the name to more than 63 characters
3. Try to create cluster
4. Verify cluster cannot be created and Rancher UI does not allow you to create the cluster

**Result**
The UI does not allow the user to create the cluster and gives the following error
```
admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request: pool name must be 63 characters or fewer
```
![image.png](https://zube.io/files/rancher/56509cbefe1ebcb64745fda0b24611b9-image.png)
