### ISSUE TITLE
2.7 版本使用keyclock的情况下无法通过 rancher-cli 通过鉴权获取 token

### ISSUE THREAD

**Issue by wuzhuoquan** [rancher/rancher#41520]
问题描述：
rancher 版本使用了  2.7.3，鉴权使用 keyclock，从浏览器可以打开并登录。
但是从浏览器下载 kubeconfig 文件然后使用 kubectl 操作，选择 keyclock 方式之后无法完成 token 获取
<img width="1674" alt="image" src="https://github.com/rancher/rancher/assets/49891988/7cb18e20-bb6a-4b89-8a75-765410562b12">
打开上面提示的地址也还是不行。
原因是 /login?xxxx 这个地址是 rancher-cli 拼装的，而 rancher 2.7 版本中并无此路径，于是直接跳转到 /dashboard/home 页面

那么请教一下在 2.7.3 版本中该如何正确使用 keyclock 来完成 kubeconfig 的鉴权？

**Comment by nflynt** [comment]
Greetings! I'm using Google Translate to understand your issue, I will reply in English.

It seems that when authenticating using `rancher-cli`, the login URL which begins with `/login?` is not working correctly. This is a bug we have just identified with Rancher 2.7.3, and the problem seems to be a regression in the dashboard. We've narrowed down the [issue](https://github.com/rancher/dashboard/issues/8964) but don't yet have a root cause or a fix.

If you need to get `rancher-cli` working again right away, but you don't want to downgrade all of Rancher, you can temporarily configure Rancher to use an older version of the dashboard:

![dashboard_workaround](https://github.com/rancher/rancher/assets/122321752/76588313-2706-4fb0-81be-6c7be8e6a8c4)

Warning: be very careful when changing these global settings. If these are incorrect, you may be locked out of the user interface.

Set `ui-index` to `https://releases.rancher.com/ui/release-2.7.1/index.html`
Set `ui-dashboard-index` to `https://releases.rancher.com/dashboard/release-2.7.1/index.html`
Set `ui-offline-preferred` to "Remote"

After this change, see if the `/login?` URL provided by `rancher-cli` works again. To undo the workaround, set these settings back to their defaults.

**Comment by wuzhuoquan** [comment]
> Greetings! I'm using Google Translate to understand your issue, I will reply in English.
> 
> It seems that when authenticating using `rancher-cli`, the login URL which begins with `/login?` is not working correctly. This is a bug we have just identified with Rancher 2.7.3, and the problem seems to be a regression in the dashboard. We've narrowed down the [issue](https://github.com/rancher/dashboard/issues/8964) but don't yet have a root cause or a fix.
> 
> If you need to get `rancher-cli` working again right away, but you don't want to downgrade all of Rancher, you can temporarily configure Rancher to use an older version of the dashboard:
> 
> ![dashboard_workaround](https://user-images.githubusercontent.com/122321752/240438647-76588313-2706-4fb0-81be-6c7be8e6a8c4.png)
> 
> Warning: be very careful when changing these global settings. If these are incorrect, you may be locked out of the user interface.
> 
> Set `ui-index` to `https://releases.rancher.com/ui/release-2.7.1/index.html` Set `ui-dashboard-index` to `https://releases.rancher.com/dashboard/release-2.7.1/index.html` Set `ui-offline-preferred` to "Remote"
> 
> After this change, see if the `/login?` URL provided by `rancher-cli` works again. To undo the workaround, set these settings back to their defaults.

 thanks for you reply, and sorry for my terrible english 😭
 I have change the  version to 2.6.8，and not work well，thank you！
