### ISSUE TITLE
[BUG] Node name, Hostname, and VM Name don't match on Rancher-launched RKE2 cluster (vSphere)

### ISSUE THREAD

**Issue by MaxAnderson95** [rancher/rancher#41581]
**Rancher Server Setup**
- Rancher version: 2.7.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.25.9+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider (vSphere)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

**Describe the bug**

When creating a cluster with the vSphere infra provider, the name of the node in Rancher, the name of the VM in vSphere, and the hostname of the VM within the OS (Ubuntu 22.04) don't match each other. They're all different.

**To Reproduce**

Create a vSphere-based RKE2 cluster with rancher

**Result**
The three names described above are all different.

**Expected Result**

These three names should all be the same

**Screenshots**

![](https://i.imgur.com/aHumndZ.png)

**Additional context**

**Comment by MaxAnderson95** [comment]
I'm aware that the hostname within the OS probably needs to be set with cloud-init. My main concern is the similarly named, but deceptively different VM names vs Machine Names.

**Comment by jakefhyde** [comment]
The machine name != the vm name, the infrastructure machine name will equal the vm name. You can see this under the machine's `spec.infrastructureRef.name` field, as well as navigate to the `https://<RANCHER_SERVER_URL>/dashboard/c/local/explorer/rke-machine.cattle.io.vmwarevspheremachine` endpoint. This is a CAPI construct, and by design. Additionally, the vm template you are using was either cloned from an existing vm (i.e. one that already had a hostname), or there is something else wrong with the template generation which causes the cloud-init to not set the hostname correctly. You can confirm this by trying to provision multiple vms with the same template, the second one will fail to register due to the kubelet rejecting the duplicate hostname.

**Comment by MaxAnderson95** [comment]
@jakefhyde thanks for the clarification!

As for the template I get a unique random hostname with every clone, even by hand outside of Rancher. So I'm not sure what the deal is.

As a workaround I set the following in my cloud-config. Requires that the template has `jq` installed but could be done without I'm sure.

```yaml
runcmd:
  - 'hostnamectl set-hostname $(cloud-init query -a | jq -r .v1.local_hostname)'
```

**Comment by Oats87** [comment]
I wonder if https://github.com/rancher/machine/commit/490fd23068f8fa8148cc47c331acacd8cc1fb645#diff-b1ed4b551f94526acf78f6fc9b36f79d2096dc6c68bba9688f466f9ba5e2cba4L158 has anything to do with this.

**Comment by snasovich** [comment]
@MaxAnderson95 , curious if you have an update for us to continue looking into this issue.

**Comment by MaxAnderson95** [comment]
Honestly I think this can be closed. I didn't realize the vm and machine names were intended to be different.
