### ISSUE TITLE
Update Rancher CLI to use new dashboard login url instead of legacy ember URL

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#41651]
**Is your feature request related to a problem? Please describe.**
This is related to rancher/dashboard#8964. Currently, when using the `rancher token` command with a SAML provider (such as OKTA) the rancher CLI produces a URL for the user to initiate the login process inside of rancher. This uses the `/login` endpoint, which produces a login page for the old ember UI.

Going forward, the rancher CLI should not use this endpoint, and instead should use an equivalent page from the dashboard.

**Describe the solution you'd like**
The URL produced [by the CLI](https://github.com/rancher/cli/blob/b16d9b0d7c03510d8e61898e1440c67722852a1e/cmd/kubectl_token.go#L418) should refer to a dashboard endpoint, like `/dashboard/auth/login`.

**Describe alternatives you've considered**
Other endpoints could be used, as long as they are not from the ember UI.

**Additional context**
Initial testing showed some issues with the `/dashboard/auth/login` endpoint. More testing will be needed to verify if this endpoint is suitable (or needs some modification).

SURE-6606

**Comment by prachidamle** [comment]
Would be good to get information from Dashboard team on what endpoint should rancher CLI  use in place of the legacy url  to initiate the login process inside of rancher

**Comment by prachidamle** [comment]
@nflynt discussed with @MbolotSuse and found the following - it is currently patched in the dashboard code, that is, new versions of rancher do not redirect the /login route that it uses

it will be necessary to rework it to use the non-ember route before we can deprecate ember, but I'm not sure what the timeline is to deprecate ember.

**Comment by eliyamlevy** [comment]
Posting repro steps from here for reference:

1. Run rancher/rancher:v2.7.3 (docker install works).
2. Install the [rancher cli](https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli#docusaurus_skipToContent_fallback).
3. Integrate the [okta auth provider](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-okta-saml#docusaurus_skipToContent_fallback), or another SAML provider with rancher.
4. Using the Rancher cli, attempt to generate a token using rancher token --server=$RANCHER_HOST --cluster=$CLUSTER (replace $RANCHER_HOST with your rancher hostname, and $CLUSTER with the cluster that you want to generate a token for).
5. Note that the rancher cli asked the user to login to rancher at a specified URL in the console where the token command was run ($RANCHER_HOST/login - note that there are other params included after login, you must use this exact login).
6. Attempt to go to this URL in your browser. Note that the rancher cli is not able to complete the process (this is due to the redirect mentioned above).

**Comment by eliyamlevy** [comment]
After some investigation with the help of Nancy Butler, I've come to the conclusion that the solution is some updates to the Dashboard code to handle the case that the `/dashboard/auth/login/` endpoint receives a request with the `requestId` parameter. Currently the dashboard does not handle this parameter. 

The solution is to add this case to the dashboard code, have it forward the request to the norman api (mirroring the ember flow) and then updating the login url to the dashboard one. 

There shouldn't need to be any major changes to the CLI code.

**Comment by gaktive** [comment]
Filed https://github.com/rancher/dashboard/issues/9608 in support of the most recent comment. Will try for 2.8.0 if it's light.

**Comment by MKlimuszka** [comment]
@eliyamlevy , you said there are no *major* changes to the CLI code. So that means there will be small changes needed to the backend code alongside the FE ticket, right?

**Comment by MKlimuszka** [comment]
The UI ticket just got moved into working this morning.

**Comment by prachidamle** [comment]
UI ticket got merged, backend should test if this is resolved now or are more changes necessary for CLI?

**Comment by KevinJoiner** [comment]
When validating this issue, we should check the[ authenticating kubeconfig with rancher cli feature](https://ranchermanager.docs.rancher.com/v2.7/reference-guides/cli-with-rancher/kubectl-utility#authentication-with-kubectl-and-kubeconfig-tokens-with-ttl) still works, since it is directly affected by the CLI changes.
These [test cases](https://github.com/rancher/rancher/issues/37705#issuecomment-1176777670) can be used as a reference on how to test that feature.

**Comment by prachidamle** [comment]
New CLI tag for 2.8.0 has been cut - v2.8.0-rc2 https://github.com/rancher/cli/tree/v2.8.0-rc2

**Comment by eliyamlevy** [comment]
Tested the new rc with a terraform set up Okta auth provider. It went through but the cli returned me the old login like in the terminal. I think this was missed and we need one more PR to fix that message. 

I did use the same link but switched the uri to point to the dashboard link and it worked so it looks like the functionality should be there from the dashboard side of things. 

Looking into the terminal message now.

**Comment by nickwsuse** [comment]
### Verified on v2.8-head ID: e232d49 ✅ 
----
Test Cases:
1. Login with no auth provider enabled
2. Login with SAML auth provider enabled
3. Login with OAuth auth provider enabled
4. Login with LDAP auth provider enabled
5. Token generation with no auth provider enabled
6. Token generation with SAML auth provider enabled
7. Token generation with OAuth auth provider enabled
8. Token generation with LDAP auth provider enabled
9. Kubeconfig TTL with MCM disabled
