### ISSUE TITLE
SSL Wildcard certificate update not picking up new URL addition

### ISSUE THREAD

**Issue by blu35ky** [rancher/rancher#4167]
We recently updated our wildcard to include another site (from 3 to 4 urls). 

In Rancher Infrastructure - Certificates, we added a new certificate. The new wildcard entry actually picks up the new url ("www.mainsite.com + 4 others"). We then updated the load balancer ensuring that the new wildcard is selected. The certificate does not seem to work on the new site, even after waiting for 1-2 days to propagate. Have we missed a step? Does Rancher cache the old certificate and need a manual refresh?

We notice that in AWS, there's wildcard load balancer with SSL Certificate setting in its "Listeners" section. But won't Rancher manage the setting for certificate? 

We also want to update the EV certificate on top of the wildcard certificate. Will the step be the same? 

Many thanks. 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.63.0` Cattle: `v0.155.0` UI: `v0.94.0` |
|Access|`github` `admin`|
|Route|`authenticated.project.help`|

**Comment by vincent99** [comment]
Rancher is generally cloud-agnostic and does not know of or manage resources in AWS for you (with a few exceptions*).  The load balancer in Rancher is made up of containers running HAProxy and does not interact with ELB.  Changing a cert should "immediately" (seconds) update the balancer containers.

But it sounds like you have ELB in front of Rancher and it's doing SSL termination, so that's where the cert needs to be.  ELB could be configured several ways:
  - Terminate the SSL connection and send plaintext traffic to the backend:  Rancher doesn't need any cert.  Since you seem to be a financial institution, that sounds like a bad idea.
  - Terminate the SSL connection and re-encrypt it with a (hopefully) different cert: Rancher balancer needs to be configured to listen using the (hopefully) different cert.  Maybe this is what you're talking about with EV vs wildcard?  Because nobody will issue you a cert that is both EV+wildcard.
  - TCP balancing, do not terminate the connection: Rancher balancer needs the original mainsite.com cert because it is terminating the SSL connection.

*: Creating new EC2 instances via Add Host calls `docker-machine` to do things, and the Route53 DNS template in the catalog manages DNS entries.

**Comment by blu35ky** [comment]
Thanks for the explanation @vincent99. 

We figured out the issue by checking up the logs in the Rancher elb. `inconsistencies between private key and certificate loaded from PEM file` turns out that the private key used was incorrect. The devops guy haven't documented which key is which. It actually is simple to setup wildcard and EV in Rancher. :)
