### ISSUE TITLE
Can't create EKS cluster node pools `SignatureDoesNotMatch: Credential should be scoped to correct service: 'iam'.`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#41716]
**Setup**
- Rancher version: v2.7-head (5a8b3bd)
- Rancher UI Extensions: 
- Browser type & version: chrome

**Describe the bug**

when creating an EKS cluster, user is presented with error `SignatureDoesNotMatch: Credential should be scoped to correct service: 'iam'.` after selecting their credentials. User is able to select some options after this step, but can't create the cluster as nodepool options aren't available. 

**To Reproduce**

* create an EKS cluster through rancher

**Result**
user can't add node pools / node pool info to the cluster

**Expected Result**

no error should occur when creating an eks cluster

**Screenshots**

**Additional context**

same AWS user on rancher v2.7.3 does not hit this issue
I believe this is a dashboard issue since the error suggests this has to do with headers not matching the credential service 
`credential scope does not specify the same service as the host header`
source: https://docs.aws.amazon.com/IAM/latest/UserGuide/signature-v4-troubleshooting.html#signature-v4-troubleshooting-credential-scope

**Comment by richardcase** [comment]
Myself & @salasberryfin have investigated this and see the issue. I'll create a change today.

**Comment by salasberryfin** [comment]
As @richardcase mentioned, we identified that the problem is caused by an update to the `aws-sdk` module.

We tested Rancher downgrading the `aws-sdk` version to v1.44.253 (current go.mod version is v1.44.266) and it works fine. Some version between 253 and 266 added a change that requires to specify the service name in the call to `iam.amazonaws.com`. As seen [here](https://github.com/rancher/rancher/blob/efc731b553111e5083ee6fb21587491f7e4fcdc9/pkg/httpproxy/sign.go#L115), since IAM is a global service, this call is sent with an empty service. This used to work but no longer does and it is what causes the error.

**Comment by richardcase** [comment]
There is a PR with a proposed fix ^^^^.  Also its worth calling out this comment in the PR:

> If we felt this was too risky, then downgrading the AWS SDK would also fix the problem short term. Long term we don't want to be in a position where we can't upgrade the AWS SDK.

**Comment by slickwarren** [comment]
tested on v2.7-head (0bb5e50):
* created new EKS cluster -- pass
* updated existing EKS cluster -- pass
