### ISSUE TITLE
rancher- rancher-webhook k8s 1.27 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41789]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by KevinJoiner** [comment]
We are unable to support K8s 1.27 until https://github.com/rancher/client-go has a 1.27 release.

**Comment by tomleb** [comment]
## Validation Template

## Root Cause

Need to support k8s 1.27

## What was fixed, or what change have occurred

We have updated various dependencies in rancher/webhook (rancher/webhook#287):
- controller-runtime to `0.15`
- k8s to `v0.27.4`
- client-go to `v1.27.4-rancher1`

We have created a new RC for the webhook and updated the charts.

## Areas or cases that should be tested

- Make sure the provisioning succeeds on a `1.27` cluster
- Make sure the latest webhook version is running (`v0.4.0-rc5`) on the local cluster
- Validate P0 functionality for the webhook
- Make sure we can upgrade from a `1.26` cluster to a `1.27` cluster

## What areas could experience regressions

The changes mostly affects interactions between the webhook and the k8s API. So potential regression would be that the newer version no longer works as intended on older k8s version (eg: `1.24`, etc). Would be worth checking that webhook stills works with the lowest supported k8s version for 2.8. (For reference, for 2.7 the lowest k8s version is `1.23` according to https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-6/, unsure about what's planned for 2.8).


## Are the repro steps accurate/minimal?

N/A

**Comment by Priyashetty17** [comment]
**QA TEST PLAN**

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Fresh install Rancher - k8s v1.27</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.8-head with k8s v1.27. </li> 
                    <li> Verify that the version of the webhook is as expected. </li>
                    <li> Verify kube-version annotation in the webhook chart's yaml has: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0' </li>
                    <li> Verify that there are no errors in the rancher-webhook logs. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> The webhook version is as expected on the cluster. </li>
                    <li> kube-version annotation in the webhook chart's yaml is as expected on the cluster. </li>
                    <li> No errors in the rancher-webhook logs. </li>
                </ol>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>Upgrade checks - from K8s v1.26 to v1.27</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.8-head. </li> 
                    <li> Create a downstream cluster with k8s v1.26. </li>
                    <li> Upgrade K8s on the downstream cluster from v1.26 to v1.27. </li>
                    <li> Verify that the version of the webhook is as expected. </li>
                    <li> Verify kube-version annotation in the webhook chart's yaml: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0' </li>
                    <li> Verify that there are no errors in the rancher-webhook logs. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> Downstream RKE1 cluster with k8s v1.26 is created successfully.  </li>
                    <li> K8s on the downstream cluster is upgraded from v1.26 to v1.27 successfully. </li>
                    <li> The webhook version is as Expected. </li>
                    <li> kube-version annotation in the webhook chart's yaml is as expected. </li>
                    <li> No errors in the rancher-webhook logs. </li>
                </ol>
            </td>
        </tr>
    </tbody>
</table>

**Comment by Priyashetty17** [comment]
@samjustus @tomleb Since 1.27 cluster provisioning isn't available in Rancher yet: https://github.com/rancher/rancher/issues/41840, should we move this to **Blocked** instead of "**To Test**"? cc @sowmyav27

**Comment by gunamata** [comment]
@Priyashetty17 , Are you still blocked to test this?

**Comment by Priyashetty17** [comment]
@gunamata No, I'm not blocked to test this.

**Comment by Priyashetty17** [comment]
Validated with 2.8.0-alpha1 (v2.8-aecfe5961e630a8db0e239e00a611227c8886253-head) 
Webhook chart: rancher-webhook:v0.4.0-rc9
