### ISSUE TITLE
gke-operator k8s 1.27 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41798]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [x] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [x] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [x] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

## PR's

- [x] https://github.com/rancher/charts/pull/2888
- [x] https://github.com/rancher/charts/pull/2886
- [x] https://github.com/rancher/rancher/pull/42878

**Comment by valaparthvi** [comment]
I tried to test this but it seems something is amiss.
1. Installed Rancher v2.8-head
2. Create GKE cluster with k8s v1.26.7
3. Changed the gke-operator deployment image to v2.0.1-rc1, the latest one available.
4. Tried to upgrade k8s version of the existing GKE cluster, but there was no option for upgrade
5. Tried to create a new cluster, but there was no option for K8s 1.27

Is there another way to install gke operator rather than relying on the cluster creation?

**Comment by valaparthvi** [comment]
@gunamata Can you please help me identify what exactly it is that needs to be tested here? My understanding is that I need to test if it is possible to add GKE cluster with K8s v1.27 on rancher.

Here are the steps I have taken to test it:
1. On an EC2 instance, spin up a k3s [v1.26.8-rc3+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.26.8-rc3%2Bk3s1) cluster.
2. Install rancher-latest helm chart (rancherImageTag=v2.8-head) that currently points to 2.7.7-rc4 on this cluster.
3. Once Rancher is up, add GKE v1.26. At this point, the version of gke-operator helm chart is 102.x.x.
4. Upgrade k3s to [v1.27.5+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.27.5%2Bk3s1).
5. Since rancher is already at 2.8, I then check if GKE operator can be upgraded to 1.27, but it's not possible at the moment.

> Make sure the existing chart and the app is functional after cluster upgrade
This seems to be fine, but after the upgrade, the rancher repository is still using dev-v2.7, I expected it to have been upgraded to dev-v2.8.

Am I missing any steps? Can you help me understand the importance of this issue?

**Comment by gunamata** [comment]
@l4zy0n3 , Can you please help Parthvi on what to test based on what you did for Mapps charts?

**Comment by cpinjani** [comment]
Depends on KDM 1.27 support https://github.com/rancher/rancher/issues/41840

**Comment by valaparthvi** [comment]
I believe this issue might be fixed once https://github.com/rancher/gke-operator/pull/178 goes in, wdyt @cpinjani?

**Comment by cpinjani** [comment]
@valaparthvi Yes, along with KDM 1.27 support IMO

**Comment by valaparthvi** [comment]
I ran smoke tests, creating/importing cluster, upgrading k8s version, adding/deleting nodes and some tests with RBAC, everything works as expected. 1.27 is also a default K8s version now.

**Comment by valaparthvi** [comment]
Closing the issue since it's working as expected.
