### ISSUE TITLE
[flaky-test] TestCreateNamespaceProjectMember and TestCreateNamespaceProjectOwner

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#41853]
TestCreateNamespaceProjectMember
TestCreateNamespaceProjectOwner
TestCRTBRoleTemplateInheritance

SURE 6453

**Comment by MbolotSuse** [comment]
Note: This issue was due to a [different test](https://github.com/rancher/rancher/blob/160bee82ebdae08b1bbb9fccab030cf2f31c15ad/tests/v2/integration/catalogv2/system_charts_version_test.go#L127) which caused the webhook to be unavailable during these tests, causing the issue. The test in question was reverted and is currently not being ran. 

This issue aims to fix the currently disabled test, so that it can be ran safely alongside these other tests.

**Comment by MbolotSuse** [comment]
Also adding TestCRTBRoleTemplateInheritance to the list.
