### ISSUE TITLE
[BUG] Custom Driver Stuck on Credential Creation

### ISSUE THREAD

**Issue by happytreees** [rancher/rancher#41910]
**Rancher Server Setup**
- Rancher version: 2.7.4
- Installation option (Docker install/Helm Chart):
   - Docker v2.7.4
   - Helm v2.7.4 on Kubernetes v1.25.10

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - admin

**Describe the bug**
I am attempting to setup the [Vultr node driver](https://github.com/vultr/docker-machine-driver-vultr) on a fresh install of Rancher(v2.7.4). The node driver can be added to Rancher without issue and it will download as well. Once I attempt to create a cluster using the driver it goes into a loop during the Cloud Credential page. I will add the values, click "create" and then it will bring me right back to creating a credential. I have also attempted to create the Cloud Credential separately, however, the driver does not show up under Cloud Credentials even so the driver is active and downloaded. 

This driver worked fine on previous versions of Rancher, however, it is recently not working with newer versions. 

**To Reproduce**
Attempt to use the node driver on Rancher v2.7.4, regardless of whether valid or invalid credentials are used it will loop on that page without any error printed. It is unable to get past the cloud credentials page. 

**Result**

**Expected Result**
Either print an error on what is wrong, or continue to creating the cluster.

**Comment by happytreees** [comment]
Issue is still present on v2.7.5

**Comment by snasovich** [comment]
@happytreees , thank you for reporting this issue.

Could you please provide some additional information:
1. You're stating "This driver worked fine on previous versions of Rancher, however, it is recently not working with newer versions." - could you please let us know what is the latest previous version where it worked for you?
2. Since you've stated "Once I attempt to create a cluster using the driver it goes into a loop during the Cloud Credential page." it looks like you're creating RKE2 cluster as the UI flow for RKE1 clusters is a bit different and requires creating Node Template where Vultr credentials should be provided.
3. Related to the above, is it possible it was working for RKE1 but maybe never worked for the RKE2 case?
4. To help reproduce the issue, please provide the exact values used for creating Vultr Node Driver in Rancher.
![image](https://github.com/rancher/rancher/assets/85187633/d2b7b059-7142-45d5-b04e-d98edfa39b94)

**Comment by happytreees** [comment]
Hey @snasovich 

Thank you for reviewing this issue. I can definitely provide that information for you:

1. The drive works fine all the way up to `v2.6.13` , however, when upgraded to `v2.7.0` the issue presents itself immediately and any versions past that. So it seems there was a breaking change or a bug introduced in `v2.7.x`. 

2. This is for an RKE1 cluster, we do are not using RKE2 at this time. 
![Screenshot 2023-07-21 at 8 59 52 AM](https://github.com/rancher/rancher/assets/110687499/12c872a2-7333-405b-a3de-80d3a4912fc3)

We first create a Node template under `RKE1 Configuration` which creates fine. We then go to the "Clusters" tab and attempt to "Create Cluster" 

We are then presented with the following page:
![Screenshot 2023-07-21 at 9 04 20 AM](https://github.com/rancher/rancher/assets/110687499/f18f490c-7dc6-4acc-ab30-430ac1cc11ba)

It is worth noting that in previous versions this page would just go straight to cluster configuration page, however, in v2.7.x it is no longer doing so as that is the default generated page by rancher. I attempt to put in the values click "continue" and I am brought to this page:
![Screenshot 2023-07-21 at 9 05 55 AM](https://github.com/rancher/rancher/assets/110687499/f9a49df0-511d-4814-9b36-7fa6e2527d3e)

This just becomes a loop and I am unable to move past it as it will have me try to create the `credential` but because it's not a hard-coded credential it doesn't seem to be able to handle it properly and loops. 

3. We never even attempted to use RKE2 at this point, only RKE1. There does not appear to be an alternate method to create a cluster using RKE1 other than the "Create Cluster" button under the Clusters tab. 

4.

Download URL:
`https://github.com/happytreees/docker-machine-driver-vultr/releases/download/v0.2.1/docker-machine-driver-vultr`

Custom UI URL:
`https://sjc1.vultrobjects.com/rancher-ui/component.js`

Whitelist Domains:
```
api.vultr.com
sjc1.vultrobjects.com
```

**Comment by snasovich** [comment]
@happytreees , thank you for providing this additional information.

I've tried to reproduce it on the latest `v2.7-head` image and only see a similar issue when "RKE1"/"RKE2/K3s" toggle is set to "RKE2/K3s" (similar because the page for creating Cloud Credentials is slightly different for me).
When RKE1 is selected it goes straight to cluster details page allowing me to use created RKE1 Node Template (please note that I don't have valid API Key but UI allowed me to proceed forward with creating the node template).

Please see attached the video demonstrating the behavior I see.

https://github.com/rancher/rancher/assets/85187633/cb2ed903-b5e0-4c4c-b27c-c7ec9d4bec01

Could you please provide a recording that shows the issue you're seeing?

**Comment by happytreees** [comment]
@snasovich I apologize! I did not notice that toggle as my screen is rather large! That resolved the loop. Thank you so much

**Comment by snasovich** [comment]
@happytreees , no worries - glad it's working as before and nothing got broken recently in regards to how Vultr driver is functioning in Rancher.

**Comment by FreekingDean** [comment]
Does this not work with RKE2 though?

**Comment by Vladyslav-Miletskyi** [comment]
@FreekingDean not possible due to https://github.com/rancher/ui/blob/master/lib/global-admin/addon/components/cru-cloud-credential/component.js#L234-L253
CC: @snasovich
