### ISSUE TITLE
Update token setting defaults to have non-zero TTLs

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#41919]
Rancher has several settings which define the TTL of a created token: https://ranchermanager.docs.rancher.com/reference-guides/about-the-api/api-tokens#token-settings

As of Rancher 2.7, both `auth-token-max-ttl-minutes` and `kubeconfig-default-token-ttl-minutes` default to zero. Tokens in general have had a 0 TTL since Rancher 2.0, meaning they last forever. This has resulted in several problems. These include:  a concern in our default security posture, performance issues around too many unexpired tokens, and confusion about which settings to adjust.

We would like to propose a **breaking change** where both of these *default* values are set to non-zero TTLs. These settings can be manually reset back to zero.  Our initial proposal is the following: 
* kubeconfig-default-token-ttl-minutes: 30 days (43200 minutes)
* auth-token-max-ttl-minutes: 90 days (129600 minutes)

In practical terms, this means given a default install of Rancher 2.8.0, when a user generates a kubeconfig in the UI, that kubeconfig's token would now expire in 30 days. 

This will not effect existing tokens made before 2.8.0. It will affect any Rancher setup which has not manually set those settings.

**Comment by Martin-Weiss** [comment]
Will there be a simple way to refresh tokens before they expire and a warning before a currently used one is going to expire?

**Comment by KevinJoiner** [comment]
@Martin-Weiss Users will always be able to create a new token before their current token expires. We are not adding the ability to refresh your current token. Users can view the token page in the UI to see the age of all of the tokens they created.

To add clarity, we are changing the default value of the settings. So if users do not care about security they have the ability to change the setting back to the TTL of 0 (forever) and regain previous behavior.

**Comment by KevinJoiner** [comment]
Related to https://github.com/rancher/rancher/issues/38535

**Comment by Martin-Weiss** [comment]
@KevinJoiner to make the life for users easier with expiring tokens - would it be possible to add some sort of warning in the UI during or after user login or even allow sending an email to the users before their tokens expire for a heads up? (expiring tokens have a simliar impact like expired SSL certificates ;-))

**Comment by cbron** [comment]
I'd like some user feedback on that. In the past when we have added UI warnings for things like socket disconnects, the feedback from community was negative and they were removed. For something like this if one user creates many tokens, they would constantly get this message and that could be annoying.
Users can always go the api keys page and sort by expiring to see which keys are close to expiration.

**Comment by cbron** [comment]
UI work for this is already there, so no work needed. It shows in UI what `auth-token-max-ttl-minutes` is, and that becomes your max option in the list.

**Comment by JonCrowther** [comment]
# Validation

## What was fixed, or what change has occurred

The TTL of auth tokens and kubeconfig tokens have been updated. Previously they were set to 0, which means they do not expire. Now auth tokens are set to 90 days (129600 minutes) and kubeconfig tokens are set to 30 days (43200 minutes) as a default.

## Areas or cases that should be tested

There are a few places you can see the new defaults:
1. When creating an API key, the `Automatically Expire` field is set to the auth token TTL (90 days)
2. In global settings, `auth-token-max-ttl-minutes` and `kubeconfig-default-token-ttl-minutes` reflect the new defaults
3.  Create a new kubeconfig (either via download, copy or opening a shell) and then do `kubectl get tokens`. There will be a token of the form `kubeconfig-user-qtcl6jfz46`, and if you describe it, the TTL will be listed as `2592000000`, which is 30 days in seconds

It's also important that setting the values in the Global Settings page updates the value when creating token.

## What areas could experience regressions

Any tests that look at the TTL value or setting values may fail. I ran the unit tests and integration tests successfully, but there's always a chance I missed a test somewhere.

Since the TTL is very long (30 or 90 days), it's unlikely to affect any unrelated tests by causing the tokens to time out. If there exists a test system that runs continuously, the TTL setting may need to be configured back to 0 so they don't expire.

## Are the repro steps accurate/minimal?

Yes. As a note, to see the changes create a rancher instance with the latest dev-2.8 branch and the defaults will be set. I don't believe upgrading from a previous version will change the settings so it does need to be a fresh instance.

**Comment by JonCrowther** [comment]
# Release note template

## Synopsis of issue
Previously, auth tokens and kubeconfig tokens never expired by default.

## Resolution
Now by default, the auth tokens expire after 90 days and kubeconfig tokens expire after 30 days. For more info visit: https://ranchermanager.docs.rancher.com/v2.5/reference-guides/about-the-api/api-tokens

**Comment by JonCrowther** [comment]
# Release note

## Synopsis of issue
Previously, auth tokens and kubeconfig tokens never expired by default.

## Resolution
Now by default, the auth tokens expire after 90 days and kubeconfig tokens expire after 30 days. For more info visit: https://ranchermanager.docs.rancher.com/v2.5/reference-guides/about-the-api/api-tokens
