### ISSUE TITLE
Catalog of Images

### ISSUE THREAD

**Issue by Verikon** [rancher/rancher#4197]
Perhaps this is a total misconception of the usage paradigm however;

It would be nice to have a type in the "catalog" which represents an image as opposed to an entire stack. From the catalog of images a stack could then be derived.

Bleedingly Obvious? already planned? already mentioned?

**Comment by deniseschannon** [comment]
Do you mean something like a built in private registry? https://github.com/rancher/rancher/issues/1738

**Comment by LLParse** [comment]
Great question.

A catalog entry typically deploys a set of one or more services. A service must exist within a stack, so you'll get a new stack name similar to whatever software you were deploying.

The possibility of deploying other catalog entries within an existing stack is what you are asking for. Rancher supports this (and this is definitely where things are going), but there are very few templates built that leverage this powerful feature.

One good example is convoy-gluster, which makes use of a glusterfs service which is a separate catalog entry. You can see how we define a question which links them:
https://github.com/rancher/community-catalog/blob/master/templates/convoy-gluster/1/rancher-compose.yml#L14

The feature I think you are really proposing would be the ability to build a stack "catalog" which comprises two or more of these catalog entries. This feature **does not exist** and explains why you see a lot of catalog entries coming from the community which defines an entire stack instead of reusing components.

**Comment by LLParse** [comment]
I'm glad to see members of the community already realizing this potential! While there is no official road map, we intend to implement this feature in the near future.

Thank you, we couldn't have done it without our users!
