### ISSUE TITLE
Fix flaky automated tests found during v2.7.5 release

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42001]
Failures: 

FAILED test_namespaced_secrets.py::test_namespaced_certificates
FAILED test_namespaced_secrets.py::test_namespaced_basic_auth
FAILED test_namespaced_secrets.py::test_namespaced_docker_credential
FAILED test_namespaced_secrets.py::test_namespaced_ssh_auth
FAILED test_namespaced_secrets.py::test_namespaced_secrets
FAILED test_secrets.py::test_ssh_auth
FAILED test_secrets.py::test_certificates
FAILED test_secrets.py::test_docker_credential
ERROR test_notifier.py::test_notifier_smtp_password

SURE-6456

**Comment by PennyScissors** [comment]
Closing this. After investigating the drone build [here](https://drone-publish.rancher.io/rancher/rancher/9863/6/2) further, and discussing this with Team 1, I've concluded this was caused by a wider webhook failure that was happening at the time and not the tests being flaky (webhook errors with 500/EOF are present, and tests need to connect in order to create secrets).
