### ISSUE TITLE
[BUG] Global System Default Private Registry not being honored when pulling cattle-cluster-agent images, reverts back to docker.io

### ISSUE THREAD

**Issue by Brianalmeida** [rancher/rancher#42048]
**Rancher Server Setup**
- Rancher version: v2.7.3

**Information about the Cluster**
- Kubernetes version: 1.24.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported generic cluster using AKS 

**Describe the bug**
When importing new generic clusters in Rancher, the global entry for system-default-registry is not being honored by Rancher and is reverting to pulling from docker.io. 

**To Reproduce**
```
1.     Spin up a private registry
2.     Add a copy of 2.7.3 to the registry
3.     In the global settings in Rancher, add your private registry under system-default-registry
4.     Create a new AKS cluster in Azure
5.     In the Rancher UI, Import a new generic cluster
6.     Run the registration command on the node
7.     View the yaml for the cluster, and search for "docker.io"
```

**Result**
Rancher will **not** honor the system-default-registry and reverts to using docker.io.

**Expected Result**
Rancher honors the system-default-registry and pulls the container images from the correct endpoint.

**Additional context**
SURE-6586

Similar to this [issue](https://github.com/rancher/rancher/issues/40550), Manual workaround [provided](https://github.com/rancher/rancher/issues/40550#issuecomment-1599404068)

SURE-6586

**Comment by mjura** [comment]
I have checked all three operators. We don't deal with Container Registries, I think this is about Default Private Reigstry in Rancher, so probably someone fro Rancher core team should look onto this. Can we reassign this issue to other team.

**Comment by snasovich** [comment]
The code that is used to generate YAML for `cattle-cluster-agent` deployment to join the cluster into Rancher does not honor `system-default-registry` - https://github.com/rancher/rancher/blob/64aba5d6c6d516640143d96679f3bd99dfd432d1/pkg/api/norman/customization/clusterregistrationtokens/import.go#L49 (it calls to `image.Resolve` which ultimately returns the image passed to it unmodified - https://github.com/rancher/rancher/blob/64aba5d6c6d516640143d96679f3bd99dfd432d1/pkg/image/resolve.go#L45-L48).

This regressed in v2.7.1 per the following change - https://github.com/rancher/rancher/pull/40368/files#diff-df058c3539a16a7aa843e7dd88ea2ffb4c50e5ec45f91ab515b1a85d521748e6R46-R48

While we're working on fixing it, there 2 workarounds:
1. From a comment on the related issue - https://github.com/rancher/rancher/issues/40550#issuecomment-1599404068
2. Download the contents of the cluster registration manifest URL as shown on the UI when opening not yet registered cluster (it's in form of `(rancher-url)/v3/import/(token)_(cluster-id).yaml`), replace the reference to `rancher/rancher-agent` image with one that includes the desired private registry and run `kubectl apply` of that modified file (instead of pulling from the URL).

**Comment by felipe-colussi** [comment]
## Validation Template

## Root Cause

When importing new generic clusters in Rancher, the global entry for system-default-registry is not being honored by Rancher and is reverting to pulling from docker.io.

## What was fixed, or what change have occurred

If we had no cluster object the go function would ignore the system-default-registry, the function was changed and tests were added. 

## Areas or cases that should be tested


- Importing clusters.
- Importing clusters with CATTLE_BASE_REGISTRY set.
- As mentioned by 

## What areas could experience regressions

None. 

## Are the repro steps accurate/minimal?
Yes. 
As mentioned [here](https://github.com/rancher/rancher/issues/42666#issuecomment-1716701966) some K8S pods will not have the Custom Registry as they are created before rancher.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.8-head 4c55a12
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: imported single node cluster
----------

### Testing: ###
Tested this issue with the following steps:
1.     Spin up a private registry
2.     Add a copy of 2.7.3 to the registry
3.     In the global settings in Rancher, add your private registry under system-default-registry
4.     Create a new AKS cluster in Azure
5.     In the Rancher UI, Import a new generic cluster
6.     Run the registration command on the node
7.     View the yaml for the cluster, and search for "docker.io"

**Result**
Importing a generic cluster using system-default-registry uses registry images and the registration.yaml does not contain docker.io images when the system-default-registry is defined
