### ISSUE TITLE
Support Rancher Extensions on air-gapped environments

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42092]
This was reported as a bug. Supporting extensions on air-gapped environments is a feature. 

ui-plugin-operater  needs to download software from local private registry.
The Kubewarden extension also needs a source to be installed from.

**Comment by mpepping** [comment]
Same issue here. Forking the repo to a local copy, and creating a custom ClusterRepo in Rancher, isn't sufficient since the plugins use hardcoded GitHub URL's:

* https://github.com/rancher/ui-plugin-charts/blob/main/charts/kubewarden/1.1.0/templates/cr.yaml#L11
* https://github.com/rancher/ui-plugin-charts/blob/main/charts/elemental/1.2.0/templates/cr.yaml#L12

**Comment by l4zy0n3** [comment]
Verified using in the instructions provided to install Kubewarden in @rohitsakala comment here https://jira.suse.com/projects/SURE/issues/SURE-6065

**Comment by enneitex** [comment]
> Same issue here. Forking the repo to a local copy, and creating a custom ClusterRepo in Rancher, isn't sufficient since the plugins use hardcoded GitHub URL's:
> 
> * https://github.com/rancher/ui-plugin-charts/blob/main/charts/kubewarden/1.1.0/templates/cr.yaml#L11
> * https://github.com/rancher/ui-plugin-charts/blob/main/charts/elemental/1.2.0/templates/cr.yaml#L12

I, the endpoints are still harcoded in the UIPlugin CR, so I guess it's still not possible to install these extensions in air-gapped env ?
