### ISSUE TITLE
[RFE] Add azureADProvider as supportedAuthProvider for rancher CLI 

### ISSUE THREAD

**Issue by jmmckenz** [rancher/rancher#42142]
**Is your feature request related to a problem? Please describe.**
I have a customer that has just moved from AD to Azure AD and are unable to request tokens using the rancher CLI or kubectl.

Requesting that azureADProvider be added as a supportedAuthProvider to allow for the rancher CLI (and kubectl) to request a new token when an existing token has expired.

**Describe the solution you'd like**
Allow rancher CLI to pull a token using azureADProvider, similar to how we can currently do this with localProvider, activeDirectoryProvider, and other supported authentication providers when kubeconfig-generate-token is set to false.

**Describe alternatives you've considered**
Set kubeconfig-generate-token to true, however this would impact the security posture required by the customer, and is not acceptable for them.  Is there another way to pull tokens while authenticating to Azure AD?

**Additional context**
https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/kubectl-utility#authentication-with-kubectl-and-kubeconfig-tokens-with-ttl

https://github.com/rancher/cli/pull/336 
(However, even though this builds, I doubt it will actually work based on the kubectl-utility documentation)

**Comment by nickvth** [comment]
Please reopen this, because no support for azuread/AzureEntra:

If admins have [kubeconfig token generation turned off](https://ranchermanager.docs.rancher.com/reference-guides/about-the-api/api-tokens#disable-tokens-in-generated-kubeconfigs), the kubeconfig file requires the [Rancher CLI](https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli) to be present in your PATH when you run kubectl. Otherwise, you’ll see an error like: Unable to connect to the server: getting credentials: exec: exec: "rancher": executable file not found in $PATH.

This feature enables kubectl to authenticate with the Rancher server and get a new kubeconfig token when required. The following auth providers are currently supported:

Local
Active Directory (LDAP only)
FreeIPA
OpenLDAP
SAML providers: Ping, Okta, ADFS, Keycloak, Shibboleth

**Comment by idogada-akamai** [comment]
Can we please open this?
We are also using Azure AD and would like to have the option of authentication via the CLI

**Comment by log1cb0mb** [comment]
Isnt this currently being worked on here:
https://github.com/rancher/cli/pull/346

**Comment by nickvth** [comment]
https://github.com/rancher/rancher/issues/44282
https://github.com/rancher/rancher/issues/42939
