### ISSUE TITLE
[RFE] Graceful Shutdown of vSphere VM

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#42308]
Add the support for configuring the graceful shutdown of VMs for node-driver clusters in Rancher when vSphere is used as the infrastructure provider. 

SURE-3285

**Comment by slickwarren** [comment]
dashboard ticket: https://github.com/rancher/dashboard/issues/9724

**Comment by slickwarren** [comment]
I was able to test this rke2 workflow using the workaround posted here: https://github.com/rancher/dashboard/issues/9620#issuecomment-1744647372 however, I believe the other suggestion of leaving this ticket open until the frontend work is done (next release) is the best solution, since I would not expect customers to go this for to use this feature. 

Another option is, once the terraform work is in an RC state, I can test this backend ticket using that customer workflow. In my opinion, that would be enough to consider the backend work validated.

**Comment by slickwarren** [comment]
based on the testing here, via a supported rancher workflow (TF), we are able to see that this feature is working as expected. When the UI options are available next release, there will be another round of testing using the UI https://github.com/rancher/terraform-provider-rancher2/issues/1222#issuecomment-1762383290

**Comment by slickwarren** [comment]
also confirmed offline, this feature is only for rancher 2.8+
