### ISSUE TITLE
Infinite upgrades

### ISSUE THREAD

**Issue by frol** [rancher/rancher#4240]
Rancher Version: 1.0.0 (and 0.63)

Docker Version: 1.10.3

OS: Ubuntu 14.04.3

Steps to Reproduce:

The simplest way to bump into infinite upgrade is:

1. Create a new stack.
2. Create a new service with port mapping to a busy port (e.g. 22/SSH). [The service won't be able to start, but you can stop it at this point of time.]
3. Upgrade the service, but don't change port mappings.

Results: 

The service will be stuck trying to upgrade forever, and rollback won't help either! You can neither stop the service nor upgrade it further to solve the issue.

NOTE: The port mapping is not the only cause of such infinite upgrades, any constraints may fail (e.g. a service may be scheduled for a specific host or for a host with a specific label, but that host is dead or dropped the label). 

Expected:

There must be a way out of this loop! Upgrade and stop actions should be available during upgrade state. I do understand that this may cause upgrade failures due to incomplete upgrades, but there might be just a warning message/popup if upgrade process is not finished while new upgrade is requested.

The only way around this I found is by making a clone of the service and deletion of the failing one.

**Comment by alena1108** [comment]
@frol thanks for raising the issue. The process for cancelling failed upgrade/rollback should be this:

* upgrading->cancel-upgrade->finish-upgrade->finishing-upgrade->active
* rollingback->cancel-rollback->finish-upgrade-finishing-upgrade->active

And although all the processes transitions are in place today, finish-upgrade never completes because of the constraints failing. We should either allow:

* scale down the service in "finishing-upgrade" state
* deactivate the service in "finishing-upgrade" state

**Comment by soumyalj** [comment]
Tested in v1.1.0-dev4-rc1. Able to scale down the service.
