### ISSUE TITLE
[BUG] windows nodes stuck in 'unavailable' state, kubelet `failed to list *v1.ConfigMap: configmaps "kube-root-ca.crt" is forbidden: User <your_user>` after upgrading rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#42426]
**Rancher Server Setup**
- Rancher version: v2.7.6-rc2
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: v1.25.12, 1.26.7 + rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vsphere node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when upgrading rancher with windows clusters downstream, those clusters get stuck after the upgrade. Windows nodes are stuck in an unavailable state

**To Reproduce**

* deploy windows clusters on a 2.7.5 rancher setup using vsphere node driver
* upgrade rancher to 2.7.6-rc2
* wait for windows cluster to upgrade

**Result**
windows nodes stuck in unavailable state, also have some issue with kubelet `failed to list *v1.ConfigMap: configmaps "kube-root-ca.crt" is forbidden: User <system:user>`

**Expected Result**

windows cluster should not fail on rancher upgrade

**Comment by HarrisonWAffel** [comment]
After looking into this issue it seems to be related to the fix made for https://github.com/rancher/rancher/issues/39658, and subsequent changes. Changes were made to `run.ps1` in order to handle scenarios where vSphere nodes are rebooted gracefully, however this resulted in various issues with upgrading windows worker nodes in other providers. 

To regain upgrade stability we should revert the changes made to the system-agent-installer, and instead find another solution (potentially within wins itself) to handle 39658. Addressing the root issue has been complicated due to unexpected behavior from the RKE2 windows service, and an inability to properly stop it using basic Powershell commands. 

The error seen in the description of this ticket may not always appear, however upgrading Rancher does seem to result in Windows nodes functioning incorrectly.

**Comment by HarrisonWAffel** [comment]
A workaround for a node stuck in a situation such as this post upgrade is to manually reboot the node.

**Comment by slickwarren** [comment]
closing in favor of https://github.com/rancher/rancher/issues/42782
