### ISSUE TITLE
Port GUID fixes into 2.7-head

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42560]
| Original Issue(s) | Original PR | 2.7-head PR |
| ---- | ---- | -----|
| https://github.com/rancher/rancher/issues/42161, https://github.com/rancher/rancher/issues/42162, https://github.com/rancher/rancher/issues/42163 | https://github.com/rancher/rancher/pull/42325 | https://github.com/rancher/rancher/pull/42540 |
| https://github.com/rancher/rancher/issues/42467 | https://github.com/rancher/rancher/pull/42470 | https://github.com/rancher/rancher/pull/42542 |
| https://github.com/rancher/rancher/issues/42467  | https://github.com/rancher/rancher/pull/42470 | https://github.com/rancher/rancher/pull/42543 |
| https://github.com/rancher/rancher/issues/42478 | https://github.com/rancher/rancher/pull/42479 | https://github.com/rancher/rancher/pull/42544 |
| https://github.com/rancher/rancher/issues/42466 | https://github.com/rancher/rancher/pull/42493 | https://github.com/rancher/rancher/pull/42546 |

**Comment by nickwsuse** [comment]
This has been tested in v2.7-head and the only issue that was found appears to be the same issue that customers are running into now with v2.7.6 - https://github.com/rancher/rancher/issues/42612

Test Cases:
1. Users/CRTBs/PRTBs have DN instead of GUID (**Pass**)
2. Migration script started and configmap is created (**Pass**)
3. Restart Rancher pod to ensure existing configmap doesn't allow further runs of the unmigration script (**Pass**)
4. Upgrade from 2.7.4, confirm configmap is created and no data has changed (**Pass**)
5. Upgrade from 2.7.4 to 2.7.5 to 2.7.6 (**Fail** - https://github.com/rancher/rancher/issues/42612)
6. Login blocked for AD users attempting to login while the script is running (**Pass**)
