### ISSUE TITLE
[2.6 Backport] [BUG] windows nodes stuck in 'unavailable' state, kubelet failed to list *v1.ConfigMap: configmaps "kube-root-ca.crt" is forbidden: User <your_user> after upgrading rancher

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#42604]
This is a backport of https://github.com/rancher/rancher/issues/42426

**Rancher Server Setup**
- Rancher version: v2.6.x
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: v1.25.12, 1.26.7 + rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vsphere node driver, custom windows cluster 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when upgrading rancher with windows clusters downstream, those clusters get stuck after the upgrade. Windows nodes are stuck in an unavailable state

**To Reproduce**

* deploy windows clusters on an older version of rancher 2.6 using vsphere node driver
* upgrade rancher to the latest 2.6 version
* wait for windows cluster to upgrade

**Result**
windows nodes stuck in unavailable state, also have some issue with kubelet `failed to list *v1.ConfigMap: configmaps "kube-root-ca.crt" is forbidden: User <system:user>`

**Expected Result**

windows cluster should not fail on rancher upgrade

**Comment by slickwarren** [comment]
tested on v2.6.13:
* deploy windows cluster on 1.24.17+rke2r1
* upgrade rancher
- the original error is not showing, but now intermittently we get `{failed to extract runtime image: open C:\var\lib\rancher\rke2\data\v<dir>\bin\kube-proxy.exe: The process cannot access the file because it is being used by another process.}`.  This is happening most of the time for windows clusters after a rancher upgrade. I will open a new issue in lue of this one since the original error is gone.
