### ISSUE TITLE
Init Node cannot be removed

### ISSUE THREAD

**Issue by thomashoell** [rancher/rancher#42709]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart): Helm (1.26.7+rke2r1)

**Information about the Cluster**
- Kubernetes version: 1.26.7 RKE2
- Cluster Type (Local/Downstream):
  Downstream, vSphere

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin

**Describe the bug**
We were trying to cycle the master pool with an updated image template. However, the provisioning got stuck at the moment the old init node should be removed and a new one elected. The error message produced by Rancher is

`[rkebootstrap] fleet-default/XXXXXXXXXXX-bootstrap-template-tk7vg: cluster fleet-default/XXXXXXXX machine fleet-default/XXXXXXXXXX-worker-844f8b754f-7wknz was still joined to deleting etcd machine fleet-default/XXXXXXXXXXX-master-6b494f986c-kg7df`

We were able to work around this by removing the label `rke.cattle.io/init-node: "true"` from the machine plan secret of the old init node and adding it to another master node's machine plan secret.

This happened on all clusters where we were trying to cycle the master pool so far.

**To Reproduce**
- create a cluster (3x master, 3x worker)
- edit master pool template causing a node rotation (image template, specs, etc)

**Result**
Provisioning gets stuck when the init node is about to be removed.

**Expected Result**
Node pool should be rotated without issues

**Screenshots**
It's stuck in this state forever without intervention
![image](https://github.com/rancher/rancher/assets/4695168/675e8a9b-4000-4c40-a34e-b8ba9fbf3304)

**Additional context**
- Issue was probably introduced with Rancher 2.7.6
- Seems to **NOT** happen when scaling down a pool

**Comment by Flou21** [comment]
We have exactly the same problem with three clusters.

One of the master nodes of a cluster is stuck in a deleting state and cannot be removed.

In addition to the `rke.cattle.io/init-node: "true"` workaround, we tried something else.

We got the log message `[rkebootstrap] %s/%s: cluster %s/%s machine %s/%s was still joined to deleting etcd machine %s/%s`.
https://github.com/rancher/rancher/blob/385b0971656dc69d9aa7646fdcdc58de73795e1b/pkg/controllers/capr/bootstrap/controller.go#L504

Trying to work around this, we changed the `JoinedToAnnotation: "rke.cattle.io/joined-to"` on most nodes.
This annotation pointed to the node that was stuck in the deleting state on all remaining nodes.

We changed the annotation to the new master node that was successfully added to the cluster during rotation.

On the new master node we specified `""` as the value for the annotation `rke.cattle.io/joined-to` and set `rke.cattle.io/init-node`.


After that, the node that was stuck in the `deleting` state was removed.
But now there is an error message `init node not found` in the cluster, so the situation has not really improved.

**Comment by thomashoell** [comment]
Update: It seems that only existing, older clusters (6 to 12 months old) seem to be affected. I cannot  reproduce this on a fresh test cluster.

**Comment by gricuk** [comment]
The same problem.
v1.24.16+rke2r1 , rancher: v2.7.6

**Comment by JeanGau-ops** [comment]
> We have exactly the same problem with three clusters.
> 
> One of the master nodes of a cluster is stuck in a deleting state and cannot be removed.
> 
> In addition to the `rke.cattle.io/init-node: "true"` workaround, we tried something else.
> 
> We got the log message `[rkebootstrap] %s/%s: cluster %s/%s machine %s/%s was still joined to deleting etcd machine %s/%s`.
> 
> https://github.com/rancher/rancher/blob/385b0971656dc69d9aa7646fdcdc58de73795e1b/pkg/controllers/capr/bootstrap/controller.go#L504
> 
> Trying to work around this, we changed the `JoinedToAnnotation: "rke.cattle.io/joined-to"` on most nodes. This annotation pointed to the node that was stuck in the deleting state on all remaining nodes.
> 
> We changed the annotation to the new master node that was successfully added to the cluster during rotation.
> 
> On the new master node we specified `""` as the value for the annotation `rke.cattle.io/joined-to` and set `rke.cattle.io/init-node`.
> 
> After that, the node that was stuck in the `deleting` state was removed. But now there is an error message `init node not found` in the cluster, so the situation has not really improved.
> 
> **Update:**
> 
> We also tried to manually set the label `rke.cattle.io/init-node-machine-id` to the machine id of the new master node.
> 
> But then we got the error message `fixed machine with ID %s not found`.
> 
> https://github.com/rancher/rancher/blob/385b0971656dc69d9aa7646fdcdc58de73795e1b/pkg/capr/planner/initnode.go#L58
> 
> After this error message the label is removed again. How can we force the election of an init node?

I have exactly the same problem on one of my clusters after a k8s upgrade which redeployed every nodes (another issue posted here [9849](https://github.com/rancher/dashboard/issues/9849#issue-1926230304))
Did you find a solution? No matter what I do, I get a `fixed machine with ID %s not found` even if Rancher knows this machine which I can confirm with :
kubectl -n fleet-default get machines $node -o jsonpath="{range}{.metadata.labels.rke\.cattle\.io/machine-id}{'\n'}{end}"

**Comment by Flou21** [comment]
@JeanGau-ops  nope, the problem still exists.
For 2 weeks, 2-3 clusters have been in this extremely problematic state.
I don't really know how to go on.

**Comment by JeanGau-ops** [comment]
> @JeanGau-ops nope, the problem still exists. For 2 weeks, 2-3 clusters have been in this extremely problematic state. I don't really know how to go on.

:(

I found a promising answer but can't make it work, it's in chinese : [init node not found](https://www.xtplayer.cn/rke2/rancher-rke2-init-node-not-found/#%E6%89%8B%E5%8A%A8%E4%BF%AE%E5%A4%8D%E6%93%8D%E4%BD%9C)
I can't find a secret ${node}-machine-plan on my Rancher so... I don't know if I'm doing something wrong or if this user doesn't have the same environment.
Hopefully it can help you.

**Comment by Flou21** [comment]
Thanks for info on this article
We tried to save a cluster this way.
Unfortunately, it didn't work either.

We don't really want to try to fix it any more in this odd way.
I'm afraid we'll break more than we actually fix.

Whereas the current way of just waiting until there is an official solution hasn't really helped so far either.

**Comment by thomashoell** [comment]
We just updated to Rancher 2.7.8, issue remains.

**Comment by JeanGau-ops** [comment]
Do you know where Rancher is saving machines ID of downstream cluster nodes?
My guess is that it didn't refresh it and only knows old ID of deleted nodes, maybe there is a way to update it with the new ones?

**Comment by Oats87** [comment]
Do any of you folks by chance have the `[planner]` prefixed logs from Rancher when it is in this state?

The CAPR planner handles a deleting etcd node by first "draining" other workers/controlplane/etcd nodes from being connected to it via the `--server` parameter. This is why you are seeing the messages from the `[rkebootstrap]` controller as it is refusing to delete the etcd node until no other nodes within the cluster are joined to it.

The `CAPR Planner` is the one responsible for assigning a new plan to the worker nodes in question during this operation, and when it updates the plan it will update the corresponding annotations on the `machine-plan` that indicate it is no longer joined to the deleting node. If the planner is erroring out for some reason then that would explain why the node is never drained.

**Comment by snasovich** [comment]
Changing the milestone and adding `status/release-blocker` for visibility. May get reverted if/as needed.

**Comment by thomashoell** [comment]
> Do any of you folks by chance have the `[planner]` prefixed logs from Rancher when it is in this state?
> 
> The CAPR planner handles a deleting etcd node by first "draining" other workers/controlplane/etcd nodes from being connected to it via the `--server` parameter. This is why you are seeing the messages from the `[rkebootstrap]` controller as it is refusing to delete the etcd node until no other nodes within the cluster are joined to it.
> 
> The `CAPR Planner` is the one responsible for assigning a new plan to the worker nodes in question during this operation, and when it updates the plan it will update the corresponding annotations on the `machine-plan` that indicate it is no longer joined to the deleting node. If the planner is erroring out for some reason then that would explain why the node is never drained.

The planner logs regarding the affected clusters look like this:

```
2023-10-12T08:40:25+02:00	[planner] rkecluster fleet-default/XXXXXXXX: error during plan processing: init node not found
2023-10-12T08:40:25+02:00	[planner] rkecluster fleet-default/XXXXXXXX: error encountered while searching for init node during etcd snapshot creation: init node not found
2023-10-12T08:40:25+02:00	[planner] rkecluster fleet-default/XXXXXXXX: unlocking 27db1692-a4cf-4e0f-9b3f-c3ea4e097f7c
2023-10-12T08:40:24+02:00	[planner] rkecluster fleet-default/XXXXXXXX: attempting to lock 27db1692-a4cf-4e0f-9b3f-c3ea4e097f7c for processing
2023-10-12T08:40:24+02:00	[planner] rkecluster fleet-default/XXXXXXXX: calling planner process
2023-10-12T08:40:24+02:00	[planner] rkecluster fleet-default/XXXXXXXX: handler OnChange called
```

If you need more logs, please let me know. However, looking at the planner logs of the last 30 minutes, I cannot see anything else than this.

**Comment by thomashoell** [comment]
Another strange thing I noticed is that the ETCD snapshots on all our downstream clusters stopped working, even on the ones not affected by the init node issue
![image](https://github.com/rancher/rancher/assets/4695168/42d22c27-d5d9-4b5b-b159-051eadb96cc9)
```
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: updating status missing=true on etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-2fe76 as it was not found in the actual snapshot config map
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: checking to see if etcdsnapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-1ef67 needs to be updated
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: not creating etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-f4b4-7d459 as it is on a local node
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: not creating etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-f4b4-705f7 as it is on a local node
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: updating status missing=true on etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-2f79a as it was not found in the actual snapshot config map
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: checking to see if etcdsnapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-4b703 needs to be updated
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: updating status missing=true on etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-bf3d6 as it was not found in the actual snapshot config map
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: not creating etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-f4b4-9b075 as it is on a local node
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: checking to see if etcdsnapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-aaf30 needs to be updated
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: updating status missing=true on etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-23a4c as it was not found in the actual snapshot config map
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: not creating etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-f4b4-77a27 as it is on a local node
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: checking to see if etcdsnapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-88783 needs to be updated
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: updating status missing=true on etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-323c-c0298 as it was not found in the actual snapshot config map
2023-10-12T15:15:00+02:00	[snapshotbackpopulate] rkecluster fleet-default/xx-xxx-xxxxxxx: not creating etcd snapshot fleet-default/xx-xxx-xxxxxxx-etcd-snapshot-xx-xxx-xxxxxxx-master-f4b4-8fb52 as it is on a local node
```

**Comment by Oats87** [comment]
@thomashoell thank you so much for that. 

I think I've identified the issue -- it stems around the etcd snapshot creation logic that exists within Rancher. I believe a workaround for this would be to set your `spec.EtcdSnapshotCreate` back to `nil` so that the planner doesn't try to "find" an init node. 

I believe this should be reproducible on any cluster that has its init node deleted after a manual etcd snapshot creation is triggered. 

The actual fix for this will be done in the codebase, but I need to think about the way to fix this without causing potential regressions.

**Comment by JeanGau-ops** [comment]
> @thomashoell thank you so much for that.
> 
> I think I've identified the issue -- it stems around the etcd snapshot creation logic that exists within Rancher. I believe a workaround for this would be to set your `spec.EtcdSnapshotCreate` back to `nil` so that the planner doesn't try to "find" an init node for etcd snapshot creation.
> 
> I believe this should be reproducible on any cluster that has its init node deleted after a manual etcd snapshot creation is triggered.
> 
> The actual fix for this will be done in the codebase, but I need to think about the way to fix this without causing potential regressions.

It worked, thank you !

**Comment by thomashoell** [comment]
@Oats87 


> @thomashoell thank you so much for that.
> 
> I think I've identified the issue -- it stems around the etcd snapshot creation logic that exists within Rancher. I believe a workaround for this would be to set your `spec.EtcdSnapshotCreate` back to `nil` so that the planner doesn't try to "find" an init node for etcd snapshot creation.
> 
> I believe this should be reproducible on any cluster that has its init node deleted after a manual etcd snapshot creation is triggered.
> 
> The actual fix for this will be done in the codebase, but I need to think about the way to fix this without causing potential regressions.

Thanks for the update.

However, I can't find ```spec.EtcdSnapshotCreate``` you mentioned.  In ```clusters.provisioning.cattle.io``` as well as in ```rkecontrolplanes.rke.cattle.io``` I only see ```spec.etcd.disableSnapshots```. Can you help me out here?

**Comment by Oats87** [comment]
@thomashoell that's quite interesting. the `rkecontrolplane` should be a descendant object generated based on the `clusters.provisioning.cattle.io` object but there is a 3-way merge that happens when we "apply" the latest `rkecontrolplane` object based on the `clusters.provisioning.cattle.io` object. You may need to manually try to edit the `rkecontrolplane` object to nullify it -- and just confirming, you don't see that spec field on your corresponding `clusters.provisioning.cattle.io`?

**Comment by adventurousyeti** [comment]
Encountering the same issue. I set `spec.EtcdSnapshotCreate` to null in cluster.provisioning.cattle.io. It then failed giving me the following error on the node. 

```shell
Oct 13 12:10:00 stage-dc1-control-prd3-dd70e72c-92xgj rke2[3566904]: time="2023-10-13T12:10:00-05:00" level=error msg="1 snapshots already in progress"
Oct 13 12:10:01 stage-dc1-control-prd3-dd70e72c-92xgj rke2[3566904]: time="2023-10-13T12:10:01-05:00" level=info msg="Waiting for API server to become available"
Oct 13 12:10:02 stage-dc1-control-prd3-dd70e72c-92xgj rke2[3566904]: time="2023-10-13T12:10:02-05:00" level=info msg="runtime is not yet initialized"
Oct 13 12:10:02 stage-dc1-control-prd3-dd70e72c-92xgj rke2[3566904]: time="2023-10-13T12:10:02-05:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Oct 13 12:10:04 stage-dc1-control-prd3-dd70e72c-92xgj rke2[3566904]: time="2023-10-13T12:10:04-05:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"

```

**Comment by Josh-Diamond** [comment]
TIcket #42709 - Test Plan
---

Reproduced on single-instance docker running Rancher `v2.7.6`:
1. Fresh install of Rancher `v2.7.6`
2. Provision a downstream AWS RKE2 cluster w/ 2 node pools - [`etcd + cp`, `wkr`] - with three nodes per pool
3. Once `active`, take a manual snapshot
4. Once snapshot is successfully captured and `active`, navigate to `Cluster Management > Edit Config` and make a modification to the `etcd + cp` node pool - [ I modified `Root Disk Size` ]
5. Reproduced - cluster enters `updating` state; init node hangs in `deleting` state, and the following Rancher logs are seen:
```log
[ERROR] [rkebootstrap] fleet-default/jkeslar-clusterr-bootstrap-template-<REDACTED>: cluster fleet-default/jkeslar-clusterr machine fleet-default/jkeslar-clusterr-pool1-<REDACTED>-<REDACTED> was still joined to deleting etcd machine fleet-default/jkeslar-clusterr-pool1-<REDACTED>-<REDACTED>
```

---

To be validated on Rancher `v2.8-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => modify the `etcd + cp` node pool | _pending_ |
| 2. | Restore local etcd backup - [`only etcd`] | _pending_ |
| 3. | Restore local etcd backup - [`k8s version and etcd`] | _pending_ |
| 4. | Restore local etcd backup - [`cluster config, k8s version and etcd`] | _pending_ |

**Comment by Josh-Diamond** [comment]
TIcket #43142 - Test Results - ✅ 
---

Reproduced on single-instance docker running Rancher `v2.7.6`:
1. Fresh install of Rancher `v2.7.6`
2. Provision a downstream AWS RKE2 cluster w/ 2 node pools - [`etcd + cp`, `wkr`] - with three nodes per pool
3. Once `active`, take a manual snapshot
4. Once snapshot is successfully captured and `active`, navigate to `Cluster Management > Edit Config` and make a modification to the `etcd + cp` node pool - [ I modified `Root Disk Size` ]
5. Reproduced - cluster enters `updating` state; init node hangs in `deleting` state, and the following Rancher logs are seen:
```log
[ERROR] [rkebootstrap] fleet-default/jkeslar-clusterr-bootstrap-template-<REDACTED>: cluster fleet-default/jkeslar-clusterr machine fleet-default/jkeslar-clusterr-pool1-<REDACTED>-<REDACTED> was still joined to deleting etcd machine fleet-default/jkeslar-clusterr-pool1-<REDACTED>-<REDACTED>
```

---

Validated on Rancher `v2.8-c4847070c39209a65029aa3a43347e4d9bac1d12-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => modify the `etcd + cp` node pool | ✅  |
| 2. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => delete the init node | ✅  |
| 3. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => delete one `etcd/cp` node which is NOT the init node | ✅  |
| 4. | Restore local etcd backup - [`only etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 5. | Restore local etcd backup - [`k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 6. | Restore local etcd backup - [`cluster config, k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 7. | Restore s3 etcd backup - [`only etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 8. | Restore s3 etcd backup - [`k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 9. | Restore s3 etcd backup - [`cluster config, k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 10. | Take snapshot, upgrade the K8s version, modify `etcd+cp` node pool, restore to snapshot | Blocked https://github.com/rancher/rancher/issues/42895 |
| 11. | Disable automatic snapshots | Blocked https://github.com/rancher/rancher/issues/42895 |
| 12. | Restore to same snapshot multiple times  - (at least 3 times) | Blocked https://github.com/rancher/rancher/issues/42895 |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, navigate to `Cluster Management > Edit Config` and modify the `etcd+cp` pool - [I changed the Root Disk Size]
5. Verified - cluster successfully updates and comes up `active`; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, delete the init node
5. Verified - cluster successfully removes the node from the cluster + a new node is provisioned in its place; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, delete a node from the `etcd+cp` pool, but NOT the init node
5. Verified - cluster successfully removes the node from the cluster + a new node is provisioned in its place; as expected

---

Snap/restore checks, were taken up as part of the regression check suite for this issue, and https://github.com/rancher/rancher/issues/42895 was encountered, blocking the snap/restore regression checks at this time.

Due to this issue no longer being hit, I'm closing this out as validated, and snap/restore issue encountered will be further tracked and tested in https://github.com/rancher/rancher/issues/42895

**Comment by sadhugit** [comment]
> Do you know where Rancher is saving machines ID of downstream cluster nodes? My guess is that it didn't refresh it and only knows old ID of deleted nodes, maybe there is a way to update it with the new ones?

Rancher stores the machine ID in the secrets, for each node it will create secret with hostname.
