### ISSUE TITLE
[RFE] [RKE1] Migrate Calico installation to operator based

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rancher#42731]
**Is your feature request related to a problem? Please describe.**

To help with the transition between rke1 ==> rke2, we should sync how we use rke1 and rke2 CNI plugins. One of the biggest diff is how we install Calico. rke2 uses the recommended Calico way of installing it, i.e. via the operator. rke1 should do the same.

We would like users/customers to move towards the operator and for that, we want to simplify things as much as possible. This is the plan:
* In 1.27, we want to deploy everything required to run the operator in all rke1-calico deployments. All operator components will be there but inactive. We will document how customers/users can migrate to the operator, which is anyway very well documented in the calico [docs](https://docs.tigera.io/calico/latest/operations/operator-migration)
* In 1.28 and 1.29, for upgrade from 1.27, we will detect if customers/users already migrated. In that case, rke1 upgrades will not deploy the manifest-based components. If customers/users have not already migrated, we will do as in 1.27

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
This was being tracked here: https://github.com/rancher/rke/issues/3328

**Comment by superseb** [comment]
- What is the benefit of installing everything before hand? It makes it easy to migrate but it interacts with the cluster and installs things that are unneeded until the actual choice is made to migrate. Having this a configurable option gives the user insurance nothing will change to the cluster until it is configured. 
- I am missing the plan for Calico regarding what we will support in the future, are we deprecating manifest based at some point or are we keeping around (what do we do when user never migrates? Do we keep updating manifests or do we stop at 3.26? The manifest <-> operator migration is supported for minor versions, so if we move to 3.27 in k8s v1.28, do we deploy 3.27 manifests and update the deployed operator resources for 3.26 if the user has not migrated?

**Comment by thomasferrandiz** [comment]
@superseb 
- As I understand, the idea behind this is that Calico in rke2 only uses the operator so we want to encourage users to use it as well with rke1 as a step to prepare their migration. Installing the operator doesn't use much resource because it does nothing except watch for the creation of the `Installation` CR. 
I think that installing the operator without activating it is way of nudging users towards the direction we want them to take without actually forcing them to do it.

- That's a good question! I don't think we talked in detail about the future. The way I implemented this, we will need to maintain only 1 manifest which contains both the operator and the manifest-based deployment. The choice is done when applying the template through the variable `.CalicoUseOperator` depending on the steps here: https://github.com/thomasferrandiz/rke/blob/09f392b58e60fd7046ebdae05c41d68223477bd7/cluster/network.go#L432

So my guess is that we keep updating both and with the current logic, we upgrade using manifests where the user is still using them and we upgrade the operator resources where the user has migrated.
Ideally, at some point we should deprecate the manifest-based installation but I don't know if that's the plan.

**Comment by superseb** [comment]
Ok, but the user wont know that anything happened so we need to make sure to document this and add it in the release notes. I think it would be good to include the plan with this change, as in, having PM sign off on the deprecation plan for manifest based installs.

I assume there is no other way than to have one file with the operator and the manifest-based deployment as it needs to fit in the current way of doing things, later on we just only have the operator code in the template.
