### ISSUE TITLE
[BUG] `legacy-rolebinding-ownerref-cleaner` handlers fire millions of times per hour

### ISSUE THREAD

**Issue by moio** [rancher/rancher#42846]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart): Helm Chart on k3s
- Proxy/Cert Details: none relevant

**Information about the Cluster**
- Kubernetes version: v1.24.12+k3s1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? None

**Describe the bug**
The Rancher Performance Debugging Grafana dashboard reports >1.5 million executions of the `legacy-rolebinding-ownerref-cleaner` handler in a few hours with 3000 RestrictedAdmin users and 3 downstream clusters.

![Screenshot 2023-08-14 at 17 19 42](https://github.com/rancher/rancher/assets/250541/8c14cf46-3627-46af-8095-76eb0f2f7070)

**To Reproduce**
Create 3000 Restricted Admins, wait few hours, check Rancher Performance Debugging Grafana dashboard.

Creation of the users can be done with the same instructions posted for https://github.com/k3s-io/k3s/issues/8234

**Result**
High hundreds thousands of executions per hour.

**Expected Result**
No excess of executions.

**Comment by git-ival** [comment]
Test passed! Confirmed expected behavior pre-patch and confirmed the `legacy-rolebinding-ownerref-cleaner` controller was removed post-patch.

Pre-patch:
![rancher-cluster-perf](https://github.com/user-attachments/assets/32c8d364-96cb-4bbd-9da6-5c3b96d677f3)
![lasso-controllers](https://github.com/user-attachments/assets/c127e41e-5583-4674-b892-353fb4673760)

Post-patch (rancher `head` image):
![rancher-cluster-perf](https://github.com/user-attachments/assets/e705b0b4-e4dd-48ae-965b-2e06a6fa5894)
![lasso-controllers](https://github.com/user-attachments/assets/b7b39ecc-49ec-4a21-8206-3eca6d5c6559)
