### ISSUE TITLE
[BUG] Rancher logs are consistently generating warnings every few seconds for k8s 1.27 downstream clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#42861]
**Rancher Server Setup**
- Rancher version: `v2.8-head efc48ac`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.27.5+k3s1`
- Proxy/Cert Details: `self-signed`

**Describe the bug**
Rancher logs are filled with the warning logs scrolling through every few seconds continuously.

**To Reproduce**
1. Crate a rancher server on v2.8-head
2. Verify the rancher logs
3. Create a downstream k3s node driver cluster  `v1.27.5+k3s1`, 3 nodes - 1 etcd, 1 cp, 1 worker

**Result**
Rancher logs spammed with the warnings:
```W0919 02:51:59.262869      38 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.```

**Expected Result**
Expected the warning logs not scroll through in the rancher logs.

**Screenshots**
<img width="400" alt="2023-09-18_19-56-46" src="https://github.com/rancher/rancher/assets/38144301/16db2c4a-1c07-49b5-b4ca-4835c6647134">

**Additional Info**

- Also noticed on an rke1 1.27 k8s cluster
- This is not seen for an rke1 cluster on k8s 1.26
- When we delete the k3s cluster, the warnings are gone 
- Also not noticed when the k3s cluster is on k8s `v1.26.8+k3s1`

**Comment by jiaqiluo** [comment]
## Root Causes

`LegacyServiceAccountTokenTracking` is a feature added to `kube-apiserver` and [enabled by default since k8s 1.27](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=LegacyServiceAccountTokenTracking,1.28). ([upstream KEPs](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md#legacyserviceaccounttokentracking))

When kube-apiserver detects an **auto-generated secret-based service account token**, it issues a warning and updates the label `kubernetes.io/legacy-token-last-used` on that secret. 


We can find at least the following secret-based service account tokens, with the mentioned label, in a downstream REK1 1.27 cluster:
```
>  k get secrets -A | grep service-account-token
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
cattle-impersonation-system   cattle-impersonation-u-nflm6bair6-token-cpjv4   kubernetes.io/service-account-token   3      37m
cattle-impersonation-system   cattle-impersonation-u-zvkisepfp7-token-8bb8k   kubernetes.io/service-account-token   3      37m
cattle-impersonation-system   cattle-impersonation-user-2tp2b-token-bjb2m     kubernetes.io/service-account-token   3      37m
cattle-system                 cattle-token-cn4ks                              kubernetes.io/service-account-token   3      37m
cattle-system                 kontainer-engine-token-45fc5                    kubernetes.io/service-account-token   3      37m
cattle-system                 pod-impersonation-helm-op-wxtjm-token           kubernetes.io/service-account-token   3      36m
```
 

## Solutions

To properly mitigate the warning, we should update the corresponding internal components to migrate from auto-generated secret-based tokens to tokens from the TokenRequest API or manually created secret-based tokens.

The exact scope of the changes is still under investigation. 


## Workaround 

As a temporary fix before the above proper solution is implemented, we can disable the feature `LegacyServiceAccountTokenTracking` on `kube-apiserver` when creating/editing the cluster. 

For example, we can set the following on a RKE1 cluster via Edit as YAML:

```
spec:
  rancher_kubernetes_engine_config:
    services:
      kube-api:
        extra_args:
          feature-gates: LegacyServiceAccountTokenTracking=false
```

**Comment by jiaqiluo** [comment]
Link to the EPIC https://github.com/rancher/rancher/issues/41720

**Comment by jiaqiluo** [comment]
Here is the list of service account token secrets found in the local cluster:
```
> k get secrets -A | grep service-account-token
cattle-impersonation-system                           cattle-impersonation-u-b4qkhsnliz-token-z8sv5                           kubernetes.io/service-account-token           3      4d3h
cattle-impersonation-system                           cattle-impersonation-u-mo773yttt4-token-tr6z2                           kubernetes.io/service-account-token           3      4d3h
cattle-system                                         git-webhook-api-service-token-27ltt                                     kubernetes.io/service-account-token           3      4d3h
cluster-fleet-default-imported-rke2-0dc69abd049d      request-vrp9l-b77820b2-1e7b-446a-a483-9534430a63fc-token                kubernetes.io/service-account-token           3      22h
cluster-fleet-default-rke2-node-driver-58b3c1838b36   request-5lvg7-f98e8bbb-fc41-4a66-8a96-85881e7d4046-token                kubernetes.io/service-account-token           3      101s
cluster-fleet-local-local-1a3d67d0a899                request-ptjzg-4a68f20f-e76b-4a4b-af98-9b0c1f6856ae-token                kubernetes.io/service-account-token           3      2d21h
fleet-default                                         import-token-rke2-node-driver-531df574-b785-4e5a-97c2-926-47465-token   kubernetes.io/service-account-token           3      118s
fleet-default                                         rke2-node-driver-bootstrap-template-m6xzl-machine-bootstra8vbft         kubernetes.io/service-account-token           3      6m49s
fleet-default                                         rke2-node-driver-bootstrap-template-m6xzl-machine-plan-tokmzkwb         kubernetes.io/service-account-token           3      5m30s
```

It indicates at least the following Rancher components we should look into:
- Fleet 
- Impersonation system 
- Rancher-webhook
- Provision V2

**Comment by manno** [comment]
Fleet uses [manually created long-lived API tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount) when the k8s doesn't create secrets automatically for service accounts.
This happens for both, the ["request" token](https://github.com/rancher/fleet/blob/master/internal/cmd/controller/controllers/clusterregistration/controller.go#L377) and the ["import" token](https://github.com/rancher/fleet/blob/master/internal/cmd/controller/controllers/clusterregistrationtoken/handler.go#L95).

KEP-2799 states
> [Non-Goals](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md#non-goals)
>
> Removal of [explicitly requested secret-based service account tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token).

Not sure why we would see a warning for those tokens.

**Comment by snasovich** [comment]
> Fleet uses [manually created long-lived API tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount) when the k8s doesn't create secrets automatically for service accounts. This happens for both, the ["request" token](https://github.com/rancher/fleet/blob/master/internal/cmd/controller/controllers/clusterregistration/controller.go?rgh-link-date=2023-09-25T12%3A23%3A51Z#L377) and the ["import" token](https://github.com/rancher/fleet/blob/master/internal/cmd/controller/controllers/clusterregistrationtoken/handler.go?rgh-link-date=2023-09-25T12%3A23%3A51Z#L95).
> 
> KEP-2799 states
> 
> > [Non-Goals](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md?rgh-link-date=2023-09-25T12%3A23%3A51Z#non-goals)
> > Removal of [explicitly requested secret-based service account tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token).
> 
> Not sure why we would see a warning for those tokens.

@manno , the KEP-2799 [states](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md#legacyserviceaccounttokentracking) there is a warning logged when such token is used:
>  - when a legacy token is used, issue a warning, update the label `kubernetes.io/legacy-token-last-used`
    on the secret at date granularity, and record in a metric.

Now, until `LegacyServiceAccountTokenCleanUp` is enabled (probably in 1.29 since that's when it's in Beta) it won't be a problem at all. And even then these tokens will only delete if not used for a long period of time (by default 1 year). Will this eventually be an issue for Fleet then?

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

Rancher's logic which creates service accounts and tokens for those service accounts (which is used in a variety of places, including v2 provisioning) used to store the secret created for a service account on the `Secret` field of the service account. In 1.27, kubernetes considers tokens that are stored on this field legacy tokens, and will [log a warning](https://github.com/kubernetes/kubernetes/blob/5ebb9f319576303cabc0216a8df536b0b4307e67/pkg/serviceaccount/legacy.go#L155) if a user attempts to use one of these tokens while interacting with kubernetes.

Since rancher uses these tokens for a wide variety of functionality (including impersonation, and the `cattle` service account used by v2 prov), this caused a large amount of log messages to appear in Rancher's log.

## What was fixed, or what change have occurred

The core functionality has been updated to have the following behavior:
- It no longer adds new Secrets to the serviceAccount.Secrets field
- New secrets use a label to indicate that they are owned by a particular service account
- When retrieving a secret for a given serviceAccount, we find the secret by using the label referred to in the previous step
  - Secrets which have the label but are not valid secrets (i.e. don't have the matching annotation, and aren't of the type `ServiceAccountToken`) are deleted 

## Areas or cases that should be tested

Generally speaking, the service accounts which are identified in [this commit](https://github.com/rancher/rancher/commit/5e99c85dfc1ad2116a0eeb7922763929ad4a8c), should have the functionality tested. This includes the following service accounts:
- cattle-token
  - This is the main service account that Rancher uses.
  -  In this case, the token is mainly used for the peering service
  - HA Rancher should be tested to ensure that it still can find the other peers (look for log statements surrounding peer add/removal and ensure that you can still access the downstream cluster through Rancher's UI)
- impersonation
  - Impersonation service accounts should be tested to that users can still user rancher through the UI/API/cluster proxy
- monitoring v1
  - Since support for this is dropping in v2.8, this may not be necessary to regression test.
- kontainer-engine
  - This appears to be for RKE1 provisioning
  - Also used in some drivers for AKS, ECS (not sure if this is/was supported), and generic imported clusters.
- CAPR machine bootstrap accounts
  -  This appears to be for v2 provisioning.
- v3.APIService service accounts
  - Rancher provides an `apiservice` crd, that fleet seems to use to expose a webhook endpoint: https://github.com/rancher/fleet/issues/424
  - I would recommend regression testing that area
  - The use case hear appears to be to use the similar remote dailer code as the cattle-token endpoint  

The upgrade test case (of 2.7.x downstream 1.26 -> 2.8.0 downstream 1.26 -> 2.8.0 1.27) should also be tested, to ensure that logs are not present, and that no services have broken.

## What areas could experience regressions

Short overview (see the test case areas for more details on how each area uses this functionality):
- cattle-token
- impersonation
- monitoring v1
- kontainer-engine
- CAPR machine bootstrap accounts
- v3.APIService service accounts

Upgrade cases are of particular concern - These areas should be tested after an upgrade from a 2.7.x version to ensure that components don't suddenly break.

## Are the repro steps accurate/minimal?
Yes, they are included here for convenience: 
1. Deploy Rancher v2.8-head.
2. Deploy a downstream cluster running kubernetes version 1.27+.
3. Go to the cluster in the UI, note that you have warnings flooding your logs.

**Comment by markusewalker** [comment]
Team 2 tested this against `v2.8-head` https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e. There were some issues spotted during upgrade scenarios. See below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision an RKE1 node driver v1.27 cluster, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:white_check_mark:|
|2|As a standard user, provision an RKE2 node driver v1.27 cluster, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:white_check_mark:|
|3|As a standard user, provision an K3S node driver v1.27 cluster, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:white_check_mark:|
|4|As a standard user, provision an RKE1 node driver v1.26 cluster, upgrade to v1.27, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:white_check_mark:|
|5|As a standard user, provision an RKE2 node driver v1.26 cluster, upgrade to v1.27, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:white_check_mark:|
|6|As a standard user, provision an K3S node driver v1.26 cluster, upgrade to v1.27, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:white_check_mark:|
|7|Setup v2.8.0-alpha2, provision an RKE1 v1.27 cluster, upgrade Rancher to v2.8-head, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:x:|
|8|Setup v2.8.0-alpha2, provision an RKE2 v1.27 cluster, upgrade Rancher to v2.8-head, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:x:|
|9|Setup v2.8.0-alpha2 provision an K3S v1.27 cluster, upgrade Rancher to v2.8-head, upgrade to v1.27, validate logs are not consistently generating warnings and that service account tokens are not auto-generated|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.27.6+-rancher1-1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Reviewed the Rancher logs and noted that I do not see repetitive warning messages pertaining to TokenRequest API.
3. In a separate client machine that has the downstream cluster's kubeconfig, ran the command `kubectl get secrets -A | grep service-account-token`. Noted the following:
```
kubectl get secrets -A | grep service-account-token
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
cattle-impersonation-system   cattle-impersonation-u-izrdhggpup-token-64l6d   kubernetes.io/service-account-token   3      4m16s
cattle-impersonation-system   cattle-impersonation-u-jstwt-token-54cqh        kubernetes.io/service-account-token   3      4m16s
cattle-impersonation-system   cattle-impersonation-u-ysttp7r2ha-token-bxvs6   kubernetes.io/service-account-token   3      45s
cattle-system                 cattle-token-k8ttx                              kubernetes.io/service-account-token   3      69s
cattle-system                 kontainer-engine-token-mblf5                    kubernetes.io/service-account-token   3      4m23s
cattle-system                 pod-impersonation-helm-op-rvc7l-token           kubernetes.io/service-account-token   3      44s
```
4. Navigated back to the downstream cluster in Rancher.
5. Scaled the worker node pool up by 1; validated that the logs still do not show the repetitive warning messages pertaining to TokenRequest API.
6. Scaled the worker node pool down by 1; validated that the logs still do not show the repetitive warning messages pertaining to TokenRequest API.

_______

**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream RKE2 `v1.27.6+rke2r1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Validated that I received the same successful results.

________

**Scenario 3**
1. Repeated scenario 1, but provisioned a downstream K3S `v1.27.6+k3s1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Validated that I received the same successful results.

_____

**Scenario 4**
1. As a standard user, provisioned a downstream RKE1 `v1.26.9-rancher1-1` node driver cluster (1 etcd+cp, 1 worker).
2. Upgraded the downstream RKE1 cluster to `v1.27.6-rancher1-1`; validated that the cluster and nodes upgraded successfully.
3. Repeated scenario 1 steps 3-6 with the same successful results.

______

**Scenario 5**
1. As a standard user, provisioned a downstream RKE2 `v1.26.9+rke2r1` node driver cluster (1 etcd+cp, 1 worker).
2. Upgraded the downstream RKE1 cluster to `v1.27.6+rke2r1`; validated that the cluster and nodes upgraded successfully.
3. Repeated scenario 1 steps 3-6 with the same successful results.

______

**Scenario 6**
1. As a standard user, provisioned a downstream K3S `v1.26.9+k3s1` node driver cluster (1 etcd+cp, 1 worker).
2. Upgraded the downstream RKE1 cluster to `v1.26.9+k3s1`; validated that the cluster and nodes upgraded successfully.
3. Repeated scenario 1 steps 3-6 with the same successful results.

________

**Scenario 7**
1. As a standard user, provisioned a downstream RKE1 `v1.27.6-rancher1-1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Reviewed the Rancher logs and reproduced the repetitive TokenRequest API logging messages that rapidly occur.
3. In a separate client machine that has the downstream cluster's kubeconfig, ran the command `kubectl get secrets -A | grep service-account-token`. Noted the following:
```
kubectl get secrets -A | grep service-account-token
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
cattle-impersonation-system   cattle-impersonation-u-dw3arjizsq-token-qchwq                         kubernetes.io/service-account-token   3      19m
cattle-impersonation-system   cattle-impersonation-u-f4mxpwfx3z-token-455nf                         kubernetes.io/service-account-token   3      18m
cattle-impersonation-system   cattle-impersonation-u-jstwt-token-jqw94                              kubernetes.io/service-account-token   3      19m
cattle-system                 cattle-token-7pf4k                                                    kubernetes.io/service-account-token   3      19m
cattle-system                 pod-impersonation-helm-op-mswl4-token                                 kubernetes.io/service-account-token   3      17m
cattle-system                 pod-impersonation-helm-op-xrm25-token                                 kubernetes.io/service-account-token   3      18m
```
4. Upgraded Rancher to v2.8-head; validated that the cluster and nodes remained in an `Active` state.
5. Reviewed the upgrade Rancher logs and noted that the repetitive TokenRequest API logging messages still occur, but at a far more frequent basis.
6. When running `kubectl get secrets -A | grep service-account-tokken`, however, I see the following:
```
kubectl get secrets -A | grep service-account-token
cattle-impersonation-system   cattle-impersonation-u-izrdhggpup-token-5gn2s   kubernetes.io/service-account-token   3      6m38s
cattle-impersonation-system   cattle-impersonation-u-izrdhggpup-token-64l6d   kubernetes.io/service-account-token   3      32m
cattle-impersonation-system   cattle-impersonation-u-jstwt-token-54cqh        kubernetes.io/service-account-token   3      32m
cattle-impersonation-system   cattle-impersonation-u-jstwt-token-mtsc4        kubernetes.io/service-account-token   3      4m28s
cattle-impersonation-system   cattle-impersonation-u-ysttp7r2ha-token-bxvs6   kubernetes.io/service-account-token   3      29m
cattle-system                 cattle-token-87qlt                              kubernetes.io/service-account-token   3      6m4s
cattle-system                 cattle-token-k8ttx                              kubernetes.io/service-account-token   3      29m
cattle-system                 kontainer-engine-token-mblf5                    kubernetes.io/service-account-token   3      32m
cattle-system                 pod-impersonation-helm-op-rvc7l-token           kubernetes.io/service-account-token   3      29m
```
7. Scaled the worker node pool up by 1; noted that the logs still show the repetitive warning messages pertaining to TokenRequest API.
8. Scaled the worker node pool down by 1; noted that the logs still show the repetitive warning messages pertaining to TokenRequest API.

______

**Scenario 8**
1. Repeated scenario 7, but provisioned a downstream RKE2 `v1.27.6+rke2r1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Experienced the same behavior as mentioned in scenario 7.

_____

**Scenario 9**
1. Repeated scenario 7, but provisioned a downstream K3S  `v1.27.6+k3s1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Experienced the same behavior as mentioned in scenario 7.

**Comment by MbolotSuse** [comment]
@markusewalker Scenario 7-9 don't appear to be valid to me, since they involve upgrading from an alpha version of 2.8. Can you run at least one re-test with:
- Start from a valid `2.7.x` version (with a 1.26 downstream, can be any distribution) 
- Upgrade to 2.8-head
- Upgrade the downstream from 1.26 to 1.27

I'll start looking into this in the meantime (since this will likely turn out the same way), but I want to make sure that this isn't an artifact of your test env that won't be present in production.

**Comment by markusewalker** [comment]
@MbolotSuse yeah I actually tested with 2.7.8 and didn't see the issue, so that is why I looked towards the alpha release.

**Comment by markusewalker** [comment]
@MbolotSuse updated the above test plan with the recommended scenarios. Still seeing the issue, but more so during the actual Rancher upgrade. More information in the test cases.

**Comment by anupama2501** [comment]
Validated the following scenarios for the service accounts fresh install v2.8-head `6376016 `, upgrade checks from v2.7.8 to v2.8-head `6376016`

- cattle-token
- Impersonation
- v3.APIService

## cattle-token 


### 1. Verify the service account secret for the cattle token is 0 - Fresh install:
```
1. Create a rancher server v2.8-head
2. Create a downstream cluster rke2 and rke1
3. Verify the cattle-token is created in the local cluster
3. Navigate to service accounts page and verify the secrets value is 0 for the service account
```

### 2. Verify a new label is added to the cattle-token secret
```
1. Create a rancher server v2.8-head
2. Create a downstream cluster rke2 and rke1
3. Verify the cattle-token is created in the local cluster
4. Validate that the new secret has the "[cattle.io/service-account.name]" label set to "cattle"
```
### 3. Verify when the cattle-token is rotated, secret generated is not same as the previous secret:
```
1. Create a rancher server v2.8-head
2. Create a downstream cluster rke2 and rke1
3. Verify the cattle-token is created in the local cluster
4. Verify the log statement for peer adding/removal is recorded
5. Rotate the cattle token
6. Token is not be similar to the previous token
7. Navigate to service accounts page and verify the secrets value is 0 for the service account
8. Validate that the new secret has the "[cattle.io/service-account.name]" label set to "cattle"
```

### 4. Verify the service account secret for the cattle token is 0 - Upgrade:
```
1. Create a rancher server v2.7.8
2. Create a downstream cluster rke2 and rke1
3. Verify the cattle-token is created in the cattle-system namespace
4. Upgrade the rancher server to v2.8-head
5. Verify the downstream clusters are active
6. Verify the log statement for peer adding/removal is recorded
7. Rotate the cattle token
8. Token should not be similar to the previous token
9. Navigate to service accounts page and verify the secrets value is 0 for the service account --> Here the secret value for the token is 1. Since there is an old cattle-token that exists and is not deleted, secret value remains at 1. 
10. Validate that the new secret has the "[cattle.io/service-account.name]" label set to "cattle".
```

##  Impersonation


### 1. Test upgrading from v2.7.8 to v2.8-head HA 
```
1. Start with a 2.7.8 Rancher with auth enabled
2. Setup AzureAD OAuth provider
3. add as cluster owner on a downstream cluster
4. Upgrade to Rancher v2.8-head
5. refresh group memberships
6. try using kubeconfig file
7. Create a downstream cluster logged in as a user from azureAD auth user
8. Verify the cluster creation goes through without errors
```
### 2. Disable and enable a different auth provider
```
1. Setup azuread OAuth provider on v2.8-head
2. add as cluster owner on a downstream cluster
3. Create a downstream cluster as the auth user
4. Disable azureAD and enable openldap
5. Verify no errors were noticed when creating clusters as users from openldap.
```
### 3. Download a kubeconfig from rancher for the downstream cluster and run kubectl commands.
```
1. Create a rancher server on v2.8-head docker install
2. Download the kubeconfig
3. Open the kubectl shell and run the following command:
`kubectl get pods -A`
4. No impersonation errors were observed.
```
### 4. Verify rancher cluster proxy works
```
1. Create a rancher server on v2.8-head
2. Create a downstream cluster rke1 and rke2 clusters
3. Create a standard user and add CO in the downstream clusters
4. Run the curl commands to both the downstream clusters:
`curl -u $APITOKEN [[https://$RANCHERSERVER/k8s/cluster/$CLUSTER/v1/api/namespaces`
5. Verified no impersonation errors were received 
```
### 5. Verify cluster GKE provisioning works as expected
```
1. Create a standard user user1
2. Login as user1 and create a GKE v2 cluster
3. Verify the cluster provisioning works as expected
4. Verified no impersonation errors were observed.
```
### 6. Install a chart in the downstream cluster from cluster explorer and verify the installation goes through
```
1. Create a rancher server on v2.8-head
2. Create a downstream cluster rke1 and rke2 clusters
3. Create a standard user and add CO in the downstream clusters
4. Install monitoring v2 chart in the cluster and verify the installation goes through
5. Click on the grafana dashaboard and verified no errors were seen
```
### 7. Verify single node cluster creation works fine
```
1. Create a rancher server on v2.8-head
2. Create a standard user downstream clusters - user1
3. Create a downstream cluster rke1 and rke2 clusters with 1 node as user1 
4. Cluster comes up active and no errors were noticed.
```
### 8. Messing with the impersonation resources - deleting or modifying them
```
1. Deploy a downstream rke2 cluster
2. delete the SA in the downstream cluster `kubectl -n cattle-impersonation-system delete sa <sa-name>`
3. Download kubeconfig from the cluster on rancher UI
4. access the kubectl of this cluster from local terminal using this kubeconfig
5. The SA gets recreated --> the token does not get recreated for rke1 clusters but for rke2 and k3s clusters, it gets recreated.
```

### 9. Enable auth provider and do not refresh user memberships
```
1. Setup azuread OAuth provider
2. add as cluster owner on a downstream cluster
3. remove the user from auth provider authorized user list
4. try using kubeconfig file
5. Verified no impersonation errors were observed. 
```


##  v3.APIService

### 1. fleet upgrade checks
```
1. Have a Rancher 2.7.8 setup with two downstream clusters
2. In Cluster Explorer (Dashboard) navigate to Left main menu dropdown?_ Continuous Delivery
3. Create a GitRepo
Use the url: https://github.com/rancher/fleet-examples
	Path: multi-cluster/helm
4. Deploy To: select the two downstream clusters.
5. Upgrade rancher server to v2.8-head
6. Verify fleet repos work fine and come up active.
7. Create a new fleet git repo, verify the repo is active and no errors observed.
```

### 2. v3.APIService service accounts - fleet P0 checks
```
1. Have a Rancher 2.8-head setup with two downstream clusters
2. In Cluster Explorer (Dashboard) navigate to Left main menu dropdown?_ Continuous Delivery
3. By this point the two downstream clusters should be listed in the Clusters objects.
4. Create a GitRepo
Use the url: https://github.com/rancher/fleet-examples
b	Path: multi-cluster/helm
5. Deploy To: select the two downstream clusters."
```

**Comment by anupama2501** [comment]
Fleet checks for the following use case will be validated as part of the linked issue by fleet team. 
```
 v3.APIService service accounts
Rancher provides an apiservice crd, that fleet seems to use to expose a webhook endpoint: https://github.com/rancher/fleet/issues/424 
```

**Comment by manno** [comment]
> Rancher provides an apiservice crd,

Fleet does not use any Rancher CRDs. I'm not aware of code in rancher/rancher that connects fleet to the apiserver CRD. I don't think there is any UI for it?

**Comment by manno** [comment]
> @manno , the KEP-2799 [states](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token/README.md#legacyserviceaccounttokentracking) there is a warning logged when such token is used:
> 
> > * when a legacy token is used, issue a warning, update the label `kubernetes.io/legacy-token-last-used`
> >   on the secret at date granularity, and record in a metric.

I can see the secrets are marked with the "last used" label, but I'm not sure if the warning code is correct.
Legacy tokens (secrets) are listed in the service accounts secret list. An "explicitly requested token" is not.
If the service account secret list is not populated automatically, which is the case since k8s 1.22,  Fleet uses the new, explicit approach. 

According to the [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount):

> You can still manually create a service account token Secret; for example, if you need a token that never expires.




> Now, until `LegacyServiceAccountTokenCleanUp` is enabled (probably in 1.29 since that's when it's in Beta) it won't be a problem at all. And even then these tokens will only delete if not used for a long period of time (by default 1 year). Will this eventually be an issue for Fleet then?

It's not the goal of KEP-2799 to clean up explicitly requested tokens. The clean up code skips these tokens: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/legacy_serviceaccount_token_cleaner.go#L260

We have to consider upgrade scenarios, though. If a user upgrades from k8s < 1.22 to 1.29, will that invalidate tokens? In that case a re-registration of the clusters might be necessary and should fix any issues.

**Comment by manno** [comment]
> > Rancher provides an apiservice crd,
> 
> Fleet does not use any Rancher CRDs. I'm not aware of code in rancher/rancher that connects Fleet in Rancher to the apiserver CRD. I don't think there is any UI for it.

As described in https://github.com/rancher/fleet/issues/1865#issuecomment-1766661851 it turns out Fleet (Gitjob) has a loose contract with steve, based on a shared secret. However the secret name does not match between Gitjob and Rancher, so the URL does not work.

@anupama2501 

> Rancher provides an apiservice crd, that fleet seems to use to expose a webhook endpoint: https://github.com/rancher/fleet/issues/424 

If the apiservice resource is a problem, we can remove the code from Rancher for now. If we decide to bring back the feature we'll add it back with testing. In any case, Fleet is not using it now and hasn't been using for two years.

**Comment by anupama2501** [comment]
thanks @manno.  As the feature is currently not functional, it might be better to eliminate the code associated with this feature.

**Comment by ibrokethecloud** [comment]
harvester is also leveraging steve aggregation to define routes for harvester services
```
apiVersion: management.cattle.io/v3
kind: APIService
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yQwU6EMBCG32XO7JZFFrI8hPHgzXiYtr9QA5R0Zolmw7ubcjCrJh7b+fJ//8yNJih7VqbuRjzPUVlDnCU/o32HU4EeU4hHx6ojjiGa4KmjgdMKUaQDL0GQ1uBAW0EuYU94DhNEeVqom6/jWNDIFuO/uQPLQB1V1rqmaqq29Rd/qtpzDb40vuayqbkpH+qyhD23bbbNPOG+TP6TBS5rFtbhKeEtfECoeyGznsw3aKgg41kGGzl5Q6/Fzv8F80TgEvTxl+vAfZ/Q79vSPSQLu5+kfIpi2ssp6zVfYdu+AgAA///MSg2gfAEAAA
    objectset.rio.cattle.io/id: harvester-apiservice
  creationTimestamp: "2023-05-03T02:07:49Z"
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: 2bbc626277d9d12754ea96d4a064a603400eb577
  name: harvester
  resourceVersion: "6044"
  uid: a8984a5b-f7f3-4df7-b01c-94dfc627e6d7
spec:
  pathPrefixes:
  - /v1/harvester/
  - /dashboard/
  paths:
  - /v1/harvester
  secretName: harvester-aggregation
  secretNamespace: harvester-system
status:
  serviceAccountName: harvester-api-service
  serviceAccountNamespace: cattle-system
```

**Comment by anupama2501** [comment]
Closing this issue as the harvester checks will be run as part of the linked issue. https://github.com/harvester/harvester/issues/4657
