### ISSUE TITLE
Rancher Convoy fails to read volume

### ISSUE THREAD

**Issue by iangcarroll** [rancher/rancher#4289]
Rancher Version: v1.0.0

Docker Version: v1.10.3

OS: Ubuntu 15.10

Steps to Reproduce: 
1) Create a GlusterFS cluster
2) Reboot one of the nodes
3) Reboot/upgrade the GlusterFS cluster (not required for GlusterFS to stop responding; containers with its mounted volumes will receive 'transport endpoint not connected' before this)
4) Try to inspect the volume with `docker volume inspect postgresql`

Results: 

```
Apr 05 03:39:07 rancher3 docker[1047]: time="2016-04-05T03:39:07.508656279Z" level=error msg="VolumeDriver.Get: error reading plugin resp: invalid character 'H' looking for beginning of value"
Apr 05 03:39:07 rancher3 docker[1047]: time="2016-04-05T03:39:07.509228451Z" level=error msg="Handler for GET /v1.21/volumes/postgresql returned error: get postgresql: invalid character 'H' looking for beginning of value"
Apr 05 03:39:07 rancher3 docker[1047]: time="2016-04-05T03:39:07.551258087Z" level=error msg="VolumeDriver.Get: error reading plugin resp: invalid character 'H' looking for beginning of value"
Apr 05 03:39:07 rancher3 docker[1047]: time="2016-04-05T03:39:07.748971059Z" level=error msg="Couldn't run auplink before unmount: signal: segmentation fault (core dumped)"
Apr 05 03:39:07 rancher3 docker[1047]: time="2016-04-05T03:39:07.761310731Z" level=error msg="Handler for POST /v1.18/containers/a3c6aaecb809ad51996b9e7ef00614735badc63d968cef2e138287ba087ab720/start returned error: get postgresql: invalid character 'H' looking for beginning of value"
```

Expected:
It to return details about the volume.

**Comment by sangeethah** [comment]
Similar issue is  tracked in https://github.com/rancher/rancher/issues/3671

**Comment by cjellick** [comment]
Gluster specific issue. No need to go into 1.2.0, right?

**Comment by deniseschannon** [comment]
@iangcarroll We have removed GlusterFS and Convoy Gluster from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  However, due to lack of active maintenance, we cannot recommend this solution going forward.

Instead, we recommend and certify Convoy NFS, which is actively maintained by Rancher. As a user, you can get GlusterFS support directly from Red Hat and use it in Rancher using Rancher's NFS plugin. 

Due to these changes regarding glusterfs and convoy gluster, we will not be addressing this bug for 1.2.0

**Comment by deniseschannon** [comment]
Closing in favor of #3671 and recommending using the new storage options.
