### ISSUE TITLE
CRTB/PRTB created without validating clusterName and logs keep generating with errors

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#42928]
CRTB/PRTB created without validating clusterName in the yaml and logs keep generating with errors for every second.

CRUD/Kubectl : Create prtb with steve api(v1)/kubectl by passing an Notexisted clusterName is creating the PRTB and it is throwing errors in Logs for every second. 

**Steps:**

1. Provision rancher
2. Create a downstream cluster
3. Try to create a PRTB with kubectl (make sure to pass a not exisitng clusterName)

prtb_create.yaml

```
apiVersion: management.cattle.io/v3
kind: ProjectRoleTemplateBinding
metadata:
  name: dastest3213
  namespace: p-2s7jl
  labels:
      hello: world45
projectName: c-not-existed:p-2s7jl
roleTemplateName: project-owner
userPrincipalName: local ://user1
```
kubectl create -f ~/Downloads/prtb_create.yaml
projectroletemplatebinding.management.cattle.io/dastest3213 created

**Result:**
1. The PRTB is created without any errors
2. Every few seconds - logs are filling with ERRORs 

**Expected:**
1. PRTB should not be created
2. Suppose to throw an error saying the clusterName is not found

**Note:** 
1. Both kubectl and Seve(v1) API are behaving the same
2. Norman API also behaving the same
3. CRTB also having the same issue

**LOGS:** 

```

2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:32 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:33 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
W0922 17:40:33.626701      46 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
2023/09/22 17:40:34 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
W0922 17:40:35.105205      46 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
2023/09/22 17:40:36 [ERROR] error syncing 'p-2s7jl/dastest32': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-vqkz877j/p-2s7jl" not found, requeuing
2023/09/22 17:40:36 [ERROR] error syncing 'p-2s7jl/dastest3213': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:37 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:42 [ERROR] error syncing 'p-2s7jl/daspsada6423427dd': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-not-existed/p-2s7jl" not found, requeuing
W0922 17:40:45.065055      46 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
2023/09/22 17:40:46 [ERROR] error syncing 'p-2s7jl/dastest32': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-vqkz877j/p-2s7jl" not found, requeuing
2023/09/22 17:40:46 [ERROR] error syncing 'p-2s7jl/dastest3213': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-not-existed/p-2s7jl" not found, requeuing
2023/09/22 17:40:46 [ERROR] error syncing 'helm3-library': handler catalog: Update failed: fatal: unable to access 'https://git.rancher.io/helm3-charts/': The requested URL returned error: 504
: exit status 128, requeuing
```

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

The webhook provided some validation of the `projectName` field, but did not perform any validation on the clusterName part of the field (the first part before the `:`).

## What was fixed, or what change have occurred

Webhook validation has been added which validates the following:
- That the clusterName part of the field was provided (alongside the projectName)
- That the clusterName refers to a valid `management.cattle.io/cluster`
- That the project specified by the projectName part of the field (the part after the `:`) has the following requirements:
  - It refers to a valid `management.cattle.io/project`
  - That the `project.Spec.Cluster` matches the clusterName part of the PRTB field

## Areas or cases that should be tested

- Creating a PRTB that does not specify any clusterName `:some-project` -> deny
- Creating a PRTB that does not specify any projectName `some-cluster:` -> deny
- Creating a PRTB that specifies a non-existent cluster `not-found:some-project` -> deny
- Creating a PRTB that specifies a non-existent project `some-cluster:not-found` -> deny
- Creating a PRTB that specifies a project that is for a different cluster than specified `some-cluster:some-project-not-in-some-cluster` -> deny
- Creating a PRTB that specifies a project that is different than the PRTB Namespace `some-cluster:some-project` (create the PRTB in the default namespace) -> deny
- Creating a PRTB that specifies a valid project in a valid cluster in the correct namespace `some-cluster:some-project`

## What areas could experience regressions

Existing PRTB validation.

## Are the repro steps accurate/minimal?
Yes. The issue is up-to-date and accurate.
