### ISSUE TITLE
[RFE] Rancher CLI doesn't have a driver for AzureAD for authenticating with kubectl

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42939]
In order to switch to AzureAd for authentication provider, we need AzureAD support in rancher CLI to be able getting token for kubectl dynamically. 

SURE-4275

**Comment by MKlimuszka** [comment]
Assigning @crobby to work on the design phase.

**Comment by MKlimuszka** [comment]
@Priyashetty17 It's very likely and planned for the Q1 feature release.

**Comment by enrichman** [comment]
## QA Testing

### Root cause

Added Azure AD provider for authenticating with kubectl through the Rancher CLI.

### What was fixed, or what changes have occurred

The issue was fixed adding some configurations to Rancher (https://github.com/rancher/rancher/pull/44285). The PR also added the validation of the token retrieved by the Rancher CLI.

The Rancher CLI is now able to perform the login with Azure AD with this PR: https://github.com/rancher/cli/pull/346.

Documentatio nwas updated here: https://github.com/rancher/rancher-docs/pull/1311

### Areas or cases that should be tested

- `kubectl` with Rancher CLI

### What areas could experience regressions?

_none_

### Steps

#### Enable Azure AD provider

We need to enable the Azure AD provider. To do so we can use an existing application, or create a new one.  

Docs on how to do this can be found here: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad

Please remember to enable the **Public Cl;ient Flows**, as written in the new docs:

---
To login from Rancher CLI you must allow public client flows.

1) From the left navigation menu, select **Authentication**.
2) Under **Advanced Settings**, select **Yes** on the toggle next to **Allow public client flows**.
---

#### Disable `kubeconfig-generate-token`

In Rancher go to _Global Settings_ > _Settings_ and set the `kubeconfig-generate-token` flag to `false`.  

#### Kubeconfig file

Download and export/use a kubeconfig file from a cluster. This Kubeconfig should contain an exec command to use the `rancher` CLI to login.

#### Rancher CLI

Be sure to download and use the latest (`rc`?) `rancher` CLI, with the support for the Azure AD provider.

Releases: https://github.com/rancher/cli/releases

**IMPORTANT NOTE:** to properly test this the Rancher CLI needs to be in your PATH, and needs to be executed through the `rancher` command. If not when running `kubectl` commands it won't work.

#### Test Kubectl

https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/kubectl-utility#authentication-with-kubectl-and-kubeconfig-tokens-with-ttl

Now to test everything you will have to run a `kubectl` command, such as:

```
kubectl get pods -A
``` 
Then kubectl should execute the `rancher` CLI, so the user should be prompted to login through the localProvider or the azureADProvider.

Selecting the azureADProvider will start the login flow, so the user will be prompted to login through the Microsoft URL, and provides a code.

Finally the `kubectl` command will execute, and the token will be cached.

To try again the login you will need to clear the Rancher CLI cache, with `rm ~/.rancher/cli2.json`.

**Comment by dasarinaidu** [comment]
I am validating this card on v2.9-head & CLI v2.9.0-rc4 & found below observations:

1. The Auth provider options are not correctly sorted

- I connected to OpenLDAP and i run the CLI the Auth providers list coming in the order as below

```
      Auth providers:
      0 - localProvider
      1 - openLdapProvider
     Select auth provider: 
```

Ex:
kubectl get pods -A
INFO[0000] Saving config to /Users/XXXXXXX
https://XXXXXX/v3-public/authProviders
Auth providers:
0 - localProvider
1 - openLdapProvider
Select auth provider: 

- When I connected to AzureAd and i run the CLI the Auth providers list coming in the order as below(Constancy is missing)
https://XXXXX/v3-public/authProviders
  Auth providers:
```
  0 - azureADProvider
  1 - localProvider
   Select auth provider: 
```

**Expected:** The sorting order should be the same like openLdap auth

2. Tokens are NOT deleted as soon as the Auth is disabled, after the Auth is disabled but the token is existed and user can continue to use the token and get the details.

Note: Happening on all auth providers (I tested with Azure AD and OpenLDAP)

**Steps:**
1. Provision rancher v2.9-head
2. Enable  AzureAD
3. CLI v 2.9.0-rc4
4. From CLI --> Connect to AzureAD
5. Check for the token from UI (Profile->Account and API Keys) -- The token is created and it marked as AzureAd https://{{HOST}}/v3/tokens/kubeconfig-user-token
6. User can loginto CLI with this token : `rancher login --token kubeconfig-user-66nbv6t4cw:l45pcgldfgdfgd https://{{HOST}}`
7. Disable the Auth provider 
8.  Check for the token from UI (Profile->Account and API Keys) -- The token should be deleted and longer should work
9. User can loginto CLI with this token : `rancher login --token kubeconfig-user-66nbv6t4cw:l45pcgldfgdfgd https://{{HOST}}`

**Expected:**  As soon as the auth is disabled the token is not deleted and the user can use that token for one month(expiration says 30days)

**Comment by dasarinaidu** [comment]
Observation 1 : https://github.com/rancher/rancher/issues/46128

**Comment by samjustus** [comment]
**Release Note - Known Issue**
https://github.com/rancher/rancher/issues/46128

**Comment by dasarinaidu** [comment]
Validations completed on this card and looks good. No new issues reported.
v2.9-head & CLI v2.9.0-rc4
