### ISSUE TITLE
[BUG] Unable to login with api using keycloak oidc user

### ISSUE THREAD

**Issue by samuelbartel** [rancher/rancher#43027]
**Rancher Server Setup**
- Rancher version: v 2.7.4

**Describe the bug**
I have setup keycloak odic authprovider for rancher and i have created user on keycloak.
Using the GUI i can connect to rancher using the keycloak odic authprovider.

When I try to do the same using the API it doesn’t work
i have try to generate directly a token from keycloak API protocol/openid-connect/token but the generate token is not recongnized by rancher i got an authentication failed when trying to use it as BEARER token

When I try to use the rancher keycloak oidc provider url from the public API (v3-public/keyCloakOIDCProviders/keycloakoidc?action=login) i got 404 error on the redirection to rancher verif-auth url

I understand that everything doable from the gui can be achieve using the API.
What is the correct workflow to authenticate with a keycloak user to rancher using the API? any documentation or example around?

**Comment by slickwarren** [comment]
Hello, this workflow is not supported, as our product doesn't support direct use of the API at this time. We don't have much documentation around this, since it is not supported, however we do have some tools like Terraform that you could use instead. Our rancher CLI is also technically an option, though this is currently dated and likely won't help with the issue you're seeing.
