### ISSUE TITLE
[BUG] Unnecessary node restart during vSphere provisioning on RHEL 8.8

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43119]
**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart): HA 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.24.15, Docker 23.0.6, RHEL 8.8
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.13
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  RKE1 vSperer node-driver, RHEL 8.8

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin 

**Describe the bug**

One customer reports that they sometimes fail to add a new node to an existing RKE1 node-driver cluster. The new node is stuck in rebooting.  

The customer uses a custom image based on RHEL 8.8 for Rancher to create VMs in vSphere. The `NetworkManager` feature is disabled in the image; the image contains a cloud-init script that takes more than 120 seconds to run.  

It turns out that Rancher reboots the node at one point during the provisioning process which interrupts the execution of the cloud-init script, which in turn causes another root-booting down in the process. As a result, the VM is stuck in a loop of restarting.  

Rancher is supposed to reboot the OS only when it is necessary, for example, when it needs to disable the `NetworkManager` feature, However,  it seems like this rebooting operation is unconditional, which means it is executed even when the `NetworkManager` has been disabled.   ([code](https://github.com/rancher/machine/blob/4b574c7f1980751f16edcf620b7eaec855d29843/libmachine/provision/redhat.go#L132))

It has been confirmed to be the solution that Rancher should not reboot the OS when the `NetworkManager` feature has been disabled. 

**To Reproduce**

It is not easy to reproduce the issue as we do not have the particular image used by the customer. 
The general steps are:
- create a custom image, the OS needs to be RHEL,  the `NetworkManager` feature should be disabled by default, and the image contains a cloud-init script that takes more than 120 seconds to run.  
- create an RKE1 node-driver cluster by using the above image for nodes, the infrastructure provider is not necessary to be vSphere 
- wait for the cluster to be active
- if the cluster becomes active and all nodes look good, try to scale up one node pool to add one new node 

**Result**

- The new node never be added successfully, and the VM keeps rebooting the OS.

**Expected Result**

The node should be added successfully with no rebooting. 

**Screenshots**

**Additional context**

SURE-6949

**Comment by jiaqiluo** [comment]
### Root cause

When provisioning a VM that runs RHEL, rancher-machine will disable the network-manager service and then reboot the VM. However, the reboot command is now unconditional, which means it still reboots the VM when the `network-manager` service has been disabled by default. This behavior causes problems in certain scenarios.


### What was fixed, or what changes have occurred

The fix is within Rancher-machine: now it will skip the rebooting step if the `network-manager` service has been disabled by default.
  
### Areas or cases that should be tested
  
Node-driver cluster provisioning with RHEL as the OS for nodes, and the `network-manager` service is disabled by default.


### What areas could experience regressions?

- create new node-driver cluster 
- in the Rancher-upgrade scenario, add a new node in an existing node-driver cluster 

### Are the repro steps accurate/minimal?

Yes. 

### Additional Notes to QA

The key validation for this fix is to confirm the VM is NOT rebooted during the provisioning process. 
I have not tried it myself, but it looks like the command [last reboot](https://www.cyberciti.biz/tips/linux-last-reboot-time-and-date-find-out.html) can be used to retrieve this information. You may want to take a deeper look.

**Comment by jiaqiluo** [comment]
The fix can be validated in the latest Rancher v2.8-head.
For more information about validating the fix, please check [this comment](https://github.com/rancher/rancher/issues/43119#issuecomment-1858320251)

**Comment by susesgartner** [comment]
Automation note: No automation testing needed for this ticket

**Comment by susesgartner** [comment]
Ticket #43119 - Test Results - ✅ Pass
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Validate node doesn't reboot | PASS |
| 2. | Scale Node driver cluster | PASS |
 
---
Validated with Docker on Rancher `v2.8-head`:
---

Scenario 1: Validate node doesn't reboot
---
1. Create an Rhel 8.8 image with NM disabled and network service enabled
2. Create a downstream rancher cluster using the image in step 1
3. Validate that no reboot occurs during provisioning.
 
 
Results:
No reboot occurred on the downstream nodes and the cluster came up successfully.

Scenario 2: Scale Node driver cluster
---
1. Create an Rhel 8.8 image with NM disabled and network service enabled
2. Create a downstream rancher cluster using the image in step 1
3. Scale the cluster up.
4. Validate that no reboots are observed and the cluster remains in a stable state.
 
 
Results:
No reboot occurred on the downstream nodes and the cluster scaled successfully.
