### ISSUE TITLE
[v2.8] Bump etcd image to 3.5.9 in KDM

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#43130]
SURE-6162

**Comment by vivek-shilimkar** [comment]
Validated the ETCD version bump for k8s v1.27, v1.26 and v1.25 as documented on the Qase.

Tested the following three scenarios on k8s v1.25.16-rancher2-1, v1.26.11-rancher2-1 and v1.27.8-rancher2-1.

1. Fresh Install checks
2. Upgrade checks
3. Downstream cluster checks.

Made sure on all the above 3 scenarios the ETCD version on the etcd node was 3.5.9.

Since the ETCD version is correct, closing the issue.
