### ISSUE TITLE
[RFE] Rancher-Selinux RHEL 9 Support

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#43146]
**Is your feature request related to a problem? Please describe.**
RHEL 9 doesn't support GPG SHA1 that is associated with the rancher-selinux package and fails on install. 

**Describe the solution you'd like**
Rancher-selinux should support RHEL 9

**Additional context**

We'll need to test logging, as implemented here: https://github.com/rancher/rancher/issues/31311

SURE-6646

**Comment by macedogm** [comment]
PRhttps://github.com/rancher/rancher-selinux/pull/20

**Comment by andypitcher** [comment]
Procedure to test rancher-selinux (RHEL9):


`rancher-selinux` test on Centos9 (RHEL9) was **successful**.

#### Environment and versions used:

- Server: Centos Stream 9 x86_64
- Cluster: rke1-v1.26.8 (standalone with etcd/controplane/worker)
- kubectl: v1.28.2
- helm: v3.13.1
- rancher: v2.7.6

#### Generate rancher-selinux rpm:

1. Generate the rancher-linux rpm (use the centos-stream9 branch), and copy the generated files locally from the container (will use it later to install it on the Centos9 server).
```
> podman run --rm -it -v $(pwd):/code quay.io/centos/centos:stream9
# yum install -y epel-release && yum -y install container-selinux selinux-policy-devel yum-utils rpm-build git
# ./policy/centos9/scripts/build
```

#### Procedure to prepare the env to test rancher-selinux rpm:

1. Spin up a Centos9 instance and install the requirements (rke, kubectl, helm, docker and SELinux packages)
  ```
    1  yum update -y
    2  yum install -y epel-release && yum -y install container-selinux selinux-policy-devel setools
    3  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    5  mv kubectl /usr/bin/
    6  chmod +x /usr/bin/kubectl
    8  yum install -y yum-utils
    9  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
   10  yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
   12  curl -LO https://github.com/rancher/rke/releases/download/v1.4.10/rke_linux-amd64
   14  chmod +x rke_linux-amd64
   15  mv rke_linux-amd64 /usr/bin/rke
```
3. Create a RKE1 cluster, use the [RKE install minimum conf](https://rke.docs.rancher.com/installation#creating-the-cluster-configuration-file)
4. Install rancher through helm, as described [here](https://ranchermanager.docs.rancher.com/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster#install-the-rancher-helm-chart).

Tools to debug SELinux AVCs (denies), this will be helpful to catch any errors related to rancher's resources to access host's resources and being blocked by SELinux.
```
# ausearch -m avc -ts recent
# tail -f /var/log/audit/audit.log | grep denied
# sealert -a /var/log/audit/audit.log
```

#### Procedure to test the Logging V2 and debug/apply SElinux's policy:

Documentation: https://ranchermanager.docs.rancher.com/v2.5/reference-guides/rancher-security/selinux-rpm/about-rancher-selinux#configuring-the-logging-application-to-work-with-selinux

1. Install Logging V2 though the GUI Charts, without rancher-selinux and global.seLinux.enabled to false (default) - This will help to catch the SELinux AVCs.
2. The install goes through but rancher-logging-rke-aggregator fails.

![image](https://github.com/rancher/rancher-selinux/assets/12878731/68b00521-562c-4960-886e-cad652181461)

`Fluent-bit` needs to access /var/lib/rancher/rke/log/*.log which has these contexts:
```
[root@centos9-apitcher-selinux ~]# ls -Z /var/lib/rancher/rke/log/
system_u:object_r:var_lib_t:s0 etcd_11105ebcdf619a602b0442473059840f349074fd258d6fa92ec9aa122ed542f6.log
system_u:object_r:var_lib_t:s0 etcd-rolling-snapshots_7879ed4bc8c82a54038e8be2a2f828a1e857c3ef146724eb83b4a455a7bd958e.log
system_u:object_r:var_lib_t:s0 kube-apiserver_d027b11a528d315ec04f32161a88c13e6f24691e5a468260f5d07039bafb2c7d.log
system_u:object_r:var_lib_t:s0 kube-controller-manager_c4b374457aacd645cd540ed1bd2cfb10ad3351e3262871fa2b1944269e58f9a9.log
system_u:object_r:var_lib_t:s0 kubelet_8af1ccdc40f32ca841e7a267c94249f3f32fe5c54894c1ea19d5ea5ff9e8e7cc.log
system_u:object_r:var_lib_t:s0 kube-proxy_c0cdad203f3f9834855cd465d89be22129ee52a71a238834362eb6a585a89ed3.log
system_u:object_r:var_lib_t:s0 kube-scheduler_a0b67f0f059b46066653b5a41df2ac3c022b1faa73869d4698a6b706843708ef.log
```

SELinux's AVC related

![image](https://github.com/rancher/rancher-selinux/assets/12878731/07e16de3-ee1a-49c1-9aa8-094ee617dfb8)


3. Fix the issue, by installing rancher-selinux rpm to have /var/lib/rancher/rke/log/ be `system_u:object_r:container_var_lib_t:s0` instead of `system_u:object_r:var_lib_t:s0`
`yum install /tmp/centos9/noarch/rancher-selinux-0.0~unknown-0.el9.noarch.rpm`
4. Reinstall/update Logging V2 with global.seLinux.enabled to true
5. Logging V2 can now be used.

**Comment by macedogm** [comment]
Adding further instructions on top of Andy's comment, the testing of Rancher's SELinux RPM for EL9 can be installed with:

1. Create in the directory `/etc/yum.repos.d/` a file named `rancher-selinux-testing.repo` with the contents below.

```
[rancher-selinux-testing] 
name=Rancher-SELinux-Testing
baseurl=https://rpm-testing.rancher.io/rancher/testing/centos/9/noarch
enabled=1 
gpgcheck=1 
gpgkey=https://rpm-testing.rancher.io/public.key 
```

2. Execute `yum update`.

3. Install the testing Rancher SElinux package (some dependencies might be pulled together):

```
# yum install -y rancher-selinux
Last metadata expiration check: 0:01:08 ago on Mon Oct 30 17:38:11 2023.
Dependencies resolved.
==============================================================================================================================================================
 Package                                 Architecture                   Version                                 Repository                               Size
==============================================================================================================================================================
Installing:
 rancher-selinux                         noarch                         0.3~rc1-2.el9                           rancher-testing                          18 k

Transaction Summary
==============================================================================================================================================================
Install  1 Package

Total download size: 18 k
Installed size: 101 k
Downloading Packages:
rancher-selinux-0.3~rc1-2.el9.noarch.rpm                                                                                       22 kB/s |  18 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                          22 kB/s |  18 kB     00:00     
Rancher-Testing                                                                                                               3.4 kB/s | 2.4 kB     00:00    
Importing GPG key 0xD161F542:
 Userid     : "Rancher (CI) <ci@rancher.com>"
 Fingerprint: 856A 0069 529C A63B 21AA 4E0A 089F A20E D161 F542
 From       : https://rpm-testing.rancher.io/public.key
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                      1/1 
  Installing       : rancher-selinux-0.3~rc1-2.el9.noarch                                                                                                 1/1 
  Running scriptlet: rancher-selinux-0.3~rc1-2.el9.noarch                                                                                                 1/1 
  Verifying        : rancher-selinux-0.3~rc1-2.el9.noarch                                                                                                 1/1 

Installed:
  rancher-selinux-0.3~rc1-2.el9.noarch                                                                                                                        

Complete!
```

Notes:
1. The package is for EL9.
2. The package is still testing only, once it passed all of QA's validations and tests, the we will tag the production version in `rpm.rancher.io` repo.

**Comment by andypitcher** [comment]
[v0.3-rc1.testing.2](https://github.com/rancher/rancher-selinux/releases/tag/v0.3-rc1.testing.2) is now fully operational, all rpms (EL7, EL8, EL9 and MicroOS) are available for testing.

cc @samjustus @macedogm

**Comment by andypitcher** [comment]
[v0.3-rc1.testing.3](https://github.com/rancher/rancher-selinux/releases/tag/v0.3-rc1.testing.3) will be the final version before tagging to production.

**Comment by andypitcher** [comment]
As per QA tests on `v0.3-rc1.testing.3`, we've adapted the policy for rhel8 and rhel9 ([expand watch permission](https://github.com/rancher/rancher-selinux/pull/38)), here is the new RC to use: [v0.3-rc1.testing.4](https://github.com/rancher/rancher-selinux/releases/tag/v0.3-rc1.testing.4)

**Comment by rishabhmsra** [comment]
With selinux permissive and enforce mode, performed below steps:

- Created 3 nodes on AWS, using RHEL 9 (ami-078cbc4c2d057c244)
- Followed steps mentioned [here](https://github.com/rancher/rancher/issues/43146#issuecomment-1766601167) and [here](https://github.com/rancher/rancher/issues/43146#issuecomment-1787932330).
- Created RKE1 `v1.26.11-rancher2-1` standalone cluster, using rke v1.4.12.
- Deployed rancher v2.7.9 on the cluster.
- Validated there were NO denied AVCs.
- Installed logging v2 chart on local cluster and validated P0 scenarios, it's working as expected.
- Validated there were NO denied AVCs.
-------
- Performed above steps and provisioned k3s `v1.26.11+k3s2` standalone clusters.
- Deployed rancher v2.7.9 on the cluster.
- Validated there were NO denied AVCs.
- Installed logging v2 chart on local cluster and validated P0 scenarios, it's working as expected.
- Validated there were NO denied AVCs.

**Comment by andypitcher** [comment]
> With selinux permissive and enforce mode, performed below steps:
> 
> * Created 3 nodes on AWS, using RHEL 9 (ami-078cbc4c2d057c244)
> * Followed steps mentioned [here](https://github.com/rancher/rancher/issues/43146#issuecomment-1766601167) and [here](https://github.com/rancher/rancher/issues/43146#issuecomment-1787932330).
> * Created RKE1 `v1.26.11-rancher2-1` standalone cluster, using rke v1.4.12.
> * Deployed rancher v2.7.9 on the cluster.
> * Validated there were NO denied AVCs.
> * Installed logging v2 chart on local cluster and validated P0 scenarios, it's working as expected.
> * Validated there were NO denied AVCs.
> 
> * Performed above steps and provisioned k3s `v1.26.11+k3s2` standalone clusters.
> * Deployed rancher v2.7.9 on the cluster.
> * Validated there were NO denied AVCs.
> * Installed logging v2 chart on local cluster and validated P0 scenarios, it's working as expected.
> * Validated there were NO denied AVCs.

@rishabhmsra thanks for confirming. We'll unrc the tags to make production ready.

**Comment by andypitcher** [comment]
Production packages are now released, see latest [v0.3.production.1](https://github.com/rancher/rancher-selinux/releases/tag/v0.3.production.1).

**Comment by andypitcher** [comment]
- https://github.com/rancher/rancher-docs/pull/974 is now merged.

**Comment by andypitcher** [comment]
Closing this issue since RHEL9 rancher-selinux has been released and documented:

- release: [v0.3.production.1](https://github.com/rancher/rancher-selinux/releases/tag/v0.3.production.1).
- doc: https://ranchermanager.docs.rancher.com/reference-guides/rancher-security/selinux-rpm/about-rancher-selinux
