### ISSUE TITLE
[BUG]custom rke2 cluster upgraded to v1.26.8+rke2r1 has issues with limitranges and clusterauthtokens

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#43202]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Kubernetes version: upgrade RKE2 from 1.24.13 to 1.26.8 

**Describe the bug**
The customer upgraded their custom downstream RKE2 cluster from RKE2 1.24.13 to 1.26.8 and afterwards, they noticed they do not see limitranges created for new namespaces they create in a projec tthat has the "Container Default Resource Limit" fields set. Prior to the upgrade, the limitranges were created for these new namespaces. The customer also said this broke clusterauthtokens when generating new kubeconfig files with ACE enabled.

**To Reproduce**

**Result**
When a new namespace is created in a project that has Container Default Resource Limits defined, a limit range is not created created for that namespace. Also, when creating a new kubeconfig file, a new token is not created.

**Expected Result**
When a new namespace is created in a project that has Container Default Resource Limits defined, a limit range should be created for that namespace. Also, when creating a new kubeconfig file, a new token should be created.

 SURE-7013

**Comment by maxsokolovsky** [comment]
## QA Testing

### Root cause

We overlooked one place where Rancher still tried to register a PSP (PodSecurityPolicy) controller when it shouldn't if
the cluster doesn't support PSPs as a resource.
This made Rancher not register other handlers, such as those that enable the propagation of LimitRanges to namespaces,
Project-scoped Secrets and so on.

### What was fixed, or what changes have occurred

1. Rancher now refuses to register a `pspdelete` controller if the cluster version is at or above 1.25.
2. Rancher now checks the cluster version more thoroughly and handles .

### Areas or cases that should be tested

1. Upgrading the remote cluster from v1.24 to v1.26.

### What areas could experience regressions?

### Steps

#### (Optional) Reproduce the issue with a Rancher version that doesn't have the fix.

1. Get a 2.7 version of Rancher that doesn't have the fix yet.
2. Provision an RKE2 cluster. Choose version 1.24; in the spec (Edit YAML)
   specify `defaultPodSecurityPolicyTemplateName: unrestricted`
3. Create a Project in the new cluster. In the Container Default Resource Limit, choose some values for CPU and Memory
   Reservations.
4. Create a namespace in the project. Verify that Rancher has automatically created a LimitRange object with the
   expected values in the namespace. You can just list or view LimitRanges.
5. Upgrade the remote cluster. Choose version 1.26, in the spec,
   ensure `defaultPodSecurityPolicyTemplateName: unrestricted` remains specified.
6. Create another namespace in the same project. Notice that Rancher no longer creates the LimitRange object. The
   handler for LimitRanges isn't working.

#### Run the above test case with a Rancher version that has a fix

Ensure that after the same cluster upgrade, the handlers still work, and LimitRanges get created.

**Comment by joesims22** [comment]
I have executed all test cases in the test plan and verified the issue on v2.7-00aa1a20fb3abf9fe8bffe680cb267e98cb44662-head
