### ISSUE TITLE
[BUG] removing permission from role template doesn't propagate to 'promoted' clusterRole in downstream cluster

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#43292]
**Rancher Server Setup**
- Rancher version: 2.7.5

**Issue description:**
If you have a custom RoleTemplate which is being used in a downstream cluster, and you edit that RoleTemplate to remove a permission, it is not propagated to the role <roleName>-promoted in the downstream cluster.

**Business impact:**
RBAC is incorrect and has to be edited manually so users don't see objects they aren't supposed to

**Repro steps:**
kubectl apply attached roletemplate to the Rancher cluster
create a new standard user in Rancher and give them access to the Default Project with the custom role imported from step one
the user logs in and can explore the downstream cluster and go to More Resources > Rancher > Mgmt Clusters
now edit the RoleTemplate and remove the get / clusters / management.cattle.io permission
this should have removed the ability for the user to see step #3 but it didn't
an admin will have to go to explore the downstream cluster > More Resources > RBAC > ClusterRoles and find the <roleName>-promoted object and edit it to also remove the get / clusters / management.cattle.io permission
now the user can't see step #3

**Workaround:**
 step #6 above

**Actual behavior:**
Removed role permission does not propagate to downstream cluster

**Expected behavior:**
Removed role permission should propagate to downstream cluster

SURE-6805

**Comment by samjustus** [comment]
@enrichman should we backport to 2.8?

**Comment by enrichman** [comment]
@samjustus if you think this is a fix that is worth the backport we could. There is a low-medium risk of regression because of some changes to the code.

**Comment by enrichman** [comment]
## Validation Template

## Root Cause

If you have a custom RoleTemplate which is being used in a downstream cluster, and you edit that RoleTemplate to remove a permission, it is not propagated to the role -promoted in the downstream cluster.

## What was fixed, or what change have occurred

Removing completely a permission from the RoleTemplate will update also to the *-promoted Role in the downstream cluster.

## Areas or cases that should be tested

- Create a RoleTemplate with some permissions
- Create a standard user, and give him access to the Default Project with the previously created custom role
- Check that the created *-promoted role has the expected permission
- Remove one of the permissions from the RoleTemplate
- Check that the change was propagated to the *-promoted Role

**Comment by nickwsuse** [comment]
### Basic Steps:
- Create Rancher v2.9-head
- `kubectl apply -f <users_roletemplate>.yaml`
- create a new standard user in Rancher
- Give the user access to the Default Project with the custom role imported from step 2
- Log in as the user and can explore the downstream cluster 
- Go to More Resources > Rancher > Mgmt Clusters
- As an admin, edit the RoleTemplate and remove the get / clusters / management.cattle.io permission
- As the user, relogin/refresh to see Mgmt Clusters is not listed 

### Cases (Tested via UI and kubectl)
- Automation: https://github.com/rancher/qa-tasks/issues/1308
- Fresh Install ✅ 
- Upgrade to v2.8-head ✅ 
- Tested on RKE1 and RKE2 downstream cluster roles ✅ 
- RBAC Regression Automation: ✅ 

Additional Upgrade Test ✅ 
1. Create rancher on 2.8.3
2. Create a role template in 2.8.3 example from JIRA
3. Add a standard user to this role
4. Remove a rule from the role templates
5. Promoted role is not updated
6. Upgrade rancher
7. Verify standard user, now is not able to access.

Fresh checks >> remove a verb >> verify user cannot list ✅ 
Fresh checks >> add a rule >> verify user can access ✅ 
Fresh checks >> add a verb >> verify new verb is added ✅
