### ISSUE TITLE
Allow load balancer to target Rancher server itself

### ISSUE THREAD

**Issue by ianwalter** [rancher/rancher#4347]
From what I've seen this hasn't been mentioned, but apologies if it has:
The load balancer is awesome. I'd like to be able to put it front of the Rancher server itself so that I can have a domain name forward to the Rancher server on port 8080.

**Comment by deniseschannon** [comment]
The [HA setup](https://github.com/rancher/rancher/issues/3874) will essentially allow this, as we support "HA" with 1 node.

**Comment by deniseschannon** [comment]
Note: This will be available in v1.0.1

**Comment by nunofgs** [comment]
I'm attempting to do this on a home server. The server is running rancher/server and rancher/agent in the same machine. The `rancher/server` container shows up on the "Infrastructure > Hosts" view correctly.

I added a rule in my load balancer to point to the rancher-server container, like so:

<img width="610" alt="screen shot 2016-07-17 at 17 28 26" src="https://cloud.githubusercontent.com/assets/92085/16901751/f0158d36-4c43-11e6-80b9-566032272dc7.png">

Unfortunately this doesn't seem to work since the generated `/etc/haproxy/haproxy.cfg` file does not contain the rancher-server frontend/backend at all. It was somehow skipped.

@deniseschannon In my case I won't be using a HA setup since it's a test machine.

Any idea if I'm doing something wrong or if this setup is explicitly unsupported?

**Comment by deniseschannon** [comment]
In order for Rancher to target itself, you'd need to use the HA setup with 1 node. 

@nunofgs The setup that you are attempting is not supported.

**Comment by nunofgs** [comment]
For future reference, I was able to get this working!

I simply added the label `io.rancher.container.network: 'true'` to Rancher server itself (scandalous I know :smile:) and now my load balancer was able to use the container as a target!

**Comment by ffittschen** [comment]
@deniseschannon How is this supposed to work? Because if I read the docs correctly, rancher needs an external loadbalancer to run in HA on a single node. Wouldn't this diminish the whole "Allow load balancer to target Rancher server itself" argument, because you still need to manage an extra loadbalancer instead of having just one that ist managed AND used by rancher?

@nunofgs How did you add the label to the server itself? I tried to add it using a `docker-compose.yml`, but once I start up the agent, I can't access rancher anymore. I'm just getting 502 errors from my nginx that is configured as proxy according to the docs to be able to use SSL

**Comment by stszap** [comment]
@ffittschen If you are still interested. I created "external service", pointing to domain "rancher-server" (the name of my rancher/server container) and just pointed load balancer to that service. I didn't tested it much but it seems to be working

**Comment by baflo** [comment]
Thanks you, @stszap, this made it work for me. However, it is even easier, now: Just add a service alias and select the original rancher server.
