### ISSUE TITLE
[Documentation] Grafana dashboards created in wrong namespace

### ISSUE THREAD

**Issue by skanakal** [rancher/rancher#43502]
**Rancher Server Setup**
- Rancher version: 2.7.9
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.26
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

In any rancher-monitoring version. There are 2 sets of data resources for grafana, dashboards and datasources.

The namespace designated to store the grafana dashboards is "cattle-dashboards", and for datasources "cattle-monitoring-system". I understand that the decision to split the dashboards to a separate namespace was due to RBAC, as datasources should be more restricted.

The issue here is that there are 2 dashboards (configMaps) created by default in the wrong namespace: "cattle-monitoring-system", instead of "cattle-dashboards".

These dashboards are "rancher-monitoring-nodes-darwin" and "rancher-monitoring-grafana-overview". And they do not even get mounted to grafana. As grafana does not know to look for them.

**To Reproduce**

Install rancher-monitoring and look for the ConfigMaps in both "cattle-dashboards" and "cattle-monitoring-system".

**Result**
Dashboards created in wrong default namespace

**Expected Result**

Dashboards created in "cattle-dashboards"

**Screenshots**

**Additional context**

Internal ref: https://jira.suse.com/browse/SURE-7159
[SURE-7159]

**Comment by pankajsqe** [comment]
Retest Fail : still able to see “rancher-monitoring-grafana-config-dashboards" in cattle-monitoring-system NameSpace instead of cattle-dashboard NameSpace.
Rancher : v2.9-head 
Cluster : RKE2
Monitoring : “rancher-monitoring-104.0.2+up45.31.1”. 
PFA
![Uploading Screenshot 2024-03-12 at 7.34.57 PM.png…]()

**Comment by skanakal** [comment]
@pankajsqe seems you're checking something wrong... 
I could see the configmaps are correctly landed in the dashboard namespace...


```
root@master-0:~# kubectl get cm -A | egrep -i "nodes-darwin|grafana-overview"
cattle-dashboards                        rancher-monitoring-grafana-overview                             1      21m
cattle-dashboards                        rancher-monitoring-nodes-darwin                                 1      21m
root@master-0:~# 

```

**Comment by MKlimuszka** [comment]
The code doesn't need any more changes, we just need to document expected behavior.

**Comment by Jono-SUSE-Rancher** [comment]
Has this documentation been updated? Are we still targeting it for v2.9.0? If not, can we shift it forward and update accordingly?

**Comment by prachidamle** [comment]
Moved it to v2.9.1, @alexandreLamarre Can you help add this documentation?

**Comment by skanakal** [comment]
@prachidamle @MKlimuszka @alexandreLamarre 

The fix was incorrectly tested [here](https://github.com/rancher/rancher/issues/43502#issuecomment-1991790047)
To clarify, with the [fix](https://github.com/rancher/charts/pull/3466) applied, the configmap is correctly created in the appropriate namespace(you can see my test results), so there is no need to open a documentation issue...

**Comment by dharmit** [comment]
Why does this need to be documented? 
- Two configmaps were getting created in a wrong namespace, @alexandreLamarre's work addressed it
- issue reporter is saying there's no need for documentation. 
- There's no mention of either of the dashboards/configmaps in the docs (https://github.com/rancher/rancher-docs/ repository):
    ```sh
    $ grep -r "rancher-monitoring-grafana-overview"
    <no-result>

    $ grep -r "rancher-monitoring-nodes-darwin"
    <no-result>
    ``` 
Can someone explain what and where the doc changes are required here? @Jono-SUSE-Rancher @prachidamle @MKlimuszka

**Comment by pankajsqe** [comment]
As per the fix "rancher-monitoring-grafana-overview" and "rancher-monitoring-nodes-darwin" ConfigMaps stores grafana dashboard hence they have been successfully moved to the cattle-dashboard namespace, and this change was tested and verified.

```
root:pkumar-0:~# kubectl get cm -A | egrep -i "nodes-darwin|grafana-overview"
cattle-dashboards                        rancher-monitoring-grafana-overview                             1      21m
cattle-dashboards                        rancher-monitoring-nodes-darwin                                 1      21m

```

There was only one query about whether the "rancher-monitoring-grafana-config-dashboards" ConfigMap should be moved to the "cattle-dashboard" namespace. 
After pairing with Siva on this, we have got to know that since "rancher-monitoring-grafana-config-dashboards" stores grafana datasources therefore it should remain in the "cattle-monitoring-system" namespace and not to move into "cattle-dashboard" namespace. It is working as expected too, therefore no documentation is required.

cc: @dharmit , @skanakal , @prachidamle
