### ISSUE TITLE
Backport fix for "Changing vSphere Credentials causes old nodes to fail on deletion" to v2.7

### ISSUE THREAD

**Issue by bfbachmann** [rancher/rancher#43574]
We need to backport the fixes in rancher-machine and rancher for https://github.com/rancher/rancher/issues/40608.

SURE-7239

**Comment by susesgartner** [comment]
Ticket #43574 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Rotate vSphere credentials without updating rancher credentials| Pass |
| 2. | Rotate vSphere credentials and update rancher credentials| Pass |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.7-head`:
---
 
Scenario 1: Rotate vSphere credentials without updating rancher credentials
---
1. Create a 1 node vSphere cluster
2. Rotate the vSphere credentials
3. Delete the cluster node.
 
Results: The cluster displays an error message as expected
 
---
 
Scenario 2: Rotate vSphere credentials and update rancher credentials
---
1. Create a 1 node vSphere cluster
2. Rotate the vSphere credentials
3. Update the rancher credentials to match the vSphere credentials
3. Delete the cluster node.
 
Results: The node is deleted as expected.

Additional Notes:
If your cluster's node is in an errored state due to credentials, update the credentials to the correct ones and then force delete the node to remove it.
