### ISSUE TITLE
Remove CAPI webhook from rancher/webhook

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#43619]
**Rancher Server Setup**
- Rancher version: 2.8-head

With the addition of the provisioning pod which now installs the capi webhook we no longer need to serve a separate webhook for capi in rancher/webhook.

rancher/webhook creates webhooks for capi in [capi.go](https://github.com/rancher/webhook/blob/release/v0.4/pkg/capi/capi.go) which can be removed as well as the sub chart which is created in rancher/webhook for capi.

#### Validation
Confirm that rancher/rancher no longer creates a validatingWebhookConfiguration that points to rancher/webhook capi endpoints.

**Comment by Oats87** [comment]
This should be fine

I would also make sure we properly clean up resources that were created by the webhook

**Comment by tomleb** [comment]
Looks like fixing this would help a lot adding support for k8s 1.28 in webhook to avoid dependencies conflicts.

Here's a summary of CAPI webhook:

In `v2.7.6`, the CAPI webhook was embedded in https://github.com/rancher/webhook/. To establish trust between the CAPI webhook and the k8s apiserver, we're generating TLS certs.

You can see the capi Helm chart here: https://github.com/rancher/webhook/blob/release/v0.3/charts/rancher-webhook/charts/capi/templates/service.yaml. When capi is enabled in the webhook, it deploys the service `webhook-service` in the `cattle-system` namespace. This service uses the [needacert](https://github.com/rancher/wrangler/blob/v2.1.3/pkg/needacert/needacert.go) package in wrangler to generate certificates in the Secret `rancher-webhook-tls`. This is used in mutating/validating webhook configuration and CRDs, and is mounted in the rancher-webhook pod.

In `v2.7.7`, the CAPI webhook was moved outside of the webhook. It still uses the needacert package but in a different namespace. The service/secrets should no longer be used/referenced. However, the code is still there in webhook to enable the embedded CAPI webhook. This is causing issues for the 1.28 k8s support, so we'd like to speed up removing it.

I've tested the following:
- Installing v2.7.6
- Upgrading to v2.7.7

After the upgrade, the Service and the secrets associated to it are deleted automatically. It seems like the service is deleted by the helm mechanism (via `helm upgrade`) and the secret is deleted because it has an ownerReference to the Service.

In `v2.7.6`, the `capi.enabled` helm value depended on the feature flag: https://github.com/rancher/rancher/blob/d395864008ca5e19611ee080ee7f5338df46192d/pkg/controllers/dashboard/systemcharts/controller.go#L136-#L138.

In `v2.7.7`, the `capi.enabled` helm value was hardcoded to `false`:  https://github.com/rancher/rancher/blob/v2.7.7/pkg/controllers/dashboard/systemcharts/controller.go#L146-#L148. Meaning it's no longer possible to enable it in the webhook when installing Rancher.

So considering that:
- it's no longer possible to enable it since `v2.7.7` 
- the resources are cleaned up by helm / apiserver automatically so they already no longer exist

It seems safe to completely remove the helm charts for CAPI and the capi webhook code from rancher/webhook.

**Comment by Oats87** [comment]
> Looks like fixing this would help a lot adding support for k8s 1.28 in webhook to avoid dependencies conflicts.
> 
> Here's a summary of CAPI webhook:
> 
> In `v2.7.6`, the CAPI webhook was embedded in https://github.com/rancher/webhook/. To establish trust between the CAPI webhook and the k8s apiserver, we're generating TLS certs.
> 
> You can see the capi Helm chart here: https://github.com/rancher/webhook/blob/release/v0.3/charts/rancher-webhook/charts/capi/templates/service.yaml. When capi is enabled in the webhook, it deploys the service `webhook-service` in the `cattle-system` namespace. This service uses the [needacert](https://github.com/rancher/wrangler/blob/v2.1.3/pkg/needacert/needacert.go) package in wrangler to generate certificates in the Secret `rancher-webhook-tls`. This is used in mutating/validating webhook configuration and CRDs, and is mounted in the rancher-webhook pod.
> 
> In `v2.7.7`, the CAPI webhook was moved outside of the webhook. It still uses the needacert package but in a different namespace. The service/secrets should no longer be used/referenced. However, the code is still there in webhook to enable the embedded CAPI webhook. This is causing issues for the 1.28 k8s support, so we'd like to speed up removing it.
> 
> I've tested the following:
> 
> * Installing v2.7.6
> * Upgrading to v2.7.7
> 
> After the upgrade, the Service and the secrets associated to it are deleted automatically. It seems like the service is deleted by the helm mechanism (via `helm upgrade`) and the secret is deleted because it has an ownerReference to the Service.
> 
> In `v2.7.6`, the `capi.enabled` helm value depended on the feature flag: https://github.com/rancher/rancher/blob/v2.7.6/pkg/controllers/dashboard/systemcharts/controller.go#L136-#L138.
> 
> In `v2.7.7`, the `capi.enabled` helm value was hardcoded to `false`: https://github.com/rancher/rancher/blob/v2.7.7/pkg/controllers/dashboard/systemcharts/controller.go#L146-#L148. Meaning it's no longer possible to enable it in the webhook when installing Rancher.
> 
> So considering that:
> 
> * it's no longer possible to enable it since `v2.7.7`
> * the resources are cleaned up by helm / apiserver automatically so they already no longer exist
> 
> It seems safe to completely remove the helm charts for CAPI and the capi webhook code from rancher/webhook.

Agree with this consensus.

As long as once you remove the ancillary componentry, you are able to upgrade in a direct line from `v2.7.6` to a version of Rancher with rancher-webhook that has the componentry completely removed, it *should* be OK. Just want to make sure we don't leave an old webhook configuration around hanging that could cause stalling from the user's perspective.

**Comment by tomleb** [comment]
## Validation Template

## Root Cause

We removed the CAPI webhook from rancher/webhook. There's a LOT more details here: https://github.com/rancher/rancher/issues/43619#issuecomment-1971574484.

A quick summary is that before `v2.7.7`, Rancher was deploying the CAPI webhook from within the Rancher webhook pod. It was deployed using the chart defined in Rancher webhook repository. Starting from `v2.7.7`, the CAPI webhook was no longer deployed within the Rancher pod. Instead, it was deployed in another namespace by Rancher. Rancher was hardcoded to NOT deploy the CAPI webhook from webhook, but we kept the CAPI webhook charts in rancher/webhook anyway.

## What was fixed, or what change have occurred

We have completely removed the possibility to deploy the CAPI webhook from within the webhook pod.

This means:
- Rancher no longer provides CAPI specific parameter for the Helm installation command to deploy webhook.
- Webhook no longer contains any CAPI-specific code and neither CAPI-specific chart

## Areas or cases that should be tested

- P0 functionality for webhook
- Upgrading from version before `v2.7.7` to a version after `v2.7.7` should work, the CAPI webhook should still work and the following resources should be cleaned up(*):
    - Service `webhook-service` in namespace `cattle-system`
    - Secret `rancher-webhook-tls` in namespace `cattle-system`

(*): Side note on this but my change doesn't affect this, the change made in `v2.7.7` should have covered this already, but if it doesn't then we should probably fix it.

## What areas could experience regressions

We made some changes to the charts, some combination of values for the chart might render unusable YAML to deploy the webhook (integration tests only test a basic case).

I don't expect it but could be an issue when upgrading from before `v2.7.7` to this version that would prevent the CAPI webhook to work.



## Are the repro steps accurate/minimal?

N/A

**Comment by Priyashetty17** [comment]
Validated with `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head` and `rancher-webhook:v0.5.0-rc8`. All scenarios identified in the test plan have been executed and passed ✅
