### ISSUE TITLE
[BUG] `rancher2_cluster_role_template_binding` resources won't get deleted on Terraform apply

### ISSUE THREAD

**Issue by voliveira-tmx** [rancher/rancher#43631]
### Rancher Server Setup
- Rancher version: v2.7.8
- Installation option (Docker install/Helm Chart): Docker installation

### Information about the Cluster
- Kubernetes version: v1.26.10+rke2r1
- Cluster Type (Local/Downstream): downstream custom cluster
- 4 on-premises worker nodes
- 3 etcd/controlplane EC2 nodes on AWS (Amazon Linux 2)
- The cluster was created using the `rancher2_cluster_v2` resource on Terraform, like this:

```
resource "rancher2_cluster_v2" "buildfarm" {
  name               = local.buildfarm_cluster_name
  kubernetes_version = "v1.26.10+rke2r1"
  rke_config {
    etcd {
      snapshot_schedule_cron = "0 1 * * *"
      snapshot_retention     = 10
      s3_config {
        bucket                = "<REDACTED>"
        endpoint              = "<REDACTED>"
        folder                = "ApplicationData/rancher/${local.buildfarm_cluster_name}/snapshots"
        cloud_credential_name = rancher2_cloud_credential.svc_devopstoolsdev_s3_fullreadwrite.id
        region                = "ca-central-1"
      }
    }
  }
}
```

The roles were created like this:

```
resource "rancher2_cluster_role_template_binding" "buildfarm_owners" {
  count            = length(local.buildfarm_cluster_owners)
  name             = "binding-${local.buildfarm_cluster_owners[count.index]}"
  cluster_id       = rancher2_cluster_v2.buildfarm.cluster_v1_id
  role_template_id = "cluster-owner"
  user_id          = local.buildfarm_cluster_owners[count.index]
}
```

### User Information
- What is the role of the user logged in? Cluster Owner

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? v3.2.0
- What is the version of Terraform in use? Terraform Enterprise, workspace configured with Terraform v1.5.7

### Describe the bug

Terraform can't destroy the mentioned resource. I get the following error:

`Error: [ERROR] waiting for cluster role template binding (c-m-mm685n9f:binding-u-ywwuxgdfgf) to be removed: timeout while waiting for state to become 'removed' (last state: 'active', timeout: 10m0s)`

### To Reproduce

Comment out the `rancher2_cluster_role_template_binding` and try to do a terraform apply

### Actual Result

The apply errors out as mentioned above.

### Expected Result

To be able to successfully delete them through Terraform.

### Screenshots

![image](https://github.com/rancher/terraform-provider-rancher2/assets/126827523/e42d6bf9-6130-440d-b5f3-0648c04ecc65)

**Comment by corym-vermeer** [comment]
We recreated this bug by creating a new template binding using a user_id containing invalid characters.   This I'd consider to be a fault due to lack of proper validation.  Terraform Apply failed though still added the bad resource.    

Query to confirm the offending resource: 
`kubectl get clusterroletemplatebindings.management.cattle.io -n <clusterid> <name>`

Resource deletion hangs: 
`kubectl delete clusterroletemplatebindings.management.cattle.io -n <clusterid> <name>`

Final resolution to delete the offending resource turned out to be removing the finalizers:
`kubectl edit clusterroletemplatebindings.management.cattle.io -n <clusterid> <name>`
replace finalizers list with the following: 
`finalizers: []`

**Comment by voliveira-tmx** [comment]
Interesting... I don't understand how I could've used user_id with invalid chars.

This is my `cluster_owners` variable, under the `local` block:

```
cluster_owners = [
    "u-kqapq4gres",
    "u-4darj5vaup",
    "u-ywwuxgdfgf",
    "u-kvpsnu7cya",
    "u-zpi42xj73n" 
  ]
```

They're basically rancher user IDs that I copied directly from the UI, under the `Users & Authentication` tab. And I can see those users by their names under Cluster Configuration > Member Roles, which leads me to think that the IDs are indeed valid.

**Comment by MbolotSuse** [comment]
Hey @voliveira-tmx - I took a look at this and wasn't able to reproduce the issue without significant tampering (adding my own custom finalizer). I suspect that there is a finalizer on these CRTBs which is preventing them from being deleted. We use these for a variety of reasons (such as making sure that the external/downstream objects are removed before removing the local object).

Unfortunately, it will be difficult for us to work on a fix (or give advice on a workaround) without a better idea of which finalizer is on the object, and why it isn't being removed. Can you pick one of the objects that is failing to delete and gather the finalizers and any related log statements?

To get the finalizers for the object, run the following command in the cluster that rancher is installed on to get the CRTB:
```bash
kubectl get ClusterRoleTemplateBinding binding-u-ywwuxgdfgf -n c-m-mm685n9f -o yaml
```

If this output contains too much information and you just want to get the finalizers, you can use the following command to just get the finalizers:
```bash
kubectl get ClusterRoleTemplateBinding binding-u-ywwuxgdfgf -n c-m-mm685n9f -o jsonpath="{.metadata.finalizers}
```

I'd also like to ask for log entries related to this CRTB. You should be able to filter for those by grepping for the `c-m-mm685n9f/binding-u-ywwuxgdfgf` string, like below:

```bash
cat logs.txt | grep 'binding-u-ywwuxgdfgf'
```

Please make sure to review the output before posting here - keep in mind that this issue is public.

In the meantime, I would recommend making sure that the cluster that these CRTBs are giving access to shows "connected" on the UI and can reach your Rancher install.
