### ISSUE TITLE
[v2.7] Bump calico and canal images to v3.26.3

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#43640]
SURE-7205
bump calico and canal images to v3.26.3 for in RKE1 KDM k8s releases: v1.25.16, v1.26.11.
k8s v1.25.x and v1.26.x are supported in calico v3.26.3 [ref](https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#supported-versions)

**Comment by vivek-shilimkar** [comment]
Validated the Calico and Canal CNI version bumps for k8s v1.26 and v1.25 as follows.

Tested the following three scenarios on k8s v1.25.16-rancher2-1, v1.26.11-rancher2-1.

1. Fresh Install checks
2. Upgrade checks
3. Downstream cluster checks.

Made sure on all the above 3 scenarios the Calico and Canal CNI version is v3.26.3.

Since the CNI version is correct, closing the issue.
