### ISSUE TITLE
Harvester-csi-driver k8s 1.28 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43749]
**This issue is to implement the chart changes & perform the required testing to support k8s 1.28. The generic process that's applicable for most charts is described here. Please adjust the steps to fit your respective chart wherever required. Perform the steps below:**

- [ ] Once you pick up the issue for your chart, apply the label `[zube]: Working` to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label `[zube]: Done`. If this is not an upstream chart then proceed to the next step.
- [ ] Update kube-version annotation in Chart.yaml to `catalog.cattle.io/kube-version: '>= 1.23.0-0'` or `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'`
- [ ] Follow the usual process to add a new chart version and file a PR to the `rancher/charts:dev-v2.8` branch. Link the PR to the issue.
- [ ] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR,  apply the label `[zube]: To Test`. Tag the respective QA team members.
- [ ] Perform below testing
   - [ ] Spin up Rancher 2.8 with k8s 1.27
   - [ ] Add a downstream cluster with k8s 1.28
   - [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch
   - [ ] Install the dev version of the chart. Verify that the installation is successful
   - [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
   - [ ] Uninstall the chart. Verify that the uninstallation is successful
   - [ ] Install the prod version of the chart. Verify that the installation is successful
   - [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful
   - [ ] Add a downstream cluster with k8s 1.27
   - [ ] Install the prod version of the chart
   - [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
   - [ ] Perform any additional testing specific to your chart if required
- [ ] If the testing passes then apply the label `[zube]: Done`. If you are blocked with any steps, add a comment with details and apply the label `[zube]: Blocked`

**Comment by Vicente-Cheng** [comment]
PR opened: https://github.com/rancher/charts/pull/3302

- [ ] Once you pick up the issue for your chart, apply the label [zube]: Working to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label [zube]: Done. If this is not an upstream chart then proceed to the next step.
- [ ] Update kube-version annotation in Chart.yaml to catalog.cattle.io/kube-version: '>= 1.23.0-0' or catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'
- [ ] Follow the usual process to add a new chart version and file a PR to the rancher/charts:dev-v2.8 branch. Link the PR to the issue.
- [ ] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR, apply the label [zube]: To Test. Tag the respective QA team members.

**Comment by khushboo-rancher** [comment]
Tested on Rancher v2.8-head with Harvester 1.2-head

**Behavior on RKE2 v1.28.6+rke2r1:**
Chart version v0.1.17 got installed by default, I was able to create PVC which created volume on Harvester side.

**Behavior on RKE1 v:**
Chart version v0.1.17 was available to install. On installing it, functionality looks good, I was able to create PVC.

Minor issues:
1. The versions are repeated as shown below
<img width="326" alt="Screenshot 2024-03-06 at 2 50 16 PM" src="https://github.com/rancher/rancher/assets/60111667/d91d2be2-580e-42c1-87f5-cd4e45077750">

2. `All charts have at least one version that is installable on clusters with Linux and Windows nodes unless otherwise indicated.` appears on the top, which I believe should not appear for CSI driver as this is only for Linux.

@Vicente-Cheng Could you please take a look at it.
I'll test with Harvester 1.3.0-rc too and update the result.

**Comment by khushboo-rancher** [comment]
Repeated versions were displaying because I was using Rancher v2.8-head. Closing this as this is working fine.
