### ISSUE TITLE
Suggestion: allow option to disable UI transitions

### ISSUE THREAD

**Issue by adamkdean** [rancher/rancher#4375]
I know this is only a little thing, and that there are many other more important things left to do, but something which would massively increase the UX of the UI is if we could turn off the transitions between pages. It slows down the site and looks terrible over RDP.

Pretty please?

**Comment by kevinsimper** [comment]
I don't see the reason either. Loading screens that takes up the whole screen is not seen anywhere else.

**Comment by vincent99** [comment]
They are shown when data is being loaded from the server which is needed for the page you're going to.  In most cases everything is loaded in advance and updated by websocket, so you don't see it in most transitions.

Where they do exist it isn't "slower" (other than maybe RDP trying to keep up).  You're waiting for a response, not an animation.  And it blocks the full screen because letting you click things when the page is going to change after the response comes in a second later is unhelpful.

2.0 has a smaller animation (which should help RDP), and less places that require separate requests and waiting for them.  But otherwise this is not going to change.

**Comment by zeroum** [comment]
@vincent99 Could we still review/improve on this? In Rancher 2.2.8, when I'm trying to view logs from pods, I can still count 5-8 screen ticks/refreshes over a slow RDP connection to an on-premises installation on a remote site. (Rancher itself is in the same machine as the master node, and the RDP server is on the same network, I'm the one remote).

Sometimes I can see that the log is already loaded(or at least its head), and it still takes 3 ticks to reach full opacity. However, I can't say if it is ready/unblocked before that.

Also, I find it weird that there's no 'packaging box icon animation' like other screen transitions when click View Log. Well, it's not really a transition, more like a pop-up.
