### ISSUE TITLE
[Backport v2.8] rancher-machine sends data to bugsnag.com without user consent

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43968]
This is a backport of https://github.com/rancher/rancher/issues/40227 for v2.8.

**Comment by jiaqiluo** [comment]
The issue can be validated in the latest v2.8-head

**Comment by Josh-Diamond** [comment]
Ticket #43968 - Test Results - ✅ 
---

As mentioned [here](https://github.com/rancher/rancher/issues/43968#issuecomment-1885725395), due to the nature of this issue, QA will validate that no regressions relating to cluster provisioning were introduced, as the result of this fix.

With Docker on Rancher `v2.8-d0a177f1745fe14a0b3de7483aa3ef895d1ab967-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE1 Linode Node driver cluster | ✅ |
| 2. | Provision a downstream RKE2 Linode Node driver cluster | ✅ |
| 3. | Provision a downstream K3s Linode Node driver cluster | ✅ |
| 4. | Provision a downstream RKE1 AWS Node driver cluster | ✅ |
| 5. | Provision a downstream RKE2 AWS Node driver cluster | ✅ |
| 6. | Provision a downstream K3s AWS Node driver cluster | ✅ |
| 7. | Provision a downstream RKE1 DO Node driver cluster | ✅ |
| 8. | Provision a downstream RKE2 DO Node driver cluster | ✅ |
| 9. | Provision a downstream K3s DO Node driver cluster | ✅ |

Screenshot:
<img width="1572" alt="Screenshot 2024-01-29 at 4 37 14 PM" src="https://github.com/rancher/rancher/assets/46494969/6bd26dee-88c5-41b5-be5e-f8030029160d">
