### ISSUE TITLE
[BUG][windows]check-wins-version container in rancher-monitoring-windows-exporter failing in windows rke2

### ISSUE THREAD

**Issue by Ducatel** [rancher/rancher#43977]
**Rancher Server Setup**
- Rancher version: v2.8.0
- Installation option (Docker install/Helm Chart): 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
````
rke2 --version
rke2 version v1.26.12+rke2r1 (10683d5a09610873f643ada416b97eb01859108d)
go version go1.20.12 X:boringcrypto
````

- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 
`````` 
kubectl version --short
Client Version: v1.26.12+rke2r1
Kustomize Version: v4.5.7
Server Version: v1.26.12+rke2r1
``````
- Cluster Type (Local/Downstream): Local
 - 1 Master on RHEL 9
 -  2 workers on RHEL 9
 -  3 workers on windows server 21H2

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
On a hybrid windows server 2022 and RHEL 9 cluster build with rke2, when I try to install the Monitoring app (Charts: Monitoring (103.0.0+up45.31.1)) the `cattle-monitoring-system/rancher-monitoring-windows-exporter` fail with error (on windows node of course)
```
ConvertFrom-Json: Conversion from JSON failed with error: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
```

**To Reproduce**
1. Install and RKE2 cluster with linux master (started with option --cni calico) and windows agent following the [official quickstart ](https://docs.rke2.io/install/quickstart)
2. Install rancher 
```
curl -#L https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo add jetstack https://charts.jetstack.io
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.crds.yaml
helm upgrade -i cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace
helm upgrade -i rancher rancher-latest/rancher --create-namespace --namespace cattle-system --set hostname=my.host.fr --set bootstrapPassword=myPassword--set replicas=1
```
3. In rancher, install Monitoring apps
4. look the failure on windows node

**Result**

**Expected Result**

rancher-monitoring-windows-exporter pod must not fail

**Screenshots**

![image](https://github.com/rancher/rancher/assets/1184332/11842317-cb84-49ff-a3ff-fb80ce8dde12)
![image](https://github.com/rancher/rancher/assets/1184332/80fbda64-437c-4ef0-890b-86791545072d)
![image](https://github.com/rancher/rancher/assets/1184332/b4acc7fd-8ec8-4e12-9290-f28ae0ca1c10)
![image](https://github.com/rancher/rancher/assets/1184332/f5007702-e2a1-47ed-8e43-b2fa8df86e57)

**Additional context**
The problem seems to be the same as #38650 #37022 #32321

**Comment by HarrisonWAffel** [comment]
@Ducatel 

This issue is due to the `rancher-wins` service not being present on the windows worker nodes. When Rancher provisions windows rke2 clusters it will automatically install and configure this service for you. However in your case, since this is the _local_ rancher cluster (and thus not provisioned _by_ rancher), that service is not installed. The rancher-wins binary can be found [here](https://github.com/rancher/wins/releases), and the command `./wins.exe server app run --register` will add the service on the machine, which can then be started with `start-service rancher-wins`. 

However, this is not an officially supported configuration for the local rancher cluster, afaik rke2 windows nodes are only supported on _downstream_ rke2 clusters.

**Comment by Ducatel** [comment]
@HarrisonWAffel 

Thanks for your help, running wins.exe helps.
now the windows exporter are running.

But I still have my monitoring stack in red

![image](https://github.com/rancher/rancher/assets/1184332/d23fe31c-c672-4467-b228-0ff9576f8c0f)
![image](https://github.com/rancher/rancher/assets/1184332/eaa4008b-b7d0-45f1-864c-1f5ba02e9e7a)
![image](https://github.com/rancher/rancher/assets/1184332/b27a1a5c-5e74-4282-803d-afae5e887893)


> However, this is not an officially supported configuration for the local rancher cluster, afaik rke2 windows nodes are only supported on downstream rke2 clusters.

Ok I don't really understand what means "downstream rke2 clusters" . I just follow the rke2 official quick start and and on top of that rancher. For me this is a "local cluster" no ?

Do you mean, the officially supported configuration is when I run rancher --> go to cluster management and create from here ?

Thanks for your helps ;)

**Comment by HarrisonWAffel** [comment]
The local cluster is whatever cluster you have installed rancher onto, and downstream clusters are ones which have been provisioned by rancher or imported into rancher

> Do you mean, the officially supported configuration is when I run rancher --> go to cluster management and create from here ?

Thats correct. Unfortunately I'm not very familiar with rancher-monitoring, and there isn't enough information in this ticket to understand what might be broken in your environment

**Comment by Ducatel** [comment]
> The local cluster is whatever cluster you have installed rancher onto, and downstream clusters are ones which have been provisioned by rancher or imported into rancher

OK so I may try to add another cluster to make test in more "official" environment. 

> Unfortunately I'm not very familiar with rancher-monitoring

I'm not familiar with all of this here, it's my first try on kubernetes 😅

> there isn't enough information in this ticket to understand what might be broken in your environment

Tell me which information you need and I will retrieve it 😊

I tried to get the metrics within the pod and seems to never finish

![image](https://github.com/rancher/rancher/assets/1184332/d18e6e06-aa3c-475a-8e84-1c214dfeff1d)


Anyway thanks for your help.

**Comment by xrow** [comment]
I have the same issue on an imported **AKS** cluster with **Win2022** nodes after monitoring install. To my belive the reason is that the host has no rancher components when it is created by Azure. And the windows exporter is using host mounts like:

<img width="809" alt="image" src="https://github.com/rancher/rancher/assets/295491/b562dccf-b627-4251-87a0-1d14fe425087">


```
  volumes:
    - hostPath:
        path: \\.\pipe\rancher_wins
        type: ''
      name: wins-pipe
    - hostPath:
        path: \\.\pipe\rancher_wins_proxy
        type: ''
      name: wins-pipe-proxy
    - hostPath:
        path: c:/etc/windows-exporter
        type: DirectoryOrCreate
      name: binary-host-path
```

**Comment by HarrisonWAffel** [comment]
@xrow Correct, this issue will occur on the following cluster types 
+ Any hosted provider (AKS, EKS, GKE, etc) 
+ Imported clusters 
+ The local cluster (though Windows nodes are not supported for the local cluster anyway) 

We are tracking this issue here https://github.com/rancher/windows/issues/223

**Comment by HarrisonWAffel** [comment]
I'm going to close this issue out as the `check-wins-version` script has been removed from rancher-monitoring and we have fully transitioned to host-process pods.
