### ISSUE TITLE
[BUG] RKE2 provisioned registry secret not being backed up by Backup/Restore operator

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#44033]
**Rancher Server Setup**
- Rancher version: v2.9-head (but reproducible on older versions
- Installation option (Docker install/Helm Chart): Docker/Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.27
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

The registry secret for RKE2 clusters is not backed up by the backup/restore operator. In case of a disaster recovery or local [cluster migration](https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster#docusaurus_skipToContent_fallback), secret would need to be manually created.

**To Reproduce**

- On the UI, cluster management, create cluster, select RKE2, custom
- On Cluster Configuration, Registries, select Pull images for Rancher from a private registry, set the credentials
- click create
- Install Backup/Restore App if necessary
- Create a backup and look for the registry secrets on the folder: secrets.#v1/fleet-default
it is not backed up

**Result**
The secret does not exist in the backup and wouldn't exist if restored from that backup.

**Expected Result**

The secret should be backed up since it is needed for the cluster object to function.

**Screenshots**

**Additional context**

It looks like this should be as easy as adding the `resources.cattle.io/backup` label with the value `true` to the secrets we want backed up since it's [already in the default resourceset](https://github.com/rancher/backup-restore-operator/blob/b1462f1e20182fd7bfc0d8c57059080a4ab84902/charts/rancher-backup/files/default-resourceset-contents/rancher.yaml#L58-L65) for the operator. This would probably just need to be done from a controller on cluster create. That way even if the customer creates the secret via terraform or other means it would still get included in the backup. 

SURE-5896

**Comment by mallardduck** [comment]
When these are created via the UI though they are generated with a consistent name under the `fleet-default` namespace. So we can actually address this in two parts - one by adjusting BRO to backup `^registryconfig-auth-` secrets under `fleet-default` and two can be the controller based fix mentioned to catch anything else created outside of Rancher UI.

**Comment by MKlimuszka** [comment]
This is fixed in both 2.9 and 2.8

**Comment by snasovich** [comment]
Since O&B team is taking care of it, removing it Hostbusters team from it.

**Comment by mallardduck** [comment]
@snasovich - just to clarify since I caused some confusion on this one.

We have pending PRs that will capture any secrets named matching the convention used when working via the Rancher UI. However I believe there's still potential that users might create these via Terraform which may not enforce the same name convention.

In that scenario the end-user would still experience a bug around this issue, which I believe could be addressed in a controller or webhook. Since in that case the secret would need to have an annotation applied to it to match a rule to be backed up instead of relying on a name match.

Today I will work to reproduce this issue with terraform to see if I can verify this and report back here. I'm hoping we can make sure that we address both use-cases since I know the additional control users have via terraform has caused some other issues in the past too.

**Comment by mallardduck** [comment]
@MbolotSuse - I just realized since my other proposed (above) actually sounds like a webhook thing I think? So that might still be our team but frameworks squad? Being really oblivious to proper webhook concepts I took a shot and a very rough proof of concept: https://github.com/rancher/webhook/compare/release/v0.5...mallardduck:cluster-registry-secret-hook?expand=0

**Comment by mallardduck** [comment]
This change can be found in:

- [v4.0.3-alpha.1](https://github.com/rancher/backup-restore-operator/releases/tag/v4.0.3-alpha.1)
- [v3.1.5-beta.2](https://github.com/rancher/backup-restore-operator/releases/tag/v3.1.5-beta.2)

And it will be in:
- [v5.0.1-alpha.2](https://github.com/rancher/backup-restore-operator/releases/tag/v5.0.1-alpha.2)

And any pre-releases higher than these.

**Comment by nickwsuse** [comment]
Validated on v2.9-head Commit ID: `4912395`  ✅ 
----
Fresh Install:
- The `registryconfig-auth` secret is saved in the fleet-default namespace ✅ 
- Backup successfully taken ✅ 
- Backup contains the generated secret under secrets.#v1/fleet-default/registryconfig-auth-<generated_name>.json ✅ 
- Restore successfully completed ✅ 
- Secret is successfully restored ✅ 

Upgrade (2.9.0 -> 2.9-head):
- The `registryconfig-auth` secret is saved in the fleet-default namespace ✅ 
- Backup successfully taken ✅ 
- Backup does NOT contain the generated secret under secrets.#v1/fleet-default/registryconfig-auth-<generated_name>.json ✅ 
- Upgrade successful ✅ 
- New backup is successful ✅ 
- New backup DOES have the generated secret under secrets.#v1/fleet-default/registryconfig-auth-<generated_name>.json ✅ 
- Restore successfully completed ✅ 
- Secret is successfully restored ✅ 

Upgrade (2.8.6 -> 2.9-head):
- The `registryconfig-auth` secret is saved in the fleet-default namespace ✅ 
- Backup successfully taken ✅ 
- Backup does NOT contain the generated secret under secrets.#v1/fleet-default/registryconfig-auth-<generated_name>.json ✅ 
- Upgrade successful ✅ 
- New backup is successful ✅ 
- New backup DOES have the generated secret under secrets.#v1/fleet-default/registryconfig-auth-<generated_name>.json ✅ 
- Restore successfully completed ✅ 
- Secret is successfully restored ✅
