### ISSUE TITLE
[Backport] Harvester harvester-cloud-provider k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44121]
Backport of https://github.com/rancher/rancher/issues/41799

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by w13915984028** [comment]
Harvester PR is ready for review:
https://github.com/rancher/charts/pull/3234

**Comment by snasovich** [comment]
@w13915984028 , for `v2.7-Patch1` milestone the https://github.com/rancher/charts/tree/dev-v2.7.11 charts branch will be used. Apologies that this communication wasn't done/clear.
Please have the changes in that branch. It's also fine to leave it in `dev-v2.7` too as we will need it there too.

FYI @MKlimuszka

**Comment by w13915984028** [comment]
@snasovich I added a new PR to bump harvester-cloud-provider to rancher-charts [dev-v2.7.11] branch. Please help review.

cc @lucasmlp 

thanks.

**Comment by noahgildersleeve** [comment]
Tested on Harvester v1.3.0-rc3 with following combination:
RKE2
- *PASS* v1.27.10 (upgrade existing to target version)
- *PASS* v1.26.13 (refresh install then upgrade k8s to v1.27.10)
RKE1
- *PASS* v1.27.10 (refresh install)
- *PASS* v1.26.13 (refresh install then upgrade k8s to v1.27.10)

Tested with Harvester v1.2.1 with the following combination:
RKE2:
- *PASS* v1.27.10 (upgrade cloud provider > 0.2.3, csi-driver > 0.1.17)
- *PASS* v1.26.13
RKE1 (need to add the overlay in node template in [comment](https://github.com/harvester/harvester/issues/4864#issuecomment-1856199625))
- *FAIL* v1.27.10 (create dhcp load balancer keep in Pending)
- *FAIL* v1.26.13 (create dhcp load balancer keep in Pending)
This is due to an [issue](https://github.com/harvester/harvester/issues/5247) with the node selector for kube-vip. There is a workaround [here](https://github.com/harvester/harvester/issues/5247#issuecomment-1970484347)

CC @lanfon72 @TachunLin
