### ISSUE TITLE
[BUG] Default RKE1 Node template image for Linode fails to provision w/ `Error installing Docker:`

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#44179]
**Rancher Server Setup**
- Rancher version: `v2.8-97b35b27fe786d1707127923e2abfb93fad6ec65-head`
- Installation option (Docker install/Helm Chart): `Docker`
 
**Information about the Cluster**
- Kubernetes version: `v1.27.8-rancher2-2`
- Cluster Type (Local/Downstream): Downstream RKE1 Linode Node driver

**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**
The default RKE1 Node template image for Linode, Ubuntu 18.04 LTS, fails to provision with:
`Error creating machine: Error installing Docker:`

**To Reproduce**
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream RKE1 Linode Node driver cluster, using the default node template image: `Ubuntu 18.04 LTS`
3. Reproduced

**Result**
An error is encountered around Docker failing to be installed which ultimately results in the cluster failing to provision.

**Expected Result**
Cluster comes up `active` and stable when using default image

**Screenshots**
![image (39)](https://github.com/rancher/rancher/assets/46494969/fb41ec3b-e62f-47de-ab77-8437d2ca6608)

**Additional context**
Attempted to reproduce w/ `Ubuntu 20.04 LTS` and `Ubuntu 22.04 LTS` but was unable to do so.  
Perhaps bumping the default to `Ubuntu 22.04 LTS` would resolve this issue.

**Comment by snasovich** [comment]
Closing this issue as "unsupported OS" as for quite a while the only officially supported Ubuntu version on Linode provisioned clusters is 22.04. E.g. see support matrix for Rancher 2.7.0 - https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-0/

However, for unofficial workaround to get provisioning working on Ubuntu 18.04 the suggestion is to change Docker installation URL to `https://releases.rancher.com/install-docker/23.0.sh` from now-default `https://releases.rancher.com/install-docker/24.0.sh`. The latter script fails on Ubuntu 18.04 due to missing package:
```
INFO: apt-cache madison docker-ce | grep '24.0.7' | head -1 | awk '{$1=$1};1' | cut -d' ' -f 3

ERROR: '24.0.7' not found amongst apt-cache madison results
```
(https://releases.rancher.com/install-docker/23.0.sh works as expected).

**Comment by Josh-Diamond** [comment]
Re-opening to further track and validate the default Linode node template image bump.

**Comment by Josh-Diamond** [comment]
Ticket #44179 - Test Results - ✅ 
---

Verified on Rancher `v2.9-4dd0c38a2aab4f77271c07d2c887ecf5bbcea5e3-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE1 Linode Node driver w/ defaults | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE1 Linode Node driver cluster, using Rancher defaults
3. Verified - Cluster successfully provisions; as expected
