### ISSUE TITLE
[BUG] Global Role Template doesn't allow to list namespaces

### ISSUE THREAD

**Issue by gutttlt** [rancher/rancher#44311]
**Rancher Server Setup**
- Rancher version: 2.7.9 and earlier (was already in 2.7.4)
- Installation option: Helm Chart
   - If Helm Chart, Kubernetes Cluster and version: k3s v1.24.13 +k3s1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: RKE2 v1.24.4 +rke2r1
- Cluster Type: Downstream
   - If downstream, what type of cluster: Custom

**User Information**
- What is the role of the user logged in: Custom
  - If custom, define the set of permissions: User Base + custom Role

**Describe the bug**

If role which enables get/list/watch verbs on * in management.cattle.io and get/list/watch on namespaces in core API groups assigned to a user, the user can't list namespaces. 

The user may list Cluster and Projects using v1 and v3 APIs but can't list namespaces. It happens both in WebUI and when the API calls are executed separately.
The following call returns a full list of Projects in all Clusters: https://rancher.hostname/v3/projects
The following call returns no namespaces, despite Cluster c-m-qrg48sdz exists and showed in the previous call: https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces

There is no error message, the call goes through, just the list of namespaces is empty. In WebUI the user sees the Projects but for each projects it's said that there are no namespaces defined.

**To Reproduce**

Create a user which has the following roles assigned:
 - User Base
 - api-ro Role with the following permissions:
```
   rules:
  - apiGroups:
      - management.cattle.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
```

Try the following API calls:
 - /v3/projects
 - /v3/cluster/<cluster-id>/namespaces
**Result**
 - /v3/projects: a list of all projects in all clusters is returned
 - /v3/cluster/<cluster-id>/namespaces: an empty list of namespaces is returned.

**Expected Result**

 - /v3/projects: a list of all projects in all clusters is returned
 - /v3/cluster/<cluster-id>/namespaces: a list of all namespaces in the cluster is returned.
**Screenshots**

Here is an example of empty namespaces list:
```{
    "type": "collection",
    "links": {
        "self": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces"
    },
    "createTypes": {
        "namespace": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces"
    },
    "actions": {},
    "pagination": {
        "limit": 1000,
        "total": 0
    },
    "sort": {
        "order": "asc",
        "reverse": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces?order=desc",
        "links": {
            "description": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces?sort=description",
            "state": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces?sort=state",
            "transitioning": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces?sort=transitioning",
            "transitioningMessage": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces?sort=transitioningMessage",
            "uuid": "https://rancher.hostname/v3/cluster/c-m-qrg48sdz/namespaces?sort=uuid"
        }
    },
    "filters": {
        "created": null,
        "creatorId": null,
        "description": null,
        "name": null,
        "projectId": null,
        "removed": null,
        "state": null,
        "transitioning": null,
        "transitioningMessage": null,
        "uuid": null
    },
    "resourceType": "namespace",
    "data": []
}
```
**Additional context**

What is really weird, if I assign the Restricted Administrator role to the user, it starts seeing the namespaces.
But if I create a clone of the Restricted Administrator role and assign it to the user, then the namespaces' list is empty again. It looks like there are some ClusterRoleBindings in the downstream clusters which allow access to namespaces in core API group connected to some roles, and other roles which have the same rules defined in custom Roles doesn't get the bindings in the downstream clusters.

If I change the role to allow * verbs on * in * API group, it doesn't work anyway.

If I assign a custom role "View All Projects" to the same user on the cluster-level, then it works fine as well.

**Comment by MbolotSuse** [comment]
Hey @gutttlt . This is a known issue of Global Roles in the 2.7.x line. We introduced a new field in 2.8.0 - `inheritedClusterRoles` which allows you to give permissions on all downstream clusters through the use of GlobalRoles. There is [documentation](https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#globalrole-permissions-on-downstream-clusters) and a [blog post](https://www.suse.com/c/rancher_blog/building-a-custom-read-only-global-role-with-the-rancher-kubernetes-api/) which can help you understand how to use the new feature.

The reason that you were seeing the desired behavior with the Restricted Administrator role was due to that role being one of two roles (the other being Administrator) which gave permissions on downstream clusters. This was inflexible, so we introduced the new field I referred to above. Please let me know if you have any additional questions/concerns - I'll leave this issue open for a short time, but will plan on closing it since we have already addressed this in the 2.8 line.
