### ISSUE TITLE
Add managed annotation to Chart.yaml in rancher-webhook helm chart

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#44352]
A customer reported a bug where the user was able to manually upgrade the rancher-webhook app. According to documentation https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook, it is a managed app which means it is installed, upgraded, and deleted by codebase. So, when the users perform these actions on managed charts in the Apps page of Rancher UI, the UI will throw a warning that it is not a recommended action.

A managed chart has the annotation catalog.cattle.io/managed:true in Chart.yaml.

Since rancher-webhook is a managed charts, they should have this annotation so customers don't complain about these charts.

**Acceptance criteria**

- [ ] Add _catalog.cattle.io/managed:true_ annotation for future versions of rancher-webhook chart

SURE-7579

**Comment by gehrkefc** [comment]
I was able to reproduce the issue but I couldn't see the warning message. Tested with both rancher v2.8.5 and 2.9.1. But I created a [PR](https://github.com/rancher/webhook/pull/498) to add the config to the Helm Chart.

Those are the steps I've followed to reproduce the issue:

1. Spawn a stable rancher instance:
	```bash
	docker run --privileged -d --restart=always -p 8080:80 -p 8443:443 rancher/rancher:v2.9.1
	```

2. Get bootstrap password:
	```bash
	docker logs $(docker ps | grep rancher/rancher | awk '{print $1}') 2>&1 | grep "Bootstrap Password:"
	```
3. Open the UI at: [https://localhost:8443](https://localhost:8443) and make the initialization and login process into it.
4. Click on the local namespace icon in the left sidebar.
5. Then change from _Only User Namespaces_ to _cattle-system_ on the upper/center namespace selection bar
6. Then click in _Apps_ in the namespace sidebar
7. Then click in _Installed Apps_ 
8. At this point you should see **rancher-webhook** listed
9. Then click on the 3 dots menu at right of it
10. Click Edit/Upgrade
11.  Then change the version and click _Next_ until the end and _Upgrade_
12. It should take some time to complete
13. You can click again in _Installed Apps_ in the left sidebar from time to time to see if the process already completed
14. Once it's Done you should see a green _Deployed_ badge on it

The only message I could notice in the UI was:

`All charts have at least one version that is installable on clusters with Linux and Windows nodes unless otherwise indicated.`

Did I miss any step ?

**Comment by gehrkefc** [comment]
@MKlimuszka This was merged in a bumped in rancher/rancher. How do we proceed ?

**Comment by brudnak** [comment]
Validated on: `v2.10-dae07ed09601506420c133a69d6e6d27bb7a53ec-head`

---

Info msg present:

```log
Warning, Rancher manages deployment and upgrade of the rancher-webhook app. Upgrading this app is not supported.
Under most circumstances, no user intervention should be needed to ensure that the 105.0.0+up0.6.1-rc.5 version is compatible with the version of Rancher that you are running.
```

#### NOTE
> Reproduced and verified this info msg is not present on Rancher 2.9.2
