### ISSUE TITLE
[rancher-dns] Support lexicon for external DNS manipulation

### ISSUE THREAD

**Issue by AnalogJ** [rancher/rancher#4447]
Hey,
So after taking a look at <https://github.com/rancher/external-dns> I thought you guys might find my python library [Lexicon](https://github.com/AnalogJ/lexicon) as an interesting alternative for ensuring that DNS entries are correctly created on 3rd party DNS services. Lexicon lets you manipulate DNS records on various DNS providers in a standardized/agnostic way.

Lexicon currently supports the following, with more being added all the time:

- Cloudflare
- DigitalOcean
- DNSimple
- DnsMadeEasy
- DNSPark
- EasyDNS
- Namesilo
- NS1
- PointHQ
- Rage4
- Vultr

Lexicon is fully tested, and creates a standardized way to manipulate DNS records, which is basically what external-dns is trying to do.

If you guys are interested I could look at creating a drop-in replacement for the External-DNS docker-container (with the same API). Since `external-dns` is a docker container anyways, the python vs golang issue won't be a problem. The only providers you support that `lexicon` doesn't currently are `gandi` and `route53`, both of which are on the todo list and can be implemented fairly quickly, if you guys are interested.

**Comment by vincent99** [comment]
While that looks like a neat project and we might have considered using/contributing to it if you existed when we started, I don't think it really makes sense to switch now given that we have our own custom provider coming (in Go) and are generally doing new development in Go.

One thing of note: we've learned to prefer using 1st party SDKs when available, rather than rolling your own client.  For example Route53 has pretty aggressive rate-limiting that your (preliminary, I know) code does not handle well, and the 3rd party client currently using (pending [#31](https://github.com/rancher/external-dns/pull/31)) also has issues.  The provider-agnostic thing also starts to break down eventually, e.g. [public vs private zones](https://github.com/rancher/rancher/issues/4262).

You can certainly create a community template that reads metadata to get the names that should be synced the same way external-dns does if you're interested, or put in PRs to add providers and/or a CLI to it.
