### ISSUE TITLE
Delay setting for docker machine host creation

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#4464]
The Vultr API limits API requests "to an average of 2/s".

When adding multiple hosts on Rancher, the API limit is hit right away and the provisioning stops.

A delay setting would help workaround such rate limiting.

**Comment by vincent99** [comment]
Changed create calls to be serial (instead of up to 4-6 in parallel, depending on the browser's AJAX limit) in https://github.com/rancher/ui/pull/605 .  This may or may not fix the issue depending on how slow their API is to respond and what other calls docker-machine does with the creds.

I don't want to impose a 500ms-1sec delay on every create for every driver, or add `if ( driver === 'vultr') { }` hacks, so there's an extra hook that driver UI components can use to add an additional arbitrary delay.  That would require a custom UI component for Vultr, though.  If someone is interested in working on that it's fairly straightforward for a one-screen form, there's support in the next Rancher release (or in `master` as of yesterday-ish) and you start from https://github.com/rancher/ui-driver-skel.

**Comment by tfiduccia** [comment]
Version - master 4/28
Verified fixed
