### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s March 2024 patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#44723]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.26.15+rke2r1                  | v2.7.5-alpha1             | v2.7.99 |
| v1.27.12+rke2r1                  | v2.7.11-alpha1             | v2.7.99 |
| v1.26.16+k3s1                  | v2.7.5-alpha1             | v2.7.99 |
| v1.27.12+k3s1                  | v2.7.11-alpha1             | v2.7.99 |

# KDM Branch
[dev-v2.7](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7)

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |

TBD

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |

TBD

# Additional Notes

**Comment by snasovich** [comment]
Since we're doing March patches with v2.8-Next1 release (see https://github.com/rancher/rancher/issues/44722#issuecomment-2008121016) it makes sense to do them with v2.7-Next1 for v2.7 instead of out-of-band. v2.7-Next1 is releasing together/shortly after v2.8-Next1.
Changing milestones and branch in the description accordingly.

**Comment by endawkins** [comment]
![Screenshot 2024-03-26 at 14 39 49](https://github.com/rancher/rancher/assets/126098099/544f1879-627a-478a-ad91-27563293762d)
