### ISSUE TITLE
RancherHA, New hosts have wrong IP, cross host networking not working

### ISSUE THREAD

**Issue by shethchintan7** [rancher/rancher#4484]
Rancher Version: v1.0.1

OS: RancherOS

Steps to Reproduce: Add a host to Rancher HA Stack

Results: IP is wrong and thus you won't be able to do cross host networking

It seems it is taking ELB IPs ( private ip )

ELB Private ips can be found by

> aws ec2 describe-network-interfaces --filters "Name=description,Values=ELB rancher" |grep -wE 'Description|PrivateIpAddress'

I used -e CATTLE_AGENT_IP="" for time sake to explicitly state IP and then it works fine.

**Comment by Rucknar** [comment]
Can confirm, seeing this issue also. Might be behind my issue with #4404

**Comment by deniseschannon** [comment]
@shethchintan7 @Rucknar We have added documentation notes that setting the CATTLE_AGENT_IP is required for AWS setups with HA.

**Comment by Rucknar** [comment]
Thanks @deniseschannon 
Link - http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/

Read through the above, the last step (4) at the bottom of the page has me confused though...
* I presume this is for adding hosts outside the Management environment?
* What is the custom script mentioned in the last step when adding hosts through the UI?, is this the add agent command we get through the 'custom' host add method?

**Comment by jgallucci32** [comment]
Thanks for the workaround tip.  Is there a separate issue tracking this bug for release to master?

**Comment by jgallucci32** [comment]
@ibuildthecloud I was able to get it working this morning.  A key piece of information was knowing that Rancher supports proxy protocol requests using ports 81 and 444 for non-secure and SSL traffic respectively. Because we are using SSL Passthrough, we cannot use any HTTP forwarding headers, and must use proxy protocol. All I had to do was change the backend port from 443 to 444 and add the `send-proxy` flag to the server statement.  I verified this configuration supports both websockets and properly proxies the client IP address.

Here is an example `haproxy.cfg` using SSL passthrough and a port 80 redirect to force all clients to use SSL:
```
# HTTP proxy for Rancher
frontend http
    bind *:80
    mode http
    redirect scheme https if !{ ssl_fc }
  
frontend https
    bind *:443
    option tcplog
    mode tcp
    default_backend https-rancher-proxy-protocol
 
backend https-rancher-proxy-protocol
    mode tcp
    balance roundrobin
    server rancher-1-https rancher-1:444 check send-proxy
    server rancher-2-https rancher-2:444 check send-proxy
    server rancher-3-https rancher-3:444 check send-proxy
```

**Comment by aemneina** [comment]
@jgallucci32 

To get haproxy to work properly in front of rancher HA you'd need need it to detect and upgrade websocket connections. Notice we're passing traffic directly to 443... that way http connections are handled properly. haproxy.cfg should contain the following params:

```
  acl is_websocket hdr(Upgrade) -i WebSocket
  acl is_websocket hdr_beg(Host) -i ws
  use_backend websockets if is_websocket
```

A minimum viable config might look like:

```
global
  ssl-server-verify none

defaults
  mode http
  balance roundrobin
  option redispatch
  option forwardfor

  timeout connect 5s
  timeout queue 5s
  timeout client 500s
  timeout server 500s

frontend http-in
  mode tcp
  bind *:443 ssl crt /etc/haproxy/certificate.pem
  default_backend servers

  acl is_websocket hdr(Upgrade) -i WebSocket
  acl is_websocket hdr_beg(Host) -i ws
  use_backend websockets if is_websocket

backend servers
  server websrv1 <rancher_server_node1_ip>:443 weight 1 maxconn 1024 ssl
  server websrv2 <rancher_server_node2_ip>:443 weight 1 maxconn 1024 ssl
  server websrv2 <rancher_server_node3_ip>:443 weight 1 maxconn 1024 ssl

backend websockets
  balance source
  option http-server-close
  option forceclose
  server websrv1 <rancher_server_node1_ip>:443 weight 1 maxconn 1024 ssl
  server websrv2 <rancher_server_node2_ip>:443 weight 1 maxconn 1024 ssl
  server websrv2 <rancher_server_node3_ip>:443 weight 1 maxconn 1024 ssl
```

We'll update our doc's to contain both nginx and haproxy configurations as well.

**Comment by jgallucci32** [comment]
@aemneina I had considered doing SSL Termination at the load balancer, but wanted to avoid the complexity of having to handle the ssl certs on both ends of the connection and the separation of websocket and http traffic.  My example shows a TCP-only (Layer 4) configuration where the traffic passes through the load balancer with the addition of proxy protocol to handle the passing of the client IP. Since the websocket handshake occurs above the TCP layer, the connection can be upgraded without haproxy intervention. This is similar to how the AWS ELB works since it does not support websockets natively.

I have verified that both host registration as well as websocket traffic (execute shell, view logs) are fully functional with my existing Rancher HA configuration (1 haproxy host, 3 rancher-server hosts, 1 database host).

What additional tests should I run to verify the load balancer is working correctly within our environment?

**Comment by aemneina** [comment]
That makes sense... 

In terms of tests, I think you touched the big ticket items with:
1. registering hosts
2. exec shell

I'd also look out for host and container metrics, and trying to hit the links in the top nav bar... esp. the HA and process view tabs.
