### ISSUE TITLE
[Backport 2.8-Next2] login command doesn't create cli2.json file

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#44844]
This is a backport issue of https://github.com/rancher/rancher/issues/31967 for 2.8-Next2

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|`cli2.json` created after logging in with CMD|Run `rancher login` command, validate login is successful and `cli2.json` file exists|
|2|`cli2.json` created after logging in with Powershell|Run `rancher login` command, validate login is successful and `cli2.json` file exists|

**Comment by markusewalker** [comment]
Reproduced this issue using the Rancher CLI v2.8.0. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/673290980ca6def732d61fcb46720b5deb5ea8f9.
- Rancher CLI version: `v2.8.0`

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|`cli2.json` created after logging in with CMD|Run `rancher login` command, validate login is successful and `cli2.json` file exists|:x:|

```
>rancher.exe login --token <removed> <Rancher server URL>
...
Do you want to continue connecting (yes/no)? yes
NUMBER    CLUSTER NAME     PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         auto-ec2-mgxkr   <removed>   System         System project created for the cluster
2         auto-ec2-mgxkr  <removed>  Default        Default project created for the cluster
3         mew-test         <removed>  Default        Default project created for the cluster
4         mew-test         <removed> System         System project created for the cluster
5         local            <removed>    Default        Default project created for the cluster
6         local            <removed>    System         System project created for the cluster
Select a Project:5
time="2024-03-28T18:46:30Z" level=info msg="Saving config to \\.rancher\\cli2.json"
time="2024-03-28T18:46:30Z" level=fatal msg="open \\.rancher\\cli2.json: The system cannot find the path specified."
```

Now that this is reproduced, I will use Rancher CLI 2.8.3 and see if this has been addressed.

**Comment by HarrisonWAffel** [comment]
RC `v2.8.4-rc1` has been created so this issue is now ready to be tested

**Comment by markusewalker** [comment]
Validated this issue using the Rancher CLI `v2.8.4-rc1`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/a49ebe3a9b52631a61717f532e8c2f87d17e745a.
- Rancher CLI version: `v2.8.4-rc1`

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|`cli2.json` created after logging in with CMD|Run `rancher login` command, validate login is successful and `cli2.json` file exists|:white_check_mark:|
|2|`cli2.json` created after logging in with Powershell|Run `rancher login` command, validate login is successful and `cli2.json` file exists|:white_check_mark:|

**REPRO STEPS**
1. Downloaded [Rancher CLI](https://github.com/rancher/cli/releases/tag/v2.8.0) on Windows client machine.
2. In CMD, ran the following command: 
```
>rancher.exe login --token <removed> <Rancher server URL>
...
time="2024-04-05T19:48:16Z" level=info msg="Saving config to C:\\Users\\Administrator\\.rancher\\cli2.json"
C:\Users\Administrator\Downloads\rancher-windows-amd64-v2.8.4-rc1\rancher-v2.8.4-rc1>dir C:\Users\Administrator\.rancher\
 Volume in drive C has no label.
 Volume Serial Number is A6F0-A5C4

 Directory of C:\Users\Administrator\.rancher

04/05/2024  07:48 PM    <DIR>          .
04/05/2024  07:48 PM    <DIR>          ..
04/05/2024  07:48 PM             1,059 cli2.json
               1 File(s)          1,059 bytes
               2 Dir(s)  89,619,906,560 bytes free
```

_______

**Scenario 2**
1. Repeated scenario 1, but used Powershell instead of CMD - same successful results.
