### ISSUE TITLE
[BUG] can't enable Azure AD because there is a timeout when our login code tries to do a simple GET on the user

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#45004]

**Comment by samjustus** [comment]
https://github.com/manicminer/hamilton/pull/280

**Comment by bigkevmcd** [comment]
We currently plan to replace our usage of "hamilton" with the "official" msgraph client, and we are currently significantly behind the current version of "hamilton" which would require some changes to support it (and get the benefit of the upstream project fixes).

This leaves us with a choice:
 * Do we want to patch 2.9 with a _similar_ fix to the one applied to Hamilton and the fix for [2.8](https://github.com/rancher/rancher/pull/45010)?
 * Do we want to defer a fix for this in 2.9 until we've replaced the code with msgraph?
