### ISSUE TITLE
Support semantic versioning in Rancher catalog/API

### ISSUE THREAD

**Issue by alecl** [rancher/rancher#4507]
Teams A, B, and C are working together.

C isn't working on a new release right now but A and B are. 

As an engineer in team A I'd like to spin up in my environment the latest stacks in the catalog from my team A and my partner team B but I want to lock onto the major.minor.* semantic version matching the production version of team C and not their latest work that may be unstable and I don't need to deal with that as my new code doesn't interact with it.

So I ask for version 5.7.* from the catalog of team C's service. There's a 5.8 series and an older 5.7.3.24 but I am given the proper latest version for the semver expression I have specified which is 5.7.3.43 for example.

**Comment by deniseschannon** [comment]
There is no way in our catalog-service today to ask for a specific version and return the relevant versions, but we've added some features in regards to versioning/upgrading.

1. Instead of showing templates by folder number, we are now displaying by version number. In this case, if you were on 5.7.30 and in your folders, there was a 5.7.20 and 5.7.35 and 5.8.0, then only 5.7.35 and 5.8.0 would show up as ability to upgrade. The "older versions" wouldn't show up even if they were in later folder numbers.

https://github.com/rancher/rancher/issues/5691

2. The other concept that we've added is "upgradeFrom" field, where you would be able to specify which versions this specific template could be upgraded from. Note: Upgrade from still hasn't been added in rancher-compose so it's not quite working yet.

https://github.com/rancher/rancher-catalog-service/pull/70

Between these 2 enhancements, I think you could achieve what you are looking for. Let me know what you think.

**Comment by deniseschannon** [comment]
@alecl If the new fields that I laid out in 1.2.0 don't achieve what you are looking for, then please reopen.
