### ISSUE TITLE
Version pinning for `rancher-provisioning-capi` chart

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45099]
Rancher automatically upgrading `rancher-provisioning-capi` chart to newer version that is not intended for usage with previous releases of Rancher may lead to issues (e.g. https://github.com/rancher/rancher/issues/44929).

To eliminate such possibility we want to pin specific version of `rancher-provisioning-capi` chart to each Rancher version. This should be same or very close to how it was implemented for Rancher Webhook in https://github.com/rancher/rancher/issues/40159 / https://github.com/rancher/rancher/pull/41302.

**Comment by vivek-shilimkar** [comment]
### Following two test scenarios are the basic tests we can do for this ticket.

### Steps

#### Use the new `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` setting
1. Set it to some fixed value (like `104.0.0+up0.2.0`) when starting Rancher. Or use the `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` environment variable.
2. When Rancher starts up, ensure that the version of the `rancher-provisioning-capi` chart matches the one you specified.
3. Set it to some other value, restart Rancher. Observe that the there is a new release with the new version.

#### Provide a non-existent exact version setting
1. Set it to some bad value (like `104.0.0+up0.3.0-rc99`) when starting Rancher. Or use the `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` environment variable.
2. When Rancher starts up, ensure that the rancher-wprovisioning-capi chart fails to deploy on the local cluster because of the incorrect version.
3. Ensure the logs have the appropriate message about this.

### Along with this we can also do the following tests.

1. Install rancher chart on v2.8.3 and upgrade rancher to v2.9-head or available RC of v2.9 by setting the env variable `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` to a correct version.
  -  Expected result is that the CAPI version gets upgraded with rancher.

2. Install rancher chart on v2.8.3 and upgrade rancher to v2.9-head or available RC of v2.9 by setting the env variable `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` to an incorrect version.
  -  Expected result is that the CAPI version remains the same as on rancher v2.8.3 since the incorrect version is provided.

3. Install rancher chart on v2.8.3 and upgrade rancher to v2.9-head or available RC of v2.9.
  -  Expected result is that the CAPI version remains the same as on rancher v2.8.3. 
  - Check if you can upgrade the CAPI version manually from the UI. CAPI version should upgrade to selected version on the UI.

**Comment by vivek-shilimkar** [comment]
Tested the above scenarios for CAPI chart and they pass successfully. Hence, closing the issue.
