### ISSUE TITLE
Script to autoadd host to enviroment

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#4516]
Hello

This isn't a issue per se.

I'm writing a script for autoinstall docker, dependences and add host to rancher.

I see for every enviroment rancher generates query like 

http://MYHOSTNAME/v1/scripts/AAAAAAAAAAAAAAAAAAA:BBBBBBBBBBB:CCCCCCCCCCCCCCCCCCCCC

How generate it? BBBBBBBBBBBBBBBB is always same for every enviroment so I need calculate AAAAAAAAAAAAAAA and CCCCCCCCCCCCCCCC in script

Thanks in advance

**Comment by ebr** [comment]
The entire part after `script` is the key that you need to use, per environment. Just go to add a host, copy this string, and add it as a parameter to pass to your script, e.g.: `http://MYHOSTNAME/v1/scripts/$1`, where `$1` is a command line argument equal to "AAA:BBB:CCC". 
When the script runs, the host will appear in your environment. This key will be valid for the environment going forward.

**Comment by vincent99** [comment]
Please don't try to parse meaning out of opaque strings.  Assuming "B" is constant will not work.  (it's a timestamp rounded to the hour so it only briefly appears to be always the same.  "A" is an API access key and "C" is a signature of A+B, which will then be invalid)

The resource you want is a `registrationToken`.  First figure out what Environment (which is called a `project` in the API) you want one for, in a fresh install the "Default" one is always `1a5`.  Then send a POST to  `/v1/projects/1a5/registrationTokens` to create a token.  You can also GET to list existing ones, but there will not be a pre-existing one unless you have visited the Add Host UI for that Environment.

The URL is the `registrationUrl` property of the token.  I would still suggest using the entire `docker run ...` command (the `command` property) or at least the `image` property so that you are running the right image for the version of Rancher it will be talking to.

**Comment by ebr** [comment]
@vincent99 thanks for that clarification. Generating the "A:B:C" once and using it in my scripts going forward has been working well for me. Is this a really bad idea, and under what circumstances would this break? Wouldn't it be safe to assume that a specific combination of key, signature and timestamp will remain valid once generated?

**Comment by JaviSabalete** [comment]
Thanks @ebr and @vincent99 for your great answers.

I'm finishing my script 😄
