### ISSUE TITLE
[BUG] Unable to Add Cloud Credentials in Rancher

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#45199]
**Rancher Server Setup**
- Rancher version: `v2.9-3a426b5ba059358f8874573c0a98d01bfda25a47-head`
- Installation option (Docker install/Helm Chart): Helm (byo-valid)
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
 
**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**
HA installation went through fine but when I tried adding cloud credentials to Rancher, it results in a 502 bad gateway error with aws creds and 500 error with google creds. And, without the creds, we cannot create downstream clusters.
Note: I did not see this issue on Friday with 2.9-head. Started seeing this issue today with 2.9-head.

**To Reproduce**
1. In Rancher UI, create AWS Cloud Credential
2. Select `Amazon` for Environment, and provide access and secret keys
3. Create

**Issue**
AWS Cloud Credential failed to create with a auth failure - `502 Bad Gateway`

Note: 
- Works fine on 2.8.3 with the same AWS credentials.
- I see the same auth failure while adding Google (500 Internal Server Error) cloud credentials as well.
- Here is the helm command that was used to install Rancher: helm_v3 install rancher rancher-latest/rancher --version 2.8.3 --namespace cattle-system --set hostname=xyz.qa.rancher.space --set global.cattle.psp.enabled=false --set ingress.tls.source=secret --set rancherImageTag=v2.9-head --set bootstrapPassword=admin

**Screenshots**
<img width="855" alt="image" src="https://github.com/rancher/rancher/assets/42880103/c198de04-c51a-49c0-838a-8f5772172709">

**`Marking this a blocker since downstream clusters cannot be created without the cloud credentials.`**

**Rancher Log has this:**
```
http: proxy error: tls: failed to verify certificate: x509: certificate signed by unknown authority

[ERROR] [gke-handler] error getting zones: Get "https://compute.googleapis.com/compute/v1/projects/ei-container-platform-qa/zones?alt=json&prettyPrint=false": oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": tls: failed to verify certificate: x509: certificate signed by unknown authority`
```

**Comment by slickwarren** [comment]
I tested this again today and ran into the same error using cert-manager 1.11.0 on the local (rancher) server.

**Comment by ericpromislow** [comment]
I'm not sure if it's related, but often on a 2.9x build, I get the error `No version info found in KDM` when I press the `Digital Ocean` button. This is before it asks me for the API token.   I repeated it today with building rancher `release/v2.9` commit a66219913

**Comment by vardhaman22** [comment]
there are multiple errors in the rancher logs regarding CA certificates.
While debugging the issue i found out that the issue is caused by **empty ca-certificates file in the recent image rancher:v2.9-head ( /etc/ssl/ca-bundle.pem)** 

![Screenshot from 2024-04-25 16-39-38](https://github.com/rancher/rancher/assets/115442970/ce045b3b-9165-4bb1-aeb9-d2017b908f7b)
this file is present in rancher v2.8.3 and has several certificates.

which in my opinion is because  **base image in dockerfile was changed from registry.suse.com/bci/bci-base:15.5 to registry.suse.com/bci/bci-micro:15.5** ref [PR](https://github.com/rancher/rancher/pull/44348)

i tried to check the file in docker image building stage and the certificates were present there
![Screenshot from 2024-04-25 16-41-34](https://github.com/rancher/rancher/assets/115442970/92ff21d2-5a3a-4a22-aeff-7cdf82622182)

then in image building step i tried running **update-ca-certificates** first and then checking the file content...and the certificates were missing after that......
![Screenshot from 2024-04-25 16-42-51](https://github.com/rancher/rancher/assets/115442970/ef658f59-fbc4-4853-98f4-b381e29fe580)

so not totally sure why this is happening but it seems the certificates are getting removed because of running **update-ca-certificates** in bci-micro image. 
update-ca-certificate command is run in entrypoint.sh https://github.com/rancher/rancher/blob/06d0eb0e18bec11752905ed6e9e7bca811dfbb5e/package/entrypoint.sh#L44-L46

i tried commenting out that line in entrypoint.sh and made a custom image ...which did resolve the certificate related errors and i was also able to create credentials.....
![Screenshot from 2024-04-25 18-16-16](https://github.com/rancher/rancher/assets/115442970/1fa73b63-cecb-4371-aca3-eed537cf8602)



but the pods were still stuck in container creating state for which i don't know the reason.....

![Screenshot from 2024-04-25 18-14-17](https://github.com/rancher/rancher/assets/115442970/d020f6af-4072-49d6-b794-b0d1d593ee39)

@pjbgf please check once.
