### ISSUE TITLE
[BUG] : Requeing error messages in Logs when user create RoleTemplates without annotations

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#45365]
**Description:** 
Rancher Upgraded from `v2.8.3->v2.8-head` is deleting user created RoleTemplates with labels, rules and without annotations are  causing requeuing errors in the logs

**Steps:**

1. Create rancher v2.8.3
2. Create RoleTemplates `kubectl create -f roleTemplate.Yaml`
3. Attached txt file needs conversion to yaml 
[roleTemplate.txt](https://github.com/rancher/rancher/files/15201323/roleTemplate.txt)
Note : This YAML has rules and labels but NO annotations.
4. In yaml file make sure to remove `metadata:annotations`
5. Create a Downstream cluster
6. Create a user and attach this RoleTemplate to the user as a Cluster Membership(Downstream cluster-> Cluster and Project Members ->Cluster Memberships)
7. Upgrade rancher to v2.8-head
8. Check for the RoleTemplate which we created on v2.8.3

**Actual:**
a. RoleTemplate is deleted as soon as the rancher is upgraded to v2.8-head
b. After upgrade, the error message related to RoleTemplate is requeuing in the logs

`2024/05/03 13:51:30 [ERROR] error syncing 'c-m-bzxpn8w7/crtb-pbdv5': handler cluster-crtb-sync: couldn't get role template dasrtc2: roletemplates.management.cattle.io "dasrtc2" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "dasrtc2" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "dasrtc2" not found, requeuing`

**Expected:**
a. RoleTemplates should not be deleted by system
b. User does not have a way to fix these errors as the RoleTemplate is deleted

**Note:**

1. Rancher is deleting only the RoleTemplates which are created without metadata:annotations
2. Rancher is NOT deleting the RoleTemplates which were created from UI/v3 API
3. On v2.8-head -- I can create new RoleTemplate with this yaml file, on an upgrade these RoleTemplates will be deleted.

**Comment by JonCrowther** [comment]
Investigating. I see it removing my roletemplate called `jono-test` in the logs.
```
2024/05/27 19:37:57 [INFO] Starting cluster controllers for local
I0527 19:37:57.842467   35156 leaderelection.go:260] successfully acquired lease kube-system/cattle-controllers
2024/05/27 19:37:57 [INFO] Reconciling GlobalRoles
2024/05/27 19:37:57 [INFO] Reconciling RoleTemplates
2024/05/27 19:37:57 [INFO] Removing jono-test
2024/05/27 19:37:57 [INFO] Registering namespaceHandler for adding labels 
```

**Comment by JonCrowther** [comment]
I believe I've found the root cause. The RoleTemplate provided by @dasarinaidu has the label `"authz.management.cattle.io/bootstrapping": "default-roletemplate"`. That label is meant to specify which RoleTemplates are default RoleTemplates that are created by Rancher. It's so we don't delete them during cleanup. However, on startup (or upgrade), Rancher creates a list of all the expected default RoleTemplates. Then it gets all the RoleTemplates with the label `"authz.management.cattle.io/bootstrapping": "default-roletemplate"` and makes sure that only the expected default RoleTemplates exist. Because the RoleTemplate created had the default label, Rancher deletes it since it isn't actually part of the default RoleTemplates.

If you remove that label, it does not get deleted on start/upgrade. I would consider this expected behaviour. Users should not be re-using the labels Rancher uses for synchronizing the system. That could lead to inconsistencies across the system.
