### ISSUE TITLE
Azure Issues Clarification

### ISSUE THREAD

**Issue by outrunthewolf** [rancher/rancher#4537]
Firstly we love Rancher, the team and the community is doing an amazing job.

I'd like to clarify a few issues I have with the Azure driver, and double check I haven't missed anything.

 - I can only use virtual machines classic?
 - I can't spin up VM's inside existing  networks?
 - Which in turn means I can't really use security groups?
 - I also can't specify which ports to open on hosts when I create them?

OK thanks. This is not a whinge, i'd just like to know where I stand with Azure right now, and whether we can use it with Rancher.

Thanks :)

**Comment by vincent99** [comment]
We use docker-machine and what is shown is all the options available.  Microsoft has rewritten the driver to use the new mode ("ARM"?) and that was released in machine v0.7 a few days ago, but is not available in a Rancher release yet.  So that addresses the first point, not sure about 2nd and 3rd yet.  No drivers for any provided have individual port opening options beyond choosing security group(s).

**Comment by outrunthewolf** [comment]
Thanks for the reply.

So, support for Azure will get better over time, is Azure still a key component the team will be actively developing?

If that is the case, it's safe to say, complex Azure operations are not fully supported right now, check back later on in the year?

**Comment by deniseschannon** [comment]
@outrunthewolf Since we are just calling docker-machine to spin up Azure instances, you'll need to really ask your questions regarding development to the [docker machine team](https://github.com/docker/machine).

We are not actively doing any development with Azure regarding docker-machine.

**Comment by outrunthewolf** [comment]
Thank you x
