### ISSUE TITLE
[BUG] Rancher Webhook Version is not pinned

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#45418]
**Rancher Server Setup**
- Rancher version: 2.8.3
- Installation option (Docker install/Helm Chart): Docker install (but also likely affects helm install)
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: N/A local cluster only 
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
On rancher v2.8.3, the webhook version is not set in the settings, and the environment variable is empty, allowing the webhook to be automatically upgraded to newer versions.

**To Reproduce**
1. Run rancher/rancher:v2.8.3: `docker run -d --restart=unless-stopped -p 8080:80 -p 8081:443 -p 8082:6060 --name rancher --privileged rancher/rancher:v2.8.3`
2. Exec into the container: `docker exec -it rancher bash`.
3. Using kubectl, retrieve the setting for the webhook version: `kubectl get setting rancher-webhook-version -o yaml`
4. Check the environment variable of the container for the webhook version: `echo $CATTLE_RANCHER_WEBHOOK_VERSION`

**Result**

Step 3 returns an empty setting:
```yaml
apiVersion: management.cattle.io/v3
customized: false
default: ""
kind: Setting
metadata:
  name: rancher-webhook-version
source: env
value: ""
```

Step 4 returns an empty value as well.

**Expected Result**
The webhook version is returned (in the case of 2.8.3, this should be: `103.0.2+up0.4.3` for both the env var and the default in the yaml). 

**Screenshots**
N/A.

**Additional context**
This currently likely affects both 2.8 and 2.9. Since it appears to be introduced in #42000, it is likely not present in 2.7. This also likely affects other env variables that are set through this system including:
- The fleet Version
- The CSP Adapter Version

**Comment by maxsokolovsky** [comment]
## QA Testing

### Root cause

The Drone configuration never used the build system's variables with which to build images on release.

### What was fixed, or what changes have occurred

The new build system now also adjusts the Drone configuration file (.drone.yml) and makes its stages refer to the necessary variables (especially CATTLE_RANCHER_WEBHOOK_VERSION) when it builds the Docker images.

### Areas or cases that should be tested

### What areas could experience regressions?

### Steps

#### Test the fix

1. Start a Rancher instance based on a v2.8 image that contains the fix.
2. When the server boots up, check the following settings: rancher-webhook-version, fleet-version, csp-adapter-min-version.
3. Ensure its values match those found in the build system in `build.yaml`. None of these should be empty. Note that you should compare the values as they were defined in code from the same commit.
4. Make a downstream cluster. Ensure its webhook version is the same as that of the local cluster, specified in build.yaml.

#### Test a version without a fix

1. Start a Rancher instance based on a v2.8 image that doesn't have the fix.
2. When the server boots up, check the following settings: rancher-webhook-version, fleet-version, csp-adapter-min-version.
3. Ensure its values are empty.

**Comment by brudnak** [comment]
Validated and passing on:
- `2.8.5-rc1-s4`
- `test-webhook:v0.4.6-rc1-s4`

**Comment by maxsokolovsky** [comment]
@brudnak, I also tested this on v2.8.5-rc2 and found no problems.
It would be good to test this on the final RC of v2.8.5, because it uses the actual webhook image, not `test-webhook`.
