### ISSUE TITLE
Unable to run rancher host/agent on same machine that rancher/server container on

### ISSUE THREAD

**Issue by hrqiang** [rancher/rancher#4543]
CentOS7.2.1511 kernel 3.10.0-327.13.1, docker 1.11.0, build 4dc5990. 
Trying to run rancher/agent host on same machine that rancher/server container on.
With rancher server public address, it stuck at curl command.
From the agent host, not able to ping public IP. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`localauth` `admin`|
|Route|`authenticated.project.help`|

**Comment by mishak87** [comment]
I think this is due to missing rule in iptables that would allow translating public ip port to localhost.

**Comment by deniseschannon** [comment]
@hrqiang Did you review the faqs on what could have happened with your rancher-agent?

http://docs.rancher.com/rancher/faqs/agents/

**Comment by hrqiang** [comment]
Thanks @mishak87. I think that's the reason. I have rancher/server and registry running on this host. But when I run rancher agent, it's not able to connect to rancher/server public IP and port.

**Comment by hrqiang** [comment]
@deniseschannon  Yes. I read that. But still cannot find out.

**Comment by stmaute** [comment]
I have the same problem as @hrqiang with rancher server and agent at the same host on a CentOS machine. 
I am sure the problem have something to do with iptables. I tested it with firewalld and also only with iptables service and both times the agent couldn't connect back to the server. 
In the logs from my agent: <Ip-Adresse> is not accessible!
Without firewalld and iptables deactivated every thing worked fine.

So is it possible to have firewalld activated and run rancher correctly?

**Comment by hrqiang** [comment]
@stmaute  Even I stop iptables. It's stuck at 
"
INFO: Starting agent for 656A20ECB961D4BEA063
INFO: Access Key: 656A20ECB961D4BEA063
INFO: Config URL: http://8.25.218.10:8080/v1
INFO: Storage URL: http://192.168.1.88:8080/v1
INFO: API URL: http://192.168.1.88:8080/v1
INFO: IP: 192.168.1.88
INFO: Port:
INFO: Required Image: rancher/agent:v1.0.1
INFO: Current Image: rancher/agent:v1.0.1
INFO: Using image rancher/agent:v1.0.1
INFO: Downloading agent http://192.168.1.88:8080/v1/configcontent/configscripts
{"id":"b2aa58db-7e3b-4014-bc47-b3a7b82d5691","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}"

**Comment by stmaute** [comment]
@hrqiang First some question to help me understand your infrastructure.
Where do you run the rancher server and agent? On a VM, localhost or in the Cloud?
What's your Host Registration URL in the settings? Because I see two different IP adresses.

**Comment by gbisheimer** [comment]
I had the same issue. Fixed that by deleting the files under /var/lib/rancher (only the files, not the folders).

In case your server uses a domain name (i.e. rancher.server.com), edit the /etc/hosts file and add the server address to it. I prefer to use the internal IP address instead of the public IP because I had fewer problems this way.

Then, rerun the agent registration:

sudo docker run -e CATTLE_AGENT_IP=[PRIV-IP-ADDRESS] --add-host rancher.server.com:[PRIV-IP-ADDRESS] -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 https://rancher.server.com/v1/scripts/753155FC97D6375C1F3A:1468022400000:JWzjpNACU9EjJ3iRyGueT8ooCxQ

Hope it helps.

**Comment by deniseschannon** [comment]
@hrqiang Are you still having issues?

**Comment by danielschlegel** [comment]
I have the same Problem. Adding host do work with other hosts but not with host on wich ranger is running.

sudo docker run -e CATTLE_AGENT_IP=[PRIV-IP-ADDRESS] --add-host rancher.server.com:[PRIV-IP-ADDRESS] -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://[PRIV-IP-ADDRESS]:8080/v1/scripts/xxx:xxx
 
INFO: Running Agent Registration Process, CATTLE_URL=http://10.1.5.136:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.11.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.2
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.5.4
INFO: docker version: Git commit (server): b9f10c9
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 3
INFO: docker info: Images: 3
INFO: docker info: Storage Driver: devicemapper
INFO: docker info: Pool Name: docker-8:1-132627-pool
INFO: docker info: Pool Blocksize: 65.54 kB
INFO: docker info: Base Device Size: 10.74 GB
INFO: docker info: Backing Filesystem: xfs
INFO: docker info: Data file: /dev/loop0
INFO: docker info: Metadata file: /dev/loop1
INFO: docker info: Data Space Used: 1.325 GB
INFO: docker info: Data Space Total: 107.4 GB
INFO: docker info: Data Space Available: 41.88 GB
INFO: docker info: Metadata Space Used: 2.277 MB
INFO: docker info: Metadata Space Total: 2.147 GB
INFO: docker info: Metadata Space Available: 2.145 GB
INFO: docker info: Udev Sync Supported: true
INFO: docker info: Deferred Removal Enabled: false
INFO: docker info: Deferred Deletion Enabled: false
INFO: docker info: Deferred Deleted Device Count: 0
INFO: docker info: Data loop file: /var/lib/docker/devicemapper/devicemapper/data
INFO: docker info: Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
INFO: docker info: Library Version: 1.02.107-RHEL7 (2016-06-09)
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 3.10.0-327.22.2.el7.x86_64
INFO: docker info: Operating System: CentOS Linux 7 (Core)
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 23.39 GiB
INFO: docker info: Name: dev
INFO: docker info: ID: DQVZ:DBSG:HGRM:DVG3:IOC4:XWVF:3C2D:FJTL:VKHT:MM2P:OTB6:RG5E
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://[PRIV-IP-ADDRESS]:8080/v1
ERROR: http://[PRIV-IP-ADDRESS]:8080/v1 is not accessible

wget http://[PRIV-IP-ADDRESS]:8080/v1 
--2016-07-21 18:02:52--  http://[PRIV-IP-ADDRESS]:8080/v1
Connecting to 10.1.5.136:8080... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

**Comment by danielschlegel** [comment]
Description how you can reproduce is here: https://github.com/rancher/rancher/issues/5536

**Comment by deniseschannon** [comment]
Please open a new issue if anyone is still having this issue.

**Comment by hholst80** [comment]
I still have this issue?

```
hholst@fb-hholst3:~/test5$ sudo docker run -e CATTLE_AGENT_IP="10.46.161.106"  --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://localhost:8080/v1/scripts/777703ACD0B87294B61E:1478167200000:gofAQVGmSArBZlQ2BiqUVnRIA

INFO: Running Agent Registration Process, CATTLE_URL=http://10.46.161.106:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.12.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.12.3
INFO: docker version: Server API version: 1.24
INFO: docker version: Go version (server): go1.6.3
INFO: docker version: Git commit (server): 6b644ec
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 375
INFO: docker info: Images: 1186
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 1677
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 4.4.0-43-generic
INFO: docker info: Operating System: Ubuntu 16.04.1 LTS
INFO: docker info: CPUs: 56
INFO: docker info: Total Memory: 62.84 GiB
INFO: docker info: Name: fb-hholst3
INFO: docker info: ID: OCTE:L424:L5TD:4NQ3:ZCS2:AQFZ:HP64:HJBP:MNEB:6PSP:5YTE:A3G3
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: docker info: Labels:
WARNING: No swap limit support
INFO: docker info: provider=generic
INFO: Attempting to connect to: http://10.46.161.106:8080/v1
INFO: http://10.46.161.106:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Systemd: true
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7faa31258e50>: Failed to establish a new connection: [Errno 111] Connection refused',))
hholst@fb-hholst3:~/test5$ 
```

**Comment by tiangolo** [comment]
I will cross-post my solution for a similar problem that I posted here: https://github.com/docker/docker/issues/16137#issuecomment-271615192 as it seems it could also be relevant in this issue (this is one of the issues I found and followed while investigating my problem).

I'm sorry if any of you consider it "spam", but as it is a possible solution I think it's best to share it.

---

**Note**: How I fixed it is a section below.

I was having issues with `firewalld` and Docker, specifically with Rancher v1.2 in CentOS 7.

Rancher needs a container to be able to communicate to the host via it's external (possibly local) IP address.

It was a requirement to have `firewalld` enabled and working.

## Environment

**OS**: `CentOS Linux release 7.3.1611 (Core)`

**Kernel** updated manually using "elrepo" to be able to use Overlay2 (`devicemapper` gave us several problems), although I don't think the kernel or the back end store is related to the problem: `4.9.0-1.el7.elrepo.x86_64`

**Docker**: 

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
[root@node19 cerebro]# uname -r
4.9.0-1.el7.elrepo.x86_64
[root@node19 cerebro]# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**`firewalld` is enabled**: 

```
systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since jue 2017-01-05 18:04:12 COT; 4 days ago
     Docs: man:firewalld(1)
 Main PID: 24584 (firewalld)
   Memory: 46.5M
   CGroup: /system.slice/firewalld.service
           └─24584 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D PREROUTING' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER-ISOLATION' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -n -L DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER-ISOLATION -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8' failed:
```

...but those errors in `firewalld` are expected as pointed out in: https://github.com/docker/docker/issues/16137#issuecomment-269398488


## The problem

`firewalld` uses `iptables` and IPtables rules under the hood, but the way it "works" is with different "zones", with different levels of access (as I understand, different sets of `iptables` rules for each "zone").

The `docker0` network interface is not assigned to any zone, so, some of its communications are blocked.

In my case, running the Rancher "agent" (a Docker container) with `firewalld` active gives errors about not being able to connect to the Rancher server (via it's external IP, in where the Rancher server, another container, is listening to). But with `firewalld` inactive, it works normally.

To make it worse, in all the systems I have tested (bare metal and Linode VPS) the `docker0` interface's `firewalld` zone cannot be modified using `firewalld` commands, because it is "controlled" by the "NetworkManager".

## The fix

* Check the `firewalld` "zone" asigned to the Docker interface:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If it says "no zone", you need to add it to the `trusted` zone

```bash
firewall-cmd --permanent --zone=trusted --change-interface=docker0
```

* If the previous command returns a message like:

```
The interface is under control of NetworkManager, setting zone to 'trusted'.
success
```

...it means that `firewalld` cannot control the zone of the interface (even if it says "success").

You can check that the zone was not assigned by running again:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If that's the case, you need to use the "NetworkManager" and restart the `docker0` interface, so first stop the `docker` daemon:

```bash
systemctl stop docker
```

* Now use the "NetworkManager" command line interface to set the zone of the `docker0` interface to `trusted`:

```bash
nmcli connection modify docker0 connection.zone trusted
```

* Now turn the `docker0` interface off:

```bash
ifdown docker0
```

* And turn it on again:

```bash
ifup docker0
```

* And check that the `firewalld` zone assigned to the interface `docker0` is "trusted":

```bash
firewall-cmd --get-zone-of-interface=docker0
```
...now it should return `trusted` instead of `no zone`

* Now you can start Docker again:

```bash
systemctl start docker
```

* Check if the problem you had was solved

## References

http://unix.stackexchange.com/a/225845/90829

[Introduction to FirewallD on CentOS - Linode](https://www.linode.com/docs/security/firewalls/introduction-to-firewalld-on-centos)

[RedHat forums (in the comments is mentioned the `nmcli`)](https://access.redhat.com/discussions/1455033)

[RedHat docs for `nmcli`](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Using_the_NetworkManager_Command_Line_Tool_nmcli.html)

**Comment by gsmafra** [comment]
Same problem with HTTPConnectionPool, also tried to map rancher/server to a different port.

**Comment by x0x01** [comment]
On my Ubuntu 16.04 it's iptables issue, I flush any rules and set policy to ACCEPT, restart docker daemon - problem solved with default agent cmd from webUI, without any CATTLE_AGENT_IP, etc.

**Comment by dhysf** [comment]
I don't think set CATTLE_AGENT_IP is success.
`docker run -e CATTLE_AGENT_IP="10.225.4.176"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://10.225.4.176:8080/v1/scripts/74D4BB42C1E8E923ECAB:1483142400000:OgSPMn2dx7ej6sR2TwfJLtrMhE

INFO: Running Agent Registration Process, CATTLE_URL=http://10.225.4.176:8080/v1
INFO: Attempting to connect to: http://10.225.4.176:8080/v1
INFO: http://10.225.4.176:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=E1800C11430EA3FEF280
INFO: ENV: CATTLE_AGENT_IP=10.225.4.176
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://10.225.4.176:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=172.17.0.1
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.6
INFO: Deleting container rancher-agent`

**Comment by jamesacampbell** [comment]
@subvillion That UPD3 worked great for me on RHEL 7.4 VM in parallels. Thank you!
