### ISSUE TITLE
k8s 1.29 support for cis-benchmark 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45465]
## Add k8s 1.29 support for cis-benchmark 

* Update rancher-cis-benchmark to 6.0.0-rc2
* Update security-scan to `v0.2.15`
* Update kubectl to `v1.28.7`
* Update cis-operator to `v1.0.13`
* Remove `psp enable` from values.yaml
* Sync with [dev-v2.8
](https://github.com/rancher/charts/tree/24f2718054a059c1d0f43e7d45ef1469a57f09d1)

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9.0-alpha5, using CIS chart 6.0.0-rc3

Fresh install - CIS v1.8-permissive profile scan:
- RKE1 v1.29.5-rancher1-1 node driver and custom - passed
- RKE2 v1.29.5+rke2r1 node driver and custom - observed below failures which are expected [42971](https://github.com/rancher/rancher/issues/42971) 
```
Fail
1.1.1	Ensure that the API server pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.3	Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.5	Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.7	Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
```
- K3s v1.29.5+k3s2 node driver and custom - passed

Upgrade checks :
- Provisioned v1.28 RKE1, RKE2 and K3s node driver clusters.
- Installed 6.0.0-rc3 CIS chart.
- Upgraded clusters to v1.29
- Ran permissive profile scan and it passed on all clusters except failures on RKE2 which is expected as mentioned in Fresh install.

Hardened RKE1, RKE2 and K3s - CIS v1.8 permissive as well as hardened profile:
- RKE1 v1.27 - scan failed with below expected failure - [42971](https://github.com/rancher/rancher/issues/42971) 
```
Mixed
4.1.7	Ensure that the certificate authorities file permissions are set to 600 or more restrictive (Automated)
```
- RKE2 v1.27 - passed.
- K3s v.127 - passed.

Local cluster checks:
- Provisioned RKE1, RKE2, and K3S v1.29 cluster and ran permissive v1.8 profile scan - passed

Since all the tests passed or show expected result. Hence, closing the ticket.
