### ISSUE TITLE
Validate SLE Micro 6 on Rancher

### ISSUE THREAD

**Issue by daviswill2** [rancher/rancher#45571]
Request description:
Rancher Manager v2.9.0
Add support for SLE micro 6.0

**Comment by susesgartner** [comment]
SLE micro 6 testing summary
---
AWS 
---
| Scenario | Test Case | vSphere 7 Result| vSphere 8 Result|
|---|---|---|---|
| 1. | Provisioning RKE1 Node Driver cluster | FAIL | FAIL|
| 2. | Provisioning RKE2 Node Driver cluster | PASS| PASS|
| 3. | Provisioning K3s Node Driver cluster | PASS| PASS|
| 4. | Provisioning RKE1 Custom cluster | FAIL | FAIL|
| 5. | Provisioning RKE2 Custom cluster | PASS| PASS|
| 6. | Provisioning K3s Custom cluster | PASS| PASS|
| 7. | Provisioning RKE1 imported cluster | PASS | PASS|
| 8. | Provisioning RKE2 imported cluster | PASS| PASS|
| 9. | Provisioning K3s imported cluster | PASS| PASS|
| 10. | Provisioning Rancher with SLE Micro local cluster | N/A| N/A|
 
---
Provisioning RKE1 Node Driver cluster `2.8-head`:
---
1. Create a 3 node all roles RKE1 node driver cluster
2. Wait until all nodes come up active
 
Results: The nodes failed to provision and reported an OS error.
 
---
Provisioning RKE2 Node Driver cluster `2.8-head`:
---
1. Create a 3 node all roles RKE2 node driver cluster
2. Wait until all nodes come up active
 
Results: The cluster comes up active and all Pods/Workloads are healthy

---
Provisioning K3s Node Driver cluster `2.8-head`:
---
1. Create a 3 node split role K3s node driver cluster
2. Wait until all nodes come up active
 
Results: The cluster comes up active and all Pods/Workloads are healthy

---
Provisioning RKE1 Custom cluster `2.8-head`:
---
1. Create a 3 node all roles RKE1 custom cluster
2. Wait until all nodes come up active
 
Results: The nodes failed to provision and reported an OS error.
 
---
Provisioning RKE2 custom cluster `2.8-head`:
---
1. Create a 2 node stacked roles RKE2 custom cluster
2. Wait until all nodes come up active
3. Reboot a node in the cluster (validating [38448](https://github.com/rancher/rancher/issues/38448))
4. Verify that the cluster returns to a healthy state
 
Results: The cluster comes up active and all Pods/Workloads are healthy

---
Provisioning K3s custom cluster `2.8-head`:
---
1. Create a 2 node stacked role K3s custom cluster
2. Wait until all nodes come up active
 
Results: The cluster comes up active and all Pods/Workloads are healthy

---
Provisioning RKE1 imported cluster `2.8-head`:
---
1. Create a 1 node all roles RKE1 imported cluster
2. Import it into rancher
3. Wait for the cluster to become available
 
Results: The cluster imports successfully and all Pods/Workloads are healthy
 
---
Provisioning RKE2 imported cluster `2.8-head`:
---
1. Create a 1 node all roles RKE2 imported cluster
2. Import it into rancher
3. Wait for the cluster to become available
 
Results: The cluster imports successfully and all Pods/Workloads are healthy

---
Provisioning K3s imported cluster `2.8-head`:
---
1. Create a 1 node all roles K3s imported cluster
2. Import it into rancher
3. Wait for the cluster to become available
 
Results: The cluster imports successfully and all Pods/Workloads are healthy
---

Additional Notes:
RKE1 is expected to fail for custom/node driver clusters since SLE micro is not in the docker install script see: [43693](https://github.com/rancher/rancher/issues/43693)

**Comment by snasovich** [comment]
@susesgartner @daviswill2 , I don't think it's fair to call it "Done" while https://github.com/rancher/rancher/issues/45815 is applicable. Am I missing something here?

**Comment by Sahota1225** [comment]
Since, https://github.com/rancher/rancher/issues/45815 is ready for QA, moving this issue to Ready for QA

**Comment by susesgartner** [comment]
Closing since https://github.com/rancher/rancher/issues/45815 has been fixed
