### ISSUE TITLE
CA check improvements for `system-agent`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45581]
Placeholder
SURE-7665

**Comment by snasovich** [comment]
Blocked on design review currently.

**Comment by MbolotSuse** [comment]
Depends on #45628.

**Comment by Sahota1225** [comment]
https://github.com/rancher/rancher/issues/45973

**Comment by markusewalker** [comment]
Tested this with results over in Qase test run /RM/1631. I noted the following failure:

|#|Scenario|Result|
|---|---|---|
|4|Setup Rancher with valid ca-certs and `agent-tls-mode=system-store`|:x:|

**VALIDATION STEPS**
1. Setup Rancher v2.9-head with a valid cert.pem and/or key.pem file.
     - Ensured  `agentTLSMode=system-store` in the helm install command.
2. Ran command `kubectl get settings agent-tls-mode -o yaml` and noted that the value is `strict`.

There are two other scenarios that have the same steps as above that have not been tested yet due to this failure. Marking as blocked until this is resolved.

**Comment by MbolotSuse** [comment]
@markusewalker Can you provide more details? The default on 2.9.0 will be strict, but the actual value should be as in the helm command, `system-store` - your output doesn't provide sufficient detail to determine if that is the case.

**Comment by markusewalker** [comment]
@MbolotSuse sure, updated my comment with the information we discussed offline.

**Comment by markusewalker** [comment]
Re-ran the test cases outlined in Qase test run /RM/1631. Using `v2.9.0-alpha7`, I was successfully able to  validate this issue. Summary of the scenarios tested provided below:

|#|Scenario|Result|
|---|---|---|
|1|Validate Rancher is accessible with valid ca-certs|:white_check_mark:|
|2|Validate Rancher is inaccessible with invalid ca-certs|:white_check_mark:|
|3|Validate Rancher is unusable with invalid ca-certs and `agentTLSMode=system-store`|:white_check_mark:|
|4|Validate Rancher is accessible/usable with valid ca-certs and `agentTLSMode=system-store`|:white_check_mark:|
|5|Update `agentTLSMode` from `strict` to `system-store`|:white_check_mark:|
|6|Update `agentTLSMode` from `system-store` to `strict`|:white_check_mark:|
|7|Upgrade Rancher from v2.8-head -> v2.9-head|:white_check_mark:|
|8|Upgrade Rancher from v2.8-head -> v2.9-head w/`agentTLSMode=strict`|:white_check_mark:|
