### ISSUE TITLE
add new agent-tls-mode setting

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#45628]

**Comment by maxsokolovsky** [comment]
## QA Testing

### Root cause

### What was fixed, or what changes have occurred

A new setting `agent-tls-mode` was added in v2.7, 2.8, 2.9.

In v2.7 and 2.8, the default value is `system-store`. In v2.9, the default value is `strict`.
But on upgrades from v2.7/2.8 to 2.9, Rancher should keep the default as `system-store`.

### Areas or cases that should be tested

1. Upgrade from v2.7/2.8 without the setting to v2.9.0.
2. Upgrade from v2.7/2.8 with the setting to v2.9.0.
3. Fresh installation of v2.9.0.

### What areas could experience regressions?

### Steps

#### Test an upgrade from a 2.8 version that does not have the new setting.

1. Start an instance of Rancher v2.8.4.
2. Ensure the `agent-tls-mode` setting doesn't exist.
3. Upgrade Rancher to v2.9.0.
4. Ensure the setting exists with a Default `system-store`. Note that it's fine that the Value is empty.

#### Test an upgrade from a 2.8 version that must have the new setting.

1. Start an instance of v2.8 Rancher that has the setting created on boot.
2. Ensure the `agent-tls-mode` setting exists with a Default `system-store`.
3. Upgrade Rancher to v2.9.0.
4. Ensure the setting exists with the same Default `system-store`. Note that it's fine that the Value is empty.

#### Test initial setup with v2.9.0.

1. Start an instance of v2.9.0 Rancher that has the setting created on boot.
2. Ensure the `agent-tls-mode` setting exists with a Default `strict`. Note that it's fine that the Value is empty.

Repeat the above tests, but where you used v2.8, use v2.7.

**Comment by MbolotSuse** [comment]
## Release Note

Added a new setting, `agent-tls-mode`, which allows users to specify if agents will use strict certificate verification when connecting to Rancher. Can be set to `strict` (which requires the agent to verify the cert using only the Certificate Authority in the `cacerts` setting) or `system-store` (which allows the agent to verify the cert using any Certificate Authority in the operating system's trust store). This setting will default to `strict` on new installs of 2.9.0+, but will be `system-store` on new installs of 2.8 or upgrades to 2.9 from 2.8.

### Breaking Changes

When `agent-tls-mode` is set to strict, users must provide the certificate authority to Rancher or downstream clusters will disconnect from Rancher, and require manual intervention to fix. This applies for several setup types, including:
- Let's Encrypt - when the setting is `strict`, users must upload the Let's Encrypt Certificate Authority and provide `privateCA=true` when installing the chart.
- Bring Your Own Cert - when the setting is `strict`, users must upload the Certificate Authority used to generate the cert and provide `privateCA=true` when installing the chart.
- Proxy/External - when the setting is `strict`, users must upload the Certificate Authority used by the proxy and provide `privateCA=true` when installing the chart.

**Comment by maxisam** [comment]
@MbolotSuse 

> Let's Encrypt - when the setting is strict, users must upload the Let's Encrypt Certificate Authority and provide privateCA=true when installing the chart.


should this be `privateCA=false` here
