### ISSUE TITLE
[RFE]  Capture LastUsed time for tokens

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#45732]
Currently it's impossible to tell when a token was last used, which is common requirement nowadays.

We want to capture the last time a token was used when a request is authenticated.
The implementation should take limiting number of writes (cap it at a second resolution) and ACE into the consideration.

UI should expose a new column `Last Used` in the "Account and API Keys". If the relative time is used to output the value we should also have a tooltip with the absolute timestamp in order to be able to tell the exact last time of when the token was used.

https://suse.slack.com/archives/C02CX064EBX/p1710853982257959

**Comment by pmatseykanets** [comment]
# Release notes

## Rancher General

### Behavior Changes

Rancher now captures the last used time for Tokens with the second precision and stores it in the `lastUsedAt` field. If Authorized Cluster Endpoint is enabled and used on a downstream cluster Rancher captures the last used time in the ClusterAuthToken object and makes the best effort to sync it back to the corresponding Token in the upstream.

**Comment by nwmac** [comment]
@samjustus @andreas-kupries I don't think we have considered the upgrade scenario with what has been implemented. There is no way to differentiate between a token that existing before this feature was added and one that was created after this feature was added - so if I create a token in 2.9 and use it and then upgrade, it does not have a `lastUsedAt` field. Equally, if I create a new token and don't use it, it also does not have a `lastUsedAt` field - so we can not differentiate between old tokens that might have been used and new tokens which we know have never been used.

We need to address this case before we can add UI.

^ FYI @gaktive

**Comment by nwmac** [comment]
My suggestion would be to add a `hasBeenUsed` boolean field - this is set to `false` when a token is created and `true` when used. We can then differentiate between old tokens that don't have this field (show as last used, Unknown) and new tokens that have never been used (field set to false).

**Comment by andreas-kupries** [comment]
Also ping @pmatseykanets

**Comment by pmatseykanets** [comment]
> I don't think we have considered the upgrade scenario with what has been implemented. There is no way to differentiate between a token that existing before this feature was added and one that was created after this feature was added...

@nwmac We did considered the upgrade. This feature (the semantics of using this field) should work exactly like LastLogin for users. There is no need to differentiate between tokens before and after this field was added. Meaning "not used" is semantically equal to "unknown if it was used". This field is optional (null'able). It's either there or not. If it's there it contains a valid timestamp.
Adding an additional field `hasBeenUsed` doesn't help with figuring out if one of the existing tokens was ever used or not.

**Comment by mattfarina** [comment]
How is a customer supposed to know if a token has been used but we don't know the last used time or if the token has never been used? UI has no way to distinguish this situation. _Not used_ is different from _unknown when last used_.

Or, another way to put it, who do you expect a UI to present this information for customers to see and understand?

**Comment by pmatseykanets** [comment]
> Not used is different from unknown when last used.

Obviously, in a strict/direct sense. Now for (relatively) short lived tokens like session and api tokens with expiration that line becomes fuzzier the shorter the TTL of the token.

> Or, another way to put it, who do you expect a UI to present this information for customers to see and understand?

IMHO UI should present it exactly how `LastLogin` information is presented for the user today as `LastUsedAt` is complimentary piece to the `LastLogin`. Today the UI shows a `-` for this as far as I recall.

> How is a customer supposed to know if a token has been used but we don't know the last used time or if the token has never been used?

Generally proving the negative is hard or impossible in many cases. Meaning no matter how many new fields we add to the token it's impossible to know if the previously issued token (especially without expiration) was ever used or not.

More over for all newly issued tokens you don't really need this information (a new flag) to know if it was used. Since if it was used it would've had the value set. The longer since the upgrade the less meaning an additional flag has. Past the TTL is has no meaning at all.
In a sense a combination of `creationTimestamp` and `lastUsedAt` gives all the information they need for those who need to to differentiate for whatever reason. I.e if they write a script to clean up or show tokens that may need cleanup. Again for all existing tokens they will never know if they were ever used (e.g. some batch job that runs once a few months).

**Comment by samjustus** [comment]
@olblak

**Comment by pmatseykanets** [comment]
## Validation Template

## What was fixed, or what change has occurred

Rancher now captures the last used time for Tokens (with the second precision) and stores it in the `lastUsedAt` field. If Authorized Cluster Endpoint is enabled and used on a downstream cluster Rancher captures the last used time in the ClusterAuthToken object and makes the best effort to sync it back to the corresponding Token in the upstream.

## Areas or cases that should be tested

Make sure the new version of the webhook is running in both upstream and downstream clusters.
Check that the new webhook version doesn't break on the downstream cluster without ACE enabled.

## Without ACE

- Authenticate with a token (UI session, API token, kubeconfig token).
- Check that the `lastUsedAt` field is updated in the token object.
- Try to set an invalid value for the `lastUsedAt` field on the token object.
- Check that the request is rejected by the webhook.

## With ACE

- Enable ACE on the downstream cluster.
- Make sure the new version of kube-api-auth is running in the downstream cluster.
- Use the correct context to authenticate using ACE.
- Check that the `lastUsedAt` field is updated in the clusterauthtoken object and is synced back to the token in the upstream cluster.
- Use the normal context to avoid ACE authentication.
- Check that the `lastUsedAt` field is updated in the token object but wasn't synced to the corresponding clusterauthtoken object in the downstream cluster.
- Try to set an invalid value for the `lastUsedAt` field on the clusterauthtoken object.
- Check that the request is rejected by the webhook.

## What areas could experience regressions

Increased number of reconciliations for tokens caused by updating the `lastUsedAt` field.

## Are the repro steps accurate/minimal?

N/A.

**Comment by nwmac** [comment]
UI is pushing the work for this to 2.11 - we should discuss the UX - I think it is important to differentiate Never used vs Not Known.

**Comment by joesims22** [comment]
Validated on v2.10-head id `fcb4b0e`.  All test cases documented in test plan completed successfully.

**Comment by joesims22** [comment]
Platform Team testing for issue has been completed.

Issue can be closed once Bullseye QA testing has been completed.

**Comment by samjustus** [comment]
@nwmac can you create a ticket for us with what you want please? We think this would make things more confusing, so if you could spell it out that would help.

**Comment by git-ival** [comment]
@pmatseykanets I'm working through validating this issue with a focus on performance and I can't seem to get anything except for a HTTP 404 when trying to update a token with a PUT on `v3/tokens/<tokenAccessKey>`. 

I see this closed issue which seems like it could be related: https://github.com/rancher/rancher/issues/30230

**Comment by pmatseykanets** [comment]
@git-ival Seems like it's existing/expected behavior unrelated to the LastUsedAt functionality. Also this particular endpoint probably doesn't help much with the performance/stress testing of the new functionality.
`kubectl edit token <name>` can be used to update tokens if needed for test cases.

**Comment by pmatseykanets** [comment]
# Release notes

## Rancher General

### Behavior Changes

Rancher now captures the last used time for Tokens and stores it in the `lastUsedAt` field. If Authorized Cluster Endpoint is enabled and used on a downstream cluster Rancher captures the last used time in the ClusterAuthToken object and makes the best effort to sync it back to the corresponding Token in the upstream.

**Comment by Jono-SUSE-Rancher** [comment]
Currently in QA. Please close when completed. Thanks :)

**Comment by rancher-max** [comment]
We are finishing up a few performance use cases, but the initial checks look fine. We will release this and continue the performance validations, commenting on this with the final results.
