### ISSUE TITLE
Validate RKE SLE Micro 5.5 - Imported Only

### ISSUE THREAD

**Issue by daviswill2** [rancher/rancher#45869]
Request description:
Rancher Manager v2.9.0
Add support for RKE SLE micro 5.5 imported only

**Comment by susesgartner** [comment]
Ticket #45869 - Test Results - ✅ 
---
K8s version: v1.29.5-rancher1-1
Provider: AWS

AMI info:
---
Docker version: 24.0.7
AMI name: suse-sle-micro-5-5-byos-v20240113-hvm-ssd-x86_64
AMI provider: Suse (public)
Additional setup: 
1. Added docker permissions to the default user.
---
   
   

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Import 3 node split role cluster | PASS |
| 2. | Import 2 node split role cluster | PASS |
| 3. | Upgrade cluster | PASS |
| 4. | Reboot node | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.9-4dd0c38a2aab4f77271c07d2c887ecf5bbcea5e3-head`:
---
 
Scenario 1: Import 3 node split role cluster 
---
1. Create a standalone rke1 3 node split role cluster
2. Import the cluster in step 1 into rancher
 
Results: The cluster was successfully imported into rancher and all workloads were healthy
 
---
 
Scenario 2: Import 2 node split role cluster 
---
1. Create a standalone rke1 2 node stacked role cluster
2. Import the cluster in step 1 into rancher
 
Results: The cluster was successfully imported into rancher and all workloads were healthy
---
 
Scenario 3: Upgrade cluster
---
1. Create a standalone rke1 3 node split role cluster with k8s 1.28.10
2. Import the cluster in step 1 into rancher
3. Upgrade the k8s version to v1.29.5

Results: The cluster remained in stable state and all workloads remained healthy
---
 
Scenario 4: Reboot node
---
1. Create a standalone rke1 2 node stacked role cluster
2. Import the cluster in step 1 into rancher
3. Reboot the worker node

Results: The cluster recovered from the node reboot and all workloads remained healthy.
Additional notes: This test was added due to https://github.com/rancher/rancher/issues/38448
