### ISSUE TITLE
[BUG] `apiGroups` endpoint no longer accessible

### ISSUE THREAD

**Issue by jordojordo** [rancher/rancher#45955]
**Rancher Server Setup**
- Rancher version: `v2.9-head`  (`a84c3a2f36c1ddbbe3cd6f08b30f02de48bdaa31`)
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: Self-signed

**Information about the Cluster**
- Kubernetes version:  v1.30.1+k3s1 
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

The `apiGroups` endpoint no longer exists in v2.9 ( `<cluster-ip>/v1/apiGroups` ). This causes the schema in the UI for `apigroup` to not be defined, I use the `apigroup` schema in a number of places in the [Kubewarden UI Extension](https://github.com/rancher/kubewarden-ui/blob/6cf49b040488de5c3f25ef772cd247ee3ce41ad1/pkg/kubewarden/chart/kubewarden/admission/Rules/index.vue#L31).

**To Reproduce**

- Run the latest 2.9-head rancher image with:

```console
docker run -d --name rancher --privileged --restart unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.9-head
```

- Navigate to the apiGroups endpoint: `http://localhost/v1/apiGroups`

**Result**
Response returned is 404

**Expected Result**

Should show the `apiGroups` schema

**Screenshots**

_Errors from the Kubewarden UI when attempting to fetch the apigroups_

![kw](https://github.com/rancher/rancher/assets/40806497/ef5d7a34-08a0-4776-abd2-baa634c3671a)

**Additional context**

This is important for Kubewarden as I use this endpoint to determine the available apiGroups for policy rule configuration and contextAware configuration.

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

When the changes were made for rancher/steve#139, the order was changed for how resources were loaded from Kubernetes. In the old format, the proto.Models were parsed first, and the `ServerGroupsAndResources` were added after.  In the new format, `ServerGroupsAndResources` are parsed first. The information from the proto.Models are only used to add information to resources already identified by `ServerGroupsAndResources`.

Since APIGroups were in `proto.Models` but not in `ServerGroupsAndResources`, in the new format they were not included in the schemas, removing the endpoint from Steve.

## What was fixed, or what change have occurred

Steve now adds a basic, hardcoded schema for APIGroups before adding schemas from other sources. This allows the endpoint to be visible again. This hardcoding is acceptable since this appears to be the only resource of this type (Represented by something in kubernetes open api, but not a true schema, and customized in steve through the use of a template).

## Areas or cases that should be tested

The defect (the ability to use the apigroups endpoint).

## What areas could experience regressions

Steve schemas.

## Are the repro steps accurate/minimal?

Yes, the steps in the issue are accurate and complete.

**Comment by Priyashetty17** [comment]
Validated that apiGroups endpoint is accessible in both local and downstream clusters : `v2.9-ddabf6b2266255276352beb1eeb740d9e4de802d-head`
