### ISSUE TITLE
[BUG] Default Alert missing from monitoring dashboard

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#45977]
Found while testing https://github.com/rancher/charts/commit/414f0688c935dd41145a037c1ae25cae9ebe2159

Grafana dashboard fails to render. Navigating directly to the grafana metrics dashboard gives the same error as the rancher UI (when the loading indicator is hidden)

![image (1)](https://github.com/rancher/rancher/assets/15875150/e2e83ec9-8c20-4632-b008-874f5006b90f)

Backend needs guidance from the UI team. For these basic queries should we be able to swap v1 w/ v2 ?

**Comment by joshmeranda** [comment]
Just to add some more context, there are 2 separate issues here:

1. Deprecated Alertmanger API

Monitoring rebase missed an API deprecation for alertmanager when initially giving UI direction on what we'll need to support newer monitoring upstream. For the basic queries causing the error in the image above, exchanging `v1` with `v2` should be enough to resolve the issue.

2. Grafana Iframes Not Loading

The grafana iframes in the docker UI are not loading the graphs. The browser console shows some dashboards cannot be reached (ex `https://rancher.local.com/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/api/dashboards/uid/rancher-etcd-nodes-1`), realistically this shouldn't be an issue since the same or similar message is present in 2.8.4 as well.

Still looking for a root cause on the backend so this *might* be something in the UI. Its uncertain

**Comment by richard-cox** [comment]
There's been another change in behaviour since yesterday. Trying to install `104.0.0+up45.31.1` now fails with 
```
Error: YAML parse error on rancher-monitoring/charts/kube-state-metrics/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 25: mapping values are not allowed in this context
```

We won't be able to implement or test any changes until that's resolve.

1. Deprecated Alertmanger API

The URL used to fetch alert management events is in https://github.com/rancher/dashboard/blob/master/shell/components/AlertTable.vue. Is the ask for certain versions of rancher-monitoring chart we swap out v1 for v2? 

2.  Grafana Iframes Not Loading

When testing yesterday the metrics dashboard failed to load even outside of the UI (cluster --> `Monitoring` --> `Metrics Dashboard` link in `Grafana` card on right). I think that is problem part one.

Problem part two would be the different types of grafana chart that fail to load. If on the test system you see some load and some not on previous installs then would agree maybe that's working as intended. In a downstream 1.30 RKE2 Digital Ocean cluster using `103.1.1+up45.31.1` etcd, cluster and node charts load ok. once part one is solved i'll double check on the same system

**Comment by richard-cox** [comment]
The UI bugs (missing monitoring alerts and charts fail to render) are covered by https://github.com/rancher/dashboard/issues/11347 which has a PR in review

**Comment by pankajsqe** [comment]
There are no parsing errors on installing monitoring chart and Default alerts are visible along with grafana dashboard is loading.


rancher v2.9-head
cluster v1.29.4+rke2r1

![Image](https://github.com/user-attachments/assets/cd01e846-bed6-4ed0-9a91-e3700448c995)
![Image](https://github.com/user-attachments/assets/b37ec02f-7da6-4583-b23b-77dc9e3c6253)
![Image](https://github.com/user-attachments/assets/c1fc0530-217f-407f-842d-c775e0ca90bc)
![Image](https://github.com/user-attachments/assets/fe994b22-affe-4a7f-85ee-f1c4185224da)
