### ISSUE TITLE
Set Docker Install URL 26.1 as the default for RKE1

### ISSUE THREAD

**Issue by IsaSih** [rancher/rancher#46020]
**Is your feature request related to a problem? Please describe.**
According to user request in
(https://github.com/rancher/dashboard/issues/10996), set the Set Docker Install URL 26.1 as the default for RKE1

**Describe the solution you'd like**
Set Docker Install URL 26.1 as the default

**Comment by snasovich** [comment]
@IsaSih , the default was changed on backend when https://github.com/rancher/rancher/pull/45632 was merged on June 21st and I've just tried on `v2.9-head` (13494c6a541d408b00e78415d18128f642f295d0) and 26.1 is the default even when shown by UI:
![image](https://github.com/user-attachments/assets/d60a732f-340e-45a7-86fd-86138d380827)

Could you please either close this issue or provide more information on how to reproduce it?(looks like our conversations happened right around June 21st (e.g. https://github.com/rancher/dashboard/issues/10996#issuecomment-2182902358) and it wasn't checked after that time and before this issue was filed on July 4th).
