### ISSUE TITLE
[BUG] No version info found in KDM after rke-metadata-config changed

### ISSUE THREAD

**Issue by vatsalparekh** [rancher/rancher#46046]
**Rancher Server Setup**
- Rancher version: `v2.9.0-alpha7`

**Describe the bug**

When trying to change `rke-metadata-config` from the default value to any value, for example `dev-v2.8` or `release-v2.8`, the channelserver seems to be showing no release info after the refresh
```json
{
"type": "collection",
"links": {
"self": ["…/v1-rke2-release/releases"](https://localhost:8443/v1-rke2-release/releases)
},
"actions": { },
"resourceType": "release",
"data": [ ]
}
```

**To Reproduce**

Change the version in the `rke-metadata-config` in Global settings

**Result**
No release data on the channelserver and No KDM info when trying to create a new cluster

**Expected Result**

Should have simply fetched and shown the new release data

**Screenshots**

![image](https://github.com/rancher/rancher/assets/6758282/7dcfbb45-1c37-4961-a649-d9c0f1563ab0)

**Additional context**

**Comment by snasovich** [comment]
This is working as expected as `rke-metadata-config.url` was pointing to KDM data intended for previous Rancher releases (e.g. `https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json`) and Rancher properly filters out all RKE2 K8s versions based on `minChannelServerVersion` / `maxChannelServerVersion` set on these versions to be for Rancher 2.8.x, not 2.9.x. Note that versions do show up when trying to provision RKE1 clusters as for that case there is only min Rancher version specified.

The issue is NOT reproducible if `rke-metadata-config.url` is set to KDM data that is intended to be used for Rancher 2.9.x releases - e.g. fork of `dev-v2.9` like `https://raw.githubusercontent.com/snasovich/kontainer-driver-metadata/dev-v2.9/data/data.json`.
