### ISSUE TITLE
[Backport] Add a webhook check for the agent-tls-mode setting

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#46057]
Backport of https://github.com/rancher/rancher/issues/45589

**Comment by brudnak** [comment]
## Validation Environment




| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version starting         | v2.8-1dceeccd0eb996fcf8ab66282b00d0ec798bacaf-head |
| Installation option              | Helm (high availability)                           |
| RKE binary version used          | v1.5.10                                            |
| If Helm Chart k8s cluster        | v1.28.10                                           |
| Downstream cluster type          | Linode k3s                                         |
| Downstream K8s version           | 1.28.11+k3s2                                       |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin                                              |
| Browser type                     | Firefox Developer Edition                          |
| Browser version                  | 129.0b5 (64-bit)                                   |
| Dashboard                        | master 102f1e6                                     |
| Webhook version                  | rancher/rancher-webhook:v0.4.8-rc5                 |

<details>
    <summary>🏗️ Rancher Installation Details... CLICK TO EXPAND! ⬅️</summary>

```sh
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.crds.yaml

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

# Install the cert-manager Helm chart
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.15.0
```

`https://letsencrypt.org/certificates/` >>> `ISRG Root X1` >>> `pem`

```sh
kubectl -n cattle-system create secret generic tls-ca \
  --from-file=cacerts.pem=./cacerts.pem
```

```sh
helm install rancher rancher-alpha/rancher --devel \
  --namespace cattle-system \
  --set hostname=$REDACTED_URL \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$REDACTED_EMAIL \
  --set letsEncrypt.ingress.class=nginx \
  --set bootstrapPassword=$REDACTED_PASSWORD \
  --set rancherImage=rancher/rancher \
  --set rancherImageTag=v2.8-head \
  --version 2.8.6-alpha3 \
  --set global.cattle.psp.enabled=false \
  --set agentTLSMode=system-store \
  --set privateCA=true
```

</details>

<hr>

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                                               | PASS/FAIL |
| --- | -------- | -------------------------------------------------------------------------------- | --------- |
| 1   | P1       | [set agent-tls-mode setting during helm install to system-store](#test-1)        | ✅ PASS    |
| 2   | P1       | [set agent-tls-mode setting during helm install to strict](#test-2)              | ✅ PASS    |
| 3   | P0       | [Changing agent-tls-mode setting with kubectl](#test-3)                          | ✅ PASS    |
| 4   | P1       | [Adding force annotation using kubectl, change setting with kubectl](#test-4)    | ✅ PASS    |
| 5   | P1       | [Upgrade](#test-5)                                                               | ✅ PASS    |
| 6   | P1       | [Set tls-mode Strict with multiple downstream AgentTlsStrictCheck=True](#test-6) | ✅ PASS    |


<details>
    <summary>🚨 6 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / set agent-tls-mode setting during helm install to system-store Status: ✅ PASS  

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Install Rancher via helm
2. Include this set:
   - `--set agentTLSMode=system-store`
3. Once Rancher is setup check that status of the setting via kubectl

    ```sh
    kubectl get setting agent-tls-mode -o yaml
    ```
4. You should see the setting as `system-store`

**✅ Expected Outcome**

For `system-store` to be set

**✅ Actual Outcome**

Value system-store was set

</details>

<hr>

# 2 / set agent-tls-mode setting during helm install to strict Status: ✅ PASS

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Install Rancher via helm
2. Include this set:
   - `--set agentTLSMode=strict`
3. Once Rancher is setup check that status of the setting via kubectl

    ```sh
    kubectl get setting agent-tls-mode -o yaml
    ```
4. You should see the setting as `strict`

**✅ Expected Outcome**

For `strict` to be set

**✅ Actual Outcome**

`Strict` was correctly set

</details>

<hr>

# 3 / Changing agent-tls-mode setting with kubectl Status: ✅ PASS  

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a rancher with `--set agentTLSMode=system-store`
2. Create a downstream cluster
3. Ensure this downstream cluster has `AgentTlsStrictCheck` set to false
   - This can be checked by going to cluster management > edit the downstream cluster as yaml > check under status at the bottom for `AgentTlsStrictCheck`

        ```yaml
        status: 'False'
        type: AgentTlsStrictCheck
        ```
4. Now try changing the agent-tls-mode setting to strict using kubectl

    ```sh
    kubectl edit setting agent-tls-mode
    ```

5. Change the value from `system-store` to `strict`
   - This should be blocked by webhook since at least 1 downstream cluster has `AgentTlsStrictCheck` set to `'False'`

**✅ Expected Outcome**

For webhook to block this change to the agent-tls-mode setting

**✅ Actual Outcome**

Getting the expected error:

```log
error: settings.management.cattle.io "agent-tls-mode" could not be patched: admission webhook "rancher.cattle.io.settings.management.cattle.io" denied the request: value.default: Forbidden: AgentTlsStrictCheck condition of cluster c-m-c7bshql9 isn't 'True'
```

</details>

<hr>


# 4 / Adding force annotation using kubectl, change setting with kubectl Status: ✅ PASS
<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a rancher with `--set agentTLSMode=system-store`
2. Create a downstream cluster
3. Ensure this downstream cluster has `AgentTlsStrictCheck` set to false
   - This can be checked by going to cluster management > edit the downstream cluster as yaml > check under status at the bottom for `AgentTlsStrictCheck`

        ```yaml
        status: 'False'
        type: AgentTlsStrictCheck
        ```
4. Now try changing the agent-tls-mode setting to strict using the Rancher UI
5. This can be accessed from starting at `dashboard/home` > click `Global Settings` (bottom left globe icon) > `Settings` > click the ellipsis (three dots) at the setting `agent-tls-mode` > `Edit Setting` > change the value to Strict > `Save`
6. This should be blocked by webhook as long as at least one downstream cluster has `AgentTlsStrictCheck` set to false
7. Now edit the `agent-tls-mode` setting using kubectl > `kubectl edit setting agent-tls-mode`
8. Add this annotation under metadata:

    ```yaml
    metadata:
      annotations:
        cattle.io/force: "true"
    ```
9. After this annotation is added try changing the agent-tls-setting to strict using kubectl
10. Now even if there is a downstream cluster that has `AgentTlsStrictCheck` set to false the webhook will allow it now


**✅ Expected Outcome**

The webhook should allow the setting to be changed now, even with a downstream cluster that has `AgentTlsStrictCheck` set to false

**✅ Actual Outcome**

Successful edit with annotation added

</details>

<hr>

# 5 / Upgrade Status: ✅ PASS

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with Rancher 2.8.5
2. Upgrade Rancher to 2.8-head
3. Add this env var to the rancher deployment > `CATTLE_AGENT_TLS_MODE` > value: `system-store`
4. Create a downstream cluster
5. Ensure this downstream cluster has `AgentTlsStrictCheck` set to false
   - This can be checked by going to cluster management > edit the downstream cluster as yaml > check under status at the bottom for `AgentTlsStrictCheck`

        ```yaml
        status: 'False'
        type: AgentTlsStrictCheck
        ```
6. Now try changing the agent-tls-mode setting to strict using kubectl
7. This should be blocked by webhook as long as at least one downstream cluster has `AgentTlsStrictCheck` set to false

**✅ Expected Outcome**

The UI action should be blocked by webhook

**✅ Actual Outcome**

Action is blocked by webhook

</details>

<hr>

# 6 / Set tls-mode Strict with multiple downstream AgentTlsStrictCheck=True Status: ✅ PASS

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a rancher with `--set agentTLSMode=system-store`
2. Create two downstream clusters
3. Ensure both downstream clusters have `AgentTlsStrictCheck` set to `'True'`
   - This can be checked by going to cluster management > edit the downstream cluster as yaml > check under status at the bottom for `AgentTlsStrictCheck`
4. Now try changing the agent-tls-mode setting to strict using kubectl

    ```sh
    kubectl edit setting agent-tls-mode
    ```

5. Change the value from `system-store` to `strict`
   - This should be allowed by webhook since both downstream cluster have `AgentTlsStrictCheck` set to `'True'`

**✅ Expected Outcome**

For the change to be successful since both downstream clusters have `AgentTlsStrictCheck` set to `'True'`

**✅ Actual Outcome**

The change was successful since both downstream clusters have `AgentTlsStrictCheck` set to `'True'`

</details>

<hr>

</details>

**Comment by brudnak** [comment]
setting not adjustable via the UI: https://github.com/rancher/dashboard/issues/11488
