### ISSUE TITLE
[v2.9] [Maintenance] Bump embedded system-agent within rancher-wins

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#46219]
For some time now `rancher-wins` has been embedded system-agent version `v0.2.11`, which is very outdated at this point (the most recent release is `v0.3.6`, with `0.3.7` planned for release alongside `2.9.0`). Importing this outdated version of the system-agent results in wins also importing outdated indirect dependencies which contain CVEs. In order to resolve a number of CVEs within `rancher-wins`, we will need to update the embedded system-agent version.

**Comment by HarrisonWAffel** [comment]
A full regression test will need to be done when this bump in merged into rancher/rancher, to ensure that the updated system-agent version does not introduce any regressions. This includes custom and node driver provisioned clusters, as well as upgrades and workload deployment.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|
|---|---|
|1|Run provisioning automated test suite on fresh install of v2.9-head|
|2|Run nodescaling automated test suite on fresh install of v2.9-head|
|3|Run snapshot automated test suite on fresh install of v2.9-head|
|4|Run upgrade automated test suite on fresh install of v2.9-head|
|5|Run certrotation automated test suite on fresh install of v2.9-head|
|6|Run provisioning automated test suite upgraded Rancher to v2.9-head|
|7|Run nodescaling automated test suite upgraded Rancher to v2.9-head|
|8|Run snapshot automated test suite on upgraded Rancher to v2.9-head|
|9|Run upgrade automated test suite on upgraded Rancher to v2.9-head|
|10|Run certrotation automated test suite on upgraded Rancher to v2.9-head|

**Comment by markusewalker** [comment]
Performed testing below. See results below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version:
     - Fresh install: `v2.9-head https://github.com/rancher/rancher/commit/25582765d25f0271f2ea648b3a29cca317b339ef`
     - Upgrade: `v2.9.0`

**TEST RESULT**
|#|Scenario|Result
|---|---|---|
|1|Run provisioning automated test suite on fresh install of v2.9-head|:white_check_mark:|
|2|Run nodescaling automated test suite on fresh install of v2.9-head|:white_check_mark:|
|3|Run snapshot automated test suite on fresh install of v2.9-head|:white_check_mark:|
|4|Run upgrade automated test suite on fresh install of v2.9-head|:white_check_mark:|
|5|Run certrotation automated test suite on fresh install of v2.9-head|skipped due to known issue https://github.com/rancher/rancher/issues/44979|
|6|Run provisioning automated test suite upgraded Rancher to v2.9-head|:white_check_mark:|
|7|Run nodescaling automated test suite upgraded Rancher to v2.9-head|:white_check_mark:|
|8|Run snapshot automated test suite on upgraded Rancher to v2.9-head|:white_check_mark:|
|9|Run upgrade automated test suite on upgraded Rancher to v2.9-head|:white_check_mark:|
|10|Run certrotation automated test suite on upgraded Rancher to v2.9-head|skipped due to known issue https://github.com/rancher/rancher/issues/44979
|11|Perform encryption key rotation|:white_check_mark:|
|12|Perform certificate rotation|:white_check_mark:|
