### ISSUE TITLE
ERROR: https://rancher.url/v1 is not accessible

### ISSUE THREAD

**Issue by tcdev0** [rancher/rancher#4630]
Rancher Version: v1.0.1
Docker Version: 1.11.1
OS: 16.04 LTS (Xenial Xerus)

**Steps to Reproduce:** 

1.Launch Rancher Server (node1)
```
$ docker run -d --name rancher-server -v /opt/rancher-data/mysql/:/var/lib/mysql --restart=always rancher/server:v1.0.1
```

2.Launch Nginx Proxy
```
$ docker run -d --restart=always --name nginx-rancher -v /opt/tls/chain.crt:/etc/rancher/cert-chain.crt -v /opt/tls/cert.key:/etc/rancher/cert.key -v /opt/nginx/default.conf:/etc/nginx/conf.d/default.conf -p 80:80 -p 443:443 --link=rancher-server nginx:latest
```

3.Launch Rancher Agent (node2)
```
$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.1 https://rancher.url/v1/scripts/6843FD60DBFC937583DB:1462017600000:vN9E9asJ23RRXIRhj3OIAP2uKTU
```

**Results:**

agent logs

```
INFO: Running Agent Registration Process, CATTLE_URL=https://rancher.url/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.11.1
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.1
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.5.4
INFO: docker version: Git commit (server): 5604cbe
INFO: docker version: OS/Arch (server): linux/amd64
WARNING: No swap limit support
INFO: docker info: Containers: 17
INFO: docker info: Images: 6
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 67
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 4.4.0-21-generic
INFO: docker info: Operating System: Ubuntu 16.04 LTS
INFO: docker info: CPUs: 2
INFO: docker info: Total Memory: 1.944 GiB
INFO: docker info: Name: docker-node2
INFO: docker info: ID: P5B2:Q2J6:BVMY:S34X:CONR:NJZB:KJ5T:TUA7:ER6K:EB6L:4VS4:RKX7
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: https://rancher.url/v1
ERROR: https://rancher.url/v1 is not accessible
...
ERROR: https://rancher.url/v1 is not accessible
ERROR: Could not reach https://rancher.url/v1. Giving up.
```

**curl (from docker container)**

```
root@79b0f9850e29:/# curl -i https://rancher.url/v1/scripts/6843FD60DBFC937583DB:1462014000000:CVX73vpjRVHj6uUhMIw3ugqdwMk
```
```
HTTP/1.1 200 OK
Server: nginx/1.9.15
Date: Sat, 30 Apr 2016 12:40:15 GMT
Content-Type: text/plain
Content-Length: 265
Connection: keep-alive
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a1
X-Api-Schemas: https://rancher.url/v1/schemas

#!/bin/sh

export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
export CATTLE_REGISTRATION_SECRET_KEY="6843FD60DBFC937583DB:1462014000000:CVX73vpjRVHj6uUhMIw3ugqdwMk"
export CATTLE_URL="https://rancher.url/v1"
export DETECTED_CATTLE_AGENT_IP="10.32.1.242"
```

**Expected:**

Agent should connect

**Comment by bjoernHeneka** [comment]
same issue

**Comment by WillTemeraire** [comment]
Yep, got the exact same Issue. Virtual Network with two small testmachines. One's running RancherOS, the other's running Ubuntu LTS 14.04. DNS is configured correctly, but nothing connects.

**Comment by deniseschannon** [comment]
Are you able to curl the Rancher/server?

http://docs.rancher.com/rancher/latest/en/faqs/agents/#how-to-check-your-host-registration-is-set-correctly

**Comment by tcdev0** [comment]
for my part everything was accessible via curl.

i switched to Ubuntu 14.04 with Docker 1.10.3 and everything works perfect. 

So ill wait for [#4491](https://github.com/rancher/rancher/issues/4491)

**Comment by WillTemeraire** [comment]
Same here. It was accessible via curl.

**Comment by dnkls** [comment]
the same problem i dont understand (((
In rancher/server i see in log : http: TLS handshake error from 30.131.25.236:37410 remote error: unknown certificate authority

In agent log: ERROR: https://32.131.23.4:8080/v1 is not accessible

i dont understand wat i shuld do(((
curl -i https://32.131.23.4:8080/scripts/E67B65C8D4A999A76214:1463259600000:8o8FelicUUCJWZjp8etWH9xQ66c

curl: (60) Peer certificate cannot be authenticated with known CA certificates
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

please tell my step by stem wuat shuld i doo. i dont understand meny moments from instruction becouse i have bad Eanglish

**Comment by deniseschannon** [comment]
Okay, I'm going to close this in favor of #4491.

**Comment by averri** [comment]
Hi all, for those who are having connection problems between Rancher Agent and Server, could you please post the contents of your `/var/lib/rancher/etc/agent.conf`?

**Comment by yenda** [comment]
I had this problem on CoreOS and the fix was just to open the ports:

sudo iptables -A INPUT -p udp --dport 500 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 4500 -j ACCEPT
