### ISSUE TITLE
[v2.10] Add support for Docker 27.0.x and 27.1.x

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46326]
Add support for docker 27.0.x and 27.1.x (up to patch versions available at the point of implementation)

Release notes:
* https://docs.docker.com/engine/release-notes/27.0/
* https://docs.docker.com/engine/release-notes/27.1/

ref issue: https://github.com/rancher/rancher/issues/45439

**Comment by vivek-shilimkar** [comment]
Tested docker 27.1.x and 27.0.x on latest versions of RHEL, Rocky, OL (8.10 and 9.4) and ubuntu 22.04, 24.04. 

Cluster provisioning works correctly. Hence, closing this issue.

**Comment by vivek-shilimkar** [comment]
reopening the ticket to test on other versions of the OSes.

**Comment by vivek-shilimkar** [comment]
Validated following docker install scripts on RHEL, Oracle Linux and Rocky (8.7, 8.8, 8.9, 9.1, 9.2, 9.3) with node driver and custom clusters. Docker install scripts works as expected and RKE1 cluster provisions successfully.

Since the docker script is validated on all the OS versions, this issue can be closed.
