### ISSUE TITLE
[Forwardport] MachineHealthCheck Object not deleted properly

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46442]
Forwardport for :https://github.com/rancher/rancher/issues/46236

**Comment by vivek-shilimkar** [comment]
### Validated the issue on v2.10-b6023c4eee4114bb49b9492072b7ffec46a08a23-head

1. Created v1.30.2+rke2r1 RKE2 node driver cluster with Auto Replace value set to 1 on AWS for 2 machine pools(1-cp and 1-etcd).
2. Validated machinehealthchecks objects created for both the machine pools in local cluster.

Tested the two different scenarios of changing the Auto Replace value. All the scenarios passed for k8s v1.30.2+rke2r1. Following scenarios were tested.
1. Case 1 updating Auto Replace value one by one.
2. Case 2 updating Auto Replace value simultaneously.

Since the machinehealthchecks objects are working as expected. Closing the issue.
