### ISSUE TITLE
CNI Driver 

### ISSUE THREAD

**Issue by benjohnlampitoc** [rancher/rancher#46524]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.30` Cattle: `v0.183.83` UI: `v1.6.52` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

We are having issues starting service. I think the CNI driver is the cause. How can I stop it? Should I upgrade it? What will be the effect if I upgrade it?
![cni driver updating in progress](https://github.com/user-attachments/assets/103267b1-fabb-49d7-88f7-31d979ae306c)
![unable to stop](https://github.com/user-attachments/assets/2d36799c-819d-4a53-965d-cb32a65aa7d8)

**Comment by benjohnlampitoc** [comment]
![image](https://github.com/user-attachments/assets/1152d19b-0474-4716-b114-08cb8c028ad6)

**Comment by pmckeithSUSE** [comment]
Hello. @benjohnlampitoc 

Thank you for being a loyal Rancher user!  I am glad to see that your system has been stable for more than 4 years without any updates.  It is a testament to the quality and reliability of Rancher that you and many of our customers rely upon.  I am however concerned that you are still relying on such an old version that is EoL and unsupported for 4+ years. As noted in the previous response Rancher 1.6.x is unsupportable due to its age.  If you are able to move to a current version of Rancher, please do so and SUSE could help.  You might find making such a large jump in versions a burden.  So if you would like assistance in moving to a currently supported Rancher, our partners or professional services would be happy to assist.  I am in NA so I personally would not be able to help but if you are interested in assistance, please contact me and I will find a contact for you.
