### ISSUE TITLE
[2.9] Rancher CLI panics when we try to switch context without any selection

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46869]
backport #45340

**Comment by dasarinaidu** [comment]
This issue is resolved on `v2.9-e65fefcaee6ca27ea4b78e355c745f34c27e5576-head`
CLI version : rancher-v2.9.2-rc3

Below tests got validated:
**TC 1:** **Validate rancher context switch**

1. Create a rancher server on 2.9-head
2. Installed rancher cli version v2.9.2-rc3
3. Ran the rancher context switch without running the login command

**TC 2:** **Validate rancher context switch on an upgraded rancher**

**TC 3:** **Validate rancher context switch error message**

**TC 4:**  **Validate rancher context switch error message, login with a user and make sure the errors are not displayed**
