### ISSUE TITLE
kubelet、kube-proxy container start error

### ISSUE THREAD

**Issue by logicigam** [rancher/rancher#4693]
after I add a new host ,kubelet container start to show some error:
W0505 08:33:24.432340   16732 server.go:445] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
2016/5/5 下午4:33:24W0505 08:33:24.432438   16732 server.go:406] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
2016/5/5 下午4:33:24I0505 08:33:24.709615   16732 server.go:683] Watching apiserver
2016/5/5 下午4:33:24W0505 08:33:24.718515   16732 kubelet.go:508] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"

as well as kube-proxy

 Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory

both container‘s cadvisor monitor are all right.container status are both stuck in Initializing

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.159.7` UI: `v1.0.7` |
|Access|`Disabled`|
|Route|`settings.projects.new`|

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/4429

**Comment by alena1108** [comment]
@logicigam could you check the following:

In the UI, go to System->Stack->pick Kubernetes stack. Then for services "kubelet" and "proxy" chose "View in API option". There check for the fields "State" and "health state"

If the state says "Active", but the healthState says "initializing" it means that the container came up fine, but health check performed by Rancher failed. It is most likely because the newly added host is unaccessible by other hosts in the system over ipsec network. Check http://docs.rancher.com/rancher/latest/en/faqs/troubleshooting/ for steps to make to fix communication error.

If the service state is not "Active", it means that there was some error in k8s startup process. 

I've checked running k8s containers on one of my systems, and I'm also seeing messages like:

kubelet, warning messages:
```
W0512 17:55:15.601619   12094 server.go:445] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
W0512 17:55:15.605802   12094 server.go:406] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
W0512 17:55:16.192550   12094 kubelet.go:508] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
```

proxy:
```
I0512 17:55:14.245313       1 iptables.go:177] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory
```
The fact that the last message is logged in INFO level, and warnings are ignored, means that all the above shouldn't affect functionality.

**Comment by lkinley** [comment]
I have the same issue.  The kubelet and proxy services are in an initializing state but appear to be running.

State says 'running', healthState is 'initializing'.
I can ping the hosts from other hosts.

This is running on AWS with 3 hosts.  I can provide whatever logs, etc needed to troubleshoot.

**Comment by alena1108** [comment]
@lkinley State saying running and healthState=initializing would mean failed health state. Pinging hosts might not be enough to debug ipsec problem. For that you would have to console to Rancher network agent on host1 and ping Rancher network agent ip (10.42.x.x ip address) residing on host2.

Also could you provide kubelet and proxy logs.

**Comment by alena1108** [comment]
@soumyalj please confirm that you don't see this error in the latest version of k8s you've tested.

**Comment by soumyalj** [comment]
Tested with master on Kubernetes 1.4 with template version v1.4.0-rancher1. No error messages seen as above in the Kubelet logs. The kubelet service was active and healthstate was healthy.
```
"name": "kubelet",
"state": "active",
"accountId": "1a5",
"assignServiceIpAddress": false,
"consumedByServiceIds": [ ],
"consumedServiceIds": [
"1s2",
],
"createIndex": 4,
"created": "2016-09-30T01:52:09Z",
"createdTS": 1475200329000,
"currentScale": 4,
"description": null,
"externalId": null,
"fqdn": null,
"healthState": "healthy",
```
