### ISSUE TITLE
[2.8] Rancher CLI panics when we try to switch context without any selection

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46933]
backport #46869

**Comment by dasarinaidu** [comment]
This issue is resolved on `v2.8-68e5d43e449fcd3ef73baf1caee98da6f0104eed-head`
CLI version : `rancher-v2.8.8-rc2`

Below tests got validated:
**TC 1: Validate rancher context switch**

1. Create a rancher server on 2.8-head
2. Installed rancher cli version v2.8.8-rc2
3. Ran the rancher context switch without running the login command

**TC 2: Validate rancher context switch error message**

**TC 3: Validate rancher context switch error message, login with a user and make sure the errors are not displayed**
