### ISSUE TITLE
Same host shows multiple times in UI after restarting the host

### ISSUE THREAD

**Issue by alexmaroz** [rancher/rancher#4698]
Rancher Version: v1.1.0-dev1

Docker Version: 1.11.1

OS: Any

Steps to Reproduce: restart connected host (multiple times)

Results: same host shows multiple times in UI (see attachment)

Expected: only one host in UI
![rancher](https://cloud.githubusercontent.com/assets/454135/15047894/f4d1876c-12b4-11e6-9c39-7fe569bb488a.png)

**Comment by cjellick** [comment]
@alexmaroz I see you've marked the OS as 'Any'. Have you reproduced this on any OS other than Boot2Docker?

This is a known issue with b2d VMs because its filesystem (outside of /var/lib/docker) is in-memory and goes away upon reboot and rancher stores some state necessary for identifying hosts in /var/lib/rancher.

**Comment by deniseschannon** [comment]
I just updated the docs in the FAQs as this is a common issue with b2d VMs.

http://docs.rancher.com/rancher/latest/en/faqs/agents/#why-is-the-same-host-showing-up-in-the-ui-multiple-times

@alexmaroz Please re-open if you can open it on other OSes.

**Comment by alexmaroz** [comment]
@cjellick, I just tested it on ubuntu 14.04.4. All work fine.

Thanks

**Comment by cjellick** [comment]
Thanks for testing it out @alexmaroz :-)
