### ISSUE TITLE
Where is the Swarm Master?

### ISSUE THREAD

**Issue by pascalandy** [rancher/rancher#4741]
I created a swarm environment with 2 nodes. 

I don't see any concept of a Swarm master node and there no mention of this concept in the docs - http://docs.rancher.com/rancher/latest/en/swarm/

I just want to be clear. When the Docker CLI will work ([issue here](https://github.com/rancher/rancher/issues/4145#issuecomment-217903124)), I expect the CLI to talk to my Swarm Master Host. Make sense? 

Is Swarm master install on the Rancher Server?
EDIT: At the moment, the only container running on the Rancher Server host is `rancher/server`.

Cheers!
https://twitter.com/_pascalandy

**Comment by deniseschannon** [comment]
I'm just reading up about swarm now and would you be able to point out the concept of this swarm master in the swarm docs itself?

**Comment by bradjones1** [comment]
@deniseschannon:
> I'm just reading up about swarm now and would you be able to point out the concept of this swarm master in the swarm docs itself?

See https://docs.docker.com/swarm/install-manual/#step-5-create-swarm-cluster - "Swarm master" appears to be a deprecated term, in favor of "primary manager," but the question is the same. I think it would be helpful to clarify in the Rancher documentation how the Swarm created by Rancher is configured. In addition, there's the concept of "replica" masters that could optionally be created in the swarm for a high-availability setup, and that may be helpful for Rancher to support in the future.

At a minimum, though, I think it would be good to improve [the README](https://github.com/rancher/swarm-agent/blob/master/README.md) on `rancher/swarm-agent` to explain how these containers work. It doesn't appear to follow the Docker Swarm docs on setting up a swarm, since if you go to the host running the agent containers and do a `docker info`, none of the Node data is shown. However, clicking the "CLI" tab in the web UI gives you a terminal in the `swarm-agent` container not running the `manage` command. Running `docker info` in that container reveals the nodes.

So if I can re-phrase the question, what is the purpose of the two `swarm-agent` containers that get created, and how do they differ in function?

**Comment by todd-alexion** [comment]
+1 NOTE: I am trying to introduce Rancher into the company I work for, and here is the use case I am presented with:

My boss wants a way to ssh into the swarm (manager, master, etc) and query the swarm cluster directly, like he was able to do when he setup the swarm cluster himself... (before I came along and messed up his world).

**Comment by pascalandy** [comment]
There is a big update with docker 1.12 that supports natively Swarm. 

root@pi6 $ docker swarm

Usage:  docker swarm COMMAND

Manage Docker Swarm

Options:
      --help   Print usage

Commands:
  init        Initialize a Swarm.
  join        Join a Swarm as a node and/or manager.
  update      update the Swarm.
  leave       Leave a Swarm.
  inspect     Inspect the Swarm

Run 'docker swarm COMMAND --help' for more information on a command.

I can understand how hard is it for Rancher's team to follow along.

**Comment by todd-alexion** [comment]
Thanks @pascalandy - I bet it is very hard to keep up with the Docker releases. However since Docker 1.12 is only a Release Candidate, I wouldn't expect the Rancher team to have already been working on that integration yet. Especially since 1.12 RC1 and RC2 both seem to have been released in the future (2016-07-14) - thats very hard to keep up with...

**Comment by bradjones1** [comment]
@todd-alexion I was just at Dockercon and after talking to the Rancher folks at their booth, it sounds like they will work with the 1.12 Swarm features as they roll out, but it indeed is still RC and probably needs to bake a while before rolling into production.

At the moment, though, you can get a CLI at the swarm master inside the web UI (Swarm > CLI) and you'll see the container ID as the hostname in the shell. Admittedly the web shell isn't always enjoyable to use, but that's how to do it, now.

Theoretically you can also set `DOCKER_HOST` and use some self-signed keys at a remote node, but #4145 seems to be an issue for myself and others when using that generated config.

**Comment by todd-alexion** [comment]
@bradjones1 Thanks for the info. The Rancher folks have always been very responsive, so I am not worried. However in this case, that Rancher Swarm CLI really is lacking as a drop in replacement for the guys at my company. I will wait, or experiment with rolling my own cluster. 

And yes, I saw that #4145 was still open...

**Comment by bradjones1** [comment]
@todd-alexion You can always SSH to the node the manager is running on, and exec in. But yes, it's not particularly straightforward, and 1.12 will make a lot of these issues less pressing.

**Comment by deniseschannon** [comment]
@pascalandy Please re-open if you have further questions.

@bradjones1 @todd-alexion Yes, we plan on supporting what's in 1.12 when it's officially released.
