### ISSUE TITLE
Improve cluster|project list-member subcommands

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#47692]
There are several improvements that can be made:
1. Rename USER column to MEMBER. It can be misleading as member can be a group.
2. Use the same logic as UI to resolve and display members - use /v3/principal endpoint to resolve member principals
3. Use the same output for members as in the UI `Name (Provider PrincipalType)`
4. If a principal can't be resolved parse the principal ID and produce the same output as in n.3 using principal ID as name
5. Add support for `--quiet` and `--format` flags

**Comment by samjustus** [comment]
https://jira.suse.com/browse/SURE-9087

**Comment by pmatseykanets** [comment]
## Validation Template

## What was fixed, or what change has occurred

Improvements to `cluster list-members` and `project list-members` commands.

## Areas or cases that should be tested

- The `USER` column should now read `MEMBER`
- The members output should be similar to the UI (Add cluster|project members) in the form of `Name (Provider PrincipalType)`
- Unlike the UI, if the member's principal can't be resolved, the output should still be in the above-mentioned format but the Name where name takes the form of the pricipal ID. This can be tested by enabling an auth provider, have an external user assigned as a member, and using the **local** user's token to login/authenticate with the CLI.
- Both `--quiet` and `--format` flags are now supported.

## What areas could experience regressions

N/A.

## Are the repro steps accurate/minimal?

N/A.

**Comment by Priyashetty17** [comment]
Validated all scenarios documented in the test plan with CLI`v2.11.0-rc.3`
- Validate Column Name Change from USER to MEMBER
- Validate Local Users Display
- Validate External Auth Provider Users Display
- Validate Group Display in Members List
- Validate unresolved principal displays principal ID instead of name - User
- Validate unresolved principal displays principal ID instead of name - Group
- Validate --quiet flag functionality
- Validate --format flag functionality - json
-  Validate --format flag functionality - yaml
-  Validate --format flag functionality - custom
