### ISSUE TITLE
Adding containers when there are no suitable targets available result in containerpocalypse of ever expanding proportions

### ISSUE THREAD

**Issue by xyntrix** [rancher/rancher#4771]
**Rancher Version:**
1.0.1

**Docker Version:**
docker-1.8.2-10.el7.centos.x86_64
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.2.1511 (Core), KVM

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
single node, external mysql db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce: **
using container_ne fill up all infrastructure hosts with a service and then attempt to add n+10 more

**Results:** 
service attempts to spin up nodes.. forever.   we have 10 infra hosts and 10 services deployed.. adding 10 more resulted in varying snapshot counts of extreme hillarity.   

include: 92 containers, most of which were in error or spinning up state
**Expected:**

10 + 10 (20 total containers, with 10 in failed and possible re-trying states)

**Comment by deniseschannon** [comment]
By design, we will try forever to spin up new containers for the service. We will back off how many the frequency of attempts as time goes on, but we will still continue to try to reach your desired scale (in this case it's 20 containers).

The error state containers should eventually be purged in Rancher. 

Your use case fails as you have a hard anti-affinity rule on the service, which means that if you only have 10 hosts but want 20 containers, you will never succeed. One option is to use a soft anti-affinity rule so that the spread of 10 of the containers would be on the 10 hosts before starting containers on a host that already has a container of the service.

**Comment by xyntrix** [comment]
Yep. Totally get the soft anti-affinity -- the problem is that rancher either as a cosmetic bug or race condition spins up far more containers, even if in a dead/dying/reap state, than I submitted for creation.  That seems like a bug to me.

**Comment by deniseschannon** [comment]
We continue to spin up containers because we are still trying to achieve your requested scale of n+10 containers. We will continue to try indefinitely until you either add more hosts or you update the scale to a number that can be satisfied. 

In the error state containers, it should provide the exact reason why they were errored out to help troubleshoot what is the issue if your original intention was to have n+10 containers. 

The concept isn't how many you want to be created, but more like how many containers do you want running.
