### ISSUE TITLE
Rancher has no native or intuitive recovery of services on down nodes which expose no TCP listeners

### ISSUE THREAD

**Issue by xyntrix** [rancher/rancher#4772]
**Rancher Version:**
1.0.1

**Docker Version:**
docker-1.8.2-10.el7.centos.x86_64

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.2.1511 (Core), KVM

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
single node, external mysql db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

*_Steps to Reproduce: *_
- run a docker container without an exposed tcp service
- turn the parent host for the container off

**Results:** 
- no failover is performed
- no indication that the services are unreachable happens
- one must engage in a circus of external activities in order to wrap health state around this

**Expected:**
- rancher should be able to tell that the parent node has gone missing and therefore the containers are in an unknown and potentially down state
- some form of heartbeat or state-parity should identify this degraded state and allow a compose option for failing over or recovery
- perhaps even a default netcat listening agent using the backend network as a "ping" might be able to assess and then respond to a "gone missing" state

**Comment by deniseschannon** [comment]
When you turn the parent host off, what does that mean? Are you turning it off from outside the UI (my assumption is that you are). In the UI under Infrastructure->Hosts, the host should show up as "Reconnecting" state. 

If the host state is in Inactive or Reconnecting state, there is no automatic failover unless you add a [health check](http://docs.rancher.com/rancher/latest/en/rancher-services/health-checks/). With a health check on the service, the container will be marked unhealthy and automatically spun up on another host. 

Rancher does know that the host has gone missing (hence the Reconnecting state), but Rancher will not re-schedule containers unless the health check. Since the host might start up again and re-connect to Rancher, the containers will still be running and be part of Rancher. 

When the container (service with health check) is marked unhealthy, it will show that the service and stack is unhealthy.

**Comment by vincent99** [comment]
@deniseschannon He knows all that, but you can only (directly) add a healthcheck for services that have a TCP or HTTP port open to check.  

So this is an enhancement request to be able to healthcheck things that have no listening ports, with something like [k8s execaction](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_execaction).

Or simpler, to just consider the service unhealthy if the host goes to reconnecting, since you can't do remote checks of a thing that's only local.

**Comment by phouverneyuff** [comment]
Any new idea how to resolve this problem?

Maybe we can allow to run command that need return true or false: `ps aux | grep process_name | awk ...`. If true, the process is health, else, restart container

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
