### ISSUE TITLE
[Question] Work around for Network Agent failed

### ISSUE THREAD

**Issue by phucvinh52** [rancher/rancher#4774]
Hello rancher team,
Looking ahead I can run rancher on the production environment.
I realized that if Network Agent is failed for any reason, the whole system will not work.
So I want to ask  your team that do you have a way to network and dns still works during time to repair?
Thank you, Sorry i'm bad english :D.

**Comment by vincent99** [comment]
"Agent" normally  refers to the container that runs on each host and performs actions that the controlling `rancher/server` container(s) tell it to do, but it sounds like you mean the server here.

DNS and networking both run on each individual host and continue to work if the master is gone.  Your containers continue to run normally.  The main thing that doesn't happen is reacting to any health checks that fail, as nobody is around to tell another host to start up a replacement until the server comes back.

High availability with multiple servers on multiple physical machines is also available starting on 1.0.1, but it is more involved to setup.  But for some use cases one container and a remote database is "good enough" because existing stuff keeps working.

**Comment by phucvinh52** [comment]
I mean when network agent failed on one host, then the host's tunnel will not connect to the rest of system, so the container on that host can't communicate with other container on other host. 
Is there any workaround on that situation?  How can i set up a manual the host's tunnel to containers can work normally?

**Comment by deniseschannon** [comment]
No, there's no workaround in this situation. You will need to restart the Network agent or delete the failed one and do something to trigger networking on the host so that a new network agent is created (e.g. add another container).  The network agent should automatically be restarted any time there is  any networking changes on that host so.

**Comment by deniseschannon** [comment]
@phucvinh52 Let me know if you have further questions.
