### ISSUE TITLE
Hostname override for agent hostname

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#4794]
The label `io.rancher.container.hostname_override` currently supports the `container_name` to set the hostname based on the service name.

I would like to propose to also support a `agent_hostname` option, that would set the container hostname to that of the host it is running on (as if using `-net host`) but still being on a managed network stack.

Unless there is another way of accomplishing this, that I've failed to find.

**Comment by lenzenmi** [comment]
+1

# Example use case

Collecting stats with telegraf and influxdb. 

It's natural to specify `always run one instance of this container on every host` and every host will automatically start reporting statistics. It would be nice if the hostname of the container matched the hostname of the host for looking at those statistics.

**Comment by ekristen** [comment]
+1 for this feature

**Comment by ferhimedamine** [comment]
+1 for this feature

**Comment by mkue** [comment]
+1 for this feature

**Comment by vincent99** [comment]
Do you guys just want `--uts=host` (https://docs.docker.com/engine/reference/run/#uts-settings-uts)?  If so it's not in the UI until 2.0, but has existed in the API/compose for probably a year...

**Comment by mkue** [comment]
Perfect, that was exactly what I was looking for. Thanks a lot!

I was able to set the uts option by updating the launchConfig through the API. Now the hostname of my node-exporter containers are the same as the hostname of the hosts and I can identify them in Grafana.

**Comment by jjscarafia** [comment]
Hi @mkue ! Can you please help me on how have you achieve to config this? Sorry but I don't know how to "set the uts option by updating the launchConfig through the API".
Thanks!

**Comment by mkue** [comment]
Hi @jjscarafia, sorry for my late response. I think you should be able to update the uts setting by sending a HTTP PUT request to the API.
In the Rancher UI you can click "View in API" on any container, and from there you can click "Edit" in the top right corner to send an HTTP request to the API.

I don't know if the launchConfig option is still there, I can't find it anymore. I remember that I tried setting this option the way I just described it. I didn't need it in the end, that's why I don't remember exactly how I did it...

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
