### ISSUE TITLE
[Backport 2.9] Implement automatic upgrades of rancher-wins alongside Rancher

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#48008]
Backport https://github.com/rancher/rancher/issues/47652

**Comment by snasovich** [comment]
@HarrisonWAffel , do we want this backported as far as v2.9.x ?

**Comment by HarrisonWAffel** [comment]
@snasovich, this isn't strictly needed for 2.9. I would be in favor of not back porting this to 2.9 since it would be a change in behavior for existing nodes within a minor release. Last we discussed this was an acceptable change for a 2.10 minor version, primarily due planner changes in that release line relying the latest versions of wins. The only caveat to this decision would be that we will need a `release-v0.4.x` branch for wins for >= 2.9, since right now both 2.9 and 2.10 just use `main`.

**Comment by snasovich** [comment]
Thank you, @HarrisonWAffel . Closing this issue as "not planned" per the above.
