### ISSUE TITLE
failed pull images from private registry

### ISSUE THREAD

**Issue by CloudWarGit** [rancher/rancher#4804]
**Rancher Version: 1.0.1

**Docker Version: 1.11

**OS and where are the hosts located? (cloud, bare metal, etc): centos7, baremetal

**Setup Details: (single node vs. single node, internal DB vs. external DB)**

**Environment Type: Cattle

**Steps to Reproduce:
1. Add a private registry in rancher-ui with credential
2. Create a new stack by docker-compose.yml file, which like following:
   
   ```
   web:
     image: 172.17.11.3/test/nginx
     links:
       - db:mysql
     ports:
       - 80:80
   
   db:
     image: 172.17.11.3/test/mysql
     environment:
       MYSQL_ROOT_PASSWORD: example
   ```

**Results:
   Failed pull from private registry with the failed logs:
   `Waiting for [service:1s203]. Service status: Waiting for [instance:ADE_db_1]. Instance status: Image [172.17.11.3/test/mysql:latest] failed to pull: Error: image test/mysql not found`

   But i can pull the from docker client which is one rancher host:

```
[root@docker03 ~]# docker pull 172.17.11.3/test/mysql:latest
latest: Pulling from test/mysql

a3ed95caeb02: Pull complete 
a3ed95caeb02: Already exists 
4947334f0ac4: Pull complete 
22c2951636da: Pull complete 
245adaddf1f1: Pull complete 
8ce55f2d3bd4: Pull complete 
fbaa25eccba5: Pull complete 
c5cfbbd45a7b: Pull complete 
3d47c8754663: Pull complete 
856b11b289dd: Pull complete 
Digest: sha256:b04342753ccd7ee358ef362b43c721e9e8fa03180aa0eabc75989d28c19fef86
Status: Downloaded newer image for 172.17.11.3/test/mysql:latest
```

**Expected:
    The images should be pulled from private registry

**Comment by sshipway** [comment]
I guess the Rancher way of doing it is to not specify the registry when defining the stack, but have it defined for the Environment?

This is actually good for us, because it allows the Environment Owner to restrict which registries can be used (and predefine the credentials).  So, in our Production Environment, only the approved registry can be used for download, even if some developer thinks they can get around this by specifying the registry in the image name (as above).

If Rancher were to be changed to allow this, then maybe it should be enabled/disabled on a per-Environment basis in the Registry definition (IE, add a checkbox for "allow specifying registry in Image name")?

**Comment by CloudWarGit** [comment]
Thanks @sshipway 

If i don't specify the registry in docker-compose.yml, rancher will download the image from docker.io, even though i have defined the registry for Environment.

**Comment by sshipway** [comment]
I don't know how Rancher manages it internally, but maybe when you have multiple registries defined for an Environment, they are in order of preference?  This might allow you to take one instance over another.  However, surely it would not be considered best practice to have identically-named images being different?  IE, reg1/ns/foo:bar should always be the same as reg2/ns/foo:bar if you use specific versions rather than :latest.

I can see the utility of being able to specify the registry as part of the image name when creating a new Service; however for the sake of security I'd also want to be able to prevent this in our Production Environment so as to prevent people from starting unapproved container images.

**Comment by will-chan** [comment]
@sangeethah do we really have issues with private registries?

**Comment by soumyalj** [comment]
@CloudWarGit : Works for me when using quay registry. Stack is created successfully. Can you please try on your setup ?
```
test1:
  restart: always
  tty: true
  image: quay.io/abc/test1
  stdin_open: true
  labels:
    test1: value1
```

**Comment by deniseschannon** [comment]
@CloudWarGit If you're still having issues with pulling images with private registries, please re-open.
