### ISSUE TITLE
[Backport 2.9] [BUG] `legacy-rolebinding-ownerref-cleaner` handlers fire millions of times per hour

### ISSUE THREAD

**Issue by moio** [rancher/rancher#48087]
Backport https://github.com/rancher/rancher/issues/42846

**Comment by git-ival** [comment]
From my searches, there are currently no 2.9 images with this patch applied. Testing with 2.9.2 and v2.9-head confirms that even the latest `v2.9-head` image does not include this change yet.

Moving to backlog for now

**Comment by moio** [comment]
v2.9.5-alpha1 has it

```
rancher % git describe --contains 4833a01
v2.9.5-alpha1~30
```

(read: 4833a01 is 30 commits prior to v2.9.5-alpha1)

You can get it as stgregistry.suse.com:/rancher/rancher:v2.9.5-alpha1

**Comment by git-ival** [comment]
Test passed! Confirmed expected behavior pre-patch and confirmed the `legacy-rolebinding-ownerref-cleaner` controller was removed post-patch.

Pre-patch (2.9.2):
![lasso-controllers](https://github.com/user-attachments/assets/958711dd-7085-42e9-b78b-297618e32918)
![rancher-cluster-perf](https://github.com/user-attachments/assets/8de30ab1-f229-4a6a-be58-85878400c57f)


Post-patch (2.9.5-alpha1):
![lasso-controllers](https://github.com/user-attachments/assets/617c7be0-3b56-4160-a0d8-d546afdd84cb)
![rancher-cluster-perf](https://github.com/user-attachments/assets/4f8c9a07-adb8-4eb3-86d3-00bbac1f0be3)
