### ISSUE TITLE
[Backport 2.10] [BUG] `legacy-rolebinding-ownerref-cleaner` handlers fire millions of times per hour

### ISSUE THREAD

**Issue by moio** [rancher/rancher#48085]
Backport https://github.com/rancher/rancher/issues/42846

**Comment by git-ival** [comment]
Test passed! Confirmed expected behavior pre-patch and confirmed the `legacy-rolebinding-ownerref-cleaner` controller was removed post-patch.

Pre-patch (v2.10.0):
![rancher-cluster-perf](https://github.com/user-attachments/assets/32c8d364-96cb-4bbd-9da6-5c3b96d677f3)
![lasso-controllers](https://github.com/user-attachments/assets/c127e41e-5583-4674-b892-353fb4673760)

Post-patch (`v2.10-ca82c9717ceb8ad2d0cc54f584d8adbae41a2341-head` image):
![rancher-cluster-perf](https://github.com/user-attachments/assets/e705b0b4-e4dd-48ae-965b-2e06a6fa5894)
![lasso-controllers](https://github.com/user-attachments/assets/b7b39ecc-49ec-4a21-8206-3eca6d5c6559)
