### ISSUE TITLE
UX / AWS: bad defaults when launching hosts

### ISSUE THREAD

**Issue by luispabon** [rancher/rancher#4841]
**Rancher Version:**
1.1.0-dev

See https://github.com/rancher/os/issues/935

The server defaults to Ubuntu 15.10 when creating new hosts. It should default to Rancher OS, obviously.

On AWS, the UI should pre-select the latest AMI for RancherOS available on the VPC selected beforehand. Also, the ssh username should be defaulted to rancher.

**Comment by deniseschannon** [comment]
As mentioned in the OS issue, we wouldn't want to put a RancherOS AMI ID as we are always adding newer versions of RancherOS and the UI would quickly be outdated and pointing to an old version of RancherOS. We do add a link to the RancherOS AMIs under the AMI field and at the link it mentions that you need to be using the rancher user. 

Since we're just calling docker-machine, if you don't add an AMI, it uses the default AMI that docker-machine is pointed to.
