### ISSUE TITLE
Allow user to select which hosts to deploy ingress controllers load balancers in k8s

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#4849]
Users who are deploying load balancer or ingress controllers should be able to control which nodes the services land on.

Environment type:
k8s

**Comment by alena1108** [comment]
@wlan0 we have to do it for 1.4. To support that, we have to: 

1) Allow user to define Rancher scheduling labels on k8s ingress resource (via annotations, the way we do set other custom parameters like scale)
2) Put a fix to ingress controller to place these labels on the corresponding rancher load balancer on its create call.

**Comment by wlan0** [comment]
This feature has been added since v1.4.0-rancher release of kubernetes

Ensure that you have more than one host added to rancher, label the hosts in rancher with names like

```
host=host1
host=host2
...

Steps to test:

1. create the reference RC and Service shown below.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
```

2. Using this reference ingress definition, create the ingress controller:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    config: "defaults\n balance source\nglobal\nmaxconnrate 60"
    io.rancher.scheduler.affinity.host_label: "host=host1"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

Note the annotation in the ingress config yaml. This will create the lb service on the host with label host=host1. Check that the lb-service container gets launched on this particular host by checking the host view in rancher UI.
```

**Comment by soumyalj** [comment]
Tested on rancher v1.4.0-rc2 with k8s v1.5.2-rancher1. Ingress Lb can be deployed on a desired host using ```io.rancher.scheduler.affinity.host_label``` annotation as mentioned in the example above. 
The ingress got deployed on the host with the label specified. Also, the ingress was edited specify a different host label. The ingress launched correctly on the new host as expected
