### ISSUE TITLE
Disabling local authentication should make accounts inactive

### ISSUE THREAD

**Issue by wangweihong** [rancher/rancher#4866]
**Rancher Version:**
v1.0.1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos 7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Enable Local Authentication,and  add some accounts
2. Disable Local Authentication.
3. From Admins >> Account page , you can  see some accounts added before still be Active state

**Comment by deniseschannon** [comment]
When access control is disabled, the accounts will not be removed or made inactive. But if you re-enabled local auth, the accounts would still be active as it's stored in our DB> 

Since access control is no longer on, it wouldn't affect usability of Rancher.

I will change this request to an enhancement to deactivate the accounts made when you disable local auth. Though I think there is an argument that some people would not want to go through the process or re-activating all the accounts just because you flip flopped between enabling local auth and disabling local auth.

**Comment by deniseschannon** [comment]
Actually, I spoke with the engineering team and this is by design. We will never automatically disable anything for a user. If you want to make these accounts inactive, you'll need to do so yourself.
