### ISSUE TITLE
[Feature Request] Add automatically executed runtime commands to service definition

### ISSUE THREAD

**Issue by RikuXan** [rancher/rancher#4880]
I often have the situation that I want to use official images for my services (e.g. php:version-fpm for my PHP applications), due to them being very stable and the nice choice of different versions. However, I often find that I have to slightly alter those images after deploying them, for example because the lack certain modules in their base configuration that I need (e.g. the official PHP image does not include LDAP support), or because I have to insert a CA certificate into the certificate store.

I am aware that I could create my own docker image and simply add the tools/modules necessary, but I would have to rebuild the image for every new version of the official image and managing this can be somewhat cumbersome for a multitude of images and to be honest, it just feels better to me to use the official image itself, rather than deriving my own from it.

Do you think adding the possibility to let rancher automatically execute commands (probably via docker exec), supplied in the service definition, after the deployment of a service container would be a good idea? Also, would you think this is something that should handled by Rancher or rather by Docker/Compose?

**Comment by deniseschannon** [comment]
What about using the command field for when you run the docker containers? Rancher also supports that functionality

https://docs.docker.com/engine/reference/run/#cmd-default-command-or-options

**Comment by vincent99** [comment]
Creating an image that derives from the base image is definitely the Docker Way™ of doing this sort of thing, particularly because it creates a container with a known and consistent configuration.  If your script is downloading and installing modules and such two separate instances of that container are now no longer necessarily the same.  So I don't think is something we'd want to add as a feature.

There are some ways to do it though...

Just using the `command` won't work (for most images) because the image's `entrypoint` won't be expecting or executing random commands passed in.  But you can override the `entrypoint` to do something like run a script that is bind-mounted in, which can then execute whatever commands you want and call the default entrypoint when it's done.

Or it's possible to use the `exec` action on a container to execute arbitrary commands, though you'd have to know when to call it (either manually or by watching the API/metadata for new containers).

**Comment by RikuXan** [comment]
The mounted entrypoint script is a very nice idea, would you possibly also have an idea on how to get the "real" entrypoint of the script from bash? I did check for an environment variable, but there is none. I would like to generalize the entrypoint call at the end of my initialization script, so that if it changes, there are no changes necessary to my script (but this is just a convenience thing, not too bad if there's no way).

**Comment by deniseschannon** [comment]
@RikuXan Please re-open if you have further questions.

**Comment by vincent99** [comment]
There is not any generic way to get the overridden entrypoint that I'm aware of.
