### ISSUE TITLE
Rancher Compose overwriting env variables when it doesn't have env vars

### ISSUE THREAD

**Issue by pragmaticivan** [rancher/rancher#4891]
**Rancher Version:**
v1.1.0-dev2-rc4
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
When I use rancher-compose and my docker-compose.yml doesn't have any env vars specified, it's upgrading my service but the env vars that I settled up there are gone. 
**Expected:**
I just wanted to update the Image, not the env vars. As a Fix I'm currently adding a `.env` file with the vars in my CI tool, but wondering if there's a way to never do that and just pull the new image for the upgrade.

I would like to be able to upgrade a service without replacing env vars that I already introduced on Rancher.

**Comment by deniseschannon** [comment]
When upgrading with rancher-compose, a new container is generated based on the service definition in the docker-compose.yml. 

So if you no longer have environment variables in your docker-compose.yml, then the new container will be started without them. This is expected behavior of how rancher-compose upgrades services.

The solution of using the an `--env-file` with your rancher-compose commands would be the correct way to handle what you are trying to do.

**Comment by pragmaticivan** [comment]
@deniseschannon I just want to pull the image, is there a way for that currently?

**Comment by deniseschannon** [comment]
`rancher-compose pull`  will pull the image to all hosts in your setup.

You can also include this label, so that whenever a new container is created, a new image will be pulled before attempting to launch the new container. 
```
labels:
  io.rancher.container.pull_image: always
```
