### ISSUE TITLE
Rancher catalog service is not available for ~40 seconds in no internet mode

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4903]
Steps to reproduce:

1) Pre-pull rancher/server:latest image
2) Turn off wifi
3) Deploy Rancher ```docker run -d --restart=always -p 8080:8080 rancher/server```
4) Access catalog tab in the UI immediately. It fails. Retry after ~40 seconds, it starts working. From the logs I am seeing the following:

```
time="2016-05-24T22:20:29Z" level=info msg="Using catalog community=https://github.com/rancher/community-catalog.git"
...20 sec
time="2016-05-24T22:20:49Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/rancher-catalog.git, error: exit status 1"
time="2016-05-24T22:20:49Z" level=error msg="Git pull for Catalog library failing with error: exit status 1 "
... another 20 secs
time="2016-05-24T22:21:09Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/community-catalog.git, error: exit status 1"
time="2016-05-24T22:21:09Z" level=error msg="Git pull for Catalog community failing with error: exit status 1 "
```

20 seconds after startup if tries to pull "Catalog library" and fails, then after 20 seconds it tries to pull "Catalog community" and fails. Only after the last failure it pulls the data from cache, and UI can access catalog service. Wonder there is some timeout on library pull, and while the call is going, service is not accessible.

**Comment by mrajashree** [comment]
Unable to reproduce this running the following command in an ubuntu VM: `docker run -d --restart=always -p 8080:8080 rancher/server:v1.2.0-pre4-rc3`. This delay seems to be there in `docker for Mac`, but not related to the catalog-service code

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.2.0-pre4-rc4
In the rancher-server setup, I have blocked access to github by adding the following iptables rules:

```
iptables -I FORWARD -d <gihub ipaddress>-j DROP
``` 


Following are the issues I am seeing:

1.  After fresh install , access catalog from UI gives me the following error:

<img width="1669" alt="screen shot 2016-10-19 at 4 34 00 pm" src="https://cloud.githubusercontent.com/assets/4266958/19542367/720aa8e4-9622-11e6-889e-c50e8b0d32af.png">

After about 5mts  -6 mts , I see the catalog being presented successfully to the user.

In my case , github access takes ~2 mts to report failure. And seems like we show "503 Error" until all the 3 catalogs infra/community/library have timed out (sequentially).

```
time="2016-10-19T23:47:41Z" level=info msg="Starting Rancher Catalog service" 

time="2016-10-19T23:47:41Z" level=info msg="Using catalog infra=https://github.com/rancher/infra-catalog.git" 

time="2016-10-19T23:47:41Z" level=info msg="Using catalog community=https://github.com/rancher/community-catalog.git" 

time="2016-10-19T23:47:41Z" level=info msg="Using catalog library=https://github.com/rancher/rancher-catalog.git” 

….

time="2016-10-19T23:49:48Z" level=error msg="Git pull for Catalog infra failing with error: exit status 1 “ 

time="2016-10-19T23:51:56Z" level=error msg="Git pull for Catalog community failing with error: exit status 1 “ 
time="2016-10-19T23:54:03Z" level=error msg="Git pull for Catalog library failing with error: exit status 1 “ 
```

2. The very first template from any catalog I try to view from UI takes about 2 mts to load. 
After this , every other template in this catalog will load immediately.

3. Disable and Enable the catalog. Once the catalog is enabled , user shown message "There are no compatible templates" presented to the user for a very long time like 2 mts (seems like this is the time taken to wait for the gihub access to timeout). Every catalog takes additional 2 mts to be shown. When i have 3 catalogs to start with , the last of the catalog takes 6 mts to load since we are doing the catalog fetch sequentially.

**Comment by sangeethah** [comment]
Tested with rancher-server version -- v1.2.0-pre4-rc5

All the timing issues tracked in the previous comments work as expected after fresh install and after enabling/disabling all catalogs.

There is still issue with very first template to view any template from any catalog takes a very long time to load which is tracked in https://github.com/rancher/rancher/issues/6388
