### ISSUE TITLE
UI update: make it easier to get download link for rancher-compose

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#4906]
There appears to be a JS menu on the bottom right "Download CLI" to download rancher-compose.  I would like to download rancher-compose programatically but its a pain to determine the url since I cannot simply right click "Copy URL" because the options "Windows", "Linux", "Mac OS X" are not links.

**Comment by DenverJ** [comment]
I found you can use the API to work out what version of rancher-compose you need then craft the download URL yourself. The URL is /v1/activesettings/cattle.rancher.compose.version

**Comment by vincent99** [comment]
@DenverJ If you're going to do that you can just get the actual URL from settings... `/v2-beta/settings/rancher.compose.darwin.url` (or `linux`, etc).

These were originally intentionally not links because they required an API call to go get the URL and are not needed on pageload 99% of the time, but as it turns out we now have it anyway so they can just be regular links now.

**Comment by tfiduccia** [comment]
Version - master 1/24
Verified fixed
