### ISSUE TITLE
openLDAP access control "test and enable" user with ":" in password produce a "Forbidden" error

### ISSUE THREAD

**Issue by dabelenda** [rancher/rancher#4923]
**Rancher Version:** 1.0.1

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** RHEL7 bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
 Setup a user with ":" in its password.
 Fill all the fields of the Access Control.
 Use the user's credentials to "test and enable" the Access Control.

**Results:** Shows "Forbidden" in the response field

**Expected:** Should authenticate and enable the access control.

**Comment by dabelenda** [comment]
I traced the error to https://github.com/rancher/cattle/blob/7dba794cfa34a6e592340fe0fc08684b3fa6a74d/code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/OpenLDAP/OpenLDAPTokenCreator.java#L56-L59

Apparently you use a single HTTP Header to contain both username and password, and ":" to split it, however, if the password contains a ":" it splits to more than 2 fields, and thus returns forbidden.

**Comment by marsmensch** [comment]
Did hit that issue as well in an OpenLDAP enterprise environment. 

**Rancher Version:** 1.1.0-dev3
**Docker Version:** 1.11.1
**OS and where are the hosts located?** RHEL7.2 VMs
**Setup Details:** Single node rancher, internal DB
**Environment Type:** Cattle

**Comment by LLParse** [comment]
A simple solution would be to base64 the username and password in the request body.

**Comment by prachidamle** [comment]
Yeah we can base64 the username/password and then use a ':' to separate
@vincent99 The "code" parameter sent in /token API contains the user credentials separated by ':' 
please comment, this will need both UI and API fix.

**Comment by vincent99** [comment]
Why do we need to support a colon in the username?  HTTP Basic auth (RFC 2617) doesn't.  So just split on the first colon and any additional ones are part of the password.

**Comment by LLParse** [comment]
Irrespective of Basic auth (not sure how that has anything to do with LDAP auth), a colon in a username would violate [RFC 2798](https://tools.ietf.org/html/rfc2798).

But then Rancher supports fancy mappings to custom object classes, so some horribly misguided organization that has allowed the username `::smug::` would have to modify their directory in order to get auth working.

**Comment by marsmensch** [comment]
Where and why did we start to talk about colons in usernames? The original reporter and me were referring to the **password** only.

**Comment by vincent99** [comment]
@marsmensch it's an obviously related problem, and we're not going to fix  one without even considering the other.. If *both* username and password can have colons then no amount of splitting is going to tell you which one separates there 2 fields.. However I agree that the username isn't important right now.

@llparse it's relevant because that's why the string is "user:pass" in the first place, and base64 encoding is guaranteed to be confused with it, but not work because the colon has to be not encoded.

@prachedamle Just change the parsing to split on the first colon and use the rest as the password.

Anything more than that is a breaking API change that needs to be backwards compatible,  documented, deprecated, etc.  If someone has a good reason for colon in a username later the, API should be 2 separate fields.

**Comment by tfiduccia** [comment]
Version - master 8/25
Verified fixed
