### ISSUE TITLE
[UI] Load balancer custom configuration should not be removed

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#4930]
**Rancher Version:** v1.1.0-dev1

**Docker Version:** n/a

**OS and where are the hosts located? (cloud, bare metal, etc):** n/a

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle.

**Steps to Reproduce:**

1. Add a load balancer, and configure it to your liking with advanced host configuration.
2. Remove the underlying containers that were linked to one of the advanced host configuration targets.

**Results:** 

Your load balancer configuration is now lost.

**Expected:**

I'd prefer to display a "degraded" or "invalid" state for the load balancer instead of losing the custom configuration.

**Comment by deniseschannon** [comment]
This is by design. As soon as a target is removed, the load balancer/haproxy config is automatically updated so that requests will not be directed to the removed target. 

In order to satisfy what you are looking for, we'd need to keep a separate copy of what the UI should look like for the load balancer service, what the actual load balancer service is doing and make sure that the haproxy config is matching what the actual load balancer is (at that time) versus what you want to fix.
