### ISSUE TITLE
Strange LB behaviour

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#5012]
I've created two stacks a41 and s35:
![image](https://cloud.githubusercontent.com/assets/1079535/15804941/e959e27c-2b3b-11e6-92aa-241c335137f0.png)

Both of it has mongodb service with ports exposed via balancer:
balancer:60000->a41.mongo:27017
balancer:60001->s35.mongo:27017
So it shuold be possible to acces to these services via 60000 and 60001 external ports:
![image](https://cloud.githubusercontent.com/assets/1079535/15804955/6d0cc936-2b3c-11e6-8a1c-53c7e62ca6cc.png)

But I experienced periodical errors during connection (via Robomongo for example) to services with:
```
E QUERY    [thread1] Error: network error while attempting to run command 'isMaster' on host...
```
If I remove one stack - connection works fine and stable. So I cheked up haproxy.cfg on balancer and there is strange mappings found (for port 60000(a41 stack) on screenshot. For 60001 same problem):
![image](https://cloud.githubusercontent.com/assets/1079535/15805045/06c9c91e-2b3f-11e6-8b4b-334e7bfccff0.png)

If I remove strings which belongs to s35 stack in port 60000 section, problem disappears for this port. Is this strings really needed or it is bug? As for me - it is bug :)

Here is a full [haproxy.cfg](http://pastebin.com/0V6cs7su)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.2` Cattle: `v0.159.8` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environments.index`|

**Comment by EugenMayer** [comment]
this is 100% related to https://github.com/rancher/rancher/issues/4310 - the same issue. We should really  try to make the rancher devs notice this issue, since this is like a complete takedown.

**Comment by EugenMayer** [comment]
Since nobody commented here but people explained me what happened in the IRC, i though i share this with you :)

The issue are TCP based frontends, they actually do not support hostname based routing at all, that leads to the issue that for "all available services" all TCP ports are routed in the backend. 

This was identified as a UI bug at leat ( tell the user, thats not possible ) and probably a cattle bug/enhancement to probably support this in general. Maybe @ibuildthecloud can comment on this, he as kindly helping me out.

The current solution is creating a second lb for the TCP part - i tried that and it works out for know. Pitty is, that this will still not handle hostname routing. Seems like alternatives like traefik do not even include any TCP routing at all.

**Comment by clicman** [comment]
@EugenMayer thank you for comment. But for clerify, I'm not usinh host based tcp routing, but port based:
LB_IP:6000->STACK_1.service:<SOME_PORT>
LB_IP:6001->STACK_2.service:<SOME_PORT>

Is your solution will help im my situatio and is the issue in combining host and tcp:port routing on same LB?

**Comment by EugenMayer** [comment]
Yes, i think its an issue when you combin host based HTTP routing and any TCP routing, TCP ends up having all entries, maybe @ibuildthecloud can comment on this more detailed.

**Comment by vincent99** [comment]
To clarify since it doesn't seem to be clear, there is no such thing as "host based TCP routing".  A connection comes from the client's IP and port number to the server's IP and port.  The server has no idea what DNS entry, if any at all, the client resolved to decide to connect to the IP it's receiving a connection from.

This can be done in HTTP and some other layer 7 protocols because there is specific place in the request payload for the client to tell the server what name it wants (the `Host` header in HTTP).  But this is highly specific to each individual protocol and many have no way at all.

One interesting one that we would like to support (but don't today) is the SNI fields in a TLS connection.  It's essentially the same add the `Host` header value, but moved into the TLS handshake so that the server can decide what certificate to present.  That all happens before HTTP gets involved, so SNI can be used for any protocol (for which clients typically support sending it...).  Or HTTP host-based routing without doing the TLS termination at the balancer.

**Comment by clicman** [comment]
@vincent99 what about ip-based port forwarding? This issue initially about port forwarding for tcp connections, not for host based.

**Comment by vincent99** [comment]
If you have multiple listeners and targets the default is that a request for any listener goes to any backend.  The advanced rules can be used to restrict the set of targets down.   If you have a line for source port 60000 -> service 1, all requests for port 60000 will go to that specific service.  Request host and request path are meaningless for requests to a TCP listing port.

TBH I hate that we allow mixing multiple listeners and types of listeners into one balancer, it makes things very confusing and has little benefit (one set of balancer containers vs several).  it is much simpler if you choose a single protocol, a list of (usually one) listening ports and then a list of targets.. But people always want One Balancer To Rule Them All™

**Comment by clicman** [comment]
I confirm, separate http and tcp listeners in two separate balancers solved my problem.

**Comment by EugenMayer** [comment]
@vincent99 got you on this. I guess, we can consider this a "UI inconvinience" then.

@clicman ip based will work, since those are different frontends. At least they have to work, i did not try it

**Comment by deniseschannon** [comment]
Closing in favor of #4310
