### ISSUE TITLE
Editing a service name makes it impossible to schedule against the new service name

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5042]
**Rancher Version:** 1.1.0-dev3.

**Docker Version:** 1.10.3.

**OS and where are the hosts located? (cloud, bare metal, etc):** aws.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: cattle.

**Steps to Reproduce:**
1. Add two hosts, one with label "foo=1" and the other with "bar=1" for example.
2. Add a load balancer with the name "lb" to any stack and set a scheduling policy for hosts with label "foo=1".
3. Now, let's say you made a mistake in the last step and you actually wanted "bar=1". So, clone the load balancer and name it "lb-new".
4. Delete the old load balancer (named "lb").
5. Rename the new load balancer from "lb-new" to "lb".
6. Add another service "redis" (for example) and set a scheduling policy for a host that has a service with name "lb".

**Results:** 

The redis service will never start because it won't be able to find the service. This is because the load balancer's container is still named "stack_lb_new_1".

**Expected:**

In my opinion, I expected one of the following to happen:
1. Cloning a load balancer (or any other service) should also rename the underlying containers to match the new service name.
2. The `io.rancher.scheduler.affinity:container_label` scheduling policy should look up the current service name instead of relying of the container's name.
3. Allow us to change all of the settings of a load balancer without having to clone it (scheduling policies, stickiness, etc.)

**Comment by deniseschannon** [comment]
In the API, we support upgrade of load balancers, but it hasn't been exposed in the UI, which would solve  the exact issues that you are facing.  https://github.com/rancher/rancher/issues/3161

The scheduler actually schedules against the labels of the container, so I could see that there is an issue where if you rename a service, you would not be able to schedule against the new service name. We aren't able to change the labels on the container as docker container 

I'm going to edit this issue to address the scheduling issue.

Steps to Reproduce:
1. Create service called `foo`
2. Edit service to be called `foo1`
3. Try and schedule a new service against the service name `foo1`. 

Results: This will fail as the containers of `foo1` will still have the label `io.rancher.stack_service.name=<stackname>/foo` instead of the new label `io.rancher.stack_service.name=<stackName>/foo1`

**Comment by will-chan** [comment]
@deniseschannon has this been resolved with the upgrade LB feature?

**Comment by tfiduccia** [comment]
Version - master 1/7

This is actually not specific to load balancer or to the scheduler.  The main issue here is when the service name is renamed, that does not reflect in the already started container.  The label for the service is not changed so nothing can find it.  Probably shouldn't be able to edit the service name, it should be part of the upgrade so container can be restarted with proper name and service label.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Editing the name of Services and Containers has been removed.
