### ISSUE TITLE
Load balancer incorrectly routing after backend service restart

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#5087]
**Rancher Version:**
1.0.1

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 / EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
  1. Create services `Foo` and `Bar`, accepting HTTP traffic, with scale Global
      - I only tested this on a single host, so only a single container was created for either service! This may be a factor?
  2. Create load balancer `LB`, with HTTP routing: 
       - `/svc` -> `Foo`
       - `/svc/bar` -> `Bar`
  3. Start both services and LB
  4. Request `/svc`. Observe traffic arriving at `Foo`
  5. Request `/svc/bar`. Observe traffic arriving at `Bar`.
  6. Restart _container_ `bar_1` (not the service)
  7. Request `/svc/bar`. Observe traffic arriving at `Foo`.
  8. Restart the LB service. Routing resumes working as expected.

**Results:** 
After container for service `Bar` is restarted, LB routes traffic to the other service in its target list. Once the container for service `Bar` is back in service, LB does not attempt to reroute traffic correctly.

**Expected:**
LB should route traffic back to its target service after at least one container exists and passes healthcheck.

I suspect this is because each of the above services has an effective scale of 1, but not yet able to test  this. Still, the LB should route correctly regardless of scale.

**Comment by deniseschannon** [comment]
This sounds like an issue that has been fixed in v1.1.0-dev4. https://github.com/rancher/rancher/issues/4487

When we trigger any other config update to Lb service , by stopping other containers in the service / scaling up service , the container that was restarted gets reprogrammed in the haproxy.

This should be resolved in the most recent release.

Please re-open if you still face this issue in a release after v1.1.0-dev4
