### ISSUE TITLE
Graphs only work if you are on first tab in Host and Container View

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5108]
**Rancher Version:** master 3/16

**Steps to Reproduce:**
1.  Go to Host View or Container View
2.  Select Volume tab in container view or Port tab in host view

**Results:** Screen noticeably slow down and the graph stop showing data

**Expected:** show data

**Comment by vincent99** [comment]
Removed `jquery.initialize` by changing the way the hosts columns (on the regular Hosts view) are sized.  This has seemingly nothing to do with graphs but was causing a significant performance hit.

The graphs themselves were not displaying because the gradient they are rendered with depends on the URL of the page.  So they are still there, but invisible once the URL changes (regardless of which tab was initially loaded).

**Comment by deniseschannon** [comment]
Verified in v1.1.0-dev5-rc5 that the stats are being updated if on the volume or port tab in the detailed container view.
