### ISSUE TITLE
Connecting to Rancher Redis Cluster?

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#5133]
Since Rancher since 1.0.1 already creates it's own Redis cluster. Could I simply connect my application to this and avoid having to setup and manage a cluster instance myself?

**Comment by vincent99** [comment]
Nothing physically stops you, but this is a bad idea for a variety of reasons.  It's not a cluster, it's independent standalone instances.  We don't persist anything so there is no persistence configured, and the default won't go to a volume that will be saved across upgrades.  And it can be restarted, reconfigured, or removed whenever we feel like because it's an internal implementation detail, not a public service.

**Comment by deniseschannon** [comment]
@ronag If you have further questions, I'd suggest using the forums to ask them to get feedback from community members.
