### ISSUE TITLE
[external-dns] State of containers is not checked when adding/updating DNS records

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#5143]
Currently the external-dns services add DNS records for any containers that expose ports, regardless of their current state. As a result we may end up with A records pointing to stopped or unhealthy containers.
We need to check the state and health_state to make sure that the DNS zone has only A records for containers whose state is `starting`/`running` and whose health_state is `healthy`/`updating-healthy`.

**Comment by sangeethah** [comment]
Tested with rancher-server - v1.2.0-pre3 and rancher/external-dns:v0.5.0.
Container in "stopped" state and "unhealthy" containers are not programmed in the Route 53 zone anymore.

Scenario1:
Have a service with health check enabled (with ports) with "When Unhealthy Take No action" option.
Check that the hosts in which the service containers  are running is programmed in  DNS zone  as A records.
Make one of the containers unhealthy , so that it continues to be running state with health_state as "unhealthy".

We see the A record relating to this unhealthy container gets removed from DNS zone.

When the container becomes healthy, it gets added back.

Scenario2:
Have a service with exposed with port.
Deactivate the host in which the container is running.
Upgrade the service .

Before proceeding to "Finish Upgrade",  upgraded container instance will get deployed in a different host and the original container is in "stopped" state .

At this point , we see the A record relating to this stopped container gets removed from DNS zone and is associated with only the new upgraded container.
