### ISSUE TITLE
Sidekick doesn't act as a sidekick, but instead is load balanced between all sidekicks of same type

### ISSUE THREAD

**Issue by MarcusSjolin** [rancher/rancher#5150]
**Rancher Version:**
1.0

**Docker Version:**
1.9

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher host

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Set up a service with a sidekick
Spawn it to be two instances
Log on one of the instances and ping the sidekick a few times

**Results:** 
It will load balance between the two sidekicks

**Expected:**
It will connect to the sidekick attached to the service

**More info**
This surfaced after trying to spawn same services on cloud instances, which didn't have the correct port access set up. After then investigating a bit it seems to go to different IPs every time you ping a service, and connection was failing due to inaccessibility of the service.

Been referring to this documentation and I can't read that they are shared between all primary services
http://docs.rancher.com/rancher/v1.0/zh/rancher-compose/#sidekicks

**Comment by deniseschannon** [comment]
This is expected behavior of Rancher's internal DNS. The sidekick relationship is only to ensure that as you launch containers that depend on each other, they will be launched onto the same host. Outside of the launch configuration concept, there is nothing specific that indicates the sidekick service would only be available to the primary service.

For all of Rancher's internal DNS, if you are trying to ping a service, it will always go between all the containers in a service regardless if it is a sidekick or not.
