### ISSUE TITLE
Name is not sorting correctly in Add Environment for Auth

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5162]
**Rancher Version:** master 6/16

**Steps to Reproduce:**
1.  Authenticate (I was using Azure)
2.  Create environment
3.  Add a bunch of users and groups
4.  sort by Name

**Results:** Doesn't sort properly
![image](https://cloud.githubusercontent.com/assets/11514927/16135317/9a23d510-33d7-11e6-901a-1822f3f2d1e1.png)

**Expected:**  Sort properly

**Comment by vincent99** [comment]
They are sorted by externalId, because the displayed names are loaded asynchronously and not part of the actual environment definition..

**Comment by westlywright** [comment]
This is technically the same issue as rancher/rancher#7500 since they are using the same component. I removed sorting for both fields mentioned in that bug for now per Vince's advice. While we maybe be able to make some kind of workaround to get the sorting working properly I don't think it will be very performant. IMO I think we should add the name data to the call for fetching this so we dont have to make a bunch of extra calls to grab the names.

**Comment by deniseschannon** [comment]
No longer applicable for 2.0.
