### ISSUE TITLE
When I select unrestricted, clearing out restricted/required users

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5172]
**Rancher Version:** master 6/16

**Steps to Reproduce:**
1.  Authenticate using AD
2.  Set Site Access to Allow member of Environment or Restrict Access and add users.  Save
3.  Set back to unrestricted.  Save and refresh browser
4.  Select Restricted or required mode again

**Results:** No one is in the list.  You are clearing the list.

**Expected:** Don't clear the list.  This is actually really importing because we should always have the admin user added.  If admin add a user now and save without adding themselves, then they would be locked out and couldn't add anymore.

**Comment by prachidamle** [comment]
@vincent99 @tfiduccia admin user needs to be set in the list by default when "restricted"/"required" mode is being saved.  When UI starts adding the logged in admin by default, we dont need any server fix.

I need to clear out the list when "unrestricted" accessmode is sent, else in the following scenario there is no way to fix the config:

1. Go to AD Access Control
2. Log in using good credentials
3. Set Site Access to Restrict & add user (if one is not already there) and Save
4. Disable access control
5. Try to log in again but put in garbage for the Service Account Password 
[At this point UI sends accessmode="unrestricted" and now suppose server did not clear the list set in step3] 
[The /ldapconfig API will always first list the current config and then save the data from the new config sent - while listing the currentconfig it loads the details of the id's if any in "allowed" list, by connecting to ldap]
[When new config is saved, the garbage password has been saved to database when this call returned]

6. Now put in proper credentials for Service Account Password [You get an ldap error and there is no way to correct the admin password henceforth]

This happens because /ldapconfig again first lists the currentConfig in DB and loads details of the "allowed" list from ldap - it gets error doing this since the password is garbage that got saved in step5.

Hence if server clears the "allowed" list when "unrestricted" is accessMode is sent, then there will be no need to connect to ldap to load the details of any id's - thus avoiding this lock out situation.

**Comment by prachidamle** [comment]
We need a UI fix instead, to set admin user by default to the list when selecting "restricted"/"required" mode.

**Comment by tfiduccia** [comment]
Version - master 6/16
Verified fixed
