### ISSUE TITLE
'ERROR: https://SERVER_IP:8080/v1 is not accessible' error when trying to connect to server on same host in Fedora

### ISSUE THREAD

**Issue by sapslaj** [rancher/rancher#5216]
**Rancher Version:**
v1.1.0-dev5

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Fedora 24 Server in a VirtualBox VM with a bridged network adapter

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
In a stock Fedora 24 Server installation, run Rancher server with `sudo docker run -d --restart=always -p 8080:8080 rancher/server`, run the agent by running the command given in the UI (in my case, `sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 https://192.168.20.163:8080/v1/scripts/#{registration_token}`)

**Results:** 
Attaching to the container gives an output of this: 

```

INFO: Running Agent Registration Process, CATTLE_URL=https://192.168.20.163:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.3
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.6.2
INFO: docker version: Git commit (server): ee81b72/1.10.3
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 6
INFO: docker info: Images: 4
INFO: docker info: Storage Driver: devicemapper
INFO: docker info: Pool Name: docker-253:0-100672500-pool
INFO: docker info: Pool Blocksize: 65.54 kB
INFO: docker info: Base Device Size: 10.74 GB
INFO: docker info: Backing Filesystem: xfs
INFO: docker info: Data file: /dev/loop0
INFO: docker info: Metadata file: /dev/loop1
INFO: docker info: Data Space Used: 1.349 GB
INFO: docker info: Data Space Total: 107.4 GB
INFO: docker info: Data Space Available: 56.35 GB
INFO: docker info: Metadata Space Used: 2.552 MB
INFO: docker info: Metadata Space Total: 2.147 GB
INFO: docker info: Metadata Space Available: 2.145 GB
INFO: docker info: Udev Sync Supported: true
INFO: docker info: Deferred Removal Enabled: false
INFO: docker info: Deferred Deletion Enabled: false
INFO: docker info: Deferred Deleted Device Count: 0
INFO: docker info: Data loop file: /var/lib/docker/devicemapper/devicemapper/data
INFO: docker info: Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
INFO: docker info: Library Version: 1.02.122 (2016-04-09)
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 4.5.7-300.fc24.x86_64
INFO: docker info: Operating System: Fedora 24 (Server Edition)
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 3.859 GiB
INFO: docker info: Name: localhost.localdomain
INFO: docker info: ID: PGOM:U53M:2W45:I5U2:EEG6:NIGI:SMSS:LTAC:XE4G:7R27:ZKFQ:635H
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: https://192.168.20.163:8080/v1
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
ERROR: https://192.168.20.163:8080/v1 is not accessible
...
```

And so on until the container eventually exits.

When I enter a shell into the container, I can access 192.168.20.163 no problem: 

```
# sudo docker run -e CATTLE_AGENT_IP="192.168.20.163"  -it --privileged --entrypoint=/bin/sh rancher/agent:v1.0.2 
# curl -ik https://192.168.20.163:8080/v1 
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 22 Jun 2016 05:22:13 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a1
X-Api-Client-Ip: 172.17.0.1
X-Api-Schemas: https://192.168.20.163:8080/v1/schemas
Transfer-Encoding: chunked

{"id":"v1","type":"apiVersion","links":{"accounts":"https://192.168.20.163:8080/v1/accounts","addOutputsInputs":"https://192.168.20.163:8080/v1/addoutputsinputs","agents":"https://192.168.20.163:8080/v1/agents","amazonec2Configs":"https://192.168.20.163:8080/v1/...
```

Ultimately, as you could imagine, no host is added to the Rancher infrastructure.

**Expected:**
Host is added to the Rancher infrastructure.

**Comment by osallou** [comment]
same issue in CentOS 7 with stable release (with ldap config). URL reachable (externally and internally).

**Comment by janeczku** [comment]
HI @sapslaj, it looks like you are running Rancher behind a SSL-enabled reverse-proxy. This might be a problem with your certificate chain.
Please open a shell into the agent container and execute the curl command again, but without the `-k` switch, ie. `curl https://192.168.20.163:8080/v1`.

**Comment by leodotcloud** [comment]
@sapslaj: Can you try using http instead of https? I just tried on my end, I ran into the same problem and changing to http worked for me.

**Comment by aemneina** [comment]
@sapslaj or possibly https://<server_ip>/v1 without specifying port 8080

**Comment by sapslaj** [comment]
Hi, sorry for the late reply. A bunch of really horrible things happened to my computer so I was without that for a little while. 

Drama aside, I (maybe?) ran into a few major issues: https://github.com/docker/docker/issues/20865 and https://github.com/docker/docker/issues/16137. The Golang issue seemed to fix itself after a few updates (Noteworthy because I'm choosing to _not_ use the official docker repos.) The firewalld issue, on the other hand... 

Because reasons, firewalld seems to be necessary for Docker to work, because stopping it leads to iptables chain errors. But Docker is _terrible_ at interfacing with firewalld. So I manually created a firewalld service and it started working:

```
$ cat /usr/lib/firewalld/services/rancher.xml 
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Rancher</short>
  <description>Rancher is an open source project that provides a complete platform for operating Docker in production.</description>
  <port protocol="tcp" port="8080"/>
  <port protocol="udp" port="4500"/>
  <port protocol="udp" port="500"/>
</service>

$ sudo firewall-cmd --zone=FedoraServer --add-service=rancher
success
```

I did check SSL as noted by others in this thread, but the `rancher/server` container starts spitting out TLS handshake errors when that is the case, which wasn't happening in the original issue. I couldn't access port 8080 at all, so I'm pretty sure this was a firewalld issue, not a certificate issue.

**Comment by averri** [comment]
Another similar problem: https://github.com/rancher/rancher/issues/5381

**Comment by danielschlegel** [comment]
Same here: https://github.com/rancher/rancher/issues/5536

**Comment by deniseschannon** [comment]
@sapslaj Are you still facing issues?

**Comment by vargalas** [comment]
same here

**Comment by vargalas** [comment]
I have a fresh ubuntu 16.04  host on azure. The problem happened with the host firewall off, too. Tried with the public ip and the 10. ip, too
Nothing else was running on the host. I changed the Host Registration URL in :8080/admin/settings to the same url, just using http instead of https. then I used the generated registration command, just changing the https to http there, too. The registration was successful after it.

**Comment by aemneina** [comment]
Closing this issue out.

**Comment by tiangolo** [comment]
I will cross-post my solution for a similar problem that I posted here: https://github.com/docker/docker/issues/16137#issuecomment-271615192 as it seems it could also be relevant in this issue (this is one of the issues I found and followed while investigating my problem).

I'm sorry if any of you consider it "spam", but as it is a possible solution I think it's best to share it.

---

**Note**: How I fixed it is a section below.

I was having issues with `firewalld` and Docker, specifically with Rancher v1.2 in CentOS 7.

Rancher needs a container to be able to communicate to the host via it's external (possibly local) IP address.

It was a requirement to have `firewalld` enabled and working.

## Environment

**OS**: `CentOS Linux release 7.3.1611 (Core)`

**Kernel** updated manually using "elrepo" to be able to use Overlay2 (`devicemapper` gave us several problems), although I don't think the kernel or the back end store is related to the problem: `4.9.0-1.el7.elrepo.x86_64`

**Docker**: 

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
[root@node19 cerebro]# uname -r
4.9.0-1.el7.elrepo.x86_64
[root@node19 cerebro]# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**`firewalld` is enabled**: 

```
systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since jue 2017-01-05 18:04:12 COT; 4 days ago
     Docs: man:firewalld(1)
 Main PID: 24584 (firewalld)
   Memory: 46.5M
   CGroup: /system.slice/firewalld.service
           └─24584 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D PREROUTING' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER-ISOLATION' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -n -L DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER-ISOLATION -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8' failed:
```

...but those errors in `firewalld` are expected as pointed out in: https://github.com/docker/docker/issues/16137#issuecomment-269398488


## The problem

`firewalld` uses `iptables` and IPtables rules under the hood, but the way it "works" is with different "zones", with different levels of access (as I understand, different sets of `iptables` rules for each "zone").

The `docker0` network interface is not assigned to any zone, so, some of its communications are blocked.

In my case, running the Rancher "agent" (a Docker container) with `firewalld` active gives errors about not being able to connect to the Rancher server (via it's external IP, in where the Rancher server, another container, is listening to). But with `firewalld` inactive, it works normally.

To make it worse, in all the systems I have tested (bare metal and Linode VPS) the `docker0` interface's `firewalld` zone cannot be modified using `firewalld` commands, because it is "controlled" by the "NetworkManager".

## The fix

* Check the `firewalld` "zone" asigned to the Docker interface:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If it says "no zone", you need to add it to the `trusted` zone

```bash
firewall-cmd --permanent --zone=trusted --change-interface=docker0
```

* If the previous command returns a message like:

```
The interface is under control of NetworkManager, setting zone to 'trusted'.
success
```

...it means that `firewalld` cannot control the zone of the interface (even if it says "success").

You can check that the zone was not assigned by running again:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If that's the case, you need to use the "NetworkManager" and restart the `docker0` interface, so first stop the `docker` daemon:

```bash
systemctl stop docker
```

* Now use the "NetworkManager" command line interface to set the zone of the `docker0` interface to `trusted`:

```bash
nmcli connection modify docker0 connection.zone trusted
```

* Now turn the `docker0` interface off:

```bash
ifdown docker0
```

* And turn it on again:

```bash
ifup docker0
```

* And check that the `firewalld` zone assigned to the interface `docker0` is "trusted":

```bash
firewall-cmd --get-zone-of-interface=docker0
```
...now it should return `trusted` instead of `no zone`

* Now you can start Docker again:

```bash
systemctl start docker
```

* Check if the problem you had was solved

## References

http://unix.stackexchange.com/a/225845/90829

[Introduction to FirewallD on CentOS - Linode](https://www.linode.com/docs/security/firewalls/introduction-to-firewalld-on-centos)

[RedHat forums (in the comments is mentioned the `nmcli`)](https://access.redhat.com/discussions/1455033)

[RedHat docs for `nmcli`](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Using_the_NetworkManager_Command_Line_Tool_nmcli.html)
