### ISSUE TITLE
etcd is being upgraded despite no changes in docker-compose.yml for a Kubernetes stack upgrade 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5227]
**Rancher Version:**: v1.1.0-dev5-rc5

**OS and where are the hosts located? (cloud, bare metal, etc):**: Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment
2. Add a "library" catalog entry using https://github.com/soumyalj/qa-catalog [ This catalog has updated images only for rancher/k8s:v1.2.4-rancher6. No updated images for etcd]
3. The Kubernetes stack should show upgrade available
4. Click on upgrade. 

**Results:** 
The etcd containers get upgraded and they are stuck in initializing state.

**Comment by deniseschannon** [comment]
Underlying issue:

For some reason the etcd container is being upgraded when using rancher-compose-executor as the hash is changing.

When testing this issue, the equivalent test using the CLI has no issues in comparing hashes.

**Comment by deniseschannon** [comment]
rancher-compose v0.8.5-rc1 has been released to fix this issue. @soumyalj please test it out.

**Comment by deniseschannon** [comment]
Verified with rancher-compose v0.8.5-rc1.

Steps To reproduce:
1. Create a catalog template that has a service with a `volume` or `volumes-from`. 
2. Upgrade the catalog template with no change to the service.

Previous issue: The service was being upgraded even though there was no change to the service because the volumes were being duplicated in the new service, so the hash of the service was not matching.

With v0.8.5-rc1, the volumes are no longer being duplicated. The service with `volumes` or `volumes-from` does not upgrade as expected.

Note: This was why the `etcd` service was being upgraded in the k8s upgrade stack, when there was no change to the `etcd` service.
