### ISSUE TITLE
Rancher Catalog is required to be enabled for k8s environments to work

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5228]
**Rancher Version:**
v1.1.0-dev5

If you disable the Rancher Catalog in the UI and try to use a k8s environment, it doesn't work as the k8s system stack templates are under the github.com/rancher-catalog repo. 

We need to de-couple what is required for k8s system stacks from Rancher certified catalog templates.

Note: we have users who have requested to be able to disable the Rancher catalogs, which is why this might be an issue.

**Comment by cloudnautique** [comment]
This will be resolved by the Infrastructure catalog.

**Comment by LLParse** [comment]
The infrastructure catalog solves many problems pertaining to system stacks, but it doesn't eliminate the requirement of accessing a catalog for K8s to function.

The modular catalog design is how Rancher is intended to function - anything that is orchestrated/managed by Rancher is launched from a catalog. Catalogs need to be able to change and are therefore not bundled within Rancher server itself.

Users who want to completely disable all rancher catalogs are able to do so *today* by checking out the required git repository and making it available to their Rancher server. This may be done in many ways. A simple approach would be to inject the repository into the rancher-server container's filesystem and define the custom catalog URL on the Settings screen:
(for 1.1.X) Name=`library` URL=`file:///.../rancher-catalog`
(for 1.2) Name=`infra` URL=`file:///.../infra-catalog`

These catalogs **must** be actual git repositories because the catalog service performs a `git clone` in order to fetch them. We should consider re-designing rancher-catalog-service for catalogs defined with `file://` scheme. Instead of performing a `git clone` every 5 minutes, we could watch the directory for changes and update immediately.

[Other users](https://forums.rancher.com/t/tools-techniques-for-development-of-cattle-catalogs/2760/7) have requested this feature in the forums because they are tired of committing every little template change for testing in their local environments. This ticket seems like a good excuse to solve that problem. @deniseschannon
