### ISSUE TITLE
Kubernetes API server HA 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5235]
We should launch Kubernetes API server in HA mode so it is failure resilient. 

Also we should review the health check configuration for Kubernetes api service: a couple of times I've ran into the bug when k8s fails to serve api request due to Kubernetes specific bug (https://github.com/rancher/rancher/issues/4838), yet the service was considered as healthy by Rancher.

**Comment by LLParse** [comment]
In order to implement this, we will need to implement sidekick health check functionality.

The api-server/scheduler/controller-manager need to run within the same network namespace since they are tightly coupled. We then would scale this deployment unit across hosts for resiliency. Our sidekick mechanism provides this ability, but will only monitor the health of one of the core components.
