### ISSUE TITLE
Scale policy

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5243]
1) Scale policy parameter was added to the service object (updatable). Fields:

minScale - minimum number of instances required to be running for the service
maxScale - maximum allowed service scale.
increment - reflects a number of containers being deployed simultaneously as we move from minScale to scale.
Example:

1) service created policy {minScale:2, maxScale:4, increment:2}.
2) Durning activate, we try to deploy 2 (=minScale) containers. If it fails, service activation fails as we don't match minScale. If succeeds, move to 3)
3) We increment scale by 2 (=increment), and wait for these instances to deploy. If at least one of them fails to deploy, we roll back to 2, and reconcile finishes with currentScale=2. If deployment of 2 extra instances is successful, reconcile finishes with currentScale=4

@soumyalj besides testing different combinations of scale policy params, we would have to test scalePolicy update use case

**Comment by ruimarinho** [comment]
@alena1108, does this new scale policy allow for the use case of testing the health check once to decide whether it is ok to proceed to the next instance(s)? This would allow for rolling upgrades where some synchronization is required between peers (e.g. zookeeper nodes) and the container state (active or not) may not be enough.

**Comment by alena1108** [comment]
@ruimarinho checking health_state check before proceeding to the new batch during in-service upgrade, was fixed as a part of diff issue. Scale policy just lets you bend the scale by saying "try your best, but do the min"

**Comment by ruimarinho** [comment]
One thing to consider is that the health check waits for the "initializing timeout" before running and advancing to the next batch if the check is successful so, in practice, this means that the batch interval will always be as small as this health check "initializing timeout".

Perhaps this is part of a different issue and I'll be glad to file it separately if you prefer, but shouldn't the "initializing timeout" be the maximum amount of time that repeated health checks can be tested until the container is considered healthy when starting? This way, if a service only takes 10 seconds to boot and the batch interval is set to 30 seconds, then the health check could be repeatedly executed every X seconds (e.g. 2s) until it responds successfully. Otherwise, after a certain amount of time of failed health checks attempts, the upgrade would fail.

**Comment by soumyalj** [comment]
Tested with 1.1.0-rc4.
