### ISSUE TITLE
Missing hyperv-url in add host with hyperv driver

### ISSUE THREAD

**Issue by djcenox** [rancher/rancher#5254]
Rancher Version: v1.1.0-rc1

Docker Version: 1.12

OS and where are the hosts located? (cloud, bare metal, etc): hyperv

Setup Details: single node rancher external db

Environment Type: Cattle

Steps to Reproduce: Just add hyperv driver in the form you cannot specify hyperv-url

Results: Error cause hyperv-url is empty.

**Comment by tfiduccia** [comment]
Version - v1.1.0-rc3
Checked and there is no field for the hyperv-url.

**Comment by vincent99** [comment]
There is not a field for that in the docker-machine driver, (https://github.com/docker/machine/blob/master/drivers/hyperv/hyperv.go).  It's only designed to run locally on a Windows machine by calling powershell.  We will add this driver to the list of ones that are hidden because they're not useful in Rancher.
