### ISSUE TITLE
Scheduler V2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5264]
Scheduler V2:

- [x] Performance Improvement
  - [x] Refactor scheduler to schedule all units in a deployment unit at once
  - [x] Create fine-grained locks built dynamically based off of constraints instead of locking at account level
- [x] Move out of cattle 
- [ ] Add compute resource management to scheduling
  - [x] CPU
  - [x] MEM
  - [ ] Storage (This one requires refactoring/rolling back our first attempt at this)

**Comment by cjellick** [comment]
Additional items:
- [ ] Integrate external scheduler with rest of rancher so that users can turn it on at a per environment level
- [ ] Create new fields for scheduling constraints on containers so that we are not overloading the docker run fields

**Comment by cjellick** [comment]
[ ] possibly completely eliminate volume allocation

**Comment by cjellick** [comment]
Right now CPU and mem are implemented. Storage is not fully functional yet.
So, lets test those and i'll open a separate issue when storage is ready.

**Comment by cjellick** [comment]
Here is the usage:
You have to deploy the [Rancher Scheduler infra-catalog item](https://github.com/rancher/infra-catalog/tree/qa/infra-templates/rancher-scheduler)

Hosts will now have three fields that indicate the total schedulable resources on them. They are explained here: https://github.com/rancher/rancher/issues/6130. Those fields will either have their values populated by the agent when the host is registered or be overridden by the user.

New fields have been introduced to container:
- memoryReservation
- milliCpuReservation

The scheduler will decide which hosts have capacity based off of those inputs. Purging the container will reclaim those resources for the host.

Those fields will also be used as part of the docker run command for the container. memoryReservation is a field in the docker API, so it is just a pass through. milliCpuReservation will be translated to cpuShares. It requires a conversion. The formula to convert is: `(milliCpuReservation / 1000) * 1024`. We do this because 1024 is the value used by default for cpuShares.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Host has the following parameters set by default:

"localStorageMb"
"memory"
"milliCpu"

We also have the ability to edit the above settings.


Deployed Rancher Scheduler from  - https://github.com/rancher/infra-catalog/tree/qa/infra-templates/rancher-scheduler.

Able to set the following parameters when launching services to allocate memory and cpu for the container:
memoryReservation
milliCpuReservation

Issues found when testing this feature are tracked in different bugs. Some of the bugs logged so far:

https://github.com/rancher/rancher/issues/6253
https://github.com/rancher/rancher/issues/6250
https://github.com/rancher/rancher/issues/6249
https://github.com/rancher/rancher/issues/6236
