### ISSUE TITLE
Respect service index when deleting containers with sidekicks

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5405]
**Rancher Version:**
1.1.0

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Steps to Reproduce:**
1. Deploy a service with sidekicks and scale=3.
2. Scale down the service which should delete `container_1` (at least on my machine).
3. Delete `container_2`.

**Results:** 

After a second or two, the scheduler will launch `container_1` which have `container_sidekick_2` as a sidekick, which is incorrect.

Here's the entire issue in a visual form:

![service index](https://cloud.githubusercontent.com/assets/92085/16771285/d078394c-4847-11e6-88ba-23290eeecf2c.gif)

**Expected:**

As per [this comment](https://github.com/rancher/rancher/issues/2494#issuecomment-178256442), the service_index should be preserved.

**Comment by deniseschannon** [comment]
Rancher was not relying on service_index of a containr due to how we were recreating instances when an unhealthy one was detected. Instead of relying on `service_index`, we were ensuring deployments had the same `deployment.unit` label. You can fetch this information from container's "labels" field on the metadata. Primary + (n) sidekick containers have the same "io.rancher.service.deployment.unit" value. For a example, in service with scale=3 having 1 sidekick, there will be 3 deployment units, each having 1 container of primary + 1 container of a sidekick service. So to get your peers, you find out what your deployment.unit is, and then get instances having the same deployment.unit from /latest/containers.

We've changed how we are recreating instances that could make us move to respecting service index now, so I've made it an enhancement request.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/5611
