### ISSUE TITLE
ssl health check not working

### ISSUE THREAD

**Issue by cavemandaveman** [rancher/rancher#5435]
**Rancher Version:** v1.1.0

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 
Launch a service that exposes an ssl endpoint, set a health check on the ssl request path and port.

**Results:** 
Service stuck in "Initializing" because health can't be verified. My guess is the health check is trying to ping http://container-ip:port/healthcheck and getting 400s instead of trying https://container-ip:port/healthcheck. Not sure how to verify.

**Expected:**
Health check should work regardless of defining an http or https endpoint

**Comment by vincent99** [comment]
SSL (TLS) is not supported for HTTP health checks.  If your container is actually doing its own SSL termination then the only option is a TCP check.

Health checks go over the private overlay network to the container port, not to the actual published host port.  So if you are doing SSL termination with a load balancer, or mapping a different public port to the container port (e.g. `-p 80:8080`) then you would want the healthcheck to go to the container port (`8080`).

**Comment by cavemandaveman** [comment]
Is it on the roadmap to support SSL for HTTP health checks? Currently, this means we have to use a third party solution like Consul, inside of Rancher, just for health checks...

**Comment by jmloeffler** [comment]
I did some spiking on this.  It looks like if we had a boolean on the health check for whether the healtcheck was SSL or not the healthcheck service would create the haproxy server lines as:
`server {{$be.Server.UUID}} {{$be.Server.Address}}:{{$be.Server.Port}} ssl verify none check check-ssl port {{$be.Server.Port}} {{$be.Server.Config}}`

... instead of the normal

`server {{$be.Server.UUID}} {{$be.Server.Address}}:{{$be.Server.Port}} check port {{$be.Server.Port}} {{$be.Server.Config}}`

So this would require a change to the UI to add the checkbox, adding the boolean to the metadata service Healthcheck type, and changing the healthcheck service to write the different haproxy lines based on whether the metadata service reports that the healthcheck is SSL or not.  I think hard-coding the "ssl verify none" would be ok since there's no need for the healthchecks to spend the time verifying certificates.  This also avoids the issue of having to provision the certs to the healthcheck containers.  Rancher-compose would probably also need to change to support this field in the rancher-compose.yml.  This wouldn't change the way the load balancers are configured, just the haproxy within the healthcheck infrastructure services.

I'd really like to have this feature so I don't mind doing the work but I'd like to get everyone's opinions on it before I start.  If there's a non-starter here then I'd rather chat it out beforehand.  Thoughts?

**Comment by jmloeffler** [comment]
@vincent99 Seem like something that would be acceptable as a PR? Happy to discuss.

**Comment by vincent99** [comment]
I'm not sure I agree on `ssl verify none`.. if the cert expires it's not very healthy, but this is also the type of thing enterprises have blanket rules about (not) doing.  OTOH making it go unhealthy will just try to replace the containers and then never leave `initializing` because the check won't pass.  Since you're adding one option already I'd probably just make this a second one, `tls` and `tlsVerify` both defaulting to false.

The main thing you're missing is the first step, changing the healthcheck schema in cattle to accept and store the new field(s).

**Comment by jmloeffler** [comment]
Thanks for the feedback.  In my mind, a healthcheck is the wrong place for cert validation.  It's nothing that can be fixed by destroying & recreating containers.  We have layers of monitoring that catch that kind of thing long before a cert expires.  I think a healthcheck is more in the realm of "is my service able to satisfy requests."  But I understand that some orgs have blanket rules against unverified TLS under any circumstances.

The biggest hurdle I see with implementing a tlsVerify option in the healthcheck is having to provision the certs out to the healthcheck containers.  I was really trying to avoid that.  The load balancers have you specify the cert when you set up the HTTPS route and there is some mechanism that has the selected pem file copied into the lb container.  I'm wondering if we'd have to do the same on the healthcheck setup or if it already has access to those certs somewhere.

**Comment by DaveOHenry** [comment]
Did anyone find a solution or is it still impossible to use HTTPS healthchecks with Rancher? Is it possible to customize the healthcheck service somehow like we can write a custom haproxy config for the Rancher loadbalancer? As far as I know the loadbalancer and healthcheck services both use haproxy. Unfortunately there is no way (at least not in the GUI) to customize the config of the health check service.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
