### ISSUE TITLE
Download using docker images from PRIVATE docker registry

### ISSUE THREAD

**Issue by g0194776** [rancher/rancher#5440]
Hi guys, How can I let the **rancher/agent** downloading those of used docker images from PRIVATE docker registry? (ETCD, agent-instance, etc.)

thanks,
Kevin Yang

**Comment by simon-scherzinger** [comment]
Hey Kevin,

check out the [docs](http://docs.rancher.com/rancher/latest/en/environments/registries/).

Cheers,
Simon

**Comment by deniseschannon** [comment]
There are docs on how to use private registries for services

But since you also added `agent-instance` in your example, you should take a look at how to run Rancher server with a private registry (aka no internet access).

http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/no-internet-access/#using-private-registry

**Comment by deniseschannon** [comment]
@g0194776 Please reopen if you have further questions.
