### ISSUE TITLE
Name LB Agent containers to reflect the LB they are servicing

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#545]
Server - V0.16.3

Currently all LB agent containers are named as "Lb Agent" . It would be very helpful and informative to be able to know the Lb that it is servicing from the name of the Lb agents .

Can the LB agents be named with some reference to the LB name it services like LB-agent-<LB name> ?

**Comment by nazar-pc** [comment]
+1, a bit confusing to see just `Lb Agent` in containers list instead of the name I gave it at creation.

**Comment by deniseschannon** [comment]
:+1: It's very difficult to see which LB Agent is for which container or service.

**Comment by gordontyler** [comment]
Yeah... I've got 25+ LB agents in my stack... :)

**Comment by deniseschannon** [comment]
In v0.51.0, load balancer containers are no longer labeled with `LB Agent` but instead are the load balancer names (like other services). They are still grey to indicate that it's a load balancer. 

Since a LB could service many different targets, it doesn't make sense to have them named after the target services.

**Comment by sangeethah** [comment]
With  v0.51.0, Currently LB agent containers are named after the LB service name.
