### ISSUE TITLE
Port should be configured in docker-compose.yml as strings

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#550]
Server Version - V0.16.3

Steps to reproduce the problem:

Create an environment.
Create a service in this environment by specifying a port map.

The docker-compose.yml for this service has the ports specified as follows:
```  
ports:
  - 8090:80/tcp

```
Following is the recommendation:

"Note: When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML will parse numbers in the format xx:yy as sexagesimal (base 60). For this reason, we recommend always explicitly specifying your port mappings as strings."

**Comment by alena1108** [comment]
Unfortunately, this problem is not trivial to solve. Unless the value has trailing or ending spaces, its not surrounded by quotes. If I change the formatter properties to set the scalarType to double or single quotes, it applies to all the entires in the compose file. In other words, you will see something like:

image: "ubuntu" 
ports
- "80:80"

While docker-compose tool expects to see mix and match of the both:

image: ubuntu  - no quotes
ports
- "80:80" - quotes


We can document it for now

**Comment by deniseschannon** [comment]
Functionality not broken, closing for now.
