### ISSUE TITLE
Rancher not answering if on same host like rancher

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#5536]
**Rancher Version: v1.1.2**

**Docker Version: 1.11.2, build b9f10c9**

**OS and where are the hosts located? (cloud, bare metal, etc): Linux 3.10.0-327.22.2.el7.x86_64**

INFO: Found Server version: 1.11.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.2
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.5.4
INFO: docker version: Git commit (server): b9f10c9
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Library Version: 1.02.107-RHEL7 (2016-06-09)
INFO: docker info: Kernel Version: 3.10.0-327.22.2.el7.x86_64
INFO: docker info: Operating System: CentOS Linux 7 (Core) 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: Kubernetes**

**Steps to Reproduce:**
```
# Start rancher 
docker run --name rancher -d -v ~/rancher/mysql:/var/lib/mysql --restart=always -p 8080:8080 rancher/server:stable
# try to add agent on same host like rancher
sudo docker run -e CATTLE_AGENT_IP="rancher-server-ip" --add-host rancher.server.com:"10.1.5.136" -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://rancher-server-ip:8080/v1/scripts/6D3C87C1464FBA547121:1469433600000:xr1Qlk39xkOU9pnyCk0RFhw5fU
# start nginx to test 
docker run -p 8000:80 -it nginx 
docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                              NAMES
e7d0588122fa        nginx                   "nginx -g 'daemon off"   12 minutes ago      Up 12 minutes       443/tcp, 0.0.0.0:8000->80/tcp      dreamy_mcclintock
ecfdabeee2cc        rancher/agent:v1.0.2    "/run.sh http://10.1."   55 minutes ago      Up 55 minutes                                          sleepy_blackwell
7eb72f3ca426        rancher/server:stable   "/usr/bin/s6-svscan /"   About an hour ago   Up About an hour    3306/tcp, 0.0.0.0:8080->8080/tcp   rancher
```
**Results:** 
```
# login into agent container
docker exec -it ecfdabeee2cc bash
root@ecfdabeee2cc:/tmp# curl http://rancher-server-ip:8000 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>     
  
# nginx works but no answer from rancher
curl http://rancher-server-ip:8080
curl: (56) Recv failure: Connection reset by peer

# also telnet can connect but gets no answer
root@ecfdabeee3cc:/tmp# telnet rancher-server-ip 8080     
Trying rancher-server-ip...
Connected to rancher-server-ip.
Escape character is '^]'.
```

**Expected:**
I should be able to get a result from rancher. If i curl from hostsystem i get a result from rancher: 

```
{"id":"1647a540-8455-40c5-9956-0c603d2889bd","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
```

**Comment by danielschlegel** [comment]
Is there anybody who could help with this?

**Comment by danielschlegel** [comment]
I was able to solve the problem with some firewall rules to accept outgoing traffic to port 8091. In Documentation i did not found this port so it would be good to add this...
From my side you can close this issue.

**Comment by deniseschannon** [comment]
Were you running a k8s environment? The only place I could find port 8091 was in our kubernetes system templates.

**Comment by danielschlegel** [comment]
yes its on a k8s env.

**Comment by tiangolo** [comment]
I will cross-post my solution for a similar problem that I posted here: https://github.com/docker/docker/issues/16137#issuecomment-271615192 as it seems it could also be relevant in this issue (this is one of the issues I found and followed while investigating my problem).

I'm sorry if any of you consider it "spam", but as it is a possible solution I think it's best to share it.

---

**Note**: How I fixed it is a section below.

I was having issues with `firewalld` and Docker, specifically with Rancher v1.2 in CentOS 7.

Rancher needs a container to be able to communicate to the host via it's external (possibly local) IP address.

It was a requirement to have `firewalld` enabled and working.

## Environment

**OS**: `CentOS Linux release 7.3.1611 (Core)`

**Kernel** updated manually using "elrepo" to be able to use Overlay2 (`devicemapper` gave us several problems), although I don't think the kernel or the back end store is related to the problem: `4.9.0-1.el7.elrepo.x86_64`

**Docker**: 

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
[root@node19 cerebro]# uname -r
4.9.0-1.el7.elrepo.x86_64
[root@node19 cerebro]# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**`firewalld` is enabled**: 

```
systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since jue 2017-01-05 18:04:12 COT; 4 days ago
     Docs: man:firewalld(1)
 Main PID: 24584 (firewalld)
   Memory: 46.5M
   CGroup: /system.slice/firewalld.service
           └─24584 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D PREROUTING' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER-ISOLATION' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -n -L DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER-ISOLATION -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8' failed:
```

...but those errors in `firewalld` are expected as pointed out in: https://github.com/docker/docker/issues/16137#issuecomment-269398488


## The problem

`firewalld` uses `iptables` and IPtables rules under the hood, but the way it "works" is with different "zones", with different levels of access (as I understand, different sets of `iptables` rules for each "zone").

The `docker0` network interface is not assigned to any zone, so, some of its communications are blocked.

In my case, running the Rancher "agent" (a Docker container) with `firewalld` active gives errors about not being able to connect to the Rancher server (via it's external IP, in where the Rancher server, another container, is listening to). But with `firewalld` inactive, it works normally.

To make it worse, in all the systems I have tested (bare metal and Linode VPS) the `docker0` interface's `firewalld` zone cannot be modified using `firewalld` commands, because it is "controlled" by the "NetworkManager".

## The fix

* Check the `firewalld` "zone" asigned to the Docker interface:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If it says "no zone", you need to add it to the `trusted` zone

```bash
firewall-cmd --permanent --zone=trusted --change-interface=docker0
```

* If the previous command returns a message like:

```
The interface is under control of NetworkManager, setting zone to 'trusted'.
success
```

...it means that `firewalld` cannot control the zone of the interface (even if it says "success").

You can check that the zone was not assigned by running again:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If that's the case, you need to use the "NetworkManager" and restart the `docker0` interface, so first stop the `docker` daemon:

```bash
systemctl stop docker
```

* Now use the "NetworkManager" command line interface to set the zone of the `docker0` interface to `trusted`:

```bash
nmcli connection modify docker0 connection.zone trusted
```

* Now turn the `docker0` interface off:

```bash
ifdown docker0
```

* And turn it on again:

```bash
ifup docker0
```

* And check that the `firewalld` zone assigned to the interface `docker0` is "trusted":

```bash
firewall-cmd --get-zone-of-interface=docker0
```
...now it should return `trusted` instead of `no zone`

* Now you can start Docker again:

```bash
systemctl start docker
```

* Check if the problem you had was solved

## References

http://unix.stackexchange.com/a/225845/90829

[Introduction to FirewallD on CentOS - Linode](https://www.linode.com/docs/security/firewalls/introduction-to-firewalld-on-centos)

[RedHat forums (in the comments is mentioned the `nmcli`)](https://access.redhat.com/discussions/1455033)

[RedHat docs for `nmcli`](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Using_the_NetworkManager_Command_Line_Tool_nmcli.html)

**Comment by morlay** [comment]
@tiangolo Just want to say thanks. 

It works on CentOS7 after docker restarted ~

BTW should we need to mv to Overlay2?

```
# uname -a
Linux iZ25o71915jZ 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tiangolo** [comment]
@morlay I'm glad it worked!



We had several issues with DeviceMapper:

* At some point containers said the disk was full although there was still plenty of host disk
* After creating and removing several containers that created lots of data, DeviceMapper failed to free the space and then, even without containers nor volumes, the host disk was full

Also, Docker has a warning saying that they don't recommend DeviceMapper for production, I don't remember where.

And... [Friends Don't Let Friends Run Docker on Loopback (DeviceMapper) in Production](http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/)

We also had problems running `docker exec`s into containers with the default kernel, so that's another thing that the updated one solved for us.

Up to now, we haven't had any problem with the new kernel.

But it's not "officially" supported.

If you want to update the kernel and try Overlay2, or even try it and revert back, it's quite easy: https://adminswerk.de/overlayfs-docker-storage-driver-centos-7/

**Comment by morlay** [comment]
@tiangolo 
Here a compare https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#/future-proofing.

Docker's warning is for DeviceMapper(loop) but not the DeviceMapper(direct-lvm). So this is why i confused. DeviceMapper(direct-lvm) work well for now on our environments.

`docker exec` fixed in the new kernel, that is really cool. I will try it ~

Thanks again. for lots of helpful informations.
