### ISSUE TITLE
[Feature Request] Shared environment variable configuration

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#5579]
Between side projects and stuff at work, I seem to be duplicating a lot of environment config between services.  Our average Laravel/Lumen application has at least 4 containers (cron, php-fpm, migrations and queue) with a copy of the application on each and we end up needing to add ENV variables to each service.  For instance, each of these containers needs access to the database, so that’s DB_HOST, DB_DATABASE, DB_USER, DB_PASSWORD that need to be defined.  It’d be great if there was a way that we could update ENV vars once and have it apply to certain services.

**Comment by ddelnano** [comment]
I did some searching around but come up empty, is there any support for using envs from a distributed key-value store like etcd??

I have the same issue but being able to use something like etcd would make it easy to modify a single value and have it effect all services with duplicate configuration.

**Comment by xaka** [comment]
Having something similar to k8s ConfigMap and Secret would be great addition to Cattle. Indeed one of those important missing features.

**Comment by pcornelissen** [comment]
Before I switched to rancher I used "Kontena" for docker orchestration and it offers a "secrets" functionality that enables you to map values to environment variables. This is not as secure as file based mounting, but you can use this mechanism to also share common configuration between stacks or services. So you can define for example a secret that contains the public hostnames for this environment and then all services can use it without the need to have a environment file on every host that wants to deploy something.

Configuration data that is specific for an environment should be hosted in rancher, this would make live much easier!

**Comment by vincent99** [comment]
Global environment variables do not really make a lot of sense, they need to be set on container create and can't be updated, and there is no explicit link between the containers and the variables being used.  So if you ever add/edit/remove a variable you gave no idea what containers are seeing it.

Secrets already exist in Rancher.  They are explicitly linked to the service using them and are not editable. To change one you create a new secret and have enough indo to upgrade the relevant containers/services.

**Comment by pcornelissen** [comment]
Well besides the fact that it would be nice to have the option to have secrets exposed as environment variable (i know it's not perfect security wise, but many docker images rely on that mechanism and can't work with the file based secrets on their own) you also have environment wide config that isn't very volatile, like DNS-names that are used in the rancher-/docker-compose.yaml files etc.

I can't just use my spring-boot based configserver for this although it would be capable of serving this kind of data, because then I can't use the default loadbalancer that comes with rancher because I need to provide the hostnames in the config somehow and I have a few stacks that require the same information and all stacks are located in dedicated git repos to make deployments etc. easier.

This would all be solved by having a central configuration store that can be used for example in a similar way to secrets where I can reference this in the config-file and the value for this environment is used automatically.
This values also need to be exposable via env variables to be compatible with all these nice container images out there.

So it would be neat to extend the secrets stuff to expose secrets as env variables if required and as "variable" during the processing of the docker-compose/rancher-compose file, then you could just put all environment specific stuff like Hostnames, password for the DB etc. in secrets and you don't have to keep them around anywhere else (especially not in your CI server which should do the deployment)

**Comment by rscully** [comment]
I further the need for something like this. We have many common configurations between our services and it would be great to be able to supply this configuration as a global config type something. This way, we change it once, it propagates to all and we don't have to go through each individual service.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by rscully** [comment]
Is this feature request now available in 2.0?

**Comment by vincent99** [comment]
Sort of, secrets can be shared across all the namespaces of a project in 2.x.
