### ISSUE TITLE
API projects delete action '/v1/projects/.../?action=delete' not working

### ISSUE THREAD

**Issue by pangdudu** [rancher/rancher#5588]
**Rancher Version:**
Rancher 1.1.2 (also happens with 1.1.0)

**Docker Version:**
1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on Google Compute Engine (cloud)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I'm using an admin account api key.

* create 'project' via API: POST /v1/projects/
* deactivate 'project' via API: POST /v1/projects/1a311/?action=deactivate
* remove 'project' via API: POST /v1/projects/1a311/?action=remove
* (try to) delete 'project' via API: POST /v1/projects/1a311/?action=delete

**Results:** 
* the last (delete) action fails
* project is stuck in 'purged' state
* API UI also breaks and shows: 
```
"Error loading schema from [https://.../v1/projects/1a311/schemas]: error"
```
* if you try to follow the project's schemas link, you get:
```json
{
"id": "3b76f314-2109-4af5-a957-be29727c2130",
"type": "error",
"links": { },
"actions": { },
"status": 403,
"code": "Forbidden",
"message": "Forbidden",
"detail": null,
}
```

I guess I'm not getting something here. What is the supposed 'project' lifecycle? 

Is it:
* active
* inactive
* purged
* (not in the system anymore)

**Expected:**
API: POST action 'delete' removes the project from the system.

**Comment by vincent99** [comment]
`purged` is the terminal state for most resources.  A few things have automatic cleanup but otherwise they are never physically removed from the database, for example because audit log entries will still refer to them.. Purged resources are not returned in listing calls, but can still be retrieved directly by ID.

`delete` is not an action that exists, so that would never work even if you more things were allowed on a purged project.

Also you should use standard HTTP DELETE on the `self` link to remove a resource. This is the equivalent of the `remove` action, which exists mainly as an accidental side-effect of the way it is internally just another action to the API framework.  It will likely be removed someday in a future API revision.

**Comment by pangdudu** [comment]
Hi vincent, thanks for the reply.

The strange thing is, if I deactivate and delete in the UI, it's gone in the /projects list in the API. If I do the same via the API it's still there (in purged state) and I have it as an item in the /projects list in the API.
