### ISSUE TITLE
Load balancer TCP Request Host random target

### ISSUE THREAD

**Issue by steevegldev** [rancher/rancher#5618]
**Rancher Version:** 1.1.2

**Docker Version:** 1.12.0

**OS and where are the hosts located? :** Boot2Docker, vSphere

**Setup Details:** single node rancher. 2x nodes with 1x minecraft server container on each. 1x Load Balance scheduled to Rancher node for static ip (see picture below).

**Environment Type:** Cattle

**Steps to Reproduce:** 

1. Add stack, set name and leave by default
2. Add a load balancer.
3. Set name
4. Add port source/target and set protocol to TCP. (In my case TCP 25565)
5. Show advanced routing options
6. Set request host 1, port, target (in my case srvmc01.domain.com, 25565, srvmc01)
7. Set request host 2, port, target (in my case srvmc02.domain.com, 25565, srvmc02)

**Results:** Access to random container srvmc01 and srvmc02. Regardless to Request Host

**Expected:** Request Host srvmc01.domain.com target ALWAYS container srvmc01 and Request Host srvmc02.domain.com target ALWAYS container srvmc02

If I read well, That Service should be use with HTTP, but TCP can be set. That's work but get random access... So it's not what I expect as described: 

> If Request Host and/or Path are specified, connections to HTTP listening ports will be routed to the appropriate target based on the request. For example, you could use this to send traffic for domain1.com to a different service than domain2.com, or domain3.com/admin to a different service than domain3.com.

> Matching requests will be sent to the Target Service on the Target Port. If that is not set, then the Default Target port for the Source Port. If that is also not set, then the Source Port.

![image](https://cloud.githubusercontent.com/assets/6455947/17349297/7b596964-58ea-11e6-859e-c43019591909.png)
![image](https://cloud.githubusercontent.com/assets/6455947/17349356/077e35c8-58eb-11e6-9ccb-fed4da171063.png)

**Comment by vincent99** [comment]
For an arbitrary TCP connection there is nothing but the source IP/port (the client) and the target IP/port (the balancer) to go on. There is no way to route requests based on Hostname because that information does not exist.. The client makes a DNS request to find the target IP and the name it used to get that IP is not involved in the connection beyond that.

The concept of routing based on hostname exists for HTTP listeners because there is a specific HTTP header that says what host the client wants, and the balancer knows how to parse HTTP  requests to retrieve that information and handle it specially.

**Comment by deniseschannon** [comment]
@steevegldev Please reopen if you have more questions.

**Comment by narmontas** [comment]
In our environment we need to route TCP based on hostname and we do this in standalone HAProxy by adding these two lines to frontend:

```
tcp-request inspect-delay 5s
tcp-request content accept if HTTP
```

We are trying to migrate to Rancher and this is a no-go. Is it possible to add some custom logic for this to work?

**Comment by vincent99** [comment]
@narmontas is there a reason you don't just use a normal http mode listener?

**Comment by ephillipe** [comment]
@vincent99 I'm trying use normal HTTP listner mode to ports 25 and 587, but not work.

**Comment by vincent99** [comment]
@ephillipe Those are SMTP ports and SMTP is not a HTTP-based protocol.  As I said above the concept of hostname routing only exists for the few protocols that have a place in the request to tell you what the hostname was, and SMTP is not one of them.

There is no way to tell what hostname the client resolved in order to get the information that it should connect to the IP address.  The only information in the data sent is the source and destination IPs.  Therefore you cannot route based on that information, since it doesn't exist.

Similar to how a HTTP-aware service can do routing based on the Host header, it is possible to have a SMTP-aware service which can route based on the client `HELO`, `MAIL FROM` or `RCPT TO` messages, etc.  But this is not a thing built into haproxy.
