### ISSUE TITLE
Display current catalog version in stacks view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5619]
Rancher Version: v1.1.2

Currently , catalog version for stacks that have been deployed from catalog is not displayed.
There is no way for the user to know the catalog version that was used to deploy the stack.

It would be good to display current catalog version of the stack in stacks view.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/5582

**Comment by deniseschannon** [comment]
@vincent99 I would like this implemented so that you don't have to go to the upgrade page to be  able to tell the version.

Specifically, this would be helpful for Kubernetes debugging. It's very hard to find out what template people are using in their Kubernetes version without asking to share ALL their images of the kubernetes system stack.

**Comment by tfiduccia** [comment]
Catalog now says "Error checking for upgrade."
![Uploading image.png…]()

**Comment by tfiduccia** [comment]
Version - master 11/16
Verified fixed
