### ISSUE TITLE
Add in automatic cleanup for audit_log, process_execution and instance 

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#5620]
**Rancher Version:**
1.1.1
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
bare / ubuntu 14.04 LTS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Use for a few months
**Results:** 
audit_log = 2.6GB
instance = 1GB
process_execution = 600MB
container_event = 500MB

**Expected:**
There is a lot of data hanging around needlessly in many of the cattle's tables. It's really slows down the UI and creates a poor user experience.

**Comment by rossigee** [comment]
+1 - i've had to clear down old cruft in my rancher db recently it was not a quick or trivial exercise or without risk :( There should really be an official script/process for this, if not an actual maintenance thread that runs in the background.

**Comment by deniseschannon** [comment]
We have ways to decrease the cleanup of certain tables today, but need to add cleanup for aduti_log.

http://docs.rancher.com/rancher/latest/en/faqs/server/#rancher-server-database-is-growing-too-quickly

**Comment by bacheson** [comment]
One of the messiest areas is hosts. Deleting a host record should cascade removing all it's child records. Instead restricts are used everywhere.

**Comment by ibuildthecloud** [comment]
@bacheson The only tables we clean up today are process_instance, process_execution, service_event, container_event, and audit_logs.  The interval we clean those up after is based on a setting (/v1/settings/)

process_instance, process_execution - process_instance.purge.after.seconds default 86400
service_event, container_event - events.purge.after.seconds default 1209600
audit_logs - audit_log.purge.after.seconds default 7776000

Those are the tables that grow quickly, all other tables, such as instance we never delete.  We should at some point but the tables don't grow all that quickly.  The size of the DB typically doesn't impact performance that much.  It is usually something else that is slowing things down.  We welcome any audit you'd like to do.  Just know that any changes you suggest need to be done in a backwards compatible way.  For example renaming tables, column is typically not feasible because it breaks zero down time upgrades and doesn't allow rollback.  Unfortunately we've just had to live with poorly named things.

**Comment by bacheson** [comment]
I totally understand. Anything I can do to help even if it's something that get thrown out on the cutting room floor.

The big one for me is hosts. There are 10 tables I have to manually run a delete on to remove cruft. The foreign keys using "no action" don't allow me to simply delete the host record and take advantage of cascading.

eg:
delete from healthcheck_instance_host_map WHERE host_id = 54;
delete from container_event WHERE host_id = 54;
delete from host_ip_address_map WHERE host_id = 54;
delete from host_label_map WHERE host_id = 54;
delete from host_vnet_map WHERE host_id = 54;
delete from instance_host_map WHERE host_id = 54;
delete from service_event WHERE host_id = 54;
delete from storage_pool_host_map WHERE host_id = 54;
delete from host WHERE id = 54;

**Comment by ibuildthecloud** [comment]
@bacheson we use liquibase to manage the schema which I'll admit is probably not the easiest thing to figure out.  If you can recommend cleanup of the "on delete" actions by just sharing a mysqldump which has the DDL changes we can handle getting it into the right format.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/5129
