### ISSUE TITLE
Update catalog service to check version instead of folder number 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5634]
Currently, we look for upgrades of a catalog entry based on folder number.

In order to support multiple versions within the same catalog, we need to look for upgrades based on version.

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher-catalog-service/pull/62
PR for this

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre2-rc5

Verified that catalog version is used instead of folder number for presenting upgradable versions.

Versions corresponding to folder numbers in the catalog:

```
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat 10/rancher-compose.yml | grep version
  version: v1.3.1
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat 9/rancher-compose.yml | grep version
  version: v1.2.4-rancher7.4
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat 8/rancher-compose.yml | grep version
  version: v1.3.0-rancher3-1
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat 7/rancher-compose.yml | grep version
  version: v1.3.0-rancher3
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat 6/rancher-compose.yml | grep version
  version: v1.2.4-rancher7.3
```

Checked the following scenarios:

1. Current Version - v1.2.4-rancher7.3 . Upgradable versions presented to user - v1.2.4-rancher7.4,v1.3.0-rancher3,v1.3.0-rancher3-1,v1.3.1

2. Current Version - v1.2.4-rancher7.4 . Upgradable versions presented to user -version: v1.3.0-rancher3,v1.3.0-rancher3-1,v1.3.1

3. Current Version - version: v1.3.0-rancher3 . Upgradable versions presented to user - version: v1.3.0-rancher3-1,v1.3.1

4.Current Version - version: v1.3.0-rancher3-1 . Upgradable versions presented to user - version: v1.3.1
