### ISSUE TITLE
Stack stuck in activating when one container fails to come up, holds up other containers

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5671]
**Rancher Version:**
1.1.x

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node/external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
This can happen to standalone containers as well, when starting a container with a conflicting port for example. Rancher will cycle trying to create the container endlessly.

**Results:** 
stacks/containers stay in activating state indefinitely

**Expected:**
Bubble up error on why container cant come up

**Comment by dxxxxxg** [comment]
I'm adding this comment from a customer:

I think that is a great start. Given we don’t want to grant everyone ssh access to look at the docker.log this will be helpful. Actions correlated with the various log sources would also be very useful. In some cases, I hope (at least over time) Rancher will be able to identify docker/systemlog events and correlate to (mis)configuration in Rancher or even the docker-compose files.
 
E.g. Pulling form a repo without the right credentials results in a forbidden in the logs – Rancher can then provide in the UI “Unable to pull image due to authentication error. Did you add the registry credentials? <link to registries page”
 
Not always related to log events, but some level of docker-compose linting would also be useful:
E.g. Launching a docker-compose file with a bind mount to a non-existent path on the host – Rancher can then provide a warning “Service bind-mounts a non-existant directory on the host. Did you mean to use a named volume?”
 
The last one there made me realize there currently no “logs” at the stack level. So something like that could be presented as Stack-level errors/warnings in the UI.

**Comment by ibuildthecloud** [comment]
We have added service logs to bubble up issues in services.  Stand alone containers will also report the errors of why they haven't started.

**Comment by aemneina** [comment]
I see in the service view, there is a log tab. This looks great, verified using c1.2.0-pre4-rc15
