### ISSUE TITLE
Support for rancher-compose v2 networks

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5715]
In rancher-compose, we've added in support for v2 services, but need to add in v2 networks support.

**Comment by willseward** [comment]
Is there any milestone for this issue?

**Comment by Ramblurr** [comment]
So without this feature, it is not possible to use docker compose v2 files that rely on v2 networks? There's no workaround?

**Comment by mrcamp** [comment]
I second @Ramblurr's question. Not being able to create networks in docker-compose is a pretty major blocker. Is there any workaround at all for this? I've read before that Rancher uses libcompose... are the changes needed in libcompose or Rancher? 

Also, is this definitely getting prioritized in the 1.4.0 milestone at the end of the month? or does it look like this will get pushed to another release?

**Comment by mrcamp** [comment]
After some more research, I see that docker-compose itself doesn't yet support the networks key in swarm mode. Looks like this functionality is coming with docker-compose v3 in 1.10 and docker 1.13.

**Comment by ibuildthecloud** [comment]
This feature is not going to be in 1.4 and is going to take a bit more work.  The issue is that we do not use docker's libnetwork and do not currently plan on using it.  rancher-compose will support the network key (maybe around march timeframe) but it will be networking based off of CNI.  Docker's networking mode is really more a property of swarm mode.  From that perspective if you truly want to use Docker's networks then the approach would be to create a swarm mode environment in Rancher and use docker-compose directly.  At the time of writing swarm mode support in Rancher is experimental and does not work fabulously well.  I wish I had a better story here, but Docker's Swarm Mode has a been an extremely hard moving target to support.  Libnetwork additionally has been a hard technology to support as it is very Docker specific.  The container industry as a whole has more adopted CNI.

**Comment by Ramblurr** [comment]
Is there an alternative for creating networks while simultaneously using compose files instead of managing everything in the gui?

**Comment by patsissons** [comment]
So is there any way to create a new CNI so that you can sandbox networking within a stack?
