### ISSUE TITLE
http/2 with loadbalancer

### ISSUE THREAD

**Issue by ahansson89** [rancher/rancher#5766]
I would like to serve me site with http/2. Can someone show an example on how to do that with the rancher load balancer and the default nginx container?

Thanks,

**Comment by aemneina** [comment]
@ahansson89 check out the following link: http://docs.rancher.com/rancher/v1.2/en/cattle/adding-load-balancers/ the docker/rancher-compose.yml files provide a good example.

**Comment by santagada** [comment]
I didn't find any example of http/2 in that page, can you point paste here the part of the document? I think rancher lb uses haproxy which still has no support for http/2 (it will come with haproxy 1.7)

**Comment by pvalsecc** [comment]
I agree with @santagada, I don't find any documentation on how to enable HTTP/2 in the rancher load balancer. I've tried to add that to the cusomt haproxy.conf:
```
frontend 443
    bind *:443 ssl crt /etc/haproxy/certs/current alpn h2,http/1.1
```

But the configuration ended up looking like that:
```
frontend 443
bind *:443 ssl crt /etc/haproxy/certs/current
        bind *:443 ssl crt /etc/haproxy/certs/current alpn h2,http/1.1
mode http
```

I guess haproxy was a bit loss because of this double bind, because I kept having SPDY protocol errors in Chrome with that config.
