### ISSUE TITLE
Simplify REST API 

### ISSUE THREAD

**Issue by mikhail** [rancher/rancher#5781]
**Rancher Version:**
1.1.2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

At the moment to issue an API call to upgrade a stack (let's say simply to change the version) a serious overhead is required. The API call must know the environment UID or search for it; it must know the stack UID or again search for it. Then it must either have the full configuration of the stack, or download the live one. Then alter the needed parameters and upload the payload back to Rancher. 

To upgrade a docker version of a specific stack I would prefer a REST call with minimal information. Such as: `/api/v1/<environment_name>/<stack_name>/<service_name>/upgrade?image=<newimage:version>`

Simplifying the API to a point of full functionality via a single curl command would allow for much more appealing integration with CI engines.

**Comment by nrvale0** [comment]
@deniseschannon for triage.

**Comment by vincent99** [comment]
I would argue this is the sort of thing there should be a call for in [rancher/cli](https://github.com/rancher/cli), so that you're integrating CI with that rather than making API calls directly...

- Environment names are not unique at all (and cannot practically be)
- (Stack and Services names are not actually unique either, there may be additional ones in with the same name in removed state which can be listed)
- You don't need the environment at all if using an environment-specific API key
- You don't need anything about the stack, unless you're trying to disambiguate non-unique service names within different stacks
- Down the road of adding a query param for "I just want to update the image" leads madness.  The next person will "just" want to update the health check, or some labels, etc, until we've added special syntax for every field.  But what you're really asking for is patch updates, which there's no reason to invent new query params for
- The idea of patch updates is fine..
  - For normal resources we support partial-update by PUTting only the fields that you want to change. 
  - This doesn't work for actions (they're not an update) or nested objets (there's no way to differentiate replacing the field with this new object vs update this one nested property of the existing value)
  - But we could create some simple generic syntax to do that, like `{"+launchConfig": {"+imageUuid": "docker:foo:bar"}}`
  - Or go much more complicated with the full [PATCH RFC](https://tools.ietf.org/html/rfc6902)

**Comment by nrvale0** [comment]
FWIW, I sent OP links to Rancher CLI in back channel.

**Comment by deniseschannon** [comment]
@mikhail Please re-open if RancherCLI is not sufficient for your needs. The current version (v0.2.0) is only compatible with Rancher v1.2.0-pre3+, but v0.1.0 can be used for v1.1.x.

**Comment by 4F2E4A2E** [comment]
> But we could create some simple generic syntax to do that, like {"+launchConfig": {"+imageUuid": "docker:foo:bar"}}
This is a great proposal.
