### ISSUE TITLE
No such image or container: rancher-agent-state while add agent on a host that just remove agent

### ISSUE THREAD

**Issue by logicigam** [rancher/rancher#5791]
**Rancher Version:**
1.1.3

**Docker Version:**
1.9.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos 7
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes
**Steps to Reproduce:**
1)start server
2)add rancher agent on a different host
3)remove the agent just added
4)add agent at the same host
**Results:** 
time="2016-08-24T05:28:44Z" level=fatal msg="Error response from daemon: Could not find container for entity id f7d429683b383422354e5653de391403328c283ce47d3508060cddf5540eac3e" 
Error: No such image or container: rancher-agent-state

================
already try to remove /var/lib/rancher ,/var/run/rancher，docker rm -fv [agent-container]，not working.
but if I add a brand new host, it works.

any idea?

**Comment by cjellick** [comment]
This appears to be a docker 1.9 bug that was fixed in later releases of docker: https://github.com/docker/docker/issues/17691

The discussion there has some work arounds, but your best bet is to not being running docker 1.9. Though,  I'm guessing your hands are tied and there's a good reason why you are on it.

**Comment by deniseschannon** [comment]
Currently, we only support Docker 1.10.3+, so I will be closing this issue.
