### ISSUE TITLE
Wait for container to be fully started (healthy) before stopping during the upgrade

### ISSUE THREAD

**Issue by etlweather** [rancher/rancher#5826]
**Rancher Version:** 1.1.2

**Docker Version:** any

I have a service running and I perform an upgrade. I select to start-before-stop. So Rancher starts a new container with the upgraded settings/image. The container takes a few seconds to initialize. But the moment the container status changes from Starting to Initializing, the old container is stopped, leaving me with a non-functioning service.

I have a health check so when the container change from Initializing to Running, it is fully operational.

I would like Rancher to wait for the new container to be Running before stopping the old one.

**Comment by etlweather** [comment]
Basically, this is what users have been posted after #3294 was closed.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre4-rc3

Created a service with scale 3 with health check enabled .
Once all the containers of the service are healthy , upgrade the service with start first set to "true" and health_check_url to a non existent url so that the upgraded containers that get started are stuck in "Initializing" state.

At this state we don't see the the older containers being "stopped" .They continue to be in "Running" state.

Once the upgraded containers get to healthy state , the older container gets to "stopped" state.

**Comment by sangeethah** [comment]
There is 1 issue relating to attempting upgrades for batches even before the upgrade of the previous batch is done fully which is tracked in  https://github.com/rancher/rancher/issues/6340
