### ISSUE TITLE
Container not able to access Kubernetes API when access control is enabled (Github)

### ISSUE THREAD

**Issue by qamalbcgdv** [rancher/rancher#5854]
**Rancher Version:** 1.1.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu Xenial @ AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA Rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
- Enable access control with Github
- Create a Kubernetes environment
- Create a pod with curl access from inside container
- Create a service account (or use the default)
- Hit the kubernetes API endpoint (e.g: https://rancher.example.org/r/projects/1a2/kubernetes/api)

**Results:** 
- You get an error because you are not logged in to github

**Expected:**
- You should be able to hit the API with a service account

I have a use case where I am using the Fluentd forwarder to aggregate the container logs. The Fluentd Kubernetes plugin requires access to the Kubernetes API in order to fetch metadata associated with the logs. When disabling access control this works fine and the container is able to fetch metadata from the Kubernetes API using the provisioned service account.

**Comment by alena1108** [comment]
@qamalbcgdv Rancher Auth is not integrated with kubernetes Authentication within the cluster (yet). 

To access k8s api service from the pod today, it has to be done via its cluster ip as per http://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod. K8s does authenticate the request as per http://kubernetes.io/docs/admin/authentication/, "Service Account Tokens". 

The example of curl request:

```
curl -v -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.43.0.1:443 --insecure
```

Static Ip is used in the request instead of "kubernetes" resolvable name due to the bug in dns resolution for system kubernetes cluster ip service (it gets resolved to ip address of the container instead of cluster ip, and port 6443 is open on the container vs port 443 being open for the cluster ip). You can retrieve this static ip  via the environment variable below

```
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
```

DNS resolution bug fix is https://github.com/rancher/rancher/issues/6190

Hope that helps

**Comment by wlan0** [comment]
@qamalbcgdv I tested this with both a named service account and the default one. 

I setup github auth and then started two pods, one with service account and one default. 

In rancher/k8s:v1.5.1-rancher1-1, this command
```
curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.43.0.1:443
```

works just fine. 

This version of kubernetes will be available from Rancher 1.3 onwards.

**Comment by galal-hussein** [comment]
@wlan0 I tested on Rancher server master build, and on rancher/k8s:v1.5.1-rancher1-1 i started a pod with default service account and tried to access the api:

```
$ curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.43.0.1:443
Unauthorized
```

**Comment by alena1108** [comment]
@galal-hussein do not use default service account; use the custom created one. K8s api server regenerates default account on restart, so after that pod has to be restarted. Try with the custom account, and see how it goes.

**Comment by galal-hussein** [comment]
Rancher version: master build
kubernetes: rancher/k8s:v1.5.1-rancher1-2

I was able to authenticate with a custom service account even with Github authentication is enabled, i wasn't able to authenticate with the default service account at first which appears to be a kubernetes problem:

https://github.com/kubernetes/kubernetes/issues/22351

And by following the workaround (deleting the invalidated secret for the default account) that is mentioned in the bug above solved the problem.
