### ISSUE TITLE
Document secrets-bridge for K8s usage.

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#5903]
In a k8s environment, you'll need to deploy the agents as a system-stack using Cattle. 

https://github.com/rancher/community-catalog/tree/master/templates/secrets-bridge-server and https://github.com/rancher/community-catalog/tree/master/templates/secrets-bridge-agents

**Comment by sangeethah** [comment]
Following line needs to be fixed in documentation - 
https://github.com/rancher/secrets-bridge/blob/master/docs/setup.md

In Step 3: Set script variables section:
env variables ```VAULT_ADDR``` should be renamed to ```VAULT_URL``` since this is the one being referenced in the later steps

In Step 4: Create grantor-default role section:

command has typo for env variables being used.It should be as follows:
```
curl -X POST -H "X-Vault-Token: ${ROOT_TOKEN}" -d '{"allowed_policies": "default,grantor-default,app1,app2"}' ${VAULT_URL}/v1/auth/token/roles/grantor-default
```

secrets-bridge-server template does not expose 8181 which needs to be exposed for secrets-bridge-agents to contact secrets-bridge-server. So we need to have LB service that will make this port available as exposed port on the host.

**Comment by cloudnautique** [comment]
Load balancer has been added to catalog entry in rancher/community-catalog#281

**Comment by sangeethah** [comment]
1. ```export RANCHER_ENVIRONMENT_API_URL=http://xxx.xxx.xxx.xxy:XXXX/v1/projects/YYY``` is not needed in "Step 3: Set script variables" section. Instead it should be moved to "Configure Secrets Bridge Server" -> command line section.

2. In "Configure Secrets Bridge Agents"-> "Kubernetes" section , option B ,step 3 contents need to be changed to be more specific.
only docker-compose file of secrets-bridge-agent catalog entry is needed.Need to manually change "${BRIDGE_URL}" variable to LB url that was created exposed for Secrets Bridge Server.

**Comment by sangeethah** [comment]
@cloudnautique: Can we document the expiry time (1 hour) for Temp token and the time user has (5 minutes) to create Temp token using the generated scerets.txt once the container is launched?

**Comment by cloudnautique** [comment]
added in rancher/secrets-bridge#20.

**Comment by sangeethah** [comment]
Latest version of https://github.com/rancher/secrets-bridge/blob/master/docs/applications.md includes information about expiry times for Temp token and Permanent token.
