### ISSUE TITLE
Failed to create compute

### ISSUE THREAD

**Issue by nazar-pc** [rancher/rancher#593]
I have Rancher on host + virtual machine with docker also.
I've connected docker inside VM to Rancher, started 2 Nginx instances from official image `nginx`, created LB, everything looks good and works fine.

Then I've started agent on host, the same physical machine where Rancher server is running. It started and connected without issues. Then I've tried to run Nginx instance from the same image in the same way as inside VM (just name and image, everything by default), Network Agent started fine, but Nginx instance stuck at creation for a long time and finally Rancher crashed (after this server was restarted according to `docker ps`, so it crashed whole Rancher). After Rancher restored I saw that contained failed to run because Rancher failed to create compute, and this is at the top of container page now:
> Stopped
> : e3dc5555-60b9-49fc-ab4f-86837065eaed : ('Connection aborted.', error(111, 'ECONNREFUSED'))

While agent still online and Network Agent is working on it.
Here is what is in `docker logs rancher-server`: http://pastebin.com/NyZpMDAP
Also, I do not see any container being created from `nginx` image neither in progress, nor after it eventually failed to start.

This happens consequently, I can't create `nginx` container on the same host where Rancher server is running.

**Comment by nazar-pc** [comment]
Both host and VM are Ubuntu 15.04 x64 with latest updates, so, they should be identical from software side.

**Comment by bscott** [comment]
@nazar-pc What version of Rancher?

**Comment by nazar-pc** [comment]
0.16.2

**Comment by deniseschannon** [comment]
@nazar-pc When you start agent on the same host as Rancher server, you'll need to make sure that you add `-e CATTLE_AGENT_IP=<ip_of_server>`. Otherwise the agent ends up picking the wrong IP. This is a known issue when adding agents on the same host as server and the known workaround. 

Can you try this workaround and see if you are still having issues?

**Comment by nazar-pc** [comment]
Sorry for very long delay.
Just tried what you said with cached images from that time - didn't appear in hosts dashboard at all.
Pulled fresh images, removed old `rancher` directory from `/var/lib`, started server - now dashboard is not accessible because of error in `bower_components/ember/ember.prod.js:24186`, can't check anything.
Current server image is `latest` as for now namely `c4466cf0a719`

**Comment by vincent99** [comment]
That line in what should be the version of the UI `latest` loads is related to the URL that was requested not existing.. are you going to a particular path instead of the root of `http://ip.of.rancher.server:8080/` ?  The names of things and their corresponding paths change sometimes between versions and the UI apparently doesn't show a useful message, especially if it is the initially loaded URL (https://github.com/rancher/rancher/issues/1506).
