### ISSUE TITLE
Stack upgrade problem with volumes-from and host scheduling

### ISSUE THREAD

**Issue by ahoeg** [rancher/rancher#5938]
**Rancher Version:**
v1.1.3

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 0.6.1-rc1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
upgrade a stack with sidekicks

**Results:** 
container moves to another host and volumes-from setting lost sometimes

**Expected:**
 upgrade shouldn't break volumes-from / host scheduling

**Comment by tfiduccia** [comment]
Volumes-from setting lost on upgrade has been fixed in Version - v1.2.0-pre2.  bug #3914.  

Also to ensure your containers go to the same host, you have to set the Run all containers on a specific host.  Did you set that in the scheduling tab of the service?  I've tried multiple times to recreate your host issue in 1.2.0 bug am unable to.

**Comment by pwFoo** [comment]
Yes, but host scheduling lost / changed during upgrade. I'll test it with the pre version. Thanks

**Comment by ahoeg** [comment]
Yes, but host scheduling lost / changed during upgrade. I'll test it with the pre version. Thanks

**Comment by aemneina** [comment]
@ahoeg if you can reproduce this on a 1.2.x version please reopen.
