### ISSUE TITLE
User is unable to login after changing password to consist of only blank spaces

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#5973]
**Rancher Version:**
v1.1.3, v.1.2.0-pre2

Steps:
1. Login with Local Auth
3. Change password to be a single or more blank spaces ` `
4. Logout and try to login again

Results:
User is unable to login into his account, both using the new or the previous password.

Expected:
1. User should not be allowed to change password to consist of only spaces. When passwords are created or changed they should be validated against a policy that specifies password length and composition.
2. Changing the password should not break authentication

**Comment by vincent99** [comment]
I don't know if there's still anything to do here, but please make sure leading/trailing spaces are either trimmed or preserved consistently on set/change/use password.

**Comment by loganhz** [comment]
There is no `trim` in UI side. Server side rejects the `blank` password when create a user. But server side doesn't reject  `blank` password when edit the password.

@mrajashree May I know why you closed your [PR](https://github.com/rancher/cattle/pull/2196) ? It looks your PR would fix this issue.

**Comment by yasker** [comment]
@mrajashree ? ^^

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
We shouldn't allow spaces anywhere in password.  So if leading or trailing, should be trimmed out.  If in middle should fail.   This is not fixed

**Comment by vincent99** [comment]
What?  No.  Space is a perfectly cromulent character that has to be allowed in the middle of a password.

Trimming the ends is arguable, it's "wrong" but user-friendly.  You could trim both ends for `local` auth, as long as it's applied on login, change password, and set password consistently.

You _cannot_ just trim spaces on a other providers like LDAP because the user's password in that system might start or end with one.  (If you want to be fancy you can trim, try that, then retry the original string if it failed)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
I can still change my password to all spaces and I cannot log in after I do that.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/7
Verified fixed
