### ISSUE TITLE
Service requires "kick" to update active when servers return to "Active" state from "Reconnecting"

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#6013]
**Rancher Version:** 1.1.3

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Start a long-running service with the scheduling policy of "Run on all hosts matching the following label" and pick a label that matches some hosts, and responds to a health check.
2. Sever the network connection to a host or peg its CPU to vCPU \* 100%, making the agent and container with its health check unreachable. Let the health checks kill the container on the host.
3. Restore the network connection to a host, the IP shouldn't have changed on reconnect.

**Results:** 

Service does not update and start a container for the service on the host. Host looks like this:

![screen shot 2016-09-20 at 10 20 10 am](https://cloud.githubusercontent.com/assets/12628715/18675443/5bce87bc-7f20-11e6-856a-397e7647d390.png)

**Expected:**

Service should update on the newly available host.

**Workaround:**

I can "kick" the service into gear by manually deactivating the host, then reactivating it right away.

**Comment by schuylr** [comment]
Reproduced the same issue in v1.2.0-pre3 now:

![screen shot 2016-09-20 at 2 27 32 pm](https://cloud.githubusercontent.com/assets/12628715/18683468/6c0c9754-7f3e-11e6-9fc0-7bc0141e7679.png)

Service Journal for the service in question on this one:

![screen shot 2016-09-20 at 2 28 44 pm](https://cloud.githubusercontent.com/assets/12628715/18683515/9900156a-7f3e-11e6-900b-ae51e6c182eb.png)

![screen shot 2016-09-20 at 2 28 53 pm](https://cloud.githubusercontent.com/assets/12628715/18683523/9fb3ac32-7f3e-11e6-8f71-e9af19bbe4e2.png)

**Comment by sangeethah** [comment]
Tested with latest build from master and using rancher/healthcheck:v0.1.0. 

Had a global service with health check enabled instances.

Brought down network on one of the hosts , so that it goes to "reconnecting" state.
Health check enabled instance is found unhealthy and marked for removal.
After sometime , restore connectivity on this host.

When host state transitions to"active" , we see the health check instance start successfully on the host.

@schuylr, this fix will be available in rancher-server 1.2 release.
