### ISSUE TITLE
create method for bootstrapping environments without UI interaction

### ISSUE THREAD

**Issue by flypenguin** [rancher/rancher#6034]
**Rancher Version:**
all up to & including 1.1.x and probably 1.2.x

**Docker Version:**
N/A

**OS and where are the hosts located? (cloud, bare metal, etc):**
N/A

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
Take 3 hosts. Install rancher master on host 1. Install Rancher Agent on hosts 2 & 3. 

**Results:** 
Currently you have to go into the Rancher UI to get the actual docker run command with the appropirate parameters to register the agents in rancher in the correct environment. So there is a manual step involved.

**Expected:**
It would be nice to pre-define a secret key or something with which you could do something like ...
- `docker run -e ACCEPT_KEY=abcdef rancher/server` (on host 1)
- `docker run -e RANCHER_ENV=myenv1 -e RANCHER_KEY=abcdef rancher/agent` (on host 2)
- `docker run -e RANCHER_ENV=myenv2 -e RANCHER_KEY=abcdef rancher/agent` (on host 3)
  ... which would automatically install the rancher master, register the two agents at the master, and create the environments "myenv1" and "myenv2" in the process. 

This way you can bootstrap everything up to and including all Rancher installations and environments from one simple file (e.g. cloudformation stack file)

The shared key is just an idea. Whatever works is fine, as long as the result is a full bootstrap :)

**Comment by bacheson** [comment]
+1 ... same with removing hosts so I can take advantage of autoscale

**Comment by aemneina** [comment]
I'm pretty sure you can automate anything the UI can do. It sounds like you want to be able to add hosts on demand, if thats the case, take a look at http(s)://rancher-uri/v1/registrationTokens. That should have the registration command used to add hosts to your deployment.

**Comment by flypenguin** [comment]
yes, but the point is that I do *not* want to do anything with the rancher UI *or* API basically, because that really complicates deployment processes . Without Rancher interaction I could do this (on AWS) with a very basic CloudFormation template, but if I need to trigger URLs I then need to write a complicated init script, which is prone to errors and is probably not very flexible.

**Comment by skyscooby** [comment]
+1 on this.. it's very important for DevOps (the people you are targeting with this product) to be able to stand up a product without UI interaction. It should also be possible configure the system via a configuration file or ENV vars.. (including LDAP setup, initial admin credentials, initial environments etc).. Also I'd like the option to startup with a Kubernetes 'Default' environment instead of Cattle.

I don't mind waiting for the master to come up first to retrieve the registration token but a convenience endpoint would be nice as currently with many environments you first need to figure out what the 'internal' ID is for that environment to get the correct node in the registrationTokens endpoint..   The suggested declarative way to set the authentication token would be even easier as you can fire and forget your configuration and once the master comes up the nodes will register automatically.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
