### ISSUE TITLE
Upgrade to docker-machine v0.8.2

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#6087]
**Rancher Version:** v1.2.0

Please upgrade to latest docker-machine release before releasing Rancher v1.2.0. Thanks!

**Comment by jloisel** [comment]
0.8.2 has been released:
https://github.com/docker/machine/releases/tag/v0.8.2

**Comment by vincent99** [comment]
As you've probably already seen we can't just upgrade the binary and call it a day because there are major backwards incompatible differences between most 0.x versions. Azure was completely changed between 0.6 and 0.8, are is unusable because they have no way to do auth with api keys (vs console interactive and using a browser)..

Options for that were added by Microsoft into master and 1.2-pre3 already includes a build from master for that.  But it contains a fairly bad credential sharing problem for our use-case ( https://github.com/docker/machine/issues/3782 ), which is now also patched in master.  None of this is in 0.8.2, so for pre4 we will include in updated build from whatever looks like the best commit after there ones we need.

**Comment by jloisel** [comment]
Great, thanks Vincent for the explanation :+1: 

Any updated version is fine for me. As long as it contains the most important fixes for Amazon EC2.
