### ISSUE TITLE
Rancher Client does not read self signed certs

### ISSUE THREAD

**Issue by warroyo** [rancher/rancher#6122]
**Rancher Version:**

agent: 1.0.2
server: 1.1.4

**Docker Version:**
1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**
centos7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA cluster with 3 nodes

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

I am seeing an issue when using a self signed cert and trying to provision a kubernetes environment. When starting the Kubernetes services the ingress_controller is failing with `level=fatal msg="Failed to create Rancher client Get https://myrancher.com/v1: x509: certificate signed by unknown authority"` 

i have configured the agent's `/var/lib/rancher/etc/ssl/ca.crt` to have the correct cert to trust. I am only seeing this issue when the ingress controller is trying to start up.

is there a way for it to be trusted?

**Comment by wlan0** [comment]
@warroyo thanks for reporting this issue.

Unfortunately, this issue is the symptom of a bigger issue. Our rancher api client library `rancher/go-rancher` does not read self-signed certs. The `ingress-controller `uses this library to talk to `rancher/server`. We'll be using this github issue to track progress on self-signed cert support for rancher-api client, and subsequently all of the microservices (including `ingress-controller`) that use it.

**Comment by cjellick** [comment]
As @wlan0 stated, this affects all our microservices that communicate with the rancher API. The rancher-agent should work because we have logic in [run.sh](https://github.com/rancher/rancher/blob/master/agent/run.sh), but I haven't explicitly confirmed this.

To fix, we'd need to develop a generic routine for inject the self-signed certs into the containers and then to configure them as part of the OS store.

**Comment by wlan0** [comment]
@cjellick, do we need to configure it as a part of the OS store? Doesn't that make it less secure? 

We could just read the certs from go-rancher using this - https://gist.github.com/michaljemala/d6f4e01c4834bf47a9c4#file-tls-client-go-L37

**Comment by cjellick** [comment]
Yep, that looks like it'll work. Didn't really put much thought into details of the solution. Thanks

**Comment by alena1108** [comment]
@StrongMonkey 

> As @wlan0 stated, this affects all our microservices that communicate with the rancher API. The rancher-agent should work because we have logic in run.sh, but I haven't explicitly confirmed this.

Could you double check if our rancher-agent works with self signed cert?

**Comment by deniseschannon** [comment]
All infra services were updated in the v1.3.0-rc2 branch with updated images for this issue.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.3.0-rc2 using self signed certs.

rancher-server is started with the following command - ```sudo docker run -d --restart=unless-stopped --name=rancher-server -v /root/nginx/ssl/test1.com.crt:/var/lib/rancher/etc/ssl/ca.crt rancher/server:v1.3.0-rc2```

It is hosted behind nginx server that acts as a reverse proxy.

On the host , certs have to be copied to /var/lib/rancher/etc/ssl/ca.crt before running the host registration url which will already include ```-v /var/lib/rancher:/var/lib/rancher```

Able to add hosts successfully to "cattle" environment.
Able to get all the infrastructure stacks to start successfully.

Able to add services with health check enabled and they get to "healthy" state.
