### ISSUE TITLE
Refresh issues with Machine Driver page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6184]
**Rancher Version:** v1.2.0-pre4-rc2

**Steps to Reproduce:**  All these problem resolve themselves if you refresh screen.

- [x] With custom drivers, shows two first time you activate it.
![image](https://cloud.githubusercontent.com/assets/11514927/19172857/f5aab8a0-8bd8-11e6-82d1-428ba351073e.png)

- [x] With custom drivers, deactivating then removing driver will show two.
![image](https://cloud.githubusercontent.com/assets/11514927/19172846/e1ce7902-8bd8-11e6-8d04-4fd55c8ab92e.png)

- [x] Removed Drivers don't go away
![image](https://cloud.githubusercontent.com/assets/11514927/19172735/44717fe2-8bd8-11e6-99ff-092bfa9a9ff7.png)

- [x] Adding/removing catalog that has machine drivers won't show drivers.

**Comment by SoreGums** [comment]
I attempted to update the vultr machine driver and it kind of worked (removed the old driver, added a new one with the new url/checksum)
rancher appeared to save the new url, however it kept using the old url to actually do anything.
there was only one driver present in the UI, however looking at the logs it was clear the previous version was being used. so deleted the new one and the old one showed up again as inactive.
I was following #5119 as it best describes what I was seeing.

This new issue is a bit confusing because refreshing the screen didn't resolve anything

> All these problem resolve themselves if you refresh screen.

**Comment by tfiduccia** [comment]
@SoreGums 
What version of Rancher are you using.  We made changes to machine drivers in the last couple of days and 1.2.0-pre4 will fix a lot of problems.

That being said - Even in the newest code, if you remove a machine driver that we provide, it will always come back.  They are stored in our catalog and that catalog will be re-read on refresh/and or change event.  But you should still be able to deactivate our vultr driver, add your own and activate it.  It should look like you have two (ours which is deactivated and your which will be active.)

**Comment by SoreGums** [comment]
It was about 2-3 weeks ago.
I just gave up and focused on other things I need to do first.
I am getting close to wanting to provision vultr machines again so will take a look again next week - cheers

**Comment by westlywright** [comment]
@tfiduccia I have addressed all issues except the last one `Adding/removing catalog that has machine drivers won't show drivers.` I am unable to reproduce this issue with Rancher UI master and Rancher Server master. Was there a special case to fall into this or was the issue related to a backend change?

**Comment by tfiduccia** [comment]
Version - master 10/19
Verified fixed
