### ISSUE TITLE
RestartPolicy not being passed to docker (i.e. restart=always)

### ISSUE THREAD

**Issue by patsissons** [rancher/rancher#6290]
**Rancher Version:** 
`1.1.4`

**Docker Version:** 
`1.12.2`

**OS and where are the hosts located? (cloud, bare metal, etc):** 
`Ubuntu 16.04.1 LTS`

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a stack on a docker node with a container configured to `restart: always`
1. Shutdown rancher host & docker node
1. Startup docker node only

**Results:** 
* container configured with `restart: always` does not start with node host boot

**Expected:**
* container should autostart according to the restart policy configured

**Notes:**
Once the rancher host is started the container will start

---

For context, I am trying to use a `mysql` container on a rancher controlled docker node host for my rancher external DB. The problem is that rancher will not start properly if the mysql container is not started ahead of time. This is usually an easy fix by configuring a restart policy and controlling startup order of the hosts, but it seems rancher is not pushing that restart policy configuration to docker.

I can confirm that after I either create a service with the UI and setting *Auto Restart* to always or use a docker compose stack with a container configured as `restart: always`, neither configured container (upon `docker inspect`) shows the expected `RestartPolicy` configuration.

Is there a hidden way of doing this? I am currently remoting into the node host and using `docker update --restart=always <container_id>` as a workaround.

**Comment by vmozgovoy** [comment]
Same problem...

**Comment by vincent99** [comment]
The starting of service containers is managed by Rancher to ensure the correct scale, that other services litter metadata are available, etc.

Standalone containers set the Docker restart policy.

**Comment by oliverorav** [comment]
@vincent99 As I understand this is intended, but can cause some problems in the production.

For example, let's say that all of the hosts in production get updated and restarted automatically by Puppet or similar tool, but somehow Rancher doesn't come up (db fails, configuration error, whatever else). In current case that means also the containers that were running on the nodes, don't get restarted, because "they just don't know" that they should come up again. 

What do you propose for this kind of a case?

**Comment by vincent99** [comment]
TBH I'd start with worrying about the first-order problem that all your host are intentionally simultaneously being rebooted, apparently including the control plane, instead of worrying about the possibility of a second-order failure after that (control plane not coming back) causing a third-order one (containers don't restart because there's no control plane).

Automatically starting up old instances of containers when a host comes back up is dangerous.  You may not care about it for your use-case but some things require exactly-n running copies, could report in duplicate results, think it is the master when a new one has been elected already, etc.  Even for a stateless workload when it does connect back up to the control plane and the scale is now too high one of them now has to be killed off, but this instance has now needlessly started accepting connections that you now have to worry about draining, etc.
