### ISSUE TITLE
Memory data error?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#6398]
rancher 1.1.4
os ubuntu 14.04
docker 1.12.1
![image](https://cloud.githubusercontent.com/assets/3667080/19721052/3e6125a0-9ba3-11e6-9d26-d3c91139dd86.png)
![image](https://cloud.githubusercontent.com/assets/3667080/19721175/b92ca660-9ba3-11e6-869c-3044f71da307.png)

**Comment by jasonhillier** [comment]
I believe Rancher's memory usage graph is not accounting for linux disk cache. Try running:
#: free -h
             total       used       free     shared    buffers     cached
Mem:          2.0G       1.9G        75M       2.3M        66M       1.4G
-/+ buffers/cache:       387M       1.6G
Swap:           0B         0B         0B

I've noticed a similar issue and would like to see this excluded from the graph, or even better, shown as a separate color -- as the memory is technically free for programs to use.

**Comment by deniseschannon** [comment]
@Dreampie @jasonhillier Our container stats are changing in the next release of Rancher (v1.2.0) so that we are no longer relying on cadvisor and switching to `docker stats` for container stats. 

When using v1.2.0, if you are facing issues with container stats, then `docker stats` would be reporting it incorrectly.
