### ISSUE TITLE
Optimize allocation to do as little as possible if requestedHostId is set

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#6427]
Mainly an invisible backend change, but basically we wanted to short circuit as much logic as possible if requestedHostId is set. But the primary change is this: if requestedHostId is provided, even if a host is inactive or reconnecting, we should allow it to be scheduled. 

This is to prevent scheduling storms we can get into when hosts are rebooted or otherwise disconnected and reconnected.

**Comment by sangeethah** [comment]
Tested with rancher server version  - v1.3.0-rc1

1. Mark one of host to "Inactive" state.
Deploy service on this host. Containers get deployed successfully on this host.

2. Power down one of the hosts in the setup.
Wait for host to get to "reconnecting"
Deploy service on this host. 
Containers get stuck in "registering" state until the host gets to "disconnected" state. 
After this there is a continuos attempt to start container on the "disconnected" host which keeps failing.
 Service is stuck in  ```Activating (Expected state running but got removed)```

Wanted to get confirmation on this behavior?
Reopening this issue to get confirmation on the expected behavior in this case.


Also there is a related issue seen with any global health check enabled services - https://github.com/rancher/rancher/issues/7118.

**Comment by cjellick** [comment]
Questions:
1.  In scenario 1, how are you deploying a *service* to an inactive host? I don't think you should be able to do that.
2. In scenario 2, same basic question: how are you deploying a service to a reconnecting host?

**Comment by sangeethah** [comment]
@cjellick , UI allows for choosing hosts to run containers on when deploying a service (this has been there always). This list of host also includes host in "inactive"/"reconnecting" state.

<img width="1129" alt="screen shot 2016-12-20 at 8 13 14 am" src="https://cloud.githubusercontent.com/assets/4266958/21358127/998ae0ce-c68c-11e6-8ea9-463ed11260ff.png">

**Comment by cjellick** [comment]
Ok, didn't realize we exposed requestedHostId for services in the UI.
@vincent99 mentioned that he might filter out non-active hosts from that.
But yes, this is the expected behavior - we want to allow the instance to get passed scheduling step if that leads to a service flapping because the host is unreachable, then so be it. Prior to this change the service would have flapped the same way, but at the scheduling step.

**Comment by sangeethah** [comment]
Logged UI issue - https://github.com/rancher/rancher/issues/7147
