### ISSUE TITLE
Even when password validator fails , new account gets added

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6475]
Rancher version - Build from master
Set api.auth.local.validate.url to the password valiator url.
Enable local auth.
Add a new admin/user account.
Make password validator return a error code , so that password validator fails.
User is presented with an error message but the account still gets created.

Expected Behavior:
Account should not get created.

**Comment by mrajashree** [comment]
@vincent99 This bug is there even when the password validation service is disabled. It's not related to the password validation service, it's about the 2 API calls made while creating account, one to v2-beta/account and one is to v2-beta/password.

**Comment by cjellick** [comment]
The bug occurs because we make two separate API requests:
1. create the account
2. create the password (credential)

Create the account succeeds and returns a 201
Create the password fails with 422.

So, I think this bug falls into the grey area of bad API design because the UI is doing what it can and the backend is doing what it can.

The API could be fixed by combining the 2 API calls into 1 and causing credential creation to be kicked off as a subprocess of account creation, but to be honest, I think that is too big of a change to sneak into 1.2 at this point for a bug that has a relatively low impact and has a user work around.

A somewhat hackier fix could be added to the UI by explaining more clearly to the user that while the account was created, credentials for it were not. _Or_ by the UI deleting the account if the password creation fails. But these both feel hacky. What do you think @vincent99?

@deniseschannon can we bump this issue out of 1.2

**Comment by cjellick** [comment]
I guess the downside of this bug is that it is now potentially more prominent/likely to be hit because of the validation URL feature.

**Comment by cjellick** [comment]
Per the reference issue #6499, you can also see this behavior if the validation times out.

**Comment by mrajashree** [comment]
Adding to the previous comments, this problem exists even when adding Local Auth Access control since 2 API calls are made there as well
