### ISSUE TITLE
kubernetes submenu items are in a gigantic font size during setup

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6482]
**Rancher Version:** master 11/01

**Steps to Reproduce:**
1.  Create a kubernetes environment
2.  go to environment and add hosts
3.  Click on the kubernetes menu

**Results:** Notice the kubernetes submenu items are in a gigantic font size
![image](https://cloud.githubusercontent.com/assets/11514927/19911408/9df96854-a050-11e6-993d-a33d590a4e17.png)

**Expected:**  Should be regular size

**Comment by vincent99** [comment]
This is the style for `loading`, which gets put on broken links.. they weren't shown before because I don't know what namespace to link to yet, so I'm going back to that, with some improvement..

![image](https://cloud.githubusercontent.com/assets/753917/19958710/a73c74f6-a15e-11e6-8c89-025380bf73ac.png)

**Comment by tfiduccia** [comment]
version - 1.2.0-pre4-rc7 UI v1.2.20
Verified fixed
