### ISSUE TITLE
Catalog refresh called on (almost?) every get /catalog

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#6507]
please add details

**Comment by mrajashree** [comment]
Hitting any template to load template details from UI causes `INFO[2016-11-04T10:57:10-07:00] Refresh for this catalog community is already in process, skipping` to be seen in logs, since refreshCatalog was being called.
Loading template details should not call refreshCatalog. It causes delay in loading template details because of the `pullCatalog()` call in `refreshCatalog()`. This is not expected. 
There is no explicit way of reproducing this bug. But regression test to assert that the catalog is still refreshed on an interval is required.

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues/6388

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc7. Accessing any catalog does not display ```
INFO[2016-11-04T10:57:10-07:00] Refresh for this catalog <catalog_name> is already in process, skipping ``` in the logs.

The message ``` time="2016-11-09T18:45:06Z" level=info msg="Request to refresh catalog" ``` will be displayed when we add a new catalog URL to the admin settings page.
