### ISSUE TITLE
Rancher Compose Unable to Replicate Web UI Load Blancer

### ISSUE THREAD

**Issue by ppandy** [rancher/rancher#6516]
Rancher Version: 1.1.4
Docker Version: 1.10.3, build cb079f6-unsupported
OS Version: CentOS Linux release 7.2.1511 (Core), Bare Metal
Single Node w/ External DB
Environment Type: Cattle

Steps to Reproduce:
When deploying a multi-site host-header based LB Environment using the WebUI, everything works as expected. Reproducing with rancher-compose (v0.8.6) results in APIError: 500 Server Error, using the exact same configuration.

Results:
No containers are created. See Attached system-error.txt
[system-error.txt](https://github.com/rancher/rancher/files/572552/system-error.txt)

Expected:
Identical Stack Creation.

Notes:
When the second site host-header is removed, the replication works fine, so in some way the duplicative port 8080 is causing issues. Load Balancer configuration attached, with sample site configuration.

[rancher-compose-lb.txt](https://github.com/rancher/rancher/files/572559/rancher-compose-lb.txt)
[docker-compose-lb.txt](https://github.com/rancher/rancher/files/572560/docker-compose-lb.txt)
[docker-compose-site.txt](https://github.com/rancher/rancher/files/572561/docker-compose-site.txt)

**Comment by deniseschannon** [comment]
How are you confirming that it is the exact same configuration? Did you export the yaml of the stack and use that config in rancher-compose?

**Comment by ppfaWebtech** [comment]
Hi Denise:

Yes, that's why we were so surprised when it happened. I'm in the process of creating a Vanilla Stack with public docker images, so you guys can see it in action, but that's a day or so off.

We had originally used yaml, added a few bits in the UI, then copied/pasted back to yaml to rerun, and that's when it happened. It's easy to reproduce, though. We have multiple containers using an identical port internally (using EXPOSE), nothing in yaml, and they seem to collide.

**Comment by vincent99** [comment]
Please comment or reopen if this is still relevant to a modern version.  Port rules and everything else in general are significantly different since 1.1
