### ISSUE TITLE
[UI] french translation too formal :(

### ISSUE THREAD

**Issue by xinity** [rancher/rancher#6517]
taking a closer look at latest french translation of rancher.
i've spotted many translations which are too formal or even worse google translating.
that's somehow the weak spot of crowdin i think.

How can we update the french translation to make it more accurate and less formal and make these changes persistent ?

i'd be happy to give another hand on this matter :)

**Comment by vincent99** [comment]
Since we don't generally speak the languages and they come from a smallish number of people we more or less just accept anything put in.  Changes made on CrowdIn are periodically synched with the UI repo.  With enough people watching a particular language I think there are voting and trusted maintainers and other sorts of tools that become useful.

So you can make changes and they will make their way in, usually at the beginning and end of a release cycle (though the current one is particularly long...).

**Comment by aemneina** [comment]
@xinity closing this out, if you have any more questions please do reopen.
