### ISSUE TITLE
Upgrade from catalog issue

### ISSUE THREAD

**Issue by saphoooo** [rancher/rancher#6536]
**Rancher Version:**
rancher/server:v1.2.0-pre4-rc6
**Docker Version:**
Docker version 1.12.1, build 23cf638
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.7.0 on AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4 qa
**Steps to Reproduce:**
create a new version of a catalog entry, with new container image in rc, upgrade to the new version.
**Results:** 
still saying that the current version is the old one. Upgrade available is still present. But if I delete pods containing new container version, new created pods have the right version for they container.
**Expected:**
rolling-update or new configuration, I don't know which feature is used by an upgrade from the catalog.

**Comment by deniseschannon** [comment]
@soumyalj When k8s is back up and running, can you test this use case?

**Comment by saphoooo** [comment]
I noticed that in v1.2.0-pre4-rc7 catalog is broken and I cannot deploy anything from there

**Comment by deniseschannon** [comment]
@saphoooo v1.2.0-pre4-rc7 does not work out from the box.

From @vincent99 in a different issue:
"RCs are intended for use by us for our QA. There is no guarantee they work at all, will upgrade from previous versions, or support upgrading to future versions. Anybody that isn't developing our testing in a throwaway installation should be using an actual release, or at least a -preX (with no -rcY).

And those non-guarantees are specifically true in this RC cycle, the current build does NOT upgrade existing environments completely, and may not be cleanly upgradeable to 1.2.0-pre4/1.2.0.

All the services previously provided by the Network Agent are being split into separate catalog items to support things like alternate networking implementations. And those catalog items are in the 1.2 branch of rancher-catalog because it is not released yet, so you need to change the catalog to point there to use them in the RCs."

**Comment by saphoooo** [comment]
ok, good to know. however, I use rc6-7 and qa catalog because I want to use K8s 1.4 to run last version of fabric8. so thank you.

**Comment by aemneina** [comment]
sounds like youre good here @saphoooo I'll go ahead and close this out. If I missed something key, feel free to reopen.

**Comment by aemneina** [comment]
actually, looks like this might be for QA to validate before closing, reopened the issue.

**Comment by soumyalj** [comment]
Tested with upgrade from rancher 1.1.4 to 1.2.0-pre4-rc15 and from 1.2.0-pre3 to 1.2.0-pre4-rc15. After upgrading Kubernetes environment, "Upgrade available " option was shown to upgrade Kubernetes to 1.4.6. Upgrade to Kubernetes 1.4.6 was successful.
