### ISSUE TITLE
Failed to find network for networkMode managed

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#6573]
**Rancher Version:**
v1.2.0-pre4-rc7

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upgraded from v1.2.0-pre4-rc5 to v1.2.0-pre4-rc7

**Results:**
Some containers cannot start and am getting an error as follows:

`Failed to allocate instance [container:1i78308]: Bad instance [container:1i78308] in state [removed]: Failed to find network for networkMode managed`

**Expected:**
Containers should start normally

**Comment by mccricardo** [comment]
Experiencing the same issue with a similar setup, but on Ubuntu 16.04.

**Comment by ruzarowski** [comment]
Same here, HA Setup is broken when upgrading from rc6 because of same issue.

**Comment by danielpalstra** [comment]
Also experiencing the same issue with  v1.2.0-pre4-rc7 on CentOS 7. Als see the following error when using a LB in combination rancher-compose version v0.11.0-rc6

ERRO[0000] Failed Creating weblb : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=lbConfig, baseType=error, code=MissingRequired] from [http://rancher.*****l/v2-beta/loadbalancerservices] 
ERRO[0000] Failed to start: weblb : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=lbConfig, baseType=error, code=MissingRequired] from [http://rancher.****/v2-beta/loadbalancerservices] 
FATA[0000] Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=lbConfig, baseType=error, code=MissingRequired] from [http://rancher.****l/v2-beta/loadbalancerservices] 

Maybe related?

**Comment by vincent99** [comment]
RCs are intended for use by us for our QA.  There is no guarantee they work at all, will upgrade from previous versions, or support upgrading to future versions. Anybody that isn't developing our testing in a throwaway  installation should be acting an actual release, or at least a -`preX` (with no `-rcY`).

And those non-guarantees are specifically true in this RC cycle, the current build does NOT upgrade existing environments completely, and may not be cleanly upgradeable to 1.2.0-pre4/1.2.0.

All the services previously provided by the Network Agent are being split into separate catalog items to support things like alternate networking implementations.  And those catalog items are in the `1.2` branch of `rancher-catalog` because it is not released yet, so you need to change the catalog to point there to use them in the RCs.
