### ISSUE TITLE
[Question] How to install k8s1.4.6 on rancher 1.1.4

### ISSUE THREAD

**Issue by andreimc** [rancher/rancher#6635]
**Rancher Version:**
 1.1.4

**Docker Version:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare-metal Centos 7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA mode

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

I can't install kubernetes as it stands due to a bug that causes k8s kublet and proxy to fail.

I am just wondering how do I modify the containers that the kubernetes stack launches on my stack?

Can I fork the rancher-catalog update the versions under kubernetes or k8s ? then change environment to k8s ?

Would that use my config if I disable the rancher-catalog ?

**Comment by deniseschannon** [comment]
Before I start, I want to state that only k8s 1.2.4 has been tested and verified working on Rancher 1.1.4. Rancher 1.1.4 also has not been verified to be working with Docker 1.12.x series. IWe recommend  There are potential Rancher specific fixes that have been put in later versions of Rancher that may not be fixed in 1.1.4, which is why even changing the kubernetes versions does not guarantee success.

You could fork the rancher-catalog, update the templates in the kubernetes folder (this is where 1.1.4 is pulling from) , make sure minimum rancher version is updated correctly in rancher-compose.yml, and update for `library` -> your fork.

**Comment by andreimc** [comment]
@deniseschannon thanks I have moved to v1.2.0-pre4-rc7 now. k8s seems to work fine on this one.

I was quite close of getting k8s 1.4.6 running on 1.1.4 but got into a snag where something was requesting v2-beta api. More things documented here:
https://forums.rancher.com/t/help-installing-k8s-1-4-on-rancher-1-1-4/4623



The only thing with v1.2.0 + is that HA install does not work :( but I can live with that for a while. :)

So as far as I can tell rancher 1.1x is pulling from kubernetes folder and rancher 1.2 + from k8s folder.

It's making more sense now 👍 thanks for very quick responses and all the guidance.
