### ISSUE TITLE
web socket error on the ui

### ISSUE THREAD

**Issue by mwaaas** [rancher/rancher#6707]
Getting this error on the ui

ember.prod.js:497 WebSocket connection to 'ws://server.rancher.3b180629.svc.dockerapp.io/v2-beta/projects/1a5/subscribe?eventNames=resource.change&eventNames=service.kubernetes.change&limit=-1&include=hosts&include=services&include=instances&include=instance&include=instanceLinks&include=ipAddresses&sockId=22' failed: Error during WebSocket handshake: Unexpected response code: 200

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre3` Cattle: `v0.169.5` UI: `v1.2.11` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by aemneina** [comment]
@mwaaas Is your rancher server behind a firewall or other networking appliance? Typically you see this when said appliance is preventing upgrading connections from http to websocket.

**Comment by mwaaas** [comment]
@aemneina I don't think so, I have just run the following docker-compose command:

db:
  environment:
    - MYSQL_DATABASE=cattle
    - 'MYSQL_PASSWORD=9118z2*9I6&746C6'
    - 'MYSQL_ROOT_PASSWORD=9118z2*9I6&746C6'
    - MYSQL_USER=cattle
  image: 'mysql:5.5'
server:
  environment:
    - CATTLE_DB_CATTLE_MYSQL_HOST=db
    - CATTLE_DB_CATTLE_MYSQL_NAME=cattle
    - CATTLE_DB_CATTLE_MYSQL_PORT=3306
    - 'CATTLE_DB_CATTLE_PASSWORD=9118z2*9I6&746C6'
    - CATTLE_DB_CATTLE_USERNAME=cattle
  image: 'rancher/server:v1.2.0-pre3'
  links:
    - db
  ports:
    - '80:8080'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'

**Comment by aemneina** [comment]
what web browser were you using when you noticed this?

**Comment by mwaaas** [comment]
@aemneina chrome

**Comment by cjellick** [comment]
@mwaaas Can you try again with the rancher/server:v1.2.0 release?

**Comment by vincent99** [comment]
@nut-abctech A `200` status means the Connection and/or Upgrade headers aren't making it to the backend, so it just returns OK when sent an otherwise normal looking GET request instead of `101 Switching Protocols`.  Your config does not match our current [suggested nginx config](https://docs.rancher.com/rancher/v1.3/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration), it looks like a variant of a very old one (because `x-api-request-url` is present).
