### ISSUE TITLE
Secrets architecture

### ISSUE THREAD

**Issue by mccricardo** [rancher/rancher#6793]
We're currently exploring the usage of **secrets-bridge** with Vault. The advisable architecture can be found [here](https://github.com/rancher/secrets-bridge/blob/master/docs/setup.md#architecture).

Regarding this architecture we have a few questions:

* should Vault be running:
  * in Rancher and if so:
    * should it be running on it's own Rancher server;
    * can be run on the same one, but in a another environment;
  * outside Rancher, in another managed environment;
* should secrets-bridge be running:
  * on another environment, within the same Rancher server;
  * on it's own Rancher server.

What is advisable and why?

This question was asked previously on the [forum](https://forums.rancher.com/t/secrets-architecture/4651) but was reposted here because there was no progress.

**Comment by vincent99** [comment]
1.4 will have a first-class secrets interface and not require secrets-bridge, defaulting to storing secrets encrypted in the Rancher DB.  Vault will be another storage option.

If you want Vault it should be running outside of Rancher's control, otherwise you are not really getting the benefit of all the added complexity.
