### ISSUE TITLE
Not able to launch swarm cluster with Rancher 1.2.0.-rc2

### ISSUE THREAD

**Issue by jolly2** [rancher/rancher#6845]
**Rancher Version:**
 rancher/server:v1.2.0-rc2
**Docker Version:**
Docker version 1.12.2,
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 xenial LTS -- bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm
**Steps to Reproduce:**
Create a swarm environment. Add a host
**Results:** 
Swarm CLI
 Shell: swarm-swarmkit-mon-1
Error: TypeError: Cannot read property 'set' of undefined
**Expected:**
Swarm should be deployed without error

**Comment by vincent99** [comment]
The underlying issue is that the hosts swarm is running on need to be registered to rancher with a private IP address (RFC1918, 10.*, 172.16-31.*, or 192.168.*) because Docker 1.12 does not support swarm on public IPs.  This is fixed in Docker 1.13, but for now you need to use private IPs for it to come up.

Separately, the UI issue that the page blows up when swarm isn't fully up (because of above) will be fixed in the next build.

**Comment by soumyalj** [comment]
Tested with 1.2.0-rc4. Swarm cluster creation was successful. Creation of containers was fine too.
