### ISSUE TITLE
"Almost there...waiting for agent connection"

### ISSUE THREAD

**Issue by longwuyuan** [rancher/rancher#6848]
**Rancher Version:** = v1.1.4

**Docker Version:** = Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):** = All hosts AWS VPC Public Subnet

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** = Single Node Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** = Kubernetes

**Steps to Reproduce:** 
(1) Create a single RancherOS Server in AWS VPC Public Subnet
(2) SSH to server and start rancher-server docker container
(3) Connect to port 8080 of server in browser and change Admin-->Access Control to local user/password
(4) Change Server Settings to http://IP-Address-of-VPC-Public-Subnet-Interface instead of Public-IP
(5) Add new Kubernetes Environment and make it default.
(6) With Kubernetes as default Environment, add host
(7) Choose to add default Ubuntu AMI in same VPC-Public-Subnet in AWS ap-southeast-1
(8) Choose all default options except AWS credentials and name for server
(9) rancher-security group is configured to allow tcp-22, tcp-2376, udp-4500, udp-500 from 0.0.0.0/0 and all-traffic from the CIDR of internal-public-subnet .

**Results:** 
(1) It works until agent has to connect back to server at http://internal-ip-address-of-server:8080
(2) Then it is just stuck there even if I leave it overnight
(3) I have tried a few changes to security-group after reading https://github.com/rancher/rancher/issues/4246 but in my case both the rancher-server and the host I am adding are in my own AWS VPC using the same internal-ip-subnet

**Expected:**
(1) I hope I don't have to open security-group rules to 0.0.0.0/0 .
(2) I hope the host agent can register and my environment works
(3) I am a first-timer on Rancher & Kubernetes so hope I am not wasting other people's time

**Comment by vincent99** [comment]
Nothing *needs* to be exposed to 0.0.0.0/0, but allowing all from any is a simple way to make sure that firewall rules are what's making it not work and not something else..

The 2 main communication flows are:

- From the `rancher/agent` on each host to the registration URL, which is 8080/tcp unless you changed otherwise.  Agents connect out to the server, not vice versa.  If the agent can't reach the server it's never going to register, so this is the first problem to look at.  You should be able to `curl http://server:8080/v1` on a host and get back JSON

- From each host to every other host in that rancher environment on 500/udp and 4500/udp.  Once they're registered, hosts connect to each other on these to enable containers to talk to each other across hosts.  If this isn't working then containers will start but may not work (because they need to talk to others) or healthchecks will fail (they run on other hosts).

**Comment by longwuyuan** [comment]
Much thanks. I get JSON on internal but blackhole when using public-ip. I can privately provide access if needed.
admin@ip-10-10-10-9:~$ curl -i http://52.74.153.231:8080/v1
^C
admin@ip-10-10-10-9:~$ curl -i http://10.10.10.10:8080/v1
HTTP/1.1 401 Unauthorized
Content-Length: 158
Content-Type: application/json; charset=utf-8
Date: Wed, 30 Nov 2016 23:23:43 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
X-Api-Schemas: http://10.10.10.10:8080/v1/schemas

{"id":"d8dc3934-d103-448d-a98f-727f315a7132","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}

Earlier I changed setting to internal like http://10.10.x.x:8080 but it did not work even then. Do I have to bounce something for that URL change to take effect.

**Comment by longwuyuan** [comment]
Was able to add 1st node just now.
Changed URL to internal and used ami-c6d073a5.
Same combo failed earlier but now worked so will add more nodes and reopen if needed.
Gratitude @vincent99
