### ISSUE TITLE
Completely missing the point of the Load Balancers if can't specify IP address

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#6852]
**Rancher Version:**
any

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
any

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
any

**Steps to Reproduce:**
Have server with multiple public IP addresses on single network card.
1.1.1.1 managed by the host itself and multiple long-running services use it (ie. SSH, MySql, nginx (for LDAP auth)
2.2.2.2 \   These IPs are for use with rancher
3.3.3.3 /   and can contain services on same ports as 1.1.1.1 (ie nginx, etc)

Add Load Balancer service in Rancher - but you cannot specify which IP to bind load balancer to. 

**Results:** 
This results in weird UFW overload, where it defines a UFW rule to take over http and https ports and renders all host-based services unusable.

**Expected:**
expected behavior would be to be able to specify which IP address the LB should bind to

When trying to specify IP address in the Load Balancing UI, getting this error:

> Source Port is required on each rule
> Choose one or more port rules to listen on

**Comment by virtuman** [comment]
I almost don't really see how load balancer can be used on a multi-IP host, or I'm sure I am completely misunderstanding how load balancers are supposed to be used. Can someone elaborate / explain ?

**Comment by bacheson** [comment]
This works nicely if you are in the cloud and your host features a LB service (Google, Amazon, Rackspace, Azure).

I deploy a public service on a group of machines. I also deploy a LB on this same group. I then point my Google loadbalancer at the group of instances. Voila. Double HA.

**Comment by virtuman** [comment]
it used to work beautifully up until 1.2.0 update where you can no longer specify BIND IP address on the service / load balancer. Now it looks like I cannot use rancher in all of our infrastructure since most of our hosts are multi-IP systems and often will host services on same port but on different IPs.

Since rancher does not allow to specify IP address anymore - is it possible to give it at least some default (or list of host IPs) that it should limit all port binding on? as of current version - it just blindly removes IP address limitation and changes UFW rules to send traffic to docker, and kills access to all of our host-driven long-running services that use same port on different IP addresses.

I honestly don't understand the point of this change, it really messes up our entire flow, we've been waiting for 1.2.x for so long and kept on overlooking all the minor issues that we had, just to end up with the release of the system that we can no longer use.

This is not our main limitation but just to clarify our problem as an example. For example, on one of our installations - we use rancher on our dev environment:
**MYSQL running on HOST** to manage common databases that are periodically synchronized with production environment DB. This allows us to have real data in dev and testing environments. Many of our projects require different mysql server settings, so we have a couple of mysql servers running on different IP addresses. Same goes for **mongodb replicasets, elasticsearch (different versions for kibana, for search engines, etc.), and many more services**.

We have GIT running on the hosts themselves and gitlab instances, that all use standard ports (22 for ssh)

We have management platforms that need to be highly available and were not yet converted to docker, for most part because we have too many of said systems and didn't have time to re-deploy all of it through docker.

we have approximately 20 sites running on host, and many more sites including our CI test/dev branches running through docker.

I understand that we could adapt the use of "different" ports for all services and then start changing all of our development and management tools, but that would just take us forever, probably good 4-6 months project, and even that would result in unforeseen issues as well as potentially poorly tested things, since environments and published ports are different in qa/staging/production environments.

And all of this is only because IP address option is now forcefully removed from load balancer support as a part of 1.2.0 design, for apparently a completely unknown reason, unless I really am not understanding how to use it. Seems like all the benefits of rancher (reasons that we used rancher) are gone with this single option. Super unfortunate.

Granted everything can still be achieved through use of extra layer of abstraction (ie add another haproxy docker flow, or something of that sort) but it complicates things even further, and with all the instabilities that we experience with rancher server on a weekly basis - this is just an extra reason to stop using rancher. Super unfortunate. 

I honestly wish that I could at least get a confirmation that our use-case is not common and rancher team doesn't like the way we utilize rancher or if this is just an oversight that is causing issues for many of the rancher users and rancher will give us IP address option back?

Thank you for the hard work on the rancher, it's a great product, although seems like we won't be able to use it anymore.

**Comment by vincent99** [comment]
I swear I responded to this yesterday but can find no evidence of it now... must have never hit Comment.

FWIW the backend still works exactly the same, so you can still do what you were doing before with the API or compose.

I think it's fair to say this is not a very common use-case.  But it's really more of a problem because it makes people *think* they can use it when they really can't.  Putting in a specific IP only works in a very specific situation:
  - You create a service of scale=1
  - You set scheduling to put the container on exactly the right host that has the desired IP
  - You put that IP into the listener ports
  - That IP is **actually** bound to an interface on the host, and not just routed there.  Most of the common cloud VM providers do not actually do this, you have one interface with one IP and other IPs routed to you.

**Comment by vincent99** [comment]
(and I found my old reply in a buried tab, grr... Anyway)

Hmm... in 1.2 we tell the Docker daemon to make the `networkMode: none` for managed network containers.  So the IP no longer physically has to be bound to a real interface on that host.

So we could insert the iptables rule to send a request to 1.2.3.4:80 to the 10.42.x.y IP of the balancer container on ALL the hosts; It would work on whichever host(s) really get packets for 1.2.3.4, and be ignored on ones that don't. 

This would cut down my "very specific situation" list to:
  - SOME host in the environment has to respond to that IP if you want things to work

Which is much more reasonable.  Still not something I think is common, but I could see it as another option at the bottom like "Show custom backend names" to allow you to input IPs.

**Comment by virtuman** [comment]
@vincent99 thank you very much for trying to clear this up, that's exactly my use-case and I intentionally want this LB to sit on a specific host, because other hosts have ports 80 and 443 taken by other web services that i cannot override. I actually assigned a label to a specific HOST and have only that host act as an HTTP(s)/TCP proxy for all incoming traffic, it also serves a bunch of stateful services (like gitlab) with storage across local raid.

Either way - if this LB was setup to freely deploy on any of the nodes - it would inevitably end up on this particular host at some point anyway, and would render everything else on other IPs on port 80 to be inaccessible just the same way. 

I guess a couple of questions:
1) you mention that API still works the same, but I believe that I already tried spinning up LB using `rancher up` but to the same avail
2) is there a way to limit whatever rancher does with ports and networkMode to IPs that rancher manages (ie - exclude some of the system IP addresses from rancher control, so that there's never a collision?)
3) what you are describing sounds a little similar to the MESH networking that docker swarm introduced, does it mean that rancher now creates its own mesh network? And if it does - when in swarm mode - does it ignore Docker Swarm's mesh and uses it's own or is it going to use MESH of the docker and won't do any of the rancher's mesh-magic?

Thank you.

**Comment by vincent99** [comment]
> you mention that API still works the same, but I believe that I already tried spinning up LB using rancher up but to the same avail


![image](https://cloud.githubusercontent.com/assets/753917/20862761/170af21a-b971-11e6-94ee-d7f3ce789f8f.png)


```
-A CATTLE_PREROUTING -d 1.2.3.4/32 ! -i docker0 -p tcp -m tcp --dport 90 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING -d 1.2.3.4/32 ! -i docker0 -p tcp -m tcp --dport 90 -j DNAT --to-destination 10.42.233.171:90
```

> is there a way to limit whatever rancher does with ports and networkMode to IPs that rancher manages

The main difference is that the `networkMode` is set to `none` on the container and the port mapping isn't given to Docker anymore.  We manage the mapping of [ip:]port to target container through iptables.  But are not aware of ports that are used by things on the host outside of Docker.

Most users treat the hosts as mostly disposable (except maybe storage) compute and run things only through Docker.  Not really additional random daemons running outside of Docker, other than things like `ssh` that are unlikely to clash with something a container would want to open.  (Incidentally this is literally the [origin of the name](http://cloudscaling.com/blog/cloud-computing/the-history-of-pets-vs-cattle/), servers are interchangeable "cattle" and the "rancher" manages them).

But anyway, we can add checking for ports bound outside of Docker.

> what you are describing sounds a little similar to the MESH networking that docker swarm introduced, does it mean that rancher now creates its own mesh network? And if it does - when in swarm mode - does it ignore Docker Swarm's mesh and uses it's own or is it going to use MESH of the docker and won't do any of the rancher's mesh-magic?

Not really, the Swarm routing mesh publishes a single port on every host.  So only one service can be using that port.  And I don't think they have any good way to handle multiple IPs per host either.  

What I said earlier would just allow a container to "listen" on a particular public ip+port, even if the container does not physically run on the host that happens to receive packets for that IP.  So you wouldn't *have to* schedule the containers to the right host anymore, though it is less hops if you do.

> in the example with the iptables rule - would it be able to handle it automatically when LB re-deploys and will re-create rule based on the IP address if the container with LB restarts under different IP?

The 10.42.x.y container IPs don't change when they're restarted.  But yes, the rules are kept in sync.

> How is LB intended to be used in rancher? ...

The balancer just balances what it's told, we don't really get involved in how you want to use it.  The cases where you actually need separate public IPs for each HTTP service are pretty slim these days.. SSL on old version of IE on old version of Windows that don't support SNI. (And arbitrary TCP services, but you seem to be talking mostly about HTTP)

If you can assume SNI is available (or are doing plain HTTP) then what you describe would typically be done with a single balancer service (probably in it's own stack, though it can be anywhere) that has a set of rules to send traffic to all different services based on the Hostname.

Most users are using hosts basically dedicated to Docker, with one public IP each, as you get from all the public cloud providers.  So they do not get involved in mapping IPs at all, services are just bound to 0.0.0.0.  You can use a label to schedule the balancer onto a particular set of hosts to put into a DNS entry manually, or use the external-dns catalog items to publish a record to a compatible provider automatically, or use a hardware or cloud balancer (like ELB) and let that manage sending requests to the balancer containers that are up.

We do not really magically do anything.  You can setup a situation where services "auto join" a balancer by having a selector rule on the balancer to look for a label and then putting that label on the services.  The services can then define their own port rules to do hostname/path routing (this part [did not make it](https://github.com/rancher/rancher/issues/6716) into the 1.2 UI, but is in compose/API).

> Is the design of rancher to fully rely on automated DNS external engines? Meaning that - since the LBs can be deployed wherever it finds available IP - is it no longer at all possible to use traditional single-ip address dns entries (for example with DNS providers that don't have any API-like access to update DNS entry when a container is re-scheduled)?

Nothing has changed here, you can still use host labels and service scheduling rules to make the balancer containers go onto the hosts that have the right IPs to match your manually maintained DNS record.

But if you don't have something managing the DNS record you don't really have fault tolerance in the first place.  When a host dies users are going to continue to get DNS answers that point them to a dead host.  You need either something like another balancer (i.e. ELB or hardware) or something to remove bad entries from DNS to keep users going only to healthy hosts.

> Is it possible to auto-merge LBs into single LB deployed across all publicly accessible hosts that would MESH all traffic across containers, despite where containers are running?

As above, you control how things are arranged.  A similar arrangement is possible with a single balancer with a selector rule, and additional rules on the selected services.

> Is it at all possible to specify DNS entry for a single service that is scheduled on a host? I'm super confused with having no ability to control where DNS entry is supposed to point, ie:

As above, you need to use labels and scheduling rules to make the containers go where you configured DNS to point if you're going to manage the record yourself. (And you don't really have fault tolerance, so you almost might as well just run scale=1)

> Scenario 1 - seems pretty straight forward and how things used to work:

I'm not sure what the question is here, but yes, those things are true?  Note that there is no need to type `1.2.3.4` anywhere in the balancer (if there is a balancer here?) or service config in the case where the host only has one public IP.  It will just be bound to 0.0.0.0 by default and there's only one possible IP for it to be bound to anyway so there's no reason to specify it.  You just know the host with 1.2.3.4 has that label and Jenkins and create the DNS entry appropriately.

> Scenario 2:
> my understanding is that traffic to jenkins.domain.com will not be restored until DNS is manually updated or hostA is back online and container with jenkins is forcefully moved back to hostA

Yes, clearly with hostA down and the manually managed DNS entry pointed at it the service is DOA until the host is back or the entry is changed.  If there's a balancer involved then it doesn't matter where the actual container for the Jenkins service is now residing.

> Scenario 3 - and I think that this is what rancher is only supporting from this point on only:

Again, nothing has changed as far as the things supported by the backend.  One field in the definition of a balancer rule was removed from the UI, and it affects *only* the situation where you have multiple IPs on a single host and want them pointed at different services for a particular port.  That has nothing to do with any of these 3 scenarios, where you're asking about how things are updated on hosts and in DNS when a host fails.  And using the IP binding in 1.1 made it impossible for that service to be rescheduled to another host anyway.

> Dynamic Automated DNS service is running through rancher (ie Amazon ELB, etc.)
> Dynamic DNS handling updates entries in DNS (might take a few minutes to replicate - during which time service might end up being completely unavailable, until DNS propagates)
> Container or host crashes - rancher reschedules this container to another Host, DynamicDNS gets updates, service is down until DNS propagates, and then service becomes available again

This was in 1.1 and remains in 1.2 the only way to have real fault tolerance.

Using an external balancer like hardware or ELB can give you (near-)seamless failover because they can probe the target servers and immediately remove failing ones. (I'll say ELB for simplicity...)

  - You put load balancer service containers on a set of hosts (with a label, or just on every host with global scheduling)
  - ELB is configured to send requests to those hosts (if you're actually using Amazon, the easy way is to make an AutoScaling Group for the hosts, point ELB to the entire ASG, and run the balancer service with global scale)
  - jenkins.domain.com CNAMEs to your-elb.amazonaws.com
  - ELB keeps track of which hosts are healthy and sends traffic only to them
  - The request goes to the host ELB picked.  The port rules for the Rancher balancer determine which service the request should go to.
  - Rancher balancer keeps track of which target service containers are healthy and sends the request to one of them (which might be on the same host or a different one).

The external-dns catalog entries are sort of the "poor man's" alternative to the ELB/hardware balancer part if you're running somewhere where one isn't available.  They have degraded response for the length of the entry's TTL, which is still a lot better than $until_someone_notices+TTL for manually managed.

In various clouds there are also the concept of floating IPs that can be moved to a different host when one dies, but this isn't something that can be generically implemented, you have to talk to their specific API.  And if you're running your own hardware you can potentially do similar on your own with VRRP/keepalived to create a floating IP.

**Comment by tfiduccia** [comment]
Version - master 11/13
Verified fixed
