### ISSUE TITLE
Deployments not respecting links

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#6854]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7.2 VMs Hyper-V

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Services and containers are all deployed in parallel and links are not respecting. If service A has a link to service B, service B should start first and then service A (same as docker-compose up) 

**Results:** 
Service A starts in parallel with service B. In cases where service A starts first, and service B is not yet running, service A exits and fails since the service B container is not yet running)

**Expected:**
Links should be respected in the same way that docker-compose up does

**Comment by vincent99** [comment]
Starting the services in dependency order does little to nothing to guarantee that service A will work.  Compose [does not know](https://docs.docker.com/compose/startup-order/) when B is actually ready to accept a connection and your application should retry and and reconnect if it needs the dependency.  Their same advice applies to us, and if A dies because B isn't ready (instead of watching for it), A will be restarted automatically to try again.

**Comment by darrenscerri** [comment]
Going to close it for now as I think this may have been a misdiagnosis as a side-effect of #6855, due to containers failing and restarting.
