### ISSUE TITLE
ActiveDirectory / LDAP integration

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#688]
Should be able to:
  - Choose AD/LDAP as the authentication source (instead of GitHub) and configure relevant settings (host, port, service account, etc)
  - Decide who can log in
    - "unrestricted" mode: allow any valid AD user in
    - "restricted" mode: allow only whitelisted users and members of whitelisted groups
  - Create environments with LDAP users & groups as projectMembers

**Comment by clemenko** [comment]
Thanks. Can't wait to test.

**Comment by hibooboo2** [comment]
Basic use case Happy flow is now supported. 

Login with username password. Ldap config now exists.

This Issue cannot be resolved until #1497 is finished.

**Comment by will-chan** [comment]
- Adding Cattle Identity API and adding capability to configure.

**Comment by will-chan** [comment]
* Complete integration with UI + write design spec.

**Comment by hibooboo2** [comment]
Ldap Authentication Integration
---------
Purpose: To be able to authenticate to rancher using ldap credentials. Add users to the site based on their ldap username or groups.
Add users to a project based on their ldap user or groups.

After configuring ldap you are able to login to rancher using ldap username and password. Then you use rancher the same
as normal except that when creating projects you use ldap users and groups not github users ors or teams.

---------

In order to configure ldap you must specify the following:
 
 * **accessMode**  (restricted or unrestricted)
 * **domain** (domain with in ldap to use. ex ad.example.com)
 * **loginDomain** 
    * default domain to login using
    * ex User1 becomes loginDomain\User
    * ex foo\User1 stays foo\User1
 * **port** (port ldap is listening on. defaults to **389**)
 * **server** (server ip or domain that rancher can use to connect.)
 * **tls** (Use tls or not. (Tls not tested / implemented yet.))
 * **serviceAccountPassword** (password for the service account that has readonly access to all of ldap (All of ldap that you may need access too for authentication.))
 * **serviceAccountUsername** (username for the service account, same account as above)
 * **searchFieldUser** (Field used on ldap object to search for a user defaults to **sAMAccountName**)
 
 **Subject to change**

**Comment by hibooboo2** [comment]
https://github.com/rancher/rancher/wiki/Ldap-Auth-Configuration.

**Comment by MhdAli** [comment]
Hi,

May I know to which docker image tag that this changes commit to? I'm using `latest` one apparently it's using `v0.30.0` tag.

**Comment by cjellick** [comment]
@MhdAli this feature hasn't landed in a release yet. We'll update this issue when it does. Sorry for the confusing statements.

Here's the relevant PR:
https://github.com/rancher/cattle/pull/703

**Comment by will-chan** [comment]
* Search for Groups.
