### ISSUE TITLE
Marketing + messaging around significant 1.2 upgrade maybe incorrect?

### ISSUE THREAD

**Issue by untoldone** [rancher/rancher#6961]
**Rancher Version: 1.2

Generally speaking, I feel that Rancher could have had significantly better messaging around 1.2. I feel like the general theme of response to bugs, and forums has been "things are broken because a lot of things changed in this release". I feel that from an enterprise software perspective, this type of messaging, while maybe true, makes me feel uncomfortable trusting future releases.

It makes me feel like Rancher's internal practice says that it is ok to introduce a significant number of bugs in a GA release to the point that at least several people (seen in bugs and forums) have a relatively un-operational cluster (myself included). It makes me worry that this same type of release might happen in the future as there's nothing in place to prevent it.

More appropriate messaging could be (assuming it is true): "We now know this release was bad, and here are the things we're doing to prevent it from happening in the future".

I really love the product, and this definitely won't cause me to go elsewhere. While I can't afford to be a customer today, I definitely hope to be one in the near future + support the future development. I hope this is seen as constructive feedback rather than me prodding in an unproductive way.

**Comment by joehumphries** [comment]
I feel the same, they are adding more 'features' before the core is stable and robust. It is a shame. I wonder about the testing done.

**Comment by bacheson** [comment]
I literally posted the same message in the forum. 1.2 has crippled my install. Even starting from fresh my ui is locking up and containers are stuck in infinite starting states. What a mess. This is making me look bad internally at my company.

**Comment by jloisel** [comment]
You should always backup your work before migrating to new versions of any software. This is not specific to Rancher. Software is designed by human, who aren't perfect by nature. You are supposed to have testing environment to test and prevent issues in production.

Sure, Rancher v1.2.0 is pretty bad from user perspective. But, from developer perspective, things have improved a lot, especially in terms of **separation of concerns**. At some point, you can do all the QA you want internally (and i'm sure Rancher did a lot of QA before releasing this version), it's several magnitudes less efficient than thousands of people testing your software in a variety of environments.

I feel like Rancher's codebase quality has worsen due to a race of implementing as many features as possible within an unreasonable timeframe. Rancher is Venture backed and this makes me think they have a pressure from their investors to make things too fast.

**Comment by bacheson** [comment]
great points @jloisel ... although no one said anything here about upgrading to 1.2 in production and not having a backup...that's obviously a terrible idea. It's frustrating when you spend hours testing only to have the latest and greatest crash and burn all while touting a GA.

**Comment by joehumphries** [comment]
@jloisel Im not sure, all the different levels of testing, unit, functional, regression, integration, ete,  load etc should have caught 95% of the problems I see people raising on this forum. 

Also, I feel a lot of the issues raised people people result in just reinstalling the server and the ticket raised here are just closed.

We shall see, I feel they need to step back a focus on the great product that is fighting to get out.

**Comment by vincent99** [comment]
There are several common issues that came up in 1.2.0 and they will be addressed.  We're sorry that's caused some people trouble, but the changes to make networking/orchestration/storage/etc drivers pluggable, reworking HA and load balancing, and all the other stuff necessitated a fairly complicated upgrade of it all at roughly the same time.  In the meantime other developers have been working on features all that time, so all that stuff shipped too.

We don't want to have giant impacting releases either; there is not going to be 5 months between 1.2 and 1.3.

For customers we support specific versions and configurations of the base OS, Docker, Kubernetes, etc upgraded from previously supported specific version and those are the permutations we spend most of the time testing against.

We added telemetry in ~1.2.0-pre3 to get some data on this... For just the small percentage that opts-in from community-land there are nearly infinite permutations of:
  - OS: Alpine, Amazon, Arch, Boot2Docker, CentOS, CoreOS, Debian, Fedora, Mint, Oracle, Photon, RancherOS, RHEL, SUSE, Slackware, Ubuntu, Windows(!), etc.
    - Each with multiple major versions.  For example with just Ubuntu there is everything ranging from 12.04 (which isn't even supported by Canonical anymore), to dev branches of 17.04
  - Kernels: Everything from 3.10.x to current, plus all the patches distros add on top
  - Docker:  1.9 (which wasn't even supported in Rancher 1.0.0) to RCs and builds from random commit IDs

Then there's:
  - Unusual configuration variations, like moving the docker storage directory or twiddling critical daemon options without understanding what they do (i.e. `--iptables=false`).
  - People that have been upgrading the same install since 0.46.0 or gone through every RC build even though we explicitly tell them that it is not supported.
  - When someone does have a problem, they frequently don't provide enough information to do anything about it, and then as you've said wipe the database and now they *can't* provide additional info, so there's really not much else to do with the issue.
  - A surprisingly (if you don't manage an open-source project) high percentage of issues end up being user-error completely external to us (i.e. typos, oops the ports aren't not open in the security group, etc)
  - People that have no problems don't come to github or the forum and tell you how awesome things are.  There are many, many more installations (even just among the opt-ins I can see) than people commenting on issues/forum posts.

**Comment by ibuildthecloud** [comment]
@untoldone  Chief Architect of Rancher Labs here.  I take this concern quite seriously.  We are basically in a very difficult position here.  We had to make some major architectural changes in order to continue to meet that demand for all the features and flexibility that people want.  Such a major change makes upgrade extremely difficult.  This left us with two options

1. Don't support upgrade.  Honestly a lot of open source projects just say this doesn't work.  (How many years did it take OpenStack and does it even really work?)  This would have been the easiest route but our users absolutely demand upgrade.

2. Test more.  We have plenty of enterprise customers and we have been testing their known configurations.  All of November was basically just doing upgrade testing.  Just to put that into perspective that's about 10 engineers working full time for a month doing nothing but fixing issues with upgrade.  Do the math and you'll see the $$ of QA that open source is getting for free.  It's not cheap to build something like this.  Now one could argue that we could have done more QA.  That's definitely true but as @vincent99 pointed out the combinations are endless and also we have to deal with all possible bugs that have existed in <= 1.1 which caused some form of data corruption.  To make things worse is that it took a very long time (5 months) to get this release out.  The longer we wait to put out a release the worse the community suffers.  They feel like we aren't fixing known issues but we have in fact fixed them.  The problem is that fixing the issue is simple, but then providing an upgrade that retroactively address problems caused by a bug is not so simple.

In short, we tested, we tested a lot.  We thought the release was good and would never release something we didn't think was.  For many people the upgrade has worked for some it hasn't.  For those it hasn't we are working to address that in a 1.2.1 (should be released 12/12).

Going forward we do not expect this level of change again.  From 1.1 to 1.2 the guts of Rancher change substantially.  That will not happen in 1.3+ going forward.  Stability and scale is a major focus of Rancher going forward.  Features are not a problem, we have plenty of them.  In order to address stability we are shortly going to launch a free public hosted instance of Rancher.  The primary reason we are doing this is for scale and stability.  It is always hard to troubleshoot random open source issues because we don't have a good communication/feedback channel.  By running a hosted version we can run at a scale larger than any of our users or customers but also have full visibility to the server to see issues we are encountering.  I expect the quality of Rancher to substantially improve because of this.  Additionally running a public service requires our upgrades to be even better.

I'm sorry 1.2 was a bad experience for you, it hurts me to have users say that and we will do all we can to improve.

**Comment by willseward** [comment]
Response bias is a tough burden to conquer. 

I'll take this as an opportunity to praise Rancher. Though, there are many other products filling the same market-space, none quite tick all of the boxes that Rancher does. I simply wouldn't be in business if it weren't for Rancher. Thanks, guys!

**Comment by untoldone** [comment]
@ibuildthecloud @vincent99 I really do appreciate you both taking the time to very thoughtfully reply and I appreciate everyone else working on the release and its subsequent fixes. I'm 100% ok with how everything has played out and definitely feel Rancher is the best option out there for its category. I'd absolutely recommend it to others.

However, I still do feel post-release communications could be improved. For example, the current listed major known issues do not include breaking bugs that I have experienced (some that also already have confirmed, open bugs). I also feel like major known regressions for this type of product should go first in release notes as they seem the most relevant topic to someone reading them / about to upgrade their cluster. The revision numbers themselves didn't suggest such a major shift -- I perceived 1.1 => 1.2 as a noteworthy upgrade, with some new features, but not a significant change. While it seems your team knew the significance of the upgrade, I'm guessing the community did not (besides being excited by new features). If either the release notes made the significance of the change very clear, or the version number shift were something more like 1.1 => 2.0, I might have taken more time to review before acting.

My experience may be rightfully my own fault for not matching industry standards of a mature IT org (no rancher backup, no testing upgrade before launching in prod), however, I'd also guess a noteworthy number of people fell into the same pit as myself with this release.

While in hindsight, it is easy for me to point to specific things and say, "this could have been done better," I can only imagine how challenging it is to deal with all the unknowns involved with this type of software. I think you've all done a fantastic job to date and will continue to share my generally positive experiences of using your software with others.

**Comment by AdamNowotny** [comment]
The lesson for me is to lock versions used so no unplanned upgrades take place before we have a chance to test things. Made the mistake of running just "rancher/server" with no version specified in CloudFormation template and for some reason the EC2 instance died over the weekend and the new one upgraded Rancher to 1.2.0. So we started the Monday morning with all of non-production environments down (luckily prod was unaffected). Tried to just fix services in the new one for a while, but all I got is "Timeout getting IP", and "Dependent services failed" or something like that, ipsec and other infrastructure stacks in "degraded" mode, restarting services for no clear reason. In the end just had to revert server to 1.1.4 and recreate all environments. There was nothing in the release notes that stood out as a cause of the problems.
It was challenging to convince the client to use Rancher, now as much as I like it and would use it in the future, I feel like sadly the experiment here might be over...

**Comment by willseward** [comment]
@AdamNowotny I had a similar situation happen to me. I updated to 1.2, but forgot to update my ansible scripts and ended up rewriting my systemd service to 1.1.4 again. I'll never make that mistake again...

**Comment by SoreGums** [comment]
> I feel similarly about Rancher, but I just can't find anything to replace it.

Most likely because there isn't anything that does what Rancher does **the way** Rancher does it. To go somewhere else you need to master a whole lot of what Rancher hides/integrates internally. Which if done properly you are looking at minimum of about 5 hosts just for the orchestration part, then you need to add your actual work nodes. Using AWS can take out **managing** some of those hosts, however still need to pay for them.

I'm in the process of setting up a dedicated sever that runs Ubuntu 16.10 + Xen 4.7 which will then have 3 VPS one of which will be Rancher Server, the other 2 running containers managed by the first. Disk I/O is going to be the biggest issue with this setup and doesn't lend itself to HA well. However for the purpose, HA is not the be all/end all at this stage and restore from offsite backups is good enough. Even adding up the number of containers to be run it is around the 15-25 range, tiny really.

From when I found out about Rancher, around Jan 2016, I've believed that it is the way to go for managing container deployments. If I had the resources I'd have already launched a managed Rancher hosting service. As a developer I just want somewhere to put a compose file and have things just work at an economical price _(the managed orchestration part)_. The current options each have their disadvantages that Rancher addresses for me, the biggest one being physical location of the actual compute power of the docker host running the containers, followed up by price.

Looking forward to what is coming next 👍
