### ISSUE TITLE
versioned rancher-metadata api

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6984]
**Rancher Version:**
1.2

Rancher metadata has [changed](https://github.com/rancher/rancher/issues/6951) its naming convention for containers. This breaks any tooling that relied on that convention earlier. Using older 'versions' of metadata '2015-07-25' for example exhibits the new naming convention.

**Comment by vincent99** [comment]
The way names are generated changed slightly in 1.2 because the current docker remote API requires it.

Metadata returns the names of the containers that exist;  the data is what it is, it is not a property of what version you asked for and it doesn't make any sense to convert it to what it *would have been* if that container were to have been created on 1.1.x.

Tooling that relies on the construction and parsing of an auto-generated name is a bad idea.   Use labels, or uuid, or create_index, etc.

And if we did change the data to return the wrong name that matches what 1.1 would of generated, *that* would break much simpler tooling that  just tries to find do exact match against a name founder in the API.

**Comment by linhaooooo** [comment]
6984
