### ISSUE TITLE
Stopped conatiner doesn't shown on service upgrade in host pane after upgrade to rancher 1.2

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#6998]
**Rancher Version:** 1.2

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04 on Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Sinhle node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
* Create stack with service which have 1 container.
* Start upgrading service (update healthcheck rule for example)
* Wait until it marked as Upgraded
* Head to Hosts tab

**Results:** 
* There is no stopped container in detailed view (postgres-1 container in my case)
![image](https://cloud.githubusercontent.com/assets/1079535/21057319/c71f890a-be6b-11e6-9e24-dfaeac25ed20.png)

* It presents on brief(bubbles only view).
![image](https://cloud.githubusercontent.com/assets/1079535/21057282/9899c492-be6b-11e6-9c25-43d43dddb827.png)
* It presents on service containers view.
![image](https://cloud.githubusercontent.com/assets/1079535/21057301/b0edceda-be6b-11e6-9560-5f82f49e04fe.png)

**Expected:**
* There is stopped container in detailed view
* It presents on brief(bubbles only view).
* It presents on service containers view.

**It was OK on Rancher 1.1.4**

**Comment by tfiduccia** [comment]
Version - v1.2.0 - checked and this is easily reproducible on current build.

**Comment by vincent99** [comment]
They are there for lack of a better place in 1.3 because they were missing entirely from 1.2 and there is not currently enough information to group them into their own row correctly with the appropriate sidekick instances.

@alena1108 Can you make the`version` always match for the set of containers that make up a version (instead of one of them sometimes being `0`) so I can group them by `deploymentUnit` + `version`?  (I don't think we need to worry about to migrating existing instances, just for new ones going forward)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
