### ISSUE TITLE
File upload does not work on https

### ISSUE THREAD

**Issue by beruic** [rancher/rancher#7031]
**Rancher Version:**
v1.2.0 and v1.1.2

**Docker Version:**
v1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS
Bare metal (5 hosts)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
I believe it's single node rancher with internal DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Setup a host and serve it on `https` through a load balancer (using service links).
2. Upload a file to that host with Cordova using `(new FileTransfer()).upload(imageNativeURL, serverURL, succesHandlerFunction, errorHandlerFunction, options);`

It should be noted that the `serverURL` in our case both has a `GET` string, but the file upload is handled as `POST`. Options contain:

```
options.fileKey = "file";
options.fileName = file.filename; //imageURI.substr(imageURI.lastIndexOf('/') + 1);
options.headers = {
    Filename: file.filename, // FIXME Should be possible to use options.fileName on server end
    Cookie: document.cookie,
    [Application specific headers]
};

The certificate is a Thawte wildcard cerficate.
```

**Results:** 
The form cannot receive the file server side. HA Proxy seems to change something.

**Expected:**
File to be uploaded like it does on `http`.

**Notes:**
I am opening this bug now to draw some attention to whether others have experiences similar issues. I am not the main person in our organization working with Rancher, all though I have full access.

**Comment by vincent99** [comment]
The only thing that changes when you do SSL termination vs http is an additional header or two.

This is far too abstract for anyone to  really help you.  It is not realistic to expect people to go figure out how to create a Cordova app to attempt to blindly recreate an unknown problem with no specific reason to think it's actually caused by anything Rancher/HAProxy is doing.

What errors do the client and/or server produce?  Does sending a file to the same server with something simple like `curl` work?  Capture the requests from the target service and compare? Create a minimal example container demonstrating the problem?

**Comment by beruic** [comment]
I agree that this is abstract. So far the only thing we see is that the form does not validate in Django, and it works when we switch HA Proxy out with Nginx in front of it instead. Currently we have some deadlines that must be adhered, but we plan to do an effort figuring this out. In the mean time it would just be nice to know if others experience similar issues. Perhaps under slightly different conditions that may give better indication of the problem.

**Comment by beruic** [comment]
Update from our side: We made it work by putting Nginx in front of the HA Proxy load balancer to handle SSL, such that the traffic through HA Proxy is pure http. We have become quite pressured here, which is why I don't see us debugging this in the near future. Therefore I am closing this issue now.
