### ISSUE TITLE
Rancher server container regularly dies/stops

### ISSUE THREAD

**Issue by nicolinux** [rancher/rancher#7053]
**Rancher Version:**
v1.2.0

**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
DigitalOcean, Ubuntu 16.10

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, no HA, internal MySQL DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
The rancher Docker container regularly dies.

**Results:** 
It might be related to #7013. In addition to it I see these errors in the log:
`2016-12-14 10:03:06,878 ERROR   [pool-3-thread-1] [ConsoleStatus] Check-in failed org.jooq.exception.DataAccessException: SQL [update `cluster_membership` set `cluster_membership`.`heartbeat` = ? where `cluster_membership`.`uuid` = ?]; Connection timed out`

**Expected:**
To be stable and don't stop?

**Comment by eshork** [comment]
This issue has been happening to us in our test environment. Minor differences in platform. 

**Rancher Version:**
v1.3.2

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2 t2.small, RancherOS v0.7.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, no HA, internal MySQL DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.175.8

----

We've noticed that the rancher service dies at strangely predictable times. (Though it doesn't always die when these times occur, it only ever seems to die at these times, so it appears to be related a scheduled job). Times we've experienced service death:
1:44
4:44
7:44
13:44
16:44
19:44
22:44

Also, after looking at the logs in the container, it appears the service is dying because it loses connection with the mysql server. Checking mysql logs shows the service is restarting at those regular intervals, but the cause of the restart isn't yet apparent.

**Comment by tcdev0** [comment]
**Rancher Version:**
v1.6.7

**Docker Version:**
docker-ce 17.06.1 

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on Xen VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, no HA, external MySQL DB (container)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

happens on a daily basis, since switching from docker-ce 17.03.1 to docker-ce 17.06.1

Logs (rancher-server): 

`2017-08-27 09:07:12,111 ERROR   [pool-3-thread-1] [ConsoleStatus] Check-in failed org.jooq.exception.DataAccessException: SQL [update cluster_membership set cluster_membership.heartbeat = ? where cluster_membership.uuid = ?]; (conn:1968) Connection timed out `
...
`Caused by: java.sql.SQLNonTransientConnectionException: (conn:1968) Connection timed out`
...
`Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Connection timed out`
...
`Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not read packet: Read timed out`
...
`Query is: update cluster_membership set cluster_membership.heartbeat = ? where cluster_membership.uuid =  ?, parameters [1503824750213,'502a9b21-a63c-474f-a385-79a867dbdf17']`
...
`Caused by: java.net.SocketTimeoutException: Read timed out`

**Comment by aemneina** [comment]
Couple of the issues here look like a database connection issue. Start by checking connectivity from the server host or container.

**Comment by tcdev0** [comment]
Database connection was aborted during backup of the mysql database and rancher-server crashed and restarted.

` [Note] Aborted connection 11 to db: 'rancher' user: 'rancher' host: '172.17.0.4' (Got an error reading communication packets)`

`mysqldump -A -h $DBSERVER $DBUSER $DBPASS --all-databases | gzip > ${TMPDIR}/${TARGET}`

changing the dump command resolves the issue:

`mysqldump -A -h $DBSERVER $DBUSER $DBPASS --all-databases --single-transaction | gzip > ${TMPDIR}/${TARGET}`

**Comment by jgysland** [comment]
This began happening to me in the past few days. I just use Rancher for some self-hosted stuff and I haven't made any changes to anything, lately.

*Rancher version:*
v1.6.0

*Docker version:*
17.05.0-ce, build 89658be

*OS and where are the hosts located:*
Ubuntu 16.04.3, bare metal

*Setup Details:*
single node, no HA, internal MySQL db

*Environment Type: (Cattle/Kubernetes/Swarm/Mesos)*
Cattle

**Comment by superseb** [comment]
@jgysland can you open a new issue with steps to reproduce and logging so we can investigate? This issue has is way old and closed.
