### ISSUE TITLE
rancher UI can't list my own network

### ISSUE THREAD

**Issue by helphi** [rancher/rancher#7083]
I hava created a network on my host, but i can't select it from the drop down list.

I have a network named `mynet`
```bash
root@docker1:~# docker network list
NETWORK ID          NAME                DRIVER              SCOPE
4c8dfd5a3056        bridge              bridge              local
ea9090ce39d6        host                host                local
72a4807f8eb6        mynet               macvlan             local
c44401f836b2        none                null                local
```

but i cant select it (i have restarted rancher yet)
![image](https://cloud.githubusercontent.com/assets/6457416/21255006/22c36c58-c3a4-11e6-8698-8d7a05023fa5.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.new`|

**Comment by leodotcloud** [comment]
@helphi we currently support CNI interface but not libnetwork. Hence we will not be able to show docker networks in the UI.

**Comment by steve-gray** [comment]
@leodotcloud - is this a 'forever' state of affairs - or is libnetwork support coming? It feels very disjoint to have to manually start containers on the host directly in order to leverage Dockers own networks.

It seems like there's three parts of work here:

- Agent - enumerate networks known to each host, store them to server.
- Scheduler - Only place containers on a host where the specified network is available.
- UI - Show the network in the networks list.

This means people can use the docker commands to allocate networks on a swarm,, and then get rancher to see and place containers on them.

**Comment by leodotcloud** [comment]
@helphi @steve-gray We will make an announcement once we have support for libnetwork. At this moment, we don't have any plans of supporting libnetwork. In fact, libnetwork/Docker guys have started support CNI.
