### ISSUE TITLE
Bulk actions/pagination issues

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#7106]
Old
- [x] Single [...] action menu on every row
- [x] Background color for selected rows
- [x] Clear selectedness of rows that become invisible due to searching
- [x] Sorting not very sort-ey
- [x] "Are you sure you want to delete thing1 thing2 ... thingN" is kinda hard to read will not go well with 50 long names... Put a newline between each name, and if length > 10 then say "Are you sure you want to delete thing1 and 42 others"
- [x] Move search into middle of floating row (between actions and paging).
- [x] Z-index: 
![image](https://cloud.githubusercontent.com/assets/753917/21285569/73ab2d4a-c3f9-11e6-9a24-52e17f151f79.png)
- [x] Toggling "Show system" or removing container can result in invalid pages:
![image](https://cloud.githubusercontent.com/assets/753917/21370155/ab6d4dfa-c6c7-11e6-9870-345d1a499ecb.png)
- [x] Clicking on sort breaks selection, bulk actions
- [x] Headers don't line up
![image](https://cloud.githubusercontent.com/assets/753917/21368943/df36a768-c6c1-11e6-8a44-920feb2516e2.png)
- [x] Call it just actions, use input-addons to make search look nicer:
![image](https://cloud.githubusercontent.com/assets/753917/21369566/c774e4f2-c6c4-11e6-8bba-46c8670fb9f2.png)
- [x] Clicking on row action icon more than once toggles the radio/selection
- [x] `tableCount` preference ~doesn't seem to have any effect~ is read from session instead of prefs, and not recomputed when changed
- [x] When a single item is selected, the additional actions are shown as the action name instead of human name: 
![image](https://cloud.githubusercontent.com/assets/753917/21369960/b879c466-c6c6-11e6-939a-a6d45e9b4919.png)
- [x] Clicking anywhere in the TD that contains the checkbox should act like the checkbox (preserve selection) not the row

**Comment by tfiduccia** [comment]
Additional issues:

- [ ] If I run a stop action on container, then select it again without refreshing page, it still thinks it's running and the Actions menu does not update.
![image](https://cloud.githubusercontent.com/assets/11514927/21533577/3944cc50-cd19-11e6-8fae-9cc9344fb72e.png)
- [ ] Unselecting containers using checkbox, does not change row color back to white (it stays yellow)
![image](https://cloud.githubusercontent.com/assets/11514927/21533588/5146330c-cd19-11e6-846d-77a75a0dc43d.png)
- [ ] Can still click on Actions and run that action even thou it's dimmed.  It will also throw a Unknown Action error
![image](https://cloud.githubusercontent.com/assets/11514927/21533686/9895f980-cd1a-11e6-91f7-013b69d9acec.png)

- [ ] If I command + Delete on multiple containers, it opens a new window instead of deleting the containers without bringing up delete modal.

- [ ] Search is case sensitive

- [ ] After doing a search, the Show System checkbox, Actions drop-down and the yellow select no longer function properly.  Have to refresh page to get them working again.

**Comment by vincent99** [comment]
Carryover: 

Round 2
- [ ] i18n: Headers & paging
- [ ] (lacsso) Border on buttons (1px) does not match border on inputs (2px), see above.  @lvuch 
- [ ] page, perPage, content, currentPage, totalPage bindings deprecation warnings
- [ ] If I command + Delete on multiple containers, it opens a new window instead of deleting the containers without bringing up delete modal.

**Comment by tfiduccia** [comment]
Version - 1.3.0
Verified all issues are fixed
