### ISSUE TITLE
Corrupt page shows up on rancher 1.3.0.-rc1

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#7114]
**Rancher Version:**
1.3.0-rc1
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Tried to install HA rancher with 3 nodes, all startup on, but UI displays like this
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
none yet
**Steps to Reproduce:**
normal install on AWS instances, 3 instances t2.medium + 1 RDS database.
**Results:** 

![image](https://cloud.githubusercontent.com/assets/9369080/21294551/e14a0e1c-c547-11e6-9c24-b85da147a441.png)

**Expected:**
:)

Hope it helps.

**Comment by darrenscerri** [comment]
Did you try clearing browser cache? Or maybe incognito mode?

**Comment by Dmitry1987** [comment]
Yup, cache is not an issue. It's all new IPs and machines we used for test.  Reinstalled 1.2.1 and UI was ok  :)

**Comment by yeta-io** [comment]
Confirm the issue, tried 1.3.0-rc, the ui is broken

**Comment by rlex** [comment]
Same here.
/assets/null.css?1.3.0 - responding with 404.

**Comment by pulberg** [comment]
@Dmitry1987 click on one of the "theme" button on the botom of the page, you should then see the UI.

**Comment by rlex** [comment]
@pulberg good find. 
Looks like light theme is broken.
Dark works fine.

**Comment by pulberg** [comment]
@rlex I can see both themes, maybe you have to click "auto" then go back to "light" or something.

**Comment by tfiduccia** [comment]
@rlex @Dmitry1987 @yeta-io - Actually the auto theme is broken.  Once you hit this issue, until you change theme and refresh browser it will stay like this.  So please turn it off (switch to light or dark) then manually refresh the browser.  It should redraw the page and you should be good to go.  This has been previously reported and will be fixed in the next release.

Closing in favor of other bug: #7090
