### ISSUE TITLE
docker --net=host

### ISSUE THREAD

**Issue by tawalaya** [rancher/rancher#7124]
**Rancher Version:**
1.1.1
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
redhat aws ec2 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
sudo docker run -e CATTLE_SCRIPT_DEBUG=debug --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/ rancher rancher/agent:v1.1.1 http://<rancher-host>:8080/v1/scripts/2056B0FF <RANDOM>:<RANDOM>
**Results:** 
Error: No such image or container: ****.eu-central-1.compute.internal

The reason for this, as far as i can see is that: --net=host overrides the hostname witch you use in your run.sh script (line 41) to inspect the running container. The thing is I need to use --net=host because I need to use a ipv6 tunnel to connect to my rancher-host.

**Comment by dchambers** [comment]
Yeah, I just tried the same thing with similar results:

```
Error: No such image or container: rancher
```

For me I wanted to use `--net=host` because I'm playing with Rancher in a VM, and the IP address changes everytime I connect to a different network, breaking Rancher. I could otherwise solve this by using ZeroConf (via 'avahi-daemon') so that the VM responds to a hostname like `rancher.local`, but this could only work if the container was able to use the host's network stack.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
