### ISSUE TITLE
api-filter-proxy feature

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#7134]
### High level thoughts/notes:
- go micro service that acts as a proxy to Cattle. It should be able to receive all Rancher API calls placed by UI/clients
- This will sit right in front of cattle, behind traefik and behind wsp (which may or may not be there based on whether this is an HA setup or not). WSP should be completely transparent to this filter. We shouldn't need to know any implementation details.
- In cattle, this should be launched similarly to rancher-auth-service or rancher-catalog-service
- We don't need to worry about proxy protocol because in that scenario, HAProxy will be sitting in front of the api-proxy-filter, terminating the proxy protocol and sending a "normal" http request to the proxy filter
- Let's eliminate the use of the term webhook from this entire feature and spec. Let's use filter and endpoint where need
- We want this proxy to ultimately completely the "generic whitelist proxy" that is currently built into cattle. This is a better solution.

### Service internals:
- The service works with a config file.
- The config.json file consists definition of API filters (webhooks mapping to API paths)
```
{
	prefilters: [
		{
			paths: [/v1/services /v1/service ] // matches /v1/service, /v1/servies, /v1/services/<id>
			endpoint: "http:/.../external-thing" // file://...sock?
			methods [post, delete]
			secretToken
		}
		{
			paths: [/v1/containers/* ] // matches only /v1/containers/<id>
			endpoint: "http:/.../external-thing" // file://...sock?
			methods [post, delete]
			secretToken
		}
	]


	postfilters: [
		{}
	]

	destinations: [{
		paths: ["/v1/services/*", "/v1/service"],
		destinationURL: "http:/.../external-server-endpoint"
	}, {
		paths: ["/v1/services/*", "/v1/service"],
		destinationURL: "http:/.../external-server-endpoint"
	}]
}
```

The framework itself WONT be responsible for passing any headers. So, for the customer (A) case, the first and only configured filter will be the "auth" preFilter. It will authenticate the original request and send back a new set of headers containing the IDs required by customer (A)'s services.

The framework will send the request to the filters by wrapping them in a new json object that looks like:
```
{
	headers: [] // The orignal headers (or the headers returned by the last filter
	body: {} // The original body (or the body returned by the last filter
}
```
The framework will send the HMAC signature of the wrapped body as a *request header* called filter-auth-signature (or something like that)

Each filter will respond with  response code of 200, 4XX, or 5XX

200 means the request was processed successfully. The response body must be a json document with optional keys of headers and body (just like the request that was sent to the filter):
```
	{
		headers: []
		body: {}
	}
```
- If a headers key is present, the orignal headers will be replaced with it
- If a body key is present, the original body will be replaced withit
- If one webhook reports failure/rejection, then no more webhooks will be invoked further and the API will be terminated
- If one webhook returns a modified JSON (code 200), then this modified payload will be sent to the subsequent webhooks. The payload sent back if any by the last webhook, will be used to process the API command at Rancher.
- 4XX or 5XX means there was an error and the code and boidy is sent directly back to the user

### Questions I have and response to questions from the original spec:

RE: Post Hooks: <For future>
	- When do we need to deliver post hooks?

RE: Even if some “post” hook fails, continue processing next “post” hooks
	- Why? This seems bad.

RE: "Serial Id [some sort of UUID that is comparable/can be sorted]"
	- What is this for? I didn't understand it.

RE: Any other HTTP code returned will result in Rancher giving out a standard error message to the user because the user should  know that something is wrong with the backend. The actual error returned by the customer (B) governance API should be logged by Rancher in this case.
	- Why do we need to hide the error returned? Can filters handle this and just return the right thing?

RE: For customer (B), we need to define hooks per environment while for customer (A) they will be global, but the scope can be introduced to the service later. Also the hooks applicable and order of hooks of an enviroment can be stored with enviroment in cattle DB and read from cattle.
	- We should be able to get way with not having to do this ourselves. The auth filter we are writing for  customer (A) will inject headers to fully identify the user/project. The customer (B) filter should be to make any decisions it wants based off of that information. They can/should configure user specific rules out-of-band from Rancher.	

RE: Updating this config file is another problem – Will it be UI rewriting the file like the catalog setting?
	- The config json is a setting. If its value changes, we relaunch the proxy filter.

RE: The original config json having both an apiPath and apiURL
	- Why do we have both of those? We should only need api path

RE: The original config json having a secretToken field
	- What is the point of this exactly?

**Comment by alena1108** [comment]
@cjellick 

> RE: "Serial Id [some sort of UUID that is comparable/can be sorted]"
- What is this for? I didn't understand it.

It was needed so the external webhook service knows the order of the calls processed by api-proxy-filter service (presuming api-proxy-filter forwards (n) calls simultaneously to external webhook service)

**Comment by alena1108** [comment]
>> RE: Even if some “post” hook fails, continue processing next “post” hooks
>> - Why? This seems bad.

we should think more about this one. Because at this point of failure pre-hooks were executed + the call was processed by cattle (the object + corresponding processes were executed); and we do not rollback these changes. If we decided to fail the request on the posthook, then we should add some handling for the re-tried request

**Comment by prachidamle** [comment]
@cjellick  here are the answers to your questions:

RE: Post Hooks: 
- When do we need to deliver post hooks?
-- These are needed to be delivered after the API request has been processed by Rancher/(or by configured apiURL). 

RE: Even if some “post” hook fails, continue processing next “post” hooks
- Why? This seems bad.
-- This is because the API request has already been processed, there is no way to do a rollback of the request. So calling the post hooks is kind of event notifications

RE: "Serial Id [some sort of UUID that is comparable/can be sorted]"
- What is this for? I didn't understand it.
-- This is for the filters to understand the order of requests.

RE: Any other HTTP code returned will result in Rancher giving out a standard error message to the user because the user should know that something is wrong with the backend. The actual error returned by the customer (B) governance API should be logged by Rancher in this case.
- Why do we need to hide the error returned? Can filters handle this and just return the right thing?
-- This is customer(B) requirement that the error be logged at Rancher and not shown to user

RE: For customer (B), we need to define hooks per environment while for customer (A) they will be global, but the scope can be introduced to the service later. Also the hooks applicable and order of hooks of an enviroment can be stored with enviroment in cattle DB and read from cattle.
- We should be able to get way with not having to do this ourselves. The auth filter we are writing for customer (A) will inject headers to fully identify the user/project. The customer (B) filter should be to make any decisions it wants based off of that information. They can/should configure user specific rules out-of-band from Rancher.

-- Again this is a requirement by customer(B) - mainly ability to define filters per environment.

RE: Updating this config file is another problem – Will it be UI rewriting the file like the catalog setting?
- The config json is a setting. If its value changes, we relaunch the proxy filter.

RE: The original config json having both an apiPath and apiURL
- Why do we have both of those? We should only need api path
-- I think for customer(A), there is a possibility that the API will not be always processed by Rancher? It maybe processed by some external service. So we need to know what should the proxy invoke for a particular path

RE: The original config json having a secretToken field
- What is the point of this exactly?
-- Customer(B) wants the request made to the filter have a way form of authentication applied for security. They will be creating and uploading the secret tokens Rancher has to use

**Comment by prachidamle** [comment]
@cjellick some questions:

- What are the methods[post, delete] for? Are they specifying the request type for the given Paths or for endpoints? 

- What about the 304 filter response for Customer(B)? Are you proposing to use 200 even for that and have empty body{}

- Also, if we assume that for Customer(B), we will get the rancher account info and the external account info for the request, by calling Customer(A) auth filter, then that means we need the ability to specify multiple endpoints for a single path in the json file. [first the auth filter, then Customer(A) configured filter]
It won't be the case that a path invokes a single endpoint.

- We need to support ability to define filters per environment for Customer(B) requirement

**Comment by cjellick** [comment]
- The methods indicate what the filter applies to. All calls to the filters from the framework are POSTs
- That was replaced by wrapping the original body and headers in a new json object that have optional headers and body fields.
If the request is not modified by the filter, the response becomes:
HTTP/1.1 200 OK
Body:
{}

Admittedly, removing the 304 response is splitting hairs a bit, but our motivations were:
We were misusing the 304 response code as it is defined in HTTP spec
We reduce the number of possible response codes. Now we have:
200 means the filter succeeded in processing,
400-500 are opaque errors that we return directly to the suer
201-399 are invalid response codes from the filter and are not supported

... TBC

**Comment by cjellick** [comment]
> Why do we need to hide the error returned? Can filters handle this and just return the right thing?
> -- This is customer(B) requirement that the error be logged at Rancher and not shown to user
But why does the filter-framework need to make this decision? Why can't it be the specific filter deciding what the response should be? They have the knowledge of what should and should not be returned.

**Comment by deniseschannon** [comment]
CLosing to use https://github.com/rancher/rancher/issues/7749 to test.
