### ISSUE TITLE
"docker ps" shows no ports (exposed or/and public) since 1.2.0 

### ISSUE THREAD

**Issue by am813nt** [rancher/rancher#7162]
**Rancher Version:**
1.2.1
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian Wheezy, SMP Debian 3.16.36-1+deb8u1~bpo70+1 (2016-09-08) x86_64 GNU/Linux, KVM-based VM 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, internal DB 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Since upgrade to 1.2.0 there is no ports in **docker ps** output. But they are in 1.1.4. Yes, the docs say that ** "when ports are exposed in Rancher, it will not show up in docker ps as Rancher manages the iptable rules to make the ports fully dynamic" **, but this behavior breaks completely some services, e.g. Consul Registrator. And if it so, there should be some kind of info about it in upgrading notes.

**Comment by CleverWhiteWolf** [comment]
I do agree with you. 
I faced with the same issue and now I have to find an another way how to re-build my existing docker cluster, because I use Registrator tool for putting data about services into Consul server.

**Comment by muteor** [comment]
I have the same problem, I had a working setup with registrator but now all containers managed by rancher are ignored with no published ports error.

Anyone got a workaround?

**Comment by JaviSabalete** [comment]
Same problem here

**Comment by vincent99** [comment]
This will not be coming back.  1.2+ use CNI for networking, which involves giving docker `--net none`, which disables the port display in `ps`.  Even in < 1.2 the port information was not necessarily correct, Rancher has always allowed you to change the host ports of running container and there is no way to make`ps`reflect that.

**Comment by muteor** [comment]
You should remove the consul-registrator from the community catalog btw :)

My final workaround was to ditch Rancher for Kubernetes.

**Comment by leodotcloud** [comment]
@muteor Kubernetes uses CNI too and the pods are launched with `--net=none`, so `docker ps` and `docker inspect` wouldn't show this information either with/without Rancher.

**Comment by JaviSabalete** [comment]
Well redirect port with rancher 1.2 not working. I was thinking was for this but maybe not...

**Comment by cabrinoob** [comment]
Same problem here ...
It seems very difficult (maybe impossible) to achieve a third party registration in a CNI network context.

It would be very nice if rancher could provide a registration mechanism to a third party backend like Consul, etcd or zookeeper.

**Comment by cloudnautique** [comment]
@cabrinoob, it can't be done with things that listen directly to the docker socket events(ie. Registrator)  since its `--net none`. 

 It could be done by looking at rancher-metadata.`./container/ports/` will give you x.x.x.x:PORT:internal mappings. Where x.x.x.x will be a specific IP that is bound, or `0.0.0.0` which could be substituted with the `./host/agent_ip`. I am using relative paths, because it would depend on the entity responsible for registering. The container would use the `self` paths and a separate observer would watch the `/container` or `/services` endpoint. Here are the metadata docs: http://docs.rancher.com/rancher/v1.3/en/rancher-services/metadata-service/

 If all of the services are consumed within Rancher, you could just use rancher-metadata and DNS directly. 

It would make a good community catalog entry for a `rancher-registrator` that supported all the different backends :)
