### ISSUE TITLE
Rancher Database uses an absurd amount of RAM

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#7177]
**Rancher Version:**
1.2.1

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu/aws

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with external DB (RDS)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I have been having some major slowness with rancher lately (1.1.4). After trying to find why its so slow, it looks like most of the time is spent using swap space on the database.  MySQL is out of memory. So, I decided to try 1.2.1 in an isolated environment. 
I spun up a rancher host which uses a t2.medium AWS RDS database. This means that MySQL should have 4g of ram available to it. I then created a single environment with 3 nodes, and  15 services. Oddly enough, the DB was still running out of memory on this small deployment. I feel like 4g of RAM is way more than sufficient for such a small deployment. Yet AWS shows memory usage in the red, and only 100MB of ram is freeable. 
So results: 3 nodes, 15 services = about 45 containers. An RDS t2.medium can not handle this relatively small deployment. I really hope I dont need a dedicated large DB just for rancher.

**Comment by ibuildthecloud** [comment]
@nhumrich Is this upgraded setup or a fresh install?  The DB usage in 1.2 should be significantly less.  That size deployment should be maybe 500mb of DB at most.  If this is an upgraded setup I can explain why you'd see more and what to do about it.

**Comment by nhumrich** [comment]
fresh install

**Comment by nhumrich** [comment]
oh, actually it was fresh at 1.2, then upgraded to 1.2.1

**Comment by ibuildthecloud** [comment]
@nhumrich Is there a possibility that you could share the DB dump?  I'd like to look at the data size.  I would agree that 4gb is absurd and it is not normal for a clean 1.2.1 installation.

**Comment by vincent99** [comment]
Also we know it runs ok (at reasonable scale, like your 45 containers) with the embedded DB + the server container on hosts that have 1 or 2GB total.. so this doesn't really add up.

I wonder if this is a case of the AWS UI displaying a mostly meaningless metric because MySQL is using all the RAM for cache but doesn't mark the pages as free-able because the instance is tuned to be dedicated to MySQL, since that's what it is...

**Comment by nhumrich** [comment]
Id be happy to share whatever with yall. However I am a noob with MySQL and have no idea how to get a heap dump. My couple minutes of googling gave me nothing useful. Any ideas? Or do you just want a basic data dump?

**Comment by vincent99** [comment]
He just meant `mysqldump`

**Comment by nhumrich** [comment]
Sent the dump to Shannon.

**Comment by jurajseffer** [comment]
I am experiencing this with fresh install of `1.1.4` (had to do a fresh install after trying out 1.2.0 because it died numerous times)
 - two environments
 - ~100 containers
 - RDS db.t2.medium (4GB RAM), gp2 ssd, MySQL 5.7.16
 - no flapping/unstable containers
 - MySQL data size is tiny

I don't recall whether it's been like this since the start as it's been running for longer than 2 weeks (max cloudwatch data available).

There are however these messages in the docker log. From what I've read they can be ignored:
```
{"log":"time=\"2017-01-05T21:05:53Z\" level=error msg=\"Error unmarshalling rancher-compose.yml under template: DATA/library/infra-templates/windows/0, error: yaml: unmarshal errors:\\n  line 1: cannot unmarshal !!str `2` into model.RancherCompose\" \n","stream":"stdout","time":"2017-01-05T21:05:53.330282472Z"}
{"log":"time=\"2017-01-05T21:05:53Z\" level=error msg=\"Skipping the template version: windows/0, error: yaml: unmarshal errors:\\n  line 1: cannot unmarshal !!str `2` into model.RancherCompose\" \n","stream":"stdout","time":"2017-01-05T21:05:53.330293102Z"}
{"log":"time=\"2017-01-05T21:10:52Z\" level=error msg=\"Error unmarshalling config.yml under template: DATA/library/infra-templates/ebs, error: yaml: unmarshal errors:\\n  line 7: cannot unmarshal !!map into string\" \n","stream":"stdout","time":"2017-01-05T21:10:52.565860898Z"}
{"log":"time=\"2017-01-05T21:10:52Z\" level=error msg=\"Error unmarshalling config.yml under template: DATA/library/infra-templates/efs, error: yaml: unmarshal errors:\\n  line 7: cannot unmarshal !!map into string\" \n","stream":"stdout","time":"2017-01-05T21:10:52.566349587Z"}
{"log":"time=\"2017-01-05T21:10:52Z\" level=error msg=\"Error unmarshalling config.yml under template: DATA/library/infra-templates/healthcheck, error: yaml: unmarshal errors:\\n  line 7: cannot unmarshal !!map into string\" \n","stream":"stdout","time":"2017-01-05T21:10:52.566778788Z"}
```

Last two weeks of monitoring data.
![screenshot from 2017-01-05 21-16-49](https://cloud.githubusercontent.com/assets/2191852/21697927/9ee99210-d38c-11e6-9dff-b2530c4fda80.png)

All I can think of at the moment is that something like extreme logging events or querying with joins using lots of buffers have not been freed up and this will now continue forever unless I reboot the instance.

**Comment by aemneina** [comment]
There have been optimizations made since 1.2.x... if you can reproduce this on a modern iteration of rancher, please file a new issue.

**Comment by Interaze** [comment]
I'm just looking back at this after seeing the RAM usage in 2x and am crying

**Comment by vincent99** [comment]
etcd and full k8s maybe, but k3s with the sqlite backend should be relatively comparable.
