### ISSUE TITLE
Update k8s services to work with internal or other non public CAs

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7204]
To support the case if a user is running an internal or other non-public CA, need to update all k8s rancher services to trust the root CA. Services below have to be updated:

rancher/k8s, rancher/kubernetes-agent, rancher/lb-service-rancher

The example of the change can be found in this PR:

https://github.com/rancher/kubectld/pull/12

@cloudnautique @deniseschannon

**Comment by wlan0** [comment]
Addressed by 
https://github.com/rancher/kubernetes-package/pull/18
https://github.com/rancher/lb-controller/pull/45
https://github.com/rancher/kubernetes-agent/pull/34

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.3.0-rc2 using self signed certs.

rancher-server is started with the following command - sudo docker run -d --restart=unless-stopped --name=rancher-server -v <cert>:/var/lib/rancher/etc/ssl/ca.crt rancher/server:v1.3.0-rc2

It is hosted behind nginx server that acts as a reverse proxy.

On the host , certs have to be copied to /var/lib/rancher/etc/ssl/ca.crt before running the host registration url which will already include -v /var/lib/rancher:/var/lib/rancher

Able to add hosts successfully to "cattle" environment.
All infrastructure stacks come up successfully.

Deploy K8s template - v.1.5.1-rancher1-7

All stacks in "kubernetes" comes up successfully except rancher-ingress-controller which keeps restarting - 
```
12/29/2016 4:51:07 PMtime="2016-12-30T00:51:07Z" level=fatal msg="Failed to create Rancher client Get https://sangee-test.rancher.space/v2-beta: x509: certificate signed by unknown authority"
12/29/2016 4:51:15 PMtime="2016-12-30T00:51:15Z" level=fatal msg="Failed to create Rancher client Get https://sangee-test.rancher.space/v2-beta: x509: certificate signed by unknown authority"
12/29/2016 4:51:23 PMtime="2016-12-30T00:51:23Z" level=fatal msg="Failed to create Rancher client Get https://sangee-test.rancher.space/v2-beta: x509: certificate signed by unknown authority"
12/29/2016 4:51:35 PMtime="2016-12-30T00:51:35Z" level=fatal msg="Failed to create Rancher client Get https://sangee-test.rancher.space/v2-beta: x509: certificate signed by unknown authority"
12/29/2016 4:51:44 PMtime="2016-12-30T00:51:44Z" level=fatal msg="Failed to create Rancher client Get https://sangee-test.rancher.space/v2-beta: x509: certificate signed by unknown authority"
1
```

**Comment by deniseschannon** [comment]
please test again with ` image: rancher/lb-service-rancher:v0.5.0` in the same template

**Comment by sangeethah** [comment]
Rancher Version:v1.3.0-rc2 using self signed certs.

rancher-server is started with the following command - sudo docker run -d --restart=unless-stopped --name=rancher-server -v :/var/lib/rancher/etc/ssl/ca.crt rancher/server:v1.3.0-rc2

It is hosted behind nginx server that acts as a reverse proxy.

On the host , certs have to be copied to /var/lib/rancher/etc/ssl/ca.crt before running the host registration url which will already include -v /var/lib/rancher:/var/lib/rancher

Able to add hosts successfully to "k8s" environment.
All infrastructure stacks comes up successfully.
Able to create services using Kubectl from UI.

Not able to connect to this rancher-server setup using the generated config. This issue is tracked in - https://github.com/rancher/rancher/issues/7235

Also helm workflow has issues which is tracked in https://github.com/rancher/rancher/issues/7234

**Comment by sangeethah** [comment]
Closing this issue since the remaining issues are tracked in #7235 and #7234
