### ISSUE TITLE
Removing service that has webhook reference causes screen to go blank

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7214]
**Rancher Version:** master 12/26

**Steps to Reproduce:**
1.  Create a service
2.  Create a webhook that references that service
3.  Delete the service
4.  Go back to webhook screen.

**Results:** Screen is blank.  Error - "receiver.js:17 Uncaught TypeError: Cannot read property 'get' of undefined"

**Expected:**  No error, screen to redraw.

**Comment by cjellick** [comment]
Discussed with @vincent99  and we decided that we'd only fix this in the UI for 1.3.

@tani do you want to verify @vincent99's fix for this and if that is good to go, assign back over to @mrajashree but change the milestone to 1.4?

**Comment by tfiduccia** [comment]
Version - master 12/29 - Verified that the UI no longer blows up.  Sending back to rajashree for backend fix.

**Comment by cjellick** [comment]
I don't think we should fix this one on the backend. The driver config is an opaque json blob as far as the webhook listing framework is concerned. The webhook is created independently of the service itself and should be managed separately by the user.

**Comment by vincent99** [comment]
I still disagree, that it happens to be implemented as two independent APIs is not relevant to the user.  Particularly because you can't even edit a hook, there is literally nothing useful you can do with that hook once the associated service is gone.

We never return links (or IDs to things) that will fail anywhere else in the API.  Nor leave dangling ID references with no referential integrity in the DB (that I know of).

**Comment by tfiduccia** [comment]
Version - master 1/17
Verified fixed
