### ISSUE TITLE
When creating a service with lots of scale, 1 container is always missing it's IP

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7217]
**Rancher Version:** master 12/26

**Steps to Reproduce:**
1.  Create a service, use hello-world, scale 1 and started-once
2.  Wait for it to go to started-once state
3.  Edit service and increase scale to 40
4.  Wait for all container to go to Started-Once state
5.  Go to Containers page and sort by IP

**Results:** Notice that 1 of the containers is now missing it's IP?  Always seems to be 1.  Tried it a couple of times with same results:
![image](https://cloud.githubusercontent.com/assets/11514927/21533939/72e1c87e-cd1d-11e6-8f01-fe549d642284.png)
![image](https://cloud.githubusercontent.com/assets/11514927/21533949/81714ea0-cd1d-11e6-9566-cb6f21c24599.png)

**Expected:**  All the containers should have IP

**Comment by leodotcloud** [comment]
@tfiduccia As discussed offline, could you please try this with 1.4.1?

**Comment by leodotcloud** [comment]
The networking logic is fine and the container is assigned an IP address as expected.

Due to race condition/timing issue in go-agent there are two problems seen:

1) The container starts and exits but by the time go-agent tries to find the IP address, the network namespace is gone as the container exited. Because of this the go-agent is reporting the status incorrectly as 'stopped'

Error message from one of the runs:
```
time="2017-02-14T21:17:37Z" level=error msg="Error processing event" err="no such file or directory" eventId=9a8d4a0c-6eb0-4ac7-8744-204d62d5966d eventName=compute.instance.activate resourceId=1ihm77 
```

2) The go-agent is in the process of reading the IP from the interface and the container started going down and the namespace is being deleted. In this scenario, the status is reported correctly but the IP is NULL.

There is no error reported in the agent log for this scenario.

**Comment by cjellick** [comment]
Don't this is priority 0 because why is the IP of a non-running container critically important? If the container were to stay up and running, the IP would resolve correctly. I'm going to remove that label.

That said, I think this should be resolved in 1.5 via https://github.com/rancher/rancher-catalog/pull/470

**Comment by cjellick** [comment]
Should* be fixed on master.

_\* i made a change to IP reporting for a different reason and have reasoned that it should also address this, but I didn't explicitly test this._

**Comment by tfiduccia** [comment]
Version - master 2/21
Verified fixed
