### ISSUE TITLE
IP detection problematic for behind-the-firewall hosts

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#7220]
Rancher always detects the wrong hosts IP for hosts that reside behind a firewall connecting to a Rancher server in the public Internet.

Not sure if there's a generic fix for all machine drivers.

But at least for a Custom host case, we should make it more obvious that users need to specify a host IP when they have a host behind a firewall connecting to Rancher server on the Internet.

**Comment by yasker** [comment]
Move out of 1.6 release.

Talked with Sheng L:

We need to find a way to deal with hosts behind the NAT, which Rancher server will only detect the public IP of it. So if there are multiples hosts behind the same NAT, they will be identified by the same IP then our overlay network and port mapping won't work.

Sheng thinks about using private IP instead of public IP for those hosts, but there can be other implications.
