### ISSUE TITLE
no such option Generate Config in UI for swarm cluster

### ISSUE THREAD

**Issue by vital-st1x** [rancher/rancher#7225]
Hi,

could someone please help me to find an UI option Generate Config for swarm cluster?

Clean latest rancher install.
More details in screenshot.

<img width="1233" alt="rancher" src="https://cloud.githubusercontent.com/assets/13592739/21550108/23d44b9e-ce08-11e6-808d-3fc4465868a3.png">

Thanks in advance.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`localauth` `admin`|
|Orchestration|`Swarm`|
|Route|`swarm-tab.console`|

**Comment by vital-st1x** [comment]
probably duplicated by https://github.com/rancher/rancher/issues/5346
but still unclear how to use docker swarm and get the access remotely (

**Comment by LLParse** [comment]
Hi @vital-st1x,

In order to administer a remote swarm, follow these instructions:

1. Install `docker` client on your host, must be the same version or newer (>=) than the Docker version comprising your swarm
2. Install `rancher` [CLI](https://docs.rancher.com/rancher/v1.2/en/cli/) and configure it to point to your installation
3. Use the CLI to find a host ID with label swarm=manager.
```
$ rancher --env swarm hosts
ID        HOSTNAME                                STATE     CONTAINERS   IP            LABELS          DETAIL
1h7       james-10acre-4.c.rancher-dev.internal   active    10           10.240.0.51   swarm=manager
```
4. Use the CLI to proxy swarm requests to this host. 
```
$ rancher --env swarm --host 1h7 docker node ls
ID                           HOSTNAME        STATUS  AVAILABILITY  MANAGER STATUS
4967wtc44cl83i5ce4m2o7qlq *  james-10acre-4  Ready   Active        Leader
```

Note that not all hosts are necessarily managers; only managers will be able to administer the swarm.

Hope this helps!

**Comment by LLParse** [comment]
Hmmm, thanks for pointing that out to me. I will see that the docs are updated.
