### ISSUE TITLE
Add ability to label hosts as non-schedulable unless explictly requested

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7254]
Add ability to tag hosts as "non-schedulable" unless there is an explicit host affinity rule to place containers on those hosts.

**Comment by cjellick** [comment]
Implemented with labels in the external scheduler.

Semantically should work like this:
Host A only allows containers with labels key1=val1, key1=val2, or key2=val3 to be schedule on them.

User should add a label like this to the host:
`io.rancher.host.scheduler_label_whitelist: key1=val1,key1=val2,key3=val3`

The result should be that only containers with label key value pairs matching one of the ones specified in the host label get deploy.

**Comment by vincent99** [comment]
Seems like it should be `io.rancher.scheduler.[something]` to match other labels.

You say OR, but is there some use-case where I want AND / only containers which have all the labels?  Perhaps:

`io.rancher.scheduler.require_any: key1=val1, key2=val2`
`io.rancher.scheduler.require_all: key1=val1, key2=val2`

**Comment by StrongMonkey** [comment]
`io.rancher.scheduler.require_any`,
`io.rancher.scheduler.require_all`,
`io.rancher.scheduler.require_more_than_one`,
`io.rancher.scheduler.require_more_than_two`,
`...`
`io.rancher.scheduler.require_more_than_X`, Is that also true? Are we extending the idea the concept here?

**Comment by sangeethah** [comment]
When specifying the rules , is there a need to support other conditional parameters like "!=","or","in","not in" .. like we support for  selectorLink in services?

In the absence of io.rancher.host.scheduler_label_whitelist label , we will allow for deployment of any containers. Once user sets this label on the host (or even in the case where we have edited the label on the host), we will continue to have the containers that does not satisfy the current rule (deployed before the label was set/edited) to be present in the host ? In the event of stopping the container and would starting the container fail ?

**Comment by vincent99** [comment]
I would like to err on the side of spring only the simpler use cases that can be easily explained and maybe show a summary of on the host list.

- `n [or more] of m`, in/not in seems excessive...
- `or` would be the same as `any`
- `!=` can be `_none`
- `in`/`not in`also sounds excessive to me... But the all/some/nice could allow the input to just be a key instead of a key=value to match just that a label exists (or not).
- if there is no label the host acts as today, eligible for any container.
-"allow no containers" is basically deactivate, don't need a new label for that.
- existing containers are where they are, they're not moved because you change the host label or start/stop them.   On upgrade/reconcile they could be rescheduled.
- global consists all the scheduler rules and press one on each eligible host.  So hosts that don't match will not get a container.

**Comment by cjellick** [comment]
@vincent99 @will-chan  @ibuildthecloud has brought up a different use case that he wants to know if users wants. It would be a different interpretation of this feature that would thusly semantically:

Through a label, Host A indicates that services with Label X MUST be deployed to it. 

So, the result is that it prevents services with a certain label (or potentially some other requirement) from deploying anywhere else in the environment.

The use case, as stated by @ibuildthecloud, is to allow admins to control where services get deployed in an environment. But honestly I don't quite see how this feature accomplishes that because it is still dependent upon users adding a certain label to their service.

**Comment by will-chan** [comment]
@cjellick @ibuildthecloud I think this generally satisfy the requirement.  What are you thinking that the label looks like?  In our original scheduling rules, we label host(s) with X=Y, and the add the hard host affinity rule on the service for X=Y.

Can we keep the rule the same on the service so it's not confusing to users and add a special label on host with something like OnlyDeployOnHostWithLabel=true to enable this?  That way nothing changes and this special label will now indicate that only services with a host affinity rule (soft or hard) can deploy on these hosts, and nothing else.

**Comment by StrongMonkey** [comment]
Current implementation https://github.com/rancher/scheduler/pull/35 works as following:
1. Host A has label: `io.rancher.sheduler.require_any: foo=bar, infra=true, Host B has nothing.
2. Launching a service with label foo=bar **or** infra=true, It will go to the Host A and Host B. Launching a service with no label, it will only go to Host B.
3. This does not guarantee Host affinity, but guarantee that Host A only accept service with label foo=bar **or** infra=true, and will reject any service without one of those labels.

**Comment by sangeethah** [comment]
Global services need to take into account  `io.rancher.sheduler.require_any``` flag set on the host. This should be similar to what is being tracked in  - https://github.com/rancher/rancher/issues/7772

Additionally , when host labels in `io.rancher.sheduler.require_any``` get edited/deleted/added   , we should be able to reconcile instances in the global services accordingly.

**Comment by StrongMonkey** [comment]
close in favor of https://github.com/rancher/rancher/issues/7795
