### ISSUE TITLE
namespace "kube-system" shown as empty

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#7259]
**Rancher Version:**
1.2.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS latest AMI, AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA 3 nodes external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.5.1
**Steps to Reproduce:**
Create K8s env as usual, on clean rancher 1.2.1
**Results:** 
namespace "kube-system" shown empty with no pods
![image](https://cloud.githubusercontent.com/assets/9369080/21605262/94e85f54-d1b0-11e6-8b8f-482eb95865db.png)

also in kubectl if i query "kubectl get pods --namespace kube-system" there's nothing shown
**Expected:**
namespace "kube-system" should show us all pods and containers, but it doesn't.

is it correct behavior and Rancher just "hides" system pods from us?  i wanted to see all components, and surprised that kubectl doesn't show them.  or maybe K8s is run somehow in "system cattle" and its components aren't pods (vs standalone K8s)?  (i didn't create cattle environment, only k8s)

**Comment by vincent99** [comment]
Kubernetes doesn't manage itself;  kube-system is there because it's created by default, and empty because there's nothing in it (in 1.3 I think the native dashboard  goes into there.)

Every environment can also run cattle services and we use that to deploy the kubernetes services, you can see them  under Kubernetes menu -> Infrastructure stacks.
