### ISSUE TITLE
Limit agent reconnects to prevent a backlog of processes

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7276]
**Rancher Version:**
1.2.2

Rancher can get into a situation where when incapacitated could schedule agent reconnects and create a large backlog of processes. Ideally, someone awesome could create functionality that would limit agent reconnects to prevent a backlog of processes

**Comment by sangeethah** [comment]
As part of validating - https://github.com/rancher/rancher/issues/7062 , following scenario was validated:

Tested with Rancher server version - v1.4.0-rc3
Had a K8s env with 3 hosts.
Had few Service/RC/pods running.
Deleted all the hosts.

There is no retry to get infra service containers up anymore.

Had a cattle env where there were ~50 services with scale 3 that were stuck in "activation" state because of allocation failures.

When this was the state , I am able to to add new host successfully.
Starting new services also succeeds.

**Comment by sangeethah** [comment]
@ibuildthecloud: Could you let me know if there are additional validations that need to be performed , other than what was done to validate and close #7062 , which is detailed in the previous comments.
