### ISSUE TITLE
Add Host With letsencrypt SSL Fail!

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#7299]
*Describe your issue here*
My Rancher Server running at port 51263, then use nginx agent to port 443 (proxy_pass), http2 enabled, chrome can browse it, no problem .

Then I copy letsencrypt cert1.pem to /var/lib/rancher/etc/ssl/ca.crt, and run rancher/agent, it showed:

INFO: Running Agent Registration Process, CATTLE_URL=https://xxx.com/v1
INFO: Attempting to connect to: https://xxx.com/v1
INFO: https://xxx.com/v1 is accessible
Traceback (most recent call last):
  File "./resolve_url.py", line 9, in <module>
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ERROR: returned
ERROR: --- START ---
ERROR: --- END ---
ERROR: Failed to load registration env from CATTLE_URL=https://xxx.com/v1 ENV_URL=
ERROR: Please ensure the proper value for the Host Registration URL is set

I don't konw what's wrong?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by zakhuang** [comment]
Rancher v1.3.0 Cattle: v0.175.2 UI: v1.3.5
is the same

**Comment by zakhuang** [comment]
Host Registration URL is set to https://xxx.com

**Comment by cnadeau** [comment]
I ran into the exact same issue on the exact same setup.

The agent was first provision using Azure driver and registered when the rancher server was using a self signed certificated which was put in /var/lib/rancher/etc/ssl/ca.crt as and it was reachable no problem.

I migrated the rancher server to use letsencrypt cert, which works fine when I provision another Azure VM, but I can't rerun the registration URL from this agent agent. Exact same log @ghost mentioned

**Comment by rsynnest** [comment]
I'm getting the exact same Python SSL errors.
**Environment** I am running Rancher Server behind Nginx Reverse Proxy which provides SSL via LetsEncrypt. When I try to install a Rancher Agent on the same Rancher Server, I get that Python SSL error. If I install a Rancher Agent on a remote host, it runs fine.

If I run the Rancher Agent interactively with `-it` and `-- bash`, SSL works via curl and openssl, but not via Python. This includes known sites like `requests.get(https://www.google.com)`. They all throw the same SSL CERTIFICATE error:
```
>>> import requests          
>>> import ssl                                                                                                                                                                                      
>>> requests.get('https://google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

Appears to be a Python-only problem with SSL libraries?

**Comment by rsynnest** [comment]
I was finally able to get LetsEncrypt working by running the Rancher Agent Host WITHOUT adding my LetsEncrypt certificate file to `/var/lib/rancher/etc/ssl/ca.crt` on the agent host as the Rancher docs suggest. Instead I just ran the agent as I normally would with no setup on the Host, and it worked. This was only after I deleted all files and directories in `/var/lib/rancher/*` in order to start fresh (though I wasn't able to remove `volumes` dir, getting a `cannot remove 'volumes/': Device or resource busy` even after removing all rancher containers and troubleshooting with lsof and fuser with no luck). I thought the entire rancher agent system was self contained, but the files in /var/lib/rancher/` persist after container removal and will mess things up if you try to start over your rancher environment from scratch. I believe this is because the `/var/lib/rancher/etc/ssl/host.key` is unique to each rancher master node.

If you've already run a failed rancher agent and are stuck with this error, remove all rancher agent containers and run `sudo rm /var/lib/rancher/*` on the agent Host (you can ignore the "cannot remove volumes" error), then run the agent as you normally would without any custom ca.crt and it should work for LetsEncrypt. The custom ca.crt was breaking Python SSL for some reason, maybe I was using the wrong cert file, the rancher docs are a bit vague simply saying "place the cert file in /var/lib/rancher/etc/ssl/ca.crt". My previous attempts of using `fullchain.pem` or `cert.pem` in `/var/lib/rancher/etc/ssl/ca.crt` all failed despite following rancher's docs as closely as possible (my environment is slightly different so I couldn't follow to a T). So far the only thing that works for me is to run the rancher agent without the `ca.crt` file. I am also running the Rancher Server without a `ca.crt` file mounted into the master /var/lib/rancher/etc/ssl/ca.crt`, this works because I am handling SSL in my reverse proxy.

**Comment by Shingaz** [comment]
I had the same issue due to an internal PKI. The `/var/lib/rancher/etc/ssl/ca.crt` file must contain the certificate chain as per documented here: https://curl.haxx.se/docs/sslcerts.html.

I my case I had to generate it: `cat [root CA crt] [intermediate CA crt] [server crt] > ca.crt`
