### ISSUE TITLE
Custom Host Label Substitution

### ISSUE THREAD

**Issue by TKCen** [rancher/rancher#7305]
In the custom host form when you add labels to the config which contain command substitutions the special characters are replaced with their URL Percent Encoding in the final command. This shouldn't be the case.

![customhost](https://cloud.githubusercontent.com/assets/5960303/21679357/f8c9cc80-d343-11e6-92db-193ed880762d.PNG)
 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`hosts.new.index`|

**Comment by vincent99** [comment]
`CATTLE_HOST_LABELS` is expected to be a urlencoded `key=value&key=value` query-string style value.  It isn't what you want, but that is the correct encoding which will produce a label with the value that you asked for, the literal string `$(curl ...)`.

Regardless of escaping those would not be evaluated by the shell because the value is single-quoted.  All the UI is doing is adding to the generated command in 5, so you can just add your own double quoted `-e CATTLE_HOST_LABELS="aws.instance_id=$(curl...)&aws.availability_zone=$(curl...)"` to it.
