### ISSUE TITLE
Cannot create new services

### ISSUE THREAD

**Issue by mostafahussein** [rancher/rancher#7339]
**Rancher Versions: 1.2.1**

**Docker Version: 1.12+**

**OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu - Vultr**

**Setup Details: Single Node**

**Environment Type: Cattle**

**Steps to Reproduce:**
I am not sure how to reproduce this issue but suddenly I am not able to create services anymore, it keeps waiting forever as the following screenshot, this process is running for more than 8 hours with no luck. I am trying to deploy the wordpress stack. also the same problem with a custom stack not just the wordpress

![screenshot from 2017-01-07 01-16-48](https://cloud.githubusercontent.com/assets/4104127/21736176/75ad486a-d477-11e6-95f1-ef23817308e7.png)

I cannot see more errors that could help me in order to debug this issue in a better way but I seeing this under  `InstanceAllocate` and the Cause is `N/A`:

```java
io.cattle.platform.async.utils.TimeoutException: Timeout
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl.retry(RetryTimeoutServiceImpl.java:43)
	at sun.reflect.GeneratedMethodAccessor390.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

The `Hosts` is separate from where Rancher is deployed.
Is there any other log should I add to this issue for a better investigation ?
What should I do in order to figure out the reason of this issue ? 

UPDATE:

I tried to add `Host` to new environment but i got the same result with the default rancher containers `ipsec `, `network`, `healthcheck`

**Comment by Moeser** [comment]
I'm having this same problem now across an entire HA cluster running v1.3.3.   The containers simply do not schedule, and I'm seeing the same pattern of activating, waiting, waiting, activate.wait.exception in the service logs in the UI.  Nothing shows up in the agent logs.  I've checked the server logs but this is a fairly large cluster, so it's hard to tell which messages are related to containers not getting schedule.  I checked the hosts and they're all online and show up in the UI without any connection problems.

I tried to make the service as simple as possible.  I simply added a service called 'test' and accepted all of the defaults, including the ubuntu:14.04.3 image.  Even with everything at default it completely fails to schedule the containers.

Even more details and things I've tried:  I tried upgrading the kernel on the agents, and also upgrading them from docker 1.12.1 to 1.13.0, but that had no affect.  I also tried restarting all of the rancher server containers, then tried restarting all of the rancher server hosts.  I tried restarting the agent hosts, and the agent docker, and the agent container itself.  The problem seems intermittent, as we had this issue come up two days ago, and it mysteriously went away over night without any changes.

**Comment by Moeser** [comment]
@mostafahussein since this issue was created 21 days ago, were you able to find any work-arounds to the problem?

**Comment by mostafahussein** [comment]
Unfortunately, I went with the available docker cli tools itself since no reply or solution provided on this issue :(
In your case if you have a running production environment then you need to prepare yourself for a backup plan. for me I was just testing rancher before using it in a production environment and when this issue happened I decided not to go with a fresh install as this is was a random issue that might happen again.

I wish to find a solution for this issue as rancher is really a helpful project but these kind of issue could cost a lot in a production environments

**Comment by aemneina** [comment]
There were quite a few issues with scheduling post 1.2, that have since been resolved. Is this reproducible in something more recent (like 1.5.6+)?
