### ISSUE TITLE
HAproxy Load Balancer

### ISSUE THREAD

**Issue by joshuacox** [rancher/rancher#7347]
**Rancher Versions:** v1.3.1
Server: 0.7.1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I think this is out of date:

https://docs.rancher.com/rancher/v1.3/en/cattle/adding-load-balancers/

Now that the catalog has taken over in place of the services? But the catalog doesn't appear to have the old load balancers, just traefik and the ELB, is someone going to port the old HAproxy LB? Or am I just failing to find it? Nonetheless the 'add services' in the docs seems to be outdated.

**Comment by vincent99** [comment]
What is it you think is out of date?  There is no catalog item for HAProxy, and will not be because we support internal balancers within a stack (which can then itself be a catalog template)  There is still an API for creating a balancer service type and defining the rules for it.  

What has changed between 1.1 and 1.2 is that it takes and runs an actual docker image, which reads the generic config describing the balancer from metadata and sets itself up as HAProxy config.  In <=1.1.x it was a "fake" image name and Cattle generated and pushed down the specific HAProxy config.

So it is now possible to create alternate implementations which read metadata and configured/run some other load balancer software (or hardware).  But none of the community catalog entries you're talking about are currently doing that.

**Comment by joshuacox** [comment]
No I'm mistaken, sorry, thanks for clarifying
