### ISSUE TITLE
Add ability to set more backend options (example SSL)

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#7356]
Please add the ability to indicate whether the backend service is using SSL or not or better yet please give the ability to add additional backend options.

Right now the built in load balancer is unable to proxy traffic to a backend that is using SSL.

**Comment by vincent99** [comment]
`tcp` or `sni` will pass the unmodified SSL request to the backend to do termination at the container.

Termination at the balancer + re-encryption requires extra config (the cert on the containers probably isn't in public CAs) and latency and is mostly a waste of effort because the request is already going to the target container over IPSec anyway.

**Comment by ekristen** [comment]
I believe its wrong to assume that all applications both internal and external within rancher will never use HTTPS.

* What if it is an application that only supports HTTPS and you want it in your stack and you need to load balance it?
* What if you want to use rancher to proxy a service that is in your VPC but is external to rancher and only supports VPC?

The answer to both of those right now is that you can't because haproxy assumes it'll never by HTTPS on the right side of the proxy.

**Comment by vincent99** [comment]
Common enough to be exposed in the UI and possible are not the same thing.  Neither of those are common configs that we want to confuse users with in the UI.  But in 1.2+ you can name the backends and provide custom config for almost anything, including the `server` lines:

https://docs.rancher.com/rancher/v1.2/en/cattle/adding-load-balancers/#custom-haproxy-configuration

**Comment by ekristen** [comment]
In the load balance configuration screen you could simple add a Protocol (HTTP/HTTPS) just like you have on the left side, this is what Amazon ELB does. 

I still think it is short-sighted to think or believe that since IPsec is being employed that all apps that need to be load balanced shouldn't use HTTPS or won't use HTTPS.

**Comment by vincent99** [comment]
Our approach for the balancer is to give you first-class API/UI/compose options for the common functionality that covers the majority of usage and make everything else possible through custom config.

Let's say I add a "simple" option for backend protocol...  Now I also have to have:
  - An option for whether the certificate should actually be validated for that connection (because SSL is largely pointless if you don't) or not (because convenient and what everyone will actually want).
  - A way to define the expected CA cert and ship that down to the haproxy container, because they're all going to be self-signed and untrusted.
  - A way to update the CA cert when it's expiring soon.
  - An option for which TLS version should be allowed or rejected for that connection because MITM forced downgrades.
  - ...etc.  And all of these options have to map to something in other possible load balancer implementations, which may not even offer a relevant equivalent.

There's about [60 things](https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#5.2) that can go on a server line, and turning on SSL backends is *by far* the single most complicated one you could pick; nearly half of the others relate to it, and now I've got a completely incomprehensible form to show to a normal user.

It's particularly bad because this is an option that "sounds" good ("https is more secure, I must want that" or "the source protocol is https so the target one should probably be too") but provides negative value to most users when it doesn't work because their backend doesn't actually speak TLS, or it does work but burns CPU and latency re-encrypting requests over IPSec network.

Trust me, we have plenty of experience with users just trying to setup ELB to terminate the server container correctly.
