### ISSUE TITLE
Make images for system k8s services configurable

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7362]
In no internet mode, default k8s images kubelet uses for pod + Rancher use for dashboard/helm/skydns/heapster - will be unable to pull, and k8s will fail to deploy in this mode. We have to make them configurable via template.

1) For kubelet, it can be done using ```pod-infra-container-image``` flag (default value is empty):

https://github.com/kubernetes/kubernetes/blob/ed5a23652566b48694ccdfacc5cff0790905a1a1/cmd/kubelet/app/options/options.go#L141

2) for skydns/helm/dashboard/heapster, we'd have to pass them to addon manager command 

@will-chan

**Comment by wlan0** [comment]
Testing Plan
==========

Need to test 
1. custom kubectl infra image and
2. Addon disable functionality 

Pre-requisites:
=============
1. You need rancher/k8s:v1.5.2-rancher1-1

Steps to test: 
============

1. Create a new rancher setup with atleast 1 host added.
2. Choose kubernetes from the infra catalog
3. Pick the version v1.5.2-rancher1-1
4. In the options, set Disable addons to true
5. Similarly, set the pod infra image to `gcr.io/google_containers/pause:2.0`
6. Click on Deploy

Once kubernetes is deployed, go to kubectl cli and ensure that none of the addons have been created. This can be done by 

`kubectl -n kube-system get pods`

You should not see any pods starting with names tiller, dashboard or kube-dns

In order to test the new infra image, create a pod in that cluster , for eg.

`apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80`

Create the above yaml file. This will create a rc that will inturn create a nginx pod. Now, login into the host that has the nginx pod(check the host UI in rancher), and execute the command

```
docker ps | grep POD
7a1386a7e782        gcr.io/google_containers/pause:2.0                     "/pause"                 54 minutes ago      Up 54 minutes                           k8s_POD.d8dbe16c_deis-registry-proxy-pgcw5_deis_8fa2356b-dda8-11e6-aa94-66b9f05ad989_5a1af9cc
```


you should see that the IMAGE name in the output is `gcr.io/google_containers/pause:2.0`

**Comment by soumyalj** [comment]
Tested with k8s v1.5.2-rancher2-1. No addons are created with addons disabled. With pod infra image set to ```pod infra image to gcr.io/google_containers/pause:2.0```, the pods created have the expected image as below: 
```
soumya@soumya140rc2bugtest-10acre-2:~$ sudo docker ps -a|grep POD
21289d15272d        gcr.io/google_containers/pause:2.0   "/pause"                 16 seconds ago      Up 15 seconds                                   k8s_POD.6059dfa2_k8testrc2-new-wn3gq_testingress2_78357be5-e34e-11e6-8b15-025ecd2f5572_510a923c
b4756dfb16b3        gcr.io/google_containers/pause:2.0   "/pause"                 5 minutes ago       Up 5 minutes                                    k8s_POD.6059dfa2_k8testrc2-sm4bg_default_c98ccb65-e34d-11e6-8b15-025ecd2f5572_c569093d
7afeed7ce68b        gcr.io/google_containers/pause:2.0   "/pause"                 6 minutes ago       Up 6 minutes                                    k8s_POD.6059dfa2_k8testrc1-wdrdd_default_8ff4458c-e34d-11e6-8b15-025ecd2f5572_dcbf1884


```

**Comment by alena1108** [comment]
@soumyalj could you try installing addons by hand for the case when addonmanager is disabled? here is the instructions: https://gist.github.com/wlan0/715983587c26884578eb3f39c9df0097

**Comment by alena1108** [comment]
@imikushin could you share the skydns source templates with qa? So they can test deploying it after the fact and verifying that stuff works.

**Comment by imikushin** [comment]
KubeDNS templates:
1. we take `*.yaml.sed` files from https://github.com/rancher/kubernetes/tree/v1.5.2-rancher/cluster/addons/dns and 
2. apply these `sed` rules to them: https://github.com/rancher/kubernetes-package/blob/master/package/dns.sed

**Comment by galal-hussein** [comment]
I tested creating the addons manually by following the instructions mentioned by @imikushin, I was able to kubedns and dashboard and ran the dns validation tests, all passed.

**Comment by deniseschannon** [comment]
We need to support being able to support the addons for no internet installations.

**Comment by wlan0** [comment]
A new feature has been added in v1.5.0-dev where users can specify the private mirror registry (that mirrors both gcr.io and docker.io). The addon images will be pulled from the private registry instead of the default registries in this case.


Steps to test:

Create a private registry which mirrors both gcr.io and docker.io
Specify the registry URL in the launch param
Ensure that all addons are started (helm, heapster, dashboard, kube-dns)

**Comment by galal-hussein** [comment]
@wlan0 I followed the steps you specified and installed a docker registry that mirrors both gcr and docker.io and specified it as registry url in the launch parameter and all the addons started correctly.
