### ISSUE TITLE
Unable to get ports exposed on host when using Docker for Mac.app

### ISSUE THREAD

**Issue by ruimarinho** [rancher/rancher#7366]
**Rancher Versions:**

Server: v1.3.0

**Docker Version:**

1.12.5 (stable channel)

**OS and where are the hosts located? (cloud, bare metal, etc):**

macOS running Docker for Mac.app

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Start rancher, launch an hello world container, create a load balancer and expose port 80.

**Results:** 

Rancher is not able to expose the given port on the host - it stays bound to the agent ip only, making it inaccessible to the host.

**Expected:**

Rancher exposes the load balancer port on the host. Running `docker ps` shows a mapping of the haproxy `0.0.0.0:80 -> …`.

**Note**

The latest docs clearly state that Rancher is not supported on Windows and macOS, so I'm not sure if we should report issues with Docker for Mac.app at all when it's clearly not even intended to work (although 1.1.4 still works without issues). Let me know what's your position here.

**Comment by vincent99** [comment]
1.2+ uses CNI for networking, which manages iptables rules to make ports available.   This does not work with the shenanigans Docker for Mac does to pretend the the ports you request are bound directly to your Mac and not the Linux VM you're actually running behind the scenes.

**Comment by ruimarinho** [comment]
That's what I suspected. Considering that CNI is the way to go, should we wait for Docker for Mac.app to hijack these evens in future versions?

**Comment by vincent99** [comment]
@ruimarinho I wouldn't get your hopes of that up.  More likely is we'll have some sort of a "Rancher for Mac" that packages it nicely.  You can try this script that I use for running on my Mac: https://github.com/rancher/10acre-ranch/#docker-machine-on-macos

**Comment by ruimarinho** [comment]
Personally, one of the things that I really enjoyed on Rancher was the ability to simply run it as a container-only infrastructure. Docker for Mac.app was the first time that made Docker on macOS almost feel like we, macOS users, could run Docker natively. Gone were the times of `eval $(docker-machine foo)` and a dedicated VM.

Rancher, combined with this seamless experience, enabled lots of developers who then also became "devops" by helping connecting code to infrastructure (as in Rancher Stacks). IMHO, that was one of the key selling points of Rancher vs Kubernetes. I'm not saying that the new setup is hard (10acre-ranch works really well so thanks for that), but the experience with v1.2+ puts it on par with minikube. 

I'm pretty sure that Rancher v1.2+ is way, way better than v1.1, specifically in terms of networking and that the complexity and modernisation justifies all of this (like CNI), but now that the magic is gone, I keep getting back old memories I'd rather not have, even with all the improvements around Hypervisor.framework like xhyve.

I hope this comment is not taken as a rant as I have a lot of respect for the work going on this project. I just wish we could get the benefits of v1.2+ with the seamless experience of v1.1.

**Comment by vincent99** [comment]
I hear what you're saying and we sympathize but there's just not really much we can do about it.  D4M since the early betas (when you still accessed published ports on something like `docker.local`) adds a set of network abstractions with assumptions about the world consisting of one Docker daemon which just don't fit well with a project whose job is to manage multiple daemons.

FWIW <= 1.1.x doesn't really work all that well either (in current versions of D4M).. some examples:

To register the "mac" (moby VM) as a host you have to know it's secret 192.168.6(4|5).1 IP and set the registration URL accordingly, because they remap ports as "localhost" on your Mac but "localhost" to the agent (or any other container) is itself, not the server.

If you connect your iPhone to make calls from your Mac ("Wi-Fi calling") that takes up `4500/udp` on the Mac, which means the network agent won't start up and then nothing else wlrks.  This part is actually *improved* by CNI/1.2 since docker is no longer told about the port, it doesn't try to remap it on the Mac, and the agent can start up correctly now.  But the ports your application publishes don't get given to Docker either, so they are not accessible on `localhost:1234` even though they are actually published (in the moby VM).

**Comment by ruimarinho** [comment]
Indeed, I'm completely aware of that. I'm from the `docker.local` time (back when VPNKit was optional) and since that merge we've had to update our cattle agent ip references to the special 192.168.6(4|5).1 ip, as well as find workarounds for other small things. Those little annoyances could mostly be automated thanks to the flexibility of the rancher agent, so for me that was a small price to pay :)

Thank you for listening and I do hope the Docker/Docker for Mac.app teams work together with the community and framework authors to provide the necessary tools so that projects like Rancher don't have to be in this position of whether or not to support a specific OS or configuration, which is contrary to the philosophy of Docker itself.
