### ISSUE TITLE
When upgrading network-services, it gets stuck in `Upgrading` state

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7375]
When attempting to upgrade network-services that have new metadata images, the services may get stuck in upgrading state due to a scheduler bug.

Workaround: Stop scheduler, finish upgrade and start scheduler again.

**Comment by Haks1** [comment]
How can I stop the scheduler ?

I was stuck in upgrade too, a guy of my team did the mistake of starting all the upgrade at the same time, so with network-service for exemple, I just did "cancel upgrade" in the stack page, then it was in an other state that proposed me "Rollback", which worked.

I got that problem on many stacks, it worked for all, but not with IPsec: https://puu.sh/thQHn/793dcde2d0.png

IPsec is stuck creating new containers and I can't do anything because it's used by other instances (it says that even if I stop them).

> Component		Version
> Rancher			v1.2.1
> Cattle			v0.174.8
> User Interface		v1.2.39
> Rancher Compose	v0.12.1

**Comment by deniseschannon** [comment]
@Haks1 You can click on `stop` next to the scheduler service. :) And start it back up after the services have been upgraded.

I cannot speak as to wehther this scheduler fix would fix your issue, but I know it's a known issue with network-services upgrade when upgrading the metadata service.

**Comment by deniseschannon** [comment]
Fixed in scheduler/v0.5.2.

**Comment by soumyalj** [comment]
Tested with upgrade from v1.2.2( with an older template) to v1.3.1-rc3 and v1.3.1-rc4. Scheduler was upgraded first and then network services. The network services upgraded successfully.

**Comment by ffittschen** [comment]
Happened to me as well with `rancher/server:v1.6.7` and `rancher/scheduler:v0.7.5`

Updating network-services (`rancher/network-manager:v0.6.6` to `rancher/network-manager:v0.7.7` and `rancher/metadata:v0.9.1` to `rancher/metadata:v0.9.3`) got stuck in upgrading.

Disabling scheduler allowed the upgrade of network-services to succeed.
