### ISSUE TITLE
Services show error while upgrading if you use scheduler to change host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7380]
**Rancher Versions:** master 1/11

**Steps to Reproduce:**
1.  Create a two host environment (add label foo=bar to host1 and foo2=bar2 to host2)
2.  Create a service
3.  After service activates, upgrade service and add schedule rule for it to go to different host

**Results:** The service will error at first saying it failed to allocate instance.  If you wait, it will eventually resolve.
![image](https://cloud.githubusercontent.com/assets/11514927/21860302/4e123878-d7ed-11e6-921f-1b5c0fc0988d.png)

**Expected:**  We should not error out first.

**Comment by StrongMonkey** [comment]
related to https://github.com/rancher/rancher/issues/7878 and https://github.com/rancher/rancher/issues/7444. When upgrading service, the new container launched in the first time will always have the same deployment uuid as the stopped container. This will append a valid host constraint which only set the initial host as valid one. Thus when we try to move container to other hosts, it will always fail at valid host constraints. When the container errors out and new one get created, a new deployment UUID will be attached and then valid host constraint will disappear. That's why it succeed later on.

**Comment by StrongMonkey** [comment]
@cjellick Does it make sense to you?

**Comment by StrongMonkey** [comment]
Found an interesting issue when re-testing this issue. I am trying to reproduce this issue, and when I upgrade my service to change some of the instances to another host, the containers keeps growing at a significant rate. It continues to stop old container and start new container, and the total number of container keeps increasing. @tfiduccia Can you try to reproduce it with rancher master? If so, might be a bug introduced by the service refactoring pr.

**Comment by StrongMonkey** [comment]
@alena1108 Assigned this to you. Actually there are several scheduler bug related and I believe once this is fixed, other ones will also get resolved.

**Comment by alena1108** [comment]
The fix will be - ignore instances of the deployment unit when they are set with upgrade=true flag, by scheduler. That is to fix new instances to be scheduled to the host satisfying the affinity during the Upgrade process.

Regarding multiple containers seen in stopping state on master - requires a separate fix, unrelated to scheduler.

**Comment by sangeethah** [comment]
Tested with latest build from master (Apr 17). There is no intermittent errors seen when upgrading a service that results in containers to be placed in a different hosts.
