### ISSUE TITLE
Rancher v1.2.2: OpenLDAP with TLS issue

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#7423]
Rancher Versions: v1.2.2

Docker Version: 1.12.6

OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu16.04, cloud

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single node ranche

Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Any

Steps to Reproduce:
ca.crt was successfully loaded to container, if I manaully change ldap.conf as below in rancher container, I can successfully get expected output by running command "ldapsearch -x -ZZ"
#
BASE    dc=demo,dc=com,dc=cn
URI     ldap://ldap.demo.com.cn ldapi://ldap.demo.com.cn

TLS_CACERT	/etc/ssl/certs/ca-certificates.crt
#
But from rancher UI, if I check TLS, error pops up "Could not talk to ldap"

![ldaperror](https://cloud.githubusercontent.com/assets/15604715/21976099/2ad4b4cc-dc0b-11e6-8d29-ff6560500365.jpg)

my config:

![ldap1](https://cloud.githubusercontent.com/assets/15604715/21976151/6d3c9f0a-dc0b-11e6-8001-fefc9958241f.jpg)
![ldap2](https://cloud.githubusercontent.com/assets/15604715/21976152/6d47b796-dc0b-11e6-8144-2da26a2eb7b7.jpg)

Please help, thanks!

**Comment by toughIQ** [comment]
I have a similar issue with 1.2.2 and 1.3.0 with my ca.crt for ActiveDirectory. TLS gives me an error. Using same config without TLS works fine.

**Comment by tfiduccia** [comment]
@hiscal2015 - First verify that you can login without TSL enabled.  Then: in 1.2.2 we had an issue where the cert was not being added to to the keystore.  This was fixed in 1.3.0 but if you want to use 1.2.2 there are additional steps you have to take to make sure it works.  @toughIQ, since you upgraded the change was not automatic for you you can either readd the cert (and it will get the change, or you can do additional steps).  Here is the whole process but the additional steps start at step 10:

1.  Log into Server
2.  vim ca.crt & i
3.  copy & paste cert info
4.  esc :x
5.  cat ca.crt (verify info is correct)
6.  sudo -s & docker ps to get container id
7.  docker stop <container id>
8.  docker create --volumes-from=<containerid> --name=rancher-data rancher/server:<version>
docker run -d --volumes-from=rancher-data --restart=unless-stopped -p 8080:8080 -v /home/tani/ca.crt:/var/lib/rancher/etc/ssl/ca.crt rancher/server:<version>
9.  docker logs -f <new container id to see if cert is added>
10. docker exec -it <container id> bash
11. cd /usr/lib/jvm/zulu-8-amd64/jre/lib/security
12. keytool -import -trustcacerts -file /var/lib/rancher/etc/ssl/ca.crt -alias myca -keystore ./cacerts <password is changeit>
13. restart container 

If this does not fix your issue, please reopen bug and let me know.

**Comment by hiscal2015** [comment]
@tfiduccia I can't get it working also on v1.3.0, I can login without TLS enabled, but when to enable TLS, there's an error from browser:
![openldaptlsissue](https://cloud.githubusercontent.com/assets/15604715/22048524/947e64d2-dd68-11e6-86f7-bbe3c35fe7bb.jpg)

**Comment by toughIQ** [comment]
@tfiduccia is it possible, that we are placing our **ca.crt** in the wrong place?
In your example you mount the ca.crt to `/var/lib/rancher/etc/ssl/ca.crt`
The manual at http://docs.rancher.com/rancher/v1.3/en/installing-rancher/installing-server/#ldap
tells to mount it to `/ca.crt`
I took a quick look at the code and could only find certificate handling at `server/bin/update-rancher-ssl`
and there is nothing done with a **ca.crt** in **/** of the container.
Thanks

**Comment by tfiduccia** [comment]
@toughIQ - yes the cert needs to be placed in -  /var/lib/rancher/etc/ssl/ca.crt.  We are updating the documentation to reflect that.  Since you are in 1.3.0, follow steps 1 through 9 (of course in step 8 remove tani and put your home dir), in the logs you should see:

Adding ca.crt to Certs.
Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
keytool error: java.lang.Exception: Alias <rancher_ca> does not exist
Certificate was added to keystore

Then it should work

**Comment by toughIQ** [comment]
Thanks @tfiduccia. I followed the updated documentation and used the current v1.3.2 image. Now TLS is fine.

**Comment by tfiduccia** [comment]
@hiscal2015 - We updated the help documentation, so you might want to check and make sure you have done all steps.  Also did you check your logs?  Do you have:

Adding ca.crt to Certs.
Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
Certificate was added to keystore

Upgrading from 1.2 to 1.3, the cert will not automatically be added to the keystore, you will have to run through the process again and make sure you see the above in your logs.
