### ISSUE TITLE
Environment gets into a state where all containers fail with "Scheduling failed: No healthy hosts with sufficient resources available"

### ISSUE THREAD

**Issue by bifr** [rancher/rancher#7482]
**Rancher Versions:**
Server: v1.2.1
healthcheck: 0.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.3.0
kubernetes (if applicable): n/a

**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7, Xen VMs, hosted locally
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external RDS DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Unclear, though it seems to have something to do with [infrastructure?] stacks spinning up in a bad way
**Results:** 
I have Rancher set up with 3 environments, each with 3 hosts each: dev, prod A, prod B. At least once on each one I've gotten into a state where any new container, infrastructure or user, will fail with a message along the lines of (Failed to allocate instance [container:1i42971]: Bad instance [container:1i42971] in state [error]: Scheduling failed: No healthy hosts with sufficient resources available). This is on a very lightly loaded set of three hosts so it's not entirely clear what resources aren't available. 

I can mostly avoid it by forcing Rancher to be very deliberate in how and when stacks start up in an environment. This includes a specific startup order for the infrastructure stacks once I have hosts set up. But once it gets into the bad state, I have been unable to walk it back except for deleting the environment and starting again. That's not going to be a viable solution once we have more than one serious stack in an environment, so I'm eager to figure out how to fix this. 

I do see a lot of running processes in scheduled state with a start time of multiple hours ago, and I don't know how or why those haven't cleared either. If they're still scheduled they may also be holding on the same mysterious resources the containers are though

**Comment by vincent99** [comment]
"No healthy hosts with sufficient resources available" just means that there is no host which is active and satisfies all the scheduling constraints.  Usually this means you're trying to use a port which is already used on all the hosts and/or or have affinity/anti-affinity labels that cannot be satisfied.

You can look at the `rancher/server` container log to see more detail leading up to that, it logs every constraint being tested and the results for each host (https://github.com/rancher/cattle/blob/master/code/iaas/allocator/src/main/java/io/cattle/platform/allocator/service/AbstractAllocator.java#L287-L312)

**Comment by bifr** [comment]
If I run ```docker logs``` on the container, when I try to start a new container all I see written is:

```
2017-01-19 22:58:23,672 ERROR [f54c7358-294a-4b1f-99ad-9171c43ea4ef:1127210] [instance:42972] [instance.start->(InstanceStart)]
[] [ecutorService-3] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [42972]
```

However, I see a bunch of messages similar to this regularly getting listed

`2017-01-19 23:02:30,075 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [storage.volume.remove.reply;agent=1]: Error response from daemon: Unable to remove filesystem for af2adac380887d5f1688102815dd9f0dc7b2c75dee8c5440ffe7a62aa563180e: remove /var/lib/docker/containers/af2adac380887d5f1688102815dd9f0dc7b2c75dee8c5440ffe7a62aa563180e/shm: device or resource busy`

Are there other logs I should be looking at?

**Comment by bifr** [comment]
For reference, I get this error without specifying any ports to expose, or host affinities or any other restrictions on where the image should run

**Comment by bifr** [comment]
It seems that I can no longer destroy and recreate an environment as likely whatever's causing the processes to queue up as scheduled seems to be preventing important parts of the environment creation (such as being able to get a url for adding hosts) from working too. Is there anything I could do with the database that would effectively reset that stuff even if old handles clutter up elsewhere?

**Comment by pythianarceri** [comment]
We have exactly the same issue, we see the load average on the rancher host climb steadily up to 300 due to "docker-runc init" processes queuing up, on this host the scheduler service has failed and when it tries to start it prints the following error:
`"scheduler (Failed to allocate instance [container:1i98090]: Bad instance [container:1i98090] in state [stopping]: Scheduling failed: No healthy hosts with sufficient resources available)"
`Trying to execute any docker commands or viewing logs hangs the terminal.
We also noticed that the memory on the server gets slowly consumed, which i assume is the result of the locked spawned processes. 
This is the 3rd time we experience this error and it always require a hard reboot of the host to recover. 
The docker-runc processes Parent PID is 891 which matches the following process
  891 root     {ros} docker-runc exec -- e4c23f2e1446f663d1fa8ff797f4a5431df546425dc56c24a572d0e6056625d6 env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=ip-10-30-0-193.ec2.internal HOME=/ docker-init daemon --log-opt max-size=25m --log-opt max-file=2 -s overlay -G docker -H unix:///var/run/docker.sock
Which is the PID of the scheduler container process

Rancher version
1.2.2
Scheduler Version:
0.5.1

#docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Comment by pythianarceri** [comment]
Found this error on rancher/server logs, the timestamp more or less matches the time the issue started.
Don't know if it's relevant but i've seen references to websocket on https://github.com/rancher/rancher/issues/6964
```
time="2017-01-22T22:15:04Z" level=info msg="Shutting down backend 5a57487f-f448-4208-b965-b0ac8af9d755. **Connection closed because: websocket: close 1006 unexpected EOF.**" 
time="2017-01-22T22:15:04Z" level=info msg="Removed backend. Key: 5a57487f-f448-4208-b965-b0ac8af9d755. Session ID 26a8dd9d-3b69-489f-8766-ecc076442557 ." 
time="2017-01-22T22:15:10Z" level=info msg="Handling backend connection request." 
time="2017-01-22T22:15:10Z" level=info msg="Registering backend for host 5a57487f-f448-4208-b965-b0ac8af9d755 with session ID 7fecbde2-d49a-4ab8-b2ab-d8c96b1164f7." 

```

**Comment by bifr** [comment]
We ended up reinstalling after scrubbing any trace of the old install from the rancher server and hosts. Which isn't a viable solution in the long term and only really works while we're running one serious stack. 

As the pile of long running processes did not come back after the reinstall, I suspect involvement. Whether they were another symptom or the cause is unclear.

**Comment by pythianarceri** [comment]
Our rancher-host crashed again today (less than 24hrs after the last crash), scheduler stack had to be deleted and re-created manually from the catalog.

**Comment by maksaimer** [comment]
Everything ok with rancher before this day. In production we have "No healthy hosts with sufficient resources available" and entire our system freezed. This problem a bolt from the blue :(

**Comment by pythianarceri** [comment]
Can you login over ssh to your rancher-host(s) and try executing any docker commands and see if docker is hanging (docker ps should be OK)

**Comment by superseb** [comment]
Thanks for reporting, sorry for the slow response. There have been several releases since v1.2, can you try if it is fixed using a newer release?
