### ISSUE TITLE
Pods that use kubernetes service accounts hold onto old service account token and fail to function when k8s stack gets recreated using backed up etcd

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#7501]
Whenever kubernetes is torn down and started again, all the pods that use service accounts don't get their service account tokens updated, and they cannot communicate with the new apiserver anymore. 

This needs to be fixed by deleting the pods when kubernetes is torn down, and then recreating it when kubernetes is brought back up

**Comment by alena1108** [comment]
Happens in the use case when k8s cluster gets recreated, and new cluster uses the etcd volumes of the old cluster. Pods/Services are being preserved, but k8s recreates tokens for existing service accounts - because k8s api service pulls a new cert from Rancher. So all pods using old service accounts' token, can no longer connect to the API server.

**Comment by deniseschannon** [comment]
This is fixed as of v1.5.7. 

Note: If your hosts were not cleaned up properly in prior Rancher setups before upgrading, it will not fix those environments.
