### ISSUE TITLE
rancher compose does open ports on Mac

### ISSUE THREAD

**Issue by ebreton** [rancher/rancher#7505]
**Rancher Versions:**
Rancher:v1.3.2
User Interface: v1.3.6
Rancher Compose:v0.12.1
healthcheck:healthcheck:v0.2.0
ipsec: net:v0.8.1
network-services: metadata:v0.7.0 & network-manager:v0.4.0
scheduler: v0.5.1

**Docker Version:**
Docker version 1.13.0, build 49bf474

**OS and where are the hosts located? (cloud, bare metal, etc):**
Mac Os X 10.12.2 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher sandbox
one host (Mac) behind firewall (UDP 500 and 4500 opened)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle: v0.175.8

**Steps to Reproduce:**

1. Start up rancher
<img width="670" alt="capture d ecran 2017-01-21 a 19 17 16" src="https://cloud.githubusercontent.com/assets/490665/22176590/54f92da8-e00e-11e6-8388-03e51b526c1c.png">

2.  write docker-compose.yml
```
version: '2'

services:
  web:
    image: nginx
    ports: 
      - 80:80
Start up rancher
```

3. rancher compose
```
$ rancher-compose up
INFO[0001] Creating stack test                          
INFO[0002] [0/1] [web]: Creating                        
INFO[0002] Creating service web                         
INFO[0003] [0/1] [web]: Created                         
INFO[0003] [0/1] [web]: Starting                        
INFO[0010] [1/1] [web]: Started   
```
<img width="884" alt="capture d ecran 2017-01-21 a 19 20 08" src="https://cloud.githubusercontent.com/assets/490665/22176605/a751f2ec-e00e-11e6-8966-a118d01ede1a.png">

**Results:** 

service not available:
```
curl -v my.domain.com
* Rebuilt URL to: my.domain.com/
*   Trying x.x.x.x ...
* TCP_NODELAY set
* Connection failed
* connect to x.x.x.x  port 80 failed: Connection refused
* Failed to connect to my.domain.com port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to my.domain.com port 80: Connection refused
```

**Expected Results:** 

by running docker-compose instead of rancher-compose
```
$ docker-compose up
Starting test_web_1
Attaching to test_web_1
```

```
$ curl -v my.domain.com
* Rebuilt URL to: my.domain.com/
*   Trying x.x.x.x ...
* TCP_NODELAY set
* Connected to my.domain.com (x.x.x.x ) port 80 (#0)
> GET / HTTP/1.1
> Host: my.domain.com
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.11.8
< Date: Sat, 21 Jan 2017 18:23:14 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 27 Dec 2016 14:23:08 GMT
< Connection: keep-alive
< ETag: "5862794c-264"
< Accept-Ranges: bytes
< 
<!DOCTYPE html>
<html>
...
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host my.domain.com left intact
```

**Comment by vincent99** [comment]
Docker for Mac is not supported by Rancher.  They employ a variety of tricks to pretend that you're actually running Docker on your Mac instead of in a Linux VM in the background, and  makes assumptions about what containers will do and how ports are published which do not hold true for more involved use cases.

Rancher uses CNI networking, which maps ports on the host using iptables rules on the host and then does not tell the Docker daemon about them (`--net=none`).  This results in ports that are open on the _actual_ host (the VM), but does not trigger the Docker for Mac logic which also opens the port on your Mac and forwards it to there.

There are also other problems, like 4500/udp is often used by the Wi-Fi calling feature of macOS.

**Comment by ebreton** [comment]
ok, thanks for the explanation
