### ISSUE TITLE
"Error looking up volume plugin rancher-nfs: legacy plugin: plugin not found"

### ISSUE THREAD

**Issue by jtcressy** [rancher/rancher#7522]
**Rancher Versions:**
Server: 
v1.3.3 (tested on 1.2.0, 1.3.1, 1.3.2)
healthcheck: 
v0.2.0
ipsec:
v0.0.2
network-services:
v0.0.8
scheduler:
v0.3.0
kubernetes (if applicable):

**Docker Version:**
1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
boot2docker 1.13.0 coreOS, vsphere VM's, private cloud.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy new rancher/server with one or more hosts deployed via vmwarevsphere machine driver.

**Results:** 
rancher-nfs never works properly. Volumes show up in "Infrastructure > storage" but every container that attempts to use that storage errors out claiming that the rancher-nfs plugin is not found.

**Previously working workarounds to this:**
I was forcibly running convoy-nfs in order to connect to my nfs server atall, and made my own custom template to override the rancher host version limit. It worked great for a while, but now the convoy-nfs driver does not register in rancher anymore. I keep trying rancher-nfs, but NOT ONCE in any of my attempts has it EVER worked 100%.

**Comment by m-svoboda** [comment]
Hi,
you must use RancherOS because rancher-nfs driver si not supported in boot2docker. I had the same issue but now I have other:
Error response from daemon: create bar: VolumeDriver.Create: Failed mount -o nolock,nfsvers=4 192.168.4.109:/nfs /tmp/wekhs: mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd. mount.nfs: mounting 192.168.4.109:/nfs failed, reason given by server: No such file or directory

**Comment by jtcressy** [comment]
I tried deploying an environment manually on two photonOS hosts, and rancher NFS works great, surprisingly. It doesn't have to be rancher OS, but you're right that it doesn't work with boot2docker. I just need a way to auto-deploy hosts to vSphere using something other than boot2docker. And nothing exists to do this. It's boot2docker or nothing using docker-machine's vsphere driver.

**Comment by m-svoboda** [comment]
Can you tell me what is your nfs server? I have it on windows server 2016 (services for nfs). I do not know if it works with rancher nfs.

**Comment by m-svoboda** [comment]
I think, you can use docker-machine look at this: https://docs.docker.com/machine/drivers/vsphere/
Use this as parameter when you are creating docker-machine:
--vmwarevsphere-boot2docker-url: URL for boot2docker image.
But use URL for photonOS image.

**Comment by jtcressy** [comment]
I'm running NFS on Freenas 9.10.
NFS works on other OS's such as centOS or ubuntu. I have to provision these hosts manually outside of rancher, so it looses the appeal of fully automated deployment.
Docker-machine will **NOT** work with photon OS or anything other than a boot2docker image. It wont even work with rancherOS. At this moment there is no way to deploy hosts on vsphere from rancher and maintain NFS functionality.

**Comment by jaredallard** [comment]
Is there a reason `rancher-nfs` doesn't work on boot2docker? Is there any plans to fix this? I don't want to switch *everything* over to RancherOS on docker-machine without actual cause to do so.

**Comment by fatalsaint** [comment]
I am seeing a similar error on Cloudformation provisioned Amazon Linux AMI's version 2016.09.  The nfs-driver container successfully starts, and new requested storage entries are created in Infrastructure->Storage, but they stay Inactive and the client containers error with: "Error looking up volume plugin rancher-nfs: plugin not found"

**Comment by superseb** [comment]
So I think this is because most OS-es these days symlink `/var/run` to `/run`.

In this line (https://github.com/rancher/storage/blob/master/docker/volumeplugin/socket.go#L9) we say we have to bind mount both path into the container, but the image we use (`ubuntu:16.04`) symlinks `/var/run` to `/run` and this works if the underlying OS does so too. (Still confusing in the code)

In boot2docker, the two are separate, which is different than the image used. So it can't find the socket and responds with `"Error looking up volume plugin rancher-nfs: legacy plugin: plugin not found"`

@StrongMonkey @LLParse @yasker Can you take a look?

**Comment by mvlintho** [comment]
I'm encountering the same issue on the latest version of rancher (1.6.7) in combination with the latest stable version of boot2docker (17.06.0-ce). All my cattle hosts are being provisioned by the vsphere driver via rancher.

**Comment by alex-mohemian** [comment]
@mvlintho This is also the solution for Amazon Linux AMIs! Fixed my issue with the `rancher-ebs` plugin! ❤️

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
