### ISSUE TITLE
 Failed to get ping from agent

### ISSUE THREAD

**Issue by gsideri** [rancher/rancher#7565]
**Rancher Versions:**
Server: v.1.2.3
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable):

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 in OpenStack
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm & Cattle

**Steps to Reproduce:**
1) Install Rancher in one node
2) Install Rancher Agent

**Results:**
The host appears as "Reconnecting" every 5 minutes. Rancher Server Containers shows:

`[i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [6] count [3]`

Could you please tell me what port is looking for the agent? How can I check it? 

Thanks

**Comment by aemneina** [comment]
is this reproducible on a newer version of rancher? Closing this out due to inactivity.

**Comment by McPringle** [comment]
Why was this issue closed? It still happened with Rancher v1.6.2 and Agent v1.2.2! No way to get Rancher up and running while "pure" Docker Swarm with Portainer works…

**Comment by vincent99** [comment]
Because a specific person had a specific problem and first we and then they did not follow up on it, and now it's ancient and irrelevant.

There are tens of thousands of installs working fine, the agent hasn't been broken with "no way" to use it for 6 months.  If you have a specific reproducible problem create your own an issue and post as much useful information as you can.
