### ISSUE TITLE
OpenStack machine driver - host add removes public key on a failed provisioning

### ISSUE THREAD

**Issue by grimmtheory** [rancher/rancher#7570]
**Rancher Versions:**
Server: latest
healthcheck: v.0.2.0
ipsec: v.0.4.0
network-services: v.0.8.1
scheduler: v.0.5.1
kubernetes (if applicable): n/a

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud - OpenStack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add a host using the OpenStack machine driver, create a failed event after the 'provisioning process begins', I think it was a bad path to the private key, or just a bad private key in this case

**Results:** 
In a roll back scenario it deleted the public key that was pre-created in OpenStack

**Comment by vincent99** [comment]
This is a bug in docker-machine: https://github.com/docker/machine/issues/3261

**Comment by grimmtheory** [comment]
Didn't realize that, thanks Vincent.  It looks like a fix was posted a couple of days ago and is waiting to be committed https://github.com/docker/machine/pull/3969

**Comment by vincent99** [comment]
Huh, that's surprising since it's nearly a year old issue.  I would be surprised if that PR actually get accepted though. It's a band-aid that passes the problem down to the user to decide if it should be deleted instead of actually correctly deleting only keys which machine created in the first place.

**Comment by grimmtheory** [comment]
Yeah, weird, it'd be better than nothing I guess at least in the short term, surprising they haven't fixed it permanently yet.  I know you guys are focused on Rancher, but how much code do you all commit upstream for underlying components, e.g. docker/machine, that negatively (perceived or real) effect Rancher user experience?  Just curious because I run into this a lot w/ trying to enterprise / production productize OpenStack.  This particular issue is an annoyance, but for major stuff do you guys carry "tech debt" in your local dev to fix a significant bug until it's fixed upstream?

**Comment by vincent99** [comment]
We generally work around issues when we can and/or blamefest upstream since for a lot of things we can't directly control (e.g. the version of the kernel and docker on your host are already there when you register it to Rancher unless you're using RancherOS too).  For things we can control we sometimes fork & maintain/try to upstream.

For docker-machine specifically, we often ship builds from a random master commit because they contain an important fix we need but no release is coming containing it anytime soon.

**Comment by grimmtheory** [comment]
This is great stuff Vincent, thank you for the detailed response.

**Comment by davidarcher** [comment]
It's finally fixed 🙌
https://github.com/docker/machine/pull/4358

and a few other random docker-machine openstack driver annoyances:
https://github.com/docker/machine/pull/4361
https://github.com/docker/machine/pull/4364
