### ISSUE TITLE
API v1: how to get all environments?

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#7574]
When using an Environment keypair, `https://rancher.url/v1/projects` returns a collection where the `data` array contains all the environments.

When using an Account keypair (hoping to list all environments), the `data` array is empty.

This happens when issuing cURL calls to the API (or via `superagent`). In the browser, the `data` array is populated as expected.

Is this a bug, or am I doing something wrong?

**Comment by vincent99** [comment]
With an API key belonging to an environment (project), the only project it is authorized to is itself so `/v1/projects` is always a collection of 1 project.

With a user/account key, the response is the 0 or more projects which the user is a member of.  This is shown in the UI as the Environment dropdown choices.

If the account is an `admin`, you can additionally add `?all=true` to get back _all_ (unremoved) projects instead of just the ones you're a member of.  This is shown in the UI as the manage environments screen.

**Comment by ebr** [comment]
@vincent99 Thank you, `?all=true` was the trick.
My account is an `admin`, but project membership is not explicit - we use GitHub teams for access control. This probably why I wasn't getting any environments back.

**Comment by vincent99** [comment]
Github teams membership should work, with the caveat that the account has to have logged in through the UI once to get it's github auth token put into place.  If the account has never logged in then we won't be able to get info about the user's teams/orgs.
