### ISSUE TITLE
503 Service Unavailable (UI RANCHER LOAD BALANCER NOT WORKING ON CATTLE)

### ISSUE THREAD

**Issue by sciensa-treinamentos** [rancher/rancher#7579]
**Rancher Versions:**
Server:v.1.3.3

**Comment by stingerpk** [comment]
Can you log into the server? Are there any system logs? Check if your instance has enough RAM available.

**Comment by ebreton** [comment]
I also have (random) 503 errors with the load balancers. A bit like in https://github.com/rancher/rancher/issues/7024, except restarting the containers does not solve the issue

**Rancher Versions:**

I am using the rancher sandbox:
Rancher	v1.3.3
Cattle	v0.175.9
User Interface	v1.3.5
Rancher Compose	v0.12.1

healthcheck: v0.2.0
ipsec:net:v0.8.1
network-manager:v0.4.0
scheduler:v0.5.1

**Docker Version:**
1.12.3, build 34a2ead

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal, coreOs stable (1235.6.0)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher sandbox, single host

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Context**
I am using the following haconfig, which redirects from old subdomains to new one, and from http to https. The overall configuration works fine since I get the expected behavior on the majority of the calls

```
frontend http-frontend
  bind *:80
  mode http
  acl hook_OLD hdr_dom(host) -i example.com
  acl hook_OLD hdr_dom(host) -i www.example.com
  http-request redirect location https://next.example.com code 302 drop-query if hook_OLD
  acl hook_LE path_beg /.well-known
  http-request redirect scheme https code 302 if !{ ssl_fc } !hook_LE
```

**Comment by aemneina** [comment]
See referenced issue for troubleshooting help.
