### ISSUE TITLE
ipsec router and cni-driver containers stuck in "post-network" error state , when host is powered down and back on.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7587]
Rancher Versions: v1.4.0-rc3

Steps to reproduce the problem:
Have few stacks with few services that are not health check enabled.
Power down the host some of the service instances (that are not health check enabled) is running.
Instances in host continues to be in "running" state as expected.
Power on the host.
When host gets to "active" state , instance state gets marked as "stopped" and get restarted.
Ipsec container on this host get to "running" state successfully but  "router" and "cni-driver" instances get to "running" state but with ```"transitioning": "error",
"transitioningMessage": "Post-network”,```  resulting in being shown as being in "error" state in UI

<img width="974" alt="screen shot 2017-01-27 at 10 52 40 pm" src="https://cloud.githubusercontent.com/assets/4266958/22394939/5626aca8-e4e3-11e6-91f0-a72ee616c787.png">

Containers that get restarted on this host are in the same state - "running" state but with ```"transitioning": "error",
"transitioningMessage": "Post-network”,```

**Comment by ibuildthecloud** [comment]
The issue was that a regression was introduced such that we weren't clearing the error state on container start.  To reproduce you need to create a container, then stop it.  Then do something will fail container start so it goes to stopped and error (red in the UI).  The next start should clear error state and then go to running.  The bug was that the error state wasn't cleared so it was Running but marked as error.

**Comment by sangeethah** [comment]
Rancher Versions: v1.4.0-rc5

This issue is not seen anymore.

**Comment by tuwid** [comment]
@sangeethah I'm seeing this issue in 1.6.24

**Comment by tuwid** [comment]
@sangeethah I'm seeing this issue in 1.6.28
