### ISSUE TITLE
Possibility to disable IPv6 in container

### ISSUE THREAD

**Issue by cabrinoob** [rancher/rancher#7592]
**Rancher Versions:**
Server: 1.1.4
**Docker Version:**
v 1.12.5

Regarding this post https://forums.rancher.com/t/dns-round-robin-doesnt-work/5330, it would be very interesting to add the possibility to disable the IPV6 inside the container.

This could be done allowing to set the value of the --sysctl docker flag through rancher : 
`sysctl net.ipv6.conf.all.disable_ipv6=1 `

**Comment by eesprit** [comment]
+1 for this

**Comment by pschrammel** [comment]
couldn't this be done in the docker-compose file:
http://stackoverflow.com/questions/39329732/specify-sysctl-values-using-docker-compose

**Comment by eesprit** [comment]
Last time I checked, version 2.1 was not supported by rancher-compose.

**Comment by aemneina** [comment]
should be possible now. closing issue.

**Comment by zbialik** [comment]
@aemneina I am having an issue creating a rancher cluster backed by flannel with ipv6 disabled.

I am using `Rancher: v2.1.7` and Kubernetes `v1.11.8-rancher1-1`

I saw that this is related to a fix with regarding containernetworking/plugins: [the fix](https://github.com/containernetworking/plugins/pull/62)

The fix was released in v0.7.0. Is this version of the cni available in any of the rancher releases at the moment? Is there some way around this besides enabling ipv6 or not using flannel? 

Thanks

**Comment by aemneina** [comment]
Hi @zbialik the original ticket is talking about rancher 1.1 and pretty old. I dont think there's an issue with ipv6 and the latest versions of docker. Can you try with the latest versions of rancher/docker and see if that works for you? If not please file a new ticket and provide as many details of the issue as possible.
