### ISSUE TITLE
Add support for other Docker Compose formats and add in relevant new fields

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#7602]
Add support for Docker Compose v3 format: https://docs.docker.com/compose/compose-file/#/versioning

**Comment by borntorock** [comment]
+1

**Comment by borntorock** [comment]
+1

**Comment by rsynnest** [comment]
I'm hoping this will be part of the rancher 1.5 release since docker compose v3 corresponds with Docker engine 1.13.0+ , which should be [supported in rancher 1.5](http://docs.rancher.com/rancher/v1.3/en/hosts/#supported-docker-versions). Rancher 1.5 is slated for release at the [end of February](https://github.com/rancher/rancher/milestones).

**Comment by rsynnest** [comment]
According to some rancher folks 1.5 will not be supporting v3. They mentioned how docker-compose is being geared more and more towards docker-swarm, and Rancher isn't sure when v3 will be supported. That said, I've found most v3 features I needed are supported in v2.1. The v3 changes are pretty minimal and easy to back-port (besides deploy) and are listed [here](https://docs.docker.com/compose/compose-file/compose-versioning/#/version-3).

**Comment by chicco785** [comment]
+1 rancher 1.5 is not supporting v3, which is really a pity given that "deploy" provides lot of interesting functionality to configure ha services

**Comment by rsynnest** [comment]
Rancher-compose uses [libcompose](https://github.com/docker/libcompose) which already has some discussion on [v2.1 support](https://github.com/docker/libcompose/issues/441) and [v3 support](https://github.com/docker/libcompose/issues/421). As mentioned there, I don't think `deploy` will be implemented for rancher-compose. Rancher uses its own orchestration framework (Cattle), so I don't think they will be integrating any Swarm commands into Cattle. That just sounds really messy, though I could be wrong. They will likely just add those new features like deploy into the Standalone Docker-Swarm Environment (you can run rancher in this way as an alternative to Cattle). I may be misunderstanding things, the waters are getting pretty muddy since docker integrated swarm into docker-engine. If all else fails we can always just keep abstracting until we reach enlightenment.

**Comment by vincent99** [comment]
Correct; cattle supports docker-compose *syntax* but not necessarily any particular *capability* of it.  Even if we add support for parsing v3 it is unlikely we would support most of `deploy`, since cattle already has similar capabilities for much of them.

**Comment by chicco785** [comment]
i understand the point of not having support for v3 docker compose in cattle. still, currently if you have a docker warm environment you cannot load a v3 compose file in the gui and (haven't tried but i suppose it's the same case) you cannot register in the swarm-templates a docker compose v3 and launch it from the catalogue. ultimately, the support need is for the parsing and launching them using docker swarm deploy. would that be possible?

**Comment by deniseschannon** [comment]
We should allow support for other compose versions and ignore the fields that are not relevant to Rancher (i.e. healthcheck, swarm fields). In analysis and design, we should investigate the list of fields that are missing and need to be added in.

**Comment by mautz-et-tong** [comment]
A little bit more precision in error messages would be great. "Error (yaml: unmarshal errors: line 1: cannot unmarshal !!str `3` into config.RawService)" is a really appalling error message for "Rancher __VERSION__ doesn not support docker-composer version 3"

**Comment by carolynhu** [comment]
For docker container fields, currently missing:
--cpuset-cpus=“”    CPUs in which to allow execution (0-3, 0,1)
--cpu-rt-period=0    Limit the CPU real-time period. In microseconds. Requires parent cgroups be set and cannot be higher than parent. Also check rtprio ulimits.
--cpu-rt-runtime=0    Limit the CPU real-time runtime. In microseconds. Requires parent cgroups be set and cannot be higher than parent. Also check rtprio ulimits.
--health-start-period   Start period for the container to initialize before starting health-retries countdown

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
