### ISSUE TITLE
Exposed ports don't get programmed on the hosts sometimes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7625]
Rancher Versions: v1.4.0-rc5

Steps to Reproduce:
Create a new environment (In my case k8s) with 3 hosts.
Once Infra stack is up and running , create a container with exposed port.

Container starts successfully , but is not reachable using this exposed ports.

Iptables in the host where the container is running , does not have the exposed ports programmed.

This issue is not reproducible always. But I saw it happen few times by following the same steps.

Note - When i start another container (even in other hosts) , I see that this exposed port gets programmed for this container.

**Comment by sangeethah** [comment]
@leodotcloud I see this issue happen again pretty consistently,  when I try to start a standalone container on a K8s setup. Can this be anything specific to starting a container on a K8s setup ?
I have not encountered this issue in a cattle setup. For k8s automation , we start a standalone container with exposed ports to act as a remote kubectl client for executing kubectl commands.

**Comment by alena1108** [comment]
@sangeethah @leodotcloud happens when metadata for container with ports gets programmed when container is still in Starting state, and thats the last metadata update for the host. Looks like iptables programming includes only instances in Running state, as when I've triggered the metadata update on Sangeetha's host, the problematic container was updated to Running state in metadata, and the ports were programmed correctly for it after that.

**Comment by leodotcloud** [comment]
Fixed in network-services(v0.1.1) with image: `rancher/network-manager:v0.5.2`

**Comment by sangeethah** [comment]
Tested with rancher/network-manager:v0.5.2 and rancher/network-manager:v0.5.3 . Have not seen this issue happen anymore.
