### ISSUE TITLE
Passing a secret to k8s ingress which uses a private registry fails

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7655]
**Rancher Versions:**
Server: 1.3.3

Rancher has a security mechanism where it wont share secrets with an ingress image it doesnt recognize. We're going to change the behavior here, to allow for this.

**Comment by alena1108** [comment]
@sangeethah @soumyalj to test this fix, we'd have to:

1) Deploy rancher, create a simple nginx server. For simplicity, have just 1 host.
2) Stop rancher server.
3) Configure default registry to some custom value in rancher via```registry.default``` setting. Say you set it to ```my.custom.registry```.
4) Tag haproxy image on your host so it looks like this:

```
docker:my.custom.registry/rancher/lb-service-haproxy:v0.5.9
``` 
5) Start rancher and create an LB service WITH certificates. 

Validate that lb instance starts fine, and certs are configured in haproxy config.

The bug was in haproxy instance rancher credentials validation when the private registry is present. Everything was working besides the haproxy not being able to fetch the certs.

**Comment by sangeethah** [comment]
Tested with rancher-server - v1.4.0-rc7:

When lb service is started with image in private registry and certificates , LB is stuck in "Initializing" state and following errors are seen in the lb logs:

```
2/3/2017 1:32:56 PMtime="2017-02-03T21:32:56Z" level=error msg="Failed to get lb config: Coudln't get certificate by name [test-922897]. Error: Unknown schema type [certificate]"
2/3/2017 1:35:19 PMtime="2017-02-03T21:35:19Z" level=error msg="Failed to get lb config: Coudln't get certificate by name [test-922897]. Error: Unknown schema type [certificate]"
```

Tested with rancher-server - v1.4.0-rc8:

When lb service is started with image in private registry (quay.io) and certificates , LB starts successfully and is functional.
