### ISSUE TITLE
Do not allow for the same scheduler ips to be set in 2 different hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7674]
Rancher Versions: v1.4.0-rc8

We are allowed to add same shceduler ip to be set in 2 different hosts.
Ideally this  should be prevented.

**Comment by StrongMonkey** [comment]
@cjellick need to discuss with @cjellick. Not sure what to do with two same private ip.

**Comment by StrongMonkey** [comment]
if it is doable, the fix should not be in the scheduler. Is it possible to prevent it in UI? I think UI knows all the scheduler ips for all the hosts and can prevent user putting the same IP? @vincent99 any idea about this?

**Comment by vincent99** [comment]
While not common, there are cases where the same IP is actually available on multiple hosts (anycast, vrrp).  So it's not clear that we should really enforce anything here.

Anyway if you want validation, that goes in the API; the UI is only one possible client.  (And this is where I again argue that this, like most things, should have been a real API field instead of a label).
