### ISSUE TITLE
scheduler not fully backwards compatible

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#7681]
The port allocations changes were not backwards compatible if you upgrade cattle to 1.4.0 but _did not_ upgrade the scheduler service.

You should be able to run 1.4 cattle with 1.3 services.

**Comment by sangeethah** [comment]
Fresh install of rancher-server version - v1.3.3

Created few services with exposed ports ,health check enabled services, lbs and global services.

Upgrade rancher-server  to v1.4.0-rc9.
Do not upgrade any of the infrastructure stacks including scheduler which is rancher/scheduler:v0.5.1.

Allocation relating to exposed ports works fine. 
Following are  few of the scenarios tested:
 Scale up existing instance with exposed ports .
 Create new instances with exposed ports. 
 service reconciles relating to stop/start/delete of instances of instance with exposed ports.
 Stopping/Starting of services for release port checks.
Metadata checks for exposed ports.
Endpoint checks for exposed ports.

Following use case fails which is an existing  issue in v1.3.3  with rancher/scheduler:v0.5.1:
1. Create service - s1 with scale 3  exposed port say 7777 (edited)
2. Create another service - s2 with scale 3  exposed port say 7777 ..fails allocation as expected
3. Stop service - s1
4.  service - s2  starts now as expected
5. Try to start S1. 

Service S1 starts successfully with exposed ports pointing to instances of service S2. 
Expected behavior is for S1 to not able start successfully because of ports not being made available.

This issue works as expected in rancher-sercer version - v1.4.0-rc9 with rancher/scheduler:v0.6.3
