### ISSUE TITLE
Can't specify host for load balancer after upgrade to 1.3.3

### ISSUE THREAD

**Issue by twoeo** [rancher/rancher#7697]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2.0
ipsec: holder
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Aliyun

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
add a load balancer
click scheduling (Wanna specify a host for it)

**Results:** 
1. No host selector
1. Use scheduling rules (host label), but not works.(can not find host)

![](http://i1.piimg.com/567571/9ceb0f322dcf9b31.png)
![](http://i1.piimg.com/567571/75e77f7120fb7421.png)

**Comment by tfiduccia** [comment]
@twoeo - The second issue you have here was fixed in 1.4.  The labels show up in the drop-down.  

The first point (about being able to select a single host), I was pretty sure that was never available. I went back and checked 1.1.  I  Here is picture:
![image](https://cloud.githubusercontent.com/assets/11514927/22658312/e8f942e6-ec56-11e6-9a39-bff5eaca16a4.png)

I think the point being you would probably never want all your load balancers on a single host anyway.  No single point of failure is suggested.  If you really wish to specify a single host, either manually type in the labels for 1.3.3 or please upgrade to 1.4.
