### ISSUE TITLE
Can I start rancher server as a service?

### ISSUE THREAD

**Issue by KaimingWan** [rancher/rancher#7825]
Can we start rancher server and agent as a service using "docker service create" command?

**Comment by toughIQ** [comment]
In theory this should be possible, since `docker service` does the same as `docker run`, but with the additional orchestration mindset.

My question is: why do you want to do it? What would you like to solve of achieve?

**Comment by KaimingWan** [comment]
@toughIQ If i start rancher as a service. Can  I manage it in rancher web UI itself. If so, I can manage all containers including rancher itself as services in rancher web UI which will offer a uniform view to manage services.

**Comment by vincent99** [comment]
Short answer, no.  You can make it almost work but if the whole cluster goes down you will end up in a circular dependent situation where you can't start the containers because there's no hosts and can't add hosts because there's no running API because there's no hosts.

What you can easily do is run a simple rancher installation which then manages the containers of a separate, possibly HA installation.

**Comment by KaimingWan** [comment]
@vincent99 Thanks. Deploy rancher in HA mode with 'docker run' command should be a good choice.
