### ISSUE TITLE
API Interceptor: Session is ended when interceptor returns an error with authentication enabled

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7840]
**Rancher Versions:**
Server: master build

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
- Make sure to have interceptor to return an error (5xx, or 4xx)
- Add interceptor configuration that returns that send requests to this interceptor
- Enable authentication in Rancher
- Navigate to the specified path

**Results:** 

The session ends and i got the login form without displaying any errors, the response headers aren't received in case of failure:

```
Request URL:http://x.x.x.x:8080/v2-beta/projects/1a63/stacks?limit=-1&sort=name
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:x.x.x.x:8080

Response Headers
Content-Length:108
Content-Type:application/json
Date:Thu, 16 Feb 2017 00:26:30 GMT

Request Headers
accept:application/json
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
content-type:application/json
Cookie:PL=rancher; token=jY97UsF6GNVnh9v8ZKy9bbywJDz3Weui5Qza7kqg; CSRF=300AEF92FA
DNT:1
Host:x.x.x.x:8080
Referer:http://x.x.x.x:8080/settings/env
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
x-api-action-links:actionLinks
x-api-csrf:300AEF92FA
x-api-no-challenge:true

Query String Parameters
limit:-1
sort:name
```

**Comment by prachidamle** [comment]
@galal-hussein @sangeethah 
Following is our current UI behavior:
1. If a user is attempting to login, and some API in the initial UI load errors out, then the UI load fails and user sees the login form back.
2. If a user had already logged in and he/she reloads the UI, and some API in the reload process errors out, UI will logout the user and show the login form
3. If a user has already logged in and some single API call fails with a 401/403, user is logged out and shown the login form
4. If a user has already logged in and some single API call fails with an error that is NOT a 401/403, then the error is shown on UI in red. No logout happens in this case.

So the cases where the API happens to be part of UI initial login/reload process and and interceptor errors out on that API, user's session will end.
This is expected behavior. 
Only fix we can probably do here is UI showing the error returned, on the login page.

@vincent99 please comment if my understanding above is not right.

**Comment by sangeethah** [comment]
Closing this issue.
per @vincent99 , we are not changing anything in UI to be showing error message in login page.
