### ISSUE TITLE
[webhooks: service-upgrade] Intermediate error in upgrade of a service with exposed ports results in finish upgrade not completing

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7879]
**Rancher Versions:**
Server: Master

**Docker Version:**v1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create 2 services test1, test2 with ubuntu image and label "test=value".  Create another service test3 with exposed port also with ubuntu image and label "test=value"
2. Create a webhook for service upgrade with label "test=value" and startFirst=True
3. Push an nginx image

**Results:** 
Services test1 and test2 get upgraded successfully.
Service test3 has an intermediate error ```Failed to allocate instance [container:1i80]: Bad instance [container:1i80] in state [error]: Allocation failed: No healthy hosts with sufficient resources available``` because of which the upgrade is delayed. After a few seconds, service goes to upgraded state but the finish upgrade does not complete as part of the service upgrade using webhook

**Comment by mrajashree** [comment]
@cjellick @soumyalj This intermediate error is returned in the apiClient call. Webhook-service goes to the next service when it sees an error for the current service. This bug does not happen when startFirst is set to `false`. So I don't think webhook-service should wait once it sees error.

**Comment by sangeethah** [comment]
@cjellick @StrongMonkey , root cause could be the same as - https://github.com/rancher/rancher/issues/7878

**Comment by mrajashree** [comment]
In webhook-service after calling upgrade on a service, there's a wait logic before calling finishUpgrade. This wait logic keeps calling service reload every 5 seconds for around 3 minutes. It checks the value of service.Transitioning, if its value is "yes" it means the service is still upgrading without any errors, if its value is "no" then that means the service is done upgrading. But if its value is "error" even before the max time, it logs an error of this format `Waiting for 1s10 failed: Failed to allocate instance [container:1i122]: Bad instance [container:1i122] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [ports: [8091:8091/tcp], ResourceType: instanceReservation, Amount: 1]` and goes to the next service. The wait logic is only to give enough time for services to upgrade without any errors. Since this service had an error while upgrading, that error is logged, and so we won't be changing the wait logic for that.

**Comment by soumyalj** [comment]
Closing this issue for the same reason explained above.
