### ISSUE TITLE
'Timeout getting IP address' error on healthcheck and ipsec containers in v1.4.1

### ISSUE THREAD

**Issue by upayavira-ndn** [rancher/rancher#7902]
**Rancher Versions:**
Server: v1.4.1
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.10
scheduler: 0.4.0
kubernetes (if applicable): n/a

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
On Amazon, add a EBS volume to a host, and mount it at /var/lib/docker/overlay. Then connect this host to the Rancher server. Rancher infrastructure components will fail with the above (timeout) error.

Remount the partition as /var/lib/docker (after, obviously, moving lots of files around), and the infrastructure services will start up safely.

Whilst this is a reasonable workaround, we have 100+ instances in this scenario, making an upgrade from 1.1.4 to 1.4.1 lots of hard work. It would be really helpful if Rancher could support the scenario where /var/lib/docker/overlay is a mounted filesystem. Thanks!

**Comment by superseb** [comment]
Adding a host with mounted `/var/lib/docker/overlay` works fine from scratch in v1.6.0. You're talking about adding a new host with failing network and about upgrading from 1.1.4 to 1.4.1. What's the exact scenario to reproduce this?

**Comment by superseb** [comment]
Please comment if you still need help with this.

**Comment by kwaio** [comment]
I'm regularily having the exact same problem with v1.4.1 on VPC VM's (centOS7, kernel 3.10 LTS,  docker 1.12.6)
Each time I add a new host to an environment I get stuck in this state where ipsec container can't start because "Timeout waiting for an IP address", same as any other container that needs networking (Healthcheck, load balancers, etc) and no logs because ipsec-router sidekick doesn't start (Waiting for dependencies"

Which container handles the "DHCP" or any other IP distribution ?
