### ISSUE TITLE
[api] Can't update stacks via `/stacks` endpoint.

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#7921]
**Rancher Versions:**
Server: 1.4.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
No hosts in this environment, the server is in the cloud.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Everything done on a new environment without any hosts.

1. Get a list of stacks via endpoint `v2-beta/stacks/`.
2. Pick any entity, confirm that is has an `update` action, the URL is similar to: `../v2-beta/stacks/1st99/?action=update`
3. Do a PUT request to that URL.

**Results:** 
Receive a `405 Method not allowed`.

I've confirmed that the GUI uses another endpoint to update stacks: `/projects/1a12345/stacks/1st99`
This endpoint does work so I suspect it is a routing issue.

**Comment by SamMousa** [comment]
It seems this happens for a lot of entities, should I move this to #7897, or is this an actual implementation bug?

````
Account --> OK
Agent --> Bad method 405
ApiKey --> OK
AuditLog --> NOT UPDATEABLE
Azureadconfig --> NOT UPDATEABLE
Certificate --> Bad method 405
ClusterMembership --> NOT UPDATEABLE
ConfigItem --> NOT UPDATEABLE
ConfigItemStatus --> NOT UPDATEABLE
Container --> Bad method 405
ContainerEvent --> NOT UPDATEABLE
Credential --> Bad method 405
Databasechangelog --> NOT UPDATEABLE
Databasechangeloglock --> NOT UPDATEABLE
ExtensionPoint --> NOT UPDATEABLE
ExternalHandler --> OK
ExternalHandlerExternalHandlerProcessMap --> Bad method 405
ExternalHandlerProcess --> Bad method 405
ExternalService --> Bad method 405
Register --> NOT UPDATEABLE
HaConfig --> NOT UPDATEABLE
HealthcheckInstanceHostMap --> NOT UPDATEABLE
Host --> Bad method 405
Identity --> NOT UPDATEABLE
Image --> Bad method 405
Container --> Bad method 405
InstanceLink --> Bad method 405
IpAddress --> Bad method 405
Label --> NOT UPDATEABLE
Ldapconfig --> NOT UPDATEABLE
LoadBalancerService --> Bad method 405
LocalAuthConfig --> NOT UPDATEABLE
Machine --> Bad method 405
MachineDriver --> OK
Mount --> NOT UPDATEABLE
Network --> Bad method 405
NetworkDriver --> Bad method 405
NetworkDriverService --> Bad method 405
Openldapconfig --> NOT UPDATEABLE
Password --> OK
PhysicalHost --> Bad method 405
Port --> Bad method 405
ProcessDefinition --> NOT UPDATEABLE
ProcessExecution --> NOT UPDATEABLE
ProcessInstance --> NOT UPDATEABLE
ProcessPool --> NOT UPDATEABLE
ProcessSummary --> NOT UPDATEABLE
Project --> OK
ProjectTemplate --> NOT UPDATEABLE
Register --> NOT UPDATEABLE
RegistrationToken --> Bad method 405
Registry --> Bad method 405
RegistryCredential --> Bad method 405
ResourceDefinition --> NOT UPDATEABLE
Schema --> NOT UPDATEABLE
Service --> Bad method 405
ServiceConsumeMap --> Bad method 405
ServiceEvent --> NOT UPDATEABLE
ServiceExposeMap --> NOT UPDATEABLE
ServiceLog --> NOT UPDATEABLE
ActiveSetting --> NOT UPDATEABLE
Stack --> Bad method 405
StoragePool --> Bad method 405
Subnet --> Bad method 405
Task --> NOT UPDATEABLE
TypeDocumentation --> NOT UPDATEABLE
UserPreference --> OK
Volume --> Bad method 405
VolumeTemplate --> Bad method 405

````

**Comment by cjellick** [comment]
I know this is going to seem weird, but if you're calling `?action=udpate`, it is actually a POST action and intentionally so. All "actions" (special operations that don't fit any of the standard HTTP methods) are POSTs. 

A reasonable response might be "But update isn't special, that's what PUT is for!" You're right. I _believe_ update is available as an action primarily due to a quirk in our framework (or maybe something we simply overlooked).

A really good way to get familiar with the API is to go to the API tab in the UI and follow the link or to create a resource like a stack or container in the UI and the click the view in API link. The API UI that you're taken to will show you all the things you can do to that resource. Navigation and HTTP methods will be blue buttons, valid actions will be green buttons, and invalid actions (for the resource's current state) will be greyed out. If you click any of these buttons, you'll get a form representing the json request payload, and if you then click "Show request" we give you both a curl version of the request and what the request looks like in raw http.

**Comment by vincent99** [comment]
This is going to be because of account vs project/environment scope.  Admin users can _see_ all the resources at the top level but most things are owned by a project and can only be manipulated in the context of that project, either with an Environment API key or using the project-specific URL (`/v2-beta/projects/<id>/<type>`)

**Comment by SamMousa** [comment]
@vincent99 if they can only be manipulated in the context if their owner then the collection should not provide `upgrade` as an action. 
@cjellick I know how to get it to work, but I want to make work based on info provided by the spec and the APIs, not based on other information or human creativity.

**Comment by vincent99** [comment]
As with everything it's not really that simple.  As an admin you *can* manipulate them using only the information returned, but have to explicitly ask to act as the project, which there are header and query param options for (besides the different URL I mentioned).

The general way to tell if a `PUT`/`POST`/`DELETE` are allowed in the context is to look at the resource's schema's resourceMethods.  If you get `/v2-beta/schemas/stacks`, `resourceMethods` will be just `['GET']`.

`update` and `upgrade` are very different things and you guys are using them interchangeably, which is confusing.

- `update` is a "fake" action that is is on every resource as the result of the Java framework's implementation of `PUT` support.  It has the same effect as `PUT`, and calling it as an action works (AFAIK), but you should use `PUT`
- `upgrade` is a "real" action that is defined specifically on Stacks (there are some others like Service with a different action of the same name).  You invoke this with POST `${resource.actions.upgrade}`
- Incidentally `remove` vs `DELETE` is the same situation.  We've kept these because it provides a way to tell if `PUT` or `DELETE` are available for the particular instance in its current state, since they aren't always allowed, which the UI needs.

**Comment by SamMousa** [comment]
@vincent99 I mistyped `upgrade` instead of `update`, I'm aware of the difference and all this is only about `update`.

Also I have tested and confirmed that I can indeed find another path to the entity and then update it via the other update url... But if both ways are advertised via the API then both ways should work.

Take this:
````
{
  "id": "1a3",
  "type": "agent",
  "links": {
    "self": "\u2026\/v2-beta\/agents\/1a3",
    "account": "\u2026\/v2-beta\/agents\/1a3\/account",
    "configItemStatuses": "\u2026\/v2-beta\/agents\/1a3\/configitemstatuses",
    "hosts": "\u2026\/v2-beta\/agents\/1a3\/hosts",
    "instances": "\u2026\/v2-beta\/agents\/1a3\/instances",
    "physicalHosts": "\u2026\/v2-beta\/agents\/1a3\/physicalhosts",
    "storagePools": "\u2026\/v2-beta\/agents\/1a3\/storagepools"
  },
  "actions": {
    "disconnect": "\u2026\/v2-beta\/agents\/1a3\/?action=disconnect",
    "reconnect": "\u2026\/v2-beta\/agents\/1a3\/?action=reconnect",
    "update": "\u2026\/v2-beta\/agents\/1a3\/?action=update",
    "deactivate": "\u2026\/v2-beta\/agents\/1a3\/?action=deactivate"
  },
  "baseType": "agent",
  "name": null,
  "state": "active",
  "accountId": "1a9",
  "created": "2016-11-10T08:26:51Z",
  "createdTS": 1478766411000,
  "data": {
    
  },
  "description": null,
  "kind": "agent",
  "managedConfig": false,
  "removeTime": null,
  "removed": null,
  "transitioning": "no",
  "transitioningMessage": null,
  "transitioningProgress": null,
  "uri": "delegate:\/\/\/?vnetId=1&networkServiceProviderId=1",
  "uuid": "fd53fbe2-9703-4c93-861f-a4ef05099966"
}
````
This is the response from the API endpoint `/agents?limit=1` (the data part).
The agent with id `1a3` has 4 actions, one of it is named `update`. This leads me to think that I can do a `PUT` request to `/v2-beta/agents/1a3/?action=update`. However I cannot and get a `405 Bad Method`.

Then there's this:
````
{
  "id": "1eh424",
  "type": "externalHandler",
  "links": {
    "self": "\u2026\/v2-beta\/externalhandlers\/1eh424",
    "externalHandlerExternalHandlerProcessMaps": "\u2026\/v2-beta\/externalhandlers\/1eh424\/externalhandlerexternalhandlerprocessmaps",
    "externalHandlerProcesses": "\u2026\/v2-beta\/externalhandlers\/1eh424\/externalhandlerprocesses"
  },
  "actions": {
    "activate": "\u2026\/v2-beta\/externalhandlers\/1eh424\/?action=activate",
    "update": "\u2026\/v2-beta\/externalhandlers\/1eh424\/?action=update",
    "remove": "\u2026\/v2-beta\/externalhandlers\/1eh424\/?action=remove"
  },
  "baseType": "externalHandler",
  "name": "goMachineService-machine",
  "state": "inactive",
  "created": "2017-01-11T09:40:40Z",
  "createdTS": 1484127640000,
  "data": {
    "fields": {
      "processConfigs": null
    }
  },
  "description": null,
  "kind": "externalHandler",
  "priority": 2000,
  "removeTime": null,
  "removed": null,
  "retries": null,
  "timeoutMillis": null,
  "transitioning": "no",
  "transitioningMessage": null,
  "transitioningProgress": null,
  "uuid": "b5174f91-53d0-4ef0-9c1e-9e300378bbd0"
}


The external handler is actually updateable via the API at the specified endpoint.
I see no difference between these 2 entities that tells me that I can update one but not the other.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
