### ISSUE TITLE
kubectl not able to connect to remote cluster

### ISSUE THREAD

**Issue by nithin-bose** [rancher/rancher#7937]
**Rancher Versions:**
Server: 1.3.4
healthcheck: 0.2.0
scheduler: kubernetes
kubernetes (if applicable): k8s:v1.5.1-rancher1-7

**Docker Version:**
1.13.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Hosts are running RancherOS v0.7.1 (4.4.24) on aws
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external db. The rancher master is exposed to port 80 with ``-p 80:8080`` while running rancher/server container
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. Create a rancher server exposed to port 80 with ``-p 80:8080`` instead of ``-p 8080:8080``
2. Run kubernetes environment,  download the generated kube-config to ~/.kube/config
3. Run ``kubectl cluster-info``

**Results:** 
``The connection to the server cluster.mobscale.in was refused - did you specify the right host or port?``

**Expected:**
The cluster info to be displayed

**Workaround:**
Editing the server entry in ``~/.kube/config`` from ``https://<rancher server host>/r/projects/1a228/kubernetes`` to ``https://<rancher server host>:80/r/projects/1a228/kubernetes`` (notice the ``:80`` added) makes everything work as expected. 

I have always wondered how the generated kube config and the kubctl has an ``https`` endpoint when the rancher server itself runs on ``http``

**Comment by appleboy** [comment]
The same problem in AWS EC2.

**Comment by vincent99** [comment]
Is this only with exactly port 80?  The UI constructs the config file based on the URL you're loading it on and the port would be missing for the special case of http+80 (or https + 443).

The config is always https because kubectl will only do authorization over TLS.  So the Rancher port is actually both http and https depending on what the connection looks like, via black magic.  But copying the URL from the UI and changing it to https makes the implied port 443 instead of 80 if not present in this exact case, and nobody is home on 443.

**Comment by superseb** [comment]
The above case should be fixed in v1.6.11, where we explicitly add port 80 when the default port (80) is used in the URL.

**Comment by superseb** [comment]
Also, documentation has been added for `kubectl`: http://rancher.com/docs/rancher/v1.6/en/kubernetes/#kubectl
