### ISSUE TITLE
503 from LB On Service Upgrade

### ISSUE THREAD

**Issue by siosphere** [rancher/rancher#8015]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.14
scheduler: 0.4.0
kubernetes (if applicable):

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** 
Ubuntu 16.04.1 LTS AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
Single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a web service (siosphere/php7 for example), setup basic health check (default settings, get request to /)
Create a loadbalancer, and point a domain to the web service
Verify that you can access the url

Upgrade the webservice, while checking the "start before stopping"

**Results:** 
Immediately while the new container is starting, you will start getting 503s from the loadbalancer. The new container should NOT be under the load until it registers as healthy or has fully started, but traffic is being routed to the new container before it has fully started.

Additionally, once the container has started there is ~1-2 seconds where the DNS has not yet resolved, but the container is still being served to from the loadbalancer.

Proposed solution would be to make sure that the container is not added to the loadbalancer until it is marked as healthy (which should also take care of the DNS issue)

**Comment by stunndard** [comment]
I have the same issue here.

**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
scheduler: 0.6.3
lb-service-haproxy:v0.5.9

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04, VPS server

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Whenever I upgrade a service with scale=1, healthcheck configured and "start before stopping" the following occurs:

1. New container starts, while the old one keeps running. At the same time, the LB for some reason switches from the old container to the new one, thus returning 503 if you try to access the web service at this moment.

2. New container started, but healthcheck is not yet successful, because the new container is still loading. The status at this moment is "Running" for the old container and "Initializing" for the new container. LB still returns 503 errors at this moment.

3. Healthcheck is successful and the status is "Stopping" for the old container and "Running" for the new container. At this time, after some delay, the new container becomes available and there is no more the 503 error from the LB.

Proposed solution is that the LB **switches from the old container to the new one only at step 3**. Not step 1 as it is for now.

If, however, the service has scale >= 2, and the upgrade is done with "--batch-size 1" option, then there's no 503 errors from the LB because it upgrades containers one by one. But it's very inconvenient to have 2 running instances of all our web services just to make a zero downtime upgrade possible.

Please fix it, as for now this issue is a major show stopper to have a true zero downtime upgrade with Rancher.

**Comment by stunndard** [comment]
Any update on this, anyone? No one cares about zero downtime service upgrade?

**Comment by kirrmann** [comment]
Same issue with v1.5.2 and rancher/lb-service-haproxy:v0.6.2

haproxy.cfg immediately switches to the new container, which is still initializing.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.2` Cattle: `v0.177.9` UI: `v1.5.8` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by avarabei** [comment]
Reproduced on my end also. This is actually a big issue for me, the downtime is not accepted for my services.

**Comment by deniseschannon** [comment]
This is due to https://github.com/rancher/rancher/issues/2777. We are aiming to fix this for Rancher 1.7.
