### ISSUE TITLE
Going to or Sorting in Audit Log page throws console errors

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8121]
**Rancher Versions:** master 3/9

**Steps to Reproduce:**
1.  Go to Audit logs
2.  Sort by each column

**Results:** 
Each time I sort I get a: 
fetch.js:404 GET http://35.184.40.80:8080/v2-beta/identities/1i!rancher_id%3A5?sort=name 404 (Not Found)
fetch.js:404 GET http://35.184.40.80:8080/v2-beta/projects/1a1?sort=name 404 (Not Found)

**Comment by westlywright** [comment]
Note: This happening because of both the `environment-name` and `identity-block` components take an id to fetch from teh user store the corresponding account info. But because some of these id's exist outside the user store they are not found. We dont have a way at the audit log level to know where the event occurred with out firing these calls afaik.

**Comment by vincent99** [comment]
n/a in 2.0
