### ISSUE TITLE
GCE support subnetworks

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#8127]
Currently it's not possible to create GCE machines via rancher that are using subnetworks. Subnetworks are frequently used on GCE for separation. 
Docker-machine doesn't support it currently but you still have an option to set network in the UI ( is it used? ) so maybe you could add subnetwork as well if you are doing some magics.

Otherwise there is a pull-req https://github.com/docker/machine/pull/3724 for supporting subnetworks on GCE that they are willing to merge if it get rebased.

**Comment by vincent99** [comment]
We don't really support the GCE driver at all because it only does browser OAuth.  But if you enable it anyway all the options are directly mapped to the driver's options.

**Comment by guzmo** [comment]
But the browser oauth doesnt matter if we are running the server there? It seems to work until the subnetworking part. If that pull-req gets merged, will you implement it in your generic google driver as well? I mean, even if they are using browser oauth they are among the biggest cloud providers. We need to support different providers and I rather not do different autoscaling of hosts for each provider. This is one of the nice parts about Rancher, that there is one solution to support multiple providers.

**Comment by vincent99** [comment]
Our API-level support for machine drivers is all generic...  It reads the fields each driver exposes and makes them available through the API.  Then there is custom UI for most of the more popular ones.  So yes, if that is merged it would be available in Rancher once we are packaging a version of machine that includes that commit.

They may be big but every single other major driver provides a way to directly pass API keys instead of doing interactive browser auth and associate them with only the one machine being created.  Microsoft added similar support because of community requests and [quickly, directly fixed an issue](https://github.com/docker/machine/issues/3782) with multi-tenancy in it for us.  Google's model works fine for running machine on a desktop and logging in once but does not fit at all with the way we run it on a remote, multi-tenant environment (inside the server container).  And they [don't care](https://github.com/docker/machine/issues/1061#issuecomment-152246328).

It is possible if the server is running in GCE that you could pull the right files or env vars into the server container(s) to make it work using the VM's service account without passing any auth info, but I don't know the details.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
