### ISSUE TITLE
Enable Docker to accept DeviceMapper as an option for volumes

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#82]
POC: enable Docker GraphDriver to include DeviceMapper as an option for volumes.

1. POC completed.  Working on PR to kick start discussion.
2. Add validation tests before submitting PR.

*Note* Docker community is also working on a "volumedriver" option for disk volumes.  Also, current PR does not include options for data migration for existing Docker containers.

**Comment by will-chan** [comment]
- Investigate whether to write a user space program to read the block changes or add a kernel module to do this.

**Comment by will-chan** [comment]
- Able to use a tool to extract block changes, and have been able to restore a volume and mount.  
- Work on the patch using device manager as a volume drive and submit it to Docker.

**Comment by thaJeztah** [comment]
Wondering; volumes in docker are also used to circumvent the performance penalty of layered file systems; using device mapper for volumes would result in bad performing volumes, or am I misunderstanding the way this will be used here?

**Comment by ibuildthecloud** [comment]
Device mapper is basically the guts below LVM.  You can expect pretty close to the same performance as LVM when using device mapper.  The problem with device mapper in Docker though is that by default it is implemented with a loop back file which makes the performance terrible.  Also creating new devices in device mapper is not particularly fast.

We are prototyping volume management with this though.  We want to be able to do `docker volume create`, `docker volume snapshot`, etc.  This is just exploratory.  Device mapper seems like a good approach because it provides snapshotting abilities at a block layer.

**Comment by thaJeztah** [comment]
Sounds interesting! I *did* see the advantages of devicemapper (snapshots, possibly moving or replicating between nodes) but wasn't aware that devicemapper would allow usable performance with the right comfiguration.

Does it have advantages over ZFS?

**Comment by yasker** [comment]
Here is a good article about device mapper(and others) performance. Back the device mapper using raw partition would be the way to get the best performance:
http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/

**Comment by will-chan** [comment]
Tabling this for a future milestone task.

**Comment by thaJeztah** [comment]
I guess this has become https://github.com/rancher/convoy ? :+1:

**Comment by yasker** [comment]
@thaJeztah Yeah. :dancer:

**Comment by thaJeztah** [comment]
Great! Gave it a short spin this week, looking good :smile:

**Comment by yasker** [comment]
@thaJeztah Thanks! :smile:
