### ISSUE TITLE
Ability to automatically unmount and remount EBS volumes if the host went down

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8252]
Ability to automatically unmount and remount EBS volumes if the host went down

**Comment by StrongMonkey** [comment]
This is more complicated. When creating healthcheck containers using EBS volume, if host went down, it will be deleted and re-created on another host. But the volume is not actually detached because the host is re-connected and cattle can't talk to the ebs-driver to detach the volume. This will result an error in creating instance on another host which shows volume is in use by another instance. 
Possible solution:
In attach(), try it 10 times and if still can't succeed, force to detach the volume. 
@cjellick @LLParse any thoughts?

**Comment by LLParse** [comment]
I would agree that this is probably the best solution to the failure scenario, given the current design.

There is still potential for other problems - consider what happens if a failed host comes back online. What state would the containers be in at this point? What would cattle do with them? What happens if 2 hosts called attach() at roughly the same time? These races can't easily be avoided from inside the storage driver code without getting really creative and using zookeeper/etcd/consul/etc to coordinate. Our best bet is to modify behavior of cattle scheduler/reconciliation to avoid any races that might occur.

**Comment by StrongMonkey** [comment]
@LLParse @deniseschannon I don't think if detaching a volume when host is reconnecting or disconnected is really a good idea. If a host is reconnecting, it only means that it lost the connection between rancher and itself(it doesn't mean that the host is dead), so it might break the consistency if there are I/O happening inside the volume when detaching. I would doubt this is a necessary feature for certifying EBS, and would rather leave it alone when the host went down than forcing to detach it.

**Comment by StrongMonkey** [comment]
the fix is in rancher/storage-ebs:v0.8.0.

**Comment by soumyalj** [comment]
Tested with master. Create a setup with 2 AWS hosts in the same zone and create an EBS volume vol1. Create a health check enabled service "testservice" of scale 2 which uses volume vol1. Power off host1. testservice1 containers move to host2 which is in the same zone. The volume gets detached from host1 and gets created on host2
