### ISSUE TITLE
Custom Network Mask for managed network not applied

### ISSUE THREAD

**Issue by SilentHunter124** [rancher/rancher#8277]
**Rancher Versions:**
Server: 1.5.1
healthcheck: v0.2.3
ipsec: v0.9.4
network-services: v0.4.8
scheduler: v0.7.4

**Docker Version:**
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.12-rancher

**OS and where are the hosts located? (cloud, bare metal, etc):**
VMWare Virtual Machine
Operating System: RancherOS v0.8.1
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.766 GiB

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
3 Cattle Environments

**Steps to Reproduce:**
Change the IP Address according to your FAQ:
https://docs.rancher.com/rancher/v1.5/en/faqs/troubleshooting/
To
172.30.0.0/24

**Results:** 

The IPSec network which is created is 172.30.0.0/16 but should be smaller.

**Comment by tfiduccia** [comment]
@SilentHunter124 - I cannot reproduce your issue.  How are you seeing that it is /16 instead of /24?  I checked the ipsec ymls through the UI and it is set properly.  The created containers also seem to be working properly.

The only thing I can of is that you are trying "update" the ipsec instead of creating a new environment with that set.  You cannot edit/update the ipsec for a pre-existing environment.

**Comment by SilentHunter124** [comment]
Hi, 

no it is not an update of ipsec. Just take a look at the network configuration inside of a deployed container. There you can see the misconfiguration.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
