### ISSUE TITLE
Add support for nested groups in LDAP/AD

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8317]
**Rancher Versions:** v1.5.3

**Comments:**
Add support for nested groups.  So I can have a "AllGroups" which has a bunch of groups in it.  Then I just have to add "AllGroups" to authentication and people inside the subgroups will have access.

GroupA has GroupB, GroupC and GroupD
People in GroupB, GroupC and GroupD all have access.

**Comment by rocketeer125** [comment]
+1 on this.

From what I can see, the logic is...

  **1) Lookup the Group and see if the user is a member** rather than  **2) Lookup the MemberOf field of the user**. With 1), you are not able to traverse to groups who are members of groups. 2) provides a flat structure with the MemberOf overlay.

**Comment by lanwench** [comment]
Anyone? Bueller? This is a huge pain for a lot of organizations.

**Comment by pasikarkkainen** [comment]
To easily implement nested ldap groups support against microsoft active directory:
https://stackoverflow.com/questions/6195812/ldap-nested-group-membership

eg. one can use the special "LDAP_MATCHING_RULE_IN_CHAIN" feature (sometimes called also: LDAP_MATCHING_RULE_TRANSITIVE_EVAL), which is an Extensible Match rule, implemented as special OID "1.2.840.113556.1.4.1941", allowing one to query all the nested group memberships easily with one single query).

Support for nested groups / extensible matches with other ldap servers varies, and might need different implementations.

**Comment by mrajashree** [comment]
Closing it as a dup of https://github.com/rancher/rancher/issues/12987

**Comment by deniseschannon** [comment]
Due to upgrade issues from earlier versions that were not using nested groups, we will be turning the nested group search off by default as of v2.0.6 (https://github.com/rancher/rancher/issues/14482) for AD and openLDAP. 

If you are using AD or openLDAP, please review the schema section on whether or not you want the nested group membership setting enabled. By enabling nested group membership, it will provide permissions to users that are in groups of groups, but due to this extensive user search, it could cause slower search results/log in.
