### ISSUE TITLE
influxdb filling up host storage

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8318]
**Rancher Versions:**
Server: 1.4.1
kubernetes: 1.5.2

**Docker Version:**
1.12.6

**Steps to Reproduce:**
- We're not setting the retention policy for influx data
1. Let grafana run for some time...

**Comment by LLParse** [comment]
https://github.com/rancher/kubernetes-package/pull/43
https://github.com/rancher/rancher-catalog/pull/614

Work was tightly coupled to my previous assignment (Monocular on Rancher) because both tasks required refactoring our addon-starter script to create helm releases in addition to raw k8s resources.

**Comment by galal-hussein** [comment]
The new heapster addon deployment has the ability to speicify a hostpath volume for influxdb data dir, when deploying the k8s, choose specify a path to "InfluxDB Host Path".

The current stack doesn't offer retention policy option due to the raised issue in  https://github.com/kubernetes/heapster/issues/1579, the heapster stack will allow setting retention policy when the issue in the upstream is fixed.

**Comment by LLParse** [comment]
Waiting for upstream fix

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

The workaround is to use the catalog to direct your logs to a different location.
