### ISSUE TITLE
Catalog configuration file changes

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8319]
1. Support `template.yml` in addition to `config.yml`
2. Support `icon.extension` and `icon-example.extension` in addition to `catalogIcon.extension` and `catalogIcon-example.extension`
3. Support `compose.yml` in addition to `docker-compose.yml`. It should support all keys in `docker-compose.yml` and `rancher-compose.yml`.
3. Support `template-version.yml` in addition to `rancher-compose.yml`. `template-version.yml` should only contain the keys in the `.catalog` section of `rancher-compose.yml`, but does not require the `.catalog`.
4. Add in `default_version` in `template.yml`, which should replace `version`.
4. Some keys in `template.yml/config.yml` use camel case rather than underscore separated. Both should be supported.

**Comment by cjellick** [comment]
I assumed that we have to continue support `version` in template-version.yml for backwards compatibility?

**Comment by deniseschannon** [comment]
Yes, anything that we change/add should be additional functionality but we'll need backwards compatibility for all the existing fields.

**Comment by SamMousa** [comment]
Is there any argumentation available for these changes?

> 1. Support template.yml in addition to config.yml
What does this do, just add another file / choice without functionally adding anything?
What happens if they both exist?

> 2. Support icon.extension and icon-example.extension in addition to catalogIcon.extension and catalogIcon-example.extension

This is more file searching, wouldn't it be better to instead put this in configuration? Allowing me to specify any path in the repository?

> 3. Support compose.yml in addition to docker-compose.yml. It should support all keys in docker-compose.yml and rancher-compose.yml.

What's the new compose.yml? Is it documented somewhere?

> 4. Support template-version.yml in addition to rancher-compose.yml. template-version.yml should only contain the keys in the .catalog section of rancher-compose.yml, but does not require the .catalog.

Not sure what the advantage is, if we have to duplicate these files for each version there's no reason to split them up.

> 5. Add in default_version in template-version.yml, which should replace version.

What does `default_version` mean, is the word version in `template-version.yml` not a placeholder? Why would I specify a version in both the file name and the file contents?

> 6. Some keys in template.yml/config.yml use camel case rather than underscore separated. Both should be supported.

I think it would be good to highlight "bad" catalogs in the UI so at some point you can stop supporting both. It is not feasible to be backwards compatible forever, adding an incentive for catalog owners to update their configuration without actually breaking stuff will make it easier in the long run.
Then of course you can also mark the old syntax as deprecated and actually stop supporting it in the next major release.

I feel we're getting a look into the decision but not into the decision making, while this issue might provide a team member with insight into what is needed, it does not provide outsiders with any details needed to follow the reasoning. (So there could very well be some real good arguments for all points and my notes could be irrelevant because of them)
