### ISSUE TITLE
k8s - catalog still accessible (intentionally and un-intentionally)

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#8336]
**Rancher Versions:**
Server: 1.5.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.5.4-1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.3, vmware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, external mysql db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
Option 1 - Go into "infrastructure stacks", click on "up to date" next to any stack, then click "cancel" on the stack upgrade page, you are redirected to the "catalog" page.

Option 2 - Go into a k8s environment, type "catalog" after the env ID - 

`https://some.url.here:8080/env/1a19/catalog`

**Results:** 
Catalog should not be accessible (i guess?) not sure if it's a big deal, catalog items don't seem to work anyway.

**Comment by tfiduccia** [comment]
This issue has been reproducible since we made upgrades available.  And it's not just a kubernetes issue.  This will happen with all types of environments.  If you cancel out of a 'available upgrade' or 'up to date' button for a stack, then cancel, it will always leave you in catalog page.  I think there is another issue entered about this but I can't find it.

**Comment by vincent99** [comment]
n/a for 2.0, don't do that™ for 1.x.
