### ISSUE TITLE
etcd volumes should be stack scoped

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8361]
etcd should use stack scoped volumes. This avoids issues when reusing hosts that had another Kubernetes cluster running at some point.

Likely depends on #8362 to handle upgrade scenarios.

**Comment by LLParse** [comment]
@joshwget This totally makes sense for the existing etcd template, but is not necessary with the new operator model. The operator implements its own volume scoping strategy and manages the volume lifecycle.

The key bits here are:
* Cluster garbage collection. When an etcd cluster is torn down, operator deletes the containers and volumes.
* Global garbage collection. When etcd-operator is down and an etcd cluster is torn down, the DELETE event is missed. The global garbage collection looks for all resources created by the operator and deletes them if they no longer belong to a cluster.
* Delete-on-create. There's still a small possibility of volume collision, so before operator schedules a container with a named volume `<stack>-<service>-<ordinal>` (ex. kubernetes-etcd-0000), it will proactively query for detached named volumes with that name and delete them.

The delete-on-create logic is required because volumes are still orphaned sometimes (for example, somebody deleted an etcd container via Rancher UI) and the global garbage collection occurs infrequently.

Closing for now
