### ISSUE TITLE
Allow ability to use private registrys for the pod infra container used in k8s templates

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8410]
We've introduced the ability to use default registry for infrastructure services and the abiltiy to specify a private registry for addons that are started by kubernetes, but the `pod infra container` used in the kubelet still requires access to the internet.

We need to add the ability where this image could be pulled from the private registry.

**Comment by galal-hussein** [comment]
Rancher version: 1.5.4-rc1

@deniseschannon I tested on kubernetes 1.5.4-rancher1-1 and it failed, the host failed to pull the containers from the private registr, i think the problem is in the following option in the template for kubelet service:

```
   - --pod-infra-container-image=artifactory.art.local:5003/gcr.io/google_containers/pause-amd64:3.0
```
The `gcr.io`  shouldn't be added because the private registry should already be mirroring the gcr.io, i confirmed that by upgrading the service and removed the `gcr.io` part and the host were able to pull the pod infra image and the addons successfully

**Comment by galal-hussein** [comment]
Rancher version: 1.5.4-rc1
Kubernetes: 1.5.4-rancher1-1

Steps:

- Set up a private registry that mirrors gcr.io and docker.io
- Register a host with rancher
- Launch kubernetes template with the following options:
  - pod infra container image: google_containers/pause-amd64:3.0
  - private registy: `<private-rgistry-address>`

I was able to see the addons being deployed and the pod infra container image being pulled from the private registry
