### ISSUE TITLE
network-service auto upgrade caused host down (with private registry as default)

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8508]
Rancher Versions: 1.5.3
Docker Version: 1.12.6
OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 16.04
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single node rancher
Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Kubernetes
Steps to Reproduce:

I have registry.default set with my private docker registry and upgrade.manager=false.
But network-service tried to upgrade automatically yesterday because there was a new version, since I don't have an image named rancher/metadata:v0.9.1 and network-manager:v0.6.6 in my private registry yet, so all network services on my host was stopped. 
I think this behavior is unexpected, there should be a switch to let user choose if network-service can be auto upgraded, and I'm confused why this behavior is not under control by upgrade.manager=false, thanks.

**Comment by niusmallnan** [comment]
There is a workaround that users can fork the rancher-catalog repo and set a local repo in Rancher.
If the local rancher-catalog does not update, the network-service does not upgrade yet.

But I think let users control the network-service upgrade behavior is better.

**Comment by deniseschannon** [comment]
For our 1.5.0 release, we had to force upgrade network-services infra stacks for all users as we had changed how metadata was working. This forced upgrade was designed in the code so that any new template for network-services would automatically be upgraded. What we hadn't factored in was that our upgrade manager would be upgrading network-services ANY time there was a new template available for network-services. We had been focused on the upgrade from 1.4.x to 1.5.0 but hadn't considered what would happen from post 1.5.0.

For 1.5.4, we had released some new network-services template (which has considerable fixes), but hadn't added a correct minimum version of 1.5.4 to avoid triggering an automatic upgrade of the network-services. We added the correct minimum version to these templates within 12 hours. 

Going forward with 1.5.x, we have understood that we can no longer add in network-services templates for a release without also shipping an accompanying Rancher release. Therefore, no users will be automatically upgraded regarding their network-services.
