### ISSUE TITLE
How will Moby affect Rancher?

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#8541]
It appears as if Docker has restructured. I'm curious to know how this will affect the Rancher project. Obviously everything is still a bit in flux.

**Comment by frekele** [comment]
Docker has always been a problem with every release, they changed the entire design structure, including and removing components in each release. This affected compatibility all the time, after a while it seemed that the project began to stabilize. But now with this surprise, a refactoring will be necessary in many projects.

Also would like to know what will affect in the Rancher Project.

**Comment by shykes** [comment]
This change will not affect Rancher. Docker binaries remain installable and usable in exactly the same way. All the source from the docker/docker repo is still available. And Moby makes it easier for Rancher to create custom builds if they want to.

@frekele I believe I have already explained this to you on the Moby repo :)

**Comment by willseward** [comment]
@shykes I was thinking that as well. I'm excited to see how Rancher can take advantage of this.

**Comment by ibuildthecloud** [comment]
The transition to the Moby Project actually started a couple months back with a discussion among the Docker Project maintainers.  The discussion was about the dual nature of Docker as both a product and a project.  The dual nature served Docker (Project and Inc.) well in the beginning but over time has grown to cause conflicts.  Docker strives to be as open and community driven as possible, but at the end of the day Docker, Inc. must make hard decisions as to what their product should be.  As a group of maintainers we all agreed that the product and project should be split.  The Moby Project is that split that gives a new home to the vast major of the Docker code, but not the product.  This allows us to innovate, contribute, and steer containers technologies in ways that weren't possible before.  We now have the ability to address use cases that are quite valid from a technical perspective, but would previously conflict with the Docker product.  One such use case is RancherOS which I'll touch on a bit later.

This move to Moby should not be viewed as a destabilization of Docker.  Honestly all we have done thus far is renamed a repo and updated a README.  In fact we wanted to do so much more but that one act of moving the repo caused such an uproar that we paused all operations.  We felt it was better to make sure it was clear to everybody what we are doing before making further changes.  In fact a group of maintainers spent almost 5 hours today discussing how we can better communicate the intentions behind the Moby Project https://twitter.com/lmarsden/status/855183909230977029.

The Moby Project was introduced with the idea of componetizing Docker into a series assemblies.  At DockerCon a neat demo was done using the `moby` tool to assemble various components into customized Linux operating system images.  While very cool, this seemed to have confused people.  The end goal of Moby is to further componentize Docker.  This is nothing new.  This work has been going on for quite a long time.  I mean this in the nicest way possible but let's just say Docker 0.x was a fabulous plate of spaghetti.  Thanks to over a thousand contributors and the maintainers Docker is currently a well organized set of libraries and packages. We are now ready to move to a fully componentized architecture.  In fact this has already started with runc and containerd.  While the Moby Project was introduced with a focus on componentization, this has long been a goal of the Docker project.  If anything, the dual nature of product and project has hampered our ability to do this.  With the Moby Project we can now move forward on this exciting phase.

Now to directly answer the question, How does this impact Rancher users?  For most users you won't see really any change.  Docker is still Docker.  It hasn't changed, and will continue to be the Docker you know and love (with hopefully a better internal architecture).  Where you will see a change is in RancherOS.  RancherOS is a highly specialized application of containers.  RancherOS is an operating system in which all components are Docker containers.  In order to accomplish this we have historically done some fairly unnatural things with Docker containers.  We need some really low level knobs in Docker to make RancherOS possible.  Docker has been kind enough to give us many of the knobs we need much to the detriment of the Docker UX.  For example `--uts=host`.  I would guess 99% of Docker users have no idea what that flag is for, but RancherOS requires it so that DHCP can propagate hostname changes dynamically.  Going forward the Moby Project is going to be absolutely great for RancherOS.  We can keep the same great Docker user interface, but with Moby we can get access to all the fancy low level Linux knobs we need.  In the end you will see RancherOS get smaller, faster, and more secure.
c
I'm very much in favor of Moby and hope people understand that this a good move for everyone involved.

**Comment by finid** [comment]
@ibuildthecloud, yours is a much better explanation of `moby` than the original announcement. Thank you.

**Comment by willseward** [comment]
@ibuildthecloud I agree! That was a fantastic explanation. I'm excited to see how this plays out.

**Comment by frekele** [comment]
@ibuildthecloud great explanation.

As soon as the PR was created, I was really confused, because simply the docker project had changed, I had not understood, now it's clearer to me.
As the [thread] was unfolding with community input and comments from @shykes I began to understand the real purpose of this change. And I truly fully agree that the moby project only brings more advantages to the open source community.



This will bring more Collaboration of the community, and each time we will have a more incredible tool beyond what it already is.

[Thread]: https://github.com/moby/moby/pull/32691
