### ISSUE TITLE
Automatic upgrade of infrastructure stack

### ISSUE THREAD

**Issue by brunograz** [rancher/rancher#8562]
**Rancher Versions:**
Server: v1.5.0
rancher/metadata from v0.8.11 to v0.9.1
rancher/network-manager from v0.5.3 to v0.6.6

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Launch rancher-server:v1.5.1
Create a new host
After some mins (~30mins) the infrastructure stack, network-services more specifically, are automatically upgraded.

Note that the setting upgrade.manager defaults to false and was not changed.

**Comment by cjellick** [comment]
@brunograz were you upgrading from a previous version of Rancher? If so what version? At any rate, we had to automatically upgrade those services in the 1.5.0 release because of a refactoring that made backwards compatibility not possible. [We mentioned it in the release notes under the Important - Upgrade section.](https://github.com/rancher/rancher/releases/tag/v1.5.1) I suspect this  is at the root of what you observed.

**Comment by brunograz** [comment]
@cjellick I was not upgrading from a previous version. Just launched rancher-server v1.5.0 and noticed the  upgrade of network-services stack.
As you pointed out, this is mentioned in the release notes and is expected to happen. 
Many thanks.
