### ISSUE TITLE
User session expires too quickly resulting in frequent forced logouts

### ISSUE THREAD

**Issue by wrsuarez** [rancher/rancher#8566]
Can't identify what causes it but we get prompted quite often to reauthenticate when switching between environments. The troubling part is its not consistently happening when switching

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.ha`|

**Comment by pulberg** [comment]
@wrsuarez I had this happening as well, it turned out to be a disk space issue with the Rancher DB server.  The auth info when using AD/LDAP is often quite large, and is written to the /tmp folder on the DB server.  In my case, there was not enough room on the disk with /tmp for the auth data to be written, i'd give that a look.

**Comment by aemneina** [comment]
@wrsuarez did you manage to sort your issue?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
