### ISSUE TITLE
Spec: How to "drain" connections for a stopping lb target

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#8627]
**Problem**

Existing connections drop can be caused due to the backend server picked by LB to forward the request to, going down in the middle of the request. So when backend service is stopped/upgraded via Rancher, and the service acts as a target service in the LB(s), there is a chance that the existing connections to it can be dropped. Ideally we should drain the connections to it from all the LBs, and only then execute the container stop. 

**There are 2 ways to drain connections to a target backed**

a)  haproxy DRAIN backend/server state:

- haproxy drain mode can be set on the backend using unix socket command:
echo "set server backend/serv state drain" | sudo socat stdio /etc/haproxy/haproxysock

- This sets the backend in DRAIN mode. No new connections are accepted and existing connections are drained. 
- However the drain state cannot be set via haproxy config. Also if a config reload happens, seems like drain state set via the socket is overwritten.

b) set weight to 0 for the target backend:
- haproxy socket commad:
echo "set server backend/serv weight 0" | sudo socat stdio /etc/haproxy/haproxysock

- Seems like we can set the “weight” of the backend to “0” via socket command or also via config file http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#5.2-weight 
“A value of 0 means the server will not participate in load-balancing but will still accept persistent connections"

- This change can also be done via haproxy config.

**How to check drain is complete**
- Check Stats:
haproxy provides a socket command to check stats per backend:
echo “show stat" | sudo socat stdio /etc/haproxy/haproxysock

- It reports data related to sessions and connections: https://gist.github.com/alq666/20a464665a1086de0c9ddf1754a9b7fb

- Out of these, I see that the stats property “rate” (number of sessions per second over last elapsed second) goes on increasing if we start hitting the target service in a loop and it is zero when the backend stops to accept new connections. 

- So “rate” can be checked and if it is 0, we can say that there are no more sessions active and can use this to say DRAIN is done.

**Set “drain” or Set “weight”?**

a) Problem with using “drain” mode on the backend approach:  This has to be done via  socket command and cannot be done via the haproxy config change.
If a haproxy config reload happens in parallel or after setting the backend in DRAIN,  this DRAIN state gets lost.

b) In case of our lb_controller, all changes to the haproxy are done via config reload. Any change as starting a new service/service stopped/any other metadata change will cause a haproxy reload to happen. So if we have set some backend in DRAIN via CLI (after receiving an event from cattle for instance.stop) and at same time a config reload gets triggered, we will lose the DRAIN mode set.

c) Another problem I see is currently lb_controller only looks at “starting” and "running” containers and adds backends to haproxy config for them. The container we plan to set in DRAIN will be in “stopping” state and any metadata change happening in parallel (causing  haproxy reload) will not include that “stopping” backend in the haproxy config at all and reload. 
We will have to fix this in either case (set drain or set weight) by keeping “stopping” containers in backend list.

So given the above, seems like we need use “set weight 0" method via a config change or via socket command + fix lb_controller to keep “stopping” containers in backend list with weight 0.

**Workflow** 
1) When a target instance is getting stopped, cattle should send event to lb_controller. Send this event with very short timeout and on timeout cattle should reschedule the instance.stop action.

2) On receiving this event, lb_controller should:
- if instance "drain complete via stats" is recorded. Finished (success/timeout) and reply back to unblock container.stop
~~- check if the backend is already set for drain. [maintain a drain-list in memory or check backend weight via socket]~~
- If not, set that target backend weight “0” via CLI or via config (need to check what is better in the given lb_controller design).
- Lastly, lb_controller should check stats on that backend and if the “rate” value is zero, send reply back to cattle. If “rate” is non-zero, do not send any reply and let cattle hit timeout on this event.

3) If any interim config reload happens, lb_controller should also keep the “stopping” containers in the config with weight “0"
4) Upon next event from cattle, again do step 2 above.

**Questions** 
1) Is there any other property in stats, that we should be looking at, other than “rate"?
2) Any problem we know with setting weight to zero?
3) Any reliable way of testing that the existing connections are really getting drained by haproxy via set weight 0?
4) How long should cattle keep sending events?

**Comment by prachidamle** [comment]
@cjellick @ibuildthecloud please review
@deniseschannon fyi

**Comment by cjellick** [comment]
To address your specific questions as best I can:
1. Is there any other property in stats, that we should be looking at, other than “rate"? _// Answer:_
  - I could only find the deprecated reference: https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#9.1. But according to that, req_rate might be another option.
  - One thing to note: both rate and req_rate represent the number of the last second. So, maybe you want to wait until you see a rate of zero for 3 seconds. Maybe one second is enough though. Would like @ibuildthecloud and @vincent99's input on this.
  - Both rate and req_rate represent new connections. They may not tell us what we need to know about existing connections
2. Any problem we know with setting weight to zero? _//Answer:_ From the docs that I read (same as you, I'm sure), it seems like a pretty reasonable solution. My only question would be around persistent connections and how those are handled when weight is 0.
3. Any reliable way of testing that the existing connections are really getting drained by haproxy via set weight 0? _//Answer:_ Seems like we could script tests for this in some reliable way, but might require interacting with some lower-level libraries.
4. How long should cattle keep sending events? _//Answer:_ Cattle should resend indefinitely until the lb-controller responds properly. But the lb-controller should probably give up after some configured number of seconds (30?)


My questions/comments:
- Do we want to allow users to configure this or just always have it on?
- Is this coming from a specific customer or user because I'd like a more specific scenario described that this is meant to address. Are they talking about persistent http connections or long lived websocket connections or something else all together? The design seems reasonable, but I think without more specific success criteria, we could end up implementing the wrong thing.

Ping @ibuildthecloud @deniseschannon @vincent99

**Comment by vincent99** [comment]
Unless I'm missing something the main number you want to look at is the number of current connections/sessions, not the rate at which new ones are coming in...  So that's `scur` for the backend and wait until it's zero, or until you hit a timeout limit.

It seems like this should integrate with the new upgrade management.  For start-before-stop you can just create all new containers, set the weight of the old ones to 0, and leave the old ones running (ideally with cosmetic or healthState of `draining`).  Once the connection count goes to 0, or the maximum time is exceeded, kill the container.  Or have no specific logic for that and just let garbage collection kill them (there's an explicit user action for it now too).

For stop-before-start it would have explicitly watch for the count to go to 0, stop the instance and start the new one before it can continue to the next batch.

**Comment by vincent99** [comment]
Persistent connections (HTTP keep-alive) should be only going to the balancer, the balancer->backend isn't keep-alive by default (the `http-server-close` option).

WebSockets are never going to get closed though without intervention.

**Comment by cjellick** [comment]
Talked to @vincent99 and a few other things have come up:
1. The drain timeout should be a property that the user can control. It should be set along side the other upgrade-strategy properties like batchSize and the one that controls start-before-stop. Apparently, these are moving from the upgrade action to properties directly on service in 1.7.
  - Follow up question: is this a property only of upgrade or does this need to be supported on nomral instance stop?
2. We should update the transitioning message of the container to something like "Waiting for connections to drain"
3. What if the user really wants to give up and just force stop the container? Do we a separate action capable of "interrupting" this action? This will not be very easy to implement.

**Comment by prachidamle** [comment]
If we want to show the container in "Waiting for connections to drain", seems like that would be like introducing a new state for containers?

**Comment by prachidamle** [comment]
@cjellick to answer one of your question:

"Is this coming from a specific customer or user because I'd like a more specific scenario described that this is meant to address. Are they talking about persistent http connections or long lived websocket connections or something else all together? The design seems reasonable, but I think without more specific success criteria, we could end up implementing the wrong thing."

The following ticket is the parent ticket logged:
https://github.com/rancher/rancher/issues/2777

However, what we are trying to address is a very portion of the issue, specific comments on this ticket:
https://github.com/rancher/rancher/issues/2777#issuecomment-243516883
https://github.com/rancher/rancher/issues/2777#issuecomment-246734094

People are seeing that they hit 503's on service upgrades, which we assume that might be due to above issue. BUT afai-understand, implementing the above may not be the ONLY solution to this problem.

**Comment by pulberg** [comment]
As a user, 1 very important thing to me is "scale down".  After I have an event of any kind that required scaling up a stack, how do I then scale down without affecting current usage?  I could def use a "smart" scale down feature.

**Comment by vincent99** [comment]
Draining would include stopping containers for scale down... Dio you mean something else by "smart" @pullberg?

**Comment by pulberg** [comment]
@vincent99 Draining would satisfy the scale down requirement.  The "smart" part would be things like:

 - displaying how many of the given stack had a current connection
 - letting the user decide to scale down only containers without connections
 - letting the user choose how many to drain concurrently

I have previously done this kind of thing in the bare metal/vm world through whatever type of LB we had in the DC (Citrix NetScaler, F5 LTM). The process i'm used to is called "quiesce" - 

https://devcentral.f5.com/articles/f5-friday-gracefully-scaling-down

https://docs.citrix.com/en-us/netscaler/10-1/ns-tmg-wrapper-10-con/ns-lb-wrapper-con-10/ns-lb-clienttraffic-con/ns-lb-clienttraffic-gracefulshutdown-tsk.html

**Comment by cjellick** [comment]
@vincent99 pointed out: there is a separate concern of draining the LBs themselves whilst upgrading the LB service itself. I think we can accomplish this by adding an additional flag to the event that informs the lb-controller that it is putting the entire lb into drain mode. We might then just set *all* backends to weight=0 and wait for them all to reach zero.
