### ISSUE TITLE
During service upgrade with start before stop , metadata for service does not have info about the older instances of the service when upgraded instance is in error state

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8684]
Rancher Versions: v1.6.0-rc5
Steps to reproduce the problem:
Create a service  - "test1" with scale 1.
Create a LB service with target service "test1".

Upgrade service - "test1" with "start before stop" option and choose an invalid image while upgrading so that the new container always fails to start (Starting -> Error -> getting removed and recreated).

When "test1" is in "upgrading" state , the older container instance is in "running" state which as expected but Lb service gets a "503 Service Unavailable" since there is no backend targets associated with it anymore.

service  metadata has empty container list.
Also DNS look up for this service name that is "upgrading" state fails.

```
root@68807de002c2:/# dig test1 +short
root@68807de002c2:/# curl http://rancher-metadata/latest/services/test1/containers
root@68807de002c2:/#
 ```

**Comment by martinbaillie** [comment]
This sounds similar to what I am seeing in 1.4.1 but happens irrespective of error state.

For zero downtime deployments, testing with a `batch-size=1`, an `upgrade_strategy: start_first: true` and using an accurate health check works fine when there’s a scale of 2 or more for the service. 

However, with a scale of 1, from a metadata-service perspective, Rancher appears to swap the new initialising container for the old (still running container). That is, instead of there being temporarily 2 containers (with one in initialising state) in the metadata-service’s `/latest/services/<service>/containers` response, there is just 1 - the new, still-initialising one.

From a UI perspective things look ideal: two containers, old still running, new in initialising state, old not swapped til new becomes active. Metadata's view of the world does not reflect this though, and that's what I'm using to write my ingress LB config (Traefik fork).

**Comment by prachidamle** [comment]
This can be seen also when the new upgraded instance happens to take a long time to come to "running" state.

**Comment by cjellick** [comment]
We are going to fix this by changing the behavior in the existing version of metadata. We are going to cause it to stop ignoring upgrading containers so that both the stopping and new containers show up and can be configured as backeends.

**Comment by prachidamle** [comment]
The same PR has been tested with 1.6 setup as well, and can be cherry-picked to 1.6 as-is.

**Comment by cjellick** [comment]
@prachidamle we are going to need some sort of validation test to at least nominally test this. Please work with QA on that. I don't care if you or qa writes the test, but I don't want this issue to get out of the testing pipeline until theres a new automated test for it.

**Comment by cjellick** [comment]
@soumyalj feel free to reassign to another QA; just wanted to have someone assigned to it

**Comment by soumyalj** [comment]
Tested with master 1.6 branch and 1.6.3-rc1. 
1. Created service test and lb pointing to this service
2. Upgraded service with start before stop option set
3. During upgrading state, Lb could reach its targets on the specified port.
4. dig and service metadata are below:
```
root@07343350fb07:/# dig test +short
10.42.241.100
root@07343350fb07:/# curl http://rancher-metadata/latest/services/test/container
s
0=test-test-1
```

**Comment by sangeethah** [comment]
Automation test - https://github.com/rancher/validation-tests/pull/332
