### ISSUE TITLE
[rancher-compose] Use same storage for creditials like rancher-cli

### ISSUE THREAD

**Issue by iBobik** [rancher/rancher#8690]
Currently compose can be configurable only by environment variables and parameters. Will be much simpler to use if user will not take care of it because it can use existing config file created by `rancher config`, so user will just select environment (if default is not enough).

**Comment by cjellick** [comment]
`rancher-compose` is slowly being replaced by the`rancher` cli. I suggest using `rancher` instead of `rancher-compose`. It will have the focus of our development. It should be capable of doing anything that you were doing with `rancher-compose`.

Feel free to reopen if this doesnt fully address you're needs.

**Comment by iBobik** [comment]
Great!

Will be nice to write it somewhere visible on presentation pages about Rancher Compose.


Honza Pobořil
https://honza.poboril.cz
