### ISSUE TITLE
 DigitalOcean DNS - function "service_name" not defined

### ISSUE THREAD

**Issue by dominicporteous** [rancher/rancher#8697]
When spinning up DigitalOcean DNS, the following error occurs;

Error (template: template:21: function "service_name" not defined)  

Service never starts. Have tried with different DO accounts, and multiple different API tokens on the accounts.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0-rc5` Cattle: `v0.179.5` UI: `v1.6.1` |
|Access|`github` |
|Orchestration|`Cattle`|
|Route|`stack.code`|

**Comment by dominicporteous** [comment]
Just tried same with AWS Route53 - same error.

Issue with the template file?

**Comment by aemneina** [comment]
@dominicporteous do you have something defined in DNS Name Template? looks like service_name is a missing  parameter that isnt being passed in.

**Comment by deniseschannon** [comment]
@dominicporteous when you run a RC, you get a custom catalog branch that doesn't necessary have all the up to date templates that will work. with this specific issue, there are `{{` in the rancher-compose.yml files for the catalog templates using external-dns. 

I've merged in a PR into our community-catalog that should fix digitalocean-dns for you, but to get a working route53 one, you will need to have your Rancher catalog pointed to the master branch instead of the custom v1.6.0-rc5 branch. 

Please try again as this should be fixed.

**Comment by dominicporteous** [comment]
Thanks a bunch!
