### ISSUE TITLE
Public DNS Improvements

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8704]
#### Functional
Users must be able to expose their services via publicly accessible domain names

### Technical
This has several components:
1. The public dns service that will act as a wrapper around the DNS provider we choose (ie route53)
2. The external-dns provider that is deployed in a user's environment that talks to our public dns service

Both are somewhat complete, but haven't but they haven't been validated or really tested at all. @ibuildthecloud wants to get this up and running so that we can test out its functionality and figure out the gaps from both a user and technical perspective.

So, the deliverable for this issue *is not* complete and ready-to-ship dns solution. The deliverables are:
1. The merging of all public dns and external dns PRs so that they code can be integrated.
2. Basic validation tests exercising the basic use case for this feature
3. The ability to easily stand-up the two components (public dns service and external dns with the proper provider) so that others can stand it up to test it out.

**Comment by prachidamle** [comment]
The public dns usecase diagram:
<img width="936" alt="screen shot 2017-05-18 at 3 37 30 pm" src="https://cloud.githubusercontent.com/assets/1470602/26226837/76ec0648-3be3-11e7-8936-63df2d3d6295.png">

**Comment by prachidamle** [comment]
Following are the links to the deliverables of this issue:

1) The merging of all public dns and external dns PRs so that they code can be integrated.
- Following is list of PRs generated/updated after testing end-to-end:

  - go-rancher
    - https://github.com/rancher/go-rancher/pull/152

  - public-dns-client
    - https://github.com/rancher/public-dns-client/pull/4

  - rancher-public-dns service:
    - https://github.com/rancherlabs/rancher-public-dns/pull/2

  - external-dns provider
    - https://github.com/rancher/external-dns/pull/81

  - catalog item
    - https://github.com/prachidamle/my-rancher-catalog/tree/master/templates/public-dns

2) Basic validation tests exercising the basic use case for this feature

- An integration test has been added to test the usecase end-to-end here:
https://github.com/prachidamle/rancher-public-dns/blob/public-dns-story/tests/integration_test.go

3) The ability to easily stand-up the two components (public dns service and external dns with the proper provider) so that others can stand it up to test it out.

- README for rancher-public-dns service updated: https://github.com/prachidamle/rancher-public-dns/blob/public-dns-story/README.md
- README for the external-dns catalog item: https://github.com/prachidamle/my-rancher-catalog/blob/master/templates/public-dns/0/README.md
- WIKI for the basic use-case: 
https://github.com/prachidamle/rancher-public-dns/wiki/How-to-create-DNS-records-for-Rancher-services-on-Rancher's-hosted-zone

**Comment by prachidamle** [comment]
@cjellick please review above comment, it would be good to merge the above PRs for go-rancher, public-dns-client, rancher-public-dns service, so the step2 improvements can be made on top of these changes.

external-dns provider and catalog item can be updated later.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
