### ISSUE TITLE
Support Azure as a cloud provider for kubernetes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8721]

**Comment by doprdele** [comment]
any idea if this will happen?

**Comment by joshwget** [comment]
Setting up the Azure cloud provider (without using ACS) seems more difficult than with other clouds. It's more likely that we'll support the ability to import an existing ACS-managed cluster into Rancher.

What functionality are you primarily looking for? Using Azure persistent volumes?

**Comment by doprdele** [comment]
The only functionality I’d really like is to be able to use the Azure LB from Kubernetes and eventually kubernetes cluster-autoscaler, which works currently on AWS.

On Mon, Aug 7, 2017 at 2:13 PM, Josh Curl <notifications@github.com> wrote:
Setting up the Azure cloud provider (without using ACS) seems more difficult than with other clouds. It's more likely that we'll support the ability to import an existing ACS-managed cluster into Rancher.

What functionality are you primarily looking for? Using Azure persistent volumes?

**Comment by janeczku** [comment]
As part of the implementation, support for CIFS mounts should be added to the kubelet image in order to support Azure File persistent volumes.

**Comment by moelsayed** [comment]
https://github.com/rancher/kubernetes-package/pull/106
https://github.com/rancher/rancher-catalog/pull/971

**Comment by moelsayed** [comment]
Tested functionality:
- Azure-files
- Azure dedicated blob disks
- Azure shared blob disks
- Azure load balancers

Issues:
- There are some random timeouts with the Azure load balancer. Seems related to configuration on Azure side. Still looking into it.

**Comment by galal-hussein** [comment]
Rancher server: v1.6.11-rc4
Tested the following functionalities:

- Azure-files
- Azure dedicated blob disks
- Azure shared blob disks
- Azure load balancers

Found one problem with load balancer where it only passes request to one server, after investigating the problem we found that controller manager opens certain ports that are specified in the load balancer configuration in the node's security group, however since security group is one of variables that are being fetched by controller manager from the Azure API then the only security group that is being modified is where the controller manager resides:
```
root@5bfd35bf7267:/# cat /etc/kubernetes/cloud-provider-config
aadClientId: 54d17b5f-0d07-41a9-8744-c6f5846826ce
aadClientSecret: eFo+8b8VRg7filZyR6ciQkrs+PZFTg+V0oAPW1t72IQ=
tenantId: abb5adde-bee8-4821-8b03-e63efdc7701c
subscriptionId: 14a619f7-a887-4635-8647-d8f46f92eaac
cloud: AzurePublicCloud
location: westus
resourceGroup: docker-machine
subnetName: docker-machine
vnetName: docker-machine-vnet
securityGroupName: hgalal-srv1-firewall
```
Since docker machine doesn't support specifying security group name when creating servers, then security group names should be passed to controller manager as a variable.

CC @moelsayed @alena1108

**Comment by galal-hussein** [comment]
Rancher server: v1.6.11-rc5
I was able to validate Azure load balancer by specifying the security group name when trying to deploy kubernetes, the load balancer distributed the requests between all hosts correctly.
