### ISSUE TITLE
Container scoped volumes can lose data in 1.6

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8755]
Related to #7271, but specific to 1.6, since it relies on a different backend.

**Comment by deniseschannon** [comment]
@sangeethah 

Can we test #7271 and #8683?

**Comment by sangeethah** [comment]
Tested with rancher-server build from master:

Create a stack with service using container scoped volume.
Write some data to this volume.
Upgrade this service by passing an invalid image so that that service upgrade fails.
Rollback upgrade.
Once the service rollback is successful , the service container has a new volume attached to it and the data that was written to the volume is not present any more.

The original container scoped volume is still present but is in detached state.

**Comment by sangeethah** [comment]
Other scenarios with per-container scoped volumes that have issues:

Scenario1:

Deploy health check enabled services with per-container scoped volumes.
Write some data to this volume.
Power down the host on which this instances of the service is running.
Wait for the container to get migrated to a different host.
After the container got migrated , it was attached to the existing volume as expected. I was able to read the existing data from this volume.
Write more data to this volume.

Power down host where this container is running.
When the container migrated to a different host , this time it got attached to a new volume instead of the existing volume.

Existing volume does not get deleted but remains in detached state now.

```
root@san-nfs1:/var/nfs# ls -ltr  mynewtest_contest1_1_dc82a1a1-aed7-4d89-b85f-6fe72546e9df_3b9c9
total 8
-rw-r--r-- 1 nobody nogroup 4 May 17 22:59 pp1
-rw-r--r-- 1 nobody nogroup 4 May 17 23:04 pp2
root@san-nfs1:/var/nfs# ls -ltr  mynewtest_contest1_1_7416b1cb-1147-40c0-b3f3-7c1719acf385_c9d82
total 0
root@san-nfs1:/var/nfs# 
```

Scenario2:
Stack has 2 services -
"health" with container scoped volume-con1 
"healthnew" with container scoped  volume-con1

Deactivated and deleted host on which health-2 and healthnew-2 instances of the services where running.

When new instances of health-2 and healthnew-2 got recreated in a different host , both health-2 and healthnew-2 now attached to the container-scoped volume of  healthnew-2 instance.

Scenario 3:

Earlier when we used to scale down instances with container scoped volumes , volume associated with the scaled down instance will get deleted. But now I don't see the volumes being deleted. 
Deploy service with per-container scoped volumes and scale 2.
On the second instance of the service , write some data to the volume.
Scale down service to 1.
As part of scaling down , when second instance of the service gets deleted , volume associated with this container is still present.
Scale up service to 2.
When a new service instance gets created , it ends up using the volume that was associated with the scaled down instance.

**Comment by sangeethah** [comment]
Tested the following scenarios on build from master and they all work as expected:

Scenario 1:
Create a stack with service using container scoped volume.
Write some data to this volume.
Upgrade this service by passing an invalid image so that that service upgrade fails.
Rollback upgrade.
Once the service rollback is successful , the service container have the original volumes attached to it. We have access to the data that was written previously for these volumes.

Scenario 2:
Deploy health check enabled services with per-container scoped volumes.
Write some data to this volume.
Power down the host on which this instances of the service is running.
Wait for the container to get migrated to a different host.
After the container got migrated , it was attached to the existing volume as expected. I was able to read the existing data from this volume.

Scenario 3:
Stack has 2 services -
"health" with container scoped volume-con1
"healthnew" with container scoped volume-con1

Deactivated and deleted host on which health-2 and healthnew-2 instances of the services where running.

When new instances of health-2 and healthnew-2 got recreated in a different host , both health-2 and healthnew-2 were attached to the appropriate volumes as expected.

**Comment by sangeethah** [comment]
There is one change in behavior w.r.to when container scoped volumes get deleted . In case of scaling down service instances, We will not be deleting volumes and so when we scale up services again , the new service instances will end up reusing the existing volumes in this case . 
Container scoped volumes will get deleted only when the stack the service belongs to gets deleted .

On stack creation , some of the container scoped volumes get deleted from the rancher-server side , but continue to the present in the storage server . This is a known issue that could happen more often with stack deletion involving lot of container scoped volumes  - https://github.com/rancher/rancher/issues/8498

**Comment by sangeethah** [comment]
agent logs and nfs driver logs - 
[nfslogs.zip](https://github.com/rancher/rancher/files/1012794/nfslogs.zip)

**Comment by deniseschannon** [comment]
@sangeethah Did we cover this use case? https://github.com/rancher/rancher/issues/8683

**Comment by sangeethah** [comment]
@deniseschannon yes. That is the scenario mentioned in scenario1 where upgrade fails and you rollback upgrade.
