### ISSUE TITLE
Catalog repository structure

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#8773]
Is there any documentation regarding the design decision(s) for the catalog repositories?
I've read the documentation and have my private catalog up and running, but it feels really cumbersome.

I'd love an approach more like composer uses (packagist.org) where:
1. I can register 1 git repository for a specific catalog entry.
2. Can use tags for new releases (so I'm actually using GIT for versioning instead of using it as a glorified file repository).
3. A catalog server could then use git hooks to update its index of catalog entries; each repo would contain a configuration file for the catalog entry `config.yml` and the `docker-compose` / `rancher-compose` files needed.

Note that something like this can already be done, the catalog server would then expose the catalog via a git repository that has the structure rancher requires, but this leaves some things open:
1. What do the folder numbers mean? 
Suppose I release: `1.0.0` (in folder `0`)
Then I release `2.0.0` (in folder `1`)
Then I release `1.0.1`, this is a bug fix for a supported major version, but what folder should I use?

2. Template folders. It seems there is a separate folder per orchestration method, but it is already inconsistent:
- Infra-templates (infrastructure is not an orchestration method)
- Templates (cattle-templates)
- Mesos-templates (mesos-templates)

And then inside `config.yml` for an infrastructure template I find `io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'`. 
So if we have this why do we need the directory as well?

3. Redundant / unclear configuration
- `config.yml` contains a name for the catalog entry, but so does `0/rancher-compose.yml`

4. No guidance on category names (this could be a valid choice), for example I see the categories `Database` as well as `Databases`. If rancher keeps on growing and templates / catalogs do as well, it makes sense to use a label system so we can search for multiple categories.

5. Uuid in `rancher-compose.yml`

> The uuid is a required parameter that is used for upgrade scenarios. Each uuid must be unique and each later version should be incremental. The recommended format is to use the name of the catalog entry and suffixed with a -0. As versions are introduced, you would increment the -0 to -1 for the next entry.

That is not a `uuid`, that is a counter. What does incremental mean in the context of strings? Does it mean the sort order needs to be strictly incremental, does it mean the difference between version 1 and 2 should be the same as between 2 and 3? What is the allowed character set, YAML supports unicode characters, but their sort order is not defined unless using a specific collation.

An alternative proposal would be to try and copy something that other dependency managers already do.
1. Instead of `rancher-minimum-version`, have a `requires` key where we can specify specifically what we need. (Including but not limited to the rancher version)
2. A repository would contain just the files for 1 catalog entry, this would then be cataloged automatically and become the new "community catalog".

Example `config.yml`:
````
name: Drone Rancher Node Manager
description: |
  (Experimental) Dynamically add remove Drone worker nodes
category: Continuous Integration
orchestration:
  - mesos
  - swarm

requires:
  rancher/rancher: ">= 0.56.0 < 1.0.0",
  self: ">= 1.0.0" # Not sure if this is better than having upgrade_from
  
````

The catalog server would then just get all tags (which signify versions) and create a file for consumption by rancher.

**Comment by deniseschannon** [comment]
@SamMousa Thanks for such detailed report. We don't have a detailed doc regarding design decisions, but we are in the process of updating the format to make it more intuitive. 
 
> What do the folder numbers mean?

At this point, folder numbers have no relevancy to version numbers, which is the current problem. We are adding in support to be able to put version as the folder name and have our catalog-service read from there. This would allow you to remove the `version` from the rancher-compose.yml. 

> Suppose I release: 1.0.0 (in folder 0)
Then I release 2.0.0 (in folder 1)
Then I release 1.0.1, this is a bug fix for a supported major version, but what folder should I use?

In Rancher, we would just use the next folder number (i.e. folder 2), which we know is not intuitive and this is why we are looking to change to folder names as versions. 

> Template folders. It seems there is a separate folder per orchestration method, but it is already inconsistent:

As Rancher has evolved, we've maintained the same Rancher catalog repo so the folder names for where the templates are have been the same since inception. At some point, we had thought of using a new catalog (infra-catalog) for what is now in the `infra-templates` folder, but maintaining multiple git repos was not the direction we wanted to go in. 

> And then inside config.yml for an infrastructure template I find io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'.
So if we have this why do we need the directory as well?

The label in the config.yml allows the UI to pick out which infra templates are available based on selected orchestration when creating/editing environment templates. If an orchestration is selected that doesn't have support for that infra template, it's hidden from the list of available choices.

> Redundant / unclear configuration
config.yml contains a name for the catalog entry, but so does 0/rancher-compose.yml

If someone forgot to put a `name` in the config.yml, I believe we would pick it up from the rancher-compose.yml, but I would need to check with the UI team. 

> No guidance on category names (this could be a valid choice), for example I see the categories Database as well as Databases. If rancher keeps on growing and templates / catalogs do as well, it makes sense to use a label system so we can search for multiple categories.

I'll be the first to admit that I think we struggle to keep up with the community catalog updates and being diligent in maintaining consistency across the board on something like this. We typically focus on the docker-compose.yml than these actual details.  I'd have to contemplate on how this could be done. Maybe something could be added into the README on available categories?

> Uuid in rancher-compose.yml

This is actually no longer used anywhere. I believed we stopped using it as of Rancher 1.2 and is reflected in the docs. 

We are looking to simplify the catalog a bit with this issue to make it easier to maintain. One of the issues we have with changing catalog-service, which is what deals with catalogs,  is that no matter what we will need to maintain backwards compatibility for users who have the old catalog structure. 

https://github.com/rancher/rancher/issues/8319

**Comment by SamMousa** [comment]
@deniseschannon Thanks for the detailed response.

I think you're overestimating the effort of managing multiple git repos; from a user perspective this makes way more sense than having to create multiple catalogs or putting unrelated `docker-compose` files in the same repo.

Of course backwards compatibility is always an issue, but it's even more of a reason to consider carefully whether to add features to an unstable foundation... 
I'd imagine most changes from the current format to a new format could be done automatically and I'd rather break backwards compatibility sooner than later.

The advantage of a central repo is also that it gives you more control without removing any control for your users. Please check out the approach composer / packagist use.

I'm not sure the changes proposed in #8319 make the catalog easier to use; they just make it even more clear in my opinion.
I'll provide some feedback there as well...

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
