### ISSUE TITLE
Validate Rancher Garbage Collection Manager

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8789]
Test Plan containing P1 workflow for Rancher Garbage Collection Manager - 
[ImageGCTests.xlsx](https://github.com/rancher/rancher/files/1008937/ImageGCTests.xlsx)

**Comment by StrongMonkey** [comment]
LGTM

**Comment by StrongMonkey** [comment]
`Image clean up for images used by containers that are flapping  when IMAGE_GC_HIGH_THRESHOLD  is reached` won't work. Current solution only guarantees that the image will be deleted at last. Because it is flapping, there is still possible that the image is not used by container and it is also detected by GC at the same time.

**Comment by sangeethah** [comment]
Added 2 more cases relating to docker being installed in mounted volumes ( Test case # 13 and 14)

[ImageGCTests.xlsx](https://github.com/rancher/rancher/files/1011697/ImageGCTests.xlsx)

**Comment by StrongMonkey** [comment]
```7. Delete service S1 . Wait for 2 mts. Delete Service S2.  Wait for 2 mts. Delete service S3 . Wait for 2 mts. Delete Service S4.```
you may need to wait longer between deleting images. The default routine interval is 5 minutes. So the images are scanned every 5 minutes by default.

**Comment by StrongMonkey** [comment]
Initial validation was done. 2 issues:
1. https://github.com/rancher/rancher/issues/8802
2. https://github.com/rancher/rancher/issues/8828
