### ISSUE TITLE
Implement public dns MVP

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8790]
Based off of review of current public dns, here are the requirements for the MVP:

- Support standalone containers
  - Might require coding against wagyu branch.
  - Should follow same naming convention as services but use container name instead of service name. 
- Change FQDN format to: `myservice-6s3ifh.38r73f.a.foo.com` `(service)-(stack random).(env random).(shard in the future).(TLD)`
  - `stack random`  should be derived from stack uuid. `env random` should be derived from environment uuid
- Work with @cloudnautique to ensure it is deployable in the new environment
  - Create a private catalog to deploy this in the new environment. Will need to work with @cloudnautique to ensure we are setting up keys properly
  - Use a non-rancher domain ( @cloudnautique )
  - Obtain 1 hosted zone to start. WIll need to be configured as part of deployment scripts

Other requirements that came up but are not in scope for MVP:
- Support sharding
  - Administrative UI for managing shards and hosted zones (if we switch from route53, we should make sure this solution works there too)
- Research moving to a different dns provider. Analysis should include the cost and the sharding requirements (ie right now route53 caps a hosted zone at 10k entries)
- Add Rancher installation ID as a a column in the DB that is recorded for each entry so that we can identify where requests are coming from
- Implement garbage collection
  - Periodically check for entries from installations that have not been touched/updated in some configurable amount of time

**Comment by vincent99** [comment]
- Add validation for container/service in Cattle to ensure the name in the stack is unique.  Currently a service `foo` and a standalone container named `foo` can both exist, hilarity will ensue.
- Change service name length limit to 50 chars in Cattle.
- If external-dns driver sees a name >50 chars, log an error and ignore the record (to handle existing records that may exceed).
- If external-dns sees more than one record with the same (name, stack, env) tuple, log an error and ignore the record (again to handle possible existing data)
- (Just a note) The reason for the naming being `service-stack.env.[tld]` is so that a single wildcard cert can cover anything in the environment later.
- I'd like to see moderate load testing to ensure this isn't going to immediately hit some unknown AWS rate limit and blow up in our face.

**Comment by cjellick** [comment]
> Add validation for container/service in Cattle to ensure the name in the stack is unique. Currently a service foo and a standalone container named foo can both exist, hilarity will ensue.
How does backpopulation affect this?

**Comment by cjellick** [comment]
@vincent99  Will the first deployment have an actual shard component to the fqdn or is the lack of a shard component the first shard?

**Comment by cjellick** [comment]
Need to circle back on how we are generating the radom bits based off of uuids

**Comment by prachidamle** [comment]
@cjellick  @vincent99 About generating stack and env random: 
Should we use a random number generator ("github.com/moby/moby/pkg/random") and pick a fixed number of characters from stack/env uuid using a random index generated?
 stack_uuid[random.Rand.Intn(len(stack_uuid))] picks a character randomly from the stack_uuid

**Comment by prachidamle** [comment]
Break-down of tasks per component:

- rancher-public-dns Service
  - Might require coding against wagyu branch.
  - Change current API POST /v1-rancher-dns/rootdomaininfo {external-dns service token} 
  - Remove the code to generate the uuid of form (random adjective- random noun)
  - API should take in the env_uuid along with the token and return a root domain of format (env-random).(shard in the future).(TLD)
  - Changes to db to add a columns to store (token, env-uuid, env-random)
  - Changes to Connect to amazon route53 using IAM profile instead of keys
  - Generate new public-dns-client for changes in API

- external-dns provider
  - Read env-uuid along with the metadata/self/service/token and pass to POST /v1-rancher-dns/rootdomaininfo
  - Implement fixed FQDN format (do not expose FQDN format in catalog as a parameter):  (service/container name)-(stack random).(root domain returned by above POST API
  - Look at standalone containers in metadata along with service containers and CRUD dns records for these containers as well. 
  - Figure out how to differentiate the standalone containers from the containers that are part of service [check if some field in metadata distinguishes them]. Add dns records for these containers as well.
  - Find out what labels should be put by cattle on standalone containers so that external-dns picks them up (ref: services with exposed ports only are picked up by external-dns since they have a system label on them “io.rancher.service.external_dns”)
  - Implement checks: 
    - If external-dns driver sees a service/container name >50 chars, log an error and ignore the record (to handle existing records that may exceed).
    - If external-dns sees more than one record with the same (name, stack, env) tuple, log an error and ignore the record (again to handle possible existing data)
  - Since looking at services in metadata is common code for all external-dns providers, will we be supporting the stand-alone container dans record generation for all current providers? Or do we do this change only for rancher-public-dans provider?

- cattle:
  - Place labels needed by external-dns on standalone container having exposed ports
  - Add a field FQDN to instance table 
  - Change the external-dns event handling to populate the FQDN for standalone containers as well
  - Add validation for container/service in Cattle to ensure the name in the stack is unique. Currently a service foo and a standalone container named foo can both exist. {follow-up on container back population and k8s service back population}
  - Change service name length limit to 50 chars in Cattle.

- catalog:
  - Create a catalog item in a private catalog for external-dns provider

- Tests:
  - Validation tests for service and stand-alone containers
  - Load tests

**Comment by prachidamle** [comment]
external-dns change to look for standalone containers in metadata along with service containers and CRUD dns records for these containers as well:

- Loop over metadata.GetContainers(), for containers that have:
  - If service_name is "" && service_index is "", but stack_name and stack_uuid is set [then this is a standalone container], then check:
     - has "running" State and "healthy"/"updating-healthy"/"" HealthState
     - If has (label "io.rancher.service.external_dns" = "auto" (default value is "auto") and ports exposed) ||  (label "io.rancher.service.external_dns" == "always"), then:
        - Check for Host Label: io.rancher.host.external_dns  = true
        - DNS IP = "io.rancher.host.external_dns_ip" OR container.Ports.IP OR host.AgentIP
        - form the FQDN by (container_name)-(stack random).(rootDomain)
        - add DNS record

**Comment by prachidamle** [comment]
How to generate the FQDN:  (service)-(stack random).(env random).(shard in the future).(TLD)
Example: myservice-6s3ifh.38r73f.a.foo.com 

Part:  (shard in the future).(TLD)
Component Involved: rancher-public-dns service
Specs:
- (TLD) 
  - is the Rancher's hosted zone domain on AWS route53. Provided to the rancher-public-dns service via ENV variables/ command parameter.
- (shard in the future)
  - ENV variable to rancher-public-dns service 
  - Start with no shard? OR use a shard value as "a" to denote the first shard?


Part:  (env random)
Component Involved: external-dns provider, rancher-public-dns service
Specs:

- external-dns Provider:
  - Read the self "token" from metadata - will uniquely identify the environment the provider is launched for. Call rancher-public-dns to generate a root domain for the token.
  - will store this {token, (env-random)} to file and use for auth for subsequent rancher-public-dns API calls 
- rancher-public-dns Service
  - Use the current API POST /v1-rancher-dns/rootdomaininfo {external-dns service "token" from metadata} 
  - Remove the current code to generate the uuid of the form (random adjective- random noun)
  - API should _generate a random 6 char string_ for (env-random)  and return a root domain of format (env-random).(shard in the future).(TLD)
  - Store (token, env-random) mapping in rancher-public-dns DB and use "unique" constraint over env-random
  - Should we also store the env_uuid in the DB along with this "token", for information purpose only? 


Part: (service)-(stack random)
Component Involved: external-dns provider
Specs:
- external-dns Provider:
  - From metadata, for each service/standalone container with exposed port:
    - _Generate the (stack random) from stack_uuid - 6 chars [Need to always return the same random for a give uuid ] Any recommendations for this algorithm?_
    - Truncate the service/container name such that (service)-(stack random) <= 63 chars
    -  Program this FQDN { (service)-(stack random).(rootDomain) } via rancher-public-dns on aws route53. 
    - Here (rootDomain) = (env random).(shard in the future).(TLD) returned by rancher-public-dns on the provider init.

- Cattle: (requirements added From Vince)
  - Limit container/service name to 50 chars
  - Add validation for container/service in Cattle to ensure the name in the stack is unique. [Currently a service foo and a standalone container named foo can both exist in same stack.]
  - How will back population affect the name unique requirement?

**Comment by prachidamle** [comment]
Container names will have to be valid DNS names. 

- 1-50 characters long (it can be 63 but we will limit to 50 to avoid truncation while creating fqdn)
- Consisting only of A-Z, 0-9, and hyphen
- Can't start of end with a hyphen
- Can't contain 2 consecutive hyphens


About not having "underscore" in container names:
from @vincent99
Underscore is weird; it's not allowed by the DNS spec (for the kind of records we're creating), but it works fine in most, but not all places.  There are a few common clients (like one of the monitoring apps, not sure which) that have problems with them
Some DNS tools care a lot about it.  According to issues: Datadog, Webspehere, Solr, ActiveMQ, Gluster, Hadoop, Netflix Zuul.  Most of those are no longer an issue because service containers are named stack-service-num instead of using underscore like we used to, but Datadog looks at *all* the things on the host

So Darren and I think underscore shouldn't be allowed on container, and the agent should substitute them when back-populating containers

**Comment by prachidamle** [comment]
For this issue to be fixed, we also need to take care of:
https://github.com/rancher/rancher/issues/9180

**Comment by prachidamle** [comment]
The PRs on this ticket are marked WIP just to indicate they depend on cattle:master code and not applicable to 1.6.x

**Comment by cjellick** [comment]
We are not going to do this for 1.6
