### ISSUE TITLE
Rancher CLI v0.6.0 is not honoring parameters set in docker-compose.yml

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#8798]
**Rancher versions:**

- rancher/server: 1.6.0
- rancher/agent: 1.2.2

**Docker version: (`docker version`,`docker info` preferred)**

- 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.03"
PRETTY_NAME="Amazon Linux AMI 2017.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Problem** 
On OS X, Rancher CLI v0.6.0 is not honoring parameters set in `docker-compose.yml`. It keeps on asking questions already answered as environment variables.

**Steps to Reproduce:**
Download two binaries of the above versions and test it on OSX (I am on 10.11.2)
These are my yaml files.
[docker-compose.yml.txt](https://github.com/rancher/rancher/files/1010997/docker-compose.yml.txt)
[rancher-compose.yml.txt](https://github.com/rancher/rancher/files/1010996/rancher-compose.yml.txt)

**Results:**
```
/usr/local/bin/rancher_v0.6.0 --url https://<rancher-master> --access-key <access_key> --secret-key <secret_key> --env <env> up --force-upgrade --confirm-upgrade -s <name_of_stack> -d
Automatically create registry in Rancher for corresponding ECR repo if it doesn't already exist
Auto Create auto_create[false]:
```

Same command runs perfectly fine on older version i.e. v0.5.2
```
/usr/local/bin/rancher_v0.5.2 --url https://<rancher-master> --access-key <access_key> --secret-key <secret_key> --env <env> up --force-upgrade --confirm-upgrade -s <name_of_stack> -d
```

**Comment by cjellick** [comment]
This was an intentional change in behavior added in this PR: https://github.com/rancher/rancher-compose-executor/pull/37 (specifically the "Ask questions up front" commit).

We had to make this change to accommodate a new templating feature in compose files. We used to be able to ask questions lazily as their values were used. Unfortunately, with the addition of templating, we have to ask the questions up front.

So, at the root of your problem is that the questions in rancher-compose are unused in docker-compose. At least, that's what I' m seeing in the files you provided. Is it possible to drop the questions from the rancher-compose file if they are unused?

I'm not sure that it would impact you directly, but it would be a good enhancement for us to at least look at the `env-file` for variables that would satisfy questions and omit those qusetions.

**Comment by vikas027** [comment]
Hey @cjellick,

It would be good to have those questions answered thru an `env-file` or something similar.

Some feedback - I know Rancher CLI is in beta but still it is good to have a deprecated warning before chucking out the functionality :) 

Just noticed other problem with Rancher CLI v0.6.0. It keeps on expecting a value, even if is not required (set to `false`). The only workaround, for now, is to remove all questions.
```
    - variable: "aws_access_key_id"
      label: "AWS Access Key ID"
      description: "AWS API Access Key to use for obtaining ECR credentials. Not required if using IAM roles."
      required: false
      type: "string"
```

**Comment by cjellick** [comment]
Thanks for the feedback @vikas027. I noted your observation about not-required questions in the above referenced issue that @joshwget is using to aggregate cli improvements.

And I'll ping @deniseschannon regarding the warning on functionality changes. Our general approach has been to note such things in the release notes. That seems like an appropriate place for now. Maybe this particular one got overlooked.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
