### ISSUE TITLE
Convert to flexvols for rancher storage drivers

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8826]
Add logic to the go-agent to recognize rancher storage drivers and call the storage driver directly as opposed to calling `docker volume` commands. In the end, we should be passing host bind mounts to the docker create command.

When the storage driver is not a rancher one, we should still fallback to `docker volume` commands.

**Comment by StrongMonkey** [comment]
Implementation Detail:
1. Call rancher socket directly to complete different volume operation. (Create, Attach, Mount, Detach, Unmount, Remove etc...). Bypass all the docker volume API calls.
2. Pass the mount point as bind mounts into container. May need to handle the mount and unmount during container start and stop.
3. Need a bit refactoring work to make code more readable and backwards-compatible with volume drivers which are still docker volume plugin.

**Comment by DonaldFoss** [comment]
@StrongMonkey - Alternately, couldn't one call docker socket to see if volume exists, create if necessary, then stick with Docker API. That should remove the need for extra logic for mount/unmount during container start/stop.

**Comment by StrongMonkey** [comment]
@DonaldFoss Thanks for you inputs. We are actually going to avoid any docker volume API call, and  dealing with mount and unmount wouldn't be a big effort in current rancher storage framework.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/storage/pull/58 + https://github.com/rancher/agent/pull/170 + https://github.com/rancher/cattle/pull/2729 are the PRs for the initial implementation.
This is the workflow(using nfs as an example):
1. Start a container with a rancher-nfs volume.(test-nfs:/data)
2. Agent call rancher storage driver to create the volume.
3. Agent call rancher storage driver to attach the volume.
4. Agent call rancher storage driver to mount the volume, which is a mountpoint on the host. Then pass this mountpoint as a host bind mount to the container.

At any point container fails to start, agent will unmount the mountpoint, which also detach the device if that is supported. Agent will also call unmount during container stop, but that will not trigger the gc method as long as the mountpoint is still active in rancher.

Since we pass bind mounts to container for these special volumes , we will need to parse these mount point in order to let cattle recognize them. https://github.com/rancher/cattle/pull/2729

Also in [gc method](https://github.com/rancher/storage/pull/58), we only unmount the volume if it is detached on the rancher side.

**Comment by StrongMonkey** [comment]
rancher/cattle#2906
rancher/agent#229
rancher/storage#58

**Comment by deniseschannon** [comment]
Test the following templates: EBS, NFS, Secrets and Secrets Bridge.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.15-rc3. 
EBS, NFS, Secrets and Secrets Bridge volume drivers use flex volumes.
Issues found when validating these volume drivers are tracked as separate issues.
