### ISSUE TITLE
Can still create two catalogs with same name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8892]
**Rancher versions:** master 5/25

**Steps to Reproduce:**
1.  Add a catalog through Manage Catalog (environment)
2. Then add a catalog with the same name through settings

**Results:**  Allows me to create both and now the global one doesn't show up anywhere.

**Comment by amy** [comment]
Update: The fix for this is more involved. Unable to replicate issue where if `Allows me to create both and now the global one doesn't show up anywhere.` Both environment and global catalog must be different for both to show up. If the same, UI will consolidate both catalogs. 

In the future, the goal is to `Change catalog and UI to submit global catalogs through the API (instead of manipulating settings directly) so it can do validation and reject a global catalog name if _any single_ environment is using that name`

**Comment by tfiduccia** [comment]
Version - v1.6.1-rc10
Verified fixed
