### ISSUE TITLE
Network Monitoring Service for IPSec

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8941]
As a Rancher User, I want to have a healthcheck enabled infrastructure service running in an environment which is constantly checking/monitoring:
- connectivity between ipsec router containers.
- various networking entries (arp/conntrack/TBD)

**Comment by wjimenez5271** [comment]
@leodotcloud this is an ask from a lot of users, so great to see work going towards this. I've been hacking on https://github.com/wjimenez5271/cowcheck to do node monitoring and was planning on adding some stuff to talk to its neighbors to assert ipsec connectivity. Maybe we can combine efforts?

**Comment by leodotcloud** [comment]
Sure @wjimenez5271 I will take a look at your repo.

**Comment by leodotcloud** [comment]
connectivity check between ipsec containers has been added: https://github.com/rancher/rancher/issues/10326

**Comment by schuylr** [comment]
@leodotcloud I would really like to be able to specify the timeout for these connectivity checkers, as I have IPSec holder containers constantly flapping on their health state between Unhealthy and Healthy.

This wouldn't be an issue if a new IPSec container doesn't fail to initialize due to the other unhealthy containers, thus making my new servers flap.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
