### ISSUE TITLE
timeouts with ldap connections result in corrupted threads in the connection pool

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8945]
hangups on the ldap connection result in corrupted threads in the connection pool

**Comment by mrajashree** [comment]
The default connection timeout for AD and OpenLdap is 1 second in cattle. It is not configurable via UI while setting up access control. 
The pr to port AD to auth-service includes changing this value to 10 seconds. So the porting to auth-service should fix this issue.

**Comment by cjellick** [comment]
@aemneina what do you mean by a "corrupted thread"?

**Comment by aemneina** [comment]
@prachidamle and I noticed random behavior when threads that were used authenticate ldap, took longer than the default 1 second timeout to respond, would end up unusable. Those threads that timed out were returned to the thread pool and would lead to intermittent issues when they were picked up from the thread pool to make ldap calls.

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by prachidamle** [comment]
The root-cause of what is mentioned in the above comment was that in the ldap java code, when connection timeout was hit, we were not closing the connection and returning it back to the connection pool. So corrupted connections got saved back to the pool.

This particular issue was fixed in this ticket: https://github.com/rancher/rancher/issues/8270

This ticket can hence be closed.
