### ISSUE TITLE
Evacuating host should not kill rancher.

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#8995]
**Rancher versions:**
rancher/server: 1.6.1
rancher/agent: 0.181.3

**Steps to Reproduce:**
Create an environment where the rancher-server host is a member. (So rancher-agent on the same host as rancher-server).
Evacuate a host that has the rancher-server running.

**Results:**
Rancher-server gets killed trouble follows.

**Expected:**
I'd expect rancher-server to not kill itself, ever, without big warnings.

**Comment by aemneina** [comment]
are there logs for this when rancher is on its way out?

**Comment by SamMousa** [comment]
I don't have them

**Comment by vincent99** [comment]
@aemneina what do you want a log of?  Evacuate deletes all non-system containers, and the server isn't a system container because it wasn't launched by the system.  So they want an exception to that.

Which is going to be hard to do reliably because you somehow need to know that this is A) a server container (the image could potentially be named anything) and B) *this* server container (running Rancher in Rancher is a thing).

**Comment by SamMousa** [comment]
Shouldnt it be relatively easy to detect if a container is the rancher
server? You can inspect the processes or just connect to the api endpoint
(you know the port) and get the server ID)

**Comment by vincent99** [comment]
You know the port the registration URL is for and they are not necessarily the same.  Then you need to check potentially every container on launch, and retry indefinitely because the server won't be up for many seconds.  Then all of it needs to be optional because it may be the desired behavior for HA & ASGs.  Iptables rules may not allow the agent to reach the container directly, etc...

**Comment by SamMousa** [comment]
Hoe about ignoring all non rancher containers? If rancher didn't launch it
why would it kill it. Alternatively allow the user to add a label that
exempts the container from being killed?

**Comment by binary64** [comment]
This bug just caught me out! Here's my solution:
on the master node, do docker stop <rancher/server>, then docker stop rancher-agent && docker rm rancher-agent, start server, delete the master host from inside the Rancher UI, now add a new agent to the master node. 
Before the above solution, the server kept shutting itself down

**Comment by cal97g** [comment]
Happened to me just. Pretty sure my rancher install is bricked? Need to reconfigure everything??

**Comment by aemneina** [comment]
I see now, I thought this was the rancher server dying by evacuating a host. Now I see that its a host it manages... that it is housed on. Change this to a feature request.

@cal97g if your db was housed within the rancher server container, you most likely lost your data and will need to redeploy. If you bind mounted the folder it should still exist on the host, and if you used an external db, just spin up a new container and point it to the external db.

**Comment by JohnDavidLarsen** [comment]
Yes a label to mark something as Infrastructure would be ideal. rancher-server could automatically assign itself such a label, correct?
Also another "fix" for someone with a broken server, stop the rancher-agent, start the rancher-server only , re-activate the host via the UI, start the agent.  
I'd suggest this go along with making sure infrastructure objects are started first, but that's a different issue.

**Comment by kwaio** [comment]
We circumvented the issue by having a dedicated machine for the rancher server not housing a rancher host.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
