### ISSUE TITLE
Route that returns latest version

### ISSUE THREAD

**Issue by amy** [rancher/rancher#8998]
When default version not available, return the latest template Version.

**Comment by vincent99** [comment]
It was more @ibuildthecloud but I think we need: 

A) a `defaultVersion` link on `template` for the `templateVersion` which matches the default.  So that the client did not have to decide which version to deploy 
  - If no default, or that one is not available to the given rancher version, then the newest compatible one (semver sorted versions). 
  - if there is no valid version, omit the link.

B) A similar `defaultUpgradeVersion` on `templateVersion` so the client does not have to decide which version to upgrade to. 
  - This should take into account the `upgradeFrom` of the versions and only offer ones that are valid from the version you are returning.
  - if the default version is a valid upgrade, return that. If not, return the newest valid semver sorted version. 
  - If there is no valid upgrade, omit the link.
