### ISSUE TITLE
Webhooks for hosts to start using host templates

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#9024]
With the introduction of host templates in 2.0, webhooks should start using them.

**Comment by carolynhu** [comment]
@deniseschannon @cjellick @mrajashree I've checked the webhook scale_host code, firstly there are a few bugs need to be fixed:
1. when adding hosts to hostScalingGroup, we should make sure the host need to be scaled matches all labels in hostSelector, not only one label
2. baseHostIndex being calculated in wrong way, it should be the last non-custom host, not when host.Driver != "" then baseHostIndex++
3. unnecessary update host.Name to be "" when host.Name != "" in "up" action, since we already set hostRaw["name"] = "" in later logic of the same code block
4. possibly invalid amount being set in "down" action, since when host.State in that four invalid states, the deleteCount may be already larger than amount, so we need add a checking if deleteCount >= amount then return directly

For adding hostTemplate support for scaling hosts, the changes can be:
1. adding a HostTemplateID field in driver_model ScaleHost struct
2. when ValidatePayload,  add the checking for config.HostTemplateID 
3. when adding valid hosts in hostScalingGroup, if config.HostTemplateID != "", we add those host with the expected HostTemplateID into hostScalingGroup, otherwise, keep the same logic for adding hosts with matched labels
4. in "up" action, update hostRaw["hostTemplateID"] = HostTemplateID if necessary.
Apart from the above changes, other logic should keep as it is. Let me know if it is ready to be implemented.

**Comment by vincent99** [comment]
For (the first) 1: There should be no looking at labels at all after converting to using hostTemplates.

**Comment by carolynhu** [comment]
@vincent99 in slack discussion, @cjellick said the "old way" should continue to work, so shouldn't we keep that one for the older version?

**Comment by vincent99** [comment]
I thought it was effectively rename the old code and leave as is, then build new one for hostTemplates.  Anyway, the old support can stay, but the current behavior is not explicitly defined in the UI or the docs so changing from `labelA OR labelB` to `labelA AND labelB` for a deprecated use case doesn't seem like a good idea.

**Comment by carolynhu** [comment]
@vincent99 ok, so you mean the old one is just match only one label? since I checked with @mrajashree, she said it should be match to all. If only need to match one, the old code will be fine.

**Comment by cjellick** [comment]
Old code should be renamed and left as is. New code should not impact it in anyway

**Comment by vincent99** [comment]
I don't know what it currently does, and the documentation/UI don't _say_ what it should do if more than one label is given, so what I'm saying is since we're deprecating the label-based approach anyway it should continue to work however it works now until it's removed.

**Comment by mrajashree** [comment]
Regarding the changes to old code/bugs
1. When going through the code again with @carolynhu we realized that in UI we can select more than one label pair but the code was using only one label pair. @vincent99 I get what you're saying, since the docs don't say anything specifically about it we don't need to change it as it'll be deprecated
2. The condition to increment the index for selecting a non custom base host for cloning seemed incorrect
3. @carolynhu We're not updating the host name, update would involve sending a POST request. The line of code you're referring to removes the value of `Name` from the config for cloning, which is done later on, so the initial line is unnecessary
4. When removing hosts in invalid states, the number of hosts being removed isn't being compared against the scale down amount.
@cjellick The 2nd and 4th points seem to be bugs, do they need to be fixed since we're renaming but still keeping the old code?

**Comment by carolynhu** [comment]
I think the test cases should cover the follows:
(1) if hostTemplateId and hostSelector both present, should return an error
(2) if both hostTemplateId and hostSelector not present, should return an error
(3) if hostSelector present, but hostTemplateId not 
3.1 action "up" + hostSelector is valid, should scale up hosts with specified labels
3.2 action "down" + hostSelector is valid, should scale down hosts with specified labels
3.3 action "up" + hostSelector is invalid, should return an error
3.4 action "down" + hostSelector is invalid, should return an error
(4) if hostTemplateId present, but hostSelector not
4.1 "up" + hostTemplateId is valid, should scale up hosts with specified hostTemplateId
4.2 "down" + hostTemplateId is valid, should scale down hosts with specified hostTemplateId
4.3 "up" + hostTemplateId is invalid, should return an error
4.4 "down" + hostTemplateId is invalid, should return an error
