### ISSUE TITLE
host w/ scheduler on it couldnt spin up new network-service containers

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9047]
**Rancher versions:**
rancher/server: 1.5.8
rancher/agent:

**Infrastructure Stack versions:**
network-services: showed up to date
scheduler: showed up to date

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Steps to Reproduce:**
host with a defunct scheduler on it couldnt schedule metadata containers. which effectively put it in a catch 22.

**Comment by deniseschannon** [comment]
Notes from @ibuildthecloud: 

The scheduler shouldn't stop when metadata/dns is down so the healthcheck should check that it can talk to metadata/dns.

**Comment by StrongMonkey** [comment]
Available in scheduler v0.8.1. We need to test following scenarios:
 scheduler will reports unhealthy(exit and restart) when metadata or rancher url is unreachable.
Noticed that there is a previous bug which scheduler won't exit when metadata service is stopped. So just make sure when metadata service is stopped or deleted, the scheduler should die.

**Comment by StrongMonkey** [comment]
Available in scheduler v0.8.1. We need to test following scenarios:
 scheduler will reports unhealthy(exit and restart) when metadata or rancher url is unreachable.
Noticed that there is a previous bug which scheduler won't exit when metadata service is stopped. So just make sure when metadata service is stopped or deleted, the scheduler should die.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.3-rc1 and scheduler v0.8.1

1. Stop metadata container that is running on the host where the scheduler is running. . 
Health check container stops (Exits) and then restarts successfully once the metadata container reconciles to running state successfully.

```
time="2017-06-23T18:11:14Z" level=info msg="Adding resource pool [hostLabels] with label map [map[io.rancher.host.zone:us-west-2a io.rancher.host.agent_image:rancher/agent:v1.2.3-rc1 io.rancher.host.docker_version:1.12 io.rancher.host.linux_kernel_version:3.10 io.rancher.host.provider:aws io.rancher.host.region:us-west-2]]" 
time="2017-06-23T18:11:49Z" level=error msg="Exiting scheduler with error: Metadata watcher exited: Get http://rancher-metadata/2016-07-29/version?wait=true&value=16879-4f3c5c96fb170da7fa8781d4ac55192c&maxWait=5: dial tcp 169.254.169.250:80: getsockopt: connection refused" 
time="2017-06-23T18:12:12Z" level=info msg="Connecting to cattle event stream." 
time="2017-06-23T18:12:12Z" level=info msg="Subscribing to metadata changes." 
time="2017-06-23T18:12:12Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck" 
time="2017-06-23T18:12:12Z" level=info msg="Initializing event router" workerCount=100 
```
2.Stop metadata service. As long as metadata service is stopped , the scheduler exists and scehduler container is in "Reinitializing" state .
```
6/23/2017 11:16:29 AMtime="2017-06-23T18:16:29Z" level=error msg="Exiting scheduler with error: Metadata watcher exited: Get http://rancher-metadata/2016-07-29/version?wait=true&value=16901-4f3c5c96fb170da7fa8781d4ac55192c&maxWait=5: dial tcp 169.254.169.250:80: getsockopt: connection refused"
```
When  metadata service is started back again , scheduler continues to be in "Reinitializing" . This is because of initialization/reinitialization timeout not set for scheduler containers.

3. Delete metadata container that is running on the host where the scheduler is running. Scheduler becomes unhealthy , gets removed and a new scheduler gets created on a different host successfully.
4. Stop rancher-server. Scheduler exits. When rancher-server is started , scheduler gets re-created successfully.

**Comment by sangeethah** [comment]
Reopening this issue to fix the issue seen with scheduler stuck  in "Reinitializing" state even after the metada service (that was in stopped state) was brought back up again.

**Comment by sangeethah** [comment]
Tested with the latest scheduler - v0.6.1 with following 2 timeout values set for scheduler:

```
      initializing_timeout: 10000
      reinitializing_timeout: 10000
```

Stop metadata service. As long as metadata service is stopped , the scheduler exists and scheduler container attempts to get recreated but fails which is as expected.

Start metadata service. Once metadata service starts successfully , scheduler is able to start successfully.
