### ISSUE TITLE
Dont update rancher DNS until containers within service pass health check

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9052]
Similar to #9051, dont have a container (with health check enabled) added to DNS until it starts passing health checks. It creates the situation where traffic can route to a service that cant field the request yet.

**Comment by kinarashah** [comment]
Servers aren't added to DNS until they're in healthy state. 

This can be confirmed using - 

1. Create a stack with 2 services : 
  a) Scaled up to >=2 containers, with health check enabled. Force all of them to stay 
  in initializing state by pointing HTTP Request Page to non existent file 
  b) For testing DNS lookup 
  
2. Use the second container to dig into the first. 

> One entry will always be returned even if all the servers are unhealthy, because the fqdn has to resolve to something.

```
$ dig nginx3 
opcode: QUERY, status: NOERROR, id: 47062 
// mandatory returns any one entry when all servers are not healthy 
nginx3.			600	IN	A	10.42.69.195 
```

3. Make changes so that few servers are healthy (make non existent file available) and 
dig again : 

```
$ dig nginx3 
opcode: QUERY, status: NOERROR, id: 50843 
// returns healthy servers only 
nginx3.			600	IN	A	10.42.54.246 
nginx3.			600	IN	A	10.42.107.53

```
Tested on - 
rancher/server:v1.6.3 
rancher/lb-service-haproxy:v0.7.5

**Comment by alena1108** [comment]
As a quick summary, unhealthy/initializing records do not go to dns config. With just one small exception - if service doesn't have at least one healthy/running record. Then we do populate it with a single ip address because once service is created, it should be resolved to something over just retuning nxdomain.

**Comment by cjellick** [comment]
No code change was made for this issue. We are just better explaining the behavior here. If @aemneina LGTMs, we can close

**Comment by aemneina** [comment]
LGTM @cjellick @alena1108 ... thanks guys!!!
