### ISSUE TITLE
Environment Variables in Add and Details needs to be changed & fixed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9068]
**Rancher versions:** 6/14

**Fixes needed:**

- [x] In Add - Remove Environment Labels from command accordion section
![image](https://user-images.githubusercontent.com/11514927/27158619-a30df17a-511c-11e7-8f95-53b990c6d210.png)

- [x] In Add - Fix Environment Variable so they work on containers and scaling groups (they seem to be broken and not adding at the moment)
![image](https://user-images.githubusercontent.com/11514927/27158631-b7550858-511c-11e7-866d-554cd1565416.png)

- [x] In Details - Remove Environment labels from command accordion
![image](https://user-images.githubusercontent.com/11514927/27158652-dda9180a-511c-11e7-9bfa-756d56a6f484.png)

- [x] In Details - Create a new Environment Variables accordion that will display information in table.

**Comment by westlywright** [comment]
@tfiduccia I can not repro the env vars not being set. As far as I can tell they are working correctly. I launched 4 containers and 4 scaling groups with env vars, all had the correct var's set. I am actually thinking that because the env vars also existed (for input mode) in the command component as well as the normal spot to add them that maybe they were over writing each other. I think this will resolve all issues but if not just send it back to me after its merged.

**Comment by tfiduccia** [comment]
Version - Wagyu (master 7/25)
Verified fixed
