### ISSUE TITLE
Import single file compose.yml does not work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9069]
**Rancher versions:** 6/14 (2.0 alpha)

**Steps to Reproduce:**
1.  Click on Import compose.yml
2.  Copy/paste a v2 compose.yml file into contents
3.  Click on Create

**Results:**  Stack get created but scaling group/containers do not.

**Comment by StrongMonkey** [comment]
adding an option for export to get a compose.yml when the payload has `combined=true`

**Comment by vincent99** [comment]
@StrongMonkey for export it should probably be an enum since there's a good chance there will be other format choices in the future.. `{format: 'compose'}` / `{format: 'rancher-compose'}`.

But that's only on export.  For import the `dockerCompose`/`rancherCompose` fields are deprecated and you just send a map of `files`, which will either be a single or multiple entries.

**Comment by StrongMonkey** [comment]
@vincent99 Now its a enum with two options "compose" and "rancher-compose". if it is `compose` then give combined compose, and if not fall back to the previous two files.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Verified fixed
