### ISSUE TITLE
What does 'Untested Docker version' on the hosts page mean?

### ISSUE THREAD

**Issue by underyx** [rancher/rancher#9106]
Clicking the tag takes you to the [supported Docker versions](http://docs.rancher.com/rancher/v1.6/en/hosts/#supported-docker-versions) page in the docs which makes no mention of the word 'untested'.

How do you support versions of Docker without testing them? What does that mean?

**Comment by deniseschannon** [comment]
The `untested versions` in the UI are to indicate to the users that this is not one of the supported versions of Docker. It directs you to the supported versions of Docker to show you what version of Docker **is** supported/tested.

The un-tested ersions are typically the latest (non-stable) versions of Docker that was released at the time of the Rancher release. These versions haven't gone through our QA validation, which is why we do not support or recommend them.

**Comment by underyx** [comment]
@deniseschannon Thanks for the quick response, but I'm still confused a bit. I thought what you just described is what an 'Unsupported Docker version' would be. Take for example `17.03.0-ee`. The support table says it's supported, so I'd assume it went through QA validation; but the hosts page marks still marks it as Untested. So, what is displayed for specific versions is:

- 1.12: no warning
- 17.03: 'Untested' (though it's marked supported on the supported Docker versions page)
- 17.05: 'Unsupported'

So how exactly are these three different?

**Comment by vincent99** [comment]
"Untested" is a version which matches the supported list of (typically) minor versions, but is newer than the newest patch release tested at the time.  For example "17.03.*"is supported but if 17.03.1 was the newest at the time and 17.03.2 comes out, that is interested because it didn't what (or at least we didn't switch and start over) at the time of the release.

**Comment by underyx** [comment]
Oh I see, so we would just have to downgrade to a lower patch release to get rid of the warnings, that makes sense! Thanks @vincent99
