### ISSUE TITLE
docker-machine virtualbox

### ISSUE THREAD

**Issue by uLow** [rancher/rancher#9240]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.12.6, build 78d1802

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.8.0-58-generic

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I'm trying to add virtualbox host with "generic docker-machine" driver. But when I click "other" in host creation, there is no "virtualbox" option, only "generic". 
So basic question is - **"How to add virtualbox docker-machine in rancher?"**. 

P.S. I can use it from CLI like `docker-machine create --driver virtualbox ...`

**Comment by vincent99** [comment]
The virtualbox driver is not shown because it's useless in this situation.  It has no options to tell it _where_ virtualbox is and assumes you're running it in the same scope (i.e. you have both machines and virtualbox installed on your laptop).

With Rancher you are running machine from inside the server container, and there is no virtualbox in there to use.

**Comment by uLow** [comment]
Why I cant set rancher on host and keep groups of containers in vms?
