### ISSUE TITLE
[RFE] extend instance.dns_search_internal db column from 256 to something bigger

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9337]
Was hitting a limit adding an instance that had a few search domains added. They just surpassed the 256 limit as rancher adds its own internal domains as well.

```org.jooq.exception.DataAccessException: SQL [update `instance` set `instance`.`data` = ?, `instance`.`dns_internal` = ?, `instance`.`dns_search_internal` = ? where `instance`.`id` = ?];  (conn:236319) Data too long for column 'dns_search_internal' at row 1```

**Comment by sangeethah** [comment]
Tested with rancher-server v1.6.8-rc1.

Able to create services by providing multiple search domains whose length adds up to > 256.

In database , instance table has length of 1024 for ns_search_internal  field.
```| dns_search_internal     | varchar(1024) | YES  |     | NULL    |   ```

**Comment by cjellick** [comment]
When we upgraded an internal environment that has a large number of rows in the instance table (1 million-ish), we discovered the fix for this (which is to update a column in that table) took way too long.

So, we are going to rollback this fix until we fix the underlying issue of the `instance` table not getting cleaned up properly. The fix for that is targeted for Septmember. I did a preliminary investigation and found that it is *not* the known issue of host-bind-mounts causing the problem (TODO reference issue).

Reopening this issue.

**Comment by alena1108** [comment]
We should also consider changing the field size to the value bigger than 1024 as that might not be enough. Per @vincent99 65535 doesn't cost any more space than 1024 (for a field that isn't going to be indexed)

**Comment by aemneina** [comment]
We need to call this ticket out in the release notes. The table migration creates a temp table and can potentially consume lots of disk space, basically ensure you have lots of space. Also the fact it can take a while to carry out the operation.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
