### ISSUE TITLE
Loading logo is missing one dot in orbit

### ISSUE THREAD

**Issue by JendaPlhak** [rancher/rancher#9350]
**Rancher versions:**
rancher/server: v1.6.2
User interface: v1.6.5
Rancher CLI: v0.6.1

**Steps to Reproduce:**
Loading logo is missing one dot in orbit while loading:
![Missing dot](https://user-images.githubusercontent.com/5598129/28215700-2d2a2898-68af-11e7-95f0-610246df37d7.png)

**Results:**
My OCD inner self is very unhappy.

**Comment by underyx** [comment]
©️

**Comment by vincent99** [comment]
I don't know what the deal is with the obvious voting brigade, or what you think that's going to accomplish...  but nowhere in the history of github have 25 people in a row independently used reactions correctly instead of posting `+1` messages,  especially in 2 hours, for a trivial issue.

It's a stroked SVG path so rendering is going to depend on browser, OS, screen resolution/DPI, etc.  But it doesn't look like that on anything I've seen, so you're going to need to provide some information. 

(Also 2.x has a completely different loading animation anyway.)

**Comment by JendaPlhak** [comment]
Well these are all apparently OCD people who would suffer greatly if such a nice thread would be polluted by misuse of messages. Anyway, the browser is Chrome version 59.0.3071.115 running on macOS Sierra, version 10.12.5, screen resolution 2880 x 1800 220.53 PPI. Hope it helps :)

**Comment by tfiduccia** [comment]
Version - 1.6.6-rc6
Verified fixed
