### ISSUE TITLE
Auditlog Purge mechanism

### ISSUE THREAD

**Issue by tuwid** [rancher/rancher#9386]
**Rancher versions:**
rancher/server: 1.6.4

**Infrastructure Stack versions:**
scheduler:v0.8.2

So I need to have rancher's audit logs in graylog and since they're in a mysql table I'm unsure on how should I periodically export the audit logs to my centralized logging solution.
* What is the best way to achieve this ? 
* Shouldnt there be any features to have the audit logs somewhere in a file or to have basic syslog capabilities ?  
* Is there any API calls that i can manually run to purge the logs so I could collect them and then purge them in order not to have duplicates and have all the process under control ?
* Is there any pre-hooks that I can add to the purging mechanism that it will execute my script before doing the purge ? 

Some time ago when I used to use splunk it had a plugin that would monitor rows added in a mysql table via jdbc (like that elasticsearch plugin ) but graylog has no support for that.
I've written a script that does a query and extracts the logs to a file but the issue is that I'm unsure on how the purging mechanism works on rancher audit logs as the only settings there is regarding this is the purge interval in seconds `audit_log.purge.after.seconds` and if I pull the logs every fime minutes and rancher purges every 6 it will overlap. 
Is the rachner purging mechanism cron based or is it event based ? 

Something fast that I had in mind : 
```
#!/usr/bin/python
import mysql.connector

import json

config = {
	'user': 'rancher',
	'password': 'xxxxxxxx',
	'host': 'xxxxx',
	'database': 'test',
	'raise_on_warnings': True,
	'use_pure': False,
}


cnx = mysql.connector.connect(**config)
cursor = cnx.cursor()

try:
	cursor.execute('SELECT * from audit_log;')
	# cursor.execute('describe audit_log;')
	results = cursor.fetchall()
	for row in results:
			print "rancher_audit_log_id " + str(row[0]).replace("\\","") + "\t",
			print "rancher_audit_log_account_id " + str(row[1]).replace("\\","")+ "\t",
			print "rancher_audit_log_auth_as " + str(row[2]).replace("\\","")+ "\t",
			print "rancher_audit_log_kind " + str(row[3]).replace("\\","")+ "\t",
			print "rancher_audit_log_auth_type " + str(row[4]).replace("\\","")+ "\t",
			print "rancher_audit_log_event_type " + str(row[5]).replace("\\","")+ "\t",
			print "rancher_audit_log_resource_type " + str(row[6]).replace("\\","")+ "\t",
			print "rancher_audit_log_resource_id " + str(row[7]).replace("\\","")+ "\t",
			print "rancher_audit_log_description " + str(row[8]).replace("\\","")+ "\t",
			print "rancher_audit_log_created " + str(row[9]).replace("\\","")+ "\t",
			print "rancher_audit_log_data " + str(row[10]).replace("\\","")+ "\t",
			print "rancher_audit_log_auth_as_ident " + str(row[11]).replace("\\","")+ "\t",
			print "rancher_audit_log_runtime " + str(row[12]).replace("\\","")+ "\t",
			print "rancher_audit_log_client_ip " + str(row[13]).replace("\\","")+ "\t",
			print "\n"
except:
	print "Error: unable to fecth data"

cnx.close()
```

**Comment by vincent99** [comment]
> What is the best way to achieve this ?

The cattle process runs a periodic task which deletes rows with a created date older than (the current time) - (the configured purge time).

You can't have a periodic reader that doesn't a) miss rows or b) see the same rows more than once, without saving state.  The normal thing to do would be to remember the last ID you've seen and select only rows higher than that next time, and run it more frequently than they're deleted (preferably somewhat more than half the interval, so that you get at least 2 chances to see each row).

Since you're already rooting around the database, you could just leave the setting at the long default and delete rows yourself after processing them.

> Shouldnt there be any features to have the audit logs somewhere in a file or to have basic syslog capabilities ?

Software should do lots of things.  Writing to a file doesn't really accomplish much besides complicating aggregation (multiple servers in a HA setup) and installation (there is nothing persistent in a standard setup except the database).  PRs welcome for optional writing to a remote syslog.

> Is there any API calls that i can manually run to purge the logs so I could collect them and then purge them in order not to have duplicates and have all the process under control ?

No, a "wipe the audit trail" button in the API somewhat defeats the purpose of the trail.  But again, you're already in the database.  Delete them yourself.

> Is there any pre-hooks that I can add to the purging mechanism that it will execute my script before doing the purge ?

No.

**Comment by tuwid** [comment]
@vincent99 thanks 👍
