### ISSUE TITLE
resource limits dont get adjusted after host spec's change

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9411]
**Rancher versions:**
rancher/server: 1.5.9

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. add host
2. power off host, resize in terms of mem/cpu
3. view host through edit view

**Results:**
The host resource limits havent changed from when the host had lower spec's. The hosts actual resources were re-detected just fine, but the host resource limits weren't recalculated.

**Comment by vincent99** [comment]
They are set specific values in the database, initially defaulted to the size at the time the host is added but can be changed by the user later.

**Comment by aemneina** [comment]
sure they can, but host spec changes are detected when an agent restarts, why not readjust these as well?

**Comment by vincent99** [comment]
Because there is currently no way to distinguish "The user set it to X" from "The user never set it but it was automatically set to X at the time the host was added".   It's just a number in the database.

You need a way to know the difference to be able to decide whether it should be updated or not when the host is suddenly Y instead of X.  Such as storing `null` or `-1` as a signal that the host's size should be used, and storing a real number only if specifically set by the user.

**Comment by aemneina** [comment]
That makes perfect sense. Thanks @vincent99

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
