### ISSUE TITLE
Rancher Secrets custom path

### ISSUE THREAD

**Issue by uLow** [rancher/rancher#9427]
I have image that is taking config file from exact path that can't be changed.
How to specify custom destination path of secrets, so my config gets mounted to that path?

**Comment by aemneina** [comment]
you might be able to sym link it after the container starts to the desired path... as secrets are mounted in `/run/secrets`.

**Comment by uLow** [comment]
Is there any method to avoid modifying entrypoint/cmd?

**Comment by vincent99** [comment]
No, it's a memory-backed volume mounted onto the container.  You can't put individual secrets in arbitrary places.

**Comment by uLow** [comment]
So "new feature request"?

**Comment by uLow** [comment]
`it's a memory-backed volume mounted onto the container`
There must be optional "mount path" when you put secret in container.

**Comment by mmkaminski** [comment]
On RedHat systems (Atomic and RHEL) /run/secrets/etc-pki-entitlement, /run/secrets/rhel7.repo, and /run/secrets/rhsm are mounted to propagate RedHat subscription info to all constituent containers on the system, regardless of base OS in the container. It would be _incredibly useful_ if we could specify an alternate mount path for the secrets service container, like /run/rancher/secrets/<secret>. Or simply mount just the specific secret to /run/secrets/<secret> instead of the whole directory. As-is this feature is completely unusable in a RHEL environment.

**Comment by aemneina** [comment]
Making this configurable might be an option. I'll change the ticket to feature request.

**Comment by superseb** [comment]
If you have to use RHEL's Docker but don't need to mount for subscription info you can configure `--enable-secrets=false` inside the `OPTIONS` parameter in `/etc/sysconfig/docker` to disable the mount on `/run/secrets`. Don't forget to restart the docker service to enable the change.

If you have to use the subscription info, this issue remains valid.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
