### ISSUE TITLE
Auth-service does not reload on update to auth config

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#9457]
AuthServiceLauncher from cattle has reload settings list, and makes auth-service reload if any of the settings in that list change.
When auth-service Testlogin api updates ldap's config, only the ldap config changes, the settings common to all providers remain unchanged. Thus reload on auth-service is never called even if the ldap config is updated. So for HA setup, auth-service on only one node on which testlogin was called will end up with the updated ldap config.

**Comment by sangeethah** [comment]
Tested with Rancher versions: v1.6.6-rc3

Set up - Rancher server setup with 3 hosts (h1,h2,h3) in a cluster.

Steps to reproduce the problem:
Have AD auth enabled.
Change service account password from LDAP server.

Session1  - Launch rancher-server UI by directly using h1's ipaddress to launch UI.
Session2  - Launch rancher-server UI by directly using h2's ipaddress to launch UI from another browser.
Session3  - Launch rancher-server UI by directly using h3's ipaddress to launch UI from another browser.

Wait for about 5 mts for the password change done on LDAP server side to take effect.

From session 1 - Launch Environment detail page that has "Access Control" tab listing all users. "User Not Found" message is seen for the users since the look up for user information fails.
From session 2  - Launch Environment detail page that has "Access Control" tab listing all users. "User Not Found" message is seen for the users since the look up for user information fails.
From session 3  - Try to log in as valid user. User authentication fails. 


From session 1 - Change service account password to correct value by using "Edit" option in "Access Control" page and using "Test and Save".
 Launch Environment detail page that has "Access Control" tab listing all users. User name lookups will succeed.
From session 2  - Launch Environment detail page that has "Access Control" tab listing all users. Launch Environment detail page that has "Access Control" tab listing all users. User name lookups will succeed.
From session 3  - Try to log in as valid user. User authentication succeeds now.


When AD settings were updated from one of the hosts , this resulted in  Auth provider was reconfigured in 2 other rancher-server hosts in the cluster.

Following logs are seen in other hosts:
```time="2017-07-25T19:00:44Z" level=info msg=" Auth provider configured ldapconfig" ```
