### ISSUE TITLE
Renaming a Stack leads to unresolveable host names

### ISSUE THREAD

**Issue by irockel** [rancher/rancher#9542]
If a stack *test-1*, which contains *host-0* and *host-1* is renamed to *test-0*, the hostname are no longer resolveable without the fully qualified domain name because a renaming of the stack moves the hosts into the new domain *test-0.rancher.internal* but the search in /etc/resolv.conf inside the containers is not updated and stays *test-1.rancher.internal*

The images in the test were built with centos:7 and ubuntu:16.04.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by proligde** [comment]
Same here and even worse: The internal haproxy won't resolve the stack's services after being restarted once. This is pretty dangerous and just rendered a setup unusable here.

Versions: Rancher v.1.6.6, lb-service-haproxy:v0.7.6

Reproduction:
- Create a Loadbalancer in a stack.
- Create a new Stack with a Name test-1 and add services
- Connect the loadbalancer to a service in test-1
- Rename stack from test-1 to test-0 or whatever
- Restart Loadbalancer

Expected behaviour:
- The service is still available when connecting to the loadbalancer endpoint
- The service is renamed when watching the loadbalancer's dropdown list for target services

Actual behaviour:
- The loadbalancer shows an error not being able to resolve the target service
- The service still shows the old name in the loadbalancer's dropdown list

**Comment by loganhz** [comment]
I can not reproduce it in v1.6.22

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by blar** [comment]
After renaming a stack, the search domain is not updated in the /etc/resolve.conf or the "Networking" tab in the container settings. It is required to upgrade It is required to upgrade (not only restart) all services in the stack to update the search domains.
