### ISSUE TITLE
Stack Scoped Agent Roles

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9546]
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

It would be very nice to have stack scoped agents vs environments. There are times where I need one service inside a stack to interact against another inside the same stack using the API, but the only option is to generate an environment access key using an environment role which is a lot of permissions.

It would be nice to have a stack scoped role.

Thanks!

**Comment by wzrdtales** [comment]
Yes generally being able to only give access to a stack would be very powerful. For both API and users.

**Comment by ekristen** [comment]
I would also like to suggest allowing for service scoped tokens while we are at it. It would be nice to allow a service to deactivate itself (it it runs into certain conditions)  and not let it access other things.

**Comment by ekristen** [comment]
Any traction on this request?

**Comment by wzrdtales** [comment]
@ekristen  I guess it wont get any traction at all. Rancher v2 is coming, which completely steps over to kubernetes. With which you can couple the user management of rancher and RBAC and really have granular way of setting permissions.

**Comment by ekristen** [comment]
First, how does kubernetes solve access to the rancher api?

Second, unless there is an upgrade path from v1 to v2, v2 is useless for anyone who has a large v1 deployment.

**Comment by wzrdtales** [comment]
After all it is a major release upcoming, no one will force you to upgrade. Just like with software in general, the moment you stop working keep up to date on your dependencies, frameworks and stuff, your product is dead.
If the rancher team provides an upgrade tool or not, only the release will reveal.

However I'm not associated with rancher, apart from being a long time user, so I can't and wont answer any question related how their API will look like and how they integrate that in the new version. You should probably ask that in a different channel than in this issue :)

**Comment by ekristen** [comment]
@wzrdtales I understand. My point is that you brought up v2 and kubernetes as a solution to RBAC and API access. I wanted to understand why you think this would solve this issue in v2.

My concern is that with "v2" coming that all work and features on v1 stops, which would be bad IMO unless there is an upgrade path to the v2 version. Otherwise there are going to be a lot of user's stuck on v1 for a while and no longer getting usability improvements/enhancements/feature requests is going to hurt the customer base.

I too am just a long time user ;)

**Comment by wzrdtales** [comment]
@ekristen As addition I know the pain you're feeling there and our setup is really really huge. That is the reason why we basically *NEVER* upgrade the ipsec stack unless it fixes critical vulnerabilities. But moving on to a new major release, this is somehow different. There is an actual value moving on, in upgrading the ipsec stack for example there is often no value at all, it might fixes bugs you never encounter.
 
And I think the rancher team will support v1 for a long time, but since they dropped their own orchestrator in favour of kubernetes, I hardly guess stuff like this will never appear on the screen.

About RBAC and the API access, basically simple: When v2 comes up, everything you could do with the API before you can do after that via kubernetes directly. And however the API will be integrated, I don't think that they will allow that you can execute any actions that would override the underlying permissions.

**Comment by wzrdtales** [comment]
I however also hope for an easy upgrade path with as little downtime as possible though :) We will do the upgrade anyway, so I might report how that went though.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/8407
