### ISSUE TITLE
Network partition when upgrading service using retain_ip feature

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#9559]
**Rancher versions:**
rancher/server: v1.6.6

**Infrastructure Stack versions:**
ipsec: rancher/net:v0.11.5

**Steps to Reproduce:**
1. Create a cattle environment with 3+ hosts
2. Create a service of scale=2 that specifies `retain_ip: true`
3. Deactivate one of the hosts with a container from aforementioned service. This forces the issue to reproduce.
4. Upgrade the service, modifying an environment variable to trigger container re-creation.

**Results:** Container on host A is stopped and replaced with container on host B. Container on host B is partitioned from the network. Existing containers continue to communicate.

**Expected:** Network is not partitioned.

**Comment by leodotcloud** [comment]
Fixed for ipsec: ipsec(0.1.3) with rancher/net:v0.11.6

**Comment by sangeethah** [comment]
Tested with Rancher version - rancher-server v1.6.7-rc1
Fresh install of rancher-server v1.5.7 have kubernetes evn in isolated planes with:

3 compute nodes
6 etcd nodes
2 orchestartion nodes

Have few pods and ingress deployed in K8s environment.

Upgrade rancher server to rancher-server v1.6.7-rc1

Upgrade all infra stacks , network-services , ipsec , scheduler and healthcheck.
Upgrade Kubernets stack.

Kubernetes stack gets upgraded successfully.
etcd containers move to different hosts when Kubernetes stack gets upgraded. 
Quorum is not lost when etcd service gets upgraded.
etcd container uses retain_ip.

**Comment by sangeethah** [comment]
Tested with Rancher version - rancher-server v1.6.7-rc1

Steps to Reproduce the problem:
Create a cattle environment with 3 hosts
Create a service of scale=2 that specifies retain_ip: true 
Deactivate the host where an instance of the service is running.
Upgrade service.
This results in the newer instance of the service to be launched in a different host.
When service is still in upgraded state , this newer instance of the service that was launched in a different host is able to communicate with other instances of the service.

There is a 10-15 sec delay for the ping (of ipaddress of other containers in the service) to respond . After this the response is prompt.

**Comment by leodotcloud** [comment]
Fixed for vxlan: vxlan(v0.2.1) with rancher/net:v0.11.6.

**Comment by leodotcloud** [comment]
@sangeethah The original problem reported in this issue is fixed. 

Regarding the delay:
- When the container moves from one host to another, the ARP entry in other containers which have previously used the reatain IP is in "STALE" state.
- When we do a ping, instead of doing an ARP request first, the stale ARP entry is used to send out ping packets.
- A second or two later, the ARP is sent again and that refreshes the MAC address. This causes the ping to start succeeding.
This is a normal behavior of things. 

We can definitely improve upon this and invalidate the ARP cache from `network-manager` aggressively. But that means we have to get inside all of the running containers in the host, check all ARP entries for all other containers which is pretty expensive. We already do this for ipsec container when the stack is upgraded.

Please feel free to file an enhancement, we can take a look at it later.

**Comment by sangeethah** [comment]
Logged this issue - https://github.com/rancher/rancher/issues/9666 to track the issue seen with delay in pings from upgraded containers.
