### ISSUE TITLE
investigate the impact on "stopping" containers

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9561]
Need to investigate how the fixes for the following issue(s) might impact "stopping" containers:
- https://github.com/rancher/rancher/issues/9559

Related issues:
- https://github.com/rancher/rancher/issues/9508
- https://github.com/rancher/rancher/issues/9389
- https://github.com/rancher/rancher/issues/9519

This issue is a dependency for https://github.com/rancher/rancher/issues/2777

**Comment by deniseschannon** [comment]
`network-manager:v0.7.13` and `rancher/net:v0.13.1` are available in the `v1.6-development` branch

**Comment by sangeethah** [comment]
Tested with rancher-server version v1.6.11-rc4 , rancher/lb-service-haproxy:v0.7.14 , network-manager:v0.7.13 and rancher/net:v0.13.1.

Target service with scale 2 and drain timeout set (25 secs).
LB service containers and target service containers should be in different hosts.

Make connections to LB Ip which persists for a longer time (like 20 secs)
When connections are still in progress , upgrade target service with batch size =2 , so that when haproxy is draining for one of the target service instances , there is also a metadata change relating to other service instances state ( to stopping/stopped) being propagated.

Existing connection made to LB service succeeds.

**Comment by galal-hussein** [comment]
Rancher server: v1.6.11-rc4

Tested stress test scenario by force upgrading ipsec stack for 10 loops in kubernetes environment and making sure that all the components are back online.
