### ISSUE TITLE
Q: Supported docker version confusion

### ISSUE THREAD

**Issue by garceri** [rancher/rancher#9611]
**Rancher versions:**
rancher/server:1.6.5
 According to the release notes for 1.6.5 (https://github.com/rancher/rancher/releases/tag/v1.6.5) docker 17.0.5 is supported, yet when i check 
http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions it says it isn't and the UI is reporting it as unsupported:
![image](https://user-images.githubusercontent.com/10517648/29035043-a49fb130-7b70-11e7-8f76-2bc7b5299fff.png)

What's the "right" position on this ?

**Comment by vincent99** [comment]
What part of the release notes do you see as saying anything about 17.05?

17.05 is an ["edge"](https://blog.docker.com/2017/03/docker-enterprise-edition/) releases and edge releases are supported by Docker for the 4-5 weeks of that month (which has long passed now).  17.03/06 are "stable" and supported for 4 months.

Rancher supports EE and Stable, but not Edge. (And the older 1.12/13 mostly as maintained by OS vendors, and because Kubernetes doesn't test anything newer).

**Comment by garceri** [comment]
Sorry, i rechecked the release notes and looks like 17.03 and 17.06 are supported but not 17.05.
