### ISSUE TITLE
Changing ldap server when editing LDAP settings , results in no admin user being available.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9641]
Rancher versions:v1.6.8-rc1

Steps to reproduce the problem:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to change the "Hostname" to point to a different LDAP server.
Use "Test and Save" to test and commit the changes to configuration.

Once "Test and Save" is done , user to brought back to the log in page.
When u try log as the admin user (user used for "Test and Save" ) , he is not the admin user anymore.
Seems like a new user gets created when log in was attempted.

Follow up questions:
1. Should we not allow for ""Hostname" to be changed as part of "Edit" option
2. Should the UI force the same admin user to be used for ""Test and Save".

**Comment by prachidamle** [comment]
Root Cause of why there is no admin user available:

When Auth settings are changed via "Edit Settings" only API calls made are: POST /v1-auth/testlogin and POST /v1-auth/config - these are to test the settings with the user/pwd provided and then save the config respectively.

Here there is no API call to login the test user or create an account for that user. We do not want to do that either as the intent of this feature is you are already logged in as an admin user and just editing some settings for the existing AD setup.

So now if you are changing the settings so that you start pointing to a new AD server althogether, you are in fact breaking your current access control setup and users created for the original AD server.

So I agree to both, that "Edit Settings" should not allow editing "Hostname" of AD server. And also forcing the test username to be same as the current logged in Admin and just asking for the password, will avoid any confusion as to whether we are creating a new account or not.

**Comment by sangeethah** [comment]
@prachidamle , Can we also evaluate if there is a potential downside to editing any other settings ? Currently UI allows for editing all fields. 
Changing "User Search Base" (by making it more restrictive) can potentially cause existing users (including Admin) to be not able to log in. Is this something we need to make a note of in UI for user?

**Comment by prachidamle** [comment]
Changing "User Search Base" should still be allowed as an Admin can "expand" the base to include more users.

But restricting  "User Search Base" can lead to problems as you noted, we can document this/ put an info tip in UI. If we do the UI change to force the test username to be the current admin, testing with that user will break if user-base is restricted and that would avoid the problem.
But in any case it has to be noted in UI/docs that restricting  "User Search Base" can lead to problems. @deniseschannon

**Comment by toughIQ** [comment]
Is there the possibility of a local admin user account, which I could define upfront to make sure, that I can access my instance, even if the defined Auth Service is down or broken?
I think the current way would be to go into the DB and change a setting there, but this isnt the most convenient way.

**Comment by cjellick** [comment]
@toughIQ no there currently is not support for that, but the feature request is captured here:
https://github.com/rancher/rancher/issues/8740

**Comment by sangeethah** [comment]
Tested with rancher versions:v1.6.8-rc3

Scenario 1:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to change the "Hostname" to point to a different LDAP server.
Use "Test and Save" to test and commit the changes to configuration.
User is presented with following error message - "Mismatch in ExternalId of the Admin account, with new server settings"

Scenario 2:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to make the user search base more restrictive such that the current admin user is not a valid user under this search base.

Use "Test and Save" to test and commit the changes to configuration.
User is presented with error message - "Cannot locate the user information with new server settings"

Scenario 3:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to change the "Hostname" to point to a different LDAP server.
There is no ability provided in the UI for changing the username under "Test and save new configuration" page.
