### ISSUE TITLE
Marking default templates private causes dupes in the UI

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9704]
Marking default templates private causes duplicates.

**Comment by aemneina** [comment]
Repro steps:
1. Click environment dropdown
2. select manage environments
3. edit a default environment template, like cattle 
4. set to sharing to private
5. save template.

Result:
after a few minutes i get two cattle templates.

**Comment by deniseschannon** [comment]
These are technically not duplicates. 

By design, if the Rancher catalog has a project template, i.e. environment template, and it doesn't find a public version of template of that catalog , it will sync with the catalog and download the latest template as a public template. 

If the catalog item for the environment template was not in the Rancher catalog, then it wouldn't download a new one.

**Comment by deniseschannon** [comment]
If you don't want any environment templates from the default Rancher library, then you'll need to create your own catalog and remove the default ones provided by Rancher.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
