### ISSUE TITLE
Port forwarding/startup issue

### ISSUE THREAD

**Issue by ttftw** [rancher/rancher#9721]
**Rancher versions:**
1.6.5

**Infrastructure Stack versions:**
latest

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Metal

I had container A receiving on a port...I replaced it by stopping this container and starting container B on the same port.  A very small percent of packets are being forwarded to container B.  I do ngrep on the host to verify packets are making it to the host, and ngrep inside the container and I only see a few.

When troubleshooting, I noticed I was able to start up both containers bound to the same port.  Typically, when I start containers bound to the same port, it errors out.  I feel like this may be related.   I've verified they are on the correct host and also tried binding to an ip directly and that doesn't help.  (it also let's me bind two containers to the same port on the same ip).  I've also confirmed I'm using the same protocol for both.

Any ideas?

** Edit.  I created the container in docker using port mapping, and everything worked as expected.  So the issue seems to lie with Rancher and how it's routing packets.

**Comment by Meowbeast** [comment]
I tried this on a new host, too.  I installed rancher and bind a port for forwarding...and it doesn't forward the packets to the container.  If I create and start a container with the same image/options, but start it in Docker directly instead of Rancher, it binds the port correctly.  Seems there is something with Rancher that is not forwarding bind ports.

**Comment by Meowbeast** [comment]
I changed the network from `managed` to `bridge` and it worked.  This has worked previously using the `managed` network.

Any feedback would be appreciated.

**Comment by vincent99** [comment]
Managed networking sites port forwarding through iptables rules.  They will not show up in `docker inspect` or `netstat`.

**Comment by Meowbeast** [comment]
I understand that, I'm not expecting them to show up in `inspect`, I'm just expecting them to work.  Port forwarding does not seem to work using `managed` network.  Using `bridge` or using Docker directly, it works.

Also, this worked for some time, and then when I upgraded the container, the port forwarding quit and no longer works even if I move the container to a new host.

**Comment by oskapt** [comment]
@vincent99 - I'm able to confirm that we are allowing multiple services to start and listen on the same port, when previously we would fail to launch the service and report that no host met the required constraints. The first service launched and bound to the IP of the host. The second service launched and bound to `0.0.0.0`. The second service received all traffic for the port until stopped, when traffic returned to the first service.

Another user reported that after removing the second service completely, the first service returns `Connection refused`, even after restarting, deleting, and recreating the service. Although that behavior was not what his Linux system showed, he was able to demonstrate it on a Windows system. This sounds like the issue reported by @Meowbeast in his most recent comment.

The user also reported that it "worked when started directly in Docker," which is what @Meowbeast reports. Because Rancher and Docker handle iptables configuration differently, the problem may be in how we're handling the port forwarding to containers.

The `Connection refused` symptom was seen in 1.6.2 in Docker/Rancher/Windows. The dual-service-on-same-port issue was seen in 1.6.7 in our demo environment.

**Steps to reproduce**
1. Start `nginx` and bind a port mapping from `xxxx` to `80`. Schedule it to one host.
2. Visit the host and see the site
3. Start `monachus/rancher-demo-php` on the same host, binding the same ports.
4. Visit the host and see the new container's site
5. Stop the second container.
6. Visit the host and see the nginx site again.

**Comment by vincent99** [comment]
I think the key here is scheduling to *a particular host*, i.e. using `requestedHostId`.  That bypasses all of scheduling, and apparently port-conflict checking too.  Paging @cjellick.

Regular scheduling seems to work fine (two hosts, `a` and `b` have no scheduling set and use up both port 80s on them, `c` also has no scheduling set and fails.  `d` was set to a specific host and fails to fail (incorrectly starts the container and commandeers the iptables rule for 0.0.0.0:80).

![image](https://user-images.githubusercontent.com/753917/30097699-b38586ea-9293-11e7-9256-51226043915e.png)

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
