### ISSUE TITLE
[cli] Rancher CLI ignoring --env-file

### ISSUE THREAD

**Issue by Cynicide** [rancher/rancher#9738]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: v1.2.5
rancher cli: rancher version v0.6.4-rc1 and v0.6.2
OS: Windows 10

**Steps to Reproduce:**

I am attempting to upgrade a stack via the rancher cli. I am expecting the CLI to perform the upgrade with no user intervention. 

Example of an environment key in the docker-compose file:

    environment:
     - ASPNETCORE_ENVIRONMENT=${myenvironment}

I have specified in my env file in the following format:

    myenvironment=development

I have used the following command:

rancher --env mydev --access-key XXXX --secret-key XXXX --url http://rancher:8080/v1 --env-file backend-dev.txt up --upgrade backend --force-upgrade --confirm-upgrade --pull

Have also tried:

rancher --env mydev --access-key XXXX --secret-key XXXX --url http://rancher:8080/v1 up --env-file backend-dev.txt --upgrade backend --force-upgrade --confirm-upgrade --pull

**Results:**

Rancher CLI asks for the environment variables.

*Output of Command:*

The environment name for the instance
Environment Name myenvironment[development]:

**Comment by sunbit** [comment]
Same here,

rancher/server: v1.6.10 (on archlinux)
rancher cli: v0.6.4 (on osx, also tried same version on archlinux)

while trying a rancher up --env-file, it ignores the file specified. I tried also following what it says in the online documentation an trying yaml and json formats for this file, without success.

Looking at the code it seems the flag was removed on purpose, can anyone confirm this? Because rancher docs still lists this option:

https://github.com/rancher/cli/commit/d3f2a8fb228b6086c26455ca90e477526eb1e322#diff-b8aac5efb9904be5c8ebe84055a5927f

http://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-up-reference

Thank you

**Comment by sunbit** [comment]
I just tested several rancher cli releases, and the last one that recognized the env-file parameter is
v0.6.0-rc2, starting with v0.6.0-rc3 the parameter has no effect.

Can anyone confirm if this is on purpose?

**Comment by carolynhu** [comment]
Cannot reproduce this error on:
rancher/server: v1.6.10 
rancher cli: v0.6.4 

docker-compose.yml
```
version: "2"  
services:  
  service:
    image: ubuntu:16.04
    tty: true
    environment:
      MyEnv:
```

myenv file:
```
MyEnv=carolynEnv
```
after run ```rancher up --env-file myenv -d``` (Note here: do make sure to put your --env-file myenv after ```up``` , otherwise, it will not going to parse env file variables)
my service launches in UI, and it's compose file as follows
```
version: '2'
services:
  service:
    image: ubuntu:16.04
    environment:
      MyEnv: carolynEnv
    tty: true
```

**Comment by deniseschannon** [comment]
@Cynicide we were unable to reproduce this issue. please re-open if you have questions or can reproduce on the latest CLI version.

**Comment by ozbillwang** [comment]
@carolynhu 

Thanks for the details. The rancher cli document misleading a lot.

>--env-file value, -e value    Specify a file from which to read environment variables. `File should be in yaml or json format` and suffixed with respective file extension.

https://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-up-reference

With your way, it works.
