### ISSUE TITLE
Rancher turns `docker:stable` image into `stable`

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#9773]
**Rancher versions:**
rancher/server: 1.6.7

**Steps to Reproduce:**
- create a service using `docker:stable` as the image

**Results:**
- rancher removes `docker:` and attempts to launch an image called `stable`

**Additional Data**
- it's possible to just run `docker`, so it's not a limitation on the image itself. It's something to do with `docker:`. It does it with any tag following `docker:`.

**Comment by superseb** [comment]
Can't seem to find a previous issue about this, will look further.

It's because we prefix with `docker:` and remove it later, like here: https://github.com/rancher/cattle/blob/master/code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instance/DockerInstancePostCreate.java#L45

Workaround till this is fixed is using `docker:docker:stable`

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
