### ISSUE TITLE
[rancher-dns?] Multiple links to single service with different aliases result in unexpected answers file.

### ISSUE THREAD

**Issue by lauvdk** [rancher/rancher#9781]
Multiple links to single service with different aliases result in unexpected answers file.

Could be rancher-dns or metadata.

**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: 0.11.2
network-services: (dns:v0.14.2, network-manager:v0.6.6, metadata:v0.9.1)
scheduler: 0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce (can provide `docker info` if needed)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 8 (jessie) - 3.16.0-4-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

In a service it's possible to link another service more than once with different aliases.

In this example I linked `target` from `source` with aliases `one` and `two`:
<img width="1068" alt="screen shot 2017-08-29 at 11 38 39" src="https://user-images.githubusercontent.com/1028110/29814980-72424ff4-8caf-11e7-9788-4326f40e6156.png">

Unfortunately only the last link appears in the answers file of our dns-container, where we expect both links to show up.

```
  "[ip-of-source-container]": {
    "search": [
      "multiple-links-dns-issue.rancher.internal",
      "linked.multiple-links-dns-issue.rancher.internal",
      "rancher.internal"
    ],
    "recurse": [],
    "authorative": [],
    "a": {
      "two.multiple-links-dns-issue.rancher.internal.": {
        "answer": [
          "[ip-of-target-container]"
        ]
      },
      "two.rancher.internal.": {
        "answer": [
          "[ip-of-target-container]"
        ]
      }
    },
    "cname": {}
  }
```

**Comment by vincent99** [comment]
Service links is a map.  The result is one key and the last one wins. And they also only support one target. 

If you want multiple targets you need to create an alias service and then point at that.

**Comment by lauvdk** [comment]
That workaround will probably work for us, thanks!

I still think this should be considered a bug, due to the possibility of adding multiple links in the frontend to 1 target. This should then also be limited.

**Comment by EyMaddis** [comment]
I would propose to reopen this issue.
Is the limitation to a map impossible to change?

In my scenario, I used the same service (a load balancer) to override the DNS entries for specific URLs (e.g. in test environments).
Both the UI and API indicate that this should be possible, but when actually making the requests, it will only work for one of the domains.
This can lead to very weird behavior.
Having Service Aliases helps, but is just a workaround, not a valid solution IMHO.

**Comment by 0ff** [comment]
+1 on that; in fact this is very misleading right now.
Either restrict it in the UI and the API or (preferably) make multiple links to the same target possible where it is not, as of today.

As routing does not change, it seems only rancher/rancher-dns must be changed to receive the correct answers.json, it that correct? (Just trying to figure out the impact of this issue and what would be needed to fix it)

**Comment by vincent99** [comment]
This has nothing to do with rancher-dns, the answer format is a map of key (fqdn) to *array of* records there so this is already supported (and how aliases and service records work).  You are taking about the API for defining links, which is a map of name to *single* target resource.

The API does not in any way indicate that  multiple is possible.  The type is `map`, and a map by definition has a unique key.  You cannot store `{x: 1, x: 2}` in JSON, YAML, or any common programming language and get both values back.

Changing the API is a breaking change for an uncommon use-case.  As I said, the supported way of doing this is an alias service.  Which also means you don't have to maintain the list of targets in multiple places if you want to use it in more than one service.

The UI on the other hand is manipulating an array  internally (because you have to be able to have e.g. multiple empty entries during editing) and  could scan through them all and show an error before it constructs the map sent to the API.

**Comment by 0ff** [comment]
Thank you for taking the time to explain that @vincent99, I really appreciate it!
There is one catch, though: I fear there's a misunderstanding of what we mean vs. what you see as a problem.

Please see this screenshot:
<img width="917" alt="screen shot 2017-09-01 at 18 32 14" src="https://user-images.githubusercontent.com/1755213/29979005-f6ae65b6-8f43-11e7-9498-bcb279a4dd8e.png">
This is, what we (@lauvdk, @EyMaddis and myself) are trying to accomplish - a *single* **target** (`Destination Service`) for *multiple* **fqdn**s (`As Name`) - as you've said, exactly what should be supported as of today.

And in fact, this is how the API stores this map:
<img width="193" alt="screen shot 2017-09-01 at 18 34 54" src="https://user-images.githubusercontent.com/1755213/29979068-44c502be-8f44-11e7-9a38-4c30c975606d.png">
Multiple keys (per fqdn) link to the very same target.

So I think we can agree that the intended behaviour would now be, that both `httpbin1` and `httpbin2` can be deleted independently from each other - right?

**Comment by eerootsus** [comment]
I would actually like to +1 this.

We are in the process of upgrading from Rancher 1.1.4 to 1.6.10 and when previously we could assign multiple names to a single service within one stack we no longer can. So this is already a broken change.

It's not about balancing one name between multiple containers, but about pointing multiple names to one stack.

In v1.1.4 this worked:
<img width="710" alt="screenshot 2017-11-28 19 31 15" src="https://user-images.githubusercontent.com/5171437/33334508-c1f02020-d472-11e7-87c6-0ef54bc92e8f.png">

In v.1.6.10 only the line beginning with api resolves correctly:
<img width="707" alt="screenshot 2017-11-28 19 32 08" src="https://user-images.githubusercontent.com/5171437/33334533-e554db32-d472-11e7-9c3c-21cb33597814.png">

**Comment by lauvdk** [comment]
@vincent99 you stated it has nothing to do with dns. Clear.

What would you need from us to re-open this issue? At this point there isn't even a warning in the UI when saving a configuration that will never work.

**Comment by vincent99** [comment]
I don't think I ever saw @0ff 's last message; yes it appears I read what you're trying to do backwards and that direction _should_ work (but does not).

Kubernetes has an equivalent for Service Alias (adding a record which is visible to all containers in the namespace).  But it does not have the concept of specifying dynamic or CNAME records that only apply to a a single deployment/pod (the equivalent of a rancher service).  So this whole whole capability doesn't really exist for 2.0.

So I can reopen it but given the situation it's unlikely to be prioritized to investigate or fix. (I'm guessing somewhere along the chain is flipping it to a representation of map of service->name instead of name->service)
