### ISSUE TITLE
"Start Once" container looks healthy after exiting with error

### ISSUE THREAD

**Issue by oliverlockwood** [rancher/rancher#9783]
**Rancher versions:**
rancher/server: v1.6.4
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: 
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.03.1-ce
 API version:  1.24 (downgraded from 1.27)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24 (minimum version )
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Irrelevant, I believe

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Irrelevant, I believe

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Irrelevant, I believe

**Environment Template: Cattle**

**Steps to Reproduce:**
Start a container (which will exit with a non-zero return code) with the label `io.rancher.container.start_once: 'true'` set in `docker-compose.yml.

**Results:**
The container appears green in the Rancher GUI with status `Started-Once` - even though it failed.

This was raised in the forums here:
https://forums.rancher.com/t/start-once-container-looks-healthy-after-exiting-with-error/4121

Someone called Vincent - perhaps @vincent99 ? - said:
> I think it's saved somewhere in the database but we do not currently expose the exit code or change the state based on it.

We're finding it very misleading that a started-once container, which we rely on having run, effectively appears as a silent failure until you look into it using `docker ps -a` and see that the status there is described as `Exited (1)`.

Is there a plan to change this behaviour at all?

**Comment by vincent99** [comment]
It's already changed for what will be 2.0; exit code is exposed, the stopped state color is based on it in the UI, and start_once no longer exists (except for backwards compatibility) because services support all the regular container restart policies.  So the equivalent is `restart: never`, but what many people really wanted I'm the first place is `restart: on-failure`.

It will not be changing for 1.x. While you may not like what the behavior is, I don't see how it's confusing.  It starts the container once and makes no claims of observing the exit code nor  offers any options to do anything based on it.

**Comment by oliverlockwood** [comment]
Hi Vincent - thanks for responding to this so quickly.  Sounds like I'll have to look forward to the release of 2.0 in Q4 2017 then :smiley:

I'll close the issue as now it's clear to me what the roadmap is in this area.  Cheers.
