### ISSUE TITLE
K8S - Replace hosts "Evacuate" option with correct K8S options "Drain", "Uncordon"

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#9789]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): rancher/k8s:v1.7.2-rancher7

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"

4.8.0-58-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, external MySql DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Go into a k8s env, goto the "Hosts" view, on a host with user pods (compute=true) click the ellipsis and select "Evacuate".

**Results:**
View the user pods being deleted, then magically re-created.  Apparently "Evacuate" is not a valid function in a k8s env.  The correct functions are "Drain" and "Uncordon", would be great to see those in place of "Evacuate" in k8s envs.

[https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)

**Comment by pulberg** [comment]
Am I understanding this correctly, that this is *not* going to be addressed in Rancher v1.6.xx?

**Comment by vincent99** [comment]
Yes; In general 1.x is being maintained with important bug fixes and a few commitments to customers, but otherwise most of the company is focused on 2.0 and any significant new functionality will be only in 2.0.

**Comment by Darkknight33** [comment]
While the actual function definitely needs to be fixed, I want to put in my $.02 regarding UI wording changes:

What user skill & level of abstraction is Rancher targeting? 'Evacuate', while not platform correct terminology is a more self explanatory action compared to 'Drain'. I'll be honest I really don't even know what 'Uncordon' is supposed to mean in this context. In the visual metaphor of shipping containers as pods, they don't really get "drained". If Rancher's raison d'etre is supposed to be making container & stack management more accessible, then that needs to carry over to UI terminology as well. 

You're telling your 1.x user base that the switch to K8s will not require staff to be retrained. If you're going to be relabeling interface functions from 1.x to suit a new underlying platform, I don't see how extra training for those already familiar with Rancher 1.x, but not K8s is going to be avoided. 

The simplest approach would be to avoid the specific terminology and take a very literal, platform agnostic approach to naming conventions in the UI. In this case, 'Unload Host' seems to me to be the least complicated way of explaining what that button does without asking a user to learn yet another product's attempt to cutely describe what is actually a common management function. You should read some of the github discussions on their terminology choices. Someone actually suggested "Stevedore" 
or "Hyperetes" in place of 'Minion' for what is ultimately just a node. Those kind of esoteric references is not something Rancher needs.

If users don't know K8s, then "unload host" should still make sense. If they do know K8s, it should also still make sense because it's so direct. If users more familiar with K8s feel like they need a button that perfectly matches the correct platform function name for clarity, I suggest putting it on an API screen with the platform appropriate label. ;-)

**Comment by vincent99** [comment]
2.0 (preview2+) will use the kubernetes terms where they are reasonably descriptive and we like them (e.g. node vs host), and our previous terms or something new where we don't (e.g. I will roll in my grave before showing you a `preferredDuringSchedulingIgnoredDuringExecution` affinity rule).

This particular one is fairly arbitrary and nobody really fully understand what any of those terms mean the first time, so the confirm dialog already explains what it will do in more detail.

**Comment by deniseschannon** [comment]
Closing in favor of #13623 for 2.0.
