### ISSUE TITLE
adding label to a host in rancher removes existing taint(s) in k8s node

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9800]
**Rancher versions:**
rancher/server: v1.6.7
kubernetes: v1.7.2

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rhel 7.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
ha

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
start with cattle, label hosts, launch k8s stack

**Steps to Reproduce:**
prereq: k8s is up and running
1. taint nodes
2. update host that has a taint, with a label via the rancher UI
3. describe node with updated label

**Results:**
node taint disappears after label is updated.

**Comment by alena1108** [comment]
Looks like kubernetes-agent labels sync up code is responsible for the taint disappearance. It is because github.com/rancher/kubernetes-model package that kubernetes-agent uses, is pretty outdated. The taint field is not being returned upon the host retrieval due to older version not having it, so when we do host.replace with the rancher label, taints are being passed as null and replace whatever is set on kubernetes ndoe. We should either:

1) Update kubernetes-model to use the latest kubernetes apis.
2) Consider switching kubernetes-agent to https://github.com/kubernetes/client-go (pointing to the latest k8s version)

**Comment by alena1108** [comment]
Should be fixed with rancher/kubernetes-agent:v0.6.6

**Comment by galal-hussein** [comment]
kubernetes agent version: rancher/kubernetes-agent:v0.6.6

Tested the scenario:

- taint nodes
- update host that has a taint, with a label via the rancher UI
- describe node with updated label

I can see the taint is still available even after i updated the labels or adding a new label via the Rancher UI.
