### ISSUE TITLE
Rancher does not move services when hosts are disconnected

### ISSUE THREAD

**Issue by typia** [rancher/rancher#9856]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.7
network-services: 0.7.7 (metadata 0.9.3)
scheduler: 0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 8 (jessie)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware esxi VMs
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
My hosts happen to have kernel panics due to CPU usage.
Rancher lists them as disconnected, but it doesn't move the machines which are on the machine
**Results:**
I'm pretty sure in previous versions when my hosts were disconnected, rancher moved automatically the services to another host.
It doesn't move it anymore

**Comment by deniseschannon** [comment]
Rancher will only move containers to another host if they have healthchecks configured on them. With healthchecks, Rancher will realize that Rancher cannot access these containers on the disconnected hosts and re-launch them on new hosts. But without the healthcheck, Rancher doesn't know the status of the container. It only knows that the rancher/server and rancher/agent containers can't communicate with each other, which is why the host is disconnected. 

http://rancher.com/docs/rancher/v1.6/en/cattle/health-checks/

**Comment by typia** [comment]
Hi Denise,
thanks for your input.
So it's a normal behaviour. I'm pretty sure in previous versions of rancher (before evacuate feature), when host was disconnected rancher moved the containers by itself.

Many thanks

**Comment by vincent99** [comment]
It has always worked the same way.

**Comment by typia** [comment]
Thanks a lot @deniseschannon and @vincent99

**Comment by aijanai** [comment]
hi guys, sorry for relighting this up, but in a Kubernetes environment this is misleading and even a little dangerous: I expect to have all my pods to be migrated somewhere else when I evacuate a host.
Currently, Rancher basically ignores a host evacuation when in a K8s environment.

Either we fix the behaviour or we disable that button as meaningless.

Many thanks for your work and dedication
