### ISSUE TITLE
Github API rate limit exceeded

### ISSUE THREAD

**Issue by dhrp** [rancher/rancher#9867]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: rancher/agent:v1.2.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): Current: v1.6.6-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
contaierOS / 4.12.10-coreos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Environment template: Cattle, infrastructure stack: Kubernetes

**Steps to Reproduce:**

* Setup Github autentication
* Let a process make many calls to Kubernetes through the rancher API, OR use the rancher API many times, for example when a host is trying to join a cluster, but something is misconfigured and it retries every few seconds.

**Results:**
I (the admin) can no longer login, because GitHub has rate-limited the amount of authentication requests allowed to make against Github. This is fair, but it's the second time we got bit by this issue. The first time was probably due to a lot of API requests our service made. The second time it was due to a host trying to join too many times. 

You get loads of lines like:
```
time="2017-09-13T03:25:07Z" level=error msg="Github getTeamByID: GET url https://api.github.com/teams/2467068 received error from github, err: Request failed, got status code: 403. Response: {\n  \"message\": \"API rate limit exceeded for dhrp.\",\n  \"documentation_url\": \"https://developer.github.com/v3/#rate-limiting\"\n}\n" 
```

**Proposed solution**
Perhaps Rancher should apply rate-limiting (under Github's limits), *and for Github only*, and a clear warning should be given to the user, api consumer.

That it happens is also weird. Can't we do something like caching credentials for 10 minutes? That may be a better solution.

**Comment by vincent99** [comment]
Github was the first (and for a long time, only) auth provider added and is the 2nd most used (after local)... but this is the first I've ever heard of hitting rate limits, they're mostly 5000/hr so that's averaging at least 1.4 requests/sec.

Host registrations (and related operations) are authenticated by the registration token or the host-specific API key.  They aren't tied to any auth provider-specific identity, so there shouldn't be any Github requests at all involved.

Using the kubernetes API to make a lot of requests sounds more plausible, (though the information should already be getting cached).  @cjellick probably need someone to look at the interaction between auth-service and k8s RBAC.

**Comment by dhrp** [comment]
It looks like this was indeed caused by an error on our side (something of a complicated feedback loop). I'll close this issue as we'll need to fix it on our side. It has shown though that each call to kubernetes must result in a call to GitHub.
