### ISSUE TITLE
was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint

### ISSUE THREAD

**Issue by rgruyters** [rancher/rancher#9900]
**Rancher versions:**
rancher/server: v1.6.9
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: 0.11.9
network-services: 0.7.8
scheduler: 0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.45-rancher
Operating System: RancherOS v1.1.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: rancher-server
ID: XPMN:PGHN:JMNG:MOGM:DXDW:3W6M:ZOIC:TQNK:DA2Y:5UVS:PT2F:WFXC
Docker Root Dir: /mnt/data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="RancherOS"
VERSION=v1.1.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.1.0
PRETTY_NAME="RancherOS v1.1.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

```
4.9.45-rancher
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Open the "View Logs" or "Upgrade" for the second time.
Close the browser and reconnect it goes fine and works as promised. (one time though)

**Results:**
When using Traefik as a frontend proxy for Rancher Server, I noticed that sometimes we see the following message in the Inspector:

```
fetch.js:404 Mixed Content: The page at 'https://rancher-server.local/env/1a8/apps/add-service?serviceId=1s64&stackId=1st34&upgrade=true' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://rancher-server.local/v2-beta/projects/1a8/services/1s64'. This request has been blocked; the content must be served over HTTPS.
```

Here is my Traefik configuration:
```
[web]
# Web administration port
#
# Required
#
address = ":8080"

# SSL certificate and key used
#
# Optional
#
CertFile = "/etc/traefik/traefik.crt"
KeyFile = "/etc/traefik/traefik.key"

# Set REST API to read-only mode
#
# Optional
ReadOnly = true

debug = true
logLevel = "debug"


# Entrypoints definition
#
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  proxyprotocol = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/traefik.crt"
      keyFile = "/etc/traefik/traefik.key"


################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
domain = "docker.dev"

# Enable watch docker changes
#
# Optional
#
watch = true

# Override default configuration template. For advanced users :)
#
# Optional
#
# filename = "docker.tmpl"

# Expose containers by default in traefik
# If set to false, containers that don't have `traefik.enable=true` will be igno                                                                                                                           red
#
# Optional
# Default: true
#
exposedbydefault = false

# Use the IP address from the binded port instead of the inner network one. For                                                                                                                            specific use-case :)
#
# Optional
# Default: false
#
usebindportip = true

# Use Swarm Mode services as data provider
#
# Optional
# Default: false
#
swarmmode = false
```

**Comment by vincent99** [comment]
I don't know enough about traefik config in detail to tell you what's wrong, but the result you're seeing is that PROXY protocol info isn't being sent to Rancher (or is wrong somehow).  It seems odd that it's on the front-end configuration instead of the target, that sort of suggests they support *receiving* the proxy line, not constructing and sending it out.

The Rancher API returns absolute URLs and needs to be given enough information (via PROXY protocol or X-Forwarded- headers) to reconstruct the fill original request URL.  What's happening is for performance the UI assumes the request URL of the initial set of things loaded, but when you do something else later like an action those go to the URL the server returned, which says `http://`.

ELB support for AWS also requires PROXY protocol, so we know support works for it in general.

**Comment by rgruyters** [comment]
@vincent99 thanks for the update. I will post an issue in the Traefik project as well just to be sure.

**Comment by sergesvr** [comment]
I am having the same issue. The problem is that it is happening from time to time. 

In fact, once i refresh my browser, the problem is gone for a few minutes then comes back.

FYI, here is my traefik config:

defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true
providersThrottleDuration = "5s"
[respondingTimeouts]
idleTimeout = "360s"

# Entrypoints, http and https
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.proxyProtocol]
    trustedIPs = ["0.0.0.0/0"]
    [entryPoints.http.forwardedHeaders]
    trustedIPs = ["0.0.0.0/0"]
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.proxyProtocol]
    trustedIPs = ["172.31.0.0/16","127.0.0.1/32"]
    [entryPoints.https.forwardedHeaders]
    trustedIPs = ["172.31.0.0/16","127.0.0.1/32"]
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "contact@rancher.example.com"
storage = "/acme.json"
entryPoint = "https"
onDemand = false
onHostRule = false
acmeLogging = true
#dnsProvider = "route53"
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
[[acme.domains]]
main = "rancher.example.com"
sans = ["dev.rancher.example.com"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "rancher.example.com"
watch = true

As you can see, I wildly opened the endpoint to work with the proxy protocol but did not solve the issue. So that i would guess the problem looks more on rancher side.

**Comment by vincent99** [comment]
As I said above, I think you guys are configuring traefik to **receive** a request containing proxy protocol header, not to **send** one to the target process.  The rancher/server container needs to be given enough information to reconstruct the original request URL so that it can return absolute URLs in the response.  The UI is just following the links that are returned.

**Comment by superseb** [comment]
See here for a workaround and long-term solution: https://github.com/rancher/rancher/issues/9726
