### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#9905]
I know this situation has been discussed, but still I'm getting the following error when trying to add my first host in AWS:
TypeError: Cannot read property 'name' of undefined

The rancher container is running on an AWS. I've validated my access and secret keys are good. From the Chrome debug tool, I'm seeing the following information: 
Request URL:http://myrancher.com:8080/v2-beta/proxy/ec2.us-east-1.amazonaws.com/
Request Method:POST
Status Code:400 Bad Request
Remote Address:52.7.4.172:8080
Referrer Policy:no-referrer-when-downgrade

Looking at the v2-beta API in rancher, "proxy" is not a valid path, so maybe that's related. 

**Rancher versions:**
Component | Version
Rancher | v1.6.9
Cattle | v0.183.21
User Interface | v1.6.23
Rancher CLI | v0.6.4
Rancher Compose | v0.12.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.38-16.35.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: ip-10-11-0-30
ID: NE7Y:GOXT:QKO2:XEBN:FRVA:SNXB:YU5P:T2HY:ZGVH:VHZE:HSNI:PROD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.03"
PRETTY_NAME="Amazon Linux AMI 2017.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

uname -r
4.9.38-16.35.amzn1.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Add the first host
**Results:**
TypeError: Cannot read property 'name' of undefined

**Comment by vincent99** [comment]
`/proxy/{whitelisted hostname}` is part of the API but not in the documentation because there's no reason for users to use it directly.  The UI uses the AWS JS client to talk to their API and do things like list your VPCs.  Requests from a page on one domain (`your-rancher.com`) to another (`ec2.*..amazonaws.com`) are not generally directly allowed, so the server container proxies the request from browser <-> rancher/server -> provider API.

You need:
  - Valid api keys
  - That are usable from the server container's IP
  - And have permission to perform basic EC2 operations (DescribeVPCs is the first one)
  - And an accurate clock on the computer running the browser (AWS auth uses time-based signatures).

Open up the network tab of the browser developer tools and grab the complete request and response headers & body.  x-out the content of authorization headers.

**Comment by eebjr** [comment]
Thanks Vincent. I think it was a role problem on my instance.  I'm past this block and on to the next: 
"transitioningMessage": "Error setting machine configuration from flags provided: RequestError: send request failed"

I'll look around the forum...
