### ISSUE TITLE
Groups not working with ActiveDirectory

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#9924]
Rancher Version: rancher/enterprise.v.1.6.10

I only can see two AD groups instead of all. People in that 2 group can't log in at all.

This all happened after an upgrade from 1.3.4 to 1.6.10

**Comment by Daxten** [comment]
https://github.com/rancher/rancher/releases/tag/v1.6.10

Starting with v1.6.8, Rancher has updated the Active Directory auth plugin and moved it into the new authentication framework. We have also further secured the AD+TLS option by ensuring that the hostname/IP of the AD server matches with the hostname/IP of the TLS certificate. Please see [#9459] for details.

Due to this new check, you should be aware that if the hostname/IP does not match your TLS certificate, you will be locked out of your Rancher server if you do not correct this prior to upgrading. To ensure you have no issues with the upgrade, please execute the following to verify your configuration is correct.

Verify the hostname/IP you used for your AD configuration. To do this, log into Rancher using a web browser as an admin and click Admin -> Access Control. Note the server field to determine your configured hostname/IP for your AD server.
To verify your the configure hostname/IP for your TLS cert, you can execute the following command to determine the CN attribute:
openssl s_client -showcerts -connect domain.example.com:443
You should see something like:
subject=/OU=Domain Control Validated/CN=domain.example.com
Verify that the CN attribute matches with your configured server field from the above step.

**Comment by Toonix** [comment]
I connect without TLS on port 389 and user authentication is working. I can disable AD Authentication and turn it back on...everything ok. I tried to connect with TLS but looks like firewall is blocking or they don't have a certificate.

**Comment by mrajashree** [comment]
@Toonix so is the issue resolved when you switched to non-TLS? Were you using TLS in 1.3.4?

**Comment by Toonix** [comment]
No its not resolved. Group dosn't work.

I never used tls not in 1.3.4 and not in 1.6.10

**Comment by mrajashree** [comment]
@Toonix Can you share rancher/server logs?

**Comment by Toonix** [comment]
I'm currently home, but there wasn't any information in the logs. It just said ldap profile updated...I didn't see any failures at all.

**Comment by Toonix** [comment]
Oh, I forgot I also have an installation with 1.6.7 which is working fine. Also without TLS and same AD Server as with the 1.6.10

**Comment by mrajashree** [comment]
@Toonix can you turn on debug logs by setting auth.service.log.level to DEBUG in v2-beta/settings, and then try login again and then share the logs you get

**Comment by Toonix** [comment]
sure..but you need to wait till tommorow..I'm from Switzerland and it's 7:57pm now here

**Comment by Toonix** [comment]
Provided the logs over email, because I don't want to make them public here.

**Comment by Toonix** [comment]
I found a other bug...when I add users to https://url/admin/access/activedirectory and then stop Rancher and restart it, all changes are lost.

**Comment by mrajashree** [comment]
@Toonix I'm taking a look at the logs, meanwhile I could not reproduce your second bug. 
1. I setup AD auth on 1.6.10, I added users via `admin/access/activedirectory` and hit `Save`
2. I then stopped and started rancher/server.
The added users were still there

**Comment by Toonix** [comment]
@mrajashree since the group didn't work I added the user directly, this way they can log in. So yes I pushed safe, else it would not have worked, correct? Then I stopped rancher and restarted it, and it was reverted back like it was after the migration from 1.3.4. Looks like it didn't get into the database.

**Comment by Toonix** [comment]
Adding Group Search Base, solved the login problem, but when I open "Authorized Users and Organizations" dropdown box it's still empty.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
