### ISSUE TITLE
[ipsec] Retry logic for failed/deleted SAS

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9971]
Problem:
I just got a chance to do a screenshare with one of our open source users who reported IPSec problems. Debugging his setup, the tunnel between two of his servers had some problems. The packets from one end were reaching the other server, but the response was not reaching. Due to this after 5 retries, the SA got deleted.

Solution:
We should have a new goroutine in IPSec which is monitoring the status of all the SAs and expect them to be in "ESTABILISHED" state. If they are not and deleted, currently there is no logic to retry/reinitiate the SA but we should re-initiate the connection.

**Comment by hilkeheremans** [comment]
Thanks for digging this up. We are also experiencing this issue.

**Comment by leodotcloud** [comment]
Fixed in ipsec:0.2.0 with image rancher/net:v0.13.2, targeted for v1.6.11 release.

**Comment by sangeethah** [comment]
Was able to reproduce the issue using rancher/net:v0.13.1 where when  connection between 2 hosts was lost and then restored after few minutes , ipsec connection between the 2 host never get re-established.

Steps that were followed to simulate the issue:

Drop connection between 2 hosts using iptable rules

```iptables -I FORWARD -d <hostip> -p udp -m udp --dport 500 -j DROP```
```iptables -I FORWARD -d <hostip> -p udp -m udp --dport 4500 -j DROP```

After 5 retransmit errors , ipsec connection between the 2 hosts gets dropped 

```swanctl --list-sas | grep <hostip>``` would be return no rows

Restore  connections between 2 hosts by deleting the rules that were created to drop connections.

Even after connection is restored , connection between containers from these hosts continues to be broken. ipsec connection between the 2 hosts does not get re-established. ```swanctl --list-sas | grep <hostip>``` would be return no rows.

When the same tests were done using rancher/net:v0.13.2  (using rancher/server:v1.6-development) , once the connection was restored between hosts , connection between containers from these hosts is restored in the next few seconds.

Even when connectivity between the hosts are down , ipsec connection between the 2 hosts get re-established in few seconds after they get dropped due to retransmission errors.

**Comment by ibrokethecloud** [comment]
I have recently run into the same issue as well after upgrading to v1.6.10

**Comment by leodotcloud** [comment]
@ibrokethecloud the issue has been fixed in v1.6.11 release.

**Comment by whisper-bye** [comment]
same issue in v1.6.14
2/8/2018 1:43:35 AMRefer to router sidekick for logs
2/8/2018 5:50:01 PMRefer to router sidekick for logs
2/8/2018 5:50:01 PMmkfifo: cannot create fifo 'f': File exists

**Comment by superseb** [comment]
`mkfifo: cannot create fifo 'f': File exists` is not a message which should cause problems, if you experience issues, please file a new issue with the behavior and the used versions.

**Comment by zlcolin** [comment]
root@hs228151:~# docker ps                                                                 
CONTAINER ID        IMAGE                             COMMAND                  CREATED     
e99f1eb1b9f7        rancher/storage-nfs:v0.8.5        "start.sh storage ..."   14 hours ago
56f05f2eede7        rancher/net:v0.13.7               "/rancher-entrypoi..."   14 hours ago
6a832fce5247        rancher/net:v0.13.7               "/rancher-entrypoi..."   14 hours ago
1f3bf6a1c032        rancher/dns:v0.15.3               "/rancher-entrypoi..."   14 hours ago
2d90eb1d9279        rancher/net:holder                "/.r/r /rancher-en..."   14 hours ago
6480fb27e13f        rancher/metadata:v0.9.5           "/rancher-entrypoi..."   14 hours ago
5c0be9b1d93c        rancher/healthcheck:v0.3.3        "/.r/r /rancher-en..."   14 hours ago
e6014b14d3ff        rancher/network-manager:v0.7.19   "/rancher-entrypoi..."   14 hours ago
54b3a5b61acb        rancher/net:v0.13.7               "/rancher-entrypoi..."   14 hours ago
745ad5ce707f        rancher/agent:v1.2.9              "/run.sh run"            14 hours ago
0d3c02051280        rancher/server:stable             "/usr/bin/entry /u..."   14 hours ago
root@hs228151:~# docker logs -f  2d90eb1d9279                                              
Refer to router sidekick for logs                                                          
^C                                                                                         
root@hs228151:~# docker exec -it 2d90eb1d9279 /bin/bash                                    
root@2d90eb1d9279:/# sh -c echo Refer to router sidekick for logs; mkfifo f; exec cat f    
                                                                                           
mkfifo: cannot create fifo 'f': File exists                                                
                                                                                           
same issue in v1.6.14  rancher/net:v0.13.7

**Comment by leodotcloud** [comment]
```
mkfifo: cannot create fifo 'f': File exists
```

This is not an error! This message can be ignored.
